### ISSUE TITLE
web UI/tsh agent forwarding

### ISSUE THREAD

**Issue by bcg62** [gravitational/teleport#1000]
currently agent forwarding works with openssh client if `forward_agent: true` is specified in a role configuration.

As far as i can tell there's no way to configure tsh ssh to forward agents to destination nodes like you can with ssh_config

Also the web UI does not give the user an agent and or provide a way to access their current certs, effectively making it not possible to jump hosts.

**Comment by russjones** [comment]
@kontsevoy What should the UX here? The role has an option to allow forwarding or not, but in the Web UI at the moment we don't know if the user wants agent forwarding or not.

Usually command line tools will allow you to toggle forwarding on or off (like `ssh -A`), do we want to add a similar toggle to the Web UI?

**Comment by bcg62** [comment]
@russjones this is a more general issue for windows users who do not have the cmdline options to effectively forward auth. It blocks them from usescases where this is required.

Generally speaking it would probably make sense to have a way to enable it for all connections where it's allowed or on a connection by connection basis.

Either way it would be nice if the UI matched functionally that's allowed via the role and ssh/tsh options.

Worth noting there's also currently not a way to enable forwarding via tsh ssh, you have to use open ssh client. There's a separate issue open for this.

**Comment by kontsevoy** [comment]
to be discussed internally.
