### ISSUE TITLE
Explain Access Role and add Session Recording to Access Role

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#10001]
### What
[Teleport 8.0.0](https://github.com/gravitational/teleport/releases/tag/v8.0.0) made changes to roles. New clusters will no longer have the default `admin` role, it has been replaced with 3 smaller scoped roles: `access`, `auditor`, and `editor`. These roles follow the practice of least privilege, when starting a new cluster. I'll add a new user like this 

```
tctl users add teleport-admin --roles=editor,access --logins=root,ubuntu,ec2-user
``` 

It would be good to introduce some of the concepts around `{internal`

```diff
kind: role
metadata:
  description: Access cluster resources
  name: access
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    db_names:
-    # Note: How to set {{internel.db_names}}
-    # - "prod-db"
    - '{{internal.db_names}}'
    db_users:
-    # Note: How to set {{internel.db_users}}
-    # - "rds-user"
    - '{{internal.db_users}}'
    kubernetes_groups:
-    # Note: How to set {{internel.kubernetes_groups}}
-    # - "system:authenticated"
    - '{{internal.kubernetes_groups}}'
    kubernetes_labels:
      '*': '*'
    kubernetes_users:
-    # Note: How to set {{internel.kubernetes_users}}
-    # - system:authenticated"
    - '{{internal.kubernetes_users}}'
    logins:
-    # Note: How to set {{internel.logins}}
-    # - "debian"
    - '{{internal.logins}}'
    - ubuntu
    node_labels:
      '*': '*'
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
+    - resources:
+     - session
+      verbs:
+      - list
+      - read
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```

### How
How would you implement this?

### Why
Why do you need this?

### Workaround
If a workaround exists, please include it.

**Comment by zmb3** [comment]
@benarent is this a feature request or a request for better docs?

**Comment by benarent** [comment]
@stevenGravy Fixed a few of these with https://github.com/gravitational/webapps/pull/644/files... but this is for a new roles created from the UI. I think we can close now, and re-open a new issue for extra details.
