### ISSUE TITLE
Add Auto-installer to Teleport Communtiy Edition

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#10000]
### What
We currently provide an easier install script for Cloud and Enterprise users, We don't have the script available to OSS users. This would make setup much easier.

#### Community Edition
![image](https://user-images.githubusercontent.com/559288/151453282-95981e3a-891b-45ba-a8e8-013dd4480b62.png)

#### Enterprise Edition 
![image](https://user-images.githubusercontent.com/559288/151453376-71b09819-f78f-4e23-8bb2-22c55b3497c9.png)

### How
I believe this was left out because some it was tied to the enterprise edition, but there is nothing specific to enterprise in the script. 

### Why
Help with time to first value.

**Comment by russjones** [comment]
@hatched This needs to be backported to `branch/v8` and `branch/v9`. Cloud is on Teleport 8.
