### ISSUE TITLE
Approved access requests should get locked when deleted or denied

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport#10018]
### What
Deleting an access request in an APPROVED state or changing an access request's state from APPROVED to DENIED while it's still not expired should trigger a lock that covers the remaining period of validity of the access request.

### Why
Without a lock, privileges escalated while the access request was approved can be maintained for longer than the existence of the access request itself (see TEL-Q321-8 - although at the time we had essentially no visibility on what users were doing with access requests, now we have access requests in every user-initiated log event and an event for access request deletion).

Locking on denial is for consistency, even though right now the only way to transition an access request from APPROVED to DENIED is to use admin access through `tctl`, so adding a lock manually is already a possibility there. At the moment, reviewers cannot deny an approved access request, but this could be changed.

**Comment by russjones** [comment]
Show a user hint when changing state from APPROVED to DENIED or deleting the access request telling them that if they want to lock out any users that may have been granted access they want to also lock the user with an example command.

**Comment by hatched** [comment]
Should I also add a warning to the `tctl` command when performing this same action?

**Comment by hatched** [comment]
A warning will be added to the UI and the `tctl` command with an example command on how to complete a lock on the account.

In the future we might want to add an option in the UI when performing this action to lock the account for the admin.
Related: https://github.com/gravitational/teleport/issues/11147
