### ISSUE TITLE
Windows installer for Desktop access configuration

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#10027]
### What
Provide a windows executable that can confirm windows as required to allow a Teleport desktop service to connect.  The tool should also give a method to validate desktop access. 

### How
An executable that connects to Teleport and can install the required windows configuration. 

### Why
There are multiple steps required steps to add in RDP enablement.  Having a tool that can achieve this easily will speed installation and reduce errors from manual steps. 

### Workaround
Developer powershell and other scripting.

**Comment by zmb3** [comment]
Possible dup of #8805 (different solution to same problem)

**Comment by zmb3** [comment]
Released new install scripts in 10.2.4.
