### ISSUE TITLE
Add example IAM policy to S3 backend docs

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#10055]
## Details
The S3 backend guide (https://goteleport.com/docs/setup/reference/backends/#s3) should have an example AWS IAM policy alongside it.

Here's an example from our Terraform: https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/ha-autoscale-cluster/auth_iam.tf#L131-L153

### Category
- Improve Existing

**Comment by zmb3** [comment]
This was completed: https://goteleport.com/docs/reference/backends/#s3-iam-policy
