### ISSUE TITLE
MySQL DB access documentation should mention mysql_listen_addr

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#10051]
## Details
The current [self-hosted MySQL guide](https://goteleport.com/docs/database-access/guides/mysql-self-hosted/) does not mention `mysql_listen_addr` at all. It should, because this is required to proxy MySQL access via the Teleport proxy and users get a `connection refused` error without it set.

### Category
- Improve Existing

**Comment by ptgott** [comment]
@webvictim Just checking whether this is still the case. In the source, I see that `onDatabaseConnect` [calls `dbcmd.NewCmdBuilder`](https://github.com/gravitational/teleport/blob/f6938613d2527be2def7c2bbfcc817596fb2e44e/tool/tsh/common/db.go#L769), which calls [`*Config.DatabaseProxyHostPort`](https://github.com/gravitational/teleport/blob/f6938613d2527be2def7c2bbfcc817596fb2e44e/lib/client/api.go#L916), which looks like it reads the cluster's `mysql_listen_addr`. In other words, from what I understand, the reader wouldn't need to set a `mysql_listen_addr` explicitly unless they want to change the default.

**Comment by webvictim** [comment]
I'm going to say that this has probably been fixed or just deprecated through change now, so we can close it.
