### ISSUE TITLE
Teleport RBAC UI improvements

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1006]
[EDIT] ekontsevoy: this issue needs to be updated to reflect changes made in #1200 

## Description
There are a couple of improvements we should to to improve the UX for RBAC

### Hide Sessions Tab

When Teleport User can not view the sessions in teleport, UI should not display processing error, simply hide the sessions tab.

### Display logins according to cluster local roles

Currently list of user's logins is displayed according to user's local roles. However on the remote cluster
user may not be authorized to login as certain principal. Modify the UI to only show the logins allowed on the current cluster, not the local cluster.

**Note** This will need a bit of backend work as well - as we should add extra web server call to check for cluster-local roles for user. We should also gracefully handle the case when older backends do not have this API handler and simply default to old behavior on 404

**Comment by kontsevoy** [comment]
This has  been done IMO
