### ISSUE TITLE
Add missing entries to the Resources reference

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#10065]
## Details
Let's make sure that any dynamic config resources you can create are documented in the [Resources reference](https://goteleport.com/docs/setup/reference/resources/). For example, `cluster_auth_preference` is missing. 

If it's easier to generate the dynamic config reference automatically in order to keep it comprehensive, we can look into that as well.

### Category

- New Feature
- Improve Existing
- Remove Outdated

**Comment by zmb3** [comment]
Closing as duplicate of #9949
