### ISSUE TITLE
Updating a users roles with tctl doesn't take effect immediately

### ISSUE THREAD

**Issue by liath** [gravitational/teleport#10071]
### Description

**What happened**:
I removed a user's role but they can still access a database that the role granted access to. I'm guessing `tsh login` caches a cert with these roles and the user will retain access until they re-login or the cert expires. That's kind of problematic as you would expect a revocation to be instant. The flip side is also true fwiw, role grants don't take effect until the user logs in again; which is kind of annoying.

**What you expected to happen**:
Removing access should apply immediately.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a user with a role granting db access and `tsh login` as it
2. Run `tsh db connect xxx` to login to database
3. Revoke role via tctl ```tctl get user/the_user | yq '.spec.roles = []'  | tctl create -f```
4. Observe that `tsh db connect xxx` still connects despite the user no longer having the role

### Server Details
- Teleport version (run `teleport version`): Teleport v8.1.1 git:v8.1.1-0-g8d1547212 go1.17.3
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS (via docker image quay.io/gravitational/teleport:8)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Client Details
- Tsh version (`tsh version`): Teleport v8.1.1 git:v8.1.1-0-g8d1547212 go1.17.3
- Computer OS (e.g. Linux, macOS, Windows): macOS 11.6.2
- Browser version (for UI-related issues): n/a
- Installed via (e.g. apt, yum, brew, website download): tsh-only pkg installer
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- db:service debug log show identical values for the `Client identity:` line on `tsh db connect` between attempts with role and after removing it.

**Comment by tpang-ameame** [comment]
Hi @liath @stevenGravy Any updates to this issue?

**Comment by tpang-ameame** [comment]
If a SAML user login, is there a way to refresh the certificate if the user .spec.roles are updated? (just like the certificate updates after access request approval)

**Comment by zmb3** [comment]
This is working as intended. Roles are encoded in the cert at time of login.

> That's kind of problematic as you would expect a revocation to be instant

For cases where you need instant revocation, locking should be used.
