### ISSUE TITLE
Run CI when base branch is not master or release branch

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#10090]
### What
I would like to have CI run on my PR, even when the base branch is not `master` or a release branch.

### How
Change the settings in Google Cloud Build.

### Why
I often split larger units of work into multiple PRs for logical separation and easier review. When these PRs depend on each other, the base branch will be the previous branch in a possible chain of branches for this feature.

It's useful to have CI run on these branches. Even if they are currently not going to merge to master or a release branch immediately, the code eventually will. It is better to catch any issues early.

### Workaround
Run all CI steps locally. The downsides to this are:
1. it's common to forget certain steps (lint, integration tests)
2. some tests do not run locally, or must run within docker and require extra dependencies or databases
3. some integration tests are very slow, and if there is a small chance of breaking them for a given change it's convenient to leave these for CI
4. running tests in docker on Mac is very slow
4. the local environment is always going to be slightly different than the CI environment

**Comment by wadells** [comment]
We no longer use GCB.  I believe that our current GHA CI will run on PRs that don't target `master`/release branches.
