### ISSUE TITLE
Teleport does not set ~/.tsh/profile with OIDC

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1013]
## Description

When using OIDC or SAML auth preference, `~/.tsh/profile` is not set, this leads request to relogin every time user tries to SSH in.

### Steps to reproduce

* version: `2.2.0-alpha.8`
* set auth preference to OIDC
* SSH using `tsh --debug --proxy=localhost ssh localhost`

the `~/.tsh/profile` is not set.

**Comment by russjones** [comment]
Closing this because as covered in https://github.com/gravitational/teleport/issues/1044 the current behavior is correct.
