### ISSUE TITLE
Expose Teleport CAs to unauthenticated users

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#10132]
### What

It should be possible to grab the host and user ca directly from the teleport endpoint without logging in.

### How

Implement an endpoint such as /ca/user.crt and /ca/host.crt

### Why

When setting mongodb access, only the certificate authority file is needed. This would be easy to automate setup if the certificate authority could simply be pulled from an https endpoint as opposed to running a privileged command to export it.

### Workaround

Manually run the command to get the certificate authority and copy it to where it needs to go.

gz#3913

**Comment by russjones** [comment]
Add CA pin to find endpoint.
