### ISSUE TITLE
[v.8.0] /docs/pages/application-access/guides/connecting-apps.mdx

### ISSUE THREAD

**Issue by leonardglaeser** [gravitational/teleport#10137]
Hi ,

first of all, this is my first issue and I really want to thank you all for teleport!

## Details

Creating an application with underscore throws an error, but it seems allowed for me in the docs.

> # Application name
> An application name should make a valid sub-domain (<=63 characters, no spaces, only a-z 0-9 _ - allowed).

### Category
- Improve Existing

``` bash
ERROR REPORT:
Original Error: *trace.BadParameterError application name &#34;cockpit_prod1&#34; must be a valid DNS subdomain: https://goteleport.com/teleport/docs/application-access/#application-name

# (The same name with - instead of _ is working)
```

**Comment by zen** [comment]
Underscore is not allowed in domain names, so parser behaves correctly, but docs are wrong. You might want to submit a PR for that
