### ISSUE TITLE
Clarify required permissions for the App Access Dynamic Registration guide

### ISSUE THREAD

**Issue by zen** [gravitational/teleport#10136]
## Details
Provided example of dynamic registration will not wok in default installation since local user with default roles is missing permissions. Documentation is missing how to allow access to configure access for managing app resources. Additionally there are no docs on newly introduced dynamic resources and how to configure access to manage them. There is also no way to get that information form teleport server itself. Infinite loop.

### Category
- Improve Existing

**Comment by ptgott** [comment]
Applies to: /docs/pages/application-access/guides/dynamic-registration.mdx
