### ISSUE TITLE
Make Teleport proxy instances horizontally scalable and unlock multi-region clusters

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#10131]
Preliminary thoughts on a request to evaluate and expand how our proxy protocol functions

Teleport clusters use a brute-force approach to ensuring that all Teleport agent nodes have reverse tunnel connections to all proxy servers behind a load balancer (see [Teleport Discovery Protocol](https://goteleport.com/blog/teleport-discovery-protocol/)).  This implies that Teleport proxies are not horizontally scalable as they require all agent connections in the cluster.  This could be improved by creating only one or two reverse tunnel connections to individual proxies and routing client connection requests to the appropriate proxy between proxy servers.

In order to do this, the proxy servers would need to keep track of some state mapping proxy servers to active reverse tunnel connections. Although, this state could entirely be tracked in memory (as the connection mapping doesn’t need to persist) and use a [raft](https://raft.github.io/) based protocol (with [etcd/raft](https://github.com/etcd-io/etcd/tree/main/raft) or [hashicorp/raft](https://github.com/hashicorp/raft)) to establish the most accurate mapping across all proxy servers. This is much more efficient than the status quo of using a CRDT and greedily keeping track of proxy servers on the agent nodes.  This also would enable multi-regional deployments of Teleport for any-cast routed Teleport proxy/auth server deployments (for example with [AWS Global Accelerator](https://aws.amazon.com/global-accelerator/?blogs-global-accelerator.sort-by=item.additionalFields.createdDate&blogs-global-accelerator.sort-order=desc&aws-global-accelerator-wn.sort-by=item.additionalFields.postDateTime&aws-global-accelerator-wn.sort-order=desc) or [Google’s Global TCP Proxy Load Balancer](https://cloud.google.com/load-balancing/docs/tcp)) and more advanced load balancing schemes than round-robin.

This does assume that proxy servers are able to communicate with each other (on the same network and IP routable) and would possibly require some mTLS identity bootstrapping for secure communications between proxy servers.

**Comment by somethingnew2-0** [comment]
Looks like this is similar enough to https://github.com/gravitational/teleport/pull/9132 and can be closed out.  I'll move my comments there if I have any.
