### ISSUE TITLE
Support User Environment 

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1014]
When creating a new session with OpenSSH you inherit only a limited number of environment variables:

```
DISPLAY
HOME
LOGNAME
MAIL
PATH
SSH_ASKPASS 
SSH_AUTH_SOCK
SSH_CONNECTION
SSH_ORIGINAL_COMMAND
SSH_TTY
TZ
USER
```

After that, if `PermitUserEnvironment true` is set in `sshd_config`, `sshd` will read in `~/.ssh/environment` and set these in your environment.

At the moment, Teleport supports the first half (getting the predefined set of environment variables), Teleport should also respect and environment file if it exists and this feature is enabled on the server.

**Comment by kontsevoy** [comment]
Teleport should use `.tsh/environment` since we've made the earlier decision to NOT reuse ssh directories.

**Comment by russjones** [comment]
It looks like OpenSSH doesn't allow you to configure where the environment file, it's hardcoded in the source:

```c
	/* read $HOME/.ssh/environment. */
	if (options.permit_user_env) {
		snprintf(buf, sizeof buf, "%.200s/.ssh/environment",
		    strcmp(pw->pw_dir, "/") ? pw->pw_dir : "");
		read_environment_file(&env, &envsize, buf);
	}
```
https://github.com/openssh/openssh-portable/blob/master/session.c#L1151-L1156

So we should also update our documentation to create a symlink if using OpenSSH clients is needed.
