### ISSUE TITLE
Document new role options for desktop access

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#10160]
## Details

For Teleport 9, we've added:

```
options:
  record_sessions:
    desktop: true
  desktop_clipboard: true
```

Document these new options.

Both of them default to true if not specified, and attempt to lean towards the _most secure_ option.

 - For session recording, the most secure thing is to record, so in order to disable recording **all** of a user's roles must explicitly disable it.

 - For clipboard sharing, the most secure thing is to not share clipboards, so in order to disable clipboard sharing, **one or more** or a user's roles must explicitly disable it.

More context in [this PR comment](https://github.com/gravitational/teleport/pull/9868#discussion_r791978457), when we implement clipboard support for Desktop Access, we should document the behavior of the [`desktop_clipboard` role option](https://github.com/gravitational/teleport/blame/080ba8fc326fd500a29023aa87c51ff1f38f7ff3/rfd/0049-desktop-clipboard.md#L134-L139) per RFD 49:

> For these reasons, clipboard access will be enabled via the `desktop_clipboard`
> role option as specified in [RFD 33](./0033-desktop-access.md). This option will
> default to `true`, but the presence of a single role that disables the clipboard
> will turn it off. When clipboard access is not enabled, Teleport will not
> respond to any clipboard messages received by either the browser or the RDP
> server.

### Category
- Improve Existing

**Comment by zmb3** [comment]
Thanks for filing, @ptgott. I've renamed this and also updated the description to include the related role option for session recording.
