### ISSUE TITLE
Non-AD Windows Desktop Access

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#10166]
### What
Customers have been increasingly requesting Windows Desktop Access that's decoupled from AD. Would be good to have a way to set up Desktop Access without having to spin up AD or connect to existing AD stack.

### Why
There are times when customers want to just connect to a Windows machine for access to a program that doesn't have an alternative on Linux, but they don't have AD deployed already. Deploying a full AD stack for a single machine doesn't make sense in these situations, nor the additional cost and overhead to maintain the AD stack. Furthermore, adding AD into the mix where the Windows deployments are created/destroyed as needed adds further complication to customer environments and deployments. Additionally, the network connectivity requirement between Windows and Microsoft AD has been flagged by some customers as a potential attack vector concern.

gz#3823

TODO for v12:
- [x] #18995
- [x] #18994
- [x] #18996

**Comment by zmb3** [comment]
Thanks for creating this.

As of now, our passwordless smart-card authentication approach requires a domain-joined desktop. We're hopeful that an eventual migration to Windows Hello will allow us to connect to standalone desktops.

**Comment by jon-can** [comment]
Had another prospect ask for this today.

**Comment by raphaelbkt** [comment]
Hi,
I would love to have such a functionnality, even if we have to enter password or to have to use a standardised name account.
Thanks

**Comment by dcfreedom** [comment]
I would really love to have this feature. We've encounter different request as below,
1. Servers do not join AD due to different reasons.
2. Linux desktop access
3. Windows client with only AzureAD joined.

**Comment by aegancs** [comment]
Agree that this would be perfect for our use case. The servers in our office are joined to a domain but our cloud servers which host public-facing services are not.

Additionally, our organisation is looking to drop on-site AD where possible and use AzureAD, so in the future we may not have the option even internally.

**Comment by raisulmushfeq** [comment]
It would be a great addition indeed because setting up AD for just a single server would be a hassle.

**Comment by sbourdette** [comment]
To access to Virtualbox VM it would be great.

**Comment by AlverezYari** [comment]
This would be a fantastic feature.
