### ISSUE TITLE
PR #9413 results in user home directories set to "/" when root squashing is enabled

### ISSUE THREAD

**Issue by jdconti** [gravitational/teleport#10177]
### Description

**What happened**:

#9413 results in user home directories set to "/" when root squashing is enabled.

**What you expected to happen**:

The users home directory should be tested in the context of the user with appropriate permissions, not root which is re-mapped to an anonymous user / nfsnobody.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Setup an NFS export with `root_squash` (which is the default).
2. Mount the above export to `/home`.
3. Restrict permissions on `/home` to `2750` or similar.
4. Populate with a user directory and attempt to login as that user.
5. You'll get dropped into `/` with `$HOME=/`

```
    [drwsr-S---]  /home
    ├── [drwx--S---]  bar
    ├── [drwx--S---]  baz
    └── [drwxr-s---]  foo
```

### Server Details
- Teleport version (run `teleport version`): 8.1.1
- Server OS (e.g. from `/etc/os-release`): `PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicated

### Client Details
- Tsh version (`tsh version`): 8.1.1
- Computer OS (e.g. Linux, macOS, Windows): Linux, macOS, Windows
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): yum

### Debug Logs
Nothing relevant in either set of debug logs but can provide if necessary.

**Comment by Joerger** [comment]
@jdconti @russjones Can you help me understand the exact flow which is expected to work? I'm getting the described behavior with both Teleport and OpenSSH, and am not sure how this can be accomplished. If `/home` is restricted to `2750` permissions from the nfs export, then neither `root` nor `user` will be able to `chdir` or even `stat` `/home/user`.

In case I'm missing something, here are the exact steps I took on my local machine with OpenSSH:
1. mkdir -p /nfs/home
2. chmod 2750 /nfs/home
3. echo "/nfs/home 127.0.0.1(rw,sync,root_squash)" >> /etc/exports
4. systemctl restart nfs-kernel-server
5. mount 127.0.0.1:/nfs/home /home
6. touch /nfs/home/dev
7. ssh dev@local.openssh
  - Puts me in "/" with stdout message `Could not chdir to home directory /home/dev: Permission denied`

If you `chmod 2751 /nfs/home`, then both Teleport and OpenSSH will successfully put the user into their home directory.

**Comment by jdconti** [comment]
@Joerger of course.  The key here is to have your `dev` user be a part of the group, that will allow the `dev` user to traverse `/nfs/home` but not `root` (when root squashed).  Please let me know if you have any other questions.
