### ISSUE TITLE
UX Improvement for Settings

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1018]
[Ev] this issue got superseded by #1233

At the moment, in the Enterprise Web UI if you have `RW` access to the following roles, you are considered an admin and the wrench shows up in the UI which allows you to configure OIDC, roles, and Trusted Clusters.

```
KindRole
KindUser
KindOIDC
KindCertAuthority
KindReverseTunnel
KindTrustedCluster
KindNode
```

However, this does not allow you to create "partial admins" that can for example just enable/disable Trusted Clusters from the Web UI or only update OIDC settings. At the moment this is impossible because the Web UI is only available if you are a full admin.

**Comment by russjones** [comment]
#### @russjones comments

On the backend, we don't have a notion of an admin, we just have roles with names (which could be admin) that have access to certain resources (which could be `RW` or `RO`). I propose we follow this pattern on in the Web UI and show the wrench and allow you to configure resources that you have `RW` access to. For example:

* If you only have `RW` to the OIDC resource, show the wrench, and then only the OIDC tab.
* If you only have `RW` to the OIDC resource and Trusted Cluster resource, show the wrench, and then the OIDC and Trusted Cluster tabs.
* If you do not have `RO` access to OIDC, Trusted Clusters, or Roles, don't show the wrench.

This way we can enable "partial admins" that only have the ability to enable/disable the parts of Enterprise they have access to.

**Comment by russjones** [comment]
#### @alex-kovoy comments

My initial impression was to see if we can avoid this change on UI side. It feels that we need to collect more 'inputs' before we dive into UI Role management/ACL changes.

Below is the summary of how UI Roles currently work and the changes needed to accommodate this request. 

UI has a concept of Access Control List  and currently it consists of the following _permissions_:
- Admin
- SSH Access.

Each permission is associated with a specific set of role attributes and UI behaviors.  For example, when admin is 'checked' it implies the full access to above resources (KindXXX) and visibility of the 'settings' page. 

Now, if we need to separate the new TrustedCluster scenario from the 'Admin'  we need to think about the following:
1. Introduce a new access type 'Trusted Cluster Management' to UI Roles.
2. Introduce new UI behavior to the 'settings' page.
3. Rethink 'admin' access. Should we split it up by more granular permissions like:
   - Allow Role Access
   - Allow Trusted Cluster management
   - Allow Auth management

**Comment by kontsevoy** [comment]
this issue got superseded by #1233
