### ISSUE TITLE
Reorganize Getting Started section.

### ISSUE THREAD

**Issue by sshahcodes** [gravitational/teleport#10199]
## Details
The current **Getting Started** section houses two different types of doc. The Linux server guide is focused on installation and initial steps, while the docker-compose is more of a tutorial-style introduction to Teleport in a preconfigured environment. 

Move docker-compose to a separate tutorial (or Teleport lab) section and keep the Getting Started section focused on installation and initial steps. 

The final section would be:

**Getting started**
- [Linux Server](https://goteleport.com/docs/getting-started/linux-server/) (current one)
- [Kubernetes Cluster](https://goteleport.com/docs/kubernetes-access/getting-started/cluster/) (move from Kubernetes Access as this is also related to installation and getting started on Kubernetes)

**Tutorial (or Teleport lab)**
- [docker-compose](https://goteleport.com/docs/getting-started/docker-compose/)
- [minikube based teleport lab](https://github.com/gravitational/teleport/issues/9359)

### Category
- Improve Existing

**Comment by ptgott** [comment]
Related to this, it would be great to nudge Teleport newcomers toward a guide that requires as little initial setup as possible. If a reader comes across one of our self-hosted Teleport guides and realizes they need to wait for DNS propagation to complete before they can even try out Teleport, for example, that could dissuade someone from giving the rest of the guide a go.

**Comment by sshahcodes** [comment]
@ptgott Would an instruqt track for our [docker compose based teleport-lab](https://goteleport.com/docs/getting-started/docker-compose/) address your issue?

**Comment by ptgott** [comment]
@sshahcodes I think it'd be great to direct new readers to our Instruqt tracks. Currently, we don't have a component for embedding our tracks in the docs. We could have some highly visible instructions in a frequently-visited page to use the following resources depending on the reader's needs.

- Instruqt tracks for a quick, no-deployment option
- Local demos (docker-compose, Kubernetes) for a risk-free lab that the user can experiment with on their own time
- Production/Staging guides (e.g., Linux Server) for setting up Teleport in a real environment

The information architecture of the docs site is something @xinding33 wants to focus on at some point. What do you think, Xin?
