### ISSUE TITLE
Documentation on sshd part

### ISSUE THREAD

**Issue by RedPepper** [gravitational/teleport#1019]
I want to integrate already running sshds to teleport. Unfortunately the documentation is not very clear how to register those sshd servers as i do not want to install teleport on them.

**Comment by russjones** [comment]
@RedPepper We have a section within our docs that covers OpenSSH integration: http://gravitational.com/teleport/docs/2.0/admin-guide/#using-teleport-with-openssh

Is there a specific issue that is not clear?

**Comment by RedPepper** [comment]
the part that is not clear to me is how a node joins the cluster without sshd (aka how does the proxy node is aware of the sshd)

**Comment by kontsevoy** [comment]
@RedPepper when using `sshd` you lose cluster introspection (this feature is only available when you're running `teleport` as your SSH node). So when `sshd` is used, Teleport proxy acts as a typical SSH jumphost: it looks up the host IP and tries to make a connection.
