### ISSUE TITLE
Create a guide to using Application Access with the Vault CLI

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#10195]
## Details
Start with this discussion forum comment: https://github.com/gravitational/teleport/discussions/6869

### Category
- Improve Existing

**Comment by stevenGravy** [comment]
Good to investigate if there is a method of using our JWT or header values with vault as a method to authenticate a user.  That would be a great useful feature.

**Comment by zmb3** [comment]
This looks like a duplicate of #6870
