### ISSUE TITLE
Locking user accounts terminated other sessions as well

### ISSUE THREAD

**Issue by wetnun** [gravitational/teleport#10202]
Trying to disable a user in the system the current code looks like this:

```
func deleteTeleportUser(ctx context.Context, teleportClient *client.Client, employeeUsername string) error {
        expirationTime := time.Now().Add(15 * time.Minute)

        leaverLock, err := types.NewLock(
                employeeUsername,
                types.LockSpecV2{
                        Target: types.LockTarget{
                                User: employeeUsername,
                        },
                        Message: "Leaver",
                        Expires: &expirationTime,
                },
        )

        log.Debugf("Creating lock to leaver User %s", employeeUsername)

        if err != nil {
                log.Errorf("failed to create lock: %v", err)
                return err
        }

        err = teleportClient.UpsertLock(ctx, leaverLock)

        if err != nil {
                log.Errorf("failed to insert lock: %v", err)
                return err
        }

        log.Warnf("Locked User %s", employeeUsername)

        log.Debugf("Deleting User %s", employeeUsername)

        err = teleportClient.DeleteUser(ctx, employeeUsername)

        if err != nil {
                log.Errorf("failed to delete user: %v", err)
                return err
        }

        return nil
}
```

Result:
User gets removed and sessions killed.  But it also dropped all other users active ssh sessions.  Web sessions seemed to stay intact.

Expected:
User get removed and sessions killed with remaining lock (no other users impacted).

Reproduction:
1. have multiple users logged into the cluster web UI
2. create active ssh sessions via the web for multiple users
3. lock/delete a single user like the code above

Details:
- Teleport server Teleport Enterprise v7.1.3 git:v7.1.3-0-g79bdd9c19 go1.16.2
- Server OS Ubuntu 20.04.3 LTS
- In AWS

Client:
- Browser (Chrome in OSX and Windows)

Debug:
Users got a disconnect for timeout message in open ssh sessions from teleport server in the web UI (thought I saved one but I don't see it now).

As I review our code (I didn't write this), I'm wondering if the user deletion messes with the locks and it gets a nil user from the DB internally and then just kills all sessions.

**Comment by dreamlibrarian** [comment]
```{ 
   addr.local: *snip*:3022
   addr.remote: *snip*:31534
   cluster_name: *snip*
   code: T3006I
   ei: 0
   event: client.disconnect
   login: tsmith
   reason: lock targeting User:"A" is in force: Reason here
   server_id: *snip*
   time: 2022-02-04T23:41:25.234Z
   uid: *snip*
   user: B
}```

Full event, anonymized - notable that the disconnect reason is user A who was locked, but the user disconnected was unrelated user B.

**Comment by russjones** [comment]
@wetnun We tried to reproduce this but could not, I'm going to close this for now. If you run into this issue again, please feel free to open it again or create another ticket, we'll try and track it down.
