### ISSUE TITLE
Implement more predictable behavior for second_factor: on|off

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#10203]
### What
Currently, the `auth_service.authentication.second_factor` config setting expects a string that can have the values `"on"` or `"off"`, among others (e.g., `"otp"`). However, users need to ensure that `on` or `off` values are wrapped in quotes, otherwise the YAML library, following the spec, [resolves these values as Booleans](https://github.com/go-yaml/yaml/blob/7649d4548cb53a614db133b2a8ac1f31859dda8c/resolve.go#L37-L42). Failure to wrap the value in quotes leads to an error when Teleport reads the user's config (see [this issue](https://github.com/gravitational/teleport/pull/10189#issue-1125899057)). The same goes for the `cluster_auth_preference` dynamic config resource.

### How
As suggested in [this comment](https://github.com/gravitational/teleport/pull/10189#pullrequestreview-874863797) by @zmb3, we can implement an `UnmarshalYAML` method for `constants.SecondFactorType` that handles `on` and `off` values without attempting to resolve these as Booleans.

### Why
Users should not be expected to remember that all possible values of `second_factor` can be quoted or unquoted like standard YAML strings _except for_ `on` and `off`.

### Workaround
If a workaround exists, please include it.

**Comment by tobiaszheller** [comment]
@ptgott can you elaborate what you mean by:
> The same goes for the cluster_auth_preference dynamic config resource

I could not find in code anything related to it which could be unmarshaled incorrectly.
