### ISSUE TITLE
Application access for TCP applications

### ISSUE THREAD

**Issue by stereobutter** [gravitational/teleport#10216]
### What
As I understand it application access currently only works for http, https and apparently also websockets (https://github.com/gravitational/teleport/issues/5264). Would it be possible to also support raw tcp?

### Why
A lot of protocols in industrial applications are implemented on top of tcp (e.g. tcp/ip flavor of modbus). It would be really handy if one could setup a small iot box running teleport for tunneling these protocols to remote devices in the field (i.e. local pc --> teleport host --> remote modbus device). 

### How
Either on top of plain ssh access or using websockets maybe? See below

### Workaround
I guess one could use application support for websockets and use something like https://github.com/novnc/websockify. Have not tried this though.

**Comment by klizhentas** [comment]
from @r0mant:

For example, just thinking through the potential UX, would the following satisfy what you’re looking for:
You’d define a plain “tcp” endpoint in Teleport same way as you define, say, a web app or a database (via teleport.yaml static config or a dynamic resource with tctl create).
Users would log into Teleport cluster using tsh login
Then they’d be able to open a local tunnel for this “tcp” application (if they have permissions for it) using tsh proxy app command. The tunnel will be mutually TLS authenticated
Any traffic sent through this local tunnel will be proxied to the target endpoint on the application agent

**Comment by stereobutter** [comment]
> You’d define a plain tcp endpoint in Teleport same way as you define, say, a web app or a database (via teleport.yaml static config or a dynamic resource with tctl create).

Yes, for `teleport.yaml` maybe something inspired by `app_service` like

```yaml
endpoint_service: 
  enabled: yes
  endpoints:
    - name: "my_tcp_server"
      protocol: "TCP"  # might be extended to UDP?
      port: 8000
      labels:
        env: "prod"
      commands:
      - name: "os"
        command: ["/usr/bin/uname"]
        period: "5s"
```

> Users would log into Teleport cluster using tsh login

If they wanted to access the server interactively. For machine to machine access I guess you would either create a long lived certificate using `tctl` or use the new `machineID` service?

> Then they’d be able to open a local tunnel for this tcp application (if they have permissions for it) using tsh proxy app command. The tunnel will be mutually TLS authenticated

Say I've got an application that wants to connect to my remote tcp server via teleport. To establish the connection I'd imagine using something like you said

```tsh proxy app my_tcp_server  --proxy="teleport.example.com", --identity=some_cert_file --port=8001```

where everything that gets send to port 8001 on the local machine is proxied to the remote machine's port 8000. In a real world scenario I'd then probably put the proxy in a sidecar container next to my application.
