### ISSUE TITLE
Cannot add nodes to a cluster, all auth servers are offline

### ISSUE THREAD

**Issue by Microos** [gravitational/teleport#1021]
I tried to follow the QUICKSTART GUIDE.  I have started the teleport server on a VPS and created a teleport user. Then according to the guide, my next step should be adding a computer to that cluster. So I ran the `sudo tctl nodes add` on the VPS and got an invitation command. When I ran the command on my computer wanted to add it to the cluster, it printed out `all auth servers are offline`. 

teleport server on VPS outputs this when a node trys to join the cluster:

`
WARN[3741] conn(111.111.111.111:40486->222.222.222.222:3025, user=xxxx-xxxx-xxxx-xxxx-226d69761f9a.6df23a96-xxx-xxxx-xxxx-e7f49b1903d1) ERROR: failed auth user xxxx-xxxx-xxxx-xxxx-226d69761f9a.6df23a96-xxx-xxxx-xxxx-e7f49b1903d1, err: ssh: certificate signed by unrecognized authority  file=auth/tun.go:421 func=auth.(*AuthTunnel).keyAuth
`

What's wrong with my steps?

**Comment by nikatjef** [comment]
Right off the bat, I would suggest adding '--insecure' to your tctl command line.  The error indicates that it is failing to validate the SSH certificate provided by the Teleport process.  

IIRC, I had a similar issue and resolved it by distributing my CA certificate to the individual nodes.

**Comment by kontsevoy** [comment]
@Microos did you build your own teleport from the master? This looks like an error message from one of the alpha versions. I would suggest:

1. Download the stable binary (or git-checkout a stable tag, and build from there)
2. Pay attention to how accurately you specified tokens when starting nodes.

**Comment by kontsevoy** [comment]
@Microos also, you're adding a node (running on your laptop it looks like) to a cluster hosted on a VPS. This is not impossible, but not common (and not recommended), i.e. make sure ports `3022`, `3025` and `3023` are all open. The unusual part here is that you need port `3025` to be available, that's the "cluster API" port which nodes use to communicate with the auth server/CA.

**Comment by kontsevoy** [comment]
@russjones lets see if we can reproduce this, but the error message needs to be improved anyway (it seems to get lost)
