### ISSUE TITLE
tls: unknown certificate error from ALPN proxy

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#10210]
### Description

**What happened**:

Users are reporting the following warning appears in Teleport logs periodically:

```2022-02-06T17:55:26+07:00 WARN [ALPN:PROX] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *tls.permanentError remote error: tls: unknown certificate
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:330 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:268 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
        /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: remote error: tls: unknown certificate] alpnproxy/proxy.go:276
2022-02-06T17:55:42+07:00 WARN [ALPN:PROX] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *tls.permanentError remote error: tls: unknown certificate
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:330 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:268 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
        /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: remote error: tls: unknown certificate] alpnproxy/proxy.go:276
```

It does not seem to affect any functionality.

**What you expected to happen**:

We should investigate why it happens and make sure that:

- If it's a red herring, there should be no warning/error in the logs.
- If it's an actual issue, provide a more useful error message with remediation steps.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.
2.
3.

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

gz#6133

**Comment by rcoxns** [comment]
We have this same issue spamming our logs.  It seems to happen roughly every 30 seconds.

teleport version
```
Teleport Enterprise v8.3.4 git: go1.17.3b7
```

cat /etc/os-release
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

Teleport is running on dedicated hardware with FIPS enabled:
```
cat /proc/sys/crypto/fips_enabled
1
```

```
tsh version
Teleport v8.3.1 git: go1.17.6
```

Running teleport in debug, gives the exact same errors as the original report.

**Comment by ThomasHoutrique** [comment]
Exact same issue here :
`Apr 12 17:56:06 teleport teleport[1472]: ERROR REPORT:
Apr 12 17:56:06 teleport teleport[1472]: Original Error: *tls.permanentError remote error: tls: bad certificate
Apr 12 17:56:06 teleport teleport[1472]: Stack Trace:
Apr 12 17:56:06 teleport teleport[1472]:         /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:344 github.com/gravitational/teleport/lib/srv/alpnpr>
Apr 12 17:56:06 teleport teleport[1472]:         /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:282 github.com/gravitational/teleport/lib/srv/alpnpr>
Apr 12 17:56:06 teleport teleport[1472]:         /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
Apr 12 17:56:06 teleport teleport[1472]: User Message: remote error: tls: bad certificate] alpnproxy/proxy.go:290`
Spammed every 4-5 seconds
The web interface is working and the cert is valid

**Comment by shivamkb17** [comment]
I am also facing same exact issue in my installation. 
`User Message: remote error: tls: bad certificate] alpnproxy/proxy.go:334
2022-12-18T03:58:32Z WARN [ALPN:PROX] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *tls.permanentError remote error: tls: bad certificate

Stack Trace:
	github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:388 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
	github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:326 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: remote error: tls: bad certificate] alpnproxy/proxy.go:334
2022-12-18T03:58:49Z WARN [ALPN:PROX] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *tls.permanentError remote error: tls: bad certificate

Stack Trace:
	github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:388 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
	github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:326 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: remote error: tls: bad certificate] alpnproxy/proxy.go:334`

**Comment by ibeckermayer** [comment]
@smallinsky can we close this issue now?

**Comment by smallinsky** [comment]
Fixed in https://github.com/gravitational/teleport/pull/19478
