### ISSUE TITLE
tctl not working in multiplex proxy mode with unsigned cert

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#10214]
### Description

**What happened**:

Unable to use `tctl` through a proxy connection in multiplex listener mode when the TLS cert is self-signed. 

**What you expected to happen**:

Using `--insecure` would allow a connection 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Run `teleport start` in `multiplex` proxy listener mode without a signed TLS
2. Create a `access,editor` roles user 
3. Login externally via `tsh` and use `tctl users ls --insecure`

### Server Details
- Teleport version (run `teleport version`): 8.1.5
- Server OS (e.g. from `/etc/os-release`): ubuntu

### Client Details
- Tsh version (`tsh version`): 8.1.5

### Debug Logs

```bash
tctl users ls --insecure
[CLIENT]       Cannot connect to the auth server: failed direct dial to auth server: Get "https://checknosign.teleportdemo.com:443/web/launch/checknosign.teleportdemo.com": stopped after 10 redirects
	Get "https://checknosign.teleportdemo.com:443/web/launch/checknosign.teleportdemo.com": stopped after 10 redirects, failed dial to auth server through reverse tunnel: Get "https://teleport.cluster.local/v2/configuration/name": ssh: handshake failed: EOF
	Get "https://teleport.cluster.local/v2/configuration/name": ssh: handshake failed: EOF.
Is the auth server running on "checknosign.teleportdemo.com:443"?
```

**Comment by r0mant** [comment]
@stevenGravy I tried to repro this and could not. tctl seems to work for me even without `--insecure` flag if cluster uses TLS routing and has self-signed cert:

```bash
# Ensure cluster uses self-signed certificate.
➜  ~ tsh login --proxy=root.gravitational.io:3080 --auth=local --user=alice
ERROR: Get "https://root.gravitational.io:3080/webapi/ping/local": x509: certificate is valid for mbp, localhost, localhost.local, not root.gravitational.io

# Log in with insecure.
➜  ~ tsh login --proxy=root.gravitational.io:3080 --auth=local --user=alice --insecure
Enter password for Teleport user alice:
WARNING: You are using insecure connection to SSH proxy https://root.gravitational.io:3080
> Profile URL:        https://root.gravitational.io:3080
  Logged in as:       alice
  Cluster:            root
  Roles:              admin
  Logins:             root, ubuntu
  Kubernetes:         enabled
  Kubernetes groups:  system:masters
  Valid until:        2022-02-09 20:48:22 -0800 PST [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

# Check TLS routing enabled.
➜  ~ cat ~/.tsh/root.gravitational.io.yaml | grep tls
tls_routing_enabled: true

# Use tctl.
➜  ~ sudo tctl -c ~/dump/resources/t/teleport-root.yaml users ls
User            Roles
--------------- ---------------
alice           admin
bob             db-limited
ca-rotator      ca-rotator
dumper-accessor dumper-accessor
r0mant          db-limited
```

Have you been able to repro this? A few questions:

- `without a signed TLS` <-- does this mean self-signed certificate or proxy with --insecure-no-tls? TLS routing won't work in the latter case.
- Is it possible to see the proxy configuration (with all sensitive info obfuscated)?
- Is there debug output from the tctl command?
- Is there any sort of the load balancer in front of proxy?

@smallinsky Could you also give it a shot please and see if you're seeing same behavior as I do?

**Comment by smallinsky** [comment]
Fixed in https://github.com/gravitational/teleport/pull/10297
