### ISSUE TITLE
Local User Password Requirement Configurability

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#10228]
### What
Request for ability to define password requirements for local users such as password strength and/or rules. Currently, local users do not allow admins specify password strength or rules? 

### Why
Customer ask for additional local user security hardening

**Comment by stevenGravy** [comment]
similar to #1936

**Comment by wadells** [comment]
closing as a dupe of https://github.com/gravitational/teleport/issues/1936.  I moved over the `c-af` and `c-qw` labels.
