### ISSUE TITLE
RBAC Log Spam after Upgrade to 8.1.1

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#10229]
### Description

**What happened**:
Customer upgraded cluster to 8.1.1 and observed an instant barrage of following logs: 

```
Feb 03 22:19:11 proxy.example.com teleport[22082]: 2022-02-03T22:19:11-08:00 INFO [RBAC]      Access to read cluster_config in namespace default denied to roles Node,default-implicit-role: no allow rule matched. services/role.go:1893
```

### Server Details
- Teleport version (run `teleport version`): 8.1.1 gz#3977

**Comment by zmb3** [comment]
Is this still an issue?
