### ISSUE TITLE
Passwordless support for the Web UI

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#10249]
### What

Support passwordless login flows in the Web UI. The flows are distinct from regular login: no username or password boxes and a slightly different RPC invocation pattern.

### How

Refer to the Passwordless RFDs for local authentication, in particular:

* [RFD 52 - Passwordless](https://github.com/gravitational/teleport/blob/master/rfd/0052-passwordless.md)
* [RFD 53 - Passwordless for FIDO2 clients](https://github.com/gravitational/teleport/blob/master/rfd/0053-passwordless-fido2.md) (only the Web-related parts)

All Web support is under FIDO2, browsers take care of native platform support for us.

See https://github.com/gravitational/teleport/issues/9160 for the Passwordless tracker.

**Comment by codingllama** [comment]
FYI @russjones @kimlisa - raising this early so you have time to prepare for it. It's a bit light on details now, ping me and I'll write a better description.

FYI @xinding33 - we'll need UX design for this one. Ping me if you want an overview and some starting ideas, but I'd say it is largely up to you.

**Comment by codingllama** [comment]
#10632 contains the necessary changes to both Auth and Proxy APIs to allow passwordless.

For authentication:
* api/client/proto.CreateAuthenticateChallengeRequest allows for Passwordless requests (set the oneof)
* lib/client.MFAChallengeRequest now contains a Passwordless field (set it to true)
* Follow up requests don't require a username for passwordless (ssh and web logins)

For registration:
* api/client/proto.DeviceUsage added to registration messages (set to passwordless during registration)
* lib/web.createRegisterChallengeRequest has a deviceUsage field (as above)

**Comment by xinding33** [comment]
@rishibarbhaya-design can you reach out to @kimlisa and work on the designs for passwordless login pages?
