### ISSUE TITLE
Database Item size has exceeded the maximum allowed size

### ISSUE THREAD

**Issue by enkov** [gravitational/teleport#10242]
### Description
Currently, I am using teleport version 8.0.7 and after upgrading it to any version higher I get this error.
```
Feb 04 04:34:24 ip-172-30-2-116 teleport[198751]: 2022-02-04T04:34:24Z WARN [DB:SERVIC] "Heartbeat failed rpc error: code = Unknown desc = ValidationException: Item size has exceeded the maximum allowed size\n\tstatus code: 400, request id: 4LBJAGADE61A4F9EDVS1LPQETBVV4KQNSO5AEMVJF66Q9ASUAAJG." srv/heartbeat.go:270
```
When I get this warning I do not see all databases. After downgrading to 8.0.7 everything works as expected.
In database service, I have 6 databases configured.

**What you expected to happen**:
Everything works after upgrade.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Install teleport version 8.0.7
2. Upgrade teleport to 8.1.0 for example
3. Get the error in logs

### Server Details
- Teleport version (run `teleport version`): Teleport v8.0.7 git:v8.0.7-0-geb8076446 go1.17.3
- Server OS (e.g. from `/etc/os-release`): Amazon Linux 2
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS with dynamodb

**Comment by zmb3** [comment]
@smallinsky did your recent change fix this or was that a separate issue?

**Comment by smallinsky** [comment]
It look like a separate issue. Recently we have fixed 1MB result query result limit where in this case it looks that during this error occurs during resource update. 

@enkov Could you share your DB agent configuration ?

**Comment by enkov** [comment]
I have found the cause of the issue. The problem was in ssl certificates. If I set `ca_cert_file: /path/to/pem` teleport db service don't work because certificate file is large than dynamodb allow to write.
So I removed all db records from dynamodb, removed `ca_cert_file` and now everything works, but I have to use `tls: {mode: insecure}`.
