### ISSUE TITLE
Run 1.8.3 tests on Mac OS as a part of CI/CD hook

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1031]
@klizhentas bought us a hosted MacOS instance which must join Jekins as a test runner and execute tests on a mac.

**Comment by russjones** [comment]
To close this, we need (at least) to resolve the following.

- [ ] https://github.com/gravitational/teleport/issues/1646
- [ ] https://github.com/gravitational/teleport/issues/1657
- [ ] https://github.com/gravitational/teleport/issues/1659
- [ ] https://github.com/gravitational/teleport/issues/1660
