### ISSUE TITLE
List certificate start/end and roles in audit log entries in user login

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#10338]
### What
Provide the issued certificate start and end time including roles when assigned to a user.

### How
Add entries to SSO Login, local user login and issued certs via `tctl auth sign`

### Why
Be able to track in the audit log what certificates are issued and their expected timeline.

### Workaround
Have to review manually the auth connector to the expected roles via attributes.

**Comment by zmb3** [comment]
@stevenGravy I think this is resolved by the `cert.create` event earlier this year, so I'm going to close this. Correct me if I'm wrong.
