### ISSUE TITLE
Add empty state to help first time user add resources

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#10339]
### What
In a fresh Teleport cluster, the product offers no prompt or guidance to help users add their first resource. 

### How
As an empty state of the resources table when no resources have been added.

### Why
To help users add resources --> reduce time to first value.

**Comment by xinding33** [comment]
Todo: designs.

cc @rishibarbhaya-design

**Comment by rishibarbhaya-design** [comment]
Currently, I've added demo content to the screens.
Kindly provide content to revise it and confirm if steps are required to add any resources.
If not, I will remove that element.

**Comment by xinding33** [comment]
@hatched updated copy available here: https://www.figma.com/file/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?node-id=1869%3A10903

Designs will be further updated tomorrow.

**Comment by rishibarbhaya-design** [comment]
![applications](https://user-images.githubusercontent.com/88441969/158653167-819417d2-84e4-4b8d-9ecb-62ab39f24368.jpg)
![databases](https://user-images.githubusercontent.com/88441969/158653170-8c40b310-c9da-492c-af30-1b424a362fc2.jpg)
![desktop](https://user-images.githubusercontent.com/88441969/158653172-0eac490e-9af9-4705-ae0b-be6e05744fe7.jpg)
![kubernetes](https://user-images.githubusercontent.com/88441969/158653174-0f58e4f7-6d53-4830-86b5-956cfb58a288.jpg)
![servers](https://user-images.githubusercontent.com/88441969/158653177-8c9af592-622c-4ee6-9c81-ce058f9cd80d.jpg)

**Comment by rishibarbhaya-design** [comment]
![applications](https://user-images.githubusercontent.com/88441969/158653272-b451344e-3a06-4a25-b173-5ba1246fc2a4.jpg)
![databases](https://user-images.githubusercontent.com/88441969/158653275-1ae5317e-2bfd-46da-aa1f-6f210d58b510.jpg)
![desktop](https://user-images.githubusercontent.com/88441969/158653279-fff174aa-98be-40ea-8f59-7386238f0824.jpg)
![kubernetes](https://user-images.githubusercontent.com/88441969/158653280-c701e043-42df-4bfd-bf32-f5f1d1e2c46d.jpg)
![servers](https://user-images.githubusercontent.com/88441969/158653284-8c92fd07-4b28-496a-bb01-677e15d7c3d8.jpg)

**Comment by rishibarbhaya-design** [comment]
![databases](https://user-images.githubusercontent.com/88441969/158658002-199a25fe-3e55-4113-a5a0-87d7d7c5c1f1.jpg)
![desktop](https://user-images.githubusercontent.com/88441969/158658003-09681e3b-6716-43ba-92f6-002758a31cae.jpg)
![kubernetes](https://user-images.githubusercontent.com/88441969/158658005-8ba879c7-7bbf-481c-af31-bc659b127373.jpg)
![applications](https://user-images.githubusercontent.com/88441969/158658006-1976b82c-db9f-498a-b3b4-cfe0fb5c08ca.jpg)
![servers](https://user-images.githubusercontent.com/88441969/158658007-b05d8c04-bed6-47a1-a8ee-02d66d192ff9.jpg)

**Comment by hatched** [comment]
This should also be backported to v8 and v9.

**Comment by hatched** [comment]
@rishibarbhaya-design can you please add a design for an empty state where the user does not have permissions to add an entity?
