### ISSUE TITLE
Simplify manual resource joining process

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#10340]
### What
Is there any reason we have steps 2 and 3 in the manual resource joining process instead of embedding an already-issued join token in step 4?

![image](https://user-images.githubusercontent.com/24904723/153897098-d6179f37-28b7-4df1-a617-dcaffd4ccc8a.png)

If we can simplify this process, we'd make it easier for users to add their first resource.

### How
Generate a join token when automatically in step 4 and delete steps 2 and 3.

### Why
Easier to add resource --> reduce time to first value.

**Comment by russjones** [comment]
@xinding33 Now that Cloud supports [Joining Nodes and Proxies in AWS](https://goteleport.com/docs/setup/guides/joining-nodes-aws/), what do you guys think about supporting three join modes, `IAM`, `Automatically`, and `Manual`?

**Comment by mcbattirola** [comment]
To make the PRs smaller, I'm doing each kind of resource individually,
Here's the tracking of the PRs

- [ ] Nodes
  - [x] master https://github.com/gravitational/webapps/pull/619
  - [ ] v9 backport
  - [ ] v8 backport

- [ ] Apps
  - [ ] master
  - [ ] v9 backport
  - [ ] v8 backport

- [ ] DB
  - [ ] master
  - [ ] v9 backport
  - [ ] v8 backport

**Comment by russjones** [comment]
@mcbattirola Yes, let's add it. Please propose a design and @xinding33 will review.

**Comment by pierrebeaucamp** [comment]
Closing this issue since the remaining work is now being tracked in #11465.
