### ISSUE TITLE
Link to enterprise Teleport artifacts in the resource joining process for Cloud

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#10341]
### What
![image](https://user-images.githubusercontent.com/24904723/153897789-5ce3e817-83da-471c-a111-53ef6e9dad49.png)

Link these to the Teleport enterprise (instead of OSS) binaries.

### Why
Reduce confusion during onboarding.

**Comment by hatched** [comment]
This has now been backported to v8
