### ISSUE TITLE
Update Github OSS Team to Logins -> Roles

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#10354]
### Description

**What happened**:

In 5? We added RBAC for OSS users. We've had a hack in place for Github OSS users, that `teams_to_logins` matches to roles, but we should change this to focus on roles.  This would be a good addition into Teleport 9 as a breaking change. 

```diff
kind: github
metadata:
  name: github_ae
spec:
  client_id: xxx
  client_secret: xxx
  display: github x
  redirect_url: https://teleport-8.asteroid.earth:443/v1/webapi/github/callback
- teams_to_logins:
+  teams_to_roles:
-  - logins:
+ - roles:
    - access
    organization: demo
    team: acme
- version: v3
+ version: v4
```

**What you expected to happen**:

v4 is default behavior, but we still respect v3.

**Comment by zmb3** [comment]
@xacrimon if we're creating `RoleV5` for 9.0 anyway maybe we should consider this.

**Comment by xacrimon** [comment]
Yeah, that seems like a good opportunity to do this. What exactly would it entail? I can’t parse the issue fully

**Comment by zmb3** [comment]
I think it's just a rename:

- `teams_to_logins` becomes `teams_to_roles`
- `logins` becomes `roles`

With appropriate conversions when v4 roles are migrated to v5.

**Comment by xacrimon** [comment]
Will submit a PR for this tomorrow but I need to doublecheck, you are aware we don't automigrate roles right? They need to be explicitly upgraded, otherwise their use for RBAC mechanics changes would be worthless.
