### ISSUE TITLE
Sunset U2F in favor of WebAuthn

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#10375]
### What

Teleport supports WebAuthn since 8.x and we are fast moving to a passwordless world. It's time to sunset U2F.

### How

The [WebAuthn RFD](https://github.com/gravitational/teleport/blob/master/rfd/0040-webauthn-support.md#u2f-phase-out) talks about the U2F phase out, which is split in two phases:

1. "u2f" mode is aliased to "webauthn" (U2F implementation effectively removed)
2. "u2f" mode is removed

The original intent was to land 1. in Teleport 9, but time flies, so we are likely looking at releases 10 and 11, respectively.

**Comment by russjones** [comment]
@codingllama Can we migrate users from U2F to webauthn automatically? Or would this mean during an upgrade users would have to re-register?

**Comment by codingllama** [comment]
> @codingllama Can we migrate users from U2F to webauthn automatically? Or would this mean during an upgrade users would have to re-register?

The change should be seamless for end-users - no re-registration or other actions.

We can tweak the details, but the current plan is: starting from v10 it's still possible to use "u2f" as a second_factor setting, but it emits a warning and seamlessly changes the backing implementation to WebAuthn (so no more "u2f" devices will be registered). We'll remove as much API surface as possible here. In v11 all "u2f" options and remaining APIs are removed; at this stage admins have to change from second_factor "u2f" to a supported setting ("on", "optional" and "webauthn" all work).

**Comment by codingllama** [comment]
> "u2f" mode is aliased to "webauthn" (U2F implementation effectively removed)

This is now complete. In addition, I've done a rather comprehensive cleanup. For v11 all that's left is clearing out the user-visible bits ([constants.SecondFactorU2F](https://github.com/gravitational/teleport/blob/f8b7b330ad9006d0cd358de1ca466800ad00398d/api/constants/constants.go#L138), [lib/config](https://github.com/gravitational/teleport/blob/bac0ccdc99068702beba395e12de114e961058b6/lib/config/fileconf.go#L728) and maybe a few other places).

The more interesting decisions for v11 are:

* What to do with the U2F App ID
* What to do with legacy U2F devices in storage

The App ID has to remain, at least in some form, so legacy devices keep working. Migrating the U2F storage devices simplifies the code a bit, but it's not paramount.

**Comment by codingllama** [comment]
Remaining cleanup tasks

- [ ] Update public documentation ("u2f" deprecated and aliased to "webauthn")

v11
- [ ] Cleanup public-facing U2F configurations
- [ ] Update public documentation ("u2f" not allowed)
- [ ] Decide the fate of the U2F App ID (keep "u2f" stanza, alternative)
- [ ] Decide the fate of storage U2F Devices (keep or migrate to WebauthnDevice)
