### ISSUE TITLE
Teleport Community edition not starting for Windows

### ISSUE THREAD

**Issue by ubmaity** [gravitational/teleport#10383]
### Unable to start Teleport Community edition on Windows

When tried to install/run teleport application , it just loads and then stops.
Nothing gets run.

Tried on the  latest version.
Windows defender is off.

Any possible resolution?

**Comment by stevenGravy** [comment]
@ubmaity Please provide your steps for starting.  You may find our slack community a helpful place for these questions. https://goteleport.com/slack
