### ISSUE TITLE
Bootstrapping clusters with shared credentials

### ISSUE THREAD

**Issue by manicai** [gravitational/teleport#1039]
I'm trying to set up Teleport to support multiple distinct server groups (AWS VPCs) that cannot talk to each other but share credentials. 

My current attempt is to have server acting as auth and proxy service per group using DynamoDB as a backend. However if I do this and launch two groups, even with different cluster names, all the servers from both groups appear in WebUI on both proxies (though each proxy cannot connect to servers in the other group). The line about "auth servers become one" in https://github.com/gravitational/teleport/issues/726#issuecomment-275033618 suggest this is intentional, is it?

The alternative I was considering looking at the documentation was to have an external auth server that all the groups talk to and separate proxies per group. But looking at the documentation it looks like this will have the same problem (there seems to be no way to have specific for proxies for nodes). We'd also prefer most of the servers in the groups to not have external internet access which we'd have to relax to do this.

Is this configuration supported, if so how?

**Comment by klizhentas** [comment]
You can add the second cluster as a trusted cluster to your first one, so you will see both clusters in the UI and will be able to access them directly or via first cluster's proxy.

**Comment by manicai** [comment]
Maybe I phrased my explanation badly but don't think that does I what I'm looking for. What I'm trying to set up is that the user should be able to use the same username, password and OTP token in each cluster but each cluster should be completely independent (they shouldn't know about any of the others, they're all equivalent and mostly fairly short lived - e.g. one per pull request for CI testing).

**Comment by kontsevoy** [comment]
@manicai this kind of goes against 2fa, where you _must_ have a second device present to manipulate a user account. A proper setup in this case is to use SAML/ODIC connector to an external identity, then you can automatically configure clusters to SSO via the same set of credentials. 

As explained here:
http://gravitational.com/teleport/docs/2.0/enterprise/#external-identities
