### ISSUE TITLE
IAM Node joining doc updates

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#10408]
## Details
Describe the documentation improvements you wish to see.
On the IAM node joining page here: https://goteleport.com/docs/setup/guides/joining-nodes-aws/

1. ~Perquisites state 8.2.0; but 8.3.0 is required for IAM node joining~
2. ~Next steps has a link to step 1.1 which doesn’t work when looking at IAM node joining docs~
3. We should recommend an IAM policy to attach as well so users aren't attaching a policy that has elevated privileges in the event of a node/proxy compromise.  For example if you don't have a policy to apply then create this policy and apply it..
4. In step 2 of the docs we specify `name: iam-token` but don't tell them this value can be anything they want (as long as it matches) until the next step; after they have created the token on the auth server via tctl. Should also specify that one should customize this value to be unique. 

### Category
- Improve Existing

**Comment by scottpgallagher** [comment]
Requirement also to make sure your on 8.3.0 on your tctl on your local machine.

**Comment by nklaassen** [comment]
> We should recommend an IAM policy to attach as well so users aren't attaching a policy that has elevated privileges in the event of a node/proxy compromise. For example if you don't have a policy to apply then create this policy and apply it

It is not necessary to attach any policy to the role, I've called this out in the update here #16303

> In step 2 of the docs we specify name: iam-token but don't tell them this value can be anything they want

Mentioning this in the update

> Also we say to apply the token.yaml file to run tctl create token.yaml we should fix it to be tctl create -f token.yaml

Switched to this in the update

> Requirement also to make sure your on 8.3.0 on your tctl on your local machine.

In v9+ the `tctl` version requirement is called out in the Prerequisites section, I will add this part in the V8 backport
