### ISSUE TITLE
IAM node joining in China (with auth cluster in aws us-east-2)

### ISSUE THREAD

**Issue by JonGilmore** [gravitational/teleport#10415]
### Description

We're operating a single teleport cluster in IoT mode with ~10k nodes connected. We're looking to implement node joining using [these docs here](https://goteleport.com/docs/setup/guides/joining-nodes-aws/), but we have nodes that register that operate in `cn-north-1` region. [Based on this here](https://github.com/gravitational/teleport/blob/4c1695d2e0e87eb3b78ac021863be29f3caa3f04/lib/auth/join_iam.go#L55), it looks like STS won't work because the URL is hardcoded. This issue was opened as a continuation [from this slack thread with](https://gravitational.slack.com/archives/CAHQS4HB5/p1645040410694699) @benarent . 

We haven't reproduced this (yet), so I don't have debug logs or specifics

### Server Details
- Teleport version: 8.3
- Server OS: ubuntu bionic
- Where are you running Teleport? aws
- Additional details: single auth and proxy clusters in aws us-east-2 running in iot mode with nodes connecting from us-east-1, us-east-2, eu-west-1, ap-northeast-1, ap-northeast-2, and cn-north-n1

**Comment by nklaassen** [comment]
Hi @JonGilmore. I don't currently have access to `cn-north-1` to test this, but I think/hope that it will just work.

At a basic level, what this feature does is:
1. On the node (in `cn-north-1` for your case) construct a signed `sts:GetCallerIdentity` HTTPS request. This will be signed with the EC2 nodes credentials for some role in `cn-north-1` in your account.
2. Send this signed request to the Teleport Auth server (this is over gRPC tunnelled through the Teleport Proxy for IoT nodes)
3. The Auth server (in `us-east-2`) sends the request to `sts.amazonaws.com` and gets the response from AWS.

The possible issue would be if the global STS endpoint will not respond to `GetCallerIdentity` requests for any identity in `cn-north-1`. I have not been able to find any AWS docs to suggest that, but if you have any information on it I would be quite interested. Let me know if you get a chance to try to feature as well.

**Comment by nklaassen** [comment]
Hmm - I have done some more reading and there is a good chance that this will actually not work. Let me dig into this further.

**Comment by JonGilmore** [comment]
Thanks @nklaassen - appreciate you digging into this and the explanation. Our sandbox teleport cluster is currently on 7.3.13, but i am happy to upgrade to 8.3 and test this out a little more if you think it'll help us get to the bottom of this quicker - just let me know

**Comment by nklaassen** [comment]
The current problem (I suspected above) is that the global STS endpoint will not respond to `sts:GetCallerIdentity` requests for any identity in the China partition. We should be able to solve this by allowing nodes to create `sts:GetCallerIdentity` requests for their own regional STS endpoint, as long as it is reachable from outside China (looks like it is).
