### ISSUE TITLE
Teleport 9.0 Release Plan

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#10447]
# Teleport 9 Release Plan

## Release Manager

@r0mant 
@zmb3

## Release Date

- [x] First Beta: February 21st, 2022
- [x] First RC: March 9th, 2022
- [x] Release: March 11th, 2022

## Product Approvals

- [x] Security @zmb3 
  - [x] https://github.com/gravitational/teleport/pull/11051
- [x] Scale @zmb3 
  - [x] https://github.com/gravitational/teleport/pull/11031
- [x] SSH and Kubernetes Access @r0mant 
- [x] Application and Database Access @r0mant 
  - [x] https://github.com/gravitational/teleport/pull/10994
  - [x] https://github.com/gravitational/teleport/pull/10693
- [x] Desktop Access @zmb3 
- [x] Machine ID @russjones  
  - [x] https://github.com/gravitational/teleport/pull/10289
  - [x] https://github.com/gravitational/teleport/pull/10833
  - [x] https://github.com/gravitational/teleport/pull/11039
- [x] Webapps @zmb3 
  - [x] https://github.com/gravitational/webapps/pull/642
- [x] Release @r0mant 
  - [x] https://github.com/gravitational/teleport/pull/11008
  - [x] https://github.com/gravitational/teleport/pull/11029
- [x] Documentation @xinding33 
  - [x] https://github.com/gravitational/teleport/pull/10775
  - [x] https://github.com/gravitational/teleport/pull/11033
  - [x] https://github.com/gravitational/teleport/pull/11013
- [x] Product @xinding33 

## Test Plan Approval

- [x] [Teleport 9.0 Test Plan](https://github.com/gravitational/teleport/issues/10446)

# Release Process

- [x] Prepare CHANGELOG/Release Notes. Must be approved be @xinding33.
  - https://docs.google.com/document/d/1Btrj-2u2piDjN7_mthSRvEAknKHJieWoeZalFmbAbIk/edit
- [x] Create release branch. @r0mant 
- [x] Cut release. @r0mant 
- [x] Release Plugins. @r0mant 

# Post-release

- [x] Create PR to update default Teleport version in Teleport docs
  - Example: https://github.com/gravitational/teleport/pull/7033
- [x] Create PR to update default AMI versions in Makefile and AMIs.md under https://github.com/gravitational/teleport/blob/master/assets/aws
  - Example command: `TELEPORT_VERSION=6.2.0 make -C assets/aws create-update-pr`
- [x] Update support matrix in docs FAQ page
- [x] Update `CURRENT_VERSION_ROOT` and other previous versions in Drone `teleport-docker-cron` job
  - Example: https://github.com/gravitational/teleport/pull/4602
- [x] Create PR to update default Teleport image referenced in docker/teleport-quickstart.yml and docker/teleport-ent-quickstart.yml
  - Example: https://github.com/gravitational/teleport/pull/4655
- [x] Create PR to update default Teleport image referenced in docker/teleport-lab.yml

# Misc

- [ ] Organize release retrospective.

**Comment by russjones** [comment]
@zmb3 @r0mant Here is how I did the post release last time.

* https://github.com/gravitational/teleport/pull/9005
* https://github.com/gravitational/teleport/pull/9006
* https://github.com/gravitational/teleport/pull/9007
* https://github.com/gravitational/teleport/pull/9008

**Comment by xinding33** [comment]
I reviewed the [CHANGELOG/Release Notes](https://docs.google.com/document/d/1Btrj-2u2piDjN7_mthSRvEAknKHJieWoeZalFmbAbIk/edit) and my comments have been addressed so it looks good to me. @ptgott can you give it a quick read?

**Comment by ptgott** [comment]
@xinding33 Just added some minor comments/suggestions in the release notes doc.
