### ISSUE TITLE
Comprehensive audit log events for the certificate renewal bot

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#10477]
### What
Audit log events should be emitted for various actions performed by / relating to certificate bots. Per the [RFD](https://github.com/gravitational/teleport/pull/7986) the following events should be emitted:
- a new bot user is created
- a new renewable certificate is issued for the first time
- a certificate is renewed
- a bot is locked
- a bot is removed (likely due to failed heartbeating or expired certificates)
- a certificate generation counter conflict is detected (certificate possibly compromised)

**Comment by strideynet** [comment]
https://github.com/gravitational/teleport/issues/18293 will partially complete this.
