### ISSUE TITLE
Add Database Button Instructions skip over required Steps

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#10479]
### Description

**What happened**:

The Add Database button gives 3 steps that seems to make this only these 3 steps.  It takes installing the agent, and adding the access for the Teleport agent (iam or certs)

![image](https://user-images.githubusercontent.com/60704961/161396178-ecb4e987-1cb3-47bc-afd8-4c2beec7fbc2.png)

**What you expected to happen**:

Provide a comprehensive set of steps or integrate with documentation.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Go to database access
2. Click add database
3. Attempt to follow these instructions without the addiitional steps like installing on a ec2 node with iam permissions.

### Server Details
- Teleport version (run `teleport version`): 8.3.1

**Comment by stevenGravy** [comment]
If you attempt to follow these steps w/o setting up IAM security then you'd get this error. 

```code
psql: error: connection to server at "enterprise.teleport.sh" (35.71.1.1), port 11389 failed: Could not generate RDS IAM auth token:

  NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Make sure that Teleport database agent's IAM policy is attached and has "rds-connect"
permissions (note that IAM changes may take a few minutes to propagate):

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "rds-db:connect",
      "Resource": "arn:aws:rds-db:us-east-1:<account_id>:dbuser:<resource_id>/*"
    }
  ]
}

ERROR: exit status 2
```

**Comment by michellescripts** [comment]
reference #10340

**Comment by r0mant** [comment]
@JanKaczmarkiewicz @michellescripts FYI this dialog is obsolete and will be superseded by the new Teleport Discover wizard we're working on, so there's probably no reason to spend engineering time on fixing it. Let's close this.
