### ISSUE TITLE
Create `Issuer` resource using teleport-cluster chart

### ISSUE THREAD

**Issue by shibataka000** [gravitational/teleport#10493]
### What
I'd like to create `Issuer` resource of cert-manager using [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) chart.

### How
1. Add `issuer.yaml` to [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) chart.
1. Add following options to [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) chart.
    - Option to determine whether or not `Issuer` resource will be create.
    - Option to define `.spec` field of `Issuer` resource.

### Why
Now we must deploy `Issuer` resource manually before deploy [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) chart. If we can deploy `Issuer` resource with [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) chart, it is more convenient.

### Workaround
Deploy `Issuer` resource manually before deploy [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) chart like described at [AWS](https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/guides/aws.mdx#step-4-install-and-configure-cert-manager) and [GCP](https://github.com/gravitational/teleport/blob/master/docs/pages/kubernetes-access/helm/guides/gcp.mdx#step-4-install-and-configure-cert-manager) guides.

**Comment by hugoShaka** [comment]
Hello,

After reviewing the issue and its related PR we think the added value of this feature does not compensate the additional complexity it brings to the chart and its values.

The rationale is the following:
- Chart users can already deploy the `Issuer` resources
- The chart does not brings additional value in this case, it just passes a raw manifest without templating
- It breaks the abstraction created by the `Issuer` ressource: if cert-manager changes its CRD users will have to redeploy the chart and change its values
- Configuring cert-manager and other core Kubernetes components is not in Teleport's scope (even if we might have to explain them in the getting started guides for the sake of time to value)

If you need to deploy everything in one command we suggest creating an internal chart with your custom resources and add the `teleport-cluster` chart in the `dependencies`.

Thank you again for creating the issue and triggering the discussion around this feature request, this is greatly appreciated.
