### ISSUE TITLE
"message_of_the_day" is not showing up in some scenarios.

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#10503]
### Description
"message_of_the_day" is not showing up in some scenarios.

**What happened**:
1. "message_of_the_day" is not showing  with `tsh login` if `--auth` option is added to the login command.
2. "message_of_the_day" is not showing with `tsh login` if `auth` node does not have `authentication` parameter.

**What you expected to happen**:

MOTD should always show when using `tsh login`.

### Reproduction Steps

1.
- spin up teleport cluster with below config:
- login to proxy using `tsh login --insecure --proxy=127.0.0.1:3080 --auth=local` command.
- MOTD will not appear, even if its setup in auth_service.
- if login using `tsh login --insecure --proxy=127.0.0.1:3080` command, MOTD is showing as expected.

2.
- spin up teleport cluster with below auth config:
- login to proxy using `tsh login --insecure --proxy=127.0.0.1:5080` command.
- MOTD will not appear, even if its setup in auth_service.

Attached scripts to reproduce this issue on local laptop [repro_4149_2.tar.gz](https://github.com/gravitational/teleport/files/8113147/repro_4149_2.tar.gz)

Steps to follow: 
- extract file from repro_4149_2.tar.gz.

```
tar xvzf repro_4149_2.tar.gz
```
- cd to extracted directory and run below commands:

```
cd repro_4149_2

# setup 2 teleport clusters with 2 different configs
./cluster_setup.sh

# run tests (this script shows MOTD behaviour)

./test.sh


# stop clusters
./stop_clusters.sh


```

### Server Details
- Teleport version (run `teleport version`): 8.1.x+

### Client Details
- Tsh version (`tsh version`): 8.1.x+

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- tsh debug logs when MOTD was shown.
[tsh_logs_debug_MOTD.txt](https://github.com/gravitational/teleport/files/8113140/tsh_logs_debug_MOTD.txt)

-  tsh debug logs when MOTD was NOT shown.
[tsh_logs_debug_no_MOTD.txt](https://github.com/gravitational/teleport/files/8113146/tsh_logs_debug_no_MOTD.txt)

**Comment by roobeshm** [comment]
System Login Notification is very important feature as part of compliance controls. Can this be expected to be fixed in next release ?

**Comment by ArunNadda** [comment]
MOTD is not showing with most of the login related options, e.g. 

`tsh login --proxy=<> --auth=<>` - does not show MOTD
`tsh login --proxy=<> --request-roles=<>` - does not show MOTD


It seems, only `tsh login --proxy=<>` is showing MOTD (with global options).
