### ISSUE TITLE
How can I remove the node to join the cluster which has been joined before?

### ISSUE THREAD

**Issue by folderman** [gravitational/teleport#1051]
Hi All,

With tctl, I can remove user, I can remove token, however, if I have a previously joined node, how can I disallow the node from connecting to the cluster again?

Do I need to manually remove the cert from the node? Or anything I can do in auth server or proxy server?

Thanks!

Kenneth

**Comment by kontsevoy** [comment]
not sure I'm following. well... just remove Teleport daemon from that node (or stop it from running). but if you are wondering how to permanently exclude the "rogue node" from a cluster, the answer is: you cannot, until cluster certificate rotation is implemented, which is needed, but never requested feature. Our CTO can't wait to get this done, see #350

**Comment by WhyAydan** [comment]
hey sorry to open this back up. But was there a way to remove rogue nodes?
