### ISSUE TITLE
app access: redirect loop

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#10519]
### Description

**What happened**:

When attempting to access an app, the browser entered a redirect loop that would continuously fail on the `POST /x-teleport-auth` call, and eventually fails with a 403.

The browser console shows:

```
Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.
https://APP.TENANT.cloud.gravitational.io/x-teleport-auth
```

The proxy/auth logs showed:

```
"{\"caller\":\"app/handler.go:179\",\"component\":\"app:web\",\"level\":\"warning\",\"message\":\"Failed to get session: failed to match applications.\",\"timestamp\":\"2022-02-22T19:24:50Z\"}\n"
```
It appears that this started happening after proxy/auth were upgraded.

A restart of the Teleport instance running the app service resolved the issue, so it's possible that app service gets into a bad state if it loses connection to auth.

### Server Details
- Teleport version (run `teleport version`): 8.3.1
- Server OS (e.g. from `/etc/os-release`): Debian Bullseye (app service)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Teleport Cloud

**Comment by zmb3** [comment]
This seems to happen every time cloud upgrades.

**Comment by stevenGravy** [comment]
when I restart my auth service the apps are unavailable for about 15m.

**Comment by zmb3** [comment]
Mine never recovers, I have to bounce the app agent and then they start working again immediately.

**Comment by webvictim** [comment]
https://github.com/gravitational/teleport/issues/13673 could be related - it's the same issue with auth/proxy being upgraded and app service/SSH both losing connectivity as a result.
