### ISSUE TITLE
Database Access for China RDS improvements

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#10540]
### What

Two improvements should be made to Database Access to better support RDS databases in China regions (e.g. `cn-north-1`):

- [ ] Automatic CA downloader should be updated to fetch CA bundles specific to Chinese regions: https://docs.amazonaws.cn/en_us/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html.
- [ ] Code that tries to parse database URI to determine whether it's an RDS instance should recognize `.amazonaws.com.cn` suffix: https://github.com/gravitational/teleport/blob/v8.3.1/api/types/database.go#L359-L369.

**Comment by greedy52** [comment]
Closed by
- #10560
- #15359
