### ISSUE TITLE
Provide cloud port info

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#10552]
## Details
Cloud tenants can be assigned different ports then the default on-prem ports. Highlighting this in getting started, how to find your ports and what ports are used for what is important.

### Category
- New Feature
- Improve Existing

**Comment by mcbattirola** [comment]
[This PR](https://github.com/gravitational/webapps/pull/580) adds the public ssh tunnel to the `Help & Support` screen.

I think we could add the other addresses/ports into this page for Cloud users and highlight it in the getting started

**Comment by stevenGravy** [comment]
Yes I think that and some explanation of TLS routing.

**Comment by stevenGravy** [comment]
The most typical issue is what port a desktop client or a agent needs to connect to.  With TLS routing perhaps that's mostly solved with only `443` port needed but if another port is needed they would have to know to open say `111423` to example.teleport.sh
