### ISSUE TITLE
Database docs show multiplex proxy without mentioning db proxy

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#10551]
## Details
Database guides do not mention a db proxy is required on the user's desktop when in `multiplex` mode.  We should provide a link to the DB GUI guide that describe how to connect which is a natural next step.

### Category
- Improve Existing

**Comment by stevenGravy** [comment]
db instructions like https://goteleport.com/docs/database-access/guides/postgres-self-hosted/

**Comment by ptgott** [comment]
@stevenGravy It looks like `tsh db connect` [calls `maybeStartLocalProxy`](https://github.com/gravitational/teleport/blob/3de0f5dfda9e615ef4ad04aec8cb2c6691e2977e/tool/tsh/db.go#L526), which starts the local database proxy automatically if TLS routing is enabled or the connection is to SQL Server ([here](https://github.com/gravitational/teleport/blob/3de0f5dfda9e615ef4ad04aec8cb2c6691e2977e/tool/tsh/db.go#L372-L376)). This was [added on Feb 16](https://github.com/gravitational/teleport/commit/41899806fda6634b174d1b2c55357ede9feee750#diff-dae87d4d3799335d85a5fa6ff17cfcbfb30705ae145c9e67ef70286423676a48R283).

Should we just mention that the local proxy will be started automatically in v9, then add the `tsh proxy db` instructions to v8?

**Comment by ptgott** [comment]
Guides in `docs/pages/database-access` that mention `tsh db connect`
but not `tsh proxy db`:

```
find docs/pages/database-access -exec awk '
BEGIN{c=0; p=0;}
/tsh db connect/{c++}
/tsh proxy db/{p++}
END{if (p==0 && c > 0) print FILENAME}
' {} \;
```

The results for `master`:

docs/pages/database-access/guides/mongodb-atlas.mdx
docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
docs/pages/database-access/guides/sql-server-ad.mdx
docs/pages/database-access/guides/mysql-self-hosted.mdx
docs/pages/database-access/guides/postgres-redshift.mdx
docs/pages/database-access/guides/mongodb-self-hosted.mdx
docs/pages/database-access/guides/postgres-cloudsql.mdx
docs/pages/database-access/guides/rds.mdx
docs/pages/database-access/guides/azure-postgres-mysql.mdx
docs/pages/database-access/guides/ha.mdx
docs/pages/database-access/guides/postgres-self-hosted.mdx
docs/pages/database-access/guides/mysql-cloudsql.mdx
docs/pages/database-access/reference/cli.mdx

The results for `branch/v8`:

docs/pages/database-access/guides/mongodb-atlas.mdx
docs/pages/database-access/guides/cockroachdb-self-hosted.mdx
docs/pages/database-access/guides/mysql-self-hosted.mdx
docs/pages/database-access/guides/postgres-redshift.mdx
docs/pages/database-access/guides/mongodb-self-hosted.mdx
docs/pages/database-access/guides/postgres-cloudsql.mdx
docs/pages/database-access/guides/rds.mdx
docs/pages/database-access/guides/azure-postgres-mysql.mdx
docs/pages/database-access/guides/ha.mdx
docs/pages/database-access/guides/postgres-self-hosted.mdx
docs/pages/database-access/guides/mysql-cloudsql.mdx
docs/pages/database-access/reference/cli.mdx
