### ISSUE TITLE
AWS Redshift serverless support

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#10550]
### What
What would you like Teleport to do differently?
https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-serverless.html
redshift serverless is currently in preview.

### How
How would you implement this?
investigate if redshift serverless supports IAM auth. If yes, we implement proper uri parser (ex: `.redshift-serverless.amazonaws.com`) and auto discovery.

### Why
Why do you need this?

### Workaround
If a workaround exists, please include it.

**Comment by zmb3** [comment]
@greedy52 @smallinsky can this be closed now?
