### ISSUE TITLE
Allow Trusted Cluster role mappings to be updated

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#10568]
### What

Currently, to update the role mappings of a Trusted Cluster, the resource must be destroyed and then recreated. This is cumbersome for two reasons:
- Connectivity between the two clusters is broken during this process.
- A new join token will be required to allow the leaf cluster to reconnect.

### Potential Solution
Have an option to update or add role mappings, similar to how there is an [option to update labels.](https://goteleport.com/docs/setup/admin/trustedclusters/#updating-cluster-labels)

**Comment by pschisa** [comment]
+1 for the ability to update the `role_map` in a trusted cluster resource without having to recreate the trusted cluster, impacting connectivity

**Comment by r0mant** [comment]
@EdwardDowling When working on this, let's make sure that it addresses the Terraform plugin issue too: https://github.com/gravitational/teleport-plugins/issues/622. As in, it should be possible to update trusted cluster role mapping by updating it in the tf file and running terraform apply.

**Comment by russjones** [comment]
@r0mant @EdwardDowling Can we have this backported to Teleport 9 as well?

**Comment by r0mant** [comment]
@EdwardDowling In terms of documenting this, let's update our Trusted Clusters guide to include a step that explains how to update the role map. For example, let's include a step before [Step 5](https://goteleport.com/docs/management/admin/trustedclusters/#step-55-remove-trust-between-your-clusters) that gives an example of updating the role map using `tctl create -f ....` command.

cc @alexfornuto - Edward will open a PR with this change to the docs and pass it on to you to wrap up.

**Comment by alexfornuto** [comment]
I just want to throw it out there that this issue is closed without docs changes, so there's currently nothing tracking the need to update the docs. Do we want to re-open this issue, or maybe create a new one to track the need?

**Comment by r0mant** [comment]
@EdwardDowling Did you verify that with this change updating trusted cluster role map via Terraform provider is now working as originally requested in https://github.com/gravitational/teleport-plugins/issues/622?

**Comment by EdwardDowling** [comment]
> @EdwardDowling Did you verify that with this change updating trusted cluster role map via Terraform provider is now working as originally requested in [gravitational/teleport-plugins#622](https://github.com/gravitational/teleport-plugins/issues/622)?

Tested with a local instance and it worked.

**Comment by EdwardDowling** [comment]
Doc changes have been merged now in https://github.com/gravitational/teleport/pull/19006
