### ISSUE TITLE
"tsh play" using a lot of memory for long sessions

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#10579]
### What

If the session to be replayed is long the "tsh play" consumes a lot of memory. For test session with ~200 MB of text it consumed ~1.7 GB of memory. Should be ~constant instead.

### Proposed solution

Investigate the source of memory usage. Optimize it so we stay at near-constant memory.

**Comment by zmb3** [comment]
Safari even warns about excessive memory usage when playing back via the web UI.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/7527103/170886399-49d70597-9578-4083-a2d2-493b68b08d0b.png">
