### ISSUE TITLE
`tctl users add` docs are incorrect, missing default `login` assignment

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#10574]
### What

Found during v9 beta tests.

The [docs](https://goteleport.com/docs/ver/9.0/setup/reference/cli/#tctl-users-add) and `tctl users add` command are out of sync:
1. ~`--logins` flag is not mentioned.~
2. ~`--windows-logins` flag is not mentioned.~
3. ~`--roles` are not mentioned.~
4. [Examples](https://goteleport.com/docs/ver/9.0/setup/reference/cli/#examples-12) are wrong and no longer work.
5. ~`--k8s-groups` and `--k8s-users` flags no longer exists (the flag cannot be set; UserCommand still has [kubeUsers](https://github.com/gravitational/teleport/blob/0602d7661f157e92364958187138b4028dc70c95/tool/tctl/common/user_command.go#L45) and kubeGroups).~
6. ~The docs suggest that `--logins` default to username when absent: "If unspecified the account will be mapped to an OS user of the same name." This is false.~

The [other docs](https://goteleport.com/docs/setup/admin/users/) we have on this topic should probably mention `--windows-logins` given Desktop Access is going GA. They also say that "If no OS login is specified, it defaults to the same name as the Teleport user", which no longer is true.

<br class="Apple-interchange-newline">

### Potential solution

1. Update the docs.
2. It isn't clear to me that removal of `--k8s-grups` and `--k8s-users` was intentional; potentially restore?
3. Implement dropped behaviour: defaulting `--logins` to username sounds like logical default. Right now it defaults to null, which means the newly created user cannot login. At the very least a warning should issues (going by the principle of least surprise).
4. Potentially do the same as above for `--windows-logins`.

**Comment by zmb3** [comment]
Would be nice to auto-generate this doc or just direct people to the `--help` output so that we don't constantly have docs going out of date. @ptgott what do you think?

I personally have never gone to a web page to see how to use a CLI and its various options - I always prefer `--help` as it's easier (don't have to go searching) and more likely to be accurate.

**Comment by Tener** [comment]
Python's [doctests](https://docs.python.org/3/library/doctest.html) come to mind - basically documentation that is verified to match with output of specific commands.

The reference docs have the big benefit of being searchable and indexed by Google.

Sometimes `--help` isn't that great too. For example `tsh scp --help` fails to demonstrate proper syntax for `from` and `to` parts of the command (host:path for remote, path for local).

```tsh scp --help
usage: tsh scp [<flags>] <from, to>...

Secure file copy

Flags:
  -l, --login                    Remote host login
      --proxy                    SSH proxy address
      --user                     SSH proxy user [tener]
      --ttl                      Minutes to live for a SSH session
  -i, --identity                 Identity file
      --cert-format              SSH certificate format
      --insecure                 Do not verify server's certificate and host name. Use only in test environments
      --auth                     Specify the type of authentication connector to use.
      --skip-version-check       Skip version checking between server and client.
  -d, --debug                    Verbose logging to stdout
  -k, --add-keys-to-agent        Controls how keys are handled. Valid values are [auto no yes only].
      --enable-escape-sequences  Enable support for SSH escape sequences. Type '~?' during an SSH session to list supported sequences. Default is enabled.
      --bind-addr                Override host:port used when opening a browser for cluster logins
  -J, --jumphost                 SSH jumphost
      --cluster                  Specify the Teleport cluster to connect
  -r, --recursive                Recursive copy of subdirectories
  -P, --port                     Port to connect to on the remote host
  -p, --preserve                 Preserves access and modification times from the original file
  -q, --quiet                    Quiet mode

Args:
  <from, to>  Source and destination to copy
```

**Comment by ptgott** [comment]
I think we should auto-generate our CLI reference (and, really, all the references we can get away with). If there's a script/make target we can run periodically, it shouldn't be much effort to maintain a docs page alongside the `--help` output.

**Comment by Tener** [comment]
This is basically what doctests do, except they explicitly require a review whenever the docs change. I think this is valuable to ensure someone reviews those changes, but that is a policy decision.
