### ISSUE TITLE
[v.8.0] /docs/pages/server-access/guides/vscode.mdx

### ISSUE THREAD

**Issue by ParinLL** [gravitational/teleport#10572]
## Details
I have the same issue as [Unexpected differences between remote.SSH.useLocalServer false and true](https://github.com/microsoft/vscode-remote-release/issues/4492)
After Trun off the remote.SSH.useLocalServer , It works
Please update the document for the setting field

### Category

- Improve Existing

**Comment by lsgunn-teleport** [comment]
As far as I can tell, this is fixed in https://goteleport.com/docs/server-access/guides/vscode/:

> Prior to connecting with a host, set the Remote.SSH: Use Local Server setting to false in the extension setting.
