### ISSUE TITLE
Playback of long (~200 MB) session crashes the browser tab

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#10578]
### Description

**What happened**:

Playback of session with single command ("find /") caused the browser (Google Chrome) to crash, after several seconds of wait. When measured with `tsh play` I found the session to be ~200 MB long.

**What you expected to happen**:

Playback working.

**Comment by schneider82** [comment]
This is an issue I'm also running into. I have a "Kiosk" running just Chromium. Once Teleport is installed, chromium constantly reboots, causing the BrowserMetrics to fill up. I can't find any report on why this happens, but the folder becomes HUGE in a few days, and the system crashes... Also, the kiosk is unusable, given the reboot.
