### ISSUE TITLE
Improve the "Deploy Teleport on Kubernetes" guide

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#10583]
## Details
Describe the documentation improvements you wish to see.
- [x] We should give examples of how to set CLUSTER_NAME and EMAIL environmental variables (also what value should CLUSTER_NAME reflect)
- [x] kubectl get services shows the service as `teleport-cluster` not `teleport-cluster-ent`
- [x] If you get a DNS name back for MYIP instead of an IPv4 address should update the docs on how to create the A records accordingly in the Route53 instructions.
- [ ] Instead of adding a normal user; give instructions for create a `teleport-admin` user like we do in the Getting Started guide. The user in the docs doesn't have full admin privileges based on just the `member` role.
- [ ] The member role created above doesn't show the k8s cluster in the UI either.

### Category

- Improve Existing

**Comment by ptgott** [comment]
We've moved this page to `docs/pages/deploy-a-cluster/helm-deployments/kubernetes-cluster.mdx`. I've updated the issue to indicate the items that we have completed.
