### ISSUE TITLE
"session_recording: proxy" causes unexpected side-effects and issues

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#10586]
### What

Discovered during v9 beta testing.

Enabling `session_recording: "proxy"` is causing unexpected side effects:

1. Seemingly doubled notification about session creation. Each time we will see:
```
tsh ssh graviton-node

Teleport > Creating session with ID: a7012025-db3e-45fa-b3a1-277893cbc3f9...

Teleport > User tener joined the session.

Teleport > Launching session...

Teleport > Creating session with ID: f18c2231-c218-49b4-b746-79bbace74bb4...

Teleport > User tener joined the session.

Teleport > Launching session...
```
2. From the 2 session IDs, only the second ("f18c2231-c218-49b4-b746-79bbace74bb4") above will be in audit log.
3. The active sessions are listed, but they cannot be joined either by Web UI or with `tsh join`. 
4. After finishing, "Session Recordings" tab does not display the node name. Instead "N/A" is shown.
5. In audit log the "Session started" event lacks "server_labels" and "server_hostname" information.

Note: the recording on its own *works*. After the session is finished `tsh play` works fine, playback with Web UI is functional too.

**Comment by xacrimon** [comment]
Caused in #8563, will investigate
