### ISSUE TITLE
regenerated UUID of teleport node if file 'host_uuid' is empty.

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#10613]
### What
teleport node start fails with error `WARN Host UUID "" is not a true UUID (not eligible for UUID-based proxying) service/service.go:667` and `Node failed to establish connection to cluster: missing parameter HostID, Get "[https://teleport.cluster.local/v2/cacert":](https://teleport.cluster.local/v2/cacert%22:) EOF. service/connect.go:68` if `host_uuid` file under `data_dir` is empty. 

`host_uuid` file can be empty if teleport process starts in a node, which is not connected to network or `host_uuid` file is manually emptied.

### How
If teleport node process find `host_uuid` file empty, it should generate UUID again, than failing to start.

### Why
Why do you need this?
In some automation cases, nodes might not be able to connect to teleport cluster at first startup, which can cause `host_uuid` file to be empty (There may be other scenarios which can cause it). teleport node process should be able to re-generate UUID, if its not already present in teleport cluster.

### Workaround
If a workaround exists, please include it.

Manual removal teleport data_dir and restart of teleport process on node fixes it. But in some automation usecases, it might not be a good option.

**Comment by pschisa** [comment]
Its possible there is a patch in upstream Teleport (tagged as [v10.0.0-roman.1](https://github.com/gravitational/teleport/commit/62173e096b35e259ef0aba54e08a11dd3ed6b33d) ) that may fix the issue by moving to a UUID generation library that correctly panics when no entropy is available on the system (the old library, pborman/uuid returns nil when there is a randomness issue and teleport/lib/utils/utils.go [L458](https://github.com/gravitational/teleport/blob/19627ee51e2f8d4ab8db7902de625bb9c12cd00c/lib/utils/utils.go#L458) will write an empty string to the file causing the bug)

**Comment by r0mant** [comment]
@atburke When you get to this, in addition to making sure Teleport correctly exits when UUID generation fails, let's also make sure that we exit with a proper error message instead of panicking, it would be a better UX.
