### ISSUE TITLE
Provide MacOS Arm instructions for Terraform

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#10614]
## Details
The instructions for MacOS Teleport Terraform provider only mention darwin version.  A Terraform user on arm64 has to compile the Terraform and must use the latest Terraform version, 1, not 0.12. 

### Category
- Improve Existing

**Comment by webvictim** [comment]
You can compile the Terraform provider on `darwin/arm64` using instructions here: https://github.com/gravitational/teleport-plugins/tree/master/terraform

We should definitely get this arch automatically published to the Terraform repo too. @tcsc Do we have an issue tracking this or a plan for it?

**Comment by pschisa** [comment]
Tracking issue for actual ARM/M! builds here: https://github.com/gravitational/teleport-plugins/issues/539

**Comment by lsgunn-teleport** [comment]
@webvictim, is there a documentation issue here? The instructions are for compiling/testing the plugin. 
The doc page is about using the plugin:
https://goteleport.com/docs/management/dynamic-resources/terraform-provider/

Can you clarify whether changes need to be made to the documentation page?

**Comment by webvictim** [comment]
I think this whole issue can be closed now; we started publishing the Terraform provider a while back and the instructions in the docs now work out of the box on MacOS and Linux.
