### ISSUE TITLE
Support CockroachDB for Audit Log storage

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#10627]
### What
Currently, there is no self-hosted storage solution for Audit Log storage.  Request is to have CockroachDB be used as a storage solution for self-hosted audit log storage

### Why
Allow HA self-hosted environments to store audit logs and view audit logs in Teleport

**Comment by espadolini** [comment]
This will be closed by the implementation of #15771.

**Comment by espadolini** [comment]
We use a BRIN index for the column that records when an audit log event is created (for the purpose of deleting it after the retention period), which is not supported in CRDB, so the `pgevents` backend won't actually work as is on CRDB. The issue can be manually worked around by applying the schema manually (and ideally by using [CRDB's ttl deletion](https://www.cockroachlabs.com/docs/stable/row-level-ttl) and disabling the Teleport-initiated one) but we should keep this open until we tweak the events
backend to do this automatically or with some config option.

**Comment by zmb3** [comment]
We have no plans to support cockroach. This issue was motivated by the lack of a self hosted audit log backend, which we now have with Postgres.
