### ISSUE TITLE
Prepare high-priority docs sections for Cloud users

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#10631]
## Details
Various docs pages contain information that is incorrect or irrelevant for Cloud users. Let's ensure that, when a user selects "Cloud" using the scope switcher, they only see relevant information. The product team has come up with a list of sections to prioritize. 

We'll track progress with a separate issue for each section. 

|Section|Linked issue|Number of pages|
|---|---|---|
|Setup|#10633|38|
|Server Access|#10634|10|
|Kubernetes Access| #10636|18|
|Database Access|#10637|25|
|Access Controls|#10638|12|

Here are some related issues that we can probably close after resolving this one:
- https://github.com/gravitational/teleport/issues/9950
- https://github.com/gravitational/teleport/issues/8477
- https://github.com/gravitational/teleport/issues/7020

### Category

- Improve Existing

**Comment by ptgott** [comment]
We have one more guide to merge from #10633. After that, this issue will be resolved.

**Comment by michaelmcallister** [comment]
Hi @ptgott - I can see that #10633 is merged. Is this issue considered resolved?

**Comment by ptgott** [comment]
@michaelmcallister Thanks for the nudge! This issue can be considered resolved.
