### ISSUE TITLE
Prepare docs guides in the Server Access section for the Cloud

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#10634]
## Details
As explained in https://github.com/gravitational/teleport/issues/10631, we want to edit docs pages in high-priority sections to show only relevant information to users who have selected "Cloud" in the scope switcher. This issue focuses on the Server Access section.

### Pages to edit
I generated a table of pages to edit by running the following script from the root of my `gravitational/teleport` repo clone:

```bash
$ echo "|Slug|PR|" && echo "|---|---|" && cat docs/config.json | jq '.navigation[] | select(.title=="Server Access").entries[] | recurse(.entries[]?) | .slug' | sed -E 's/(^.*$)/|\1||/'
```

Here is the output:

|Slug|PR|
|---|---|
|"/server-access/introduction/"|N/A: Currently relevant for both Cloud and Self-Hosted Teleport users|
|"/server-access/getting-started/"| #11470|
|"/server-access/guides/"|N/A: index/menu page|
|"/server-access/guides/ssh-pam/"|#11419|
|"/server-access/guides/tsh/"|#11419|
|"/server-access/guides/openssh/"|#11470|
|"/server-access/guides/bpf-session-recording/"| #11381 |
|"/server-access/guides/restricted-session/"| #11381 |
|"/server-access/guides/vscode/"|N/A: Already edited to accommodate Cloud users|

### Category
- Improve Existing

**Comment by wadells** [comment]
Re the openssh config, we definately had someone looking for this info today:

https://goteleport.slack.com/archives/CEZH6UL64/p1646423807471249

> I'm experimenting with Teleport Enterprise on the cloud.  I'm trying to follow the steps outlined at https://goteleport.com/docs/server-access/guides/openssh/ for compatibility with OpenSSH.  I'm wondering how I edit the auth server config to enable "recording proxy" mode when it seems like I don't have access to the auth server.

I'm researching this now -- add me as a reviwer or let me know if you have questions during docs development.

**Comment by ptgott** [comment]
All linked PRs have been merged.
