### ISSUE TITLE
Trusted cluster role mapping scalability

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#10630]
### What
Currently, a trusted cluster `role_map:` requires that a role explicitly be defined on the root cluster to map to leaf clusters.  This can have scaling issues if managing many leaf clusters through a single root with unique access patterns or attempting a 1-1 mapping of leaf cluster roles to root roles.  

One option is to allow SSO claims/attributes passed in on the root login to be available to a leaf cluster so that trusted cluster role mappings can reference external claims for mapping to a role instead of an existing root cluster role.

Another option is to allow the Teleport username to be used as match criteria for role mapping rather than a Teleport role

Trusted clusters have become a more important feature because even when using a `tsh login --proxy` to switch between non-trusted Teleport clusters with valid credentials still prompts the full SSO login workflow.  This is disruptive to end user workflows.  If this issue can be addressed then the trusted cluster scalability issues are not as much a concern.

### Workaround
Revisit how roles are assigned at the root cluster and focus root cluster roles around access patterns by end user teams rather then pushing leaf cluster roles to the root for a 1x1 mapping

**Comment by russjones** [comment]
@pschisa This should be doable today, can you try and tell us if it does not?

https://goteleport.com/docs/setup/admin/trustedclusters/#sharing-user-traits-between-trusted-clusters

**Comment by russjones** [comment]
@pschisa I'm going to close this one since it looks like it's working and remove it from the Queue. If you think it needs to be re-opened, re-open and ping us on Tuesday to take a look, we'll add it back to the queue.
