### ISSUE TITLE
Prevent kubectl commands needing per-command MFA when using per-session MFA

### ISSUE THREAD

**Issue by nickbrennan1** [gravitational/teleport#10661]
When using per-session MFA with Teleport and kubernetes, this requires the user to enter their 2FA each time they run a kubectl command:

```
▶ kubectl get po
Tap any security key or enter a code from a OTP device:
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          5d14h

~/terraform/simple-cluster
▶ kubectl get po
Tap any security key or enter a code from a OTP device:
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          5d14h

~/terraform/simple-cluster
▶ kubectl get po
Tap any security key or enter a code from a OTP device:
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          5d14h
```

This is extremely disruptive when interacting with the Kubernetes layer.

When running kubectl commands with per session authentication, it would be useful to have the kubectl commands behave like short lived TTL certificate, ie 5 minutes, so the user does not have to enter MFA for each individual command.

**Comment by ravicious** [comment]
It looks like we have a similar feature request here: #7568.

**Comment by zmb3** [comment]
Closing in favor of #7568
