### ISSUE TITLE
Teleport node sqlite schema create table failure

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#10713]
### Description

**What happened**:
Customer launched a Teleport SSH node and observed the logs noted below on start causing a continuous crash. Customer deleted `/var/lib/teleport` dir and everything came up as expected.

### Server Details
- Teleport version (run `teleport version`): 8.1.5

### Debug Logs
```
09:32:58 germainb@chi-super-init.nasdaq.com log $ tail -50 teleport.log
2022-02-14T09:32:58-05:00 ERRO [SQLITE]    "Failing schema step: CREATE TABLE IF NOT EXISTS kv (\n           key TEXT NOT NULL PRIMARY KEY,\n           modified INTEGER NOT NULL,\n           expires DATETIME,\n           value BLOB);\n        CREATE INDEX IF NOT EXISTS kv_expires ON kv (expires);, file is not a database." lite/lite.go:251
ERROR: error creating schema: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF
initialization failed
file is not a database
```

gz#4071

**Comment by philip-teleport** [comment]
I've hit the same error on 9.0.0 after clearing out the `journalctl` logs on a SSH node.
```
sudo journalctl --rotate
sudo journalctl --vacuum-time=1s
```
Error Log:
```ERRO [SQLITE]    "Failing schema step: CREATE TABLE IF NOT EXISTS kv (\n           key TEXT NOT NULL PRIMARY KEY,\n           modified INTEGER NOT NULL,\n           expires DATETIME,\n           value BLOB);\n        CREATE INDEX IF NOT EXISTS kv_expires ON kv (expires);, file is not a database." lite/lite.go:246
ERROR: error creating schema: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF
initialization failed
file is not a database
```
Running the same commands on the instance hosting my Teleport proxy-auth had no impact.

**Comment by espadolini** [comment]
Are you by any chance rotating files in `/var/lib/teleport/proc`?

**Comment by espadolini** [comment]
The `SQLITE_NOTADB` error ("file is not a database") on what _should_ in fact be a database points to database corruption, but it's hard to figure out what happened without the logs immediately preceding the problem. I doubt that it's possible to fix the actual database file so clearing out `/var/lib/teleport/proc` (or the whole of `/var/lib/teleport`) was the correct course of action.

@Aharic does the customer have the last process logs before the problem started?

**Comment by zmb3** [comment]
@Aharic @philip-teleport I'm marking this one as inactive and will close it in 1 week if there is no additional activity.

**Comment by philip-teleport** [comment]
I'm happy for this to be closed. I've been clearing out `journalctl` logs regularly since without issue.
