### ISSUE TITLE
[WINDOWS_D] Session has encountered slow writes

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#10753]
### Description

**What happened**:
While testing Teleport Desktop Access, I noticed this message. At first I thought it was an issue with a small host `t2.micro` but I bumped to a `t3.large` and still noticed the message. What are the specs needed for the Teleport Desktop Access / Windows service?

```
2022-03-02T04:46:38Z DEBU [WINDOWS_D] Session has encountered 554 slow writes out of 12860. Check disk and network on this server. events/auditwriter.go:404
```

**Comment by zmb3** [comment]
These are nothing to worry about for now. The audit writer is capable of handling this - it's heuristics are just based on SSH sessions and we need to tweak it a bit for desktop.

**Comment by zmb3** [comment]
in https://github.com/gravitational/teleport/pull/15808 I tweaked the debug logging here so we only print this message if > 15% of writes are slow.
