### ISSUE TITLE
We are missing Redis, MariaDB, Microsoft SQL Server from DB Dropdown

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#10757]
### Description

**What happened**:

While Testing Teleport 9, we are missing DB Type for the drop down. Teleport 9 will have Redis, MariaDB, Microsoft SQL Server, we should add these options. 

Docs for 
- Active Directory SQL Server https://goteleport.com/docs/ver/9.0/database-access/guides/sql-server-ad/ 
- MariaDB https://goteleport.com/docs/ver/10.0/database-access/guides/mysql-self-hosted/ 
- Redis Docs PR https://github.com/gravitational/teleport/pull/10693

<img width="640" alt="image" src="https://user-images.githubusercontent.com/559288/156427828-9e1f2709-7c83-40e1-bd10-c252708da06f.png">
<img width="983" alt="image" src="https://user-images.githubusercontent.com/559288/156428401-f5e8e609-74ec-4d8b-81aa-a16ff8b961a9.png">

**Comment by pierrebeaucamp** [comment]
Cloud is waiting for release 9.1.0
