### ISSUE TITLE
Visual Artifacts with Teleport Desktop Access

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#10751]
### Description

**What happened**:

While testing Teleport 9.beta. I found a few pages caused this visual artifact. 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/559288/156421999-9d849f0e-d384-4773-89ba-81b60977f04e.png">
<img width="434" alt="image" src="https://user-images.githubusercontent.com/559288/156422014-092d01ca-6984-4a76-9a3d-0ff0ce2483c9.png">

To replicate view https://teleport-9a.asteroid.earth/

### Server Details
- Teleport version (run `teleport version`): 9.0.0-beta.1

**Comment by zmb3** [comment]
If you see this again, I'd be curious to know if it also appears this way in the session recording.

**Comment by zmb3** [comment]
@benarent have you ever seen this occur since the original report?

I have a feeling this one is going to be hard to reproduce, so unless it's a constant problem I don't know there's much more to be done here.

**Comment by benarent** [comment]
I've not seen it recently, but If I do I'll open it again
