### ISSUE TITLE
F1-F5 hotkeys not working

### ISSUE THREAD

**Issue by sergeygolubev** [gravitational/teleport#1076]
Hi all!

We have problem in our Teleport installation for some unknown reason  
keys F1 F2 F3 F4 F5 not working

in some cases in console key F1 prints symbol "P" , F3 prints symbol "R"

Thanks

**Comment by alex-kovoy** [comment]
Could you provide more detail? Is it web terminal? What is your OS/Browser version?

**Comment by kontsevoy** [comment]
yes, which terminal app too. there is a huge matrix of possibilities of what "console" may mean. marking as "invalid" for now.
