### ISSUE TITLE
`tctl get all` ignores `--with-secrets` flag, always shows secrets

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#10798]
### Description

**What happened**:

Since the first implementation, `tctl get all` implementation contained the line: [`rc.withSecrets = true`](https://github.com/gravitational/teleport/commit/05f3eeaf004af5e8a854401d117e83be95c9375e#diff-0ded7335cb699ba03c82523badbb1b4dd5db4e605d34b89b26b88e3942e1f94dR184). This causes it to disregard completely `--with-secrets` and `--no-with-secrets` flag and always print secrets. While useful in some contexts, it is also a massive foot gun and security leak waiting to happen due to unaware users.

Nowhere in the docs is this behavior mentioned; to the contrary, we do have two usages of `tctl get all` with explicit `--with-secrets` flag. I believe this indicates that the author of the doc was unaware of this behavior too, and so will be the future users:

1. https://goteleport.com/docs/kubernetes-access/helm/guides/migration/#step-4-extracting-the-contents-of-teleports-database
2. https://goteleport.com/docs/setup/operations/backup-restore/#migrating-backends

**What you expected to happen**:

The flag is respected, no overwrite happens.

### Suggested resolution

1. My personal preference: remove the single line causing the override, restoring the standard behavior. Add warning about breaking change to release notes.
2. Alternative: Revise docs to mention the behavior with an ample warning. Update the `--help` message to do the same.

**Comment by Tener** [comment]
@xinding33 @klizhentas @r0mant @fspmarshall @smallinsky 

A penny for your thoughts. I may have overreacted yesterday seeing private keys where I didn't expect them to be seen 😓  but I can imagine a scenario where this exact behavior leaks to a security incident for one of the customers, which would be less than ideal.

**Comment by smallinsky** [comment]
We don't support `--no-with-secrets` flag and don't any doc for it.  The`--no-with-secrets`  flag is superficially added by our CLI flag parsing library. 

The `tctl get all` call creates a bootstrap file and creating a bootstrap file without secrets doesn't make any sense.

Agree that for a user perspective the behavior of `tctl get all` that dumps the secrets is not fully transparent thus we can force a user to provide `--with-secrets` flag during `tctl get all` to acknowledge the fact that secrets will be dumped.  Also we can return an error if `--with-secrets` was not provided or for some reason  users called `tctl get all --no-with-secrets` and updated the docs.
