### ISSUE TITLE
Improve metrics readyz/healthz documentation around recovery and probing

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#10799]
## Details
https://goteleport.com/docs/setup/reference/metrics/ provides minimal documentation how the metrics endpoints function.

Request is to add further details such as the probing interval and if that can be influenced on these endpoints.  This will help customers understand expectations on recovery times, which is crucial if using these endpoints for health checks.

### Category
- Improve Existing

**Comment by russjones** [comment]
@zmb3 Let's find out how much time it takes to recover and update documentation.
