### ISSUE TITLE
Version 8.3.3 not available via apt repository

### ISSUE THREAD

**Issue by alexmv** [gravitational/teleport#10800]
### Description

**What happened**:

```
# apt-get update
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://deb.releases.teleport.dev stable InRelease
Fetched 3483 B in 1s (3978 B/s)
Reading package lists... Done

# apt-cache policy teleport
teleport:
  Installed: 8.3.2
  Candidate: 8.3.2
  Version table:
 *** 8.3.2 500
        500 https://deb.releases.teleport.dev stable/main amd64 Packages
        100 /var/lib/dpkg/status
```

And we can check the apt source directly, and find it only has 8.3.2:
```
# curl -s https://deb.releases.teleport.dev/dists/stable/main/binary-amd64/Packages | grep -A1 Package
Package: teleport
Version: 8.3.2
--
Package: teleport-ent
Version: 8.3.2
--
Package: teleport-ent-fips
Version: 8.3.2
```

**What you expected to happen**:

8.3.3 is a security release, and was [released 16 hours ago](https://github.com/gravitational/teleport/releases/tag/v8.3.3).  It should ideally be easy to upgrade to get the security fixes in a timely fashion. :)

See also: #9770, #8166

**Comment by r0mant** [comment]
@alexmv Sorry about the issue - looks like our deb publishing pipeline didn't kick in due to the 9.0.0-beta.1 release already being present which it considered the latest. cc @wadells 

In the meanwhile, you can download 8.3.3 .deb package directly: https://get.gravitational.com/teleport_8.3.3_amd64.deb.

We'll fix the pipeline and publish 8.3.4, I'll update/close this issue after that.

**Comment by alexmv** [comment]
Yup, I pulled the .deb from https://get.gravitational.com/, but I figured it was worth filing a bug for.

Thanks for the quick fix!

**Comment by r0mant** [comment]
8.3.4 is published and should be available in the deb repo now.
