### ISSUE TITLE
Add `--logins` support to `tctl bots add`

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#10814]
Right now when you `tctl bots add foo --roles=access` you can only login using the hardcoded logins defined within your role.

It would be nice to be able to do `--logins=foo,bar` to add traits to the user created so `{{internal.logins}}` can be correctly filled out per-bot user.

**Comment by strideynet** [comment]
This is unfortunately a little more complex than it first appears. I've done a quick test to add a logins trait to the bot user, and this isn't reflected in the role impersonation certificates.
