### ISSUE TITLE
Support Casbin as the authorization backend

### ISSUE THREAD

**Issue by hsluoyz** [gravitational/teleport#1082]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

I think it's more powerful than the current RBAC in teleport. So I want to hear your opinions. Let me know if you have any questions:)

**Comment by kontsevoy** [comment]
@hsluoyz you have a cool project, congrats. we do not really see any advantages of using it though. Teleport (and SSH in general) RBAC requirements are fairly modest, compared to more complex systems. It feels like learning and auditing Casbin is not worth the time savings we'd get by DIY.

Besides, Casbin's data formats are not compatible with Teleport system, which is closely aligned with Kubernetes formats (JSON/YAML with standardized "signatures").

**Comment by hsluoyz** [comment]
Hi @kontsevoy ,

Thanks for the reply!

> you have a cool project, congrats. we do not really see any advantages of using it though. Teleport (and SSH in general) RBAC requirements are fairly modest, compared to more complex systems. It feels like learning and auditing Casbin is not worth the time savings we'd get by DIY.

If you are worried about the dev effort about Casbin, I can make the PR to do the integration. If the learning is about the the user learns to use Casbin policy, I think it's fairly not too much difference with a DIY policy.

> Besides, Casbin's data formats are not compatible with Teleport system, which is closely aligned with Kubernetes formats (JSON/YAML with standardized "signatures").

Casbin uses adapters to adapt to different data formats, so it can support JSON if you like. And what do you mean by standardized "signatures"?

**Comment by kontsevoy** [comment]
@hsluoyz "signatures" means that every structure starts with a standardized header with certain fields that are guaranteed to be present, like all Kubernetes resources, here's an example:

```
# standard fields:
apiVersion: v1
kind: Pod
metadata:
  name: example-app
  labels:
    app: example-app
    version: v1
    role: backend
spec:
  # structure-specific fields
```
