### ISSUE TITLE
issue add users

### ISSUE THREAD

**Issue by yusranad0404** [gravitational/teleport#10832]
I have been add new users when I delete the tokens and user for recreating I got error that **Invitation Code Expired**

**Comment by stevenGravy** [comment]
hi @yusranad0404 I'd recommend posting your commands and output to the slack community channel where multiple folks could help. https://goteleport.com/slack

**Comment by russjones** [comment]
@yusranad0404 As @stevenGravy please post commands and output to our Slack channel. I'll close this ticket for now.
