### ISSUE TITLE
Clarify ADFS Getting Started Guide

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#10848]
## Details
Feedback from a user who is new to ADFS. Some inconsistencies in our guide (https://goteleport.com/docs/enterprise/sso/adfs/#enable-adfs-authentication) with group names. In one screenshot we reference a group called `teleportadmins` and later on in the guide, we reference that group in the yaml config as `Administrators`. See screenshots for reference:

![Screen Shot 2022-03-04 at 8 39 29 AM](https://user-images.githubusercontent.com/1424442/156774346-682cd577-29b7-4a79-891b-8f029d4e6817.png)

![Screen Shot 2022-03-04 at 8 41 37 AM](https://user-images.githubusercontent.com/1424442/156774355-4972b78c-971c-41f1-984f-6c1dede5b467.png)

### Category

- Improve Existing

**Comment by ptgott** [comment]
@alexfornuto Is this something you ran into when looking at this guide?
