### ISSUE TITLE
No way to set `logins` and `windows_logins` traits for users with Web UI

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#10850]
### What

Bring the Web UI to feature parity with `tctl users add` with respect to `--logins` and `--windows-logins` flags.

### How

There are a few complimentary options, with varying amounts of work behind them:

1. Additional fields for `logins` and `windows_logins` when creating a local user
2. A way to edit `logins` and `windows_logins` for the existing local users.
3. Fully-blown trait editor for local users.
4. Automatically assign `logins` and `windows_logins` for new users (they stay empty now).

### Why

To avoid the possible unhappy path, which happened to me:

```
1. Create a new user `foobar` with Web UI
2. Login as `foobar` with tsh
3. Attempt to login to 
4. Spend precious time debugging the issue, get frustrated
5. Discover the user does not have any logins assigned from and roles have no hardcoded ones
6. `tctl get users/foobar > foobar.yaml`
7. Edit `foobar.yaml` manually, adding the traits.
8. `tctl create -f foobar.yaml`
```

There is no guarantee anyone gets past step 5. Those that will are likely to be frustrated by the speed bump. 

Furthermore, forcing the user to fall back to console-level editing (steps 6-8) is bad UX. There is also a non-zero chance of slip-ups at step 7. as they have to consult the docs to do this properly.

### Workaround

None.

**Comment by zmb3** [comment]
Duplicate of #9790, right?

**Comment by Tener** [comment]
> Duplicate of #9790, right?

Ah, sure looks like it. Thanks for pointing it out!
