### ISSUE TITLE
The password/mfa prompt isn't shown if the client cert is expired when running kubectl 

### ISSUE THREAD

**Issue by rosskusler** [gravitational/teleport#10868]
### Description

**What happened**:
When my teleport login certificate has expired (after X hours) and I run a kubectl command, it appears to just hang. It does not display a prompt for the password or MFA token. Through some experimentation I have discovered that it IS waiting for me to enter my password and MFA token so that I can re-authenticate and get an updated certificate, but it doesn't actually show a request for password/token so it just appears to be hanging. 

Obviously when I just run tsh directly (tsh kube ls) it does prompt me to log back in. I think the problem is that when logging in, tsh prints the prompts for password/token to stdout which gets eaten by kubectl. It might work if it sent the prompts to stderr, which (in my testing at least) does get passed back from kubectl to the console.

**What you expected to happen**:
I would expect to see the prompt for 'Enter password for Teleport user XYZ' like I do when I run tsh commands directly.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Login to tsh from the command line 
2. Run 'kubectl get pods' and observe that it works
3. Wait several hours until the teleport client certificate has expired
4. Run 'kubectl get pods' and observe that it APPEARS to hang (it's really just waiting for you to enter the password, unprompted)

### Server Details
- Teleport version (run `teleport version`): v8.0.0-alpha.1
- Server OS (e.g. from `/etc/os-release`): 20.04.3 (it is the teleport docker image)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): k8 on dedicated hardware
- Additional details:

### Client Details
- Tsh version (`tsh version`): v8.1.0
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues): n/a
- Installed via (e.g. apt, yum, brew, website download): website download
- Additional details:

#### NOTE: I modified the ~/.kube/config to add --debug to the 'tsh kube credentials' command temporarily

$ kubectl get pods
INFO [CLIENT]    no host login given. defaulting to myuser client/api.go:1102
ERRO [CLIENT]    [KEY AGENT] Unable to connect to SSH agent on socket: "". client/api.go:2959
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/myuser/.tsh/keys/teleport.mydomain.com/myuser-x509.pem" valid until "2022-03-03 12:55:04 +0000 UTC". client/keystore.go:283
DEBU [KEYSTORE]  Reading certificates from path "/Users/myuser/.tsh/keys/teleport.mydomain.com/myuser-ssh/teleport.mydomain.com-cert.pub". client/keystore.go:306
INFO [KEYAGENT]  Loading SSH key for user "myuser" and cluster "teleport.mydomain.com". client/keyagent.go:180
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/myuser/.tsh/keys/teleport.mydomain.com/myuser-x509.pem" valid until "2022-03-03 12:55:04 +0000 UTC". client/keystore.go:283
DEBU [TSH]       Requesting TLS cert for kubernetes cluster "k8vs1-sea" tsh/kube.go:106
INFO [CLIENT]    Connecting proxy=teleport.mydomain.com:3023 login="-teleport-nologin-50c8dd69-6292-4e54-bbd9-c297d1a02e1c" client/api.go:2156
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com STRIPPED ." client/keyagent.go:338
DEBU [KEYAGENT]  Validated host teleport.mydomain.com:3023. client/keyagent.go:344
DEBU [CLIENT]    "Activating relogin on failed to authenticate with proxy teleport.mydomain.com:3023\n\tssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain." client/api.go:517
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport.mydomain.com:443 client/api.go:2924
DEBU             Attempting GET teleport.mydomain.com:443/webapi/ping webclient/webclient.go:62

**Comment by russjones** [comment]
@xacrimon I know you fixed some issues around this recently. Do you know if this is still an issue?

@rosskusler I see that you are running `8.0.0-alpha.1`, this may have recently been fixed, can you try with the latest release?

**Comment by rosskusler** [comment]
This does appear to be fixed in Teleport v9.0.2 git:v9.0.2-0-g354b8c037 go1.17.7.

Thank you!
