### ISSUE TITLE
Proxy Peering - reverse tunnel count

### ISSUE THREAD

**Issue by dboslee** [gravitational/teleport#10867]
I wanted to propose a change to the design described in #9132 for handling graceful shutdowns and proxy initiated reconneced. You can read more about this behavior in the RFD [here](https://github.com/gravitational/teleport/blob/7b85f709f6aecee8deea2c372be79388cf02639f/rfd/00XX-proxy-peering.md#reverse-tunnel-agent-pool).

Rather than amend the RFD, I am proposing this here to avoid blocking the initial implementation from being completed. However if this gets approval quickly it shouldn't be too difficult to add to the initial implementation. 

### What
The idea is to add a configuration for `ReverseTunnelCount` to the `ClusterNetworkingConfig` to configure the number of reverse tunnels connections an AgentPool creates when `ProxyPeering` is enabled. This  would also be added to the teleport config under the `auth_service` section as `reversetunnel_count`. The value must be >= 1 and the default value would be 1. Just to reiterate this value will only change the reverse tunnel behavior if proxy peering is enabled.

### How
AgentPools retrieve the latest `ClusterNetworkingConfig` when creating a new agent. If proxy peering is enabled this value would determine how many reverse tunnels the agentpool maintains.

### Why
This seems like a more graceful approach than the one I outlined in #9132 which requires the proxy to send a reconnect to the agent during graceful shutdowns to minimize the time an agent is unreachable through any proxy. High availability of agents can be achieved by settings this value to `2` or greater while still solving the scalability issues of the current agent behavior which requires the agent to connect to every proxy instance. Agent connections can be closed without any extra signaling and the agent will still be reachable through another proxy if configured properly.

### Further discussion
Open to suggestions on the naming of `ReverseTunnelCount`

Credit to @somethingnew2-0 for this suggestion [here](https://github.com/gravitational/teleport/pull/9132#discussion_r806179977)

**Comment by dboslee** [comment]
@russjones @rosstimothy @NajiObeid @knisbet Could I get some thoughts on this? As I said above I don't want to add scope and block the initial implementation so I'm not adding this to the RFD but if we could get approval on the additional configuration parameter it doesn't seem difficult to add.

**Comment by NajiObeid** [comment]
my only comment would be to merge both configs into something like:
```
auth_service:
  proxy_peering:
    enabled: yes
    reversetunnel_count: 2
```

**Comment by somethingnew2-0** [comment]
Thank you for adding this, LGTM!

**Comment by dboslee** [comment]
After some discussion [here](https://github.com/gravitational/teleport/pull/10223#discussion_r820754965), I am thinking something like this will work:
```
auth_service:
  tunnel_strategy:
    type: "proxy_peering"
    connection_count: 2
```

This will allow us to support other `tunnel strategies` in the future each with its own set of additional parameters.
