### ISSUE TITLE
Allowing user access per group of nodes

### ISSUE THREAD

**Issue by Vish0007** [gravitational/teleport#1086]
Is there a way to allow user access to a group of nodes in the teleport cluster?
For example, there is a teleport cluster with 100 nodes(with 10 storage nodes) and there is user 'A' .
user 'A' is storage admin and should be allowed access only those 10 storage nodes.
Also, as an admin i want to expire the user 'A' within for example 5hrs.
How can we do this in Teleport?

**Comment by kontsevoy** [comment]
This is a part of role-based access control (RBAC) and is done via Roles and node labels, only available in [enterprise teleport](http://gravitational.com/teleport/docs/2.0/enterprise/#rbac)

**Comment by Vish0007** [comment]
@kontsevoy thanks for sharing this.
On the link, 
1. its mentioned about session TTL. Does the user gets deactivated/deleted after TLL timeout? and needs to be re-provisioned again?
2. how we can add labels to nodes? Can you please point me the API to list nodes and  its attributes (including labels)

Is there a slack channel to discuss certain features, developers doubts  code base

**Comment by kontsevoy** [comment]
@Vish0007

1. When the certificate expires (TTL) it becomes invalid, i.e. a user will remain in the system but won't be able to log in. 
2. Nodes are labeled as shown in the [docs](http://gravitational.com/teleport/docs/2.0/admin-guide/#labeling-nodes)

Yes, do we provide a Slack channel and a ticket-based support for enterprise customers

**Comment by Vish0007** [comment]
@kontsevoy can you please point me to the command/flow on how set the TTL for a user?
Is the TTL for user information maintained by the auth server? what happens to sessions which are ongoing but TTL is expired?

**Comment by kontsevoy** [comment]
@Vish0007 see the "User role" example in [this chapter](http://gravitational.com/teleport/docs/2.0/enterprise/#rbac), specifically `max_session_ttl` setting. When TTL expires, Teleport does not terminate ongoing sessions, this is now becoming somewhat popular feature request.
