### ISSUE TITLE
Teleport does not wrap long lines correctly upon first login.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1087]
**Problem**

On initially connecting to a Teleport node, long lines of text don't wrap correctly until terminal is resized.

**Reproduction**

1. Start Teleport.
1. Open `Terminal.app` and resize to 80x24.
1. Use `tsh` or `ssh` to connect to a Teleport node.
1. Paste `aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggghhhhhhhhhhiiiiiiiiiijjjjjjjjjjkkkkkkkkkkllllllllllmmmmmmmmmmnnnnnnnnnnoooooooooopppppppppp` in `Terminal.app`.
1. You'll see something like `nnooooooooooppppppppppiiiiiiiiijjjjjjjjjjkkkkkkkkkkllllllllllmmmmmmmmmmnnnnnnnn`. This is incorrect.
1. Resize `Terminal.app` and you'll see the text wrap correctly.
1. Paste another long line and you will see text wrap correctly.

**Comment by aashley** [comment]
This also happens in linux on gnome-terminal 3.18.3, mate-terminal 1.12.1, xterm(322). Resizing the window doesn't help with these. And despite comments in #926 this only occurs in tsh, all other apps wrap correctly.

**Comment by kontsevoy** [comment]
@aashley I am having a problem interpreting "all other apps" comment. `tsh` is basically a tunnel connecting your terminal app (gnome-terminal) to a server-allocated PTY. Then _on top_ of that you're running CLI apps like `bash`. This bug is about `tsh` not communicating the size of the server-allocated PTY to gnome-terminal which leads to this behavior.

What we're trying to determine how can this be reproduced for BOTH use cases:
* incorrect behavior with `tsh`
* correct behavior with `ssh`

**Comment by aashley** [comment]
I'm not sure how else to reproduce this. It happens on every connection through tsh for me.

1. Start gnome-terminal with bash as shell.
1. connect to remote server using ssh starting bash remotely
1. type long text and it wraps onto new line correctly, resize gnome-terminal continues to wrap correctly
1. connect to same remote server using tsh starting bash remotely
1. type long text and it wraps onto the same line, resize gnome-terminal and continues to wrap incorrectly.

If I launch byobu within the tsh connection it takes over and the wrapping works correctly. It only when in the basic shell directly in tsh that the wrapping fails for me. I've only tested with bash though.

**Comment by kontsevoy** [comment]
@aashley gotcha, this is perfect (regular `ssh` appears to work perfectly). Which Gnome version you're on? We'll try to nail this one for 2.4

**Comment by aashley** [comment]
Not actually using gnome, using Ubuntu Mate 16.04 with the earlier mentioned terminals and versions.

**Comment by patrobinson** [comment]
I have a similar issue using iTerm 2 on MacOS X Sierra. When connecting to a host with ssh, the terminal wraps commands correctly. When connecting with `tsh` it does not until I resize the window

**Comment by kontsevoy** [comment]
I tried 2.4 and cannot reproduce it. WIll try again later, but punting for now.
