### ISSUE TITLE
Add Kubernetes Access and Database Access support to Machine ID

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#10890]
Machine ID does not support setting the following fields for user certificates. These fields are needed for Machine ID to support Kubernetes Access and Database Access.

* `kubernetes_labels`, `kubernetes_users`, and `kubernetes_groups` for Kubernetes Access
* `db_labels`, `db_users`, and `db_names` for Database Access

**Comment by timothyb89** [comment]
Quick summary of progress so far:
 - Database access requests were added in https://github.com/gravitational/teleport/pull/11904, however this doesn't support proxying so multiplexed servers will not work
 - Partial support for tsh was added in https://github.com/gravitational/teleport/pull/11596, which allows use of `tsh -i ...`. Unfortunately this does not support database access.

Remaining items:

- [ ] Database access support for `tsh -i` (https://github.com/gravitational/teleport/issues/11770)
- [ ] Kubernetes requests
- [ ] Kubernetes config generation and `tsh` integration if necessary

**Comment by zmb3** [comment]
@timothyb89 are we good to close this one?

**Comment by timothyb89** [comment]
Yup, it's merged and will be in 10.1!
