### ISSUE TITLE
Make local login always available

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1090]
## Problem

For SAML/OIDC scenario we have the following problems:
* If you just set, say, OIDC auth in config, you cannot get to the admin UI to configure OIDC. What's the point of even having OIDC configuration UI then if you can only use CLI to set everything up?
* Once your OIDC/SAML cluster is happily running, but SAML endpoint goes down (for reasons that have nothing to do with Teleport) you do not want to end up locked out of SSH. 

## Proposal

The local auth should always be available. This way you can:

1. Login via local admin and use the UI to configure SAML/OIDC.
2. If a SAML/OIDC provider goes down (or changes its configuration, say the hostname), you can use a local user to login into the cluster and use the configuration UI to fix it.

## CLI Implementation

`tsh login` should support `--auth` flag. Possible values:

* `local`: forces uses local authentication. [we need this for 2.3] 
* `foobar`: uses connector `foobar`. [this can be skipped for 2.3] for scenarios when multiple SAML/OIDC connectors are present. Listing it here to keep in mind how `--auth` flag will be used.

## Web UI implementation

The web UI login should always have the local auth available (used to be like this). We actually used to have it like this.

* Username + password
* If 2nd factor is enabled, should be visible as well
* `Login with foobar` button for `foobar` SAML/OIDC provider. (if enabled)

**Comment by kontsevoy** [comment]
@russjones this is done, no?

**Comment by russjones** [comment]
@kontsevoy Yes it is.
