### ISSUE TITLE
Unable to decrypt SAML assertion

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#10909]
### Description

**What happened**:
As part of the RA findings, one of the Digital Identity Guidelines (FedRAMP Federal Mandate) is to use both signed and encrypted bearer (SAML) assertions for SSO to Okta-managed resources/applications.
It was noted that the Teleport <-> Okta SAML wasn't in compliance.

~~~
failed to retrieve SAML assertion info from response: error validating response: unable to decrypt encrypted assertion: unknown symmetric encryption method "http://www.w3.org/2009/xmlenc11#aes256-gcm"
~~~

However, it does seem from the https://github.com/golang/go/blob/dev.boringcrypto/README.boringcrypto.md repo that AES 256 GCM is approved (see section 9.1, second row): https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3678.pdf 

Teleport is running in FIPS mode.

**What you expected to happen**:
SAML assertation will not fail due to AES 256 GCM encryption method, even with FIPS.

Any indication of if this is truly not a supported algorithm or if there is some other error here is appreciated

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Configure Teleport to use FIPS
2. Configure SSO with Okta using the specified encryption method

**Comment by probakowski** [comment]
I think this is not really connected to FIPS, it's just [gosaml2](https://github.com/russellhaering/gosaml2/) doesn't support AES-256-GCM ([encrypted_assertion.go#L53](https://github.com/russellhaering/gosaml2/blob/main/types/encrypted_assertion.go#L53)). 
I've opened https://github.com/russellhaering/gosaml2/pull/91 that should fix that problem (we would need to upgrade gosaml2 when this fix is released)

**Comment by russjones** [comment]
@probakowski Can we fork gosaml2 and use our own while we wait for upstream to merge these changes?

**Comment by probakowski** [comment]
@russjones we can, I'll do it today
