### ISSUE TITLE
Headless SSO by using the teleport proxy (or auth) server as the redirect_uri

### ISSUE THREAD

**Issue by rosskusler** [gravitational/teleport#10923]
### What
We would like to run commands like 'tsh ssh', 'tsh kube login, and teleport based 'kubectl' from headless linux servers. This works fine with OSS teleport because authentication (tsh login) is all command line driven, but we're interested in switching to enterprise and using SSO.

### How
It looks like there are some solutions already being considered. One possibility may be running 'tsh login' on our workstations and using ssh-agent forwarding to share credentials from the workstation with headless servers. I think this is what #9127 is referring to (It mentions #7830 but I'm not 100% clear on the relationship). This would work, but agent-forwarding has some security downsides. My ideal state would be sshing into a headless server and running 'tsh login' from there. Currently this isn't possible because 'tsh login' (w/ SSO enabled), either wants to open a web browser (which doesnt exist on headless servers) or expects you to port forward from your workstation to the headless system.

I'd like to propose another option. Currently when you run 'tsh login' w/ SSO enabled, tsh starts a small web server bound to 127.0.0.1 which becomes the target of the redirect_uri. What if, instead, the Teleport proxy were made the target of the redirect_uri?  Both the tsh cli tool and the web browser can reach the proxy server. In such a workflow, 'tsh login' would start by generating a unique URL that the user could copy/paste into their workstation browser. This functionality already exists in tsh. The difference is that instead of tsh starting a small webserver, it would poll the teleport proxy until the authentication flow is completed. This could be done by periodically polling (once per second), a long poll, or maybe even a websocket. In any case, tsh would block until either someone breaks (ctrl-c) or the SSO login is complete. While tsh is waiting, the user pastes the generated URL into their workstation browser and logs in to the IDP. Then instead of the browser being redirected to localhost, it is redirected to the teleport proxy. The proxy would then see that the authentication attempt was successful and would have access to the JWT (or SAML, I guess). It would generate the necessary x.509 and ssh certificates (or maybe the auth server does it?) and hands them to the tsh client, which was waiting/polling for them. I might have some of the terminology wrong.. maybe the redirect_uri should be the auth server instead of the proxy. Anyway the idea is that the browser could redirect to a teleport component instead of the tsh cli, because the browser and tsh cli would always have access to the proxy without needing port forwarding.
 

### Workaround
Port forwarding from the workstation to the headless system is possible but it's not optimal. It requires the end user to remember a lot (set up port forwarding on the command line, setting the bind-addr during login, etc). It also doesn't scale well when you have multiple headless servers that you want to do this from (each server could need a different port number to be forwarded).

**Comment by Joerger** [comment]
Headless SSO is now available for `tsh ls`, `tsh ssh`, `tsh scp` - https://github.com/gravitational/teleport/issues/21519

Bringing Headless SSO to additional features will be tracked in https://github.com/gravitational/teleport/issues/21520

We also have a specific ticket for adding Headless SSO for kubernetes access here - https://github.com/gravitational/teleport/issues/24293
