### ISSUE TITLE
open /var/lib/teleport/bot/tlscert: is a directory

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#10938]
### Description

**What happened**:
By default if you don't set `--destination-dir`, tbot will try to write to `/var/lib/teleport/bot/tlscert` but if fails. 
```
root@ip-10-0-0-66:~# tbot start --config=/etc/tbot.yaml    --token=xxx      --auth-server=teleport-9a.asteroid.earth:443INFO [TBOT]      Attempting to generate new identity from token tbot/main.go:192
INFO [AUTH]      Attempting registration via proxy server. auth/register.go:165
INFO [AUTH]      Successfully registered via proxy server. auth/register.go:172
INFO [TBOT]      Successfully generated new bot identity, valid: after=2022-03-08 05:34:50 +0000 UTC, before=2022-03-08 06:35:50 +0000 UTC, duration=1h1m0s | properties: renewable=true, disallow-reissue=false, roles=[bot-terminatora], principals=[], generation=1 tbot/main.go:229
ERROR: could not write to tlscert
unable to save generated identity back to destination
open /var/lib/teleport/bot/tlscert: is a directory
```

I was able to fix this by adding `--destination-dir` to my config.
```
tbot start --config=/etc/tbot.yaml      --data-dir=/var/lib/teleport      --destination-dir=/opt/machine-id      --token=9fc5143c902e2a3a7a9f0977ae928af0      --auth-server=teleport-9a.asteroid.earth:443
```

**What you expected to happen**:
Better error message, and or write to /bots/tlscerts if nothing is set.

**Comment by timothyb89** [comment]
I _think_ this should be significantly improved already with https://github.com/gravitational/teleport/pull/10289 but you may have hit a harder error than we now handle. What's the output of:

```
ls -lah /var/lib/teleport/bot
```

If the `tlscert` entry in there is a directory it will never succeed. It does now automatically create files and directories as long as it has the permissions needed to do so, so depending how that `tlscert` became a directory there may be a bug in that logic.

**Comment by strideynet** [comment]
I'm going to go ahead and close out this ticket. It feels like the introduction of `tbot init` has tidied up a lot of the story around guiding the user to creating the correct directory/permissions structure. Having just tried running `tbot` without a `--destination-dir` with a few permutations, I'm unable to reproduce this.

Feel free to re-open this with some more details/reproduction steps if this looks like something else is going wrong here.
