### ISSUE TITLE
Failed to handle client connection: acme can't get a cert for domain 74656c65706f72742e616e616368726f6e69732e646576.teleport.cluster.local

### ISSUE THREAD

**Issue by TheAnachronism** [gravitational/teleport#10951]
### Description

**What happened**:
Recently tore down my bare-metal k8s-cluster because I wanted to start with a clean environment. In that old version, I had teleport running, and had multiple servers for ssh access connected. Now that I have setup my new cluster with all the required services, teleport tells me, that it can't get certificates, which as I understand it are needed for connecting further nodes.

**What you expected to happen**:
As in the previous environment, the nodes are added to the teleport-cluster.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.Install teleport with helm
2.Try add new teleport node.
3.

### Server Details
- Teleport version (run `teleport version`): `Teleport v8.3.1 git:v8.3.1-0-g64812df6e go1.17.3`
- Server OS (e.g. from `/etc/os-release`): k8s
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): 
  bare-metal k8s-cluster, created with kubeadm and running in proxmox VMs over 2 physical servers.
- Additional details:

I've found this issue and solution here: https://github.com/gravitational/teleport/issues/7938#issuecomment-901465923
But I've already waited more than a week, which is apparently the time-out duration for let's encrypt. So, either I'm still rate-limited or something else is not working as intended.

**Comment by TheAnachronism** [comment]
The error messages I get from `kubectl logs -n teleport-cluster teleport-cluster-XXX -f` are just a bunch of these:
`
2022-03-08T13:56:34Z WARN [ALPN:PROX] Failed to handle client connection: acme can't get a cert for domain 74656c65706f72742e616e616368726f6e69732e646576.teleport.cluster.local, add it to the proxy_service.public_addr, or use one of the domains: teleport.XX.XX alpnproxy/proxy.go:274
`

the XXs are, of course, replaced with my actual domain

**Comment by wiredmind** [comment]
I ran into the same problem with a completely new install: Teleport v9.0.0 git:v9.0.0-0-g1fa8857aa go1.17.7

**Comment by TheAnachronism** [comment]
I recently tore down the entire setup with teleport and then reinstalled it and even used a different email for the acme setting (one that I've never used for Let's Encrypt) and I still get those error messages.
So, either I got IP-Banned or something from Let's Encrypt or something is going wrong while attempting to get those certificates.

**Comment by truonghdpk** [comment]
Same isssue

**Comment by TheAnachronism** [comment]
OK, so now I updated to the latest version `9.0.3` with helm and used this new script which is provided by the cluster pod itself. I have no idea why, but now the connections work and all my nodes can join the cluster again.
If at some point anyone has an idea what the problem was, please tell me, so I have an idea how I could fix this if it happens again -.-
