### ISSUE TITLE
Quickly switch between clusters

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#10956]
### What

```bash
# Currently, tsh login <cluster> switches between root/leaf clusters
$ tsh login root
$ tsh login leaf

# there is no way to switch between different profiles without re-login
# this below adds a quick alias

# the home symbol tells to switch cluster profile:
$ tsh login ~cluster-a

# switch into cluster b profile and choose leaf
$ tsh login ~cluster-b/leaf
```

gz#4631

gz#5709

**Comment by rephadmin** [comment]
perhaps there should be a way to have profile names and/or aliases be specified.
I would propose something like   tsh login -p <profile_alias>    and then it just switches to the other profile

**Comment by eedgar** [comment]
> one question is whether this should recognize that you're still in a current session instead of making another login
> 
> `tsh login --proxy=teleport.example.com`
> 
> Currently it ignores if you already have a session and always attempts a login to get a new cert.

I would prefer a flag to skip the login in case the cert is just minutes away from expiring and you did want to re-auth.

perhaps tsh login -s --proxy=teleport.example.com   to turn on the skip feature?

**Comment by klizhentas** [comment]
What if instead of `~` we use something like `@`. One inspiration is `ssh root@location` - using aliases for frequently used commands.

**Comment by sover02** [comment]
This would be valuable for us as well.  Our org has several independent clusters that our engineers need to authenticate against.

**Comment by rocking-e** [comment]
This ability to switch profiles without a re-login would be a bit help for our org. We have several independent clusters that users will have to access regularly. 

I like the idea where `tsh login` will switch profiles and if the session is still active, not do a re-login. To address the issue of a session close to expiration, add a `--force` flag that says to the re-login even if the session has not expired.

If you go with the `tsh switch` option, why can't it do a login if it sees the session for that profile has expired?

**Comment by r0mant** [comment]
I've been thinking about this a bit and I wonder if the following UX would be straightforward.

1. Not technically related to this ticket but first we can add `tsh clusters -R` flag that will display all clusters across all profiles, similar to what we've just done for `tsh ls -R` commands:

```
$ tsh clusters -R
Proxy   Cluster Name Status Cluster Type Labels   Selected
------  ------------ ------ ------------ -------- --------
proxyA  root         online root                  *
proxyA  leaf         online leaf         env=prod
proxyB  root         online root                  
proxyB  leaf2        online leaf         env=prod
```

2. Then, to switch between clusters users can just use regular `tsh login <cluster-name>` that will switch to this cluster if its name is unambiguous between the profiles, or require prefixing the cluster name with the proxy name `<proxy>/<cluster>` if there's ambiguity:

```
$ tsh login leaf 
Logged into cluster "leaf" on proxyA

$ tsh login leaf2
Logged into cluster "leaf2" on proxyB

$ tsh login root
Error: cluster "root" is present on proxyA, proxyB, please select the profile explicitly e.g. proxyA/root

$ tsh login proxyA/root
Logged into cluster "root" on proxyA
```

No special symbols are needed. @klizhentas @xinding33 Lmk what you think.

**Comment by r0mant** [comment]
Update on this after discussing with @klizhentas. The above approach wouldn't work well because if one of the profiles is expired, tsh won't be able to know its cluster names without re-login.

So, given that the main issue is inability to change the profile without re-login, we have decided to make a couple of tweaks to the existing `tsh login` behavior instead of introducing additional behaviors/commands:

- Make sure that `tsh login --proxy` command does not make user re-login if the profile is still valid (not expired).
  - It will re-login the user if it's expired.
- Make sure that `tsh logout --proxy` works for logging out of a single profile.

cc @alistanis

**Comment by wetnun** [comment]
can it not just skip the expired profiles? or do a warn to stderr saying it skipped an expired profile?

Ideally I like the concept that all of your sessions are transparently merged into a single view. only issue I could foresee is if you have multiple environments joined where nodes have the same name (one dev, one staging, one prod all deployed by automation for example), so you'd have to ensure you used labels or do proper naming in case you happen to be authenticated to all environments at once.

A wrapper I've given users to switch between our environments currently is this:
```
$ cat ~/bin/ptsh
#!/usr/bin/env bash

current=$(cat ~/.tsh/current-profile)
echo "Select an environment:"
select tenv in $(ls ~/.tsh/*.yaml | grep -oE '([^/]+).yaml$' | rev | cut -d. -f2- | rev); do
  echo "Switching to: $tenv"
  echo $tenv > ~/.tsh/current-profile
  break
done
```

The ability to do better filtering from the cli without having to pipe to grep would also be great, I can't find the issue I remember off hand to link at the moment.
