### ISSUE TITLE
Determine a standard name for Teleport services that aren't the Auth/Proxy

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#10976]
## Details
We can divide Teleport's services into those that (a) expose specific resources for access and run on the same network as those resources (the Database Service, Node Service, Kubernetes Service, Application Service, and Desktop Access) and (b) those that centrally coordinate/manage access to the services in (a) (the Auth and Proxy). We should come up with a standard term we can use in our documentation for the services in (a). 

One reason this would be helpful is that is services in (b) currently run on Teleport Cloud while services in (a) do not.

Some possibilities:
- We use the term "sidecar" in our blog (e.g., announcements for [Application Access](https://goteleport.com/blog/application-access-announcement/) and [Database Access](https://goteleport.com/blog/introducing-database-access/)) but not in our docs. 
- We use the term "agent" a lot in the docs, e.g., when talking about a "database agent."

Our [architecture overview](https://goteleport.com/docs/architecture/overview/) only recognizes the Node service, so it would be good to incorporate this general term when we expand it to talk about our additional services.

### Category
- Improve Existing

**Comment by zmb3** [comment]
Suggestion: refer to the auth/proxy as the Teleport Control Plane.

**Comment by webvictim** [comment]
I think `agent` is very widely known, SE uses it constantly in demos/diagrams etc. It's probably the easiest mental model to expand upon.

**Comment by ptgott** [comment]
I like the idea of using "Teleport Control Plane" and "Teleport agents". I think the next steps can be to:

- Update our docs [style guide](https://github.com/gravitational/teleport/blob/c239344649797d4b2ab9a1a0197c60934df9ae89/docs/pages/contributing/documentation/style-guide.mdx) with a section on product names that spells this out
- Make a list of some pages we should change to introduce this naming convention, starting with [Adding Nodes](https://github.com/gravitational/teleport/blob/c239344649797d4b2ab9a1a0197c60934df9ae89/docs/pages/setup/admin/adding-nodes.mdx) and pages in the Architecture section, then start editing these pages in the background
- We can also do a general find/replace for "Node" where it can be mistaken for a placeholder for "any non-Auth/Proxy service" and use "agent" instead

Should we capitalize "agent"?

**Comment by ulysseskan** [comment]
> Suggestion: refer to the auth/proxy as the Teleport Control Plane.

While control plane is correct, auth/proxy is more descriptive.  I think wherever we can be more clear, we should be.  Control plane seems like a slight obfuscation.

...

Agent does sound good instead of node.

**Comment by pschisa** [comment]
From a perspective of deploying teleport, it is important to have a way to reference the auth service separate from the proxy service as the components themselves are often separated.  So even if combined they are called the `Teleport Control Plane` I would like to see some standard terminology for referencing the individual components when talking about configurations and troubleshooting of the auth and proxy services respectively

**Comment by ptgott** [comment]
To better scope this issue, I'll look at all instances of `teleport node` in the docs (regardless of case) and see if we need to edit each one to talk about resource services instead.

As of today, at the root of `gravitational/teleport`, there are 119 instances, which is pretty manageable for a manual find/replace.

```
$ find ./docs/pages -name "*.mdx" -exec grep -i "teleport node" {} \; | wc -l
     119
```
