### ISSUE TITLE
Where is debian package source files?

### ISSUE THREAD

**Issue by lsaavedr** [gravitational/teleport#10971]
## Details
We need see debian package source files to check if the package upgrade restart teleport service,

regards,
Luis

### Category

- Improve Existing

**Comment by webvictim** [comment]
The .deb package is built by this script here: https://github.com/gravitational/teleport/blob/master/build.assets/build-package.sh#L329-L348

To answer your question, Teleport .deb packages do not automatically restart the Teleport service when being upgraded. This is to prevent issues with connectivity when running package upgrade commands over Teleport itself.
