### ISSUE TITLE
MachineID should be able to generate a host file.

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#11000]
### What
As part our Ansible Guide https://github.com/gravitational/teleport/pull/10987, we recommend generating a hosts file using `$ tsh ls --format=json | jq -r '.[].spec.hostname + ".example.com"' > hosts`. This works well, but still requires extra work to export this list to host. It would be nice if `tbot` could query Teleport and be used for an integrated way to export a list of hosts. 

### Why
Reduce need for extra programs and automation. 

### Workaround
Use `tsh` and or create a robot with an impersonation role to generate the file.

**Comment by benarent** [comment]
Ok.. I tried this again today and wasn't able to replicate it. Maybe something was fixed between the beta and 9.0.1. I'm going to close this issue. cc @timothyb89

**Comment by timothyb89** [comment]
Hmm, are you sure this is fixed? I don't think we've changed anything that would make hosts file generation easier.
