### ISSUE TITLE
Machine ID: Add ephemeral token joining

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#11017]
### What
Machine ID currently supports ephemeral clients with IAM joining. We should also support this with token-based joining.

### How
We can mostly emulate how IAM joining works today: disable the renewable flag and generation counter.

IAM joining allows for renewals without a renewable cert because we can continually prove the node identity. We can't do that with secret tokens, so ephemeral nodes joined via token just won't get to renew.

### Open questions
Secret tokens aren't really meant to live for a long time. How can we make this more secure? What can we do to make rotating tokens easy?

**Comment by mvgijssel** [comment]
Would this be a (generic) addition to the already present join methods CircleCI, GitHub and GitLab? I'm curious because I really want to use Machine ID inside BuildBuddy CI.

**Comment by strideynet** [comment]
Replaced by https://github.com/gravitational/teleport/issues/26885
