### ISSUE TITLE
Support exporting Teleport Desktop Access User CA with Machine ID 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#11070]
### What
As part of Teleport Desktop Access, we require users to export Teleport CA using `tctl auth export --type=windows > user-ca.cer` , we then expect the user to get this CA onto the Windows Domain controllers. I've been using a S3 bucket, but it's a few extra steps and also requires extra work during a rotation. 

It would be good if tbot could obtain this CA. 

### How
To be decided by dev team. 

### Why
Make onboarding and also automation easier. 

### Workaround
Exporting the CA and running it with a playbook. https://github.com/robpomeroy/teleport-ansible/tree/main/Windows-domain#certificates

**Comment by zmb3** [comment]
I don't think this necessarily _needs_ to be part of Machine ID.

Machine ID is about generating short lived credentials. This is about exporting the CA, which lives much longer than the certs it issues.

We could use the short-lived machine ID credentials to authenticate to the cluster and export the CA, but we're also looking at other options that would render this unnecessary (see #10132, for example).

**Comment by zmb3** [comment]
This is doable with https://github.com/gravitational/teleport/pull/15491
