### ISSUE TITLE
Update resources reference /docs/pages/setup/reference/resources.mdx

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#11079]
## Details

Update the resources reference page at: https://goteleport.com/docs/setup/reference/resources/

- Ensure `user` and `role` resources are accurate and up to date
- Add missing resources (trusted clusters, auth connectors, etc)

### Category

- Improve Existing

**Comment by ptgott** [comment]
Closing so we can track this here: https://github.com/gravitational/teleport/issues/16948
