### ISSUE TITLE
Ensure deb package restarts auth on upgrade

### ISSUE THREAD

**Issue by sashker** [gravitational/teleport#11104]
### Description

After upgrading to Teleport 9.0.0, I get an error when connecting to a node:

```
unknown method CreateSessionTracker for service proto.AuthService
ERROR: ssh: could not start shell
```

The same error I can see in the log of the problematic node (it's just one node that has this problem)

After manually restarting the auth service, the error goes away. This suggests that upgrading via the deb package is not restarting the Teleport service.

### Server Details
- Teleport v9.0.0 git:v9.0.0-0-g1fa8857aa go1.17.7 (installed via .deb package)
- Debian 10 Buster x86_64
- AWS EC2

### Client Details
- Teleport v9.0.0 git:v9.0.0-0-g1fa8857aa go1.17.7
- OSX
- Installed via brew

### Debug Logs
DEBU [CLIENT]    Client  is connecting to auth server on cluster "CLUSTER_NAME". client/client.go:896
DEBU [CLIENT]    No Key Agent selected. client/session.go:269
unknown method CreateSessionTracker for service proto.AuthService

ERROR REPORT:
Original Error: *errors.errorString ssh: could not start shell
Stack Trace:
	/private/tmp/teleport-20220311-24015-1b5c2od/teleport-9.0.0/lib/client/session.go:488 github.com/gravitational/teleport/lib/client.(*NodeSession).runShell.func1
	/private/tmp/teleport-20220311-24015-1b5c2od/teleport-9.0.0/lib/client/session.go:296 github.com/gravitational/teleport/lib/client.(*NodeSession).interactiveSession
	/private/tmp/teleport-20220311-24015-1b5c2od/teleport-9.0.0/lib/client/session.go:481 github.com/gravitational/teleport/lib/client.(*NodeSession).runShell
	/private/tmp/teleport-20220311-24015-1b5c2od/teleport-9.0.0/lib/client/api.go:2085 github.com/gravitational/teleport/lib/client.(*TeleportClient).runShell
	/private/tmp/teleport-20220311-24015-1b5c2od/teleport-9.0.0/lib/client/api.go:1473 github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH
	/private/tmp/teleport-20220311-24015-1b5c2od/teleport-9.0.0/tool/tsh/tsh.go:1684 main.onSSH.func1
	/private/tmp/teleport-20220311-24015-1b5c2od/teleport-9.0.0/lib/client/api.go:525 github.com/gravitational/teleport/lib/client.RetryWithRelogin
	/private/tmp/teleport-20220311-24015-1b5c2od/teleport-9.0.0/tool/tsh/tsh.go:1683 main.onSSH
	/private/tmp/teleport-20220311-24015-1b5c2od/teleport-9.0.0/tool/tsh/tsh.go:653 main.Run
	/private/tmp/teleport-20220311-24015-1b5c2od/teleport-9.0.0/tool/tsh/tsh.go:313 main.main
	/opt/homebrew/Cellar/go/1.17.8/libexec/src/runtime/proc.go:255 runtime.main
	/opt/homebrew/Cellar/go/1.17.8/libexec/src/runtime/asm_arm64.s:1133 runtime.goexit
User Message: ssh: could not start shell

**Comment by zmb3** [comment]
`CreateSessionTracker` was added to the auth server in Teleport 9. Is it possible your auth server is outdated?

**Comment by sashker** [comment]
I double checked it:
Node: Teleport v9.0.0 git:v9.0.0-0-g1fa8857aa go1.17.7
Server: Teleport v9.0.0 git:v9.0.0-0-g1fa8857aa go1.17.7
Node I'm connecting from: Teleport v9.0.0 git: go1.17.8

When I restarted the Server I managed to connect successfully, so it seems like some problem of an automatic update via apt.

So, the daemon running was probably older than the version installed. But this is not visible whatsoever.

**Comment by sashker** [comment]
@zmb3 That is correct

**Comment by zmb3** [comment]
Thanks @sashker - I've updated the title/description of this to make sure we look into the deb package upgrade process.

**Comment by webvictim** [comment]
The RPM package doesn't automatically restart the Teleport daemon when upgraded either. This was actually a deliberate decision to avoid dropping a connected Teleport session in the middle of a `dnf upgrade`/`apt upgrade` and causing corruption. My understanding is that `systemctl reload` isn't guaranteed to work when the underlying Teleport version has changed either, because the re-exec code may fail due to the binary being changed out.

If there's some other way to make this reliable then I agree we should do it, but it needs to be a well-tested fix rather than a knee-jerk reaction.

**Comment by zmb3** [comment]
Tracking this at #10154
