### ISSUE TITLE
Allow Use of Self-deployed TLS Key/Cert in Teleport Cluster Chart

### ISSUE THREAD

**Issue by mattmelgard** [gravitational/teleport#11103]
### What

This [discussion post](https://github.com/gravitational/teleport/discussions/11101) describes the context for this, but to summarize - it would be nice to be able to specify a Kubernetes secret to be used for the Teleport [key and cert file](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/templates/config.yaml#L102) so that cert-manager does not need to be installed as a dependency, and, as is needed in our case, to enable use of something like a [Cloudflare Origin Certificate](https://blog.cloudflare.com/cloudflare-ca-encryption-origin/) when terminating TLS in Teleport.

### How

I would say the chart should allow for more flexibility around how the certificates are supplied. The easiest way I can think to do this would be to add a value that lets you specify a Kubernetes Secret name containing the TLS cert and key. The other option here might be to enable overriding of the `https_keypairs` configuration block, which could then be pointed at a certificate mounted via the `extraVolumes`/`extraVolumeMounts` chart values.

### Why

Mentioned most of it in the first section, but this would enable use of an existing k8s secret to be used for TLS.

### Workaround
None that I'm aware of.

### Additional Info

I'm still rather new to Teleport, but the [docs](https://goteleport.com/docs/kubernetes-access/helm/guides/gcp/) don't seem to mention any other reasons why cert-manager/Let's Encrypt are requirements for the cluster other than for generating the initial cert/key PEM files. If I'm missing something here, please let me know, but this would definitely ease adoption for us if we didn't have to add the overhead of managing a cert-manager deployment in addition to the cluster and if we were able to use Cloudflare's proxied DNS features (DOS protection, WAF rules etc...) which are only possible through the use of an origin certificate.

Also, I'm happy to PR the changes myself, just wanted to get some feedback on what the preference would be for exposing this kind of option before I went ahead with that.

**Comment by webvictim** [comment]
@mattmelgard Here's a draft PR which implements this: https://github.com/gravitational/teleport/pull/11295

If you have a chance to test it, I'd be curious to know if it works for you.

**Comment by mattmelgard** [comment]
> @mattmelgard Here's a draft PR which implements this: #11295
> 
> If you have a chance to test it, I'd be curious to know if it works for you.

Sure thing, sorry for the late reply. Should be able to test this out this evening.
