### ISSUE TITLE
Disable Session Recording

### ISSUE THREAD

**Issue by patrobinson** [gravitational/teleport#1111]
Session Recording looks nice but there are a couple problems:
- Users can view anybody else's session https://github.com/gravitational/teleport/issues/924
- Users can unwittingly expose sensitive information through session recordings
- Sharing a session means any user can impersonate a user https://github.com/gravitational/teleport/issues/999

I think it would be easier if we could completely disable this feature until we are comfortable it can be secured.

**Comment by kontsevoy** [comment]
@patrobinson 120% in agreement. This work is already under way as part of #1085 and #1092. This is by far number one user request right now. I hope you don't mind if I close this one as a duplicate, but feel free to add more comments & thoughts, we're reading all of this. Thanks!
