### ISSUE TITLE
Best Practices

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1112]
Several commercial customers have asked us for best practices for setting up Teleport. It would be useful to document various common scenarios and what we recommend. This might not be appropriate for a completely new guide maybe it should just be sprinkled into existing documentation, I'm not quite sure yet.

A few examples:

- [ ] When to use different clusters to restrict access. How they do they work and what are their limitations.
- [ ] When to use labels to restrict access. How do they work and what are their limitations.
- [ ] When to use namespaces to restrict access. How do they work and what are their limitations. (Teleport 2.4).
- [ ] When to use principles to restrict access. How do they work and what are their limitations.
- [ ] How to restrict access to session recording (Teleport 2.3).
- [ ] Creating roles and role based access control.

**Comment by benarent** [comment]
We've currently added this to a range of docs in the admin guide etc. Since it's a several years old, I'm going to close this. It has made think we could have a 'how to lock down' Teleport guide.
