### ISSUE TITLE
Add Web UI for creating Session Locks

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#11147]
### What
Currently, session locks are only able to be created via the CLI with `tctl`.  Request is to be able to create new locks via the Web UI.

This would be an extension beyond just listing/deleting locks in the Web UI as tracked here: https://github.com/gravitational/teleport/issues/8543

### Why
Enables users more comfortable with Web UI workflows to use session locks without requiring the CLI tooling.

### Workaround
Use `tctl`

gz#5936

**Comment by hatched** [comment]
Completed by https://github.com/gravitational/teleport/pull/22437
