### ISSUE TITLE
Teleport v9.0.0 git:v9.0.0-0-g1fa8857 go1.17.7 not working after upgrade on Oracle Linux 

### ISSUE THREAD

**Issue by layer3lv** [gravitational/teleport#11142]
OS:
Operating System: Oracle Linux Server 8.5
CPE OS Name: cpe:/o:oracle:linux:8:5:server
Kernel: Linux 5.4.17-2136.304.4.5.el8uek.x86_64

Teleport Version:
Teleport v9.0.0 git:v9.0.0-0-g1fa8857 go1.17.7

Errors:
SSH 
ERRO unknown method CreateSessionTracker for service proto.AuthService regular/sshserver.go:1774

Web pannel: 
disconnected 
ssh: could not start shell

**Comment by zmb3** [comment]
`CreateSessionTracker` was added in 9.0.0. Please confirm that your auth server is updated.

We have seen issues where the auth server doesn't restart when using the deb packages to upgrade, so I would try manually restarting it too.

**Comment by layer3lv** [comment]
@zmb3 thx for the tip all works fine!
