### ISSUE TITLE
TTL: never does not work for cache policy

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1116]
Version: 2.2.3

When using `never` get this error:
```bash
cache.ttl invalid duration: never, accepted format '10h'
```

**Comment by kontsevoy** [comment]
what's `cache.ttl` and "cache policy"? if this is something Telekube needs, it shouldn't be exposed to regular users.

**Comment by klizhentas** [comment]
@kontsevoy it's all documented here:

https://github.com/gravitational/teleport/pull/853#issue-215907945

**Comment by kontsevoy** [comment]
nevermind then

**Comment by kontsevoy** [comment]
@klizhentas @russjones is this something trivial? seems so, adding to the cleanup milestone we're in the middle of.

**Comment by russjones** [comment]
Tried to reproduce and couldn't, turns out it was fixed in https://github.com/gravitational/teleport/pull/1117.
