### ISSUE TITLE
imagePullPolicy is not reflected in teleport-kube-agent chart

### ISSUE THREAD

**Issue by gclawes** [gravitational/teleport#11183]
### Description

**What happened**:
The `.Values.imagePullPolicy` value for `teleport-kube-agent` is not reflected in the `StatefulSet` or `Deployment` templates, despite being in `values.yaml`:

https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/values.yaml#L192

**What you expected to happen**:
Setting `.Values.imagePullPolicy` should be reflected in the templates

### Server Details
- Teleport version (run `teleport version`): 9.0.0
- Server OS (e.g. from `/etc/os-release`): N/A
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Kubernetes
- Additional details: N/A

### Client Details
- Tsh version (`tsh version`): N/A
- Computer OS (e.g. Linux, macOS, Windows): N/A
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): N/A
- Additional details: N/A

**Comment by webvictim** [comment]
That's spooky, I noticed this around the exact same time (while adding unit tests) and fixed it. I didn't even see this issue!

https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/templates/deployment.yaml#L108-L110

https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/templates/statefulset.yaml#L104-L106

I'll get this fix backported to `branch/v9` so it'll be reflected in the next Helm chart release to the repo.

**Comment by webvictim** [comment]
This has been fixed on `master` and backported to `branch/v9`. It will be fixed in the Helm charts in the repo when Teleport 9.0.2 is published.
