### ISSUE TITLE
Add support for `:` to label keys

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#11196]
If you set labels for a resource like the following, Teleport refuses to start.

```
   labels:
     foo:bar: baz
```

```
ERROR REPORT:
Original Error: *trace.BadParameterError invalid label key: &#34;foo:bar&#34;
```

**Comment by r0mant** [comment]
@yjperez @stevenGravy @pschisa Guys, we've fixed this in master and planning to backport to v9 and v8. Is that ok or does anyone still using v7 need this too?

**Comment by pschisa** [comment]
Not that I am aware of
