### ISSUE TITLE
Add label filtering to `tsh db ls`

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#11194]
### What
Currently `tsh db ls` is not able to filter output databases by label like `tsh ls <key>=<value>` can:

~~~
tsh db ls region=west1
ERROR: unexpected region=west1
~~~

### Why
Allow end users who interact with large DB clusters to filter the node search based on assigned labels

**Comment by russjones** [comment]
@kimlisa This should now work, can you confirm?

**Comment by kimlisa** [comment]
@russjones yes with https://github.com/gravitational/teleport/pull/11016
