### ISSUE TITLE
Ctrl+c freezes session in WebUI

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#11193]
### Description

**What happened**:
Using `Ctrl+c` in WebUI sessions freezes the session completely starting with 9.0

**What you expected to happen**:
`Ctrl+c` should behave as expected and abort the previously run command.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Open WebUI ssh session
2. Run command such as `journalctl -fu teleport`
3. Run `ctrl+c` to try and abort
4. Observe session freeze and prevent and further interactivity

### Server Details
- Teleport version (run `teleport version`): 9.0

**Comment by alexmv** [comment]
_This_ issue is #11193.  For anyone else looking, the main ctrl-C issue is #11092.
