### ISSUE TITLE
Optimize magic link to automatically remove any old teleport data/configs and act as a clean re-install link

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#11199]
### What
Currently our magic link attempts to install teleport on a remote node and have it join the existing cluster, but if a previously installed teleport version and config exist, it errors out and suggest manual steps for the customer to remove the old files/directories before re-running the script. Customers have requested that our magic link be optimized to automatically remove any old teleport data/configs and act as a clean re-install link every time it's run.

**Comment by webvictim** [comment]
It wasn't ever our intention that this script be the only way to install Teleport on machines - it was just a simple "hey here's an quick script to run so you can add your first instance" thing. Making the script automatically destructive will cause more harm than good. Newer agent installations performed via the script will be automatically enrolled into automatic upgrades when the cluster has them enabled.
