### ISSUE TITLE
Unclear documentation around `in-memory` caching enablement

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#11195]
## Details
Docs here https://goteleport.com/docs/setup/reference/config/ indicate that `enabled: true` is a required part of the configuration for in-memory caching but docs here https://goteleport.com/docs/setup/operations/scaling/#proxy-configuration dont show this value at all.

The documentation should be clear on which options are required to enable in-memory caching.

I am trying to confirm which version is correct and will update the issue once determined

### Category
- Improve Existing

**Comment by pschisa** [comment]
Confirmed with team that `enabled` is the default option meaning it is not required.

I would recommend updating https://goteleport.com/docs/setup/reference/config/ in the below section to clearly indicate that is the default value and not required for enabling the feature:

~~~
    # For use on a Teleport Proxy.
    # See the "Teleport Scalability Tweaks" of the admin manual
    # (https://goteleport.com/docs/admin-guide/#teleport-scalability-tweaks)
    # cache:
    #  # use an in-memory cache to speed up the connection of many teleport nodes
    #  # back to proxy
    #  type: in-memory
    #  enabled: true
~~~

**Comment by espadolini** [comment]
The cache (as of 8.3.7 and the releases after 9.0.3 and 7.3.18) is always `in-memory`, and the default of `enabled: true` still stands, so the update ought to just remove that section altogether.

**Comment by ptgott** [comment]
Closing since the `type` field is no longer in the config reference.
