### ISSUE TITLE
Allow a way for `tsh` to be able to fetch a list of session recordings available for play

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#11205]
### What
Feature request is to allow the `tsh` tool to list session recordings available for playback to an end user.

### How
Something like `tsh sessions ls` to list out all session recording ids compatible with `tsh play` over a specified timeframe or most recent entries.

- [ ] By default `tsh sessions ls` should output table with all sessions containing columns: session ID, session type (can we?), session timestamp, participants, server information.
- [ ] The command should support `--format` flag to print sessions in JSON/YAML formats.
- [ ] Command should use pagination for events API.
- [ ] Command should allow to fetch sessions of particular type e.g. SSH vs Kubernetes:
  * `tsh sessions ls --type=[ssh|k8s]`.
- [ ] Command should allow to fetch sessions for particular time interval: 
  * `tsh sessions ls --from-utc=xxx --to-utc=xxx`
- [ ] Confirm that after listing sessions with `tsh sessions ls` you should be able to use `tsh play` to play the sesion.

### Implementation

Use events API to fetch `session.end` events. Use pagination.

### Why
This would be a big quality of life for users to not have to grab the session id from the Web UI before reviewing a session recording.

### Workaround
Get the session id from the web UI or audit logging

**Comment by russjones** [comment]
Add support for `tctl` at the same time.
