### ISSUE TITLE
tsh play shows a confusing error for desktop sessions

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#11207]
When running `tsh play <session>` with a session ID that corresponds to a desktop session, you get a strange error.

This is because `tsh play` downloads the session and then attempts to convert it to the legacy SSH (chunks/events) formats prior to streaming, and desktop sessions can not be converted in this manner.

Potential improvements:
- Just spit out an error "desktop sessions cannot be viewed with tsh"
- Attempt to open the user's browser to the URL of the session player, which will play the session.

**Comment by klizhentas** [comment]
Let's go with a simpler option:

Let's go with an error:

"Desktop sessions cannot be viewed with tsh. Please use the browser to play the sessions. Click on the URL to view the session in the browser".

**Comment by mcbattirola** [comment]
Fixed in https://github.com/gravitational/teleport/pull/14879
