### ISSUE TITLE
Add support for Elasticache/MemoryDB

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#11227]
### What

Redis database access should be able to connect to Elasticache/MemoryDB and automatically sign user in.

### How

Elasticache only supports username/password auth. Integrate with AWS Secrets Manager for rotating credentials.

**Comment by greedy52** [comment]
Here are some preliminary research.

## Secret Manager

- [auto rotation](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_schedule.html) minimum period is 24 hours
- Based on [quotas](https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_limits.html), a secret can have at most 100 version per day. That's about one new version per 15 minutes.

## Elasticache Redis

- [3 modes](https://aws.amazon.com/blogs/database/work-with-cluster-mode-on-amazon-elasticache-for-redis/)
  - single node: does not support TLS
  - replication group: primary, replica endpoint
  - cluster/shard mode: configuration endpoint
- Auth "state"
  - 4 states
    - No TLS
    - TLS without auth
    - TLS with auth token: single token, 2 tokens during rotation
    - TLS with ACL (users): each user can have 2 passwords. update takes 2 minutes. must use a group.
  - All states are mutually exclusive, meaning configuring one will break others.
- No public ip so can be only accessed within the same VPC.

## MemoryDB
- Redis 6.2
- TLS is not mandatory
- No Redis auth token. Only [ACL](https://docs.aws.amazon.com/memorydb/latest/devguide/clusters.acls.html)
