### ISSUE TITLE
Cannot stop "tsh agent" by Ctrl-C or SIGTERM

### ISSUE THREAD

**Issue by tatsushid** [gravitational/teleport#1123]
Hello,

I met an issue that I couldn't stop `tsh agent` command by Ctrl-C or SIGTERM signal after v2.2.0 release. To stop it, at least SIGQUIT has to be sent to the process.

Here is the instruction to reproduce the issue.

1. login to system by `tsh login`
2. build tsh by `make build/tsh`
3. run `./build/tsh agent` to test the built binary
4. type Ctrl-C and see if the process stops or not

According to `git bisect` result with the instruction above, it seems to have been introduced at commit 7d741b10. I think there is something race condition in signal handler goroutine in `tool/tsh/common/tsh.go` introduced by the commit.

I hope it will be fixed in future release and thanks for developing a great software!

**Comment by tatsushid** [comment]
I forgot to mention about my environment. I tested it on macOS El Capitan 10.11.6 with Go 1.8.3

**Comment by kontsevoy** [comment]
@tatsushid we are actually thinking about deprecating `tsh agent` because this very same functionality is available using macOS built-in agent (actually when you execute `tsh login` the certificate is automatically fed into MacOS built-in agent).

Thoughts?

**Comment by tatsushid** [comment]
Thanks for the response!

I confirmed that the public key is stored in macOS agent (by running SSH client command with `-v` option) and I can use Teleport proxy without running `tsh agent`. It is better if I don't have to run `tsh agent` to use SSH client (in most cases, for Ansible, Serverspec or something automation tools).

I agree with you on deprecating it on macOS.

**Comment by kontsevoy** [comment]
phew! awesome. Thanks. :) I'll close this ticket then.
