### ISSUE TITLE
Allow for colons `:` to be used in labels as a key

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#11259]
### What
Currently, if a key has a `:` Teleport disallows the labels. Some clients have naming conventions in resources that are unable to change and they use colons in the key

### How
Modify the key validator for labels to include `:`
https://github.com/gravitational/teleport/blob/master/api/types/resource.go#L350-L351

### Why
Why do you need this?
Will allow current customers and prospects to use existing labels in their cloud infrastructure 

### Workaround
If a workaround exists, please include it.
Use labels without `:`

**Comment by stevenGravy** [comment]
same as #11196
