### ISSUE TITLE
[docs] create a reference style section for template variable and function references

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#11263]
## Details

There should be a complete reference for the RBAC template variables and template functions. Currently, you need to visit multiple docs to get a complete picture:

* docs/pages/access-controls/guides/role-templates.mdx
* docs/pages/enterprise/workflow/index.mdx
* docs/pages/database-access/rbac.mdx
* docs/pages/kubernetes-access/guides/migration.mdx
* docs/pages/desktop-access/reference.mdx

Here's the list of template functions that I pulled from the doc tree:

- regexp.match
- regexp.not_match
- regexp.replace
- email.local

The mentions of template variables:

- internal.db_names
- internal.db_users
- internal.kubernetes_groups
- internal.kubernetes_users
- internal.logins
- internal.windows_logins

additionally, there are several references to `external.STUFF` since it can be anything sent over by the sso provider. The common ones could be called out and include an explanation that it depends on the provider. Here's some examples:

- external.groups
- external.foo
- external["http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname"]

The last one illustrates the `[]` syntax as opposed to the `.` syntax that is needed for saml attributes that often appear with that URI identifier format. The docs could call out whether that alternate syntax works in any other situations too.

This reference should also point out which places these templates can be used-- I am aware of them being used in at least roles, access requests, and application access definitions. (that may not be an exhaustive list)

### Category

- Improve Existing

I would say that this sort of reference belongs in the existing `docs/pages/access-controls/guides/role-templates.mdx` file in the role interpolation rules section, but a totally new reference doc would work too.

**Comment by klizhentas** [comment]
@programmerq this section: https://goteleport.com/docs/setup/reference/resources/#role should have all the variables, fields, etc.

**Comment by ptgott** [comment]
Related: https://goteleport.com/docs/reference/predicate-language
