### ISSUE TITLE
Ansible docs missing from website.

### ISSUE THREAD

**Issue by arouzing** [gravitational/teleport#11275]
### Description
A webpage is not displaying on your website.
**What happened**:
https://goteleport.com/docs/server-access/guides/ansible/ results in a 404
**What you expected to happen**:
The guide to exist.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Go to https://goteleport.com/docs/server-access/guides/ansible/ results in a 404
2. Witness the page error out.

Thanks in advance for looking into this matter!

**Comment by russjones** [comment]
Hi @arouzing, apologies I moved this guide to https://goteleport.com/docs/machine-id/guides/ansible/ without putting a redirect at the old URL. I'll fix this next week.

Thank you for reporting!

**Comment by aqiank** [comment]
The page is still missing.
