### ISSUE TITLE
Broken Terraform docs (starter-cluster)

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#11284]
## Details
In the `readme.md` file here - https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/starter-cluster/README.md - it references this page: https://goteleport.com/docs/aws-oss-guide/#single-oss-teleport-amis-manual-gui-setup - but it is broken with a redirect loop.

Snippet from the readme:

> How does this work?
> Teleport AMIs are built so you only need to specify environment variables to bring a fully configured instance online. See data.tpl or our [documentation](https://gravitational.com/teleport/docs/aws_oss_guide/#single-oss-teleport-amis-manual-gui-setup) to learn more about supported environment variables.
> 

It looks to be `v6` docs that this page re-appears in our defunct Infrastructure Guides page.

### Category

- Improve Existing
- Remove Outdated

**Comment by ptgott** [comment]
I've tried this link today and can confirm that there is no longer a redirect loop.
