### ISSUE TITLE
tsh does not correctly error when binding to a local port already in use

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#11293]
### Description
Executing the following commands in 2 different terminals (i.e. keep both connections active at the same time):
`tsh ssh --cluster=<cluster_name> -L 3025:127.0.0.1:3025 ubuntu@<ip_of_host_1>`
`tsh ssh --cluster=<cluster_name> -L 3025:127.0.0.1:3025 ubuntu@<ip_of_host_2>`

They both succeed and open an ssh session to the relevant host.  Looking at my bound ports only the first process is actually listening on port 3025 so that confirms that only one process was able to bind on the local port.

doing an equivalent flow with using ssh directly produces the expected warning:
`bind [127.0.0.1]:3025: Address already in use`

Expectation would be for `tsh` to mimic `ssh` behavior and error out if unable to bind to the local port already in use.

**Comment by Tener** [comment]
@EdwardDowling looks like `v10` branch is missing this PR. Is this intentional, or simply missing?

**Comment by EdwardDowling** [comment]
> @EdwardDowling looks like `v10` branch is missing this PR. Is this intentional, or simply missing?
Ah that was unintentional, I'll fix that now.

**Comment by Tener** [comment]
@EdwardDowling thanks for the v10 backport! Looking further, v8 doesn't have the backport either. Do you mind doing the backport to v8 too? This makes it possible for me to backport https://github.com/gravitational/teleport/pull/14745 cleanly.
