### ISSUE TITLE
Accept environment variables in the OAuth token field

### ISSUE THREAD

**Issue by WilliamLoy** [gravitational/teleport#11324]
### What
What would you like Teleport to do differently?
`[slack]
token = "xoxb-11xx"             # Slack Bot OAuth token`

This field currently only accepts string values. 
### How
How would you implement this?
Allow the use of environment variables or file paths in the OAuth token field. 
### Why
Why do you need this?
The customer would like to be able to hide the token value without having to write a script to do so. 
### Workaround
If a workaround exists, please include it.
none

**Comment by marcoandredinis** [comment]
@WilliamLoy You can read the token from a file
Just set the token value to the file which contains the token
```
[slack]
token = "/<token_location>"
```

**Comment by WilliamLoy** [comment]
Closing in favor of documentation update.
