### ISSUE TITLE
tsh does not read /etc/environment 

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#11327]
### Description
Regression, customer has to source every time /etc/environment when they use tsh instead of ssh (tsh does not read /etc/environment)

**What happened**:
Customer is using tsh instead of ssh now and they seem to be having problems with tsh not respecting /etc/environment. They have a cert export that is required for their particular use-case, but tsh does not appear to source the global environment file. It seems we had a fix for this issue previously in PR #3317, but has regress since then. 
(Same issue happens from the browser access, running teleport cluster 7.3.17)

**What you expected to happen**:

That Teleport sessions allows vars from /etc/environment to be sourced when using tsh. Customer states that when they use ssh to log into the same host, then /etc/environment is read. 

How can we have tsh respect global environment files so an export var can be read?

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Update path on source file /etc/environment
e.g /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/test:/snap/bin
2. echo "$PATH" ===> shows original user path
3. Attempt to source /etc/environment  ===> shows new path

### Server Details
- Teleport version (run `teleport version`): Teleport v7.3.3 git:v7.3.3-0-g47ccf9e5f go1.16.2
- Server OS (e.g. from `/etc/os-release`): Ubuntu 18.04.5 LTS 
- Where are you running Teleport? AWS

### Client Details
- Tsh version (`tsh version`): 7.3.3
- Computer OS: Mac

### Debug Logs
None, just our own testing which can be done via reproducing steps provided. 

gz#4289

**Comment by Erick-Reyes** [comment]
@russjones Seems a variation of this issue was fix previously: 
https://github.com/gravitational/teleport/issues/3021

So this might be a regression potentially. Not completely sure.

**Comment by gschwim** [comment]
Seeing the same behavior.
version: ```Teleport v9.0.2 git:v9.0.2-0-g354b8c037 go1.17.7```
Ubuntu server 20.04

**Comment by Jamira40** [comment]
We are observing same issue. Client is installed from latest release during deployment of server. Ubuntu 20.04

**Comment by corkrean** [comment]
Enabling PAM with the default settings solves this issue. https://goteleport.com/docs/server-access/guides/ssh-pam/

**Comment by zmb3** [comment]
Correct. Reading `/etc/environment` is a PAM thing, not a Teleport thing. This means PAM must be enabled in order for this to work.
