### ISSUE TITLE
tsh closes local listener upon connection problems with remote host when forwarding ports

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1133]
## Problem

Teleport can be used to forward connections from a local port to a port on a remote server with the following command:

```
tsh --proxy=localhost --user=rjones ssh -L 8080:remote.example.com:8080 localhost
```

This will start a listener on `127.0.0.1:8080` that forwards connections to `remote.example.com:8080`. In addition, `tsh` will open a shell to the remote server.

However, if an error occurs when communicating with the remote host, Teleport closes the listening socket and leaves `tsh` running. This has two problems, it doesn't indicate to the user any error occurred when forwarding the connection and `tsh` incorrectly closes the listening socket.

## Proposed Solution 

If an error occurs while forwarding a connection, we should not close the listener. The listener should be kept open so the user can establish another connection at some point in the future.

In addition, if an error occurs while forwarding a port we should log the error in the terminal like OpenSSH does so the user is aware of the connectivity problems (and can potentially resolve the issues with the remote host).

## Importance

This issue is affecting an enterprise customer.

**Comment by klizhentas** [comment]
Can't reproduce it
