### ISSUE TITLE
Add docs for how to unlock a Teleport user 

### ISSUE THREAD

**Issue by KasperSkytte** [gravitational/teleport#11350]
## Details
How can I unlock a locked user account after too many failed login attempts? Can't find it anywhere

### Category
- Improve Existing

**Comment by webvictim** [comment]
Good question, and the answer should definitely be in the docs.

IIRC: 
- run `tctl get user/<locked_username> > user.yaml`
- edit `user.yaml` and change `locked: true` to `locked: false`
- run `tctl create -f user.yaml` to update the user

**Comment by antoniotorres** [comment]
Thanks @webvictim. That worked for my user.

**Comment by ptgott** [comment]
We have the ["Session and Identity Locking"](https://github.com/gravitational/teleport/blob/7cd49e97566d11e1eb2582971915a3b88ce52992/docs/pages/access-controls/guides/locking.mdx) guide in the docs, but unless I'm missing something, this is a different mechanism than locks related to failed logins. We'll need to determine a good home for this information.

**Comment by webvictim** [comment]
Yes, this is more of a local Teleport user-specific issue where we automatically lock local users that fail 5 password/MFA attempts (to prevent brute force attacks). The exact specifics of how this work are in the Teleport codebase but not documented anywhere.

**Comment by zmb3** [comment]
Fixed in #25022
