### ISSUE TITLE
Allow admins to pass labels via magic link

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#11355]
### What
A lot of our customers use the magic link to install teleport across a large number of instances during onboarding and/or use cases such as qa testing. It would be nice if they could pass a label set during install instead of having to manually go through and modify each individual /etc/teleport.yaml file after creation as this gets burdensome for use cases with dozens or hundreds of nodes being spun up and down.

**Comment by russjones** [comment]
@Aharic This is being added as part of our time to first value work here: https://github.com/gravitational/teleport/issues/10342.
