### ISSUE TITLE
MachineID Support 'Set up mutual TLS' for Teleport Database Access 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#11358]
### What
We currently require users to export host CA to connect Databases and complete set up.
https://goteleport.com/docs/database-access/guides/redis/#step-45-set-up-mutual-tls

```
# Redis Example
tctl auth sign --format=redis --host=redis.example.com --out=server --ttl=2190h
# MySQL Example
tctl auth sign --format=db --host=db.example.com --out=server --ttl=2190h
``` 
It would be good if MachineID could be used to retrieve these certs

**Comment by benarent** [comment]
@r0mant Do you have feedback or thoughts on ways I could automate this? It seems other people in the community are running into this issue and without a lot of extra `tctl auth export` automation I have to create a lot of extra scripts to automate my mutual TLS set up.

**Comment by strideynet** [comment]
Duplicate of https://github.com/gravitational/teleport/issues/20056
