### ISSUE TITLE
Embed videos into empty states

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#11360]
Embed videos into new empty states for joining resources.

![image](https://user-images.githubusercontent.com/5017502/159584674-f2653d1d-9a62-41f3-9a05-0777f805239a.png)

**Comment by xinding33** [comment]
Screenshot of old empty states documented here: https://docs.google.com/document/d/11JQF3l2fjSc-ll-C7S6rN0dmdYFJcfFJA9A-CQZFUEM/edit

**Comment by xinding33** [comment]
@rishibarbhaya-design after you wrap up the current passwordless work, can you modify the new empty state designs to embed the videos?

**Comment by rishibarbhaya-design** [comment]
![applications](https://user-images.githubusercontent.com/88441969/164553335-c159e567-d80c-42f9-bc8c-4121449a8611.jpg)
![databases](https://user-images.githubusercontent.com/88441969/164553337-8c56c131-6c7a-4b1f-a2aa-1e350e267e80.jpg)
![desktop](https://user-images.githubusercontent.com/88441969/164553338-5e14b579-e662-4505-8372-ff239c345b15.jpg)
![kubernetes](https://user-images.githubusercontent.com/88441969/164553339-d5e9095b-a9bc-48ef-8f90-2aeb4b94e826.jpg)
![servers](https://user-images.githubusercontent.com/88441969/164553340-1534cbb4-7b10-4475-93d4-eff3e7897579.jpg)

**Comment by russjones** [comment]
@benarent @dumez-k Do we have new empty state videos ready? We don't need all of them ready, we can get going with the ones you have.

**Comment by dumez-k** [comment]
Hi @russjones playing a little bit of catchup here as Ben is on vacation for the next week or so. Looking at our asana backlog I can't find any tasks for empty state specific videos and haven't heard anything from Ben. Can't find anything in Slack about this either. Was this ask communicated recently? If not I can totally create some asana tasks and we can work on prioritizing them!

**Comment by xinding33** [comment]
No longer relevant as we decided to work on teleport discover instead.
