### ISSUE TITLE
Duration time in session playback

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#11385]
For Windows session recordings, the Duration column matches how long it takes to play back the recording, because the desktop session player does "play" the dead time (the screen sits static during this time).

For SSH, we skip over dead time during playback. For sessions with lots of idle time, it may only take a fraction of the total duration to play back the session. No data is missing in this case, but it can be surprising to users.

Consider making this behavior consistent or at least documenting the discrepancy so it's clear that no data is missing from the recording.

**Comment by zmb3** [comment]
Hey @scottpgallagher - I'm not sure I understand the request.

For the duration, we're just computing the amount of time between the "session started" event and the "session end" event. This behavior is the same for SSH and Windows sessions.

Can you show a screenshot or example of what the duration reads compared to what you'd expect?

**Comment by scottpgallagher** [comment]
![Screen Shot 2022-03-23 at 12 23 38 PM](https://user-images.githubusercontent.com/51385814/159747701-f8103e9b-5127-405a-8c42-85d84582c1cf.png)

For example, in this screenshot Duration shows 9 minutes; but full video playback is only 4 seconds.....I enter the session; run some commands, then don't exit for 9 minutes of being idle.

**Comment by zmb3** [comment]
Ah, I see.

The duration column is accurate in both cases - it's describing the true length of the session.

The discrepancy is during playback:

- the SSH player "skips over" dead time, making it appear like the recording doesn't contain the full session (with the advantage of making it easier to watch the whole thing)
- the desktop player accurately pauses during dead time, which may match user expectations better, but can make it difficult to quickly watch a recording with lots of dead time in it

**Comment by GunFood** [comment]
Hi,

The option to have full length ssh recordings or clearer description in the session recording list is important to have the sessions fully auditable. Especially in the public sector are high needs and standards, customers has to face, if they want to run the intrafstructure using Teleport as one part.

I think an option to

1. set the ssh session recording to full length, so dead time is also included in the recording or
2. an additional column next to the session time called "active time", which states the actual working time in the recording

could be a possible solution.

**Comment by klizhentas** [comment]
what if we keep things as is, but on hover show active time and then full time for ssh sessions?

**Comment by klizhentas** [comment]
@zmb3 do we need any other decision, see the comment above
