### ISSUE TITLE
Implement A --as Wrapper for Kubernetes TSH Login for Users with Multiple Roles for All Kubectl Commands

### ISSUE THREAD

**Issue by Richard-Barrett** [gravitational/teleport#11402]
### What
What would you like Teleport to do differently?

Teleport should be able to handle the kubernetes `--as` flag on the initial login for a user defined with multiple roles. 
Right now, the implementation requires that a user us the `--as` to impersonate another user in regards to the overall flow model as follows:
- 1. `tsh login --proxy=something.com:443
- 2. `tsh kube login something-region`
- 3. `kubectl <some_command> --as teleport-user` flag or using the key value pair `app:appname`

### How
How would you implement this?
The implementation should carry over from the `tsh kube login` to use the `--as` flag setting the initial user for all future kubectl commands. Or the `tsh login` should have the ability to set the default user that will be wrapped into the API for Kubernetes `kubectl` issuances.

### Why
Why do you need this?
It would decrease the hassle and the confusion for users with multiple roles. 

### Workaround
If a workaround exists, please include it.
The workaround is use `--as` and the user every single time you want to issue a `kubectl` command to the Kubernetes API server. 

gz#4821

**Comment by r0mant** [comment]
@tigrato Let's add a `--kube-user` flag to `tsh kube login` command so the user would be able to run `tsh kube login --kube-user=alice my-k8s-cluster` which would set this user as default in their kubeconfig. Then subsequent `kubectl` commands will default to that user.
