### ISSUE TITLE
UX for adding an IAM bot token is funky.

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#11405]
### Description

**What happened**:

We currently get people to create IAM tokens using a yaml config and `tctl create`, but when you add the bot. It makes a hard requirement to have the same name as the yaml config. I would just remove the requirement to name it, if the name has been already set. 

```
➜  tctl bots add robot --token=iam-token_3 --roles=access
ERROR: error while creating bot
cannot add bot: role "bot-robot" already exists

➜  tctl bots add robot-iam --token=iam-token_3 --roles=access
ERROR: error while creating bot
token "iam-token_3" is valid for bot with name "bot-ansible-a", not "robot-iam"

➜  tctl bots add bot-ansible-a --token=iam-token_3 --roles=access

```

**Comment by strideynet** [comment]
This is resolved by the new Bot resource flow for creating bots introduced in v15.
