### ISSUE TITLE
Option to set recording store location

### ISSUE THREAD

**Issue by GunFood** [gravitational/teleport#11409]
### What
In the moment sessions are recorded. They are logged in /var/lib/teleport/logs/records. We could mount a different filesystem to this folder, but a nicer option would be, to configure a different folder in Teleport. Maybe with ftp:// or nfs-links as target.

### How
As recording is configured in Auth service, I would add an option
recoding_directory
This directory has to be used in /var/lib/teleport/[sid]/ daily logs and in the recorded sessions list.

### Why
We have high security requirements and having potential important logging on a centralized host is a basic. So, we don't need to rely on a way to fetch the recordings from the proxy server, then having it stored directly from the proxy to the recording server.
And it also saves space on the proxy host.

### Workaround
We fetch the recordings via a script from the proxy server and have them backed up centrally.

**Comment by scottpgallagher** [comment]
For this we would probably recommend not storing this data on the proxy/auth server and instead use a different backend as per the docs here: https://goteleport.com/docs/setup/reference/backends/

**Comment by mdrasheek** [comment]
The given doc URL says only about the AWS S3 setup. Please share syntax to setup S3 based backends (i.e., non AWS like minio setup) using access and secret keys. Also I request to share syntax for setting up alternate directory if we have mounted a highly available storage in the auth server.

**Comment by zmb3** [comment]
This has always been possible by setting:

`audit_sessions_uri: file:///path/to/some/other/dir`
