### ISSUE TITLE
Option to define the session recording keep time

### ISSUE THREAD

**Issue by GunFood** [gravitational/teleport#11410]
### What
I would like to have an option, to set how long saved recordings should be stored. 

### How would you implement this?
I would add an option
recording_keep_time

Teleport could run a cleanup, maybe at the first session opened at the day, to remove old recordings or as a cronjob.
The same timeframe should be used to clean up the /var/lib/teleport/[sid] - day logs.

### Why
For GDPR it's important to store sensitive information, and a full length session recording could be very sensitive as it is directly linked to the user, only a defined time.

### Workaround
Manually configure cronjobs to clean up recordings and old logs.

**Comment by scottpgallagher** [comment]
Currently you can limit what session recordings users can see (right now just their own sessions) and have admin users with the ability to see all session recordings: https://goteleport.com/docs/access-controls/reference/#rbac-for-sessions

**Comment by zmb3** [comment]
Closing as duplicate of #5609
