### ISSUE TITLE
app access: document session recording/playback

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#11418]
I had no idea myself how session recording/playback worked until I read @webvictim's awesome explanation at https://github.com/gravitational/teleport/discussions/11334.

I then searched our docs and this is not mentioned anywhere. It should be.

**Comment by webvictim** [comment]
It'd be awesome if we could actually support playing back an app session via `tsh play --format=json` with the app session ID too, rather than requiring that you log onto the auth server, dig out the chunk IDs, etc. Maybe a little out of scope though.

**Comment by webvictim** [comment]
I've just realised that the workaround I detailed in the discussion doesn't work for Cloud customers as you can't log onto the auth server to access the session chunks directly. With this in mind, I think the request to implement this via `tsh play` is actually a lot more important than I thought.

**Comment by strideynet** [comment]
Came across this whilst performing the application access manual testing. We could definitely do with getting this into the documentation or building support in for this properly.

**Comment by zmb3** [comment]
See also #4943

**Comment by xu-xiang** [comment]
The WEB audit log should support configuration to record complete HTTP fields, such as http request data, http response data , This is critical for security analysis.

**Comment by webvictim** [comment]
Teleport doesn't currently log the payloads of web requests or responses to prevent potentially confidential data from showing up in its audit logs. This is the same reason we also don't log responses to database queries.

It would also entail a huge increase in storage volume.

**Comment by moisesmejia1200** [comment]
The customer would like to ensure this FR would include the following in the audit logs 

```"ei": 0,
  "event": "<app_request>",
  "uid": "<uid>",
  "code": "<code>",
  "time": "<time>",
  "cluster_name": "<cluster-name>",
  "status_code": 200,
  "path": "<>",
  "raw_query": "",
  "method": "GET",
  "app_uri": "<URL>",
  "app_public_addr": "<URL>",
  "app_name": "<app name> "
}```

**Comment by xinding33** [comment]
Notes from our internal discussion: we should formalize @webvictim's comments [here](https://github.com/gravitational/teleport/discussions/11334) in our docs.

**Comment by zmb3** [comment]
Additionally, @webvictim's comments require direct access to the auth server, which is not possible for cloud customers. We'll be updating that by recommending the use of `tsh play` for app access sessions, which is supported but has a few UX issues to work out, which are mentioned here: https://github.com/gravitational/teleport/issues/11418#issuecomment-1157450145

**Comment by ptgott** [comment]
Closing since we have `tsh play` for applications documented in the [tsh guide](https://github.com/gravitational/teleport/blob/master/docs/pages/connect-your-client/tsh.mdx#playing-recordings) and some details on application session recording in the session recording [reference](https://github.com/gravitational/teleport/blob/master/docs/pages/architecture/session-recording.mdx#app-sessions). If there are more specific issues with our app session recording docs, we can flag them as new GitHub issues.
