### ISSUE TITLE
Sizes for Recorded Sessions in Desktop Access

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#11425]
## Details
Provide example sizes of recorded desktop sessions.  Would be good to have different sizes based on resolution sizes and length of session.

### Category
- New Feature

**Comment by ibeckermayer** [comment]
A note in the docs was added [here](https://github.com/gravitational/teleport/pull/18655/files#diff-8474ce743bbc178ac09253ab70b0d0d3d434d9916792221ee117fd4c824be15eR81-R88).
