### ISSUE TITLE
SSO connector name is case-sensitive

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#11427]
### Description

SSO connector names are case-sensitive.

This is not a problem when using the Web UI (you just click on the SSO connector button). However, from the CLI the customer tried to run `tsh login --auth=okta` and it simply failed without indicating why. The reason was the connector name was `Okta` and the customer had to type `tsh login --auth=Okta`.

Customer had to read Teleport source to figure out the issue.

**Comment by zmb3** [comment]
@hatched on this one, no need to do any sort of case-sensitive comparison. Instead, if the specified auth connector is not found, update the error message to list all available auth connectors.
