### ISSUE TITLE
Ability to specify custom API endpoints for `aws` mode

### ISSUE THREAD

**Issue by ThelonKarrde** [gravitational/teleport#11423]
### What
What would you like Teleport to do differently?

I would like to request an option to be able to specify custom endpoints of dynamodb and s3 in `aws` storage mode.

### How
How would you implement this?

Additional parameters in `teleport.yaml` and options in charts.

### Why
Why do you need this?

Example: I'm running a kubernetes cluster with ScyllaDB with enabled DynamoDB API compatible interface and Minio as S3 storage. I would like to be able to use them instead of AWS endpoints as teleport storage backend.

### Workaround
If a workaround exists, please include it.

So far I don't know any except of DNS repoint in cluster which is not really good.

**Comment by webvictim** [comment]
Teleport doesn't (knowingly) support any provider other than DynamoDB itself for the `dynamo` backend at present (as described in #3329. I think that providing an optional override for the S3 URL format is doable though.
