### ISSUE TITLE
Jenkins build fails due to unstable unit-tests 

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#1143]
Here is the PR #1142.

![image](https://user-images.githubusercontent.com/7816406/28288301-c6173640-6b0c-11e7-9f8f-2834d0b0007e.png)

**Comment by kontsevoy** [comment]
@alex-kovoy not following... you created a ticket, fixed it (and merged) but assigned it to me?

**Comment by kontsevoy** [comment]
@alex-kovoy we had a Jenkins outage (stuck processes consumed 100% CPU utilization) at that time. Some tests could be more reliable, true, but I'll close this for now.
