### ISSUE TITLE
Machine ID ssh_config requires legacy SSH handler to be enabled

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#11445]
### Description

**What happened**: The generated `ssh_config` assumes port 3023 is open, but newer clusters with multiplexing enabled disable this handler making the default SSH config unusable.

**What you expected to happen**: The generated `ssh_config` should work regardless of Teleport server configuration. Ideally it should proxy connections just like `tsh proxy ssh` does.

gz#5028

**Comment by teleport-contractor** [comment]
Spent a bit of time working to try to get this going using our Ansible guides. My cluster is using multiplexing and in its current form you cannot ssh or do anything due to the `3023` port setting in the `ssh_config`. Even changing out the port to `443` still fails.

**Comment by Valien** [comment]
Encountered the same issue today while working through our Ansible guides on a `v9.0.1` cluster and node. Couldn't get Ansible working so backtracked and tried to get SSH working and no go due to the port issue.

**Comment by timothyb89** [comment]
We've been looking into workarounds for this and have settled on adding `tsh` integration into Machine ID. We've refactored Machine ID's default output in https://github.com/gravitational/teleport/pull/11596 to generate identity files which can be passed to tsh:

```bash
tsh -i /opt/machine-id/identity ssh alice@node
```

`tsh ssh` supports multiplexed SSH sessions as normal, but we just provide Machine ID's identity file in lieu of logging in.

We'll also be introducing wrappers around `tsh` to provide proxy functions:
```bash
tbot proxy ssh user@host:port
```

This part is still a work in progress, but we'll be able to update our generated `ssh_config` to use `tbot proxy`, exactly how `tsh config` does it today.
