### ISSUE TITLE
Provide way to download a specific version of Teleport via DEB

### ISSUE THREAD

**Issue by emmahsax** [gravitational/teleport#11461]
## Details
The Teleport documentation [says we can install Teleport using the DEB repo](https://deb.releases.teleport.dev/). The instructions look something like this:

![image](https://user-images.githubusercontent.com/7562793/160153937-d0938c63-ba9c-43d0-ab50-81dccd4c2870.png)

This works as expected. However, running those commands automatically install the latest version of Teleport (currently v9.0.1). But, there's no documentation of any way to install a specific version. I would expect something like this to work:

```bash
echo 'deb https://deb.releases.teleport.dev/ stable 8.3.3' | sudo tee /etc/apt/sources.list.d/teleport.list
```

But it does not, returning an error similar to this:

```
W: Skipping acquire of configured file '8.3.3/binary-arm64/Packages' as repository 'https://deb.releases.teleport.dev stable InRelease' doesn't have the component '8.3.3' (component misspelt in sources.list?)
```

It would be awesome if there was either:
1. Documentation explaining how to install a specific Teleport version via DEB
2. Adding a way to install the specific version via DEB and _then_ updating documentation accordingly

### Category

- New Feature OR Improve Existing

**Comment by Valien** [comment]
Related: https://github.com/gravitational/teleport/issues/7546

**Comment by webvictim** [comment]
We're tracking the work we're doing to allow specific versions of DEB packages to be installed from the DEB repo here: https://github.com/gravitational/teleport/issues/9770

In the meantime, if you want a DEB for a specific version of Teleport you can download the package itself from here: https://goteleport.com/teleport/download/

**Comment by fheinecke** [comment]
This should be released/available for APT/deb artifacts now. See the updated docs at https://goteleport.com/docs/installation/#linux.

Closing as completed.

**Comment by na1k3** [comment]
Hi there! 
Is there a way to download deb package for bullseye version 10.3.16?

**Comment by fheinecke** [comment]
@na1k3 sure - there are several ways:
Via our release service:
* https://cdn.teleport.dev/teleport_10.3.6_amd64.deb
* https://cdn.teleport.dev/teleport_10.3.6_i386.deb
* https://cdn.teleport.dev/teleport_10.3.6_arm.deb
* https://cdn.teleport.dev/teleport_10.3.6_arm64.deb

Via APT:
```shell
# Download the signing key for the APT repo
sudo curl https://apt.releases.teleport.dev/gpg -o /usr/share/keyrings/teleport-archive-keyring.asc

# Add the APT repo with stable/v10 component
echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] https://apt.releases.teleport.dev/debian bullseye stable/v10" | \
    sudo tee /etc/apt/sources.list.d/teleport.list > /dev/null

# Pull in the metadata from the new repo entry
sudo apt-get update

# Install the package. `teleport-ent` can be replaced with `teleport` if desired.
sudo apt-get install teleport-ent=10.3.6

# Alternatively, download but don't install:
apt-get download teleport=10.3.6
```

That said I would recommend that you upgrade if at all possible. Version 10 is a couple of years old now I believe and no longer supported.
