### ISSUE TITLE
Simplify Kubernetes joining process through web UI

### ISSUE THREAD

**Issue by mcbattirola** [gravitational/teleport#11465]
This is part of #10340

I'll use this issue to propose what the flow could look like and gather feedback

___

### What
Add a `Add Kubernetes` button on the web UI like the ones in apps, servers and db screens

### How
Use the [teleport-kube-agent](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-kube-agent) to add a simple way to add the cluster. Provide links to the helm file reference and our docs if the user wants to use another method.

### Why
Reduce time to first value

**Comment by webvictim** [comment]
Love this. Rather than suggesting the use of `--set` on the command line, could we embed a heredoc to write a `prod-cluster-values.yaml` file and use that instead? Helm's CLI templating is nasty and I think people will get greater value from being able to edit their values in a YAML file and run `helm install` rather than needing to preserve the full escaped CLI every time. It'll also allow them to add annotations and other supported functionality way more easily in future.

```bash
cat << EOF > prod-cluster-values.yaml
roles: kube
authToken: abc123abc123abc123...
proxyAddr: teleport.example.com:443
kubeClusterName: prod-cluster
teleportVersionOverride: <proxy version>
EOF

helm repo add teleport https://charts.releases.teleport.dev && helm repo update
helm install -f prod-cluster-values.yaml
```

It'd also be good to tell people that the name that will show up for their cluster in `tsh kube ls` is `<proxy FQDN>-<cluster name>` so `teleport.example.com-prod-cluster`.

**Comment by webvictim** [comment]
It'd also be awesome if we could add this same flow to add applications and databases via the `teleport-kube-agent` chart as well. It becomes somewhat harder as we need to combine people's values for charts.

I almost think this could eventually become a fully-featured wizard interface with checkboxes to enable "Kubernetes", "Database", "Applications" etc which show new sections when enabled, and then a button to click to add a new rows with settings for each database/app, etc.

**Comment by mcbattirola** [comment]
Great ideas @webvictim , thanks!
I've incorporated the feedback on the proposal and created a new issue to implement using the helm chart to add other resources

**Comment by mcbattirola** [comment]
@rishibarbhaya-design looks like we are good with the flow, can you provide us a design? Do you need any more information?

**Comment by xinding33** [comment]
@mcbattirola latest designs available here: https://www.figma.com/file/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?node-id=1856%3A8594

**Comment by rishibarbhaya-design** [comment]
![home](https://user-images.githubusercontent.com/88441969/164075733-7796fab8-4751-4a84-96cd-61bfab708994.png)

![step_1](https://user-images.githubusercontent.com/88441969/164075728-610c73fa-f54e-4a2a-8935-949c07bf54fb.png)

![step_2](https://user-images.githubusercontent.com/88441969/164075731-5ea30fb6-d647-48e1-a006-0c17e5446c39.png)

**Comment by rishibarbhaya-design** [comment]
Prototype Link: https://www.figma.com/proto/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?node-id=1856%3A8595&scaling=min-zoom&page-id=1856%3A8594&starting-point-node-id=1856%3A8595
