### ISSUE TITLE
Improve machine ID config generation

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#11483]
I was reading the machine ID guide:

https://goteleport.com/docs/machine-id/guides/jenkins/

I am wondering if we can reduce the steps with creating a systemd unit and /etc/tbot.yaml 
Most of the content there is a boilerplate. See how event handler does it:

https://goteleport.com/docs/setup/guides/fluentd/#step-26-generate-configuration

```bash
./teleport-event-handler configure . teleport.example.com:443
```

I am wondering if `tbot configure` could generate all necessary files for users in one command

**Comment by timothyb89** [comment]
We do have a (hidden) `tbot config` today that dumps a (golang pretty-printed) config file, I think it would be good to have it dump a YAML config as well which could be easily piped to `/etc/tbot.yaml`.

As a possible alternative (or addition), a `tbot install` that installs a systemd .service, adds a system user, assigns correct permissions, etc might be helpful. There's probably a similar story for our .deb and .rpm packages but from a brief look while preparing for the 9.0 release configuring all that would be a bit tricky with our current packaging scripts.

**Comment by strideynet** [comment]
I'll be starting work towards this ticket by converting `tbot config` to return a YAML formatted config file as per @timothyb89's suggestion. Once that's done we can progress towards an installation command that leverages that work, as well as creating appropriate systemd services etc.
