### ISSUE TITLE
Failed to create (dynamic) label for `hostname`

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#11498]
### Description

**What happened**:
The server's hostname label has the output of an error
![image](https://user-images.githubusercontent.com/689271/160386156-53af29e2-0500-4026-a3d3-766a2f295903.png)

**What you expected to happen**:
It should have the correct hostname

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1) run `docker run --rm -it redhat/ubi8:8.5 sh -c "hostname"`

(I can provide a real reproduction steps if necessary, but it should be reproducible when using the docker image above)

### Server Details
- Teleport version (run `teleport version`): 9.0.1
- Server OS (e.g. from `/etc/os-release`): "Red Hat Enterprise Linux" / "8.5 (Ootpa)"
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): local/docker
- Additional details:

### Client Details
- Tsh version (`tsh version`): 9.0.1
- Computer OS (e.g. Linux, macOS, Windows): Linux - redhat/ubi8:8.5
- Browser version (for UI-related issues): -
- Installed via (e.g. apt, yum, brew, website download): yum
- Additional details:

### Debug Logs

We are relying on the `hostname` binary to set the value for the `hostname` dynamic value
https://github.com/gravitational/teleport/blob/9e1b887d942e55126f3eea5aed5bfc37eae505f4/lib/config/fileconf.go#L180-L182

This works fine for most Linux, Windows and Mac
However, some Linux distros don't ship this binary and spit out this message
```
2022-03-28T11:02:31Z ERRO             Failed to run command and update label: exec: "hostname": executable file not found in $PATH. labels/labels.go:152
```
As an example:
```
$ docker run --rm -it redhat/ubi8:8.5 sh -c "hostname"
sh: hostname: command not found
```
A better approach for *Linux* would be to read `/proc/sys/kernel/hostname`
```
$ docker run --rm -it redhat/ubi8:8.5 sh -c "cat /proc/sys/kernel/hostname"
1c7867bc8182
```
However, that wouldn't work for Mac and Windows machines

To solve this we could have a `FallbackCommand` and run it in case the current `Command` fails to execute

---
For reference, here's how the Go's `os` package does it:
https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/os/sys.go;l=9

**Comment by GunFood** [comment]
I don't think it's a Teleport bug. Maybe a feature-request.
Better option would be to create the labels depending on the maschine you try to connect to and choose the working way for this system.

**Comment by webvictim** [comment]
The issue isn't actually that the binary isn't installed, just that Go doesn't get a `$PATH` variable by default so it needs a full path to the executable (i.e. `/bin/hostname`, which works on Macs and most Linux distros)

This should work:
```yaml
ssh_service:
  commands:
  - name: hostname
    command: ["/bin/hostname"]
    period: 1m0s
```

I can agree that we should fix the path to something that works by default though - that's a simple PR.

**Comment by marcoandredinis** [comment]
@webvictim 
I don't think we should change from `hostname` to `/bin/hostname`
It won't solve the example above, the one using redhat:
```
> docker run --rm -it redhat/ubi8:8.5 sh -c "/bin/hostname"
sh: /bin/hostname: No such file or directory
```

And it would break in Linux distributions where it was previously working, like NixOS:
```
> /bin/hostname
/bin/hostname: command not found
```

@GunFood 
Thank you for your comment
Yeah, I guess this is provided as best effort and should always be configured by the user
However, showing the error message in the UI is, IMO, a bug (low priority, maybe?)

We could change the code to detect erroneous commands, but that could break existing flows
