### ISSUE TITLE
tsh scp with a node name containing semi-colon fails

### ISSUE THREAD

**Issue by capripot** [gravitational/teleport#1149]
I tried this and got an error:
```
> tsh scp root@HOST\:\:2017-07-15T00\:17\:15Z:/app/tmp/file.json tmp/
failed connecting to node HOST. dial tcp: lookup HOST on 1.2.3.4:53: no such host
```

That works tho: `tsh ssh root@HOST\:\:2017-07-15T00\:17\:15Z`

```
> tsh version
Teleport v2.2.3
```

**Comment by kontsevoy** [comment]
@capripot thanks for the report, will take a look. BTW you have the best personal domain name, the team here is jealous.

**Comment by kontsevoy** [comment]
@capripot do you mean the host name containing semicolons or the path on the server?
For example this one works with `tsh` and OpenSSH:

$ tsh scp hi.txt localhost:one\:two/
$ scp hi.txt localhost:one\:two/

But adding `a:b` to `/etc/hosts`:

```
127.0.0.1	localhost a:b
```

... leads to both `tsh` and `scp` not being able to interpret such host properly. Both treat the very first semi-colon as a host:path delimiter.

What behavior are you looking for?

**Comment by capripot** [comment]
@kontsevoy Thanks, got early on board with the `.nyc` :D

I was looking at the second behavior, the semi-colon being in the host name being something like `kangourou::2017-07-15T00:17:15Z`. We create a new instance for each deployment and name it with the timestamp so it's easy to see which one is last. It works fine with `tsh`, I encountered an issue only when trying to use `tsh scp`

**Comment by kontsevoy** [comment]
@capripot correct, because due to `scp` syntax (we did not invent it but we adhere to it) the semi-colon means "end of the host name" since it's used as a delimiter. There's no escaping for it.
