### ISSUE TITLE
Intermittent ERR_EMPTY_RESPONSE accessing Teleport Web UI from Mac

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#11509]
### Description

**What happened**:
Intermittently, users are unable to reach the Teleport Web UI.  Instead, the web UI sends an `ERR_EMPTY_RESPONSE` page and the users cannot access the web page.

zscaler is present in the environment proxying user access to the Teleport Web UI.  Zscaler does have logging and does not report any issues. However looking at a connection to Teleport (on occurrence of the issue) I see the connection stays "open" in Zscaler for a while – before it is closed later on.  No issues are reported but it's as if Teleport never actually closed the connection.

Some additional details of the issue gathered during troubleshooting

- The issue appears for some users at times and other users it is not present
- multiple browsers have been tried while the issue is present and even used openssl to try to download the certificate and it presents an error saying it is unable to connect
- A windows machine works with no problems (switching to a Windows VDI (still using zscaler) and it works no problems straight away
- no root cause has been identified yet for what causes the issue to clear up. After a random amount of time, usually days / weeks, it then works ok on a Macbook
- Nothing else exists between Teleport proxy and end users except zScaler and malware (Crowdstrike)

The following error was noted in the proxy logs around the same time as the issue occurred:
~~~
WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp <redacted>:3080-&gt;[<redacted>:62797](http://<redacted>:62797/): i/o timeout\nStack Trace:\n\t/go/src/[github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:282](http://github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:282) [github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:206](http://github.com/gravitational/teleport/lib/multiplexer.detect%5Cn%5Ct/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:206) [github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1581](http://github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward%5Cn%5Ct/opt/go/src/runtime/asm_amd64.s:1581) runtime.goexit\nUser Message: failed to peek connection\n\tread tcp <redacted>:3080-&gt;[<redacted>:62797](http://<redacted>:62797/): i/o timeout" multiplexer/multiplexer.go:209
~~~

### Server Details
- Teleport version: 8.3
- Where are you running Teleport: AWS EKS

### Client Details
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues): various  and incogntio

**Comment by pschisa** [comment]
Right now confirming if `tsh` connectivity is still available during an outage and see if the lingering zScaler connection can be manually cleared

**Comment by crashdump** [comment]
@pschisa It's not.

```
$ tsh login --proxy=${HOST} --auth azuread --debug
DEBU [CLIENT]    not using loopback pool for remote proxy addr: ${HOST}:443 client/api.go:2986
DEBU             Attempting GET ${HOST}:443/webapi/ping/azuread webclient/webclient.go:62
 
ERROR REPORT:
Original Error: *url.Error Get "[https://${HOST}:443/webapi/ping/azuread"](https://${HOST}/webapi/ping/azuread%22);: EOF
Stack Trace:
     /private/tmp/teleport-20220316-15032-ntr49l/teleport-9.0.1/api/client/webclient/webclient.go:74 github.com/gravitational/teleport/api/client/webclient.doWithFallback
     /private/tmp/teleport-20220316-15032-ntr49l/teleport-9.0.1/api/client/webclient/webclient.go:135 github.com/gravitational/teleport/api/client/webclient.Ping
     /private/tmp/teleport-20220316-15032-ntr49l/teleport-9.0.1/lib/client/api.go:2551 github.com/gravitational/teleport/lib/client.(*TeleportClient).Ping
     /private/tmp/teleport-20220316-15032-ntr49l/teleport-9.0.1/lib/client/api.go:2405 github.com/gravitational/teleport/lib/client.(*TeleportClient).Login
     /private/tmp/teleport-20220316-15032-ntr49l/teleport-9.0.1/tool/tsh/tsh.go:917 main.onLogin
     /private/tmp/teleport-20220316-15032-ntr49l/teleport-9.0.1/tool/tsh/tsh.go:667 main.Run
     /private/tmp/teleport-20220316-15032-ntr49l/teleport-9.0.1/tool/tsh/tsh.go:313 main.main
     /opt/homebrew/Cellar/go/1.17.8/libexec/src/runtime/proc.go:255 runtime.main
     /opt/homebrew/Cellar/go/1.17.8/libexec/src/runtime/asm_arm64.s:1133 runtime.goexit
User Message: Get "[https://${HOST}:443/webapi/ping/azuread"](${HOST}/webapi/ping/azuread%22);: EOF
```

**Comment by pschisa** [comment]
It was identified that restarting zScaler resolves the issue.  This isolated the issue to zScaler and the investigation will continue with their team
