### ISSUE TITLE
Ability to auto import tags from GCP/Azure

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#11517]
Two requests:
- Teleport should allow you to set its hostname/nodename (i.e. what it registers in the web UI and `tsh ls`) from an AWS/GCP/Azure tag, rather than relying on the machine's hostname (which may be generic and not descriptive)
- Teleport should allow you to automatically set AWS/GCP/Azure tags as labels on Teleport nodes.

The customer's request is only actually for AWS and GCP, but I figure it makes a lot of sense to add this for Azure too.

**Comment by zmb3** [comment]
Azure tag importing was added in Teleport 11: https://goteleport.com/docs/changelog/#azure-integrations

GCP is in progress and is being tracked in a dedicated issue (#22815) so I'm closing this one.
