### ISSUE TITLE
Produce a .deb package from the centos7 compatible build

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#11511]
### What
Teleport makes a build marked with centos7 which maintains Teleport compatibility with older glibc versions.  This is only available as a .tar.gz

Feature request is to start producing a .deb package for the centos7 build.

### Why
Easier integration with exisiting config management infrastructure designed around .deb package interaction

### Workaround
Use the .tar.gz pacakge

**Comment by pschisa** [comment]
This would unblock upgrades past v7 for agents and no longer require the user to have a v8 backport for https://github.com/gravitational/teleport/issues/6822

**Comment by r0mant** [comment]
All assets are built on CentOS 7 now so this should be done.
