### ISSUE TITLE
Allow users to specify dial mode "hint"

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#11524]
I often describe the "feature" that allows users to set `teleport.auth_servers` to point at auth servers **or** proxy servers as Teleport's billion dollar mistake.

Because we don't know the user's intent, we have to try dialing directly to auth and via the proxy reverse tunnel. This works well enough if one of the attempts succeeds, but if they both fail then we actually report two connection failures to the user, one of which is completely unrelated to their actual problem. It's hard for us to present a nicer error message or actionable advice because we don't have any idea what the user was trying to do. It's also inefficient, as we have to attempt two connections even though only one (at most) will succeed.

I propose we allow the user to specify their intent with a new (but optional) `dial_mode` configuration option.

For tunneling via proxy:
```
teleport:
  auth_servers:
  - proxy.example.com:3080
  dial_mode: tunnel  
``` 

For direct dial to auth:
```
teleport:
  auth_servers:
  - auth.example.com:3025
  dial_mode: direct 
```

When `dial_mode` is specified we only need to try a single connection rather than attempt to dial via both mechanisms. Further, because we understand what the user was trying to do, we can attempt to offer better error messages (for example, there are a number of x509 errors that only surface when dialing via the proxy - if we know the user intended to dial through the proxy we can attempt to diagnose what went wrong. This information would be too verbose and confusing to present to a user that was attempting to direct dial).

We can even introduce this field as optional for one or two major versions and then make it required in a future update.

**Comment by klizhentas** [comment]
@zmb3 overall I like your suggestion, please do it!

**Comment by zmb3** [comment]
See also #5247, which is similar and will likely be closed when this is addressed.

**Comment by zmb3** [comment]
This is addressed by https://github.com/gravitational/teleport/pull/15761
