### ISSUE TITLE
Google SSO OIDC Connector Changes

### ISSUE THREAD

**Issue by nick-at-teleport** [gravitational/teleport#11545]
## Details
OIDC connector `v2` behaves differently than the current `v3` connector. Transitive group search now requires **Google Workspace Enterprise** or **Google Cloud Identity Premium**.
Link to current docs: https://goteleport.com/docs/enterprise/sso/google-workspace/

### Category
- Improve Existing

**Comment by russjones** [comment]
Fixed in https://github.com/gravitational/teleport/pull/11422.
