### ISSUE TITLE
would teleport accept a postgresql storage backend?

### ISSUE THREAD

**Issue by james-lawrence** [gravitational/teleport#1161]
I might have time to put work into that backend if there is an interest in accepting it.

**Comment by kontsevoy** [comment]
absolutely. the storage back-ends are very easy to implement. Take a look at `Backend` interface in `lib/backend/backend.go`, it is a very simple key-value store interface.

PRs are welcome :)

**Comment by kontsevoy** [comment]
@james-lawrence actually we have a plan in place to allow 3rd party plugins as separate binaries (dynamic libraries). If you build a postgreSQL backend, it would have to be a separate so file loaded via Golang's new plug-in mechanism. The exact interface for this is still being discussed, but we're open to suggestions.
