### ISSUE TITLE
Current stable release version?

### ISSUE THREAD

**Issue by ilovezfs** [gravitational/teleport#1162]
Based on https://github.com/gravitational/teleport/releases/latest it's not clear to me whether 2.2.4 or 2.2.6 is the current stable release version. Could you clarify which should be in Homebrew now? Thanks!

**Comment by klizhentas** [comment]
good time of day! all minor changes of teleport 2.2.x are backwards compatible and stable, so 2.2.6 is the current stable version!

**Comment by ilovezfs** [comment]
@klizhentas cool. Do you mind marking 2.2.6 as the latest so that the GitHub API returns the correct version?

**Comment by klizhentas** [comment]
sure we will!

**Comment by ilovezfs** [comment]
Thank you!!
