### ISSUE TITLE
Automatically add AWS tags to servers

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#11627]
Convert AWS tags attached to a instance into labels. This will allow users to reuse existing discovery/inventory information in AWS with Teleport as well.

On possible implementation is upon startup of a `ssh_service`, query the metadata endpoint for all tags associated with that instances and automatically add all tags as labels. Also attach instance name as a label.

https://aws.amazon.com/about-aws/whats-new/2022/01/instance-tags-amazon-ec2-instance-metadata-service/

Potentially look into doing the same for all resources, not just for SSH servers.

**Comment by webvictim** [comment]
There is one further requirement as part of this request:
- allow the Teleport `nodename` displayed in the web UI/`tsh ls` to be set from an EC2 tag, overriding the default (i.e. `hostname`)
