### ISSUE TITLE
Automatically do a rolling update to `teleport-cluster` chart deployments when `cert-manager` renews certs

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#11622]
### What
The `teleport-cluster` chart should have some way of detecting updated certs when using `cert-manager` and automatically updating these inside the pods.

Similar to https://github.com/gravitational/teleport/issues/3815 - but inside Kubernetes specifically.

### How
Some kind of automated watcher process that can look for certificate updates inside a k8s `Secret` and trigger a rolling update.

### Why
Let's Encrypt certs only last 90 days and after this, you'll see expiry warnings in browsers and for `tsh` clients unless we deploy updated certs.

### Workaround
https://github.com/stakater/Reloader is something that basically does exactly what we need. The best idea might be to have a section of the docs recommending its use (similar to how we do with `cert-manager` and provide an example installation)

**Comment by webvictim** [comment]
Anyone looking to do this in the meantime: see this helpful comment: https://github.com/gravitational/teleport/issues/3815#issuecomment-1085106950

**Comment by webvictim** [comment]
@hugoShaka @r0mant This would be some good low-hanging fruit for us to tackle when updating Helm charts.

**Comment by hugoShaka** [comment]
Restarting the pods is a disruptive operation, especially when running with a lot of proxies. While we can document how to use `reloader` in the guide, the best solution would be for Teleport to support reloading https certs from files. A daily reload would be more than enough given that Kubernetes updates secrets and configmap mounts in less than a minute and and `certmanager` issues new certs 30 days before expiry.

**Comment by webvictim** [comment]
@hugoShaka See https://github.com/gravitational/teleport/pull/19996 🎉 

If we template `proxy_service.https_keypairs.https_keypairs_reload_interval: 12h` or similar into the v12 Helm chart I think this one can be resolved.
