### ISSUE TITLE
changing web_listen_addr is not effecting on base url 

### ISSUE THREAD

**Issue by nuved** [gravitational/teleport#1163]
I try change default port web_listen_addr from 3080 to 80. everything is ok. but when I added  user, 
url had the previous port again.  

 tctl users add novid root
https://teleport.site:3080/web/newuser/1852995348f4406009c0f0eae49a0fdb

**Comment by kontsevoy** [comment]
`tctl` cannot possibly know which port numbers you're exposing the endpoint on. the printed URL is just a suggestion which conveniently works for default configuration, so this behaviour is expected.
