### ISSUE TITLE
2.4 Documentation

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1165]
The following issues highlight the changes we've made in code that need to be reflected within the Teleport and Enterprise documentation:

**RoleV3** https://github.com/gravitational/teleport/issues/1092

- [x] Document new format for the Role resource.
- [x] Document supported rules.
- [x] Document `Allow` and `Deny` conditions.
- [ ] Document how roles can be combined in `AND`, `OR`, and `NOT`.
- [x] Document how access to a server checked (namespace, label, and logins).
- [x] Document how access to a rule is checked (namespace and rule).

**Role Variables** https://github.com/gravitational/teleport/issues/1120

- [x] Add note that role templates are deprecated in 2.3 and will be removed in 2.4.
- [x] Document role variable syntax.
- [x] Document how to use role variables. 
- [ ] Document that role variables can not be used with Trusted Clusters.

**Default Role** https://github.com/gravitational/teleport/issues/1136 https://github.com/gravitational/teleport/pull/1279

- [x] Document the capabilities of the `admin` role.
- [ ] Document that all local users assume the role `admin`.
- [x] Document that Teleport and Enterprise `admin` roles differ.

**Cluster Configuration** https://github.com/gravitational/teleport/issues/1098

- [x] All cluster configuration now must be done from `teleport.yaml`.
- [x] Cluster configuration consists of: cluster name, static tokens, and authentication preference.
- [x] `ClusterName` can only be set once.
- [x] OIDC/SAML connectors must be created using `tctl`.
- [x] `tsh` now has a `--auth` flag used to select the non-default connector.

**tctl**  #1137

- [x] Document resource commands: `get`, `rm` and `create`.
- [x] Rename `del` to `rm` everywhere.

**Trusted Cluster Toggle** #1199 

- [x] Document how to add Trusted Cluster using a resource.
- [ ] Document how to enable/disable a Trusted cluster.

**Role Rules** #1200 

- [x] Document supported rules.
- [x] Document supported verbs.
- [ ] Document default role.
- [ ] Document an example administrator role (all verbs for all rules).
- [ ] Document an example partial partial administrator role (all verbs for some rules).

**Session Access Controls** #1223

- [ ] Document how session access controls work at the moment (`list`, `read`)
- [ ] Document how sessions access controls for Trusted Cluster rely on the role assumed in the Trusted Cluster not your local rule.

**Rule Processing** #1222

- [ ] Document how `where` and `actions` fields work in in rules

**Comment by kontsevoy** [comment]
Most of the documentation has been done. The remainder is going into 2.4

**Comment by kontsevoy** [comment]
Instead of closing it, I renamed it to 2.4.1 (because most of 2.4 features have been covered, except a few chapters I still want to add)

**Comment by kontsevoy** [comment]
Moved to #1720
