### ISSUE TITLE
How do I unlock a bot?

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#11676]
### Description

**What happened**:
Looking at the [RFD](https://github.com/gravitational/teleport/pull/7986/files#diff-ec9e495770e6e889bdae0db75d53c9c15a6c3a3303bd72ab60e1108e2ce876f7R220) unlock should be correct, but it's not working for me on 9.0.3 
```
$ sudo tctl bots lock vun
Created a lock with name "7f38279c-b54f-46aa-8c4a-33dc1ed046f6".

$ sudo tctl bots unlock vun
tctl: error: expected command but got "unlock"
```

**Comment by zmb3** [comment]
Looks like we never implemented `tctl bots unlock`.

For now, `tctl rm locks/<ID>` will do the trick.

**Comment by timothyb89** [comment]
Yep, I opted not to implement it since we don't implement any resource-specific unlocking functionality anywhere else in Teleport. We don't even have a `tctl unlock` to complement `tctl lock`, which admittedly might be a UX problem of its own.

**Comment by strideynet** [comment]
I think we can close this for a few reasons:
- It looks like #14871 will be including a troubleshooting section on the most likely scenario that will cause the bot to be locked, and guides the user to the correct command.
- For now, I think it makes the most sense for unlocking to remain consistent with other resources. We should definitely consider opening a ticket to introduce commands to `tctl` for removing locks on a more resource specific basis (e.g `tctl users unlock [user-name]` `tctl bots unlock [bot-name]`)
- I'm going to open a PR to update the RFD now that we've reached implementation.
