### ISSUE TITLE
Implement `tsh play --format=text`

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#11694]
### What
Various customers/users have requested a way to extract commands/text from a session recording so they can run `grep` against it to find specific strings. This was possible with pre-4.4 session recordings using `zgrep` against the `.chunks.tar.gz` file that was stored inside the `.tar` file (since it was actually an archive) but since we switched to the binary protocol format in 4.4 this hasn't been possible.

### How
`tsh play --format=text`, which just dumps all strings from the session recording without control characters etc.

This approach does have the caveat that it obviously isn't 100% accurate, as you can obfuscate commands so a string won't appear in `grep`, but it would be "good enough" for some use cases.

### Why
It's a useful feature that many people would like to use. it also doesn't require the overhead of setting up enhanced session recording, which isn't available to many users due to kernel version/distro/environment constraints. It also saves time from having to watch a full session recording.

### Workaround
Not great. You can run `tsh play` and pipe it into `strings`, but it's not very readable or useful as it doesn't show everything. It also runs in real time i.e. it takes as long to execute as it does to play the session recording back, which is something that could be optimised with the full file available in text format.

Related: https://github.com/gravitational/teleport/issues/4930

**Comment by zmb3** [comment]
See also:
- #928
- #1527

**Comment by zmb3** [comment]
> You can run tsh play and pipe it into strings, but it's not very readable or useful as it doesn't show everything. It also runs in real time i.e. it takes as long to execute as it does to play the session recording back

With `tsh` v15, you can set `--speed=8x`, which makes this workaround a little more tolerable.

**Comment by webvictim** [comment]
One prospect requested that this functionality be added so that they could use an LLM to process the session recording and summarise its content. Thought that was an interesting use case!
