### ISSUE TITLE
tsh db connect to support password input

### ISSUE THREAD

**Issue by weeband** [gravitational/teleport#11701]
### What
`tsh db connect` command to prompt for password input

### How
with an extra flag, for example ask-db-password :
```
tsh db connect --db-user=xxx --ask-db-password --db-name=yyy zzz
```

### Why
default "recomended" installation for mysql is to run `mysql_secure_installation`, and this command will install plugin validate_password to make sure password is secure, but this plugin need to be uninstalled because `CREATE USER 'alice'@'%' REQUIRE SUBJECT '/CN=alice';` on [mysql self hosted docs](https://goteleport.com/docs/database-access/guides/mysql-self-hosted/) will failed because there's no password provided.

### Workaround
add docs to remove validate_password on  [mysql self hosted docs](https://goteleport.com/docs/database-access/guides/mysql-self-hosted/)
```
# mysql 5.7
mysql> uninstall plugin validate_password;
# mysql 8
mysql>UNINSTALL COMPONENT 'file://component_validate_password'; Query OK, 0 rows affect
```

**Comment by greedy52** [comment]
We have no plan to support password as an authentication method for MySQL. Existing methods like x509 cert-based authentication (for self-hosted databases) and IAM authentication (for cloud-based databases) provider better security.

As for the compatibility with `validate_password`,  you can use a random password (or one that passes the validation) when creating the database user. The user cannot use that password to log in anyway when SUBJECT is required:
```
CREATE USER "teleport-admin"  IDENTIFIED BY RANDOM PASSWORD REQUIRE SUBJECT "/CN=alice";
```
