### ISSUE TITLE
misspelling in an error message

### ISSUE THREAD

**Issue by bboles** [gravitational/teleport#1172]
The term "administrator" is misspelled in these 2 files:

web/dist/app/app.15aaa133e361eb0d234c.js:       var MSG_ERROR_LOGIN_FAILED = 'Login unsuccessful. Please try again, if the problem persists, contact your system **administator**.';
web/src/app/components/msgPage.jsx:const MSG_ERROR_LOGIN_FAILED = 'Login unsuccessful. Please try again, if the problem persists, contact your system **administator**.';

**Comment by kontsevoy** [comment]
@russjones I fixed this already.
