### ISSUE TITLE
Replace MacOS tarball with MacOS package in download links

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#11738]
When prompting users to download Teleport for MacOS, we currently link to unsigned MacOS tarballs which yield the following warning when users try to install:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/24904723/161831297-c61c0bfd-224c-4b39-8305-2b1bbd205b40.png">

This is concerning especially for security-minded developers.

To sidestep this problem entirely, we can point the download link to our MacOS package instead which is signed.

**Comment by hatched** [comment]
@xinding33 can you elaborate on where these prompts are? Are they the ones in the `Add Server` modal?

**Comment by zmb3** [comment]
@hatched yep!
