### ISSUE TITLE
Databases list as available when not using reverse tunnel

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#11767]
### Description

**What happened**:

If a database service is connected directly to the auth service it will list as available but the users can't interact with it.

**What you expected to happen**:

If services are configured that require reverse tunnel they won't list and errors are shown in the node.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.  Add a database service node that connects to the auth service
2. See the DBs list
3. Attempt to do a db connect.

### Server Details
- Teleport version (run `teleport version`): 9.0.3
- Server OS (e.g. from `/etc/os-release`): ubuntu

**Comment by waynechong1995** [comment]
i got 'Failed to add agent - failed to find reverse tunnel address' with this setup, i following the HA setup with an additional node as database service, tried to connect to the auth only server and couldn't get db connect running

**Comment by stevenGravy** [comment]
> 

@waynechong1995 You can only connect through the proxy, not the auth server, for apps, dbs, and k8s services.
