### ISSUE TITLE
Kubernetes agent guide doesn't mention configuring a role for kubernetes_users/kubernetes_groups

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#11774]
## Details
The guide which teaches people how to install the `teleport-kube-agent` chart (https://goteleport.com/docs/kubernetes-access/getting-started/agent/) doesn't make any reference at all to adding `kubernetes_users` or `kubernetes_groups` to a Teleport role so that you can actually log into a cluster and make requests.

We should at the very least detail how to add `system:masters` to the `editor` role or something to make getting started with Cloud easier.

### Category
- Improve Existing

**Comment by stevenGravy** [comment]
same as this https://github.com/gravitational/teleport/issues/10480

**Comment by tigrato** [comment]
The same applies to https://goteleport.com/docs/kubernetes-access/getting-started/local/

**Comment by ptgott** [comment]
@tigrato The local Kubernetes guide doesn't actually set up Kubernetes Access—it just installs the Auth Service and Proxy Service on Kubernetes—so I'm not sure this applies there. (We're in the process of moving the guide outside the Kubernetes Access section).

**Comment by tigrato** [comment]
> @tigrato The local Kubernetes guide doesn't actually set up Kubernetes Access—it just installs the Auth Service and Proxy Service on Kubernetes—so I'm not sure this applies there. (We're in the process of moving the guide outside the Kubernetes Access section.)

@ptgott 
If I remember correctly it enables the Kubernetes access to the local cluster via in cluster config

https://github.com/gravitational/teleport/blob/7fc8f4dfd60c5b6bcbaecae68ee7499839d2bf78/lib/kube/utils/utils.go#L102-L113

Btw, it is worth mentioning that it can enable kube access as well and to do it, `clusterName` or `kubeClusterName` must not be empty

https://github.com/gravitational/teleport/blob/7fc8f4dfd60c5b6bcbaecae68ee7499839d2bf78/examples/chart/teleport-cluster/templates/config.yaml#L88-L92

**Comment by ptgott** [comment]
@tigrato Ah, that makes sense. I'll open a separate issue to include instructions for using Kubernetes Access in the local Kubernetes guide, including configuring RBAC.
