### ISSUE TITLE
Document an official example of an upstart script

### ISSUE THREAD

**Issue by mechastorm** [gravitational/teleport#1177]
This is probably related to #514 but for the interim can we at least have an official example of an upstart script in the documentation. 

There is already an official example of a [systemd unit file](http://gravitational.com/teleport/docs/2.0/admin-guide/#teleport-daemon). Can we also please include an upstart/init.d file equivalent to this.

This will be especially for those that have to deploy Teleport to OSes that have not yet moved to systemd yet - biggest example is the latest Amazon Linux AMI still uses init.d.

I have been using the example of https://github.com/jaxxstorm/puppet-teleport at https://github.com/jaxxstorm/puppet-teleport/blob/master/templates/teleport.init.erb but I'd like verification if this could be officially documented for others? 

The init.d script I am currently using is here - https://gist.github.com/mechastorm/ff4add694afada6ff6b4647aa2cb5797

**Comment by kontsevoy** [comment]
Great suggestion. Adding to 2.3

**Comment by russjones** [comment]
@kontsevoy Started some work on this already and have basic scripts for systemd, upstart, sysvinit, and launchd. They need some more to be cleaned up however: https://github.com/gravitational/rusty/tree/master/daemon (internal gravitational repo)

**Comment by tacerus** [comment]
Hi, as a result of this apparently only an upstart example was provided, not a sysvinit one. I tried making my own, as I run Teleport on Slackware (which, by the way, works exceptionally well with no dependency issues whatsoever), however Teleport does not seem to have a --daemonize option that would allow it to properly run in the background without having to "hack" it through nohup (which prevents proper logging).
I would appreciate if you could include a --daemonize option to ensure compatibility with legacy init systems and possibly include a sysvinit script accompanying it.

This is the script I am currently using, which is, as said, not ideal:

```
/etc/rc.d/rc.teleport
#!/bin/sh
# Start Teleport SSH service:

. /etc/init.d/functions
start() {
	initlog -c "echo -n Starting Teleport: "
	daemon nohup "/usr/local/bin/teleport start --config=/etc/teleport.yaml" 2>/dev/null &
	touch /var/lock/subsys/teleport
	success $"Teleport startup"
	echo
}

stop() {
	initlog -c "echo -n Stopping Teleport: "
	killproc teleport
	rm -f /var/lock/subsys/teleport
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status teleport
		;;
	restart|reload|condrestart)
		stop
		start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		exit 1
esac

exit 0
```
