### ISSUE TITLE
tsh db/app commands not working correctly with --identity flag

### ISSUE THREAD

**Issue by joeportela** [gravitational/teleport#11770]
### Description

**What happened**:
When trying to use `tsh db` commands with a non-interactive user via an identity file, the commands fail on `ERROR: not logged in` or if the ~/.tsh is missing - `Failed to stat file: stat ~/.tsh: no such file or directory.`.  `tsh ls` works fine with the identity file.

`tsh db ls` and `tsh db login` have different outputs, but debug mode shows the same issue of the missing ~/.tsh/* files or the missing ~/.tsh directory.

If I'm already logged in with my normal user (via Github SSO) and then try the commands with --identity for the non-interactive user, the command partially ignores the identity flag passed in and later proceeds using the default profile.

**What you expected to happen**:
`tsh db` commands should respect the identity file passed to them and function normally.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. `tsh logout` to clear any existing profiles
2. generate an identity file either through `tsh login --out ...` or `tctl auth sign ...`
3. run `tsh db ls --identity=identity.txt --proxy=teleport.example.com:443 --login=username` and see failure
4. run `tsh ls --identity=identity.txt --proxy=teleport.example.com:443 --login=username` and see success
5. login via SSO or any normal user (not via --identity file)
6. run `tsh db ls --identity=identity.txt --proxy=teleport.example.com:443 --login=username` and see success but debug logs show SSO user certificates were used

### Server Details
- Teleport version (run `teleport version`): Teleport v9.0.2 git:v9.0.2-0-g354b8c037 go1.17.7
- Server OS (e.g. from `/etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Client Details
- Tsh version (`tsh version`): 9.0.3 (and 8.3.1)
- Computer OS (e.g. Linux, macOS, Windows): macOS and Ubuntu
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download): brew and yum
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

The non-interactive teleport user here is named `githubactions`, my local user is `joe` and my teleport user is my Github username - `joeportela`
Here we can see failures trying to run `tsh db ls` and `tsh db login`, but success with `tsh ls`
```
> tsh logout
Logged out all users from all proxies.

> tsh db ls --debug --proxy=teleport.example.com:443 --identity=githubactions.txt --login=githubactions --cluster=dev
[TSH]       DEBU Extracted username "githubactions" from the identity file githubactions.txt. tsh/tsh.go:1918
[TSH]       DEBU Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:2110
[CLIENT]    DEBU not using loopback pool for remote proxy addr: teleport.example.com:443 client/api.go:3074
            DEBU Attempting GET teleport.example.com:443/webapi/ping webclient/webclient.go:105
[CLIENT]    INFO Connecting to proxy=teleport.example.com:3023 login="githubactions" client/api.go:2322
            DEBU No valid environment variables found. client/proxy.go:116
[HTTP:PROX] DEBU No proxy set in environment, returning direct dialer. proxy/proxy.go:268
[CLIENT]    INFO Successful auth with proxy teleport.example.com:3023. client/api.go:2327
[CLIENT]    DEBU Found clusters: [{"name":"admin","lastconnected":"2022-04-06T16:17:04.623738656Z","status":"online"},{"name":"dev","lastconnected":"2022-04-06T16:17:04.476063994Z","status":"online"}] client/client.go:127
[CLIENT]    DEBU Client  is connecting to auth server on cluster "dev". client/client.go:969
[CLIENT]    DEBU open /Users/joe/.tsh/teleport.example.com.yaml: no such file or directory client/api.go:781

ERROR REPORT:
Original Error: *trace.NotFoundError not logged in
Stack Trace:
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/lib/client/api.go:710 github.com/gravitational/teleport/lib/client.StatusCurrent
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/db.go:53 main.onListDatabases
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/tsh.go:739 main.Run
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/tsh.go:333 main.main
    /opt/homebrew/Cellar/go/1.18/libexec/src/runtime/proc.go:250 runtime.main
    /opt/homebrew/Cellar/go/1.18/libexec/src/runtime/asm_arm64.s:1259 runtime.goexit
User Message: not logged in

> tsh db login --debug --proxy=teleport.example.com:443 --identity=githubactions.txt --login=githubactions --cluster=dev dev-db-main
[TSH]       DEBU Extracted username "githubactions" from the identity file githubactions.txt. tsh/tsh.go:1918
[TSH]       DEBU Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:2110
[CLIENT]    DEBU not using loopback pool for remote proxy addr: teleport.example.com:443 client/api.go:3074
            DEBU Attempting GET teleport.example.com:443/webapi/ping webclient/webclient.go:105
[CLIENT]    INFO Connecting to proxy=teleport.example.com:3023 login="githubactions" client/api.go:2322
            DEBU No valid environment variables found. client/proxy.go:116
[HTTP:PROX] DEBU No proxy set in environment, returning direct dialer. proxy/proxy.go:268
[CLIENT]    INFO Successful auth with proxy teleport.example.com:3023. client/api.go:2327
[CLIENT]    DEBU Found clusters: [{"name":"admin","lastconnected":"2022-04-06T16:17:10.089203088Z","status":"online"},{"name":"dev","lastconnected":"2022-04-06T16:17:04.476063994Z","status":"online"}] client/client.go:127
[CLIENT]    DEBU Client  is connecting to auth server on cluster "dev". client/client.go:969
[TSH]       DEBU Fetching database access certificate for Database(Service=dev-db-main, Protocol=postgres, Username=, Database=) on cluster dev. tsh/db.go:92
[CLIENT]    DEBU open /Users/joe/.tsh/teleport.example.com.yaml: no such file or directory client/api.go:781

ERROR REPORT:
Original Error: *trace.NotFoundError not logged in
Stack Trace:
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/lib/client/api.go:710 github.com/gravitational/teleport/lib/client.StatusCurrent
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/db.go:104 main.databaseLogin
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/db.go:79 main.onDatabaseLogin
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/tsh.go:741 main.Run
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/tsh.go:333 main.main
    /opt/homebrew/Cellar/go/1.18/libexec/src/runtime/proc.go:250 runtime.main
    /opt/homebrew/Cellar/go/1.18/libexec/src/runtime/asm_arm64.s:1259 runtime.goexit
User Message: not logged in

> tsh ls --debug --proxy=teleport.example.com:443 --identity=githubactions.txt --login=githubactions --cluster=dev
DEBU [TSH]       Extracted username "githubactions" from the identity file githubactions.txt. tsh/tsh.go:1918
DEBU [TSH]       Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:2110
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport.example.com:443 client/api.go:3074
DEBU             Attempting GET teleport.example.com:443/webapi/ping webclient/webclient.go:105
INFO [CLIENT]    Connecting to proxy=teleport.example.com:3023 login="githubactions" client/api.go:2322
DEBU             No valid environment variables found. client/proxy.go:116
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:268
INFO [CLIENT]    Successful auth with proxy teleport.example.com:3023. client/api.go:2327
DEBU [CLIENT]    Found clusters: [{"name":"admin","lastconnected":"2022-04-06T16:19:13.044234568Z","status":"online"},{"name":"dev","lastconnected":"2022-04-06T16:19:04.475590873Z","status":"online"}] client/client.go:127
DEBU [CLIENT]    Client  is connecting to auth server on cluster "dev". client/client.go:969
Node Name                                Address         Labels
---------------------------------------- --------------- -----------------
<host>-us-east-2-compute-internal <host>:3022 nodetype=ecs-host
```

After logging in via Github SSO to my user, the same `tsh db ls` command begins with the provided identity user but ends up using my `joeportela` certs later on.
```
> tsh login --proxy=teleport.example.com:443
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:58438/b2ad2e08-e89c-46a5-822c-343822eaec07
> Profile URL:        https://teleport.example.com:443
  Logged in as:       joeportela
  Cluster:            admin
  Roles:              access, eng
  Logins:             joeportela, ec2-user
  Kubernetes:         enabled
  Valid until:        2022-04-06 20:20:01 -0400 EDT [valid for 8h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

> tsh db ls --debug --proxy=teleport.example.com:443 --identity=githubactions.txt --login=githubactions --cluster=dev
DEBU [TSH]       Extracted username "githubactions" from the identity file githubactions.txt. tsh/tsh.go:1918
DEBU [TSH]       Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:2110
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport.example.com:443 client/api.go:3074
DEBU             Attempting GET teleport.example.com:443/webapi/ping webclient/webclient.go:105
INFO [CLIENT]    Connecting to proxy=teleport.example.com:3023 login="githubactions" client/api.go:2322
DEBU             No valid environment variables found. client/proxy.go:116
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:268
INFO [CLIENT]    Successful auth with proxy teleport.example.com:3023. client/api.go:2327
DEBU [CLIENT]    Found clusters: [{"name":"admin","lastconnected":"2022-04-06T16:20:10.657186454Z","status":"online"},{"name":"dev","lastconnected":"2022-04-06T16:20:04.476102699Z","status":"online"}] client/client.go:127
DEBU [CLIENT]    Client  is connecting to auth server on cluster "dev". client/client.go:969
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/joe/.tsh/keys/teleport.example.com/joeportela-x509.pem" valid until "2022-04-07 00:20:01 +0000 UTC". client/keystore.go:307
DEBU [KEYSTORE]  Reading certificates from path "/Users/joe/.tsh/keys/teleport.example.com/joeportela-ssh/admin-cert.pub". client/keystore.go:330
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/joe/.tsh/keys/teleport.example.com/joeportela-x509.pem" valid until "2022-04-07 00:20:01 +0000 UTC". client/keystore.go:307
Name        Description                 Labels                                                                 Connect
----------- --------------------------- ---------------------------------------------------------------------- -------
dev-db-main Aurora cluster in us-east-2 account-id=<account>,endpoint-type=primary,engine-version=12.8,e...
```

**Comment by r0mant** [comment]
@timothyb89 This will be addressed with the tbot changes we discussed last week, right?

**Comment by timothyb89** [comment]
At least partially, yes. I've tested it with database support so far but will need to verify / follow up with app support.

**Comment by armandobelardo** [comment]
Thank you so much for this @timothyb89 and @r0mant! How can we confirm the version of Teleport the fix will be on?

**Comment by timothyb89** [comment]
We've released improvements in Teleport v9.3 but I'm actually going to reopen this as it's only a partial fix.

The main improvement is that `tsh -i <identity file> proxy db` (without `--tunnel`) and a few `tsh -i <identity file> db` commands, like `db ls`, now work without any additional login steps. A few commands like `tsh db connect` (and `tsh proxy db --tunnel`) require additional certificate files on disk beyond just the identity file to work in practice; we added an internal interface to pass these into tsh for Machine ID use but it's not something I'd necessarily recommend others make use of.

We improved some internal behavior to close the gap for app support but still don't initiate app sessions properly, so it remains broken for now. I'm planning to circle back on this alongside app support in Machine ID, hopefully sometime in the 10.x timeframe.

In any case, if there's specific additional workflows you'd like to see supported please let us know!

**Comment by zmb3** [comment]
@timothyb89 any outstanding work left to do here?

**Comment by cwegener** [comment]
> I'm planning to circle back on this alongside app support in Machine ID, hopefully sometime in the 10.x timeframe.

Is this resolved now?

**Comment by timothyb89** [comment]
We added app support to Machine ID in https://github.com/gravitational/teleport/pull/14551, so I'd expect core use cases to work, along with `tbot proxy <app/db> --tunnel ...`. We have guides for [applications](https://goteleport.com/docs/machine-id/guides/applications/) and [databases](https://goteleport.com/docs/machine-id/guides/databases/) on the public docs site with examples.

If you do try to use identity files with `tsh app` and `tsh db`, I would still expect certain subcommands to behave strangely. We had to add a number of workarounds where `tsh` expects to have a fully-formed `~/.tsh` to use and while core use cases mostly work, certain things still don't. The core functions should all work alright (i.e. list, proxy, tunneled proxy) after some fiddling to get the flags correct.

I think we can close this now - if you find use cases that still don't work, please let us know!

**Comment by cwegener** [comment]
Thanks!

> We have guides for [applications](https://goteleport.com/docs/machine-id/guides/applications/) and [databases](https://goteleport.com/docs/machine-id/guides/databases/) on the public docs site with examples

I found my answer in this discussion [1] . I needed the `destinations:` field in the tbot config. It seems that this fact is undocumented.

[1] https://github.com/gravitational/teleport/discussions/20069
