### ISSUE TITLE
docs: clarify where to run commands in MySQL guide

### ISSUE THREAD

**Issue by imasonaz** [gravitational/teleport#11788]
## Details

Re: `/docs/pages/database-access/guides/mysql-self-hosted.mdx`

Most of the commands and configurations given in this page are ambiguous to where these commands are being executed - the information jumps between the SQL server and the Teleport server without much explanation and is somewhat user hostile for someone just getting started trying to deploy Teleport.

### Category

- Improve Existing

**Comment by ptgott** [comment]
@imasonaz Thanks for bearing with us as we work through the docs ticket backlog! I know there have been some substantial edits to this guide since you first opened this issue. I just want to check in to see if these edits add any clarity in terms of where to run different commands. Thanks!

**Comment by ptgott** [comment]
Closing as completed. If there's more work to be done on this, please feel free to reopen the issue or create another one, adding detail to the issue about specific parts of the page that are unclear. Thanks!
