### ISSUE TITLE
tctl tokens add: improve help message

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#11798]
It's not clear from the `tctl tokens add --help` message that you can specify more than one type at a time. The help message very much suggests it is a single value.

```
usage: tctl tokens add --type=TYPE [<flags>]

--type         Type of token to add
```

The `--type` flag can be a comma-separated list of system roles. We should make that more obvious.

**Comment by sklirg** [comment]
Thank you for this. When I stumbled upon this (and therefore [asked about it in the Community Slack](https://goteleport.slack.com/archives/CEZH6UL64/p1649339298280909)), I also tried to issue the `--type` flag multiple times. Is that something that should be supported as well?

Example:

```
$ tctl tokens add --type db --type node
ERROR: flag 'type' cannot be repeated
```

**Comment by webvictim** [comment]
Personally I don't believe multiple flags _should_ be supported (all our docs examples use the `--type db,app` format) but we should absolutely fix the example text.
