### ISSUE TITLE
TCTL token removal

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#11819]
### Description

**What happened**:
When using `tctl rm token/<token> you will get an error of:
ERROR: deleting resources of type "token" is not supported

**What you expected to happen**:
Token to be removed

This issue arises when someone does a `tctl rm --help` they see an option for removing tokens this way:
<resource type>  Type of a resource [for example: connector,user,cluster,token]

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a token
2. Issue `tctl rm token/<token>`

### Server Details
- Teleport version (run `teleport version`): Teleport Enterprise v9.0.2 git:v9.0.2-0-g354b8c037 go1.17.7
- Server OS (e.g. from `/etc/os-release`): Ubuntu 18.04.6 LTS
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS EC2
- Additional details:

### Client Details
- Tsh version (`tsh version`): Teleport v9.0.2 git:v9.0.2-0-g354b8c037 go1.17.7
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by enraiha0307** [comment]
Hi, can I work on this issue?
