### ISSUE TITLE
Unable to use `tsh login` on cluster started with config-less `teleport start`.

### ISSUE THREAD

**Issue by hatched** [gravitational/teleport#11812]
### Description
After starting a default cluster using `teleport start` with no additional flags or config options and adding some users. Trying to connect to it using `tsh login` emits a connection refused error and fails.

**What happened**:
`dial tcp [::1]:3023: connect: connection refused`

**What you expected to happen**:
tsh to login to the cluster

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. `sudo teleport start`
2. create a user or two
3. `tsh login --proxy=localhost:3080 --debug --insecure`

### Server Details
- Teleport version (run `teleport version`): 9+
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Macos 12.3.1

### Client Details
- Tsh version (`tsh version`): 9+
- Computer OS (e.g. Linux, macOS, Windows): Macos 12.3.1
- Installed via (e.g. apt, yum, brew, website download): freshly compiled

**Comment by webvictim** [comment]
It looks like in the default configuration, `teleport start` doesn't add a listener on port 3023 for the SSH proxy, but also doesn't set `tls_routing_enabled: true` in the ping output so `tsh` has no clue where to send the traffic.

Another reason to discourage the use of `teleport start` as per https://github.com/gravitational/teleport/issues/11457

**Comment by stevenGravy** [comment]
Retested and confirmed working now.  A `3023` listener is added.
