### ISSUE TITLE
Allow for tsh login to accept a provided SAML assertion without using a browser

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#11824]
### What
Feature request for the `tsh` tool to allow a user to provide a SAML assertion without requiring the use of a browser or referencing the `http://127.0.0.1` link to complete SSO login.

###Why
It is possible for the end user to already have tooling that can provide a validated SAML assertion without requiring browser-based SSO login.  Waiting through the browser login stage is the slowest part of the `tsh login` process and being able to skip this step can help significantly speed up the process

**Comment by webvictim** [comment]
I feel like this might potentially allow replay attacks in some shape or form...

**Comment by klizhentas** [comment]
It is unlikely we are going to implement this feature to avoid additional complexity and possible replay attacks. What is the use-case that folks are looking for?
