### ISSUE TITLE
Prompt for Teleport credentials when using an OpenSSH client

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1183]
### Problem

When using an OpenSSH client with Teleport, if your certificate has expired you get a message like the following when attempting to login to a server:

```
$ ssh node
Permission denied (publickey).
ssh_exchange_identification: Connection closed by remote host
```

This message does not explain why permissions was denied, nor does suggest a way to resolve the problem. The way to solve the problem is to run `tsh login` again and get new certificates.

### Proposed Solution

The simple solution is to improve the error message (if possible) to tell the user what happened.

A better user experience would be to prompt the user for their Teleport credentials and allow them to re-authenticate. We can potentially accomplish this by using tsh to form the outer SSH tunnel when using `ProxyCommand`.

**Comment by webvictim** [comment]
Could be related to https://github.com/gravitational/teleport/issues/3734

**Comment by programmerq** [comment]
This was solved by the [ALPN SNI Proxy](https://github.com/gravitational/teleport/pull/7524) that is indeed used in a ProxyCommand.

```
% tsh login --ttl 1 && sleep 62
Enter password for Teleport user jeff:

% tsh ssh mynode.teleport.example.com
Enter password for Teleport user jeff:
jeff@mynode ~ %

```
