### ISSUE TITLE
Audit some beginner/early-stage Teleport guides

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#11841]
## Details
Ensure that guides for users in the early stages of setting up Teleport are accurate and straightforward to follow. 

While we want all of our guides to have these qualities, this issue focuses on some guides that users first getting acquainted with Teleport are expected to read. 

Since these guides provide the basis for following other guides, frustration while working through them can hamper a new user's overall adoption of Teleport.

I will set up a demo environment for the Cloud, Open Source, and Enterprise editions of Teleport, and verify each page separately for each.

|Guide|PR (Cloud)|PR (self-hosted)|
|---|---|---|
|`/docs/getting-started/linux-server`|N/A|#12236|
|`/docs/installation`| #12282| #12282|
|`/setup/admin/github-sso/`|#11913|#11913||
|`/setup/admin/adding-nodes/`|#11913|#12504|
|`/setup/admin/trustedclusters/`|#10708 |#10708|
|`/setup/admin/labels/`|#12034|#12034|
|`/setup/admin/users/`|#12001|#12001|
|`/setup/admin/troubleshooting/`|#12074|#12074|
|`/setup/admin/graceful-restarts/`|N/A|#12119|
|`/setup/admin/daemon/`|#12038|#12038|
|`/setup/admin/` (add intro paragraph)|#11913|#11913|
|`/docs/server-access/guides/openssh/`|#12183|#12183|

### Category
- Improve Existing

**Comment by stevenGravy** [comment]
would include:

docs/setup/admin/ - no opening info on what these guides are for.  The setup section lacks a intro which nearly all others have
/docs/server-access/guides/openssh/ - frequent usage

**Comment by ptgott** [comment]
This is done
