### ISSUE TITLE
tsh login - login does not accept arguments

### ISSUE THREAD

**Issue by knisbet** [gravitational/teleport#1184]
Hi,

I found a minor issue, where the documentation doesn't appear to match the behavior of the tsh command.

In docs/2.0/user-manual.md it suggest that tsh login can be used as "tsh login --proxy=work.example.com".

However, this results in the following error:
```
tsh login --proxy=abc.123
login does not expect arguments
```

Moving the argument to the root command does appear to work as intended:
```
tsh --proxy=abc.123 login
```

It appears that Issue #667 redefined tsh logout to logout of all proxy servers, so PR #734 added functionality to error if any arguments are passed to the command. However, I suspect based on the issue, that it may have been unintentionally added to the login command as well.

The line in question:
https://github.com/gravitational/teleport/blob/ca1f8253e53185f0be498ec26640d90079370197/tool/tsh/tsh.go#L267

I can submit a PR if you wish, but for a 1 line change it's likely faster if a maintainer makes the change (assuming that this was unintended behavior).

**Comment by kontsevoy** [comment]
@knisbet thanks! this has already been fixed in master.
