### ISSUE TITLE
Invalid example for ssh nodes

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#11863]
## Details
This example shows connecting to a different port then `3022` for a ssh node.  Teleport Cloud only supports reverse tunnel for Teleport agent daemons.

https://goteleport.com/docs/server-access/guides/openssh/?scope=cloud

![image](https://user-images.githubusercontent.com/60704961/162581740-213d7289-c59b-4257-8677-d3a0d68af68b.png)

### Category

- Improve Existing

**Comment by zmb3** [comment]
Not sure I understand the issue here.
