### ISSUE TITLE
Ability to add OpenSSH servers as records in Teleport backend with labels

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#11876]
### What
Some customers would love to leverage Teleport for their infrastructure but still want to stick with OpenSSH. They either can't or don't want to run an agent on their servers (unsupported OSes like Solaris/AIX come to mind) so they'd like an API or client which is able to register instances with labels to a Teleport cluster so they show up in the web UI and can be connected to over SSH, similar to the way SSH servers currently appear.

### How
Add an API which allows you to create/replace/update/delete servers in the backend.

### Why
Big Enterprise customers often cannot or will not deploy the Teleport agent, but have to support non-technical teams who require access to resources. They would also like to leverage Teleport's RBAC functionality to gate access to these machines, and use recording proxy mode to capture session logs.

### Workaround
Build your own web UI in front of Teleport and embed deeplinks to sessions?

**Comment by raphaelbkt** [comment]
Hi,

That's exactly what I was missing following this guide : https://goteleport.com/docs/server-access/guides/openssh/
Some platforms have ssh available but can't get the teleport binary installed, like Cisco switches for example.

So imagine that we can deploy the certificate and private key on the SSH config of the switches, we havo no way to register them in the cluster to make them available ?

If I understand well we can connect to OpenSSH only on nodes where the teleport binary is installed ?

**Comment by raphaelbkt** [comment]
Hi,
Thanks for clarification.

I am trying to connect from GUI providing server details with : user@server:22 (Ssh config is made).
When I try to connect I have a message : "access denied to server on cluster teleport.xxx.xxxxx".
I am logged as teleport-admin with full rights, how do you tell teleport the user is authorized to login into the remote server ?
Thanks
Raphaël

**Comment by webvictim** [comment]
@raphaelbkt Add the username to the `logins` section of a Teleport role - e.g.:

```
spec:
  allow:
    logins:
    - ec2-user
    - ubuntu
    - root
```

**Comment by raphaelbkt** [comment]
Yes the user is present in the rôle.
I am investigation the issue. Anyway thanks for your answers.

**Comment by zmb3** [comment]
@capnspacehook @r0mant can we close this one now?
