### ISSUE TITLE
Unable to merge backport due to pull_request_review failing

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#11887]
### Description

**What happened**:
I created a backport PR using https://github.com/sqren/backport , but my PR https://github.com/gravitational/teleport/pull/11815 isn't able to be merged since the bot didn't assigned reviewers. See 

```
Run cd .github/workflows/robot && go run main.go -workflow=check -token="***" -reviewers=""
```

**What you expected to happen**:
I'm able to automate my backports and it selects the correct reviewers.

**Comment by benarent** [comment]
@russjones it looks like https://github.com/gravitational/teleport/commit/94802175fa64cdd4c7046098c1f187b47cf35145 needs to be backported to `branch/v9` etc

**Comment by zmb3** [comment]
@benarent is this still an issue?

The bot always runs from master, so it's not due to a missing backport.
