### ISSUE TITLE
Automatically label Helm PRs

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#11880]
It'd be cool if the review bot could detect any changes to the `examples/chart` directory and automatically add a Helm label to them. That way interested parties (i.e. me) can more easily keep track of new/existing Helm PRs.

**Comment by zmb3** [comment]
This is actually already implemented: 
https://github.com/gravitational/teleport/blob/fcd1916e9dc6e65f41446319f4af42b179866873/.github/workflows/robot/internal/bot/label.go#L101

Maybe the label workflow isn't always running?

**Comment by webvictim** [comment]
You're right, I think I'm just blind.

![image](https://user-images.githubusercontent.com/897821/162829264-220caf92-fd60-4218-807f-63fe5592e1db.png)

**Comment by webvictim** [comment]
(I'll reopen if I find a case where this doesn't happen)
