### ISSUE TITLE
`tsh db config` should tell the user to use `tsh proxy db` when multiplexing is on

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#11907]
### Description

**What happened**:

When attempting to configure a GUI database IDE, all connections would fail when configured with the `tsh db config` output information for a mysql database.

It turns out that the end user was using a teleport cluster in multiplexing mode and didn't realize that meant that `tsh proxy db` needed to be used instead.

(Other database types may also be affected, but I only tested with mysql after receiving a report about mysql specifically)

**What you expected to happen**:

The `tsh db config` output should instead advise the user about the need to proxy instead of outputting incorrect connection information.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Set up a mysql database on a teleport cluster with multiplexing enabled.
2. connect via `tsh db connect` and observe it works.
3. attempt to connect with a db gui using the `tsh db config` connection information and observe a timeout.

### Server Details
- Teleport version (run `teleport version`): 9.0.3
- Server OS (e.g. from `/etc/os-release`): n/a
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): eks
- Additional details:

### Client Details
- Tsh version (`tsh version`): 9.0.3
- Computer OS (e.g. Linux, macOS, Windows): mac

gz#4764

**Comment by greedy52** [comment]
Fixed in https://github.com/gravitational/teleport/pull/14971
