### ISSUE TITLE
Why did past release files change?

### ISSUE THREAD

**Issue by ekristen** [gravitational/teleport#1190]
I just fetched the v2.2.0 with a script I wrote to verify it was ok with a hash I had stored and now the file for linux is different. 

Did you guys change or re-upload v2.2.0 binaries and if so why? 

If not, the linux tar.gz file sha256 sums have changed.

**Comment by russjones** [comment]
@ekristen Good catch! Yes, I did re-upload the v2.2.0 binary.

It was re-uploaded because I incorrectly build the release binary and `teleport version` was reporting an incorrect value.

**Comment by ekristen** [comment]
Awesome. Sorry if I came off strong. It threw me for a while and my tooling today. Glad it wasn't malicious.

**Comment by russjones** [comment]
No problem, we appreciate that you checked!
