### ISSUE TITLE
How to edit users and roles?

### ISSUE THREAD

**Issue by wjdavis5** [gravitational/teleport#1191]
I'm not seeing options in TCTL to edit users or the roles assigned to them. What is the best way to do this?

**Comment by kontsevoy** [comment]
@wjdavis5 Roles are part of the RBAC and that's the enterprise-only feature, the OSS edition of `tctl` only shows you the faux role-per-user model which is exposed to the open source teleport. as awlays, we're happy to chat about a commercial engagement, so if you believe you have a case for SSH RBAC, ping us at info@gravitational.com

Thanks!
