### ISSUE TITLE
tctl command does not match documentation - 'unknown long command'

### ISSUE THREAD

**Issue by mechastorm** [gravitational/teleport#1192]
This is for Teleport v2.2.4-0-ge43f052b

In the documetation for using [Teleport with OpenSSH](http://gravitational.com/teleport/docs/2.0/admin-guide/#using-teleport-with-openssh) it mentions to run the command `tctl auth --type=host export > cluster_node_keys`

When I did that I instead get an error message `unknown long flag '--type'`

What should be the correct command for this?

**Comment by kontsevoy** [comment]
@mechastorm ouch, it's a typo in the documentation. Try:

```
$ tctl auth export --type=host
```

**Comment by kontsevoy** [comment]
fixed in 2.3
