### ISSUE TITLE
Deprecate the "EC2 Tags as Teleport Node Labels" guide once we add first-class support

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#11929]
## Details
Context here: https://github.com/gravitational/teleport/pull/10920#discussion_r848899825

Creating this issue as a reminder to remove the "EC2 Tags as Teleport Node Labels" guide when applicable.

### Category
- Remove Outdated

**Comment by zmb3** [comment]
@ptgott @atburke I think we can take care of this one now that we support EC2 node labels.

**Comment by ptgott** [comment]
@zmb3 @atburke What functionality have we added since #12593? In the `ec2-tags.mdx` guide after that PR's edits (and as it is now), the only step is to enable tags in EC2 instance metadata. Is this step no longer needed?

**Comment by atburke** [comment]
Nothing substantial has been added since #12593. Enabling tags in instance metadata is still required.
