### ISSUE TITLE
Teleport Proxy Protocol

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1193]
### Problem

Teleport allows you to run multiple Auth Servers in a highly available (HA) configuration in two ways: either you list multiple Auth Servers in `teleport.yaml` or put your Auth Servers behind a load balancer (LB) and list the LB as the location of the Auth Server in `teleport.yaml`.

However, at the moment the second approach does not work because when the Auth Server registers a nodes heartbeat, it registers the address of the remote node using the source address from the connection it receives which originate from the LB:

[lib/auth/apiserver.go#L247-L249](https://github.com/gravitational/teleport/blob/5459c2b1e34a3f9bf82487234080bef3ceaf940a/lib/auth/apiserver.go#L247-L249)

This address is incorrect and all future attempts to login to the node become attempts to login to the LB which will timeout and fail.

This same problem also presents itself when recording the IP address of a client when putting proxy servers behind an LB. We record the address of the LB instead of the address of the client.

### Proposed Solution

Communication with the Auth Server occurs over a HTTP-in-SSH tunnel so the LB can't simply add a `X-Forwarded-For` header to the request because the LB isn't able to unravel the SSH connection. Instead we should add support for [Proxy Protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) to Teleport which works at the TCP layer which would allow us to forward the source address to the Teleport Auth Server so the nodes address gets correctly registered.

We also need to support Proxy Protocol for the Teleport proxy.

**Comment by benarent** [comment]
Followed up with @russjones and we can mark this as closed.
