### ISSUE TITLE
helm: teleport-kube-agent does not set imagePullSecrets when in statefulset mode

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#11935]
### What
We should create parity between statefulset and deployment by adding the following section from the deployment into the statefulset as well:
https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/templates/deployment.yaml#L70-L73

```
agent/templates/deployment.yaml)
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
{{- end }}
```

gz#4480

**Comment by webvictim** [comment]
Sorry, this one is my bad as I forgot to duplicate the fix between the two.
