### ISSUE TITLE
add reference for all teleport yaml schemas

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#11930]
## Details

Currently, there are examples for teleport users and roles at this location: https://goteleport.com/docs/setup/reference/resources/

I tried to find an example of the token yaml, or schema information but could not find any.

I'd expect something that relays the structure, required fields, fields with default values, and the data types that each field can take.

There is a protobuf schema for every teleport object in https://github.com/gravitational/teleport/blob/7bd3692ca7609a750bb29e375aec247867acdc53/api/types/types.pb.go

I believe there are tools to generate docs for these object types. The doc would need to work for at least yaml. Since tctl also supports json, it might be a good idea to have one of those tabbed pages in the doc that can flip between the yaml and json in the example.

For example, the token schema reference would point out that it needs `kind: token`, and that `spec.roles` is a list of strings whose values must be names of system roles (auth, proxy, node, etc...), and that `metadata.name` is required by the API server, and that `metadata.id` will be auto assigned, etc...

### Category
- Improve Existing

gz#4774

**Comment by zmb3** [comment]
See also #11079

**Comment by ptgott** [comment]
Closing so we can track this here: https://github.com/gravitational/teleport/issues/16948
