### ISSUE TITLE
Auth Server Health Check

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1194]
### Problem

If you put multiple Auth Servers behind a load balancer (LB) the only health check we can perform is a TCP health check because the Auth Server speaks SSH-in-HTTP. TCP health checks usually consist of simply creating a TCP connection to the specified address. If the request times out the host is down otherwise it is up.

If you enable this check on a Auth Server, it floods the logs with the following error.

```
ERRO[0667] EOF                                           file=sshutils/server.go:425 func=sshutils.(*connectionWrapper).Read
```

**Comment by flyinprogrammer** [comment]
I built a little project to try and help with this: https://github.com/flyinprogrammer/nss

but it would be great if the SSH agent and the Auth servers had health checks.
