### ISSUE TITLE
`tsh version` should report proxy version

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#11986]
### What

Similar to how `kubectl version` and `helm version` report version of the Kubernetes server from the current profile, it would be very useful to have `tsh version` and `tctl version` report version of the Teleport proxy they're talking to.

Proxy server version is returned as a part of the "ping" endpoint so tsh version should just call it when you're logged in.

**Comment by webvictim** [comment]
Auth server version would also be useful (maybe even more useful) with this.
