### ISSUE TITLE
Maximum allowed writes exceeded in Firestore Commit

### ISSUE THREAD

**Issue by silamon** [gravitational/teleport#12007]
### Description

**What happened**:
Teleport tries to purge more than 500 expired documents and reaches a limit of Firestore documented here: 
https://firebase.google.com/docs/firestore/quotas#writes_and_transactions

```Task purgeExpiredDocuments has returned with error. error:[                                                                       │
│ ERROR REPORT:                                                                                                                                                           │
│ Original Error: *status.Error rpc error: code = InvalidArgument desc = maximum 500 writes allowed per request                                                           │
│ Stack Trace:                                                                                                                                                            │
│     /go/src/github.com/gravitational/teleport/lib/backend/firestore/firestorebk.go:716 github.com/gravitational/teleport/lib/backend/firestore.ConvertGRPCError         │
│     /go/src/github.com/gravitational/teleport/lib/backend/firestore/firestorebk.go:694 github.com/gravitational/teleport/lib/backend/firestore.(*Backend).purgeExpiredD │
│     /go/src/github.com/gravitational/teleport/lib/backend/firestore/firestorebk.go:583 github.com/gravitational/teleport/lib/backend/firestore.RetryingAsyncFunctionRun │
│     /opt/go/src/runtime/asm_amd64.s:1371 runtime.goexit                                                                                                                 │
│ User Message: rpc error: code = InvalidArgument desc = maximum 500 writes allowed per request] firestore/firestorebk.go:585
```

Related code: https://github.com/gravitational/teleport/blob/master/lib/backend/firestore/firestorebk.go#L709-L721

**What you expected to happen**:
A commit should not contain more than 500 documents. If more than 500 documents are ready to be purged, multiple commits should be made. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Setup Teleport with Firestore backend
2. Have more than 500 expired audit events 
3. Let Teleport try to purge them

### Server Details
- Teleport version (run `teleport version`): 7.3.17
- Server OS (e.g. from `/etc/os-release`): 
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP
- Additional details:

**Comment by silamon** [comment]
@rosstimothy, thank you for taking the time to fix this issue. Very much appreciated! Would it be possible to have this backported to v7 or v8?

**Comment by rosstimothy** [comment]
> @rosstimothy, thank you for taking the time to fix this issue. Very much appreciated! Would it be possible to have this backported to v7 or v8?

Backport PRs are now up for v7, v8, v9. Sorry I was a bit busy and didn't get to this yesterday.
