### ISSUE TITLE
Support for XRDP for Linux machines

### ISSUE THREAD

**Issue by jeffr1975** [gravitational/teleport#12023]
### What
Support for XRDP for Linux machines

### How
Remove the AD/LDAP requirement for RDP configuration

### Why
Teleport front end it the perfect solution other than I don't believe it can support XRDP for Linux machines

### Workaround
I don't think there is one, but if there is I would love to hear about it!

**Comment by sbourdette** [comment]
I agree with the request.

Put optional AD/LDAP requirement.

I would like to access to virtualbox RDP guest through the virtualbox host.

We should be able to configure a list of host + port + credentials to connect to RDP.

**Comment by zmb3** [comment]
Closing this in favor of #13179.

**Comment by acfranken** [comment]
Yes please.
