### ISSUE TITLE
Possible Error in Documentation

### ISSUE THREAD

**Issue by typkrft** [gravitational/teleport#12024]
## Details
Describe the documentation improvements you wish to see.
On https://goteleport.com/docs/setup/guides/docker/ it tells you to run the following command to generate the teleport.yml. 

Current Command
```SHELL
docker run --hostname localhost --rm \
  --entrypoint=/bin/sh \
  -v ~/teleport/config:/etc/teleport \
  quay.io/gravitational/teleport:9 bash -c "teleport configure > /etc/teleport/teleport.yaml"
```

Previous Command
```SHELL
sudo docker run --hostname localhost --rm \
--entrypoint=/bin/sh \
  -v ~/teleport/config:/etc/teleport \
quay.io/gravitational/teleport:8.0.7 -c "teleport configure > /etc/teleport/teleport.yaml"
```

This has changed from the last command adding `bash -c` instead of just `-c`. For me `bash -c` does not work, while `-c` does regardless of version.
Running the current command results in `/bin/sh: 0: Can't open bash`

Maybe this is some issue on my end, but I thought I'd mention it.

**Comment by stevenGravy** [comment]
Thanks @typkrft should be addressed now

**Comment by typkrft** [comment]
Just read through the documentation, looks great! All the best!
