### ISSUE TITLE
On-demand reverse tunnel

### ISSUE THREAD

**Issue by awoz** [gravitational/teleport#1203]
Rather than persistent reverse tunnel, an option for on-demand reverse tunnel would improve session cost and management for large scale deployments. Use case is that remote cluster nodes periodically check the bastion server for a connection request. Only at that time does the cluster node open a reverse ssh tunnel.

It is unclear if SSH reverse tunnel on-demand is currently  available in teleport.

**Comment by kontsevoy** [comment]
@awoz this is unclear what you're proposing and what the benefits would be. The part I am curious about is "improve session cost and management". What cost? A cost of a single connection? All sessions to a remote cluster get proxied through a single connection, so even if you have hundreds of data centers, you can still use a Raspberry Pi as your Teleport proxy.

But if you were referring to the inconvenience of updating configuration on both ends, **we 120% agree**. The upcoming 2.3 release simplifies cluster connection _dramatically_.

Let me know! Thanks.

**Comment by kontsevoy** [comment]
@awoz dynamically creating reverse tunnels has been released in 2.3

**Comment by georgehristov** [comment]
How is this feature implemented exactly? Could not find in the docs.

**Comment by klizhentas** [comment]
https://gravitational.com/teleport/docs/2.3/admin-guide/#trusted-clusters see the section with "Trusted cluster resource"

**Comment by georgehristov** [comment]
Thanks, I read this and checkd the code but I cannot figure out how the "on demand" option is impemented

**Comment by klizhentas** [comment]
tctl create -f <trustedcluster.yaml>
will create a cluster on demand

**Comment by georgehristov** [comment]
Thanks. Will you add this to the docs with an example?

**Comment by klizhentas** [comment]
I think it's already referenced `$ tctl create cluster.yaml`

**Comment by georgehristov** [comment]
Correct, I was looking in the wrong version of the manual.
But in any case in present implementation I believe the tunnel is open permanently or on demand of the "east" cluster admin (referring to the example in the docs)
Original question in this issue was for creating the tunnel on demand of the "main"cluster admin.
Is this possible?

**Comment by klizhentas** [comment]
ok, I understand now - you mean mantain the connection on demand? I'm not 100% sure I understand what behavior would you want, can you elaborate what do you mean by "on demand" then?

**Comment by georgehristov** [comment]
Amazingly what I need in my case is pretty well described in the initial post.
The "main" and "east" clusters are set up but the actual tunnel is established only when user from "main" wants to do administration on a machine in the "east" cluster. Of course the only way to achieve that considering "east" is behind a firewall is that "east" cluster nodes periodically check the bastion server for a connection request.
To give a background on that: in my case the "main" cluster is ashore and "east" is located on board a sea going vessel where connection between them is a limited bandwidth satellite link.

**Comment by klizhentas** [comment]
ok, thanks for taking your time to explain this. Let me reopen this issue, we will discuss internally and get back to you

**Comment by georgehristov** [comment]
Thanks for considering my request.

**Comment by awoz** [comment]
Gentlemen, I've been away on other projects and was delighted to more interest in this on-demand tunnel feature. The use-case for "session cost" is related to "data cost" for remote devices that connect to bastion server via "cell modem". Because our customers are sensitive with their operating "data plan cost", we want to minize impact when using reverse ssh for remote diagnostic/service sessions.

**Comment by awoz** [comment]
We also plan to use the bastion server as an HTTP proxy for browser sessions (over sh tunnel) from AWS bastion to remote device. Thanks so much for you expertise in this area.

Cheers

**Comment by kontsevoy** [comment]
@awoz the resource-based approach is what we recommend. A tunnel either exists or not, we do not believe in "disabled" or "turned off" tunnels, because a tunnel represents trust. In the latest Teleport you can now create/destroy tunnels on the fly.

I am going to close this now, but will reopen if something changes.
