### ISSUE TITLE
dial tcp failed

### ISSUE THREAD

**Issue by galenzhao** [gravitational/teleport#1204]
when add node to auth server 10.8.0.4

it shows an error about other ip connection refused,

`
[root@redmine build]# route -nv
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.8.0.0        0.0.0.0         255.255.255.0   U     0      0        0 peervpn0
192.168.174.0   0.0.0.0         255.255.255.0   U     0      0        0 eth0
10.4.120.0      0.0.0.0         255.255.248.0   U     0      0        0 eth1
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1003   0        0 eth1
0.0.0.0         10.4.120.2      0.0.0.0         UG    0      0        0 eth1
[root@redmine build]# teleport start --roles=node --token=024fbac0290101e869307bcef7a2b68b --auth-server=10.8.0.4:3025
bash: teleport: command not found
[root@redmine build]# ./teleport start --roles=node --token=024fbac0290101e869307bcef7a2b68b --auth-server=10.8.0.4:3025
WARN[0000] syslog not available. reverting to stderr     file=utils/cli.go:52 func=utils.InitLoggerCLI
dial tcp 10.4.120.248:3025: getsockopt: connection refused
[root@redmine build]# iptables --list -nv

`

**Comment by kontsevoy** [comment]
@galenzhao it means the node 10.4.120.248 is not accessible on TCP port 3025.

**Comment by galenzhao** [comment]
@kontsevoy 

Hi, my auth node is 10.8.0.4, the node I want to added is 10.8.0.6,

I'm confused why it using this ip 10.4.120.248,

**Comment by kontsevoy** [comment]
@galenzhao I would try:

1. wipe out `/var/lib/teleport` on the node. 
2. on the auth server (since it has so many IPs) set `--advertize-ip=10.8.0.4` flag.
