### ISSUE TITLE
Kubernetes clusters auto-discovery

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#12048]
### What

Similar to [AWS databases auto-discovery](https://github.com/gravitational/teleport/blob/master/rfd/0038-database-access-aws-discovery.md), Teleport should give users ability to automatically discover and register EKS, GKE and AKS clusters matching a certain criteria e.g. labels/tags.

**Comment by russjones** [comment]
Users can use Teleport Discover to automatically discover and enroll Kubernetes clusters.

| Phase        | PR       | Date      |
|--------------|----------|-----------|
| Phase 0: RFD |          | Q3 2022   |
| Phase 1: AWS |          | Q3 2022   |
| Phase 2: AWS |          | Q4 2022   |
