### ISSUE TITLE
Ability to list roles which can be requested by user using CLI.

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#12053]
### What
User can request roles using `access request` workflow via both CLI and UI. In UI, a dropdown shows all the roles, which can be requested by the user, but in CLI, there is no way to see which all roles can be requested by specific user.

`tsh` CLI, needs role name to be given to request same with option `--request-roles`, thus having a option to list all roles which can be request would be helpful.

### How

`tsh` CLI, should have option to list all the roles which can be requested by user like `tsh request roles ls`

### Why
It will make easy for user to list all the roles and behaviour will be same as UI.

### Workaround
Not in CLI, UI does have dropdown which gives all the roles that can be requested.

**Comment by zmb3** [comment]
Closing as duplicate of #7693
