### ISSUE TITLE
tctl index out of range panic

### ISSUE THREAD

**Issue by mdaniel** [gravitational/teleport#12124]
### Description

**What happened**:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/gravitational/teleport/tool/tctl/common.Run({0xc000b7be80, 0xf, 0x7ff84b0dde70?})
        /tmp/teleport-20220407-3274045-1ke6j8u/teleport-9.0.4/tool/tctl/common/tctl.go:169 +0xf9b
main.main()
        /tmp/teleport-20220407-3274045-1ke6j8u/teleport-9.0.4/tool/tctl/main.go:41 +0x30a
```

**What you expected to happen**:

Not panicking

After applying the following patch, it at least emits a much more reasonable, although still unhelpful, error
> [CLIENT]       Cannot connect to the auth server: failed direct dial to auth server: must provide Dialer or Addrs in config
>        must provide Dialer or Addrs in config.
> Is the auth server running on "UNKNOWN"?

```diff
diff --git a/tool/tctl/common/tctl.go b/tool/tctl/common/tctl.go
index b75b6efa3..554a04bb4 100644
--- a/tool/tctl/common/tctl.go
+++ b/tool/tctl/common/tctl.go
@@ -164,9 +164,13 @@ func Run(commands []CLICommand) {
 
        client, err := authclient.Connect(ctx, clientConfig)
        if err != nil {
+               addr := "UNKNOWN"
+               if len(cfg.AuthServers) > 0 {
+                       addr = cfg.AuthServers[0].Addr
+               }
                utils.Consolef(os.Stderr, log.WithField(trace.Component, teleport.ComponentClient), teleport.ComponentClient,
                        "Cannot connect to the auth server: %v.\nIs the auth server running on %q?",
-                       err, cfg.AuthServers[0].Addr)
+                       err, addr)
                os.Exit(1)
        }
 
```

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. `tctl auth sign --auth-server example.teleport.sh:3025 --out slack_file --format=file --app-name slack-plugin`
2. :bomb:

### Server Details
- Teleport version (run `teleport version`): Teleport v9.0.4 git: go1.18
- Server OS (e.g. from `/etc/os-release`): Ubuntu 21.10
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): N/A
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by zmb3** [comment]
This was fixed by https://github.com/gravitational/teleport/pull/16130
