### ISSUE TITLE
Long Delay with Application Access before Application is Open

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#12121]
### Description

**What happened**: When using Teleport application access to access all applications (mostly Grafana and Kibana), after a few redirects there is a long (1-2 minute delay) before the Teleport application is opened and working successfully.

The 1-2 minute hang seems to happen during the phase where the URL in the Web UI shows `https://<application-public-addr>/x-teleport-auth?state=<string>`.  There is no logging taking place on the Teleport application agent during this time.  Below is the log messages taken from the proxy during the delay that seemed relevant to the app service:
~~~
2022-04-20T13:58:52Z INFO [AUDIT]     app.session.start addr.remote:<redacted>:39132 app_name:<redacted>.com app_public_addr:<redacted>.com app_uri:<redacted>.com cluster_name:<redacted>.com code:T2007I ei:0 event:app.session.start namespace:default public_addr:<redacted>.com server_id:<redacted> sid:<redacted> time:2022-04-20T13:58:52.414Z uid:937ade42-e248-4dc7-ae63-8f0b7c3b4f7c user:<redacted> events/emitter.go:325
2022-04-20T13:58:52Z INFO [AUDIT]     app.session.start addr.remote:<redacted>:39132 app_name:<redacted>.com app_public_addr:<redacted>.com app_uri:<redacted>.com cluster_name:<redacted> code:T2007I ei:0 event:app.session.start namespace:default public_addr:<redacted>.com server_id:<redacted> sid:<redacted> time:2022-04-20T13:58:52.414Z uid:937ade42-e248-4dc7-ae63-8f0b7c3b4f7c user:<redacted> events/emitter.go:325
<logging removed>
2022-04-20T13:59:54Z ERRO [APP:WEB]   Error forwarding to /, err: context canceled forward/fwd.go:181
~~~

The Teleport cluster is a kubernetes hosted cluster deployed via Helm running 3 replicas.  The Agent is a teleport-kube-agent pod deployed via helm with a single replica.  The Teleport cluster is running 9.0.3 and the Teleport agent is running 8.1.3.  Dynamic application discovery is being used to configure the applications.  The Teleport agent runs in the same Kuberentes cluster as the application host pod.

Kube Agent config for app service
~~~
apiVersion: v1
data:
  teleport.yaml: |
    teleport:
      auth_token: "/etc/teleport-secrets/auth-token"
      auth_servers: ["<redacted>:443"]
      log:
        severity: INFO
        output: stderr
        format:
          output: text
          extra_fields: ["timestamp","level","component","caller"]

    app_service:
      enabled: true
      resources:
      - labels:
          clusterName: <redacted>
          region: us-west-2
      apps:
        []
kind: ConfigMap
~~~

App config
~~~
kind: app
metadata:
  labels:
    app: grafana
    clusterName: boapus-blue
    grade: system:2
    namespace: system
    production: "true"
    region: us-east-1
    teleport.dev/origin: dynamic
  name: grafana.blue.<redacted>
spec:
  insecure_skip_verify: false
  public_addr: grafana-76cfe694.<redacted>
  uri: https://grafana.blue.<redacted>.com/
version: v3
~~~

**Comment by pschisa** [comment]
Investigating if they are possibly affected by https://github.com/gravitational/teleport/issues/11285 and having more applications across their agents than expected

**Comment by pschisa** [comment]
Further info from user experience with the AWS console functionality in the same cluster incase this helps narrow down the root cause:

AWS applications behave similarly in that when we go to the assume the role from within the teleport client in the web browser there is a long period whereby the client is sitting idle, waiting for the remote end to perform some action before being redirected and logged into AWS. Note that in this case the teleport agents for AWS connectivity are situated in the same EKS cluster as the teleport cluster itself.

**Comment by pschisa** [comment]
upgraded to version 9.2.1 and still noticing a long delay (>60 seconds) when using application access.  We have also verified that the correct number of agents are present on each server and the labeling is working as expected.  This rules out either of the above two issues as being the root cause.

Any suggestions on areas to focus troubleshooting or further data to gather?

**Comment by pschisa** [comment]
Latest update:

The cluster was upgraded from 8.1.3 to 9.2.1 but not the agents.  After upgrading the agents to 9.2.1 as well performance is now significantly improved

**Comment by r0mant** [comment]
@pschisa Can we consider this resolved and close, or are there any other performance issues still?

**Comment by pschisa** [comment]
I have not heard any further issues since they have let it back in so I will go ahead and close this one out
