### ISSUE TITLE
Ability to set custom ExternalIDs w/ Teleport AWS Console access

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#12146]
### What
Customers who have access to AWS accounts that belong to their customers or other, separate parts of the org, may at times need to log into those customer/other accounts, but are currently unable to do so with Teleport because of the external ID notion that AWS uses to authorize cross-organization users. Customers would ideally run all of this through Teleport so it can be logged and audited, but right now we're currently setting the external ID ourselves (to match the username of the signed-in teleport user), so they're not able to pass or set that via another method.

### Why
Customer ask.

**Comment by r0mant** [comment]
@smallinsky @greedy52 Can you guys look into this after Teleport 10 release?
