### ISSUE TITLE
Allow for agents to run a version of teleport ahead of auth/proxy within supported +/- 1 major release

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#12163]
### What
Customers have requested the ability to run nodes ahead of the teleport auth/proxy version to make upgrades easier to manage, especially in MSP models where they have to coordinate with a number of different customers/providers for a singular upgrade otherwise.

**Comment by zmb3** [comment]
It's looking more like we'll be taking the opposite approach and start making this configuration fail fast as opposed to letting it run and then encountering random error cases.

We're looking to automatic upgrades to be the proper solution to this problem. It's unlikely we'll change the existing compatibility guidelines as it would make introducing new APIs or deprecating old APIs much more difficult.

**Comment by Aharic** [comment]
Makes sense, especially with auto-upgrades being on the horizon this year. Going to close this one in that case.
