### ISSUE TITLE
Add more context/clarity to the Application Access "Connecting Apps" page

### ISSUE THREAD

**Issue by markcupitt-methodmaker** [gravitational/teleport#12168]
## Details
It is not clear where to start the teleport app proxy, perhaps explain the difference between the main proxy and the app proxy, also how to run the approxy as a service, explain how long a token is valid for, better examples on labels, like a working example on how to restrict a specific user to one or two apps

### Category

- Improve Existing

**Comment by ptgott** [comment]
Applies to: `/docs/application-access/guides/connecting-apps/`

We should give this the structure of our other how-to guides, including a prerequisites section and numbered steps, and make sure that it is possible to follow the guide from beginning to end.
