### ISSUE TITLE
restore support for SSH reverse tunnel connection through HTTP CONNECT proxy

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#12215]
### Description

**What happened**:

After proxy support was added, all connections could be made through the proxy. #11990 was introduced to exclude all reverse tunnels from being proxied.

**What you expected to happen**:

There should be a configuration that would allow for reverse tunnel (and other ssh connections throughout teleport) to make use of an HTTP CONNECT proxy.

gz#4909

gz#4904

**Comment by r0mant** [comment]
As discussed during the sync, since this is going to be a backwards incompatible change, we will address this in Teleport 10 release and document the breaking behavior in the changelog.
