### ISSUE TITLE
Provide gui for editing existing users

### ISSUE THREAD

**Issue by PavelNiedoba** [gravitational/teleport#12225]
### Discussed in https://github.com/gravitational/teleport/discussions/11820

<div type='discussions-op-text'>

<sup>Originally posted by **PavelNiedoba** April  8, 2022</sup>
I have existing user "John" which I created using gui. "John" has no logins (there's no gui field for it). How do I set login "john" for user "John" then?

I found this issue: https://github.com/gravitational/teleport/issues/9790 which clearly states that it's not possible and it's not even priority so tried to do it via command line using tctl. I'm stuck here too. Tried different variation of

```
root@vm-teleport:~# tctl users update pavel
ERROR: missing name
```

but have no idea what `name` the ERROR is referring to
</div>

**Comment by webvictim** [comment]
Current answer in case anyone doesn't read the discussion:
``` console 
tctl get user/pavel > pavel.yaml
# Edit the pavel.yaml file and change the logins section to include the logins you want
tctl create -f pavel.yaml
```

**Comment by zmb3** [comment]
We do offer limited user edit functionality in the web UI (roles and traits).

Additionally, the `missing name` error no longer occurs.

Since the ability to edit logins is being tracked in #9790 I'm going to close this as a duplicate.
