### ISSUE TITLE
v9 breaks kubectl cp

### ISSUE THREAD

**Issue by gaetansnl** [gravitational/teleport#12229]
### Description

**What happened**:

When running for example `kubectl cp ./example-file namespace/pod:/tmp/example-file` the command doesn't work (hangs indefinitely)

**What you expected to happen**:

Command to work

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Install Teleport 9.1.1
2. Run `kubectl cp ./example-file namespace/pod:/tmp/example-file` avec tsh login
3. It doesn't work
4. Rollback to Teleport 8.3.8
5. Run the command, it works now

### Server Details
- Teleport version (run `teleport version`): 9.1.1
- Server OS (e.g. from `/etc/os-release`): 
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicated Hardware
- Additional details:

### Client Details
- Tsh version (`tsh version`): 9.1.1
- Computer OS (e.g. Linux, macOS, Windows): Linux Ubuntu 20.01
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

**Comment by xacrimon** [comment]
Note: likely the same as #12292
