### ISSUE TITLE
Terraform provider new syntax and labels

### ISSUE THREAD

**Issue by ygersie** [gravitational/teleport#12227]
### Description

With terraform provider version >= 9.0 the syntax has changed as documented [here](https://github.com/gravitational/teleport/pull/11669)

Can someone explain how we're supposed to supply multiple node_labels for a teleport_role resource?
It used to be possible to use a nested block:
```hcl
node_labels {
  key   = "env"
  value = ["dev", "dev2"]
}
node_labels {
  key   = "type"
  value = ["compute"]
}
```
But now the `key` needs to be a list of strings, which doesn't make real sense to me, and we have to make everything, including the `node_labels` an argument definition, meaning we can only define 1 like:
```hcl
node_labels = {
  key    = ["foo"]
  values = ["bar"]
}
```
I can't make the argument a list of maps either, then I get `Inappropriate value for attribute "spec": attribute "allow": attribute "node_labels": map of list of string required.`

**Comment by marcoandredinis** [comment]
Hey @ygersie :wave: 

Can you please try it like this?
```tf
      node_labels = {
        dev = ["dev", "dev2"]
        type = ["compute"]
      }
```

Does it work for your use case?

**Comment by ygersie** [comment]
@marcoandredinis that works perfectly, thank you! Could this be added to the documentation?

**Comment by marcoandredinis** [comment]
> @marcoandredinis that works perfectly, thank you! Could this be added to the documentation? 

I just added an example on how to do it
Can you please check?
https://github.com/gravitational/teleport/pull/12351
