### ISSUE TITLE
Audit kubectl commands

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#12240]
What would you like Teleport to do?
Ability for Teleport to audit kubectl commands

What problem does this solve?
Ability to see if users execute a command such as kubectl delete

If a workaround exists, please include it.
Not currently.

**Comment by tigrato** [comment]
@scottpgallagher friendly ping

**Comment by zmb3** [comment]
Closing this given the information requested is already logged, and we recently updated the description that shows in the web UI to make it more clear what the request was.
