### ISSUE TITLE
Audit log does not accurately report kubernetes namespace

### ISSUE THREAD

**Issue by colinedwardwood** [gravitational/teleport#12258]
Expected behavior:
When I run `kubectl get pods -n nginx`, for example, Teleport creates a log with a `namespace` field showing the correct namespace (in this example `nginx`).

Current behavior:
When I run `kubectl get pods -n nginx`, for example, Teleport creates a log entry but the `namespace` field always shows `default` rather than showing the correct namespace (in this example `nginx`).

Bug details:
- Teleport version 9.1.1
- Recreation steps
- See above.

- Debug logs

**Comment by tigrato** [comment]
@colinedwardwood the resource namespace is reported under `resource_namespace`.
The `namespace` field is the namespace of the proxy server and not a K8S namespace

```go
	// ServerNamespace is a namespace of the server event
	ServerNamespace string `protobuf:"bytes,1,opt,name=ServerNamespace,proto3" json:"namespace,omitempty"`
```

**Comment by zmb3** [comment]
@colinedwardwood with that info are we good to close this one?

**Comment by colinedwardwood** [comment]
Yes, I think part of the confusion is that when query all namespaces the `namespace` field is shown but `resource_namespace` is not. Perhaps for all namespaces `resource_namespace` should still be displayed but with "all" or some other result?
