### ISSUE TITLE
Application access support for full automatic user provisioning

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#12263]
What would you like Teleport to do?
Set up full user provisioning to web applications such that once users are authenticated via SSO (e.g. OKTA) they are automatically provisioned as new users on the application (e.g. Grafana). 

What problem does this solve?
To avoid manually creating new users in web application after users are already connected through SSO.

**Comment by TamCore** [comment]
Shouldn't this be possible to achieve with the JWT tokens? https://goteleport.com/docs/application-access/guides/jwt/

**Comment by zmb3** [comment]
This can either be done with JWT tokens (for apps that support JWT passthrough) or by using Teleport as a SAML IdP.

Adhering to standards like SAML or JWT is the best we can do. It's not feasible to support user provisioning for arbitrary applications in any other way.
