### ISSUE TITLE
No release builds for 2.2.5, 2.2.6 or 2.2.7

### ISSUE THREAD

**Issue by aashley** [gravitational/teleport#1230]
Just went to upgrade our change management system to deploy the latest version of teleport and noticed the last 3 bug fix releases don't have any official builds associated with them. Is this a permanent change going forward and thus should I update my deployment systems to use builds from somewhere else?

**Comment by klizhentas** [comment]
sorry, not doing the best job releasing 2.2.x properly, will fix.  I will ping @russjones to release tomorrow

**Comment by russjones** [comment]
@aashley I've released 2.2.7: https://github.com/gravitational/teleport/releases/tag/v2.2.7
