### ISSUE TITLE
kill switch for a cert/connection

### ISSUE THREAD

**Issue by bboles** [gravitational/teleport#1231]
If a user needs to have their connection terminated immediately, there is not a way to do that.  A command or method to terminate a current connection and revoke the certificate would be helpful.

**Comment by webvictim** [comment]
Related to https://github.com/gravitational/teleport/issues/2938

**Comment by stevenGravy** [comment]
The lock feature provides this. https://goteleport.com/docs/access-controls/guides/locking/
