### ISSUE TITLE
Error in Enterprise Cluster Documentation

### ISSUE THREAD

**Issue by mellowtelecode** [gravitational/teleport#12325]
## Details
There is a command for deploying Teleport in a Kubernetes cluster that is in the docs on: 

https://goteleport.com/docs/kubernetes-access/getting-started/cluster/?scope=enterprise

helm install teleport-cluster teleport/teleport-cluster --namespace=teleport-cluster-ent \
  --set clusterName=${CLUSTER_NAME?} --set acme=true --set acmeEmail=${EMAIL?} --set enterprise=true

This will not work for Enterprise, it needs to be helm install teleport-cluster-ent ....

helm install teleport-cluster-ent teleport/teleport-cluster --namespace=teleport-cluster-ent \
  --set clusterName=${CLUSTER_NAME?} --set acme=true --set acmeEmail=${EMAIL?} --set enterprise=true

This has caused me some trouble with set up in the past and I ran across it again spinning up another cluster.

### Category
- Improve Existing

**Comment by zmb3** [comment]
Closing as duplicate of #10583
