### ISSUE TITLE
Switch from `github.com/denisenkom/go-mssqldb` to `github.com/microsoft/go-mssqldb`

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#12336]
Looks like https://github.com/denisenkom/go-mssqldb is going to be unmaintained going forward, instead Microsoft SQL Server team has created their official fork of this library where the development will continue:

https://github.com/microsoft/go-mssqldb

We should switch to it. Specifically, I imagine that the PR that implements Kerberos support will only be merged in the new Microsoft's library. See https://github.com/gravitational/teleport/issues/10483.

**Comment by gabrielcorado** [comment]
Closed by #21065
