### ISSUE TITLE
improve data migration visibility

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#12365]
### What would you like Teleport to do?

Teleport does migrations sometimes. We should communicate the status of these to a teleport administrator so they can effectively plan and execute upgrades.

They should be able to refer to our documentation to see whether a migration for a given from and to version would possibly be required.

There should be information about migration status in a metrics or healthcheck endpoint so systems can be built to automate upgrades.

### What problem does this solve?

* Currently it is difficult-to-impossible to tell whether a given version upgrade will have any migrations.
* At startup, it is not clear how to tell whether migrations were determined to be needed, whether they are currently running, or what the result of the migration might be.

### If a workaround exists, please include it.

Currently, one would need to do some significant looking through the codebase to determine how migrations work to try to anticipate whether they will be needed or not.

gz#4254

**Comment by zmb3** [comment]
In addition to better documenting migrations, one option for monitoring the status is to make `tctl top` aware of migrations.

**Comment by russjones** [comment]
Let's do `tctl top`, add a log line that migrations are complete, and a Prometheus metric.

@vitorenesduarte Feel free to ping me for more details.
