### ISSUE TITLE
Allow configuration of separate Kubernetes public address in teleport-cluster chart

### ISSUE THREAD

**Issue by pimguilherme** [gravitational/teleport#12397]
**What would you like Teleport to do?**
We woud llike the teleport-cluster chart to include these items:
- possibility of configuring the kube_public_addr in the proxy service
- possibility of not configuring the kubernetes listener on the service (we want to define it manually through terraform with some extra restrictions)

**What problem does this solve?**
- being able to have a separate endpoint for kubernetes and to be in accordance with some internal policies
- for us, we can apply some extra firewall rules when accessing kubernetes 

If a workaround exists, please include it.
- workarounds are to basically do all the changes manually after the helm chart is applied

Please let me know your thoughts on item #2.. item #1 seems pretty reasonable so it's already been done as part of this PR: https://github.com/gravitational/teleport/pull/12416

UPDATE: removed need of nodeSelector as we can do it with affinity :)

thanks!

**Comment by webvictim** [comment]
Hey - as we discussed on the PR, we wouldn't look to implement this at the moment as it's fairly esoteric functionality that only works for one specific use case. If other people would like to see this added in future, please comment on this issue!
