### ISSUE TITLE
aws AMI should use port 3024 for tunnel on a non-acm proxy

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#12404]
Expected behavior:

When using the terraform/cloudformation examples with our published AMI, if there is a proxy with acm disabled, then the tunnel address should be set to port 3024 instead of 3080 (non-multiplexing)

Current behavior:

https://github.com/gravitational/teleport/blob/v9.1.3/assets/aws/files/bin/teleport-generate-config#L255-L266

Currently, the teleport.yaml file for a node with `TELEPORT_ROLE=proxy` and `USE_ACM=false` is generated by teleport-generate-config to have `tunnel_listen_addr: 0.0.0.0:3080` and `web_listen_addr: 0.0.0.0:3080`, which does not work since tls multiplexing mode is not enabled in the auth service.

This was specifically seen to cause a leaf cluster be unable to join. It appeared that it would try to connect to connect to the tunnel and time out and give up.

Bug details:
- Teleport version 9.1.3
- Recreation steps - deploy a cluster via https://github.com/gravitational/teleport-cluster-terraform and observe that the proxy nodes end up with overlapping tunnel and web listen addresses.
- Debug logs

gz#4994

**Comment by webvictim** [comment]
It's kinda weird that we just broke existing behaviour when we added TLS routing. This used to work without any additional changes required.
