### ISSUE TITLE
Option to provide `ca_pin` from file same as `auth_token`

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#12444]
What would you like Teleport to do?

There should be option to read `ca_pin` from `file_path` same as `auth_token`, so these are not hardcoded in `teleport.yaml` file.

What problem does this solve?
`ca_pin` can be managed separate from `teleport.yaml`.

If a workaround exists, please include it.
No

**Comment by ftong2020** [comment]
ca_pin should be included in helm repos IMO, there is no way to set it through helm values currently

**Comment by r0mant** [comment]
@GavinFrazar See the comment above, could you please add the field to our Helm charts also? After that we can close the ticket.

**Comment by GavinFrazar** [comment]
The helm charts have not been updated yet

**Comment by r0mant** [comment]
@GavinFrazar Got it, I've opened a new issue to track it: https://github.com/gravitational/teleport/issues/13580. Going to close this one.
