### ISSUE TITLE
docs: automatically expand side nav bar

### ISSUE THREAD

**Issue by FrankWeissmann** [gravitational/teleport#12463]
## Details
On the left hand subject menu rows - please remove the requirement to expand the sub-topics.  Instead, please have those sub-topics automatically listed underneath each major topic.  This request is for the teleport docs homepage.  Thank you!

### Category
- Improve Existing

**Comment by ptgott** [comment]
@FrankWeissmann Just checking to see how often you get this request/how important it is for users. I can create an issue in `gravitational/docs` (which is where we track work on the docs site functionality), and I'll add any context you provide there as well. Thanks!
