### ISSUE TITLE
Synchronize user information, access nodes between two teleport authencation servers

### ISSUE THREAD

**Issue by vnsinh921** [gravitational/teleport#12466]
To ensure high availability of the authentication server.
I have two authentication servers installed, so how can I synchronize user information and access nodes in the cluster between these two authentication servers?

Thanks for support!

**Comment by zmb3** [comment]
You would need to select a backend for the cluster state that supports multi-server (high availability), as per https://goteleport.com/docs/architecture/authentication/#storage-back-ends

Options are etcd, DynamoDB, or Firestore.
