### ISSUE TITLE
Remove `readsecrets` verb from rule definition

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1246]
Teleport admins do not need to be mentally overloaded with understanding the difference between "read" and "readsecrets".

`readsecrets` verb must be removed from the role definition.

## Implementation

Having discussed this with @klizhentas here's how we want to do it: simply by renaming.

- `read` verb must act as "read with secrets". I.e. if a role has "read" verb to a resource, the full representation of that resource, including secrets, must be given.

- `readnosecrets` verb must act as "read, but no secrets". This verb is only needed internally, for Teleport services (such as proxy).

## Behavior of "list"

When "list" action is executed (for example a caller is requesting a list of resources, like SAML connectors), the object included in the list can be either with secrets or without, depending on either the calling role has `read` or `readnosecrets`.

**Comment by klizhentas** [comment]
looks good to me

**Comment by klizhentas** [comment]
Chatted to @kontsevoy about it again - I suggested that we simply go back to pre 2.3 idea that `read` and `list` by default grant access to non-secret data, and getting access to secret should require `update` verb privilege on a collection

**Comment by klizhentas** [comment]
@russjones see above

**Comment by kontsevoy** [comment]
re-opening. this caused #1261 so these two are now a dupe.
