### ISSUE TITLE
Disable Pagination and re-enable instant-search

### ISSUE THREAD

**Issue by sgohl** [gravitational/teleport#12483]
What would you like Teleport to do?

I am a Teleport user since ~1 week, so I am not 100% sure, but I think Pagination was implemented just in the last few days.
Before, I have seen all servers in 1 list, without any pagination. 

I also imagine, that the search was instant-search. Instead, now I must press Return

These two things may are complaining at a high level, but since it was already there, it made the things actually worse and I'd like to have a setting to change it back to the old user interface without pagination - that would be great!

I'd happily ditch the advanced search in favor of instant-search

Edit: As usual with pagination, if not possible to disable, it should be possible to preset (as default) the items per page, with an option "all"

**Comment by tukusejssirs** [comment]
@zmb3, why there are no plans to do so?

+1 to re-open this issue and and those too features back.
