### ISSUE TITLE
Access to trusted clusters requires access to cert_authority and tunnels

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#1250]
Access to trusted clusters should not require access to cert_authority and tunnel. Right now a user has to grant access to all 3 resources in order to modify trusted clusters.

**Comment by kontsevoy** [comment]
@russjones Sasha says its a simple fix on the checker level.

**Comment by klizhentas** [comment]
yes, I suggest we do the following:

If user has some verb on trusted cluster imply the same verb rule on the cert authority and reverse tunnel as these are internal objects. This should fix problem.

**Comment by kontsevoy** [comment]
This issue is closely related to #1251
