### ISSUE TITLE
Strict-Transport-Security (HSTS) header should not be absent on `/`

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#12529]
Expected behavior:

Every http response from teleport should include the Strict-Transport-Security header.

Current behavior:

Most endpoints on the web proxy port include the `Strict-Transport-Security: max-age=31536000; includeSubDomains` header, but the `/` endpoint is a 302 redirect to `/web` and does not include the HSTS header.

```
$ curl -I https://teleport.example.com/
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /web
Date: Mon, 09 May 2022 20:38:23 GMT
```

Bug details:
- Teleport version 9.2.1
- Recreation steps - Look at the headers for the `GET /` response for any teleport cluster.
- Debug logs - n/a

gz#5077

**Comment by zmb3** [comment]
This seems more like a request to appease a security scan than a bug.

1. The HSTS header will be picked up on the subsequent request to `/web`.
2. Teleport doesn't listen for plain http:// traffic anyway, so there's no potential for protocol downgrade.

Is there any additional context behind the request that we should know?

**Comment by programmerq** [comment]
@zmb3 it is indeed related to a security scan, but having the HSTS header everywhere is certainly a stronger security posture. Future security scans will likely trigger on the same thing, so it'll save teleport users from the effort involved with going back and forth with an audit team, which is a good thing.

As for the specific case that prompted the github issue, I'm waiting to hear back on how big of a deal it is seen as by the folks doing the scan/audit.

**Comment by zmb3** [comment]
See also #3853 and #7500 which request that we start an HTTP listener that redirects to HTTPS.

HSTS doesn't really make any sense until/if there is an HTTP listener.
