### ISSUE TITLE
Add additional audit metadata for web actions

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#12523]
We should collect the following metadata for actions made via the web interface to improve security teams insight into key actions:

- IP address
- User Agent

Both these values will need to be forwarded from the proxy's web apiserver in the request made to the auth server API, where the auth server can then add these to the appropriate audit log entries.

The following actions need this metadata adding:

- [x] Log in
- [ ] Password reset
- [ ] Recovery code usage
- [ ] Changing MFA device configuration

**Comment by strideynet** [comment]
#12537 completes the addition of this metadata for the login action. I foresee some additional complexity in adding this additional metadata to other actions for reasons I will detail later today on here.

**Comment by jentfoo** [comment]
This came up again internally: https://github.com/gravitational/teleport-private/issues/1148

When considering audit events with SSO / auth failures, it's important to know the source of that request.

**Comment by reedloden** [comment]
See also #34598.

**Comment by strideynet** [comment]
Closing as dupe of https://github.com/gravitational/teleport/issues/34598
