### ISSUE TITLE
Create a local lab for trying out Teleport Cloud

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#12532]
## Details
We currently have two completely local demos for trying out Teleport:

- [Local Kubernetes Getting Started guide](https://github.com/gravitational/teleport/blob/40b9b524f230f451ceb1f2b864da5d2ff0360c60/docs/pages/kubernetes-access/getting-started/local.mdx)
- [docker-compose Getting Started guide](https://github.com/gravitational/teleport/blob/40b9b524f230f451ceb1f2b864da5d2ff0360c60/docs/pages/getting-started/docker-compose.mdx)

The advantages of these guides is that a user doesn't need to deploy any infrastructure of their own in order to try out Teleport, meaning no impact to their cloud bill and no need to (depending on the organization) coordinate with colleagues.

I think we could do something similar with Teleport Cloud. After a user begins a free Cloud trial, we would provide a readymade, locally running lab (e.g., another `docker-compose.yaml` config) that includes preconfigured resources like Nodes, applications, and databases. The user could then register these resources with their Teleport Cloud trial tenant and experiment with different Teleport products.

### Category
- Improve Existing

**Comment by stevenGravy** [comment]
A more builtout version of this could work @ptgott https://github.com/stevenGravy/teleportsampleresources

**Comment by xinding33** [comment]
@ptgott we can take a few different approaches:

- Create local lab as you've mentioned here
- Add pre-populated demo resources to Cloud trial environments so users can experience the access workflow
- Provide instructions for users to add their own workstation (for macOS and Linux)


We don't really have data to conclude which approach would have better results with regards to driving higher product engagement.

**Comment by ptgott** [comment]
Thoughts on this:

Our "Getting Started With Teleport Cloud" page (https://goteleport.com/docs/choose-an-edition/teleport-cloud/getting-started/) is probably the best place to put this. It requires a Linux Server, but we can easily change this to use a Docker container instead.

Why don't we include instructions to:
- Add `minikube` and Docker as prerequisites your workstation
- Launch a `minikube` cluster
- Launch Grafana in the cluster (https://grafana.com/docs/grafana/latest/setup-grafana/installation/kubernetes/)
- Launch the Teleport Application Service in the `minikube` cluster with `grafana` registered
- Launch the Teleport Kubernetes Service in the `minikube` cluster

We would include a role that can access `grafana` pods and the `grafana` application, plus instructions for creating a local user with that role.

The guide would include a step showing how to access the two resources we registered, and also how attempts to access _other_ resources fail.

**Comment by ptgott** [comment]
https://github.com/gravitational/teleport/pull/20837 adds a local setup using Docker to the Getting Started guide. It only includes the SSH Service, but the guide seems long enough. I think we can close this issue.
