### ISSUE TITLE
When upserting a new resource, we should verify it's 'kind' value

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#1254]
When calling an **internal** API method for upserting a resource of particular kind we should be checking it's kind value. For example, it's possible to create a trusted_cluster resource with random 'kind' value.

**Comment by kontsevoy** [comment]
which method?

**Comment by alex-kovoy** [comment]
These set of methods -> https://github.com/gravitational/teleport/blob/master/lib/auth/clt.go#L1616

In 'e' I added this [check](https://github.com/gravitational/teleport.e/blob/master/lib/web/handlers.go#L176) to fix it but this is on webapi level. If it looks good, you can close this.

**Comment by kontsevoy** [comment]
@alex-kovoy is this done? I think we can close this.
