### ISSUE TITLE
Document dynamic resource namespaces

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#12580]
## Details

It looks like Teleport applies [`deny` rules](https://github.com/gravitational/teleport/blob/b96cff3acf5e89fb48dbc5e076ed3bfa93b6374d/lib/services/role.go#L1884) and [`allow` rules](https://github.com/gravitational/teleport/blob/b96cff3acf5e89fb48dbc5e076ed3bfa93b6374d/lib/services/role.go#L1916) to the `metadata.namespace` of a dynamic resource when checking a user's access to that resource. However, we don't seem to have any documentation on the `Metadata.Namespace` field outside of the descriptions of `--namespace` flags in the CLI reference.

### Category
- Improve Existing

**Comment by zmb3** [comment]
As far as I understand it, namespaces are something that was never fully implemented and then abandoned. 

There are a number of places where the code just assumes the namespace will always be default. 

I think we can probably get by with just mentioning that namespaces are not supported in teleport and the field is meaningless.

**Comment by ptgott** [comment]
Thanks for the information. There are a couple mentions of the `--namespace` flag in the CLI reference, but I'm not sure we mention this anywhere else. Should we go ahead and delete these Teleport namespace references and otherwise not mention namespaces at all in the docs?

**Comment by marcoandredinis** [comment]
I created this issue for us to remove the namespace field
https://github.com/gravitational/teleport/issues/14000

**Comment by rsyracuse** [comment]
Shifting focus of this task to remove references to the `namespace` where applicable since Teleport only uses the default namespace and will never change. This is not something users need to interact with

**Comment by ptgott** [comment]
Closing in favor of #14000
