### ISSUE TITLE
Some Kubernetes Access setup docs don't mention creating appropriate role or include insufficient role configuration

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#12596]
## Details

I had connect a local k8s cluster (just the default stuff you get by running minikube) to my local Teleport cluster. So I went to the "Kubernetes Access - Getting Started" section of our docs and then I followed the [Connect a Kubernetes Cluster to Teleport](https://goteleport.com/docs/kubernetes-access/getting-started/agent/) guide.

After finishing the set up and doing `tsh kube login minikube`, I couldn't run any kubectl command.

```
$ kubectl cluster-info dump
Error from server: this user cannot request kubernetes access, has no assigned groups or users
$ kubectl get pods -A
error: the server doesn't have a resource type "pods"
$ kubectl get nodes -A
error: the server doesn't have a resource type "nodes"
```

Ultimately, the issue was that none of my user roles had `kubernetes_labels` specified.

But before Marek helped me figure that out, I googled the error message ("this user cannot request kubernetes access, has no assigned groups or users") and found [a discussion in our repo](https://github.com/gravitational/teleport/discussions/10852). One of the comments mentioned another guide: [Get started with Teleport on DigitalOcean Kubernetes](https://goteleport.com/docs/kubernetes-access/helm/guides/digitalocean/#create-a-new-kubernetes-role-named-member). That guide tells you to create a role with `kubernetes_groups: ["system:masters"]`. I did so, but it didn't solve my problem.

Joel tried reproducing this issue, but everything was working fine for them. When I tried to recreate Joel's Teleport cluster config, I ended up following the [Kubernetes Access from a Standalone Teleport Cluster](https://goteleport.com/docs/kubernetes-access/guides/standalone-teleport/) guide. Just like the Connect a Kubernetes Cluster to Teleport guide, it doesn't mention creating a user role.

So it seems that we'd need to update those two guides to mention the user role in some form and the DigitalOcean k8s guide should have `kubernetes_labels` added to its role. [We discussed this briefly](https://gravitational.slack.com/archives/C0DF0TPMY/p1652273113522249?thread_ts=1652105835.982879&cid=C0DF0TPMY) and it seems that after switching the role spec from v3 to v4, it became necessary to provide `kubernetes_labels`.

### Category
- Improve Existing

**Comment by ptgott** [comment]
We added the `kubernetes-access/rbac.mdx` partial since this issue was opened, which includes instructions for using the `kubernetes_labels` field.
