### ISSUE TITLE
Add custom CA cert configuration in the kube-agent helm chart

### ISSUE THREAD

**Issue by Dhru1Tanna** [gravitational/teleport#12594]
Details:
-

Teleport agent (as a database services) out of the box supports configuration of custom CA certs which currently isn't supported with the kube-agent helm chart.

- The CA cert can be included as a secret (k8s resource) which can be pre-deployed by the user and the secret name can be passed as a parameter value in the values.yaml. The secret then can be mounted as a volume alongside the auth-token secret.
- Adding support for using that secret will help the user configure the service with custom certs (which is very common).

For example:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/26624409/168009309-2f5c6c41-5ad8-4c0b-ba8d-9ee65696717f.png">

**Comment by Dhru1Tanna** [comment]
If the approach looks good. I can raise a PR to add the bit in the helm chart.

**Comment by webvictim** [comment]
There is a way to do this currently documented here: https://github.com/gravitational/teleport/discussions/12129

If you'd like to submit a PR to add this functionality to the chart itself as detailed then please go ahead. Our Helm chart contribution guidelines are here: https://github.com/gravitational/teleport/blob/master/examples/chart/CONTRIBUTING.md

Thanks!

**Comment by Dhru1Tanna** [comment]
Thanks @webvictim.
I have created this PR to include the piece: https://github.com/gravitational/teleport/pull/12630.
