### ISSUE TITLE
cert.create Audit Log Clutters the Audit Logs

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#12605]
**What would you like Teleport to do?**

Do not create an audit log every time the cert.create event occurs. Presently, an audit log entry is created every seven minutes that a user has an active WebUI session. 

**What problem does this solve?**

The cert.create/"Certificate Issued" logs in the WebUI clutter the audit logs and make it difficult to find important audit logs. 

**If a workaround exists, please include it.**

None

**Comment by zmb3** [comment]
Maybe the solution here is that the audit log needs better search functionality instead of emitting less events.

The `cert.create` was added in response to a security audit and is unlikely to be removed.

**Comment by r0mant** [comment]
Since we're keeping cert.create event I'm going to close this.
