### ISSUE TITLE
API - CheckLoginDuration(time.Duration) does not check for denied logins 

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#1260]
API - CheckLoginDuration(time.Duration) does not check for denied logins and uses only allowed ones.

**Comment by kontsevoy** [comment]
@russjones is this expected behavior?

**Comment by russjones** [comment]
@kontsevoy @alex-kovoy Yes, if you don't have access, you have no duration.

@alex-kovoy What is the context in which you are running into this being an issue.

**Comment by alex-kovoy** [comment]
this issue is outdated
