### ISSUE TITLE
To see auth connectors users are required to have update access

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1261]
Currently users are getting "access denied" when they try to see auth connectors (without trying to update them).

Logs (when I click on "Auth Connectors" in the Settings):

```
INFO [RBAC] list access to oidc [namespace default] denied for roles default,default-implicit-role: no allow rule matched  file="services/role.go:1395" func=services.RoleSet.CheckAccessToRule
INFO [RBAC] read access to oidc [namespace default] denied for roles default,default-implicit-role: no allow rule matched  file="services/role.go:1395" func=services.RoleSet.CheckAccessToRule
INFO [RBAC] update access to oidc [namespace default] denied for roles default,default-implicit-role: no allow rule matched  file="services/role.go:1395" func=services.RoleSet.CheckAccessToRule
INFO [RBAC] update access to auth_connector [namespace default] denied for roles default,default-implicit-role: no allow rule matched  file="services/role.go:1395" func=services.RoleSet.CheckAccessToRule
````

**Comment by kontsevoy** [comment]
@klizhentas I was told this is an artifact of trying to implement "readnosecrets"? (or the equivalent)

**Comment by kontsevoy** [comment]
I would be OK to punt this if we document the clean way of fixing this in the future. I am not concerned with the UX (after all the user may assume that it's expected behavior) but I am concerned that we have an auth API method which _reads_ auth connectors, but returns "access denied for verb 'update'". That's not solid.

**Comment by kontsevoy** [comment]
ouch. looks like it was caused by the recent experiment with #1246

**Comment by klizhentas** [comment]
@kontsevoy that's by design, if you want to see auth connectors in the admin UI you should be able to update them or UI should request auth connectors without secrets

**Comment by kontsevoy** [comment]
Update: having discussed this with @klizhentas the decision has been made to implement the original proposal in #1246, i.e. have a verb `readnosecrets`, used only by internal teleport services, for cases when we need to fetch connectors with stripped sensitive information (and other similar use cases as they may arise in the future)
