### ISSUE TITLE
Update all partials to use relative links

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#12618]
## Details
There's an open PR in `gravitational/docs` to allow for relative links in partials (https://github.com/gravitational/docs/pull/50). Once this is merged, let's change all links to MDX files in partials to be relative, letting us use our custom `remark-links` functionality on these links.

### Category
- Improve Existing

**Comment by rsyracuse** [comment]
https://github.com/gravitational/docs/issues/156
