### ISSUE TITLE
Add IAM join support to the k8s agent chart.

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#12639]
What would you like Teleport to do?
Add IAM join token support to the k8s agent chart.
https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-kube-agent

What problem does this solve?
Customer considers it a nice to have

If a workaround exists, please include it.
https://goteleport.com/docs/setup/guides/joining-nodes-aws-iam/#step-34-configure-your-nodes

**Comment by hugoShaka** [comment]
Closing as duplicate of https://github.com/gravitational/teleport/issues/10942
