### ISSUE TITLE
Terraform provider doesn't accept Machine ID identity files

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#12676]
Expected behavior:

The Terraform provider should accept identity files from Machine ID.

Current behavior:

Given this config:
```terraform
terraform {
  required_providers {
    teleport = {
      version = "9.0.0"
      source  = "terraform.releases.teleport.dev/gravitational/teleport"
    }
  }
}

provider "teleport" {
  addr               = "test-cluster1.schisa.cf:3025"
  identity_file_path = "identity"
}
```

...the Terraform provider fails with the following:

```
$ terraform plan

Error: all connection methods failed

	tls: found a certificate rather than a key in the PEM for the private key

  on main.tf line 10, in provider "teleport":
  10: provider "teleport" {
```

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by pschisa** [comment]
I upgraded my Terraform to the latest (1.1.9), updated the Teleport Terraform provider to 9.2.3 using out new registry, everything is now working fine with the machine ID creds

terraform {
  required_providers {
    teleport = {
      version = "9.2.3"
      source  = "terraform.releases.teleport.dev/gravitational/teleport"
    }
  }
}

provider "teleport" {
  addr               = "test-cluster1.schisa.cf:443"
  identity_file_path = "/opt/machine-id/identity"
  #cert_path          = "/opt/machine-id/tlscert"
  #key_path           = "/opt/machine-id/key"
  #root_ca_path       = "/opt/machine-id/teleport-user-ca.crt"
}
