### ISSUE TITLE
CentOS 7 binaries are built without BPF support

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#12688]
When building Teleport in our regular Ubuntu-based buildbox, we install libbpf in it so Teleport is linked against it:

https://github.com/gravitational/teleport/blob/740e626943d04660fd22c98e251011c35c0e8726/build.assets/Makefile#L131
https://github.com/gravitational/teleport/blob/740e626943d04660fd22c98e251011c35c0e8726/build.assets/Dockerfile#L134-L139

CentOS 7 based binaries do not include BPF dependency:

https://github.com/gravitational/teleport/blob/740e626943d04660fd22c98e251011c35c0e8726/build.assets/Makefile#L151-L177

We should update CentOS 7 (both regular and FIPS compatible) build and Dockerfiles to include BPF dependency:

https://github.com/gravitational/teleport/blob/740e626943d04660fd22c98e251011c35c0e8726/build.assets/Dockerfile-centos7
https://github.com/gravitational/teleport/blob/740e626943d04660fd22c98e251011c35c0e8726/build.assets/Dockerfile-centos7-fips

Advanced session recording won't work on CentOS 7 due to kernel version but since these are our "main" CentOS images now, it should work on newer CentOS versions.

**Comment by jakule** [comment]
@r0mant Can we close this issue or do we want to port the Docker CentOS changes to v9?
