### ISSUE TITLE
Allow agent joining over port 3024

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#12730]
## Problem

Currently, agents joining over reverse tunnel require access to several web handler methods which also serves web UI (port 3080 by default). The methods that they need are /webapi/ping, /webapi/ping, /webapi/host/credentials.

Because the same handler also serves all methods for web UI, there is no way to open up only parts of it, for example, to allow nodes to join the cluster but without also exposing web UI.

## Solution

Agents should be able to join over reverse tunnel port (3024 by default) without requiring access to the full web handler. Reverse tunnel listener should multiplex connections and expose a lightweight version of the web handler with methods mentioned above that agents can use for initial discovery.

With this in place, users will be able to only open 3024 for their agents and not expose entire web UI running on 3080.

**Comment by russjones** [comment]
@r0mant Do you mind updating this ticket with the workaround? What endpoints are needed on :3080 for a node to join. Then a user can configure their LB to only forward those endpoints.

**Comment by r0mant** [comment]
In a quick test I did a while ago, I was able to get the node to join only exposing these handlers:

- `/webapi/ping`
- `/webapi/ping/:connector`
- `/webapi/find`
- `/webapi/ssh/certs`
- `/webapi/host/credentials`

Not all of them may be required. Here's commit for reference: https://github.com/gravitational/teleport/commit/53e7786965ec3c370c847105ce977e8d11cbd382.
