### ISSUE TITLE
Indicate that labels with the same key and multiples values will overwrite each other

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#12739]
## Details
We can indicate this in our labeling guide: https://github.com/gravitational/teleport/blob/master/docs/pages/setup/admin/labels.mdx

### Category
- Improve Existing

**Comment by ptgott** [comment]
@lsgunn-teleport That's the up-to-date location, thanks!

**Comment by lsgunn-teleport** [comment]
@ptgott does the "values will overwrite each other" mean:
If I define the same static label key in a configuration file multiple times with different values, only the last value is used? I'm assuming that Teleport doesn't select a random value from the set of possible key values.
or
If I define the same static label key in different configuration files with different values, only one of them is used?

Do you happen to know the behavior here? If not, I'll try to do some testing.
