### ISSUE TITLE
Improve Delve developer experience

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#12744]
As an engineer trying to debug Teleport with Delve, it can be awkward to get off the ground with our current Makefile.

My suggestions would be to:

1. Modify the Makefile to either:
  a. Have a debug variable that ensures the binaries are built with the appropriate compiler flags (exclude `-ldflags='-s -w'`) to allow Delve to attach to the process. e.g `make all DEBUG=1`
  b. Include new targets that build and start teleport via Delve (`dlv debug tools/teleport`) e.g `make teleport-debug`
2. Include a section within the readme on using Delve to attach to a running Teleport process with the new Makefile changes.

My preference of 1) leans towards a), as this gives the most control to the engineer when they invoke the binary.

**Comment by zmb3** [comment]
This was solved in #18317 (I took approach 1a)
