### ISSUE TITLE
Docs for System Requirements

### ISSUE THREAD

**Issue by jsbrain** [gravitational/teleport#12757]
## Details

Not sure if I just missed it but I couldn't find anything about system requirements, neither in the docs nor the issues.

So I'm planning to try out Teleport and deploy it in my cloud but I have no clue what kind of server would be sufficient for the job.

### Category

- New Feature

**Comment by zmb3** [comment]
Is https://goteleport.com/docs/setup/operations/scaling/#hardware-recommendations what you're looking for?

**Comment by jsbrain** [comment]
Totally missed that, thanks. Yet I'm not sure if this is also helpful in a "minimal hardware requirements" scenario. Now I know what i need for 10.000 connections, but what about 100?
Like could I give teleport a test run installing it on a 1 vCPU 1GB RAM droplet on digital ocean or would it refuse to start?

I understand that's probably not the intended use-case for large teams but I can imagine there are quite a few people that just deploy it for personal use.

**Comment by zmb3** [comment]
It won't refuse to start. 1vCPU/1GB might be a little small, but it depends on how much usage you're expecting. I've run small test environments on 1vCPU/2GB without issue, but I'm generally the only user of the Teleport cluster.

**Comment by jsbrain** [comment]
That helps a lot, thank you!

**Comment by alifiroozi80** [comment]
Hello Guys
What about the storage capacity?
I want to install the Open-Source Teleport on a single Ubuntu server.
How much Storage capacity should I dedicate to the server?
