### ISSUE TITLE
Make Docs Scope more obvious

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#12773]
## Details
The scope dropdown is rather difficult to notice.  Many folks say they don't even notice it.  The landing pages could perhaps have a way of saying "I'm a cloud user", "I'm a OSS user"... that drives them to to the scope.  

<img width="498" alt="image" src="https://user-images.githubusercontent.com/60704961/169408463-e37770da-9f2e-4954-abee-be6fef7e7c0a.png">

### Category
- Improve Existing

**Comment by ptgott** [comment]
I've let the web design team know that this is an issue so they can consider ways to make the scope switcher more noticeable and (ideally) less avoidable.

Once my [PRs related to scoped visibility](https://github.com/gravitational/teleport/pulls?q=is%3Apr+is%3Aopen+author%3Aptgott+11383) are merged, I'll look into ways to add links to scopes to menu/landing pages.

**Comment by ptgott** [comment]
@stevenGravy There are still some outstanding backport PRs related to #11383, but once these are merged, will that address this issue from the docs side? Here are the relevant PRs that have been merged to `master`. These add links to different scopes to each section menu page:

- https://github.com/gravitational/teleport/pull/12708
- https://github.com/gravitational/teleport/pull/12712
- https://github.com/gravitational/teleport/pull/12716
- https://github.com/gravitational/teleport/pull/12718
- https://github.com/gravitational/teleport/pull/12737
- https://github.com/gravitational/teleport/pull/12741
- https://github.com/gravitational/teleport/pull/12742

I also recently opened this PR to add scoped Getting Started guide links for each edition to the docs home page: https://github.com/gravitational/teleport/pull/13062

**Comment by ptgott** [comment]
@stevenGravy Does the current docs header design resolve this issue?

**Comment by alexfornuto** [comment]
After talking with @stevenGravy I think the solve here is to replace the expandable components with tab components where appropriate. The expansions are locked into the versioning the user selects (or forgets to select) at the top, whereas tabs can be switched to match the users's environment ad-hoc.
