### ISSUE TITLE
Make Windows installation script more version agnostic

### ISSUE THREAD

**Issue by KurtLehnardt** [gravitational/teleport#12791]
## Details
Describe the documentation improvements you wish to see.
For this doc, https://goteleport.com/docs/installation/, under windows, 
The commands listed for windows RDP access are version dependent. 
The first command 
```$Resp = Invoke-WebRequest https://get.gravitational.com/teleport-v9.2.3-windows-amd64-bin.zip.sha256```
requires the -UseBasicParsing flag to work properly if IE engine is not available or complete. 

The command
```curl -O teleport-v9.2.3-windows-amd64-bin.zip https://get.gravitational.com/teleport-v9.2.3-windows-amd64-bin.zip```
doesn't work on Windows Server 2012 R2, it gives and error "-O is ambiguous", even though the docs say that tsh works on 2012 R2 and later.
It does work on Windows Server 2019. 
### Category

- Improve Existing

**Comment by zmb3** [comment]
FYI @ryanclark @LKozlowski we should look at the auto configure scripts and clean this up.

**Comment by zmb3** [comment]
These installation scripts make too many assumptions that don't hold true in enterprise environments, so they are being deprecated as of Teleport 16.
