### ISSUE TITLE
Remove misleading Enterprise tctl directions for Cloud users

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#12799]
## Details
There are some pages in the docs where we direct Cloud users to the Enterprise customer dashboard to download tctl. This dashboard is not available for Teleport Cloud users. Let's change these instructions to use the regular `tctl` or to reach out to Sales to get Enterprise dashboard credentials.

### Category
- Improve Existing

**Comment by ptgott** [comment]
I've searched for all mentions of the customer dashboard on the `master` branch of `gravitational/teleport`, and can confirm that none of them direct Cloud users to download `tctl` from there.

**Comment by sacrificeme** [comment]
@ptgott How about this one?

tctl create -f saml.yaml
ERROR: creating resources of type "saml" is only supported in Teleport Enterprise. If you connecting to a Teleport Enterprise Cluster you must install the enterprise version of tctl. https://goteleport.com/teleport/docs/enterprise/
