### ISSUE TITLE
`tsh` glitches umbrella ticket

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#12809]
## Not clear how to switch multiple clusters

We don't have a way to switch between two different root clusters `tsh login`:

https://github.com/gravitational/teleport/issues/10956

## tsh login requires --login flag

It is unclear to users that `tsh login` needs `--user` flag. Make it obvious or may be guess the user?

## Improve --help

`tsh login --help` is long as unclear, very unfriendly to first-time users. This one needs creativity. What can we learn from tools like `heroku` that have great UX?

**Comment by russjones** [comment]
Closing in favor of 

* https://github.com/gravitational/teleport/issues/10956
* https://github.com/gravitational/teleport/issues/13779
* https://github.com/gravitational/teleport/issues/13780
