### ISSUE TITLE
Improve user experience for users trying teleport with self-signed certificates.

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#12808]
Lots of times users want to try Teleport in their lab that is not connected to the internet usually and they run into when start teleport 9.2 with self signed certificate. Here's what I've recorded happened from one user who tried the system:

## Node fails to join

The node can't join because of the x.509 cert connecting to proxy. Node has failed with confusing error message:

```
Failed to resolve tunnel address Get "https://teleport.domain.com:443/webapi/find": x509: certificate signed by unknown authority reversetunnel/transport.go:90
```

In this case, the error message should have been (with a proper guide linked)

```
Failed to connect to the target proxy. Error: x509: certificate signed by unknown authority. Your proxy certificate is not trusted or expired. Please update certificate or follow this guide for self-signed certs: https://goteleport.com/docs/getting-started/self-signed#node
```

Please write the guide and update the section with the systemd unit to have insecure flag if running on Linux, or with helm chart for agent.

Don't forget to add `sudo systemctl daemon-reload` and `systemctl restart teleport.service` in the guide.

## Tsh fails to connect

Tsh login will fail:

```
tsh ssh --proxy=teleport.example.com --user=test ubuntu@test
ERROR: Get "https://teleport.example.com:3080/webapi/ping": dial tcp 172.16.30.98:3080: connect: connection refused
```

If you run the command with --debug you will see:

```
DEBU [TSH]       Race request failed error:[Get "https://teleport.example.com3080/webapi/ping": dial tcp 1.2.3.4:3080: connect: connection refused] tsh/resolve_default_addr.go:83
DEBU [TSH]       Trying teleport.example.com:443... tsh/resolve_default_addr.go:109
DEBU [TSH]       Race request failed error:[Get "[https://teleport.example.com:443/webapi/ping](https://teleport.example.com/webapi/ping)": x509: certificate signed by unknown authority] tsh/resolve_default_addr.go:83
```

First of all, let's improve this unclear "Race request failed error`. Seems like some strange internal phrasing.

Second, the user facing error should be:

```bash
tsh ssh --proxy=teleport.example.com --user=test ubuntu@test
ERROR: Failed to connect to https://eleport.example.com. The certificate has expired or signed by untrusted certificate authority. Please update your certificate. 

If you are trying teleport with self-signed certificate, please follow this guide: https://goteleport.com/docs/getting-started/self-signed#tsh
```

## User can't see nodes if missing principals

Our getting started for local users has this:

```
tctl users add --roles=editor,access test
```

The problem is, that this user has no principals and it should have been:

```
tctl users add --logins=ubuntu --roles=editor,access test
```

This one requires creative solution. First of all, user should be able to add principals without removing the user entry. Second, we should find a way to explain to users why they don't see the nodes if they are missing principals.

We only guessed (properly) when troubleshooting. But there should be a better way. For example, if users see empty list of nodes, they should see a different empty state:

```
Not seeing nodes? Your user is missing Linux principals. If trying teleport for the first time, follow this guide:

https://goteleport.com/docs/getting-started#principals
```

Related issues: https://github.com/gravitational/teleport/issues/9790
https://github.com/gravitational/teleport/issues/10574

**Comment by strideynet** [comment]
As for issues with principals not being configured https://github.com/gravitational/teleport/issues/9790 feels relevant here. At the moment, you cannot edit or see the principals assigned to a user within the UI. If we at least surfaced them so they were visible, it would probably be more obvious what is going wrong.

The same goes for `tctl`, we currently output only the user's roles within the table output by `tctl`. This should probably also show a list of the users principals, or, if that is likely to be too verbose we should offer a command that lets you show all information related to a user e. g `tctl users get noahstride`.

https://github.com/gravitational/teleport/issues/10574 also feels relevant regarding the documentation of adding users via tctl.

**Comment by GavinFrazar** [comment]
fwiw, I joined teleport last week and this one tripped me up quite a bit. I thought there was some issue with getting my cluster setup, but I had simple forgot to add principals for my user.

**Comment by russjones** [comment]
Closing in-favor of:

* https://github.com/gravitational/teleport/issues/13781
* https://github.com/gravitational/teleport/issues/13782
* https://github.com/gravitational/teleport/issues/13783
