### ISSUE TITLE
[TELEPORT 9.2.4 - LOW]  ERRO [IAM] Failed to get AWS identity. error  in gcp instance

### ISSUE THREAD

**Issue by Baskkra** [gravitational/teleport#12812]
Expected behavior:
Log run as it was and not check for aws IAM

Current behavior:
teleport always check for AWS IAM

Bug details:
- Teleport version : 9.2.4
- Recreation steps : when try to run teleport agent inside db instance
`2022-05-22T10:11:23Z ERRO [IAM]       Failed to get AWS identity. error:[
ERROR REPORT:
Original Error: *awserr.baseError NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/cloud/aws/identity.go:104 github.com/gravitational/teleport/lib/cloud/aws.GetIdentityWithClient
	/go/src/github.com/gravitational/teleport/lib/srv/db/cloud/iam.go:186 github.com/gravitational/teleport/lib/srv/db/cloud.(*IAM).getAWSIdentity
	/go/src/github.com/gravitational/teleport/lib/srv/db/cloud/iam.go:283 github.com/gravitational/teleport/lib/srv/db/cloud.(*IAM).deleteOldPolicy
	/opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors] cloud/iam.go:285`

is it due to update on new version 2 days ago? in fact it doesn't effect the connection to teleport it self, i think it's a low priority issue

**Comment by zmb3** [comment]
@atburke I believe this was fixed by #14867, can you confirm?

**Comment by atburke** [comment]
No, #14867 only deals with EC2 instance metadata. It doesn't interact with AWS credentials at all.
