### ISSUE TITLE
(web) Rename siteId with clusterName in JS files 

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#1282]
rename siteId with clusterName in JS files

**Comment by kontsevoy** [comment]
@alex-kovoy is this a big deal / a lot of work? you're renaming a variable or what? not sure how to prioritize this.

**Comment by alex-kovoy** [comment]
This is not a big deal. This is about code refactoring/clean-up.

**Comment by russjones** [comment]
@alex-kovoy I imagine this has been resolved since the UI has been re-written.
