### ISSUE TITLE
[v.9.0] /docs/pages/setup/admin/trustedclusters.mdx - Change cloud port from `3024` to `11XXX`

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#12824]
## Details

Trusted cluster details for Cloud needs to be updated. It references port `3024` whereas in the cloud this port is listed but for it to work it needs to be the `ssh_tunnel_public_addr` port instead (typically in the `11xxx` range).

Screenshots showing `3024` in the guide:

![Screen Shot 2022-05-23 at 9 27 24 AM](https://user-images.githubusercontent.com/1424442/169830517-39d39ab1-8625-4ab0-b8b3-3b6dc06f41a3.png)

![Screen Shot 2022-05-23 at 9 27 43 AM](https://user-images.githubusercontent.com/1424442/169830525-74f08b11-df0f-4054-abbf-f5cfe1046360.png)

![Screen Shot 2022-05-23 at 9 27 57 AM](https://user-images.githubusercontent.com/1424442/169830538-4b293908-8210-4430-8fab-b7bc4effcaf6.png)

If you are on Teleport cloud (`tenant.teleport.sh`) and try to follow the guides you will get an offline cluster/not-found if using port `3024`.

Run a `curl -k https://tenant.teleport.sh/webapi/ping | jq .` and look for this entry:

````
      "ssh_tunnel_public_addr": "tenant.teleport.sh:11131"
````

This is the port that needs to be configured in your cluster yaml. Our guides do not mention this at all.

### Category

- Improve Existing

**Comment by rsyracuse** [comment]
This was updated in https://github.com/gravitational/teleport/pull/10708
