### ISSUE TITLE
Add scaling information for Cloud users

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#12836]
## Details
Currently, our [Scaling guide](https://goteleport.com/docs/setup/operations/scaling/) focuses on the Auth Service and Proxy Service. We should add information that benefits Cloud users, such as:

- How much the managed Auth Service and Proxy Service scale in relation to a tenant's connected agents
- If it's possible to request more compute/storage capacity for a cloud tenant
- If there are any vertical scaling recommendations for a single agent host (e.g., one `teleport` binary configured to access a server, database, etc.)

We can consider adding a separate page for this.

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
While we're working on this page, we should expand this page to not just discuss SSH nodes, but DB/Desktop access and anything else we provide secured access to. This could also be spun into a separate issue, if we determine the scope is to large.
