### ISSUE TITLE
Teleport hardcodes global AWS STS endpoint, but this is no longer the default in EKS

### ISSUE THREAD

**Issue by chongyangshi** [gravitational/teleport#12867]
When Teleport runs inside an AWS Elastic Kubernetes Service (EKS) cluster, the recommended way to implement workload identity is to [add the EKS OIDC provider to IAM and allow ServiceAccounts to assume IAM roles](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html). This would on paper make it perfect for joining Teleport Proxy and Kube nodes into the cluster using [the IAM role method](https://goteleport.com/docs/setup/guides/joining-nodes-aws-iam/).

However, as stated in the relevant code in [master branch at the time of writing](https://github.com/gravitational/teleport/blob/bb121d7b1e210577dd23ec19de3677befc6b30d7/lib/auth/join_iam.go#L52):

```
	// Only allowing the global sts endpoint here, Teleport nodes will only send
	// requests for this endpoint. If we want to start using regional endpoints
	// we can update this check before updating the nodes.
	stsHost = "sts.amazonaws.com"
```

The global endpoint is hardcoded and this appeared to have been an intentional design. However using the global STS endpoint (`sts.amazonaws.com`) is [no longer the default behaviour in EKS from version 1.22 onwards](https://docs.aws.amazon.com/eks/latest/userguide/configure-sts-endpoint.html), which has been mainstream released for new EKS clusters. Instead, the regional endpoint for the current cluster region e.g. `sts.eu-west-1.amazonaws.com` is used by default.

Expected behavior:

Without explicitly configuring EKS ServiceAccount's STS endpoint, Teleport Auth nodes configured with IAM tokens should accept otherwise-valid join requests from nodes using regional STS endpoints.

Current behavior:

Because the global endpoint is hardcoded, the following error is reported by the nodes attempting to join through a regional STS endpoint:

```
2022-05-24T14:34:33Z INFO [AUTH]      Attempting registration via proxy server. logrus@v1.4.4-0.20210817004754-047e20245621/entry.go:289
2022-05-24T14:34:33Z ERRO [PROC:1]    Kube failed to establish connection to cluster: rpc error: code = PermissionDenied desc = sts identity request is for unknown host "sts.eu-west-1.amazonaws.com", rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority". logrus@v1.4.4-0.20210817004754-047e20245621/entry.go:289
```

While it is possible to explicitly configure the global STS endpoint to be used, [VPC interface endpoints](https://docs.aws.amazon.com/vpc/latest/privatelink/create-interface-endpoint.html) -- which allow STS traffic to be served by STS API using private VPC IPs -- cannot be used when using the global endpoint. This means that egress access to a wide and shifting set of AWS IAM/STS IP ranges in `us-east-1` must be allowed in VPC firewall rules, making the infrastructure less secure and this is undesirable for us.

Bug details:
- Teleport version: 8.3.1, but we are certain this is present on versions 9 and 10 as well given this behaviour is in `master` branch
- Recreation steps:
   - Create an AWS EKS cluster using version 1.22
   - Set up [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)
   - Set up [the IAM join method](https://goteleport.com/docs/setup/guides/joining-nodes-aws-iam/) in Teleport
   - Attempt to join a node using such a service account and its IAM permissions, observe the error above
- Debug logs
   - shown above

**Comment by nklaassen** [comment]
This should be fixed by allowing use of regional STS endpoints in https://github.com/gravitational/teleport/pull/15337, released in v10.2.0
