### ISSUE TITLE
Trusted clusters in OSS version of Teleport cannot be set up

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1290]
The notion of "Role" is absent in the OSS Teleport. Therefore I have the following definition of a trusted cluster:

```yaml
kind: trusted_cluster
version: v2
metadata:
  name: east
spec:
  enabled: true
  token: dogs-are-great
  tunnel_addr: ev-t1-master:3024
  web_proxy_addr: ev-t1-master:3080
```

I successfully create it, because I have added the following snipped to `CheckAndSetDefaults()`:

```go
if !lib.IsEnterprise(){
	// OSS teleport uses 'admin' by default:
	c.Spec.Roles = []string{teleport.AdminRoleName}
}
```

... basically added 'admin' role to the trusted cluster spec.

The trusted cluster is established and I can see it via `tsh clusters`.
But when I try to connect, I get "access denied" and here's what I see in the logs:

(with nicer formatting)
```
ERRO Permission denied: user ekontsevoy@ev-t1-master is not authorized to login as ekontsevoy@ev-t2-master: 
access to node ev-t2-master is denied to role(s): 

[
  role admin denied access: allow rules did not match; match(namespace=true, label=true, login=false) 
  role default-implicit-role denied access: allow rules did not match; match(namespace=true, label=false, login=false)
]  

file="srv/sshserver.go:699" fingerprint="ssh-rsa-cert-v01@openssh.com SHA256:VcyzfFxlQLkcTYCcjachaiTOTxOWa0lA/Das6fpKOWM" func="srv.(*Server).keyAuth" local="127.0.0.1:3022" remote="192.168.1.16:34088" user=ekontsevoy
```

Dump of the trusted cluster:

```bash
$ tctl get cluster/oss

kind: trusted_cluster
version: v2
metadata:
  name: oss
spec:
  enabled: true
  role_map:
  - local:
    - admin
    remote: admin
  token: dogs-are-great
  tunnel_addr: ev-t1-master:3024
  web_proxy_addr: ev-t1-master:3080
```

So the role mapping appears to be set. Yet it still won't let me in even though I'm an admin.

Here's my "admin" role on the cluster that's denying me access:

```bash
ev-t2-master ~: tctl get role/admin

kind: role
version: v3
metadata:
  name: admin
spec:
  allow:
    logins:
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
    rules:
    - resources:
      - role
      verbs:
      - connect
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - auth_connector
      verbs:
      - connect
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - session
      verbs:
      - list
      - read
    - resources:
      - trusted_cluster
      verbs:
      - connect
      - list
      - create
      - read
      - update
      - delete
  deny: {}
  options:
    max_session_ttl: 30h0m0s
```

**Comment by kontsevoy** [comment]
## Update

I looked at the code. The remote users (i.e. users coming from remote clusters) do not have their "traits" available for evaluation against `{{internal.logins}}`. I looked into `ApplyTraits()` function and it always gets `nil` for its [second parameter](https://github.com/gravitational/teleport/blob/57f0380d3cde535ba5161a33071a7da72fd73ffe/lib/services/role.go#L270).

**Comment by klizhentas** [comment]
In OSS mode we should evaluate SSH cert principals and covert them to traits for remote trusted clusters. @russjones talk to me before doing this ticket.

**Comment by klizhentas** [comment]
For `internal.logins` we should always look at the `logins` from the certificate to make teleport.

**Comment by klizhentas** [comment]
Here when fetching roles, for remote users, we should call `ApplyTraits`:

https://github.com/gravitational/teleport/blob/master/lib/srv/sshserver.go#L526

to allow roles to process `internal.logins`
