### ISSUE TITLE
Tweak the organization of `/docs/getting-started`

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#12921]
## Details
In the current version of [`/docs/getting-started`](https://github.com/gravitational/teleport/blame/f4ead6122372bc44977f7f6dc6cf995f32db1e38/docs/pages/getting-started.mdx), the "Deploy to Production" section includes a link to "Teleport on DigitalOcean" along with a link to each edition-specific Getting Started guide. This is a bit misleading, since:

- It's the only guide in this section that is not the representative Getting Started guide for an edition
- It suggests that DigitalOcean is the only platform we have specific guidance for

The Teleport on DigitalOcean guide might be better suited for the `/setup/deployments` section, which includes guides for self-hosted clusters on specific platforms.

### Category
- Improve Existing

**Comment by stevenGravy** [comment]
This could also potentially link to enterprise.
