### ISSUE TITLE
Incomplete session uploads metric

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#12935]
Add a metric a metric (and log line) for number of sessions recordings that have not been uploaded to auth.

Useful when debugging cluster to find nodes with either corrupted or incomplete recordings.

**Comment by zmb3** [comment]
This metric should also exist on auth, for the number of incomplete uploads to external storage.

**Comment by r0mant** [comment]
@EdwardDowling Please don't forget to update [Metrics](https://goteleport.com/docs/management/diagnostics/metrics/) docs page to include this new metric.
