### ISSUE TITLE
Local user DB needs reset/passwd capability 

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1294]
The users of open source Teleport have been repeatedly asking for two features that are closely related:

* Ability to reset a user account, i.e. re-initialize the 2nd factor without having to re-create the user record.
* Ability for users to change their passwords.

## Proposals

To be discussed, but here's the initial approach:

1. Introduce `tctl users reset <username>` command which would print a URL similar to sign-up URL we create for `tctl users add`. An admin would then share the URL with the user who'll re-initialize his phone for 2FA and pick a new password.

2. Expose "Settings" tab to all OSS users with standard password change functionality. If the 2FA is enabled, it must be involved as well to change the password.

## Related

When changing the password we're going to implement additional restrictions. Consider doing this work with #1936

**Comment by aberoham** [comment]
@nawadanp see above

**Comment by gclawes** [comment]
Somewhat related to this, are there plans for supporting multiple 2fa factors (multiple u2f keys, u2f+TOTP)?

**Comment by kontsevoy** [comment]
@gclawes Teleport supports multiple simultaneous authentication providers (connectors). The community/OSS version can use Github (which itself brings a menu of MFA options) _plus_ the local connector with built-in 2FA methods. The enterprise edition can do a lot more: any enterprise SSO (with various MFA options) can be used.

**Comment by klizhentas** [comment]
@kontsevoy I suggest we move this one out of 2.6.0 to reduce the scope a bit, does not seem like a pressing issue.

**Comment by gclawes** [comment]
@kontsevoy specifically for the local connector, would it be possible to support both TOTP and U2F auth at once, and mutliple U2F keys registered per account.  That seems to be the standard supported for 2-factor auth on many popular apps/sites (for example, GitLab):

<img width="1458" alt="screen shot 2018-04-26 at 11 51 09 am" src="https://user-images.githubusercontent.com/172517/39316851-2ad28d5e-4948-11e8-9472-3be7ffc6fcb0.png">

**Comment by kontsevoy** [comment]
@gclawes your suggestion is reasonable. do you mind creating a separate ticket for it? This one is about password resets and your comment will probably be lost after devs add this feature.

**Comment by gclawes** [comment]
Opened: https://github.com/gravitational/teleport/issues/1929

**Comment by alex-kovoy** [comment]
Closing it as it has been implemented  https://github.com/gravitational/teleport/pull/3287 in the hornet branch which is the dev branch for V5 release.
