### ISSUE TITLE
Add `tctl proxy ls` and `tctl auth ls` to get a clean list of connected auth and proxy services

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#12965]
What would you like Teleport to do?
Add the functionality to `tctl` for auth and proxy resources to run an ls and get a short list of the connected `auth` and `proxy` services, similar to what you can do for other services like `node`

Would like to be able to run `tctl proxy ls` or `tctl proxies ls` to return a short/clean list of connected proxies

Would like to be able to run `tctl auth ls` or `tctl auths ls` to return a short/clean list of connected auths

What problem does this solve?
Observe and track currently connected proxies and auth services in a manner consistent with our other resource services.

If a workaround exists, please include it.
use `tctl get proxy` and `tctl get auth` with a `grep` to sort for the relevant information you are hunting for in the list

**Comment by zmb3** [comment]
I would probably advocate for this in `tctl status` or `tctl top` rather than in a `ls` subcommand, just because proxy/auth are not proper teleport resources.

**Comment by r0mant** [comment]
They are proper resources, or `proxy` and `auth_server` kind respectively, as they participate in the heartbeat just like regular nodes. I think `tctl proxy/auth ls` makes sense (by analogy with `tctl nodes/app/db/etc ls` we already have), I'll get this assigned as a warm up issue to someone.
