### ISSUE TITLE
Add functionality to add MySQL parameters to teleport-generate-config script

### ISSUE THREAD

**Issue by jpena88** [gravitational/teleport#12991]
What would you like Teleport to do?
Update the `teleport-generate-config` script to support being able to add `mysql_listen_addr` & `mysql_public_addr` if a variable in the user data is set.

What problem does this solve?
Allows users who run Teleport in HA mode to proxy MySQL connections for Teleport Database access.

If a workaround exists, please include it.
Unfortunately the workaround is pretty manual. I would like to create a PR that adds this functionality, should be very straightforward.

**Comment by jpena88** [comment]
@ryanclark

**Comment by ryanclark** [comment]
Closing as the desired functionality was introduced in https://github.com/gravitational/teleport/pull/12972
