### ISSUE TITLE
Provide documentation on port usage for DBs

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#13009]
## Details
The DB doc reference includes postgresql, mysql and mongodb.  We have additional protocols such as Redis, SQL Server and cockroachdb.  An administrator using non-TLS configuration would want to know what ports need to be available for each db type.

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
@stevenGravy can you point to what page and section this is referring to?

**Comment by stevenGravy** [comment]
> @stevenGravy can you point to what page and section this is referring to?

Sure, https://goteleport.com/docs/database-access/reference/configuration/#proxy-configuration

**Comment by alexfornuto** [comment]
Thanks! These services are also not included in `docs/pages/includes/config-reference/proxy-service.yaml`, so before making documentation changes I'd like confirmation that there are in fact config keys available for these services (and what they are).

Tagging @GavinFrazar @smallinsky and @greedy52 as database SMEs to weigh in.

**Comment by greedy52** [comment]
https://goteleport.com/docs/database-access/reference/configuration/#proxy-configuration is up-to-date as far as configuration goes. We stopped adding more separate ports for database types.

Redis, ElasticSearch, OpenSearch do native TLS so sharing the Proxy Web/Public address port. Other databases not in the previous list are only supported through TLS routing.

https://docs.google.com/spreadsheets/d/1m0swp5F4PZ9-C6pAUR45FbIB1o2IeJ3mjmJz1VrRG3g/edit?usp=sharing we have a spreadsheet to track this (e.g `tsh db config`). Hope that helps.
