### ISSUE TITLE
Support AWS RDS Auora Serverless v2

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#13018]
## What would you like Teleport to do?

AWS RDS Aurora Serverless v2 is [GA](https://aws.amazon.com/blogs/aws/amazon-aurora-serverless-v2-is-generally-available-instant-scaling-for-demanding-workloads/)  now.

In the preview of Serverless v2, the IAM auth aws not supported. However according to [the latest doc](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html), v2 now supports IAM auth.

Should investigate and enable serverless v2 in Teleport if possible
https://github.com/gravitational/teleport/blob/ce4d6234ff29d96a63bedd4df55b2981e6680097/lib/services/database.go#L517-L524

**Comment by webvictim** [comment]
Mentioned in https://github.com/gravitational/teleport/discussions/13036
