### ISSUE TITLE
Per-session MFA eats 1-2 keypresses (depending on devices)

### ISSUE THREAD

**Issue by gabrielcossette** [gravitational/teleport#13021]
### Expected behavior
Once the remote prompt appears, all input should get sent to the remote server.

### Current behavior
With "Per-session MFA" enabled, depending on what device(s) you have added, `tsh ssh` logins may eat 1-2 keypresses.

Scenarios:

1.  OTP and WebAuthn added
    1. OTP used = 1 keypress
    1. WebAuthn used = 2 keypresses
1. OTP only added = 1 keypress
1. WebAuthn only added = 0 keypress

It looks a bit similar to #11709.

#### Teleport version

9.3.0 (also tested with 9.2.4)

### Recreation steps

1. Enable "Per-session MFA"
2. Add an OTP device (and optionally a 2nd WebAuthn one)
3. Try to login in a device `tsh ssh`

### Debug logs

_Let me know if you would like them._

I'll be happy to help further, thanks!

**Comment by codingllama** [comment]
Hey Gabriel, thanks for the report.

It's definitely #11709 in a new clothing. The solution we used there may be a bit difficult to implement here, as defaulting to the strongest auth (WebAuthn) could make starting ssh sessions from remote hosts not possible (aka #12675, but without mitigations).

I'll go back to the drawing board, find a way to reconcile all those issues and see what I can put together.

**Comment by codingllama** [comment]
I've put together a fix that should land in master shortly (I'll port it to v9 after it lands).

It's similar to the fix #11709, but this time I've gone ahead and made anything that isn't `tsh login` default to the strongest MFA method. If that doesn't work for you (eg, remote machine), then you can use the `--mfa-mode` flag to specify a different MFA method (eg, `tsh --mfa-mode=otp ssh llama@themachine`). Setting the `TELEPORT_MFA_MODE` environment variable also works.

**Comment by codingllama** [comment]
Backport just landed on v9, docs soon to follow. Closing the issue.

**Comment by gabrielcossette** [comment]
Thanks a lot @codingllama for looking into this!

I just tested the fix. No more keypresses eaten for WebAuthn. But unfortunately, still 1 keypress is eaten when we use OTP (both when "OTP and WebAuthn" and "Only OTP" has been added).

Tested on 9.3.6.

Thanks again in advance!

**Comment by codingllama** [comment]
Repro confirmed, doesn't seem to affect v10/master. I've backported a couple more changes I did a while back to v9, those make the all-consuming-stdin-read-loop a bit more gentle, which fixes it for me. PR on the way.

**Comment by codingllama** [comment]
Thanks for the patience, @gabrielcossette !

**Comment by gabrielcossette** [comment]
Awesome!
Can't complain, thanks for your awesome support @codingllama!

**Comment by gabrielcossette** [comment]
Release 9.3.9 fixes the remaining issue, thanks for your awesome work @codingllama!
