### ISSUE TITLE
Duplicate image names in /docs/pages/setup/guides/docker.mdx

### ISSUE THREAD

**Issue by harskogr** [gravitational/teleport#13026]
## Details
In "Step/1.4. Pick your image".
You describe your naming scheme for docker images tag.
But both examples use the same image tag: quay.io/gravitational/teleport:9.2.4
I think first one should be:
quay.io/gravitational/teleport:9 

### Category
- Improve Existing

**Comment by zmb3** [comment]
This is a problem on v10 as well.

**Comment by ptgott** [comment]
We can address this at the same time as https://github.com/gravitational/teleport/issues/13502
