### ISSUE TITLE
Provide non SSL endpoint for web proxy

### ISSUE THREAD

**Issue by sokoow** [gravitational/teleport#1304]
I'd like to have an option to disable TLS completely when using teleport. Why? Cause it makes a lot of problems when you want to terminate through reverse proxy that respects LetsEncrypt. I want to be able to terminate my SSL session on reverse proxy, but because Teleport uses it's own mandatory certs, it doesn't currently work. Is this something hard to do ?

**Comment by sokoow** [comment]
This will also make it way easier to deploy in Kube + Traefik scenario.

**Comment by kontsevoy** [comment]
@sokoow thanks for the suggestion. This is, of course, trivial to do, but we have made a decision to "tls-all-the-things" and have managed to stick to it so far. Lets keep this open and see how popular this gets. 

To clarify: you're having problems telling your proxies to use self-signed certificate that Teleport proxy auto-generates?

**Comment by sokoow** [comment]
Yes, that's what's happening, but let me explain in details: so I'm running Teleport on top of a kubernetes cluster, and in kubernetes world, the ingress traffic is usually pure http from the application side. What's sorting out the SSL cert is usually reverse proxy itself. So now I have a situation where my reverse proxy has a valid SSL cert from LetsEncrypt, but teleport listens on https instead of http, so further communication doesn't work.

**Comment by kontsevoy** [comment]
Understood. Let us keep it here for a while to collect community feedback. We need to weight this against situations when people accidentally leave TLS off for exposed Teleport proxies and get owned. Even if we do it, we need to make sure that turning TLS off is as explicit (and loud) as possible.

**Comment by octalthorpe** [comment]
Running this in AWS behind a loadbalancer that does TLS termination with AWS provided keys would be ideal. +1 for this feature.

**Comment by sokoow** [comment]
Any more comments ? Do we have a consensus yet ? I'm tempted to patch it myself :D

**Comment by dadicool** [comment]
+1 on this, we have a similar need with teleport begin deployed behind an internal LB within our own infrastructure and terminating SSL at the LB helps a lot with operational management of the SSL certs.

**Comment by mechastorm** [comment]
This will also help with our implementation as well in AWS being deployed in an ELB-like architecture. The storage of the SSL certs on the proxy servers create an additional operational and security overhead for us.

**Comment by sokoow** [comment]
Bump, any more comments on that ?

**Comment by kontsevoy** [comment]
closed, thanks @sokoow
