### ISSUE TITLE
Machine ID should generate an OpenSSH certificate with a conventional name

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#13086]
What would you like Teleport to do?

`tbot` should generate a certificate following OpenSSH's convention (https://man7.org/linux/man-pages/man5/ssh_config.5.html):

> If no certificates have been explicitly specified by CertificateFile, ssh(1) will try to load certificate information from the filename obtained by appending -cert.pub to the path of a specified IdentityFile

Given this, we should generate `key-cert.pub` in addition to / in place of our current `sshcert` file.

What problem does this solve?

Users that manually configure SSH will unnecessarily need to specify the `CertificateFile`. In normal circumstances it should be detected automatically by OpenSSH based on the rule above.

If a workaround exists, please include it.

Workarounds include:
* Use the included `ssh_config` which configures the certificate file path
* Create a symlink: `ln -s $(pwd)/sshcert key-cert.pub`
* Manually specify `-o CertificateFile=/path/to/sshcert`

**Comment by strideynet** [comment]
Merely renaming this file results in an error when it attempts to load in the old identity:

```
Identity directory /var/lib/teleport/bot is not found or empty and could not be loaded, will start from scratch: artifact "key-cert" is unexpectedly empty in destination directory /var/lib/teleport/bot tbot/tbot.go:315
```

Therefore, we need to either write it under both names, or include some migration that allows it to read from the old path for a version or two.
