### ISSUE TITLE
Machine ID should manage database proxies automatically

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#13085]
What would you like Teleport to do?

`tbot` should automatically run (or have an option to run) the `proxy db ...` function for a given destination if database certificates were requested.

What problem does this solve?

Currently, if using database access with Machine ID, you'll need to manually run `tbot proxy ...` in the background somehow to start the proxy listener. This is awkward to do manually and requires manual steps for systemd.

If a workaround exists, please include it.

It can be run in the background, but the UX is awkward:

```
tbot proxy --destination-dir=/opt/machine-id --proxy=proxy.example.com db foo
```

A systemd service will help, but will crash until the directory has been initialized:
```
[Unit]
Description=Teleport Machine ID Proxy Service
After=network.target

[Service]
Type=simple
Restart=on-failure
ExecStart=/usr/local/bin/tbot proxy --destination-dir=/opt/machine-id --proxy=proxy.example.com db foo

[Install]
WantedBy=multi-user.target
```

We could add a systemd dependency on the tbot service to smooth this over a bit. It will still be ugly when certs expire (and I'm sure there's other edge cases).

**Comment by strideynet** [comment]
I think this somewhat fits in nicely with the refactor we've got in mind. If each destination is actually a goroutine (or multiple goroutines) then this sort of functionality is each to achieve.

**Comment by strideynet** [comment]
Replaced by https://github.com/gravitational/teleport/issues/36291
