### ISSUE TITLE
Replace  /var/lib/teleport/bot with something that doesn't expose /var/lib/teleport

### ISSUE THREAD

**Issue by slavitch** [gravitational/teleport#13117]
I'd like to replace /var/lib/teleport/bot with something that doesn't expose /var/lib/teleport 

Perhaps /opt/bot or somewhere, anywhere else.  

Exposing /var/lib/teleport is a bad idea.

**Comment by zmb3** [comment]
You can use whatever data dir you want:

```
$ tbot start --data-dir=/opt/bot
```

**Comment by zmb3** [comment]
Does this work for you @slavitch or is there an issue here?

**Comment by zmb3** [comment]
I'm going to close this due to inactivity and assume this works for you. Let me know if that's not the case.
