### ISSUE TITLE
`tctl bots add` should use the proxy's public address by default

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#13123]
Expected behavior:

When adding a new bot, the joining snippet should set `--auth-server=proxy.example.com:3080` rather than the auth server's address.

Auth servers are frequently inaccessible and now that we support connecting to the auth server via the proxy, there's few downsides to recommending this by default (other than nastier error messages). Also, proxy servers should always have a sane public address.

Current behavior:

We generate a snippet referring to the auth server's address. We check for a set public address (not always the case) and fall back to the internal address. This can be confusing and is unlikely to work out of the box for a significant number of users:

```
Then, run this as the bot user to begin continuously fetching
certificates:

> tbot start \
   --destination-dir=./tbot-user \
   --token=<snip> \
   --ca-pin=sha256:c4d6abc8e93828e58e1b56fd95aef8a6590b70bce48ade6c434d6b84f50846c8 \
   --auth-server=192.168.10.2:3025
```

Bug details:
- Teleport version: v9.3
- Recreation steps: `tctl bots add example --roles=access`
- Debug logs

**Comment by webvictim** [comment]
We should do this for `teleport start` as a whole. Similar to https://github.com/gravitational/teleport/issues/11458
