### ISSUE TITLE
Adding authorization labels to a given node

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#13135]
What would you like Teleport to do?
Customer would like for Teleport to enable the following: 
I’m looking for something different from dynamic labeling. We need to be able to, from an arbitrary server, add a label associated with the device. We want to inject SSH labels without needing to change /etc/teleport.yaml on the node itself.

What problem does this solve?
They have nodes which, they want to reduce the amount of state on the device itself, this nodes don’t have access to information that we want to use as a label. That information is stored in a DB and could be made to be query-able. 
A more clear-cut example would be adding authorization labels to a given node. The node itself might not know what it is authorized to do, but some external server would. This would assist greatly in our daily operations. 

If a workaround exists, please include it.
Customer suggestion: 
In the meantime, we may be able to solve this with having one label query an endpoint to receive its labels.

A possible workaround from Teleport side:
We could have that server just update a file on the node, and use dynamic labeling to cat the file. In addition, we could probably use MachineID to always have tsh ssh credentials ready for the script. Again, out of the box Teleport can't do this directly. Currently, they are using v9.

**Comment by zmb3** [comment]
I'm not sure I understand.

Does this not work?
```
ssh_service:
  labels:
    foo: bar
    baz: quux
```

**Comment by webvictim** [comment]
I think the ask here is that you can inject SSH labels without needing to change `/etc/teleport.yaml` on the node itself.

**Comment by Erick-Reyes** [comment]
Correct, I believe customer wants to inject SSH labels without needing to change /etc/teleport.yaml on the node itself. Here some additional input from customer: 
Another thought would be something like an API for moving nodes to named clusters. Is something like this possible?

**Comment by 3gmgithub** [comment]
Definitely would be a huge update if we could do this through tctl for all resources not just nodes... or even from the gui to add/remove labels would be huge...

**Comment by zmb3** [comment]
> We want to inject SSH labels without needing to change /etc/teleport.yaml on the node itself.

This is now doable with the `server_info` resource.

Docs at https://goteleport.com/docs/management/admin/labels/#apply-resource-based-labels
