### ISSUE TITLE
build error on Ubuntu 20.04 

### ISSUE THREAD

**Issue by jingkang99** [gravitational/teleport#13144]
Ubuntu 20.04
rustc     1.57.0   <-- installed by using **apt install rustc**
go version go1.18.2 linux/amd64

Bug details:
- Teleport version  9.3.2
- Recreation steps 
- Debug logs
![image](https://user-images.githubusercontent.com/10793075/171822277-05e4d48d-d6fb-4c7b-9da0-f83d6255371a.png)

**Comment by zmb3** [comment]
Try using a newer version of `rustc`? We're currently using 1.61.0 for our official builds.

**Comment by jingkang99** [comment]
Thanks. teleport team working hard, committing quit often. 
![image](https://user-images.githubusercontent.com/10793075/171946283-ee831f55-2932-478c-9aad-245490ba915d.png)

this can be compiled. 
make
