### ISSUE TITLE
Desktop unable to connect to Windows Servers (licensing nego)

### ISSUE THREAD

**Issue by ugmac** [gravitational/teleport#13152]
Expected behaviour: Able to establish RDP connection to the server.

Current behaviour: Teleport connects to Windows 10 endpoints just fine but cannot establish the connection to the servers. Teleport console logs the issue as 'RdpError { kind: NotImplemented, message: "Licensing nego not implemented'

Teleport can connect to all Windows 10 endpoints without error.
RDP clients other than Teleport can connect to Windows Servers without the issue.

Bug details:
- Teleport version
- 9.2.3, Docker
- Recreation steps
- Under 'Desktops' select the endpoint and click 'Connect' with preconfigured user account.
- Debug logs
INFO [AUDIT]     windows.desktop.session.start addr.remote:<removed>:3389 cluster_name:teleport code:TDP00W desktop_addr:<removed>:3389 desktop_labels:map[teleport.dev/computer_name:WIN19SERV teleport.dev/dns_host_name:<removed> teleport.dev/is_domain_controller:true teleport.dev/origin:dynamic teleport.dev/os:Windows Server 2019 Standard teleport.dev/os_version:10.0 (17763) teleport.dev/<removed> teleport.dev/windows_domain:<removed>] desktop_name:<removed> ei:1 error:[Rdp(RdpError(RdpError { kind: NotImplemented, message: "Licensing nego not implemented" }))] event:windows.desktop.session.start login:<removed> message:Rdp(RdpError(RdpError { kind: NotImplemented, message: "Licensing nego not implemented" })) proto:tdp sid:6639c20a-f4b2-4909-816e-d8d18933e136 success:false time:2022-06-03T16:32:04.123Z uid:54e92749-48b0-4fd4-a44e-0a0361d1baf1 user:steven windows_desktop_service:1b8c3c46-7870-415a-ab44-f537ff6def3a windows_domain:<removed> windows_user:<removed>u events/emitter.go:325

**Comment by zmb3** [comment]
Do you have a valid Windows Server license?

**Comment by ugmac** [comment]
All the windows servers are properly licensed. There are 2x Windows Server 2016 Standard, 1x Hyper-V standalone and 2x Windows Server 2019, same results across the board.

**Comment by zmb3** [comment]
Thanks for the info! This may be the first time we've seen per-user CAL used. We're tracking this and will work to have a fix out soon.

**Comment by zmb3** [comment]
Closed by #15643
