### ISSUE TITLE
Provide an easy way to deploy and scale macOS builders

### ISSUE THREAD

**Issue by fheinecke** [gravitational/teleport#13155]
- [ ] Provide an easy way to deploy Drone macOS builders on AWS.
- [ ] Build AMI using Packer.
- [ ] Make sure builders are connected to a Cloud tenant.

Related issue we might want to tackle at the same time: https://github.com/gravitational/teleport/issues/8210

**Comment by zmb3** [comment]
See also https://github.com/gravitational/teleport/issues/4226, which may or may not make sense to do at the same time.

**Comment by r0mant** [comment]
This is no longer relevant as we're migrating to Github Actions.
