### ISSUE TITLE
Guide to managing Teleport audit logs via Datadog

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#13159]
## Details
See #2922 

### Category
- Improve Existing

**Comment by soudaburger** [comment]
I would like to add the use case, in case it's not apparent, of using Teleport Cloud.  Since we don't own the agents, getting the audit logs out of Teleport Cloud is not only extremely tedious, but also lacks documentation/support on then sending _those_ logs to Datadog, as an example.
