### ISSUE TITLE
Improve confusing error message

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#13178]
If user misconfigures certs on their proxy, and uses IOT mode, they get error that looks like this:

"Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.\n\tGet \"https://teleport.cluster.local/v2/domain\": x509: certificate is valid for [teleport.example.com](http://teleport.example.com, not 15312345135123531253125123531252315312513253125.teleport.cluster.local, Get \"https://teleport.cluster.local/v2/domain\": dial tcp 1.2.3.4:3024: connect: connection refused." service/connect.go:86

Instead, we should explain what is going on and how to fix it:

Node failed to establish connection to Teleport Proxy. We have tried the following endpoints:

* `teleport.example.com:443` - TLS certificate error. Certificate is invalid or not trusted. Fix the certificate to correct this error: [link to docs]
* `1.2.3.4:3024` - Connection refused. This is the alternative port we tried and it's not configured.

**Comment by zmb3** [comment]
See also https://github.com/gravitational/teleport/issues/11524

It will be a lot easier to provide an actionable error message if we know the user's intent.
