### ISSUE TITLE
Add support for Redis 7

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#13202]
What would you like Teleport to do?

Looks like recently https://github.com/go-redis/redis added support for Redis 7. After updating our go-redis fork we should be able to also support Redis 7.

**Comment by smallinsky** [comment]
Closing in favour  or https://github.com/gravitational/teleport/issues/33922

 Redis 7 is  is supported by Teleport by protocol downgrade from RESP3 to RESP2 but this approach  limits the RESP3 capabilities. To have full integration we need to implement RESP3  support in Teleport Redis Engine.
