### ISSUE TITLE
A user with permissions to create a token cannot create it in the web gui

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#13218]
Expected behavior:

A user with the `create` permission for tokens should be able to create a token in the web interface.

Current behavior:

The web interface complains that the user does not have the `update` permission when a user tries to create a token. It appears the web gui will create and then update. The same user is able to successfully do a `tctl create` command from the command line since that only issues an api call with the create verb.

![image](https://user-images.githubusercontent.com/37278/172232670-d676a1c8-b4cf-4eb6-b5be-8974b7128a9c.png)

Bug details:
- Teleport version 
- Recreation steps
- Debug logs

gz#5325

**Comment by marcoandredinis** [comment]
There's a difference between `tctl` and `web` clients:
- tctl uses `GenerateToken`
- web uses `UpsertToken`

`Upsert` requires both `create` and `update` verbs on the `token` resource
That's why we get this error

I'll open a PR to fix this
