### ISSUE TITLE
Add support for custom ports for tsh proxy db --tunnel

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#13210]
What would you like Teleport to do?

Right now if you use the default `tsh proxy db --tunnel` or `tsh proxy db` you get a random high level port to connect to. This goes with the Teleport Connect UI app as well. It creates a random high port for tunneling.

Ideally would be nice to set a custom port so that users do not have to constantly edit their DB UI or IDE tools to read the latest port.

What problem does this solve?

Solves dev problems of constantly editing IDE and DB UI tools for the random ports everytime a new tunnel is created.

If a workaround exists, please include it.

None at the moment. You have to start the tunnel to get the new port, then edit your connection string in your IDE or DB UI tool in order to connect by changing it to match the new port.

**Comment by Valien** [comment]
Additional context around this request can be found in the community slack thread here --> https://goteleport.slack.com/archives/CEZH6UL64/p1654536038205649

**Comment by crielly** [comment]
Worth noting that `tsh proxy db` does provide a --port option, but it cannot easily be daemonized for background use. See https://github.com/gravitational/teleport/issues/13211

However, the teleport connect GUI tool doesn't provide any option to set a --port, so the port used is random and results in reconfiguring your IDE for each connection. Not an ideal workflow.
