### ISSUE TITLE
Sync EC2 Tags and Teleport Labels

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#13242]
Expected behavior:
Teleport will automatically detect and import EC2 tags as Teleport labels for SSH nodes, Applications, Databases, and Kubernetes clusters.

Current behavior:
Teleport does not detect and import EC2 tags as Teleport labels on the UI dashboard. After following documentation and restarting the instance it doesn't automatically populate. We would like an automative methods where EC2 tags are imported to Teleport as labels on the UI. Docs seem incomplete. 
<img width="856" alt="Screen Shot 2022-06-07 at 11 48 52 AM" src="https://user-images.githubusercontent.com/96448492/172438469-ad38a986-b22e-45dc-ae76-8b9e28a8c489.png">

```ubuntu@ip-172-31-22-153:~$ aws ec2 describe-instances --filters "Name=tag-value,Values=ninja" --region=us-west-1 | grep -i Tags -A 15
                    "Tags": [
                        {
                            "Key": "Cluster",
                            "Value": "ninja"
                        },
                        {
                            "Key": "Owner",
                            "Value": "owner_name"
                        },
                        {
                            "Key": "Name",
                            "Value": "proxy-auth"
                        },
                        {
                            "Key": "Delete",
                            "Value": "never"```

Bug details:
- Teleport version: v9
- Recreation steps:
# Follow our internal doc guide: 
https://goteleport.com/docs/setup/guides/ec2-tags/ 
- Debug logs:
Images above show the tags being modify on AWS, instance restarted but the labels not being updated on the UI.

**Comment by zmb3** [comment]
This is already implemented and will be out in the next release.
