### ISSUE TITLE
Integrate Teleport 2FA with sudo

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#13258]
What would you like Teleport to do?
Customer would like to see if we can integrate Teleport 2FA with sudo. If this is possible, enabling proper MFA integration through a remote sudo call, would require to write our own PAM module to handle it.

What problem does this solve?
Use case is literal: I knows there is a way to use Google Authenticator PAM to control SUDO.  Is it possible to provide this feature with Teleport?

If a workaround exists, please include it.
A possible alternative with Teleport functionality as it exists today is to use RBAC rules/access requests/etc to allow certain users to log into the root user directly.

gz#5337

**Comment by klizhentas** [comment]
@corkrean can help you to show how it could be done.

**Comment by programmerq** [comment]
I talked to @corkrean and he said that he had gotten Duo set up with pam via the duo docs site: [Duo Unix - Two-Factor Authentication for SSH with PAM Support (pam_duo)](https://duo.com/docs/duounix)
