### ISSUE TITLE
Eliminate Upsert pattern in resource access

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1326]
## Problem

Teleport core uses `upsert` pattern to manipulate its database. This creates a number of issues, some of them are cosmetic, but others are more serious (RBAC currently requires BOTH verbs to be present at the same time for _any_ of them to work: `create` and `update`). Also, updating a resource now requires `read` access because `tctl` tires to read it before updating, to avoid overriding by accident, see how `--force` flag is implemented.

## Outcome

Complete absence of `Upsert` word in any of the APIs we have internally, and usage of `insert()` and `update()`. 

* Insert would return an error if a duplicate exists.
* Update would return an error if a resource does not exist. (tricky: how to rename something?)

## Sub-tickets

The following tickets **must be closed** at the same time as this one:

* #1325 - Wrong error message when trying to update|create a resource
* #1324 - Wrong error message when 'read' access is denied to Auth Connectors

**Comment by benarent** [comment]
@kontsevoy I'm reviewing `P0` label, the two referenced issues are still open. Is this issue still relevant or should we close it / reprioritise ?
