### ISSUE TITLE
Add Machine ID troubleshooting guide

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#13325]
This guide should include, at a minimum:

- Information on generation counter errors
  - What they mean
  - How to identify them
  - Corrective actions (unlock bot when all is well)

**Comment by timothyb89** [comment]
Some topic ideas:
 * General bot usage
   * Generation counter lock. Why did it happen, how can it be resolved?
   * Bot certs expired, how to reset a bot?
 * Database access failures
   * Database not found = missing RBAC permissions to list databases
