### ISSUE TITLE
[v.9.0] /docs/pages/enterprise/workflow/ssh-approval-slack.mdx

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#13320]
## Details
Update Slack plugin example as it currently shows the older way of setting up the `teleport-slack.toml` file.

Example in current docs -- https://goteleport.com/docs/enterprise/workflow/ssh-approval-slack/#editing-the-config-file

````
# Optional Slack Rooms
recipients = ["team","devops"]
````

and new method:

````
[role_to_recipients]
"*" = "teleport"
````

### Category

- Improve Existing
- Remove Outdated

**Comment by ptgott** [comment]
Closed as completed
