### ISSUE TITLE
Error integrating with auth0: patrick.robinson@example.com is not a valid user name

### ISSUE THREAD

**Issue by patrobinson** [gravitational/teleport#1333]
While trying to integrate with Auth0 and Google, following a similar mechanism to this post https://gravitational.com/blog/aws-github-sso/, I'm getting the following error

```
Error while processing callback: 'patrick.robinson@example.com' is not a valid user name  file=web/apiserver.go:547 func=web.(*Handler).oidcCallback
```

I notice we are not passing any username field in but it's odd that's it's trying to use the email user

```
DEBU[0058] [OIDC] Claims: map[verified_email:true given_name:Patrick hd:example.com updated_at:2017-09-19T12:11:54.479Z user_id:oauth2|Gapps|106763322445143832582 iss:https://example.auth0.com/ email:patrick.robinson@hd:example.com clientID:example.com  nickname:patrick.robinson identities:[map[provider:oauth2 user_id:Gapps|01223 connection:Gapps isSocial:true]] created_at:2017-09-12T23:17:56.223Z app_metadata:map[roles:[teleport@example.com]] roles:[teleport@example.com] name:Patrick Robinson family_name:Robinson locale:en groups:[teleport@example.com ] sub:oauth2|Gapps|01223 aud:example.com]
```

**Comment by kontsevoy** [comment]
@patrobinson we should probably update the tutorial, but that blog post was written for an early preview of Teleport Enterprise. The standard OSS teleport only understands local usernames.

**Comment by patrobinson** [comment]
The way I had to work around this was to add a rule to auth0 to re-write my email address and strip out the `@example.com`. From looking at the code, it appears email is the only thing we know will be in the oicd claim but since an email will never be a "valid user name" it doesn't make sense to use it.

Should there be a seperate configuration option to choose a field in the claim for the users user name?

**Comment by kontsevoy** [comment]
@patrobinson this works natively in the enterprise AFAIK. @klizhentas can you please confirm? [meanwhile closing the issue]
