### ISSUE TITLE
Explain how OIDC/SAML connectors work in conjunction with certificate authorities

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#13347]
## Details

For example:
- Teleport does not create persistent local users
- All information is in the certificate
- Temporary user entries are created for visibility/auditing
- If an OIDC provider is down, a second one can be used

CC @klizhentas 

### Category
- Improve Existing

**Comment by ptgott** [comment]
@klizhentas Does this apply to SAML as well?

**Comment by klizhentas** [comment]
@ptgott yes, same rules apply to SAML
