### ISSUE TITLE
allow providing the join token from command line, and environment variable.

### ISSUE THREAD

**Issue by james-lawrence** [gravitational/teleport#1334]
I might just be missing it in the documentation but doesn't seem like there is a way to provide the join token from the command line or environment variable.

**Comment by kontsevoy** [comment]
you mean for a node to join a cluster? how about `teleport start --token=xxx`?

**Comment by james-lawrence** [comment]
ah perfect, I wonder if my version is out of date. I checked there as well. maybew i just missed it.
