### ISSUE TITLE
Error when trying to access tctl

### ISSUE THREAD

**Issue by sfulham** [gravitational/teleport#13369]
Expected behavior:
`tctl status --insecure` to return it's proper output.

Current behavior:
`[CLIENT]       Cannot connect to the auth server: failed direct dial to auth server: Get "https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech": stopped after 10 redirects
	Get "https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech": stopped after 10 redirects, failed dial to auth server through reverse tunnel: Get "https://teleport.cluster.local/v2/configuration/name": Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech
	Get "https://teleport.cluster.local/v2/configuration/name": Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech.
Is the auth server running on "teleport.internalmediagroup.tech:443"?`

Bug details:
- Teleport version - 9.2.3
- Recreation steps
Install teleport in kubernetes, with --set-acme false, create a user, then login with tsh, then try to run `tctl status --insecure`
- Debug logs
`DEBU             Debug logging has been enabled. common/tctl.go:196
DEBU             No config file or identity file, loading auth config via extension. common/tctl.go:223
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/sfulham/.tsh/keys/teleport.internalmediagroup.tech/sfulham-x509.pem" valid until "2022-06-10 13:37:44 +0000 UTC". client/keystore.go:307
DEBU [KEYSTORE]  Reading certificates from path "/home/sfulham/.tsh/keys/teleport.internalmediagroup.tech/sfulham-ssh/teleport.internalmediagroup.tech-cert.pub". client/keystore.go:330
DEBU             Found active profile. proxy:https://teleport.internalmediagroup.tech:443 user:sfulham common/tctl.go:342
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/sfulham/.tsh/keys/teleport.internalmediagroup.tech/sfulham-x509.pem" valid until "2022-06-10 13:37:44 +0000 UTC". client/keystore.go:307
DEBU [KEYSTORE]  Reading certificates from path "/home/sfulham/.tsh/keys/teleport.internalmediagroup.tech/sfulham-ssh/teleport.internalmediagroup.tech-cert.pub". client/keystore.go:330
DEBU             Setting auth server to web proxy teleport.internalmediagroup.tech:443. common/tctl.go:384
DEBU             Connecting to: [{teleport.internalmediagroup.tech:443 tcp }]. authclient/authclient.go:50
DEBU             Attempting GET teleport.internalmediagroup.tech:443/webapi/find webclient/webclient.go:118
ERRO             Failed to resolve tunnel address Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech reversetunnel/transport.go:90
ERRO             Failed to resolve tunnel address Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech reversetunnel/transport.go:90
INFO [CLIENT]    "Cannot connect to the auth server: failed direct dial to auth server: Get \"https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech\": stopped after 10 redirects\n\tGet \"https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech\": stopped after 10 redirects, failed dial to auth server through reverse tunnel: Get \"https://teleport.cluster.local/v2/configuration/name\": Get \"https://teleport.internalmediagroup.tech:443/webapi/find\": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech\n\tGet \"https://teleport.cluster.local/v2/configuration/name\": Get \"https://teleport.internalmediagroup.tech:443/webapi/find\": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech.\nIs the auth server running on \"teleport.internalmediagroup.tech:443\"?" utils/cli.go:275
[CLIENT]       Cannot connect to the auth server: failed direct dial to auth server: Get "https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech": stopped after 10 redirects
	Get "https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech": stopped after 10 redirects, failed dial to auth server through reverse tunnel: Get "https://teleport.cluster.local/v2/configuration/name": Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech
	Get "https://teleport.cluster.local/v2/configuration/name": Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech.
Is the auth server running on "teleport.internalmediagroup.tech:443"?`

**Comment by GavinFrazar** [comment]
I was going to open an issue for this just now. I think I tracked the source of the problem down, will open a PR to fix tomorrow.
