### ISSUE TITLE
[docs] Explain template variables wherever they appear

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#13377]
## Details
Describe the documentation improvements you wish to see.

It is extremely common for various examples in the docs to include `{{internal.db_names}}` or other template system snippets. For folks newer to teleport, these look strange in isolation. For places where it is appropriate to have a reference to a templating system directive, there should be a note or link calling it out. Having a place with a comprehensive description of the templating engine might be a good place to link to (as outlined in #11263)

### Category
- Improve Existing

**Comment by zmb3** [comment]
How does this differ from #11263?
