### ISSUE TITLE
Add more items to our edition comparison table

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#13389]
## Details
Here are some comparison points between Teleport Cloud and Self-Hosted Enterprise that we should add to the edition comparison table in our FAQ:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/25250668/173131450-d218a6eb-e637-4acb-8584-2780daf022c9.png">

### Category
- Improve Existing

**Comment by ulysseskan** [comment]
Is this the comparison table that we are adding to or is it somewhere else?  https://goteleport.com/docs/faq/#how-is-open-source-different-from-enterprise

Suggestions:
* Link "metrics collection" to https://goteleport.com/docs/setup/reference/metrics/ so customers can get more details on what that means.
* Link "SOC 2" under Cloud to https://goteleport.com/docs/cloud/faq/#does-your-socii-report-include-teleport-cloud

**Comment by ptgott** [comment]
@ulysseskan That's the one! And that sounds good to me.
