### ISSUE TITLE
Add Architecture guides for each resource-specific Teleport service (and Machine ID)

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#13384]
## Details

Currently, the only guide in our Architecture section that takes a deep dive into a resource-specific service is our [Nodes guide](https://github.com/gravitational/teleport/blob/9bb07eabd2cca992fd8c08098d14d0513b674bea/docs/pages/architecture/nodes.mdx). We should add similar guides to the Database Service, Kubernetes Service, etc.

### Category
- Improve Existing

**Comment by zmb3** [comment]
Closing this, as we're rebuilding all of the Machine ID docs this quarter.
