### ISSUE TITLE
Desktop access: support May 2022 certificate-based auth changes

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#13419]
Microsoft released an update last month to harden the security of certificate-based logins.

With this update installed, Teleport still authenticates, but generates a warning in the event log.

```
The Key Distribution Center (KDC) encountered a user certificate that was valid but could not be mapped to a user in a strong way (such as via explicit mapping, key trust mapping, or a SID). Such certificates should either be replaced or mapped directly to the user through explicit mapping. See https://go.microsoft.com/fwlink/?linkid=2189925 to learn more.
```

It looks like MSFT will eventually enable "strict enforcement mode" (May 2023) which will likely prevent Teleport from working without updates to the certificates we issue.

https://support.microsoft.com/en-us/topic/kb5014754-certificate-based-authentication-changes-on-windows-domain-controllers-ad2c23b0-15d8-4340-a468-4d4f3b188f16

**Comment by zmb3** [comment]
From a quick read, looks like we have two options:

1. Manually link AD users to Teleport-issued certificates by setting the `altSecurityIdentities` attribute in LDAP. This is undesirable, because we would have to make updates per-user.
2. Update Teleport to issue Windows Desktop certificates with the new non-critical SID extension (OID `1.3.6.1.4.1.311.25.2`). The extension should be set to the value of the user's `objectSid`, which we can query via LDAP. For example, in my environment `objectSid` is an attribute of `CN=zac,CN=Users,DC=example,DC=com`.

**Comment by ibeckermayer** [comment]
Event has event ID 39 and can be found in the Event Viewer under Windows Logs > System

**Comment by ibeckermayer** [comment]
See the TODO heading in the description of https://github.com/gravitational/teleport/pull/19340 for the latest.
