### ISSUE TITLE
Migrate auth server API to HTTPS

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1342]
Currently the auth server operates via SSH-over-HTTP. This creates unnecessary difficulties when establishing trust, see #302

## Proposal:

The auth server API must run on HTTPS. 

## To be discussed

- Upgrades & backward compatibility (old clients?)
- How would this work with the planned migration to a 2-port system?

**Comment by aberoham** [comment]
Could this be closed out now that #1334 is done?
