### ISSUE TITLE
Teleport Environment Variables

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1343]
### Problem

Teleport sets five Teleport specific environment variables in all sessions:

```
SSH_TELEPORT_USER
SSH_SESSION_WEBPROXY_ADDR
SSH_TELEPORT_CLUSTER_NAME
SSH_TELEPORT_HOST_UUID
SSH_SESSION_ID
```
https://github.com/gravitational/teleport/blob/master/constants.go#L21-L34

To support #1327, this means users need to set `AcceptEnv SSH_*` in `/etc/ssh/sshd_config` which is too broad.

### Proposed Solution

Teleport specific environment variables should have a common prefix that doesn't clash with OpenSSH which limits the scope of how much users have to open OpenSSH.

Proposed ideas for a common prefix:

```
TELEPORT_*
SSH_TELEPORT_*
```

**Comment by kontsevoy** [comment]
Lets make all telport-specific vars start with `SSH_TELEPORT_`

**Comment by russjones** [comment]
@kontsevoy Now I recall the issue, two environment variables are causing problems:  `SSH_SESSION_ID` and `SSH_SESSION_WEBPROXY_ADDR`.

`SSH_SESSION_ID` is not an OpenSSH environment variable and `SSH_SESSION_WEBPROXY_ADDR` has an inconsistent prefix. These two should be called `SSH_TELEPORT_SESSION_ID` and `SSH_TELEPORT_SESSION_WEBPROXY_ADDR`.

**Comment by russjones** [comment]
Because the forwarding server does not support session joining at the moment, and the only other remaining use for the environment variables is for convenience purposes (like the `teleport status` command), I'm going to close this issue for now.

We can re-open and address this later if needed.
