### ISSUE TITLE
improve kubernetes agent docs for cloud

### ISSUE THREAD

**Issue by michaelnowin** [gravitational/teleport#13438]
Hi all,

Submitting a request around the [Kubernetes documentation](https://goteleport.com/docs/kubernetes-access/helm/reference/) for my prospect. Copy and pasting what they asked below:

"The only kubernetes configuration doc is this one. https://goteleport.com/docs/kubernetes-access/helm/reference/
In hindsight it is sufficient, I found other docs about configuration often assumed an ec2 setup for proxy/auth and access to teleport cli which does not work for k8s agent. Would be neat if under 'teleport cloud', there was a ref to any values.yaml for that section. Small detail though :slightly_smiling_face:"

**Comment by ptgott** [comment]
@michaelnowin We've restructured our Kubernetes docs since this issue was opened—is the prospect still having this issue?

**Comment by michaelnowin** [comment]
Hey @ptgott, don't believe so anymore. Apprecaite you getting to it!
