### ISSUE TITLE
App Access Support for gRPC 

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#13432]
**What would you like Teleport to do?**

Provide access to gRPC endpoints. 

**What problem does this solve?**

Teleport does not currently provide access to gRPC-based endpoints. 

**If a workaround exists, please include it.**

None

**Comment by zmb3** [comment]
This should work when https://github.com/gravitational/teleport/issues/10216 is completed.

**Comment by zmb3** [comment]
@corkrean are we good to close now that app access supports arbitrary TCP connections?
