### ISSUE TITLE
Update trusted cluster docs to mention multiplexing

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#13448]
## Details
The current trusted cluster docs state that both ports 443 and 3024 are needed for trusted clusters, which doesn't work when multiplexing is configured (as both `web_proxy_addr` and `tunnel_addr` should point to port 443)

### Category
- Improve Existing

**Comment by Nawaz027** [comment]
Hey @webvictim , I want to work on this issue. Can you please assign this to me?
Thanks

**Comment by webvictim** [comment]
Hey @Nawaz027 - if you'd like to work on this, please submit a pull request with the changes for review.

Our documentation style guide is here: https://goteleport.com/docs/contributing/documentation/style-guide/

Thanks!

**Comment by webvictim** [comment]
This doc update should **also** mention that for Teleport Cloud, you will need to use whatever the `ssh_tunnel_public_addr` is from the `webapi/ping` endpoint for the `tunnel_addr` in the trusted cluster config:

```
~ » curl -s https://tenant.teleport.sh/webapi/ping | jq -r .proxy.ssh.ssh_tunnel_public_addr 
tenant.teleport.sh:11696
```

**Comment by alexfornuto** [comment]
I believe this has been resolved since https://goteleport.com/docs/management/admin/trustedclusters/ no longer mentions port `3024`. If I'm wrong, please feel free to re-open and tell me what else needs to be adjusted.
