### ISSUE TITLE
Server Access cloud documentation remove `sudo` when running `tctl` on local machine

### ISSUE THREAD

**Issue by JanKaczmarkiewicz** [gravitational/teleport#13462]
## Details
[Server Access Getting Started Guide (cloud version)](https://goteleport.com/docs/server-access/getting-started/?scope=cloud) informs that we should run [tctl on local machine](https://goteleport.com/docs/server-access/getting-started/?scope=cloud#make-sure-you-can-connect-to-teleport).

The problem occurs when running:
```
sudo tctl tokens add --type=node | grep -oP '(?<=token:\s).*' > token.file
```
or
```
sudo tctl users add tele-admin --roles=editor,access --logins=root,ubuntu,ec2-user
```
on local machine.

It prints an error:
```
ERROR: lstat /private/var/lib/teleport: no such file or directory
```

We should run these commands without `sudo`.
I think we should update documentation in these steps. 

I am running MacOS Monterey v12.4 Apple M1 Pro. 
tctl version: Teleport Enterprise v9.3.3 git:v9.3.3-0-g5fc41416c go1.17.10

### Category
- Improve Existing

**Comment by Nawaz027** [comment]
Hey @JanKaczmarkiewicz , I want to work on this issue. Can you please assign this to me?
Thanks!

**Comment by JanKaczmarkiewicz** [comment]
Hi [Nawaz027](https://github.com/Nawaz027) 
You are welcome to submit a PR and we will review it if we haven't already worked on the issue.

useful resources:
* https://goteleport.com/docs/contributing/documentation/style-guide/
* https://github.com/gravitational/teleport/blob/master/CONTRIBUTING.md#contributing-a-patch
