### ISSUE TITLE
Failed to join node / view tokens with default config

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#1348]
I'm on `v2.3.0-8-g481ef94` (latest master at the time of writing).

Following Quick Start guide, starting teleport from scratch (no config file or previous state):

```
[vagrant@node-1 ~]$ sudo ./teleport start
```

After that, an attempt to join a node fails with:

```
[vagrant@node-2 ~]$ sudo ./teleport start --roles=node --token=775ccbf23fab7cd4f1807a03d9f8e896 --auth-server=192.168.121.127:3025
ERRO [Node] failed to join the cluster: access denied to 'f12ae7cb-6679-41e3-828c-7805246ac656': bad username or credentials  file="service/service.go:622" func="service.(*TeleportProcess).RegisterWithAuthServer.func1"
```

And the corresponding error on the auth server:

```
ERRO token validation error: failed to validate: kind: kind is required,spec: spec is required,name: name is required  file="auth/tun.go:594" func="auth.(*AuthTunnel).passwordAuth"
```

Also, listing tokens also fails. This happens right after clean start, even before a join attempt:

```
[vagrant@node-1 ~]$ sudo ./tctl tokens ls
failed to validate: kind: kind is required,spec: spec is required,name: name is required
```

**Comment by lcaflc** [comment]
+1 got the same issue.

**Comment by wdlgithub** [comment]
+2 got the same issue.

What's the manual way to fix this ?

**Comment by lcaflc** [comment]
The quick way is to setup a static token in configuration (https://gravitational.com/teleport/docs/2.3/admin-guide/#adding-nodes-to-the-cluster) and use it for other nodes to join the cluster.

**Comment by wdlgithub** [comment]
ths, got it

**Comment by wdlgithub** [comment]
ths, got it
