### ISSUE TITLE
Document cluster upgrade 

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1350]
### Problem

We don't have documentation on the recommended safe way to upgrade a cluster. This leads to customers and developers performing ad-hoc upgrades which sometimes work and sometimes don't work.

* Develop proper practice, may be even ansible example script that demonstrates upgrade on AWS.

**Comment by klizhentas** [comment]
Passing this on to @kontsevoy and making this as a documentation ticket, wrote working example here:

https://github.com/gravitational/teleport/pull/1664/files
