### ISSUE TITLE
Tests occasionally fail with "directory not empty" during temp. dir cleanup

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#13501]
Both unit and integration tests sometimes fail when trying to cleanup temporary directory created for Teleport data with error similar to:

```
TempDir RemoveAll cleanup: unlinkat /tmp/TestExecLongCommand825667642/002/log/upload/streaming/default: directory not empty
```

Most likely this happens because "filesession" session uploader keeps writing even after being closed leading to this race condition.

There are a few ways we can fix this:

- Ensure there are no writes after the session uploader is closed.
- Use "discard" session uploader in all tests that don't actually test session recording instead of filesessions.
- Use sync recording which bypasses disk?

Option 2 is likely easier to implement so we can start with it but it probably wouldn't be a complete solution. Investigate and come up with a way to fix it once and for all.

**Comment by ibeckermayer** [comment]
You can find some specific tests that tend to fail like this by following this link:

https://github.com/gravitational/teleport/issues?q=is%3Aissue+is%3Aopen+label%3A%22flaky+tests%22+%3A+directory+not+empty

**Comment by zmb3** [comment]
I think we got most of these - if not, let's open new issues for the specific tests that fail with this error.
