### ISSUE TITLE
A feature to Pause moderated sessions 

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#13510]
What would you like Teleport to do?
Implement a feature that pauses the ongoing moderated session when the moderator switches the tab to a different one

What problem does this solve?
To ensure that the session is actually being observed

If a workaround exists, please include it.
Currently no workaround exists.

gz#5536

**Comment by dmsergeevN26** [comment]
@zmb3 That's a good point. Haven't thought about the cli. MFA based presence could work, I think.
