### ISSUE TITLE
API to flush the Teleport cache

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#13527]
What would you like Teleport to do?
Offer a way to flush the Teleport cache using an API endpoint.

What problem does this solve?
Easier method to flush the Teleport cache for troubleshooting and rejoining when needed. Removes the need restart the service to flush the cache.

If a workaround exists, please include it.
Log in to the node and manually flush the cache.

Notes from discussions so far:
Teleport has provided customers with debug builds capable of this in the past.  It's a fairly simple thing to add.  Ex: [70bf7883f2a99cf32e36ea02807d676696d74772](https://github.com/gravitational/teleport/commit/70bf7883f2a99cf32e36ea02807d676696d74772)

**Comment by portswigger-tim** [comment]
Even a tctl command would be helpful.

**Comment by zmb3** [comment]
Also requested in #4182, this is not planned at the moment.
