### ISSUE TITLE
`TestListResources` is flaky

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#13548]
### Relevant Snippet
```bash
Nics-MacBook-Pro:teleport nklaassen$ go test github.com/gravitational/teleport/api/client -run TestListResources --count 1000 --failfast
--- FAIL: TestListResources (0.01s)
    --- FAIL: TestListResources/DatabaseServer (0.00s)
        client_test.go:527:
                Error Trace:    client_test.go:527
                Error:          Received unexpected error:
                                rpc error: code = Internal desc = unexpected EOF
                Test:           TestListResources/DatabaseServer
FAIL
FAIL    github.com/gravitational/teleport/api/client    6.899s
FAIL
```

CI Logs:
- https://console.cloud.google.com/cloud-build/builds/c73e4d67-4567-443e-b47e-84ec07adef47;step=0?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/6dd339aa-ffa9-466c-89c1-116b1e287ac4?project=ci-account

**Comment by greedy52** [comment]
Could related to https://github.com/grpc/grpc-go/issues/5358

With the window size workaround mentioned in the above post, I run `-count=10000` without any failures.

**Comment by zmb3** [comment]
This is waiting on grpc-go release 1.49.0

**Comment by zmb3** [comment]
We're now on grpc-go 1.51.0 and I've run about 10K iterations without a failure, so I'm going to call this fixed.
