### ISSUE TITLE
Can't Login via tsh login

### ISSUE THREAD

**Issue by Nicknakin** [gravitational/teleport#13542]
Expected behavior:
Successful Login

Current behavior:
Login fails, error is thrown

Bug details:
- Teleport version
Teleport v9.3.6 git:v9.3.6-0-g83544812d go1.17.11

- Recreation steps
sudo tsh login --proxy=*example.proxy.server:####* --user=*user* -d

- Debug logs
ERROR REPORT:
Original Error: trace.aggregate connection closed before server preface received
Stack Trace:
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:1168 main.onLogin
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:764 main.Run
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:361 main.main
	/opt/go/src/runtime/proc.go:255 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: connection closed before server preface received

**Comment by zmb3** [comment]
Hi @Nicknakin - can you add some context to help us help you?

Is this a first time setup or was this working previously? If it was working, what changed in the environment recently?
