### ISSUE TITLE
`TestAppServersHA/RootServer` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#13568]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/db1e87f4-7b8b-4d36-8c49-a983215a3cd4?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/8714fdc9-23e7-4707-b170-c6f6337c7dbb?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/b8047da9-c5af-44e4-90ee-6493bd9aa5d2?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/86514bdf-0b24-4164-a22b-9899b1a1b7cb?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/645fc813-e29b-4e07-bd54-be76aecaf5d6?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/b96e4750-e8dd-42da-8f79-c6d759f9b280?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/ffcdb98f-e903-4427-8e0e-99b98ee50ab9?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/fbcb9b93-2620-41d2-a535-e459b2970029?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/d15d59af-37d8-44d1-8460-585e0a1bfa99?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/88816b2c-f1ed-487b-b204-5f24417c225d?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/7dd5bc9c-62a1-4e5a-817c-59b4d40bf124?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/1472c9cc-1309-4b11-ba48-c17d167c4eb4?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/a67a39d0-bf51-4554-927e-1ebf0c8ce1d3?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/920bafa2-91f1-4020-8334-7b10c7160f42?project=ci-account

#### Relevant snippet

```
    app_integration_test.go:711: 
        	Error Trace:	app_integration_test.go:711
        	            				app_integration_test.go:720
        	            				app_integration_test.go:764
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 500
        	Test:       	TestAppServersHA/RootServer
```

**Comment by nklaassen** [comment]
I'm seeing unexpected code `302` rather than `500` in the description. This has killed at least 2-3 of my ci runs today.

**Comment by jakule** [comment]
I was looking into this test a few days ago. I was able to find 3 issues there:
1. `expected 200, actual 302` - this is caused by a logic in the application access https://github.com/gravitational/teleport/blob/66a676eb736dd8d6cbdabb7d0df08ae83a31fd58/lib/web/app/handler.go#L220-L225
I was able to "fix" that by re-trying from the test
2. `expected 200, actual 500` - happens when there are no Teleport backends that can response to a request.
3. `websocket: bad handshake` -  no idea why this happens.

I think that we should start by splitting this test into a few smaller one as currently this one test does to much and debugging takes too much time.

**Comment by ibeckermayer** [comment]
> I think that we should start by splitting this test into a few smaller one as currently this one test does to much and debugging takes too much time.

@jakule thanks for looking into it, that makes sense to me. Is that something you want to take on, or would you prefer to punt to @gabrielcorado (who appears to be the original author)?

**Comment by jakule** [comment]
@ibeckermayer I'd be more than happy to fix at least the `302` error, but I'm not sure how the correct fix should looks like. 
1. Why an authentication failure redirects users to `/web`? Shouldn't we just return 4xx response with either access denied, bad request or something similar?
2. If the session doesn't exist shouldn't we wait until the session appear? This is not as simple as it sounds. Potential attacker could open a bunch of connections knowing the server won't close them for a while, but returning `302` also sounds wrong, as the session could be created by one process, but it's not propagated anywhere else. Then the first few requests will be redirected to launcher. I know that we do something like that in a few other places.
3. If we're fine with eventual consistency then we should add retry to the test.

Any thought? @smallinsky @gabrielcorado

**Comment by zmb3** [comment]
On latest master I can't get a single clean run locally. I went back to the commit before proxy peering was merged (ff4c3074536047dcd11d5f313861406db797e70c) and it passed for me first try.

Not enough samples to be certain, but usually when things start acting up it's due to a large PR that changed some subtle behavior, and proxy peering was an enormous change.

cc @dboslee @NajiObeid

**Comment by NajiObeid** [comment]
I'll look at it first thing on monday

**Comment by ibeckermayer** [comment]
@NajiObeid I ran each of your listed commits like
```
go test -count=3 -run ^TestAppServersHA$ github.com/gravitational/teleport/integration
```
(with the `"LeafServer"` test commented out) and got:

1- passed
2- passed
3- passed
4- passed

Is there some other way I should run them in order to better simulate the CI environment?

**Comment by dboslee** [comment]
I also had the tests pass on each of those commits. I left the `LeafServer` test in for these runs.
```bash
go test -run TestAppServersHA ./integration -count 5
```

**Comment by zmb3** [comment]
I struggle to run any of these locally due to the amount of open file descriptors they require. What on earth needs to open so many files?

**Comment by ibeckermayer** [comment]
@NajiObeid Interesting that behavior is consistent on individual machines but inconsistent across machines.

@zmb3
> I struggle to run any of these locally due to the amount of open file descriptors they require. What on earth needs to open so many files?

👆 seems like our best lead. How do you know its too many file descriptors?

**Comment by zmb3** [comment]
> 👆 seems like our best lead. How do you know its too many file descriptors?

Because the error is "too many open files."

This is not the same error we see in CI. macOS ships with a notoriously low open fd limit. I could increase it (and I swear I have in the past), but it still bothers me that you can't buy a new mac, put Go and teleport on it, and expect the tests to pass without changing system defaults.

**Comment by smallinsky** [comment]
The flakiness was probably caused by `t.Parallel()` call in integration tests flow: https://github.com/gravitational/teleport/blob/branch/v10/integration/app_integration_test.go#L730  where it was fixed on master branch by https://github.com/gravitational/teleport/pull/13867 but never backported to v10.

**Comment by ibeckermayer** [comment]
@smallinsky Hopefully that takes care of most of the flakiness. 

I did some investigating and see that #13867 was merged on June 25, but I encountered the same problem in [this](https://console.cloud.google.com/cloud-build/builds/88816b2c-f1ed-487b-b204-5f24417c225d?project=ci-account) CI run on June 27. So I think we should leave the issue open for now.

Still, the vast majority of the recorded failures are on branch/v10 (though that could be selection bias, since its mostly me recording them and I'm mostly trying to merge stuff into v10).

**Comment by zmb3** [comment]
@gabrielcorado @russjones we're good to close this one now, right?

**Comment by ibeckermayer** [comment]
I encountered this one again in a v10 backport

- https://console.cloud.google.com/cloud-build/builds/352de529-85e5-42dd-8ac1-0eefee0c0ddd?project=ci-account

```
        --- FAIL: TestAppAccess/TestAppServersHA/RootServer (17.02s)
        	Test:       	TestAppAccess/TestAppServersHA/RootServer
        	            	actual  : 500
        	            	expected: 200
        	Error:      	Not equal: 
        	            				app_integration_test.go:681
        	            				app_integration_test.go:635
        	Error Trace:	app_integration_test.go:626
    app_integration_test.go:626: 
```

**Comment by greedy52** [comment]
Same on master:
https://console.cloud.google.com/cloud-build/builds/a6b7fbac-edc7-4524-ab1f-e2e8f512e911?project=ci-account

**Comment by GavinFrazar** [comment]
on v18 backport: https://github.com/gravitational/teleport/actions/runs/17748311834/job/50438208211

```
    appaccess_test.go:1088: 
        	Error Trace:	/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1088
        	            				/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1096
        	            				/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1126
        	Error:      	Received unexpected error:
        	            	websocket: bad handshake
        	Test:       	TestAppAccess/TestAppServersHA/RootServer
```

**Comment by zmb3** [comment]
https://github.com/gravitational/teleport/actions/runs/17741005582/job/50421687186?pr=59144

```
   appaccess_test.go:1091: 
        	Error Trace:	/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1091
        	            				/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1100
        	            				/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1133
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 302
        	Test:       	TestAppAccess/TestAppServersHA/RootServer
```

**Comment by zmb3** [comment]
Got the bad handshake error today, which is different than the error I saw yesterday:

https://github.com/gravitational/teleport/actions/runs/17765308994/job/50487208089?pr=59084

```
    appaccess_test.go:1088: 
        	Error Trace:	/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1088
        	            				/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1096
        	            				/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1126
        	Error:      	Received unexpected error:
        	            	websocket: bad handshake
        	Test:       	TestAppAccess/TestAppServersHA/RootServer
```

**Comment by smallinsky** [comment]
https://github.com/gravitational/teleport/actions/runs/17768457898/job/50497877015

```
    appaccess_test.go:1084: 
        	Error Trace:	/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1084
        	            				/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1093
        	            				/__w/teleport/teleport/integration/appaccess/appaccess_test.go:1126
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 302
        	Test:       	TestAppAccess/TestAppServersHA/RootServer
```

**Comment by zmb3** [comment]
Fixed by https://github.com/gravitational/teleport/pull/59262
