### ISSUE TITLE
`TestIntegrations/RotateTrustedClusters` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#13569]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/8714fdc9-23e7-4707-b170-c6f6337c7dbb?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/52d7737f-1612-492d-8107-544ac2290439?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/86514bdf-0b24-4164-a22b-9899b1a1b7cb;step=0?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/1961a62a-ca72-4d9b-a299-a155e00ca833?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/53174f13-1099-4e82-a3f1-bd470c830422?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/9483aba0-169f-4eb9-9507-bbeceac00b42?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/6d8c7d85-6a28-4815-97db-3b38cda77ec3?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/caceac51-153c-4531-a45d-094369a35514?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/995804c8-bf92-4efc-8e56-b2ec22032f96?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/e71d86c9-be40-4600-8730-9d8bb581cde2?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/8b83b8d2-44bb-4624-8956-4306b95e4c00?project=ci-account

#### Relevant snippet

```
    integration_test.go:4260: 
        	Error Trace:	integration_test.go:4260
        	            				integration_test.go:4311
        	            				integration_test.go:97
        	Error:      	Condition never satisfied
        	Test:       	TestIntegrations/RotateTrustedClusters
        	Messages:   	failed to converge to phase "update_servers"
2022-06-15T18:21:51Z DEBU             Tracer completed github.com/gravitational/teleport/integration.testRotateTrustedClusters in 41.678114775s. utils/utils.go:121
    --- FAIL: TestIntegrations/RotateTrustedClusters (41.68s)
```

**Comment by ibeckermayer** [comment]
The first four failures have
```
failed to converge to phase "update_servers"
```
and the fifth has
```
failed to converge to phase "standby"
```

**Comment by ibeckermayer** [comment]
Oh god, oh no. It's back.
```
        	Test:       	TestIntegrations/RotateTrustedClusters
        	            	database is closed
        	Error:      	Received unexpected error:
        	            				/workspace/integration/integration_test.go:97
        	Error Trace:	/workspace/integration/integration_test.go:4399
```
Looks like a new problem though.

https://console.cloud.google.com/cloud-build/builds/e4d4900f-6b78-45a3-8cb8-0e08e5ddf80a?project=ci-account

**Comment by zmb3** [comment]
v10 hit: https://console.cloud.google.com/cloud-build/builds/db470808-f723-4c98-8942-c0310584387c;step=0?project=ci-account

**Comment by ibeckermayer** [comment]
on master: https://github.com/gravitational/teleport/actions/runs/3849572272/jobs/6558723375

**Comment by zmb3** [comment]
Closing since there have been no recent reports
