### ISSUE TITLE
`TestAgentForwardPermission` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#13565]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/316c920e-a387-4484-b887-df35f9bddb20?project=ci-account

#### Relevant snippet

```
    testing.go:1090: TempDir RemoveAll cleanup: unlinkat /tmp/TestAgentForwardPermission3320884236/002/log/upload/streaming/default: directory not empty
--- FAIL: TestAgentForwardPermission (17.92s)
```

**Comment by zmb3** [comment]
I fixed this in `TestAgentForward`, so we can probably make the same changes to `TestAgentForwardPermission`.

See https://github.com/gravitational/teleport/pull/13166 for the fix.
