### ISSUE TITLE
After upgrading a node+client to 9.3.6 with 8.3.4 auth servers, we’re seeing Attempted to use Moderated Sessions with an Auth Server below the minimum version of 9.0.0.  

### ISSUE THREAD

**Issue by jdconti** [gravitational/teleport#13591]
Expected behavior: 

A 9.3.6 client and 9.3.6 node should work with an 8.3.4 auth backend without issue per https://goteleport.com/docs/setup/operations/upgrading/#component-compatibility.

Current behavior:
```
{
  "caller": "regular/sshserver.go:1796",
  "component": "node",
  "level": "error",
  "message": "Attempted to use Moderated Sessions with an Auth Server below the minimum version of 9.0.0.",
  "timestamp": "2022-06-16T17:53:29-04:00"
}
```

Bug details:
- Teleport version: 
  - node = 9.3.6
  - client = 9.3.6
  - auth = 8.3.4
- Recreation steps
  - Upgrade node and client without updating auth server. 
- Debug logs
  - Available upon request.

**Comment by Joerger** [comment]
@xacrimon It looks like this is caused by https://github.com/gravitational/teleport/pull/11872

Can we safely remove this check?

**Comment by Joerger** [comment]
@jdconti To work around this issue for now, you can upgrade Auth first, then Proxy and Node.

**Comment by zmb3** [comment]
This is officially an unsupported configuration that was not clearly defined in the docs.

We updated the docs with https://github.com/gravitational/teleport/pull/12487/files but missed backports to older releases. I'll get those opened.
