### ISSUE TITLE
Ability for tsh to query which version of Teleport is installed on nodes.

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#13597]
What would you like Teleport to do?
The user would like the ability to query which version of Teleport is installed on each node without manually sshing into each node to validate. 

What problem does this solve?
Avoids user from manually checking current Teleport version, this issue arose when we released “Teleport Security Update”. The user had to login to each node to query which version of teleport is installed. 

If a workaround exists, please include it.
As they add more nodes I have told them to add the following label to query Teleport Version. 
- name: version
    command: ["/bin/sh", "-c", "teleport version | cut -d ' ' -f 3"]
    period: 1h

**Comment by zmb3** [comment]
Related: #10465

**Comment by zmb3** [comment]
@fspmarshall can we close this now that we've fixed RBAC for the `tctl inventory --connected` command?

**Comment by fspmarshall** [comment]
We are in the process of rolling out an official way to do this via `tctl inventory ls`.  That command relies on instance heartbeats, which are currently disabled by default, but will become enabled for all users in a future release.  If you are using teleport cloud, they are already enabled for you.  If you have an on-prem teleport deployment you can enabled enable them now by setting the env var `TELEPORT_UNSTABLE_ENABLE_INSTANCE_HB=yes` on your auth servers (note: takes a couple minutes after enabling for all instances to show up).

Once you have instances heartbeats going, you can find outdated instances using the `--older-than` flag like so:

```
$ tctl inventory ls --older-than=v1.2.3
Server ID                            Hostname        Services Version Upgrader
------------------------------------ --------------- -------- ------- --------
1e6578b6-9530-448e-8013-d32641324abb old.example.com Node     v1.1.1  none
...
```

You can also get a quick summary of the state of versioning across your cluster using `tctl inventory status`:

```
$ tctl inventory status
Services:
  Proxy: 2
  Node:  2
  Auth:  1
Total Instances: 5
Versions:
 v1.1.1: 2
 v1.2.3: 3
Upgraders:
  unit: 2
  none: 3
```
