### ISSUE TITLE
Can't join/view sessions

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#13595]
Expected behavior:

A user with the `access` role or a role with `resources: *`, `verbs: *` and no deny rules should be able to view and join their own sessions - https://goteleport.com/docs/access-controls/reference/

Current behavior:

I cannot view my own sessions or join them.

Versions:

This doesn't work in master/v10 or v9.3.6.

**Comment by zmb3** [comment]
This might be related to @xacrimon's new RBAC changes.

**Comment by xacrimon** [comment]
Yep, this is something that I didn't check when I wrote the v9 RBAC moderated sessions engine. It previously always worked in v8 since you always had the ability to join sessions on nodes you could access. Somehow we didn't catch this in the v9 test plan. Fix PR up.
