### ISSUE TITLE
`TestHSMDualAuthRotation` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#13635]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/bf5dc298-970e-468c-b739-11b47347036f?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/d44b12f3-f37a-4835-a443-e3b5db10c712?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/143a9e10-c336-4dc4-baa5-3846cd40d7d3?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/1e717527-9d6e-482c-bce1-13182af4468d?project=ci-account
- 07.07.2022 -> https://console.cloud.google.com/cloud-build/builds;region=us-west1/e42873ae-6da5-4f76-a6f7-687771a0997f;step=0?project=ci-account
#### Relevant snippet

```
    hsm_test.go:76: 
        	Error Trace:	hsm_test.go:76
        	            				testing.go:1034
        	            				testing.go:1203
        	            				testing.go:1187
        	            				panic.go:500
        	            				testing.go:864
        	            				hsm_test.go:76
        	            				testing.go:1034
        	            				testing.go:1203
        	            				testing.go:1433
        	            				panic.go:500
        	            				testing.go:864
        	            				hsm_test.go:680
        	            				hsm_test.go:693
        	Error:      	Received unexpected error:
        	            	context canceled
        	Test:       	TestHSMDualAuthRotation
        	Messages:   	error while closing auth1 during test cleanup
--- FAIL: TestHSMDualAuthRotation (480.13s)
```

**Comment by nklaassen** [comment]
failures where the log includes `is not in dotted-tri format` should be fixed by https://github.com/gravitational/teleport/pull/14178

**Comment by nklaassen** [comment]
This is hopefully fixed now, it looks like we had no hits this week. Going to close this issue, please ping me directly if you see a failure.
