### ISSUE TITLE
a way to access all applications with their own CLIs

### ISSUE THREAD

**Issue by salehkhazaei** [gravitational/teleport#13654]
**What would you like Teleport to do?**
There are a lot of applications with expose certain port and one should work with their own CLIs (e.g. ArgoCD, cqlsh). So it would be really helpful if accessing them through Teleport would be possible. Also, this way it would be possible to access all other DBs which teleport doesn't support yet, thought teleport and have access management and basic access events recorded through teleport.

**What problem does this solve?**
- Accessing applications with their own CLIs.
- Accessing databases which teleport doesn't support yet (e.g. Cassandra)

**If a workaround exists, please include it.**
So in order to do so, it should be possible to create some sort of tunnel using tsh. we already have an [API access to applications through curl using teleport certificates](https://goteleport.com/docs/application-access/guides/api-access/). why not use that connection to build a tunnel to connect to the port the applications exposes using it's own cli?

Example:

> tsh app tunnel argocd 8443:443
Listening to 8443 ... (Press Ctrl+C to exit)

in another terminal:
> argocd login localhost:8443

**Comment by greedy52** [comment]
@salehkhazaei we are adding `tsh app proxy` in the coming Teleport 10 release.

Change:
- https://github.com/gravitational/teleport/pull/10509

Original feature request:
- https://github.com/gravitational/teleport/issues/10064

Let us know if this resolves your use case.

**Comment by salehkhazaei** [comment]
@greedy52 Yes, this definitely resolves our problems and changes the way we handle access management to our infrastructure.
Sorry for asking here, couldn't find it anywhere else, what's the estimate on v10 release date?

**Comment by salehkhazaei** [comment]
Thanks for your detailed response, it was very helpful.
Appreciate your efforts and we definitely going to use this feature and will get back to you if we had any feedback
Thanks :)

**Comment by salehkhazaei** [comment]
@greedy52 I've tried this with Teleport 9.3 running on the backend nodes and recent tsh client as you said.
Added the app in teleport with nc listening on the target port 
Here's my configuration for the app:
`
  - name: "test"
    description: "Test Port"
    uri: "tcp://targethost:2224"
    labels:
      env: "production"
`

NC command in target host:
$ nc -l 2224

The command to proxy :
tsh proxy app -p 2224 test

sending anything to the localhost:2224 would result in bad request and nothing is sent to the specified port:
`
ubuntu@******:~$ telnet 127.0.0.1 2224
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
abcd
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad RequestConnection closed by foreign host.
`

**Comment by greedy52** [comment]
@salehkhazaei `tcp` support in Teleport is currently in progress: https://github.com/gravitational/teleport/pull/13455

Until then, application support is at http level. If your target application is http based, on the server-side try
```
  - name: "test"
    description: "Test Port"
    uri: "http://targethost:2224"
    labels:
      env: "production"
```
