### ISSUE TITLE
Teleport roles not automatically upgrading to v5

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#13684]
Expected behavior:
According to the docs (https://goteleport.com/docs/access-controls/guides/moderated-sessions/?scope=enterprise#backwards-compatibility-with-server-access), modifying a v4 role in the Web UI automatically upgrades the role to v5.

Current behavior:
The Teleport v4 role is not automatically upgraded to v5 when edited via the web UI, leading to moderated sessions not applying.

Not sure if this is a docs or code bug but it has impacted a customer attempting to set up moderated sessions.

Bug details:
- Teleport version: 9.2.3
- Recreation steps
Attempt to modify a v4 role in the Web UI

**Comment by dmsergeevN26** [comment]
applies to 9.3.5 as well

**Comment by nklaassen** [comment]
@xacrimon was it expected for editing a role in the UI to upgrade the version? It doesn't seem to happen and I'm not aware of any code for it. If not I think this is just a docs issue and we should rephrase

**Comment by xacrimon** [comment]
It shouldn't. That would automatically change behaviour which isn't great, this should be edited.
