### ISSUE TITLE
Ability to between ssh to different host within Teleport Cluster

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#13697]
What would you like Teleport to do?

What I am looking for is a way to ssh between hosts inside the teleport cluster.
For example my user has a role granting access to host1 and host2. I login through the UI and SSH to host1. Then in the UI I type for example tsh ssh host2 and I get to host2.

What problem does this solve?

The use-case is to run Ansible from 1 host of the cluster and connect to other hosts inside the cluster. For context in some environments our operators SSH into the cluster using customer-provided laptops which don’t have tsh, ansible, ansible playbooks. So the idea is to connect to 1 host using the Web UI and run Ansible from there, using SSH to run Ansible is our preferred approach because it is our current way of doing it.

Machine-id is not able to be used, In our case Ansible is run by operators so they should use their own identity. It cannot be a machine-id identity or a static identity, it needs to be their own cert.

If a workaround exists, please include it.
No Workaround exist at this moment.

**Comment by zmb3** [comment]
This is supported today with headless authentication.

Here's a demo: https://www.loom.com/share/26e872843cde48ba83b4f00870104a9f
