### ISSUE TITLE
Teleport node User CA export

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1370]
### Problem

If you are running Teleport and OpenSSH on the same server, if you want to use the Teleport CA with OpenSSH you have to:

1. Connect to the host that has `tctl` and export your User CA.
1. Copy the User CA to the node running Teleport and OpenSSH.
1. Update `TrustedUserCAKeys` in `/etc/ssh/sshd_config`
1. Restart OpenSSH.

You have to do this because the CA is stored in the Auth Server backend. Teleport nodes can communicate with the Auth Server backend, but OpenSSH can not.

The above is for user certificates, for host certificates you have to do the following:

1. Connect to a host that has `tctl` on it and export your Host CA.
1. Copy the Host CA to your client.
1. Update `~/.ssh/known_hosts` or a global known hosts file.

Once again, you have to do this because while `tsh` can communicate with the Auth Server (via the proxy), OpenSSH can not.

### Proposed Solution

To make this process easier, Teleport nodes (who have access to the User CA) should be able to export the User CA. Then we can point Teleport nodes to a file (where `TrustedUserCAKeys` points) and it will periodically write it out to disk. This way we can make CA rotation easier as well.

This feature would also allow us to configure OpenSSH further in the future. For example `HostCertificate` once https://github.com/gravitational/teleport/issues/1327 is released.

The same applied to `tsh`, we use it to set the trusted host CA.

**Comment by programmerq** [comment]
The `/v1/webapi/auth/export?type=user` endpoint was implemented in #15491 and documented by #23560
