### ISSUE TITLE
Extend MOTD functionality to the Web UI

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#13724]
What would you like Teleport to do?
Use the message_of_the_day functionality introduced for `tsh login` and extend this to the Web UI.

What problem does this solve?
It allows Teleport admins to inform Web UI users of changes to the cluster, maintainance outages, and general instructions on usage as the log in to the cluster.

If a workaround exists, please include it.
None for Web UI

**Comment by russjones** [comment]
This should already be the case, but if it's not let's add this functionality to the Web UI.

**Comment by strideynet** [comment]
To what extent does the "Cluster Alert" functionality complete this ticket? Is this supposed to replace motd for this kind of usage where an admin wants to show a message to their users ?

**Comment by russjones** [comment]
I don't think the Cluster Alert will do it. MOTD is often reasonably long which won't fit into a cluster alert. Also it shouldn't be dismissible.
