### ISSUE TITLE
DB tctl auth sign should have the RBAC example

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#13768]
## Details

These docs should have RBAC example required to allow user to sign:

https://goteleport.com/docs/database-access/reference/cli/#tctl-auth-sign

Right now users don't have the understanding of the RBAC role

**Comment by GavinFrazar** [comment]
User must be able to impersonate the db service: impersonate role "Db" and user "Db".

**Comment by GavinFrazar** [comment]
Related #12910
