### ISSUE TITLE
Delete connector problem.

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1378]
When deleting a SAML connector via the Proxy UI, the delete button incorrectly fires the delete OIDC connector URL (see attached screenshot).

[Screenshot](https://drive.google.com/open?id=0Bw7L7BB1mhpZbkxPdF9zRG1tSVE)

**Comment by alex-kovoy** [comment]
closed by https://github.com/gravitational/teleport.e/pull/26
