### ISSUE TITLE
Node fails to join with self-signed certificates

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#13781]
_Umbrella: Improve user experience for users trying teleport with self-signed certificates._

The node can't join because of the x.509 cert connecting to proxy. Node has failed with confusing error message:

```
Failed to resolve tunnel address Get "https://teleport.domain.com:443/webapi/find": x509: certificate signed by unknown authority reversetunnel/transport.go:90
```

In this case, the error message should have been (with a proper guide linked)

```
Failed to connect to the target proxy. Error: x509: certificate signed by unknown authority. Your proxy certificate is not trusted or expired. Please update certificate or follow this guide for self-signed certs: https://goteleport.com/docs/getting-started/self-signed#node
```

Please write the guide and update the section with the systemd unit to have insecure flag if running on Linux, or with helm chart for agent.

Don't forget to add `sudo systemctl daemon-reload` and `systemctl restart teleport.service` in the guide.

**Comment by GavinFrazar** [comment]
Fixing the error message was very straightforward, but I don't think I quite understand the scope of this "self-signed" guide. Should this "guide" just explain:
* the purpose and meaning of  the `--insecure` flag with `teleport start`
* why you shouldn't use `--insecure` in production
* link to docs on on how to get certificates set up properly

It seems to me that if the guide explains how to setup teleport services as well, we'd just be rehashing what is already explained in the other getting started guides.

**Comment by GavinFrazar** [comment]
Reopening pending doc update. I forgot that putting `Closes #X` will close the issue.  Planned to update the docs in a separate PR to simplify reviews.
