### ISSUE TITLE
Web UI Open SSH connection feature

### ISSUE THREAD

**Issue by papiveron** [gravitational/teleport#1379]
Hi,

Where can we find a good documentation of Web UI Open SSH connections feature?

How does it works? ssh connections are initiated from the proxy.... Are they normal ssh connections (port 22) or it works only through teleport? How about private key authentication method of ssh in this case?

Where can we find a detailed explanation of the feature please? I checked the CHANGELOG file but there is nothing. 

Regards,
Eugène NG

**Comment by kontsevoy** [comment]
@papiveron first, read this (to prepare OpenSSH servers to authenticate Teleport users):
https://gravitational.com/teleport/docs/2.3/admin-guide/#using-teleport-with-openssh

Then just start using the WebUI.
