### ISSUE TITLE
Trusted clusters in v2.3.x

### ISSUE THREAD

**Issue by papiveron** [gravitational/teleport#1381]
Hi,

I moved to teleport 2.3.1, and regarding the documentation it seems like trusted cluster management has changed, using `tokens` instead of `key_file`

When I add this line to the `auth_service`of my main cluster
```
tokens:
  - trusted_cluster:secret-token-to-add-new-clusters
```
I get the error below
```
role Trusted_cluster is not registered
```
Where is the subtility please? 

Regards,
Eugène NG

**Comment by kontsevoy** [comment]
@papiveron you get this error simply by starting teleport with an updated config file? or you're trying to do something else?

**Comment by papiveron** [comment]
I updated the config file by adding this line to my tokens list, the teleport service failed to restart, and I then try a foreground start and got the error.

**Comment by kontsevoy** [comment]
this seems to be a pretty serious regression, adding to our point-release next week. thanks for reporting this.

**Comment by papiveron** [comment]
So what's the work around? Sould I export CA keys and use key file with old(2.2.x) configuration directives?
Do trusted clusters feature works fine in 2.3.x?

**Comment by papiveron** [comment]
And I can even notice among others, that the command `tctl auth ls` is no longer available in v2.3.x, and there is no alternative to list clusters from the auth servers CLI as in the older versions.

**Comment by kontsevoy** [comment]
@papiveron correct. that command wasn't documented and it got removed, i.e. `tsh clusters` was the only supported way to list trusted clusters. We did not document `auth ls` because we knew that [resources](https://gravitational.com/teleport/docs/2.3/admin-guide/#resources) were coming.

Try:

```
$ tctl get clusters
```

**Comment by kontsevoy** [comment]
@papiveron [trusted clusters](https://gravitational.com/teleport/docs/2.3/admin-guide/#trusted-clusters) should work in 2.3.x First, let our engineering look into your problem.

**Comment by papiveron** [comment]
Yes I tried `tctl get clusters` as indicated in the  documentation and got and empty list. And from proxy when using `tsh cluster` I'm forced to indicate the `--proxy` flag and a `teleport user` and then asked for password and OTP token, and get error. I think it's a bit heavy for administration task...
```
admin@ip-10-99-20-76:~$ tsh clusters --proxy=localhost --insecure --user=eugene
WARNING: You are using insecure connection to SSH proxy https://localhost:3080
Enter password for Teleport user eugene:
Enter your OTP token:
483075
WARNING: You are using insecure connection to SSH proxy https://localhost:3080
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
admin@ip-10-99-20-76:~$ 
```
About the original trusted clusters problem, I export my CAs' keys and onfigure  `trusted_clusters` under auth section, and once I restarted the main proxy, I have no trusted cluster again in the main proxy web ui.
So trusted cluster doesn't work for v2.3.x in my case.

Regards,
Eugène NG

**Comment by papiveron** [comment]
In fact before teleport version update in all my clusters I had one main cluster and two trusted cluster.
 
- **trusted-cluster-a**
-  **trusted-cluster-b**

I updated all teleport nodes in the infrastructure.

I change the name of the first rusted cluster from **trusted-cluster-a** to **trusted-cluster-new**, and emptied the data_dir `/var/lib/teleport` because this cluster was failing to start again due to bad credentials issue. So after doing a `rm -rf /var/lib/teleport/*` the cluster restart good with a new name. I then rexport the cluster ca and copy it to main cluster.

I change nothing on the second trusted cluster except the teleport version update.

Af all this, I also restart teleport service on main proxy, and as I told in my previous message, I did not see again my trusted cluster in the drop-down box.
Now after a few time I can see again the other trusted cluster **trusted-cluster-b** but still don't the trusted cluster **trusted-cluster-new** in the drop-down box main proxy web ui.
I even reexported the `main` cluster ca and copy it to **trusted-cluster-new** (it generates the same file as the main cluster name did not change) and restart services all side, but stiil don't my trusted cluster **trusted-cluster-new** in the main proxy webui.

I didn't succeed to troubleshoot.

Regards.
Eugène NG

**Comment by papiveron** [comment]
Hi,

Thank for your answer, because with the old method consisting of export CA certificate,  every new cluster can"t be trusted by the proxy.

So what to do now to use Trusted Cluster static token feature? Will you roll out a new release?

Regards,
Eugène NG

**Comment by papiveron** [comment]
Do you know why I don't see new trusted cluster in the main cluster proxy web ui when using ca export method?

I just see old trusted clusters, but if I rename or create a new trusted cluster, it doesn't appear in the drop down box....

**Comment by papiveron** [comment]
I look at logs, and I can notice that  my new and renamed trusted clusters do not send tunel client pings to the main cluster proxy.

The one sending tunel client pings is the old (the one I didn't renamed since the upgrade of teleport to version 2.3.1)
```
Oct. 11 00:01:14 ip-10-179-0-4 teleport[26608]: level=debug msg="[TUNNEL CLIENT] pings \"main\" at 10.10.10.10:3024" file="reversetunnel/agent.go:336" func="reversetunnel.(*Agent).runHeartbeat.func1"
```
`10.10.10.10` is the ip address of my main proxy cluster.

I precise that all my teleport clusters use the same teleport vesion `v2.3.1`.

What could explain such behavior please?

Regards,
Eugène NG

**Comment by papiveron** [comment]
In the main auth servers I have this several times, but the cluster is working, except that I don't see my trusted clusters.

```
ct 11 10:43:07 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:43:07 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:43:27 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:43:27 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:43:47 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:43:47 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:44:07 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:44:07 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:44:27 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:44:27 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:44:47 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:44:47 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:45:07 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:45:07 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:45:27 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:45:27 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:45:47 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:45:47 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:45:59 ip-10-99-21-236 sudo[5913]: admin : TTY=pts/0 ; PWD=/home/admin ; USER=root ; COMMAND=/bin
Oct 11 10:45:59 ip-10-99-21-236 sudo[5913]: pam_unix(sudo:session): session opened for user root by admin(
Oct 11 10:46:07 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:46:07 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:46:27 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
Oct 11 10:46:27 ip-10-99-21-236 teleport[5886]: level=error msg=EOF file="sshutils/server.go:425" func="ss
```

**Comment by papiveron** [comment]
Here attached are systemd teleport status and configuration files of my three trusted cluster.
All this trusted cluster are running `auth`, `proxy`, and `node` services on the same machine. 
I renamed the configuration files for github upload compatibility.
These three servers use teleport `v2.3.1` and trust the same `main cluster`.
As you can see only the cluster `ca-trusted3` is pinging the `main cluster proxy` host (`34.249.81.23:3024`), and thus cans be seen in the main web gui.
The two other has a such behavior I don't understand, but services are running on them (`node`, `proxy`, `auth`)

Can some one look at these files content and tell me if he sees something I didn't noticed please? 
Maybe I should roll back to the old teleport version?

[ca-trusted-3.txt](https://github.com/gravitational/teleport/files/1375473/ca-trusted-3.txt)
[ca-trusted-2.txt](https://github.com/gravitational/teleport/files/1375474/ca-trusted-2.txt)
[ca-trusted-1.txt](https://github.com/gravitational/teleport/files/1375475/ca-trusted-1.txt)
[ca-trusted-3.yaml.txt](https://github.com/gravitational/teleport/files/1375476/ca-trusted-3.yaml.txt)
[ca-trusted-2.yaml.txt](https://github.com/gravitational/teleport/files/1375477/ca-trusted-2.yaml.txt)
[ca-trusted-1.yaml.txt](https://github.com/gravitational/teleport/files/1375478/ca-trusted-1.yaml.txt)

Thx.

**Comment by papiveron** [comment]
Hello,

I rolled back to version `v2.2.7` and got all my old nice features, with trusted clustering working fine.
