### ISSUE TITLE
Add the eksctl Helm guide in the discussion forum to the docs

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#13853]
## Details
In the discussion forum, there's a guide to deploying Teleport on EKS with `eksctl` and Helm: https://github.com/gravitational/teleport/discussions/13850

We should either add it to the docs (editing to fit the docs format) or incorporate it into our existing [AWS Helm guide](https://github.com/gravitational/teleport/blame/1254ec140bc390635f1bf329789bd5b7d3429885/docs/pages/setup/helm-deployments/aws.mdx).

### Category
- Improve Existing

**Comment by webvictim** [comment]
Just a standard warning about not doing this for things we don't have the time or inclination to support; it's not Teleport's responsibility to teach people to use `eksctl` or how to set up an EKS cluster correctly.

**Comment by ptgott** [comment]
How should we determine which third party services we should and shouldn't mention in guides? (I.e., what do you mean by "doing this"?)

**Comment by webvictim** [comment]
I agree that it's potentially a tough problem - we already mention `cert-manager` in that guide, for example. I'm drawing the line in my own mind based on these notions:
- Installing Teleport via Helm chart currently requires that you have an existing Kubernetes cluster of some kind to install to.
- If you don't have an existing Kubernetes cluster, you need to go and figure out how to get one.
- There are many existing guides online which give detailed instructions on how to get a Kubernetes cluster set up on your platform of choice.
- If we were to publish our own guide telling someone how to set up a Kubernetes cluster, we would then also be expected to tell them how to fix it when it doesn't work (which would likely require time to reproduce the failure on our side)

I'm of the opinion that Teleport is a complex product to configure and our support teams already give a lot of extra help around technologies that are only tangentially related to Teleport. It seems logical to try and keep the scope of everything in our docs restricted to things that we are both willing and able to assist people with. As such, we should avoid adding extra third party references unless absolutely necessary (as it was with `cert-manager` - arguably one of the only ways to reliably get highly-available, auto-renewing TLS certificates working for an HA Teleport setup inside Kubernetes)

**Comment by ptgott** [comment]
I'm not super familiar with eksctl, but one thing I think is interesting about the discussion forum post above is that it configures a starter cluster that can accommodate Teleport, e.g., with `cert-manager` installed. I think this would be useful for users who just want to demo Teleport quickly in a fresh setup, i.e., a more mature version of the [local Kubernetes guide](https://goteleport.com/docs/try-out-teleport/local-kubernetes/), which uses `minikube`. `eksctl` is also one of the tools AWS [mentions](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html) in its guide for getting started with EKS, so I think it makes sense to anticipate users wanting to configure it for Teleport.
