### ISSUE TITLE
race conditions and timeouts in unit-tests

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#1386]
See attached files for details.

[test-run-1.txt](https://github.com/gravitational/teleport/files/1376449/test-run-1.txt)
[test-run-2.txt](https://github.com/gravitational/teleport/files/1376450/test-run-2.txt)
~~[test-run-3.txt](https://github.com/gravitational/teleport/files/1376451/test-run-3.txt)~~ (dupe of #1341)
~~[text-run-4.txt](https://github.com/gravitational/teleport/files/1376452/text-run-4.txt)~~ (dupe of test-run-1.txt above)

**Comment by kontsevoy** [comment]
1st and 4th are the same, aren't they?

**Comment by kontsevoy** [comment]
Also, #1341 is related.
