### ISSUE TITLE
Add logging capabilities to 'Audit the Auditors'

### ISSUE THREAD

**Issue by campanamarco** [gravitational/teleport#13880]
What would you like Teleport to do?

- Add the ability to see when auditors review and play session recordings in the Teleport Audit Log
- Utilize Session Recording IDs, and Access Request Workflow of Auditor Roles, to provide a reasonable degree of traceability to audit the auditor 

What problem does this solve?

- For customers that have extremely tight compliance requirements, this would ensure that auditors are being held to zero trust, and only reviewing the session recordings that are pertinent to their required Audit at that time  

If a workaround exists, please include it.

- Customers can currently utilize the access request workflow and request a role that allows playback of session recordings.  This would will log and review when an auditor needs elevated permissions to play session recordings.  However, you cannot see which .tar file records they precisely reviewed

**Comment by russjones** [comment]
Add an event when a session recording is played back.

**Comment by ryanclark** [comment]
This landed in https://github.com/gravitational/teleport/pull/14302 and has been backported to v8, v9 and v10.
