### ISSUE TITLE
`TestProxyClientDisconnectDueToIdleConnection` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#13881]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/100687ce-308c-42fd-a908-57df24b82498?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/f8f450a0-48cf-46b9-82f7-f10c2832e9ce?project=ci-account: I couldn't find precisely where this one failed by looking at the logs 🤷‍♂️.
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/cb64eb71-300d-4640-8242-54c5bb7f5de5?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/0c6360e4-a907-4900-9c23-d8614b73a34e;step=0?project=ci-account

#### Relevant snippet

```
        	Test:       	TestProxyClientDisconnectDueToIdleConnection
        	Error:      	An error is expected but got nil.
        	Error Trace:	proxy_test.go:169
    proxy_test.go:169: 
```

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/d8b88f02-f48c-4aee-956b-699d45a4f075?project=ci-account

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds;region=us-west1/563f54de-10dd-4256-9fcc-7476ffbfcc1e?project=ci-account

**Comment by smallinsky** [comment]
Potential fix: https://github.com/gravitational/teleport/pull/15241/files

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/cf261a8d-a1b1-4c9b-8735-040cce4c0a87?project=ci-account

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/14898f69-9e0b-4d88-802c-afae7c7dcc29?project=ci-account

**Comment by zmb3** [comment]
Another v10 failure.

**Comment by smallinsky** [comment]
I have backpoted the [fix](https://github.com/gravitational/teleport/pull/15241) to v10 and v9. I will close the issue for now but please feel free to reopen when you see `TestProxyClientDisconnectDueToIdleConnection` toggle again.
