### ISSUE TITLE
tsh proxy db support for DB certs generation 

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#13922]
`tsh proxy db` should be able to start without dependency to manual `tsh db login` command call where user db  certs are generated. The `tsh proxy db` command can be extended by `--db-user`  `--db-name` flags and trigger certs generation flow internally. 
This change will allow to simplify DB UX flow from: 
```
tsh db login --db-user=alice instance1
tsh proxy db --tunnel --port=9999 instance1
```
to just one command:
```
tsh proxy db --tunnel  --port=9999 --db-user=alice instance1
```

**Comment by greedy52** [comment]
will also try to add `--cluster` flag.
