### ISSUE TITLE
`TestMux/Timeout` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#13933]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/060c6ce5-17fe-4acb-a97a-74df73df5e91?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/59f94b95-4db6-4c40-bbe4-ec180200d159?project=ci-account

#### Relevant snippet

```
=== RUN   TestMux/Timeout
    multiplexer_test.go:333: 
        	Error Trace:	multiplexer_test.go:333
        	Error:      	Expected value not to be nil.
        	Test:       	TestMux/Timeout
    --- FAIL: TestMux/Timeout (0.04s)
```

**Comment by zmb3** [comment]
Unfortunately this is still happening.

https://console.cloud.google.com/cloud-build/builds/d1b3a43b-a11e-4eb5-a531-fbda5d6c6e8a;step=0?project=ci-account

```
=== CONT  TestMux/Timeout
    multiplexer_test.go:347: 
        	Error Trace:	multiplexer_test.go:347
        	Error:      	Expected value not to be nil.
        	Test:       	TestMux/Timeout
```

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/b6d4dc8a-e98a-4d99-a8fe-9bdb7da4789e?project=ci-account

**Comment by zmb3** [comment]
Haven't seen this occur on GHA, so calling it fixed for now.
