### ISSUE TITLE
Provide a way to test connection to resource

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#13957]
## Problem

As a part of [Teleport Discover's](https://github.com/gravitational/teleport/pull/13440) "day 1" experience, on one of the final steps the UI wizard will ask the users to test connection to a resource (e.g. `tsh ssh` or `tsh db connect`) they have connected to the cluster. Teleport currently lacks a way for the web UI wizard to understand whether a particular connection was successful or not 
and why it failed (for example, due to RBAC checks).

## Solution

The proposal is to add an optional ability to enable a "request context" (or a "connection context") for a particular connection which will be passed through the entire connection flow. It will collect information about the connection at certain points and keep it in the backend which can then be queried via an API.

## UX

This can be implemented by providing an optional "request ID" flag to a particular connect command, for example:

```
$ tsh ssh --test-id=123 ubuntu@node-1
$ tsh db connect --test-id=456 --db-user=postgres postgres
```

## Implementation

When `--test-id` is provided, Teleport will propagate this request ID through the entire connection chain (by encoding it in the client certificate) and save "traces" in the backend at certain points. For the purposes of the initial Teleport Discover work, I propose to get started with just these:

- Connection was successful: save success trace.
- Connection failed with RBAC error due to missing principals (for SSH) or database users (for DB access): save a failure trace with recommendation on how to update the role to fix the issue that UI can then show.
- Connection failed due to other error: save a failure trace with the error message UI can show as-is.

When generating a command for a user to run to test the connection, the Discover wizard will pre-generate the request ID and include it in the command. The wizard will then use the API to poll for the traces related to this particular request and display it in the UI.

The wizard will recognize whether the trace represents a success (in which case it will tell the user connection was successful and move on to the next step or let them close the dialog) or a failure (in which case it will display the error and optionally provide some recommendation on how to fix).

## Backend

Backend structure can be similar to:

```
/connections/<connection-id>/<trace-id>
```

where each trace object could look like

```
{"id": "123", "success": false, "type": "rbac.principals", "message": "User alice's role is not allowed to connect to node-1 as ubuntu. Please update your user/role using tctl xxx command."}
```

We can tweak this structure during the implementation if we come up with a better format.

## API

A new web API (`lib/web/apiserver.go`) will be needed for the wizard to fetch all traces for a particular request ID:

```
GET /webapi/sites/:site/connections/:connection-id
// returns a list of all traces
```

## Prior work

Something similar was implemented as a part of our SSO tester: https://github.com/gravitational/teleport/pull/11508. Look at `SSODiagnosticInfo`.

**Comment by klizhentas** [comment]
@r0mant this looks great, but let's change it to `--trace` that will auto generate trace id with UUID. Request ID is already used for access requests and we want to avoid confusion.

Also, implementation question: We have work done that is already using opentracing by @rosstimothy and @gozer, can we somehow re-use their work or integrate with it?

**Comment by marcoandredinis** [comment]
Done https://github.com/gravitational/teleport/pull/14781
