### ISSUE TITLE
`TestPasswordTimingAttack` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#13951]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/78f20b76-7a89-4a86-ae35-06904e5ff5e4?project=ci-account

#### Relevant snippet

```
--- FAIL: TestPasswordTimingAttack (11.36s)
        	Messages:   	elapsed difference (14.175179455095122%) greater than 10%
        	Test:       	TestPasswordTimingAttack
        	Error:      	Should be true
        	Error Trace:	password_test.go:165
    password_test.go:165: 
```

**Comment by zmb3** [comment]
I thought Jakub had recently fixed this one.

**Comment by ibeckermayer** [comment]
This was on a `branch/v10`, so there's a chance that he did but it didn't get backported.

**Comment by jakule** [comment]
I checked, and my "fix" is on v10 https://github.com/gravitational/teleport/pull/13229.
I'm happy that at least it reduced the flakiness. However, I do have a few more ideas on how we can improve the test to make it more deterministic.

**Comment by r0mant** [comment]
Seems to fail in Github Actions as well: https://github.com/gravitational/teleport/actions/runs/3501198931/jobs/5864602152.

**Comment by zmb3** [comment]
Let's just remove this test. It's totally dependent on time, we'll never eliminate the flakiness, and it's not verifying correctness in any way.
