### ISSUE TITLE
Provide a way to hide the red recording button in Windows desktop sessions

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#13973]
**What would you like Teleport to do?**

By default, Teleport shows "Recording" or "Not Recording" at the top right of a Windows desktop session.

![image](https://user-images.githubusercontent.com/897821/176459593-ed8a628b-a07d-491a-a3b1-bfd57cee1bf0.png)

We've had a request from a prospect to be able to hide this constant warning that a session is being recorded - perhaps replacing it with a one-time warning that appears at the beginning of the session saying "Your session is being recorded, click here to accept".

According to the prospect "it's a question of user trust" - basically trying to win over old-school Windows administrators who will reluctantly accept change, but don't want to be constantly reminded that their sessions are being recorded.

**What problem does this solve?**

Winning over internal users.

**If a workaround exists, please include it.**

None currently.

**Comment by klizhentas** [comment]
In SSH, all sessions are always being recorded by default, @zmb3 it's OK just to completely remove this element from the UI, as this is up to system administrator.
