### ISSUE TITLE
`tsh` defaults to passwordless via Touch ID when viable

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#13979]
__What would you like Teleport to do?__

It's possible to know if Touch ID credentials are available, as is to check if the cluster is passwordless-capable/enabled. Putting those together means that `tsh login` could easily default to passwordless in those conditions.

Note that existing toggles still apply:

* Admins can set `passwordless: false` in their configs (which disables the behavior)
* Users can do `tsh login --mfa-mode=X` to change the behavior (anything but "auto" or "platform" disables the behavior).

This came up during passwordless conversations, but wasn't included in the preview.

__What problem does this solve?__

This enables a better login UX.

__If a workaround exists, please include it.__

Not applicable.

**Comment by tobiaszheller** [comment]
Closed via https://github.com/gravitational/teleport/pull/16964
