### ISSUE TITLE
`tsh` FIDO2 support for Windows

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#13985]
__What would you like Teleport to do?__

`tsh` should support FIDO2 on Windows, meaning it's linked and uses libfido2 in that environment.

Once this is done we could cleanup all plain-U2F support from `tsh`, so libfido2 is the only WebAuthn backend, which simplifies things a bit.

__What problem does this solve?__

This allows Windows to benefit from passwordless with `tsh`. Possibly unblocks the same features for Connect.

__If a workaround exists, please include it.__

Not applicable.

**Comment by tobiaszheller** [comment]
It is implemented using windows webauthn.dll, more details in: https://github.com/gravitational/teleport/pull/16360.
