### ISSUE TITLE
Can't tsh login to a Teleport 9 cluster with tsh 10

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#13988]
Expected behavior:
I'm unable to login to my 9 cluster, as my yubikey isn't being read. I downgraded to 9 and it worked. 

Current behavior:

```
Last login: Wed Jun 29 11:30:32 on ttys001
➜  ~ tsh login --proxy=teleport-9a.asteroid.earth --user=teleport-admin

Enter password for Teleport user teleport-admin:
Tap any security key
ccccccfvkjchkdfrbvhdjcrjknkhbnvtinfunejfdlvt
```

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by webvictim** [comment]
On a similar topic, Teleport 10 agents also won't join a Teleport 9 cluster. It's probably expected (IIRC Teleport 9 agents couldn't join a Teleport 8 cluster either) but we should be explicit about this in the release notes, because our `n-1` version guarantee doesn't apply.

**Comment by zmb3** [comment]
Starting with 10 agents will error when you attempt to connect to an old auth server.

(This can be bypassed with `--skip-version-check`)

**Comment by zmb3** [comment]
@codingllama what do you think?

If this is not an easy fix, we can just accept it and close the issue since it's not an officially supported configuration.

If the fix is straightforward, then we should try our best to make it work so that users don't have to keep changing their tsh version if they have old and new clusters to connect to.

**Comment by codingllama** [comment]
@zmb3 @benarent it seems to work fine for me:

```shell
# tab1
$ teleport version
> Teleport v9.3.6 git:v9.2.3-133-ga8e8b9179 go1.18.3
$ teleport start -c ./teleport.yaml
# ...

# tab2, tsh built from master
$ tsh login --proxy=zarquon --user=llama
> Enter password for Teleport user llama:
> Tap any security key or enter a code from a OTP device
# (works)
```

I think the problem here is not tsh <> teleport compatibility, but instead libfido2 isn't playing well with Ben's Yubikey. Ben, could you send me your Yubikey make/model, `tsh version`, try `tsh fido2 diag` and then try login with `-d`?
