### ISSUE TITLE
Create a `Payload.skip(n)` function for handling padding in Rust RDP client

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#13990]
```suggestion
            payload.seek(SeekFrom::Current(23))?;
```
Make sure you import the [Seek](https://doc.rust-lang.org/stable/std/io/trait.Seek.html) trait from the `std::io` as it allow you to use the `seek` method. 

By doing it this way you can avoid using the padding field in the struct and also remove it from here.

_Originally posted by @LKozlowski in https://github.com/gravitational/teleport/pull/13071#discussion_r893988832_

**Comment by zmb3** [comment]
This will be deprecated by IronRDP
