### ISSUE TITLE
Remove `namespace` from resources' `metadata`

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#14000]
Expected behavior:
The namespace field, judging by its name, should allow us to categorize resources.
Or having documentation on how it can be used

Current behavior:
The namespace field cannot be used to categorize resources.
Sometimes, we cannot even set its value to other than `default`

It should be removed from the code and documentation.

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
This is intentionally not documented and forced to `default` in many places. Teleport does not support namespaces and the remnants in the code exist only for compatibility reasons.
