### ISSUE TITLE
lib/teleterm: Remove daemon.Service methods that only delegate work to clusters.Cluster

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#14011]
The RPC handlers delegate most requests to `daemon.Service`. It makes sense that requests related to gateways go through the daemon as this is the struct that manages those gateways. However, is that necessary for other requests?

Methods like `daemon.Service.ListServers` appear to do nothing more than resolve the cluster based on the URI and then call an equivalent method on `clusters.Cluster` that does the actual work. It seems that the daemon layer could be completely skipped in this scenario. Does that layer help us accomplish anything?

It seems that the handlers themselves could orchestrate a couple of structs that do the actual work. In fact, handlers like `Login` and `GetAuthSettings` already do exactly that.

I thought that maybe the daemon layer could be useful for writing tests but [we can test the orchestration without starting a gRPC server](https://stackoverflow.com/a/42103776/742872).

**Comment by alex-kovoy** [comment]
You may want to check the cloud repo to see how mocks are used there (in case if it helps)
