### ISSUE TITLE
regression: newer 9.x tsh fails to list access requests on older 9.x backend

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#14015]
Expected behavior:

Any tsh 9.x.y client should be able to run `tsh request ls` against any teleport 9.x.y backend.

Current behavior:

tsh 9.3.4 encounters this error against a teleport 9.1.3 backend:

```
ERROR: This server does not implement this feature yet. Likely the client version you are using is newer than the server. The server version: 9.1.3, the client version: 9.3.4. Please upgrade the server.
unknown method GetAccessRequestsV2 for service proto.AuthService
```

Bug details:
- Teleport version - `Teleport v9.3.4 git:v9.3.4-0-g2d53086c0 go1.17.11`
- Recreation steps - run `tsh request ls` with a tsh 9.3.4 client against a 9.1.3 teleport cluster.

gz#5732

**Comment by Joerger** [comment]
This is fixed in v9.3.6+ by https://github.com/gravitational/teleport/pull/13459
