### ISSUE TITLE
Provide web API for downloading mTLS certificates for database access

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#14049]
When configuring self-hosted databases, users need to download Teleport's CA and generate cert/key pair in order to configure mutual TLS between Teleport and the database server. Right now we ask users to run `tctl auth sign` command to get these files.

In Teleport Discover wizard, instead of asking users to run auth sign (which would also require them to login first), we can provide them with a `curl` command that will make a request to web API to generate these files and download them.

```
GET /webapi/sites/:site/sign?hostname=postgres.example.com&ttl=365d&type=db
```

The API should return a tarball containing Teleport's CA (specifically, database CA for db access), and cert/key pair.

Check if we create audit log entry when these secrets are generated and add it if we don't (can do later).

The discover wizard should show the `curl` command to the user that will call this endpoint and download the mTLS secrets. We should use some cryptographically secure token to authenticate the client's request, which web UI will pre-generate and which will expire after first use. Look at `/webapi/host/credentials` that uses similar approach for node registration. See if we can reuse `ProvisionToken` or one of other `XXXToken` objects for this.

**Comment by zmb3** [comment]
I'm almost certain there was an issue for this same request with desktop access certs, but I can't find it.
