### ISSUE TITLE
Quickstart docs need to be more accurate on installing

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1404]
Feedback:

```
>sudo make install
response > make: Nothing to be done for `install'.

Had to run sudo ./install instead
```

**Comment by kontsevoy** [comment]
This is closed.

**Comment by jbritt1** [comment]
This is still an issue in the Admin Manual. Going through the steps today with v4.2.10 and was seeing same error with same resolution.

**Comment by kontsevoy** [comment]
@benarent I've reopened it, will take a look at it myself.

**Comment by benarent** [comment]
Thanks for reporting @jbritt1. I've gone ahead and hot-patched the Admin Manual, which now links to our Installation page.  ( going to keep this open, and close with an official docs PR )

**Comment by jbritt1** [comment]
> Thanks for reporting @jbritt1. I've gone ahead and hot-patched the Admin Manual, which now links to our Installation page. ( going to keep this open, and close with an official docs PR )

Looks good! Thanks all.
