### ISSUE TITLE
Separately configure expiry period on Access Requests

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#14040]
What would you like Teleport to do?

Access Requests currently expire based on the `max_session_ttl` defined in the role that is requested, i.e. if you request a role with a 10 minute TTL, the request will expire 10 minutes after you create it. 

The expiry time/period should be separately configurable, perhaps across a deployment so that all access requests expire X hours/mins after they are created if they are not actioned.

What problem does this solve?

The `max_session_ttl` on a role should not be used as the expiry period of an Access Requests as a short TTL on a role would not give enough time for an approver to see and action a request.

If a workaround exists, please include it.

N/A

**Comment by philip-teleport** [comment]
Related documentation issue: https://github.com/gravitational/teleport/issues/13927

**Comment by WilliamLoy** [comment]
Is there a status for when this issue might get picked up? 

Thanks!

**Comment by philip-teleport** [comment]
@zmb3 I've checked and this is fixed by the new `max_duration` option, see "Request expires in 3 days" below:

![Image](https://github.com/user-attachments/assets/84fd16c8-5b19-4131-8041-3da1d9d33fca)

This feature request can be closed as completed.
