### ISSUE TITLE
Allow ability to set default login name for tsh via config

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#14090]
What would you like Teleport to do?
Ability to configure default tsh login name via config file (non-env variable option). If one is not configured, when guessing a login for `tsh ssh` nodename it should never default to a name that is missing from the cert's list of logins. If a username has been specified explicitly as part of `tsh ssh username@nodename` or via environment variable or configuration file, that should be attempted even if absent from the cert, but when tsh is trying to infer the username to use it should restrict the possibilities to those in the cert.

What problem does this solve?
Customer would like to have an option for default login username outside of the environment variable or explicit callout with every tsh ssh  invocation.

If a workaround exists, please include it.
Set username as env variable, set alias, or explicitly call out the username.

**Comment by Vasfed** [comment]
Setting `TELEPORT_LOGIN` env variable helps for simple cases (tested on tsh 11 alpha, did not check minimum version where it was added), it has lower priority than explicit username in the command
