### ISSUE TITLE
Audit log missing `session.end` events for Kubernetes sessions

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#14120]
The presence of a `session.end` event is what the web UI uses to show a recorded session in the "Session Recordings" page.

For some long-running Kubernetes sessions, users have reported seeing a `session.start` event but no corresponding `session.end` event. As a result, the recording of the session is inaccessible, even if the session data was successfully uploaded to external storage.

The upload completer has some [special logic](https://github.com/gravitational/teleport/blob/cf88c0a283f27e14bf523fc9317acefd0346c97a/lib/events/complete.go#L240-L338) for ensuring that an end event is emitted, but it may not be taking effect for kube sessions.

To reproduce, I would start an interactive shell via `kubectl exec`, and then terminate the kube agent and restart it. If things are working correctly and a file-based uploader is used, then the upload completer should see some parts files on disk that were recorded while the session was alive and try to emit an end event.

**Comment by russjones** [comment]
The correct way to fix this issue is to switch to `node-sync`, let's close this issue.
