### ISSUE TITLE
Don't allow joining forwarded sessions

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1421]
### Problem

Once https://github.com/gravitational/teleport/issues/1327 is merged, Teleport will record sessions with OpenSSH servers so we will emit events to the audit log that are used to show active sessions a user can join.

Because we won't be supporting joining sessions with OpenSSH nodes in 2.4.0, we need to disable joining active sessions in the Web UI for Teleport 2.4.0 when `session_recording: proxy` is set.

**Comment by kontsevoy** [comment]
Nothing special or new is needed to be done here. If a session cannot be replied, an error will be returned by the server. The current web-based (and CLI based) client will simply show this error.

**Comment by kontsevoy** [comment]
EDIT: turns out the server doesn't return the correct code (yet). Re-opening.
