### ISSUE TITLE
Remove the "usage summary" table from the "billing & usage" menu

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#14220]
What would you like Teleport to do?

Remove the "usage summary" table from the "billing & usage" table (see screenshot). The information presented in this table is inaccurate and misleading. Note that to view this table, user needs to be assigned a role with `billing: list` and `billing: read` permissions.

![image](https://user-images.githubusercontent.com/24904723/177895981-d1eb4a84-54fd-41c7-b6d1-f7a31cbd4858.png)
![image](https://user-images.githubusercontent.com/24904723/177895997-39bf59ef-9dd2-42ed-b95e-cb0e2439fd03.png)

What problem does this solve?

It is currently causing confusion with Cloud users.

If a workaround exists, please include it.

N/A.

**Comment by xinding33** [comment]
User can also create an admin role with access to everything:

```
    rules:
    - resources:
      - '*'
      verbs:
      - '*'
```

**Comment by xinding33** [comment]
The same information is available via sales center --> accounts page

**Comment by ulysseskan** [comment]
To add context around why the screen was created in the first place:
> From Pierre: "It’s coming from our original Cloud launch where the idea was that we bill customers based on their usage. Early feedback was that we needed to be transparent on how they were getting billed since there was some disconnect between the resource count “they perceived” to be using and the amount that showed up on their invoice.

I agree that the numbers themselves without a clear explanation of what they represent are confusing.  And if we don't use the usage-based billing method above any longer (?), the whole screen is not worth having.

**Comment by jimbishopp** [comment]
Scope: hide the menu item

**Comment by mcbattirola** [comment]
This should be removed for all users, not just Cloud users, correct?

cc @xinding33

**Comment by xinding33** [comment]
@mcbattirola I'm not sure it exists on self-hosted but if so, yes, please remove it.

**Comment by jimbishopp** [comment]
> Scope: hide the menu item

@mcbattirola Thanks for doing this so quickly! It looks like the PR removed the entire billing section. We were looking to hide the menu item in case we want to resurrect the view again in the future. It may not be a big deal in the end. We can always restore from the commit and the longer we go without it the more likely we'll want to build from scratch anyway.

@xinding33 Is this okay?

**Comment by mcbattirola** [comment]
> We can always restore from the commit

Yes, I didn't want us to have dead code since we can restore it if needed.

Sorry about that, I can revert it if we plan to use it soon.

**Comment by jimbishopp** [comment]
> Sorry about that, I can revert it if we plan to use it soon.

Not a problem! I'm with you about dead code.

I didn't get the impression this was something we were going to address anytime soon, but let's see what @xinding33 says. I have a product meeting in 20m and will bring it up as well.

**Comment by jimbishopp** [comment]
@mcbattirola Xin confirmed the PR is fine. Thanks for working on this today.
