### ISSUE TITLE
Status of IPv6 Support?

### ISSUE THREAD

**Issue by Omeryl** [gravitational/teleport#1423]
The README has said IPv6 is not supported for as long as I can remember, yet I can't find any specific issues stating why that's the case. Can someone shed light on this for me?

Thanks!

**Comment by kontsevoy** [comment]
@Omeryl It may actually work, there's nothing IPv4 specific in Teleport, we just don't support it. It's a bit of a chicken-and-egg problem: we do not have the IPv6 requirement internally and none of the existing commercial customers uses IPv6. This creates the void in which we can't guarantee regular IPv6 exposure/testing/usage, which makes it hard to declare a commercial support for it.

**Comment by maznu** [comment]
My experience is IPv6 is working perfectly on Teleport 2.3:

* teleport web accessible via IPv6 (both direct and behind nginx)
* teleport node connections via IPv6
* teleport proxy and trusted cluster via IPv6

Only downside is that advertise_ip is a single-valued configuration item, so you probably end up having to pick IPv4.

**Comment by netmonk** [comment]
Can you please post a valid nginx reverse-proxy configuration for teleport. 
Like for https://somedomaine.com/teleport redirecting to https://localhost:port/web/login?
