### ISSUE TITLE
Documentation of Trusted Cluster change in 2.3 does not cover BC break with 2.2

### ISSUE THREAD

**Issue by aashley** [gravitational/teleport#1424]
The documentation does not mention that 2.3 is a BC break compared to 2.2 with regards to configuring trusted clusters. The only mention of this is a warning in syslog when starting the teleport instance.

**Comment by aashley** [comment]
Additionally the documentation does not cover that allow_logins is dropped and that the role requirements for users have changed to work with trusted clusters. And that users can not be updated to meet new requirements have to be replaced.

**Comment by aberoham** [comment]
@kontsevoy the bit about allowed_logins and its interaction with Trusted Clusters is something we recently discussed? Should link that ticket to this one? 

@aashley Have you tried 2.4 or 2.5 w/trusted clusters, I suspect that they are a bit more seamless during upgrade

**Comment by aashley** [comment]
Yes we're running 2.4 in production now. Haven't upgraded to 2.5 yet
