### ISSUE TITLE
Doc tests do not check for stale links

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#14274]
Expected behavior:
Tests check for stale links in our nav bar

Current behavior:
They don't.

I don't know how to do this because I'm not at all familiar with our docs scripts. Basically, I'd like to check if any slugs in `docs/config.json` point to pages that don't exist. We had some docs pages 404'ing today with v10 because of stale slugs: #14273

Simple mistake to make and simple mistake to catch and prevent with scripts.

**Comment by xacrimon** [comment]
When we do this, please make sure it's only internal links. Checking externals isn't a good idea since we've had that break before and kill our CI.

**Comment by ptgott** [comment]
Closing so we can track this in `gravitational/docs`. I have a PR open here as well: https://github.com/gravitational/docs/pull/123
