### ISSUE TITLE
With High-Availability the Auth Server should recover the CA keys from backend

### ISSUE THREAD

**Issue by patrobinson** [gravitational/teleport#1428]
Version: 2.2.1

## Steps to reproduce

- Build an Teleport Auth server in an AWS AutoScaling Group
- Run the Teleport Auth server with the DynamoDB backend
- Bring the Auth server up
- Register a Node to the Auth Server
- Terminate the Auth server and let the Autoscaling Group provision a new node

## Result

The already registered nodes fail to re-register with the new Auth Server.
Node logs:
```
access denied to '4fb66122-1b39-48c5-ba28-e0c2e12a6eb9.399d7f1e-1865-43d0-9547-a0c23797c01c': bad username or credentials
```

Auth logs:
```
failed auth user 4fb66122-1b39-48c5-ba28-e0c2e12a6eb9.399d7f1e-1865-43d0-9547-a0c23797c01c, err: ssh: certificate signed by unrecogized authority
```

## Expected Result

The nodes successfully re-register to the new Auth server

## Analysis

After some digging of the source code I noticed the CA is tied to the Cluster Name, so I updated the configuration to set the ClusterName so the CA would persist across reboots. While the backend stores the CA keys, it does not appear that the Auth Server retrieves it from the backend on boot https://github.com/gravitational/teleport/blob/master/lib/auth/init.go#L233 and https://github.com/gravitational/teleport/blob/master/lib/auth/init.go#L272

Instead it only looks if they exist on disk. This means the CA keys are regenerated instead causing all already issued node and user certificates to be invalid.

**Comment by patrobinson** [comment]
Upon further investigation once I set the cluster name this works properly, perhaps the High Availability documentation should mention you need to set the Cluster Name?

**Comment by kontsevoy** [comment]
@patrobinson we have updated the docs with a warning on importance of the cluster name. Also, newer versions of Teleport will complain if you try to change it.
