### ISSUE TITLE
Web UI should not display sessions when sessions recording has been disabled

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1429]
### Problem

The Web UI uses this audit log to construct a list of sessions that can be played back. Once a user clicks play, then Web UI then fetches session related events (bytes and timing) and plays back the recorded session.

In Teleport 2.4, we will support disabling session recording, #1329 defines `session_recording: off` to disable recording of sessions. This disables session data, but leaves session related metadata in the audit log. When the user clicks on the sessions tab, the user sees all sessions with play next to them, but when clicked, nothing happens (because no session related events exist).

### Proposed Solution

When the user clicks play, maybe we should have a popup that explains that the session was not recorded. I'll defer to @kontsevoy for the UX on this.

**Comment by kontsevoy** [comment]
## Behavior

When a user clicks on "play" for a session which wasn't recorded the popup must be shown, saying:

```
The recording for this session is not available.
```

**Comment by alex-kovoy** [comment]
I suggest we hide these recordings and do not show it to the user. This way there is nothing to click on.

**Comment by kontsevoy** [comment]
We must still show the list of old sessions. This information is valuable because it's basically a log of past logins.

**Comment by harsh3897** [comment]
Add Auditor role to user.
