### ISSUE TITLE
Option to group and organize resources visually in WebUI for easier user navigation

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#14346]
What would you like Teleport to do?
Ability to easily group resources visually in the WebUI.

What problem does this solve?
UX Improvement and end-user friendliness.

**Comment by zmb3** [comment]
@Aharic can you elaborate? What does it mean to "group resources visually?"

**Comment by zmb3** [comment]
@avatus this will be closed by your resource pinning work.

**Comment by novahubdev** [comment]
This was never satisfactorily resolved. New ticket now opened 'organise resources visually in WebUI' under #35064.
