### ISSUE TITLE
Metric query user_max_concurrent_sessions_hit_total does not report total count when user exceeds ssh connection to Nodes

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#14384]
Expected behavior:
Report the appropriate metric query count for `user_max_concurrent_sessions_hit_total` when the `max_connections` is reached for ssh connection to Nodes

Current behavior:
The metric query for `user_max_concurrent_sessions_hit_total` does not record total counts when a user exceeds their max concurrent ssh connections to Nodes. It only records and counts connection attempts made to the auth/proxy server. 

Bug details:
- Teleport version v.9.3.3
- Teleport version v.8.3.13

- Recreation steps
1. configure `max_connections` on for the access role assigned to a user to ensure that the rule applies to the user.
2. Attempt to initiate multiple connections to a node either `tsh ssh` or via web UI to exhaust the connection limit
3. Once connection limit is reached, the following error is printed to the screen  
`ssh: rejected: administratively prohibited (too many concurrent ssh connections for user "test" (max=1))disconnected`
4. Review the metrics endpoint for above event -  `user_max_concurrent_sessions_hit_total` reports 0

The right total count is only recorded in the metric query `user_max_concurrent_sessions_hit_total` when the user exceeds their max concurrent ssh connections for connection attempts made to the auth/proxy server. 

gz#5877

**Comment by anil-kumar-acquia** [comment]
@oshati would you please add the closing comments and any findings if possible.
