### ISSUE TITLE
Add arm64 build

### ISSUE THREAD

**Issue by sokoow** [gravitational/teleport#1440]
I see you've added arm build, but more sensible would be to add arm64 build as most of arm servers these days are arm64 already. Doable ?

**Comment by kontsevoy** [comment]
@sokoow long story short: not possible at the moment. 

You can take a look at [discussions here](https://github.com/gravitational/teleport/issues?q=is%3Aissue+ARM+is%3Aclosed) for some background. The takeaways are:

* The existing ARMv6 is good enough [runs without any performance penalties on ARM7/8]
* When Go adds a native support for ARMvX, we'll be able to support that too.
