### ISSUE TITLE
TLS multiplexing still requires kube_listen_addr under the proxy_service

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#14402]
Expected behavior:
As mentioned in the documentation (https://goteleport.com/docs/setup/operations/tls-routing/#step-77-disable-legacy-listeners), only the proxy `web_listener` should be required

Current behavior:
If the `kube_listen_addr` is omitted from the configuration when TLS multiplexing is enabled, `kubectl` commands fail to execute and Teleport reports the following in the auth/proxy logs in a loop while the command attempts to execute:

~~~
Jul 12 20:53:28 Test-Cluster-Node1-US-East teleport[14687]: 2022-07-12T20:53:28Z WARN [ALPN:PROX] Failed to handle client connection: received kube request but k8 service is disabled alpnproxy/proxy.go:320
Jul 12 20:53:29 Test-Cluster-Node1-US-East teleport[14687]: 2022-07-12T20:53:29Z WARN [ALPN:PROX] Failed to handle client connection: received kube request but k8 service is disabled alpnproxy/proxy.go:320
~~~

This is only resolved after setting the `kube_listen_addr` back in the proxy service, then everything works as expected.

Bug details:
- Teleport version - 9.3.6 on the auth/proxy service
- Recreation steps
1) Start a Teleport service using `proxy_listener_mode: multiplex` and no `kube_listen_addr` set in the proxy
2) Log in to a kube cluster and attempt to run a kubectl command

Proxy/Auth Config
~~~
teleport:
  nodename: test-cluster-node1-us-east
  advertise_ip: xxx.xxx.xxx.xxx
  log:
    output: stderr
    severity: DEBUG
  data_dir: /var/lib/teleport
  ca_signature_algo: "rsa-sha2-512"

  storage:
    type: dynamodb
    region: us-east-1
    table_name: test-cluster1
    audit_events_uri: ['dynamodb://test-cluster1-events', 'file:///var/lib/teleport/log']
    audit_sessions_uri: s3://schisaport-test-cluster1/records

auth_service:
  enabled: yes
  client_idle_timeout: 1m
  web_idle_timeout: 5m
  license_file: /etc/licenses/super-license.pem
  tokens:
    <redacted>
  keep_alive_interval: 1m
  keep_alive_count_max: 3
  proxy_listener_mode: multiplex
  routing_strategy: most_recent
  session_recording: "proxy"
  listen_addr: 0.0.0.0:3025
  public_addr: test-cluster1.schisa.cf:3025
  authentication:
    type: github
    #local_auth: false
    second_factor: otp

ssh_service:
  enabled: yes
  listen_addr: 0.0.0.0:3022
  labels:
    region: east1
  commands:
  - name: version
    command: ["/bin/sh", "-c", "teleport version | cut -d ' ' -f 3"]
    period: 1h

proxy_service:
  enabled: yes
  web_listen_addr: 0.0.0.0:443
  public_addr: ["test-cluster1.schisa.cf:443", "test-cluster4.schisa.cf:443"]
  https_keypairs:
    - cert_file: /etc/letsencrypt/live/test-cluster1.schisa.cf-0001/fullchain.pem
      key_file: /etc/letsencrypt/live/test-cluster1.schisa.cf-0001/privkey.pem
    - cert_file: /etc/letsencrypt/live/schisa.cf/fullchain.pem
      key_file: /etc/letsencrypt/live/schisa.cf/privkey.pem
~~~

**Comment by SooOverpowered** [comment]
currently facing the same problem, please have a fix soon

**Comment by zmb3** [comment]
This was addressed by #14987 which didn't get merged.

**Comment by tigrato** [comment]
@pschisa @SooOverpowered

When using Teleport config with version > `v1`, Teleport does not require `kube_listen_addr `  when `proxy_listener_mode` is `multiplex`.

You are using a config without a version which Teleport defaults to config `v1`. This version requires you to specify kube proxy addresses.

Can you please append `version: v2` to your config file and confirm that it works without specifying `kube_listen_address`?

For future reference:
If the config does not define `kube_listen_addr` or `kube_public_addr` values and its version != v1, Teleport enables the Kube Proxy.

https://github.com/gravitational/teleport/blob/7300fc769b029bedcb2324cc3306d32b3a804f0b/lib/config/configuration.go#L937

The value is later used to enable TLS multiplexing for Kubernetes if Multiplex mode is enabled.

https://github.com/gravitational/teleport/blob/7300fc769b029bedcb2324cc3306d32b3a804f0b/lib/service/proxy_settings.go#L60-L70

**Comment by pschisa** [comment]
thanks @tigrato , appending `version: 2` resolved the problem for me

**Comment by webvictim** [comment]
@tigrato Does `kubernetes_service.listen_addr` work the same way? I notice that we still have to set it in the Helm chart when `proxy_listener_mode: multiplex` is set: https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/templates/config.yaml#L104-L108

**Comment by tigrato** [comment]
@webvictim
For now `kubernetes_service` still requires the `listen_addr` property although it's possible to work without it it if we use reversetunnel
