### ISSUE TITLE
Statically defined applications temporarily disappear on `app_service` restart

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport#14422]
Expected behavior:
Restarting an `app_service` Teleport agent - which might happen as a result of a CA rotation, for instance - with statically configured apps doesn't affect the list of available apps.

Current behavior:
Depending on timing, it's possible that the new `app_service` instance will heartbeat for the static apps before the old instance unregisters them, causing them to disappear and become unavailable for the following 5-6 minutes (the `AnnouncePeriod` for the new heartbeat).

Bug details:
- Teleport version: tip of `branch/v10` at time of writing (e9bcc379422d2ab0268aef5cd87866145532af9b), but I think that all versions of Teleport with Application Access are affected.
- Recreation steps: configure a static app (even the builtin `dumper` is ok), restart the agent with a CA rotation or a HUP

**Comment by r0mant** [comment]
After discussing with @espadolini, we'd like to keep the behavior of applications being unregistered during agent shutdown, but do not unregister them in case of restart. @espadolini is working on introducing a flag indicating restart that can be propagated to all service shutdown methods, we'll be able to implement this once it's ready.
