### ISSUE TITLE
UX for CLI based Access Requests  tsh login --request-id= 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#14432]
What would you like Teleport to do?
When trying Teleport 10 access requests, it's unclear that after I assume the role that I need to `tsh request ls` and `tsh login --request-id=2a2f53f2-c57f-4c50-8e53-9973bb9921a3` after I've assumed that role.

I've made this short video to highlight my issue.

https://user-images.githubusercontent.com/559288/178796400-f5f65866-4d9c-46f0-9912-8bc2b6750604.mp4

What problem does this solve?
Time to value and UX for people using access requests for CLI only protocols such as Databases and Kubernetes clusters. 

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Thanks for this @benarent 🙏

**Comment by adubkov** [comment]
@zmb3 @rudream Why this issue is closed? 

This PR supposed to solve the problem https://github.com/gravitational/teleport/pull/15653 but now it removed `--request-id` from the UI and when I run login it doesn't assume any roles that was approved for the user. 

We are at 11.3.1 now. both, tsh, agents and cluster.

**Comment by rudream** [comment]
> @zmb3 @rudream Why this issue is closed?
> 
> We are at 11.3.1 now. both, tsh, agents and cluster and it apparently still present.
> 
> The PR supposed to solve the problem #15653 but now `--request-id` is removed from the UI and when I run `tsh login` it doesn't assume any approved roles unless I explicitly specify request-id
> 
> cc @christinahaidemenos

@adubkov Thank you for reporting this! I can confirm that this is a regression bug that was inadvertently introduced in a later PR. I have opened a PR to fix it: https://github.com/gravitational/teleport/pull/21444

Thanks again for reporting the issue and apologies for the inconvenience.

**Comment by zmb3** [comment]
Fixed (again) by #21444
