### ISSUE TITLE
Have storage persistent when user logins. 

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#14469]
What would you like Teleport to do?
Following this documentation: https://goteleport.com/docs/server-access/guides/host-user-creation/. Customer states they have hundreds of people who do penetration testing on distributed systems, they would like to be able to dynamically assign access without pre-provisioning the ID but have their work stay after they logout. Ideally have it delete the .ssh directory so they can't leave keys online, and delete the password for the user. They would like persistent storage on some of their systems. 

```The session can then proceed as usual, however once the SSH session ends, the user will be automatically removed and their home directory will be deleted. Files owned by the deleted user, created outside the home directory, will remain in place. Groups that were created will remain on the system after the session ends.```

What problem does this solve?
Allow penetration testing work be saved on the nodes and not delete their progress. 

If a workaround exists, please include it.
At the moment they have to stick to pam based or static provisioning.

**Comment by zmb3** [comment]
This was released in 13.2
