### ISSUE TITLE
[v.10.0] /docs/pages/kubernetes-access/getting-started.mdx

### ISSUE THREAD

**Issue by kenske** [gravitational/teleport#14485]
## Details
In the deployment overview section, the specified cluster `tele.example.com` doesn't match the name in the diagram.

### Category

- Improve Existing

**Comment by Nishchay1571999** [comment]
Hi @kenske i would like to look into the issue. Could you help me on where a should i start looking at?

**Comment by Nishchay1571999** [comment]
Instead of tele.example.com what should be the name?
