### ISSUE TITLE
Add an easy way to drop a resource access request and return to 'normal' access

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#14491]
## What would you like Teleport to do?

As per https://goteleport.com/docs/enterprise/workflow/resource-requests/#step-78-access-the-requested-resource, if you assume a resource access request, your existing permissions are gone:

> While logged in with a resource access request, users will be blocked from access to any other resources. This is necessary because their certicate now contains an elevated role. Their certificate is restricted to only allow access to the resources they were specifically approved for. They will need to `tsh logout` and log back in to resume their regular access.

Having to run `tsh logout` and then go through the login procedure again just to drop an access request is a little cumbersome.

A command like `tsh drop request` or `tsh request switch-back` or something would be useful to avoid these extra steps.

## What problem does this solve?

Makes resource access requests considerably easier to use from a user perspective.

## If a workaround exists, please include it.

None known. AFAIK `eval $(tsh env)` cannot be used either as it will overwrite the existing credentials for the given cluster/proxy.

**Comment by nklaassen** [comment]
the workaround is `tsh logout && tsh login`, but you're right, we should have something better
