### ISSUE TITLE
Application access Multi-domain support to a single logical application.  

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#14505]
What would you like Teleport to do?
Have application access object reference handle multiple uri strings such that there is the functionality to proxy two different subdomains to a single logical application. 

What problem does this solve?
Allows for UI to call appropriate subdomain specified in REST API calls. 

gz#5840

**Comment by krumware** [comment]
Also need this

**Comment by webvictim** [comment]
Similar request to https://github.com/gravitational/teleport/issues/17588

**Comment by zmb3** [comment]
Tracking this one at #17588
