### ISSUE TITLE
GenerateToken fails

### ISSUE THREAD

**Issue by narang99** [gravitational/teleport#14504]
I'm trying to create tokens using the client.

What I'm doing:
```go
clt, ctx, err := GetClient()
if err != nil {
	return "", err
}
defer clt.Close()
return clt.GenerateToken(ctx, &proto.GenerateTokenRequest{
	Roles: types.SystemRoles{types.RoleNode},
})
```

Expected behavior:
I want it to return the token

Current behavior:
```
unknown method GenerateToken for service proto.AuthService
```

Bug details:
- Teleport version: `github.com/gravitational/teleport/api v0.0.0-20220714155839-ac69da99fb30`
- Go version: 1.18
- OS: Ubuntu 22.04-LTS
- Also tested in docker container, get the same error with base image Ubuntu:20.04

**Comment by Joerger** [comment]
Hi @narang99, what version is your Teleport cluster? GenerateToken is a recent addition to the api so it will only work with a v10.0.0+ auth server.

If you can't upgrade, you can use UpsertToken with an empty token to get the same functionality as GenerateToken.

**Comment by narang99** [comment]
Oh yes, im sorry. My versions 9.3.4
I noticed UpsertToken doesnt return anything    
https://pkg.go.dev/github.com/gravitational/teleport/api/client#Client.UpsertToken   
I dont understand how I can get the actual token. Should I actually pass a randomly generated token?

Can you give me an example please? Thanks.

**Comment by narang99** [comment]
Great, this works. Thanks a lot Joerger
