### ISSUE TITLE
`TestFnCacheSanity` flakiness

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#14534]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds;region=us-west1/a47d1dff-fa4c-4ba6-88c9-aa474f19b96c?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/f74bb490-6b78-4f9b-959c-94e839d1b9a9?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/7fa3a357-ebcb-4ce0-84ab-bb178694efd0?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/a548f2c3-a15e-4eb1-8f4e-735fb9e1d7fc?project=ci-account

#### Relevant snippet

```
=== RUN   TestFnCacheSanity/non-blocking
    fncache_test.go:151: 
        	Error Trace:	fncache_test.go:151
        	            				fncache_test.go:76
        	Error:      	Max difference between 11.10786165 and 9 allowed is 2, but difference was 2.1078616500000003
        	Test:       	TestFnCacheSanity/non-blocking
    --- FAIL: TestFnCacheSanity/non-blocking (0.45s)
```

**Comment by zmb3** [comment]
Another failure: https://console.cloud.google.com/cloud-build/builds/52d61a26-7ba6-4982-a10d-4ca10841ff2a;step=0?project=ci-account
