### ISSUE TITLE
Web UI downloads append `{"message":"ok"}` to files

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#14557]
When using the Web UI to download a file, `{"message":"ok"}` is appended to all files.

This occurs in Teleport 9 and Teleport 10.

**Comment by zmb3** [comment]
This is due to:

https://github.com/gravitational/teleport/blob/ad512e449fd44d7caf21f1c397b4e0cc2f4caa8d/lib/web/files.go#L82

Our middleware writes whatever you return to the HTTP response. For file transfers, we'll have to return `nil, nil` here.
