### ISSUE TITLE
Support automated provision of Machine ID bots via Terraform provider

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#14575]
**What would you like Teleport to do?**

Machine ID join tokens (`tctl bots add`) are currently single-use, which makes sense from a security perspective. However, the experience of adding a bot is currently a manual process which must be scripted against the auth server. We should support the provisioning of Machine ID bots via Terraform provider for users who want to deploy them as part of automated workflows, and provide documentation on how to do this.

**What problem does this solve?**

Automated provisioning of Machine ID bots.

**If a workaround exists, please include it.**

Technically using `tctl` manually or via an automated process is a workaround, but it's not a good one.

**Comment by strideynet** [comment]
There's definitely some complexity here around idempotency, since a "bot" isn't a single resource in Teleport like other things currently configured in Terraform are. We should keep an eye out for this.

**Comment by timothyb89** [comment]
I've got a draft PR up to add basic support for this: https://github.com/gravitational/teleport-plugins/pull/669

Usage looks something like this (for one-time-use tokens, which isn't ideal):

```terraform
locals {
  bot_name = "example"
}

resource "random_password" "bot_token" {
  length           = 32
  special          = false
}

resource "time_offset" "bot_example_token_expiry" {
  offset_hours = 1
}

resource "teleport_provision_token" "bot_example" {
  metadata = {
    expires = time_offset.bot_example_token_expiry.rfc3339
    description = "Bot join token for ${local.bot_name} generated by Terraform"

    name = random_password.bot_token.result
  }

  spec = {
    roles = ["Bot"]
    bot_name = local.bot_name
    join_method = "token"
  }
}

resource "teleport_bot" "example" {
  name = local.bot_name
  token_id = teleport_provision_token.bot_example.metadata.name
  roles = ["access"]
}
```

It's much better to use IAM/OIDC tokens for this since they don't get deleted after first use. Terraform will dutifully recreate the provisioning token after it's consumed which is not great security-wise.
