### ISSUE TITLE
tsh v9 breaks tsh v8 functionality

### ISSUE THREAD

**Issue by anurag-work** [gravitational/teleport#14592]
# Expected behavior

The following should work:
```
# tsh version
Teleport v8.3.14 git:v8.3.14-0-g1433d2456 go1.17.11
# tsh login --proxy=root-proxy.company.com:3080 --auth=corporate
# tsh ssh sjc37p1xxxxxxx 
```

# Current behavior:
```
# tsh version
Teleport v9.2.1 git:v9.2.1-0-gc6daeda62 go1.17.9
# tsh login --proxy=root-proxy.company.com:3080 --auth=corporate
# tsh ssh sjc37p1xxxxxxx
ERROR: access denied to anurag connecting to sjc37p1xxxxxxxon cluster root-cluster
```

Bug details:
- Teleport cluster and client agent is v9.3.5 . connecting via teleport agent

**Comment by strideynet** [comment]
Is this a duplicate of https://github.com/gravitational/teleport/issues/14592 ?

**Comment by zmb3** [comment]
This *is* #14592 :-)

**Comment by strideynet** [comment]
> This _is_ #14592 :-)

🤦  Meant https://github.com/gravitational/teleport/issues/14604

**Comment by r0mant** [comment]
Yes, it's the same issue. Let's close this one.
