### ISSUE TITLE
Provide ability for `tsh` to load all CAs

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#14604]
In https://github.com/gravitational/teleport/pull/9357 we updated `tsh` to only load CAs for the cluster you're currently connected to. This was highlighted during an external security audit as a potential security issue that could allow an attacker controlling network and DNS to trick `tsh` into thinking it's connecting to one leaf cluster while in fact it would be talking to another leaf cluster.

For setups where this attack vector is not a big concern though, this change broke a scenario where users would legitimately want to connect to a node within any leaf cluster after logging into the root:

1. Log into a root cluster.
2. Connect to a node within a _leaf_ cluster using `tsh ssh`.

With the linked change, `tsh ssh` receives "access denied" error in Teleport 9 and 10 because `tsh` only loads the CA of the root cluster and cannot verify certificate presented by the leaf's host. Using `--insecure` flag allows to connect.

To keep supporting this scenario, add an optional server-side setting that restores the old behavior - i.e. makes `tsh` to load all CAs - and verify that the above scenario works like in prior versions.

Note that it should be a server-side setting (i.e. a flag somewhere in cluster configuration) so end users don't need to provide any additional flags to the `tsh` command and it can be controlled by cluster admin.

**Comment by atburke** [comment]
I've dug into the code and I've discovered that `tsh` is currently loading all CAs after logging in despite changes in #9357. A user can pass the `--cluster` flag to `tsh ssh` and get the same behavior as before #9357.

https://github.com/gravitational/teleport/blob/b19836abe774a2196de32aa305e6acddcde1737b/lib/client/api.go#L3468-L3470

**Comment by r0mant** [comment]
@atburke The ask is to able to get this behavior without having to pass any extra flags (like `--cluster`) to tsh, via a server-controlled setting. So tsh should detect that "load all CAs" is enabled on the server and load all CAs automatically. cc @jakule
