### ISSUE TITLE
Node join script assumes `/usr/local/bin` is in the $PATH (aka install-node.sh)

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#14607]
__Expected behavior:__

A command like:

```shell
$ sudo bash -c "$(curl -fsSL https://example.com/scripts/<token>/install-node.sh)"
```

should work without `/usr/local/bin` being in the PATH.

__Current behavior:__

```shell
$ sudo bash -c "$(curl -fsSL https://example.com/scripts/<token>/install-node.sh)"
(abridged)
> Installed:
>   teleport.x86_64 0:10.0.1-1
> 
> Complete!
> 2022-07-18 19:57:48 UTC [teleport-installer] Found: Teleport v10.0.1 git:v10.0.1-0-gac73232 go1.18.3
> 2022-07-18 19:57:48 UTC [teleport-installer] Writing Teleport node service config to /etc/teleport.yaml
> bash: line 439: teleport: command not found
```

We shouldn't assume users, especially root, have their $PATH configured in a specific way. This fails in some Amazon EC2 machines, for example.

Tracing back we can see that [install_teleport_node_config](https://github.com/gravitational/teleport/blob/e2c29e2917926c2ea22ca82668fd554f44831af6/lib/web/scripts/node-join/install.sh#L440) relies on `teleport` being on $PATH, despite [check_teleport_binary](https://github.com/gravitational/teleport/blob/e2c29e2917926c2ea22ca82668fd554f44831af6/lib/web/scripts/node-join/install.sh#L305) looking for the binary in an specific folder.

My suggestion is to always use absolute paths for the teleport binaries in the script. (We don't want to allow binary ingestions on `/usr/local/bin` to take effect.)

Bug details:
- Teleport version: v10.0.1
- Recreation steps: see above
- Debug logs: see above

**Comment by codingllama** [comment]
FYI @hatched

**Comment by webvictim** [comment]
Related: https://github.com/gravitational/teleport/issues/14834
