### ISSUE TITLE
Canvas flickering problem

### ISSUE THREAD

**Issue by RyanCode** [gravitational/teleport#14618]
I see that teleport uses base64 format for image frame transmission, will this not affect the efficiency?When the page changes in a large range, the canvas will have a flickering problem,I ran into this problem but teleport not ,how do teleport resolve that?

**Comment by zmb3** [comment]
I'm not sure I understand the question here. Would you mind moving this to a [Discussion](https://github.com/gravitational/teleport/discussions) and we can discuss there?
