### ISSUE TITLE
Add Search Bar in Roles Access Request 

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#14642]
What would you like Teleport to do?
Add Search Bar in Roles Access Request

What problem does this solve?
Customer has over 2000+ roles in their environment, it would resolve having to scroll over 2000+ roles. 
Servers have search bar: 
![Screen Shot 2022-07-19 at 11 06 31 AM](https://user-images.githubusercontent.com/96448492/179797987-f717bbc9-f206-4297-8ba1-bafad89bf00a.png)
Roles doesn't have search bar: 
![Screen Shot 2022-07-19 at 11 06 49 AM](https://user-images.githubusercontent.com/96448492/179798035-ac4f5eab-876e-42eb-8415-9f152471cd29.png)

If a workaround exists, please include it.
We could probably do ctl + F, do specify the search but not ideal.

**Comment by russjones** [comment]
I'm not sure if we should add the ability to search.

Can the customer reduce the number of roles using role variables?

**Comment by stevenGravy** [comment]
Another customer has asked for this.  They wouldn't have thousands of role but enough that this is a burden not to have.

**Comment by BrianGalfond-Teleport** [comment]
+1 for a prospect looking to leverage this

**Comment by gzdunek** [comment]
Fixed in https://github.com/gravitational/teleport.e/pull/2301. It will be backported to v14, v13 and v12.
