### ISSUE TITLE
libfido2 "no suitable devices found" on Arch Linux

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#14657]
__Expected behavior:__

`tsh fido2 diag` and similar commands work (like `tsh login`).

__Current behavior:__

```shell
$ tsh fido2 diag -d
Tap your security key
            DEBU FIDO2: Selecting devices error:[no suitable devices found] webauthncli/fido2.go:592
            DEBU FIDO2: Selecting devices error:[no suitable devices found] webauthncli/fido2.go:592
            DEBU FIDO2: Selecting devices error:[no suitable devices found] webauthncli/fido2.go:592
            DEBU FIDO2: Selecting devices error:[no suitable devices found] webauthncli/fido2.go:592
            DEBU FIDO2: Selecting devices error:[no suitable devices found] webauthncli/fido2.go:592
            DEBU FIDO2: Selecting devices error:[no suitable devices found] webauthncli/fido2.go:592
^C
FIDO2 available: true
Register successful? false
Login successful? false

ERROR REPORT:
Original Error: *errors.errorString context canceled
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/auth/webauthncli/fido2.go:596 github.com/gravitational/teleport/lib/auth/webauthncli.findSuitableDevicesOrTimeout
        /go/src/github.com/gravitational/teleport/lib/auth/webauthncli/fido2.go:546 github.com/gravitational/teleport/lib/auth/webauthncli.runOnFIDO2Devices
        /go/src/github.com/gravitational/teleport/lib/auth/webauthncli/fido2.go:444 github.com/gravitational/teleport/lib/auth/webauthncli.fido2Register
        /go/src/github.com/gravitational/teleport/lib/auth/webauthncli/fido2_common.go:95 github.com/gravitational/teleport/lib/auth/webauthncli.FIDO2Register
        /go/src/github.com/gravitational/teleport/lib/auth/webauthncli/fido2_common.go:137 github.com/gravitational/teleport/lib/auth/webauthncli.FIDO2Diag
        /go/src/github.com/gravitational/teleport/tool/tsh/fido2.go:26 main.onFIDO2Diag
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:947 main.Run
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:396 main.main
        /opt/go/src/runtime/proc.go:250 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: context canceled
```

In that same system libfido2 1.11.0-1 is installed and `fido2-token` works:

```shell
$ fido2-token -L
/dev/hidraw4: vendor=0x1050, product=0x0407 (Yubico Yubikey 4 OTP+U2F+CCID)
```

Current workaround is to set `TELEPORT_FIDO2=0` in the environment (falls back to the U2F backend).

Thread on Slack: https://goteleport.slack.com/archives/CEZH6UL64/p1658255710172229

__Bug details:__

- Teleport version: 10.0
- Recreation steps: see above
- Debug logs: see above

**Comment by codingllama** [comment]
Regarding udev rules, which were my first suspect, the user said:

"Arch does not ship with any (udev rules) since this commit: https://github.com/archlinux/svntogit-packages/commit/e29cf8f50bb55edcd373efe0d2d4226dd6b7e511. If the commit message is right that is due to the fact that in arch systemd handles the the rules"

**Comment by codingllama** [comment]
`tsh fido2 diag` works fine in the Arch box I have here:

```shell
$ ./tsh fido2 diag  # downloaded from https://get.gravitational.com/teleport-v10.0.2-linux-amd64-bin.tar.gz
> Tap your security key
> Tap your security key
>
> FIDO2 available: true
> Register successful? true
> Login successful? true
```

`fido2-token` for completeness:

```shell
$ fido2-token -L
> /dev/hidraw3: vendor=0x1050, product=0x0406 (Yubico YubiKey FIDO+CCID)
```

I suspect it has to do with some other package I have installed, so I did some digging:

```shell
# Explicitly installed
$ pacman -Qe | grep -iE '(fido|u2f|yubi)'
> libfido2 1.11.0-1
> libu2f-server 1.1.0-4
> yubikey-manager 4.0.8-1

# All installed
$ pacman -Q | grep -iE '(fido|u2f|yubi)'
> libfido2 1.11.0-1
> libu2f-server 1.1.0-4
> python-fido2 1.0.0-1
> yubico-c 1.13-6
> yubico-c-client 2.15-5
> yubikey-manager 4.0.8-1
> yubikey-personalization 1.20.0-3

# "u2f" udev rules
$ rg -i u2f /usr/lib/udev/rules.d/
(none)

# "fido" udev rules
$ rg -i fido /usr/lib/udev/rules.d/
> /usr/lib/udev/rules.d/60-fido-id.rules
> 3:ACTION=="remove", GOTO="fido_id_end"
> 5:SUBSYSTEM=="hidraw", IMPORT{program}="fido_id"
> 14:LABEL="fido_id_end"
$ pacman -Qo /usr/lib/udev/rules.d/60-fido-id.rules
> /usr/lib/udev/rules.d/60-fido-id.rules is owned by systemd 251.3-1

# "yubi" udev rules
$ rg -i yubi /usr/lib/udev/rules.d/
> /usr/lib/udev/rules.d/69-yubikey.rules
> 1:ACTION!="add|change", GOTO="yubico_end"
> 3:# Udev rules for letting the console user access the Yubikey USB
> 6:# Yubico Yubikey II
> 10:LABEL="yubico_end"
$ pacman -Qo /usr/lib/udev/rules.d/69-yubikey.rules
> /usr/lib/udev/rules.d/69-yubikey.rules is owned by yubikey-personalization 1.20.0-3
```

Based on the above, `yubikey-personalization` seems to be my best guess, but I would throw in `libu2f-server` and `yubikey-manager` if that doesn't work. It's not very scientific, I know, but if it works I'll take it.

**Comment by christian-heusel** [comment]
So I think our configurations & installed packages match for the most part:
```
$ teleport version
Teleport v10.0.2 git:v10.0.2-0-g47e0914 go1.18.3
$ tsh version
Teleport v10.0.2 git:v10.0.2-0-g47e0914 go1.18.3
Proxy version: 10.0.0
$ tctl version
Teleport v10.0.2 git:v10.0.2-0-g47e0914 go1.18.3

$ pacman -Qe | grep -iE '(fido|u2f|yubi)'
libfido2 1.11.0-1
libu2f-host 1.1.10-4
libu2f-server 1.1.0-4
yubikey-manager 4.0.8-1
yubikey-manager-qt 1.2.4-1
yubikey-personalization 1.20.0-3
yubikey-personalization-gui 3.1.25-2

$ pacman -Q | grep -iE '(fido|u2f|yubi)' 
libfido2 1.11.0-1
libu2f-host 1.1.10-4
libu2f-server 1.1.0-4
python-fido2 1.0.0-1
yubico-c 1.13-6
yubico-c-client 2.15-5
yubikey-manager 4.0.8-1
yubikey-manager-qt 1.2.4-1
yubikey-personalization 1.20.0-3
yubikey-personalization-gui 3.1.25-2

$ rg -i "fido|yubi" /usr/lib/udev/rules.d/
/usr/lib/udev/rules.d/60-fido-id.rules
3:ACTION=="remove", GOTO="fido_id_end"
5:SUBSYSTEM=="hidraw", IMPORT{program}="fido_id"
14:LABEL="fido_id_end"

/usr/lib/udev/rules.d/69-yubikey.rules
1:ACTION!="add|change", GOTO="yubico_end"
3:# Udev rules for letting the console user access the Yubikey USB
6:# Yubico Yubikey II
10:LABEL="yubico_end"
```
If you find a difference let me know!

I really have no clue about the specifics, but could it make a difference that my yubikey shows "Yubico Yubikey 4 OTP+U2F+CCID" while yours explicitly lists FIDO? 🤔

**Comment by codingllama** [comment]
Re FIDO vs U2F, it shouldn't make a difference, at least in theory. libfido2 does both CTAP2 (aka FIDO) and CTAP1 (aka U2F).

I don't have a Yubi4 on me, but I'll see if someone else can try to repro.

**Comment by christian-heusel** [comment]
Alright, so I took another look at the problem with a buddy of mine and we got so far that we built the code on our own. The following build produces a version of `tsh` on my system, with which I can login into the cluster:
```shell
# use dynamicallly linked libfido2
$ make WITH_FIDO=dynamic build/tsh
....

# Weirdly (or maybe thats why its works)for that binary the FIDO2 features are unavailiable
$ ./build/tsh fido2 diag
FIDO2 available: false
Register successful? false
Login successful? false


# unfortunately the static build does not work, so there is no comparison
$ make FIDO2=yes build/tsh  
GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -tags " libfido2 libfido2static " -o build/tsh  -ldflags
'-w -s' ./tool/tsh
# pkg-config --cflags  -- libfido2-static
Package libfido2-static was not found in the pkg-config search path.
Perhaps you should add the directory containing `libfido2-static.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libfido2-static', required by 'virtual:world', not found
pkg-config: exit status 1
make: *** [Makefile:239: build/tsh] Error 2
```

Said friend also uses the binary distribution but for him it all works 🤔 Maybe we get to test his yubikey on my machine and the other way around in the next weeks.

**Comment by codingllama** [comment]
@christian-heusel, thanks for your help debugging this!

> $ make WITH_FIDO=dynamic build/tsh

I don't think WITH_FIDO does anything, meaning you got the non-libfido2 backend.

> Weirdly (or maybe thats why its works)for that binary the FIDO2 features are unavailiable

Yep, that's the same as setting `TELEPORT_FIDO2=0` in the environment. It's a valid fallback, but you won't get passwordless features.

> unfortunately the static build does not work, so there is no comparison

The static build is a bit tricky to get going, we write `libfido2-static.pc` ourselves, among other things.

Since you've gone through all this trouble, could you see if the binary built like this makes a difference for you?

```shell
cd /path/to/teleport/sources
go build -tags=libfido2 ./tool/tsh
./tsh fido2 diag
```

(If you still get libfido2-static errors building, try `go clean -cache` and build again.)

> Said friend also uses the binary distribution but for him it all works 🤔 Maybe we get to test his yubikey on my machine and the other way around in the next weeks.

Good to know that it works for him!

**Comment by ulysseskan** [comment]
Is it possible another daemon has exclusive control over the yubikey device, preventing tsh from selecting it?
Ref: https://wiki.archlinux.org/title/YubiKey#Troubleshooting

**Comment by christian-heusel** [comment]
Alright, so as far as I understand it (after debugging with `gdb`) the problem is kind of the following:

1. The first time we hit the try to add the device to the `devs []devicesWithInfo` slice, the following error occurs:
    ```
   $ ./build/tsh --debug fido2 diag
   DEBU             FIDO2: locations /dev/hidraw4 webauthncli/fido2.go:612
   Tap your security key
   DEBU             "FIDO2: hit some error device /dev/hidraw4: info\n\tnot a FIDO2 device" webauthncli/fido2.go:545
    ```
    We then hit the trap here:
    https://github.com/gravitational/teleport/blob/fafb8016b1b1bc7f23fa742112ea6a0bd309295a/lib/auth/webauthncli/fido2.go#L630-L632
    I added a extra debug statement in line 545 to see this previously ignored error.
2. Afterwards we already have the `/dev/hidraw4` in the knownPaths and execution of the loop is skipped everytime, thats why we never get to the real error (which was ignored in the first iteration):
    https://github.com/gravitational/teleport/blob/fafb8016b1b1bc7f23fa742112ea6a0bd309295a/lib/auth/webauthncli/fido2.go#L611-L613
   ```
   DEBU             FIDO2: locations /dev/hidraw4 webauthncli/fido2.go:612
   DEBU             FIDO2: path "/dev/hidraw4" is in known Paths map["/dev/hidraw4":{}], skipping loop execution with 0 devices webauthncli/fido2.go:614
   DEBU             FIDO2: Selecting devices error:[no suitable devices found] webauthncli/fido2.go:593
   DEBU             FIDO2: locations /dev/hidraw4 webauthncli/fido2.go:612
   DEBU             FIDO2: path "/dev/hidraw4" is in known Paths map["/dev/hidraw4":{}], skipping loop execution with 0 devices webauthncli/fido2.go:614
   DEBU             FIDO2: Selecting devices error:[no suitable devices found] webauthncli/fido2.go:593
   ```

>> but could it make a difference that my yubikey shows "Yubico Yubikey 4 OTP+U2F+CCID" while yours explicitly lists FIDO?

> Re FIDO vs U2F, it shouldn't make a difference, at least in theory 

So as it appears my device does not support FIDO2:
```
$ ykman info
WARNING: PC/SC not available. Smart card protocols will not function.
Device type: YubiKey 4
Serial number: 7466094
Firmware version: 4.3.7
Enabled USB interfaces: OTP, FIDO, CCID

Applications
FIDO2           Not available
OTP             Enabled
FIDO U2F        Enabled
OATH            Enabled
YubiHSM Auth    Not available
OpenPGP         Enabled
PIV             Enabled
```

 and the logging output/logic needs to be improved to also log the reason for a device's rejection...? 🤔

**Comment by codingllama** [comment]
@christian-heusel many thanks, that's a lot of good info. We can't do passwordless without FIDO2, but it should absolutely work for MFA. Time to put together a patch.

**Comment by codingllama** [comment]
For folks following the issue, the fix is currently on its way to v10 (#14795). Once it lands it'll get picked up by the next minor/patch release.

**Comment by christian-heusel** [comment]
But that means with the latest implementation I still have to set `TELEPORT_FIDO2=0` in order to use my U2F device without FIDO2 capabilities...?

**Comment by codingllama** [comment]
Hey @christian-heusel, once the fix is out you can drop the env variable. If you still have problems after that let me know.

**Comment by christian-heusel** [comment]
Hey @codingllama! 😊 

I think I picked up your fix from the latest version unfortunately it seems like the problem persists and it still only works by setting `TELEPORT_FIDO2=0`. Is this expected?

I have `Teleport v10.1.2 git:v10.1.2-0-g5bc7caf go1.18.3` installed, which lists the fix as included in its [Changelog](https://github.com/gravitational/teleport/releases/tag/v10.1.2): 

> Other improvements and bug fixes:
> * Fixed "no suitable devices found" libfido2 error. https://github.com/gravitational/teleport/pull/14795

<details>
<summary>Click to see debug output (<code>TELEPORT_FIDO2</code> being unset)</summary>

```
tsh login -d --proxy=my.domain.com
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/chris/.tsh/keys/my.domain.com/chris-x509.pem" valid until "2022-08-03 09:08:42 +0000 UTC". client/keystore.go:319
DEBU [KEYSTORE]  Reading certificates from path "/home/chris/.tsh/keys/my.domain.com/chris-ssh/MathPhysInfo-cert.pub". client/keystore.go:342
INFO [CLIENT]    no host login given. defaulting to chris client/api.go:1418
INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/tmp/ssh-XXXXXXo7tCfM/agent.8787" client/api.go:3957
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/chris/.tsh/keys/my.domain.com/chris-x509.pem" valid until "2022-08-03 09:08:42 +0000 UTC". client/keystore.go:319
DEBU [KEYSTORE]  Reading certificates from path "/home/chris/.tsh/keys/my.domain.com/chris-ssh/MathPhysInfo-cert.pub". client/keystore.go:342
INFO [KEYAGENT]  Loading SSH key for user "chris" and cluster "MathPhysInfo". client/keyagent.go:202
DEBU [CLIENT]    not using loopback pool for remote proxy addr: my.domain.com:3080 client/api.go:3912
DEBU             Attempting GET my.domain.com:3080/webapi/ping webclient/webclient.go:115
Enter password for Teleport user chris:
DEBU [CLIENT]    not using loopback pool for remote proxy addr: my.domain.com:3080 client/api.go:3912
DEBU [CLIENT]    HTTPS client init(proxyAddr=my.domain.com:3080, insecure=false) client/weblogin.go:233
DEBU [CLIENT]    WebAuthn: prompting devices with origin "https://my.domain.com:3080" client/mfa.go:203
DEBU             Attempting platform login webauthncli/api.go:119
DEBU             Platform login failed, falling back to cross-platform error:[touch ID not available] webauthncli/api.go:125
DEBU             FIDO2: Using libfido2 for assertion webauthncli/api.go:135
DEBU             FIDO2: Info for device /dev/hidraw5: &libfido2.DeviceInfo{Versions:[]string(nil), Extensions:[]string(nil), AAGUID:[]uint8(nil), Options:[]libfido2.Option(nil), Protocols:[]uint8(nil)} webauthncli/fido2.go:650
DEBU             FIDO2: Device /dev/hidraw5: filtered due to lack of allowed credential webauthncli/fido2.go:149
Tap any security key
```

</details>

**Comment by codingllama** [comment]
Hey Christian, log output looks legit to me. Could you try to re-register the yubikey without the `TELEPORT_FIDO2` env variable and see if it works after that?

(Re-opening until we confirm the fix.)

**Comment by christian-heusel** [comment]
I think I re-registered it as WebAuthn device by running the `tsh mfa add` wizard:
```
$ tsh mfa ls
Name                Type     Added at                      Last used
------------------- -------- ----------------------------- -----------------------------
YubiKey@muehlenband WebAuthn Tue, 02 Aug 2022 23:37:09 UTC Tue, 02 Aug 2022 23:37:09 UTC
u2f                 U2F      Wed, 07 Jul 2021 21:58:52 UTC Tue, 02 Aug 2022 23:37:08 UTC
```

Sadly, the problem persists and no device is prompted...

**Comment by codingllama** [comment]
The fact that the registration itself went through is already some progress - a lot has to go right for that to happen, including an authentication ceremony. That tells me we do have the capacity to authenticate and that the libfido2 code is behaving better now.

Something you can double-check is the proxy address - make sure that `https://my.domain.com:3080` matches exactly your configuration (auth_service.authentication.webauthn.rp_id) and the `tsh --proxy=` flag.

If that fails, I have a Yubi4 on the way. It'll still take a few days, but hopefully when it gets here I can repro and nail this down definitively. Thanks for the patience!

**Comment by christian-heusel** [comment]
`auth_service.authentication.webauthn.rp_id` is set to `my.domain.com` whereas 
`auth_service.authentication.u2f.app_id` is set to `https://my.domain.com:3080`
 as advised in the example config here: https://goteleport.com/docs/access-controls/guides/webauthn/#u2f
The used proxy flag is also just `tsh login -d --proxy=my.domain.com`.

**Comment by codingllama** [comment]
Hey @christian-heusel, it took an unreasonable amount of time, but I finally got my hands on an Yubi4 and managed to repro your last issue. Fix incoming.

**Comment by codingllama** [comment]
FYI, this is now out on 10.2.0.

**Comment by codingllama** [comment]
I'll close the issue for now, shout if you still have problems.
