### ISSUE TITLE
web ui can't ssh node

### ISSUE THREAD

**Issue by sunzqe** [gravitational/teleport#1465]
Hi,
   I installed this software in my test environment, other functions are normal use, but when I use the web ui connected to the node tips
{"error": "ssh: cert has expired", "event": "auth", "success": false, "time": "2017-11-20T11: 12: 36Z", "user": "ch" }

It is normal to use cli
can anybody help me what's the happen

**Comment by klizhentas** [comment]
most likely this happens when you have significant time difference between your server and local computer

**Comment by klizhentas** [comment]
ping, can you check the time on your side?

**Comment by sunzqe** [comment]
The method you provided solves my problem， thanks
