### ISSUE TITLE
[v.10.0] /docs/pages/application-access/guides/connecting-apps.mdx

### ISSUE THREAD

**Issue by dmSync** [gravitational/teleport#14687]
## Details
Describe the documentation improvements you wish to see.

User restriction per application ,  For example I have application a and application b and I need role a to access application a, b and role b to access application b only 

### Category

- Improve Existing

**Comment by zmb3** [comment]
Does the [Access Controls page](https://goteleport.com/docs/application-access/controls/) answer your questions?

**Comment by ptgott** [comment]
Closing in favor of #12190. The information is there, but it needs more context and a clearer step-by-step structure.
