### ISSUE TITLE
Is there a way to avoid logging security sensible content in session replays?

### ISSUE THREAD

**Issue by iuriaranda** [gravitational/teleport#1472]
We're setting up a Vault server that's managed in a Teleport cluster. The thing is that the Vault setup process involves handling unseal keys and tokens, which under no circumstances should end up in session replay files, as this would be a serious security issue.

Have you guys thought of a way to handle this kind of situations?

**Comment by klizhentas** [comment]
we have a nuclear option to turn off all audit log, although what you are loking for is turning off session recording for some specific sessions seems like.

My first reaction would be to advise and take the same precautions as with usual .bashrc SSH session - make sure that credentials are never in the standard output/standard error of the SSH session.

We can also chat about other options for future improvements as well

**Comment by iuriaranda** [comment]
Yeah indeed I was referring to the session recordings. But I understand that it's a difficult thing to solve. For example giving users the ability to turn off recording of certain sessions can be a security issue by itself, as malicious users could potentially erase their tracks.

For now I realized that you can provide auth tokens to Vault in a hidden field (like a password), so no issues with that I guess. But I'm still interested for a more general solution, if there's any 😄

**Comment by benarent** [comment]
Closing due to ticket age and already answered.
