### ISSUE TITLE
Database access guides don't mention that you can use your own cert/key pair

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#14728]
All our self-hosted database access guides instruct the user to configure their database with Teleport-signed certificate and key.

This is technically not a hard requirement as Teleport can instead be configured to trust the CA that signed database's certificate via `ca_cert_file` configuration parameter. Right now this parameter is only mentioned in our CLI reference and [FAQ](https://goteleport.com/docs/database-access/faq/#can-i-provide-a-custom-ca-certificate).

We should mention this in the docs, the question is what would be the best way to integrate it:

- Mention inline in each self-hosted guide?
- Have a separate guide for this use-case covering all self-hosted scenarios?

**Comment by ptgott** [comment]
@r0mant How much is the lack of docs on using your own cert/key pair for Database Access blocking users?
