### ISSUE TITLE
Remove corrupt audit session recordings after X number of days.

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#14732]
What would you like Teleport to do?

Teleport would skip (or give errors) any corrupt session recordings while uploading, but these files would still be present in `<teleport logs>/upload/streaming` directory. Teleport should automatically delete these files after X number of days (at next restart of teleport process?).

What problem does this solve?
It will keep teleport logs directory tidy and teleport process wont need to check/skip multiple files while uploading.

If a workaround exists, please include it.

In older versions, it was recommended to manually remove any corrupt files from `/var/lib/teleport/log/upload/streaming/default`. 

gz#4711

**Comment by zmb3** [comment]
I'm not sure we would want to delete these files. There may still be relevant audit data in there that would be useful in the case of a security incident.

**Comment by curtislau6** [comment]
But the failed upload session error will be prompted continuously, those error log will make our disk size full.

**Comment by ArunNadda** [comment]
Is it possible to move these files to a separate (customer provided) location may be upon restart of teleport process after some days?

**Comment by russjones** [comment]
If we fail to upload in the past 30 days, we will stop trying to upload, log that we are not trying to upload these recordings anymore.

We won't delete any recordings.

**Comment by zmb3** [comment]
With #19011 we'll move corrupt recordings to a separate directory so teleport won't repeatedly try to process them. We will also add a metric for the number of corrupt recordings to make it easier to track.

Given those changes, I'm going to close this issue out.
