### ISSUE TITLE
fix: escalated non root user access to `/usr/local/bin/teleport` for tsh scp to work

### ISSUE THREAD

**Issue by moabu** [gravitational/teleport#14742]
### Expected behavior:

When running `tsh scp` either to push or pull a file using a non root user i.e a user that does not have access to teleport processes, the `tsh scp` should work. Protection of the processes of teleport is important so no escalated permission access occurs where the non root user can initiate new connections by starting new agents or gaining access to teleport commands

Example `tsh scp` command:

```
tsh.exe scp --proxy example-dev.example.org--user=nonroot nonroot@examplevm.example.org:/home/nonroot/test/hello local-hello
```

The nonroot user should only be able to push/pull to the folders or location/s it has access to without the need for additional higher permissions.

### Current behavior when running on local:
```
tsh scp --proxy example-dev.example.org--user=nonroot nonroot@examplevm.example.org:/home/nonroot/test/hello local-hello

/bin/bash: /usr/local/bin/teleport: Permission denied
ERROR: Process exited with status 126
```

This happens because permission in the vm enviornment to the user `nonroot` was disallowed for `/usr/local/bin/teleport` inside the joined vm : 

```
root@examplevm:/usr/local/bin$ ls -l 
total 324208
-rwxrwx--- 1 root root  49510696 May 24 12:26 tbot
-rwxrwx--- 1 root root  73671936 May 24 12:26 tctl
-rwxrwx--- 1 root root 132771136 May 24 12:26 teleport
-rwxrwx--- 1 root root  76027224 May 24 12:26 tsh
```

Once logged in the vm as root to do a bad security practice and give `nonroot` the access wanted. `nonroot` was able to see and play with `teleport`. `tsh scp` after that permission change worked. 

```
nonroot@examplevm:/usr/local/bin$ ls -l 
total 324208
-rwxrwx--- 1 root root  49510696 May 24 12:26 tbot
-rwxrwx--- 1 root root  73671936 May 24 12:26 tctl
-rwxrwxrwx 1 nonroot nonroot 132771136 May 24 12:26 teleport
-rwxrwx--- 1 root root  76027224 May 24 12:26 tsh

``` 

On local:

```
tsh scp --proxy example-dev.example.org--user=nonroot nonroot@examplevm.example.org:/home/nonroot/test/hello local-hello
<- local-hello (0)
```

Bug details:
- Teleport version: 9.3.9
- Recreation steps
1. install teleport in HA or single node for testing
2. create a VM and install the teleport client
3. join the VM to the cluster
4. login as root and protect the teleport processes and folders such as `/usr/local/bin/*`
5. create non root user in teleport web console
6. on your local computer execute a `tsh scp` command using the non root user and you will get the permission denied error. 
7. Give access to the non root user to `/usr/local/bin/teleport`
8. rerun the `tsh scp` command again using the non root user and you should be able to push or pull files

gz#5952

gz#6000

**Comment by jingsun-teleport** [comment]
/usr/local/bin/teleport is 755 by default, and it is required.

**Comment by moabu** [comment]
but that sets read,write,execute permission to owners which is fine and read/execute permission to group and others which is not. Anyone can execute /usr/local/bin/teleport ? Thats really intended ?

**Comment by moabu** [comment]
My thought would be that it should be protected then either grant it a role to execute `tsh scp` or simply always allow `tsh scp` without escalating permissions. The `tsh scp` command with then operate pushing to any folder the non root user has write access to, and pulling from anything that user has read access to

**Comment by programmerq** [comment]
The `tsh scp` functionality does execute a new instance of the `teleport` binary. It simply needs to be readable and executable by all users who may need to use it. The default permissions of 0755 allow all users to read and execute the teleport binary. There is nothing secret or sensitive in the teleport binary. A non-root user should not have access to the /var/lib/teleport directory, which is where the teleport identity information is stored for the node in question.

Several valid non-root use cases for running the `teleport` binary include:

* `teleport scp` - invoked by `tsh scp`
* `teleport db start` - run a database access agent as a non-root user
* `teleport app start` - run an application access agent as non-root user
* `teleport configure` - generate a sample auth/proxy configuration file
* `teleport node configure` - generate a sample node configuration file 
* `teleport db configure` - generate sample db access configuration file
* `teleport status` - show the current status of the teleport session while logged in via tsh ssh

None of those require access to any of the sensitive information that is stored under /var/lib/teleport that should be accessible by only root, so it is safe and expected to have read and execute permissions set for all users on the teleport binaries.

**Comment by moabu** [comment]
Thanks for the clarification.Ok that's understood @programmerq. But what if we don't want the non root user to execute/run any agent? What do we do there ? This a controlled environment usecase.

**Comment by programmerq** [comment]
> Thanks for the clarification.Ok that's understood @programmerq. But what if we don't want the non root user to execute/run any agent? What do we do there ? This a controlled environment usecase.

Those non-root users would not be able to run an agent unless they have a valid token for a teleport cluster somewhere. The binary itself does not represent any type of sensitive data. A motivated user could simply download the teleport binary and put it somewhere else (just like they can do with _any_ binary).

Taking a step back, there are a lot of not-so-nice things that can be done with other binaries on a system. bash alone can make a network connection, write to files, read from files, etc. The problem isn't the bash binary-- the user running the program can only affect files that they have access to. a non-root instance of bash can't read a file that is not readable by that user, so the file permission preventing the read is the layer in which the protection kicks in rather than whether bash is executable by that user.

**Comment by moabu** [comment]
Thanks @programmerq. Makes sense , I guess we can also introduce wrapper script around it to allow the non root user to only execute `tsh scp` .
