### ISSUE TITLE
Adjusting TTL for invite token for locally created user

### ISSUE THREAD

**Issue by mechastorm** [gravitational/teleport#1474]
Its stated in the documentation that when I create a local user `tctl users add --roles=admin j.doe@samsung.com` that "Teleport generates an auto-expiring token (with a TTL of 1 hour) and prints the token URL which must be used before the TTL expires."

Is there a way to adjust this TTL for the invite token? IE to something longer via a command line argument.

**Comment by klizhentas** [comment]
Currently this is hardcoded to 1 hour:

https://github.com/gravitational/teleport/blob/eccb071677ee5038d6b05a9fae2208468f0da910/lib/auth/new_web_user.go#L95

But should not be a big deal to make it adjustable

**Comment by klizhentas** [comment]
@mechastorm you are all set, now you can set ttl up to 48 hours when inviting users, let me know if I can help with anything else.
