### ISSUE TITLE
`tbot` CA rotation watcher emits client connection error after renewal

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#14753]
```
Error occured whilst watching CA rotations, retrying in 1.294469236s. error:[
ERROR REPORT: 
Original Error: *status.Error rpc error: code = Canceled desc = grpc: the client connection is closing
Stack Trace:
/go/src/github.com/gravitational/teleport/api/client/streanwatcher.go:87 [github.com/gravitational/teleport/api/client.(*streamWatcher).receiveEvents](http://github.com/gravitational/teleport/api/client.(*streamWatcher).receiveEvents)
/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: rpc error: code = Canceled desc = grpc: the client connection is closing] tbot/ca_rotation.go:117
```

Is emitted after each renewal. This is because when we renew, we replace the central client in `tbot` with one using the new certificates, and as part of this, we call `client.Close()` on the old client. This causes the open connection used by the CA rotation watcher to close, throwing this error. Whilst this error looks concerning, it's mostly innocent. The connection re-opens itself, although, there is a small risk of this coinciding with a rotation.

I see two options:
- Smarter closing, that doesn't close it if there is an open watcher using that client.
- Swallow client connection error and reconnect immediately rather than retrying after some period, as we know what causes this and it is a special case.

Whilst the first option seems the "cleanest", I'm concerned it might actually be fiddly to keep track of if a watcher is using the client, and that we risk leaking clients if we don't detect the watcher going away. The second option is easier, and does always ensure that the watcher is using the latest credentials (even though this doesn't really make much of a difference).

**Comment by thg-adamdean** [comment]
Thanks @strideynet, was watching this one with interest.
