### ISSUE TITLE
Standby Auth/Proxy config option for DR Scenarios

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#14790]
What would you like Teleport to do?
Allow teleport agent configs to configure a "standby" auth/proxy that a node would automatically reach out to and attempt to connect to if the "primary" auth/proxy becomes unreachable for some time. Either as a separate "standby" parameter, or as a cascading `auth_server` list.

What problem does this solve?
Customers with multiple clusters planning for regional outages and DR would like to see Teleport be more self-resilient in cases where a proxy/cluster connection goes down. In these instances it'd be useful to provide teleport with a "standby" url for a backup cluster that it should connect to if their "primary" cluster becomes unresponsive or connectivity cannot be established after some time.

If a workaround exists, please include it.

**Comment by xinding33** [comment]
@Aharic we don't plan to support this configuration.
