### ISSUE TITLE
Reduce the complexity of Teleport download options

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#14793]
# What would you like Teleport to do?

Reduce the complexity of Teleport download options at https://goteleport.com/download/.

# What problem does this solve?

New users have trouble figuring out which package to download, especially for Linux (screenshot 1). This applies to a lesser extent to MacOS (screenshot 2). This adds friction for new users to start using Teleport. Suggestions:

1. Reduce the number of different packages? An acceptable tradeoff is combining different packages into one, even if the result is a single larger package.
2. Provide some sort of automation to detect what OS the user is running and recommending a package (while still giving users the option to download other ones).

Other suggestions welcomed.

![image](https://user-images.githubusercontent.com/24904723/180484580-83ab5823-6624-4da1-ac5d-76e9a03d9908.png)
![image](https://user-images.githubusercontent.com/24904723/180484754-448f65ee-dda1-4ddf-8eac-9f20db062358.png)

**Comment by stevenGravy** [comment]
I liked Elastic's approach here 
<img width="939" alt="image" src="https://user-images.githubusercontent.com/60704961/180502417-db210da5-4afe-433a-9f31-ea37af85aa47.png">

**Comment by stevenGravy** [comment]
https://www.elastic.co/downloads/enterprise-search

**Comment by benarent** [comment]
This has been deployed https://goteleport.com/download/

**Comment by mcbattirola** [comment]
Closing as this has been deployed
