### ISSUE TITLE
Agent failed to reconnect after pod was restarted

### ISSUE THREAD

**Issue by takeda** [gravitational/teleport#14817]
After pod was terminated (due to node replacement) new pod never got ready.

Producing logs like:
```
2022-07-23T06:41:08Z ERRO [PROC:1]    Instance failed to establish connection to cluster: role Instance is not registered, invalid character '<' looking for beginning of value. pid:7.1 service/connect.go:113
```

and 

```
App failed to establish connection to cluster: Cert: missing parameter
```

back and forth.

- Teleport version: 10.0.2 (first observed on 10.0.0, but due to another bug the reason was <nil>), rolling back helm chart to 9.3.12 got the agent to a working condition.

**Comment by webvictim** [comment]
This looks like you updated your agents to v10 but left your root cluster on v9, maybe?

**Comment by takeda** [comment]
@webvictim you are right, I learned later that the cluster was downgraded. That would explain why agents started successfully and failed during restart.
