### ISSUE TITLE
Allow override of default systemd service

### ISSUE THREAD

**Issue by flybyray** [gravitational/teleport#14836]
https://github.com/gravitational/teleport/blob/9313899f28da0b854b3a4c297a89a2f042dc32d7/lib/web/scripts/node-join/install.sh#L394

It would be nice to allow a replacement for `./${TELEPORT_ARCHIVE_PATH}/examples/systemd/teleport.service`.

A use case would be for test deployments to allow `--insecure`  flag enabled by default or specify a different config file.

The ideal case would be that if some flag for insecure deployment is set, that the copy-paste command from webapp has the `-k` option for curl in place and the downloaded script is using an prepared `examples/systemd/teleport-insecure.service` file for systemd.
see: https://github.com/gravitational/webapps/issues/1029

Together with https://github.com/gravitational/teleport/issues/14834 it would then allow to have easy automatic test deployments with minimal vagrant virtual machines ( where `/usr/locla/bin` is not in PATH )

**Comment by webvictim** [comment]
Philosophically, I don't think we're ever going to package a script which deliberately disables TLS verification (as it's insecure and not recommended)

**Comment by flybyray** [comment]
Ok
