### ISSUE TITLE
[docs] SSH Azure AD Docs: Cloud URL Example Update

### ISSUE THREAD

**Issue by gaille-teleport** [gravitational/teleport#14847]
## Details
[SSH Azure AD Docs](https://github.com/gravitational/teleport/blob/master/docs/pages/enterprise/sso/azuread.mdx?plain=1#L64) needs to be updated to the full proxy url that would be used for Entity ID and Reply URL, which is `https://mytenant.teleport.sh/v1/webapi/saml/acs`

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
Consolidating into #21984.
