### ISSUE TITLE
[docs]: Annotate that Teleport Homebrew Package will not allow users to run tctl commands on Cloud docs

### ISSUE THREAD

**Issue by gaille-teleport** [gravitational/teleport#14848]
## Details
Some users are not aware that the Teleport Homebrew package isn't maintained by Teleport org and that there is a known issue where users cannot run any `tctl` commands using Homebrew's Teleport. 

Can this discrepancy be annotated in the docs where we ask users to run `tctl` on Cloud, for example, [here](https://goteleport.com/docs/enterprise/sso/azuread/?scope=enterprise#make-sure-you-can-connect-to-teleport)? Essentially, users will need to download the Enterprise binary instead of using the Homebrew package.

### Category
- Improve Existing

**Comment by webvictim** [comment]
Extra colour (as I couldn't figure out why at first): the reason this happens is that Homebrew packages OSS `tctl`, but we need Enterprise `tctl` to be able to manage connectors.

I'd have thought that everything except SAML/OIDC connector creation would work with OSS `tctl`, though.
