### ISSUE TITLE
Modify Customization Provider

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#14866]
## Details
Seems there is a typo in the following doc:
https://github.com/gravitational/teleport/blob/master/docs/pages/enterprise/sso.mdx#sso-customization
Seems the following needs to be modify:
From OpenID protocol ---> Okta provider
![Screen Shot 2022-07-25 at 4 12 07 PM](https://user-images.githubusercontent.com/96448492/180875333-bae43b14-b1ce-426e-baf8-d5e52af79f63.png)

### Category
- Improve Existing

**Comment by webvictim** [comment]
This is actually working as intended; the purpose of the doc is to show the different logos that Teleport can show and the strings that you need to make them show.
