### ISSUE TITLE
Support additional headers for application access using teleport proxy

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#14874]
##What would you like Teleport to do?

Currently teleport proxy with application access does not support specific headers as mentioned in https://goteleport.com/docs/application-access/guides/connecting-apps/#headers-passthrough.

There are some applications which need these headers to be passed through by proxy. Other revers proxies (apace, nginx etc) support most of these headers.

For example `zammad` application (ref: https://zammad.org/), with latest version requires proxy to set header (ref: https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080/33) for SSO login to work because of CSRF issues. In case of `zammad`, to make SSO login work with zammad, we should be able to set `X-Forwarded-*` header, specifically

```
X-Forwarded-Ssl
X-Forwarded-Port
X-Forwarded-Proto
```

Similar issue can be seem with recent version of Grafana.

##What problem does this solve?

Provide proxy functionality in teleport on par with other reverse proxies available in market.

## If a workaround exists, please include it.

NA

**Comment by mdwn** [comment]
This has been merged in to Teleport 11.
