### ISSUE TITLE
--ttl is not honored when creating token 

### ISSUE THREAD

**Issue by avdhoot** [gravitational/teleport#14916]
Expected behavior:
 When user pass `--ttl` at the time of token creation teleport should honor it. 

Current behavior:
Irrespective of what value users pass as `--ttl`; the token is generated with TTL 30 min. 

Recreation steps
```
root@teleport-cluster-bb55bf7bd-j42xz:/# tctl tokens add --type=node --ttl 8760h
The invite token: xxxx.
This token will expire in 525600 minutes.

Run this on the new node to join the cluster:

> teleport start \
   --roles=node \
   --token=xxx \
   --ca-pin=sha256:xxxx \
   --auth-server=xxxxx:3025

Please note:

  - This invitation token will expire in 525600 minutes
  - xxxx:3025 must be reachable from the new node

 root@teleport-cluster-bb55bf7bd-j42xz:/# tctl tokens ls 
Token                            Type    Labels Expiry Time (UTC)                 
-------------------------------- ------- ------ ---------------------------------    
xxxxxxx Node           27 Jul 22 10:34 UTC (29m53s)    
```

- Teleport version :  v10.0.2

**Comment by strideynet** [comment]
I can confirm I'm able to reproduce this.

**Comment by avdhoot** [comment]
Which `10.x` release will contain a fix for this?  We are able to create tokens that are valid for more than 1/2 hour.
I do not see it is part of `10.1.2` :(  cc @strideynet

**Comment by strideynet** [comment]
@avdhoot  It appears that the fix didn't make it into the change log, but when I download the binaries for 10.1.2, it appears that the fix has been included. Please let me know if this does not appear to be the case.
