### ISSUE TITLE
tctl points to the wrong directory

### ISSUE THREAD

**Issue by rrueth** [gravitational/teleport#1492]
To simplify our build and deployment system, I broke the different teleport services up into their own systemd units (i.e. node, proxy, and auth).  Thus, all of our instances run the Teleport node. The  proxy instance runs the Teleport proxy service and the Teleport node service.  The auth instance runs the Teleport auth service and Teleport node service. This is done by creating different yml configs for each service.  Then, each service has its own `data_dir` (e.g. `/var/lib/teleport_auth` vs `/var/lib/teleport` for the node). 

For the most part, everything works as expected. All of the nodes connect to the auth hosts.  I can proxy into any host using tsh ssh. But, when I try to run `tctl` (e.g. `tctl users ls`) on the Teleport auth instance, it seems to be looking at the node's `data_dir` instead of the auth instance's `data_dir`.  For example:

```
ubuntu@teleport-auth:~$ sudo tctl users ls
lstat /var/lib/teleport/admin.key: no such file or directory
```

If I temporarily copy the `admin.key`, `admin.cert`, and `host_uuid` into the node's `data_dir`, then everything works.  But, I would rather be able to point the tctl command at the appropriate `data_dir`.  Is that possible?

I'm currently running v2.2.2.  Would this issue be addressed in any of the newer releases?

Thanks,
Ryan

**Comment by klizhentas** [comment]
Ryan,

You can simply use `tctl -c` command and point to the right config file that specifies correct data directory. Let me know if that works for you.

**Comment by klizhentas** [comment]
going to close this ticket, but feel free to follow up with your questions here or in the new ticket.

**Comment by rrueth** [comment]
Thanks for the quick response, @klizhentas!  I'll try that out.

**Comment by klizhentas** [comment]
no prob, ping us in case if you need anything else, will be glad to help you out
