### ISSUE TITLE
docs: mention that you must type the OS User to start an SSH session on a leaf cluster

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#14949]
*Update*: Teleport is working as intended here, but this behavior came as a surprise, so the task here is to update the trusted cluster documentation to clarify.

The root cluster's web UI can not populate the OS users for leaf cluster nodes, because it knows nothing about leaf cluster roles. As a result, users must manually type in the user rather than selecting it from a dropdown.

*Original issue content below..*

Expected behavior:
Ability for user to login to leaf cluster with listed user from the root cluster. The user in this case should be present as shown in screenshot. 
![image (4)](https://user-images.githubusercontent.com/103964432/181303027-c45ff510-f370-49f8-98ca-8f84b2911850.png)

Current behavior:
The expected user "Ubuntu" is not present when admin attempts to login to their leaf cluster. 

![image (3)](https://user-images.githubusercontent.com/103964432/181303055-c28c31f7-904b-4b7d-93ed-c74cbccba410.png)

Bug details:
- Teleport version
- V10.0.2
- Recreation steps
- Login to Root Cluster and attempt to authenticate to an existing Leaf Cluster
- Debug logs

gz#6010

**Comment by zmb3** [comment]
This is not necessarily wrong.

Can you share the role mappings between the root and leaf cluster as well as the leaf roles for the user?

**Comment by moisesmejia1200** [comment]
Sharing Requested information: 

```

    role_map = [
      {
        remote = "administrator"
        local  = [local.administrator_role_name]
      },
      {
        remote = "default"
        local  = [local.reviewer_role_name]
     

    ]

resource "teleport_role" "administrator" {
  version = "v5"

  metadata = {
    name        = local.administrator_role_name
    description = "The role allows access to all nodes as ubuntu and to read cluster configuration"
  }
  spec = {
    allow = {
      request = {
        roles = ["*"]
      }
      review_requests = {
        roles = ["*"]
      }
      logins = ["ubuntu"]
      node_labels = {
        "*" = ["*"]
      }
      rules = [{
        resources = ["*"]
        verbs     = ["list", "read", "create", "update", "delete"]
      }]
    }
    options = {
      cert_format           = "standard"
      forward_agent         = false
      max_session_ttl       = "8h"
      port_forwarding       = false
      client_idle_timeout   = "5m"
      permit_x11_forwarding = false
    }
  }
}

**Comment by zmb3** [comment]
Ok, need a little bit more info.

- What user is logged in to the root cluster in your screenshots above? 
- Which local (root) roles do they have?
- What do the "administrator" and "default" roles look like on the leaf cluster?

**Comment by zmb3** [comment]
I've updated the issue title and description to convert this into a docs issue.
