### ISSUE TITLE
Desktop Access: document sizing guidelines for Windows Desktop Service

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#14957]
Document rough sizing guidelines for Windows Desktop Service.

Test with a specific Window size (1080p?) and measure memory usage for a single session as well as a couple concurrent sessions.

**Comment by benarent** [comment]
For reference I had issues with a `t2.medium` but a `t3.large` worked ok.

t2.medium : vCPU 2, RAM 4, CPU Credits 24/hr https://aws.amazon.com/ec2/instance-types/t2/

t3.large: vCPU 2, RAM 8, CPU credits 35hr https://aws.amazon.com/ec2/instance-types/t3/
