### ISSUE TITLE
Handle incorrect hostname syntax in `tsh login` more smoothly

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#14998]
## What would you like Teleport to do?

In `tsh login`, the value of the `--proxy` flag must be a hostname, with no URL path or scheme. If a user adds a URL path or scheme, `tsh login` returns a cryptic error message:

```console
$ tsh login --proxy=https://teleport.example.com/ --user=myuser
ERROR: Get "https://https//teleport.example.com//webapi/ping": dial tcp: lookup https: no such host

$ tsh login --proxy=teleport.example.com/ --user=myuser
ERROR: json: cannot unmarshal number into Go value of type webclient.PingResponse
```

These error messages don't mention the user actions that caused them (i.e., adding a URL scheme and root path). I think we should either:

- Add explicit error messages related to the user input, rather than passing internal errors to the user
- Allow for excusable syntax variations in the `proxy` flag. I stored the full URL of my Teleport cluster in my password manager after copying it from the browser, for example, including the scheme and root path. `tsh` could easily remove the scheme and URL path before executing the `login` command.

## What problem does this solve?

`tsh login` should be one of the smoother parts of the Teleport client experience. A user who needs Teleport to access infrastructure should not need any cognitive effort to run `tsh login`. Any friction suggests that Teleport is a not-yet-polished tool that is not ready for adoption—if there are mysterious internal errors while using `tsh login`, a user might wonder what other issues might be in store.

## If a workaround exists, please include it.

It's pretty straightforward to try different variations of the `--proxy` URL until `tsh login` accepts one, but this isn't ideal.

**Comment by stevenGravy** [comment]
https://github.com/gravitational/teleport/pull/19641 improves the error messages
