### ISSUE TITLE
Standalone Teleport Kubernetes Operator

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#15014]
The teleport Kubernetes operator should be able to run on its own and not as a sidecar of the Teleport cluster.

This solves the problems:
- Teleport Cloud users want to manage their Teleport resources in an IaC fashion, they want to use the operator for this.
- Running teleport-operator as a side-car harms teleport availability: an issue in teleport-operator will also bring down Teleport (readiness will fail).
- The teleport-operator leader election mechanism is not mixing well with Kubernetes rolling updates: it will hide potential issues until this is too late and all pods but one are rolled-out. Pods will become unready and unavailable, bringing teleport down.
- the teleport-operator resource requirements scale linearly with the number of pods, this makes no sense as only one pod is working and can be expensive for big deployments

Required steps:

- allow the operator to support any join method, use the kubernetes in-cluster join method by default when deployed by the chart
- create a bot token, user and role with the `--apply-on-startup` to bootstrap the operator user when deployed by the chart
- protect against multiple operators pointing to the same cluster ?

**Comment by hugoShaka** [comment]
The potential availability issues caused by the operator can be worked-around on clusters using non-local storage backend:

* create a second release from the `teleport-cluster` chart alongside your existing one
* set 1 replica
* set `service.type: ClusterIP`

In this setup teleport-operator will work against its own dedicated Teleport instance. This instance won't be in the LB pool and can have a different QoS than the rest of the cluster without harming the user's ability to connect if something goes wrong.

**Comment by gunzy83** [comment]
> Teleport Cloud users will be able to manage their resources from Kubernetes without having to self-host Teleport.
We have a cluster that will be hosting the event handler and slack plugin so this would be the perfect location for hosting an operator just for configuration against Cloud. We can then manage the resources as K8s objects using our existing Pulumi toolchain rather than Terraform.
