### ISSUE TITLE
tsh auth server issues OSX 

### ISSUE THREAD

**Issue by KhanMechAI** [gravitational/teleport#15025]
Expected behavior:
`tsh ls` to show list of available nodes. Get other errors for other commands too, but can still `tsh ssh` into nodes.

Current behavior:
❯ tsh ls
ERROR: This server does not implement this feature yet. Likely the client version you are using is newer than the server. The server version: 4.2.9, the client version: 10.0.2. Please upgrade the server.
unknown method ListResources for service proto.AuthService

~ via  on ☁️  (us-east-1)
❯ tsh version
Teleport v10.0.2 git: go1.18.4
Proxy version: 4.2.9

**Comment by strideynet** [comment]
Your server is running `4.2.9` and your `tsh` is `10.0.2`. We only tend to support compatibility forwards/backwards one major version.

Upgrade your server or downgrade your client and this issue will be resolved. I recommend upgrading your server if possible, 4.2.9 is quite old, and you are missing out on security patches and new features !
