### ISSUE TITLE
Support cross-account access to AWS resources

### ISSUE THREAD

**Issue by aidan-canva** [gravitational/teleport#15024]
### What would you like Teleport to do?
Add support for cross account access to AWS resources.  

We use Teleport to connect to RDS instances using IAM authentication.  To reduce the number of trusted clusters and Teleport resources we have to deploy and maintain, we can use services like AWS Transit Gateway to allow a single trusted cluster to gain network level access to multiple AWS accounts.

Currently the Teleport DB nodes assume that the DB resources exist in the same account as them.  If we could add an 'assume_role_arn' to the configuration of each individual database, Teleport could firstly assume that role (which exists in a potentially foreign account) before calling the [`BuildAuthToken` API](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/rdsutils/#BuildAuthToken).

### What problem does this solve?
This would allow us to have a single Teleport trusted cluster that services multiple AWS account's RDS instances.  This would be very useful for us if it also supports other AWS services which Teleport uses IAM based auth to connect to (ie, Redshift).

Reducing the number of Teleport leaf-clusters in our environment greatly reduces the overhead in managing them and our baseline costs for an AWS account/environment.

### If a workaround exists, please include it.
It looks like we might be able to just deploy dedicated DB node(s) in each AWS account rather than having to deploy an entire trusted cluster.  This reduces _some_ of the complexity and _some_ of the cost associated with running Teleport at scale, but could be better.

**Comment by GavinFrazar** [comment]
Closing this as completed in v13.

Guide is here: https://goteleport.com/docs/database-access/guides/aws-cross-account/
