### ISSUE TITLE
Support adding attributes to local users to better support role interpolation

### ISSUE THREAD

**Issue by aidan-canva** [gravitational/teleport#15023]
### What would you like Teleport to do?
When creating and managing local users within Teleport, we should be able to add arbitrary additional attributes to their metadata.  This metadata should then be used as part of the role interpolation in the same way that it is used for SSO users.

### What problem does this solve?
We primarily use SSO (Okta SAML) to authenticate users to our Teleport clusters.  We have a minimal set of simple roles configured in our cluster.  We use attributes from the users SAML assertion to dynamically grant them access to individual resources (ie, individual databases or servers).  This is working well for our SSO users.

We have some use cases where we would like to be able to effectively use local users within Teleport (ie, Okta outage, or user isn't available in Okta) and have them re-use these minimal roles using existing interpolation rules.  To do this, we would need to set attributes on the local user that align with what the Okta SAML response would include if they were an SSO users.

Managing the attributes of a user on the root-cluster is much simpler then managing a role per database they need to access.  This pattern also allows us to not have to replicate specific roles to all Teleport trusted-clusters.

### If a workaround exists, please include it.
I am not aware of any workaround.

**Comment by zmb3** [comment]
> and have them re-use these minimal roles using existing interpolation rules. To do this, we would need to set attributes on the local user

This exists today. These "attributes" are known as _traits_ in Teleport lingo: https://goteleport.com/docs/access-controls/guides/role-templates/#local-users
