### ISSUE TITLE
[v.10.0] /docs/pages/server-access/getting-started.mdx

### ISSUE THREAD

**Issue by mikeh89** [gravitational/teleport#15032]
## Details
Update regex used to retrieve token. 

Currently: (?<=token:\s).*

Replace with: (?<=token:\s)\w*

Why? 
The existing regex also pulls the '.' character after the token. This results in an invalid token.file. 
Using \w instead should still retrieve the alphanumeric token, but will not include the '.' in the token. 

### Category

- Improve Existing

**Comment by zmb3** [comment]
This has been fixed - we no longer print the training `.` character.
