### ISSUE TITLE
[v.10.0] /docs/pages/desktop-access/reference/sessions.mdx

### ISSUE THREAD

**Issue by jiahao19971** [gravitational/teleport#15030]
## Details
https://goteleport.com/docs/desktop-access/reference/sessions/#disable-session-recording-via-rbac 
The `Disable session recording via RBAC` should specify that it is only for Desktop, as SSH recording will still works 
Describe the documentation improvements you wish to see.

### Category
- Improve Existing

**Comment by zmb3** [comment]
@ptgott do you have suggestions for improving this?

The current page shows:

```
    record_session:
      desktop: false
```

But it seems that it's not clear enough that this applies for desktop recording only.

**Comment by zmb3** [comment]
cc @xinding33 I would love to talk about the UX here.

**Comment by ptgott** [comment]
I think the current text is clear enough that this setting applies to desktop session recording. If this is a user's first time learning about our RBAC settings for session recording, though, I could see how it would be possible for a user not to be aware of `record_session` fields for other protocols. Maybe we could add something like this just before the "Recording" section:

```markdown
See the [Teleport Access Controls Reference](https://goteleport.com/docs/access-controls/reference/) for 
all possible settings in the `record_session` section.
```

**Comment by jiahao19971** [comment]
Can I suggest maybe add a note to let users know that if they do:
```
record_session:
      desktop: false
```
ssh will not be disabled
