### ISSUE TITLE
no error given when using --ttl for an access request OR allow user to set -ttl on requests

### ISSUE THREAD

**Issue by WilliamLoy** [gravitational/teleport#15048]
What would you like Teleport to do?
When a user requests role access via CLI and tries to set the `--ttl` , Teleport should produce an error letting them know they can't do that. 

OR

Allow users to set the `--ttl` when requesting role access.

What problem does this solve?
Usability. 

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Specifying `--request-ttl` is supported with tsh: https://goteleport.com/docs/access-controls/access-requests/role-requests/#using-ttls-with-access-requests

**Comment by zmb3** [comment]
See previous comment.
