### ISSUE TITLE
Enable WebAuthn and Passwordless login by default

### ISSUE THREAD

**Issue by sshahcodes** [gravitational/teleport#15079]
### What would you like Teleport to do?
For future Teleport versions, enable WebAuthn and passwordless login option by default. The current default account setup asks users to set a password. We should change this method and make "passwordless" a default while allowing user to opt-in to password-auth. 

### What problem does this solve?
Promoting passwordless auth over password-based. Better user experience (remove extra config step for a task that Teleport can handle as a default)

### If a workaround exists, please include it.
Currently Teleport administrators need to update `teleport.yaml` file manually. This is okay for advanced configuration but for starters, Teleport can just assume `connector_name: passwordless` as a default and use `cluster_name` for `rp_id` in WebAuthn?

**Comment by zmb3** [comment]
Closing this in favor of #19671
