### ISSUE TITLE
Can't add Node

### ISSUE THREAD

**Issue by jsargent8789** [gravitational/teleport#15078]
Expected behavior:
Node shows up the web UI

Current behavior:
Node logs 
```
INFO [PROC:1]    Connecting to the cluster ssh.east.dozecloud.com with TLS client certificate. pid:15485.1 service/connect.go:256
ERRO [PROC:1]    "Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.\n\tconnection error: desc = \"transport: authentication handshake failed: remote error: tls: internal error\", connection error: desc = \"transport: Error while dialing failed to dial: ssh: handshake failed: ssh: no authorities for hostname: ssh.east.dozecloud.com:443\"." pid:15485.1 service/connect.go:113
```

teleport server logs

```
2022-08-01T00:12:46-04:00 WARN [ALPN:PROX] Failed to handle client connection: acme can't get a cert for domain 7373682e656173742e646f7a65636c6f75642e636f6d.teleport.cluster.local, add it to the proxy_service.public_addr, or use one of the domains: ssh.east.dozecloud.com alpnproxy/proxy.go:320

2022-08-01T00:18:08-04:00 WARN [ALPN:PROX] Failed to handle client connection: acme can't get a cert for domain teleport.cluster.local, add it to the proxy_service.public_addr, or use one of the domains: ssh.east.dozecloud.com alpnproxy/proxy.go:320
```

Bug details:
- Teleport version Teleport v10.0.2 git:v10.0.2-0-g47e0914 go1.18.3
- Recreation steps: add node or start teleport service

**Comment by jsargent8789** [comment]
I have reinstalled the OS and teleport no change

**Comment by nmass-betpawa** [comment]
same problem, same version

**Comment by jsargent8789** [comment]
@zmb3 any way that this can be fixed

**Comment by OliverKellyATech** [comment]
I am seeing this today on a server which was previously connected and then rebooted. 

Stopping the teleport client, `rm /var/lib/teleport`, and then restarting does not resolve the issue:

```Aug 31 01:52:41 media teleport[1956]: 2022-08-31T01:52:41Z ERRO [PROC:1]    "Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.\n\tconnection error: desc = \"transport: authentication handshake failed: remote error: tls: internal error\", connection error: desc = \"transport: Error while dialing failed to dial: ssh: handshake failed: ssh: no authorities for hostname: tele.atech.host:443\"." pid:1956.1 service/connect.go:114
```

The Auth Server `tele.atech.host` does have a valid TLS cert.

**Comment by kevit-sunny-anuvadiya** [comment]
Facing same issue with `v10.1.9 git:v10.1.9-0-g8f6f6cc go1.18.3`
![image](https://user-images.githubusercontent.com/53612273/188077072-26332d79-2e12-4dfa-8bc0-a1c5377f5ab6.png)

**Comment by vitorenesduarte** [comment]
@jsargent8789 @nmass-betpawa @OliverKellyATech @kevit-sunny-anuvadiya I'm trying to reproduce this, but so far I wasn't able to.

Could you confirm that this is still an issue in the [latest release](https://github.com/gravitational/teleport/releases/tag/v11.1.0)?

Can you share the steps/configs to reproduce this?

**Comment by russjones** [comment]
@vitorenesduarte If you can't reproduce this, let's move on to something else for now. We can come back to this later once we have a better idea on how we can reproduce.

**Comment by jsargent8789** [comment]
Fixed the latest version of teleport
