### ISSUE TITLE
ssh command blocking is necessary

### ISSUE THREAD

**Issue by RyanCode** [gravitational/teleport#15070]
intercept input command

**Comment by zmb3** [comment]
Hi, could you provide a little more info on what you're requesting here?

**Comment by RyanCode** [comment]
Auditing of ssh sessions is necessary, but should have blocking features. For example, some users are not allowed to use the "docker" command on a certain machine. It can be better configured with some strategies

**Comment by zmb3** [comment]
Got it - this is captured in #12117 so I will close as a duplicate.
