### ISSUE TITLE
intermittent error while connecting  to auth server

### ISSUE THREAD

**Issue by Miki-mi** [gravitational/teleport#15077]
We usually don't have any problems from doing ssh or login to using `tsh login`. But lately we experienced some error while doing them.

Expected behavior:
get this response

```
  Profile URL:        https://teleport.******.com:443
  Logged in as:       
  Cluster:           
  Roles:             
  Logins:             
  Kubernetes:     
  Valid until:        
  Extensions:         
```

Current behavior:
get this response
`ERROR: connection error: desc = "transport: Error while dialing failed to dial: failed connecting to node . unable to connect to auth server\n"`

Bug details:
- Teleport version
`Teleport v8.3.7`

- Recreation steps
`tsh login --proxy=teleport.*********.com:443 --user=abc` or `tsh ssh root@****` or SSH connect using Teleport GUI

- Debug logs
```
Jul 29 15:43:00 15708] *****: 2022-07-29T15:43:00Z ERRO [NODE]      unable to connect to auth server regular/sshserver.go:1771

Jul 29 09:43:14 ***** teleport[15708]: 2022-07-29T09:43:14Z WARN [PROXY]     Subsystem request proxySubsys(cluster=default/*****, host=, port=) failed: unable to connect to auth server. id:1043 local:***** login:root remote:***** teleportUser: regular/sshserver.go:1581
```

**Comment by hryan-ib** [comment]
We are also experiencing this exact issue. Intermittent failures with that same log. Doing `tsh logout` and purging any teleport cache files does not help to fix this.
