### ISSUE TITLE
Trigger an alert system for use of some specific commands during Server or Kubernetes Access session

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#15082]
What would you like Teleport to do?
A feature that explicitly trigger an alert system when specific commands are executed on nodes.

What problem does this solve?
Continuous monitoring for all commands used and executed inside production nodes. 

If a workaround exists, please include it.
[Moderated Sessions
](https://goteleport.com/docs/access-controls/guides/moderated-sessions/)

gz#6056

**Comment by r0mant** [comment]
@oshati Our recommended solution to use enhanced session recording and event handler to ship events to an external SIEM that can create alerts for you. It is unlikely that this functionality will be built into Teleport natively in the near future.
