### ISSUE TITLE
`TestIntegrations/SessionRecordingModes/StrictMode` flakiness

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#15097]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds;region=us-west1/ade1ffc4-de37-4868-942b-66a700b1b9f3;step=0?project=ci-account

#### Relevant snippet

```
    integration_test.go:867: 
        	Error Trace:	integration_test.go:867
        	            				integration_test.go:928
        	Error:      	Condition never satisfied
        	Test:       	TestIntegrations/SessionRecordingModes/StrictMode/BeforeStartFailure
            --- FAIL: TestIntegrations/SessionRecordingModes/StrictMode/BeforeStartFailure (10.00s)
===================================================
```

**Comment by zmb3** [comment]
@gabrielcorado I'm still encountering this on branch/v10, could you backport to all applicable branches please?

**Comment by gabrielcorado** [comment]
Sure. Here is PR (You're marked as a reviewer): https://github.com/gravitational/teleport/pull/15221
