### ISSUE TITLE
[bot] Apply backport labels automatically to docs PRs

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#15103]
## What would you like Teleport to do?

We usually need to backport each docs PR to at least one other versioned branch, and often all of the versioned branches we currently support.

For docs PRs, our GitHub Actions automation currently applies the `documentation` label. We could adjust this to also apply the `backport/branchv[0-9]+` label for each branch we currently support. We can change the bot's configuration file to include the backport labels to add. This way, we wouldn't need to remember to add backport labels, and could either (a) remove the appropriate labels before merging a PR or (b) delete any unnecessary/incorrect backport branches that the bot automatically generates.

## What problem does this solve?

While the label-based backport mechanism makes backporting super straightforward, it's possible to forget to add backport labels. If someone does forget, they also need to remember to use another mechanism to execute the backport later on. This leads to inconsistencies in how we backport PRs.

## If a workaround exists, please include it.

PR authors can set calendar reminders for backporting PRs. The issue is that we have no way to standardize this across docs contributors.

**Comment by alexfornuto** [comment]
I like this, because seeing an incorrect label and removing it is a lot more likely to happen than always remembering to add it. Plus, there are more steps in a backport getting merged, so more opportunity to stop false positives.

**Comment by ptgott** [comment]
Closing since we won't be implementing this (see the discussion gravitational/shared-workflows#82)
