### ISSUE TITLE
Way to provide links to specific hosts in the web UI

### ISSUE THREAD

**Issue by aashley** [gravitational/teleport#1511]
We use teleport to manage nodes in our distributed systems, I'd like to provide a way to link from our management interface direct to the teleport web interface for a specific node to assist our support staff.

From our side we know the name of the node and can figure out the name of the cluster it's in, is there a way to generate a URL that will open the teleport Web UI on a console for that node, or to the list of nodes within that cluster?

**Comment by alex-kovoy** [comment]
You can construct an URL to a particular node terminal with the following:
https://host:3080/web/cluster/:clusterName/node/:nodeId/:login

where **:clusterName** is your cluster name, **:nodeId** is your node id, and **:login** and a login name.

WebUI will create a new SSH session with above parameters. 

I suggest to open a terminal in Web UI and examine\play with the URL. You can also use the existing session URL to send it others to share your _existing_ session.

**Comment by klizhentas** [comment]
I would leave this ticket open as an opportunity to improve this, e.g. there is an icon "get shareable link" for Google docs. I think it will be cool if we added something similar to that to promote session sharing. @kontsevoy what do you think?

**Comment by aashley** [comment]
@alex-kovoy was this fixed in 2.3 or later? Playing in the web UI is where I went straight away however 2.2 uses an internal guid for the nodeId and does not accept the hostname as a nodeId

**Comment by aashley** [comment]
I'm not trying to connect to a SSH node, I'm trying to connect to a teleport node.

As per your note I generate a URL:
https://teleport:3080/web/cluster/od-server-00183/node/od-server-00183/root

This gives a console with disconnected at the top of the screen and nothing happens.

The links in the teleport UI are:
https://teleport:3080/web/cluster/od-server-00183/node/bb757478-7d26-48db-9d77-51cd71cc6e48/root

The node ID used in teleport appears to be an internal guid which I can't retrieve to generate a link

**Comment by alex-kovoy** [comment]
Sorry, we added a [hostname resolution ](https://github.com/gravitational/teleport/blob/master/lib/web/terminal.go#L279)for a terminal node in 2.3.5 release.

**Comment by kontsevoy** [comment]
@aashley yes, this works in the newer Teleport versions, but to make it more obvious, we've created #1514

Closing....
