### ISSUE TITLE
ERROR: pull access denied for teleport, repository does not exist or may require 'docker login' ERROR: pull access denied for teleport, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by tuanbo91** [gravitational/teleport#1513]
I've built base image then run make, got below issue:

ERROR: pull access denied for teleport, repository does not exist or may require 'docker login'

**Comment by kontsevoy** [comment]
@tuanbo91 we do not support / maintain Docker images for teleport because Teleport is not supposed to run in a container. The repository you've used before was probably created by someone else and maybe they removed it?
