### ISSUE TITLE
Drop support for SHA1

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#15149]
Drop SHA1 support so customers don't have to put workarounds in SSH Config for OpenSSH clients to connect to Teleport.

Requires the following PR to be merged in `crypto/ssh`:

* https://github.com/golang/crypto/pull/211
* https://go-review.googlesource.com/c/crypto/+/396714

**Comment by zmb3** [comment]
@r0mant @jakule good to close this one?

**Comment by jakule** [comment]
SHA-1 was dropped as a part of https://github.com/gravitational/teleport/pull/19579 and released in Teleport v12.0.1
