### ISSUE TITLE
Use hostname / IP in a host URLs by default, instead of GUIDs

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1514]
## Intro

Currently Teleport can open a web-based terminal for any node using the following URL format:

```
https://proxy.example.com:3080/web/cluster/:cluster_name/node/:node_id/:user
```

`node_id` can be one of [`node_uuid`, `hostname`, `node_ip`] basically anything a node can be addressed by. 

## Current behavior

The web UI generates these URLs using node GUIDs. They aren't intuitive for users who wish to use their own.

## Suggestion

Use hostname instead.

**Comment by klizhentas** [comment]
would be also nice to have a way to get a "shareable link" by clicking on some button/icon alongside the list of teleport servers, just like for google docs.

**Comment by kontsevoy** [comment]
@klizhentas rick clicking on any link in a browser gives you "copy URL" menu item. Apps that do this _must_ provide this clutch because they usually do not have reusable links. Luckily Teleport UI doesn't have this problem.
