### ISSUE TITLE
Server Access integration for Azure

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#15150]
* Teleport automatically imports node labels when running on Azure VMs
* Teleport nodes can join cluster without using tokens (analogue IAM/EC2 method)
* Teleport can automatically discover and enroll Azure VMs similar to https://github.com/gravitational/teleport/pull/12410

Fixes https://github.com/gravitational/teleport/pull/16218.

**Comment by zmb3** [comment]
This is implemented
