### ISSUE TITLE
Teleport Connect Advanced Search Support

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#15169]
Add advanced search to Connect.

**Comment by ravicious** [comment]
I updated the description from "Redesign search experience (spotlight-like search)" to just "Add advanced search to Connect" because this task specifically is not about spotlight-like search.

**Comment by ravicious** [comment]
@avatus Was this issue supposed to be closed by that PR? AFAIK the PR https://github.com/gravitational/webapps.e/pull/396 added access requests, not advanced search.

**Comment by avatus** [comment]
This issue was not meant to be closed. Thank you
