### ISSUE TITLE
Move webapps code into teleport, and webapps.e into teleport.e

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#15164]
Let's start with an RFD to ensure we aren't breaking any existing workflows.

Things to consider:

- Open issues: should we migrate these as well?
- Open PRs: try to merge or close anything outstanding first
- CI/CD: try to avoid breaking the build or disrupting devs from merging
- Auto backports: will Teleport's existing machinery just work?
- Git history: do we care about retaining this? Can we?
- webassets: do we continue to submodule in a compiled version of the webapps or is there a better approach?

RFD: https://github.com/gravitational/teleport/blob/master/rfd/0089-merge-webapps.md

Tasks: 
- [x] Merge webapps into teleport (fork).
- [x] Merge webapps enterprise into teleport enterprise (fork).
- [x] Create dockerfile for building webapps (fork).
- [x] Remove `build.assets/webapps` (fork).
- [x] Modify scripts to build OSS with new dockerfile and folder structure (fork).
- [x] Modify scripts to build enterprise with new dockerfile and folder structure (fork).
- [x] Investigate what happens with in-flight PR's on a merged repo (fork).
- [x] Create GitHub action to build & test
- [x] Test drone config on merge branch to ensure a successful build (fork).
- [x] ~Create single GitHub action for building webassets to speed up subsequent builds.~
- [x] Generate how-to document.
- [x] Draft email to team about upcoming change.
- [x] Perform webapps into teleport merge.
- - [x] `master`
- - [x] `v12`
- - [x] `v11`
- - [x] `v10`
- [x] Merge changes into teleport repository.
- [x] Perform webapps enterprise into teleport enterprise merge.
- [x] Merge changes into teleport enterprise repository.
- [x] Repair any potentially failing CI jobs.

Post-migration:
- [ ] Triage and migrate issues in webapps repository.
- [ ] Triage and migrate issues in webapps enterprise repository.
- [ ] Archive webapps repository.
- [x] Triage and migrate pull requests in webapps repository.
- [x] Triage and migrate pull requests in webapps enterprise repository.
- [ ] Archive webapps enterprise repository.
- [x] Remove `DEBUG` and `DEBUG_ASSETS_PATH` as they are no longer necessary.
- [x] Update homebrew config to reflect new webassets setup.
- [x] ~Update slab pages re: webassets.~

**Comment by hatched** [comment]
Tasks: 
- [x] Merge webapps into teleport (fork).
- [x] Merge webapps enterprise into teleport enterprise (fork).
- [x] Create dockerfile for building webapps (fork).
- [x] Remove `build.assets/webapps` (fork).
- [x] Modify scripts too build OSS with new dockerfile and folder structure (fork).
- [ ] Modify scripts too build enterprise with new dockerfile and folder structure (fork).
- [ ] Investigate what happens with in-flight PR's on a merged repo (fork).
- [ ] Point drone at forked repositories to ensure a successful build (fork).
- [ ] Draft email to team about upcoming change.
- [ ] Perform webapps into teleport merge.
- [ ] Merge changes into teleport repository.
- [ ] Perform webapps enterprise into teleport enterprise merge.
- [ ] Merge changes into teleport enterprise repository.
- [ ] Repair any potentially failing CI jobs.
- [ ] Triage and migrate issues in webapps repository.
- [ ] Triage and migrate issues in webapps enterprise repository.
- [ ] Archive webapps repository.
- [ ] Triage and migrate pull requests in webapps repository.
- [ ] Triage and migrate pull requests in webapps enterprise repository.
- [ ] Archive webapps enterprise repository.
- [ ] Change `DEBUG` and `DEBUG_ASSETS_PATH` in teleport to better reflect the new folder structure (fork).
