### ISSUE TITLE
Add linter for protobuf

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#15187]
## Success criteria

- [x] Protobuf specs are run through a linter during CI

**Comment by strideynet** [comment]
I've had great success leveraging Buf Lint for this in the past: https://docs.buf.build/tour/lint-your-api

We will need to determine what rule set we want to lint with. I have a feeling that their strictest ruleset will likely not be compatible with our existing protos, and it may not be able to change them to be abiding by the rules without making breaking changes, so we may need to tweak the rules.

They also offer a breaking change detector which may also be invaluable: https://docs.buf.build/tour/detect-breaking-changes

**Comment by codingllama** [comment]
Hijacking this issue for the ongoing Buf changes. It is technically correct (we are adding a linter), but going a bit beyond and reorganizing protos too.

**Comment by codingllama** [comment]
After #15961 I think we can call this closed. There's more we could do, but these are incremental improvements - linting is in full effect in master and soon-to-be in v10.

**Comment by russjones** [comment]
@codingllama Since this is done I am going to close it, feel free to re-open if needed.
