### ISSUE TITLE
Implement Teleport Discover "day 1" experience

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#15181]
## Success criteria

- [x] Users can add a Server and test connection to it using guided UI wizard.
- [x] Users can add a Database and test connection to it using guided UI wizard.
- [x] Users can add a Kubernetes cluster and test connection to it using guided UI wizard.
- [ ] Users can add an Application and test connection to it using guided UI wizard.
- [x] Users can add a Desktop and test connection to it using guided UI wizard.
- [x] Users can configure and test access without leaving the Discover UI.
- [x] Users should not have to reference documentation outside of the Discover UI.

**Comment by zmb3** [comment]
Closing as we are no longer using this as a tracking issue.
