### ISSUE TITLE
K8s Active Session shows 2 users connected

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#15211]
Expected behavior:
When issuing a kubectl exec command in Active Sessions it show the correct users who are connected. Currently it will show 2 of the same users connected and when the recording is done and in Session Recordings it will show only the user who was connected.

Current behavior:
When issues kubectl exec it shows 2 users in the session under Active Sessions

Bug details:
- Teleport version - 10.0.1
- Recreation steps - Issue a kubectl exec into a pod and look under active sessions at the users who are connected.
- Debug log
<img width="1166" alt="Screen Shot 2022-08-04 at 1 30 07 PM" src="https://user-images.githubusercontent.com/51385814/182914326-ee44ea5d-8a0a-44b8-aa99-71c0df78567e.png">
<img width="1168" alt="Screen Shot 2022-08-04 at 1 30 28 PM" src="https://user-images.githubusercontent.com/51385814/182914337-1246399f-fa70-4196-914d-9a89d47fd8a6.png">
s

**Comment by zmb3** [comment]
@xacrimon this looks related to session trackers / moderated sessions.

**Comment by xacrimon** [comment]
@scottpgallagher Hi, I can't replicate, do you have any more detailed instructions? Did you join the session using `tsh kube join` too?

I:
1. checkout v10.0.1
2. build teleport and added a standalone minikube cluster
3. logged into the cluster using tsh on the cli
4. executed `kubectl --insecure-skip-tls-verify exec -it nginx -- /bin/bash` to start an interactive session
5. looked in the sessions tab
<img width="1197" alt="Screenshot 2022-08-05 at 13 24 11" src="https://user-images.githubusercontent.com/21025159/183067760-5eb73687-64ff-43ef-bf32-fb8ed47a55e6.png">

**Comment by zmb3** [comment]
I think @rosstimothy saw similar issues in a recent load test.

**Comment by webvictim** [comment]
I believe this happens when a v9 agent is connected to a v10 cluster. I haven't seen it on v10 -> v10 traffic.

**Comment by xacrimon** [comment]
I believe this is fixed as of the latest v9/v10 releases. I have not managed to reproduce this on v9-v9 or v10-v10 traffic clusters and not with v9-v10-v10 node-proxy-auth either.
