### ISSUE TITLE
Write a guide to explain how to deploy Teleport with Cloudformation

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#15213]
## Details

We have an [undocumented cloudformation stack](https://github.com/gravitational/teleport/tree/master/examples/aws/cloudformation), the README mostly covers how to deploy itm this should be part of the documentation.

Biggest missing parts are:
- how to configure region
- how to create a new user after install

### Category
- New Feature

**Comment by zmb3** [comment]
We deprecated the cloudformation stack - so nothing left to document.
