### ISSUE TITLE
Add light theme to web UI

### ISSUE THREAD

**Issue by rajeshisnepali** [gravitational/teleport#15234]
What would you like Teleport to do?
There is only one default dark blue theme and it is very hard to view items. Also the default font size is small. Can you please add an option for more color themes and increase the font-size by 1px.

What problem does this solve?
This will be helpful to anyone who is viewing the panel for an extended period of time. Fewer eye strains.

**Comment by thg-adamdean** [comment]
Or particular interest to me as I have a tough time reading light text on dark backgrounds thanks to eye issues, makes Teleport a chore to use.

**Comment by rudream** [comment]
Thanks for the request! A light theme will be available in Teleport 13.0 🙂
