### ISSUE TITLE
MongoDB Atlas option missing from Teleport UI.

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#15245]
Expected behavior:

When you are using the Telport UI and try to add a new database there is a dropdown with some supported options. Self-hosted Mongo is listed but Atlas is not listed.

Current behavior:

Nothing shows for Atlas on the dropdown (although it is supported in Teleport cloud):

![Screen Shot 2022-08-05 at 10 23 17 AM](https://user-images.githubusercontent.com/1424442/183097260-abf5a002-9783-49cc-8b55-d24e6de67396.png)

Bug details:
- Teleport version: `v9.3.10` (Teleport Cloud)
- Recreation steps: Go to Add Database, select dropdown

**Comment by zmb3** [comment]
<img width="840" alt="image" src="https://github.com/gravitational/teleport/assets/7527103/fe654b44-8a5c-4331-9de6-443042eed9de">

It's there now.
