### ISSUE TITLE
Support for running the AWS proxy on a non-localhost address

### ISSUE THREAD

**Issue by philchristensen** [gravitational/teleport#15282]
**What would you like Teleport to do?**
I would like to be able to run the `tsh proxy aws` service on the `0.0.0.0` interface instead of `localhost`.

**What problem does this solve?**
This would allow me to run the proxy in a Docker container, making it easier to work with multiple accounts and multiple proxies.

**If a workaround exists, please include it.**
There doesn't seem to be any workaround, to access a port inside a container it must be running on the `0.0.0.0` interface, not localhost

I'd suggest adding a `-I, --interface` option that would default to `127.0.0.1` but could be overridden with `0.0.0.0` or other interface.

**Comment by philchristensen** [comment]
Was thinking about this a bit, and I think this would be generally useful for all the proxy types, not just AWS.

**Comment by programmerq** [comment]
This is a security concern, so it is recommended to implement a workaround solution for this type of use case.

Some possible workarounds include:

* run the container in host mode networking so its localhost is the same as the docker host's localhost.
  ```
  docker run --rm -it --net=host ... tsh proxy app
  ```
* run a socat process inside the container:
  ```
  docker run --name tshproxy -d -p 55000 myimage tsh proxy app -p 55001
  docker exec tshproxy socat tcp-listen:55000,reuseaddr,fork tcp:127.0.0.1:55001
  ```

**Comment by philchristensen** [comment]
Hmm, the first option is a nonstarter because host mode doesn't work on Docker Desktop.

Socat really looks like it should do the trick though, I'll report back.

**Comment by philchristensen** [comment]
oh yes, that certainly does the trick!

well, I'm fine with closing this ticket, then.
