### ISSUE TITLE
Disable dormant/inactive accounts

### ISSUE THREAD

**Issue by weom** [gravitational/teleport#15299]
### What would you like Teleport to do?
Implement account expiry for inactive users(local teleport users). e.g if a user has not logged in for X amount of days, the account will be disabled. 

### What problem does this solve?
Policies e.g CIS states that the focus of this control will ensure accounts are managed in a fashion that promotes clean account hygiene.  See https://csf.tools/reference/critical-security-controls/version-8/csc-5/csc-5-3/

**Comment by zmb3** [comment]
Thanks for the feature request. Sounds like a reasonable idea, though most people solve this by using an external IdP for SSO rather than Teleport local users.

**Comment by klizhentas** [comment]
Yes, we suggest to delegate this to SSO provider instead.
