### ISSUE TITLE
tctl should have a WARN log level by default

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#15329]
https://github.com/gravitational/teleport/pull/9265 - this was merged last December, but the message is silenced unless tctl is in debug mode even though the message is logged at the WARN level.

For the message to successfully warn the user that something unexpected to happen, it should be printed by default rather than only during situations where debug is set.

current:

```
tctl auth sign --user=terraform --out=auth.pem --ttl 17520h

The credentials have been written to auth.pem
```

expected:

```
tctl auth sign --user=terraform --out=auth.pem --ttl 17520h

The credentials have been written to auth.pem
            WARN Requested TTL of 17520h0m0s was not granted. User may have a role with a shorter max session TTL or an existing session ending before the requested TTL. Proceeding with 29h59m59s common/auth_command.go:748
```

**Comment by ChrHan** [comment]
I might have a working implementation, although I'm not too sure if the change is correct - I'll refer this issue on the pull request

**Comment by russjones** [comment]
Let's not just turn on warning logs, instead return a human readable message.

So this ticket won't be a general fix for this issue, but rather fixing this specific instance a bad error message (or lack of error message).
