### ISSUE TITLE
Include the node name in all server session audit log descriptions

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#15338]
What would you like Teleport to do?

Include the node name (`server_hostname`) in all server session audit log descriptions, i.e. append "on node [`server_hostname`]" to all descriptions of server events.

What problem does this solve?

Allows users to search for all audit log events on a certain server/node. Currently users can only search by session ID (`sid`) to see all events for a session. Searching by node name (`server_hostname`) only returns the 'Session Ended' event (with a link to the Session Recording).

![Screenshot 2022-08-09 at 09 43 52](https://user-images.githubusercontent.com/95687564/183606325-81a5ddd2-d24d-4d1a-b45c-3d48bcc5e925.png)
![Screenshot 2022-08-09 at 09 44 02](https://user-images.githubusercontent.com/95687564/183606410-c938928f-5685-423b-af29-8550958d2943.png)

If a workaround exists, please include it.

Integrate with a SIEM solution and implement queries there.

**Comment by philip-teleport** [comment]
Related to https://github.com/gravitational/teleport/issues/8042 - searching by node name should also return command executions.

**Comment by zmb3** [comment]
Closing as a duplicate of #3251
