### ISSUE TITLE
Package Teleport in .msi?

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#15332]
What would you like Teleport to do?
We currently offer Teleport as a .exe file, this is Ok but if you look at my Install Video. https://youtu.be/XH047Qc45xs?t=70  You have to move it to Program files and if you do double click it ( you're not meant to, it throws a strange error ) 

It would be nice to have a .msi installer  https://docs.microsoft.com/en-us/windows/win32/msi/windows-installer-portal that would put tsh.exe into program files and also bundled in Teleport Connect. 

What problem does this solve?
Onboarding, make it nicer for Windows users. 

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Are you referring to the teleport daemon or Teleport Connect here?

AFAIK, the only exe we ship today is tsh.exe.

**Comment by webvictim** [comment]
I think a `.msi` installer to automatically install `tsh.exe` into a known path and make it accessible via `%PATH%` in Powershell or `cmd.exe` could be a good idea. Teleport Connect already has a `.exe` installer, but `.msi` packages are preferred by Windows admins for automated deployment via GPOs.

**Comment by zmb3** [comment]
See also #12616

**Comment by zmb3** [comment]
Closing in favor of #12616
