### ISSUE TITLE
Manually adding server instructions fail on fresh Ubuntu install

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#15343]
Expected behavior:

Following the web UI Manually Add Server instructions should successfully configure and launch Teleport

Current behavior:

1. Copy the command from Step 2: `teleport configure --output=$HOME/.config/node_config.yaml --roles=node --token=<token> --auth-server=<server> --data-dir=$HOME/.config`
2. Run the command on a fresh install of Ubuntu
3. Get an error that `$HOME/.config` does not exist

**Comment by jimbishopp** [comment]
Assume we only need to add a `mkdir`.

**Comment by mcbattirola** [comment]
Hi, I've fixed this in the master branch here https://github.com/gravitational/teleport/pull/14691

It ended up not getting into v10, so I opened a backport https://github.com/gravitational/teleport/pull/15352

**Comment by zmb3** [comment]
Should this be on v9 too?

**Comment by mcbattirola** [comment]
I think it is worth it, yes
v9 backport: https://github.com/gravitational/teleport/pull/15386
