### ISSUE TITLE
`tsh login` instruction for database access includes `--auth=local` for passwordless user

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#15353]
Expected behavior:
The recommended `tsh login` instruction should work for passwordless users, and should not include the `--auth=local` flag. The `--auth=passwordless` flag should probably be shown instead.

Current behavior:
<img width="656" alt="Screen Shot 2022-08-09 at 12 40 37 PM" src="https://user-images.githubusercontent.com/16807901/183747237-31ee1084-1e89-465e-991e-a4b1eda944ee.png">

The current recommended `tsh login` includes the `--auth=local` flag, and `tsh` prompts for a password, which this user does not have.

Bug details:
- Teleport version: 10.1.2
- Recreation steps:
  1. Log in to Teleport Web UI with a passwordless user.
  2. Click the "CONNECT" button for a database in the database tab of the Web UI
  3. Attempt to run the recommended login command.
- Debug logs

**Comment by djanda97** [comment]
Is this issue up-for-grabs?
If so, I can take a shot at fixing it.
I just discovered Teleport this past week and I would love the chance to contribute.

**Comment by tobiaszheller** [comment]
@djanda97 hello, sorry for late response. Are you still interested in solving that issue?

**Comment by djanda97** [comment]
Hi @tobiaszheller!

Yes, I am still interested in working on this issue and am looking forward to learning the codebase. This is my first time contributing to Teleport, so I will follow the `README` instructions in order to get a development environment up and running.

Pertaining to this issue, the `Databases/ConnectDialog` component (from the webapps repo) seems like a good place to start looking at since the `connectCmd` string variable conditionally evaluates based on the `authType` prop.

**Comment by tobiaszheller** [comment]
@djanda97 seems that you have found correct place to fix it. Let me know if you need anything else to solve it

**Comment by tobiaszheller** [comment]
Hi @djanda97 how is it going with task? Do you need any help?

**Comment by djanda97** [comment]
Hi @tobiaszheller, I'm on vacation and don't have access to my laptop. I'll submit a PR for this issue sometime next week!

**Comment by djanda97** [comment]
Hi @tobiaszheller, I've opened a PR with the proposed changes previously mentioned in this thread.
I would appreciate feedback, as well as any suggestions for how to test these changes.
PR: https://github.com/gravitational/webapps/pull/1431
