### ISSUE TITLE
Change Access Workflow When Deleting Access Requests

### ISSUE THREAD

**Issue by kylern** [gravitational/teleport#15356]
What would you like Teleport to do?

If upon deleting access requests, the user who requested access immediately loses permission, without a need to suddenly log out and log back in.

What problem does this solve?

Currently, deleting an access request doesn’t remove the permissions a user has to fully lock the session. The user has to log out and log back in, only then changing the access.

**Comment by zmb3** [comment]
If you want to prevent users with approved access requests from using those elevated permissions, the mechanism to achieve that is to create a lock, not to delete the access request. (Once the user has an elevated certificate, the presence or absence of an access request is irrelevant).

In fact, if you try to delete an approved access request, Teleport will detect that you're probably doing the wrong thing and will suggest that you create a lock instead:

https://github.com/gravitational/teleport/blob/4c2fe9ae09be45f1299fe9c28b53ce77869b63ee/tool/tctl/common/access_request_command.go#L308-L314
