### ISSUE TITLE
Add personalized view of resources in the Web UI

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#15369]
Customer has requested the ability to create a personalized view of resources in the Web UI.

For example, a user should be able to favorite servers and have them show up in their personalized dashboard view.

Should show all protocols.

**Comment by russjones** [comment]
Needs input from Product on exactly what would be implemented.

**Comment by WilliamLoy** [comment]
I received a similar request from a customer wanting to organize resources into folders in the Web UI.

**Comment by pschisa** [comment]
another +1 for customer wanting to organize servers in the Web UI/Teleport Connect
