### ISSUE TITLE
Teleport version improvements

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1538]
Running teleport version confuses users because it tries to init config (never using it) and returns the following output:

```
container(94b50f508213) /: teleport version
Teleport Enterprise v2.5.0-alpha.1 git:v2.5.0-alpha.1-5-g56aa615-dirty
auth_servers is empty, configuration error.
```

**Comment by dhilipkumars** [comment]
it doesnt happen in master
```
./build/teleport version
Teleport v2.5.0-alpha.2 git:v2.5.0-alpha.2-49-g1607d32
```
Looks like an enterprise only problem? Does Label `P2` mean production or Priority?

**Comment by klizhentas** [comment]
I think this happens when teleport config is missing, because that's what it tries to locate.
 P0 highest, P1 - medium, P2 - lower

**Comment by dhilipkumars** [comment]
Unable to re-produce in a linux box.
