### ISSUE TITLE
docs: Entreprise sso section "Configuring SSO" is broken since v10

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#15391]
## Details

The entreprise SSO page is broken for versions 10 and 11, the "Configuring SSO" section does not render properly, likely because of the recent scope changes.

Broken page: https://goteleport.com/docs/ver/10.0/enterprise/sso/#configuring-sso

What the page should look like (manually adding scope in the url): https://goteleport.com/docs/ver/10.0/enterprise/sso/?scope=enterprise#configuring-sso

### Example 1

The list of supported connectors only contains `github`. `saml` and `oidc` are not rendered. There is no selector to switch the doc scope from "OSS" to "Entreprise" on this page.

![image](https://user-images.githubusercontent.com/16366487/183984261-73910270-9524-4459-8324-23c3dcff3efa.png)

The output should be

![image](https://user-images.githubusercontent.com/16366487/183984609-bed7cc55-e10b-4e65-b231-ae80060b6de5.png)

### Example 2

The "Creating an authentication connector" section is mostly not rendered, the instructions don't make sense but this is not obvious.

The correct flow should be:
- Set auth type (either though `cap` or static config
- Write the manifest for your connector
- Create the connector from the manifest

Page currently looks like: 
![image](https://user-images.githubusercontent.com/16366487/183986391-c10c2629-d4b9-48df-ab7d-4794277b567f.png)

The page should be:
![image](https://user-images.githubusercontent.com/16366487/183986837-caec6719-7a7a-4fff-9080-a050003b2664.png)

### Category
- Bug

**Comment by ptgott** [comment]
Closed as resolved
