### ISSUE TITLE
Add activity badge with number of open access requests to web UI

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#15393]
**What would you like Teleport to do?**

Add an activity badge to the "Access Requests" menu when there are open access requests waiting that the logged in user has the permission to approve.

Mockups:
![image](https://user-images.githubusercontent.com/897821/183991978-da1b4f25-d6b9-4914-ad9f-deeb3ef5e6c9.png)

![image](https://user-images.githubusercontent.com/897821/183991623-c304e7a5-25dd-44fb-9d93-59b646e63c50.png)

**What problem does this solve?**

Makes it easier to notice at a glance that access is being requested and grant approval in a timely fashion.

**If a workaround exists, please include it.**

Use plugins for notification of access requests.

**Comment by zmb3** [comment]
Teleport Connect is going to have indicators for this purpose. Let's wait until that is complete so we can ensure we have consistent UI elements in the web UI too.

**Comment by zmb3** [comment]
We solved this with the notifications system instead. Similar use case, different solution.
