### ISSUE TITLE
Remove `admin` role from enterprise/pro

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1540]
This role is useless for enterprise and pro versions - has no real privileges, but is called admin. People get confused.

**Comment by klizhentas** [comment]
Also, deleting the role leads to strange output:

```bash
$ tctl rm roles/admin
role admin has been deleted
deleting resources of type "role" is not supported
```

**Comment by klizhentas** [comment]
tctl version
Teleport Enterprise v2.5.0-alpha.2 git:v2.5.0-alpha.2-0-gdc44b76

**Comment by kontsevoy** [comment]
Ok, the description of this ticket needs to be expanded. It makes sense to NOT have this built-in role for RBAC-enabled builds, but the use case I am worried about is when OSS users upgrade to Enterprise. What do we do in this case?

**Comment by klizhentas** [comment]
I don't know, we can cancel this ticket or may be just improve the docs on the upgrade from OSS to enterprise to tell users to write their own roles after upgrade and update users then? so could be simply documentation issue.

**Comment by kontsevoy** [comment]
Per discussion with @klizhentas: we've decided not to mess with it, because it's just a trivial thing to document: when a OSS user upgrades to enterprise, they need to update the built-in "admin" role to their linking.
