### ISSUE TITLE
tsh logout

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1541]
## Logout

```
# In case if user is logged in as `bob@example.com`, but current shell username is `bob`,
# this will be effect
tsh logout
bob is not logged in
```

Instead, `tsh logout` should just clean up all ~/tsh folder basically logging user out at all times.

**Comment by kontsevoy** [comment]
regression: `tsh logout` does not remove certs from the SSH agent. when testing this, please make sure it handles `--proxy` flag properly
