### ISSUE TITLE
Documentdb/ Mongodb connection error

### ISSUE THREAD

**Issue by Aur0nd** [gravitational/teleport#15410]
Expected behavior:
Able to connect to DocumentDB with "tsh proxy db DbName"

Current behavior:
![image](https://user-images.githubusercontent.com/71910902/184094432-23adc864-d4c7-473d-944d-b1fb4ce1e5f1.png)

Bug details:
- Teleport version 
latest:10
- Recreation steps
- Debug logs
When I try to use no TLS/SSL in my compass I get the error below:
Error: User Message: tls: unsupported SSLv2 handshake received] alpnproxy/proxy.go:322

When I try to use the .pem files teleport prints out I get the below:
error:[access to db denied]

Notes:
I've installed nginx and port forwarded the teleport connection and it works that way. - so there's definitely something wrong with teleport. (or my config)

**Comment by greedy52** [comment]
Duplicate of #11665
