### ISSUE TITLE
Remove CI/CD dependency on docker socket/docker shim

### ISSUE THREAD

**Issue by fheinecke** [gravitational/teleport#15440]
Kubernetes version 1.24 removes the Docker CRI (and therefor the `/var/run/docker.sock` socket) which our current Drtone pipelines rely on extensively for Docker-in-Docker. Additionally GKE 1.23 adds additional related restrictions that may impact us, preventing us from bumping up even to the next minor version.

To fix this we will need to replace the Docker CRI (probably with containerd) on each node, and update all of our Drone pipelines accordingly. This is not limited to Teleport itself, but all of our repos that build on Drone. Given the magnitude of this change and some talks about moving everything to AWS, we may want to consider creating a new Drone cluster on AWS and migrating each repo one at a time.

**Comment by wadells** [comment]
> To fix this we will need to replace the Docker CRI (probably with containerd) on each node

We already use containerd for all our drone nodepools:

![image](https://user-images.githubusercontent.com/187314/193766023-b754c9ca-75d4-4c0f-be5f-cd131c1061b3.png)

`/var/run/docker.sock` comes from the DIND container, not the host itself.  Not to say we sholdn't ditch DIND -- that is https://github.com/gravitational/teleport/issues/8269

**Comment by r0mant** [comment]
Won't be relevant once we migrate to Github Actions.
