### ISSUE TITLE
Publish join tokens to parameter store

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1546]
Publish and rotate join tokens to SSM parameter store and show how nodes can use the data to join the cluster.

**Comment by kontsevoy** [comment]
Implementation proposal:

```
auth_service:
    token_publish: /path/to/executable {{token}} {{purpose}}
```

Where "token" gets substituted with the generated token and "purpose" is one of the same values we already use in "tokens" section, i.e. "node", "user", etc. 

This provides a generic way for forwarding tokens dynamically to external secret store on any infrastructure. Also, users can stick their own additional arguments in-between our own.

**Comment by kontsevoy** [comment]
Implementation proposal 2: "Inversion of control"

Instead of pushing Teleport-generated tokens, consider an external source of token. This way we need to add --token parameter to `tctl node add`, which a user will fetch from an external token-generated source, the same one nodes we'll use.

**Comment by klizhentas** [comment]
for the first proposal, we would not even need additional configuration section. I wanted to see if I can get away with a cron job that uses existing CLI and uses our resources to produce tokens.
