### ISSUE TITLE
Support for Kubernetes Websocket V5 protocol

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#15474]
Kubernetes will deprecate the usage of SPDY for IO-related events (`attach`, `exec`, `port-forward`) and will introduce a new websocket protocol (V5).

Teleport must support it as a server and as client.

Draft PR: https://github.com/kubernetes/kubernetes/pull/119157
RFD: https://github.com/kubernetes/enhancements/pull/4016

**Comment by tigrato** [comment]
This is a tracking issue, for now no action is required since the PR is not yet ready/merged

**Comment by ringerc** [comment]
If you're getting errors like

```
websocket._exceptions.WebSocketBadStatusException: Handshake status 500 Internal Server Error

During handling of the above exception, another exception occurred:

...

kubernetes.client.exceptions.ApiException: (0)
Reason: Handshake status 500 Internal Server Error
```

from the Python kubernetes client when (say) attempting to set up port-forwards, this will be why. Unfortunately the Python client doesn't detect when the kube API server endpoint doesn't support websockets and fail with a more graceful error.

**Comment by aviramha** [comment]
Is this still relevant?

**Comment by AntonAM** [comment]
Implemented by https://github.com/gravitational/teleport/pull/39755
