### ISSUE TITLE
Log all `tctl` audit events.

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#15486]
What would you like Teleport to do?

Audit all `tctl` commands that are run.  AFAIK nothing (or very little) is logged when a user runs any `tctl` commands.

What problem does this solve?

Increases audit trail for observability and security.

If a workaround exists, please include it.

None AFAIK.

**Comment by zmb3** [comment]
Can we get a bit more specific about we think is missing here? Im not sure that "nothing (or very little) is logged" is a true statement.

- `tctl users add` emits a `user.create` event
- `tctl users update` emits a `user.update` event
- `tctl users reset` emits a `user.password_change` event
- `tctl auth sign` emits `cert.create`
- `tctl create` emits lots of events depending on resource created (`oidc.created`, `github.created`, `trusted_cluster.create`, etc)
- `tctl bots add` emits `bot_token.create` as well as `user.create` and `role.create`
- `tctl requests` emits `access_request.create`, `access_request.review`, etc.

Some that I'm not sure about:
- `tctl tokens add`
- `tctl auth rotate`

**Comment by Valien** [comment]
So I am trying to troubleshoot why my `tctl create -f cap.yaml` isn't working. CLI says it is, but results on a `tctl get cap` show no updates.

Went to the audit log to see if anything was listed there and saw nothing. Now I have not tested all the `tctl` commands but it did get me thinking that it would be good to have some audits of anyone running `tctl` admin level commands. Maybe even log someone trying to 'hack' or run a command they do not have permissions to run?

**Comment by ArunNadda** [comment]
There should be audit logs generation for any `tokens` events. i.e. `add`, `rm`, `expire (auto)` or any usage of the token (for adding nodes/app/db etc). This is including `tctl tokens ...` command or any `static` token used to join the cluster.

**Comment by ArunNadda** [comment]
> 

@Valien , were you able to solve this issue. i.e. not Audit but `cap.yaml`? I guess there was documentation issue with `cap.yaml` reference. This doc issue is resolved now, please compare your `cap.yaml` with doc - https://goteleport.com/docs/reference/authentication/#dynamic-resource.

**Comment by Valien** [comment]
Hi @ArunNadda ! Yup, got my `cap.yaml` fixed. Ended up having some wrong formatting I think.
