### ISSUE TITLE
Remove non-revenue-generating feature flags from enterprise licenses

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#15489]
## What would you like Teleport to do?

Remove non-revenue-generating feature flags from the enterprise license. Examples of these include:

1. Resource Access Request
2. Moderated Sessions

## What problem does this solve?

The only advantage to having these flags is driving conversations with customers but it's bad practice to prioritize that over user experience and feature discoverability.

## If a workaround exists, please include it.

Not really relevant but today Sales can go find the license, modify it, and ask customer to update their license.

**Comment by zmb3** [comment]
@rudream the features that need to be removed were added in:

- https://github.com/gravitational/teleport/pull/13629
- https://github.com/gravitational/teleport/pull/11388

In addition to this, you can remove them from:

- https://github.com/gravitational/houston/pull/422
- https://github.com/gravitational/ops/blob/722d6d826de2a66236ff62af207e60958cb7ee10/license/generate-test-license.go#L63
- https://github.com/gravitational/ops/blob/722d6d826de2a66236ff62af207e60958cb7ee10/license/generate-test-license.go#L65
