### ISSUE TITLE
Lock not enforced on TCP Application Access

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#15526]
Expected behavior:

Locks are enforced for TCP Access like HTTP Access apps.

Current behavior:

TCP App Access is not prevented during user locks.

Bug details:
- Teleport version: 10.1.2
- Recreation steps

1. Setup  HTTP and TCP application
Add a TCP Application like the postgres example in https://goteleport.com/docs/application-access/guides/tcp/
Add a HTTP Application like grafana in https://goteleport.com/docs/application-access/getting-started/

2. Confirm Access to both

3. Lock the user 
`tctl lock --user=alice --ttl=5m`

The HTTP application will return `Forbidden` while the tcp application will not block access.

**_Note: This applies to already established TCP connections. New connections will not be created when the lock is in action. We need to add connection monitor that terminates active connection upon a lock being placed like we do for other protocols._**

**Comment by mdwn** [comment]
This is resolved by https://github.com/gravitational/teleport/pull/17436.
