### ISSUE TITLE
Visual notification of new Teleport versions in proxy web UI 

### ISSUE THREAD

**Issue by aberoham** [gravitational/teleport#1552]
It would be nice if Teleport included a visual mechanism in the proxy web UI to alert users / administrators when their version of Teleport is out of date.

Gitlab has a decent implementation of this functionality in their web interface, uses red/yellow/green icons. Non-code details at https://about.gitlab.com/2015/05/07/version-check/ and https://about.gitlab.com/handbook/sales-process/version_check/

Notably, Gitlab's implementation is opt-out but the configuration flag to trigger the version check is enabled by default.

**Comment by aberoham** [comment]
@alexwolfe There's a somewhat similar and interesting "diagnostics" approach that Cockroach DB takes, detailed here: https://www.cockroachlabs.com/docs/stable/diagnostics-reporting.html

**Comment by russjones** [comment]
@benarent Starting with Teleport 4.3 we started to show the version, do we want to also alert people when new versions are avaiable?

**Comment by zmb3** [comment]
This will eventually be handled with the automatic upgrades system that @fspmarshall is working on.

**Comment by russjones** [comment]
@zmb3 This has been rolled out, can we close?
