### ISSUE TITLE
`tsh recordings ls` fails to parse its own recommended time format

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#15537]
There are several issues with the new `tsh recordings ls` command:

1. It doesn't parse the time format that its own `--help` message recommends:

```
➜ ./build/tsh recordings ls -h
usage: tsh recordings ls [<flags>]

List recorded sessions.

Flags:
      --from-utc                 Start of time range in which recordings are listed. Format 2006-01-02T15:04:05Z07:00. Defaults to 24 hours ago.
      --to-utc                   End of time range in which recordings are listed. Format 2006-01-02T15:04:05Z07:00. Defaults to current time.
```

```
❯ ./build/tsh recordings ls --from-utc 2006-01-02T15:04:05Z07:00
ERROR: failed to parse session recording listing start time: expected format 2006-01-02T15:04:05Z07:00, got 2006-01-02T15:04:05Z07:00.
```

It looks like the help message should say `2006-01-02T15:04:05Z` instead.

2. The error message `invalid days` is not clear to the user. Provide a better error message when the date (or dates) are invalid. For example: "cannot request recordings, --from-utc is in the future" or "--to-utc must be after --from-utc".

3. When an invalid range is provided, `tsh` should terminate. The current build (90f34c3a5ef4a36af9d57c33a2bee7f5f0f97ad4) prompts me to re-login even though my credentials are valid and have not expired:

```
❯ ./build/tsh recordings ls --from-utc 2022-10-12T07:20:50Z
Enter password for Teleport user zac:
ERROR: invalid days
```

**Comment by EdwardDowling** [comment]
The issue seems to be that I had the help string / error message is the time.RFC3339 which turns out is not actually a valid RFC3339 string since you can't have both a Z and an offset in the time.
Will swap to the YYYY-MM-DD format since that is more human readable.
