### ISSUE TITLE
Update Machine ID Jenkins guide now that TLS routing is supported

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#15550]
## Details
Machine ID Jenkins guide includes an admonition in relation to an older Machine ID version, we should provide guidance on how to use it after this version.

We should check the rest of this guide is still up to date.

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
@strideynet I'm guessing that this is no longer an issue since I see no such admonition. If I'm wrong, please feel free to re-open this issue and clarify what section is outdated, and what guidance needs to be added.
