### ISSUE TITLE
Enforce IP-Based restrictions for Ephemeral Certificates for Kube, DB, Desktop

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#15565]
What would you like Teleport to do?

Teleport provides IP- Based restrictions to SSH.  Some clients want this expanded to include at least Kube, DB and Desktop certificates.

What problem does this solve?

Provides additional security to prevent reuse of certificates from multiple IP sources.

**Comment by zmb3** [comment]
Closing as duplicate of https://github.com/gravitational/teleport/issues/14702
