### ISSUE TITLE
Need guide and documentation around IP Pinning.

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#15573]
## Details
In Teleport v10 we released a preview feature called IP Pinning -  https://goteleport.com/docs/changelog/#1000 (the IP-Based Restrictions (Preview)) - but as of now, there are no guides or any information in our docs around how to get this working.

Our search engine also does not return any results.

### Category
- New Feature
- Improve Existing

**Comment by zmb3** [comment]
The `pin_source_ip` option is documented on the Role overview page: https://goteleport.com/docs/access-controls/reference/

**Comment by Valien** [comment]
Thanks @zmb3 ! That is helpful but shows how bad our search is with natural language or common terms. You see something in the changelog, but then almost impossible to find it unless you dive deep into templates/code. :( Not a good user experience.

**Comment by zmb3** [comment]
Yeah, a guide would probably help with that as there would be more natural language.

We didn't do a guide this time around because there's not much to configure or set up, you just turn on the role option.

As we add IP restrictions to other protocols this quarter I think we'll see more documentation which should improve searchability.

**Comment by ptgott** [comment]
Hi @zmb3 , just double-checking when the best time would be to write these docs. Thanks!

**Comment by ptgott** [comment]
@zmb3 Now that we have #17579, should we close this issue, or are there docs for other protocols we'll need to write eventually?

**Comment by zmb3** [comment]
I'll defer to @AntonAM on that one. A general "how IP pinning works and how we propagate the client IP" guide might be helpful.

**Comment by AntonAM** [comment]
Yes, I would say that general guide would be good after changes IP propagation/pinning are implemented. It should be transparent for the user and work in general way, so we probably don't even need feature-specific issues like #17579

**Comment by ptgott** [comment]
That makes sense to me! I'll close the issue for the Kubernetes guide

**Comment by ptgott** [comment]
@AntonAM Just double-checking if there is any more work to on this. I think we're backporting your PR now, right?

**Comment by AntonAM** [comment]
@ptgott Originally I didn't plan to backport it further then v12, but I see now, that we probably should just remove mention of kube and DB access from the page and backport it like this to v10 and v11. I'll take care of it, thanks for bringing it up!

**Comment by AntonAM** [comment]
Opened PR: https://github.com/gravitational/teleport/pull/23908 and https://github.com/gravitational/teleport/pull/23909

**Comment by ptgott** [comment]
Closing as completed
