### ISSUE TITLE
Database Access DynamoDB audit log

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#15572]
What would you like Teleport to do?
[AWS audit log](https://github.com/gravitational/teleport/issues/8611) has been added recently. In this implementation, AWS audit log is implemented in a similar fashion as the normal app audit log where there are session recordings that can be played back.

@smallinsky suggested that DynamoDB access (through AWS app access) can have an Audit log that is more aligned with other databases.

What problem does this solve?
Improves Audit log for DynamoDB

**Comment by GavinFrazar** [comment]
> @smallinsky suggested that DynamoDB access (through AWS app access) can have an Audit log that is more aligned with other databases.

By "more aligned", you mean just add session recordings for DynamoDB through aws app access?

**Comment by smallinsky** [comment]
@GavinFrazar 
Right now the DynamoDB access leverages the app access and emits DynamoDB audit events like normal AWS/CLI http request. For DynamoDB  audit logs we want to introduce a new audit events dedicated to DynamoDB access.

**Comment by webvictim** [comment]
Is the intention that this would be a reasonably similar experience to accessing DynamoDB tables via Teleport database access?

**Comment by greedy52** [comment]
> Is the intention that this would be a reasonably similar experience to accessing DynamoDB tables via Teleport database access (which isn't implemented)?

Unfortunately no. DynamoDB will still be accessed through AWS App access. This is only for an improvement on the audit log for DynamoDB. Currently, DynamoDB audit logs are saved in a recording as HTTP requests.

**Comment by GavinFrazar** [comment]
I discussed with @smallinsky what we should do here. We want to log the json payload in these http requests basically, and log them as database queries.

**Comment by smallinsky** [comment]
We want unify DynamoDB and move the configuration from app access to database access  and unify the flow. For that firstly we want extract dynamoDB app log and and explicitly log dynamoDB events as a database log entries. The second part is moving DynamoDB configuration from app access  to database configuration.

**Comment by GavinFrazar** [comment]
this is implemented
