### ISSUE TITLE
AWS app to cache AWS session credentials

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#15574]
What would you like Teleport to do?
Teleport Application Service currently make a new AssumeRole call to get AWS credentials for every incoming AWS API request.

It would be great the AWS credentials can be cached to avoid an STS call to AWS every time. Especially with the support of `tsh proxy aws`, users can run tools like `terraform` that possibly make hundreds of AWS calls in the same session.

What problem does this solve?
Avoid spamming AWS STS service.

**Comment by pschisa** [comment]
+1 from user looking at 100+ people using AWS API and running Terraform
