### ISSUE TITLE
Provide list of devices connected with revocation option

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#15575]
What would you like Teleport to do?

Provide the list of connected user devices and the ability to revoke the client devices.

What problem does this solve?

Adds more security to knowing what devices are connected and the ability to revoke the devices.

**Comment by zmb3** [comment]
What is a "device" in this context?

We don't support revocation, but you can achieve the same effect today with locks.

**Comment by stevenGravy** [comment]
A device would be a user's desktop. I looked for device trust issue which this be linked to but couldn't find an issue.

**Comment by zmb3** [comment]
You can still lock a user out by user or role today.

When device trust is implemented, we'll be sure to add *enrolled* devices as a lock target (cc @codingllama).

Emphasis here on the term enrolled as opposed to connected.

**Comment by codingllama** [comment]
Confirming, I do have this feature in my drafts. Zac put it well: it has to be an enrolled device, otherwise we can't ascertain its identity.

@stevenGravy, feel free to either close or keep the issue around, as you prefer.

**Comment by zmb3** [comment]
Given that device trust doesn't yet exist, this issue is more informational than actionable, so I'm going to close it.
