### ISSUE TITLE
[Teleport Discover] Desktop Access - Day 1 Experience

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#15589]
Design and implement the Teleport Discover Day 1 Experience for Desktop Access (AD-only).

User should be able to copy and paste a single curl-bash-like script that configures an AD-managed Windows Desktop for Teleport Desktop Access.

**Comment by rishibarbhaya-design** [comment]
Teleport Discover Database Access is divided into 2 parts.
Check designs here: https://www.figma.com/file/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?node-id=1425%3A76864

**1. AWS RDS**
-------------------

![Image](https://user-images.githubusercontent.com/88441969/198720147-1f31994a-e779-492b-85ec-84285cf9fbd1.png)
![Image](https://user-images.githubusercontent.com/88441969/198720146-81721362-7460-4e38-a675-e9c804209d50.png)

![Image](https://user-images.githubusercontent.com/88441969/198720238-641a502c-8efe-4de2-909c-64242ff892b9.png)


![Image](https://user-images.githubusercontent.com/88441969/198720317-e8e7e0f1-dc24-486e-9e63-d42b16bf42a4.png)
![Image](https://user-images.githubusercontent.com/88441969/198720313-4185aa1e-bdee-4628-8849-f14ee87d5deb.png)
![Image](https://user-images.githubusercontent.com/88441969/198720315-6bcfa0bf-93f3-4632-916c-120d8a59b39c.png)
![Image](https://user-images.githubusercontent.com/88441969/198720312-2653ca7a-2bc4-4213-81fa-df449d44dc5c.png)
![Image](https://user-images.githubusercontent.com/88441969/198720311-6587815b-55c8-4bf2-ba41-e110299b51c0.png)
![Image](https://user-images.githubusercontent.com/88441969/198720314-e7e01e84-a5c0-44cb-a74d-c681a9e20986.png)
![Image](https://user-images.githubusercontent.com/88441969/198720316-749457c3-3ab1-48d7-8bc9-167443587f68.png)

![Image](https://user-images.githubusercontent.com/88441969/198720360-00dee4ec-65cb-4522-8c9a-32ab9b90f2aa.png)


**2. Self-Hosted Database**
---------------------------------

![Image](https://user-images.githubusercontent.com/88441969/198720147-1f31994a-e779-492b-85ec-84285cf9fbd1.png)
![Image](https://user-images.githubusercontent.com/88441969/198720573-bd563962-6623-4755-b2c7-68bbe650aae6.png)

![Image](https://user-images.githubusercontent.com/88441969/198720842-d30f35b1-2fee-40d2-b857-ef59e312cf54.png)
![Image](https://user-images.githubusercontent.com/88441969/198720837-01410707-f31f-4e85-8bf1-a14ba42f836c.png)
![Image](https://user-images.githubusercontent.com/88441969/198720840-bc2565f6-b4e7-4ba1-937e-540a57df7ec4.png)
![Image](https://user-images.githubusercontent.com/88441969/198720839-28c21873-f624-43e5-be15-8637ecfcbad2.png)
![Image](https://user-images.githubusercontent.com/88441969/198720841-b97356c0-442c-4156-94c6-ffcd74bb405d.png)
![Image](https://user-images.githubusercontent.com/88441969/198720838-36c504dd-92df-4251-9e0c-25d7cf2859cd.png)
