### ISSUE TITLE
Can't add Yubikey bio using tsh mfa add

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#15596]
Expected behavior:
I was unable to add a new YubiBio to my account using TSH, but it worked in the browser. This was version 10.1.4

Current behavior:
```
Choose device type [TOTP, WEBAUTHN]: WEBAUTHN
Enter device name: yubibiot
Allow passwordless logins [YES, NO]: YES
Tap any *registered* security key
Tap your *new* security key
ERROR: device ioreg://4294985199: info
failed to open: rx error
```

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by tobiaszheller** [comment]
@benarent can you attach debug output of command? We were not able to reproduce it locally.
