### ISSUE TITLE
No viable challenge type found on linux server version. 

### ISSUE THREAD

**Issue by mtgnoah** [gravitational/teleport#15591]
Expected behavior:

Connects to website which is dev.example.com

Current behavior:

022-08-16T22:46:36Z WARN [ALPN:PROX] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *errors.errorString acme/autocert: unable to satisfy &#34;https://acme-v02.api.letsencrypt.org/acme/authz-v3/142850786797&#34; for domain &#34;dev.example.com&#34;: no viable challenge type found
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:376 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:314 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: acme/autocert: unable to satisfy &#34;https://acme-v02.api.letsencrypt.org/acme/authz-v3/142850786797&#34; for domain &#34;dev.example.com&#34;: no viable challenge type found] alpnproxy/proxy.go:322
2022-08-16T22:46:36Z DEBU [AUTH]      ClientCertPool -> cert(dev.example.com issued by dev.example.com:108168437823915554513874734050075693581) auth/middleware.go:672
2022-08-16T22:46:36Z DEBU [AUTH]      ClientCertPool -> cert(dev.example.com issued by dev.example.com:58183078097642943525305082968994174302) auth/middleware.go:672
2022-08-16T22:46:36Z WARN [ALPN:PROX] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *errors.errorString acme/autocert: missing certificate
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:376 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
        /go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:314 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: acme/autocert: missing certificate] alpnproxy/proxy.go:322

Bug details:
- Teleport version - Teleport v10.1.4 git:v10.1.4-0-gf095c6f go1.18.3
- This computer is running ubuntu server. 
- Recreation steps 
- I just followed this tutorial. Originally I did a self signed cert but then I deleted everything to move to letsencrypt so I could expose it to the public more easily. 
- https://goteleport.com/docs/getting-started/linux-server/
- Debug logs

**Comment by webvictim** [comment]
When I load that challenge URI, it points me to the actual domain that you were trying to use. When I resolve that DNS record, it points to an internal IP:

```
~ » host dev.ano***.com
dev.ano***.com has address 192.168.1.20
```

You'll need to point this DNS record to the external IP address of your server in order for Let's Encrypt to be able to fulfil the challenge and issue you a certificate. If you don't know what the external IP, you should be able to get it by running `curl icanhazip.com` at the command line.
