### ISSUE TITLE
Cache Connect cluster clients between calls to tsh daemon

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#15603]
There are two types of clients used within tshd: proxy client and cluster (auth) client. For each call to tshd, those clients are constructed from scratch, which means performing some kind of a handshake with the proxy service and then the auth service.

This introduces a significant overhead for each call. Up until now it wasn't such a big problem because Connect wasn't making calls to the cluster that often. This is going to change with the introduction of advanced search (https://github.com/gravitational/webapps/pull/1105).

The webserver already implements some kind of caching for the Web UI in [`lib/web/sessions.go`](https://github.com/gravitational/teleport/blob/2baa7e72d9c22fc5263d46a03a4ba1e17de74ffd/lib/web/sessions.go). Part of this task is to check if and how we can reuse some of that cache implementation in Connect.

**Comment by ravicious** [comment]
I suppose the main difference is going to be that lib/web/sessions.go needs to cache many client for each user on a single cluster. In Connect we're going to cache a single client for one user per cluster.

The server also needs to periodically clear expired sessions. Connect doesn't have to do that. Our expiry can be tied purely to actions which affect the state of `TELEPORT_HOME` – logging in, logging out and perhaps assuming roles (though even here invalidating the cache might not be necessary).

**Comment by ravicious** [comment]
Notes from my limited research into this ticket:

The way to think about it is that `TeleportClient` is a specific struct initially meant to be used by tsh only (I haven't checked if tctl or teleport use it too but probably not). `ProxyClient` is also tsh-oriented and deals with saving certs to disk, among other things. Auth client is a regular gRPC client that can be used in different environments, for example the Web UI uses it on the backend.

We should be able to replace most of the calls that we do through `TeleportClient` (`clusters.Cluster.clusterClient`) with auth client calls. The only exceptions will be things that need to touch certs on disk: authn code or getting DB certs.

Regarding how the Web UI caches those clients, it looks like we could have a single remoteClientCache instance with a single remoteClientGroup? Since in case of Connect, there’s always only a single session to any given root cluster.

Relevant PRs:

* #19010

**Comment by gzdunek** [comment]
For reference, I measured how long it takes to call `ListUnifiedResources` from my location (Warsaw) to teleport-15-ent.

Total: 2.6 s
* `clusterClient.ConnectToProxy` - 1.61 s
* `proxyClient.ConnectToCluster` - 17.9 us (I thought this call also takes time)
* `authClient.ListUnifiedResources` - 986 ms

By caching the client we should make it ~2,5x faster, nice :)

**Comment by ravicious** [comment]
When do we backport this to v15?

**Comment by gzdunek** [comment]
I wanted to give it a few days on master, I'm going to open a PR today.
