### ISSUE TITLE
Refresh/redesign SSO documentation

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#15601]
## Details
The Teleport SSO guides - GitHub and Enterprise versions - have grown organically over the years. This led to a drift in page content and a lack of uniformity. For example:
- Different page titles: "Teleport SSO Authentication with GitLab" vs. "SSH Authentication with Google Workspace (G Suite)".
- Some guides offer numbered steps, some don't.
- The links have outdated titles and the listings are incomplete (e.g. https://goteleport.com/docs/enterprise/sso/?scope=enterprise links to just 4 guides in the body text).

There are more issues than those; more generally though, Teleport capabilities have grown and so did the complexity of the SSO guides. The guides should be streamlined and common parts between guides shared or unified. Furthermore, the new commands `tctl sso configure github|saml|oidc` and `tctl sso test` should be used in the guides for better experience:
- https://goteleport.com/docs/setup/reference/cli/#tctl-sso-configure-github
- https://goteleport.com/docs/setup/reference/cli/#tctl-sso-configure-oidc
- https://goteleport.com/docs/setup/reference/cli/#tctl-sso-configure-saml
- https://goteleport.com/docs/setup/reference/cli/#tctl-sso-test

Pages affected: 
- Enterprise SSO overview: https://goteleport.com/docs/enterprise/sso/?scope=enterprise
- Github SSO guide: https://goteleport.com/docs/setup/admin/github-sso/?scope=enterprise
- Individual SAML/OIDC providers guides, e.g: https://goteleport.com/docs/enterprise/sso/google-workspace/?scope=enterprise https://goteleport.com/docs/enterprise/sso/gitlab/?scope=enterprise

### Category
- Improve Existing
- Remove Outdated

## Progress

- [x] Azure Active Directory (AD)
- [x] Active Directory (ADFS)
- [x] Google Workspace
- [x] GitHub
- [x] GitLab
- [x] OneLogin
- [x] OIDC
- [x] Okta

**Comment by Tener** [comment]
@r0mant @smallinsky FYI.

**Comment by alexfornuto** [comment]
Tagging myself to break this out into issues per IDP, and updating the reference.

**Comment by ptgott** [comment]
As part of this work, we can consider adding an SSO guide to setting up Keycloak: https://github.com/gravitational/teleport/issues/14490

**Comment by ptgott** [comment]
We can consider creating a JumpCloud guide as part of this work, since it's getting increased demand (https://github.com/gravitational/teleport/issues/13765)

**Comment by ptgott** [comment]
Worth noting that the work we did on the Okta guide earlier this year doesn't include the `tctl sso` commands.

**Comment by alexfornuto** [comment]
Complete!
