### ISSUE TITLE
Update PagerDuty URL

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#15616]
## Details
Update URL for PagerDuty on docs/pages/access-controls/access-request-plugins/index.mdx to https://goteleport.com/docs/access-controls/access-request-plugins/ssh-approval-pagerduty/ as the current URL reaches a 404

### Category

- Improve Existing

**Comment by ptgott** [comment]
This is fixed in [this backport PR](https://github.com/gravitational/teleport/pull/15414/files#diff-ee37334db20c1b2e351556d3be9a7bf93f50e79b5e79d4e748f0875bea197af6), which is still awaiting review.
