### ISSUE TITLE
regex.replace does not work with email.local function

### ISSUE THREAD

**Issue by akgoteleport** [gravitational/teleport#15627]
Expected behavior:
regexp.replace should work with email.local function

Current behavior:
{{regexp.replace(external.email, "@(.*)|[\\W]+","")}- email [first.last@domain.com] , login firstlast
regexp.replace(email.local(external.email), "\\.","")- email [first.last@domain.com], login [firstlast@domain.com]

Bug details:
- Teleport version: 10.0.2
- Recreation steps: Please see above details

**Comment by zmb3** [comment]
Hi @akgoteleport, can you help us out by providing a clear description of what you expected to happen and what happened instead?

It looks like you were trying to use:

`foo: {{regex.replace(email.local(external.email), "\.", "")`

What do you mean by "should work?" Did you get an error? Did you get an unexpected output? If so, what was the input and what were you expecting to see instead?

**Comment by akgoteleport** [comment]
Hello @zmb3 The customer was trying to create a login in role such that  first name.lastname@company.com becomes firstnamelastname 
However, when email.local function is used with regex.replace(email.local(XXX), ...) email.local() will not work and regex.replace will work on the whole email instead and give firstname.lastname@company.com

He solved this using {{regexp.replace(external.email, "@(.*)|[\\W]+","")}} which gives login as firstnamelastname. The expected behavior was that regexp.replace would act on the output of email.local(external.email, however, the e-mail.local portion is effectively ignored.

**Comment by zmb3** [comment]
Ah, yep - looks like this was never implemented:

https://github.com/gravitational/teleport/blob/9bfa8dea925af7ab7cfdb328248d6796bbb797ef/lib/utils/parse/parse.go#L17-L18
