### ISSUE TITLE
Document public_addr and --token flag for nodes add

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1563]
See #1174 for more details.

**Comment by klizhentas** [comment]
Also, adding to this ticket:

```
tctl nodes add --roles=node --ttl=10h --token=[custom-token]
```

 now works and should be documented

**Comment by klizhentas** [comment]
Also document that token could be both value and path at the config file:

```yaml
token: /path/to/token
```
I don't think its documented

**Comment by klizhentas** [comment]
Document 

tctl auth export --type=tls

and /var/lib/teleport/ca.cert file meaning

**Comment by klizhentas** [comment]
Also, `public_addr` is not documented

**Comment by kontsevoy** [comment]
Part of this moved to #1716
