### ISSUE TITLE
Refresh the Fluentd plugin guide

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#15661]
## Details
- QA all instructions in the guide.
- Ensure configuration instructions are up to date and comprehensive.
- Ensure the guide is as easy as possible to follow.

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
From DevRel:

> A weird error that could be documented is one concerning `start time`. This happens when the state that the forwarder stores is in conflict. To fix this, delete the storage directory that is created every time the command is run. This happened to me every time I would start and stop the event handler plugin.
>
> Another thing that could be explicitly documented is the “invalid identity” error. This can be a little ambiguous when really it’s just because the identity file we created earlier has expired. In order to fix this run the command: tctl auth sign — user=teleport-event-handler — out=identity again to regenerate a valid identity file.

**Comment by ptgott** [comment]
@alexfornuto Did your recent changes take care of this one?

**Comment by alexfornuto** [comment]
Yes, this can be considered resolved by #21865, thanks for flagging!
