### ISSUE TITLE
Search for Available Roles in CLI for Access Requests

### ISSUE THREAD

**Issue by campanamarco** [gravitational/teleport#15679]
What would you like Teleport to do?
We currently support users searching resources to request in the CLI via: https://goteleport.com/docs/setup/reference/cli/#tsh-request-new  Teleport should enable user to also search available roles to request in the CLI with the same syntax: `tsh request roles ls`

What problem does this solve?
This enables customers and prospects a more intuitive way of requesting elevated access in the CLI, and provides less operational direction to have to ask or go to WebUI to see available roles. 

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Looks like we have many duplicates here.

- #12099
- #12053
- #7693

Let's try to do better at searching for existing issues before opening new ones. The more duplicates we have to sift through the easier it is for important items to get buried and lost in the noise.

**Comment by campanamarco** [comment]
@zmb3 - agreed. Did this on behalf of prospect to show actions being done against call. Would like me to keep or delete?

**Comment by zmb3** [comment]
Feel free to comment/+1 on the original (#7693) to register the prospect's interest.
