### ISSUE TITLE
Add drone pipeline for building Connect with signed tsh.app

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#15681]
To build a release version of Connect, we need:

* a signed version of tsh.app
* Node.js
* the developer ID cert from Keychain

darwinTagPipeline has Node.js but at that point tsh.app isn’t signed yet. darwinPkgPipeline signs tsh.app but doesn’t have Node.js.

## Where we are now

**pipeline**|**artifacts**|**toolchains**|**notarization & home dirs**
-----|-----|-----|-----
darwinTagPipeline|publishes Teleport binaries & Connect|needs Node, Rust, and Go toolchains|notarizes Connect, needs HOME to be in /Users
darwinPkgPipeline|downloads artifacts made by the tag pipeline, publishes .pkg & tsh-only .pkg|doesn’t need any toolchains|notarizes tsh.app, needs HOME to be in /Users
darwinPushPipeline|builds Teleport binaries & Connect without publishing|needs Node, Rust, and Go toolchains|doesn’t notarize and doesn’t need HOME to be changed; still, it installs toolchains in the same way as darwinTagPipeline

## Where we want to be

**pipeline**|**artifacts**|**toolchains**|**notarization & home dirs**
-----|-----|-----|-----
darwinTagPipeline|🛑 publishes Teleport binaries|🛑 needs Rust and Go toolchains|🛑 doesn’t notarize, doesn’t need special accommodations for HOME
darwinPkgPipeline|downloads artifacts made by the tag pipeline, publishes .pkg & tsh-only .pkg|doesn’t need any toolchains|notarizes tsh.app, needs HOME to be in /Users
darwinPushPipeline|builds Teleport binaries & Connect without publishing|needs Node, Rust, and Go toolchains|doesn’t notarize and doesn’t need HOME to be changed
darwinConnectDmgPipeline|downloads tsh-only .pkg, publishes Connect .dmg|needs Node toolchain|notarizes Connect, needs HOME to be in /Users

What follows from those tables is that only darwinTagPipeline would require some changes. We’d mostly remove responsibilities from it and move them to darwinConnectDmgPipeline.

At the moment though, both darwinTagPipeline and darwinPushPipeline have special HOME handling to support notarizing & toolchains in temporary workspaces, as described in 86f3a3d618. However, after the changes described here none of those two pipelines would notarize anything, so technically they could go back to the original HOME handling. But, darwinPushPipeline and darwinConnectDmgPipeline will need to share the steps needed to build Connect.

darwinConnectDmgPipeline can acquire tsh.app by downloading the tsh-only .pkg and calling `pkgutil --expand-full`.

**Comment by zmb3** [comment]
`darwinConnectDmgPipeline` would only run on tags, right?

Would we still run a Connect build on Mac for every commit? (do we even do that today?)

**Comment by ravicious** [comment]
> `darwinConnectDmgPipeline` would only run on tags, right?

Yeah.

> Would we still run a Connect build on Mac for every commit? (do we even do that today?)

Yes, as described in the `darwinPushPipeline` row. We do that today though we only build the JS files and then package them into `Teleport Connect.app`, without signing the app.
