### ISSUE TITLE
[v.10.0] /docs/pages/setup/guides/docker.mdx

### ISSUE THREAD

**Issue by alezkv** [gravitational/teleport#15680]
## Details
First step mention "The latest version of Teleport Open Source 10.0" with auto-update feature, but in both cases full strict version of docker image is used

Image name | Teleport version | Image automatically updated? | Image base
-- | -- | -- | --
quay.io/gravitational/teleport:10.1.4 | The latest version of Teleport Open Source 10.0 | Yes | Ubuntu 20.04
quay.io/gravitational/teleport:10.1.4 | The version specified in the image's tag (i.e. 10.1.4) | No | Ubuntu 20.04

First image must be something like `quay.io/gravitational/teleport:10`

### Category
- Improve Existing

**Comment by zmb3** [comment]
This has been fixed.

**Comment by zmb3** [comment]
This should be fixed (we've migrated on to ECR instead of quay)
