### ISSUE TITLE
Yubikey-based alternative for MFA in remote machines

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#15688]
__What would you like Teleport to do?__

A common issue customers have is trying to use WebAuthn/USB-based MFA in remote machines. An example is trying to use `tsh ssh` while connected to a remote host.

USB-based MFA doesn't work when remote machines are in play, as physical access to the machine is required. A common fallback is enabling and using TOTP.

Yubikeys have a series of features that could work in this scenario, providing a bit more convenience to the end user. Namely:

* Yubico OTP (namesake protocol)
* Yubico OTP / HOTP

Both of these use the "OTP" function of the key and are activated by a short/long touch.

Other options beyond the ones above may also be viable.

__What problem does this solve?__

This gives users a way to do MFA in remote machines using a Yubikey they may already have, instead of enrolling an authenticator app.

__If a workaround exists, please include it.__

[Yubico Authenticator](https://www.yubico.com/products/yubico-authenticator/) is a valid workaround that uses an existing Yubikey to store TOTP secrets. It's also possible to guard the secret with a touch.

There are no Yubikey TOTP secret APIs (at least that I'm aware atm), but it's possible to drive the devices using `ykman` (eg, `ykman -d <serial_number> oath accounts code <account>`).

**Comment by codingllama** [comment]
FYI @corkrean @rosstimothy @tobiaszheller

**Comment by codingllama** [comment]
Also relevant: https://pkg.go.dev/github.com/pquerna/otp@v1.3.0/hotp.

**Comment by benarent** [comment]
We ran into the same thing with our remote Teleport Instrqut tracks.

**Comment by corkrean** [comment]
The customer who requested this, c-dx, has now stated that they need to use Webauthn for all MFA, so this will no longer help them.

**Comment by codingllama** [comment]
Ack. I'll keep the issue around, as we've had similar asks before, but lacking interesting it's unlikely to see any work in the short term.

**Comment by Joerger** [comment]
We may also be able to use Hardware Key support as an alternative to webauthn for this use case. Once [ssh-agent forwarding](https://github.com/gravitational/teleport/issues/17402) is supported, users should be able to use their YubiKey-forwarded keys to start new sessions requiring PIV-touch.

**Comment by Joerger** [comment]
Headless SSO is now available for `tsh ls`, `tsh ssh`, `tsh scp` - https://github.com/gravitational/teleport/issues/21519

Bringing Headless SSO to additional features will be tracked in https://github.com/gravitational/teleport/issues/21520
