### ISSUE TITLE
docs: update grafana guide

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#15691]
## Details

This guide was written for an older version of grafana. There are a few tweaks that need to be made.

In order for current versions of grafana to run behind a web proxy, there are two changes that need to be made.

These are documented in the grafana doc [Run Grafana behind a Reverse Proxy](https://grafana.com/tutorials/run-grafana-behind-a-proxy/)

1) set the variables in the grafana.ini [server] section.
2) set teleport to rewrite the Host header for all requests.

The rewrite alone is not enough, since websockets won't know to trust the origin unless the correct domain is present in the grafana.ini settings.

This does complicate the tutorial. There will be additional steps to cover the procedure for customizing grafana.ini and the `teleport app start` command to include the rewrite.

Without these changes, the tutorial does not get the end user a working grafana setup.

### Category
- Improve Existing

[see also](https://github.com/grafana/grafana/issues/36929#issuecomment-883237258)

**Comment by zmb3** [comment]
@programmerq @ptgott I know there have been recent edits to the Grafana guide - is this still an issue?

**Comment by lsgunn-teleport** [comment]
@programmerq @ptgott The change to the` grafana.ini ` file is included in the tutorial. I didn't run into the second issue, but I was testing in a self-contained sandbox, not the real world. I just received information about this header/cross-origin thing as a general application access issue, so I will be adding something shortly.
