### ISSUE TITLE
Agent forwarding handling by tsh

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1571]
**Problem**

Starting with Teleport 2.4.0 `-A` was added to `tsh` to allow forwarding the running agent to the target node. For `tsh` this is a agent that is created in-memory with keys from `~/.tsh` this means it non-Teleport certificates and keys will not be forwarded using `tsh -A`.

Note: To work around this issue for now, `ssh` can be used to connect to a node within the Teleport cluster and whatever agent that can be reached at `$SSH_AUTH_SOCK` will be used.

**Comment by soedar** [comment]
I'd love to see this feature implemented, as it appears that `tsh ssh` is intended to be used as a drop in replacement to be a somewhat drop in replacement for `ssh`.

Related: https://community.gravitational.com/t/tsh-ssh-agent-forwarding-does-not-forward-existing-host-identities/571

**Comment by sfc-gh-acardaniuc** [comment]
Would be real nice to have this work instead of doing:
ssh -A -J teleport-proxy:3023 -p 3022 node

**Comment by awly** [comment]
@tcsc can this be closed now?

**Comment by russjones** [comment]
@awly @tcsc Yes, looks like it was merged into `master` as well as `branch/v6`.

https://github.com/gravitational/teleport/pull/6525
https://github.com/gravitational/teleport/pull/6773
