### ISSUE TITLE
Feature Request: version node_label

### ISSUE THREAD

**Issue by nikatjef** [gravitational/teleport#1573]
Greetings,

   I would like to request a node_label for teleport version.

  Yes, it would be very simple to create this label with something like "teleport version | /usr/bin/cut -f2 -d' '", but the version is already hard-coded into the teleport daemon, as such it would make more sense to expose this in some way to be used in node_labels.

  Please note I am not asking for this to be automatically added to the node_labels list, no.  Instead it should require a command line argument or a configuration entry to add it to the list.  Something like '--labels-version' or 'labels_version: true'

**Comment by maznu** [comment]
…or a --short option to pass to teleport version which prints out v2.4.0, rather than the full string?

Downside with running a command is that you'll be told the version of teleport that is installed, not necessarily the version of teleport that is running as a daemon.

**Comment by kontsevoy** [comment]
@maznu do you mind me asking why do you want to strip git revision from the version output?

**Comment by maznu** [comment]
@kontsevoy I'll admit that I'm not someone who is running git-based builds in production — so it's easier to reference for running a mass command like `tsh root@teleport=v2.3.5 install-latest-teleport`

**Comment by kontsevoy** [comment]
@nikatjef exposing the version of server-side software is discouraged for security reasons, see #970 which is basically the exact opposite of what you're asking. but `version --short` flag makes sense, how about I create another ticket for this and reference this one.

**Comment by kontsevoy** [comment]
@maznu @nikatjef see  #1656 and feel free to comment there

**Comment by nikatjef** [comment]
#970 covers the version showing up when someone simply connects to the port.  Showing a version number to someone who is not logged in can be a bad thing.

My request actually requires the user to be logged in to see the version either by the 'tsh ls' command or via the web interface.  Additionally, as I stated above, it would not be enabled automatically.
