### ISSUE TITLE
Visual Pink Glitch on Login to Windows

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#15764]
Expected behavior:
Seamless, non-glitchy desktop login.

Current behavior:
Some customers have observed pink blocks on login screen that disappear once authentication is complete and users is logged into the desktop instance.

Bug details:
- Teleport version 9.3+

Example:

![desktop_glitch](https://user-images.githubusercontent.com/12404099/186188642-56ef89da-eee4-4bd8-b1c5-733055453886.png)

**Comment by zmb3** [comment]
Also reported in https://github.com/gravitational/teleport/issues/10751

I've seen this happen too, but can't consistently reproduce and I'm not sure what we can do about it. My best guess is the PNG encoder spit out some bad PNGs.

**Comment by russjones** [comment]
@deusxanima Can you check if the Teleport Desktop Access agent is hitting CPU or memory limits when this occurs?

**Comment by deusxanima** [comment]
@russjones , when this originally occurred with customer c-dh we asked them to up CPU and memory limits to rule out mem/cpu issues. After significantly increasing both the issue was still observed after confirming that the cpu/mem limits were not being hit.

**Comment by thg-jonnield** [comment]
I ran in to a similar issue yesterday, except with green blocks.  I can consistently replicate this in a test cluster so if you'd like me to attempt any debugging let me know.

Using version 10.3.8 and no obvious resource constraints on the desktop access agent
