### ISSUE TITLE
S3 bucket issue when using tsh aws s3

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#15765]
Expected behavior:

The customer would like the ability for an S3 bucket name to have the `=` and successfully upload using `tsh aws s3` command. 

Current behavior:

The customer has multiple s3 buckets with special characters specifically `=` in them.  When executing `tsh aws s3 cp test.txt ` the commands fails with following error:  An error occurred (403) when calling the PutObject operation: Forbidden. Once they remove the `=` from the name they are successfully able to copy to their bucket. We have tested using the `aws s3 cp test.txt` with name having `=` and this method works as expected. 

```
tsh aws s3 cp test.txt s3://my-bucket/process/priority=1/
upload failed: ./test.txt to s3://my-bucket/process/priority=1/test.txt An error occurred (403) when calling the PutObject operation: Forbidden
```
```
tsh aws s3 cp test.txt s3://my-bucket/process/priority1/
upload: ./test.txt to s3://my-bucket/process/priority1/test.txt
```

```
aws s3 cp test.txt s3://my-bucket/process/priority=1/
upload: ./test.txt to s3://my-bucket/process/priority=1/test.txt
```
Bug details:
- Teleport version
- v9.3.3
- Recreation steps:
- Create S3 bucket folder name that contain `=`
- Debug logs
- I have debug logs, however it has sensitive information.

**Comment by greedy52** [comment]
Both tsh local proxy and app service receive encoded url (e.g. `%3D` instead of `=`). However, v4.Signer expects url not escaped for signing s3.

https://github.com/aws/aws-sdk-go-v2/blob/4714d7c7a1a8d857d3aa140e55fff2925fbf36eb/aws/signer/v4/v4.go#L97

**Comment by greedy52** [comment]
The fix is in v8,v9, and v10 so they should catch the next release. Just want to note that both server and tsh client requires update.
