### ISSUE TITLE
client_idle_timeout warning

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#15777]
**What would you like Teleport to do?**
Warn users five minutes before a `client_idle_timeout:` disconnect occurs. To keep it simple, this could be done by emitting a warn level log on the auth service. The users could then set up alerts for this log. 

**What problem does this solve?**
A user is executing a long-running script and would like to be warned before their session is disconnected. 

**If a workaround exists, please include it.**
n/a

**Comment by zmb3** [comment]
If a user has access to read the logs on the auth service, they probably also have access to just disable the client idle timeout, no?

IMO, the better place for this information would be the audit log.

Though if you have to run a long-running script that's going to result in large idle times, it's probably a better UX all around if you do that without a role that enforces an idle timeout. Perhaps using an access request to request a much longer timeout when this script needs to run is the better approach.
