### ISSUE TITLE
`tsh play` should take a file argument as a valid parameter

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1580]
## Problem

If a user periodically backs up recorded sessions to a long-term storage (like Glacier) and decides to replay a sessions from 2 years ago, there is no easy way to do this in Teleport right now. 

## Solution

Currently a recorded session is a set of files:

* session stream file(s) - they have the same name prefix, possibly [compressed](https://github.com/gravitational/teleport/issues/1579)
* session events file
* (optional) cryptographic signature file #1579

So if a session stream files are named:

```bash
2394827492384723-x.gz 
2394827492384723-y.gz 
2394827492384723-z.gz 
2394827492384723.json  # events
2394827492384723.pem  # SSH signature 
```

Then all of the following should work:

```
$ tsh play ./2394827492384723-y.gz
$ tsh play 2394827492384723
```

And if the `.pem` file is missing or invalid, a warning should be shown:

```
WARNING: cluster signature is missing for session 2394827492384723
WARNING: cluster signature is INVALID for session 2394827492384723
```

**Comment by klizhentas** [comment]
it should actually take our tarball format as is and play it instead, this way folks can download and play all tarballs sent to S3 for example

**Comment by klizhentas** [comment]
@kontsevoy I suggest we move this one out of 2.6.0 to reduce the scope a bit, does not seem like a pressing issue.

**Comment by webvictim** [comment]
Another request for this in #3225

**Comment by travelton** [comment]
Another request in ZD#1699. Building some sort of index from stored objects would be helpful to locate the sessions of interest. The events object contains the session metadata.
