### ISSUE TITLE
Google workspace guide should show an example of the correct JSON file content to use for the gworkspace-creds.json

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#15812]
## Details
The process of configuring google workspace generates two JSON files, One JSON file is generated when the OAuth client id is configured and the other JSON file is generated when service account is created.  The documentation should show an example of the correct JSON key file content to use here `google_service_account_uri: file:///var/lib/teleport/gworkspace-creds.json`
https://goteleport.com/docs/enterprise/sso/google-workspace/?scope=enterprise

Example below: 

```
{
  "type": "service_account",
  "project_id": "",
  "private_key_id": "",
  "private_key": "-----BEGIN PRIVATE KEY----------END PRIVATE KEY-----\n",
  "client_email": "@.iam.gserviceaccount.com",
  "client_id": "",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/%40.iam.gserviceaccount.com"
}
```

### Category
- Improve Existing

**Comment by espadolini** [comment]
It's also important to stress that the JSON file one gets from the "Download JSON" button that appears as part of the step where one creates the OAuth Client ID is not the correct file:

![image](https://user-images.githubusercontent.com/886075/186670611-00a149c1-8ab8-4a07-ad28-1d0df7b926f2.png)
