### ISSUE TITLE
`teleport install systemd` fails on non-Linux systems

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#15818]
Expected behavior:

`teleport install systemd` should not be available/do not return errors when run on Windows or MacOS.

Current behavior:

```bash
% teleport install systemd       
ERROR: Can't find Teleport binary. Please specify the path.
readlink /proc/self/exe: no such file or directory
```

Bug details:
- Teleport version- master

**Comment by zmb3** [comment]
`teleport install systemd --path=/usr/local/bin/teleport` should work. It's the auto-detection of the teleport binary that doesn't work.

We could default to something instead, but the thought here was that if you're running this on Mac or Windows you probably want to be explicit anyway.

**Comment by zmb3** [comment]
@xinding33 do you want to see any changes here?
