### ISSUE TITLE
`web_idle_timeout` not ending session

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#15811]
The `web_idle_timeout` field is not ending sessions in the Web UI.

It might be due to some background API calls always being made on some screens of the Web UI.

From customer:

> Doesn't seem to do anything, I can leave the page open in the background for a couple hours and still click around without any re-auth.

> It did eventually log me out, though it was after I moved the focus to another tab and I went back to check after this message.  Might have stayed logged in since it was the active tab in the window for the morning part of my test?

> ok, it seems to be working now as long as it isn't the active tab

**Comment by zmb3** [comment]
Running on 24f6957639d3968a42202b65e2b3413dfe7c92e4 with `web_idle_timeout: 1m` I see:

- leaving the web UI on the default "Servers" page logs me out after 1m
- leaving the web UI on the "Active Sessions" page (when there are no active sessions) logs me out after 1m
- leaving the web UI on the "Active Sessions" page and also having a web session open in another tab logs me out (and terminates my active session) after 1m
- leaving the web UI on the audit log page logs me out after 1m
- leaving the web UI on the "Servers" page and switching to a non-Teleport browser tab logs me out after 1m

So far, I'm yet to find a scenario where things aren't working as expected.

**Comment by zmb3** [comment]
Turns out this is working as intended.
