### ISSUE TITLE
Add integrate with OpsGenie 

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#15822]
What would you like Teleport to do?
Add just in time access request plugin with OpsGenie. 
https://goteleport.com/docs/access-controls/access-request-plugins/

What problem does this solve?
This fits their use-case as they want to be able to elevate access for certain engineers who are currently on-call and then remove the access after the on-call rotation is completed. 
OpsGenie is the best option for them as that is what their currently managing with their on-call rotation schedules. 

If a workaround exists, please include it.
They can use any of the other plugins, currently available in our docs.

**Comment by programmerq** [comment]
Closing in favor of https://github.com/gravitational/teleport-plugins/issues/437
