### ISSUE TITLE
Double Recording with Teleport Nodes

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1582]
**Problem**

When using the recording proxy and connecting to a Teleport node, sessions get recorded twice: once at the proxy and again at the Teleport node.

**Proposed Solution**

When the cluster is recording sessions at the proxy, Teleport nodes should start discarding audit events so we don't have double recordings.

**Comment by alex-kovoy** [comment]
Tried the latest using our docker setup (one.yaml)

2 things. 
1. I see 2 nodes.
2. When I start a new session I see 2 active sessions in the session tab.

![image](https://user-images.githubusercontent.com/7816406/34908967-1a1a4c4a-f867-11e7-92c2-3c6b8f88369d.png)
