### ISSUE TITLE
Fix flaky builds of Teleport Connect

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#15835]
After merging in #15763 and gravitational/webapps#1116 we saw an uptick of random failures of `push-build-darwin-amd64` and `build-darwin-amd64-connect` (the new pipeline introduced by #15763).

Both pipelines fail when executing `yarn package-term -c.extraMetadata.version=$VERSION` with the error saying `hdiutil: couldn't eject "disk19" - Resource busy`:

<details>
<summary>Error log</summary>

```
  • building        target=DMG arch=x64 file=build/release/Teleport Connect-11.0.0-dev.dmg
  ⨯ Exit code: 16. Command failed: hdiutil detach -force /dev/disk19
hdiutil: couldn't eject "disk19" - Resource busy

hdiutil: couldn't eject "disk19" - Resource busy
  failedTask=build stackTrace=Error: Exit code: 16. Command failed: hdiutil detach -force /dev/disk19
hdiutil: couldn't eject "disk19" - Resource busy
hdiutil: couldn't eject "disk19" - Resource busy
    at /private/tmp/push-build-darwin-amd64/go/src/github.com/gravitational/webapps/node_modules/builder-util/src/util.ts:133:18
    at ChildProcess.exithandler (node:child_process:404:5)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /private/tmp/build-14948-1661354261/toolchains/node-v16.13.2-darwin-x64/bin/node
Arguments: /Users/build/.node/corepack/yarn/1.22.15/lib/cli.js package -c.extraMetadata.version=11.0.0-dev
Directory: /private/tmp/push-build-darwin-amd64/go/src/github.com/gravitational/webapps/packages/teleterm
```

</details>

# Early investigation

While errors in the new pipeline are understandable as it does something we haven't done before, the errors in the push pipeline are surprising to me. #15763 doesn't introduce much changes to that pipeline, [it merely reorders a few commands](https://github.com/gravitational/teleport/commit/b4c94ebf9b7ce5b3db0ed07a75a5c73e05689acc#diff-b54b39f1afced2465e1f3641db9d5bbf4f3a7fcf890996dfedd3c197bcb7f8c7L559-R588) (it's the first chunk of changes to `.drone.yml`).

gravitational/webapps#1116 also doesn't introduce changes that should be substantial for the push pipeline. It copies the tsh binary under a slightly different location but that's it.

There's a GitHub issue with a myriad of people running into this problem on CI servers but never locally. One person says that [it has to do with Spotlight](https://github.com/electron-userland/electron-builder/issues/4606#issuecomment-667641621) indexing the files on disk and suggests turning it off which is our best bet for now.

The recent update of electron-builder from 23.0.3 to 23.3.3 in gravitational/webapps#1098 might have also contributed to this issue.

Failed builds:

* push https://drone.platform.teleport.sh/gravitational/teleport/14948/6/6
* tag https://drone.platform.teleport.sh/gravitational/teleport/14943/25/5
* push https://drone.platform.teleport.sh/gravitational/teleport/14980/6/6

Successful builds:

* push https://drone.platform.teleport.sh/gravitational/teleport/14946
* tag https://drone.platform.teleport.sh/gravitational/teleport/14950/25/5

**Comment by ravicious** [comment]
diskimages-helper hanging and preventing the build from finishing despite the app being built successfully: https://gravitational.slack.com/archives/C0351AUPJ8K/p1664249725267459

Another failed push build: https://drone.platform.teleport.sh/gravitational/teleport/15962/6/6

**Comment by ravicious** [comment]
Spotlight indexing has just been disabled, we'll see if it has any effect.

**Comment by ravicious** [comment]
It looks like turning off Spotlight indexing has not helped. Another failed build due to `hdiutil: couldn't eject "disk8" - Resource busy`: https://drone.platform.teleport.sh/gravitational/teleport/16092/6/6

**Comment by zmb3** [comment]
@ravicious has this been an issue lately or can we close it?

**Comment by ravicious** [comment]
I haven't seen that one in a while, we can close it.
