### ISSUE TITLE
Issue using CAPSLOCK with Desktop Access

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#15849]
Expected behavior:

Turning CAPSLOCK on and off during a Desktop Access session should work as expected.

Current behavior:

Start a Desktop Access session, open Notepad:
- Type a word - it's not in capitals.
- Turn on CAPSLOCK, type another word - it's in capitals.
- Turn off CAPSLOCK, type another word - it's in capitals when it should not be.

Hitting the CAPSLOCK key does not register every time so the Desktop Access session is out-of-sync with the local CAPSLOCK setting.

Bug details:
- Teleport version: 10.1.4
- Recreation steps: As above.
- Debug logs: N/A

**Comment by zmb3** [comment]
Good find! I can confirm this behavior.

It looks to me like it takes two presses of capslock to trigger a change after the first attempt.

**Comment by zmb3** [comment]
Looks like something's related to the way the browser handles key down/up events.

I just tested on a random textarea via dev tools, pressing a key typically emits a down event and a subsequent up event as soon as the key is released.

For capslock, the events are handled differently. A keydown event is emitted when capslock is enabled, and a key up event is emitted when it is disabled. (They don't actually correspond to physical key down and up events in this case)

In fact, based on https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent this is a macOS issue:

>>> However, a limitation of the macOS event model causes Caps Lock to dispatch only the keydown event. Num Lock was supported on some older laptop models (2007 models and older), but since then, macOS hasn't supported Num Lock even on external keyboards. On older MacBooks with a Num Lock key, that key doesn't generate any key events. Gecko does support the Scroll Lock key if an external keyboard which has an F14 key is connected. In certain older versions of Firefox, this key generated a keypress event; this inconsistent behavior was [bug 602812](https://bugzilla.mozilla.org/show_bug.cgi?id=602812).

**Comment by zmb3** [comment]
We should probably also incorporate https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/6c5d0ef9-4653-4d69-9ba9-09ba3acd660f into our client to synchronize the initial state.
