### ISSUE TITLE
Add a file extension to the user’s private key

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#15845]
What would you like Teleport to do?

Add a file extension to the user’s private key created by a `tsh` login, e.g. user-name.key. Or allow this to be configured. 

What problem does this solve?

Some GUI clients that do not allow you to type in the file path to point to the Teleport certificates/keys so you can only select from the file browser and the file browser does not show files without an extension.

If a workaround exists, please include it.

Rename the private key file after each `tsh` login or create a symlink to the file.

**Comment by zmb3** [comment]
It's unlikely that we'll change this any time soon. Do you happen to recall which GUI client did not allow you to select a file without an extension?

**Comment by philip-teleport** [comment]
This came up using [QGIS](https://www.qgis.org/en/site/) with Teleport.

**Comment by zmb3** [comment]
Haven't seen any more request like this and I don't think we should break compatibility in order to support an issue in another product when a workaround (renaming the file) is universally available. Closing this one.
