### ISSUE TITLE
`tsh login` hangs with SAML authentication via FireFox 

### ISSUE THREAD

**Issue by tcsc** [gravitational/teleport#15858]
Expected behavior:
`tsh login` to progress through the normal login redirects and allow access to the cluster

Current behavior:
Login flow gets stuck at /login/sessionCookieRedirect

Bug details:

Seeing the following warnings in the JS console, which may (or may not) be related:

```
Cookie “JSESSIONID” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite sessionCookieRedirect

Cookie “t” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 sessionCookieRedirect
```

See Also:
- https://github.com/gravitational/cloud/issues/1657
- https://gravitational.slack.com/archives/C01TYKHFVTQ/p1661446657105929
- https://gravitational.slack.com/archives/C010BD557L6/p1653527421313329

gz#5473

gz#6401

**Comment by russjones** [comment]
@mcbattirola I know you are working on the new download page, do you have capacity to work on this?

**Comment by mcbattirola** [comment]
@russjones not right now, I'll probably be free to work on this again in a couple of days. I'll unassign myself for now in case anyone want to work on it.

___

I'll leave what I found here, in case it is useful:

I’m pretty sure the problem is in the call to [ConstructSSHResponse](https://github.com/gravitational/teleport/blob/master/lib/web/saml.go#L154), since the previous message is logged (`Callback redirecting to console login`) but the client never gets a response after this, but I couldn’t dig into its implementation too deep yet.

Running locally, I couldn't reproduce the bug, the login works fine.

**Comment by aos-10x** [comment]
This is happening to me as well. Some things I noticed:

- Logging in to Teleport cluster running `8` works just fine. 
- Chrome works fine
- Teleport cluster running `v10.0.2` **does not work**

**Comment by chipturner** [comment]
I am seeing similar issues.  Disabling (and re-enabling) http2 via `network.http.http2.enabled` made it start working again.  I suspect there is some http2 issue with teleport's servers, perhaps, and it is getting stuck on some pooled connection.  Just a theory based on tcpdumps and other behavior I saw when poking at it before toggling http2 and seeing it begin working again.

**Comment by sielakos** [comment]
@russjones @jimbishopp  I have trouble replicating it. I have tested platform.teleport.sh as described in this issue, but web login with firefox and okta works correctly. On my tenant in cloud, I have no problem with other SSO options such as GitHub.

@wadells I think has the same experience as [the comment](https://github.com/gravitational/cloud/issues/1657#issuecomment-1278462643) from 4 days ago indicates.

The issue may still occur somewhere, but I would have to have help understanding and replicating it.

**Comment by sielakos** [comment]
As @vitorenesduarte suggested I have also tried using an older version of Firefox from the issue description. The issue still does not occur.

**Comment by mcbattirola** [comment]
I just run a couple tests:

Firefox 105.0 (64-bit)

```bash
$ tsh version
Teleport v10.3.1 git:v10.3.1-0-g2fa9454 go1.18.6
Proxy version: 10.3.1
```

On `platform.teleport.sh`: It works fine

On `teleport.teleportinfra.sh`: It hangs awaiting response to `https://teleport.teleportinfra.sh/v1/webapi/saml/acs`


I also tried `teleport.teleportinfra.sh` with tsh v6.2.3 (same as cluster), and had the same issue.

**Comment by sielakos** [comment]
@mcbattirola Thanks for help!

If the problem occurs in older versions of teleport (6.X) do we still want to fix it? @jimbishopp
