### ISSUE TITLE
/docs/setup/guides/joining-nodes-aws-iam/#step-24-create-the-aws-node-joining-token

### ISSUE THREAD

**Issue by BrianGalfond-Teleport** [gravitational/teleport#15850]
## Details
To avoid confusion in Step 2, we should clarify that the AWS Node joining token (token.yaml) is stored on the auth server which you'll need access to. Also, when using the ADD SERVER option for AWS in the Web UI, generating a script automatically creates that AWS Node joining token.

### Category
- Improve Existing

**Comment by sdickhoven** [comment]
yes please 🙏 

maybe also explain _where_ `token.yaml` should be placed?

* `/etc/token.yaml` (i.e. "next to" `teleport.yaml`)?
* `$data_dir/token.yaml`?
