### ISSUE TITLE
[DevEnv] Public NTPD server to be setup 

### ISSUE THREAD

**Issue by dhilipkumars** [gravitational/teleport#1587]
**What happened**:
I was unable to auth (using google's 2-factor auth) as described in the installation instructions.

It was always throwing invalid token.

I had to install `ntpd` and configure [googles public time servers](https://developers.google.com/time/guides) to make it work

**What you expected to happen**:
Should we not add these in development document? 

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by kontsevoy** [comment]
@dhilipkumars sorry, I am not sure we're following you 100%. are you proposing that Teleport would ignore system time and talk to some NTPD servers directly?

**Comment by aberoham** [comment]
This has tripped me up once before where the machines I was working with had an incorrect timezone. Once that was corrected suddenly all of my certs were invalid (as the machine had jumped ahead). It's probably worth adding a note that system-level clocks should be accurate and synchronized by NTP or similar. Such a FAQ already exists in the [Telekube docs](https://gravitational.com/docs/faq/#system-time-sync)

**Comment by dhilipkumars** [comment]
@kontsevoy I was trying to configure teleport in my virtualbox VM (which was my dev-env) which was off by few seconds from googles NTP, so all my 2-factor auth (Authenticator App from my mobile) tokens were invalid. once i had NTPD installed and configured the tokens were accepted.  It is possible that onces dev machine (or VM in my case) is to 100% aligned with a public time server.

**Comment by benarent** [comment]
Due to age and no direct action I'm going to close this issue out. 

We could add a note in the docs about Google 2FA and server timing but it might complicate the setup instructions as it isn't a hard requirement.
