### ISSUE TITLE
Set default advertise addr on AWS to private instance IP

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1589]
In many samples I have seen, folks have been using sed to set private address to the private instance address.

Often folks are setting public EC2 IP as well, which I think is incorrect, as there is no reason to advertise public IP address. 

To fix this, I would set default advertise address of the instance to the private ipv4 if not specified on AWS, this would solve many problems.

**Comment by kontsevoy** [comment]
Notes from the discussion:

* `teleport start` already takes `--advertise-ip` argument.
* lets have a "sidecar" executable (and we'll have one for each cloud eventually) which we can use like this:

```bash
$ teleport start --advertise-ip=$(teleport-aws <arg>)
```

## Sidecars

I propose we add a new directory: `modules/aws` which will contain `main.go` + friends, and its binary output should go to `build/modules`, which will be packaged into the distribution.

How about `tele-aws-tool`? This leads to obvious `tele-gce-tool`, `tele-openstack-tool`, etc.. in the future.

**Comment by klizhentas** [comment]
tool is extra, could be just `teleport-aws`. I don't think `tele` prefix is good, because we have a tool called `tele`

**Comment by klizhentas** [comment]
Note: we've decided not to add extra binary, rather provide good examples/documentation on how to set those things via CLI/env variables
