### ISSUE TITLE
Compile master

### ISSUE THREAD

**Issue by tomberek** [gravitational/teleport#1590]
**What happened**:
Go compilation error (go1.9) 
go/src/github.com/gravitational/teleport/integration/helpers.go:952:30: undefined: Host

**What you expected to happen**:
No error

**How to reproduce it (as minimally and precisely as possible)**:
compile b3d4d36fdecbf43a2a087a2266b448fcd529f693

**Environment**:
- Teleport version (use `teleport version`): master (b3d4d36fdecbf43a2a087a2266b448fcd529f693)
- Tsh version (use `tsh version`): master
- OS (e.g. from /etc/os-release): NixOS

This line may be to blame:
https://github.com/gravitational/teleport/blob/master/integration/helpers.go#L952
I don't see where `Host` is defined.

**Comment by klizhentas** [comment]
Just tried on master (although mac, not linux) gives me:

```bash
$ go version
go version go1.8.5 darwin/amd64
$ make goinstall
go install  -ldflags '-w -s' \
		github.com/gravitational/teleport/tool/tsh \
		github.com/gravitational/teleport/tool/teleport \
		github.com/gravitational/teleport/tool/tctl
$ git rev-parse HEAD
b3d4d36fdecbf43a2a087a2266b448fcd529f693
$ go test ./integration/
ok  	github.com/gravitational/teleport/integration	39.128s
```

What go version do you use?

**Comment by tomberek** [comment]
Go1.9 per my report.

**Comment by tomberek** [comment]
Heads-up. I’m packaging teleport for NixOS. 
https://github.com/NixOS/nixpkgs/pull/33853

**Comment by klizhentas** [comment]
Sorry, missed that, let me try 1.9

**Comment by klizhentas** [comment]
hm, could not repro with 1.9 either, will try on linux box tomorrow.

>Heads-up. I’m packaging teleport for NixOS.

thanks for that!

**Comment by tomberek** [comment]
I'm doing `make full`. Is that not needed?

**Comment by klizhentas** [comment]
I've tried both make full with 1.9 on ubuntu could not reproduce :/

**Comment by tomberek** [comment]
I'll close, perhaps i had something wrong.

**Comment by Manuel1510** [comment]
I just had the same error while trying to `go install github.com/gravitational/teleconsole`

`go/src/github.com/gravitational/teleport/integration/helpers.go:1220:30: undefined: Host`

Any hint on how to fix it?

**Comment by severach** [comment]
See `TELEPORTVER=` in `teleconsole/Makefile'. Each `teleconsole` version requires a specific version of `teleport`. You get errors if the build checks out the wrong version.
