### ISSUE TITLE
Predicate Language Doc

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#15922]
Following this [documentation](https://goteleport.com/docs/setup/reference/predicate-language/#resource-filtering), we found an issue when trying to query node by name. In doc it states the following command  ` tsh ls --query 'name == "some_name"` should query by node name. It turns out, the  'name' / 'resource.metadata.name' is the uuid, and not the node name.

---

Given the following node list:

```
$ tsh ls
Node Name                 Address        Labels
------------------------- -------------- ------------------------------------------------------
node1                     ⟵ Tunnel       arch=x86_64,hostname=node1,ip=192.168.168.191/24,up...
```

I would expect this to return my node:

```
$ tsh ls --query 'name == "node1"'
Node Name Address Labels
--------- ------- ------


  Not seeing nodes? Your user may be missing Linux principals. If trying teleport for the first time, follow this guide:

https://goteleport.com/docs/getting-started/linux-server/#step-46-create-a-teleport-user-and-set-up-two-factor-authentication
```

The doc points out that it is looking at `metadata.name` on the resource, which is the auto-generated uuid.

```
$ tctl get node/node1 | yq -P .metadata.name
23bc35d7-10f5-421f-9ef4-890af45e3166
```

To show that the `name ==` query is looking at the uuid rather than the actual node name, the following output is observed:

```
$ tsh ls --query 'name == "23bc35d7-10f5-421f-9ef4-890af45e3166"'
Node Name Address    Labels
--------- ---------- --------------------------------------------------------------------------
node1     ⟵ Tunnel   arch=x86_64,hostname=node1,ip=192.168.111.21/24,uptime=up 4 weeks, 4 d...
```

---

tested with `Teleport v10.1.9 git:v10.1.9-0-g8f6f6ccbb go1.18.3`

Documentation: https://goteleport.com/docs/setup/reference/predicate-language/#resource-filtering

**Comment by alexfornuto** [comment]
Is the resolution here to update the software so that `metadata.name` is the human-friendly name, or to update the docs to indicate that `metadata.name` uses the UUID? If the latter, what query would provide the "node name"?
