### ISSUE TITLE
Update CockroachDB logos

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#15925]
## Details

CockroachDB has a new logo, and the diagram in our CockroachDB guide uses the old one. Let's use this new logo instead:

![image](https://user-images.githubusercontent.com/25250668/187299780-12d3d49c-6fba-431d-98c8-f6deaa598bc7.png)

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
Resolved in #15978
