### ISSUE TITLE
[Teleport Discover] Kubernetes Access - Day 1 Experience

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#15923]
- Minimalist design approach (i.e. we are not building a Kubernetes client)
- Kubernetes Access in Connect works much like Server Access. Users can click a “Connect” button next to the Kube cluster they want to connect to and Connect opens a new terminal tab. Only instead of a remote SSH terminal, it’s a local shell with #KUBECONFIG set to a temporary kubeconfig specifically generated for this Kube cluster. Upon opening the local shell, we run `kubectl --cluster-info` for 2 reasons:
    - To prompt users that kubectl is not installed if that’s the case
    - To display relevant cluster information to the user so that they know what they’re looking at

**Comment by rishibarbhaya-design** [comment]
To access the Design Go to Figma > In Progress Work file > Ticket #13295 | Teleport Discover UI
https://www.figma.com/file/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?node-id=444%3A49313
Follow the section label marked in Yellow 🟨 

Kindly share your comments in the Figma to boost the process
