### ISSUE TITLE
IAM join method should use FIPS AWS STS endpoints

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#15927]
Expected behavior:
When Teleport is running in FIPS mode, the IAM join method should use FIPS AWS STS endpoints when reaching the STS service.

The joining node should target the FIPS endpoint when generating the signed `sts:GetCallerIdentity` request, and the auth server should ideally enforce that the FIPS endpoint is used (with consideration of backward compatibility).

Current behavior:
Regular non-fips endpoints are used.

Bug details:
- Teleport version: Since inception of IAM join method, 8.3+
- Recreation steps
- Debug logs

**Comment by reedloden** [comment]
To be clear, only need to use FIPS endpoints when in FIPS mode. :-)
