### ISSUE TITLE
Windows Desktop Session Disconnected error when initiated from client.

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#15948]
Expected behavior:

When using Desktop Access if you click the Teleport disconnect button you get a friendly message that it successfully disconnected. When you log out of Windows using the Windows log out procedure you expect the same message.

Current behavior:

Instead you get this:

 but if you go through the Windows log out procedure you get a red box:

![Screen Shot 2022-08-30 at 8 58 53 AM](https://user-images.githubusercontent.com/1424442/187451430-a64e7839-361e-4757-8a34-de13bf500a88.png)

I believe it is because the disconnection is coming from Windows vs Teleport. When disconnecting from Teleport it has time to display a friendly message. When you disconnect from Windows it drops the connection and Teleport thinks it might be an error or another disconnect and flags it.

Bug details:
- Teleport version `v10.1.4`
- Recreation steps:
  1. Log into Windows desktop
  2. Log out with Windows log out procedure
  3. Be greeted with red box.
   
- Debug logs

**Comment by zmb3** [comment]
Thanks for filing this, Allen.

In this case, the server sends a notification to us indicating the reason it's about to disconnect, but we're not currently handling that part of the protocol.

I've captured most of the details in #14451, so I'm going to close this as a duplicate.
