### ISSUE TITLE
Add ability to override default browser to `tctl sso test`

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#15950]
**What would you like Teleport to do?**

When running `tctl sso test file.yaml`, the system's default browser will open to handle the SSO flow. This isn't always desirable - sometimes you want to test with a different user, or in a different browser, or use an incognito window to see the full flow from end to end.

`tsh login` supports the use of `--browser=none` to just print the URL to the console - it'd be good if `tctl sso test` supported the same flag.

**What problem does this solve?**

Makes SSO testing easier.

**If a workaround exists, please include it.**

None known currently.

**Comment by zmb3** [comment]
See also #5592 which is the same request, but for `tsh login` instead.
