### ISSUE TITLE
Resource Requests: add `--resource` to `tctl request create`

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#15966]
**What would you like Teleport to do?**

When running `tctl request create`, it should be possible to create a resource request.

**What problem does this solve?**

it would allow the current role request functionality that you get out of `tctl request create` but with resource requests too.

**If a workaround exists, please include it.**

none that I am aware of.

Perhaps something like a teleport plugin that uses client.go in order to create the request. It would be handy to have such an example if that is possible.

gz#6508

**Comment by zmb3** [comment]
You can create resource requests today with the CLI using `tsh request search` and `tsh request create`: https://goteleport.com/docs/access-controls/access-requests/resource-requests/#step-48-search-for-resources

Is this what you're looking for?

**Comment by yuri-1987** [comment]
> 



> You can create resource requests today with the CLI using `tsh request search` and `tsh request create`: https://goteleport.com/docs/access-controls/access-requests/resource-requests/#step-48-search-for-resources
> 
> Is this what you're looking for?

When I initially requested this, my intention was to use TSH. I don't believe it is possible to request a resource on behalf of a dynamic user (SSO) with privileged rights.

**Comment by nklaassen** [comment]
> I don't believe it is possible to request a resource on behalf of a dynamic user (SSO) with privileged rights.

@yuri-1987 With `tsh` you should be able to log in with SSO and create an access request. But it sounds like maybe you are trying to create some automation to have a bot or admin create an access request on behalf of a dynamic user. Can you share a bit more about your use case?

**Comment by yuri-1987** [comment]
> > I don't believe it is possible to request a resource on behalf of a dynamic user (SSO) with privileged rights.
> 
> @yuri-1987 With `tsh` you should be able to log in with SSO and create an access request. But it sounds like maybe you are trying to create some automation to have a bot or admin create an access request on behalf of a dynamic user. Can you share a bit more about your use case?

Hi @nklaassen , sure, in our case, we have an internal portal for non-technical users, where we provide various information about nodes (not just teleport information), this portal has a privileged teleport role, and we were thinking about creating a feature where they can request access to a specific node, and we will ask for this on their behalf, and once approved they will have a link to the assumed role with specific resource access.

**Comment by programmerq** [comment]
@zmb3 

The current `tctl` command does allow a user with a certain level of permissions to create a request on behalf of another user. In my test lab, I was able to log in as my "admin" user and then create a request on behalf of my "bob" user:

```
$ tctl request create --roles exec bob
f90001c2-aace-4569-8494-b568a64cfcf5
```

This interface simply doesn't have the capability to also do `--resource` as opposed to `--roles`.

Additionally, this type of functionality would seem to be a better fit for a plugin type of process rather than tctl, but tctl also seems like a logical utility to have a CLI interface for any operation that a plugin should be able to do. Having a hint or an example for how a plugin might achieve this would be handy.

I think the idea of having a plugin create resource requests on behalf of a user has a decent UX capability for some of the more interesting or less common use cases like the one described.

**Comment by zmb3** [comment]
I see, so you're pointing out that even though `tsh` works for both role-based and resource-based access requests, `tctl` only works for role-based.

**Comment by nklaassen** [comment]
Yeah, I didn't consider this usecase when adding the command to `tsh`, I think we should add it to `tctl` as well
