### ISSUE TITLE
WebAuthn MFA from a Remote Host

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#15960]
**What would you like Teleport to do?**
Allow users to use WebAuthn/USB-based MFA from a remote machine. 

**What problem does this solve?**
When WebAuthn MFA is required, users have no way to authenticate from a remote machine.

**If a workaround exists, please include it.**
Switch to OTP MFA. (not viable for many customers)

Related to #15688.

**Comment by zmb3** [comment]
This is covered by headless SSO.
