### ISSUE TITLE
rdp protocol error ,windows server  2019

### ISSUE THREAD

**Issue by RyanCode** [gravitational/teleport#15993]
Rdp(RdpError(RdpError { kind: ProtocolNegFailure, message: "Error during negotiation step: the server requires that the client support enhanced RDP security with CredSSP" }))

>It is impossible for users to modify the configuration of the target server. It is a very bad experience to adapt the teleport by modifying the configuration of the server.
Has your team considered adapting cipher suites to the rdp standard?

**Comment by zmb3** [comment]
This is unrelated to cipher suites. This is the server requiring NLA, which must currently be disabled for our smart card authentication as per 

https://goteleport.com/docs/desktop-access/getting-started/#allow-remote-rdp-connections

We will be working on supporting NLA in the future - that work is tracked in #8546

**Comment by RyanCode** [comment]
> This is unrelated to cipher suites. This is the server requiring NLA, which must currently be disabled for our smart card authentication as per
> 
> https://goteleport.com/docs/desktop-access/getting-started/#allow-remote-rdp-connections
> 
> We will be working on supporting NLA in the future - that work is tracked in #8546
> 
> Thanks, looking forward to supporting NLA

**Comment by RyanCode** [comment]
Thanks, looking forward to supporting NLA
