### ISSUE TITLE
Make errors more visible

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1599]
See error below. The important part of the message is that "User already exists. Remove local user and try again." yet, it's rendered really small compared to not helpful "login unsuccessful." page. May be spend some time on page UX.

![login](https://user-images.githubusercontent.com/13717/34967290-6e2b3e24-fa16-11e7-80a2-68b02228bf48.png)

**Comment by kontsevoy** [comment]
clients are only supposed to see "access denied". the detailed error descriptions must be logged to teleport's audit log
