### ISSUE TITLE
Get rid of Microsoft Defender SmartScreen warnings when installing Connect on Windows

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#15995]
This is what it takes to install Connect on Windows today:

https://user-images.githubusercontent.com/27113/187653063-632770cd-6690-4dc9-bbc3-a4bbc84747a7.mov

There are two problems:

* Edge prevents you from opening the file unless you explicitly acknowledge that it might be unsafe.
* On top of that, Microsoft Defender is going to prompt you again just before executing the installer.

The first one is specific to Edge and doesn't exist in Chrome. The second problem persists no matter which browser you use and both problems are related to SmartScreen.

> Applications that are signed with a standard code signing certificates need to have a positive reputation in order to pass the Smart Screen filter. Microsoft establishes the reputation of an executable based upon the number of installations world wide of the same application. Since you haven't published your application as yet (and therefore the reputation hasn't been established as yet), the Smart Screen will continue to flag the application.
>
> There are two solutions: either wait till the application has a large user base and its reputation will be adjusted by the Smart Screen. However, the current working status might prevent users from installing and trusting the application. The second option is to sign it with an EV (Extended Validation) code signing certificate. Applications signed with an EV certificate establishes its reputation right away.

https://security.stackexchange.com/a/139520/127482

https://docs.microsoft.com/en-gb/archive/blogs/ie/microsoft-smartscreen-extended-validation-ev-code-signing-certificates

# Early investigation

The standalone tsh.exe doesn't trigger the SmartScreen warning, perhaps because it's been already installed by customers on many devices.

It appears that our cert is a regular code signing cert from DigiCert rather than an EV code signing cert. https://www.digicert.com/signing/code-signing-certificates#EV-Code-Signing

**Comment by ravicious** [comment]
@zmb3

> An encrypted token containing the private key is stored on a USB device that you receive after you purchase your certificate. Only those who have the physical device can sign code with your EV code signing certificate, providing reinforced authentication and enhanced security.

I guess this rules out our Windows builders?

**Comment by zmb3** [comment]
Good find. Seems [possible](https://docs.aws.amazon.com/cloudhsm/latest/userguide/signtool.html) but maybe more involved than we were hoping.

**Comment by ravicious** [comment]
I just downloaded the installer for 10.2.4 without warnings. I wonder if it's because I already allowlisted an item from goteleport.com or if the warning is gone altogether, I suspect the former.

**Comment by gzdunek** [comment]
I just created a new Windows 11 VM and installed 11.0.3 without any warnings. It seems that the problem no longer occurs.
