### ISSUE TITLE
Have the ability to download files from moderated sessions

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#16008]
What would you like Teleport to do?
The customer would like the ability to use SCP or any method to download files in moderated sessions, currently they are not able to perform these actions. 

What problem does this solve?
Allow the ability to securely copy files from a moderated session to another host

If a workaround exists, please include it.

No workaround exist at the moment.

**Comment by dmsergeevN26** [comment]
This should probably extended to uploads as well.

**Comment by russjones** [comment]
@kylern I put this into Q1 planning. That doesn't mean we'll work on it, but we'll discuss to see if it can be scheduled in Q1.

Please reach out to me again in Q1 and I can tell you if it got scheduled.

**Comment by DiogoMCampos** [comment]
@russjones Out of curiosity, did this get sscheduled?

**Comment by zmb3** [comment]
Released in v13.0.0 (web UI only)
