### ISSUE TITLE
Describe TTL when accessing a leaf node from the root cluster

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#16002]
## Details

The "How does this work" section of the [Trusted Clusters documentation](https://goteleport.com/docs/management/admin/trustedclusters/#how-does-this-work) should include a description on what defines the TTL (time to live) on the user's session when accessing a leaf node from the root cluster.  Is it the TTL defined on the mapped role on the leaf and not the current TTL on the user's certificate on the root?

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
> Is it the TTL defined on the mapped role on the leaf and not the current TTL on the user's certificate on the root?

That's a good question. @zmb3 do you know the answer, if not can you ping someone who might?

**Comment by zmb3** [comment]
The root cluster only knows the names of the roles in the leaf cluster, but not their contents, so I'm fairly certain that it would have to be the TTL on the user's certificate on the root.

@nklaassen does that sound right?

**Comment by nklaassen** [comment]
Yes, the ttl is defined by the users certificate, which they get when they initially log in to the root cluster, and is only controlled by the roles in the root cluster
