### ISSUE TITLE
K8s access not working with multiplexing

### ISSUE THREAD

**Issue by ognjenVlad** [gravitational/teleport#16145]
Expected behavior:
kubectl connects to k8s cluster using Teleport with multiplexing

Current behavior:
kubectl only works with legacy listeners and can only connect with 3026 port and kube_listen_addr set up. 

If we try to connect using 433 and multiplexing kubectl fails with `x509: certificate signed by unknown authority`. Certificate authority inside kubeconfig is the same for both ports. 

Teleport proxy is failing with bad certificate error only when using port 433. With legacy listeners everything works as expected.

Bug details:
- Teleport version: 10.1.9
- Recreation steps: We are using docker-compose with acme to start teleport
- Debug logs:
`2022-09-06T10:04:59Z WARN [ALPN:PROX] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *tls.permanentError remote error: tls: bad certificate
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:376 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
	/go/src/github.com/gravitational/teleport/lib/srv/alpnproxy/proxy.go:314 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: remote error: tls: bad certificate] alpnproxy/proxy.go:322`

**Comment by stevenGravy** [comment]
@ognjenVlad please share how you set the auth and proxy service.  Are there any load balancers between a user and the proxy service?

**Comment by ognjenVlad** [comment]
Hey @stevenGravy , thanks for fast response. There is no load balancers in between user and the proxy.

`version: v2

teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
  auth_servers:
  - "example.com:3025"

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: example.com
  authentication:
    type: github
  proxy_listener_mode: multiplex

ssh_service:
  enabled: "yes"
  
proxy_service:
  enabled: "yes"
  # kube_listen_addr: 0.0.0.0:3026 this has to be enabled to be able to connect to k8s cluster
  web_listen_addr: 0.0.0.0:443
  public_addr: scotty.bestbytes.net:443
  acme:
    enabled: "yes"
    email: admin@example.com
`

**Comment by stevenGravy** [comment]
Thanks, that listen_addr is required to enable k8s protocol.  If you do a `kubectl get po -v=8` should confirm it's still going through the `443` port.

**Comment by tigrato** [comment]
@ognjenVlad which `kubectl` version are you using?

This is happening because the SNI is not being sent either because the kubeconfig does not include `tls-server-name` or because your kubectl does not support it.

Does your `kubeconfig` include the `tls-server-name` field in the Teleport cluster?
