### ISSUE TITLE
Validate roles when SSO connectors are created

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#16160]
**Expected behavior:**

If a role doesn't exist give a warning that the user will not be able to log in, at the moment if the non-existing role is configured user will be locked out. 

![image](https://user-images.githubusercontent.com/103964432/188686940-9413226c-ce5b-408d-bb29-15fb6aedfc57.png)

![image (1)](https://user-images.githubusercontent.com/103964432/188686968-78a13f76-9c98-4728-9dca-dadbc5756463.png)

**Current behavior:**

We have encountered an issue when configuring SAML that includes a mapping role that doesn't exist. Adding this non-existing role will prevent the user from login in. 

<img width="864" alt="Screen Shot 2022-09-06 at 11 01 06 AM" src="https://user-images.githubusercontent.com/103964432/188686153-07d3fe89-bc4f-4030-9cd2-13d73dd91684.png">

**Bug details:**
- Teleport version
- 10.1.2
- Recreation steps
- Add a non-existing role to SAML

**Comment by zmb3** [comment]
Good call - we should be validating all the roles at connector creation time.

**Comment by wadells** [comment]
Similar lockouts can also happen with local users as described in https://github.com/gravitational/teleport/issues/16614
