### ISSUE TITLE
helm: Register Helm repository on artifacthub.io

### ISSUE THREAD

**Issue by jlucidar** [gravitational/teleport#16163]
I would really like to see teleport listed on artifathub.io, it helps a lot with documentation and release tracking.

It seems that the chart repo is almost fully compatible (only a few image links are broken).
I tried to integrate it for testing purposes, but it would look better with an official teleport account : 
https://artifacthub.io/packages/helm/teleport-agent-kube/teleport-kube-agent

You just need to create an account on their website, and register the following repo url : https://charts.releases.teleport.dev

Thanks !

**Comment by hugoShaka** [comment]
Note: we would need to add annotations for artifacthub to understand that our test versions are not viable for deployment. It seems artifacthub has different rules than helm for choosing the lastest version.

This is an issue as when you search "teleport" in artifact hub it currently points users to my test releases, which is harmful:
![image](https://user-images.githubusercontent.com/16366487/190229290-0dfaa114-cdf2-497e-987f-53faa898e952.png)

**Comment by klizhentas** [comment]
For now, we would like to only promote teleport-controlled artifact distribution repositories to avoid supply chain attacks. That is why we would discourage any artifact repositories to host or publish our charts/packages.
