### ISSUE TITLE
Refactor Helm charts to make detecting available upgrades easier

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#16178]
> As a general comment, I'd also like to point out that it would be much easier for us to detect when an upgrade is necessary if the teleport-kube-agent helm chart was published properly, rather than being a sub-directory on the teleport repo. If it was published, then dependabot or other dependency update checkers could see that the new version has been released and automatically open PRs for us to upgrade. As it is, I have to pay attention to my email or other Teleport communications.

**Comment by russjones** [comment]
Internal ticket: https://gravitational.zendesk.com/agent/tickets/6591

**Comment by highb** [comment]
This was my comment. Subscribing to this thread for updates. 🙂

**Comment by r0mant** [comment]
@highb I'd like to get more details about your use-case. We do publish our Helm charts to a publicly available chart repository:

```
➜  ~ helm repo list
NAME    	URL
teleport	https://charts.releases.teleport.dev
➜  ~ helm search repo teleport
NAME                                  	CHART VERSION	APP VERSION	DESCRIPTION
teleport/teleport                     	0.0.13       	6          	[This chart is deprecated, use teleport-cluster...
teleport/teleport-cluster             	9.3.8        	9.3.8      	Teleport is a unified access plane for your inf...
teleport/teleport-kube-agent          	9.3.8        	9.3.8      	Teleport provides a secure SSH and Kubernetes r...
teleport/teleport-plugin-email        	9.3.7        	9.3.7      	A Helm chart for Kubernetes
teleport/teleport-plugin-event-handler	9.3.7        	9.3.7      	A Helm chart for Teleport Event Handler Plugin
teleport/teleport-plugin-mattermost   	9.3.7        	9.3.7      	A Helm chart for the Teleport Mattermost Plugin
teleport/teleport-plugin-pagerduty    	9.3.7        	9.3.7      	A Helm chart for the Teleport Pagerduty Plugin
teleport/teleport-plugin-slack        	9.3.7        	9.3.7      	A Helm chart for the Teleport Slack Plugin
```

Could you elaborate regarding what you mean by "not being published properly"?

**Comment by highb** [comment]
Oh, when I adopted the helm chart, it was only hosted in the `examples` subdirectory on the Teleport repo. If it is published to `https://charts.releases.teleport.dev` then we're good to go! Thank you!
