### ISSUE TITLE
Unable to access Aurora primary endpoint after removing a reader

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#16188]
Expected behavior:
Able to access Aurora database

Current behavior:
Unable to access Aurora primary database after removing a reader as the IAM auth IAM policy is removed

Bug details:
- Teleport version: v10
- Recreation steps
1. Create an Aurora cluster with two databases
2. Enables auto-discovery, and give database agent permission to enable IAM auth through IAM policy
3. Verify can connect to both primary and reader databases through tsh
4. Delete reader instance from the Aurora cluster
5. Wait a while and check if reader database is gone from `tsh db ls`
6. Connect to the primary database fails

Workaround:
Restart database agent

**Comment by GavinFrazar** [comment]
This issue is solved if we solve https://github.com/gravitational/teleport/issues/43829

I don't think it's worth fixing explicitly otherwise, since v17 will start the migration away from dynamic IAM permissions. Without the dynamic IAM permissions, the bug is gone.
