### ISSUE TITLE
`TestAppAccess/TestAppInvalidateAppSessionsOnLogout` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#16200]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/9780d3e1-1482-4f64-8f00-6637678a9337?project=ci-account

#### Relevant snippet

```
        	Test:       	TestAppAccess/TestAppInvalidateAppSessionsOnLogout
        	            	actual  : 302
        	            	expected: 200
        	Error:      	Not equal: 
        	Error Trace:	app_integration_test.go:710
    app_integration_test.go:710: 
```

**Comment by zmb3** [comment]
Hit on v10 today: https://console.cloud.google.com/cloud-build/builds/62dc3494-c3a3-4817-a250-67fe8e855c81;step=0?project=ci-account

**Comment by tigrato** [comment]
Another hit on v10 https://console.cloud.google.com/cloud-build/builds/201452df-a9d0-45c7-8e9b-ebc8e9f27808?project=ci-account

**Comment by zmb3** [comment]
Another v10: https://console.cloud.google.com/cloud-build/builds/37294671-af57-4269-a29c-bdd9b912b8c4;step=0?project=ci-account

**Comment by GavinFrazar** [comment]
https://console.cloud.google.com/cloud-build/builds/bba72ce5-8ec4-4848-a2b7-ff8cfdb2f15c?project=ci-account

https://console.cloud.google.com/cloud-build/builds/4070d0f7-1752-4748-a018-c502d856d59a?project=ci-account

In a branch/v10 backport: https://github.com/gravitational/teleport/pull/18618

**Comment by GavinFrazar** [comment]
another one on the same backport: https://console.cloud.google.com/cloud-build/builds/6063777e-6920-44dd-b13a-d167e89a4587?project=ci-account

**Comment by tigrato** [comment]
In a branch/v11 backport https://console.cloud.google.com/cloud-build/builds/9d303194-275c-4c3c-af15-b8b19e1d6054?project=ci-account

**Comment by tigrato** [comment]
branch/v10 again https://console.cloud.google.com/cloud-build/builds/32ec2736-cbd9-4afd-9683-8e8e4c95bc06?project=ci-account

**Comment by ibeckermayer** [comment]
```
    appaccess_test.go:583: 
        	Error Trace:	/__w/teleport/teleport/integration/appaccess/appaccess_test.go:583
        	            				/__w/teleport/teleport/integration/appaccess/fixtures.go:376
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 504
        	Test:       	TestAppAccess/TestAppInvalidateAppSessionsOnLogout
```

On master 

https://github.com/gravitational/teleport/actions/runs/3850890563/jobs/6561526328

**Comment by tigrato** [comment]
It's difficult to merge anything into branch/v10 because of this issue
- https://console.cloud.google.com/cloud-build/builds/68bb33b8-c92a-44af-8ec7-51f06d5779de?project=ci-account

**Comment by ibeckermayer** [comment]
Killing me on a v11 backport this evening
- https://console.cloud.google.com/cloud-build/builds/16da358b-b755-42d3-8800-6415e496048e?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/ecf15a91-5eb6-483f-b237-d0d84c204772?project=ci-account

**Comment by zmb3** [comment]
Closing since there have been no recent reports
