### ISSUE TITLE
Terminal not cleared upon `client_idle_timeout` in FIPS mode

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#16225]
In https://github.com/gravitational/teleport/pull/10095 we implemented clearing of the terminal upon session termination.

However, a customer is reporting that the terminal is not cleared when session is terminated upon reaching `client_idle_timeout` configured in the user's role set when auth server is running in FIPS mode. Terminal _is_ cleared if the session is closed manually. Terminal also seems to be cleared in web UI sessions.

Customer's set up where they're reproducing this in is just a root cluster running in FIPS mode, however we should make sure it works for leaf cluster sessions as well.

Success criteria:

- [ ] Make sure that `client_idle_timeout` is respected properly. It seems that any input/output on the session resets the idle timer, let's just verify this is the case.
- [ ] Make sure terminal is getting cleared when session is closed manually.
  - [ ] Make sure this is the case for both tsh and web UI sessions.
  - [ ] Make sure it works for both root and leaf clusters running in FIPS mode.
  - [ ] Make sure it works for leaf cluster sessions when root is not running in FIPS mode (is this a supported scenario at all?)
- [ ] Make sure terminal is getting cleared when session is terminated upon reaching client idle timeout.
  - [ ] Make sure this is the case for both tsh and web UI sessions.
  - [ ] Make sure it works for both root and leaf clusters running in FIPS mode.
  - [ ] Make sure it works for leaf cluster sessions when root is not running in FIPS mode (is this a supported scenario at all?)

**Comment by atburke** [comment]
Fixed by #16391.
