### ISSUE TITLE
Post AWS EC2 discovery follow-on features

### ISSUE THREAD

**Issue by lxea** [gravitational/teleport#16236]
- [x] Add a `teleport discovery bootstrap` command
  - Make use of contents of config.yaml file
  - For EC2 creation this should:
     - Create an IAM policy with that will allow the discovery node to send ssm commands and retrieve ec2 instances
- [ ] migrate to aws-sdk-v2

**Comment by zmb3** [comment]
Closing as completed, since the only remaining task (AWS SDK migration) is already being tracked at #14142
