### ISSUE TITLE
Teleport AMIs should include plugin binaries and accompanying scripts/roles

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#16244]
### What would you like Teleport to do?

Teleport AMIs should include plugin binaries and accompanying scripts/roles. The AMIs live in this repository, so I am opening the issue here. https://github.com/gravitational/teleport/tree/master/assets/aws

### What problem does this solve?

As plugins become more common, it is helpful to be able to deploy them alongside our recommended teleport cluster setups. This includes our cloudformation and terraform scripts that deploy these AMIs.

### If a workaround exists, please include it.

Build a new AMI based off of release Teleport AMIs that installs the plugins.

**Comment by fheinecke** [comment]
Not planned, see https://github.com/gravitational/teleport.e/pull/4309#pullrequestreview-2096890995 (internal) for details.
