### ISSUE TITLE
lib/events: determine if we can remove metadata.index

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#16250]
Audit events have an index field (which is encoded in the JSON as `ei`) that is described as:

```
// Index is a monotonicaly incremented index in the event sequence
```

It looks like this may be a remnant of prior iteration of the session recording system. Today, we only ever set this index to a non-zero value in a couple circumstances:

- in tests
- `SessionDataIndex` (a large value that attempts to ensure that the `session.data` event has a higher index than any other events in the session)
- `SessionUploadIndex` (an even larger value that attempts to ensure that `session.upload` has the highest index in a session recording)

I don't see any code left that depends on `session.data` or `session.upload` having a specific value, so I think we might be able to remove this field. Since it's undocumented, has an unclear name "ei", and is not necessary, let's get rid of it if we can.

**Comment by espadolini** [comment]
We also set it in `AuditWriter` to a consecutive value that's supposed to match the index of the event in the recording file, FWIW.
