### ISSUE TITLE
`TestTLSConfiguration/valid_provided_CA/mongodb` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#16265]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/044dcd8e-438a-497d-9134-89adc1ebf181?project=ci-account

#### Relevant snippet

```
        --- FAIL: TestTLSConfiguration/valid_provided_CA/mongodb (17.23s)
```

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/1209c0e8-e446-4cfe-97a1-ac58b992b38b?project=ci-account

**Comment by zmb3** [comment]
Saw a similar failure in a different subtest on v9 today: https://console.cloud.google.com/cloud-build/builds/bdba6072-06a1-4d5f-90ed-571319a82f97;step=0?project=ci-account

```
 TestTLSConfiguration/server_name_can_be_overridden_on_provided_CA/mongodb
    ca_test.go:467: 
        	Error Trace:	/workspace/lib/srv/db/ca_test.go:467
        	Error:      	Received unexpected error:
        	            	server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: 127.0.0.1:34831, Type: Unknown, Average RTT: 0 }, ] }
        	Test:       	TestTLSConfiguration/server_name_can_be_overridden_on_provided_CA/mongodb
```

**Comment by zmb3** [comment]
Another v9 failure: https://www.google.com/search?client=safari&rls=en&q=restrict+input+to+whole+numbers&ie=UTF-8&oe=UTF-8

**Comment by jakule** [comment]
@zmb3 @ibeckermayer I see that the last reported failure is from Nov. Can we close this issue?

**Comment by zmb3** [comment]
Sure. I haven't seen this one come up recently, and it looks like it was only on v9, which will start receiving a lot less PRs very soon.
