### ISSUE TITLE
Support query string in URI for Application Access

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#16297]
### What would you like Teleport to do?

As confirmed in [15796](https://github.com/gravitational/teleport/discussions/15796), URI string in application access does not support query string (like `https://localhost/xslweb/login.do?useLegacy=1`). This FR is to support query string in URI.

### What problem does this solve?
Application can be configured to land on specific page based on query string. 

### If a workaround exists, please include it.

This can be achieved using a proxy path configuration to default to query string, but if multiple paths are required for same app, this will not work.

**Comment by zmb3** [comment]
This is a duplicate of an earlier issue from today, #16278, which is itself a duplicate of #15998.

I've moved the `c-xa` tag to the original and will close this one out.
