### ISSUE TITLE
Unable to login teleport SSH session

### ISSUE THREAD

**Issue by mdrasheek** [gravitational/teleport#16308]
Expected behavior:

Usual teleport SSH session

Current behavior:

ERROR: access denied to root connecting to XXXX on cluster XXX)

Bug details:
- Teleport version: Teleport v10.1.4 git:v10.1.4-0-gf095c6f go1.18.3
- Recreation steps: Post joining the node to cluster, I'm unable to login through SSH.
- Debug logs:
- 
[tsh-debug-log.txt](https://github.com/gravitational/teleport/files/9539636/tsh-debug-log.txt)

Please suggest a way to fix this.

**Comment by zmb3** [comment]
Your user needs to have a role that grants access to the SSH node.

You may find some of our [getting started](https://goteleport.com/docs/access-controls/getting-started/) guides helpful here. If not, feel free to start a discussion and we'll try our best to help.

**Comment by mdrasheek** [comment]
Yes, My user has a role associated to it. Please refer the output below.

% tsh status
> Profile URL:        https://teleport.e2enetworks.com:443
  Logged in as:       rasheek
  Cluster:            teleport.e2enetworks.com
  Roles:              access, auditor, editor, nebu-root, superuser, temp-root
  Logins:             root, e2ecloud, -teleport-internal-join
  Kubernetes:         enabled
  Valid until:        2022-09-12 16:10:57 +0530 IST [valid for 4h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

**Comment by mdrasheek** [comment]
This I have figured it out, the error was due to incorrect time between server and the remote node. Post fixing the time it is done.
