### ISSUE TITLE
`TestDatabaseRootLeafIdleTimeout/leaf_role_with_idle_timeout` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#16347]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/54250ba2-8a93-4e5c-9f15-607cf03ac72c?project=ci-account

#### Relevant snippet

```
        	Test:       	TestDatabaseRootLeafIdleTimeout/leaf_role_with_idle_timeout
        	            	ERROR 1105 (HY000): leaf.example.com is offline: no active tunnels to root.example.com found
        	Error:      	Received unexpected error:
        	            				db_integration_test.go:365
        	Error Trace:	db_integration_test.go:332
    db_integration_test.go:332: 
```

**Comment by ibeckermayer** [comment]
Also see https://github.com/gravitational/teleport/issues/9492#issuecomment-1069441572

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/347dcec3-5488-4071-8791-01dc446021d4?project=ci-account

**Comment by smallinsky** [comment]
Should be fixed in https://github.com/gravitational/teleport/pull/18202
