### ISSUE TITLE
Can the video file be downloaded to MP4?

### ISSUE THREAD

**Issue by RyanCode** [gravitational/teleport#16357]

**Comment by webvictim** [comment]
No, session recordings are stored as a combination of text and offsets and are stitched together by a Javascript player in the browser so it isn't technically a video. If you want a video, you could always try screen recording the browser while it's playing back a session recording.

**Comment by RyanCode** [comment]
> 不，会话记录存储为文本和偏移量的组合，并由浏览器中的 Javascript 播放器拼接在一起，因此从技术上讲它不是视频。如果您想要视频，您可以随时尝试在浏览器播放会话记录时对其进行屏幕录制。

Whether it is possible for teleport to discuss converting this file into a video, the most useful one is rdp recording, the customer requests this function, is there any possibility or idea to realize it

**Comment by RyanCode** [comment]
> No, session recordings are stored as a combination of text and offsets and are stitched together by a Javascript player in the browser so it isn't technically a video. If you want a video, you could always try screen recording the browser while it's playing back a session recording.

Whether it is possible for teleport to discuss converting this file into a video, the most useful one is rdp recording, the customer requests this function, is there any possibility or idea to realize it

**Comment by webvictim** [comment]
It's unlikely that we will provide MP4 downloads for Windows session recordings any time soon.

**Comment by RyanCode** [comment]
> It's unlikely that we will provide MP4 downloads for Windows session recordings any time soon.

Maybe you can use MediaRecorder API, it can capture the stream of canvas.then call URL.createObjectURL(new Blob(video, { type: 'video/webm' })) canvert to a video.
for example
```ts
    const canvas = canvasRef.current;
    const stream = canvas.captureStream();
    const recorder = new MediaRecorder(stream, { mimeType: 'video/webm' });
    recorder.start()
    recorder.ondataavailable = function (event) {
      video.push(event.data);
    };
    setTimeout(() => {
      recorder.stop()
      const url = URL.createObjectURL(new Blob(video, { type: 'video/webm' }));
      window.open(url)
    }, 30000);
```

**Comment by RyanCode** [comment]
> It's unlikely that we will provide MP4 downloads for Windows session recordings any time soon.

RDP frame drop is a bit serious, can it be optimized?
