### ISSUE TITLE
Emit audit log entries for token creation and deletion

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#16359]
Tokens can be created by users in three ways:
- `GenerateToken` RPC (which calls the `ProvisioningService.UpsertToken` after generating some token fields) - this is the RPC used by `tctl tokens add`.
- `UpsertToken` RPC (which calls onto `ProvisioningService.UpsertToken`)
- `CreateToken` RPC (which calls onto `ProvisioningService.CreateToken`)

Currently we have a `trusted_cluster_token.create` event that is emitted when `GenerateToken` is used to create a token including the Trusted Cluster role. No other events are emitted.

Part of #15486 

Token redemption should be considered out of scope for this task.

## Solution

I suggest the deprecation of the `trusted_cluster_token.create` event, and the introduction of a `provision_token.create` event that includes a field that specifies which roles have been requested. [This was suggested, and deferred, in the original PR that introduced the `trusted_cluster_token.create` event](https://github.com/gravitational/teleport/pull/3733#discussion_r427603783). I don't believe creating distinct events for each role type makes much sense, as this will potentially generate a few events if multiple roles are included in the token.

It is imperative that this event is emitted when either of the three RPCs are used. The event must record the user that triggered the action. It probably makes sense to extract this functionality to a method that can be re-used between all three of the RPCs.

Whilst we are here, it would also make sense to introduce a `provision_token.delete` event.

## Questions

For some provision tokens, the name of the token is a sensitive value. We need to determine if we want to partially redact this, or not include the name of the token within the audit log at all.

**Comment by bl-nero** [comment]
Capturing a decision made between me and @strideynet on Slack: we'll call these events `join_token.create`, since "join token" is our official name for these.

**Comment by bl-nero** [comment]
Closing with a caveat: we deemed it's OK to close it without token deletion messages.
