### ISSUE TITLE
Provide how to access RDS DBs through Kube Agent

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#16366]
## Details
Documentation on DB Access and Kube agent lacks information on connecting to RDS databases.  Currently to enable access that requires allowing the EKS node role to have access.  That should be included so users can configure access to RDS through EKS Teleport kube agent.

### Applies To
- https://goteleport.com/docs/database-access/getting-started/
- https://goteleport.com/docs/database-access/guides/rds/
- https://goteleport.com/docs/database-access/guides/redis-aws/

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
@stevenGravy Can you please update this issue with the relevant docs pages that should be updated?

**Comment by jonatanzafar59** [comment]
@stevenGravy Do you mind explain in further details? I'm kind of stuck on the it and would like more clear guidance.

**Comment by ptgott** [comment]
This issue covers a portion of #15043

**Comment by ptgott** [comment]
Fixed in https://github.com/gravitational/teleport/pull/27899
