### ISSUE TITLE
How to setup 1 teleport portal, to access different servers not in lan but on net

### ISSUE THREAD

**Issue by noriuky** [gravitational/teleport#1636]
Hi, i have a new question.
I have 12 different VPS, in 3 different providers: digital ocean, layerstack and aruba.
all 12 have them own public ip which i use at the moment to access throught SSH with putty, or mac book with ssh joe@ip ...
I installed teleport on 1 of 12 and it work fine, but i didnt understand by manual, if is possible starting by this only teleport i installed on 1 server to login into it and see all other 11 servers and enter into these.
If is possible, can you give me a step by step guide on how to config the main and others teleports plz?
thanks

**Comment by russjones** [comment]
@noriuky Now that we support IoT mode, one thing you can do is setup a single Auth/Proxy server and use IoT nodes to connect your 12 servers to that single cluster. Does this work for you?

**Comment by zmb3** [comment]
This looks more suitable for a discussion than an issue. Feel free to start a new [discussion](https://github.com/gravitational/teleport/discussions) if you're still looking for help here.
