### ISSUE TITLE
Desktop Access does not match similar guides 

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#16397]
## Details
Desktop Access does not include the details such as those include in DB guides. 
 - `WindowsDesktop` token required
 -  Connecting to the auth server from the service
 - Installing teleport guide on a linux machine.

### Applies To
- https://goteleport.com/docs/desktop-access/getting-started/

### Category
- Improve Existing

**Comment by zmb3** [comment]
The token and connecting to the auth server are covered in `## Step 6/7. Configure Teleport`, it just doesn't appear at the beginning like other guides.

**Comment by alexfornuto** [comment]
> * `WindowsDesktop` token required

Are you referring to the `windows_desktop_service` key? If so, @zmb3 is correct.

> * Connecting to the auth server from the service
> * Installing teleport guide on a linux machine.

This is covered as a [prerequisite](https://goteleport.com/docs/desktop-access/getting-started/#prerequisites):
> An existing Teleport cluster with one of the following versions:
