### ISSUE TITLE
"><img src=x onerror=alert(1)>

### ISSUE THREAD

**Issue by arifenmahfuj** [gravitational/teleport#16432]
Expected behavior:
```
strideynet: I have redacted a suspicious link included within this issue
```

Current behavior:

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by strideynet** [comment]
I'm unsure what you are trying to report here. Please open an issue with more information if you have a genuine issue. Repeatedly opening issues on the Teleport repository containing a single suspicious link will likely result in a ban from engaging with our repository.
