### ISSUE TITLE
Improve Cloud/Enterprise Downloads page

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#16433]
## Details

1. The [Teleport Cloud Downloads](https://goteleport.com/docs/deploy-a-cluster/teleport-cloud/downloads/) page is not as user-friendly as the [Community (OSS) Download](https://goteleport.com/download/) page - consider categorising the page by Linux/MacOS/Windows (like the Community page) and showing the filenames (e.g. teleport-x.y.z.pkg) as hyperlinks.
2. The Teleport Cloud Downloads page is also relevant for Enterprise (self-hosted) but is part of the Cloud documentation - consider re-locating this.
3. For MacOS:
- Explain that there are no ARM packages available but AMD installers can be used with Rosetta.
- Clearly indicated if packages signed are signed by Apple or not.
- Reference the “Apple Signing Certificates” section on the [Security](https://goteleport.com/security/) page.
- Advice against using Homebrew for installations - e.g. The versions you get from Homebrew are based on OSS, are not signed or notarized with Teleport's signing certificates which means that certain Enterprise features won't work.

### Category
- Improve Existing

**Comment by zmb3** [comment]
@xinding33 and @mcbattirola are redesigning all of the download pages now.

This work is being tracked here: https://github.com/gravitational/cloud/issues/2027

**Comment by mcbattirola** [comment]
We are reworking https://goteleport.com/download/, I think the request is to improve https://goteleport.com/docs/deploy-a-cluster/teleport-cloud/downloads/

**Comment by philip-teleport** [comment]
Yes, this request is to improve https://goteleport.com/docs/deploy-a-cluster/teleport-cloud/downloads/. 
@ptgott asked for this issue to be created.
