### ISSUE TITLE
Honor public_addr in signup URL.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1643]
**Problem**

When adding a user like below, the signup address that Teleport returns has the hostname of the first proxy it finds: [user_command.go#L117-L135](https://github.com/gravitational/teleport/blob/master/tool/tctl/common/user_command.go#L117-L135)

```
$ tctl users add --roles=admin rjones
Signup token has been created and is valid for 3600 seconds. Share this URL with the user:
https://proxy1.example.com:3080/web/newuser/00000000000000000000000000000000

NOTE: make sure 'proxy1.example.com' is accessible!
When the user 'rjones' activates their account, they will be assigned roles [admin]
```

This is a problem for HA situation as the proxy host my not be directly accessible (it may be behind a LB).

**Proposed Solution**

If `public_addr` is set, honor it here as the public address of the proxy.

**Comment by kontsevoy** [comment]
Another proposed solution: maybe we should stop being too smart with our suggestions and simply print  URL with  `<proxyhost>` and say that _"make sure <proxyhost> points at Teleport proxy which your users can access"_
