### ISSUE TITLE
Update "Adding Nodes" documentation

### ISSUE THREAD

**Issue by rsyracuse** [gravitational/teleport#16431]
## Details
Our guides for adding a node to a cluster could use more work. This issue is created to address the following:

- Starting a teleport node as a daemon configured to be added to a cluster using a systemd unit file
- We could touch on more simplified tooling both inside and outside of the browser app(such as using `tctl nodes add` or the script suggested by the browser app) to simplify the current configuration steps.
- Where we use longer commands, we should explain more about what the command is doing, i.e`export INVITE_TOKEN=$(tctl nodes add --ttl=5m --roles=node | grep "invite token:" | grep -Eo "[0-9a-z]{32}")
)` where we are setting a variable based on the token outputted from the `tctl nodes add` command. We should also aim to identify these longer commands as a need as opposed to other more clear alternatives, replacing them where necessary.

I am including an example daemon config as part of this issue for whoever may begin this work, we just need to include the necessary configuration flags in the ExecStart field:

```[Service]
Type=simple
Restart=on-failure
EnvironmentFile=-/etc/default/teleport
ExecStart=/usr/local/bin/teleport start --pid-file=/run/teleport.pid --roles=node --token=************* --ca-pin=sha256:*********************** --auth-server=exampleserver.com
ExecReload=/bin/kill -HUP $MAINPID
PIDFile=/run/teleport.pid
LimitNOFILE=8192
```

Primary doc in question:
https://goteleport.com/docs/management/admin/adding-nodes/

### Category
- Improve Existing
- Remove Outdated

**Comment by zmb3** [comment]
In general you should use a teleport.yaml configuration file instead of adding a bunch of flags to your `teleport start` command.

Adding nodes is being completely revamped with Teleport Discover, so I think this issue is going to be deprecated by that work.

**Comment by rsyracuse** [comment]
Thanks @zmb3, that's really helpful insight. Whenever these guides get a revamp we'll focus on using the configuration file `teleport.yaml` to set configuration flags wherever applicable instead of the unit file, I shouldn't have assumed.

Pending any further feedback, we'll consider this task a lower priority for now and re-review once Teleport Discover is added.

**Comment by corkrean** [comment]
@zmb3 I see value in **not** using Teleport Discover in this documentation. I think it would be more valuable to demonstrate joining a node with a config file. 

Teleport Discover will require very little documentation (it's intuitive). Users need a lot of help with properly creating a configuration file that can be used by CICD systems to join many nodes.

**Comment by zmb3** [comment]
@ptgott do you think there's anything left to do here?

**Comment by ptgott** [comment]
Looks like we've completed this. Closing!
