### ISSUE TITLE
Typo in 'tctl lock' command on 'Delete Request' page

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#16447]
Expected behavior:

The `tctl lock` command provided on the Access Request 'Delete Request' page should run correctly.

Current behavior:

The `tctl lock` command provided on the Access Request 'Delete Request' page contains a typo - `tctl lock --access_request` should be `tctl lock --access-request` (hyphen instead of underscore)

![image](https://user-images.githubusercontent.com/95687564/190473051-271b30f8-610b-48fa-b575-4c4aee3c9a97.png)

Bug details:
- Teleport version: v10.2.1

**Comment by zmb3** [comment]
@hatched looks like you forgot to backport the fix from https://github.com/gravitational/webapps.e/pull/366

**Comment by hatched** [comment]
Backports have now been applied for v9 and v10.
