### ISSUE TITLE
Add redis/elasticache backend

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1645]
During performance testing and after additional tuning it was found that most of the reads/writes to the database are session live server. 

By the nature of the session server every session is actively tracked/updated. DynamoDB/Etcd is not a good backend for live session tracking.

I suggest to add elasticache/redis protocol support, this will bring down the amounts of reads/writes to dynamo to 20/10 per second while most load will go to transient memory storage - as live sessions are not persistent.

It will not be possible to use auth server in memory tracking as it won't work in case of auth servers.

**Comment by russjones** [comment]
We went a different route with implementing caches within Teleport to achieve the same functionality.
