### ISSUE TITLE
terraform provider documentation improvement

### ISSUE THREAD

**Issue by j-teleport** [gravitational/teleport#16463]
## Details
Side note:
https://goteleport.com/docs/reference/terraform-provider/?scope=enterprise#teleport_role
describes setup instructions for the Terraform provider,

but only the page at
https://goteleport.com/docs/management/guides/terraform-provider/#step-23-create-a-terraform-configuration
mentions that there's a Terraform software version requirement.

It'd be good if the requirement was listed in both places.

----------------------------------------------------

Also, the documentation is still for U2F at,
https://goteleport.com/docs/reference/terraform-provider/#teleport_auth_preference

But Starting on Teleport v10, WebAuthn replaces U2F.

### Category
- Improve Existing
- Remove Outdated

**Comment by ptgott** [comment]
@marcoandredinis Is there a way to provide the required Terraform version in the auto-generated "Terraform Provider Resources" page?

**Comment by marcoandredinis** [comment]
Yes
Just added https://github.com/gravitational/teleport-plugins/pull/790/commits/778820662060c8954814d70e571fe57a5254f8b7
