### ISSUE TITLE
Align and single-source Dynamo policy examples.

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/teleport#16466]
> @alexfornuto that might be a good idea for a cleanup in a subsequent PR.
> 
> In the case of Dynamo, we list the policy in both helm-deployments/aws.mdx and backends.mdx, but they don't match! 😱 (The one in aws.mdx is pretty granular and the one on backends.mdx is overly permissive)
> 

_Originally posted by @zmb3 in https://github.com/gravitational/teleport/issues/16464#issuecomment-1249507097_

The PR this spawned from turned the S3 IAM policy in our Helm doc into an include and shared it with other relevant docs. This issue is to take the same action for the DynamoDB policies in our docs.

**Comment by ptgott** [comment]
Completed when we added [this include](https://github.com/gravitational/teleport/blob/6aa1aac0b58ca31694d828cb404dc7d991a81671/docs/pages/includes/dynamodb-iam-policy.mdx).
