### ISSUE TITLE
`tsh ssh` inside a host

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1648]
## Intro

When users use `tsh ssh -A` they're requesting their certificate to be forwarded to the host. This makes sense if/when they want to use `ssh` on the remote host to jump somewhere else.

## Problem

What's interesting is that the forwarded agent is accessible by `ssh` but cannot be used by `tsh ssh` natively: while the certificate is available, tsh won't just use it - it will insist on supplying `--proxy` flag, which makes it less convenient as it could have been.

## Proposals

Consider passing the current proxy context (host:port) to a session via one of SSH_TELEPORT environment variables. Then when `tsh ssh user@host` runs, it should check if the environment variable is set and use its value instead of `--proxy` flag and, of course, using the forwarded agent instead of (missing) `~./tsh/keys`

## Notes

This should also support per-session MFA over agent connection so whenever a user uses `tsh ssh` from inside the host, they get prompted for a MFA tap on their machine.

**Comment by codingllama** [comment]
Related issue about MFA in remote hosts: https://github.com/gravitational/teleport/issues/15688.

**Comment by r0mant** [comment]
@Joerger @jakule To add to the ticket description, a couple of requirements we should keep in mind when working on the design and implementation:

- This should work with per-session MFA so when you `tsh ssh` on the bastion host, it should prompt you for a MFA tap on your machine. Can we do this over ssh-agent channel?
- As another research item we'd also want to explore whether this can be extended to Kubernetes Access as well. So you'd be able to use `kubectl` on the bastion host. `kubectl` doesn't have a concept of agent forwarding, but it does allow to specify a custom plugin/command to fetch credentials in its kubeconfig file. Can this be used to get it to fetch credentials on demand over the same tunnel / use ssh-agent as a signer?

This needs an RFD before we start implementation.

**Comment by flybyray** [comment]
A kind of workarround for this is to use `ssh-agent tsh ssh -A ...`  but it was (is?) currently not possible to use this with `tsh proxy ssh` in _ssh_config_ file. 
When using with `ssh-agent tsh ssh -A ...` the _ssh_config_ on the "jump" hosts is a little bit dedicated.

**Comment by jakule** [comment]
@r0mant I think this can be closed as "won't implement". Correct me if I'm wrong.

**Comment by jakule** [comment]
As we decided to replace proxy forwarding with Headless SSO https://github.com/gravitational/teleport/issues/21519 as it's more secure. I'm closing this issue. Related RFD: https://github.com/gravitational/teleport/blob/master/rfd/0105-headless-authentication.md

Another alternative is using jump hosts https://goteleport.com/docs/connect-your-client/tsh/#ssh-jump-host
