### ISSUE TITLE
Redesign Teleport Website Download Page

### ISSUE THREAD

**Issue by rishibarbhaya-design** [gravitational/teleport#16519]
I am redesigning the Teleport Download Page with revised Information Architecture.
Check https://www.figma.com/file/Dx5qAeVCxIlEBhIiFCdhb3/Website-Designing?node-id=174%3A1719 for designs.

The file is divided into 3 pages
1. Approved Designs: Designs approved by @xinding33 @mcbattirola and the marketing team will be displayed here. This file will also include desktop, tablet, and mobile view adapts (responsive UI)
3. Version: Design Ideas (yet to be approved) will be displayed here, refer to this for different options and review them.
4. Discarded: Screens that couldn't qualify for reviewing stage will be displayed here.

**Comment by rishibarbhaya-design** [comment]
![Image](https://user-images.githubusercontent.com/88441969/191106890-36960ba6-fc27-475e-b334-16f022a9f4e8.png)
![Image](https://user-images.githubusercontent.com/88441969/191106888-00afbd8c-ea90-439c-94c5-4a2168dc0b55.png)
![Image](https://user-images.githubusercontent.com/88441969/191106889-9d2abbbb-f176-4e52-9b40-b9c8a252c136.png)

**Comment by zmb3** [comment]
Can this be closed now?

**Comment by mcbattirola** [comment]
Yes, everything here is implemented
