### ISSUE TITLE
3-level documentation

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1652]
## Problem

The current docs use 2-level navigation, where the last level (i.e. "node" level) is based on H2/H3 tags within a single markdown document. This creates difficulties publishing guides. We've clearly outgrown 2-level navigation.

## Solution

`mkdocs` since 0.15 is capable of 3-level documentation. I have created a branch called `ev/3levels` where this is turned on for experimental purposes.

We need to roll this out. But 3 things need to happen:

1. Docs themselves need to be re-formatted
2. We need to design the new look for 3-level docs [kate]
3. New CSS/Layout/JS [@alex-kovoy]
4. Bonus points: the search field shouldn't be rounded. Nothing else in our current design is.

## Design 

Kate's work is below

**Comment by Kate288** [comment]
![treleport 3-level navigation_v2](https://user-images.githubusercontent.com/33237244/35834672-b248b674-0a8b-11e8-9453-0b7ac0be7183.png)
Here is updated version for the menu

**Comment by Kate288** [comment]
![treleport 3-level menu latest version](https://user-images.githubusercontent.com/33237244/35836091-352576de-0a93-11e8-9a91-87a5a6cc4910.png)

**Comment by alex-kovoy** [comment]
closed with #1667
