### ISSUE TITLE
`TestIntegrations/TwoClustersTunnel/node` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#16530]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/3be16660-ed72-4c9f-8e13-73e8dc0e811e?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/e1066425-dc59-4162-80b3-2d267e1c2742?project=ci-account

#### Relevant snippet

```
        	Messages:   	Failed to find 3 events on helpers.Site A after 5s
        	Test:       	TestIntegrations/TwoClustersTunnel/node
        	Error:      	Condition never satisfied
        	            				integration_test.go:1775
        	Error Trace:	integration_test.go:1950
    integration_test.go:1950: 
```

**Comment by nklaassen** [comment]
got another hit on this one https://console.cloud.google.com/cloud-build/builds/ad8c87cd-b566-42b7-99ad-92648a5a74c3?project=ci-account

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/1dfa39fd-f411-4a15-95d4-9ba72baf400b?project=ci-account

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/d16f7af6-b383-4968-ac68-2fa311158d9e?project=ci-account

**Comment by zmb3** [comment]
https://console.cloud.google.com/cloud-build/builds/781a0e73-1823-4f9c-a2b5-dc80ab203fc4;step=0?project=ci-account

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/979031ee-660c-4aa7-9e62-9f66051c6ebb?project=ci-account

**Comment by GavinFrazar** [comment]
https://console.cloud.google.com/cloud-build/builds/798149d3-e9b0-4e04-82b3-ac91ea70bb49?project=ci-account

https://console.cloud.google.com/cloud-build/builds/ddc8ffdc-4bf9-4797-9289-5165e83f7045?project=ci-account

On a branch/v10 backport: https://github.com/gravitational/teleport/pull/18618

**Comment by ibeckermayer** [comment]
https://github.com/gravitational/teleport/actions/runs/3904564810/jobs/6670513093

**Comment by nklaassen** [comment]
I've had multiple hits on v10 today https://github.com/gravitational/teleport/actions/runs/4534349161/jobs/7993624665?pr=23649

**Comment by tobiaszheller** [comment]
fixed by https://github.com/gravitational/teleport/pull/26233
