### ISSUE TITLE
tsh starts the browser with the login flow many times in parallel

### ISSUE THREAD

**Issue by fungiboletus** [gravitational/teleport#16534]
Expected behavior:
Running tsh on an expired session many times in parallel should not open a browser many times and corrupt the tsh state.

Current behavior:
When I start VSCode with the Kubernetes plugin on an expired session, tsh starts my web browser 3 times in parallel. This cause potential race conditions. See #16494.

Bug details:
- Teleport version `10.2.2`
- Recreation steps Start tsh many times in parallel on an expired session.
- Debug logs N/A

**Comment by ICHx** [comment]
I have the same issue, from pycharm as well as, vscode when opening any yaml file.

**Comment by fungiboletus** [comment]
<img width="1388" alt="image" src="https://github.com/gravitational/teleport/assets/45740/106b10a7-773c-4742-a3c1-965faa512b4a">

A new record of parallel login flows in my web browser 😄

**Comment by webvictim** [comment]
Fixed by https://github.com/gravitational/teleport/pull/26102
