### ISSUE TITLE
Bad certificate error connecting with `tsh proxy db` while using `require_session_mfa: true`.

### ISSUE THREAD

**Issue by danielatjumo** [gravitational/teleport#16552]
Expected behavior:
`require_session_mfa: true` allows us to use session MFA with `tsh proxy db` to connect to a RDS aurora cluster.

Current behavior:
`require_session_mfa: true` allows us to connect to a RDS aurora cluster using MFA but it disconnects shortly.

Bug details:
- Teleport version 
v10.2.0 in cluster
v10.2.0 to v10.2.2 client
- Recreation steps
We set `require_session_mfa: true` and we are able to connect but it disconnects after a few seconds with bad certificate error in debug logs
We set `require_session_mfa: false` allows us to use `tsh proxy db` to connect to a RDS aurora cluster without MFA but its stable connection.
- Debug logs

From tsh client:
ERROR REPORT:
Original Error: trace.aggregate readfrom tcp 127.0.0.1:60939-&gt;127.0.0.1:60966: remote error: tls: bad certificate
Stack Trace:
	/private/tmp/teleport-20220916-10028-11awu4w/teleport-10.2.2/lib/srv/alpnproxy/local_proxy.go:194 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).handleDownstreamConnection
	/private/tmp/teleport-20220916-10028-11awu4w/teleport-10.2.2/lib/srv/alpnproxy/local_proxy.go:132 github.com/gravitational/teleport/lib/srv/alpnproxy.(*LocalProxy).Start.func1
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/asm_arm64.s:1172 runtime.goexit
User Message: readfrom tcp 127.0.0.1:60939-&gt;127.0.0.1:60966: remote error: tls: bad certificate] alpnproxy/local_proxy.go:136

**Comment by smallinsky** [comment]
@danielatjumo 
What client are you using to connect to the db local proxy ?

**Comment by danielatjumo** [comment]
@smallinsky 
dbeaver or datagrip GUIs are being used, some users I believe use mysql workbench. 
users also having this issue with redshift.

we also tried without --tunnel but couldnt get it to work properly either.

But we have disabled session mfa for db access for now. We will wait on https://github.com/gravitational/teleport/issues/12704

thanks
