### ISSUE TITLE
missing PEM encoded block

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1655]
When using `tsh` 2.5-rc against 2.4 servers that's what user gets. I suspect this is a result of switching to "protocol multiplexing" on one of the proxy ports. We have two possibilities:

1. Making this work. Possible? Expensive?
2. Giving user a proper error message and updating the docs and the upgrade procedure (less preferable, of course).

**Comment by klizhentas** [comment]
we don't support forward compatibility - (new tsh clients don't work with older teleport servers). We should explicitly tell that.

**Comment by klizhentas** [comment]
old tsh client will work fine with new 2.5.0 teleport server.

**Comment by kontsevoy** [comment]
So it's the 2nd option then, otherwise we'll be getting hit on support (documentation is the last place people will look). Can we say _"your .tsh version is newer than the server"_? Anything more informative than "missing PEM encoded block" will help a lot

**Comment by klizhentas** [comment]
yes, server can return a version and client can compare. if version of the client on the middle version is greater than server we should return an error:

e.g. 

tsh 2.5.0 and teleport 2.4.x is not ok
tsh 2.5.1 and teleport 2.5.0 is ok
tsh 2.4.0 and teleport 2.5.0 is ok

**Comment by klizhentas** [comment]
I have explained this in a more detail in #1661

**Comment by kontsevoy** [comment]
@klizhentas  this can be closed now right?
