### ISSUE TITLE
Unify `aws/terraform/ha-autoscale-cluster` and `teleport-cluster-terraform`

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#16553]
We have 2 terraform code bases doing the exact same thing in two sightly different fashions:

* terraform module https://github.com/gravitational/teleport-cluster-terraform
* terraform project https://github.com/gravitational/teleport/tree/master/examples/aws/terraform/ha-autoscale-cluster

The module seem to be unmaintained and a several fixes/features were added to the `ha-autoscale-cluster` project (likely because it's the one referenced in the docs) and not ported. It seems the module was meant to replace the project but migration was never done, and we seemingly have users relying on both.

Most of the code is duplicated and this looks like a dangerous technical debt (e.g. the module is not compatible with the Grafana version in our new AMIs).

I suggest we:
- bring back the module to feature parity
- use the module in `ha-autoscale-cluster` (deduplicate logic)
- use [`moved` blocks](https://www.terraform.io/language/modules/develop/refactoring#splitting-one-module-into-multiple) to provide an upgrade path for previous `ha-autoscale-cluster` users
- bring the module in the main repo to reduce multi-repo coupling (modules can be sourced from subdirectories by using the double slash syntax)

**Comment by sidick** [comment]
I'd suggest maybe not having it in a separate repository, as if you have it in it's own then it can be published on the public Terraform registry which makes it easier to integrate

**Comment by webvictim** [comment]
@pschisa suggests that a customer tried to use the `teleport-cluster-terraform` module and found some bugs, so it seems like it might now be broken.

**Comment by pschisa** [comment]
https://github.com/gravitational/teleport-cluster-terraform/pull/11

**Comment by hugoShaka** [comment]
CLosing as teleport-cluster-terraform has been archived
