### ISSUE TITLE
version --short command

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1656]
Sometimes, for scripting purposes, people want to parse the version of teleport. In such cases `gitref` portion of it gets in the way. It would be nice to have `--short` flag which would simply report the version, i.e.:

```bash
# Default:
$ teleport version
Teleport v2.4.0-rc.4 git:v2.4.0-rc.4-0-gf31f6ff4-dirty

# Suggested:
$ teleport version --short
2.4.0-rc.4
```

As requested/discussed in #1573

## Notes

* Lets make this work for all CLI tools: `tsh`, `teleport` and `tctl`

**Comment by nikatjef** [comment]
This request is more closely related to #970 than it is to #1573

**Comment by zmb3** [comment]
Closing as duplicate of #9601 (even though this one has been around longer)
