### ISSUE TITLE
Allow session recordings inherit labels from resources like nodes/db

### ISSUE THREAD

**Issue by j-teleport** [gravitational/teleport#16576]
**What would you like Teleport to do?**
Now session recordings only can be filtered by session.participants,
Please allow session recordings inherit labels from resources like nodes/db, and the filter can be more flexible.

**What problem does this solve?**
Hard to find session recordings what resource it was from.

**If a workaround exists, please include it.**
NA

**Comment by zmb3** [comment]
Duplicate of #13482?

**Comment by jingsun-teleport** [comment]
> Duplicate of #13482?

Looks like yes, please close it if need. Thanks,
