### ISSUE TITLE
Our documentation needs any example credentials to be OBVIOUSLY FAKE

### ISSUE THREAD

**Issue by wadells** [gravitational/teleport#16597]
## Details
We regularly get vulnerability submissions for content like:

* https://github.com/gravitational/teleport/blame/65e01165124c97740ecf1f1fd8ddbeacc95c6b57/docs/pages/deploy-a-cluster/deployments/ibm.mdx#L153-L155

We should update these credentials to be clearly bogus.  For example, prefix them with "fake" or "replaceme", or "yourkey".

We may also include this standard in our docs guide to help future contributors make good example choices.

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
Variables like this are configured in `config.json`, so we will update the demo vars there to be obviously fake.
