### ISSUE TITLE
Validate roles serverside when a local user is created/updated

### ISSUE THREAD

**Issue by wadells** [gravitational/teleport#16614]
## Expected Behavior

If I attempt to create a user with a non-existant role, server side validation will fail and I'll get a helpful error message from the api.

## Current Behavior
Currently roles are validated on the clientside:

https://github.com/gravitational/teleport/blob/2657be4c1d0b6426d1b8711c27adb1df5b3b7350/tool/tctl/common/user_command.go#L298-L307

https://github.com/gravitational/webapps/blob/f0abaf5b9e5a94f6f4212262dd3dbe6167423330/packages/teleport/src/Users/UserAddEdit/UserAddEdit.tsx#L108

However with e.g. a postman replay or a poorly behaved api client, this validation is circumvented and a user can be updated with invalid roles.  For the `tctl` validation, it is almost certainly much slow to do validation clientside, as it involves O(roles) api calls (sometimes across the network).

## Repro:

<details><summary>intentionally invalid <code>tctl update user</code></summary>

```
walt@work:~/git/teleport$ git diff
diff --git a/tool/tctl/common/user_command.go b/tool/tctl/common/user_command.go
index 7435d36ab..bc6bc903c 100644
--- a/tool/tctl/common/user_command.go
+++ b/tool/tctl/common/user_command.go
@@ -297,11 +297,6 @@ func (u *UserCommand) Update(ctx context.Context, client auth.ClientI) error {
        updateMessages := make(map[string][]string)
        if len(u.allowedRoles) > 0 {
                roles := flattenSlice(u.allowedRoles)
-               for _, role := range roles {
-                       if _, err := client.GetRole(ctx, role); err != nil {
-                               return trace.Wrap(err)
-                       }
-               }
                user.SetRoles(roles)
                updateMessages["roles"] = roles
        }
walt@work:~/git/teleport$ make build/tctl                    
GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -tags " " -o build/tctl  -ldflags '-w -s' -trimpath ./tool/tctl

walt@work:~/git/teleport$ ./build/tctl version
Teleport v11.0.0-dev git:v9.3.2-0-gb3597d12a go1.18.3
walt@work:~/git/teleport$ ./build/tctl users update bugz --set-roles bogus 
User bugz has been updated:
        New roles: bogus

walt@work:~/git/teleport$ tctl get user/bugz
kind: user
metadata:
  id: 1663799559789235252
  name: bugz
spec:
  created_by:
    time: "2022-09-21T22:12:29.395092058Z"
    user:
      name: walt@goteleport.com
  expires: "0001-01-01T00:00:00Z"
  roles:
  - bogus
  status:
    is_locked: false
    lock_expires: "0001-01-01T00:00:00Z"
    locked_time: "0001-01-01T00:00:00Z"
    recovery_attempt_lock_expires: "0001-01-01T00:00:00Z"
version: v2
```

compared to the unmodified behavior:

```
walt@work:~/git/teleport$ tctl users add bugz --roles=bogus                                                                                                                                   
ERROR: role bogus is not found 
```

</details>

When a local user is created or updated with an invalid role, that user is locked out of Teleport.

```
walt@work:~/git/teleport$ tsh login --proxy wadells.teleport.sh --user bugz
Enter password for Teleport user bugz:
Tap any security key
ERROR: role bogus is not found
```

This lockout capability isn't a concern, as anyone with update on users could already lock users out via editing the `expires` field (or maybe the `status: is_locked` field too).

The clientside validations prevent anyone not doing intentionally stupid things from hitting this behavior.

## See Also
The SSO verision of this behavior: https://github.com/gravitational/teleport/issues/16160

**Comment by zmb3** [comment]
@EdwardDowling I think you just implemented this, right?

**Comment by EdwardDowling** [comment]
Yes, [here](https://github.com/gravitational/teleport/pull/22065) is the PR adding the check to upsertUser
