### ISSUE TITLE
Automatically lock deleted access requests

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#16626]
What would you like Teleport to do?

Automatically create a lock for an access request during the deletion of said access request.

What problem does this solve?

Deleting the access request doesn't revoke access. While there is a warning that states as much when an access request is deleted, it would be a better UX if we could just automatically lock the access request to delete and revoke access in one step.

If a workaround exists, please include it.

Manually create the lock for the access request as the warning suggests.

**Comment by nklaassen** [comment]
@rosstimothy mentioned there was discussion on this elsewhere where we decided the warning was good enough
