### ISSUE TITLE
Listing nodes with tsh doesn't work with "local" cluster

### ISSUE THREAD

**Issue by iuriaranda** [gravitational/teleport#1662]
**What happened**:

I'm logged into a cluster that has multiple trusted clusters connected. The Web UI works perfectly, I can see all the clusters in the drop-down menu, I can ssh into all the servers, etc.

With tsh I can list the clusters with `tsh clusters`, and I can ssh into all the servers on all clusters. But if I try to list the nodes from the local cluster it fails:
```
$ tsh ls
WARN             syslog not available. reverting to stderr utils/cli.go:88
ERRO             failed connecting to node . unable to connect to auth server client/client.go:168
WARN [CLIENT:CA] connection problem: failed connect to the auth servers, using local cache state/cachingaccesspoint.go:543
Node Name Node ID Address Labels
--------- ------- ------- ------
```

Although it works if I list the nodes on a trusted cluster:
```
$ tsh ls --cluster=example
WARN             syslog not available. reverting to stderr utils/cli.go:88
Node Name   Node ID                              Address           Labels
----------- ------------------------------------ ----------------- -----------
api.example 9a43bc8c-96fd-4b5a-b16d-87706857c834 10.108.21.32:3022 arch=x86_64
web.example e06e1fa2-9e00-4ad4-98fe-49554c83c584 10.108.0.214:3022 arch=x86_64
```

A part from the log that I see from `tsh`, the proxy server also logs this:
```
ERRO unable to connect to auth server regular/sshserver.go:953
```

And there's nothing relevant on the audit logs.

Additionally (and probably related), when I ssh into a server through `tsh` I can access the terminal but it's constantly outputting log entries like:
```
ERRO             "\nERROR REPORT:\nOriginal Error: *trace.ConnectionProblemError ssh: subsystem request failed\nStack Trace:\n\t/gopath/src/github.com/gravitational/teleport/lib/client/client.go:334 github.com/gravitational/teleport/lib/client.(*ProxyClient).ConnectToNode\n\t/gopath/src/github.com/gravitational/teleport/lib/client/client.go:165 github.com/gravitational/teleport/lib/client.(*ProxyClient).ConnectToSite.func1\n\t/opt/go/src/net/http/transport.go:852 net/http.(*Transport).dial\n\t/opt/go/src/net/http/transport.go:1008 net/http.(*Transport).dialConn\n\t/opt/go/src/net/http/transport.go:908 net/http.(*Transport).getConn.func4\n\t/opt/go/src/runtime/asm_amd64.s:2198 runtime.goexit\nUser Message: failed connecting to node . unable to connect to auth server\n" client/session.go:313
```
But this doesn't happen if I ssh into the same node through the Web UI, nor if I ssh into a node on a trusted cluster through `tsh`.

**What you expected to happen**:

- I expected to see the nodes from the local cluster with `tsh ls`.
- I didn't expect to see any log entries inside an ssh session through `tsh`.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`): `v2.4.0`
- Tsh version (use `tsh version`): `v2.4.0`
- OS (e.g. from /etc/os-release): both teleport `auth` and `proxy` are running on a Docker container (Debian - Jessie) on ECS, nodes are running on Ubuntu (16.04.3) and I'm running `tsh` locally on Ubuntu (16.04.3) as well.

As mentioned, `auth` and `proxy` are running separated on Docker containers, and both are accessible through independent load balancers.

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by ACBullen** [comment]
Bumping onto this as I have encountered something similar when setting up our own system. What appears to have happened at least in our case is that when the child cluster restarts, whatever cached certificates the user has are not appropriately trusted so an empty list of nodes is returned.
(relevant line returned from running `tsh ls --cluster=<name> -d`)
```
WARN [CLIENT:CA] Connection problem (Get https://teleport.cluster.local/v2/namespaces/default/nodes?skip_validation=true: x509: certificate signed by unknown authority) failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:862
```

If you nuke your `.tsh` directory and log back in to the main cluster, this issue goes away. It might be worth returning an error telling the client to clear their .tsh directory if nothing appears, or promoting this to an error that stops the client rather than failing silently and returning an empty list.

**Comment by asgoel** [comment]
Bump, any resolution on this one?

**Comment by jalil** [comment]
Any resolution on this one?

**Comment by klizhentas** [comment]
@jalil do you have the same issue? Can you paste the logs?

**Comment by russjones** [comment]
Can't reproduce this, if you are still running into this problem, please create another ticket.
