### ISSUE TITLE
tsh no longer recognizes --browser option

### ISSUE THREAD

**Issue by Enomised** [gravitational/teleport#16632]
Expected behavior:

The documentation states that `tsh --browser=none` will not launch a browser, but instead require the user to pass the link to a browser in their own way.

Current behavior:

`tsh: error: unknown long flag '--browser'`

Bug details:
- Teleport version:   Teleport v9.3.20 git:v9.3.20-0-g48fbd9434 go1.17.11

Speaking of the `--browser` flag, my reading of #3611 tells me that the intent was to allow the browser to be chosen by the user, not merely disabled, but I'm not sure if that functionality ever was entered.

Is this a documentation bug, meaning `--browser` isn't supposed to work?

I would actually like if the argument to `--browser` could be a path to a script, that could take the URL and pass it to a browser using a user-specified mechanism.  But I suspect this functionality does not exist, and would constitute a feature request.

Currently `--browser` is documented to work, but does not work.

**Comment by zmb3** [comment]
`tsh login --browser=none` works.

`--browser` is a flag to the login subcommand, not to all of `tsh`.

**Comment by Enomised** [comment]
Thanks for correcting my understanding.

Is this design intentional, though?  In my use of Teleport, I never use `tsh login` because it's performed automatically for me when I `tsh ssh`, if I am not currently logged in.  In such a case, it's useful if `tsh ssh` will pass the login flags to the login process, if it finds a need for a login session.

If this is working the way you intentionally designed it and want it to work, then I am satisfied with this result.

**Comment by zmb3** [comment]
It is working the way we intended for it to work, but your feedback about auto re-login on `tsh ssh` is valid and we're happy to entertain the feature request.
