### ISSUE TITLE
Web UI: Allow specifying the role used for resource access requests

### ISSUE THREAD

**Issue by GERey** [gravitational/teleport#16647]
What would you like Teleport to do?

Currently in the webUI Teleport adds all roles relevant to the resource. This is a different flow from the command line/ tsh where you can specify exactly the role you want to apply to the resource in order to define access. We would like Teleport to implement the ability to specify which roles you want to apply to the resource to the webUI as well.

What problem does this solve?

This would solve the problem of having different flows across webUI and tsh, bringing them closer to parity. This would also allow our webUI users more flexibility when requesting resources as right now there exists a possibility that two wildly conflicting roles get assigned that don't give the user the permission that they were expecting. 

If a workaround exists, please include it.

**Comment by xinding33** [comment]
Related to #17920.
