### ISSUE TITLE
Terminal Session File Transfer (Revised)

### ISSUE THREAD

**Issue by rishibarbhaya-design** [gravitational/teleport#16645]
Design File Transfer for Terminal Session. 
Inclusions

**1. Uploading Files (Under Review)**
- Default
- In Progress
- Error
- Success

**2. Downloading Files (In Progress)**
- Default
- In Progress
- Error
- Success

Check Designs here:
https://www.figma.com/file/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?node-id=2595%3A63215
Ticket #16645 | Terminal Session File Transfer

**Comment by rishibarbhaya-design** [comment]
Downloading Files


![Image](https://user-images.githubusercontent.com/88441969/193664718-31a509f6-55e9-4339-bb25-aa12659ed7b7.png)
![Image](https://user-images.githubusercontent.com/88441969/193664720-68618e88-7ad5-4662-8e5c-f0809ce26f32.png)
![Image](https://user-images.githubusercontent.com/88441969/193664719-4246a4fa-00ea-42ef-9150-78f1028dfe83.png)

**Comment by zmb3** [comment]
Closing this as the feature has been shipped.
