### ISSUE TITLE
I went back an old cluster and my TLS was broken, ACME cert expired

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#16656]
Expected behavior:
ACME Certs should renew

Current behavior:
I was unable / had to click warning to access my 9.x cluster as it looked like certs had expired. 

<img width="851" alt="image" src="https://user-images.githubusercontent.com/559288/191859697-469a1f12-cd99-45dc-896e-da36a4d6386f.png">

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by benarent** [comment]
I've tried this https://github.com/gravitational/teleport/discussions/10039 to resolve me issues.

**Comment by benarent** [comment]
I now have an account+key, but it's not obtaining my new certificates. 
```log 
root@ip-172-31-13-216:/var/lib/teleport/acme# ls
acme_account+key
```

**Comment by zmb3** [comment]
@benarent is this still an issue? If so, what do you need from us in order to get it closed out? There's no logs, configuration files, or any other info in the issue that would make it actionable for an engineer, so I don't see this going anywhere unless we can better understand the problem.

**Comment by benarent** [comment]
I think it was also due to let's encrypt bug.. we can close this for now
