### ISSUE TITLE
simplified docs entry point for end user usage

### ISSUE THREAD

**Issue by aberoham** [gravitational/teleport#1666]
**What happened**:

Anonymous user asked: "Is there a tsh installation method for MacOS? I'm getting confused with the documentation coupling server and client"

**What you expected to happen**:

Documentation for end-users w/o admin focus to be more clear, or pointer to pre-existing packages such as `brew install teleport`

**How to reproduce it (as minimally and precisely as possible)**:

Pretend you are not acclimated to Teleport internals, or consume enough alcohol to be 1.5x beyond your personal Balmer Peak, then try to install tsh on a fresh MacBook.

**Comment by kontsevoy** [comment]
Yep, openssh usually comes in two packages: `ssh-client` and `ssh-server`
