### ISSUE TITLE
Support for X-Forwarded-For header on Proxy

### ISSUE THREAD

**Issue by TJuberg** [gravitational/teleport#1668]
**What happened**:
External client connected via https proxy which adds X-Forwarded-For header to pass along actual IP of client to Teleport.

**What you expected to happen**:
Teleport session list to display proxied client IP as provided by X-Forwarded-For in addition to actual connected IP

While we do have logs from the proxy, it would be nice if Teleport had built in support to display where the external connection originated. Preferably it would display both IP's, or in the event of wanting to show only the X-Forwarded-For address, you should be allowed to specify which sources to trust X-Forwarded-For header from.

**How to reproduce it (as minimally and precisely as possible)**:
Connect to Teleport proxy via http/https proxy.

**Environment**:
- Teleport version (use `teleport version`): 2.4.0
- Tsh version (use `tsh version`): n/a
- OS (e.g. from /etc/os-release): n/a

**Browser environment**

- Browser Version (for UI-related issues): n/a
- Install tools: n/a
- Others: n/a

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by lierdakil** [comment]
:+1:

**Comment by zmb3** [comment]
@probakowski FYI in case this is related to any of the work you're doing

**Comment by ArunNadda** [comment]
One of the customers is using zammad enterprise, which is ruby on rails. Zammad uses proxy (customer is using apache) to frontend the app (https://docs.zammad.org/en/latest/getting-started/configure-webserver.html).
They are using AzureAD SSO (https://admin-docs.zammad.org/en/latest/settings/security/third-party/microsoft.html) to login to zammad app. SSO logins work fine if teleport is not in picture but fails with `csrf` related errors if application is registered to teleport.

As per https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080/33, SSO login works if `X-Forwarded-Proto` is set to `https` on proxy. 

To get `zammad` SSO login working with teleport, we should be able to set `X-Forwarded-*` header. 


I assume recent versions of grafana have the similar issues with CSRF protection.

**Comment by jacobb84** [comment]
I'd love to see this functionality. We have our instance of Teleport running with the proxy listener running in separate mode so that we can put the web interface behind the AWS application load balancer (and therefore the web application firewall). I don't currently see any way in this setup to get the originating IP from Teleport logs without support for X-Forwarded-For

**Comment by webvictim** [comment]
As per the update on #27120, I believe this is now supported in Teleport v13.2.0+ when you add this to your Teleport proxy service configs:

```yaml
proxy_service:
  trust_x_forwarded_for: true
```
