### ISSUE TITLE
sftp events are unkown

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#16692]
Expected behavior:
As we add sftp support, we don't have an appropriate / matching audit event type. 

Current behavior:
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/559288/192046026-315f0dc2-58ba-44da-9ae1-9dc23ab6743b.png">

```
{
  "action": 3,
  "addr.local": "127.0.0.1:3022",
  "addr.remote": "79.184.139.38:49995",
  "cluster_name": "teleport-10-ent.asteroid.earth",
  "code": "TS003I",
  "ei": 0,
  "event": "sftp",
  "login": "ubuntu",
  "namespace": "default",
  "path": "/home/ubuntu/teleport-ent-v10.2.0-linux-amd64-bin.tar.gz",
  "server_hostname": "ip-172-31-14-126",
  "server_id": "0322fe38-7293-4fda-b67d-86e54cc80c22",
  "sid": "",
  "time": "2022-09-23T15:12:00.746050527Z",
  "uid": "b82b6b04-b639-4781-806b-b03ac63bf871",
  "user": "gzdunek-testuser",
  "working_directory": "/home/ubuntu"
}
```

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
What version of Teleport are you running, Ben?

**Comment by benarent** [comment]
Upgraded from 10.2.0 to 10.2.2 and it works 

<img width="645" alt="image" src="https://user-images.githubusercontent.com/559288/192054750-94214fd5-6559-445a-9ac2-eff17a2797ef.png">
