### ISSUE TITLE
[Docs] Desktop Access LDAPS CA

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/teleport#16745]
## Details

Re: [Getting Started With Desktop Access](https://goteleport.com/docs/desktop-access/getting-started/?scope=enterprise#step-57-export-your-ldap-ca-certificate)

In [step 5](https://goteleport.com/docs/desktop-access/getting-started/?scope=enterprise#step-57-export-your-ldap-ca-certificate) we export an existing key from the Certification Authority tool. In my testing on Windows 2019 I wasn't able to get any LDAPS (only LDAP) connection until I had created a "Local Computer" CA with KDC Authentication using the Microsoft Management Console (`mmc`) tool.

I assume most customers will already have an appropriate certificate solution for LDAPS, but I'm not sure if they will get the right one exporting from Certification Authority versus MMC.
 
### Category
- Improve Existing

**Comment by zmb3** [comment]
Sounds like you didn't install AD CS, which would have set up an enterprise CA and LDAPS for you. In any case, this is is also automated with the new discover flow.
