### ISSUE TITLE
Option to merge kubeconfig file generated using `tsh kube login...`

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#16744]
#### What would you like Teleport to do?

- Add option to merge `kubeconfig` file for subset of k8s clusters. This should also include option to provide multiple cluster names in single `tsh kube login k8s-cluster1, k8s-cluster2 .... k8s-clusterx` command.
- Add option to have separate `kubeconfig` file for subset of k8s clusters, this would help isolate a group of k8s clusters with separate `kubeconfig` files. like say prod k8s clusters and dev k8s clusters have separate `kubeconfig` file generated using command like `tsh kube login k8s-prod01, k8s-prod02... --out1=prod-kubeconfig k8s-Dev01,k8s-Dev02... --out2=Dev-kubeconfig`
- both above options should be available with `tbot`, `tctl auth sign....` and `tsh kube login` commands.

#### What problem does this solve?
- provide option to have a single kubeconfig file for multiple clusters.
- Also help CI/CD tools to use MachineID to generate kubeconfig file for multiple clusters, where workflow requires access to multiple k8s clusters.

#### If a workaround exists, please include it.
- Currently, i think options `destinations.directory/destinations.kubernetes_cluster` (in machineID) can be used to generate a separate `kubeconfig` file for each k8s cluster.

**Comment by tigrato** [comment]
`tsh kube login` already merges into the specified kubeconfig.  The only thing it does not support is to login into multiple clusters at the same time because `tsh kube login` changes the current context.


```
EXPORT=prod_kube_config tsh kube login kube1
EXPORT=prod_kube_config tsh kube login kube2

EXPORT=stg_kube_config tsh kube login kube3
EXPORT=stg_kube_config tsh kube login kube4
```

It will generate 2 files, each one with 2 clusters.

**Comment by zmb3** [comment]
@tigrato I think you mean:

```
KUBECONFIG=prod_kube_config tsh kube login kube1
KUBECONFIG=prod_kube_config tsh kube login kube2
```

😄

**Comment by tigrato** [comment]
> @tigrato I think you mean:
> 
> ```
> KUBECONFIG=prod_kube_config tsh kube login kube1
> KUBECONFIG=prod_kube_config tsh kube login kube2
> ```
> 
> 😄

i really need coffee before i start work
