### ISSUE TITLE
Some notes on documentation

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1676]
## Description

Here are some notes on documentation parts that could be improved:

* [ ]  https://gravitational.com/teleport/docs/2.4/architecture/#user-accounts

Note states that external identities are only supported with Enterprise. This is no longer true as OSS supports github.

* [ ]  https://gravitational.com/teleport/docs/2.4/architecture/#teleport-cluster

Teleport cluster diagram shows web and tsh - this could be misleading as people can think tsh is a requirement. this diagram could be improved showing that ssh clients can be used too as it's a standard SSH.

* [ ]  https://gravitational.com/teleport/docs/2.4/architecture/#ssh-proxy

Typo in the diagram - "forwards" vs forward and the same comment about tsh and ssh as above.

*  [ ] https://gravitational.com/teleport/docs/2.3/enterprise/#rbac docs on port forwarding are missing

* [ ] https://gravitational.com/teleport/docs/2.4/admin-guide/#trusted-clusters

Nowhere in the documentation of trusted clusters there is a mention of how to map roles for enterprise.

**Comment by kontsevoy** [comment]
The items 1, 2 and 3 are fixed. The rest has separate tickets.
