### ISSUE TITLE
Document our new Desktop Access setup workflow

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#16777]
## Details
You can now copy scripts from the Web UI to set up Desktop Access. Let's document this new automatic workflow in the Desktop Access getting started guide. 

If possible, we could frame the existing instructions—which are long and involved—as a description of what happens behind the scenes of the setup scripts. However, we will need to make the existing instructions visually subordinate to the new workflow instructions to avoid putting off users. A massive `Details` box with the existing instructions would probably be overkill, but maybe there's another way to preserve them while making them more obscure?

**Comment by scottpgallagher** [comment]
As part of this I'd also call out that when you start from the beginning this is using a bare bones Windows server; if your using a server that already has AD & CA installed then skip those commands.
