### ISSUE TITLE
Add a 'Add Desktop' button in the UI

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#16804]
What would you like Teleport to do?
In the UI currently under Desktop Access when Desktops are connected we have a 'View Documentation' button. This should be changed to reflect that we have a process to add Desktops like we do with other protocols in Teleport.

What problem does this solve?
Instead of taking the user to the documentation it will take them to the setup screen to walk them through adding Desktops.

If a workaround exists, please include it.
Yes, if you click on your username and go to Manage Access you can access it from there.

**Comment by zmb3** [comment]
cc @xinding - adding `needs-product-decision`. Let's make sure this aligns with the desire to separate access manager and access provider interfaces.

**Comment by scottpgallagher** [comment]
Implemented... Closing
