### ISSUE TITLE
Document signal handling procedure

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1680]
## Description

This is a basis for documentation, leaving this up to @kontsevoy to shape it up to a usable state:

## Signal handling for downtime-less upgrades

Parent teleport process is now capable of forking
the child process and passing listeners file descriptors
to the child.

Parent process then can gracefully shutdown
by tracking the amount of current connections and
closing listeners once the amount goes to 0.

## Signal handling details

Here are the signals handled:

`USR1` signal is helpful for debugging and troubleshooting running teleport process.
It prints out information about memory, gorotuines and other diagnostic info 
without stopping the process.

`USR2` signal will cause the parent to fork
a child process and pass listener file descriptors to it.
Child process will close unused file descriptors
and will bind to the used ones.
At this moment two processes - the parent
and the forked child process will be serving requests.
After looking at the traffic and the log files,
administrator can either shut down the parent process
or the child process if the child process is not functioning
as expected.

`QUIT` signal will trigger graceful process shutdown.
Auth, node and proxy processes will wait until the amount
of active connections goes down to 0 and will exit after that.

`TERM`, `INT` signals will cause immediate non-graceful
shutdown.

`HUP` signal combines `USR2` and `QUIT` signals in a convenient
way: parent process will fork a child process and
self-initate graceful shutdown. This is a more convenient
than USR2/QUIT sequence, but less agile and robust
as if the connection to the parent process drops, but
the new process exits with error, administrators
can lock themselves out of the environment.

### Rollback procedure with USR2

With USR2 if you are not happy with performance of the child process, replace the binary back and terminate the child process. The first parent process is perfectly functional and handles things well

### Rollback procedure with HUP

While the original connection is running, you can safely bring back the old binary, stop the child process and start the new process again.

## Backend considerations

Boltdb backend has to be phased out,
as it does not support read/writes by two concurrent
processes. Users should switch to `dir` back-end for local file handling
or `etcd` or `dynamo` backends for HA mode operation.

**Comment by kontsevoy** [comment]
@klizhentas this is obsolete a little, isn't it? I've looked at the code and `USR2` seems to be redundant now, since `HUP` works really well. Anyway, please review #f478d18fdc1fbb833e696568bcc40e740e16981a
