### ISSUE TITLE
Document Host Certificate Support for Machine ID

### ISSUE THREAD

**Issue by rsyracuse** [gravitational/teleport#16822]
https://goteleport.com/docs/server-access/guides/openssh/
https://goteleport.com/docs/machine-id/introduction/
https://goteleport.com/docs/machine-id/reference/configuration/

## Details
We need to create supporting documentation for host certificate support on Machine ID for OpenSSH. This will require upgrading configuration reference documentation and creating a separate doc for how host certificates work on Machine ID

**Comment by ptgott** [comment]
Addressed via https://github.com/gravitational/teleport/pull/16989
