### ISSUE TITLE
Discover: Web UI should be able to query registered Kube agent

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#16823]
In Teleport Discover flow for Servers, we updated the node joining script to support "resource labels" that the wizard uses to query the node and understand whether it's successfully joined before allowing the user to proceed to next step:

https://github.com/gravitational/teleport/pull/15114

We need to implement the same kind of functionality for Kubernetes agents and include the resource ID label in the Helm install command that we generate and show to the user.

**Comment by tigrato** [comment]
When the wizard calls `/v1/webapi/token` to generate the joining token for the `kube-agent`, Teleport already returns the `resource-id` label.
```
{
  "id": "...",
  "expiry": "2022-09-29T13:03:50.595774Z",
  "method": "token",
  "suggestedLabels": [
    {
      "name": "teleport.internal/resource-id",
      "value": "27d9c198-bef1-4645-8006-0e847c89f9ed"
    }
  ]
}
```

The only thing missing is for the wizard to include this change - helm command is generated by the wizard:

```diff
cat << EOF > prod-cluster-values.yaml
roles: kube
authToken: token
proxyAddr: tele.teleport.local:3080
kubeClusterName: test
teleportVersionOverride: 11.0.0-dev
+labels:
+    teleport.internal/resource-id: 27d9c198-bef1-4645-8006-0e847c89f9ed
EOF
 
helm install teleport-agent teleport/teleport-kube-agent -f prod-cluster-values.yaml --create-namespace --namespace test
```

Did I miss anything @r0mant ?

**Comment by r0mant** [comment]
@tigrato Great, sounds like just a small frontend change then - @kimlisa FYI, we will need to update the value.yaml snippet we should in web UI to include the labels and then should be all set.

**Comment by r0mant** [comment]
@kimlisa Sounds like this is already supported - can you confirm that you were able to add labels and query kube agent by labels? Then we can close this.

**Comment by kimlisa** [comment]
i tested this out and it works, thanks!
