### ISSUE TITLE
[Discover] Database Flows Day 1

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#16858]
Implement the various database flow for day 1 discover

#### Databases
AWS RDS
 - [x] postgres
 - [x] mysql/mariaDB
 - [ ] sql server
 - [ ] redshift

Self Hosted
 - [x] postgres
 - [x] mysql/mariaDB
 - [ ] mongo
 - [ ] sql server
 - [ ] redis

#### Resolve TODO's before closing this issue
- [ ] Check language:
   - https://github.com/gravitational/webapps/pull/1335#discussion_r1016733321
- [ ] If have time, refactor according to https://github.com/gravitational/webapps/pull/1335#discussion_r1017541446

**Comment by r0mant** [comment]
We're tracking the rest of the work in our quarterly goals and individual tickets.
