### ISSUE TITLE
Helm cluster deployment: provide option to split `auth` and `proxy` pods

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#16871]
#### What would you like Teleport to do?
Currently teleport helm chart deploys cluster with both `auth` and `proxy` in single pod.  This request is to provide option in helm chart deployment to split `auth` and `proxy` to separate pods.

#### What problem does this solve?
This will help keeping `auth` pod is private network with only `proxy` pod can access, whereas proxy pod can be open to outside network.

#### If a workaround exists, please include it.
This can be done manually, by modifying helmchart. But this will make upgrades hard.

**Comment by webvictim** [comment]
It's worth noting that the original `teleport` Helm chart supported this, but it became difficult to manage and maintain separate configurations for each pod. The `teleport-cluster` Helm chart was designed specifically as an all-in-one replacement with the intent of removing toggles and options to make it considerably simpler to use.

**Comment by zmb3** [comment]
This is now supported.
