### ISSUE TITLE
Database access tsh db connect with local proxy hijacks the ^C  SIGINT signal and terminates the background db local proxy

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#16874]
### Details: 
When the `tsh db connect` command is called it spawns in the background teleport local proxy that forwards the traffic to the teleport proxy. For the cancellation of local proxy tsh command currently the global context is used where it can be canceled by `SIGINT` signal send from database subcommand like `psql` or `mycli`. In case of background Teleport local proxy the `SIGINIT` is hijacked by background local proxy handler in the result local proxy running in the background is terminated after receiving `SIGINIT` . 
 

### Expected behavior:
The correct behavior can be observed where the teleport local proxy is run in a separate process intended from `psql` or `mycli` DB clients: 
1) Staring local proxy manually: 
```
tsh proxy db postgres01 --tunnel
Started authenticated tunnel for the PostgreSQL database "postgres01" in cluster "example.cloud.gravitational.io" on 127.0.0.1:62245.

Use the following command to connect to the database:
  $  /usr/local/opt/libpq/bin/psql postgres://marek@localhost:62245/postgres
```

2) Connecting through a local proxy  and spawning `SIGINIT` signal by `CTRL+C`
```
/usr/local/opt/libpq/bin/psql postgres://marek@localhost:62245/postgres
psql (14.4, server 13.4)
Type "help" for help.

postgres=> (SIGINT  triggered by CTRL+C)
postgres=>
postgres=>
postgres=>
postgres=> \d
       List of relations
 Schema | Name  | Type  | Owner
--------+-------+-------+-------
 public | leads | table | marek
(1 row)
```
`SIGINIT` signal doesn't affect database connection  

### Current behavior:

When the local proxy is spawned in the background by `tsh db connect --db-user=marek --db-name=postgres postgres01` command it hijacks the SIGINT handler and terminates running local proxy: 
```
tsh db connect --db-user=marek --db-name=postgres postgres01
psql (14.4, server 13.4)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_128_GCM_SHA256, bits: 128, compression: off)
Type "help" for help.


postgres=> \d
       List of relations
 Schema | Name  | Type  | Owner
--------+-------+-------+-------
 public | leads | table | marek
(1 row)

postgres=> (SIGINT  triggered by CTRL+C)
postgres=> \d
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
!?>
```

**Comment by zmb3** [comment]
Good to close this one?

**Comment by smallinsky** [comment]
It already fixed on master but I'm sill waiting for backports approval. I will close this issue after merging backports.

**Comment by smallinsky** [comment]
Fixed by https://github.com/gravitational/teleport/pull/16875
