### ISSUE TITLE
Improve AWS access to better develop AWS SDKs 

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#16895]
**What would you like Teleport to do?**

The admin would like to have direct access to AWS using Teleport and not the CLI proxy. 

**What problem does this solve?**

The admin has stated that using Teleport's AWS feature takes away direct AWS access and instead exposes a CLI proxy, this makes it very difficult to develop using AWS SDK's. 

They envision a proxy returning a temporary STS session credential and app logout could revoke them if possible. 

For now, it can be sidestepped somewhat by allowing the AWS role to assume itself and then just call ```tsh aws sts assume-role```

**If a workaround exists, please include it.** 

No workaround exists at this moment.

**Comment by zmb3** [comment]
Is this covered by https://github.com/gravitational/teleport/issues/16326?
