### ISSUE TITLE
backend.mdx typo on line 442

### ISSUE THREAD

**Issue by WilliamLoy** [gravitational/teleport#16920]
## Applies To
[
]https://github.com/gravitational/teleport/blob/806a568ada7c640a64eb60f718e7d56be34049ad/docs/pages/reference/backends.mdx?plain=1
## Details
Describe the documentation improvements you wish to see.
stores appears twice in the sentence "By default, Teleport stores stores audit events with an AWS TTL of 1 year"

**Comment by zmb3** [comment]
PRs welcome! 🤗
