### ISSUE TITLE
When the network environment is not particularly stable, the rdp session experience is not very good

### ISSUE THREAD

**Issue by RyanCode** [gravitational/teleport#16936]
I noticed that when my network environment is not particularly good or the server cup power consumption is high, the drawing of the rdp session is not very friendly.Is it possible to further optimize the drawing of rdp? For example, using the drawing scheme in GDI.https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegdi/52635737-d144-4f47-9c88-b48ceaf3efb4

**Comment by zmb3** [comment]
Hi @RyanCode. As I've mentioned in other issues that you've filed, we are tracking the performance of RDP in #9707 and are aware of alternative codecs that will perform better.

Creating additional issues is not going to speed this up, it only creates more items for the team to sort through. Thank you for your patience.
