### ISSUE TITLE
ssh dynamic port forwarding

### ISSUE THREAD

**Issue by steven-aerts** [gravitational/teleport#1693]
The -D flag of ssh can sometimes be very handy.
It allows you to dynamically setup network connections through the ssh tunnel.
For example to browse as if you are on the connected node, or tunnel jmx connections.

Hope you do not mind that I already have a patch ready for this.

**Comment by kontsevoy** [comment]
@steven-aerts if `-D` is fully compatible with OpenSSH, this is more than welcome addition! We'll review the PR shortly, thanks.

**Comment by steven-aerts** [comment]
For a SOCKS5 proxy it should be fully compatible with the -D behaviour of ssh.
For a SOCKS4 proxy which is also supported by OpenSSH I print an error that it is not yet implemented.  I doubt that a lot of people are still using a SOCKS4 proxy.

**Comment by kontsevoy** [comment]
@klizhentas move this out of 2.6?

**Comment by klizhentas** [comment]
We promised Steven to get it going as a part of 2.6 release, I would try to push this, to avoid long waits if possible.

**Comment by RO-29** [comment]
Is there any plan to support dynamic port forwarding, 

I really use socks5 proxy a lot and my current company has enforced tsh so missing out a lot on not able to use -D flag with it.

Thanks

**Comment by steven-aerts** [comment]
Hi Rohit,

I did not have time to apply the review comments of PR  #1694 
When you build a tsh with this PR, you should be able to use it against the servers of your client.  As this patch only changes the `tsh` client and does not impact anything on the server side.

Good luck,

   Steven

**Comment by klizhentas** [comment]
@steven-aerts  Given the age of this commit we will probably take over this PR and apply our code review comments if you don't mind.

**Comment by steven-aerts** [comment]
Hi Rohit,

I did not have time to apply the review comments of PR  #1694 
When you build a tsh with this PR, you should be able to use it against the servers of your client.  As this patch only changes the `tsh` client and does not impact anything on the server side.

Good luck,

   Steven
