### ISSUE TITLE
Elasticsearch docs

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#16963]
With Teleport 10.3 we now support (as a preview) Elasticsearch for db access. We need to have it documented.

Notes:
1. Elasticsearch with [PKI auth](https://www.elastic.co/guide/en/elasticsearch/reference/current/pki-realm.html) available is needed. The feature is available in both 7.x and 8.x versions, but requires a [premium license](https://www.elastic.co/subscriptions#:~:text=IP%20filtering-,LDAP%2C%20PKI3%2C%20Active%20Directory%20authentication,-Elasticsearch%20Token%20Service). [30-day trial info](https://www.elastic.co/guide/en/elasticsearch/reference/current/start-trial.html).
2. I used [Elasticsearch with Docker](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) for local dev.
3. Get certs for Elasticsearch configuration:
``` 
$ tctl auth sign --format=elasticsearch --host=ELASTICSEARCH_HOST --out=elastic --ttl=<desired ttl>h
Database credentials have been written to elastic.key, elastic.crt, elastic.cas.

To enable mutual TLS on your Elasticsearch server, add the following to your elasticsearch.yml:

xpack.security.http.ssl:
  certificate_authorities: /path/to/elastic.cas
  certificate: /path/to/elastic.crt
  key: /path/to/elastic.key
  enabled: true
  client_authentication: required
  verification_mode: certificate

xpack.security.authc.realms.pki.pki1:
  order: 1
  enabled: true
  certificate_authorities: /path/to/elastic.cas

For more information on configuring security settings in Elasticsearch, see:
https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
```
4. Copy the generated certs somewhere Elasticsearch can access, e.g. `/usr/share/elasticsearch/config`.
5. Follow the instructions from `tctl` and update `elasticsearch.yml` as instructed. By default, some Elasticsearch installations (in particular Docker one) will have a set `xpack.security.http.ssl.keystore.path` setting to some value, e.g. `certs/http.p12`. This must be removed because it conflicts with `xpack.security.http.ssl.certificate` setting. Similarly `xpack.security.authc.realms.pki.pki1.order` may need changing to other value if there are other PKI realms enabled.
6. If not already done, set up Elasticsearch `role_mapping`. This can be done in variety of ways; here is an example of mapping user `teleport_user` to `superuser` (obv. bad idea for prod): 
```
$ curl --insecure  -u elastic:PASS -X POST "https://localhost:9200/_security/role_mapping/mapping1?pretty" -H 'Content-Type: application/json' -d'
{
  "roles": [ "superuser"],
  "enabled": true,
  "rules": {
    "field" : { "username" : "teleport_user" }
  },
  "metadata" : {
    "version" : 1
  }
}
'
```
7. Update Teleport config. For static config, add a section like the below. Update as needed, especially uri:
```
db_service:
  enabled: true
  resources:
  - labels:
      "*": "*"
  databases:
  - name: myelastic
    protocol: elasticsearch
    uri: ELASTICSEARCH_HOST:9200
    static_labels:
      env: dev
```
7. After restarts the db should be accessible. For clients, we support (somewhat niche) `elasticsearch-sql-cli`, REST API clients (like curl) and JDBC/ODBC clients (common GUI DB clients) with proxy: `tsh proxy db myelastic --tunnel --db-user=bob`. Given the certs the REST API clients can connect to Teleport and access Elasticsearch; JDBC/ODBC clients require certs in a different format, which we don't provide out of the box.
8. Requests should be visible in Teleport audit log.
9. Alternative configuration: it is not necessary for Elasticsearch to use Teleport-provided certs for securing its REST API. Teleport needs to accept the certificate in use, though, either through proper chain of trust or by specifying the certificate in configuration section; for example for Docker-generated `http_ca.crt`:
```
  - name: myelastic
    protocol: elasticsearch
    uri: ELASTICSEARCH_HOST:9200
    static_labels:
      env: dev
    tls:
      ca_cert_file: /path/to/elastic/cert/http_ca.crt
```

Let me know if anything is unclear or more info is needed.

**Comment by alexfornuto** [comment]
@Tener and I walked through this and were unable to get a working example for me. He's going to run through it again, update as needed, then I'll take another pass at it. Moving it around in the docs queue accordingly.

**Comment by greedy52** [comment]
As part of the v11 release testing, I was testing out elasticsearch (7.17.6) and was able to get it working following this guide. 

On the server side, I think overall it's very not very difficult as most instructions are provided in `tctl auth sign`. I did run into a few docker issues (like giving cert files proper permissions and mounting them in the right place) but that's it.

On the client side, besides `elasticsearch-sql-cli` and `curl`, I've also tried this GUI tool [elasticvue](https://elasticvue.com/) in `--tunnel` mode and it works great too
<img width="713" alt="Screen Shot 2022-10-11 at 2 52 35 PM" src="https://user-images.githubusercontent.com/12417665/195175767-03a6b24c-b1f3-4900-861d-4a4e90cbb313.png">

**Comment by GavinFrazar** [comment]
Not sure if this is being tracked elsewhere, but we should document the new audit event for elastisearch requests somewhere. We have an audit event reference here: https://goteleport.com/docs/ver/11.0/reference/audit/

**Comment by Tener** [comment]
> Not sure if this is being tracked elsewhere, but we should document the new audit event for elastisearch requests somewhere. We have an audit event reference here: https://goteleport.com/docs/ver/11.0/reference/audit/

Thanks for the link; I don't recall seeing it before. There are quite a few missing ones from https://github.com/gravitational/teleport/blob/master/lib/events/api.go though. I wonder if we could automatically generate this reference based on code docs and tests/examples in webapps repo?

**Comment by GavinFrazar** [comment]
If we could do that it'd be great, although I wouldn't where to start to get that working.

This reference page is outdated in other ways too, for instance there is no mention of app access sessions... I might just open an issue to update this reference

**Comment by GavinFrazar** [comment]
issue already exists: https://github.com/gravitational/teleport/issues/10350

**Comment by ptgott** [comment]
I have a [draft PR](https://github.com/gravitational/teleport/pull/13615) to add a Make target that generates the audit event reference automatically, but it relies on certain assumptions about the source, and we'd need a separate linter to ensure that the source is organized according to those assumptions.

**Comment by Tener** [comment]
> I have a [draft PR](https://github.com/gravitational/teleport/pull/13615) to add a Make target that generates the audit event reference automatically, but it relies on certain assumptions about the source, and we'd need a separate linter to ensure that the source is organized according to those assumptions.

Given that we want to merge the repos soon, would it make sense to augment your tool with information from the JS tests? We should have all event types covered there, so it should be fine to use as a base of reference. This would give us event identifiers that we could look up in the Go source code, loosening the restrictions on code structure.

**Comment by ptgott** [comment]
@Tener Is that [this file](https://github.com/gravitational/webapps/blob/8f2d35d6393788463181e36fb791adf23d4f60d6/packages/teleport/src/Audit/fixtures/index.ts)? That sounds promising—do we have a way to ensure that all new event types get added to `events`?

**Comment by GavinFrazar** [comment]
There is at least one event that is not in the JS tests: `AppSessionRequest` - we don't display this event in the web ui. There may be others. This is the only one I'm aware of.

**Comment by Tener** [comment]
> @Tener Is that [this file](https://github.com/gravitational/webapps/blob/8f2d35d6393788463181e36fb791adf23d4f60d6/packages/teleport/src/Audit/fixtures/index.ts)? That sounds promising—do we have a way to ensure that all new event types get added to `events`?

Yup, this one. I don't think we have a way to enforce coverage, but I'd expect the gaps to be sparse; if anything, this should be a good starting point.

> There is at least one event that is not in the JS tests: `AppSessionRequest` - we don't display this event in the web ui. There may be others. This is the only one I'm aware of.

It doesn't look special. Why and how is it filtered out?

**Comment by GavinFrazar** [comment]
> It doesn't look special. Why and how is it filtered out?

It's filtered out because otherwise the request logs for some applications spam up the audit log excessively.

This is one place we filter it, there may be other places as well:
https://github.com/gravitational/teleport/blob/fe1dac1a905b73e9baf00cb6e79749f25378493a/lib/events/emitter.go#L499-L503

Now that I look at that, we also don't have "print" or "desktop.recording" events in index.ts. I don't know if those events can be viewed with `tsh play`, but "app.session.request" does show up when you play back a session chunk with tsh.
