### ISSUE TITLE
Add support to output Ansible-compatible inventory (server list) to tsh

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1696]
## Introduction

It would be nice to have `tsh` produce output which can be directly fed into `ansible`. 

## Solution

We've got a pretty good PR from the awesome Teleport user @halfa here: #1456 While we can't accept the PR as-is (read comments there) we still want to do it, building on @hala's excellent work.

Going to close that PR but keep a reference for it here.

**Comment by chuckyz** [comment]
Hello I'm wondering there been any progress on including this anywhere?  I've recently installed 2.7.3 and was about to write something of my own before running across this, and seeing it several versions behind has me somewhat concerned, would this be too difficult to implement into a current version?

**Comment by halfa** [comment]
@chuckyz the patch is trivially ported to 2.6 and 2.7 branches. I maintain a patched branch in my repo, on the [2.7/tsh-ansible branch](https://github.com/halfa/teleport/tree/branch/2.7/tsh-ansible). You only need to compile teleport from it to get the patched binaries.

**Comment by kontsevoy** [comment]
@chuckyz once you see this ticket assigned to a milestone, you'll see the Teleport version where it will be scheduled for.

**Comment by stevenGravy** [comment]
Examples of getting information in a format that works with Ansible. https://goteleport.com/docs/server-access/guides/ansible/#step-23-configure-ansible
