### ISSUE TITLE
Create a new server option similar to SSH

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#16978]
**What would you like Teleport to do?**

The customer is requesting the following: In Teleport Enterprise, create a new server option similar to SSH and auto-join that makes a script, instead of a one-liner generate a cloud-init user data YAML file similar to https://gist.github.com/derekbekoe/0ea6fd6cd31e5c3aef21150c4f7de429 would download and install teleport and have it dial back in with a join token with a configurable lifetime.

**What problem does this solve?**

This way the customer could hand a client a cloud-init yaml and have them provision pentest cloud resources.

**If a workaround exists, please include it.**

N/A

**Comment by zmb3** [comment]
Not planned at this time.
