### ISSUE TITLE
Add more `readRaw*` implementations

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#16999]
Add `readRaw*` implementations for the relevant TDP messages and add them to the `case` statement in `readRaw()`
https://github.com/gravitational/teleport/blob/81623c6a5c46b0e1e5e71b0ebb2020f35761cd34/lib/srv/desktop/tdp/proto.go#L97-L114

`readRaw()` is used to properly proxy messages from the w_d_s to the client (via websocket, [here](https://github.com/gravitational/teleport/blob/81623c6a5c46b0e1e5e71b0ebb2020f35761cd34/lib/web/desktop.go#L335)), meaning that we only really need these implementations for TDP messages sent from server to client. At the time of this writing, that includes

- [ ] Shared Directory Acknowledge
- [ ] Shared Directory Info Request
- [ ] Shared Directory Create Request
- [ ] Shared Directory Delete Request
- [ ] Shared Directory Read Request
- [ ] Shared Directory Write Request
- [ ] Shared Directory Move Request
- [ ] Shared Directory List Request
- [ ] clipboard data

See [this diff](https://github.com/gravitational/teleport/pull/16864/files/79992fb3f7aee459f88d41b4e86d982908b727e0..81623c6a5c46b0e1e5e71b0ebb2020f35761cd34#diff-98a4bee57beb7f007614e4810d2cf8413bddf48484c8aad6dd0756a218797c36L417-L424) for a potentially helpful function to add back.

**Comment by zmb3** [comment]
Deprecated by #20127
