### ISSUE TITLE
Unanswered U2F MFA prompt quickly causes system memory exhaustion

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#17012]
Expected behavior:
If I get an MFA prompt and forget/afk leaving it unaddressed, nothing bad should happen.

Current behavior:
My mac exhausts all memory and starts paging GB to disk after minutes, eventually locking up my computer completely.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/16846283/193897030-ab1961ce-2f17-495f-b5df-7355e8cbe8fe.png">
This is from system activity monitor. That fourth column is "ports" and it grows very quickly. If I leave `tsh login` password prompt without typing my password, it sits at about 49. If I type my password but don't tap my yubikey, it grows to 20,000 ports after less than a minute.

Bug details:
- Teleport version
v11-dev (sha1: 188beb23cad031bcc356be317b2a2a260fd036b2 )
built without libfido2, so this is using U2F. I tested the same steps using libfido2 support and there is no issue.

- Recreation steps
1. run`tsh login`
2. type your password
3. don't tap your yubikey.

**Comment by GavinFrazar** [comment]
As @codingllama pointed out, we use libfido2 in prod builds now, so this isn't as serious an issue now. I'm not sure how far back we switched to libfido2 though.

**Comment by codingllama** [comment]
@GavinFrazar I don't think this will see work anytime soon, so I'll close it.
