### ISSUE TITLE
Build arm binaries on CentOS 7

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#17014]
For Teleport 10 we migrated our amd64 binaries to build on CentOS 7 to maintain lower glibc requirement:

https://github.com/gravitational/teleport/pull/14062

arm builds still use Ubuntu buildbox though:

https://github.com/gravitational/teleport/blob/master/build.assets/Dockerfile-arm
https://github.com/gravitational/teleport/blob/master/build.assets/Dockerfile-arm-fips

Customers are asking for arm binaries to support older distros too so we need to update our arm assets to be built on CentOS 7 as well.

arm binaries do not support advanced session recording and BPF based network restrictions so we don't need to include those in the build.

**Comment by zmb3** [comment]
@r0mant this is a duplicate of https://github.com/gravitational/teleport/issues/16356
