### ISSUE TITLE
Add support for "hidden" label namespaces

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#17041]
Add support for "hidden" label namespaces.

Labels with "hidden" namespaces would not be visible in the UI but can be utilized for RBAC.

**Comment by r0mant** [comment]
@EdwardDowling Let's introduce a `teleport.hidden/` label namespace that, unlike `teleport.internal/`, will be specifically for users to define their labels they don't want to show anywhere in the UI/CLI.

Use changes in this PR as a base: https://github.com/gravitational/teleport/pull/18638.

**Comment by r0mant** [comment]
@EdwardDowling Please include docs that mention this hidden namespace with your implementation PR. Check with @ptgott to figure out where to put it in the docs.

**Comment by ptgott** [comment]
@r0mant @EdwardDowling How central do you think this will be to users' RBAC/resource querying workflows? It this will be a core part of managing labels, we could add another step to our [Labels](https://github.com/gravitational/teleport/blob/fcdde329556d88477903f90e4fd6defb7d3a57bd/docs/pages/management/admin/labels.mdx) guide about hidden labels. An `Admonition` in Step 2 would be another place we could put this information if it's more of a minor feature.

**Comment by r0mant** [comment]
Yes, adding it to Labels page should be good.
