### ISSUE TITLE
[v.10.0] Add missing databases under the supported database section

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#17092]
## Applies To
 /docs/pages/database-access/introduction.mdx

## Details
Describe the documentation improvements you wish to see.
In the introduction add missing databases we support under `Database Access currently supports the following databases:`.

Missing databases: Snowflake and AWS DynamoDB

**Comment by yjperez** [comment]
Also missing AWS Redshift

**Comment by zmb3** [comment]
Dynamo DB isn't actually supported yet, is it?
