### ISSUE TITLE
List active Desktops sessions under "Active Sessions"

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#17126]
What would you like Teleport to do?

List active Desktops sessions under "Active Sessions".

What problem does this solve?

Currently, you can only see active for Kubernetes and SSH sessions.

If a workaround exists, please include it.

N/A

**Comment by ibeckermayer** [comment]
@zmb3 closed by https://github.com/gravitational/webapps/pull/1315?

**Comment by zmb3** [comment]
@ibeckermayer not quite yet, requires https://github.com/gravitational/teleport/pull/17945 as well.
