### ISSUE TITLE
Restricted sessions modules causes problems in 5.14 Kernel

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#17133]
Expected behavior:

Enhanced logging will work even if restricted session modules aren't available. If restricted sessions isn't required it shouldn't attempt to load those modules on that machine.

Current behavior:

A 5.14 kernel SUSE fips will fail to run when Teleport attempts to load modules for restricted sessions.

Bug details:
- Teleport version: 10.2.2
- Recreation steps

  Install a FIPS enabled Suse 15 vm that uses 5.14 as the default Kernel. Attempt to enable enhanced logging.  This will not occur in a non-FIPS env. 

- Debug logs

```
[  192.420549][ T5037] BUG: unable to handle page fault for address: ffffffffc13f7bcc
[  192.423075][ T5037] #PF: supervisor instruction fetch in kernel mode
[  192.424999][ T5037] #PF: error_code(0x0010) - not-present page
[  192.426955][ T5037] PGD 1d815067 P4D 1d815067 PUD 1d817067 PMD 0 
[  192.513528][ T5037] Oops: 0010 [#1] PREEMPT SMP NOPTI
[  192.515296][ T5037] CPU: 0 PID: 5037 Comm: teleport Kdump: loaded Tainted: G           OE  X    5.14.21-150400.24.18-default #1 SLE15-SP4 695ab7a8fc20f5ddb345280570966cd1eb06d469
```

**Comment by jakule** [comment]
A few reproduction tips:
1. I was only able to reproduce this issue on AWS EC2 SLES instance
2. Here is a guide on how to enable FIPS https://www.suse.com/support/kb/doc/?id=000019432 Additionally, you also need to install `fips-check` tool. Otherwise, the system won't boot in FIPS mode after a restart.
