### ISSUE TITLE
Discovery service initialization should not depend on time.Sleep

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#17146]
Discovery service right now relies on time.Sleep when creating a node watcher:

https://github.com/gravitational/teleport/blob/branch/v10/lib/service/discovery.go#L69-L71

```go
for !nodeWatcher.IsInitialized() {
    time.Sleep(1 * time.Second)
}
```

This is not reliable or robust and in general we should avoid using time.Sleep directly as much as possible.

Instead, the service should periodically check whether the watcher has been initialized using a ticker (or ideally without any tickers at all and by having ability to block on a channel until it gets initialized or receive some event, see comments below).

@tigrato refactored this as a part of AKS auto-discovery PR:

https://github.com/gravitational/teleport/pull/16633/files#diff-7a030693b277c072225ebea353dbdf312158a3c04c4ee09da1befbef2180e7b3R304-R315

Also, ideally it should be done in a background goroutine to make sure it does not block the service startup. It can/should block the task that invokes SSM installer, but not the service startup.

The fix should go in branch/10 as the v11/master fix is included in https://github.com/gravitational/teleport/pull/16633.

**Comment by zmb3** [comment]
Doesn't the watcher emit some type of event when it's ready?

**Comment by r0mant** [comment]
I don't think it does currently but yeah, a better way would be to have a some sort of "ready channel" that would for example get closed when the watcher gets initialized, instead of a boolean "is initialized" flag. Then the caller would be able to block on that channel until the watcher is initialized without polling. cc @lxea @tigrato
