### ISSUE TITLE
tctl auth export --type=tls

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1716]
## Problem

We need to document the following command:

```
$tctl auth export --type=tls
````

and the meaning of `/var/lib/teleport/ca.cert`

## Questions

In what context a user may want to do this? Currently this is only required when trying to access the auth server  API. But the API itself is not documented.

**Comment by kontsevoy** [comment]
Correct, I get that. But how would a user _use_ this command for? By default nodes are perfectly fine joining a cluster with a self-signed cert without exporting it (which is a usability choice we've made). So... when would a user _want_ to use `$ tctl auth export --type=tls`?

**Comment by klizhentas** [comment]
to fix the potential MITM attack in production, this is an equivalent of self signed certs for web UI

**Comment by kontsevoy** [comment]
@klizhentas TBDiscussed, you're

**Comment by kontsevoy** [comment]
Fixed in 6a8167cac26df77ec0
