### ISSUE TITLE
`tsh ssh -A` does not work for remote nodes on trusted clusters

### ISSUE THREAD

**Issue by mdwn** [gravitational/teleport#17183]
Expected behavior:
```
➜  teleport-clusters tsh ssh -A root@68604a2cc539
root@68604a2cc539:~# ssh -T git@github.com
Hi mdwn! You've successfully authenticated, but GitHub does not provide shell access.
```

Current behavior:

```
➜  teleport-clusters tsh ssh --cluster=11test.trustedteleport -A visitor@f8b6d8c318db

$ ssh git@github.com
Warning: Permanently added the ECDSA host key for IP address '140.82.113.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
```

Bug details:
- Teleport version 11.0.0-alpha2
- Recreation steps
  - Set up a root Teleport cluster with a trusted leaf Teleport cluster associated with it.
  - While logged into the root Teleport cluster, use `tsh ssh -A` to SSH into one of nodes on the leaf Teleport cluster.
  - Try running `ssh -T git@github.com` or `echo $SSH_AUTH_SOCK`. Neither will display as expected.
- Debug logs

**Comment by r0mant** [comment]
@mdwn Can you try and reproduce with Teleport versions v10 and v9 to understand whether this is a regression or not?

**Comment by mdwn** [comment]
So this was also a user error -- I didn't have the `forward_agent` permission set for my user, so this is actually fine. Closing this now.
