### ISSUE TITLE
`TestHostCertVerification/Alt_cluster_rejected_by_default` flakiness

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#17198]
## Failure

Introduced in https://github.com/gravitational/teleport/pull/15178

Repro: 
```
$ go test -run TestHostCertVerification/Alt_cluster_rejected_by_default ./lib/client -failfast -count=10 
```

#### Relevant snippet

```
    keyagent_test.go:378:
        	Error Trace:	/Users/zmb/teleport/lib/client/keyagent_test.go:378
        	Error:      	An error is expected but got nil.
        	Test:       	TestHostCertVerification/Alt_cluster_rejected_by_default
--- FAIL: TestHostCertVerification (0.12s)
```

**Comment by zmb3** [comment]
All I've been able to figure out so far is that when the test fails, the `sshutils.KeysEqual(key, keys[i])` check passes.

**Comment by ibeckermayer** [comment]
I got this same error again here:

https://console.cloud.google.com/cloud-build/builds/4258756d-4b9e-46f9-ae3d-4b3a62cc9b7f?project=ci-account

**Comment by zmb3** [comment]
@ibeckermayer the build you linked started on: Oct 6, 2022, 11:14:44 AM

The fix was merged to master on October 10.
