### ISSUE TITLE
OpenSSH server compatibility issues

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#17197]
Expected behavior:
OpenSSH servers can be accessed via teleport using tsh, the Teleport WebUI, or OpenSSH

Current behavior:

| client                            | sshd version      | working | server error |
| ----------------------|-----------------| --------|-------------|
| tsh 11.0.0-alpha.2        | OpenSSH_7.4p1 | ❌         | `unsupported public key algorithm: [rsa-sha2-256-cert-v01@openssh.com]` |
| tsh 10.0.0                      | OpenSSH_7.4p1 | ❌         | `unsupported public key algorithm: [rsa-sha2-256-cert-v01@openssh.com]` |
| Web UI 11.0.0-alpha.2 | OpenSSH_7.4p1 | ❌         | `unsupported public key algorithm: [rsa-sha2-256-cert-v01@openssh.com]` |
| Web UI 10.0.0              | OpenSSH_7.4p1 | ❌         | `unsupported public key algorithm: [rsa-sha2-256-cert-v01@openssh.com]` |
| ssh OpenSSH_8.6p1   | OpenSSH_7.4p1 | ✅         |
| tsh 11.0.0-alpha.2        | OpenSSH_8.9p1 | ✅         |
| Web UI 11.0.0-alpha.2 | OpenSSH_8.9p1 | ✅         |
| ssh OpenSSH_8.6p1   | OpenSSH_8.9p1 | ❌         | `no matching host key type found. Their offer: ssh-rsa-cert-v01@openssh.com` |

Same behaviour on local and leaf cluster.

**Comment by jakule** [comment]
`sshd` compatibility should be fixed by https://github.com/gravitational/teleport/pull/18181 We're still working on the client part.
