### ISSUE TITLE
Tables get a horizontal scroll bar on Safari

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#17227]
I'm seeing unnecessary scroll bars on table pages in Safari (screenshot taken with full screen on MacBook Pro (16-inch, 2021))

![image](https://user-images.githubusercontent.com/13578537/194920118-089abc1c-688e-4f60-9a54-71dfd4031614.png)

**Comment by zmb3** [comment]
This was introduced in gravitational/webassets@52c71e0c587647aa07a91599f1b9204d577de271.

This corresponds to gravitational/webapps@db006cbb5e0ff98660c183b4e7c8ba3769f6dfb1.

cc @ryanclark
