### ISSUE TITLE
(Low Priority) Teleport Product Design System

### ISSUE THREAD

**Issue by rishibarbhaya-design** [gravitational/teleport#17235]
Redesigning the Design System with all the recent additions and iterations for the existing components.

**Comment by rishibarbhaya-design** [comment]
Design System Components Checklist 
(redesigning for the current color scheme)

- [ ] Colors
- [ ] Typeface
- [ ] Buttons
- [ ] Dropdowns

**Comment by rishibarbhaya-design** [comment]
Buttons Variants



![Image](https://user-images.githubusercontent.com/88441969/195204200-d51fe8e2-ed9f-474b-92d5-2c3021afbc5d.png)

**Comment by rishibarbhaya-design** [comment]
Colors Set


![Image](https://user-images.githubusercontent.com/88441969/195207488-47f99731-d783-4be8-8dcd-ebfc15b2d0af.png)

**Comment by roraback** [comment]
I think the color palette is very pleasing and that the colors coordinate well with one another. My biggest question on color is about the philosophy that underlies it: what guides our choices of color? For example:
* When should people use colors from the base, secondary, utility and gradients categories? 
* Is there an underlying logic as to how we're using each? For example: which should be used for foreground content vs. background content? Among the light neutrals, when should we be using shades of white vs. Athens vs. Geyser?
* How are we using color to signal interactivity (or a lack thereof)?

Other underlying items we should consider/codify for our system's conceptual framework:
- [ ] Shadow - where/when is this used? Is it providing a sense of elevation, dimensionality, something else?
- [ ] Motion - where/when/how do we use motion to draw users' eyes to important details and/or interactivity?
- [ ] Elevation - how are foreground and background (and different gradations of those) represented in our design system? (Color/light? Shadow?)
- [ ] Shape - Rounded/sharp/geometric/organic: how are we using shape in our system and how does it relate to our brand and to interactivity of elements (if at all)?
- [ ] Typography - We currently have 3 typefaces that we use: Lato, Ubuntu, and Ubuntu Mono. When is each used? How do our heading styles interact with our page designs?
- [ ] Interaction States - do we support distinct default/hover/active/focus/disabled states across all elements? Do we collapse two or more of those states?

Answers to at least some of the above are implied by some of the choices made already, but I think it would be helpful to write them down so we can ensure components are consistent with one another and that the underlying logic is consistent across all components.

I'm happy to hop on a call to brainstorm about any/all of these, and we can break up the work of documenting them between us. Feel free to schedule time with me if you would like to discuss!

**Comment by roraback** [comment]
Broke this out into numerous draft issues around design guidance; closing this issue, as it is too broad and is more akin to what Jira might call an Epic.
