### ISSUE TITLE
Add support for Cloud HSM on Google Cloud

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#17230]
Add support for Cloud HSM on Google Cloud

* https://goteleport.com/docs/deploy-a-cluster/teleport-enterprise/hsm/
* https://cloud.google.com/kms/docs/hsm

**Comment by nklaassen** [comment]
this has been implemented and backported to v11 here https://github.com/gravitational/teleport/pull/18835. Docs are live here https://goteleport.com/docs/deploy-a-cluster/teleport-enterprise/gcp-kms/?scope=enterprise
