### ISSUE TITLE
wtmp updates broken on el8/el9

### ISSUE THREAD

**Issue by jdconti** [gravitational/teleport#17243]
**Expected behavior:**

As per the previous issue https://github.com/gravitational/teleport/issues/3987 teleport should be properly writing to:
utmp -- current logins (working)
wtmp -- login history (not working)
btmp -- bad logins (not currently implemented but would be useful to see those in `lastb`)

`wtmp` updates fail on RHEL 8 & 9 today because `wtmp` is in `/var/log` and not `/var/run`, it appears this broke after https://github.com/gravitational/teleport/pull/10460.

If at all possible, can we please create the utmp/wtmp/btmp entries with hostname instead of just IP addresses?  Thanks!

**Current behavior:**

Teleport attempts to update `/var/run/wtmp` (which doesn't exist) which results in no `wtmp` updates.  This can be validated by symlink, auditd, or strace.

Bug details:
- Teleport version: v10.2.6
- Recreation steps: login+logout on rhel8/rhel9 and check `last`
- Debug logs: N/A

**Comment by jakule** [comment]
Fixed in https://github.com/gravitational/teleport/pull/19382

**Comment by jdconti** [comment]
> btmp -- bad logins (not currently implemented but would be useful to see those in lastb)

It doesn't look like `btmp` was addressed as part of this PR, can we re-open and track updating `btmp`?  

Thanks!

**Comment by jdconti** [comment]
Is there any chance we could get utmp/wtmp working with FQDN to emulate existing login behavior?  In it's current state it's just utilizing the IP address.
