### ISSUE TITLE
Improve Nav Highlighting for New Docs

### ISSUE THREAD

**Issue by twakes** [gravitational/teleport#1724]
**What happened**: When I click on a section in the docs, that section is not highlighted in the navigation. Rather both levels above are highlighted so you don't know where you are in the docs. See attached screen shot.
![screenshot 2018-02-26 09 28 30](https://user-images.githubusercontent.com/3769197/36685324-e06d5b16-1ad7-11e8-99e5-304399016356.png)

**What you expected to happen**: The section I am on should be highlighted.

**How to reproduce it (as minimally and precisely as possible)**: Go to https://gravitational.com/teleport/docs/2.4/quickstart/#installing-and-starting

**Comment by Kate288** [comment]
It should have text hoover, but Alexey didn't add it yet. I'll work on it. Thanks for letting me know.

**Comment by Kate288** [comment]
![nav bar](https://user-images.githubusercontent.com/33237244/36751201-548ca2fe-1bb4-11e8-9a2d-79e29e95dd40.png)
Only the text should be highlighted. I also think that we need to use smaller font size for the sub items for each section. It will increase the visual hierarchy of the menu. What do you think about this  style?

**Comment by twakes** [comment]
I like it, this will solve my issue. 

The only other thing I found confusing is that I perceived the blue background as the current location rather than a section demarcation. I would remove that background. Maybe replace with underlined text?

**Comment by Kate288** [comment]
[image: Inline image 3]
Are you talking about the title for every section?

On Tue, Feb 27, 2018 at 12:06 PM, Taylor Wakefield <notifications@github.com

**Comment by twakes** [comment]
yes

**Comment by Kate288** [comment]
oh ok. There are can be couple options to solve it. I'll send you some
examples when I will be done.

On Tue, Feb 27, 2018 at 12:12 PM, Taylor Wakefield <notifications@github.com

**Comment by Kate288** [comment]
Here are some solutions 
![nav bar examples](https://user-images.githubusercontent.com/33237244/36754407-b79b01b6-1bbd-11e8-959c-8e2dc0cc48ae.png)

**Comment by Kate288** [comment]
Ev prefers Example #3

**Comment by kontsevoy** [comment]
Yes. I also like how the example 3 is less "heavy" (i.e. top-level captions aren't as tall as what we have on staging)

**Comment by klizhentas** [comment]
I think example 3 works better because the nav color does not overlap with link color
