### ISSUE TITLE
`teleport configure` for app_servers produces deprecated/invalid YAML

### ISSUE THREAD

**Issue by mdwn** [gravitational/teleport#17268]
Expected behavior:

`teleport configure` for an application server, the resulting YAML should be valid.

Current behavior:

The YAML is invalid.

Bug details:
- Teleport version 11.0.0-alpha2
- Recreation steps
  - Add an application via the UI and copy the teleport configure string.
  - Run the command locally.
  - Run `teleport start -c app_config.yaml`
- Debug logs
```
teleport configure --output=$(pwd)/app_config.yaml --app-name=ui-app --app-uri=http://localhost:9000/ --roles=app --token=REDACTED --auth-server=11test.teleport:443 --data-dir=$(pwd)/ui-app-data-dir

A Teleport configuration file has been created at "/Users/mike/src/teleport-clusters/11test/app_config.yaml".
To start Teleport with this configuration file, run:

teleport start --config="/Users/mike/src/teleport-clusters/11test/app_config.yaml"

Happy Teleporting!
➜  11test teleport start -c app_config.yaml
ERROR: config v3 has replaced auth_servers with either auth_server or proxy_server

**Comment by zmb3** [comment]
See also https://github.com/gravitational/teleport/issues/5409
