### ISSUE TITLE
Access request: Search option in the Access Request to roles

### ISSUE THREAD

**Issue by akgoteleport** [gravitational/teleport#17283]
What would you like Teleport to do?
Currently, if a user wants to use request access to roles, they have to click on Access Request> New Request > Select roles > Select the role that they want to gain access to. However, if the list is long for the number of roles, there is no search option available. Nice to have the search option under Access request to list the desired role.

What problem does this solve?
Ease the navigation through the access request roles category.

If a workaround exists, please include it.
cmd + F and search for the role

**Comment by Erick-Reyes** [comment]
Duplicate as there is an existing issue already: 
https://github.com/gravitational/teleport/issues/14642
