### ISSUE TITLE
Leaf cluster roles access request not visible when access is initiated from the Root cluster

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#17291]
**Expected behavior:**
In a trusted cluster architecture, option to request leaf cluster roles should be visible when leaf cluster is accessed from the Root cluster

**Current behaviour:**
When a user accesses leaf cluster from the root cluster, the option to request roles isn't showing in the `New request` dropdown list. However, option to request roles is visible when the leaf cluster is accessed directly. 

**Bug details:**
- Teleport version
Observed in the versions below: 
Teleport v10.2.2
Teleport v10.3.1

**Recreation steps**
- Create a Trusted Cluster architecture as advised in the following documentation while mapping the role appropriately
https://goteleport.com/docs/management/admin/trustedclusters/

- Create a Teleport role access request with basic roles as in the following documentation
https://goteleport.com/docs/access-controls/access-requests/role-requests/

- Login to Root cluster web UI.
- Navigate to the cluster dropdown lists and select the specific leaf cluster. 
- Click Access Request > New Request > click the new request drop down list 
-  No option to select roles to request access, only resource are shown

However, if the Leaf Cluster Web UI is accessed directly, the option to request role is visible

I have also attached two screenshots for reference:
Screenshot one shows the visible role option when user logs in directly to the leaf cluster
Screenshot two shows missing role option when leaf cluster is accessed from the root. 

**- Debug logs**
N/A

![image](https://user-images.githubusercontent.com/74545288/195153543-eaccb73f-8a4f-427e-81bc-0276782b4b4e.png)
![image](https://user-images.githubusercontent.com/74545288/195153768-5c29f409-6414-44f1-9d67-9576b941064b.png)

**Comment by russjones** [comment]
This is working as intended. The leaf cluster decided who can gain access from the root cluster and how to map to a particular role.
