### ISSUE TITLE
Hardware Key Support for Teleport Connect

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#17311]
Hardware Key Support works with Teleport Connect, but is missing some important UX details:
 - [ ] YubiKey touch prompt for login, requests, sessions, etc. According to [prior discussion](https://github.com/gravitational/teleport/pull/14774#discussion_r949657009), this may require tsh-initiated call backs, similar to per-session MFA.

TODO: Do more Connect testing to list out additional UX issues

**Comment by gzdunek** [comment]
Implemented in https://github.com/gravitational/teleport/pull/47652.
