### ISSUE TITLE
A kubernetes-friendly way to handle the tokens

### ISSUE THREAD

**Issue by aardbol** [gravitational/teleport#17378]
What would you like Teleport to do?

A kubernetes-friendly way to handle the tokens

What problem does this solve?

Current, manual or non-ideal scenarios are needed to handle the tokens to authenticate the agents to the cluster. This has been implemented with traditional approaches in mind. Making this in a more k8s-friendly way will allow us to automate this easily and not rely on more risky solutions.

If a workaround exists, please include it.

Set the TTL very far in the future

**Comment by tigrato** [comment]
This issue will be fixed for Teleport 11. Starting with this version, Teleport will no longer need tokens with giant TTLs and it will also not be necessary to use storage volumes if they intend to short TTLs. It will use Kubernetes Secret Storage to store the agent's identity

There is also an open contribution to configure the helm chart to support IAM joining in which case no tokens are needed.

**Comment by aardbol** [comment]
Sounds great!
