### ISSUE TITLE
Unable to import package github.com/gravitational/teleport/lib/client

### ISSUE THREAD

**Issue by tonedefdev** [gravitational/teleport#17401]
Expected behavior:
When using the libraries to build a client to interact with the Teleport gRPC endpoints it should allow for importing all dependencies but its returning an error specifically with the `core-os` `go-oidc` packages.

These packages appear to have been deprecated in favor of the v3 packages. Is there an alternative source or way to get around this?

Current behavior:
```sh
github.com/gravitational/teleport/lib/client imports
        github.com/gravitational/teleport/lib/auth imports
        github.com/coreos/go-oidc/jose: cannot find module providing package github.com/coreos/go-oidc/jose
github.com/gravitational/teleport/lib/client imports
        github.com/gravitational/teleport/lib/auth imports
        github.com/coreos/go-oidc/oauth2: cannot find module providing package github.com/coreos/go-oidc/oauth2
github.com/gravitational/teleport/lib/client imports
        github.com/gravitational/teleport/lib/auth imports
        github.com/coreos/go-oidc/oidc: cannot find module providing package github.com/coreos/go-oidc/oidc
```

Bug details:
- Recreation steps
  go get "github.com/gravitational/teleport/lib/client"

**Comment by stevenGravy** [comment]
Not seeing this problem with go `1.18.5` or `1.19`.  what env @tonedefdev are you seeing this?

**Comment by tonedefdev** [comment]
Thanks for the prompt reply @stevenGravy! I don't know if it makes a difference that I'm using go `1.19.2` but I can't imagine a patch release being too much different, but definitely let me know if that could be it.

I'm trying to create a CLI that generates kubeconfigs similar to how `tctl auth sign  --user=my-user --format=kubernetes --ttl= 72h` works. I'm trying to rotate kubeconfigs every 72h, now, I could honestly just use tctl to do this, but I would like to build this into some tooling that was already written to integrate with our platform. 

Here's a snippet of the packages I'm attempting to import to make this work:
```go
package main

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"flag"
	"fmt"
	"log"
	"time"

	"github.com/gravitational/teleport/api/client"
	"github.com/gravitational/teleport/api/client/proto"
	"github.com/gravitational/teleport/api/defaults"
	"github.com/gravitational/teleport/api/types"
	keyClient "github.com/gravitational/teleport/lib/client"
	"golang.org/x/crypto/ssh"
)

Unfortunately, I can't share all the code, but I have gotten to the point of generating the user certificates and getting them signed by the auth server, so I looked to see how `tctl` client package handles this. I see this in the CLI but it's unexported:

[generateUserKeys](https://github.com/gravitational/teleport/blob/master/tool/tctl/common/auth_command.go#L673)

However, I essentially re-created most of what that function handles, but realized when I tried to create the Teleport profile that the `key` referenced here:

https://github.com/gravitational/teleport/blob/master/tool/tctl/common/auth_command.go#L794-L800

Is of this type:

https://github.com/gravitational/teleport/blob/2e892fed3a2aa7d4859a76ca211d36b330160a95/lib/client/interfaces.go#L70-L95

So I'm trying to import that package as `keyClient "github.com/gravitational/teleport/lib/client"` so I can create that `key` to pass it in to create the identity file. That's where I'm running into these issues that I posted here. Just wondering if there's maybe another way I can go about this? I feel like I'm almost there!

**Comment by zmb3** [comment]
We don't support importing `lib/client` in external packages. Everything under the `/api` module is fair game and we do support importing the API for external use.

That said, if you just want to generate a kubeconfig every 72 hours, you don't need to write any code to do that. This is exactly what Machine ID is for. You would just run `tbot` as a background service and configure it with a renewal period of 72 hours.

**Comment by tonedefdev** [comment]
> We don't support importing lib/client in external packages. Everything under the /api module is fair game and we do support importing the API for external use.

Ah, no worries then. I'll just leverage `tctl` directly in the pipeline to do what I need it to do, but I was hoping I could wrap it up nicely in a single binary.

> That said, if you just want to generate a kubeconfig every 72 hours, you don't need to write any code to do that. This is exactly what Machine ID is for. You would just run tbot as a background service and configure it with a renewal period of 72 hours.

I looked into Machine ID and `tbot` first actually and it unfortunately doesn't fit our needs. Each of our teams uses a shared agent pool for CI/CD, and with `tbot` it appeared that I would have to grant that machine a role to access each cluster, so theoretically, someone could access clusters they weren't supposed to access because the Machine ID would be shared. We also use scale sets so these agents are spun up per CI/CD job and I don't know how Teleport would handle that.

Today, each team gets a Service Connection for Kubernetes in their Azure DevOps project using IAM roles that is only meant for their application which is how we separate those duties for compliance purposes. I have code from how we were previously doing it that uploads the kubeconfig to their project's Service Connection in Azure DevOps so I was trying to keep this as unintrusive as possible.

Thanks for the help! I'll close this issue out :)
