### ISSUE TITLE
Switch default backend to `dir`

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1741]
## Description

Current default backend is `boltdb` that does not support graceful restarts, so we have to migrate off it in favor of `dir`.

The problem is that if we do that, we will break a lot of clusters that already rely on boltdb and have empty non explicit configuration.

So to do it properly, teleport 2.5.1 should:

* Upon start detect if there is a backend change, if the backend has been changed, but local auth server state points to the different one, admins should be asked to wipe out state directory and try again.

This means we would have to have some sort of on disk backend type file, for example /var/lib/teleport/backend.type

This also means that we will have to do flip through one minor version, so in the first minor version we in migration initialize this value, and in the second version we will use it to detect the backend change.

So 2.5.1 will write the value of the current backend to disk in /var/lib/teleport/backend.type

Then, 2.6.0 can introduce the following logic:

* If backend has been specified and  changed, return error asking admin to explicitly clean up the local state dir
* If backend has been specified not changed, proceed.

* If backend has not been specified, and this is the first start, pick dir backend
* If backend has not been specified, but the backend is picked, do nothing

**Comment by kontsevoy** [comment]
Lets _not_ punt this. This significantly helps with zero-downtime upgrades.

**Comment by klizhentas** [comment]
yeah, I agree on this one.
