### ISSUE TITLE
Add instructions for upgrading Teleport on Docker

### ISSUE THREAD

**Issue by KasperSkytte** [gravitational/teleport#17421]
## Applies To
Suggested chapter: Best practices for keeping Teleport updated.

## Details
Would be nice to know how to properly update teleport without having to reconfigure everything and rejoin nodes etc. A new container based on a newer container image version is essentially a new teleport cluster with a new CA pin. How can I easily update to a new version? Is creating a new container based on a newer image and mounting the same folders with configuration files enough?

**Comment by zmb3** [comment]
> Is creating a new container based on a newer image and mounting the same folders with configuration files enough?

Yes, so long as you persist the `data_dir` then teleport services will retain their identity during the upgrade and you won't need to re-join the cluster or update your CA pin, etc.

**Comment by KasperSkytte** [comment]
Thank you. Just upgraded with the same folder from v9 mounted. Worked like a charm. I think it would be nice to mention in the docs too.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ptgott** [comment]
For context, the current ["Upgrading the Teleport Binary" page](https://goteleport.com/docs/management/admin/upgrading-the-teleport-binary/) assumes that you have installed the `teleport` binary on a Linux host.
