### ISSUE TITLE
Provide web APIs for adding database and updating database CA certificate

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#17454]
## Description

When adding a new self-hosted database in Teleport Discover day-1 flow, users will need to:

1. Register "database" resource with basic metadata such as name, connection endpoint, labels; and
2. Set up mTLS between Teleport database service and their database instance.

These are 2 separate steps in the Discover wizard and we need to implement web APIs to support them. Currently we only have the API to fetch databases: https://github.com/gravitational/teleport/blob/v11.0.0-beta.1/lib/web/apiserver.go#L557.

### Add database

When registering a new database, Discover wizard will supply basic metadata:

```
POST /webapi/sites/:site/databases
{
  "name": "example",
  "protocol": "postgres",
  "uri": "postgres.example.net:5432",
  "labels": {"k": "v"}
}
```

The handler will make a [types.Database](https://github.com/gravitational/teleport/blob/v11.0.0-beta.1/api/types/database.go#L121) resource and [create it](https://github.com/gravitational/teleport/blob/v11.0.0-beta.1/api/client/client.go#L2365) in the cluster.

### Update database

For updating a database that already exists we only need to support updating CA certificate for now:

```
PUT /webapi/sites/:site/databases/:db
{
  "ca_cert": "---- BEGIN CERTIFICATE ----\nxxxx...."
}
```

Which will update it in the [spec](https://github.com/gravitational/teleport/blob/v11.0.0-beta.1/api/types/database.go#L259) and then [update](https://github.com/gravitational/teleport/blob/v11.0.0-beta.1/api/client/client.go#L2375) the database resource.

**Comment by marcoandredinis** [comment]
> The issue mentions self-hosted database. will the same endpoint be used for creating cloud-hosted databases?

Yeah, we should be able to create any database Type.
Specific fields will be within a root key for that cloud.

As an example
```json
{
  "name": "example",
  "protocol": "postgres",
  "uri": "postgres.example.net:5432",
  "labels": {"k": "v"},
  "aws": {...}
}
```
