### ISSUE TITLE
Allow pods to add themselves as Teleport applications or databases

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#17473]
A discussion recently with a prospect introduced a potential use case for both Teleport Kubernetes access and application access. If pods could automatically register themselves as application targets for Teleport application access, this would make a number of auto-scaling/auto-provisioning use cases much easier.

One way to achieve this currently might be to use a machine ID sidecar to get credentials that allow applications to register via the existing Teleport `tctl create -f app.yaml` or API functionality, but making this automatic or possible via Kubernetes service discovery (labels on Kubernetes services) would reduce friction considerably.

**Comment by zmb3** [comment]
See also https://github.com/gravitational/teleport/issues/4705

**Comment by programmerq** [comment]
This was added in Teleport 14.0.0

https://goteleport.com/docs/ver/14.x/application-access/enroll-kubernetes-applications/get-started/

See also: https://github.com/gravitational/teleport/issues/25538 and https://github.com/gravitational/teleport/blob/branch/v14/rfd/0135-kube-apps-discovery.md

**Comment by mvarendorff** [comment]
Before I open an accidental duplicate - The RFD states
> `- types: ["app"] # in the future "db" will be possible`

Is there an issue that tracks progress on supporting database pods registering themselves as DB against Teleport inside a Kubernetes cluster (not AWS / Azure)?

I couldn't find one but I am also not too familiar with the correct terminology.

**Comment by webvictim** [comment]
I think this issue was intended to track it, but turned into a catch-all for apps. Please open a separate issue with the request.
