### ISSUE TITLE
Getting started with Docker Compose

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#17492]
Expected behavior:
In our getting started with docker compose docs we have the users run `tsh ssh root@env=example hostname` which should work

Current behavior:
Instead it returns an error

Bug details:
- Teleport version - v10.3.2
- Recreation steps - Walk through docs (https://goteleport.com/docs/try-out-teleport/docker-compose/)
- Debug logs
`ERRO             failed to send user start event to auditd: failed to get auditd status: netlink receive: operation not permitted error:[
ERROR REPORT:
Original Error: *errors.errorString failed to get auditd status: netlink receive: operation not permitted
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/auditd/auditd_linux.go:182 github.com/gravitational/teleport/lib/auditd.(*Client).isEnabledUnderMutex
	/go/src/github.com/gravitational/teleport/lib/auditd/auditd_linux.go:293 github.com/gravitational/teleport/lib/auditd.(*Client).sendMsg
	/go/src/github.com/gravitational/teleport/lib/auditd/auditd_linux.go:282 github.com/gravitational/teleport/lib/auditd.(*Client).SendMsg
	/go/src/github.com/gravitational/teleport/lib/auditd/auditd_linux.go:147 github.com/gravitational/teleport/lib/auditd.SendEvent
	/go/src/github.com/gravitational/teleport/lib/srv/reexec.go:212 github.com/gravitational/teleport/lib/srv.RunCommand
	/go/src/github.com/gravitational/teleport/lib/srv/reexec.go:542 github.com/gravitational/teleport/lib/srv.RunAndExit
	/go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:399 github.com/gravitational/teleport/tool/teleport/common.Run
	/go/src/github.com/gravitational/teleport/tool/teleport/main.go:34 main.main
	/opt/go/src/runtime/proc.go:250 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: failed to get auditd status: netlink receive: operation not permitted] srv/reexec.go:213
luna.teleport
ERRO             failed to send UserEnd event to auditd: failed to get auditd status: netlink receive: operation not permitted error:[
ERROR REPORT:
Original Error: *errors.errorString failed to get auditd status: netlink receive: operation not permitted
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/auditd/auditd_linux.go:182 github.com/gravitational/teleport/lib/auditd.(*Client).isEnabledUnderMutex
	/go/src/github.com/gravitational/teleport/lib/auditd/auditd_linux.go:293 github.com/gravitational/teleport/lib/auditd.(*Client).sendMsg
	/go/src/github.com/gravitational/teleport/lib/auditd/auditd_linux.go:282 github.com/gravitational/teleport/lib/auditd.(*Client).SendMsg
	/go/src/github.com/gravitational/teleport/lib/auditd/auditd_linux.go:147 github.com/gravitational/teleport/lib/auditd.SendEvent
	/go/src/github.com/gravitational/teleport/lib/srv/reexec.go:226 github.com/gravitational/teleport/lib/srv.RunCommand.func1
	/go/src/github.com/gravitational/teleport/lib/srv/reexec.go:427 github.com/gravitational/teleport/lib/srv.RunCommand
	/go/src/github.com/gravitational/teleport/lib/srv/reexec.go:542 github.com/gravitational/teleport/lib/srv.RunAndExit
	/go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:399 github.com/gravitational/teleport/tool/teleport/common.Run
	/go/src/github.com/gravitational/teleport/tool/teleport/main.go:34 main.main
	/opt/go/src/runtime/proc.go:250 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: failed to get auditd status: netlink receive: operation not permitted] srv/reexec.go:227`

**Comment by zmb3** [comment]
@jakule something wrong with auditd here?

**Comment by jakule** [comment]
> @jakule something wrong with auditd here?

@zac I'm literally merging the fix right now https://github.com/gravitational/teleport/pull/17319
I'll close this issue after this fix is merged into v10

**Comment by jakule** [comment]
https://github.com/gravitational/teleport/pull/17495 should fix it.
