### ISSUE TITLE
CA rotations should be limited to one type at a time

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport#17493]
As the (currently) four CA types have very different uses and rotating them can cause very different things to happen in the cluster (every node restarts, all users must log in again), or require very different manual user actions (Teleport-aware web apps must reload the JWT key set, databases must be given a new certificate and must trust the new db CA), it doesn't really make sense to have a way - let alone _default_ - to rotate them all at once. Moreover, since CA rotation is not really an atomic process, it's easy to fall into problems such as #13481 (admittedly, that'd also be fixed by removing the forced in-process restart on host CA rotations).

We should disallow rotating all CAs at once on the auth service, and require a CA type to be passed in with `--type` in `tctl auth rotate`.

Will fix #13481.
Related Slack convo: https://gravitational.slack.com/archives/C0DF0TPMY/p1665496340374849

**Comment by sfreiberg** [comment]
The first portion of this work is complete. Rotating all of the certs is no longer the default option so users will have to explicitly rotate all certs now. When users do rotate all certs they will see a deprecation notice that this will no longer be supported in future versions. Once the v12 branch is cut I'll remove the deprecated functionality entirely for v13.

**Comment by espadolini** [comment]
Completed by #23608
