### ISSUE TITLE
ADFS Integration Notes

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1754]
#### Status Responder

If you see `urn:oasis:names:tc:SAML:2.0:status:Responder` as the status in the SAML response, the issue is most likely with the SAML authority (ADFS) [1]. Check the ADFS logs to see what errors are occurring. Typically this occurs when the signing key/certificate in the connector does not match the one uploaded to ADFS.

```xml
<samlp:Response ID="_rst456" InResponseTo="_abc123" IssueInstant="2014-09-17T21:06:32"
    Version="2.0">

  <samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder"/>
  </samlp:Status>

  <saml:Assertion ID="_xyz888" IssueInstant="2014-09-17T21:06:32" Version="2.0">
    <saml:AttributeStatement>
      <saml:Attribute Name="email">
        <saml:AttributeValue>alice@acme-corp.biz</saml:AttributeValue>
      </saml:Attribute>
    </saml:AttributeStatement>
  </saml:Assertion>

</samlp:Response>
```

A successful response will have status `urn:oasis:names:tc:SAML:2.0:status:Success` that looks like the following:

```xml
<samlp:Status>
  <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
</samlp:Status>
```

#### Clock Synchronization

If Teleport logs report `SAML error, invalid time auth`, this means that ADFS sent a Response that was issued in the future (in other words, the `NotBefore` value is not yet valid). This usually occurs when there is clock skew between ADFS and Teleport. To push back the time the Response is valid use the following PowerShell command to add a skew value to `NotBefore` [2]. This value may need to be adjusted depending on how much the skew is.

```powershell
Set-ADFSRelyingPartyTrust -TargetIdentifier "<relying party identifier>" -NotBeforeSkew 5
```

#### Updating TLS Certificates

If the TLS certificate used by ADFS has expired, use the following steps to update the certificate.

1. First obtain a valid TLS certificate and convert it to PFX format.
   ```
   openssl pkcs12 -export -out cert.pfx \
      -inkey private_key.key \
      -in cert.crt \
      -certfile intermediate_cert_chain.crt
   ```
1. Follow the following steps to import the certificate into the users personal store: https://technet.microsoft.com/en-us/library/cc995171.aspx. While importing, note down that thumbprint of the certificate. This will be used later.
1. Use the below PowerShell command to update the certificate. [3]
    ```powershell
    Set-AdfsSslCertificate -Thumbprint '<thumbprint of new cert>'
    ```

#### Notes

[1] https://msdn.microsoft.com/en-us/library/hh269642.aspx
[2] http://rmichaelmead.com/adfs-not-before-time-skew/
[3] https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap

**Comment by zmb3** [comment]
@russjones what's the action here? Do we want to put these "notes" in our docs somewhere, or was this just for bookkeeping?

**Comment by russjones** [comment]
@zmb3 This was just for notes when I was adding ADFS SSO integration.

I don't think it belongs in the docs unless @ptgott thinks so.

Feel free to close it.
