### ISSUE TITLE
Upgrade react-select library and refactor existing usage

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#17553]
There was a refactoring done with forms using react select a while back and it seems it introduced some regressions. We need to do the following (i think we use the dark version to use in our console view - the web terminal in blank state):

- Upgrade react-select and utilize typescript
- Upgrading will introduce probably a bunch of typescript errors so we need to go in and refactor all usage
- There are styling bugs with our [light version css](https://github.com/gravitational/webapps/blob/4da005d774cff0820b50439541a3d6ee1f89d0b3/packages/shared/components/Select/Select.tsx#L62) probably in our [dark version css](https://github.com/gravitational/webapps/blob/776f924cabc4d20b0e18fe86c16185e00ee09019/packages/shared/components/Select/DarkStyledSelect.tsx#L19) as well where:
   - with multi field selects, if selected items get bigger than width, instead of height expanding, it does not expand at all (caused by [this](https://github.com/gravitational/webapps/blob/776f924cabc4d20b0e18fe86c16185e00ee09019/packages/shared/components/Select/DarkStyledSelect.tsx#L40))
   - text size is not unified between `FieldInput` and `FieldSelect`, i think `FieldInput` the text is larger for some reason

While working on refactoring, we should also address these issues:
- figma designs favor dark themed forms, we might as well convert now? when we do, we also need to make sure it looks okay in our dark console view (web terminal blank page)
- https://github.com/gravitational/webapps/issues/474

**Comment by kimlisa** [comment]
Also note that we don't use allcaps like we do currently in our theme for the text above input boxes

<img width="301" alt="image" src="https://user-images.githubusercontent.com/43280172/196533220-f24f846f-14e3-4712-bc69-2a4af98d5f9c.png">

<img width="652" alt="image" src="https://user-images.githubusercontent.com/43280172/196533274-78930141-e120-47fc-b814-72aa0ad551f7.png">

**Comment by zmb3** [comment]
@kimlisa do you want to keep this open or can we close it? I have to imagine we have upgraded this library at some point since 2022.

**Comment by kimlisa** [comment]
yes, @bl-nero updated it: https://github.com/gravitational/teleport/pull/43056
