### ISSUE TITLE
`tsh mfa add` doesn't show OTP QR code in Windows

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#17564]
__Expected behavior:__

Open the OTP QR code using a system image viewer.

__Current behavior:__

QR code image is not shown, user has to type the OTP secret key manually.

Bug details:
- Teleport version: 11
- Recreation steps: `tsh mfa add --type=OTP` and follow the prompts
- Debug logs: not necessary

**Comment by tobiaszheller** [comment]
@codingllama does it work on macOS? I have tried it on mac and same behaviour as on Windows.

**Comment by codingllama** [comment]
@tobiaszheller yes, it opens in the background for me too. If you can find an easy way to give it focus, go for it.
