### ISSUE TITLE
Firefox 58.0.2 (64 bits) - no copy & paste

### ISSUE THREAD

**Issue by hdep** [gravitational/teleport#1758]
Hi,

I'm running Teleport v2.4.3 git:v2.4.3-0-g165acec.
Copy and paste like https://gravitational.com/teleport/docs/faq/#does-web-ui-support-copy-and-paste does work with chrome, but not with firefox 58.0.2

is firefox supported ? I didn't see any statement on this.

**Comment by alex-kovoy** [comment]
Copy&Past works as in regular terminals i.e. `ctrl+shift+v`.

In some browsers like Firefox 58.0.2 `ctrl+shift+v` might not work, please use `shift+insert` instead.

For a terminal we use xtermjs control, you can read a discussion on the subject in here sourcelair/xterm.js#292

**Comment by C-Duv** [comment]
`[Ctrl]+[Shift]+[V]` works to paste, but `[Ctrl]+[Shift]+[C]` opens the Inspector view/tool (on Firefox 123.0).

Workaround: Use `[Ctrl]+[Insert]` to copy (as advised on [this comment](https://github.com/rancher/rancher/issues/28723#issuecomment-1443363117)).
