### ISSUE TITLE
Audit log can be altered 

### ISSUE THREAD

**Issue by hdep** [gravitational/teleport#1759]
Hello,

by default session records are stored in /var/lib/teleport/log as stated in https://gravitational.com/teleport/docs/admin-guide/#audit-log

I see that if I changed the data in the bytes file, the session recorded can be wrong. 
So in this state I can't use the software for compliance.

is there some plan to encrypt/sign those file on order to provide authenticity of the recorded session ?

**Comment by klizhentas** [comment]
for file system storage backend we expect customers to use FS level encryption, we are going to release external S3 backends for sessions upload in 2.5.1
