### ISSUE TITLE
Increase a connection timeout from proxy to SSH

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1760]
**What happened**:

One of our users noticed that a server that was a bit busy or something didn’t respond within 10 seconds to the teleport proxy on the first SSH of the day
It’d be nice to increase that timeout to 30 seconds to smooth that sort of thing out

**What you expected to happen**:

Is it possible to increase the connection timeout setting for the proxy’s connection to the target ssh server?
The default seems to be 10 seconds

**How to reproduce it (as minimally and precisely as possible)**:

Delay the connection response for more than 10 seconds

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

```
```channel 0: open failed: connect failed: ssh: handshake failed: read tcp x.x.x.x:43564->x.x.x.x:22: i/o timeout```
```

**Comment by klizhentas** [comment]
I think it's reasonable to bump timeout to 60 seconds

**Comment by james-lawrence** [comment]
more reasonable to provide a way to configure it. maybe pull from SSH config?

**Comment by klizhentas** [comment]
I'd like to keep it simple for now - 60 seconds seems reasonable default, if someone needs anything different we will reconsider.
