### ISSUE TITLE
Revise the output of `tctl desktops ls`

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#17612]
Currently `tctl desktops ls` produces a table like the following:

```
Host                Address             AD Domain Labels               Version
------------------- ------------------- --------- -------------------- ----------
Isaiahs-MacBook-... ec2-54-162-177-2...           another=label,tes... 12.0.0-dev
```

It would be nice if a `Name` column were added, to make it easier for users to determine the object name required for other commands like `tctl get` and `tctl rm`. It also appears that `Version` is reporting the teleport version, whereas it would make more sense if this were the resource version.

**Comment by zmb3** [comment]
> It also appears that Version is reporting the teleport version, whereas it would make more sense if this were the resource version.

Why would that make more sense? Is that what other commands do?

**Comment by ibeckermayer** [comment]
> Why would that make more sense?

All the other fields are information about the desktop itself, reporting the version of teleport seems like a non sequitur. 

> Is that what other commands do?

It looks like it, so probably not appropriate to fix in this issue. Still I wonder why we do that.

**Comment by zmb3** [comment]
This was completed in #18779
