### ISSUE TITLE
Correct two issues in the Desktop Getting Started Guide

### ISSUE THREAD

**Issue by ionutcbn** [gravitational/teleport#17625]
## Applies To
[https://goteleport.com/docs/desktop-access/getting-started/](url)

## Details
1. In the section "Step 6/7. Configure Teleport" in the Teleport Configuration Guide make it explicit that the port number is required for the 
```
ldap:
  addr: $LDAP_SERVER_ADDRESS"
```
If the port (636 by default) is not provided the system will issue an error.

2. In the same documentation reference it is stated:
```
# This should be the path to the certificate exported in Step 4.
    der_ca_file: /path/to/cert
```
But actually it is step 5 since step 4 only refers to Windows Server 2012 R2 Domain Controller

**Comment by ibeckermayer** [comment]
Thanks for the report @ionutcbn
