### ISSUE TITLE
Access requests docs don't explain how TTL for requests works

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#17630]
## Applies To

* https://goteleport.com/docs/access-controls/access-requests/
* https://goteleport.com/docs/access-controls/access-requests/resource-requests/
* https://goteleport.com/docs/access-controls/access-requests/role-requests/

## Details

I was testing the upcoming access requests in Connect. I made two identical resource requests which resulted in granting me the same role which has TTL of 10h10m. One request was made through Connect, the other through the Web UI.

I was surprised to see that when assuming those requests, no matter whether through the Web UI or Connect, the one request submitted through Connect would always give me overall TTL that was shorter by ~25 minutes compared to the other resource request created through the Web UI.

I _assumed_ that when assuming a resource request, the TTL will be set to 10h10m from the time the request was made. But this is not how it works, I suppose for security reasons (according to Michael this is explained somewhere in code comments). Teleport will always pick the smallest TTL from the set of the current cert TTL, the role TTL and maybe some other TTL that I didn't even think of.

The docs don't explain it though. They also don't explain how `tsh request drop` affects the TTL of current "session". It'd be nice to have that documented.

**Comment by ravicious** [comment]
@ptgott Tremendous work on that access requests docs page!

One thing I think is still not explained explicitly anywhere is how `tsh request drop` affects the TTL of the cert. In general, that command is mentioned only in two places and none of them mentions that:

* https://goteleport.com/docs/access-controls/access-requests/resource-requests/#step-88-resume-regular-access
* https://goteleport.com/docs/reference/cli/tsh/#tsh-request-drop

Should I open a new issue for this?

**Comment by ptgott** [comment]
@ravicious Thanks! And a new issue would be great.
