### ISSUE TITLE
Find a tidy way to handle our growing library of Database Access guides

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#17641]
## Applies To
`docs/config.json`, `/docs/database-access/guides/`

## Details
The Database Access section of the docs has, by far, more guides than any other `/guides` section:

```bash
$ find docs/pages -maxdepth 2 -type d -name "guides" -exec bash -c "echo -n {}:; find {} -name '*.mdx' | wc -l" \;
docs/pages/database-access/guides:      18
docs/pages/machine-id/guides:       5
docs/pages/access-controls/guides:       8
docs/pages/kubernetes-access/guides:       4
docs/pages/management/guides:       9
docs/pages/server-access/guides:       8
docs/pages/application-access/guides:       5
```

As a result, the sidebar listings for this section have become fairly difficult to navigate:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/25250668/197049113-60d7b7f3-cca2-4948-8bf7-9fa5be886131.png">

Let's find a neater way to organize these guides as as we add more Database Access integrations.

## Related Issues
N/A

**Comment by stevenGravy** [comment]
Good to have a path to Guides to Connect as a user vs Guides to configure a db resource.

**Comment by ptgott** [comment]
I'm thinking the best way forward is to split the `/docs/database-access/guides` section into:

- `/docs/database-access/aws`
- `/docs/database-access/google-cloud`
- `/docs/database-access/azure` 
- `/docs/database-access/self-hosted`

If we move all self-hosted guides into a dedicated "Self Hosted" section, it also means we can remove "Self-Hosted" from their sidebar entries and make the sidebar easier to read.

The "High Availability" guide can move into the top level of the "Database Access" section.
