### ISSUE TITLE
Include `tsh proxy db` in Teleport CLI reference

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#17664]
## Applies To

[Command Line (CLI) Reference ](https://goteleport.com/docs/reference/cli/#tsh-proxy-app)

## Details

There’s no CLI reference on `tsh proxy db` that details that you can use `--tunnel` to avoid including the certificate locations in the GUI and that you can define the proxy port with `-p` : `tsh proxy db --tunnel -p 12345 postgres`.

This is only documented in the [Database Access GUI Clients guide](https://goteleport.com/docs/connect-your-client/gui-clients/#get-connection-information).

**Comment by zmb3** [comment]
This is resolved.
