### ISSUE TITLE
teleport start default output

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1776]
## Problem 1

Our quickstart promises this output:

```
$ mkdir -p /var/lib/teleport
$ sudo teleport start

[AUTH]  Auth service is starting on 0.0.0.0:3025
[PROXY] Reverse tunnel service is starting on 0.0.0.0:3024
[PROXY] Web proxy service is starting on 0.0.0.0:3080
[PROXY] SSH proxy service is starting on 0.0.0.0:3023
[SSH]   Service is starting on 0.0.0.0:3022
```

Notice the absence of `--debug` flag.
2.5 is giving this:

```bash
WARN [PROCESS]   No TLS Keys provided, using self signed certificate. service/service.go:1474
WARN [AUTH]      Parameter advertise_ip is not set for this auth server. Trying to guess the IP this server can be reached at: 192.168.122.1:3025. service/service.go:684
```

## Problem 2

```
$ tctl users add ekontsevoy
user "User(name=ekontsevoy, roles=[], identities=[])" already exists
```

Should be "user ekontsevoy already exists"

## Proposal

* When in "zero-configuration mode" (i.e. no YAML config provided) Teleport should start with `ERROR` log level (so those warnings won't confuse first-timers).
* Default stderr output should be as before.
* Make the warning more readable / less verbose for `advertise_ip` (Ev: I'll update the text myself)

**Comment by klizhentas** [comment]
Also provide more progress during migrations of the sessions, to let admins know about what's actually going on.

**Comment by kontsevoy** [comment]
@klizhentas I've fixed "problem 2", removing myself from assigness.
