### ISSUE TITLE
Teleport Agent installation via Helm 

### ISSUE THREAD

**Issue by r-aju** [gravitational/teleport#17776]
Expected behavior:
There has been multiple changes made in helm charts of teleport agent files over the past week 

Installation of Teleport Agent using Helm Chart in Kubernetes Cluster deploying as expected.

Current behavior:
Installation of Teleport Agent failing in Kubernetes.

Bug details:
- 10.0.2
- Deploying teleport Agent on Kubernetes via helm chart in master branch

Since, there has been multiple changes In the helm charts, the installation is failing with the following below error.Please help expediting this.

```
ERROR: failed parsing the config file: yaml: unmarshal errors:  line 6: field proxy_server not found in type config.Global
```

**Comment by stevenGravy** [comment]
@r-aju please use the branch version to match your version.  The `master` version is not compatible with the V10.  You can download the tarball of version 10 or get it from the `branch/v10` branch.

**Comment by r-aju** [comment]
@stevenGravy, but the installation of agent with the version in the master branch was working a week back though.

Need to understand if there was any major changes made in the master branch code and helm chart templates.

**Comment by stevenGravy** [comment]
There is a new config version that supports `proxy_server` field.

**Comment by yefryf** [comment]
Got the same error and fixed it by installing teleport-agent at the same version of the teleport server, just adding:
`--version SERVER-VERSION`

`helm install teleport-agent teleport/teleport-kube-agent --version 10.0.2 -f prod-cluster-values.yaml --create-namespace --namespace teleport`

**Comment by r-aju** [comment]
@stevenGravy , Thank you for the confirmation.

Also, @yefryf thanks for this 😄, For a short term fix I just cloned the older stable branch and deployed this 😓
