### ISSUE TITLE
Unable to add application

### ISSUE THREAD

**Issue by klimonoid** [gravitational/teleport#17784]
Expected behavior:
I want to access my app through teleport

Current behavior:
When i press LAUNCH button in UI i have infinite redirection

Bug details:
- Teleport version: 
on the node where app runs - v10.3.2 git:v10.3.2-0-g504d64c go1.18.6
on the node where proxy and auth services run -  v10.2.2 git:v10.2.2-0-gdd70f8a go1.18.6
- Recreation steps
I have a domain on cloudflare where my teleport service is. on different node i have the containerized grafana service on 3000 port. I have started application service on it using this command
`start teleportation --config=$HOME/.config/app_config.yaml`
- Logs and other info:
We have described this topic in slack and were instructed to open the issue - https://app.slack.com/client/TF04GMFKN/CEZH6UL64/thread/CEZH6UL64-1666022175.260919
[app_service.txt](https://github.com/gravitational/teleport/files/9861129/app_service.txt)
[app_service_logs.txt](https://github.com/gravitational/teleport/files/9861130/app_service_logs.txt)
[proxy_service_logs.txt](https://github.com/gravitational/teleport/files/9861131/proxy_service_logs.txt)
[teleport_central.txt](https://github.com/gravitational/teleport/files/9861132/teleport_central.txt)

**Comment by jcace** [comment]
Same issue here. `Teleport v11.2.2 git:api/v11.2.2-0-g90bde73 go1.19.5` 

I've tried with the `debug_app` enabled but still getting infinite redirection. Port 443 is forwarded and domain is correct. What else could cause this?

**Comment by zmb3** [comment]
This should be fixed by #20418
