### ISSUE TITLE
Add client-only version option to `tsh`

### ISSUE THREAD

**Issue by tcsc** [gravitational/teleport#17817]
What would you like Teleport to do?

> we would like you to add a command-line flag to this subcommand that disables its contacting the server, and reports only the version of the client tool, with no network activity involved or required.
For prior art, see the kubectl version subcommand's --client flag

What problem does this solve?

Avoids doomed-to-fail attempts to contact a Teleport proxy in situations where the network is known not to be good, and the error messages  this causes

**Comment by seh** [comment]
Hey, I wrote that (https://github.com/gravitational/teleport/issues/17817#issue-1423134641). Thank you for implementing this!
