### ISSUE TITLE
Possibility to case-insensitive filtering using simple and advanced options.

### ISSUE THREAD

**Issue by dw72** [gravitational/teleport#17829]
1. What would you like Teleport to do?

    Should be a possibility for case-insensitive filtering using simple and advanced options.

2. What problem does this solve?

    The user now must remember if the name, labels, or other has a lower, upper, or mixed case. This is problematic with a large number of managed items.

3. If a workaround exists, please include it.

    I don't know any.

**Comment by zmb3** [comment]
This is being tracked in #6707
