### ISSUE TITLE
`TestIntegrations/TrustedTunnelNode` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#17824]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/347dcec3-5488-4071-8791-01dc446021d4?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/c96fa16b-3f09-433a-aaef-07b08a585650?project=ci-account

#### Relevant snippet

```
    --- FAIL: TestIntegrations/TrustedTunnelNode (7.47s)
{"caller":"sshutils/server.go:490","component":"ssh:proxy","level":"debug","message":"Closed connection 127.0.0.1:41550.","timestamp":"2022-10-21T20:50:57Z"}
        	Test:       	TestIntegrations/TrustedTunnelNode
        	            	failed connecting to node cluster-aux-node. connection rejected: failed dialing through tunnel (no tunnel connection found: no node reverse tunnel for  found) or directly (dial tcp: lookup cluster-aux-node on 127.0.0.11:53: no such host)
        	Error:      	Received unexpected error:
        	            				/workspace/integration/integration_test.go:97
        	Error Trace:	/workspace/integration/integration_test.go:2764
    integration_test.go:2764: 
```

**Comment by GavinFrazar** [comment]
https://console.cloud.google.com/cloud-build/builds/59ffe1b4-c3ac-4ed6-9954-58bc4df80d18?project=ci-account

on a branch/v10 backport: https://github.com/gravitational/teleport/pull/18618

**Comment by ibeckermayer** [comment]
Another on a v10 backport 

https://console.cloud.google.com/cloud-build/builds/8aa22a6f-8386-4403-b549-22298f963b77?project=ci-account

**Comment by zmb3** [comment]
Closing since there have been no recent reports
