### ISSUE TITLE
Option of case insensitive for SSO claims and values 

### ISSUE THREAD

**Issue by jing-teleport** [gravitational/teleport#17822]
**What would you like Teleport to do?**
Please add option to support case insensitive for SSO claims and values.

**What problem does this solve?**
Some SSO providers making claims and values to all lower cases, and some providers keeping case sensitive.

Role mapping in Teleport is difficult and easy to break.

Everything will be fixed if there is an option to support case insensitive for SSO claims and values.

**If a workaround exists, please include it.**
NA

**Comment by zmb3** [comment]
This is tracked in https://github.com/gravitational/teleport/issues/6707
