### ISSUE TITLE
Server Access getting started guide should make use of `--proxy` instead of `--auth-server`

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#17845]
## Applies To
https://goteleport.com/docs/server-access/getting-started/

## Details

Since introducing `--proxy` support in Teleport, we should prefer that in situations where the user is connecting their Node to their cluster via the proxy. Continuing to supply `--auth-server` with the proxy address may not work in some cases and may stop working in future releases, and the sooner we can shift this behaviour the better.

**Comment by lsgunn-teleport** [comment]
There aren't any `--auth-server` occurrences in the server-access docs. There are occurrences elsewhere.

**Comment by lsgunn-teleport** [comment]
Since other occurrences seem to be valid, closing this issue as done.
