### ISSUE TITLE
aws cli command error from : https://goteleport.com/docs/deploy-a-cluster/deployments/aws-terraform/

### ISSUE THREAD

**Issue by pnrao1983** [gravitational/teleport#17840]
## Applies To
(https://goteleport.com/docs/deploy-a-cluster/deployments/aws-terraform/)

## Details
➜  teleport-ent git:(master) ✗ aws elbv2 describe-load-balancers --names "${TF_VAR_cluster_name}" --query "LoadBalancers[*].DNSName" --output text

An error occurred (ValidationError) when calling the DescribeLoadBalancers operation: Load balancer names cannot be empty
➜  teleport-ent git:(master) ✗ aws elbv2 describe-load-balancers --names "${TF_VAR_cluster_name}" --query "nara-test-cluster-proxy-cba58e4966f66195.elb.us-east-2.amazonaws.com[*].DNSName" --output text

Bad value for --query nara-test-cluster-proxy-cba58e4966f66195.elb.us-east-2.amazonaws.com[*].DNSName: Bad jmespath expression: Unknown token '-':
nara-test-cluster-proxy-cba58e4966f66195.elb.us-east-2.amazonaws.com[*].DNSName
    ^
➜  teleport-ent git:(master) ✗ aws elbv2 help

Could not find executable named "groff"
➜  teleport-ent git:(master) ✗ aws elbv2 describe-load-balancers --names "${TF_VAR_cluster_name}-proxy" --query "LoadBalancers[*].DNSName" --output text

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: -proxy

➜  teleport-ent git:(master) ✗ aws elbv2 describe-load-balancers --names "${TF_VAR_cluster_name}-auth" --query "LoadBalancers[*].DNSName" --output text

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: -auth

**Comment by pnrao1983** [comment]
While executing the aws commands i could see the above errors in description. Please correct me if i am executing with insufficient info

**Comment by zmb3** [comment]
@pnrao1983 are you still having trouble with this or can I close it?
