### ISSUE TITLE
AWS DynamoDB support (DB access)

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#17842]
### What
Would like Teleport to have the ability to manage DynamoDB access through Database Access flow. 

### Success criteria:
* DynamoDB should be extracted from application access flow and it should be configurable as Database Access resource.
* Support DynamoDB events as Database Audit Logs.

**Comment by GavinFrazar** [comment]
closing this since the only remaining work is the docs update and we are tracking that on a separate issue here: https://github.com/gravitational/teleport/issues/19600
