### ISSUE TITLE
`teleport configure --auth-server <proxy address>` breaking change in v11

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#17890]
### Expected behavior:
`teleport configure --auth-server <addr>` should continue to generate a working configuration when `<addr>` points to an auth server **or** a proxy server. If we want to specify that the service should only connect to an auth server and not a proxy, this change should be opt-in.

 ### Current behavior:
`teleport configure --auth-server <proxy address>` generates a v3 teleport config with `auth_server` set to the given proxy address, and the service will fail to join the cluster, only attempting to join as if it is connecting directly to an auth server.

This diverges from the behaviour of `teleport start --auth-server <proxy address>` which still successfully connects when given a proxy address.

### Workaround
Use `teleport configure --proxy <proxy address>`

### Bug details:
- Teleport version: 11.0.0
- Recreation steps: Use `teleport configure --auth-server <proxy address>` to generate a config, and try to join the cluster with it.
- Debug logs
```
Node failed to establish connection to cluster: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for *.teleport.example.com, teleport.example.com, not <id>.teleport.cluster.local". pid:30996.1 service/connect.go:119
```

**Comment by nklaassen** [comment]
related: https://github.com/gravitational/teleport/issues/17845 and https://github.com/gravitational/teleport/pull/17869

**Comment by nklaassen** [comment]
@russjones I'm not sure if we'll want to revert the breaking change while we're early here and (at least temporarily) continue to generate v2 configs when the `--auth_server` flag is used, or leave it as is, update the docs, and deal with the fallout, but that probably needs a product decision.

If we want to revert the breaking change we should get this assigned and out the door relatively quickly so that people don't start relying on the new behaviour.

cc @ryanclark

**Comment by strideynet** [comment]
Closed by https://github.com/gravitational/teleport/pull/17914
