### ISSUE TITLE
`TestWebAgentForward` flakiness

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#17918]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/649ebad9-23c2-44c9-b64f-7e0608370c4d?project=ci-account

#### Relevant snippet

```
    testing.go:1097: TempDir RemoveAll cleanup: unlinkat /tmp/TestWebAgentForward2505968907/002/log/upload/streaming/default/multi/e831e256-d73a-442a-aec1-d3fe4fd9b47d/6f55c068-6459-41df-a401-bda7822f6b82: directory not empty
--- FAIL: TestWebAgentForward (7.56s)
```

**Comment by zmb3** [comment]
I can't reproduce the original failure, though it would be easy to eliminate by disabling async recording.

Also note that this test also suffers from the issue described in #13335.
