### ISSUE TITLE
Add optional role option to web UI resource access request

### ISSUE THREAD

**Issue by rishibarbhaya-design** [gravitational/teleport#17920]
- By default, add the set of minimal roles that are associated with the request
- Allow users to remove roles from this minimum set

**Comment by rishibarbhaya-design** [comment]
Considering the requirement, we've selected this option for the role option.
Role element follows ACCORDION structure experience.

1. Default state includes 1 role selected with accordion collapsed
2. Once expanded user can select the Roles and move to reviewers

Once expanded the below elements move down making the entire side drawer vertically expanded.
And submit button becomes STICKY.

**Comment by rishibarbhaya-design** [comment]
![Image](https://user-images.githubusercontent.com/88441969/198719043-27e4d4b3-ff3e-43f3-8d3c-a1fd4d993000.png)
![Image](https://user-images.githubusercontent.com/88441969/198719042-6a78eb19-66f7-4545-93f0-e317586e13ab.png)

**Comment by xinding33** [comment]
Design looks good but to clarify, default roles should be the minimal set of roles associated with the request and this is likely multiple pre-selected roles.

**Comment by zmb3** [comment]
FYI @rudream

**Comment by zmb3** [comment]
Closing this since we shipped the feature.
