### ISSUE TITLE
Implement HTTP Health Check Endpoint (Feature Request)

### ISSUE THREAD

**Issue by osterman** [gravitational/teleport#1794]
## what
* Implement a standard health check endpoint (e.g. `/ping` or `/healthz`) for Teleport proxy

## why
* Using `/web` as a health check endpoint throws exceptions if cookies not enabled
* Want to use this health check for Kubernetes Liveness and Readiness probes
* ELBs do not support passing HTTP headers with health checks

**Comment by klizhentas** [comment]
you can start teleport with --diag-addr=127.0.0.1:1234 and use it as a healthz

**Comment by benarent** [comment]
Just looping back on this. We've added a range of useful health checks. https://gravitational.com/teleport/docs/admin-guide/#troubleshooting 

I'm going to mark as closed, but if you have any questions please reply on this ticket.
