### ISSUE TITLE
`TestOIDCAuthRequest` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#17962]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/a6e02731-0e2e-46b3-b733-bc97c7e73060?project=ci-account

#### Relevant snippet

For `TestOIDCAuthRequest/can_create_sso_test_request_with_combined_access`:

```
    --- FAIL: TestOIDCAuthRequest/can_create_sso_test_request_with_combined_access (10.04s)
        	Test:       	TestOIDCAuthRequest/can_create_sso_test_request_with_combined_access
        	            	timed out syncing oidc connector example, ensure URL "https://gitlab.com" is valid and accessible and check configuration
        	Error:      	Received unexpected error:
        	Error Trace:	/workspace/lib/auth/auth_with_roles_test.go:598
    auth_with_roles_test.go:598: 
```
and for `TestOIDCAuthRequest/can_create_regular_request_with_normal_access`

```
    --- FAIL: TestOIDCAuthRequest/can_create_regular_request_with_normal_access (10.06s)
        	Test:       	TestOIDCAuthRequest/can_create_regular_request_with_normal_access
        	            	timed out syncing oidc connector example, ensure URL "https://gitlab.com" is valid and accessible and check configuration
        	Error:      	Received unexpected error:
        	Error Trace:	/workspace/lib/auth/auth_with_roles_test.go:598
    auth_with_roles_test.go:598: 
```

and for `TestOIDCAuthRequest/can_create_regular_request_with_combined_access`

```
    --- FAIL: TestOIDCAuthRequest/can_create_regular_request_with_combined_access (10.05s)
        	Test:       	TestOIDCAuthRequest/can_create_regular_request_with_combined_access
        	            	timed out syncing oidc connector example, ensure URL "https://gitlab.com" is valid and accessible and check configuration
        	Error:      	Received unexpected error:
        	Error Trace:	/workspace/lib/auth/auth_with_roles_test.go:598
    auth_with_roles_test.go:598: 
	invalid character '<' looking for beginning of value
```

**Comment by zmb3** [comment]
Ehhh it looks like this test actually hits gitlab.com - an external dependency like this is not suitable for a unit test.

**Comment by zmb3** [comment]
cc @Tener - looks like a dependency on gitlab.com was added in https://github.com/gravitational/teleport/pull/12519

Can we use a Fake IdP instead for this test so that is more deterministic and can run without a network connection to another company's infra?

**Comment by ibeckermayer** [comment]
AFAICT the test with the external gitlab.com dependency has been removed from OSS `master`, but a similar test remains in `e/lib/auth/oidc_test.go` (https://github.com/gravitational/teleport.e/pull/630/files#diff-a3dc13a8f8867056f2611b2212425e50a213d44dc02fbd87571aeb03e08ecace)

**Comment by camscale** [comment]
> that removal has not been backported

I'm working on that now and a series of PRs is imminent. If this change gets made before I complete the backports, I'll bring it back when I do the rest.

**Comment by Tener** [comment]
> Ehhh it looks like this test actually hits gitlab.com - an external dependency like this is not suitable for a unit test.

> cc @Tener - looks like a dependency on gitlab.com was added in #12519
> 
> Can we use a Fake IdP instead for this test so that is more deterministic and can run without a network connection to another company's infra?

Agreed. I don't recall exactly why I picked `https://gitlab.com/`, but introducing external dependency wasn't my intention.

@camscale let me know if you need any help with your PRs.

**Comment by Tener** [comment]
PRs for:
master: https://github.com/gravitational/teleport.e/pull/674
v11: https://github.com/gravitational/teleport/pull/19617
v10: https://github.com/gravitational/teleport/pull/19627

**Comment by ibeckermayer** [comment]
e ref with the fix from https://github.com/gravitational/teleport.e/pull/674 was updated in https://github.com/gravitational/teleport/pull/19610
