### ISSUE TITLE
Warn Users accessing Kubernetes cluster with no users or groups setting

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#18000]
What would you like Teleport to do?

Warn if no users or groups are available within a K8s cluster.  Example below. 

```bash
Logged into kubernetes cluster "example".
Try 'kubectl version' to test the connection.
WARNING: No Kubernetes users or groups are associated with this Kubernetes cluster access.  That could prevent access.
```

What problem does this solve?

If a user has access to a Kubernetes cluster but no user or groups in the cluster that can cause internal errors when attempted. The errors given will not indicate easily to the user they lack access within the cluster. See below.

```bash
$ kubectl version 
Error from server (InternalError): an error on the server ("unknown") has prevented the request from succeeding
```

If a workaround exists, please include it.

Users need to review the roles configuration required with Kubernetes access.

**Comment by tigrato** [comment]
@stevenGravy this was fixed by #21289
