### ISSUE TITLE
Teleport as SAML IdP

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#18043]
### What

In order to support Azure Portal Access and GCP Web Console access via Teleport Application access in a unified way Teleport should be able to act as IDP  SAML provider allowing to add Azure and GCP Teleport IdP connector.

Investigate if teleport can leverage [IdP initiated SSO](https://cheatsheetseries.owasp.org/cheatsheets/SAML_Security_Cheat_Sheet.html#unsolicited-response-ie-idp-initiated-sso-considerations-for-service-providers) to simplify UX. 

### Why
Azure Portal Access and GCP console web doesn't provide an ability used in AWS console integration called  Federation Token logging allowing to support AWS web console access. In order to support Azure Portal and GCP Console Teleport as IdP should provide the ability to add integration to Teleport with  Web access to Azure and GCP Web access.

**Comment by dballenger** [comment]
+1  Would love to see this to help manage internal off the shelf apps that don't support JWT auth or other header based auth methods Teleport currently supports.
