### ISSUE TITLE
Newer v9 AMIs use a version of Teleport that rely on an unavailable version of glibc

### ISSUE THREAD

**Issue by fheinecke** [gravitational/teleport#18069]
Expected behavior:
All v9 AMIs should be able to execute `teleport version` without erroring/exiting with error.

Current behavior:
Certain v9 AMIs starting sometime after v9.3.14 have a version of Teleport installed that rely on glibc 2.27, which is not available on the base image (Amazon Linux 2). As a result, executing and Teleport binary (`teleport`, `tctl`, etc.) exits with error code `1`, with message ``teleport: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by teleport)`` printed.

This does not affect AMIs for the latest release of v8, v10, or v11.

Bug details:
- Teleport version: Starting sometime after v9.3.14, confirmed on v9.3.21 and v9.3.22
- Recreation steps:
  * Deploy an EC2 instance with AMI gravitational-teleport-ami-oss-9.3.2 (`ami-0795b11d2b5731966` in us-west-2 for example)
  * Run `teleport version` or any other Teleport command
- Debug logs:
``teleport: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by teleport)``

As a side note we might want to add a provisioner that simply calls `teleport version` to the packer build script so that we can catch/prevent issues like this in the future.

**Comment by r0mant** [comment]
v9 has been EoL for over a quarter now so it's unlikely we'll get to this.
