### ISSUE TITLE
Improve error message when token is missing

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#18071]
If you follow the following instructions on how to join a node to your cluster, you are given the following command to run.

https://goteleport.com/docs/server-access/getting-started/#step-24-add-a-node-to-the-cluster

```
sudo teleport start \
   --roles=node \
   --token=/path/to/token.file \
   --auth-server=tele.example.com:443
```

If the file `/path/to/token.file` is empty, the user gets a cryptic error message:

```
Node failed to establish connection to cluster: missing parameter Token, rpc error: code = Unknown desc = unexpected HTTP status code received from server: 302 (Found); malformed header: missing HTTP content-type. pid:88589.1 service/connect.go:117
```

Improve this error message to something along the lines of: "Node failed to join cluster, the token at /path/to/token.file is empty."

**Comment by stevenGravy** [comment]
@russjones it says this now so this has been addressed I think.

```bash
ERRO [PROC:1]    Node failed to establish connection to cluster: open /tmp/nowhere: no such file or directory. pid:2484.1 service/connect.go:119
ERRO [PROC:1]    Instance failed to establish connection to cluster: open /tmp/nowhere: no such file or directory. pid:2484.1 service/connect.go:119
```
