### ISSUE TITLE
[v.11.0] /docs/pages/installation.mdx

### ISSUE THREAD

**Issue by flybyray** [gravitational/teleport#18099]
## Applies To

The `install-linux.mdx` partial

## Details

on rhel  8.6 `yum-config-manager` will result in error `command not found`

```shell
user@host:~ $ source /etc/os-release
user@host:~ $ echo sudo yum-config-manager --add-repo $(rpm --eval "https://yum.releases.teleport.dev/$ID/$VERSION_ID/Teleport/%{_arch}/stable/v11/teleport.repo")
```

output
```txt
sudo yum-config-manager --add-repo https://yum.releases.teleport.dev/rhel/8.6/Teleport/x86_64/stable/v11/teleport.repo
```

[When accessing https://yum.releases.teleport.dev/rhel/8.6/Teleport/x86_64/stable/v11/teleport.repo](https://yum.releases.teleport.dev/rhel/8.6/Teleport/x86_64/stable/v11/teleport.repo)
```txt
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: rhel/8.6/Teleport/x86_64/stable/v11/teleport.repo
RequestId: 8KZVKVQBVZ5VHNRV
HostId: r7e0ZIQrdgcOBhL2wGoWgwWZWKVagwX3fsnX1djV4S2wU729WchqrTHqrogWYfjgBN79BdVpywc=
```

Error output when using `sudo dnf config-manager --add-repo https://yum.releases.teleport.dev/rhel/8.6/Teleport/x86
_64/stable/v11/teleport.repo` instead:

```txt
Updating Subscription Management repositories.
Adding repo from: https://yum.releases.teleport.dev/rhel/8.6/Teleport/x86_64/stable/v11/teleport.repo
Status code: 404 for https://yum.releases.teleport.dev/rhel/8.6/Teleport/x86_64/stable/v11/teleport.repo (IP: 52.222.214.85)
Error: Configuration of repo failed
```

**Comment by flybyray** [comment]
The better documentation but not referenced seems: https://rpm.releases.teleport.dev/

**Comment by webvictim** [comment]
This is an issue with the way RHEL declares `VERSION_ID` in `/etc/os-release`.

Using a single digit version (i.e. https://yum.releases.teleport.dev/rhel/8/Teleport/x86_64/stable/v11/teleport.repo) will work.

**Comment by ptgott** [comment]
Closing since this partial now includes instructions for getting the major version from `VERSION_ID`: https://github.com/gravitational/teleport/blob/d6ffc0cc389e8013d30b5bbd096e5ae64f5875c4/docs/pages/includes/install-linux-ent-self-hosted.mdx#L37C22-L37C22
