### ISSUE TITLE
`tsh join` requires CTRL-C twice to leave session

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#18090]
Expected behavior:

`CTRL-C` causes the user to leave the session and `tsh` to terminate. If the moderator leaves and the `require_session_join` policy is no longer satisfied then the session is paused/terminated.

Current behavior:

`CTRL-C` causes `Left session` to be printed on the users session, but `tsh` doesn't exit. A second `CTRL-C` is required in order for things to work properly. Until the second `CTRL-C` is entered the `require_session_join` policy isn't evaluated again. 

```
tsh join -l alice -m moderator ee7afae9-8a85-44d5-b041-8dc119d7da57
Teleport > Creating session with ID: ee7afae9-8a85-44d5-b041-8dc119d7da57...
Teleport > Controls
  - CTRL-C: Leave the session
  - t: Forcefully terminate the session (moderators only)
Teleport > User hank joined the session.
Teleport > Waiting for required participants...
Teleport > User alice joined the session.
Teleport > Connecting to server01 over SSH
➜  ~ while echo $(date); do sleep 5; done
Wed Nov 2 15:31:07 EDT 2022
Wed Nov 2 15:31:12 EDT 2022
<----------------------------------------------- CTRL-C happened here
Left session.                       
Wed Nov 2 15:31:17 EDT 2022
Wed Nov 2 15:31:22 EDT 2022
```

**Comment by zmb3** [comment]
This has been fixed
