### ISSUE TITLE
`tbot` should mitigate improper or unspecified `--join-method`

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#18124]
### What would you like Teleport to do?

`tbot` should mitigate an improper `--join-method` flag when given a token it cannot possibly use with the chosen (or selected by default) join method.

One possible solution could be token prefixes. These can be enforced purely on the client side, meaning `tctl bots add ...` adds an appropriate prefix to the token when it prints the CLI example. When `tbot` receives a prefixed token, it automatically infers the correct join method and uses it, removing the need for `--join-method` in most cases.

For example:

```
$ tctl bots add test --roles=access
The bot token: secret:abcdef1234567890
This token will expire in 59 minutes.

[...snip...]

Then, run this as the bot user to begin continuously fetching
certificates:

> tbot start \
   --destination-dir=./tbot-user \
   --token=secret:abcdef1234567890 \
   --auth-server=example.com
```

(alternately, it might print `iam:foo`, `github:foo`, etc, depending on token type)

If given an unprefixed token, bots can revert to today's existing behavior.

In some sense this is just reencoding an existing parameter, however I think tightly coupling the join method to the token will reduce the chances a join method is accidentally forgotten. In the future we could require token prefixes and remove the default (token) join method behavior entirely, meaning users will never accidentally attempt to join bots with an unexpected join method.

### What problem does this solve?

Currently, if a user attempts to join a bot using an IAM token but forgets to specify `--join-method=iam` (or github, circleci, etc) they might receive a very cryptic error:

```
INFO [TBOT]      Attempting to generate new identity from token tbot/renew.go:454
INFO [AUTH]      Attempting registration via proxy server. auth/register.go:187
INFO [AUTH]      Attempting registration with auth server. auth/register.go:187
WARN [AUTH]      Joining cluster without validating the identity of the Auth Server. This may open you up to a Man-In-The-Middle (MITM) attack if an attacker can gain privileged network access. To remedy this, use the CA pin value provided when join token was generated to validate the identity of the Auth Server. auth/register.go:343
ERROR: this token is only valid for the IAM join method but the node has connected to the wrong endpoint, make sure your node is configured to use the IAM join method, invalid character '<' looking for beginning of value
```

### If a workaround exists, please include it.

Specify the correct `--join-method` parameter.

**Comment by strideynet** [comment]
As of Teleport 14, `--join-method` is now a required parameter and therefore this issue is resolved.
