### ISSUE TITLE
Reevaluate the organization of "Try out Teleport" and "Deploy a Cluster" guides and include a Linux server "try out" guide

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#18127]
Expected behavior:

In this section:

https://goteleport.com/docs/try-out-teleport/

There is no Linux Server option any more. Given that's one of the most popular options we should bring it back.

Teleport 9.0 had it running:

https://goteleport.com/docs/ver/9.0/getting-started/linux-server/

Also I found that `installation` section https://goteleport.com/docs/installation/ is missing any guides on how to get started. E.g. you have installed helm and there is no continuation to the next steps.

Let's fix this, I think this has big impact on our adoption numbers

**Comment by ptgott** [comment]
The docs reorganization that took place earlier this year (https://github.com/gravitational/teleport/pull/15357) assumed that guides in `/docs/try-out-teleport` would be purely local and meant for seeing Teleport's value as quickly as possible with minimal setup, while guides in `/docs/deploy-a-cluster` would apply to a user's infrastructure and introduce Teleport's three editions. 

This change moved the Linux Server guide to `/docs/deploy-a-cluster/open-source/`.

I think it makes sense to reevaluate the content that belongs in `/docs/try-out-teleport` and include something like our  Linux Server guide, but we should include a version of the guide that emphasizes seeing what Teleport can do versus how to prepare your infrastructure (e.g., setting up DNS), install, and configure Teleport, which for me is the focus of the Linux Server guide.
