### ISSUE TITLE
Adding server from WEB UI, `install-node.sh` script should install teleport from pkg repos using the system package manager for easier maintenance

### ISSUE THREAD

**Issue by KasperSkytte** [gravitational/teleport#18145]
When adding a node/server using the install script `sudo bash -c "$(curl -fsSL https://teleport.example.com/scripts/<token>/install-node.sh)` from the WEB UI it installs teleport on the node with the same version as the auth server. In my case, when I run Debian-based OS everywhere, I would have thought it would add the APT repo and install from there instead of pulling a specific version from a `.deb` package. Is there a reason why it doesn't use an APT repo for installation?

Specifically when [upgrading teleport](https://goteleport.com/docs/management/admin/upgrading-the-teleport-binary/) it's much more convenient just running `sudo apt-get upgrade teleport` and restart the service. Right now it's a hassle upgrading teleport on multiple nodes when upgrading the auth server, at least to a newer major version.

**Comment by webvictim** [comment]
Agreed, the script should use the APT/YUM repos where possible to make upgrades easier.

**Comment by pnunn** [comment]
Yes please. Just about to try and update 50 odd servers, and its going to be painful to do by the looks.

**Comment by tukusejssirs** [comment]
Moreover, I think that if Teleport is installed from APT/YUM repos, the script should not require the users to uninstall them first. It should upgrade `teleport` package and continue with Teleport node configuration.

**Comment by webvictim** [comment]
@marcoandredinis I think this has been done now? Last I saw, the script uses APT/YUM repos where possible.

**Comment by marcoandredinis** [comment]
They should, yeah :+1: 

There's a new request for another package manager (zypper/suse) but that has its own issue
