### ISSUE TITLE
Azure PostgreSQL and MySQL Flexible Server support

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#18158]
## What 

Add support for Azure Flexible Server connection PostgreSQL and MySQL using ADD.
- https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-azure-ad-authentication
- https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-azure-ad-authentication

## How
According to the docs: 
> Azure Active Directory authentication supports the following methods of connecting to a database using Azure AD identities:
> * Managed Identity
> Once you have authenticated against the Active Directory, you then retrieve a token. This token is your password for logging in.

 Managed Identities can be used to obtain an access token for a particular managed Identities that will allow for distinguishing particular db users.  

The  [GetAzureIdentityResourceID](https://github.com/gravitational/teleport/blob/bea2e89df5f1313c3b92f0406b21a71896c8a38d/lib/srv/db/common/auth.go#L668) function can be reused to get user assigned manage Identities to a Azure VM instance where  [github.com/Azure/azure-sdk-for-go/sdk/azidentity](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.1.0) library provides a method to get an access token. 

Split: 
- [x] Azure PostgreSQL Flexible Server Integration
- [x] Azure MySQL Flexible Server Integration

**Comment by MattiasAng** [comment]
@smallinsky Do you think this will make it in to version 12 since you are focusing on Azure?

**Comment by smallinsky** [comment]
Yes. We will probably take a look at this before 12 release.

**Comment by GavinFrazar** [comment]
Closing this as complete as the only remaining work is docs update and we are tracking that in #20046
