### ISSUE TITLE
Trusted Clusters support broken between Teleport 9.3.x and Teleport 8.3.x

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#18171]
Tested with clean install of Teleport 9.3.22 (root) and Teleport 8.3.21 (leaf).

* Launch the Web UI.
* Navigate to the leaf cluster (in the screenshot that is `remote.example.com`).
* You will see the following error in the Web UI: "resource type node does not support pagination".

<img width="864" alt="image" src="https://user-images.githubusercontent.com/5017502/200065598-cf90b476-010d-44ba-80cb-e94e0bf0cff1.png">

**Comment by r0mant** [comment]
@kimlisa Can this be closed now?
