### ISSUE TITLE
Enable PIV support in docker release

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#18176]
PIV support requires that the `piv` build tag is included and that the static `libpcsclite` library is available at build time. Currently, this is only included in the standard binary releases that use the Centos7 buildbox.

It's not clear to me how we want to approach this, whether it's using the Centos7 buildbox for docker releases, or adding the static `libpcsclite` library to other buildboxes.

[#dev-teleport-support thread](https://gravitational.slack.com/archives/C01TYKHFVTQ/p1667576739547869)  for context

**Comment by Joerger** [comment]
@tcsc @r0mant when you get a chance, let me know how we want to proceed.

**Comment by r0mant** [comment]
@Joerger What do you mean by "docker releases"? For arm builds we are migrating to use CentOS 7 buildbox too: https://github.com/gravitational/teleport/issues/16356. Are there any other builds that are missing this feature currently?

**Comment by Joerger** [comment]
I mean the quay.io images used for helm. And it's excluded from fips builds as well.
