### ISSUE TITLE
tbot CLI errors out with any command

### ISSUE THREAD

**Issue by Arsenikki** [gravitational/teleport#18210]
After a fresh install of the teleport CLI tools, 'tbot' command fails to provide output or guidance of what kind of configuration is required to be able to run the commands. This currently seems to affect any command that I execute, even the 'tbot version' command.

Expected behavior:
'tbot version' prints out the version

Current behavior:
'tbot version' command errors out with following output: 

```
$ tbot version
ERROR: validating merged bot config
strconv.ParseInt: parsing "16.3": invalid syntax
```

Additional details:

This behavior has been observed on two different machines running Ubuntu on WSL2, as well as within a teleport container.

Repro steps using Docker:

```
$ docker run -it --entrypoint ./usr/local/bin/tbot public.ecr.aws/gravitational/teleport:11.0.1 version
ERROR: validating merged bot config
strconv.ParseInt: parsing "16.3": invalid syntax
```

**Comment by Arsenikki** [comment]
Thanks for getting back so quickly!

I'm facing the issue with following setup:

- Windows 10 20H2 Buld 19042.2132
- WSL2 running Ubuntu 20.04 LTS
  - Kernel 5.10.102.1 
- Docker Desktop 4.13.1 (90346)
- Docker version 20.10.20, build 9fdeb9c

After trying to redo the machine-id steps I noticed that the output changed slightly in within both WSL2 and inside Docker (`parsing "102.1"` compared to `parsing "16.3"` in the initial post). This to me would also indicate that there is something interesting happening in WSL2/kernel, and no issue with my local teleport configs.

```
docker run -it --entrypoint ./usr/local/bin/tbot public.ecr.aws/gravitational/teleport:11.0.1 version
ERROR: validating merged bot config
strconv.ParseInt: parsing "102.1": invalid syntax
```
```
tbot version
ERROR: validating merged bot config
strconv.ParseInt: parsing "102.1": invalid syntax
```

Please let me know if there are other ways I can help.

**Comment by strideynet** [comment]
@Arsenikki - would you be willing to join our community slack so I can ask questions there ? It may be easier to nail this down and get it fixed.

https://goteleport.com/slack/

**Comment by strideynet** [comment]
We've determined that this is caused by the Kernel version name used in WSL:

```sh
➜  ~ docker run -it --entrypoint ./usr/local/bin/tbot public.ecr.aws/gravitational/teleport:11.0.1 -d version

ERROR REPORT:
Original Error: *strconv.NumError strconv.ParseInt: parsing &#34;68.1&#34;: invalid syntax
Stack Trace:
        github.com/gravitational/teleport/lib/utils/kernel.go:68 github.com/gravitational/teleport/lib/utils.kernelVersion
        github.com/gravitational/teleport/lib/utils/kernel.go:46 github.com/gravitational/teleport/lib/utils.KernelVersion
        github.com/gravitational/teleport/lib/tbot/botfs/fs_linux.go:444 github.com/gravitational/teleport/lib/tbot/botfs.HasSecureWriteSupport
        github.com/gravitational/teleport/lib/tbot/config/destination_directory.go:67 github.com/gravitational/teleport/lib/tbot/config.(*DestinationDirectory).CheckAndSetDefaults        github.com/gravitational/teleport/lib/tbot/config/destination.go:38 github.com/gravitational/teleport/lib/tbot/config.(*DestinationMixin).checkAndSetDefaultsInner
        github.com/gravitational/teleport/lib/tbot/config/destination.go:68 github.com/gravitational/teleport/lib/tbot/config.(*DestinationMixin).CheckAndSetDefaults
        github.com/gravitational/teleport/lib/tbot/config/config_storage.go:45 github.com/gravitational/teleport/lib/tbot/config.(*StorageConfig).CheckAndSetDefaults
        github.com/gravitational/teleport/lib/tbot/config/config.go:222 github.com/gravitational/teleport/lib/tbot/config.(*BotConfig).CheckAndSetDefaults
        github.com/gravitational/teleport/lib/tbot/config/config.go:388 github.com/gravitational/teleport/lib/tbot/config.FromCLIConf
        github.com/gravitational/teleport/tool/tbot/main.go:143 main.Run
        github.com/gravitational/teleport/tool/tbot/main.go:47 main.main
        runtime/proc.go:250 runtime.main
        runtime/asm_amd64.s:1594 runtime.goexit
User Message: validating merged bot config
        strconv.ParseInt: parsing &#34;68.1&#34;: invalid syntax
```

```sh
root@fa2e8d1017fb:/# cat /proc/sys/kernel/osrelease
5.15.68.1-microsoft-standard-WSL2
root@fa2e8d1017fb:/#
```

It looks like Microsoft don't use a standard three part semver like the rest of the world does - we'll need to make some adjustments to our kernel version parsing code.
