### ISSUE TITLE
docs: document how to deploy helm charts for a specific major version

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#18304]
Our deployment guides for helm generally say:

```
$ helm repo add <teleport chart URL>
$ helm install
```

This is going to install the latest version.

Instead, we should update this based on the currently selected docs version. If the user is not on the latest version, then we should add the `--version=(=teleport.version=)` flag to the helm install command.

**Comment by rwiteshbera** [comment]
Hi @zmb3, could you please assign me this issue? I want to work on it.
