### ISSUE TITLE
EC2 auto-discovery should import discovered instances' labels

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#18329]
Teleport nodes running on EC2 instances can automatically import labels using metadata endpoint but some users disable the metadata endpoint but still would like to import tags.

Our EC2 auto-discovery feature fetches all instances via API so there's no reason it can't pass their labels to the install script.

**Comment by r0mant** [comment]
@EdwardDowling Implementation plan:

1. Add new DiscoveredServer resource
2. Update watcher to save DiscoveredServer from DescribeInstances
3. Update GetServerInfo for nodes to include AWS metadata (accID, instID)
4. Update auth heartbeat to replace labels for nodes that have DiscoveredServer
5. Update watcher to reconcile labels for existing nodes if they changed

**Comment by espadolini** [comment]
How does the node end up knowing its own overridden labels?

**Comment by r0mant** [comment]
This was a part of the agentless RFD @lxea linked in the comment above, we can probably move that part into a separate RFD if you think it's worth it, or expand it in that RFD.
