### ISSUE TITLE
`TestDatabaseRootLeafIdleTimeout/root_role_with_idle_timeout` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#18357]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/81ccd415-95ed-4224-ba5d-df9979643348?project=ci-account

#### Relevant snippet

```
    --- FAIL: TestDatabaseRootLeafIdleTimeout/root_role_with_idle_timeout (1.30s)
    helpers.go:260: event type "client.disconnect" not found after 1s
```

**Comment by tigrato** [comment]
Another failed run: https://console.cloud.google.com/cloud-build/builds/d60d6a52-5eca-481e-9b00-d2e6b64f86ea?project=ci-account

**Comment by Tener** [comment]
```
    helpers.go:281: event type "client.disconnect" not found after 1s
    --- FAIL: TestDatabaseRootLeafIdleTimeout/root_role_with_idle_timeout (1.51s)
```

Another instance: https://github.com/gravitational/teleport/actions/runs/5162756153/jobs/9300668031#step:6:1787

**Comment by Tener** [comment]
https://github.com/gravitational/teleport/actions/runs/5977458660/job/16217484614

**Comment by zmb3** [comment]
https://github.com/gravitational/teleport/actions/runs/5980777628/job/16227574722

**Comment by zmb3** [comment]
@smallinsky can you have a look on Monday? this one seems to have gotten much worse _today_, so maybe a very recent change.
