### ISSUE TITLE
Server Access - ctrl+c status 130

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#18478]
Expected behavior:
For the session to terminate properly. 

Current behavior:
If the last thing you do in an ssh session is a `ctrl+c` and then `exit` you will get `ERROR: Process exited with status 130`

Bug details:
- Teleport version 11.0.1
- Recreation steps Login to an server node (UI or CLI), press ctrl+c, type `exit`
- Debug logs

**Comment by zmb3** [comment]
I think this just bash behavior and not a bug. 

See: https://unix.stackexchange.com/questions/99112/default-exit-code-when-process-is-terminated

SIGINT (ctrl+c) is 2, and bash adds 128.

Here's an example of the same behavior without Teleport involved and using OpenSSH to connect to a Linux server:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/7527103/209010710-f0fa88c7-6bec-4a01-ad5a-59b9736efa11.png">
