### ISSUE TITLE
Azure and Etcd support on Helm chart

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#18483]
Currently, teleport helm deployment does not include etcd deployment or any support for Azure. The only way to deploy teleport on azure AKS is by using the custom chart and manually creating a config map.

It would be nice to have Azure deployment mode on the helm chart which will deploy etcd and configure the etcd configurations.

**Comment by hugoShaka** [comment]
The chart now has postgres on azure support, and can be configured to use etcd with `auth.teleportConfig`.
