### ISSUE TITLE
Indicate grep and ggrep commands to Create Join Tokens depending on machine

### ISSUE THREAD

**Issue by gaille-teleport** [gravitational/teleport#18517]
## Applies To
[Server Access Getting Started Guide - Step 2/4 - Create a join token](https://goteleport.com/docs/server-access/getting-started/?scope=cloud#step-24-add-a-node-to-the-cluster)

## Details
`sudo tctl tokens add --type=node | grep -oP '(?<=token:\s).*' > token.file` assumes the installation is being done on a Linux machine with GNU grep. 

`grep -P` doesn't exist for `grep` on MacOS, so for Teleport users installing on Mac, it may be good to annotate that they will need to `brew install grep` and use `ggrep` during this step, so that the command looks like this: `sudo tctl tokens add --type=node | ggrep -oP '(?<=token:\s).*' > token.file`

**Comment by zmb3** [comment]
At some point we talked about a `--format=token` or `--format=raw` option that would print only the token. I can't find the original discussion, but that's probably the best approach, then there's no need for grep at all.

**Comment by ptgott** [comment]
Closing because we no longer pipe `tctl tokens add` commands into `grep` in the docs:

```
$ grep -Rn "tctl tokens add.*grep" docs/pages
$ echo "$?"
1
```
