### ISSUE TITLE
Desktop Directory Share - downloaded zip files from remote Desktop to client is corrupt 

### ISSUE THREAD

**Issue by igontaric** [gravitational/teleport#18534]
Expected behavior:
The Downloaded file via Directory Share should not be altered.

Current behavior:
When a zip file from the remote Desktop is moved into the Teleport Mapped Drive, it sends with a delay and after it's sent in the client the file shows the same size as original but its content is altered (different hash). It seams to work with text files but NOT binary files. 
Note: upload of zips from client to remote Desktop via Shared Drive is working fine

Bug details:
- Teleport version: 11.0.1
- Recreation steps:
1. Connect to a Desktop via teleport (web UI)
2. create a zip file of an executable ~3MB in size
3. Share a local folder on client machine with Remote Desktop for Share Directory function (top right side of the teleport remote desktop screen
4. copy the zip with executable to the teleport mapped drive created by Share Directory functionality
The File is copied with a delay but it is copied
5. Extract on the client machine the executable
6. extraction doesn't work, an error is shown indicating a corrupt zip file
- Debug logs
Could not find any...

**Comment by ibeckermayer** [comment]
Discovered that this is problem for raw executables (.exe) as well as zipped executables, and seeing as zipped text files work fine, it appears the problem is with executables, and the zippedness is only incidental.

**Comment by ibeckermayer** [comment]
Thanks for the bug report @igontaric. 

It turns out the problem wasn't with binary or zip files per say, but with large files in general. It's a simple fix, but took some experimentation to track down, see https://github.com/gravitational/webapps/pull/1382 for a technical explanation.

**Comment by igontaric** [comment]
Hi @ibeckermayer,
Thank you so much for the fix, will upgrade as soon as a release is available with this fix. As we consider using teleport in prod as well, it's good that the support of the product is fast. 
I shared my good opinion regarding the product with some leading IT's from other large companies :) pls don't let me down.
Good luck!

**Comment by ibeckermayer** [comment]
@igontaric the fix should be there in the next minor release

**Comment by igontaric** [comment]
Thank You, @ibeckermayer 
Eagerly waiting for 11.1.3 :)
