### ISSUE TITLE
Expose MOTD Settings in Helm

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#18569]
**What would you like Teleport to do?**
Allow configuration of MOTD in the values.yaml

**What problem does this solve?**
Customers do not want to fork the helm chart to add a MOTD

**If a workaround exists, please include it.**
n/a

**Comment by hugoShaka** [comment]
Closed in v12 since this can be configured through `auth.teleportConfig.auth_service.message_of_the_day`
