### ISSUE TITLE
Show Cloud-specific content in the configuration reference

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#18584]
## Applies To
`docs/pages/reference/config.mdx`

## Details
The configuration reference shows all possible fields within the Teleport configuration file, making no distinction between fields that are available in Teleport Cloud and fields that apply only to self-hosted clusters. Let's find a clearer information architecture for the configuration reference.

See #14730 for an example of what this issue wants to achieve.

## Related Issues
N/A

**Comment by russjones** [comment]
Until we have official documentation, I create a GitHub Discussion that we can point customers to with a list of resources that can be used to configure Teleport Cloud.

https://github.com/gravitational/teleport/discussions/19467

**Comment by ptgott** [comment]
#21594 makes it more explicit which config reference sections are irrelevant for Teleport Cloud, so I think we can close this one.
