### ISSUE TITLE
Question: Can Teleport work without the Linux user account existing

### ISSUE THREAD

**Issue by jaxxstorm** [gravitational/teleport#1858]
It's been a while since I've used teleport in anger.

Is it possible to SSH to a machine if the Linux user accont doesn't exist already? Or does the box need some kind of LDAP/local user created?

**Comment by klizhentas** [comment]
> It's been a while since I've used teleport in anger.

in anger? :)

> Is it possible to SSH to a machine if the Linux user accont doesn't exist already? Or does the box need some kind of LDAP/local user created?

Yeah, you have to have a user created first. 2.6.0 has pam support, so technically you can use PAM module that creates home dir for that purpose.

**Comment by jaxxstorm** [comment]
@klizhentas sounds interesting, can you elaborate a bit?

**Comment by russjones** [comment]
This is supported now, https://gravitational.com/teleport/docs/features/ssh_pam/
