### ISSUE TITLE
[Docs] https://github.com/gravitational/teleport/tree/master/assets/aws - missing guide from Docs

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#18600]
## Applies To
In our AWS AMI info here - https://github.com/gravitational/teleport/tree/master/assets/aws - it references an AMI Guide within our Teleport docs as listed here: https://goteleport.com/docs/aws_oss_guide/#single-oss-teleport-amis-manual-gui-setup - but this returns a 404. 

Searching old docs and such I'm not finding this old guide.

## Details
Need to update the repo to remove or fix the link.

Search doesn't return anything either.

**Comment by AzimWarsii** [comment]
Hey I'm willing to work on this issue

**Comment by ptgott** [comment]
The bad link was added in 08551e36baf. At that commit:

```
$ find ./ -name "*aws_oss*"
.//docs/4.2/aws_oss_guide.md
.//docs/4.1/aws_oss_guide.md
.//docs/4.0/aws_oss_guide.md
```
