### ISSUE TITLE
[v.11.0] /docs/pages/try-out-teleport/local-kubernetes.mdx

### ISSUE THREAD

**Issue by jamestexas** [gravitational/teleport#18622]
## Applies To

- https://goteleport.com/docs/try-out-teleport/local-kubernetes/#expose-the-proxy-service-to-your-local-machine

## Details
Describe the documentation improvements you wish to see.
- When going through this, `kubectl get pods` did not show my pod running until _after_ I ran the [minikube tunnel command](https://goteleport.com/docs/try-out-teleport/local-kubernetes/#expose-the-proxy-service-to-your-local-machine). This was due to the following:
```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  2m2s  default-scheduler  Successfully assigned teleport-cluster/teleport-cluster-6c6985b884-qqxtv to minikube
  Normal   Pulling    2m1s  kubelet            Pulling image "public.ecr.aws/gravitational/teleport:11.0.3"
  Warning  Failed     2s    kubelet            Failed to pull image "public.ecr.aws/gravitational/teleport:11.0.3": rpc error: code = Unknown desc = context deadline exceeded
  Warning  Failed     2s    kubelet            Error: ErrImagePull
  Normal   BackOff    2s    kubelet            Back-off pulling image "public.ecr.aws/gravitational/teleport:11.0.3"
  Warning  Failed     2s    kubelet            Error: ImagePullBackOff
```

- Running the curl command required the addition of `--proxy-insecure` in order for it to load on my end. The escapes for `EXTERNAL_IP` did not work for me either (I am using zsh locally on an intel Mac).

```shell
└> curl --insecure -v https://$\{EXTERNAL_IP\?\}:443/webapi/ping 
* Could not resolve host: $EXTERNAL_IP
* Closing connection 0
curl: (6) Could not resolve host: $EXTERNAL_IP
```

This works for bash / sh / zsh, though I can't speak to the portability of other shells:

```shell
$SHELL -c "curl --insecure --proxy-insecure https://${EXTERNAL_IP?}:443/webapi/ping"
```

The "Copy all" buttons on the code blocks also copies the output from said commands. This is kinda inconvenient, and granted there is "copy line" button. I mention it because I expect "copy all" to copy (all) the command(s) present and not the output, too.

**Comment by ptgott** [comment]
Closing because we're removing this guide as part of our efforts to simplify the getting started experience (https://github.com/gravitational/teleport/pull/25415). For running Teleport on a small-scale Kubernetes cluster, I'd recommend following this guide: https://goteleport.com/docs/deploy-a-cluster/helm-deployments/kubernetes-cluster/
