### ISSUE TITLE
Can't SCP/SFTP with Teleport 11

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#18633]
Expected behavior:
that I can transfer files to my hosts

Current behavior:
I can't seem to transfer files post 11.x upgrade, I've a 11.0.3 cluster and I've tried a few hosts but I can't use the transfer options within the app. 
<img width="328" alt="image" src="https://user-images.githubusercontent.com/559288/202835161-8da49d26-1b38-42da-b29a-d1239d5d616d.png">
<img width="295" alt="image" src="https://user-images.githubusercontent.com/559288/202835207-3cdad8d1-f466-4406-ba7f-e1a0aa376881.png">

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by gzdunek** [comment]
I tested it on my local 11.0.3 cluster and it works fine.
When I try `tsh scp` to any server from `teleport-11-ent.asteroid.earth` it fails with the same `ssh: subsystem request failed` error.
@capnspacehook do you have any ideas why this is happening?

**Comment by capnspacehook** [comment]
Turns out a role has the `ssh_file_copy` role option set to `false`, which prevents users with that role from copying files. Unclear whether this role option was set to `false` intentionally or due to a bug. The default should be `true`.

**Comment by capnspacehook** [comment]
https://github.com/gravitational/teleport/issues/15621 also makes this hard to debug

**Comment by benarent** [comment]
Thanks for the debug @capnspacehook, I'm going to close this ticket and keep an eye on my role / options with my Teleport 12 cluster.
