### ISSUE TITLE
License validation is not user friendly

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1865]
## Introduction

When I use an invalid license file [1] for teleport enterprise I get these in my logs:

```
Apr 11 07:07:31 t1-master teleport[4934]: ERRO             "failed to flush events: \nERROR REPORT:\nOriginal Error: *status.statusError rpc error: code = Unknown desc = failed to verify the license\nStack Trace:\n\t/home/ekontsevoy/go/
```

## Problems

1. I do not use `--debug` flag (I am a user). Why is this dumping stack traces into my log?
2. Even if I used `--debug` these log messages are borderline readable. It's a giant single-line string that's tough to read or even copy&paste.
3. And _most importantly_ I still don't know what I (the user) should do. 

## Notes

[1] I used `fixtures/license-enterprise.pem` in the enterprise repo

**Comment by klizhentas** [comment]
I have discovered that there are two separate issues:

* Excessive logging in reporting library that should be tweaked.
* In case if incorrect license signed by unknown cert authority, houston reports:

Code: 500 `{"message":"x509: certificate signed by unknown authority"}`

Houston should respond with protocol error understood by the pro enforcer in this case, then we will get  a proper error message.

**Comment by klizhentas** [comment]
I have addressed the first issue by updating the reporting library to use debug logging instead, and to address the second one I'm moving this ticket to houston.
