### ISSUE TITLE
Add DNS config to helm chart

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#18661]
What would you like Teleport to do?
Add support to add a custom dnsPolicy or dnsConfig block to the spec on our current helm chart.
We should be able to pass YAML block values for these and be able to add them to the pod spec, as so: 
```
spec:
  containers:
    - name: teleport-test
      ...
  dnsConfig:
    options:
      - name: ndots
        value: "1" 
```

What problem does this solve?
Having interaction issue with Teleport and Kubernetes DNS services due to the default Kubernetes resolve.conf settings. `resolve.conf` settings include an `options ndots:5` when teleport is attempting to connect to a configured application, it has the search domain of the cluster applied. The problem is when `Teleport` is configured with `https://name.namespace.svc.cluster.local` as an application target, it does 5 iterative DNS lookups before solving that name. 
e.g.
`name.namespace.svc.cluster.local.svc.cluster.local`
`name.namespace.svc.cluster.local.cluster.local`
`name.namespace.svc.cluster.local.google.internal`
`name.namespace.svc.cluster.local.etc.etc` 

If a workaround exists, please include it.
Normally, the recommendation for a workaround to this issue: 
Add a trailing dot to the DNS name to force it to be treated as a `Full Qualified` name and not have a search path applied, but this doesn't work with Teleport as it starts issuing JWTs that customer backend app now rejects.

**Comment by hugoShaka** [comment]
I wonder if we could just set ndots=1 or 0 for everyone and limit the rube goldberg machine that is DNS resolution in Kubernetes.

I'm not sure this would really be a breaking change for the `teleport-cluster` chart.

The issue with those features is that we eventually end up with a chart that exposes all Kubernetes fields, and becoming almost useless, and even sometimes counter-productive

**Comment by hugoShaka** [comment]
After a [slack discussion](https://gravitational.slack.com/archives/C01TYKHFVTQ/p1669127818097999?thread_ts=1669070457.817229&cid=C01TYKHFVTQ) we concluded that we need to add dnsConfig to the `teleport-kube-agent` chart. We'll hold off the flag now for the `teleport-cluster` chart to limit values.yaml inflation and will re-evaluate if the use-case arises for `teleport-cluster`.
