### ISSUE TITLE
tctl --format=json specified returns null instead of empty document when output has no data

### ISSUE THREAD

**Issue by eric-belhomme** [gravitational/teleport#18672]
When using teleport CLI tools like `tctl` with `--format=json` specifier and the output data is empty (no data) the tools return `null` string instead of an empty JSON document.
This is annoying as I expect JSON document and it fails when I pipe it with `jq`for example...

In the example bellow I use `tctl get locks` as this usually should output no data but I experienced the same behavior with many other like `tctl bots ls`, etc.

Expected behavior:
```bash
[root@server ~]# tctl get locks --format=json
{}
```

Current behavior:
```bash
[root@server ~]# tctl get locks --format=json
null[root@server ~]# 
```

Bug details:
- Teleport v11.0.3 git:v11.0.3-0-g6f0eeef go1.19.2
- any teleport CLI tool (tsh/tctl/tbot) with a command that supports `--format=json` output

**Comment by zmb3** [comment]
Another good candidate for the CLI style guide tracked in #12811

**Comment by zmb3** [comment]
This looks to have been fixed:
```
➜ tctl get locks --format=json
[]
➜ tctl bots ls --format=json
[]
```
