### ISSUE TITLE
Trusted cluster names

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1870]
## Problem

Adding a trusted cluster is a frustrating experience because of how we handle cluster names.

## Steps to reproduce (Web UI)

* Try adding a cluster without specifying name. You get a [strange error](https://github.com/gravitational/teleport/issues/1868), i.e. the name is required. Ok.
* Give it a name, say "foobar"
* You will see a cluster is created.
* Try to delete it.

Now you'll see strange behavior:

* "Are you sure?" popup does not go away.
* There is an error displayed _underneath it_.
* If you cancel the popup, you will discover that the error is "foobar is not found"

That happens because the name of the trusted cluster is IGNORED. We pull the real name from the remote cluster anyway.

## Fixes

* First of all, fix the mechanics of showing errors underneath "Are you sure" dialog. I am sure this affects other errors as well.
* Do not require users to name their clusters! It makes no sense: we insist on providing a name which we throw away. I will remove this requirement from the docs as well. **ping Ev** when this ticket is closed, I will update the docs.
* The web UI should discover the real name of the cluster.

**Comment by alex-kovoy** [comment]
fixed with https://github.com/gravitational/teleport.e/commit/b1f38994277044dd50aa04a3eaf5ab8bb5536e15
