### ISSUE TITLE
Moving Database Auto Discovery to Teleport Discovery Service 

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#18742]
### What

Recently The [Teleport Discovery Service](https://github.com/gravitational/teleport/blob/master/lib/srv/discovery/discovery.go#L83) was introduced where right now discovery service allows to for  [AKS](https://goteleport.com/docs/kubernetes-access/discovery/aws/), [EC2](https://goteleport.com/docs/server-access/guides/ec2-discovery/), [EKS](https://goteleport.com/docs/kubernetes-access/discovery/aws/) Auto Discovery. 

Database Discovery functionality should be extracted from the Database Access code/configuration and moved to the Teleport Discovery Service with preserving backward compatibility.

**Comment by r0mant** [comment]
@greedy52 @smallinsky Can this be closed now?
