### ISSUE TITLE
Write migration guides from old hosted RPM/DEB repos to new hosted YUM/APT repos

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#18753]
## Applies To
https://goteleport.com/docs/installation/

## Details
As we're deprecating the old RPM/DEB repos in Teleport v11 (as per [changelog](https://goteleport.com/docs/changelog/#deprecated-old-debrpm-repositories)) we should write migration guides detailing how to move from:
- `rpm.releases.teleport.dev` --> `yum.releases.teleport.dev`
- `deb.releases.teleport.dev` --> `apt.releases.teleport.dev`

## Related Issues
#9770

This isn't a very involved process for an experienced sysadmin, but I think we should do a little better than putting a message in the changelog saying "we will be removing the old repos in a future release" without detailing exactly how to move from the old repos to the new repos.

**Comment by ptgott** [comment]
Closing since v11 has been out of support for a few major versions now.
