### ISSUE TITLE
How to specify a trusted cluster for OSS version?

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1876]
## Problem

Our OSS documentation for trusted clusters is no longer valid.
If you follow [this tutorial](https://gravitational.com/teleport/docs/admin-guide/#example-configuration) you will get an error:

> missing 'role_map' parameter: missing 'role_map' parameter

How is this supposed to work? OSS does not have roles.

@klizhentas ping me

**Comment by klizhentas** [comment]
make sure you are using tctl + auth server of the OSS version, should work

**Comment by kontsevoy** [comment]
user error :)
