### ISSUE TITLE
mongo-driver v1.11.x breaks support for MongoDB <= v3.6

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#18777]
At the moment, it's not possible to update go.mongodb.org/mongo-driver past v1.10, as v1.11 deprecates MongoDB <= v3.6.

We need a way forward, lest we hit a situation where a newer driver is needed but the only way to update is to drop support for older clients.

Original context: https://github.com/gravitational/teleport/pull/18531#discussion_r1028193936.

**Comment by greedy52** [comment]
Older mongo support will be dropped in v14:

- https://github.com/gravitational/teleport/pull/29745
- https://github.com/gravitational/teleport/pull/27429
