### ISSUE TITLE
Linux Browsers not showing _ char in ssh session

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#18784]
Expected behavior:

Chars such as `_` are visible within a web ssh session.

Current behavior:

Running `echo hello_world` looks like this.  
<img width="160" alt="image" src="https://user-images.githubusercontent.com/60704961/204017488-ca11a711-c72b-4216-9aae-d99fad0922e8.png">

Bug details:
- Teleport version: 11.0.3
- Recreation steps
Start a browser session in a Linux env (firefox or google chrome) such as Ubuntu 22.04

**Comment by webvictim** [comment]
Pretty sure this is a Linux desktop font rendering issue :(

Apparently if you zoom in many levels, the `_` is there but very thin.

**Comment by voidburn** [comment]
110% (first zoom level) makes it appear, albeit very thin and barely visible. 

I have past experience with low level glyph rendering in OpenGL / Vulkan from true type and bitmap fonts, and I can tell the the problem with the `_` character on the current font is that the `descent` of the glyph is pushed so low, or the line is so thin, that it either incurs in rounding issues or falls outside the `line height` boundaries.

The proper and faster solution would be to find a font that does not trigger the problem, or patch the current one manually to adjust the descent/ascent parameters for the `_` character and see if that is enough.

See pictures below for reference on the positioning of the character:

100% 
![image](https://user-images.githubusercontent.com/1438321/204028512-99858362-3951-405c-b84f-0998f2be8ede.png)

110% (1 step)
![image](https://user-images.githubusercontent.com/1438321/204028572-c9bc345c-6f3e-4b91-8a55-f4f74dcc6ca1.png)

200%
![image](https://user-images.githubusercontent.com/1438321/204028697-44757c65-787b-4ad7-86a3-1814479d76ab.png)

**Comment by zmb3** [comment]
There's lots of discussion on this issue upstream on the xterm.js repo. 

Let's start by updating xterm (at least to the latest 4.X version, if not v5) and seeing if that fixes the issue before we try to change fonts.

**Comment by voidburn** [comment]
I dug up some oldies, in case any discussion in there can inform decisions in this regard:

https://bugs.chromium.org/p/chromium/issues/detail?id=41457
https://bugs.chromium.org/p/chromium/issues/detail?id=1190216
