### ISSUE TITLE
Automate adding servers

### ISSUE THREAD

**Issue by ben-z** [gravitational/teleport#18793]
What would you like Teleport to do?

Have a way to enable adding servers (nodes) automatically. e.g. a persistent key that we can save in CI to automatically install Teleport onto all nodes in a cluster.

What problem does this solve?

AFAIK, currently, we need to manually run the `install-node.sh` script obtained from the Web GUI to add nodes. This alleviates that need.

If a workaround exists, please include it.

N/A

**Comment by zmb3** [comment]
This is coming in the Teleport Discover project.

Since we already have a number of issues tracking that work, I'm going to close this one. Feel free to follow along by watching issues with the `discover` label.
