### ISSUE TITLE
Web UI improvements: nodes list

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1879]
None of these are bugs, but implementing these would make user's life a lot more pleasant:

## Login box

The web UI has a login box which is much more convenient to use if you already know the host you want to connect to. The following improvements would make it much nicer (sorted by priority):

* It's too narrow. Needs to be 50% wider to accommodate most production server names I have used. Lets make the entire row of controls wider and give all extra pixels to this control.
* It should remember the last thing someone typed. People frequently return to the same server over and over again.
* It would be even nicer if "login" button (on the right) was replaced [1] with a "history" button, i.e. pressing it would reveal a "history dropdown" with the last 10 addresses you've typed. 
* Typing "up" arrow in the box should allow user to go back in time over the previous 10 addresses they typed (i.e. show the same history dropdown)

## Keyboard shortcuts

We have a search box and login box. Both have tooltips and they're nice. Would be super convenient if tooltips should show a keyboard hotkey to move to focus to these controls, for example:

* Login to SSH node (l)
* Filter the node list (s)

## Default Focus

By default we place the focus on "search". We need to stop doing this because it will prevent hotkeys from working. Searching hosts isn't something people exect/used to. 

## User Experience Scenarios

The following should be possible:

0. A user opens "hosts" page.
1. A user presses "l", types `user@host` and hits "Enter" -> logs into the host
2. A user presses "l" and immediately hits "Enter" -> goes to the same host because its address was preserved in the login box from the previous step.
3. A user presses "l" and types "user@db" and hits "Enter" -> goes to DB
4. A user presses "l", hits "up" and hits "Enter" once -> goes to DB again
5. A user presses "l", hits "up" and changes "db" to "host" -> goes to "host"

[1] Login button is redundant, people are already trained to press "Enter" to login (or to search)

**Comment by alex-kovoy** [comment]
closed with https://github.com/gravitational/teleport/commit/d5a5d68210834bca519d0f76a62f2abc53abf471
