### ISSUE TITLE
MAC OS: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by shiftedreality** [gravitational/teleport#1880]
**What happened**:
Running `tsh --proxy=some:port --user=username login` throws error

```
A fatal error occurred: invalid character '<' looking for beginning of value
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.5.6
- Tsh version (use `tsh version`): Teleport v2.5.6
- OS (e.g. from /etc/os-release): MAC OS 10.13.4

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
```
ERROR REPORT:
Original Error: *json.SyntaxError invalid character '<' looking for beginning of value
Stack Trace:
	/private/tmp/teleport-20180410-94599-7rktia/teleport-2.5.6/src/github.com/gravitational/teleport/lib/client/weblogin.go:332 github.com/gravitational/teleport/lib/client.Ping
	/private/tmp/teleport-20180410-94599-7rktia/teleport-2.5.6/src/github.com/gravitational/teleport/lib/client/api.go:1081 github.com/gravitational/teleport/lib/client.(*TeleportClient).Login
	/private/tmp/teleport-20180410-94599-7rktia/teleport-2.5.6/src/github.com/gravitational/teleport/tool/tsh/tsh.go:329 main.onLogin
	/private/tmp/teleport-20180410-94599-7rktia/teleport-2.5.6/src/github.com/gravitational/teleport/tool/tsh/tsh.go:260 main.Run
	/private/tmp/teleport-20180410-94599-7rktia/teleport-2.5.6/src/github.com/gravitational/teleport/tool/tsh/tsh.go:146 main.main
	/usr/local/opt/go/libexec/src/runtime/proc.go:207 runtime.main
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2362 runtime.goexit
```
- teleport --debug

**Comment by klizhentas** [comment]
it seems more like your proxy is behind some sort of load balancer that responds HTML instead of json. Can you double check that the curl on the proxy side responds with teleport actually and not nginx for example.

**Comment by shiftedreality** [comment]
Yes, server side was not working with version > 1.3.2.
Thanks, closed.

**Comment by klizhentas** [comment]
No prob, feel free to ping us if you need any other help! Thanks for trying Teleport.
