### ISSUE TITLE
Add example use of `tsh ls -R` using Go API

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#18820]
Write an example of calling `tsh ls -R` using our Go API. The application should connect to a root cluster, fetches all trusted clusters, and then iterates over them and fetches all nodes for each cluster, and outputs them in a json/yaml format.

The documentation should be added under https://goteleport.com/docs/api/introduction/ (create a new tab called Examples)

**Comment by zmb3** [comment]
@jakule can I close this?
