### ISSUE TITLE
Machine ID GitHub Actions instructions resulting in errors

### ISSUE THREAD

**Issue by lucasmellos** [gravitational/teleport#18856]
## Applies To

https://goteleport.com/docs/machine-id/guides/github-actions/

## Details
The listed Action file has some path errors, Teleport has no permission to write on <code>/opt</code> and it doesn't match with <code> tsh -i ./opt/machine-id/identity</code>

The fetch credentials task should be something like

```yaml
- name: Fetch credentials
       run: >
         tbot start
         --join-method=github
         --token=github-token
        --ca-ping=sha256:<hash from tctl status command>
# Use the address of the auth/proxy server for your own cluster.
         --auth-server=example.domain:443
         --oneshot
         --destination-dir=./opt/machine-id
         --data-dir=./opt/machine-id-data
```

Adding a dot before <code>./opt/</code> on destination-dir and data-dir.

Also, there isn't a relation to ca-pin when running <code>tbot start</code>. Running it without --ca-pin throws 
```
Joining cluster without validating the identity of the Auth Server. This may open you up to a Man-In-The-Middle (MITM) attack if an attacker can gain privileged network access. To remedy this, use the CA pin value provided when join token was generated to validate the identity of the Auth Server. auth/register.go:412
```

That's why I suggest adding --ca-pin to tbot start command.

**Comment by strideynet** [comment]
As for the CA Pin, this is only needed when directly connecting to an auth server rather than via a proxy - we should add some words to that effect.

**Comment by strideynet** [comment]
> https://goteleport.com/docs/machine-id/guides/github-actions/

Interesting, are you doing anything else that would modify the user or directory permissions ? I had no issues using `/opt` with `ubuntu-latest` - but I'll retest tonight to confirm.

**Comment by strideynet** [comment]
This will be covered by https://github.com/gravitational/teleport/issues/19112
