### ISSUE TITLE
Update Yum install command

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#18888]
## Applies To
https://goteleport.com/docs/server-access/getting-started/#step-14-install-teleport-on-your-linux-host

## Details
The customer is using a custom script that defaults to `no` when asked for GPG key 
```
Is this ok [y/d/N]:
```
By default, the script will default to `no` causing the installation to fail. The customer would like to suggest we add a `y` flag to the `yum` command to default to `yes` instead. 

```
sudo yum install teleport -y
```

**Comment by zmb3** [comment]
I'm not sure that updating our docs to accommodate a custom script is the right approach here. It sounds like the docs are fine as-is, and if you create custom scripts based on the info there it is expected that you might have to make some adjustments.
