### ISSUE TITLE
Allow disabling automatic tags for nodes in cloud providers

### ISSUE THREAD

**Issue by wlopes39** [gravitational/teleport#18881]
Possibility to disable the function

https://github.com/gravitational/teleport/pull/16218

https://github.com/gravitational/teleport/pull/12593

**Comment by williammpe** [comment]
I'm same problem.
How to disable automatic tags?

**Comment by LamNapp** [comment]
Interesting subject, I would like to know how to resolve this issue as well.

**Comment by zmb3** [comment]
Duplicate of #17102
