### ISSUE TITLE
`TestAuthSignKubeconfig` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#18882]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/0ef11edb-53c4-4d0a-ac3f-ccd248fe6cd7?project=ci-account

#### Relevant snippet

Timeout failure

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/0f8dbca5-f0c2-4b1d-b7ef-6b613e9e6082?project=ci-account

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/86607fc6-a517-4ea6-9fee-d0d4cf2eaf4f?project=ci-account

**Comment by ibeckermayer** [comment]
The flakes in https://github.com/gravitational/teleport/issues/17989 are also this same problem

**Comment by zmb3** [comment]
No recent occurrences - closing.

**Comment by r0mant** [comment]
Two occurrences in the past week:
https://github.com/gravitational/teleport/actions/runs/4811149864
https://github.com/gravitational/teleport/actions/runs/4798861827

**Comment by zmb3** [comment]
Another one: https://github.com/gravitational/teleport/actions/runs/4812353510/jobs/8567494931
