### ISSUE TITLE
Corrupted session recording files cause massive spike in CPU usage

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#18936]
Expected behavior:

Corrupted session recordings don't impact Teleport.

Current behavior:

Corrupted session recordings are retried over and over again causing a massive spike in CPU usage and the following log line is spamming.

```
{"caller":"filesessions/fileasync.go:252","component":"upload","error":"session file could be corrupted or is using unsupported format: session recording 1234abcd is either corrupted or is using unsupported format, remove the file /var/lib/teleport/log/upload/streaming/default/1234abcd.tar to correct the problem, remove the /var/lib/teleport/log/upload/streaming/default/1234abcd.error file to retry the upload","level":"warning","message":"Skipped session recording 1234abcd.tar.","timestamp":"2022-11-30T07:46:08-06:00"}
```

Proposed Behavior:

Move corrupted sessions to `/var/lib/teleport/log/corrupted/` and stop trying to upload it

**Comment by zmb3** [comment]
I'd propose `/var/lib/teleport/log/upload/corrupted/default/1234abcd.tar` for the corrupted files. It mirrors the existing structure and makes it clear that it's a corrupted upload, since `log` is a pretty generic term.
