### ISSUE TITLE
tctl get clusters OSS UX

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1895]
## Problem

The OSS edition of `tctl get clusters` dumps `role_map` setting for remote clusters. This is confusing to users because it's an RBAC feature which we do not document and it shouldn't be used/touched.

## Solution

There are a few things we can do, but the easiest is probably to filter out `role_map` when a role is dumped via "get" command. Obviously it should continue to work the way it works in the enterprise build.

**Comment by kontsevoy** [comment]
punting

**Comment by zmb3** [comment]
This no longer applies, because RBAC is no longer an enterprise-only feature.
