### ISSUE TITLE
Macos app crashed right after install

### ISSUE THREAD

**Issue by ykshev** [gravitational/teleport#18960]
Expected behavior:
Mac Os app works after installation

Current behavior:
Mac Os app crashes on the first start

Bug details:
- Teleport version: Teleport Connect-11.1.0.dmg
- Recreation steps: Download dmg from the official website, open, copy the app to an app's folder, run the app
- Debug logs:
`Internal Error
Error: Error invoking remote method 'main-process-get-resolved-child-process-addresses': Error: Could not resolve address (unix:///Users/andrei/Library/Application Support/Teleport Connect/shared.socket) for process /private/var/folders/jg/m_h185cd66vf6g8kl2nbp1680000gn/T/AppTranslocation/70209214-A145-4C4D-A13B-804704AB7537/d/Teleport Connect.app/Contents/Frameworks/Teleport Connect Helper.app/Contents/MacOS/Teleport Connect Helper: the process exited with code 1. `
<img width="1168" alt="Screenshot 2022-12-01 at 13 47 32" src="https://user-images.githubusercontent.com/6626711/205033935-35820fb4-5fe5-42b3-b041-1d62deebea40.png">
<img width="392" alt="Screenshot 2022-12-01 at 13 48 30" src="https://user-images.githubusercontent.com/6626711/205033952-a292029d-b3c3-49d5-a86c-ac17fbcfa4fc.png">

**Comment by ravicious** [comment]
This has been fixed in 11.1.1 by #18899. 11.1.1 is now available to download, try it out and please let me know if it fixes the issue for you.

**Comment by ykshev** [comment]
@ravicious 
Yeah, it works, thanks!
