### ISSUE TITLE
Integrated alerts

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#19018]
What would you like Teleport to do?

Provide a notification mechanism that alerts when certain actions take place within the cluster. 

Example actions that could trigger an alert:
- user X connects as root to host foo
- user Y executes an INSERT/UPDATE/DELETE query on any database 

What problem does this solve?

Reduces manual load required to analyze audit logs and provides notifications in real time and not after the fact.

If a workaround exists, please include it.

Analyze audit logs periodically.

**Comment by zmb3** [comment]
The current plan is to integrate this with some built-in reports based on the new audit logger.

(cc @tobiaszheller)

**Comment by zmb3** [comment]
This is deprecated by the security reports feature.
