### ISSUE TITLE
Machine ID: support for Kubernetes joining

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#19019]
### What would you like Teleport to do?

tbot should be able to join using kubernetes provision tokens

### What problem does this solve?

Simpler tbot deployment by joining the teleport cluster automatically via a Kubernetes token.

`tbot` support was removed from [the Kubernetes joinMethod PR](https://github.com/gravitational/teleport/pull/18659#issuecomment-1335295628) because we had no functional test case and the feature was untested

**Comment by strideynet** [comment]
This will be bundled into https://github.com/gravitational/teleport/issues/25543
