### ISSUE TITLE
Add database service heartbeat and web API

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#19032]
To support Discover Day One flow for databases we need to provide ability for the web app to tell whether there's a database service that can proxy the database created by a user. The flow itself works like this:

1. User creates database with some labels.
2. We see if there's already a database service that has resources filter matching this database. <--- currently missing
3. Depending on the outcome, we either show or skip "deploy database service" step.

The problem is that database service itself currently does not heartbeat anything to the cluster. It only heartbeats `DatabaseServer` resources corresponding to each database it is proxying.

So to support this scenarios we'd need to do the following:

- Add a new resource e.g. `DatabaseService` that would represent a database service/agent.
- Make sure database service heartbeats its presence to the cluster as `DatabaseService` resource.
  - It should heartbeat even if it's empty and doesn't have any databases.
- Provide web API that would return `DatabaseService`'s that would match the labels for the registered database.

**Comment by greedy52** [comment]
> - Make sure database service heartbeats its presence to the cluster as DatabaseService resource.
>    - It should heartbeat even if it's empty and doesn't have any databases.

I assume empty here means at the minimum database should have dynamic resource matchers, or no?

https://github.com/gravitational/teleport/blob/afa6077b1d70fc01b5be4c8ca833efbc53ae7076/lib/service/db.go#L32-L40

**Comment by marcoandredinis** [comment]
We only included the ResourceMatchers
We can the others as well if required, should be easy as soon as the last PR merges

**Comment by r0mant** [comment]
@marcoandredinis I think what @greedy52 is saying is that if the database service doesn't have any static databases or any matchers, it won't start and won't be heartbeating back. Which I think is fine for our use-case since it effectively can't be used for anything.
