### ISSUE TITLE
Refresh button on server page

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#19053]
**What would you like Teleport to do?**

The customer would like to have a refresh button for the results of a search on the servers page. When you wait for an instance to appear and you've got a search in place to narrow down the list. Currently, there is no method to refresh the list besides refreshing the entire Teleport page. 

**What problem does this solve?**

This would be useful when waiting for a host to appear

**If a workaround exists, please include it.**

Refresh the entire page.

**Comment by zmb3** [comment]
Duplicate of #4503
