### ISSUE TITLE
DB Access RDS missing permission unambiguous error

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#19098]
### Details:
During RDS access when Teleport DB agent don't have right permission to auth-configure IAM auththe following error is returned: 
```
2022-12-06T12:40:03Z ERRO [IAM]       Failed to auto-configure IAM for Database(Name=mydatabase, Type=rds, Labels=map[teleport.dev/origin:config-file]). error:[
ERROR REPORT:
Original Error: trace.aggregate expect no placeholders but got [{account_id} {resource_id}]
Stack Trace:
github.com/gravitational/teleport/lib/srv/db/cloud/aws.go:114 github.com/gravitational/teleport/lib/srv/db/cloud.(*awsClient).setupIAM
github.com/gravitational/teleport/lib/srv/db/cloud/iam.go:272 github.com/gravitational/teleport/lib/srv/db/cloud.(*IAM).processTask
github.com/gravitational/teleport/lib/srv/db/cloud/iam.go:121 github.com/gravitational/teleport/lib/srv/db/cloud.(*IAM).Start.func1
runtime/asm_amd64.s:1594 runtime.goexit
User Message: expect no placeholders but got [{account_id} {resource_id}]] cloud/iam.go:123
```

## Expected behaviour 
The error message in that case should be more verbose: the ` no placeholders but got [{account_id} {resource_id}]` error is ambiguous  and hides the root cause why IAM auth setup failed.

**Comment by greedy52** [comment]
Good catch. I think this error message definitely needs some clarity. Though it's hard to know the exact cause at this point (at the "IAM" service).

What do you think if we change this message to something like this?
```
database "my-rds" has empty values for [{account_id} {resource_id}]. Please make sure the database agent has the IAM permissions to fetch cloud metadata, or make sure these values are set in the static config.
```
Ideally, we can print out what actual permissions are required for fetching metadata here.

I think another problem (only for this situation) is the `IsAccessDenied` error in "Metadata" service is debug only. Maybe the "IAM" service can call "Metadata" service again but this time propagate the `IsAccessDenied` error?

**Comment by klizhentas** [comment]
As a user who has never seen this error or knows the details of account_id and resource_id, here is what would make it easier for me to understand:

`Could not fetch IAM metadata for database "my-rds". Please make sure the database agent has the IAM permissions to fetch cloud metadata, or make sure these values are set in the static config. Set values for account_id and resource_id.
`
