### ISSUE TITLE
Include more straightforward instructions for production Teleport deployments

### ISSUE THREAD

**Issue by PavelNiedoba** [gravitational/teleport#19107]
## Applies To
https://goteleport.com/docs/management/guides/docker/
## Details

We need simple and straight forward documentation how to run single instance of teleport for production environment. This is only one i found. It should not mention anything like 

`This example command will create a Teleport user called testuser`

`Insecure Certificate Error`

`Accept the Risk and Continue.`

Instead we need to know how to configure domain name, ports on firewall, how to generate and renew certificates

there is https://goteleport.com/docs/deploy-a-cluster/open-source/, but cluster is not what we want (there's only one machine, why do you call it cluster), but I have no idea why do you instruct me to create html page? 

there is docker page https://goteleport.com/docs/try-out-teleport/docker-compose/ but its demo lab, again not what we want, changing image to production one prevents service from starting

improving those pages will improve teleport adoption significantly, now it's a lot of pain and more to come when certificates don't renew and business stops

**Comment by zmb3** [comment]
> how to run single instance of teleport for production environment.

I think you're not seeing much documentation on this because we don't see a single instance deployment as being suitable for a production environment. Single instance deployments are recommended for demos, POCs, or small lab environments.

**Comment by ptgott** [comment]
I think one source of confusion here is that our information architecture around deploying Teleport to production doesn't have a clear path for new users. This is something I'm working on this month:

- #19205 reorganizes some sections of the docs so it's clearer that the Linux Server guide is intended for small-scale demos. I can consider giving the same treatment to our standalone Docker guide. For Kubernetes, we recommend using our Helm charts. I'm not sure how many users are on ECS, but I don't think the Docker guide alone is very useful for that case. Same with Nomad.
- I'm working on building out a general guide to production Teleport deployments in #19217 that will introduce our more specific deployment guides. This needs some substantial edits and a diagram.

**Comment by ptgott** [comment]
Closing since we have overhauled the getting started experience and removed the Docker guide.
