### ISSUE TITLE
Add Machine ID guide showing `gravitational/teleport-actions/auth-k8s` action

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#19113]
Guide should show:

- Creating role with access to a Kubernetes cluster that has already been configured with Teleport
- Creating a bot with access to the above role
- Using `gravitational/teleport-actions/setup` and `gravitational/teleport-actions/auth-k8s` to authenticate with the cluster

Some brief documentation exists at https://github.com/gravitational/teleport-actions#gravitationalteleport-actionsauth-k8s

**Comment by rsyracuse** [comment]
Part of this task will include:

- Creating a warning partial or partials for Github Actions, ensuring that we recommend that users lock their github action workflows to a specific commit hash.
- Creating  a separate sidebar navigation subcategory or subcategories for Github Actions. This will be more descriptive than our current "guides" subcategory.
