### ISSUE TITLE
Generate documentation for `tctl inventory`

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#19129]
## Applies To
https://goteleport.com/docs/reference/cli/#tctl

## Details
It appears there is command `tctl inventory` to list connected resources. However, I'm unable to find documentation for it. 

Note: I am currently hitting issue [18016](https://github.com/gravitational/teleport/issues/18016), so I am unable to determine the expected output to generate the docs. Creating this issue to track and ensure we create documentation when the bug is fixed. 

## Related Issues
- [18016](https://github.com/gravitational/teleport/issues/18016)

**Comment by zmb3** [comment]
This command is intentionally hidden and not documented because it's very much a work in progress and part of an incomplete feature.

https://github.com/gravitational/teleport/issues/17488#issuecomment-1281266660
