### ISSUE TITLE
Allow to add comments to servers (and other services) in web gui

### ISSUE THREAD

**Issue by PavelNiedoba** [gravitational/teleport#19143]
With many servers we need to write comments (free text) visible in web gui. It should be for users convenience only, therefore low risk and low effort. New edit action is needed.

What problem does this solve?
server names are often generic (like docker-worker-12), we need more comprehensive descriptions

There is no workaround now, labels should not be used for this

**Comment by zmb3** [comment]
I would recommend naming the servers with a more descriptive name if the host name is not descriptive enough. You can do this with the nodename config property.
