### ISSUE TITLE
Upgraded node from 9 to 11 and all servers are unreachable

### ISSUE THREAD

**Issue by PavelNiedoba** [gravitational/teleport#19144]
Expected behavior:
Servers should be reachable and easy update process should be in place

Current behavior:
I need to ssh in old fashion way. Teleport is installed by command fro webgui `sudo bash -c "$(curl -fsSL https://teleport.xxxx/install-node.sh)"`  Reinstalling fails with: `Warning: There is already a Teleport config file present at /etc/teleport.yaml.`

I don't want to purge config, i need to preserve it

there is no apt repo so 'apt upgrade' is not helping.

we need upgrade process, ideally it should upgrade with node

Bug details:
- Teleport version 9 and 11
- Recreation steps upgrade node, servers get disconnected

**Comment by zmb3** [comment]
Teleport 11 nodes are not compatible with Teleport 9 auth servers. More information on compatibility and the proper upgrade procedure is available in our public docs: https://goteleport.com/docs/management/operations/upgrading/

**Comment by zmb3** [comment]
Closing this, as there is no bug and you've found yourself in an unsupported scenario.

You're welcome to start a GitHub discussion or join our Slack workspace if you need help or advice for getting back to a good state.
