### ISSUE TITLE
Allow limiting access to the audit log events based on roles

### ISSUE THREAD

**Issue by thg-jonnield** [gravitational/teleport#19140]
**What would you like Teleport to do?**
It would be nice if Teleport allowed for limiting access to audit event entries based on roles.

**What problem does this solve?**
This would allow teams to review audit events limited to just the infrastructure they have access to, eg SSH logins could be reviewed by a team without having access to all SSH login events across the cluster.

**If a workaround exists, please include it.**
This can be achieved by shipping the logs to an external system such as Elasticsearch.

**Comment by zmb3** [comment]
Duplicate of #10405
