### ISSUE TITLE
List SSH sessions in TSH

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#19152]
What would you like Teleport to do?
Ability to `tsh sessions ls` and see active SSH sessions.

What problem does this solve?
Aligns with the ability we have with `tsh kube sessions` and the ability to then join them. 

If a workaround exists, please include it.
Have to pull the session ID from the Proxy UI.

**Comment by zmb3** [comment]
Makes sense to me. I would go so far as to say we should deprecate `tsh kube sessions` in favor of `tsh sessions ls`. The new `tsh sessions ls` command should have a flag for `--kinds`.

**Comment by ekrekeler** [comment]
Bump. Was looking for this functionality today, seems you can only find live SSH sessions in the WebUI. Would be nice to have this available from tsh and other teleport CLI utilities.
