### ISSUE TITLE
Missing docs for `teleport node configure`

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#19167]
## Applies To
https://goteleport.com/docs/server-access/getting-started/#join-your-node-to-the-cluster

## Details
The `teleport start` approach on this page is very outdated. Instructions should be updated to use `teleport node configure` instead which will generate an appropriate config file for an SSH node joining via the proxy.

@hatched wrote the functionality but it never made it into the docs. I used `teleport node configure` on a call with a prospect the other day along with `teleport install systemd` - it worked very well and was MUCH simpler than the existing instructions.

I'm raising this here so we don't lose track of it.

**Comment by zmb3** [comment]
Partially addressed in #15974
