### ISSUE TITLE
Include architecture diagrams in our protocol-specific "Architecture" pages

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#19190]
## Applies To

`docs/pages/*-access/architecture.mdx`

## Details
Our Database Access Architecture guide includes an architecture digram (https://goteleport.com/docs/database-access/architecture/). We can add similar diagrams to our other protocol-specific "Architecture" pages to make it clearer how Teleport supports these protocols.

**Comment by alixander** [comment]
We really liked the diagram on the README, and [recreated it](https://play.d2lang.com/?script=pFVBb9s8DL3rVxD-kKOT1MW3gzEUSNNma9cOGVKgx0KRWUerLHkS7S5b-98HKnbaFMWQYCdLlPhIvkfKW_Fy8EyaEE1AHyBNodWSP4QGa-dJiH4F6Ql81yRzSKQxoJy1G4wAsik0YQHSFmBcWWKR7Lhpe-_lLpIu0JKmNdTetbpA_3L6MX3ndJNgDkkCvwXA6wbI4UgIgHNbaovxEt8AiHrloLRXBqOFeyOHFVEd8tGId2FI6L0M5BtFQ-WqEYbAsaUJg2x2_OH_lAMPQ1sKgGcBcC3VSlv8xyjykeGnrqobwpfVNs6zEK2Wfyt3gw_J55ub-SIfjRIB8NAsUZHJITnp12ymsIomCiveylrHraw1b4slKKPREqOdncJ0s0k4h16THG56dbbp8MjlkHEu2tY5PFVFLP8_uOjV-ypJtwhz736uBcBTR1lswRyOx-NYqwCYcAPBlSuH-5BHqFaDbGYkd3hH2RQ9waShlfOa1nvByF-NZ-5vcTnIxgv0rVY4yMZTfnMG2WxS17t29KTvtZKEIUZ9FqIbiMsmUKptSrpCmCiFIfAgJW_ZisotjFQPe2VYYDvIZiHe35R5HV_OygUSAJfaSwEwlyX6oiGm-LyS2uxXfezAu09o0UvD5d4u0uh-Z_hJSJdlX2Qc3xwu-LNBaDy-2wghrPYKvjNkR0dZGtC32zH70izRW2SaD9HxjodIWo0M-gqjY24Ni29XB9BercMP0zs7W7qz00O82aNYdv7zw0LXLlDp8SX-rbb8AzoA4rHz6CV8-6CynL1t3tmipIcw3g_6u-Pz6rB0LXorrcIunz8BAAD__w%3D%3D&layout=elk&sketch=1&theme=104&) with our text-to-diagram tool. If ever you want to use diagrams that anyone can modify (vs just the imgs right now), perhaps  https://github.com/terrastruct/d2 could help.

<img width="684" alt="Screen Shot 2023-04-09 at 2 28 00 PM" src="https://user-images.githubusercontent.com/3120367/230797327-f4d26083-2b42-4c08-87d6-08f2ac864a42.png">
