### ISSUE TITLE
Edit the docs to reflect our new messaging

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#19214]
## Applies To

We should review every page in the docs, ideally using an automated system.

## Details

We've changed some ways we talk about the product, so we should reflect these in the docs.

### Terms to change

- [x] "Access plane" -> "Access Platform"
- [x] We say now "protocols" instead of describing "[A-Za-z]+ Access" as a product: "SSH", "Kubernetes", "Databases", "Windows", "Applications". The main point is that these aren't discrete sub-products, but protocols you can add as part of the Teleport Access Platform.
- [x] "Open Source Teleport"  -> "Teleport Community Edition"
- [ ] "Teleport Cloud" -> "Teleport Enterprise Cloud"

### Automated checking

One thing that will help with this is a linter in our docs engine for incorrect usages of Teleport terms (https://github.com/gravitational/docs/issues/154). We can add this linter, then introduce proscribed/prescribed terms gradually until all of the docs are compliant with the new messaging.

### Short product descriptions we should add to the docs

When we describe the benefits of Teleport, we can draw from one of these:

#### Tagline

> Identity-Native Infrastructure Access. Faster. More Secure.

#### ~50-word description

> Teleport is the first identity-native infrastructure access platform for engineers and machines. By replacing insecure secrets with true identity, Teleport delivers phishing-proof zero trust for every engineer and service connected to your global infrastructure. The open source Teleport Access Platform provides a frictionless developer experience and a single source of truth for infrastructure access.   

#### ~100-word description

> Teleport is the first identity-native infrastructure access platform for engineers and machines. By replacing insecure secrets like passwords, keys and tokens with true identity based on biometrics and security modules, Teleport delivers phishing-proof zero trust for every engineer and service connected to your global infrastructure. The open-source Teleport Access Platform consolidates connectivity, authentication, authorization and audit into a single source of truth for access policy across your entire infrastructure while delivering a frictionless developer experience. Teleport replaces VPNs, shared credentials, secrets vaults and legacy PAM solutions, improving security and engineering productivity.

**Comment by ptgott** [comment]
We have a messaging linter in `gravitational/docs` to catch incorrect term usage. You can configure it here: https://github.com/gravitational/docs/blob/main/messaging-config.json

**Comment by lsgunn-teleport** [comment]
Search only revealed a couple of instances of "Access plane". I'm not sure Access Platform is still a thing, but if it is:
[#32769]

**Comment by lsgunn-teleport** [comment]
There are a few stragglers that I wasn't sure about (like OSS AMIs). [#32771]

**Comment by lsgunn-teleport** [comment]
@ptgott @xinding33 Do we really want 
"Teleport Cloud" -> "Teleport Enterprise Cloud" 
or 
"Teleport Cloud" -> "Teleport cloud platform" (this might be easier because it's less context-sensitive) 
or 
"Teleport Cloud" -> "Teleport Team and Teleport Enterprise Cloud" (this might be more difficult to do globally or programmatically because it's likely to depend on context).

**Comment by ptgott** [comment]
@lsgunn-teleport I think all of these changes depend on context:

|Change|When to use|
|---|---|
|"Teleport Cloud" -> "Teleport Enterprise Cloud"|A feature is available for Teleport Enterprise Cloud but not for Team|
|"Teleport Cloud" -> "Teleport cloud platform"| We're talking about architecture, e.g., the need to deploy the Auth Service/Proxy Service|
|"Teleport Cloud" -> "Teleport Team and Teleport Enterprise Cloud"|I think we can pretty much always say "The Teleport cloud platform" instead of these, unless we want to be really explicit about which editions we support.|

What do you think?
