### ISSUE TITLE
Automatic Database User Creation for PostgreSQL

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#19247]
What would you like Teleport to do?
Automatically created database users like is done for SSH today.

What problem does this solve?
Users don't want a process to create a new database user each time someone joins their company across their databases.

If a workaround exists, please include it.
Manually creating the users or scripting it in some way.

**Comment by stevenGravy** [comment]
This would be helpful in a operator

**Comment by r0mant** [comment]
This was released in 13.1 for PostgreSQL. Check out the [guide](https://goteleport.com/docs/database-access/rbac/configuring-auto-user-provisioning/). We're tracking other databases support in https://github.com/gravitational/teleport/issues/27323.
