### ISSUE TITLE
Improve DB docs to create a foundation for ongoing DB work

### ISSUE THREAD

**Issue by rsyracuse** [gravitational/teleport#19273]
## Applies To
[Database Access](https://goteleport.com/docs/database-access/)

## Details
- Make the recommended separation of Auth/Proxy services more clear.
- Better clarity on IAM policies.
- Standardize working Example configurations in [Getting Started](https://goteleport.com/docs/database-access/getting-started/), [RDS guides](https://goteleport.com/docs/database-access/guides/rds/), others.
- Ensure that roles and services are specified and tuned for Database Access when required.

## Related Issues
[#18047](https://github.com/gravitational/teleport/issues/18047)

Improvements to be prioritized for ongoing releases.

**Comment by rsyracuse** [comment]
https://github.com/gravitational/teleport/pull/19265

**Comment by ptgott** [comment]
I'm going to close this issue since we don't have a good way to test the bullet points in the "Details" section for completion.
