### ISSUE TITLE
No Terraform provider for darwin_arm64

### ISSUE THREAD

**Issue by expnch** [gravitational/teleport#19290]
Would it be possible to add a darwin_arm64 build to the official Terraform provider distribution at terraform.releases.teleport.dev/gravitational/teleport?  Building locally works fine as noted in [discussions#10274](https://github.com/gravitational/teleport/discussions/10274), but it would to pull from the official repository instead of rebuilding whenever we switch provider versions.  Thanks!

### Discussed in https://github.com/gravitational/teleport/discussions/10274

<div type='discussions-op-text'>

<sup>Originally posted by **DimitriosPrasakis** February 10, 2022</sup>
Its not published yet but its there.
It is not clear to me how to build it manually

https://github.com/gravitational/teleport/issues/7386</div>

**Comment by zmb3** [comment]
I'm going to close this one, as we're already tracking this work separately. Rest assured, ARM builds for the terraform provider and other plugins are coming soon.

See also:

- https://github.com/gravitational/teleport-plugins/issues/605
- https://github.com/gravitational/teleport-plugins/issues/539
