### ISSUE TITLE
improve error message when using tsh ssh with identity file

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#19293]
```
$ tctl auth sign --user=foo --format=file --out=key.pem
$ tsh --identity=key.pem ssh user@node
ERROR: missing parameter hostname
```

In this case, it's not clear _what_ is missing the hostname parameter.

Note: the same happens with `tsh --identity=key.pem ls`.

The cause of the issue is that there is no tsh profile and no `--proxy` flag, so `tsh` doesn't know what endpoint it is supposed to connect to.

Consider checking for an empty proxy value and showing a clearer error. Something like:

```
ERROR: missing proxy address. Specify --proxy or login with tsh login.
```

**Comment by chethan27** [comment]
@zmb3 can u assign this to me ?

**Comment by zmb3** [comment]
@chethan27 you're welcome to submit a PR for this one.

**Comment by wadells** [comment]
Since I don't see a PR from @chethan27 , I'm looking at having a new hire work on this during their first week as a way to learn teleport.

**Comment by jof** [comment]
It came up in the PR that `tctl` basically has the same issue, and I'm going to try and address both in each utility.
