### ISSUE TITLE
parallel kubectl invocations excessively bog down client

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#19313]
### Expected behavior:

A team utilizing kubernetes has adopted Teleport for kube access. Their existing processes and scripts make use of parallel invocations of kubectl for tasks such as mass updating resources. These scripts may do things such as labeling resources, update container image, etc.

While Teleport does add its proxy and agent component between the end user and the real kube api server, it is expected that performance should be comparable and error-free.

### Current behavior:

During the research of this symptom, the customer ended up duplicating some of the error messages by doing the following:

* use an affected kube cluster (dozens of namespaces each with pods)
* run `kubectl get ns --no-headers | cut -f 1 -w | xargs -n 1 -P 40 kubectl get pod -n` - this lists all namespaces, and then launches one `kubectl get pod -n <namespace>` command per namespace. It runs up to forty of these in parallel.

Errors generated on the host where `kubectl` is being run. 192.168.1.81 is the macos client itself, and 192.168.1.1 is the local network's dns server. Switching to a different (external/public/popular) dns service doesn't affect the appearance of this type of error.

```
Unable to connect to the server: dial tcp: lookup teleport.example.com on 192.168.1.1:53: dial udp 192.168.1.1:53: connect: can't assign requested address
Unable to connect to the server: dial tcp: lookup teleport.example.com on 192.168.1.1:53: read udp 192.168.1.81:51968->192.168.1.1:53: i/o timeout
```

Errors that appeared in the proxy service include:

```
2022-12-01T08:15:07Z ERRO [MXWEB]     Expected *tls.Conn, got *multiplexer.Conn. multiplexer/web.go:116
2022-12-01T08:15:07Z ERRO [MXWEB]     Expected *tls.Conn, got *multiplexer.Conn. multiplexer/web.go:116
```

Debug level logs will come.

Both of these error types seem to point to some resource becoming overloaded on the local machine that is preventing some instances of kubectl from going through the flow.

---

Another quick test that I did against a single node kube instance was to create 100 empty namespaces, and then time that same operation as a baseline:

`for i in `seq 100`; do kubectl create ns test-${i}; done`

There were six existing namespaces with pods (including teleport-kube-agent), so this means there are 106 `kubectl get pod -n <ns>` commands that will run for each run.

| - | P=1 | P=10 | P=40 | P=80 | P=120 |
| --- | --- | --- | --- | --- | --- |
| direct | 9.90s user 3.14s system 64% cpu 20.284 total | 11.08s user 3.60s system 496% cpu 2.955 total | 12.46s user 4.36s system 820% cpu 2.050 total | 12.81s user 4.76s system 811% cpu 2.164 total | 13.02s user 5.07s system 861% cpu 2.100 total|
| teleport | 18.45s user 7.80s system 51% cpu 51.085 total | 21.58s user 10.03s system 434% cpu 7.270 total | 22.33s user 10.52s system 178% cpu 18.402 total | 22.04s user 10.83s system 96% cpu 33.977 total | 22.57s user 11.45s system 55% cpu 1:01.34 total|

I wasn't able to reproduce the other errors mentioned above, but the times are indicative of an issue. When executing only one kubectl command at a time, responses start coming very quickly. When al 106 were launched at the same time, it took several seconds before the first one completed, and took more clock time for them all to complete compared to running one at a time with no parallelization.

I suspected that the `tsh kube credentials` command that the kubeconfig refers to may be contributing to a decent amount of the extra stuff that is done on the client side. I created a kubeconfig file that had the credentials from `tsh kube credentials` defined statically and reran the same timing test:

| - | P=1 | P=10 | P=40 | P=80 | P=120 |
| --- | --- | --- | --- | --- | --- |
| no tsh kube credential | 8.61s user 2.99s system 31% cpu 36.336 total | 9.57s user 3.39s system 283% cpu 4.565 total | 10.22s user 4.03s system 553% cpu 2.574 total | 9.32s user 3.82s system 559% cpu 2.351 total | 11.49s user 4.85s system 624% cpu 2.617 total

Unfortunately https://github.com/gravitational/teleport/issues/19312 makes this workaround a little trickier.

I decided to run `tsh kube credential` in parallel, and there definitely seems to be some sort of slowdown.

<details>
<summary>details on parallelizing tsh kube credentials</summary>
This command runs a specified number of identical `tsh kube credentials` commands all in parallel. `seq 106` controls how many total will run, and `-P 120` simply needs to be higher to run all in parallel at once.

```
seq 106 | time xargs -I {} -P 120 -n 1 tsh kube credentials --teleport-cluster other --kube-cluster vultr
```

| instances | total | avg |
| --- | --- | --- |
| 1 | 0.145 | 0.145 |
| 10 | 0.430 | 0.043 |
| 20 | 0.740 | 0.037 |
| 30 | 1.108 | 0.037 |
| 40 | 1.483 | 0.037 |
| 60 | 13.604 | 0.228 |
| 80 | 30.236 | 0.378 |
| 106 | 46.681 | 0.440 |

It does seem that as the number of parallel instances of `tsh kube credentials` increase, there hits a point where they are fighting for some local resource. I don't believe `tsh kube credential` makes any calls out to the network, so it's a bit strange that there is a detectible slowdown. I would have hoped that the average clock time would go down as more instances are added. I don't know to what degree the tsh kube credential instantiations are prompting the errors seen by kubectl and the proxy service.
</details>

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
Given that the slower Teleport invocations use less CPU, it's likely that we're I/O bound here.

Consider enabling tracing on auth and configuring things such that `tsh kube credential` runs with the `--trace` flag, which should help us see where the time is being spent.

**Comment by tigrato** [comment]
The workaround mentioned (issue #19312) is included in the following releases:
- `>= v11.1.4`
- `>= v10.3.11`
- `>= v9.3.25`


The workaround can be used to generate static `kubeconfig` with static Kube access credentials while I continue to investigate the root cause of this issue.
