### ISSUE TITLE
`tsh db connect` db access always uses `8.0.0-Teleport` even when `mysql.server_version` is set. it is not consistent with `tsh proxy db`

### ISSUE THREAD

**Issue by flybyray** [gravitational/teleport#19336]
Expected behavior:

should show the configured string
in this example `8.0.28-19.1 Percona XtraDB Cluster (GPL), Release rel19, Revision f544540, WSREP version 26.4.3`

Current behavior:

```shell
$ tsh db connect --db-user=myuser db11-rr-pxc80-test-33001 <<< "\s;\q"
--------------
mysql  Ver 8.0.29-21.1 for Linux on x86_64 (Percona XtraDB Cluster (GPL), Release rel21, Revision 250bc93, WSREP version 26.4.3)

Connection id:          10003
Current database:
Current user:           myuser@10.11.1.11
SSL:                    Cipher in use is TLS_AES_128_GCM_SHA256
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server version:         8.0.0-Teleport Percona XtraDB Cluster (GPL), Release rel19, Revision f544540, WSREP version 26.4.3
Protocol version:       10
Connection:             teleport.example.com via TCP/IP
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    utf8mb3
Conn.  characterset:    utf8mb3
TCP port:               443
Uptime:                 20 days 16 hours 32 min 12 sec

Threads: 11  Questions: 52  Slow queries: 0  Opens: 162  Flush tables: 3  Open tables: 74  Queries per second avg: 0.000
--------------

$ tctl get db/db11-rr-pxc80-test-33001 --format=json | jq -r '.[].spec.mysql.server_version'
8.0.28-19.1 Percona XtraDB Cluster (GPL), Release rel19, Revision f544540, WSREP version 26.4.3
```

Bug details:
- Teleport version

```shell
$ tctl status
Cluster  teleport.example.com
Version  10.3.9
```

- Recreation steps

follow documentation

- Debug logs
nothing to debug

**Comment by flybyray** [comment]
when connecting with jdbc driver it has some logic to query a global `query_cache_size` variable from mysql server because the server reports wrong version. in `8.0.3` the `query_cache_size` was removed hence jdbc drivers cannot be easily used against teleport db proxy.

**Comment by smallinsky** [comment]
The `mysql.server_version` is propagated only when a client connects to the teleport proxy with TLS Routing mode ("multiplex") where the `the db proxy` always uses the multiplex mode but `tsh db connect` connections depends global proxy listener mode ref: https://goteleport.com/docs/management/operations/tls-routing/#step-27-enable-proxy-multiplexing

In https://github.com/gravitational/teleport/pull/24464 we will allow to overwrite default mysql server version per teleport proxy for a connection where TLS Routing is not used and dynamic `mysql.server_version` mysql version propagation is not possible via TLS extensions.
