### ISSUE TITLE
BPF high CPU utilization

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#19344]
The teleport process utilizes CPU resources when idle after enabling the enhanced session. Our BPF modules pass all IO events from the kernel to the user space, which can cause high CPU usage on systems with many IO operations. 
We could filter all events in the kernel space before sending them to our user space process, which should reduce CPU usage.

Bug details:
- Teleport version v10+ (but probably also before that)
- Recreation steps
  - enable enhanced session recording
  - run IO heavy operations outside of Teleport
  - check the CPU usage of the teleport process

**Comment by jakule** [comment]
Fixed in https://github.com/gravitational/teleport/pull/19354

**Comment by Homio** [comment]
> The teleport process utilizes CPU resources when idle after enabling the enhanced session. Our BPF modules pass all IO events from the kernel to the user space, which can cause high CPU usage on systems with many IO operations. We could filter all events in the kernel space before sending them to our user space process, which should reduce CPU usage.
> 
> Bug details:
> 
>     * Teleport version v10+ (but probably also before that)
> 
>     * Recreation steps
>       
>       * enable enhanced session recording
>       * run IO heavy operations outside of Teleport
>       * check the CPU usage of the teleport process

Hi,
  Does it fixed on arm64?
