### ISSUE TITLE
Ambiguous timeout flake

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#19372]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/e20c4a89-3cc0-4e00-9542-22e6ff447b5b?project=ci-account

#### Relevant snippet
[ambiguous_flake.log](https://github.com/gravitational/teleport/files/10230562/ambiguous_flake.log)

**Comment by ibeckermayer** [comment]
https://console.cloud.google.com/cloud-build/builds/d620aeab-62ec-4c1a-8005-7c0bcf2594f1?project=ci-account

**Comment by zmb3** [comment]
https://github.com/gravitational/teleport/actions/runs/3796323648/jobs/6456312658

**Comment by zmb3** [comment]
v9: https://console.cloud.google.com/cloud-build/builds/65a159c0-d2c9-4d10-a902-b9de10445cdf;step=0?project=ci-account

**Comment by zmb3** [comment]
Master: https://github.com/gravitational/teleport/actions/runs/4055818111/jobs/6979470507

**Comment by ibeckermayer** [comment]
https://github.com/gravitational/teleport/actions/runs/4068348700/jobs/7006793211

**Comment by ibeckermayer** [comment]
master: https://github.com/gravitational/teleport/actions/runs/4068524590/jobs/7007171819

**Comment by nklaassen** [comment]
master: https://github.com/gravitational/teleport/actions/runs/4296095131/jobs/7487386845

**Comment by zmb3** [comment]
@r0mant just fixed this one in v11+. v10 wasn't cooperating and will be deprecated soon.
