### ISSUE TITLE
Add support for custom pod labels for teleport-cluster

### ISSUE THREAD

**Issue by aardbol** [gravitational/teleport#19381]
In our case, being able to label our pods is essential, but the teleport-cluster Helm chart doesn't support that.

**Comment by hugoShaka** [comment]
No, I might have the time to do it before the cut if needed. Else it will have to be backported.

I'm still a bit afraid of allowing users to set labels and don't know if this feature should be implemented. Labels should be used to select pods, mainly by Replication controllers and services. 

Allowing users to configure them is a big footgun, I don't know yet use-cases that would require using labels, except the new Pod Security Admission (which feels wrong, I'll need to read the KEP to understand why they did not use annotations).

**Comment by russjones** [comment]
No problem, let's wait for @r0mant to get back before we make a decision on this then.

**Comment by aardbol** [comment]
In our case, we depend pod labels as part of our [OPA](https://kubernetes.io/blog/2019/08/06/opa-gatekeeper-policy-and-governance-for-kubernetes/) requirements.

**Comment by anthonysomerset** [comment]
From my perspective - i would like to start looking at using AKS workload Identity which requires pod labels to enable - https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview

**Comment by hugoShaka** [comment]
@anthonysomerset thank you for the example. The questionable AKS design choices don't leave us much choice but to add the feature.

**Comment by aardbol** [comment]
This feature seems to have been implemented in the v12 chart. Is there an intention to backport it to v11?

**Comment by hugoShaka** [comment]
The v12 `teleport-cluster` chart does not currently support setting additional custom pod labels (the `teleport-kube-agent` supports it, though).

You can workaround by overwriting the label template in an umbrella chart by doing:

```
{{/* Auth selector labels */}}
{{- define "teleport-cluster.proxy.selectorLabels" -}}
app.kubernetes.io/name: '{{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}'
app.kubernetes.io/instance: '{{ .Release.Name }}'
app.kubernetes.io/component: 'proxy'
my-custom-additional-label: foo
{{- end -}}
```

**Comment by jlm0x017** [comment]
Looks like https://github.com/gravitational/teleport/pull/34986 would support this issue
