### ISSUE TITLE
`teleport-cluster` Helm chart should support webauthn and passwordless by default

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#19394]
What would you like Teleport to do?

Clusters deployed using the `teleport-cluster` Helm chart should support webauthn and passwordless by default instead of supporting only OTP. We can do this by default in the Helm chart because we know the public address and can automatically set the `rp_id` (which is not the case when deploying Teleport using the binary only).

What problem does this solve?

This allows users to get more value from Teleport by default, as they can log in using hardware tokens.

If a workaround exists, please include it.

Learn about the 2fa configuration and the chart parameters, and set the value ~`authentication.second_factor: webauthn`~ `authentication.second_factor: on`.

**Comment by webvictim** [comment]
I think it should be `authentication.second_factor: on` to support both OTP _and_ webauthn.
