### ISSUE TITLE
Connect: Use PowerShell 7 if available on the system

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#19392]
On Windows, [Connect uses `powershell.exe` as the default shell](
https://github.com/gravitational/webapps/blob/19711954648bd435f9bb171fa6720d666f154e59/packages/teleterm/src/mainProcess/runtimeSettings.ts#L174-L175). That's PowerShell 5 which is installed by default on Windows.

However, there's PowerShell 7 which is [faster to start up](https://twitter.com/shadowbIood/status/1602990252720807938) and has some nice new features. Unfortunately, even if the user installs it, Connect will not use it because PowerShell7 is started through the `pwsh.exe` command, not `powershell.exe`.

A simple fix would be to check for the existence of `pwsh.exe` with [lookpath](https://www.npmjs.com/package/lookpath) and if not present, fall back to `powershell.exe`.

Some users also expressed interest in being able to configure the shell used on Windows.

**Comment by swastik959** [comment]
@ravicious hi I am new to open source and want to work on this issue but finding it difficult to understand it please guide me through it

**Comment by swastik959** [comment]
@ravicious hi can you tell me how to reproduce this issue

**Comment by ravicious** [comment]
Sure. When you launch a new terminal session in Connect on Windows (fastest way is to hit Ctrl + K, then Escape to close the autocomplete and then Enter), PowerShell says this:

> Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

This means that Connect is using the old version of PowerShell that's distributed with Windows. Once you follow the installation instructions from the link, you'll see that the new version of PowerShell uses `pwsh.exe` as its executable rather than `powershell.exe`.

The issue description links to a place in the code where we say which shell should be used by our terminal tabs on Windows. We'd like Connect to use the [lookpath](https://www.npmjs.com/package/lookpath) npm package to determine if `pwsh.exe` is available in Path and use `pwsh.exe` instead of `powershell.exe` if available.

**Comment by ravicious** [comment]
Ah, sorry, I forgot to mention that at the moment the OSS build of Connect is broken, see #17706. I'm working on this at the moment but it won't be ready for the next couple of weeks. In the meantime you can follow instructions from #17706, which boil down to commenting out any imports from e-teleterm & e-teleport and replacing imported types from those packages with `any`.
