### ISSUE TITLE
Cloud-scoped docs use invalid version

### ISSUE THREAD

**Issue by jimbishopp** [gravitational/teleport#19471]
## Applies To
One example: [Database Access with AWS ElastiCache and AWS MemoryDB for Redis](https://goteleport.com/docs/database-access/guides/redis-aws/?scope=cloud#step-37-create-a-database-service-configuration)

## Details
The tarball installation guide uses the `(=cloud.version=)` variable which is a *currently* unpublished version due to a private release. This will resolve itself once the private release is published to OSS.

Changing this to `(=teleport.version=)` would resolve this issue but only for the current private release scenario. However, for standard releases, the OSS version can be ahead of the cloud version. These examples should use the most recent OSS version less than or equal to the current cloud version.

**Comment by stevenGravy** [comment]
One possible solution is to have a cloud oss version.  Which OSS version should be used with the Cloud version.
