### ISSUE TITLE
disable passwordless feature per users

### ISSUE THREAD

**Issue by bahmanjafari** [gravitational/teleport#19472]
What would you like Teleport to do?
currently, we can disable the passwordless feature globally per cluster in the teleport auth server. we have two models of a hardware token, one of them supports bio, and another just supports button click. I want passwordless enabled for users who have bio tokens and for others this feature is disabled.

What problem does this solve?
disabled passwordless features for specific users.

**Comment by codingllama** [comment]
If one of the tokens doesn't support passwordless, then this is the behavior you'd get anyway. 

If you want to limit the set of devices exclusively to token model1 and model2, you can look at WebAuthn attestation (https://goteleport.com/docs/access-controls/guides/webauthn/#step-13-enable-webauthn-support). That would guarantee no other tokens are used.

That all said, I think the default WebAuthn configuration will do a good job for you, so I'd advice just letting users who can do passwordless do it.
