### ISSUE TITLE
Docs: Terraform teleport_provision_token needs to be more explicit about supported fields

### ISSUE THREAD

**Issue by gaille-teleport** [gravitational/teleport#19487]
## Applies To
https://goteleport.com/docs/reference/terraform-provider/#teleport_provision_token

## Details
Currently, `spec` portion states the following:
> Spec contains parameters of a resource. It has a single field: `roles`, a list of roles associated with a token. It will be converted to metadata in the SSH and X509 certificates issued to the user of the token.

This portion could be improved and should state that `roles` is the only required field, _and_ also stating that there are other, optional fields such as `join_method`.

## Related Issues
The following issue was reported when it shouldn't have been an issue at all since the params are already supported for this resource: #9420

**Comment by ptgott** [comment]
Fixed in https://github.com/gravitational/teleport/pull/42798
