### ISSUE TITLE
Weak SSH ciphers by default

### ISSUE THREAD

**Issue by ocha** [gravitational/teleport#1953]
**What happened**:
Scanning port 3023 revealed that teleport uses weak ciphers (arcfour) by default

**What you expected to happen**:
Not to have weak ciphers enabled by default

**How to reproduce it (as minimally and precisely as possible)**:
Install Teleport with default config

**Environment**:
- Teleport version (use `teleport version`): `Teleport v2.5.6 git:v2.5.6-0-g81d77d2`
- OS (e.g. from /etc/os-release): `Centos 7`

**Relevant Debug Logs If Applicable**

The following weak `client-to-server` and `server-to-client` encryption algorithms are supported by the remote service:
`arcfour128`
`arcfour256`

**Comment by klizhentas** [comment]
this is fixed in 2.6.0, those ciphers are disabled by default.

**Comment by klizhentas** [comment]
@russjones can you confirm and close this

**Comment by russjones** [comment]
@ocha This was fixed in https://github.com/gravitational/teleport/pull/1948 and will roll out in Teleport 2.6.0.

In the meantime if you are running Teleport 2.5.6, you can update `ciphers` to remove `arcfour128` and `arcfour256`.

```
Teleport:
    ciphers:
      - aes128-ctr
      - aes192-ctr
      - aes256-ctr
      - aes128-gcm@openssh.com
```
