### ISSUE TITLE
teleport web interface connect button leads to connection to incorrect node

### ISSUE THREAD

**Issue by aberoham** [gravitational/teleport#1955]
**What happened**:

Passing along a bug from a Teleport Enterprise eval -- "I’m not sure if this is a bug or if it’s working as intended. We have set up teleport and connected some nodes to it, these nodes use the same nodename and labels but different IPs. When we try to sign into them via the web interface we are always connected to the same node (the first one registered with the auth server). If we use the `tsh` command on the same demo cluster the connection is established and works as expected, ie we’re connecting to the node we specify. "

**What you expected to happen**:

The connection to land on the intended node.

**How to reproduce it (as minimally and precisely as possible)**:

Set up a cluster where all attached nodes have identical labels and only the IP address differs. Something like this --

```
Node Name                                   Node ID                                     Address            Labels
------------------------------------------- ------------------------------------------- ------------------ --------------------------------------------------
XYZ Worker Node v1                          81172c9a-3feb-4f63-b9a4-cfe58b755e7e        10.203.xx.40:3022  environment=workers,region=us-east-1
XYZ Worker Node v1                          b21fb268-1297-42b1-a85b-05e023d05e56        10.203.yy.40:3022  environment=workers,region=us-east-1
XYZ Worker Node v1                          88b07a14-b319-445d-a56f-853c3da69939        10.203.zz.40:3022  environment=workers,region=us-east-1
```

**Environment**:
- Teleport version (use `teleport version`): 2.5.6
- Tsh version (use `tsh version`): 2.5.6
- OS (e.g. from /etc/os-release): n/a

**Browser environment**

Chrome 66.0.3359.139 (Official Build) (64-bit)

**Relevant Debug Logs If Applicable**

[logs available upon request but likely not interesting as this appears to be within the UI and not the server-side components]

**Comment by kontsevoy** [comment]
the web UI should use the Node ID or the IP to connect.
