### ISSUE TITLE
teleport db configure create flag checking is inconsistent with valid database config

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#19560]
Expected behavior:
I should be able to create a config for a static database that doesn't require a URI e.g. AWS Keyspaces (Cassandra):
```sh
$ teleport db configure create \ 
      --name="foo" \
      --proxy="mars.local.gd:443" \
      --protocol=cassandra \
      --aws-region="us-west-1" \
      --token="abc123"
```
Current behavior:
prints
`ERROR: --uri is required when configuring static database`

Furthermore, `--aws-accound-id` (for static database config) is missing from the config flags. This setting is required for AWS Keyspaces.

I think we should have very few flag checks in this command and instead we should generate the yaml config, parse it, and then try to build a database from it. This way we can keep this command's flag validation in sync with the database config spec validation code.

Bug details:
- Teleport version: dev v12  (4237ad3cc72176e343684f3b807c6b2cc11e2968)

@smallinsky

**Comment by GavinFrazar** [comment]
This also affects DynamoDB now btw.

**Comment by GavinFrazar** [comment]
@smallinsky have you had a chance to work on this? I'd like to fix this for v12 since it affects the new DynamoDB integration. I can do it if you prefer.

**Comment by smallinsky** [comment]
@GavinFrazar No I haven't had chance to take a look at this in this week so I would be grateful if you can handover. Thanks!
