### ISSUE TITLE
Extend AWS Token more than 1hr

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#19586]
**What would you like Teleport to do?**

Admin would like Teleport to allow them to create an AWS app and generate tokens longer than 1 hour.

**What problem does this solve?**

Admin has to end up login in multiple times a day; this is not ideal. They prefer to have 1 login per day. 4h is ideal

**If a workaround exists, please include it.**

No workaround exists

**Comment by greedy52** [comment]
Is the App agent deployed in an EKS pod using a service account? 

If so (or a similar situation), there is a note in the [guide](https://github.com/gravitational/teleport/blob/master/docs/pages/application-access/guides/aws-console.mdx)

> If Teleport is running with [temporary security credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html), the management console session will be limited to a maximum of one hour.

This is a limitation of using temp AWS credentials to assume another role on the AWS side. The workaround would be to c place IAM role credentials in `~/.aws/credentials` for the app agent.
