### ISSUE TITLE
`race detected during execution of test`

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#19589]
## Failure

Several unit tests failed with this message, I think the majority were just what happened to be running when a race was detected.

#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/abee20f3-a310-47b1-a698-95f3012cd6eb?project=ci-account

#### Relevant snippet

```
testing.go:1319: race detected during execution of test
```

**Comment by zmb3** [comment]
Let's assume this was fixed by #19592 and open a new issue if we see further failures.
