### ISSUE TITLE
AWS CloudFormation DNS

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1959]
When creating a CloudFormation stack, we should create DNS entries for:

```
proxy01.example.com
proxy02.example.com
auth01.example.com
auth02.example.com
node01.example.com
node02.example.com
```

This will make running commands using SSH very simple. For example instead of telling users to connect to the AWS Console and get the IP addresses of their proxy server and auth server, we can just say run the following command:

```
ssh -o ProxyCommand="ssh -W %h:%p ec2-user@proxy01.example.com" \
   ec2-user@auth01.example.com.
```

**Comment by klizhentas** [comment]
that's not for marketplace though, as users don't expect these entries to exist, I think we should implement this one in the context of terraform

**Comment by msyber** [comment]
With a simple tag on EC2 resources it can work. Take a look on this: https://aws.amazon.com/blogs/compute/building-a-dynamic-dns-for-route-53-using-cloudwatch-events-and-lambda/

**Comment by mumoshu** [comment]
> that's not for marketplace though, as users don't expect these entries to exist, I think we should implement this one in the context of terraform

Sry If I'm not following you correctly, but how about adding `HostedZoneID` is a stack parameter? So that the stack template can be improved to create Route53 record sets under the hosted zone.
