### ISSUE TITLE
Docs for DynamoDB integration via Database Access

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#19600]
## Applies To
https://goteleport.com/docs/database-access/guides/dynamodb/

## Details
Previously DynamoDB integrant was done by Application Access after implementing  [18843](https://github.com/gravitational/teleport/pull/18843) DynamoDB access is fully integrated via Teleport Database Access. 

Align the docs to use Database DynamoDB access instead of AWS CLI Applicaiton access flow. 

## Related Issues

https://github.com/gravitational/teleport/pull/18843

**Comment by GavinFrazar** [comment]
We can keep the old guide for app access and just move it to that app access guides section (where it belongs).
