### ISSUE TITLE
AWS CloudFormation Policy

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1960]
I was not able to successfully create a CloudFormation stack until I added fairly broad access capabilities. The getting started guide should provide a list of permissions that the user has to run it.

**Comment by webvictim** [comment]
Yes - this is definitely something I want to get under control. I've got bits and pieces of the IAM policies needed noted down locally, so when the files in a bit more of a constant state I'll add details of the required permissions to the README.
