### ISSUE TITLE
Add support for UI driven upload and download of files

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1962]
## Description

Teleport UI should add support for downloading and uploading files. 

Important design consideration to keep in mind:

* Upload and download should work over existing terminal tab and re-use the same connection to use the same user permissions.

I will leave the UX of the feature to design to @kontsevoy 

This feature has to be shipped in 2.7.0

## Upload

* User has to specify a destination folder on the remote server. By default it's set to `~/` AKA $HOME
* User has to specify local file(s) to upload.

The upload progress may look like this:

```
Path                                        Progress
------------------------------------------  --------
/full/path/to/file/on/server/lib/name.gpg   complete
/full/path/to/file/README                   complete
/full/path/to/file/on/server/name.txt       ERROR
/full/path/to/file/on/server/: access denied
```

## Download

* Due to web tech limitations, _only a single file_ can be downloaded.
* User has to provide the path of the file to download. If the provided path is absolute (i.e. starts with `/`) it's treated as-is. If the path does not start with `/` it's assumed to be relative to `~/` (just like `scp` does it)

The download progress will be shown by browser's native downloading UI.

**Comment by klizhentas** [comment]
@kontsevoy

**Comment by kontsevoy** [comment]
@alexwolfe I have a couple of proposals but we'll need mockups for this.

**Comment by klizhentas** [comment]
Deadline for this one is July 6th, we have to publish RC

**Comment by jddonz** [comment]
Would it be possible to add a progress meter to `tsh scp` similar to ssh scp? Currently there is no feedback that the transfer is in progress, only when it finishes:
```
tsh scp file.tgz user@host:
-> file.tgz (0)
```
For small files this isn't an issue but with larger files it is nice to be able to see the progress.

**Comment by ilanbowen** [comment]
it looks like every file that is downloaded using the feature has the text '{"message":"ok"}' appended to it, which then requires manual removal for each downloaded file

**Comment by kontsevoy** [comment]
@ilanbowen we'll look into this, thank you.

**Comment by russjones** [comment]
@ilanbowen I've reproduced this, we'll track it here https://github.com/gravitational/teleport/issues/14557.
