### ISSUE TITLE
trusted_cluster: RemoteProxy,default-implicit-role policy violation

### ISSUE THREAD

**Issue by hoobaman** [gravitational/teleport#1963]
1) Currently testing the latest stable version of Teleport

Version : 2.5.7
Type: OSS
Architecture: trusted_cluster setup

main cluster <- east cluster (reverse tunnel)

resource trusted_cluster:

kind: trusted_cluster
metadata:
  name: east
spec:
  enabled: true
  role_map:
  - local:
    - admin
    remote: admin
  token: cluster-join-token
  tunnel_addr: x.x.x.x:3024
  web_proxy_addr: x.x.x.x:3080
version: v1

resource role (default admin -OSS version- role on both auth servers):
kind: role
metadata:
  name: admin
spec:
  allow:
    logins:
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
    rules:
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - auth_connector
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - session
      verbs:
      - list
      - read
    - resources:
      - trusted_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
  deny: {}
  options:
    cert_format: standard
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3

2) While testing the connection flow below:

client -> proxy main -> -reverse tunnel > proxy east -> proxy/node east

End-user functionality (connecting/recording/joining) works as expected.
However my log files get hammered with an RBAC violation. In addition this seems to cause cpu spikes and a somewhat "slow" terminal behaviour.

- log file main cluster (auth/proxy instance)
access denied to perform action 'read' on session web/stream.go:98

- log file east cluster (auth/proxy instance)
INFO [RBAC] read access to session [namespace default] denied for roles RemoteProxy,default-implicit-role: no allow rule matched services/role.go:1640

They are clearly related (timestamp + number of messages)

**Comment by aberoham** [comment]
Thanks for the detailed error report. Another Teleport user reported this issue yesterday. We didn't open a bug because the issue has been fixed in master and the latest v2.6 tags. Possible for you to try v2.6.0-beta.3 binaries to see if the correlation with cpu spikes persists?

**Comment by hoobaman** [comment]
Thanks for the the feedback. I downloaded the latest beta source (v2.6.0-beta3) and compiled the binaries. Your assessment of the situation is correct. 
The latest beta version resolves the issues described above:

- RBAC violation errors are gone on both clusters 
- CPU consumption is better under control

**Comment by kontsevoy** [comment]
@aberoham shall we close this?
