### ISSUE TITLE
[Web UI] Refreshing the web terminal in a pending moderated session disconnects the user and crashes the webpack dev server

### ISSUE THREAD

**Issue by rudream** [gravitational/teleport#19660]
#### Expected behavior:
Refreshing the terminal shouldn't crash the running Web UI dev server nor disconnect the user.

#### Current behavior:
When on this screen:
![image](https://user-images.githubusercontent.com/56373201/209410410-d986717d-861b-4e32-89b6-39350bc5e160.png)

Refreshing the page causes you to disconnect (this doesn't happen for non-moderated sessions)
![image](https://user-images.githubusercontent.com/56373201/209410477-fdd4149b-50b5-4283-824e-37232a1f9a0c.png)

If running the Web UI via the webpack dev server, it crashes with the following error:
```
node:events:515
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on TLSSocket instance at:
    at TLSSocket.onerror (node:internal/streams/readable:785:14)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}

Node.js v18.4.0
error Command failed with exit code 1.
```

#### Bug details:
- Teleport version: 12.0.0-dev
- Recreation steps: Start a moderated SSH session in the UI and refresh the page.

**Comment by zmb3** [comment]
@rudream did we fix this one already?

**Comment by rudream** [comment]
No, this seems to be a frontend error. The issue we fixed was with the backend panicking and crashing.

**Comment by zmb3** [comment]
@rudream do you recall if this also happened with Vite, or was it only the webpack dev server?

If only webpack, I'm inclined to close as won't fix.

**Comment by rudream** [comment]
@zmb3 This does seem to only occur with webpack, I just tested again on v13 and v14 using the Vite dev server and wasn't able to reproduce the bug.
