### ISSUE TITLE
tsh --user isn't being recognized 2.5.7 OSX 10.12.6

### ISSUE THREAD

**Issue by eegilbert** [gravitational/teleport#1967]
**What happened**:
The tsh --user=username doesn't seem to be honored

**What you expected to happen**:

I expected tsh --user=erric ssh hostname to make a successful connection with a username that's not the same as my local host login, but matches the remote system user.

**How to reproduce it (as minimally and precisely as possible)**:

    ✘-1 ~ []-> tsh --user=erric --proxy=iron.example.com login
    Enter password for Teleport user erric:
    Enter your OTP token:
    367791
    
    You are now logged in
    ✔ ~ []-> tsh ls
    Node Name Node ID                              Address        Labels                                                    
    --------- ------------------------------------ -------------- --------------------------------------------------------- 
    iron      ccea0dcd-9c70-43b8-b1e1-fad8a8685f46 127.0.0.1:3022 arch=x86_64,db_role=master,db_type=postgres,hostname=iron 
    
    ✘-1 ~ []-> tsh --debug --user=erric ssh iron
    
    ERROR REPORT:
    Original Error: *errors.errorString access denied to froboz connecting to iron
    Stack Trace:
            /tmp/20180508T142644/src/github.com/gravitational/teleport/lib/client/client.go:418 github.com/gravitational/teleport/lib/client.(*ProxyClient).ConnectToNode
            /tmp/20180508T142644/src/github.com/gravitational/teleport/lib/client/api.go:510 github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH
            /tmp/20180508T142644/src/github.com/gravitational/teleport/tool/tsh/tsh.go:461 main.onSSH
            /tmp/20180508T142644/src/github.com/gravitational/teleport/tool/tsh/tsh.go:260 main.Run
            /tmp/20180508T142644/src/github.com/gravitational/teleport/tool/tsh/tsh.go:146 main.main
            /usr/local/go/src/runtime/proc.go:204 runtime.main
            /usr/local/go/src/runtime/asm_amd64.s:2338 runtime.goexit
    User Message: access denied to froboz connecting to iron

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.5.7 git:v2.5.7-0-gb3f4ecb5
- Tsh version (use `tsh version`): Teleport v2.5.7 git:v2.5.7-0-gb3f4ecb5
- OS (e.g. from /etc/os-release): MacOS 10.12.6

**Browser environment**

N/A this is only a CLI issue

**Relevant Debug Logs If Applicable**

    ERROR REPORT:
    Original Error: *errors.errorString access denied to froboz connecting to iron
    Stack Trace:
            /tmp/20180508T142644/src/github.com/gravitational/teleport/lib/client/client.go:418 github.com/gravitational/teleport/lib/client.(*ProxyClient).ConnectToNode
            /tmp/20180508T142644/src/github.com/gravitational/teleport/lib/client/api.go:510 github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH
            /tmp/20180508T142644/src/github.com/gravitational/teleport/tool/tsh/tsh.go:461 main.onSSH
            /tmp/20180508T142644/src/github.com/gravitational/teleport/tool/tsh/tsh.go:260 main.Run
            /tmp/20180508T142644/src/github.com/gravitational/teleport/tool/tsh/tsh.go:146 main.main
            /usr/local/go/src/runtime/proc.go:204 runtime.main
            /usr/local/go/src/runtime/asm_amd64.s:2338 runtime.goexit
    User Message: access denied to froboz connecting to iron

From the teleport proxy logs:

    May 20 05:43:11 iron teleport: WARN [NODE]      failed login attempt events.EventFields{"user":"erric", "success":false, "error":"ssh: principal \"froboz\" not in the set of valid principals for given certificate: [\"erric\"]"} fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:6Sls0xEG5IsUOvPGimBbDak9+ih3HobBgwwA5JQ+uOg local:127.0.0.1:3022 remote:83.1.1.1:59915 user:froboz srv/authhandlers.go:166

So my local username is froboz and I want to user erric on the host I'm connecting to just like in SSH:
    ssh erric@remotehost.tld

I've compared this to Linux and with the same version the same behaviour exists. For example sudo to root, then:

    tsh --user=erric --proxy=iron.example.com login
    tsh --user=erric ssh iron

Produces the same error, tsh is using the root user instead of the user specified on the cli with the --user flag

**Comment by nikatjef** [comment]
Greetings,

   Right off the bat, it looks like you are using the wrong argument.  You state;
```
So my local username is froboz and I want to user erric on the host I'm connecting to just like in SSH:
ssh erric@remotehost.tld

I've compared this to Linux and with the same version the same behaviour exists. For example sudo to root, then:

tsh --user=erric --proxy=iron.example.com login
tsh --user=erric ssh iron
```

That construct is not saying what you think it is.  Instead it is saying ssh to iron as froboz, but login to the Teleport system as erric.  Instead, you need to use;
```tsh --login=erric ssh iron```
Or
```tsh ssh erric@iron```

**Comment by eegilbert** [comment]
@nikatjef thanks, that indeed was the issue!
