### ISSUE TITLE
CHANGELOG.md is outdated

### ISSUE THREAD

**Issue by fungiboletus** [gravitational/teleport#19670]
Expected behavior:
`CHANGELOG.md` contains the description of the latest releases.

Current behavior:
`CHANGELOG.md` hasn't been updated since the release `10.0.0`

**Comment by zmb3** [comment]
The changelog is updated on the release branches.

**Comment by fungiboletus** [comment]
I see. Since this repository has 2000+ branches, perhaps it could be updated in the main/master branch as well, so it's possible to find it.
