### ISSUE TITLE
Add documentation for fips mode in helm charts

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#19728]
## Applies To

docs/pages/deploy-a-cluster/helm-deployments.mdx
docs/pages/reference/helm-reference.mdx
docs/pages/reference/helm-reference/teleport-cluster.mdx
docs/pages/reference/helm-reference/teleport-kube-agent.mdx

(possibly others?)

## Details

Document the steps necessary to enable fips mode for both charts. Both currently need:

```yaml
teleportVersionOverride: 11.1.4-fips
extraArgs: ["--fips"]
```

teleport-cluster also needs:

```yaml
localAuth: false
```

Additional notes regarding providing a fips-compliant certificate would also be helpful.

## Related Issues

n/a

**Comment by pschisa** [comment]
https://goteleport.com/docs/access-controls/compliance-frameworks/fedramp/#deploy-a-teleport-cluster-in-fips-mode-with-helm documented for v15 where 
~~~
teleportVersionOverride: 11.1.4-fips
extraArgs: ["--fips"]
~~~
are no longer required

**Comment by pschisa** [comment]
reference: https://github.com/gravitational/teleport/pull/38244
