### ISSUE TITLE
Desktop Directory Share - downloaded large files from remote Desktop to client is corrupt

### ISSUE THREAD

**Issue by igontaric** [gravitational/teleport#19731]
Expected behavior:
When copying a large file from remote desktop to shared directory, the file should not be corrupted.
Original reported bug: [#18534](https://github.com/gravitational/teleport/issues/18534)

Current behavior:
Larger files (~20MB) that are copied from remote desktop to shared directory are still corrupt.

Bug details:
- Teleport Version: 11.1.4
- Recreation steps
  - copy a zip (~20MB file) from remote desktop (in teleport) to shared drive
  - test (extract the copied file) 
  
- Debug logs: Cannot find any

**Comment by zmb3** [comment]
@ibeckermayer can you have a look?

**Comment by ibeckermayer** [comment]
Confirmed that this problem still exists. It's independent of the general large file problem fixed by https://github.com/gravitational/webapps/pull/1382. I've been able to reproduce it by creating a zip file >= 500kb.

**Comment by ibeckermayer** [comment]
@igontaric sorry for offering false hope previously! I'm pretty sure this will take care of it once and for all though: https://github.com/gravitational/webapps/pull/1471

**Comment by ibeckermayer** [comment]
@igontaric we are planning to have a release with this fix on Friday

**Comment by igontaric** [comment]
Hi @ibeckermayer , no worry :) I understand that this kind of issues may be tricky to fix, take your time to test and fix it. 
Happy to black box test it for you.
Cheers
