### ISSUE TITLE
Question: Disconnected after 1 mins if user did not do anything

### ISSUE THREAD

**Issue by vipervn2010** [gravitational/teleport#1975]
**What happened**:
- I run command `/usr/local/bin/teleport start -d --insecure-no-tls --config=/etc/teleport.yaml --pid-
file=/var/run/teleport.pid` for create a auth,proxy cluster.
- I joined node, created user, activated user
- Setup AWS Application Load Balancer and Route 53
- Open web and login [https://luan-teleport.production.icbsys.net/web/login](https://luan-teleport.production.icbsys.net/web/login)
- Logged into Node
- I don't do anything in 1 minute then it automatically disconnected

**What you expected to happen**:
- I tested with self-signed cert and it did not disconnect.
- Can we have 1 more configuration like WebSessionTimeout ?

**Environment**:
tctl - tsh - teleport v2.5.7 git:v2.5.7-0-gb3f4ecb5 that i downloaded from main page. Then I tar and ./install.

- OS: Ubuntu 16.04 64 bit

**Browser environment**
Chrome and Firefox latest version

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by klizhentas** [comment]
Please check idle timeout settings on your ALB. Default is 1 minute, most likely that's why you are disconnected.

**Comment by vipervn2010** [comment]
Many thanks! Have a nice day !
