### ISSUE TITLE
Port forwarding request denied: port forwarding not allowed by role set: roles admin,default-implicit-role.

### ISSUE THREAD

**Issue by nikatjef** [gravitational/teleport#1976]
I am fairly certain I have done something wrong, but...  I am getting the following error when I attempt to use port forwarding in the Open Source version;
```Port forwarding request denied: port forwarding not allowed by role set: roles admin,default-implicit-role.```

As this is the OSS version, I am unable to add new roles or update admin role to add support for port forwarding.

Teleport version is: Teleport v2.6.0-beta.3 git:v2.6.0-beta.3-3-g2b2952ab

EDIT.  Also getting this in Teleport v2.6.0-rc.2 git:v2.6.0-rc.2-0-g850048f1

**Comment by nikatjef** [comment]
Any update on this request please?

**Comment by russjones** [comment]
@nikatjef Was this a fresh install or an upgrade? Can you try this on a fresh install and see if you are still running into this problem?

**Comment by nikatjef** [comment]
It was an upgrade.

Will try a fresh install this weekend when I can take my clusters offline.

**Comment by russjones** [comment]
@nikatjef What version did you start at and what versions did you upgrade through? I think you may have hit a bug in either 2.4 or 2.5 where we did not correctly upgrade the admin role. It was fixed in a point release if I recall correctly.

If you are running a backend which you are comfortable manually updating the values in, I can tell you what fields to update.

**Comment by nikatjef** [comment]
IIRC, I went from 1.3, 2.2, to 2.3.  At 2.3, I wiped my cluster and rebuilt due to some backend incompatibility. Then from 2.3, 2.4.1, 2.4.2, 2.5.1, to 2.6.0-rc2.

Please note these were not binary releases, but local compiles with whatever version of Go was the most recent at the time of building.

As for the backend, I am using the stock Teleport, with no extra backend...  Having said that I am thinking of downloading DynamoDB and running it off one of my Rpi3's.

**Comment by russjones** [comment]
You are probably using Bolt if you started on older versions of Teleport and if you have been upgrading to in-between builds that's probably why you ran into this issue.

I'm not sure if Bolt has command line support to do it or if you will have to write a program to update a Bolt database, but to fix this on your current cluster you would have to open the `roles/admin/params` key and update `options` in your role to include `port_forwarding: true`. It might be easier to just wipe out and start fresh on 2.6.2.

```
        "options": {
            "cert_format": "standard",
            "forward_agent": true,
            "max_session_ttl": "30h0m0s",
            "port_forwarding": true
        }
```

**Comment by russjones** [comment]
@nikatjef Going to close this issue for now. If you have any other questions feel free to open another ticket or comment here.
