### ISSUE TITLE
docs/ver/9.0 URLs no longer work

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#19765]
## Applies To

* https://goteleport.com/docs/ver/9.0/setup/operations/tls-routing/
* https://goteleport.com/docs/ver/9.0/database-access/guides/redis/
* probably more

## Details

https://github.com/gravitational/teleport/issues/9569#issuecomment-1119434771 used to link to `https://goteleport.com/docs/ver/9.0/setup/operations/tls-routing/`. Someone pointed out that the link no longer works. I went to check what's the URL for v9 docs now and `9.0` was changed to `9.x`.

We still have some links to 9.0, for example in [the 9.0 changelog](https://goteleport.com/docs/changelog/#database-access). I suppose it'd make sense to redirect 9.0 URLs to 9.x.

**Comment by ravicious** [comment]
@ptgott Do we plan to introduce redirects for the old URL scheme? #19836 fixes the links in the changelog but any old link on the internet which uses `<major>.0` instead of `<major>.x` will remain broken.

I see you wrote on Slack that you plan on working on this but I'm not sure if you meant adding redirects or introducing the changes from #19836.

**Comment by ptgott** [comment]
@ravicious Ah, good point. At the level of `gravitational/teleport`, our redirect config (`docs/config.json`) only applies to a particular version of a docs site. We'll need to see what's possible for redirects from the old versioned path format to the new one in our docs engine. I'll create an issue!
