### ISSUE TITLE
Unreasonable ERROR message

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1977]
## Problem

When you're running Teleport in non-verbose mode, you see **lots** of these in the log:

```
ERRO [SESSION:N] Shell exited with error: wait: remote command exited without exit status or exit signal srv/sess.go:664
```

Upon closer examination, I determined that this is a result of using the web UI. The Web UI has a red "close session" button, which closes the session, i.e. it's a completely normal path of execution. 

The same thing happens when `tsh` cliens simply close a terminal window _while the session is in progress_, which is again a totally normal thing to do.

So why are we scaring users by showing them errors?

## Solution

Change this to `INFO`.

**Comment by russjones** [comment]
Fixed in https://github.com/gravitational/teleport/commit/cc8ae9919282cf7cc8f9629713391051b50f6a33
