### ISSUE TITLE
Machine ID Kubernetes Access incorrectly uses web address/port when multiplexing disabled

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#19811]
### Expected behavior:

machine id should match the tsh behavior when generating the host:port for use in a kubeconfig when multiplexing is disabled.

### Current behavior:

Given a cluster with multiplexing disabled and no explicit `kube_public_addr` set, tsh kube login and machine id with a kubeconfig destination will not use the same host:port for the same cluster.

The `tsh kube login` version will generate a `cluster:` section with `server: https://cluster.example.com:3026`, which is correct. The kubernetes service is not enabled on the web port in this cluster configuration.

If a kubeconfig is generated with a machine id bot, even when using the same exact roles and kube cluster, the resulting kubeconfig ends up with `server: https://cluster.example.com:3080`. Since there is no kube service running on port 3080, kubectl gives a certificate error. The cert error is incidental-- the kubeconfig is expecting a cert signed by the Teleport CA, but the web proxy service does not do that. Even if one did adjust the kubeconfig accordingly, the web proxy port is still not running the kube service when multiplexing is disabled.

```
$ curl https://cluster.example.com:3080/webapi/ping
{"auth":{"type":"local","second_factor":"off","local":{"name":""},"private_key_policy":"none","has_motd":false},"proxy":{"kube":{"enabled":true,"listen_addr":"0.0.0.0:3026"},"ssh":{"listen_addr":"[::]:3023","tunnel_listen_addr":"0.0.0.0:3024","web_listen_addr":"0.0.0.0:3080","public_addr":"cluster.example.com:3080","ssh_public_addr":"cluster.example.com:3023","ssh_tunnel_public_addr":"cluster.example.com:3024"},"db":{},"tls_routing_enabled":false},"server_version":"11.1.4","min_client_version":"10.0.0","cluster_name":"cluster"}
$ export KUBECONFIG=~/.kube/config
$ tsh login --user testuser --proxy cluster.example.com:3080
$ tsh kube login default
$ grep server: $KUBECONFIG
    server: https://cluster.example.com:3026
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:50:52Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
$ tbot start -c /opt/bot/bot.cfg &
$ export KUBECONFIG=/opt/bot/dest/kubeconfig.yaml
$ grep server: $KUBECONFIG
    server: https://cluster.example.com:3080
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Unable to connect to the server: x509: certificate signed by unknown authority
```

### Workarounds:

The machine id user would need to set up some type of process to adjust the kubeconfig.yaml output on the fly.

_or_

The Teleport admin could set `kube_public_addr` explicitly to match the expected hostname/port rather than relying on the behavior of the tsh/tctl client binaries to correctly use the correct value.

### Bug details:
- Teleport version - reported against 9.3.24, also present in `Teleport v11.1.4 git:v11.1.4-0-ge4ac5f6717 go1.19.4`
- Recreation steps - set up a cluster with multiplexing disabled, kube access enabled, at least one kube cluster. Omit the `kube_public_addr` in the teleport.yaml for the proxy. compare the generated kubeconfig files for both `tsh kube login` and `tbot start` and observe that machine id is using the web port incorrectly.
- Debug logs - n/a

Here's an example teleport.yaml that was used with 11.1.4 to recreate the issue locally:

```yaml
version: v3
teleport:
  nodename: recreate
  data_dir: /opt/recreate/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: "cluster"
  license_file: /opt/recreate/teleport/license.pem
  proxy_listener_mode: separate
  authentication:
    type: local
    second_factor: off
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:3080
  public_addr: cluster.example.com:5443
  listen_addr: "[::]:3023"
  tunnel_listen_addr: 0.0.0.0:3024
  ssh_public_addr: cluster.example.com:3023
  tunnel_public_addr: cluster.example.com:3024
  kube_listen_addr: 0.0.0.0:3026
  #kube_public_addr: cluster.example.com:3026
  https_keypairs: []
  acme: {}

kubernetes_service:
  enabled: "yes"
  kubeconfig_file: /opt/recreate/kind_kubeconfig
  listen_addr: 0.0.0.0:3027
```

**Comment by strideynet** [comment]
I'm taking a look at this.

Part of me thinks that the current reliance on clients do to the right thing here is pretty bizarre. It would make more sense for us to treat the Ping endpoint as more of a client autoconfiguration endpoint, and, if `kube_public_addr` has not been set, to take the value of `public_addr` and append the port configured for `kube_listen_addr`.

**Comment by SoulKyu** [comment]
Hello, 

Facing the same issue

**Comment by strideynet** [comment]
Experienced this bug with a open source community member in slack today - I do intend to get around to fixing this this quarter. Working closely with this user has given me some inspiration on the best way for us to handle.

**Comment by strideynet** [comment]
Had another OSS user bump into this today. Setting kubePublicAddr in the proxy fixes this.
