### ISSUE TITLE
Can't find old arm releases

### ISSUE THREAD

**Issue by Yoni-shir** [gravitational/teleport#19825]
We currently have a teleport cluster set up with a very old version (4.4.11), and we want to install teleport on graviton servers with arm architecture. At the moment, I can't find any packages/binaries with arm architecture that would be compatible with our cluster. Not sure if those packages still exist, but if they do, can you make them available to download?

Expected behavior:
I see that in the past you have added arm builds for version 4.2 in the [changelog](https://goteleport.com/docs/changelog/#442) 
I want to be able to download them, like I'm able to download older versions from the deb repository/from https://get.gravitational.com/

Current behavior:
Those versions aren't included in the download portal (understandably, as this is a very old version) but I am also unable to download the arm from the deb repo (stable/v4) or from https://get.gravitational.com/. 

Bug details:
- Teleport version
4.4.11
- Recreation steps
trying to download teleport version 4.4.11 for arm  - for example by running `curl -O https://get.gravitational.com/teleport_4.4.11_arm64.deb` (doesn't work)  vs. running `curl -O https://get.gravitational.com/teleport_4.4.11_amd64.deb` (works)
- Debug logs

**Comment by zmb3** [comment]
Hi @Yoni-shir - we did not publish deb packages in the Teleport 4 days, so you'll have to download the [tarball](https://get.gravitational.com/teleport-v4.4.11-linux-arm64-bin.tar.gz ) instead and install it manually.
