### ISSUE TITLE
OpenSSH Proxy Subsystem Problem

### ISSUE THREAD

**Issue by wntdone** [gravitational/teleport#1983]
**What happened**:
In an attempt to use an OpenSSH client to ssh into a node behind a Teleport proxy, the system responds with "SSH-2.0-Teleport 2.6.0" and hangs

**What you expected to happen**:
Receive a regular ssh prompt.

**How to reproduce it (as minimally and precisely as possible)**:
`ssh -i ~/.tsh/keys/auth.example.com/joe -p 3023 joe@auth.example.com -v -s proxy:host:3022`

**Environment**:
- Teleport version (use `teleport version`): v2.6.0 git:v2.6.0-0-g7978158b
- Tsh version (use `tsh version`): Teleport v2.6.0 git:v2.6.0-0-g7978158b
- OS (e.g. from /etc/os-release): Server: Ubuntu 16.04.4 LTS, Workstation: MacOS 10.13.4

**Relevant Debug Logs If Applicable**

> $ ssh -v -i ~/.tsh/keys/auth.example.com/joe -p 3023 joe@auth.example.com -s proxy:host:3022
> OpenSSH_7.6p1, LibreSSL 2.6.2
> debug1: Reading configuration data /Users/joe/.ssh/config
> debug1: Reading configuration data /etc/ssh/ssh_config
> debug1: /etc/ssh/ssh_config line 48: Applying options for *
> debug1: Connecting to auth.example.com port 3023.
> debug1: Connection established.
> debug1: identity file /Users/joe/.tsh/keys/auth.example.com/joe type 0
> debug1: identity file /Users/joe/.tsh/keys/auth.example.com/joe-cert type 4
> debug1: Local version string SSH-2.0-OpenSSH_7.6
> debug1: Remote protocol version 2.0, remote software version Teleport 2.6.0
> debug1: no match: Teleport 2.6.0
> debug1: Authenticating to auth.example.com:3023 as 'joe'
> debug1: SSH2_MSG_KEXINIT sent
> debug1: SSH2_MSG_KEXINIT received
> debug1: kex: algorithm: curve25519-sha256@libssh.org
> debug1: kex: host key algorithm: ssh-rsa-cert-v01@openssh.com
> debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
> debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
> debug1: Server host certificate: ssh-rsa-cert-v01@openssh.com SHA256:xxxxxxxxxxx, serial 0 ID "" CA ssh-rsa SHA256:xxxxxxxxxxx valid forever
> debug1: checking without port identifier
> debug1: No matching CA found. Retry with plain key
> debug1: No matching CA found. Retry with plain key
> debug1: Host '[auth.example.com]:3023' is known and matches the RSA host key.
> debug1: Found key in /Users/joe/.ssh/known_hosts:23
> debug1: rekey after 4294967296 blocks
> debug1: SSH2_MSG_NEWKEYS sent
> debug1: expecting SSH2_MSG_NEWKEYS
> debug1: SSH2_MSG_NEWKEYS received
> debug1: rekey after 4294967296 blocks
> debug1: SSH2_MSG_SERVICE_ACCEPT received
> debug1: Authentications that can continue: publickey
> debug1: Next authentication method: publickey
> debug1: Offering public key: RSA-CERT SHA256:xxxxxxxxxxx /Users/joe/.tsh/keys/auth.example.com/joe
> debug1: Server accepts key: pkalg ssh-rsa-cert-v01@openssh.com blen 1097
> debug1: Authentication succeeded (publickey).
> Authenticated to auth.example.com ([1.1.1.1]:3023).
> debug1: channel 0: new [client-session]
> debug1: Entering interactive session.
> debug1: pledge: exec
> debug1: X11 forwarding requested but DISPLAY not set
> debug1: Sending environment.
> debug1: Sending env LANG = en_US.UTF-8
> debug1: Sending subsystem: proxy:host:3022
> SSH-2.0-Teleport 2.6.0
> ^Cdebug1: channel 0: free: client-session, nchannels 1
> Killed by signal 2.

**Comment by klizhentas** [comment]
I don't think this command performs jumphost, try something like this:

```
ssh -i ~/.tsh/keys/auth.example.com/joe -p 3022 -o ProxyCommand='ssh -i ~/.tsh/keys/auth.example.com/joe -p 3023 -v -s proxy:target:3022'   joe@target
``

**Comment by wntdone** [comment]
Thank you for the assistance.  Using "ProxyCommnds=" worked perfectly.
