### ISSUE TITLE
Don't store saml connector secrets in CI/CD

### ISSUE THREAD

**Issue by WilliamLoy** [gravitational/teleport#19861]
What would you like Teleport to do?
The ability to make changes to the attributes_to_roles mappings using CI/CD pipeline without having to store sensitive information about the saml connector in the CI/CD pipeline, such as XML metadata and key pairs.

What problem does this solve?
Allows admins to automate the management of the attributes_to_roles mappings without storing sensitive information in CI/CD pipeline.

If a workaround exists, please include it.

**Comment by zmb3** [comment]
See also #6815

**Comment by nathan-bowman** [comment]
+1 I'd like to see the SSO connector to be more cloud native, declarative, and secrets management friendly.

**Comment by zmb3** [comment]
Lets track this in #6815.
