### ISSUE TITLE
Clean up `tctl tokens add` output

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#19894]
This command prints a lot of output with suggested commands. For example:
```
$ tctl tokens add --type=db
The invite token: *snip*
This token will expire in 60 minutes.

Fill out and run this command on a node to start proxying the database:

> teleport db start \
   --token=*snip* \
   --ca-pin=sha256:*snip*\
   --auth-server=*snip* \
   --name= \
   --protocol= \
   --uri=

Or, generate the configuration and start a Teleport agent using it:

> teleport db configure create \
   --token=*snip* \
   --ca-pin=sha256:*snip* \
   --proxy=*snip* \
   --name= \
   --protocol= \
   --uri= \
   --output file:///etc/teleport.yaml

> teleport start -c /etc/teleport.yaml

Please note:

  - This invitation token will expire in 60 minutes.
  - Database address  must be reachable from the new database
    service.
  - When proxying an on-prem database, it must be configured with Teleport CA
    and key pair issued by "tctl auth sign --format=db" command.
  - When proxying an AWS RDS or Aurora database, the region must also be
    specified with --db-aws-region flag.
```

In no particular order, here are the things I see wrong with this:
* The commands needlessly have flags without values. We shouldn't print those flags at all if they are blank.
* `teleport db start` should not be printed at all. See: https://github.com/gravitational/teleport/issues/11457
* I don't understand why `file://` is prefixed to the `--output` flag. It seems to work on my mac regardless. On EC2, it create a file named `file:///etc/teleport.yaml`. Is this some windows compatibility thing? I'd prefer we don't add that prefix unless it's really necessary.
* Multiple flags for cloud databases are missing (`--aws-region`, `--aws-external-id`, `--azure-*`, etc) from the `tctl tokens add` command. We have a note at the end about AWS regions flag, but it suggests the flag `--db-aws-region` that does not exist. No mention of the required flags for other cloud databases in that note.
* With `--type=app,db`, only the app command is suggested. It also does not consistently output a configuration example for the App case (and we don't have a corresponding `teleport app configure create` command).

I propose we remove the `teleport db start` and `teleport db configure create` command suggestions altogether. `tctl tokens add` output should just look like this:
```
The invite token: *snip*
This token will expire in 60 minutes.
```

*Maybe* include a suggestion that they check out the teleport config commands to generate a yaml config.

Imo, we should also consolidate config generation under `teleport configure` instead of having a separate command for each service. What if I want a config generated for an agent that will proxy both apps and databases? Can't generate one with the commands we have now, I have to run separate commands, and confusingly I have to use `teleport configure --app-name=foo --app-uri=foo.com` for apps, and `teleport db configure create` for databases.

Related issue (in general): https://github.com/gravitational/teleport/issues/12811

**Comment by GavinFrazar** [comment]
The "bug" here is the `--db-aws-regions` flag that does not exist. The "feature" part is the rework of this command to simplify its output.

**Comment by GavinFrazar** [comment]
@zmb3 do you think this is a good starter issue? It's just command output, but it would require a decent bit of refactoring in `tctl` and `teleport`. Happy to work it myself though

**Comment by strideynet** [comment]
I agree with the suggested change of just outputting the token. We provide documentation elsewhere that's much more thorough and reviewed by our docs team, and often these example commands provided by `tctl tokens add` get left behind. If needed we can add a link to the docs in the output. We also have more specific commands like `tctl nodes add` which seem more suited to this hand-holded output.

**Comment by tukusejssirs** [comment]
Isn’t this issue fixed?

My current output is as follows:

```bash
# tctl nodes add --ttl=15m --roles=node,app --format text
The invite token: $token
This token will expire in 15 minutes.

Run this on the new node to join the cluster:

> teleport start \
   --roles=node,app \
   --token=$token \
   --ca-pin=sha256:$ca_pin \
   --auth-server=$auth_server:3025

Please note:

  - This invitation token will expire in 15 minutes
  - $auth_server:3025 must be reachable from the new node
```

**Comment by zmb3** [comment]
Going to close this, as the request for `--format=token` is already tracked in #9986
