### ISSUE TITLE
Show Teleport versions in node list

### ISSUE THREAD

**Issue by mpitt** [gravitational/teleport#1992]
I think it would be useful to show the Teleport version running on each node in the output of `tsh ls` and `tctl nodes ls`. Possibly hidden by a flag.

**Environment**:
- Teleport version (use `teleport version`): 2.6.1

**Comment by aberoham** [comment]
Hi Michele, this is possible today using dynamic node labels. Did you see that section of the docs? https://gravitational.com/teleport/docs/admin-guide/#labeling-nodes

**Comment by mpitt** [comment]
@aberoham That's interesting, but I was thinking of a different use case. I probably didn't explain myself really well. 

With dynamic labels I would see the output of `teleport version`, i.e. the installed version. What I'm interested in is the running version, which isn't always the same thing: I might have installed a new version but not reloaded/restarted the service.

Actually, maybe what I'm looking for is an extension of the `teleport status` command that reports which version is running (and in case of a graceful restart, whether there are open connections to the old version).

**Comment by nikatjef** [comment]
This is actually related to #1573

**Comment by kontsevoy** [comment]
@nikatjef I guess we'll have to look into this again, heh?

**Comment by nikatjef** [comment]
hehehe.  Sorry.  ;)

**Comment by zmb3** [comment]
This is now solved with the introduction of `tctl inventory status`.
