### ISSUE TITLE
Support ALPN websocket passthrough for all protocols

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#19975]
When hosting Teleport in a Kubernetes cluster, it makes sense for users to be able to expose Teleport through their existing ingress-controller (as opposed to exposing Teleport using a LoadBalancer service).

Quoting @hugoShaka 

> This will dramatically improve the Helm experience by removing big dependencies like cert-manager, reducing the time to value by half, and behaving like any other Kubernetes application like our users expect. Plus, we keep receiving support cases and tickets of users trying to run Teleport behind an ALB/NLB terminating TLS.

This implies implementing "ALPN behind ALPN" support for all protocols like what was done for database access: [issue](https://github.com/gravitational/teleport/issues/14369), [PR](https://github.com/gravitational/teleport/pull/15669).

**Comment by webvictim** [comment]
I'd like to request that this work also include a fix for [IAM joining](https://goteleport.com/docs/management/guides/joining-nodes-aws-iam/) not working behind TLS terminating-load balancers as per https://github.com/gravitational/teleport/issues/20792

**Comment by greedy52** [comment]
https://github.com/gravitational/teleport/issues/21870#issuecomment-1679470294
