### ISSUE TITLE
Kubernetes Helm Guide should provide IAC flow

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#19974]
## Description

When users follow https://goteleport.com/docs/deploy-a-cluster/helm-deployments/aws/ they get several wrong impressions:

## Teleport needs to create S3 buckets and DynamoDB
 
The policies below are written in a way that allow Teleport to create DynamoDB/S3 buckets. 

Production admins don't like that, as they don't like infrastructure drift

https://goteleport.com/docs/deploy-a-cluster/helm-deployments/aws/#dynamodb-iam-policy

Instead, link Terraform examples and JSON commands to policies referring to existing tables and S3 buckets.

## No IAC way to create users/resources

The guide above uses `kubectl exec` instead of using Terraform (IAC) or Kubernetes operator (that is not mentioned anywhere in the guide as far as I see, what is strange, as it's K8s guide):

https://github.com/gravitational/teleport/tree/master/operator#teleport-kubernetes-operator

**Comment by KeenanLawrence** [comment]
We faced this same "problem". We resolved it by removing the permissions that create and alter the resources and declare that in IAC instead.

`s3`:
```
"s3:PutEncryptionConfiguration",
"s3:PutBucketVersioning",
"s3:CreateBucket"
```
`dynamodb`:
```
"dynamodb:CreateTable",
"dynamodb:UpdateTable",
"dynamodb:UpdateContinuousBackups"
```

The only one we didn't remove because we're unsure how it would affect operation is `"dynamodb:UpdateTimeToLive"`. That being said, it would be nice to have the attributes (name and type) used for the hash and range keys explicitly documented (for the respective DynamoDB tables).

**Comment by ptgott** [comment]
### Context for the second item, "No IAC way to create users/resources"

If people visit the docs, they don't know (until they visit pages buried in the "Manage your Cluster" section) that the Terraform provider or Operator exists. The impression is that you can only configure Teleport using `tctl` and the Web UI.

We should make sure that the docs reflect all available techniques for applying configuration resources. `tctl`, the Web UI, Terraform, and the Operator should be first-class citizens.

The scope of this request is to rework the information architecture of the docs so users encounter all of these administration methods at the same time.

**Comment by ptgott** [comment]
Since these are two different requests, we should track them separately:

- [ ] Teleport needs to create S3 buckets and DynamoDB
- [ ] No IAC way to create users/resources

**Comment by ptgott** [comment]
Created this issue to track the S3/DynamoDB issue: https://github.com/gravitational/teleport/issues/22482

**Comment by ptgott** [comment]
I've opened a separate issue for emphasizing IAC approaches in the docs: https://github.com/gravitational/teleport/issues/22483

I'm going to close this issue so we can track the individual asks separately. Please feel free to add detail/context to #22482 or #22483.
