### ISSUE TITLE
Reducing confusion in the JIT access request form for users with permanent cluster access

### ISSUE THREAD

**Issue by inboxamitraj** [gravitational/teleport#19988]
### What would you like Teleport to do? ###
Reduce confusion in the JIT access request form for users with permanent cluster access.

### What problem does this solve? ###
We are evaluating the Just-In-Time (JIT) access workflow for our Kubernetes clusters. I have noticed that if a user already has permanent access to a cluster, they can still see that cluster under Access Requests->Kubernetes.

I am referring to this form - `https://<teleport-url>/web/cluster/tele.test.cstack.sg/requests/new` 

This can be misleading in a multi-cluster scenario. E.g.  Where users have permanent access to the Dev cluster but can request JIT access to the Stg and Prd clusters. 

For example, in the attached screenshot, the user 'myuser' already has permanent access to the 'tele-test-eks' cluster. If the user **already** has permanent access, why is the cluster being shown in the JIT request form?
<img width="755" alt="Screenshot 2023-01-05 at 5 15 11 PM" src="https://user-images.githubusercontent.com/33777211/211283724-473e6de9-1da6-4e66-bfdf-ebf6161e36d0.png">

### If a workaround exists, please include it ###
Currently if the user attempts to submit JIT access request for a cluster, which she/he already have access, the error is thrown when submitting the request.
<img width="491" alt="Screenshot 2023-01-09 at 6 08 08 PM" src="https://user-images.githubusercontent.com/33777211/211284584-954e1f41-650c-470c-945c-1e368e43b07f.png">

### Which version of Teleport you are using? ###
We are using self-hosted enterprise teleport-11.1.2

### Why this feature is important? ###
The current JIT access form is not user-friendly. Users may accidentally click on the access request button and later realize they made a mistake. It is also challenging to explain to users why they are seeing clusters that they already have access to.

**Comment by zmb3** [comment]
This was fixed in https://github.com/gravitational/teleport.e/pull/2653
