### ISSUE TITLE
Document differences in config file schema versions

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#20016]
## Applies To

https://goteleport.com/docs/reference/config/

## Details

Currently, there are three schema versions that Teleport can use. These differences are not captured in the reference, which can exacerbate confusion around differences in Teleport behavior when changing the schema version.

This can be helped if the reference doc included the following:

* A note about the existence of different schema versions and why Teleport uses a versioned schema in the first place.
* A list of any schema-specific behaviors (v2 and v3 are multiplexing-on by default, for example)
* Any schema-exclusive options (auth_servers vs auth_server/proxy_server, for example)

Some information specific to the concept as a whole could get its own small note or section. Any other schema-specific options could appear in line with the reference config file doc. Some options already have some mentions of schema versions, but not all of them.

## Related Issues

#13324

**Comment by programmerq** [comment]
I see confusion around the schema versioning a few times a week on average.

**Comment by alexfornuto** [comment]
> A note about the existence of different schema versions and why Teleport uses a versioned schema in the first place.

A note at the top of the config reference page introducing the concept and referencing versioned docs, and a table for Teleport Version to Schema Version

**Comment by alexfornuto** [comment]
> A list of any schema-specific behaviors (v2 and v3 are multiplexing-on by default, for example)

Schema changelog, possibly independent page?
