### ISSUE TITLE
AD Joined Machines

### ISSUE THREAD

**Issue by wjdavis5** [gravitational/teleport#2002]
**What happened**:
Cannot log into active directory joined machines using active directory usernames. 
**What you expected to happen**:
Able to log in
**How to reproduce it (as minimally and precisely as possible)**:
I create a new user:
tctl user add testUser testUser, testUser@synovia.local, synovia\\testUser, synovia\testUser
Then try to use any of them to access an AD joined instance

**Environment**:
- Teleport version (use `teleport version`): 2.6.1
- Tsh version (use `tsh version`): 2.6.1
- OS (e.g. from /etc/os-release):
Teleport Server:  Operating System: CentOS Linux 7 (Core)
All Client Machines: Ubuntu 16.04

**Comment by klizhentas** [comment]
Teleport supports only account management and session management PAM functions:

#1766

It does not support pam_authenticate and will probably never will, because it contradicts teleport's invariant of using SSH and X509 certificates as the only form of authentication in the cluster available.
