### ISSUE TITLE
Windows tsh client connects to local host instead of proxy when trying to access MySQL

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#20042]
**Expected behavior:**
`tsh db connect` connects users to the MySQL DB. 

**Current behavior:**
Users receive the error message `ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)` when trying to connect to MySQL using the tsh Windows client. I expected tsh to try to connect to the DB at the proxy addr, not localhost, when not using multiplexing. 

**Workaround:**
Connect to the DB with an [authenticated tunnel ](https://goteleport.com/docs/connect-your-client/gui-clients/#get-connection-information)and the MySQL client.

**Bug details:**
- Teleport version
   tsh: 11.0.3 db-agent: 11.0.1 auth/proxy: 11.1.4
- Recreation steps
   On a windows client, attempt to connect to a database. The cluster should not use multiplexing and should have the `mysql_listen_addr` set
- Debug logs

No logs are generated in the db service or the auth/proxy service from the connection attempt.

Client logs:
```
>tsh db connect -d
←[36mINFO←[0m [CLIENT]    no host login given. defaulting to exampleuser client\api.go:1471
←[36mINFO←[0m [CLIENT]    [KEY AGENT] Connected to the system agent: "" client\api.go:4341
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [KEYSTORE]  Reading certificates from path "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-ssh\\examplecompany-teleport-cert.pub". client\keystore.go:346
←[36mINFO←[0m [KEYAGENT]  Loading SSH key for user "exampleuser@examplecompany.com" and cluster "examplecompany-teleport". client\keyagent.go:246
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [KEYSTORE]  Reading certificates from path "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-ssh\\examplecompany-teleport-cert.pub". client\keystore.go:346
←[37mDEBU←[0m [KEYSTORE]  Reading certificates from path "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-db\\examplecompany-teleport". client\keystore.go:346
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [KEYSTORE]  Reading certificates from path "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-ssh\\examplecompany-teleport-cert.pub". client\keystore.go:346
←[37mDEBU←[0m [KEYSTORE]  Reading certificates from path "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-db\\examplecompany-teleport". client\keystore.go:346
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[36mINFO←[0m [CLIENT]    Connecting to proxy=tele.accessiq.examplecompany.com:3023 login="-teleport-nologin-f5348840-1c2e-4293-b9ad-7d5e1a676c20" client\api.go:3320
←[37mDEBU←[0m [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy\proxy.go:301
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com <omitted>" client\keyagent.go:418
←[37mDEBU←[0m [KEYAGENT]  Validated host tele.accessiq.examplecompany.com:3023. client\keyagent.go:424
←[36mINFO←[0m [CLIENT]    Successful auth with proxy tele.accessiq.examplecompany.com:3023. client\api.go:3329
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [CLIENT]    Client  is connecting to auth server on cluster "examplecompany-teleport". client\client.go:1404
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [TSH]       C:\ProgramData\chocolatey\bin\mysql.exe --defaults-group-suffix=_examplecompany-teleport-stg06-useast1-cis-d --user teleport_devops_ro tsh\db.go:762
ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
ERROR REPORT:
Original Error: *exec.ExitError exit status 1
Stack Trace:
        github.com/gravitational/teleport/lib/client/db/dbcmd/error.go:56 github.com/gravitational/teleport/lib/client/db/dbcmd.ConvertCommandError
        github.com/gravitational/teleport/tool/tsh/db.go:775 main.onDatabaseConnect
        github.com/gravitational/teleport/tool/tsh/tsh.go:1070 main.Run
        github.com/gravitational/teleport/tool/tsh/tsh.go:457 main.main
        runtime/proc.go:250 runtime.main
        runtime/asm_amd64.s:1594 runtime.goexit
User Message: exit status 1
```

**Comment by webvictim** [comment]
What's in the `%userprofile%\.my.cnf` file?

Here's an example of what it should look like after running `tsh db connect --db-user=teleport purple-db-mysql`:
```
C:\Users\Gus>type %userprofile%\.my.cnf
[client_example-purple-db-mysql]
host=teleport.example.com
port=3036
user=teleport
ssl-mode=VERIFY_IDENTITY
ssl-ca=C:\Users\Gus\.tsh\keys\teleport.example.com\cas\example.pem
ssl-cert=C:\Users\Gus\.tsh\keys\teleport.example.com\gus@example.com-db\example\purple-db-mysql-x509.pem
ssl-key=C:\Users\Gus\.tsh\keys\teleport.example.com\gus@example.com
```

This part works fine for me with `tsh` 10.3.9 and with a regular `mysql_listen_addr` set:

```
gus@hades:~$ curl -s https://teleport.example.com/webapi/ping | jq .proxy.db
{
  "mysql_listen_addr": "0.0.0.0:3036"
}
```

I don't have `mysql` installed on this Windows machine at the moment to validate the full end-to-end connection however.

**Comment by corkrean** [comment]
@webvictim the `.my.cnf` file is being generated exactly like yours. I also have the `mysql_listen_addr` set.

**Comment by webvictim** [comment]
I'm having the same problem with `mysql` (installed from Chocolatey):
```
←[37mDEBU←[0m [TSH]       C:\tools\mysql\current\bin\mysql.exe --defaults-group-suffix=_purple-purple-db-mysql --user teleport tsh\db.go:749
ERROR 1045 (28000): Access denied for user 'teleport'@'localhost' (using password: NO)

ERROR REPORT:
Original Error: *exec.ExitError exit status 1
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/client/db/dbcmd/error.go:56 github.com/gravitational/teleport/lib/client/db/dbcmd.ConvertCommandError
        /go/src/github.com/gravitational/teleport/tool/tsh/db.go:762 main.onDatabaseConnect
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:1054 main.Run
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:450 main.main
        /opt/go/src/runtime/proc.go:250 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: exit status 1
```

It seems like maybe `mysql` isn't reading `.my.cnf`.

**Comment by Tener** [comment]
> It seems like maybe `mysql` isn't reading `.my.cnf`.

Per https://stackoverflow.com/questions/1712646/i-can-not-find-my-cnf-on-my-windows-computer/1712684#1712684 the file should be `my.cnf` not `.my.cnf`. This seems to contradict MySQL docs: https://dev.mysql.com/doc/refman/8.0/en/option-files.html, but I'll see if it works.

**Comment by Tener** [comment]
I found the issue. 

Per https://dev.mysql.com/doc/refman/8.0/en/option-files.html on Windows `mysql` client reads:

<p class="title" style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; border: 0px; outline: 0px; font-size: 14.256px; vertical-align: baseline; background: rgb(24, 26, 27); line-height: 1.6; display: block; color: rgb(178, 172, 162); font-family: &quot;Open Sans&quot;, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="box-sizing: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 14.256px; vertical-align: baseline; background: transparent;">Table 4.1 Option Files Read on Windows Systems</b></p><div class="table-contents" style="box-sizing: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 14.256px; vertical-align: baseline; background: rgb(24, 26, 27); color: rgb(178, 172, 162); font-family: &quot;Open Sans&quot;, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

File Name | Purpose
-- | --
%WINDIR%\my.ini, %WINDIR%\my.cnf | Global options
C:\my.ini, C:\my.cnf | Global options
BASEDIR\my.ini, BASEDIR\my.cnf | Global options
defaults-extra-file | The file specified with --defaults-extra-file, if any
%APPDATA%\MySQL\.mylogin.cnf | Login path options (clients only)
DATADIR\mysqld-auto.cnf | System variables persisted with SET PERSIST or SET PERSIST_ONLY (server only)

Contrast with Linux:

<p class="title" style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; border: 0px; outline: 0px; font-size: 14.256px; vertical-align: baseline; background: rgb(24, 26, 27); line-height: 1.6; display: block; color: rgb(178, 172, 162); font-family: &quot;Open Sans&quot;, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="box-sizing: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 14.256px; vertical-align: baseline; background: transparent;">Table 4.2 Option Files Read on Unix and Unix-Like Systems</b></p><div class="table-contents" style="box-sizing: inherit; margin: 0px; padding: 0px; border: 0px; outline: 0px; font-size: 14.256px; vertical-align: baseline; background: rgb(24, 26, 27); color: rgb(178, 172, 162); font-family: &quot;Open Sans&quot;, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

File Name | Purpose
-- | --
/etc/my.cnf | Global options
/etc/mysql/my.cnf | Global options
SYSCONFDIR/my.cnf | Global options
$MYSQL_HOME/my.cnf | Server-specific options (server only)
defaults-extra-file | The file specified with --defaults-extra-file, if any
~/.my.cnf | User-specific options
~/.mylogin.cnf | User-specific login path options (clients only)
DATADIR/mysqld-auto.cnf | System variables persisted with SET PERSIST or SET PERSIST_ONLY (server only)

Notably on Windows `~/.my.cnf` is not read.

The solution is to invoke `mysql` with `--defaults-extra-file` flag pointing at the file we wrote.

**Comment by smallinsky** [comment]
@Tener Can we alter the tsh login  flow for Windows OS  and use one of the Windows MySQL Option files ?

**Comment by Tener** [comment]
> @Tener Can we alter the tsh login flow for Windows OS and use one of the Windows MySQL Option files ?

Yep, we can make `mysql` use the config file that we write. See #20397 for the fix.

@webvictim @corkrean can you take a look at #20397 to see if the fix works for you? `GOOS=windows GOARCH=amd64 make build/tsh` should build `tsh` as a Windows binary, usable on Windows after renaming to `tsh.exe`.
