### ISSUE TITLE
Docs for Azure MySQL/PostgreSQL flexible server database access integration

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#20046]
## Applies To
https://goteleport.com/docs/database-access/guides/azure-postgres-mysql/

## Details
Update Azure postgres/mysql access guide to include instructions for discovering Azure flexible servers.
Currently, our guide is for Azure single-server access. Single-server is being deprecated by Azure and will reach end-of-life in late 2024.

There are some differences in:
1. required db agent permissions in Azure
2. setting Azure active directory admin on flexi servers
3. static config of Azure databases

The db agent will need these additional permissions:
```diff
{
    "id": "*snip*",
    "properties": {
        "roleName": "DatabaseDiscovery",
        "description": "Test role for minimal permissions for azure db discovery",
        "assignableScopes": [
            "/subscriptions/060a97ea-3a57-4218-9be5-dba3f19ff2b5"
        ],
        "permissions": [
            {
                "actions": [
                    "Microsoft.DBforMySQL/servers/read",
                    "Microsoft.DBforPostgreSQL/servers/read",
+                    "Microsoft.DBforMySQL/flexibleServers/read",
+                    "Microsoft.DBforPostgreSQL/flexibleServers/read"
                ],
                "notActions": [],
                "dataActions": [],
                "notDataActions": []
            }
        ]
    }
}
```

There is a small change required for statically-registered Flexible servers as well, so we should update the reference database yaml config as well (static config should not be the focus of the guide though - we want the guide to remain focused on auto-discovery):
```diff
databases
  - name: exampledb
     protocol: mysql
     uri: exampledb.mysql.database.azure.com:3306
     static_labels:
       env: "dev"
     azure:
+       is_flexi_server: true
```

## Related Issues
https://github.com/gravitational/teleport/issues/18158

**Comment by smallinsky** [comment]
@GavinFrazar AFAIK Creation of flexi mysql/postgres AAD users differs a bit from creation of static db aad users. Could you provide examples ?

**Comment by GavinFrazar** [comment]
Ah you're right, that is different too (only for postgres though).

You have to do it like this for flexi server:
```
pgaadauth_create_principal_with_oid('example-dbuser', '00000000-0000-0000-0000-000000000000', 'service', false, false);
```
https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-manage-azure-ad-users#create-a-role-using-azure-ad-object-identifier

**Comment by alexfornuto** [comment]
Re: Updating the config file reference -  is `is_flexi_server:` default to `true`/`false` when not present, or is it required?

**Comment by GavinFrazar** [comment]
> Re: Updating the config file reference - is `is_flexi_server:` default to `true`/`false` when not present, or is it required?

it defaults to `false` when not present. It is only required to specify `true` when the db is a flex server.
