### ISSUE TITLE
Machine ID: PostHog Analytics (Server Side)

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#20067]
Machine ID should report various usage events to help estimate which features are and are not being used.

We can use the existing usage events / prehog reporters to submit events to the auth server, which will anonymize and forward events to our prehog endpoint when configured (currently only on cloud).

Ideas:
 * Auth server reported: we can derive some events on the server at e.g. bot join or create time
   * Bot join methods used (token, AWS IAM, GitHub Actions, etc)
   * General usage stats: setup (bot create) and usage (cert renewal), especially for a particular license ("how many customers have setup Machine ID" vs "how many customers are using Machine ID?")

**Comment by strideynet** [comment]
This will be considered in Q2 - anonymised client metrics will be first.

**Comment by strideynet** [comment]
Closing this in favour of a more detailed ticket in `teleport.e`
