### ISSUE TITLE
Prevent Teleport from clearing local terminal 

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#20068]
**What would you like Teleport to do?**
Today, after I use tsh ssh to log into a session, when I then exit the session, Teleport clears my terminal screen. I would like to disable this behavior. I would like tsh ssh to leave the output from the session in the terminal window when the session is closed, in the same way that ssh does by default.

**What problem does this solve?**
It allows us to reference data from previous sessions. For example, if we need to check the IP configuration on a node, we shouldn’t have to leave the session open if we need to copy/paste the IP address elsewhere.

**If a workaround exists, please include it.**

The only workarounds are in the shell/terminal applications themselves. For example, since I am using iTerm2 on macOS, I can enable the setting “Save scroll buffer when clearing screen”. Not everyone is using this terminal application or has access to the same workaround.

**Comment by zmb3** [comment]
I'm pretty sure it works this way by default and the clearing of the screen is enabled for FIPS mode.

**Comment by zmb3** [comment]
Yeah, see #6107 and #9767.

**Comment by zmb3** [comment]
@moisesmejia1200 did I answer your question here?

**Comment by moisesmejia1200** [comment]
Yes, thank you!
