### ISSUE TITLE
Allow s3 bucket for audit sessions and dynamodb to exist in different regions

### ISSUE THREAD

**Issue by darend** [gravitational/teleport#2007]
Currently when you use s3 for audit sessions and dynamodb for storage, they must exist in the same region. Supporting them existing in different regions would allow for more flexibility in how the resources are deployed.

For example: you may want to create a shared bucket in an account and have all your teleport clusters store their sessions within it without forcing everything to be exist in the same region.

**Comment by klizhentas** [comment]
I've added additional configuration
for the `audit_sessions_uri` parameter:

`audit_sessions_uri: s3://example.com/path?region=us-east-1`

Additional query parameter `region` will override
default `audit` section `region` if set.

**Comment by klizhentas** [comment]
Also it's worth documenting that `path` is possible to set, so sessions will be located in a separate path.

**Comment by kontsevoy** [comment]
LGTM
