### ISSUE TITLE
[Teleport Discover] Database Access - Day 1 - Design for V2 (Video Required)

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#20080]
Rethink the workflow so that the user can check every step of the Database access flow before moving on—or if that is impossible, so that they have easy remediation in the moment when the check/error happens, without having to restart the process over again.

Ensure we've planned for:
* Happy path (what happens if everything goes right)
* Each error (including messaging) that a user could encounter at each phase - work with @kimlisa to ensure we've captured everything that could go wrong
* Instructions/guidance for each step - now that we've worked out the technical details, we should be able to replace any Lorem Ipsum text.
* Testing (with actual customers or internally) - @roraback will pair with you on this!

**Comment by zmb3** [comment]
@roraback @rishibarbhaya-design just checking on this old issue. Is there any other work planned here or can we close it out?

**Comment by roraback** [comment]
Closing out, will track additional work in Notion until planned
