### ISSUE TITLE
scp transfer progress needs to be more granular

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2009]
Curently `tsh scp` only updates its stdout after processing each file. From @jddonz :

Would it be possible to add a progress meter to tsh scp similar to ssh scp? Currently there is no feedback that the transfer is in progress, only when it finishes:

```
tsh scp file.tgz user@host:
-> file.tgz (0)
```

For small files this isn't an issue but with larger files it is nice to be able to see the progress.

**Comment by zmb3** [comment]
@capnspacehook something for you to consider when you add client-side support for SFTP ^
