### ISSUE TITLE
 DB connection breaks and the db service is not accessible through teleport during upgrade

### ISSUE THREAD

**Issue by pnrao1983** [gravitational/teleport#20126]
When we test [this](https://goteleport.com/docs/management/admin/upgrading-the-teleport-binary/), the node connection is fine, and active connections are not disconnected or impacted, but the db connection breaks and the db service is not accessible through teleport and all the DB connections disappear from the Teleport Web UI: below is the reconnect message
<img width="1499" alt="Screenshot 2023-01-12 at 10 11 10" src="https://user-images.githubusercontent.com/115497626/212103917-e54b59b1-e591-49b8-8387-99e966ce95e0.png">

No connection. Trying to reconnect...
DEBU             Using ping connection alpnproxy/local_proxy.go:170
ERROR 1105 (HY000): database "rds-mysql" not found among registered databases in cluster "ip-172-31-20-162-us-west-1-compute-internal"
ERROR:
Can't connect to the server

**Comment by greedy52** [comment]
Just a quick update, I am able to repro similar behaviour. 

In my testing, the existing SSH connection is fine during upgrade as the old/parent process would wait for the connection to finish before exiting. DB agent on the other hand does NOT wait and kills the connection. 

A separate issue is that the child/new db agent process fails to heartbeat for some time and it eventually covers in a few minutes
```
2023-01-30T20:10:02Z WARN [DB:SERVIC] Keep alive has failed: key /databaseServers/default/f930e8a0-5192-42c0-872c-713fca7e3fa7/f930e8a0-5192-42c0-872c-713fca7e3fa7 is not found. srv/heartbeat.go:609
2023-01-30T20:10:02Z WARN [DB:SERVIC] Heartbeat failed keep alive channel closed. srv/heartbeat.go:282
```
This causes tsh db ls to show an empty list and new connections would fail until the heartbeat is recovered.

**Comment by greedy52** [comment]
For the second issue where db servers disappear after QUITing the parent
https://github.com/gravitational/teleport/blob/7c4bba74140513eb0e55a351c6dd49f727337103/lib/srv/db/server.go#L538-L542
so the db agent on close (in this case the parent) will explicitly delete the heartbeat.

**Comment by greedy52** [comment]
@pnrao1983 as stated in #21156, the fix prevents db servers from disappearing during the upgrade process. This also means that the connection will still break but an immediate reconnect will be fine. 

A separate issue #21158 is created for waiting for connections during a graceful shutdown. There is currently no plan yet to fix that in the coming release as it may require product discussions on whether we want to wait forever for the live connections before shutting down.
