### ISSUE TITLE
Support base64URL encoding of webauthn challenges on server and client side

### ISSUE THREAD

**Issue by tobiaszheller** [gravitational/teleport#20122]
`go-webauthn/webauthn` in release v0.6.0 changed encoding of challenges during registration/login, details (https://github.com/go-webauthn/webauthn/pull/82). 

Updating `teleport` server or `tsh` client to v0.6.0 will break login/registration flow if one of server/client is using old version (unmarshaler expects base64 encoding and throws an error when standard base64 is used). 
It will however in web version, because we are less strict there: [base64urlToBuffer](https://github.com/gravitational/webapps/blob/5e80f7f88fce2628a88629c103f71da3da229fd0/packages/shared/utils/base64/base64url-arraybuffer.ts#L19-L26) supports both base64 and base64url.

We need to support scenario when server is using new version of webauthn and `tsh` is using old one (the one with strict encoding check). This can be solved by extending message used during registration/login, it should contain now both, old was of encoding challenge (to support old clients) and new one. We should support both fields for at least couple versions before dropping it.  
Webapps part should also be updated in order to support new field. 

Bug details:
- Teleport version v11, v10, v9

**Comment by codingllama** [comment]
Related: https://github.com/gravitational/teleport/pull/29750.

Solved by not solving - we'll keep using standard b64 encoding for the foreseeable future. WebAuthn challenges (and alike information) are not encoded in URLs, only in the bodies.
