### ISSUE TITLE
Command line arguments don't support quoting

### ISSUE THREAD

**Issue by onitake** [gravitational/teleport#2017]
**What happened**:
Teleport doesn't parse quotes around command line arguments properly.

For example, quotes around the --auth-server= argument result in the following error message:
```
Failed to dial auth server "my.master.node:3025": dial tcp: address tcp/3025": unknown port. auth/clt.go:92
```
Note the solitary quote after tcp/3025".

This also applies to other options that require arguments.

**What you expected to happen**:
Quoting or double-quoting command line arguments should not change the interpretation or their values, as is common in most software.

**How to reproduce it (as minimally and precisely as possible)**:
Run teleport like this:
```sh
teleport start -d --roles=node --token="SECRET TOKEN" --auth-server="my.master.node:3025"
```

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.6.1 git:v2.6.1-0-g63d4968f
- Tsh version (use `tsh version`): Teleport v2.6.1 git:v2.6.1-0-g63d4968f
- OS (e.g. from /etc/os-release): CentOS Linux 7

**Browser environment**
(not applicable)

**Relevant Debug Logs If Applicable**
(not applicable)

**Comment by russjones** [comment]
@onitake The shell should remove quotes for you, we tried to reproduce and could not. If you are still running into this issue, please create another ticket.
