### ISSUE TITLE
Teleport Connect: Custom shortcuts

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#20176]
Hey Team,

In order for me to use Teleport connect terminal every day, I'd need to bring my usual shortcuts. Here is a list I use:

```
Ctrl-+ Next tab (Right now increases / decreases font)
Ctrl-- Previous tab
Ctrl-Shift-T Create new terminal
```

**Comment by gzdunek** [comment]
Probably you know it, but we already have shortcuts for prev/next:
```
'tab-previous': 'Control-Shift-Tab',
'tab-next': 'Control-Tab',
```
We don't have a shortcut for opening a terminal tab.

### Customization 
We recently added a new config service that uses `app_config.json` file to store user settings. For now, we're only storing usage reporting information there (enabled/disabled). We explicitly disabled configuring other things, like keyboard shortcuts (we were considering adding a validation to it). 
After we add it, you should be able to edit `app_config.json` and put there new values to override the defaults.
(And we will have to add a new config key for creating a terminal tab).

We can think of adding a GUI for changing the settings, but it requires more work.

**Comment by klizhentas** [comment]
@gzdunek I'd be happy with just editing `app_config.json` somewhere in my home folder. Once you add it, please add to the docs and we will consider this part done.

**Comment by zmb3** [comment]
This has been completed. Docs are here: https://github.com/gravitational/teleport/issues/21803

**Comment by revolution1964** [comment]
Is it possible to set ctrl-c to copy and and ctrl-v to paste?  The default drives me crazy.  I'm not sure what they do, but they mess me up everytime I use Teleport Connect because all my other linux terminals assign these to copy/paste.

**Comment by revolution1964** [comment]
Is there any way to get it so that when you highlight something in the terminal, it is copied automatically into the buffer?

**Comment by revolution1964** [comment]
I use autohotkey for various tasks.  I was able to add the ctrl-v and auto copy to clipboard with these autohotkey macros.  Use at your own risk.  They work pretty good for me.

 #IfWinActive ahk_exe Teleport Connect.exe
 ^v::
 send +{insert}
return

#IfWinActive ahk_exe Teleport Connect.exe
~LButton Up::
    send ^{insert}
return

**Comment by gzdunek** [comment]
Hello @revolution1964!

Currently it is not possible to automatically copy the selected text. I added a task for it (https://github.com/gravitational/teleport/issues/24451), but it is hard to me to provide any ETA. 
Thanks for posting the temporary solution!
