### ISSUE TITLE
Review AWS bootstrap partial file.

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/teleport#20170]
It's worth noting that this guide contains an edited version of the contents in `docs/pages/includes/database-access/aws-bootstrap.mdx`. I'm still learning about the `bootstrap` command and don't know if the changes should be applied to the partial for other docs.

_Originally posted by @alexfornuto in https://github.com/gravitational/teleport/issues/20168#issuecomment-1381068582_
      
Compare the version found [here](https://github.com/gravitational/teleport/pull/20168/files#diff-44e8d236ecda11852ee6c0ed323afc9e08502172b2ee5fbfb7f43bad0c7ac6c1R244-R289) with the partial file, and determine if the changes should be applied to the partial file itself.

If so, don't forget to update `redshift-serverless.mdx` to use the partial file again.

**Comment by ptgott** [comment]
Closing as complete since we refactored these docs in https://github.com/gravitational/teleport/pull/45459
