### ISSUE TITLE
Allow usage of WSL for Teleport Connect

### ISSUE THREAD

**Issue by SoulKyu** [gravitational/teleport#20186]
What would you like Teleport to do?
Would be insane if we could use our WSL on teleport console when connecting to a Kubernetes cluster

![image](https://user-images.githubusercontent.com/30684712/212345618-20d25210-ee26-4c51-9f41-78db8a7057d1.png)
Actually, it will open powershell by default, maybe, it could use wsl.exe instead ? 

All my dev setup is on it !

What problem does this solve?
Will allow teleport connect to work with WSL.

If a workaround exists, please include it.
I didn't find any atm

**Comment by ravicious** [comment]
Related: #19392

On macOS and Linux, we use [`os.userInfo`](https://nodejs.org/docs/latest-v16.x/api/os.html#osuserinfooptions) to get the preferred shell of the user. We should find a way to get this info from the system on Windows (though I believe Windows doesn't have the equivalent of `chsh` and similar commands) or make it configurable.

**Comment by SoulKyu** [comment]
Couldn't you not just say if you are on windows, you are able to use cmd.exe, powershell or wsl.exe ?
