### ISSUE TITLE
tsh scp strconv error

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#20234]
**Current behavior:**
This command `tsh --proxy=example.com scp -P "file.txt" ubuntu@hostname:/home/ubuntu` results in this error `"ERROR: strconv.ParseInt: parsing "file": invalid syntax"`.

It seems strange that tsh is trying to convert the source string to an int. 

Bug details:
- Teleport version: 11.2.1

**Comment by corkrean** [comment]
Actually, this is a docs issue. The -P is unnecessary.

**Comment by zmb3** [comment]
I'm going to close this since you already have a PR open
