### ISSUE TITLE
Support authenticating users in a trusted domain AD setup

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#20233]
### What would you like Teleport to do?

In the case of an active directory with trusted domains, Teleport should be able to specify the domain along with the username.

### What problem does this solve?

Currently, if Teleport tries to authenticate a user that is in a different domain, it explicitly specifies the domain name as seen in the teleport.yaml config file. This causes an authentication failure when trying to connect to a resource that is on the other domain.

For example, an MSP sets up the domains for all its customers. The MSP has its own domain that is trusted by the customer domains. Employees at the MSP authenticate to their domain and can access the appropriate resources connected to customer domains.

When adding Teleport to the mix, this should still be possible. It should be able to recognize that the resource is in a different domain and present the correct username structure.

Currently, the result is the end user is asked to type their password or pin (or whatever non-smartcard auth that is available).

### If a workaround exists, please include it.

none - The MSP employees only have accounts in their own domain. They don't have users provisioned on the dozens of customer active directory domains and instead use the trusted domain feature to gain access.

**Comment by zmb3** [comment]
This is resolved in #33218 (to the extent we're planning to support - users and hosts must still be in the same domain)
