### ISSUE TITLE
Add Alias for Servers

### ISSUE THREAD

**Issue by StudentSA** [gravitational/teleport#20259]
When setting up multiple ssh servers they get added to the Teleport UI using their host names. Unfortunately most of the hostname of my servers are very non descriptive. AWS's default server hostname would be something like "ubuntu@[local ip address]". I also have servers with non descriptive hostnames like server1, server2, server3.

Is it possible to add an alias, or some textual info about a server so that I can easily identify them in the list of many servers.

Thanks.

**Comment by zmb3** [comment]
You can set the name yourself using the `nodename` property in teleport.yaml so that it doesn't default to the hostname.

Alternatively, you can use labels to attach arbitrary key/value pairs to nodes, and even use those labels to connect to servers as an alternative to specifying the hostname.
