### ISSUE TITLE
Support for multiple resource versions in operator

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#20261]
What would you like Teleport to do?

Support for multiple resource versions in the operator

**Comment by hugoShaka** [comment]
Status update: The design problem blocking RoleV6 and RoleV7 implementation has been resolved [in RFD-160](https://github.com/gravitational/teleport/pull/35954).

**Comment by hugoShaka** [comment]
Closed by https://github.com/gravitational/teleport/pull/37288

Starting with Teleport 15, the operator supports `TeleportRoleV6` and `TeleportRoleV7` CRs.

We will rename existing resources for consistency in a future Teleport version (e.g. `TeleportRole` will become `TeleportRoleV5`, `TeleportUser` will become `TeleportUserV2`, ...). This will likely happen in v16.
