### ISSUE TITLE
Clarify `tsh` instructions in the Docker guide

### ISSUE THREAD

**Issue by slacker247** [gravitational/teleport#20268]
## Applies To

https://goteleport.com/docs/management/guides/docker/

## Details
Unless I am mistaken, step 4/4 with the tsh command should be run as a docker exec command not a generic console command.
When I run this command and enter nothing for the password and the pin, it says invalid.  Is there somewhere I should be creating this?  I enter the 9999999 and it says the same thing.
On building this on a debian instance, I think I missed the step when creating the user asks you to go to the URL to set the password.  Perhaps due to the output response from creating the user is not formatted well.

Also you map 3080 indicating that the web portal is on port 80 http.  When it's actually 443, or https.  Add clarifying words or map it to 3443 instead?
Also, you do not have -d for running the docker instance and it just shows the logs.  Which you have to control-C out of which terminates the instance.

**Comment by strideynet** [comment]
I believe that running `tsh` outside of the container is correct here, but, we should probably include instructions on how to install `tsh` on the host operating system as the guide currently just assumes `tsh` is installed.

Yes, you will need to visit the link to setup the user's password and TOTP pin, without this step, you will not be able to log in to the user using `tsh`. If you have lost this link, you can create a new user following the same steps with a different username and then once you are able to access Teleport, delete the old user.

As for the port of the Proxy's web console, `3080` would be correct if Teleport Proxy is running in insecure mode without the necessary certificates setup for TLS. Personally, I think we ought to rewrite this guide to suggest using LetsEncrypt to fetch a valid TLS certificate. I don't recommend using Teleport in insecure mode for anything other than experimental use on your local machine.

**Comment by slacker247** [comment]
it's secured using a self signed cert.  Which is why it required https 443 while it's pointing to 3080.
To clarify I got side tracked trying to figure out why I couldn't connect to the teleport site using http 80
and that is why I lost sight of the url to set the user's password.

While letsEncrypt is fine.  I use it on my resume website.  I would not suggest it be forced upon someone just testing out the system.  As I'm about to describe below.  I am not moving forward with your product.

I don't like it.
First I was unable to get a client to connect.
When trying to add a server to the debian install
"failed to join the cluster"
When trying to add a server to the docker install
"The token may be expired or invalid."
So it's wasting my time.  I've already wasted enough time trying to setup a user account.
Also, I run debian, it is not a port blocking issue.  I do not have iptables running.
No I am not helping you diagnose the problem.  I run a simple install of debian and docker.
oh, I guess I force install python 3.6 through pyenv if your software is reliant on python.
you can test it and figure it out.  I'm going to spend my time seeing if someone makes a better product.
I noticed when I uninstalled teleport from the client it reconfigured docker.  it may have been just updating docker.
since it didn't do it the subsequent times I installed and removed telelport from the client.

Why does it even have a client install?
Do you know how many computers I have in my network?
way to many to be installing a client on every single one
definitely when it complains it can't connect.
Why not just have a web based telnet, ssh, rdp client?
Not sure how important a mysql client would be, but sure a web based one of those.

Some other features would be nice.
Some kind of web proxy to connect to internal sites.
Supposedly you have this feature but I have to have a client node and configure that functionality
something similar to angry ip scanner
Something similar to spiceworks then you wouldn't need angry ip scanner
Possibly something to browse network file shares

Since this is the first time I am being made aware of a product like yours.  
I'm now looking to see who else makes a similar product.
Currently I am using HaProxy to connect to internal websites.
It would be nice if I had something a little more robust.
And your product seems to be targeting or built around kubernetes, which I do not use.

**Comment by ptgott** [comment]
Closing because we are removing the Docker getting started guide as part of our effort to simplify the getting started experience (https://github.com/gravitational/teleport/pull/25415). For Docker instructions, you can use our installation guide (https://goteleport.com/docs/installation/#docker).
