### ISSUE TITLE
Release binaries link in README.md points to github releases instead of new download page

### ISSUE THREAD

**Issue by aashley** [gravitational/teleport#2026]
Wondering when/if release binaries will be available for the 2.6 series OSS releases?

**Comment by aashley** [comment]
Finally found the new download location, can probably change this to a documentation update for the README.md in the repository which still directs users to the github releases page for binary downloads

**Comment by aashley** [comment]
Admin Manual also still directs to github releases page

**Comment by kontsevoy** [comment]
Thanks @aashley !
