### ISSUE TITLE
Machine ID should not fail when running as an undefined user

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#20309]
Expected behavior:

If run as a user with no `/etc/passwd` entry, Machine ID shouldn't fail.

Current behavior:

Currently certificate renewal fails with an error like this:
```
WARN [TBOT]      Renewal attempt 1 of 5 failed. Retrying after 778.980791ms. error:[
ERROR REPORT:
Original Error: user.UnknownUserIdError user: unknown userid 9807
Stack Trace:
	github.com/gravitational/teleport/lib/tbot/config/destination_directory.go:171 github.com/gravitational/teleport/lib/tbot/config.(*DestinationDirectory).Verify
	github.com/gravitational/teleport/lib/tbot/renew.go:609 github.com/gravitational/teleport/lib/tbot.(*Bot).renew
	github.com/gravitational/teleport/lib/tbot/renew.go:686 github.com/gravitational/teleport/lib/tbot.(*Bot).renewLoop
	github.com/gravitational/teleport/lib/tbot/tbot.go:247 github.com/gravitational/teleport/lib/tbot.(*Bot).Run.func3
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: user: unknown userid 9807] tbot/renew.go:695
```

In this case, the UID `9807` is the user specified in our Helm charts. If users try to run `tbot` in an `initContainer` from our published docker image, it fails with the above error.

The error is produced by `user.Current()` failing to look up the non-existent username: https://github.com/gravitational/teleport/blob/11d58e25c7b04a1b68677703b12b17fb9557d056/lib/tbot/config/destination_directory.go#L169

We probably only need the uid for ACL verification, so if possible we should drop the dependency on the named user. Otherwise, we should at least have some method to avoid failing, maybe by disabling ACLs or verification (with whatever caveats that may entail).

Bug details:
- Teleport version: 11.2.1
- Recreation steps
- Debug logs

**Comment by strideynet** [comment]
I think my preference here would be to drop dependency on the named user - https://pkg.go.dev/os#Getuid should do the trick here.

**Comment by russjones** [comment]
Will be fixed by https://github.com/gravitational/teleport/issues/20310.

**Comment by hugoShaka** [comment]
#20310 will provide a workaround for users to deal with `tbot`'s user limitation. However, I believe this issue is still valid and `tbot` should be able to run in constrained environments with users without passwd entry.

**Comment by strideynet** [comment]
Running `tbot` statically compiled with `glibc` on another system yielded: `ERROR: user: lookup userid 1983: invalid argument`.

Further evidence we should support falling back to something sane here, as it'll solve what I just ran into as well as the initial issue.
