### ISSUE TITLE
`tctl edit` breaks SAML connectors

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#20326]
Expected behavior:

`tctl edit` allows to succesfully edit saml connectors.

Current behavior:

`tctl edit saml/my-connector` removes (secret) `spec.signing_key_pair.private_key` field from the spec.

Note: I didn't test other resource types; it is possible they have a similar issue.

Bug details:
- Teleport version: `Teleport Enterprise v12.0.0-alpha.1 git:api/v12.0.0-alpha.1-0-g8144a7e843 go1.19.5`
- Recreation steps:

```
# observe private key in connector definition is present
> tctl get saml/my-connector --with-secrets --format=json | jq '.[0].spec.signing_key_pair.private_key'
"-----BEGIN RSA PRIVATE KEY-----\nMIIEpQ..."

# edit connector, save file, close it
> TELEPORT_EDITOR="code --wait" tctl edit saml/my-connector
authentication connector 'my-connector' has been created

# observe private key in connector definition is missing
> tctl get saml/my-connector --with-secrets --format=json | jq '.[0].spec.signing_key_pair.private_key'
""
```

Caused by: https://github.com/gravitational/teleport/pull/18826

---

Found when testing SSO connectors for v12 release (https://github.com/gravitational/teleport/issues/20132).

**Comment by zmb3** [comment]
Good catch @Tener!
