### ISSUE TITLE
Not possible to `tsh login` with OTP when another MFA is added with TouchID on WebUI 

### ISSUE THREAD

**Issue by hydezhao** [gravitational/teleport#20322]
Expected behavior:

`tsh login` should be able to choose OTP as MFA for login

Current behavior:

When setup an account with 2 MFA:
1. OTP
2. Hardware Key with Touch ID registered with WebUI

And do `tsh login`
I got prompt: 
```
 tsh login --user=yzhao
Enter password for Teleport user yzhao:
Tap any security key
```
and got blocked at this step. I have to delete the hardware key from webUI to unblock the login.

PS: I tried `--mfa-mode=cross-platform` it doesn't help. `--mfa-mode=cross-platform` does the trick when there is a TouchID setup with `tsh mfa add`. 

Bug details:
- Teleport version: 11.2.1
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
`--mfa-mode=otp`?

**Comment by hydezhao** [comment]
Effectively ! My bad !

**Comment by hydezhao** [comment]
I closed the ticket too quickly : 

When i registered touchID with CLI and try `--mfa-mode=otp`

```
$ tsh mfa ls
Name       Type     Added at                      Last used
---------- -------- ----------------------------- -----------------------------
otp-device TOTP     Thu, 19 Jan 2023 08:01:17 UTC Thu, 19 Jan 2023 08:06:44 UTC
touch-cli  WebAuthn Thu, 19 Jan 2023 08:06:47 UTC Thu, 19 Jan 2023 08:07:22 UTC
```

```
$ tsh login --user=yzhao --mfa-mode=otp
Using platform authenticator, follow the OS prompt
```

**Comment by hydezhao** [comment]
Even if I remove the touch-id, CLI keeps requiring me with OS prompt:
```
$ tsh mfa rm touch-cli
Using platform authenticator, follow the OS prompt
MFA device "touch-cli" removed.

$  tsh logout
Logged out all users from all proxies.

$  tsh login --user=yzhao
Using platform authenticator, follow the OS prompt
ERROR: invalid Webauthn response
```
Are there some cache on my PC that I should cleanup ?

**Comment by zmb3** [comment]
@codingllama thoughts?

**Comment by hydezhao** [comment]
@codingllama thanks a lot! effectively with this "hidden" command things work better.

**Comment by codingllama** [comment]
Glad to hear it. I'm pushing the --mfa-mode=otp fix to release branches, once it lands, assuming it's all working for you, feel free to close the issue.
