### ISSUE TITLE
`tctl` no longer defaults to local auth connection when no config is provided

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#20346]
### Expected behavior:

I run `tctl` on a machine without `/etc/teleport.yaml` file, nor `TELEPORT_CONFIG_FILE` env var, nor `-c` CLI flag, nor `~/.tsh` directory.

`tctl` tries to connect to a local auth server.

### Current behavior:

`tctl` returns the following error:
```
ERROR: no profile provided and no current profile
```

Passing an empty configuration file makes tctl try to connect to the local auth
```
tctl status -c /dev/null
```

Most of our Helm guides rely on `tctl` to work out of the box to create new users with `tctl users add`. The Helm chart does not stores its config in `/etc/teleport.yaml` but in `/etc/teleport/teleport.yaml`, which triggers the bug.

### Recreation steps

Expected behaviour in v11
```shell
docker run -it --entrypoint="" --platform=linux/amd64 public.ecr.aws/gravitational/teleport:11.0.0 tctl status
ERROR: Could not load Teleport host UUID file at /var/lib/teleport/host_uuid. Please make sure that Teleport is up and running prior to using tctl.
lstat /var/lib/teleport: no such file or directory
```

Unexpected behaviour in v12.0.0-alpha.1
```shell
docker run -it --entrypoint="" --platform=linux/amd64 public.ecr.aws/gravitational/teleport:12.0.0-alpha.1 tctl status
ERROR: no profile provided and no current profile
```

Expected behaviour with v12 and empty config
```shell
docker run -it --entrypoint="" --platform=linux/amd64 public.ecr.aws/gravitational/teleport:12.0.0-alpha.1 tctl status -c /dev/null
ERROR: Could not load Teleport host UUID file at /var/lib/teleport/host_uuid. Please make sure that Teleport is up and running prior to using tctl.
lstat /var/lib/teleport/host_uuid: no such file or directory
```

**Comment by hugoShaka** [comment]
Bisecting points to this commit: 488af75797326e92145497955fdadbd97711171b

**Comment by espadolini** [comment]
This regression notwithstanding, shouldn't we explicitly run `tctl --config /path/to/teleport.yaml` in our charts/automation regardless?

**Comment by hugoShaka** [comment]
The chart already sets the config path on each command it invokes, but the initial setup process requires users to manually `exec` in an auth pod and use `tctl users add` to bootstrap their first user. We could change all the documentation instances where we tell them to do so, but I think it would reduce readability.
