### ISSUE TITLE
Access check fails when using IAM role ARNs as db_users in user roles

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#20359]
Found by #20168

Expected behavior:
`tsh db connect --db-user <role-name> --db-name <db-name> redshift-serverless-wg` should succeed.

Current behavior:
```
connection to server at "localhost" (127.0.0.1), port 59922 failed: access to db denied. User does not have permissions. Confirm database user and name.
```
The current workaround is to specify the "short" role name (instead of the ARN) in `db_users`.

Bug details:
- Teleport version: v12
- Recreation steps
  - `tctl users update --set-db-users arn:aws:iam::<account-id>:role/steve-redshiftserverless-readonly alice`
  - `tsh login --proxy <proxy> --user alice`
  - `tsh db connect --db-user steve-redshiftserverless-readonly --db-name test steve-wg`

We currently do a "dumb" comparison such that `--db-user` match one of `db_users`. So if AWS role ARNs are used in `db_users`, using short role names in `tsh db connect --db-user <role-name>` will fail the match. This is also true the other way where an ARN is used as `--db-user` but short role names are used in `db_users`.

This problem should apply to all AWS databases that impersonate an IAM role: Keysapces, DynamoDB, Redshift Serverless

**Comment by alexfornuto** [comment]
Note that when this issue is resolved we will need to review many docs (not just the one linked) to update references to "short" role names in Teleport role definitions.
