### ISSUE TITLE
`tctl edit` cannot edit cluster auth preference

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#20360]
Expected behavior:
`$ tctl edit cap` allows me to change cluster auth preference settings.

Current behavior:
When I try to change any setting, it returns an error.

Bug details:
- Teleport version: v12.0.0-alpha.1
- Recreation steps:
```
$ tctl edit cap
ERROR: renaming resources is not supported with tctl edit
```
(I changed `spec.disconnect_expired_cert` from true to false, not `metadata.name` in this case)
- Debug logs:
```
ERROR REPORT:
Original Error: *trace.NotImplementedError renaming resources is not supported with tctl edit
Stack Trace:
	github.com/gravitational/teleport/tool/tctl/common/edit_command.go:129 github.com/gravitational/teleport/tool/tctl/common.(*EditCommand).TryRun
	github.com/gravitational/teleport/tool/tctl/common/tctl.go:208 github.com/gravitational/teleport/tool/tctl/common.TryRun
	github.com/gravitational/teleport/tool/tctl/common/tctl.go:97 github.com/gravitational/teleport/tool/tctl/common.Run
	github.com/gravitational/teleport/tool/tctl/main.go:27 main.main
	runtime/proc.go:250 runtime.main
	runtime/asm_arm64.s:1172 runtime.goexit
User Message: renaming resources is not supported with tctl edit
```t

**Comment by zmb3** [comment]
Good catch. I missed this.

The resource is named `cluster-auth-preference`, but you invoke it with `tctl edit cap` or `tctl edit clutser_auth_preference` so there appears to be a mismatch.

I'll fix it by pulling the original name from the YAML instead of what's provided on the command line.
