### ISSUE TITLE
getCertAuthority wastes a lot of bandwidth

### ISSUE THREAD

**Issue by josephduchesne** [gravitational/teleport#2036]
**What happened**:
An idle teleport node uses:
~0.33kB/s bandwidth at all times. (hires polling at 10s)
~0.11kB/s bandwidth at all times. (hires polling at 90s)
~0.10kB/s (getCertAuthority commented out in syncServiceRotationState)

**What you expected to happen**:

I would expect an idle SSH connection manager to use less bandwidth.
For comparison, an otherwise unused openssh tunnel uses 0.03kB/s (less than 1/8 the amount)

The bulk of this appears to be authority's getCertAuthority, which is requesting a 2.3kB JSON blob of certificate data every 10 seconds. The blob contents doesn't seem to change very often (I didn't see it chage at all).

**How to reproduce it (as minimally and precisely as possible)**:
I used `sudo nethogs -c 120 -d 1 -v 3 -t $INTERFACE` to watch traffic on a per connection basis.

**Environment**:
- Teleport version (use `teleport version`): master as of today
- OS (e.g. from /etc/os-release): Ubuntu 14.04 (auth+proxt) and 18.04 (node)

**Comment by klizhentas** [comment]
what you would be comfortable with? e.g. if I make it every minute, will this help?

**Comment by klizhentas** [comment]
we are going to replace it with event driven approach, but for now this is what we have to deal with

**Comment by josephduchesne** [comment]
I saw the comment about polling just being a placeholder while in the code. I've got an internal build where I run that every 90s, , but I'm not sure what ramifications changing this has.

How often is the cert supposed to change? With otherwise default configurations are there any keys that are likely to expire with 60sec old certs?

My main concern is keeping low bandwidth for our customers, some of whom are on per-gigabyte data-plans. Current default configuration is ~38MB/month (just the openssh reverse tunnel).

With 60s cert updates, things would probably be much more palatable (171MB/month total at 12h/day idle bandwidth usage). This is much better than the ~418MB that the current configuration would blow through.

Is there a possibility of adding automatic compression inline to all api requests as an option? I implemented it (just for the marshal/unmarshal of this request), but it broke the server (I believe because it was trying to decode un-gzipped values from disk, if it's using the same json marshaling to store state- I didn't have a chance to dig deeper).

JSON is pretty bandwidth inefficient since it's restricted to a small subset of ASCII and entirely uncompressed. Having a more efficient option would be nice, and might be able to be handled entirely transparently to the higher level of the app if it was entirely handled at the API layer (especially if it was client-driven, since the web API use case wouldn't really need this).

**Comment by aashley** [comment]
Has there been any progress on this issue? We're working on a bandwidth reduction project for our product and have identified Teleport as one of the heavier users. At idle we're seeing 180M/per day of data for Teleport.

Our setup is for trusted cluster between the remote node and the cloud setup, so it's not entirely like the situation this ticket was opened for. Each deployed product is a self contained server that can be deployed behind a random firewall.

**Comment by klizhentas** [comment]
we have planned switching to event driven system that will reduce this traffic to 0 right after 3.0 release, so that's coming hopefully soon.

**Comment by aashley** [comment]
Any ETA on the 3.0 release? Even just a ballpark so I can take it into account in our project planning.

**Comment by klizhentas** [comment]
We are planning to release 3.0 in a couple of weeks from now, then we are going to work on event-driven API for notifications. So ETA on this particular feature is not clear yet. I'm going to take a look though at what could be done to reduce the traffic in the shorter term.
