### ISSUE TITLE
darwin: tsh doesn't respect private CAs installed in System.keychain

### ISSUE THREAD

**Issue by mumoshu** [gravitational/teleport#2042]
**What happened**:

```
$ sudo security add-trusted-cert -d -r trustRoot -k "/Library/Keychains/System.keychain" path/to/my/ca.pem

$ tsh --proxy=teleport.example.com --debug --auth=onelogin login

ERROR REPORT:
Original Error: *trace.ConnectionProblemError x509: certificate signed by unknown authority
Stack Trace:
	/Users/mumoshu/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:110 github.com/gravitational/teleport/lib/httplib.ConvertResponse
	/Users/mumoshu/go/src/github.com/gravitational/teleport/lib/client/https_client.go:81 github.com/gravitational/teleport/lib/client.(*WebClient).Get
	/Users/mumoshu/go/src/github.com/gravitational/teleport/lib/client/weblogin.go:328 github.com/gravitational/teleport/lib/client.Ping
	/Users/mumoshu/go/src/github.com/gravitational/teleport/lib/client/api.go:1295 github.com/gravitational/teleport/lib/client.(*TeleportClient).Login
	/Users/mumoshu/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:337 main.onLogin
	/Users/mumoshu/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:266 main.Run
	/Users/mumoshu/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:147 main.main
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:207 runtime.main
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2362 runtime.goexit
User Message: Get https://teleport.example.com:3080/v1/webapi/ping/onelogin: x509: certificate signed by unknown authority
```

However, [requesting to the same http endpoint with curl does succeed](https://gist.github.com/mumoshu/33259e2b18199fe8ba50f9581e480d52).

Reading some golang code, it turns out that `tsh`, more specifially the api client defined in `lib/client/api.go`, seems to load the root CA cert from `/var/lib/teleport/webproxy_cert.pem` only.

So after copying my private CA cert there:

```
sudo mkdir -p /var/lib/teleport
sudo chown $USER /var/lib/teleport
cp pki/ca.pem /var/lib/teleport/webproxy_cert.pem
```

It starts working:

```
$ tsh --proxy=teleport.example.com --debug --auth=onelogin login
If browser window does not open automatically, open it by clicking on the link:
 https://MY_IDP_AUTH_ENDPOINT/...
```

**What you expected to happen**:

`tsh login` just works against the proxy with the tls cert signed by my private, but trusted CA.

**How to reproduce it (as minimally and precisely as possible)**:

Install Teleport with the helm chart proposed in #2014, and run the commands in the beginning of this issue.

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by kontsevoy** [comment]
Looks like Golang added support for MacOS keychains to crypto/x509 a while ago. Should be automatically picked up by `tsh`:

https://go-review.googlesource.com/c/go/+/20351

**Comment by bcg62** [comment]
we see this on teleport builds produced by homebrew, the official releases hosted by teleport do not behave the same way.

I don't have details as to why.

**Comment by kontsevoy** [comment]
@bcg62 thank you for clarification. We do not maintain the homebrew package, it's community-supported and you should report this to whoever maintains that package. (maybe it's just too old?)
