### ISSUE TITLE
Setting Azure identities doesn't support all valid characters

### ISSUE THREAD

**Issue by mdwn** [gravitational/teleport#20434]
Expected behavior:

```
tctl users update teleport-admin --set-azure-identities /subscriptions/<xxxxx>/resourceGroups/az-cli-access_group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/teleport-azure
```

Should succeed.

Current behavior:

It fails.

Bug details:
- Teleport version: 12.0.0-alpha.1
- Recreation steps
  - Try to set the azure identities for a user with the resource group containing underscores.
- Debug logs

```
ERROR: Azure identity "/subscriptions/<xxxxx>/resourceGroups/az-cli-access_group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/teleport-azure" has invalid format.
```

**Comment by mdwn** [comment]
Looks like I can use `tctl edit` to alter the identity to one that uses an underscore, though.

**Comment by Tener** [comment]
I guess we need to relax the regexp for allowed Azure identities.

**Comment by GavinFrazar** [comment]
@Tener noticed you have this comment regarding `arm.ParseResourceID`:
```
// ParseResourceID from Azure SDK is too lenient; we use a strict regexp instead.
var azureIdentityPattern = regexp.MustCompile(`(?i)^/subscriptions/([a-fA-F0-9-]+)/resourceGroups/([0-9a-zA-Z-]+)/providers/Microsoft\.ManagedIdentity/userAssignedIdentities/([0-9a-zA-Z-]+)$`)
```

The obvious reason for it being "too lenient" is that any valid resource ID would pass the check - but is it still too lenient if we check for `parsedID.Provider == "Microsoft.ManagedIdentity"`?

**Comment by Tener** [comment]
> @Tener noticed you have this comment regarding `arm.ParseResourceID`:
> 
> ```
> // ParseResourceID from Azure SDK is too lenient; we use a strict regexp instead.
> var azureIdentityPattern = regexp.MustCompile(`(?i)^/subscriptions/([a-fA-F0-9-]+)/resourceGroups/([0-9a-zA-Z-]+)/providers/Microsoft\.ManagedIdentity/userAssignedIdentities/([0-9a-zA-Z-]+)$`)
> ```
> 
> The obvious reason for it being "too lenient" is that any valid resource ID would pass the check - but is it still too lenient if we check for `parsedID.Provider == "Microsoft.ManagedIdentity"`?

Unfortunately, yes. For example: take a look at https://github.com/Azure/azure-sdk-for-go/blob/sdk/azcore/v1.3.0/sdk/azcore/arm/resource_identifier.go#L64. The Azure SDK parser will first split the identifier on `/` and then discard empty sections, however many of them. This makes `/foo///////////////////////////////bar/` equivalent to `/foo/bar/`.

This kind of flexibility is not welcome from a security perspective. I think that having to maintain our own regexp is a good tradeoff here.
