### ISSUE TITLE
Fix example typo for moderate sessions

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#20433]
## Applies To
Moderate sessions documentation:
[https://goteleport.com/docs/access-controls/guides/moderated-sessions/#example:~:text=filter%3A%20%27contains(user.spec.roles%2C%20%22auditor%22)%27](url)

## Details
We need to fix the example typo under the filter syntax. It currently looks like this: 
![Screenshot 2023-01-19 at 1 24 00 PM](https://user-images.githubusercontent.com/96448492/213540386-b926163e-383d-48c8-91ec-c582f9f91eec.png)
This should be correct to: 
`filter: 'contains(user.roles, "auditor")`
as this gives user permission issues when trying to configure. 
## Related Issues
New Issue, no other issue available.

**Comment by zmb3** [comment]
I'm not sure this is actually the issue. It's come up before: https://github.com/gravitational/teleport/issues/15898

**Comment by zmb3** [comment]
Yeah, #18402 added support for both `user.spec.roles` and `user.roles`.
