### ISSUE TITLE
Request to Rename Apt Repo Origin Name

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#20435]
What would you like Teleport to do?
Rename the repo origin name to something related to Teleport. 

What problem does this solve?
"ubuntu focal" is not descriptive of Teleport 
#apt-cache policy
Package files:
https://apt.releases.teleport.dev/ubuntu focal/stable/v10 amd64 Packages
release o=ubuntu focal,a=focal,n=focal,l=ubuntu focal,c=stable/v10,b=amd64
origin apt.releases.teleport.dev

A more descriptive and unchanging repo origin name will facilitate automation upgrades. 
e.g. 
Have unattended-upgrades configurations. 

If a workaround exists, please include it.
N/A

**Comment by zmb3** [comment]
No plans to do this any time soon. Renaming things like this comes with a lot of risk and little benefit.

**Comment by wjordan** [comment]
Workaround: configure [`unattended-upgrades`](https://github.com/mvo5/unattended-upgrades) with the more descriptive `site=apt.releases.teleport.dev` within an `Unattended-Upgrade::Origins-Pattern` apt configuration list:

```
# /etc/apt/apt.conf.d/52unattended-upgrades-local
Unattended-Upgrade::Origins-Pattern {
  "site=apt.releases.teleport.dev"
}
```

This allows packages from the teleport apt repository to be included in unattended upgrades:
```
$ unattended-upgrade -d --dry-run
Allowed origins are: o=Ubuntu,a=bionic, [...], site=apt.releases.teleport.dev
[...]
Checking: teleport ([<Origin component:'stable/v12' archive:'bionic' origin:'ubuntu bionic' label:'ubuntu bionic' site:'apt.releases.teleport.dev' isTrusted:True>])
[...]
pkgs that look like they should be upgraded: teleport
[...]
```
