### ISSUE TITLE
The latest version of the docs should say "latest"

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2044]
## Context

We do not always release a new version of the docs. This way if the latest teleport release is 2.6 but the latest docs say 2.5 people start looking for "docs v2.6".

## Solution

To avoid confusion, the latest version of Teleport in the docs should be called "current", but the same deployment/directory structure should be in place, so when the new version comes out the "old current" becomes accessible by it's own number.

I.e.

* `/teleport/docs/` -> "latest"
* `/teleport/docs/ver/2.4/` -> 2.4

... and so on

**Comment by benarent** [comment]
While looking for another issue, related to version numbers of Docs. I found this issue. I'm going to close it, and make a new issue related to how we can optimise version numbers in product documentation.  https://github.com/gravitational/teleport/pull/3262
