### ISSUE TITLE
Use cases for Upload/Download 

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#2046]
@alex-kovoy I'm going to put the use cases in designs for the Upload/Download project here so we can reference it and I can update if there are additional designs needed. The numbers in the use case below will correspond to the numbers in the images I've included. Please let me know if you have any questions/comments/etc. 

####  Update
- All dialogs that are used to initiate the process of upload/download will need to start in the bottom left corner near the upload/download button. Once the upload/download process begins successfully the transfer dialog will be place in the top right corner to allow the user to continue using the console while the transfer is in progress. 
- Cancel/Close (not X, actual buttons) should be `#B0BEC5` 
- Disable buttons should be: Border: `#324148`, Text: `#566D77`
- Active Buttons and Green Color: `#28FE14`

### Download File Standard Use Case
1. User opens a teleport console session 
2. Use clicks the download button on the bottom right of the console
3. A dialog is displayed asking the user for the full path of the file they wish to download
4. The user enters the full path in the dialog, the download button then become active
5. The user clicks download, once the download begins the download dialog will disappear as the browser's native download process will now take over. 

### Download File Exceptions
5a. The user clicks download but the path is incorrect
6. An error message will appear below the field and the path will also be highlighted in red. The download button will now be disabled until another path is entered 

### DOWNLOAD USE CASE IMAGES (refers to numbers above) 
![teleport - download hover](https://user-images.githubusercontent.com/407237/42177293-0de41b0e-7de1-11e8-9937-45c546f9a265.png)
![teleport - download steps](https://user-images.githubusercontent.com/407237/42177430-9415846a-7de1-11e8-80d4-71ce6af9d304.png)

Please note that all three dialogs will not be displayed at once, this is just an illustration to make the use case easier to understand. 

### Upload File Standard Use Case
1. User opens a teleport console session
2. User clicks on the upload button (hover state displayed) 
3. Upload file dialog is displayed (by default the home directory path is populated) 
4. User enters the file path they desire (if it's not the home directory) 
5. User Selects files
6. Upload process is then initiated
7. Upon the first sign of success the Dialog is updated to only display the paths of the files being uploaded and the status
8. When the upload is complete the cancel button now become a "close" button
9. User clicks close or 'x' and the dialog is closed 

#### 7a. Upon first file transfer an error occurs (ex permission denied, no path exist) 
1. Error message is displayed immediately, user still has the option of editing the path and files
2. User enters a new path and clicks retry
3. Error message is removed and upload process is initiated again

#### 8a. Error during the middle of a file transfer
1. Error message is displayed
2. Cancel button becomes a close button (since the operation is now canceled) 

### UPLOAD USE CASE IMAGES (refer to numbers above)  
![teleport - upload hover](https://user-images.githubusercontent.com/407237/42177280-030e98a8-7de1-11e8-93e8-0be6a0c5d4e2.png)
![teleport - upload hover](https://user-images.githubusercontent.com/407237/42177002-cab07860-7ddf-11e8-8b87-11f447f70d10.png)
![teleport - upload file selector](https://user-images.githubusercontent.com/407237/42177062-21aa592e-7de0-11e8-9cd5-30c33cb59bf2.png)
![teleport - upload in progress](https://user-images.githubusercontent.com/407237/42177108-5699c886-7de0-11e8-9cec-261dc447361d.png)

**Comment by kontsevoy** [comment]
## Update

@alexwolfe we need the updated screenshots based on the _current_ (tabless) design.

**Comment by alexwolfe** [comment]
@alex-kovoy @kontsevoy I've updated the use cases and images for the upload/download functionality in Teleport. Please take a look and let me know if you have any questions/comments. Thanks.
