### ISSUE TITLE
Open ID connect support

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#20515]
It will be nice to have open ID connect for Teleport

**Comment by zmb3** [comment]
Teleport supports OIDD identity providers today. Can you be more specific as to what you're looking for?

**Comment by nivasomu** [comment]
Sorry, @zmb3 this is meant to be Teleport as an OIDC provider not integrating with OIDC.

**Comment by pschisa** [comment]
Duplicate of https://github.com/gravitational/teleport/issues/18043
