### ISSUE TITLE
Terraform Provider Binaries for ARM64

### ISSUE THREAD

**Issue by alloveras** [gravitational/teleport#20539]
**What would you like Teleport to do?**
Teleport is currently publishing binary releases of the Teleport `provider` for Terraform to https://terraform.releases.teleport.dev. 

However, it seems like the binaries are only published for a handful of target platforms which do not seem to include the ARM64 architecture.

```
$ curl -sSL -I "https://terraform.releases.teleport.dev/registry/gravitational/teleport/10.3.2/download/darwin/amd64"
HTTP/2 200

$ curl -sSL -I "https://terraform.releases.teleport.dev/registry/gravitational/teleport/10.3.2/download/linux/amd64"
HTTP/2 200

$ curl -sSL -I "https://terraform.releases.teleport.dev/registry/gravitational/teleport/10.3.2/download/darwin/arm64"
HTTP/2 404

curl -sSL -I "https://terraform.releases.teleport.dev/registry/gravitational/teleport/10.3.2/download/linux/arm64"
HTTP/2 404
```

We would like to request that Teleport starts publishing pre-built binaries for its Terraform provider for the ARM64 CPU architecture for MacOS and, ideally, Linux as well.

**What problem does this solve?**
It's been a while since Apple took the decision to move away from Intel chipsets and started pushing for their own chips that are based on the ARM64 architecture (M1 and M2 chips). At this point, there are quite a lot of Apple M1 and M2 machines in circulation and, unfortunately, these machines struggle to use the Teleport provider for Terraform because their only option is to fallback to using the `darwin/amd64` binaries through [Apple's Rosetta](https://en.wikipedia.org/wiki/Rosetta_(software)).

Leaving aside the performance hit caused by the binary translation layer, we've seen that Terraform executions that use providers through Rosetta have an extremely high ratio of failure. From our experimentation, execution succeeds ~33% of the time, and the other ~66% of the time, we see crashes with very cryptic errors such as the one below:

```
│ Error: Unrecognized remote plugin message: 
│ 
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol.
│ 
```

The only workaround that we know so far is to re-try the failed operations until they work but that's not really a workaround.

**Comment by zmb3** [comment]
We'll be working on ARM builds soon. In the meantime, we're tracking this request over in the plugins repo: https://github.com/gravitational/teleport-plugins/issues/539
