### ISSUE TITLE
Okta SSO configuration has wrong values for URLs

### ISSUE THREAD

**Issue by camscale** [gravitational/teleport#20538]
## Applies To
https://goteleport.com/docs/access-controls/sso/okta/?scope=enterprise#configure-the-app

## Details
The "Single sign on URL" and "Audience URI" URLs have `/connectorName` on the end. If this is used, trying to log in with the connector/provider fails with the following error:

```
Original Error: *trace.AccessDeniedError received response with incorrect or missing attribute statements,
please check the identity provider configuration to make sure that mappings for claims/attribute statements
are set up correctly. &lt;See: https://goteleport.com/teleport/docs/enterprise/sso/ssh-sso/&gt;,
failed to retrieve SAML assertion info from response:
error validating response:
Unrecognized Destination value,
Expected: https://local.teleport:3080/v1/webapi/saml/acs,
Actual: https://local.teleport:3080/v1/webapi/saml/acs/okta-dev.
```

where my local proxy address is `local.teleport:3080` and the connector name I used is `okta-dev`.

Removing the `/okta-dev` from the end of the URLs (the connector name) makes login work.

The screenshot will also need to be updated, as it contains the connector name (truncated) in the URLs.

## Related Issues

https://github.com/gravitational/teleport/issues/15601 covers the refresh of SSO documentation, in which this might be addressed.

**Comment by zmb3** [comment]
Let's check with @xacrimon as I believe this was added for idp initiated login.

**Comment by xacrimon** [comment]
Yep, this is needed for IdP-initiated login. The bug is rather that it doesn't accept this *optional* parameter.

**Comment by zmb3** [comment]
I'm not sure I follow, @xacrimon. What exactly is the bug? Cam followed the docs and saw this error so the docs are either missing something or we're not handling something correctly in the code.

**Comment by xacrimon** [comment]
Hmm, at first I thought it was a code error that came about. But upon further inspection, does the URL configured in the Okta IdP match the ACS URL in the connector? I believe this can happen since teleport fails to validate the issuer URL. Now, we do have a special error message about this that triggers if you only change the local connector resource and not the IdP configuration, but this isn't shown if you change the IdP without changing the remote. Could this be the cause? @camscale

**Comment by camscale** [comment]
> Cam followed the docs and saw this error so the docs are either missing something or we're not handling something correctly in the code.

@xacrimon was correct - I did not have the full URL in the connector config for the `acs` field - putting the connector name on the end of the URL makes it work.

Not a bug or a documentation error, just user error.

Sorry for the noise. Closing this now.

**Comment by zmb3** [comment]
Awesome, thanks for clarifying!
