### ISSUE TITLE
Support Per-session MFA using OTP in the web UI

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#20540]
What would you like Teleport to do?

Support Per-session MFA using OTP in the web UI

What problem does this solve?

Currently in v11.2.2, for SSH, the `tsh client` must be used for per-session MFA. This is stated in the [list of limitations](https://goteleport.com/docs/access-controls/guides/per-session-mfa/#limitations) for Per-session MFA.

![Screenshot 2023-01-23 at 09 36 10](https://user-images.githubusercontent.com/95687564/214007437-3bb04f28-24e5-4c9a-b2ab-4dde2488ac6a.png)

If a workaround exists, please include it.

N/A

**Comment by philip-teleport** [comment]
Related to #18739

**Comment by zmb3** [comment]
Tagged with `needs-product-decision` as this would be a fair amount of UI work to enable support for _weaker_ MFA. I'm not sure it's worth the investment. What do you think @klizhentas?

**Comment by klizhentas** [comment]
I think we should gradually deprecate TOTP from the product, as Webauthn has gained wide adoption.

**Comment by zmb3** [comment]
Closing this as "won't fix" then. Opened #20725 to track the deprecation of TOTP.
