### ISSUE TITLE
Dynamic labels empty

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2056]
`CheckAccessToServer` in `lib/services/role.go`  calls `GetAllLabels() on `services.Server` to fetch static and dynamic labels. Static labels are returned by dynamic labels are always empty. Due to this, RBAC checks on dynamic labels always fail.

Dynamic labels show up the UI.

**Comment by aberoham** [comment]
FYI this happened to be encountered by two separate customers this week
