### ISSUE TITLE
Massive degradation of performance in scp performance in Teleport 11 vs Teleport 10.

### ISSUE THREAD

**Issue by slavitch** [gravitational/teleport#20579]
Observed Behavior:

I'm seeing a massive degradation in sftp performance with Teleport 11 vs what was seen with scp in prior releases.

For one session 'tsh scp' gets 220kbs transfer rates

If I use the local ssh connection (via -Llocalhost:2022:localhost:22 I get 100mbps transfer rates, multiple orders of magnitude different.

This is a massive performance degradation over what was seen before with SCP.

CPU and IO are not bound on the teleport server so I do not understand this degradation without it being a bug.

This test was repeated with same results with sender, receiver, and teleport server all running 11.2.2 

Traffic is normal.  I have 5GBPS ingres/egres through AWS.   Target sites have varying infrastructure but I could and did easily saturate an edge DSL link using sftp on Teleport 10.

Pushing (large)  artifacts (no, we cannot pull)  used to take seconds and now ETA is in hours (!!).

tsh scp TO the teleport server is fast, 20MB a second  within AWS, rate limit is write to disk.
tsh scp THROUGH the teleport server to another device in AWS falls to 5-10mb/s.

tcsh scp outside of AWS falls to kbps range no matter the target.  Prior performance for nodes on well-connected networks was write to disk speeds, up to 100mBps (800mbps).  I used to be able to saturate AWS egres with teleport. 

In all cases performance is much worse than it was with old obsolete SCP.

In all cases performance is almost two orders of magnitude slower than using scp with the edge device sshd via port redirection.

It seems that sftp performance is dependent on available CPU on the RECIPIENT node.

Expected behavior:

tsh scp (really tftp) should be as fast as running scp through a teleport connection using ssh tunneling.

How to test:

Send large files greater than 1GB in size to a client on another network over multiple network hops via 'tsh scp'.
Compare to sending that same vile using 'tsh ssh -Llocalhost:2222:localhost:22'

The transfer rates should be the same.

**Comment by srelf-eschercloud** [comment]
Seeing the same issue, please let me know if there is any debug you need

**Comment by aorsaria** [comment]
Seeing the same. I believe Teleport 11 switched to the `sftp` Go package for file transfers, so perhaps that caused a performance regression?

The throughput that I see is compatible with a fixed buffer size of 32KB. For instance, between two hosts with 0.09s RTT a `tsh scp` transfer gets ~350 KB/s, while the bandwidth-delay product (BDP) rule would predict ~355 KB/s with a 32 KB buffer size. Similarly, between two hosts with 0.02 RTT I get ~1.5 MB/s, while BDP would predict 1.6 MB/s.

**Comment by slavitch** [comment]
> bandwidth-delay product (BDP) rule

Yeah this is it. The throughput is worse with higher latency.

**Comment by slavitch** [comment]
Ah, found the code bug.   Should use ReadFrom not Write!

func (*File) [ReadFrom](https://github.com/pkg/sftp/blob/v1.13.5/client.go#L1761) [¶](https://pkg.go.dev/github.com/pkg/sftp#File.ReadFrom)
func (f *[File](https://pkg.go.dev/github.com/pkg/sftp#File)) ReadFrom(r [io](https://pkg.go.dev/io).[Reader](https://pkg.go.dev/io#Reader)) ([int64](https://pkg.go.dev/builtin#int64), [error](https://pkg.go.dev/builtin#error))
ReadFrom reads data from r until EOF and writes it to the file. The return value is the number of bytes read. Any error except io.EOF encountered during the read is also returned.

This method is preferred over calling Write multiple times to maximise throughput for transferring the entire file, especially over high-latency links.

**Comment by slavitch** [comment]
Reading the source code....   teleport calls write multiple times.

It needs to be replaced with a single ReadFrom:

That does break the pretty graphics showing progress however.

**Comment by mv-si** [comment]
This still affects me. 
Trying to scp a disk image to a distant node, I get 3MB/s using tsh scp
~30MB/s using regular scp. 
Teleport 15.4.0
