### ISSUE TITLE
ability to change logo displayed by teleport-proxy web interface

### ISSUE THREAD

**Issue by aberoham** [gravitational/teleport#2058]
**What happened**

Teleport logo and login page content is hard-coded within teleport-proxy. 

**What you expected to happen**

Customer requests ability to replace Teleport logo and possibly other key identifiers within teleport-proxy with own branding.

Changes would include:

* Logo changes in Login Page and Web UI
* Background theme update - Primary and secondary colour changes
* Please add copyrights to Teleport or Gravitational Inc at the bottom of the Web UI

**How to reproduce it (as minimally and precisely as possible)**: n/a

**Environment**:
- Teleport version (use `teleport version`): Teleport-2.6 Enterprise
- Tsh version (use `tsh version`): n/a
- OS (e.g. from /etc/os-release): n/a

**Comment by Valien** [comment]
As an example of this, look at AWX (Ansible Tower OSS project) or Ansible Tower enterprise. They allow users to upload a custom logo.

**Comment by RoseSecurity** [comment]
@russjones Has there been any update on an upcoming release with this feature?

**Comment by zmb3** [comment]
There are no plans to support this in the Community Edition. For commercial enquiries, please contact sales at goteleport dot com.
