### ISSUE TITLE
Design for Teleport Connect enhanced search

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#20615]
Design for Teleport Connect search that combines commands and connections in its suggestions.

Currently: search suggests commands only:

![Image](https://user-images.githubusercontent.com/1095531/214369976-d9d32ba2-b15d-450b-a701-165425aaa1a6.png)

Process for constructing a command is a bit confusing for newbies—there's a bit of lag in the help text showing up for each step of constructing a command and there's no loading state, so it isn't immediately clear that more help is coming. New design should plan for loading states and guidance throughout any multi-step processes.

Desired:
* Commands (with loading states to help you build out a command)
  * Preference for recent commands?
* Connections
  * Preference for recent? Preference above recent for still-open commands?
* More details to come...

**Comment by zmb3** [comment]
This shipped in Teleport 13
