### ISSUE TITLE
Simplify upgrades

### ISSUE THREAD

**Issue by madsonic** [gravitational/teleport#2064]
Problem: as a maintainer of multiple teleport clusters, upgrading teleport is a manual and painful process largely due to incremental update requirements and specific upgrade sequence. Also the available versions have to be check manually from teleport page

Something like `teleport update <version>` is highly desirable.

In order to do that a list of versions that can be fetched is required, then it is as simple as iteratively updating teleport using this list until the desired version (which is done by hand currently)

Let me know if this makes sense

**Comment by klizhentas** [comment]
@madsonic this is something we usually solve by using ansible or similar, do you use any deployment automation? Here are some examples you can find useful:

https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/ansible/upgrade.yaml

You can use ansible through teleport as well, so in a sense teleport can upgrade itself using ansible :D
