### ISSUE TITLE
Align AWS assume-role request duration with cert expiration

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#20724]
What would you like Teleport to do?
* Intercept AWS sts assume-role API calls and modify the requested credentials duration to be `min(request_duration, teleport_identity_ttl)`. We do this for aws console via web ui access, and we should do the same via cli/sdk app access.
* Update https://goteleport.com/docs/application-access/guides/aws-console/ to include a warning against cyclic role-chaining in AWS (as we discussed problems with that in slack). Our current guide is fine as-is and AWS (subtly) advises against this already, but let's mention in the guide so no one trips on this. Cyclic role-chaining would allow a user to "juggle" temporary role credentials indefinitely, even if they've been kicked out of the Teleport cluster at some point.

What problem does this solve?
* prevents user from fetching AWS credentials that outlive their Teleport login.

**Comment by greedy52** [comment]
Will update docs once doing the Athena and Timestream docs.
