### ISSUE TITLE
Migrate remaining tag build pipelines to GitHub Actions

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#20729]
- [x] build-linux-386-deb
- [x] build-linux-386-rpm
- [x] build-linux-386
- [x] build-linux-amd64-centos7-fips-rpm
- [x] build-linux-amd64-centos7-fips
- [x] build-linux-amd64-centos7-rpm
- [x] build-linux-amd64-centos7
- [x] build-linux-amd64-deb
- [x] build-linux-amd64-fips-deb
- [x] build-linux-amd64-fips
- [x] build-linux-amd64
- [x] build-linux-arm-deb
- [x] build-linux-arm-rpm
- [x] build-linux-arm
- [x] build-linux-arm64
- [x] build-linux-arm64-deb
- [x] build-linux-arm64-rpm
- [x] build-native-windows-amd64
- [x] build-windows-amd64
- [x] build-darwin-amd64
- [x] build-oss-amis
- [x] build-ent-amis
- [x] teleport-container-images-branch-tag
- [x] build-teleport-oci-distroless-images
- [x] build-teleport-hardened-amis
- [x] build-teleport-kube-agent-updater-oci-images

**Comment by camscale** [comment]
The tag build pipelines we have duplicate the logic for uploading to the staging S3 bucket as well as releasing to the release server. I experimented with trying to remove this duplication via a reusable workflow as per https://docs.github.com/en/actions/using-workflows/reusing-workflows (a callable workflow), however it does not seem possible to use a callable workflow and a deployment environment at the same time. The latter is needed to access the secrets from the environment, the former to reduce duplication of "code". I will see if there are other ways to remove the duplication that will work for us.

**Comment by camscale** [comment]
All workflows for the tag build on master and branches v12, v13 and v14 run on GitHub Actions now. The top-level is still orchestrated by drone, but the only work drone does is to call GHA workflows, wait for them and send errors to slack.

The next steps are to create a github action to send error notifications to slack, write a top-level tag build workflow and trigger that workflow from tags pushed to teleport.e. That won't be done or deployed until the promotion pipelines are moved to GHA in such a way that it can be triggered manually. Currently promotion is still triggered through drone so we still need drone doing something so we can hit the promote button. An intermediate step could be to get the errors on slack and the top-level workflow running and have drone just trigger that single workflow for a build until we figure out the security details around the OSS repo safely using creds to run workflows on teleport.e.

**Comment by camscale** [comment]
The tag builds and the entire process have been migrated successfully to GitHub Actions, with two releases made successfully without drone:

* v13: https://github.com/gravitational/teleport.e/actions/runs/8099530127
* v15: https://github.com/gravitational/teleport.e/actions/runs/8105035695
