### ISSUE TITLE
Disable cluster relationship from the main side.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2075]
For these examples I'll assume that we the following trusted cluster relationship: `main.example.com<-remote.example.com`.

### Remove Trusted Cluster relationship from both sides

Once established, to fully remove a trust relationship between two clusters, do the following:

1. Remove the relationship from the remote side: `tctl rm tc/main.example.com`.
1. Remove the relationship from the main side: `tctl rm rc/remote.example.com`.

### Remove Trusted Cluster relationship from the main side

1. Remove the relationship from the main side: `tctl rm rc/remote.example.com`.

Note: The `remote.example.com` cluster will continue to try and ping the main cluster, but will not be able to connect. To re-establish the trusted cluster relationship, the trusted cluster has to be create again from the remote side.

### Remote Trusted Cluster relationship from the remote side

1. Remove the relationship from the remote side: `tctl rm tc/main.example.com`.

**Comment by fatagnus** [comment]
Hi @kontsevoy, 
I'am also trying to disable trusted clusters completely, I think there is something missing in your fix. Could you check it? You added like;
`
# execute on "main":
$ tctl rm tc/east
# execute on "east":
$ tctl rm tc/main
`
I think it should be like;
`
# execute on "main":
$ tctl rm rc/east
# execute on "east":
$ tctl rm tc/main
`

@russjones , I applied it like that, but in "main" cluster, I get this warning in proxy log.
`
WARN             cluster "east" is not found web/apiserver.go:1877
`
I checked that the clusters are seperated (tsh clusters). But "main" proxy is still tring to reach "east".

**Comment by fatagnus** [comment]
update:
@russjones please ignore that, I forgot to refresh my browser :)
