### ISSUE TITLE
Namespace/resources RBAC access control

### ISSUE THREAD

**Issue by than-pet** [gravitational/teleport#20811]
What would you like Teleport to do?

A similar feature like this https://github.com/gravitational/teleport/issues/19573, but in a namespace level or even deployments/statefulsets/etc of a namespace.

Allow users of Teleport UI to search for available resources on a specific k8s cluster and ask for access.

What problem does this solve?

This will allow a user to access the specified resources and not just pods that they might get rescheduled and revoke access unintentional.

If a workaround exists, please include it.

**Comment by pnrao1983** [comment]
I would also like to add below interest from one of the customer:
Plans to add additional kubernetes_resources.kind values (right now it is just pod)? Giving a user access to every single resource (e.g. stateful set, svc, deployment, secrets, etc...) in a single K8s namespace would be ideal for Customers. We have a workaround for this, but being able to control everything from kubernetes_resources would simplify a whole lot.

**Comment by jpenagg** [comment]
We are also in need of a broader scope of k8s access that is not just limited to pods.

**Comment by adrianmoisey** [comment]
> We have a workaround for this, but being able to control everything from kubernetes_resources would simplify a whole lot.

What is the workaround?
We're looking at Teleport, and only supporting Pod is quite a limitation for us.

**Comment by BennettKnapek** [comment]
> > We have a workaround for this, but being able to control everything from kubernetes_resources would simplify a whole lot.
> 
> What is the workaround? We're looking at Teleport, and only supporting Pod is quite a limitation for us.

We create k8s ClusterRoles with the desired permissions, map those ClusterRoles into k8s Groups, and then reference those groups in the `kubernetes_groups` value. 

It is quite a lot of maintenance so this feature is still extremely desired.

**Comment by tigrato** [comment]
I started working on this feature and I plan to:
*  Allow wildcard `*` selector for `kubernetes_resources[:].kind` 
* Extending the supported resources to:
  * Deployments
  * Statefulset
  * Secrets
  * Configmap
  * DaemonSet
  * Job
  * CronJob
  * Namespace
  * Services
  * Nodes
  * ReplicaSets
  * Roles
  * RoleBindings
  * ClusterRoles 
  * ClusterRoleBindings
  * PersistentVolumes 
  * PersistentVolumeClaims
  * Ingress
  * Certificates
  * ServiceAccounts

Does anybody want to have support for other resource types?

**Comment by tigrato** [comment]
#26244 implements this feature
