### ISSUE TITLE
(web) A terminal session becomes unresponsive due to unknown reasons

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#2081]
A session can become unresponsive due to unknown reasons. When it happens, websocket continues to send audit events but with no terminal output data. Here is how I was able to reproduce it 
```
1. $ cd docker
2. make start
3. Open a web terminal and type "ls / -laR"
4. Try to refresh the browser while terminal is processing above command
```

**Comment by klizhentas** [comment]
@alex-kovoy what version is this?

**Comment by alex-kovoy** [comment]
this is master

**Comment by alex-kovoy** [comment]
still repros on current master 08902c5c2b238ea424e9333737a02834a54e7c6d

**Comment by alex-kovoy** [comment]
still repros on current master 4253b883391e0fd4f485698894822c4a47f610a6

**Comment by russjones** [comment]
@alex-kovoy Is this still a issue on the new UI? If not, we can close this issue.

**Comment by alex-kovoy** [comment]
Need to double check but 6m ago it still was

**Comment by stevenGravy** [comment]
Tried, not failing
