### ISSUE TITLE
Playback error should be displayed better

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2088]
## Description

If a recorded session is lost (i.e. teleport logged an ERROR trying to submit it) but a user requests a replay, the current behavior is to show this error message in the web UI:

0 not found.

Instead of "0" we should probably show the URI Teleport was trying to use?
Would that be kosher from a security perspective?
Because if we don't - that's an immediate support call/ticket instead of fixing it DIY style.

**Comment by kontsevoy** [comment]
merged with #2125
