### ISSUE TITLE
Audit log vertical alignment is slightly off

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#20884]
The vertical alignment for the text in the event type is 1-2 pixels off from the text for the description.

<img width="342" alt="Screenshot 2023-01-28 at 10 13 32 AM" src="https://user-images.githubusercontent.com/7527103/215279847-d3c482b0-b783-4db5-bf2e-3211149d2ff0.png">

It's easier to spot when one of the rows overflows and the row height changes:

![IMG_0014](https://user-images.githubusercontent.com/7527103/215279939-a347eff8-a8b8-461b-94f9-fb7f79bc7cb5.PNG)

**Comment by zmb3** [comment]
This is already covered via the first task in #17795

**Comment by hatched** [comment]
The issue in #17795 has been resolved, this one is similar but different.

**Comment by hatched** [comment]
However this one is also resolved.

<img width="626" alt="Screenshot 2023-02-08 at 3 05 03 PM" src="https://user-images.githubusercontent.com/532033/217650733-548b5a35-7643-4c4b-b32e-339e5ff8e371.png">
