### ISSUE TITLE
When kubernetes Day-1 command expires, clicking regenerate command does not clear the error state

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#20898]
Steps to reproduce:

* Go do "Add Kubernetes cluster"
* Wait until the command times out
* Click regnerate

Expected the error state to clear and the timer to go back to normal. 
The command regenerates, but still shows the error state.

**Comment by ryanclark** [comment]
We're removing the timeouts from the commands in #20829, so this incorrect state won't be an issue once that lands
