### ISSUE TITLE
`TestALPNSNIProxyDatabaseAccess/teleterm_gateways_cert_renewal` flakiness

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#20906]
This concerns both tests:

* `TestALPNSNIProxyDatabaseAccess/teleterm_gateways_cert_renewal/root_cluster`
* `TestALPNSNIProxyDatabaseAccess/teleterm_gateways_cert_renewal/leaf_cluster`

#### Link(s) to logs

We need more runs to establish what's failing exactly!

- [connection error](https://console.cloud.google.com/cloud-build/builds/19a8aa7f-921b-4037-8cb3-3a01210b3549?project=ci-account)
- [data race](https://github.com/gravitational/teleport/actions/runs/4145936053/jobs/7170963708) `mysql.(*OptionFile).Upsert()`
   - #21712 
   - https://github.com/gravitational/teleport/blob/5c752c4df8987c16afa4c4c1ef6a00d2d21b73c6/lib/client/db/mysql/optionfile.go#L103
   - https://github.com/go-ini/ini/blob/v1.67.0/file.go#L457-L460
- [data race](https://github.com/gravitational/teleport/actions/runs/4147464214/jobs/7174375679) `mysql.(*OptionFile).Upsert()`
- [data race](https://github.com/gravitational/teleport/actions/runs/4136229576/jobs/7149792627) `server.(*Conn).writeOK()`
   - https://github.com/gravitational/teleport/blob/42342c7a7066ac0483c9291b098e29b8493043cd/integration/proxy/teleterm_test.go#L133

#### Relevant snippet

```
    teleterm_test.go:122: 
        	Error Trace:	/workspace/integration/proxy/teleterm_test.go:122
        	            				/workspace/integration/proxy/teleterm_test.go:68
        	Error:      	Received unexpected error:
        	            	connection error: desc = "transport: authentication handshake failed: EOF"
        	Test:       	TestALPNSNIProxyDatabaseAccess/teleterm_gateways_cert_renewal/leaf_cluster
```

**Comment by zmb3** [comment]
@ravicious are we good to close this one now?

**Comment by ravicious** [comment]
I wanted to wait for Russell's update email (well, the next one after the one that's going to be sent today) to verify that #21710 indeed fixed the problem.

**Comment by ravicious** [comment]
Two weeks in a row where those tests are not mentioned in the weekly email, I consider this issue to be fixed.

**Comment by zmb3** [comment]
v15 hit here: https://github.com/gravitational/teleport/actions/runs/8284085913/job/22668830846

**Comment by ravicious** [comment]
It looks like it stopped being an issue after we disabled the client cache in tests.
