### ISSUE TITLE
Azure AD SSO setup screenshots out of date

### ISSUE THREAD

**Issue by camscale** [gravitational/teleport#20905]
## Applies To
https://goteleport.com/docs/access-controls/sso/azuread/

## Details
The screenshots for setting up a non-gallery application do not match what I see in the Azure AD portal.

Step 2 Select New Application is correct.

For Step 3, Select a Non-gallery application, the screen has changed. It should now be:

3. Select "Create your own application"

![image](https://user-images.githubusercontent.com/35285934/215398032-d5f8302b-8373-4a64-8fc9-d6a200369da3.png)

4. Enter the application name (e.g. Teleport) and select "Integrate any other application you don't find in the gallery (Non-gallery)

![image](https://user-images.githubusercontent.com/35285934/215398577-5cfa0c02-9683-4fc4-a284-d31d8082e411.png)

## Related Issues

Teleport 12 test plan: #20132

**Comment by gabrielcorado** [comment]
Yes, it was fixed.
