### ISSUE TITLE
[v.11.x] /docs/pages/try-out-teleport/introduction.mdx

### ISSUE THREAD

**Issue by matthewhelmke** [gravitational/teleport#20912]
## Applies To

https://goteleport.com/docs/try-out-teleport/introduction/

## Details

I found a simple typo. Under Local Deployments, the final clause of the introductory sentence says, "...check out or local deployment labs:". The "or" should be "our".

I'm happy to contribute a patch, but it's probably a lot faster for anyone with repo access to create a quick PR.

**Comment by stevenGravy** [comment]
thanks @matthewhelmke !  pr submitted.
