### ISSUE TITLE
tsh scp does not work correctly during multiple file uploads

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#2094]
During multiple file uploads as shown below, all files will be overriding each other if remote location is not a directory but a file.

```
./tsh scp file1 file2  file3 file4 root@one:newfile
```
Actual:
only 1 file is created in the home directory which is `newfile` with a content of `file4`

Expected behavior:
scp should show an error saying that given remote location is not a directory.

This happens on the current master.

**Comment by russjones** [comment]
I was able to reproduce this. Also, OpenSSH `scp` does not suffer from this:

```
$ scp -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p" foo bar baz node.example.com:/tmp/123/foo
scp: /tmp/123/foo: No such file or directory
```
