### ISSUE TITLE
Expiryless tokens for Delegated Joining

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#20977]
## What's wrong?

At the moment, all ProvisionTokens require an expiry. This makes perfect sense for string join tokens, however, I fail to see any real security benefits of this expiry for ProvisionTokens that use the new delegated joining types (e.g GitHub, CircleCI, Kubernetes, AWS).

This is problematic for a few reasons:

- This has led to us suggesting values like the [year 3000](https://www.youtube.com/watch?v=Tu7HoGZaspo) which breaks etcd as seen in https://github.com/gravitational/teleport/issues/20962.
- It's confusing. When users discover this is a required field, they feel like they might be misunderstanding how delegated joining works if it needs to expire.
- There's no real sane value we can suggest here, because expiry doesn't make sense.

### Current implementation

Tokens without an expiry automatically have a thirty minute expiry applied:

```go
func (s *ProvisioningService) tokenToItem(p types.ProvisionToken) (*backend.Item, error) {
	if err := p.CheckAndSetDefaults(); err != nil {
		return nil, trace.Wrap(err)
	}
	if p.Expiry().IsZero() || p.Expiry().Sub(s.Clock().Now().UTC()) < time.Second {
		p.SetExpiry(s.Clock().Now().UTC().Add(defaults.ProvisioningTokenTTL))
	}
```

Zeroed expiry would currently be treated as "expired":

```go
// checkTokenTTL checks if the token is still valid. If it is not, the token
// is removed from the backend and returns false. Otherwise returns true.
func (a *Server) checkTokenTTL(tok types.ProvisionToken) bool {
	ctx := context.TODO()
	now := a.clock.Now().UTC()
	if tok.Expiry().Before(now) {
		err := a.DeleteToken(ctx, tok.GetName())
		if err != nil {
			if !trace.IsNotFound(err) {
				log.Warnf("Unable to delete token from backend: %v.", err)
			}
		}
		return false
	}
	return true
}
```

## How can we fix this ?

For all token types that are considered "Delegated Joining" we should make the expiry field of the ProvisionToken resource optional.

We should then include a condition in `checkTokenTTL` that accepts tokens where the time.Time `IsZero`

### Backwards compatibility

Currently, an expiryless token  would be treated as expired and deleted by `checkTokenTTL` if they downgraded their Auth server.

Options:
- A: Accept this behaviour.
- B: Create a two stage release, where in version X, we change the logic to support joining with a token without expiry, and in version X+1, we allow the creation of tokens without expiry. This allows downgrading by one version without the tokens being removed. 

I personally prefer option A, whilst option B seems like a better user experience, it means spreading this change across two whole Teleport versions, which is a relatively protracted process and ought to be saved for situations where the alternative is unworkable.

**Comment by nklaassen** [comment]
Agreed, this should have been done when ec2 joining was introduced, I just overlooked it. I'd go with option A of enabling it all at once. I'm just unsure of whether or not the change should be backported, it could reduce the chance of an issue on downgrade, but we'll want to make sure that docs for older versions still mention the necessary expiry field for people who are behind the latest minor/patch

**Comment by strideynet** [comment]
Backporting seems like a good idea here, I doubt this will make it into 12.0.0

**Comment by zmb3** [comment]
Related: #3327

**Comment by strideynet** [comment]
@zmb3 - I'm more than happy to extend the PR for this issue to be for all join token types, however, are we happy with that as a security posture and leaving it up to the user ?
