### ISSUE TITLE
YUM repository URL is out of date

### ISSUE THREAD

**Issue by larkly** [gravitational/teleport#20978]
## Applies To
https://goteleport.com/docs/management/admin/upgrading-the-teleport-binary/

## Details
I'm attempting to follow the documentation on adding the Teleport repos to a RHEL 8.7 system. The documentation refers to this snippet:
```
source /etc/os-release
sudo yum-config-manager --add-repo $(rpm --eval "https://yum.releases.teleport.dev/$ID/$VERSION_ID/Teleport/%{_arch}/stable/v11/teleport.repo")
sudo yum install teleport
```
The repo link resolves to `https://yum.releases.teleport.dev/rhel/8.7/Teleport/x86_64/stable/v11/teleport.repo` on my system, but this request fails with a 404 Not Found and Code: NoSuchKey. Browsing the webserver tree manually does not give any more insight.

Using yum-config-manager --add-repo https://rpm.releases.teleport.dev/teleport.repo directly as specified on https://rpm.releases.teleport.dev works fine. Documentation should be updated accordingly.

## Related Issues
#18099

**Comment by webvictim** [comment]
This is an issue with the way RHEL declares `VERSION_ID` in `/etc/os-release`.

Using a single digit version (i.e. https://yum.releases.teleport.dev/rhel/8/Teleport/x86_64/stable/v11/teleport.repo) will work. I'll see if we can get a note in the docs about RHEL, or find a more reliable way to extract the major version only.
