### ISSUE TITLE
Web UI scp errors

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2100]
## Teleport version:

```
$ teleport version
Teleport v2.7.0-rc.1 git:v2.7.0-rc.1-0-g23a71f2b
```

## Browsers

Happens on both:
* Chrome Version 67.0.3396.99 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
* Firefox 61.0.1 (64-bit) Ubuntu

## Simple download 

The screenshot should be self-explanatory but I'll list the sequence of steps:

- created `hi.txt` file
- clicked "download" button
- typed `hi.txt` and hit Enter
- got this error
- also notice that the name of the file I typed disappeared and got replaced with _invalid_ prompt

![scp-error](https://user-images.githubusercontent.com/461020/43030444-ff358b5c-8c44-11e8-8d05-e50bb8b5f9ba.png)

**Comment by alex-kovoy** [comment]
fixed with https://github.com/gravitational/teleport/commit/7553f1325693dc9655800d46678f9c774cd74e67
