### ISSUE TITLE
Bugs: web UI font rendering is off

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2101]
Something happened with the latest build. The web-based terminal is very hard to use because there is no spacing between lines:

## Before

![before](https://user-images.githubusercontent.com/461020/43030561-a58e5de8-8c46-11e8-9b97-665a28d89b4e.png)

## After

![after](https://user-images.githubusercontent.com/461020/43030562-a82418c2-8c46-11e8-8d4d-892bb6cda566.png)

## Browser

```
Chrome Version 67.0.3396.99 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
```

## Importance

We can punt on this if no solution is found by the end of July 26. 
In this case it needs to move to 2.7.1

**Comment by klizhentas** [comment]
This is ubuntu 18.04 problem, so removing it from 2.7.0
