### ISSUE TITLE
--insecure-no-tls CSRF token issue

### ISSUE THREAD

**Issue by celi28** [gravitational/teleport#2104]
**What happened**:
When launching teleport with ``--insecure-no-tls`` user can't log-in into the web interface. User go an "access denied" error. Based on the debug output, it seem related to a CSRF issue
**What you expected to happen**:
Sucessfull login.
**How to reproduce it (as minimally and precisely as possible)**:

- Launch teleport with teleport start ``--insecure-no-tls -d``
- Create user with ``tctl users add jhmartin root``
- Adjust url to HTTP and connect
- Set the password
- Attempt to log in. Note Access Denied response and above URL. 

**Environment**:
- Teleport version (use `teleport version`): ``Teleport v2.7.0-alpha.5 git:v2.7.0-alpha.5-64-g031168bb``
- Tsh version (use `tsh version`): ``Teleport v2.7.0-alpha.5 git:v2.7.0-alpha.5-64-g031168bb``
- OS (e.g. from /etc/os-release): ``Debian GNU/Linux 9 (stretch)``

**Browser environment**

- Browser Version (for UI-related issues): ``Firefox 61.0.1-1 x86_64 ArchLinux``

**Relevant Debug Logs If Applicable**

```
root@teleport:~# tctl users add cecile cecile,root
Signup token has been created and is valid for 1 hours. Share this URL with the user:
https://teleport:3080/web/newuser/cc5131ef150b3c7975c39b28aa258d5e

NOTE: Make sure teleport:3080 points at a Teleport proxy which users can access.


WARN             http: named cookie not present request:GET /web/login web/apiserver.go:1888
DEBU             [web] GET zip:/app/vendor.a61d92a44f57c4eb872e.js web/static.go:195
DEBU             [web] zip::Close(vendor.a61d92a44f57c4eb872e.js) web/static.go:188
DEBU             [web] GET zip:/app/styles.a61d92a44f57c4eb872e.js web/static.go:195
DEBU             [web] zip::Close(styles.a61d92a44f57c4eb872e.js) web/static.go:188
DEBU             [web] GET zip:/app/vendor.74f7a92a8aff0163c57f9be83b093efc.css web/static.go:195
DEBU             [web] GET zip:/app/app.a61d92a44f57c4eb872e.js web/static.go:195
DEBU             [web] zip::Close(app.a61d92a44f57c4eb872e.js) web/static.go:188
DEBU             [web] zip::Close(vendor.74f7a92a8aff0163c57f9be83b093efc.css) web/static.go:188
DEBU             [web] GET zip:/app/assets/img/img-54ca7c.png web/static.go:195
DEBU             [web] zip::Close(img-54ca7c.png) web/static.go:188
WARN             unable to validate CSRF token unable to extract CSRF token from cookie httplib/httplib.go:85
```

**Comments**
Looks related to https://github.com/gravitational/teleport/issues/1816

**Comment by kontsevoy** [comment]
@alex-kovoy can you please verifiy?

**Comment by russjones** [comment]
This is probably because `grv_csrf` is a secure cookie and won't be set on a HTTP connection.

@celi28 Do you have Teleport behind a LB and serving HTTPS on the LB or are you trying to connect directly to the HTTP endpoint?

**Comment by celi28** [comment]
The LB is serving HTTPS and take charge of SSL encapsulation.
Indeed, I was trying to connect to the HTTP endpoint.

**Comment by celi28** [comment]
@alex-kovoy Fixed or ?

**Comment by russjones** [comment]
@celi28 You can't connect directly to the HTTP endpoint. The `--insecure-no-tls` can be used to run Teleport behind a LB, but not to bypass it.

**Comment by alex-kovoy** [comment]
@celi28 you cannot use teleport web UI without secured connection (https)
