### ISSUE TITLE
Update SSH and Desktop Players to new design

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#21068]
The design team has created an updated design for the playback video player which allows for a more sensible single style between ssh session and desktop session playbacks.

Paused:
<img width="1052" alt="Screen Shot 2022-01-26 at 09 35 26" src="https://user-images.githubusercontent.com/13578537/151182674-16143280-7901-4296-93ae-79e61651083f.png">

On Mouse Move:
<img width="1052" alt="Screen Shot 2022-01-26 at 09 36 20" src="https://user-images.githubusercontent.com/13578537/151182842-69d4da61-8aea-4075-8c63-14093a8dae90.png">

See [Figma](https://www.figma.com/file/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?node-id=2390%3A14385)

**Comment by zmb3** [comment]
Closing as deprecated by time. The "new" designs are no longer new, and we have a new(er) design system now, so any updates to the player should be looked at under the latest design guidanc.e
