### ISSUE TITLE
Silent installation of teleport connect 

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#21090]
Teleport Connect software can be downloaded and installed by an end-user on their Mac or Windows machine using a user interface on their device. But for a few scenarios, it would be easy to install the software without UI interaction. 

This helps the organizations to install Teleport Connect software on every device by a script or by using software management platforms.

**Comment by ravicious** [comment]
The NSIS installer provided by electron-builder that we use seems to support this out of the box. You need to provide the `/S` flag when executing the installer.

```
"Teleport Connect Setup-12.0.1.exe" /S
```

We'll need to document that and make sure it doesn't break between electron-builder updates.

**Comment by ravicious** [comment]
#21975 adds the documentation for silent install.

**Comment by ravicious** [comment]
Should we add macOS and Linux documentation for this as well? On those OSes, folks should be able to silently install Connect using an approach that's common for the given system. The only outlier was Windows when it's not obvious whether the installer supports silent installation or not.
