### ISSUE TITLE
Configure who can get the upgrading notification banner 

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#21097]
Today when there is a new or a patch version of the teleport available the banner notification is displayed for every user. but the end users cannot do anything with upgrading the cluster. It's only useful for the administrator of the teleport cluster. 

<img width="758" alt="Screenshot 2023-02-02 at 12 40 55 AM" src="https://user-images.githubusercontent.com/13088331/216140989-ecb540b4-4631-4626-929e-b12a7bfde94a.png">

It would be nice to make it configurable who can get this banner? 
So, in this way, it allows only sending the notification/banner to the Administrator and not to the wide audience.

**Comment by webvictim** [comment]
There's also relevant discussion about alert-based RBAC in #17188

**Comment by twskipper** [comment]
@nivasomu  Here is my solution:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/14154850/218028493-b1ae537a-de38-4377-851a-683f55fc5d64.png">

Just rewrite the ip of api.github.com to your /etc/hosts
like
127.0.0.1 api.github.com

**Comment by twskipper** [comment]
teleport check release through github release api. 
<img width="1651" alt="image" src="https://user-images.githubusercontent.com/14154850/218028852-6650d3d5-db27-4a9e-b085-2c358a1ec1ed.png">

**Comment by twskipper** [comment]
https://github.com/gravitational/teleport/blob/48d91ab84dba0c0a2fc5fc541af5c9cf46755f71/lib/versioncontrol/github/github.go#L108

**Comment by webvictim** [comment]
Running `echo '127.0.0.1 api.github.com' | sudo tee -a /etc/hosts` on the Teleport auth server will also achieve the same result on Linux/Mac hosts.

You can clear all existing banners from a on-disk backend by running `echo "DELETE FROM kv WHERE key LIKE '/cluster-alerts/%';" | sudo sqlite3 /var/lib/teleport/backend/sqlite.db`

**Comment by dmsergeevN26** [comment]
The bigger issue that I see is why would a security critical piece of software talk to the public internet at all?

**Comment by zmb3** [comment]
This is addressed via `tctl alerts ack`
