### ISSUE TITLE
Notify end user to upgrade CLI binary  after cluster upgrade

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#21108]
If the cluster version and the CLI version are not equal teleport doesn't notify the end user to upgrade their binaries. 
It would be nice if we can notify the CLI user if the teleport cluster version and the CLI version are different and point them to docs to upgrade their binaries.

**Comment by swastik959** [comment]
hi I want to work on this issue can you please explain it to me

**Comment by webvictim** [comment]
While we're here why don't we just make `tsh` able to automatically use the right version for the cluster it's talking to, like a Python `venv`...?

**Comment by Jasstkn** [comment]
@webvictim that would be great. I think it's somehow can be connected with this existing feature as well https://goteleport.com/docs/reference/cli/#aliases.

**Comment by zmb3** [comment]
> If the cluster version and the CLI version are not equal teleport doesn't notify the end user to upgrade their binaries.

`tsh` does notify the user when attempting to log in to a cluster with an incompatible version: https://github.com/gravitational/teleport/blob/a3876ae7ab12d8cfe2d6d1f6d2743472a0420eb7/lib/client/api.go#L4323-L4349

As for automatic client upgrades, that's being tracked at #37872.
