### ISSUE TITLE
[Web] Resetting a local user's password does not unlock their account

### ISSUE THREAD

**Issue by rudream** [gravitational/teleport#21109]
### Expected behavior:

When a user's account is locked due to too many failed login attempts, an admin resetting their account should work to unlock it.

### Current behavior:

When a locked user's account is reset via a reset password link, they are still unable to log in. The only way to get their account unlocked from within the WebUI is to delete the account and recreate it.

### Recreation steps

1. Attempt to login to a user's account with an incorrect password many times until the account gets locked and even using the correct password doesn't work.
2. From an admin account, generate a reset link for that user.
3. Reset the user's account credentials using that reset link.
4. Observe that the user is still unable to log in.

#### Teleport version: `v11.0.0`, `v12.0.0`

**Comment by zmb3** [comment]
See also #11350

**Comment by zmb3** [comment]
This is by design right now.

**Comment by maxdwit** [comment]
@zmb3 by design. Interesting.
