### ISSUE TITLE
Backgrounded screen/tmux sessions closed when teleport restarts

### ISSUE THREAD

**Issue by aashley** [gravitational/teleport#2110]
**What happened**: screen/tmux placed into background with command running within it is terminated with teleport service is restarted.

Issue was identified while running configuration management tools in the background to upgrade from Teleport 2.4 cluster to 2.6 cluster. Attempting to do upgrades on old servers where the only remote connection is Teleport 2.4.

**What you expected to happen**: screen/tmux continues to run in the background while teleport restarts the same as if doing it via SSH

**How to reproduce it (as minimally and precisely as possible)**:
1. Connect to server via SSH.
2. Connect to server via Teleport.
3. On Teleport console start screen.
4. Within screen start top.
5. On SSH console check that screen is running.
6. On SSH console restart teleport service.
7. On SSH console observe that screen is no longer running.

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.6.7 git:v2.6.7-0-g280f0fe3 and Teleport v2.4.6 git:v2.4.6-0-g46e3079
- Tsh version (use `tsh version`): Teleport v2.6.7 git:v2.6.7-0-g280f0fe3 and Teleport v2.4.6 git:v2.4.6-0-g46e3079
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS

**Comment by webvictim** [comment]
Related to #4195 and #2355

**Comment by aashley** [comment]
Can confirm the fix from #4195 does resolve this issue. Deployed with Teleport 4.2 into our production environment.
