### ISSUE TITLE
teleport proxy does not respect TTL on DNS

### ISSUE THREAD

**Issue by elijahsgh** [gravitational/teleport#21151]
Expected behavior:
When resolution changes for DNS names teleport should resolve the host and use the updated IP.

Current behavior:
teleport seems to **only resolve host names once during proxy lifetime**. Proxies have to be restarted for infrastructure changes to take affect. Proxies have kept the wrong IP for upwards of 3 hours.

Bug details:
- Teleport version
9.x, 10.x
- Recreation steps
Add resource to teleport, access resource, change the IP in DNS, try to use the resource again
- Debug logs
None

**Comment by zmb3** [comment]
I think we need some more information on this one.

- What's the TTL on the DNS record before you changed it?
- Is it the node not respecting DNS (as the title implies) or the proxy dialing the wrong (outdated) IP?
- What specific actions are you taking that are not working the way you'd expect? What is the error you see?

**Comment by elijahsgh** [comment]
The DNS TTL was 5 minutes.
The proxy is dialing the old IP. The title implies that it is not respect **DNS TTL** - not "DNS". These are different topics. The time to live for a DNS record is what the title clearly states.
Attempting to connect to a resource fails.

**Comment by zmb3** [comment]
Ok, so it's the proxy that is seemingly not respecting the TTL on the DNS record, and _not_ the node.

**Comment by elijahsgh** [comment]
Changed node to proxy in title.

**Comment by zmb3** [comment]
Last we spoke you were going to try and reproduce this @elijahsgh - any updates?
