### ISSUE TITLE
Improve Error Message for User Host Creation 

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#21165]
What would you like Teleport to do?
Currently, failures in Host User Creation related to host groups creates the error message:
`User Message: error while creating groups`

Request is to improve this error message with further details around the exact command it ran including the group names

What problem does this solve?
Users hitting this error and unable to find the resolution swiftly.  A recent real world example, it took a while to isolate the root issue creating this error was a misconfiguration in the host_groups of a role:
~~~
host_groups:
  - "*"
~~~
Having this output by the error message would have made the problem immediately obvious to the end user to self solve.

Sample Logs
~~~
DEBU             "Error creating user xxxxx: error while creating groups\n\texit status 3" srv/sess.go:207
teleport[28462]: 2023-01-30T14:55:15Z ERRO             failure handling SSH "shell" request error:[
teleport[28462]: ERROR REPORT:
teleport[28462]: Original Error: trace.aggregate exit status 3
teleport[28462]: Stack Trace:
teleport[28462]: github.com/gravitational/teleport/lib/srv/usermgmt.go:211 github.com/gravitational/teleport/lib/srv.(*HostUserManagement).CreateUser
teleport[28462]: github.com/gravitational/teleport/lib/srv/sess.go:205 github.com/gravitational/teleport/lib/srv.(*SessionRegistry).TryCreateHostUser
teleport[28462]: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1603 github.com/gravitational/teleport/lib/srv/regular.(*Server).dispatch
teleport[28462]: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1487 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests
teleport[28462]: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1208 github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan.func1
teleport[28462]: runtime/asm_amd64.s:1594 runtime.goexit
teleport[28462]: User Message: error while creating groups
~~~

**Comment by swastik959** [comment]
@pschisa hi I am new to open source and want to work on this issue please guide me through it

**Comment by Jasstkn** [comment]
@pschisa hi. Is this something that you expect? I'm not sure if there is an easy way to test it out. But anyway let me know what do you think?

https://github.com/Jasstkn/teleport/commit/5f1f76a7f1103be6abd3b8ed24e6b0e6f625ea2a#diff-a35048985af8efdca6e8d32d3c08e6352c47be70c9605d7e702ccaead4c4d284R207
