### ISSUE TITLE
unable to join a kubernetes moderated session from a root cluster

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#21167]
### Expected behavior:

In a usecase where an MSP has customers with leaf clusters. A user on a root cluster would like to join a session as a moderator.

### Current behavior:

When the root cluster user attempts to join the session, they get a "session not found" error.

The leaf user launches the session:

```
$ kubectl -n other exec -it deploy/web -- bash --login
Teleport > Creating session with ID: d6835cb9-18c5-4cec-b52a-53335fa2e267...
Teleport > Controls
  - CTRL-C: Leave the session
  - t: Forcefully terminate the session (moderators only)
```

The root proxy user attempts to join:

```
$ tsh login --user mod --proxy root.example.com leaf.example.com
$ tsh kube ls
Kube Cluster Name Labels Selected
----------------- ------ --------
somekube
$ tsh kube login somekube
$ tsh kube sessions
ID                                   State                  Created              Hostname Address Login Reason
------------------------------------ ---------------------- -------------------- -------- ------- ----- ------
d6835cb9-18c5-4cec-b52a-53335fa2e267 SessionStatePending    2023-02-02T19:33:48Z                  root
$ tsh kube join d6835cb9-18c5-4cec-b52a-53335fa2e267
ERROR: session d6835cb9-18c5-4cec-b52a-53335fa2e267 not found
```

The corresponding error messages that print on the root cluster logs are attached as files. I have also attached the yaml for the roles, trusted cluster, and teleport users that were used to reproduce the behavior.

The root logs show the connections being made and a disconnect happening. The leaf logs show the user mapping happening, but don't have anything populated in kubernetes_groups or kubernetes_users. If a leaf user that has the `moderator` role attempts to join the session, it works correctly.

### Bug details:
- Teleport version 11.3.2 for the leaf, proxy, and tsh
- Recreation steps - deploy a root and a leaf cluster and install the corresponding yaml. attempt to start a `kubectl exec -it` when logged in to the leaf cluster. attempt to join that session when logged in as the mod user on the root cluster.
- Debug logs (see attached)
  * [rootlogs.txt](https://github.com/gravitational/teleport/files/10573226/rootlogs.txt)
  * [leaflogs.txt](https://github.com/gravitational/teleport/files/10573217/leaflogs.txt)
  * [rootobjects.yaml](https://github.com/gravitational/teleport/files/10573228/rootobjects.yaml.txt)
  * [leafobjects.yaml](https://github.com/gravitational/teleport/files/10573229/leafobjects.yaml.txt)

**Comment by russjones** [comment]
@programmerq We have a fix for this ready, we should be able to ship a fix within 2 weeks.
