### ISSUE TITLE
[v.11.x] /docs/pages/management/admin/upgrading-the-teleport-binary.mdx

### ISSUE THREAD

**Issue by kianamcdaniel** [gravitational/teleport#21173]
## Applies To
(https://goteleport.com/docs/management/admin/upgrading-the-teleport-binary/)

## Details
The 4 example commands (see red arrows in screenshot) for installing teleport enterprise (non-fedramp/fips) are missing `ent`

## Related Issues
<img width="870" alt="image (2)" src="https://user-images.githubusercontent.com/40674230/216449396-f148db1c-ee4a-47b4-9156-96d001b09187.png">

**Comment by zmb3** [comment]
I think @alexfornuto has backports open to fix this.

**Comment by alexfornuto** [comment]
Yes, this was resolved in #21095 - but thanks for letting us know all the same!
