### ISSUE TITLE
Fix typo in X.509 certificate image

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#21215]
## Applies To
https://goteleport.com/docs/architecture/authentication/

This image in particular:

https://goteleport.com/docs/_next/static/media/x509-cert@2x.902f96d8.svg

![image](https://user-images.githubusercontent.com/1424442/216625666-dae806d2-8b46-41bf-92bd-efd15f3ba614.png)

## Details

The image needs to be re-done. There is a typo. 

Should say **device** but instead says **devcie** under the **Extensions** box.

**Comment by webvictim** [comment]
There is also a typo in algorithm
![image](https://user-images.githubusercontent.com/897821/221656111-bdf088a0-b715-49e7-b203-c055199fa9e8.png)
