### ISSUE TITLE
Support AWS OpenSearch database access

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#21211]
What would you like Teleport to do?

Support AWS OpenSearch database access in addition to the existing support for [Self-Hosted Elasticsearch](https://goteleport.com/docs/database-access/guides/elastic/).

What problem does this solve?

Provides support for both Cloud-managed and Self-hosted Elasticsearch. AWS OpenSearch is an open source, distributed search and analytics suite derived from Elasticsearch.

If a workaround exists, please include it.

N/A

**Comment by smallinsky** [comment]
Openserach seems to support IAM auth [dentity and Access Management in Amazon OpenSearch Service](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ac.html) where the integration can be done by the same way like AWS CLI access where teleport service is responsible for assuming an AWS role and requests signing

**Comment by othmane399** [comment]
@smallinsky how do you sign your requests with teleport ? as signing is done locally (just with your credentials) and theses credentials you need stays at the teleport agent level ?

**Comment by Tener** [comment]
> @smallinsky how do you sign your requests with teleport ? as signing is done locally (just with your credentials) and theses credentials you need stays at the teleport agent level which act as a proxy ?

@othmane399 Teleport will request AWS credentials and use them to assume the role associated with the incoming OpenSearch request. The assumed role will be used to sign the request before forwarding it to the OpenSearch instance. The credentials used never leave the Teleport service processing the request.

**Comment by kaan-carbon** [comment]
Team thanks for adding the OpenSearch database access feature! We are really waiting for this feature.

AWS's Fine-Grained Access Control mechanism requires request signing for accessing the OpenSearch service. 
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/fgac.html

SAML authentication mechanism is required to access Dashboards (Kibana) application.
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/saml.html
