### ISSUE TITLE
app access leaf cluster 

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#21238]
Expected behavior:
`--cluster` flag should be supported in `tsh app ls` command and consistent with other commands like: 
`tsh db connect --db-user=marek --cluster=leaf` where a user can select leaf cluster without requiring to login-in into leaf cluster. 

Current behavior:
` --cluster` flag is not supported in `tsh app login` command: 

```
tsh app login  --help
usage: tsh apps login [<flags>] <app>

Retrieve short-lived certificate for an app.

Flags:
  -l, --login                    Remote host login
      --proxy                    Teleport proxy address
      --user                     Teleport user [marek]
      --ttl                      Minutes to live for a session
  -i, --identity                 Identity file
      --cert-format              SSH certificate format
      --insecure                 Do not verify server's certificate and host name. Use only in test environments
      --auth                     Specify the name of authentication connector to use.
      --skip-version-check       Skip version checking between server and client.
  -d, --debug                    Verbose logging to stdout
  -k, --add-keys-to-agent        Controls how keys are handled. Valid values are [auto no yes only].
      --enable-escape-sequences  Enable support for SSH escape sequences. Type '~?' during an SSH session to list supported sequences. Default is enabled.
      --bind-addr                Override host:port used when opening a browser for cluster logins
      --mfa-mode                 Preferred mode for MFA and Passwordless assertions (auto, cross-platform, platform, otp)
  -J, --jumphost                 SSH jumphost
      --aws-role                 (For AWS CLI access only) Amazon IAM role ARN or role name.
      --azure-identity           (For Azure CLI access only) Azure managed identity name.

Args:
  <app>  App name to retrieve credentials for. Can be obtained from `tsh apps ls` output.
```
```
tsh app login app1 --cluster=leaf
ERROR: unknown long flag '--cluster'
```

**Comment by bendoerr** [comment]
Just ran into this issue as well. Seems like a major oversight?

**Comment by pschisa** [comment]
Workaround:
switch to a leaf cluster directly from root cluster using `tsh login leafcluster` and then log in to the leaf cluster app via `tsh app login appleaf`

**Comment by bendoerr** [comment]
> Workaround: switch to a leaf cluster directly from root cluster using `tsh login leafcluster` and then log in to the leaf cluster app via `tsh app login appleaf`

Ah so that is how you switch clusters!!!! I've been trying to figure that out for ever! Where in the world is that documented?

**Comment by smallinsky** [comment]
It looks like this feature is not explicitly documented though  you can find a reference to [tsh login <cluster>](https://goteleport.com/docs/reference/cli/#tsh-login) command in tsh cli docs.

**Comment by r0mant** [comment]
@Tener When fixing this, can you do https://github.com/gravitational/teleport/issues/25231 at the same time? Would be a nice UX improvement and is in the related area as this fix. cc @smallinsky

**Comment by greedy52** [comment]
Should the cluster flag be added to `tsh proxy app` and`tsh aws/azure/gcp` the same time?

Otherwise, it creates some UX inconsistency. For example:
```
$ tsh apps login --cluster my-leaf-cluster my-tcp-app
Logged into TCP app redis-tcp. Start the local TCP proxy for it:

  tsh proxy app my-tcp-app

Then connect to the application through this proxy.
```
Then both `tsh proxy app my-tcp-app` and `tsh proxy app --cluster my-leaf-cluster  my-tcp-app` do not work.
