### ISSUE TITLE
enable server-side-encryption w/auto-created AWS Dynamo tables

### ISSUE THREAD

**Issue by aberoham** [gravitational/teleport#2127]
**What happened**: Teleport-auth's dynamo storage configuration as-is does not allow an administrator to enable AWS Dynamo's server-side encryption within teleport.yaml. 

The AWS Marketplace and examples/aws/terraform/dynamo.tf recipes get around this by creating the required tables w/encryption enabled before teleport-auth first starts. 

**What you expected to happen**: There should be an configuration option to enable dynamo's server-side encryption. Note that not all AWS regions support the required Dynamo/KMS integration to enable encryption at rest.

**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Environment**:
- Teleport version (use `teleport version`): 2.6.7
- Tsh version (use `tsh version`): n/a
- OS (e.g. from /etc/os-release):

**Comment by ken5scal** [comment]
S3 server-side-encryption for `audit_sessions_uri`  would be helpful as well.

**Comment by awly** [comment]
Auto-created DynamoDB tables should default to using server-side encryption using AWS-managed keys.
