### ISSUE TITLE
Standalone `tbot` docker image

### ISSUE THREAD

**Issue by hagaibarel** [gravitational/teleport#21280]
What would you like Teleport to do?

I would like `teleport` to publish a standalone container image with just the `tbot` binary included, so running it as a sidecar won't required pulling the entire teleport image which is ~600mb in size.

What problem does this solve?

Smaller footprint for running `tbot` as a sidecar container for other applications, smaller image -> less time to pull -> quicker startup, especially in a kubernetes pod sidecar setup.

If a workaround exists, please include it.

Other than building a custom version of the docker image, none.

It might be related to the this thread https://github.com/gravitational/teleport/issues/8735, although specifically I'm referring to `tbot` container image

**Comment by strideynet** [comment]
Thanks for raising this. I don't see why we couldn't do this ! 

I'm sure https://github.com/gravitational/teleport/issues/19019 will be of interest to you as well.

**Comment by hagaibarel** [comment]
Hi folks, any update on this?

**Comment by Jasstkn** [comment]
we ended up writing our own Dockerfile for tbot:
```Dockerfile
FROM frolvlad/alpine-glibc:alpine-3.17 AS builder

ARG TELEPORT_VERSION
ARG ARCH=amd64

RUN apk add curl


RUN curl https://get.gravitational.com/teleport-ent-v${TELEPORT_VERSION}-linux-${ARCH}-bin.tar.gz.sha256 > checksum  && \
    curl -O https://cdn.teleport.dev/teleport-ent-v${TELEPORT_VERSION}-linux-${ARCH}-bin.tar.gz && \
    sha256sum -c checksum

RUN tar -xvf teleport-ent-v${TELEPORT_VERSION}-linux-${ARCH}-bin.tar.gz && \
    cd teleport-ent && \
    ./install

FROM frolvlad/alpine-glibc:alpine-3.17

COPY --from=builder /usr/local/bin/tbot /usr/local/bin/tbot
```

**Comment by strideynet** [comment]
Work has started on this ✅

**Comment by strideynet** [comment]
After the image has been released, the documentation for the Machine ID on Kubernetes flow should be updated. We aim to publish this for v15, v14 and v13.

**Comment by strideynet** [comment]
public.ecr.aws/gravitational/tbot-distroless:15.1.0 is now available. We've also backported this to 14/13 so this should also be available in their next releases.

**Comment by hagaibarel** [comment]
Fantastic, thanks a lot.

Just for reference:

```shell
$ docker images
REPOSITORY                                         TAG       IMAGE ID       CREATED       SIZE
public.ecr.aws/gravitational/teleport-distroless   15.1.0    f70023b07832   8 hours ago   658MB
public.ecr.aws/gravitational/tbot-distroless       15.1.0    1785d46a3f20   8 hours ago   127MB
```

The `tbot` image is ~20% of the full `teleport` image

**Comment by strideynet** [comment]
Great - just the result I was hoping for. I'm hoping to carry out some refactors over the next few quarters to reduce the dependencies of `tbot` and keep shrinking that binary :D
