### ISSUE TITLE
Unable to add initial user using Ansible's "shell"

### ISSUE THREAD

**Issue by kajogo777** [gravitational/teleport#2129]
**What happened**:
trying to add a user
"tctl users add  user-admin root"
"error: tctl must be used on the auth server"

**What you expected to happen**:
user to be added (since Ansible executes this command on the machine with an Auth node running)

**Comment by kajogo777** [comment]
this should not violate the tctl should be used locally on the server, please explain the mechanism by which tctl determines it's on the server, and how to circumvent this to bootstrap my initial user and nodes

**Comment by kajogo777** [comment]
update:

when trying to add user via ssh on local machine:
ssh -o StrictHostKeyChecking=no root@{ip address}tctl users add --ttl=3h xyz-admin root

it fails first and i get "tctl must be used on the auth server"
then if i try execute the same command again, user is created successfully, which is very odd the behavior is non-deterministic

**Comment by aberoham** [comment]
Hi George, please attach or share debug-level logs, ie `tctl -d` showing the scenario you are encountering. Please also let us know what version of Teleport you're running.

**Comment by kajogo777** [comment]
now it doesn't work at all :D

**Comment by kajogo777** [comment]
adding a sleep time buffer before issuing these command seems to solve the issue

for Ansible
after server start or restart:
`-  wait_for:
         timeout=60
`
then follow through using tctl

however the error message could be more descriptive than just 
> tctl must be used on the auth server

**Comment by klizhentas** [comment]
I agree on the error message part, thanks for the report on this
