### ISSUE TITLE
Generate a reference of Teleport API endpoints

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#21297]
## Applies To

Our API section: https://goteleport.com/docs/api/introduction/

## Details

We should auto-generate a reference of API endpoints so users looking to build API consumers outside the narrow confines of our [API getting started guide](https://goteleport.com/docs/api/getting-started/) can find a way to meet their needs.

## Related Issues

- https://github.com/gravitational/teleport/issues/19716

**Comment by strideynet** [comment]
I would recommend looking into https://github.com/pseudomuto/protoc-gen-doc - I have used this previously for documenting gRPC APIs.

**Comment by ptgott** [comment]
Since our API client is documented on `pkg.go.dev` (https://pkg.go.dev/github.com/gravitational/teleport/api/client#section-readme), and I'm guessing most/all Go developers are comfortable with the GoDoc format, I'm tempted to refer readers here instead of generating a reference for the docs. That said, there's probably some work we can do helping API client developers understand the scope of the library, some commonly used types/functions, etc.
