### ISSUE TITLE
Hide all unavailable `Feature`s

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#21312]
Track down the ACL flags (or the RBAC flags that need to be added to the ACL) that determine access to each `Feature`. Look for `Feature`s with an `isAvailable` function that looks like
```javascript
isAvailable(ctx: Ctx): boolean {
    return true; // TODO(isaiah)
}
```
to find the `Feature`s which are yet to be properly hidden.

It would also be helpful to add some tests that check that features are properly hidden, and that entire groups of features (such as e.g. "Activity") are hidden if none of the child `Feature`s are available.

See the description in https://github.com/gravitational/webapps/pull/845 for the motivation.
Don't forget about enterprise features https://github.com/gravitational/webapps.e/pull/292

**Comment by zmb3** [comment]
This is not something we'll address - the goal is to make features more discoverable, even if they are disabled.
