### ISSUE TITLE
Make the "Connect your Client" docs more visible

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#21316]
## Applies To

`/docs/connect-your-client`

## Details

Let's see if we can make our docs for end users more visible. Currently, our admin-focused docs (i.e., all docs pages except for those in the "Connect your Client" section) get more traffic than the "Connect your Client" docs, even though there are ostensibly more end users than operators.

Some possibilities:

- [x] Link to this section on our landing page and make this link especially visible

- [x] Add a more prominent link to the end-user docs on the Teleport corporate site

- [ ] Improve the SEO of our end-user docs

- [ ] Rename the section from "Connect your Client"

**Comment by ptgott** [comment]
@alexfornuto @stevenGravy Do you have any thoughts on ways to make this section more visible? I'm tempted to close this issue because, as it stands, this section is already quite popular: it comes just below `/installation/` and above `/try-out-teleport`/ in terms of pageviews

**Comment by alexfornuto** [comment]
@ptgott Before closing, I'd like to dig into this line a bit:

> Add a more prominent link to the end-user docs on the Teleport corporate site

Can you give an example of what sort of end-user docs are on the marketing site? Both to address this issue, and because I'm interested in looking into what docs live elsewhere, and how they are being maintained.

**Comment by ptgott** [comment]
There's the "Teleport Clients" link in the "Documentation" dropdown, which is the only place the corpsite links to the "Connect your Client" section of the docs.

As far as I know, there aren't any how-to guides for using client tools on the main Teleport site.

**Comment by ptgott** [comment]
There's the "Teleport Clients" link in the "Documentation" dropdown, which is the only place the corpsite links to the "Connect your Client" section of the docs.

As far as I know, there aren't any how-to guides for using client tools on the main Teleport site.

**Comment by alexfornuto** [comment]
> Rename the section from "Connect your Client"

Is this something we're still interested in? What other names would we choose from?

**Comment by ptgott** [comment]
I'm not sure, to be honest. I think "Connect your Client" is an accurate description. If "Client" is too vague, we could think about using "Connect to your Infrastructure", which is more along the lines of what and end user would be using Teleport to do. But I'm not sure that's a meaningful improvement.

**Comment by alexfornuto** [comment]
I think if we were gonna rename it, it would be something about "end users", to be an eye-catch for folks not managing Teleport, but using it to access things.

@xinding33 do you have any input on this discussion? If not, I'd say we close it as 'as complete as it can be.... _for now_"

**Comment by ptgott** [comment]
Closing so we're not blocked on Xin. Xin, if needed, please feel free to reopen. Thanks!
