### ISSUE TITLE
Design for improved passkey support

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#21319]
Design support for #19314 - Improving Passkey Support.

Recommended route: split username and authentication so that we can recommend the appropriate login approach based on the username. See the link shared in a comment to #19314 for more about this approach: https://passkeys.dev/docs/use-cases/bootstrapping/

Default to passwordless for auth setup.

**Comment by roraback** [comment]
Let's also revisit the sign-up flow to make passwordless sign-up clearer and more prominent. ccing @rishibarbhaya-design

**Comment by roraback** [comment]
Engineering not planning until Q3

**Comment by rishibarbhaya-design** [comment]
Based on the requirement, we have designed the revised passkey flow. 
Click here to access the [Figma Designs ](https://www.figma.com/file/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?type=design&node-id=7052%3A56894&mode=design&t=2YH0oZGHiL8LFYt3-1)

The design includes the following section

1. Account Setup | Passkey Option OR Manual Setup
2. Password | Set Password & Change Password
3. Account Settings Default Views
4. Passkeys Setup & Multiple Flows
5. Login Flows
6. Recovery Flow
