### ISSUE TITLE
Design to redact secrets by default from the web-based YAML editor

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#21323]
Design support for #16159 - Redact secrets within web based YAML editor

For consideration
- Do we go with a single toggle as suggested in #16159?
- Do we show a toggle option right next to the redacted secrets?

Solution should 
1. hide secrets in YAML files _by default,_ 
2. enable users to show secrets, and
3. enable users to hide secrets once shown

**Comment by rishibarbhaya-design** [comment]
Sharing multiple variations for designs.
Click on this link to view in detail: https://www.figma.com/proto/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?page-id=4873%3A95019&type=design&node-id=4873-95726&viewport=1909%2C908%2C0.45&scaling=min-zoom

**Comment by benarent** [comment]
@rishibarbhaya-design , I can't view that design 
<img width="2072" alt="image" src="https://github.com/gravitational/teleport/assets/559288/e0245109-2780-48f6-b3fb-7ff4f911b0f9">

**Comment by roraback** [comment]
@benarent my understanding is that you reviewed this with Rishi, but I'm attaching the correct link for anyone else tracking the issue: https://www.figma.com/file/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?type=design&node-id=4873%3A95019&t=ifmpA1VKOXi5sq2W-1

**Comment by benarent** [comment]
The 'Traditional Approach' to view / hide secrets is perfect. In an ideal work, a user wouldn't be able to retrive secrets from YAML config but that would require use to build another secret system and or use load secrets from disk.
