### ISSUE TITLE
New Metric: Unique User Login Count

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#21352]
What would you like Teleport to do?
Add a [metric](https://goteleport.com/docs/ver/10.x/reference/metrics/) that can count when users (with username) logged into Teleport and how many times. 

What problem does this solve?
Switching to a user-base model and would like to measure/monitor how many users are currently connecting/using Teleport Cluster. This will allow us to gauge if we need to scale. 

If a workaround exists, please include it.
We currently have `user_login_total`, but this only provides the total number of user logins. No specific counts per user/username login. In addition, they can use a Loki log query to count a user.login event, but this query takes a very long time when increasing the time range to weeks/months.

**Comment by tunguyen9889** [comment]
This is the current Loki log query I'm using to count user.login event:

```
count by (user) (count_over_time({job="teleport/teleport-cluster"} | json | component="audit" | event="user.login" [1h]))
```
