### ISSUE TITLE
App configuration missing labels 

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#21365]
Expected behavior:

Teleport configure --roles=app --node-labels=env=prod either produces an app config with the labels env=prod, or produces an error informing the user that --node-labels is not valid with --roles=app (and, ideally, offers a parameter that will allow the user to set the labels on the indicated app; none are shown in teleport configure help)

Current behavior:
an app config is created but lacks any labels

Bug details:
- Teleport version: teleport-ent 11.3.1
- Recreation steps
teleport configure --roles=app --output=/etc/teleport/east/test1.yaml --node-labels=env=prod,access=eng --app-name=test --app-uri=https://127.0.0.1/
teleport configure --roles=app --output=/etc/teleport/east/test2.yaml --node-labels=env=prod --app-name=test --app-uri=https://127.0.0.1/
teleport configure --roles=app --output=/etc/teleport/east/test3.yaml --node-label env=prod --app-name=test --app-uri=https://127.0.0.1/
teleport configure --roles=node --output=/etc/teleport/east/test4.yaml --node-labels=env=prod
teleport configure --roles=app --output=/etc/teleport/east/test5.yaml --apps-labels=env=prod --app-name=test --app-uri=https://127.0.0.1/

for file in `ls test*`; do echo "# printing $file"; cat $file; done

version: v3
teleport:
  nodename: <IP_ADDRESS>.us-east-2.compute.internal
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: test
    uri: https://127.0.0.1/
    public_addr: ""
    insecure_skip_verify: false

version: v3
teleport:
  nodename:<IP_ADDRESS>.us-east-2.compute.internal
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: test
    uri: https://127.0.0.1/
    public_addr: ""
    insecure_skip_verify: false

version: v3
teleport:
  nodename: <IP_ADDRESS>us-east-2.compute.internal
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
app_service:
  enabled: "yes"
  debug_app: false
  apps:
  - name: test
    uri: https://127.0.0.1/
    public_addr: ""
    insecure_skip_verify: false

version: v3
teleport:
  nodename: <IP_ADDRESS>.us-east-2.compute.internal
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    env: prod
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
- Debug logs

I doubt any logs will be helpful here. The behavior is pretty straight forwards

**Comment by zmb3** [comment]
@moisesmejia1200 how is this different from #21364?

**Comment by arcaven** [comment]
> @moisesmejia1200 how is this different from #21364?

They are the same issue, reported in one thread via slack. These two, the write up and the original problem expressed via terminal output, got separated when entered into GitHub issue tickets.

**Comment by zmb3** [comment]
Gotcha. I'll close this one then to keep the discussion at #21364.
