### ISSUE TITLE
Machine ID: Per-session MFA

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#21423]
# The problem

Some users in security conscious environments enable cluster-wide per-session MFA. This requires that when connecting a node that the user has completed MFA for that individual session.

Machine ID lacks the ability to prompt a user to complete MFA and this means that if cluster-wide per-session MFA is enabled, Machine ID will not function.

# Current implementation

See https://github.com/gravitational/teleport/blob/master/rfd/0014-session-2FA.md for detailed background on the implementation of per-session MFA.

To simplify this, per-session MFA is implemented and enforced via an additional fields that can be included in certificates. Clients, before connecting to a Node when per-session MFA is enabled, will complete a challenge and response flow that prompts the user for MFA with the Auth server in order to receive a single-use certificate with this field. 

These fields indicate the ID of the MFA device that was used to authenticate the signing, and the intended target of the connection. Nodes receiving connections check the global state of per-session MFA as well as the per-session MFA configuration of a users roles, and ensures that this MFA device ID field is provided. They also check that they are listed as the intended target.

Per-session MFA certificates also have an extremely short TTL (1 minute) in which they can be used to establish connections.

# Solutions

## Ignore per-session MFA enforcement for bot user certificates

The simplest solution here is to modify the per-session MFA enforcers to ignore this requirement for bot users. This would require us to encode a field within the certificates that indicate whether or not a certificate belongs to a bot or human user, or require the nodes to look up the user to check their type. In the interest of reducing requests made to the auth service, it seems to make sense to include this within the certificate.

One open question is whether or not we make this mode of operation configurable. We could introduce another option alongside `require_session_mfa` e.g:

```yaml
auth_service:
  authentication:
    require_session_mfa: yes
    require_session_mfa_exclude_bots: yes
```

My preference would be, that in the absence of any particularly defined user use-case for this, and ensuring that we do not compromise the security of per-session MFA for users, that we make this behaviour un-configurable to ensure a better out of the box experience for users using Machine ID and to reduce Teleport configuration complexity.

# Workaround

Currently, per-session MFA can still be used by making use of role-based per-session MFA. Users can create roles designed for humans (with role-based per-session MFA enabled) and roles designed for machines (without role-based per-session MFA enabled). This is extremely high friction and introduces the overhead of managing this on a per-role basis, when several customers would prefer to enable it globally.

**Comment by klizhentas** [comment]
From the security perspective, instead of removing per-session MFA requirement, we can enforce that MachineID uses secure enclave and use this as a device ID that will pass per-session MFA requirement for MachineID certificates.

**Comment by strideynet** [comment]
> From the security perspective, instead of removing per-session MFA requirement for MachineID certs, we can enforce that if MachineID uses secure enclave/TPM and treat it as a device ID that will pass per-session MFA requirement for MachineID certificates.

That's an interesting idea that definitely avoids compromising the security of per-session MFA - and TPM/HSM/Secure Enclave support is something we've had on the radar for Machine ID for a while anyway. We'll need to reach out to the customer and confirm that they have TPM capabilities in their environment though - and then assess how large of a build this is likely to be.

**Comment by klizhentas** [comment]
Recording the summary of the follow conversation, the task for MachineID here:

* The external system receives a request from a user to run a set of commands, and does some app specific checks, etc.
* Once approved, it sends the list of commands to run to a CI/CD system, instructing it to impersonate the user
* The user in question can have a role set that requires per session MFA or a trusted device.

The right solution would be to ask MachineID is not to impersonate a user, but to take users's role set, remove irrelevant options (like per session MFA, etc) and then ask MachineID to impersonate an equivalent role set?

**Comment by strideynet** [comment]
> Recording the summary of the follow conversation, the task for MachineID here:
> 
> * The external system receives a request from a user to run a set of commands, and does some app specific checks, etc.
> * Once approved, it sends the list of commands to run to a CI/CD system, instructing it to impersonate the user
> * The user in question can have a role set that requires per session MFA or a trusted device.
> 
> The right solution would be to ask MachineID is not to impersonate a user, but to take users's role set, remove irrelevant options (like per session MFA, etc) and then ask MachineID to impersonate an equivalent role set?

Machine ID in its current state is not compatible with user impersonation. This is something we could look into, but right now, Machine ID outputs role impersonated certificates which are prohibited from being used to further issue certificates (e.g they cannot be used to then impersonate a user).

The impression I am getting is that customers are after the convenience of being able to enable per-session MFA cluster-wide (with humans in mind) and for Machine ID to work regardless. This avoids the overhead of the current work-around which means disabling this cluster-wide, and carefully ensuring all human roles have per-session MFA enabled and that no machine roles do.

In Device Trust's current state it can only be configured cluster-wide. This means that Device Trust in required mode and Machine ID are effectively mutually exclusive. If we want to see uptake in both of these parts of Teleport, then we need to find a solution for this soon that is convenient and secure.

---

I'm tempted to suggest that we address the TPM/HSM work and this work around cluster-wide per-session MFA and device trust as separate endeavours. Whilst it would certainly be neat to implement some system whereby Machine ID instances leveraging a TPM would pass the enforcement of cluster-wide per-session MFA/device-trust, from conversations with customers it does not appear that TPMs are commonplace in environments where Machine ID is being used. Whilst PKCS#11 compatible HSMs are more common, this API lacks any way to remotely verify that a key is indeed being stored in the HSM.

I'm also of the belief that Device Trust and per-session MFA tackle a different range of threats than enforcing Machine ID use of TPMs would, and that configuring this as a single option for both humans and machines conflates this. It seems entirely reasonable that you would enforce per-session MFA with humans in mind, and be satisfied with your existing security controls for your machine environments.

So what I'd suggest instead is probably three units of work:

- Machine ID certificates bypass the requirement for per-session MFA or Device Trust, as the standard behaviour or as something that is explicitly enabled depending on what we assess the risk of this to be - this unblocks Machine ID for customers using per-session MFA or Device Trust cluster-wide as soon as possible, which seems to be the primary request.
- Support in Machine ID for storing credentials in a PKCS#11 cryptographic store.
- Eventually (dependent on verifying TPM support exists in customer Machine ID environments), TPM support in Machine ID and the ability to configure cluster-wide/role-based that Machines must be using a TPM to interact with this role.

**Comment by klizhentas** [comment]
I don't think MachineID should bypass per-session MFA or Device Trust, as it creates serious security vulnerability, so we can drop  this initiative. I will work with customer on alternatives.

We can also explore TPM support and PKCS#11 support separately from this issue.

**Comment by strideynet** [comment]
Opened https://github.com/gravitational/teleport/issues/21555 and https://github.com/gravitational/teleport/issues/21554 to cover TPM and PKCS#11 support as a result of this ticket.
