### ISSUE TITLE
Trusted cluster not showing nodes unless user logs in after trusted cluster is setup

### ISSUE THREAD

**Issue by knisbet** [gravitational/teleport#2142]
**What happened**: 
`tsh ls --cluster <abc>` wasn't showing any nodes for a trusted cluster, when the trusted cluster was created after the user logged in.

This may be by design and only be a UX issue, that the login needs to be recreated when connecting to new clusters, but it presents as not working since `tsh ls --cluster` just shows an empty cluster.

**What you expected to happen**:
`tsh ls --cluster <abc>` to show the nodes

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup a master cluster
2. Login to the master cluster `./tsh login...`
3. Setup second cluster
4. Connect second cluster to the master cluster
5. Try and view the cluster `tsh ls --cluster second`

Note: logging out / logging in clears the issue, it's important to login before connecting the second cluster

**Environment**:
- Teleport version (use `teleport version`): Teleport v3.0.0-alpha.4 git:v3.0.0-alpha.4-0-g36d7cb77
- Tsh version (use `tsh version`): Teleport v3.0.0-alpha.4 git:v3.0.0-alpha.4-0-g36d7cb77
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS (Xenial Xerus)

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug
```
Aug 06 16:13:14 meetup-devopsto-prod-jump-0 teleport[3528]: DEBU [PROXY:AGE] Outbound tunnel for meetup-devopsto connected to 1 proxies. cluster:meetup-devopsto-prod reversetunnel/agentpool.go:341
Aug 06 16:13:14 meetup-devopsto-prod-jump-0 teleport[3528]: DEBU [PROXY:AGE] ping -> 35.203.119.68:3024 target:meetup-devopsto.jump.gravitational.io:3024 reversetunnel/agent.go:516
Aug 06 16:13:17 meetup-devopsto-prod-jump-0 teleport[3528]: DEBU [PROXY:AGE] transport request: teleport-transport target:meetup-devopsto.jump.gravitational.io:3024 reversetunnel/agent.go:530
Aug 06 16:13:17 meetup-devopsto-prod-jump-0 teleport[3528]: DEBU [PROXY:AGE] proxyTransport target:meetup-devopsto.jump.gravitational.io:3024 reversetunnel/agent.go:319
Aug 06 16:13:17 meetup-devopsto-prod-jump-0 teleport[3528]: DEBU [PROXY:AGE] Received out-of-band proxy transport request: [10.162.0.19:3025] target:meetup-devopsto.jump.gravitational.io:3024 reversetunnel/agent.go:319
Aug 06 16:13:17 meetup-devopsto-prod-jump-0 teleport[3528]: DEBU [PROXY:AGE] Successfully dialed to @remote-auth-server, start proxying. target:meetup-devopsto.jump.gravitational.io:3024 reversetunnel/agent.go:407
Aug 06 16:13:17 meetup-devopsto-prod-jump-0 teleport[3528]: 2018/08/06 16:13:17 http: TLS handshake error from 10.162.0.19:41818: remote error: tls: bad certificate
```

**Comment by kontsevoy** [comment]
@klizhentas is this caching?

**Comment by russjones** [comment]
This is an issue with identity aware GetNodes.
