### ISSUE TITLE
`TestDialLocalAuthServerNoAvailableServers` flakiness

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#21453]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4124635357/jobs/7124129959

#### Relevant snippet

```
===================================================
FAIL: github.com/gravitational/teleport/lib/srv/alpnproxy/auth
FAIL: github.com/gravitational/teleport/lib/srv/alpnproxy/auth.TestDialLocalAuthServerNoAvailableServers
===================================================
OUTPUT github.com/gravitational/teleport/lib/srv/alpnproxy/auth.TestDialLocalAuthServerNoAvailableServers
===================================================
=== RUN   TestDialLocalAuthServerNoAvailableServers
    auth_proxy_test.go:38: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/alpnproxy/auth/auth_proxy_test.go:38
        	Error:      	An error is expected but got nil.
        	Test:       	TestDialLocalAuthServerNoAvailableServers
        	Messages:   	dialLocalAuthServer expected to fail
--- FAIL: TestDialLocalAuthServerNoAvailableServers (0.00s)
===================================================
```

**Comment by GavinFrazar** [comment]
This one is bizarre. The test case just calls `NewAuthProxyDialerService` passing `nil` for the slice of auth servers. Then it calls `s.dialLocalAuthServer` which should immediately detect `len(s.authServers) == 0` and return an error 🤔

**Comment by mdwn** [comment]
> This one is bizarre. The test case just calls `NewAuthProxyDialerService` passing `nil` for the slice of auth servers. Then it calls `s.dialLocalAuthServer` which should immediately detect `len(s.authServers) == 0` and return an error 🤔

I think that's `TestDialLocalAuthServerNoServers`. The flaky one, `TestDialLocalAuthServerNoAvailableServers`, uses `0.0.0.0:3025` as an auth server. I've got a feeling that this is inadvertently being run on executors that have something at this port, perhaps our integration tests?
