### ISSUE TITLE
Add Ubuntu 22.10 support to repos

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#21459]
**What would you like Teleport to do?**

Provide apt packages out of the box for installing on Ubuntu 22.10 `kinetic`

**What problem does this solve?**

Lack of packages for a newer OS.

**If a workaround exists, please include it.**

`sudo sed -i 's/kinetic/jammy/g' /etc/apt/sources.list.d/teleport.list && apt -y update`

**Comment by zmb3** [comment]
#18679 ?

**Comment by webvictim** [comment]
Yep - it didn't appear in search because it doesn't contain the string "22.10"
