### ISSUE TITLE
Timezone for audit logs 

### ISSUE THREAD

**Issue by vjmax** [gravitational/teleport#21469]
What would you like Teleport to do?

Audit log and session logs only in UTC.we need to change the timezone for logs but it's not possible please include that future it will really helpful for us to access logs in our time IST.

What problem does this solve? 

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Displaying the audit log in UTC was a recent product decision (see #14562) and not something we're likely to change in the near future.
