### ISSUE TITLE
New node unable to join cluster

### ISSUE THREAD

**Issue by GunFood** [gravitational/teleport#21461]
Expected behavior:
Installed a new node and followed "Add Server" workflow.
Installation went fine and node continous the workflow in "Set Up Access".

Current behavior:
Installation without any issue, but workflow is stuck at "Configure Ressources". Node is note joined to cluster.

Bug details:
- Teleport version 12.0.1
- logs

**Node Log:**
```
Feb  8 16:23:00 inf-web systemd[1]: Started Teleport Service.
Feb  8 16:23:00 inf-web teleport[49902]: 2023-02-08T16:23:00+01:00 INFO             Starting Teleport v12.0.1 with a config file located at "/etc/teleport.yaml" common/teleport.go:516
Feb  8 16:23:00 inf-web teleport[49902]: 2023-02-08T16:23:00+01:00 INFO [PROC:1]    Generating new host UUID: 2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5. pid:49902.1 service/service.go:5067
Feb  8 16:23:00 inf-web teleport[49902]: 2023-02-08T16:23:00+01:00 INFO [PROC:1]    Joining the cluster with a secure token. pid:49902.1 service/connect.go:585
Feb  8 16:23:00 inf-web teleport[49902]: 2023-02-08T16:23:00+01:00 INFO [PROC:1]    Joining the cluster with a secure token. pid:49902.1 service/connect.go:585
Feb  8 16:23:01 inf-web teleport[49902]: 2023-02-08T16:23:01+01:00 INFO [AUTH]      Attempting registration via proxy server. auth/register.go:251
Feb  8 16:23:01 inf-web teleport[49902]: 2023-02-08T16:23:01+01:00 INFO [AUTH]      Attempting registration via proxy server. auth/register.go:251
Feb  8 16:23:06 inf-web teleport[49902]: 2023-02-08T16:23:06+01:00 INFO [AUTH]      Successfully registered via proxy server. auth/register.go:258
Feb  8 16:23:06 inf-web teleport[49902]: 2023-02-08T16:23:06+01:00 INFO [PROC:1]    Instance has obtained credentials to connect to the cluster. pid:49902.1 service/connect.go:635
Feb  8 16:23:06 inf-web teleport[49902]: 2023-02-08T16:23:06+01:00 INFO [AUTH]      Successfully registered via proxy server. auth/register.go:258
Feb  8 16:23:06 inf-web teleport[49902]: 2023-02-08T16:23:06+01:00 INFO [PROC:1]    Node has obtained credentials to connect to the cluster. pid:49902.1 service/connect.go:635
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [PROC:1]    The process successfully wrote the credentials and state of Instance to the disk. pid:49902.1 service/connect.go:676
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [PROC:1]    Instance: features loaded from auth server: Kubernetes:true App:true DB:true Desktop:true  pid:49902.1 service/connect.go:92
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [INSTANCE:] Successfully registered instance client. pid:49902.1 service/service.go:2134
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [PROC:1]    The process successfully wrote the credentials and state of Node to the disk. pid:49902.1 service/connect.go:676
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [PROC:1]    Node: features loaded from auth server: Kubernetes:true App:true DB:true Desktop:true  pid:49902.1 service/connect.go:92
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [NODE:1:CA] Cache "node" first init succeeded. cache/cache.go:802
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO             debug -> starting control-stream based heartbeat. regular/sshserver.go:817
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [NODE:1]    Service is starting in tunnel mode. pid:49902.1 service/service.go:2397
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [UPLOAD:1]  starting upload completer service pid:49902.1 service/service.go:2460
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log. pid:49902.1 service/service.go:2500
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log/upload. pid:49902.1 service/service.go:2500
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log/upload/streaming. pid:49902.1 service/service.go:2500
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log/upload/streaming/default. pid:49902.1 service/service.go:2500
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log. pid:49902.1 service/service.go:2500
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log/upload. pid:49902.1 service/service.go:2500
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log/upload/corrupted. pid:49902.1 service/service.go:2500
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [UPLOAD:1]  Creating directory /var/lib/teleport/log/upload/corrupted/default. pid:49902.1 service/service.go:2500
Feb  8 16:23:26 inf-web teleport[49902]: 2023-02-08T16:23:26+01:00 INFO [PROC:1]    The new service has started successfully. Starting syncing rotation status with period 10m0s. pid:49902.1 service/connect.go:687
```

**Cluster Log:**
```
2023-02-08T16:23:05+01:00 INFO [AUTH]      Node "inf-web.sysops-XXXXX.local" [2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5] is trying to join with role: Node. auth/join.go:104
2023-02-08T16:23:05+01:00 INFO [AUTH]      Node "inf-web.sysops-XXXXX.local" [2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5] is trying to join with role: Instance. auth/join.go:104
2023-02-08T16:23:05+01:00 INFO [CA]        Generating TLS certificate {0xa67e2c0 0xc002e74230 1.3.9999.1.7=#131862617374696f6e2e7379736f70732d736368756c652e6465,1.3.9999.2.11=#13044e6f6465,CN=2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5.bastion.sysops-XXXXX.de,O=Instance,POSTALCODE=null,STREET= 2033-02-05 15:23:05.885550865 +0000 UTC [inf-web.sysops-XXXXX.local] [] 5 []}. common_name:2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5.bastion.sysops-XXXXX.de dns_names:[inf-web.sysops-XXXXX.local] locality:[] not_after:2033-02-05 15:23:05.885550865 +0000 UTC org:[Instance] org_unit:[] tlsca/ca.go:1091
2023-02-08T16:23:05+01:00 INFO [CA]        Generating TLS certificate {0xa67e2c0 0xc003962770 1.3.9999.1.7=#131862617374696f6e2e7379736f70732d736368756c652e6465,CN=2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5.bastion.sysops-XXXXX.de,O=Node,POSTALCODE=null,STREET= 2033-02-05 15:23:05.885569122 +0000 UTC [inf-web.sysops-XXXXX.local 2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5] [] 5 []}. common_name:2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5.bastion.sysops-XXXXX.de dns_names:[inf-web.sysops-XXXXX.local 2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5] locality:[] not_after:2033-02-05 15:23:05.885569122 +0000 UTC org:[Node] org_unit:[] tlsca/ca.go:1091
2023-02-08T16:23:05+01:00 INFO [AUTH]      Node "inf-web.sysops-XXXXX.local" [2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5] has joined the cluster. auth/join.go:286
2023-02-08T16:23:05+01:00 INFO [AUDIT]     instance.join cluster_name:bastion.sysops-XXXXX.de code:TJ002I ei:0 event:instance.join host_id:2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5 method:token node_name:inf-web.sysops-XXXXX.local role:Instance success:true time:2023-02-08T15:23:05.889Z token_name:************************60912a2f uid:3ab439c4-a5b7-44d0-bc02-41797454aacc events/emitter.go:265
2023-02-08T16:23:05+01:00 INFO [AUTH]      Node "inf-web.sysops-XXXXX.local" [2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5] has joined the cluster. auth/join.go:286
2023-02-08T16:23:05+01:00 INFO [AUDIT]     instance.join cluster_name:bastion.sysops-XXXXX.de code:TJ002I ei:0 event:instance.join host_id:2ccc21d1-62a0-4d5c-b55c-35f6f50a4ae5 method:token node_name:inf-web.sysops-XXXXX.local role:Node success:true time:2023-02-08T15:23:05.889Z token_name:************************60912a2f uid:3e5666e5-915a-41af-976c-fca60646a22f events/emitter.go:265
```

**Comment by r0mant** [comment]
@ryanclark @marcoandredinis Could you guys take a look if there's an issue with node joining flow in v12?

**Comment by marcoandredinis** [comment]
@GunFood Thank you for your report.

According to logs, everything worked as expected
Was the node actually added to your resources?
If so, we might have some error in the browser's console or network.
Could you please do it again and check for errors there?

**Comment by GunFood** [comment]
@marcoandredinis 
The server is not added to the resources. I also tried a different browser.
I will check the browser console

**Comment by GunFood** [comment]
``![2023-02-09_11h09_13](https://user-images.githubusercontent.com/10937518/217782617-1106e6fc-00f2-4e85-9b2e-a7db5a1f78da.png)

I get a message during deployment on the teleport server.
I switched the teleport log to debug on the new node, to see a bit more information.

`2023-02-09T11:05:01+01:00 DEBU [PROXY:AGE] Received discovery request: [5544c775-3a12-449f-9246-af54d595ea9e] leaseID:1 target:bastion.sysops-schule.de:443 cluster:bastion.sysops-schule.de reversetunnel/agent.go:649
2023-02-09T11:07:01+01:00 DEBU [PROXY:AGE] Received discovery request: [5544c775-3a12-449f-9246-af54d595ea9e] leaseID:1 target:bastion.sysops-schule.de:443 cluster:bastion.sysops-schule.de reversetunnel/agent.go:649
2023-02-09T11:07:32+01:00 DEBU [PROXY:AGE] Received discovery request: [5544c775-3a12-449f-9246-af54d595ea9e] leaseID:1 target:bastion.sysops-schule.de:443 cluster:bastion.sysops-schule.de reversetunnel/agent.go:649
2023-02-09T11:09:01+01:00 DEBU [PROXY:AGE] Received discovery request: [5544c775-3a12-449f-9246-af54d595ea9e] leaseID:1 target:bastion.sysops-schule.de:443 cluster:bastion.sysops-schule.de reversetunnel/agent.go:649
2023-02-09T11:09:51+01:00 DEBU             'teleport-service' group not found, not deleting users srv/usermgmt.go:305
2023-02-09T11:10:01+01:00 DEBU [PROXY:AGE] Ping -> 130.73.212.35:443. leaseID:1 target:bastion.sysops-schule.de:443 cluster:bastion.sysops-schule.de reversetunnel/agent.go:556`

**Comment by marcoandredinis** [comment]
I'm assuming you didn't change anything in the `teleport.yaml` generate by the `sudo bash $(curl ...)` command.

Can you please do a print of the network tab in the browser's devtool when you reach that screen?

**Comment by GunFood** [comment]
You assume right, nothing changed.

![image](https://user-images.githubusercontent.com/10937518/217796094-2803c4c0-bba0-4cae-9227-e1f1c76fcfa8.png)

**Comment by ryanclark** [comment]
@GunFood what permissions do you have in this cluster?

Can you please try the following steps -

On the machine you're trying to add, run

```
sudo systemctl stop teleport
sudo rm -rf /var/lib/teleport
sudo rm /etc/teleport.yaml
```

And then, in a new browser window, open up dev tools.

Go to your Teleport cluster and add a server

You'll notice in dev tools that there's a search request made every 3 seconds. Click on one of these requests, go to payload and take note of the `search` value

<img width="561" alt="image" src="https://user-images.githubusercontent.com/7922109/217797842-eebf996b-14b8-4fcb-b13a-609889de614e.png">

We care about the value after the `resource-id%20`, so `3d6c2d98-aa42-4953-a605-f5843b83df4c` in this case

After this, go back to the server and run the new command given to you on the screen

This will re-install & configure Teleport.

If the UI still hasn't detected this new instance of Teleport, on the server open up `/etc/teleport.yaml`

Look at `ssh_service` - does the value for `teleport.internal/resource-id` match the value we copied from the request earlier?

In this case, I'd hope to see:

```
ssh_service:
  enabled: "yes"
  labels:
    teleport.internal/resource-id: 3d6c2d98-aa42-4953-a605-f5843b83df4c
```

And then confirm that it's completely missing from the "Servers" page under "Resources" in your cluster?

**Comment by GunFood** [comment]
![image](https://user-images.githubusercontent.com/10937518/217810291-41ac5fe9-d91c-418b-9311-146b46e0d753.png)
![image](https://user-images.githubusercontent.com/10937518/217810314-628c648e-9d9c-41c3-857b-4f1175b727d5.png)

They match.

The workflow doesn't contiune. If I simply exist the flow for adding a new server, the server is still not shown in the Servers list.

**Comment by ryanclark** [comment]
Thanks for confirming @GunFood.

Could you please list the roles that your user has assigned? And if they're custom roles, could you share the RBAC rules for them?

My theory - for some reason the API isn't showing you the added resource, even though it's successfully joined. Taking a look at your RBAC rules would help see if this is correct

**Comment by GunFood** [comment]
You are right. I added the editor and access roles to my user and it's showing the server now. But I don't see an issue in my custom role config:

`kind: role
metadata:
  id: 1647257081109296552
  name: Company
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    kubernetes_groups:
    - admin
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
    logins:
    - root
    node_labels:
      env: '*'
    rules:
    - resources:
      - '*'
      verbs:
      - '*'
  deny:
    logins:
    - guest
  options:
    cert_format: standard
    create_host_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 8h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v3`

Shouldn't get the workflow to the next step, even if I don't see the new server in the servers list?

**Comment by marcoandredinis** [comment]
```yaml
    node_labels:
      env: '*'
```

This means that only nodes with the label key `env` (doesn't matter its value) are visible to the user.
Can you please either update your role to have a `'*': '*'` instead of the `env` line?

As an alternative, you can edit the `/etc/teleport.yaml` on the new node and add a label for `env` key. Example `env: something`
After this, restart the `teleport` process.

**Comment by marcoandredinis** [comment]
Are you on 12.0.1 as well?
Can you please share the roles your user has? As well as the `allow.node_labels` for those roles?

**Comment by danielslyman** [comment]
Thanks for taking the time, yes I am.

User   Roles
------ ---------------------
daniel editor,auditor,access
pvsv   editor,access

How do I do the second part?

**Comment by marcoandredinis** [comment]
You must open Management/Roles/<access/auditor/editor>/Options/Edit and look for the `allow.node_labels`
![image](https://user-images.githubusercontent.com/689271/217848845-fe56d420-719f-4ddb-9b94-3eb8c82370f9.png)

**Comment by danielslyman** [comment]
Found it one second before you answered, it's correctly set:


![image](https://user-images.githubusercontent.com/17143596/217849930-5361c8ea-9ad8-4f87-8157-9af4d52c2c14.png)

**Comment by danielslyman** [comment]
weirdly though, the node isn't listening to 3022

**Comment by marcoandredinis** [comment]
Can you please open another issue?
Seems to be something else

**Comment by marcoandredinis** [comment]
> Shouldn't get the workflow to the next step, even if I don't see the new server in the servers list?

@GunFood You will only be able to go to the next step if your roles allow you access to the server.
The same set of rules are applied when listing the servers.

If you changed your role, you might need to logout/login in order to see the servers list.
