### ISSUE TITLE
Teleport Agent Command Line arguments should be available in teleport.yaml config - `insecure-no-tls`

### ISSUE THREAD

**Issue by mechastorm** [gravitational/teleport#2147]
I am not sure if this is consistent in the Teleport agent yet, but it would be good if all CLI arguments are available to configure in the `teleport.yaml`. One example encountered is when configuring `insecure-no-tls`

**What happened**:

Teleport complains `insecure-no-tls` config is not valid when including it in the YAML config.

**What you expected to happen**:

When `/usr/local/bin/teleport start --config=/etc/teleport.yaml` is run, it detects the `insecure-no-tls` config in the YAML config.

**How to reproduce it (as minimally and precisely as possible)**:

Include the configuration `insecure-no-tls` in teleport.yaml to disable TLS.

Run `/usr/local/bin/teleport start --config=/etc/teleport.yaml`

**Environment**:
- Teleport version (use `teleport version`): 2.7.1 (enterprise)
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release): Ubuntu 14.04

**Comment by zmb3** [comment]
Closing - as per the discussion in https://github.com/gravitational/teleport/pull/12145 we want to keep the current behavior.
