### ISSUE TITLE
Flexible license enforcement

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2148]
## Context

Enterprise builds of Teleport need to selectively enforce usage restrictions based on flexible/arbitrary values encoded in the license file.

## Proposal

The Houston UI should give the sales person the controls to specify the following:

Property    | Data type | Description | UX 
--------------|--------------|----------------|------
Live usage reporting | boolean | If `true`, teleport should report usage to Gravitational | checkbox 
Kubernetes Proxy | boolean | If `false`, teleport auth should fail to start if the configuration file enables k8s proxy [1] | checkbox
Length of the trial period | date | Date after which Teleport should stop working [2] | calendar picker

[1] The error message must be shown to `stderr`: _"Your Teleport license does not have Kubernetes support enabled. Please reach out to sales@gravitational.com"_
[2] What do we currently do when Teleport license is expired? IIRC we show "yellow ribbon" with a warning. No change there.

**Comment by alex-kovoy** [comment]
This one is done. Houston Admin user can generate now above licenses for Teleport 3.

https://dashboard.gravitational.co/web/admin
