### ISSUE TITLE
Audit log event for `scp` does not match documentation.

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2149]
## Context

The audit log event for `scp` command is documented here (scroll down to "events" table):
https://gravitational.com/teleport/docs/admin-guide/#ssh-events

As you can see, `scp` event must contain:

```json
{"path": "/path/to/file.txt", "len": 32344, "action": "read" }
```

## Problem

Due to changes to `scp` implementation (it is based on `exec` under the hood), we currently create `exec` audit event which looks like this:

```json
{"addr.local":"127.0.0.1:3022","addr.remote":"127.0.0.1:56908",
  "command":"/bin/bash -c /home/sasha/go/src/github.com/gravitational/teleport/build/teleport scp --remote-addr=127.0.0.1:56908 --local-addr=127.0.0.1:3022 -t /tmp/sasha2","
event":"exec",
"login":"sasha",
"namespace":"default",
"time":"2018-08-07T20:42:53Z",
"user":"klizhentas@example.com"}
```

## Solution

The proper `scp` audit event must be recorded. Here's the place in code where it's _supposed_ to happen (audit log is `nil`???);

https://github.com/gravitational/teleport/blob/master/lib/sshutils/scp/scp.go#L313

Please make sure the proper `scp` even is logged for both uploads and downloads.
Also would be nice to NOT log the `exec` event for `scp`.

**Comment by klizhentas** [comment]
**Note** Implementation guidance - **DO NOT** add audit log to the `teleport scp` process. Instead, detect exec with scp, parse arguments and log a proper event.
