### ISSUE TITLE
Node join script should use apt/rpm repositories

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#21492]
## Description

Currently our automatic node join script installs Teleport by downloading either binary archive or deb/rpm file and installing them directly:

https://github.com/gravitational/teleport/blob/v12.0.0/lib/web/scripts/node-join/install.sh

As part of automatic upgrades work, we want to change that to instead use our existing apt/yum repositories, similar to how EC2 auto-discovery install script does:

https://github.com/gravitational/teleport/blob/v12.0.0/api/types/installers/installer.sh.tmpl

The reason for that is we want to unify how users install Teleport on their instances, whether through Discover flow (i.e. using node-join script) or through auto-discovery or manually using apt/yum install commands.

For Cloud customers we're introducing a separate `stable/cloud` channel for our deb/rpm repositories which will contain versions compatible with Cloud and also will include an additional systemd unit specific to Cloud's auto-upgrades. By having node-join script use package repositories Cloud customers will automatically get it installed when connecting their nodes to the Cloud. This also means we should be able to parameterize the script so it selects Cloud-specific channel when a Cloud user uses it via Discover flow.

## Success criteria

- [x] Discover's node join script uses apt/yum repository packages to install Teleport (Darwin is out of scope).
- [ ] When going through Discover flow, Cloud customers get a script that uses `stable/cloud` channel for apt/yum repos.

**Comment by marcoandredinis** [comment]
Is the `stable/cloud` available?
If so, what's the link I should use?

I was assuming something like this, but it doesn't seem to work
As an example, this link returns 404
```
https://apt.releases.teleport.dev/ubuntu/dists/jammy/stable/cloud/binary-amd64/Packages
```
But it works for v12
```
https://apt.releases.teleport.dev/ubuntu/dists/jammy/stable/v12/binary-amd64/Packages
```

**Comment by r0mant** [comment]
@marcoandredinis It is not available yet but @fheinecke is working on it.

For now let's just make sure that the repo can be passed to the install script as a parameter.

**Comment by marcoandredinis** [comment]
The install script is now using the apt/rpm repos.
We are still missing the switch to use the cloud channel (it's not completed afaik)
