### ISSUE TITLE
Have the ability to configure longer MFA sessions. 

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#21552]
**What would you like Teleport to do?**

Extend the per-session MFA duration/cache and make it configurable

**What problem does this solve?**

Currently doing a kubectl with per-session MFA means it requires MFA for every k8s action. Instead, it would be better if there was a per-session MFA that could be cached for ~5-10 mins

**If a workaround exists, please include it.**

No current workaround exists.

**Comment by zmb3** [comment]
This is a duplicate of #7568
