### ISSUE TITLE
RDP Connection Failed (Timed out)

### ISSUE THREAD

**Issue by mighty-services** [gravitational/teleport#21561]
Expected behavior:
Click on existing (registered) Windows Server Item and connect to it via RDP-Session.

Current behavior:
Click on existing (registered) Windows Server Item and it´s showing an Connection error:
![grafik](https://user-images.githubusercontent.com/71066192/217913656-2ae4c3eb-1fad-4405-8b91-b2c48043ad78.png)

Bug details:
- Teleport version 12.

Recreation steps
 - install teleport selfhosted-cluster ion ubuntu 22.04lts
 - install teleport client onsite on ubuntu 22.04lts
 - use auto enrollment-scripts from the teleport webpage to implement CA-Authority and generate yaml output
 - paste yaml output to teleport-client and start it
 - it connected 

Debug logs
- on the teleport-Client it shows me this errors:
![grafik](https://user-images.githubusercontent.com/71066192/217914242-01533da1-0c30-4427-9142-a8742280c8d2.png)

I tried so far:
- going through the [troubleshooting documentation](https://goteleport.com/docs/management/admin/troubleshooting/)
- goin through the [RDP-connection troubleshooting](https://goteleport.com/docs/desktop-access/troubleshooting/#rdp-connection-failed)
- setting up manual CA-certificate template and GPO-setting via the [manual tutorial](https://goteleport.com/docs/desktop-access/active-directory-manual/#step-47-configure-a-certificate-for-rdp-connections) Step 4

**Comment by zmb3** [comment]
This is covered in the troubleshooting docs: https://goteleport.com/docs/desktop-access/troubleshooting/#enhanced-rdp-security-with-credssp-required

The message about _enhanced RDP security with CredSSP_ indicates that your server is requiring RDP NLA, which we don't support yet. Disabling NLA should resolve your issue.

**Comment by mighty-services** [comment]
Unfortunately the link from the Page you´ve send me didn´t work, so I looked it up for myself.

I found [this instruction](https://kb.parallels.com/en/123661) and chhose the path via group policy.

I ended up with this on the target-server:
![grafik](https://user-images.githubusercontent.com/71066192/217928295-8d828369-0606-414b-bdd3-dbe5490bcacd.png)

When I try again, it´s showing the same error.

**Comment by zmb3** [comment]
Oops, I see the broken link now too. We'll get that fixed.

I might try rebooting the machine then. It looks like you did disable it, but if you're getting the same error, it means the server is still requiring NLA.

**Comment by mighty-services** [comment]
I rebotted and I laso completely reomve the items from the AD with this powershell commands
`get-aduser -filter * | Where-Object {$_.name -match "teleport"} | Remove-ADUser -Confirm:$false`

`remove-ADObject -Identity "CN=teleport,CN=CDP,CN=Public Key Services,CN=Services,CN=Configuration,$DOMAIN_DN" -Confirm:$false`

`remove-GPO "Block teleport-svc Interactive Login"`
`remove-GPO "Teleport Access Policy"`

at the end I ran your deployment script again, but it thows the same error

This client was added with the new teleport 12.0 release candidate and now with the 12.0.1 version.
The other ones (which are working just fine) where creates with the pervious version 11.x

**Comment by mighty-services** [comment]
well I rebotted the windows server and the teleport-client. And the windows host (still) sais the same thing

**Comment by mighty-services** [comment]
hm, interesting. Now it worked, once I remove all manual gpo-settings. So only the ones from the teleport Rollout-Script remained on the host:
![grafik](https://user-images.githubusercontent.com/71066192/217942764-5e6dbaa9-5565-4b12-a449-dd53a8461863.png)

that´s what the log on the teleport-client sis now:
```
[2023-02-09T21:24:11Z WARN  rdp_client::piv] unimplemented instruction Unknown(202)
GLOBAL: Parsing data PDU error RdpError(RdpError { kind: NotImplemented, message: "GLOBAL: Data PDU parsing not implemented Pdutype2SaveSessionInfo" })
[2023-02-09T21:24:18Z INFO  rdp_client::cliprdr] RDP server clipboard capabilities: GeneralClipboardCapabilitySet { version: 2, flags: CB_USE_LONG_FORMAT_NAMES | CB_STREAM_FILECLIP_ENABLED | CB_FILECLIP_NO_FILE_PATHS | CB_CAN_LOCK_CLIPDATA | CB_HUGE_FILE_SUPPORT_ENABLED }
```

I also followed [this tutorial](https://social.technet.microsoft.com/Forums/windowsserver/en-US/6f013b8f-85fc-4e89-b158-788e745d629f/domain-computer-not-located-within-public-key-services?forum=winserversecurity), since I discovered an event-id 94 disconnect item in the eventlog.
Maybe both fexed the error

**Comment by mighty-services** [comment]
Yeah, it's the GPO settings. I may have broken it additionally by trying to apply the manual steps following your tutorial :)
Anyway. It's working now. Thanks a lot for your help!

**Comment by zmb3** [comment]
Glad to hear you got it working, thanks for following up!

The `Pdutype2SaveSessionInfo` message is safe to ignore.
