### ISSUE TITLE
[Docs]Setting guide for HA using DynamoDB

### ISSUE THREAD

**Issue by ken5scal** [gravitational/teleport#2157]
**What happened**:
Documents for ver2.5, ver2.7 and example implementation have different parameters.

[In 2.5 documents](https://gravitational.com/teleport/docs/ver/2.5/admin-guide/#high-availability), there is a parameter with `table_name` to define dynamo table for storing cluster state.

[In 2.7 documents](https://gravitational.com/teleport/docs/admin-guide/#high-availability), the `table_name` disappears and new parameter `audit_events_uri` was introduced to store session events rather than cluster state.

[In aws example](https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/auth-user-data.tpl#L71), it still has `table_name`, but there is `audit_table_name` parameter which does not exist in https://gravitational.com/teleport/docs.

So I feel documents do not have all parameters regarding `high-availability` with clear definition.

**What you expected to happen**:
All 3 versions have same parameters and thorough parameters

**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Environment**:
- Teleport version (use `teleport version`): na
- Tsh version (use `tsh version`): na
- OS (e.g. from /etc/os-release): na

**Browser environment**
- Browser Version (for UI-related issues): na
- Install tools: na
- Others: na

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by benarent** [comment]
We've since updated our AWS docs https://gravitational.com/teleport/docs/aws_oss_guide/, and Terraform script.  

If anything else come up, please let us know.
