### ISSUE TITLE
Azure AD SSO Docs: Update Teleport Cloud-specific instructions

### ISSUE THREAD

**Issue by gaille-teleport** [gravitational/teleport#21570]
## Applies To
[SSH Authentication with Azure Active Directory (AD)](https://goteleport.com/docs/access-controls/sso/azuread/?scope=cloud)

## Details
For [Configure Azure AD](https://goteleport.com/docs/access-controls/sso/azuread/?scope=cloud#configure-azure-ad) Step, improve the documentation to indicate that the full **Entity ID** and **Reply URL** fields should be filled with `https://teleport.example.com:443/v1/webapi/saml/acs`

For [Create a SAML Connector](https://goteleport.com/docs/access-controls/sso/azuread/?scope=cloud#create-a-saml-connector) Step, improve the documentation to indicate that the port should be `443` for Teleport Cloud -  under `spec.acs`, `spec.audience`, and `spec.service_provider_issuer`

**Comment by ptgott** [comment]
Related: #21305

**Comment by ptgott** [comment]
See: https://github.com/gravitational/teleport/pull/33655

Closing because ports are not required within the URLs mentioned and there is not enough context in this issue for what problem this is solving.
