### ISSUE TITLE
Propagate RDP client connection errors to the client

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#21588]
Currently, if a desktop session fails because the rdp connection fails, all a user sees is

![image](https://user-images.githubusercontent.com/13578537/217947086-dbdab179-0e18-4c9d-800d-5ccaa2281588.png)

They can find more info in the logs, but ideally there would be a more descriptive error message for them in the interface. In particular, we want to intercept [`"Error during negotiation step: the server requires that the client support enhanced RDP security with CredSSP"`](https://goteleport.com/docs/desktop-access/troubleshooting/#enhanced-rdp-security-with-credssp-required) and tell the user that they likely need to disable NLA.

This can be implemented by having `connect_rdp` return a string value associated with its error in an updated return struct, similar to what we already have for [`read_rdp_output`](https://github.com/gravitational/teleport/pull/19389/files#diff-04d4ba71603f3d244046f417a7b96c4830840c73c3d18a361b83364095ee2f3cR1217-R1221).

**Comment by zmb3** [comment]
Addressed with #26356. Any error with a `UserMessage` will be propagated to the client.
