### ISSUE TITLE
Cannot join any in progress session and clicking on play on a past session give back an error : 0 not found .

### ISSUE THREAD

**Issue by aleroot** [gravitational/teleport#2165]
**What happened**:

Cannot join any in progress session and clicking on play on a past session give back an error : 0 not found .
The issue started occurring after activating the following settings on the server configuration: 

    session_recording: "proxy"  # can also be "off" and "node" (default)
    proxy_checks_host_keys: no

**What you expected to happen**:

I should be able to join current sessions and play past sessions as in the session_recording: node .

In addition I don't know why it is not possible to decide what kind of session_recording use based on the host you connect to, I have several nodes with teleport node installed and other nodes with just OpenSSH server I do need to handle both cases, but the recording type that I can set is just one for all types of servers ...

**How to reproduce it (as minimally and precisely as possible)**:

Change the teleport settings to: 

    session_recording: "proxy"  # can also be "off" and "node" (default)
    proxy_checks_host_keys: no

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.7.3 git:v2.7.3-0-g7df9595b
- Tsh version (use `tsh version`): Teleport v2.7.3 git:v2.7.3-0-g7df9595b
- OS (e.g. from /etc/os-release):

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

**Browser environment**

- Browser Version (for UI-related issues): Safari 11.1.2 (13605.3.8)

**Comment by aberoham** [comment]
Session recording is a cluster-level setting. Perhaps the docs should make this more clear? 

The recording proxy mode (aka MITM for openssh-daemon) landed in version 2.4 as part of commercially sponsored feature development work. The use/business case did not call for making session recording controls a role-level setting. I vaguely recall this being discussed in person, with the take-away being that dynamic runtime configuration of recording is quite complex, especially from the mixed security mode perspective.

Is this something you'd like to take on, or something you'd like to pay for?

Note, old design ticket: #1510 docs: #1497 end-user observations: #1520

**Comment by kontsevoy** [comment]
@aleroot @aberoham per-host session recording would make audit _extremely_ complex to reason about. However, the way the error is reported is quite annoying and the upcoming 3.0 is going to provide you with a nicer error message.
