### ISSUE TITLE
cannot signup to teleport-web if user has no logins specified

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#2167]
This is `teleport E` master

Repro:

1. create a role with no logins.
2. create a user with this role
3. try to signup

Expected: a user should be able to signin.

Actual:

![image](https://user-images.githubusercontent.com/7816406/44061905-440143c0-9f28-11e8-82e7-af790d2828e4.png)

**Comment by klizhentas** [comment]
that's by design, we don't allow to login into control panel when there are no logins available for the user.

**Comment by russjones** [comment]
I believe the root cause of this is when the default admin role is created with Enterprise on a new system, it picks the logins from open source Teleport.
