### ISSUE TITLE
Application example doesn't configure --app-public-addr

### ISSUE THREAD

**Issue by GunFood** [gravitational/teleport#21697]
## Applies To
(https://goteleport.com/docs/application-access/getting-started/)
## Details
Step 3.3 says: "Every application is assigned a public address that you can use to navigate to the application directly. **In our sample Grafana application we have provided a public address with the --app-public-addr flag**, so go to https://grafana.teleport.example.com to access the app."

Please fix the configuration example. I try to understand how to get access to an application, but don't get it running. :)

**Comment by ptgott** [comment]
@GunFood Would you mind providing a bit more detail about what was inaccurate/unclear about the `--app-public-addr` flag instructions? If you haven't been able to get your Application Service setup to work yet, I'd recommend getting help in our [Slack community](https://goteleport.com/community-slack/) or [discussion forum](https://github.com/gravitational/teleport/discussions). Thanks!

**Comment by GunFood** [comment]
It's simply not mentioned (neither in the examples nor in the descriptive text) before, but the Statement says "we have provided earlier". But _we_ didn't :)

**Comment by lsgunn-teleport** [comment]
It doesn't seem like you need to use that flag and that text has been removed from the 14.x doc.
---
Step 5/5. Access the application

There are a couple of ways to access the proxied application.

Sign in to the Teleport Web UI using your Teleport cluster address. All available applications are displayed on the Applications tab. Click Launch on the Grafana application tile to access it.

Alternatively, you can call the application directly with its name as the subdomain, for example, https://grafana.teleport.example.com or https://grafana.mytenant.teleport.sh. You are prompted to sign in if you haven't already been authenticated.

---

In my test environment, opening the URL with the app subdomain works.

**Comment by ptgott** [comment]
Closing as resolved
