### ISSUE TITLE
Change Linux installation instructions to work with Ubuntu 20.04 (correct permissions on teleport-archive-keyring.asc)

### ISSUE THREAD

**Issue by haukened** [gravitational/teleport#21698]
## Applies To
Teleport Linux installation documentation

## Details
Using the default method on Ubunt 20.04.5 LTS, the file permissions of `/usr/share/keyrings/teleport-archive-keyring.asc` doesn't always allow the keyring to be read by `apt-key` resulting in the wonderfully descriptive error message:

```
Err:6 https://apt.releases.teleport.dev/ubuntu focal InRelease
  Unknown error executing apt-key
Reading package lists... Done
W: GPG error: https://apt.releases.teleport.dev/ubuntu focal InRelease: Unknown error executing apt-key
```

Upon checking the file permissions in `/usr/share/keyrings` i found the following:

```
4 -rw------- 1 root root 3163 Feb 10 16:21 teleport-archive-keyring.asc
4 -rw-r--r-- 1 root root 2247 Nov 17 18:06 ubuntu-advantage-cc-eal.gpg
4 -rw-r--r-- 1 root root 2274 Nov 17 18:06 ubuntu-advantage-cis.gpg
4 -rw-r--r-- 1 root root 2236 Nov 17 18:06 ubuntu-advantage-esm-apps.gpg
4 -rw-r--r-- 1 root root 2264 Nov 17 18:06 ubuntu-advantage-esm-infra-trusty.gpg
4 -rw-r--r-- 1 root root 2275 Nov 17 18:06 ubuntu-advantage-fips.gpg
4 -rw-r--r-- 1 root root 2250 Nov 17 18:06 ubuntu-advantage-realtime-kernel.gpg
4 -rw-r--r-- 1 root root 2235 Nov 17 18:06 ubuntu-advantage-ros.gpg
8 -rw-r--r-- 1 root root 7399 Sep 17  2018 ubuntu-archive-keyring.gpg
8 -rw-r--r-- 1 root root 6713 Oct 27  2016 ubuntu-archive-removed-keys.gpg
8 -rw-r--r-- 1 root root 4097 Feb  6  2018 ubuntu-cloudimage-keyring.gpg
0 -rw-r--r-- 1 root root    0 Jan 17  2018 ubuntu-cloudimage-removed-keys.gpg
4 -rw-r--r-- 1 root root 1227 May 27  2010 ubuntu-master-keyring.gpg
```

## Resolution
Changing the file permissions to match (0644) resolved the issue and allowed updating securely.

```
david@tele:~$ sudo apt update
Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu focal-security InRelease
Get:5 https://apt.releases.teleport.dev/ubuntu focal InRelease [92.3 kB]
Get:6 https://apt.releases.teleport.dev/ubuntu focal/stable/v12 amd64 Packages [2231 B]
Fetched 94.6 kB in 1s (132 kB/s)    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
```

I would recommend adding the correct permissions to the installation guide in the following way:

```
sudo curl https://apt.releases.teleport.dev/gpg -o /usr/share/keyrings/teleport-archive-keyring.asc
source /etc/os-release
echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] https://apt.releases.teleport.dev/${ID?} VERSION_CODENAME?} stable/v12" | sudo tee /etc/apt/sources.list.d/teleport.list > /dev/null
++ sudo chmod 0644 /usr/share/keyrings/teleport-archive-keyring.asc
sudo apt-get update
sudo apt-get install teleport
```

**Comment by haukened** [comment]
> @haukened I am currently having the same issue, besides this workaround, was this ever resolved?

Unfortunately not, haven't even gotten a response. It's just a documentation update, so it should be relatively easy.

**Comment by ptgott** [comment]
Hi @haukened, thank you for reporting this issue. I know it's been a long time. I'm working on addressing this as part of improving our Installation page, and I'm curious about this statement:

> Using the default method on Ubunt 20.04.5 LTS, the file permissions of /usr/share/keyrings/teleport-archive-keyring.asc doesn't always allow the keyring to be read by apt-key

In the documentation, `teleport-archive-keyring.asc` is the result of redirecting the output of a `curl` command, so as far as I understand it, there shouldn't be a reason for the permissions to change after creating the file unless another process has altered the file. Would you mind providing more context on what you mean by "doesn't always allow"?

**Comment by haukened** [comment]
Hey Paul, since the file is newly created it will create with whatever the default permissions are which are set by the system umask. On Jan 11, 2024, at 15:17, Paul Gottschling ***@***.***> wrote:﻿
Hi @haukened, thank you for reporting this issue. I know it's been a long time. I'm working on addressing this as part of improving our Installation page, and I'm curious about this statement:

Using the default method on Ubunt 20.04.5 LTS, the file permissions of /usr/share/keyrings/teleport-archive-keyring.asc doesn't always allow the keyring to be read by apt-key

In the documentation, teleport-archive-keyring.asc is the result of redirecting the output of a curl command, so as far as I understand it, there shouldn't be a reason for the permissions to change after creating the file unless another process has altered the file. Would you mind providing more context on what you mean by "doesn't always allow"?

**Comment by ptgott** [comment]
Thanks for clarifying! Since running Teleport requires dealing with a lot of third-party systems, we need to be careful to limit our docs as much as possible to Teleport itself. In some cases, like launching a self-hosted Teleport cluster with our Helm chart, we include [instructions](https://goteleport.com/docs/deploy-a-cluster/helm-deployments/kubernetes-cluster/#launching-a-fresh-eks-cluster-with-eksctl) for a third-party system because a quick demo makes the guide easier to follow. In this case, though, file permissions are Linux fundamentals that are not in scope for the Teleport docs.
