### ISSUE TITLE
Clarify upgrade instructions

### ISSUE THREAD

**Issue by srikanthps** [gravitational/teleport#21718]
## Applies To
https://goteleport.com/docs/management/operations/upgrading/

## Details
What are the steps involved in "Upgrading"? This page simply says "Upgrade" auth service first and then proxy service, etc. - however, it does not clearly articulate what does the action of upgrading involve?

**Comment by ptgott** [comment]
We have a separate guide to upgrading an individual `teleport` binary: https://goteleport.com/docs/management/admin/upgrading-the-teleport-binary/

We should associate these two guides more clearly or consider merging them into a single guide (I'm guessing few users will want to upgrade a single binary without upgrading the whole cluster).

**Comment by ptgott** [comment]
Also related to #19335: the "Upgrading the Binary" page is in a separate subsection of the "Manage your Cluster" section than the "Upgrading the Cluster" page.

**Comment by ptgott** [comment]
I am going to fold this issue into #19335. Now that we have several guides on automatic upgrades in the "Manage your Cluster" section of the docs, I think there's even more urgency for organizing that section in a way that provides clarity around upgrading Teleport.
