### ISSUE TITLE
`tsh ls` becomes operation time out

### ISSUE THREAD

**Issue by ken5scal** [gravitational/teleport#2172]
**What happened**:
While the proxy can accept an inbound access to 3023, `tsh ls` returns `error: dial tcp 54.92.1.124:3023: getsockopt: operation timed out`

**What you expected to happen**:
list ssh nodes in a cluster

**How to reproduce it (as minimally and precisely as possible)**:
* tsh login --proxy=proxy.teleport.com:443 --user=ken5scal
* tsh list

**Environment**:
- Teleport version (use `teleport version`): Teleport Enterprise v2.7.3 git:v2.7.3-0-g7df9595b
- Tsh version (use `tsh version`): Teleport v2.7.3 git:v2.7.3-0-g7df9595b
- OS (e.g. from /etc/os-release): MacOSX

**Browser environment**
NA

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by klizhentas** [comment]
@ken5scal are you using AWS Dynamo DB backend by any chance?

**Comment by ken5scal** [comment]
Yeap

**Comment by klizhentas** [comment]
@ken5scal check your throttling on DynamoDB cloudwatch metrics and provision more capacity if necessary. You may be running out of capacity and DynamoDB is throttling requests.

**Comment by ken5scal** [comment]
Hm, yes, we are using DynamoDB. Let me check the metrics

**Comment by klizhentas** [comment]
@ken5scal ping did you find anything?
