### ISSUE TITLE
TLS Handshake Error Bad Certificate

### ISSUE THREAD

**Issue by iGeekuPlay** [gravitational/teleport#2179]
**What happened**:
When trying to add a node to a cluster I am getting the error TLS Handshake Error Bad Ceri
**What you expected to happen**tificate

**How to reproduce it (as minimally and precisely as possible)**:
sudo teleport start --advertise-ip=X.X.X.X -d
-AND-
sudo tctl nodes add --roles node -d
-AND-
teleport start --roles=node --token=XXXXXXXXXXXXXXXX --auth-server=X.X.X.X:3025

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.7.2 git:v2.7.2-0-ge3054bf7
- Tsh version (use `tsh version`): Teleport v2.7.2 git:v2.7.2-0-ge3054bf7
- OS (e.g. from /etc/os-release): "16.04.4 LTS (Xenial Xerus)"

**Relevant Debug Logs If Applicable**
Working: Ubuntu (proxy, auth, node) to MacBook Pro (node)
http://dpaste.com/0C45NNW

Not Working: Ubuntu (proxy, auth, node) to RaspberryPi (node)
http://dpaste.com/2MPCEXB

**Comment by kontsevoy** [comment]
@iGeekuPlay are there config files on any nodes? because your CLI arguments to `teleport start` only overwrite what's in the config, usually `/etc/teleport.yaml`. Besides, looks like it's working when another machine is used, which makes me believe there's a difference in how your boxes are set up.

In other words, there's not enough information in this ticket for us to help you.

**Comment by iGeekuPlay** [comment]
@kontsevoy I have a teleport.yaml setup on the proxy, auth, node host and here are the contents:

teleport:
    auth_servers:
        - X.X.X.X:3025
proxy_service:
    public_addr: X.X.X.X:3080

**Comment by kontsevoy** [comment]
It looks like you're using both `public_addr` (via config file) but also specifying `advertise-ip` (via CLI flag) which is something we usually recommend for nodes. I would suggest only using `public_addr` with `--insecure-no-tls` flag.

**Comment by iGeekuPlay** [comment]
@kontsevoy no matter what I have tried i still get the same error:
2018/08/22 22:49:28 http: TLS handshake error from 136.56.36.130:35696: remote error: tls: bad certificate

I am using a ubuntu host in AWS for the proxy and auth server so if i dont specify the advertise-ip then it uses the internal private IP. I need to use the advertise flag so that it will advertise on the public ip that is associated to the host.

**Comment by klizhentas** [comment]
can you check if there is a time difference on your server and AWS server, this could be the reason for TLS bad certificate warning

**Comment by iGeekuPlay** [comment]
@klizhentas 
Here is the output. They are the same.


pi@raspberrypi:~ $ timedatectl
      Local time: Wed 2018-08-22 23:04:56 UTC
  Universal time: Wed 2018-08-22 23:04:56 UTC
        RTC time: n/a
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no


ubuntu@ip-10-0-0-18:~$ timedatectl
      Local time: Wed 2018-08-22 23:04:40 UTC
  Universal time: Wed 2018-08-22 23:04:40 UTC
        RTC time: Wed 2018-08-22 23:04:40
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

**Comment by iGeekuPlay** [comment]
@klizhentas and @kontsevoy is there anything else that I should try or other details that would help troubleshoot?

**Comment by kontsevoy** [comment]
@iGeekuPlay apologies for not being responsive, we're not a big company and have limited resources to troubleshoot problems for open source users.

**Comment by kontsevoy** [comment]
I suspect this is a UX problem we can improve on. 
Related: #1941

**Comment by klizhentas** [comment]
going to punt this from Pleasanton milestone

**Comment by iGeekuPlay** [comment]
@kontsevoy and @klizhentas any update on this? Looking to take this to a higher level and future support but need to implement the design before determining if teleport is the best option.

**Comment by kz12123** [comment]
Similar issue, start ater the recent upgrade on Ubuntu 20.

Syslog is full of these messages affecting storage I/O of the whole node.

**Comment by kz12123** [comment]
I have removed tailscale and I see tailscaled TLS handshake error filling up my syslog.

**Comment by benarent** [comment]
@kz12123 are you running tailscale and teleport? Or did you just find this error message. If you're interested in connecting iot devices; or machines on different networks. You should checkout running teleport in IoT mode. https://gravitational.com/blog/iot_security_teleport/

**Comment by russjones** [comment]
This is probably related: https://github.com/gravitational/teleport/issues/2838
