### ISSUE TITLE
Connect: Using tab completion in Powershell breaks shell tabs

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#21809]
Transferred from https://github.com/gravitational/webapps.e/issues/367

Steps to reproduce:

1. Compile the Windows version from v10 branch (master is likely broken too).
2. Open a shell tab.
3. Type `Get-Co` and press tab.
4. Some kind of error message will flash on the screen.
5. Close the shell tab.
6. Open a new shell tab.

At this point, the new shell tab will never start.

Nothing interesting is happening in the logs. After breaking the shell, no new items are added to `shared.log`.

---

That message from point 4. doesn't seem to be an error:

```
Searching for available modules
Searching UNC share \\Mac\Home\Documents\WindowsPowerShell\Modules.
```

https://user-images.githubusercontent.com/27113/182587245-a2e8b9d2-7602-4ec1-90c7-5f6c461d393d.mov

**Comment by ravicious** [comment]
I cannot seem to reproduce this anymore.

**Comment by gzdunek** [comment]
I retested it on Windows 11, can't reproduce it too.
