### ISSUE TITLE
Implement GHA workflow for promoting release to Cloud

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#21863]
## Description

As part of automatic upgrades work we will introduce (tracked by https://github.com/gravitational/teleport/issues/21447) separate `stable/cloud` channels for deb/rpm repositories where we will be publishing versions compatible with Cloud, which agents running as systemd units will pull from.

We don't want to have releases published to the `stable/cloud` repo during regular promotion. Instead, let's build a Github action that can be triggered on some version file change to promote a specific release into `stable/cloud` channels. The workflow needs to live in cloud repository.

In addition to publishing packages, the workflow needs to set the current Cloud version in the S3 lock file which agents will use to fetch Cloud release information from.

## Success criteria

We have a Github Action workflow that lives in teleport.e, triggers on "version" file change (that also lives somewhere in Cloud - @jimbishopp to tell us where to put it) and:

- [x] Publishes deb and rpm packages to `stable/cloud` channels.
- [x] Sets Cloud version in S3 lock file.
- [x] Optionally sets "emergency override" flag in another S3 file.

**Comment by russjones** [comment]
@jimbishopp Can you share with @fheinecke how you want to trigger release promotion for agents?

**Comment by russjones** [comment]
@r0mant Let's make sure @gozer and @fheinecke sync up on this before working on anything.

**Comment by fheinecke** [comment]
Completed, workflow is here: https://github.com/gravitational/cloud/blob/master/.github/workflows/deploy-auto-update-changes.yml
