### ISSUE TITLE
Allow order of users displayed when using web UI

### ISSUE THREAD

**Issue by chuckyz** [gravitational/teleport#2188]
**What happened**:
Created users with `tctl users add username foo,bar,root`

A user username was created with

```
root
foo
bar
```

In the web dropdown, defaulting to root.

**What you expected to happen**:
User, after creation, to have in the web dropdown for user

```
foo
bar
root
```

Defaulting to foo

**How to reproduce it (as minimally and precisely as possible)**:
Run `tctl users add username foo,bar,root`

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.7.3 git:v2.7.3-0-g7df9595b
- Tsh version (use `tsh version`): Teleport v2.6.6 git:v2.6.6-0-g20ce9103
- OS (e.g. from /etc/os-release): CentOS 7

**Browser environment**

- Browser Version (for UI-related issues): Firefox/Chrome

**Comment by alex-kovoy** [comment]
Right now the order is not based on the order of logins assigned during `tctl users add `. The list of logins gets computed from all available to a user roles where each role has its own list of allowed/denied logins. Basically, it means that you cannot specify the default value for that combo-box. This is why we use 'root' as a default login (if present of course) to make this behavior for showing a default value somehow consistent.
