### ISSUE TITLE
Add v6 role version to our Access controls reference document 

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#21889]
## Applies To
We need to update our access controls reference documentation as we now have a new role version (v6). 
- [role-versions](https://goteleport.com/docs/access-controls/reference/#role-versions)

## Details
Add v6 reference as we do for v3, v4, and v5. We mention and use v6 on our Kubernetes access controls [docs](https://goteleport.com/docs/kubernetes-access/controls/). 

## Related Issues

None

**Comment by zmb3** [comment]
FYI @tigrato

**Comment by tigrato** [comment]
@ptgott @alexfornuto 

Do you guys have any suggestions for showing the differences between roles to the user?

Label              | `v3` Default   | `v4` and `v5` Default | `v6` Default
------------------ | -------------- | --------------- | ---------------
`node_labels`       | `[{"*": "*"}]` if the role has any logins, else `[]` | `[]`  |  `[]`
`app_labels`        | `[{"*": "*"}]` | `[]` | `[]`
`kubernetes_labels` | `[{"*": "*"}]` | `[]` | `[]`
`database_labels`   | `[{"*": "*"}]` | `[]` | `[]`
`kubernetes_resources`   | `[{"kind":"pod", "name":"*", "namespace": "*"}]` | `[{"kind":"pod", "name":"*", "namespace": "*"}]` | `[]`

in my opinion, if we add another column with `v6` and another row with `kubernetes_resources`, the table will be difficult to read and will break the table width.

A nice-to-have feature would be a description of what changed between each role's versions and why we added them.
Role `v4` introduced the RBAC representation we have today (I guess it was the change at the time).
Role `v5` introduced Moderated Sessions sections.
Role `v6` introduced `kubernetes_resources` to control access to individual pods.
