### ISSUE TITLE
Can nodes autodiscover proxies?

### ISSUE THREAD

**Issue by andrewbanchich** [gravitational/teleport#2190]
I'd like to use Teleport on a number of devices which run behind a firewall, all of which are on the same private network. I currently set them up to use a public Trusted Cluster and it is working great.

However, I hardcoded the IP address of the proxy node that all the other nodes connect to to form the cluster. I don't want to hardcode the IP in the node config files, though, since if the proxy node gets restarted it could have a different IP address.

Is there any way around this? How would you suggest I handle this?

Thank you

**Comment by aberoham** [comment]
you probably want to use DNS, i'll send you a note out-of-band to discuss

**Comment by aberoham** [comment]
Additional details via discussion w/Andrew -- use case involves deployed fleet of PoE-connected IoT devices with pre-baked firmware in a hands-off low security industrial farming setting, a few to many dozens of devices per site. Local control of layer2/LAN isn't presumed, all of these IoT devices currently get IP addresses from a site-provided existing network (some sort of basic DSL/internet gateway). One of these IoT Teleport instances is configured to be proxy+auth+node instance and all others on the same local LAN are supposed to form a cluster with it. Some sort of lightweight & simple gossip configuration mechanism seems ideal. Would serf and a simple client like https://github.com/garethr/serf-master be too complex?

**Comment by klizhentas** [comment]
so what about something simpler like DNS or floating ip with heartbeatd?

**Comment by knisbet** [comment]
It might be possible to do this with avahi, and use mDNS discovery to discover the teleport service, but this isn't something I've really tried to setup myself.
