### ISSUE TITLE
tsh config uses ssh-formatted hostname instead of literal hostname

### ISSUE THREAD

**Issue by TwiggyWan** [gravitational/teleport#21939]
Hello

Expected behavior:
Since teleport host names are case sensitive, tsh config should generate a config using  `%n` instead of `%h` in the `ProxyCommand tsh proxy ssh` line, or else names with uppercases are modified and login is rejected.

This subtlety is not mentioned in the document I followed setting up my ssh config file, [Ansible with teleport guide](https://goteleport.com/docs/server-access/guides/ansible/)

Current behavior:
My host name with uppercases is replaced with lowercase only before executing `tsh proxy ssh`.

Bug details:
- Teleport version : `v11.3.2 git: go1.19.5 Proxy version: 11.3.4`
- Recreation steps : 

1. create a host with some uppercases
2. generate tsh config file
3. add host to the config file to be pattern matched
4. try connecting to it using the config file

- Debug logs : 
```
$ tsh config > ssh.cfg
$ sed -i -E "s/(^Host.*)/\1 $(tsh ls --format names | tr  '\n' ' ')/g" teleport.cfg
$ ssh -vvv -F teleport.cfg -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 HOSTNAME-WITH-CAPS
OpenSSH_8.6p1, LibreSSL 3.3.6
debug1: Reading configuration data teleport.cfg
debug1: teleport.cfg line 4: Applying options for HOSTNAME-WITH-CAPS
debug1: teleport.cfg line 12: Applying options for HOSTNAME-WITH-CAPS
debug1: Executing proxy command: exec "/opt/homebrew/bin/tsh" proxy ssh --cluster=XXXX --proxy=XXXX twiggywan@hostname-with-caps:3022 # here, it should be in caps
ERROR: ssh: subsystem request failed


# here is the solution
$ sed -i 's/%h/%n/g' teleport.cfg

$ ssh -vvv -F teleport.cfg -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 PLS-OWK-02
[...]
debug1: Executing proxy command: exec "/opt/homebrew/bin/tsh" proxy ssh --cluster=XXXX --proxy=XXXX twiggywan@HOSTNAME-WITH-CAPS:3022
```

Cf ssh_config manual :

**Comment by TwiggyWan** [comment]
Reading `rfd/0062-tsh-proxy-template.md` i do not understand if it's up to me to tell teleport how to behave when parsing my hostnames with uppercases.

**Comment by strideynet** [comment]
Related: https://github.com/gravitational/teleport/issues/16457

**Comment by TwiggyWan** [comment]
> Potential duplicate of: #16457

agreed!
