### ISSUE TITLE
In split auth/proxy mode, rolling out auth causes 5 min downtime

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#21944]
### Expected behaviour:

I roll out auth nodes (e.g. in Kubernetes with v12 Helm chart). Auth pods get restarted. All ssh nodes that were connected to the restarted auth nodes reconnect quickly.

### Current behaviour:

No nodes connect back before it's been 5 min since the auth was removed. According to the logs, nodes don't seem to be aware they lost their tunnel to the auth.

This shows how the amount of connected servers reacts to an auth rollout in Kubernetes:
![image](https://user-images.githubusercontent.com/16366487/219479362-dfa7eaea-8fa5-43b3-960e-cee9df8933f1.png)

Note: in the above example, Kubernetes waits for the new auth to be ready before it deletes the old one (plus adds a 30 second delay). During the rollout there's always an auth server ready and ssh nodes can connect to it.

### Bug details:
- Teleport version v11 and v12
- Recreation steps:
  - run 1 proxy, 2 auth
  - connect 1 ssh node in tunnel mode
  - remove the auth the node is connected to
  - observe it takes 5 minutes for the node to reconnect to the remaining auth
- Debug logs
  ```
  {"caller":"reversetunnel/agent.go:649","component":"proxy:agent","leaseID":1,"level":"debug","message":"Received discovery request: [0a10027e-8abc-4dd7-a472-463a9d83400f 07d6450d-a34b-4ca9-b3bb-3f0ea08ec401]","target":"monster.gravitational.co:3024","timestamp":"2023-01-20T19:33:15Z","trace.fields":{"cluster":"one"}}
  {"caller":"cache/cache.go:849","component":"node:1:cache","error":"watcher is closed: keepalive ping failed to receive ACK within timeout","level":"warning","message":"Re-init the cache on error","timestamp":"2023-01-20T19:33:17Z"}
  {"caller":"cache/cache.go:853","component":"node:1:cache","level":"debug","message":"Reloading cache.","timestamp":"2023-01-20T19:33:17Z"}
  {"caller":"service/connect.go:702","component":"proc:1","level":"warning","message":"Sync rotation state cycle failed. Retrying in ~10s","pid":"1.1","timestamp":"2023-01-20T19:33:17Z"}
  {"caller":"webclient/webclient.go:129","component":null,"level":"debug","message":"Attempting GET monster.gravitational.co:3080/webapi/find","timestamp":"2023-01-20T19:33:17Z"}
  {"caller":"proxy/proxy.go:301","component":"http:proxy","level":"debug","message":"No proxy set in environment, returning direct dialer.","timestamp":"2023-01-20T19:33:17Z"}
  {"caller":"proxy/proxy.go:301","component":"http:proxy","level":"debug","message":"No proxy set in environment, returning direct dialer.","timestamp":"2023-01-20T19:33:17Z"}
  {"caller":"cache/cache.go:864","component":"node:1:cache","level":"debug","message":"Initiating new watch after waiting 2.827925117s.","timestamp":"2023-01-20T19:33:20Z"}
  {"caller":"services/watcher.go:239","component":"node:1","level":"debug","message":"Attempting to restart watch after waiting 4.212202214s.","pid":"1.1","resource-kind":"lock","timestamp":"2023-01-20T19:33:21Z"}
  {"caller":"services/watcher.go:246","component":"node:1","level":"warning","message":"Restart watch on error: watcher is closed: keepalive ping failed to receive ACK within timeout.","pid":"1.1","resource-kind":"lock","timestamp":"2023-01-20T19:33:21Z"}
  {"caller":"services/watcher.go:210","component":"node:1","level":"debug","message":"Starting watch.","pid":"1.1","resource-kind":"lock","timestamp":"2023-01-20T19:33:21Z"}
  {"caller":"inventory/inventory.go:158","component":null,"level":"warning","message":"Inventory control stream failed: inventory control stream closed: keepalive ping failed to receive ACK within timeout","timestamp":"2023-01-20T19:34:10Z"}
  {"caller":"inventory/inventory.go:137","component":null,"level":"debug","message":"Re-attempt control stream acquisition in ~2.836935101s.","timestamp":"2023-01-20T19:34:10Z"}
  {"caller":"service/supervisor.go:383","component":"proc:1","event":"TeleportDegraded","level":"debug","message":"Broadcasting event.","pid":"1.1","timestamp":"2023-01-20T19:34:10Z"}
  {"caller":"webclient/webclient.go:129","component":null,"level":"debug","message":"Attempting GET monster.gravitational.co:3080/webapi/find","timestamp":"2023-01-20T19:34:13Z"}
  {"caller":"proxy/proxy.go:301","component":"http:proxy","level":"debug","message":"No proxy set in environment, returning direct dialer.","timestamp":"2023-01-20T19:34:13Z"}
  {"caller":"srv/usermgmt.go:305","component":null,"level":"debug","message":"'teleport-service' group not found, not deleting users","timestamp":"2023-01-20T19:35:14Z"}
  ```

**Comment by zmb3** [comment]
@sclevine @hugoShaka is this still an issue or was it resolved with the cloud work?

**Comment by sclevine** [comment]
The first graph here shows time-to-first heartbeat (`teleport_connected_resources`, similar to `teleport_registered_servers`) for an auth roll on Cloud:
https://github.com/gravitational/cloud/blob/sclevine/downtime-rfd/rfd/0070-reducing-downtime-on-upgrades.md

My understanding is that the watch reconnection time is not strictly relevant for auth availability. The tunnel to the proxy (which which provides network access to the auth Kubernetes Service) remains open during an auth roll. The watch connection ends when the auth pod terminates. However, without the watch, agents will make direct requests to the auth service via the tunnel that will still succeed. When the watch is reestablished, agents will switch back to their auth cache.

**Comment by sclevine** [comment]
To be sure, I'll test this in Cloud again to ensure that there isn't an issue with auth availability separate from stream availability.

**Comment by sclevine** [comment]
Chatting with @rosstimothy, this isn't quite right: some unary grpc requests could still fail until the agent's grpc client is reconnected. We're going to discuss tomorrow.

**Comment by sclevine** [comment]
Result of chat: we believe that failed requests should be transient, and the grpc client will be able to reconnect through the tunnel if if a new request is made during the reported period (where the metric low). Will still test this after other zero-downtime work is complete.

**Comment by zmb3** [comment]
There should no longer be user-observable downtime when rolling auth. Closing.
