### ISSUE TITLE
tsh login: Remove "-teleport-internal-join" logins

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#21948]
What would you like Teleport to do?
We want to remove the `-teleport-internal-join" login from the tsh login (logins). If this cannot be done, we would like to allow explicit denying from the logins list as this is currently not possible. 
![deny-logins](https://user-images.githubusercontent.com/96448492/219488742-1e745502-80a3-4242-8092-cc138c60c1b1.png)

What problem does this solve?
After upgrading from 9.3.x -> 10.3.x the `-teleport-internal-join` logins started to show in the tsh status. This currently breaks some automation logic around retrieving a username as the login scripts rely on the `Logins` entry. Updating the script across the board is not an easy task. 

If a workaround exists, please include it.
We could update the script across the board, however, this looks more like a bug.

**Comment by zmb3** [comment]
There's no need to explicitly deny it, because the leading - character makes it an invalid Linux username.

We could probably filter it out of the tsh output though.

**Comment by zmb3** [comment]
See also #6789
