### ISSUE TITLE
Discover's "helm install" command should use enterprise image on enterprise and Cloud clusters

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#21952]
The `helm install` command we give to users in Access Manager UI should use teleport-ent image for enterprise and Cloud clusters.

**Comment by marcoandredinis** [comment]
AFAIK, there's no need to use the enterprise image for the Kube Agent.
So, even if we deliver this right now, there'll be no difference.

We'll some features enterprise only in the future. (automatic upgrades)
Is that why we want to use the Enterprise image now? To be ready when those new features land?

**Comment by r0mant** [comment]
@marcoandredinis Yeah, even though they're basically equivalent (I think) now we still recommend enterprise users to use enterprise binaries for agents and clients. There may be enterprise-specific features that require enterprise agents in future, plus we sometimes publish enterprise releases with security fixes before OSS.
