### ISSUE TITLE
teleport-cluster deployment fails in scratch mode with helm charts v12.0.2

### ISSUE THREAD

**Issue by jm-bertheas-datailor** [gravitational/teleport#21970]
Current behavior:
teleport-cluster-auth-test and teleport-cluster-proxy-test jobs failed in "scratch mode" with helm chart v12.0.2 with this error :
FAIL /etc/teleport/teleport.yaml
ERROR: failed parsing the config file: yaml: unmarshal errors:  line 1: field Error not found in type config.FileConfig

After some investigation, it's caused by 2 erroneous lines into _config.scratch.tpl files like: 
{{- required "'auth.teleportConfig' is required in scratch mode" .Values.auth.teleportConfig }}
and
{{- required "'proxy.teleportConfig' is required in scratch mode" .Values.proxy.teleportConfig }}

Bug details:
- Teleport version: 12.0.2
- Recreation steps: use scratch mode

**Comment by anthonysomerset** [comment]
I hit this error also

key information - this is the beginning of the config map data

teleport.yaml:
----
Error: 'error converting YAML to JSON: yaml: line 2: mapping values are not allowed
  in this context'
auth_service:
  authentication:

**Comment by anthonysomerset** [comment]
the issue appears to stem around the fact that `required` will render the variable if its present but this is not the desired effect and causes the template error showing in the configmap
