### ISSUE TITLE
Refresh the Okta SSO guide

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#21987]
## Applies to

docs/pages/access-controls/sso/okta.mdx

## Description

See #15601 for context.

Refresh the Okta SSO guide so it is consistent with our other SSO guides.
Ensure that:

- The guide is accurate, including our newer  commands for managing SSO
- It is possible to follow the guide as a sequence of steps
- We can extract as many partials as possible to share between this and other
  SSO guides

**Comment by alexfornuto** [comment]
Pre-assigning since I'm already using Okta.

**Comment by alexfornuto** [comment]
Re-opening since my last round of updates didn't include `tctl sso configure`.
