### ISSUE TITLE
Refresh the Azure AD SSO guide

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#21984]
## Applies to

docs/pages/access-controls/sso/azuread.mdx

## Description

See #15601 for context.

Refresh the Azure AD SSO guide so it is consistent with our other SSO guides.
Ensure that:

- The guide is accurate, including our newer `tctl` commands for managing SSO
- It is possible to follow the guide as a sequence of steps
- We can extract as many partials as possible to share between this and other
  SSO guides

**Comment by ptgott** [comment]
A lot of this was taken care of by https://github.com/gravitational/teleport/pull/25271

**Comment by alexfornuto** [comment]
When resolving, address the issue brought up in #14847:

> [SSH Azure AD Docs](https://github.com/gravitational/teleport/blob/master/docs/pages/enterprise/sso/azuread.mdx?plain=1#L64) needs to be updated to the full proxy url that would be used for Entity ID and Reply URL, which is https://mytenant.teleport.sh/v1/webapi/saml/acs
