### ISSUE TITLE
Refresh the OneLogin SSO guide

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#21983]
## Applies to

docs/pages/access-controls/sso/one-login.mdx

## Description

See #15601 for context.

Refresh the One Login guide so it is consistent with our other SSO guides.
Ensure that:

- The guide is accurate, including our newer `tctl` commands for managing SSO
- It is possible to follow the guide as a sequence of steps
- We can extract as many partials as possible to share between this and other
  SSO guides

**Comment by ptgott** [comment]
Aside from extracting partials, https://github.com/gravitational/teleport/pull/25290 has resolved this issue

**Comment by alexfornuto** [comment]
Resolved by #28444
