### ISSUE TITLE
Opening the terminal in v10 throws error

### ISSUE THREAD

**Issue by hatched** [gravitational/teleport#22001]
When trying to connect to a node with v10 this error is displayed instead:

![image](https://user-images.githubusercontent.com/532033/219735609-09298dea-5266-4a4f-b719-e20a6f3cd084.png)

**Comment by zmb3** [comment]
@hatched good to close this one?

**Comment by hatched** [comment]
Yep sorry, I guess I used the wrong string in the description to have GH auto close it :)
