### ISSUE TITLE
Teleport node should process access if no disk space left on device

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2200]
**What happened**:

```
 open /var/lib/teleport_agent/log/upload/sessions/default/....index: no space left on device
error: ssh: could not start shell
````

**What you expected to happen**:

Not sure, on one hand:

1. if recording is requested on the node, but teleport can't fulfill the recording
it should not proceed
2. on the other hand, for resillience purposes it should proceed.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by kontsevoy** [comment]
@klizhentas let's discuss in person when you have a chance.

**Comment by klizhentas** [comment]
Just had an idea about this one - in case of no disk space if available, normal sessions should be prohibited, because audit is not available. However, admin sessions should be available, so admins can recover the state.

To solve this, we can introduce `recoveryMode` option, that will limit access in this case to certain users in OSS mode and roles in the enterprise mode.

```yaml
recoveryMode:
    enabled: yes
    roles: [admin]
```

**Comment by chendo** [comment]
We ran into this issue last night when the rostered on-call engineer wasn't able to log into a node due to disk space issues and needed to escalate high enough to someone who had keys on the machine. Has there been any progress on this issue?
