### ISSUE TITLE
Create ticker systemd units for automatic upgrades

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#22002]
Packages installed via stable/cloud channel will include 2 additional systemd ticker units:

- [x] One that's ticking on schedule, pulling the latest version, and kicking off the upgrade via systemctl restart.
- [x] Another one that's updating the first ticket's schedule for the emergency override.
- [x] Dynamic reload of timer
- [x] Allow the endpoint that is checked for version information to be configurable for self-hosted customers.

**Comment by fspmarshall** [comment]
Completed of https://github.com/gravitational/teleport.e/pull/1109
