### ISSUE TITLE
proxy has no way to configure the hostname:port for token urls.

### ISSUE THREAD

**Issue by james-lawrence** [gravitational/teleport#2202]
important because the local hostname isn't always the entry point from the web.

**What happened**:
used the proxy's hostname for the url, and default port.
```
Signup token has been created and is valid for 1 hours. Share this URL with the user:
https://{hostname}.example.com:3080/web/newuser/{random}

NOTE: Make sure {hostname}.example.com:3080 points at a Teleport proxy which users can access.
```

**What you expected to happen**:
expected it to use the web_listen_addr.
```
Signup token has been created and is valid for 1 hours. Share this URL with the user:
https://teleport.example.com/web/newuser/{random}

NOTE: Make sure teleport.example.com points at a Teleport proxy which users can access.
```

**How to reproduce it (as minimally and precisely as possible)**:
`tctl --config=/etc/teleport/auth.yml users add soandso@example.com dev`

**Environment**:
- tctl version
Teleport v2.6.1 git:v2.6.1-0-g63d4968f
- ubuntu 17.04
```
teleport:
  data_dir: /var/lib/teleport/proxy
  pid_file: /run/teleport-proxy/teleport.pid
  auth_token: {snip}
  connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stderr
    severity: INFO
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: teleport.example.com:443
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: {snip}
  https_cert_file: {snip}
```

**Comment by aberoham** [comment]
Hi James, similar concerns have been noted prior, such as #845 & #1709. Could you try using the `public_addr` setting under proxy_service and let us know if that makes for a better displayed entry point in the signup token UX? 

An example config in the [latest Teleport docs](https://gravitational.com/teleport/docs/admin-guide/) mentions the setting  --
```
proxy_service:
    # The DNS name the proxy server is accessible by cluster users. Defaults to 
    # the proxy's hostname if not specified. It is highly recommended to set it
    # to something meaningful when running multiple proxies behind a load balancer.
    public_addr: teleport-proxy.example.com:3080
```

**Comment by james-lawrence** [comment]
gah how'd I miss that in the docs and code, will try it out.
