### ISSUE TITLE
[Bug]: Redis `command info` hangs

### ISSUE THREAD

**Issue by dm3ch** [gravitational/teleport#22078]
**Steps to reproduce** (How to reproduce what you found step by step)
- Create AWS ElastiCache redis instance
- Add redis instance to teleport
- Run the fillowing commands:
```
❯ tsh db connect <db_name>
localhost:55573> auth <password>
"OK"
localhost:55573> command info ai.info
```

Current behavior:
The sessions just hangs forever. Client doesn't receives any response

Expected behavior:
I expect same behavior as when I connects directly:
```
/ # redis-cli -h <db_host> --tls
<db_host>:6379> auth <db_password>
OK
<db_host>:6379> command info ai.info
1) (nil)
```

So with a direct connection (without teleport) you immediately receives a `1) (nil)` response.

Bug details:
- Teleport version
11.1.3
- Recreation steps
Described in the begining of the issues
- Debug logs
I'm not sure how to recieve debug logs from my cluster.

P.S.
This issue blocks me from connecting RedisInsight to my redis instance, cause redis insight is using `command info ai.info` during connection sequence. So redisinsight is getting connection timeout error.

P.S.S.
I assume that a bug lives somewhere in https://github.com/gravitational/teleport/blob/master/lib/srv/db/redis/protocol/resp2.go#L41  
I think so, because the response that is dropped by teleport is a `(nil)` but not regular one but a `1) (nil)`, so I assume that it's a unhandled cornercase.

**Comment by maxUo** [comment]
Bump ^

**Comment by JackBrannan** [comment]
Bump ^

**Comment by Hex4dec1mal** [comment]
bump ((

**Comment by 1inch-bulatgumerov** [comment]
Any updates?
