### ISSUE TITLE
Add links to Docker images

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2212]
## Description 

Starting teleport 2.7.0-alpha.5 we now have official releases of docker images paired with every binary release.

They are all publicly available and located here:

quay.io/gravitational/teleport:2.7.0-alpha.5
quay.io/gravitational/teleport-ent:2.7.0-alpha.5

Will be cool if our downloads page referenced them somehow.

## Ev's

I will update README and QuickStart with this. They both have "Installing" section which is perfect for this.

**Comment by kontsevoy** [comment]
Let's punt this for now. Our images published on quay are sub-optimal, they contain (even though they are NOT unused) components with unpatched CVE's, so we shouldn't advocate their use.

**Comment by kontsevoy** [comment]
Related: #2135

**Comment by benarent** [comment]
![image](https://user-images.githubusercontent.com/559288/58900406-f9385f80-86b3-11e9-9f84-69e1c2b5b658.png)

I had another look into this. Quay does recommend that five are fixable https://quay.io/repository/gravitational/teleport/manifest/sha256:43692b19070e71585629a9022009d3539a313e340826c2fb3cc65aab300c9999?tab=vulnerabilities&fixable=true but from 3.1.15 we don't have any more *High* issues.
