### ISSUE TITLE
[Discover] Auto setup database agent

### ISSUE THREAD

**Issue by ryanclark** [gravitational/teleport#22132]
Using the [AWS Integration](https://github.com/gravitational/teleport/issues/22131), we can allow for users to select an EC2 instance and have Teleport automatically set itself up on that machine, with the correct configuration for the selected resources.

Design - https://www.figma.com/file/uLevdNsEnIvvLDSZ9sQqXM/Teleport-Discover-Access?node-id=182%3A12030&t=4MTVzi4hUj6RCotl-0

**Comment by marcoandredinis** [comment]
Closing because it was done already.
We ended up using Amazon ECS to deploy a Teleport Database Service.
