### ISSUE TITLE
Docs for building Teleport will build alpha/beta versions

### ISSUE THREAD

**Issue by andrewbanchich** [gravitational/teleport#2220]
I followed the instructions for doing a custom build of Teleport, then installed the binaries on a bunch of devices. After doing so I noticed that the devices were running the 3.0-alpha. I looked into why that was and it looks like doing a plain `git clone` will pull the master branch which will cause `make full` to build the latest release, regardless of whether it is stable or not.

**Comment by klizhentas** [comment]
yes, that's by design. If you want to build a tag, just check the tag and run make release.
