### ISSUE TITLE
Show Example of MachineID Managing Plugin Credentials

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#22202]
## Applies To
https://goteleport.com/docs/access-controls/access-request-plugins/

## Details
Using MachineID to generate the access plugin credentials allows for not having to generate long certs as an example.  Currently the documentation shows using `tctl auth sign` to generate a long lived cert.

**Comment by zmb3** [comment]
See also https://github.com/gravitational/teleport-plugins/issues/641

We're unlikely to address this since we're currently working on hosted plugins which will remove the need to manage plugin credentials at all.
