### ISSUE TITLE
Add Device Trust Support for Windows 

### ISSUE THREAD

**Issue by campanamarco** [gravitational/teleport#22205]
What would you like Teleport to do?
_Add support for registering trusted windows devices.  Similar support for MacOS Devices noted here: https://goteleport.com/docs/access-controls/guides/device-trust/ _

What problem does this solve?
_A lot of current and prospective Teleport Users still use Windows laptops as their main devices.  With `tsh` being supported on powershell through Teleport, adding device trust for Windows, would be the next logical step to continue to add value in regards to our business impact on establishing zero trust security_

If a workaround exists, please include it.

**Comment by zmb3** [comment]
This is already being tracked at https://github.com/gravitational/teleport.e/issues/829
