### ISSUE TITLE
Add instructions for building a custom Access Request plugin

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#22227]
## Applies To

`docs/pages/api/*`

## Details
See #19716

Building Access Request plugins is a popular use case for our API. Let's add a how-to guide that walks a user through how to write their own Access Request plugin, sending Access Request notifications to a generic HTTP REST/JSON API endpoint.

## Related Issues
- #19716

**Comment by hugoShaka** [comment]
I don't know how much we want to give a minimal example project or a full-featured plugin, but we started to deduplicate the logic of access request plugins. The discord and slack plugin are using [the same common base.](https://github.com/gravitational/teleport-plugins/tree/master/access/common)

This common base was not initially designed for quick external reuse. However some/most parts should be adaptable with little effort and provide useful abstractions to build a teleport plugin.
