### ISSUE TITLE
Listing apps via the UI does not handle unsupported apps correctly

### ISSUE THREAD

**Issue by rudream** [gravitational/teleport#22239]
### Context

There are certain types of apps that can't be launched from the Web UI (Cloud apps and TCP apps). Since they aren't supported by the UI, we prune them from the response when the UI tries to list apps. 

With the current implementation, we are pruning from a list of apps after they have already been filtered and paginated. This causes issues with how many apps are returned per page and the `totalCount`.

This pruning should be done prior to filtering so that this bug doesn't occur. Another approach is to remove the pruning of unsupported apps entirely and the Web UI should list all Apps and simply disable the `Launch` button for unsupported ones.

#### Example of when this issue can occur:
A user has 10 supported apps and 10 unsupported apps in their cluster and these apps are evenly distributed (in terms of sorting). They make a request to list the first page of apps with a `pageSize` of 8.

If we did no pruning of unsupported apps, they would expect to receive 8 apps, 4 of which would be supported apps and the other 4 being unsupported ones.

With the current implementation, they would receive only 4 apps on that page. This is because the filtering and pagination would have filtered the entire list into a list of 8, and then the unsupported apps would be pruned from that list afterwards, leaving only the 4 supported apps.

**Comment by zmb3** [comment]
@kimlisa fixed this one, right?
