### ISSUE TITLE
Add network_restrictions to the terraform provider

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#22261]
What would you like Teleport to do?
Add the "network_restrictions" resource to the Terraform provider [options](https://goteleport.com/docs/management/guides/terraform-provider/#create-the-terraform-user). 
***Note: `network_restrictions` - restrictions for SSH sessions
![Screenshot 2023-02-24 at 2 46 12 PM](https://user-images.githubusercontent.com/96448492/221288574-44a6b895-3b91-433b-9208-c3507722d57d.png)

What problem does this solve?
Adding this resource will help facilitate the use of the "network_restrictions" resource as the configuration is managed with terraform. Thus, if the resource is missing we cannot use this functionality at all. 

If a workaround exists, please include it.
None.

**Comment by zmb3** [comment]
@Erick-Reyes it's not clear to me exactly what you're looking for here.

The screenshot and link you shared is an example role, users are free to add whatever additional permissions they'd like to this role.

Are you just looking for us to update the documentation to include this permission in the example? If so, this seems like it should be tagged `documentation`, not `feature-request`.

**Comment by Erick-Reyes** [comment]
@zmb3 Seems we don't have the `network_restrictions` resource in our terraform provider code. Could we add this resource to the terraform provider? Not a documentation issue.

**Comment by russjones** [comment]
We're going to deprecate this feature in the future so no point in adding it to the Terraform Provider.
