### ISSUE TITLE
[v.12.x] /docs/pages/architecture/nodes.mdx

### ISSUE THREAD

**Issue by karthikeyamuppalla-at** [gravitational/teleport#22260]
## Applies To
https://goteleport.com/docs/architecture/nodes/?scope=enterprise

## Details
Just like how https://goteleport.com/docs/architecture/tls-routing/?scope=enterprise has a "Version Warning" at the top of the page, Is it possible to specify from which version onwards this https://goteleport.com/docs/architecture/nodes/?scope=enterprise is supported?

**Comment by zmb3** [comment]
SSH nodes have been supported for several years. These warnings are generally added for new features that aren't available in all supported versions of Teleport.
