### ISSUE TITLE
Unable to deploy teleport-cluster v12

### ISSUE THREAD

**Issue by 6ixfalls** [gravitational/teleport#22285]
Expected behavior:
The cluster is healthy and deployed, and accessible.

Current behavior:
Upgrade/Install hangs on wait-auth-update container, which seems to never resolve.
`lookup teleport-cluster-auth-v11.teleport-cluster.svc.cluster.local: No address associated with hostname`
Seems to occur even when installing a new cluster, but doesn't seem to error on minikube on my local machine for some reason.

Bug details:
- Teleport version v11.3.4 > v12.0.2
- Cluster details k3s running Rancher. Deployment fails with both Helm and Rancher UI
- Recreation steps
`helm install teleport-cluster teleport/teleport-cluster --create-namespace --namespace=teleport-cluster --set clusterName=teleport-cluster.teleport-cluster.svc.cluster.local --set podSecurityPolicy.enabled=false --version 12.0.2` (or 11.3.4, then helm upgrade --install...)

`lookup teleport-cluster-auth-v11.teleport-cluster.svc.cluster.local: No address associated with hostname` is repeated over and over again in logs.

**Comment by jctrouble** [comment]
I think the wait logic introduced in #19277 might need some expanding

**Comment by jctrouble** [comment]
(I am hitting this too on a fresh helm install on a bare-metal cluster)

**Comment by TeleLos** [comment]
I see similar behavior happening with the minikube example. Executing the following steps. 

CLUSTER_NAME="teleport-cluster.teleport-cluster.svc.cluster.local"
helm install teleport-cluster teleport/teleport-cluster \
  --create-namespace \
  --namespace=teleport-cluster \
  --set clusterName=${CLUSTER_NAME?} \
  --version 12.2.1

Error message seen with with **_kubectl logs teleport-kube-agent-0 -n teleport-cluster_**

2023-04-11T18:59:01Z ERRO [PROC:1]    Instance failed to establish connection to cluster: Failed to connect to Proxy Server through tunnel: connection error: desc = "transport: Error while dialing failed to dial: dial tcp: lookup teleport-cluster.teleport-cluster.svc.cluster.local: no such host". pid:7.1 service/connect.go:119
2023-04-11T18:59:03Z INFO [PROC:1]    Joining the cluster with a secure token. pid:7.1 service/connect.go:585
2023-04-11T18:59:03Z INFO [AUTH]      Attempting registration via proxy server. auth/register.go:267

**Comment by darox** [comment]
I have no idea why it blocks the whole deployment, but you can overcome it by just removing the init container:
` kubectl patch deployment teleport-cluster-proxy -n teleport  --type json -p '[{"op": "remove", "path": "/spec/template/spec/initContainers"}]'`

**Comment by sms-astanley** [comment]
Ran in to the same problem as noted here - https://github.com/gravitational/teleport/discussions/29180#discussioncomment-7076334

**Comment by zmb3** [comment]
Should be fixed with $37476
