### ISSUE TITLE
Configure the recording feature (rotation, max size, etc)

### ISSUE THREAD

**Issue by thalesfsp** [gravitational/teleport#2233]
**What happened**:

I would like to know where I can configure the recording feature (rotation, max size, etc)

**What you expected to happen**:

I expected to set these feature, or to find documentation around that.

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.7.4 git:v2.7.4-0-g2fff1056
- Tsh version (use `tsh version`): Teleport v2.7.4 git:v2.7.4-0-g2fff1056
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS (Bionic Beaver)

**Browser environment**

- Browser Version (for UI-related issues): Firefox 62.0 (64-bit)

**Comment by aberoham** [comment]
Hi Thales, Teleport supports multiple different persistence & logging backends (local filesystem, Dynamo/S3, etcd, etc) and each has its own unique requirements & tooling when it comes to deployment, backup, rotation, archival, sizing, etc. Part of what makes Teleport special is that it follows the unix philosophy of doing one thing and doing it really well (eg, enforcement of certificate-based identity at an encrypted protocol level). So what precisely you could or should do with the audit log or individual session recordings captured by Teleport is a highly personal or environment-specific concern that the Teleport feature set does not get into. (With regard to "recording feature" -- Teleport does have some options, such as configuration flag to do recording at all, to do recording at the teleport-node level or to run an entire cluster in "Recording Proxy" mode aka at a transparent MITM) But Teleport's feature set doesn't get into file or database management. With regard to max size, there may be ways to simply limit the length/time of sessions, which could indirectly approximate "size." Does that help?

**Comment by kontsevoy** [comment]
@aberoham agreed.

**Comment by Mustafa-Azzam** [comment]
Hi @aberoham 
I understand what you said, but the thing I need to know is: 
Where can I add these configurations? in which file/directory?
