### ISSUE TITLE
access denied to every other user except vagrant

### ISSUE THREAD

**Issue by npsoni88** [gravitational/teleport#2234]
**What happened**:
I setup 3 vagrant machines (1 server and 2 nodes). Everything works fine for "vagrant" user which is a user present by default on all 3 machines. But other users can't login neither with webUI nor terminal. A simple "access denied" message appears.

**What you expected to happen**:
To be able to login

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version : latest
- Ubuntu Xenial

**Comment by npsoni88** [comment]
Update -
Aww, so the user actually has to be present on the server/nodes who would be impersonated by the teleport-users logging in. So this isn't actually a user management tool but more like a tool for alternative session management?

**Comment by aberoham** [comment]
The way to think about Teleport from a systems perspective is that it enforces certificate(key)-based identity at an SSH protocol level while giving you forensic-level visibility into those encrypted SSH sessions. What happens on the far side of SSH tunnel, eg the local unix shell, is outside the scope of what Teleport does. We do, however, have an integration with Linux-pam, which should allow you to trigger unix account-local things such as automatic instantiation of local user accounts upon successful connection of Teleport's end-to-end identity-enforced & logged SSH tunnel. Does that help?

We may have example pam.d recipes (to auto-create local POSIX users) already in the main repo, or would be happy to accept a PR if you have examples you'd like to contribute.
