### ISSUE TITLE
Remove the need to pre-distribute auth API certificates

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2237]
## Description

Currently to avoid MITM-attack when adding new nodes to a cluster, a user must export the cluster's auth API HTTPS certificate via `tctl auth export --type=tls` and save it into `/var/lib/teleport/ca.cert` on every node, see [this](https://gravitational.com/teleport/docs/admin-guide/#untrusted-auth-servers)

## Problem

It's annoying and inconvenient.

## Proposal

@klizhentas has developed a plan to avoid doing this. It's based on changing the way how invitation tokens are generated:

* The auth server computes a secure hash of it's private key and uses it as a prefix for an invitation token.
* The new node, prior to offering its join token, requests the hash from the auth server.
* Node decides to trust the auth server only if the hash matches what's in the token

## Questions

How would this work with [static tokens](https://gravitational.com/teleport/docs/admin-guide/#static-tokens)?

**Comment by russjones** [comment]
## Proposal

When a node joins a cluster, both sides need to verify the identity of the other before a successful join can occur. The cluster needs to ensure that the node joining was issued a token that itself generated and the node connecting needs to verify the Auth Server it is connecting to is the one that issued the token.

The current approach is for nodes to look for a file on disk at `/var/lib/teleport/ca.cert` which contains the CA certificate and use this to verify the certificate presented by the Auth Server. However as mentioned in #2237 this can be inconvenient.

This proposal adds a more user friendly way for nodes to verify the identity of the Auth Server by using CA pins. Similar to the approach [used by Kubernetes](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#token-based-discovery-with-ca-pinning), when an Auth Server issues a join token, it also takes the SHA256 hash of the CA Subject Public Key Info (SPKI) of it's CA. This is sent along with the token and used by the node to join the cluster.

## Implementation

### Auth and Proxy Changes

The first change needs to be made on the Auth Server. When a Teleport client requests a invitation token, the SPKI hash needs to be returned along with the token. Generating of the SPKI hash is outlined in [RFC 7469](https://tools.ietf.org/html/rfc7469).

The second change needs to occur on the Proxy Server. The `/ping` endpoint should contain the CA certificate of the cluster. This will be used by the node to verify the identity of the cluster.

### Node Changes

When attempting to join a cluster, a Teleport node should try to use a CA certificate or CA pin to validate the identity of the Auth Server.

Using the CA certificate to validate the identity is already supported, the only change required is provide a configurable path the the CA certificate.

Using CA pins, when attempting to join a cluster, the client should first fetch the cluster CA from the `/ping` endpoint and check that the CA pin provided matches the value calculated from the cluster CA fetched from `/ping`.

If the above is successful, the node should create a `*tls.Config` which uses the cluster CA fetched from the `/ping` endpoint to validate the certificate presented by the Auth Server.

If both checks hold then continue to connect to the Auth Server and present the node invitation token.

## Examples: Creating a join token.

```
$ tctl nodes add
The invite token: 1ac590d36493acdaa2387bc1c492db1a
This token will expire in 30 minutes

Run this on the new node to join the cluster:

$ teleport start \
   --roles=node \
   --token=1ac590d36493acdaa2387bc1c492db1a \
   --ca-pin=sha256:68517d9f8591d29d0b1fdbd157389db3ef92ea101c4867d45b8719049a6ac8f5 \
   --auth-server=10.12.0.6:3025

Please note:

  - This invitation token will expire in 30 minutes.
  - 10.12.0.6:3025 must be reachable from the new node.
```

## Examples: Joining a cluster.

When joining a cluster, the following fields related to mutual authentication are supported:

* `--token` (CLI) or `auth_token` (Config): Used by the cluster to verify the node.
* `--ca-path` (CLI) or `ca_path` (Config): Used by the node to verify the cluster using an exported CA certificate.
* `--ca-pin` (CLI) or `ca_pin` (Config): Used by the node to verify the cluster using a CA pin.
* `--insecure-skip-ca-verification` (CLI) or `insecure_skip_ca_verification` (Config):  Used by the node to by-pass checking the identity of the cluster.

### Examples:

```
$ teleport start \
   --roles=node \
   --token=1ac590d36493acdaa2387bc1c492db1a \
   --ca-pin=sha256:68517d9f8591d29d0b1fdbd157389db3ef92ea101c4867d45b8719049a6ac8f5 \
   --auth-server=10.12.0.6:3025
```

```
$ teleport start \
   --roles=node \
   --token=1ac590d36493acdaa2387bc1c492db1a \
   --ca-path=/var/lib/teleport/ca.cert  \
   --auth-server=10.12.0.6:3025
```

```
$ teleport start \
   --roles=node \
   --token=1ac590d36493acdaa2387bc1c492db1a \
   --insecure-skip-ca-verification \
   --auth-server=10.12.0.6:3025
```

```
teleport:
  nodename: "node"

  auth_token: "1ac590d36493acdaa2387bc1c492db1a"
  ca_pin: "sha256:68517d9f8591d29d0b1fdbd157389db3ef92ea101c4867d45b8719049a6ac8f5"

  auth_servers:
    - "10.12.0.6:3025"
```

```
teleport:
  nodename: "node"

  auth_token: "1ac590d36493acdaa2387bc1c492db1a"
  ca_path: "/var/lib/teleport/ca.cert"

  auth_servers:
    - "10.12.0.6:3025"
```

```
teleport:
  nodename: "node"

  auth_token: "1ac590d36493acdaa2387bc1c492db1a"
  insecure_skip_ca_verification: true

  auth_servers:
    - "10.12.0.6:3025"
```

**Comment by russjones** [comment]
@kontsevoy

**Comment by klizhentas** [comment]
design looks good to me

**Comment by aberoham** [comment]
Will CA pinning work with trusted cluster join tokens same as normal node join tokens?

**Comment by klizhentas** [comment]
cluster join tokens connect via web API, therefore they rely on "web" X509, not Auth internal one
