### ISSUE TITLE
Emit protected resource count metric (Cloud only)

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#22435]
Emit a new metric to ClickHouse that gets sent along with resource heartbeats. We'll use this to count unique resource connected over a period of time (probably monthly).

For example, if you have a single agent proxying 4 databases, that protected resource count should be 4.

Document any edge cases that will not be covered by this that we can handle in Phase 2. For example, how would we handle resource that you `tctl create` (for example, static nodes for Server or Desktop Access). You don't need to implement this for now.

**Comment by klizhentas** [comment]
For phase 1 emitting just on heartbeat is fine. Let's just send a unique set with each heartbeat that includes timestamp, unique hash of server id, resource type. 

To support agentless mode in phase 2 we can emit similar event when discovered server will be created:

https://github.com/gravitational/teleport/pull/22033
