### ISSUE TITLE
Machine ID: FIPS support

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#22448]
In FIPS mode it should behave just like any other FIPS-mode component, use proper IAM FIPS mode endpoints, use FIPS-approved crypto library and algorithms.

**Comment by strideynet** [comment]
**Some rough thoughts**

For invocation, mimic the same flag used by `teleport` e.g `tbot start --fips`.

Fips flag should:
- Ensure compiled with boringcrypto
- Ensure generated keys use 2048-bit RSA
- When IAM joining, use FIPS compliant STS endpoints

**Comment by strideynet** [comment]
https://github.com/gravitational/teleport/issues/15328
