### ISSUE TITLE
IAM joining with FIPS Auth and non-FIPS client

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#22444]
### Expected behavior:
Non-FIPS clients (Teleport nodes without FIPS binaries or started without `--fips`, all MachineID bots) should be able to join a Teleport cluster where the Auth server is running in FIPS mode using the IAM join method.

### Current behavior:

Auth servers running in FIPS mode enforce that all RegisterUsingIAMMethod calls must use a FIPS endpoint for the AWS STS service, and currently the endpoint used is selected by the client.

All non-FIPS clients will be blocked from joining the cluster, receiving an AccessDenied error including `node selected non-FIPS STS endpoint (sts.<region>.amazonaws.com) for the IAM join method`.

### Bug details:
Teleport version: v12.0.0+, previous versions will only have a warning in the auth server logs
Recreation steps: v12+ auth server started with `--fips`, any node started without `--fips` joining with the IAM method

### Possible Solutions:
1. All clients could try to use a FIPS endpoint by default, possibly falling back to a non-FIPS endpoint on error. This should be possible except for nodes running in the AWS China partition which has no FIPS endpoint and no way to join a FIPS cluster with the IAM method anyway.
2. All clients could select an endpoint using the current logic and fall back to a FIPS endpoint on error.
3. Update the `RegisterUsingIAMMethod` protocol to have the Auth server select which STS endpoint should be used, instead of having the client select. This could also benefit any clients in new regions unknown to the auth server which are currently blocked from joining, Auth could tell them to use a known endpoint. (Possibly have the auth server generate the entire `sts:GetCallerIdentity` request and just have the node sign it).

**Comment by nklaassen** [comment]
CC @strideynet

**Comment by klizhentas** [comment]
Hey Team, non-FIPS teleport clients should not be able to join FIPS cluster. FIPS mode requires strict usage of crypto libraries and algorithms.

For Teleport Machine ID `tbot` to work in FIPS mode it should be compiled in FIPS mode.

**Comment by klizhentas** [comment]
closed in favor of https://github.com/gravitational/teleport/issues/22448
