### ISSUE TITLE
Automatic Upgrades Documentation

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#22453]
Teleport documentation should be updated to reflect the following.

* When using the `Cloud` selector, all references to download links should switch to downloads from `cloud/stable`.
* Create a dedicated page within documentation that outlines how automatic upgrades work at a high level.
  * It should also contain a "Danger Zone" block that explain how you can manually "opt-out" of automatic upgrades and what the responsibilities for the customer are.
  * It should also contain a a block that explains how to manually recover from a bad release. For example, if 12.2.2 is broken and the customer wants to manually roll back to 12.2.1, what should they do?
  * It should also contain a block that outlines how self-hosted customers can utilize automatic upgrades. Outline that they have to setup a HTTPS server with a single endpoint `/version` and how they can configure systemd unit and Kubernetes Operator to point to their own version endpoint instead of the Cloud one. 

In addition, work with @jimbishopp and @evanfreed to create a runbook on what Cloud should do if a release is broken. For example, let's say 12.2.2 is broken what do we do? The answer is update `/version` to point to `12.2.1` and then work to get 12.2.3 out because we don't do rollbacks. Explain why we don't do rollbacks.

**Comment by zmb3** [comment]
@fspmarshall is this complete now? I see https://goteleport.com/docs/management/operations/self-hosted-automatic-agent-updates/?scope=enterprise is live.
