### ISSUE TITLE
Track Automatic Upgrades Usage

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#22451]
Success criteria

* How many agents does a tenant have with automatic upgrades enabled
* How many tenants have where all agents are using automatic upgrades

Essentially, we want to know how what adoption of automatic upgrades looks like. This is primarily to track if adoption is low. If it is, we need to figure out why and fix it.

@fspmarshall Talk to me before working on this. We can push this to after we release Teleport 13 and we may be able to gather this information from logs.

**Comment by fspmarshall** [comment]
This should be addressed as of https://github.com/gravitational/teleport/pull/28951.  The following new prometheus metrics were added:

  - `teleport_enrolled_in_upgrades`: total number of instances enrolled in upgrades.
  - `teleport_ upgrader_counts`: instances enrolled per upgrader.
  - `teleport_total_instances`: total number of instances (for easy comparison).
  
  Additionally, the upgrader itself was added to the prehod `AgentMetadata` event.  Cloud folks have been notified about adding these to their internal dashboards, and (I think) the changes should be landing in the auth version being rolled out this week, so we should start getting some numbers in shortly.
