### ISSUE TITLE
Process Redis Clusters `MOVED` message

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#22457]
When Redis Cluster moves the endpoint, it sends `MOVED` message back to teleport. Teleport does not update it's internal state and fails to process the event. This leads to disruption for Elasticache redis use-cases and blocks deployment for some customers.

If you use `tsh db connect` it's straight up ignored, if you use `tsh proxy db` it eventually times out and fails

This happens specifically with Redis Clusters. This problem does not exist with standalone Redis.

**Comment by klizhentas** [comment]
Customer would be OK if we fix this within 3-6 months from Feb 28 2023

**Comment by greedy52** [comment]
`MOVED` should be handled automatically by redis-driver, when the redis databse is setup in cluster mode:
```yaml
databases:
  - name: "redis-cluster"
    uri: "rediss://redis.example.com:6379?mode=cluster"
```
https://goteleport.com/docs/database-access/guides/redis-cluster/

Auto-discovered ElastiCache/MemoryDB clusters should have the flag set by default.

I would love to investigate more in set ups where `MOVED` is not handled when above is set.
