### ISSUE TITLE
Give infrastructure-as-code approaches to Teleport more prominence in the docs

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#22483]
## Applies To

Determining the scope of the change is part of this project.

## Details

If people visit the docs, they don't know (until they visit pages buried in the "Manage your Cluster" section) that the Terraform provider or Operator exist. The impression is that you can only configure Teleport using `tctl` and the Web UI.

We should make sure that the docs reflect all available techniques for applying configuration resources while putting infrastructure-as-code approaches in the foreground. The Terraform provider and Kubernetes Operator should be first-class citizens for deploying configuration resources. In general, we should direct users toward IAC approaches to installing Teleport and applying configuration resources.

Further, rather than using `kubectl exec` to create configuration resources in our Helm guides, we should consider including instructions to use the Kubernetes Operator.

**Since this issue has a broad scope, we should create a table of sub-issues/PRs before we start addressing it.**

_This issue is based on a [previous issue](https://github.com/gravitational/teleport/issues/19974), refining its scope._

**Comment by TravisGary** [comment]
This is great.  Any intention of getting on registry.terraform.io?

**Comment by ptgott** [comment]
@TravisGary Not sure! This issue is more for making it easier to learn how to interact with Teleport using IAC/GitOps tools

**Comment by ptgott** [comment]
## Planned solutions:

|Task|Issue|PR|
|---|---|---|
|Make the Terraform and Operator guides more prominent within the "Manage your Cluster" section (e.g., put them in `docs/management/configure-your-cluster`) or something similar, not to increase pageviews necessarily but to tidy up the section.|||
|Add a guide for using the Teleport Terraform provider with Spacelift to that section (assuming an already running Teleport cluster/Teleport Cloud).|||
|Create a plan/GitHub issue to add tabs for the Operator/Terraform where we mention `tctl` in how-to guides. There are 117 pages in docs/pages that include `$ tctl`, so we can space this out over a few months|||

CC @klizhentas @xinding33 

_I originally tried writing a Terraform module and accompanying learning track to deploy the `teleport-cluster` Helm chart along with Teleport configuration resources, but this turned out to be too complex for the purpose of a Getting Started guide._
