### ISSUE TITLE
tsh kube credentials should not open browser when invoked from a kube gui

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#22494]
### Expected behavior:

When using kube access in conjunction with a tool like [lens](https://k8slens.dev/), the GUI will continually attempt to connect to the cluster, even if the user locks the screen. When the tsh session expires, it should not try to pop open the browser, but instead simply fail. When using a Teleport local user, this is the effective behavior. The tsh kube credential command simply fails because the current credential isn't valid, and it can't prompt the user for their password.

### Current behavior:

When using a SAML or OIDC connector, lens can invoke tsh kube credentials dozens of times, creating dozenos of browser tabs overnight.

### Bug details:
- Teleport version - n/a
- Recreation steps - open lens and connect to a cluster via teleport kube access. let the tsh session expire, and leave lens open.
- Debug logs - n/a

![image (3)](https://user-images.githubusercontent.com/37278/222230857-6267de97-0d8c-45e2-b604-a305cd705f2d.png)

**Comment by stevenGravy** [comment]
same as https://github.com/gravitational/teleport/issues/9450
