### ISSUE TITLE
Stop publishing teleport images to quay.io/gravitational

### ISSUE THREAD

**Issue by wadells** [gravitational/teleport#22506]
## What would you like Teleport to do?

As part of https://github.com/gravitational/teleport/issues/5225, we started publishing all of our sanctioned OCI images to AWS ECR, in addition to their preivous quay home.  Similarly, we updated our documentation to refer all users to the new ECR location in Teleport 10 (see https://github.com/gravitational/teleport/pull/15382 and ports).  We now want to stop publishing new images to `quay.io/graviatational`, and tear out the related release infrastructure.

## What problem does this solve?

This will reduce the maintenace burden of publishing to a second place, and additionally set us up to terminate our quay account for good.

## Metadata
Tracked as a mitigation item for [BR-03](https://app.drata.com/risk-management/edit/BR-03), [BR-17](https://app.drata.com/risk-management/edit/BR-17), [BR-18](https://app.drata.com/risk-management/edit/BR-18) in Teleport's Risk Register.

**Comment by wadells** [comment]
Timeline wise, I propose we tie this to @tcsc #19045 work, as he is already planning to change the sanctioned repos.

I'll keep an eye on how many users we have hitting our quay repos, and plan a slow deprecation probably a year after we stop publishing new images to them.  We'll do a couple brownouts before turning the repo off for good to catch any stragglers.

cc @r0mant @tcsc

**Comment by r0mant** [comment]
@wadells FYI we just sent an announcement to our customers last week saying that we'll stop publishing to quay.io when Teleport 13 comes out. It was deprecated in Teleport 11.

**Comment by wadells** [comment]
> @wadells FYI we just sent an announcement to our customers last week saying that we'll stop publishing to quay.io when Teleport 13 comes out. It was deprecated in Teleport 11.

Sounds good -- I filed this because I needed a specific issue to track for some compliance work.  Let me know if there is a better issue, and we can close this as a duplicate.

**Comment by zmb3** [comment]
@wadells @r0mant I think we're good to close this now, yeah?

**Comment by wadells** [comment]
> @wadells @r0mant I think we're good to close this now, yeah?

Yeah, we still have 10, 11, 12 publishing to quay, but they'll rotate out of support later this year.  I'll track turning off quay separately.
