### ISSUE TITLE
[shameless plug] Rules Engine

### ISSUE THREAD

**Issue by antonmedv** [gravitational/teleport#22509]
Hello! Thanks for the awesome project!) 👍🏻

May I suggest switching to using https://github.com/antonmedv/expr for rules?

Expr has a similar syntax, precompiles expressions to bytecode, and even type-checks them. And more importantly, it is fast.

**Comment by zmb3** [comment]
Thanks for the suggestion, looks like a nice package. Not something we're likely to take on any time soon though.
