### ISSUE TITLE
SSH Nodes: Download Files Ambiguous Error 

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#22507]
Expected behavior:
When accessing a specific node in the Teleport UI, which shares a name with other nodes, it should allow you to download a file using the file transfer dialog without any issues.
![Screenshot 2023-03-01 at 2 00 37 PM](https://user-images.githubusercontent.com/96448492/222253948-2b2cf8fe-27d2-40c3-ac17-479cbfa2c36a.png)

Current behavior:
When starting a session through the Teleport UI to a specific node, which shares a name with other nodes, it fails to download any file using the file transfer dialog with the following error: 
![Screenshot 2023-03-01 at 2 00 25 PM](https://user-images.githubusercontent.com/96448492/222254024-7ed6d8ef-1e11-4c5e-a768-fb46a1f6cacd.png)

Bug details:
- Teleport version: 12.0.x (tested on v12.0.1 and v12.0.4)
- Recreation steps: 
1. Add 2 Ubuntu 20.04 to your Teleport Cluster with the same node name
2. Attempt to download a file from any of the nodes 
- Debug logs: `failed connecting to node ninja-node4. err-node-is-ambiguous`

**Comment by russjones** [comment]
@avatus Can you fix this while you are working on moderated sessions downloads? We should connect/download via UUID instead of node name.

cc @zmb3

**Comment by avatus** [comment]
Sure thing!

**Comment by ravicious** [comment]
I've addressed a similar issue in Connect a few weeks ago when I was working on removing the resource cache. We were using the hostname (which we had to get from the resource cache) while the UUID is available from the URIs used by Connect. 

* https://github.com/gravitational/teleport/pull/21913

**Comment by avatus** [comment]
@ravicious basically same thing to solve here as well. We already sent the serverID in the http request itself, so rather than searching for a hostname, I just passed in the serverID and all is well 👍
