### ISSUE TITLE
operator:  Do not store sensitive information directly in Operator CRDs

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#22557]
### What would you like Teleport to do?

Customer requesting that CRDs for the operator do not contain secret values. Examples include: password hashes, sso connectors

### What problem does this solve?

The preference is to store this sensitive information as a Kubernetes secret then reference that secret when needed by the operator. 

### If a workaround exists, please include it.

None

**Comment by zmb3** [comment]
https://github.com/gravitational/teleport/pull/46699
