### ISSUE TITLE
Clarify where to run the Desktop Service AD script

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#22558]
## Applies To

There needs to be some clarity around where to run the Active Directory configuration script.  Our Web UI also doesn't explain it very well.

![image](https://user-images.githubusercontent.com/1424442/222541291-60914d6b-cdbe-436f-8d31-ad879e54d789.png)

## Details

Add a note to explain where to run this script. The windows device to connect to? The AD box itself? The assumption is to run it off the AD server, but having it declared will help reduce confusion.

**Comment by zmb3** [comment]
The server isn't an AD server until you run the script 😀

**Comment by Valien** [comment]
The thing is, it's already an AD server (in our POV case). There was confusion on whether to run this or not since AD and ADCS was already up and going.  

They did end up running it on the AD server but encountered some errors in the script so reverted to a manual process instead. 

But the confusion came up on a call as the prospect wasn't 100% sure where to run the script: stand-alone windows box connected to AD or the AD box itself.
