### ISSUE TITLE
desktop access: clipboard doesn't appear to sync from local workstation to teleport session

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#22614]
On Chrome and Edge (on Windows) users report that clipboard sharing is not correctly synchronizing the local clipboard with the remote machine.

- local copy, followed by a paste in the session: does not work
- copy from the session, pasted locally: works

**Comment by ibeckermayer** [comment]
This was a matter of clipboard permissions being denied to the browser. Suggested remediation to avoid confusion in the future can be tracked here: https://github.com/gravitational/teleport/issues/22754
