### ISSUE TITLE
ERROR: auth_server is supported from config version v3 onwards

### ISSUE THREAD

**Issue by reinka** [gravitational/teleport#22651]
## Applies To

Version 12.x of https://goteleport.com/docs/deploy-a-cluster/helm-deployments/custom/ 

## Details
Following the steps of the above documentation does not lead to a successful Helm installation for me. I get the error put in the title of this issue thrown by the `teleport-proxy` pod. 

I have been trying both some custom Helm values and the Helm values of the documentation, and both lead to the same error.

```
$ ./install.sh               
Release "teleport" has been upgraded. Happy Helming!
NAME: teleport
LAST DEPLOYED: Sun Mar  5 11:32:38 2023
NAMESPACE: teleport
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:

$  kgp
NAME                             READY   STATUS             RESTARTS        AGE
teleport-auth-6f9987466f-wkgkd   1/1     Running            0               13m
teleport-proxy-d8ddf5454-l5bff   0/1     CrashLoopBackOff   7 (2m45s ago)   13m
$  k logs teleport-proxy-d8ddf5454-l5bff
ERROR: auth_server is supported from config version v3 onwards
```

where the content of my `install.sh` script is:

```
#!/usr/bin/env bash

# kubectl create namespace teleport
# kubectl label namespace teleport 'pod-security.kubernetes.io/enforce=baseline'

helm upgrade --install teleport teleport/teleport-cluster \
    --create-namespace \
    --namespace=teleport \
    --values values.yaml
```

```
helm list
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                  	APP VERSION
teleport	teleport 	1       	2023-03-05 11:46:34.704694508 -0800 PST	deployed	teleport-cluster-12.0.5	12.0.5    
```

I'm not sure if I did something wrong or if there's something missing in the documentation (also not sure how it's possible to specify the config version via Helm values).

**Comment by MarkCupitt** [comment]
I also found that this was incorrect in the example yaml

```
      # The auth server domain pattern is "<RELEASE-NAME>-auth.<RELEASE-NAMESPACE>.svc.cluster.local:3025"
      # If you change the Helm release name or namespace you must adapt the `auth_server` value.
      auth_server: "teleport-auth.teleport.svc.cluster.local:3025"
```

shoudl be

```
      # The auth server domain pattern is "<RELEASE-NAME>-auth.<RELEASE-NAMESPACE>.svc.cluster.local:3025"
      # If you change the Helm release name or namespace you must adapt the `auth_server` value.
      auth_server: "teleport-cluster-auth.teleport.svc.cluster.local:3025"
```

**Comment by MarkCupitt** [comment]
I also found this on that may be a little better documented

```
    teleport:
      # The join_params section must be provided for the proxies to join the auth servers
      # By default, the chart creates a Kubernetes join token which you can use.
      join_params:
        method: kubernetes
        # The token name pattern is "<RELEASE-NAME>-proxy"
        # Change this if you change the Helm release name.
        token_name: "teleport-proxy"
```

Might help if it was something like

```
      join_params:
        method: kubernetes
        token_name: "{helm-release-name}-proxy"
```

**Comment by MarkCupitt** [comment]
The example suggested this for the proxy pod

```
    proxy_service:
      enabled: true
      listen_addr: 0.0.0.0:3080
 ```

which resulted in and error in th eproxy pods:

```
ERROR: listen tcp 0.0.0.0:3080: bind: address already in use
```
Removing the listen seems ot have fixed it
```
    proxy_service:
      enabled: true
      #listen_addr: 0.0.0.0:3080     
```

**Comment by hugoShaka** [comment]
Thank you for the report and feedback. The `scratch` mode is entirely unnecessary, the other modes coupled with the override mechanism allow users to pass arbitrary configurations without having to write a fully working configuration. 

We'll change the custom guide to use `standalone` instead of `scratch` and the users should not have to face those issues and deal with listener and internal joining.

Should be fixed in https://github.com/gravitational/teleport/pull/26787

**Comment by hugoShaka** [comment]
Closed in https://github.com/gravitational/teleport/pull/26787, we no longer send users to the scratch mode, they should not have to deal with `teleport.yaml` versions nor listener configuration
