### ISSUE TITLE
Multiple connection reverse tunnel using resources

### ISSUE THREAD

**Issue by jplana** [gravitational/teleport#2267]
With Teleport version pre 2.4(?) you could define a trusted_cluster with multiple endpoints, using the configuration file, something like this:

```
  trusted_clusters:
    - key_file: XXX
      allow_logins: root, somebody
      tunnel_addr: XX.XX.XX.XX:P,XX.XX.XX.XX:P
```
But now with resources we can't add multiple IPs for a reverse tunnel:

`Original Error: *trace.BadParameterError invalid network address: 'access.tuenti.io:14024,access.tuenti.io:24024', expecting host:port `

While the support for multiple peers for a single cluster seem to be in place (is [this](https://github.com/gravitational/teleport/blob/cbfa38a9223fc7d4782324310bb45d152e933fc8/lib/reversetunnel/peer.go#L52) it?), creation of a reverse tunnel with multiple peers seem to be [disabled](https://github.com/gravitational/teleport/blob/master/lib/auth/trustedcluster.go#L624).
 
If we change the resource directly within etcd, changing the key `teleport-ent/reverseTunnels/XXXX` manually, to something like:

```
{
  "kind": "tunnel",
  "version": "v2",
  "metadata": {
    "name": "XXX"
  },
  "spec": {
    "cluster_name": "XXX",
    "dial_addrs": [
      "XX.XX.XX.XX:P",
      "XX.XX.XX.XX:P"
    ]
  }
}
```  
 
both connections will be established to the remote cluster.

**Comment by aberoham** [comment]
Hi Jose, as-is we recommend a load balancer in front of the two distinct endpoints if at all possible. 

In a future milestone we will consider making `tunnel_addr` a list, probably with syntax such as this:

```
tunnel_addr:
   - xx.xx.xx.xx:pp
   - xx.xx.xx.xx:pp
```

If you have urgent requirements around this configuration/feature request, please reach out to us directly.

**Comment by jplana** [comment]
Hi Abraham,

while we use LBs for other endpoints (like web access), the previously supported pattern (when this configuration was possible using the configuration file instead of dynamic resources) of multiple connections save us quite a few resources (mainly the use of two LBs). 

We haven't tested this feature in depth, however we've found the if only one reverse tunnel is established (like when using a LB). Some cases don't work properly:   

```
                             +-------------+         +------------+        +-------------+
                             |             |         |            |        |             |
                             |             |         |            |        |             |
                             |  Proxy A    +--------->    LB      +-------->  Proxy A    |
                             |             |         |            |        |             |
  +--------------+           |             |         |            |        |             |
  |              |           |             |         |            |        |             |
  |              |           +-------------+         +------------+        +-------------+
  |   Host B     |
  |              |
  |              |           +-------------+                               +-------------+                +---------------+
  +--------------+           |             |                               |             |                |               |
                             |             |                               |             |                |               |
                             |  Proxy B    |                               |  Proxy B    <----------------+    Host A     |
                             |             |                               |             |                |               |
                             |             |                               |             |                |               |
                             |             |                               |             |                +---------------+
                             +-------------+                               +-------------+



+----------------------------------------------+      +----------------------------------------------------------------------+

                             Remote Cluster                                     Local cluster
```

In this case, connections from HOST A to HOST B (in a remote cluster) seem to fail, given that there's no active tunnel between the proxy B in the local cluster to any proxy in the remote cluster.

The previous configuration, or our current "hack" editing directly the ETCD resource, seems to work fine:

```
                             +-------------+                               +-------------+
                             |             |                               |             |
                             |             |                               |             |
                             |  Proxy A    +-------------+----------------->  Proxy A    |
                             |             |             |                 |             |
  +--------------+           |             |       +----------------------->             |
  |              |           |             |       |     |                 |             |
  |              |           +-------------+       |     |                 +-------------+
  |   Host B     |                                 |     |
  |              |                                 |     |
  |              |           +-------------+       |     |                 +-------------+                +---------------+
  +--------------+           |             |       |     |                 |             |                |               |
                             |             |       |     |                 |             |                |               |
                             |  Proxy B    +-------+    ++----------------->  Proxy B    <----------------+    Host A     |
                             |             |       |                       |             |                |               |
                             |             |       +----------------------->             |                |               |
                             |             |                               |             |                +---------------+
                             +-------------+                               +-------------+



+----------------------------------------------+      +----------------------------------------------------------------------+

                             Remote Cluster                                     Local cluster
```

As cluster peers are connected to all local proxies. 

That said, we could live with such hack, but it would be great to recover the "client LB" support that you had in place.

BTW, we're using Teleport Enterprise 2.6.7

Thanks!

**Comment by jplana** [comment]
Thanks @klizhentas, we might review this setup in a future iteration. In any case, "client load balancing" sounds like a good feature, and the system seems to already have support, just missing a few changes over the Reverse Tunnel model. Should I keep open this issue as a feature request?

**Comment by benarent** [comment]
Hi @jplana, I was reviewing this ticket while creating another ticket and due to age and an older version. I'm going to close it for now. If you're still having issues with your trusted cluster proxy setup. Please send me a mail ben@gravitational.com
