### ISSUE TITLE
Support for Disabling GCP Database TLS

### ISSUE THREAD

**Issue by soudaburger** [gravitational/teleport#22697]
I'm sort of frustrated, to be honest.  We keep trying to make teleport functional in our environment, but we keep running into hurdles, so I'm not really sure what the paradigm for this architecture is supposed to be.  Perhaps someone can help here?

We are currently running teleport cloud via GKE with a helm installation of the `teleport-kube-agent` chart.  We are unable to `enforce` TLS on our instances because the permissions in the docs call for granting `cloudsql.sslCerts.createEphemeral`, but THAT permission is ONLY available in `CloudSQL Admin` and NOT available as a grantable permission in a custom role.

Ok, that's not necessarily teleport's fault, so we'll try something else.  Let's deploy Google's https://github.com/GoogleCloudPlatform/cloud-sql-proxy as a sidecar.  We figured out how to do that, although the helm chart does not directly support sidecars.  But the issue we're running into now, is that because Teleport wants to connect to EVERYTHING over TLS, it's unable to connect to `cloudsqlproxy`, because `cloudsqlproxy` is handling these connections and doesn't support connecting to it over TLS.

So what are my options here for connecting to GCP databases via Teleport for users? The way I see it:
1. Disable "Enforce SSL Connections" on GCP CloudSQL instances, our security team isn't going to sanction this.
2. Grant `CloudSQL Admin` to the `teleport-db-service` service account?  Our security team isn't going to sanction this either.
3. Connect to `cloudsqlproxy` as a sidecar, but this requires being able to tell teleport that certain DB connections are allowed to be unencrypted.  Maybe if we could ONLY use `localhost` as the URI? I'm grasping at straws here.
4. Don't use teleport at all and bypass teleport completely because teleport doesn't really seem functional in this paradigm.

Thoughts?  Am I missing something here?

**Comment by soudaburger** [comment]
I should also add that connecting to `cloudsqlproxy` produces the following error message:
```bash
"component":"db:service","error":"server refused TLS connection","level":"error","message":"Failed to handle connection."
```

**Comment by zmb3** [comment]
Hi there,

I'm just now seeing this old issue. Sorry to see that you had trouble with Teleport and GCP.

Given that this is approaching a year old and is buried in a large list of issues, I'm going to close it due to inactivity. 

If you are still having trouble, feel free to create a new issue with fresh details and we'll try our best to take a look. If you happen to be a Teleport customer, I'd recommend filing a support ticket, which will get more attention than an issue on the OSS repo.
