### ISSUE TITLE
Incorrect user specified when running tsh ssh into clusters

### ISSUE THREAD

**Issue by andrewbanchich** [gravitational/teleport#2272]
**What happened**:

I have one `master` trusted cluster and two clusters attached to that. When I run `tsh ls --cluster=ChildCluster role=node` it correctly lists all nodes with that label. However, when I run `tsh ssh --cluster=ChildCluster role=node touch /root/test.txt` it produces the following error:

```
error: access denied to andrewbanchich connecting to [ip address]
```

This is strange because my teleport username is `andrew` and my local computer's username is `andrewbanchich`. When I specify a user explicitly with `--user=andrew` it still produces the same error with the same incorrect username of `andrewbanchich`.

**What you expected to happen**:

I expected to be able to issuer SSH commands on child clusters of my trusted cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`): 3.0.0
- Tsh version (use `tsh version`): 3.0.0
- OS (e.g. from /etc/os-release): Tested on Mac OS and Ubuntu

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by aberoham** [comment]
Try `-l` param? Node-local identity isn't directly connected to your Teleport identity, Teleport is just spawning the shell as the requested node-local identity. 

```
sh
Usage: tsh [<flags>] <command> [<args> ...]

TSH: Teleport SSH client

Flags:
  -l, --login        Remote host login
[snip]
```

**Comment by andrewbanchich** [comment]
When I try `tsh ssh -l andrew --cluster=ChildCluster role=node touch /root/test.txt` it now produces the same error, but with the correct user:

```
error: access denied to andrew connecting to [ip address]
```

**Comment by aberoham** [comment]
When you run `tsh status` on your local instance after logging in, does your Teleport-specific account name (aka the `Logged in as` value) on your immediate cluster map through to a valid Teleport-specific account name and role (likely just `admin`) on the remote cluster? 

You might want to always use `--user` AND `--login` params on your command lines to make sure any implicit value being picked up from your shell isn't adding to the confusion.

**Comment by andrewbanchich** [comment]
> When you run tsh status on your local instance after logging in, does your Teleport-specific account name (aka the Logged in as value) on your immediate cluster map through to a valid Teleport-specific account name and role (likely just admin) on the remote cluster?

Yes it does.

```
~ » tsh status
> Profile URL:  [removed]
  Logged in as: andrew
  Cluster:      master
  Roles:        admin*
  Logins:       root
  Valid until:  2018-10-06 00:08:29 -0400 EDT [valid for 10h14m0s]
  Extensions:   permit-agent-forwarding, permit-port-forwarding, permit-pty


* RBAC is only available in Teleport Enterprise
  https://gravitaitonal.com/teleport/docs/enteprise
```

When I run `tsh ssh --login=andrew --user=andrew --proxy=[proxy url]--cluster=ChildCluster role=node touch /root/test.txt` it still says:

```
error: access denied to andrew connecting to [ip address]
```

**Comment by klizhentas** [comment]
your SSH login though does not contain `andrew` in SSH principals

**Comment by andrewbanchich** [comment]
> your SSH login though does not contain andrew in SSH principals

I'm not sure I understand.

**Comment by aberoham** [comment]
`Logins:       root`

If you wanted to log in locally as `andrew`, the SSH principals should include that username aka "allowed logins" within Teleport's role definition

**Comment by andrewbanchich** [comment]
Ah, that does make sense. Thank you! I was just confused about what `login` vs `user` meant.
