### ISSUE TITLE
Navigation issue in 12.1.0

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#22755]
There is a new bug in the Teleport 12.1.0 while navigating between "Management" and "Resources" menu

Steps to repro:

![repro-issue](https://user-images.githubusercontent.com/13717/223588701-7213a0fd-d697-4e00-8ff6-120f0e214227.png)

in "Resources" screen, navigate to "Help & Support"
Navigate to "Management" screen
Navigate to "Resources" screen back again, you won't see Resourse again
You need to refresh the screen to see the Resources screen.

**Comment by vnkr-teleport** [comment]
To add to the above on V12 I observed that if you go to the Account Settings - 2FA Devices, you can't get back to the Resources from there without refreshing the page.

**Comment by hatched** [comment]
The issue for the 2FA bug mentioned above is: https://github.com/gravitational/teleport/issues/22206
