### ISSUE TITLE
Machine ID: Azure Managed Identity delegated joining

### ISSUE THREAD

**Issue by taetayy** [gravitational/teleport#22758]
What would you like Teleport to do?
[Dynamic Join Tokens](https://goteleport.com/docs/machine-id/architecture/#dynamic-join-tokens-eg-aws-iam) are the recommended method for authenticating `tbot` however the only supported provider is AWS IAM. I would like Teleport to add functionality to authenticate via Azure Managed Identity.

What problem does this solve?
Currently there is not an Azure supported method of generating Dynamic Join Tokens for Machine ID. This would give short lived Azure resources (ACI, VMSS, etc.) the ability to autoscale and authenticate themselves to Teleport. 

If a workaround exists, please include it.

**Comment by zmb3** [comment]
@strideynet does machine ID work with Azure joining?

**Comment by strideynet** [comment]
> @strideynet does machine ID work with Azure joining?

It looks like the required bits of code in the `tbot` package itself have been omitted from the implementation that was merged. However, this shouldn't be too much work to add assuming there's no problems with the Azure join implementation.
