### ISSUE TITLE
Build infrastructure improvements

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2277]
Also update zendesk issue 347

**Comment by russjones** [comment]
@klizhentas What do you think about adding support for building with Go 1.9.x to this ticket and making this a generic build improvements ticket?

**Comment by klizhentas** [comment]
do it

**Comment by russjones** [comment]
Let's make the following build improvements.

**Support 32-bit builds for Linux**

We have to investigate 32-bit VM support on the various cloud providers to act as a build box.

The other option that may be more viable is using Docker to do cross compilation of 32-bit binaries like we build Windows binaries.

The output archive should have the following format: `teleport-v3.0.0-linux-386-bin.tar.gz`

**Maintain Teleport binaries built with Go 1.9**

Several issues have come up that require us to continue to support binaries built with Go 1.9 long term. We should update the build infrastructure to have both the current version of Go and a legacy version so Linux binaries can be built as well.

The output archive should have the following format: `teleport-v3.0.0-linux-amd64-legacy-bin.tar.gz`.

**Comment by russjones** [comment]
Fixed in the following PRs:

https://github.com/gravitational/ops/pull/96
https://github.com/gravitational/teleport/pull/2306
https://github.com/gravitational/teleport.e/pull/97
