### ISSUE TITLE
What is the best way to change a teleport cluster setup?

### ISSUE THREAD

**Issue by andrewbanchich** [gravitational/teleport#2278]
I currently have one trusted cluster and several clusters which connect to that. These lower level clusters each have one proxy and multiple nodes. I am worried that if the proxy of the lower level clusters becomes unavailable that I will lose access to that entire cluster.

1. Am I correct in thinking the best way to deal with this is to reconfigure my setup so that every lower level node is a proxy itself instead of relying on just one proxy to connect to my trusted cluster?

2. If so, I am worried there will be authorization issues with bad certs if I reconfigure them to be proxies when they were once nodes. What is the best process for changing a cluster's configuration like this?

Thank you

**Comment by andrewbanchich** [comment]
Also:

3. If everything is a proxy, it would be nice to not have each proxy be equivalent to a cluster. For example, if I have 20 proxy nodes at the same location, the Web UI dropdown will show 20 different clusters. I would really like the ability to set up a cluster which connects to a trusted cluster where the lower level cluster has higher resiliency in some way, but it doesn't clog the Web UI dropdown with many different clusters where each cluster consists of one node.

**Comment by benarent** [comment]
Hi Andrew, We are currently re-working our Cluster view and we hope to address a few of these issues. We are looking for early people to help with feedback. If these issues are still relevant can you please email me at ben@gravitational.com
