### ISSUE TITLE
teleport lab: "failed to fetch" after setting up MFA device

### ISSUE THREAD

**Issue by DonThorntonJr** [gravitational/teleport#22793]
Set Two-Factor Device
Failed to fetch
after setting up with Authy

**Comment by zmb3** [comment]
Hi @DonThorntonJr! The more information you can provide us, the better we'll be able to assist.

Some information that might be useful:

- What version of Teleport you're running
- A screenshot of the error
- Logs

**Comment by zmb3** [comment]
Closing due to in activity.
