### ISSUE TITLE
Reset/regenerate TOTP 2fa "master key"

### ISSUE THREAD

**Issue by lierdakil** [gravitational/teleport#2280]
It's absolutely mandatory to be able to reset/regenerate TOTP 2fa "master key"

Situation: I've switched phones. I need to update 2fa "master key". Apparently, I can't. Now I have to jump through the hoops of recreating everything with a new user apparently.

If I'm missing something, please let me know.

**Comment by aberoham** [comment]
Hi Nikolay, thanks for opening an issue and providing feedback. 

Most of our large users & deploymemnts - the ones that fund Teleport feature development - connect Teleport to SSO where 2fa/utf is a function of that larger IdP (identity provider, eg Okta, Microsoft Active Directory ADFS, Auth0, OneLogin, etc).

You are an end-user of a Teleport cluster (teleport-auth instance) ran by someone else? You're running your own teleport-auth instances?

If you are a `tctl` admin and using Teleport's internal user database, the work-around is to simply delete and re-create the record that maps a user to a role. `tctl delete user/[username]`, then `tctl add user [with same params as original]`. There shouldn't be much to re-create, all of the machinery should continue to work just fine even after the user record is swapped out. 

Perhaps you're an end-user who doesn't have direct `tctl` admin privs and the hoops involve the round-trip to the admin? If you could provide more color on your ideal UX here that could be useful.

Thanks!

**Comment by lierdakil** [comment]
> the workaround is to simply delete and re-create the record that maps a user to a role

That's basically what I figured. While it isn't as big of a challenge I initially imagined it to be, it's still not ideal. By happy coincidence, I am "admin-ing" the Teleport instance in question. But if not for that, this *would* involve the round-trip to the admin, and that could've been quite the round-trip considering geographically-distributed nature of our team.

> If you could provide more colour on your ideal UX here that could be useful.

So, a bit of background. We're running Teleport to provide access to a few number-crunching servers for a small engineering team. This is leagues easier than what we used to have, which involved a lot of SSH keys and some hacky NAT traversal, so I'm very pleased with Teleport in this regard. Using a separate identity provider is a bit of an overkill for our use-case, so we're running 'auth service' provided by Teleport.

Now then, all was good until I had to switch phones. And I was unpleasantly surprised that there seems to be no straightforward way to accommodate that with the current set-up. I might have overreacted a little in the opening post, but I was just finishing up with over other services that use TOTP (quite a few) and running into a roadblock like this was more than a little bit jarring.

My initial expectation was that the end-user should be able to reconfigure 2fa from Teleport's web interface -- after all, it's possible to change the password from there, and that's basically how it works with your Googles and Facebooks and whatnot. This is, sadly, not the case.

My second thought was that there *has* to be a `tctl` command to do this. There isn't (well, unless we count the whole dance involving `get user/joe > joe.yaml && users rm joe && users add joe && create -f joe.yaml`)

So anyway, while I did solve the issue for myself using the workaround, I kinda-sorta dread the moment someone else on our team runs into the same issue (because then it also would be my problem, and these things tend to happen at the worst possible moment).

I'm pretty sure it should be relatively straightforward to implement TOTP management in the web UI, after all, the groundwork is already in place (OTP key generation, QR code generation, etc). I understand if it's not a priority, but it would be a nice feature to have I believe. In the meantime, writing a paragraph or two on this in the documentation might be a good idea, maybe?

**Comment by gclawes** [comment]
This has already been raised in https://github.com/gravitational/teleport/issues/1929

**Comment by lierdakil** [comment]
I would argue that #1929 is a bit different. Implementation of #1929 might cover the case described here, but from where I stand it doesn't have to necessarily. At the very least, this issue seems to be much narrower in scope, and so might be easier to address. That is to say, adding a web UI for regenerating TOTP keys sounds easier to me than solving the general problem of supporting multiple different keys per account (and *then* creating a web UI for *that*)

**Comment by ybaumy** [comment]
would be great if a user could not only change his password, but also his MFA device or token authentication.

**Comment by zedtux** [comment]
I'm also facing this issue and would like to see the 2fa reset option available.

**Comment by awly** [comment]
Fixed via https://github.com/gravitational/teleport/pull/5473
You can now add new devices via `tsh mfa add` (to be released in teleport 6.0), but you need at least one 2FA method still available
