### ISSUE TITLE
Design Component Library: Buttons

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#22806]
Button Types:

- [ ] Primary Button
- [ ] Minimal Button
- [ ] Danger Button
- [ ] Icon-only Minimal Button
- [ ] (Do we currently have a need for Primary/Danger icon-only buttons? If not, we can punt on that until we come up with a need for them)

Button Sizes:
- [ ] Small
- [ ] Medium
- [ ] Large

Each should have Light and Dark theme with the following states for each:
- [ ] Default
- [ ] Hover
- [ ] Active/Pressed
- [ ] Focus
- [ ] Disabled
- [ ] Interaction links between states for prototyping

Buttons should also have hidden (by default) 
- [ ] left icon and 
- [ ] right icon 
that we can show as needed in designs.

**Comment by rishibarbhaya-design** [comment]
Component: Buttons (btn)
Inclusion: Light and Dark Version

Link: https://www.figma.com/file/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?node-id=6642%3A29063&t=kQYtyY6zBmtNvlMs-1
Go to file > Buttons (btn)

**Comment by zmb3** [comment]
@roraback my understanding is that the design system has been updated w.r.t buttons and it's just on engineering to make the updates now. Is this correct?

If so, can we close this issue out?

**Comment by zmb3** [comment]
This is tracked as a development task in #37260, so I assume there is no more design work to be done and this can be closed. Feel free to reopen if I am mistaken.
