### ISSUE TITLE
Design Component Library: Radio Button with Label

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#22819]
Radio Button with Label in:
- [ ] Light Theme
- [ ] Dark Theme

Sizes for each theme:
- [ ] Large Radio Button with Label
- [ ] Medium Radio Button with Label

Checked states for each size:
- [ ] On
- [ ] Off

Interactive states for each checked state:
- [ ] Default
- [ ] Hover
- [ ] Active/Pressed
- [ ] Focus
- [ ] Disabled
- [ ] Prototype connections across interactive states

**Comment by roraback** [comment]
Note: This could be combined with the Checkbox component with a property for "Type" and values of "check" and "radio"

**Comment by zmb3** [comment]
This is tracked as a development task in #37260, so I assume there is no more design work to be done and this can be closed. Feel free to reopen if I am mistaken.
