### ISSUE TITLE
u2f: untrusted facet id

### ISSUE THREAD

**Issue by andrewbanchich** [gravitational/teleport#2281]
**What happened**:

I changed the auth type from `OTP` to `U2F` to use with a Yubikey 5.

On Firefox I go to the signup page, enter a password, submit, Firefox shows the popup to touch the Yubikey, so I do and Teleport displays:

```
{"message":"u2f: untrusted facet id"}
```

If I try the same thing on Chrome, Chrome doesn't have a popup for touching the Yubikey, but when I do it displays:

```
Please check your U2F settings, make sure it is plugged in and you are using the supported browser.
U2F error: BAD_REQUEST
```

I'm using Teleport 3.0.0.

**Comment by andrewbanchich** [comment]
Found (probably) [the issue](https://github.com/gravitational/teleport/blob/1c2b2b7de2ec17f2bc97ccbd948cfb0e5065b0df/docs/1.3/admin-guide.md#enabling-u2f). Thanks though!

**Comment by andrewbanchich** [comment]
Actually, after adding `app_id` and `facets` it is still coming up with the same error message.

**Comment by alex-kovoy** [comment]
> In the Web case, the FacetID must be the Web Origin [RFC6454] of the web page triggering the FIDO operation, written as a URI with an empty path. Default ports are omitted and any path component is ignored.

Below is an example of working config (against localhost)

```
{
  "kind": "cluster_auth_preference",
  "version": "v2",
  "metadata": { "name": "cluster-auth-preference" },
  "spec": {
    "type": "oidc",
    "second_factor": "u2f",
    "u2f": {
      "app_id": "https://localhost:3080",
      "facets": ["https://localhost", "https://localhost:3080"]
    }
  }
}
```

**Comment by andrewbanchich** [comment]
@alex-kovoy I have this config:

```
...
    authentication:
        type: local
        second_factor: u2f
        app_id: https://localhost:3080
        facets:
        - https://localhost:3080
...
```

These are settings on a trusted cluster that was previously configured with `otp`. Not sure if that makes any difference.

**Comment by andrewbanchich** [comment]
Ah, I don't know how I missed that in the docs! Thank you.

Maybe Teleport could add a feature to prevent restarting it with an invalid config file?

**Comment by alex-kovoy** [comment]
Good point, I've created this ticket to track the issue #2309.

Closing this one.
