### ISSUE TITLE
Design Component Library: Checkboxes with Labels

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#22818]
Radio Button with Label in:
- [ ] Light Theme
- [ ] Dark Theme

Sizes for each theme:
- [ ] Large
- [ ] Medium

Checked states for each size:
- [ ] On
- [ ] Off
- [ ] Indeterminate

Interactive states for each checked state:
- [ ] Default
- [ ] Hover
- [ ] Active/Pressed
- [ ] Focus
- [ ] Disabled
- [ ] Prototype connections across interactive states

**Comment by roraback** [comment]
Note: This could be combined with radio buttons and toggle switches with a property for "Type" and values of "check" + "radio" + "switch" – but even if we do, we should create the checkboxes variants first.

**Comment by zmb3** [comment]
This is tracked as a development task in #37260, so I assume there is no more design work to be done and this can be closed. Feel free to reopen if I am mistaken.
