### ISSUE TITLE
Paste text with right click, copy by selection in terminal

### ISSUE THREAD

**Issue by vdtoorn** [gravitational/teleport#22828]
What would you like Teleport to do?
I'd like similar behavior to many terminals like putty, that if you right-click in the terminal window it would paste the text from the clipboard. Alternatively, make ctrl-v work. It would also be nice if selecting text in the terminal window automatically copies that text. Maybe as an option, so people who think it is a security risk can disable the behavior.

What problem does this solve?
To paste text (commands) in a terminal, you need to right-click and select 'paste', to copy you need to select, right-click and 'copy'. This is cumbersome and unlike other shell emulators.

If a workaround exists, please include it.

**Comment by zmb3** [comment]
See https://github.com/microsoft/vscode/pull/38287 for how this was implemented in VS Code.

**Comment by revolution1964** [comment]
I have figured out that you can use ctrl-insert to copy and shift-insert to paste, but it drives me crazy when I copy something with the mouse and paste to find out my selection wasn't automatically copied to the clipboard, and I paste something old instead.  I wish there was an option to make it auto-copy what is selected like in many other terminals.
