### ISSUE TITLE
Web UI port

### ISSUE THREAD

**Issue by andrewbanchich** [gravitational/teleport#2282]
Is there a reason to stick with port 3080 for the Web UI, or can I tell it to use 443 without any issues?

**Comment by aberoham** [comment]
Many folks run teleport-proxy UI on port 443, or run a load balancer in front that listens on 443 and forwards to a set of teleport-poxy instances listening to 3080. The only caveat is that when you login using the command line you need to remember to specify :443 as the port. (Though in the future the `tsh` client may automatically try 443 if 3080 isn't listening) Docs here https://gravitational.com/teleport/docs/user-manual/#proxy-ports

**Comment by andrewbanchich** [comment]
Out of curiosity: when I change the `web_listen_addr`  to `0.0.0.0:443` my remote clusters still connect without any issues. I had configured them with `web_proxy_addr: mydomain.com:3080`, so I would have thought they'd be trying to connect on 3080 while the trusted cluster is listening on 443 instead.

How does this still work?

**Comment by aberoham** [comment]
Port 3024 is the default port used by teleport-proxy to receive inbound trusted cluster connections. https://gravitational.com/teleport/docs/admin-guide/#ports

**Comment by andrewbanchich** [comment]
That makes sense. I guess I am more wondering what the purpose of specifying the `web_proxy_addr` for a trusted_cluster.yaml config like this: https://gravitational.com/teleport/docs/admin-guide/#example-configuration

**Comment by aberoham** [comment]
I believe web_proxy_addr and its TLS certificate is used when first joining a trusted cluster to establish trust (by leveraging public web certs + CAs), and then is no longer used. peek at the code or test it out for me?
