### ISSUE TITLE
SSL x509 error with kubectl when used with trusted clusters

### ISSUE THREAD

**Issue by andrewl3wis** [gravitational/teleport#2289]
**What happened**:
When using kubeproxy with a remote trusted cluster, kubectl returns an x509 error for the remote cluster. If you use `--insecure-skip-tls-verify` connectivity works. 

Ex:
```
kubectl get nodes
No resources found.
Unable to connect to the server: x509: certificate is valid for teleport-9fbbcc87d-8p75c, teleport.aws.example.com, remote.kube.proxy.teleport.cluster.local, kube.aws.example.com, not blue.teleport.aws.example.com
```

```
kubectl get nodes --insecure-skip-tls-verify 
NAME                                           STATUS    ROLES     AGE       VERSION
ip-10-110-193-153.us-east-2.compute.internal   Ready     node      21d       v1.10.7
ip-10-110-193-191.us-east-2.compute.internal   Ready     master    16d       v1.10.7
ip-10-110-194-165.us-east-2.compute.internal   Ready     master    31d       v1.10.7
ip-10-110-194-24.us-east-2.compute.internal    Ready     node      21d       v1.10.7
ip-10-110-194-76.us-east-2.compute.internal    Ready     node      21d       v1.10.7
ip-10-110-195-119.us-east-2.compute.internal   Ready     master    31d       v1.10.7
ip-10-110-195-250.us-east-2.compute.internal   Ready     node      21d       v1.10.7
ip-10-110-195-31.us-east-2.compute.internal    Ready     node      21d       v1.10.7
```

**What you expected to happen**:
A wildcard to be generated for connections to the kubeproxy, it was mentioned as a requirement for trusted clusters in #1986, but doesn't look like it was implemented. 

**How to reproduce it (as minimally and precisely as possible)**:

Setup two kubernetes clusters as trusted clusters, and try to connect to the remote trusted cluster using kubectl 

**Environment**:
- Teleport version (use `teleport version`): 3.0.0
- Tsh version (use `tsh version`): 3.0.0
- OS (e.g. from /etc/os-release):

**Comment by klizhentas** [comment]
just make sure you add `blue.teleport.aws.example.com` to public_addr section of addresses in your `kubernetes` config section and it will work:

```
proxy_service:
  enabled: yes
  kubernetes:
    enabled: yes
    public_addr: ['blue.teleport.aws.example.com', 'kube.aws.example.com']
```

**Comment by klizhentas** [comment]
feel free to reopen if this does not help

**Comment by klizhentas** [comment]
forgot to mention - you can use wildcards to save you some typing too

**Comment by klizhentas** [comment]
`public_addr: ['*.teleport.aws.example.com', 'kube.aws.example.com']`

**Comment by earlytracks-admin** [comment]
Hi folks,
I'm playing a bit with Teleport and i think that it's an amazing product for current dynamic infrastructure.
I'm trying also to setup teleport as an kube proxy for audit and recording session with my rancher cluster.
On the teleport daemon logs i got : 
``WARN [PROXY:KUB] Failed to get certificate for user: test, groups: [system:masters], cluster: bastion-example-ssh: {"message":"Post https://rancher.example.com:8443/k8s/clusters/c-mqg7f/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: x509: certificate signed by unknown authority"}.
I'm using Let's encrypt for Rancher SSL Termination.
I'm gonna try to add letsencrypt ca to my linux system to see if it fix the issue.

Have a nice week-end.
