### ISSUE TITLE
tsh --proxy=proxhost --cluster=clustername ssh clusternode no longer works as documented.

### ISSUE THREAD

**Issue by aashley** [gravitational/teleport#2290]
**What happened**:
`
$ tsh --cluster=od-server-00296 ssh od-server-00296
error: unknown long flag '--cluster'
`

**What you expected to happen**:
`
$ tsh --cluster=od-server-00296 ssh od-server-00296
od-server-00296$ 
`
As documented at: https://gravitational.com/teleport/docs/admin-guide/#trusted-clusters

**Environment**:
- Teleport version (use `teleport version`): Teleport v3.0.0 git:v3.0.0-0-g017ae5f9
- Tsh version (use `tsh version`):Teleport v3.0.0 git:v3.0.0-0-g017ae5f9
- OS (e.g. from /etc/os-release):Ubuntu 16.04

**Comment by klizhentas** [comment]
I think we switched --cluster to be ssh specific flag, not a global one anymore, does `tsh ssh --cluster` work?

**Comment by aashley** [comment]
Can confirm, moving --cluster to after ssh works as expected. This ticket should probably be changed to a documentation bug then to update the linked section in the admin-guide to reflect this change

**Comment by sekka1** [comment]
Looks like the usage of it is very strict and it is looking for it in a particular location:
```
$ tsh version
Teleport v3.2.4 git:v3.2.4-0-g339827c6 go1.11.5
```
```
tsh ls --cluster=teleport.example.com

tsh ssh --cluster=teleport.example.com root@teleport-5b6575c6c8-zplv5
```

**Comment by webvictim** [comment]
Fixed in https://github.com/gravitational/teleport/pull/2758
