### ISSUE TITLE
Document Application Access HA

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#22919]
To achieve HA for an application proxied by Teleport Application Access, you can run multiple agents with the exact same configuration for `app_service`.

Document this is how to achieve HA with Application Access.

**Comment by russjones** [comment]
Copy this https://goteleport.com/docs/database-access/guides/ha/

**Comment by pschisa** [comment]
Desktop access HA works the same way as well and is not documented either.  Maybe a general "protocol agent HA" guide would cover all these use cases at once?

**Comment by ptgott** [comment]
Closed via https://github.com/gravitational/teleport/pull/23024
