### ISSUE TITLE
Database access guides are too geared towards auto-discovery

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#22942]
When we originally introduced auto-discovery, we intentionally refactored all our cloud database access guides to explain how to set it up right from the start. For example, the RDS guide always tells users to set up policies for auto-discovery:

https://goteleport.com/docs/database-access/guides/rds/#step-36-create-an-iam-policy-for-teleport

For users who prefer to manage all policies themselves (without giving Teleport extra permissions for security reasons) we do have a section that explains required policies but it's not easily discoverable, and the guide doesn't mention it anywhere:

https://goteleport.com/docs/database-access/reference/aws/#manual-registration

Moreover, with the existing guides it's just not possible to understand how to connect, for example, a single RDS instance to your cluster - you're always forced to setup full discovery and auto-IAM.

We need to rethink information architecture of database access to clearly present scenarios that users may be interested in (I use RDS as example here but it applies to any cloud-based database we support), mirroring our Teleport Discover's day 1/2 flows:

- How to connect a single or multiple RDS instances.
- How to configure IAM policies for them and how to configure Teleport to auto-configure IAM policies for them.
- How to enable/disable auto-discovery and configure IAM policies for it.
- How to use IaC flows to configure things.

**Comment by JohnAtOlo** [comment]
Found these guides impossible to follow for a Kubernetes based deployment.
