### ISSUE TITLE
Allow tsh to go background and without executing remote command

### ISSUE THREAD

**Issue by bric3** [gravitational/teleport#2297]
**What happened**:
`tsh` don't have the options to make a command just for port forwarding. 

**What you expected to happen**:
When running a port forwarding like `tsh ssh -L localhost:8000:internal-name:80 dev-role@node`, I would like `tsh` to have equivalent `ssh` 

* `-f` to go background after login
* `-N` to avoid the execution of a remote command

In other words I would like this command to just forward ports.

**How to reproduce it (as minimally and precisely as possible)**:
I think the above command is enough.

**Environment**:
- Teleport version (use `teleport version`): `Teleport v2.7.4`
- Tsh version (use `tsh version`): `Teleport v2.7.4`
- OS (e.g. from /etc/os-release):
  ```
  ProductName:	Mac OS X
  ProductVersion:	10.14
  BuildVersion:	18A391
  ```

**Browser environment**

- Browser Version (for UI-related issues): N/A
- Install tools: `brew`
- Others: N/A

**Comment by kontsevoy** [comment]
@bric3 love this suggestion! we'll schedule this to a future release

**Comment by klizhentas** [comment]
@kontsevoy let's move this out of Pleasanton, we don't have enough time to roll this out

**Comment by bric3** [comment]
Arg too bad. Thx for considering this though ;)

**Comment by kontsevoy** [comment]
@klizhentas let's not forget. There's a commercial customer who asked for this as well.

**Comment by klizhentas** [comment]
let's do 4.1 release milestone and add this and other improvements there.

**Comment by webvictim** [comment]
I have another potential customer also requesting this.

**Comment by klizhentas** [comment]
when it comes to `-f` I'm not sure we should be trying to implement it due to complexity of a go runtime:

https://github.com/golang/go/issues/227

would it be OK to have just `-N` and then folks can shell features like `&` and `nohup` + io forwarding for the rest?

**Comment by amanasterdio** [comment]
Any updates on this feature team?
