### ISSUE TITLE
Non-Microsoft LDAP environments

### ISSUE THREAD

**Issue by guilhermeferreyra** [gravitational/teleport#23058]
What would you like Teleport to do?
Support for SAMBA or other open source LDAP providers.

What problem does this solve?
Unnecessary licensing costs for Active Directory.

If a workaround exists, please include it.

**Comment by zmb3** [comment]
This is not something we'll be pursuing any time soon.

The dependency on Active Directory is not just for LDAP, it's for the certificate-based authentication via smart cards.

If you don't have AD, the [local users preview](https://goteleport.com/docs/desktop-access/getting-started/) might be of interest. (Currently only available for Teleport Enterprise)
