### ISSUE TITLE
Screen of a windows server freezes in browser 

### ISSUE THREAD

**Issue by gilbert0571** [gravitational/teleport#23051]
**Description:**
The entire screen of a windows server 2022 in the active directory domian will freeze in the Chrome  when  a non-administrator user Click the 'No' button in the User Account Control dialog box that requires entering administrator account and password. But You can still click the "disconnect" icon in the top right corner of the web  browser to close the seesion successfully.

**Problem reproduction:**
1.Start by going to This Computer, right-clicking on a volume, and selecting Properties. 
2. Switch to the Quota tab and select Show Quota Settings.
3. a User Account Control dialog box will pop up for a non-administrator user.
4. click the 'No' Button.
5.  the screen freezes

**Server Details:**
Teleport version (run teleport version): v12.1.1
teleport auth and porxy Server OS (run cat /etc/issue): Debian GNU/Linux 11
Windows version: windows 2022 server
Chrome  version: 110.0.5481.178

**Debug Logs:**
No error logs have been generated.

**Comment by webvictim** [comment]
Just found the same issue with the UAC (User Account Control) dialog when trying to enter a domain administrator username/password too. Typing in the boxes works fine, but the second you click "Yes" (or "No") the screen freezes.

If you wait a minute or so, it seems to time out and just act as though you clicked "No".

Interestingly, if you enter credentials, click "Yes", let things freeze and start a fresh desktop access session as the same user while in this frozen state, it proceeds through with the Administrator logon successfully.

![image](https://user-images.githubusercontent.com/897821/225722474-a4b6edef-0b05-4ca2-850d-faf795a4c14b.png)
