### ISSUE TITLE
Add GHA workflow for updating AMI IDs

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#23066]
After each release we have to execute the following:

```bash
$ TELEPORT_VERSION=12.1.0 make -C assets/aws create-update-pr
```

It calls the following Makefile target that fetches latest AMI IDs, updates terraform scripts and opens a Github PR with the changes:

https://github.com/gravitational/teleport/blob/master/assets/aws/Makefile#L131

We want to convert this to a Github Actions workflow that runs upon the creation of the _latest_ Github release (only the latest).

For authentication with AWS we will use a OIDC role locked down to only being able to list public AMIs in our account. @wadells to fill out details on how to use it.

**Comment by wadells** [comment]
We've got a bit of backend work to do before the role is available O(1-2 days).   Particularly, we'll grant the role `ec2:DescribeImageAttribute`, and `ec2:DescribeImages`, but we need a way to limit it to only the public AMIs (as this account does have some private, not yet promoted AMIs.  I haven't found any promising [image related condition keys](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html#amazonec2-policy-keys), which means we'll probably need to tag all these AMIs so we can use a tag condition key.  This will also require updating the publishing infra to apply this tag when it promotes new images going forward.

**Comment by wadells** [comment]
I've cleaned up the legacy, private AMIs in the `gravitational`/`126027368216` account.  It should be safe to enumerate anything in there now.

The `arn:aws:iam::126027368216:role/tf-teleport-ami-gha-role` role can be used with GitHub actions, in the same manner as this workflow:

https://github.com/gravitational/teleport.e/blob/f64397a5610b2bde64f8598fc9b4ed43f5065f42/.github/workflows/oci-image-promote.yml#L86-L94

For more info, please see:

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#updating-your-github-actions-workflow

Let me know if you have further questions.

**Comment by zmb3** [comment]
@r0mant we're good to close this one, right?
