### ISSUE TITLE
Add New Two Factor modal closes when validation fails.

### ISSUE THREAD

**Issue by hatched** [gravitational/teleport#23073]
<img width="566" alt="Screenshot 2023-03-14 at 1 11 56 PM" src="https://user-images.githubusercontent.com/532033/225112437-ae32bb18-9226-49a9-a4fb-e620be61532d.png">

If you submit this form without adding a name, it'll show a validation error on the name input and then the modal will close. It should not close when validation fails.

**Comment by zmb3** [comment]
<img width="725" alt="image" src="https://github.com/gravitational/teleport/assets/7527103/41be5443-75c3-4bcd-9457-a488ff863c0c">

This is no longer the case.
