### ISSUE TITLE
Enable/disable displaying multiple auth methods in UI

### ISSUE THREAD

**Issue by BennettKnapek** [gravitational/teleport#23076]
*What would you like Teleport to do?*
We would like to have the ability to enable or disable an auth method on the landing page of the UI. If I have both a SAML auth connector and a OIDC auth connector configured, there should be an option to only allow one to be used at a time. 
The second one could possible be greyed out and only enabled if the first connector stops working. 

*What problem does this solve?*
Increases the simplicity of a break-glass solution while limiting that break-glass accessibility during normal operations. 
During break-glass, users would only have to login through the 2nd auth connector. The actions here would be auditable as well. 

*If a workaround exists, please include it.*
No workaround.

**Comment by zmb3** [comment]
Tracking this at #11578
