### ISSUE TITLE
Ordered ouptut when running tsh ssh comand against multiple nodes

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#23108]
What would you like Teleport to do?
When `tsh ssh` command is executed against multiple nodes, it results in an unordered output thereby making it difficult to identify which node gave which output. e.g:
 
```
$ tsh ssh root@stack=stacka date
WARNING: Multiple nodes matched label selector, running command on all.
Running command on 72b0681f-e2dc-4b8c-96cf-0a25c632d9e7:
Running command on f8e6957b-b1b2-423d-8e2a-9c7dcf616c69:
Running command on 491e09e4-7ef4-4d4e-8a47-9e9b67d13c1a:
Running command on 2dd3a3f3-90b3-483d-b6f5-9b32d1c594c6:
Running command on 18b98ee0b-6f5e-42a8-a8f9-9e77c00d040e
Mon Mar 13 19:59:01 UTC 2023
Mon Mar 13 19:59:02 UTC 2023
Mon Mar 13 19:59:01 UTC 2023
Mon Mar 13 19:59:02 UTC 2023
Mon Mar 13 19:59:02 UTC 2023
```

It would be worth having the id/node name info before each output or a more ordered output such that the nodes are easily identifiable against their corresponding output.

What problem does this solve?
easy identification of nodes against their output

If a workaround exists, please include it.
N/A

**Comment by zmb3** [comment]
@atburke fixed this in #33429
