### ISSUE TITLE
Open a non-ssl port up on your dockerfile for non-TLS reverse proxy based setups

### ISSUE THREAD

**Issue by sokoow** [gravitational/teleport#2310]
Open a non-ssl port up on your dockerfile for non-TLS reverse proxy based setups please:

https://github.com/gravitational/teleport/blob/ec7e53370df2d80f409da8ebfbeaeb8a18e8947b/docker/Dockerfile#L24

**Comment by webvictim** [comment]
The port will be the same whether you use TLS or not - it's the command line that decides whether TLS is enabled or not. Teleport doesn't support listening in both TLS and non-TLS modes simultaneously.

If you want to run without TLS enabled for testing purposes, you can start Teleport with `teleport start --insecure-no-tls`. A modification to the `Dockerfile` should allow this.
