### ISSUE TITLE
add windows desktop role to teleport-kube-agent chart

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#23111]
### What would you like Teleport to do?

Add support for the windows desktop service to the teleport-kube-agent chart

### What problem does this solve?

This would allow users to run the windows service via the chart, similar to how they can deploy a database, kube, or app access agent via the chart

### If a workaround exists, please include it.

fork the chart or use a different deploy method

**Comment by zmb3** [comment]
Duplicate of #15956 and #22402.
