### ISSUE TITLE
Cannot Copy And Paste texts over 128 letters on GUI

### ISSUE THREAD

**Issue by ken5scal** [gravitational/teleport#2313]
**What happened**:
Teleport GUI will not allow to paste textrs with more than 128 char length on GUI.
It will round the texts to 128 lengths.

![oct-24-2018 15-29-21](https://user-images.githubusercontent.com/9734362/47410740-ad2e4f80-d7a1-11e8-9dcc-2a6ff170bf63.gif)

This won't happen in CLI.

**What you expected to happen**:

Paste entire letters.

**How to reproduce it (as minimally and precisely as possible)**:

Copy and paste texts with length with more than 128 letters.

**Environment**:
- Teleport version (use `teleport version`): Teleport Enterprise v3.0.1 git:v3.0.1-0-g4ff9a7b0
- Tsh version (use `tsh version`): Teleport v3.0.1 git:v3.0.1-0-g4ff9a7b0
- OS (e.g. from /etc/os-release): amazon-linux2

**Browser environment**

- Browser Version (for UI-related issues):　Version 69.0.3497.100 (Official Build) (64-bit)
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by LuRenJiasWorld** [comment]
Yes, mine has the same problem.
It really bring some inconvenient.
