### ISSUE TITLE
Machine ID Telemetry INFO log url is a placeholder

### ISSUE THREAD

**Issue by dumez-k** [gravitational/teleport#23147]
Expected behavior:
When `Anonymous Telemetry` is enabled an INFO level log message will tell you where to learn more about the telemetry collection with a proper url.

Current behavior:
Right now the log message prints out:
```INFO [TBOT]      Anonymous telemetry is enabled. Find out more about Machine ID’s anonymous telemetry at [example.com/placeholder](http://example.com/placeholder) tbot/anonymous_telemetry.go:86```

Bug details:
- Teleport version: 12.1.0
- Recreation steps:
In the github action `teleport-actions/auth-k8s@v1` set the paramater `anonymous-telemetry` value to `1`. Run the action. (I assume this is not action specific and is just TBOT in general, but this is how I got the bug initially)
- Debug logs
```INFO [TBOT]      Anonymous telemetry is enabled. Find out more about Machine ID’s anonymous telemetry at [example.com/placeholder](http://example.com/placeholder) tbot/anonymous_telemetry.go:86```

**Comment by benarent** [comment]
fyi @strideynet

**Comment by strideynet** [comment]
Already fixed in https://github.com/gravitational/teleport/pull/22773 . Just waiting for the next release. Thanks for raising this.

**Comment by strideynet** [comment]
I can confirm this fix shipped in 12.1.1
