### ISSUE TITLE
successful `tsh login` won't return back to terminal from browser

### ISSUE THREAD

**Issue by ken5scal** [gravitational/teleport#2314]
**What happened**:

When you `tsh login --proxy=bastion.example.com:443` is executed while SAML authN is enabled, the login is redirected to browser. When the authentication is successful, the transaction has been returned  to the terminal and the process exits with 0 until ver2.7. But from ver3.0.1, it won't returned back to the terminal

```
[ksuzuki@A-M-201711-003] ~/workspace
% tsh login --proxy=bastion.example.com:443
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:49961/1a111111-1111-11a1-aa1a-1a1111a1111
```

This unable of using '--out' to save private key because the tsh login won't exit.

**What you expected to happen**:
same behavior as v2.8

**How to reproduce it (as minimally and precisely as possible)**:

upgrade Auth, Proxy to 3.0.1.
upgrade client teleport version to v3.0.0

**Environment**:
- Teleport version (use `teleport version`): Teleport v3.0.0
- Tsh version (use `tsh version`): Teleport v3.0.0
- OS (e.g. from /etc/os-release): MacOS SIerra

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by russjones** [comment]
Discussed this with @ken5scal offline. The issue was the web and SSH proxy endpoints. This was not supported in Teleport 2.8 but in 3.0 is now supported with the following config.

```
proxy:
   public_addr: web.example.com:443
   ssh_public_addr: ssh.example.com:3023
```
