### ISSUE TITLE
Document how to deploy the SSH Service in a Kubernetes environment

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#23145]
## Applies To

We'll need to find a good place for this. We have our Helm deployment guides in `docs/deploy-a-cluster/helm-deployments`, but users might also look for these kinds of instructions in `docs/server-access`.

## Details

Add some brief text about how we don't recommend the use of a daemonset to deploy the SSH Service and, instead, recommend installing the SSH Service directly on worker nodes. 

CC @webvictim

**Comment by webvictim** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/ gives good context on how to build your own AMI to use on EKS.
