### ISSUE TITLE
sudo -s returns error: No proxy address specified, missed --proxy flag?

### ISSUE THREAD

**Issue by tbjornli** [gravitational/teleport#2315]
I'm receiving an error message when executing `sudo -s`

```
tomtom@laptop $ ssh ubuntu@server.tld
ubuntu@ip-10-0-0-63:~$ tsh ssh localhost
ubuntu@ip-10-0-0-63:~$ sudo -s
error: No proxy address specified, missed --proxy flag?
root@ip-10-0-0-63:~#
```

Is there a way to automatically log all incoming ssh connections without having to run 
`tsh ssh localhost` when logged into the server?

**Environment:**
Ubuntu 18.04
Teleport v3.0.1

**Comment by aberoham** [comment]
Hi Tom, generally folks would run teleport in proxy mode on a "bastion" or "jump server" that remains hidden and then would run `tsh` directly from their laptop to connect thru that teleport-proxy to a teleport target running in node agent mode. 

Perhaps there is a specific concern or something missing within the quickstart documentation that could make this more clear? -- https://gravitational.com/teleport/docs/quickstart/
