### ISSUE TITLE
A user can't connect with another saml connector

### ISSUE THREAD

**Issue by slallema** [gravitational/teleport#2316]
**What happened**:
When logging with a SAML connector different to the one the user was created with, I get the following error:
`user %q already exists and is not SAML user, remove local user and try again.`
I'm trying to do this because my company is switching identity providers.

**What you expected to happen**:
The user should be able to login from different connectors

**How to reproduce it (as minimally and precisely as possible)**:
Create a SAML connector, log in
Create another SAML connector and try to log in with the same username, it fails.

**Environment**:
- Teleport version : 2.7.6

This check can probably be done differently to allow multiple saml providers that contain the same users:
https://github.com/gravitational/teleport/blob/97074076cb048606a4d3042c89b94d072956fba7/lib/auth/saml.go#L155

**Comment by kontsevoy** [comment]
@klizhentas let's discuss. Adding to 3.1 for now.

**Comment by aberoham** [comment]
I encounter this myself when I try to demo a single Teleport cluster configured to authenticate against multiple distinct identity providers -- eg, only the first unique account identifier (from any identity source) saved into Teleports internal DB will work, any additional logins using same unique identifier will conflict with the login process erring out as an unintuitive failure. Related, if you have multiple distinct sources of identity and swap them in/out, there's not a reliable way to go back in time and see which precise connector+identity a given Teleport yaml log entry belongs to.

**Comment by klizhentas** [comment]
We already track that there is conflict on a sign up if there is a similar user created by different connector. Right now we simply reject the user, but we should delete the old user and recreate a new one with new roles.

Sending this to @russjones to take care of.

**Comment by aberoham** [comment]
Not as simple as making the name of the connector part of the user record so that there won't be conflicts? The question of support for multiple auth providers does come up quite a lot. A similar glitch that folks hit is having a "backup" internal auth=local username that conflicts with same username from SSO.

**Comment by klizhentas** [comment]
I like prefix solution less because it will make it very confusing in the various logs, including OpenSSH and our audit logs, preferably users have one identity regardless of the identity provider of choice, with this solution this will be impossible.
