### ISSUE TITLE
Export GitHub Actions test metrics to Prometheus

### ISSUE THREAD

**Issue by wadells** [gravitational/teleport#23206]
We want to ship Teleport's GitHub Actions test metrics to Prometheus.

A draft PR is available at https://github.com/gravitational/teleport/pull/19942, we just need to help @gzigzigzeo out with a buddy merge.

**Comment by zmb3** [comment]
I haven't heard anything about this in a long time. Do we still want to do this or can we close it out as not planned?

**Comment by wadells** [comment]
I think we can close it not planned.  Cloud scrapped their plans to ingest GHA metrics in grafana, as described here: 

https://github.com/gravitational/cloud/pull/5741#issuecomment-1687098254
