### ISSUE TITLE
Mark Role spec options that are enterprise only

### ISSUE THREAD

**Issue by MarkCupitt** [gravitational/teleport#23219]
## Details
Describe the documentation improvements you wish to see.
THe Full Role Spec should note that these fields are for the enterprise version only

ERROR: role option request_access: reason is only available in enterprise subscriptions
ERROR: role option max_sessions is only available in enterprise subscriptions
ERROR: role option pin_source_ip is only available in enterprise subscriptions

**Comment by zmb3** [comment]
Looking at https://goteleport.com/docs/access-controls/reference/:

- [x] `request_access` is already marked enterprise only
- [x] `pin_source_ip` is already marked enterprise only
- [ ] `max_sessions` is not marked enterprise only
