### ISSUE TITLE
[Web UI] Web UI attempts to join moderated sessions using the OS user of the session creator

### ISSUE THREAD

**Issue by rudream** [gravitational/teleport#23238]
#### Expected behavior:

When joining a moderated session, the login used to connect should be the `-teleport-internal-join` OS user. The joiner should not need access to the login user of the session creator.

#### Current behavior:

The login being used to join/connect to the session is the login of the session creator, which the joiner might not have access to, which results in an `Access Denied`.

#### Bug details:
- Teleport version: `v13`, `v12`, `v11`

**Comment by zmb3** [comment]
This happens in v12 too, right?
