### ISSUE TITLE
Request for option to disallow joining session by other users

### ISSUE THREAD

**Issue by feicipet** [gravitational/teleport#2324]
**What happened**: When I have an active TSH session to a server, others can see my session in the web UI and join in arbitrarily. This has caused problems where, if the session is started by me, the session recording is 100% attributed myself. However, another person who is logged in (as another user), can just browse the sessions page, see my active session, click on "Join" and then proceed to do any sorts of mischief. Once he logs out, all his actions would be attributed to me and if would be very difficult for me to prove otherwise because the session recording does not show that the other user had done anything. This is effectively equivalent to a session hijacking.

**What you expected to happen**: While being able to allow others to join a session is a good thing, it should be an explicit action by myself to share my session ID to others so that I (the session owner) am in control. The sessions page in the web UI should only show my own sessions and not sessions started by other users by default.

**How to reproduce it (as minimally and precisely as possible)**: Create 2 users and have user A start a session. While user A is still logged in, have user B sign on to the web app and open the Sessions page. He will be able to see user A's session there and join it.

**Environment**:
- Teleport version (use `teleport version`): 3.0.1
- Tsh version (use `tsh version`): 3.0.1
- OS (e.g. from /etc/os-release): 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"

**Browser environment**

- Browser Version (for UI-related issues): Chrome
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by klizhentas** [comment]
that's fair. The simplest workaround is to set teleport proxy to recording mode, in this mode sessions can not be joined.

**Comment by aberoham** [comment]
Hi Wong, If you are using Teleport within an environment where UserA doesn't trust UserB, such as an enterprise subject to audit and controls, another workaround would be to license the Teleport Enterprise offering which includes role based access control (eg the ability to have more than just a single 'admin' role). That "RBAC for SSH" solution is documented here: https://gravitational.com/teleport/docs/ssh_rbac/#roles and licenses are available via a self-serve purchase flow, Amazon marketplace AMIs, traditional procurement process, etc.

The documentation for recording proxy mode (which implicitly disables session sharing by nature of how it changes teleport-proxy's operating internals) is at https://gravitational.com/teleport/docs/admin-guide/#recording-proxy-mode

If you'd like a free trial of Enterprise or want to discuss your use case privately please reach out.

**Comment by feicipet** [comment]
Thanks @aberoham @klizhentas 

We just started using Teleport and I will have to show the value of the tool to my bosses in order to get a budget for implementing the Enterprise edition. Will do that first and then contact your sales team if / when I get clearance.

In the meantime, I also found a workaround to identify anybody who had joined somebody else's session by using filebeat to pull in audit logs into an ELK cluster. By identifying session.join events, I would be able identify who joined what session and at least I would know that anything done in that particular session would be attributable to both the owner and the session joiner. Hope that helps anyone who is facing a similar concern.

**Comment by zmb3** [comment]
This has been resolved with moderated sessions. The default mode for joining SSH sessions is still "peer" to preserve backwards compatibility, but you can set it to "observer" - which prevents the person who joined the session from taking any actions (their stdin is never connected to the session).


https://goteleport.com/docs/access-controls/guides/moderated-sessions/?scope=enterprise#participant-modes
