### ISSUE TITLE
Machine ID: Support generating certificates with RouteToCluster for direct access to leaf cluster

### ISSUE THREAD

**Issue by anurag-work** [gravitational/teleport#23249]
## What would you like Teleport to do?
Tbot should pull leaf cluster public certificates too .
This is similar to when you run
```
tsh login leaf-cluster
```
## What problem does this solve?
When accessing leaf cluster ssh nodes, we can skip communicating to the root cluster proxy.

The below works but tsh proxy usage forces communication with the leaf proxy
```
ssh  -F /dev/null
-o IdentityFile=root-key
-o CertificateFile=root-cert.pub
-o UserKnownHostsFile=/dev/null
-o ProxyCommand="tsh  -i root-identity proxy ssh -J leaf-proxy:3080 --cluster=leaf-cluster --proxy=root-proxy:3080 %r@%h:%p"
root@leaf-ssh-vm -p 3022
```

Instead I want to use 
```
ssh  -F /dev/null 
-o IdentityFile=root-key
-o CertificateFile=leaf-cert.pub 
-o ProxyCommand="ssh -F /dev/null 
    -o IdentityFile=root-identity 
    -o CertificateFile=leaf-cert.pub 
    %r@leaf-proxy -p 3023 -W %h:%p" 
 
root@leaf-ssh-vm -p 3022
```

AFAIK, leaf-cert.pub  can not be generated by tbot.

This works when using tsh generated certs as the below creates the leaf-cert.pub file 
```
 tsh login leaf-cluster
 ```
## If a workaround exists, please include it.

**Comment by strideynet** [comment]
Relevant RFD for initial introduction of direct routing through a leaf cluster: https://github.com/gravitational/teleport/blob/master/rfd/0021-cluster-routing.md

Open questions:
- Is route to cluster mutually exclusive to route to app/db/kubernetes (e.g only for SSH) ? Or is it usually combined with these to allow directly communicating with those types of resources in those clusters?
- Should this affect `ssh_config` generation and introduce the jump flag ?

Suggested configuration:

```yaml
destinations:
    - directory:
          path: /opt/machine-id
      roles: ["blah"]
      cluster: "cluster-i-want-direct-credentials-for"
```

**Comment by strideynet** [comment]
For now, this work will target exclusively SSH, but this can be adjusted in future to work with the other protocols.

**Comment by zmb3** [comment]
@strideynet good to close this?
