### ISSUE TITLE
Add support for AWS Managed AD to Desktop access automatic setup script

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#23251]
**What would you like Teleport to do?**

The [desktop access automatic setup scripts](https://github.com/gravitational/teleport/tree/master/lib/web/scripts/desktop) are great and work well in a self-hosted AD environment. Unfortunately, they do not support AWS Managed AD which a number of customers are using. This means they have to follow the [manual setup guide](https://goteleport.com/docs/desktop-access/active-directory-manual/) instead which slows them down.

Desktop access works fully with AWS Managed AD, it's just two things that need to be done differently:

- When using AWS Managed Active Directory, AWS Delegated Domain Administrator accounts are not granted permissions to apply GPOs at the domain level. Instead, you should apply this GPO to the automatically-created OU with the NetBIOS domain name containing Computers and Users which is nested one level beneath the domain root.

![image](https://user-images.githubusercontent.com/897821/225986444-ed4cf8de-e908-4828-942e-fcd6a2939cbb.png)

- When using AWS Managed Active Directory, the Teleport CA needs to be published to the domain using an account which is part of the AWS Delegated Domain Administrators group, such as the AWS-provided `admin` account.

**What problem does this solve?**

These two simple fixes would make onboarding in AWS Managed AD environments much simpler.

**If a workaround exists, please include it.**

Follow the manual docs, which increases time taken.

**Comment by zmb3** [comment]
These installation scripts make too many assumptions that don't hold true in enterprise environments, so they are being deprecated as of Teleport 16.
