### ISSUE TITLE
Teleport Lab issue

### ISSUE THREAD

**Issue by mbssecguy58** [gravitational/teleport#23256]
I created a user in the Teleport Lab container and was given an invite link to complete the process which is valid for one hour. When i clicked the link to bring up the site, I was prompt to click an icon to proceed. After clicking the icon the following error message appeared. Please see attachment. 
![Selection_001](https://user-images.githubusercontent.com/31019283/226002917-5fd03166-f517-459b-881c-98d83df56b61.png)

**Comment by benarent** [comment]
Thanks for reporting. Which lab was this? Server, Kubernetes, Database or Machine ID

**Comment by mbssecguy58** [comment]
My oligopolies I figured it out but forgot to cancel this ticket. Sorry about that...
