### ISSUE TITLE
Active Directory script / remove

### ISSUE THREAD

**Issue by veltbf** [gravitational/teleport#23307]
Dear all

I tried to add a Windows desktop to Teleport. We already have an AD including AD certificates, so I skipped this step. 

After that, I ran the script on the domain controller.

(Invoke-WebRequest -Uri https://teleport.xxx.xxx:3080/v1/webapi/scripts/desktop-access/configure/053951c4a41263079e25328ed5cad081/configure-ad.ps1).Content | Invoke-Expression

This ran for a while, but in the end it did not output the desired config output.

`version: v3
teleport...`

When I run the script again, I get the message:

_New-ADUser : The specified account already exists
At line:45 char:1
New-ADUser -Name $AD_USER_NAME -SamAccountName $SAM_ACCOUNT_NAME -Acc ...
    CategoryInfo          : ResourceExists: (CN=Teleport Ser...=XXX,DC=local:String) [New-ADUser], ADIdentityAlreadyExistsException
    FullyQualifiedErrorId : ActiveDirectoryServer:1316,Microsoft.ActiveDirectory.Management.Commands.NewADUser_

Is there any way to remove everything from domain and run again the script from the beginning?

Thank you and best regards

**Comment by zmb3** [comment]
We recently made some changes to make the setup script more idempotent. In the meantime, you may find the manual setup guide helpful: https://goteleport.com/docs/desktop-access/active-directory-manual/

**Comment by oscar-vlugt** [comment]
I get the same error when running with seperate domain controllers and certificate services:

```
CertUtil: No local Certification Authority; use -config option
CertUtil: No more data is available.
DecodeFile returned The system cannot find the file specified. 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: -encode command FAILED: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
Updating policy...

Computer Policy update has completed successfully.
User Policy update has completed successfully.

Get-Content : Cannot find path 'C:\Users\XXX\AppData\Local\Temp\windows.pem' because it does not exist.
At line:178 char:16
+ $CA_CERT_PEM = Get-Content -Path $WindowsPEMFile
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ADMINO...emp\windows.pem:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```

**Comment by zmb3** [comment]
These installation scripts make too many assumptions that don't hold true in enterprise environments, so they are being deprecated as of Teleport 16.
