### ISSUE TITLE
tctl top should should show error when diagnostic metrics not available

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#23312]
Expected behavior:

If `tctl top` cannot reach the diagnostic port should give an error to that effect.

Current behavior:

Generic error below if running remotely or on an instance that doesn't have metrics available.

```bash
ERROR: text format parsing error in line 1: invalid metric name
```

Bug details:
- Teleport version: 12.1.1
- Recreation steps

Start `teleport` without having the diagnostic metrics on.
Run `tctl top` on the same machine.

OR

Attempt to use remotely when diagnostic metrics are enabled.
`tsh login`
`tctl top`

**Comment by zmb3** [comment]
I'm not able to reproduce the "text format parsing error":

```
➜ tctl top
ERROR: [CLIENT] Could not connect to metrics service at http://127.0.0.1:3000. Is teleport running with --diag-addr=http://127.0.0.1:3000?

❯ tctl top localhost:12345
ERROR: [CLIENT] Could not connect to metrics service at localhost:12345. Is teleport running with --diag-addr=localhost:12345?
```
