### ISSUE TITLE
Add footnote to SSO connector updates 

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#23349]
## Applies To
Access request with Slack documentation [step 3/8](https://goteleport.com/docs/access-controls/access-request-plugins/ssh-approval-slack/#step-38-create-a-user-and-role-for-the-plugin). 

## Details
We need to add a footnote explaining to customers updating their SSO connector with additional attributes via the CLI to use the `--with-secrets` flag to obtain the whole auth connector configuration file. If they don't pass this flag they will obtain a configuration file without the private_key, thus causing the connector to update without a private key. Resulting in user loss of access. 
```
e.g. 
# sudo tctl get saml/azure-saml --with-secrets > saml.yaml
```
## Related Issues
We had an S1 issue due to this. SF# 16414

**Comment by r0mant** [comment]
Fixed in https://github.com/gravitational/teleport/pull/23337.
