### ISSUE TITLE
Add port forwarding to the audit log

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2337]
## User Question

When using ssh tunnels, for example “tsh shh -L 3389:10.0.0.0:3389 hostname” – is there anyway this can be captured in the audit logs? At the minute all I see is the session start entry, but nothing about the variables passed such as the port forwarding:

 
```
{                                                         
  "addr.local": "127.0.0.1:3022",                         
  "addr.remote": "127.0.0.1:37128",                       
  "ei": 0,                                                
  "event": "session.start",                               
  "login": "bob",                                
  "namespace": "default",                                 
  "server_id": "b93e9830-97f9-42b0-9fbb-9a30208d3189",    
  "sid": "7596ae06-ddeb-11e8-8f06-005056362386",          
  "size": "213:51",                                       
  "time": "2018-11-01T15:33:19.487Z",                     
  "user": "bob.jones"                                  
}          
```
 
## Proposal

Let's add `forwarded_ports` field to the `session.start` event, which should be an array. And since we're doing this, let's look into adding a boolean `terminal` field ("yes" means "allocate")

**Comment by klizhentas** [comment]
afaik, it's already implemented and teams alert on forwarded ports

**Comment by kontsevoy** [comment]
Update:

The port forwarding is sent to the server when a connection to the forwarded port is attempted, i.e. the audit log entry is added NOT during `tsh ssh -L` but later.
