### ISSUE TITLE
Enable Configure Active Dir Script to support separate DC and CS machines

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#23401]
What would you like Teleport to do?

Provide a method of running portions of the script on the Domain controller and others on a Certificate Services enabled windows machine. 

What problem does this solve?

In some scenarios a client might be running the Certificate Services separate from their Domain controllers.  That causes having to use the manual steps instead of the script.

If a workaround exists, please include it.

Manual setup

**Comment by zmb3** [comment]
These installation scripts make too many assumptions that don't hold true in enterprise environments, so they are being deprecated as of Teleport 16.
