### ISSUE TITLE
Include Helm option for MS Teams Plugin Docs

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#23426]
## Applies To
https://github.com/gravitational/teleport/pull/new/stevenGravy/docs/msteamsplugin

## Details
Include the helm chart option like the pagerduty plugin docs have

**Comment by ptgott** [comment]
Related: Give Kubernetes-based deployments more prominence in how-to guides (#15043)

**Comment by ptgott** [comment]
Fixed in https://github.com/gravitational/teleport/commit/322cb2d026a7dd0fe7f4e80d804dd525885366fb
