### ISSUE TITLE
BootstrapResources is not compatible with `tctl get all` (*types.ProvisionTokenV2)

### ISSUE THREAD

**Issue by Tamahome-M** [gravitational/teleport#23422]
Export dynamic configuration state from old cluster
`tctl get all --with-secrets > state.yaml `
bootstrap fresh server (kill the old one first!)
`teleport start --config fresh.yaml --bootstrap state.yaml `
```
2023-03-22T12:58:18+03:00 INFO [AUTH]      Applying 53 bootstrap resources (first initialization) auth/init.go:251
ERROR: backend bootstrap failed
initialization failed
cannot itemFrom resource of type *types.ProvisionTokenV2
```
Teleport v12.1.1 git:api/v12.1.1-0-gb9ee483 go1.19.7

**Comment by strideynet** [comment]
Taking a look at the code here, I can see that `lib/services/local/resource.go.CreateResources()` does not support the same set of resources that `tctl get all` does. Essentially meaning this affects more than just Token resources.

For now, I'm going to go ahead and produce a patch to fix this for the most important Resources that I imagine this bug affects. I imagine it'll make sense for us to reconsider at some point the difference between `BootstrapResources` and `ApplyOnStartupResources` and whether we could produce some kind of ResourceRegistry to prevent these parts of the codebase diverging again.
