### ISSUE TITLE
Support login rules for the SAML IdP

### ISSUE THREAD

**Issue by mdwn** [gravitational/teleport#23433]
What would you like Teleport to do?

The SAML IdP should support login rules so that assertions can be customized.

What problem does this solve?

Allows users to customize assertions and thus customize SAML IdP access.

**Comment by flyinghermit** [comment]
@mdwn I think this ticket can be closed now as we addressed the issue with attribute mapping? 

https://goteleport.com/docs/access-controls/idps/saml-attribute-mapping/

**Comment by mdwn** [comment]
Agreed!
