### ISSUE TITLE
Better UX when adding MFA

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#23443]
Expected behavior:

Provide an error that no existing Hardware Key exists. Also pre-select the Authenticator App if that's all they have.

Current behavior:

If a user has no Hardware key they get a generic error but no information that they don't have a hardware key.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/60704961/226950436-7971b5bd-c9d8-4b1a-8642-be9e875416dd.png">

Bug details:
- Teleport version: 12.1.1
- Recreation steps:

1. Register a user with Authenticator App
2. Go to add another device and press continue when Hardware Key selected

**Comment by zmb3** [comment]
@codingllama did we address this with your recent error message changes?

**Comment by zmb3** [comment]
@bl-nero let's see if we can fix this as part of #36232 (disable MFA options if the user doesn't have any such devices)

**Comment by codingllama** [comment]
My 2c: I would start double-checking if the frontend is swallowing the error message. The backend often sends appropriate error messages for cases like this.
