### ISSUE TITLE
"Configure Teleport to Automatically Enroll EC2 instances"feature error

### ISSUE THREAD

**Issue by Camaine** [gravitational/teleport#23441]
Expected behavior:
Discover not enrolled ec2 node and enroll it to proxy server

Current behavior:
In Discover step, IAM Policy related error occured.

 aws cli which is describe ec2 instance is working.

Current Policy Setting

    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:GetPolicy",
                "iam:TagPolicy",
                "iam:ListPolicyVersions",
                "iam:CreatePolicyVersion",
                "iam:CreatePolicy",
                "ssm:CreateDocument",
                "iam:DeletePolicyVersion",
                "iam:AttachRolePolicy",
                "iam:PutRolePermissionsBoundary"
            ],
            "Resource": "*"
        }
    ]

Bug details:
- Teleport version
12.1.1

- Recreation steps
I followed this docs step.
https://goteleport.com/docs/server-access/guides/ec2-discovery/?scope=enterprise#troubleshooting

- Debug logs

Error log below

    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: 2023-03-22T14:31:34Z ERROR            
    Failed to fetch instances error:[
    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: ERROR REPORT:   
    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: Original Error: *trace.AccessDeniedError 
    UnauthorizedOperation: You are not authorized to perform this operation.
    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: status code: 403, request id: e7dcd064-0ddc-4af3-be0c-a882aa957dac
    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: Stack Trace:
    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: github.com/gravitational/teleport/lib/cloud/aws/errors.go:39 github.com/gravitational/teleport/lib/cloud/aws.ConvertRequestFailureError
    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: github.com/gravitational/teleport/lib/srv/db/common/errors.go:63 github.com/gravitational/teleport/lib/srv/db/common.ConvertError
    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: github.com/gravitational/teleport/lib/srv/server/ec2_watcher.go:176 github.com/gravitational/teleport/lib/srv/server.(*ec2InstanceFetcher).GetInstances
    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: github.com/gravitational/teleport/lib/srv/server/watcher.go:56 github.com/gravitational/teleport/lib/srv/server.(*Watcher).Run
    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: runtime/asm_amd64.s:1598 runtime.goexit
    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: User Message: UnauthorizedOperation: You are not authorized to perform this operation.
    Mar 22 14:31:34 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: status code: 403, request id: e7dcd064-0ddc-4af3-be0c-a882aa957dac] server/watcher.go:61
    Mar 22 14:31:59 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: 2023-03-22T14:31:59Z DEBU             Attempting GET kimjuwon1.teleport.sh:443/webapi/find webclient/webclient.go:129
    Mar 22 14:31:59 ip-10-0-15-215.ap-northeast-2.compute.internal teleport[9239]: 2023-03-22T14:31:59Z DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:301

**Comment by zmb3** [comment]
Your IAM policy is missing `DescribeInstances`
