### ISSUE TITLE
In teleport-kube-agent guides check if the agent pods are up and healthy

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#23449]
## Applies To

- https://goteleport.com/docs/kubernetes-access/register-clusters/register-via-deployment/
- https://goteleport.com/docs/kubernetes-access/register-clusters/iam-joining/ ([might not be merged yet](https://github.com/gravitational/teleport/pull/22978))

## Details

As discussed in https://github.com/gravitational/teleport/pull/22978#discussion_r1145024682 we might want to check if the pods are running and ready before trying to access the agent through Teleport. Users will fail faster in case of pod error, and we can rule out RBAC errors. Users will also be able to perform basic troubleshooting like checking the pod logs, checking the pod can start, and looking at its Kubernetes events.

**Comment by ptgott** [comment]
All the pages that mention `teleport-kube-agent`:

```
$ grep -Rl "\$ helm.*teleport-kube-agent" docs/pages
docs/pages/database-access/guides/oracle-self-hosted.mdx
docs/pages/database-access/guides/rds.mdx
docs/pages/kubernetes-access/manage-access/rbac.mdx
docs/pages/kubernetes-access/getting-started.mdx
docs/pages/kubernetes-access/controls.mdx
docs/pages/kubernetes-access/troubleshooting.mdx
docs/pages/kubernetes-access/register-clusters/iam-joining.mdx
docs/pages/includes/database-access/db-helm-install.mdx
docs/pages/management/admin/uninstall-teleport.mdx
docs/pages/agents/join-services-to-your-cluster/kubernetes.mdx
docs/pages/api/rbac.mdx
docs/pages/application-access/getting-started.mdx
```
