### ISSUE TITLE
Feature Request: Automate creation of resources

### ISSUE THREAD

**Issue by darend** [gravitational/teleport#2347]
Problem:
When deploying Teleport auth/proxy under Kubernetes it would be ideal to be able to automate the provisioning of [resources](https://gravitational.com/teleport/docs/admin-guide/#resources) such as roles and saml.  The existing tooling requires using the UI, or exec'ing into the auth container in order to use the local tctl command.

Proposal:
Allow a directory to specified when starting the auth service that contains resource manifests. Any manifests found will be imported.

**Comment by benarent** [comment]
Hi @darend , This is now possible using Teleports Bootstrap flag. We've outline a few of the details here https://gravitational.com/teleport/docs/admin-guide/#migrating-backends . Please ping me if you have any more questions.
