### ISSUE TITLE
Reduce installation size

### ISSUE THREAD

**Issue by Gunni** [gravitational/teleport#23511]
# What would you like Teleport to do?
Currently installing teleport installs these binaries in `/usr/local/bin`

60M	tbot
102M	tctl
165M	teleport
104M	tsh

Would it be possible to reduce their size and or not install the ones not needed for nodes?

# What problem does this solve?
Installation size of Teleport is a significant size of the entire system.

# If a workaround exists, please include it.
N/A

**Comment by zmb3** [comment]
On nodes you can safely remove everything but Teleport.

Other than that, not much you can do without hacking up the source code. See also #8735

**Comment by Gunni** [comment]
Closing this as duplicate of https://github.com/gravitational/teleport/issues/8735.
