### ISSUE TITLE
scp returns 1 when using with OpenSSH

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#23625]
Expected behavior:

scp should return 0 when a file transfer succeeds when OpenSSH server is used.

Current behavior:

As described here https://github.com/gravitational/teleport/issues/20863, file transfer returns 1 even when on success.

PR https://github.com/gravitational/teleport/pull/23626 fixes the case when Teleport is used as the server.

Bug details:
- Teleport version v10.1+
- Recreation steps
    Run sshd server and Teleport proxy
     run `scp` command to copy a file
    Check the error code
- Debug logs

**Comment by zmb3** [comment]
Fixed by #23626
