### ISSUE TITLE
Support for tcpip-forward

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#23627]
What would you like Teleport to do?

Teleport currently (v12) supports `direct-tcpip`, but not `tcpip-forward`. 

What problem does this solve?

Some tools (IDEs, for example) are using `tcpip-forward` to create a TCP connection to a remote server. Without support for it, Teleport won't work with some of those tools.

If a workaround exists, please include it.

No

**Comment by Joerger** [comment]
Added in v15 - https://github.com/gravitational/teleport/pull/38047
