### ISSUE TITLE
Add an auto-refresh option or notification on session recordings and audit logs

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#23692]
What would you like Teleport to do?

Either auto-refresh or show a box saying "new logs available" on the audit log page (or even "new sessions available" on the session recordings page).

What problem does this solve?

Right now with Teleport if you want to see new logs or recordings you have to hit the browser refresh to reload the page. This is not super user-friendly and with the advent of modern web frameworks, etc we should be able to have an inline notification that would load new logs or at least notify a user that there are new logs and recordings available.

If a workaround exists, please include it.

Not really. You have to manually hard refresh the browser to get newest logs or leave the audit logs area and go back to it.

**Comment by zmb3** [comment]
Closing as WONTFIX for now, there's just not much demand and working on this would have very low impact.
