### ISSUE TITLE
What happens to existing users when auth type is changed?

### ISSUE THREAD

**Issue by andrewbanchich** [gravitational/teleport#2370]
I couldn't find any documentation on what happens in this scenario. Do existing users get locked out of their accounts and have messages saying they need to use the new auth type? Or would I have to delete existing users and readd them in order for the new auth type to take affect on their accounts?

**Comment by klizhentas** [comment]
Your question has moved to [community forum](https://community.gravitational.com/t/what-happens-to-existing-users-when-auth-type-is-changed/33)
