### ISSUE TITLE
Compress the labels and show a single line of labels

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#23704]
It would be great to make the Labels on the UI compressed and show the important tags alone with a `Expand` or `more` button which shows all the tags. We can also have a mechanism or a feature to configure which labels are to be shown first. 

For example the teleport administrator user can configure a set of ~5 tags that all their end users care to show first 

Multiple labels on the UI make it hard for the user to read. Especially, when they import tags from AWS. Users mostly care about very few tags and the rest of them are just populated without any use in several cases. Here is the image below where we can see how much of inventory page space is taken when we have a lot of Labels. 

<img width="1411" alt="Screenshot 2023-03-27 at 15 50 58" src="https://user-images.githubusercontent.com/13088331/228319265-eaab8733-c504-4bb7-be71-0e95ce8db45a.png">

**Comment by zmb3** [comment]
This is solved by the unified resources view shipping in Teleport 14, so I'm going to call it complete.
