### ISSUE TITLE
Issue with EC2 Discovery on Teleport Enterprise

### ISSUE THREAD

**Issue by Camaine** [gravitational/teleport#23751]
## Applies To
[Configure Teleport to Automatically Enroll EC2 instances (Preview)]
https://goteleport.com/docs/server-access/guides/ec2-discovery/

## Details
This feature is doesn't work on enterprise version.

According this docs, users may misunderstand Enterprise version supports this feature.

You must add information about which version doesn't support this feature

## Related Issues

https://github.com/gravitational/teleport/issues/23441

**Comment by ptgott** [comment]
Would you mind adding some information about the issues you are facing in Teleport Enterprise? Thanks!

**Comment by ptgott** [comment]
Closing this issue since we don't have sufficient detail to address it. @Camaine once you can provide a description of the issues you are facing with setting up EC2 discovery on Teleport Enterprise, please feel free to reopen this issue.
