### ISSUE TITLE
Teleport web idle timeout not working

### ISSUE THREAD

**Issue by farru1998** [gravitational/teleport#23756]
Expected behaviour:
Upon configuring `web_idle_timeout = 12h` Teleport should keep the users logged in for 12 hours.
E.g. WebApp A logged in via teleport after 6 hours when accessing WebApp B it should stay logged in as we are still under the 12 hours session timeout period.

Current behaviour:
What is happening in actual is that WebApp A stays logged in and continue in the working state whereas when we try to login WebApp B  after 6 hours we are being redirected to the teleport login page and it seems that the session logged out however WebApp A is still accessible/logged in, also when we try to access teleport home page after 6 hours it redirects us to the login page which again is not the expected behaviour since we have a time out of 12 hours.

```yaml
auth:
  serviceAccount:
    create: true
  teleportConfig:
    auth_service:
      web_idle_timeout: 12h
```

Setup Details:
Teleport along with kube agent is deployed via helm chart on Amazon EKS.

Bug details:
- Teleport version = v12.1.1
- Teleport kube agent version = v12.1.1
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
`web_idle_timeout` is for Teleport web UI sessions. If the session TTL is less than that, application access sessions will be limited by the shorter TTL.

**Comment by farru1998** [comment]
@zmb3 In my case the applications are still accessible even though when the teleport web session has timed out that's not an expected behaviour I believe.
