### ISSUE TITLE
Device trust configurations not included in tctl get all

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#23775]
Expected behavior:

Device trust configurations are included with `tctl get all`.  Good if this can be included with #23765 so locks and devices are included.

Current behavior:

You have to call with `tctl get device` to get device configurations

Bug details:
- Teleport version: 12.1.2 enterprise
- Recreation steps

1. Enroll a device
2. Run `tctl get device` to retrieve the `kind: device` configurations.
3. Run `tctl get all` and check if the `kind: device` is included

**Comment by codingllama** [comment]
@xacrimon, mind taking this one?

**Comment by xacrimon** [comment]
@codingllama on it

**Comment by zmb3** [comment]
@sshahcodes this is probably something you could pick up soon since @xacrimon is on to other work now.
