### ISSUE TITLE
Teleport Connect not allowing MFA connections for DB Access

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#23782]
Expected behavior:

DB Access that requires MFAs would prompt at the proxy start and allow connections.

Current behavior:

No MFA prompt and db access attempts will fail.

Bug details:
- Teleport version: 12.1.2
- Recreation steps

1. Require MfA for a db access
2. Confirm working with `tsh db connect` with MFA.
3. Attempt to access the same db in Teleport Connect

**Comment by zmb3** [comment]
Duplicate of https://github.com/gravitational/teleport.e/issues/874
