### ISSUE TITLE
Proxy not connecting to trusted cluster when network changes

### ISSUE THREAD

**Issue by andrewbanchich** [gravitational/teleport#2379]
We are testing how resilient Teleport is in different scenarios and the only issue we've found so far is that if we set it up on a laptop and have it connect to a trusted cluster, then change from one wifi network to another, it doesn't work. The logs say it connected to the trusted cluster, it shows up in the Web UI clusters list, but the node is missing. We have to restart the teleport service on the node to get it working. 

**Environment**:
- Teleport version (use `teleport version`): 3.0.0
- Tsh version (use `tsh version`): 3.0.0
- OS (e.g. from /etc/os-release): Arch Linux

**Comment by benarent** [comment]
@andrewbanchich With Teleport 4.0 we introduced IoT Mode which should improve these network retries and setup. If you're still using Teleport please let us know if this will work for you. https://gravitational.com/blog/iot-security-teleport/
