### ISSUE TITLE
Add node labels to the audit log

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2380]
## Customer request

The reasonable expectation (especially in cloud environments where node IP or/and hostname do not mean much) is to include node labels to the audit log events, where applicable.

## Notes

* Make sure it works with recording proxy

**Comment by Zwordi** [comment]
Hi, 
I'm playing with Teleport and EFK and i'm looking forward to have the name or label of the node on the audit logs to improve the details of the logs.

Just my 2cents...

**Comment by benarent** [comment]
We had another feature request for this today.  After adding node/app/kubernetes labels, the customer plans to use these labels to filter who can see which sessions. e.g. 'dba-audit' role can only view sessions related the databases.

**Comment by russjones** [comment]
These are available in the `session.end` event if I am not mistaken.
