### ISSUE TITLE
Permit to choose the TOTP secret

### ISSUE THREAD

**Issue by Twister42** [gravitational/teleport#2385]
It would be to nice to be able to share the TOTP secrets between systems. You could add an option to tctl add in order to specify the secret.

The goal is to enable people using hardware tokens to avoid having multiples devices per users.

(My tokens has 2 authentications slots, one is for U2F, one for TOTP)

Warn : If implemented it has to override the "rotateAndFetchSignupToken" mechanism when a secret is specified.

**Comment by Twister42** [comment]
I've made a branch : https://github.com/Twister42/teleport/tree/feat-specific-otp-secret

Be gentle, it is quick and dirty, and it is my first time with Go ;)
It is just to show what I mean

**Comment by Twister42** [comment]
Hello, any insight about this ? Will it be done one day or never ?

Thx.

**Comment by brissenden** [comment]
We're interested in such feature too 👍

**Comment by zmb3** [comment]
See also #18289

**Comment by zmb3** [comment]
Closing this one as not planned - we are not investing any more time in TOTP and will likely deprecate it in a future release.
