### ISSUE TITLE
Add information on running Teleport in a Docker container

### ISSUE THREAD

**Issue by Mikebru10** [gravitational/teleport#23867]
## Applies To
https://goteleport.com/docs/try-out-teleport/linux-server/
https://goteleport.com/docs/installation/
https://goteleport.com/docs/management/guides/docker/

## Details
You are missing details about where/how to store certs/keys when running a docker container. I am self hosting Teleport Community in a Docker Container on my personal internal network and there seem to be little or no documents that describe this use case. I understand you are trying to write the documentation to account for many different use cases, but as a new user it's very confusing and very difficult to follow. I spent the better part of an entire day trying to get the docker run configured to a docker compose that would work, and get it deployed.Once I finally got feed up and just used the commands you offer in the documentation, I got the server up and then when I tried to connect my first host machine for management, I got an error from curl that it couldn't trust the server the url was pointing to in the Teleport bash script. Then I spend another 6 hours trying to either find a command that would force curl to over look the Self-signed cert on the teleport server or install the Let's Encrypt cert I got for the Teleport server. It would be great if if the web interface I could manage certs, upload and select the appropriate certs. You don't make it easy to you the documentation it's very confusing.  I am a Cisco CCNP Route/Switch and I am still very much struggling to navigate the documentation. The documentation assumes the user is very familiar with your documentation, there are like 12 pages to getting started or installation, every time I turned around I was looking at a different installation instruction that looked very similar to the last except for a new url and slightly different instructions. The instructions are very confusing to get started, there seem to be several places to get started, Home > Installation, Deploy a Cluster, Manage Your Cluster > Integrations. It's more than a little confusing, which instructions do you expect me to follow? I'm lost. Maybe that's the plan, make it so confusing people just sign up for the subscription, you make money from using open source software but you make your open source product so confusing no one will choose to go that route.   

In the Docker Compose instructions < https://goteleport.com/docs/try-out-teleport/docker-compose/ > it's a demo environment which can't easily be modified by a user, so that doesn't work. I can't begin to understand what would need to change to modify the lab compose config to modify it for a production environment. You don't have a listing of environment variables so I could possibly back into making this deployment workable.

This is the problem every time I try to deploy an Open Source project, they assume too much or they only care about making it work for paid subscriptions. No one likes subscriptions except for the software companies.

**Comment by ptgott** [comment]
Thanks for bringing up this issue, and I'm sorry you're having difficulties getting started with Teleport. We've merged a PR that helps simplify the Getting Started experience (https://github.com/gravitational/teleport/pull/25415, which will appear as the default docs version soon), and recommend referring to our Docker instructions on the Installation page (https://goteleport.com/docs/installation/#docker) for Docker setups. You can see the new approach on version 13.x of the docs site.

For any issues with the new approach, would you mind opening a new issue? Thanks!
