### ISSUE TITLE
Allow more granular configuration options for port forwarding

### ISSUE THREAD

**Issue by bric3** [gravitational/teleport#2386]
**What happened**:
Teleport only allow an all access port forward or nothing at all (if blocked).

```
sudo tsh ssh -L 80:dev-resource:80 --proxy=teleport.proxy.corp.com dev@machine
tsh ssh -L 1521:pord-db:80 --proxy=teleport.proxy.corp.com dev@machine
....
```

**What you expected to happen**:
It would be nice for admin to allow port forwarding but to restrict this to some hosts only.

**Environment**:
- Teleport version (use `teleport version`): v2.7.4
- Tsh version (use `tsh version`): `v2.7.4`
- OS (e.g. from /etc/os-release): `Mac OS X 10.14.1`

**Comment by russjones** [comment]
Closing this in favor of https://github.com/gravitational/teleport/issues/6783.
