### ISSUE TITLE
Fix curl command in Windows tsh client installation instructions

### ISSUE THREAD

**Issue by countz3r0** [gravitational/teleport#23887]
## Applies To

https://goteleport.com/docs/installation/#windows-tsh-client-only

## Details
Describe the documentation improvements you wish to see.
The curl command as written doesn't work as expected. The uppercase O doesn't require the filename argument. Only the lowercase o does. 

The documentation could be updated to either remove the filename so that the remote name is used, or  with the upper case O or switch to a lower case o and it will then work as well.

**Comment by nitish799** [comment]
i am intrested in fix this issue. can you assign me ?

**Comment by zmb3** [comment]
This has been fixed.
