### ISSUE TITLE
UI navigation redirects to root cluster resources when using Trusted Clusters

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#23894]
Expected behavior:

When using Trusted Clusters, the navigation in the web UI should not redirect back to the root cluster, you should stay in the leaf cluster.

Current behavior:

When using Trusted Clusters on v12, there’s an issue with the navigation in the web UI in that you don’t “stay” in the leaf cluster when you use the left-hand navigation. You are always redirected back to the root cluster.

If you select the leaf cluster from the drop-down, the Servers dashboard of the leaf cluster is displayed but if you then select Applications from the left-hand navigation, the Applications dashboard of the root cluster is displayed. You need to re-select the leaf cluster from the drop-down to switch to the Applications dashboard of the leaf cluster. 

Bug details:
- Teleport version: 12.1.1
- Recreation steps: As above
- Debug logs: N/A

**Comment by zmb3** [comment]
This was fixed in #23567 and will be in todays release.
