### ISSUE TITLE
SSH connection can not be established from the root of the Trusted Cluster to the Node belonging to the leaf.

### ISSUE THREAD

**Issue by fnifni** [gravitational/teleport#2389]
**What happened**:

SSH connection can not be established from the master of the Trusted Cluster to the Node belonging to the slave.
The workaround for this issue is to register an entry that can resolve the name of its nodename in "/ etc / hosts" of the slave Trusted Clouster proxy server.

**What you expected to happen**:

SSH connection can be made from the master of the Trusted Cluster to the Node belonging to the slave.
Even in a Trusted Cluster configuration, the Proxy server in Teleport Cluster should be able to access the Node server using advertise_ip.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure the Trusted Cluster.
2. Set a name that can not be resolved by DNS, "/ etc / hosts", etc. for the nodename of teleport.yaml that is set as the Node of the slave cluster.
3. Restart the teleportService of the Node in the cluster that will become the slave.

**Environment**:

- Teleport version (use `teleport version`): Teleport Enterprise v3.0.1 git:v3.0.1-0-g4ff9a7b0
- OS (e.g. from /etc/os-release):

```
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

**Comment by benarent** [comment]
Hi @fnifni , we are following up on older tickets. Are you still running into this issue? If so please email support@gravitational.com and we'll follow up.

**Comment by fnifni** [comment]
I do not currently use Teleport.
I will contact support when I resume using Teleport and the same phenomenon occurs.
Please close this ticket.
