### ISSUE TITLE
Proxy peering docs are incomplete

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#23890]
https://goteleport.com/docs/architecture/proxy-peering/
https://goteleport.com/docs/management/operations/proxy-peering/

From the docs above it's impossible to understand how to configure proxy peering, how load balancing works, how to troubleshoot and read log messages. It's unclear how it works with trusted clusters. Overall it's impossible to figure it out without reading the RFD:

https://github.com/gravitational/teleport/blob/master/rfd/0069-proxy-peering.md

This creates significant support load.

**Comment by jimbishopp** [comment]
Proxy-peering-related work: https://github.com/gravitational/teleport/pull/24164

**Comment by zmb3** [comment]
This was addressed in #24164
