### ISSUE TITLE
First page load after SSO sign in causes rpc error

### ISSUE THREAD

**Issue by Gunni** [gravitational/teleport#23893]
Expected behavior:
Just work, load server list.

Current behavior:
![image](https://user-images.githubusercontent.com/358099/229108129-60aa35c5-89d9-470a-ad42-844d4edcc0a4.png)

List loads after refresh.

Bug details:
- Teleport version: v12 cloud
- Recreation steps: Connect azure sso
- Debug logs: cloud

**Comment by zmb3** [comment]
This was fixed in #23691 and will be in todays release.
