### ISSUE TITLE
Fix port descriptions in the Adding Nodes guide

### ISSUE THREAD

**Issue by patrickomatik** [gravitational/teleport#23900]
## Applies To
https://goteleport.com/docs/management/admin/adding-nodes/

## Details
Port references are inconsistent - there are references to port `3024` but the config line for` $ADDR` uses port `3025` which seems to be the port used in the default config files.

The reference to `tunnel_listen_addr` seems to be incorrect, when included in the config file the service fails to start.

The instructions for multiplexing are incorrect - if you set the proxy and auth ports to 443, the daemon fails to start reporting that the port is already in use.

**Comment by ptgott** [comment]
#23869 should address this, but please let us know if there are more details we should add.
