### ISSUE TITLE
Make Proxy Template Docs more discoverable

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#23907]
## Applies To
https://goteleport.com/docs/server-access/guides/openssh/#experiencing-latency-in-leaf-cluster-nodes

## Details
The Docs for [Proxy Templates](https://github.com/gravitational/teleport/blob/master/rfd/0062-tsh-proxy-template.md) are buried within the OpenSSH guide linked above. These docs should be moved somewhere they can be discovered more easily, like in a separate guide.

**Comment by strideynet** [comment]
Strong agree - I saw discussion of Proxy Templates and actually was not able to find these docs at all when trying to learn more about them. This issue is the first time I've actually been able to find a link to them :')
