### ISSUE TITLE
Add kubernetes_resources to the permission denied error message

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#23910]
What would you like Teleport to do?
If you access Teleport kuberentes on role v6 without any `kubernetes_resources` allowed, you receive the following error message:

`Error from server (NotFound): Your user's Teleport role does not allow Kubernetes access. Please ask cluster administrator to ensure your role has appropriate kubernetes_groups and kubernetes_users set.`

Request is to add `kubernetes_resources` to the kubernetes permission error output so users know to check the new per-pod RBAC permissions as well.

What problem does this solve?
This helps customers identify issues proactively from error logging and reduces the support load

**Comment by tigrato** [comment]
This message was configured this way for Teleport to reflect the same error message that Kubernetes API returns when access is denied.

Would something like `kubectl auth can-i get pod/<pod-name>` help if it prints a detailed denied message?

**Comment by tigrato** [comment]
https://github.com/gravitational/teleport/pull/26425 addresses this error message and returns an actionable error message where users can learn how to fix the issue.
