### ISSUE TITLE
Expose User Invite API.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2392]
Allow a Teleport administrator with appropriate admin role to:

- [x] Add the following API methods to the Auth Server.
   - [x] Create invitation links for local users.
   - [x] Remove invitation links for local users.
   - [x] List all invitation links for local users. #PR.
- [x] Add support for the following API methods to the Web Proxy.
   - [x] Create invitation links for local users.
   - [x] Remove invitation links for local users.
   - [x] List all invitation links for local users.
- [x] Add support for the following API methods in the CLI.
   - [x] Create invitation links for local users `tctl users add ...`.
   - [x] Remove invitation links for local users `tctl tokens rm ...`.
   - [x] List all invitation links for local users `tctl tokens ls --type=signup`. #PR.

**Comment by benarent** [comment]
Marking this issue as closed as it was implemented in the CLI  https://gravitational.com/teleport/docs/cli-docs/#tctl-users-add
