### ISSUE TITLE
Add option to disable JWT headers

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#23924]
What would you like Teleport to do?
Add an option to disable JWT headers

What problem does this solve?
Upgraded Teleport cluster from v10.x.x to v12.x.x and now getting the following error when attempting to access an application on the Teleport UI: 
![Screenshot 2023-03-31 at 1 28 55 PM](https://user-images.githubusercontent.com/96448492/229201062-176fef7c-eebc-4aa4-b390-132785c803eb.png)
Adding an option to disable JWT headers will remove this error as the expected response by the backend application will be within range. 

If a workaround exists, please include it.
Increase header limits, but not all applications have that capability. 
e.g. 
AWS OpenSearch 
- We get a 413 error message ("Request Entity Too Large") due to this particular app not expecting large JWT headers. Now that we have 2 copies of the application, upgrading from 10.x to 12.x can cause issues for the previously working apps to fail in this manner.

**Comment by programmerq** [comment]
An ugly workaround would be to put another reverse proxy between Teleport and the application that has the header size limit. That additional component can pass on only the needed headers to stay under the size limit.

**Comment by pschisa** [comment]
similar to https://github.com/gravitational/teleport/issues/21731

**Comment by kpython** [comment]
Just notice this new issue now on teleport v.13.1.0, which was not happening on older version of teleport.
Is there any update or new workaround for this issue?

**Comment by r0mant** [comment]
We will add a `jwt_claims` property to the application rewrite configuration with the following values:

```yaml
apps:
  - name: "dumper"
    uri: http://localhost:4321/
    rewrite:
      jwt_claims: (none|roles-and-traits|roles)
      headers:
      - "Authorization: Bearer {{internal.jwt}}"
```

Possible values are:
- `roles-and-traits`: current behavior, we include both roles and traits in the token. This should be default for compatibility.
- `roles`: only include roles, no traits.
- `none`: do not include roles or traits.

So we will still always include the JWT token with all requests but its claims will depend on the above per-app setting.
