### ISSUE TITLE
Expose Events API.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2394]
Note, still need to work with @r0mant to make this consistent with Gravity.

- [ ] Document that HA Teleport with disk backed audit log will have inconsistent views in the Web UI.
- [ ] Expose Audit Log API to the Web UI.
  - [ ] API should support fetching all audit events (currently can only fetch events of a certain type).
  - [ ] API should support filtering by event type and timestamp should be supported.
  - [ ] API should support pagination by timestamp (with a limit) should be supported.
- [ ] Active Sessions API should support the new realtime backend.

**Comment by benarent** [comment]
@russjones I'm just prepping tasks for 4.2. Can you let me know if task and it's issues are still up-to-date.

**Comment by benarent** [comment]
@russjones How many of these have been addressed? and how many of these are still open issues?

**Comment by benarent** [comment]
I'm going to close this issue for now, as we've more fine grained events data / requests in the 5.0 Milestone.
