### ISSUE TITLE
[v.12.x] /docs/pages/deploy-a-cluster/high-availability.mdx

### ISSUE THREAD

**Issue by patrickomatik** [gravitational/teleport#24001]
## Applies To
https://goteleport.com/docs/deploy-a-cluster/high-availability/

## Details
The documents state:

The auth_service and proxy_service configurations above have the following required settings for a high-availability Teleport deployment:

In the **auth_service** section, we have **enabled** the Teleport Auth Service (enabled) and instructed it to find an Enterprise license file at /var/lib/license/license.pem (license_file). Remove the license_file field if you are deploying the open source edition of Teleport.

In the **proxy_service** section, we have **enabled** the Teleport Proxy Service (enabled) and instructed it to find its TLS credentials in the /etc/teleport-tls directory (https_keypairs).

(My emphasis).
However, following these instructions gives the following error:

23-04-03T17:03:53+01:00 INFO             

Starting Teleport v12.1.5 with a config file located at "/etc/teleport.yaml" common/teleport.go:522
ERROR: configuration error
initialization failed
**config: cannot use both auth_server and proxy_server**

**Comment by patrickomatik** [comment]
Please could someone explain the correct method to add a node to a teleport cluster given the above issue?

**Comment by stevenGravy** [comment]
@patrickomatik please provide details on your setup.

**Comment by stevenGravy** [comment]
For `v3` of the Teleport config file you can put either a `auth_server` or a `proxy_server`, not both.  Are you seeing this on your proxy service?  On the proxy you would put the auth_server.

**Comment by ptgott** [comment]
Closing as inactive.
