### ISSUE TITLE
remote cluster last_heartbeat: 0001-01-01T00:00:00Z

### ISSUE THREAD

**Issue by andrewbanchich** [gravitational/teleport#2402]
**What happened**:

When running `sudo tctl get rc` I see that some of the remote cluster nodes are offline and say `last_heartbeat: 0001-01-01T00:00:00Z`.

**What you expected to happen**:

I do know that these were online at one point, so I would have expected `last_heartbeat` to be the time they were last online. Is that not what `last_heartbeat` is?

**Comment by benarent** [comment]
This issue has been fixed with Teleport 4.3.
