### ISSUE TITLE
Device Trust connect failure message does not match expected output

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#24042]
Expected behavior:

Match to documentation

```bash
tsh ssh server1
ERROR: ssh: rejected: administratively prohibited (unauthorized device)
```

Current behavior:

Error shows generic connect error

```bash
tsh ssh devuser@appdevserver2
ERROR: access denied to devuser connecting to appdevserver2:0@default@tele1c
```

Bug details:
- Teleport version: 12.1.5
- Recreation steps:

1. Configure a role to require device enrollment
2. Connect via that role from a enrolled device and a non-enrolled device.

**Comment by zmb3** [comment]
I wonder if this is related to the changes I just made for you to show the server name instead of UUID.

**Comment by sshahcodes** [comment]
This happens for role-based trusted device enforcement. Parent issue: [Better device trust connection errors](https://github.com/gravitational/teleport/issues/20645) 

The cluster-wide enforcement correctly returns the `rejected: administratively prohibited (unauthorized device)` error.

**Comment by codingllama** [comment]
Yep, it looks like this has to do with piping error messages through the SSH protocol, which is trickier than it looks. Closing in favor of #20645 (mentioned by Sakshyam above).
