### ISSUE TITLE
View Toggle Component

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#2404]
The view toggle component needs two states: 
1. Card View
2. Table/List View

![screen shot 2018-12-03 at 11 18 02 am](https://user-images.githubusercontent.com/407237/49396086-1da78500-f6ed-11e8-8efa-14d98842f647.png)

## Used in:
https://github.com/gravitational/teleport/issues/2499 
https://github.com/gravitational/teleport/issues/2503
https://github.com/gravitational/teleport/issues/2500

**Comment by alex-kovoy** [comment]
done
