### ISSUE TITLE
Add Amazon Linux 2023 support to EC2 auto-discovery

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#24069]
AL2023 is new and we don't have the packages for it yet so the EC2 auto-discovery install script fails.

Install script itself may need updating as well.

**Comment by webvictim** [comment]
Same thing as https://github.com/gravitational/teleport/issues/24007

**Comment by hugoShaka** [comment]
Fixed in https://github.com/gravitational/teleport.e/pull/1316
