### ISSUE TITLE
Button w/ Dropdown Component 

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#2406]
The button will have a default state that when pressed will initiate an action. However if the user clicks the dropdown arrow they will be able to select from a list of other options. 

![screen shot 2018-12-03 at 11 19 30 am](https://user-images.githubusercontent.com/407237/49396249-87279380-f6ed-11e8-88d0-358406280ac7.png)
![screen shot 2018-12-03 at 11 19 16 am](https://user-images.githubusercontent.com/407237/49396255-8a228400-f6ed-11e8-9803-93e48b21f259.png)

**Comment by alexwolfe** [comment]
@alex-kovoy can we get a story for this? Thanks!

**Comment by benarent** [comment]
I've noticed this is fixed in Gravity. I'm going to mark as closed as we don't heavily use the dropdown menu in Teleport.
