### ISSUE TITLE
Documentation Improvement: Desktop Access with Active Directory (Discovery)

### ISSUE THREAD

**Issue by gaille-teleport** [gravitational/teleport#24074]
## Applies To
[Desktop Access with Active Directory (Discovery)](https://goteleport.com/docs/desktop-access/active-directory/?scope=cloud#step-12-run-the-discovery-wizard)

## Details
The Desktop Access Active Directory Discovery Wizard docs do not explain how to install Teleport Desktop Access service on the Linux server. It just assumes that you have already installed it here:

![Screenshot 2023-04-04 at 12 19 25 PM](https://user-images.githubusercontent.com/106986732/229897801-fd3228d9-9c67-4afc-bc10-6809d69f70ca.png)

It may be helpful/clarifying to add instructions on how to install/configure Teleport on the Linux host. It is outlined in our Manual Active Directory docs [here](https://goteleport.com/docs/desktop-access/active-directory-manual/?scope=cloud#step-67-configure-teleport), so maybe we can include similar instructions there?

**Comment by nitisjan** [comment]
what change you sugget ? we add installation process in brief for linux.
