### ISSUE TITLE
[v.12.x] Unexpected "$VERSION_ID" return on Amazon Linux 2.

### ISSUE THREAD

**Issue by grousk** [gravitational/teleport#24127]
## Applies To
[This section](https://goteleport.com/docs/try-out-teleport/linux-server/)

**Step 3/6**

**Amazon Linux 2** / RHEL(RPM)

`"sudo yum-config-manager --add-repo $(rpm --eval "https://yum.releases.teleport.dev/$ID/$VERSION_ID/Teleport/%{_arch}/stable/v12/teleport.repo")"`

Amazon Linux 2 is affected.

## Details
In newest  Amazon Linux $VERSION_ID returns 2023 instead of 2. This causes an 404 error.

**Comment by zmb3** [comment]
Duplicate of:
- #24069
- #24007
