### ISSUE TITLE
tbot support for aws access

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#24147]
What would you like Teleport to do?
Add tbot support for AWS access.

What problem does this solve?
It will allow the following since teleport/tsh doesn't currently support it: 
We want to define access to `AWS` CLI using `tsh aws` generated credentials which we want to provide for some CLI-based tasks in our CICD pipeline. 

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Duplicate of #16935
