### ISSUE TITLE
tsh uses generic `teleport.cluster.local` SNI for requests

### ISSUE THREAD

**Issue by stereobutter** [gravitational/teleport#24184]
We have deployed two independent teleport clusters in HA mode (using the helm chart) and would like to put them both behind the same load balancer with `traefik` as a layer 4 router to route TCP traffic based on the SNI (e.g. `prod.example.com` for one cluster and `staging.example.com` for the other). For the web UI this works but we noticed (by looking at the `CLIENT HELLO` TCP packets using wireshark) that `tsh` makes requests to the auth server (over the proxy) using SNIs of the form `<some-random-id>.teleport.cluster.local`. 

![wireshark](https://user-images.githubusercontent.com/35063695/230350757-29534b7c-c014-4e52-ae00-cac0fd213079.png)

This is somewhat intentional according to https://goteleport.com/docs/management/admin/troubleshooting/#teleportclusterlocal but makes it impossible to distinguish traffic for multiple clusters based on the SNI. While it is possible to add a custom SAN for the auth server (in addition to `teleport.cluster.local`) it appears that `tsh` has no way to make use of this.

```yaml
# this adds "prod.example.com" to the auth server certificate as SAN
auth_service:
  public_addr: prod.example.com
```

Expected behavior:
- `tsh` uses a cluster-specific SNI in its requests. Maybe `tsh` could default to using the proxy DNS name as SNI and only if that fails it falls back to using `teleport.cluster.local`? That way one could simply add the proxy DNS name as SAN for the auth service like done in the config above and everything would work out. 

Bug details:
- Teleport version: 12.1.5 (via the helm chart in `scratch` mode)

**Comment by webvictim** [comment]
The value before `.teleport.cluster.local` isn't actually random: 

https://github.com/gravitational/teleport/blob/50826a1b413339afdfc5f94097b8fa34e1418e91/api/utils/cluster.go#L29-L33

https://github.com/gravitational/teleport/blob/50826a1b413339afdfc5f94097b8fa34e1418e91/api/constants/constants.go#L32-L35

You should be able to work out what the encoding will be for each of your clusters (based on their `cluster_name`) and then add routing for those: https://play.golang.com/p/p4p4clKJDp8

Or is this a bug report: you know what the IDs are, but `tsh` doesn't always use them correctly? We've had users doing exactly what you describe before when they have multiple clusters being one layer 4 LB and use `ClientHello` to route requests so I do think it's possible today, but let me know.

These discussion posts may also be helpful:
- https://github.com/gravitational/teleport/discussions/13006
- https://github.com/gravitational/teleport/discussions/19093

**Comment by webvictim** [comment]
Closing as this is working as expected.
