### ISSUE TITLE
Allow login username to be set when calling `tsh config`

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#24234]
**What would you like Teleport to do?**

Running `tsh config` currently assumes that you will use the same login username as your shell. In many environments this isn't desirable.

We should support the use of `tsh config --login shareduser` to automatically add a `User shareduser` line into the Teleport-generated `ssh_config` file.

**What problem does this solve?**

Ease of onboarding and rollout for less technical users who need to remember to always connect to `login@host`.

**If a workaround exists, please include it.**

Provide login on the command line every time or set `TELEPORT_LOGIN` environment variable.

**Comment by russjones** [comment]
Customer has also asked for something similar but wanted to control the port.
