### ISSUE TITLE
Fallback to `SSH_*` env variables for `tsh` commands

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#24241]
`tsh` should check the env variables `SSH_TELEPORT_USER`, `SSH_SESSION_WEBPROXY_ADDR`, and `SSH_TELEPORT_CLUSTER_NAME` when the standard flags/env variables are not set (e.g. `--user`, `TELEPORT_USER`).

This would be especially useful in combination with Headless SSO, so you can `tsh ssh` into a remote box and then perform `tsh --headless` without setting additional flags or env variables.

**Comment by zmb3** [comment]
Wouldn't it make more sense for them to start with `TELEPORT_`?

**Comment by Joerger** [comment]
`tsh ssh` already sets the environment variables `SSH_TELEPORT_USER, SSH_SESSION_WEBPROXY_ADDR, and SSH_TELEPORT_CLUSTER_NAME` for the session, so the request is just to use these values when their respective flag / `TELEPORT_` env variable is not set.
