### ISSUE TITLE
Document new `sqlite` backend option

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2431]
## Description

`Dir` and `bolt` backends were deprecated in 3.2 in a backwards-compatible way. Whenever there is `bolt` or `dir` mentioned in the configuration, the data will be automatically migrated to `sqlite` backend that is the only embedded database supported.

It's also worth mentioning that `NFS` backed storage is not supported for embedded backend options. It was never supported (was failing anyways), but we never mentioned it anywhere.

**Comment by kontsevoy** [comment]
Let's call it `local`. Renaming config. values simply because we keep chaning the implementation is leaking too much of internal guts.

**Comment by klizhentas** [comment]
This works as you described it, however `sqlite` should also be supported explicitly, as some configuration parameters of sqlite may change from deployment to deployment and are a trade-off, for example sync vs async mode and timeouts.
