### ISSUE TITLE
Provide overview of discovery

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#24326]
## Applies To
Could be added to https://goteleport.com/docs/core-concepts/ or have its own page

## Details
Provide an overview of Teleport discovery as concept.  What does discovery do and how does it apply to the protocols.  The guides have a mix of discovery or direct access.  That makes it unclear at time which one to use.

**Comment by zmb3** [comment]
Resource discovery or reverse tunnel / proxy discovery?

**Comment by stevenGravy** [comment]
> Resource discovery or reverse tunnel / proxy discovery?

Resource discovery.  How are elements found, how often.  how do you tag them.

**Comment by ptgott** [comment]
Would it help to have a dedicated section on the Discovery Service? So far, docs on this service are dispersed across our other service-related sections.

**Comment by stevenGravy** [comment]
That @ptgott or part of the Architecture section

**Comment by ptgott** [comment]
Going to fold this issue into #38741, which is a more specific plan
