### ISSUE TITLE
Windows Copy/Paste issue when we use command+tab in Web UI

### ISSUE THREAD

**Issue by pnrao1983** [gravitational/teleport#24342]
Expected behavior:
Copy/paste should work in Web UI for Windows desktops when using a MAC keyboard when changing tabs using command+tab.

Current behavior:
It works fine when we copy/paste within Web UI using control copy(c)/control paster (v). It works well in RDP sessions.
But when we change tabs using command+tab (Mac keyboard) copy/paste not working until we hit the command button twice or paster command+v twice.
Bug details:
- Teleport version: v12
- Chrome Browser version: 111.
- Recreation steps: 
   Logged on to Windows desktop session from Web UI
   Open Browser/Notepad and try copy/paste works. Copy Data from another session without using command+tab will copy/paste works.
   But when we use command+tab and try copy/paste dint work.

https://www.loom.com/share/fe66e21182bd4d7ca85ef54919fd22e1
- Debug logs
   NA

**Comment by zmb3** [comment]
This is likely due to us not implementing the [synchronize event](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/6c5d0ef9-4653-4d69-9ba9-09ba3acd660f) to sync the state of toggle keys with the remote desktop.

We're looking to move away from rdp-rs, so this should be resolved when the migration is complete.

**Comment by zmb3** [comment]
A similar issue appears when using alt+tab on Windows to change focus from the remote desktop session to some other app.

The remote Windows desktop sees the alt key pressed down, but then focus moves away from the browser and we are not able to tell the remote end that the alt key was released, so when you eventually go back into the remote session it behaves as if alt is being held down (until you press alt to re-synchronize things).

**Comment by ciriarte** [comment]
I'd like to express my support for prioritizing this ticket. It's very disruptive for us. I believe this part is not open source? If it is, could you please point me to the code owners? I can perhaps submit a Pull Request given proper guidance.

**Comment by dbrummer** [comment]
+1 for prioritizing this.

**Comment by rdill-83** [comment]
I too recommend prioritizing this ticket.

**Comment by nvelcea** [comment]
+1

**Comment by kernelPanic10** [comment]
Adding another vote to prioritize this ticket.

**Comment by michaelscales88** [comment]
+1

**Comment by ConstableBrew** [comment]
+1
