### ISSUE TITLE
Write a section in the docs about switching backends

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2440]
## Description

Customers faced a problem when they updated the backend type and were not aware of the consequences. We should update docs with facts:

* Switching backends will not migrate data from old backends to new backends
* It is possible to transfer cluster state to the new backend using export/import of certificate authority and using the same cluster name
* Events and records are not going to be uploaded,  however it's possible to migrate them from local storage theoretically using script. 

May be we should write a script for customers to automate that?

**Comment by alexfornuto** [comment]
Update: I spoke with our team to determine where we are with regards to solving this. As it stands, we have `tctl get` which accepts `all`, but doesn't necessarily get "all". There's currently no clear method to know and backup all the configuration required to do a storage backup and migration.

In general I'm in favor of closing docs issues that aren't solvable by the docs team, and it looks like this issue requires further dev work to make possible. On the other hand, this is an important topic and if/when Teleport can create a path to storage migration I'd like to know and document it. So I'm asking for input; what do we want to do with this issue?

**Comment by zmb3** [comment]
This is documented at https://goteleport.com/docs/management/operations/backup-restore/#migrating-backends

We can open more specific and actionable issues if we find something is lacking here.
