### ISSUE TITLE
Non-AD Windows: curl command to get CA cert does not work

### ISSUE THREAD

**Issue by BrianGalfond-Teleport** [gravitational/teleport#24502]
Expected behavior:
When running the .exe file for Non-AD windows, users should be able to select the cert generated by this [curl command in our docs](https://goteleport.com/docs/desktop-access/getting-started/?scope=cloud#import-the-teleport-root-certificate):
curl 'https://teleport-proxy.example.com:443/webapi/auth/export?type=windows' > teleport.cer

Current behavior:
After running the .exe file and selecting the certificate from the curl command, this error is displayed:
![Screenshot 2023-04-12 at 8 32 14 PM](https://user-images.githubusercontent.com/94465695/231619167-56aea05a-4cdf-430c-8c68-de5b4518fbcd.png)

Bug details:
- Teleport version: 12.2.1
- Recreation steps:
Run the curl command from our docs (curl 'https://teleport-proxy.example.com:443/webapi/auth/export?type=windows' > teleport.cer) then, select that cert after running the Auth Setup executable.

Workaround:
Use _tctl auth export_ to get the CA cert

**Comment by zmb3** [comment]
@BrianGalfond-Teleport I'm not having any issue with this. Which version of Windows are you running this on? I think older versions have limited curl support.

**Comment by zmb3** [comment]
cc @probakowski - we should consider having the user just paste the URL to their proxy in the installer, and having the installer fetch the cert. That would eliminate the need for curl or tctl, but would require connectivity to the proxy from the desktop, which may be available but isn't strictly required today.

**Comment by BrianGalfond-Teleport** [comment]
@zmb3 I hit the same issue for 2019 and 2022. In both cases, using the cert from tctl auth export worked. The cert files from tctl and curl are different.
