### ISSUE TITLE
using private github with teleport community

### ISSUE THREAD

**Issue by GAHila** [gravitational/teleport#2452]
**What you expected to happen**:
Instead of github.com we want to use our own private installation of github.
I have been unable to find a place where to configure this.

Is it possible to configure teleport github connector to point to a private installation of github?

**Environment**:
- Teleport version (use `teleport version`):
Teleport community 3.1.0

**Comment by klizhentas** [comment]
I'm assuming you are referring to github enterprise, AFAIK it can act as [SAML provider](https://help.github.com/enterprise/2.15/admin/guides/user-management/using-saml/) that Teleport Enterprise supports too. So the likely answer - this should work, but not with Teleport Community Edition.
