### ISSUE TITLE
tctl rm user error

### ISSUE THREAD

**Issue by Ma1tobiose** [gravitational/teleport#2453]
**What happened**:
I update to the latest version,I find out that user detail will save into sqlite which is a nice change!
However, when i use '$tctl users rm abc', i received an error like 'error: key /web/users/abd is not found'. I promise that username abc is actually exact in my database,and this phenomenon only appears with saved username.

**What you expected to happen**:
expect delete user by tctl correctly

**How to reproduce it (as minimally and precisely as possible)**:
use '$tctl users rm abc' 

**Environment**:
- teleport version:Teleport v3.0.1
- tsh version:Teleport v3.0.1
- OS :macOS 10.14.2

**Browser environment**
 - Chrome

 might there is a bug in /lib/services/local/users.go func RangeEnd

**Comment by moritzdietz** [comment]
Would you please fill out the template that was provided to you when you opened the issue on Github?

**Comment by Ma1tobiose** [comment]
> Would you please fill out the template that was provided to you when you opened the issue on Github?

Ok, I am trying to describe the problem more clearly.

**Comment by CaptCrankyPants** [comment]
Similar issue.

```
$ tctl users rm ryan --debug
DEBU             DEBUG logging enabled common/tctl.go:188
DEBU [SQLITE]    Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF lite/lite.go:153
DEBU [SQLITE]    Synchronous: 0 lite/lite.go:193
DEBU [SQLITE]    Busy timeout: 10000 lite/lite.go:198
DEBU [MIGRATE]   Detected legacy backend, data has already been imported. legacy/import.go:50

ERROR REPORT:
Original Error: *trace.NotFoundError key /web/users/ryao is not found
Stack Trace:
        /usr/lib/golang/src/github.com/gravitational/teleport/lib/auth/clt.go:1342 github.com/gravitational/teleport/lib/auth.(*Client).DeleteUser
        /usr/lib/golang/src/github.com/gravitational/teleport/tool/tctl/common/user_command.go:174 github.com/gravitational/teleport/tool/tctl/common.(*UserCommand).Delete
        /usr/lib/golang/src/github.com/gravitational/teleport/tool/tctl/common/user_command.go:90 github.com/gravitational/teleport/tool/tctl/common.(*UserCommand).TryRun
        /usr/lib/golang/src/github.com/gravitational/teleport/tool/tctl/common/tctl.go:117 github.com/gravitational/teleport/tool/tctl/common.Run
        /usr/lib/golang/src/github.com/gravitational/teleport/tool/tctl/main.go:33 main.main
        /usr/lib/golang/src/runtime/proc.go:210 runtime.main
        /usr/lib/golang/src/runtime/asm_amd64.s:1334 runtime.goexit
User Message:

$ cat ryan.yaml
kind: user
metadata:
  name: ryan
spec:
  created_by:
    time: 0001-01-01T00:00:00Z
    user:
      name: ""
  expires: 0001-01-01T00:00:00Z
  roles:
  - admin
  status:
    is_locked: false
    lock_expires: 0001-01-01T00:00:00Z
    locked_time: 0001-01-01T00:00:00Z
  traits:
    kubernetes_groups: null
    logins:
    - centos
version: v2
```

**Comment by klizhentas** [comment]
Thanks for the report, I will take a look before beta release and make sure it works

**Comment by klizhentas** [comment]
I've just tried this on the fresh master and the issue is not reproducible there. Feel free to reopen (but please add exact config/instructions on how to repro) if you are still seeing this.
