### ISSUE TITLE
Azure IAM join fails when identity is in a separate resource group

### ISSUE THREAD

**Issue by atburke** [gravitational/teleport#24551]
Expected behavior:
Nodes joining with the Azure join method can join a cluster regardless of which resource group their Azure managed identity is in.

Current behavior:
If a VM's identity is in a different resource group from itself, joining will fail with the error `no VM found with matching VM ID`.

Bug details:
- Teleport version
12.1.5
- Recreation steps
Follow the [Azure join method guide](https://goteleport.com/docs/management/guides/joining-nodes-azure/), but create the identity in a separate resource group from the VM.

**Comment by mik-konop** [comment]
Hi, any news on when this will be fixed?
