### ISSUE TITLE
Automatically generate the changelog from release notes

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#24601]
## Applies To

`docs/pages/changelog.mdx`, which includes `CHANGELOG.md` as a partial

## Details

The changelog is difficult to maintain across `master` and the three release branches we support at a given time. The changelog differs in unexpected ways across our release branches, making it cumbersome to edit the document and backport those edits.

Let's see if we can use a script to generate the CHANGELOG from our release notes. This way, we can easily open consistent PRs against `master` and our release branches. We can either run the script manually or via GitHub Actions.

For inspiration, run this one-liner using the `gh` CLI from within your `teleport` clone to get the beginnings of a concatenated changelog:

```bash
gh release list | grep -Eo "v[0-9]+\.[0-9]+.[0-9]+(-[a-z]+\.[0-9]+)?" | xargs -I{} gh release view --json name,body  --template '
# {{ .name }}

{{ .body }}' {}
```

We would need to expand this to cover all releases (not just the first 30) and clean up the text a lot (i.e., this is better done using a program that imports a GitHub client library instead of `gh`), but this is very, very doable.

I imagine the hardest part will be cleaning up our past release notes to ensure that their formatting is consistent and matches the expectations of the generator. We can also have the generator flag aberrant release notes so we can clean them up individually.

**Comment by zmb3** [comment]
FWIW, our current release process is to generate the changelog first, and copy it into the release notes. The suggestions here create a bit of a chicken/egg problem.

**Comment by ptgott** [comment]
Interesting, thanks! What would it take for us to write the release notes first?

**Comment by zmb3** [comment]
That's not really doable, because we want the changelog for vX.Y.Z to be present in the tag for vX.Y.Z, and the release on GitHub only comes after the tag is pushed and artifacts are available.

I have some thoughts, but I'll take them to a private medium since we're now talking about internal release processes and not OSS development.

**Comment by ptgott** [comment]
Thanks! I think that's enough info to close this issue. We'll find another way to address the underlying considerations.
