### ISSUE TITLE
connecting to machine in cluster with securecrt

### ISSUE THREAD

**Issue by johandeclercqdemocon** [gravitational/teleport#24609]
Expected behavior:

This is more or less a documentation issue : 

cli 
1. connect to proxy. 
2. connect to cluster. 
3. ssh to machine. 

question is how do I configure this in securecrt ? 

I don't figure it out myself. 
Current behavior:

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
I'm not sure we've ever tried using SecureCRT with Teleport. This might be more suited for a [discussion](https://github.com/gravitational/teleport/discussions) as opposed to a bug report.

**Comment by johandeclercqdemocon** [comment]
zmb3, I opened a discussion on this.
