### ISSUE TITLE
Teleport API and Plugin System

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2461]
## Description

 [Teleport API and Plugin design document](https://docs.google.com/document/d/1sPXXxx03P8VXWy-YD5w190g7VVoDFV96DAe3Q8z81gE/edit?usp=sharing) is a public draft to be discussed with customers and community. Please leave comments in the document. 

Once we polish the document in the next several weeks, we are going to move it to this ticket.

**Comment by klizhentas** [comment]
We would really like to hear back (please leave a comment to this ticket or in the document, especially we would like to learn more about:

* Use cases you would like API to handle
* Languages you would like API wrappers to exist
* Anything else

**Comment by stevenGravy** [comment]
@klizhentas think this can be closed with our current API docs and plugins
