### ISSUE TITLE
storage.path vs. data_dir

### ISSUE THREAD

**Issue by mpitt** [gravitational/teleport#2462]
The Admin manual only mentions `data_dir` at the top level `teleport`, but I've seen examples with `storage.path` (e.g. https://github.com/gravitational/teleport/issues/2070#issuecomment-404686817) when the `dir` backend is used.

More in general, it would be great to have complete configuration examples for each backend, not just the highly-available ones.

**Comment by kontsevoy** [comment]
@mpitt good point, adding to the nearest milestone.

**Comment by benarent** [comment]
I've added a not about storage.path vs data_dir. I've a not to add info about complete configuration examples for each backend as part of our upcoming guides project.
