### ISSUE TITLE
Audit Log won't be generate when I try ssh to new node which is joined Teleport cluster via modify sshd config file.

### ISSUE THREAD

**Issue by johnnyjpixy** [gravitational/teleport#2470]
**What happened**:
Audit Log won't be generate when I try ssh to new node which is joined Teleport cluster via modify sshd config file.
In fact, I know I just wanna modify new node's sshd config file to join current Teleport cluster. in fact, the current teleport cluster won't aware the new nodes exits. That's the root cause why the audit log won't generate after ssh to the new node ?
Thanks.

**What you expected to happen**:
New audit log records should be generated on auth server /var/lib/teleport/log/

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`): Teleport v3.0.1 git:v3.0.1-0-g4ff9a7b0
- Tsh version (use `tsh version`): Teleport v3.0.1 git:v3.0.1-0-g4ff9a7b0
- OS (e.g. from /etc/os-release): Ubuntu 16.04 LTS

**Browser environment**
Chrome

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by johnnyjpixy** [comment]
And it looks like the solution is the "RECORDING PROXY MODE" ?
But i got another error in other 2 issues : #2471 #2472

**Comment by aberoham** [comment]
Exporting your teleport-auth certificate authority's public key to an openssh server does nothing more than configure that specific openssh server to accepted certificates signed by your teleport-auth CA. Your openssh-server node does not "join" your Teleport cluster and teleport-auth has no way to know that you've copied its public key material to some random node/location.

For end-users who do not understand PKI (and frankly for almost all use cases revolving around active management of exported certificates or keys), we highly recommend that you run teleport-node agent and **stop trying to manually manage PKI.**
