### ISSUE TITLE
What's the specify server meanning in "Audit Log" section ?

### ISSUE THREAD

**Issue by johnnyjpixy** [gravitational/teleport#2471]
**What happened**:
When I read the section of "Audit Log"
It says:
The recommended solution is to ask Teleport to issue valid host certificates for all OpenSSH nodes. To generate a host certificate run this on your auth server:

$ tctl auth sign \
      --host=node.example.com \
      --format=openssh
Then add the following lines to /etc/ssh/sshd_config and restart sshd.

HostKey /etc/ssh/teleport_host_key
HostCertificate /etc/ssh/teleport_host_key-cert.pub

I so confused. 
1) what's the "node.example.com" means ? the auth node ? or proxy node ? or other common node ?

2) and I should add the lines to sshd_config on which server ? the auth node ? or proxy node ? or other commnon node ?

3) Should I need to use "tctl auth sign \
      --host=node.example.com \ " for all nodes in the teleport cluster ? then modify the all sshd_config files on the nodes ?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by aberoham** [comment]
Please see the warning in my comment on #2470. You should run teleport-node and stop trying to manually manage PKI. Automatically managing host and user certificates is one of the major benefits of Teleport. 

As to the specific questions, the documentation section you're asking about relates to manually signing a single host certificate. `node.example.com` would be an openssh-server node that you wish to configure to trust (and be trusted by) your teleport-auth instance. One-off copies of signed certificates is not the recommended way to use Teleport and should be reserved for exceptional use cases.
