### ISSUE TITLE
Update HA configuration section

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2474]
## Description

Some users experience troubles setting up HA Teleport on AWS and other clouds, because it is not clear that Teleport Proxy is using web x509 certificates, while Auth servers are setting up internal x509 CA and therefore ELBs with SSL termination will not work for auth servers.

Update documentation to make it more clear.

[Ev moving this from #2431] Also, we need to tell users NOT to use NFS to HA purposes in combination with `dir` back-end type.

**Comment by benarent** [comment]
@DaveHewy I've a PR open for this, if you're still having issues could you either post in https://community.gravitational.com/ or in our Slack Channel https://grv8.slack.com/
