### ISSUE TITLE
Automatic Upgrades Test Plan

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#24750]
## Linux upgrades @fspmarshall 

- Verify that install of upgrader package results in working `teleport-upgrade` service and timer units, and that teleport automatically starts exporting schedule post-install:
  - [x] apt/Ubuntu 20.04
  - [x] yum/Amazon Linux 2
  - [x] yum/CentOS 7

 _TODO: expand os/version coverage._

- Manually trigger an upgrade using each real installer variant, and verify that the running teleport is upgraded and restarted:
  - [x] apt/Ubuntu 20.04
  - [x] yum/Amazon Linux 2
  - [x] yum/CentOS 7
  
 _TODO: expand os/version coverage._

- Manually trigger the following scenarios using the `nop` installer (any platform):
  - [x] versions match => no action is taken.
  - [x] outside maintenance window => no action is taken.
  - [x] outside maintenance window, critical=yes => install is triggered.
  - [x] inside maintenance window => install is triggered.
  - [x] maintenance schedule missing => first run warns, second run upgrades.
  - [x] maintenance schedule outdated => first run warns, second run upgrades.

## Kubernetes upgrades @hugoShaka

- [x] test updater on arm64 cluster
- [x] test updater on amd64 cluster
- [x] test that agents are exporting their maintenance windows into the shared secret
- [x] test that the updater updates when a release channel says it is critical
- [x] test that the updater does not update when everything is green and we are out of maintenance
- [x] test that the updater updates during a maintenance window
- [x] test that the updater updates if the statefulset is unhealthy
- [x] test that the updater can unstuck a stuck statefulset (deploy an invalid version)
- [x] test that the updater does not react to ther deployments in the same namespace
- [x] test that the updater requeues reconciliation after 30 min
- [x] test that the updater ignore statefulsets wearing the skip label

## Build and promotion @fheinecke 

xxx

## Reference

```
https://updates.releases.development.teleport.dev/v1/stable/cloud/version
https://updates.releases.development.teleport.dev/v1/stable/cloud/critical
```

**Comment by hugoShaka** [comment]
PR fixing various issues encountered during the test plan: https://github.com/gravitational/teleport/pull/24746

**Comment by hugoShaka** [comment]
Chart references the wrong readiness port: https://github.com/gravitational/teleport/pull/25323

**Comment by fspmarshall** [comment]
A couple configuration parameters weren't being applied correctly by the updater package, and both `apt` and `yum` variants of the install commands ended up not working quite right for downgrades.   All addressed in https://github.com/gravitational/teleport.e/pull/1154.
