### ISSUE TITLE
Web UI has no favicon

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#24773]
Expected behavior:
The web UI has a favicon, as it did in previous versions (12.1.5 has one)

Current behavior:
No favicon

Bug details:
- Teleport version: 13.0.0-dev.alpha.1
- Recreation steps: open the proxy web ui
- Debug logs: N/A

**Comment by ryanclark** [comment]
> Hmm. Nothing seems to be calling `useFavicon` anymore (even on v11 and v12).
> 
> @ryanclark might this be related to vite?

Sorry for the delay - opened up PRs to fix
