### ISSUE TITLE
setting ALPNSNIAuthDialClusterName will only set ALPN not SNI

### ISSUE THREAD

**Issue by Ballihakkari** [gravitational/teleport#24802]
Expected behavior:

To talk to my teleport cloud via TLS I need to set the ALPN and SNI to get past the load balancer/proxy that teleport uses. 
To do this I would think I set the "ALPNSNIAuthDialClusterName" parameter when creating the teleport client. i.e.  
```
clt, err := client.New(ctx, client.Config{
		Addrs: []string{
			clusterName+port,
 		},
		Credentials: []client.Credentials{
			creds,
		},
		ALPNSNIAuthDialClusterName: clusterName,
	})
```
Then I can talk to the teleport cloud via TLS. 

Current behavior:

this parameter only sets the ALPN but not the SNI, as can be seen on Wireshark
![clustername not in the SNI](https://user-images.githubusercontent.com/34066727/233081687-aca74191-a3fe-460e-9b98-d9fb2eb94252.png)
In this pic we can see the ALPN is set but the SNI only has teleport.cluster.local, not <hex-encoded cluster name>.teleport.cluster.local  

To fix I just manually set the SNI in the TLSconfig before I pass it to the client. 
i.e. 
```
tlsCfg, err := creds.TLSConfig()
tlsCfg.ServerName = fmt.Sprintf("%s.%s",hex.EncodeToString([]byte(clusterName)), "teleport.cluster.local")
creds = client.LoadTLS(tlsCfg)
```
Then I create the client as I did above and it works. 

Bug details:
- Teleport version 12

**Comment by strideynet** [comment]
What Credential source are you using in your "Expected behavior" ?

**Comment by strideynet** [comment]
I've raised #25534 which describes the root cause of this issue. Your work-around is correct, and my suggested work-around until we fix this.

The other way to work around this would be to use an identity file and allow one of the SSH based methods to be used to connect to the auth server instead of the ALPN routing being used.
