### ISSUE TITLE
Agent forwarding broken in tsh.exe

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#24823]
Logs TBA.

`tsh` version `12.2.1`.
Customer is using msys2 SSH and agent.

**Comment by r0mant** [comment]
@capnspacehook We're collect more information from the customer but as a first step can you see if you're able to reproduce this issue on a Windows machine?

**Comment by russjones** [comment]
@capnspacehook How much work is left on this issue?

**Comment by capnspacehook** [comment]
I not much, once I can confirm the change is working with the customer we should be good to merge. Made a change based off of customer feedback and have been held up creating a dev build for them to try
