### ISSUE TITLE
Github Actions macOS workflow doesn't publish artifacts to clientbuilds bucket

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#24839]
The new GHA macOS workflow doesn't upload built artifacts to the legacy clientbuilds.gravitational.io S3 bucket however our automatic install script still relies on it:

https://github.com/gravitational/teleport/blob/master/lib/web/scripts/node-join/install.sh#L766

Until we can fully migrate to cdn.teleport.dev (which depends on [restoring checksums](https://github.com/gravitational/teleport/issues/18186)) we need to keep publishing our assets to the clientbuilds bucket as well.

**Comment by camscale** [comment]
This has been fixed on master and backported to v12 and v13. It will be in the whole mac pipeline backport to v11.

Still to be done is updating the `e` reference on the various branches which @r0mant will do when cutting the releases and will likely happen soon on master as part of normal development. I'll raise a PR to update `e` on master at the end of my day if it still is not done.

**Comment by camscale** [comment]
This is now present on v13, v12 and v11 with the `e` ref up-to-date to include it from the teleport repo.
