### ISSUE TITLE
tsh login timeout too aggressive, not configurable

### ISSUE THREAD

**Issue by aberoham** [gravitational/teleport#2483]
**What happened**:

`tsh login` timeout for SAML/OIDC is too quick for some scenarios, such as when the identity provider has non-immediate additional auth factors (such as email-based tokens).

```$ tsh login --proxy=[redacted]:443             
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:54679/[redacted]
error: timed out waiting for callback
```

**What you expected to happen**: For SAML/OIDC timeout to be configurable or simply longer than the current 60 second value

**How to reproduce it (as minimally and precisely as possible)**: Run `tsh login` against an auth provider you're not currently logged into and wait 60+ seconds.

**Environment**: 
- Teleport version (use `teleport version`): 3.x
- Tsh version (use `tsh version`): 3.x
- OS (e.g. from /etc/os-release): n/a

**Browser environment** 
n/a

**Relevant Debug Logs If Applicable**

n/a

**Comment by kontsevoy** [comment]
@klizhentas need your opinion on this, especially about simply increasing the default value to, say, 180 seconds.

**Comment by klizhentas** [comment]
sounds good
