### ISSUE TITLE
v13 webUI missing navigation scrollbar on login/invite screen

### ISSUE THREAD

**Issue by tobiaszheller** [gravitational/teleport#24885]
Expected behavior:
Navigation scrollbar should be visible.

Current behavior:
Navigation scrollbar  is not visible. On smaller windows it's not possible to click "sign in" or other buttons below. 

Bug details:
- Teleport 13 (both light and dark theme), (works on v12).

In attachment screens from v13 and v12.

<img width="1104" alt="v13-bug-webui" src="https://user-images.githubusercontent.com/14020794/233387026-dd7c98bb-9fcf-4e6a-8a4e-481fc22b0d56.png">
<img width="1143" alt="v12-working-webui" src="https://user-images.githubusercontent.com/14020794/233387041-610b6e0e-12ed-46be-a9eb-82520d02c335.png">

**Comment by kimlisa** [comment]
> I wonder if this is related to https://github.com/gravitational/teleport/pull/22437/files#r1148594941
> 
> I was hesitant to change the styling of `<body>`.

it is, i reverted them
