### ISSUE TITLE
Support TCP-Apps in Teleport Connect

### ISSUE THREAD

**Issue by kschoenberger** [gravitational/teleport#24962]
What would you like Teleport to do?

Teleport Connect should support setting up proxied tcp app connections.

What problem does this solve?

It would improve UX a lot. On the cli it is working pretty nice, but for unexperienced users or technicians that are not familiar with CLIs it is a nightmare to setup, handle and supporting them. From my point of view, the Teleport Connection Application would be the perfect place to implement that.

**Comment by zmb3** [comment]
Tracking this in #30421 now
