### ISSUE TITLE
Dark Theme selection doesn't persist for user

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#24971]
Expected behavior:

If I select dark theme that should persist when I log back in with the same user.

Current behavior:

Users have to select the theme every time they log in.

Bug details:
- Teleport version: 13
- Recreation steps

Log into browser
Select dark theme
Log out
Log back in with the same user in a incognito browser
Theme is back to light.

**Comment by zmb3** [comment]
This is not a bug and is working as intended. Theme preference is stored client side and by opening an incognito window you asked the browser to not consider any client side state.
