### ISSUE TITLE
Roles Page 

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#2497]
### Spec: 
The roles page allows Teleport users to define roles, in combination with RBAC, this can be a helpful tool to help define permissions. 

#### List of Roles
![image](https://user-images.githubusercontent.com/559288/62665354-cf115100-b933-11e9-97a9-fe3e353dadf9.png)

#### Delete Modal
![image](https://user-images.githubusercontent.com/559288/62665362-d59fc880-b933-11e9-9c63-0b501da42188.png)

**Comment by alex-kovoy** [comment]
done
