### ISSUE TITLE
Create/Edit Role Modal

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#2498]
### Spec:
Teleport Enterprise supports RBAC, https://gravitational.com/teleport/docs/ssh_rbac/  Roles can be created by `tctl` CLI to create the roles or via the UI. 

RBAC can be used to restrict access to sessions. https://gravitational.com/teleport/docs/ssh_rbac/
 
#### Enterprise Edition.
![image](https://user-images.githubusercontent.com/559288/62963331-a1099200-bdb5-11e9-9357-55cb3e4f4d12.png)

#### OSS Edition.
( Teleport OSS doesn't have roles admin in the UI )

**Comment by alex-kovoy** [comment]
done
