### ISSUE TITLE
Auth Connector Page

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#2500]
### Spec:

In the OSS version, show the github integration and upgrade modal. https://github.com/gravitational/teleport/issues/2506 

### Old Designs:
![image](https://user-images.githubusercontent.com/559288/62812026-e4fc4e80-bab8-11e9-9918-78dc324b3570.png)

![image](https://user-images.githubusercontent.com/559288/62812035-f2193d80-bab8-11e9-9f8f-d2d0c5733355.png)

![image](https://user-images.githubusercontent.com/559288/62812047-fcd3d280-bab8-11e9-899d-ed7508d4dbbc.png)

**Comment by alex-kovoy** [comment]
done
