### ISSUE TITLE
Slow host user lookups can make `tsh` much slower

### ISSUE THREAD

**Issue by capnspacehook** [gravitational/teleport#25014]
If the host `tsh` is running on is connected to a domain, host user lookups can potentially take multiple seconds. This can result in `tsh` commands taking anywhere from 10 seconds to 10 minutes. This can be solved by explicitly giving user behavior to `tsh` so it doesn't have to look it up itself.

Steps to solve:

- Ensure tsh v12.2.4+ is being used
  - https://github.com/gravitational/teleport/pull/24156 makes host user lookups timeout after 10 seconds
- Either set `TELEPORT_USER` environment variable or set the `--user` flag to the name of your Teleport User
- Either set `TELEPORT_LOGIN` environment variable or set the `--login` flag to the name of current host user
- Set `TELEPORT_HOME` environment variable to be the home directory of your current host user + \.tsh

Either `tsh` itself should make this more clear, or our docs should be updated. `tsh` now will tell the user that setting `--user` and `--login` might help when host user lookups timeout, but `TELEPORT_HOME` is never mentioned.

**Comment by zmb3** [comment]
Closing this - setting `TELEPORT_HOME` should no longer be necessary with #25950.
