### ISSUE TITLE
Trusted Clusters Page

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#2503]
[Teleport 4.2 UI - Cluster Spec ](https://docs.google.com/document/d/1W6MLWYxPJbr5qVY9co4CCVc5lEjPooX_augKXsdtXI0/edit#)

- [ ] As a user I want to be able to quickly see the status of connected cluster. 
- [ ] As a user I want to be able to view more than 40+ cluster on a page https://github.com/gravitational/teleport/issues/2502 

Additional information needed for Teleport Clusters:

- Number of Nodes
- Public Address (default if two urls are available)
- Teleport Version #
- Ability to remove cluster via frontend api

![image](https://user-images.githubusercontent.com/559288/62655589-2ce37000-b917-11e9-8ac9-4d26c54332f5.png)

**Comment by alex-kovoy** [comment]
done
