### ISSUE TITLE
Edit/New Trusted Clusters Modal 

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#2504]
### Spec:
We currently allow customers to configure Trusted Cluster Relationships via the Web UI. https://gravitational.com/teleport/docs/admin-guide/#example-configuration 

### Current Design:
This UI is only avaible in Teleport Enterprise
![image](https://user-images.githubusercontent.com/559288/62659806-44275b00-b921-11e9-9b3a-0cd13a4c741d.png)
![image](https://user-images.githubusercontent.com/559288/62659827-51444a00-b921-11e9-830f-b9151bc3608a.png)

Error Message State:
![image](https://user-images.githubusercontent.com/559288/62660096-f7904f80-b921-11e9-87bb-86b13f55aa42.png)

Connecting Status:
![image](https://user-images.githubusercontent.com/559288/62660232-5f469a80-b922-11e9-879f-ed7a85fbcd25.png)

Modal if a user tries to leave. 
![image](https://user-images.githubusercontent.com/559288/62660680-97021200-b923-11e9-886a-339a5de40a70.png)

**Comment by alex-kovoy** [comment]
done
