### ISSUE TITLE
Windows tsh login does not prompt for OTP when OTP and MFA registered

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#25051]
Expected behavior:

Receive prompt for OTP and webauthn device as in MacOS and Linux `tsh`.

Current behavior:

The user will only be able to authenticate with webauth devices.

Bug details:
- Teleport version: 12.2.4
- Recreation steps

1. Configure webauthn and set `second_factor` to `on`.  
2. Register a OTP and MFA device for a local user
3. Authenticate in windows with `tsh`
```powershell
tsh login --proxy=enterprise.teleportdemo.com --auth=local --user=steven
Enter password for Teleport user steven:
Using platform authenticator, follow the OS dialogs
ERROR: missing second factor
```

**Comment by zmb3** [comment]
Have you tried `tsh login --mfa-mode=otp`? If you don't specify a mode and there are multiple options, tsh is going to want to prefer the stronger webauthn mode.

**Comment by tobiaszheller** [comment]
It's related to https://github.com/gravitational/teleport/issues/17563
It actually accepts otp if you type it, just prompt for it is missing. Although it's not that trivial to fix.

**Comment by codingllama** [comment]
@stevenGravy, fixes should land in the next patches. Hopefully it's a bit better.
