### ISSUE TITLE
docs: Backup and restore docs will not work remotely with tctl

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#25052]
## Applies To
https://goteleport.com/docs/management/operations/backup-restore/

## Details
A `tctl get all` will return the error `this request can be only executed by an admin" when done remotely`.  This is due to users not retrievable.  Until this is allowed we should either show the individual calls or that you should do a `tctl get all` on the auth service host.

Also the trusted cluster retrievable can cause issues when trying to restore with it. We should confirm that following these instructions works for restoring all of these resources.

## Related Issues

https://github.com/gravitational/teleport/issues/21598

**Comment by ptgott** [comment]
Folding this issue into #31866, which includes other stale details that we should update.
