### ISSUE TITLE
docs: Example IAM policies in DynamoDB Docs are confusing 

### ISSUE THREAD

**Issue by tcsc** [gravitational/teleport#25056]
## Applies To
v13

## Details
There are two policy examples in the DynamoDB storage backend docs;
1. a simple grant-everything one for storing the Teleport Cluster State in one table, and
2. a detailed, fine-grained example that covers storing both the Cluster State and Audit Event Log in DynamoDB.

On a first reading, I wasn't able to discern that I needed to use 2 different policies for the State and Event tables - I used the same simple one for both, and there was quite a time lag between me using the wrong policy and the feeling the effects of it, so it was a pain to go back and find the appropriate docs. Once I _did_ find the issue, I found it confusing that the example policy for the event table overlapped with the cluster state table.

Once I knew what I was looking for, it was all crystal clear though.

Some possible changes:
 * Delineate the Cluster State, Audit Log and Combined policy example sections, or 
 * Split the combined policy and include the specific policy in sections for the Cluster State and Event Log cases, or
 * Something else...

**Comment by ptgott** [comment]
We have a PR that does some work on the DynamoDB IAM docs: https://github.com/gravitational/teleport/pull/23323

Is there anything in there that we should tweak? Thanks!

**Comment by webvictim** [comment]
I think that linked PR did a good job of explaining the required setup for the Teleport backend table, but it doesn't cover the audit events table - they have different schemas.

Backend - https://github.com/gravitational/teleport/blob/branch/v13/examples/aws/terraform/ha-autoscale-cluster/dynamo.tf#L4-L49
Audit events - https://github.com/gravitational/teleport/blob/branch/v13/examples/aws/terraform/ha-autoscale-cluster/dynamo.tf#L51-L110

It'd be good if we could add clarification that the two tables have different schemas, and give the required details for the audit events schema when people want to create it themselves. This just confused a prospect.
