### ISSUE TITLE
Shared Session Bar in Terminal 

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#2505]
### Spec
Teleport users can share sessions, this feature allows them to see who else is on the session. ( note: It isn't currently shown in the replay ) 

- [ ] Update to latest UI

### Current Design
![image](https://user-images.githubusercontent.com/559288/62661513-24466600-b926-11e9-9fe5-6fc61ff46367.png)

**Comment by alex-kovoy** [comment]
As per our discussion about terminal improvements https://github.com/gravitational/teleport/issues/2975, we need some new designs for the session participant indicator. Could we use a session tab to show a circle with a number of the users inside + rich tooltips?

**Comment by alex-kovoy** [comment]
![image](https://user-images.githubusercontent.com/7816406/68145673-55720a80-ff04-11e9-9dee-57740994ea14.png)


done
