### ISSUE TITLE
Provide install and uninstall in Tsh guide

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#25064]
## Applies To
https://goteleport.com/docs/connect-your-client/tsh/

## Details
Currently the `tsh` guide directs users to the general installation guide.  This is a complex guide meant for administrators and lots of options.  Our recommendation would be to install the signed MacOS `tsh` version, Windows `tsh.exe` download and the linux option.   We can also mention that Teleport Connect includes `tsh` and link to the steps to use it https://goteleport.com/docs/connect-your-client/teleport-connect/#using-tsh-outside-of-teleport-connect

**Comment by ptgott** [comment]
Closing as complete: https://github.com/gravitational/teleport/blob/d6ffc0cc389e8013d30b5bbd096e5ae64f5875c4/docs/pages/connect-your-client/tsh.mdx
