### ISSUE TITLE
Upgrade CTA in Teleport OSS 

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#2506]
## OSS CTA

With a focus on driving OSS users we should make more functionality visible to these users, and use the OSS to help show the full power of Teleport. 

For OSS Teleport we currently offer..

  | OSS | Enterprise
-- | -- | --
Roles | admin.yaml | Ability to create unlimited roles
SSO Connectors | github | Github, OIDC, SSO
Trusted Cluster | Unlimited ( yet they can only create via tctl now ) | Ability to create unlimited Trusted Clusters

We currently hide these elements in Teleport OSS, this means customers lack visibility into Truster Clusters, Easy editing for Github connector and lack context for Role definition.

### Roles

Version | Content | Button
-- | -- | --
Enterprise | ROLE BASED ACCESS CONTROL<br> Teleport role can be assigned based on user identity when used with single sign-on (SSO).Learn more in the cluster management (RBAC) section of online documentation. | Create New Role Button works as is.
OSS | ROLE BASED ACCESS CONTROL<br>Teleport OSS uses local login to access systems with a default admin role used to display preferences. Learn more about options for limiting access using [Teleport OSS](#) or get in touch to [Demo Teleport Enterprise](https://gravitational.com/teleport/demo) | Create New Role Button is disabled. Roles List.Show no roles… ( thinking about this )

### Roles

Version | Content | Button
-- | -- | --
Enterprise | AUTHENTICATION CONNECTORS<br>Authentication connectors allow Teleport to authenticate users via an external identity sources such as Okta, Active Directory, Github, etc. This authentication method is frequently called single sign-on (SSO).Please view our [documentation](https://gravitational.com/teleport/docs/enterprise/ssh_sso/)for samples of each connector. | Create New Role Button works as is.
OSS | AUTHENTICATION CONNECTORS<br>Authentication connectors allow Teleport to authenticate users via an external identity sources such as Okta, Active Directory, Github, etc. This authentication method is frequently called single sign-on (SSO).Please view our [documentation](https://gravitational.com/teleport/docs/enterprise/ssh_sso/)for examples for each connector.Teleport OSS supports Github as an SSO provider. [Contact us](https://gravitational.com/teleport/demo) to demo other SSO options. | Create New Role Button only provides Github.

**Editing Role:**
If someone was to try to edit the Github role to make it OSS, we should display an error message:

![image](https://user-images.githubusercontent.com/559288/80634055-a889cd80-8a0e-11ea-8008-968b68991ee5.png)

[Link to Teleport Spec](https://docs.google.com/document/d/1gMyMYFxPhYSMz9OT_BVCOTKmGPgtcYCOxmQBa9XddCA/edit#heading=h.9rl60yviwfji )

**Comment by benarent** [comment]
I have reviewed this from current master and ported over content. @alex-kovoy Can you please provide an estimate for development for this? So I can appropriately plan if it should go into 4.3 or 5.0.  There is strong internal feedback for getting this in sooner than later, so if need to reduce scope / streamline it, let's do that.

**Comment by alex-kovoy** [comment]
@benarent it should go to 5.0.
