### ISSUE TITLE
Cluster Meta Info

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#2507]
Additional information needed for Teleport Clusters: 

1. Number of Nodes
2. Public Address (default if two urls are available) 
3. Teleport Version # 
4. Ability to remove cluster via frontend api 

<img width="445" alt="screen shot 2019-01-18 at 11 50 51 am" src="https://user-images.githubusercontent.com/407237/51409776-98025c00-1b17-11e9-8a30-5d948b8bbb26.png">

[Teleport 4.2 UI - Cluster Spec](https://docs.google.com/document/d/1W6MLWYxPJbr5qVY9co4CCVc5lEjPooX_augKXsdtXI0/edit#)

**Comment by benarent** [comment]
Closing as I'm merging with https://github.com/gravitational/teleport/issues/2503
