### ISSUE TITLE
Resource Based Access Request Add All does not highlight properly

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#25096]
Expected behavior:
When you press `add all` all the selected resources should display the remove button which at the moment only the first resource is showing as selected.

Current behavior:
When the `Add All` button is pressed all the resources are selected, as you can see in screenshot the number of `resources added` at the bottom has increased but only the button for the first resource is displayed as `remove`. If you click `+add to request` the remove button appears then you can click again to remove it from the request.
![Screenshot 2023-04-24 at 1 48 32 PM](https://user-images.githubusercontent.com/48836604/234088719-62617bbe-9351-4903-84ed-c19b917ae307.png)

Bug details:
- Teleport version 12.1.0
- Recreation steps: Use the add all button in resource-based access request
- Debug logs

**Comment by zmb3** [comment]
@rudream low priority, but if you find yourself working in the UI and this looks like a quick fix feel free to take care of it. If it ends up being more difficult just let me know and we'll prioritize it accordingly.

**Comment by rudream** [comment]
I'm not sure when this regressed, but it appears to have been fixed since then and I can't reproduce this on `v12.4.15`, `v13.3.7`, or `v14.0.0-alpha.2`.
