### ISSUE TITLE
[Feature Request] `tsh ls` default ordering

### ISSUE THREAD

**Issue by vad** [gravitational/teleport#2511]
**What happened**:

`tsh ls` apparently sorts by "Node ID".

**What you expected to happen**:

IMHO it should sort by "Node Name" instead, or it should allow to configure the default ordering (using a configuration file). The use case is that I often forget the name of a node. We call nodes with a word + a number:

- aword1
- aword2
- aword6
- anotherword6

And so on. I remember the word but usually not the number, so I currently use `grep` to filter.

Having results sorted by "Node Name" would allow me to easily go though results to find what I want.

**Environment**:
- Teleport version (use `teleport version`): v3.0
- Tsh version (use `tsh version`): v3.0

**Comment by kontsevoy** [comment]
## Proposal

Agree with @vad. Let's sort by node name by default.
