### ISSUE TITLE
Persian alphabet in web terminal

### ISSUE THREAD

**Issue by bahmanjafari** [gravitational/teleport#25134]
Expected behavior:

If you're using the web terminal and the cat command or vim to open a file that contains the Persian alphabet, you may encounter issues with the file's formatting. The Persian alphabet may appear jumbled or disordered.

Current behavior:
Show the Persian alphabet correctly in the web terminal

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
Closing in favor of #16627
