### ISSUE TITLE
Design for Stripe Error states -

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#25167]
Error states: 

- Failed Stripe API call
- Expired payment method
- Failed Payment

**Comment by rishibarbhaya-design** [comment]
Hi,

I've designed Stripe error states based on their official documentation.
I already shared it in our channel just sharing here to keep track.

Where to find designs?
Go to Figma -> In-Progress Work -> Ticket #3524 | Design for Metering and Billing UI -> **Scroll Down to "Error States"** 
Sharing an image for reference

![Image](https://user-images.githubusercontent.com/88441969/235491567-6f2c44fb-6e0d-4011-9389-ce66c2cf98ee.png)
