### ISSUE TITLE
Document DynamoDB HA limitations

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#25170]
>Note
No more than two processes at most should be reading from the same streams shard at the same time. Having more than two readers per shard can result in throttling.
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html

Due to the linked restrictions from AWS there should be no more than 2 Auth Servers in a cluster that uses DynamoDB to store cluster state.

**Comment by nitish799** [comment]
can you explain it in more detail ?
