### ISSUE TITLE
Provide a windows 32bits tsh binary

### ISSUE THREAD

**Issue by mgarstecki** [gravitational/teleport#2517]
**What happened**:

I didn't find a Windows 32bits version of tsh on the downloads page.
I had to build one from source, cross-compiling from Linux.

**What you expected to happen**:

I wanted to download a 32bits version of the build :)
32bits installs of Windows are unfortunately still common in corporate environments, including my current customer.

**Feasibility**

I managed to build a working version from source, cross-compiling from Linux with mingw :

`GOOS=windows GOARCH=386 CXX=i686-w64-mingw32-g++-win32 CC=i686-w64-mingw32-gcc-win32 CGO_ENABLED=1 go build -o build/tsh.386.exe -ldflags '-w -s' ./tool/tsh`

Minimal changes should be necessary to add this configuration to a build pipeline that already manages windows 64bits builds.

**Comment by zmb3** [comment]
Closing this, as 32-bit Windows is not something we're looking to support at this time.
