### ISSUE TITLE
tsh login timeout for fetching login alerts is too aggressive

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#25239]
We use a 500ms timeout when fetching alerts in `tsh status` to avoid slowing the command down too much.

This change inadvertently also applied the 500ms timeout to `tsh login`.

Since login is interactive and already takes a few seconds, we should remove the timeout from `tsh login`.

**Comment by rushikeshsuryawanshi** [comment]
Can i work on this issue ?

**Comment by smallinsky** [comment]
related: https://github.com/gravitational/teleport/pull/25137
