### ISSUE TITLE
Web UI and CLI list AWS DynamoDB dbs listed in different format

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#25262]
Expected behavior:

DynamoDB dbs would be listed as "AWS DynamoDB"

Current behavior:

DynamoDB shows as "dynamodb dynamodb".  This doesn't match other DB listing.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/60704961/234883819-66d68bac-c8fd-49c3-a50a-f3e8739912e8.png">

Bug details:
- Teleport version: 12
- Recreation steps

Add a dynamodb db and list in the Web UI, `tsh db ls -v` and Teleport Connect

**Comment by Tener** [comment]
@greedy52 PTAL
