### ISSUE TITLE
Expose access request TTL in the web UI

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#25267]
By default, access requests have a 1 hour TTL. Requests that are not approved prior to expiration will disappear and become unusable.

`tsh` exposes a `--request-ttl` flag to override this 1 hour TTL, but no such option exists in the web UI.

**Comment by zmb3** [comment]
This is working as designed. The default access request TTL is 1 hour. You can specify a custom TTL with `tsh`, as documented here: https://goteleport.com/docs/access-controls/access-requests/role-requests/#using-ttls-with-access-requests

Should we change this from `bug` to `feature-request` to expose the request TTL to the web UI?

**Comment by stevenGravy** [comment]
> This is working as designed. The default access request TTL is 1 hour. You can specify a custom TTL with `tsh`, as documented here: https://goteleport.com/docs/access-controls/access-requests/role-requests/#using-ttls-with-access-requests
> 
> Should we change this from `bug` to `feature-request` to expose the request TTL to the web UI?

Yes that would be a big help to the ux

**Comment by zmb3** [comment]
Reopened and update the description to match the feature request.
