### ISSUE TITLE
regression "could not verify PROXY signature" when AWS load balancer proxy_protocol enabled

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#25283]
### Expected behavior:

Using proxy protocol on AWS should continue to work when upgrading from 12.1.x to 12.2.x

### Current behavior:

After upgrading from to any Teleport 12.2.x from 12.1.5, an AWS instance of Teleport with the `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"` annotation on their aws load balancer results in this error appearing in the Teleport proxy logs. It doesn't matter whether `proxy_service.proxy_protocol` is on or off, the same error occurs.

Looking at the stacktrace, I believe https://github.com/gravitational/teleport/pull/23418 introduced this behavior.

```
teleport-proxy-7476f7857-bsmf6 teleport 2023-04-27T15:08:22.261693236-04:00 2023-04-27T19:08:22Z WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *errors.errorString could not find signature data on the proxy line\nStack Trace:\n\tgithub.com/gravitational/teleport/lib/multiplexer/proxyline.go:474 github.com/gravitational/teleport/lib/multiplexer.(*ProxyLine).VerifySignature\n\tgithub.com/gravitational/teleport/lib/multiplexer/multiplexer.go:441 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detect\n\tgithub.com/gravitational/teleport/lib/multiplexer/multiplexer.go:267 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\truntime/asm_amd64.s:1598 runtime.goexit\nUser Message: could not verify PROXY signature\n\tcould not find signature data on the proxy line (logs containing \"could not verify PROXY signature\" were seen 3 times in the past minute)" loglimit/loglimit.go:181
```

This error will periodically repeat with the log limiter saying how many times it has been seen in a given timeframe. The teleport web ui is inaccessible.

### Bug details:
- Teleport version - (reproduced with 12.2.2 but all 12.2.x versions appear to be affected)
- Recreation steps - see included helmvalues.yaml. That values file worked with 12.1.2, but produced the error by simply upgrading to 12.2.2
- Debug logs - see above

[helmvalues.yaml](https://github.com/gravitational/teleport/files/11347297/helmvalues.yaml.txt)

--

edit:

the other symptom here is that all connections to the proxy web port fail.

Chrome:

> ### This site can’t be reached
> **teleport.example.com** unexpectedly closed the connection.
> Try:
> * Checking the connection
> * [Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
> 
> ERR_CONNECTION_CLOSED

curl:

```
curl -v https://teleport.example.com/
*   Trying 18.216.109.72:443...
* Connected to teleport.example.com (18.216.109.72) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to teleport.example.com:443
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to teleport.example.com:443
```

Taking a packet capture in the pod where the Teleport proxy is running, the ProxyV2 packet comes in as expected, but then Teleport sends a FIN immediately after that, before receiving the TLS client handshake attempt.

**Comment by zmb3** [comment]
@AntonAM are we good to close this one?

**Comment by AntonAM** [comment]
@zmb3 I'm pretty sure it was fixed, but if @programmerq can retest it for 100% confidence, that would be great.

**Comment by programmerq** [comment]
> @zmb3 I'm pretty sure it was fixed, but if @programmerq can retest it for 100% confidence, that would be great.

I actually tested it as soon as 12.2.5 went live. I was hitting refresh until the helm chart and docker images were up.

My lab with the issue started working immediately once the 12.2.5 pods were up.

Thanks for such a quick turnaround!

**Comment by AntonAM** [comment]
Perfect, thanks Jeff!
