### ISSUE TITLE
ARM64 builds for the Teleport Slack and Pagerduty plugins

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#25416]
What would you like Teleport to do?

Customer ask for AR64 builds of the Slack and Pagerduty Plugin. Currently we only provide linux-amd64 binaries. 

What problem does this solve?
The customer wants to have the option of AMD64 and ARM64. Per customer, ARM64 is a popular platform with AWS Graviton servers. 

If a workaround exists, please include it.
Our source code for plugins is publicly available. A workaround is to compile this source code for ARM64.

**Comment by zmb3** [comment]
FYI, this is being tracked at https://github.com/gravitational/teleport-plugins/issues/539

**Comment by camscale** [comment]
@zmb3 That issue is for Apple ARM64 builds (M1/M2). We do not currently release slack and pagerduty plugins for any architecture on MacOS AFAIK. This issue would be for Linux builds.

**Comment by fheinecke** [comment]
As of v16 we will be releasing both amd64 and arm64 builds of all plugins.
