### ISSUE TITLE
Support for Gravatar

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#25420]
What would you like Teleport to do?

Have the ability to support Gravatar icons/images for signed-in users.

What problem does this solve?

Adds support for Gravatar. Currently there isn't any support in Teleport.

![image](https://user-images.githubusercontent.com/1424442/235504895-0aba8661-2267-4f92-aa00-70a426ffaa85.png)

![image](https://user-images.githubusercontent.com/1424442/235504971-ebe1a1df-dc7a-4483-86e4-daa4a3d9c7fc.png)

When signing in with GitLab as an SSO provider it passes along a picture/gravatar setting. Teleport doesn't take advantage of this.

If a workaround exists, please include it.

None today.

**Comment by zmb3** [comment]
Not planned.
