### ISSUE TITLE
Design automatic agent installation

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#25468]
Proposed UX for setting up auto-install:

- First version: single database agent / SINGLE region - can't select databases across multiple regions
- We _think_ we can we infer region and VPCs and subnets from which database(s) – investigation in progress
- Two Use cases:
  - USER WITH NO AGENT: Need to communicate to the user that a container will be spun up to host their agent
  - USER WITH EXISTING AGENT: skip all agent details entirely
  - Additional decision point
    - Need ability to escalate AWS IAM permissions for users who have previously set up the AWS integration
      - Provide a link to the page + updated permissions to copy/paste

**Comment by roraback** [comment]
On hold for the moment, pending more Engineering guidance

**Comment by roraback** [comment]
Updated description. Ready for design!

**Comment by roraback** [comment]
@marcoandredinis Open question: Is there anything to input for the agent container? E.g. a name to be used in AWS?

**Comment by marcoandredinis** [comment]
> @marcoandredinis Open question: Is there anything to input for the agent container? E.g. a name to be used in AWS?

We have 3 things to name:
Cluster https://docs.aws.amazon.com/AmazonECS/latest/developerguide/clusters.html
Task Definition https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definitions.html
Service https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html

The service is what starts everything: run this Task (eg Teleport DB agent) within this Cluster.

We can either:
- allow them to name all 3 pieces (providing some defaults)
- hard code for all of them resources to something like (letting the user know what those are)
  - Teleport-<TeleportClusterName> for Cluster
  - Teleport-<TeleportClusterName>-DatabaseAgent for Service
  - Teleport-<TeleportClusterName>-DatabaseAgent for Task

No strong opinion here.
It will be slightly less development if we hard code things, but don't let that be the deciding factor

**Comment by r0mant** [comment]
This was done.
