### ISSUE TITLE
Design integration management (edit) page

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#25467]
Management page for editing an integration. (Starting with AWS integration)

**Comment by rishibarbhaya-design** [comment]
Starting with AWS Integration adding a screen.
A warning modal will be added once detailed are received.

Minor revisions can be expected once new elements/functionalities are added.


![Image](https://user-images.githubusercontent.com/88441969/236851611-8494a744-194b-4cc5-a324-5e5c08628d5b.png)
