### ISSUE TITLE
Change the `install-linux.mdx` partial to use our one-liner

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#25505]
## Applies To
`docs/pages/includes/install-linux.mdx`, plus pages that include it

## Details
We have a simplified, one-line command to use to install Teleport on Linux (https://goteleport.com/download/):

<img width="833" alt="Screenshot 2023-05-02 at 3 27 42 PM" src="https://user-images.githubusercontent.com/25250668/235766045-2d07ec9e-d2a3-4453-9caa-1a4e0188c23b.png">

Let's edit the `install-linux.mdx` to use this command.

**Comment by stevenGravy** [comment]
Would be good to confirm if we plan to keep this long term and if there's a similar enterprise version.
