### ISSUE TITLE
attempting to create a agentless moderated session does not return an error

### ISSUE THREAD

**Issue by capnspacehook** [gravitational/teleport#25522]
Expected behavior:

Joining agentless moderated session is successful

Current behavior:

Joining agentless moderated session fails

Bug details:
- Teleport version: v13

**Comment by zmb3** [comment]
What is an agentless moderated session? Moderation requires the teleport agent, no?

**Comment by capnspacehook** [comment]
Yeah you're probably right. Added it to the test plan without thinking too hard about it. Will just check the items off and make a PR to remove those tests for next time.

**Comment by zmb3** [comment]
Well I'd still be interested to know what the failure looks like. If it's a non-obvious error, there's probably some work left to be done here.

**Comment by capnspacehook** [comment]
Yep, I closed a bit prematurely working on presenting a clear error to the user
