### ISSUE TITLE
Auto-discovery of apps in Kubernetes

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#25538]
## What 

Add support for Teleport Discovery service to automatically discover APPs in Kubernetes clusters

## How

Extend Teleport `discovery_service` capabilities to scan Kubernetes Services and register them in Teleport if they match the selector.
Currently, the Discovery service supports AWS, GCP, and Azure sources and we aim to add another (kubernetes) where the service will auto-populate the Teleport catalog with Kubernetes apps.

Split: 
- [x] RFD
- [x] Add support for discovery_serivce to scan Kubernetes Services and enroll them as dynamic Apps in Teleport.
- [x] Update Teleport helm charts to support the new feature.
- [x] Documentation changes

**Comment by zmb3** [comment]
See also #19976

**Comment by jtsai-quid** [comment]
Hello team, any schedule release for shipping this feature?

**Comment by AntonAM** [comment]
@jtsai-quid yes, it's currently scheduled to be released in Teleport v14, you can always check it at https://goteleport.com/docs/upcoming-releases/
