### ISSUE TITLE
Add the ability to persist servers and prevent cleanup

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#25705]
What would you like Teleport to do?
Currently, after 10 minutes when a node goes offline, it is removed from the server list by Teleport (give or take some delay when using DynamoDB storage).  The request is to be able to have servers that will not be removed from the list when disconnected and would only be removed manually by an administrator.  A per-node and cluster-wide setting would be ideal.  Some possible solutions:

1) Configuration option to disable the node cleanup process
2) Configuration setting that flags nodes as permanent resources that should not be affected by cleanup
3) Provide a static resource list that the user configures to indicate permanent resources

What problem does this solve?
There are access use cases where Teleport servers may go offline for extended periods of time due to the nature of the server's workload (remote servers, mobile servers, emergency servers, etc).  Some users have expressed an interest in being able to continuously see that these resources are configured in Teleport and just offline, rather than being able to only view current online resources.  These users tend to have a very static list of Teleport servers where going offline is expected, but the same servers are meant to come back online later.

If a workaround exists, please include it.
None, offline resource will be cleaned up out of Teleport

**Comment by zmb3** [comment]
Looks like the same request as #3657.

**Comment by pschisa** [comment]
Agree, closing in favor of #3657
