### ISSUE TITLE
Can't enter a db user to test if usernames allowed is regular exps in discovery

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#25722]
Expected behavior:

Able to enter a username and database name to test with.  

Current behavior:

The `*` will show but you can't enter different usernames to test with.  This same issue is in 12.

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/60704961/236526028-35aa012f-b965-4f8c-9ab1-b8f113aca8cb.png">

Bug details:
- Teleport version: 13 alpha, 12
- Recreation steps

1. Create a user with db user and names with `*` of allowed.
2. Follow the RDS enroll in 13 or 12
3. On the test connection page

**Comment by marcoandredinis** [comment]
Closed by https://github.com/gravitational/teleport/pull/40931
