### ISSUE TITLE
`TestFileTransferEvents` flakiness

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#25738]
From today: 

* https://github.com/gravitational/teleport/actions/runs/4895776441

Other instances:

* https://github.com/gravitational/teleport/actions/runs/4935889325/jobs/8822760177#step:6:298

Test was added in https://github.com/gravitational/teleport/pull/24580.

**Comment by zmb3** [comment]
I ran 200 iterations locally and couldn't reproduce.

**Comment by greedy52** [comment]
https://github.com/gravitational/teleport/actions/runs/9007863661/job/24748642306
```
=== Failed
=== FAIL: lib/web TestFileTransferEvents (6.80s)
    apiserver_test.go:1564: 
        	Error Trace:	/__w/teleport/teleport/lib/web/apiserver_test.go:1564
        	Error:      	expected to receive a file transfer event
        	Test:       	TestFileTransferEvents
```

**Comment by hugoShaka** [comment]
Hit today on master: https://github.com/gravitational/teleport/actions/runs/20603143624/job/59173065457

```
=== FAIL: lib/web TestFileTransferEvents (5.53s)
    apiserver_test.go:1898: 
        	Error Trace:	/__w/teleport/teleport/lib/web/apiserver_test.go:1898
        	Error:      	expected to receive a file transfer event
        	Test:       	TestFileTransferEvents
```
