### ISSUE TITLE
tctl: json format for users add/ls and  tokens ls

### ISSUE THREAD

**Issue by jeremy-clerc** [gravitational/teleport#2573]
Would it be ok to add json output for `tctl users add/ls` and  `tctl tokens ls`, like `nodes add` ?

This would be helpful to create / delete users via scripts.

I have written the code https://github.com/jeremy-clerc/teleport/commit/a821771e08cec543c0ae4e2f35c4ba12cf774184 as I need it, if you think it is worth integrating it, I will create the pull request.

**Comment by Pluggi** [comment]
What is the current status for this issue?

**Comment by russjones** [comment]
This has been implemented.
