### ISSUE TITLE
Document Cloud-specific maintenance window process

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#25743]
## Applies To

There should be a screenshot in the docs illustrating how to find where to set the maintenance window for a tenant.

## Details

Many users don't know that a maintenance window can be set. A doc page that visually shows where to find the option would be super handy!

**Comment by zmb3** [comment]
This is documented: https://goteleport.com/docs/choose-an-edition/teleport-cloud/faq/#are-upgrades-times-configurable-for-my-teleport-enterprise-cloud-tenant
