### ISSUE TITLE
I need a new link to set up my password

### ISSUE THREAD

**Issue by johnbherring** [gravitational/teleport#2574]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by klizhentas** [comment]
Hey John, 

I'm not sure how we can help with your request. If you have a question about using teleport, please use our [community forum](https://community.gravitational.com/)
