### ISSUE TITLE
RDP proxy support [research]

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2577]
# Introduction

Numerous users have expressed interest in adding support for RDP protocol to Teleport proxy. This is a research ticket, i.e. we need to:

* Write a design document and add a link to it.
* Break the implementation down into smaller and more specific tickets.
* Assign priority / milestones.

## Proposals

* Consider rolling this out in stages. For example we can add basic functionality with RBAC first, and implement RDP recording later. 
* Collect requirements. Do people want Teleport to be the only proxy, or a "proxy of proxies"? Remote Gateway is included with Windows Server, so what additional functionality they're looking for?

**Comment by aberoham** [comment]
re: `additional functionality they're looking for` -- a large ticketing company delivers their 90's era Delphi app via RDP from venue box offices into their primary datacenters. IIRC simply running MSFT's gateway wasn't sufficient, auditors required putting another device between any client's VPN/LAN and the datacenter-hosted Windows TCP/IP stack. (In that case the solution involved hardware load balancers in front of a farm of MSFT RDP gateways & virtual desktops)

re: `RDP recording`, @shamsalmon had this is a key requirement, hinted that he had a DIY method but much preferred ssh+rdp recordings all in one.

**Comment by aberoham** [comment]
Back in Feb of '18, well known footwear & apparel company that was BLESS-curious would have been more interested if we had "RDP integration within the same product used for SSH bastion."

**Comment by aberoham** [comment]
RDP mention in [private notes](https://docs.google.com/document/d/1P9S1Yk9tTCnuYg3lq3e1SucoJbsWRx2CHumr0T1xVDE/edit?usp=sharing) from a educational SaaS company that was facing into cyclic SOC2 compliance testing. Installing+operating Teleport was too complex for their DevOps engineer.

**Comment by kontsevoy** [comment]
[supporting docs](https://docs.google.com/document/d/17G9DT8UAhV2wiJ-AiOvYaxyk9hYzYk-SUDW3G7JG2uE/edit)

**Comment by ghakfoort** [comment]
Is there any news about RDP support in Teleport? It would be a very nice feature to add to Teleport.

**Comment by awly** [comment]
@ghakfoort I'm researching and prototyping this right now.
Teleport will have remote desktop support, which may or may not be RDP-based.

**Comment by awly** [comment]
Design in progress: https://github.com/gravitational/teleport/pull/7725
