### ISSUE TITLE
Restricted Shell support + Exfiltration [research]

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2578]
## Problem

There's enough interest in adding support for restricted sessions (shells) to Teleport. The existing options that can be combined with Teleport do not seem to be satisfactory ("security theater" argument). 

This is a research ticket. To address it:

* Write a design document and attach it to this ticket.
* We'll break the implementation down to smaller tickets.
* Prioritize / milestone (if approved)

## Questions / Proposals

I strongly believe that restricted shell is not a core Teleport functionality. It must not be included (complied) into the `teleport` binary. Also, it needs to be a wrapper around existing shells, for  obvious reasons. Let's consider the following options:

* `tshell` binary which gets compiled into `build` directory.
* New open source repository?
* Consider an implementation, where `tshell` is an easy to use wrapper around `bash` or any other shell (whatever's in the user profile on a machine) which uses built-in protections (namespaces, SELinux, etc).
* Make it easy to configure.
* Make it available to open source users (how?)
* Ideally should be perfectly usable with OpenSSH or as a built-in shell to inject into containers.

## Market research

Also let's take a look at proprietary implementations. I've looked into one of them (not to be named here) and it falls into "security theater" category i.e. doesn't add any value in terms of security.

**Comment by bardiashahali** [comment]
[supporting docs](https://docs.google.com/document/d/1sJlVB-opiS6ao_4rX2oW7tHXJ3fW7P1bjpy2ImQlFOw/edit)
