### ISSUE TITLE
Support configuring dynamodb for on-demand mode via config file

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport#25829]
Using dynamodb in on-demand mode has been our recommended deployment strategy for a while now, but our configuration files still only provide options for deployment with provisioned capacity.  We should add a config option for on-demand mode.

Additionally, it would be preferable if there was a way for teleport to assist in switching to on-demand mode for an existing cluster.  Currently, teleport only applies dynamo config options during table creation, and subsequent changes to the config file have no effect.  This is a reasonable default since many users may want to manually tune their databases, but it also increases the complexity of managing teleport since an alternative procedure needs to be added for updating existing deployments.  For backwards-compatibility we will need to keep the current default behavior, but we should add a way to opt into having teleport update dynamo parameters on change.

Ex:

```yaml
teleport:
  storage:
    type: "dynamo"
    on_demand: yes
    auto_apply_changes: yes
```

note: in the interest of keeping rolling updates smooth, it is probably best to have any "apply changes" operation be lazy/periodic rather than running immediately on start, the way table creation does.

**Comment by r0mant** [comment]
This was implemented in https://github.com/gravitational/teleport/pull/27674, we'll backport to v13 as well. cc @lxea
