### ISSUE TITLE
AWS Guide

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2583]
Add a guide for AWS:
https://docs.google.com/document/d/1nqYTmcBR_zbjkrASsS_szT4v4LBUypS1ar1ch5wiU2w/edit

**Comment by benarent** [comment]
Note: 
Along with AMI Usage, we also need to come up with 
- [ ] High level best practices for AWS
- [ ] Example Terraform / Ansible / Automation for setting up Teleport.

**Comment by benarent** [comment]
I'm going to close this issue. We'll address a few more AWS edge cases with our How To Guides.


For customers who find this ticket looking for extra AWS support. I would recommend these links. 
https://gravitational.com/teleport/docs/aws_oss_guide/
https://github.com/gravitational/teleport/tree/master/examples/aws
