### ISSUE TITLE
Rancher-Teleport Support

### ISSUE THREAD

**Issue by earlytracks-admin** [gravitational/teleport#2584]
Teleport Support Rancher

**What happened**:
I'm trying to setup Teleport to use it as an kube-proxy for my rancher/kubernetes cluters using the same way used on the documentation based on gke-cloud as rancher have an extra layer of authentication.

**What you expected to happen**:
Connect to my kubernetes/rancher cluster using Teleport as an proxy
**How to reproduce it (as minimally and precisely as possible)**:
Setup a Rancher Server
Use the gke-cloud script to generate an kubeconfig.

**Environment**:
- Teleport version (use `teleport version`): 3.1.7 OSS
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release): debian 9
- Rancher SSL Termination using letsencrypt
- Rancher:latest

**Relevant Debug Logs If Applicable**
``WARN [PROXY:KUB] Failed to get certificate for user: test, groups: [system:masters], cluster: bastion-example-ssh: {"message":"Post https://rancher.example.com:8443/k8s/clusters/c-mqg7f/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: x509: certificate signed by unknown authority"}.

Have a nice week-end folks.

**Comment by klizhentas** [comment]
This support question has been moved [here](https://community.gravitational.com/t/rancher-teleport-support/95)

Please use community.gravitational.com to ask support questions.
