### ISSUE TITLE
`tsh ls` can't be escaped like `tsh login`

### ISSUE THREAD

**Issue by aberoham** [gravitational/teleport#2587]
**What happened**: `tsh --proxy=[hostname] ls` can't be escaped if hostname is resolvable but not listening on the given hostname. `tsh` gets hung dialing, can't be escaped from w/`CTRL-C`. Example --
```
➜  teleport tsh --proxy=hostnamedoesnotexist.dev ls
error: Get https://hostnamedoesnotexist.dev:3080/v1/webapi/ping: dial tcp: lookup hostnamedoesnotexist.dev: no such host

➜  teleport tsh --proxy=www.google.com:443 ls
error: "<!DOCTYPE html>[snip]<p>The requested URL <code>/v1/webapi/ping</code> was not found on this server.  <ins>That’s all we know.</ins>\n"

➜  teleport tsh --proxy=www.google.com ls
^C
^C
[hung, can't escape]
^C
^C
error: Get https://www.google.com:3080/v1/webapi/ping: dial tcp [2607:f8b0:4009:803::2004]:3080: i/o timeout
```

**What you expected to happen**: `CTRL-C` would cancel the connection attempt, similar to how it now works with `tsh login`

**Environment**:
- Teleport version (use `teleport version`): Teleport v3.1.7 git:v3.1.7-0-g44074d74 go1.11.4
- Tsh version (use `tsh version`): Teleport v3.1.7 git:v3.1.7-0-g44074d74 go1.11.4
- OS (e.g. from /etc/os-release): OSx

**Comment by kontsevoy** [comment]
I think this happens because `tsh` drops into "raw terminal" mode too early, i.e. _before_ it starts dialing, not after.

**Comment by klizhentas** [comment]
can't reproduce in 4.0, feel free to reopen if can reproduce

**Comment by klizhentas** [comment]
```
$ tsh ssh --proxy=www.google.com ls
^Cerror: Get https://www.google.com:3080/v1/webapi/ping: context canceled
```
