### ISSUE TITLE
teleport should drop web connections on user delete

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#259]
## Description

Here's what happens when teleport user is deleted during live session:
- The web page does not indicate anything
- Attempt to open new browser window redirects to logout
## How success looks like
- [ ] If there are any connected sessions to the terminal, they should be all dropped
- [ ] UI should forward user to login screen

**Comment by kontsevoy** [comment]
I propose we punt it indefinitely. Yes it would be nice but it's not an easy change. Realistically we have many months of more pressing features to implement, so this will be sitting here forever.

**Comment by kontsevoy** [comment]
Closing this, as it's not compatible with SAML/OIDC and overall system design (even with local auth a user can be deleted using etcd CLI).
