### ISSUE TITLE
kubectl configuration is wrong when login in to a trusted cluster from central teleport instance

### ISSUE THREAD

**Issue by MoJo2600** [gravitational/teleport#2592]
Have a question? Please use [Our Forum](https://community.gravitational.com)

My setup is as follows: I have one main teleport cluster (teleportmain), which is set up with the terraform example scripts. Teleport is listening on https://teleportmain.mycompany.foo:443. I added a second cluster inside kubernetes (remote) the url is https://remote.mycompany.foo, set up with the helm chart from the example scripts. In both cases i updated the version of teleport to 3.1.7. I joined the clusters as trusted clusters and i am able to connect from teleportmain to remote. 

**What happened**:
When i do a login to the cluster with `tsh --proxy=teleportmain.mycompany.foo login remote`
the login succeeds and the kubctl configuration is extended with the configuration. But when i do a context switch and try something like `kubectl get ns` i receive the error `Unable to connect to the server: x509: certificate signed by unknown authority`. After inspection of the configuration i see, that the kubectl configuration is set to `https://remote.teleportmain.mycompany.foo:443`. When i adjust the configuration to https://remote.mycompany.foo:3026 kubectl is working. I then changed the url of the remote cluster to match https://remote.teleport.mycompany.foo, but the port is still wrong (443 instead of 3026). When i connect directly to the remote cluster, the configuration is correct `tsh --proxy=remote.teleport.mycompany.foo --auth=local login`
Changing the setting of `kubernetes.public_addr: ['kube.example.com:3026']` in teleport.yaml has not effect.

**What you expected to happen**:
I expected two things:

1. teleportmain.teleport.foo is my central proxy for accessing everything behind it. I do only have to expose this service to get access to the trusted clusters behind it. So the url should be https://teleport.mycompany.foo
2. The port should be set correctly to whatever is correct in this case

**How to reproduce it (as minimally and precisely as possible)**:
Connect a teleport cluster running inside a kubernetes cluster which is set up with the provided helm chart to a teleport cluster that has been set up with the provided terraform scripts. Try to login to the remote cluster and use kubectl to query resources.

**Environment**:
- Teleport version (use `teleport version`): Teleport v3.1.7 git:v3.1.7-0-g44074d74 go1.11.4
- Tsh version (use `tsh version`): Teleport v3.1.7 git:v3.1.7-0-g44074d74 go1.11.4
- OS (e.g. from /etc/os-release): MacOS Mojave 10.14.3 (18D109)

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by klizhentas** [comment]
Christian,

My apologies for the slow response.

This looks a lot like the issue https://github.com/gravitational/teleport/pull/2526 where not all certificate authorities were fetched by default, therefore the client did not recognize the server's certificate authority.

The fact that it's an x509 error indicates that the issue is not a configuration error, rather some logic error in the code.

Can you please paste your configuration here? I'd be glad to help in the slack channel as well, it'd be faster to exchange debug logs there rather than using github.

In addition to that, can you please use `tsh login --debug` in your first example and paste the logs here (or if they contain domain information, paste them in community slack chat directly to me).

Thanks
Sasha

**Comment by drewwells** [comment]
I'm seeing the same problem, it appears to be a general issue calling into trusted servers. If I have a `main` and `east`. I setup `east` as a trusted cluster to `main`.

`kubectl` calls `main` which attemps to connect to main's kube-apiserver, not `east` kube-apiserver. This is reproducible by using real kubeconfigs for each auth-service. If you deploy within the cluster, both clusters access `kubernetes.default.svc` and show this x509 error.

**Comment by webvictim** [comment]
This issue should be fixed in Teleport 4.1.1.
