### ISSUE TITLE
Add Standardized Typography sizes to Storybook

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#25925]
**What would you like Teleport to do?**
Long-term, I'd like us to standardize type sizes based on the updated design system. Short-term, though, I'd love for us to at least add the new type sizes to our component library/design system so that we can use them consistently in all new and updated features.

**What problem does this solve?**
Adds more consistency and predictability to our product and makes it easier for engineers to match designs.

**If a workaround exists, please include it.**
This really _is_ the workaround: a full overhaul takes a lot of time and energy, but to start we can add the type system to our library and use it whenever we add features or pages or substantially edit existing ones.

Type scale is listed in our [design system file in Figma](https://www.figma.com/file/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?node-id=7020%3A34015&t=B7QUzPzCE9TYFKrc-1).

**Comment by zmb3** [comment]
@roraback I'm going to assume this is covered by the typography task in #37260 and close it.

Feel free to reopen if I was mistaken.
