### ISSUE TITLE
Teleport Connect should have a tab for applications

### ISSUE THREAD

**Issue by audip** [gravitational/teleport#25941]
What would you like Teleport to do?

Teleport Connect in it's preview state already is a useful app, but it doesn't cover the internal applications which then requires using the Web App to access internal tools. 

It'd be great if Teleport Connect can have an applications tab in addition to kubes, servers and databases tabs.

![Screenshot 2023-05-09 at 23 53 07](https://github.com/gravitational/teleport/assets/4290846/7410343f-05dc-4829-a4db-e6fe7eb8e28a)

What problem does this solve?

Having to go to Teleport Web App for just accessing internal apps

If a workaround exists, please include it.

Workaround is to use web app for just one use-case

**Comment by DoumLaberge** [comment]
It should also support TCP app.  A way to start proxying a TCP app at a press of a button could be useful for my users.

**Comment by webvictim** [comment]
Similar to https://github.com/gravitational/teleport/issues/24962

**Comment by zmb3** [comment]
Tracking this in #30421 now
