### ISSUE TITLE
Unknown Event showing in Audit Log related to Device Authenticate after tsh login

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#25970]
Expected behavior:

Audit log events are defined.  

Current behavior:

After a `tsh login` seeing Unknown Event related to device authenticate.  This doesn't seem to matter if device trust is on, off or optional.  

![image](https://github.com/gravitational/teleport/assets/60704961/b5c47a25-3914-477c-b664-2077fa79ddb1)

Bug details:
- Teleport version: 13.0.0
- Recreation steps

Install a 13.0.0 cluster
Login with `tsh login`
Review audit log

**Comment by webvictim** [comment]
This is happening on 12.3.3 too.

**Comment by codingllama** [comment]
Landed backports for all applicable versions. Expect it to be fixed in the next release of each.
