### ISSUE TITLE
app access: cookie failures with Firefox 113's "total cookie protection"

### ISSUE THREAD

**Issue by jacobb84** [gravitational/teleport#26009]
Expected behavior:
Accessing an application via Safari or Firefox should prompt to login to teleport and then redirect to the application.

Current behavior:
Accessing an application via Safari or Firefox results in an infinite redirect between the proxy public url and the teleport url. The proxy url is on a different tld then the teleport url is in my case. 

Bug details:
- Teleport version: 11.3.10
- Debug logs

It's hard to tell the relevant logs, but one thing I have noticed is the logs fill up with session start log entries.
![image](https://github.com/gravitational/teleport/assets/6265054/6480310f-b8b4-41f8-8ad7-3942c9656a45)

I've also seen this error close before those session start entries.
![image](https://github.com/gravitational/teleport/assets/6265054/80173867-f399-4c8b-9727-703ce084dfc8)

**Comment by webvictim** [comment]
Does this same application work in another browser which isn't Safari?

Often in older versions of Teleport, infinite redirects are caused by an underlying error with the tunnel - just trying to isolate whether Safari is the real problem here.

**Comment by jacobb84** [comment]
Actually, I take it back. We've started getting reports of people having similar issues, but with different browser configurations. I have an app I'm looking at right now that loads in Chrome/Edge but not in Firefox.

**Comment by webvictim** [comment]
Thanks for the comprehensive report. I'll try to get someone to investigate this.

**Comment by jacobb84** [comment]
Thank you! Let me know if there's any other information you need.

**Comment by jacobb84** [comment]
Thank you for the work so far on this! Just curious, are you targeting a specific version release/milestone to merge this in? Just trying to figure out scheduling on our side so we can roll it out once it drops.
