### ISSUE TITLE
Docs: Review and consolidate AWS Role screenshots.

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/teleport#26022]
>Not a task for this PR, but at some point we should review all the separate screenshots we have for AWS role creation for various guides, and see which ones we can consolidate to reduce repo size.

_Originally posted by @alexfornuto in https://github.com/gravitational/teleport/pull/26008#discussion_r1190319885_
            

The idea here is to reduce our repo size by identifying duplicate screenshots of AWS role creation and standardizing them to use the same image where appropriate.

**Comment by ptgott** [comment]
I've reviewed all images with `role` in the filename. The only duplicates I've found are:

- `docs/img/database-access/guides/aws-opensearch/create-ec2-role.png` duplicates `dynamodb-create-ec2-role.png`
- `docs/img/database-access/guides/aws-opensearch/create-role-1.png` duplicates `dynamodb-create-role-1.png`

The time spent fixing these isn't worth the repo size loss, in my opinion. Closing this issue.
