### ISSUE TITLE
Terraform provider doesn't expose `cluster_maintenance_config`

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#26066]
**Expected behaviour**
The Terraform provider should support the configuration of all resource types that Teleport exposes natively via YAML files.

**Current behaviour**
 The Terraform provider does not allow the configuration or manipulation of the `cluster_maintenance_config` resource, which is required for automatic agent upgrades

Bug details:
- Teleport version: 13.0.0

See also #22261 for another missing resource.

**Comment by zmb3** [comment]
`network_restrictions` was already captured in #22261 so I updated this issue to only contain the `cluster_maintenance_config`.

**Comment by lxea** [comment]
Closed by https://github.com/gravitational/teleport-plugins/pull/886
