### ISSUE TITLE
Add Systemd instructions to the Application Access getting started guide

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#26138]
## Applies To
https://goteleport.com/docs/application-access/getting-started/

## Details
Cloud enterprise SaaS 12.3.3 UI no longer offers the wizard that generates a script to complete the application install. Now a user is directed to the link above in our docs. The nice thing about the script was the systemd configuration which added the teleport.service to the host and enabled it it start at boot. I think we should mention needing to do this as a last step in the doc. Might be understood already by most users so no need to go into huge details about. Recommendation would be "Add the teleport.service to systemd so will start automatically on restart"

**Comment by ptgott** [comment]
Closing since there are [now systemd instructions in this guide](https://github.com/gravitational/teleport/blob/a94a817373e102cc8c61746dd5fb7227dad5a525/docs/pages/application-access/getting-started.mdx#L126) (using the `start-teleport.mdx` partial).
