### ISSUE TITLE
Feature Request: `tsh login` should support `--bind` parameter

### ISSUE THREAD

**Issue by osterman** [gravitational/teleport#2620]
**What happened**:

Running `tsh login` inside of a [docker container](https://github.com/cloudposse/geodesic) on "Docker for Mac" opens a server on a **random** port that we cannot access. We [cannot use `--net=host` on "Docker for Mac"](https://github.com/docker/for-mac/issues/1031), so we need a way to explicitly port map a port to the container.

**What you expected to happen**:

We expected `tsh login` support an argument to specify an explicit port. 

For example, we use `kubectl proxy` inside of the same container. With `kubectl proxy`, we do the following:
```
kubectl proxy --port=12345 --address=0.0.0.0 --accept-hosts='.*'
```

With `tsh login`, we would expect to be able to do something similar:
```
tsh login --bind=0.0.0.0:12345
```
Which would permit us to do something like this when we start up our container:
```
docker run -it -p 12345:12345 ourcontainer sh
```

**Comment by kontsevoy** [comment]
Love it. One considerations:

* `--bin-addr` is more explicit and consistent with Teleport's flag naming.
* `--bind-addr` is obviously more convenient than separate `--bind-port` and `--bind-address` but it makes it a bit harder (but not impossible) to support IPv6, i.e.

```
$ tsh login --bind-addr=[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:12345
```

.. should work.

**Comment by osterman** [comment]
@kontsevoy thanks for your vote! Your considerations make sense to me.

**Comment by osterman** [comment]
One more feature request related to this: support `TSH_BIND_ADDR` environment variable so we can set this at the container level. 

e.g.
``` 
export TSH_BIND_ADDR="[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:12345"
```

**Comment by osterman** [comment]
@klizhentas any updates on this? We are blocked on this for one of our Teleport Enterprise customers and will soon have this with another Enterprise customer =)

**Comment by klizhentas** [comment]
@osterman understood. We will roll this for 3.2.x patch early next week.

**Comment by klizhentas** [comment]
working on this right now

**Comment by osterman** [comment]
Thanks for the update @klizhentas

**Comment by klizhentas** [comment]
Working versions:

```
# host:port
tsh login  --bind-addr=localhost:3333
# just port (all interfaces)
tsh login --bind-addr=:3333
# ipv6 format
tsh login --bind-addr=[::1]:3333
# pass through environment variable
TELEPORT_LOGIN_BIND_ADDR=localhost:7777 tsh login
```

**Comment by osterman** [comment]
Beautiful!! @nuru can you give this a go?

**Comment by Nuru** [comment]
No a complete solution, @osterman. See https://github.com/gravitational/teleport/pull/2646#issuecomment-482704679

**Comment by osterman** [comment]
@klizhentas we got everything working in [`geodesic`](https://github.com/cloudposse/geodesic). We can now `tsh login` inside our containers. Thanks so much for helping us get this working.
