### ISSUE TITLE
Would be great if we can define teleport roles in the teleport-cluster helm chart values file

### ISSUE THREAD

**Issue by yidongw** [gravitational/teleport#26223]
What would you like Teleport to do?
Define teleport roles in the teleport-cluster helm chart values file

What problem does this solve?
If we have that in place, we can avoid manually config the teleport roles after installing the teleport-cluster instance into the k8s.

It is more gitops friendly.

If a workaround exists, please include it.

**Comment by yidongw** [comment]
Thank you. This is very helpful

**Comment by webvictim** [comment]
While this technically does work, it'll only allow resources to be applied the first time the cluster starts. Re-running `bootstrap` after the cluster has been initialised does nothing, which is somewhat confusing.

The best way to actually work around this in Kubernetes is to apply resources with the Teleport Operator - unfortunately the operator doesn't support _all_ resource types that `--bootstrap` does which makes it awkward.

Another alternative is to use the Teleport Terraform provider to provision resources instead, but 1) getting this working in Kubernetes is more cumbersome than using the operator and 2) it _also_ doesn't support all resource types for some reason.

We really need better solutions for all of this.
