### ISSUE TITLE
`TestIntegrations/TwoClustersTunnel/node` flakiness

### ISSUE THREAD

**Issue by tobiaszheller** [gravitational/teleport#26225]
#### Link(s) to logs
- https://github.com/gravitational/teleport/actions/runs/4979689048/jobs/8911603076

#### Relevant snippet

I believe it's related to changes in https://github.com/gravitational/teleport/pull/25639 when I have introduce explicit closing of events and solved issue: https://github.com/gravitational/teleport/issues/15210

```
    integration_test.go:2355: 
                Error Trace:    /Users/tobiasz/go/src/github.com/gravitational/teleport/integration/integration_test.go:2355
                                                        /Users/tobiasz/go/src/github.com/gravitational/teleport/integration/integration_test.go:2179
                Error:          Condition never satisfied
                Test:           TestIntegrations/TwoClustersTunnel/node
                Messages:       Failed to find 3 events on helpers.Site A after 5s
```

**Comment by smallinsky** [comment]
Related: https://github.com/gravitational/teleport/issues/16530
