### ISSUE TITLE
[Feature] Make helm chart available without needing to download repository

### ISSUE THREAD

**Issue by aaronmell** [gravitational/teleport#2623]
There are several ways this can be accomplished.  The chart could be moved to the helm charts project https://github.com/helm/charts/tree/master/stable

The basic reason for this, is we want to be able to easily update the chart without hosting the chart source in our own repo.

**Comment by Nuru** [comment]
You can use CloudPosse's charts:
- [teleport-ent-auth](https://github.com/cloudposse/charts/tree/master/incubator/teleport-ent-auth) installs the auth service and supports enterprise feature like RBAC
- [teleport-ent-proxy](https://github.com/cloudposse/charts/tree/master/incubator/teleport-ent-proxy) installs the proxy service

Those charts are hosted at https://charts.cloudposse.com/incubator/

There are also corresponding [helmfile](https://github.com/roboll/helmfile) releases at https://github.com/cloudposse/helmfiles/blob/master/releases/teleport-ent-auth.yaml and https://github.com/cloudposse/helmfiles/blob/master/releases/teleport-ent-proxy.yaml
