### ISSUE TITLE
Test plan - v12.4 

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#26281]
### Core
 
- [ ] Login with MFA @jakule 
    - [x] Add an OTP, a WebAuthn and a Touch ID/Windows Hello device with `tsh mfa add`
    - [x] Login via OTP
    - [x] Login via WebAuthn
    - [ ] Login via platform authenticator
    - [x] Login via WebAuthn using an U2F device

- [x] Backends @jakule 
  - [x] Teleport runs with etcd
  - [x] Teleport runs with SQLite

- [x] Per-Session MFA (try webauthn on each of Chrome, Safari, and Firefox; u2f only works with Firefox) @jakule 
  - [x] Attempting to start a session no keys registered shows an error message
  - [x] Attempting to start a session with a webauthn registered pops up the "Verify Your Identity" dialog
    - [x] Hitting "Cancel" shows an error message
    - [x] Hitting "Verify" causes your browser to prompt you for MFA
    - [x] Cancelling that browser MFA prompt shows an error

- [x] Session Recording @xacrimon  
  - [x] Session recording can be disabled
  - [x] Sessions can be recorded at the node

- [x] Interact with a cluster using `tsh` @hugoShaka  

   These commands should ideally be tested for recording and non-recording modes as they are implemented in a different ways.

  - [x] tsh ssh \<regular-node\>
  - [x] tsh ssh \<node-remote-cluster\>
  - [x] tsh ssh -A \<regular-node\>
  - [x] tsh ssh -A \<node-remote-cluster\>
  - [x] tsh ssh \<regular-node\> ls
  - [x] tsh ssh \<node-remote-cluster\> ls
  - [x] tsh join \<regular-node\>
  - [x] tsh join \<node-remote-cluster\>
  - [x] tsh play \<regular-node\>
  - [x] tsh play \<node-remote-cluster\>
  - [x] tsh scp \<regular-node\>
  - [x] tsh scp \<node-remote-cluster\>
  - [x] tsh ssh -L \<regular-node\>
  - [x] tsh ssh -L \<node-remote-cluster\>
  - [x] tsh ls
  - [x] tsh clusters

Moderated session: @xacrimon 
 - [x] User can create a moderated session
 - [x] User can join a moderated session
 - [x] The session is paused/destroyed on moderator disconnect

### WebUI

- [x] Interact with a cluster using the Web UI @ryanclark 
  - [x] Connect to a Teleport node
  - [x] Connect to a OpenSSH node
  - [x] Check agent forwarding is correct based on role and proxy mode.
 
- Assist @ryanclark 
  - [x] A new conversation can be created
  - [x] User can ask questions and see assistant responses
  - [x] WebUI elements are not shown to a user when the API key is not provided
  - [x] WebUI elements are shown to a user when the API key is provided
  - [x] Command can be executed from the Assist conversation

### Cloud @justinas 

- [x] Assist rate limiting works
- [x] Assistant is available on the Team plan
- [x] Assistant is not available on the Enterprise Cloud plan

**Comment by xacrimon** [comment]
bug: https://github.com/gravitational/teleport/issues/26321

**Comment by jakule** [comment]
> bug: #26321

This is a duplicate of a bug that already exists in v12 https://github.com/gravitational/teleport/issues/25115
