### ISSUE TITLE
GitHub Actions fetch of Teleport binaries is slow

### ISSUE THREAD

**Issue by mnaser** [gravitational/teleport#26388]
Expected behavior:
GitHub action to download toolkit from cdn.teleport.dev

Current behavior:
It uses get.gravitational.com which is _super_ slow.

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by strideynet** [comment]
How slow are you seeing ? Are you using GitHub's runners or your own runners ?

**Comment by mnaser** [comment]
I've got a customer runner that's based out of Pakistan which seems to be downloading the artifacts very slowly (vs the CDN address).

Having said that, the official artifacts on the Teleport website seem to come from the CDN so I'm thinking it might be better to go towards there instead.

**Comment by strideynet** [comment]
Thanks for clarifying - I'll take a look at some speed comparisons in different locations and make a decision. We might also be able to leverage better caching.

**Comment by stevenGravy** [comment]
Yes the CDN is specifically designed to be faster.

**Comment by strideynet** [comment]
Version 1.0.3 of @teleport-actions/setup should now use the CDN @mnaser - thanks for raising this issue with us.
