### ISSUE TITLE
[operator] Allow use of secrets in TeleportGithubConnector

### ISSUE THREAD

**Issue by kenske** [gravitational/teleport#26402]
What would you like Teleport to do?
The `TeleportGithubConnector` currently requires a `client_id` and `client_secret` to be specified in plaintext. It would be nice to be able to have the operator fetch those values from a k8s `secret` or a mounted volume.

What problem does this solve?
Storing secrets in plaintext

If a workaround exists, please include it.
Not using the `TeleportGithubConnector`, instead adding it manually

**Comment by zmb3** [comment]
I've merged this into #6815
