### ISSUE TITLE
Investigate reduced cryptographic performance when establishing connections on `arm64` and/or with Go 1.20

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#26412]
During a customer incident today it appeared that a thundering herds ability to bring down a customer's auth/proxy was exacerbated by a less performant crypto implementation being used on the `arm64` platform as well as potential performance regressions in Go 1.20.

CPU profiles indicated that 24 out of 30 seconds were being spent in https://go.dev/src/crypto/internal/bigmod/nat_noasm.go . This implementation is a pure-go implementation that is used on platforms where a more optimised asm implementation is not available. There are some other related notes on reduced `arm64` performance on https://github.com/golang/go/issues/22807.

It would also appear that Go 1.20 included performance regressions to crypto performance: https://github.com/golang/go/issues/59442 - this could be a further exacerbating factor.

We should determine what the performance difference is here with `arm64` and if we are affected by the performance regressions in Go 1.20 - and what recommendations we should make based on this.

**Comment by codingllama** [comment]
https://tip.golang.org/doc/go1.21#crypto/rsa

**Comment by zmb3** [comment]
This is going to be solved with the Go 1.21 upgrade, so I'm closing this out as there's no additional action necessary.
