### ISSUE TITLE
fix confusing error around Enterprise-only features (`creating resources of type "saml" is not supported`)

### ISSUE THREAD

**Issue by aberoham** [gravitational/teleport#2641]
The tctl error message `User Message: creating resources of type "saml" is not supported` needs to be improved. Many commercial evaluations trip up over trying to use Enterprise features within OSS and that is the only hint they receive. 

_Originally posted by @aberoham in https://github.com/gravitational/teleport/issues/2246#issuecomment-433939757_

**Comment by fspmarshall** [comment]
Looks like this was fixed in #2724.  @webvictim, can you confirm?

**Comment by webvictim** [comment]
Yes, that's correct. Trying to add a SAML connector to an OSS Teleport server should now generate a more logical error.
