### ISSUE TITLE
SIGSEGV when running tsh logout with no logins stored

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#2644]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**: Running `tsh logout` when Teleport has no logins stored seems to cause a segmentation fault.

```
~ » tsh --debug logout
INFO [CLIENT]    No teleport login given. defaulting to gus client/api.go:690
INFO [CLIENT]    no host login given. defaulting to gus client/api.go:700
INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/tmp/ssh-AGcdNzWcwff6/agent.3150" client/api.go:1928
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10d43a6]

goroutine 1 [running]:
main.onLogout(0xc00026e400)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:550 +0x196
main.Run(0xc0000c4070, 0x2, 0x2, 0x0)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:330 +0x4b83
main.main()
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:163 +0x11c

```

**What you expected to happen**: Either nothing, or a message saying that there are no users to log out.

**How to reproduce it (as minimally and precisely as possible)**: Run `tsh logout` on a fresh Teleport installation (with an ssh-agent running)

**Environment**:
- Teleport version (use `teleport version`): `Teleport v3.2.0 git:v3.2.0-0-gd0abdeac go1.11.5`
- Tsh version (use `tsh version`): `Teleport v3.2.0 git:v3.2.0-0-gd0abdeac go1.11.5`
- OS (e.g. from /etc/os-release): Fedora 29

**Comment by klizhentas** [comment]
I think I've fixed this problem in master.
