### ISSUE TITLE
Add OpsGenie integration web UI page

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#26485]
Related to: https://github.com/gravitational/teleport-plugins/issues/437.

As a part of hosted OpsGenie plugin implementation, we need to add a tile to our Integrations page to allow users to add an OpsGenie plugin, similar to hosted Slack plugin.

The difference with Slack is that OpsGenie doesn't support OAuth2 API authentication and uses API tokens instead. So the "Add OpsGenie integration" page needs to ask the user to enter the following details:

- API endpoint. It can be either `https://api.opsgenie.com` or `https://api.eu.opsgenie.com` so we can just give users a choice instead of asking them to type it in.
- API token.
- Optional default schedule name which will receive alerts. Later we can look into populating this automatically by calling OpsGenie API using the auth token.

After collecting these parameters, create the OpsGenie Plugin resource on the backend. @EdwardDowling Can you provide details on how would frontend create it? API endpoint and parameters.

**Comment by mdwn** [comment]
We'll need this for the Okta plugin as well.
