### ISSUE TITLE
Clarify the `host` flag of `tctl auth sign` in the self-hosted MySQL guide

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#26517]
## Applies To
https://goteleport.com/docs/database-access/guides/mysql-self-hosted/#step-24-create-a-certificatekey-pair

## Details
Step 2/4 states to run command **tctl auth sign --format=db --host=db.example.com --out=server --ttl=2190h**

It is not clear what to input for the --host= field. In my setup using a docker-compose declaring a mysql service, it should have be fqdn of the docker instance. I needed to specify the name given to my container which was simply "mysql" as defined in my docker-compose.yaml file.  Researching the tctl auth sign command in command reference [document](https://goteleport.com/docs/reference/cli/#tctl-auth-sign), you are guided to use the Teleport host name which added to my confusion. 

version: '3'
services:
  mysql:
    image: mysql:latest

**Comment by ptgott** [comment]
Closing as fixed in 2cf7284404c9fd4b57e4bfffe30ebc5dd63a707f
