### ISSUE TITLE
sudo tctl create -f admin-role.yml error msg 

### ISSUE THREAD

**Issue by luupux** [gravitational/teleport#2652]
Hi,
first of all tnks for your work, so now I have an little issue but I don't think it's related to 
my setup.
I followed this page 
https://gravitational.com/teleport/docs/quickstart-enterprise/

and I execute  "sudo tctl create -f admin-role.yml"
I update the file as you can see below

kind: roles
metadata:
  name: admin
spec:
  allow:
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    logins:
    - adminusr
    node_labels:
      '*': '*'
    rules:
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - auth_connector
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - session
      verbs:
      - list
      - read
    - resources:
      - trusted_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - event
      verbs:
      - list
      - read
  deny: {}
  options:
    cert_format: standard
    client_idle_timeout: 0s
    disconnect_expired_cert: false
    forward_agent: true
    max_session_ttl: 30h0m0s

and  executed "sudo tctl create -f admin-role.yml" but I received  an error like that
error: creating resources of type "roles" is not supported
I only followed the doc, after I checked in the site and on internet but I didn't found any good
reason for this message.

**Comment by webvictim** [comment]
@luupux The use of RBAC/roles is only supported in Teleport Enterprise. Check what version you’re using with `tctl version`

**Comment by webvictim** [comment]
Resolving this for now.
