### ISSUE TITLE
`teleport-kube-agent` chart default security context breaks hooks

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#26570]
Expected behavior:

I apply the chart and it works

Current behavior:

The chart upgrade gets stuck on a non-schedulable hook caused by mismatched spec/securityContext

Bug details:

[Reported on the community Slack.](https://goteleport.slack.com/archives/CEZH6UL64/p1684419233350679)

```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  4m42s                   default-scheduler  Successfully assigned system/teleport-kube-agent-hook-mmgxm to XXXXX
  Normal   Pulling    4m36s                   kubelet            Pulling image "alpine/k8s:1.26.0"
  Normal   Pulled     4m24s                   kubelet            Successfully pulled image "alpine/k8s:1.26.0" in 11.819847397s
  Warning  Failed     2m13s (x12 over 4m24s)  kubelet            Error: container has runAsNonRoot and image will run as root (pod: "teleport-kube-agent-hook-mmgxm_system(568cc41d-b654-4703-8299-bf02cf97df4c)", container: post-install-job)
  Normal   Pulled     2m13s (x11 over 4m24s)  kubelet            Container image "alpine/k8s:1.26.0" already present on machine
```

**Comment by tigrato** [comment]
@hugoShaka it's safe to remove the hook. 
It was meant to convert v10-->v11 but we are already on Teleport 13 so we can safely remove it

**Comment by hugoShaka** [comment]
I suspect some people are still using the latest chart with v11 Teleport so I suggest we keep at least until v14 the hook.

After troubleshooting with the user, it ended up being a v11 limitation (no security context on hooks) combined with a kyverno policy blocking root execution. I'll close the issue.
