### ISSUE TITLE
Docs need updating for 3.2.0

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#2658]
**What happened**: Docs weren't updated for 3.2.0

**What you expected to happen**: Docs to be updated for 3.2.0

- k8s impersonation API changes and required ServiceAccount permissions
- moving of kubeconfig file parameter from auth to proxy

**Comment by webvictim** [comment]
Assigning to @kontsevoy as requested by @klizhentas

**Comment by webvictim** [comment]
How do we regenerate the published docs on the website? https://gravitational.com/teleport/docs/ver/3.2/intro still doesn't exist

**Comment by klizhentas** [comment]
you have to deploy them in jenkins
