### ISSUE TITLE
Provide data schema

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#26589]
## Applies To
https://goteleport.com/docs/reference

## Details
Provide a document of the data schema used in Teleport. There is not a comprehensive reference of all the configurations and state of the system.  This makes it difficult to retrieve values like nodes, auth connectors and confirm the settings.

**Comment by stevenGravy** [comment]
We can narrow it but like we don't have the `cert_authority` listed, `users`,... Seems like there should be way of collection all the `kind` types and keeping them up to date.

**Comment by ptgott** [comment]
Are you talking about dynamic configuration resources? If so, we have a few issues opened already to have a comprehensive reference, and plans to move forward with this.

**Comment by stevenGravy** [comment]
No, these are the other configurations in the system.  LIke `cert_authority`, `lock`, ...
