### ISSUE TITLE
Teleport Connect 13.0.2 does not support OpenSearch database connection.

### ISSUE THREAD

**Issue by kaan-carbon** [gravitational/teleport#26588]
While working on OpenSearch integration, I faced this issue in Teleport Connect.

Expected behavior:
Expected to connect OpenSearch cluster over Teleport Connect.

Current behavior:
Teleport Connect 13.0.2 does not support OpenSearch database connection. 
Getting this error: `12 UNIMPLEMENTED: "opensearch" protocol is not supported`

<img width="1420" alt="Screenshot 2023-05-19 at 14 30 11" src="https://github.com/gravitational/teleport/assets/102513863/23d83b3e-0ac4-4c6f-a343-78eff73bc545">

<img width="1427" alt="Screenshot 2023-05-19 at 14 34 32" src="https://github.com/gravitational/teleport/assets/102513863/f38973a1-c2b5-4306-a56e-99007005c833">

Bug details:
- Teleport Connect version: 13.0.2 (Community Edition)
- OS: MacOS
- Recreation steps: Defined above.
- Debug logs: The screenshots are shared.

**Comment by Tener** [comment]
I cannot replicate the issue. Can you make sure all components are at least v13?

**Comment by kaan-carbon** [comment]
I've reinstalled Teleport Conenct, and the issue is solved. Thanks.

Versions:
Proxy+Auth Service: `public.ecr.aws/gravitational/teleport:13`
Database Services: `public.ecr.aws/gravitational/teleport:13`
Teleport Connect: MacOS 13.0.2
