### ISSUE TITLE
SFTP audit log events do not identify as Upload or Download

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#26603]
Expected behavior:

As SFTP replaced SCP we would expect a easy way to identify if a upload or download is happening.  The previous SCP behavior looked like this

<img width="1704" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/76d3c77b-ea55-4324-85d6-478966ddaf72">

Current behavior:

A download looks like this
<img width="1345" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/2b6a18ff-b80c-4a24-a8e5-954f9cd8aa0e">

And a upload looks like this

<img width="1354" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/462c2c8a-2cc5-456c-953e-caadf70bb855">

A user would have to know what a Setstat is doing that this is related to a upload. 

There is also a empty audit log record for the session.

<img width="1359" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/f3fc3feb-fbc9-4bcc-8cbf-2d3856737f78">

Bug details:
- Teleport version: 13.0.2
- Recreation steps

Perform upload and downloads in Web UI and `tsh`
Review audit log

**Comment by zmb3** [comment]
I'm not sure this is a bug so much as a protocol difference between SFTP and SCP.
