### ISSUE TITLE
Add performance metrics for DB Proxy/DB Agent/DB Instance flow

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#26667]
## What:

Add prometheus metrics in DB Access flow: 

#### DB Agent:
- [x] number of client connections [grouping per db agent, per database, ...?] 
- [x] db connection time from db agent side
- [x] auth token/issue db cert time. 
- [ ] Bonus: Add metrics for external API calls
#### Teleport Proxy: 
- [x] DB agent connection time.

**Comment by Tener** [comment]
> @Tener @smallinsky Once this is implemented, can you guys please work with our Cloud SRE team and set up Grafana dashboards tracking database access performance metrics?

Done (a while ago): https://github.com/gravitational/cloud/pull/5789
