### ISSUE TITLE
[v.13.x] "CA Pinning" link in ca-rotation.mdx leads to nonexistent heading

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#26666]
## Applies To

* https://goteleport.com/docs/management/operations/ca-rotation/

## Details

Just what the title says.

BTW, didn't we have a linter in place which prevented this from happening?

**Comment by ptgott** [comment]
The linter is working correctly here, but the heading is invisible by default because it is part of a `Details` box. I'll change this to link to the `Details` box instead.

**Comment by ptgott** [comment]
You're probably not the only one 😬
