### ISSUE TITLE
obvious way to do K8s-only access, without ssh (without allowed logins)

### ISSUE THREAD

**Issue by aberoham** [gravitational/teleport#2670]
**What happened**: A commercial end-user tried to configure Kubernetes-only access. When a role was configured to not set any allowed logins values, users assigned to this role would encounter an esoteric OIDC error: "[OIDC] Error while processing callback: this user cannot create SSH sessions, has no allowed logins web/apiserver.go:822"

**What you expected to happen**: There'd be an obvious and documented way to disable SSH completely while still allowing kubectl.

**Environment**: - Teleport version (use `teleport version`): <= v3.2.x

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190134506177097/1190154500255591) by [Unito](https://www.unito.io/learn-more)

**Comment by aberoham** [comment]
Feedback from end-user: "If I specify a node label that doesn’t exist, and use an invalid login I can get in, and I get an empty list of nodes, which is what I want"

**Comment by awly** [comment]
Someone needs to verify that a user with empty `logins` can use k8s.
It _should_ work these days.

**Comment by stevenGravy** [comment]
This is fixed now with the empty login set by default.
