### ISSUE TITLE
tsh status does not show correct cluster name

### ISSUE THREAD

**Issue by Nuru** [gravitational/teleport#2671]
**What happened**:
`tsh status` lists the master cluster rather than the specific cluster I am logged into.

**What you expected to happen**:
`tsh status` shows the cluster I am logged into and that is the context for things like `tsh ls` and `tsh ssh`.

**How to reproduce it (as minimally and precisely as possible)**:
In a trusted cluster configuration (here `corp` is the master cluster and `tele.cpco.io` is the public proxy name):
```
$ tsh login
  Profile URL:  https://tele.cpco.io:3080
  Logged in as: nuru@cpco.io
  Cluster:      tele.cpco.io
  Roles:        root*
  Logins:       admin
  Valid until:  2019-04-23 23:14:22 +0000 UTC [valid for 2h19m0s]
  Extensions:   permit-port-forwarding, permit-pty

$ tsh clusters
Cluster Name Status 
------------ ------ 
corp         online 
staging      online 
data         online 
prod         online 

$ tsh login data
  Profile URL:  https://tele.cpco.io:3080
  Logged in as: nuru@cpco.io
  Cluster:      tele.cpco.io
  Roles:        root*
  Logins:       admin
  Valid until:  2019-04-23 23:14:22 +0000 UTC [valid for 2h19m0s]
  Extensions:   permit-port-forwarding, permit-pty
```
I expected to see `Cluster: data` not `Cluster: tele.cpco.io`. 

**Environment**:
- Teleport version (use `teleport version`): Teleport Enterprise v3.2.2git:v3.2.2-0-gfbd6b388 go1.11.5
- Tsh version (use `tsh version`): Teleport v3.2.2 git:v3.2.2-0-gfbd6b388 go1.11.5
- OS (e.g. from /etc/os-release): alpine 3.9.2

**Comment by kontsevoy** [comment]
## More information

Just got here to report the same issue. But found another:

```
$ tsh clusters
Cluster Name Status 
------------ ------ 
org-1        online 
org-2        online 
```

Now I try non-existent cluster name:

```
$ tsh login org-3
```

... and it prints me my status instead of saying "cluster 'org-3' is not found"

**Comment by webvictim** [comment]
Think #2842 may also be covered by this (Bug 2)
