### ISSUE TITLE
Add deltarpm instructions to the "Upgrading the Teleport Binary" guide

### ISSUE THREAD

**Issue by hdcAWSproduction** [gravitational/teleport#26829]
## Applies To

https://goteleport.com/docs/management/admin/upgrading-the-teleport-binary/
## Details

I had an error when trying to upgrade to 13, thought that maybe you could add a bit to help people who are not familiar with yum, fix it.

Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
teleport-12.4.3-1.x86_64.rpm   FAILED                                          
https://yum.releases.teleport.dev/amzn/2/Teleport/x86_64/stable/v13/repo_rpms/teleport-12.4.3-1.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found                                                                                           ]  0.0 B/s |    0 B  --:--:-- ETA 
Trying other mirror.
Error downloading packages:
  teleport-12.4.3-1.x86_64: [Errno 256] No more mirrors to try.

I resolved it by doing the following:

$ sudo yum install deltarpm
# not really required, but it does make the error "... /usr/bin/applydeltarpm not installed" go away
$ sudo yum clean all
$ sudo yum update
$ sudo yum upgrade teleport

## How will we know this is resolved?

I guess teleport binary is upgraded correctly

**Comment by ptgott** [comment]
Thanks for your interest in improving the Teleport docs. This particular issue doesn't seem common enough among Teleport users to warrant inclusion in the docs. The solution is also readily available from a Google search. While I'm closing this issue for now, I'm also working on adding more context about our package repositories to the [Installation](http://localhost:3000/docs/installation) page so users can determine how best to configure their systems to install Teleport.
