### ISSUE TITLE
TLS Routing behind ALB: Teleport Connect Kube Proxy Support

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#26836]
### What 

Add support in Teleport Connect for `kube proxy` flow that allows to Teleport Kube Access  when Teleport Proxy is behind L7 Load balancer.

**Comment by nmlc** [comment]
I wonder how this would work together with `tsh request create`. Currently, when requesting additional roles, you need to restart `tsh kube proxy`.
