### ISSUE TITLE
Move teleport builds off ubuntu 18.04 

### ISSUE THREAD

**Issue by wadells** [gravitational/teleport#26856]
Ubuntu 18:04 is reaching the end of its life in ~1 week on 2023-05-31:

https://ubuntu.com/blog/18-04-end-of-standard-support

We currently use 18.04 in the following buildboxes:

https://github.com/gravitational/teleport/blob/v13.0.2/build.assets/Dockerfile#L99

https://github.com/gravitational/teleport/blob/v13.0.2/build.assets/Dockerfile-fips#L73

These workflows will need to be moved to a supported distro.

**Comment by wadells** [comment]
We moved most workflows to centos:7 in https://github.com/gravitational/teleport/issues/13913.  However, this wasn't possible with Teleport Connect, as it depends on a node version which doesn't support centos:7. Per https://github.com/gravitational/teleport/issues/21724

> Our builders currently use Node v16 which EOL is [September 11th, 2023](https://nodejs.org/ar/blog/announcements/nodejs16-eol/).  
> The main problem with the upgrade is that we use CentOS 7 image for Linux pipelines, which Node v18 [does not support](https://nodejs.org/de/blog/announcements/v18-release-announce/#toolchain-and-compiler-upgrades).

Further discussion in a slack thread here: https://gravitational.slack.com/archives/C08HF8E9F/p1683130098612679

**Comment by wadells** [comment]
I believe `Dockerfile-fips` is no longer needed after https://github.com/gravitational/teleport/pull/14062

**Comment by zmb3** [comment]
> However, this wasn't possible with Teleport Connect, as it depends on a node version which doesn't support centos:7

My understanding is that the _new_ node version that we're trying to upgrade to doesn't support centos:7, but the version we are on today does.

**Comment by wadells** [comment]
This was largely addressed by https://github.com/gravitational/teleport/pull/27497
