### ISSUE TITLE
Show Auth or Proxy versions in Web UI.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2698]
Print the Auth or Proxy versions in Web UI to allow for easy conformation of updates.

**Comment by benarent** [comment]
@russjones we do currently print this out in the console. 
![image](https://user-images.githubusercontent.com/559288/62162554-64299f80-b2cd-11e9-9a85-be02a7fa3300.png)

This might be something we want to add into 4.2, unless @alexwolfe has a suggestion for where we could implement it in the current UI.

**Comment by klizhentas** [comment]
moved to 4.2

**Comment by alex-kovoy** [comment]
done

**Comment by alex-kovoy** [comment]
This was done during initial work on Teleport 5.0. Since we made several UI changes, I am reactivating it to make sure that we do not miss it.

**Comment by alex-kovoy** [comment]
closed by https://github.com/gravitational/teleport/pull/3515
