### ISSUE TITLE
Improve Web UI Node Search

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2699]
At the moment, in the Web UI, the Teleport "Search ..." box filters based off labels, address, and hostname. More complex patterns (regex) or conditions (AND, OR) are not supported.

Customers that have multiple labels per node have asked for a more sophisticated filter box to allow matching on a more granular level. 

![image](https://user-images.githubusercontent.com/5017502/57253849-985e2e80-7004-11e9-9b20-5695842a0237.png)

**Comment by webvictim** [comment]
Request from another customer: this functionality should also be extended to the cluster dropdown - we should allow a typeahead-type search for cluster names which will help when there are many clusters to choose from.

It would also be good to allow the possibility to 'tag' clusters and then enable searching clusters by tag.

**Comment by benarent** [comment]
@alex-kovoy With the new UI foundations do we have anything at our disposal that'll start to make fronted search better without investing in backend search engines.

**Comment by alex-kovoy** [comment]
related #5021 #3860

**Comment by zmb3** [comment]
This is complete with the introduction of advanced search + pagination in Teleport 9.
