### ISSUE TITLE
Add multiple AWS profiles and connect to aws services

### ISSUE THREAD

**Issue by teenwolf99** [gravitational/teleport#26996]
I have to added multiple aws secret key and access keys in the same linux server not in AWS(another cloud) by using AWS_SHARED_CREDENTIALS_FILE=~/.aws/credentials. What I'm trying to achive is access various aws consoles by using the assume role. I have added two different aws  consoles in the teleport configuration and added the aws keys in the .aws directory. 

### teleport.yaml
app_service:
  enabled: "yes"
  apps:
  - name: aws-1
    uri: https://console.aws.amazon.com/ec2/v2/home
    labels:
      aws_account_id: 123456789
      access: ec2
  - name: aws-2
    uri: https://console.aws.amazon.com/ec2/v2/home
    labels:
      aws_account_id: 987654321
      access: ec2

### .aws/credentials
[aws-1]
AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXX
[aws-2]
AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXX

I can able to access only the second profile, the first profile is getting Access Denied by the second profile.

### WARN [APP:SERVI] "Failed to serve request: AccessDenied: User: arn:aws:iam::987654321:user/teleport is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789:role/teleport\n\tstatus code: 403.

But while accessing the second profile no issues, it is working as expected. How to setup multiple aws account in teleport to get connected with aws console.

I also tried this with the EnvironmentFile=-/etc/default/teleport and Environment="AWS_SHARED_CREDENTIALS_FILE=/home/ubuntu/.aws/credentials.

**Comment by stevenGravy** [comment]
See https://goteleport.com/docs/application-access/cloud-apis/aws-console/#step-29-update-iam-role-trust-relationships for being able to assume roles in other accounts.

**Comment by teenwolf99** [comment]
For security reasons, isn't there any other possible way in teleport to use individual AWS profiles without allow permissions to another account. Please let me know it would be much appreciated.

**Comment by stevenGravy** [comment]
> For security reasons, isn't there any other possible way in teleport to use individual AWS profiles from /home/ubuntu/.aws/credentials without allow permissions to another account. Please let me know it would be much appreciated.

No, this allows you in each account to define what other accounts to connect.  This is considered secure in that you don't have to store all the credentials for all the AWS accounts in one place.  That account is then also able to disable access if needed.

**Comment by teenwolf99** [comment]
> > For security reasons, isn't there any other possible way in teleport to use individual AWS profiles from /home/ubuntu/.aws/credentials without allow permissions to another account. Please let me know it would be much appreciated.
> 
> No, this allows you in each account to define what other accounts to connect. This is considered secure in that you don't have to store all the credentials for all the AWS accounts in one place. That account is then also able to disable access if needed.


Ok, This process requires a primary AWS account which will have assume access to all the AWS accounts(two or more). Can you please tell me one thing what if the primary account is breached and that account has assume privileges to 10 accounts. I can even assume roles out of teleport, correct me if I'm wrong.

**Comment by stevenGravy** [comment]
You have the option to have one agent install that can connect to multiple accounts or individual agents for each account. If you would prefer to use credentials to each account you can run more then one Teleport instance on a single machine. They just need to have separate configs, systemd and data dirs. As mentioned having Iam configs allows more control from those accounts to what account can connect vs static credentials.

**Comment by stevenGravy** [comment]
Please join the slack channel for further questions https://goteleport.com/community-slack/ or use the GitHub discussions
