### ISSUE TITLE
replace polling with event streams

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#270]
Currently there's lots of polling going on in sshserver, reverstunnel and other components. This does not scale very well. We have to replace it with event watch mechanisms. 

Luckily, Etcd provides a great way to detect changes and we should take benefit of that.
On the API side - HTTP API will use websockets mechanism for streaming data.

**Comment by russjones** [comment]
@alex-kovoy Are we still polling on the Web UI or has that been removed in 4.3?

**Comment by alex-kovoy** [comment]
@russjones  Yes, we stopped polling events on the client side for _now_ but we _may_ need to start polling it again to handle "request access" events from Web UI.

**Comment by russjones** [comment]
Alright let's close this ticket as resolved then.
