### ISSUE TITLE
Teleport Discover "Nonpositive parameter limit"

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#27081]
Expected behavior:
I went through the onboarding on our cloud 12.4.3 and have running AWS integration on. When trying to fetch databases, I get "nonpositive parameter limit", see below

Current behavior:
<img width="905" alt="Screenshot 2023-05-29 at 11 57 52 AM" src="https://github.com/gravitational/teleport/assets/13717/7bededa1-f11e-4a7c-b437-786902c07bcf">

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by klizhentas** [comment]
The issue is intermittent, and after a couple of tries, it works, but this error gives an impression something crashed.

**Comment by marcoandredinis** [comment]
The error is returned from backend when GETing a page of resources
However, the only call I was expecting here is the one hitting the integration, and it doesn't use the generic list resources endpoint 🤔 

So, we are probably doing an extra call here.
@kimlisa can probably help us here 🙏
