### ISSUE TITLE
SCP failing with error code 126

### ISSUE THREAD

**Issue by bharadwajrembar** [gravitational/teleport#2712]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
`tsh scp` isnt working when trying to copy a file from an upstream server.

**What you expected to happen**:
`tsh scp ubuntu@server:~/file.txt .`
Must copy a file name `file.txt` to my local machine

**How to reproduce it (as minimally and precisely as possible)**:
`tsh scp ubuntu@server:~/file.txt .`

**Environment**:
- Teleport version (use `teleport version`): 3.1.1
- Tsh version (use `tsh version`): 3.1.1
- OS (e.g. from /etc/os-release): Ubuntu 16.04

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**
```
ERROR REPORT:
Original Error: *ssh.ExitError Process exited with status 126
Stack Trace:
	/tmp/20181218T163658/src/github.com/gravitational/teleport/lib/client/client.go:581 github.com/gravitational/teleport/lib/client.(*NodeClient).ExecuteSCP
	/tmp/20181218T163658/src/github.com/gravitational/teleport/lib/client/api.go:1227 github.com/gravitational/teleport/lib/client.(*TeleportClient).SCP
	/tmp/20181218T163658/src/github.com/gravitational/teleport/tool/tsh/tsh.go:747 main.onSCP
	/tmp/20181218T163658/src/github.com/gravitational/teleport/tool/tsh/tsh.go:309 main.Run
	/tmp/20181218T163658/src/github.com/gravitational/teleport/tool/tsh/tsh.go:164 main.main
	/usr/local/go/src/runtime/proc.go:210 runtime.main
	/usr/local/go/src/runtime/asm_amd64.s:1334 runtime.goexit
User Message:
```

- tsh --debug
- teleport --debug

**Comment by webvictim** [comment]
Resolved on the forum - this was a unmask issue.

https://community.gravitational.com/t/scp-failing-with-error-code-126/191
