### ISSUE TITLE
Cannot connect to node either in web or tsh

### ISSUE THREAD

**Issue by toby1991** [gravitational/teleport#2723]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
Cannot connect to node either in web or tsh
**What you expected to happen**:
Connected
**How to reproduce it (as minimally and precisely as possible)**:
follow the official instruction

**Environment**:
- Teleport version (use `teleport version`): `3.2.4`
- Tsh version (use `tsh version`): `3.2.4`
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools: docker
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

`ERRO [NODE]      no such user fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:xxxxxxx local:127.0.0.1:3022 remote:172.19.0.7:47768 user:xxxx srv/authhandlers.go:194`

**Comment by klizhentas** [comment]
and do you have a target linux user on the host?

**Comment by toby1991** [comment]
> do you have a tar

Thank you for replying, I used both already existed user and `tctl users add xxx`'s xxx, cannot be processed login operation.

When I use existed user, which the user hasn't been added by `tctl`, there's not debug message at all.
when I use the non-existed user on the machine, which has been added by `tctl`, it says `ERRO [NODE] no such user fingerprint:xxxxxx`

**Comment by toby1991** [comment]
problem solved.

for example,
I've a node `AAA`, and has a user named `aaa`

then I `tctl add users bbb`
I login the WEB using `bbb`, and `bbb` cannot connect to `AAA`, it will caused the problem described by this issue.

then I `tctl add users aaa`
I login the WEB using `aaa`, and `aaa` could connect to `AAA` successfully.

Hope this could help others.

I'm closing the issue.

**Comment by klizhentas** [comment]
what about OS linux user, does it actually exist?

**Comment by klizhentas** [comment]
sounds, good thanks!
