### ISSUE TITLE
Terraform example brings up proxies with incorrect permissions

### ISSUE THREAD

**Issue by Obsecurus** [gravitational/teleport#2729]
**What happened**:
Teleport proxies would not start with examples/terraform 

**Environment**:
- Teleport version: gravitational-teleport-ami-oss-3.2.4

**Fix** (On Proxy nodes)
- SSH from the bastion to the proxies by adding your AWS private key as id_rsa into the bastion
```
sudo chown teleport:adm /etc/teleport.yaml
sudo chmod 664 /etc/teleport.yaml
sudo chown teleport:adm /var/lib/teleport/proc
```

**Comment by Obsecurus** [comment]
guessing there is a bug in a script somewhere. I noticed the user for /var/lib/teleport/proc was 664:adm

**Comment by Obsecurus** [comment]
Also the bastion node is not joining the cluster. I assume this is an error as well?

**Comment by klizhentas** [comment]
@webvictim can you please investigate?

**Comment by webvictim** [comment]
@Obsecurus The bastion node isn't intended to join the cluster - it's just for use as a bastion server (for example with an SSH `ProxyCommand`) so that public IPs aren't needed for all services.

I'll investigate the other issue.
