### ISSUE TITLE
Update configuration for Kubernetes

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2731]
## Description

Our kubernetes guide is out of date.

https://gravitational.com/teleport/docs/kubernetes_ssh/#teleport-auth-service <- `auth_service` does no longer have `kubernetes_path` section, it has been moved to proxy.

Also I wrote several related articles the could be added to the guide:

https://community.gravitational.com/t/how-to-share-kubernetes-groups-between-trusted-clusters/54

https://community.gravitational.com/t/what-is-the-difference-between-internal-and-external-variables-in-teleport-templates/159/2

**Comment by webvictim** [comment]
FYI I think the `kubeconfig_file` thing has been fixed now with the release of Teleport 3.2 docs.

**Comment by benarent** [comment]
I'm just reviewing this ticket, it seems we've updated the info about the Auth server,  or would "How to share kubernetes groups between trusted clusters".. might be a useful extra section?

**Comment by benarent** [comment]
Reviewing this ticket and I can confirm that it's fixed. https://gravitational.com/teleport/docs/kubernetes_ssh/
