### ISSUE TITLE
Okta assignments should be reflected in Teleport during initial import

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#27319]
When an IT administrator turns on Okta integration, we import apps and groups. Internally we create group assignments in Teleport based on group assignments in Okta as a part of import.

Success criteria:
-  After configuring Okta integration, users automatically get access to all existing Okta assignments within Teleport without extra configuration.

**Comment by mdwn** [comment]
This looks to be complete with the Okta access list sync work, so I'm closing this.
