### ISSUE TITLE
Requesting access to Okta app should allow user to pick group

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#27320]
Teleport should associate groups with apps based on the Okta model internally and allow users to select a group when requesting access to an application.

Success criteria:

- Teleport access requests UI allows users to pick a group when requesting access to an application.
- Users do not have to request access to groups/apps separately in order to receive access and see app in Teleport.

**Comment by mdwn** [comment]
This is in flight. The backend work is largely complete save for anything needed for the frontend, so now this needs some front end work.
