### ISSUE TITLE
Teleport scalability recommendations

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2733]
Scenario | Max Recommended Count | Proxy | Auth server
------------ | -------------|---------|-------
Teleport nodes connected to auth server | 10,000 |2x  2-4 vCPUs/8GB RAM | 2x 4-8 vCPUs/16GB RAM
Teleport nodes connected to proxy server (IOT) | 2,000* | 2x 2-4 vCPUs/8GB RAM |2x 4-8 vCPUs/16+GB RAM

* Teleport 4.1 release will focus on increasing Teleport IOT supported count to 10,000

**Comment by benarent** [comment]
Added to the FAQ for 4.0 Docs
