### ISSUE TITLE
Machine ID: `tbot` IAM joining memory leak

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#27359]
Customer reports memory leak:
- 12.4.2
- IAM joining

![image](https://github.com/gravitational/teleport/assets/16336790/3fc2066e-176e-4f5a-aee7-086feb7282a4)

Potentially reproduced by @strideynet  in `Teleport v12.4.6 git:api/v12.4.6-0-g5253d42 go1.20.4` with IAM joining.

This memory leak looks specific to IAM joining (I was not able to reproduce it on GCP)

**Comment by strideynet** [comment]
This "leak" is proving very hard to trace. I'm looking into it, but one idea floating in my head is that this is just uncollected garbage and that the GC isn't being triggered as there's not enough of it to cause the GC to run.

**Comment by strideynet** [comment]
![image](https://github.com/gravitational/teleport/assets/16336790/dd2f943d-c98b-49a3-a510-6003f93182b9)

**Comment by zmb3** [comment]
@strideynet is this fixed now?

**Comment by strideynet** [comment]
@zmb3 I've been unable to reproduce after the changes made to V14.

**Comment by strideynet** [comment]
Customer confirms that on 13.2.3 this is resolved for them. Closing.
