### ISSUE TITLE
Desktop Playback instructions need updating

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#27363]
## Applies To

https://goteleport.com/docs/desktop-access/reference/sessions/#playback

## Details

Provide the navigation updates included in V12 and V13.  Now session recordings are under the Management pages.

## How will we know this is resolved?

Users can follow the instructions to find session recordings in V12 and V13.

**Comment by zmb3** [comment]
Let's find a way to make this more durable and not require a rewrite every time we change the nav (which we're likely to do again soon with the unified resources view)
