### ISSUE TITLE
Provide a method to execute a script when a node joins

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#27380]
What would you like Teleport to do?
Allow a parameter that would execute a user-defined script when a new node joins a Teleport cluster.

What problem does this solve?
Being able to configure a WebHook to fire when a new node joins a cluster such that Teleport could send the node name and tags it has to a configurable external endpoint.   There can be external tools used to update other teams about the health and status of all services running and what versions said services are running.  It would be useful in getting this information out in near real-time to those tools.

If a workaround exists, please include it.
Use a custom watcher/script to monitors the node list for new nodes and then executes the custom script outside of Teleport

**Comment by zmb3** [comment]
No significant traction on this in almost a year, so closing as not planned for now.
