### ISSUE TITLE
Explain how to list agents that are out of date

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#27389]
<img width="818" alt="warning" src="https://github.com/gravitational/teleport/assets/13717/871f9372-ccb7-4d84-ad1f-dcd33a4ca444">

The message above should point users to the docs:

https://goteleport.com/docs/choose-an-edition/teleport-cloud/faq/#how-can-i-find-version-information-on-connected-agents

Otherwise everyone is asking, "Well, how do I know which ones are out of date?"

**Comment by zmb3** [comment]
See also #17488

**Comment by zmb3** [comment]
Said message was removed, so this is no longer applicable.
