### ISSUE TITLE
Clarify DynamoDB audit event backend schema

### ISSUE THREAD

**Issue by sudaan** [gravitational/teleport#27393]
## Applies To

https://goteleport.com/docs/reference/backends/#dynamodb
## Details

In manage a table by yourself section, then attribute is not applied to the audit event dynamodb.
The value would be 
Partition Key: SessionID (string)
Sort Key: EventIndex(number)
based on the table created by teleport application

## How will we know this is resolved?
Provide a example for audit event dynamodb table

## Related Issues

https://github.com/gravitational/teleport/issues/25056

**Comment by ptgott** [comment]
Addressed in this PR: https://github.com/gravitational/teleport/pull/30363/files
