### ISSUE TITLE
HTTPS_PROXY not being correctly used for connections in v13

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#27397]
Expected behavior: If `HTTPS_PROXY` is set in Teleport's environment, all Teleport connections should be HTTP `CONNECT` requests sent via the proxy.

Current behavior: `HTTPS_PROXY` is not used when checking whether an ALPN connection upgrade is required (and potentially for the actual connections themselves)

```
Jun 05 19:05:37 server1 teleport[45820]: 2023-06-05T19:05:37+02:00 DEBU [PROC:1]    Retrying connection to auth server after waiting 3.885913434s. pid:45820.1 service/connect.go:135
Jun 05 19:05:33 server1 teleport[45820]: 2023-06-05T19:05:33+02:00 ERRO [PROC:1]    Instance failed to establish connection to cluster: Failed to connect to Proxy Server through tunnel: connection error: desc = "transport: Error wh>
Jun 05 19:05:33 server1 teleport[45820]: 2023-06-05T19:05:33+02:00 DEBU [HTTP:PROX] Found proxy "http://squid.proxy.local:8080/" in environment, returning proxy dialer. proxy/proxy.go:201
Jun 05 19:05:33 server1 teleport[45820]: 2023-06-05T19:05:33+02:00 INFO             ALPN connection upgrade test failed for "teleport.cluster.com:443": dial tcp 1.1.1.1:443: i/o timeout. client/alpn_conn_upgrade.go:73
Jun 05 19:05:33 server1 teleport[45820]: 2023-06-05T19:05:33+02:00 ERRO [PROC:1]    Node failed to establish connection to cluster: Failed to connect to Proxy Server through tunnel: connection error: desc = "transport: Error while >
Jun 05 19:05:33 server1 teleport[45820]: 2023-06-05T19:05:33+02:00 DEBU [HTTP:PROX] Found proxy "http://squid.proxy.local:8080/" in environment, returning proxy dialer. proxy/proxy.go:201
Jun 05 19:05:33 server1 teleport[45820]: 2023-06-05T19:05:33+02:00 INFO             ALPN connection upgrade test failed for "teleport.cluster.com:443": dial tcp 1.1.1.1:443: i/o timeout. client/alpn_conn_upgrade.go:73
Jun 05 19:05:03 server1 teleport[45820]: 2023-06-05T19:05:03+02:00 DEBU             Attempting GET teleport.cluster.com:443/webapi/find webclient/webclient.go:128
```

Bug details:
- Teleport version: 13.0.3

**Comment by greedy52** [comment]
> ALPN connection upgrade test failed for "teleport.cluster.com:443": dial tcp 1.1.1.1:443: i/o timeout

ALPN handshake test is not respecting ProxyURL and testing directly against the Proxy server. This result i/0 timeout in this situation and auth connect fails.

Current workaround is to set the following env var for Teleport agent to skip the ALPN handshake test:
```
TELEPORT_TLS_ROUTING_CONN_UPGRADE=false
```

**Comment by lroquec** [comment]
I'm sorry but how exactly can I apply the workaround?...doing export TELEPORT_TLS_ROUTING_CONN_UPGRADE=false does not fix the issue at all, so I must doing it wrong. Could someone please help me?

**Comment by lroquec** [comment]
I'm on version Teleport v13.2.2 and have exactly the same error...In the mean time since I have lan access to server I get it to work not using the proxy for the nodes, instead directly auth_server.
