### ISSUE TITLE
Using tsh scp 

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#27467]
## Applies To

https://goteleport.com/docs/reference/cli/?scope=cloud#tsh-scp

## Details

An additional requirement for tsh scp to function are the following: 
The user role(s) require setting ssh_file_copy: true.  
The teleport host teleport.yaml can have setting ssh_file_copy: true. 

Without this setting in place, or if set to false, could prevent a tsh scp request. 

## How will we know this is resolved?

I think adding this to the SCP note section would suffice. More information on this setting is located is available here: https://goteleport.com/docs/access-controls/reference/

**Comment by zmb3** [comment]
Let's combine this with #22456
