### ISSUE TITLE
Provide a guide on how to use teleport k8s with external proxy

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2746]
## Description

The documentation on how to use Teleport Proxy that is external to kubernetes cluster:

* Should explain that this feature won't work with EKS out of the box.
* For other clusters, should use gen-cert.sh example and show the cluster role binding for the teleport proxy's user.
* This should be a step by step guide I think that works with GKE/kops clusters.

**Comment by webvictim** [comment]
This should be fairly simple:

1) Install UUID (`yum -y install uuid`/`apt-get-y install uuid`)
2) `go get -u github.com/cloudflare/cfssl/cmd/cfssl`
3) `go get -u github.com/cloudflare/cfssl/cmd/cfssljson`
4) Download `https://raw.githubusercontent.com/gravitational/teleport/master/examples/gke-auth/get-kubeconfig.sh`
5) `chmod +x ./kubeconfig.sh`
6) `./kubeconfig.sh`
7) Copy `build/kubeconfig` to your Teleport proxy instance (for example to `/var/lib/teleport/kubeconfig`)
8) Edit `/etc/teleport.yaml` to add `kubeconfig`:

```yaml
proxy_service:
  kubernetes:
    kubeconfig_file: /var/lib/teleport/kubeconfig
```

9) Restart Teleport proxy
10) Log into Teleport proxy from your client machine (`tsh login --proxy=proxy.tld:3080`)
11) Run `kubectl get nodes` and you should get a list of nodes

There's a missing part here with the `Role` and `RoleBinding` for impersonation, but the process I wrote above worked fine on the test kops cluster that I built.

**Comment by awly** [comment]
https://goteleport.com/teleport/docs/kubernetes-access/#option-1-standalone-teleport-gateway-for-multiple-k8s-clusters should be sufficient, with [some pending updates](https://github.com/gravitational/teleport/pull/5061)
