### ISSUE TITLE
IsALPNConnUpgradeRequired check should resect HTTP_PROXY env

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#27461]
## What:
The [IsALPNConnUpgradeRequired](https://github.com/gravitational/teleport/blob/master/api/client/alpn_conn_upgrade.go#L51) check should respect HTTP_PROXY env.

**Comment by greedy52** [comment]
Duplicate of #27397

**Comment by smallinsky** [comment]
Closing in favour of https://github.com/gravitational/teleport/issues/27397
