### ISSUE TITLE
Notes on teleport compatibility

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2747]
## Description

This is an note to whoever is going to write release notes - 3.2 could be upgraded to 4.0, although it's a major release, it's compatible and users can follow our upgrade guide docs.

**Comment by benarent** [comment]
Update: I've created a new label for this task as I've added this to the docs already but wanted to have a reminder for the release notes.

**Comment by benarent** [comment]
Added to release notes draft.
