### ISSUE TITLE
IP handling is broken in 4.x

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2751]
## Problem 1: Node IPs

When Teleport is used in "IoT mode", node IPs become meaningless, i.e. 

```
$ tsh ls
Node Name Address         Labels    
--------- --------------- --------- 
mars      10.5.100.1:3022 env=stage 
moon      10.5.100.1:3022 env=stage 
smb       10.5.100.1:3022 env=prod  
sun       10.5.100.1:3022 env=prod  
```

See? Same IP. BTW the same issue with the web UI.
Also, I cannot SSH into my nodes using their IP addresses.

## Problem 2: Client IP

The client IP as reported in the audit log is not valid:

```
"event":"session.start",
"login":"ekontsevoy", 
"addr.local":"10.2.1.159:39014",
"addr.remote":"172.16.0.1:38560"
```

In this case, `addr.local` is actually correct (!) - that's the IP of the host. But the "remote" IP, i.e. the machine I am accessing this from, is invalid. 

[edit] Looks like the "remote" IP is broken even for non-IoT mode. It's always reporting `172.16.0.1` for me... not even sure where it's getting it from.

## Problem 3: Address Resolution

See comments ([at the bottom](https://github.com/gravitational/teleport/issues/803#issuecomment-497461251)) for #803. User @speeltronics is reporting that when he tries to connect to any "IoT node" he always lands onto a proxy (!).

**Comment by kontsevoy** [comment]
Note: same issue with the web UI.

**Comment by russjones** [comment]
For nodes that do not listen on a port, we'll report them as `← Tunnel` under address with a tool tip that explains they are connected to over a reverse tunnel.

**Comment by kontsevoy** [comment]
Relevant discussion at the bottom of #803
