### ISSUE TITLE
dnf install instructions not working on RHEL 8

### ISSUE THREAD

**Issue by dgkirkwood** [gravitational/teleport#27520]
Expected behavior:
That I can follow the instructions for RHEL 8 here for Teleport install: https://goteleport.com/docs/installation/#installation-instructions
`source /etc/os-release
sudo dnf config-manager --add-repo "$(rpm --eval "https://yum.releases.teleport.dev/$ID/$VERSION_ID/Teleport/%{_arch}/stable/v13/teleport.repo")"

sudo dnf install teleport`

I should get a Teleport install by running these commands. 

Current behavior:

I receive a 404 error on the repository add:
`[ec2-user@ip-10-0-1-119 ~]$ source /etc/os-release
[ec2-user@ip-10-0-1-119 ~]$ sudo dnf config-manager --add-repo "$(rpm --eval "[https://yum.releases.teleport.dev/$ID/$VERSION_ID/Teleport/%{_arch}/stable/v13/teleport.repo](https://yum.releases.teleport.dev/$ID/$VERSION_ID/Teleport/%%7B_arch%7D/stable/v13/teleport.repo)")"
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Adding repo from: https://yum.releases.teleport.dev/rhel/8.6/Teleport/x86_64/stable/v13/teleport.repo
Status code: 404 for https://yum.releases.teleport.dev/rhel/8.6/Teleport/x86_64/stable/v13/teleport.repo (IP: 18.155.202.96)
Error: Configuration of repo failed`

If I change the ${VERSION_ID} to 8 instead of 8.6, this works. 

Bug details:
- Teleport version: 13.0.4
- Recreation steps: See expected behaviour
- Debug logs: N/A

**Comment by webvictim** [comment]
Same thing as https://github.com/gravitational/teleport/issues/20978, which was recently addressed in the docs/installation instructions by https://github.com/gravitational/teleport/pull/27367
