### ISSUE TITLE
Machine ID: `tbot proxy --tunnel` should support reloading renewed credentials

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#27524]
Machine ID `tbot` regularly outputs renewed short-lived credentials.

`tbot proxy --tunnel` loads credentials once on start. This means it does not pick up the renewed credentials from `tbot` and this means that after the initial certificate expires, that new connections to the local proxy will fail.

This issue primarily affects long-term workloads.

Workarounds:

- For short workloads, invoke `tbot proxy --tunnel` for each run of the short workload and ensure the certificate TTL is long enough to cover the the period that the workload may make any new connections.
- For long term workloads, use `tbot proxy` without `--tunnel` and have the workload handle the loading of the rotated credentials. This is not an ideal workaround as it assumes that the workload is a codebase that the user controls.

**Comment by webvictim** [comment]
This also affects `tbot proxy` for application access, as the certs aren't re-read after expiry and any commands hitting the `localhost:<port>` listener will start to return empty responses at some point after this happens.

**Comment by SergeyTsimfer** [comment]
Is there any progress on that feature?

**Comment by strideynet** [comment]
>Is there any progress on that feature?

We don't have any updated timelines on this.

**Comment by strideynet** [comment]
Replaced by https://github.com/gravitational/teleport/issues/36291
