### ISSUE TITLE
tsh cert expiration parameters are not configurable

### ISSUE THREAD

**Issue by drewwells** [gravitational/teleport#27578]
Expected behavior:
if kubeconfig expires, it is possible to set parameters like `bind-addr` on the magic login prompt

Current behavior:
`tsh` autologin creates a web prompt with a randomly assigned port. This port isn't available to the user and causes the login to fail.

Alternatively, I would also like to disable this behavior entirely. It comes up in weird situations like `kubectl config current-context` and causes issues with my cli.

**Comment by stevenGravy** [comment]
@drewwells the env variable `TELEPORT_LOGIN_BIND_ADDR' allows you set to set that in the users env.   https://goteleport.com/docs/reference/cli/#tsh-environment-variables

**Comment by drewwells** [comment]
perfect, thanks
