### ISSUE TITLE
EC2 auto discovery service showing failed status with VERSION_CODENAME  error on the node/agent.

### ISSUE THREAD

**Issue by pnrao1983** [gravitational/teleport#27646]
Expected behavior:
/tmp/install.sh script should execute without any issues and register the agent with Teleport Cluster.

Current behavior:
Observed this behavior especially with Amazon Linux2: 
```
      "Failing with below error:
      "documentStatus": "InProgress",
       "documentTraceOutput": "",
        "runtimeStatus": {
    "runShellScript": {
      "status": "Failed",
      "code": 1,
      "name": "aws:runShellScript",
      "output": "\n----------ERROR-------\n/tmp/installTeleport.sh: line 33: VERSION_CODENAME: unbound variable\nfailed to run commands: exit status 1",
      "startDateTime": "2023-06-08T16:11:10.426Z",
      "endDateTime": "2023-06-08T16:11:10.434Z",
      "outputS3BucketName": "",
      "outputS3KeyPrefix": "",
      "stepName": "",
      "standardOutput": "",
      "standardError": "/tmp/installTeleport.sh: line 33: VERSION_CODENAME: unbound variable\nfailed to run commands: exit status 1""
```

Discovery Service logs:
`Jun 08 16:13:15 ip-172-31-13-219.us-west-2.compute.internal teleport[6884]: 2023-06-08T16:13:15Z INFO [AUDIT]     ssm.run account_id:140211729453 code:TDS00W command_id:831c389b-f05c-4bd8-8d93-a2bab795478d ei:0 event:ssm.run exit_code:-1 instance_id:i-05ef79b7b798e6620 region:ap-south-1 status:Failed time:2023-06-08T16:13:15.036Z uid:de6a7911-ba37-4f84-aeeb-d50fddcaca6b events/emitter.go:265`

Bug details:
- Teleport version: 12.4.6
- Recreation steps:
   Recreated the issue on my test bed and got into the same issue.
- Debug logs
- Updated in the Current behavior section 

Work Around: 
- In order to fix the error temporarily : we can change the default installer script by adding a line of code VERSION_CODENAME=foobar 
- Steps:
1.  Below is the Line of code we are going to modify in default install script:
     https://github.com/gravitational/teleport/blob/master/api/types/installers/installer.sh.tmpl#L31-L36
2. tctl get installer/default-installer > teleport-default-installer.yaml
3. edit and append the line of code VERSION_CODENAME=foobar after the 33rd line:
4. tctl create -f teleport-default-installer.yaml
Below is the code snippet after the update:
```
- # old versions of ubuntu require that keys get added by `apt-key add`, without
  # adding the key apt shows a key signing error when installing teleport.
  LEGACY_UBUNTU=false
  VERSION_CODENAME=foobar
  if [ "$VERSION_CODENAME" = "xenial" ] || [ "$VERSION_CODENAME" = "trusty" ]; then
    LEGACY_UBUNTU=true
  fi
```
- This will fix the issue temporarily.

**Comment by pschisa** [comment]
Same issue reported when running an Oracle Linux Server on EC2
