### ISSUE TITLE
Automatic Windows users are not assigned to Windows groups

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#27644]
Expected behavior:
When `desktop_groups` as described via our [guide](https://goteleport.com/docs/desktop-access/rbac/#user-management), automatically created Windows users will be assigned these groups

Current behavior:
Setting `desktop_groups` is creating the groups but not assigning the Windows users to those groups

Bug details:
- Teleport version: 12.4.5
- Recreation steps
Create a user role with `desktop_groups` groups defined and attempt to have Teleport automatically create and assign users to these groups

**Comment by probakowski** [comment]
Group membership for Teleport managed users is ephemeral - user is not added to the group permanently but the token returned from logon process contains correct group information (user during this session is treated as if they were part of the group). 
Consider example below with role config:
```yaml
desktop_groups:
- abcd
- xyz
- Administrators
``` 
![Zrzut ekranu 2023-06-12 o 21 56 37](https://github.com/gravitational/teleport/assets/3896475/ab29a787-657d-4ed7-9bab-d338932ec8ba)
The user above will have access to all administrative privileges (that's how I opened `mmc` in the first place) even though user management snap-in doesn't show `Administrators` in the group list.
Could you confirm if that's the case?

**Comment by zmb3** [comment]
@pschisa any updates here?

**Comment by pschisa** [comment]
I think both the explination and an upgrade solved the issues.  From the customer:
_" by using latest version 3.1.5 of windows authentication it appears that users are being assigned to the correct groups and correct permissions now. "_

Closing as no longer a reported issue
