### ISSUE TITLE
Allow for custom support page links

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#27648]
What would you like Teleport to do?
Enable the ability to configure a custom support page instead of teleport's support page (https://{proxy}/web/support). Something like allowing users to remove the HTML page and have a configuration option where the support link redirects to a custom URL (e.g. https://{proxy}/web/support -> 302 https://teleport-help.oursite.com) would work.

What problem does this solve?
This helps users who have custom setups and their own support wiki to better assist end users with their unique challenges.

If a workaround exists, please include it.
n/a

**Comment by strideynet** [comment]
User also states that the ability to just disable this page entirely would also work in the midterm as a way to avoid their end users being directed to Teleport's resources.

**Comment by zmb3** [comment]
See also #3863
