### ISSUE TITLE
Unable to generate working ssh_config when using --identity with tsh

### ISSUE THREAD

**Issue by mvgijssel** [gravitational/teleport#27659]
### Expected behavior:

When running 

```
tsh config --identity=buildbuddy_identity
```

It generates a SSH config file containing references to the right user

```
# Begin generated Teleport configuration for tele.vgijssel.nl by tsh

# Common flags for all provisioner hosts
Host *.provisioner tele.vgijssel.nl
    UserKnownHostsFile "/home/devcontainer/.tsh/known_hosts"
    IdentityFile "/home/devcontainer/.tsh/keys/tele.vgijssel.nl/buildbuddy"
    CertificateFile "/home/devcontainer/.tsh/keys/tele.vgijssel.nl/buildbuddy-ssh/provisioner-cert.pub"
    HostKeyAlgorithms rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com

# Flags for all provisioner hosts except the proxy
Host *.provisioner !tele.vgijssel.nl
    Port 3022
    ProxyCommand "/home/devcontainer/bazel/output_base/external/teleport_arm64/teleport/tsh" proxy ssh --cluster=provisioner --proxy=tele.vgijssel.nl %r@%h:%p

# End generated Teleport configuration
```

where the referenced files also exist on disk.

### Current behavior:

Unable to use the generated config because the referenced files in the config don't exist. Also unknown how to generate these files, because `tsh login --identity=buildbuddy_identity` does not work and results in 

```
ERROR: -i flag cannot be used here
```

### Bug details:

```
devcontainer@d42ed4873fd2:/workspaces/setup$ tsh version
Teleport v13.0.0 git:v13.0.0-0-g6d0ce2b go1.20.4
Proxy version: 13.1.0
Proxy: tele.vgijssel.nl:443
```

**Comment by stevenGravy** [comment]
@mvgijssel have you looked at using machine-id.  That sets up a ongoing certification and ssh_config. https://goteleport.com/docs/machine-id/getting-started/

**Comment by mvgijssel** [comment]
Yes I have! But because there is no support for BuildBuddy CI yet, I have to use an identity file. Eagerly awaiting https://github.com/gravitational/teleport/issues/26885😍

**Comment by mvgijssel** [comment]
I managed to get a first working version by doing the following. Generating **both** the identity file and the openssh files on the Teleport server

```
tctl auth sign --out=buildbuddy.identity --ttl=1d --format=file --user buildbuddy
tctl auth sign --out=buildbuddy --ttl=1d --format=openssh --user buildbuddy
```

generate the ssh config with

```
tsh config > ssh_config
```

and updating the generated ssh config like

```
# Begin generated Teleport configuration for tele.vgijssel.nl by tsh

# Common flags for all provisioner hosts
Host *.provisioner tele.vgijssel.nl
    IdentityFile "buildbuddy" # use generated OpenSSH private key here
    CertificateFile "buildbuddy-cert.pub" # use generated OpenSSH public certificate here
    HostKeyAlgorithms rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com

# Flags for all provisioner hosts except the proxy
Host *.provisioner !tele.vgijssel.nl
    Port 3022
    ProxyCommand "/home/devcontainer/bazel/output_base/external/teleport_arm64/teleport/tsh" proxy ssh --add-keys-to-agent=no --cluster=provisioner --proxy=tele.vgijssel.nl --user buildbuddy --identity buildbuddy.identity %r@%h:%p # specify the right user and pass in the identity file

# End generated Teleport configuration
```

Enables me to login to ssh using 

```
ssh -F ssh_config ubuntu@provisioner.provisioner
```

Looking at the contents of the identity file, I'd image it's possible to split that file and extract the `buildbuddy` and `buildbuddy-cert.pub` from that for SSH.

**Comment by stevenGravy** [comment]
fyi @mvgijssel the next release will automatically include the proxy web port in the `--port` parameter.

**Comment by hugoShaka** [comment]
We added support for `tsh login -i <identity.pem>` which logs the user with the identity and flattens the identity file into a local profile. You should be able to run `tsh config` without the `--identity` after this step.

PR: https://github.com/gravitational/teleport/pull/39024

As far as I understand, this solves the initial issue. I will close it, if this is a mistake please reply so I can reopen it.
