### ISSUE TITLE
"How to Build an Access Request Plugin" guide doesn't work

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#27696]
### Expected behavior:

Following the guide should result in a working plugin.

### Current behavior:

The guide does not explain how to install the teleport Go libraries, which is a bit non-standard process described here https://goteleport.com/docs/api/getting-started/#step-33-create-a-go-project, but that probably doesn't even work for reasons explained in the following paragraph

The example Go program imports `github.com/gravitational/teleport-plugins/lib` and `github.com/gravitational/teleport-plugins/lib/watcherjob`, which no longer exist in recent versions of `teleport-plugins`. Their new locations are in `github.com/gravitational/teleport/integrations/lib`, but it seems difficult/impossible to import these packages alongside an external import of the `github.com/gravitational/teleport/api` package.

### Workaround:

Replace these imports in the example Go code:
`github.com/gravitational/teleport-plugins/lib` => `github.com/gravitational/teleport/integrations/lib`
`github.com/gravitational/teleport-plugins/lib/watcherjob` => `github.com/gravitational/teleport/integrations/lib/watcherjob`

Instead of relying on `go` commands to automatically download the right teleport libraries, clone it locally in a subdirectory of `teleport-sheets` (created in the guide):
```bash
$ git clone --depth=1 --branch v12.3.1 https://github.com/gravitational/teleport
```
Set the `--branch` flag to the same version of Teleport that your cluster auth/proxy are running.

In the local `teleport-sheets` module created as part of the guide, remove all references to `github.com/gravitational/teleport` and `github.com/gravitational/teleport/api` from `go.mod`, then run
```bash
$ go mod edit -replace github.com/gravitational/teleport=./teleport -replace github.com/gravitational/teleport-api=./teleport/api
$ go mod tidy
```

The example should then be able to build and run

**Comment by ptgott** [comment]
This PR adds the demo code to the `examples` directory and uses partials to share code between the `examples` directory and the guide: https://github.com/gravitational/teleport/pull/23255

We should edit this PR to incorporate the workaround before merging it.

**Comment by ptgott** [comment]
Another possibility is to build a slimmed-down version of `watcherjob` for the guide based on `api` packages. It looks like `*Client.NewWatcher` ([GitHub](https://github.com/gravitational/teleport/blob/d80ab5b556591f372182ea51fe9a6a11a5889990/api/client/streamwatcher.go#LL31C2-L31C2)) would be a good place to start with this.
