### ISSUE TITLE
Machine ID: Allow `tbot proxy` to bind to an address other than localhost

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#27692]
### Proposal

Currently, `tbot proxy` is hardcoded to bind to `localhost`. This limitation can impede certain Kubernetes and pod use cases. For instance, when using Teleport's `tbot proxy`, users might want to connect to multiple service instances running in different pods within the same cluster to allow them to access the Teleport resource. Allowing `tbot proxy` to bind to a specified address, such as `0.0.0.0`, would enhance the user experience in these situations and reduce complex configurations or workarounds. Additionally, network policies and other firewall rules can limit traffic to the authenticated tunnels from only authorized sources.

As such, it would be helpful for users to have a configuration option to specify the network interface/IP address for `tbot proxy` to bind to. This would enrich flexibility and provide better support for various deployment scenarios, especially in Kubernetes or other container environments.

### Considered Workarounds

- Use a `netcat` container/process to redirect traffic from `0.0.0.0` to `localhost`, but this is quite hacky.
- Use a sidecar container approach, although this has caveats like the inability to manage database connection configurations in a single place and the need to update multiple affected job workflow specifications instead of just the proxy pod.

**Comment by strideynet** [comment]
This limitation actually resides in `tsh`. We'll either need to make it possible directly in `tsh`, or, stop relying on calling out to `tsh` for this behaviour in `tbot`.

There's definitely a bit of a security/philosophical consideration here - in many ways, it would be preferable to continue to push people down the sidecar path. 

If we enable this behaviour, it becomes fully possible that users can create a configuration that creates an open port that when connected to without credentials, provides unfettered access to their database. On the other hand, there's definitely a usability issue here. It's worth us considering if there are things we can do to make the sidecar experience easier and if that would make it usable enough to avoid implementing support for this.

**Comment by strideynet** [comment]
Implementation of https://github.com/gravitational/teleport/issues/36291 has enabled this now - proxies can bind to any port or to a UDS.
