### ISSUE TITLE
Create users with NSS instead of useradd

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#27727]
What would you like Teleport to do?

We'd like to use this feature [automatically create host users](https://goteleport.com/docs/server-access/guides/host-user-creation/#step-22-test-host-user-creation), but unfortunately cannot. The /etc/passwd, /etc/shadow, and /etc/group files on our systems are immutable, so operations like calling `useradd` and similar do not work.

Teleport already ships a PAM module. It would be great if Teleport would also ship an NSS (Name Service Switch) module. This is a way of implementing auto-user creation without having to mutate these configuration files.
NSS complements PAM and can co-exist with it. An example implementation of PAM+NSS for user creation is Google's OS Login. 
The code of the guest-agent is open source and you can find it here: https://github.com/GoogleCloudPlatform/guest-oslogin. The README also explains how the whole thing works.

What problem does this solve?
The feature is considered Nice to have to get more value from using Teleport.

**Comment by zmb3** [comment]
Hi @oshati - this one is not planned. User creation has changed a bit recently for security reasons, so you may want to take a fresh look at the latest and see if it addresses the original concern.
