### ISSUE TITLE
User validation issues

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2776]
If a invalid local user is somehow create (for example, user with a space in their name): it appears if any user fails validation, no user is able to login (atleast in gravity).

Error message in the logs.

```
2019-06-14T18:50:27Z WARN             failed to SSH: ssh: rejected: administratively prohibited (Unable to create identity from connection: special characters are not allowed in resource names, please use name composed only from characters, hyphens and dots) web/terminal.go:216
```

Also would be nice if we had better error logs on what failed validation so it can be debugged easier.

**Comment by benarent** [comment]
In Teleport we do let customers create invite tokens for users with spaces. 
![image](https://user-images.githubusercontent.com/559288/72480047-face1800-37aa-11ea-86b7-67931c59bb82.png)

^ This is perhaps an edge case but let's review again after we've completed the Gravity & Teleport SSO work.

**Comment by sebschlue** [comment]
I am confused because of this error:

```
$ tctl users rm heinz
error: special characters are not allowed in resource names, please use name composed only from characters, hyphens and dots
```

`tctl users rm` works fine for other user names, but "heinz" is rejected.

**Comment by inabil** [comment]
Same, I'm also confused.
teleport ~]# tctl users rm shahbaz
ERROR: special characters are not allowed in resource names, please use name composed only from characters, hyphens and dots: "/web/users/shahba{"

**Comment by wojtokuba** [comment]
I found that the problem is in letter z at the very ending of the username. Same with my username. Im getting ERROR: special characters are not allowed in resource names, please use name composed only from characters, hyphens and dots: "/web/users/jakub.wojtowic{" while executing tctl users rm jakub.wojtowicz
