### ISSUE TITLE
MFA - it works for a week or so, then I does not work anymore - TSH LOGIN...

### ISSUE THREAD

**Issue by OneideLuizSchneider** [gravitational/teleport#27778]
Expected behavior:
Login using TSH without issues.

Current behavior:

It should login, but the MFA/pass does work, for all users that use `tsh login --proxy=teleport.myhost.com:443 --auth=local --user=username teleport.myhost.com`
the same problem as here #13338

One of log errors:
```
ERROR REPORT:
Original Error: *trace.AccessDeniedError too many incorrect attempts, please try again later
```
```
code":"T1000W","time":"2023-06-12T22:06:47.983Z","cluster_name":"teleport.myhost.com","user":"username","success":false,"error":"invalid username, password or second factor","method":"local","user_agent":"Go-http-client/1.1"
```

My installation is with Docker.
It was working normally until last Friday.

Sometimes on teleport UI it works as well, but I need it with TSH...
So this is weird, we really wanna use it but I'm not sure because this is happening every 2 weeks.

And just for you know, I'm in Germany and my colleagues are in US.

And today, I restored the database from friday again, reboot the instance as well, and Sync the time with AWS every 15s using `chrony`.
Now it is working again, but it's my last shot here.

Any thoughts will be great.

Bug details:
- Teleport version 13.0.3

**Comment by zmb3** [comment]
Sounds like clock drift to me.

**Comment by zmb3** [comment]
@OneideLuizSchneider Are things working for you after syncing the time?

**Comment by OneideLuizSchneider** [comment]
@zmb3 It's working with `chrony` time sync, but I'll wait a week more until I come back here to close the issue.

**Comment by OneideLuizSchneider** [comment]
Just to finish the issue, it is still working, so that time sync is the solution.

**Comment by behnambm** [comment]
My Teleport auth service was located in Germany and I was connecting to it from Iran. 
The timezone of server was UTC and clients were Asia/Tehran. 

I tried setting the same timezone for both but didn't work. 

Then i moved my Teleport server to Iran and now it works. 

Could you please share some detail about fixing this problem with NTP server?
@OneideLuizSchneider

**Comment by OneideLuizSchneider** [comment]
@behnambm 

Howdy
Yeah, As I said, I just changed the time sync. to `Chrony `.
I never had an issue anymore.

Basically what I did was:
```
sudo yum erase ntp*
sudo yum -y install chrony
sudo service chronyd start
sudo chkconfig chronyd on
```

**Comment by behnambm** [comment]
@OneideLuizSchneider 

Thanks for the help.
