### ISSUE TITLE
Display a more descriptive error message when RBAC denies a desktop session

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#27776]
Currently when a desktop session is refused due to RBAC, the user sees a generic error message:

<img width="755" alt="image" src="https://github.com/gravitational/teleport/assets/13578537/8bc6b887-7905-4c40-ae2e-0a49483eacf3">

Change this so that it's clear that they were denied due to RBAC

**Comment by zmb3** [comment]
<img width="733" alt="image" src="https://github.com/gravitational/teleport/assets/7527103/ca8c5c7f-9639-47e8-b854-5e8d67c1a503">

I'm now seeing a more descriptive error, so we must have fixed this.
