### ISSUE TITLE
Self-hosted automatic agent updates without a version server

### ISSUE THREAD

**Issue by stefankaufmann** [gravitational/teleport#27782]
**What would you like Teleport to do?**

The setup for "[self-hosted automatic agent updates](https://goteleport.com/docs/management/operations/self-hosted-automatic-agent-updates/)" seems overcomplicated. Setting up a separate webserver just for serving the current version number of Teleport should be avoided. Instead, teleport should have an API endpoint which provides the current version directly. All clients already access Teleport using https, therefore I see no reason for not simplifying this. 

I am aware that the current solution is a preview feature, but I am highly interested in the final solution and would like to push for a solution which does not require a second server.

**What problem does this solve?**
Usability will be massively improved. No second server required, no manual maintenance of the version number required.

**Comment by zmb3** [comment]
@bernardjkim can we close this now that #36220 is merged?

**Comment by ravicious** [comment]
Is the stuff introduced by #36220 documented anywhere?

**Comment by bernardjkim** [comment]
See https://goteleport.com/docs/upgrading/ for more details.
