### ISSUE TITLE
"certificate authority missing SSH key pairs"

### ISSUE THREAD

**Issue by kurtisane** [gravitational/teleport#27802]
Currently I'm having difficulties login into my teleport server over a teleport client on a Ubuntu machine. 
Weirdly it is working over Windows machines.

Login command :
tsh login --proxy=myteleportserver.com:443 --user=TELEPORTUSERNAME

After promting me for password and OTP I'm facing following error message :
certificate authority missing SSH key pairs

Any suggestions what is causing this  ?

Bug details:
- Teleport version 
Teleport Server 6.1.1 / Teleport Client 11.3.1

**Comment by zmb3** [comment]
Clients must be at the same major version as the server, or 1 version behind. Your client is **5** major versions ahead of your server. That's not likely to work.
