### ISSUE TITLE
User agent missing

### ISSUE THREAD

**Issue by Kenyre** [gravitational/teleport#2782]
**What happened**:
tsh login functions as it should. But trying to use the generated certificate with OpenSSH always results in user agent missing. I've tried both with the generated certificate in my ssh-agent, as well as manually specifying the cert file location in the .ssh/config file.

**What you expected to happen**:
I expected to be able to ssh into our server (as was possible via the web UI).

**How to reproduce it (as minimally and precisely as possible)**:
Login through the tsh client on windows. (we have u2f enabled, so yubikey authentication is required). The following settings have been set in my .ssh/config file. Then try to ssh using ssh -vvv ubuntu@HOSTNAME . 
The simpler version specified in https://gravitational.com/teleport/docs/user-manual/#ssh-proxy-configuration has been tried as well.

Host HOSTNAME
  Port 3022
  IdentityFile C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri
  ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -i C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri -p 3023 %r@PROXY_ADDRESS -s proxy:%h:%p

**Environment**:
- Teleport version (use `teleport version`): 4.0
- Tsh version (use `tsh version`): 4.0
- OS (e.g. from /etc/os-release): Windows

**Relevant Debug Logs If Applicable**

ssh -vvv ubuntu@HOSTNAME
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\Joeri/.ssh/config
debug1: C:\\Users\\Joeri/.ssh/config line 1: Applying options for HOSTNAME
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug1: Executing proxy command: exec C:\\Windows\\System32\\OpenSSH\\ssh.exe -i C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022
debug3: spawning "C:\\Windows\\System32\\OpenSSH\\ssh.exe" -i C:\\Users\\Joeri\\.tsh\\keys\\bastion.bitvavo.com\\Joeri -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022
debug3: w32_getpeername ERROR: not sock :2
debug1: identity file C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri type 0
debug3: Failed to open file:C:/Users/Joeri/.tsh/keys/PROXY_ADDRESS/Joeri-cert error:2
debug1: identity file C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri-cert type 4
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
error: user agent missingsubsystem request failed on channel 0
ssh_exchange_identification: Connection closed by remote host

PS. I changed our proxy address to PROXY_ADDRESS and my hostname to HOSTNAME. I did ofcourse not use these names in the files.

**Comment by benarent** [comment]
Thanks for reporting @Kenyre . Let me get someone on our side to replicate this, and we'll get back to you soon.  Was this bug introduced after upgrading?

**Comment by Kenyre** [comment]
I've started with version 3.2.6, but updated to test if it would make a difference. The same problem however arose in both versions. (i am not exactly aware what version our auth and proxy server are running, do these have to be the same version as the client?) I'll contact the admin for the proxy and auth server teleport versions.

**Comment by russjones** [comment]
@Kenyre You need to pass either `-A` from the command line or set `ForwardAgent yes` in your `~/.ssh/config` for the host you are connecting to.

**Comment by Kenyre** [comment]
Hi @russjones,

Sorry for the late reaction, been on vacation for a while. I've tried specifying the forwardAgent, both through my .ssh/config file using ForwardAgent yes, as well as in the command line using -A.
I have also tried specifying other identity files (tsh login seems to produce multiple files, i tried to use the file which had the same content as was shown through ssh-add -L, which was the USER-cert.pub file).

This means i have tried the following combinations of config file and command line options:

*config:*
Host HOSTNAME
  Port 3022
  IdentityFile C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub
  ForwardAgent yes
  ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -i C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub -A -p 3023 %r@PROXY_ADDRESS -s proxy:%h:%p
*commandline:*
ssh -vvv ubuntu@HOSTNAME

*config:*
Host HOSTNAME
  Port 3022
  IdentityFile C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub
  ForwardAgent yes
  ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -i C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub -p 3023 %r@PROXY_ADDRESS -s proxy:%h:%p
*commandline:*
ssh -vvv -A ubuntu@HOSTNAME

*config:*
Host HOSTNAME
  Port 3022
  IdentityFile C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub
  ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -i C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub -p 3023 %r@PROXY_ADDRESS -s proxy:%h:%p
*commandline:*
ssh -vvv -A ubuntu@HOSTNAME

All unfortunately end in the same kind of error. Starting with `debug3: w32_getpeername ERROR: not sock :2` in the debug and ending with `error: user agent missingsubsystem request failed on channel 0` .
I will again attach the full stacktrace of the last execution in case it might help:


ssh -vvv -A ubuntu@HOSTNAME
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\Joeri/.ssh/config
debug1: C:\\Users\\Joeri/.ssh/config line 1: Applying options for HOSTNAME
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug1: Executing proxy command: exec C:\\Windows\\System32\\OpenSSH\\ssh.exe -i C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri-cert.pub -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022
debug3: spawning "C:\\Windows\\System32\\OpenSSH\\ssh.exe" -i C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri-cert.pub -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022
debug3: w32_getpeername ERROR: not sock :2
debug1: identity file C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri-cert.pub type 4
debug3: Failed to open file:C:/Users/Joeri/.tsh/keys/PROXY_ADDRESS/Joeri-cert.pub-cert error:2
debug3: Failed to open file:C:/Users/Joeri/.tsh/keys/PROXY_ADDRESS/Joeri-cert.pub-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri-cert.pub-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
error: user agent missingsubsystem request failed on channel 0
ssh_exchange_identification: Connection closed by remote host
