### ISSUE TITLE
Teleport 4.0 to run on older OS Versions

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#2783]
**What happened**:
Teleport 4.0 is being built with GoLang 1.12.1 which requires  GLIBC_2.14. Currently we have a customer running on CentOS 6, and would like to use `Linux 64-bit (FedRAMP/FIPS)`

**What you expected to happen**:
Teleport 4.0 to run on CentOS. Customer is open to installing a newer version of glibc to `/opt/teleport-ent` if this fixes the problem. 

**Environment**:
- Teleport version (use `teleport version`): Linux 64-bit (FedRAMP/FIPS)
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release): CentOS6

**Comment by russjones** [comment]
[Building and installing a parallel version of glibc is going to be the best approach](https://stackoverflow.com/questions/32316707/rhel-6-how-to-install-glibc-2-14-or-glibc-2-15). Doing that I was able to build and install glibc 2.14 on CentOS 6 and run the FIPS build of Teleport.

Reproducing steps from the above post here:

```
1. wget http://mirrors.ocf.berkeley.edu/gnu/libc/glibc-2.14.1.tar.gz
2. tar xvfz glibc-2.14.tar.gz
3. cd glibc-2.14
4. mkdir build
5. cd build
6. ../configure --prefix=/opt/glibc-2.14
7. make
8. make install
9. LD_LIBRARY_PATH=/opt/glibc-2.14/lib:$LD_LIBRARY_PATH teleport start ...
```

Some of the alternatives:

1. Run Teleport within a Docker contain that has a newer version of glibc.
2. Either build all FIPS builds with an older version of glibc or create another FIPS release built against a older version of glibc.

It should be noted I also also built Teleport with `-ldflags '-w -extldflags "-static"'`. During the build, warnings like these were logged.

```
/tmp/go-build/cgo-gcc-prolog:185: warning: Using 'dlopen' in statically linked
applications requires at runtime the shared libraries from the glibc version used for
linking
```

So it appears even with `-extldflags "-static"` this wouldn't really give us a static build.
