### ISSUE TITLE
AMI letsencrypt cert renewal should not sync audit events

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#27884]
### Expected behavior:

The [teleport-renew-cert](https://github.com/gravitational/teleport/blob/master/assets/aws/files/bin/teleport-renew-cert) script should renew the letsencrypt certs without filling the disk of the auth server.

### Current behavior:

When the script runs, it syncs the entire bucket to /etc/letsencrypt. This includes the `records` directory, which is where the auth servers are configured to store audit logs. https://github.com/gravitational/teleport/blob/19e36d6a67af736f446359bfe4929d223a13e906/assets/aws/files/bin/teleport-renew-cert#L20

As more audit logs are stored, this can make the records directory large enough to fill the disk, and eventually make cert renewal fail.

I believe that adding `--exclude records` to the `aws s3 sync` command may be all that is needed.

### Bug details:
- Teleport version- n/a
- Recreation steps- set up a terraform ha provider with letsencrypt enabled. observe the renewal process copy a large directory, 'records' to '/etc/letsencrypt'.
- Debug logs- n/a

**Comment by andreyzhelnin-st** [comment]
The bug still present in the us-east-1 v15.3.7 arm64 OSS AMI
