### ISSUE TITLE
Wrong help text on ls verbose flag

### ISSUE THREAD

**Issue by maeserichar** [gravitational/teleport#2797]
**What happened**:
The help text for the verbose flag in ls command is the same as for the cluster parameter
```
      --cluster             Specify the cluster to connect
  -v, --verbose             Specify the cluster to connect
```
**What you expected to happen**:
A correct help text describing the flag.
**How to reproduce it (as minimally and precisely as possible)**:
`tsh ls --help`

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`): Teleport v3.1.5 git:v3.1.5-0-g7621bbd5 go1.11.5
- OS (e.g. from /etc/os-release): Ubuntu 18.04

**Comment by maeserichar** [comment]
If you are ok with something in the line of `Print everything on a single line and include the Node ID` I can do a PR with the change.

**Comment by russjones** [comment]
Fixed by @webvictim.
