### ISSUE TITLE
Teleport Connect: native support for `tsh proxy kube`

### ISSUE THREAD

**Issue by FireDrunk** [gravitational/teleport#28049]
**What would you like Teleport to do?**
Builtin native support for `tsh proxy kube` in Teleport Connect.
Starting Teleport Connect, and navigating to to Kubernetes Clusters, and clicking connect, only opens a terminal to start `tsh proxy kube` manually. To connect afterwards, you have to open another terminal and attempt to connect again. This seems counter-intuitive.

I think teleport-connect should always start the `tsh proxy kube` upon launch (or at least have the option to do so). After opening a terminal it could inject the requried environment variables (if any).

**What problem does this solve?**
Having to open 2 terminals to use Kuberentes Clusters in Teleport Connect, with weird subcommands.

**If a workaround exists, please include it.**
One might be able to start `tsh proxy kube` in their .bashrc, the same way an ssh-agent works, but that seems like Teleport Connect's responsibility.

**Comment by ravicious** [comment]
At the moment Teleport Connect does not use `tsh proxy kube`, but @greedy52 is working on implementing that.

The way kube support in Teleport Connect works at the moment is that upon opening a new kube tab, Teleport Connect generates a unique kubeconfig path for the given kube cluster, sets the path as `KUBECONFIG` and then does `tsh kube login` followed by opening a shell.

That unique kubeconfig path will stay the same until you either manually log out of the Teleport cluster in Connect or open the connections list in the top left and manually remove that kube connection from there.

The kubeconfig will continue to work even after closing Connect, as long as the certs are valid. If you have 3rd party tools such as [Lens](https://k8slens.dev/), you should be able to point them at that kubeconfig and have them work with a kube cluster guarded by a Teleport cluster.

Does this help with your use case? I'm not sure what exactly you have a problem with, but just to restate it, opening a new kube tab does not launch `tsh kube proxy`.

---

@greedy52 Could you confirm that this behavior will stay the same after you implement `tsh proxy kube` into Connect? I think we agreed to make the `KUBECONFIG` behavior stay the same. AFAIK the only thing which would change compared to what I've described above is that to make 3rd party tools work with `tsh proxy kube`, Connect needs to be running and at least a single kube tab open needs to be open.

**Comment by greedy52** [comment]
Yes. Will implement as discussed/described. I am also curious the use case of `tsh proxy kube` in Connect. It should be only required if Proxy is behind a layer 7 load balancer. Other than that, with the current release, the $KUBECONFIG set by new kube tab in the terminal should usually suffice.

**Comment by tigrato** [comment]
> Other than that, with the current release, the $KUBECONFIG set by new kube tab (tsh kube login) in the terminal should usually suffice.

If you have MFA devices it's annoying to tap the MFA device each minute to generate new cert.

**Comment by greedy52** [comment]
> If you have MFA devices it's annoying to tap the MFA device each minute to generate new cert.

Per-session MFA support for Database is not added for Connect though (`proto.UserCertsRequest_TSH_KUBE_LOCAL_PROXY`). So I wasn't planning to add it for kube proxy in my implementation.

**Comment by FireDrunk** [comment]
> Yes. Will implement as discussed/described. I am also curious the use case of `tsh proxy kube` in Connect. It should be only required if Proxy is behind a layer 7 load balancer. Other than that, with the current release, the $KUBECONFIG set by new kube tab (`tsh kube login`) in the terminal should usually suffice.

Well, exactly that, I'm using the new TLS Routing Multiplex option, so I have to use the proxy.
When using Teleport Connect, that means opening 2 tabs, and start the proxy in one, and then open another to use.

**Comment by ravicious** [comment]
Ah sorry, I understand now what your problem is. This is exactly what @greedy52 is working on at the moment.

**Comment by FireDrunk** [comment]
@greedy52 Do you need any more information / testing for this feature? Can we help in any way?

**Comment by greedy52** [comment]
> @greedy52 Do you need any more information / testing for this feature? Can we help in any way?
 
We are currently working on this and it will be released in v14. Starting v14, When you open a new kube tab, a local proxy will automatically start in the background and it will handle the connection upgrade for the load balancer transparently.

Would appreciate it if you can try this when v14 is out and provide any feedback.

>  Thanks! Interesting, does that mean kube proxy isn’t needed when bypassing the load balancer?

Kube proxy is needed if there is a layer 7 load balancer or reverse proxy. But it might be also needed if it is layer 4 load balancer that terminates TLS. 

`tsh kubectl` automatically starts a local proxy if it thinks a local proxy is required. Otherwise `tsh kubectl` would send requests straight to Teleport Proxy (and in this case native `kubectl` can work directly without `tsh proxy kube` too).

For this Teleport Connect feature releasing in v14, a new kube tab will always start a kube local proxy in the background, regardless there is a load balancer or not. Just for consistency. Teleport Connect is already doing local proxies for database connections.

**Comment by FireDrunk** [comment]
> > @greedy52 Do you need any more information / testing for this feature? Can we help in any way?
> 
> We are currently working on this and it will be released in v14. Starting v14, When you open a new kube tab, a local proxy will automatically start in the background and it will handle the connection upgrade for the load balancer transparently. (no need for another tab/terminal)
> 
> Would appreciate it if you can try this when v14 is out and provide any feedback.

Will do, shout out if there is a downloadable beta.

**Comment by ravicious** [comment]
v14 which includes changes related to this is out now. Give it a try and we're looking forward to your feedback!

**Comment by FireDrunk** [comment]
@greedy52 
I'm still getting:
```
ERROR: Cannot connect Kubernetes clients to Teleport Proxy directly. Please use `tsh proxy kube` or `tsh kubectl` instead.
```
When using v14.2, is that expected behavior?

**Comment by ravicious** [comment]
v14+ starts a proxy for new kube tabs. `KUBECONFIG` in those tabs should point to a folder that follows this structure: `<Connect config dir>/kube/keys/<proxy>/<cluster-username>-kube/<cluster>/<kube-cluster>-kubeconfig`.

However, if you had an open kube tab in Connect v13, then upgraded to v14 and reopened the tabs when launching the app, Connect is going to use the old kube implementation. The path of `KUBECONFIG` will be different in that case. Reopening an existing tab with the old kube implementation is the only reason that comes to my mind as to why you're getting that error.

Could you try to reproduce the issue by finding the kube cluster in Connect's UI and then clicking the "Connect" button next to it? This opens a new tab and should use an equivalent of `tsh kube proxy` underneath.

If you're able to reproduce the issue this way, then please [submit a new issue with logs included](https://goteleport.com/docs/connect-your-client/teleport-connect/#submitting-an-issue).
