### ISSUE TITLE
`teleport exec` does not handle `SIGQUIT` gracefully

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#28070]
Customer is using a supervisor that sends `SIGQUIT` to the entire process group and while the parent `teleport` process handles it correctly and initiates a graceful shutdown, spawned `teleport exec` child processes that handle the user session are stopped immediately terminating the session.

We should make sure user sessions are not terminated in this case by handling the signal gracefully (or just ignoring it in the child process?). Let's confirm this behavior and compare with sshd as well first.

**Comment by Joerger** [comment]
I was able to reproduce this with `kill -SIGQUIT $(pidof teleport)`. However, if you only SIGQUIT the parent process, it waits for the child processes to close (graceful shutdown). OpenSSH has the same behavior.

It would not be difficult to ignore SIGQUIT in child processes, but I'm not sure this behavior would be generally expected. WDYT?

**Comment by r0mant** [comment]
@Joerger What do you think the expected behavior should be? `SIGQUIT` is supposed to be graceful shutdown but since all `teleport exec` does is handles the user session, wouldn't ignoring the signal effectively be equivalent to graceful shutdown (i.e. waiting for user session to complete on its own)?

**Comment by Joerger** [comment]
@r0mant My point is just that OpenSSH has the same behavior. `kill -SIGQUIT $(pidof sshd)` gracefully shuts down sshd but ungracefully shuts down any user sessions. Usually we base expected behavior off of OpenSSH.

That being said, deviating from OpenSSH seems reasonable here. We can simply ignore `SIGQUIT` in the user sessions as you said.
