### ISSUE TITLE
request: teleport-plugins docker images for linux arm64

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#28087]
### What would you like Teleport to do?

Currently, images in `public.ecr.aws/gravitational/teleport-ent` and `public.ecr.aws/gravitational/teleport` are multiarch images that support amd64, arm, and arm64. The `public.ecr.aws/gravitational/teleport-plugin-*` repositories are amd64 only.

### What problem does this solve?

Some teams are moving away from x86_64 and adopting arm64, especially with the AWS Graviton servers.

### If a workaround exists, please include it.

Currently, teams must build their own container images to run teleport plugin containers on arm.

**Comment by zmb3** [comment]
Closing as duplicate of #25416
