### ISSUE TITLE
Teleport demo environments don't restart a failed teleport

### ISSUE THREAD

**Issue by knisbet** [gravitational/teleport#2811]
**What happened**:
When testing configuration changes in a teleport demo environment, teleport accidentally exited, and was not restarted. 

**What you expected to happen**:
The teleport process exit should have triggered the container to fail and be restarted.

**How to reproduce it (as minimally and precisely as possible)**:
Kill the teleport process in a demo environment

**Additional**
https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-demo/docker/teleport-ent/rootfs/scripts/teleport.sh#L18 appears to be the cause. The script launches teleport in the background, and then holds itself open.

**Comment by klizhentas** [comment]
could be mitigated by using teleport readiness probe, ideally we remove the background shell script as well, it's not ideal

**Comment by webvictim** [comment]
The reason for the background shell script is that we don't have any good way to run `tctl`-based commands automatically when the Teleport server starts. There's already one sidecar container in this pod for other operations - I didn't want to add more and make this even more complicated than it already is. If anyone has other suggestions about ways to remove the background shell script, I'm listening.
