### ISSUE TITLE
Support multiline MOTD in UI

### ISSUE THREAD

**Issue by sshahcodes** [gravitational/teleport#28201]
Expected behavior:
Should support multiline MOTD. More details reported here: https://github.com/gravitational/teleport/pull/27922#issuecomment-1594955385

Current behavior:
Multiline is not supported

Bug details:
This issue hits MOTD feature added to v13, v12 and v11.

**Comment by zmb3** [comment]
@sshahcodes additional web UI request - up to you whether you want to include it in scope here or break it out into a separate issue.

> Since headless already shows the MOTD when you tsh, could we exclude it from being shown if the redirect URI is a headless approval link? This adds an extra layer of clicks to the approval process which already takes a bit.

**Comment by sshahcodes** [comment]
Tracking headless auth issue in a separate ticket - https://github.com/gravitational/teleport/issues/28746
