### ISSUE TITLE
Emit auto-discovery Posthog events

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#28245]
Currently we don't have any visibility into how many people are using auto-discovery in the Cloud. Let's add a Posthog event that is emitted whenever an auto-discovered resource of any type was added to the cluster. We should be able to differentiate by kind and protocol, similar to the service heartbeat events.

**Comment by atburke** [comment]
Planning for the new event to look something like this:
```
message ResourceDiscoveredEvent {
  string resource_type = 1;  // "ssh", "k8s", "db"
  string cloud = 2;  // "aws", "azure", "gcp"
  DiscoveredSSHMetadata ssh = 3;
  DiscoveredDatabaseMetadata database = 4;
}
```
With subfields:
```
message DiscoveredSSHMetadata {
  bool agentless = 1;
}

message DiscoveredDatabase {
  string db_type = 1;
  string db_protocol = 2;
}
```

**Comment by r0mant** [comment]
@atburke Couple of suggestions:

- Instead of having separate "agentless" field, let's set the resource kind to "node.openssh" so it's consistent with how agentless nodes are currently tracked in the existing events: https://github.com/gravitational/cloud/blob/bc975da782d604f6c57c638de4dfb16be412a366/tools/prehog/lib/prehog/data.go#L235. And then we can get rid of "DiscoveredSSHMetadata".
- Instead of specific "resources discovered" event, how about we use a more generic "resource created" event and with a `resource_origin` property set to "cloud" for auto-discovered resources? This way if in future we want to track, say, how many resources are created via API, we'll be able to extend it. WDYT?

**Comment by atburke** [comment]
I'm fine with the more generic event. We already have a currently unused [`ResourceCreateEvent`](https://github.com/gravitational/teleport/blob/f6e9ca269ee3acbe6cb88aea0b96d62f567c96b8/proto/prehog/v1alpha/teleport.proto#L51-L57) that we could extend.

**Comment by r0mant** [comment]
This is completed, just need to create a Posthog dashboard.
