### ISSUE TITLE
Teleport EKS Guide

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2829]
## Description

We should have start to finish EKS guide with Teleport that glues together:

https://gravitational.com/teleport/docs/kubernetes_ssh/

It should use the terraform scripts attached, use our helm chart for k8s and then set up sample cluster role bindings. 

## More details

(Ev) Our guides should always offer two things:

1. An easy to follow explanation of how something works, so people could build their own automation using _their own tooling of choice_. **This is important**.
2. An example using our choice of tooling (like Terraform or Helm).

It's extremely important to have "implementation neutral" documentation because of two reasons:

- Some people ALWAYS develop an incorrect assumption that an external tool (like Terraform or Helm or Ansible or whatever) is _required_ to make a product work.
- Similarly, highly opinionated people (some hate Helm with a passion) automatically get turned off if a guide/manual forces them to use it.

So the rule of thumb is (I'm repeating myself):

1. Explain to people how something needs to be done using plain English.
2. Then, point at an example using tool X, while making it very clear that they can use their own tool.

Bonus point for having good comments in our `/examples` scripts, especially if they point back to the documentation, so people can go in both directions `English <-> Examples`

**Comment by klizhentas** [comment]
@webvictim @benarent 

Most of materials are here:

https://github.com/gravitational/teleport/pull/2830

**Comment by klizhentas** [comment]
I suggest to have one for Github and OSS and another with Enterprise and Okta for example

**Comment by klizhentas** [comment]
also this guide should be there too:

https://community.gravitational.com/t/how-to-share-kubernetes-groups-between-trusted-clusters/54

**Comment by benarent** [comment]
also need to add a link to @jicowan awesome post https://aws.amazon.com/blogs/opensource/authenticating-eks-github-credentials-teleport/  on setting Teleport up with EKS.

 Thanks @jicowan!

**Comment by CarpathianUA** [comment]
guys, any updates?

**Comment by benarent** [comment]
@CarpathianUA We've just been re-organising our docs on, but I've not made much process on content yet. Did you have a look at https://aws.amazon.com/blogs/opensource/authenticating-eks-github-credentials-teleport/ ? If you have any other questions, can you please open a ticket on our community forum. https://community.gravitational.com/

**Comment by CarpathianUA** [comment]
Hi @benarent ,
Thanks for an update, the article is usefull, but users would like to see structured documentation in Teleport docs as well

**Comment by russjones** [comment]
We should write a complimentary AKS guide as well.

**Comment by benarent** [comment]
This has been added to Kubernetes guide https://gravitational.com/teleport/docs/kubernetes_ssh/#aws-eks / AWS Guide.

I had AWS OpenSource blog update their link https://aws.amazon.com/blogs/opensource/authenticating-eks-github-credentials-teleport/
