### ISSUE TITLE
Teleport Server Access Lab: confusing "create a Node Join token" section

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#28345]
Expected behavior: clear understanding of what a node join token is.

Current behavior:
The user creates a join token, but then doesn't use it anywhere. Instead, the VM has a shell script with another token hardcoded. It creates confusion about what the token idea is all about.

Bug details:
- Start the Teleport Server Access Lab from https://goteleport.com/labs/
- Create the user
- Get to the "create a Node Join token" part

**Comment by rodgtr1** [comment]
This has been made clearer, merged and deployed. Closing this issue. Thank you for the feedback!
