### ISSUE TITLE
Teleport Server Access Lab: UX friction in the "view audit log" part

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#28343]
Expected behavior:

The user should be guided through the steps, without gaps in instructions

Current behavior:

There's no explanation how to access the Web UI in the "view audit log" part if the user didn't open it themselves or closed it after creating the password. The instructions should include a link to open the Web UI. And once the user opens the UI, there's a mismatch between the guidelines and the Web UI: the guide should mention that the user needs to switch to the Management section of the Web UI before proceeding.

Bug details:
- Start the Teleport Server Access Lab from https://goteleport.com/labs/
- Create the user
- Log in to Teleport and use SSH
- Look at the "view audit log" part

**Comment by rodgtr1** [comment]
Updated, merged, deployed in instruqt repo. Closing.
