### ISSUE TITLE
Users without home directory will not be able to log-in

### ISSUE THREAD

**Issue by ioannisky** [gravitational/teleport#2834]
**What happened**:
When I try to connect to a remote node I some times get the following error.
```
ERRO [NODE]      Unable to run shell command (bash): fork/exec /bin/bash: no such file or directory id:30 local:127.0.0.1:3022 login:<username> remote:xxx.xxx.xxx.xxx:58860 teleportUser:ioannis srv/sess.go:605
ERRO [NODE]      fork/exec /bin/bash: no such file or directory regular/sshserver.go:1230
```
**What you expected to happen**:
Login to the node successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Create a user with a home directory pointing to a non existing location. Try to login to that node with that user. After creating the home directory the problem goes away.

**Environment**:
- Teleport version (use `teleport version`):
Teleport v4.0.0-rc.3 git:v4.0.0-rc.3-2-g1544d40 go1.10.3
- Tsh version (use `tsh version`):
Teleport v4.0.0-rc.3 git:v4.0.0-rc.3-2-g1544d40 go1.10.3
- OS (e.g. from /etc/os-release):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by fspmarshall** [comment]
Making note here... `openssh` seems to drop you into `/` if the user's home directory does not exist, so thats probably the correct fallback to use.

**Comment by angelomellos** [comment]
Plus one on this. I just ran into this issue on a host running 4.3.2.
