### ISSUE TITLE
Confusing message after picking a wrong two-factor type

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#28351]
Expected behavior:
A message that notifies the user that the credential couldn't be fetched from a hardware key

Current behavior:
The message "error obtaining credential, please try again" is overly generic. If a user simply skims the form, fills in username and password and promptly presses Enter/Return, they may not notice that the system by default expects a hardware key to be present. In my case, it caused a couple of repeated login attempts (I thought maybe the password was wrong).

Bug details:
- Teleport version: cloud
- Recreation steps:
   - Create a user with 2-factor based on authenticator app
   - Attempt to sign in, giving a correct username and password, but leaving the "two-factor type" dropdown at its default ("Hardware Key").

**Comment by codingllama** [comment]
@bl-nero, a quick lookup shows me this is a frontend error message. Feel free to tackle the issue (and CC me if you like).
