### ISSUE TITLE
[v.13.x] /docs/pages/architecture/authentication.mdx: not sure about the diagram purpose

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#28358]
## Applies To

https://goteleport.com/docs/architecture/authentication/#short-lived-certs-for-users

## Details

The diagram in this section is captioned as "SSO exchange with short-lived certs", but it only explains (very roughly) the general concept of SSO itself, not even in the context of Teleport. It also looks like there is another diagram or screenshot missing there, since the first paragraph ends with a colon.

**Comment by zmb3** [comment]
This diagram was updated.
