### ISSUE TITLE
Database Access Instance EC2 tags propagation

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#28390]
### What

According to the docs EC2 metadata service tags sync should be supported for [SSH nodes, Applications, Databases, and Kubernetes clusters](https://goteleport.com/docs/management/guides/ec2-tags/#:~:text=When%20running%20on%20an%20AWS%20EC2%20instance%2C%20Teleport%20will%20automatically%20detect%20and%20import%20EC2%20tags%20as%20Teleport%20labels%20for%20SSH%20nodes%2C%20Applications%2C%20Databases%2C%20and%20Kubernetes%20clusters.): 
> When running on an AWS EC2 instance, Teleport will automatically detect and import EC2 tags as Teleport labels for SSH nodes, Applications, Databases, and Kubernetes clusters.
 
Where in database access flow the ec2 tags metadata sync is done only during the heartbeat call in [getServerInfo](https://github.com/gravitational/teleport/blob/f2adcda2a11a8099243cf45a0bad61ecde735a4c/lib/srv/db/server.go#L669). In the result tags from Database Server in Auth backend and Database resource in the DB Agent are out of sync. 

In the result, the RBAC rules based on not existing db resource labels are evaluated to access denied error:
 [#80](https://github.com/gravitational/customer-sensitive-requests/issues/80)

Fix labels sync done by EC2 metadata service in Database Access flow and ensure that EC2 labels sync is also applied for SSH nodes, Applications, Databases, and Kubernetes clusters access.

**Comment by gabrielcorado** [comment]
#29215 solves this issue.
