### ISSUE TITLE
Session sharing does not work in Web UI anymore

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2839]
Starting with 4.x the web UI does not offer the "join" button.

[EDIT] Also, it takes a LONG time for the completed session to show up in "sessions" tab. Makes it awkward to show demos.

**Comment by klizhentas** [comment]
This was a regression in 4.0/3.2 that Alexey has fixed, so not sure if it did not make it to 4.0?

**Comment by kontsevoy** [comment]
The latest stable release from `/download` has this issue.

**Comment by alex-kovoy** [comment]
This is  a dup of https://github.com/gravitational/teleport/issues/2801 and it has been fixed in Teleport `4.0.2`
