### ISSUE TITLE
WebSocket closes due to 'Could not decode a text frame as UTF-8'

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#284]
We still have encoding issues. It does not happen too often but from time to time I have this error. One way to reproduce it is to:

1) run midnight commander (I use it for testing :-) )
2) from there run htop
3) do F10

![image](https://cloud.githubusercontent.com/assets/7816406/13939131/69918320-efa8-11e5-9493-f402e821ae6e.png)

**Comment by klizhentas** [comment]
seems to be fixed by our base64 encoding fix
