### ISSUE TITLE
tsh login doesn’t return an error if you log into a non-existent cluster

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#2842]
**What happened**:

UX nitpick, `tsh login` doesn’t return an error if you log into a non-existent cluster:

```
~ [⎈ |fmc.lab:default] $ tsh clusters
Cluster Name Status
------------------ ------
<redacted> online
c1.chi online
abn.qa.sdd.gke online
c2.car online
c1.gke online
abn.prod.sdd.gke online
twr.qa.sdd.gke online
c1.nff.aws online
int.sdd.gke online
c1.car online
twr.prod.sdd.gke online
devops1.gke online
dies.gke online
ms.prod.sdd.gke online
<redacted> online
lab.fmc online
fi.ume.nff.aws online
demo.ume.nff.aws online
dies.nff.aws online
qa.sdd.gke online

~ [⎈ |fmc.lab:default] $ tsh login fake.cluster
> Profile URL: https://<url>:443
Logged in as: <user>
Cluster: <cluster>
Roles: *
Logins: <logins>
Valid until: 2019-05-22 18:21:10 -0400 EDT [valid for 9h44m0s]
Extensions: permit-agent-forwarding, permit-port-forwarding, permit-pty

* RBAC is only available in Teleport Enterprise
https://gravitational.com/teleport/docs/enterprise
```

**What you expected to happen**: Error saying `cluster 'fake.cluster' does not exist` or similar.

**How to reproduce it (as minimally and precisely as possible)**: `tsh login` to a cluster name that does not exist.

**Environment**:
- Teleport version (use `teleport version`): `Teleport Enterprise v4.0.2git:v4.0.2-0-gb7e0e872 go1.12.1`
- Tsh version (use `tsh version`): `Teleport v4.0.2 git:v4.0.2-0-gb7e0e872 go1.12.1`
- OS (e.g. from /etc/os-release): `Fedora 29`

**Comment by stevenGravy** [comment]
@webvictim looks like this is fixed:

```bash
tsh login nowhere
ERROR: remote cluster "nowhere" is not found
```
