### ISSUE TITLE
Reduce keep alive interval

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2845]
Starting in Teleport 4.0 we have introduced configurable keep alive messages across the board for Teleport. The default interval between keep alive messages is 15 minutes to match OpenSSH.

However, several customers have pointed out that the default timeout for an idle connect with a NLB on AWS is actually 350 seconds and since many customers run their proxies behind a NLB, reducing the default keep alive interval to something like 300 seconds would greatly improve the user experience.

**Comment by klizhentas** [comment]
let's do it in 4.1 - very small change
