### ISSUE TITLE
`tsh xxx --identity <identity-file>` fails when Proxy behind L7 LB 

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#28486]
Expected behavior:
`tsh xxx --identity <identity-file>` should succeed

Current behavior:
`tsh xxx --identity <identity-file>` fail with tls dial errors

Bug details:
- Teleport version: v13, master
- Recreation steps: Proxy behind L7 LB, export an identity, then `tsh ls --identity <identity-file> --proxy <proxy> --debug`
- Debug logs:
```
$ tsh ls --identity terraform-identity --proxy $awsrootdev:443 --debug
2023-06-29T14:58:00-04:00 INFO [CLIENT]    ALPN connection upgrade required for "teleport.root.dev.aws.stevexin.me:443": false. client/api.go:653
...
ERROR REPORT:
Original Error: *tls.CertificateVerificationError tls: failed to verify certificate: x509: certificate is valid for <redacted> not <redacted>
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/alpn.go:148 github.com/gravitational/teleport/api/client.(*ALPNDialer).DialContext
	github.com/gravitational/teleport/lib/utils/proxy/proxy.go:71 github.com/gravitational/teleport/lib/utils/proxy.directDial.DialTimeout
	github.com/gravitational/teleport/lib/utils/proxy/proxy.go:58 github.com/gravitational/teleport/lib/utils/proxy.directDial.Dial
	github.com/gravitational/teleport/lib/client/api.go:3108 github.com/gravitational/teleport/lib/client.makeProxySSHClientWithTLSWrapper
	github.com/gravitational/teleport/lib/client/api.go:3027 github.com/gravitational/teleport/lib/client.makeProxySSHClient
```

Workaround:
`TELEPORT_TLS_ROUTING_CONN_UPGRADE=true tsh ls --identity <identity-file> --proxy <proxy>` would succeed though.

**Comment by strideynet** [comment]
Do you have further information about this failure ? It looks similar to a failure we've been seeing with the Terraform provider when behind an ALB

**Comment by greedy52** [comment]
@strideynet normally `tsh` saves `tls_routing_conn_upgrade_required` value in profile.yaml (the value is determined by doing ALPN handshake test at tsh login).

For this particular case when loading from `--identity`, `tls_routing_conn_upgrade_required` is never configured. so the fix would be doing the ALPN Hanshake test here:
https://github.com/gravitational/teleport/blob/cf23101efbad671d6f65bd502f5025997e446be9/tool/tsh/common/tsh.go#L3325-L3338
I am considering moving the ALPN handshake test to `tc.Ping()`

**Comment by greedy52** [comment]
I did take a quick look at the failure Gabriel was investigating. When Terraform provider uses api/client.New "foreground" connect should tries all connect methods, it does the handshake test here automatically.
https://github.com/gravitational/teleport/blob/cf23101efbad671d6f65bd502f5025997e446be9/api/client/contextdialer.go#L356

**Comment by strideynet** [comment]
> I did take a quick look at the failure Gabriel was investigating. 

Ah, this is the one I was referring to - thank you for looking into that.

**Comment by greedy52** [comment]
For that ticket, both TLS routing dialer gives `ssh: handshake failed:` so I suspect the TLS routing part already went through correctly but SSH connect fails. Maybe we can get webapi/ping output to double check the network settings and maybe get proxy/auth log to see if any obvious ssh auth errors?
