### ISSUE TITLE
User Agent missing, while specifying forwardagent

### ISSUE THREAD

**Issue by Kenyre** [gravitational/teleport#2848]
**What happened**:
User agent is still missing after specifying forward agent

**What you expected to happen**:
To be able to ssh into our server from a windows environment

**How to reproduce it (as minimally and precisely as possible)**:
Use the tsh client on windows to login, using the yubikey as second factor authentication. Use the outputted certificate in either ssh-agent or specify the file through -i in the proxy command in the ssh config.

**Environment**:
- Teleport version (use `teleport version`): 3.2.6
- Tsh version (use `tsh version`): 3.2.6
- OS (e.g. from /etc/os-release): Windows 10

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**
I've already specified this in the last comment in my previous issue, but since it was closed and i could not reopen the issue #2782  i'll repost it here:

I've tried specifying the forwardAgent, both through my .ssh/config file using ForwardAgent yes, as well as in the command line using -A.

I have also tried specifying other identity files (tsh login seems to produce multiple files, i tried to use the file which had the same content as was shown through ssh-add -L, which was the USER-cert.pub file).

This means i have tried the following combinations of config file and command line options:

```
config:
Host HOSTNAME
Port 3022
IdentityFile C:\Users\Joeri.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub
ForwardAgent yes
ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -i C:\Users\Joeri.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub -A -p 3023 %r@PROXY_ADDRESS -s proxy:%h:%p
commandline:
ssh -vvv ubuntu@HOSTNAME

config:
Host HOSTNAME
Port 3022
IdentityFile C:\Users\Joeri.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub
ForwardAgent yes
ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -i C:\Users\Joeri.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub -p 3023 %r@PROXY_ADDRESS -s proxy:%h:%p
commandline:
ssh -vvv -A ubuntu@HOSTNAME

config:
Host HOSTNAME
Port 3022
IdentityFile C:\Users\Joeri.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub
ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -i C:\Users\Joeri.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub -p 3023 %r@PROXY_ADDRESS -s proxy:%h:%p
commandline:
ssh -vvv -A ubuntu@HOSTNAME
```

All unfortunately end in the same kind of error. Starting with ```debug3: w32_getpeername ERROR: not sock :2``` in the debug and ending with error: user agent missingsubsystem request failed on channel 0 .
I will again attach the full stacktrace of the last execution in case it might help:

```
ssh -vvv -A ubuntu@HOSTNAME
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\Users\Joeri/.ssh/config
debug1: C:\Users\Joeri/.ssh/config line 1: Applying options for HOSTNAME
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug1: Executing proxy command: exec C:\Windows\System32\OpenSSH\ssh.exe -i C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022
debug3: spawning "C:\Windows\System32\OpenSSH\ssh.exe" -i C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022
debug3: w32_getpeername ERROR: not sock :2
debug1: identity file C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub type 4
debug3: Failed to open file:C:/Users/Joeri/.tsh/keys/PROXY_ADDRESS/Joeri-cert.pub-cert error:2
debug3: Failed to open file:C:/Users/Joeri/.tsh/keys/PROXY_ADDRESS/Joeri-cert.pub-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri-cert.pub-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
error: user agent missingsubsystem request failed on channel 0
ssh_exchange_identification: Connection closed by remote host
```

**Comment by webvictim** [comment]
1) The path in your SSH config is incorrect (`C:\Users\Joeri.tsh\` - should actually be `C:\Users\Joeri\.tsh` unless you've explicitly moved the keys) but it does appear correctly in the SSH log, so I'm going to assume that it might have got mangled during the copy/paste/edit into Github?

**Comment by webvictim** [comment]
1) The path in your SSH config is incorrect (`C:\Users\Joeri.tsh\` - should actually be `C:\Users\Joeri\.tsh` unless you've explicitly moved the keys) but it does seem to appear correctly in the SSH log, so I'm going to assume that it might have got mangled during the copy/paste/edit into Github?

2) Here's the files in my `.tsh/keys` directory after logging into a cluster:
```
 Directory of C:\Users\IEUser\.tsh\keys\gus-main.gravitational.co

07/22/2019  07:00 AM    <DIR>          .
07/22/2019  07:00 AM    <DIR>          ..
07/22/2019  07:00 AM             3,859 certs.pem
07/22/2019  07:00 AM             1,675 gus@gravitational.com
07/22/2019  07:00 AM             1,522 gus@gravitational.com-cert.pub
07/22/2019  07:00 AM             1,330 gus@gravitational.com-x509.pem
07/22/2019  07:00 AM               381 gus@gravitational.com.pub
```

The key file that needs to be used in this instance is `gus@gravitational.com`. The `.pub` files are the associated public keys for the cert - you need to be using the private key version. Bearing this in mind, your `.ssh/config` looks incorrect.

Can you try changing your SSH config to use the filename on its own (which I would presume to be `C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri`?) and see whether this allows you to log into the cluster successfully?

I understand that your issue is ultimately with SSH agent forwarding - I'm just trying to work through the issues one at a time. Once you can log into the cluster successfully, we can figure out what else might be going on.

**Comment by Kenyre** [comment]
1. Indeed your assumption was correct, something has gone wrong in copy pasting, my keys are indeed located in `C:\Users\Joeri\.tsh`.

2. I started out with this file, started using other files since it did not work. I'll switch back to the private key file Joeri. Unfortunately this does not  allow me to ssh into our cluster.

My configuration is now as follows:
```
Host HOSTNAME
  Port 3022
  IdentityFile C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri
  ForwardAgent yes
  ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -i C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri -p 3023 %r@PROXY_ADDRESS -s proxy:%h:%p
```

These are the outputs of my commandline:
```
.\tsh.exe status
> Profile URL:  https://PROXY_ADDRESS:3080
  Logged in as: Joeri
  Cluster:      PROXY_ADDRESS
  Roles:        Joeri*
  Logins:       ubuntu, ec2-user
  Valid until:  2019-07-23 20:26:26 +0200 CEST [valid for 11h59m0s]
  Extensions:   permit-agent-forwarding, permit-port-forwarding, permit-pty


* RBAC is only available in Teleport Enterprise
  https://gravitational.com/teleport/docs/enterprise
```

```
ssh -vvv ubuntu@HOSTNAME (as well as ssh -A -vvv ubuntu@HOSTNAME)
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\Joeri/.ssh/config
debug1: C:\\Users\\Joeri/.ssh/config line 1: Applying options for HOSTNAME
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug1: Executing proxy command: exec C:\\Windows\\System32\\OpenSSH\\ssh.exe -i C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022
debug3: spawning "C:\\Windows\\System32\\OpenSSH\\ssh.exe" -i C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022
debug3: w32_getpeername ERROR: not sock :2
debug1: identity file C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri type 0
debug3: Failed to open file:C:/Users/Joeri/.tsh/keys/PROXY_ADDRESS/Joeri-cert error:2
debug1: identity file C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri-cert type 4
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
error: user agent missingsubsystem request failed on channel 0
ssh_exchange_identification: Connection closed by remote host
```

**Comment by webvictim** [comment]
1) Are you running the `ssh-agent` as a Windows service? If so, can you please post the output of `sc query ssh-agent`?

2) The `debug1: Executing proxy command: exec C:\\Windows\\System32\\OpenSSH\\ssh.exe -i C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022` - presumably the `hostname` part is the real hostname that you've redacted out, rather than actually just the word `hostname`?

3) The `error: user agent missing` is coming from Teleport but it's happening before the remote software version is even shown, which leads me to believe there's a pretty fundamental issue with the connection. Is this Windows machine going through any kind of proxy server which could interfere with your outbound connectivity?

I cannot reproduce this issue at all unfortunately.

**Comment by webvictim** [comment]
Actually, I just tried against a cluster running Teleport 3.2.6 and it does seem that I get an error saying `subsystem request failed on channel 0` and I'm unable to log in with a config I'd expect to work. When I try logging into a cluster running Teleport 4.0.2, it works fine.

I'll look into what changed between 3.2.6 and 4.0.2 and see what could be causing this. In the meantime, if you want to upgrade your Teleport service to version 4.0.2 it might solve this issue.

**Comment by Kenyre** [comment]
1. I am using OpenSSH included in windows 10, so i recon that means i am using the ssh-agent as a  windows service. This was the result of running `sc query ssh-agent`:
```
sc.exe query ssh-agent

SERVICE_NAME: ssh-agent
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

2. Indeed hostname is the redacted out part. Our hostname is however specified in all capital letters. I tried to specify HOSTNAME wherever the hostname was printed in capital letters, and hostname whenever it was printed in lowercase. (i don't know if that matters, i recon all capital letter hostnames should be possible?)

3. It should not be using a proxy. I am directly connected to our router over LAN cable. Our network does not utilize any VPN or other obstructing software which i can think of. So this should not be the problem.

4. I'll try updating to version 4.0.2. Our backend needs to be updated for this as well. I do not have access to the backend myself. So i'll have to wait for our admin to download the update. I'll post back here once i have results.

**Comment by webvictim** [comment]
The case of hostnames shouldn't matter, but lowercase is preferred for DNS in general.

**Comment by Kenyre** [comment]
Hi there, we've updated both our backend and the tsh client to version 4.0.3 (the most recent version). It did however not help with being able to ssh into our server. The error output however did change a bit.

One more thing i forgot to mention untill now:
I need to run powershell as an administrator for `tsh.exe status` to show the logged in profile. When i run the powershell without admin privileges, `tsh.exe status` will show `Not logged in.` (i don't think this is the problem, but it might help in debugging the problem).

I will post the different outputs of commands, since they are now slightly different
```
.\tsh.exe version
Teleport v4.0.3 git:v4.0.3-0-g69c4868b go1.12.1
```

```
.\tsh.exe login --proxy=PROXY_ADDRESS --user=Joeri (as well as tsh.exe status afterwards.)
Enter password for Teleport user Joeri:
Please press the button on your U2F key
> Profile URL:  https://PROXY_ADDRESS:3080
  Logged in as: Joeri
  Cluster:      PROXY_ADDRESS
  Roles:        Joeri*
  Logins:       ubuntu, ec2-user
  Valid until:  2019-08-02 21:04:01 +0200 CEST [valid for 12h0m0s]
  Extensions:   permit-agent-forwarding, permit-port-forwarding, permit-pty


* RBAC is only available in Teleport Enterprise
  https://gravitational.com/teleport/docs/enterprise
```

This is still the default error log i get most of the time.
```
ssh -vvv ubuntu@HOSTNAME
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\Joeri/.ssh/config
debug1: C:\\Users\\Joeri/.ssh/config line 1: Applying options for HOSTNAME
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug1: Executing proxy command: exec C:\\Windows\\System32\\OpenSSH\\ssh.exe -i C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADRESS\\Joeri -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022
debug3: spawning "C:\\Windows\\System32\\OpenSSH\\ssh.exe" -i C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri -p 3023 ubuntu@PROXY_ADRESS -s proxy:hostname:3022
debug3: w32_getpeername ERROR: not sock :2
debug1: identity file C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri type 0
debug3: Failed to open file:C:/Users/Joeri/.tsh/keys/PROXY_ADDRESS/Joeri-cert error:2
debug1: identity file C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri-cert type 4
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
error: user agent missingsubsystem request failed on channel 0
ssh_exchange_identification: Connection closed by remote host
```

Once i specify the following ssh config (difference being the -A flag), i however get another error (although i think it might be an error which triggers earlier than the real problem).
```
Host HOSTNAME
  Port 3022
  IdentityFile C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri
  ForwardAgent yes
  ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -A -i C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri -p 3023 %r@PROXY_ADDRESS -s proxy:%h:%p
```
Which will result in the following output:
```
ssh -vvv ubuntu@HOSTNAME
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\Joeri/.ssh/config
debug1: C:\\Users\\Joeri/.ssh/config line 1: Applying options for HOSTNAME
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug1: Executing proxy command: exec C:\\Windows\\System32\\OpenSSH\\ssh.exe -A -i C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022
debug3: spawning "C:\\Windows\\System32\\OpenSSH\\ssh.exe" -A -i C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri -p 3023 ubuntu@PROXY_ADDRESS -s proxy:hostname:3022
debug3: w32_getpeername ERROR: not sock :2
debug1: identity file C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri type 0
debug3: Failed to open file:C:/Users/Joeri/.tsh/keys/PROXY_ADDRESS/Joeri-cert error:2
debug1: identity file C:\\Users\\Joeri\\.tsh\\keys\\PROXY_ADDRESS\\Joeri-cert type 4
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
error: dial tcp: lookup hostname: Temporary failure in name resolutionsubsystem request failed on channel 0
ssh_exchange_identification: Connection closed by remote host
```

**Comment by webvictim** [comment]
Firstly, I'm aware of the issue with `tsh.exe` commands showing `Not logged in` - I raised https://github.com/gravitational/teleport/issues/2878 previously. I've added your experiences to it though and hopefully we can use this extra information to figure out what the problem is.

With regard to your SSH problem:

`error: dial tcp: lookup hostname: Temporary failure in name resolution` seems to be the issue for me. Presumably `hostname` here is the `HOSTNAME` that you're providing on the command line (as in `ssh -vvv ubuntu@HOSTNAME`)?

This would indicate to me that you're using proxy recording mode (as I would expect when using OpenSSH clients) and your proxy server's DNS resolver can't look up whatever the `hostname` is that you're trying to log into. Can you try `ssh -vvv ubuntu@1.2.3.4` (replacing 1.2.3.4 with the actual IP that corresponds to `HOSTNAME`) and see whether that works?

**Comment by Kenyre** [comment]
Yes, i've finally managed to login to our server, thanks to using the direct ip.
The next problem however immediately arises. On logging in to the cluster i have to add the RSA key fingerprint to my list of known hosts. However, on the second attempt to log in the fingerprint has changed and i get the following message:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:Luy34PYzSalcdAJowJGZhv7QlHrBnavcYLDyhXawG0E.
Please contact your system administrator.
Add correct host key in C:\\Users\\Joeri/.ssh/known_hosts to get rid of this message.
Offending RSA key in C:\\Users\\Joeri/.ssh/known_hosts:43
RSA host key for [IP_ADDRESS]:3022 has changed and you have requested strict checking.
Host key verification failed.
```

Now i guess this is due to the internal functioning of teleport (dynamic rsa_keys i guess?). But it would be preferable to not have to manually adjust my known_hosts file on each login.
Anyhow, thanks for the support! At least it is now possible to access our servers without the web interface.

P.S.
i've indeed redacted out the hostname before, as i have done now with the IP_ADDRESS.

**Comment by webvictim** [comment]
The host key should always be the same with Teleport - it doesn't change dynamically. It should only change following a deliberate rotation of the keys. Do you know whether your Teleport cluster uses more than one proxy server behind a load balancer? If so, that might explain some of this.

As you've said, the easiest way to prevent this from happening is to disable strict host key checking, but this is **only** advisable for something like an internal development environment where you anticipate that the VM may be re-imaged often and the host key would therefore change. It would definitely be a potential security risk to do something like this for any production server.

You can set this up automatically for a particular IP address in your `C:\Users\Joeri\.ssh\config` like so:

```
Host IP.ADDRESS.GOES.HERE
    StrictHostKeyChecking no
    UserKnownHostsFile NUL
```

I'm going to close this issue now as we've solved the underlying problem - DNS resolution for the target hostname wasn't working on the Teleport proxy.

**Comment by Kenyre** [comment]
I've made a mistake in my previous comment. This error message is not displayed on logging into the cluster, but on loggin in to our server. Everything now functions, both ssh and scp. But i keep getting the man in the middle attack message. Since i sometimes have to login to production servers, it is not preferable to use `StrictHostKeyChecking no`. I do think it might be related to me using IP adresses now, since the default error message now is `Certificate invalid: name is not a listed principal`. I have seen several issues with this same error message being related to ip addresses not being in the principals (although some are older and should have been fixed).

What happens:
The fingerprint of the RSA key is different on every login to the server.

Error log:
```
debug3: hostkeys_foreach: reading file "C:\\Users\\Joeri/.ssh/known_hosts"
debug3: record_hostkey: found ca key type RSA in file C:\\Users\\Joeri/.ssh/known_hosts:1
debug3: record_hostkey: found key type RSA in file C:\\Users\\Joeri/.ssh/known_hosts:8
debug3: load_hostkeys: loaded 2 keys from [hostname]:3022
debug3: Failed to open file:C:/Users/Joeri/.ssh/known_hosts2 error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug1: Host '[hostname]:3022' is known and matches the RSA-CERT host certificate.
debug1: Found CA key in C:\\Users\\Joeri/.ssh/known_hosts:1
key_cert_check_authority: invalid certificate
Certificate invalid: name is not a listed principal
debug1: No matching CA found. Retry with plain key
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:c/eJ/6bLgG1nn6OIMQ5h7InHnNMHXFVUw6duhsbWTOk.
Please contact your system administrator.
Add correct host key in C:\\Users\\Joeri/.ssh/known_hosts to get rid of this message.
Offending RSA key in C:\\Users\\Joeri/.ssh/known_hosts:8
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
Agent forwarding is disabled to avoid man-in-the-middle attacks.
```
(i've truncated parts of the debug log in the beginning and end, let me know if you need more, thought this was the only helpfull section). I've tried the solution mentioned in  issue #2843. But this did not make a difference.

My certificate:
```
@cert-authority * ssh-rsa AAAA.....TRUNCATED...AAAA type=host
```
our cluster is called main (the default cluster i think). And all our servers are within this cluster. I've tried `*.main` as well, but this also did not make a difference.

**Comment by webvictim** [comment]
@Kenyre I'm really sorry it's taken so long to reply - this one fell through the cracks a bit because the issue was closed. My apologies.

I think you can fix this error by removing all old keys referencing this host from `C:\Users\Joeri\.ssh\known_hosts` - this error is mentioning line 8, for example. If you have other entries for the proxy or its IPs then you should also tidy up and remove these too. If there are multiple entries for the same proxy host, SSH will get confused and ignore them which leads to this error.

After that, you should make sure that you have the line with `cert-authority` added to your `known_hosts` as you mentioned before - I think that setting the host to `*` may not work, however, because it's too broad for SSH to match against. You should use whatever the full DNS name of your Teleport proxy is when you connect to it - so `@cert-authority PROXY_ADDRESS ssh-rsa AAAAA....` in your case.

Please let me know how you get on with this, or if you're not longer having the issue. Thanks!

**Comment by Kenyre** [comment]
@webvictim Hi there,

I've backed up the known_hosts file and created a new one containing only the `cert-authority`. I've replaced the wildcard * with our PROXY_ADDRESS. However on my first login the RSA fingerprint is added, while the second login still shows the same man in the middle warning. For reference, my hosts in .ssh\config have the following format:
```
Host HOSTNAME
  Port 3022
  IdentityFile C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri
  ForwardAgent yes
  StrictHostKeyChecking no
  ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -A -i C:\Users\Joeri\.tsh\keys\PROXY_ADDRESS\Joeri -p 3023 %r@PROXY_ADDRESS -s proxy:IP_OF_HOST:%p
```
where PROXY_ADDRESS is in the format prefix.endpoint.com
and HOSTNAME is an all caps name for our host
and IP_OF_HOST is the ip address of our host (i believe hostname did not work at this position)

My known hosts looks as follows (after the first login):
```
@cert-authority PROXY_ADDRESS ssh-rsa AAAA.......AAAA type=host
[hostname]:3022 ssh-rsa AAAA....AAAA
```
here hostname is all lowercase letters of our hostname defined in config.

**Comment by webvictim** [comment]
@Kenyre OK, understood. Couple more things to try:

1) Please change the `PROXY_ADDRESS` in the `known_hosts` file to `[hostname]:3022` (just edit that part, leave the `@cert-authority` etc) and also remove the automatically added `[hostname]:3022` entry, so there's just one line in the file. Then, try logging into the node again.

2) If this doesn't work, please post the output of `ssh -vvv` for both successful and unsuccessful logins (i.e. with and without `StrictHostKeyChecking no`)

Incidentally - I understand why you're redacting the proxy address for posting the logs here on Github, but it would be very useful for me to see the logs without any editing at all just in case there's something seemingly obvious that we're missing here. If you could send those logs to us via email (support [at] gravitational.com) or upload them via Zendesk that would be very helpful.

Thanks!

**Comment by Kenyre** [comment]
Hi there,

I've tried what you specified, but still no luck. I have sent the requested logs to support@gravitational.com . The output was generated starting with a known_hosts containing only the cert authority in which i replaced the earlier wildcard *, and later PROXY_ADDRESS, with [hostname]:3022.

 Thanks for looking into this, let me know if you need any more information

**Comment by webvictim** [comment]
We got the logs. I've responded via email/Zendesk with a potential solution.

**Comment by Kenyre** [comment]
I've responded over email with further information, the solution did unfortunately not work.

**Comment by webvictim** [comment]
This issue has been resolved now.

As IP addresses were being used to connect to the node in this case, the fix was to modify the SSH `known_hosts` file to point the `cert-authority` line to the node's IP (`1.2.3.4` in this example).

Steps:

1) Get the `cert-authority` by running this command on the Teleport auth server:
```
$ tctl auth export --type=host
@cert-authority *.example.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdMIGhbl66GR4l/Uliwjqv8QVNVp5C7eFHsOZs3VMDPxiJnbrsYjJi2hX0gavpOM86UJN60j20URl50YRRdFWBk6zZU3SBPmof+CCsHqUOFOGVRLJEnSEra6+D2lpwrAbBTGLb8e7uc5ZCfLKjqs1b2yyXd7yOHgM2v7yRG/ij8WyZ56emb5IaE8dsOSbev8QPTQIc7MUqsEIvrBsIyrUXFZQ4YflsRKPytgdOUlqRihLDrM+RUM+KB5ZBlehT7NfrwSjflxyZnukgX0nh1WIEpKtRVFJAixehK7AJTnySpJn/xM861se/L4E+tMpAhjGfuF/hXUqeYE0+if4BrCMP type=host
```

2) Add the `cert-authority` to your `known_hosts` file, changing the `*.example.com` to the IP of the node being connected to.
```
@cert-authority 1.2.3.4 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdMIGhbl66GR4l/Uliwjqv8QVNVp5C7eFHsOZs3VMDPxiJnbrsYjJi2hX0gavpOM86UJN60j20URl50YRRdFWBk6zZU3SBPmof+CCsHqUOFOGVRLJEnSEra6+D2lpwrAbBTGLb8e7uc5ZCfLKjqs1b2yyXd7yOHgM2v7yRG/ij8WyZ56emb5IaE8dsOSbev8QPTQIc7MUqsEIvrBsIyrUXFZQ4YflsRKPytgdOUlqRihLDrM+RUM+KB5ZBlehT7NfrwSjflxyZnukgX0nh1WIEpKtRVFJAixehK7AJTnySpJn/xM861se/L4E+tMpAhjGfuF/hXUqeYE0+if4BrCMP type=host
```

3) Use OpenSSH to connect to and disconnct from the host several times and observe that no `WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!` messages are generated.
