### ISSUE TITLE
gke:autopilot cluster Teleport

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#28506]
```
Kubernetes Cluster is registered in Teleport.
User-associated roles define valid Kubernetes principals.
Unknown error. groups "system:masters" is forbidden: User "system:serviceaccount:teleport:teleport-agent" cannot impersonate resource "groups" in API group "" at the cluster scope: GKE Warden authz [denied by user-impersonation-limitation]: impersonating system identities are not allowed
```

Teleport 13.1
GKE autopilot

```
sasha@Alexanders-MacBook-Pro ~ % kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.8-gke.1000", GitCommit:"4ac1389d4c3eefaabbd9fa31782fcbfd72e6e6e6", GitTreeState:"clean", BuildDate:"2023-03-30T14:01:58Z", GoVersion:"go1.19.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

EDIT: I understand it's intentional move by Autopilot. May we then fix this by suggesting `edit` and `view` built-in K8s presets by default in the wizard?

EDIT 2: I've changed to `edit` `admin` `view` and getting this now:

```
Error from server (Forbidden): pods is forbidden: User "sasha" cannot list resource "pods" in API group "" in the namespace "default"
```

From this discussion it works, but you can't use system roles or admin roles:

https://github.com/gravitational/teleport/discussions/11959

EDIT 3: I've tried creating a custom role, and still get access denied. It seems like something is missing.

**Comment by klizhentas** [comment]
Response from @tigrato 

I have tested GKE in the past (autopilot and normal) and it works.
GKE has a limitation that forbids Teleport from impersonating the only Kubernetes group with admin priviledges: system:masters
This is a problem for GKE because most users just grant system:masters to their users given that's widely available for all k8s cloud offers except GKE.
K8S ships with predefined cluster wide roles editor, admin and  view but those roles are not linked to any default group by a ClusterRoleBinding . Check [here](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles)
 For Teleport to work, you must create a ClusterRoleBinding that links the cluster-admin or admin  ClusterRole  to a custom Kubernetes group eg.:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sasha-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: sasha-admin
```

And finally, you assign your user with kubernetes_group= [sasha-admin]
I think you missed the last part because the default ClusterRoles admin, edit, view aren't default assigned to any group.

**Comment by klizhentas** [comment]
My response:  thanks, but this nuance creates a UX wall I can't climb, and I'm afraid first time users can't either

**Comment by klizhentas** [comment]
Here is a related issue:

https://github.com/gravitational/teleport/issues/28276

@r0mant can I ask you to review possible improvements to our wizard to better guide first time users of teleport. I'm afraid the state today is leading first time users down the path filled with papercuts

**Comment by r0mant** [comment]
I have discussed this with @tigrato and we're going to make the following updates to our Discover wizard:

- When enrolling a GKE cluster, ask the user to enter the name of a Kubernetes group they want to use.
- Automatically add this group to their traits.
- Pass the group name and role name (cluster-admin for GKE) as Helm chart values so we can create the binding automatically.
- Update the "Setup Access" screen copy to better explain what Kubernetes groups/users are.

The success criteria is to make sure access works without any extra configuratioon after going through the Kubernetes Discover GKE wizard.
