### ISSUE TITLE
Add ability to supply access request TTLs in the web UI

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#28513]
### What would you like Teleport to do?

Access Request TTLs were implemented in https://github.com/gravitational/teleport/pull/17453 but the web ui interface was not updated to allow for this.

### What problem does this solve?

Users who do access requests in the web UI should be able to specify the request TTL.

### If a workaround exists, please include it.

switch to a CLI workflow, but this is not ideal for end-users that are not comfortable with the CLI.

**Comment by programmerq** [comment]
It might be more appropriate to create a separate issue, but a way to set the request ttl at the role level so users don't need to explicitly specify it in the first place, that'd be nice. Something like:

```yaml
  allow:
    request:
      roles:
        - 'db'
      ttl: 5h
```

**Comment by zmb3** [comment]
This is covered in #25267
