### ISSUE TITLE
On upgrade, Teleport overwrites teleport.service and loses any custom parameters passed in ExecStart line

### ISSUE THREAD

**Issue by gord-lyr** [gravitational/teleport#28515]
Upgrading the version of Teleport resets the teleport.service ExecStart parameters to "/usr/local/bin/teleport start --pid-file=/run/teleport.pid", which removed the --skip-version-check we have in place. This is to ensure that if someone does an "apt upgrade" and upgrades teleport to a mixed version we don't lose access (e.g. server is 12.4.10, but an upgrade will set it to 13.1.5)

What would you like Teleport to do?
Retain parameters configured in teleport.service on upgrade. 

What problem does this solve?
Custom service parameters will persist during upgrades

If a workaround exists, please include it.
Every time I upgrade the service I have to validate the "--skip-version-check" is added, which defeats the purpose of having this parameter

**Comment by programmerq** [comment]
Systemd has provisions to override vendor settings.

It is typical to use an override file.

You can create /etc/systemd/system/teleport.service.d/override.conf and only put the new ExecStart directive in the `[Service]` section. As a shortcut, the `systemctl edit teleport.service` command will create the directory and open an editor with that file already open.

source: https://man7.org/linux/man-pages/man5/systemd.unit.5.html#EXAMPLES - example 2

Here's what a typical override file would look like:

```desktop
[Service]
ExecStart=/usr/local/bin/teleport start --pid-file=/run/teleport.pid --skip-version-check
```

**Comment by gord-lyr** [comment]
hmmm. Using either method of adding the ExecStart option (whether /etc/systemd/system/teleport.service.d/local.conf or /etc/systemd/teleport.service.d/teleport.service) I get the same error message from systemd:

teleport.service: Service has more than on ExecStart= setting, which is only allow for Type=oneshot services. Refusing.

If found that first zeroing the ExecStart, then specifying it in the override works though (weird):
[Service]
ExecStart=
ExecStart=/usr/local/bin/teleport start --pid-file=/run/teleport.pid --skip-version-check

Thanks for pointing me in the right direction!!
