### ISSUE TITLE
Add an RBAC control to allow users to view/replay only their own session logs

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#2852]
[submitted on behalf of a customer]

**What happened**: The switch for whether or not users can view session logs and access replays or not is binary - users can either see and replay all session logs, or see and replay none of them.

**What you expected to happen**: To be able to optionally specify via RBAC that users can view and replay their own session logs, but no others.

**How to reproduce it (as minimally and precisely as possible)**: Log into a Teleport cluster with a role granting `session: list` and `session: read` permission, observe all logs. Remove privileges and observe no logs.

**Environment**:
- Teleport version (use `teleport version`): `Teleport Enterprise v4.0.2git:v4.0.2-0-gb7e0e872 go1.12.1`
- Tsh version (use `tsh version`): `Teleport v4.0.2 git:v4.0.2-0-gb7e0e872 go1.12.1`
- OS (e.g. from /etc/os-release): `Fedora 29`

**Browser environment**

- Browser Version (for UI-related issues): `Google Chrome version 75.0.3770.100 (Official Build) (64-bit)`

**Comment by stevenGravy** [comment]
This has been implemented with https://goteleport.com/docs/access-controls/reference/#rbac-for-sessions. Close this @webvictim ?
