### ISSUE TITLE
Kubernetes groups not included in x509 certificates

### ISSUE THREAD

**Issue by connesc** [gravitational/teleport#2860]
**What happened**:
I cannot access a remote Kubernetes cluster through a trusted cluster relationship.

My user has the following trait configured in the main Teleport cluster:

```
kubernetes_groups: ['system:masters']
```

On the remote cluster, Kubernetes groups are forwarded like that in the default `admin` role:

```
kubernetes_groups: ['{{internal.kubernetes_groups}}']
```

However, when I log into the remote cluster and attempt to use `kubectl`, I get 403 (Forbidden) errors. Looking at logs reveals that my user doesn't get any Kubernetes group in the remote cluster (see below).

According to #2489, the x509 certificate stored in `~/.kube/config` should contain the Kubernetes groups, but none is present:

```
Subject: L=root, L=ubuntu, O=admin, O=default-implicit-role, CN=connesc
```

I guess this is the root of the problem.

**What you expected to happen**:

As described in #2489, I would expect the `system:masters` group to be forwarded from the master cluster to the remote cluster, so that `kubectl` can work properly.

**How to reproduce it**:

1. Create a pair of trusted clusters with community edition v4.0.2.
2. On the main cluster, create a user with the `system:masters` Kubernetes group.
3. Setup Kubernetes access on the remote cluster.
4. Login with the user created on the main cluster, and attempt to access Kubernetes through the remote cluster.

**Environment**:
- Teleport version: `Teleport v4.0.2 git:v4.0.2-0-gb7e0e872 go1.12.1`
- Tsh version: `Teleport v4.0.2 git:v4.0.2-0-gb7e0e872 go1.12.1`
- OS: Ubuntu 18.04.2 LTS

**Relevant Debug Logs If Applicable**

From the remote cluster:

```
Jul 15 15:22:18 ip-10-16-13-61 teleport[3270]: DEBU [AUTH]      Mapped roles [admin default-implicit-role] of remote user "connesc" to local roles [admin] and traits map[kubernetes_groups:[] logins:[root ubuntu]]. auth/permissions.go:151
Jul 15 15:22:18 ip-10-16-13-61 teleport[3270]: WARN [PROXY:KUB] this user cannot request kubernetes access, has no assigned groups proxy/forwarder.go:320
```

When attempting to use `kubectl`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Error from server (Forbidden): unknown
```

**Comment by awly** [comment]
I can no longer reproduce this on the latest version of Teleport.
Please reopen if you still experience this issue.
