### ISSUE TITLE
Machine ID: BitBucket Pipelines Delegated Joining

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#28601]
Like we support CircleCI, GitLab CI and GitHub Actions, we should consider adding support for BitBucket Pipelines as they now support issuing OIDC tokens to Pipeline runs.

https://support.atlassian.com/bitbucket-cloud/docs/integrate-pipelines-with-resource-servers-using-oidc/

**OIDC IDToken Payload**

![image](https://github.com/gravitational/teleport/assets/16336790/2d1df1e5-3d14-49ab-ae46-7225898ffa89)

**Comment by strideynet** [comment]
User expressed interest in using this as part of a deployment pipeline to connect to production machines using SSH. Currently use static credentials.

**Comment by strideynet** [comment]
> Support for BitBucket would be great.. Any time line on this?

Hey @andrewbks - thanks for expressing interest. We've not yet formerly scheduled this but I'd like to address it in the next few months.

**Comment by revawiki** [comment]
+1 on this, i think its kinda sad bitbucket haven't got the same love as the others.

**Comment by giriparus** [comment]
Is there an update on this? Having a hard time configuring automated deployments on bitbucket using teleport. 
Static tokens also do not have a join method which is blocking me from using them to join a cluster on bitbucket. 

It feels like unless there is an integration, it is impossible to configure MachineID for automation which is counter intuitive but an automation that requires a user to create ephemeral tokens is defeating the purpose.

Hence at least for short lived ( oneshot ) connections, there is no real way to configure it that I could figure out.

**Comment by strideynet** [comment]
Unfortunately we've still not been able to schedule this due to other high priority items. It remains one of our higher priority items, and we're also planning to ship better support for static tokens to support environments where we don't have a join method.

**Comment by giriparus** [comment]
Thank you for your response @strideynet! Will be eagerly waiting for either of the two to roll out soon.
