### ISSUE TITLE
Slack integration should have more robust role channel mappings

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#28620]
### What would you like Teleport to do?

In the self-hosted plugin, it is quite flexible in its ability to configure which slack channels or users should get notified. The built-in integration of this plugin should have similar functionality.

### What problem does this solve?

Currently, the integration appears to only support a single catch-all channel name: 
![image](https://github.com/gravitational/teleport/assets/37278/dcc1dfc1-96e3-48b1-abce-bfb2b7cd0313)

### If a workaround exists, please include it.

n/a

**Comment by zmb3** [comment]
@r0mant is this resolved by notification routing rules?

**Comment by r0mant** [comment]
Yeah I think we can close this now.
