### ISSUE TITLE
PAM integration for non-local users

### ISSUE THREAD

**Issue by jkendzorra** [gravitational/teleport#2863]
**What happened**:
Tried using PAM modules like `pam_script.so` for users that do not (yet) have a local account, got error message saying the node `does not have OS user`.

**What you expected to happen**:
PAM is called even when there is no local user available.

**Solution**:
Have a PAM modules that can automatically users do that for you, but they don't work at the moment.

**How to reproduce it (as minimally and precisely as possible)**:
- enable PAM integration
- use non-existent user to login to a Teleport node

**Environment**:
- Teleport version (use `teleport version`): Teleport Enterprise v4.0.0git:v4.0.0-0-gc7f55ac3 go1.12.1
- Tsh version (use `tsh version`):  Teleport v4.0.0 git:v4.0.0-0-gc7f55ac3 go1.12.1
- OS (e.g. from /etc/os-release): Ubuntu 16.04

**Comment by benarent** [comment]
Thanks for reporting this @jkendzorra, I wanted to let you know that we've reviewed this and I've placed it into an accelerated milestone. After reviewing with a dev lead, we expect this to take less than a week, and while we don't have someone immediately working on it. It'll make its way into 4.2 or 4.3.

**Comment by webvictim** [comment]
Another request for this bug fix.
