### ISSUE TITLE
Builds are failing with `Failed to parse PKCS#12 file: windows-signing-cert.pfx (Wrong password?)`

### ISSUE THREAD

**Issue by fheinecke** [gravitational/teleport#28722]
Windows builds are failing again due to something with PFX signing. Example build [here](https://drone.platform.teleport.sh/gravitational/teleport/25893/21/4). Not sure what is going on but this issue has been causing (or contributing to) failing master builds for a few weeks now.

**Comment by r0mant** [comment]
@tcsc Can we close this now?
