### ISSUE TITLE
Use Github-hosted Apple Silicon runners for macOS workflows

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#28725]
GHA team enrolled us into Github-hosted Apple Silicon runners beta. Use `macos-13-xl-arm64` and `macos-latest-xl-arm64` (preferred) "runs-on" selectors.

@camscale How much work is it to switch our macOS workflows to these runners esp. w/r/t universal builds? Github team says the performance gain is 40-50% so if it's just a matter of switching up the runner and/or making a minor change to the universal build, might be a cheap way to speed up the builds and save money.

**Comment by camscale** [comment]
The change was not quite as simple as changing the `runs-on` field in the workflow. It looks like the arm64 runners erroneously have the `$HOME/.config` and `$HOME/.cache` directories owned by root and not the `runner` user, causing build errors when node tries to create `~/.cache/node`.

An early step of:
```
     - name: Fix home dir perms
       run: sudo chown -R $(id -u):$(id -g) $HOME/.cache $HOME/.config
```

fixes it. @reedloden has raised https://support.github.com/ticket/enterprise/9266/2238925 with GitHub support for this (I can't see the ticket - not sure if it mentions `.config` as I discovered that one too after pointing out the problem with `.cache`).

We can wait for GitHub to fix the runner image, or we can add that step to the top of any jobs that want to use the new runners. Perhaps we'll see how responsive GitHub are. In parallel I could add that to the release workflows to see how much faster these runners are.

**Comment by camscale** [comment]
The architecture-specific parts of the release build should fully specify the architecture with no dependency on the host architecture, so in theory it should be as simple as updating the runner to the new one (and adding that step if still needed) and it should still "just work". :crossed_fingers:

**Comment by camscale** [comment]
At the moment it fails to build. It looks like the ARM64 runners do not have `/usr/local/bin/pkg-config` installed.
A good run says: `Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")`
A bad run says: `Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`

The old runners were macos 12. The ARM64 runners are macos 13. Looking at what is included in each, it looks like pkg-config has been removed from the runner image for macos 13 :disappointed:
13: https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
12: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

**Comment by reedloden** [comment]
It's coming back very very soon.

https://github.com/actions/runner-images/issues/7632

https://github.com/actions/runner-images/pull/7719

They say they do weekly updates, but it's been two weeks since that merged. I'll open a support ticket.

In the interim, you could do `brew install pkg-config`.

**Comment by camscale** [comment]
@r0mant https://github.com/gravitational/teleport/pull/28741 should be cleaned up and merged. I'll push another commit that reverts the path setting which I think was just for testing and merge it. Not my PR so I didn't merge it.

**Comment by camscale** [comment]
According to the [readme](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md), the runner image is still from early June - the updates that fix the two issues we had have still not been released. We could leave this open until it is released and we remove the workarounds from the workflows, or we can just close it now as done. I'll leave that up to you @r0mant

**Comment by r0mant** [comment]
Let's just close it.
