### ISSUE TITLE
Implement database access product metrics and dashboard

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#28743]
Database Access currently lacks any product metrics that would allow us to answer questions, for example, like "what is the most popular protocol in the Cloud?".

Let's start by extending our existing [tp.session.start.v2](https://github.com/gravitational/cloud/blob/b66d875322f2531156c124c22968337fb681699e/tools/prehog/lib/prehog/data.go#L31) event to include more database information so we can build breakdowns in Posthog to better understand the usage. 

Success criteria:

- [ ] The session start event includes database type information. Keep in mind that just including the database protocol is not enough as we would also like to differentiate between e.g. self-hosted Postgres and RDS/CloudSQL/etc. So we should rather report the database type: https://github.com/gravitational/teleport/blob/master/api/types/database.go#L516.
- [ ] We have a new "Teleport Database Access" dashboard in Posthog that includes an insight with a breakdown of database usage.

**Comment by greedy52** [comment]
the "origin" might also be an interesting metric to collect.

**Comment by zmb3** [comment]
This was completed.
