### ISSUE TITLE
`TestServer_Authenticate_headless/OK_approved` flakiness

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#28756]
## Failure

Related issues:

* #23505

#### Link(s) to logs

- on branch/v12 https://github.com/gravitational/teleport/actions/runs/5473334870/jobs/9966666463#step:6:1312

#### Relevant snippet

```
    auth_login_test.go:877: 
        	Error Trace:	/__w/teleport/teleport/lib/auth/auth_login_test.go:877
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestServer_Authenticate_headless/OK_approved
```

**Comment by r0mant** [comment]
Two more failures within the past week:

https://github.com/gravitational/teleport/actions/runs/5610767704/job/15200966997
https://github.com/gravitational/teleport/actions/runs/5558653363/job/15058576821

@Joerger Can you take a look?
