### ISSUE TITLE
Reconsider the term "agentless mode"

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#28775]
## Applies To

```
$ grep -Rli "agentless" docs/pages
docs/pages/includes/edition-comparison.mdx
docs/pages/architecture/agent-update-management.mdx
docs/pages/faq.mdx
```

## Details

The docs currently define "agent" in a way that is specific to Teleport, i.e., as a service that proxies traffic to a remote resource:
- [Core Concepts page](https://github.com/gravitational/teleport/blob/18602f913fa9810a50a06f89446ded620454d3d4/docs/pages/core-concepts.mdx#L118-L123)
- [Introduction to the "Teleport Agents" section](https://github.com/gravitational/teleport/blob/18602f913fa9810a50a06f89446ded620454d3d4/docs/pages/agents/introduction.mdx)

However, some users might misconstrue the term "agent" as implying that they need to run a `teleport` binary on all hosts/Kubernetes clusters in their infrastructure (which is not true). To counter this, we include the term "agentless mode" in some pages of the documentation. 

While this term is useful in the context of addressing that particular misunderstanding, though, it also implies that there is an "agent mode" that, unlike agentless mode, requires running a `teleport` binary on the target resource. This is only true of the SSH Service. For agents running the Database Service, Kubernetes Service, etc., being an "agent" actually means the opposite of this.

Let's consider replacing "agentless mode" with a more precise term to clarify that the SSH Service is proxying traffic to a remote host, just like Teleport's other agent services.

## How will we know this is resolved?

We have replaced "agentless mode" with a more precise term in all of the locations this term appears in the docs.

## Related Issues

https://github.com/gravitational/teleport/issues/13364

**Comment by zmb3** [comment]
It's been over a year and no changes here, so I'm considering this not planned.
