### ISSUE TITLE
Automatic upgrades for Fargate agents

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#28780]
After https://github.com/gravitational/teleport/issues/25521 is implemented, Teleport Discover UI will gain ability to automatically deploy database agents on ECS Fargate in users' AWS accounts.

Because the agents run in containers, the automatic upgrades functionality we built that depends on either systemd or Kubernetes will not work for them. So we need to come up with a way to keep these agent versions in sync as well, otherwise our automatic upgrades story will be incomplete again.

As an initial idea: because in the Cloud environment we always have connection to AWS, can we just run a periodic sync loop on the cluster control plane that will monitor the auto-upgrades version endpoint and upgrade/downgrade those that run a different version (within a cluster's preferred maintenance window)?

Cloud agents upgrade RFD for reference: https://github.com/gravitational/teleport/blob/master/rfd/0109-cloud-agent-upgrades.md.

**Comment by marcoandredinis** [comment]
This is now completed.
