### ISSUE TITLE
Document new support for stdout://

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2880]
This commit implements #2872.

Similarly to `file://`, the scheme `stdout://` could be used complimentary
to the existing external scheme to logs audit logs:
to stdout:

```yaml
audit_events_uri: ['dynamodb://events', 'stdout://',]
```

Just like `file://` scheme it is only possible to use `stdout://`
scheme when external events and session uploader are defined,
so all audit upload and search features of teleport could work.

**Comment by benarent** [comment]
Closing as merged with #2921
