### ISSUE TITLE
Ubuntu Lunar (23.04) does not have a release

### ISSUE THREAD

**Issue by xmsanchez** [gravitational/teleport#28806]
Expected behavior:
Should be able to download Teleport from: https://goteleport.com/download/

Current behavior:
Repository is not found:
```
Err:12 https://apt.releases.teleport.dev/ubuntu lunar Release           
  404  Not Found [IP: 18.154.41.127 443]
E: Repository «https://apt.releases.teleport.dev/ubuntu lunar Release» does not have a file Release.
```

Bug details:
- Teleport version -
- Recreation steps
Try to run on Ubuntu 23.04:
```
curl https://goteleport.com/static/install.sh | bash -s 13.2.0
```
- Debug logs
```
Err:12 https://apt.releases.teleport.dev/ubuntu lunar Release           
  404  Not Found [IP: 18.154.41.127 443]
E: Repository «https://apt.releases.teleport.dev/ubuntu lunar Release» does not have a file Release.
```

UPDATE: You can still download directly the .deb packages, though.

**Comment by marcoandredinis** [comment]
Teleport's repo doesn't support `Ubuntu 23.04 (Lunar)`
Our latest supported version is `22.04 (Jammy)`

Related
https://github.com/gravitational/teleport/issues/18679
You can see some workarounds there

I'll change the title to describe the particular distro that we don't currently support

**Comment by pnunn** [comment]
Is this still the case?

**Comment by marcoandredinis** [comment]
Just tried on a fresh 23.04 ubuntu and was able to install teleport using 
```
curl https://goteleport.com/static/install.sh | bash -s 14.0.0
```
