### ISSUE TITLE
Manage Network Devices via SSH

### ISSUE THREAD

**Issue by milaan-muc** [gravitational/teleport#28898]
What would you like Teleport to do?
We want to access various network devices from Teleport via SSH so we dont need to rollout a silly Windows jump host.

What problem does this solve?
Monitoring and Authentication via a central instance

If a workaround exists, please include it.
Workaround is to use a bastian host with Teleport agent which is not feasible for us as we then have two jump hosts.

**Comment by zmb3** [comment]
This seems more appropriate for a [discussion](https://github.com/gravitational/teleport/discussions) as it's not quite detailed enough for a feature request.

You might be able to accomplish what you're looking for today with agentless mode (assuming your various network devices_ run openssh.
