### ISSUE TITLE
`proxy ssh` subcommand via tbot and tsh is too heavy

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#28910]
### Expected behavior:

When using openssh compatibility, performance should be on par with other ssh connection approaches.

### Current behavior:

When openssh invokes the `tbot proxy ssh` or `tsh proxy ssh` subcommand, there can be a significant amount of time before the tunnel is established, when compared to using a ProxyCommand that uses some combination of `ssh` and/or `openssl` commands.

Executing the command `tsh proxy ssh` or `tbot proxy ssh`, particularly with multiple invocations being launched simultaneously (example: running ansible against three hosts)

Initial recognition of this issue was reported when following the ansible+machine id guide. Connection failures with `"msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange"` were causing every ansible attempt to fail.

Ansible isn't required for there to be a problem. If you simply run `time ssh -F /opt/machine-id/ssh_config user@host hostname`, you can easily get really awful loading times. Ansible's default timeout is 10 seconds, so it gives up at that point. I tried running four invocations of that in four tmux panels so I could start them all at the same time. The four teleport binaries spent most of their time in D state as seen in top, and finally completed after `4m55.943s`. What is interesting is that all of them completed in exactly the same amount of time. When I repeated the test using a non-go-binary ProxyCommand, the same test completed in `0m4.775s`

Also, the amount of time it takes to complete the command seems to depend on how many parallel invocations there are at the same time. With 1, it might complete in the 10 second ansible timeout sometimes.

<details>
</summary>info on alternate ProxyCommand</summary>

```ini
# Begin generated Teleport configuration for teleport.example.com by tbot

# Common flags for all teleport.example.com hosts
Host *.example teleport.example.com
    UserKnownHostsFile "/opt/machine-id/known_hosts"
    IdentityFile "/opt/machine-id/key"
    CertificateFile "/opt/machine-id/key-cert.pub"
    HostKeyAlgorithms ssh-rsa-cert-v01@openssh.com

# use openssl command for connecting to proxy through multiplexing. Comment this out if not using multiplexing.
Host teleport.example.com
    ProxyCommand "openssl s_client -connect teleport.example.com:443 -alpn teleport-proxy-ssh 2>/dev/null"

# Flags for all teleport.example.com hosts except the proxy
Host *.example !teleport.example.com
    Port 3022
    #ProxyCommand "/usr/local/bin/tbot" proxy --destination-dir=/opt/machine-id --proxy=teleport.example.com:443 ssh --cluster=example  %r@%h:%p

    # use proxy subsystem with openssh client
    ProxyCommand ssh -F /path/to/this/ssh_config %r@teleport.example.com -s proxy:%h:%p

# End generated Teleport configuration
```

</details>

Another observation I made while troubleshooting this was that unlike `tsh proxy ssh` when run with a ~/.tsh credential, `tbot proxy ssh` will hit the proxy endpoint to determine the tunnel endpoint. This means that the `ssh` client must wait on `tbot proxy ssh` to [complete a full round-trip https request](https://github.com/gravitational/teleport/blob/branch/v13/tool/tsh/tsh.go#L3315-L3331) before it even starts setting up the tunnel. Since tbot continuously renews the cert, it seems reasonable for it to write out the endpoint in a way that `tbot proxy ssh` would not need to do this round-trip request on every invocation.

### Workarounds

* increase the ansible timeout from the 10 second default (this is very slow, but things can progress)
* use an alternate ProxyCommand as outlined in the above collapsed details section.
* Enable ssh's [connection sharing](https://man.openbsd.org/ssh_config.5#ControlMaster) feature to allow multiple invocations of the `ssh` client to use an existing tunnel connection without invoking a new instance of `tsh proxy ssh` or `tbot proxy ssh`

### Bug details:
- Teleport version - seen on `Teleport v13.1.5 git:api/v13.1.5-0-g77eae2d go1.20.5` but is not specific to this version
- Recreation steps
  * Launch a t3.nano instance
  * Follow the guide for [machine id with ansible](https://goteleport.com/docs/machine-id/guides/ansible/)
  * Connect to 3-5 hosts with the example playbook in the guide, running `hostname`, and observe timeouts.
- Debug logs - n/a

This issue affects both tbot proxy ssh and tsh proxy ssh, but is slightly worse with tbot. This issue is really present on systems with low compute resources, but any improvement will help user experience across the  board.

**Comment by strideynet** [comment]
I share these concerns - for a few customers - I've walked them through modifying the `ssh_config` to connect directly to their Proxy server's SSH proxying port, but this isn't always possible depending on their configuration and it feels like this is brittle to changes in the future.

> This means that the ssh client must wait on tbot proxy ssh to [complete a full round-trip https request](https://github.com/gravitational/teleport/blob/branch/v13/tool/tsh/tsh.go#L3315-L3331) before it even starts setting up the tunnel. Since tbot continuously renews the cert, it seems reasonable for it to write out the endpoint in a way that tbot proxy ssh would not need to do this round-trip request on every invocation.

This is a really good catch and probably explains the worse performance seen with `tbot` added to the mix (although, it's worth noting this would also affect users using the old `tctl auth sign` method of performing machine access).

The current issue with fixing this is that the identity file format is used in a few different ways, and isn't easily extensible. We'd need to think about whether we'd want to extend the current identity file to include this information, introduce a new identity file format or, remove `tbot`'s reliance on `tsh` entirely.

**Comment by strideynet** [comment]
Partially addressed by https://github.com/gravitational/teleport/pull/41342
