### ISSUE TITLE
`teleport configure` doesn't generate a valid config file out of the box

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#2891]
**What happened**: Running `teleport configure` should output a config file which will immediately work. 

Unfortunately this isn't currently the case - the value for `auth_servers` is set to `0.0.0.0:3025` as a default, but this is a bind address rather than a connectable address and causes clusters not to work correctly.

```
$ teleport configure                                                                                                                                            
#
# Sample Teleport configuration file.
#
teleport:
  nodename: antaeus
  data_dir: /var/lib/teleport
  pid_file: /var/run/teleport.pid
  auth_token: cluster-join-token
  auth_servers:
  - 0.0.0.0:3025
  connection_limits:
    max_connections: 15000
    max_users: 250
  log:
    output: stderr
    severity: INFO
  ca_pin: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  tokens:
  - proxy,node:cluster-join-token
  session_recording: ""
  client_idle_timeout: 0s
  disconnect_expired_cert: false
  keep_alive_count_max: 0
ssh_service:
  enabled: "yes"
  labels:
    db_role: master
    db_type: postgres
  commands:
  - name: hostname
    command: [/usr/bin/hostname]
    period: 1m0s
  - name: arch
    command: [/usr/bin/uname, -p]
    period: 1h0m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: /var/lib/teleport/webproxy_key.pem
  https_cert_file: /var/lib/teleport/webproxy_cert.pem
```

This has flummoxed several users on the Community forums (https://community.gravitational.com/t/adding-a-node-to-the-cluster/239) as the error isn't immediately obvious.

**What you expected to happen**: A config which is usable without any changes should be generated.

**How to reproduce it (as minimally and precisely as possible)**: Download Teleport, extract tarball, run `teleport configure`.

**Environment**:
- Teleport version (use `teleport version`): `Teleport Enterprise v4.0.2git:v4.0.2-0-gb7e0e872 go1.12.1`
- Tsh version (use `tsh version`): `Teleport v4.0.2 git:v4.0.2-0-gb7e0e872 go1.12.1`
- OS (e.g. from /etc/os-release): `Fedora 29`

This is probably an easy starter issue.

**Comment by benarent** [comment]
As another bonus, if a customer is running teleport-ent, we should include information about the license file in the file format. As it's not 100% clear, until it doesn't run and then you find out why. 

```
error: auth server requires a valid license file to start, please set the correct license_file path under auth_service section in your teleport config or put the license into the default search location at /var/lib/teleport/license.pem, initialization failed
```
