### ISSUE TITLE
Server Session Locking

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#28948]
Expected behavior:
User should be able to create a lock in the UI for Servers.

Current behavior:
When a user tries to create a lock for a server resource there is an error: 
<img width="634" alt="Screenshot 2023-07-11 at 10 05 42 AM" src="https://github.com/gravitational/teleport/assets/51385814/91a4d77e-3dfb-4248-96f4-fcec63c75c72">

Bug details:
- Teleport version: v13.2.0
- Recreation steps: Login to the UI and try to create a Server lock
- Debug logs

**Comment by zmb3** [comment]
This appears to be a regression introduced in #27395
