### ISSUE TITLE
Install Script Fails on Pop!_OS

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/teleport#28957]
Expected behavior:
Run `curl https://goteleport.com/static/install.sh | bash -s 13.2.0` and get Teleport.

Current behavior:
The install script creates a malformed `teleport.list` file with two codenames:

```
❯ cat /etc/apt/sources.list.d/teleport.list
deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc]  https://apt.releases.teleport.dev/ubuntu debian jammy stable/v13
```

The extra `debian` before `jammy` is the problem.

Bug details:
- ~Teleport~ OS version:
   ```
   ❯ cat /etc/os-release
   NAME="Pop!_OS"
   VERSION="22.04 LTS"
   ID=pop
   ID_LIKE="ubuntu debian"
   PRETTY_NAME="Pop!_OS 22.04 LTS"
   VERSION_ID="22.04"
   HOME_URL="https://pop.system76.com"
   SUPPORT_URL="https://support.system76.com"
   BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
   PRIVACY_POLICY_URL="https://system76.com/privacy"
   VERSION_CODENAME=jammy
   UBUNTU_CODENAME=jammy
   LOGO=distributor-logo-pop-os
   ```

- Recreation steps

1. Have Pop!_OS
2. Run the install script.

**Comment by alexfornuto** [comment]
P.S. It looks like the issue is that Pop has two values in `ID_LIKE` and our script expects only one.

**Comment by alexfornuto** [comment]
No reference to the code change that resolves?

**Comment by ptgott** [comment]
Hi Alex, the code change is in a private repo.
