### ISSUE TITLE
Improve teleport error message UX

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2898]
![errr](https://user-images.githubusercontent.com/13717/62571602-a2334000-b846-11e9-9c20-ff906360f35f.png)

Take a look at the attached error. There are a couple of things that we should improve:

* Supplemental error message is greyed out and not visible.
* Call to action should be to community.gravitational.com for OSS and zendesk to paid customers, not a github
* Giant construction sign is probably overdue for refactoring

Shall we add this to 4.2 milestone? I will let you folks to decide

**Comment by benarent** [comment]
We are going to remove some of these styles in 4.2, so these will look different. I will put it into 4.2 milestone to remind us to check all of the error messages when we run the update.

**Comment by benarent** [comment]
Related Specs: [Teleport 4.3 - Hornet ( aka Redesign ) | Login Page: Error States: ](https://docs.google.com/document/d/1gMyMYFxPhYSMz9OT_BVCOTKmGPgtcYCOxmQBa9XddCA/edit#heading=h.p34hgo3r0a44 )

**Comment by alex-kovoy** [comment]
![image](https://user-images.githubusercontent.com/7816406/77609367-2cbfd100-6ef6-11ea-9756-48edbc64a0d0.png)
