### ISSUE TITLE
Add Opsgenie documentation guide

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#29005]
We should write a guide explaining to users how to use our Opsgenie integration and put it among other access plugin guides:

https://goteleport.com/docs/access-controls/access-request-plugins/

The guide is a bit different from existing access plugin guides because Opsgenie is only Cloud-hosted currently. So the guide should not instruct the users to download any binaries or creating any configuration files but it should cover the following:

- How to set up Opsgenie access token and which permissions are needed.
- How to enable Opsgenie hosted plugin in Teleport Cloud. The guide should only have "cloud" scope. Screenshots from the Discover wizard would be helpful as well.
- How to set up roles for Opsgenie access requests and how to use annotation.
- How to set up auto-approval (when it's ready).

**Comment by ptgott** [comment]
Closing as complete
