### ISSUE TITLE
Grant OSS instances access to use the Desktop Access feature

### ISSUE THREAD

**Issue by binaryn3xus** [gravitational/teleport#29015]
**What would you like Teleport to do?**

Please allow OSS users to use Windows Desktop Access. Currently, according to [Getting Started With Teleport Windows Access (Youtube)](https://youtu.be/9DyKQbg4ORc), this feature is only supported for Enterprise licenses. In the comments of the recently referenced video, the official goteleport account said the following:

```
@goteleport: We hope to have a more flexible plan for people in your situation, both for the community and small team,. Watch this space.
```

**What problem does this solve?**

By allowing this, you would give all personal/home-lab users to be able to utilize this useful Teleport tool.

Extra:
<details>
  <summary>Screenshot of YouTube Comment Mentioned</summary>

![image](https://github.com/gravitational/teleport/assets/1706923/0e7bacd4-a50f-4565-835b-eac2387fe90d)

</details>

**Comment by zmb3** [comment]
This work is in progress.

**Comment by zmb3** [comment]
Work is completed and docs are merged. This will be available in v14 for up to 5 desktops.
