### ISSUE TITLE
"localhost" not in the set of valid principals for given certificate

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#2910]
**What happened**:
When a customer completes the Quickstart they get this error message. 

```
WARNING: You are using insecure connection to SSH proxy 
https://localhost:3080 error: ssh: handshake failed: ssh: principal 
"localhost" not in the set of valid principals for given certificate: 
["cc91fdc6-81a8-4dc2-88d0-77b4b07e1b16.abdu-ThinkPad-T480" "abdu-ThinkPad-
T480.abdu-ThinkPad-T480" "abdu-ThinkPad-T480" 
"remote.kube.proxy.teleport.cluster.local"]
```

This is due to `localhost` not being created as part of the SSH certificate. Customers can fix this by copying the hostname and using this e.g. `https://abdu-ThinkPad-T480:3080`.

**What you expected to happen**:
We should improve the error message, if possible add the hostname as default. 

Customer can add localhost to the set of principles by adding 
```
teleport:
  proxy_service:
    listen_addr: localhost:3080
```

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`): 4.0
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release): Linux

**Comment by klizhentas** [comment]
I don't see any problem adding `localhost` by default everywhere

**Comment by webvictim** [comment]
We do already add the hostname by default, i.e. `abdu-ThinkPad-T480`. I definitely agree that adding `localhost` to everything would make for a nicer example.

**Comment by webvictim** [comment]
We should also add `127.0.0.1` as well as `localhost` when fixing this issue.
