### ISSUE TITLE
Terminal in Web UI: `_` show as spaces

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#29126]
Expected behavior:
![image](https://github.com/gravitational/teleport/assets/689271/f96e6649-ccb1-4703-85a5-30028b10c52b)

Current behavior:
Use the Terminal Web UI and notice that the `_` chars appear as spaces
![image](https://github.com/gravitational/teleport/assets/689271/7814818e-e7f7-4f22-a5af-6ea84f168f73)

Bug details:
- Teleport version
`master`, `v13.2.1`, `v12.4.11` and `v11.3.17`

- Recreation steps
Linux w/ `Chrome Version 114.0.5735.198 (Official Build) (64-bit)`

If you zoom out or zoom in, you'll see the `_` (that's how I got the first screenshot)

**Comment by zmb3** [comment]
For context, this was an issue in the past and we fixed it by upgrading to xterm.js v5 in gravitational/webapps#1400

See also:

- https://github.com/xtermjs/xterm.js/issues/4067
- https://github.com/xtermjs/xterm.js/issues/3353
- https://github.com/xtermjs/xterm.js/issues/3423
- https://github.com/xtermjs/xterm.js/issues/1170
- https://github.com/xtermjs/xterm.js/issues/1138

**Comment by marcoandredinis** [comment]
If we add the xterm-addon-webgl it works:
![image](https://github.com/gravitational/teleport/assets/689271/816711e3-435f-4023-8e3c-0f7b05dd5fcd)

I've added `xterm-addon-webgl` and `xterm-addon-canvas` to have a fallback

**Comment by zmb3** [comment]
Out of curiosity - do you see the same behavior in Teleport Connect?

**Comment by durzo** [comment]
This is a pretty frustrating bug that still affects latest versions of Teleport. any progress on this?

**Comment by marcoandredinis** [comment]
> Out of curiosity - do you see the same behavior in Teleport Connect?

It does not
WebUI `master` on the left and Connect 14.1.3 on the right
![image](https://github.com/gravitational/teleport/assets/689271/d47d88d8-eaef-42ab-851f-1eab8b2cdbf1)

**Comment by marcoandredinis** [comment]
Fixed in https://github.com/gravitational/teleport/pull/36763
