### ISSUE TITLE
Create user messgage when `tsh login` ignores the `--user` flag

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#29141]
What would you like Teleport to do?
When the Teleport cluster has the authentication `type` set to `saml`/`oidc`, `tsh login` defaults to SSO login flow unless overridden with the `--auth` flag.  If the `--user` flag is set but the SSO login flow is initiated, the `--user` flag is silently ignored and the user will be logged in as the user provided by the SSO.  This can create confusion for users who explicitly set a user and most likely intended to pass `--auth=local` as well.

The request is to add a warning or user message that the selected `--user` is being ignored, and indicate that local users will require setting `--auth=local` or changing the default.

What problem does this solve?
User experience is degraded when flags are ignored silently and the logged in user is not as expected from the input without explicit warning.

If a workaround exists, please include it.
ensure the default is set to local or you pass the `--auth=local` flag

**Comment by stevenGravy** [comment]
This was partially implemented by #29203 .  This still needs to be implemented to cover when the SSO is the default and the user parameter is specified.
