### ISSUE TITLE
NO_PROXY doesn't support IP ranges, preventing usage with all-in-one node

### ISSUE THREAD

**Issue by ThinkBriK** [gravitational/teleport#2915]
**What happened**:
Tried to setup a single node deployment in a private environment in aws.
A part of my problem is with DynamoDB streams that are not supported by AWS endpoints, so I have to use an HTTP Proxy. here comes the BUT...

Setting the HTTP(S)_PROXY env variables in the sytemd unit is OK but I need the proxy part to connect to the nodes and it is using the nodes IPs to do so !

So I set up the NO_PROXY env in systemd with my private addresses 10.0.0.0/8 and ....
I got `unable to proxy connection: 403 Forbidden` errors that are actually my Proxy replies...

Checking the code at https://github.com/gravitational/teleport/blob/ff5cfc6b43fe86bdcd5a9ae6eedd0d483c54bba6/lib/utils/proxy/noproxy.go#L22, I found that the NO_PROXY support is custom and the IP ranges are not taken into account.

**What you expected to happen**:
IP ranges support in NO_PROXY variables by Teleport Proxy
**How to reproduce it (as minimally and precisely as possible)**:
Use a NO_PROXY env variable with a CIDR notation (eg. 10.0.0.8) and HTTPS_PROXY env set. If the proxy itself cannot access the local Teleport ports, you will be unable to connect to the nodes. 
**Environment**:
- Teleport version (use `teleport version`): Teleport v4.0.4 git:v4.0.4-0-g1a2ed507 go1.12.1
- Tsh version (use `tsh version`): Teleport v4.0.4 git:v4.0.4-0-g1a2ed507 go1.12.1
- OS (e.g. from /etc/os-release): Centos 7

**Relevant Debug Logs If Applicable**

Teleport Server
```
INFO [CLIENT]    Client=10.0.0.12:51692 connecting to node=mynode:0@default@my.cloud client/client.go:363
WARN [PROXY]     Subsystem request proxySubsys(cluster=default/my.cloud, host=mynode, port=0) failed: unable to proxy connection: 403 Forbidden. id:6 local:127.0.0.1:2222 login:centos remote:127.0.0.1:46426 teleportUser:thinkbrik regular/sshserver.go:1174
ERRO [NODE]      unable to proxy connection: 403 Forbidden regular/sshserver.go:1246
WARN [WEBSOCKET] Unable to stream terminal: failed connecting to node mynode. error: unable to proxy connection: 403 Forbidden. web/terminal.go:296
```

Proxy
```
1565604636.095      0 10.0.0.10 TCP_DENIED/403 3868 CONNECT 10.0.0.11:3022 - HIER_NONE/- text/html
```

**Comment by bcg62** [comment]
I have also hit this issue when configuring teleport to use external auth (saml/okta) and  entity_descriptor_url which needs HTTPS_PROXY to be fetched.

Teleport then tries to hit the local k8s api endpoint via HTTPS_PROXY and you cannot set a no_proxy cidr to avoid it.

I think this is a larger issue with go itself. 

https://github.com/golang/go/issues/16704
https://github.com/golang/proposal/blob/master/design/16704-cidr-notation-no-proxy.md

**Comment by ThinkBriK** [comment]
Actually the decision to use the HTTP Proxy for the Teleport Proxy is actually made in the **useProxy** function I already listed, the Go Net/HTTP you referenced is not used for this : https://github.com/gravitational/teleport/blob/ff5cfc6b43fe86bdcd5a9ae6eedd0d483c54bba6/lib/utils/proxy/noproxy.go#L22

**Comment by ThinkBriK** [comment]
In addition, the proxy doesn't support proxying and url and not proxying its child urls (shold be explicit notation with url starting with a dot):
`NO_PROXY="dynamodb.eu-west-1.amazonaws.com"` will skip proxy for both `dynamodb.eu-west-1.amazonaws.com` and `streams.dynamodb.eu-west-1.amazonaws.com`.

In my specific case it's not obvious because I use a VPC endpoint for DynamoDB (`dynamodb.eu-west-1.amazonaws.com`) and endpoints do not provide stream access (I have to proxy  `streams.dynamodb.eu-west-1.amazonaws.com`).

I have to use a decoupled auth_server/rpoxy setup with the authserver using `NO_PROXY="eu-west-1.amazonaws.com"` as a workaround ...

**Comment by russjones** [comment]
It looks like two things have happened: first the proxy handling code has [moved out from the standard library into a standalone package](https://pkg.go.dev/golang.org/x/net/http/httpproxy) and second [the CIDR limitations have been addressed](https://go-review.googlesource.com/c/net/+/115255/).

I have a preference to either use the `httpproxy` package and completely remove proxy handling logic from Teleport. If that's not possible, make a copy like we originally did.

**Comment by atburke** [comment]
@zmb3 This is fixed. We now use `httpproxy` directly instead of the old local `useProxy()` copy.
