### ISSUE TITLE
`app.session.start` audit event is not emitted when using Application Access with `tsh` or `tbot`

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#29246]
The `app.session.start` audit event is intended to be emitted when a user begins an Application Access session. This functions correctly when using the Web UI, but when using `tsh` or `tbot` it does not appear. Other audit events, such as those that are emitted for each chunk / request, function correctly.

This is because it is emitted by the handler for POST `/v1/webapi/sessions/app` in the Proxy Service API. `tsh` and `tbot` call the `CreateAppSession` RPC on the Auth Server directly and do not use this endpoint.

As `app.session.start` is converted to an analytics event, this also has a knock on affect on our product analytics (app activity using `tsh` or `tbot` will not be recorded) for Teleport Cloud.

**Comment by zmb3** [comment]
Fixed by #43636
