### ISSUE TITLE
WebApi cluster API should return a cluster teleport version

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#2925]
This API `/v1/webapi/sites `should provide a teleport `version` of each cluster, so it can be displayed inside cluster card 

![image](https://user-images.githubusercontent.com/7816406/63047565-b3adc500-bea2-11e9-9774-ab243da8aff1.png)

**Comment by benarent** [comment]
Closing this issue as https://github.com/gravitational/teleport/pull/3324 returns cluster version
