### ISSUE TITLE
Yeahu

### ISSUE THREAD

**Issue by budsone** [gravitational/teleport#2931]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by budsone** [comment]
>http://[server_addr]:7500 to

**Comment by klizhentas** [comment]
seems like incomplete report. if you have a question please use our https://community.gravitational.com
