### ISSUE TITLE
aws configurator gives incorrect policy output in manual mode

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#29335]
I have my config like this:
```yaml
discovery_service:
  enabled: true
  discovery_group: "aws-dev"
  aws:
    - types:
        - "rds"
      regions:
        - "us-west-1"
      assume_role_arn: "arn:aws:iam::278576220453:role/ci-e2e-test-discovery-svc"
      tags:
        "*": "*"
```

I tried to print the IAM policies with this command:
```
$ teleport discovery bootstrap -c ~/config.yaml --manual --attach-to-role ci-e2e-test-discovery-svc
```

## Expected behavior
It should print policy docs with RDS permissions for discovery, namely:

```
Configure AWS for Discovery Service
1. Create IAM Policy "TeleportEC2Discovery":
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "rds:DescribeDBInstances",
                "rds:DescribeDBClusters"
            ],
            "Resource": "*"
        }
    ]
}

2. Create IAM Policy "TeleportEC2DiscoveryBoundary":
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "rds:DescribeDBInstances",
                "rds:DescribeDBClusters"
            ],
            "Resource": "*"
        }
    ]
}

3. Attach IAM policies to "ci-e2e-test-discovery-svc".
```

## Current behavior
```
Configure AWS for Discovery Service
1. Create IAM Policy "TeleportEC2Discovery":
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::278576220453:role/ci-e2e-test-discovery-svc"
        }
    ]
}

2. Create IAM Policy "TeleportEC2DiscoveryBoundary":
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "*"
        }
    ]
}

3. Attach IAM policies to "ci-e2e-test-discovery-svc".
```

It's caused by the fact that in manual mode, we don't know the `--attach-to-role` account and partition in AWS, therefore, it does not match the `assume_role_arn` in config and know that I'm trying to attach permissions to that role.

@greedy52 I think we discussed this a while ago in one of my PRs, but regardless I found the behavior surprising and I'm sure users will too. I'm not sure if calling this a "bug" is right, since it's more like poor UX.

What do you think about just requiring that the user supply a full ARN for `--attach-to-role` (and similar flags) in `--manual` mode?
I'd rather just get an error message telling me to be specific about what role I'm attaching to than get seemingly random results lol.

Also, the `--confirm` flag for automatic mode seems to be backwards logic to me. If you do `--no-confirm` then it prompts for confirmation at each step, but `--confirm` does not prompt. I got the expected output for this issue by running with confirmation and ran into that surprising behavior in the process lol.

Bug details:
- Teleport version: master (pre-release v14)

Workaround:
- specify a full AWS Role arn, like this: `--attach-to-role arn:aws:iam::123456789012:role/ci-e2e-test-discovery-svc`

**Comment by GavinFrazar** [comment]
also, the policy generated has "ec2" in the name... :/

**Comment by greedy52** [comment]
> What do you think about just requiring that the user supply a full ARN for --attach-to-role (and similar flags) in --manual mode?

+1

> Also, the --confirm flag for automatic mode seems to be backwards logic to me. If you do --no-confirm then it prompts for confirmation at each step, but --confirm does not prompt. I got the expected output for this issue by running with confirmation and ran into that surprising behavior in the process lol.

Maybe we can rename it to `--skip-confirm` similar to this:
https://github.com/gravitational/teleport/blob/6bbcfbd8d556741cc1db9a3680169b4b21a81ff7/tool/tsh/common/tsh.go#L1016
Do we still have the RFD for CLI guideline?

> also, the policy generated has "ec2" in the name... :/

we can remove the `ec2` part. i was hesitant on this as if someone re-bootstrap they will end up with a new policy. Though I don't think we officially support re-bootstrap.

**Comment by GavinFrazar** [comment]
> Do we still have the RFD for CLI guideline?

Yes... although it's been in my backlog for a while now, I still only have a rough draft of it locally

> we can remove the ec2 part. i was hesitant on this as if someone re-bootstrap they will end up with a new policy. Though I don't think we officially support re-bootstrap.

hmm, I think it should be ok since they have to specify which identity to attach to. At worst they just end up with an extra policy sitting around
