### ISSUE TITLE
can not create bot token

### ISSUE THREAD

**Issue by qixiangyang** [gravitational/teleport#29337]
Expected behavior:
tctl tokens add --ttl=5m --type=Bot --bot_name=bot
output: token info

Current behavior:

first step:
tctl tokens add --ttl=5m --type=Bot
ERROR: token with role "Bot" must set bot_name

second step:
tctl tokens add --ttl=5m --type=Bot --bot_name=bot
tctl: error: unknown long flag '--bot_name'

Bug details:
- Teleport version 13.1.5
- Recreation steps
- Debug logs

**Comment by strideynet** [comment]
Bot tokens will automatically be created when running `tctl bots add` - you do not need to run `tctl tokens add` :)
