### ISSUE TITLE
Version 11.3.17 has issues displaying Audit Log and Session Recordings

### ISSUE THREAD

**Issue by aardbol** [gravitational/teleport#29349]
Expected behavior:
Display both sections correctly

Current behavior:
Shows this error:
`rpc error: code = Unknown desc = rpc error: code = InvalidArgument desc = Cannot have inequality filters on multiple properties: [createdAt, sessionID]`

Downgrading back to v11.3.12 fixes this.

Bug details:
- Teleport version 11.3.17 (enterprise)
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
This was fixed in #29116
