### ISSUE TITLE
Helm chart certs not generated

### ISSUE THREAD

**Issue by stobias123** [gravitational/teleport#2936]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
Pod never gets created.
```
secrets "tls-web" not found
```

**What you expected to happen**:
Pod to be created.
**How to reproduce it (as minimally and precisely as possible)**:
Run the helm install without pre-creating tls certs for proxy service.

**Comment by russjones** [comment]
Best: 1 day.
Realistic: 2 days.

**Comment by webvictim** [comment]
This is now addressed in the Helm chart README under this section: https://github.com/gravitational/teleport/blob/master/examples/chart/teleport/README.md#certificate-usage-configuration

This should make it clearer for future Helm users. Closing the ticket.
