### ISSUE TITLE
invalid sorting of recordings post migration from opensource/GH to enterprise/okta builds

### ISSUE THREAD

**Issue by joshdurbin** [gravitational/teleport#2937]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:

2 days ago we migrated our clusters from the open source branch https://github.com/bigcommerce/teleport/tree/gcp_ha_support to an enterprise build on the same branch.

**What you expected to happen**:

Post migration it appeared that recordings weren't working against GCS. I looked into the data stores for the expected events, which included upload events and then confirmed that the recordings were in fact in GCS. After tinkering with the UI, if I changed the date scope to the present day, I could find my recordings.

When sessions are active they are at the top of the list with the orange/yellow "join" button as expected.

**How to reproduce it (as minimally and precisely as possible)**:

See prior section.

I believe what's going on has something to do with sorting in the UI when you migrated from usernames without domains to those with. For example, the cluster that was migrated from OS --> ent build first used a Github connector, which was then replaced with an Okta/SAML connector. This meant that usernames went from GH handles, ex: `joshdurbin`, to usernames + domain, ex: `josh.durbin@domain`.

It's either that or there's a bug in the sorting for Firestore in this case.

**Environment**:
- Teleport version (use `teleport version`): `Teleport Enterprise v4.1.0-alpha.5git:v4.1.0-alpha.5-37-g7b632ba5-dirty go1.12.6`
- Tsh version (use `tsh version`): `Teleport v4.1.0-alpha.5 git:v4.1.0-alpha.5-37-g7b632ba5-dirty go1.12.6`
- OS (e.g. from /etc/os-release): `Debian GNU/Linux 8 (jessie)`

**Browser environment**

- Browser Version (for UI-related issues): MacOS version `10.14.6 (18G87)`, Safari `Version 12.1.2 (14607.3.9)`
- Install tools: n/a
- Others: n/a

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by joshdurbin** [comment]
@fspmarshall agreed on your find, I'll run through some tests after changing that block to:

```
	docSnaps, _ := l.svc.Collection(l.CollectionName).Where(eventNamespaceDocProperty, "==", defaults.Namespace).
		Where(createdAtDocProperty, ">=", fromUTC.Unix()).Where(createdAtDocProperty, "<=", toUTC.Unix()).
		OrderBy(createdAtDocProperty, firestore.Asc).Limit(limit).Documents(l.svcContext).GetAll()
```

**Comment by zmb3** [comment]
Closing this one due to inactivity. The firestore backend has changed quite a bit in the last 3 years, so feel free to open a new issue if there are still concerns.
