### ISSUE TITLE
feat: Allow setting kops cluster name

### ISSUE THREAD

**Issue by Nuru** [gravitational/teleport#2939]
The cluster name used by Teleport is different than the cluster name used by `kops`. This breaks `kops`. The solution is to provide a way to specify the `kops` cluster name and use that when creating the `kubecfg`. 

See https://github.com/cloudposse/geodesic/issues/474 for more details.

**Comment by zmb3** [comment]
Closing this one due to inactivity. Unfortunately, we haven't seen large demand for any changes here.
