### ISSUE TITLE
Stop emitting the deprecated trusted_cluster_token.create event

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#29392]
**Note: this can only be addressed in v15 or later.**

PR #28769 created a new, generic audit event that is intended to replace `trusted_cluster_token.create`. The old event still needs to be recognized by the frontend (which can be used to view legacy data), so it can't be completely eradicated from our codebase; however, Teleport should stop actively emitting it.

This is a follow-up to #16359.

**Comment by zmb3** [comment]
Why v15? This can be merged now for release in v14, right?

**Comment by bl-nero** [comment]
I thought that the rule is to keep the deprecated feature for at least one full major release. Since 14 will be that release, I assumed that v15 is the earliest when this can be removed. Am I mistaken here?

**Comment by zmb3** [comment]
I suppose either is fine. If this were a full "feature" I'd agree with waiting for v15, but we already have the new event, so we just need to decide when we stop emitting the old event. I think as long as it lands in a new major it doesn't really make a difference if that ends up being 14 or 15.
