### ISSUE TITLE
TELEPORT_SITE not affecting `tsh login` as expected

### ISSUE THREAD

**Issue by Nuru** [gravitational/teleport#2940]
I'm not sure if this is a regression or if it never worked properly, but the feature introduced in https://github.com/gravitational/teleport/pull/2675 is not working as expected in Teleport 4.0.4.

**What happened**:
We have a setup where there is a trusted cluster `corp` that has the public authentication portal, and a trusting cluster `prod` that you can only get to through `corp`
Executing
```
$ TELEPORT_PROXY=teleport.corp.com TELEPORT_SITE=prod tsh login
```
correctly logs us into `prod` through `corp` for most purposes. `tsh status` is still affected by https://github.com/gravitational/teleport/issues/2671 but if we do `tsh ls` we get the list of clusters in `prod`. However, our `KUBECFG` is pointing to `corp` and `kubectl get nodes` lists the nodes in `corp`, not `prod`. To switch Kubernetes clusters we have to put `prod` on the command line, and the whole point of https://github.com/gravitational/teleport/pull/2675 was to avoid that requirement.

**What you expected to happen**:

Expected to be logged into the cluster specified by `TELEPORT_SITE` and for `kubectl` to be configured to operate on that site. (Also expected `tsh status` to indicate `Cluster: prod` but that is https://github.com/gravitational/teleport/issues/2671)

**How to reproduce it (as minimally and precisely as possible)**:

Set up a trusting and trusted cluster. Log into the trusting cluster using `TELEPORT_PROXY` and `TELEPORT_SITE` environment variables instead of command line or config file settings.

**Environment**:
- Teleport version (use `teleport version`): 4.0.4
- Tsh version (use `tsh version`): 4.0.4
- OS (e.g. from /etc/os-release): Alpine 3.10.1

**Comment by strideynet** [comment]
This was closed by https://github.com/gravitational/teleport/pull/2942.
