### ISSUE TITLE
Active Session

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#2943]
**Motivation**
With the move to a unified audit log view, we'll need a new area to show active sessions. 

Proposal
- New sidebar item showing for active sessions ( with count of them in progress ) 
- List of active sessions with ability to join @alexwolfe to provide design.

**Comment by alexwolfe** [comment]
![Cluster - Active Sessions](https://user-images.githubusercontent.com/407237/63975905-f6f06200-ca64-11e9-90fb-e7e4bf7d71d4.png)

**Comment by benarent** [comment]
Thanks @alexwolfe , I've re-assigned to @alex-kovoy now.

**Comment by alexwolfe** [comment]
@benarent @alex-kovoy Here's an updated design based on feedback. 
![Cluster - Operations](https://user-images.githubusercontent.com/407237/64038640-64f06400-cb0d-11e9-9730-6c9894b065c1.png)

**Comment by alex-kovoy** [comment]
done
