### ISSUE TITLE
Extra notes for Teleport 4.2 Design.

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#2944]
- [x] Add Teleport dashboard link to account settings dropdown.
- [ ] Clicking Logo goes to Nodes page
- [x] Loading Screen
- [x] Table view for clusters

**Comment by alexwolfe** [comment]
![Account Settings](https://user-images.githubusercontent.com/407237/63975928-0374ba80-ca65-11e9-9c76-7b597b79bed1.png)
![Uploading Cluster - Active Sessions.png…]()

**Comment by alexwolfe** [comment]
![Loading Sceen](https://user-images.githubusercontent.com/407237/63977759-6bc59b00-ca69-11e9-96cd-b2cf7856757a.png)

**Comment by alexwolfe** [comment]
@benarent @alex-kovoy here are updated images to address these screens

**Comment by benarent** [comment]
I've moved these comments and notes to https://docs.google.com/document/d/1gMyMYFxPhYSMz9OT_BVCOTKmGPgtcYCOxmQBa9XddCA/edit#heading=h.zfra0q2ohphg 

Going to close this issue for now.
