### ISSUE TITLE
--k8s-groups is not support local user, but not document it in user Admin Manual

### ISSUE THREAD

**Issue by mailtokun** [gravitational/teleport#2950]
**What happened**:
```
tctl users add test@com --k8s-groups="system:masters"
error: unknown long flag '--k8s-groups'
https://gravitational.com/teleport/docs/admin-guide/#adding-and-deleting-users
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`): 4.05
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release): Mac

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by mailtokun** [comment]
adminisatorsmbp:teleport administrator$ tctl users add --help
usage: tctl users add --roles=ROLES [<flags>] <account>

Generate a user invitation token [Teleport DB users only]

Flags:
  -d, --debug   Enable verbose logging to stderr
  -c, --config  Path to a configuration file [/etc/teleport.yaml]
      --roles   List of roles for the new user to assume
      --ttl     Set expiration time for token, default is 1 hour, maximum is 48 hours

Args:
  <account>  Teleport user account name

Aliases:
Notes:

  1. tctl will generate a signup token and give you a URL to share with a user.
     A user will have to complete account creation by visiting the URL.

  2. The allowed logins of the account only apply if a role uses them by including
     '{{ internal.logins }}' variable in a role definition.

Examples:

  > tctl users add --roles=admin,dba joe

  This creates a Teleport account 'joe' who will assume the roles 'admin' and 'dba'
  To see the permissions of 'admin' role, execute 'tctl get role/admin'

**Comment by zmb3** [comment]
This one obsolete now that k8s groups belong to roles and not users.
