### ISSUE TITLE
typo in documention:  /etc/teleport.yaaml should be # snippet from /etc/teleport.yaml

### ISSUE THREAD

**Issue by mailtokun** [gravitational/teleport#2951]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
https://gravitational.com/teleport/docs/admin-guide/#github-oauth-20
<img width="595" alt="image" src="https://user-images.githubusercontent.com/18410000/64095024-3a620d80-cd90-11e9-91b7-4353ab556551.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by benarent** [comment]
Thanks for reporting. I've a PR to fix this, I'm going to mark this issue as closed.
