### ISSUE TITLE
Confusing error message in Teleport install script on MacOS

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#29518]
I've followed our install on MacOS in Teleport cloud, and we get two confusing messages:

```
023-07-24 12:41:18 PDT [teleport-installer] Writing Teleport node service config to /etc/teleport.yaml

A Teleport configuration file has been created at "/etc/teleport.yaml".
Add your Teleport license file to "/var/lib/teleport/license.pem".
To start Teleport with this configuration file, run:

sudo teleport start --config="/etc/teleport.yaml"

Note that starting a Teleport server with this configuration will require root access as:
- The Teleport configuration is located at "/etc/teleport.yaml".
- Teleport will be storing data at "/var/lib/teleport". To change that, run "teleport configure" with the "--data-dir" flag.

Happy Teleporting!
2023-07-24 12:41:18 PDT [teleport-installer] Host is running MacOS
2023-07-24 12:41:18 PDT [teleport-installer] Installing Teleport launchd config to /Library/LaunchDaemons
2023-07-24 12:41:18 PDT [teleport-installer] Starting Teleport via launchctl. It will automatically be started whenever the system reboots.

Teleport has been started.
```

One says that I have to run `sudo teleport start` and another one says that `Teleport has been started`. I think the first message is not necessary.

**Comment by r0mant** [comment]
Looks like the first message is coming as default output message from "teleport configure" command, this should be just a matter of suppressing this message in the install script with --silent flag or similar. We'll get that fixed.

**Comment by r0mant** [comment]
The `--silent` flag support for `teleport node configure` command that suppresses the output has been merged. Once it gets released and the Cloud version endpoint is updated to that release, will follow up with a change to the Discover install script to use this flag (likely, in a week or two).
