### ISSUE TITLE
Not able to update github connector config

### ISSUE THREAD

**Issue by mohandutt134** [gravitational/teleport#2952]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
using `tctl create github.yaml` I created a github connector, it worked fine. Then I needed to change the connector config to add another github group. Using the documentation, I ran the `tctl create` command again with updated github.yaml, it errored out with message: `error: authentication connector "github" already exists`
**What you expected to happen**:
As per the documentation, I expect it to update the connector config.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run teleport server
2. Create github connector
3. Make any change in the config
4. Apply the change.

**Environment**:
- Teleport version (use `teleport version`): Teleport v4.0.3 git:v4.0.3-0-g69c4868b go1.12.1
- Tsh version (use `tsh version`): Teleport v4.0.3 git:v4.0.3-0-g69c4868b go1.12.1
- OS (e.g. from /etc/os-release): VERSION="18.04.2 LTS (Bionic Beaver)"

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools: Docker
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by fspmarshall** [comment]
Overwriting/updating an existing resource requires adding the `-f`/`--force` flag, Ex:
```bash
tctl create -f resource.yaml
```

**Comment by klizhentas** [comment]
@benarent @fspmarshall I feel like it's an opportunity to improve the error message though, should say:

```
error: authentication connector "github" already exists, use -f or --force flag to overwrite
```
