### ISSUE TITLE
Automatically create access requests for Kubernetes access (just like server sessions)

### ISSUE THREAD

**Issue by pnrao1983** [gravitational/teleport#29532]
What would you like Teleport to do?
Automatically create access requests for Kubernetes access (just like server sessions)

What problem does this solve?
Feature Request for Kube access.

If a workaround exists, please include it.
NA

**Comment by tigrato** [comment]
@pnrao1983 `tsh kubectl`  - a fully functional kubectl wrapper -  already supports automatic creation and assumption of resource access requests when the user supports it.

**Comment by tigrato** [comment]
#29562 adds support for automatic resource access requests when `tsh kube login <cluster>` fails.
