### ISSUE TITLE
Initiate login from your identity provider (IdP) 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#2967]
**What happened**:
When you have setup SSO with an identify provider a customer still has to go to the Proxy to initiate the login system. 

**What you expected to happen**:
Once setup, a users should be able to login via Okta, as per our note 

> Teleport only supports sending party initiated flows for SAML 2.0. This means you can not initiate login from your identity provider, you have to initiate login from either the Teleport Web UI or CLI.

![image](https://user-images.githubusercontent.com/559288/64553449-3aad5c00-d2ee-11e9-91a4-661ecffdc1e0.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190134506177097/1190155289310915) by [Unito](https://www.unito.io/learn-more)

**Comment by benarent** [comment]
@aelkugia here is the ticket that we chatted about on Friday based on Customer feedback.

**Comment by kinghrothgar** [comment]
This would be a greatly appreciated feature. All of the apps my company currently uses that support Okta support this.

**Comment by benarent** [comment]
@russjones Could you review this and see what we would do to provide the option for the other flow.

**Comment by benarent** [comment]
Extra notes around the risks of using IdP-Initiated SSO Flow

> In general, it is recommended to use Service-Provided flows whenever available. When an application actively requests an authentication as a first step (as is the case for SP-Initiated flows), it can check that the authentication response matches the original request. In IdP-initiated scenarios, on the other hand, the application can not verify that the user actually started the flow. Because of this, the IdP-Initiated flow opens the possibility of an Login CSRF attack, where an attacker can trick a legitimate user into using a session created by the attacker.

> Login CSRF attacks are generally less of a concern in enterprise-only scenarios, as any would-be attacker would have to come from the same directory of users. But it's definitely a security concern in consumer-facing applications, so we strongly advise against enabling IdP-Inititated flows on SAML connections.

via https://auth0.com/docs/protocols/saml/saml-configuration/special-configuration-scenarios/idp-initiated-sso 

```diff
kind: saml
version: v2
metadata:
  # the name of the connector
  name: new_saml_connector
spec:
  # connector display name that will be appended to the title of "Login with"
  # button on the cluster login screen so it will say "Login with Okta"
  display: Okta
+  idp_initiated_sso: true
+  idp_relaystate: "/web/"
```

**Comment by pschisa** [comment]
One possible workaround for Okta in the meantime is to use bookmark applications for Teleport.  This allows Teleport to show up in Okta as an application.  When selected, you would not be automatically signed in to Teleport, but you would be already signed in to Okta so all a user would have to do is click the Okta connector button once at the Teleport page and they should log in to Teleport without putting in further information.  While not a full integration, it does allow Teleport to show up as an Okta application and only requires one additional click for login securely.

**Comment by klizhentas** [comment]
We have scheduled IdP initiated logins support. ETA  - 2-3 months.

**Comment by benarent** [comment]
This feature is available in https://github.com/gravitational/teleport/releases/tag/v10.1.9
