### ISSUE TITLE
New designs for Houston notifications (expired license or unable to connect)

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#2974]
We need new designs for the following dialogs:

This dialogs display notifications that come from Houston when teleport instance reports its usage.

![image](https://user-images.githubusercontent.com/7816406/64725724-31192500-d4a3-11e9-8b4e-32296e9972c6.png)

![image](https://user-images.githubusercontent.com/7816406/64725828-5efe6980-d4a3-11e9-8dfb-de0d47836d24.png)

![image](https://user-images.githubusercontent.com/7816406/64725894-81908280-d4a3-11e9-8934-bd42183c54d9.png)

**Comment by benarent** [comment]
Link to Spec: https://docs.google.com/document/d/1gMyMYFxPhYSMz9OT_BVCOTKmGPgtcYCOxmQBa9XddCA/edit#

**Comment by alex-kovoy** [comment]
@benarent  any progress on that?

**Comment by benarent** [comment]
I just synced with @alexwolfe , we'll try to get something by this week / Monday by latest.

**Comment by benarent** [comment]
An updated version is here. https://docs.google.com/document/d/1fWhbPvAsBZIG_VTnzFr880a2edB5ffjY96vCIcRnIPw/edit#heading=h.t5r3k52hcrr8
