### ISSUE TITLE
Sign Mac .pkg 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#2979]
**What happened**:
When trying the new .pkg, I get a message that it's from an unidentified developer. We should consider adding a developer ID to the pkg. https://developer.apple.com/developer-id/

![image](https://user-images.githubusercontent.com/559288/64739838-22813c80-d4a8-11e9-89f0-1eee13ddeb49.png)

**What you expected to happen**:
It'll make gatekeeper a little happier, and won't require people to log into settings to open the app. 

We've a few extra steps to signup as an org, https://developer.apple.com/programs/enroll/ but afterwards the process looks pretty simple and we could add to the build process.

**Comment by webvictim** [comment]
This work is done, at least for `tsh`.

Signed packages will be coming out with Teleport 4.2.1.

**Comment by webvictim** [comment]
Signed and notarized client-only `tsh` packages are now available - https://get.gravitational.com/tsh-4.2.1.pkg

This should make the experience on MacOS Catalina much nicer. The package URL is the same for both OSS and Enterprise versions of Teleport, as the `tsh` client does not change between the two.

We should be able to expand this support to providing signed/notarized `teleport` packages for MacOS when we resolve #3158. For now though, I'm going to close this issue.
