### ISSUE TITLE
Stream audit logs to cloud

### ISSUE THREAD

**Issue by Gunni** [gravitational/teleport#29858]
# What would you like Teleport to do?
I would like teleport node to stream the audit logs live to the teleport server, either without using local disk storage or gracefully being able to keep sending them if the disk becomes full.

# What problem does this solve?
We have devices that are deployed into the field, they have strict disk usage quotas for everything, we assigned 1 MB to Teleport but quickly found out that audit logs nom'd that up and Teleport failed to open its database after that.

So after that we added a subvolume for the `log` folder which works but the audit logs can be trivially defeated by someone executing `cat /dev/random` or something similar to fill up the available storage space for audit logs (or the entire disk if you don't have disk quota).

# If a workaround exists, please include it.
Make the subvolume bigger, wasting space that other things could be using.

# Logs Showing Problem
```
teleport[3292]: 2023-08-01T12:42:56Z WARN [UPLOAD]    Failed to close upload. error:[
teleport[3292]: ERROR REPORT:
teleport[3292]: Original Error: trace.aggregate invalid argument
teleport[3292]: Stack Trace:
teleport[3292]:         github.com/gravitational/teleport/lib/events/filesessions/fileasync.go:334 github.com/gravitational/teleport/lib/events/filesessions.(*upload).Close
teleport[3292]:         github.com/gravitational/teleport/lib/events/filesessions/fileasync.go:410 github.com/gravitational/teleport/lib/events/filesessions.(*Uploader).startUpload
teleport[3292]:         github.com/gravitational/teleport/lib/events/filesessions/fileasync.go:251 github.com/gravitational/teleport/lib/events/filesessions.(*Uploader).Scan
teleport[3292]:         github.com/gravitational/teleport/lib/events/filesessions/fileasync.go:206 github.com/gravitational/teleport/lib/events/filesessions.(*Uploader).Serve
teleport[3292]:         github.com/gravitational/teleport/lib/service/service.go:2745 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initUploaderService.func1
teleport[3292]:         github.com/gravitational/teleport/lib/service/supervisor.go:546 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
teleport[3292]:         github.com/gravitational/teleport/lib/service/supervisor.go:281 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
teleport[3292]:         runtime/asm_amd64.s:1598 runtime.goexit
teleport[3292]: User Message: invalid argument] filesessions/fileasync.go:411
teleport[3292]: 2023-08-01T12:42:56Z WARN [UPLOAD]    Uploader scan failed. error:[
teleport[3292]: ERROR REPORT:
teleport[3292]: Original Error: *trace.AccessDeniedError failed to execute command /var/lib/teleport/log/upload/streaming/default/3e5625e4-8f6f-4db9-9557-baa4f715942a.checkpoint error:  disk quota exceeded
```

**Comment by strideynet** [comment]
I'm not sure on the precise details - but I wonder if enabling Recording Proxy mode would meet your needs here (https://goteleport.com/docs/server-access/guides/recording-proxy-mode/)

**Comment by zmb3** [comment]
This is supported today, you want to use `node-sync` recording mode, which doesn't write to disk on the node at all and streams everything directly to auth.

**Comment by Gunni** [comment]
I was unaware of `node-sync`, problem solved 🕺🏻
