### ISSUE TITLE
tsh ssh -D should fail when a port is not specified

### ISSUE THREAD

**Issue by thoefkens** [gravitational/teleport#29856]
Expected behavior:

I expect tsh ssh -D user@host to work. Instead it returns required argument '[user@]host' not provided.
Using tsh ssh -L port:remote_host:port user@host works fine.

Current behavior:
tsh returns required argument '[user@]host' not provided.

Bug details:
Teleport v13.2.3 git: go1.20.6
Proxy version: 13.2.3

**Comment by webvictim** [comment]
I can't recreate this, it seems to work fine on `tsh` v13.1.0 and v13.2.3:

```
gus@apollo:~ % tsh --debug ssh -D 11080 ubuntu@ip-172-31-30-140
...logs trimmed...
2023-08-02T14:57:14-03:00 INFO [CLIENT]    Starting dynamic port forwarding. localAddr:127.0.0.1:11080 client/client.go:1909
...logs trimmed...
ubuntu@ip-172-31-30-140:~$
```

@thoefkens Could you please share a full terminal log of you attempting to run the command with `tsh --debug ssh -D <port> user@host`?

**Comment by webvictim** [comment]
How odd. 

```
gus@apollo:~ % tsh version
Teleport v13.2.3 git:v13.2.3-0-g4785e70 go1.20.6
```

Installed from https://cdn.teleport.dev/tsh-13.2.3.pkg

**Comment by zmb3** [comment]
Yeah, we should probably mark `-D` as `.Required()` though.

**Comment by zmb3** [comment]
Related:
- https://github.com/gravitational/teleport/issues/28761
- https://github.com/gravitational/teleport/issues/28760

**Comment by atburke** [comment]
> Yeah, I see what's happening - we use `StringsVar` for this flag, and its not easy to tell if `-D` was supplied without a value or if it was not supplied at all.

Kingpin correctly reports when `-D` is supplied without a value. The actual issue is that if `-D` (or any flag that takes an argument) is the last flag and it's provided without an argument, Kingpin assumes that the user and host is an argument for `-D` and not the `[user@]host` argument, which is why we get the missing `[user@]host` error. I don't know that this is practically addressable without radically changing how Kingpin does parsing.

**Comment by webvictim** [comment]
Another good case for switching to a different flag parser like [kong](https://github.com/alecthomas/kong)?

**Comment by atburke** [comment]
Same thing happens with kong, I overemphasized Kingpin's role in this 😂. I think that `--flag <arg>` when both a flag argument and a positional argument are expected is just inherently ambiguous.

**Comment by atburke** [comment]
Closed as not actionable.
