### ISSUE TITLE
Emit audit events for Roles, Auth Connectors, Trusted Clusters, and Users.

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#2989]
When a user modifies the following resources:
Roles, Auth Connectors, Trusted Clusters, and Users.

### Roles [enterprise]
- [x] Role added (upsert)
- [x] Role Removed
- [x] Role Modified (upsert)

Hold of per @benarent 
<del> - [ ] Role Escalated </del>

### Auth Connectors
- [x] Auth Connector added (upsert)
- [x] Auth Connector Removed
- [x] Auth Connector Modified (upsert)

### Trusted Clusters 
- [x] Trusted Cluster token created
- [x] Trusted Cluster added (upsert)
- [x] Trusted Cluster removed
- [x] Trusted Cluster modified (upsert)

### Users 
- [x] User added
- [x] User removed (is already emitting, but event user is incorrect, leaving it as is as a next issue)
- [x] User modified 

### Password change
- [x] Upsert password by user (UI)

We need to emit audit events to record the user actions. The first phase is to send these to the Audit Log https://gravitational.com/teleport/docs/admin-guide/#audit-log 

** upserts handles create and update, and is associated with one event type `create`.

**Comment by benarent** [comment]
Assigning to RJ, for when he comes back from vacation. We'll first add these events to the audit log.

**Comment by alex-kovoy** [comment]
@russjones is it scheduled for 4.3 release?

**Comment by alex-kovoy** [comment]
The same events have been added to Gravity an year ago. So I suggest we copy the structure and format from Gravity for consistency.  Here is an original PR -> https://github.com/gravitational/gravity/pull/389/files.
