### ISSUE TITLE
Implement `tctl auth sign --type=openssh` and update docs

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#29901]
## What would you like Teleport to do?

Currently, it isn't possible to sign your own certs from the `openssh` authority inside Teleport (which is used by the proxy to connect to `sshd`-based nodes when using `teleport join openssh`)

This makes it impossible for users who cannot run the `teleport` binary on their servers (think Alpine users, restricted environments) to add their servers using `sshd`. The old method in the <=v12 docs (https://goteleport.com/docs/ver/12.x/server-access/guides/openssh/) issued certs from the `host` certificate authority so was possible without any binary on the node itself. This also allowed an automated approach which is critical for many users.

The new approach gives a much better UX on the client side, but is much less useful to cluster administrators at present.

## What problem does this solve?

Don't force people to copy a `teleport` binary to their servers and provide a manual way to achieve the same thing via automation.

## If a workaround exists, please include it.

None currently.

Related issue: #28730

**Comment by philip-teleport** [comment]
+1

**Comment by webvictim** [comment]
This is also needed for OSes like FreeBSD which we don't provide Teleport binaries for.

**Comment by webvictim** [comment]
Requirement for completion of this ticket would also be to document the manual process for doing this from end to end, similar to that described in the older docs: https://goteleport.com/docs/ver/12.x/server-access/guides/openssh/

**Comment by ptgott** [comment]
@r0mant @capnspacehook Is there a workaround for this?

**Comment by webvictim** [comment]
## Success criteria for this issue

- [ ] there must be a documented, supported way to issue a host certificate from the `openssh` authority for arbitrary nodes
- [ ] there must be a documented, supported way to inject an OpenSSH node into the Teleport backend with `subkind: openssh`
  - [ ] include details on adding, updating and deleting labels for these nodes to be used with Teleport RBAC
- [ ] there must be a documented, supported way to copy the generated key/host certificate onto a server running `sshd` and configure the `/etc/ssh/sshd_config` file to present these
- [ ] there should be a documented, supported way to generate these certificates and add an OpenSSH node using the Teleport Go API (including example client)

**Comment by capnspacehook** [comment]
We had this documented before, could re-add it somewhere. Here's the OpenSSH docs before it was updated to use `teleport join openssh`: https://github.com/gravitational/teleport/blob/8592bfacf468e010abc9f3ec0e2f1af37c640e41/docs/pages/server-access/guides/openssh.mdx

**Comment by ptgott** [comment]
@capnspacehook Should users be able to follow the previous version of the OpenSSH guide as it is now?

I think it would make sense to split up the Server Access "Guides" subsection to include an "OpenSSH" subsection that includes the legacy guide as well as the current guide.
