### ISSUE TITLE
Hide labels starting with `teleport.hidden/` in `tsh` command output as well as the web UI

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#29902]
## What would you like Teleport to do?

Currently, any label starting with `teleport.hidden/` is hidden from the web UI but still used in RBAC evaluation throughout Teleport. This was implemented in https://github.com/gravitational/teleport/pull/19725

These labels do still appear in the output of `tsh` commands like `tsh ls` and `tsh request search` which is surprising. The general expectation is that if a label is hidden, it won't be shown anywhere inside Teleport's client-side tooling (except `tctl get node/<uuid>` which would be expected)

I'm uncertain whether the labels also appear in Teleport Connect at present, but they should not.

## What problem does this solve?

Unification of expectations between web UI and `tsh` tooling.

## If a workaround exists, please include it.

None known.

**Comment by strideynet** [comment]
I tested this issue before and after https://github.com/gravitational/teleport/pull/30079 was merged. It appears this PR has fixed this for both `tsh ls` and `tsh request search`. This refactor has gone into v13 and master for release in v14.

Marking this as closed.
