### ISSUE TITLE
OSS Download link is showing 0B and 404 on download. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#2990]
Linux 64-bit (RHEL5.x compatible) |  Beta 

Is showing 0B, I think this is due to S3 Permissions error. 

 
![image](https://user-images.githubusercontent.com/559288/64979208-16142f80-d86c-11e9-951c-8ea95ccb9a2e.png)
![image](https://user-images.githubusercontent.com/559288/64979271-39d77580-d86c-11e9-8516-af76bfc530cf.png)

**Comment by webvictim** [comment]
Literally just fixed this with https://github.com/gravitational/houston/pull/200 which I've deployed to production. Refresh and I think the 0-byte builds should be gone?

**Comment by benarent** [comment]
ha, Yeah. It's fixed. ✨
