### ISSUE TITLE
Device Trust: The maximum Model Identifier string length is too short

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#29915]
Expected behavior:

Device Trust enrolment should cater for longer Model Identifier string lengths; the current maximum string length of 40 characters is too short.

Current behavior:

When you run `tsh device collect` on a Windows laptop, you can see the following: `"model_identifier":  "HP ZBook Fury 17.3 inch G8 Mobile Workstation PC"`

And then when trying to enrol the laptop with `tsh device enroll` , you get: `ERROR: rpc error: code = InvalidArgument desc = model identifier exceeds 40 characters`

Bug details:
- Teleport version: 13.2.x

**Comment by codingllama** [comment]
The fix should land in the next v13 patch.
