### ISSUE TITLE
Reconsider "version warning" `Details` boxes

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#29913]
## Applies To

Run this command from your `gravitational/teleport` clone to see the pages/lines this applies to:

```
$ grep -Rni 'title="version warning"' docs/pages
```

## Details

A number of pages use a `Details` box to indicate a version warning similar to this:

<img width="880" alt="image" src="https://github.com/gravitational/teleport/assets/25250668/c1eaf17f-02f3-4dc9-93ed-faa70f3387da">

The issue with this approach is that the `Details` box is intended to show or hide information through user interaction.

If the box is closed by default and specifies a version in the title, a reader will see the the required version, then see it _again_ when they open the box. If there is no required version in the title, the step to open the box only adds unnecessary interaction. If the box is opened by default, there's no reason a reader would ever close it, and no reason to use a `Details` box.

## How will we know this is resolved?

We have:
- Replaced all "version warning" `Details` boxes with a more appropriate component, e.g., a `Notice` or `Admonition`
- (optional) Opened an issue in `gravitational/docs` proposing a UX change or linter to ensure consistency in our version warnings

**Comment by lsgunn-teleport** [comment]
I think this belongs in the "Before you begin" (currently "Prerequisites") section.
