### ISSUE TITLE
AWSoidc error when trying to add a Aurora MySql/Mariadb Database

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#29974]
Expected behavior:
Being able to see and add the database in AWS regions for Aurora MySql/Mariadb databases

Current behavior:
Get an error in the attached screenshot when selecting an AWS region.
<img width="862" alt="Screenshot 2023-08-03 at 9 52 08 AM" src="https://github.com/gravitational/teleport/assets/51385814/64cc3adb-03c5-42e0-b3e1-f5934fdf9ca1">

Bug details:
- Teleport version: v13.2.1
- Recreation steps
- Debug logs

**Comment by marcoandredinis** [comment]
`aurora` engine identifier is not a valid engine in some regions
We must ensure that the API calls here https://github.com/gravitational/teleport/blob/1d2244f2b9066a905f413cfc6d7a1e1021b3a452/lib/integrations/awsoidc/listdatabases.go#L104
re-use the same logic that was developed to handle this error in database auto-discovery
https://github.com/gravitational/teleport/blob/1d2244f2b9066a905f413cfc6d7a1e1021b3a452/lib/srv/discovery/fetchers/db/aws_rds.go#L257-L282

**Comment by greedy52** [comment]
```
$ aws ec2 describe-regions | jq -r .Regions[].RegionName | xargs -I {} aws rds describe-db-clusters --filters Name=engine,Values=aurora --region {}
```
I have tried this in our dev, CN, US Gov account, and `aurora` is unrecognized for all of them. Our dev account doesn't have all regions enabled but I doubt those regions will be different. So an alternative is just remove the legacy `aurora` engine type
