### ISSUE TITLE
Document hosted plugins

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#29979]
## Applies To

Access Requests: `/docs/access-controls/access-request-plugins/`
Jamf: `/docs/access-controls/device-trust/jamf-integration/`
Okta: `/docs/access-controls/sso/okta/`

## Details

We are introducing hosted support for Teleport plugins, and should reflect this in the documentation.

## How will we know this is resolved?

We have:
1. Come up with a plan for documenting hosted plugins
1. Documented each of the plugins below:
    
    |Plugin|PR|
    |---|---|
    |Slack|`private#2116`|
    |Opsgenie|`private#2116`|
    |PagerDuty|`private#2116`|
    |Jamf Pro|`private#2116`|
    |Okta||
    |Mattermost|`private#2116`|
    |Jira|`private#2116`|
    |Discord|`private#2116`|
    |~Ms Teams~|~No plans to make this hosted. Create a new issue when this changes.~|
    |ServiceNow||

## Related Issues

- https://github.com/gravitational/teleport/issues/32847
- https://github.com/gravitational/teleport/issues/32519

**Comment by ptgott** [comment]
## Options for documenting hosted Access Request plugins

### Option 1: Leave most of the work to the Web UI

When a user enrolls a hosted Access Request plugin via the Web UI, the Web UI
currently presents a form to configure the plugin. This also includes a description of the
plugin. We can add instructions to this view for setting up the relevant communication
platform instead of linking to the docs.

Then, on the menu page of the "Access Request Plugins" section of the docs,
indicate that the Web UI includes instructions for setting up Access Request
plugins, and that the docs focus on self-hosted plugins.

The advantage of this approach is that hosted Access Request plugin users do not
need to stumble across our documentation for self-hosting. The disadvantage is
the time it would take to edit the Web UI in a way that would provide a good UX.

### Option 2: Edit our existing guides

In each of our current Access Request plugin guides:

- Edit the "install the plugin" step to include a separate tab for the hosted
  plugin, indicating how to enroll the plugin via the Web UI. We could also put
  this information in the "Configure" section instead.
- For sections that are only relevant to self-hosted plugins, add a note indicating that 
  the section isn't necessary in Teleport Cloud.

The advantage of this approach is that we can complete it quickly. Users
following the docs would find the information they needed, albeit with a clunky
UX.

The downside of this approach is that a user who wants to use hosted plugins
must wade through irrelevant information on self-hosting the plugin, which makes
the process seem far more complex than it is.

### Option 3: Split up the Access Request plugin guides

Each Access Request plugin guide has a nearly identical set of steps. The only
step that differs between the guides is the one to set up the communication
platform.

We could take advantage of this and restructure the "Access Request Plugins"
section of the docs to make it easier to document hosted plugins. The structure
of the section would look like this:

- **Introduction**: explains what Access Request plugins are and describes each
  step in the process of setting the up at a high level, linking to the pages
  below.
- **Set up RBAC for Access Request plugins**: a how-to guide for setting up RBAC
  for Access Request plugins, i.e., the requirements for defining roles. There
  wouldn't be any information here that is not already in other guides, but we
  could use this to focus the reader.
- **Configure your platform**: the model for this guide would be the [GUI client guide
  for database access](https://goteleport.com/docs/connect-your-client/gui-clients/). Each H2 would be the name of a communication platform.
  The guide would tell a reader how to configure their platform to, for
  example, create an API key.
- **Self-host your Access Request plugin:** How to run a plugin on your own
  infrastructure, including how to obtain an identity file. This would include
  configuration instructions.

The advantage of this approach is that users can quickly navigate to the
instructions they need, since the docs would be better signposted for different
parts of the process. 

This is also easy to accomplish, since it consists mostly of moving around
existing information, with most of the new content appearing in a new
"Introduction" page.

The disadvantage is that users still need figure out which instructions apply to them.
It also might be more confusing to navigate across different guides than to screen
out irrelevant instructions within a single guide.

**Comment by xinding33** [comment]
I prefer Option 1 for hosted plugins because it removes dependency and external linking. For something like this, I would expect for users to not have to navigate away from the UI.
