### ISSUE TITLE
tsh login always appends port 3080 to proxy URL

### ISSUE THREAD

**Issue by smoll** [gravitational/teleport#2997]
**What happened**:

I am using the Helm Chart https://github.com/gravitational/teleport/tree/master/examples/chart/teleport and have enabled ingress with TLS. Nginx-ingress only exposes 2 ports: HTTP over 80 and HTTPS over 443, and I can successfully visit and log into the web login UI at https://teleport.mywebsite.com

However, when I run `tsh login --proxy=teleport.mywebsite.com --auth=github login`

I get
```
error: Get https://teleport.mywebsite.com:3080/v1/webapi/ping/github: dial tcp 
12.34.56.78:3080: connect: connection refused
```

While `https://teleport.mywebsite.com:3080/v1/webapi/ping/github` does not resolve, `https://teleport.mywebsite.com/v1/webapi/ping/github` displays a valid JSON response as expected.

**What you expected to happen**: for tsh to connect to `https://teleport.mywebsite.com` (port 443)

**How to reproduce it (as minimally and precisely as possible)**: Install teleport helm chart into a Kubernetes Cluster, enable ingress, and attempt to connect to it via teleport installed on another machine.

**Environment**:
- Teleport version (use `teleport version`): Teleport v4.0.8 git: go1.13
- Tsh version (use `tsh version`): Teleport v4.0.8 git: go1.13
- OS (e.g. from /etc/os-release): macOS 10.14

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by klizhentas** [comment]
You need to set proxy`s public_addr section and add the desired port there to fix this problem.
