### ISSUE TITLE
Include troubleshooting information in agent service Getting Started guides

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#29989]
## Applies To

`/docs/*-access/getting-started/`, except for `/docs/database-access/getting-started/`. This includes the Server Access, Application Access, Kubernetes Access, and Desktop Access guides.

## Details

Add a "Troubleshooting" section to each guide with common errors that users might face even though they have:
- Set up the Prerequisites properly
- Followed each step in the guide

## How will we know this is resolved?

Each guide listed above includes a "Troubleshooting" section.

**Comment by lsgunn-teleport** [comment]
- [ ] Application Access doesn't have a troubleshooting section.
- [ ] Server Access doesn't have a troubleshooting section.
- [ ] Database Access has a troubleshooting section.
- [ ] Desktop Access guides has a troubleshooting section.
- [ ] Kubernetes Access has a troubleshooting section.
