### ISSUE TITLE
`TestTeleterm/Test_headless_watcher` flakiness

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#30044]
https://github.com/gravitational/teleport/actions/runs/5763608694/job/15625793973
```
=== FAIL: integration TestTeleterm/Test_headless_watcher (1.07s)
    teleterm_test.go:88: 
        	Error Trace:	/__w/teleport/teleport/integration/teleterm_test.go:304
        	            				/__w/teleport/teleport/integration/teleterm_test.go:88
        	Error:      	Condition never satisfied
        	Test:       	TestTeleterm/Test_headless_watcher
```

**Comment by zmb3** [comment]
Another failure here: https://github.com/gravitational/teleport/actions/runs/5763778752/job/15626319154

**Comment by zmb3** [comment]
I noticed a couple things that might be causing issues.

- a timeout of 100ms is probably too short
- we are calling `require.NoError` inside of an eventually. This is not allowed.
- we are calling a nested `assert.Eventually` inside of a `require.Eventually` - I'm not sure if this is valid, but even if it is, it's pretty hard to reason about.

**Comment by Joerger** [comment]
> * a timeout of 100ms is probably too short

It looks like this is the cause. Extending this to seems to resolve the flakiness.

> * we are calling `require.NoError` inside of an eventually. This is not allowed.

My mistake, this should be `assert.NoError`. FWIW it's not causing the flakiness though.

> * we are calling a nested `assert.Eventually` inside of a `require.Eventually` - I'm not sure if this is valid, but even if it is, it's pretty hard to reason about.

We are using `require.EventuallyWithT`, which does support nesting asserts, including `assert.Eventually`. Otherwise, I'd have to use some custom retry logic to replicate the internal `assert.Eventually`.

**Comment by zmb3** [comment]
@Joerger this is still flaking in v13: https://github.com/gravitational/teleport/actions/runs/5952928736/job/16145995939

```
=== CONT  TestTeleterm/Test_headless_watcher
    teleterm_test.go:81: 
        	Error Trace:	/__w/teleport/teleport/integration/teleterm_test.go:285
        	            				/__w/teleport/teleport/integration/teleterm_test.go:81
        	Error:      	Condition never satisfied
        	Test:       	TestTeleterm/Test_headless_watcher
```

**Comment by zmb3** [comment]
FYI @Joerger just got another v13 hit: https://github.com/gravitational/teleport/actions/runs/6174853204/job/16760396710
