### ISSUE TITLE
Concurrent Session control

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3005]
## Proposal: 
For our customers currently undergoing FedRAMP, they required control over [AC-10 Concurrent Session Control](https://docs.google.com/document/d/11LnPljqQqlrx8kIRQUxvR6bY5YscaKJohGqeAmfuuco/edit#). 

> For example, organizations may limit the number of concurrent sessions for system administrators or individuals working in particularly sensitive domains or mission-critical applications. This control addresses concurrent sessions for information system accounts and does not address concurrent sessions by single users via multiple system accounts.

[Advanced Session Control - Public](https://docs.google.com/document/d/11LnPljqQqlrx8kIRQUxvR6bY5YscaKJohGqeAmfuuco/edit#)

**Comment by benarent** [comment]
I'm doing to close this issue as we had a duplicate ticket. I've exported the content to https://github.com/gravitational/teleport/issues/2938
