### ISSUE TITLE
Naming convention - adopt root/leaf for trusted clusters

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3007]
## Description

In our trusted clusters set up and the documentation, we use term `trusted clusters`, but we also need a term for different sides of the trust.

Right now we alternate between `trusted/trusting/remote/main` clusters terminology which is confusing. 

We can adopt a networking/graph theory term of `root/leaf` clusters:

`root` cluster is the cluster that is being trusted by all remote, `leaf` clusters.

**Comment by benarent** [comment]
Updated reference in the docs, we should also review the CLI to make sure we're not missing anything.
