### ISSUE TITLE
Provide reference deployment for multiple datacenters

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3008]
## Description

There are multiple ways to deploy a multi-datacenter and multi-region cluster and common challenges. 

We usually recommend to deploy a cluster per region, and use a designated cluster as a login endpoint. 

To pair this with DNS aware resolution, it is possible to make sure folks are logging in only once, but use the closest proxy to access the server, providing an invisible fabric.

However the UX of this is not polished and the documentation is lacking.

**Comment by klizhentas** [comment]
More notes:

* `root` cluster is used by everyone to log in
* `leaf` clusters could be used with `root` cluster's credentials directly:

```
1. tsh login --proxy=root
2. tsh -J leaf ssh --cluster=leaf -A root@node-on-leaf-cluster
```
This allows folks to login in `root` cluster somewhere in `US` and assuming that `leaf` trusts `root`, go directly to the proxy of the `leaf` that is located in `EU` to avoid latency issues.

It would be also cool if `tsh` would be smart enough to pick the right proxy based on the cluster name itself with a certain mode.

**Comment by ptgott** [comment]
@klizhentas The closest thing we have to this now is the general High Availability guide (https://goteleport.com/docs/deploy-a-cluster/high-availability/). Should we edit that guide to include more information? 

Also, it's been a few years since this issue was opened. Do we still recommend Trusted Clusters for multi-region deployments?

Thanks!

**Comment by ptgott** [comment]
@klizhentas We now have a multi-region deployment guide for AWS: https://goteleport.com/docs/deploy-a-cluster/deployments/aws-gslb-proxy-peering-ha-deployment/

Does this guide meet the requirements of this issue?

Thanks!

**Comment by ptgott** [comment]
@hugoShaka Does the [multi-region blueprint](https://goteleport.com/docs/deploy-a-cluster/multi-region-blueprint/) resolve this?

**Comment by hugoShaka** [comment]
This describes how to build one giant multi-region Telepeort cluster but does not describe how to create independent federated root/leaf.

I think there's still value in documenting a standard multi-DC setup with root/leaf relations but I guess we can close this issue and open a new one.
