### ISSUE TITLE
Teleport auth not working with FreeOTP android app

### ISSUE THREAD

**Issue by pgier** [gravitational/teleport#30084]
Expected behavior:
I should be able to scan the generated QR code with FreeOTP and use that for my two factor authentication.

Current behavior:
When I try to scan the generated QR code in FreeOTP I get the error message: ""Token is Invalid! The token you are attempting to add is invalid. Please alert your token provider."

Bug details:
- Teleport version v12.4.12
- Recreation steps - create a new user and try to scan the QR code with FreeOTP

I'm not sure if this is an issue with teleport or with FreeOTP.  I believe it was working with an older version of FreeOTP, see also: https://github.com/freeotp/freeotp-android/issues/293

**Comment by zmb3** [comment]
Closing as not planned - TOTP is not an area we're planning to invest more engineering time in. It will likely be deprecated in the next major release.
