### ISSUE TITLE
Session playbacks appear to "load infinitely" when recording is turned off.

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport#3009]
When session recording is turned off, clicking the `play` button in the teleport UI takes you to an infinite loading screen.  It would probably be nice to either have unrecorded sessions show a "greyed out" play button, or alternatively to simply present an error indicating that the recording is unavailable for playback.

**Comment by klizhentas** [comment]
@benarent we figured it might be something you can discuss with Alex as we redesign the UI anyways

**Comment by alex-kovoy** [comment]
I quickly looked at the issue and I found that session `start` event is missing for a given session. So it fails while trying to normalize the rest of this session events. See below.

![image](https://user-images.githubusercontent.com/7816406/65360099-9cae7100-dbcc-11e9-8605-77239320aef2.png)

**Comment by alex-kovoy** [comment]
My bad, the session start event is actually there, disregard that comment.

**Comment by klizhentas** [comment]
@alex-kovoy this is specifically about the case when session is not being recorded.

**Comment by atburke** [comment]
Addressed by gravitational/webapps#368.
