### ISSUE TITLE
Provide more tsh/profile context when showing error messages. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3010]
**What happened**:
As I've been testing tsh across a range of machines, I have a found that I've different tsh profiles, my default usage is I first fire up `tsh`, depending on how Teleport is setup it can do a range of things. Since my home machine was setup using the quickstart teleport, it's looking for my localhost.  

```
➜  ~ tsh ls
error: dial tcp [::1]:3023: connect: connection refused
➜  ~ tsh login
error: Get https://localhost:3080/v1/webapi/ping: dial tcp [::1]:3080: connect: connection refused
➜  ~ .tsh
➜  .tsh ls
cache          keys           known_hosts    localhost.yaml profile
➜  .tsh cat profile
web_proxy_addr: localhost:3080
ssh_proxy_addr: localhost:3023
user: benarent
```

**What you expected to happen**:
Add more meta data to error messages.

```
➜  ~ tsh ls
error: dial tcp [::1]:3023: connect: connection refused for benarent on localhost:3080 
➜  ~ tsh login
error: Get https://localhost:3080/v1/webapi/ping: dial tcp [::1]:3080: connect: connection refused for user benarent
```

**Comment by Joerger** [comment]
Should all tsh errors have this meta data, or just login/connection errors like the ones in the issue? I'm not sure exactly where to insert this change.

**Comment by zmb3** [comment]
This issue doesn't quite have enough info to be actionable and is so old the behavior has probably changed anyway. Feel free to file a new issue with more details on exactly what the current behavior is versus the behavior you'd expect and we'll take a fresh look.
