### ISSUE TITLE
sessionRecording: "off" helm value causes error

### ISSUE THREAD

**Issue by aardbol** [gravitational/teleport#30131]
Expected behavior:
`sessionRecording: "off"` helm value for teleport-cluster translates into teleport config `session_recording: "off"` properly

Current behavior:
Translates into `session_recording: false` because the value is not quoted: https://github.com/gravitational/teleport/blob/1de5baf20588b05e0b6d2cde9965b88ca43cb07b/examples/chart/teleport-cluster/templates/auth/_config.common.tpl#L52

Error: `ERROR: session recording mode must be one of node,proxy,off,node-sync,proxy-sync; got "false"`

Works: `sessionRecording: "'off'"` but that's a hack

Bug details:
- Teleport version v12.4.14
- Recreation steps
- Debug logs

**Comment by avivgold098** [comment]
We experience this bug as well
