### ISSUE TITLE
Upgrade Banner is working. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#30134]
Expected behavior:
I upgraded to 13.3.1, but I'm seeing the below banner. We shouldn't show this banner if the system is updated. 

Current behavior:
<img width="548" alt="image" src="https://github.com/gravitational/teleport/assets/559288/ded4d295-de61-4bc6-94c4-c2e697aaa07e">

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
This will go away in a few minutes after the alert expires.

**Comment by benarent** [comment]
> few minutes after the alert expires.

It's been at least 10 minutes, and I still see the banner.

**Comment by benarent** [comment]
ack, it's gone now.
