### ISSUE TITLE
Security Review of GCP Backend

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3015]
The new GCP backend introduced in https://github.com/gravitational/teleport/pull/3014 needs a security review before cutting 4.2.

At the minimum session upload needs to be checked that it doesn't clobber an existing session recording.

**Comment by awly** [comment]
Notes from review:
- session upload could indeed overwrite a previous upload
- `lib/backend/firestore` key escaping could lead to data corruption by mapping different teleport keys to the same firestore documentIDs
- some minor bugs like unhandled errors, possible nil pointer dereferences, missing connection/resource cleanup
- some stylistic problems (that aren't bugs)

Sent https://github.com/gravitational/teleport/pull/3766 to fix all found problems, except for stylistic ones.
