### ISSUE TITLE
TunClient should check AuthServer's host keys

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#302]
## Description

Currently TunClient does not check AuthServer's signatures. It is understandable when we provision the first node, however this should not be the case on subsequent connects.

In addition to that it is now possible to supply trusted host authorities to Host on first start, so it wil use that information to connect and check host signature

## How success looks like
- [ ] TunClient should check host cert whenever it's possible

## Proposal

[ev]: we should consider switching to a simple HTTPS for the Auth server endpoint. This way the machinery of validating host identity is well-understood, cheap to implement and document.

**Comment by kontsevoy** [comment]
Dupe of #1342
