### ISSUE TITLE
`TestRollback` `TestManualRotation` `TestAutoRotation` flakiness

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#30253]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/5805551202/job/15736836341

#### Relevant snippet

```
    tls_test.go:686: 
        	Error Trace:	/__w/teleport/teleport/lib/auth/tls_test.go:686
        	Error:      	Error "write tcp 127.0.0.1:43040->127.0.0.1:34821: write: broken pipe" does not contain "certificate"
        	Test:       	TestRollback
```

**Comment by GavinFrazar** [comment]
@codingllama @jakule I think this is related to our test patch for v1.21 bump the other day, but I'm not sure how

**Comment by jakule** [comment]
Here is a proper patch https://github.com/gravitational/teleport/pull/30220, except this one exposed some issue in a Kube test. 
I'll take a look at the `TestRollback` tomorrow.

**Comment by codingllama** [comment]
Thanks, Jakub.

**Comment by GavinFrazar** [comment]
these tests flake fairly regularly now

**Comment by GavinFrazar** [comment]
https://github.com/gravitational/teleport/actions/runs/5810988376/job/15753173546?pr=30221

AutoRotation again:
```
    tls_test.go:418: 
        	Error Trace:	/__w/teleport/teleport/lib/auth/tls_test.go:418
        	Error:      	Error "write tcp 127.0.0.1:42184->127.0.0.1:41055: write: broken pipe" does not contain "certificate"
```

**Comment by zmb3** [comment]
Another `TestRollback` failure: https://github.com/gravitational/teleport/actions/runs/5856748348/job/15877150371

**Comment by GavinFrazar** [comment]
@codingllama oh, I didn't see that the tests were disabled. I was going through old issues I created and saw this one had no reports of flakiness in over a year.

**Comment by GavinFrazar** [comment]
ah, looks like that skip commit was never merged actually, it's just an orphaned commit that linked this issue.

The tests are not skipped on master, so I'm going to leave this closed.
