### ISSUE TITLE
Add CTA's for enterprise features in OSS

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#30250]
We want to surface enterprise features in OSS Teleport similar to how Teleport Team plan does it and present users with an "upgrade to Enterprise" CTA that points them to our contact sales page with an appropriately attached UTM code signifying that the contact request originated from OSS.

Examples from Teleport Team cluster:

## Access requests

<img width="1541" alt="Screenshot 2023-08-09 at 4 39 28 PM" src="https://github.com/gravitational/teleport/assets/339322/20d5fee2-7ef2-4033-85d6-6a97363082f4">

## OIDC/SAML connectors

<img width="1541" alt="Screenshot 2023-08-09 at 4 40 02 PM" src="https://github.com/gravitational/teleport/assets/339322/beee9d36-bc66-4c90-8045-f79d1b3ec598">

## Device trust

<img width="1541" alt="Screenshot 2023-08-09 at 4 40 28 PM" src="https://github.com/gravitational/teleport/assets/339322/0b226e4d-2fe2-48a4-ae27-da241daceeac">

## Others

* Moderated sessions (don't have a screenshot).
* Hosted plugins and Okta integration (need to get design from @roraback as they're enabled in Team).

**Comment by zmb3** [comment]
Device Trust is addressed in #30249

**Comment by xinding33** [comment]
@r0mant Looks good. The only other thing to note is clarifying the CTA links. For example, the SSO CTA in Teleport Team points to this link: https://goteleport.com/r/upgrade-team?e_13.3.2&utm_campaign=CTA_AUTH_CONNECTOR. For OSS, we should use https://goteleport.com**/r/upgrade-community**?e_13.3.2&utm_campaign=CTA_AUTH_CONNECTOR. More information here: https://gravitational.slab.com/posts/utm-parameters-1rlklvez#h9tgh-in-product-ut-ms.

**Comment by sshahcodes** [comment]
@xinding33 Following your suggestion above, I have updated the link to be `upgrade-community` in oss in [#30249 ](https://github.com/gravitational/teleport/pull/30249/files#diff-a26dd76949ce1c0eb42a205242cf8e26bfe7bce59d40aca2995640bf223e247f)

**Comment by zmb3** [comment]
Closing this in favor of gravitational/cloud#5598

(cc @r0mant @jimbishopp @michellescripts)
