### ISSUE TITLE
G Suite OIDC instructions in documentation are outdated

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3028]
**What happened**: A customer has reported that trying to use the documentation to set up G Suite with Teleport via OIDC is hard because the docs and screenshots are out of date.

**What you expected to happen**: Docs and screenshots should be up to date.

**How to reproduce it (as minimally and precisely as possible)**: Try to set up OIDC using G Suite with the docs at https://gravitational.com/teleport/docs/ssh_gsuite/

Screenshot from docs: 

![image (1)](https://user-images.githubusercontent.com/897821/65786042-25c52b00-e12c-11e9-99cc-b8a12305ab11.png)

Screenshot from Google now: 

![image (2)](https://user-images.githubusercontent.com/897821/65786051-29f14880-e12c-11e9-9671-6f8612741460.png)

We also need to make sure that the correct redirect URL is explicitly specified.

**Comment by adityachandra-zt** [comment]
Please can you guys update documentation and advise us exact steps, we have been grappling with this issue for past 45 days, and tried signup trial account 3 times.

**Comment by webvictim** [comment]
The documentation has now been updated - there's a video describing the whole G Suite setup process from start to finish.
