### ISSUE TITLE
Feature Request: add ability to update node/resource labels via teleport backend

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#30369]
### What would you like Teleport to do?

A request for Teleport to facilitate the updating of node or other resource labels from the backend is proposed. The mechanism should allow modification node or resource labels via GUI, CLI, or both.

### What problem does this solve?

The current process involves doing label updates on individual nodes. This results in an extensive overhead when dealing with a high number of nodes. Backend-facilitated label updating mitigates this problem.

### If a workaround exists, please include it.

Custom scripting, ansible, config management, or other systems to make changes on a large number of teleport.yaml files across nodes.

**Comment by zmb3** [comment]
There's a few duplicates of this already - most recently #19257.

Not an easy change due to the way heartbeats work in Teleport.
