### ISSUE TITLE
Improve Device Trust CLI / Desktop UX

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#30386]
I went through the trusted device docs and set up the device in the Teleport Team cloud plan. Unfortunately, I could not make it work.

Let's work on improving UX for the flow:

* The role `device-admin` is standard, any cluster would need it. Why ask users to create it, let's make it a preset. 
* The `tctl devices add` can be improved. It can detect `macos` on its own and get the `asset-tag` by calling `ioreg` on it's own.
* The same applies to `tctl devices enroll`. Why can't it get asset tag on it's own?

Most importantly, 

* Add a feature to enroll device to Teleport Connect as well. If Teleport connect is already running on a user computer, can we bypass the token completely and `push` the enrollment to a user? Why can't Teleport Connect heartbeat the inventory of devices back? 
* Right now there is no way to register a device for non-cli users?

I did not get past through the enroll step, I got the following error:

```
ERROR: binary missing signature or entitlements, download the client binaries from https://goteleport.com/download/
```

I made sure I installed teleport via official `pkg` installer:

```
tsh version
Teleport v13.3.2 git:v13.3.2-0-gfc60440 go1.20.7
Proxy version: 13.3.2
```

* Finally, the most important part - the enforcement of trusted devices is hidden in the final section after `windows` section 

https://goteleport.com/docs/access-controls/device-trust/guide/?scope=enterprise#optional-cluster-wide-trusted-device-enforcement

We should have a wizard that helps admin to turn on role-based enforcement in the UI.

**Comment by zmb3** [comment]
> The role device-admin is standard, any cluster would need it. Why ask users to create it, let's make it a preset.

Agree, this sounds like a good idea. Let's do it.

> The tctl devices add can be improved. It can detect macos on its own and get the asset-tag by calling ioreg on its own.

Inventory management is done by a cluster administrator, not by the end user. This means most invocations of `tctl devices add` would be to enroll someone else's device, not your own.

We could make these fields optional and default to registering the current device if they are not specified.

> The same applies to tctl devices enroll. Why can't it get asset tag on its own?

Similarly, `tctl devices enroll` is more geared towards an administrator enrolling a device on behalf of someone else. If you want users to enroll their own devices, they would probably use `tsh device enroll` instead, which does not require them to specify an asset tag (or you would just enable auto enrollment so they don't have to think about it).

Similar to `tctl devices add` we can decide to interpret missing fields as "enroll the current device" - I'm just not sure if we want to do that.

**Comment by codingllama** [comment]
@klizhentas, quoted replies below.

> The role device-admin is standard, any cluster would need it. Why ask users to create it, let's make it a preset.

FYI, the editor role has the necessary powers to administer devices on new clusters.

The idea of `device-admin` in the docs was to illustrate the necessary permissions, but I can add the preset too if you prefer that.

> The tctl devices add can be improved. It can detect macos on its own and get the asset-tag by calling ioreg on it's own.
> The same applies to tctl devices enroll. Why can't it get asset tag on it's own?

What Zac said. Let me know if you want it done, it's easy enough to do.

> Add a feature to enroll device to Teleport Connect as well. If Teleport connect is already running on a user computer, can we bypass the token completely and push the enrollment to a user?

Auto-enrollment should work just fine with Connect. "Bypassing the token" is, in a way, what auto-enrollment does (it issues a token automatically, but in practice you don't see it).

If you mean that we should have a Connect-exclusive bypass, that isn't auto-enrollment, then we'd need to look into it more carefully.

> Why can't Teleport Connect heartbeat the inventory of devices back?

Connect can query the device inventory, I don't see why not.

> Right now there is no way to register a device for non-cli users?

No, we never pursued registration in the Web UI. (Just confirming the question.)

> I did not get past through the enroll step, I got the following error:

I don't like the installer situation either. My long-standing proposal to solve it is #14006.

> Finally, the most important part - the enforcement of trusted devices is hidden in the final section after windows section

We can change the flow of the docs, move RBAC and cluster-wide enforcement up top and the recommended TPM section further down. Would that make it less hidden?

**Comment by zmb3** [comment]
> I don't like the installer situation either. My long-standing proposal to solve it is https://github.com/gravitational/teleport/issues/14006.

FYI, I included this in the list for Q3 and we green-lit this work for the tools team. It will be resolved this quarter.

**Comment by zmb3** [comment]
WDYT @codingllama - good to close this one? Other than the pending docs PR I think we addressed everything we said we would.

**Comment by codingllama** [comment]
Sure, happy to close.
