### ISSUE TITLE
Build Mac package containing Teleport client only

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3040]
We've had a request for a Mac package which only contains the client. We should build one and publish it alongside all our other images.

**Comment by benarent** [comment]
@webvictim There is also a case for making tctl as a client package, which would leverage this feature. https://github.com/gravitational/teleport/issues/3018

**Comment by webvictim** [comment]
You’re never going to please everybody though - the people who just want `tsh` will be wondering why there’s still an extra binary. Plus,`tctl` has separate OSS and Enterprise binaries which would double the number of packages for download.

I can just about get on board with packaging `tsh` separately because it’s a client. I think everything else just has to stay in the other package otherwise we’re going to end up confusing people with what they need to download.

**Comment by benarent** [comment]
After a weekend of RnR, I think short term starting with tsh is a good idea. We've many more end users of `tsh` than Teleport and we should make their experience as smooth as possible.

**Comment by webvictim** [comment]
This was done in https://github.com/gravitational/teleport/pull/3159
