### ISSUE TITLE
Support include directive in Teleport config file

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3042]
**What happened**: Teleport's config file is monolithic and doesn't allow includes.

**What you expected to happen**: It would be nice if Teleport supported an `include` directive in the main config file which could be used either for including extra files by specifying their path, or perhaps to include all of a certain file type within a directory (for example `/etc/teleport.d/*.conf`)

This should fit with the standard YAML syntax used elsewhere in the file and take a list of files which should be included.

Example:
```
include:
  - proxy.conf # (relative include, looking in the same directory as the config file by default)
  - /etc/teleport/auth.conf # (specify a full path)
  - /etc/teleport.d/*.conf # (include all .conf files in /etc/teleport.d)
```

**Comment by webvictim** [comment]
From #4997:

Copied from [community](https://community.goteleport.com/t/add-the-ability-to-use-includes-in-teleport-yaml/892)

With the upcoming release of 5.0 and Applications, teleport.yaml could become very unwieldy if dozens, or even hundreds of web apps are added to the config.

It would be useful to have individual includes in teleport.yaml, or a /etc/teleport.d include directory rather than a single monolithic file.

This could also allow for modularization of teleport, app, proxy, auth sections in a /etc/teleport.d where /etc/teleport.yaml has a single line such as
includedir: /etc/teleport.d

**Comment by jryberg** [comment]
Is there any kind of support for include directive yet? It's very usable feature.

It would also be great if malformed includes are ignored so teleport starts but maybe don't include an application and not just stops working all together that's happening now... cutting the branch you are standing on

**Comment by webvictim** [comment]
While not a direct solution to the issue, you can `teleport configure --test <path>` to do basic linking on a full configuration file if needed. This can catch many syntax/formatting issues before they become a problem.

**Comment by zmb3** [comment]
No significant traction in 4.5 years, so marking not planned.
