### ISSUE TITLE
virus/malware scanning for files transferred via tsh scp

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#30428]
What would you like Teleport to do?
In terms of security, the integrity of file transmissions with `tsh scp` relies more on the secure SSH protocols and permissions management to ensure securely copying the files.  When `tsh scp` is used, It would be nice to have files scanned for viruses and malware on the teleport proxy or via ICAP protocol. 

What problem does this solve?
Improve security for file transfer. 
Files unscanned just transmitted to the target server could be infected by a malware and could authenticate and then the malware could start uploading.

**Comment by T5wxnxWgbJF6** [comment]
This request isn’t about Teleport performing malware scans directly; it’s about enabling third-party malware scanners to inspect file uploads, such as through an ICAP interface. Server-based antivirus solutions are often impractical, so having the capability to scan at the perimeter layer would be extremely valuable. Please reconsider reopening this feature request.
