### ISSUE TITLE
Teleport Web Terminal can crash on heavy console output

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#30436]
### Expected behavior:

The Teleport web shell should handle even very large amounts of output.

### Current behavior:

A customer was monitoring a long-running process that produces heavy output. After a while, their chrome tab crashed with the "Aw Snap" error.

I was able to reproduce this by doing the following steps:

* connect to an ubuntu VM in the web shell
* right click on the tab and choose "duplicate". Drag the new tab to be a new window. I did this twice so I had a total of three visible copies of the web session. (likely not critical for reproducing the error)
* I opened the Chrome task manager by choosing the three dots->more tools->task manager.
* In the web session, I ran `cat /dev/random | base64 -w 0`.
* In the task manager, I observed the chrome process for the three tabs slowly started consuming more and more memory.
* Once it got up to about 2.5 or 2.8 GiB, all three tabs simultaneously showed the "Aw Snap" page, and said that it had experienced "error 5".

### Bug details:
- Teleport version - 13.3.2
- Recreation steps - 
- Debug logs - n/a

Google Chrome 115.0.5790.170 on macos (x86_64) - 16-inch 2019 Macbook Pro (2.6 GHz 6-Core Intel Core i7, AMD Radeon Pro 5300M 4 GB, Intel UHD Graphics 630 1536 MB, 32 GB 2667 MHz DDR4)

**Comment by zmb3** [comment]
Do you see the same behavior if you set the scrollback length to something like 100 lines?

**Comment by programmerq** [comment]
The default scrollback value is 1000 lines. My test did not include any new lines, so I ended up with a very large single line.

I set the scrollback to 100 lines and repeated the test. This time I saw the memory usage spike up to 3.7GiB before being killed by chrome.

**Comment by zmb3** [comment]
Hmmm, I'm running on Brave 1.57.47 (Chromium 116.0.5845.96) with `cat /dev/random | base64` (the `-w 0` is default behavior on macOS, and I'm not seeing the issue. I've had it dumping random output for 10 minutes or so and the total JS heap is covering between 5-15MB but I've never seen it higher than that.

**Comment by zmb3** [comment]
Unable to reproduce
