### ISSUE TITLE
External Kubernetes joining docs

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#30455]
PR is not yet merged, but we'll be introducing a new variant of the Kubernetes join method.

PR: https://github.com/gravitational/teleport/pull/30225
RFD: https://github.com/gravitational/teleport/pull/29225

Documentation needs to cover Machine ID and Agent joining.

We'll want to provide some good signposting as to which variant of the Kubernetes join method people should use. They'll want to continue using the old `in_cluster` variant if their joining agent/bot is in the same cluster as their Teleport Auth Server - but otherwise - they'll need to use this variant of `kubernetes` joining.

Some parts of this variant are the same as the old variant (e.g allow rule definitions) so we may need to find a nice way to template this or present them within the same guide. It may make sense to just make these part of the same page and diverge where appropriate.

**Comment by ptgott** [comment]
Hi @strideynet, just to double-check, is the scope of this PR to (a) add docs for the variant of the Kubernetes join method; (b) rework the information architecture of the docs to direct the user to the appropriate join method; or (c) both?

**Comment by strideynet** [comment]
> Hi @strideynet, just to double-check, is the scope of this issue to (a) add docs for the variant of the Kubernetes join method; (b) rework the information architecture of the docs to direct the user to the appropriate join method; or (c) both?

(a) I think - the Machine ID information architecture refactor is a seperate ticket.
