### ISSUE TITLE
Select prompt type with OIDC

### ISSUE THREAD

**Issue by kenchan0130** [gravitational/teleport#3048]
**What happened**: When we use login with OIDC, the end users have to select account every time because it is set as `select_account` in https://github.com/gravitational/teleport/blob/05f3eeaf004af5e8a854401d117e83be95c9375e/lib/auth/oidc.go#L165-L166
**What you expected to happen**: The administrator will be able to set prompt type like https://github.com/gravitational/teleport/blob/master/docs/4.0/oidc.md#oidc-connector-configuration.

**Environment**:
- Teleport version (use `teleport version`): 4.1.0

**Comment by stevenGravy** [comment]
We have been made aware of OIDC type providers that cannot handle the parameter 'prompt' being at 'select_account'.   Other options may also apply for some clients. The specification at   [openid](https://openid.net/specs/openid-connect-core-1_0.html ) has 4 options 'none', 'login', 'consent', 'select_account'.  'prompt' is also an optional parameter.  Details of each parameter definition is available at the openid link.

Given these values and the optional nature of the  parameter recommend the following:

- Add a new parameter redirect_prompt
```
display: Oidc provider
issuer_url: https://x.y.com
redirect_prompt: select_account 
```
- The available values (5) are then none,login, consent, select_account, noparameter.  If noparameter is the value then no prompt parameter is passed.
- If no value is provided the value will stay as select_account as the default.

For further information Google oidc uses multiple values of this parameter (https://developers.google.com/identity/protocols/OpenIDConnect).
