### ISSUE TITLE
Unclear documentation on import of cluster public keys on client machine

### ISSUE THREAD

**Issue by stefanandres** [gravitational/teleport#305]
In http://gravitational.com/teleport/docs/admin-guide/#using-teleport-with-openssh it says
> First, you need to export the public keys of cluster members. This has to be done on a node which runs Teleport auth server and probably must be done by a Teleport administrator:
>>  tctl authorities --type=host export > cluster_node_keys

> On your client machine, you need to import these keys:
>
>> cat cluster_node_keys >> ~/.ssh/authorized_keys

What is the technical reason behind this? Is the auth server ssh'ing into the client box?

The documentation needs to clarify that part.

**Comment by klizhentas** [comment]
Fair point - I will update the docs. In short, this needs to be done so SSH clients will be capable of validating host certificates during SSH connection - that' how users will know they are logging into the right server.

**Comment by klizhentas** [comment]
k, docs updated:

http://gravitational.com/teleport/docs/admin-guide/#using-teleport-with-openssh

lmk if you have any other questions and thanks for a good catch!
