### ISSUE TITLE
Tsh 4.1.0 backwards incompatible message with 4.0.10

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3050]
## Description

When using `tsh 4.1.0` with cluster of `4.0.10` the following error occurs:

```go
$ tsh login  example.com
error: unknown method GenerateUserCerts
```

Teleports' existing version compatibility check should provide a clear and concise error message.

**Comment by russjones** [comment]
On unknown error, return advice, and we know the client is older than server, then tell them client is much older and they may want to upgrade.

**Comment by andrejtokarcik** [comment]
Going to be resolved by https://github.com/gravitational/teleport/pull/6018.

**Comment by webvictim** [comment]
We can link the issue and leave this open until the PR merges, just so we don't lose track if the PR is closed for any reason.
