### ISSUE TITLE
`TestDiscoveryInCloudKube ` flakiness

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#30515]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/5871515517/job/15921041799

#### Relevant snippet

**replace everything below here with your snippet**

```
=== FAIL: lib/srv/discovery TestDiscoveryInCloudKube/no_clusters_in_auth_server,_import_2_stg_clusters_from_EKS (1.87s)
    discovery_test.go:990: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/discovery/discovery_test.go:990
        	Error:      	Condition never satisfied
        	Test:       	TestDiscoveryInCloudKube/no_clusters_in_auth_server,_import_2_stg_clusters_from_EKS
```

**Comment by tigrato** [comment]
@atburke can you please take a look?
Flakiness was introduced by #29285.
Probably the 100ms isn't enough to propagate the events

**Comment by zmb3** [comment]
@atburke any updates on this? We need to be a bit more proactive about fixing flakiness, especially during release time when everyone is trying to get their work in.
