### ISSUE TITLE
Use Vault for HSM support.

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3055]
Integrate with HashiCorp Vault for [HSM support](https://www.vaultproject.io/docs/enterprise/hsm). Then Vault can be used to store private key material.

**Comment by benarent** [comment]
Did the customer have a specific request for a HSM module. We could start by building a reference setup using https://aws.amazon.com/cloudhsm/ , but until we've a strong customer use case I'll leave this issue open for more feedback.

**Comment by webvictim** [comment]
They didn’t request any particular HSM.

**Comment by russjones** [comment]
Best: 30
Worst: 90

**Comment by klizhentas** [comment]
@russjones let's clarify the design proposal a bit. I think we should really clarify that we can support hashicorp/vault with HSM enabled as a storage backend for private key material on prem and suggest using DynamoDB with encryption  and other native clouds when Teleport is running in cloud-integration mode.

**Comment by klizhentas** [comment]
Likely not going to happen.
