### ISSUE TITLE
`TestKubeServerWatcher ` flakiness

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#30566]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/5881833472/job/15951108628

#### Relevant snippet

```
=== FAIL: lib/services TestKubeServerWatcher (0.04s)
    watcher_test.go:1073: 
        	Error Trace:	/__w/teleport/teleport/lib/services/watcher_test.go:1073
        	Error:      	An error is expected but got nil.
        	Test:       	TestKubeServerWatcher
```

**Comment by GavinFrazar** [comment]
can't repro this even with `-race -count=1000` 👀

**Comment by GavinFrazar** [comment]
@tigrato

**Comment by tigrato** [comment]
This failure looks odd. I run 5000 replicas with `-cpu=0.04` and all of them PASS.

The test runs the following steps:
1. creates several `kube_server`
2. waits till the watcher is initialized
3. ensures that the number of servers is expected in the watcher
4. deletes one element
5. ensure the expected servers in the watcher decreased by 1
6. check if the deleted server doesn't exist in the watcher -> fails here

We either have the watcher receiving events from previous insertions between steps 5 and 6 or the delete event is received for a wrong `kube_server` - I hope this isn't the case :cry:
