### ISSUE TITLE
Enroll New Resource: Application within kubernetes

### ISSUE THREAD

**Issue by logand22** [gravitational/teleport#30568]
What would you like Teleport to do?
As a part of the generated scripts / helm charts in the `Enroll New Resource` tab, add an option to enroll an application that is hosted in kubernetes.

What problem does this solve?
It increases the ease of use of Teleport by providing another simplified enrollment process to a potentially common scenario.

If a workaround exists, please include it.
It seems that the current method of enrolling an application hosted in kubernetes would be to enroll a kubernetes cluster and then modify the chart by hand to include the application.

**Comment by tigrato** [comment]
Hey @logand22,

For Teleport 14, we are releasing a feature that automatically discovers every application in the Kubernetes cluster you are installing the `teleport-kube-agent` chart.

You can read more about it [here](https://github.com/gravitational/teleport/blob/master/rfd/0135-kube-apps-discovery.md).

When following the `Enroll New Resource` tab and choosing `Kubernetes`, the script generated will automatically configure this new auto-discovery feature. 
Once the agent starts, it will search all services in the Kubernetes cluster and will create applications for services whose ports are HTTP or discovered as HTTP.
It is also possible to include TCP apps but for now, they require a simple annotation.

**Comment by logand22** [comment]
That satisfies my requirements at least so I'll go ahead and close this.
