### ISSUE TITLE
Include email attribute in SAML response when using Teleport as an IdP.

### ISSUE THREAD

**Issue by vip8439** [gravitational/teleport#30589]
What would you like Teleport to do? Include an assertion for email address. For example:
```
<saml:Attribute Name="User.Email"
 NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
 <saml:AttributeValue xsi:type="xs:anyType">testuser@youremail.com
 </saml:AttributeValue>
 </saml:Attribute>
```

What problem does this solve? Allows me to use Teleport as an IdP for Slack (the email attribute is required in the SAML response).

If a workaround exists, please include it. None

**Comment by zmb3** [comment]
Duplicate of #23128
