### ISSUE TITLE
S3 Permissions Docs

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3059]
**What happened**:

Customer has reported a lot of critical information in cloud-trail logs, around S3 access to viewing recorded sessions. 

We need to `ListObjectVersions`. `s3:ListBucketVersions` & `s3:GetObjectVersion` 

**What you expected to happen**:

We need to provider clearer information for s3 permissions, in Docs, Terraform and CloudFormation examples.

**Comment by aelkugia** [comment]
I had seen #3022 addressed updating the Terraform and CloudFormation examples. I feel like they are clearly detailed in terms of mentioning `ListObjectVersions`, `s3:ListBucketVersions` & `s3:GetObjectVersion`. What else were you thinking of adding to those @benarent? I was going to add some clarification to the docs [here](https://gravitational.com/teleport/docs/admin-guide/#using-amazon-s3) if you think that would be clear?

**Comment by webvictim** [comment]
Yep - a concise list of exactly which permissions are needed (maybe with an inline policy example as below) would be great.

```
{
   "Version": "2012-10-17",
   "Statement": [
     {
       "Effect": "Allow",
       "Action": [
         "s3:ListBucket",
         "s3:ListBucketVersions"
        ],
       "Resource": ["arn:aws:s3:::example.s3.bucket"]
     },
     {
       "Effect": "Allow",
       "Action": [
         "s3:PutObject",
         "s3:GetObject",
         "s3:GetObjectVersion"
       ],
       "Resource": ["arn:aws:s3:::example.s3.bucket/*"]
     }
   ]
 }
```

**Comment by benarent** [comment]
I agree with @webvictim that we should make this smoother in general https://github.com/gravitational/teleport/pull/3072 

We could add these to https://gravitational.com/teleport/docs/aws_oss_guide/#iam

**Comment by aelkugia** [comment]
Okay great, I just submitted PR #3073. Ended up adding to the location @benarent mentioned [here](https://gravitational.com/teleport/docs/aws_oss_guide/#iam). Let me know if I missed any permissions or if you think should be added somewhere else as well.

**Comment by benarent** [comment]
Could you also create a example IAM permissions for DynamoDB and provide a header that outlines this is the IAM for S3.

**Comment by aelkugia** [comment]
Just added an example for DynamoDB + updated headers.

**Comment by aelkugia** [comment]
I am thinking now it's redundant. I feel like we should add the S3 IAM permissions [here](https://gravitational.com/teleport/docs/admin-guide/#using-amazon-s3), considering DynamoDB IAM permissions are already discussed [there](https://gravitational.com/teleport/docs/admin-guide/#using-dynamodb). Let me know what you think @benarent and I can make the update
