### ISSUE TITLE
Provide clearer error than 'missing secret' when client and server versions mismatch

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3060]
**What happened**: An employee at a customer ran `brew upgrade` yesterday and got their `tsh` client updated to `4.1.0` as a result. Their server has not been updated to Teleport 4.1.x yet and so they got a `missing secret` error when trying to authenticate with their SSO provider via the pop-up browser window. 

**What you expected to happen**: Ideally, the in-browser error should give the user a hint that `missing secret` actually means their client and server versions are out of sync. This would save some time debugging the issue.

**How to reproduce it (as minimally and precisely as possible)**: Try to log into a 4.0.x cluster with a 4.1.x `tsh` client

**Environment**:
- Teleport version (use `teleport version`): `teleport 4.0.2`
- Tsh version (use `tsh version`): `tsh 4.1.0`

**Comment by benarent** [comment]
@webvictim is this just a 4.0 -> 4.1 issue, or is this each time we do a major bump? 

We are starting to see some increased downloads from Homebrew, https://formulae.brew.sh/formula/teleport#default .  We should also provide clear info on how to change version `brew install teleport@4.0`

**Comment by webvictim** [comment]
It's happened with 4.0 clients against 3.2.x clusters before as well I believe. I can't remember the exact details.

**Comment by benarent** [comment]
I feel this is more a bug, the `tsh` client often has less breaking functionality than versions of Teleport.  It should be ok for end users to have different version of `tsh` clients. I would say it's Ok to break for larger versions.

**Comment by quinqu** [comment]
I tried to replicate this, but was able to successfully log in with different versions. Forrest also was able to log in using an `oidc` type connector as well. I'm closing because these particular versions were so far out of sync.
