### ISSUE TITLE
Provide a high level tool that lets customer define / return which IP ranges belong to a cluster. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3067]
**What happened**:
Customers are used to being able to lookup nodes based on IP ranges. These nodes could belong to many clusters, similar to setting an IP range in [ssh_config](https://man.openbsd.org/ssh_config#PATTERNS). 

An example is 

`10.1.* `- cluster1
`10.10.*` - cluster 2
`10.12.* 10.13.* ` - cluster3

From an end user perspective they'll be able to `tsh ssh` and it'll be able to let the customer know which cluster it's in / auto connect it. ( Final implementation TBD ) 
 

**What you expected to happen**:

_Final Design and Implementation TBD_

**Comment by benarent** [comment]
Also noted by customer,

> and if a user is logged in a particular cluster with `tsh login custername` and tries to log into a box in another cluster `tsh` just hangs

**Comment by zmb3** [comment]
Doesn't seem to be much appetite for this.
