### ISSUE TITLE
Document role mapping

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3068]
## Dynamic role mapping is not documented anywhere

https://github.com/gravitational/teleport/blob/master/lib/services/map_test.go#L141

**Comment by benarent** [comment]
Can you provide a few use cases that we current have users using dynamic role mapping?  Is this more for integrating with external systems, such as ` kubernetes_groups: ["system:masters", "{{external.trait_name}}"]]`  and `{{external.username}}` for SSO providers to pass in Login information?
