### ISSUE TITLE
Should be able to specify a token timeout for nodes add

### ISSUE THREAD

**Issue by jaxxstorm** [gravitational/teleport#307]
Currently if I want to add a new node to teleport, I run the following:

```
tctl nodes add
```

This generates a token which is valid for 900 seconds.

If I want to add nodes using configuration management like Puppet, the join might take longer than 900 seconds, which isn't very fun.

With this in mind, can we have an option to set the token validity?

**Comment by klizhentas** [comment]
yep, we've been just discussing this with @kontsevoy the other day. 

Here's what we have in mind so far:

* TTLs for tokens

We will add a flag to extend ttl for a token

* Long-lived deployment tokens

We are actually thinking about creating special long lived tokens that can be reused multiple times - we are also looking for ways to avoid executing special action on every node add, what currently complicates deployment.  

* Ideas and feedback

If you could share more details about your ideal deployment/configuration scenario, this would help us as well

We will keep you posted once we get to some balanced solution in terms of security/good UX soon!

**Comment by jaxxstorm** [comment]
Ideally we'd be able to specify the token in `/etc/teleport.yml` and then just simply be able to run a `teleport start` - from there it would allow us to register multiple nodes without much issue.

Currently we can already do this according to the yaml example, will this work?

**Comment by klizhentas** [comment]
it will work, but you will have to generate new token for every new added node, because tokens are one time

**Comment by kontsevoy** [comment]
@jaxxstorm this is no 1 request we're getting. this will come our very soon (<1 mo)

**Comment by jaxxstorm** [comment]
awesome! i wrote a puppet module for this so once it's done it'll be easi;y configurable: https://github.com/jaxxstorm/puppet-teleport

**Comment by kontsevoy** [comment]
yes, these two are expressing the same problem.
