### ISSUE TITLE
docs: team scope should recommend installing enterprise binaries from the cloud repo

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#30706]
## Applies To

example page. This is across all of the linux install includes.

https://goteleport.com/docs/ver/14.x/database-access/guides/azure-sql-server-ad/?scope=team#step-68-create-a-database-service-configuration

## Details

The team scope is recommending to install OSS on the same version as cloud.  It then is installing the major repo, not the cloud and enterprise version. Teleport Team instances should be installing with the cloud repo which will also install the teleport upgrader.

<img width="915" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/d924fd2a-be68-4c9c-8879-27c4fe5191ff">

If a admin does a `sudo apt upgrade` that will upgrade in the major version repo, not the `cloud` repo.

**Comment by ptgott** [comment]
Closing as completed in 2c457b11c1da6ddad86642aa9e189dbcf94b38cd.
