### ISSUE TITLE
Mac terminal resize loop/bug when running kubectl run -it

### ISSUE THREAD

**Issue by dan-ih** [gravitational/teleport#30714]
Expected behavior:
Terminal stays the same size when starting an interactive command with kubectl run -it

Current behavior:
Terminal rapidly resizes

Bug details:
- Teleport version: 
 `Teleport v13.3.2 git:v13.3.2-0-gfc60440 go1.20.7`
 `Proxy version: 12.4.3`
- Recreation steps:
1. Log into a kubernetes cluster using tsh. 
2. Start a container in interactive mode with 'kubectl run' in a smaller sized mac terminal window:
* `kubectl run -it alpine --image alpine --command sh`
3. You should see the terminal rapidly resizing back and forth. If you are having difficulty recreating this issue, try a smaller terminal window size.

- Debug logs
```I0818 18:08:20.283301    2787 round_trippers.go:463] POST https://teleport.introhive.com:3026/api/v1/namespaces/default/pods/alpine/attach?container=alpine&stdin=true&stdout=true&tty=true
I0818 18:08:20.283314    2787 round_trippers.go:469] Request Headers:
I0818 18:08:20.283327    2787 round_trippers.go:473]     User-Agent: kubectl/v1.28.0 (darwin/arm64) kubernetes/855e7c4
I0818 18:08:20.283338    2787 round_trippers.go:473]     X-Stream-Protocol-Version: v4.channel.k8s.io
I0818 18:08:20.283348    2787 round_trippers.go:473]     X-Stream-Protocol-Version: v3.channel.k8s.io                                                                                                        I0818 18:08:20.283358    2787 round_trippers.go:473]     X-Stream-Protocol-Version: v2.channel.k8s.io
I0818 18:08:20.283368    2787 round_trippers.go:473]     X-Stream-Protocol-Version: channel.k8s.io
I0818 18:08:20.448352    2787 round_trippers.go:574] Response Status: 101 Switching Protocols in 164 milliseconds

I0818 18:08:20.448408    2787 round_trippers.go:580]     Connection: Upgrade
I0818 18:08:20.448416    2787 round_trippers.go:580]     Pragma: no-cache
I0818 18:08:20.448424    2787 round_trippers.go:580]     Referrer-Policy: strict-origin
I0818 18:08:20.448431    2787 round_trippers.go:580]     Upgrade: SPDY/3.1
I0818 18:08:20.448439    2787 round_trippers.go:580]     X-Frame-Options: SAMEORIGIN
I0818 18:08:20.448446    2787 round_trippers.go:580]     Cache-Control: no-cache, no-store, must-revalidate
I0818 18:08:20.448454    2787 round_trippers.go:580]     Expires: 0
                                                                                                              I0818 18:08:20.448461    2787 round_trippers.go:580]     Strict-Transport-Security: max-age=31536000; includeSubDomains
                                                                                                               I0818 18:08:20.448468    2787 round_trippers.go:580]     X-Content-Type-Options: nosniff
I0818 18:08:20.448475    2787 round_trippers.go:580]     X-Stream-Protocol-Version: v4.channel.k8s.io
I0818 18:08:20.448483    2787 round_trippers.go:580]     X-Xss-Protection: 1; mode=block```

**Comment by tigrato** [comment]
@dan-ih 

I cannot reproduce this behavior in my config.
Which terminal are you using? 
Does the problem persists on new versions of Teleport?

**Comment by dan-ih** [comment]
@tigrato This seems to happen fairly consistently in the default macos terminal (using Version 2.13 (447)) . I personally use iterm and the issue doesn't happen there, but others in the company who use the default mac terminal have had trouble with this. Unfortunately it looks like something we can't just tell people to ignore, they need to change to iTerm for this to work properly, otherwise it makes it impossible to read anything. I posted a video of what is looks like in the teleport slack workspace when we discussed there.

**Comment by tigrato** [comment]
Oh, I tested with iterm that's why I didn't reproduce it.
Will debug it with the default terminal

**Comment by dlipofsky** [comment]
I experience the same issue (vibration or jitter of terminal due to rapid continuous resizing) with
- Terminal 2.14
- MacOS Sonoma 14.5
- Teleport v14.3.3
- Proxy version: 15.3.1
- AWS EKS 1.29

and it does seem specifically related to teleport, since I can run the same command against the same cluster when connecting via "assume" and I don't have this issue.

**Comment by dlipofsky** [comment]
@tigrato were you able to reproduce?
