### ISSUE TITLE
Connect: Do not show gRPC status numbers in UI, prettify status codes

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#30753]
At the moment, when a gRPC request returns an error, we show the status number followed by the code and the message.

https://grpc.github.io/grpc/core/md_doc_statuscodes.html

![gRPC error](https://github.com/gravitational/teleport/assets/27113/71151457-8889-4dc6-99a9-38128bc0289f)

The status number is pretty much useless to the end user and the status code could be displayed in a prettier way, i.e. "Invalid argument:" instead of "INVALID_ARGUMENT:".

I haven't explored if grpc-js offers a built-in way to deal with this. But the message we see today is the default message for errors coming from grpc-js. This means that those errors could be rewrapped on [the gRPC client level](https://github.com/gravitational/teleport/blob/9960d827a77c358a5c4f91ec926a26aee090c64b/web/packages/teleterm/src/services/tshd/createClient.ts), before they cross the context bridge. At that point, each error has both `code` (status number) and `details` (custom message) properties, which lets us reraise another error with a better `message`.

This coincides with gravitational/teleport.e#853, which also outlines how we should inspect errors for retryable metadata. In both cases, we'd need a function shared for every gRPC call, so that they all treat errors in the same way. The idea in gravitational/teleport.e#853 was to refactor every call to something like in the snippet below. This issue doesn't call for anything as sophisticated, we merely need to rewrap each error, but such generalized wrapped for the gRPC would be useful anyway.

<details>
<summary>Example call from gravitational/teleport.e#853</summary>

```typescript
async createGateway(params: types.CreateGatewayParams) {
  const req = new api.CreateGatewayRequest()
    .setTargetUri(params.targetUri)
    .setTargetUser(params.user)
    .setLocalPort(params.port)
    .setTargetSubresourceName(params.subresource_name);

  return call(tshd.createGateway, req, response => response.toObject());
}
```
</details>

It'd be best if we were able to preserve the status code across the context bridge, but this means returning a custom object instead of an error, as described in gravitational/teleport.e#853, and then reassembling it into an error.

Closes #25264.

**Comment by ravicious** [comment]
With the MFA support for kube access and administrative actions, when an incorrect TOTP is entered, the backend returns access denied with a message about TOTP being incorrect. But because Connect completely removes messages from access denied errors, the user will simply see "Access Denied" instead of a meaningful message.

**Comment by gzdunek** [comment]
After switching the client to `protobuf-ts` (https://github.com/gravitational/teleport/pull/39229), the error messages no longer contain the status code. 
I think this default behavior is fine, if we want to inspect the status code and number, we can look at the logs, where we have the full error details.

**Comment by ravicious** [comment]
Yeah, the default is find and I don't think we ever had a bug report so far where the status code would be the deciding factor.

One thing that caught my attention is that we have a lot of places which just show `attempt.statusText` in a red alert box with no proceeding text. Because of [how Go error strings are supposed to look like](https://go.dev/wiki/CodeReviewComments#error-strings), we should update those places in UI to say something before showing the error, like `Could not log in, <error>` or `Could not <action>: <error>`.

**Comment by gzdunek** [comment]
Good point, seems like a quick thing to do, I will squeeze it into my other work this week.
