### ISSUE TITLE
Make token roles case insensitive or improve error message

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#30768]
The values in the `roles` array must be capitalized (`Node`, `App` and so on) which feels unusual for our configuration.

If you attempt to make [an IAM token](https://goteleport.com/docs/agents/join-services-to-your-cluster/aws-iam/#step-24-create-the-aws-joining-token) with the role `app`, you get "ERROR: role app is not registered".

Instead, we should either make the roles case insensitive or improve the error message. If we detect that the error is due to the role not being registered, we should output an additional note saying that the roles are case sensitive. Or perhaps just list all available roles.

**Comment by zmb3** [comment]
I made them case (and underscore) insensitive for `tctl tokens add` a while ago, so there's already precedent for this.
