### ISSUE TITLE
Proxying GUI sessions

### ISSUE THREAD

**Issue by patcable** [gravitational/teleport#308]
Hi! I just set up Teleport, and it's very cool. I put something together like this once upon a time [here](https://www.usenix.org/conference/lisa15/conference-program/presentation/cable), but you did a much better job on the usability aspect. Cheers!

I was wondering if y'all had given any thought to handling GUI sessions? Lots of these private networks that you would want to mediate access to have WebGUIs (Dell DRACs and other BMCs come to mind) and it'd be neat to know if that was on your roadmap.

Thanks!

**Comment by klizhentas** [comment]
hey, nice presentation and project looks cool! We thought about it - probably easiest would be to do X11 forwarding support. Some folks asked for RDP as well. We don't have any definitive plans yet, but I will keep this issue as a reference to collect feedback.

**Comment by patcable** [comment]
Thanks @klizhentas! 

Perhaps something like http://guac-dev.org/ would be worth looking into for integration; if you were able to spawn a vncserver process as that particular user then you could link to the VNC/RDP session that way.

**Comment by kontsevoy** [comment]
@patcable We've discussed this, and auto-launching VNC/RDP by a security protocol implementation (Teleport) is probably not a good idea and goes against "one tool == one job" UNIX philosophy. How about this: can't you do this already by connecting to a node via Teleport, launching VNC/RDP and opening up port forwarding for VNC/RDP ports?

**Comment by patcable** [comment]
I certainly could just start up a vncserver on a machine sitting on the other side -- but then I've also bypassed any of the session logging goodness that Teleport does, too. I could tell that an admin started a VNC session, but I would have no visibility into what they did.

The use case I was imagining that you had a network of Dell DRAC hosts that expose a web interface, and you wanted to capture admins use of those tools. If teleport spawned a container running VNC and kept screen capture info then one could imagine in the event of something bad.

Granted, this is a use case that is probably geared more towards people with their own datacenters and not cloud, since most cloud IaaS resources (that aren't Windows based... but even that's changing) should be CLI based. Since I was looking at Teleport as something that monitored and audited access to a private network I figured that would fit in nicely.

In any case, thanks for considering it. Teleport is pretty great!

**Comment by betabrain** [comment]
Hello! I am also looking for something with the security features of teleport AND the _business-compatibility_ of GUI sessions - mainly because there is Windows involved as well as Windows users.

I agree that using teleport to start vnc servers to circumvent teleport is a bad idea, hence I am more arguing along the lines of X11 support. There is a maintained [X11 server for Windows](http://www.straightrunning.com/XmingNotes/), therefore all that's missing for me is teleport supporting GUI sessions.

Now, I know absolutely zero about X11 aside from there being X11 forwarding in OpenSSH, so please forgive my ignorance. Can X11 traffic be captured and replayed? This would mean teleport can offer X11 audit and playback. Without sacrificing it's main features.

**Comment by kontsevoy** [comment]
Yes, X11 can be captured and replayed, but I'd guess the complexity of replaying X11 is comparable to implementing a lightweight X server. This definitely lies outside of our current focus for Teleport.

**Comment by jdc0589** [comment]
@klizhentas @kontsevoy as someone who likes teleport, and it pretty disgusted with the pricing of stuff like Cyberark/BomgarPAM/etc... if you guys ever add RDP support with similar auditing it would be **mind blowingly amazing**. If it was around right now, it would be our automatic choice and you'd probably have an annual support contract from us too.

**Comment by gedw99** [comment]
Check wingo.
It's a golang implenentation of x11.

https://github.com/u-root/wingo

Have used it for a while for example fly this on different OS's. It's so lucky it exists. Took the one developer a long time of tedious work.

Also uroot itself is a great way to boot servers.

Please let me know if wingo helps you as I also think teleport is awesome. Thanks for putting it open
