### ISSUE TITLE
"error: no PEM data found" with letsencrypt

### ISSUE THREAD

**Issue by zedtux** [gravitational/teleport#3082]
**What happened**:

I'm configuring Teleport with Let's Encrypt which fails with the following error :

```
teleport[9190]: error: no PEM data found
```

Here is the `/etc/teleport.yml` file part related to the SSL certificates:

```yaml
    # TLS certificate for the HTTPS connection. Configuring these properly is
    # critical for Teleport security.
    https_key_file: /etc/ssl/teleport.domain.lu.crt
    https_cert_file: /etc/ssl/teleport.domain.lu.key
```

The files are present on the disk and not empty in the following form:

**/etc/ssl/teleport.domain.lu.crt**

```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```

**/etc/ssl/teleport.domain.lu.key**

```
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
```

I'm provisioning my nodes using Chef, and I've generated the certificate using the [chef-acme](https://github.com/schubergphilis/chef-acme) cookbook.

With Chef I'm generating the `/etc/teleport.yml` file based on the given one from the Teleport documentation.

I found [this post](https://community.gravitational.com/t/teleport-web-tls-certificates-no-pem-data-found/46) which explains that let's encrypt generate 4 files in the `/etc/letsencrypt/live/` folder, but the `chef-acme` cookbook doesn't provide me those files.

But looking closer, the following line :

```
https_key_file: /etc/letsencrypt/live/domain/privkey.pem
```

Seem to be the equivalent to my `/etc/ssl/teleport.domain.lu.key` file.

And the line:

```
https_cert_file: /etc/letsencrypt/live/domain/fullchain.pem
```

Seem to be the equivalent to my `/etc/ssl/teleport.domain.lu.crt` file.

Could you please help me so that I have the certificates used by Teleport?

**What you expected to happen**:

Teleport should start without any errors and use the certificate.

**How to reproduce it (as minimally and precisely as possible)**:

1. Generate a Let's Encrypt certificate
2. Update the `/etc/teleport.yaml` file with the crt and key files
3. Restart teleport

**Environment**:
- Teleport version (use `teleport version`): `Teleport v4.1.1 git:v4.1.1-0-gb359aaa8 go1.12.1`
- Tsh version (use `tsh version`): `Teleport v4.1.1 git:v4.1.1-0-gb359aaa8 go1.12.1`
- OS (e.g. from /etc/os-release): Debian Stretch

**Comment by klizhentas** [comment]
In your own example it looks like your key file is in the place of cert and your cert is in place of key, I would swap the files and see how it goes. Feel free to ask your questions in https://community.gravitational.com in the future.

**Comment by zedtux** [comment]
Pfff, I am very sorry for this ... end of the day you know ... 🤦‍♂. Thank you anyway.

**Comment by tacerus** [comment]
The same just happened to me! I guess I'm too used to having the certificate come before the key value in configuration files.. nice twist in things by the Teleport configuration example. :-)
