### ISSUE TITLE
Cloudformation IAM permissions are open. 

### ISSUE THREAD

**Issue by ctindall** [gravitational/teleport#3085]
Hey there! I noticed some possible problems in some code in this repo. A quick summary of a few of them is below, but let me know if you're interested in seeing a full report or talking about cloud security in general.

---

**severity:** serious

**filename:** `./examples/aws/cloudformation/ent.yaml`

**line number(s):** [540]
https://github.com/gravitational/teleport//blob/master/examples/aws/cloudformation/ent.yaml#L540 

**resource(s):** 

IAM policy should not allow * action

---

**severity:** warning

**filename:** `./examples/aws/cloudformation/ent.yaml`

**line number(s):** [540] 
https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L540 

**resource(s):** 

IAM policy should not allow * resource

---

**severity:** warning

**filename:** `./examples/aws/cloudformation/ent.yaml`

**line number(s):** [893] https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L893

**resource(s):** 

S3 Bucket should have access logging configured

---

**severity:** warning

**filename:** `./examples/aws/cloudformation/ent.yaml`

**line number(s):** [78, 107, 278]
https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L78
https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L107
https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L278

**resource(s):** 

Security Groups egress with an IpProtocol of -1 found

---

**severity:** warning

**filename:** `./examples/aws/cloudformation/ent.yaml`

**line number(s):** [78, 107, 278]
https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L78
https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L107
https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L278

**resource(s):** 

Security Groups found with cidr open to world on egress

---

**severity:** warning

**filename:** `./examples/aws/cloudformation/ent.yaml`

**line number(s):** [78, 278]
https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L78
https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L278

**resource(s):** 

Security Groups found with ingress cidr that is not /32

---

**severity:** warning

**filename:** `./examples/aws/cloudformation/ent.yaml`

**line number(s):** [78, 278]
https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L78
https://github.com/gravitational/teleport/blob/master/examples/aws/cloudformation/ent.yaml#L278

**resource(s):** 

Security Groups found with cidr open to world on ingress.  This should never be true on instance.  Permissible on ELB

**Comment by benarent** [comment]
Thanks for the issue @ctindall, I've gone ahead and updated the title and added in quick links to the line numbers. We'll likely need to do this for out oss.yaml, and we should also check our Terraform template. 

Did you use a specific tool for this output?

**Comment by webvictim** [comment]
The output looks like https://github.com/stelligent/cfn_nag to me.

There's certainly some things we could change here and more best practices to follow, but on the whole the "shouldn't be open to all" thing on security groups is bunkum here as our product's whole purpose is to provide a publicly accessible bastion host. We can run cfn-nag on the templates and fix them up as appropriate.

**Comment by ctindall** [comment]
Yes, this is generated by cfn_nag. I appreciate your taking a look at my report and also agree that there are instances where cfn_nag is a little too nag-y. Gonna take a look at these examples and see if there isn't some generalizable case where cfn_nag doesn't need to be as diligent and possibly submit those upstream.

**Comment by webvictim** [comment]
Appreciated!
