### ISSUE TITLE
NAT documentation

### ISSUE THREAD

**Issue by jaxxstorm** [gravitational/teleport#309]
There's an option `--advertise-ip` which isn't well document.

Would it be possible to:

  - Document how it can be used in config files
  - Explain when it's best used

If you want to reply in this README I'm happy to update `admin-guides.md`

Would also be good if you could write a brief explanation about how use an apache proxy maybe as part of this? Any considerations?

**Comment by klizhentas** [comment]
yep, I will update admin guide with flags and config files. 

`advertise_ip` can be set in config file as well.

Can you tell me more about your apache use-case?

**Comment by pmorch** [comment]
Here is a question I have about NAT, that I'd love to see documented somehow: 

(How) can one use teleport for nodes that are behind remote NATs and that aren't routable/accessible from the outside - where there are no port-fowards to get through the NAT? Is this possible?

For such nodes beind a remote NAT there are no good values for `--advertise-ip`. 

We'd love to replace our home-grown system, where all our "nodes" maintain an open ssh connection from each "node" to the "proxy" with something similar to:

    ssh -R $randomPort:localhost:22 restricteduser@proxy

This is used as a poor-man's NAT hole punching. Our version of the "proxy" then connects clients to `locahost:$remotePort`.

If teleport doesn't support this scenario out of the box, we'd love to be able to do this hack but then I'm guessing at least we'd need an `--advertise-ip-and-port` option where one can provide a value such as `127.0.0.1:$randomPort` That way all these nodes have their own ports on `localhost`.

**Comment by klizhentas** [comment]
@pmorch  Teleport has first class support for reverse tunnels just for this special case. We will elaborate in the docs to address this particular problem.

**Comment by pmorch** [comment]
@klizhentas  HURRAY! You just made my day!!!!

**Comment by jaxxstorm** [comment]
> Can you tell me more about your apache use-case?

Essentially I'd like to be able to expose teleport behind an already existing proxy.

**Comment by jaxxstorm** [comment]
Any updates here? I'm still having to work with an apache reverse proxy which is less than ideal :(

@klizhentas or @kontsevoy

**Comment by kontsevoy** [comment]
@jaxxstorm we've been finishing up the 3rd party security audit and preparing 1.0 to be released with "production-ready" moniker. This will mean another round of documentation update/refresh where reverse tunnels will be well-documented.

**Comment by jaxxstorm** [comment]
Awesome, thanks!

**Comment by kontsevoy** [comment]
`advertise_ip` has been documented in commit e2887fba3241712584ac3fb98899ecb75927268a

behind-firewall operation will be documented in a separate commit/PR.

**Comment by pmorch** [comment]
> behind-firewall operation will be documented in a separate commit/PR.

I can see that the original issue about `advertise_ip` has been covered by e2887fba3241712584ac3fb98899ecb75927268a. 

There doesn't seem to be an open issue for behind-firewall operation. Since behind-firewall operation and `advertise_ip` apparently are considered separate issues, should I open a separate issue for behind-firewall operation?

**Comment by kontsevoy** [comment]
@pmorch yes you can. the work is underway already, see `ev/tunnels` branch. Thanks!
