### ISSUE TITLE
GCP Authentication with db service fails. 

### ISSUE THREAD

**Issue by adamstrawson** [gravitational/teleport#30901]
Expected behavior:

As a user, I should be able to run `tsh db connect --db-name=foo my-server` and connect to the database

Current behavior:

Running the below command, returns an error:
`tsh db connect  --db-name=foo my-server`

```
psql: error: connection to server at "<snip>" (xx.xx.xx.xx), port 443 failed: Could not generate GCP IAM auth token:

  rpc error: code = InvalidArgument desc = Invalid form of account ID <snip>.gserviceaccount.com. Should be [Gaia ID |Email |Unique ID |] of the account

Make sure Teleport db service has "Service Account Token Creator" GCP IAM role,
or "iam.serviceAccounts.getAccessToken" IAM permission.

ERROR: exit status 2
```

This is a recent issue, with no changes to our GCP Authentication, and being observed by multiple people across our organisation. 

I can confirm that the Teleport service has appropriate IAM roles (`iam.serviceAccounts.getAccessToken`), which also haven't changed.

Any pointers?

Bug details:
- Teleport version: 13.3.5

**Comment by smallinsky** [comment]
I think that it can be related to https://github.com/gravitational/teleport/issues/28996

GCP Database integration requires to set the `--db-user=` flag with specific format like: 
```
tsh db connect --db-user=teleport@<project-id>.iam --db-name=postgres cloudsql
```

https://goteleport.com/docs/database-access/guides/postgres-cloudsql/#step-77-connect

@adamstrawson 
Could you follow the https://goteleport.com/docs/database-access/guides/postgres-cloudsql/#step-77-connect guide and try to  use the `--db-user=teleport@<project-id>.iam` format ? 

> When connecting to the database, use the name of the database's service account that you added as an IAM database user [above](https://goteleport.com/docs/database-access/guides/postgres-cloudsql/#step-27-create-a-service-account-for-the-database), minus the .gserviceaccount.com suffix. The database user name is shown on the Users page of your Cloud SQL instance.

**Comment by smallinsky** [comment]
Seems like a regression issue described in https://github.com/gravitational/teleport/issues/31147  
We will fix this shortly. Thanks for reporting this issue.

**Comment by GavinFrazar** [comment]
This is fixed in the next release in v13 and v14.
