### ISSUE TITLE
Design for Connect Unified view for resources

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#30907]
Unified resources view for Connect as they add Application support.
NOT supported - Desktops. Will need to plan how to display them in the Connect UI / what the user action can be.

**Comment by zmb3** [comment]
For context, connecting to a desktop in the web UI is as simple as opening a specific URL. This means if the user is logged in to the web UI, we can show an "Open in browser" button in Teleport Connect that will link them directly to the desktop.
