### ISSUE TITLE
Unnecessary `auto-upgrade-enroll` message emitted at WARN level

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#30903]
## Expected behavior

All Teleport warnings should provide real errors with actionable feedback for users.

## Current behavior

With a stock config from `teleport configure`, ~45 seconds after startup and every ~8 minutes after that, Teleport 13.2.3 and later emit a message at `WARN` level:

```
Aug 23 10:19:33 ubuntu teleport[17262]: 2023-08-23T10:19:33-03:00 WARN [AUTH]      Failed to delete auto-upgrade-enroll alert: cluster alert "auto-upgrade-enroll" not found auth/auth.go:1101
Aug 23 10:27:58 ubuntu teleport[17262]: 2023-08-23T10:27:58-03:00 WARN [AUTH]      Failed to delete auto-upgrade-enroll alert: cluster alert "auto-upgrade-enroll" not found auth/auth.go:1101
```

This message is not actionable and confuses users, thinking there is a problem with their cluster when it's just running normally. There has been an uptick in logs in the Community Slack mentioning this message as a problem with the cluster in the last week.

We should suppress or otherwise remove this message from log output.

@fspmarshall `git blame` has pointed me at https://github.com/gravitational/teleport/pull/28951 and its v13 backport https://github.com/gravitational/teleport/pull/29206 as being the likely culprit.

**Comment by fspmarshall** [comment]
Fixed in https://github.com/gravitational/teleport/pull/30849
