### ISSUE TITLE
Update the `tctl auth export` reference

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#30920]
## Applies To

https://goteleport.com/docs/reference/cli/tctl/?scope=enterprise#tctl-auth-export

## Details

Currently, the documentation contains little information on why you would use this command and what each of the different types means.

Also, the examples (https://goteleport.com/docs/reference/cli/tctl/?scope=enterprise#examples-10) contain a reference to the old `tls` type that is no longer present in the current.  

## How will we know this is resolved?

The examples section is correct with complete information on different formats and why you would use them.

**Comment by zmb3** [comment]
Fixed in #38093
