### ISSUE TITLE
Access denied when playing recorded sessions on S3

### ISSUE THREAD

**Issue by iuriaranda** [gravitational/teleport#3095]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:

I get an access denied error when trying to replay any recorded session.

![image](https://user-images.githubusercontent.com/510809/67224354-4a61a980-f431-11e9-8e45-3b225b268cdb.png)

**What you expected to happen**:

I expected to be able to replay recorded sessions correctly.

**How to reproduce it (as minimally and precisely as possible)**:

Hit the play button in the web UI, or run the `tsh play session-id` command.

**Environment**:
- Teleport version (use `teleport version`): Teleport v4.1.1 git:v4.1.1-0-gb359aaa8 go1.12.1
- Tsh version (use `tsh version`): Teleport v4.1.0 git:v4.1.0-0-g3078799c go1.12.1
- OS (e.g. from /etc/os-release): Ubuntu 16.04.6

**Browser environment**

- Browser Version (for UI-related issues): Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
  ```
    ERROR REPORT:
  Original Error: *trace.BadParameterError AccessDenied: Access Denied
          status code: 403, request id: 96060132021987D5, host id: C/yXsUEEgPy/WdgMPgPSiFKTPulHjr8eLxejGKhaMiuUAOqLNCQ46+Rs6x0jtfISDLef9y/r52Y=
  Stack Trace:
          /tmp/20191001T141742/src/github.com/gravitational/teleport/lib/auth/clt.go:2133 github.com/gravitational/teleport/lib/auth.(*Client).GetSessionEvents
          /tmp/20191001T141742/src/github.com/gravitational/teleport/lib/client/api.go:1079 github.com/gravitational/teleport/lib/client.(*TeleportClient).Play
          /tmp/20191001T141742/src/github.com/gravitational/teleport/tool/tsh/tsh.go:372 main.onPlay
          /tmp/20191001T141742/src/github.com/gravitational/teleport/tool/tsh/tsh.go:337 main.Run
          /tmp/20191001T141742/src/github.com/gravitational/teleport/tool/tsh/tsh.go:184 main.main
          /usr/local/go/src/runtime/proc.go:209 runtime.main
          /usr/local/go/src/runtime/asm_amd64.s:1338 runtime.goexit
  ```
- teleport --debug
  ```
  Oct 21 16:51:27 ip-10-10-11-199 teleport[16416]: DEBU [DYNAMODB]  Got 0 stream shard records. dynamo/shards.go:172
  Oct 21 16:51:27 ip-10-10-11-199 teleport[16416]: DEBU [AUDIT]     GetSessionEvents. afterN:0 printEvents:true sid:a3acc4f5-f40e-11e9-ba8b-0a33c04d6b2e events/auditlog.go:800
  Oct 21 16:51:27 ip-10-10-11-199 teleport[16416]: DEBU [AUDIT]     Starting download of a3acc4f5-f40e-11e9-ba8b-0a33c04d6b2e. events/auditlog.go:605
  Oct 21 16:51:27 ip-10-10-11-199 teleport[16416]: DEBU [WEB]       "Unable to find events for session a3acc4f5-f40e-11e9-ba8b-0a33c04d6b2e: AccessDenied: Access Denied\n\tstatus code: 403, request id: D83C02CC4C2EFD12, host id: Kog0jr2/ZvijcXFx6/LYdYarPzw0uKpBG/k5h/Z5dS2dFkdCf/JXTgCTrHZBxjmmG4R7azCNNeE=." web/apiserver.go:1852
  ```

**Other relevant information**

It worked fine when using Teleport version 3.1.x, it started failing when we upgraded to 4.1. Although we did a stepped upgrade, so we upgraded through all minor versions from 3.1 to 4.1 and we didn't test this on all of them.

IAM permissions related to DynamoDB and S3 look like this (it's Terraform code):

```
  statement {
    sid = "AllAPIActionsOnTeleportAuth"

    actions = [
      "dynamodb:*",
    ]

    resources = [
      "arn:aws:dynamodb:${data.aws_region.current.name}:*:table/${local.teleport_dynamodb_table}",
      "arn:aws:dynamodb:${data.aws_region.current.name}:*:table/${local.teleport_dynamodb_table}/*",
      "arn:aws:dynamodb:${data.aws_region.current.name}:*:table/${local.teleport_dynamodb_table}/stream/*",
      "arn:aws:dynamodb:${data.aws_region.current.name}:*:table/${local.teleport_dynamodb_table}_events",
      "arn:aws:dynamodb:${data.aws_region.current.name}:*:table/${local.teleport_dynamodb_table}_events/*",
      "arn:aws:dynamodb:${data.aws_region.current.name}:*:table/${local.teleport_dynamodb_table}_events/stream/*",
    ]
  }

  statement {
    sid = "S3EventAccess"

    actions = [
      "s3:Get*",
      "s3:Put*",
    ]

    resources = [
      "${aws_s3_bucket.sessions.arn}/*",
    ]
  }
```

New sessions are stored correctly on S3 and audit data is also correctly stored on DynamoDB. Also, this happens on both sessions created after and before the upgrade.

**Comment by benarent** [comment]
Can you first try to update the permission to add s3:ListBucket, s3:ListBucketVersions and s3:GetObjectVersion. First and let me know if that fixes the issue. 

https://gravitational.com/teleport/docs/aws_oss_guide/#iam

**Comment by iuriaranda** [comment]
Ok, `s3:ListBucketVersions` was the one we were missing. `s3:ListBucket` was already in place but forgot to add it on the issue description.

I assume that the need for `s3:ListBucketVersions` was introduced in a recent version, right?

Thanks a lot for the help.
