### ISSUE TITLE
Document / Teleport FIPS Mode Enterprise

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3097]
**FedRamp Compliance**
With this 4.0 release of Teleport, we have built out the foundation to help Teleport Enterprise customers build and meet the requirements in a FedRAMP System Security Plan (SSP). This includes a FIPS 140-2 friendly build of Teleport Enterprise as well as a variety of improvements to aid in complying with security controls even in FedRAMP High environments. 

> Added "--fips" flag to "teleport start" command which can start
> Enterprise in FedRAMP/FIPS 140-2 mode.
> 
> In FIPS mode, Teleport configures the TLS and SSH servers with FIPS
> compliant cryptographic algorithms. In FIPS mode, if non-compliant
> algorithms are chosen, Teleport will fail to start. In addition,
> Teleport checks if the binary was compiled against an approved
> cryptographic module (BoringCrypto) and fails to start if it was not.
> If a client, like tsh, tries to use non-FIPS encryption, like NaCl,
> those requests are also rejected.

Created Docker Image with FIPS support. https://github.com/gravitational/teleport/issues/3052

Teleport 4.1 added Docker FIPS support https://github.com/gravitational/teleport/releases/tag/v4.1.2 

Add note about  FIPS 140-2 Algorithms.

**Comment by benarent** [comment]
@russjones Apart from https://github.com/gravitational/teleport/issues/3052, and setting --fips. What else is required to run Teleport in FedRAMP/FIPS 140-2 mode.

**Comment by webvictim** [comment]
Local auth has to be disabled in the config file:

```
auth_service:
  authentication:
    local_auth: false
```

Teleport will refuse to start and warn you if this is not the case when run with `—fips` however.

I think it also enforces that `proxy_checks_host_keys` is set to `true` when running in proxy recording mode.

**Comment by benarent** [comment]
Closed via #3129

**Comment by mwos-sl** [comment]
I don't see "fips" suffix tag on distroless `teleport-ent-distroless` docker images. Just to compare:
regular:
![Image](https://github.com/user-attachments/assets/8e893a54-0451-4881-92fc-40bcbd485a54)

vs. distroless:
![Image](https://github.com/user-attachments/assets/58446a30-1604-4de9-b025-2547d7caf2b6)

Also I don't see major relases of `teleport-ent` >= 15.* with "fips" tag suffix too, both for regular and distroless. Questions:

1. If we require docker image compatible with FedRAMP, can we switch to distroless? Is it compatible?
2. What happened with "fips" starting major version 15.*

**Comment by webvictim** [comment]
@mwos-sl As per https://goteleport.com/docs/installation/#version-tags, distroless images can be found here: https://gallery.ecr.aws/gravitational/teleport-ent-fips-distroless
