### ISSUE TITLE
Cloud IAM guide for SSO

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3098]
## Description

Demonstrate the usage of Teleport SAML SSO with Google Cloud IAM. 

The demo and guide should propagate GSuite group memberships and other traits via Google Cloud IAM SAML traits.

Publish the draft to community.gravitational.com and then port it to our SSO guides section.

**Comment by klizhentas** [comment]
cc @bardiashahali

**Comment by webvictim** [comment]
Think this is actually known as Identify Platform: https://console.cloud.google.com/marketplace/details/google-cloud-platform/customer-identity

**Comment by webvictim** [comment]
After testing, this doesn't appear to be possible.

- G Suite SAML works but won't allow you to send groups automatically - you have to configure them manually on a per-user basis
- Identity Platform (both free and premium) seem to rely on a client-side SDK being installed - there is no SAML machine->machine authentication as with Auth0 or Okta.
