### ISSUE TITLE
Issues logging in with new proxy

### ISSUE THREAD

**Issue by jaxxstorm** [gravitational/teleport#310]
I'm getting the following error when trying to login to to a new teleport proxy:

```
INFO[0029] conn(192.168.4.104:51831->192.168.4.34:3023, user=lbriggs) auth attempt with key ssh-rsa-cert-v01@openssh.com 2f:98:da:3f:cb:0e:fb:06:6b:13:de:8a:3b:65:d0:a1  file=srv/sshserver.go:426
WARN[0029] authenticate err: ssh: principal "lbriggs" not in the set of valid principals for given certificate: ["root"]  file=srv/sshserver.go:453 fingerprint=ssh-rsa-cert-v01@openssh.com 2f:98:da:3f:cb:0e:fb:06:6b:13:de:8a:3b:65:d0:a1 local=192.168.4.34:3023 remote=192.168.4.104:51831 user=lbriggs
INFO[0029] conn(192.168.4.104:51831->192.168.4.34:3023, user=lbriggs) auth attempt with key ssh-rsa-cert-v01@openssh.com cd:cd:c1:4b:11:8f:c6:89:91:d2:dc:4f:da:11:d4:b7  file=srv/sshserver.go:426
WARN[0029] authenticate err: ssh: principal "lbriggs" not in the set of valid principals for given certificate: ["root"]  file=srv/sshserver.go:453 fingerprint=ssh-rsa-cert-v01@openssh.com cd:cd:c1:4b:11:8f:c6:89:91:d2:dc:4f:da:11:d4:b7 local=192.168.4.34:3023 remote=192.168.4.104:51831 user=lbriggs
```

I'm assuming it's because I've been using multiple different proxies today as I've been testing, so I need to clear something out from my machine, but not sure what?

**Comment by klizhentas** [comment]
the certificate you've got in your `~/.tsh` was issued for the user `root` when you were adding user:

e.g. 

`sudo tctl users invite` will produce user entry that will be allowed to login as a current os user (in this case root)

then you are trying to log in using `tsh` for example without sudo, tsh will pick your current user name, `lbriggs`. 

I recommend recreate the user that will be capable of logging both as root and lbriggs (for demo purposes):

`sudo tctl users invite lbriggs lbriggs,root` <- this will produce user entry allowed to login as both root and lbriggs so you will be capable of switching users.

lmk if you have any other questions

**Comment by jaxxstorm** [comment]
hmm, something going a bit weird here.

So I:

- Deleted the user using `tctl users del lbriggs`
- Removed `~/.tsh`
- Recreated user and new 2 factor code

Still getting same issue:

From the client:

```
ERROR: access denied to 'lbriggs': bad username or credentials
Enter password for lbriggs:
Enter your HOTP token:
615423
DEBU[0162] not using loopback pool for remote proxy addr: web.leebriggs.lan:3080  file=client/api.go:656
Enter password for lbriggs:
```

**Comment by klizhentas** [comment]
what do the server logs say?

**Comment by klizhentas** [comment]
proxy and node

**Comment by jaxxstorm** [comment]
Errors regarding node and token:

```
RN[0335] password auth error: &teleport.BadParameterError{Traces:trace.Traces{trace.Trace{Path:"/home/alex/go/src/github.com/gravitational/teleport/lib/services/web.go", Func:"github.com/gravitational/teleport/lib/services.(*WebService).CheckPassword", Line:300}}, Param:"password", Err:"passwords do not match"}  file=auth/tun.go:367
```

```
WARN[0333] password auth error: &teleport.BadParameterError{Traces:trace.Traces{trace.Trace{Path:"/home/alex/go/src/github.com/gravitational/teleport/lib/services/web.go", Func:"github.com/gravitational/teleport/lib/services.(*WebService).CheckPassword", Line:307}}, Param:"token", Err:"bad one time token"}  file=auth/tun.go:367
```

I just reconfigured the user and the same issue, confirming password as well. :(

**Comment by klizhentas** [comment]
can you try with another user name? (to see if that's some data sync issue)

**Comment by jaxxstorm** [comment]
Ah, figured it out. It's because the Unix user wasn't present on the box, I didn't realise that it had to be there.

Is this a hard requirement? It's kind of a show stopper for my use case? :(

**Comment by klizhentas** [comment]
Check out user manual users section for details:

http://gravitational.com/teleport/docs/user-manual/#user-identities

basically you'd need to tell what Unix users this particular teleport user can login as, where you can enumerate arbitrary unix names when adding user.

Let me know if that helps

**Comment by jaxxstorm** [comment]
yeah that was the path I was trying, but didn't seem to work unless the Unix user existed. I'll post more details if needed..

**Comment by jaxxstorm** [comment]
I did a bit more debugging today, and at this point I'm convinced there's some kind of bug at play here.

**Comment by kontsevoy** [comment]
This is closely related to #251

**Comment by kontsevoy** [comment]
@jaxxstorm happy to jump on Google hangout to help. I'm in PST TZ.

**Comment by jaxxstorm** [comment]
let's try figure out a time tomorrow?

**Comment by kontsevoy** [comment]
Shoot me an invite for late afternoon PST today (friday) or 8:30am - 11am PST on Monday to ev@gravitational.com

**Comment by jaxxstorm** [comment]
Discussed this with @kontsevoy and it's now resolved in master. Thanks!
