### ISSUE TITLE
Document `max_session_ttl` parameter

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#31095]
There are repeat questions about `max_session_ttl`:
- it is common to assume we do `max(...)` over available values, where in practice we do `min(...)`
- it is unclear in some cases which roles are being taken into account
- the best practices of configuring this parameter, possibly in conjunction with access requests, are not documented

There are numerous support tickets and Slack threads about this topic, so more specifics can be found there.

**Comment by zmb3** [comment]
FYI @jakule - it may make sense to do this while you document the `max_duration` parameter.

**Comment by zmb3** [comment]
See also 

- #26750
- #22496
- #17630
- #12671
