### ISSUE TITLE
Mention that trusted clusters connects from leaf auth to root proxies. 

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#31091]
## Applies To

https://goteleport.com/docs/architecture/trustedclusters/#overview
https://goteleport.com/docs/management/admin/trustedclusters/

## Details

The trusted cluster setup relies on the Auth service leaf connecting to the proxy. That is not directly mentioned in our docs and has led to confusion in some causes on the required connectivity.

## How will we know this is resolved?

Clear that a network connection is required from the leaf auth service to the root proxy address.

**Comment by zmb3** [comment]
FYI @lsgunn-teleport who is working on the trusted cluster docs.

**Comment by lsgunn-teleport** [comment]
docs/img/trusted-clusters/simplified-trusted-cluster.png

> After you establish a trust relationship between the root and leaf clusters, the leaf cluster can
> run behind a firewall without any inbound ports open. The leaf cluster creates an outbound reverse 
> SSH tunnel to the root cluster and keeps the tunnel open.
> When a user tries to connect to any resource in the leaf cluster, the connection goes through the 
> reverse tunnel using the root cluster's proxy.

Would changing this to "using the Teleport Proxy Service instance running on the root cluster" clarify the issue?

> Each leaf cluster dials back to the root cluster to establish a reverse tunnel. If you have multiple 
> proxies, you have multiple tunnels for high availability.

See [#31046] for reference.

**Comment by stevenGravy** [comment]
> docs/img/trusted-clusters/simplified-trusted-cluster.png
> 
> > After you establish a trust relationship between the root and leaf clusters, the leaf cluster can
> > run behind a firewall without any inbound ports open. The leaf cluster creates an outbound reverse
> > SSH tunnel to the root cluster and keeps the tunnel open.
> > When a user tries to connect to any resource in the leaf cluster, the connection goes through the
> > reverse tunnel using the root cluster's proxy.
> 
> Would changing this to "using the Teleport Proxy Service instance running on the root cluster" clarify the issue?
> 
> > Each leaf cluster dials back to the root cluster to establish a reverse tunnel. If you have multiple
> > proxies, you have multiple tunnels for high availability.
> 
> See [#31046] for reference.

We'd want to state the Auth Service on the Leaf Cluster connects to the root cluster.

**Comment by lsgunn-teleport** [comment]
Does this capture it (I'm not sure about adding another diagram-just trying it out)?

After you establish a trust relationship between the root and leaf clusters, the leaf cluster can
run behind a firewall without any inbound ports open. The leaf cluster creates an outbound reverse 
SSH tunnel to the root cluster and keeps the tunnel open.
When a user tries to connect to any resource in the leaf cluster, the Teleport Auth Service on the 
leaf cluster connects to the root cluster through the reverse tunnel using the Teleport Proxy Service 
instance running on the root cluster.

![service-interaction](https://github.com/gravitational/teleport/assets/136391445/cf733f03-863b-4dc9-b115-3013f29ef27a)
