### ISSUE TITLE
Pass SSO Groups in SAMLResponse when using Teleport as a SAML IDP

### ISSUE THREAD

**Issue by nloveupgrade** [gravitational/teleport#31105]
**What would you like Teleport to do?**
When using Teleport as a SAML IDP it [only passes the user's UID and Teleport Roles](https://goteleport.com/docs/access-controls/idps/saml-reference/#assertions-1) in it's SAMLResponse.

I would like Teleport to include the Teleport User's SSO Groups in it's assertions. For example if I am using Okta to login to Teleport I would like all of my Okta groups to be included in the SAMLResponse in addition to the UID and Teleport Roles.

This is already the behavior when using JWT Token Auth in Teleport, I'd love to see it in SAML as well.

**What problem does this solve?**
It's incredibly tedious to switch to Teleport as a SAML provider when you have a good amount of roles from your current SSO provider. You would need to recreate every role and hope that they are assigned correctly. This problem grows the more roles you have.

If the groups from Teleport's SSO provider (i.e. Okta) were included as an assertion in the SAMLResponse it would make the transition far less risky, reduce teleport role clutter, and save many hours of effort.

**If a workaround exists, please include it.**
Right now it's possible to create a Teleport Role and map it to the role in Teleport's SSO Provider, but when you have hundreds of roles this becomes a little unreasonable.

**Comment by flyinghermit** [comment]
Closing this issue as we now support attribute mapping, which can be used to include Okta groups (or any user details coming from upstream SSO provider and available in Teleport user traits) in SAML response asserted by Teleport SAML IdP.

Attribute mapping is available in `v15` and `v14`. 

Here's a reference docs on attribute mapping - https://goteleport.com/docs/access-controls/idps/saml-attribute-mapping/
cc @nloveupgrade
