### ISSUE TITLE
`TestProxyClientDisconnectDueToLockInForce` flakiness

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#31117]
#### Link(s) to logs

- https://github.com/gravitational/teleport.e/actions/runs/5998420136/job/16266671408

#### Relevant snippet

```
    proxy_test.go:464: 
        	Error Trace:	/__w/teleport.e/teleport.e/lib/srv/db/proxy_test.go:464
        	Error:      	An error is expected but got nil.
        	Test:       	TestProxyClientDisconnectDueToLockInForce
```

Seems to be caused by recent change https://github.com/gravitational/teleport/pull/31066 which emits the audit event before disconnecting the client and allows a scenario where the test code pings the connection before it's been disconnected.

**Comment by zmb3** [comment]
@GavinFrazar is this resolved now?

**Comment by GavinFrazar** [comment]
ah, yes it's resolved now thanks. I guess I worded the issue mention in my PR such that github didn't auto-close it.
