### ISSUE TITLE
Login fails on v13.3.6

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#31140]
Expected behavior:
Users should be able to login

Current behavior:
At least two Customers reported that they can't login after upgrading to 13.3.6
WebUI shows `unable to login, please check Teleport's log for details`

Both customers were using Azure as SSO
After clicking on Azure SSO as login option, we receive this error:
![image](https://github.com/gravitational/teleport/assets/689271/7ea5afa6-a651-47b2-bd62-a7dc223e0fa1)

Downgrading to 13.3.5 fixes the issue

Bug details:
- Teleport version: 13.3.6
- Recreation steps
- Debug logs

**Comment by capnspacehook** [comment]
Should be fixed by https://github.com/gravitational/teleport.e/pull/2075

**Comment by marcoandredinis** [comment]
V13.3.7 was released 
https://github.com/gravitational/teleport/releases/tag/v13.3.7
