### ISSUE TITLE
v12: Proxy & Auth anti-affinity are based on same values and causes x2 node scaling

### ISSUE THREAD

**Issue by aardbol** [gravitational/teleport#31145]
Expected behavior:
proxy and auth components should treat anti-affinity separately. This is implemented in [master](https://github.com/gravitational/teleport/blob/e0086909ccb7c4783443ec2c787163c82975de55/examples/chart/teleport-cluster/templates/auth/deployment.yaml#L72) & v13 but hasn't been backported to [v12](https://github.com/gravitational/teleport/blob/77bf3956e8f081607bea79796f763932274e1fc6/examples/chart/teleport-cluster/templates/auth/deployment.yaml#L68) branch

Current behavior:
with 2 replicas of each component, 4 nodes are required instead of 2, thus doubling the costs.

Bug details:
- Teleport version: v12
- Recreation steps
- Debug logs

**Comment by hugoShaka** [comment]
Closing the issue as Teleport 12 is out of support
