### ISSUE TITLE
Autodiscover auth servers using go-discover

### ISSUE THREAD

**Issue by dkrutsko** [gravitational/teleport#3115]
We recently deployed [Consul](https://www.consul.io) onto our AWS infrastructure and they have a nice feature where each client can automatically [discover](https://www.consul.io/docs/agent/cloud-auto-join.html#amazon-ec2) the servers to connect to.

This feature is implemented as part of [go-discover](https://github.com/hashicorp/go-discover), I was wondering if this could be added to Teleport so that it could bed used in `auth_servers`, instead of specifying each IP manually.

**Comment by zmb3** [comment]
I'm going to close this one.

For HA configurations with multiple auth servers we recommend running the auth servers behind a load balancer rather than listing them individually in the configuration.
