### ISSUE TITLE
Create a guide detailing how to configure and use Teleport/tsh on Windows

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3117]
We should have a guide detailing how to use Teleport on Windows.

- how to install OpenSSH client/ssh-agent via Windows features (Windows 10)
- maybe a manual installation guide for Windows 7/8
- SSH config file/ProxyCommand examples using windows paths
- limitations/gotchas when running on Windows

**Comment by webvictim** [comment]
I've made a start on this here - https://community.gravitational.com/t/how-to-connect-to-teleport-hosts-using-windows/559

**Comment by ptgott** [comment]
@webvictim I'm taking a look at this issue as part of [this milestone](https://github.com/gravitational/teleport/milestone/67). Given the release of v8 and our current Desktop Access docs, is there any other work you think we should do here? Thanks!

**Comment by webvictim** [comment]
I think this has definitely got easier now with the addition of `tsh config` (which is Windows-aware). In general desktop access is fairly easy from the client side as it's all in the browser.

**Comment by ptgott** [comment]
@webvictim Here is what I was thinking we could change. Does this work for you?

- New tab for Windows 7/8 in the Windows section of our [installation guide](https://goteleport.com/docs/installation/). We would change the current tab's label to "Windows 10 (Powershell)"
- In our existing [OpenSSH guide](https://goteleport.com/docs/server-access/guides/openssh/), add a `Tabs` box re: how to install OpenSSH/`ssh-agent` on different systems, including Windows.
- Explain how to use `tsh config` and what the expected output is in our [OpenSSH guide](https://goteleport.com/docs/server-access/guides/openssh/), which currently only mentions the command briefly. Include separate tabs for MacOS, Linux, and Windows systems.
- We can talk about limitations/gotchas re: using OpenSSH with Teleport on Windows in a `Details` box in the [OpenSSH guide](https://goteleport.com/docs/server-access/guides/openssh/). Are there any that come to mind that we should definitely include?

**Comment by stevenGravy** [comment]
@webvictim I think we can close this now right?

**Comment by webvictim** [comment]
Yes, this is now handled by docs and `tsh config`.
