### ISSUE TITLE
Suggested improvements for the EC2 discovery guide

### ISSUE THREAD

**Issue by dgkirkwood** [gravitational/teleport#31180]
## Applies To

EC2 Discovery Doc -
https://goteleport.com/docs/server-access/guides/ec2-discovery/

## Details

I found there were multiple times where the documentation was incomplete or incorrect, despite testing with a fairly vanilla AWS and Teleport setup. I was able to work around all of them, but am concerned that the UX could turn off people who are testing this. 

- The v13 docs include a v2 configuration file with auth_servers in [step 4/7](https://goteleport.com/docs/server-access/guides/ec2-discovery/#step-47-configure-teleport-to-discover-ec2-instances). It should be updated to v3 with proxy_server. 

https://github.com/gravitational/teleport/pull/41593

- When running `sudo teleport discovery bootstrap` on an EC2 instance which has its AWS credentials via an Instance Profile (which is how I imagine most people would be following this guide), the bootstrap process gives an error about not knowing which role to attach the new permissions to. As the doc instructs you to run this on an EC2 instance but is not specific about how the AWS credentials are supplied, it should include an instruction to specify the role via `--atttach-to-role` against the bootstrap command

https://github.com/gravitational/teleport/pull/41817

- When running `sudo teleport discovery bootstrap` on an EC2 instance which has its AWS credentials via an Instance Profile (which is how I imagine most people would be following this guide), the command gives an error related to the region. `Failure reason: MissingRegion: could not find region configuration`. The docs should include an instruction to set the region via the `AWS_REGION` env var. 

https://github.com/gravitational/teleport/pull/31401

- On [step 6/7](https://goteleport.com/docs/server-access/guides/ec2-discovery/#step-67-optional-customize-the-default-installer-script) when I ran `tctl get installer/default-installer` this command failed as I did not have permissions to read the installer resource. I was running as a user with access/editor permissions. Possibly due to my roles being long lived but we should include this permission as a pre-req
 
https://github.com/gravitational/teleport/pull/41765

- The first server I tested this on was Amazon Linux 2023 (the first AMI available in the launch wizard). The SSM run command failed with `sudo: yum-config-manager: command not found`. 

https://github.com/gravitational/teleport/pull/34870

- Once I found a server where the SSM command would run, I found the Teleport install was still failing. I found that it was related to the IAM token. When I started the guide I already had an IAM token with a different name to the token in the guide, which I assumed I could use. I could not work out how to alter the discovery service to use my existing IAM token. It would be great to include this in the docs, or point out that the discovery service needs an IAM token with the exact name of `aws-discovery-iam-token` as per [step 1](https://goteleport.com/docs/server-access/guides/ec2-discovery/#step-17-create-an-ec2-invite-token).

https://github.com/gravitational/teleport/pull/41765

## How will we know this is resolved?

Run through the EC2 discovery guide without hitting the six above errors. 

## Related Issues

AL2023 should be supported as per https://github.com/gravitational/teleport/issues/24069

**Comment by philip-teleport** [comment]
Another improvement is to add the following to the Troubleshooting section:
- Another reason for the `InvalidInstanceId: Instances [[i-123]] not in a valid state for account 456` error is that the discovered server with matching tags is not in an AWS account that is allowed to join the cluster, defined by the `aws_account` in the join token. In this scenario, Teleport has been successfully by the SSM agent but the server cannot join the cluster and the following error is shown in the logs: `Error: *status.Error rpc error: code = PermissionDenied desc = instance did not match any allow rules`

**Comment by marcoandredinis** [comment]
> Another improvement is to add the following to the Troubleshooting section:
> 
> * Another reason for the `InvalidInstanceId: Instances [[i-123]] not in a valid state for account 456` error is that the discovered server with matching tags is not in an AWS account that is allowed to join the cluster, defined by the `aws_account` in the join token. In this scenario, Teleport has been successfully by the SSM agent but the server cannot join the cluster and the following error is shown in the logs: `Error: *status.Error rpc error: code = PermissionDenied desc = instance did not match any allow rules`


You now get an audit event saying that Node ip-x-y-z-w failed to join the cluster.
This should allow you to further debug the issue.

**Comment by marcoandredinis** [comment]
All suggestions are applied.
