### ISSUE TITLE
Passwordless Registration fails with `Error parsing attestation response`

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#31187]
Passwordless registration in the WebUI fails with error: `rpc error: code = Unknown desc = Error parsing attestation response`.

git bisect shows that https://github.com/gravitational/teleport/pull/30819 is the cause. I've confirmed that reverting it on Master fixes the issue, but I'm not sure exactly which dependency bump caused the issue. Surprisingly, it doesn't seem to be `github.com/google/go-attestation`.

**Comment by codingllama** [comment]
What device were you using? Did you explicitly enable attestation?

**Comment by Joerger** [comment]
Just my Yubikey 5 Nano, and no special settings.
