### ISSUE TITLE
Add support for auto-user deletion mechanism in database auto user provisioning flow

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#31199]
## What 
Teleport Postgres Auto User provisioning mechanism [RFD](https://github.com/gravitational/teleport/blob/master/rfd/0113-automatic-database-users.md)  should also support auto user deletion similar to Host user provisioning model where a `HOST_USER_MODE_OFF, HOST_USER_MODE_DROP, HOST_USER_MODE_KEEP` options are [available](https://github.com/gravitational/teleport/blob/2e6973470b0607d1557b46c3081fc0df1f334160/integrations/operator/crdgen/testdata/protofiles/teleport/legacy/types/types.proto#L2616). 

To narrow the scope Postgres auto db user deletion should not support on CASCADE method and all objects created by a auto provisioned user should leave unchanged:  [RFD Ref](https://github.com/gravitational/teleport/blob/master/rfd/0113-automatic-database-users.md#disabling-users)

**Comment by zmb3** [comment]
See also #29731

**Comment by greedy52** [comment]
`best_effort_drop` is currently supported for all databases that support db auto-user. All supported modes should be part of the standard feature when supporting a new db for auto-user in the future.
