### ISSUE TITLE
Docker install cant add  Server

### ISSUE THREAD

**Issue by gudge25** [gravitational/teleport#31218]
Docker
using this  How-TO
https://goteleport.com/docs/installation/#example-of-running-a-teleport-container
so i can see docker is up and running 
then. in order to create use  run 
according to doc
https://goteleport.com/docs/#step-34-create-a-teleport-user-and-set-up-two-factor-authentication

docker exec teleport tctl users add teleport-admin --roles=editor,access --logins=root,ubuntu,ec2-user

User "teleport-admin" has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h:
https://localhost:3080/web/invite/a286a803b3001910d2df73e513b32382

so. i went to  https://EXTERNAL_IP:3080/web/invite/a286a803b3001910d2df73e513b32382
and i can manage cluster

inside cluster in order to add server i 
i have command

bash -c "$(curl -fsSL https://EXTENRNAL-IP:3080/scripts/67f36e5f069664691668ee712b99dd24/install-node.sh)"

but  curl exist with cert issue 

so i run again with -k 

bash -c "$(curl -kfsSL https://EXTENRNAL-IP:3080/scripts/67f36e5f069664691668ee712b99dd24/install-node.sh)"

but exit is 

An error has occurred.
The token may be expired or invalid.
Please check log for further details.

**Comment by zmb3** [comment]
> Please check log for further details

Anything interesting in the log?

Would also be helpful to see the output of `tctl tokens ls`.

**Comment by gudge25** [comment]
here is  a log  from deleport docker instance
`2023-08-30T16:51:02Z INFO [WEB]       Failed to return the node install script. error:[
ERROR REPORT:
Original Error: *errors.errorString proxy public_addr is not set, you must set proxy_service.public_addr to the publicly reachable address of the proxy before you can generate a node join script
Stack Trace:
	github.com/gravitational/teleport/lib/web/join_tokens.go:342 github.com/gravitational/teleport/lib/web.getJoinScript
	github.com/gravitational/teleport/lib/web/join_tokens.go:222 github.com/gravitational/teleport/lib/web.(*Handler).getNodeJoinScriptHandle
	github.com/gravitational/teleport/lib/httplib/httplib.go:117 github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1
	github.com/julienschmidt/httprouter@v1.3.0/router.go:399 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	github.com/gravitational/teleport/lib/web/apiserver.go:302 github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP
	github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
	github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
	github.com/gravitational/teleport/lib/httplib/httplib.go:94 github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1
	net/http/server.go:2122 net/http.HandlerFunc.ServeHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.40.0/handler.go:213 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
	net/http/server.go:2936 net/http.serverHandler.ServeHTTP
	net/http/server.go:1995 net/http.(*conn).serve
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: proxy public_addr is not set, you must set proxy_service.public_addr to the publicly reachable address of the proxy before you can generate a node join script] web/join_tokens.go:224
^C2023-08-30T16:52:04Z INFO [PROC:1]    Got signal "interrupt", exiting immediately. pid:7.1 service/signals.go:86`

**Comment by zmb3** [comment]
> `proxy public_addr is not set, you must set proxy_service.public_addr to the publicly reachable address of the proxy before you can generate a node join token`

Looks like you need to provide the `--public-addr` flag on the `teleport configure` command.

**Comment by gudge25** [comment]
> > `proxy public_addr is not set, you must set proxy_service.public_addr to the publicly reachable address of the proxy before you can generate a node join token`
> 
> Looks like you need to provide the `--public-addr` flag on the `teleport configure` command.

Yahoo )
so 2 add. steps needed
1- Change teleport configure command to 
 `docker run --hostname localhost --rm \
  --entrypoint=/usr/local/bin/teleport \
  public.ecr.aws/gravitational/teleport-distroless:13.3.6 configure --roles=proxy,auth  --public-addr:example.com:3080 > ~/teleport/config/teleport.yaml`

2-running Teleport service with --insecure
`teleport start --config="/etc/teleport.yaml" --insecure`


thanks @zmb3

**Comment by gudge25** [comment]
Resolved
