### ISSUE TITLE
Tabbed Terminal Search

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#3123]
Search functionality for Tabbed Terminal. This will need to include the following: 
- List of nodes available in the cluster
- Blankstate for when all the tabs are closed

**Comment by benarent** [comment]
Design Spec: 
[Teleport 4.3 - Hornet ( aka Redesign ) - Terminal](https://docs.google.com/document/d/1gMyMYFxPhYSMz9OT_BVCOTKmGPgtcYCOxmQBa9XddCA/edit#heading=h.8tlerqzgnrn2)

**Comment by benarent** [comment]
Closing this ticket as we've addressed these issues in other tickets.
