### ISSUE TITLE
Detailed View of session player

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#3124]
There are some outstanding design items for the session player: 
- Design for all the text in the consoles
- Design for blankstate for each tab when not enabled
- Design for blankstate of toggle when not enabled 

[Teleport 4.3 Product Spec for Session Player](https://docs.google.com/document/d/1gMyMYFxPhYSMz9OT_BVCOTKmGPgtcYCOxmQBa9XddCA/edit#heading=h.7ffaxc53bxz)

**Comment by benarent** [comment]
Closing as @alexwolfe will create smaller tickets for specific issues.
