### ISSUE TITLE
Teleport Navigation

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#3125]
Make sure there is a clear way to get from the cluster view back to the Cluster Dashboard view.

**Comment by alexwolfe** [comment]
#### Individual Cluster View
![Audit Log - System Events](https://user-images.githubusercontent.com/407237/68234677-94f92f00-ffb6-11e9-817c-464ed3ffa8c2.png)

#### All Clusters Dashboard
![All Clusters](https://user-images.githubusercontent.com/407237/68236220-a09a2500-ffb9-11e9-83d0-d5b7a9942220.png)

Ok, please take a look at the navigation on both of these screens. Below is the proposed functionality for how this will operate: 

1. When a user clicks on the Teleport logo they will navigate back to the "All Clusters Dashboard" 
2. This behaviour is the same whether they are in the dashboard or individual cluster view.

**Comment by alexwolfe** [comment]
Please note the subtle visual change I made to the side nav logo (line underneath)

**Comment by alex-kovoy** [comment]
Thanks Alex! 
Another thing to look for is that there is no "public URL"  and "Info" button.

**Comment by alex-kovoy** [comment]
finished (in webapps)
