### ISSUE TITLE
Add ability to create ServerInfo resources for users

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#31261]
As part of [refactoring AWS auto-discovery](https://github.com/gravitational/teleport/pull/27476) to pull tags via API, we introduced a `ServerInfo` resource that allows to augment labels heartbeat by nodes themselves.

```yaml
kind: ServerInfo
metadata:
  name: xxx
spec:
  new_labels:
    a: b
    c: d
```

Right now this resource is only used internally in auto-discovery to update the labels of auto-discovered EC2 instances but we should expose ability to create this resource for users as well via tctl/API so they can control node labels server-side.

Main thing to think about is how to map ServerInfo onto a Server to merge labels with, it should be ok to require 1-to-1 mapping by some unique server property e.g. ID or IP address. Some more details [here](https://github.com/gravitational/teleport/pull/27476#pullrequestreview-1477445128).

**Comment by jeffjen** [comment]
Bump
