### ISSUE TITLE
Principles are set in  locality.

### ISSUE THREAD

**Issue by binoue** [gravitational/teleport#3126]
**What happened**:
In auth pod logs, the locality and the timestamp are not what we expected.

We got this log at **Thu Oct 31 05:31:48 UTC 2019**.

- Log:
INFO [CA]        Generating TLS certificate {0x3339ea0 0xc001647390 CN=xxxx,O=admin,POSTALCODE=null,STREET=,**L=XXXX 2019-10-31 17:16:21.578351235 +0000 UTC []**}. common_name:xxxx dns_names:[] **locality:[XXXX]** not_after:2019-10-31 17:16:21.578351235 +0000 UTC org:[admin] org_unit:[] tlsca/ca.go:203

Probably, this is caused by [this code](https://github.com/gravitational/teleport/blob/v4.1.3/lib/tlsca/ca.go#L112) in [this pull request](https://github.com/gravitational/teleport/pull/2187).

We are not sure that this behavior is intended or not.

**What you expected to happen**:
We expected the locality was empty and the timestamp was UTC.

**How to reproduce it (as minimally and precisely as possible)**:
Create teleport environment with github auth.

**Environment**:
- Teleport version (use `teleport version`): v4.1.3
- Tsh version (use `tsh version`): v4.1.3
- OS (e.g. from /etc/os-release): Ubuntu:18.04

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by webvictim** [comment]
The locality field containing principals is expected as that’s exactly what the pull request dictates. There are a limited number of available fields on certificates so some have to be overloaded/used for purposes that aren’t exactly what their labels state. The certificates are only intended for internal use by Teleport and its users.

With regard to the timestamp, what is the TTL configured to be for the role that this certificate was generated for?

**Comment by binoue** [comment]
Thank you for your reply.

I understood containing principles in the locality field is intentional. Also, TTL is set as default(12h), so the timestamp is correct.

I fix the title and close this issue.
