### ISSUE TITLE
where is teleport.yaml

### ISSUE THREAD

**Issue by LinX9581** [gravitational/teleport#31270]
Expected behavior:
teleport.yaml should be in /etc/teleport.yaml?

Current behavior:
I use "curl https://goteleport.com/static/install.sh | bash -s 13.3.7" to install teleport
But I can't find /etc/teleport.yaml

find ./ -name "teleport.yaml" -> empty

Bug details:
- Teleport version 13.3.7 , GCE VM Linux Ubuntu2004
- Recreation steps
- Debug logs

**Comment by stevenGravy** [comment]
@LinX9581 Installing `teleport` does not generate a `/etc/teleport.yaml`.  A configure step as shown here will create a `/etc/teleport.yaml` file.

**Comment by stevenGravy** [comment]
Recommend going to our slack channel or discussions if you have further ?s.
