### ISSUE TITLE
Download link in Help & Support goes to generic deprecated page

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#31277]
Expected behavior:

The download link would take the user to either the downloads page or a informational page on downloads.

Current behavior:

The user gets a message that `dashboard.gravitational.com` has been deprecated. No information on downloads is given.

Bug details:
- Teleport version: 14 alpha
- Recreation steps

Select Help and Support Under username
Select Downloads

<img width="216" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/0563452f-f94b-494c-9932-18576e269aca">

**Comment by zmb3** [comment]
@avatus do you mind taking this one? I would just link to goteleport.com/download and call it a day.

**Comment by avatus** [comment]
Yup, will do
