### ISSUE TITLE
Adjustments to Unified Resources UI

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#31302]
---
TODO
- [ ] (defered) Can get into a state where borders disappear before cards break to 1 across
- [ ] (defered) Move cluster dropdown to filters where there are connected clusters, with same default selection behavior; user cannot clear the value (for now); hide cluster selector where there is only one cluster/there are no leaf clusters.

---
In Reivew

https://github.com/gravitational/teleport/pull/31518
- [x] breakpoints don’t align with the switches in card size
  - [x] Can get into a state where there horizontal scrolling with 2 items across (our current min-width wont allow us to go below 2 cards, but the layout itself is fixed. this will automatically be fixed once sidebar is gone)
  - [x] Can get a state where there are 4 items across with horizontal scrolling

---
Done
- [x] Need tooltips on any icon buttons, incl. segmented. For now that's just the sort button.
- [x] Sort button should be up/down arrows rather than chevrons, so that it doesn't look so much like it's a drop-down indicator.
  - [x] Can find SVG files in Google Drive exports—looks like the Icons set only has left/right arrows. Please add to "Icons" rather than "Custom Icons," as the latter is mostly outdated.
- [x] Filter and sort buttons are much too big
- [x] Filter and sort buttons should have different styling so they do NOT look too similar to one another—they have different functions, and we want to hint at that with their styling
  - [x] Filter buttons should be secondary-style buttons
  - [x] Sort buttons should be outlined
- [x] There’s a weird thing going on with our button padding that has the caret overlapping the padding such that the padding looks unbalanced but that’s in the old CONNECT buttons, too, so it isn’t a regression
- [x] Card background was meant to be transparent until hovered. Then if we need to use these somewhere else, say, that has a different background level, they’ll still look flat.
- [x] Reverse tunnel text should be hidden
- [x] Labels: section height is currently 26px with label height of 24px; should be 20px for both.
- [x] Remove top margin on resource images. I'd originally gone back-and-forth on whether to center or top-align them, and especially with the current implementation being a bit taller than the designs, center alignment looks a bit more sloppy. Top alignment will create more consistently clean lines.
- [x] Card titles (resource names) should be 300 weight
- [x] Still using the wrong resource icons from “Custom Icons” set rather than “Icons” set. They’re oversized compared to the intended set, which has built in padding.
- [x] Add skeleton loader for each load event with smooth transitions fading old content out and/or new content in.
- [x] Labels
  - [x] Probably more effective layout to cap the width of the labels row with `overflow: hidden;`  so that you don’t need the `+X more` background to hide the labels where they overlap, which currently looks quite wonky when the card is hovered (because the background isn’t changing with the card). (LMK if you want to pair on this; I'm pretty good at manipulating HTML and CSS)

**Comment by roraback** [comment]
LMK if you'd like me to attach screenshots. For now I've left them out so I don't break up the checklist too much.

**Comment by avatus** [comment]
Checked off some things that will be handled here: https://github.com/gravitational/teleport/pull/31474

**Comment by avatus** [comment]
https://github.com/gravitational/teleport/pull/31623

**Comment by avatus** [comment]
Skeleton loader: https://github.com/gravitational/teleport/pull/31677

**Comment by zmb3** [comment]
@avatus is there anything else we are both waiting on and planning to address soon? If not, let's close this out.

**Comment by avatus** [comment]
You can close this as the final two will be done when we remove the sidebar this quarter
