### ISSUE TITLE
Document `max_age` in OIDC connector

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#31320]
## Applies To

- docs/pages/access-controls/sso/oidc.mdx
- examples/resources/oidc-connector.yaml

## Details

Document the existence of `max_age` setting in our OIDC connector, starting from v13 onward.

Also, it seems that Google OIDC doesn’t return an `auth_time` claim, so if `max_age` is set, then all auth attempts fail:

```
$ tsh login --auth=google
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:60369/ad086ad3-d707-4028-8ef8-7bdbe0380bde
ERROR: identity provider callback failed with error: Invalid parameters received from OIDC provider.
	OAuth2 error code=access_denied, message=missing claim auth_time
```

This isn't a bug with Teleport. Google is just out of spec (intentionally, apparently 🙄 ).
I think it would be worse if we just silently ignored the missing claim when the connector has max_age set.
What I think we should do is:

- [ ] document the `max_age` setting (not sure if this is in the works already)
- [ ] document the fact that it does not work with Google OIDC or Gitlab
- [ ] when a user tries to set max_age in a google oidc connector, return an error linking them the documentation.
- [ ] when a user tries to set max_age in a gitlab oidc connector, return an error linking them the documentation.

see: https://stackoverflow.com/questions/29748579/google-openid-connect-receiving-a-500-error-when-supplying-the-max-age-parame/29749870#29749870

## Related Issues

`max_age` was added in https://github.com/gravitational/teleport.e/pull/1915 and backported to v13.

**Comment by capnspacehook** [comment]
Note that `max_age` doesn't work correctly with Gitlab either, they will return an invalid config error if it is set.

**Comment by zmb3** [comment]
Completed with #31800
