### ISSUE TITLE
CentOS 6 and scp

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3132]
In https://github.com/gravitational/teleport/issues/2783, we recommend compiling a parallel libc to run Teleport on CentOS 6 boxes. Compiling and setting `LD_LIBRARY_PATH` correctly in the startup script allows Teleport to start, but Teleport fails with the following when attempting to scp a file.

```
[...]
ERRO [CLIENT]    EOF client/client.go:593
[...]
Original Error: *ssh.ExitError Process exited with status 1
```

The reason is Teleport attempts to re-execute itself, by looking up it's own path, and then executes itself without the updated `LD_LIBRARY_PATH` and fails to start.

A temporary workaround is to update `~/.bashrc` to export this variable as `~/.bashrc` is read before bash executes `teleport scp`.

The long term fix is another point towards releasing CentOS 6 binaries.

**Comment by zmb3** [comment]
Closing as we no longer support CentOS 6
