### ISSUE TITLE
New two-factor device not added through Web UI when name is not set

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#31350]
Expected behavior:
The dialog box should prevent me from closing the window if the device name is not set

Current behavior:
The device name box briefly flashes red, and the dialog is closed without adding a new device.

Bug details:
1. Open Account Settings.
2. Click two-factor device.
3. Enroll into the OTP app.
4. Click "Add device" without setting a device name.

**Comment by zmb3** [comment]
<img width="567" alt="image" src="https://github.com/gravitational/teleport/assets/7527103/27848c73-f439-4ed8-b155-973db6d21056">

The "add device" button should be disabled unless the code and name are provided.
