### ISSUE TITLE
kubernetes_resources kind namespace for roles

### ISSUE THREAD

**Issue by metsoft68** [gravitational/teleport#31357]
What would you like Teleport to do?
I'm interested to have the option in kubernetes_resources to have the kind of namespace in roles
which then I can filter the namespaces can see by regular expression when the user issues `kubectl get ns`

What problem does this solve?
just filtering out the only namespaces that users need to see, like the pods feature which is already there. I need to have same implementation for the Kind: namespace

If a workaround exists, please include it.
no

**Comment by tigrato** [comment]
@metsoft68 

This feature will be included in Teleport 14, released in a few weeks.
In the meanwhile, you can test yourself - but not in production - the behavior of 

```yaml
kubernetes_resources:
- name: yourNamespace
  kind: namespace
  verbs: '*' # edit, patch, create,get,list...
```

This will give your users access to all resources within that namespace and prevent users from accessing resources from other namespaces including namespaced custom resources. Replace the version in the download link with `14.0.0-alpha.2` and it will download the alpha version of Teleport 14. Use it only for kube access

If you need help, ping me on Teleport Community slack
