### ISSUE TITLE
Proxies not accepting connections while in a loop invalidating cache

### ISSUE THREAD

**Issue by aashley** [gravitational/teleport#3137]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**: frontend proxies stopped responding to all connection attempts

**What you expected to happen**: connections to continue as normal

**How to reproduce it (as minimally and precisely as possible)**: Not sure cluster was working as expected at 10pm this morning by 2am it was not accepting connections. no config changes occurred.

**Environment**:
- Teleport version (use `teleport version`): Teleport v4.1.4 git:v4.1.4-0-gc487a75c go1.13.2
- Tsh version (use `tsh version`):Teleport v4.1.4 git:v4.1.4-0-gc487a75c go1.13.2
- OS (e.g. from /etc/os-release): ubnutu 16.04

**Browser environment**

- Browser Version (for UI-related issues): Chrome 78
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: WARN [PROXY:SER] Request for connection to remote site failed: od-server-00119 is offline: no active tunnels to od-teleport found. cluster:od-server-00119 reversetunnel/remotesite.go:593
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: WARN [REVERSE:O] Re-init the cache on error: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing od-server-00119 is offline". cache/cache.go:336
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: WARN [REVERSE:O] Re-init the cache on error: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing od-server-00119 is offline". cache/cache.go:336
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: WARN [REVERSE:O] Re-init the cache on error: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing od-server-00148 is offline". cache/cache.go:336
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: WARN [REVERSE:O] Re-init the cache on error: unknown method GetUsers. cache/cache.go:336
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: INFO [PROXY:SER] Connection <- 203.54.161.134:38844, clusters: 62. cluster:od-server-00359 reversetunnel/srv.go:855
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: WARN [PROXY:SER] Request for connection to remote site failed: od-server-00359 is offline: no active tunnels to od-teleport found. cluster:od-server-00359 reversetunnel/remotesite.go:593
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: WARN [REVERSE:O] Re-init the cache on error: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing od-server-00359 is offline". cache/cache.go:336
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: WARN [REVERSE:O] Re-init the cache on error: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing od-server-00359 is offline". cache/cache.go:336
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: WARN [REVERSE:O] Re-init the cache on error: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing od-server-00354 is offline". cache/cache.go:336
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: WARN [REVERSE:O] Re-init the cache on error: unknown method GetUsers. cache/cache.go:336
Nov 12 06:39:22 ip-172-32-11-122 teleport[16778]: WARN [REVERSE:O] Re-init the cache on error: unknown method GetUsers. cache/cache.go:336

Getting thousands of the Re-init the cache on error messages on the proxy nodes. Getting no errors on the auth nodes, in fact not getting any log messages at all on the auth nodes. Putting into debug mode doesn't supply any extra information.

**Comment by zmb3** [comment]
I'm going to close this one due to inactivity since there have been many improvements to Teleport since the v4 release.
