### ISSUE TITLE
Quickstart link in Web UI Help & Support

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#31372]
Expected behavior:

The quickstart link would take a user to learning about Teleport as a user and/or admin.

Current behavior:

The quickstart link takes you to deploying Teleport in community edition. As you're already in a deployed Teleport not clear how that helps the user.

Bug details:
- Teleport version: 14
- Recreation steps

1. Open the Help & Support page under username in WEb UI
2. Select quickstart under resources.
3. Lands on goteleport.com/docs that is currently how to deploy a OSS Teleport.

**Comment by zmb3** [comment]
@roraback or @xinding33 - any suggestions for better places to link to, or should we just remove this link from the product? I agree it doesn't make much sense to link to "how to deploy teleport" from an already deployed cluster.

**Comment by zmb3** [comment]
Fixed in #34251
