### ISSUE TITLE
tctl sso configure github does not generate a correct yaml file

### ISSUE THREAD

**Issue by mkysel** [gravitational/teleport#31387]
Expected behavior:
The yaml generated by `configure github` can be directly used, or at least `test` will pass.

Current behavior:
Invalid yaml leads to:
```
$ cat github.yaml | tctl sso test
ERROR: Failed to create auth request. Check the auth connector definition for errors. Error: rpc error: code = Unknown desc = url scheme is empty
```

Bug details:
$ tctl version
Teleport v13.3.7 git: go1.21.0

Repro steps:
Follow the documentation here https://goteleport.com/docs/access-controls/sso/github-sso/#step-23-create-a-github-authentication-connector
The generated yaml file will start with:
```
$ cat github.yaml 
kind: github
metadata:
  name: github
spec:
  api_endpoint_url: ""
```

It seems that the `api_endpoint_url` has to be set to `https://api.github.com`.

Once set, the test will succeed and the config can be used to authenticate with github SSO.

**Comment by stevenGravy** [comment]
@mkysel , the API endpoint url will default to `https://api.github.com` if it's not set.  I tested this and did not get that error. Can you confirm if you put that github config as a auth connector what you get?

**Comment by mkysel** [comment]
When mocking around with this, I also noticed that the org name is case sensitive. Which tripped me over. Our org is called `SecureDNA` but I was providing `securedna` as the slug.
For example `--teams-to-roles=securedna,dev-ops,access,editor`

The Teleport docs talk about team names, not really org names:
> To create the slug, GitHub replaces special characters in the name string, changes all words to lowercase, and replaces spaces with a - separator.

The log in this case is:
```
  "error": "user does not belong to any teams configured in connector; the configuration may have typos.",
  "event": "user.login",
  "message": "Failed to calculate user attributes.\n\tuser does not belong to any teams configured in connector; the configuration may have typos.",
  "method": "github",
  "success": false,
```

**Comment by stevenGravy** [comment]
No sounds like the same issue as Team names. We can see about making the docs more clear. Please go ahead and close the issue if GitHub auth is now working for you.

**Comment by franciscoprin** [comment]
I am getting the same error than above, and the only solution was to set:
```yaml
  api_endpoint_url: "https://api.github.com"
  endpoint_url: "https://github.com"
```
It will be nice that this would be reflected in the docs here.

In theory the command `cat github.yaml | tctl sso test` should use the default values for `api_endpoint_url` and `endpoint_url` but, it isn't doing it.
