### ISSUE TITLE
No AWS logo for AWS Console Access

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#31381]
Expected behavior:
Starting with 14, we've lost support for the AWS logo. 

<img width="1195" alt="image" src="https://github.com/gravitational/teleport/assets/559288/e138320e-3bf0-4685-953c-29c918ac852c">

### Early Designs 
<img width="603" alt="image" src="https://github.com/gravitational/teleport/assets/559288/af627fc6-289c-4f40-8009-7d6eed5904f9">

Current behavior:

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by avatus** [comment]
Will be fixed once https://github.com/gravitational/teleport/pull/31178 goes in

**Comment by zmb3** [comment]
@avatus are we good to close this one?

**Comment by avatus** [comment]
Yes. closing
