### ISSUE TITLE
Anonymize applications public address with random string

### ISSUE THREAD

**Issue by sblonder** [gravitational/teleport#31406]
What would you like Teleport to do?
Generate a temporary string for the public URL when an application is launched through the UI. 

What problem does this solve?
Hackers can use subdomain mapping tools to gain information about the cluster. 

If a workaround exists, please include it.
public_addr can be randomized for each application in node configuration file, but this complicate node setup and less secure than a ranodmized on-demand name.

**Comment by zmb3** [comment]
Interesting suggestion, but not likely to be implemented any time soon so I'm going to mark not planned.
