### ISSUE TITLE
[Web] GitHub Auth Connector tile is larger and misaligned with other tiles

### ISSUE THREAD

**Issue by rudream** [gravitational/teleport#31460]
The GitHub tile in the empty state on the Auth Connectors page is larger than the OIDC & SAML tiles.

![image](https://github.com/gravitational/teleport/assets/56373201/18c48e0b-2549-4aff-8e24-91bd4b36c06f)

**Comment by zmb3** [comment]
I think this was intended for OSS, so that we emphasized GitHub and added an enterprise CTA for the others. cc @roraback to confirm.

But I agree in enterprise builds they should all be equally sized.

**Comment by michellescripts** [comment]
Yep they should be equal: https://www.figma.com/file/8DQZl1mYUPLgvKgmA6zPOM/In-Progress-Work?type=design&node-id=4809%3A87216&mode=design&t=dTGfbOZxpjfV585h-1
