### ISSUE TITLE
No QR code when adding OTP device through tsh mfa add, but the app suggests it should be there

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#31482]
Expected behavior:
I expected to see a QR code upon clicking a link that is given to me by `tsh mfa add`. Or perhaps a QR code printed on a console. :)

Current behavior:
`tsh mfa add` prints: "Open your TOTP app and scan the QR code", but doesn't give any QR code. It prints out a URL that starts with `otpauth://totp/bartosz-staging-3.cloud.gravitational.io:admin@bartosz-staging-3.cloud.gravitational.io:443`. After clicking it, I'm being redirected to the system settings/passwords applet and given an opportunity to register the system's built-in OTP mechanism.

Bug details:
- Teleport version: 14.0.0-alpha.2
- Recreation steps Use `tsh mfa add` on a MacOS device

**Comment by zmb3** [comment]
I"m not able to reproduce this.

<img width="1326" alt="image" src="https://github.com/gravitational/teleport/assets/7527103/f344ff41-c418-4861-be64-ac52aa942d1e">

Preview opens up with a QR code for me.
