### ISSUE TITLE
`teleport app start` fails

### ISSUE THREAD

**Issue by mdwn** [gravitational/teleport#31496]
Expected behavior:

`teleport app start` should succeed.

Current behavior:

`teleport app start` fails with an error message. There appears to be no way to supply the expected proxy-server variable.

Bug details:
- Teleport version: 14.0.0-alpha.2
- Recreation steps: Run `teleport app start`, for example:

```
./teleport app start --name demo-app-2 --uri "http://localhost:9000" --proxy-server punch.teleport.localhost:443 --config /Users/mike/tmp/teleport-ent/config/teleport.yaml
```

- Debug logs

```
➜  teleport-ent ./teleport app start --name demo-app-2 --uri "http://localhost:9000" --auth-server punch.teleport.localhost:443 --config /Users/mike/tmp/teleport-ent/config/teleport.yaml
ERROR: configuration error
initialization failed
config: when app_service is enabled, proxy_server must be specified instead of auth_server
...
➜  teleport-ent ./teleport app start --name demo-app-2 --uri "http://localhost:9000" --proxy-server punch.teleport.localhost:443 --config /Users/mike/tmp/teleport-ent/config/teleport.yaml
teleport: error: unknown long flag '--proxy-server'
```

**Comment by zmb3** [comment]
Does this repro on v13 as well?

**Comment by mdwn** [comment]
> Does this repro on v13 as well?

Just wanted to acknowledge that I saw this, I'll attempt to repro when I'm able.

**Comment by mdwn** [comment]
Hey all, sorry for the delay. Yes, this does repro on v13.

**Comment by r0mant** [comment]
I think we wanted to deprecate all `teleport xxx start` commands anyway in favor of `teleport config` + `teleport start` so I'm not sure we should even spend time adding this flag. I propose we just close this as "won't fix".
