### ISSUE TITLE
webauthnwin: generate types from windows webauthn header

### ISSUE THREAD

**Issue by tobiaszheller** [gravitational/teleport#31559]
Currently types used to call webauthn.dll are created manually. 
That's approach is quite fragile and can be source of bugs, example: https://github.com/gravitational/teleport/pull/31407

It should be possible to generate types based on header file.

Possible options:
1. https://github.com/xlab/c-for-go 
2. go generate with golang.org/x/sys/windows/mkwinsyscall (windowsauth already uses it in teleport.e).

**Comment by zmb3** [comment]
+1 for `mkwinsyscall`

**Comment by codingllama** [comment]
I wend ahead and moved us to mkwinsyscall. Sadly, it doesn't generate the structs from the header.

I've also looked at https://github.com/xlab/c-for-go, but it's a lot less obvious to make work. I'll call this closed once mkwinsyscall lands, I don't see us doing any follow ups after that.
