### ISSUE TITLE
Resizing web terminal is broken

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#31565]
Expected behavior:

Resizing an active web terminal results in the session being resized.

Current behavior:

Resizing web terminal doesn't work, old dimensions are sticky. This only affects web terminal, regular `SSH` session behaves correctly.

Bug details:
- Teleport version: `Teleport v14.0.0-alpha.2 git:api/v14.0.0-alpha.2-0-g71aea8d go1.21.0`
- Recreation steps: 

1. Open new session via web UI.
2. Start `htop` or other full-terminal program (for ease of observation).
3. Resize browser window. 
4. Observe malformed output: the old terminal dimensions remain in effect.
5. Observe the warning being logged:

```
2023-09-07T13:10:21Z WARN [WEBSOCKET] Failed to parse resize payload: json: cannot unmarshal number into Go value of type string session_id:447db0bb-408f-4932-9354-04eace45e7ec web/terminal.go:1115
```

**Comment by zmb3** [comment]
The payload is 

```
{"event":"resize","width":105,"height":53,"size":"105:53"}
```

We're trying to unmarshal this into a `map[string]string` - so it's `width` and `height` that are breaking it. Not sure when this might have changed.

**Comment by zmb3** [comment]
@rosstimothy maybe this regressed in #25988?
