### ISSUE TITLE
tsh ls --help minor documentation issue

### ISSUE THREAD

**Issue by jkendzorra** [gravitational/teleport#3156]
There seems to be a copy'n'paste mistake in `tsh ls --help` which shows the same error message for two different flags:
```
(...)
      --cluster             Specify the cluster to connect
  -v, --verbose             Specify the cluster to connect
```
Would be great if the help text for -v would include the information from https://github.com/gravitational/teleport/issues/2264 (about labels not being wrapped).

**Comment by wadells** [comment]
This would be a good first issue for @quinqu if we can wait a month for them to start.
