### ISSUE TITLE
Unable to add a v13 tunnel agent to a v14 cluster

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#31607]
Expected behavior:

Agents get added to the cluster and are connectable/routable.

Current behavior:

Agents never connect to the Proxy.

The Proxy continusously logs:
`2023-09-07T16:57:21-04:00 WARN [SSH:PROXY] Error occurred in handshake for new SSH conn error:[ssh: overflow reading version string] pid:4337.1 remote_addr:127.0.0.1:59869 sshutils/server.go:482`

The agent continuously logs:
`2023-09-07T16:57:01-04:00 ERRO [PROC:1]    Instance failed to establish connection to cluster: Failed to connect to Proxy Server through tunnel: connection error: desc = "transport: Error while dialing: failed to dial: ssh: handshake failed: EOF". pid:5379.1 service/connect.go:123`

The initial payload from the agent:

```
Teleport-Proxy{"tracingContext":{"traceparent":"00-f5015567ef06d4c77a10354b761d70d9-ca5e5dfbbaad8bbe-01"}}SSH-2.0-Go
<
��߷}di0j��t9h�curve25519-sha256,[curve25519-sha256@libssh.org](mailto:curve25519-sha256@libssh.org),ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie
```

https://github.com/gravitational/teleport/pull/29670 removed support for the `ProxyHelloSignature` but v14 still needs to support receiving the payload from older clients.

**Comment by AntonAM** [comment]
Fixed by https://github.com/gravitational/teleport/pull/31649 (we only need it in branch v14, not in master)
