### ISSUE TITLE
Automatically assume the default RDP port for non-AD Desktop access

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#31646]
What would you like Teleport to do?
Right now, RDP access will fail if an address is defined for the `addr` section without including the RDP port `:3389`

Request is to make the default port used be :3389 if there is no other port specified in the `addr` for the desktop resource.

What problem does this solve?
This helps users who may not be aware the port is required to automatically connect with fewer issues.

If a workaround exists, please include it.
explicitly add the port

**Comment by stevenGravy** [comment]
The hosts section assumes `3389`. Which `addr` is this referring to? We just have the LDAP `addr` AFAIK.
