### ISSUE TITLE
Audit Log Performance

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3166]
With Teleport 4.2, Teleport will be emitting substantially more information to the audit log. Not only will the amount increase, but the rate at which events are emitted will increase substantially as well.

To handle this we need to look at doing some bench marking of the audit log to see how many events can we currently emit per second and how to scale it. We should also look into what filters we can possibly apply to allow administrators to opt-out of certain types of events they are not interested in.

From a implementation perspective, right now submitting events to the Audit Log is just a HTTP  POST. We should move to a GRPC streaming API to improve performance.

**Comment by benarent** [comment]
Other thoughts.
 - Adding benchmarking and load testing to release testing.
 - How to integrate with third party tools like ( [e.g Splunk Add-On](https://docs.splunk.com/Documentation/AddonBuilder/2.2.0/UserGuide/Overview) [DataDog](https://docs.datadoghq.com/logs/log_collection/go/) uses  [Logrus](https://github.com/sirupsen/logrus)

**Comment by zmb3** [comment]
@russjones can we close this one? I imagine the audit log that existed in 4.2 looks nothing like the one we have today.

**Comment by russjones** [comment]
Yeah, let's close, it's really outdated.
