### ISSUE TITLE
Openssh agentless instruction without teleport binary on target 

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#31705]
## Applies To

https://goteleport.com/docs/server-access/guides/openssh/

## Details
The current documentation  only details openssh agentless instructions where Teleport binary can be copied to the sshd host. The documentation should also include clear instructions to follow for a target that is not capable of running a teleport binary (targets hosts like network devices).

## How will we know this is resolved?
Successfully Configure sshd by registering the OpenSSH node to teleport without having to Copy the teleport binary to the sshd host

## Related Issues
https://github.com/gravitational/teleport/issues/31681

**Comment by zmb3** [comment]
Fixed by #31647 (when it merges)
