### ISSUE TITLE
Support for GCP Cloud Spanner 

### ISSUE THREAD

**Issue by BenCoughlan15** [gravitational/teleport#31714]
What would you like Teleport to do?
Provide support for Cloud spanner access from Teleport. 

What problem does this solve?
It allows me to test my application, end to end, as datas would be written to the correct DB. 

I'd also benefit from traces, etc. 

If a workaround exists, please include it.
We run an emulator, but it's of limited use, particularly for async/event driven calls.

**Comment by webvictim** [comment]
Related:
- https://github.com/gravitational/teleport/pull/40859
- https://github.com/gravitational/teleport/pull/41129

**Comment by GavinFrazar** [comment]
This was added in https://github.com/gravitational/teleport/pull/40859
