### ISSUE TITLE
Teleport not working with PAM module, undefined symbol: pam_get_user

### ISSUE THREAD

**Issue by brandstettermichael** [gravitational/teleport#3171]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:

I enabled PAM on teleport using SSHD service with a jail shell pam module ( https://github.com/pymumu/jail-shell/ ).

When I use "tsh ssh user@server" I get the error: "error: Module is unknown error: ssh: could not start shell"

In /var/log/auth.log I have this error:
` PAM unable to dlopen(pam_jail_shell.so): /lib/security/pam_jail_shell.so: cannot open shared object file: No such file or directory`

I tried changing the path to "pam_jail_shell.so" to "/lib/x86_64-linux-gnu/security/pam_jail_shell.so" in **/etc/pam.d/common-session**

/etc/pam.d/common-session:
```
# /etc/pam.d/common-session - session-related modules common to all services
#
# This file is included from other service-specific PAM config files,
# and should contain a list of modules that define tasks to be performed
# at the start and end of sessions of *any* kind (both interactive and
# non-interactive).
#
# As of pam 1.0.1-6, this file is managed by pam-auth-update by default.
# To take advantage of this, it is recommended that you configure any
# local modules either before or after the default block, and use
# pam-auth-update to manage selection of other modules.  See
# pam-auth-update(8) for details.

# here are the per-package modules (the "Primary" block)
session	[default=1]			pam_permit.so
# here's the fallback if no module succeeds
session	requisite			pam_deny.so
# prime the stack with a positive return value if there isn't one already;
# this avoids us returning an error just because nothing sets a success code
# since the modules above will each just jump around
session	required			pam_permit.so
# and here are more per-package modules (the "Additional" block)
session	required	pam_unix.so 
session	optional	pam_systemd.so 
# end of pam-auth-update config
session required	/lib/x86_64-linux-gnu/security/pam_jail_shell.so
```

But then in /var/log/auth.log when using tsh ssh I got the error:
`PAM unable to dlopen(/lib/x86_64-linux-gnu/security/pam_jail_shell.so): /lib/x86_64-linux-gnu/security/pam_jail_shell.so: undefined symbol: pam_get_user`

**What you expected to happen**:

Being able to login using tsh ssh

**How to reproduce it (as minimally and precisely as possible)**:

Just install: https://github.com/pymumu/jail-shell/ (no need to create a jailed user, just install it) on your node then configure teleport to use PAM with SSHD service or "common-session" and try to tsh ssh on the node.

**Environment**:
- Teleport version (use `teleport version`): Teleport v4.2.0-alpha.2 git:v4.2.0-alpha.2-41-g7b54e7f8 go1.13.4
- Tsh version (use `tsh version`): Teleport v4.1.4 git:v4.1.4-0-gc487a75c go1.13.2 (on client)
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)

**Comment by R-gues** [comment]
Starting teleport with `LD_PRELOAD=/lib/x86_64-linux-gnu/libpam.so.0` ( `LD_PRELOAD=/lib/x86_64-linux-gnu/libpam.so.0 teleport start .......` ) resolve the issue.

Am I missing something ? Or teleport just doesn't load the libpam.so.0 module from the system ?

**Comment by webvictim** [comment]
It looks like this Teleport binary wasn’t built with PAM support. Did you compile it yourself or use a downloaded binary?

**Comment by igtsekov** [comment]
I have the same issue. I am building the binary myself. I am not able to find any information on how to enable the PAM module. Is there some doc file somewhere?

**Comment by webvictim** [comment]
You need PAM headers available on your build system to build with PAM support. See https://github.com/gravitational/teleport/blob/master/Makefile#L66

This is usually provided by a `pam-devel` or similar package.

**Comment by stevenGravy** [comment]
Closing, if still having an issue open a discussion or slack discussion.
