### ISSUE TITLE
Support Windows desktop clipboard sharing in other non-Chromium web browsers

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#31747]
What would you like Teleport to do?

Support Windows desktop clipboard sharing in other non-Chromium web browsers, such as Firefox.

What problem does this solve?

Some organisations restrict users so that they can only use certain web browsers, such as Firefox and Teleport Desktop Access clipboard sharing requires a Chromium-based browser such as Google Chrome, Brave, or Microsoft Edge. If using another browser, clipboard sharing will be disabled irrespective of whether a user's role allows it.

![Screenshot 2023-09-12 at 10 32 55](https://github.com/gravitational/teleport/assets/95687564/208c191c-e67b-4706-a660-edb6d6c982be)

If a workaround exists, please include it.

N/A

**Comment by zmb3** [comment]
This is well discussed in the RFD: https://github.com/gravitational/teleport/blob/master/rfd/0049-desktop-clipboard.md#user-experience
