### ISSUE TITLE
Allow specifying listener IP for tsh proxy app

### ISSUE THREAD

**Issue by kenske** [gravitational/teleport#31764]
## What would you like Teleport to do?
When running `tsh proxy app`, teleport creates a proxy that's [hardcoded](https://github.com/gravitational/teleport/blob/master/tool/tsh/common/proxy.go#L563) to listen from `127.0.0.1`. This creates an issue when trying to connect to the proxy from a docker network on the same host.

It would be great to be able to specify the IP that's used for the listener.

## What problem does this solve?
Connecting to a teleport proxy from docker containers

## If a workaround exists, please include it.
- Run teleport proxy in the same docker container
- Use `socat` to setup a relay

**Comment by zmb3** [comment]
Closing in favor of #40509
