### ISSUE TITLE
Investigate weirdness with CentOS 6 builds inside Docker container having a 'dirty' git tag

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3184]
**What happened**: For some reason, CentOS 6 builds (which are built inside a container) seem to get a dirty git tag from `git describe --tags --long --dirty` when the build is run, using either `make -C build.assets release-centos6 OS=linux ARCH=amd64` or `make -C build.assets release-centos6-fips OS=linux ARCH=amd64`

Expected tag: `v4.2.0-alpha.5-0-ged4930a66`
Actual tag: `v4.2.0-alpha.5-0-ged4930a-dirty`

Take this sequence of actions:

```bsh
$ git clone https://github.com/gravitational/teleport.git
Cloning into 'teleport'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 57861 (delta 3), reused 4 (delta 1), pack-reused 57849
Receiving objects: 100% (57861/57861), 79.46 MiB | 4.71 MiB/s, done.
Resolving deltas: 100% (36969/36969), done.
$ cd teleport
$ git checkout tags/v4.2.0-alpha.5
Note: checking out 'tags/v4.2.0-alpha.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ed4930a6 Release 4.2.0-alpha.5
$ git status
HEAD detached at v4.2.0-alpha.5
nothing to commit, working tree clean
$ make clean
---> Cleaning up OSS build artifacts.
rm -rf build
go clean -cache
rm -rf `go env GOPATH`/pkg/`go env GOHOSTOS`_`go env GOARCH`/github.com/gravitational/teleport*
rm -rf teleport
rm -rf *.gz
rm -rf *.zip
rm -f gitref.go
$ VERSION=4.2.0-alpha.5 /usr/bin/make -f version.mk setver
$ cat version.go
/* DO NOT EDIT THIS FILE. IT IS GENERATED BY 'make setver'*/

package teleport

const (
        Version = "4.2.0-alpha.5"
)

// Gitref variable is automatically set to the output of git-describe
// during the build process
var Gitref string
$ cat gitref.go
/* DO NOT EDIT THIS FILE. IT IS GENERATED BY make */

package teleport

func init() { Gitref = "v4.2.0-alpha.5-0-ged4930a66" }
```

Everything looks fine. However, as soon as you run `make -C build.assets release-centos6 OS=linux ARCH=amd64` and then immediately `cat gitref.go`:

```bsh
$ cat gitref.go
/* DO NOT EDIT THIS FILE. IT IS GENERATED BY make */

package teleport

func init() { Gitref = "v4.2.0-alpha.5-0-ged4930a-dirty" }
$ git status
HEAD detached at v4.2.0-alpha.5
nothing to commit, working tree clean
```

Apparently nothing has changed in the repo, but for some reason the git tag is dirty.

**What you expected to happen**: The git tag shouldn't be dirty, as nothing has changed in the repo. This only seems to affect the CentOS 6 builds, which are semi-unique in that they're done inside a CentOS 6 container so they can be built against a lower version of glibc.

I've tried running these commands both inside and outside the CentOS container and can't seem to reproduce why this happens.

**How to reproduce it (as minimally and precisely as possible)**: Follow the steps above.

**Comment by webvictim** [comment]
The same thing still happens with artefacts built by [`drone.gravitational.io`](https://drone.gravitational.io/gravitational/teleport/240/4/3):

```
Teleport Enterprise v4.3.0-alpha.2git:v4.3.0-alpha.2-0-gd9e436b-dirty go1.13.2
```

**Comment by zmb3** [comment]
Closing this, as we no longer distribute CentOS 6 artifacts.
