### ISSUE TITLE
Teleport doesn't correctly handle protobuf conversion of `bot_token.create`

### ISSUE THREAD

**Issue by xacrimon** [gravitational/teleport#31901]
##Expected behavior:

Teleport emits no errors when executing `go test ./lib/ai/`

## Current behavior:

The following lines are observed
```
time="2023-09-14T19:58:16+02:00" level=error msg="Attempted to convert dynamic event of unknown type \"bot_token.create\" into protobuf event."
time="2023-09-14T19:58:16+02:00" level=error msg="Attempted to convert dynamic event of unknown type \"bot_token.create\" into protobuf event."```

## Bug details:
- Teleport version: v14
- Recreation steps: run `go test ./lib/ai/` and observe stdout

**Comment by zmb3** [comment]
What an interesting find.

FYI @bl-nero and @strideynet - I know we recently deprecated `trusted_cluster_token.create` in favor of `join_token.create` - maybe we should do the same for this one?

Another interesting thing is this event doesn't seem to actually be used at all. I can't find any matches for this other than its definition. It looks like maybe we stubbed out the event code in the original Machine ID PR but never actually implemented the event? (@timothyb89)

```
	// BotTokenCreateEvent is emitted when a new bot join user token is created
	BotTokenCreateEvent = "bot_token.create"
```

Also @bl-nero it looks like the docs for your recent work say `join_token.created` but the code says `join_token.create`.

**Comment by zmb3** [comment]
Looks like the actual warning stems from the `eventschema` package. The warning goes away with this change:

```diff
diff --git a/gen/go/eventschema/eventtype.go b/gen/go/eventschema/eventtype.go
index 9f331ed3c9..cb16d8ca8f 100644
--- a/gen/go/eventschema/eventtype.go
+++ b/gen/go/eventschema/eventtype.go
@@ -21,7 +21,7 @@ var eventTypes = []string{
 	"access_request.review",
 	"auth",
 	"bot.join",
-	"bot_token.create",
 	"cert.create",
 	"db.session.query",
 	"db.session.query.failed",
```

My recommendation is that we just remove `bot_token.create` and make sure that a `join_token.create` gets emitted (if it isn't already) when a bot token is created.

**Comment by strideynet** [comment]
I agree w/ your suggestion - we should just remove `bot_token.create`. I'm not familiar with this having ever done anything and this is adequately covered by `join_token.create` (I see no reason for a distinct event).
