### ISSUE TITLE
Teleport connects to incorrect node from WebUI

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3190]
If you create two nodes with the exact same hostname within a cluster, Teleport will always connect to the first one via the Web UI. Teleport will connect to the correct host when connecting through `tsh`.

Customer reported this in 4.0.11 and I was able to reproduce in 4.2.0-rc.2.

**Comment by benarent** [comment]
@alex-kovoy Aill you be able to investigate this and make sure that it's fixed in 4.3?

**Comment by alex-kovoy** [comment]
Yes, I will

**Comment by zmb3** [comment]
> Teleport will connect to the correct host when connecting through tsh.

How do you even know what the "correct" host is if they both have the same name?

(I suspect this is similar to #10696 and is related to the web UI's deduplication logic)

**Comment by zmb3** [comment]
@rosstimothy @hatched do the recent web UI dialing changes have any effect on this issue?

**Comment by hatched** [comment]
I expect that if there are two nodes with the exact same hostname in the servers list and the user clicks the "connect" button it'll work as expected as that link uses the servers UUID.

However if they type it in the input box and connect that way I'd expect that it'll pick the first one as it has no way to determine which `root@<duplicateHost>` is the one they meant to connect to.

**Comment by zmb3** [comment]
Yeah, I agree. I think there's no further action necessary here and we can close this.
