### ISSUE TITLE
Gitlab and Github SSO Guides

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3194]
We now have a docs section for SSO guides. We already provide Github in the OSS version but we should pull these docs out for the Enterprise product ( after fixing  https://github.com/gravitational/teleport/issues/3160  ) 

We should use the same docs template for both Github and Gitlab.

**Comment by zedtux** [comment]
Does it mean that Gitlab SSO is already implemented and *just* not documentated?

**Comment by benarent** [comment]
@zedtux For github you can follow https://gravitational.com/teleport/docs/admin-guide/#github-oauth-20 this works for both our OSS and Enterprise version. 

Gitlab in only available on our Enterprise version, but it'll likely follow the same flow as many other SSO providers.  https://gravitational.com/teleport/docs/enterprise/ssh_sso/

**Comment by zedtux** [comment]
Thank you for your comment @benarent

**Comment by ptgott** [comment]
@benarent since we have these two guides now, is there any work left to be done on this issue?
- https://goteleport.com/docs/setup/admin/github-sso/
- https://goteleport.com/docs/enterprise/sso/gitlab/

**Comment by benarent** [comment]
Yes, I'll close this issue.
