### ISSUE TITLE
Interactive sessions do not exit with correct exit code.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3202]
When running exec commands, `tsh` will exit with the correct exit code.

```
$ tsh ssh server01 exit 2
error: Process exited with status 2
$ echo $?
2
```

However, with an interactive session (shell), Teleport always returns `0`.

```
$ tsh ssh server01
$ exit 2
logout
the connection was closed on the remote side on  10 Dec 19 01:07 UTC
$ echo $?
0
```

Compared to OpenSSH which does return the appropriate exit code.

```
$ ssh server01
Warning: Permanently added '[localhost]:3023' (RSA) to the list of known hosts.
Warning: Permanently added '[localhost]:3022' (RSA) to the list of known hosts.
$ exit 2
logout
Connection to localhost closed.
$ echo $?
2
```

It should be noted this is purely a client side issue with `tsh`. The server, `teleport`, correctly sends the exit code, it is just ignored and not printed by `tsh`.

This is because for exec commands, `session.Run()` is used which will block until completion and return the exit code and interactive sessions use `session.Start()` or `session.Shell()` which do not block and `session.Wait()` is never used.

https://github.com/gravitational/teleport/blob/branch/4.1/lib/client/session.go#L472
https://github.com/gravitational/teleport/blob/branch/4.1/lib/client/session.go#L440
https://github.com/gravitational/teleport/blob/branch/4.1/lib/client/session.go#L409

**Comment by sfc-gh-satherton** [comment]
This problem also happens for non-interactive sessions that run specific commands so long as they allocate a TTY (which is done by default if no command is provided):

```
$ tsh ssh <host_info> exit 3; echo $?
error: Process exited with status 3
3
$ tsh ssh -t <host_info> exit 3; echo $?
0
```
