### ISSUE TITLE
Alert when node disconnected to datadog

### ISSUE THREAD

**Issue by yosa212** [gravitational/teleport#32032]
What would you like Teleport to do?
can you add a feature where teleport and datadog can be communicate.
and whenever nodes in teleport clusters got disconnected it'll give alert to datadog which nodes that got connected

What problem does this solve?
notice of nodes got disconnected from teleport

If a workaround exists, please include it.
i tried to sent from datadog-agent to make log collection where the machine is connected to teleport clusters but it's not enough to make some alert

**Comment by zmb3** [comment]
Teleport exposes Prometheus-style metrics, which Datadog can support. A list of available metrics is here: https://goteleport.com/docs/reference/metrics/

Teleport is making the info that you need available. Configuring alerts is something that should be solved outside of Teleport.
