### ISSUE TITLE
Bump aws-sdk-go version dependency

### ISSUE THREAD

**Issue by robcoward** [gravitational/teleport#3210]
Please bump the aws-sdk-go version dependency to at least v1.21.0 https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v1210-2019-07-18

AWS added support in EKS for kubernetes service accounts to be associated to IAM roles to allow granular, pod-level permissions to be inherited by containers. This release of the SDK is required in order to support the `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` environment variables.

**Comment by webvictim** [comment]
+1 for this from a customer.
