### ISSUE TITLE
Find a way to reduce a number of ports

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3211]
## Description

Find a way to reduce the amount of ports. Can we remove 3023 and forward TLS via proxy? This will knock out one port from this list:

https://gravitational.com/teleport/docs/admin-guide/#ports

Same for SSH reverse tunnel, can we replace reverse tunnel with GRPC, this will allow us to have only one port for proxy.

**Comment by webvictim** [comment]
We’ve also had a request in the past to multiplex Kubernetes traffic over the same port as the proxy - https://community.gravitational.com/t/kubernetes-api-proxy-through-tunnel/415
