### ISSUE TITLE
How do I enroll Cisco devices (routers/switches) into Teleport? Kindly assist

### ISSUE THREAD

**Issue by dseronu** [gravitational/teleport#32115]
What would you like Teleport to do?
Enrolling Network Devices e.g. Routers and switches?

What problem does this solve?
Centrally managing access of the devices.

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Hi there @dseronu - this type of question is better suited towards [GitHub discussions](https://github.com/gravitational/teleport/discussions) or our community Slack workspace. The issue tracker is more for bugs and other development work.
