### ISSUE TITLE
Wishlist: Add 'favorites' to Applications list (or 'recently used')

### ISSUE THREAD

**Issue by msplival** [gravitational/teleport#32183]
We have over 200 applications in Teleport, and on bi-monthly basis I would use most of them.
But on day-to-day basis I use maybe 5 or 6 of them. While 'search' text box greatly helps in locating those apps I think users would benefit from a 'recently used' list, or maybe being able to tag some applications as 'favorites' so that those would be easily accessible.

**Comment by zmb3** [comment]
This is coming in 14.1 and is tracked at #30418
