### ISSUE TITLE
Check prerequisites for the guided flow for Connect My Computer in Discover

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#32186]
- [x] Check if we can tie a login directly to the CMC node
   * This is needed for the connection test in the Web UI. We need to know which login the node uses. There's only ever a single valid login because the agent runs as a system user and not root. The CMC role can include multiple logins if the user uses CMC on two separate devices with two distinct system usernames.
   * Does this impact the RBAC for the CMC node? So far the login was included only in the CMC role, meaning that by default only the user with the role was able to log in to the CMC node. This is not foolproof of course, we just have to be wary of how tying a login directly to the node impacts this scenario.
- [x] Check how to detect from within the Web UI that the CMC node has joined the cluster
   * This is required in order to finalize the guided flow in the Web UI and offer an optional connection test.
   * One potential solution would be to first check how many CMC nodes for the current user are currently in the server and then wait for this number to change.
      * This handles a situation where the user added a node on one device and goes to perform the setup on another device.
   * What if the user opens the tile but the node they want to add is already visible in the cluster?
   * ~If there's a problem and the user is not able to see the node for some reason, we will not notice that the node has joined the cluster. We need to know the node UUID but how?~
      * This could happen if the user has roles explicitly denying access to nodes.
      * Maybe at this step we could offer troubleshooting tips which normally are reserved for the connection test?
         * Yes, this is where Discover usually displays "We're still looking for your server".
- [x] Check if on macOS we can make the app handle the custom protocol without the user having to launch the app first
   * Initial tests done by Grzegorz in a macOS VM have shown that this should be possible. The OS recognizes that the Slack app handles `slack://` URLs without launching the app. Just dragging it from the .dmg to /Applications was enough.
   * How does it work on Ubuntu and Fedora?

**Comment by ravicious** [comment]
We cannot tie a login directly to the CMC node. When adding a regular SSH node through Discover, Discover adds the selected logins to the traits of the user.

However, in the case of Connect My Computer the CMC role associated with the user is going to enumerate all possible usernames. So we basically have to support two use cases:

1. Alice has added a single device through CMC and the only login in the role is "alice".
   * In that case, the connection test is simply going to use "alice" without asking for login.
2. Alice just added a second device through CMC and the role now includes two logins: "alice" and "allie".
   * In that case, the connection test should show a select and let the user pick the correct one.

**Comment by ravicious** [comment]
### Detecting that the node joined the server

Initially, I thought of supporting a wide variety of what-if scenarios through the guided flow in the Web UI. However, doing that would simply explode the complexity of the implementation and the UI.

Instead, we want to support an existing Discover invariant: when the user goes through the guided flow and adds a node, the Web UI must unambiguously know which node is the one just added by the user.

#### How Discover does this

Discover implements this by generating a UUID which is tied to the join token provided to the installation script. During installation, the script adds that UUID as the value for a hidden label. The Web UI polls for nodes with that label and the value to unambiguously identify the node. The UUID has no use outside of the setup.

#### How Connect My Computer could implement this

The UUID could be passed to Connect through the deep link. The guided flow in the Web UI would require the user to use the deep link before proceeding further. When setting up the agent, Connect could provide that UUID as a hidden label. Polling would then behave similar to how it already does in Discover. Polling would start immediately after the user clicks the deep link.

If the user starts the guided flow while Connect is already running a Connect My Computer agent for the given cluster, clicking the deep link could stop the agent, update the config file with the hidden label, and then start the agent again.

**Comment by ravicious** [comment]
@roraback 

> Could we instead have a non-unique hidden label for the user + Connect My Computer, and watch for that to join the cluster?

We already have a label like this that we could use for polling. However, this gets complicated with having Connect My Computer set up on multiple devices. By looking at just the label, we're not able to differentiate between these two scenarios:

1) The user went ahead and set up Connect My Computer without the deep link.
   * In the cluster we see that there's already a device labeled `teleport.dev/connect-my-computer/owner: alice`.
2) The user wants to connect another device while the already set-up device is running an agent.
   * In the cluster we see that there's already a device labeled `teleport.dev/connect-my-computer/owner: alice`, but we'd actually like to wait for the second device to join.

We must either be able to unambiguously determine which device was added through the guided flow _or_ be able to deal with ambiguities.

**Comment by ravicious** [comment]
### Detecting that the node joined the server v2

What we established with Kenny is that when the user begins the guided flow in the Web UI, we could store the current time in the Web UI's state. During the setup, Connect would add a hidden label with the time of when the config file was generated.

When polling for the node, the Web UI would compare the timestamp from its state with the timestamp in the hidden label. If the node was configured after the tab was opened, the Web UI would then decide that this is the node that the user has intended to add.

This solves the issue described in the comment above (https://github.com/gravitational/teleport/issues/32186#issuecomment-1733717517).

If they click the deep link and CMC is already set up, open the CMC tab and send a notification saying that the computer is already set up.

If the Web UI doesn't see the node after X amount of seconds, it should attempt to extend the session in case the new role that was added to the user grants them access to see the new node.

**Comment by gzdunek** [comment]
I like this approach, it's simple and keeps the ambiguity level low :)
