### ISSUE TITLE
Reusing old users data from old teleport in new teleport

### ISSUE THREAD

**Issue by dimasmamot** [gravitational/teleport#3218]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
I migrate user data from old version of teleport (2.5.1) to the latest (4.1.7), the users is carried away, yet the old password is unusable. Is this an expected behavior ? Where and how exactly teleport store the password ? Is it possible to use the old password ?

**What you expected to happen**:
Users and password from old teleport can be reused in new teleport

**How to reproduce it (as minimally and precisely as possible)**:
Copy users directory from old auth server to the latest one with adapted configuration

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.4.5.1 git:v2.4.5-19-g4901c48 (old) >>>> Teleport v4.1.7 git:v4.1.7-0-g4c6e3ace go1.13.2 (new)
- Tsh version (use `tsh version`): Teleport Teleport v2.4.5.1 git:v2.4.5-19-g4901c48 (old) >>>> Teleport v4.1.7 git:v4.1.7-0-g4c6e3ace go1.13.2 (new)
- OS (e.g. from /etc/os-release): 18.04.3 LTS (Bionic Beaver)

**Browser environment**

- Browser Version (for UI-related issues): -
- Install tools: -
- Others: -

**Relevant Debug Logs If Applicable**

- tsh --debug -
- teleport --debug -

Thanks !

**Comment by webvictim** [comment]
Hi - upgrading directly from Teleport 2.4.x to 4.1.7 goes through a lot of major version changes and is not a supported use case, I'm afraid. 2.4.x is a very old version and there's no guarantee anything from it will be compatible with a more modern Teleport version.

The thing you could have done to try and make this work would be to go through each minor release in order (so 2.4.x -> 2.5.x -> 2.6.x -> 2.7.x -> 3.0.x -> 3.1.x -> 3.2.x -> 4.0.x -> 4.1.x) but even that might not work.

In your situation, the best advice I can offer for a cluster that hasn't been updated in so long is to build a new cluster alongside the current one and run them in parallel while you manually add users and nodes to the new cluster, then shut down and decommission the old one once everyone has moved over.
