### ISSUE TITLE
Automatically printing the message of the day

### ISSUE THREAD

**Issue by dkrutsko** [gravitational/teleport#3219]
As recommended by the [community post](https://community.gravitational.com/t/teleport-and-printing-the-message-of-the-day/490), I would like to see if it would be possible to implement the ability to automatically print the message of the day upon teleporting into a server. Similar to how the `PrintMotd` option does in OpenSSH.

We have a lot of useful information there which would be nice to display whenever somebody logs into a server.

**Comment by zmb3** [comment]
The MOTD is already printed when logging in via CLI, and we have #13724 to track adding it to the web UI, so I'll close this issue.
