### ISSUE TITLE
Play old sessions without teleport running?

### ISSUE THREAD

**Issue by Veraticus** [gravitational/teleport#3225]
Hello!

We take filesystem-level backups of our teleport servers, including the teleport data directory (`/var/lib/teleport`). It would be nice to be able to replay the sessions in `log/<uuid>/sessions/default` without standing up the entire server that it originated from. Is there an easy way to do that?

**Comment by webvictim** [comment]
There isn't currently an easy way to do this. We have an outstanding issue which would solve the problem - #1580

**Comment by webvictim** [comment]
With regard to the actual session content, you can run `zcat` or `zgrep` etc on the files to look for specific keywords or strings, but the "video playback" type view that you can currently get via the web UI or `tsh play` isn't available.

**Comment by benarent** [comment]
Thanks for replying Gus, I'm going to mark this as a duplicate and move any discussion to the other issue.

**Comment by Veraticus** [comment]
Thank you, this issue is helpful!
