### ISSUE TITLE
Issues on license requirement on Teleport on OSS feature for with GHE

### ISSUE THREAD

**Issue by loveshoo** [gravitational/teleport#32288]
Expected behavior:
- Auth Connector with GHE(https://goteleport.com/docs/access-controls/sso/github-sso/)
In **Teleport Enterprise and Enterprise Cloud**, organization can be hosted from either GitHub Cloud or GitHub Enterprise Server.
- Machine ID with GHE(https://goteleport.com/docs/machine-id/guides/github-actions/)
From Teleport 11.1.4, users with **Teleport Enterprise** are able to permit workflows within GitHub Enterprise Server instances to authenticate using the GitHub join method.

Current behavior:
Not supported

Does Teleport OSS support license requirement with GHE ? 
Or with GHE only support at Teleport Enterprise ?

**Comment by zmb3** [comment]
GHE requires Teleport Enterprise
