### ISSUE TITLE
Failure to join cluster should result in a clear message

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#323]
Should say:

```go
Error joining cluster <auth-server-param>. This node certificate was signed by another cluster.
```

**Comment by klizhentas** [comment]
Here's the problem Ev faced while hacking on it:

https://github.com/gravitational/teleport/pull/322/files#diff-b2616f8fc5d7121127fe898e501d328dR155

**Comment by kontsevoy** [comment]
The root of the problem is the behaviour of this function:
```
err := process.connectToAuthService(role)
```
it _never_ returns "access denied" error. Instead, the process gets killed.

**Comment by kontsevoy** [comment]
This works fine now.
