### ISSUE TITLE
`--db-name` is no longer optional in `tsh db login` 

### ISSUE THREAD

**Issue by adamstrawson** [gravitational/teleport#32307]
Expected behavior:

Running `tsh db login --db-user=user my-database`

should login to the teleport database. 

This was the behaviour prior to upgrading to `14.0.0`. 

Current behavior:

```
tsh db login --db-user=user my-database
ERROR: please provide the database name using the --db-name flag, allowed database names for my-database: [*]
```

The documentation from `tsh db login --help` shows `--db-name` as optional still. 

```
 --db-name                  Optional database name to configure as default.
```

Bug details:
- Teleport version 14.0.0

**Comment by zmb3** [comment]
The change was intentional (see the [release notes](https://github.com/gravitational/teleport/releases/tag/v14.0.0) for more info), but it looks like the documentation is out of date.

@GavinFrazar mind getting a docs fix out?

**Comment by adamstrawson** [comment]
Super quick response 👏  

Thanks for confirming, I'll update our internal docs with this change. I assume for us because `db_names` is `*` for our users, it's not able to select a default, and so expects it to be passed?

**Comment by zmb3** [comment]
> Super quick response 👏

Got lucky 😅 

> it's not able to select a default, and so expects it to be passed?

Yes, that would seem to make sense. I'll let Gavin elaborate if I've missed something.

**Comment by GavinFrazar** [comment]
which db protocol is it? `--db-name` is required for specific protocols

**Comment by zmb3** [comment]
@GavinFrazar let's just remove `Optional` from the help message and then describe more specifically when it is required in the CLI reference guide.
