### ISSUE TITLE
Montly active users counter

### ISSUE THREAD

**Issue by fernandocastrovilar** [gravitational/teleport#32311]
What would you like Teleport to do?
Will be a great feature to have a counter under the user management section where admins are able to see the monthly active users.

What problem does this solve?
Whit enterprise plans, the facturations is directly related to the number of monthly active users. When you have no local users and users comes from an Azure Active directory (e.g.) you are only able to see daily active users so as administrator you dont have an idea of how many users had connected to the platform.

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Thanks for the request.

This will be coming to enterprise plans over the next several quarters. We're tracking this internally, and given that it's specific to enterprise I don't think we need a duplicate issue in the OSS repo. More to come soon!
