### ISSUE TITLE
Release 4.2 AMI

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3237]
I was looking to update our 4.2 examples and I noticed we still need to publish 4.2 AMI.
 
![image](https://user-images.githubusercontent.com/559288/71635464-abe48800-2bd9-11ea-9832-7726baf25dd5.png)

**Comment by wadells** [comment]
When someone takes care of this (@webvictim)? Please grab me, such that I can either watch over your shoulder or drive while you watch over my shoulder.  I want to make sure we've got this process accurately captured in our release process documentation.

**Comment by webvictim** [comment]
I updated the docs on the wiki relating to AMI deployments.
