### ISSUE TITLE
Helm upgrade on Azure AKS fails with db auth error

### ISSUE THREAD

**Issue by anthonysomerset** [gravitational/teleport#32440]
Expected behavior:
Helm Upgrade from 13.3.x to 14.x should succeed

Current behavior:
The Helm upgrade appears to succeed but the pods fail to start with following logs

```
2023-09-23T06:42:38Z INFO             Starting Teleport v14.0.0 with a config file located at "/etc/teleport/teleport.yaml" common/teleport.go:587
2023-09-23T06:42:38Z INFO [PROC:1]    Service diag is creating new listener on 0.0.0.0:3000. pid:7.1 service/signals.go:215
2023-09-23T06:42:38Z INFO [DIAG:1]    Starting diagnostic service on 0.0.0.0:3000. pid:7.1 service/service.go:3123
2023-09-23T06:42:38Z INFO [PGBK]      Setting up backend. pgbk/pgbk.go:181
ERROR: initialization failed
ERROR: permission denied for database prd_teleport (SQLSTATE 42501)
```

Bug details:
- Teleport version - 14.0.0
- Recreation steps - working 13.3.1 cluster configured on AKS with postgres DB, run helm upgrade to 14 e.g. `helm upgrade teleport teleport/teleport-cluster`
- Debug logs

As far as i can see things should be continuing to use the existing workload identity and nothing else was changed there, we had previously upgraded from 13.3.0 to 13.3.1 just fine otherwise

**Comment by anthonysomerset** [comment]
ok possible false positive... failing to re-replicate it possible DB permissions issue not not clear

**Comment by espadolini** [comment]
Is it possible that the user did not have create perms on the database? Can you try to replicate it with debug logs enabled?

The only thing that I could see fail is a `CREATE PUBLICATION` that I added in the v14 schema change for future development but it's actually technically a breaking change, as that requires create permissions on the whole database rather than just the schema - I'll be removing that shortly.

**Comment by anthonysomerset** [comment]
yes looks like this was indeed the issue, thanks for clarifying - i've manually granted the user permissions on the DB for now and it resolves

**Comment by espadolini** [comment]
@anthonysomerset by the way, once Teleport is initialized once you can get rid of the create permissions on the database for the Teleport user, if that's a concern - and you can even `DROP PUBLICATION kv_pub` (it's not being used, and we'll never be able to assume that it exists or doesn't exist).
