### ISSUE TITLE
web ui - default two factor type

### ISSUE THREAD

**Issue by rifler** [gravitational/teleport#32494]
What would you like Teleport to do?
On login page there is a select ("Hardware type" / "Authenticator App"). By default "Hardware type" is selected. It would be nice to be able set default option via helm

What problem does this solve?

If a workaround exists, please include it.

**Comment by zmb3** [comment]
You should be able to set `authentication.type` with the [`auth.teleportConfig`](https://goteleport.com/docs/reference/helm-reference/teleport-cluster/#authteleportconfig) value.

**Comment by webvictim** [comment]
You can also set `authentication.secondFactor` to change this value directly - see https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L144

"Hardware Key" will always be selected by default when webauthn is enabled (which is the default with `authentication.secondFactor: on`.

If you only want to offer TOTP and select that by default, set `authentication.secondFactor: otp`
