### ISSUE TITLE
Add hostname to event output in logs

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3251]
**What happened**:
Teleport event logs don't currently contain the hostname of the server where they originate.

```
{
  "addr.local": "1.2.3.4:3022",
  "addr.remote": "5.6.7.8:63274",
  "code": "T2006I",
  "ei": 2147483646,
  "event": "session.data",
  "login": "root",
  "rx": 3542,
  "server_id": "b6f108ad-b2fc-4ad1-a19f-3bcc69eac31d",
  "time": "2020-01-09T19:18:04Z",
  "tx": 4969,
  "uid": "842b9510-0a6c-4d7d-a52a-5c54f653bc61",
  "user": "jsmith"
}
```

**What you expected to happen**: The logs should contain the hostname as an extra field. This would help enormously when submitting the logs to a centralised logging service

**Comment by zmb3** [comment]
The `session.data` event has server metadata now, which includes the hostname. I'm going to close this, but feel free to open another issue if there's a specific event where you notice something missing.
