### ISSUE TITLE
Session timeouts during working business hours

### ISSUE THREAD

**Issue by bahmanjafari** [gravitational/teleport#32535]
What would you like Teleport to do?
Configure session timeouts during working business hours. For instance, during these hours, the timeout is set to 5 hours, but after 6:00 PM, users will disconnect if idle for 15 minutes.

What problem does this solve?
Improve security and usability 

If a workaround exists, please include it.

**Comment by zmb3** [comment]
This request is tracked with a bit more detail at #31405
