### ISSUE TITLE
Packaging and release Teleport Plugins

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3254]
As we start to get ready for releasing the Teleport Plugins we should provide the same convenience & packaging as for current Teleport binaries. 

- [ ] Inclusion of Automated Testing
- [ ] Follow same release best practices for Teleport. 
- [ ] Package available at https://get.gravitational.com/

**Comment by xnutsive** [comment]
`make access-slackbot` already works in `gravitational/teleport-plugins`. It's early, but we can start putting together a system to release the plugins and automatically(?) upload them on the website.

**Comment by benarent** [comment]
For the first release, I propose we only provide gz binaries. ( add packages later ) 

https://get.gravitational.com/teleport-plugins/slackbot/slackbot-v0.0.1-linux-386-bin.tar.gz
https://get.gravitational.com/teleport-plugins/slackbot/slackbot-v0.0.1-linux-arm-bin.tar.gz
https://get.gravitational.com/teleport-plugins/slackbot/slackbot-v0.0.1-linux-amd64-bin.tar.gz

**Comment by xnutsive** [comment]
For now, all existing and new plugins will support `make release` in their plugin subdirectory and pack the `.tar.gz` with the binary, the installer, changelog, readme, etc. 

Keeping an eye on this, ping us if you'll need any help packing the plugin releases.

**Comment by russjones** [comment]
Tracked in https://github.com/gravitational/teleport-plugins/issues/110.
