### ISSUE TITLE
One binary or multiple per plugin? 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3255]
I'm currently working on some docs / developer experience prior to development. 

While following the same guidelines as Teleport, I've created a quickstart and guide for running Teleport Plugins. https://gist.github.com/benarent/da80e3167ed1e997818ed37d355ad422#test-run

The current Teleport Plugin is the first version of https://github.com/gravitational/teleport/issues/2461 . which is still in the `spec` stage.  

We've a few options currently available to us.

### 1. Create one `teleport-plugin` binary.
This binary would provide all the functionality needed for a plugin, this might include all the setup required to provide TLS, config options per plugin and would provide an easy way to expand plugins without having to mange multiple apps. 

**Teleport Slackbot Example**
All options would be set in config, similar to Teleports option of running the Proxy and Auth on the same node.  
```
teleport-plugin start --config=/etc/teleport-plugin.toml
```
### 2. Create a binary per use case. e.g. `teleport-access` binary.
A binary that only offers the access plugins. This could offer extra functionality such as providing TLS and public access. 

**Teleport Slackbot Example**
```
teleport-access start --plugin=slack --config=/etc/teleport-plugin.toml
```
### 3. Create a binary per plugin. e.g. `teleport-slackbot` binary.
This is how we currently have `teleport-plugins` setup.

**Teleport Slackbot Example**
```
teleport-slackbot start --config=/etc/teleport-plugin.toml
```

#### Summary 
My gut says we should go for 1, as this would greatly simplify packages and the build process for us, but 3. could make it much easier for external devs to create plugins ( this is similar to how Terraform plugins are made )

**Comment by xnutsive** [comment]
> @fspmarshall @marshall-lee before the release we have to make sure that the plugins verify the version of the server for compatibility like tsh does and refuse to start if the versions are incompatible.

I'll make a separate issue to track that.

**Comment by benarent** [comment]
Closing this issue as we'll have one binary per plugin type. e.g. teleport-slackbot, teleport-jirabot etc.
