### ISSUE TITLE
Teleport Connect Kube proxy internal server error with access requests

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#32567]
Expected behavior:

I requested a role that lets me login into k8s cluster biscuit in the demo env. I assumed the role via teleport connect and connected to cluster, trying to run `kubectl get pods` did not work until I also ran `tsh kube login biscuit`. It seems like local proxy did not get the memo about updated certs.

Current behavior:

```
sasha ~ % kubectl get pods
Error from server (InternalError): an error on the server ("Internal Server Error") has prevented the request from succeeding
sasha ~ % kubectl get namespaces
Error from server (InternalError): an error on the server ("Internal Server Error") has prevented the request from succeeding

tsh kube login biscuit
Logged into Kubernetes cluster "biscuit". Try 'kubectl version' to test the connection.
sasha@Alexanders-MacBook-Pro ~ % kubectl get pods
No resources found in default namespace.
```

Bug details:
- Teleport version v.14.
- Recreation steps:

https://www.loom.com/share/524447ccad9b4d49bf0ce1549537a56f?sid=50a31db2-5d58-44bd-85a2-876d0aa39aef

- Debug logs

**Comment by im-alfa** [comment]
It seems to have a very similar problem to #32380
