### ISSUE TITLE
Typos: Teleport Users 4.1 & 4.2

### ISSUE THREAD

**Issue by aa7955** [gravitational/teleport#3259]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
There is a typo in the Teleport users documentation:

> Every Teleport User must be associated with a list of one or more machine-level OS usernames.it can authenticate as during a login. 

https://github.com/gravitational/teleport/blob/af88dcdd84d34d9ebb12514684babecce81326b9/docs/4.1/architecture/teleport_users.md

https://github.com/gravitational/teleport/blob/46eefa1e0fcf4ab39860151741b07ab0933936f6/docs/4.2/architecture/teleport_users.md

**What you expected to happen**:
Should remove the period in `usernames.it`

**Comment by benarent** [comment]
Thanks for reporting @aa7955 , I've just opened a PR to fix this. I'm going to close for now.
