### ISSUE TITLE
Website button on Ubuntu Software App, not working as intended

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#3261]
**What happened**:
I installed community teleport using `Ubuntu Software` app, and on the display screen, clicking on the `Website` button downloads "teleport-v4.2.1-linux-386-bin.tar.gz" instead of taking me to website.

**What you expected to happen**:
Lead me to gravitational's website

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to https://gravitational.com/teleport/download/
1. Download "Linux 64-bit DEB"
1. Click on downloaded file
1. Default opens file on Ubuntu Software App, and click "Website" button

**Environment**:
- OS (e.g. from /etc/os-release): Ubuntu 18.04.3 LTS

![Screenshot from 2020-01-10 09-45-07](https://user-images.githubusercontent.com/43280172/72182187-d1268280-339f-11ea-89d9-e43d24312b3a.png)

**Comment by kimlisa** [comment]
Also, I don't know how customizable it is, but it would be nice if there was a link to "get started"

**Comment by webvictim** [comment]
I’ll take a look. FYI you installed the 32-bit version rather than the 64-bit version - not sure if that was deliberate.

**Comment by kimlisa** [comment]
> I’ll take a look. FYI you installed the 32-bit version rather than the 64-bit version - not sure if that was deliberate.

@webvictim I accidentally installed the 32-bit version, and couldn't figure out why my teleport wasn't working until I installed the 64 bit version. Though I thought technically 32 bit versions should work on 64 bit systems?

**Comment by webvictim** [comment]
Yes, absolutely. The 32-bit binary works fine on my 64-bit system here (although I didn't install from a package manager) so I'm unsure why it wasn't working for you.

**Comment by webvictim** [comment]
The changes in the PR will take effect when new packages are built for the next release of Teleport.
