### ISSUE TITLE
Provide non-Go API client examples for gRPC API

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#32658]
What would you like Teleport to do?

Provide examples in addition to using Go other languages for the gRPC API.  The most common asks are Python and Java.  Other programing languages client include Koitlin. 

What problem does this solve?

Python and other programming languages are common for IaC maintenance. If Go is not a used programming language that can make it harder to adopt IaC with Teleport.

If a workaround exists, please include it.

Clients have to invoke `tctl`.

**Comment by zmb3** [comment]
We don't have capacity to support this at this time. Marking not planned for now.
