### ISSUE TITLE
Web UI Login Feedback

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#3267]
**What happened**:
On the login page, for two-factor authentication, the current selection of words make it look like I **have** to use google authenticator. But in quick start guide, it says I can use google authenticaor, authy, or another 2FA client. 

I suggest we remove confusion by generalizing the 2FA client options, like the quick start guide: https://gravitational.com/teleport/docs/quickstart/#step-4-register-a-user

![teleport-web-ui-login](https://user-images.githubusercontent.com/43280172/72278908-d414b380-35e9-11ea-9301-a3ea23591019.png)

**Environment**:
- Teleport version (use `teleport version`): 4.2.1

**Suggestion**:

Github does this:
```Open the two-factor authentication app on your device to view your authentication code and verify your identity``` 
In addition, we can add links to: (Google Authenticator, Authy, or another 2FA client)

**Comment by benarent** [comment]
Thanks @kimlisa I've added a note to upcoming design spec. https://docs.google.com/document/d/1gMyMYFxPhYSMz9OT_BVCOTKmGPgtcYCOxmQBa9XddCA/edit.

Going to leave open for other feedback.

**Comment by stevenGravy** [comment]
Having the version of Teleport hosted throughout the web app I think would be helpful. I put some comments in the document.

**Comment by aelkugia** [comment]
@stevenGravy @benarent tagging this ticket with #2698  which mentioned printing the Auth or Proxy versions in Web UI as well

**Comment by benarent** [comment]
Closing this issues as it's been fixed in 4.3
