### ISSUE TITLE
Consider disallowing directory indexing for /web/app/

### ISSUE THREAD

**Issue by sclevine** [gravitational/teleport#32770]
Some vulnerability scanners complain that directory indexing is enabled for `/web/app/`. E.g., https://levine.teleport.sh/web/app/

Although all assets in the binary-embedded `/web/app/` directory are all intended to be public, disabling indexing would reduce reports from these scanning tools.

**Comment by zmb3** [comment]
See #28873

**Comment by sclevine** [comment]
Auditing tools will continue to complain about this until it's addressed. Is it worth addressing for that reason, or should I close?

**Comment by strideynet** [comment]
> Auditing tools will continue to complain about this until it's addressed. Is it worth addressing for that reason, or should I close?

If it were a simple enable/disable boolean on `http.FileServer`, I think I'd be in favour of disabling it - but as it currently stands you either have to:

- Wrap the filesystem implementation with something that disables the methods necessary for listing files but not the ones for serving files.
- Introduce a middleware that returns a Not Found or similar error on the root path. As it's a middleware, it would be liable to being forgotten about if things were moved around, or subdirectories were introduced.

Imho both of these seem liable to causing issues that are actually tangible compared to a false positive raised by a security tool thats fairly trivial to determine is non-issue upon inspection of the implementation or inspecting the system filesystem and finding no such directory.

**Comment by sclevine** [comment]
👍 closing this for now. If it keeps coming up, we can reevaluate.
