### ISSUE TITLE
[Enhancement] Add Release Table to Teleport Docs

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport#3278]
Teleport docs currently do not have a release table that discusses current releases, support dates, along with specified versions. 

Releases are currently listed here: https://github.com/gravitational/teleport/releases

Would be nice to have a `Releases` page in the docs, similiar to Gravity docs. Can look similar to this: https://gravitational.com/gravity/docs/changelog/#releases

**Comment by benarent** [comment]
I've written up a few notes about our current Release Cycle / options for a release table in Teleport. https://docs.google.com/document/d/1ul25m2m9jcXbOZKQj_n5NjZ2TyXFhbCWM9TaLOEefww/edit?usp=sharing  PTAL @webvictim @russjones @fspmarshall
