### ISSUE TITLE
SetAccessRequestState GRPC method should not fail on CompareAndSwap

### ISSUE THREAD

**Issue by marshall-lee** [gravitational/teleport#3282]
`SetAccessRequestState` could return `FailedPrecondition` code (`trace.CompareFailedError`) if the given request has been updated concurrently.
It forces the API user to call this method in a loop: https://github.com/gravitational/teleport-plugins/blob/d20cba44b811b669dfa9b33e1b0bf9e8be9a081d/access/access.go#L160-L170

Instead of this, I propose to do such loop internally in Teleport so `SetAccessRequestState` will have updated the state eventually.

Not sure about implementation though. What to do if for some reason loop exits without updating? Perhaps some error should be returned but i think it must differ from `trace.CompareFailedError`. I think such error could only be used if the user explicitly states what is desired to compare.

**Comment by fspmarshall** [comment]
Fixed in #3295
