### ISSUE TITLE
Teleport to access IBM Kubernetes Service using JWT auth scheme

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3289]
We've had a feature request to support IBM K8s [Kubernetes Service - Overview](https://www.ibm.com/cloud/container-service/). 

Reference Docs:
- [Getting started with IBM Cloud Kubernetes Service ](https://cloud.ibm.com/docs/containers?topic=containers-getting-started)
 - [IBM Cloud Kubernetes Service CLI](https://cloud.ibm.com/docs/containers?topic=containers-cli-plugin-kubernetes-service-cli)

When inspecting the `ClusterRoleBindings`, there are the following roles created by default (in IBMs K8 service): `ibm-admin, ibm-edit, ibm-view`

**Example `ibm-admin`**
```yaml
kubectl get clusterrolebinding ibm-admin -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 annotations:
   iam.iks.cloud.ibm.com.reserved: This role binding is automatically generated,
     any changes will be overwritten
 creationTimestamp: "2019-04-16T02:54:57Z"
 name: ibm-admin
 resourceVersion: "30530033"
 selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/ibm-admin
 uid: 04a72c3d-5ff3-11e9-a340-92af3c60e5c2
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
 kind: User
 name: IAM#alice@us.ibm.com
- apiGroup: rbac.authorization.k8s.io
 kind: User
 name: IAM#bob@us.ibm.com
```

Internally, IBMs K8 service uses the identity token (jwt) is used to map to these Users (e.g. `IAM#alice@us.ibm.com`)

So this is partially the reason why we need to have the `identity_token` passed as part of the cluster config. There is also a `refresh_token` but I don’t think this is required

**Comment by klizhentas** [comment]
This issue can be closed, we are not going to use JWT scheme, impersonation will work out of the box.
