### ISSUE TITLE
`tctl` should be smarter when deciding to use tsh profile

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#32926]
### Expected behavior:

```
jeff@host ~ % tsh login
> Profile URL:        https://teleport.example.com:443
...
jeff@host ~ % tctl status
Cluster      teleport.example.com
...
```

### Current behavior:

```
jeff@host ~ % tsh login
> Profile URL:        https://teleport.example.com:443
...
jeff@host ~ % tsh status
/var/lib/teleport/host_uuid. Ensure that you are running as a user with appropriate permissions.
lstat /var/lib/teleport/host_uuid: permission denied
```

When a non-root user has an active `tsh` profile, it shouldn't matter whether there is an /etc/teleport.yaml and associated /var/lib/teleport that is inaccessible.

Right now the [docs mention](https://goteleport.com/docs/reference/cli/tctl/#on-a-remote-host-after-running-tsh-login):

> If `tctl` cannot find a local Teleport configuration file or a user-provided identity file, it attempts to load the user's `tsh` profile to authenticate to the cluster. The `tsh` profile is created when a user runs `tsh login`.

It does mention that if `TELEPORT_CONFIG` is blank, it will proceed to using the `tsh`, but the current experience is confusing.

### Bug details:
- Teleport version - `Teleport Enterprise v13.4.1 git:v13.4.1-0-gcb7f7b6 go1.20.8`
- Recreation steps - try to run any `tctl` command on a system that has /etc/teleport.yaml present and an active `tsh` profile
- Debug logs - n/a

**Comment by zmb3** [comment]
Duplicate of #25620?

**Comment by programmerq** [comment]
Yup! that's a duplicate. I did search, but missed that one! Closing.
