### ISSUE TITLE
Migrate Teleport to new CI 

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3294]
Migrate Teleport tests (the `Teleport` job in Jenkins) and builds (`TeleportPublish` job in Jenkins) to Force.

The test job should support PRs from external contributors as well as Teleport developers.

The build job should support all the same functionality as well (build based off of tag, platforms, and repo).

**Comment by benarent** [comment]
I'm not sure if force supports this, but it would be cool if we had different tests for Docs vs Teleport main. We could filter it based on the Branch name?

**Comment by russjones** [comment]
Closing in favor of https://github.com/gravitational/teleport/issues/3936.
