### ISSUE TITLE
Teleport v14: Resources: Add a list view of resources

### ISSUE THREAD

**Issue by tukusejssirs** [gravitational/teleport#32999]
### What would you like Teleport to do?

Re-add an option to view the list of resources as a list/table.

There could be a buttom to toggle the list view and card view, however, I wish that either the last state would be saved to user preferences (permanently) or there would be user preference added to `Account Settings` to set the default view.

### What problem does this solve?

I prefer it much more than the new card view, as I prefer going through the list top-to-bottom instead of left-to-right **and then** top-to-bottom.

Also, we have many labels and `+6 more [labels]` is not much helpful. When clicking on `+6 more`, the additional labels are displayed as long as I keep my cursor on the resource card, that it disappears. I want to see **_all the labels at once and permanently_** without any clicking or hovering.

### If a workaround exists, please include it.

No workaround I know of.

**Comment by kenske** [comment]
Yes please, the card view is very hard to navigate quickly when you have a lot of resources. I'd be happy with a deployment-wide configuration setting for this if a per-user setting is too much.

**Comment by zmb3** [comment]
Fixed by #34203

**Comment by tukusejssirs** [comment]
Thanks, @zmb3! :pray:

In which stable TP version will this be released?

**Comment by zmb3** [comment]
14.2

**Comment by tukusejssirs** [comment]
@zmb3, I can’t see the PR in the [`v14.2` commits](https://github.com/gravitational/teleport/commits/v14.2.0/). Was the commit reverted? :thinking:

**Comment by zmb3** [comment]
No, it just made it in prior to 14.2.
