### ISSUE TITLE
Teleport Community instructions for repos refers to removed steps

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#33008]
## Applies To

https://goteleport.com/docs/installation/#installation-instructions

## Details

These instructions  refer to Debian/Ubuntu instructions.

<img width="903" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/0188ba9c-cd3c-4287-89d0-0e5f93dd6797">

currently we only have this for community

<img width="562" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/b966037f-4ff3-4a87-af24-48fe45c6390b">

## How will we know this is resolved?

An administrator would be able to confirm the available repos and update their environment.

**Comment by ptgott** [comment]
We should take care of this when improving the upgrade instructions in #33817. These instructions have to do with upgrading rather than the initial installation step.

**Comment by zmb3** [comment]
Was this fixed in #36282?

**Comment by ptgott** [comment]
Closing as complete
