### ISSUE TITLE
Web UI wizard for adding trusted clusters should not reference `tunnel_addr` on port 3024

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#33013]
## Expected behavior

When adding a new trusted cluster via the dialog in the web UI:

![image](https://github.com/gravitational/teleport/assets/897821/4e284604-2057-4324-808e-81a0071fe96c)

All our default configurations now recommend the use of multiplexing over port 443 instead, so the example YAML should be updated to default to using port 443 for tunnels.

It should, at the very least, have an explanation of how if you're using multiplexing, you should set `tunnel_addr` to the same host/port as `web_proxy_addr`, or just leave it blank (as its default behaviour is the same)

## Current behavior

The YAML example references `tunnel_addr` on port 3024 which means anyone joining a root cluster via multiplexing is more likely to fail.

Case in point: https://github.com/gravitational/teleport/discussions/33012

![image](https://github.com/gravitational/teleport/assets/897821/6393b756-6c10-438c-80ee-b5ba5b4cdc18)

Bug details:
- Teleport version: 14.0.2

**Comment by stevenGravy** [comment]
Looks same as https://github.com/gravitational/teleport/issues/11078

**Comment by webvictim** [comment]
Yes, very similar.
