### ISSUE TITLE
Spammy log message regarding roles/traits in identity when using Github as a provider

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3301]
**What happened**:

```
Jan 24 13:20:39 artemis teleport[602]: WARN             "Failed to find roles or traits in x509 identity for testuser. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:1418
Jan 24 13:20:39 artemis teleport[602]: WARN             "Failed to find roles or traits in x509 identity for testuser. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:1418
Jan 24 13:20:42 artemis teleport[602]: WARN             "Failed to find roles or traits in x509 identity for testuser. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:1418
Jan 24 13:20:42 artemis teleport[602]: WARN             "Failed to find roles or traits in x509 identity for testuser. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:1418
Jan 24 13:20:45 artemis teleport[602]: WARN             "Failed to find roles or traits in x509 identity for testuser. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:1418
Jan 24 13:20:45 artemis teleport[602]: WARN             "Failed to find roles or traits in x509 identity for testuser. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:1418
Jan 24 13:20:48 artemis teleport[602]: WARN             "Failed to find roles or traits in x509 identity for testuser. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:1418
Jan 24 13:20:48 artemis teleport[602]: WARN             "Failed to find roles or traits in x509 identity for testuser. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:1418
Jan 24 13:20:51 artemis teleport[602]: WARN             "Failed to find roles or traits in x509 identity for testuser. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:1418
Jan 24 13:20:51 artemis teleport[602]: WARN             "Failed to find roles or traits in x509 identity for testuser. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:1418
Jan 24 13:20:51 artemis teleport[602]: INFO             [WEB] closing context testuserbd458a9cdd647cda0a6cd26018880b55 web/sessions.go:361
```

When the web UI of a Teleport cluster which uses Github auth is open in a browser tab, the message above is spammed into the Teleport log twice every three seconds.

**What you expected to happen**:

This message isn't useful for an end user or actionable and there's no way to stop it while the UI is open. We should:
1) Reduce the frequency with which it prints; once each time the user is logged in would be acceptable
2) Add an actionable step for how the user can fix the problem

If there is no actionable step or anything that the user can do to fix this (which may always be true in the case of Github auth) then I don't think we should print the message at all. At the very least if we're going to print it this often, we should drop it to `DEBUG` level so it doesn't show up in regular logs.

This seems to predominantly affect OSS clusters because their default auth method is Github, but this bug does also affect Enterprise clusters using Github auth. I don't know if there are other SAML/OIDC providers which are also affected.

**How to reproduce it (as minimally and precisely as possible)**: Set up an OSS or Enterprise cluster, deploy the Github connector and then log in via the web UI as a Github user which is mapped to a Teleport role.

**Environment**:
- Teleport version (use `teleport version`): `Teleport Enterprise v4.2.0git:v4.2.0-0-g3090806 go1.13.2
`
- Tsh version (use `tsh version`): `Teleport v4.2.0 git:v4.2.0-0-g3090806 go1.13.2`
- OS (e.g. from /etc/os-release): `Raspbian GNU/Linux 10 (buster)`

**Comment by webvictim** [comment]
Triage:
- This seems to occur because we run `ExtractFromIdentity()` and expect to find a list of `groups` and `traits` on the certificate
- We run `MissingIdentity()` which returns true if either `groups` or `traits` is zero
- In the Github connector, we never actually set values `groups` on the certiticates because they're not valid concepts in the OSS edition, only in Enterprise
- Keeping the web interface open calls `ExtendWebSession()` on a reasonably regular basis, `ExtendWebSession()` calls `ExtractFromIdentity()` and runs into the `MissingIdentity()` situation every time.

**Comment by dheitman42** [comment]
I'm experiencing the same, or possibly just similar, issue.  We're using gitlab as an identity provider, and I've created a local Teleport user, and created an API key for said user.  Every time the API is called, it generates two log messages exactly like this.

**Comment by zmb3** [comment]
This message no longer exists.
