### ISSUE TITLE
Include Audit Log with JIT Access Request

### ISSUE THREAD

**Issue by djohns7** [gravitational/teleport#33021]
What would you like Teleport to do?
Compile or link to the audit log associated with a JIT access requests, so JIT requests can include a review of all actions taken.

What problem does this solve?
Customer requires reviews of access requests to ensure what was stated is what was accomplished. Using audit log filters, we could include a link or report of the actions taken during an access request.

If a workaround exists, please include it.
Customer can manually retrieve the request ID and then using a SEIM query the audit logs for associated actions.

**Comment by zmb3** [comment]
Duplicate of #29533
