### ISSUE TITLE
EICE integration UX issues

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#33032]
I was trying to go through the new EIC flow, starting from scratch (configuring AWS integration) and couldn't get it to work. Here's the list of bugs and papercuts I've encountered that we need to fix.

## (Bug) Create AWS integration default policy should include DescribeInstances permission

Right now it only asks for RDS permissions so it can't be used for EIC flow right after creation.

<img width="804" alt="Screenshot 2023-10-05 at 11 17 37 AM" src="https://github.com/gravitational/teleport/assets/339322/78cf9131-1c4f-4e6d-ab32-d761ea450571">

## (UX) CloudShell link in the error should be clickable

The error tells you to open CloudShell but there's no link to click to open it.

<img width="1036" alt="Screenshot 2023-10-05 at 11 10 54 AM" src="https://github.com/gravitational/teleport/assets/339322/a62761e1-c6e7-4121-a91e-a42e821180f7">

## (Bug) CloudShell script for assigning extra permissions doesn't work

The script itself downloads fine but always returns 404.

<img width="1288" alt="Screenshot 2023-10-05 at 11 14 01 AM" src="https://github.com/gravitational/teleport/assets/339322/c80bfea0-45e2-41ed-a08b-8334a1b07bac">

## (UX) EC2 instances table should include Name column

We should display Name in a separate column like AWS console does.

<img width="1028" alt="Screenshot 2023-10-05 at 11 19 44 AM" src="https://github.com/gravitational/teleport/assets/339322/eae7696a-0104-4ff6-b7de-227d6254001c">

## (Bug) Even with `ec2:DescribeInstances` permission, can't get past "Enroll EC2 instance" step

Since the shell script above didn't work, I added `ec2:DescribeInstances` permission manually to my OIDC provider role.

This made the instances table work, however, after picking an instance and clicking Next, I still got the same error about lacking some permission and asking me to run the script which doesn't work.

## (Bug) UI gets in a blocked state where you can't click Next

After above and clicking Refresh, the UI got into a weird state where I can pick and instance but Next button is disabled. You have to exit the wizard completely and start over to get out of it.

<img width="1064" alt="Screenshot 2023-10-05 at 11 21 03 AM" src="https://github.com/gravitational/teleport/assets/339322/2d9d86fd-c274-452c-a8b6-bcfb1ca3c193">

## (UX) Each resource enrollment flow should tell you which permissions it needs

Every step that calls an AWS API should tell you exactly what permissions it needs to work in some kind of a hint block or dialog.

Even after adding `ec2:DescribeInstances` permission to my OIDC provider role, I couldn't get it to work since I assume it still lacks some permissions.

**Comment by marcoandredinis** [comment]
> (Bug) CloudShell script for assigning extra permissions doesn't work

This should be fixed by this PR
https://github.com/gravitational/teleport/pull/33061

**Comment by marcoandredinis** [comment]
> (UX) CloudShell link in the error should be clickable

This should be fixed by this PR
https://github.com/gravitational/teleport/pull/33062

**Comment by marcoandredinis** [comment]
> (Bug) Even with ec2:DescribeInstances permission, can't get past "Enroll EC2 instance" step

There's a couple more required permissions for being able to use this feature.
I wouldn't consider this a bug.
Re-running the script should be the way to go, IMO.

I think we could improve the UX :+1: 
I like your suggestion here:

> (UX) Each resource enrollment flow should tell you which permissions it needs

For the record, those are the required permissions for the flow
https://github.com/gravitational/teleport/blob/2fc901c44455243dc1d9fd9281e3c0d8ba8f44d7/lib/cloud/aws/policy_statements.go#L109-L129

**Comment by marcoandredinis** [comment]
> (Bug) Create AWS integration default policy should include DescribeInstances permission

I would move this to UX
So, we will have a new screen for the Set Up Integration step, where a user is asked to run a script in CloudShell.
This means that the integration set up is extracted from anything else
Why would someone add `rds:DescribeDBInstances` when they are just interested in EC2?

From UX prespective, I think it's ok to have two scripts to run:
- one to set up the integration
- another one to set up the required policy for the current use case

However, we might want to have a script that Sets Up the integration and also the required permissions for the current use case.
Eg, When adding an EC2 without an Integration, the user would be greeted with a script that would set up the integration **and** set up the required policies for accessing EC2 instances.

That's valid, but again, IMO, falls into improving UX.

**Comment by marcoandredinis** [comment]
> (UX) EC2 instances table should include Name column

Should be fixed in https://github.com/gravitational/teleport/pull/33064

**Comment by r0mant** [comment]
We've resolved most of these now.
