### ISSUE TITLE
per-session MFA for kubernetes does not work on Teleport Connect 

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#33081]
### Expected behavior:

With per-session MFA enabled, I should be prompted for my 2fa when I open a kube cluster in the Teleport Connect UI.

### Current behavior:

Teleport Connect does not prompt for 2fa, and all requests fail with

```
% kubectl get node
Error from server (Forbidden): kubernetes cluster "mycluster1" not found
```

### Bug details:
- **Teleport Connect version**:  `Version 14.0.1 (14.0.1.1612)`
- **Teleport Proxy version**: 13.4.2
- ```Recreation steps``` - enable per-session mfa, verify it works with `tsh proxy kube` outside Teleport Connect. Then try opening the same cluster inside Teleport Connect.
- Debug logs

**Comment by ravicious** [comment]
Done in #35361, will be released in 15.0.0.
