### ISSUE TITLE
Request a FAQ about where to ask questions

### ISSUE THREAD

**Issue by pmorch** [gravitational/teleport#331]
I'd like to ask if this could be covered e.g. in the FAQ: Where should one ask questions?

[The homepage](http://gravitational.com/teleport/) mentions two mailing lists.

One I can join in the bottom. I joined, but could not find an archive, email address or any way to post to it. Is it for announcements from Gravitational only? It doesn't say.

There is also a link to [teleport-dev@googlegroups.com](https://groups.google.com/forum/#!forum/teleport-dev) which is closed. I applied to join it, but the name doesn't imply that it is a good place to ask user questions...

So where should one ask questions? My particular question was related to #309 so I [piggy-backed my question](https://github.com/gravitational/teleport/issues/309#issuecomment-204820775) to that issue.

**Comment by pmorch** [comment]
And if the reason that there isn't a place to ask questions is that you don't want to spend the man-power on it ( I totally understand ), I might suggest:

> Ask questions on [serverfault.com and tag them "gravitational-teleport"](http://serverfault.com/questions/ask?tags=gravitational-teleport)

That way all the questions are tagged the same way, are crowd-sourced, wonderfully searchable and you don't have to maintain infrastructure.

Either way I just wanted to know where to ask... ;-)

**Comment by kontsevoy** [comment]
@pmorch: `teleport-dev@` is the best place to ask! Yes, it's empty because it was created a couple of days ago ;) Github is good too. Thanks.
