### ISSUE TITLE
Run BPF tests in CI

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3310]
CI/CD pipeline does not run BPF tests at the moment. Run tests.

**Comment by russjones** [comment]
Best: 3 day.
Realistic: 8 days.

**Comment by webvictim** [comment]
This needs a throwaway VM for each test run. @russjones has written a script to stand up the VPC/subnet/instance automatically but the best way to make it happen reliably/easily might just be to use Packer and not save the AMI at the end.

To keep costs down we should only run BPF tests on push. It also needs to be quick - ideally we want an answer within ~7 minutes as that’s how long all the push builds on `master` take to run currently.

This may change with the new BPF improvements which are coming.
