### ISSUE TITLE
Notify a user about required proxy node upgrade via web UI

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#3313]
Teleport V5 will introduce some breaking changes to the web UI when connecting via proxy of an older version. When it happens, proxy should notify a web user about required proxy node upgrade.

1. Allow proxy node to know auth node version
2. Redirect a user to /msg/ page with the text about required upgrade ( ?message="user_message")

In other words, when a user attempts to signup with the following URL
`https://XXXX:3080/web/newuser/tokenID`

We need to redirect a user (on the backend) to the following page
`https://XXX:3080/web/msg/error?details=There is a version mismatch between your proxy and auth services. Please upgrade your proxy service to the 5.0.0 or higher.`

Which can be done [from this place](https://github.com/gravitational/teleport/blob/master/lib/web/apiserver.go#L280). Where we can check if auth. service is >= 5.0.0 and proxy version is less than that.

![image](https://user-images.githubusercontent.com/7816406/76975639-38653380-6909-11ea-938a-ff430c910e33.png)

**Comment by benarent** [comment]
We discussed this today. How many versions do you think we should back port this to @alex-kovoy?

**Comment by alex-kovoy** [comment]
Only 4.3 version needs this small change. @benarent
