### ISSUE TITLE
allow github tokens for unreachable github enterprise instances.

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#33171]
### What would you like Teleport to do?

It should be possible to configure a github token with a statically defined jwks, so the auth service does not need to load it from the github enterprise backend. This will allow the Auth service to trust tokens signed in an internal network that it cannot reach.

This is similar to https://github.com/gravitational/teleport/pull/30225 for kube tokens.

### What problem does this solve?

When following the [github actions](https://goteleport.com/docs/ver/13.x/machine-id/guides/github-actions/) token guite with a Github Enterprise that is not reachable from the Teleport auth service, it fails.

This is a concern when using Teleport Cloud.

### If a workaround exists, please include it.

none

**Comment by strideynet** [comment]
Extremely similar to https://github.com/gravitational/teleport/issues/30831 - I'm going to close this as dupe and make this part of that ticket since the solution will easily be implemented for both at the same time and the same limitations apply.

**Comment by strideynet** [comment]
Merged with https://github.com/gravitational/teleport/issues/30831
