### ISSUE TITLE
Fix default cluster name stored against QR code when registering a local account

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3318]
**What happened**: I wanted to add a user to a cluster that's been generated using our Terraform scripts:
```
[root@ip-172-31-0-46 ~]# tctl users add gustwo --roles=admin
Signup token has been created and is valid for 1 hours. Share this URL with the user:
https://gus-example.gravitational.io:443/web/newuser/1e5014f8b9cc782620b20ae46808a6a6

NOTE: Make sure gus-example.gravitational.io:443 points at a Teleport proxy which users can access.
When the user 'gustwo' activates their account, they will be assigned roles [admin]
```

After I scan the presented QR code to set up TOTP, the default name which gets stored in my authenticator app (Google Authenticator) isn't very descriptive or helpful (I added two accounts here for testing):

![image0](https://user-images.githubusercontent.com/897821/73566830-3e778180-443b-11ea-9843-581dda1f6465.jpeg)

I think the caption is currently set to the `nodename` of the auth server node where I issued the `tctl` command. Some apps (like Authy) allow you to change this name while you're adding a token, but Google Authenticator doesn't. It **is** possible to edit the name after you've finished adding it to Google Authenticator, but this is an extra manual step that you have to remember to do.

**What you expected to happen**: The config for this cluster has `proxy.service_public_addr` set correctly in the config, as is reflected in the user join URL. I think it would make much more sense if the default 'caption' or name offered when scanning the QR code matches the value of `proxy_service.public_addr` if set so it's much more obvious which 2-factor token applies to which cluster. Another possibility would be the `cluster_name` from the Teleport config, if set.

I have around 30 2-factor tokens of various kinds, so naming them is critical to be able to find the right one.

**How to reproduce it (as minimally and precisely as possible)**: Add a local user to a Teleport cluster and scan the QR code.

**Environment**:
- Teleport version (use `teleport version`): `Teleport Enterprise v4.1.4git:v4.1.4-0-gc487a75c go1.13.2`
- Tsh version (use `tsh version`): `Teleport v4.1.4 git:v4.1.4-0-gc487a75c go1.13.2`
- OS (e.g. from /etc/os-release): `Fedora 30`

**Comment by benarent** [comment]
Now you mention this, I have the same problem. 

Let's move forwards with using  `proxy.service_public_addr` or `cluster_name` if set. 

I would rank this as low, but an annoying bug we should fix.

**Comment by sh7dm** [comment]
I'm working on this one, will open a PR soon.
