### ISSUE TITLE
Ability to test if a specific user exists

### ISSUE THREAD

**Issue by jaxxstorm** [gravitational/teleport#332]
At the moment, if I want to check for users that exist I have to do the following:

```
tctl users ls | grep something
```

This might get unwieldy if we have a lot of users. It would be great if the command could be expanded so that I could do this:

```
tctl users ls something
```

And it would return just the username `something` and who they're allowed to login as.

**Comment by kontsevoy** [comment]
Hey @jaxxstorm, we're going to close this one. Eventually there will be pluggable account backends and a more comprehensive "search" API will be added. Right now it feels premature.

We did, however, implement pre-defined AKA "static" tokens you've requested ;)
