### ISSUE TITLE
Add command line flag to prevent 'tsh login' from opening a browser

### ISSUE THREAD

**Issue by clement-escolano** [gravitational/teleport#3321]
**What happened**:
I logged in by running: `tsh --proxy=teleport.corp.blablacar.com login`.
My default browser Safari opened.

**What you expected to happen**:
Nothing (or at least an option to open a specific browser or no browser).

**How to reproduce it (as minimally and precisely as possible)**:
Just run `tsh --proxy=teleport.corp.blablacar.com login`.

**Environment**:
- Teleport version (use `teleport version`): `Teleport v4.2.2 git: go1.13.6`
- Tsh version (use `tsh version`): `Teleport v4.2.2 git: go1.13.6`
- OS (e.g. from /etc/os-release): macOS 10.14

**Browser environment**

- Browser Version (for UI-related issues): Safari 12
- Install tools: ?
- Others: ?

**Comment by webvictim** [comment]
Your browser needs to be open in order to actually pass the authentication data from the identity provider back to Teleport, so I don't think what you're asking is possible.

**Comment by clement-escolano** [comment]
I know that I need to open some browser to authenticate.
However, the default browser on my computer is not the one I use to authenticate. So everytime I want to login, Safari opens above everything, I have to close it then enter the link in the shell inside my other browser.
If there was an option to do nothing, I could just get the link and then paste it in my browser.

**Comment by webvictim** [comment]
On OS X, `tsh` just calls `open http://127.0.0.1:12345/etc` to load the browser, so it'll use whatever your default browser is set to.

Is changing your default browser to the correct one not an option?

**Comment by webvictim** [comment]
At any rate, adding a command-line flag to say "don't open the browser for me" is probably the easiest way to fix this and should be fairly easy to do.

**Comment by clement-escolano** [comment]
Thank you for your answers.

> On OS X, `tsh` just calls `open http://127.0.0.1:12345/etc` to load the browser, so it'll use whatever your default browser is set to. On Linux it uses `xdg-open`, on Windows `rundll32.exe url.dll,FileProtocolHandler` etc.

I tried to alias `open` to something else to prevent the opening of the browser but it didn't work unfortunately.

> Is changing your default browser to the correct one not an option?

I have a browser for work (the one with authentication) and another for personal life (the default one). That's why I would like to keep separated the two.

**Comment by hooksie1** [comment]
I'd like to take a stab at a PR for this. Looks like I need to add the flag for login, add a boolean to the TeleportClient and the Config structs, and then just check if it's true or false. Do you want the output to be different? Instead of saying "If browser window doesn't open automatically...", just say "click the following URL".

**Comment by webvictim** [comment]
Yes, if the auto-open behaviour is suppressed then the message should be changed to indicate that the URL needs to be clicked manually.

**Comment by hooksie1** [comment]
Opened PR #3611 for this.
