### ISSUE TITLE
Documentation clarification on long lived signed keys

### ISSUE THREAD

**Issue by jowrjowr** [gravitational/teleport#3332]
Not a bug, per se, but something that I feel should be fixed in the documentation to avoid timewastage in the future. I am not new to SSH but SSH CA usage is new to me.

Normally for SSH clients, you only need the private key to login to a server. This is not the case with SSH certificates - you need the private key and the certificate otherwise 

https://gravitational.com/teleport/docs/admin-guide/#using-teleport-with-openssh

There needs to be a clarification/note indicating that if you are deploying the key you create from ```tctl auth sign```, you need to include the certificate public key as well. 

This is crucially important when it comes to CI tools like jenkins/circleCI.

**Comment by webvictim** [comment]
Yeah, valid point. It's something I've noticed more recently too and it isn't easily obvious. We'll get something into the docs.
