### ISSUE TITLE
User signup

### ISSUE THREAD

**Issue by jaxxstorm** [gravitational/teleport#334]
I'm trying to automate the user creation for teleport using a Puppet provider:

https://docs.puppetlabs.com/guides/provider_development.html

This helps me centrally manage the users and Puppet's provider system makes it easy with methods to only add the user if it doesn't exist.

The problem is, when creating a new user, it outputs the signup page and the user isn't created until that page is accessed. 

Now, I can have the provider output the result of running `tctl users add`, but I think this is a security issue, because anyone could potentially view the output of that command and then steal the users login on first run.

What would help a lot would using email to do the initial sign up. You pass an email address for the user and then the sign up link gets sent to their email address. This would probably also help drastically with things like forgotten passwords etc. I understand at the moment the only way to modify users is to delete and recreate them, so I suspect anything like this is dependent on that happening.

**Comment by kontsevoy** [comment]
@jaxxstorm the upcoming v1 will have an integration with external identity managers. Teleport by itself should not be considered (in our humble opinion) to be the primary identity storage. Then you'd use 3rd party tools to manage users and Teleport will sync their identities from there.
