### ISSUE TITLE
[Enhancement] Add k8s integration to session recording/audit log

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport#3342]
Customer feedback of extending session recording/audit log to include some k8s integration of seeing the following on users:

- pod user accessed
- what time access occurred
- what namespace
- inside what cluster

**Comment by stevenGravy** [comment]
A icon or text label  indicating if a session was ssh or k8s would be helpful.

**Comment by benarent** [comment]
This should be addressed by duplicate of https://github.com/gravitational/teleport/issues/3528
