### ISSUE TITLE
[REQUEST] Node-based Logins

### ISSUE THREAD

**Issue by nooraimanr** [gravitational/teleport#33443]
What would you like Teleport to do?
Allow the configuration of node-based logins for users.

What problem does this solve?
**PROBLEM**: When added "root" as one of the allowed logins for users, it allows also access to other "higher-privilege" servers that the users may access using "non-root" logins. 

**REQUEST**: Limits users to login as "root" on certain servers while allowing "root" logins on other servers. 

If a workaround exists, please include it.

**Comment by stevenGravy** [comment]
You can assign multiple roles to a user to have different permissions such as root logins depending on the label.
