### ISSUE TITLE
Teleport sometimes creates orphan shell processes.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3345]
A customer has reported that if their session is interrupted by network glitch or client crash bash session on the remote machine is not closed. For example:

```
init(1)─┬─abrt-dump-oops(2826)
        ├─acpid(2112)
        ├─agetty(2947)
        ├─atd(2876)
        ├─bash(2937)───sleep(29307)
        ├─bash(25414,username)
```

Note `bash(25414,username)`.

This is most likely due to the chances in shell execution introduced in Teleport 4.2. Teleport now reexecs itself before launching a shell. If the parent process dies, the children will be re-attached to PID 1.

The fix is most likely going to be to create a process group during execution and send a kill signal to all.

**Comment by russjones** [comment]
A possible error that occurs when this happens.

```
ERRO [NODE]      Failed to remove active session: 00000000-0000-0000-0000-000000000000: /namespaces/default/sessions/active/00000000-0000-0000-0000-000000000000 is not found. Access to backend may be degraded, check connectivity to backend. id:946 local:10.10.10.10:35124 login:ubuntu remote:1.1.1.1:49893 teleportUser:foo@example.com srv/sess.go:888
```

**Comment by awly** [comment]
`lib/web` unit tests create ~4 orphan shell processes.
Other tests may be leaking some too.
I'll poke around more to see if there's some exec cleanup missing there.

**Comment by awly** [comment]
The following tests leak 1 shell process each:
- TestResizeTerminal
- TestTerminal
- TestWebAgentForward
- TestActiveSessions
