### ISSUE TITLE
Unusable tsh download links are documented when scoped to Teleport Enterprise Cloud

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#33457]
## Applies To

https://goteleport.com/docs/installation/

## Details

Teleport SaaS Cloud currently is running 13.4.2, a private security release before the public 13.4.3 was announced.  We don't release `tsh` versions for the private releases.  This means when scoped to Teleport Enterprise Cloud all the `tsh` installation instructions are failing right now.

## How will we know this is resolved?

The docs installation page does not recommend `tsh` installation instructions for a version without a `tsh` release.

**Comment by zmb3** [comment]
> We don't release tsh versions for the private releases. 

I don't think this is true. I can pull https://cdn.teleport.dev/tsh-13.4.2.pkg just fine.

**Comment by pschisa** [comment]
The customer was specifically testing with `teleport-v13.4.2-windows-amd64-bin.zip`.  At the time I could recreate like the customer but I cannot now.  Since no logs were captured, moving to closed and will revisit if the issue arises again in the future
