### ISSUE TITLE
Better error message when connecting to incompatible Auth Server.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3347]
A customer was trying to connect a Teleport 4.2.2 node to a 3.2.4 auth server. Teleport was failing to start with the following error message:

```
 WARN [PROC:1]    Failed to write Node identity: missing parameter SSH CA bytes.
                  service/connect.go:405
```

Now that a Ping endpoint has been added to the Auth Server in https://github.com/gravitational/teleport/pull/3324 we should look into the feasibly of calling Ping and checking for version compatibility before doing anything else.

**Comment by zmb3** [comment]
Tagging with `time-to-value` since we've been discussing failing on startup (with a `--skip-version-check` escape hatch) when connecting to an outdated auth/proxy server.

**Comment by r0mant** [comment]
I think this is implemented now. @capnspacehook We implemented the auth version check, correct?

**Comment by capnspacehook** [comment]
Yep, in https://github.com/gravitational/teleport/pull/12797
