### ISSUE TITLE
`teleport join openssh` is missing from `teleport` CLI reference

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#33516]
## Applies To

https://goteleport.com/docs/reference/cli/teleport/

## Details

`teleport join openssh` should be added to this list to keep the reference accurate and provide a place to link to from elsewhere in the docs.

## How will we know this is resolved?

The `teleport` CLI reference will contain a `teleport join openssh` section.

## Related Issues

Original docs issue: https://github.com/gravitational/teleport/issues/25963
Follow-up docs issue: https://github.com/gravitational/teleport/issues/29901

**Comment by zmb3** [comment]
Fixed in #38093
