### ISSUE TITLE
Add a response header

### ISSUE THREAD

**Issue by Wyrzelek** [gravitational/teleport#33512]
What would you like Teleport to do?
Add a response header so the browser sees it because browser uses it

What problem does this solve?
When we try to connect teleport SSO with Structurizr, browser have problem with CPS header, and we cant add it:
![obraz](https://github.com/gravitational/teleport/assets/148060350/18056019-da68-4415-8e27-e2591bbf50b0)

If a workaround exists, please include it.

**Comment by strideynet** [comment]
When you say "CPS" is this referring to "CSP" e.g Content Security Policy ?

**Comment by Wyrzelek** [comment]
Yes, sorry, i wrote acronim in wrong order :)

**Comment by zmb3** [comment]
I'm not sure I understand this request.
