### ISSUE TITLE
Documentation: Broken Link in Quickstartguide (HTTP 404)

### ISSUE THREAD

**Issue by SvenMW** [gravitational/teleport#3354]
**What happened**:
I was just diving into the docs to learn about teleport.
On this page:
https://gravitational.com/teleport/docs/quickstart/
is this link:
https://gravitational.com/teleport/docs/quickstart/architecture
labeled as "We recommend that you read the Architecture Guide[..]"

which gives me HTTP 404 and honestly a bad first impression about the state of the docs.

**What you expected to happen**:
the link should work

maybe this is the correct link (i'm a newbie, so please check for yourself)?
https://gravitational.com/teleport/docs/architecture/teleport_architecture_overview/
**How to reproduce it (as minimally and precisely as possible)**:
see above
**Environment**:
Does not apply
**Browser environment**
Firefox
- Browser Version (for UI-related issues):
n/a

**Relevant Debug Logs If Applicable**
n/a

**Comment by benarent** [comment]
Thanks @SvenMW, I saw your other post on using Teleport with for users on Windows. I think it would be good to setup a call to discuss what you would think would be an ideal experience when rolling out Teleport.  Could you e-mail ben@gravitational.com and we can setup a time once we have connected.
