### ISSUE TITLE
Feedback for resting user password CLI 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3363]
This Issue contains product feedback from testing https://github.com/gravitational/teleport/issues/3265 

### Provide reset context via `tokens ls`

**Current**
```
teleport5auth ~: sudo tctl tokens ls
Token                            Type           Expiry Time (UTC)
-------------------------------- -------------- ------------------------------
cluster-join-token               Proxy,Node    never
6ff9b6ee380999bcfea13c6e09d6c7f6 User Signup    19 Feb 20 04:57 UTC (7h55m47s)
```

**Proposed**
```
teleport5auth ~: sudo tctl tokens ls
Token                            Type        Expiry Time (UTC)
-------------------------------- ----------- ------------------------------
cluster-join-token               Proxy,Node  never
6ff9b6ee380999bcfea13c6e09d6c7f6 Password    19 Feb 20 04:57 UTC (7h55m47s)
```

### Inform users that it's only for Teleport DB user only 

**Current**
```
Commands:
  help         Show help.
  users add    Generate a user invitation token [Teleport DB users only]
  users ls     List all user accounts [Teleport DB users only]
  users rm     Deletes user accounts
  users reset  Reset user password and generate a new token
```

**Proposed**
```
Commands:
  help         Show help.
  users add    Add a new user and generate a password reset token [Teleport DB users only]
  users ls     List all user accounts [Teleport DB users only]
  users rm     Deletes user accounts
  users reset  Reset user password and generates a new token  [Teleport DB users only]
```

### Who reset the password?
When using `tctl` we don't know who reset the password, but do know it was someone with tctl access. I would suggest that we take this into consideration with the audit log.  Example audit events [Current Events](https://gist.github.com/benarent/1aaf5370cd8e5dc5ef976400017ac22e)

**Current**
![image](https://user-images.githubusercontent.com/559288/74778429-67c44a00-5250-11ea-8456-1436e45f7aa8.png)
**Proposed**
![image](https://user-images.githubusercontent.com/559288/74778645-d99c9380-5250-11ea-9701-48555ecaf13f.png)

### Example Setup and Reset

**Current**
```
$ tctl users add benarent2 --roles=admin
Invite token has been created and is valid for 1h0m0s. Share this URL with the user to complete user setup:
https://teleport5auth.com:3080/web/invite/c877f7f46e8d2c1c8909a2a1310f9557

NOTE: Make sure teleport5auth.com:3080 points at a Teleport proxy which users can access.
```
```
$ tctl users reset benarent2
Reset password token has been created and is valid for 8h0m0s. Share this URL with the user to complete password reset process:
https://teleport5auth:3080/web/reset/5b81e866c44c6d65945a11c08f36acfb
```

**Proposed**
```
$ tctl users add benarent2 --roles=admin
User benarent2 has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h0m0s
https://teleport5auth.com:3080/web/invite/c877f7f46e8d2c1c8909a2a1310f9557

NOTE: Make sure teleport5auth.com:3080 points at a Teleport proxy which users can access.
```
```
$ tctl users reset benarent2
User benarent2 has been reset. Share this URL with the user to complete password reset, link is valid for 8h0m0s. 
https://teleport5auth:3080/web/reset/5b81e866c44c6d65945a11c08f36acfb
```

**Comment by benarent** [comment]
@alex-kovoy I had a chance to review this today. I've left my comments in the ticket.

**Comment by alex-kovoy** [comment]
> User benarent2 has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h0m0s

Should we then show Reset Password form instead of Invite? So URL will have `/reset` in it.

**Comment by benarent** [comment]
We should still have two different experiences for first time password creation vs password reset. This will help with onboarding, and will provide extra context on reset.

**Comment by alex-kovoy** [comment]
> We should still have two different experiences for first time password creation vs password reset. 
 his will help with onboarding, and will provide extra context on reset.

I think a better experience would be to keep things consistent. What is "first time password creation" vs "reset password" ? How would it be communicated between teleport admins/users? Do we expect to have different default ttl values?

Here is a situation: a user is having issues with invite, he then asks an admin a question - "Invite form gives me an error about expired token". Is it clear from this question that reset password token needs to be regenerated?

It feels that we are artificially creating 2 different experiences from the same use-case.

**Comment by alex-kovoy** [comment]
[update] The wording has been updated by Ben. We need to make sure that the text matches Ben's **Proposed** versions the ticket body.
