### ISSUE TITLE
`TestCloseWithActiveConnections` flakiness

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#33659]
#### Link(s) to logs

https://github.com/gravitational/teleport/actions/runs/6564837632/job/17832063788

#### Relevant snippet

```
    server_test.go:461: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/db/server_test.go:516
        	            				/__w/teleport/teleport/lib/srv/db/server_test.go:461
        	Error:      	Condition never satisfied
        	Test:       	TestCloseWithActiveConnections
        	Messages:   	expected one active connection, but got none
```

**Comment by zmb3** [comment]
@smallinsky does anyone on the DB team have time to investigate this one?

**Comment by smallinsky** [comment]
> does anyone on the DB team have time to investigate this one?
Yes, Thanks for reporting. 

@gabrielcorado Could you take a look at this test flakiness ?

**Comment by gabrielcorado** [comment]
Recently, I've opened a PR with an attempt to solve this falkiness (#32923). It wasn't backported, so I'm opening it now (v13: #33687, v14: #33686)
