### ISSUE TITLE
adding tsh config to ssh config causing other VMs to fail

### ISSUE THREAD

**Issue by ss2342** [gravitational/teleport#33703]
Expected behavior:
Ability to log in to other VMs should not be affected by adding in tsh config to ssh config

Current behavior:
I am unable to access all my other VMs after updating my ssh config with tsh config

Bug details:
- Teleport version: 14.0.0

**Comment by stevenGravy** [comment]
The ssh config could have a conflict if you have similar named nodes.  I'd suggest going to the Teleport community slack channel to walk through the issue.  Please share some more details otherwise on what you're experiencing.
