### ISSUE TITLE
Integration test ‘TestHA’ is broken

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3371]
**What happened**: Integration test `TestHA` (https://github.com/gravitational/teleport/blob/master/integration/integration_test.go#L1196-L1271) is broken. It will either pass or fail depending on timing/power of the system running it. The behaviour is very inconsistent. On Jenkins it fails the majority of the time.

**What you expected to happen**: The test should have a definitive outcome which happens every time it is run.

**How to reproduce it (as minimally and precisely as possible)**: `make integration` or `make -C build.assets integration`

**Environment**:
- Teleport version (use `teleport version`): `4.2.2`
- Tsh version (use `tsh version`): `4.2.2`
- OS (e.g. from /etc/os-release): Fedora 30

**Comment by webvictim** [comment]
Based on the output of the test, this may be related to https://github.com/gravitational/teleport/issues/3137

**Comment by awly** [comment]
Has https://github.com/gravitational/teleport/pull/3536 fixed this?

**Comment by webvictim** [comment]
I think so. I’ll close the issue for now - we can always reopen if needed.
