### ISSUE TITLE
Configurable home location for tsh configuration and data

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3375]
**What happened**:

> Configurable home location for tsh configuration and data. For example on Linux it would be default as "tsh -C /home/oliver/.tsh". However the use case is actually for Windows where we have systems that have home folder on a network drive that is cross mounted from Linux systems, but the Windows AppData and other default home locations are not to be used.

**What you expected to happen**:
As part of https://github.com/gravitational/teleport/issues/3089 we should provide options to set `TSH_CONFIG_FILE` as an environment variable.   TBD final design and UX

**Comment by webvictim** [comment]
I think `TSH_HOME` is probably more appropriate.

**Comment by gclawes** [comment]
Agreed.  If tsh used something like a single `KUBECONFIG` file, `TSH_CONFIG_FILE` would make more sense.
