### ISSUE TITLE
FHS compliance is partial

### ISSUE THREAD

**Issue by renich** [gravitational/teleport#3391]
**What happened**:
You correctly instruct to put binary is in `/usr/local/bin` but, then, you instruct to add libraries to `/usr/lib/teleport`.

**What you expected to happen**:
They should be in `/usr/local/lib`.

https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html

**Comment by webvictim** [comment]
Can you provide a link to show where this is written?

**Comment by renich** [comment]
The link I provided states: 

>  /usr/local hierarchy is for use by the system administrator when installing software locally. It needs to be safe from being overwritten when the system software is updated.

**Comment by webvictim** [comment]
I understand that. I am asking where it says: `you instruct to add libraries to /usr/lib/teleport.`

**Comment by renich** [comment]
Oh! :smile: 

https://github.com/gravitational/teleport#building-teleport

**Comment by renich** [comment]
My bad. It's /var/lib/teleport what you're using. Misread... sorry
