### ISSUE TITLE
Azure Workload Identity authentication doesn't work with discovery service

### ISSUE THREAD

**Issue by MattiasAng** [gravitational/teleport#33920]
Expected behavior:

Able to authenticate to Azure Kubernetes Service clusters while using [Workload Identity](https://azure.github.io/azure-workload-identity/docs/) without enabling sidecar 

Current behavior:

Authentication errors with the following:

`The provided value for scope 6dae42f8-4368-4678-94ff-3960e28e3630 openid offline_access profile is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI). Trace ID: 128cabbc-cd70-4b93-884a-57dd05341f00 Correlation ID: 15b6b9d4-147a-4e86-b10d-cf350e16f432 Timestamp: 2023-10-25 13:06:09`

This could potentially be a quite easy fix. If you look at [Microsofts kubelogin flow](https://github.com/Azure/kubelogin/blob/2bce1c32aad5ed941d645f477acd64e9ff55cb6a/pkg/token/federatedIdentity.go#L62C1-L66C3) for Workload Identity, they simply append the suffix `/.default` on the Azure Managed Cluster Server ID, which you have a [variable](https://github.com/gravitational/teleport/blob/71a37bf50ca23ff8226a4431f4de8fd3aeaac50f/lib/cloud/azure/kubernetes.go#L427) for. This might however break other authentication flows, so I would suggest looking at if the environment variable `AZURE_FEDERATED_TOKEN_FILE` is set first before adding the suffix.

Bug details:
- Teleport version
14.1.0

- Recreation steps
1. Install [Workload Identity](https://azure.github.io/azure-workload-identity/docs/installation/managed-clusters.html#azure-kubernetes-service-aks) on a AKS cluster
2. Setup a service account for Teleport with a new Managed Identity with a Federated Credential
3. Setup `discovery_service` and create a discovery group for AKS.

- Debug logs
See relevant log above.

**Comment by MattiasAng** [comment]
@tigrato Sorry for tagging you directly, but since you implemented auto-discovery for AKS. Quite curious how you actually got this to work with AAD Managed clusters, as all the examples I've been able to find utilize the scope `6dae42f8-4368-4678-94ff-3960e28e3630/.default` to be able to authenticate properly.

Is there something I am missing here? This doesn't seem related to workload identity specifically, but all authentication flows for Azure.

**Comment by tigrato** [comment]
> @tigrato Sorry for tagging you directly, but since you implemented auto-discovery for AKS. Quite curious how you actually got this to work with AAD Managed clusters, as all the examples I've been able to find utilize the scope `6dae42f8-4368-4678-94ff-3960e28e3630/.default` to be able to authenticate properly.
> 
> Is there something I am missing here? This doesn't seem related to workload identity authentication specifically, but most authentication flows for Azure. Looking at the Azure Go SDK this [might not apply to Managed Identity.](https://github.com/Azure/azure-sdk-for-go/blob/0699b05a18bae7447d823d8c07bf84a6b6d6f532/sdk/azidentity/managed_identity_credential.go#L108-L109) (and possibly Azure CLI).
> 
> As an easy fix if this actually works for others, is allowing overriding the `azureManagedClusterScope` const with an environment variable.

Yes, that's indeed the case. It wasn't required when I initially developed the feature.
Will update.
Thanks!
