### ISSUE TITLE
[v.14.x] /docs/pages/management/export-audit-events/fluentd.mdx

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#33930]
## Applies To

https://goteleport.com/docs/management/export-audit-events/fluentd/
https://goteleport.com/docs/management/export-audit-events/datadog/
https://goteleport.com/docs/ver/13.x/management/export-audit-events/splunk
https://goteleport.com/docs/management/export-audit-events/elastic-stack/

## Details

In step to install the event handler plugin we suggest running the following command to download the teleport-event-handler for v13.

curl -L -O https://get.gravitational.com/teleport-event-handler-v13.4.4-linux-amd64-bin.tar.gz

At the time of submitting this issue, this teleport-event-handler versions is not available so the request will fail. v13.4.4 is not available [here](https://github.com/gravitational/teleport-plugins/releases) as a release. I believe the version presented is the latest Teleport release available. For Teleport v13, the latest version available of this plugin is: teleport-event-handler-v13.3.8-linux-amd64-bin.tar.gz

## How will we know this is resolved?

The latest release for the teleport-event-handlers are posted [here](https://github.com/gravitational/teleport-plugins/releases). 

## Related Issues

I could not find a related issue.

**Comment by zmb3** [comment]
We just need to hard code that version in the v13 and v12 branches since we no longer publish plugins releases for them.

**Comment by ptgott** [comment]
@zmb3 Would Teleport v12 use the latest 12x `teleport-plugins` release (v12.3.1), or v13.3.8 as well? Thanks!

**Comment by zmb3** [comment]
The latest v12 plugins release.
