### ISSUE TITLE
In web UI list tag file uploads and downloads in sessions with info

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3396]
File uploads and downloads are listed as sessions separately from the ssh session. From the web UI there are no indications that a given session is a scp/file interaction vs a ssh session.  If you attempt to play the scp session you get a series of circles spinning with no content.

 Having the file list would also be helpful.  This information is available within the log.

To reproduce:
Open a ssh session via the web ui to a node.  
echo "hello world" > hello.txt
Click the download icon in the webui and download ~/hello.txt
Close the ssh session. 
You will have two sessions listed in the sessions for this node.  One is the ssh session and the other is the file interaction.  The file session interaction will not play anything or indicate that it is a scp interaction.

This occurred in:
teleport enterprise 4.2.3
firefox: 73.0.1

**Comment by xinding33** [comment]
@sielakos Is it possible to print something to the terminal upon downloading a file? That way, we can delete the "non-interactive" session altogether and rely on the playable session recording to reference all events. Additionally, the download event is already recorded in the audit log so I'm not worried about auditability in general.

cc @stevenGravy

**Comment by sielakos** [comment]
@xinding33 Given that terminal is a separate session from the session for the downloading of the file, I honestly do not know if it is possible. And if it was possible how much work would that require for us?  

I would need advice from someone more experienced in that matter.

**Comment by sielakos** [comment]
@xinding33

Just to understand it better, do you want to add output to the SCP session that the file was downloaded while keeping it separate?
Or do you want to add to the terminal session information that the user downloaded a file?

**Comment by stevenGravy** [comment]
This no longer occurs with a sep session reported.
