### ISSUE TITLE
Can not login server via teleport.

### ISSUE THREAD

**Issue by Dancoa** [gravitational/teleport#33962]
Hello, you awesome people!

I'm having problems with SSH connections

As you see in this pic, I can't login into server via teleport:
![25842db6ec9bf3471098be49dbd003b](https://github.com/gravitational/teleport/assets/18479340/783a7554-4dd0-4141-ba21-596e99bb3617)

And I checked the status of teleport service in this server, it showed that:
![52b7ad95e0e164e714239b464e6ec86](https://github.com/gravitational/teleport/assets/18479340/5b561319-1752-4cfb-a28f-8d69f0fb9680)

I tried to restart teleport service and reinstall teleport agent in this server, but didn't work.

Have you encountered the same problem, or do you have any good suggestions?

Thank you very much for your help!!

**Comment by zmb3** [comment]
"Cert is not yet valid" sounds like a time drift issue. 

Is the system time on all machines correct?

**Comment by Dancoa** [comment]
Hi @zmb3 Thanks for your replying.
I've checked the system time.Everything is ok.
