### ISSUE TITLE
Provide more user friendly messages for audit commands

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#33966]
Expected behavior:

If `audit` commands do not apply a user friendly message that the cluster has not been configured with Audit querying or reporting.

Current behavior:

Attempting to use the `tctl audit` commands provides a service error without explanation.

```bash
$ tctl audit report ls
ERROR: unknown service teleport.secreports.v1.SecReportsService
```
```bash
$ tctl audit query ls
ERROR: unknown service teleport.secreports.v1.SecReportsService
```

Bug details:
- Teleport version: 14.1.1
- Recreation steps

Configure a Teleport 14.1.1 enterprise cluster with sql lite backend
Attempt to use the `tctl audit report ls` command.

**Comment by zmb3** [comment]
WDYM by _If audit commands do not apply_? 

Is this just when running against an OSS auth server or are there other cases?

**Comment by stevenGravy** [comment]
> WDYM by _If audit commands do not apply_?
> 
> Is this just when running against an OSS auth server or are there other cases?

This happens with Teleport Enterprise by default.

**Comment by stevenGravy** [comment]
If you setup Teleport 14.1.1 enterprise with a sqllite backend, start it and attempt to run those `tctl` commands you will get those above errors.

**Comment by zmb3** [comment]
This should be fixed now that we have a single build of tctl.
