### ISSUE TITLE
tsh ls provides different results than web UI

### ISSUE THREAD

**Issue by JonGilmore** [gravitational/teleport#3398]
**What happened**:
when I run `tsh ls` and filter by application, I'm seeing nodes that have since been terminated. When I check for those same instance ID's in the web UI, they don't show up. 

**What you expected to happen**:
I'd expect consistent results between the CLI and web UI

**How to reproduce it (as minimally and precisely as possible)**:
We're running IoT mode and recently switched to an in-memory cache for our proxy clusters. This issue is new since then. 

**Environment**:
- Teleport version (use `teleport version`): 4.2.3 beta1
- Tsh version (use `tsh version`): 4.2.2
- OS (e.g. from /etc/os-release): client: macOS

**Browser environment**
chrome

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by JonGilmore** [comment]
@benarent @klizhentas any updates on this? I'd love to jump on a call to discuss this further if possible - I think we have more details that could be helpful in digging into the root cause of this. 

cc @dmart

**Comment by benarent** [comment]
@JonGilmore I'll reach out to you this week to plan a call.

**Comment by benarent** [comment]
@JonGilmore This should be fixed with 4.2.9, can you let me know if you're still seeing this issue.
