### ISSUE TITLE
Headless login fails after 30 seconds

### ISSUE THREAD

**Issue by AntonAM** [gravitational/teleport#33982]
When using headless login, you're supposed to have 3 minutes to approve/reject it, but currently if you wait for more than 30 seconds it will fail with error for tsh `alertBadRecordMAC (20)`.

**Comment by Joerger** [comment]
Oddly enough, this is a regression. I remember testing this flow and it still works in v13.0.0.

**Comment by AntonAM** [comment]
@Joerger yep, write timeouts were added after you merged headless login.
