### ISSUE TITLE
Missing docs for TeleportSAMLConnector K8s Operator.

### ISSUE THREAD

**Issue by fprin** [gravitational/teleport#34023]
## Applies To

I will love to see below this some examples of how to create an `TeleportSAMLConnector`  https://goteleport.com/docs/management/dynamic-resources/teleport-operator/#step-23-manage-teleport-users-and-roles-using-kubectl you can add something like 

## Details

Could you add some kind of example of how the `TeleportSAMLConnector` looks like? At the moment there is example for `TeleportRole`.

## How will we know this is resolved?

There is an clear example of how `TeleportSAMLConnector` looks like.

## Related Issues

- https://github.com/gravitational/teleport/issues/32165

**Comment by franciscoprin** [comment]
Hey @zmb3 Is there any progress with this? Can you all point me to the source code where the TeleportSAMLConnector is defined?
