### ISSUE TITLE
User logging off Desktop via windows treated like error

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#34073]
Expected behavior:

A method to close the tab or instructions to after logging out of the user session.

Current behavior:

If a user logs out via Windows they receive this message that says error. There is no option to close the tab and this is often not a error.   As Teleport does not log off users itself it can be expected they would do the logging out.

<img width="732" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/46d9b0b4-f100-45d4-9e24-c635a439b42f">

Bug details:
- Teleport version: 14.1.1
- Recreation steps:
 1. Open a desktop session
 2. Log out within Windows

**Comment by zmb3** [comment]
Fixed in #33941
