### ISSUE TITLE
Revised table view for Unified Resources

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#34088]
Revise table view to hide labels by default, with a button to toggle to show/hide them

**Comment by roraback** [comment]
Designs here: https://www.figma.com/file/JKd0Bgs30AnNfNCLUuzzc2/Unified-Resources?type=design&node-id=2059%3A46377&mode=design&t=QXE80vdWWbvJJo8o-1

**Comment by zmb3** [comment]
@roraback my understanding is that this has been implemented by engineering and will be out in the next release. If this is correct, I assume we're not waiting on any more design work and can close this out.
