### ISSUE TITLE
Resource Access Requests in Plugins

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#34204]
Expected behavior:
When someone does resource access requests the name of the resource(s) being requested should be shown. 

Current behavior:
For Servers it appears were using the resource ID instead of the node name. 
![Screenshot 2023-11-03 at 10 48 16 AM](https://github.com/gravitational/teleport/assets/51385814/0f88d6a5-8234-4595-92ed-a512f07e2846)

Bug details:
- Teleport version: v14.1.1
- Recreation steps: submit a resource access request for servers that is tied into a plugin.
- Debug logs

**Comment by zmb3** [comment]
This is likely a permissions issue, not a missing feature.

Andrew just updated the docs in #33844 - let me know if that works for you.
