### ISSUE TITLE
Problem downloading files through sftp

### ISSUE THREAD

**Issue by jhhenriquee** [gravitational/teleport#34201]
Expected behavior:
Complete the download of the file

Current behavior:
The progress bar just stops and the download freezes, do not show any error messages.

Bug details:
- Teleport version v14.1.1 git:api/v14.1.1-0-gfb6429e go1.21.3
- Recreation steps
- Debug logs

Started right after I upgrade to 14 from 13

The download just freezes, and nothing is logged anyware.
Little files like 5mb works fine, but larger ones like 300mb or 2gb the progress bar on the download stops and do nothing more.
We tested in different browsers, with different users.
![image](https://github.com/gravitational/teleport/assets/71674873/eab2acb8-336a-4ebd-a6d9-ed593de99c65)

![image](https://github.com/gravitational/teleport/assets/71674873/5280cd8a-6248-413a-b903-133c7581f5a3)

Monitoring ps output the sftp process just disappears
![image](https://github.com/gravitational/teleport/assets/71674873/07392e1e-aa96-44db-9f04-e752d04957e1)

**Comment by TeleLos** [comment]
Additional observation testing with Cloud Teleport 14.1.3. When the upload is frozen. Try dropping another file to upload. The system will accept the file and continue with process and either pass or fail depending on file size. My cut off for success is 77MB File. Another condition to note, is that despite the terminal reporting "disconnected" I can still drop files and have them transferred to the VM.

**Comment by avatus** [comment]
Thank you @TeleLos , I'm working on this currently and it's great info!

**Comment by avatus** [comment]
This seems to have been fixed by https://github.com/gravitational/teleport/pull/34843. I was able to recreate locally 100% of the time and after applying this fix, I haven't been able to recreate at all. Once the next release goes out, please let me know if this continues.

**Comment by jhhenriquee** [comment]
Here still hapenning now in v14.2.0, same behavior.
If I download in a machine theres in the same network of the teleport server, the download is much faster and the % downloaded are much higher, but the time running looks the same. 
Seems to be some timeout threshold, indeed.

**Comment by avatus** [comment]
This didn't make it into 14.2.0, but will be in the next minor release (cut early next week I believe)
