### ISSUE TITLE
Server side label management against client side?

### ISSUE THREAD

**Issue by Bralva** [gravitational/teleport#34212]
What would you like Teleport to do?

We would like to have ability to control labels from server side against client!

What problem does this solve?

This feature could improve access management , because we have bindings with labels and roles to get access to specific resource(client/agent), but roles we only manage with server side but labels with client side!

And therefore access may break if someone changes the labels on the client.

If we have a feature to prevent labels from being changed after registration or a feature to manage labels from the server side, it would be better to achieve more security.

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Thanks for opening this. 

As far as managing labels server-side goes, you'll soon (see #34137) be able to do that by creating `ServerInfo` resources with `tctl`.

As far as the immutable labels request goes, that's already captured in #31964.

Given the above, I'm going to close this one out.
