### ISSUE TITLE
UI shows an additional SSH server when updating `nodename`

### ISSUE THREAD

**Issue by lbogdan** [gravitational/teleport#34236]
**Expected behavior:**

When updating `teleport.nodename` in `/etc/teleport.yaml` on a server and restarting the `teleport` service on an SSH server, the name is updated in the UI.

**Current behavior:**

The UI updates the name, but it also shows an additional SSH Server resource, with the same exact details. This happens every time you change `nodename` and restart `teleport`, so you can end up with multiple copies of the same server:

<img width="738" alt="image" src="https://github.com/gravitational/teleport/assets/2083930/b89d8e4c-4ad2-47a8-98ee-3c685f50e43e">

This only happens in the UI, the CLIs only show it once, as expected:

```sh
tctl nodes ls | grep bogdan
# bogdan   [redacted]...                hostname=bogdan   14.1.1
#
tsh ls | grep bogdan
# bogdan    ⟵ Tunnel       hostname=bogdan
```

**Bug details:**
- Teleport version: 14.1.1
- Recreation steps: see above
- Debug logs: N/A

**Comment by zmb3** [comment]
Thanks for the report. I can reproduce this.

I do not see duplicate nodes in the backend or via `tsh ls`. 

@avatus could this be an issue with the resource cache?

**Comment by lbogdan** [comment]
> could this be an issue with the resource cache?

The stale instances go away after a while, the same as when a server goes down (or `teleport` is stopped on it), it still shows in the UI for a while, so I'd guess it's some kind of cache.

 It's interesting that the CLIs don't have this "issue", though, I would have expected them to use the same API to list resources.

**Comment by lbogdan** [comment]
So this behavior is a side-effect of the change?

If so, considering that the state is eventually consistent, and if you think this is expected behavior, feel free to close.

Last, but not least, let me just say this is an incredible project, thanks a lot to you and the rest of the team for all the hard work!

**Comment by avatus** [comment]
Definitely an unintended side-effect to the update. I have a proposed fix that you can check out [here](https://github.com/gravitational/teleport/pull/34238) with some more details on what I believe is causing it. 

> Last, but not least, let me just say this is an incredible project, thanks a lot to you and the rest of the team for all the hard work!

Thanks!
