### ISSUE TITLE
Show date/time fields based on Time Zone of the user

### ISSUE THREAD

**Issue by amanmajeed** [gravitational/teleport#34243]
What would you like Teleport to do?
Show date/time fields based on the time zone of the user in Teleport console
E.g. Under Management - Session Recordings - Created (UTC) 
This is always under UTC TZ.

If the user timezone cannot be auto fetched, allow the user to configure it under their profile.

What problem does this solve?
All other applications report in my local time-zone. I need to corelate the time from other apps to UTC for Teleport, and then work on Teleport.

If a workaround exists, please include it.
None.

**Comment by zmb3** [comment]
Audit events and session recordings are deliberately displayed in UTC - see #17623 for more information.
