### ISSUE TITLE
`teleport-ent-updater` is not in armhf deb repository.

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#34259]
### Expected behavior:

```
curl -s 'https://apt.releases.teleport.dev/debian/dists/bookworm/stable/v14/binary-armhf/Packages' | grep ent-updater
Package: teleport-ent-updater
```

Current behavior:

```
curl -s 'https://apt.releases.teleport.dev/debian/dists/bookworm/stable/v14/binary-armhf/Packages' | grep ent-updater
```

It looks like the GitHub action that is supposed to publish this ends up publishing to `binary/arm/Packages` instead of `binary/armhf/Packages`

The binaries are built for `amd64`, `i386`, `arm` and `arm64`. The Debian architectures for these are: `amd64`, `i386`, `armhf`, and `arm64`, respectively. Only the `armhf` architecture is affected.

This means that when following the instructions to install `teleport-ent` and `teleport-ent-updater` on an armhf Debian variant, the `teleport-ent` package installs just fine, but the updater package is not found.

Bug details:
- Teleport version all through 14.1.1
- Recreation steps - If you don't have an armhf device handy, the easiest way to reproduce is on docker desktop with its built-in binfmt compatibility. Run `docker run --rm -it --platform linux/armhf debian bash` and then step through the install instructions.
- Debug logs - n/a

**Comment by bernardjkim** [comment]
The `teleport-ent-updater` should be available in the armhf repository starting `v16.0.0`.
