### ISSUE TITLE
Remove legacy AMIs from Teleport 15

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#34282]
From Q4 goals:

> Starting from Teleport 15 we should not build and publish legacy (non-hardened) AMIs.

**Comment by webvictim** [comment]
Completing this issue successfully will also require all Terraform documentation, Makefiles and READMEs to be updated to reference the methods of finding the new hardened images.

### Docs

https://github.com/gravitational/teleport/blob/master/docs/pages/deploy-a-cluster/deployments/aws-ha-autoscale-cluster-terraform.mdx

https://github.com/gravitational/teleport/blob/master/docs/pages/deploy-a-cluster/deployments/aws-starter-cluster-terraform.mdx

### Makefiles

https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/ha-autoscale-cluster/Makefile

https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/starter-cluster/Makefile

### READMEs

https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/ha-autoscale-cluster/README.md

https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/starter-cluster/README.md

**Comment by reedloden** [comment]
All remnants of the legacy AMIs that I could find have been removed from `master`. No more legacy AMIs for Teleport 15+!
