### ISSUE TITLE
Machine ID: UI for Bot creation

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#34300]
Allow the user to create a Bot through the UI, without need to fall back to `tctl`.

The first part of this task is determining if we want to approach this as we do for Roles - and give the user a plain default YAML spec for the resource to edit, or if we'd rather approach this as a discover wizard-esque flow.

Effectively dependent on https://github.com/gravitational/teleport/issues/31671 as creating a Bot will require that the user then creates a join token in order to use it.

Dependent on https://github.com/gravitational/teleport/issues/34260

_____

### Machine ID + GitHub Actions Bot creation task

- [x] Add bot resource to user ACL https://github.com/gravitational/teleport/pull/35774#event-11326229236
- [x] Add JSON endpoints https://github.com/gravitational/teleport/pull/36063
- [x] https://github.com/gravitational/teleport/pull/37412
- [x] https://github.com/gravitational/teleport/pull/37348
- [x] Add bot creation UI

Future work:

- [ ] Add posthog events to each UI flow step

backports:
- [ ] (v14) Add bot resource to user
- [ ] (v14) Add JSON endpoints
- [ ] (v14) Add bot creation UI

**Comment by strideynet** [comment]
I can see an argument for adding the ability to create/edit based on the YAML spec (as we do for roles) and then approaching the wizard flows as a separate build down the line.

**Comment by mcbattirola** [comment]
Closing as this has been merged and backproted to v15
