### ISSUE TITLE
Let `tctl` control Teleport Auth via the Proxy Server. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3431]
**What happened**:
While testing https://github.com/gravitational/teleport/issues/3018 I found that it only works for auth servers that are publicly accessible. I often run the auth server on a private subnet, as it doesn't have easy internet ingress. This proposal is the same as our IoT feature and would let admins access the auth server via the proxy server. 

**What you expected to happen**:

```
remote$ tctl auth sign \
                --auth-server=teleport-proxy.example.com:3080 \
                --identity=identity.pem \
                --user=alice \
                --out=alice.pem 
```

**Comment by russjones** [comment]
Best: 4
Worst: 8
