### ISSUE TITLE
When closing a web terminal tab, prompt a user with confirmation window

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#3434]
When a user attempts to close a tab with active SSH session, prompt a user with the confirmation message:

```
    window.confirm('Are you sure you want to terminate this session?')
```

![image](https://user-images.githubusercontent.com/7816406/76435195-101b8900-638d-11ea-881c-07f5a18de4d0.png)

**Comment by webvictim** [comment]
Presumably this will also hook Ctrl+W/Command+W (shortcut for "close tab" in most browsers)? It's the "delete last word" command in bash and I often hit it accidentally while trying to use the web terminal :(
