### ISSUE TITLE
We need to sign `teleport-ent-x.pkg`

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3437]
### Description
I was trying to update my local tsh and happened to pull the latest pkg from our dashboard.

**What happened**:
I saw the Untrusted message again.
![image](https://user-images.githubusercontent.com/559288/76471828-04da5480-63b1-11ea-8348-efd79b74f383.png)

**What you expected to happen**:
To sign using the same method as our OSS Software.

**Comment by webvictim** [comment]
TL;DR We can't - see https://github.com/gravitational/teleport/issues/3158

**Comment by webvictim** [comment]
To clarify the current situation:
- Full archives (containing `teleport`, `tsh` and `tctl`) for OSS or Enterprise cannot currently be signed due to the above issue
- Client-only packages (containing `tsh`) are signed. The `tsh` binary is the same for both OSS and Enterprise.

**Comment by benarent** [comment]
This makes sense, I mixed up the .pkg with the signed .pkg. 

I think this is due to it being 'below the fold'. I'll ask the ( houston )  team for the best way to address this. 

<img width="1435" alt="Image 2020-03-16 at 11 06 07 AM" src="https://user-images.githubusercontent.com/559288/76787949-3ec3a600-6777-11ea-84f7-e8d4c36964cd.png">

**Comment by webvictim** [comment]
Yeah, the list is sorted by filename currently which is the reason for that. We should add some group headers to the page, or make it a dual-column display instead.

**Comment by webvictim** [comment]
The download view looks better now as it's grouped by OS.

**Comment by benarent** [comment]
Note: this still isn't the case for Houston, but let's keep this open and keep tracking https://github.com/golang/go/issues/41191
