### ISSUE TITLE
User invite prevents token list

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#34387]
Expected behavior:

`tctl tokens ls` will work while users are being invited.

Current behavior:

Until a user invitation is completed `tctl tokens ls` will return 

```
ERROR: role Password is not registered
```

Also impacting `tctl get tokens`

Bug details:
- Teleport version: 14.1.1
- Recreation steps

1. Confirm `tctl tokens ls` works with a cluster
2. Create a user invite. `tctl users add --roles=access userxyz`
3. Before registering the user with their password attempt to list the tokens
`tctl tokens ls`

**Comment by sergefedorow** [comment]
The attempt to "Reset Authentication..." of user from web interface gives me the same results.

**Comment by djohns7** [comment]
A prospect ran into this as a bug and it is preventing them from setting up Machine ID following the Teleport guide, as they've created a bot token which hasn't yet been used.
