### ISSUE TITLE
Audit log entries for AD desktops should use desktop name

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#34392]
Expected behavior:

The names of the computer are shown in the audit log listing.

Current behavior:

The address is used which is often a IP address.

![image](https://github.com/gravitational/teleport/assets/60704961/d6a46ba9-85dc-4f66-b432-1fc6afbfc9d3)

The desktop dns host name would be better to show.

```json
  "desktop_labels": {
    "teleport.dev/computer_name": "EC2AMAZ-GJR38AU",
    "teleport.dev/dns_host_name": "EC2AMAZ-GJR38AU.teleport.example.com",
    "teleport.dev/is_domain_controller": "true",
    "teleport.dev/origin": "dynamic",
    "teleport.dev/os": "Windows Server 2022 Datacenter",
    "teleport.dev/os_version": "10.0 (20348)",
    "teleport.dev/ou": "OU=Domain Controllers,DC=teleport,DC=example,DC=com",
    "teleport.dev/windows_domain": "teleport.example.com"
  },
  "desktop_name": "EC2AMAZ-GJR38AU-teleport-example-com",
```

Bug details:
- Teleport version: 14.1.1
- Recreation steps

Connect to a AD machine via desktop services
Review log. The address is used, not the dns host name or desktop name

**Comment by zmb3** [comment]
`teleport.dev/dns_host_name` only exists if the LDAP-based discovery was used.

Maybe we should just use `desktop_name`.
