### ISSUE TITLE
Machine ID: Document Spacelift join

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#34391]
## Details

Add a page explaining how to use Machine ID with Spacelift and the Teleport Terraform Provider

Depends on https://github.com/gravitational/teleport/issues/34389
Depends on https://github.com/gravitational/teleport/issues/34390

## How will we know this is resolved?

Try deploying a simple resource using Teleport's Terraform Provider in Spacelift and using the `spacelift` join method.

**Comment by zmb3** [comment]
Note that @ptgott recently published a new guide on using Spacelift with Teleport: https://goteleport.com/docs/ver/15.x/management/dynamic-resources/spacelift/

Let's ensure this gets a re-review and any necessary updates when proper Spacelift joining support lands.
