### ISSUE TITLE
New browsers SameSite cookie attribute default behavior breaks SAML

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#3440]
Browser vendors started changing the default behavior for the SameSite cookie attribute. This is to enable default CSRF protection for the websites. Since Teleport uses it's own CSRF protection mechanism during SAML sign-up flow by setting `grv_csrf` cookie, this new browser behavior breaks it.

More info here:
https://www.chromestatus.com/feature/5088147346030592

We need to explicitly set `sameSite=none` for the `grv_csrf` cookie to opt-in from this default behavior.

**Comment by alex-kovoy** [comment]
@russjones we need to packport it to other versions as well.

**Comment by benarent** [comment]
+1 - Thanks for the quick turn around on this @alex-kovoy
