### ISSUE TITLE
Operator fails to interact with Teleport if it joined while no proxy was here

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#34423]
### Expected behavior:

I run `helm install`, it starts both Teleport auth and proxy pod. The operator's embedded tbot can consistently join the cluster.

### Current behavior:

If tbot joins before the proxy has joined (e.g. proxy takes some time to start, e.g. it is waiting for its LE certs), it will see a cluster without proxies. When attempting to render its identity destination, generation fails because the identity destination tries to parse the proxy address (which is empty).

The operator stays in a shadow failure state, not able to reconcile anyting but reporting as ready for 30 minutes or until manual restart.

### Bug details:
- Teleport version: v14.1 and v15.0.0-dev
- Recreation steps:
  - Start a fresh auth server on a fresh backend
  - have a slow proxy startup
  - start the operator
  - the operator runs but cannot reconcile anything

- Debug logs
```
2023-11-09T20:06:18Z INFO             Generating output. output:identity (memory) tbot/impersonated_identity.go:548
2023-11-09T20:06:18Z WARN             Failed to render output identity (memory) error:[
ERROR REPORT:
Original Error: *trace.BadParameterError proxy  has no usable public address: missing port in address
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/tbot/config/template_ssh_client.go:105 github.com/gravitational/teleport/lib/tbot/config.(*templateSSHClient).render
	/go/src/github.com/gravitational/teleport/lib/tbot/config/output_identity.go:77 github.com/gravitational/teleport/lib/tbot/config.(*IdentityOutput).Render
	/go/src/github.com/gravitational/teleport/lib/tbot/impersonated_identity.go:586 github.com/gravitational/teleport/lib/tbot.(*Bot).renewOutputs
	/go/src/github.com/gravitational/teleport/lib/tbot/impersonated_identity.go:70 github.com/gravitational/teleport/lib/tbot.(*Bot).renewOutputsLoop
	/go/src/github.com/gravitational/teleport/lib/tbot/tbot.go:153 github.com/gravitational/teleport/lib/tbot.(*Bot).Run.func4
	/go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1
	/opt/go/src/runtime/asm_amd64.s:1650 runtime.goexit
User Message: rendering template ssh_client
	proxy  has no usable public address: missing port in address] tbot/impersonated_identity.go:587
```

**Comment by strideynet** [comment]
Closed by 34442 and Hugo's work to integrate this.
