### ISSUE TITLE
access denied in web UI when using SAML

### ISSUE THREAD

**Issue by JonGilmore** [gravitational/teleport#3445]
### Description
After we upgraded to 4.2.3-beta1, SAML auth (using Okta) was working just fine. After some time, we're seeing the following error: {"message": "access denied"}
This can be worked around by using private browsing, but this isn't a great workflow. 

**What happened**:
Upgrade to 4.2.3-beta1

**What you expected to happen**:
usable web UI

**How to reproduce it (as minimally and precisely as possible)**:
see description

### Environment
- Teleport version (use `teleport version`): 4.2.3-beta1
- Tsh version (use `tsh version`): 4.2.2
- OS (e.g. from `/etc/os-release`): 

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
AWS

**Browser environment**
chrome

- Browser Version (for UI-related issues): Version 80.0.3987.132 (Official Build) (64-bit)
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by JonGilmore** [comment]
cc @dmart

**Comment by webvictim** [comment]
This is likely due to https://github.com/gravitational/teleport/issues/3440

We are working on a fix.

**Comment by JonGilmore** [comment]
> This is likely due to #3440
> We are working on a fix.

from what I understand, [4.2.5-beta1](https://github.com/gravitational/teleport/releases/tag/v4.2.5-beta.2) fixes this. is this not true?

**Comment by webvictim** [comment]
Yes, it looks like the fix is included in 4.2.5-beta.2.
