### ISSUE TITLE
Auto-discovery install script doesn't work on AL2023

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#34538]
## Expected behavior:

EC2 auto-discovery can successfully enroll instances running Amazon Linux 2023.

## Current behavior:

AL2023 instances fail to enroll because the SSM install script runs `yum-config-manager` command which is not recognized:

```
 "documentStatus": "InProgress",
  "documentTraceOutput": "",
  "runtimeStatus": {
    "runShellScript": {
      "status": "Failed",
      "code": 1,
      "name": "aws:runShellScript",
      "output": "\n----------ERROR-------\nsudo: yum-config-manager: command not found\nfailed to run commands: exit status 1",
      "startDateTime": "2023-11-09T08:18:49.275Z",
      "endDateTime": "2023-11-09T08:18:49.342Z",
      "outputS3BucketName": "",
      "outputS3KeyPrefix": "",
      "stepName": "",
      "standardOutput": "",
      "standardError": "sudo: yum-config-manager: command not found\nfailed to run commands: exit status 1"
    }
  }
}
```

Changing the command to `yum config-manager` (note "config-manager" here is a subcommand of yum) fixed the issue for the customer.

Let's:

- [ ] Reproduce this.
- [ ] Fix the install script to support AL2023.
- [ ] Check other install scripts as well for the same issue.
- [ ] Check the installation commands in the documentation for the same issue.

**Comment by zmb3** [comment]
See also #31180
