### ISSUE TITLE
Race condition in Jira plugin

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#34581]
Reported by a customer:

Hey folks, we’re experiencing an issue with the Jira Access plugin where the webhook payload it receives says the ticket is in the Approved status, but when it asks the Jira API, it says the ticket is still in Pending.

We believe this is a race condition inside of Jira where it hasn’t synchronized its internal state between nodes. This results in the API call getting outdated information for a short while.

This would stem from this code - https://github.com/gravitational/teleport/blob/v14.0.0/integrations/access/jira/app.go#L330-L342

This issue is not consistent and sometimes processes webhooks as expected.

Perhaps a retry when the status doesn’t match between the payload and API would help here?

## Expected behavior

Jira plugin should successfully be able to process and handle Teleport access requests.

## Current behavior

Jira plugin does not work as expected.

## Bug details
- Teleport version: 14.1.1

**Comment by zmb3** [comment]
@EdwardDowling are we good to close this?

**Comment by webvictim** [comment]
Hey - unfortunately the customer has reported that this didn't fix the issue. Debug logs attached:

```
DEBU   Processing incoming webhook event "jira:issue_updated" with type "issue_generic" jira_http_id:1721244908-3 jira_issue_id:4090132 jira/app.go:301
DEBU   Will retry in 0s: mismatch of webhook payload and issue API response: "approved" and "pending". retryutils/retry.go:191
DEBU   Will retry in 5s: mismatch of webhook payload and issue API response: "approved" and "pending". retryutils/retry.go:191
WARN   Using most recent successful getIssue response: context deadline exceeded jira_http_id:1721244908-3 jira_issue_id:4090132 jira/app.go:332
DEBU   Issue has pending status, ignoring it jira_http_id:1721244908-3 jira_issue_id:4090132 jira_issue_key:VCPFBR-768 jira/app.go:342
```

**Comment by hugoShaka** [comment]
The logs indicate that the first retry happens after 5 seconds, and the Jira HTTP client calling the webhook bails out before. This causes the webhook context to get cancelled.

There are two ways to fix this:
- decrease the retry step
- create a new context, unrelated to the HTTP call context with a longer deadline (the dealine should be the max retry deadline)

**Comment by EdwardDowling** [comment]
Fix and backport are merged and have confirmation [here](https://github.com/gravitational/customer-sensitive-requests/issues/304#issuecomment-2303186251) the fix works.
