### ISSUE TITLE
Use a different env var to enable loading webassets from disk

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3460]
**What happened**: If the `DEBUG` environment variable is set and evaluates to `true` where Teleport is running, Teleport tries to load its web assets from a local directory on disk rather than using the embedded archive version. If `proxy_service` is set to `true`, this results in Teleport failing to start. 

**What you expected to happen**: `DEBUG` is a pretty widely used term/environment variable, so it's quite likely that it might be set somewhere that Teleport is running. I'm actually amazed we've never run into this before.

We should change this variable to `TELEPORT_DEBUG` or something else. It looks like `TELEPORT_DEBUG` is actually already used in the code for verbose logging, so maybe we should use something else which won't overload its use.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
export DEBUG=true
teleport start
```

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.2.6git:v4.2.6-0-gce1cbbf8 go1.13.2`

**Comment by zmb3** [comment]
This is unfortunately by design, but I agree it would be best to use something like `TELEPORT_DEBUG` or `TELEPORT_DEBUG_WEBASSETS` to enable this behavior.

**Comment by webvictim** [comment]
Whatever variable you end up using, please ensure it starts with `TELEPORT` for namespacing :)

**Comment by hatched** [comment]
`DEBUG` and `DEBUG_ASSETS_PATH` are being removed now that the UI is in the same repository as teleport.
