### ISSUE TITLE
Access request page in UI is slow when there are a large number of access requests

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#34628]
As the number of access requests increases so does the load time for the access request page in the web ui. This is a result of a few things

1) There is no paginated api for access requests. When the page is loaded it pulls **all** access requests from the backend
2) All resources defined in all access requests are retrieved from the appropriate clusters Auth instance so that the "friendly" name can be displayed instead of the host UUID.

A short term solution might be to parallelize the resource friendly name resolution. The long term solution is to add a `ListAccessRequest` API and convert the web UI to only request a page of requests at a time. Note, it could still be worthwhile to parallelize friendly name resolution even with the paginated approach.

**Comment by nklaassen** [comment]
Oh `getResourceDetails` per request is going to be super slow, I didn't know we were using it on the `list` endpoint now, it was only designed to be used on the details page for an individual access request.

You should be able to get away with a single ListResources request per cluster, instead of per request

**Comment by bernardjkim** [comment]
@fspmarshall Thanks for the quick patch!

https://github.com/gravitational/teleport.e/pull/2670 has reduced the load time of the Access Request page for the customer from ~3min to ~25sec. They'd still like a proper fix though, and get the load time much lower.

**Comment by zmb3** [comment]
This was resolved with the new access requests page in 15.2.0.
