### ISSUE TITLE
Documentation how to list users using app 2fa

### ISSUE THREAD

**Issue by skirmantaskr** [gravitational/teleport#34655]
## Applies To

Probably https://goteleport.com/docs/reference/cli/tctl/

## Details

It would be good to know how to list users which are using not webauth, but application second factor and enforce them to use webauth.

## How will we know this is resolved?

There is clear documentation how to list users by second factor they are using

## Related Issues

https://github.com/gravitational/teleport/issues/20725

**Comment by zmb3** [comment]
cc @smallinsky - perhaps a good fit for security reports

**Comment by skirmantaskr** [comment]
Maybe you already have preliminary eta when you will implement ability to search who is using not hardware key as teleport 2fa, but auth app?

**Comment by zmb3** [comment]
@skirmantaskr for now the best option for you would be to foward your audit logs to a SIEM, where you can then query for `user.login` events without an `mfa_device` set.

In the future we will consider adding a custom security report that displays this information. Security reports are an enterprise-only feature.
