### ISSUE TITLE
Access Monitoring - Add PostHog metrics

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#34701]
### What

Add Business PostHog metrics for Access Monitoring product: 
- Security report opened/refreshed
- A custom user query executed.

**Comment by zmb3** [comment]
@smallinsky are we good to close this? Looks like we have cloud updates in gravitational/cloud#6794 and Teleport updates in #34982

**Comment by smallinsky** [comment]
Yes, This is already implemented. Thanks
