### ISSUE TITLE
Best Practices for Long Lived SSH tokens

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3470]
## Summary
We don't let customers follow the best practices when setting up Teleport. We https://gravitational.com/teleport/docs/user-manual/ recommend creating a long lived cert but we should provide with alternative of rotating certificates every day and publishing them to encrypted secret storage. Using Amazons SSM or Vault. 

### Audience
This is mostly for power users of Teleport. 

### Location
This is currently in the user guide, but It'll be better placed in the Admin Guide.

**Comment by kontsevoy** [comment]
How is this better from storing `certificate.pem` in Vault?

**Comment by zmb3** [comment]
Closing this as deprecated by Machine ID, which basically does exactly what Ben suggests - periodically rotating your certificate and publishing it to some external storage.
