### ISSUE TITLE
Refactor localStorage.ts to use named export and avoid shadowing `window.localStorage`

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#34718]
`localStorage.ts` is typically imported as `import localStorage from './services/localStorage';`. If you remove this import by mistake (see #34713), TypeScript won't catch the breaking change: the name `localStorage` shadows `window.localStorage` which is typed as `Storage`, which has `[name: string]: any;` which means you can pretty much call any method on it and TypeScript won't complain.

`localStorage.ts` should export a named export called `LocalStorage` so that mistakes like these are not possible.

**Comment by jakule** [comment]
@ravicious Thanks for creating this.
