### ISSUE TITLE
teleport-kube-agent Host header changed

### ISSUE THREAD

**Issue by tearfulDalvik** [gravitational/teleport#34747]
Expected behavior:
Keep the original Host and Origin header

Current behavior:
Enable debug in app_server, and visit dumper, it shows:
```
    Host: 127.0.0.1:13639
```
The Host header is not right. It should keep 'dumper.example.com' as the client requeted.
This will cause many application to drop websocket connection because the origin check will fail, for example, https://github.com/rancher/rancher/issues/36158

Bug details:
- Teleport version
tctl version
Teleport v14.1.5 git:api/v14.1.5-0-gf1ce28f6f6 go1.21.4
- Recreation steps
Enable debug in app_server, and visit dumper
- Debug logs

**Comment by tearfulDalvik** [comment]
I noticed that there's a X-Forwarded-Host header, but it is not standard, and the origin header is indeed modified.
If this is intentional for specific purposes, I would like to suggest the implementation of a switch feature in the teleport.yaml

**Comment by strideynet** [comment]
Teleport attaches `X-Forwarded-Host` with the original hostname. This is a fairly standard thing for a Proxy to do, and applications should aim to support this header. It's unlikely we'll change this behaviour as this would be a breaking change for those already expecting Teleport to change the `Host` header.

If an application does not support `X-Forwarded-Host`, it's possible to override the `Host` header to be the value they expect using the rewrite config:

```
- name: "dashboard"
  uri: https://localhost:4321
  public_addr: dashboard.example.com
  rewrite:
    headers:
    - "Host: dashboard.example.com"
```

**Comment by tearfulDalvik** [comment]
It works, thank you.
As `X-Forwarded-Host` has been marked non-standard in [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host), maybe we can add a switch in the teleport.yaml

**Comment by strideynet** [comment]
I'll close this as solved for now - as mentioned previously, we're now in a position whereby operators expect Teleport to behave this way and it would be challenging for us to change this behaviour without breaking a number of existing setups.
