### ISSUE TITLE
Option to set configure stopped Nodes TTL ( currently 15 minutes )

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3479]
### Feature Request
Nodes can currently linger in the UI and Web UI, this feature was well described here https://github.com/gravitational/teleport/issues/1118, and it looks like some parts were fixed. 
 

### Motivation
The motivation is for teams that autoscale a lot of nodes and need to Teleport quickly and when an operator tries to access it they get kicked out an error message. We currently set Node Linger TTL to 15min, we should provide customisation for customers. 

### Code changes
When a node skips 3 pings (or whatever is the current default) it needs to go into the "offline state".
Introduce "node linger TTL". It's a maximum time a node can spend in "offline state" before being automatically removed from the cluster.
UX changes

- tsh ls should not display offline nodes by default.
- tsh ls --all should display both offline and offline nodes. Careful here: the CLI parsing library we use does not allow this syntax by default, i.e. --all should be an argument and a flag.
Web UI should not show offline nodes by default.
- No need for tctl node delete. I am very much against this command. Its default meaning is to kick a healthy node out (something we don't support).

Maybe to make UI/UX changes minimal our implementation of auth_api.GetNodes() should take an argument defaulting to "online only"? This way only minimal code changes will be required and they will be caught by the compiler.

### Lingering TTL
Lets not expose it to Teleport users in any form (we have plenty of other TTLs that need documenting / configuration, maybe we'll do them all at once in the future).

The default should be set to 15min.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by benarent** [comment]
@stevenGravy @kimlisa FYI - Created this issue based on your requirements yesterday.

**Comment by jon-can** [comment]
+1 as a nice to have.

**Comment by robertapas** [comment]
Has this been abandoned? 
It would be a very much needed feature for dynamic clusters (especially when accessed using labels).

**Comment by zmb3** [comment]
This is not planned at the moment.

Node TTLs are no longer hard coded to 15 minutes, they heartbeat at a variable rate depending on the size of the cluster.
