### ISSUE TITLE
Windows tsh binary doubled in size

### ISSUE THREAD

**Issue by fheinecke** [gravitational/teleport#34812]
The Windows tsh binary doubled in size when the build process for it moved from Linux to Windows.

Related PRs/commits:
* https://github.com/gravitational/teleport/pull/34273 - PR that introduced the change
* https://github.com/gravitational/teleport/tree/1811d437855a4048438760245847291a98a1e3bc - this is the last commit that did not have this problem

The biggest difference is that the tsh build process moved from Linux cross-compiling for Windows, to natively building on Windows.

**Comment by zmb3** [comment]
![image](https://github.com/gravitational/teleport/assets/7527103/38bece6c-949d-41fb-9ec8-437d36f94e57)

Looks like there's 176MB of debug info in the tsh binary. Are we missing `-w -s`?
