### ISSUE TITLE
v14 `installer/default-installer` fails on v13 nodes due to `--azure-client-id` flag

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#34860]
## Expected behavior
v14 default installer script is backwards compatible with v13 nodes (as the `stable/cloud` repo is still serving 13.4.3 while most Cloud instances are now running 14.1.3)

## Current behavior
v13 nodes using the auto-join scripts against a v14 cluster fail to join correctly:

```
[ec2-user@ip-172-31-34-128 ~]$ teleport node configure --proxy=test.teleport.sh:443 --join-method=token --azure-client-id=client --token=blah --output=file --labels="os:linux"
teleport: error: unknown long flag '--azure-client-id'
```

v13 default installer: https://github.com/gravitational/teleport/blob/branch/v13/api/types/installers/installer.sh.tmpl#L109-L114

v14 default installer: https://github.com/gravitational/teleport/blob/branch/v14/api/types/installers/installer.sh.tmpl#L110-L116

A Cloud prospect ran into this today and we lost some face.

Bug details:
- Teleport version: 13.4.3

**Comment by stevenGravy** [comment]
A workaround is that you can edit the default installer to remove the offending flag.  See the instructions here https://goteleport.com/docs/server-access/guides/ec2-discovery/#step-67-optional-customize-the-default-installer-script
