### ISSUE TITLE
Enhancement of http-connect-proxies documentation using already defined EnvironmentFile

### ISSUE THREAD

**Issue by jryberg** [gravitational/teleport#34888]
## Applies To

https://goteleport.com/docs/reference/networking/#http-connect-proxies

## Details

I think we should change this section and include something about EnvironmentFile that are used by systemd in later Teleport installations.

This is how it looks like today

> To use HTTP CONNECT tunneling, set the HTTPS_PROXY and HTTP_PROXY environment variables when running Teleport. You can also optionally set the NO_PROXY environment variable to avoid use of the proxy when accessing specified hosts/netmasks/ports.
> 
> For example, when launching Teleport with systemd, you can add the following lines to your systemd unit file, replacing proxy.example.com with the address of your proxy.
```
[Service]
Environment="HTTP_PROXY=http://proxy.example.com:8080/"
Environment="HTTPS_PROXY=http://proxy.example.com:8080/"
Environment="NO_PROXY=localhost,127.0.0.1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
```

The [Service] section does in fact look like this
```
[Service]
Type=simple
Restart=on-failure
EnvironmentFile=-/etc/default/teleport
ExecStart=/usr/local/bin/teleport start --config /etc/teleport.yaml --pid-file=/run/teleport.pid
ExecReload=/bin/kill -HUP $MAINPID
PIDFile=/run/teleport.pid
LimitNOFILE=524288
```

The user can create a new file "/etc/default/teleport" and put proxy envs in the file without modifying teleport.service with content like this:
```
HTTP_PROXY=http://proxy.example.com:8080/
HTTPS_PROXY=http://proxy.example.com:8080/
NO_PROXY=localhost,127.0.0.1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
```

**Comment by ptgott** [comment]
Thanks for pointing this out! I have opened a PR: https://github.com/gravitational/teleport/pull/35209
