### ISSUE TITLE
Other key types for Teleport clients

### ISSUE THREAD

**Issue by dsseng** [gravitational/teleport#3489]
### Feature Request
As I've seen now by using Teleport and in the code, it doesn't support other key types than RSA. I think Ed25519 should be supported, since it's a more modern, fast and secure type of signing algorithm.

### Motivation
New algorithms for SSH auth are supported by OpenSSH and Dropbear, why not to support them in Teleport?

### Who's it for?
OSS User, Pro, Enterprise

**Comment by awly** [comment]
@lsascha OpenSSH complains about the signing algorithm (SHA1 vs SHA2) there, which is slightly different.
Teleport 4.3 adds support for SHA2-based RSA signing algorithms to fix this, see Upgrade Notes in https://github.com/gravitational/teleport/releases/tag/v4.3.0

But yes, configurable key types would be nice-to-have. We just need time and people to do the work.
There are some technical wrinkles to iron out (e.g. FIPS requirements), but it's totally doable.

**Comment by strideynet** [comment]
Closing in favour of https://github.com/gravitational/teleport/issues/28392
