### ISSUE TITLE
Improving Teleport Helm Chart 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3499]
### Feature Request
We currently offer Helm charts, as part of Teleport repo, but this isn’t easily consumable by our customers.  https://github.com/gravitational/teleport/tree/master/examples/chart/teleport 

Issues:
- We currently have Helm 2.0 
- Customers can’t easily pull in these charts. Publishing to Helm Hub would be good.
- Currently a range of Teleport Charts ( but most are out of date ) 
https://hub.helm.sh/charts?q=teleport
- We only publish an Enterprise chart, we should also ship a OSS version that doesn’t require a license etc..
-  Where do we want to publish the binary? 
We could then publish to https://get.gravitational.com/charts/teleport-4.2.6-1.tgz

Extra docs here https://docs.google.com/document/d/1KrLVIUchwGbZ2T3i_brhsu1fGrPiff2yUd6xB_fwU84/edit  

### Motivation
Feedback from a customer. 

### Who's it for?
OSS User, Pro, Enterprise

**Comment by drewwells** [comment]
Also, this chart appears to have more functionality than the one you linked: https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-demo

I'd love to see an official teleport chart. We have had to manage one internally and it does not work well. 

Some functionality we have had to solve on our own:

- daemonset SSH service
- auto provisioning of oauth connector ie. github
- kubectl access, I guess the binary we are using does not automatically read the in-cluster kubeconfig

**Comment by drewwells** [comment]
Helm repos can be served from github directly: https://helm.sh/docs/topics/chart_repository/#github-pages-example

**Comment by benarent** [comment]
Thanks for the comments  @drewwells we are currently working on improving our K8s experience, Would you be open to a 30min call to chat more about how you're currently using Teleport. If so, can you drop me an email at ben@gravitational.com

**Comment by benarent** [comment]
Closing this issue as a range of tasks have been completed. The last step would be add Helm 2.0 support but we have this tracked in #3656
