### ISSUE TITLE
Generate teleport.yaml on install

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3500]
### Feature Request
When teleport is installed it would be helpful if a basic working teleport.yaml could be generated and placed into the correct location.

### Motivation
Make getting started quicker and easier.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by webvictim** [comment]
`teleport configure > teleport.yaml`

**Comment by jon-can** [comment]
It would be nice if it was auto generated and placed in the correct spot. Even though the documentation does specify where to put it I've still seen a few people get tripped up on where to place it and what information to actually include in it.

**Comment by zmb3** [comment]
Tagged with `time-to-value` so we can discuss whether or not this is the right approach.

**Comment by stevenGravy** [comment]
Given the configure and discovery options we have not seen this come up, closing.
