### ISSUE TITLE
Remove unused React imports

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#35039]
After switching to automatic runtime in `@babel/preset-react` (https://github.com/gravitational/teleport/pull/35037), importing React into scope is no longer necessary for jsx/tsx files.

There's [a codemod that can remove unused React imports](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports). We should also adjust the ESLint rule for unused imports to prevent adding unnecessary imports in the future.

**Comment by siddhakdak** [comment]
I am on it
