### ISSUE TITLE
How-to guide for using the Teleport gRPC API with non-Go clients

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#35089]
## Applies To

Either a new guide in `docs/pages/api` or a section in `docs/pages/api/introduction.mdx`.

## Details

Let's accommodate Teleport users who want to build a Teleport API client in a language besides Go. While it's (at least theoretically) possible to compile our .proto files into a non-Go gRPC client, our API reference documentation and how-to guides cater to Go users. 

We can write a guide that explains:
- If there are any special workflow steps for building a non-Go gRPC client for the Teleport API.
- If there are any issues that users need to be aware of before converting Go-based instructions to non-Go ones.

If these instructions are pretty straightforward, we could add a short section to the API introduction page (`docs/pages/api/introduction.mdx`) instead of a full guide.

## How will we know this is resolved?

There is a new guide/section as elaborated above.

**Comment by zmb3** [comment]
Personally, I don't think we have the capacity to support this right now.
