### ISSUE TITLE
Teleport fails to use EKS ServiceAccount IAM role

### ISSUE THREAD

**Issue by Nuru** [gravitational/teleport#3510]
### Description
I deployed Teleport into an Amazon EKS cluster in high-availability mode (using DynamoDB and S3) based on your [example Terraform](https://github.com/gravitational/teleport/tree/v4.2.8/examples/aws/terraform) and [chart](https://github.com/gravitational/teleport/tree/v4.2.8/examples/chart/teleport), modified to work in EKS. I assigned the Teleport auth IAM role to the Teleport Kubernetes ServiceAccount.

**What happened**:

Teleport auth service failed to start because it could not access the DynamoDB table

**What you expected to happen**:

Teleport pod would provide auth and proxy services

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`): 4.2.8
- Tsh version (use `tsh version`): NA
- OS (e.g. from `/etc/os-release`): NA

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS EKS

**Relevant Debug Logs If Applicable**

```
Original Error: *awserr.requestError AccessDeniedException: User: arn:aws:sts::<redacted>:assumed-role/example-eks-us-east-2c-workers/i-0f85ef29911b013a3 is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:us-east-2:<redacted>:table/example-teleport
        status code: 400, request id: <redacted>
Stack Trace:
        /gopath/src/github.com/gravitational/teleport/lib/backend/dynamo/dynamodbbk.go:575 github.com/gravitational/teleport/lib/backend/dynamo.(*DynamoDBBackend).getTableStatus
        /gopath/src/github.com/gravitational/teleport/lib/backend/dynamo/dynamodbbk.go:236 github.com/gravitational/teleport/lib/backend/dynamo.New
        /gopath/src/github.com/gravitational/teleport/lib/service/service.go:2331 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthStorage
        /gopath/src/github.com/gravitational/teleport/lib/service/service.go:906 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService
        /gopath/src/github.com/gravitational/teleport/lib/service/service.go:648 github.com/gravitational/teleport/lib/service.NewTeleport
        /gopath/src/github.com/gravitational/teleport/e/lib/pro/process.go:41 github.com/gravitational/teleport/e/lib/pro.NewTeleport
        /gopath/src/github.com/gravitational/teleport/e/tool/teleport/main.go:35 main.run.func1
        /gopath/src/github.com/gravitational/teleport/lib/service/service.go:401 github.com/gravitational/teleport/lib/service.Run
        /gopath/src/github.com/gravitational/teleport/e/tool/teleport/main.go:43 main.run
        /gopath/src/github.com/gravitational/teleport/e/tool/teleport/main.go:27 main.main
        /opt/go/src/runtime/proc.go:212 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1358 runtime.goexit
User Message: initialization failed

```

**Comment by osterman** [comment]
We suspect it might be due to an old AWS SDK. The service account stuff is pretty new, but is the defacto way for doing IAM with EKS (e.g. not `kiam` or `kube2iam`). Simply upgrading the AWS Go SDK might be enough to fix this.

**Comment by robcoward** [comment]
This has been fixed in #3330 and has been merged to master, but I'm still waiting for it to be added to the 4.2 branch and released, or for someone to provide a roadmap on when 4.3 might be cut from master to include the update.

**Comment by Nuru** [comment]
@osterman Actually, the current 4.2.8 release is using [1.12.17](https://github.com/gravitational/teleport/blob/a9015b336c1f5c202f991a07165f8923f546da11/Gopkg.toml#L72). Anyway, @robcoward  see also [this comment](https://github.com/aws/aws-sdk-go/issues/3101#issuecomment-585983699) where the problem is reproduced in 1.28.11. [This comment](https://github.com/aws/aws-sdk-go/issues/3101#issuecomment-600317329) notes it is fixed by 1.29.26.

**Comment by benarent** [comment]
@russjones This is the issue, we should consider bumping to `1.29.26` for 4.3

**Comment by awly** [comment]
Prematurely closed, we should actually verify the fix.

**Comment by benarent** [comment]
I tested this, and didn't have any issues. Please keep an eye on 4.3 release early next week.
