### ISSUE TITLE
Expand Database Access E2E tests

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#35153]
Related
- https://github.com/gravitational/teleport/issues/27325

#27325 has implemented automated E2E for RDS MySQL/PostgreSQL.

Potential things to add
- Database types
  - Redshift
  - RDS Proxy
  - ElastiCache
  - ...
- Features
  - Auto-user provisioning
    - keep mode vs drop mode 
    - Permission management

**Comment by GavinFrazar** [comment]
Do we want to add self-hosted databases as well? or just focusing on AWS for now?

**Comment by GavinFrazar** [comment]
closing this because we expanded e2e tests as planned and I don't want this to stay an open-ended issue indefinitely
