### ISSUE TITLE
S3 audit event paging gets stuck on single large event

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#35161]
Expected behavior:
All clients including the event-handler plugin should be able to page through all events without getting stuck.

Current behavior:
If a single event greater than 1MB is stored in the audit log, all clients paging through the events will get "stuck" when they reach that event.

A previous call to the paginated endpoint will return a `LastKey` pointing immediately before the large event. Using that as the `StartKey` for subsequent calls will return a page with 0 events and an empty `LastKey`, making it appear that the client has reached the end of the event stream.

This affects the Athena/S3 audit backend and not the Dynamo or File backends, which already truncate large events before writing them to the backend. The S3 backend does not truncate events and fails when the large events are queried.

Bug details:
- Teleport version: All with Athena/S3 audit backend (including Cloud)
- Recreation steps: Create very large event (large DB query) with running event-handler plugin, it will get stuck and stop exporting events
- Debug logs
```
INFO   Using initial cursor value cursor:sB2LWc4KBgBW8C3jzVBM440bLile9j4k event-handler/app.go:191
INFO   Using initial ID value id:1c4fdf95-6c30-4f63-b069-b76c519a46c3 event-handler/app.go:192
INFO   Using start time from state value:2023-08-31 16:51:53 +0000 UTC event-handler/app.go:193
DEBU   Fetched page cursor:sB2LWc4KBgBW8C3jzVBM440bLile9j4k len:14 next:oGpIWs4KBgAcT9-VbDBPY7Bpt2xRmkbD event-handler/teleport_events_watcher.go:186
DEBU   Skipping last known event id:1c4fdf95-6c30-4f63-b069-b76c519a46c3 new_pos:14 event-handler/teleport_events_watcher.go:218
DEBU   Fetched page cursor:oGpIWs4KBgAcT9-VbDBPY7Bpt2xRmkbD len:0 next: event-handler/teleport_events_watcher.go:186
DEBU   No new events, pause for 10s seconds event-handler/teleport_events_watcher.go:240
DEBU   Fetched page cursor:oGpIWs4KBgAcT9-VbDBPY7Bpt2xRmkbD len:0 next: event-handler/teleport_events_watcher.go:186
DEBU   No new events, pause for 10s seconds event-handler/teleport_events_watcher.go:240
```

**Comment by jentfoo** [comment]
I believe this should be considered a security issue.  Luckily it is a client side issue in that these events are still captured by the backend.  But this technique could be used to make it difficult to retrieve the audit events.  Since events are captured, severity is fairly low / medium, CVSS 4.3
