### ISSUE TITLE
Nix build

### ISSUE THREAD

**Issue by ari-becker** [gravitational/teleport#3518]
### Feature Request
Write Nix packaging for the Teleport build and consider adding it to Nixpkgs.

### Motivation
Part of the Nix ecosystem includes a tool called `nix-shell`, which allows for the following experience:
a) an end user has the Nix ecosystem tooling installed on their machine
b) the end user runs a shell script, whose shebang is `nix-shell`
c) `nix-shell` ensures that all of the shell script's dependencies are installed locally and make them available in the script's `PATH`. If the dependencies are not installed locally, the Nix tooling downloads and installs them prior to running the script.

See for example: https://nixos.org/nix/manual/#use-as-a-interpreter

We've found this to be a great way to pin the dependencies of our shell scripts and ensure that we can reliably update those dependencies without needing to strictly control the installations on an engineer's laptop.

If `teleport` had a maintained Nix expression (package), it would make it easier for us to maintain our installations of the `teleport` tooling.

### Who's it for?
OSS User, Pro, Enterprise (all of the above)

**Comment by ari-becker** [comment]
I do see that there is an unofficial package already available in `nixpkgs`: https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/teleport/default.nix however, it is out-of-date (`4.2.3` vs. `4.1.0`) and installs all three binaries when only one of the three might be desirable (particularly in the contexts of a script).

**Comment by benarent** [comment]
Hi @ari-becker Thanks for creating the issue. I've labeled this under release-mgmt, and we'll likely look at publishing to more package managers once we've picked a new CI/CD service.

**Comment by goakley** [comment]
Adding some context, as we're using nix to manage packages on developer machines.

The [current nix package](https://search.nixos.org/packages?channel=unstable&show=teleport&type=packages&query=teleport) for Teleport usually lags behind the latest Teleport release, and while it's not so bad as to be unusable, it would be great if Gravitational provided some official support of the package.

**Comment by zmb3** [comment]
Not planned at this time.
