### ISSUE TITLE
4096-bit RSA and FedRAMP

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3519]
Investigate if 4096-bit RSA certificates are supported by FedRAMP.

**Comment by webvictim** [comment]
This is waiting on an upstream BoringCrypto fix from Go: https://github.com/golang/go/issues/41147

(see https://groups.google.com/g/golang-nuts/c/DbzPtRDtVgQ?pli=1 for some extra detail)

**Comment by russjones** [comment]
Looks like there are two issues were this comes up frequently.

1. Azure AD metadata endpoint.
2. AKS Kubernetes API.

**Comment by elsesiy** [comment]
This is a blocking issue for us. I reached out to MSFT to see whether we can provide a custom key length for the API server TLS cert but no chance...

**Comment by pschisa** [comment]
https://github.com/golang/go/issues/41147 is closed now allowing 4096-bit RSA keys

**Comment by pschisa** [comment]
@zmb3 Is there any updated timeline for when the fix will land in Teleport?

**Comment by zmb3** [comment]
@pschisa it landed in 11.1.4, so should be available today.

**Comment by pschisa** [comment]
Was able to confirm that 11.2.3-fips  worked with LetsEncrypt 👍
