### ISSUE TITLE
Support Athena storage in our Teleport Helm Chart

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#35205]
What would you like Teleport to do?
Have the option to deploy Athena via our chartMode: aws type for audit storage

What problem does this solve?
This allows for self-hosted AWS users of IGS access monitoring to deploy the Athena storage out of the box with our helm charts, reducing the barrier to using access monitoring

If a workaround exists, please include it.
Manually deploy Athena and sync it up with a helm cluster or fork the chart.

**Comment by hugoShaka** [comment]
This issue will be closed when #39801 merges. Users are not blocked anymore, they can use an Athena backend with the AWS chart mode. However we still don't have a happy path for users wanting to use Access Monitoring. There's another issue about this: https://github.com/gravitational/teleport/issues/39900
