### ISSUE TITLE
RDS Proxy auto-discovery uses proxy target port

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#35268]
Expected behavior:
- RDS Proxy always listens on port 3306/mysql or 5432/postgres, so teleport database auto-discovery should use those ports (although docs don't say for sql server, but we can assume it's the default sql server port).

Current behavior:
- teleport auto-discovery uses the RDS proxy's target's port as the uri for the RDS Proxy endpoint.

Bug details:
- Teleport version: v12+
- Recreation steps:
  - configure RDS db instance or cluster with a non-default port
  - configure RDS Proxy to use that db as a target (if you use an existing RDS proxy you may need to change the target and then change it back to propagate the port to RDS Proxy)
   - confirm that the RDS proxy target port is non-default: `aws rds describe-db-proxy-targets --db-proxy-name=<name> --region=<region>`
   - configure Teleport db_service discovery or discovery_service to discover the RDS Proxy
   - `$ tctl get db_server/<db-name> --format json | jq .[].spec.database.spec.uri` will show the non-default port was discovered

**Comment by GavinFrazar** [comment]
@greedy52 should be a simple fix, let me know if you want me to do this

**Comment by greedy52** [comment]
> @greedy52 should be a simple fix, let me know if you want me to do this

Thanks!
