### ISSUE TITLE
Advanced Session Control

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3526]
### Feature request

Implement [Advanced Session Control](https://docs.google.com/document/d/11LnPljqQqlrx8kIRQUxvR6bY5YscaKJohGqeAmfuuco/edit) session management and locking parts.

**Comment by klizhentas** [comment]
Covers A10 and A11
Best case: 1mo
Worst case: 2 months

**Comment by klizhentas** [comment]
Additional requirement:

If a login/session is blocked, a log entry should be created.

**Comment by benarent** [comment]
duplicate of #3360
