### ISSUE TITLE
Add more information to session.start

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3529]
### Feature Request

`session.start should log important items as username,internal ip, external ip, hostname, any labels, etc`

**Comment by klizhentas** [comment]
Addresses: A17
Best case: 1 week
Worst case: 1 week

**Comment by zmb3** [comment]
This has been addressed. `session.start` contains:
- UserMetadata (username, etc)
- ConnectionMetadata (local+remote address)
- ServerMetadata (hostname, labels, etc)
