### ISSUE TITLE
Teleport SSH Service

### ISSUE THREAD

**Issue by Jim0530** [gravitational/teleport#35307]
What would you like Teleport to do?
with the server Teleport SSH Service, Most of the time with the protected resource. It's hard to build the connection outside the world. SO the command down below actually won't work. 
`curl https://goteleport.com/static/install.sh | bash -s 14.2.1`
Is there other easy way to configure in a protected resource with limited internet access.
What problem does this solve?

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Yes, you can download the binaries from goteleport.com/download and get them on the machine in whatever way you see fit.

Once you've got the binaries on the node, you can generate a config file with `teleport configure` and start the process with `teleport start`.

In order for the node to join the cluster. You'll need a join token. There's a whole wealth of information on the various join methods and how to use them here: https://goteleport.com/docs/agents/join-services-to-your-cluster/
