### ISSUE TITLE
Unable to create working Vmware Vcenter app_service

### ISSUE THREAD

**Issue by savv3** [gravitational/teleport#35350]
Expected behavior:
Get a working Vcenter web application

Current behavior:
Vcenter seems to perform multiple redirects from their /websso login page, which seems to make Teleport loose track of it.

Bug details:
- Teleport version
teleport-14.2.0

**Recreation steps** 

- Create app_service:

  - name: "examplevcenter"
    uri: "https://examplevcenter.domain.com/"
    insecure_skip_verify: true
    rewrite:
      redirect:
      - "examplevcenter.domain.com"
      headers:
      - "Origin: https://examplevcenter.teleport.carus.com"
      - "Host: examplevcenter.teleport.carus.com"

- Restart teleport
- Navigate to https://examplevcenter.teleport.carus.com and try and login. 

I've tested with all manner of combinations for the app, but none that I've tried have worked.
I also found https://github.com/gravitational/teleport/discussions/25746 which seem to talk about the same issue. Sadly the accepted solution does not work for me.

I've also tested setting an nginx proxy between teleport and vcenter. I then get a working login and can navigate to vcenter. So this leads me to believe that there's some bug in teleport that makes vcenter not work. Maybe some proxy flag that is not set.

**Comment by zmb3** [comment]
Hi there,

Issues are best used for tracking specific feature requests or known bugs with detailed reproduction steps. General support requests are better suited for our community Slack workspace or GitHub discussions.

In fact, there's a relevant discussion on vCenter that may be of interest to you: https://github.com/gravitational/teleport/discussions/25746
