### ISSUE TITLE
Audit log shows node id vs node name. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3537]
### Description

**What happened**:

Audit log shows node-id vs it's node name. 

![image](https://user-images.githubusercontent.com/559288/78722298-06c70300-78de-11ea-85e8-b0cf9ccb1332.png)

**What you expected to happen**:
In my case `85f20e05-1c43-4c64-a572-38dd9837f90b` = node name `teleport5yubiauth`

**Comment by alex-kovoy** [comment]
This is related https://github.com/gravitational/teleport/issues/3542
