### ISSUE TITLE
Migrate from dep to go modules

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#3541]
Go modules are the future. They works outside of GOPATH, so build instructions are simpler.

**Comment by webvictim** [comment]
I’m running up against GOPATH/dep issues while looking into new CI solutions, so +1 from me.

**Comment by klizhentas** [comment]
I think we should do it, I would like to time it the way that won't disrupt too much - may be right after major release, or after beta release is cut, create beta.2 that is identical and is migrated to new dep modules, so we will avoid disrupting development flows.

**Comment by awly** [comment]
@klizhentas @russjones @webvictim @fspmarshall any objections to doing this now?
4.3 was just released and we have plenty of time to polish out any issues before 4.4.
I should be able to migrate without changing the locked versions of any deps.

Thumbs up on this comment if you approve, leave a comment if not.

**Comment by webvictim** [comment]
Only question from me is whether we’re going to keep with `dep` for `branch/4.3` and then cut over with 4.4, or whether we cut immediately and use Go modules for 4.3.1.

**Comment by awly** [comment]
To keep things simple, we should leave the 4.3 branch as is, using `dep`.
