### ISSUE TITLE
Support disabling automatic cloud tag detection

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#35426]
## What would you like Teleport to do?

Have a way to disable automatic instance tag detection in the `teleport.yaml` configuration.

## What problem does this solve?

In setups where labels are already managed manually, the users might not want to get additional labels from the cloud provider. This increases noise.

## If a workaround exists, please include it.

Disable the IMDS endpoint on AWS. Add a firewall rule to block the IMDS IP (169.254.169.254 in azure).

Related to: https://github.com/gravitational/teleport/issues/24230

**Comment by zmb3** [comment]
Looks like a duplicate of #23440

**Comment by hugoShaka** [comment]
Duplicate of https://github.com/gravitational/teleport/issues/23440
