### ISSUE TITLE
Improve the `tsh login` access request review message

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#35427]
What would you like Teleport to do?
with the following versions:
~~~
tsh version
Teleport v14.1.3 git:v14.1.3-0-g748fa4e go1.21.4
Proxy version: 14.2.0
Proxy: test-cluster1.plainsofconquest.com:443
~~~

I get the following output during a `tsh login`:
~~~
Access lists that need to be reviewed:
	dad0eeb2-2775-422e-8b26-6c7c65f64021 (-454h56m29s left to review)
~~~

Two problems with this output
1) The access list should be represented by the name instead of the ID to be human-readable
2) The negative seconds look wrong, especially when paired with "left to review"

What problem does this solve?
Making the access list output from `tsh login` more user-friendly and actionable

**Comment by zmb3** [comment]
`-454h56m29s left to review` does look awkward, but are you sure that the access list's next review date wasn't 454 hours in the past? Looking at the code and I don't see an obvious logic error.

**Comment by pschisa** [comment]
@zmb3 you are right, the time displayed was correct, awkward would be a more accurate description.  Its more about human readability to see a negative number combined with the phrase "time left to review"

**Comment by zmb3** [comment]
Thanks Paul - opened #35977 with a fix (it will now say "review was required 450 hours ago").
