### ISSUE TITLE
Clean-up the list of columns on the Active Session screen

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#3544]
The column names and content are a bit confusing. It appears that it's coming from the Event list.

![image](https://user-images.githubusercontent.com/7816406/78745034-0f94f480-7931-11ea-9b30-72a17ebb84ad.png)

Could you clean up the table titles together with the cell text templates?

**Comment by alex-kovoy** [comment]
@benarent any updates on this one?

**Comment by benarent** [comment]
I had some time today to review this ticket. 

### Active Session in 4.2

Session ID | User | Node | Created (UTC) | Duration
-- | -- | -- | -- | --
joinb7d66c23… | r0mant [73.202.138.51] | teleport-4-2-1-node-a [10.2.1.222] | 04/29/2020 12:29:18 | a few seconds


### Currently in 4.3
TYPE | DESCRIPTION | USER | CREATED |  
-- | -- | -- | -- | --
Session in progress... | Session started at root@teleport5auth | benarent | 2020-04-29 12:22:24 | JOIN

### Proposal. 

Description | Users | Node | Started (UTC) | Duration | Session ID |  
-- | -- | -- | -- | -- | -- | --
Session is in progress... | r0mant [73.202.138.51] | teleport-4-2-1-node-a [10.2.1.222] | 04/29/2020 12:29:18 | a few seconds | b7d66c23… | Options ↓
