### ISSUE TITLE
tbot attempt to approve access request is denied

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#35443]
Expected behavior:
Machine Bot user is not able to approve access requests

Current behavior:

Bug details:
- Teleport version: Teleport 14.2.1
- tbot version:  Teleport v13.4.3 git:api/v13.4.3-0-g80f1080 go1.20.10

- Recreation steps

1. Create a tob user: **tctl bots add robot --roles=reviewer --logins=root**
2. Start tbot process process providing token and proxy information from step 1
3. Using a separate user make a valid role request 
4. Review the requests from tbot instance using command: tsh request ls  --proxy=vasquca.teleport.sh -i /opt/machine-id/identity
5. Attempt to approve the request from tbot instance using command: tsh request review --approve <request-id>  --proxy=vasquca.teleport.sh -i /opt/machine-id/identity

- Debug logs

ERROR REPORT:
Original Error: *trace.AccessDeniedError user &#34;bot-robot&#34; cannot submit reviews
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/client.go:1103 github.com/gravitational/teleport/api/client.(*Client).SubmitAccessReview
	github.com/gravitational/teleport/tool/tsh/access_request.go:315 main.onRequestReview.func1
	github.com/gravitational/teleport/lib/client/api.go:1481 github.com/gravitational/teleport/lib/client.(*TeleportClient).WithRootClusterClient
	github.com/gravitational/teleport/tool/tsh/access_request.go:314 main.onRequestReview
	github.com/gravitational/teleport/tool/tsh/tsh.go:1346 main.Run
	github.com/gravitational/teleport/tool/tsh/tsh.go:537 main.main
	runtime/proc.go:250 runtime.main
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: user &#34;bot-robot&#34; cannot submit reviews

**Comment by strideynet** [comment]
Regression likely introduced by https://github.com/gravitational/teleport/pull/34594
