### ISSUE TITLE
ARMv7 build requires newer glibc

### ISSUE THREAD

**Issue by tomasvilda** [gravitational/teleport#35476]
Expected behavior:

Teleport starts

Current behavior:

Teleport v14.2.1 fails to start with the following error

```
teleport: /lib/libc.so.6: version `GLIBC_2.33' not found (required by teleport)
teleport: /lib/libc.so.6: version `GLIBC_2.32' not found (required by teleport)
teleport: /lib/libc.so.6: version `GLIBC_2.34' not found (required by teleport)
```

It works ok with v14.2.0

As I understand from release notes that's due to buildbox is based on debian 12 starting from v14.2.1. We use teleport as nodes for yocto dunfell based embedded linux systems. Current glibc version is 2.31.

Bug details:
- Teleport version 14.2.1

**Comment by fheinecke** [comment]
I can confirm that this is failing as described above:
<img width="578" alt="image" src="https://github.com/gravitational/teleport/assets/23390735/b0bf4182-28f1-4d06-bd67-55cdd7856e65">

Here is the output from the same build on amd64:
<img width="669" alt="image" src="https://github.com/gravitational/teleport/assets/23390735/f399bb72-ffe1-4493-84d7-17745b2deaf9">

Given that https://github.com/gravitational/teleport.e/actions/runs/7055201183 did not catch the issue, we probably need to include fixing that workflow in the scope of this issue.

**Comment by camscale** [comment]
Verified the the 32-bit ARM tarball on the release page for 14.2.2 (https://cdn.teleport.dev/teleport-v14.2.2-linux-arm-bin.tar.gz) contains a version of Teleport linked against earlier glibc - the latest symbol used is 2.28, earlier than 2.31 required by @tomasvilda
