### ISSUE TITLE
document terraform provider's create_host_user_mode option

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#35497]
## Applies To

https://goteleport.com/docs/reference/terraform-provider/#teleport_role

## Details

Our terraform provider plugin for teleport_role has the parameter spec.option.create_host_user_mode which is expecting a type number. Engineering has implemented the setting as an enum where valid options are: 1 (off), 2 (drop) and  3 (keep). 

This information is missing in the description for **create_host_user_mode**

## How will we know this is resolved?

Review docs. 

## Related Issues
https://github.com/gravitational/teleport/pull/27074

**Comment by ptgott** [comment]
We'll need to edit the code that [generates](https://github.com/gravitational/teleport-plugins/blob/b16e69ecbe52eaeaf71e95c84273a70c809aac69/terraform/gen/main.go#L553-L604) the Terraform provider reference docs. CC @marcoandredinis

**Comment by marcoandredinis** [comment]
We can add custom documentation here
https://github.com/gravitational/teleport-plugins/blob/b16e69ecbe52eaeaf71e95c84273a70c809aac69/terraform/gen/main.go#L547-L550

**Comment by hugoShaka** [comment]
Closing as the reference now says

> create_host_user_mode (Number) CreateHostUserMode allows users to be automatically created on a host when not set to off. 0 is "unspecified"; 1 is "off"; 2 is "drop" (removed for v15 and above), 3 is "keep"; 4 is "insecure-drop".
