### ISSUE TITLE
Ability to store the session recordings in Azure storage

### ISSUE THREAD

**Issue by voidspacexyz** [gravitational/teleport#35551]
What would you like Teleport to do?

I would like teleport [session recordings](https://goteleport.com/docs/architecture/session-recording/#storage) to be stored in [Azure Blob Storage](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction)

What problem does this solve?
It ensures environments that are run only in Azure, and have alternative cloud, have the ability to store and retreive session recordings from Azure blob storage itself without having to rely on another cloud provider. These are usually strong compliance regulations prohibiting many from using a 2nd cloud and only rely on a single cloud provider (in this case, Azure)

If a workaround exists, please include it.

I am not aware of it yet, as I have not read the code personally.

**Comment by stevenGravy** [comment]
@voidspacexyz this has been available since 13.3. Please see https://goteleport.com/docs/reference/backends/#azure-blob-storage
