### ISSUE TITLE
Define session.data event, provide context in audit log

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3556]
### Description

**What happened**:

![image](https://user-images.githubusercontent.com/559288/78913449-deeeb100-7a3d-11ea-8ae1-4c6ac56cff58.png)

We currently have a unknown event that shows data transferred during a session, `rx` & `tx`

<details>
        <summary>Details JSON for Unknown event</summary>

```json
{
  "addr.local": "127.0.0.1:3022",
  "addr.remote": "66.220.18.10:37396",
  "code": "T2006I",
  "ei": 2147483646,
  "event": "session.data",
  "login": "root",
  "rx": 93114,
  "server_id": "4ea15b6b-b4d4-4a1b-8ada-0966e9979ef6",
  "time": "2020-04-09T15:32:47Z",
  "tx": 40936386,
  "uid": "05fe444a-a08c-4123-a777-14612581b561",
  "user": "benarent"
}
```
</details>

**What you expected to happen**:

We should transfer bytes into a reasonable unit for it's size. Rolling up to kb, mb or gb. 
 - Session Data Report:  93kb data received and 40mb sent. 
 - Session Data Report: 5kb data received and 4kb sent. 

![image](https://user-images.githubusercontent.com/559288/78913699-3ee55780-7a3e-11ea-850b-28c88ad1db14.png)

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`): `5.0.0-alpha-1`

**Comment by benarent** [comment]
@alexwolfe Do you have thoughts on an icon for this?

**Comment by benarent** [comment]
Unknown should be `Session Data`

**Comment by benarent** [comment]
![image](https://user-images.githubusercontent.com/559288/86050984-8b22b100-ba09-11ea-8fe9-85045e2edcd8.png)

We provide a report, but it still lacks extra context. I would suggest that we could shorten the Session ID (expand on hover etc ) and display more information inline.

**Comment by alex-kovoy** [comment]
This has been fixed. As for improvements to the session logs, lets do them in the next release.
