### ISSUE TITLE
Verify that session remote.addr contains client address, not a proxy address

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3557]
### Feature Request

`remote.addr` is indeed logged for session.start or (kubectl.)exec, however this appears to be the IP of the proxy-server (or perhaps our ingress?); not the actual user. Confirm which IP is logged and fix if it's not the case

**Comment by benarent** [comment]
+1. I ran into this today. On my test cluster, it's correctly reporting the IP for server sessions but not for Kubernetes sessions. cc @awly

**Comment by strideynet** [comment]
Any objections to closing this in favour of #15521 ? This behaviour you are seeing is almost certainly related to the proxy reverse tunnel.

**Comment by strideynet** [comment]
Closing this in favour of #15521 and the ongoing work on client IP propagation by @AntonAM which will open doors for us getting this correct across all protocols.
