### ISSUE TITLE
Filtering not applied from Manage Clusters link in unified view

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#35597]
Expected behavior:

selecting a resource type fro Mange Clusters for a Teleport Cluster would apply a filter for only that resource type.

Current behavior:

Selecting a resource type does not apply filtering after navigating. In this example selecting Kubernetes go to the unified view and shows all resource types.

![image](https://github.com/gravitational/teleport/assets/60704961/7788b8ca-9033-42cf-9f71-7934a52f2f4d)

![image](https://github.com/gravitational/teleport/assets/60704961/ee237bdf-7bea-4a19-93f4-2b0184b0d5db)

Bug details:
- Teleport version: 14.2.0
- Recreation steps

1. Have a Teleport cluster with multiple resource types
2. Go to Manage Clusters Under Management
3. Select a cluster and a resource type
4. All resource types will show instead of that resource type.

**Comment by zmb3** [comment]
Personally I wouldn't bother with filtering and just reduce the menu to a single "Resources" item.

**Comment by stevenGravy** [comment]
> Personally I wouldn't bother with filtering and would just reduce the menu to a single "Resources" item

Closing with #35600 issue and have added a PR to address.
