### ISSUE TITLE
Custom Icon Integration for Social Media Platforms on Website

### ISSUE THREAD

**Issue by Ayush9026** [gravitational/teleport#35648]
**Issue Description:**

Overview:
The current website lacks individualized icons for major social media platforms such as Slack, GitHub, Twitter, LinkedIn, and YouTube. Integrating custom icons for these platforms will enhance the website's visual appeal, brand consistency, and user engagement. Marked in screenshot below.

![Teleport Website](https://github.com/gravitational/teleport/assets/114745463/b4b70171-b9d0-4ae3-8c46-7360aa73c660)

**Proposed Solution:**
Integrate custom icons for Slack, GitHub, Twitter, LinkedIn, and YouTube on relevant sections of the website. Ensure that the icons are visually consistent, aligned with the brand's identity, and easily recognizable by users.

**Benefits:**

Improved visual appeal and professionalism.
Reinforcement of brand identity.
Enhanced user engagement through recognizable icons.
Competitive advantage in terms of modern design standards.
 
**Implementation Steps:**

Design or obtain custom icons for each social media platform.
Update the website's code to replace existing generic icons with custom ones.
Test the integration across various browsers and devices to ensure compatibility.
Seek feedback from users and stakeholders to validate the effectiveness of the custom icons.

**Comment by strideynet** [comment]
Hey, would it be possible for you to raise this against https://github.com/gravitational/next - this repository is the correct one for issues relating to the website.

**Comment by zmb3** [comment]
Thanks for the feedback - I will share it with the owners of the website. I'm not going to keep the issue open though, as this is a very minor point that will eventually just become buried amongst higher priority issues.

**Comment by Ayush9026** [comment]
Yes @strideynet i will raise it.

**Comment by Ayush9026** [comment]
Thanks @zmb3. @strideynet this repo is not opening that you tell me.
