### ISSUE TITLE
allow to open multiple tcp forwards at once

### ISSUE THREAD

**Issue by Aureliolo** [gravitational/teleport#35684]
Currently we have the situation of that we are coming from a solution where everything was done over SSH tunnels with portforwarding. 
This includes websites,RDP,SSH,HTTP/HTTPS/MYSQL/APIs etc etc. 

We have a few thousand connections that are managed that way and after migrating to Teleport alot of those go away. 
But a significant amount still remains, so for example Websites or SQL etc. where you cannot do it that Teleport displays it in Browser or modify target SQL config to allow native. This is a list of Connections we open every single day over Bitvise currently. (just saves a profile we can easily share that opens hundreds upon hundreds of SSH tunnels)

When I want to replicate the legacy part we cannot migrate to native Teleport methods the only real way I found so far is like this: 

`
Start-Job -ScriptBlock { tsh proxy app mariadb-XXXXXX --port 56934 }; Start-Job -ScriptBlock { tsh proxy app minio-XXXXXX  --port 56936 }; Start-Job -ScriptBlock { tsh proxy app minio-XXXXXX  --port 56935 }
`

Which works but it is not really maintanable and scalable. And it spawns hundreds upon hundreds of processes in background. 

Now of course just having alot of ports open in Background goes against Zero trust etc. 

But if you want to convince people to use it instead of legacy system it has to be on same level as usability. and telling someone that needs like 20 of those connections "Oh yeah, just type this one command every single time you need to access Website XYZ and it blocks the shell, then you can close that one again and open another one" which seems to be the indeded use case/ux doesn't seem to nice. 

If at least you could natively open the ports in the background and wouldn't have to spawn a whole new process everytime with & or windows equivalent. 

Preferably there would be a way to define profiles maybe even or just give tsh a json or similar config object with combinations of ports and apps and so on it should open all at once without calling it hundreds of times would be a great improvement.

**Comment by Aureliolo** [comment]
@zmb3 Please do correct me if im wrong here, but to my understanding teleport connect does not open any TCP tunnels. It only allows actual SSH sessions right?

**Comment by Aureliolo** [comment]
Thats good to hear :) 
It will not solve the issue of sharing tough. This would mean every single person in our organisation would have to rebuild hundreds of ports manually one by one in teleport connect.

**Comment by zmb3** [comment]
This will be solved with the launch of Teleport VNet in Teleport 16. Teleport Connect will transparently establish tunnels for any TCP app you have access to.

@ravicious I'm assigning to you only so we don't forget to close this post-release, not because any specific action is necessary.

**Comment by zmb3** [comment]
This is solved by VNet in Teleport 16 (currently macOS only).
