### ISSUE TITLE
"How it works?" diagram should show "Root Cluster" not "Leaf Cluster"

### ISSUE THREAD

**Issue by tuladhar** [gravitational/teleport#35709]
## Applies To

- https://goteleport.com/docs/management/admin/trustedclusters/#how-it-works
![image](https://github.com/gravitational/teleport/assets/5674762/a6197950-48c4-4dbe-8a33-2bf5c40a083b)

## Details

In diagram above it, there should be root cluster.

## How will we know this is resolved?

Update the diagram.

**Comment by webvictim** [comment]
cc @ptgott

**Comment by zmb3** [comment]
Thanks @tuladhar - you're 100% correct.
