### ISSUE TITLE
Send error message type when there is an error starting sessions

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#3570]
### Feature Request
Send error message type when there is an error starting sessions.

Currently, when there is an error starting a session, server sends to client a series of events, eventually sending us a close session:
![Screenshot from 2020-04-13 13-28-51](https://user-images.githubusercontent.com/43280172/79158416-27360800-7d8b-11ea-9b43-f721b9c61cc9.png)
![Screenshot from 2020-04-13 12-44-56](https://user-images.githubusercontent.com/43280172/79158029-77609a80-7d8a-11ea-8cc9-5c23b1d45fd3.png)

Typing `exit` command, is also a close session event:
![Screenshot from 2020-04-13 13-35-03](https://user-images.githubusercontent.com/43280172/79158713-a88d9a80-7d8b-11ea-916a-0d86ddca8ebd.png)
![Screenshot from 2020-04-13 13-35-14](https://user-images.githubusercontent.com/43280172/79158714-a9263100-7d8b-11ea-86ca-f8a8bef49657.png)

### Problem
Currently, close sessions closes the terminal and there is no other event that tells the client there is an error unless we examine the msg payload. So error messages are swallowed and not seen by user.

### Motivation
Close session `without` error is a clean closing of terminal. Close session `with` error allows us to close terminal and show an error message to user.

### Who's it for?
OSS, Enterprise

**Comment by alex-kovoy** [comment]
closing in favor of #4025
