### ISSUE TITLE
v.4.3 UX: Expect to see all events when clicking on Audit Log tab

### ISSUE THREAD

**Issue by twakes** [gravitational/teleport#3577]
### Description

**What happened**: When ever I click on the Audit Log tab in the new UI, I expect to see a list of all the events but just the sessions show up. It then takes me a while to notice that in order to see all events you need to select that at the top of the list.

**What you expected to happen**: I would expect to see all the events with a filter for sessions. The more simple fix would be to make the "Events" is the default selection with the ability to click on "Sessions".

**Comment by benarent** [comment]
Thanks Taylor, we deliberated on this for a bit and at first we tried to keep the same mental modal as our current experience but since the sidebar menu now says `Audit Log`, the proposed switch might make sense. ( I'll leave this open for now for extra feedback )

**Comment by benarent** [comment]
We've decided to combine these lists for now. It better maps to our current RBAC rules for the UI and makes navigation easier.  Alexey is going to address this for 4.3

**Comment by alex-kovoy** [comment]
Some update below:

We decided to remove sessions and display only the Events inside Audit Log. 

Session Play button will be part of the Events view (TBD).

![image](https://user-images.githubusercontent.com/7816406/85075977-5e5ed600-b18d-11ea-8b10-b0b9044777dc.png)

**Comment by alex-kovoy** [comment]
closed by https://github.com/gravitational/webapps/pull/109
