### ISSUE TITLE
Web UI breaking changes in 4.3

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3580]
### Breaking changes to existing bookmarks.

New UI comes with updated routing (URLs) where each cluster has its own URL. Below is the list of URL changes.

|4.2.x   | 4.3.0  |
|---|---|
|web/newuser/:token|  web/invite/:token|
|web/sessions| web/clusters/:cluster/sessions|
|web/nodes| web/clusters/:cluster/nodes|
|web/settings/clusters|  web/clusters/:cluster/trusted|
|web/settings/auth| web/clusters/:cluster/auth|
|web/settings/account| web/account|
|web/cluster/:cluster/node/:node/:login| web/cluster/:cluster/console/:node/one/:login|
|web/cluster/:cluster/node/:node/:login/:sid|  web/cluster/:cluster/console/session/:sid|

### Backward compatibility 
Both Auth and Proxy services needs to be updated to 4.3 version. If one is 4.3 and another is still running 4.2, the New User Signup flow will be broken.

**Comment by benarent** [comment]
@russjones Do you remember what content we need for this?

Is this around creating new users / resetting users?

**Comment by benarent** [comment]
Added this into Release notes.
