### ISSUE TITLE
Unable to ssh into linux servers using older versions of teleport after upgrading main teleport server to V14 

### ISSUE THREAD

**Issue by MediaMeasure** [gravitational/teleport#35823]
We upgraded the main teleport node (proxy?) to version 14 and tried again after upgrading to v14.2.3.

Since the upgrade initially to 14, I can see the old linux nodes with teleport versions 9.3.4  and 9.3.9 in the web interface. however I cannot connect to the nodes via ssh reverse tunnel. I get the error:

    Teleport proxy failed to connect to "node" agent "@local-node" over reverse tunnel:
    no tunnel connection found: no node reverse tunnel for abc-node-id.teleport.xyz.com found

Our Teleport web shows nodes and their heartbeat etc seem in order. Nodes are also shown when running command: 

    sudo tctl nodes ls

Why can I not connect to my servers running older versions of teleport? 

Please help

**Comment by stevenGravy** [comment]
Teleport supports one major version behind.  Please update servers to at least 13.
