### ISSUE TITLE
Change copy on Trusted Cluster Page. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3586]
### Feature Request
I've improved the copy for Trusted clusters, our previous language was too vague and didn't clearly spell out root vs leaf relationship.

![image](https://user-images.githubusercontent.com/559288/79359105-ff63b300-7ef6-11ea-9425-cd6c18b82813.png)

1. Copy when not sharing cluster access. "Not sharing cluster access to a root cluster"
2. Button: "Connect to Root Cluster"
3. TRUSTED CLUSTERS
Trusted Clusters allows Teleport administrators to connect multiple clusters together and establish trust between them. Users of trusted clusters can seamlessly access the nodes of the cluster from the root cluster
Please view our documentation to learn more about [trusted cluster](https://gravitational.com/teleport/docs/trustedclusters/). 

### Who's it for?
Enterprise

**Comment by benarent** [comment]
https://gist.github.com/benarent/0a62bc2605a28ad77b6a0d5957c60b79 <- Is suggested updated to the placeholder trusted cluster yaml.

**Comment by alex-kovoy** [comment]
@benarent this placeholder means a root cluster. We cannot prepopulate it because we do not know it.
