### ISSUE TITLE
Ability to disable Authentification App two-factor and force hardware key to login to teleport

### ISSUE THREAD

**Issue by skirmantaskr** [gravitational/teleport#35922]
What would you like Teleport to do?
I want to be able to disable Authentication app two-factor type and leave only hardware key, because it is more secure.

What problem does this solve?
Can not find other way to force everyone to use hardware key as 2fa for authenticating to teleport. 

If a workaround exists, please include it.
Do not know any and even worse that I can not find the way to check who is using auth app instead of hardware key.

**Comment by zmb3** [comment]
To disable OTP, you should set `second_factor: webauthn` in your auth server's `teleport.yaml`. You likely have `second_factor: on` today.

**Comment by parassjain** [comment]
i m still not able to disable 2f here
