### ISSUE TITLE
Canceling MFA prompt isn't propagated correctly in Firefox

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#35933]
I suspect this is due to Firefox throwing different class of errors or something compared to other browsers.

Expected behavior:

https://github.com/gravitational/teleport/assets/27113/ed41ead3-bacc-4390-af3a-00a6c5b64a60

Current behavior:

After cancelling the prompt, I see `NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.` in the console.

https://github.com/gravitational/teleport/assets/27113/2bacbc58-c565-417a-96f5-a2075f08b53e

Bug details:
- Teleport version: master 00f3b4c9c3

**Comment by Joerger** [comment]
@ravicious I haven't had a chance to look into this. Is this a new bug related to my recent changes?

**Comment by ravicious** [comment]
I think it might be, as it happens during the prompt for MFA when updating a role.

I guess it's some kind of a trivial JS issue. I suspect you're pretty swamped with all of the MFA changes for v15, so I'll throw this under the Web test plan to have a full stack dev look at this.

**Comment by kimlisa** [comment]
hrm, i can't replicate this in firefox 
<img width="1536" alt="image" src="https://github.com/gravitational/teleport/assets/43280172/af110af3-a488-485b-b53c-c1b9bd9b6dda">

**Comment by ravicious** [comment]
I can still reproduce this on alpha.5. 🤔

**Comment by ravicious** [comment]
I wonder if it has to do with secure context and the cert being invalid in your case? I'm testing this on a local cluster where I trust the cert that the Web UI uses. I'm on Firefox 121 for what it's worth.

**Comment by kimlisa** [comment]
this is my staging cluster: 

<img width="1165" alt="image" src="https://github.com/gravitational/teleport/assets/43280172/68a91374-e0e8-4c7d-81a4-3e04b3fc73fd">

<img width="310" alt="image" src="https://github.com/gravitational/teleport/assets/43280172/f39d2385-7074-4e3b-83fb-a9172131c8f2">

**Comment by ravicious** [comment]
`navigator.credentials.get` must be returning a `NotAllowedError`, but for some reason this error is never surfaced to that `catch` in `api.ts` that shows the error from your screenshot.

Similar situation happens if I attempt to log in with Webauthn when having the Web UI on localhost – I see `SecurityError: The operation is insecure.`, but the error has no stack and the UI is stuck in the disabled state.

I said that "I suspect this is due to Firefox throwing different class of errors or something compared to other browsers". This is unlikely, as `fetchJsonWithMfaAuthnRetry` and all code below `auth.getWebauthnResponse` don't check the error in any way, they just have a generic `try catch` for all errors.

I tried turning off uBlock Origin and Enhanced Tracking Protection but it didn't help.

Let's close this for now until we're able to reproduce this on more than one machine.
