### ISSUE TITLE
Leaf Cluster not Mapping Approved Roles

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3593]
### Description
After a user is approved for another role the new role is not mapped when connecting to the leaf cluster. In case of Kubernetes the user then cannot use the approved role on the leaf cluster for their k8s access.

**What happened**:
A user has a limited role in the k8s groups binding with their default roles.  They request and receive approval for a role that maps to a group with k8s exec privilege in a namespace.  Within the cluster they requested the role with the exec privilege works.  After getting approval they have additional privileges within k8s in the cluster.

  When they login to a leaf cluster they only have access to their original default roles. Attempts to use the exec function return errors matching to their role before received approval.

**What you expected to happen**:
When a user logins to a another cluster after receiving approved roles they receive the mapping from those approved roles, not just their default roles.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a teleport configuration with a leaf cluster
2. Define two k8s roles, role bindings to groups that have different access (ex: one get only list pods and the other can exec sessions)
3. Create two roles in each cluster each matching to the different k8s groups.  One role can request the other role with more privileges.  The roles should map to the leaf cluster with the same privileges.
4. Create a user with the less privileged role and a user with the more privileged role.
5.  Confirm both users have the access expected and denied access with their k8s groups on the trusted and leaf cluster.
6. Have the user request the more privileged role (tsh login --request-roles=<rolename>) on the trusted cluster.
7. Approve the request through tctl
8. Confirm the user now has more k8s access with the approved role session
9. Login to the leaf cluster
10. Attempt the same access

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v4.2.8git:v4.2.8-0-ga9015b33 go1.13.2

- Tsh version (use `tsh version`): Teleport v4.2.8 git:v4.2.8-0-ga9015b33 go1.13.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GKE

**Relevant Debug Logs If Applicable**

These logs show a user not getting the mapped role they were approved after getting approved from the trusted cluster.  A user that has the devadminrole was confirmed to work on the leaf cluster through the trusted cluster mapping.

Original tsh status after logging into the trusted cluster:
```
 Profile URL:  https://mdem428-dev
  Logged in as: stevendev
  Cluster:      mdem428-dev
  Roles:        devrole*
  Logins:       devuser
  Valid until:  2020-04-16 11:32:40 -0400 EDT [valid for 12h0m0s]
  Extensions:   permit-agent-forwarding, permit-pty
```

 tsh status after getting approved for devadminrole and logging into leaf cluster
```
> Profile URL:  https://mdem428-dev
  Logged in as: stevendev
  Cluster:      mdem428-test
  Roles:        devadminrole, devrole*
  Logins:       devuser, devadminuser, root2
  Valid until:  2020-04-16 11:32:40 -0400 EDT [valid for 11h53m0s]
  Extensions:   permit-agent-forwarding, permit-pty
```

- Leaf cluster when a k8s exec is attempted.  The testadminrole (mapped from devadminrole) is missing.
```
DEBU [AUTH]      Mapped roles [devrole] of remote user "stevendev" to local roles [testrole] and traits map[kubernetes_groups:[developer-oncall] kubernetes_users:[] logins:[]]. auth/permissions.go:161
DEBU [PROXY:KUB] Exec /api/v1/namespaces/prd/pods/nginx-65f88748fd-2v7hn/exec?command=bash&container=nginx&stdin=true&stdout=true&tty=true. proxy/forwarder.go:443
```

Error received through leaf cluster after attempting exec:
`error: Internal error occurred: error executing command in container: Internal error occurred: error executing command in container: pods "nginx-65f88748fd-2v7hn" is forbidden: User "remote-stevendevl.com-mdem428-dev.gravitational.co" cannot create resource "pods/exec" in API group "" in the namespace "prd"`

**Comment by benarent** [comment]
@awly I know you've been poking around the our kubernetes setup. Have you had a chance to test role mapping yet?

**Comment by awly** [comment]
I haven't played with trusted clusters or custom roles yet, but can dig in later.
If this becomes urgent, I might pass it off to someone with more experience.
