### ISSUE TITLE
`make test` should verify that binaries build on all supported platforms

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#3594]
Right now `make test` and even `make release` all use local `GOOS` value.
To prevent accidentally breaking releases with platform-specific changes, `make test` (or possibly another rule) should build:
- `teleport` and `tctl` for `linux` and `darwin`
- `tsh` for `linux`, `darwin` and `windows`

**Comment by awly** [comment]
Couldn't get this to work due to CGO - it seems tricky to cross-compile our binaries to non-native OSs.
We'll just have to catch any breakage at release time instead of PR review.

**Comment by webvictim** [comment]
This is now implemented at PR merge time by #5292
