### ISSUE TITLE
Setup redirect service for links used in Teleport code 

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport#3605]
There are some instances of using static links to our docs in Teleport code, specifically in certain error logs. It has been discussed to set up some kind of redirection service and use links to that instead.

Using some redirection service doesn't rely on us needing to update the code if we ever change a path to the docs - we will just have to change where the link points to in our external database.

Additional benefits discussed in #3566 are redirection services give the ability to monitor how many people are clicking on a specific link

**Comment by benarent** [comment]
I've been noodling on this, and while there are 3rd party services that do this. I think it's best to keep this in house. A simple S3 bucket can be configured to setup redirects easily and we can have it managed in another project, I've used a simple S3_website ruby gem for this in the past, but I'm sure there is something in the Go land that does the same thing. 

It would also be good to pass along the Teleport Version and hash, so we track if any version is running errors. This also gives us the ability to redirect the correct version number of the docs.

**Comment by klizhentas** [comment]
We are are tracking this ina  separate projec.t
