### ISSUE TITLE
The New Request table sort is not intuitive

### ISSUE THREAD

**Issue by twakes** [gravitational/teleport#36070]
Expected behavior: When making a new resource request I sorted the table by "Name". That did not lead to a sort by the left column, which is what I was expecting. It's also not clear what the columns are without column headers, so maybe it's sorting on some other column.  I would expect column headers with the ability to sort each column header instead of a separate sorting dropdown.

Current behavior:
Column on the left is sorted alphanumerically and there is a separate sorting UI element that does not specify which column you are sorting by. Not clear what "Name" or "Type" is in the Table.

Bug details:
- Using teleport cloud version as of 12/27
- Debug logs (will send screenshot)

**Comment by zmb3** [comment]
I believe this was fixed in #35729, which is in the 14.3.0 release that I am starting on right now.

**Comment by zmb3** [comment]
This table was reworked and the issue should no longer be present. Let me know if you run into it again, otherwise we'll consider this deprecated by recent changes.
