### ISSUE TITLE
New teleport-auth in ASG group is missing /etc/letsencrypt state

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3610]
### Description

**What happened**:

When teleport-auth in ASG group comes up, it should sync the renewal state (and periodically)

```
# AWS sync replaces symlinks with copies, certbot expects symlinks
# https://community.letsencrypt.org/t/certstorageerror-expected-etc-letsencrypt-live-example-com-cert-pem-to-be-a-symlink/46622/9

ln -sf /etc/letsencrypt/archive/iot.gravitational.io/cert1.pem /etc/letsencrypt/live/iot.gravitational.io/cert.pem 
ln -sf /etc/letsencrypt/archive/iot.gravitational.io/chain1.pem /etc/letsencrypt/live/iot.gravitational.io/chain.pem 
ln -sf /etc/letsencrypt/archive/iot.gravitational.io/fullchain1.pem /etc/letsencrypt/live/iot.gravitational.io/fullchain.pem 
ln -sf /etc/letsencrypt/archive/iot.gravitational.io/privkey1.pem /etc/letsencrypt/live/iot.gravitational.io/privkey.pem

aws s3 sync s3://${TELEPORT_S3_BUCKET} /etc/letsencrypt --sse=AES256
```

otherwise it's renewal state folder is empty, and when the certbot renewal runs the renewal it's missing the folder contents and does nothing. 

To fix that, I suggest to dd the sync line above before running certbot in the renew script

```bash
#!/bin/bash

# This script is called hourly to check if the certificate
# needs renewal, and renews the cert after that

set -e
set -x

# Source variables from user-data
. /etc/teleport.d/conf

if [ ! -f /etc/teleport.d/role.auth ] && [ ! -f /etc/teleport.d/role.all ]; then
    echo "Not running 'auth' or 'all' role, exiting with success"
    exit 0
fi

# AWS sync replaces symlinks with copies, certbot expects symlinks
# https://community.letsencrypt.org/t/certstorageerror-expected-etc-letsencrypt-live-example-com-cert-pem-to-be-a-symlink/46622/9

ln -sf /etc/letsencrypt/archive/iot.gravitational.io/cert1.pem /etc/letsencrypt/live/iot.gravitational.io/cert.pem 
ln -sf /etc/letsencrypt/archive/iot.gravitational.io/chain1.pem /etc/letsencrypt/live/iot.gravitational.io/chain.pem 
ln -sf /etc/letsencrypt/archive/iot.gravitational.io/fullchain1.pem /etc/letsencrypt/live/iot.gravitational.io/fullchain.pem 
ln -sf /etc/letsencrypt/archive/iot.gravitational.io/privkey1.pem /etc/letsencrypt/live/iot.gravitational.io/privkey.pem

aws s3 sync s3://${TELEPORT_S3_BUCKET} /etc/letsencrypt --sse=AES256
# This is called periodically, if renewal is successful
# certs are uploaded to the S3 Bucket
certbot renew --deploy-hook=/usr/bin/teleport-upload-cert
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by klizhentas** [comment]
I have also noticed, that on proxy I had to:

```
 rm -f /var/lib/teleport/fullchain.pem 
```

Before aws sync actually worked, mysteriously and unexpectedly it synced the old copy of the file 

So this did not work as I expect, the file was the same

```
/bin/aws s3 sync s3://${TELEPORT_S3_BUCKET}/live/${TELEPORT_DOMAIN_NAME} /var/lib/teleport
```

This did:

```
 rm -f /var/lib/teleport/fullchain.pem 
/bin/aws s3 sync s3://${TELEPORT_S3_BUCKET}/live/${TELEPORT_DOMAIN_NAME} /var/lib/teleport
```

Before aws sync actually worked, mysteriously and unexpectedly it synced the old copy of the file

**Comment by klizhentas** [comment]
Also, probably instead of just symlinking hardcode fullchain1.pem, we should find out the latest fullchainN.pem and symlink it instead

**Comment by emmahsax** [comment]
We can use the exact timestamps:
```
/bin/aws s3 sync --exact-timestamps s3://${TELEPORT_S3_BUCKET}/live/${TELEPORT_DOMAIN_NAME} /var/lib/teleport
```

and then not have to delete the files first

**Comment by webvictim** [comment]
So for anyone who has redeployed their Teleport auth servers, then found that their Let's Encrypt certs have expired and aren't automatically renewing, here's the sequence of events to make things work again:

- Delete the contents of the `live/` directory from the S3 bucket which Teleport is configured to use
  - This is the `TELEPORT_S3_BUCKET` variable in `/etc/teleport.d/conf`
- Log onto an auth server and run `systemctl restart teleport-get-cert`
  - If it fails, that server probably doesn't have the lock, so run it on the other auth server.
  - You can check the hostname of the server which does have the lock in the DynamoDB table with the `-locks` suffix. Locks last an hour.
- The job should block while the certs renew (takes 30-60 seconds) and are synced up to S3. You can check the S3 bucket after the job has finished to make sure there are new certs available there.
- Log onto all your Teleport proxies and run `sudo rm -f /var/lib/teleport/*.pem`, then `sudo systemctl restart teleport-proxy` on each. This will sync the latest certs from the S3 bucket to `/var/lib/teleport` and then restart the proxy service.

At this point, Teleport should start with the fresh, up-to-date Let's Encrypt certs. We're going to fix this in the AMI so certs are properly synced when a new auth server is provisioned, which should prevent the issue from occurring in future.
