### ISSUE TITLE
Use AD CS to request windows logon certificates

### ISSUE THREAD

**Issue by unreality** [gravitational/teleport#36172]
**What would you like Teleport to do?**

Active Directory Certificate Services has a few methods for requesting certificates. Teleport could use the DCOM RPC (via SMB or Dynamic Endpoint), or the Web Enrolment Service to request smartcard certificates instead of generating them itself.

**What problem does this solve?**

Currently Teleport requires a service account which can edit and update the `NTAuth` certificate store. This is a reasonably high privilege level, which is not necessary if ADCS issues the certificates instead. Security teams are wary of allowing write access to the `NTAuth` store, so any reduction in privileges is desirable. 

Teleport recommends ADCS as part of its deployment, so this does not introduce any additional requirements, but it would provide an attractive configuration option for those who have large AD deployments and cannot obtain write access to NTAuth. Other CAs such as Hashicorp Vault or Step-CA may be easier to implement as well if the certificate request is abstracted into an interface.

Changes required would probably be on the order of:
* Altering the LDAP configuration to use stored credentials (or certificate?) instead of generating its own from its CA certificate.
* Altering https://github.com/gravitational/teleport/blob/1dcd7b37a673eb813245ea041a18e934f6061bea/lib/auth/windows/windows.go#L191 (or further up) to examine the configuration and request a certificate via RPC instead.
* Documenting required changes to ADCS and windows service config (creating a new certificate template, service account, etc)

Happy to take a crack at this if its something that would get merged in, its a feature we would like.

**Comment by zmb3** [comment]
Starting with Teleport 15, Teleport will no longer require write access to NTAuth.

This is a much simpler change than the proposal here.
