### ISSUE TITLE
Request to Add File Size Limit Permission for SCP Transfer

### ISSUE THREAD

**Issue by bahmanjafari** [gravitational/teleport#36222]
What would you like Teleport to do?
Teleport 13

What problem does this solve?

Hi
Happy New Year! 

Currently, there doesn't seem to be a defined maximum size limit for the files transferred using SCP. I believe it would be beneficial to implement a permission mechanism to set a maximum size limit for SCP file transfers. This would help ensure efficient use of resources and prevent potential issues related to large file transfers.

I kindly request your consideration in adding this feature to our system

Thank you for your attention to this matter.

**Comment by strideynet** [comment]
Could you talk a little more about the usecase here? In terms of standard system administration, I can't see a purpose for this so would be interested in finding out more. This helps us make sure that what we build meets the need appropriately.

**Comment by zmb3** [comment]
Thanks for the request. This is unfortunately not something we're planning on addressing.
