### ISSUE TITLE
"Webauthn session data is not found error" with passwordless logins

### ISSUE THREAD

**Issue by mathijstrue** [gravitational/teleport#36287]
Expected behavior:
Passwordless logins and registrations should not fail with a "webauthn session data is not found" error. 

Current behavior:
Passwordless registration and some passwordless logins are receiving the error "webauthn session data is not found".

Bug details:
After upgrading from teleport 13.4.x to 14.3.0 some users are no longer able to login using passwordless login methods. Creating a new user and selecting the passwordless login option always results in the same error: "webauthn session data is not found". There are users where passwordless login does still work, it looks like older user accounts are not affected by this bug. The bug is reproducible in both chrome and safari on macos with either a yubikey or chrome/safari passkeys.

- Teleport version
Teleport v14.3.0 git:v14.3.0-0-g390d33c go1.21.5

- Recreation steps

(upgrade from 13.4 to 14.3, not sure if this step is necessary)

1. Create a new user
2. Start the setup by following the invite link
3. Choose "Go passwordless"
4. Use any passkey or hardware key
5. Observe the error: webauthn session data is not found

- Debug logs
[debug.log](https://github.com/gravitational/teleport/files/13833910/debug.log)
I recorded the log with the following config while performing steps 1 through 5:
```
log:
    output: /var/log/teleport/teleport.log
    severity: warn
    format:
      output: text
```
And could not find any error that would explain this behaviour.

HTTP request:
```
{
    "token": "d2d4acc695a4421a248127fe65d49b7f",
    "password": null,
    "webauthnCreationResponse": {
        "id": "uacBselPEHxGV_QQgd9-OPTWPtiSlkkf8Cldya1ZtKbc7q-lSi57bYu4kgUX4fXO",
        "type": "public-key",
        "extensions": {
            "appid": false
        },
        "rawId": "uacBselPEHxGV_QQgd9-OPTWPtiSlkkf8Cldya1ZtKbc7q-lSi57bYu4kgUX4fXO",
        "response": {
            "attestationObject": "o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVjCcr18AmNUW0o3-PxAkIKx6ZNKBSmkTpUd_0l0k7R34eDFAAAAAgAAAAAAAAAAAAAAAAAAAAAAMLmnAbHpTxB8Rlf0EIHffjj01j7YkpZJH_ApXcmtWbSm3O6vpUoue22LuJIFF-H1zqUBAgMmIAEhWCC5pwGx6U8QfEZX9BCBLTCz8K8gWgjD-D9H9AqdEa7L_CJYIK2cAF_2uexSm5I6GJOfuOEQrbuS6pYWv_8ZWbhKJ6ovoWtjcmVkUHJvdGVjdAI",
            "clientDataJSON": "eyJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIiwiY2hhbGxlbmdlIjoiOGxXaGNzY042MkljSjN4ZjVXb0FNNWRZV1JxTjdUZV95TFA2SklNMnhHUSIsIm9yaWdpbiI6Imh0dHBzOi8vdGVsZS50cnVlLm5sIiwiY3Jvc3NPcmlnaW4iOmZhbHNlLCJvdGhlcl9rZXlzX2Nhbl9iZV9hZGRlZF9oZXJlIjoiZG8gbm90IGNvbXBhcmUgY2xpZW50RGF0YUpTT04gYWdhaW5zdCBhIHRlbXBsYXRlLiBTZWUgaHR0cHM6Ly9nb28uZ2wveWFiUGV4In0"
        }
    },
    "deviceName": "passwordless-device"
}
```
response:
```
{
    "error": {
        "message": "webauthn session data is not found"
    }
}
```

**Comment by zmb3** [comment]
Webauthn challenges are only valid for 5 minutes, and some recent changes ensure that we don't operate on challenges that have reached their expiry.

I'd check the system time on your client and cluster components to make sure there's not any clock drift that could cause something to expire prematurely.

**Comment by mathijstrue** [comment]
No time drift on the auth servers or my local machine:
```
ssh auth_server_1 date -u; ssh auth_server_2 date -u; date -u
Fri Jan  5 08:07:48 UTC 2024
Fri Jan  5 08:07:48 UTC 2024
Fri Jan  5 08:07:48 UTC 2024
```

I have an existing account where my passwordless login works with both my yubikey and chrome passkey. When i create a new account and open the invite link in an incognito window i do get the above error.

**Comment by mathijstrue** [comment]
Looks like this check was only introduced 21 days ago:
https://github.com/gravitational/teleport/commit/dfc176f41efae5fb0b7b31ca6b3ccd1f657dc6ea#diff-e48d4b5ab5dddc2b08cfa82bd08865c95b0e2dad03354fad797dc4c5109282b3R739

**Comment by Joerger** [comment]
@mathijstrue I have not been able to reproduce this is standard cluster conditions. Can you share more about your setup? It looks like you have 2 auth servers, do you have a high availability setup with a load balancer?

Can you also check that there is no system time drift that could affect your backend?

Also, would you mind testing with v14.2.3 to see if you can still reproduce a similar error, before https://github.com/gravitational/teleport/commit/dfc176f41efae5fb0b7b31ca6b3ccd1f657dc6ea was introduced?
