### ISSUE TITLE
What's the best approach to show new data in the Teleport UI. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3629]
WIP

### Feature Request
Before Teleport 4.3, Teleport would keep open a websocket for new events / new nodes joining and other cluster joining. This meant customers wouldn't need to constantly hard refresh the Teleport UI to get the latest nodes. 

### Motivation
Describe why we should work on this feature request.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by alex-kovoy** [comment]
With thousands of nodes each potentially emitting events, having a live-update mechanism would impact UX, scalability, and performance.  Instead we can add "Refresh" buttons to specific tables to re-fetch the data.

**Comment by benarent** [comment]
We've fixed a few of these issue in newer versions of Teleport. I'm going to close this issue and continue the discussion in another ticket.
