### ISSUE TITLE
Allow creation of auth connector when Teleport first starts

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3632]
### Feature Request
"tctl create <auth-file>.yaml" is kind of a wacky workflow because you can only run tctl from within the auth server.  So once I deploy my cluster I'm in this intermediary state where I cannot login until I do extra work to get on the auth server and do that configuration.  It would be nice if I could configure a default auth connector in the auth server's configuration file, or point it at a directory of connector configurations, so that it just starts up and I can log in immediately.

### Motivation
The current workflow creates extra steps. Allowing the creation of an auth connector at the same time as starting Teleport will speed up onboarding.

### Who's it for?
Enterprise

**Comment by webvictim** [comment]
I believe you can do this with `teleport start —bootstrap`

**Comment by zmb3** [comment]
Ooh, neat - will give that a try.  Thanks Gus!

**Comment by benarent** [comment]
Closing this issue based based on previous suggestion.
