### ISSUE TITLE
Change the `insecure_skip_verify` attribute on an App discovered in a K8s cluster using the `discovery_service`

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#36328]
What would you like Teleport to do?

Provide an option change the `insecure_skip_verify` attribute on an App discovered in a K8s cluster using the `discovery_service`. The current set of [Annotations](https://goteleport.com/docs/application-access/enroll-kubernetes-applications/reference/#annotations) does not support changing this option and the option is not mentioned in [RFD 135](https://github.com/gravitational/teleport/blob/master/rfd/0135-kube-apps-discovery.md).

What problem does this solve?

Currently on all discovered Apps the default of `insecure_skip_verify=false` applies and this cannot be changed

If a workaround exists, please include it.

No workaround is available.

**Comment by gecube** [comment]
I agree. I also missed this annotation and kindly asking to add it. 

MORE: I'd like to ask to add all possible annotations to cover all config options available through config file.

Thanks in advance.
