### ISSUE TITLE
teleport.tar.gz doesn't include latest examples

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3636]
### Description

**What happened**:
The team has started to add a bunch of Teleport examples but we are still including older ones in the packaged `tar.gz`

```bash
benarent@wellington:~/teleport/examples$ ls
aws  chart  etcd  gke-auth  go-client  local-cluster  README.md  resources  systemd  upstart
benarent@wellington:~/teleport/examples$ cat README.md
# Examples

## Configuration Examples

* `local-cluster` : Sample configuration of a 3-node Teleport cluster using
  just a single machine

## Daemon Configuration

* `systemd` : Service file for systemd
* `upstart` : Start-up script for [upstart](https://en.wikipedia.org/wiki/Upstart)

## AWS examples

* `aws` : Examples of provisioning Teleport on AWS.


benarent@wellington:~/teleport/examples$ teleport version
Teleport v4.1.10 git:v4.1.10-0-gfd0d5599 go1.13.2
```

**What you expected to happen**:

Pull the latest examples from https://github.com/gravitational/teleport/tree/master/examples

**Comment by webvictim** [comment]
I think fixing this is going to require a backport of the changes from `master` into the `release/4.2`, `release/4.1`, `release/4.0` and `release/3.2` branches.

**Comment by benarent** [comment]
I don't think a backport is needed just for examples. I wasn't sure what cut / uploaded this. If `release/4.3` will have the updated examples, I'm Ok with that.

**Comment by benarent** [comment]
If we do another 4.2 patch release for something else, it might be worth including it but not just for this.
