### ISSUE TITLE
Password policy for local accounts

### ISSUE THREAD

**Issue by Matrix-Kim** [gravitational/teleport#36449]
What would you like Teleport to do?

We are testing teleport in an internet-blocked environment. Compared to other solutions, we were considering introducing it for a long time because it had so many necessary features,
but one thing that was disappointing was that there was no password policy for local accounts.
So, I decided to modify the source code of teleport and modified it so that password complexity(ref. wagslane go-password-validator) and password expiration cycle can be set in teleport.yaml. 
Because it was modified for a short period of time, some necessary functions, such as preventing password reuse, were missing, but no special problems occurred after using it for about a month.
We respect the teleport policy of minimizing local account functions for interoperability with legacy IAM, but we hope that the community version will add a feature that allows security protection even for small systems like ours.

What problem does this solve?

If a workaround exists, please include it.

**Comment by strideynet** [comment]
We've generally omitted adding more complex password policy to instead prioritise more modern and secure methods of authentication e.g Passwordless. For the most part, users who require password policies for compliance are going to be using an external SSO provider.

We have an existing ticket to cover password policy ( https://github.com/gravitational/teleport/issues/1936 ) so I'll close this as duplicate. Please feel free to add any additional remarks you have there.
