### ISSUE TITLE
`useUserTraits.test.tsx` flakiness

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#36444]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/7460167877/job/20297704086?pr=36283#step:7:1025

#### Relevant snippet

```
FAIL web/packages/teleport/src/Discover/Shared/SetupAccess/useUserTraits.test.tsx (7.156 s)
  ● static and dynamic traits are correctly separated and correctly creates Option objects › kubeUsers

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 12
    + Received  +  1

    - Array [
    -   Object {
    -     "isFixed": false,
    -     "label": undefined,
    -     "value": undefined,
    -   },
    -   Object {
    -     "isFixed": false,
    -     "label": undefined,
    -     "value": undefined,
    -   },
    - ]
    + Array []

      413 |       },
      414 |     ];
    > 415 |     expect(result.current.getSelectableOptions(traitName)).toStrictEqual(
          |                                                            ^
      416 |       dynamicOptions
      417 |     );
      418 |

      at toStrictEqual (web/packages/teleport/src/Discover/Shared/SetupAccess/useUserTraits.test.tsx:415:60)
```

```
Seed:        259909280
```

This was in teleport OSS, so ent tests were not ran. But even after removing `e` locally and running `yarn test --seed 259909280`, the test doesn't reliably fail, which tells us it's not because of test ordering.

**Comment by ravicious** [comment]
https://github.com/gravitational/teleport/actions/runs/8097195934/job/22127690869#step:7:762

**Comment by ravicious** [comment]
https://github.com/gravitational/teleport/actions/runs/8262755788/job/22602769299#step:7:968

**Comment by kimlisa** [comment]
this should've been resolved by this [change](https://github.com/gravitational/teleport/pull/40243/files#diff-12da1d5aba345e98631cafac9b252274b1fb6d0963fc69e0c5fbede3312a028dR534)

the reason why it was flaky was i was testing that something was getting `called` versus checking for a state to be updated
