### ISSUE TITLE
Support multiple recipients for cloud-managed slack plugin

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#36459]
## What would you like Teleport to do?

The Cloud-hosted Slack integration should support sending notifications to multiple channels or recipients based on the requested role.

## What problem does this solve?

Reduce access request noise for large organizations or heavy access request flows by sending the requests to the most appropriate channel/DM based on the request role.

This sounds like a cloud/self-hosted feature parity issue.

## If a workaround exists, please include it.

- Use `additional_reviewers` when creating the access request.
- Self-host the slack plugin and use the `role_to_recipents` map

## Notes

There's [an approved RFD](https://github.com/gravitational/teleport/pull/16288) about notification routing which never got implemented due to its complexity and priority changes.

**Comment by zmb3** [comment]
This was solved with notification routing rules.
