### ISSUE TITLE
Proxy should self-test k8s impersonation permissions at startup

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#3649]
### Feature Request

When a proxy starts up with k8s support, it should test its permissions against the k8s API with the provided kubeconfig.
This could be `selfsubjectreview` or some dummy request (like `get pods`) impersonating a known group.

### Motivation

If proxy has a mis-configured kubeconfig (or doesn't support some newer authn methods) it will appear as `system:anonymous` on the k8s API side and be denied impersonation of real user requests.
This is very confusing to debug, because a user sees some form of "permission denied" or even a "not found" error.

### Who's it for?

OSS User, Pro, Enterprise

**Comment by webvictim** [comment]
+1, great idea
