### ISSUE TITLE
With Teleport UI Access Request, by default the Roles items that apply are all selected, these should be unselected by default. 

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#36534]
What would you like Teleport to do?
By default the access request summary has all the roles selected. Instead the UI should have the roles unselected. 

What problem does this solve?
This is to help ensure the requester selects the role that provides adequate level of access. The use case shared by the customer is the following. One mysql instance has multiple databases with different permissions. We want to ensure that users will select the role that provides the correct level of access. With all the roles selected, they could gain higher privileges than required. 

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Not planned - see my response in https://github.com/gravitational/teleport/issues/36533#issuecomment-1887412306 for more details.
