### ISSUE TITLE
Helm chart upgrades/improvements

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3656]
Here's a list of things we should do to make our Helm chart better.

- [x] Make it easier to run Teleport OSS via Helm
- [x] Merge `teleport` and `teleport-auto-trustedcluster` Helm charts into one
- [ ] Add the ability to bootstrap certain config items up front
  - [ ] Roles
  - [ ] OIDC/SAML connectors for Enterprise
  - [ ] Github for OSS
- [x] Improve documentation with full table of potential values that can be overridden (see https://hub.helm.sh/charts/jetstack/cert-manager for an example)
- [x] Encourage people to leave the default values.yaml intact and just add their own overrides via a `teleport-values.yaml` file if necessary
- [x] Update everything to work with the latest version of Helm v3
- [x] Host the final chart somewhere to facilitate the workflow detailed below

Optional:
- [ ] Maybe look at some of the features of `teleport-demo` and how they might be useful in the main Helm chart

Planned final workflow: 
```console
helm repo add teleport https://charts.releases.teleport.dev
helm install -f teleport-values.yaml teleport teleport/teleport
```

**Comment by jon-can** [comment]
From a customer:
I didn’t realize this wasn’t helm-pullable already. For what it’s worth, I’d bump your product team on that, it’s a general expectation that if a vendor has a helm chart for a deployment that you should be able to run 1-2 commands to get the stack running in your cluster. Kubecost does this better than anyone else I’ve seen https://kubecost.com/install (need to enter an email to get the instructions, but it’s incredibly easy to set up once you have those)

**Comment by webvictim** [comment]
Updating from Helm v2 to v3 is a bit more of a priority now; Helm v2 is officially EOL as of Friday 13th November.

**Comment by llavaud** [comment]
In HA mode, the `checksum/config` annotation for the teleportauth deployment is updated only if `config.auth_public_address` change.
If we change other parameters like `tokens` or `storage` no rollingupdate are triggered.

**Comment by webvictim** [comment]
As a quick update on this, you can now do this:

```
helm repo add teleport https://charts.releases.teleport.dev
helm install -f teleport-values.yaml teleport teleport/teleport
```

**Comment by webvictim** [comment]
I think most of this has been handled by #5582 now. Any improvements will be tracked as feature requests for that chart.
