### ISSUE TITLE
Desktop Playback fastpath decoding bug

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#36604]
I managed to create a desktop session whose recording stops playing back at some point with the error

```
Error { context: "Fast-Path", kind: Custom, source: Some(Error { context: "<ironrdp_pdu::basic_output::surface_commands::ExtendedBitmapDataPdu as ironrdp_pdu::PduDecode>::decode", kind: NotEnoughBytes { received: 172464, expected: 188681 }, source: None }) }
```

It's not clear what's causing this, but it wasn't present in the session itself. It could be an IronRDP bug, though then I would expect to have seen it during the session itself (which is using the same codepath to decode fast path pdus). It may also be that there's a bug somewhere in the session recording or recording streaming code that's causing a fastpath pdu message to get corrupted.

**Comment by zmb3** [comment]
If you run into this during the test plan, try to save the recording so we have a repro.

**Comment by zmb3** [comment]
@ibeckermayer any recurrences or should we close?

**Comment by ibeckermayer** [comment]
I haven't seen any recurrences but I've mostly been tied up in CI stuff since posting this.
