### ISSUE TITLE
Management section is not responsive like resources in web ui

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#36698]
Expected behavior:

The Management section will be responsive in the UI like the resources.

Current behavior:

In the mgmt section listing horz scroll bars show.

<img width="1043" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/5c9b3578-e0ff-491c-87e8-13314af52f95">

Bug details:
- Teleport version: 14.3.3
- Recreation steps

Set resolution to 1400 x 900. Horz scroll bars will show.

**Comment by zmb3** [comment]
Closing in favor of #37179
