### ISSUE TITLE
Teleport client doesn't work.

### ISSUE THREAD

**Issue by aestebangarcia** [gravitational/teleport#3676]
Teleport client doesn't work.

**What happened**:
when I try to connect to a server, I get the following error and it doesn't let me do anything but if I do it with sudo I can.

**What you expected to happen**:
one day it worked and the next day it didn't.
**How to reproduce it (as minimally and precisely as possible)**:
when I try to connect to a server, I get the following error and it doesn't let me do anything but if I do it with sudo I can.
Example:
```
$./tsh --proxy='access.domain:port' login
anic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x108d725]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/client.(*Config).LoadProfile(0xc0004795e8, 0xc0000b2024, 0xc, 0x7ffcc94a8760, 0x1a, 0x0, 0x0)
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:484 +0xb5
main.makeClient(0xc0002c0000, 0x1, 0x0, 0x0, 0x0)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:839 +0xc33
main.onListNodes(0xc0002c0000)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:574 +0x48
main.Run(0xc0000aa070, 0x2, 0x2, 0x0)
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:323 +0x4c31
main.main()
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:163 +0x11c
```
### Environment
- Tsh version: Teleport v3.1.6 git:v3.1.6-0-gaada9001 go1.11.5
- OS :
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

It only happens to me in one user.
- Where are you running Teleport? Dedicated Hardware:

**Browser environment**

Google Chrome 81.0.4044.138

**Comment by webvictim** [comment]
1) You’re using an old version of the tsh client (3.1.6) - the latest version is 4.2.9 and has many bug fixes. You can download the latest version here: https://gravitational.com/teleport/download

2) I suspect that your tsh cache directory is probably owned by a different user. Please provide the output of `ls -lR ~/.tsh` to confirm.

**Comment by aestebangarcia** [comment]
the output of ls -lR ~/.tsh:

```

/home/a/.tsh:
total 24
-rw-r----- 1 a a     0 may  4 12:12 access.domain.yaml
drwxr-x--- 3 a a  4096 abr  5 22:34 cache
drwx------ 3 a a  4096 abr  5 22:34 keys
-rw-r----- 1 a a 13215 may  4 11:16 known_hosts
lrwxrwxrwx 1 a a    21 may  4 11:16 profile -> access.domain.yaml

/home/a/.tsh/cache:
total 4
drwxr-x--- 4 a a 4096 abr  8 15:09 access.domain:port

'/home/a/.tsh/cache/access.domain:port':
total 8
drwxr-x--- 2 a a 4096 abr 17 10:27 domanin1
drwxr-x--- 2 a a 4096 may  4 11:16 domanin2

'/home/a/.tsh/cache/accessdomain:port/domanin1':
total 0
-rw------- 1 a a 0 abr 17 10:27 namespaces%2Fdefault%2Fnodes

'/home/a/.tsh/cache/domain:port/domanin2':
total 428
-rw------- 1 a a  87222 may  4 11:16 authorities%2Fhost
-rw------- 1 a a 346057 abr  5 22:42 namespaces%2Fdefault%2Fnodes

/home/a/.tsh/keys:
total 4
drwx------ 2 a a 4096 abr  5 22:34 access.domain

/home/a/.tsh/keys/access.tuenti.io:
total 52
-rw------- 1 a a  1675 may  4 11:16 user@domain
-rw------- 1 a a  1578 may  4 11:16 user@domain-cert.pub
-rw------- 1 a a   381 may  4 11:16 user@domain.pub
-rw------- 1 a a  1407 may  4 11:16 user@domain-x509.pem
-rw-r----- 1 a a 33370 may  4 11:16 certs.pem
```

**Comment by webvictim** [comment]
@aestebangarcia What is the version of `teleport` on your `auth` and `proxy` servers? You can check with `teleport version` on these servers.

One thing you can try is deleting your entire `~/.tsh` directory and logging into the cluster again. It seems like maybe something has got confused there.

**Comment by russjones** [comment]
Closing this since we have not gotten a response from creator of this ticket. @aestebangarcia if you are still running into this issue, please create a new ticket.
