### ISSUE TITLE
Desktop access recording progress bar fails to reach the end in case of error

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#36827]
If a desktop access recording ends due to an error, the progress bar indicator doesn't reach the end of it's available track:

<img width="1243" alt="297496198-868e6e21-a361-401c-8cb0-4574bb6589eb" src="https://github.com/gravitational/teleport/assets/13578537/3aada27d-8423-4eb6-80df-1f344c5b2a3f">

**Comment by zmb3** [comment]
We can fix this here: https://github.com/gravitational/teleport/blob/88152574bf3da2236df960af5fe7cf98a236d0a0/web/packages/teleport/src/Player/DesktopPlayer.tsx#L74-L76

(Basically use `isComplete` to check for both states)

**Comment by ibeckermayer** [comment]
I tacked it on to https://github.com/gravitational/teleport/pull/36843
