### ISSUE TITLE
No audit log entries indicating SFTP failue due to RBAC restrictions

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#36820]
Expected behavior:
Teleport should refuse to copy a file and add an entry about it to the audit log.

Current behavior:
Teleport refuses to copy, but doesn't add any information about it in the audit log entry. I can only see "Usage report has been updated for session []".

Bug details:
Teleport version: v15.0.0-alpha.5
Recreation steps:
1. Create a role that denies copying files to a node and assign it to a user.
2. Try to copy a file to some node using `tsh scp`.

**Comment by zmb3** [comment]
Also reported last quarter: #31417

**Comment by capnspacehook** [comment]
Can repro, fix here: https://github.com/gravitational/teleport/pull/36977
