### ISSUE TITLE
Login failed events are not emitted when MFA is enabled 

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#36837]
Expected behavior:

A login failed event is emitted for every failed login attempt

Current behavior:

- When I login with MFA enabled and enter an incorrect password there is no login failure event emitted
- When I login with MFA enabled and tap an incorrect key there is no login failure event emitted
- When I login with MFA disabled and enter an incorrect password there is an event emitted

**Comment by yonathanpy** [comment]
There might be specific settings that control whether failed login events are logged or not. Look for options related to logging, auditing, or event generation, +Examine the audit logs or security logs of the system. These logs often provide more detailed information about authentication events, including failed attempts,ome MFA systems have specific behavior when it comes to logging failed attempts,

import logging

def authenticate_user(username, password, mfa_code):
    # Your authentication logic here

    # Example: Check if authentication failed
    if not authentication_successful(username, password, mfa_code):
        # Log the failed login attempt
        logging.error(f"Failed login attempt for user {username}")
        return False

    # Authentication succeeded
    return True

**Comment by codingllama** [comment]
Fixed.
