### ISSUE TITLE
`unknown or missing MFAAuthenticateResponse type <nil>`

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#36850]
Expected behavior:
tsh ssh ubuntu@server should return the error message saying ubuntu ins't allowed to be used by the user

Current behavior:

Error isn't propagated to users when the principal is denied, instead it prints a weird error saying `unknown or missing MFAAuthenticateResponse type <nil>` after requesting to login again.

``` 
tsh ssh ubuntu@tele.tsilva.dev
			Enter password for Teleport user tiago:
ERROR: unknown or missing MFAAuthenticateResponse type <nil>
``` 

Bug details:
- Teleport version: 15
- Recreation steps
- Debug logs

**Comment by codingllama** [comment]
I think this fall into relogin being too aggressive, which I've experienced a few times during the testplan too (see #36749). I'll take a look at it, although I'm not sure I'm the best person for this job.

**Comment by tigrato** [comment]
I can confirm that #36866 fixes this problem but given the cause, it should also happen in v14, v13 and v12

**Comment by codingllama** [comment]
Thanks for confirming the fix, Tiago! I'll mail out the backports and close this one.
