### ISSUE TITLE
tsh v13.4.15+ does not work on Windows 10 rev. 1607

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#36851]
I set up a virtual machine on Azure with Windows 10 2016 LTSB which is exactly rev. 1607. [Docs advertise rev. 1607 as the minimal supported version](https://goteleport.com/docs/installation/#operating-system-support).

Attempting to launch tsh fails with:

```
C:\Users\rav\Downloads>tsh.exe
panic: The specified module could not be found.

goroutine 1 [running]:
golang.org/x/sys/windows.(*LazyProc).mustFind(...)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.16.0/windows/dll_windows.go:325
golang.org/x/sys/windows.(*LazyProc).Addr(...)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.16.0/windows/dll_windows.go:333
github.com/gravitational/teleport/lib/auth/webauthnwin.webAuthNGetApiVersionNumber()
        C:/a/teleport.e/teleport.e/lib/auth/webauthnwin/zsyscall_windows.go:83 +0xb4
github.com/gravitational/teleport/lib/auth/webauthnwin.checkIfDLLExistsAndGetAPIVersionNumber(...)
        C:/a/teleport.e/teleport.e/lib/auth/webauthnwin/webauthn_windows.go:183
github.com/gravitational/teleport/lib/auth/webauthnwin.newNativeImpl()
        C:/a/teleport.e/teleport.e/lib/auth/webauthnwin/webauthn_windows.go:51 +0x18
github.com/gravitational/teleport/lib/auth/webauthnwin.init()
        C:/a/teleport.e/teleport.e/lib/auth/webauthnwin/webauthn_windows.go:36 +0x169
```

Teleport Connect starts up correctly, but cannot work as it's not able to start the tsh daemon.

The same problem exists on v14.3.3 (same error but x/sys is 0.15.0). 13.0.0 works but 13.4.15 fails with the same problem, which means that the issue was introduced between 13.0.0 and 13.4.15.

Bug details:
- Teleport version: 15.0.0-alpha.5

Related:

* https://github.com/gravitational/teleport/issues/32601

**Comment by codingllama** [comment]
I'm guessing the Azure machine lacks WebAuthn.dll, which causes a panic, which in turn escapes our error handling and makes tsh fail: https://github.com/gravitational/teleport/blob/9ce2c6ab6e62d1f9759b050c8ce890f26088033d/lib/auth/webauthnwin/webauthn_windows.go#L51-L58

Webauthn won't work if WebAuthn.dll is missing, but tsh should work. If I'm right it shouldn't be too hard to fix.

I had a look at the commits in branch/v13, but failed to spot where the regression happened.

**Comment by codingllama** [comment]
OK to close after backports land.
