### ISSUE TITLE
Security issues in no particular order

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3686]
### Description
This is a list of UX and security blocking issues, in no particular order, but coming from a customer:

* [x] Fix Quay.io teleport images as they are currently reporting vulnerabilities. Should be as easy as `apt-get update && apt-get dist upgrade` periodically.
*  [x] Disconnect the node from the auth server or proxy (shut down the auth server and proxy). Folks are reporting that `/readyz` endpoint is not going to degraded state. In addition to that they would want to have Prometheus gauge that mirrors readyz status
* [x] `/var/lib/teleport` is automatically created by teleport with `755` permissions without good reason.
* [x] Teleport download portal does not mention quay.io images or helm charts. This is unfortunate and gives wrong impression of teleport being "old school" when it's not. Quay.io images should be first class citizens of the download portal for that reason
* [x] Make sure that teleport AWS SDK and teleport configs support scenarios with DynamoDB custom KMS key aliases for server side encryption. It's not clear to folks if that is even possible with teleport right now and how to configure that

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190134506177097/1190159351875757) by [Unito](https://www.unito.io/learn-more)

**Comment by awly** [comment]
Rebuilding quay.io images is tracked at https://github.com/gravitational/teleport/issues/3357

**Comment by benarent** [comment]
I've created an issue in Web for #4 https://github.com/gravitational/web/issues/900
