### ISSUE TITLE
proper branding for SSO provider

### ISSUE THREAD

**Issue by flyinghermit** [gravitational/teleport#36883]
### What would you like Teleport to do?
In the `Sign in To Teleport` page, use proper icon and branding for SSO tiles.

<img width="734" alt="Screenshot 2024-01-18 at 2 20 55 PM" src="https://github.com/gravitational/teleport/assets/10177602/d5e92305-9b41-4eab-9fb9-fa14b59435b7">

- Why is Google tile colored "red" and orange for Okta? 
- Missing Okta Icon.

### What problem does this solve?
Proper branding increases trust in the login page. 

### If a workaround exists, please include it.
n.a

**Comment by zmb3** [comment]
See also #7325

**Comment by benarent** [comment]
I was recording a video yesterday and would love to have the right branding for key SSO providers.
