### ISSUE TITLE
Update Passkey / Security Key when saving the key

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#36896]
Expected behavior:
```diff
- Enter a name for your hardware key.
+ Enter a name for your Passkey or Security key
```
Also, update / refresh the USB key image to include passkey / hardware key graphics. 

Current behavior:
<img width="1060" alt="image" src="https://github.com/gravitational/teleport/assets/559288/72aba2b0-b98b-4045-848a-75af47e6bedf">

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
Closing in favor of #37616
