### ISSUE TITLE
Web: Re-authentication (admin action) errors

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#36900]
Expected behavior:

be able to deploy service 

Current behavior:

using the same hardware key to log in, when asking to be re-authenticated, it still gives me `access denied` and am not able to deploy:

<img width="1212" alt="image" src="https://github.com/gravitational/teleport/assets/43280172/9885a133-ef7a-447d-8930-e7f81ef8f6f2">

<img width="953" alt="image" src="https://github.com/gravitational/teleport/assets/43280172/0540ea62-9721-4780-b28e-966cfcea096f">

Bug details:
- Teleport version: the current `branch/v15` branch in my `cloud staging`
- Recreation steps: try enrolling a `rds` from `Enroll New Resource` flow

**Comment by kimlisa** [comment]
<img width="1588" alt="image" src="https://github.com/gravitational/teleport/assets/43280172/206db478-4cbb-498f-a83c-a5c7fb1363cc">

**Comment by Joerger** [comment]
These are both instances where reused MFA is necessary because the WebAPI performs more than one admin action on behalf of the user from a single web HTTP call. I'll have a fix for these once the necessary PRs are merged, before v15.0.0. Thanks for catching these!

**Comment by kimlisa** [comment]
tracking, teleterm is also affected with the admin action: https://github.com/gravitational/teleport/issues/36664#issuecomment-1908807105

**Comment by rudream** [comment]
- https://github.com/gravitational/teleport/issues/37298
- https://github.com/gravitational/teleport/issues/37299
