### ISSUE TITLE
Not able to use kubectl against leaf k8s cluster

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3694]
Prospect is not able to use kubectl against leaf k8s cluster. Relevant info is in this G Doc:
https://docs.google.com/document/d/1e-vbuyIGt_W-6huvAw6EBAR_t9v_s7JD-FB6JfxKnUM/edit

**Comment by webvictim** [comment]
This could potentially be related to

**Comment by awly** [comment]
@jon-can can they retry with https://github.com/gravitational/teleport/releases/tag/v4.2.10 ?

**Comment by awly** [comment]
Fixed via https://github.com/gravitational/teleport/pull/3735
