### ISSUE TITLE
incorrect default `--db-user` with auto-user provisioning via trusted cluster

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#36976]
Expected behavior:
- in a local cluster with my user setup to use database auto-user provisioning, I don't need to specify `--db-user`, it just uses my username automatically. So a trusted cluster should also work, e.g.: `tsh db connect --db-name=admin --cluster=leaf.com` should work.
- the default username should be: `remote-<username>-<root-cluster-name>`.
- `tsh db ls --cluster=leaf.com` displays my username as allowed db name, and ideally that should stay the same instead of printing the long form `remote-<username>-<root-cluster-name>`.
- Ideally it should also auto-detect when I manually specify my username and wrap it with the extra prefix/suffix automatically (i.e. don't leak this implementation detail in the UX).

Current behavior:
- default `--db-user` is selected as if it's a local cluster, i.e. just `<username>`
- However, it should be `remote-<username>-<root-cluster-name>`

I tried this with MongoDB, but it's not specific to mongo.

workaround:
- I can use `tsh db connect --db-user=remote-gavin-gavin2.cloud.gravitational.io --db-name=admin --cluster=gavin-leaf.cloud.gravitational.io`

Bug details:
- Teleport version: v15.0.0-alpha.5
- Recreation steps:
1. setup auto user provisioning in local cluster
2. create trusted cluster in local cluster, make sure you map the role that has auto user provisioning enabled
3. attempt to connect without giving `--db-user` from the root cluster.

- Debug logs:
```
2024-01-19T18:33:51-08:00 ERRO [DB:SERVIC] "Failed to send error message to MongoDB client: error authorizing database access\n\tplease use your Teleport username (\"remote-root-gavin2.cloud.gravitational.io\") to connect instead of \"root\"." db:self-hosted-mongodb error:[
ERROR REPORT:
Original Error: *errors.errorString EOF
Stack Trace:
	github.com/gravitational/teleport/lib/srv/db/mongodb/protocol/errors.go:52 github.com/gravitational/teleport/lib/srv/db/mongodb/protocol.ReplyError
	github.com/gravitational/teleport/lib/srv/db/mongodb/engine.go:340 github.com/gravitational/teleport/lib/srv/db/mongodb.(*Engine).replyError
	github.com/gravitational/teleport/lib/srv/db/mongodb/engine.go:71 github.com/gravitational/teleport/lib/srv/db/mongodb.(*Engine).SendError
	github.com/gravitational/teleport/lib/srv/db/common/reporting.go:79 github.com/gravitational/teleport/lib/srv/db/common.(*reportingEngine).SendError
	github.com/gravitational/teleport/lib/srv/db/server.go:1011 github.com/gravitational/teleport/lib/srv/db.(*Server).handleConnection.func2
	github.com/gravitational/teleport/lib/srv/db/server.go:1058 github.com/gravitational/teleport/lib/srv/db.(*Server).handleConnection
	github.com/gravitational/teleport/lib/srv/db/server.go:954 github.com/gravitational/teleport/lib/srv/db.(*Server).HandleConnection
	github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:606 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).handleLocalTransport
	github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:523 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).handleTransport
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:585 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels.func2
	runtime/asm_arm64.s:1197 runtime.goexit
User Message: EOF] id:8c42284f-f5cf-4177-87f6-4ff1e4df157a mongodb/engine.go:342

```

**Comment by greedy52** [comment]
dup of https://github.com/gravitational/teleport/issues/35901

**Comment by GavinFrazar** [comment]
closing as dup
