### ISSUE TITLE
TSH key TTL refactor

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#370]
- Use UTC everywhere
- Avoid separate storage file and just store in certificate

**Comment by klizhentas** [comment]
I think a good test would be - rename `.tsh` to `.ssh` and make sure that ssh client works:

http://gravitational.com/teleport/docs/admin-guide/#using-teleport-with-openssh

**Comment by klizhentas** [comment]
Couple of places with spotted local time used:

https://github.com/gravitational/teleport/blob/master/lib/auth/native/native.go#L182
https://github.com/gravitational/teleport/blob/master/lib/auth/native/native.go#L146

should be 

`time.Now().UTC()`
