### ISSUE TITLE
Can't play session recordings directly from audit log page

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#37066]
Expected behavior:
I should be able to click the play button on a session recording directly from the Audit Log page in the web UI to play the recording
<img width="692" alt="Screenshot 2024-01-22 at 5 16 47 PM" src="https://github.com/gravitational/teleport/assets/16807901/37b54696-1377-4395-b980-8ee7a31230b7">

Current behavior:
I just see a page with an error: `Invalid query parameter durationMs: , should be an integer.`

Bug details:
- Teleport version: v15.0.0-alpha.5
- Recreation steps:
- Debug logs

**Comment by nklaassen** [comment]
@zmb3 I suspect this was introduced in https://github.com/gravitational/teleport/pull/36168

**Comment by zmb3** [comment]
We already fixed this. We decided to just make this not a button, since few people know it's a button and none of the other audit events treat it as a button.

**Comment by zmb3** [comment]
See #36841
