### ISSUE TITLE
Support dynamic registration for Windows desktops

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#37103]
What would you like Teleport to do?

Support dynamic registration for Windows desktops. Similar to support that exists for the `db_service` and `app_service`, support should be added to run a `windows_desktop_service` with no defined hosts and for Windows desktops to be then registered dynamically using configuration (with a Terraform provider resource also added).

What problem does this solve?

Teleport currently supports dynamic registration of databases and applications but Windows `static_hosts` must be configured directly on a running `windows_desktop_service`.

**Comment by zmb3** [comment]
`static_host` is a file configuration, not a Teleport resource configuration.

That said, we already support registration via API or tctl.
- Example API integration: https://github.com/gravitational/teleport/tree/master/examples/desktop-registration
- Example resource for tctl: https://goteleport.com/docs/desktop-access/rbac/#static-hosts

**Comment by philip-teleport** [comment]
Thanks @zmb3 - the existing `kind: windows_desktop` resource is what I was thinking of above!

When using `tctl` to register a windows host can you explicitly set which windows_desktop_service(s) can proxy connections to it?

Based on what's support already, the outstanding items for this request would be:
1. To support matchers like app access does.
2. To support a Terraform provider resource for `kind: windows_desktop`.

**Comment by zmb3** [comment]
> When using tctl to register a windows host can you explicitly set which windows_desktop_service(s) can proxy connections to it?

Not only can you, it's a strict requirement. This must go in the `host_uuid` field.

> 1. To support matchers like app access does.

Seems like a reasonable request, but I don't see it being high priority any time soon.

> 2. To support a Terraform provider resource for kind: windows_desktop.

This may just work. I'm not super familiar with how the provider works. @hugoShaka what say you?

**Comment by hugoShaka** [comment]
To implement a resource in the provider, we need:
- the resource to have a protobuf message, if it's a legacy gogoproto one it's better
- a CRUD-like API, like all our other resources

If botyh conditions are met, I can bundle windows_desktop support with the agentless openssh and eic registration I have to do in Q1.

**Comment by zmb3** [comment]
Nice. Both conditions should be met. `WindowsDesktopV3` is an old gogoproto-style resource.

**Comment by eaterm** [comment]
Is there any status update on this?

Running a windows_desktop service that is bound to a specific host is not desired as this is not a highly available setup.

**Comment by zmb3** [comment]
There are no further updates on this.

You can register a separate copy of the desktop resource against as many windows_desktop_service host IDs as you'd like to achieve a highly available setup.

**Comment by eaterm** [comment]
> There are no further updates on this.
> 
> You can register a separate copy of the desktop resource against as many windows_desktop_service host IDs as you'd like to achieve a highly available setup.

Will look into that. 
Still hoping this will be added in the future. As this would make registering windows_desktop_service to the correct agents a lot easier.

**Comment by eaterm** [comment]
Nice to see that this is added.
Will there also be Terraform available for managing this?
