### ISSUE TITLE
tctl denied error message 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3712]
### Description

**What happened**:
When running `tctl` on the auth server, It throws the below error as the current user doesn't have enough permissions.

```bash
$ teleport-43-auth ~: tctl create github.yaml
ERRO[0000] Failing schema step: CREATE TABLE IF NOT EXISTS kv (
           key TEXT NOT NULL PRIMARY KEY,
           modified INTEGER NOT NULL,
           expires DATETIME,
           value BLOB);
        CREATE INDEX IF NOT EXISTS kv_expires ON kv (expires);, unable to open database file.  trace.component=sqlite
error: error creating schema: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF
```

**What you expected to happen**:
```bash
$ teleport-43-auth ~: tctl create github.yaml
Error: tctl must be run as root
```
^ IDK if we should require or even want to encourage running as root but this always fixes it for me. 😅

**Comment by webvictim** [comment]
I think this mostly a side effect of Teleport's data storage being under `/var/lib/teleport` where everything is owned by `root`:

```
$ ls -ld /var/
drwxr-xr-x. 23 root root 4096 Oct 31  2019 /var/
$ ls -ld /var/lib
drwxr-xr-x. 93 root root 4096 May 13 09:50 /var/lib
```

Maybe for auth/proxy servers (which don't need to run as `root`) we should encourage the creation of a `teleport` user to drop privileges, then run `chown -R teleport /var/lib/teleport` instead? It'd require some changes to the `systemd` unit to run as the `teleport` user too. Not sure how involved we want to get with people's filesystem permissions.
