### ISSUE TITLE
Hardware keys - failed to SSH

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#37146]
`tsh ssh` fails when `require_session_mfa: hardware_key` is set in the auth config.

```
$ tsh ssh dffe30aa-cc94-47fa-b461-ae8e08cfacf9
Enter password for Teleport user bob:
ERROR: unknown or missing MFAAuthenticateResponse type <nil>
```

Bug details:
- Teleport version: 15.0.0-alpha.5
- Recreation steps
- Debug logs

**Comment by Joerger** [comment]
You don't have any MFA devices registered for the user, right? Looks like the wrong error is getting propagated, it should be: `MFA is required to access this resource but user has no MFA devices; use "tsh mfa add"; to register MFA devices`

**Comment by jakule** [comment]
> You don't have any MFA devices registered for the user, right? Looks like the wrong error is getting propagated, it should be: `MFA is required to access this resource but user has no MFA devices; use "tsh mfa add"; to register MFA devices`

I do have mfa registered
```
~/projects/teleport/test/teleport-ent$ tsh mfa ls
Name   Type     Added at                      Last used                     
------ -------- ----------------------------- ----------------------------- 
YK-DEV WebAuthn Wed, 10 May 2023 18:38:33 UTC Wed, 24 Jan 2024 04:59:59 UTC 

~/projects/teleport/test/teleport-ent$ tsh ssh dffe30aa-cc94-47fa-b461-ae8e08cfacf9
Enter password for Teleport user bob:
ERROR: unknown or missing MFAAuthenticateResponse type <nil>
```

**Comment by Joerger** [comment]
@jakule That's odd, do you still get the error when you turn off hardware key support? Also does https://github.com/gravitational/teleport/pull/37223 fix it for you?

**Comment by jakule** [comment]
@Joerger It changes the error message but the end result is still the same
```
$ tsh ssh dffe30aa-cc94-47fa-b461-ae8e08cfacf9
ERROR: MFA is required to access this resource but user has no MFA devices; use 'tsh mfa add' to register MFA devices

$ tsh mfa ls
Name            Type     Added at                      Last used                     
--------------- -------- ----------------------------- ----------------------------- 
webauthn-device WebAuthn Mon, 18 Sep 2023 16:38:22 UTC Wed, 24 Jan 2024 04:59:38 UTC 
```

**Comment by Joerger** [comment]
@jakule The only was I was able to reproduce this was by registering a webauthn device and then setting `second_factor` to `off` or `optional`.

In old versions, this path should return `ERROR: MFA is required to access this resource but user has no MFA devices; use 'tsh mfa add' to register MFA devices`, and joerger/tsh-ssh-no-mfa-device fixes that too.
