### ISSUE TITLE
Display same connection errors in web as in tsh

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3722]
### Feature Request
Display connection errors so web users can see the same issues as within a tsh session.
 As one example the user `monitor` does not exist on a node though a user attempts to open a session.  The tsh user will receive the below

```bash
Failed to launch: user: unknown user monitor.
```
Within the web the same attempt results in the screen refreshing with no error displayed to the user.  Errors resolving a node's host are displayed within the web.

### Motivation
A user could miss issues causing inability to connect and confuse that with an issue with teleport.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by alex-kovoy** [comment]
@stevenGravy it's been fixed for the web UI

```
disconnected
Failed to launch: user: unknown user alex-kovoy.
the connection was closed on the remote side on  19 Apr 21 20:47 UTC
```
