### ISSUE TITLE
Classification between high privileged role and low privileged role and send automatic slack notification to provide reason for access

### ISSUE THREAD

**Issue by naidu-kjml** [gravitational/teleport#37247]
What would you like Teleport to do?
Classification between high privileged role and low privileged role, , some tag can be applicable to high privileged role like prod or non-prod, and to send automatic slack notification asking requester for the reason why approval is needed to higher role

What problem does this solve?
Current problem is all the teleport roles are considered in same way, no way of categorizing between Prod and Non prod, so if it required to keep some auditing, custom policies on high privileged role can be possible in case if we can do roles classification, and also it can notify on slack why prod role access is required.

If a workaround exists, please include it.
No workaround currently

**Comment by zmb3** [comment]
This is not quite actionable enough. 

> Current problem is all the teleport roles are considered in same way

This is by design. 

> so if it required to keep some auditing, custom policies on high privileged role can be possible in case if we can do roles classification, and also it can notify on slack why prod role access is required

Sounds like a good fit for access requests.
