### ISSUE TITLE
suggestion comment to use low privileged roles when raising access for high classified privileged role 

### ISSUE THREAD

**Issue by naidu-kjml** [gravitational/teleport#37248]
What would you like Teleport to do?
suggestion comment to use low privileged roles when raising access for high classified privileged role 

What problem does this solve?
While users raise request for a role with higher privileges, it can suggest as form of suggest comment box in UI , to consider using a role with lesser privileges as per the comment added by admin in the configuration to use alternative roles

If a workaround exists, please include it.
No work around currently

**Comment by zmb3** [comment]
We're in agreement that best practice is to use the tightest-scoped role possible, but I don't think adding a generic message to the UI is the right solution. Users will eventually go blind to it, and the definition of a "low privileged role" and a "high classified privileged" role is rather subjective.

Marking this one as not planned for now.
