### ISSUE TITLE
While raising a new “access request”, it should land by default to roles section instead of resources

### ISSUE THREAD

**Issue by naidu-kjml** [gravitational/teleport#37249]
What would you like Teleport to do?
While selecting on  “access request” tab, it should land by default to roles section instead of resources

What problem does this solve?
Teleport resources are classified according to roles, not individual resources, and when the new access request has to be raised, the page has to select "roles" option by default instead of "resources"

If a workaround exists, please include it.
No workaround currently

**Comment by zmb3** [comment]
This is not planned.

Resource access requests are our preferred mechanism as they are more finely scoped, and we prefer fine-grained access over broad access.
