### ISSUE TITLE
While reviewing access requests, approver should land on “Approve request” option by default , instead of “Reject request”

### ISSUE THREAD

**Issue by naidu-kjml** [gravitational/teleport#37250]
What would you like Teleport to do?
Approver should land on “Approve request” option by default, instead of “Reject request” , which can prevent the rejection of request by mistake.

What problem does this solve?
When approver has to review the access request raised by members, the radio option by default lands on "Reject request" option, if it can be on land on "approve request" option, it can prevent the rejection of request by mistake

If a workaround exists, please include it.
No workaround currently

**Comment by strideynet** [comment]
Wouldn't it be worse if you accidentally approved a request ? I'm not sure changing the default here is safe, especially if people expect the existing behaviour 😅

**Comment by zmb3** [comment]
I'm going to share the feedback with our design team, but close this issue. I will open a new one if something actionable comes of it, but it seems more like personal preference and changing defaults can be very disruptive to those who have been using the software for a long time.
