### ISSUE TITLE
Capture all kubectl commands in audit logs

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3729]
### Feature Request
We would like to be able to capture everything done using kubectl. For example if someone were to use "kubectl edit deployment", we would like to know who did that from what IP address and when they did it.

### Motivation
Our entire environment is kubernetes so we want to be able to capture everything being done in the cluster.

### Who's it for?
Community, Pro, Enterprise

**Comment by awly** [comment]
Events emitted in https://github.com/gravitational/teleport/pull/4526.
We still need the UI to not mark them as "Unknown"

**Comment by awly** [comment]
https://github.com/gravitational/webapps/pull/190 for UI update

**Comment by awly** [comment]
Fixed
