### ISSUE TITLE
"Add MFA" disabled in the WebUI

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#37311]
Expected behavior:

I should be able to add additional MFA devices in the WebUI. I have `webauthn` enabled and `local` auth (non-passwordless).

Current behavior:

the "Add MFA" button is grayed out.

![image](https://github.com/gravitational/teleport/assets/16672031/428d2dd0-6275-448c-9fa8-bdf8ea3ac6d7)

Bug details:
- Teleport version v15.0.0-beta.1

**Comment by Joerger** [comment]
@bl-nero It looks like this is related to https://github.com/gravitational/teleport/pull/37195

**Comment by zmb3** [comment]
This looks to be the culprit: https://github.com/gravitational/teleport/pull/37195/files#diff-3295ab646af6e24af3f7269c2b31695ee49c15437954181efbdbf1e2762053faR78

The ability to add an MFA device should not require TOTP to be the default.
