### ISSUE TITLE
Machine ID: Document AWS Roles Anywhere support using Workload Identity.

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#37329]
AWS Roles Anywhere allows AWS to be configured to trust x509 certs as a form of authentication. It would be useful if Machine ID was able to issue certificates which are compatible with RA as it would allow machines to access AWS without necessarily running on AWS using short-lived certificates (rather than an exported long-lived credentials file)

Potentially, the best route for this will be via our new SPIFFE x509 SVID capability in Workload ID - AWS docs show specific examples working with SVIDs. But, it's worth investigating if there's any clever workarounds in the mean time, even if the SVIDs would be more semantic.

https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html

**Comment by strideynet** [comment]
https://PROXY/webapi/auth/export?type=tls-user

**Comment by strideynet** [comment]
# With Experimental SPIFFE support 

1. Configure `tbot` and run this:

```yaml
version: v2
auth_server: redacted:443
certificate_ttl: 24h
onboarding:
  join_method: token
  token: redacted
storage:
  type: directory
  path: /opt/bot-storage
outputs:
- type: spiffe-svid
  destination:
    type: directory
    path: /opt/aws-roles-anywhere
  svid:
    path: /ra/my-role
```

2. Create trust anchor in AWS RA via the GUI (https://us-east-1.console.aws.amazon.com/rolesanywhere/home/trust-anchors/create). Use the contents of `/opt/aws-roles-anywhere/svid_bundle.pem` as the "
External certificate bundle" 

3. Create role and configure RA and Trust Anchor as a trusted entity. Replace TRUST_ANCHOR_ARN and CLUSTER_NAME:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "rolesanywhere.amazonaws.com"
            },
            "Action": [
                "sts:AssumeRole",
                "sts:TagSession",
                "sts:SetSourceIdentity"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:PrincipalTag/x509SAN/URI": "spiffe://CLUSTER_NAME/ra/my-role"
                },
                "ArnEquals": {
                    "aws:SourceArn": "TRUST_ANCHOR_ARN"
                }
            }
        }
    ]
}
```

5. Configure AWS RA profile specifying role. Record the RA Profile ARN.

6. Download AWS SIgning Helper, make it executable - https://github.com/aws/rolesanywhere-credential-helper

7. Configure aws CLI to use  `aws_signing_helper`. Replace PROFILE_ARN, TRUST_ANCHOR_ARN and ROLE_ARN.

```
➜  ~ cat ~/.aws/config 
[profile use-roles-anywhere]
credential_process = /Users/noah/Downloads/aws_signing_helper credential-process --certificate /opt/aws-roles-anywhere/svid.pem --private-key /opt/aws-roles-anywhere/svid_key.pem --profile-arn PROFILE_ARN --trust-anchor-arn TRUST_ANCHOR_ARN --role-arn ROLE_ARN
```

8. Use AWS CLI
```
➜  ~ aws --profile use-roles-anywhere sts get-caller-identity --no-cli-pager 
{
    "UserId": "REDACTED:REDACTED",
    "Account": "REDACTED",
    "Arn": "ROLE_ARN"
}
```

**Comment by gclawes** [comment]
Does Machine ID w/ SPIFFE utilize any intermediate certificates?

**Comment by strideynet** [comment]
> Does Machine ID w/ SPIFFE utilize any intermediate certificates?

Not at this time - there's a root SPIFFE CA created in Teleport and the workload identity certificates are then directly issued by this CA. Is there a use-case in mind in relation to intermediate certs @gclawes

**Comment by gclawes** [comment]
> > Does Machine ID w/ SPIFFE utilize any intermediate certificates?
> 
> Not at this time - there's a root SPIFFE CA created in Teleport and the workload identity certificates are then directly issued by this CA. Is there a use-case in mind in relation to intermediate certs @gclawes

No specific need for intermediates, but if they do get introduce they'll need to be present on the client machines.  In IAM Roles Anywhere the `aws_signing_helper` needs to pass any intermediate CAs in a bundle via the `--intermediates` flag.  I'm sure there are other use cases where they may need to be present on the client machines, too.
