### ISSUE TITLE
Design to edit user traits in the web UI

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#37369]

**Comment by strideynet** [comment]
It'd be nice to make sure we tie this into the new Bots management page too ( the UI should be entirely the same )

**Comment by roraback** [comment]
For context: current Traits UI in Access Lists (but it could use a bit of TLC)

![Image](https://github.com/gravitational/teleport/assets/1095531/47633ba0-2431-46ee-bf9e-81e0aa6533e5)

**Comment by flyinghermit** [comment]
@roraback any ETA on this? 

I had this following mock up which is built on the current "Edit User" modal. 
<img width="870" alt="Screenshot 2024-03-25 at 3 22 32 PM" src="https://github.com/gravitational/teleport/assets/10177602/e647a048-a09e-4dee-9969-916e7f6b9aa8">

**Comment by roraback** [comment]
@flyinghermit what you have is quite close to what @rishibarbhaya-design designed back in April. Designs are here: https://www.figma.com/design/v6GunK50D2VC7w7I2FBDNf/Management?node-id=3958-12402&t=xDKXOK1N0shan8wF-1
