### ISSUE TITLE
TCP FIN Packets Missing While Using `tsh ssh -L`

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#3749]
### Description

**What happened**: 
When using `tsh ssh -L <local_port>:localhost:<remote_port> <user>@remote_server`, it seems that tcp fin packets are sent from client to the local port, but are not transmitted to the remote port on the remote server. 

**What you expected to happen**: 
tcp fin packets should be transmitted, so the remote server properly closes the connection. 

**How to reproduce it (as minimally and precisely as possible)**:

- On a Teleport node, connected to a Teleport cluster, run [server.py](https://gist.github.com/travelton/796d244880c52158da8155b571bd69d9#file-server-py). 
- On the client side, create a [client.py](https://gist.github.com/travelton/796d244880c52158da8155b571bd69d9#file-client-py).
- On the client side, run `tsh ssh -d -L 65432:localhost:65432 root@<remote_host>` and now execute `client.py`

- Observe that the server.py process did not terminate. The socket is still open waiting for fin packet.
- Remove Teleport from the equation... scp client.py to the remote machine. Run server.py and client.py and observe that server.py terminates properly. 

### Environment
- Teleport version (use `teleport version`): v4.2.9
- Tsh version (use `tsh version`): v3.2.14
- OS (e.g. from `/etc/os-release`): Client - Ubuntu 18.04, Server - Ubuntu 16.04.6

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP

**Relevant Debug Logs If Applicable**

tcpdump: https://gist.github.com/travelton/39b216602a34bf1229cad2b43d3272d3

**Comment by awly** [comment]
Still need to backport to 4.3 branch.
