### ISSUE TITLE
Bash/ZSH Shell Completion

### ISSUE THREAD

**Issue by dkalashnik** [gravitational/teleport#3753]
### Feature Request
Add bash-completion to tsh command

### Motivation
With tons configured clusters/nodes it makes switch much easier
Original kingpin has that feature: https://github.com/alecthomas/kingpin#bashzsh-shell-completion

### Who's it for?
All: OSS User, Pro, Enterprise

**Comment by keenan-v1** [comment]
This is something I find myself wishing Teleport had whenever I use it. As an enterprise user with a lot of nodes, I really hope it gets some traction soon.

**Comment by steveberryman** [comment]
This is very much not perfect, but fits my needs. It's a zsh completion script for `tsh`. It doesn't cover db's or k8s but will do completion for most options and user/nodes for ssh and scp.

https://gist.github.com/steveberryman/94beb6d8ebc1917e0e381943db257235

You can source it from a .zshrc, or add it to oh-my-zsh plugins or whatever :)

**Comment by dragonlobster** [comment]
> steveberryman

i need one for DBs

**Comment by gzdunek** [comment]
We have updated kingpin version that our CLI tools use and enabled autocompletion for commands and flags.
* https://github.com/gravitational/teleport/pull/26238
* https://github.com/gravitational/teleport/pull/26596

It was backported to v13, v12 and v11.

**Comment by gzdunek** [comment]
That's correct, for now we have added completion only for commands/subcommands/flags, not cluster resources.

**Comment by KasperSkytte** [comment]
> That's correct, for now we have added completion only for commands/subcommands/flags, not cluster resources.

Then this must be reopened. The FR was for autocompleting hostnames just like regular `ssh` does. Though both types of autocompletion is nice to have

**Comment by PeaStew** [comment]
How can this be closed without a solution to the original request?

**Comment by pradcliffe-ns** [comment]
Please reopen this issue and give us hostname completion.

**Comment by phsee-ppi** [comment]
I've written a fish shell function to allow logging into clusters using [fzf](https://github.com/junegunn/fzf):

```fish
function tp  
  set -f cluster (tsh kube ls | tail -n +3 | cut -d " " -f 1 | fzf)
  tsh kube login "$cluster"
end
```

And for bash:
```bash
function tp() {
    cluster=$(tsh kube ls | tail -n +3 | cut -d " " -f 1 | fzf)
    tsh kube login "$cluster"
}
```

**Comment by anilanar** [comment]
I recreated this issue here: https://github.com/gravitational/teleport/issues/38965. Feel free to migrate your thumb ups! 👍

**Comment by anilanar** [comment]
This is "reopened", see #30175  for the new issue.
