### ISSUE TITLE
Provide more information on windows tsh status

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3758]
### Feature Request
On windows inform the user they need to provide the proxy if not given.  Currently if they enter  `tsh status` without a proxy they get `Not logged in`.  

### Motivation
Users can get confused they are not logged in since the proxy is not required in other environments.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by webvictim** [comment]
Also, running `tsh status` on Windows when not logged in currently generates no output:

```
C:\Users\Gus\Desktop>.\tsh.exe version
Teleport v7.0.0-dev git:v6.0.0-alpha.2-241-gf9997ab8c go1.15.5

C:\Users\Gus\Desktop>.\tsh.exe status

C:\Users\Gus\Desktop>
````

**Comment by stevenGravy** [comment]
Fixed in latest tsh.exe
