### ISSUE TITLE
teleport will not let user defined in ldap to login

### ISSUE THREAD

**Issue by gkappel** [gravitational/teleport#376]
Using latest git checkout

If I create a local user on destination machine I can login with tsh, but with a user defined in ldap tsh does not work

./tsh --proxy=teleportstaging --user=george --login george ls 
Enter password for george:
Enter your HOTP token:
Node Name                  Node ID                                  Address              Labels
---------                  -------                                  -------              ------
AppAPI_i-5cd7c4fd     44f63c87-59a3-4a61-85d2-65a7a2133f71     172.31.0.55:3022     role=AppAPI,uptime=20:36:52 up 243 days,  5:32,  4 users,  load average: 0.00, 0.01, 0.05
ip-172-31-0-10             93f71593-a662-4d46-834b-deded1c6cc20     172.31.0.10:3022 

./tsh --proxy=teleportstaging --user=george --login george ssh AppAPI_i-5cd7c4fd
ERROR: cannot determine shell for george
ERROR: ssh: could not start shell

Verified following on AppAPI_i-5cd7c4fd as well as logging in directly via ssh
$ getent passwd george
george:*:10000:10000:George Kappel:/home/george:/bin/bash

$ id george
uid=10000(george) gid=10000(sysadmins) groups=10000(sysadmins)

From teleport log on AppAPI_i-5cd7c4fd

INFO[0092] [::]:3022 accepted connection from 172.31.0.10:45547  file=sshutils/server.go:156
INFO[0092] conn(172.31.0.10:45547->172.31.0.55:3022, user=george) auth attempt with key ssh-rsa e8:6a:83:ba:f2:a8:d0:0b:b4:9a:d6:96:ee:4a:
c5:a9  file=srv/sshserver.go:457
WARN[0092] server doesn't support provided key type      file=srv/sshserver.go:468 fingerprint=ssh-rsa e8:6a:83:ba:f2:a8:d0:0b:b4:9a:d6:96
:ee:4a:c5:a9 local=172.31.0.55:3022 remote=172.31.0.10:45547 user=george
INFO[0092] conn(172.31.0.10:45547->172.31.0.55:3022, user=george) auth attempt with key ssh-rsa 62:6a:b3:45:53:5b:94:fa:c3:3a:3e:6c:43:95:
33:81  file=srv/sshserver.go:457
WARN[0092] server doesn't support provided key type      file=srv/sshserver.go:468 fingerprint=ssh-rsa 62:6a:b3:45:53:5b:94:fa:c3:3a:3e:6c
:43:95:33:81 local=172.31.0.55:3022 remote=172.31.0.10:45547 user=george
INFO[0093] [::]:3022 accepted connection from 172.31.0.10:45548  file=sshutils/server.go:156
INFO[0093] conn(172.31.0.10:45548->172.31.0.55:3022, user=george) auth attempt with key ssh-rsa-cert-v01@openssh.com 87:c2:28:6b:89:3f:cf:
19:70:80:bb:4a:e0:76:ba:00  file=srv/sshserver.go:457
INFO[0093] new ssh connection 172.31.0.10:45548 -> 172.31.0.55:3022 vesion: SSH-2.0-Go  file=sshutils/server.go:202
INFO[0094] opened session channel                        component=node fields=map[id:1 local:172.31.0.55:3022 remote:172.31.0.10:45548 lo
gin:george teleportUser:george] file=srv/sshserver.go:595
INFO[0094] dispatch(req=env, wantReply=true)             component=node fields=map[local:172.31.0.55:3022 remote:172.31.0.10:45548 login:g
eorge teleportUser:george id:1] file=srv/sshserver.go:645
INFO[0094] handleEnv(sshutils.EnvReqParams{Name:"TELEPORT_SESSION", Value:"16e225a0-08cc-11e6-b9f7-3c07545f067b"})  component=node fields=map[teleportUser:george id:1 local:172.31.0.55:3022 remote:172.31.0.10:45548 login:george] file=srv/sshserver.go:758
INFO[0094] setEnv(TELEPORT_SESSION=16e225a0-08cc-11e6-b9f7-3c07545f067b)  component=node fields=map[local:172.31.0.55:3022 remote:172.31.0.10:45548 login:george teleportUser:george id:1] file=srv/ctx.go:189
INFO[0094] dispatch(req=env, wantReply=true)             component=node fields=map[remote:172.31.0.10:45548 login:george teleportUser:george id:1 local:172.31.0.55:3022] file=srv/sshserver.go:645
INFO[0094] handleEnv(sshutils.EnvReqParams{Name:"LANG", Value:"en_US.UTF-8"})  component=node fields=map[local:172.31.0.55:3022 remote:172.31.0.10:45548 login:george teleportUser:george id:1] file=srv/sshserver.go:758
INFO[0094] setEnv(LANG=en_US.UTF-8)                      component=node fields=map[login:george teleportUser:george id:1 local:172.31.0.55:3022 remote:172.31.0.10:45548] file=srv/ctx.go:189
INFO[0094] dispatch(req=pty-req, wantReply=true)         component=node fields=map[remote:172.31.0.10:45548 login:george teleportUser:george id:1 local:172.31.0.55:3022] file=srv/sshserver.go:645
INFO[0094] handlePTYReq()                                component=node fields=map[login:george teleportUser:george id:1 local:172.31.0.55:3022 remote:172.31.0.10:45548] file=srv/sshserver.go:764
INFO[0094] handlePTYReq(new terminal)                    file=srv/sshserver.go:784
INFO[0094] Parsed pty request pty(enn=xterm, w=138, h=40)  file=srv/term.go:71
INFO[0094] resizing terminal to TerminalParams(w=138, h=40)  file=srv/term.go:104
INFO[0094] notifyWinChange(16e225a0-08cc-11e6-b9f7-3c07545f067b)  file=srv/sess.go:108
INFO[0094] notifyWinChange: session 16e225a0-08cc-11e6-b9f7-3c07545f067b not found  file=srv/sshserver.go:792
INFO[0094] setTerm: &{{[0 0 0 0 0 0 0 0 0 0 0 0] 0} {0 0} 0xc820026878 0xc820026880 <nil> false {138 40}}  file=srv/ctx.go:136
INFO[0094] PTY allocated successfully                    component=node fields=map[login:george teleportUser:george id:1 local:172.31.0.55:3022 remote:172.31.0.10:45548] file=srv/sshserver.go:796
INFO[0094] dispatch(req=shell, wantReply=true)           component=node fields=map[local:172.31.0.55:3022 remote:172.31.0.10:45548 login:george teleportUser:george id:1] file=srv/sshserver.go:645
INFO[0094] joinShell(sid=16e225a0-08cc-11e6-b9f7-3c07545f067b)  component=node fields=map[local:172.31.0.55:3022 remote:172.31.0.10:45548 login:george teleportUser:george id:1] file=srv/sess.go:59
INFO[0094] setTerm: <nil>                                file=srv/ctx.go:136
ERRO[0094] cannot determine shell for george             file=srv/exec.go:154
INFO[0094] error dispatching request: &trace.TraceErr{Err:(*errors.errorString)(0xc82041d000), Traces:trace.Traces{trace.Trace{Path:"/home/ubuntu/go/src/github.com/gravitational/teleport/lib/srv/exec.go", Func:"github.com/gravitational/teleport/lib/srv.getLoginShell.func2", Line:117}, trace.Trace{Path:"/home/ubuntu/go/src/github.com/gravitational/teleport/lib/srv/exec.go", Func:"github.com/gravitational/teleport/lib/srv.prepareOSCommand", Line:155}, trace.Trace{Path:"/home/ubuntu/go/src/github.com/gravitational/teleport/lib/srv/sess.go", Func:"github.com/gravitational/teleport/lib/srv.(*session).startShell", Line:275}, trace.Trace{Path:"/home/ubuntu/go/src/github.com/gravitational/teleport/lib/srv/sess.go", Func:"github.com/gravitational/teleport/lib/srv.(*sessionRegistry).joinShell", Line:76}}, Message:"", DebugMessage:""}  component=node fields=map[remote:172.31.0.10:45548 login:george teleportUser:george id:1 local:172.31.0.55:3022] file=srv/sshserver.go:620
INFO[0094] closing session channel                       component=node fields=map[login:george teleportUser:george id:1 local:172.31.0.55:3022 remote:172.31.0.10:45548] file=srv/sshserver.go:599
INFO[0094] Terminal wait for copy to be over             file=srv/term.go:155
INFO[0094] Terminal copy is over                         file=srv/term.go:157

**Comment by gkappel** [comment]
I can get teleport to work with ldap users with the attached patch
[patch.txt](https://github.com/gravitational/teleport/files/234960/patch.txt)

**Comment by klizhentas** [comment]
@gkappel thanks for digging into this! We will look into the patch and get back to you!

**Comment by gkappel** [comment]
Any update on this?

**Comment by kontsevoy** [comment]
Reopening. That PR does not address LDAP case well.

**Comment by kontsevoy** [comment]
@gkappel your patch went into PR for review. Should be in master shortly and we'll cut a new release within a week. Thanks!
