### ISSUE TITLE
Design for selecting keyboard layouts for desktop access

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#37607]

**Comment by roraback** [comment]
Engineering isn't planning for Q1 anymore; not planned for Q2.

**Comment by zmb3** [comment]
This is now being tracked in #42691

**Comment by roraback** [comment]
Oh, good catch. I forgot that I'd moved this issue over to the "For Discussion" column. Thank you!

**Comment by rishibarbhaya-design** [comment]
Sample Screenshot

![image](https://github.com/gravitational/teleport/assets/88441969/00c335d0-4c75-4c91-814b-225a8e1f1dc1)
