### ISSUE TITLE
Local Terraform / Teleport terraform-identity fails with Teleport 15

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#37627]
Expected behavior:
Users can't `tctl auth sign --user=terraform --out=terraform-identity` when using Teleport 15, as you need to create a bot users instead. 

```
 tctl auth sign --user=terraform --out=terraform-identity
ERROR: access denied: impersonation is not allowed
```

> Ah sorry I was conflating Bots with Machine ID. Yes, you just need to create a bot user via tctl and impersonate. I'll make a pass through the plugin/integration docs to specify that bots should be used.
> P.S. I think we have been recommending bot users for several releases, but let me circle back and see if there is a better deprecation path we can take that won't break existing deployments. 

Current behavior:

```
 tctl auth sign --user=terraform --out=terraform-identity
ERROR: access denied: impersonation is not allowed
```

## Solutions:

Running ` tctl auth sign --user=terraform --out=terraform-identity` on the auth server, using Machine ID to obtain the cert. 

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
@rosstimothy @Joerger  this is what we discussed - we're just going to call this out as a breaking change in the release notes. 

Can you guys write up a quick description for me and I'll get it in the release notes?

**Comment by benarent** [comment]
> Can you guys write up a quick description for me and I'll get it in the release notes?

@zmb3 I don't think we ever posted an official FYI/How To for this.

**Comment by zmb3** [comment]
https://goteleport.com/docs/changelog/#mfa-for-administrative-actions

**Comment by thedevelopnik** [comment]
I'm going through Terraform set up for the first time right now, and I think the thing we need to connect in the docs somehow is that
* setting up with webauthn 2FA is kind of the default way Community gets set up (and others?)
* this breaks the Terraform tutorial where we link out to "we recommend machine id for CI servers" but the rest of the tutorial uses a user
* the only error you get is `ERROR: access denied: impersonation is not allowed` and `impersonation is not allowed` is nowhere in the docs
* now people are stuck and have to look for support on how to get started using Terraform

Maybe we just want to change the Terraform tutorial to tell people to use a bot?

**Comment by thedevelopnik** [comment]
Hey @gardar thanks for the feedback. I agree and am owning updating this section of the docs. Aiming to have it done within a week or so.

**Comment by thedevelopnik** [comment]
@gardar I have a PR open now: https://github.com/gravitational/teleport/pull/39377
