### ISSUE TITLE
kubectl exec session with ELB not respecting keep-alives and session not in UI

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3765]
### Description
**What happened**:
ELBs have an idle timeout: https://aws.amazon.com/blogs/aws/elb-idle-timeout-control/
This issue addresses that: https://github.com/gravitational/teleport/issues/2334
However those configuration options seem to only apply to SSH sessions. If someone is kubectl exec’ing through an ELB the kubectl exec session will end depending on what the idle timeout is set to. If the kubectl exec session ends due to the timeout then there is not a recording that appears in the UI.

**What you expected to happen**:
kubectl exec session should not end and the session should be recorded and appear in the UI

**How to reproduce it (as minimally and precisely as possible)**:
Used this Helm Chart with an AWS ELB:
https://github.com/gravitational/teleport/tree/master/examples/chart/teleport

AWS ELB has an idle timeout so keep_alive_interval is set to a value less than the idle timeout. 

### Environment
image:
  repository: quay.io/gravitational/teleport-ent
  tag: 4.2.8

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190134506177097/1190159321022445) by [Unito](https://www.unito.io/learn-more)

**Comment by russjones** [comment]
Best: 3
Worst: 5

**Comment by awly** [comment]
https://github.com/kubernetes/kubernetes/pull/94170 has been merged.
Now we can just bump our vendored version and enable the SPDY pings.
