### ISSUE TITLE
Assist crashes when closing the sidebar. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#37657]
Expected behavior:

Current behavior:
Assist crashes when closing the sidebar. See Video. 

https://github.com/gravitational/teleport/assets/559288/9fceb321-20c0-4157-96b9-598a7c76b978

Bug details:
- Teleport version: 15.0.0
- Recreation steps: 
- Debug logs

**Comment by zmb3** [comment]
Looks like a duplicate of #36428.

@ryanclark didn't you fix this in #36794?

**Comment by ryanclark** [comment]
> @ryanclark didn't you fix this in #36794?

Yeah, at least I thought I did. I'll take a look in the morning, maybe I missed something

**Comment by ryanclark** [comment]
@benarent I've tried to reproduce this on a build of v15.0.1 and can't, could you please verify that it is still an issue?

**Comment by benarent** [comment]
yes, looks like it's fixed in 15.0.1, no longer an issue on my cluster
