### ISSUE TITLE
Ctrl+C/Ctrl+V doesn't copy/paste text in Connect on Windows

### ISSUE THREAD

**Issue by gzdunek** [gravitational/teleport#37650]
Ctrl+C/Ctrl+V is interpreted by `xterm.js` and doesn't work as copy/paste operations (Ctrl+V has to be confirmed, it worked on my machine).

To improve the UX, we should make Ctrl+C copy the text when something is selected https://github.com/xtermjs/xterm.js/issues/2478#issuecomment-1002371588. 
This should be done for Linux/Windows.

TBD how to handle Ctrl+V.

**Comment by zmb3** [comment]
It's pretty common for Windows terminals to _not_ treat ctrl+c as copy.

Another way to solve this would be to address #22828 (which is how PuTTY behaves, IIRC)
