### ISSUE TITLE
Implement approving root cluster's access to leaf cluster

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3767]
### Feature Request
A prospect has a database that they install on a VM image and they then share this image with a customer of theirs. Their customer then installs this image in their own environment. For example, this could be an AMI installed in their AWS account. If the customer who installed the image has an issue with the database, the prospect needs to be able to SSH into the machine to troubleshoot/fix the issue. This would be a trusted cluster setup. However, the prospect wants to be able to access their customers' clusters only once the customer has approved their access. Ideally the prospect would only be able to access their customers' clusters if at least two customer admins approve the access. 

Essentially trusted cluster with workflow approval.

### Who's it for?
Enterprise

**Comment by stevenGravy** [comment]
RBAC allows controlling access to trusted clusters.
