### ISSUE TITLE
Machine ID with Ansible doc needs CanonicalizeMaxDots in SSH config 

### ISSUE THREAD

**Issue by tenaciousdlg** [gravitational/teleport#37713]
## Applies To

https://goteleport.com/docs/machine-id/access-guides/ansible/#step-34-configure-ansible
## Details

In Section 3/4 there is an example `ansible.cfg` that contains the following as its last line.

```
ssh_args = -F /opt/machine-id/ssh_config -o CanonicalizeHostname=yes -o CanonicalDomains=example.com
```

Since `CanonicalizeMaxDots` is not listed here it defaults to `1` and can cause issues for nested subdomains as targets. For example `a.deep.sub.domain` would not run properly. This issue is a proposal to update the line to the following.

```
ssh_args = -F /opt/machine-id/ssh_config -o CanonicalizeHostname=yes -o CanonicalizeMaxDots=10 -o CanonicalDomains=example.com
```

## How will we know this is resolved?

Running the guide against any SSH node with a hostname similar to `ip-172-31-17-255.us-east-2.compute.internal` which contains multiple levels of subdomains. 

## Related Issues

None found

**Comment by strideynet** [comment]
It'd probably be simplest for us to revert https://github.com/gravitational/teleport/pull/29854/files and avoid using CanonicalizeHostname at all
