### ISSUE TITLE
Document Proxy Protocol

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3772]
For HA deployments, Teleport supports running components (auth and proxy) behind a load balancer. A downside to this is that the client IP address appears to be that of the load balancer and not of the client making the request.

To support propagating the client IP address, many load balancer support proxy protocol. [AWS](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol) and 
[GCP](https://cloud.google.com/load-balancing/docs/tcp/setting-up-tcp#proxy-protocol) both support PROXY protocol with minor configuration changes.

Once your load balancer supports proxy protocol, you can enable proxy protocol support in Teleport by setting the `proxy_protocol` variable for either auth or proxy service.

```
auth_service:
   proxy_protocol: on
```

```
proxy_service:
   proxy_protocol: on
```

**Comment by kgtw** [comment]
Current valid options in 4.2.9 are `on` & `off`

```
User Message: bad "proxy_protocol" parameter value: "yes", supported values are on or off
```

This breaks from the norm of other boolean options where you can also use `true`/`false` & `yes`/`no`

**Comment by webvictim** [comment]
For anyone else finding this issue in future, be advised that Teleport only currently supports PROXY protocol v1 (plain text version). It does not support protocol v2 (binary version). If you require support for PROXY protocol v2, please add a +1 on this issue: https://github.com/gravitational/teleport/issues/4904

**Comment by probakowski** [comment]
Teleport now supports PROXY v2 as well (https://github.com/gravitational/teleport/pull/11684)

**Comment by dboslee** [comment]
@zmb3 not sure I am the right person to answer that. Maybe you're mixing up proxy peering and proxy protocol?

**Comment by zmb3** [comment]
d'oh. of course. sorry!

**Comment by zmb3** [comment]
This is documented in the [IP pinning guide](https://goteleport.com/docs/access-controls/guides/ip-pinning/#observing-ips-through-load-balancers) as well as the config reference.
