### ISSUE TITLE
very slow and unstable connections when blocking traffic outside of our network

### ISSUE THREAD

**Issue by qwilbird** [gravitational/teleport#37745]
### Issue:
We are running currently blocking any non internal network traffic on the servers hosting the Auth & the Proxy applications. We are not really comfortable having a third party tool having access to all our servers allowed to connect outside of our network.

When we do not block non internal traffic, teleport (UI & ssh) is fast 
When we block non internal traffic, UI becomes very sluggish and ssh sessions are very slow.

### Expected:
- Teleport UI and SSH sessions should not be affected by lack of connectivity to the outside network.

**Comment by stevenGravy** [comment]
Please confirm your network traffic and the connectivity speed you are seeing.  Likely it was still traversing through the public connection before you blocked it. Teleport can operate on public, private and airgapped networks. There is a latency indicator in v14 and v15 you can see in SSH sessions in the upper right.

**Comment by stevenGravy** [comment]
![image](https://github.com/gravitational/teleport/assets/60704961/d938ec22-ba32-4faf-89fe-a50382986f67)

**Comment by stevenGravy** [comment]
Going to close this for now as would need specifics to look in further.  If you are still seeing issues please join the slack community at https://goteleport.com/community-slack/.
