### ISSUE TITLE
JSON_EQUALS error still showing up despite Teleport v15

### ISSUE THREAD

**Issue by greedybro** [gravitational/teleport#37748]
Hi @greedy52 

Following the merge of #36938, i still have the same error of teleport trying to use JSON_EQUALS function...
I updated teleport proxy, teleport on the mysql instance i'm trying to reach and teleport-connect to v15, but no changes.

Is there a cache somewhere in the chain that can explain why despite seeing no references of JSON_EQUALS on the teleport repo, it stills show in the logs ?

```
ERROR 1105 (HY000): your Teleport role requires automatic database user provisioning but an attempt to activate database user "test_db" failed due to the following error: ERROR 1305 (42000): FUNCTION teleport.JSON_EQUALS does not exist

ERROR REPORT:
Original Error: *exec.ExitError exit status 1
Stack Trace:
	github.com/gravitational/teleport/lib/client/db/dbcmd/error.go:58 github.com/gravitational/teleport/lib/client/db/dbcmd.ConvertCommandError
	github.com/gravitational/teleport/tool/tsh/common/db.go:810 github.com/gravitational/teleport/tool/tsh/common.onDatabaseConnect
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1426 github.com/gravitational/teleport/tool/tsh/common.Run
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:570 github.com/gravitational/teleport/tool/tsh/common.Main
	github.com/gravitational/teleport/tool/tsh/main.go:26 main.main
	runtime/proc.go:267 runtime.main
	runtime/asm_arm64.s:1197 runtime.goexit
```

**Comment by greedy52** [comment]
Hmm. This is weird. The stored procedures by default are installed in the `teleport` database and their versions are in the comment:
```sql
show procedure status where Db='teleport';
```

With the above fix, the Database Agent should automatically update the procedures to this version:
https://github.com/gravitational/teleport/blob/e126e8cd7165f26ab724aaa58f285120db8e38e5/lib/srv/db/mysql/autousers.go#L526-L528

You can force a procedure update by:
```
ALTER PROCEDURE teleport.teleport_activate_user COMMENT 'need update';
```
Then connect the auto-user from `tsh` again. Though this is usually not necessary as the auto-procedure-update should work on each new `tsh` connection.

I would also double-check the version of the Teleport Database Service on the MariaDB instance too and make sure the service is restarted.

**Comment by greedybro** [comment]
Thanks for your quick answer ! 

It turns out the service was not properly restarted after installation, so my bad. Sorry for that.
Closing the issue.
