### ISSUE TITLE
No Teleport 15 Images In ECR

### ISSUE THREAD

**Issue by tgoodsell-tempus** [gravitational/teleport#37813]
Expected behavior:
Expect to see `15.0.0` and `15.0.1` as tagged images in https://gallery.ecr.aws/gravitational/teleport-ent (and others).

Current behavior:
Do not see these images at all

**Comment by zmb3** [comment]
This is expected. See https://goteleport.com/docs/changelog/#container-images for details.

**Comment by tgoodsell-tempus** [comment]
> This is expected. See https://goteleport.com/docs/changelog/#container-images for details.

Woops, sorry for missing that.
