### ISSUE TITLE
Cannot connect to RDS Database Instance via GUI Client

### ISSUE THREAD

**Issue by r-aju** [gravitational/teleport#37811]
Expected behavior:
Connection to database via teleport using GUI Client.

Current behavior:
Heyy, I'm accessing the AWS RDS Instances using teleport and while proxying and connecting to RDS Instance via GUI Clients, I get the below error an random basis.

<img width="1130" alt="mysql-error" src="https://github.com/gravitational/teleport/assets/43216503/edc37f3a-63ca-4c64-a897-560b6aea450c">

Bug details:
- Teleport version -> 14.3.0
- Recreation steps
  Accessing database via teleport using GUI Client.
  
- Debug logs
```
2024-02-06T10:09:45Z ERRO [DB:PROXY]  Failed to handle database TLS connection. error:[
ERROR REPORT:
Original Error: *fmt.wrapError access denied without password
Stack Trace:
	github.com/gravitational/teleport/lib/srv/db/mysql/proxy.go:206 github.com/gravitational/teleport/lib/srv/db/mysql.(*Proxy).performHandshake
	github.com/gravitational/teleport/lib/srv/db/mysql/proxy.go:93 github.com/gravitational/teleport/lib/srv/db/mysql.(*Proxy).HandleConnection
	github.com/gravitational/teleport/lib/srv/db/proxyserver.go:356 github.com/gravitational/teleport/lib/srv/db.(*ProxyServer).handleConnection
	github.com/gravitational/teleport/lib/srv/db/proxyserver.go:305 github.com/gravitational/teleport/lib/srv/db.(*ProxyServer).ServeTLS.func1
	runtime/asm_arm64.s:1197 runtime.goexit
User Message: access denied without password] db/proxyserver.go:307
2024-02-06T10:10:01Z ERRO [DB:PROXY]  Failed to handle database TLS connection. error:[
ERROR REPORT:
Original Error: *fmt.wrapError access denied without password
Stack Trace:
	github.com/gravitational/teleport/lib/srv/db/mysql/proxy.go:206 github.com/gravitational/teleport/lib/srv/db/mysql.(*Proxy).performHandshake
	github.com/gravitational/teleport/lib/srv/db/mysql/proxy.go:93 github.com/gravitational/teleport/lib/srv/db/mysql.(*Proxy).HandleConnection
	github.com/gravitational/teleport/lib/srv/db/proxyserver.go:356 github.com/gravitational/teleport/lib/srv/db.(*ProxyServer).handleConnection
	github.com/gravitational/teleport/lib/srv/db/proxyserver.go:305 github.com/gravitational/teleport/lib/srv/db.(*ProxyServer).ServeTLS.func1
	runtime/asm_arm64.s:1197 runtime.goexit
User Message: access denied without password] db/proxyserver.go:307
```

**Comment by stevenGravy** [comment]
@r-aju which db gui client and target db are you using?

**Comment by r-aju** [comment]
Heyy @stevenGravy , GUI Client is Sequel Ace and the target DB is AWS RDS Instances.

The GUI client can be found [here](https://sequel-ace.com)

**Comment by r-aju** [comment]
So, I can connect to the database using the CLI, but while connecting to through the GUI Client it fails on intermittent basis

**Comment by stevenGravy** [comment]
There could be issues like networking as GUIs do more traffic then CLI. AS mentioned I would try another GUI like workbench to see if that's consistent or could just be an issue with that one. Typically any that support certs or direct connections are fine.

**Comment by r-aju** [comment]
sure, will check on this part
