### ISSUE TITLE
Passwordless audit events display undefined user

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#37826]
![image](https://github.com/gravitational/teleport/assets/39066650/0b78342b-2f03-4fd0-96b2-51f45f80c11a)

If it's not possible to discern the user responsible for the audit event due to the nature of passwordless we shouldn't include undefined in the messaging. If it's possible to get the user information we should populate the event appropriately.

**Comment by zmb3** [comment]
@codingllama this still seems to be an issue.

Here's a live cloud cluster provisioned today:

<img width="1072" alt="image" src="https://github.com/gravitational/teleport/assets/7527103/95198cd9-980d-4860-b058-c660983f2a4b">

**Comment by zmb3** [comment]
I do!

Here's the "authentication success"

```
{
  "challenge_allow_reuse": false,
  "challenge_scope": "CHALLENGE_SCOPE_PASSWORDLESS_LOGIN",
  "cluster_name": "feathers.cloud.gravitational.io",
  "code": "T1016I",
  "ei": 0,
  "event": "mfa_auth_challenge.validate",
  "mfa_device": {
    "mfa_device_name": "passwordless-device",
    "mfa_device_type": "WebAuthn",
    "mfa_device_uuid": "4d8737ed-0f17-46f3-b35c-ce45e130b849"
  },
  "success": true,
  "time": "2024-04-16T10:10:10.29Z",
  "uid": "e029a5d5-0113-42cb-bbb2-cb867994895a",
  "user_kind": 1
}
```

And here's the auth attempt:

```
{
  "challenge_allow_reuse": false,
  "challenge_scope": "CHALLENGE_SCOPE_PASSWORDLESS_LOGIN",
  "cluster_name": "feathers.cloud.gravitational.io",
  "code": "T1015I",
  "ei": 0,
  "event": "mfa_auth_challenge.create",
  "time": "2024-04-16T10:10:07.457Z",
  "uid": "50c05d2e-71c0-458f-9d3c-723679bcca43",
  "user_kind": 1
}
```

**Comment by codingllama** [comment]
Oh, nevermind, this is passwordless. Strictly speaking there is no user for "mfa_auth_challenge.create"; for "mfa_auth_challenge.validate" we do know the user, so that we could fix.

Let me see what I can do.
