### ISSUE TITLE
Datadog - Offical Teleport integration for metrics

### ISSUE THREAD

**Issue by ocient-jlarson** [gravitational/teleport#37847]
What would you like Teleport to do?
Teleport current exposes a Prometheus compatible endpoint that can be scraped for valuable insight to the inner workings of Teleport. Teleport should have an official Datadog integration, listed on their integrations page.

What problem does this solve?
Datadog can easily scrape the existing metrics endpoint. However these metrics are considered "custom" to Datadog and there is an additional cost associated with it. If there is an official integration, the metrics are not considered custom and it really is only the monthly cost of the agent. A huge win for Datadog/Teleport customers!

If a workaround exists, please include it.
The metric endpoint today IS compatible with Datadog, an official integration would significantly lessen the cost of Teleport monitoring.

**Comment by ocient-cliimatta** [comment]
Prometheus can be used for collecting the metrics, or a custom agent check can be created with Python if you need more checks than just metrics.

https://docs.datadoghq.com/developers/integrations/?tab=integrations

The important part is that the metric names are whitelisted with Datadog so they're no longer charged as custom metrics. 

Plus you get a nice Tile on Datadog's integrations page!

**Comment by benarent** [comment]
TIL: Integration Metrics are Free! This is news to me, and looks like it should be an easy lift. I'll follow up with Datadog integrations team.

**Comment by thedevelopnik** [comment]
@ocient-cliimatta @ocient-jlarson I've started work on this and wanted to ask some scoping questions. Are you monitoring all our kinds of access services (database, kubernetes, ssh, etc) or just the Auth/Proxy services. I think the long-term goal here would be to cover everything but if you're only actively monitoring a subset I can probably ship it faster. Thanks!

**Comment by thedevelopnik** [comment]
There is now an [official integration supported by Datadog](https://docs.datadoghq.com/integrations/teleport/)! Please submit feedback as you find it to them. I'll be working with their team to smooth out rough edges.
