### ISSUE TITLE
Adding node to cluster with CM

### ISSUE THREAD

**Issue by ktosiek** [gravitational/teleport#379]
There should be a way to add node to cluster without running it as a daemon, something like --stop-after-connect.
This way it would be easier to use tools like Ansible to initialize new nodes.

**Comment by kontsevoy** [comment]
Yes! It's in the works.

**Comment by jaxxstorm** [comment]
duplicate of #307 right?

**Comment by ktosiek** [comment]
Only of that comment, if anything: https://github.com/gravitational/teleport/issues/307#issuecomment-203286075 - this one is about passing the token to teleport, not about how long the token is valid (I'd be using Ansible and requesting the tokens seconds before using them, so I hadn't stumbled upon the timeout problem)

**Comment by kontsevoy** [comment]
yes, these two are expressing the same problem.
