### ISSUE TITLE
Incorrect audit log formatting for device trust events

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#37906]
Expected behavior: user can see important details about the event, like the username.

Current behavior:

<img width="1375" alt="image" src="https://github.com/gravitational/teleport/assets/158712/e45464bb-401b-4027-938e-d67364f6f191">

Repro:

Start storybook with:

```shell
> cd web
> yarn storybook
```

Then open `http://localhost:9002` and see [Audit] Tab -> [All Possible Events].

**Comment by Tener** [comment]
Spotted by accident while working on other events, thanks to the advice from @smallinsky https://github.com/gravitational/teleport/pull/37798#discussion_r1481390576

**Comment by codingllama** [comment]
"User [[object.Object]]" for sure seems wrong.

Would you expect to see the device asset tag in the event title? Like "User llama updated the device ABC123"?

**Comment by Tener** [comment]
Probably best to see what other events are doing here.

**Comment by codingllama** [comment]
@Tener you raised the issue, so I wanted to know what your expectation is. Other than the "User [[object.Object]]" part of the string, it's not clear to me what the desired outcome here is.

**Comment by Tener** [comment]
Well, probably the actual username, now that I look at it closer. There seems to be the field for that, not sure why it is showing as `[[object.Object]]`. Maybe this is just a test being incorrect?

**Comment by Tener** [comment]
Here is the test material:

```
{
    cluster_name: 'im-a-cluster-name',
    code: 'TV005I',
    device: {
      asset_tag: 'M2CQVQV64R',
      device_id: '99d39707-efdd-436c-94f3-6a1aeef1fbf2',
      os_type: 2,
    },
    ei: 0,
    event: 'device', // legacy event
    status: {
      success: false,
    },
    time: '2023-01-12T19:28:36.842Z',
    uid: '94d33b77-82cd-4558-8893-0320699bf755',
    user: {
      user: '3827e8ad-7cbe-4423-a80f-dfc89e83eb86.im-a-cluster-name',
    },
  },
```

Not sure what the reality is, whether it is indeed nested `user.user` or if the test data needs updating.

**Comment by codingllama** [comment]
Similar issue: #37826.

**Comment by zmb3** [comment]
Can we at least get a quick fix in for `User [[object.Object]]`? This looks unprofessional.

**Comment by codingllama** [comment]
I think this is only in the storybook, audit looks fine for me on both master and v15.0.1.

![image](https://github.com/gravitational/teleport/assets/12500300/85160515-d5ae-4337-b20d-05ce3718ef5f)

**Comment by codingllama** [comment]
Closing as a non-issue.
