### ISSUE TITLE
Invalid format error when using web login ssh field when username has dashes

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3790]
### Description

**What happened**: 
If you enter a ssh connect in the web 'login to ssh server field' that has a user  with dashes you get a "Invalid format error".  See attached image.
![userdasherror](https://user-images.githubusercontent.com/60704961/83429574-3ab43580-a402-11ea-9c24-4d1e021a75b3.png)

The same user can connect in the Login as dropwdown or the tsh ssh command.  In this example the ec2-user is a very common user in AWS. Other users such as root@machine connect cleanly.

**What you expected to happen**:
Connecting to ssh session as with other users.

**How to reproduce it (as minimally and precisely as possible)**:

Add a user 'ec2-user' on a node and have the login 'ec2-user' available for a teleport role.  Confirm able to open a ssh session via CLI tsh or the Login as dropdown.  Attempt to connect in the field by typing ec2-user@machinename

### Environment
- Teleport version (use `teleport version`): 4.2.10
- Tsh version (use `tsh version`): 4.2.10
- OS (e.g. from `/etc/os-release`): 18.04.4 LTS (Bionic Beaver)"

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
AWS, in a docker-compose env.

**Browser environment**
Chrome

- Browser Version (for UI-related issues): Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by benarent** [comment]
Can you try this on 4.3?

**Comment by webvictim** [comment]
![D6D68262-4D7E-49D5-A971-996DB279AF63](https://user-images.githubusercontent.com/897821/84767895-9ad1dc80-afa9-11ea-8a19-84c7b7a2648e.jpeg)

Same thing on 4.3

**Comment by webvictim** [comment]
Still an issue in latest 4.3.
