### ISSUE TITLE
`teleport-windows-auth-setup-v15.0.1-amd64.exe` install error

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#37942]
When attempting to run the `teleport-windows-auth-setup-v15.0.1-amd64.exe` installer I run into this error after selecting the certificate

![image](https://github.com/gravitational/teleport/assets/13578537/49adf718-a9a8-4196-ae55-02318fd989e9)

This occurred for me both with an older certificate I had already on the system, and with a recently exported one from a v15.0.1 instance. In case it's relevant, this was for an update, not a new install.

**Comment by zmb3** [comment]
User error.
