### ISSUE TITLE
Fix Event Handler service config

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#37967]
## Applies To

https://goteleport.com/docs/management/export-audit-events/splunk/#start-the-teleport-event-handler

## Details

The ExecStart command has a typo:
ExecStart=/usr/local/bin/teleport-event-handler start --config=/etc/teleport-event-handler.toml --teleport-refresh-enabled true

It should be: 
ExecStart=/usr/local/bin/teleport-event-handler start --config=/root/teleport-event-handler.toml --teleport-refresh-enabled=true

**Comment by stevenGravy** [comment]
Per this I think it's fine to have the `toml` file in `/etc` but we should probably have instructions to move it there prior to this section.

**Comment by zmb3** [comment]
Fixed in #38093
