### ISSUE TITLE
Pass more Teleport variable to PAM modules

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3797]
### Feature Request
Currently Teleport can only pass three variables to PAM modules:
https://gravitational.com/teleport/docs/features/ssh_pam/#creating-local-users-with-teleport

We would like to be able to pass claims from our identity provider to PAM modules, specifically a Unix userID so that users can be assigned specific UIDs.

### Motivation
This would provide greater flexibility when generating users on demand using PAM modules.

### Who's it for?
Enterprise

**Comment by jon-can** [comment]
See also https://github.com/gravitational/teleport/issues/3814

**Comment by stevenGravy** [comment]
@jon-can believe this can be closed with https://goteleport.com/docs/server-access/guides/ssh-pam/#get-and-set-environment-variables-for-pam-modules now available
