### ISSUE TITLE
Dynamically set sudo rules for users created via PAM modules

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3802]
### Feature Request
PAM modules can be used to dynamically create users on my behalf, however I would like to be able to give users several sudo rules as well (for instance, I'm allowed to sudo only on /opt/Dell/MegaRAID/MegaCLI).  These can be arbitrarily different per group.

I can effectively allow or deny access to servers arbitrarily using labels in a Teleport role, but once someone is in a server, Teleport does not handle the sudo rules for that person.

This is fine if everyone is coming in as, say, the centos, dev, devops, or other role-based user, but we lose some fine-grained control when using dynamic users - I would need some way to control an operations user on each of these nodes, to allow them to run whatever operating scripts.

That means I'd have to handle the operations user on individual nodes using config management or something.

### Who's it for?
Enterprise

**Comment by awly** [comment]
Theoretically, you should be able to do this via `pam_exec.so`.
For example, add `includedir /etc/sudoers.d` to `/etc/sudoers` and generate files in there for dynamic users from a `pam_exec.so` script.

Alternatively (and IMO preferably) sudo rules should be group-based and a PAM module should be adding dynamic users to system groups (based on roles).

What would your ideal UX be here? Where would these rules be specified?

**Comment by dampersand** [comment]
Chiming in on jon-can's note here - I think it would be ideal to calculate and control rules at the teleport cluster level, per user - such that dynamic user 'dampersand' would get different sudo rules than dynamic user 'awly', and then either user drags those sudo rules with them to any node they teleport to.

One possible UX implementation might be a 'sudo rulesets' section in teleport that can be attached to users the way that roles are attached to users.  One would hope they could be additive, or even possibly allowed on a per-label basis (i.e., a sudo ruleset that is applied to a 'qa_user' role.  Inside that ruleset might be a 'labels' section where a teleport admin could specify server labels like 'relaxed' or 'protected' or '*', and then specify rules under each label... '*':'sudo /opt/userScript.sh',  or 'relaxed':'sudo -i').  In this way, when a user teleports to a node, all sudo rules can be calculated taking into account 1) their roles, and 2) the node they are about to reach.

While you can definitely use pam_exec.so to include /etc/sudoers.d/$TELEPORT_USER , I don't see any way to edit those per-person rules (and as another consideration, I don't see a good way to have that sudoers ruleset expire, either, the way useradd -e can create an expiring dynamic user).

**Comment by jon-can** [comment]
See also https://github.com/gravitational/teleport/issues/3814

**Comment by benarent** [comment]
Another +1 for this from a call today, host per host integration.

**Comment by jon-can** [comment]
Another +1 from a different call today

**Comment by jon-can** [comment]
Another +1

**Comment by stevenGravy** [comment]
Available with `sudo` and auto create users https://goteleport.com/docs/server-access/guides/host-user-creation/
