### ISSUE TITLE
Auth Server with cache.enabled does not emit deleted access request events

### ISSUE THREAD

**Issue by marshall-lee** [gravitational/teleport#3806]
### Description

**What happened**:

While working on https://github.com/gravitational/teleport-plugins I updated the vendored Teleport version. After this, tests involving access request expiration started failing. I investigated the problem and found that 4e9eed9ac0e38d177a49877ca5c3944a29c9aeba commit brought the change. This commit affects the cache behavior so I tried to turn off the cache and then everything worked as before.

After 4e9eed9ac0e38d177a49877ca5c3944a29c9aeba with cache turned on I don't get `OpDelete` events anymore. The reason is that new fanout implementation doesn't treat `OpDelete` events as 'filterable'. Probably it's right but then behavior must be unified whether cache is enabled or disabled.

**What you expected to happen**:

I expect that it must either work as it worked before, or, with cache disabled, it must ignore `OpDelete` events too.

**How to reproduce it (as minimally and precisely as possible)**:

Start new watcher with `WatchEvents` grpc method with filter on pending requests.

cc @fspmarshall

**Comment by fspmarshall** [comment]
I found the offending line [here](https://github.com/gravitational/teleport/blob/4e9eed9ac0e38d177a49877ca5c3944a29c9aeba/lib/services/events.go#L69-L72):

```golang
// no filters currently match delete events
if e.Type != backend.OpPut {
	return false, nil
}

```

When we determine a match we should instead propagate the event assuming the caller will be able to determine if it is relevant.
