### ISSUE TITLE
Install macOS: tsh included in teleport package not signed 

### ISSUE THREAD

**Issue by itzsimpl** [gravitational/teleport#38077]
The Teleport installation links provided at https://goteleport.com/docs/installation/#macos, have non matching versions of tsh.  

Expected behavior:

Both links contain the same version of tsh (signed). 

Current behavior:

Currently the two packages contain different versions (one signed - [tsh](https://cdn.teleport.dev/tsh-15.0.1.pkg), one not [teleport](https://cdn.teleport.dev/teleport-15.0.1.pkg)). This results in different behaviour; with one TouchID works, with the other not. Having `tcl` of the same version already installed, installing the entire teleport package later will override the existing `tcl` and TouchID will stop working. There used to be a notification of the requirement to override with a signed version of `tsh`, but there isn't anymore, it is natural to assume both packages contain the same (signed) version of `tsh`.

**Comment by zmb3** [comment]
This is being tracked at #14006
