### ISSUE TITLE
Node identification of output on multi-node tsh ssh commands

### ISSUE THREAD

**Issue by sover02** [gravitational/teleport#3808]
### Feature Request
Currently, with multi-host command executions, there is no easy way to link the output of `tsh` with the node the command is run on.

Example - the output:
```
Running command on box-1:
[output from box-1]
Running command on box-2:
Running command on box-3:
[output from box-1]
[output from box-2]
[output from box-3]
[output from box-3]
[output from box-3]
```
makes it hard to determine which box sent which output.

### Motivation
Our users love that they can leverage multi-tsh ssh commands based on roles instead of developing one-off ansible commands and bash scripts, but this limits that use case to some extent.

They can currently do some bash hackery to make the output from the nodes self-identify, but it would be advantageous and encourage this use case if there was a more elegant/native solution built into `tsh`.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by zmb3** [comment]
This is tracked at #6635 now.
