### ISSUE TITLE
charts/teleport-cluster: configurable podSecurityContext

### ISSUE THREAD

**Issue by AuditeMarlow** [gravitational/teleport#38138]
I'd like to be able to configure the pod security context for the auth and proxy deployments. In restrictive environments this could be helpful where for example the container user does not have write permissions on pod volumes by default and requires to set the `fsGroup` parameter in the pod security context.

**Comment by hugoShaka** [comment]
Blosed by https://github.com/gravitational/teleport/pull/40945
