### ISSUE TITLE
Create Teleport PAM module

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3814]
### Feature Request
More and more customers are asking for Teleport to be able to easily create OS users and groups on their SSH servers. Customers don't want to have to maintain scripts in order to make our current PAM integration instructions work. Okta ASA is able to do this much easier, for example, dynamically assign sudo permissions:
https://help.okta.com/asa/en-us/Content/Topics/Adv_Server_Access/docs/sudo-entitlements.htm

Here are two tickets currently open related to greater PAM capabilities:
https://github.com/gravitational/teleport/issues/3802
https://github.com/gravitational/teleport/issues/3797

### Who's it for?
OSS User, Pro, Enterprise

**Comment by russjones** [comment]
Best: 10
Worst: 20

**Comment by stevenGravy** [comment]
@jon-can believe this can be closed with https://goteleport.com/docs/server-access/guides/host-user-creation/

**Comment by srelf-eschercloud** [comment]
@stevenGravy Whilst the host-user-creation stuff is good, it forces you into ephemeral users, and sometimes you really need your history and home directory to persist between access to nodes.
