### ISSUE TITLE
Document `--[no-]fips` flag in the tbot CLI reference

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#38141]
## Applies To

`/docs/pages/reference/cli/tbot.mdx`

## Details

The document lacks use of tbot start flag: `--[no-]fips`.

## How will we know this is resolved?

The reference contains an entry for these flags.

**Comment by zmb3** [comment]
Did you link to the wrong page? I'm not sure I'd expect the GCP helm guide to mention tbot.
