### ISSUE TITLE
[v.15.x] /docs/pages/installation.mdx

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#38144]
## Applies To

https://goteleport.com/docs/installation/#linux
## Details

We provide Note to replace ID but I believe this is also referring to the %{_arch} variable when using command: 

sudo yum-config-manager --add-repo "$(rpm --eval "https://yum.releases.teleport.dev/$ID/$VERSION_ID/Teleport/%{_arch}/stable/v15/teleport.repo")"

It would be helpful to mention this in that note.

**Comment by stevenGravy** [comment]
That's using a built-in `rpm` macro that retrieves the system architecture. So we could say it will retrieve the repo based on version and system architecture.
