### ISSUE TITLE
User Events are missing the user field 

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#3816]
Currently, we are unable to capture the user who modifies resources because current API does not accept/pass around context objects through the `auth_with_roles` layer. Below are list of operations that contain `unimplemented` as a placeholder for users:

![image](https://user-images.githubusercontent.com/7816406/84207414-52815e80-aa7f-11ea-86cd-045682b66679.png)

### Roles [enterprise]
- [ ] GenerateToken
- [ ] DeleteRole
- [ ] upsertRole

### Auth Connectors
- [ ] upsertGithubConnector
- [ ] deleteGithubConnector
- [ ] UpsertOIDCConnector
- [ ] DeleteOIDCConnector
- [ ] UpsertSAMLConnector
- [ ] DeleteSAMLConnector

### Trusted Cluster
- [ ] UpsertTrustedCluster
- [ ] DeleteTrustedCluster

### References 
https://github.com/gravitational/teleport/issues/2989
https://github.com/gravitational/teleport/pull/3710
https://github.com/gravitational/teleport/pull/3714
https://github.com/gravitational/teleport/pull/3719
https://github.com/gravitational/teleport/pull/3733
https://github.com/gravitational/teleport/pull/3736
https://github.com/gravitational/teleport.e/pull/136

**Comment by alex-kovoy** [comment]
@kimlisa can we close this one?
