### ISSUE TITLE
Switching between light/dark themes causes appearance issues

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#38170]
Expected behavior:
When switching between them and hovering over resources the theme switches as well.

Current behavior:
When switching between themes it appears sometime the hover over color isn't changing and doesn't get fixed until a refresh of the website. 

![Screenshot 2024-02-13 at 2 38 00 PM](https://github.com/gravitational/teleport/assets/51385814/52191a80-ca19-42e2-b562-c44c21a962fd)
![Screenshot 2024-02-13 at 2 35 18 PM](https://github.com/gravitational/teleport/assets/51385814/f4fffb65-6606-4e94-83b6-891f49c88404)

Bug details:
- Teleport version: v15.0.1
- Recreation steps: 

start on dark theme --> light theme (it’s ok) --> back to dark theme and flashbang (when hovering over a resource)
start on light theme --> switch to dark (its ok) --> back to light and darkness (when hovering over a resource)

- Debug logs

**Comment by zmb3** [comment]
I'm not able to reproduce. Mind capturing a short video?

**Comment by gzdunek** [comment]
It affects Connect too, I will push a fix tomorrow.
For some reason, two classes are generated [for the hovered element](https://github.com/gravitational/teleport/blob/3983f88d5d85478ec248cf2978784aceaf642a39/web/packages/shared/components/UnifiedResources/CardsView/ResourceCard.tsx#L292):

<img width="407" alt="image" src="https://github.com/gravitational/teleport/assets/20583051/5a65a15e-b98e-4ecd-962a-2ffe325e8e97">

and the incorrect one wins.
