### ISSUE TITLE
4.3.0-alpha.1 build failures.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3818]
It looks like builds appear to be failing due to lack of access to `webassets.e` on the build box. See 
https://jenkins.gravitational.io/view/Publishing/job/TeleportPublish/440/console.

**Comment by webvictim** [comment]
The FIPS Docker image built fine after clearing the cached buildbox image from the Jenkins server. `docker rmi gravitational/teleport-buildbox-fips:go1.13.2` for future reference.

**Comment by webvictim** [comment]
Fixed by https://github.com/gravitational/ops/pull/160 and https://github.com/gravitational/ops/pull/161.
