### ISSUE TITLE
Where is Slack plugin / no-code integration with Teleport 15 ent

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#38180]
Expected behavior:
Have a Slack integration type as a card, or a no-code integration card.

Current behavior:

I'm missing Slack for my Teleport Enterprise Account, it shows up for Teleport Team/Cloud.

<img width="1505" alt="image" src="https://github.com/gravitational/teleport/assets/559288/e66c126d-0cd3-42e8-ac35-afc6b7a251ff">

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
_Hosted_ plugins require Teleport Cloud right now.

**Comment by benarent** [comment]
> _Hosted_ plugins require Teleport Cloud right now.

In that case, shouldn't AWS ODIC be the only card visible for Enterprise users and the rest of these cards should link to docs under self-hosted plugins

**Comment by zmb3** [comment]
See #30137 where we're tracking moving hosted plugins into self-hosted teleport. As you can see, most of them are completed but Slack has not been done yet.
