### ISSUE TITLE
Teleport does not show all sessions

### ISSUE THREAD

**Issue by soemeier** [gravitational/teleport#3820]
### Description

I have a teleport installation, that is deployed on AWS with dynamodb. After running a couple of ansible scripts the new sessions that I created where not visible anymore in the UI. If I search manually in the dynamodb I can find them.

I would have expected to see those sessions or at least see a warning that not all sessions are displayed.

How to reproduce:
run an ansible script like the following:

```- hosts: all
  gather_facts: no
  vars:
  tasks:
    - shell: echo test
      loop: "{{ range(1,1000) | list }}"  
```
After that login with tsh to one of your nodes. You are now able to see that session as active session. After you logout you can't find it anymore.

I assume this is due to the fact that the dynamo db does only return a certain number of rows and there is no proper pagination implemented in the WEB GUI. Also it would help if I could change the time period of session

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v4.2.10git:v4.2.10-0-g7fd6c7348 go1.13.2
- Tsh version (use `tsh version`): Teleport v4.2.10 git:v4.2.10-0-g7fd6c7348 go1.13.2
- OS (e.g. from `/etc/os-release`): CentOS Linux 7 (Core)

- Where are you running Teleport? AWS:

**Browser environment**

- Browser Version (for UI-related issues): Chrome 83.0.4103.61

**Comment by alex-kovoy** [comment]
A dup of https://github.com/gravitational/teleport/issues/4977

**Comment by zmb3** [comment]
Fixed in https://github.com/gravitational/teleport/pull/5420
