### ISSUE TITLE
external access not working (cloudlfare)

### ISSUE THREAD

**Issue by twf0** [gravitational/teleport#38242]
I have access with https://<ip>:9999 but not with the domain name.
I have a A DNS record (in cloudflare) pointing to the teleport server.
No firewall or NAT problems.
My config :

version: v3
teleport:
  nodename: xxx
  data_dir: /var/lib/teleport
  log:
    output: xxx
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: xxx.fr
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:9999
  public_addr: tp.xxx.fr:9999
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "no"
    email: user@example.com

Bug details:
- Teleport version : Teleport v15.0.1 git:v15.0.1-0-gd347510 go1.21.6

Someone have any idea ?

**Comment by stevenGravy** [comment]
This is likely due to cloudflare support of connection upgrades. Please take a look at https://github.com/gravitational/teleport/issues/30493. Recommend further discussion in the community slack or discussion.

**Comment by twf0** [comment]
Thanks for your reply, so for the moment cloudflare is not compatible with teleport ?

**Comment by stevenGravy** [comment]
Not for TLS routing which is the multiplex mode.

**Comment by twf0** [comment]
I tried to put the proxy_listener_mode in separate mode, same issue...

**Comment by stevenGravy** [comment]
Please post this in the slack community or in GitHub discussion to continue.

**Comment by evrynet1** [comment]
@twf0 CF only supports 443/80 so you should run teleport on 433 instead of 9999 and make sure you have a valid SSL cert set as well and then it will work with multiplexing too.

**Comment by Anmirazik** [comment]
@evrynet1 could you pls share your config files ? Im running teleport using cloudflare tunnel and haven't been able to make it work yet ... Are you using CF tunnel as well ?
