### ISSUE TITLE
Connect button doesn't display a username if there's only one user available

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3828]
**What happened**: In Teleport <4.3 you could connect to a node with one click from the UI view (by clicking the username in the UI).

![2020-06-11-163017__98x66__maim](https://user-images.githubusercontent.com/897821/84430955-dc0c6a00-ac00-11ea-97c9-73549e10fc3d.png)

In Teleport 4.3 this takes two clicks, one click on "Connect" to open the box:

![2020-06-11-162021__162x286__maim](https://user-images.githubusercontent.com/897821/84430996-efb7d080-ac00-11ea-897b-f62519313dad.png)

...then one click on the username.

![2020-06-11-162025__369x373__maim](https://user-images.githubusercontent.com/897821/84431018-f8a8a200-ac00-11ea-8926-83476c510144.png)

**What you expected to happen**: It should take the same number of clicks to start a session on a node from the web UI.

**How to reproduce it (as minimally and precisely as possible)**: As above

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-alpha.1git:v4.3.0-alpha.1-0-gd82e16ed0 go1.13.2`

**Comment by alex-kovoy** [comment]
This is by design.

**Comment by webvictim** [comment]
Maybe it is, but customers are used to using the old way and they will complain.

**Comment by alex-kovoy** [comment]
This is by design :-) Meaning that this per @benarent and @alexwolfe  requirements.

**Comment by webvictim** [comment]
Understood. Thank you for the call and explanation.
