### ISSUE TITLE
Update description of how we calculate TPRs

### ISSUE THREAD

**Issue by twakes** [gravitational/teleport#38293]
## Applies To

https://goteleport.com/docs/usage-billing/

## Details

We need to change the description of how we measure TPRs to reflect the change to using daily averages. Below is the language that needs to be replaced and the new language:

Existing:
~~We aggregate TPRs over each monthly period, starting on the subscription start date and ending on each monthly anniversary thereafter.~~

New:
We aggregate TPRs on a daily basis and use the average of those daily sums to determine the amount of TPRs for each monthly period, which starts on the subscription start date and ends on each monthly anniversary thereafter.

@zmb3 Can you coordinate this update when the change in calculation is pushed? Also, let me know if you disagree with the new language.

cc/ @TMG63

**Comment by zmb3** [comment]
This work is already underway and I'm tracking it over at gravitational/cloud#7588.

The language you have here looks fine to me, I'll move that over the existing issue and close this one out.
