### ISSUE TITLE
Invalid profiles cause `tsh status` to fail

### ISSUE THREAD

**Issue by arsenetar** [gravitational/teleport#38302]
Expected behavior:
Adding a config file with entries does not break operation of tsh commands, especially those that did not have any configuration applied.

Current behavior:
Adding an aliases section to a new config file results in errors from some commands, the config followed one of the examples from https://goteleport.com/docs/connect-your-client/tsh/#aliases.  When the config contained:
```yaml
aliases:
    "l": "tsh login --auth=okta"
```
Commands such as `tsh login`, `tsh status` returned an error:
```
ERROR REPORT:
Original Error: *trace.BadParameterError key index field Username is not set
Stack Trace:
        github.com/gravitational/teleport/lib/client/interfaces.go:64 github.com/gravitational/teleport/lib/client.KeyIndex.Check
        github.com/gravitational/teleport/lib/client/keystore.go:311 github.com/gravitational/teleport/lib/client.(*FSKeyStore).GetKey
        github.com/gravitational/teleport/lib/client/client_store.go:95 github.com/gravitational/teleport/lib/client.(*Store).GetKey
        github.com/gravitational/teleport/lib/client/client_store.go:166 github.com/gravitational/teleport/lib/client.(*Store).ReadProfileStatus
        github.com/gravitational/teleport/lib/client/client_store.go:226 github.com/gravitational/teleport/lib/client.(*Store).FullProfileStatus
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:3942 github.com/gravitational/teleport/tool/tsh/common.(*CLIConf).FullProfileStatus
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:4295 github.com/gravitational/teleport/tool/tsh/common.onStatus
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:1354 github.com/gravitational/teleport/tool/tsh/common.Run
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:558 github.com/gravitational/teleport/tool/tsh/common.Main
        github.com/gravitational/teleport/tool/tsh/main.go:24 main.main
        runtime/proc.go:267 runtime.main
        runtime/asm_amd64.s:1650 runtime.goexit
User Message: GetKey with CertOptions requires a fully specified KeyIndex
        key index field Username is not set
```

Bug details:
- Teleport version 14.3.4
- Recreation steps
  1. Create config as mentioned
  2. Run `tsh status`
  3. Observe error

**Comment by zmb3** [comment]
I'm not able to reproduce this. Based on the error, it doesn't look related to aliases at all - it seems your tsh profile is corrupt and somehow missing the `user` field.

Can you try wiping out `~/.tsh` or pointing `$TSH_HOME` at a new directory and see if you get the same error?

**Comment by arsenetar** [comment]
Wiping out the profile produced the same behavior after re-adding the config.  Removing the config corrects the issue.

**Comment by arsenetar** [comment]
The `user` field is also set in the profile file for the current_profile

**Comment by arsenetar** [comment]
Looking at code: https://github.com/gravitational/teleport/blob/80b0912edf5a4a07c820d18d19b635cf779f8797/tool/tsh/common/tshconfig.go#L40C24-L40C30
Moving the config to `~/.tsh/config/config.yaml` fixed this I must have missed the need for the sub config dir.

**Comment by zmb3** [comment]
Good find. I can reproduce the error by putting config.yaml in the wrong place too. We will fix that up.

**Comment by arsenetar** [comment]
Perhaps a better error to make that more clear to someone who makes that mistake would be nice or maybe an output like `invalid profile in file ...` or similar?
