### ISSUE TITLE
Session duration doesn't display correctly in the web UI

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3830]
**What happened**: Session duration under audit log displays "not implemented" in the new UI.

![2020-06-11-162111__277x389__maim](https://user-images.githubusercontent.com/897821/84431515-ca779200-ac01-11ea-9bf7-1cceac28f023.png)

Under the old UI this was a useful value:

![2020-06-11-164655__1059x79__maim](https://user-images.githubusercontent.com/897821/84432464-36a6c580-ac03-11ea-95a1-7a46243002ca.png)

**What you expected to happen**: Either this field should be removed, or it should display a useful value.

**How to reproduce it (as minimally and precisely as possible)**: As above

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-alpha.1git:v4.3.0-alpha.1-0-gd82e16ed0 go1.13.2`

**Comment by alex-kovoy** [comment]
This is a dup of https://github.com/gravitational/teleport/issues/3542

**Comment by alex-kovoy** [comment]
This has been fixed (we removed the sessions tab and show the duration as part of the session.end event description)
