### ISSUE TITLE
TouchID not accepted for MFA Admin actions in CLI

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#38316]
Expected behavior:

MFA confirmation is uniform in Web UI and CLI for admin actions.

Current behavior:

TouchID is accepted in Web UI for confirming admin actions.

 In CLI without a YubiKey being plugged in the user will get this error. No YubiKey is required to be plugged in for WebUI.

```bash
This is an admin-level action and requires MFA to complete
ERROR: failed to authenticate using available MFA devices
	Webauthn authentication failed
	no security keys found
```

Bug details:
- Teleport version: 15.0.1
- Recreation steps

1. Register a user with administrative access such as `editor` role
2. Register a touchid in CLI and Web UI as a MFA
3. Attempt to do a admin action such as `tctl users add --roles=access test`

**Comment by zmb3** [comment]
This is expected at this point. We'd need to ship a signed and notarized version of tctl, which is something we only do for tsh right now.
