### ISSUE TITLE
If you start a session then go back to the dashboard, there is no way to get back to the session view

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3831]
**What happened**: When returning to the dashboard in the 4.3 UI, the session stays connected but there is no obvious way to get back to to your running session.

![2020-06-11-162130__1591x246__maim](https://user-images.githubusercontent.com/897821/84432157-cf891100-ac02-11ea-8f6d-84b8bacf4d2b.png)

I'm not sure whether using the "join session" button at the right hand side connects a second client or not. If it doesn't (and resumes your old session) then the text should say "resume session" or something.

It does currently appear that it connects multiple users:

![2020-06-11-164633__917x100__maim](https://user-images.githubusercontent.com/897821/84432971-f431b880-ac03-11ea-9a2f-def553d757de.png)

It also isn't very obvious that you can click on the little terminal icon at the left-hand side of the row to do the same thing.

Maybe we should have a "return to active sessions" button somewhere at the top of the UI?

**What you expected to happen**: There should be an easy way to get back to the terminal view if you go back to the dashboard using the ... button at the top right.

![2020-06-11-162137__276x130__maim](https://user-images.githubusercontent.com/897821/84432275-f9dace80-ac02-11ea-9f7b-0d6cd459e217.png)
 
**How to reproduce it (as minimally and precisely as possible)**: As above.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-alpha.1git:v4.3.0-alpha.1-0-gd82e16ed0 go1.13.2`

**Comment by alex-kovoy** [comment]
> What you expected to happen: There should be an easy way to get back to the terminal view if you go back to the dashboard using the ... button at the top right.

Once you close/leave your terminal you cannot get back to it. This is by design (the same in 4.2).

**Comment by webvictim** [comment]
If the session ends and is exited when you click the button to go back to the dashboard, we should make this clear. There is no way to do this in 4.2 other than clicking the back button or closing the tab (which generates a warning)

**Comment by webvictim** [comment]
@alex-kovoy This is also even more relevant given the conversation we just had - say you have 5 tabs open and you go back to the dashboard, you will lose all your tabs. This is a weird experience as it doesn't say "close all sessions and return to dashboard" or something.
