### ISSUE TITLE
Session playback from audit log fails in some cases

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3833]
**What happened**: Attempting to playback some session entries in the audit log seems to fail because the files they're associated with can't be found.

![2020-06-11-164226__1231x1294__maim](https://user-images.githubusercontent.com/897821/84433112-2fcc8280-ac04-11ea-9787-bfab1c34a6ca.png)

The URL clicked to get here was https://example-main.gravitational.co:3080/web/cluster/gustest-main.gravitational.co/session/b5aaf9f4-ac18-11ea-958d-662a7f37020d/player

This was the corresponding entry in the audit log:

![2020-06-11-165504__912x59__maim](https://user-images.githubusercontent.com/897821/84433205-4ffc4180-ac04-11ea-86c5-f33898c44e20.png)

**What you expected to happen**: All events displayed should play back correctly, or be hidden.

**How to reproduce it (as minimally and precisely as possible)**: As above.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-alpha.1git:v4.3.0-alpha.1-0-gd82e16ed0 go1.13.2`

**Comment by russjones** [comment]
@webvictim Do you have reproduction steps for this on a fresh cluster?
