### ISSUE TITLE
Confusing experience when closing all tabs

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3834]
**What happened**: After you close all the tabs in console view, you are greeted with this screen:

![2020-06-11-162150__470x466__maim](https://user-images.githubusercontent.com/897821/84433379-8afe7500-ac04-11ea-9e65-c62c075cb2b2.png)

It isn't super obvious that you need to go to the top right, click the three dots and go to "Dashboard" to get back to sanity.

Pressing escape also doesn't work, which I would expect it to (when there are no sessions open at least)

**What you expected to happen**: We should just close this page and take you back to the dashboard once all sessions have finished. If we don't want to do that, provide a button to take you back. The usual place I would expect to look is either an "X" at the top right or a back arrow at the top left. Neither of these are present.

**How to reproduce it (as minimally and precisely as possible)**: As above.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-alpha.1git:v4.3.0-alpha.1-0-gd82e16ed0 go1.13.2`

**Comment by alex-kovoy** [comment]
It's been fixed (as we open terminal in the new browser tab)
