### ISSUE TITLE
Cloudflare rocket-loader.min.js blocked by CSP since v14.3.6

### ISSUE THREAD

**Issue by Ranoth** [gravitational/teleport#38376]
Expected behavior: Redirection to application.teleport.mydomain.com when clicking on the corresponding Launch button on the Resources page with content of the corresponding application.

Current behavior: Redirection to application.teleport.mydomain.com when clicking on the corresponding Launch button on the Resources page with blank content and tab is named "Teleport Redirection Service" with the following error:

>rocket-loader.min.js:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-36f632e6f87f96fc44829deaa735a360'". Either the 'unsafe-inline' keyword, a hash ('sha256-R90D4Ch6YhPQoolRiEOwk2sUKvV01QjeX4Rb9CfC8hw='), or a nonce ('nonce-...') is required to enable inline execution.
t.activateScript @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
t.run @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1
(anonymous) @ rocket-loader.min.js:1

Bug details:
- Teleport v14.3.6 and v15.0.2, going back to 14.3.4 fixes the error
- I am using Teleport behind a Traefik reverse proxy on Docker
- Config files: 
  - [teleport.txt](https://github.com/gravitational/teleport/files/14323824/teleport.txt)
  - [traefik.txt](https://github.com/gravitational/teleport/files/14323831/traefik.txt)
  - [docker-compose.txt](https://github.com/gravitational/teleport/files/14323836/docker-compose.txt)
- Debug logs: [teleport_debug.log](https://github.com/gravitational/teleport/files/14323794/teleport_debug.log)

**Comment by zmb3** [comment]
Hmm, I can't explain why it works in 14.3.4. We haven't changed the CSP recently.

Can you disable rocket loader for the impacted apps?

**Comment by Ranoth** [comment]
> Hmm, I can't explain why it works in 14.3.4. We haven't changed the CSP recently.
> 
> Can you disable rocket loader for the impacted apps?

Disabling rocket loader fixed the error
