### ISSUE TITLE
Teleport node connection status/local healthcheck

### ISSUE THREAD

**Issue by dampersand** [gravitational/teleport#3838]
### Feature Request
I'd love to see a way for a node (of any role) to export the status of whether it has successfully joined a cluster or not, its roles, etc.  Simple data known only to the node, but collected in a local location for monitoring/automatic remediation.

Something like:
>\# tctl status --self
nodename: test.dampersand.ohyeah
roles: node,proxy
cluster connection: Healthy
last ping: 5s

>\#tctl status --self
nodename: node.dampersand.ohno
roles: NA
cluster connection: no response from auth.dampersand.ohno
last ping: 3s

### Motivation
This is entirely for monitoring purposes/declarative setup (ie via config management), or for automated remediation (because nobody wants to be woken up at 3am).  As it stands, finding out whether a new node successfully joined the teleport cluster (from that node) requires crawling teleport.log and looking for 'failed to establish connection to cluster'.  Determining the roles of a node requires viewing its config file (or its command string, if teleport was not run with a config file).

So something like Sensu or Nagios currently have to have home-built plugins installed to determine "is the node correctly attached to a cluster?"

Declarative systems like puppet or saltstack that are used to spin up and control a new teleport node have no clever way of knowing the state of a teleport node and must rely on imperatively-programmed bash scripts instead.  In my case, I have a bash script that, upon bootstrap, shuts down the teleport systemd service, runs teleport in the foreground with a token as an environment variable to talk to the cluster, stops the foreground service, and restarts teleport from systemd.  This prevents me from needing auth_token.  For immortal systems, I basically have to hope this is never needed again, because attempting to gather the state information (is this node connected to the cluster?) is quite difficult because I don't trust log scraping. :)

It's also currently a hard to trigger remediation - for instance, consider an automated path that creates a dynamic auth_token with a node role (gating it with proper authorization, of course).  Let's say some yahoo SRE managed to uninvite the wrong node, but didn't notice - and that node's invitation token expired months ago.  Something like sensu would love to be able to notice the state change and then run the dynamic auth_token path on the node's behalf, without having to wake anyone up... but noticing the state change requires scraping logs.  Yuck!

### Who's it for?
OSS User, Enterprise

**Comment by webvictim** [comment]
You might find this useful: https://gravitational.com/teleport/docs/admin-guide/#troubleshooting

Essentially you run something like `teleport start --diag-addr=127.0.0.1:3000`, then `curl http://127.0.0.1:3000/readyz`. 

`/readyz` is similar to `/healthz`,, but it returns "OK" only after the node successfully joined the cluster - i.e. it expresses the difference between "healthy" and "ready". This should give you the information you need.

**Comment by dampersand** [comment]
That is pretty good.  I'm sorry I didn't finding before posting the feature request.

I'm away from my lab at the moment to guess-and-test, but is there a config file directive to enable diag-addr, instead of via command?

**Comment by webvictim** [comment]
I'm afraid not - `--diag-addr` on the command line is the only way.

**Comment by awly** [comment]
We should expose it in the config file too.
Filed https://github.com/gravitational/teleport/issues/3841
