### ISSUE TITLE
tctl can't edit cluster_auth_preferences

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#38390]
Expected behavior:
I should be allowed to edit the `cluster_auth_preference` resource using `tctl`.

Current behavior:
```
$ tctl -c ~/teleport/tp1/teleport.yaml edit cluster_auth_preference
ERROR: The cluster auth preference resource is managed by static configuration. We recommend removing configuration from teleport.yaml, restarting the servers and trying this command again.

If you would still like to proceed, re-run the command with both --force and --confirm flags.

$ tctl -c ~/teleport/tp1/teleport.yaml edit cluster_auth_preference --force --confirm

tctl: error: unknown long flag '--force'
```

Bug details:
- Teleport version v16.0.0-dev
- Recreation steps
1. Create a local cluster with auth server config.
2. Perform Commands specified above.

**Comment by bl-nero** [comment]
@zmb3 FYI, Alan said you may want to know about it.

**Comment by zmb3** [comment]
This is working as intended. You either define auth settings in teleport.yaml or you use dynamic configuration with tctl, but you can't mix both. See RFD 0016 if you're curious about the details.
