### ISSUE TITLE
Errors you may encounter when upgrading this dependency

### ISSUE THREAD

**Issue by KateGo520** [gravitational/teleport#3840]
### github.com/prometheus/client_golang  
-Latest Version: V1.6.0   (Latest commit 6edbbd9 on 28 Apr)
[NOW, you used version v1.0.0]
-Where did you use it: 
https://github.com/gravitational/teleport/search?q=prometheus%2Fclient_golang&unscoped_q=prometheus%2Fclient_golang
-Detail: 
>>[github.com/prometheus/client_golang/go.mod](https://github.com/prometheus/client_golang/blob/v1.6.0/go.mod#L5)
```
module github.com/prometheus/client_golang
go 1.11
require (
	github.com/beorn7/perks v1.0.1
	github.com/cespare/xxhash/v2 v2.1.1
	…
)
```

>>[github.com/prometheus/client_golang/prometheus/registry.go](https://github.com/prometheus/client_golang/blob/v1.6.0/prometheus/registry.go#L28)
```
package prometheus
import (
	"github.com/cespare/xxhash/v2"
	"github.com/golang/protobuf/proto"
	…
)
```
This problem has existed since version v1.2.0. If you try to get these version, you will get an error: no package exists at "github.com/cespare/xxhash/v2"

## Why?
1.	These dependencies all added [Go modules](https://github.com/golang/go/wiki/Modules) in the last version.

2.	They all comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules. Such as: Repo github.com/my/module opted in to Modules on version v3.x.y. Then the import statements within the module to also use /v3 (e.g., import `"github.com/my/module/v3/mypkg"`).

3.	This "github.com/my/module/v3/mypkg" is not the `physical path`. So earlier versions of Go (including those that don't have minimal module awareness) plus all tooling(like dep, glide, govendor, etc) don't have `minimal module awareness` as of now and therefore don't handle import paths correctly See [golang/dep#1962](https://github.com/golang/dep/issues/1962), [golang/dep#2139](https://github.com/golang/dep/issues/2139).
> Note: creating a new branch is not required. If instead you have been previously releasing on master and would prefer to tag v3.0.0 on master, that is a viable option. (However, be aware that introducing an incompatible API change in master can cause issues for non-modules users who issue a go get -u given the go tool is not aware of semver prior to Go 1.11 or when module mode is not enabled in Go 1.11+).
> Pre-existing dependency management solutions such as dep currently can have problems consuming a v2+ module created in this way. See for example dep#1962.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

### Migrate to Go Modules.
Go Modules is the future, If you want a better upgrade package experience, you can opt into Go Modules.

* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher
* https://github.com/golang/dep/issues/1962
* https://github.com/golang-migrate/migrate/issues/103

If this report helps you a little, please let me know

**Comment by KateGo520** [comment]
@klizhentas  @kontsevoy

**Comment by awly** [comment]
Thanks for the report.
We [plan to migrate](https://github.com/gravitational/teleport/issues/3541) to Go modules after a few large branches get merged into master (to avoid disruption for the authors).
I'll close this issue in favor of https://github.com/gravitational/teleport/issues/3541
