### ISSUE TITLE
A bit lost in new navigation

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3842]
Alex, this question is probably for you. I've tried the new UI for the past couple of days and at some point, I've noticed that I got lost in the navigation, here's how:

1. Opened the list of nodes
2. I've opened terminal, it got opened in the same window
3. Closed the terminal, and ended up in the state that is different from the state 1 and no going back.

See the recording of my steps:

![lost](https://user-images.githubusercontent.com/13717/84528490-9ef1b780-ac94-11ea-9874-93079d2b5282.gif)

My question is, can we make it more obvious for folks like me who wish who go back to the list of nodes after they close the tab?

**Comment by webvictim** [comment]
Same thing as https://github.com/gravitational/teleport/issues/3834

**Comment by alex-kovoy** [comment]
This is a bug, the terminal should be open in the new browser tab.

**Comment by alexwolfe** [comment]
Correct, this is a bug and I agree very confusing. The terminal should open in a new tab. This will allow users to play with the terminal as a separate application. The current behavior is a bug and causes usability issues when trying to get back to the dashboard.

**Comment by alex-kovoy** [comment]
This has been fixed (as terminal opens in a new tab)
