### ISSUE TITLE
Provide user context on user role(s)  in web

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3844]
### Feature Request
Provide the user roles for a user in their user name link for web sessions.  

### Motivation
In a tsh session users can see their roles for a given session.  The same information would be helpful for users to confirm their role assignment in a web session and reduce confusion on why they are allowed or not allowed to access certain nodes.

### Who's it for?
Pro, Enterprise

**Comment by benarent** [comment]
I can see arguments for making it harder to find, but for transparent organisations, it's better to be more explicit. I think it's a good feature request but will need a bit more detail.

**Comment by stevenGravy** [comment]
Since we have the user circle that list of assigned roles could show when selecting.  Otherwise I would expect a user information page that lists roles and other relevant information such as what roles they can request.  
![image](https://user-images.githubusercontent.com/60704961/84659041-cd65d180-aee4-11ea-92ac-8c7218a4497d.png)

**Comment by stevenGravy** [comment]
There is a user account settings page when the user is a local user.  That seems a good place too.

**Comment by benarent** [comment]
SSO users don't have an account settings page. but we could consider it.

Since it's per cluster, I wonder if a first step is to add this into `Cluster Information` . @alexwolfe Any thoughts for this? 

![image](https://user-images.githubusercontent.com/559288/84704709-1763ad00-af0f-11ea-9533-ac96deaa9ce3.png)
