### ISSUE TITLE
Provide Auth Connector Test mechanism

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3845]
### Feature Request
Provide a mechanism for administrators to test connecting to a Auth Connector to confirm connection and role mapping.  The mechanism should allow for a attempted login, confirm connectivity, role assignment, metadata and also return errors (no connection, incorrect traits,...).  

### Motivation
Configuring a single sign on mechanism can be a timely part of the initial Teleport configuration.  To troubleshoot requires a combination of attempting logins, monitoring the log with debug on, and reconfiguring the connection.  Having a mechanism that provides that ability within the web or command line would speed up configuration.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by benarent** [comment]
A few notes:
It looks like https://godoc.org/github.com/coreos/go-oidc#IDTokenVerifier  supports some kind of Token Verification.
