### ISSUE TITLE
Provide documentation on installing and maintaining tsh

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3846]
## Summary
Provide documentation on installing tsh for user machines in addition to the teleport executable.  I think we also need to look at this from the perspective of a new user to teleport.  One question is whether clietn users should only have tsh or the full Teleport installation.

 Documentation (https://gravitational.com/teleport/docs/installation/) shows installing teleport but little mention of tsh.  Users connecting to Teleport will need access to tsh and need to know which versions will work.  The admin guide mentions backwards compatibility (https://gravitational.com/teleport/docs/admin-guide/#component-compatibility) which we may want to include as part of the instructions.

Some users have older versions of tsh, especially previous OSS, which without knowing to upgrade or how to can cause confusion.

### Audience
Users accessing Teleport via tsh. Administrators configuring their environment to use the correct version of tsh client.

### Location
Expand installation guide, user manual link to installing tsh.  Possibly update the Help & Support in 4.3.

**Comment by zmb3** [comment]
There is a tsh-specific guide at https://goteleport.com/docs/use-teleport/tsh/ so I'm going to close this out.
