### ISSUE TITLE
Provide example groups and users Kubernetes configuration with Teleport in K8s usage

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3847]
## Summary
Provide example documentation on linking K8s groups or users with Teleport via roles or OSS.  Current documentation describes the impersonation process. Administrators that do not use the groups feature or often modify roles often have to ask how to setup roles and groups.  By having the documentation users would more clearly see how you setup a secure K8s access configuration.

   Showing a sample configuration with multiple groups and users would show how you can configure access to a K8s cluster.  

### Audience
New administrators taking on Teleport to integrate with K8s clusters.

### Location
Expand Kubernetes guide

**Comment by benarent** [comment]
I've added a section here https://gravitational.com/teleport/docs/kubernetes_ssh/#kubernetes-groups-and-users
