### ISSUE TITLE
Issue with install.

### ISSUE THREAD

**Issue by OMGLent** [gravitational/teleport#385]
I'm constantly being bombarded with the following error:

> DEBU[0102] [AUTH API] ping from PROXY 638306c2-3e52-4e93-b07d-daebb01c8ef5 (162.243.203.166) at 127.0.0.1:47340  file=auth/apiserver.go:143
> INFO[0103] fetch and sync servers: no auth servers with remote ips advertised  file=auth/tun.go:638
> DEBU[0103] [AUTH API] ping from AUTH 638306c2-3e52-4e93-b07d-daebb01c8ef5 (162.243.203.166) at 127.0.0.1:47338  file=auth/apiserver.go:143
> INFO[0104] fetch and sync servers: no auth servers with remote ips advertised  file=auth/tun.go:638
> INFO[0105] fetch and sync servers: no auth servers with remote ips advertised  file=auth/tun.go:638
> DEBU[0106] [AUTH API] ping from NODE 638306c2-3e52-4e93-b07d-daebb01c8ef5 (162.243.203.166) at 127.0.0.1:47342  file=auth/apiserver.go:143
> DEBU[0108] [AUTH API] ping from PROXY 638306c2-3e52-4e93-b07d-daebb01c8ef5 (162.243.203.166) at 127.0.0.1:47340  file=auth/apiserver.go:143
> INFO[0108] fetch and sync servers: no auth servers with remote ips advertised  file=auth/tun.go:638
> DEBU[0109] [AUTH API] ping from AUTH 638306c2-3e52-4e93-b07d-daebb01c8ef5 (162.243.203.166) at 127.0.0.1:47338  file=auth/apiserver.go:143
> INFO[0109] fetch and sync servers: no auth servers with remote ips advertised  file=auth/tun.go:638
> INFO[0110] fetch and sync servers: no auth servers with remote ips advertised  file=auth/tun.go:638

I'm not sure what this means or even how to begin to fix it so any help would be great.

**Comment by kontsevoy** [comment]
@OMGLent can you please provide the config file and the command line arguments you have used to start teleport? Thanks!

**Comment by kontsevoy** [comment]
I am assuming you're starting a Teleport proxy and it complains that it cannot automatically find the auth server (CA). You can point it to one using `--auth-server` flag
