### ISSUE TITLE
Improve SAML error reported

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport#3851]
### Description

**What happened**:

Users see the following error when they get access to the teleport SAML app, but don't have access to any servers which is confusing. 

![image](https://user-images.githubusercontent.com/8000186/84720364-b948c100-af32-11ea-9076-da5233ae18bb.png)

**What should happen**:

The error reported for this case can be improved to give more guidance.

**Comment by russjones** [comment]
Fixed in 4.3.

**Comment by JonGilmore** [comment]
@russjones curious what approach was taken in resolving this? is there anything configurable in the error message? was the wording just changed? thanks for taking care of this!

**Comment by russjones** [comment]
@JonGilmore We changed the error message to be more clear in 4.3, can you try it and tell us if that works. If not we can create another ticket for a configurable error message.
