### ISSUE TITLE
Free-type login@host box is missing in new UI

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3852]
**What happened**: In the old Teleport UI, there is a free-type `login@host` box at the top right which can be used to connect to any arbitrary host reachable behind Teleport proxy.

![2020-06-16-134859__1747x330__maim](https://user-images.githubusercontent.com/897821/84803442-632e5900-afd8-11ea-9ce3-c08ebb9950e7.png)

In the new UI, this box has disappeared. This is likely to confuse users who rely on it.

![2020-06-16-134850__1759x459__maim](https://user-images.githubusercontent.com/897821/84803429-5dd10e80-afd8-11ea-91a8-04e2fb60710f.png)

**What you expected to happen**: The free-type login box should be present in the new UI too.

**How to reproduce it (as minimally and precisely as possible)**: As above.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-alpha.1git:v4.3.0-alpha.1-0-gd82e16ed0 go1.13.2`

**Comment by russjones** [comment]
This will affect users using the recording proxy, they may have no Teleport nodes.
