### ISSUE TITLE
Teleport service fails to reload via systemctl on CentOS 7

### ISSUE THREAD

**Issue by savv3** [gravitational/teleport#38546]
Expected behavior:
`systemctl reload teleport` should reload teleport

Current behavior:
Fails with error:

> Failed to reload teleport.service: Job type reload is not applicable for unit teleport.service.
> See system logs and 'systemctl status teleport.service' for details.
> 
> [/usr/lib/systemd/system/teleport.service:10] Executable path is not absolute, ignoring: pkill...port.pid

Bug details:
- Teleport version
`# teleport version
Teleport v15.0.2 git:v15.0.2-0-g520f79d go1.21.7`

- Recreation steps
1. Install version 15.0.2
2. Try `systemctl reload teleport`

**Comment by zmb3** [comment]
@espadolini didn't you fix the absolute path issue already?

**Comment by savv3** [comment]
Thanks @espadolini! I'll try as soon as I get a chance!

**Comment by savv3** [comment]
Works now. Thanks again!
