### ISSUE TITLE
OTP QR code missing Issuer

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#3855]
### Description

**What happened**:

Create a new user with OTP enabled on the auth server.
Open the signup link and use Aegis (OTP app) to scan the QR code.
Aegis parsed the OTP URL and populated:
- username as `Teleport:awly@proxy.example.com:3080`
- issuer as empty string

**What you expected to happen**:

OTP URL is parsed as:
- username `awly@proxy.example.com:3080`
- issuer as `Teleport`

I believe this is because we don't set the `issuer` URL param, per https://github.com/google/google-authenticator/wiki/Key-Uri-Format#issuer

### Environment
- Teleport version (use `teleport version`): 4.3

**Comment by awly** [comment]
This happens in [Aegis](https://play.google.com/store/apps/details?id=com.beemdevelopment.aegis) but not in Google Authenticator.
The reason is that we put the port number in the OTP URL: `otpauth://totp/Teleport:alice@proxy.example.com:3080?secret=ABC&issuer=Teleport`.

Given that it's not explicitly prohibited by https://github.com/google/google-authenticator/wiki/Key-Uri-Format#issuer and kinda useful for local setups with multiple clusters on the same host (with different ports), we can leave this as is.

**Comment by stefan-as** [comment]
Same behavior with FreeOTP. QR code results in invalid token.

By the way: putting a port number in the url IS explicitly prohibited by https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label: "Neither issuer nor account name may themselves contain a colon"
