### ISSUE TITLE
Resource Access Request doesn't show role in list view

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#38586]
Expected behavior:
When performing an access request the role that was selected (out of multiples) should show up for the reviewer appropriately and in the audit log. 

Current behavior:
Unclear how it's selecting a particular role vs the one that was requested for review. It does approve the correct role, just doesn't show it correctly.

Creating the requet:
![Screenshot 2024-02-23 at 1 51 36 PM](https://github.com/gravitational/teleport/assets/51385814/c73b43ed-d834-4d4e-b8f8-7e531d9e297b)

Selecting the one role:
![Screenshot 2024-02-23 at 1 51 49 PM](https://github.com/gravitational/teleport/assets/51385814/1669938c-6d23-4a70-800a-77783841389c)

How it shows for the requester:
![Screenshot 2024-02-23 at 1 52 09 PM](https://github.com/gravitational/teleport/assets/51385814/1869d007-efe7-432f-9678-9291ad6fd763)

How it shows for the approver:
![Screenshot 2024-02-23 at 1 52 23 PM](https://github.com/gravitational/teleport/assets/51385814/22c8aae6-d060-4719-8763-3ce7ae207d76)

How it shows when reviewing the request (has the right role):
![Screenshot 2024-02-23 at 1 52 41 PM](https://github.com/gravitational/teleport/assets/51385814/7c3f7f94-a71e-4127-bc4c-b467003ed903)

Audit log entries:

```json
{
  "cluster_name": "scott.teleportdemo.com",
  "code": "T5000I",
  "ei": 0,
  "event": "access_request.create",
  "expires": "2024-02-23T22:48:22.998789709Z",
  "id": "2c73c468-2a4c-4ff9-a4a4-724b89f8f0e7",
  "max_duration": "2024-02-23T22:48:22.998789709Z",
  "resource_ids": [
    {
      "cluster": "scott.teleportdemo.com",
      "kind": "db",
      "name": "scott-rds-postgres"
    }
  ],
  "roles": [
    "database-rds-admin"
  ],
  "state": "PENDING",
  "time": "2024-02-23T18:51:59.993Z",
  "uid": "bd827ad9-086a-45bd-a2c5-2a8ca3c0f790",
  "user": "dev-user",
  "user_kind": 1
}
```

```json
{
  "cluster_name": "scott.teleportdemo.com",
  "code": "T5002I",
  "ei": 0,
  "event": "access_request.review",
  "expires": "2024-02-23T22:48:22.998789709Z",
  "id": "2c73c468-2a4c-4ff9-a4a4-724b89f8f0e7",
  "max_duration": "2024-02-23T22:48:22.998789709Z",
  "proposed_state": "APPROVED",
  "reviewer": "scott.gallagher@goteleport.com",
  "state": "APPROVED",
  "time": "2024-02-23T18:52:51.698Z",
  "uid": "dc682a95-74a1-4e33-85c5-0f7ca992e88a"
}
```

Bug details:
- Teleport version: 15.0.1
- Recreation steps: create an access request for a resource that has multiple roles attached to the resource.
- Debug logs

**Comment by webvictim** [comment]
Related: https://github.com/gravitational/teleport/issues/17109

**Comment by zmb3** [comment]
Updated the title of this to be more clear. The role does show in the "review request" page - it just doesn't show up in the list view.

Personally, I'd opt to do nothing here and close this. I think the fact that resource requests show resources in the list view and role requests show roles in the list view is a helpful distinction.
