### ISSUE TITLE
Expand tab to length of node name.

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3859]
### Description

**What happened**:
![image](https://user-images.githubusercontent.com/559288/85046659-92160d80-b145-11ea-87d1-42527757dd26.png)

**What you expected to happen**:
Extend to length of name ( within reason )

**Comment by webvictim** [comment]
This should also display the node name rather than the node’s UUID.

**Comment by webvictim** [comment]
+1 for this, we lots of spare screen real estate for these tabs and it's really important to be able to see the full hostname where possible. It should at the very least display the full hostname when you mouseover the tab.
