### ISSUE TITLE
Provide node multiple label sorting and filtering in web UI

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3860]
### Feature Request
Provide the ability to search for multiple labels in the web ui. Currently you can only search by a value in a label key/value pair.  As in the example `tsh ls` below you can search for multiple labels with a comma delimited list.  In a webui you could expect to have a excel like filtering or other similar experience.  

```bash
# tsh ls tier=dev,type=webserver
Node Name     Address            Labels                                                         
------------- ------------------ -------------------------------------------------------------- 
webdevserver1 webdevserver1:3022 id=231x21a, tier=dev                                           
                                 type=webserver, uptime=up 1 week, 6 days, 16 hours, 40 minutes 
webdevserver2 webdevserver2:3022 id=nm1x21a, tier=dev                                           
                                 type=webserver, uptime=up 1 week, 6 days, 16 hours, 40 minutes 
```
### Motivation
It can be difficult to find one or more groups of nodes without being able to filter by multiple labels in large number of nodes.  Also being able to sort by labels makes it easier to view the information in a easy to digest manner.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by alex-kovoy** [comment]
related #5021

**Comment by zmb3** [comment]
This is resolved with advanced search.
