### ISSUE TITLE
Where's the documentation for setting up a proxy for web app?

### ISSUE THREAD

**Issue by yangliping** [gravitational/teleport#3866]
## Summary
In [how it works](https://gravitational.com/teleport/how-it-works/) document, there's a diagram saying that teleport supports proxy for internal web apps. However, I can't find the document page on how to set it up.

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/6970919/85274385-7302dd00-b4b1-11ea-941c-c9a6f03e9ed3.png">

### Audience
docs, new users

### Location
Please add a how to guide on existing document.

**Comment by benarent** [comment]
Thanks for creating the issue @yangliping , Web Apps are going to be supported in Teleport 5.0, but are looking for beta testers. Can you send an email to me ben@gravitational.com and I'll add you to the beta list.
