### ISSUE TITLE
Unbound variable error on https://goteleport.com/static/install.sh install

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#38675]
Expected behavior:

No errors in regular installation

Current behavior:

Receiving message after setup

```
Setting up teleport (14.3.6) ...
main: line 39: TELEPORT_EDITION: unbound variable
```

To recreate run

`curl https://goteleport.com/static/install.sh | bash -s 14.3.6`

**Comment by slarti-b** [comment]
Just hit the same on CentOS 7 (yeah, I know).  Adding an empty
```
TELEPORT_EDITION=
```
At line 365 avoids the error.

However, also then get the script ending as
![image](https://github.com/gravitational/teleport/assets/12972794/72efbbff-35dd-4482-bb16-eb69c5e60f52)
(no commands listed).  By default `/usr/local/bin` is on the PATH for all users _except root_ - but the script is run as root.  As any other user I have `tsh` and `teleport` commands available but not as root.

**Comment by ptgott** [comment]
> Should I log a separate issue for this?

Yes, thanks!

**Comment by slarti-b** [comment]
Logged the path issue as #38697

**Comment by stevenGravy** [comment]
Looks like for centos stream they've now included that path for `root`.

**Comment by slarti-b** [comment]
> Looks like for centos stream they've now included that path for `root`.

Moved comment to linked issue
