### ISSUE TITLE
"tctl get rc" doesn't show correct last_heartbeat for offline clusters

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#3869]
### Description

**What happened**:

Running `tctl get rc` returns the zero time for offline clusters:
```
$ tctl get rc
kind: remote_cluster
metadata:
  name: b
status:
  connection: offline
  last_heartbeat: "0001-01-01T00:00:00Z"
version: v3
```

**What you expected to happen**:

`last_heartbeat` should show the last time that remote cluster was connected.

**How to reproduce it (as minimally and precisely as possible)**:

- start cluster A
- start cluster B
- create a trusted cluster resource in cluster B for cluster A
- run `tctl get rc` on cluster A
- stop cluster B
- run `tctl get rc` on cluster A

**Comment by russjones** [comment]
Best: 2
Worst: 5
