### ISSUE TITLE
teleport-agent-0 pod can not be created.

### ISSUE THREAD

**Issue by Dancoa** [gravitational/teleport#38735]
Hi guys, 

I'm trying to reinstall teleport agent for kubernetes (last time I deleted the pod, I thought it will be recreated itself but not). I installed it in standard way which I did successfully for many times before. However, no pods were created in teleport namespace and I found statefulset was always not ready. Could you pls help me about this? 

Thanks in advance!

![image](https://github.com/gravitational/teleport/assets/18479340/d4ef9786-fb23-4d8e-9773-4e2745f241ed)
![image](https://github.com/gravitational/teleport/assets/18479340/d3dbe2b0-6abd-47f2-9231-ebdfcf1a0866)

Bug details:
- Teleport version: 13.4.15

**Comment by zmb3** [comment]
Hi there,

This looks more like a request for help troubleshooting Kubernetes deployments. You might have better luck starting a [discussion](https://github.com/gravitational/teleport/discussions) or asking for help in our community Slack workspace.

GitHub issues are better suited for work that is actionable by the dev team (ie confirmed bugs with clear reproduction steps, logs, etc)
