### ISSUE TITLE
Option to authorise with 2nd factor when connecting to a node/k8s cluster.  

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3878]
### Feature Request
Teleport current authenticates users on login, access is then authorised based on Teleports Auth API.  We've a customer who would like to an identity provider and get Teleport end-users to use a 2nd factor ( U2F Token / Yubi Key ) when trying to access a node.  This provides an extra check, since even if a certificate was compromised, Teleport would still require a token to access the node.

### Motivation
Strengthen Security posture for accessing nodes. 

We should take into account https://github.com/gravitational/teleport/issues/3814 and[ Mac Device Authentication ( Internal Doc )](https://docs.google.com/document/d/1hSWBP5LAMzTzK1DVXOKZBtvoZi9DfJJGxqbVKpRaEAA/edit#heading=h.ju0cos12gk8t)

### Who's it for?
OSS User, Pro, Enterprise

### Estimated Release Timeframe:
Calendar Q1 2021

**Comment by benarent** [comment]
Another request for this feature to use Yubi Key FIPS https://www.yubico.com/products/yubikey-fips/ but only on Login and optional for sessions.

**Comment by russjones** [comment]
Best: 30
Worst: 90

**Comment by awly** [comment]
Remaining tasks:

- [ ] cluster-level config option
- [ ] docs
- [ ] database and application access integration
- [ ] MFA check during web SSH

**Comment by awly** [comment]
https://github.com/gravitational/teleport/issues/6172 for app/db access integration.
Only docs remaining for this one.
