### ISSUE TITLE
webhooks for proxy events

### ISSUE THREAD

**Issue by nate-thirdwave** [gravitational/teleport#38797]
What would you like Teleport to do?
I'd like to be able to get webhook notifications about connection events on the proxy server.  

What problem does this solve?
This would allow for a number of extensions:
 * Posting in a slack channel or web dashboard that <nodename> is in use by <user>
 * Potentially automating some kinds of resource locking.

If a workaround exists, please include it.
 * The closest conceptual workaround would be to scrape the audit logs via some other service.

**Comment by strideynet** [comment]
As part of our API, we do provide the ability to watch for changes to resources and to fetch audit events - that'd most likely be a good workaround without explicit support for webhooks.

**Comment by zmb3** [comment]
Marking not planned for now.
