### ISSUE TITLE
Role setup for host user creation is too hard to debug

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#38801]
During my support shifts, I've run into at least two users having problems with host user creation setup. The crucial part they missed is contained within a warning in the guide:

> When a Teleport user accesses an SSH Service instance, Teleport checks each of the user's roles that match the instance. If at least one role matches the instance but does not set `create_host_user_mode`, automatic user creation will be disabled. Roles that do not match the server will not be checked.

https://goteleport.com/docs/server-access/guides/host-user-creation/#step-13-configure-a-role

There's a couple of issues that we should address.

## Problems with Teleport

Teleport itself doesn't show any logs related to host user creation being disabled. The service that checks the roles could output a debug message when host user creation gets disabled and explain why.

## Problems with the guide

This section is no longer relevant as the guide has been updated in #39405.

<details>
<summary>Old section text</summary>

The guide makes it too easy to make that mistake. It asks you to create a new role called `auto-users` with `create_host_user_mode: keep` and assign it to your user. But you're almost guaranteed to have another role such as `access` assigned to your user which will cause host user creation to not work.

Perhaps the guide should make you create a new user account first and assign only that role to it. It could also explain why that new user account is being created.

I feel like this would be merely a band-aid, as the moment you try to assign the role to another user, host user creation will break due to other roles matching an SSH instance. Ultimately, it is something that needs to be addressed on the software-level as well.
</details>

**Comment by ravicious** [comment]
It's great that the docs are better now, but I'm going to reopen this to specifically focus on Teleport doing a better job at logging this. I swear I run into a user with this problem every other support shift.

**Comment by stevenGravy** [comment]
Related https://github.com/gravitational/teleport/issues/40370

**Comment by ravicious** [comment]
Let's just track it there I suppose.
