### ISSUE TITLE
Audit log postgres connection PID

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#38820]
What would you like Teleport to do?
* Audit log the PID when a new postgres session is established.

What problem does this solve?
* Allows customers to associate a running process to a teleport user's database session. Since users may (and likely do) share a database user, the database user who started the query is not enough information. While PID is also not complete information, it can help to quickly narrow down the origin of a running postgres backend process.

If a workaround exists, please include it.
* N/A

**Comment by Askir** [comment]
Does Teleport not log the original SSO user with every statement?
Just gonna shamelessly advertise my open source tool here then: https://github.com/kviklet/kviklet 😇  Recently build a proxy into it that does log the associated SSO user with every query and statement and not just the postgres user.

**Comment by GavinFrazar** [comment]
We log both the user in Teleport and the postgres user already. PID logging was requested so a user can (more easily) trace a running postgres backend process started by someone else to the Teleport user who started it.

**Comment by djohns7** [comment]
Hey team,
Can you help us understand the use case here? Teleport's audit logs associate the Teleport user who ran a query (which should always be unique), as well as the database user (which may or may not be unique), as it exists today. Can you help clarify what PID Teleport could record and how that would help? What are we hoping to identify?

**Comment by GavinFrazar** [comment]
Postgres backend PID. Useful to more easily associate a long-running query with a Teleport user. This is not actually necessary to find the user responsible, it just makes it easier to search for a PID rather than trying to locate a matching query in the audit log.
