### ISSUE TITLE
Alternative service to `samltest.id` for SAML IdP guide

### ISSUE THREAD

**Issue by flyinghermit** [gravitational/teleport#38821]
### Applies To

[Teleport as a SAML identity provider guide](https://goteleport.com/docs/access-controls/idps/saml-guide/)

### Details

The guide uses [samltest.id ](http://samltest.id/), a free reference SAML IdP and SP testing service as a reference service provider to test integration. Unfortunately, the service is broken now. It may come up online again but it leaves bad experience for our docs user when following the guide. 

### How will we know this is resolved?

The guide should show example based on an always reproducible SAML service provider service, maybe with an application runnable in a docker container. 

### Related Issues

n.a

**Comment by mmcallister** [comment]
**Status**:

I've tested this one out from Auth0, it's free and they are a trusted org. However it is a bit involved to set up on their end. 
https://auth0.com/docs/authenticate/protocols/saml/saml-configuration/configure-auth0-as-service-and-identity-provider

![Auth0-SAML-test](https://github.com/gravitational/teleport/assets/6885322/749ac190-8a1b-43e1-928c-dc265bf80f3d)

Once in place you can simply add the details , similar to the defunct `samltest.id` service.

```kind: saml_idp_service_provider
metadata:
  # The friendly name of the service provider. This is used to manage the
  # service provider as well as in identity provider initiated SSO.
  name: auth0-samltest
spec:
  # entity_id is the metadata endpoint of service provider
  # that serves entity descriptor, aka SP metadata.
  entity_id: urn:auth0:dev-e8erwfts8t85u6x0:MARIE-SAML-Auth0-IDP
  # acs_url is the endpoint where users will be redirected after
  # SAML authentication.
  acs_url: https://test-marie.us.auth0.com/samlp/3op6w0gzXDxYGtU9oKBhMFjjx0QB8KRi
version: v1

Metadata:

https://dev-e8erwfts8t85u6x0.us.auth0.com/samlp/metadata?connection=MARIE-SAML-Auth0-IDP
```

[Metadata](https://dev-e8erwfts8t85u6x0.us.auth0.com/samlp/metadata?connection=MARIE-SAML-Auth0-IDP)

---

I'm trying out a couple of Docker solutions as well

**Comment by mmcallister** [comment]
Docker demo from Disney dev:
https://medium.com/disney-streaming/setup-a-single-sign-on-saml-test-environment-with-docker-and-nodejs-c53fc1a984c9

**Comment by mmcallister** [comment]
thanks @flyinghermit!

**Comment by mmcallister** [comment]
![Screenshot 2024-06-03 at 16-46-48 Protected Page SAML Demo Service Provider](https://github.com/gravitational/teleport/assets/6885322/725bb642-e4d4-4968-9d4a-94a500f9cdfd)

tested the new process out successfully - closing this as a duplicate
