### ISSUE TITLE
RBAC docs don't explain how to grant new roles to a user

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#3886]
## Summary

When not using an SSO provider, user roles are baked into a user object. The docs don't mention how to update this, specifically when dealing with RBAC.

### Audience

Enterprise POCs

### Location

https://gravitational.com/teleport/docs/enterprise/ssh_rbac/

**Comment by zmb3** [comment]
Closing as this information is documented at https://goteleport.com/docs/access-controls/guides/role-templates/
