### ISSUE TITLE
Create or deleting access lists in Web UI does not refresh access lists page

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#38869]
Expected behavior:

If a access list was created or deleted in the web ui the list should be refreshed.

Current behavior:

Creating a access list shows the list prior to creating. A user has to refresh or navigate away and back to see the updated list.

In the case of a delete the old access list will still show after deleting. Pressing it will show this error.

![image](https://github.com/gravitational/teleport/assets/60704961/585aa154-9671-4262-8bc1-a63d9674c93f)

Bug details:
- Teleport version: 15.1.0
- Recreation steps

1. Create a Access List from the Identity Access Management section
2. The new access list will not show in the list of Access Lists

For deletion select a access list, delete and it will still show in the list. selecting will show the above error.

**Comment by kimlisa** [comment]
fixed with https://github.com/gravitational/teleport.e/pull/4347
