### ISSUE TITLE
How can I change the record name for Session recording?

### ISSUE THREAD

**Issue by Dancoa** [gravitational/teleport#38916]
What would you like Teleport to do?

**Define the name by myself**
![image](https://github.com/gravitational/teleport/assets/18479340/3aafc180-59b8-4799-9ecf-7e4650fa06e0)

**Because I have so many servers and they have the same hostname but with different labels I set in teleport agent configuration(/etc/teleport.yaml). So I want to change them with my own label that I can check the records more clearly.**

What problem does this solve?

**In this case: all servers have the same hostname. Otherwise, I need to check them one by one which is impossible for me.**

If a workaround exists, please include it.

**Comment by zmb3** [comment]
That column will always display the name of the connected resource associated with the recording. The only way to change it is to change the name of the resource.
