### ISSUE TITLE
Update `install-linux.mdx` to use the one-liner for all editions

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#38933]
## Applies To

[`docs/pages/includes/install-linux.mdx`](https://github.com/gravitational/teleport/blob/7175938cebc86f4042ffde0810d04ecb1e1738bc/docs/pages/includes/install-linux.mdx)

## Details

Now that the `install.sh` script supports an edition parameter, we should update the `install-linux.mdx` partial to use the one-line script with this parameter. Currently, the partial uses a nested `Tabs` component for non-Community editions. By using the one-line script with different edition parameter values instead, we can vastly simplify the partial.

Once we merge #36596, the Installation page will provide users the context they need for more bespoke installation commands. For how-to guides, the one-line script should be sufficient.

## How will we know this is resolved?

- Make sure that the one-line installation script supports all installation methods shown in the current `install-linux.mdx` partial. As of Mar 4, 2024, the script does not support Zypper.
- We have edited `install-linux.mdx` to use the one-line installation script.

**Comment by stevenGravy** [comment]
I would say having more details on what/where repos are being installed is very helpful for admins. Too much of a black box makes upgrading a install difficult.  So if there's perhaps a option to hide/show the details of the apt/yum/zypper repo installs that's great.

**Comment by ptgott** [comment]
> I would say having more details on what/where repos are being installed is very helpful for admins. Too much of a black box makes upgrading a install difficult. So if there's perhaps a option to hide/show the details of the apt/yum/zypper repo installs that's great.

That makes sense—which details are admins usually looking for?

Maybe we could add a brief note beneath the one-line command indicating that the installation script detects the local package manager and installs a package from a remote DEB or RPM repo? We could also link to the Installation page for more information.

**Comment by stevenGravy** [comment]
> 
> That makes sense—which details are admins usually looking for?
> 
> Maybe we could add a brief note beneath the one-line command indicating that the installation script detects the local package manager and installs a package from a remote DEB or RPM repo? We could also link to the Installation page for more information.

As we do here you'd want to know the Teleport keyring source, the repos and the name of the installation.  The Yum and Zypper are simpler but you'd want to know the repos. Typically the biggest issue we see is when these resources are not available within their networks so they need to proxy them in some way.

```bash
sudo curl https://apt.releases.teleport.dev/gpg \
-o /usr/share/keyrings/teleport-archive-keyring.asc
source /etc/os-release
echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] \
https://apt.releases.teleport.dev/${ID?} ${VERSION_CODENAME?} stable/v15" \
| sudo tee /etc/apt/sources.list.d/teleport.list > /dev/null
sudo apt-get update
sudo apt-get install teleport-ent
```

**Comment by stevenGravy** [comment]
@webvictim any additional thoughts?
