### ISSUE TITLE
Provide more Login 'Display' Options

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3896]
### Feature Request
We currently provide a range of `Display` Options for Teleport

![image](https://user-images.githubusercontent.com/559288/85631287-1d057500-b62a-11ea-80ae-52b472893a2e.png)

https://github.com/gravitational/webapps/blob/39022cc357e64d5713473b88df690a3f59ff4607/packages/shared/components/ButtonSso/utils.js#L21

It would be good to provide support for custom icon / login buttons for

- Okta
- Auth0
- OneLogin
- Update Google, so it's not the Google Plus Logo

**Comment by kimlisa** [comment]
@klizhentas do we need to go through a design process for this? else i propose the following:

Ignore the colors of the icon image. The coloring of buttons will remain the same format: the branding color will be the button's bgColor and white icons.

update google icomoon icon:
![image](https://user-images.githubusercontent.com/43280172/117375056-32227580-ae83-11eb-9966-d9df2e3eec9b.png)

add auth0 icomoon icon:
![image](https://user-images.githubusercontent.com/43280172/117375126-45354580-ae83-11eb-99aa-205db7672534.png)

onelogin icon isn't available in icomoon, but they have it on their website with exact colors used: https://www.onelogin.com/press-center/press-kit

okta doesn't have a small icon, its just `okta` so i'm not sure how to go about including this one. We can do a bolded letter `o`?: https://www.okta.com/press-room/media-assets/logos/

**Comment by benarent** [comment]
I ran into this again today, so did 
https://github.com/gravitational/teleport/issues/7325 & https://github.com/gravitational/teleport/issues/3896 .

**Comment by zmb3** [comment]
Closing in favor of #36883
