### ISSUE TITLE
WindowsDesktop service is not reported in inventory

### ISSUE THREAD

**Issue by bernardjkim** [gravitational/teleport#38977]
Expected behavior:
When running the `tctl inventory ls` command, the `WindowsDesktop` service should be reported.

Current behavior:

The service is listed when using `tctl get windows_desktop_service`:
```
$ tctl get windows_desktop_service --format=text
Name Address Version
---- ------- -------
xxxx ...     14.3.6
```

The Linux server running the WindowsDesktop service is listed, but only as a `Node` service.
```
$ tctl inventory ls
Server ID                            Hostname                        Services       Agent Version  
------------------------------------ ------------------------------- -------------- ---------------
xxxx                                 ...                             Node           v14.3.6        
```

Bug details:
- Cluster version: v14.3.6, Agent version: v14.3.6, tctl version: v13.4.3
- Recreation steps: Was unable to reproduce, I'll investigate a bit more.
- Debug logs

**Comment by zmb3** [comment]
Note: `WindowsDesktop` and `WindowsDesktopService` are distinct resources. I assume you're more interested in `WindowsDesktopService` (the agent) than the individual desktops they proxy.

@fspmarshall does `tctl inventory ls` only work for resources that use instance heartbeats?

**Comment by fspmarshall** [comment]
@zmb3 `tctl inventory ls` should show all the enabled services.  It doesn't matter if the specific service uses the inventory control stream for anything, the logic in `lib/service` should automatically be advertising all enabled system roles for the instance.  This is definitely a bug.

**Comment by zmb3** [comment]
Interesting, `tctl inventory ls` comes up empty for me, even though I'm running `ssh_service`, `app_service`, and `windows_desktop_service`.

**Comment by zmb3** [comment]
Just tried this again with 85e5e3d7304762caba8e8d52660d4c4406962929 and two desktop agents connected:

- one in-process with proxy and auth
- a standalone windows agent

The in-process agent does show up in inventory, but the standalone agent does not.

```
➜ tctl inventory ls
Server ID                            Hostname Services                           Agent Version Upgrader Upgrader Version
------------------------------------ -------- ---------------------------------- ------------- -------- ----------------
307e091b-7f6b-42e0-b78d-3362ad10b55d mbp16    Proxy,App,WindowsDesktop,Auth,Node v16.0.0-dev   none     none
```
