### ISSUE TITLE
Unable to restart Teleport agent

### ISSUE THREAD

**Issue by michaelrigart** [gravitational/teleport#39001]
Expected behavior:

Restart Teleport agent successfully 

Current behavior:

In v15, changes have been made to the Teleport reload behavior: [Commit ](https://github.com/gravitational/teleport/commit/bd47f0e02ace4df4cb3a40fb4a06ccfcb0ed2e79) and [PR](https://github.com/gravitational/teleport/pull/37773)

The `ExecReload` option has been changed and only contains the binary name. This fails using systemd:

`Failed to restart teleport.service: Unit teleport.service is not loaded properly: Exec format error.
See system logs and 'systemctl status teleport.service' for details.`

Checking the status shows:

`
● teleport.service - Teleport Service
   Loaded: error (Reason: Exec format error)
   Active: active (running) since Wed 2024-03-06 06:15:28 CST; 1min 16s ago
 Main PID: 20983 (teleport)
    Tasks: 16 (limit: 4915)
   CGroup: /system.slice/teleport.service
           └─20983 /usr/local/bin/teleport start --config /etc/teleport.yaml --pid-file=/run/teleport.pid
.........
Mar 06 06:15:59 vm-dev-lab-mic730-1 systemd[1]: /lib/systemd/system/teleport.service:10: Executable path is not absolute: pkill -HUP -L -F /run/teleport.pid
`

Bug details:
- the pkill executable path needs to be obsolete (in our case, pkill is located in /usr/bin
- previous commit needs to be revised and make the executable path for pkill absolute

**Comment by espadolini** [comment]
@michaelrigart What distro are you using, and which systemd version is it shipping?

As a workaround until we figure out a more reliable fix, you can `systemctl edit teleport.service` to override the `ExecReload` option with one that has an absolute path for `pkill`.

**Comment by michaelrigart** [comment]
@espadolini : This happens in different Ubuntu distro's (18.04, 20.04 and 22.04). 

Systemd versions: 237, 245, 249

We have indeed overwritten the unit file of all our devices after the client upgrade, with the small change providing the absolute path.

**Comment by espadolini** [comment]
I can't seem to replicate it on Ubuntu 20.04 or 22.04, but I was able to replicate it on 18.04 (systemd 237), and a (very simple) fix is underway.

**Comment by michaelrigart** [comment]
Hey @espadolini ,

Thank you for the quick intervention. I checked the merged PR, but the absolute path was only added in `examples/systemd/teleport.service`. Is this enough? Since the initial PR had a lot more changes.

I apologize for the perhaps dumb question, I don't know how the build process of Teleport works :)

**Comment by espadolini** [comment]
@michaelrigart thank you for noticing! It would've indeed not been enough for the fips release at least; most other ones are probably fine to leave with the relative `pkill` but I've just updated them all for consistency anyway.
