### ISSUE TITLE
Audit Log doesn't log file name.

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3900]
### Description

**What happened**:
While testing SCP, I noticed that it doesn't capture the file that's being upload. I'm unsure if this is a bug, or a limit of our current audit log and we require eBPF to capture all of the SCP events. 

```json
{
  "action": "upload",
  "addr.local": "66.220.18.10:3022",
  "addr.remote": "73.202.138.51:47994",
  "code": "T3005I",
  "command": "/usr/local/bin/teleport scp --remote-addr=73.000.000.00:47994 --local-addr=66.220.18.10:3022 -t /etc/teleport",
  "event": "scp",
  "exitCode": "0",
  "login": "root",
  "namespace": "default",
  "path": "/etc/teleport",
  "time": "2020-06-24T22:45:17Z",
  "uid": "8f94e7b9-4ef9-4ef1-bad7-e0fd502bc8d2",
  "user": "benarent"
}
```

2. Uploaded a File Copy.

We currently say `User "benarent" uploaded a file / to node 66.220.18.10:3022` , we should update this to be

`User "benarent" uploaded a file to / on node 66.220.18.10:3022`

![image](https://user-images.githubusercontent.com/559288/85635236-3dd1c880-b632-11ea-9dfd-222b323dddaf.png)

 Tested on Auth Service Version:
4.3.0-alpha.1

**Comment by benarent** [comment]
Note: It works for Downloads 
![image](https://user-images.githubusercontent.com/559288/85635380-93a67080-b632-11ea-8eca-dc2a95d9d0da.png)

**Comment by russjones** [comment]
Best: 2
Worst: 4

**Comment by benarent** [comment]
Ping again from 5.0 test plan :-P

**Comment by jakule** [comment]
@capnspacehook I think this can be closed as SFTP logs file names. Correct me if I'm wrong.

**Comment by capnspacehook** [comment]
Yes you are correct, SFTP does log file names.
