### ISSUE TITLE
Implement PostHog for database permissions, auto user provisioning

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#39018]
PostHog for:
- https://github.com/gravitational/teleport/pull/37808
- auto db user provisioning

**Comment by Tener** [comment]
@zmb3 https://github.com/gravitational/teleport/pull/39394 shouldn't close this issue, although it is related: it is a prerequisite for the next PR which will indeed resolve it.

**Comment by zmb3** [comment]
> @zmb3 https://github.com/gravitational/teleport/pull/39394 shouldn't close this issue, although it is related: it is a prerequisite for the next PR which will indeed resolve it.

Understood. Let's at least link the issues with an "Updates #XYZ" comment.

**Comment by Tener** [comment]
Yup, exactly what I did.

**Comment by greedy52** [comment]
Can this be closed?
