### ISSUE TITLE
Log spam about flushing events in teleport enterprise

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#3902]
### Description

**What happened**:

Running teleport enterprise 4.3 with FIPS mode, I get the following repeatedly logged in debug log:
```
DEBU             Failed to flush events: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate specifies an incompatible key usage". client/client.go:116
```

This seems to start after a user login via github connector.

This cluster is a root cluster with 1 leaf cluster, if it matters.

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by awly** [comment]
This is coming from the enterprise version reporting logic, which is not related to recording actual teleport audit events.
It's not breaking core teleport functionality so we don't need to block 4.3 on this.

**Comment by zmb3** [comment]
This log message no longer exists, so I'm going to consider this resolved.
