### ISSUE TITLE
Teleport updater is incompatible with ArgoCD

### ISSUE THREAD

**Issue by bernardjkim** [gravitational/teleport#39094]
Expected behavior:
There are a number of users deploying Teleport with ArgoCD. Teleport auto updates should be compatible with ArgoCD deployments.

Current behavior:
Users are unable to enroll in auto updates because it is incompatible with their ArgoCD deployments. ArgoCD generates the template from the Helm release and manages the resources itself. It monitors changes to the teleport-agent resource and reconciles with the initial template if the resource has diverged from the initial spec.

**Comment by evendark** [comment]
We We currently have a project where we have to connect about 50 ArgoCD environments to Teleport. Currently this topic is a blocker for us
