### ISSUE TITLE
Search box location is inconsistent between cluster view and node view

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3912]
**What happened**: The search box for cluster view is at the top right:

![2020-06-25-161750__1679x427__maim](https://user-images.githubusercontent.com/897821/85786116-53adbf00-b700-11ea-97f2-c45b20d19bca.png)

...whereas the search box for node view is on the left and below where you'd expect it to be.

![2020-06-25-161801__1694x460__maim](https://user-images.githubusercontent.com/897821/85786166-60caae00-b700-11ea-9525-7abd4ba35fea.png)

This is confusing, as I refine the list of clusters in the cluster view, click into one, then start typing in the same box to filter the list of nodes and nothing happens.

**What you expected to happen**: Search boxes should be in similar locations to be more intuitive.

**How to reproduce it (as minimally and precisely as possible)**: Log in and observe.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-master.1git:v4.2.0-alpha.5-444-g3976a9977-dirty go1.13.2`

**Comment by alex-kovoy** [comment]
this is by design (it has been discussed)

**Comment by alex-kovoy** [comment]
+ Quick Launch has been removed from the Nodes screen.
