### ISSUE TITLE
Time filtering in audit log "events" view doesn't seem to work

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3914]
**What happened**: Time filtering in the "events" view of the audit log page doesn't seem to correctly filter down the events to the requested timeframe.

Select 19-20 June:
![2020-06-25-164941__507x295__maim](https://user-images.githubusercontent.com/897821/85788877-06cbe780-b704-11ea-8523-22d8c50d1396.png)

See events from June 21:
![2020-06-25-164935__2213x1077__maim](https://user-images.githubusercontent.com/897821/85789061-53172780-b704-11ea-91d4-2b36b1b96cbe.png)

The "sessions" view seems to filter OK, it's just the "events" page which seemingly doesn't.

**What you expected to happen**: Filters should be applied correctly.

**How to reproduce it (as minimally and precisely as possible)**: Load audit log, look at events view, filter by date, observe brokenness.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-master.1git:v4.2.0-alpha.5-444-g3976a9977-dirty go1.13.2`

**Comment by alex-kovoy** [comment]
I quickly check this cluster and form the first glance the issue appears with the backend.

![image](https://user-images.githubusercontent.com/7816406/85904862-d3f32380-b7d7-11ea-9d22-be1c6cb33326.png)

API returns events which do not fall into specified range.

**Comment by russjones** [comment]
Best: 2
Worst: 4

**Comment by alex-kovoy** [comment]
@xacrimon do you know if this has been fixed?

**Comment by xacrimon** [comment]
Should be fixed @alex-kovoy
