### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by ocyedwin** [gravitational/teleport#392]
I was testing teleport on my Ubuntu Xenial virtualbox following the quickstart guide.

All is fine until I tried to ssh in with:
```
tsh --proxy=localhost ssh localhost
```

I encountered:
```
Enter password for vagrant:
...
Enter your HOTP token:
...
ERROR: [client/api.go:610]  [web/sshlogin.go:65]  [httplib/httplib.go:96]  x509: certificate signed by unknown authority

```

Any idea what went wrong?

**Comment by klizhentas** [comment]
Can you try --insecure flag? Can you also add -d to get debug output ?

**Comment by ocyedwin** [comment]
the output with --insecure and -d:
```
DEBU[0018] attempting to use loopback pool for local proxy addr: localhost:3080  file=client/api.go:659
DEBU[0018] could not open any path in: /var/lib/teleport/webproxy_cert.pem  file=client/api.go:665
WARNING: You are using insecure connection to SSH proxy https://localhost:3080
ERROR: access denied to 'vagrant': bad username or credentials
```

yesterday, I can login into the web terminal as 'vagrant' just fine.

![websessions](https://cloud.githubusercontent.com/assets/1121425/15002840/1c659c60-11d8-11e6-8126-a3e8bb08dc30.png)

I created a new user 'vagrant2' today however and got logged out immediately in web terminal.

![vagrant2](https://cloud.githubusercontent.com/assets/1121425/15002857/4579c1a8-11d8-11e6-9782-7a09060fc610.png)

**Comment by kontsevoy** [comment]
@ocyedwin I think I know what the problem is. The fix is coming shortly.

**Comment by kontsevoy** [comment]
ocyedwin: Teleport users are not the same as local users on a host. This PR #397 will allow you to properly select which teleport user you want to login as, but you still have to select the proper host login, either by adding login@host or via `--login` flag. I hope this makes sense.

In your example there's Teleport `vagrant2` user, but the VM doesn't have `vagrant2` OS user on it.
