### ISSUE TITLE
Login with Bitwarden Passkey

### ISSUE THREAD

**Issue by naimo84** [gravitational/teleport#39228]
Expected behavior:
A working login with passkeys and bitwarden/vaultwarden

Current behavior:
adding a passkey to bitwarden via the options works as expected, 
verifing identity via passkey works,
login only works with a Google Passwordmanager Passkey, not with the added bitwarden passkey

Bug details:
- Teleport version: 15.1.1
- Recreation steps

---
adding:
![image](https://github.com/gravitational/teleport/assets/11535502/8e5e8627-562f-4adc-ac1b-7b8e12eb0f43)
![image](https://github.com/gravitational/teleport/assets/11535502/eb5d4cf1-c59b-4f57-a4f1-ce5fe9def722)
![image](https://github.com/gravitational/teleport/assets/11535502/9d83eced-43df-4d90-99eb-713e6e7f7663)

---
verifing identity:
![image](https://github.com/gravitational/teleport/assets/11535502/3fb0eff3-1bf7-4de6-96f7-2af860f44deb)
![image](https://github.com/gravitational/teleport/assets/11535502/eade923e-ea98-4d15-aecc-9404023cd712)

---
logging in:
![image](https://github.com/gravitational/teleport/assets/11535502/07d8733f-cb11-47dd-b086-c371bc14305c)
![image](https://github.com/gravitational/teleport/assets/11535502/2445b558-593a-484f-a41f-76fa088f3932)

- Debug logs
- 
Mar 12 11:38:52 1337 teleport[3131766]: 2024-03-12T11:38:52+01:00 INFO [AUDIT]     mfa.add addr.remote:[::1]:37468 cluster_name:teleport code:T1006I ei:0 event:mfa.add mfa_device_name:bitwarden2 mfa_device_type:WebAuthn mfa_device_uuid:42037189-d5bb-48af-b48e-4b9f180ba6ab time:2024-03-12T10:38:52.755Z uid:32a9c0ab-4480-41d2-a6d1-c9baec11ce7a user:naimo user_kind:1 events/emitter.go:278
Mar 12 11:39:19 1337 teleport[3131766]: 2024-03-12T11:39:19+01:00 INFO [AUDIT]     mfa_auth_challenge.validate challenge_allow_reuse:false challenge_scope:CHALLENGE_SCOPE_MANAGE_DEVICES cluster_name:teleport code:T1016I ei:0 event:mfa_auth_challenge.validate mfa_device_name:bitwarden2 mfa_device_type:WebAuthn mfa_device_uuid:42037189-d5bb-48af-b48e-4b9f180ba6ab success:true time:2024-03-12T10:39:19.405Z uid:37dc8ec9-fee1-4ae1-abda-746e3fc85049 user:naimo user_kind:1 events/emitter.go:278

Issue Link: [#19314](https://github.com/gravitational/teleport/issues/19314)

**Comment by ilbarone87** [comment]
I have same issue, bitwarden self hosted, not working either on Chrome and Safari. Both bitwarden and teleport are behind traefik reverse proxy. I can delete and re-add the passkey without problem but the login doesn't work

**Comment by im-alfa** [comment]
Hello,

I can confirm I have the same issue as @naimo84 .

"Verify my identity" opens Bitwarden as expected
![image](https://github.com/gravitational/teleport/assets/25107205/0550f4af-eff5-4e51-bdf5-3083e14ca24f)

However, "Sign in with a passkey" automatically opens the Windows selector. Same with Passkey as MFA
![image](https://github.com/gravitational/teleport/assets/25107205/af34c450-8072-4e90-952a-8aae200c326b)

**Comment by milos-teleport** [comment]
Workaround:

1. [Export your Bitwarden vault](https://bitwarden.com/learning/passwordmanager-how-to-export-your-bitwarden-vault/)
2. Open the exported file and remove all JSON elements except the one for your tenant
3. Change the `items[].login.fido2Credentials[].discoverable` to `true`
5. [Import](https://bitwarden.com/help/import-data/) the single JSON element into bitwarden (creates a duplicate)
6. Optional: Remove the old Bitwarden vault entry

**Comment by milos-teleport** [comment]
The workaround should only be needed for old Bitwarden passkeys. Looks like Bitwarden fixed similar issues recently: https://github.com/bitwarden/clients/issues/7302
