### ISSUE TITLE
Updated Table Styles Feedback

### ISSUE THREAD

**Issue by michellescripts** [gravitational/teleport#39272]
This issue is to track feedback and issues related to the new table styles merged in https://github.com/gravitational/teleport/pull/37276

The initial scope was to update the table styles to be aligned with the table view in Unified Resources without any additional functionality (i.e., it does not include new search, pagination, filter, etc. functionality). The changes were scoped to be within the `design/src/DataTable` directory.

**All issues commented below should be tracked here:**

- [x] Integrations > Okta > Import: header is transparent
  - [x] https://github.com/gravitational/teleport.e/pull/3711
- [x] Account > Manage Devices > List With Devices: Hover causes rows to jump
  - [x] https://github.com/gravitational/teleport/pull/39435
- [x] New Lock Request > Servers/Desktops: Unnecessary shadow around the table
  - [x] https://github.com/gravitational/teleport/pull/39435
- [x] Access Requests > Roles : Unnecessary shadow around the table
  - [x] https://github.com/gravitational/teleport.e/pull/3711

**Comment by kimlisa** [comment]
more info:

the header is transparent:
http://127.0.0.1:9003/?path=/story/teleporte-integrations-enroll-okta--import
<img width="1285" alt="image" src="https://github.com/gravitational/teleport/assets/43280172/f97d5a51-4c39-4eaf-accc-ff06202dfae7">

when you hover over these rows, it does a slight jump:
http://127.0.0.1:9003/?path=/story/teleport-account-manage-devices-device-list--list-with-devices&globals=theme:Light%20Theme
<img width="1706" alt="image" src="https://github.com/gravitational/teleport/assets/43280172/ab6f6c24-e6ed-46ef-b9df-edabc3f56cf7">

**Comment by zmb3** [comment]
I'm a fan of this change overall, but I have two comments:

<img width="1403" alt="image" src="https://github.com/gravitational/teleport/assets/7527103/f7b81d0a-a63d-4d02-b975-4aad4386c6c3">

1. The empty state looks a bit awkward. Maybe a horizontal divider below the table header would help?
2. The search bar feels massive.

**Comment by gzdunek** [comment]
There is an unnecessary shadow around the table in New Lock Request > Servers/Desktops.

<img width="1079" alt="image" src="https://github.com/gravitational/teleport/assets/20583051/ea7e0ff2-9b73-48fb-ae9f-333fed804f1a">

**Comment by kimlisa** [comment]
think same issue as grzegorz

access request > new access request > roles

<img width="888" alt="image" src="https://github.com/gravitational/teleport/assets/43280172/51ea3a92-1952-4d76-89f5-bd1edb578dd9">

**Comment by zmb3** [comment]
@michellescripts @avatus are we good to close this one?

**Comment by avatus** [comment]
Yes I believe so
