### ISSUE TITLE
Configure access for Active Directory manually: cannot set minimum persmissions for service account

### ISSUE THREAD

**Issue by nlhomme** [gravitational/teleport#39289]
When configuring access for Active Directory manually on Step 1/7:
[https://goteleport.com/docs/desktop-access/active-directory-manual/#step-17-create-a-restrictive-service-account](https://goteleport.com/docs/desktop-access/active-directory-manual/#step-17-create-a-restrictive-service-account)

During the subsetp 3: `Set the minimum permissions that must granted to the service account by running the following script in the PowerShell console:`

I try to run the following command with Windows Powershell ISE (as Admin):
```
# Allow Teleport to read certificationAuthority objects in the NTAuthCertificates container.
dsacls "CN=NTAuthCertificates,CN=Public Key Services,CN=Services,CN=Configuration,$DomainDN" /I:T /G "$($SamAccountName):GR;certificationAuthority;"
```

Expected behavior:
The command should run succesfully

Current behavior:
The command fails with this error:
```
PS C:\Windows\system32> dsacls "CN=NTAuthCertificates,CN=Public Key Services,CN=Services,CN=Configuration,$DomainDN" /I:T /G "$($SamAccountName):GR;certificationAuthority;"
certificationAuthority est un type d'objet. Les autorisations valides sont CC (Cr‚er un enfant) et DC (Supprimer un enfant).
ParamŠtre incorrect. 
```

Which we can translate by:
```
PS C:\Windows\system32> dsacls "CN=NTAuthCertificates,CN=Public Key Services,CN=Services,CN=Configuration,$DomainDN" /I:T /G "$($SamAccountName):GR;certificationAuthority;"
certificationAuthority is a type of object. Valid authorizations are CC (Create a child) and DC (Delete a child).
ParamŠtre incorrect. 
```

Only this command fails, all others in the substep runs successfully.

I don't know what I'm doing wrong, espacially since the command has been approved in [Pull Request #35578](https://github.com/gravitational/teleport/pull/35578)
Can you help me?

Regards

Bug details:
- Teleport version: 15.1.3
- Windows Server 2022 Datacenter
- Recreation steps: Follow the documentation [Configure access for Active Directory manually](https://goteleport.com/docs/desktop-access/active-directory-manual/#step-17-create-a-restrictive-service-account)
- Debug logs: see command output above

**Comment by zmb3** [comment]
Thanks @nlhomme, I can reproduce the error you're seeing.

We will have a closer look soon, but in the meantime I would try just skipping that command and moving on with the rest of the steps.

**Comment by nlhomme** [comment]
Hello @zmb3 

Thank you for your answer.

Can you confirm that the Teleport server will access Windows even if this one command fails and I follow the rest of the steps?
To precise my question: imaging that the rest of the steps succeed, what will happend when a user want to open a session to a Windows server throught Teleport? I guess that something (I don't know what) will fail as well..?

Regards

**Comment by nlhomme** [comment]
Surely Teleport will not be able to access/read the CA certificate during NT authentication, so a Teleport user trying to open a session to a Windows Server will fail

**Comment by zmb3** [comment]
> Surely Teleport will not be able to access/read the CA certificate during NT authentication, 

I'm not as sure as you are.

1. Teleport doesn't need to read the CA certificate, Windows does.
2. I suspect that the NTAuth store is readable by all domain users.

**Comment by nlhomme** [comment]
Hello @zmb3,

I've gone through the rest of the step without the failing command.

The Windows hosts are discovered as expected.
But when we try to open a connection, console is open with the Windows login screen throwing an error "Signing in with a smart card isn't supported for your account":
![image(3)](https://github.com/gravitational/teleport/assets/9362475/821c3122-3833-4f95-91f2-41c925adb4ee)

It's the same error documented [here](https://goteleport.com/docs/desktop-access/troubleshooting/#smart-card-not-supported-for-account)

**Comment by zmb3** [comment]
Ok, that is a separate error. Have you gone through the Kerberos event logs as suggested in the docs linked above?

**Comment by nlhomme** [comment]
Yes and a fix is being tested
 I'll keep you informed if it the issue can be closed.

**Comment by nlhomme** [comment]
The fix has been sucessfully tested in our sandbox environment.
I think that the failing command can be removed
