### ISSUE TITLE
`client_idle_timeout` disconnects users performing long-running scp operations

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3933]
**What happened**: Reported by a customer, validated by me.

If `client_idle_timeout` is set and a client has an active file transfer via `tsh scp`, the client will be disconnected when the timeout hits. This is undesirable behaviour, as having an active file transfer should mean the client is not considered "idle". Big files can take a long time to transfer.

This is the case for transfers via web UI as well as `tsh`. I haven't tested native `scp`.

**What you expected to happen**: File transfers should be counted as activity and clients should not be disconnected while transferring files.

**How to reproduce it (as minimally and precisely as possible)**:

Set `client_idle_timeout` to something other than the default of `never` (using 30 seconds here for easy testing):
```yaml
auth_service:
  client_idle_timeout: 30s
```

```bash
# create a 1GB test file on a local client
$ dd if=/dev/urandom of=/tmp/testfile bs=1k count=1000k

# upload the test file to the cluster with the short timeout set
# observe that transfer stops after 30 seconds
$ time tsh scp /tmp/testfile root@example-east-auth-0:/tmp
-> /tmp/testfile (1048576000)
error: wait: remote command exited without exit status or exit signal
tsh scp /tmp/testfile root@example-east-auth-0:/tmp  1.23s user 0.98s system 7% cpu 30.595 total

# try the same thing in reverse, create a test file on the remote node
$ dd if=/dev/urandom of=/tmp/testfile bs=1k count=1000k

# try downloading the file instead
# observe the same timeout issue
$ time tsh scp root@example-east-auth-0:/tmp/testfile /tmp/incoming
<- /tmp/incoming (1048576000)
error: wait: remote command exited without exit status or exit signal
tsh scp root@example-east-auth-0:/tmp/testfile /tmp/incoming  2.36s user 1.62s system 12% cpu 30.814 total
```

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-alpha.2git:v4.3.0-alpha.2-0-gd9e436bdc go1.13.2`
- Tsh version (use `tsh version`): `Teleport v4.2.9 git:v4.2.9-0-ga4bd6c36 go1.13.2`
- OS (e.g. from `/etc/os-release`): `Fedora 31`

**Comment by alex-kovoy** [comment]
> This is undesirable behaviour, as having an active file transfer should mean the client is not considered "idle". Big files can take a long time to transfer.

@webvictim  Hm... these are bytes flying over the network without any user interaction. It could have been any other program not just scp.

**Comment by webvictim** [comment]
It could, but in the case of `tsh scp` or SCP via the web interface, we should not time a client out which has an active connection.

**Comment by russjones** [comment]
Best: 3
Worst: 5
