### ISSUE TITLE
Proxies may incorrectly believe that reversetunnel nodes are offline.

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport#3935]
Users have encountered a bug where proxies appear to believe that a reversetunnel node is not connected indicated by a `dial tcp: missing address` error (see #3467).  However, during this time the logs of the associated node indicate that it *is* connected to the target proxy.  I believe this may be due to a race and/or leak wherein the proxy continues to keep a tunnel alive after having discarded/replaced it.

One possible culprit is [`localSite.handleHeartbeat`](https://github.com/gravitational/teleport/blob/d2c03e90ee63139bf7176bd01194f1f599fdd5c5/lib/reversetunnel/localsite.go#L333) which appears to be able to continue to hold an ssh channel open after it has been marked as invalid.

**Comment by fspmarshall** [comment]
Update: I've been able to verify that proxies can definitely end up with orphan connections which produce the above error if the connection is marked as invalid in a way which doesn't trigger `handleHeartbeat` to close, or if the connection is overwritten inside of the `localSite` mapping for some reason.  I had to manually force the proxy to enter the bad state, but it is definitely conceivable that these issues could arise naturally due to degraded performance (they are basically timing/ordering errors).

Started prototyping a fix on [fspmarshall/proxy-rt-state](https://github.com/gravitational/teleport/compare/fspmarshall/proxy-rt-state).  Needs additional verification to ensure that this doesn't break any related behavior since this causes the proxy to be more agressive when it comes to closing tunnels after an error.

**Comment by russjones** [comment]
Best: 3
Worst: 5

**Comment by deemerby** [comment]
Hello @fspmarshall 
Could you please tell me when the bug will be fixed? (estimated release)
thank you in advance

**Comment by c1moore** [comment]
Is there a workaround for this while a solution is being considered/built?  I believe I'm running into this issue now.

**Comment by fspmarshall** [comment]
This should be fixed as of https://github.com/gravitational/teleport/pull/17899
