### ISSUE TITLE
Feature parity for Drone with Jenkins

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3936]
This is a checklist of current Teleport CI/CD processes running in Jenkins which we need to port to Drone.

#### Gravitational PRs
- [x] Automatically run linter against every PR and post feedback to Github
- [x] Automatically run unit tests against every PR and post feedback to Github
- [x] Automatically run integration tests against every PR and post feedback to Github
- [x] Run Kubernetes tests (see https://github.com/gravitational/teleport/pull/4045 where Kubernetes tests are failing in Jenkins but not in Drone)

#### Forks
- [x] Enable forks on the teleport repo so we can test external PRs in Drone, but separate out and gate the Enterprise git checkout to only running against `gravitational/*` repos so that we don't risk exposing Enterprise code
- [x] Gate other functionality in .drone.yml to `gravitational/*` repos too.

#### OSS
- [x] linux-amd64 **.tar.gz**
- [x] linux-amd64 **.rpm**
- [x] linux-amd64 **.deb**
- [x] linux-amd64 CentOS 6 **.tar.gz**
- [x] linux-i386 **.tar.gz**
- [x] linux-i386 **.rpm**
- [x] linux-i386 **.deb**
- [x] linux-armhf **.tar.gz**
- [x] darwin-amd64 **.tar.gz**
- [x] darwin-amd64 **.pkg**
- [x] darwin-amd64 **.pkg (tsh only)**
- [x] windows-amd64 **.zip (tsh only)**

#### Enterprise
- [x] linux-amd64 **.tar.gz**
- [x] linux-amd64 **.rpm**
- [x] linux-amd64 **.deb**
- [x] linux-amd64 CentOS 6 **.tar.gz**
- [x] linux-i386 **.tar.gz**
- [x] linux-i386 **.rpm**
- [x] linux-i386 **.deb**
- [x] linux-armhf **.tar.gz**
- [x] darwin-amd64 **.tar.gz**
- [x] darwin-amd64 **.pkg**
- [x] windows-amd64 .zip (tsh only - this is a copy of the OSS `tsh` but with an Enterprise name)

#### Enterprise FIPS
- [x] linux-amd64 **.tar.gz**
- [x] linux-amd64 **.rpm**
- [x] linux-amd64 **.deb**
- [x] linux-amd64 CentOS 6 **.tar.gz**

### Docker images (linux-amd64)
- [x] OSS
- [x] Enterprise
- [x] Enterprise FIPS

### AMIs
- [x] OSS
- [x] Enterprise
- [x] Enterprise FIPS

### Web Assets
 - [x] Merge to branch.

#### Docker images
- [x] Build and push Docker images with a temporary name during `tag` stage
- [x] Pull this image, retag it with the `production` name and push the updated tag to quay.io during `promote` stage
#### AMIs
- [x] Build AMIs during `tag` stage (but don't make them public)
- [x] Make AMIs public during `promote` stage

**Comment by russjones** [comment]
Best: 5 day.
Realistic: 15 days.

**Comment by webvictim** [comment]
This is done!
