### ISSUE TITLE
Able to select the reviewer while requesting access 

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#39390]
Expected behavior:

We should be able to select the approver from the list on the UI while requesting access. 

Current behavior:

Teleport access request currently selects all the reviewers based on the RBAC and send notifications to everyone. 

<img width="499" alt="Screenshot 2024-03-14 at 10 42 39 PM" src="https://github.com/gravitational/teleport/assets/13088331/1a16a9f4-0536-429c-9818-439e9c6e79fc">

Success Criteria:
- [ ] Add a button to clear all suggested reviewers
- [ ] Add a button to clear all selected roles (for resource access requests)

**Comment by zmb3** [comment]
Are you not able to edit the reviewers by removing them (the X button) or using the `EDIT` button?

**Comment by naidu-kjml** [comment]
If it would be 3 to 4 reviewers then its fine, but we have 100+ reviewers to remove everyone using X button, either there should be clear all, or the selections should be NIL by default

**Comment by trinadh444** [comment]
Hi, Any update on the feature request ?
