### ISSUE TITLE
OTP re-use gives server error EOF

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#39393]
Expected behavior:

Re-reusing a OTP would give either invalid or that this OTP is no longer valid.

Current behavior:

Re-using OTP gives a EOF error in adding a MFA

![image](https://github.com/gravitational/teleport/assets/60704961/896b6b8f-5744-4e6f-9dd3-f4a7fafaab31)

Bug details:
- Teleport version: 15.1.4
- Recreation steps

1. Go to Account settings in the UI
2. Start MFA and use a OTP to authenticate
3. Cancel and start MFA again with the same OTP

**Comment by bl-nero** [comment]
This error message doesn't come from our code. It most probably comes from [`grpc-go`](https://github.com/grpc/grpc-go/blob/4f43d2e91d2d3c0f9c37cf871bd3e2d322743f3e/internal/transport/http2_client.go#L1620). It would indicate that the auth server breaks the RPC connection in an ugly way before it's finished.

My hypothesis here is that the auth server crashes while serving this request, and I suspect this may be exactly the same issue as https://github.com/gravitational/security-findings/issues/97, as that one leads to a crash in a similar scenario.

I can't reproduce the issue locally, so I'd love to see some server logs. I'm waiting for @stevenGravy to provide it.

**Comment by stevenGravy** [comment]
Fixed by https://github.com/gravitational/teleport/pull/39407
