### ISSUE TITLE
Terraform Provider mapping values

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#39434]
## Applies To

https://goteleport.com/docs/reference/terraform-provider/

## Details

Provide the accepted values for Terraform configurations. There are some mappings from terraform format to others that do not have the same type in the roles yaml. An example is `create_host_user_mode` that is a number in terraform provider and
a string in roles.

## How will we know this is resolved?

Any attributes can be mapped from their terraform types to yaml. Especially for those that have a different type then the yaml version.

**Comment by stevenGravy** [comment]
RElated issue here but we should check how many of these there are. https://github.com/gravitational/teleport/issues/35497

**Comment by ptgott** [comment]
@stevenGravy Since the Terraform reference was revamped, does it resolve the issue? The description of `create_host_user_mode` explains the number-to-value mapping here: https://goteleport.com/docs/reference/terraform-provider/resources/role/#nested-schema-for-specoptions

**Comment by ptgott** [comment]
Fixed in https://github.com/gravitational/teleport/pull/42798, which makes it explicit that `create_host_user_mode` and other enums accept a number. As long as the comments above these fields indicate which numbers correspond to which options, this should be clear in the reference.
