### ISSUE TITLE
Ability to encapsulate teleport's traffic (node<->proxy) in a websocket tunnel

### ISSUE THREAD

**Issue by mikegarts** [gravitational/teleport#3944]
### Feature Request
Ability to encapsulate teleport's traffic (node<->proxy) in a websocket tunnel.
This is especially useful for iot-mode cases when the node can be located behind restrictive proxies.
We witnessed scenarios where teleport nodes were not able to communicate with the proxy, even in iot mode and our testing shows that websocket encapsulations solves the issue.

### Motivation
This feature would allow adoption of teleport in any environment without the need to reconfigure the existing network infrastructure. 

### Who's it for?
OSS User, Pro, Enterprise

**Comment by zmb3** [comment]
This is a pretty invasive change and not something we've seen much demand for, so I'm marking this as not planned.
