### ISSUE TITLE
Kubernetes Proxy UI lacks context 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3946]
### Feature Request
When setting up Teleport as a Kubernetes gateway / proxy. It's unclear from the UI that I've done so. 

![image](https://user-images.githubusercontent.com/559288/86151772-0771ce80-bab4-11ea-948e-a9328e623326.png)

For the User, it would be good to show their traits in the UI.

```  Logged in as: benarent
  Cluster:      teleport-eks
  Roles:        admin*
  Traits:       kubernetes_groups: [system:masters]
                kubernetes_users: []
                logins: [github ec2-user]
  Logins:       github, ec2-user
  Valid until:  2020-06-30 02:12:54 -0700 PDT [valid for 10h11m0s]
  Extensions:   permit-agent-forwarding, permit-port-forwarding, permit-pty
```

If we know that a Kubernetes config has been set, we should provide this info in the UI. 

```
    kubernetes:
      enabled: yes
      public_addr: teleport-eks-demo.com:3026
      listen_addr: 0.0.0.0:3026
      kubeconfig_file: /home/ec2-user/.kube/config
```
```
$ cat  /home/ec2-user/.kube/config
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:3333:cluster/teleport-eks
    user: arn:aws:eks:us-west-2:333:cluster/teleport-eks
  name: arn:aws:eks:us-west-2:3333:cluster/teleport-eks
current-context: arn:aws:eks:us-west-2:333:cluster/teleport-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:333:cluster/teleport-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - teleport-eks
      command: aws
```
e.g. We could use `name:` and provide that context in Teleport UI / Added to a Kube Cluster CLI command. 

### Motivation
Describe why we should work on this feature request.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by benarent** [comment]
@awly if you have any more thoughts, on the presentation of Kubernetes. Please add them here.

**Comment by awly** [comment]
As part of [5.0 k8s enhancements](https://docs.google.com/document/d/1cS6J2d_xBcJMWPewWPjdOZyrDHLKdqmgF1QLLo4E1YI/edit) we can add a separate UI page listing all k8s clusters. This would be a good place to surface any kubeconfig info (most likely we should only show the server address).

As for the `tsh` experience: https://github.com/gravitational/teleport/issues/3447

**Comment by awly** [comment]
Closing this in favor of https://github.com/gravitational/teleport/issues/5086
Trusted cluster != kubernetes clusters anymore
