### ISSUE TITLE
APT package channel stable/cloud have been switched to v15 although our cloud instance is still in v14

### ISSUE THREAD

**Issue by mtparet** [gravitational/teleport#39505]
Expected behavior:

Upgrade channel cloud/stable to next major only when all client instances are upgraded.

Current behavior:

Teleport clients and agents are broken because automatically (when upgrading the system) upgraded to v15 although cloud instance is in v14.

Bug details:
- Teleport version : v14
- Recreation steps : Use teleport cloud with current v14 version, install teleport agent on ubuntu, run apt-get upgrade, teleport agent is upgraded to v15 and failed to connect to v14 proxy.
- Debug logs

**Comment by mtparet** [comment]
We used the "enroll resources" bash script which auto configure cloud/stable

**Comment by zmb3** [comment]
Tracking this at #39215
