### ISSUE TITLE
Improve default AD automatic discovery for Desktop Access

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#39526]
**What would you like Teleport to do?**
Improve the default discovery capabilities of the Windows desktop service to only discover windows machines.  Currently, the wildcard '*' character discovers all hosts in the Active Directory domain including Linux hosts and disabled machines regardless of their operating system.  
```
  discovery:
    base_dn: '*'
```
**What problem does this solve?**
This behaviour causes unintended enrollment of machines that are not relevant for Windows Desktop access (such as Linux servers or disabled/decommissioned machines) and also clutter of resources in the Teleport portal. 

**If a workaround exists, please include it.**
Use WDS LDAP filters for further customizing the LDAP search.

**Comment by zmb3** [comment]
This is a duplicate of #14116 and is a stretch goal for this quarter.
