### ISSUE TITLE
Kubernetes Enhancements

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3952]
RFD: https://github.com/gravitational/teleport/pull/4455

- [x] add `kubernetes_service` to `teleport.yaml`
- [x] add `kube_listen_addr` to `proxy_service`
- [x] reverse tunnels (IoT mode) for `kubernetes_service`
- [x] k8s proxy request routing to `kubernetes_service`
- [x] support multiple clusters in `kubeconfig`
- [x] RBAC for k8s
  - [x] labels on k8s clusters
  - [x] `kubernetes_labels` filter on roles
- [x] complete k8s audit logs (all requests)
- [x] `tsh`
  - [x] list/switch clusters
  - [x] exec plugin for `kubectl`
- [x] register k8s clusters handled by proxies
- [ ] helm one-liner to deploy proxy in k8s cluster
- [ ] migration guide
- [ ] update test plan

**Comment by awly** [comment]
All core functionality is in. Remaining tasks are docs and deployment tooling.
