### ISSUE TITLE
[docs] Need to clarify session join role intersection behavior

### ISSUE THREAD

**Issue by jentfoo** [gravitational/teleport#39525]
## Applies To

https://goteleport.com/docs/access-controls/guides/moderated-sessions/#configure-an-allow-policy

## Details

In our docs we specifically describe that joining sessions can be done with any session with a user who has a matching role.  This is accurately described, but I don't believe is very clear to our customers.

![image_720-1](https://github.com/gravitational/teleport/assets/2165757/3ce5d622-b4e5-412d-94be-dff568656153)

Given the current description I believe most customers would believe that in order to join a session using this role, the session would need to be able to be initiated using the `prod-access` role.  However the behavior is actually such that a session is joinable if started by a user using another role, but which the user also has the `prod-access` role associated to their account.

## How will we know this is resolved?

We should clarify that it is not the `prod-access` role used to determine if the specific session can be joined, instead it's the presence of the role on the account.

## Related Issues

Prior clarifications: https://github.com/gravitational/teleport/pull/14149/
Internal security issue: https://github.com/gravitational/teleport-private/issues/1421

**Comment by zmb3** [comment]
The docs are correct as-is.
