### ISSUE TITLE
Skipping tls verification in K8S configuration?

### ISSUE THREAD

**Issue by taikai-zz** [gravitational/teleport#39550]
Add the -- insecure parameter to the command line to skip validation,

How to configure skipping tls validation in K8S?

**Comment by tigrato** [comment]
@taikai-zz what do you mean by skipping tls validation in k8s?

Do you mean skipping the tls validation between Teleport kubernetes service and your Kubernetes Cluster API  server or do you mean between a user kubectl and Teleport proxy?
