### ISSUE TITLE
Fix Missing Helm Chart Icon

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#39570]
Please update the referenced Helm charts to fix the missing icon.

Expected behavior:
Charts should link to Teleport's symbol logo svg located here: 
https://goteleport.com/static/teleport-symbol-bimi.svg

Current behavior:
Charts are currently linking to the following missing file, resulting in 100's of 404 error messages per minute.
https://goteleport.com/images/logos/logo-teleport-square.svg

Referenced Helm charts:
- https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/Chart.yaml#L8
- https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/Chart.yaml#L8
- https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/charts/teleport-operator/Chart.yaml#L8

**Comment by harshit-paneri** [comment]
Hey @travelton

I checked the referenced Helm chart file and found that the path for the "icon" is incorrect. When I opened the path, there was no SVG file found.
