### ISSUE TITLE
Check resource count before showing "add my first resource" modal

### ISSUE THREAD

**Issue by flyinghermit** [gravitational/teleport#39595]
### Expected behavior:

The "add my first resource" modal is shown only when resource count is zero.

### Current behavior:

I added resource (a SAML application) using `tctl`. But then signing into web UI still shows me the modal. 

<img width="1618" alt="Screenshot 2024-03-19 at 6 02 53 PM" src="https://github.com/gravitational/teleport/assets/10177602/55e53473-64a8-4446-980d-c2bbc1063c7c">

Bug details:
- Teleport version: latest

**Comment by zmb3** [comment]
This may be due to SAML apps not being counted - see #31556.

**Comment by flyinghermit** [comment]
Addressed with https://github.com/gravitational/teleport/pull/45355
