### ISSUE TITLE
Dark mode toggle for Teleport Connect

### ISSUE THREAD

**Issue by tuladhar** [gravitational/teleport#39655]
What would you like Teleport to do?

- Add toggle option to switch to dark mode, currently, it's based on system apperance.

What problem does this solve?
- Use Teleport Connect in dark mode without turning on system wide dark appearance.

If a workaround exists, please include it.
- Enable system wide dark mode appearance. Atleast on Mac.

**Comment by zmb3** [comment]
There is no requirement to change the system theme. Following the system theme is the default behavior, but you can configure light or dark mode along with other teleport connect configuration by following the configuration docs: https://goteleport.com/docs/connect-your-client/teleport-connect/#configuration
