### ISSUE TITLE
Provide ability to view enhanced logging commands and networking in web and tsh

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3967]
### Feature Request
Currently the enhanced logging contents are only available by the session file logs in the auth server or extracting from the High Availability storage.  We should make the contents viewable through the UI and/or tsh.  Perhaps in a table format.  

### Motivation
Users would get more value with the enhanced logging by being able to directly access the command and networking logs for given sessions without using other manual or configured extraction. 

### Who's it for?
OSS User, Pro, Enterprise

**Comment by benarent** [comment]
We already have designs for this ( and some code implemented ) we can come back and review this in 5.0. @alexwolfe Can you review the previous designs with all of our changes in 4.3

**Comment by benarent** [comment]
@stevenGravy I tested this morning and you do get a lot out of the box. 
![image](https://user-images.githubusercontent.com/559288/86387245-c01c4700-bc47-11ea-9dfb-6fe9fe982186.png)

**Comment by stevenGravy** [comment]
I'll close then @benarent

**Comment by stevenGravy** [comment]
Misread.  I do think it's a good idea to be able to get all the commands and network activity for a given id.  Useful for auditors

**Comment by webvictim** [comment]
Can you put an ID in the search box to drill down?

**Comment by alex-kovoy** [comment]
@benarent  i've updated BPF descriptions.

![image](https://user-images.githubusercontent.com/7816406/86522527-5362a180-be2d-11ea-9b3c-8c58c1653733.png)
