### ISSUE TITLE
Make it easier to update the list of principals for a user.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3973]
Right now if you want to update the list of principals for a user, you have to first do `tctl get users/foo > file.txt`, open the file, update the principals, then do `tctl create -f users.yaml`. We should think about easier ways to do this.

One option would be adding `tctl edit <resourceName>` which will download the resource and open it the editor you have set in the `EDITOR` environment variable. Once you save and close your editor, we do a `tctl create -f <temp.file>` automatically.

**Comment by Valien** [comment]
Another way (might simplify quick updates) is doing a `tctl update users/<user> --add-role=<new role>` or something similar. Could also add something like `--delete-role` or other user functions.

**Comment by zmb3** [comment]
This is resolved with `tctl users update --set-logins x,y,z`
