### ISSUE TITLE
Can't add kibana through teleport app_service

### ISSUE THREAD

**Issue by asamirr** [gravitational/teleport#39766]
Currently on AKS with ELK installed and kibana service working properly whenever tested using port-forward
Tried adding it to Teleport apps to restrict its access.

Expected behavior:
Kibana opens and I'm able to navigate it.

Current behavior:
Internal server error whenever I launch it.

Bug details:
- Teleport version
14.3.3
- Recreation steps
Deploy ELK on kubernetes and then add it's configuration to teleport configmap
`

 apps:

      - name: 'kibana'
        uri: http://kibana.monitoring.svc.cluster.local/
        public_addr: "kibana.teleport.example.com"
        insecure_skip_verify: false
        labels:
          app: kibana
        rewrite:
          headers:
          - "Host: kibana.teleport.example.com"
          - "Origin: https://kibana.teleport.example.com/"
`
- Debug logs
`2024-03-25T13:31:44Z ERRO [APP:SERVI] Error forwarding to http://kibana.monitoring.svc.cluster.local/, err: dial tcp 10.0.157.103:80: i/o timeout reverseproxy/reverse_proxy.go:231
2024-03-25T13:32:14Z ERRO [APP:SERVI] Error forwarding to http://kibana.monitoring.svc.cluster.local/favicon.ico, err: dial tcp 10.0.157.103:80: i/o timeout reverseproxy/reverse_proxy.go:23`

**Comment by tigrato** [comment]
Is Your Kibana kubernetes service running on port 80?
The i/o timeout comes from the fact that Teleport can't dial to Kibana

**Comment by asamirr** [comment]
@tigrato Worked. The kibana service had both `port` and `targetPort` set to 5601. Changed the `port` only to 80 and worked. Will update if any more issues arise. Thanks a lot!
