### ISSUE TITLE
Improve UX for empty state in Sessions tab

### ISSUE THREAD

**Issue by twakes** [gravitational/teleport#3980]
### Feature Request
I've attached what you see in the Sessions tab when there are no active Sessions - just a lame "No Sessions Found" message. Instead we should have a CTA to create a new session (or launch the terminal UI), like we have when you close a Session in a new tab. I've also attached a screenshot of that. 

By the way, I'd change the name of the tab to "Active Sessions". I was looking here for expired sessions and then found them in the Audit Log.

### Motivation
Help the user figure out what to do.

### Who's it for?
Web interface users.

<img width="1250" alt="Screen Shot 2020-07-02 at 3 04 15 PM" src="https://user-images.githubusercontent.com/3769197/86413328-c45f5900-bc75-11ea-8a4b-94ce39923c66.png">
<img width="432" alt="Screen Shot 2020-07-02 at 3 03 57 PM" src="https://user-images.githubusercontent.com/3769197/86413329-c4f7ef80-bc75-11ea-810a-d7b1e7b29825.png">

**Comment by twakes** [comment]
As a followup, the empty state for Trusted Clusters is great and a good example for what should be in "Sessions"

<img width="1278" alt="Screen Shot 2020-07-02 at 3 29 41 PM" src="https://user-images.githubusercontent.com/3769197/86414551-15248100-bc79-11ea-859e-33afee3833c9.png">

**Comment by benarent** [comment]
Thanks for the ticket @twakes , it's been updated to say 'Active Sessions' 
![image](https://user-images.githubusercontent.com/559288/86806751-07327f80-c02e-11ea-8351-2bcb66bba589.png)

but I agree it could use some polish. Assigning to Wolfe to review.
