### ISSUE TITLE
phenomenon where the process remains

### ISSUE THREAD

**Issue by veranderson** [gravitational/teleport#39821]
Expected behavior: 
Abnormally terminated processes remain on the Teleport Node server and are taking up resources.

For example : I logged out of Teleport Connect, but the process remains.
In most cases, connections and terminations are normal, but the phenomenon occurs at unspecified times.
Does anyone know a solution for this case?
![image](https://github.com/gravitational/teleport/assets/156073041/d6c80a88-d79a-4ba6-af94-eddd2e80082e)

Current behavior: 
The connection has been terminated, but it remains and is occupying resources.

Bug details:
- Teleport version : Teleport v14.2.2 git:api/v14.2.2-0-gcb615fe417 go1.21.5
- Recreation steps
- Debug logs : None

**Comment by zmb3** [comment]
@ravicious could this be related to #27125?

**Comment by veranderson** [comment]
@zmb3, @ravicious Thanks for the advice. It was very helpful.
We will observe the phenomenon through version upgrade. :-)
