### ISSUE TITLE
Access Requests default to Roles section/selection

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#39852]
What would you like Teleport to do?
When a user makes an access request; default the landing page to the Roles section for an Access Request.

What problem does this solve?
Prevents users from choosing the correct role for auto approval vs them selecting individual resources and the auto approval not being engaged.

If a workaround exists, please include it.
Educating users to select the 'Roles' dropdown.

**Comment by zmb3** [comment]
See https://github.com/gravitational/teleport/issues/37249#issuecomment-1910380329
