### ISSUE TITLE
Very small fraction of nodes get stuck during startup

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport#3985]
When running tests for the 4.3 release (10k IoT nodes with DynamoDB backend),  approximately 0.25% of nodes froze during initial startup and never successfully joined the cluster (no timeout errors ever occurred).  I'm not 100% certain where they froze, but based on the final logs, it appears it was somewhere early in the startup process:

```
...
DEBU [AUTH]      Attempting to register through proxy server. auth/register.go:143
DEBU [CLIENT]    HTTPS client init(proxyAddr=example.com, insecure=false) client/weblogin.go:295
DEBU [AUTH]      Successfully registered through proxy server. auth/register.go:132
DEBU [PROC:1]    Deleted generated key pair Node first-time-connect. service/connect.go:242
INFO [PROC]      Node has obtained credentials to connect to cluster. service/connect.go:377
DEBU [PROC]      Attempting to connect to Auth Server directly. service/connect.go:795
DEBU [PROC]      Attempting to connect to Auth Server through tunnel. service/connect.go:803
DEBU [CLIENT]    HTTPS client init(proxyAddr=example.com, insecure=false) client/weblogin.go:295
DEBU [PROC]      Discovered address for reverse tunnel server: example.com. service/connect.go:883
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
```

All nodes appear to have frozen in the same place.  Some of the nodes had `SLOW TRANSACTION` warnings from sqlite after this point, but since I've seen those warnings in some of the logs of nodes which didn't freeze, I don't think they are causally related.

**Comment by klizhentas** [comment]
@fspmarshall likely not a regression, so should not block a release - as you recall we have observed that for 4.2 release as well as some previous ones.

**Comment by fspmarshall** [comment]
We haven't seen this in a long time.  Likely that this has been fixed incidentally.  Will reopen if we start hitting this again.
