### ISSUE TITLE
Move event-handler README information into the docs

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#39886]
## Applies To

https://goteleport.com/docs/management/export-audit-events/fluentd/#start-the-teleport-event-handler

## Details

We should provide a link to the event-handler [github repo](https://github.com/gravitational/teleport-plugins/tree/master/event-handler) that has more information on setting up this plugin. A new customer or someone new to the plugin would benefit from this information. 

## How will we know this is resolved?

A visible link to the event-handler plugin github repo in the [next steps](https://goteleport.com/docs/management/export-audit-events/fluentd/#next-steps
) section is sufficient.

**Comment by ptgott** [comment]
We could also incorporate this information into the `export-audit-events` section of the docs as a reference guide

**Comment by zmb3** [comment]
Closing in favor of #37842
