### ISSUE TITLE
Unable to delete GitHub auth connector from OSS

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3988]
**What happened**:
In the open source version of Teleport it is not possible to delete a GitHub connector. Trying to use tctl to delete a GitHub connector results in an error.

**What you expected to happen**:
I should be able to use the following to delete a GitHub connector:
`tctl rm connector/github`

**How to reproduce it (as minimally and precisely as possible)**:
`tctl rm connector/github`

### Environment
- Teleport version (use `teleport version`): 4.2.10 Open Source
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by webvictim** [comment]
This is a docs bug - it's fixed in #3977.

@benarent We might need to push the docs to pick that up?

**Comment by benarent** [comment]
I'm going to close this, It will go out with the 4.3 docs.
