### ISSUE TITLE
`tsh kube login <name>` overwrites config

### ISSUE THREAD

**Issue by fbuetler** [gravitational/teleport#39930]
Expected behavior:
The command `tsh kube login <name>`, to download the kube config onto a host, adds the configuration to the existing ones (like context, users and cluster).

Current behavior:
The command deletes all content in the configuration file and fills in its own configuration.

Bug details:
- Teleport version

```
➜ tsh version
Teleport v15.1.10 git:v15.1.10-0-gfc3b2b3 go1.21.8
Proxy version: 15.1.9
```

- Recreation steps

```
export KUBECONFIG=${HOME?}/kubeconfig.yaml # non-empty/containing configuration for a different cluster
tsh login --proxy=<proxy-addr> <addr>
tsh kube login <name>
```

**Comment by tigrato** [comment]
@fbuetler are you sure about that? 
I tried the process and `tsh kube login` appended a cluster, context, and user for Teleport but maintains the old config.
Look that `tsh kube login` updates the kubeconfig and changes the default context.

**Comment by fbuetler** [comment]
I just tried to reproduce the issue but failed. It is correctly added to en existing kubeconfig as you said and I suggested. However, some kind of combinations of events originally resulted in my existing kubeconfig being overwritten.

Closing as non-reproducible.
