### ISSUE TITLE
Web-ui does update the list of resources

### ISSUE THREAD

**Issue by behnambm** [gravitational/teleport#39945]
Expected behavior:
When a resource gets deleted using `tctl` the web-ui should not list that resource anymore.

Current behavior:
The web-ui show a removed resource in the list of resources.

![image](https://github.com/gravitational/teleport/assets/26994700/7a96f3b8-cc2e-45f5-8d81-1ca9127a8224)

I still get the `dbpg` in the list of resources.

![image](https://github.com/gravitational/teleport/assets/26994700/946aaaec-1194-4605-bd03-44a162aec02f)

Bug details:
- Teleport version: `Teleport v15.1.7 git:v15.1.7-0-g71df538 go1.21.8`
- Recreation steps
- Debug logs

**Comment by stevenGravy** [comment]
@behnambm was this removed from the config first, the Teleport service then restarted first? since this is a config file created service, not dynamic, it should be removed from the Teleport databaes service config file.

**Comment by behnambm** [comment]
@stevenGravy As far as I know the database server went down so there was no re-register. Teleport restarted but nothing changed.

**Comment by stevenGravy** [comment]
The Teleport database service will still show databases configured whether the database itself is up or down that it points to.  Can you confirm if the Teleport agent that had this database configured in Teleport was still running?

**Comment by behnambm** [comment]
@stevenGravy Confirmed. The server is down.

**Comment by behnambm** [comment]
@stevenGravy I tried running this and got no output. `tctl get all | grep dbpg`

**Comment by stevenGravy** [comment]
Please refresh the page in the proxy and do a `tctl db ls`.  In most cases after 10 minutes the database should no longer show if the Teleport database service is no longer running.

**Comment by behnambm** [comment]
![image](https://github.com/gravitational/teleport/assets/26994700/62e16a00-2c78-4883-8c88-e19b5b905d8e)

there is no database

**Comment by behnambm** [comment]
Thanks Steven, it seems that the Teleport agent was the problem. 

@stevenGravy
