### ISSUE TITLE
Desktop access: mouse cursor disappears or gets stuck

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#39986]
The custom mouse cursor behavior in 15.1 can sometimes cause the mouse cursor to disappear completely, and other times cause it to get stuck as a custom icon instead of the standard pointer.

**Comment by doabu** [comment]
I see the same in Teleport version 15.2.0.
To reproduce: open notepad and start typing.
The mentioned workaround works aswell, disabling the mouse pointer shadow makes the problem disappear.
I was able to reproduce this on Server 2016 and Server 2019.
On Server 2022 the issues was not there.
