### ISSUE TITLE
Document SSH access using EC2 Instance Connect Endpoint

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#40020]
## Applies To
Create a page describing how to use and the supported features for the EICE access.

Similar to this page: https://goteleport.com/docs/server-access/openssh/openssh/

## Related Issues
https://github.com/gravitational/teleport/issues/29317
https://github.com/gravitational/teleport/pull/35504
https://goteleport.com/blog/aws-ec2-instance-connect/

**Comment by zmb3** [comment]
@marcoandredinis @r0mant should we mark this not planned given the limitations of the EICE flow?

**Comment by marcoandredinis** [comment]
I think so, but I'll defer that to Roman
