### ISSUE TITLE
Error with trusted cluster prevents accessing 

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4005]
### Description

**What happened**:

Logging into the web shows the following error with no way of navigating into the cluster.

![image](https://user-images.githubusercontent.com/60704961/87061188-70a2c180-c1d9-11ea-822e-2472c7c90537.png)

Removing and recreating the trusted clusters appeared to resolve the issue.  

`tsh` access was still available.

**What you expected to happen**:

If there is an error with a particular cluster the individual cluster would indicate an error and the user can still navigate to clusters that are accessible.

**How to reproduce it (as minimally and precisely as possible)**:

Create a configuration with two teleport clusters with one trusting the other.  Stop both. Reset the root cluster /var/lib/teleport so it's CA changes. Restart.  Attempt to login with the web.

### Environment
- Teleport version (use `teleport version`): 4.3
- Tsh version (use `tsh version`): 4.3
- OS (e.g. from `/etc/os-release`): AWS linux 2

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): aws ec2

**Browser environment**

- Browser Version (for UI-related issues): Chrome 84

**Comment by russjones** [comment]
@stevenGravy Is this related to OTP?

**Comment by russjones** [comment]
Best: 1
Realistic: 3
