### ISSUE TITLE
Quickstart UI invalid username

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4008]
### Description

**What happened**:
Quick launch doesn't account a `.` in the username. e.g. `ben.arent@host`

![image](https://user-images.githubusercontent.com/559288/87075732-a6de4200-c1d5-11ea-89aa-94c7309bf119.png)

**What you expected to happen**:
Within reason, we should let customers input. Within the limits of linux username, e.g. a Ec2 instance allows a username with up to 256 characters. 

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`): 4.3.0

**Comment by webvictim** [comment]
We should fix this in 4.3.1. The regex was already changed to allow `-` in an early 4.3.0 alpha.

**Comment by benarent** [comment]
We should also consider this PR https://github.com/gravitational/teleport/pull/4002

**Comment by alex-kovoy** [comment]
@kimlisa lets simplify that validation rule by checking 

1. if not empty
2. if no spaces.

**Comment by russjones** [comment]
Best: 1
Realistic: 2
