### ISSUE TITLE
Machine ID: Kubernetes Services

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#40117]
Today, Kubernetes Access and Machine ID can be awkward in situations where there are a number of Kubernetes clusters you need to access or where these Kubernetes clusters are ephemeral. The new service architecture is more flexible than the legacy Output types and introducing a service for Kubernetes will allow us to solve several problems that exist today with Machine ID and Kubernetes Access.

Goals:

- Support connecting to more than one Kubernetes cluster. Ideally, this should be reactive to new clusters being onboarded without a restart of `tbot`.
- Support a large number of clusters (e.g tens/hundreds) without a significant degradation in performance.
- Support cases where tunnelling is required to negotiate a L7 LB between the client and the Teleport Proxy. Currently we require the user to separately execute `tbot proxy kube` for this.

Selecting which Kubernetes clusters will be accessible via the service can be done using the name of the cluster or label selectors.

We can leverage watchers to support regenerating the configurations when new Kubernetes clusters are onboarded.

### `kubernetes-tunnel` Service

One option is to have the service expose a listener and a kubeconfig file will be output that directs the Kubernetes API requests via the listener. This is very similar to the existing functionality of `tsh kube proxy`. This service could request certificates on-the-fly as-needed and this would reduce the amount of signing requests tbot needs to make to the Teleport Auth Service when idle.

This implementation would also easily supports cases where a L7 LB is configured and some form of a local proxy (today using `tbot proxy kube`) is necessary.

This tunnel listener may not be suitable in cases where:

- `tbot` running in the background as a daemon is awkward (e.g ephemeral CI/CD systems)
- `tbot` runs in a location separate from where the credentials will be consumed. There may not be network connectivity between that location and `tbot`. We could just require that you move `tbot` into that environment.

### `kubernetes-kubeconfig` Service

If we determine that the tunnel is not fit for all use cases, then we likely need an implementation which directly outputs the credentials for each cluster into a single kubeconfig file - this is more similar to the existing implementation of the Kubernetes output today.

We would need to think about how this would work with an L7 LB in front of the proxy, the current `tsh kube proxy` implementation may not currently support loading credentials from an existing `kubeconfig` file.

**Comment by strideynet** [comment]
Could replace https://github.com/gravitational/teleport/issues/31753

**Comment by strideynet** [comment]
I think the biggest challenge is deciding between `kubernetes-tunnel` and `kubernetes-kubeconfig` - I think perhaps as the kubeconfig variant is most similar to the existing implementation of the Output, we probably ought to build the tunnel variant first. I think this offers the most value add over what we have today and the limitations could likely be worked around.

**Comment by strideynet** [comment]
Closing this in favour of reworking the Output type - as of today and having spoken to three of our larger k8s access Machine ID customers - it seems clear that compatibility with tools like ArgoCD is more important.

**Comment by oche-jay** [comment]
> Closing this in favour of reworking the Output type - as of today and having spoken to three of our larger k8s access Machine ID customers - it seems clear that compatibility with tools like ArgoCD is more important.

Hi @strideynet , as per your comment , I was wondering if you have any work planned to make Machine ID outputs more compatible with ArgoCD specifically.

**Comment by strideynet** [comment]
> > Closing this in favour of reworking the Output type - as of today and having spoken to three of our larger k8s access Machine ID customers - it seems clear that compatibility with tools like ArgoCD is more important.
> 
> Hi [@strideynet](https://github.com/strideynet) , as per your comment , I was wondering if you have any work planned to make Machine ID outputs more compatible with ArgoCD specifically.

There's a ticket at https://github.com/gravitational/teleport/issues/43403 for this on our roadmap.

**Comment by oche-jay** [comment]
Thanks, do you have a rough idea when this might become available? @strideynet
