### ISSUE TITLE
Cannot join an active session on some of the clusters (4.3)

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#4012]
The endpoint which returns an active session information _may_ return an empty `cluster_name` field  (which has been added in 4.3) thus preventing webui from joining a session. This has been observed on cluster upgraded from 4.2 to 4.3 using the dir storage.

/v1/webapi/sites/:siteID/sessions/:SID

```js
{
  id: "XX"
  namespace: "default"
  parties: [{id: "XXX", remote_addr: "XXX",…}]
  terminal_params: {w: 80, h: 25}
  login: "root"
  created: "2020-07-10T16:08:25.033352638Z"
  last_active: "2020-07-10T16:08:25.033354254Z"
  server_id: "61ada453-eb22-4692-b07f-9c729ad35b83"
  server_hostname: ""
  server_addr: ""
  cluster_name: ""
}
```

There are 2 things that we can do:

1. Understand why cluster_name might be empty.
2. If we cannot guarantee an availability of this field after upgrading from 4.2 to 4.3 then make UI more resilient - if empty, take this value from URL.

**Comment by stevenGravy** [comment]
This is specifically happening with a 4.2.X agent with a 4.3.0 proxy/auth. A 4.3.0 agent works.  Note that the webui is that part that doesn't work.  `tsh` joining does work.

**Comment by russjones** [comment]
Best: 1
Realistic: 2
