### ISSUE TITLE
`session.command` event hits a `ConditionalCheckFailedException` on dynamoevents

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport#40126]
Expected behavior:
`session.command` events are stored in the audit log even when using the DynamoDB events backend.

Current behavior:
`sesssion.command` events fail to get stored, reporting a `ConditionalCheckFailedException` error from DynamoDB.

Bug details:
All `session.command` events are emitted with the session ID of the session they belong to, and an event index of 0. DynamoDB uses (session ID, event index) as a primary key for the event, so prior to #38495 each `session.command` event overwrote the initial `session.start` event at first, and then all the other `session.command`s that took its place; now we refuse to overwrite events, rejecting the event and storing an error.

A similar issue exists for a different event (#39833), suggesting that perhaps we should fix the problem in a more general way rather than chase individual instances of event indexes not being set correctly for a session event.

- Teleport version: 15.2.0, but it's likely that we've only just noticed now that we're logging errors rather than overwriting.

**Comment by andreyzhelnin-st** [comment]
Having same issue with Web App published.
```
Stack Trace:
github.com/gravitational/teleport/lib/events/emitter.go:305 github.com/gravitational/teleport/lib/events.(*MultiEmitter).EmitAuditEvent
github.com/gravitational/teleport/lib/events/emitter.go:177 github.com/gravitational/teleport/lib/events.(*CheckingEmitter).EmitAuditEvent
github.com/gravitational/teleport/lib/events/emitter.go:98 github.com/gravitational/teleport/lib/events.(*AsyncEmitter).forward
runtime/asm_arm64.s:1197 runtime.goexit
User Message: ConditionalCheckFailedException: The conditional request failed
```

**Comment by espadolini** [comment]
@andreyzhelnin-st the PR that exposed this issue (#38495) was specifically to fix app access events; could you ensure that the `app_service` agent is up to date?

**Comment by andreyzhelnin-st** [comment]
> @andreyzhelnin-st the PR that exposed this issue (#38495) was specifically to fix app access events; could you ensure that the `app_service` agent is up to date?

The agent was version 15.0.2, I have just updated to 15.2.0 and it helps.
