### ISSUE TITLE
Allow Subnet and SecurityGroup selection when using Discover Auto-Enroll RDS flow (AWS OIDC Integration)

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#40174]
What would you like Teleport to do?
Select which Subnets and Security groups to apply when deploying the service.
![image](https://github.com/gravitational/teleport/assets/689271/2bcfc208-c30a-4c79-8052-f4cb554e43b1)

What problem does this solve?
Currently, it picks all the Subnets found in the RDSs and uses the default Security Group for the VPC.
Those settings might not work for some use cases (eg, default SG is very restrict).

If a workaround exists, please include it.

**Comment by GavinFrazar** [comment]
Closed with https://github.com/gravitational/teleport/pull/44671
