### ISSUE TITLE
Sometimes server invalidates the token (and a session) even though the token has not been expired.

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#402]
Sometimes server invalidates the token (and a session) even though the token has not been expired.

**Comment by kontsevoy** [comment]
I am marking this as "invalid" for now: you haven't provided much detail to reproduce this. Next time you see this, can you please:

- Attach the server log
- Make a tarball from `/var/lib/teleport` and attach that also

Thanks.

**Comment by kontsevoy** [comment]
closing for now to clan up the view. lets reopen if this shows up again. (I am betting it was a result of merging during web client redesign)
