### ISSUE TITLE
`TestBotDatabaseTunnel` flakiness

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#40228]
This was originally caught in the nightly test reporter: 

https://github.com/gravitational/teleport.e/actions/runs/8536817828/job/23386134208

Failure logs from a run that included the changes introduced in https://github.com/gravitational/teleport/pull/40179:

https://github.com/gravitational/teleport/actions/runs/8561027639/job/23461322763?pr=40227

**Comment by strideynet** [comment]
Looks like it's related to https://github.com/gravitational/teleport/issues/13501
