### ISSUE TITLE
Web UI should not repeat the name of the root cluster in URLs

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#40245]
## What would you like Teleport to do?

Today if I want to make a new access request or list active sessions, I'm redirected to a URL which looks like this:

```
https://ravicious.cloud.gravitational.io/web/cluster/ravicious.cloud.gravitational.io/sessions
https://ravicious.cloud.gravitational.io/web/cluster/ravicious.cloud.gravitational.io/requests/new
https://foo.teleport.sh/web/cluster/foo.teleport.sh/requests/new
```

If the URL is supposed to show me sessions in the root cluster, it should avoid repeating the name of the root cluster which is already in the URL. Especially since for all Cloud clusters `root cluster name == root cluster proxy host` (that's not necessarily the case for self-hosted clusters).

## What problem does this solve?

It makes the URLs in the Web UI a bit tidier for [the overwhelming majority of our users who use just a single cluster](https://reporting-grafana-prod.platform.teleport.sh/d/c770d134-9a11-4ae3-a593-57d4a4eee5c3/teleport-connect?orgId=1).

Using just `/web/sessions` and `/web/requests/new` could be a slight issue in the future if we decided that we want to support both kinds of views – `/web/sessions` which shows sessions from all clusters and `/web/cluster/<root cluster>/sessions` which shows sessions only from a specific cluster. However, I don't think it'd really be that much of a problem.

**Comment by zmb3** [comment]
Note that the cluster name and its `public_addr` are often the same, but that doesn't have to be the case.

See also #2123

**Comment by zmb3** [comment]
Closing this one not planned, though we will have #2123 if we ever get around to redoing the URL structure of the web app.
