### ISSUE TITLE
Document propagating k8s groups and logins between main and leaf clusters 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4024]
## Summary
> there used to be a section about propagating k8s groups and logins between main and leaf clusters and now I can’t find it
the one about “internal.*” variables in the roles and how that works in the context of trusted clusters 

via @r0mant 

### Audience
Kubernetes users / Gravity users. 

### Location
Kubernetes Guide.

**Comment by webvictim** [comment]
This is on https://gravitational.com/teleport/docs/ver/4.2/trustedclusters/ under the "Sharing Kubernetes groups between Trusted Clusters" section. Guess it got pruned somehow during the Big Docs Rebase™
