### ISSUE TITLE
Unknown user error is not shown in Web UI (Failed SSH connect attempts are not handled as errors by the server)

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4025]
### Description

**What happened**:

Attempting to open a session with a non-existent user on a machine via the Web simply displays the "start a new session" button.  The user does not know the issue.  They have to replay the session to see the unknown user message which they may not have access to.

**What you expected to happen**:

The error message would display of unknown user and some indication in the audit log of a failed session would be written.

![image](https://user-images.githubusercontent.com/60704961/87341529-c64bd680-c517-11ea-9297-f1a7ac5c883e.png)

**How to reproduce it (as minimally and precisely as possible)**:

Add logins (myuser3, myuser4,..).  Through the web ui attempt to open a ssh session with a user that doesn't exist on a ssh node.

### Environment
- Teleport version (use `teleport version`): 4.3.0
- Tsh version (use `tsh version`): 4.3.0
- OS (e.g. from `/etc/os-release`): Ubuntu

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Browser environment**

- Browser Version (for UI-related issues):  chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by alex-kovoy** [comment]
This is known behavior even for older teleport version where server does not return an error and emits `Session.start` and `Session.end` events as if nothing happened in which case the web terminal closes the tab automatically (upon receiving `Session.end` event).

The expected behavior for the server would be to return/report an error as it does for Teleport node which does not happen in this case.

**Comment by alex-kovoy** [comment]
The fact that you can playback that session with the error text indicates that Teleport proxy has no clue about the error.

**Comment by alex-kovoy** [comment]
This is a dup of https://github.com/gravitational/teleport/issues/3570

**Comment by russjones** [comment]
Best: 2
Realistic: 4
