### ISSUE TITLE
Extra Drone functionality/wishlist

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4031]
This is an ongoing list of Drone functionality I want to add.

- [x] Only run docs tests against docs-only PRs (skip CI tests for speed)
- [x] Auto deploy new versions of docs when a PR is merged to master
- [ ] Switch from raw YAML to [Starlark](https://docs.drone.io/pipeline/scripting/starlark/) to reuse code sections and cut down on YAML file size.
  - [ ] Needs some more investigation - not sure whether jsonnet/Starlark will be automatically expanded out by Drone at run time or not.
  - [ ] I think the intended use for Starlark is that you locally run something like `drone starlark --format --target .drone.yml && drone sign .drone.yml` to output the pipeline after you've changed it.
- [x] Fix the issue [here](https://github.com/gravitational/ops/blob/master/xcloud/release-teleport.sh#L169-L172) which leads to Enterprise builds not being named correctly, and remove all rename logic from Drone scripts (probably at the same time as the `4.4.0` release)
  - [ ] Remove `image-ci` and `publish-ci` Docker targets from Makefiles
- [x] Auto-build artifacts when we merge a PR and post result to Slack
  - [x] Run the checks against commits to `master` or `branch/*` too so we get checkmarks on commits.
- [x] Improve Slack feedback for success/failure (https://github.com/gravitational/teleport/blob/master/.drone.yml#L115-L124)
- [ ] Automatically raise a PR to update AMI IDs when we build OSS/Enterprise AMIs for a new version (see code in https://github.com/gravitational/teleport/pull/4219)
  - [ ] Terraform README
  - [ ] Terraform docs (if AMI IDs are present)
  - [ ] CloudFormation `oss.yaml` and `ent.yaml`
- [ ] Automatically check that released AMIs have correctly been made public and fix if appropriate (https://github.com/gravitational/teleport/issues/4353)
- [ ] Uptime/disk space/process monitoring for servers accessed via https://teleport-buildboxes.gravitational.io
  - [ ] `seamini` used to be in the Seattle office and had to be moved, we didn't know it was offline until we went to cut a build
- [ ] Run tests on commits to teleport.e and enforce test runs passing to commit
- [ ] Host buildbox images in `us-west-1` GCR for faster pulls/build starts
  - [ ] Also remove the automatic buildbox build from linter, unit tests and integration tests when running in Drone as we automatically pull/build the buildbox as the first step
- [ ] Figure out how to speed up AMI builds - they currently take ~15 minutes for OSS and ~17 minutes for Enterprise which is the longest thing in the build after `armv7` builds at ~8 minutes
  - [ ] Removing marketplace will help, maybe a beefier build box (we currently use a t2.micro) - I think the majority of time is spent waiting for AWS to copy the AMIs to other regions, though. If we can reduce the size of the AMI as much as possible, this will probably make it faster.

https://docs.drone.io/pipeline/triggers/#by-repository
https://docs.drone.io/pipeline/conditions/#by-repository

**Comment by benarent** [comment]
Auto deploying of Docs when merged to master would also be 💯 .  We would need a better way of adding docs to newer versions, but we could overcome that... this would also fix the old PR issue.

**Comment by webvictim** [comment]
Sure, that should be doable.

**Comment by webvictim** [comment]
https://github.com/gravitational/teleport/issues/4418 is also relevant

**Comment by webvictim** [comment]
I don't think any of this is really relevant any more :)
