### ISSUE TITLE
I want create home dir with create_host_user_mode: insecure-drop

### ISSUE THREAD

**Issue by godkid1412** [gravitational/teleport#40383]
I'm using byobu in Linux. It requirement home dir with user for using it.
When i using create_host_user_mode: insecure-drop, it dont create home dir

Please give me config useradd for create home dir when login with tsh

**Comment by godkid1412** [comment]
you can help me by build image docker souce code

**Comment by zmb3** [comment]
GitHub issues are not the right place to ask for general support. Please take questions like this to GitHub discussions or community Slack. 

You will have more luck getting help if you are clear about what you're trying to accomplish, what you've already tried, and what went wrong.
