### ISSUE TITLE
AKS Guide

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4046]
## Summary
Similar to the AWS EKS Guide https://gravitational.com/teleport/docs/aws_oss_guide/#accessing-eks-using-teleport, but for https://azure.microsoft.com/en-us/services/kubernetes-service/

### Audience
People onboarding for EKS and Azure 

### Location
New Guide / Link from Kubernetes section

**Comment by ptgott** [comment]
We can adopt this discussion forum post: https://github.com/gravitational/teleport/discussions/18547

**Comment by zmb3** [comment]
https://goteleport.com/docs/deploy-a-cluster/helm-deployments/azure/
