### ISSUE TITLE
Grammar used in event log is weird

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4051]
**What happened**: Some of the grammar used in the event log doesn't read very well.

`User [gus@gravitational.com] has ended a few seconds interactive session [061ec026-c6b5-11ea-a1ee-ce661b0ed760] on node [gusdemo-root-node-0]`

<img width="1547" alt="Screenshot 2020-07-15 13 06 50" src="https://user-images.githubusercontent.com/897821/87568657-63377c80-c69c-11ea-9fc7-2e18893fd851.png">

A longer session doesn't quite look right either:

`User [gus@gravitational.com] has ended 4 minutes interactive session [6fd8d7fe-c6b5-11ea-a1ee-ce661b0ed760] on node [gusdemo-root-auth-0]`

**What you expected to happen**: This should read:

`"User [gus@gravitational.com] has ended an interactive session lasting a few seconds [061ec026-c6b5-11ea-a1ee-ce661b0ed760] on node [gusdemo-root-node-0]"`

`"User [gus@gravitational.com] has ended an interactive session lasting 4 minutes [6fd8d7fe-c6b5-11ea-a1ee-ce661b0ed760] on node [gusdemo-root-auth-0]"`

**How to reproduce it (as minimally and precisely as possible)**: Start a session. Stop session. Observe audit log.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0git:v4.3.0-0-g73b68f401 go1.13.2`

**Comment by alex-kovoy** [comment]
@benarent are you OK with proposed gramma?

**Comment by benarent** [comment]
Yes. @webvictim is the Grammar Professor
