### ISSUE TITLE
Recreating recovery codes through the account settings page doesn't work

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#40528]
Expected behavior:
User should be able to recreate the recovery codes through the settings page.

Current behavior:
A following error appears:

> MFA response validation failed: required scope "CHALLENGE_SCOPE_MANAGE_DEVICES" is not satisfied by the given webauthn session with scope "CHALLENGE_SCOPE_ACCOUNT_RECOVERY"

Creating recovery codes while setting up accounts or resetting authentication works correctly.

Bug details:
Teleport version: v15, master

**Comment by codingllama** [comment]
Duplicate of #37299? FYI @Joerger.
