### ISSUE TITLE
Dcument ID override for installing Teleport on popular distros

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#40532]
## Applies To

- https://goteleport.com/docs/installation/

## Details

Users are running many Linux distros derivated from distros we officially support. While not officially supported, Teleport runs very well on such distros as the core packages are the same. Our installation instructions don't explain how to configure Teleport's repos for those distros.

For example
- rocky -> centos
- opensuze-leap -> sles
- kali -> debian

We should have an optional section (in a spoiler?) describing which variables to override to install Teleport on the most common distros.

e.g. 

```shell
export ID=centos
```

## How will we know this is resolved?

Users can install on popular distros without having to fiddle or reverse-engineer our package repository.

## Related Issues

- Internal support slack thread of a customer asking for installation instructions: https://goteleport.slack.com/archives/C0582MBSMHN/p1712947384557019

**Comment by ptgott** [comment]
Similar issue with the one-line installation script: https://github.com/gravitational/teleport/issues/39340
