### ISSUE TITLE
Unable to Replay Interactive k8s Sessions, Web UI due to missing event field 

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#4055]
### Description

**What happened**:
When running an interactive k8s session through Teleport w/ k8s support enabled, the session is labeled as non-interactive, and you are unable to replay through the Teleport web UI. If you downgrade the cluster to 4.2.10, the session is playable in the web UI. If you use tsh (4.2.10 and 4.3), the session is playable. 

**What you expected to happen**:
Interactive k8s sessions are recorded and accessible via Teleport web UI. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure Teleport w/ k8s proxy
2. Launch an interactive session `kubectl run -i --tty --rm debug2 --image=busybox --restart=Never -- sh`.
3. Observe that the Teleport web UI does not show this as an active session. There is no option to join the session. 
4. End the interactive session. 
5. Observe that the session is listed in the audit log, but it shows as non-interactive and there's no way to replay the session. 
6. Using tsh, run `tsh play <session-id>`. 
7. Observe that it's possible to replay the interactive session from tsh. 

![Selection_084_clean](https://user-images.githubusercontent.com/241714/87576959-c1ae2c00-c697-11ea-91b6-96359449ad26.png)

![Selection_083](https://user-images.githubusercontent.com/241714/87576962-c377ef80-c697-11ea-9cc1-5023411f97db.png)

### Environment
- Teleport version (use `teleport version`): 4.3.0 Enterprise
- Tsh version (use `tsh version`): 4.3.0 
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP + Azure AKS

**Browser environment**

- Browser Version (for UI-related issues): Chrome 84.0.4147.89

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

session.end event:
```
{
  "code": "T2004I",
  "ei": 12,
  "event": "session.end",
  "namespace": "default",
  "proto": "kube",
  "sid": "e1b00ab4-99c5-4e02-a75f-f2829e9860ea",
  "time": "2020-07-15T16:59:02.497Z",
  "uid": "b9e283de-2d28-4f7c-88c1-89474c2770dd",
  "user": "travelton"
}
```

**Comment by alex-kovoy** [comment]
This `Session.end` is missing `interactive` flag which tells if this session can be open in the session player.
This needs to be fixed on the server side.

**Comment by russjones** [comment]
Best: 1
Realistic: 3

**Comment by travelton** [comment]
Looks like the issue might originate from here, https://github.com/gravitational/teleport/blob/master/lib/kube/proxy/forwarder.go#L563-L568

**Comment by alex-kovoy** [comment]
Also, this event is missing some other fields

```js
{
 server_id
 server_addr
 server_hostname
}
```
