### ISSUE TITLE
The `saml.idp.auth` event uses a non-UUID session ID

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport#40589]
Expected behavior:

The `saml.idp.auth` event is correctly emitted and stored by all audit log backends.

Current behavior:

The `saml.idp.auth` event is generated with a "session ID" consisting of 64 random hex characters (as that's just the `(*crewjam/saml.Session).ID`), and that doesn't correctly parse as a UUID, so the PostgreSQL audit log storage will fail to store it.

The `SessionID` field in the `SessionMetadata` protobuf message is documented as being a UUID:
```
// SessionMetadata is a common session event metadata
type SessionMetadata struct {
	// SessionID is a unique UUID of the session.
	SessionID string `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"sid"`
```

We should either use a UUID as the SAML session ID (if that's possible), or decouple the audit log "session ID" from the SAML session ID for the `saml.idp.auth` events.

**Comment by flyinghermit** [comment]
I could verify that the SAML auth events were never logged in PostgreSQL backend. Ideally, we should not have directly logged the session ID in the first place and instead logged a derived or hashed value.

Any suggestions on effectively decoupling the audit log "session ID" from the SAML session ID? A random new UUID wont be helpful to correlate with the actual session. 

I am looking at `uuid.NewSHA1()` from the `github.com/google/uuid` package which derives new uuid from uuid and a random value ( I can create SAML session ID as UUID and use SAML session index which is of random value). SessionMetadata expecting a proper UUID value seems like needlessly restrictive.
