### ISSUE TITLE
Get rid of `domain_name` variable for ODIC config

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#406]
This is a must: 
Get rid of `domain_name` variable for ODIC config. Every Teleport cluster (AKA "site" AKA CA) must have a name configurable in `teleport` section.

Optional:
Find out a way to get rid of `--auth` flag.

**Comment by kontsevoy** [comment]
Ha! Looks like our YAML config does not have a "site/cluster name" setting. Perhaps it's the time to add it?

**Comment by klizhentas** [comment]
domain name is a part of `auth_service` section, not OIDC section, that is currently treated as a name of cluster
