### ISSUE TITLE
ProxyWatcher appears to miss proxy creation events immediately after startup.

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport#4066]
During review of #4060, @russjones noticed that sometimes the [`ProxyWatcher`](https://github.com/gravitational/teleport/blob/ed73260b5f1e488dc8e0bc00b452c2b8b110104a/lib/services/proxywatcher.go#L63) appears to stay empty significantly longer than it should after initial startup.  This is evidenced by an initial log message like this:

```
DEBU [PROXY:1]   List of known proxies updated: []. services/proxywatcher.go:148
```

Then, a few minutes later:

```
DEBU [PROXY:1]   List of known proxies updated: ["<proxyname>"]. services/proxywatcher.go:148
```

While it is perfectly normal for the first proxy to see an empty proxy list on startup, it should see an updated proxy list containing at least its own identity within 1-2 seconds at most.

This likely indicates an issue with the in-memory cache, as the `ProxyWatcher` instantiates its internal event watcher *before* loading the initial proxy set, so a well-behaved backend should either return a non-empty proxy list, or emit a proxy creation event shortly thereafter (neither of which has happened in the above case).

**Comment by kimlisa** [comment]
I got this error again. I saved the entire log from start to finish if you want to view it (its not that big). But basically as you said, list of known proxies is initially empty, and few minutes later (maybe about <5min?) it gets updated.
