### ISSUE TITLE
Remote Desktop Service with Teleport

### ISSUE THREAD

**Issue by MinhAn2106** [gravitational/teleport#40684]
Bug details:
- Cant integrate teleport with remote desktop service (multi session).  Only install feature RDS, using remote to server via  teleport occur error like attach image
![Screenshot 2024-04-19 121242](https://github.com/gravitational/teleport/assets/71483190/2e76e244-e733-4242-b69e-7e4e610b534c)

**Comment by zmb3** [comment]
Should be fixed by #40590

**Comment by MinhAn2106** [comment]
Niceeeee, Tks @zmb3
