### ISSUE TITLE
UX: `tsh --auth` fails to understand user

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#408]
here's what started to happen when I use OIDC with tsh. 
- Login is successful. 
- Next time I execute the same command it fails to find existing keys:

```
export TELEPORT_LOGIN=admin; export TELEPORT_PROXY=localhost; export TELEPORT_AUTH=google; export TELEPORT_SITE=example.com; tsh -d ssh --local -L 8080:localhost:8080 -L 5000:localhost:5000 root@teleport-role=master

INFO[0000] no teleport login given. defaulting to sasha  file=client/api.go:174
INFO[0000] using FSLocalKeyStore                         file=client/keystore.go:71
ERRO[0000] open /home/sasha/.tsh/keys/localhost/sasha.cert: no such file or directory  file=client/keystore.go:147
INFO[0000] Got error after GetKey(sasha): open /home/sasha/.tsh/keys/localhost/sasha.cert: no such file or directory  file=client/keystore.go:97
ERRO[0000] open /home/sasha/.tsh/keys/localhost/sasha.cert: no such file or directory  file=client/keystore.go:147
INFO[0000] Got error after GetKey(sasha): open /home/sasha/.tsh/keys/localhost/sasha.cert: no such file or directory  file=client/keystore.go:97
INFO[0000] connecting to proxy: localhost:3023 with host login root  file=client/api.go:772
```

This happens because I authenitcate not as `sasha` but as `admin`. Here's my keys dir:

```
ls -l ~/.tsh/keys/localhost/
total 12
-rw-r----- 1 sasha sasha 1354 May  9 20:05 admin.cert
-rw-r----- 1 sasha sasha 1679 May  9 20:05 admin.key
-rw-r----- 1 sasha sasha  381 May  9 20:05 admin.pub
```

So it fails to recognize that I've logged in already and let me in. 

However I was able to solve this issue without any coding, by simply hinting `tsh` what user I need by adding `--user` flag:

export TELEPORT_LOGIN=admin; export TELEPORT_PROXY=localhost; export TELEPORT_AUTH=google; export TELEPORT_SITE=example.com; tsh ssh --user=admin --local -L 8080:localhost:8080 -L 5000:localhost:5000 root@teleport-role=master

So I'm thinking this not a bug, but a UX issue

**Comment by klizhentas** [comment]
I think your suggestion to use:

```
--user=admin/google
```
will actually work

**Comment by kontsevoy** [comment]
@klizhentas since we're de-emphasizing local users mapped to OIDC, lets close this.
