### ISSUE TITLE
connection refused on tsh due to port "mismatch"

### ISSUE THREAD

**Issue by aberfeldy** [gravitational/teleport#4080]
### Description

**What happened**:
I've installed teleport via the helm chart and tried to configure it as far as the docs told me what to do. I can login to the web-ui, create new users, enable github, and login to the teleport pod (the only one showing) and get the session recorded.
Once I try to login via tsh, I get this error
```
• tsh login --proxy=teleport.domain.tld --auth=github login
error: Post https://teleport.domain.tld:3080/v1/webapi/github/login/console: dial tcp xxx.xxx.xxx.xxx:3080: connect: connection refused
```
It seems that tsh appends the port, but with an nginx-ingress enabled it just exposes the 443 port, so the connection will never go through.

**What you expected to happen**:
That the tsh login goes through the ingress.

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`): Teleport v4.3.0 git:v4.3.0-0-g73b68f401 go1.13.2
- Tsh version (use `tsh version`): Teleport v4.3.0 git:v4.3.0-0-g73b68f401 go1.13.2
- OS (e.g. from `/etc/os-release`): kubernetes, used the helm-chart

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
Kubernetes on root-servers 

**Relevant Debug Logs If Applicable**
 my values.yaml for helm looks like this:
https://gist.github.com/aberfeldy/9444980f09abca6c3b7fd0deffb74cef

Any help would be appreciated

**Comment by webvictim** [comment]
Try explicitly setting [this](https://gist.github.com/aberfeldy/9444980f09abca6c3b7fd0deffb74cef#file-values-yaml-L124) to `teleport.domain.tld:443` and running a `helm upgrade`. If you don't specify a port, Teleport assumes the default (3080).

**Comment by aberfeldy** [comment]
Hey,
thanks, I set :443 on the public_addr and upgraded the release on kubernetes.
I get the same output once I try to login from my shell, still with the 3080 port attached.

![Screen Shot 2020-07-20 at 16 29 19](https://user-images.githubusercontent.com/1640534/87949438-505ee680-caa6-11ea-8ef8-47e246438510.png)

<img width="1369" alt="Screen Shot 2020-07-20 at 16 32 03" src="https://user-images.githubusercontent.com/1640534/87949800-c6634d80-caa6-11ea-920b-1ec51158a565.png">

**Comment by webvictim** [comment]
Oh, `tsh` will also assume port 3080 if you don't provide it with an alternative. Unfortunately, it can't figure the port out for itself because the proxy is the part that provides the response telling `tsh` what `public_addr` it should use - it's a bootstrapping problem.

Try `tsh login --proxy=domain.example.com:443 --auth=github login`

**Comment by aberfeldy** [comment]
hm tried that, got the same. 

<img width="1460" alt="Screen Shot 2020-07-20 at 17 00 14" src="https://user-images.githubusercontent.com/1640534/87952848-961dae00-caaa-11ea-9bb2-d3ff274d0398.png">

**Comment by webvictim** [comment]
What do you get if you `curl https://domain.example.com:443/webapi/ping`?

**Comment by aberfeldy** [comment]
```json
{
  "auth": {
    "type": "github",
    "second_factor": "otp",
    "github": {
      "name": "github",
      "display": "Github"
    }
  },
  "proxy": {
    "kube": {
      "enabled": true,
      "public_addr": "domain.tld:3026",
      "listen_addr": "0.0.0.0:3026"
    },
    "ssh": {
      "listen_addr": "0.0.0.0:3023",
      "tunnel_listen_addr": "0.0.0.0:3024",
      "public_addr": "domain.tld:3080",
      "ssh_public_addr": "domain.tld:3023",
      "ssh_tunnel_public_addr": "domain.tld:3024"
    }
  },
  "server_version": "4.3.0",
  "min_client_version": "3.0.0"
}
```

**Comment by webvictim** [comment]
The `"public_addr": "domain.tld:3080",` part indicates that the `public_addr` setting hasn't been updated correctly. You may need to look at the `teleport` `ConfigMap` explicitly, see whether it's set correctly and manually restart the Teleport pod to get it to pick up the right setting. It should say `domain.tld:443`.

**Comment by aberfeldy** [comment]
yes, that was the case, the configmap was not updated. Thanks a lot.

I just deleted it and installed it again with helm and it seems to have the same issue. 
I tried a bit around and it seems, that the `public_addr` is always overwritten by  [this](https://gist.github.com/aberfeldy/9444980f09abca6c3b7fd0deffb74cef#file-values-yaml-L39) value + the port (3080). 
When I delete that line from my values.yaml, but keep the `proxy_service.public_addr` as `domain.tld:443`, the result in the configmap will be `teleport.example.com:3080`
When I change the value to `domain.tld:443` I will get `teleport.example.com:443:3080` in the configmap.

I had a look in the helm charts in the `example/`-dir and the value is never set, because it's generated from the global `public_adress` [here](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport/templates/config.yaml#L72)

**Comment by webvictim** [comment]
@aberfeldy This should be fixed now. Please check out the latest Helm chart from `master` and try again - let us know if it doesn't work for you.

**Comment by aberfeldy** [comment]
works like a charm thanks a lot! still have to figure out some other issues before we can get started but this is a nice fix

**Comment by webvictim** [comment]
Great to hear!

**Comment by aberfeldy** [comment]
only one thing to add: is there a plan to add the other public_addr as ingresses as well? e.g. ssh_public_addr will be set to domain.tld:3023 which doesn't match the ingress which leads to 
`error: failed to authenticate with proxy domain.tld:3023: dial tcp xxx.xxx.xxx.xxx:3023: connect: connection refused` on tsh login. I'm trying to build some ingresses myself in order to fix that

**Comment by webvictim** [comment]
Interesting, I’ll take a look. We should be setting public_addr correctly for all listening ports.
