### ISSUE TITLE
CLI wizards for common configuration tasks

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#4082]
### Feature Request

Add wizards to `tctl` and `tsh` to help users generate various configs. Specific examples:
- openssh client (~/.ssh/config and ~/.ssh/known_hosts) and server (/etc/ssh/sshd_config) configs
- systemd unit config
- trusted cluster config
- editing users/roles

Other suggestions welcome!

The wizards should prompt the user for key pieces of information (which port to listen on, public address for proxy, etc) and provide sane defaults. Similar to `ssh-keygen` without flags.

### Motivation

[The admin guide](https://gravitational.com/teleport/docs/admin-guide/) has tons of config examples and advice. However, users have to copy those configs and edit them by hand (potentially missing something) or merge example config sections with their existing config.
Power users might still want to write everything from scratch.
A wizard is aimed at anyone getting started, to get teleport up and running with reasonable configuration that they can then tweak. 

### Who's it for?
OSS User, Pro, Enterprise

We'll look at thumbs up/down to measure interest ;)

**Comment by webvictim** [comment]
Some elements of this have now been covered:

> "openssh client (~/.ssh/config and ~/.ssh/known_hosts) and server (/etc/ssh/sshd_config) configs"

Covered by `tsh config` on the client side, server side is probably not something we need to support

> "systemd unit config"

Covered by `teleport install systemd`
