### ISSUE TITLE
No data shown by "tctl top"

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#4083]
The `tctl top` command should monitor the Prometheus endpoint and report current information. Customer reports that no information is being shown.

**Comment by russjones** [comment]
Possibly related to https://github.com/gravitational/teleport/issues/3755.

**Comment by benarent** [comment]
I noticed in https://github.com/gravitational/teleport/pull/4069 that we document 3434, vs the default port of 3000. I tried it with 4.3 and it's working but it defaults to 3434. I would suggest we change it.  ( note: we also still have the background color issue )

**Comment by russjones** [comment]
Best: 2
Worst: 3

**Comment by russjones** [comment]
This is because Teleport has to be started in debug mode for metrics to show up. We should fix this so metrics to Prometheus are always emitted.

**Comment by awly** [comment]
Prometheus metrics are emitted without debug mode and `tctl top` works fine against it, as long as the address is correct.
I made some small fixes in https://github.com/gravitational/teleport/pull/4231 but most of the data shows correctly already.

@russjones can we get a screenshot from the customer? Also also the flags used to run `teleport` and `tctl top`.
