### ISSUE TITLE
Teleport Terraform provider resource examples missing version information 

### ISSUE THREAD

**Issue by tenaciousdlg** [gravitational/teleport#40870]
## Applies To

https://goteleport.com/docs/reference/terraform-provider

## Details

It appears that in Teleport v15 an argument called version was added to roles. This argument can be seen in the description of resources such as https://goteleport.com/docs/reference/terraform-provider/#teleport_app but does not appear in any of the examples following a resource's descriptions. 

## How will we know this is resolved?

When the Teleport Terraform resource examples show an arugmeent in them such as the following. 

```
resource "teleport_role" "user" {
  version = "v6"
  metadata = {
    name        = "user"
    description = "user"
  }
  spec = {
    options = {
      record_session = {
        desktop = true
      }
      desktop_clipboard   = false
      create_desktop_user = true
    }
    allow = {
      windows_desktop_labels = {
        "environment" = ["dev", "stage"],
        "cloud"       = ["aws"]
      }
      windows_desktop_logins = ["bob"]
    }
  }
}
```

**Comment by ptgott** [comment]
Resolved in this PR: https://github.com/gravitational/teleport/blob/250366bb61454f1a2ba9f1899a019b2076b9197e/docs/pages/reference/terraform-provider/data-sources/role.mdx
