### ISSUE TITLE
Design to manage join tokens in the Web UI

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#40892]
**Description:** 
Teleport’s web UI will provide the ability to list, view, create, and edit join tokens. This will provide more insight into the joining process, allow Teleport Discover users to use more secure join methods, and remove the requirement to use `tctl` to work with join tokens.

https://github.com/gravitational/teleport/issues/31671

**Success Criteria:**

- The web UI has a new page that lists all join tokens.
- The web UI provides the ability to create new join tokens.
- The web UI provides the ability to edit existing join tokens.
- The web UI provides the ability to delete an existing join token.
- (Stretch) Teleport Discover flows allow you to select an existing join token rather than creating a new one each time.

**Comment by roraback** [comment]
Discussed in Design and Product Office Hours:
* Messaging: “Long-lived and static tokens are insecure and will be deprecated. Use short-lived tokens or alternative join methods (gcp, iam) for long-lived access.”
* Anything > 24 hours -> show warning icon
* Make it impossible to create long-lived tokens through web UI
* MVP can be for fewer token types, but it should be more user-friendly/form-based, rather than YAML
* Messaging: “You cannot configure or delete static tokens via the web UI. You should delete…”

**Comment by zmb3** [comment]
@roraback can we close this out? My understanding is that the implementation is complete and ready to ship in 16.2.0.

**Comment by roraback** [comment]
Yes, thanks for checking - I forgot to follow up when [designs](https://www.figma.com/design/v6GunK50D2VC7w7I2FBDNf/Management?node-id=4141-20889&t=zj4c2HKo0WA4D7W0-4) were finished.
