### ISSUE TITLE
Set the default role for Resource based access

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#40934]
**What would you like Teleport to do?**

Set the default role for Resource-based access

**What problem does this solve?**

Consider that there are two roles, `db-read` and `db-write` that users can request. 
When the user creates a resource-based request, the role defaults to both. the roles.
This brings confusion for the users when they have no understanding of roles, and they go by resources. 

It would be great if we could have a mechanism to set the default role when resources are requested.

**Comment by zmb3** [comment]
This is not planned.

> This brings confusion for the users when they have no understanding of roles,

The whole point of resource access requests is for users to not have to care about roles. Teleport's default behavior does the right thing and guarantees that the correct access will be granted.

The ability to adjust the computed roles for a resource-based access request is a power-user feature for a limited number of circumstances. In general, you should just avoid messing with those options.
