### ISSUE TITLE
Non-admin windows users error with tsh login

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4095]
### Description
**What happened**:
If a non-admin user in Win10 attempts to login they can get an error on symbolic links.

**What you expected to happen**:

`tsh` will allo login or provide a workaround.

**How to reproduce it (as minimally and precisely as possible)**:

Create a windows 10 environment.  Create a non-admin default user.  Attempt to login with `tsh login` with that user.

### Environment
* Teleport version (use `teleport version`): 4.3.0
* Tsh version (use `tsh version`): 4.3.0
* OS (e.g. from `/etc/os-release`): Windows 10
* Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Relevant Debug Logs If Applicable**

* `tsh --debug`

```cmd
←[37mDEBU←[0m [KEYSTORE]  Returning SSH certificate "C:\\Users\\testuser\\.tsh\\keys\\tele1c.gravitational.co\\steven@gravitational.com-cert.pub" valid until "2020-07-22 00:04:08 -0400 EDT", TLS certificate "C:\\Users\\testuser\\.tsh\\keys\\tele1c.gravitational.co\\user@site.com-x509.pem" valid until "2020-07-22 04:04:08 +0000 UTC". client\keystore.go:277
←[33mWARN←[0m [CLIENT]    Failed to remove symlink: remove C:\Users\testuser\.tsh\profile: The system cannot find the file specified. client\profile.go:150

ERROR REPORT:
Original Error: *os.LinkError symlink tele1c.gravitational.co.yaml C:\Users\testuser\.tsh\profile: A required privilege is not held by the client.
Stack Trace:
        /gopath/src/github.com/gravitational/teleport/lib/client/profile.go:154 github.com/gravitational/teleport/lib/client.(*ClientProfile).SaveTo
        /gopath/src/github.com/gravitational/teleport/lib/client/api.go:645 github.com/gravitational/teleport/lib/client.(*Config).SaveProfile
        /gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:511 main.onLogin
        /gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:351 main.Run
        /gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:188 main.main
        /opt/go/src/runtime/proc.go:212 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1358 runtime.goexit
User Message:
```

**Comment by benarent** [comment]
It looks like Windows does support it in https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/#I5mtt0eAfWemiHAa.97 

This could just a bug on our side.

**Comment by benarent** [comment]
Looks like there is an open issue / fix https://github.com/golang/go/issues/39183 .

I would suggest for now we recommend these customers to the use Teleport UI. Unless there is any specific tooling thats running on Windows.

**Comment by webvictim** [comment]
If we can work around this in some way that doesn't involve a symlink it'd probably be preferable. Network filesystems on Windows also sometimes have these restrictions where they don't play nicely with symlinks.

**Comment by klizhentas** [comment]
best case: 3 days
worst case 6 days
