### ISSUE TITLE
Personalization for  web experience

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4096]
### Feature Request
Provide personalization features in the web experience to provide ease of use including:

  - Ability to save and reopen set of ssh web tabs
   - See your recent sessions, upload/downloads and replay, restablish session from list
   - Ability to tag sessions with metadata. 

 
### Motivation
The web user experience is fairly generic per user.  Having personalization options is available in similar products and makes reusing the product a more efficient process.  

If a user loses their web session they will have to restablish across multiple tabs to restore their work env. 

Provide 

### Who's it for?
OSS User, Pro, Enterprise

**Comment by stevenGravy** [comment]
Helpful here as well would be to be to tag a favorite list of servers. If you have a long list of nodes it can be tedious to navigate through.

**Comment by benarent** [comment]
Thanks for this issue @stevenGravy, we've a few of these in older issues but I'll keep it open to make sure we get a more personalised UX in 2021.

**Comment by zmb3** [comment]
I'm going to close this as it's fairly generic and we have a number of more specific and up-to-date issues that cover it.

- #15368 is for customizing SSH via the web UI
- #15369 for "pinning" your favorite servers for easy access

We're also exploring personalized elements in Teleport Connect on the default "new tab" screen for recently accessed resources, favorites, etc.
