### ISSUE TITLE
Deleting a role which is assigned by an access list can prevent logging into a cluster

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#41074]
## Expected behavior

If you try to delete a role which is actively being assigned by an access list, the backend should prevent you from doing so.

## Current behavior

Deleting a role which is assigned by an access list can prevent users signing into the cluster with the error `<role> is not found`.

This issue is exacerbated by the fact that roles which are assigned by access list aren't currently "registered" against users (and thus shown under users in the web UI), which means the overarching protection of not allowing deletion of roles which are actively assigned to users doesn't take effect here.

Bug details:
- Teleport version: 15.2.2

**Comment by russjones** [comment]
I think https://github.com/gravitational/teleport/issues/43775 and this are the same actually.

**Comment by russjones** [comment]
@r0mant I think https://github.com/gravitational/teleport/issues/43775 and this are the same?

**Comment by r0mant** [comment]
Yeah seems like the same issue, with the only difference being in https://github.com/gravitational/teleport/issues/43775 the role is deleted automatically based on TTL.

**Comment by rudream** [comment]
Fixed in https://github.com/gravitational/teleport/pull/45610
