### ISSUE TITLE
Add SAML logout endpoint

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#41076]
If you logout from Teleport and then immediately login again, the user is not asked for username/password.

Keycloak provides logout endpoint for SAML `[https://{host}/realms/{realm}/protocol/saml`. Add an option to call this endpoint to log the user out of Teleport (but not other applications).

**Comment by sizgiyaev** [comment]
+1

**Comment by nix-power** [comment]
+10

**Comment by zmb3** [comment]
See https://www.keycloak.org/docs/latest/securing_apps/index.html#logout (though note that Keycloak only seems to document this for `/realms/{realm}/protocol/openid-connect/logout`, I don't see `/protocol/saml` documented here).

This probably requires some configuration for the SAML app in Keycloak as well.

I believe the more general feature is called Single Logout (SLO), so ideally we support this for any SAML provider that supports SLO.

- https://help.okta.com/en-us/content/topics/apps/apps_single_logout.htm
- https://auth0.com/docs/authenticate/login/logout/log-users-out-of-saml-idps

>  Add an option to call this endpoint to log the user out of Teleport (but not other applications).

I'm not sure if this is how it works. I believe SLO signs out of the entire IdP session.

**Comment by yair-segal** [comment]
Hi Zac,

> Add an option to call this endpoint to log the user out of Teleport (but not other applications).
> 
> I'm not sure if this is how it works. I believe SLO signs out of the entire IdP session.

In a way, you are correct, but I don't think this issue should focus on that, as this resides on the way we configure realms/clients in Keycloak. 
For example: In our setup, we are using Teleport and ArgoCD in the same realm. ArgoCD is configured with open id, with logout configuration. When I am logged in to both applications, I see in my session (in KeyCloak) that I am logged in with both clients. Then, when I logout from ArgoCD (from ArgoCD UI), then in Keycloak _both_ sessions are terminated - for ArgoCD _and_ Teleport.
