### ISSUE TITLE
Add repo for Ubuntu 24.04 LTS (Noble Numbat)

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#41092]
## What would you like Teleport to do?

Support Ubuntu 24.04 LTS in the DEB repos and automatic installation script.

## What problem does this solve?

Adds support for Ubuntu 24.04 LTS.

## If a workaround exists, please include it.

Manually install packages for an older Ubuntu distro.

**Comment by zmb3** [comment]
@marcoandredinis is it safe to close this as completed by #40960?

**Comment by marcoandredinis** [comment]
> @marcoandredinis is it safe to close this as completed by #40960?

Yes 👍
