### ISSUE TITLE
Prometheus Metrics for `failed_login_attempts_total` are not incrementing. 

### ISSUE THREAD

**Issue by but-i-am-dominator** [gravitational/teleport#41093]
Expected behavior:
Counters go up when failed attempts are encountered.

Current behavior:
Counters are not incrementing.

Bug details:
- Teleport version
Teleport Enterprise v15.0.2 git:v15.0.2-0-g520f79d go1.21.7
- Recreation steps

Step 1 - Attempted fake login
```
tsh --proxy teleport.<company_domain>.com --user=fake_login --auth=local login
Enter password for Teleport user fake_login:
ERROR: invalid username or password
```

Step 2 - Check the raw prometheus output on Teleport auth and proxy servers
Note - F5 pressed repeatedly to make to ensure that browser is refreshing. (No trusty AJAX)

![image](https://github.com/gravitational/teleport/assets/13467018/c5595e71-6043-449b-8706-0326d6230f18)

Step 3 - Check logs.

![image](https://github.com/gravitational/teleport/assets/13467018/c9c839ac-1892-4f4e-a4fa-6d68fb8e4bfb)

- Debug logs

```
2024-05-01T10:28:21-04:00 INFO [AUDIT]     user.login addr.remote:127.0.0.1:36974 cluster_name:dash-cluster code:T1000W ei:0 error:[invalid username or password] event:user.login method:local success:false time:2024-05-01T14:28:21.461Z uid:84a6517f-63e3-41fc-b26e-7b38116d7af3 user:fake_login user_agent:Go-http-client/1.1 events/emitter.go:288
```

**Comment by zmb3** [comment]
This metric only applies to SSH auth, as defined in:

```
// UserKeyAuth implements SSH client authentication using public keys and is
// called by the server every time the client connects.
func (h *AuthHandlers) UserKeyAuth(conn ssh.ConnMetadata, key ssh.PublicKey) (*ssh.Permissions, error) {
```

This is why the `HELP` message for the metric says `Number of failed SSH connection attempts to a node`. Providing incorrect credentials to `tsh login` is not an SSH connection attempt to a node.
