### ISSUE TITLE
Usage in Self Hosted clusters UI

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#41095]
What would you like Teleport to do?
Have the ability to report usage in the Teleport UI for self hosted customers similar to how Teleport does it for SaaS tenants.

What problem does this solve?
Let's self hosted customers see usage within their tenant environment(s).

If a workaround exists, please include it.
Sending usage data to Teleport.

**Comment by zmb3** [comment]
Hey Scott,

Not saying we won't eventually do this, but I don't think we need an issue in the OSS repo for it, as it's more related to internal processes than the core Teleport product, and it's not actionable by devs until we've made a product decision.

This is the type of thing that's probably best raised through a revenue top 10 request.

Z
