### ISSUE TITLE
teleport-quickstart wrong config path

### ISSUE THREAD

**Issue by sj14** [gravitational/teleport#4113]
### Description

**What happened**:

The config path in teleport-quickstart.yml is wrong and thus is not used.

**What you expected to happen**:

The config should be used.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
curl -Lso teleport-quickstart.yml https://raw.githubusercontent.com/gravitational/teleport/master/docker/teleport-quickstart.yml
```
```
docker-compose -f teleport-quickstart.yml up
```

1. edit the config
2. restart teleport with docker-compose 
3. the config is not used

**Solution**

https://github.com/gravitational/teleport/blob/eefef4ddb7573a147a89e6208f090f663b8d8136/docker/teleport-quickstart.yml#L27

should be like ` - ./teleport/config/teleport.yaml:/etc/teleport.yaml`

**Comment by sj14** [comment]
https://github.com/gravitational/teleport/blob/eefef4ddb7573a147a89e6208f090f663b8d8136/docker/teleport-quickstart.yml#L10

should maybe also be like

```
   command: - ... teleport configure > /etc/teleport.yaml; fi"
```

**Comment by webvictim** [comment]
Thanks for the bug report. I've raised a PR with fixes.
