### ISSUE TITLE
docs: show starting fluentd in datadog log exporter integration.

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#41200]
## Applies To

https://goteleport.com/docs/management/export-audit-events/datadog/

## Details

The datadog logs forwarder assumes that Fluentd is running. Many using log collectors are not familiar with fluend. Like https://goteleport.com/docs/management/export-audit-events/fluentd/ this should include starting to run fluentd.

## How will we know this is resolved?

Installing the datadog integration will step through running the fluentd service.

**Comment by ptgott** [comment]
2443ad7f178eb57768d98d2328d00ef4be0b929e reworks the Datadog guide to no longer include fluentd instructions.
