### ISSUE TITLE
386 build is broken.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#4122]
32-bit builds of Teleport fail for `branch/4.3`. I suspect it's because `gcc-multilib` is not being installed within the build image.

```
In file included from _cgo_export.c:3:
/usr/include/stdlib.h:25:10: fatal error: bits/libc-header-start.h: No such file or directory
   25 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

See https://jenkins.gravitational.io/view/Publishing/job/TeleportPublish/457/

**Comment by webvictim** [comment]
This is actually fixed in master, but the changes to `build.assets/Dockerfile` didn’t get backported to 4.3.

**Comment by webvictim** [comment]
This should now be fixed.
