### ISSUE TITLE
`tctl inventory ls` shows incorrect services for host when multiple Teleport instances run

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#41244]
If Teleport is initially running as multiple services, e.g. `Node,Db`, and the configuration is changed to disable one of them, e.g. `db_service.enabled: false`, and Teleport is restarted, then `tctl inventory ls` correctly shows services as just `Node`.

However, if Teleport is not restarted, but instead a second instance of Teleport is started on the same host using the updated config, then the services in `tctl inventory ls` will show only one instance of Teleport on that host, and it will only show as `Node`.

This is misleading, since the old Teleport instance is still running and still proxying databases, i.e. it's still got a `Db` service running on that host.

Bug details:
- Teleport version: 15.0.2

Recreation steps:
1. start teleport with multiple services in its config file
2. disable one of those services
3. start a second instance of teleport on the same host
4. observe that the old instance continues to provide all of the original services, but `tctl inventory ls` shows it only has the reduced service set.

**Comment by fspmarshall** [comment]
Fixed in https://github.com/gravitational/teleport/pull/41467
