### ISSUE TITLE
Auto-enrollment db tags not compatible with UI Enrollment for Cloud DBs

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#41256]
Expected behavior:

Having auto-enrollment tags would work with UI Enrollment and discovered dbs.

Current behavior:

Adding RDS Postgresql dbs that have auto enrollment tags do not apply using the UI Enroll New Resource. Using cloud discovered approach does work.

Bug details:
- Teleport version: 15.3.0
- Recreation steps

1. Add Auto-enrollment tags as  in https://goteleport.com/docs/database-access/auto-user-provisioning/postgres/
2. Follow the Enroll RDS in UI

**Comment by marcoandredinis** [comment]
This happens for the single element enroll (auto-enroll is disabled).

UI ends up creating the Database and an Origin label.
UI creates the Database using what is returned here:
https://github.com/gravitational/teleport/blob/a2591f25d79e1ebfbc2355cdb2a60897587bec9d/lib/integrations/awsoidc/listdatabases.go#L159

When trying to access the DB, we try to fetch the default user/db, if the field is not filled we get its value from the labels but only for `label:origin=cloud` databases

https://github.com/gravitational/teleport/blob/b7ee6e015fcc4d31016aac4dd023fcbc6999d01a/api/types/database.go#L304-L313
