### ISSUE TITLE
Audit log information for non-interactive Kubernetes session is incorrect

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4139]
**What happened**: I ran a non-interactive `kubectl exec` command on a Kubernetes cluster after logging in:

```console
$ kubectl -n gusdemo-root exec gusdemo-root-node-3 hostname
gusdemo-root-node-3
```

Audit log entry from `events.log` file:

```json
{
  "addr.local": "10.7.240.1:443",
  "addr.remote": "1.2.3.4:54346",
  "code": "T3002I",
  "command": "hostname",
  "event": "exec",
  "login": "gus@gravitational.com",
  "namespace": "default",
  "proto": "kube",
  "time": "2020-07-28T19:54:00Z",
  "uid": "c0699522-2aac-4490-8980-94258b988890",
  "user": "gus@gravitational.com"
}
```

Entry in UI:

![2020-07-28-165414__1236x70__maim](https://user-images.githubusercontent.com/897821/88716049-d5747c00-d0f4-11ea-861a-28c4887ec5e0.png)

Issues:
- The hostname for the command is incorrect - I ran my command against `gusdemo-root-node-3`, not `10.7.240.1:443`.

**What you expected to happen**: The pod where the command was run should be correctly reported via the audit log (and consquently, the UI)

**How to reproduce it (as minimally and precisely as possible)**: Log into a Kubernetes-enabled Teleport cluster and run the `kubectl` command listed above.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.2git:v4.3.2-0-gc6d702ad8 go1.13.2`
- Tsh version (use `tsh version`): `Teleport v4.3.0 git:v4.3.0-0-g73b68f401 go1.13.2`
- OS (e.g. from `/etc/os-release`): `Fedora 31`

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GKE

**Comment by russjones** [comment]
@webvictim `addr.local` and `addr.remote` come from the load balancer and are not the output of the `hostname` command. Looks like this is working as intended?

**Comment by webvictim** [comment]
@russjones The issue is that the name of the pod doesn’t appear anywhere in the audit log, which is pretty critical information when using Teleport to capture `kubectl exec` commands for auditing.

I think that `10.7.240.1:443` is the Kubernetes apiserver.  I redacted `1.2.3.4` - it was originally my WAN IP.

**Comment by awly** [comment]
We now print the k8s cluster name in the web UI, and include a pod name in the audit event body
