### ISSUE TITLE
Audit log information for interactive Kubernetes session is incorrect

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4140]
**What happened**: I ran an interactive `kubectl exec` command on a Kubernetes cluster after logging in:

```console
$ kubectl -n gusdemo-root exec gusdemo-root-node-3 -it /bin/bash
root@gusdemo-root-node-3:/# date
Tue Jul 28 19:54:40 UTC 2020
root@gusdemo-root-node-3:/# echo this is k8s
this is k8s
root@gusdemo-root-node-3:/# date
Tue Jul 28 19:54:42 UTC 2020
root@gusdemo-root-node-3:/# exit
```

(these commands were executed immediately, one after another)

Audit log entries from `events.log` file:
```json
{
  "addr.local": "10.7.240.1:443",
  "addr.remote": "1.2.3.4:54384",
  "code": "T2000I",
  "ei": 0,
  "event": "session.start",
  "interactive": true,
  "login": "gus@gravitational.com",
  "namespace": "default",
  "proto": "kube",
  "server_addr": "10.7.240.1:443",
  "server_hostname": "gusdemo-root.gravitational.co",
  "server_id": "0d7391ee-53b4-404f-92c4-5dce494d85ac",
  "sid": "6b59d036-f724-400b-b7eb-47fcf5ed1a24",
  "size": "100:100",
  "time": "2020-07-28T19:54:38.788Z",
  "uid": "2007eb5b-3081-4d0b-b929-cffddc6f51a0",
  "user": "gus@gravitational.com"
}
{
  "code": "T2002I",
  "ei": 1,
  "event": "resize",
  "login": "gus@gravitational.com",
  "namespace": "default",
  "proto": "kube",
  "sid": "6b59d036-f724-400b-b7eb-47fcf5ed1a24",
  "size": "120:73",
  "time": "2020-07-28T19:54:39.013Z",
  "uid": "eaa2c825-f82c-432d-b86e-3fe45dac3f66",
  "user": "gus@gravitational.com"
}
{
  "code": "T2004I",
  "ei": 37,
  "event": "session.end",
  "interactive": true,
  "namespace": "default",
  "participants": [
    "gus@gravitational.com"
  ],
  "proto": "kube",
  "server_addr": "10.7.240.1:443",
  "server_hostname": "gusdemo-root.gravitational.co",
  "server_id": "0d7391ee-53b4-404f-92c4-5dce494d85ac",
  "session_start": "2020-07-28T19:37:02.462816053Z",
  "session_stop": "2020-07-28T19:54:43.334510151Z",
  "sid": "6b59d036-f724-400b-b7eb-47fcf5ed1a24",
  "time": "2020-07-28T19:54:43.336Z",
  "uid": "b74ce637-dd7d-4b66-893f-e3773cc029b7",
  "user": "gus@gravitational.com"
}
```

Entry in UI:

![2020-07-28-171724__1236x130__maim](https://user-images.githubusercontent.com/897821/88717000-3ea8bf00-d0f6-11ea-8097-cef886133451.png)

Issues:
- The displayed hostname for the command is incorrect - I ran my command against `gusdemo-root-node-3`, not `gusdemo-root.gravitational.co`.
- The `session_start` timestamp under the `session.end` event is wrong. You can see via the first event in the log that my interactive session actually started at `2020-07-28T19:54:38.788Z`, not `2020-07-28T19:37:02.462816053Z`.
  - It looks like this start timestamp may be when I actually logged into the cluster via `tsh login`, not when my session started.

**What you expected to happen**: The pod where the command was run should be correctly reported via the audit log (and consquently, the UI). Also, the timestamps displayed should be correct.

**How to reproduce it (as minimally and precisely as possible)**: Log into a Kubernetes-enabled Teleport cluster and run the `kubectl` command listed above.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.2git:v4.3.2-0-gc6d702ad8 go1.13.2`
- Tsh version (use `tsh version`): `Teleport v4.3.0 git:v4.3.0-0-g73b68f401 go1.13.2`
- OS (e.g. from `/etc/os-release`): `Fedora 31`

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GKE

**Comment by russjones** [comment]
Best: 1
Worst: 3

**Comment by awly** [comment]
We now print the k8s cluster name instead of the proxy node name in the audit log.
I also confirmed that session start timestamp matches the `kubectl exec` time, not `tsh login` time.

**Comment by webvictim** [comment]
Thanks!
