### ISSUE TITLE
Fallback to default proxy servers in IoT mode.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#4141]
When using Teleport in IoT mode, Teleport attempts to discover the address of the reverse proxy by hitting the ping endpoint. If Teleport is unable to do that, it does not start.

In some environments, it may not be possible to hit the ping endpoint but connection through the proxy is possible. In those situations, Teleport should attempt to fallback directly to the proxy server directly before giving up. 

A customer has submitted a patch in https://github.com/gravitational/teleport/pull/4030.

**Comment by mikegarts** [comment]
An important note here: 
I am not sure what do you exactly mean exactly by 'not possible to hit the ping endpoint', but the desired outcome here is that the agent MUST attempt to use the proxy even if an error happens at a later stage of the handshake - this is very important and a hard requirement.

**Comment by russjones** [comment]
Fixed in 6.1.
