### ISSUE TITLE
Provide a warning before navigating to documentation

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#41444]
What would you like Teleport to do?

Provide a warning before going to docs link from enrollment options.

What problem does this solve?

Leaving a application you are signed into can be abrupt and confusing. This is a typical behavior for most applications once you are leaving the application under control.

**Comment by zmb3** [comment]
Meh, I would just make the docs link open in a new tab and call it a day.

**Comment by stevenGravy** [comment]
> Meh, I would just make the docs link open in a new tab and call it a day.

Sure, I'll take a look.

**Comment by stevenGravy** [comment]
Currently it's doing a new tab so closing as fixed.
