### ISSUE TITLE
Firestore: Local User Setup Error

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#4145]
### Description

**What happened**:
1. On a fresh Teleport cluster, create a new local user. `tctl users add <user> --roles admin`
2. Visit user setup link. `https://<cluster_host>:3080/web/invite/d92a13c821739fe26ae4c3c501ce78f3`. Expired link... 
![image](https://user-images.githubusercontent.com/241714/88839552-d9f66e80-d1a0-11ea-9255-af316451f80a.png)
3. In Teleport debug logs, error fetching reset password token.
```
DEBU             pushing event Put for key '/web/users/<user>/params'. firestore/firestorebk.go:609
DEBU [USAGE]     Ignoring event "user.create". pro/auditlog.go:80
INFO [AUTH]      "<user>" user created auth/grpcserver.go:396
DEBU [USAGE]     Ignoring event "reset_password_token.create". pro/auditlog.go:80
DEBU             pushing event Put for key '/web/users/<user>/pwd'. firestore/firestorebk.go:609
DEBU             pushing event Put for key '/resetpasswordtokens/d92a13c821739fe26ae4c3c501ce78f3/params'. firestore/firestorebk.go:609
WARN             Failed to fetch a reset password token: rpc error: code = Internal desc = grpc: error while marshaling: proto: field "google.firestore.v1.Value.ValueType" contains invalid UTF-8. web/apiserver.go:1218
```

**What you expected to happen**:
User credential set up screen is presented. 

**How to reproduce it (as minimally and precisely as possible)**:
See above.

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v4.3.2git:v4.3.2-0-gc6d702ad8 go1.13.2
- Tsh version (use `tsh version`): N/A
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04.6 LTS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
GCP

**Browser environment**

- Browser Version (for UI-related issues): Chrome 84.0.4147.89
- Install tools: N/A
- Others: N/A

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by awly** [comment]
This is a new regression in 4.3 and appears to be cause by the UI redesign.
As part of the redesign, the signup flow was changes such that we generate a QR code when a user visits the invite link.
It looks like when we try to store that QR code in the backend, we send it in binary, not base64-encoded. Firestore doesn't like that.

We should either ensure that (1) nothing ever writes binary data to any backend or (2) firestore backend internally base64-encodes the data. The latter is more robust, but may be tricky to migrate.

**Comment by alex-kovoy** [comment]
if I recall correctly, the QR code format has not changed ([]byte)

**Comment by alex-kovoy** [comment]
But we did replace user/invite REST APIs with GRPC ones which may have caused a regression.

**Comment by wenxiaohe** [comment]
I have the similar env (Teleport enterprise v4.3.2, GCP Firestore & GCS, Teleport auth and proxy behind balancers), and ran into the same `Invitation Code Expired` issue. However there's no `Failed to fetch a reset password toke` in the log.

```
# useradd -m mytelportuser

# tctl users add mytelportuser --roles=admin
DEBU[0000] Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s  trace.component=sqlite
DEBU[0000] Synchronous: 0, busy timeout: 10000           trace.component=sqlite
DEBU[0000] Connecting to auth servers: [{10.25.0.29:3025 tcp }].
DEBU[0000] GRPC(): keep alive 1m0s count: 3.             trace.component=auth
User mytelportuser has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h0m0s:
https://<my_teleport_proxy>:3080/web/invite/6765682300f8fc0a01c8612648b0bbb8

NOTE: Make sure <my_teleport_proxy>:3080 points at a Teleport proxy which users can access.

# grep mytelportuser /var/log/syslog
Jul 31 17:23:39 <my_teleport_auth> teleport[9558]: DEBU             pushing event Put for key '/web/users/mytelportuser/params'. firestore/firestorebk.go:609
Jul 31 17:23:39 <my_teleport_auth> teleport[9558]: INFO [AUTH]      "mytelportuser" user created auth/grpcserver.go:396
Jul 31 17:23:39 <my_teleport_auth> teleport[9558]: DEBU             pushing event Put for key '/web/users/mytelportuser/pwd'. firestore/firestorebk.go:609

# date
Fri Jul 31 17:24:31 UTC 2020

# tctl tokens ls
DEBU[0000] Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s  trace.component=sqlite
DEBU[0000] Synchronous: 0, busy timeout: 10000           trace.component=sqlite
DEBU[0000] Connecting to auth servers: [{10.25.0.29:3025 tcp }].
Token                            Type       Expiry Time (UTC)
-------------------------------- ---------- ----------------------------
EXAMPLE-CLUSTER-JOIN-TOKEN       Proxy,Node never
018629af5adb0a149ab96ada11d3a5ed Password   31 Jul 20 18:16 UTC (51m35s)
6765682300f8fc0a01c8612648b0bbb8 Password   31 Jul 20 18:23 UTC (59m3s)
```
