### ISSUE TITLE
Add "How It Works" section for Application Access 

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#41471]
## Applies To

[How It Works](https://goteleport.com/how-it-works/)

## Details

The "How It Works" overview should be updated to include a section on Application Access.

## How will we know this is resolved?

Table Of Contents has been updated.

## Related Issues

N/A

**Comment by zmb3** [comment]
https://github.com/gravitational/teleport/issues/39875#issuecomment-2110340029
