### ISSUE TITLE
"websocket unavailable" when starting RDP session in full screen mode

### ISSUE THREAD

**Issue by uedvt359** [gravitational/teleport#41515]
Expected behavior:

I'm starting RDP sessions using Chrome/ium's App mode, to provide a more native feel, using the following command:

```
chrome.exe --app=https://teleport.local/web/cluster/teleport.local/desktops/the-hostname/myuser --start-fullscreen
```

After logging in with a Passkey, I'm prompted for MFA auth.

Current behavior:

After touching the yubikey when the Windows MFA prompt appears, I get the following error: "websocket unavailable"

![image](https://github.com/gravitational/teleport/assets/54625981/496fe049-81a9-4364-97de-0fb6f287322b)

devtools error:

![image](https://github.com/gravitational/teleport/assets/54625981/a6eaa3d5-47c7-4082-90c6-82698ab3a6b9)

**This error only occurs when trying to use MFA in full screen mode, if I hit F11 to get out of full screen mode, it works flawlessly.** 

This message is produced when the error occurs:
```
May 14 13:48:03 teleport.local teleport[3068931]: 2024-05-14T13:48:03+02:00 INFO [AUDIT]     mfa_auth_challenge.create challenge_allow_reuse:false challenge_scope:CHALLENGE_SCOPE_USER_SESSION cluster_name:teleport.local code:T1015I ei:0 event:mfa_auth_challenge.create time:2024-05-14T11:48:03.89Z uid:7394e7f6-842e-4209-8fb4-2f33da719448 user:myuser user_kind:1 events/emitter.go:288
May 14 13:48:05 teleport.local teleport[3068931]: 2024-05-14T13:48:05+02:00 ERRO [WEB]       expected MFA message type 10, got 1 cluster-name:teleport.local desktop-name:the-hostname session:6d11 user:myuser web/desktop.go:84

```

My Role has `spec.options.require_session_mfa: true`

This is reproducible reliably with Chrome 123.0.6312.123/32bit and MSEdge 123.0.2420.97 on Windows 10, and sometimes with chromium-121.0.6167.85-1.fc38.x86_64 on Fedora 38.

Previously, with Teleport 15.1.8, this used to work everytime/everywhere.

Bug details:
- Teleport version: 15.3.0, 15.3.4
- Recreation steps: use the above chromium command line for a RDP host with MFA enabled
- Debug logs: see above

**Comment by zmb3** [comment]
@ibeckermayer looks like there are 2 problems here:

1. Error handling. The error that we sent to the browser is not the error that the user sees. This is likely due to a timing issue related to us closing the websocket on error.
2. Resize functionality is breaking the per-session MFA flow, as the MFA decoder is seeing unexpected screen spec messages on the connection instead of the MFA message. We probably need to withhold resizes until after MFA completes.
