### ISSUE TITLE
Broken link on "Enhanced Session Recording" page

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4154]
## Summary
The "patch kernel" link next to 4.18 on the Ubuntu 18.10 line under https://gravitational.com/teleport/docs/features/enhanced_session_recording/ is broken.

It points to http://www.theubuntumaniac.com/2018/11/update-install-kernel-4191-stable-on.html which appears to have disappeared off the internet.

If we're going to rely on "unofficial" external sites in our documentation we probably ought to copy the content and host it ourselves.

**Comment by benarent** [comment]
I fixed this with https://github.com/gravitational/teleport/pull/4130 . For now I've removed the link and will only link to official sources, but since I couldn't find any for Ubuntu. I've left it empty for now.
