### ISSUE TITLE
Can’t scroll sideways in docs on mobile browsers

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4156]
![CEE23509-6205-48BE-A69A-FF8BACA6B8D5](https://user-images.githubusercontent.com/897821/89184504-4db4c480-d56f-11ea-877d-f79846d69d32.png)

The table in the [Teleport Docker quickstart](https://gravitational.com/teleport/docs/quickstart_docker/) doesn’t render well on mobile browsers (at least Safari on iOS) - you can’t scroll sideways, so it’s impossible to read the other columns in the table. It’s marginally better if you turn the phone sideways but even then some content is still cut off.

We should figure out a way to allow sideways scrolling in the docs on mobile browsers.

**Comment by ptgott** [comment]
This appears to be working now.
