### ISSUE TITLE
Machine ID: Improve the way Bots are shown in TAG

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#41596]
![image](https://github.com/gravitational/teleport/assets/16336790/66e535b4-746a-431b-8fb7-c99ca40bb3c9)

There's some small, relatively easy, improvements we could make:

- Show a Bot icon rather than a User icon
- Show the Bot's name rather than the Bot User's name

**Comment by strideynet** [comment]
@tigrato did that PR close this or is there a front-end element remaining ?

**Comment by tigrato** [comment]
> @tigrato did that PR close this or is there a front-end element remaining ?

Yeah, @ryanclark will add it.
jakub added the "closes ..."

**Comment by strideynet** [comment]
Thanks Tiago <3
