### ISSUE TITLE
AWS Console guide results in error

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#41660]
## Applies To

`docs/pages/application-access/cloud-apis/aws-console.mdx`

## Details

As reported by @taraspos:

> ...it seems like steps 1 and 2 need to be swapped in place. This is because in Step 1 we are trying to create IAM role with trust policy pointing to the role created in step 2,
however AWS validates existence of the target role, so it would fail with cryptic error (see screenshot). While if role from the step 2 exist, it works fine.

The error is "Invalid principal in policy".

## How will we know this is resolved?

A user can follow the AWS Console guide without receiving this error message.

**Comment by mmcallister** [comment]
I'm not finding the screenshot in this issue. I'll walk through to reproduce and correct as needed

**Comment by mmcallister** [comment]
I ran through 1 & 2 steps as-is and they seem to work.

I think the confusion is due to the fact that we are creating a trust policy with the `TeleportAWSAccess` role, even though we create that role later in the guide. (The part that shows: `aws iam create-role --role-name "TeleportAWSAccess" \
--assume-role-policy-document file://app-service-tp.json`)

This shouldn't cause an issue as we don't do the associations it till _after_ all of that's in place anyway: 

```
% aws ec2 associate-iam-instance-profile --iam-instance-profile Name="TeleportAWSAccess" --instance-id i-02367315518f174de --region us-east-2
{
    "IamInstanceProfileAssociation": {
        "AssociationId": "iip-assoc-0b9dfe098f62534d6",
        "InstanceId": "i-02367315518f174de",
        "IamInstanceProfile": {
            "Arn": "arn:aws:iam::278576220453:instance-profile/TeleportAWSAccess",
            "Id": "AIPAUBXDPZESTNZA7XYN5"
        },
        "State": "associating"
    }
}
```

@taraspos If I am misunderstanding, please let me know! Maybe you can grab the screenshot where you ran into the issue

**Comment by mmcallister** [comment]
Thanks for the clarification! I was able to generate the error:

```
/Users/mmcallister
% aws iam create-role --role-name "ExampleReadOnlyAccessv2" --assume-role-policy-document file://ro-access.json

An error occurred (MalformedPolicyDocument) when calling the CreateRole operation: Invalid principal in policy: "AWS":"arn:aws:iam::AWS_ACCESS_ACCOUNT:role/TeleportAWSAccess2024"
```

Apologies, I did not catch that the role was already in place in this aws account. Looks like the 4 steps under **_Give the Teleport Application Service permissions to assume other roles_** need to be moved up (going to change this header a bit too, maybe **_Create a role with trust policy for the Teleport Application Service_.**)

**Comment by mmcallister** [comment]
@taraspos Requesting a sanity check on the updates:

https://docs-o2vv5noi7-goteleport.vercel.app/docs/enroll-resources/application-access/cloud-apis/aws-console/

**Comment by taraspos** [comment]
Yeah, it looks good.
