### ISSUE TITLE
Email Access Request Plugin Support for Teleport Enterprise Cloud 

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#41675]
What would you like Teleport to do?
With Teleport Enterprise Cloud, Teleport manages Access Request plugins for you, and you can enroll in Access Request plugins from the Teleport Web UI. Currently, the email option is not supported. 

What problem does this solve?
The customer's justification is that email is the best method to reach approvers. Teleport Cloud can already send invite emails to new users to register a new account on the Teleport cluster. 

If a workaround exists, please include it.
Email notifications can be implemented in Teleport Cloud using the self-hosted environment [instructions](https://goteleport.com/docs/access-controls/access-request-plugins/ssh-approval-email/). The customer will need to supply an SMTP service.

**Comment by FabioSpagna** [comment]
The workaround has a logic issue.. 
In a cloud system, the customer as expecting that Access Request have the same logic as all the other message sent by the system (eg enrol).
Adding a plugin for a built-in function is an extra-cost (plugin and maintenence) that let the cloud env less attractive

**Comment by zmb3** [comment]
This is now being tracked at #45969
