### ISSUE TITLE
Pick a default name for cluster_name vs hostname

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4170]
### Feature Request
When creating a new cluster using `teleport configure` we don't pre-populate `cluster_name` and we instead pick the hostname. This can be pretty long in cloud environments; to help get people setup i think we should pick a default, I'm almost tempted to just call it `teleport` 

### Motivation
Make quickstart easier.

### Who's it for?
OSS User

**Comment by webvictim** [comment]
Using `teleport` as a default will probably lead to a lot of people needing to rename their cluster during PoCs. It’ll also cause trouble if people try to set up a leaf cluster with default values and link it back to a root cluster which is also named `teleport`.

Maybe we should pick a UUID or some kind of other relatively unique value, or have some semi-smart logic which tries to deduce where you’re running the cluster and name things accordingly. Alternatively, we could do something like add a mandatory `--cluster-name` flag to `teleport configure` with some useful help text, which will force people to choose a sensible name at setup time.

**Comment by zmb3** [comment]
`teleport configure` has a `--cluster-name` flag.
