### ISSUE TITLE
Allow configurable teleport package repo name

### ISSUE THREAD

**Issue by bernardjkim** [gravitational/teleport#41731]
### What would you like Teleport to do?
Teleport automatic updates should support a configurable teleport repository name.

### What problem does this solve?
Users are able to set an arbitrary name for the Teleport package repository name. However, the teleport updater is hardcoded to assume that the Teleport package repository name is "teleport".

Some users require a custom name for their Teleport package repository, so this limitation is blocking enrollment of automatic updates for these users.

### If a workaround exists, please include it.
The teleport updater is hardcoded to only work with the "teleport" package repository. So to workaround this:
- Update the package repository name to "teleport"
- Modify the `teleport-upgrade` script and replace the hardcoded instances of the "teleport" repo name with the custom repo name. Ex: `--enablerepo="teleport"`, `--disableexcludes="teleport"`, `--repo="teleport"`.

**Comment by zmb3** [comment]
Is this the same as #30881?

**Comment by bernardjkim** [comment]
Oh, yup.
Closing. Duplicate of https://github.com/gravitational/teleport/issues/30881.
