### ISSUE TITLE
SAML groups are stored in the clear in SSH certificates

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#4175]
### Feature Request
Teleport-issued SSH certificates include all SAML-assigned groups as cleartext in the L(locality) attribute of the Subject field of the certificate. This leaks a significant amount of sensitive information to an adversary who has compromised the client machine and has access to the certificate. The adversary could leverage this information to focus their attack on specific groups or systems of interest. It seems unnecessary to include this information in the clear in the certificate.

Confirm with openssl x509 -in ~/.tsh/keys/hostname/user-x509.pem -text

Desired Behavior
Consider either 1) removing the SAML groups from the certificate entirely, and caching it instead in the Auth daemon's persistent datastore, or 2) at least encrypt the SAML group information in the certificate, so it cannot be read by an adversary who has compromised the client machine.

### Who's it for?
Enterprise

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190134506177097/1190141146394875) by [Unito](https://www.unito.io/learn-more)

**Comment by awly** [comment]
Are SAML claims any more sensitive that other identity metadata? What are some examples where this info helps the attacker? 

Given a compromised certificate, an attacker has access to anything that certificate has.
So this wold mostly be security-through-obscurity.
It's a reasonable hardening step, but if we do it, we should consider all identity info (like Teleport login/groups and k8s users/groups), not just SAML.

**Comment by jon-can** [comment]
Response from the customer who raised this:
The SAML claims include all the groups the user belongs to, which can convey information about what department the user works in, what their level/rank is, and what systems they have access to. Note that *all* groups that are assigned to the user in the IdP are passed through and embedded in the certificate, not just the ones relevant to Teleport. So the current scheme can disclose information about many other systems beyond Teleport/SSH/K8s, including enterprise SaaS applications, CIFS shares, RDP, internal web applications, etc.

This would provide a hands-on attacker with valuable intelligence about the internal organizational and systems structure of the target company. The attack might use this information as hints about what other systems to target next, as well as how valuable it would be to pursue one user versus another for further compromise effort. Obscuring this information has practical benefits in slowing down attackers and making them work harder and take more time to map out and understand the target environment. During an attack, time is valuable and slowing down the attacker gives defenders more time for detection and response.

So yes, this is in part security-by-obscurity, but obscurity can be a valuable element of defense-in-depth in real-world attack scenarios.

**Comment by klizhentas** [comment]
We decided that Okta/others can control the attribute statements sent to teleport, and that's a good way of addressing this issue.
