### ISSUE TITLE
Teleport does not properly handle SSH sessions initiated by Microsoft Visual Studio Code

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#4176]
### Feature Request
A significant number of our users run Microsoft Visual Studio Code in conjunction with the Microsoft "Remote - SSH" extension to edit code locally on their laptops while saving files to a remote Unix machine over an SSH connection. On macOS, when terminating the SSH connection at a Teleport Node daemon, the VSCode extension is not able to successfully inject and run its remote daemon. However, it does work properly when terminating the connection with sshd instead of Teleport Node. It also works properly on Windows regardless of sshd vs Teleport Node. If you examine the VSCode extension's debug logs, the problem seems related to unexpected terminal echoing confusing the extension.

This issue is forcing us to allow users to terminate their Teleport connections with sshd instead of Teleport Node daemons, meaning we don't get session recording. It also forces us to continue to permit users to keep SSH keys on their local machines.

VSCode functions properly with other solutions like OpenSSH and Smallstep.

We would like the VSCode SSH extension to work properly with SSH connections that terminate with the Teleport Node daemon, so we can use Node daemons exclusively and can disable sshd.

### Who's it for?
Enterprise

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190134506177097/1190140535819823) by [Unito](https://www.unito.io/learn-more)

**Comment by webvictim** [comment]
Could we get some more detailed steps for a reproduction, please? I regularly use VSCode myself on a Mac with the Remote SSH extension, connected to a Linux server running Teleport - it works fine.

Knowing the differences between my working setup and a non-working setup will help us isolate what the issue might be.

**Comment by russjones** [comment]
@jon-can Can you provide some more details. This may be a documentation issue because @webvictim has gotten this to work.

**Comment by webvictim** [comment]
I did a bit more investigation into this and did manage to reproduce the issue with "default" setting in VS Code. It seems that there's something with the local server model that recent versions of VS Code are using that doesn't work well with Teleport.

As a workaround, set `"remote.SSH.useLocalServer": false` in your VS Code config and then try connecting again. This worked for me in my testing.

**Comment by klizhentas** [comment]
Working correctly, verified as working.

**Comment by lamhoangtung** [comment]
@webvictim Can you give a small example of how to use VSCode Remote - SSH with an SSH server running Teleport ? I typically use `.ssh/config` for a typical SSH server, but for Teleport I don't know how to write a proper config or are there any other way ?

**Comment by webvictim** [comment]
@lamhoangtung See my post here on[ how to set up Teleport with an SSH config file](https://github.com/gravitational/teleport/discussions/5530)! Please comment there if you have any questions.

**Comment by lamhoangtung** [comment]
Hi @webvictim. I had tried your post and the SSH seems to work, but I notice this error before every login:
```console
Certificate invalid: name is not a listed principal
```
Also VSCode remote are not working. I'm not sure if it due to the warning message above. But I want to resolve it first before moving on to VSCode. Are there anything that I might be doing wrong here ?

**Comment by webvictim** [comment]
@lamhoangtung As this issue is closed, I replied to you here: https://github.com/gravitational/teleport/discussions/5530#discussioncomment-520589

We can continue to talk there.

**Comment by lamhoangtung** [comment]
I replied with some other issue over there. Thanks @webvictim

**Comment by KasperSkytte** [comment]
> As a workaround, set `"remote.SSH.useLocalServer": false` in your VS Code config and then try connecting again.

Man. I have struggled with getting teleport to work with VSCode and also ansible. I pretty much never use a terminal without editing files or developing, which involves using `ssh` instead of `tsh` (sadly). I find teleport awesome, but this has kept me from using it for more than a year. I see this now, thank you so much!

On a sidenote, maybe worth making `tsh` integrated with VSCode - remote, or is that up to Microsoft?

**Comment by KasperSkytte** [comment]
@webvictim maybe this line should be mentioned in the documentation page for VSCode or a version range be specified?

**Comment by webvictim** [comment]
@KasperSkytte The weirdest thing is that it works for me whether local server is enabled or not, but it doesn't work out of the box for a colleague unless the local server is disabled. I suspect it's some kind of quirk of my environment.

I can raise a PR to get `"remote.SSH.useLocalServer": false` added to the docs if it's made the difference between things working and not working for you.

**Comment by KasperSkytte** [comment]
@webvictim I had it working on a single node behind NAT (though probably irrelevant) without adjusting that setting, but suddenly it doesn't. So I get the weirdness. But I haven't had any issues so far since I've set it to false. It could just be added as a note for people to try if struggling with it.

**Comment by webvictim** [comment]
Might be a silly question but you're definitely logging in with `tsh login` to get an active cert before starting VS Code, right?

**Comment by KasperSkytte** [comment]
@webvictim better to be sure. Yes I am :)
