### ISSUE TITLE
Teleport auth should refuse to start when jumping major versions

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#41782]
From time to time we get S1's from folks who attempt to jump multiple major versions at once when upgrading despite our [compatibility guarantees](https://goteleport.com/docs/upgrading/overview/#component-compatibility) that state that only adjacent major upgrades are supported. This leads to corrupted backend, broken cluster and lengthy recovery time.

Let's prevent these situations by having auth to just refuse to start when it detects an incompatible upgrade path is being attempted. One way to implement this would be to have auth save its version in the backend and then check it the first thing during startup to make sure that last "saved" version is not more than 1 major version behind, and abort startup if it is before any backend migrations are done, and exit with an error exit code and a clear error message explaining that this is unsupported upgrade path and linking to the compatibility documentation.

**Comment by hugoShaka** [comment]
This issue is only solved for stateful local teleport installations (when you don't use ephemeral containers or VMs). https://github.com/gravitational/teleport/issues/49848 describe why the current implementation does not solve the issue in most Teleport deployment.
