### ISSUE TITLE
Decouple session playback and events

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4180]
## Description

Customers feedback with the new UI is that session playbacks are mixed with audit logs, there is no way to focus on just playback.

**Comment by benarent** [comment]
I'm feeling this issue, especially with enhanced audit logging. 

![image](https://user-images.githubusercontent.com/559288/91247000-18cb0600-e706-11ea-84e0-3b587985720c.png)

**Comment by zmb3** [comment]
This was addressed - session recordings have their own page in the UI now.
