### ISSUE TITLE
Join Tokens: Web UI support

### ISSUE THREAD

**Issue by avatus** [gravitational/teleport#41867]
Teleport should enable join token operations available in `tctl tokens` in the Web UI 

task breakdown:

- [ ] Add sort cache service for JoinTokens
- [ ] Add grpc methods/pagination for ListJoinTokens
- [ ] Create apiserver routes for JoinTokens CRUD
- [ ] UI/UX for the web component (prototype done by @avatus , feedback from kenny after)
- [ ] Final updates/adjustments to web UI
- [ ] Integrate with Discover UI (token reuse)

**Comment by zmb3** [comment]
@avatus I moved your task breakdown into the existing issue (#31671) which is already linked in our goals doc, just so we don't have multiple issues describing the same work.
