### ISSUE TITLE
Roles.Equals has a problem in matching two arrays

### ISSUE THREAD

**Issue by WhiteN1ght** [gravitational/teleport#4186]
### Description

**What happened**: 
In some special cases, it will misjudge that two arrays are equal, such as if parameter named roles contents {Auth,Auth,Auth} and parameter other contents {Auth, Web, Node} that function will return true means that two arrays are equal.

**What you expected to happen**: Roles array {Auth,Auth,Auth} is not equal array {Auth, Web, Node}

**How to reproduce it (as minimally and precisely as possible)**: 
The elements in the two arrays are compared in sequence, or the deduplication judgment is added

### Environment
found this  by code review

**Comment by awly** [comment]
Thanks for the report. Could you link which `Roles.Equals` method you're referring to?
https://github.com/gravitational/teleport/blob/master/lib/services/role.go seems to be doing comparisons correctly.

**Comment by WhiteN1ght** [comment]
> Thanks for the report. Could you link which `Roles.Equals` method you're referring to?
> https://github.com/gravitational/teleport/blob/master/lib/services/role.go seems to be doing comparisons correctly.

https://github.com/gravitational/teleport/blob/master/roles.go
and function is :
// Equals compares two sets of roles
func (roles Roles) Equals(other Roles) bool
