### ISSUE TITLE
Teleport binary was built without web assets, Docker 4.3.4

### ISSUE THREAD

**Issue by vfylyk** [gravitational/teleport#4203]
### Description

**What happened**:

Seems like the version 4.3.4's docker image came without web assets and won't run without them.

**What you expected to happen**:

Docker image to run.

**How to reproduce it (as minimally and precisely as possible)**:

```
# docker run -it --rm --name teleport.test -v $(pwd)/etc:/etc/teleport  quay.io/gravitational/teleport:4.3.4
[AUTH]    Auth service 4.3.4:v4.3.4-0-g65669d5d3 is starting on 0.0.0.0:30003.
[PROXY]   Reverse tunnel service 4.3.4:v4.3.4-0-g65669d5d3 is starting on 0.0.0.0:30002.
ERRO [PROC:1]    Critical service proxy.init has exited with error the teleport binary was built without web assets, try building with `make release`, aborting. service/signals.go:145
error: the teleport binary was built without web assets, try building with `make release`
```

### Environment
- Teleport version (use `teleport version`): v4.3.4-0-g65669d5d3
- Tsh version (use `tsh version`): NA
- OS (e.g. from `/etc/os-release`): NA

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Docker

**Comment by webvictim** [comment]
Thanks for the report, you are indeed correct. It looks like some of the build process got broken during a migration. I'm working on a fix.
