### ISSUE TITLE
It's not possible to select text in vim in Web UI

### ISSUE THREAD

**Issue by zabszk** [gravitational/teleport#42032]
Expected behavior:
It should be possible to select text in vim (in the Web UI, eg. in order to copy it to system clipboard) by holding shift while selecting the text using mouse. It was possible in the **previous** Teleport versions - I don't know the exact version that introduced this bug, but it was a couple of months ago.

Current behavior:
Selection is removed right after releasing the mouse key, just like it was possible in Teleport in the past (and like it's possible in most of the SSH clients). When selecting without holding shift key, vim enters visual mode and it's not possible to copy the selected text to system clipboard.

Bug details:
- Teleport version: v15.3.7 git:v15.3.7-0-gd8e06e8 go1.21.10
- OS: Debian 12 (bookworm)
- Tested browsers (bug is related to Web UI): Firefox, Edge, Chrome

**Comment by zmb3** [comment]
Likely caused by #36763.

**Comment by zabszk** [comment]
> This seems to work again in 16. I can select with the mouse (with or without shift key). VIM correctly enters visual mode, stays in visual mode and selected and I'm able to yank to the system clipboard.

I just tested it on 16.1.0 using Edge and Chrome and it doesn't work for me. Selecting with shift mode instantly removes the selection when I release mouse button. Selecting without shift enters VIM visual mode, selection stays, but it's not possible to copy it to the system clipboard (option "Copy" is not available after right clicking).

**Comment by zabszk** [comment]
Issue is fixed in 16.2.1 (might have been fixed earlier). Tested using Firefox, Edge and Chrome.
