### ISSUE TITLE
Add functionality to `teleport configure` so it allows setting a nodename

### ISSUE THREAD

**Issue by milos-teleport** [gravitational/teleport#42127]
### What would you like Teleport to do?

Add functionality to `teleport configure` so it allows setting a nodename, similarly to `teleport node configure --node-name`

### What problem does this solve?

There are users who would like this option exposed via the CLI so they can avoid editing the `teleport.yaml` file

### If a workaround exists, please include it.

Edit the `teleport.yaml` file

```yaml
teleport:
    nodename: my_custom_name
```

**Comment by milos-teleport** [comment]
This feature is similar to https://github.com/gravitational/teleport/issues/10102

**Comment by zmb3** [comment]
`teleport configure` is generally discouraged in favor of more specific configure commands.

If you're just trying to configure `ssh_service`, then you should prefer `teleport node configure` instead.

(`teleport node configure` supports a `--node-name` flag which does exactly what you'd expect)

**Comment by milos-teleport** [comment]
What if the user wants to run `teleport configure` to set up the auth node?
