### ISSUE TITLE
RPM/DEB Packages incorrectly installing binaries to /usr/local/bin

### ISSUE THREAD

**Issue by gardar** [gravitational/teleport#42130]
**Expected behavior**:

Teleport binaries should be installed to `/usr/bin` as per the [Linux Filesystem Hierarchy Standard (FHS)](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html).

**Current behavior**:
Teleport binaries are currently being installed to `/usr/local/bin`, which is intended for manually installed software, not for package-managed software.

**Bug details**:
- Teleport version: 15.3.7
- Recreation steps:
  1. Install Teleport using the RPM/DEB package.
  2. Check the installation directory of the binaries.
- Debug logs: N/A

**Description**:

Hi.

I noticed the RPM and DEB packages for Gravitational Teleport install binaries to `/usr/local/bin`. According to the [Linux Filesystem Hierarchy Standard (FHS)](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html), package-managed software should go to `/usr/bin` instead.

The FHS specifies that `/usr/local` is for manually installed software, not for packages managed by a package manager. Installing to `/usr/local/bin` can cause conflicts with manually installed software.

**Suggestion**:
Could you update the packages to install binaries in `/usr/bin`? This would align with FHS and prevent potential conflicts.

**Comment by zmb3** [comment]
After consideration, we've decided that we won't be addressing this issue.

While we agree that using `/usr/bin` for the deb/rpm packages is more correct per the FHS standard, we believe that our customers care more about not having their deployments breaking than conforming to FHS. Teleport packages have been installed to /usr/local/bin for years and the risk of breaking an existing setup is too great to justify.
