### ISSUE TITLE
Not specifying a service starts it.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#4214]
Found something surprising while working on AAP. If you don't specify a section in `teleport.yaml`, Teleport will configure that section and start it with defaults. For example, if you omit `proxy_service` in `teleport.yaml`, Teleport will configure and start the proxy service.

Is this intentional?

**Comment by stevenGravy** [comment]
I think that's similar if you just do a `teleport start` with no configuration file.  All services are on by default.

**Comment by webvictim** [comment]
To confirm the intended behaviour for anyone reading this in the future:

Services which will automatically be started by default (i.e. you must specify `enabled: false` to disable them):
- `auth_service`
- `proxy_service`
- `node_service`

Services which will **not** automatically be started by default (i.e. you must specify `enabled: true` to enable them):
- `app_service`
- `kubernetes_service`
- `db_service`
- probably any other services added to Teleport in future

This is quite confusing, but cannot be easily changed as we have to maintain backward compatibility.

**Comment by webvictim** [comment]
Maybe this needs documentation now that we have more modes Teleport can run in.
