### ISSUE TITLE
"Cancel and Logout" button does nothing

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#42209]
Expected behavior:

In my web UI session after completing a CA rotation, I got this error modal with a "Cancel and Logout" button. I'd expect this button to actually log me out (clear the cookie) and return to the login page.

<img width="566" alt="Screenshot 2024-05-30 at 4 10 27 PM" src="https://github.com/gravitational/teleport/assets/16807901/6713946f-69ce-438b-a002-d5f6f4533d8c">

Current behavior:

The button appears to do nothing, and I have no way to logout/login, except for manually clearing the cookies.

Bug details:
- Teleport version: v16.0.0-alpha.2
- Recreation steps
  - log in to web ui
  - rotate user CA
- Debug logs

**Comment by webvictim** [comment]
Looks like the same sort of behaviour as https://github.com/gravitational/teleport/issues/41651 (happens after enabling IP pinning)
