### ISSUE TITLE
4.3.5 WebUI has wrong version

### ISSUE THREAD

**Issue by kinghrothgar** [gravitational/teleport#4222]
### Description

I am running the docker image teleport-ent:4.3.5. Running `teleport version` shows the correct version of `Teleport Enterprise v4.3.5git:v4.3.5-0-g122349e78 go1.13.2`. The WebUI shows 4.3.2.

![Screen Shot 2020-08-18 at 12 00 21 PM](https://user-images.githubusercontent.com/1952767/90548590-68c82c80-e14a-11ea-89bb-4f8fdd7cabbf.png)

**Comment by stevenGravy** [comment]
hi @kinghrothgar I recently updated a docker auth and proxy and it's showing as 4.3.5.  Can you confirm the steps you took to replace the docker image? That was in a docker-compose env for myself.

**Comment by kinghrothgar** [comment]
I pulled `quay.io/gravitational/teleport-ent:4.3.5`. I then pushed this to GCP's gcr repository. I then edited the GKE deployment to use the new 4.3.5 image from the repository. I have logged into each of the 3 pods and ran `teleport version` and they show the correct version. However, the Web-UI still shows `4.3.2`.

**Comment by kinghrothgar** [comment]
I am using Firestore and Google Storage as my backends. Is this something that is stored there and maybe didn't get migrated?

**Comment by kinghrothgar** [comment]
After several days the Web UI started showing the correct version.

I just upgraded another cluster and am seeing the same behavior. It appears the version is somehow being cached somewhere and that eventually gets resolved?

**Comment by kinghrothgar** [comment]
Update, it took an hour or so for this cluster to show the correct version. Interestingly the proxy updated first.

**Comment by zmb3** [comment]
Sounds like this resolved itself.
