### ISSUE TITLE
Need to attach CA-Bundle on Database Resources

### ISSUE THREAD

**Issue by 4durban** [gravitational/teleport#42221]
Expected behavior:

The scenario is that we are deploying Teleport Enterprise. We have been adding resources to the cluster. We started with ssh and apps and everything worked fine. The "bug" arise when we added a Database.

We have a database with TLS exposed. If we connect to the database directly (without going through Teleport but using TLS) there is no issues, everything works fine. In fact the TLS Server Certificate that we use in the database is the same that we use for the web (the applications in Teleport). The issue comes when we add the Database to the cluster, Teleport Database Service does not accept the Database TLS Certificate, because it is emitted by an "unknown CA", but in fact, is the same certificate that the applications, and we had no issue with the application TLS certificate. 

So, I think that there is some kind of issue checking the certificate, the behavior is different in Application Service than it is in Database Service for checking CA Root Trust.

The message is:

ERROR 1105 (HY000): Database service cannot validate database's certificate: tls: failed to verify ceritifcate: x509 certificate signed by a unknown authority. Please verifiy if the correct CA bundle is used in the database config.

The biggest issue is that this certificate is a Sectigo certificate, which is trusted by everybody, browsers, os...

```
adurban@XXXX:~$ openssl s_client -starttls mysql -showcerts -connect mysql.XXXX.com:3306
CONNECTED(00000003)
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
verify return:1
depth=0 CN = *.XXXX.com
verify return:1
---
Certificate chain
 0 s:CN = *.XXXX.com
   i:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: XXXX 2024 GMT; NotAfter: XXXX 2025 GMT
-----BEGIN CERTIFICATE-----
MIIGMDCCBRigAwIBAgIRAPL0cEE5gNUF4Hvb0fbSxSEwDQYJKoZIhvcNAQELBQAw
gY8xCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDE3MDUGA1UE
```

This made us to specify the ca bundle in the database file.

And then we have an application that is a web with the same certificate without any issues.

```
adurban@XXXX:~/Downloads$ openssl s_client -showcerts -connect XXXX.XXXX.com:443
CONNECTED(00000003)
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
verify return:1
depth=0 CN = *.XXXX.com
verify return:1
---
Certificate chain
 0 s:CN = *.XXXX.com
   i:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: XXXX 2024 GMT; NotAfter: XXXX 2025 GMT
-----BEGIN CERTIFICATE-----
MIIGMDCCBRigAwIBAgIRAPL0cEE5gNUF4Hvb0fbSxSEwDQYJKoZIhvcNAQELBQAw
gY8xCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDE3MDUGA1UE
```

I have no issues with the web application, the Sectigo CA is NOT unknown, it is trusted by default, but this is not the case for the database.

I did not expect to have to specify the ca bundle when i didn't need to specify it in Apps.

Would you mind checking why I need to do it?

Bug details:
- Teleport version: 15.3.4
- Recreation steps: 

Enroll any database with a trusted CA TLS certificate such as Digicert or Sectigo without indicating the CA Bundle to Teleport and check for the error message. Replicate this with a Web Application and see that there is no error of the CA.

**Comment by greedy52** [comment]
@4durban 

Thanks for filing this issue.

The reason that CA bundle is required to be specified in this case, is that the "default" behaviour expected is the database servers will be serving Teleport-issued DB server certs. Thus by default, Teleport only checks the cert presented by the database server against Teleport's DB server CA. This behaviour is best preserved for security reasons.

What do you think instead of providing a CA bundle, we add an option to trust system certs?
```yaml
  - name: "self-hosted-database"
    protocol: "postgres"
    uri: "localhost:5432"
    tls:
      trust_system_certs: true
```
This will still require a flag in your case but there is no need to provide the actual pem file.

**Comment by 4durban** [comment]
Hello @greedy52

I think that the fact you assume that all users are going to use Teleport Issued certs is quite a big assumption to make. In our case all of our databases already had TLS Certificates provided by Trusted CAs because we already need it for our applications and wanted to make sure we had valid ones to avoid issues like this one. 

The fact that depending on the technology you have a different behavior for CA Trust is quite confusing for the admin. Why in web application you don't do this assumption too? You can also generate TLS Certs for webs using Teleport, but you indeed trust the system CA Certs. So I guess that this should be the case for all of them.

I do not understand how the fact that you trust the System CA Certs is going to affect security. In order for this to be an issue a Root CA Private key should be exposed (which I see quite unlikely but also would have bigger implications) or that our DNS is compromised, which again would have much bigger implications.

What do you think about making it the other way around? That by default all System CA Certs are trusted but if you, by your own will, want to increase security you only trust Teleport CA.

```
  - name: "self-hosted-database"
    protocol: "postgres"
    uri: "localhost:5432"
    tls:
      only_trust_teleport_ca: true (default false)
```
That would be aligned with the other technologies because by default the System CA Certs are trusted but if you want a stronger security, as you say, you can configure it. And since Teleport CA is already trusted this is a non-breaking change (users would not need to change anything in order for it to keep working).

**Comment by 4durban** [comment]
Hello @greedy52 

I still think that the fact that most people do not encrypt its databases with TLS should not be considered the default behavior. I think that the premise should be, the system is already using the best practices possible, such as using TLS for self-hosted databases and they are signed by a public CA (I think that we can agree that this is the best practice possible) so this should be the baseline, not the other way around.

I am just saying this because if you take as a baseline the common scenario and not the "best practice" one you are going to force  people that is already implementing best practices to work harder than the ones that are not, taking into account that is quite likely that they have already put more effort into implementing this best practices.

If you choose to not implement the System CA, which I do not share but completely understand, it would be nice to have the flag that you mention. Just to avoid copying the different CAs that we have. Because depending on the hundreds of databases that we already have, some of them are signed by Digicert, others by Sectigo and so on. All of them trusted by the System but not by Teleport, which increases tremendously the amount of resources and time to enroll databases.

**Comment by greedy52** [comment]
> using TLS for self-hosted databases and they are signed by a public CA (I think that we can agree that this is the best practice possible) so this should be the baseline

Agree and disagree. Self-signed certificates have a bad reputation as you don't want to trust a Web app with a random cert when browsing. 

For Teleport's database access case, you control both ends with mTLS. In theory, fewer CAs you trust means less attack surface. For self-signed, you only need to trust one CA but you do have to protect your key for the CA. GCP Cloud SQL, for example, generates server certs per instance. There is no general CA for validation and you validate against that specific cert. Well, Cloud SQL doesn't even have domain names (only IPs). I am sure Google can keep their private key secure. And if you are Teleport Database CAs, we are protecting it.

That said, I agree that publicly-signed database domains are secure in general and provide good value to programs accessing the db (that are not going Teleport). We are happy to add the `trust_system_cert_pool ` flag as previously mentioned and to preserve the existing behaviour.

**Comment by 4durban** [comment]
Thank you for the information. That would be lovely.

How long do you think that this may take? 

We are still enrolling the database resources and we wanted to know if we should wait for the feature or keep going like we used to for the moment.
