### ISSUE TITLE
Document how the `--invite` flag can be used to integrate with other tools

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#42255]
What would you like Teleport to do?

Moderated Sessions appear to have a field `--invite` flag, it appears the contents of this flag get added to the `session_tracker` as well.

However, this field is poorly documented: it is [documented as `--invited`](https://goteleport.com/docs/ver/14.x/access-controls/guides/moderated-sessions/). In addition, there is little documentation on how this field can be used with other tools (like a email notification system) to alert moderators that they should join a session.

What problem does this solve?

Moderators could get notified when they are required to join a session automatically.

**Comment by zmb3** [comment]
> it appears the contents of this flag get added to the session_tracker as well.

I haven't looked in much detail, but at a glance I don't see any code that does this.

The only thing I see is that we set the `TELEPORT_SESSION_JOIN_MODE` environment variable (yes, join mode, this is a typo that has existed for 2 years) to the JSON-encoded array of whatever you pass to `--invite`.


FYI @rudream this could be a good use-case for the new notifications system.
