### ISSUE TITLE
HSM Support

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#4225]
Add HSM support to Teleport to store CA private key material on HSM.

Initial release will only support [YubiHSM 2](https://www.yubico.com/product/yubihsm-2) and PKCS#11 to sign and verify signatures.

Long term plan for HA is needed.

**Comment by travelton** [comment]
Consider plan for migration path or tooling for rotating from on-disk certs to HSM.

**Comment by awly** [comment]
Per https://github.com/gravitational/teleport/blob/master/rfd/0025-hsm.md, there are 3 major implementation chunks:

- [ ] PKCS#11 config, key provisioning and signing (@awly)
- [ ] Backend schema update and migration (@Joerger)
- [ ] CA rotation updates (@awly)

**Comment by nklaassen** [comment]
HSM support merged to master in https://github.com/gravitational/teleport/commit/da951723f65bd4710df050f2f87254287ec4c762, backport to 7.x is open here https://github.com/gravitational/teleport/pull/7981

**Comment by nklaassen** [comment]
HSM support is released in Teleport 7.2
