### ISSUE TITLE
Add Apple Silicon (ARM) Macs into the build matrix

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4226]
### Feature Request
This has already come in via a survey, and for early adopters we should support `tsh` for Apple Silicon Macs, and quickly after `teleport` depending on demand.   

### Motivation
Via survey and the march of new hardware.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by awly** [comment]
This is similar to https://github.com/gravitational/teleport/issues/3383, support `aarch64` architecture but with `darwin` OS.
I don't think we can cross-compile without an actual machine with that architecture and OS available, due to CGO.

**Comment by russjones** [comment]
I think you can apply/buy a developer kit from Apple: https://developer.apple.com/programs/universal/

**Comment by benarent** [comment]
I have applied, I'm unsure if we're cool enough but If not we can just wait for the boxes to become GA and add then.

**Comment by webvictim** [comment]
It'd be nice for us to already be offering these binaries straight out of the gate when they become GA. If we could add an `aarch64` Mac Mini as a build box then it should be fairly easy to port our existing release/signing/notarization process over (although we may have to build https://github.com/mitchellh/gon from source if they aren't providing an `aarch64`/fat binary)

**Comment by benarent** [comment]
Looks like Apple is going to announce these tomorrow. Might be a hot item for Q4.

**Comment by webvictim** [comment]
Teleport builds fine using `go version go1.16beta1 darwin/arm64`. Once 1.16 is out of beta we can upgrade Go on all our build boxes and should then be able to add an Apple Silicon box. I haven't tested signing, but `gon` compiles fine for `darwin/arm64` so it should work.

**Comment by pschisa** [comment]
+1 for teleport-ent binaries for `aarch64-darwin`

**Comment by zmb3** [comment]
Good to close this one out Cam?

**Comment by camscale** [comment]
Teleport v13 is now built with AMD64/ARM64 universal binaries for MacOS for all release artifacts. The terraform plugin is also now a universal binary and is just waiting for a release. I think we can call this done.
