### ISSUE TITLE
Consul backend

### ISSUE THREAD

**Issue by jaxxstorm** [gravitational/teleport#423]
Rather than having to deploy etcd for the HA config, it would be excellent to be able to use consul's K/V store to store the same data etcd supports.

Many places already have support and configuration for consul already.

**Comment by josegonzalez** [comment]
Might it be better to use [libkv](https://github.com/docker/libkv) to abstract the backends completely, thereby potentially offering support for multiple backends out of the gate. If desired, I can sit down and work on a pull request for this, as we'd love to use teleport but currently have a consul cluster and not etcd.

**Comment by josegonzalez** [comment]
Still willing to dig into this if there is a desire to support it from the core team.

**Comment by code-ape** [comment]
I'd be interested in this feature. Along with perhaps integrating Hashicorp's Vault to secure the data that's stored. No idea how complex of a feature this is but I'd be willing to contribute some to see this happen!

**Comment by ajvb** [comment]
Is this something the maintainers would be behind? I would much prefer to make use of our battle-tested consul cluster over setting up etcd just for this.

**Comment by klizhentas** [comment]
@ajvb we will accept the PR with consul backend with no problem for sure

**Comment by ekristen** [comment]
Anyone actively working on this?

**Comment by ekristen** [comment]
Another problem with Consul is that it doesn't do TTLs like most other K/V stores, so that will have to be addressed as well.

**Comment by apestel** [comment]
@ekristen DynamoDB does not support TTL either. I have done it the same way the BoltDB implementation did. It remove the key if the TTL expired. Not a big deal.

**Comment by ekristen** [comment]
After further investigation libkv handles TTL across its backends, the only deficiency at the moment is that it doesn't support ACL tokens for consul or etcd.

**Comment by ekristen** [comment]
FWIW https://github.com/docker/libkv has a PR open for dynamodb and I'm working on a PR that supports consul access tokens, ISTM that any new backend could be implemented using libkv and could eventually migrate the existing backends over to using libkv so there is a consistent interface.

**Comment by ajvb** [comment]
I've gotten started on an implementation: https://github.com/gravitational/teleport/compare/master...ajvb:ajvb/consul

Hopefully will have a PR by end of day.

**Comment by CumpsD** [comment]
Perhaps it could use https://www.vaultproject.io/ as backend? :)

**Comment by sandstrom** [comment]
Yes, support for vault as an auth-backend would be very useful.

**Comment by jiangytcn** [comment]
hello,  any update for supporting the vault backend ? 

If not , I'd like to work on this :)

**Comment by klizhentas** [comment]
No work is done to my best knowledge yet. If you are going to work on this, please create a design issue describing your approach first, so we can discuss

**Comment by klizhentas** [comment]
Also keep in mind that there is a major backend refactor wrapping up in branch sasha/cache3 that, once merged will change all interfaces on the backend

**Comment by zmb3** [comment]
I'm going to close this due to inactivity. Happy to take a fresh look if there is renewed interest in the future.

**Comment by sandstrom** [comment]
No worries! 

In case others have this question, there is another open source project called Boundary, which have support for Consul/Vault (https://www.boundaryproject.io/).
