### ISSUE TITLE
Login page doesn't pull OTP from macOS/iOS passwords

### ISSUE THREAD

**Issue by bjacobgordon** [gravitational/teleport#42300]
Expected behavior:
OTP field autofills using 2FA code generated by Apple's native password manager

Current behavior:
OTP field stays blank, have to right click and manually select "autofill" -> "passwords" -> search "teleport", etc.
Demonstrated [here](https://github.com/gravitational/teleport/assets/61476868/31733cf8-1b28-4462-9b15-2309496527c0).

Problem:
Input field needs `autocomplete="one-time-code"` attribute.

**Comment by zmb3** [comment]
Thanks for the helpful video demonstration. Can you confirm what version of Teleport you're running? From the looks of it, it seems like an old (and potentially EOL) version.

**Comment by bjacobgordon** [comment]
It’s the web version, and the client gives me no indication of the version.

Didn’t seem to be encoded in our URL, starting with
https://teleport.throwingboulders.com

- Jacob

**Comment by zmb3** [comment]
Yep, 8.0.1 has been end of life for almost 2 years now, so I'll close this out.

If you are able to reproduce the same behavior on a current version please open a new issue and we'll take a look.
