### ISSUE TITLE
Hashicorp Vault Secrets Engine - Teleport tctl

### ISSUE THREAD

**Issue by t94swFBAQbzkM3jXt5Q5Ut8T** [gravitational/teleport#4233]
### Feature Request
We would like the ability to create dynamic tokens via Hashicorp Vault
### Motivation
We would find this feature valuable as it allows us to leverage existing secret storage technologies to issue/revoke tctl tokens
### Who's it for?
Enterprise

**Comment by russjones** [comment]
https://github.com/gravitational/teleport/issues/4225

**Comment by zmb3** [comment]
This is not something we're looking to support at this time.

The general direction we are heading is to try and eliminate the need to securely distribute join tokens at all (with things like AWS IAM joining or OIDC-based joining).
