### ISSUE TITLE
RDP Client: screen turns white after a resize event - `DOMException: Failed to execute 'putImageData' on 'CanvasRenderingContext2D': The source has been detached`

### ISSUE THREAD

**Issue by uedvt359** [gravitational/teleport#42349]
Expected behavior:

the session should continue to work.

Current behavior:

When alt-tabbing, I sometimes get a resolution change of +/- 1px. Sometimes, this causes the following exception in the devtools console:

 `DOMException: Failed to execute 'putImageData' on 'CanvasRenderingContext2D': The source has been detached`

then, the screen turns white and the session needs to be disconnected (using the "..." menu) and restarted to work again. This is shown in the devtools (chrome 125 for windows):

![image](https://github.com/gravitational/teleport/assets/54625981/68d21806-41ca-4f36-a41a-a62897d8b5dd)

I don't have a screenshot ready, but firefox shows a slightly different error message: it complains that width and height are invalid (again for putImageData' on 'CanvasRenderingContext2D)

this may or may not be related to #42006, which i reported earlier.

Bug details:
- Teleport version: ~~15.3.7~~15.3.5
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
This should have been fixed by https://github.com/gravitational/teleport/pull/41492

**Comment by uedvt359** [comment]
apologies, i should have checked the latest version first (i didn't at first, as i did not find anything relevant in the changelog). i upgraded to 15.4.0 and will close this ticket, unless it manifests again. thank you for your quick response.

**Comment by zmb3** [comment]
Well, the fix was in 15.3.6, so if you are still seeing it on 15.3.7 then it's an incomplete fix. I'll reopen this so the team can investigate.

cc @probakowski @ibeckermayer

**Comment by uedvt359** [comment]
i re-checked which teleport version i was running, and it turns out it was 15.3.5. i was switching back and forth between versions, and must have accidentally stayed on an older release. sorry - i should have noticed this before.
