### ISSUE TITLE
Users without a second factor are locked out in the transition to v16

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#42386]
__Expected behavior:__

Unspecified.

__Current behavior:__

Users that lack a second factor on v15 cannot login by any means on v16 and have to be reset. This is because the "off" and "optional" second factor modes can't be set anymore.

__Bug details:__
- Teleport version: v16.0.0-alpha.3
- Recreation steps: see above
- Debug logs: not necessary

**Comment by zmb3** [comment]
This is intentional, right? People should set second factor to on or webauthn prior to upgrading.
