### ISSUE TITLE
Support custom CAs in the event-handler helm chart

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#42425]
If a user's Teleport proxies are using TLS certs signed by a custom CA, there is currently no supported way in the event-handler helm chart to make the plugin trust the CA, errors like the following will be observed:

```
transport: Error while dialing: failed to dial: Get \"https://teleport.example.com:443/webapi/find (https://teleport.example.com/webapi/find)\": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Our kube-agent helm chart already supports this according to this guide https://github.com/gravitational/teleport/discussions/12129

The event-handler chart is most of the way there, it already supports custom volume mounts via the `volumes` and `volumeMounts` variables, but there is no built-in variable for setting the necessary `SSL_CERT_FILE` environment variable in the container

**Comment by elevesque-sfr** [comment]
Hello,

We have the same problem here. The teleport proxy uses a server certificate delivered by our own CA.
The plugin can't verify the certificate sent during the HTTPS requests.

```
ERROR REPORT:
Original Error: *errors.errorString context deadline exceeded: connection error: desc = &#34;transport: Error while dialing: failed to dial: Get \&#34;https://xxxxx.pack.valentine.example.com:443/webapi/find\&#34;: tls: failed to verify certificate: x509: certificate signed by unknown authority&#34;
```
The teleport Helm chart supports it but not the teleport event handler plugin Helm chart.

Regards,
Eric

**Comment by elevesque-sfr** [comment]
Hello,

Thanks for fixing this issue. We will test it when we will upgrade to Teleport 16 (September).

Regards,
Eric
