### ISSUE TITLE
Naming: auth_servers: &  auth_service inconsistency 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4245]
### Feature Request
Customers currently define auth settings under `auth_service` yet, we ask nodes to connect to `auth_servers`. Since we support more than just servers, FQDN & a Proxy we should use standard language. 

```diff
    # list of auth servers in a cluster. you will have more than one auth server
    # if you configure teleport auth to run in HA configuration.
    # If adding a node located behind NAT, use the Proxy URL. e.g.
    #  auth_servers:
    #     - teleport-proxy.example.com:3080
-   auth_servers:
+   auth_service:
        - 10.1.0.5:3025
        - 10.1.0.6:3025
```

This change should be backwards compatible. 

### Motivation
Consistency and using modern terminology

### Who's it for?
OSS User, Pro, Enterprise

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190029021439585/1190136168574075) by [Unito](https://www.unito.io/learn-more)

**Comment by strideynet** [comment]
Closing this as covered by the V3 configuration which has clarified this with the introduction of `auth_server` and `proxy_server.
