### ISSUE TITLE
Jira Ticket Cannot be Created if too Many Roles are Requested

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#42454]
When creating an access request with multiple roles, you can reach a point where the Jira ticket will no longer be successfully created if requesting too many roles.  Based on testing it seems that this may be related to the summary limit of Jira to contain 255 characters max and the fact that Teleport puts every role requested into the summary.

Request is to have a standard ticket response(s) that will never exceed the 255 character limit for Jira ticket summary since the list of roles requested is contained in the ticket body (if this does prove to be the source of the issue)

**Comment by zmb3** [comment]
@marcoandredinis didn't you just fix this?

**Comment by marcoandredinis** [comment]
That's correct 👍 
https://github.com/gravitational/teleport/pull/42825
