### ISSUE TITLE
Unable to open psql interactive session with Teleport Connect

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#42490]
Expected behavior:

Postgres Teleport Connect db session would work as in version 15.3.7.

Current behavior:

A Postgres session will not connect in Teleport Connect in version 15.4.0 that does work with 15.3.7.  Using the command `tsh db connect` in version `15.4.0` does work so this seems specific to Teleport Connection.

![image](https://github.com/gravitational/teleport/assets/60704961/ffcd2d32-bb01-47dc-976b-1e2c00cced74)

Note the working example connection is with psql 14 as the client to a Postgres 15 server version.

Bug details:
- Teleport Connect: 15.4.0
- Recreation steps
1. Have a available postgres db
2. Confirm works with `tsh db connect`
3. Attempt with the same user and db name in Teleport Connect 15.4.0

**Comment by ravicious** [comment]
Can you reproduce this consistently? If so, do you mind running `open -a "Teleport Connect" --args --connect-debug`, reproducing the problem and attaching logs?

I tried reproducing it on 15.4.0 (connecting to 16.0.0-alpha.3 cluster) and everything seems to work. From your screenshot, it looks like the TTY for psql was created, but for some reason it's not transmitting any data.

**Comment by stevenGravy** [comment]
> Can you reproduce this consistently? If so, do you mind running `open -a "Teleport Connect" --args --connect-debug`, reproducing the problem and attaching logs?
> 
> I tried reproducing it on 15.4.0 (connecting to 16.0.0-alpha.3 cluster) and everything seems to work. From your screenshot, it looks like the TTY for psql was created, but for some reason it's not transmitting any data.

Reattempts are not failing again.  I'll close this for now and attach logs if it happens again and can reproduce consistently.
