### ISSUE TITLE
Host YUM repo

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4255]
### Feature Request
We publish a RPM but it still requires some extra work. We've a customer who will mirror RPMs anyway and having a Yum repo would help their ops. 

It seems we could start with s3; this other project had a good background for it. 
http://tylerpower.io/post/hosting-yum-repo-on-s3/

### Motivation
Large customer looking to mirror RPMs; this will make things easier

### Who's it for?
Enterprise

**Comment by webvictim** [comment]
The RPM repo will be released with Teleport 5.0.

**Comment by webvictim** [comment]
RPM repo is out - see setup instructions at https://rpm.releases.teleport.dev/
