### ISSUE TITLE
Jumphosting to ssh node

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4257]
### Description
**What happened**:

Attempting to jumphost to a OpenSSH server through the Proxy.  The user attempted has the teleport user cert in their authorized key. A `tsh ssh --port=22 root@IP` works. Attempting the jumphost approach users receive access denied or the web login prompt opens (with SSO enabled).

**What you expected to happen**:

A user can connect through a jumphost proxy to a OpenSSH node. 

**How to reproduce it (as minimally and precisely as possible)**:

Export the user cert from the auth server `tctl auth export --type=user > teleport_user_ca.pub`
Copy the results into a authorized key on a openssh server node for a user

confirm you can tsh to that node:
`tsh ssh --port=22 myuser@<IP/Domain>

now attempt to do the jumphost

`tsh ssh -J proxy:3023 myuser@<IP/Domain>:22`

### Environment
* Teleport version (use `teleport version`): 4.3.5
* Tsh version (use `tsh version`): 4.3.5
* OS (e.g. from `/etc/os-release`): Ubuntu 18.04
* Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190029021439585/1190604627860696) by [Unito](https://www.unito.io/learn-more)

**Comment by ptgott** [comment]
@stevenGravy Is this addressed now that we've updated our OpenSSH guide?

**Comment by ptgott** [comment]
Closing this, as we've updated the OpenSSH guide substantially since this issue was opened (https://github.com/gravitational/teleport/commits/master/docs/pages/server-access/guides/openssh.mdx). If there are still issues using this guide, we should open a new GitHub issue.
