### ISSUE TITLE
Multiple tabs opened in Web SSH/Dashboard navigation

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4262]
### Description
**What happened**:

A user can quickly start having multiple tabs open as they navigate to open new ssh sessions and selecting the Dashboard link. Once the user logs out they then need to close out several tabs instead of just two. 

![image](https://user-images.githubusercontent.com/60704961/91450952-e24ad380-e84a-11ea-8ea8-e9938964d9db.png)

**What you expected to happen**:

The dashboard link should return to the already opened tab.  Otherwise there should be a mechanism to close tabs already opened as part of this session. 

**How to reproduce it (as minimally and precisely as possible)**:

Log into the web UI.  Open a ssh session.  Select the Dashboard link in the ... menu option.  Open a new ssh session from tab.  a new tab will open.  And the sequence will continue. Log out and all the pages will return to Login.

### Environment
* Teleport version (use `teleport version`): 4.3.5
* OS (e.g. from `/etc/os-release`): ubuntu 18.04
* Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Browser environment**

* Browser Version (for UI-related issues): Chrome 85.0.4183.83

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190029021439585/1191012887996447) by [Unito](https://www.unito.io/learn-more)

**Comment by alex-kovoy** [comment]
> The dashboard link should return to the already opened tab. Otherwise there should be a mechanism to close tabs already opened as part of this session.

@stevenGravy  It's not possible to programmatically set a focus to another browser tab from within JS. So we cannot "close" or "navigate to" other browser tabs. So what this ticket is asking for is not possible. This, however, does not mean that we cannot address it differently by revisiting the following questions:   

1. How often would a dev jump between cluster management (cluster view) and the terminal? 
2. Is accessing a terminal from the cluster management screen (node list) is a primary use case? 
3. Can we open a terminal in the same window? If so, how would I navigate back? (given that the terminal is a standalone app)

**Comment by alex-kovoy** [comment]
@stevenGravy closing it as it's not technically possible
