### ISSUE TITLE
Mobile app for `tsh vnet`

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#42646]
## What would you like Teleport to do?

`tsh vnet` would work amazingly well on iOS/Android devices via a "virtual VPN"/VPN-on-demand integration on the phone itself.

## What problem does this solve?

Allows the use of native mobile apps connecting to servers/REST endpoints behind Teleport. This isn't currently possible, and would increase the mass-market appeal of Teleport a lot.

## If a workaround exists, please include it.

Use something like Tailscale, which has mobile clients and VPN integrations.

**Comment by zmb3** [comment]
Can we just add this context to #3343?

**Comment by webvictim** [comment]
I guess. I hoped that a separate smaller app just to do this would be simpler to write and have a more obvious value proposition.
