### ISSUE TITLE
Design to Expand Account Settings

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#42691]
In addition to existing Security/Auth settings, it needs to support:
* Theme preference (system default, light, dark)
* Keyboard layout for use with Windows Desktop sessions (select list for language/country)

**Comment by rishibarbhaya-design** [comment]
Submitted Wireframes Options for the Account settings page considering scalability
**Wireframe link:** https://www.figma.com/board/8c7QEVaLt2WL6upVgvFZKl/AWS-Integration?node-id=53-10815&t=OPUcaJ0o9PI3RpkI-1

Feel free to add comments.

**Comment by rishibarbhaya-design** [comment]
Based on feedback we have finalized Option 1 with Account Settings Side Navigation and eliminated default Side Navigation from this page.  

**Design Link:** https://www.figma.com/design/rlcaLyLb3AkG6MW4fnRSAG/Profile-Settings?node-id=1-2&t=EncLzlBu3kMH28rp-1

**Comment by rishibarbhaya-design** [comment]
Side Navigation Functionality

![Image](https://github.com/gravitational/teleport/assets/88441969/49a81128-b10d-4d8a-8c16-ddad234d215c)

- Remove Profile from the current implementation
- Highlight Tier 1 of the page to show all the sections of the page.
- Moving ahead we will highlight Tier 2 and perform section scrolling.

**Comment by rishibarbhaya-design** [comment]
Revise our existing profile dropdown

**Current Implementation**
![Image](https://github.com/gravitational/teleport/assets/88441969/16e2c3d1-a122-46d1-8b36-5fd754010a65)

**Revised Implementation**
![Image](https://github.com/gravitational/teleport/assets/88441969/5f87b6e9-b63b-43a2-a049-b7af4a49eb08)

- Remove Email Address from the top navigation -> resulting in more space in the top navigation.
- Add Email Address on the top of the dropdown.
- Remove Switch to Light Theme and move it to the Account Settings page -> Preferences.
