### ISSUE TITLE
Non-existing bug bounty program in SECURITY.md 

### ISSUE THREAD

**Issue by nielss-hdr** [gravitational/teleport#42745]
There is currently no clear way of reporting a security issue. The link in SECURITY.md  to Teleport's HackerOne program (https://hackerone.com/teleport) returns a 404. 

Could you help me with finding the right avenue to report a potential vulnerability?

Thanks!

**Comment by zmb3** [comment]
You can report your findings via the form on https://goteleport.com/security/
