### ISSUE TITLE
Teleport Slack Plugin Setup Documentation missing a script

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#4275]
## Summary
https://gravitational.com/teleport/docs/enterprise/workflow/ssh_approval_slack/
Under “Create User and Role for Access” it reads “The below script will create a yaml resource file for a new user and role”, but there's currently no script. This script should be there:

```# This command will create two Teleport Yaml resources, a new Teleport user and a
# Role for that users that can only approve / list requests.
$ cat > rscs.yaml <<EOF
kind: user
metadata:
  name: access-plugin-slack
spec:
  roles: ['access-plugin-slack']
version: v2
---
kind: role
metadata:
  name: access-plugin-slack
spec:
  allow:
    rules:
      - resources: ['access_request']
        verbs: ['list','read','update']
    # teleport currently refuses to issue certs for a user with 0 logins,
    # this restriction may be lifted in future versions.
    logins: ['access-plugin-slack']
version: v3
EOF
# Run this to create the user and role in Teleport.
$ tctl create -f rscs.yaml

**Comment by benarent** [comment]
This is strange, it's in master. I think I just need to redeploy https://github.com/gravitational/teleport/blob/master/docs/4.3/enterprise/workflow/ssh_approval_slack.md#create-user-and-role-for-access
