### ISSUE TITLE
Expose/Manage Users from Web UI

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#4277]
### Feature Request
Being able to control user information like when we use `tctl users ls`, `tctl get users/[account]`, `tctl users add` from web would be helpful since we need to use CLI to obtain that information today.

### Motivation
For customers who wish to manage users from the UI instead of CLI. 

### Who's it for?
OSS User, Pro, Enterprise

**Comment by benarent** [comment]
We'll have the ability to list and add users in 5.0. Duplicate of https://github.com/gravitational/teleport/issues/2945

**Comment by benarent** [comment]
Duplicate of #2945

**Comment by travelton** [comment]
@benarent Ah, thanks. I searched and search and couldn't find a ticket! `Local User CRUD UI`. Closing this one.

**Comment by fvmediahub** [comment]
I tried with latest open source version (9.3.2) but could not found Users management menu.
![image](https://user-images.githubusercontent.com/73211394/172322441-a03225be-6127-478f-8c39-27795d55d892.png)

I have login with admin account which was created in CLI as
```sh
tctl users add teledemo   --roles=admin
```
Can you please tell me what is the option/config to enable this feature?

**Comment by fvmediahub** [comment]
Never mind, the right role should be editor
