### ISSUE TITLE
Statically configured Oracle database breaks `tctl`

### ISSUE THREAD

**Issue by Tener** [gravitational/teleport#42845]
Expected behavior:

`tctl` works irrespective of configured databases

Current behavior:

With statically configured Oracle database in `teleport.yaml`:

```yaml
  - name: oracle
    protocol: oracle
    uri: localhost:2484
    static_labels:
      env: dev
```

`tctl` will complain about lack of enterprise license and refuse to start

```
tctl --debug edit user/tener
2024-06-12T17:05:50+02:00 DEBU             Debug logging has been enabled. common/tctl.go:287
2024-06-12T17:05:50+02:00 DEBU             reading config file: /etc/teleport.yaml config/configuration.go:397
ERROR: oracle database protocol is only available with an enterprise license
```

Bug details:
- Teleport version: v16 alpha
- Recreation steps: add static database to local Teleport configuration, issue `tctl` command which reads the local configuration
- Debug logs: see above.

**Comment by zmb3** [comment]
Good find. We should only be doing these checks in the auth server, not in `tctl`.

@greedy52 can you assign a dev to fix this (today if possible) so we can get it in v16?

**Comment by greedy52** [comment]
@zmb3 assigned to @gabrielcorado. 

> Good find. We should only be doing these checks in the auth server, not in tctl.
we can try moving that validation to somewhere only auth does the check.
