### ISSUE TITLE
Update `docs/pages/reference/networking.mdx`

### ISSUE THREAD

**Issue by tenaciousdlg** [gravitational/teleport#42917]
## Applies To

https://goteleport.com/docs/reference/networking/

## Details

For the following line Teleport only shows the Auth Service as an applicable Downstream service.

```

3024 | Auth Service | SSH port used to create reverse SSH tunnels from behind-firewall environments into a trusted Proxy Service instance.
```

It should be updated to indicate the protocol type (believe it is SSH) and that this port is used for all reverse tunnel connections (something like App Access would use this too). 

## How will we know this is resolved?

When the doc is updated to the scope that it includes the additional information.

**Comment by zmb3** [comment]
Isn't port 3024 used by the proxy service (not auth)?

**Comment by tenaciousdlg** [comment]
![Screenshot 2024-06-14 at 9 12 09 AM](https://github.com/gravitational/teleport/assets/28679416/447a64a7-7780-45ef-947d-480b1d66c4ab)

The docs show Auth service. What drove this is in the Ports without TLS routing section we did not see anything for App Access. There does not appear to be specific call outs for Database or Kubernetes Access either but I am inferring that Kubernetes goes through SSH?

**Comment by zmb3** [comment]
Sorry Chris, I'm not understanding what you're asking for here.

> It should be updated to indicate the protocol type (believe it is SSH) and that this port is used for all reverse tunnel connections

Doesn't it already say this? _SSH port used to create reverse SSH tunnels_ mentions both the protocol (SSH) and that it is used to create reverse tunnels. What am I missing?

**Comment by tenaciousdlg** [comment]
The issue we were seeing is that the context reads as it only applies to SSH reverse tunnels whereas it is used for any reverse tunnels (Application Access as an example).

**Comment by zmb3** [comment]
I see. _All reverse tunnels_ in Teleport are SSH reverse tunnels. Seems like that's the confusion and you thought that only applied to server access.
