### ISSUE TITLE
'proxy_checks_host_keys must be one of: yes, no'

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4292]
### Description

**What happened**: The validation for `proxy_checks_host_keys` does not parse truthy/falsey values correctly.

**What you expected to happen**: You should be able to use 'true' or 'false' as arguments to this config file setting, rather than only 'yes' or 'no'.

**How to reproduce it (as minimally and precisely as possible)**: 
```yaml
auth_service:
  proxy_checks_host_keys: false
```

### Environment
- Teleport version (use `teleport version`): Teleport v4.2.7

**Comment by russjones** [comment]
YAML supports `[true, on, yes]` for `true` and `[false, off, no]` for `false`. Let's make sure we're consistent for these across the board. In documentation let's stick to `yes` or `no.`

**Comment by webvictim** [comment]
We definitely have a mix of both in documentation currently. We can update it after the true/false parsing code is fixed across the board.

**Comment by espadolini** [comment]
Stumbled upon something similar to this today, for `proxy_protocol`, both in the `auth_service` section and in the `proxy_service` section:

```
ERROR: bad "proxy_protocol" parameter value: "false", supported values are on or off
```

It seems like we can just change the function calls in `lib/config/configuration.go` from `utils.ParseOnOff` to `utils.ParseBool` for this one.

**Comment by espadolini** [comment]
(this is nice to have if we are parsing JSON as YAML, as a typed JSON bool will turn into a `"true"`/`"false"` YAML scalar)

**Comment by ptgott** [comment]
The scope of this issue has changed substantially, so I am going to close this and open a new issue focused on standardizing the way we show example Boolean values in documentation YAML snippets.
