### ISSUE TITLE
cannot start teleport web GUI

### ISSUE THREAD

**Issue by anasri72** [gravitational/teleport#4293]
### Description

From terminal output there are several errors which are showing on screen which is all the same. 

```
teleport     | WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 172.18.0.3:3080->31.14.151.7:6687: i/o timeout\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:260 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:197 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1358 runtime.goexit\nUser Message: failed to peek connection\n" multiplexer/multiplexer.go:200
```

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by benarent** [comment]
@anasri72  Can you please add the version and paste the setup of teleport.yaml

**Comment by webvictim** [comment]
What is the actual problem here? Is something not working as expected? These warnings are usually benign.

**Comment by zmb3** [comment]
What is this multiplexer error meant to indicate?

I'm seeing this same error after updating from 4.4.2 to 4.4.4 today.  After the upgrade completed we noticed our node was missing from the cluster.  In the auth server logs I'm seeing the node try to join, a message that it joined successfully, and then this error.  The process repeats every few seconds.

**Comment by strideynet** [comment]
Closing this as stale / duplicate of [more descriptive tickets](https://github.com/gravitational/teleport/issues/17538)
