### ISSUE TITLE
Got Internal Error When Accessing New Teleport

### ISSUE THREAD

**Issue by obed-budiman** [gravitational/teleport#4294]
got internal error when log in to https://port.tokopedia.net
user : obed.budiman

**Comment by webvictim** [comment]
I’m afraid we can’t help with this as your report doesn’t contain any useful information. You might be better off speaking with internal support at Tokopedia for assistance - find out who administrates the Teleport cluster and ask them for help.

In order for us to assist, you would need to add more detail:
- the cluster setup
- Teleport version being used
- the exact commands and process used to log in
- logs from the Teleport server
