### ISSUE TITLE
Documentation - default value of --browser for tsh login

### ISSUE THREAD

**Issue by GwonsooLee** [gravitational/teleport#4297]
### Description

**What happened**:
According to the reference, the default value of `--browser` is `none` which `tsh login` should not open browser without flag.

But it opens if I miss the flag. 

**What you expected to happen**:
I don't know what it is intended for. But as one of teleport users, opening browser is kind of irritating. So I personally want it to be none by default :) 

Or just correct the documentation.

**How to reproduce it (as minimally and precisely as possible)**:
Just download the lastest version of tsh and try login

```
$ tsh version
Teleport v4.3.2 git: go1.14.5
```

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
AWS

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools: Chrome
- Others:

**Comment by webvictim** [comment]
We’ll correct the documentation if this is indeed wrong.

FYI - Teleport only opens a browser if it needs to, as part of the SSO login flow. This is a mandatory step as authentication data is passed from the browser to the `tsh` client in this way. The flag is just intended to suppress the automatic browser opening and allow a user to open the URL manually in the browser of their choice.
