### ISSUE TITLE
provide more informative error on Teleport Connect with device trust errors

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#43021]
Expected behavior:

User messages would be given:
  - mismatch of web session user to Teleport Connect user
  - No trusted device id found.

Current behavior:

A very generic error is given for those flows.

![image](https://github.com/gravitational/teleport/assets/60704961/bd0ff6f8-3869-4dd3-89a4-75e2e8468e89)

Bug details:
- Teleport version: 16.0.0
- Recreation steps
 1. Attempt to login with web session to a trusted device through Teleport Connect on a unenrolled device

1. Attempt to login with trusted device in web session. Have another user logged in for Teleport Connect.

**Comment by codingllama** [comment]
There are many different situations where we reply with "invalid device web token", all obfuscated on purpose so we don't give a roadmap of failures to attackers-to-be.

That said, I'm not against de-obfuscating a few key errors for UX.

Talking specifics:

> 1. Attempt to login with web session to a trusted device through Teleport Connect on a unenrolled device

An unenrolled device doesn't generate a device web token, meaning it won't open Connect. I'm not sure which scenario you reached here. (#43126 has more ideas related to this.)

> 2. Attempt to login with trusted device in web session. Have another user logged in for Teleport Connect.

This is, IMO, a Connect error. It should be smart enough to log-in with the correct user (as specified by the "open device_authenticate" URL. FYI @avatus @ravicious.

In the meantime we can tweak this error to be more friendly.

**Comment by codingllama** [comment]
> There are many different situations where we reply with "invalid device web token", all obfuscated on purpose so we don't give a roadmap of failures to attackers-to-be.

Adding to this, you can see the actual reasons for failure in the audit log.

![Screenshot 2024-07-05 at 7 23 16 PM](https://github.com/gravitational/teleport/assets/12500300/01018a02-dfcd-4c56-ab1a-aade1574bcdf)

**Comment by codingllama** [comment]
Closing after the revisited error message.
