### ISSUE TITLE
tsh sessions should only initiate from trusted devices (MDM)

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#4304]
### Feature Request
Users in an organization should only be allowed to initiate tsh sessions from trusted devices. We use mobile device management software to issue device managed certificates. Devices that have those managed certificates are considered trusted devices.

### Motivation
Security. We don't want users initiating tsh sessions from a non-trusted device.

### Who's it for?
Enterprise

**Comment by klizhentas** [comment]
@jon-can @russjones we think our way (with U2F device attestation) is a better system than MDM.
MDM support is unlikely

**Comment by strideynet** [comment]
@codingllama - can this be considered a duplicate of the Device Trust work ?

**Comment by codingllama** [comment]
Yep, sounds like it. I'll close on those grounds, feel free to message me for details.
