### ISSUE TITLE
Trusted Cluster create, delete events show as Unknown in Audit Log

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4307]
### Description

**What happened**:

The trusted cluster event  shows as Unknown type and description in the Audit Log.  The same occurs for a delete.

![image](https://user-images.githubusercontent.com/60704961/92758118-64172280-f35c-11ea-88de-12765f2b6c7b.png)

**What you expected to happen**:

A type of Trusted Cluster create and a description of the trusted cluster that was added or removed.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy two teleport clusters.  Add a trusted cluster and look in the trusted cluster Audit Log.

### Environment
- Teleport version (use `teleport version`): 4.3.5
- OS (e.g. from `/etc/os-release`): Ubuntu 

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by webvictim** [comment]
Think this is a UI issue @alex-kovoy?

**Comment by webvictim** [comment]
Closing in favour of #4507
