### ISSUE TITLE
AMI Let'sEncrypt Renewal Failure Scenario

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#4311]
### Description
When using the Teleport AMIs, Let'sEncrypt generates certificates on the box, then we synchronize the `/etc/letsencrypt` directory to S3 (occurs [here](https://github.com/gravitational/teleport/blob/master/assets/aws/files/bin/teleport-get-cert)). 

When other Teleport machines join the cluster, it will download the Let'sEncrypt certificates (occurs [here](https://github.com/gravitational/teleport/blob/master/assets/aws/files/bin/teleport-all-pre-start#L18)). 

If the original machine that executed the Let'sEncrypt certificate generation process no longer exists... The renewal process will fail. The AMI has no scripts to rebuild the required Let'sEncrypt directory structure to renew an expired certificate. Let'sEncrypt uses symlinking to publish certificates "live" from a simple archive location. 

Example Paths:
```
/etc/letsencrypt/live/<domain>/cert.pem -> /etc/letsencrypt/archive/<domain>/cert1.pem
/etc/letsencrypt/live/<domain>/chain.pem -> /etc/letsencrypt/archive/<domain>/chain1.pem
/etc/letsencrypt/live/<domain>/fullchain.pem -> /etc/letsencrypt/archive/<domain>/fullchain1.pem
/etc/letsencrypt/live/<domain>/privkey.pem -> /etc/letsencrypt/archive/<domain>/privkey1.pem
```

**What happened**:
With a fully configured Teleport Cluster, rebuild the machine that initially generated the Let'sEncrypt certificates. Now, attempt to renew the certificates on a newly bootstrapped node within the same cluster. The required directory structure does not exist, therefore it cannot renew the certificates. 

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/certbot/_internal/renewal.py", line 63, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/local/lib/python3.7/site-packages/certbot/_internal/storage.py", line 466, in __init__
    self._check_symlinks()
  File "/usr/local/lib/python3.7/site-packages/certbot/_internal/storage.py", line 533, in _check_symlinks
    "expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: expected /etc/letsencrypt/live/<domain>/cert.pem to be a symlink
Renewal configuration file /etc/letsencrypt/renewal/<domain>.conf is broken. Skipping.
```

**What you expected to happen**:
Any machine in the Cluster is able to renew Let'sEncrypt certs and sync them to S3. 

**How to reproduce it (as minimally and precisely as possible)**:
Using any AMI, build a Teleport Cluster with Let'sEncrypt as the SSL provider. While maintaining the contents of the S3 bucket, rebuild your Teleport Cluster with the same domain name. Attempt to renew the certificate manually `certbot renew`. 

### Environment
- Teleport version (use `teleport version`): 4.3
- Tsh version (use `tsh version`): 4.3
- OS (e.g. from `/etc/os-release`): N/A

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by webvictim** [comment]
Similar to https://github.com/gravitational/teleport/issues/3610

**Comment by travelton** [comment]
@webvictim Yes, thank you! Closing this one so we don't have duplication.
