### ISSUE TITLE
Warn users about the lack of a trusted device and how to fix it

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#43126]
__What would you like Teleport to do?__

Since v16 Teleport added Web UI support for device trust. The feature works by showing a prompt, during web login, to open Connect and authorize the user's trusted device. The prompt is not shown for users that lack a trusted device.

We should warn users that the lack of a trusted device is likely to impede access (based on cluster and role settings) and, more importantly, provide instructions on how to fix it (namely, that they need to enroll their device).

__What problem does this solve?__

This solves the problem of users having reduced access but not knowing how to fix it.

__If a workaround exists, please include it.__

The workaround is to instruct the user to enroll their device.

- https://goteleport.com/docs/access-controls/device-trust/device-management/#web-ui-fails-to-authenticate-trusted-device

**Comment by codingllama** [comment]
@avatus for UI/UX input, if you have any ideas.

**Comment by avatus** [comment]
Just thinking of things off the top of my head.
1. we can return something in the same place as `deviceWebToken` like an error message to display "hey, you need device trust to access stuff and you don't have a token. run this command to enroll your device"
2. maybe even forgo the above and have some way to enroll via the web but... im assuming that would have to open connect as well to do it there. 
3. ok, final bit of ramble, if device trust required, still open connect, and if we detect the device _isnt_ enrolled, enroll and then auth all in the same flow?

**Comment by codingllama** [comment]
Related issue: #43020

- #43020

**Comment by codingllama** [comment]
> Just thinking of things off the top of my head.
> 
> 1. we can return something in the same place as `deviceWebToken` like an error message to display "hey, you need device trust to access stuff and you don't have a token. run this command to enroll your device"

That was my original thinking - we do some checks in the backend and return something to let the UI/tsh know about potential access problems.

> 2. maybe even forgo the above and have some way to enroll via the web but... im assuming that would have to open connect as well to do it there.

Yes, that would need to go through Connect.

> 3. ok, final bit of ramble, if device trust required, still open connect, and if we detect the device _isnt_ enrolled, enroll and then auth all in the same flow?

I like this one. It's a bit more work (we don't have a way to say that the expected device doesn't exist yet) but it's pretty smooth.

**Comment by codingllama** [comment]
Solved by the "yellow shield" work.
