### ISSUE TITLE
AppArmor policy on ubuntu 24.04 + SegFault

### ISSUE THREAD

**Issue by GuillaumeCisco** [gravitational/teleport#43168]
Expected behavior:
Teleport-connect launches correctly without bugs

Current behavior:
Teleport-connect displays an error on launch, and after fix still segfault sometimes

Bug details:
- Teleport version: 16.0.1
- Recreation steps

```shell
$> teleport-connect
LaunchProcess: failed to execvp:
/opt/Teleport
[34780:0618/110357.688481:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Invalid argument (22)
Trace/breakpoint trap (core dumped)
```

This issue appeared after upgrading to ubuntu 24.04.
It looks like there is an issue with electron app based on chromium:
- https://github.com/electron/electron/issues/41066
- https://forum.unity.com/threads/unity-hub-and-x-ubuntu-24-04-not-starting-workaround.1586640/

I used this workaround:
Create file `/etc/apparmor.d/teleport-connect` with content:
```
abi <abi/4.0>,
include <tunables/global>

profile teleport-connect /opt/Teleport\ Connect/teleport-connect flags=(unconfined) {
userns,

# Site-specific additions and overrides. See local/README for details.
include if exists <local/teleport-connect>
}
```

Then:
`$> sudo systemctl restart apparmor.service`

Sometimes it works with a displayed error, sometimes it directly segfault:
```
$> teleport-connect --trace-warnings
(node:41551) UnhandledPromiseRejectionWarning: Error: Window was closed before frontend app got initialized
    at BrowserWindow.<anonymous> (/opt/Teleport Connect/resources/app.asar/build/app/main/index.js:21565:9)
    at Object.onceWrapper (node:events:633:26)
    at BrowserWindow.emit (node:events:530:35)
    at emitUnhandledRejectionWarning (node:internal/process/promises:201:15)
    at processPromiseRejections (node:internal/process/promises:297:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:41551) Error: Window was closed before frontend app got initialized
    at BrowserWindow.<anonymous> (/opt/Teleport Connect/resources/app.asar/build/app/main/index.js:21565:9)
    at Object.onceWrapper (node:events:633:26)
    at BrowserWindow.emit (node:events:530:35)
Segmentation fault (core dumped)
```
          
```
$> teleport-connect --trace-warnings
Segmentation fault (core dumped)
```

- Debug logs
Using gdb with bt does not show any valuable information.
```
Thread 1 "teleport-connec" received signal SIGSEGV, Segmentation fault.
0x000060a3b7ca34c8 in ?? ()
(gdb) bt
#0  0x000060a3b7ca34c8 in ??? ()
#1  0x000016d00015dc00 in ??? ()
...
```

**Comment by rmntrvn** [comment]
Some isssue in kubuntu 24.04, teleport version 16.01

**Comment by ravicious** [comment]
Thanks for a detail bug report! We're waiting to learn how VSCode addressed this issue. https://github.com/electron/electron/issues/41066#issuecomment-2185907037

In the meantime, I wonder how correct that profile shared on the Unity forum is. In the original Ubuntu blogpost, [they show this example profile](https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890#unprivileged-user-namespace-restrictions-15):

```
abi <abi/4.0>,

include <tunables/global>

/opt/google/chrome/chrome flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/chrome>
}
```

Notice how it just starts with the path to the executable, not with `profile chrome <path>`.

[In the docs for apparmor profiles](https://documentation.suse.com/pt-br/sles/15-SP3/html/SLES-all/cha-apparmor-profiles.html#sec-apparmor-profiles-types-unattached), it states that the `profile …` syntax is for unattached profiles:

> Unattached profiles do not reside in the file system namespace and therefore are not automatically attached to an application. The name of an unattached profile is preceded by the keyword profile. (…)
> 
> Unattached profiles are never used automatically, nor can they be transitioned to through a Px rule. They need to be attached to a program by either using a named profile transition (see [Section 34.12.7, “Named profile transitions”](https://documentation.suse.com/pt-br/sles/15-SP3/html/SLES-all/cha-apparmor-profiles.html#sec-apparmor-profiles-exec-named)) or with the change_profile rule (see [Section 34.2.5, “Change rules”](https://documentation.suse.com/pt-br/sles/15-SP3/html/SLES-all/cha-apparmor-profiles.html#sec-apparmor-profiles-types-change)).

Does it help if you change Connect's profile to the following one?

```
abi <abi/4.0>,
include <tunables/global>

/opt/Teleport\ Connect/teleport-connect flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/teleport-connect>
}
```

**Comment by GuillaumeCisco** [comment]
Hello, thank you for your message.
I tried with an unattached profile and unfortunately, I still have pretty ofently "Segmentation fault (core dumped)" :/

**Comment by ravicious** [comment]
The fix for the AppArmor issue will go out in 16.0.4, 15.4.7, and 14.3.22.

**Comment by GuillaumeCisco** [comment]
I no more have issue with 16.0.3
and 
Create file /etc/apparmor.d/teleport-connect with content:
```
abi <abi/4.0>,
include <tunables/global>

profile teleport-connect /opt/Teleport\ Connect/teleport-connect flags=(unconfined) {
userns,

# Site-specific additions and overrides. See local/README for details.
include if exists <local/teleport-connect>
}
```

:tada:

**Comment by ravicious** [comment]
Cool, thanks for letting us know!
