### ISSUE TITLE
[Documentation/Event handler plugin] Clarification on the teleport.address attribute of the Helm chart

### ISSUE THREAD

**Issue by elevesque-sfr** [gravitational/teleport#43181]
## Applies To

https://goteleport.com/docs/management/export-audit-events/fluentd/#step-66-run-the-event-handler-plugin
https://github.com/gravitational/teleport/blob/master/examples/chart/event-handler/README.md

## Details

In the Teleport documentation, for the installation of the evnt handler plugin, at step 6/6, it says :

`address: Include the hostname and HTTPS port of your Teleport Proxy Service or Teleport Enterprise Cloud tenant (e.g., teleport.example.com:443 or mytenant.teleport.sh:443).`

In the README.md file in the repo github, it says :
`teleport.address : Host/port combination of the teleport auth server`

## How will we know this is resolved?

What is the correct value of the attribute ? The proxy service or the auth service ?

Regards,
Eric

**Comment by ptgott** [comment]
Related to #39886: we need to reconcile the event-handler README with the docs!
