### ISSUE TITLE
logname doesn't work for root user in combination with su

### ISSUE THREAD

**Issue by pprkut** [gravitational/teleport#4321]
### Description
If you login with teleport as a normal user and then switch to the root user using `su -`, neither `who am i` nor `logname` work, with the latter reporting 

```
logname: no login name
```

Neither works with a normal `su` either, but there $LOGNAME is set correctly since it's inherited from the original user.

**What you expected to happen**:
This works just fine with openssh, so I would expect it to work similarly fine in teleport. Without this I'm not sure how you'd be ale to determine the originally logged in user.

**How to reproduce it (as minimally and precisely as possible)**:
tsh ssh user@host
su -
logname // who am i

### Environment
- Teleport version (use `teleport version`):

Teleport Enterprise v4.3.5git:v4.3.5-0-g122349e78 go1.13.2

- Tsh version (use `tsh version`):

Teleport v4.3.5 git:v4.3.5-0-g122349e78 go1.13.2

- OS (e.g. from `/etc/os-release`):

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

AWS

- Browser Version (for UI-related issues):

Firefox 78.1.0esr

**Comment by webvictim** [comment]
`whoami` works fine as a workaround.

`who am i` is technically just `who`, which reads from utmp and thus doesn’t work with Teleport (see #3987). I would imagine `logname` is doing the same thing.

**Comment by pprkut** [comment]
> `whoami` works fine as a workaround.

Well, no. If I do `whoami` after `su` or `su -` it just tells me I'm `root`, which isn't really the point. I need to get to the username of the user who ran `su` or `su -`.

But anyway, the linked issue looks indeed like the underlying issue/feature, so I think this one can be closed.

**Comment by webvictim** [comment]
My apologies - I didn't realise what `logname` actually did. I agree that it doesn't work - https://www.gnu.org/software/coreutils/manual/html_node/logname-invocation.html#logname-invocation does show that it relies on utmp/wtmp, so the linked issue (https://github.com/gravitational/teleport/issues/3987) is indeed correct.

I'll close this one in favour of that. Thank you for reporting.
