### ISSUE TITLE
MySQL Galera: unsupported certificate purpose

### ISSUE THREAD

**Issue by arteonprifti** [gravitational/teleport#43235]
Trying to expose a MySQL Galera cluster using teleport CA fails, because the replicas cannot connect to the primary anymore after updating the certs with the one generated from teleport.

The error thrown is: [Galera] Handshake failed: certificate verify failed: unsupported certificate purpose

And checking the certificate purpose shows that in comparison to a working certificate, the one generated from teleport is missing the `SSL client: yes` purpose.

The change seems to have been introduced in the v14, because it worked on v13.

Bug details:
- Teleport version: v14.3.20
- Recreation steps
```
tctl auth sign \
  --format=db \
  --host=myhost \
  --out=server \
  --ttl=30h
  
❯ openssl x509 -in server.crt -noout -purpose
Certificate purposes:
SSL client : No
SSL client CA : No
SSL server : Yes
SSL server CA : No
```

**Comment by greedy52** [comment]
Hi @arteonprifti!

This behaviour is intended. The purpose of `server.crt` is "server" not "client", to avoid using `server.crt` as a client to authenticate a database. 

For MySQL cluster setup, it is recommended to use your own self-signed TLS certificates within your cluster. Then setup mTLS trust between your server CA and Teleport's client CA.

More details, please see the sections on "use custom CA" on the MySQL guide:
https://goteleport.com/docs/database-access/enroll-self-hosted-databases/mysql-self-hosted/

**Comment by arteonprifti** [comment]
Hello, 

thank you for your answer.
I see your point here, but this makes the configuration imo unnecessarily more complicated, because now you would need to exchange the CAs.
Anyway, will try that way.
