### ISSUE TITLE
Add /readyz handle on the proxy web endpoint

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#4329]
### Feature Request

Right now we recommend `/webapi/ping` as a healthcheck endpoint. This endpoint does a lot more work than is needed for health status.
Expose the `/readyz` handler used in the diagnostics server on the web server and update the docs accordingly.

### Motivation

`/webapi/ping` is too slow for frequent pings.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by strideynet** [comment]
We now offer `/healthz` and `/readyz` on the `--diag-addr` specific listener. This is used as the ready/health check in our official Helm chart for the Proxy pod.
