### ISSUE TITLE
Trusted Cluster Delete Issue

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#4335]
## Summary

Deletion of a "remote cluster" on the root cluster is accomplished via `tctl rm rc/<cluster name>`. 

https://gravitational.com/teleport/docs/admin-guide/

![capture-2020-09-16-10:07:07](https://user-images.githubusercontent.com/241714/93356495-d7111500-f804-11ea-8fb1-57bd0abc9ee2.png)

### Audience
Everyone

### Location
Existing

**Comment by webvictim** [comment]
https://gravitational.com/teleport/docs/admin-guide/#disabling-trust

**Comment by ptgott** [comment]
Looks like this is covered [here](https://goteleport.com/docs/setup/admin/trustedclusters/). @benarent okay to close?

**Comment by ptgott** [comment]
Closing since we cover this in the Trusted Cluster guide.
