### ISSUE TITLE
Terraform DynamoDB Autoscaling Target, Unnecessary Role

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#4338]
### Description
The Teleport Terraform example includes an AWS Application AutoScaling Scalable Target resource with a `role_arn` attribute that seem unnecessary. 

See attributes [here](https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/dynamo.tf#L198) and [here](https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/dynamo.tf#L172). 

According to Terraform and AWS docs, you should not provision a custom IAM role as there is a default service linked role applied at creation. 

See Terraform docs [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_target#role_arn), and AWS docs [here](https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-service-linked-roles.html). 

**What happened**:
With the current Teleport Terraform DynamoDB configuration and while running Terraform plan/apply, the output reflects a change for every subsequent run. Here are the changes:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_appautoscaling_target.read_target will be updated in-place
  ~ resource "aws_appautoscaling_target" "read_target" {
        id                 = "table/Delete-Me"
        max_capacity       = 100
        min_capacity       = 5
        resource_id        = "table/Delete-Me"
      ~ role_arn           = "arn:aws:iam::126027368216:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable" -> "arn:aws:iam::126027368216:role/Delete-Me-autoscaler"
        scalable_dimension = "dynamodb:table:ReadCapacityUnits"
        service_namespace  = "dynamodb"
    }

  # aws_appautoscaling_target.write_target will be updated in-place
  ~ resource "aws_appautoscaling_target" "write_target" {
        id                 = "table/Delete-Me"
        max_capacity       = 100
        min_capacity       = 5
        resource_id        = "table/Delete-Me"
      ~ role_arn           = "arn:aws:iam::126027368216:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable" -> "arn:aws:iam::126027368216:role/Delete-Me-autoscaler"
        scalable_dimension = "dynamodb:table:WriteCapacityUnits"
        service_namespace  = "dynamodb"
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

**What you expected to happen**:
The AWS AutoScaling Target `role_arn` attribute should not show a change in the Terraform Plan or Apply commands. 

**How to reproduce it (as minimally and precisely as possible)**:
Set values in Makefile, run make apply. Once complete, run make apply again and observe the output. 

### Environment
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

### Solution
We should remove the creation of the [custom IAM role](https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/dynamo.tf#L102-L120) and delete the `role_arn` attributes within the two AutoScaling targets [here](https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/dynamo.tf#L198) and [here](https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/dynamo.tf#L172). 

Doing so will result in a clean Terraform Plan and Terraform Apply.

**Comment by webvictim** [comment]
The autoscaler role is used by other parts of the Terraform so I left it in, but I removed the ARN assignment for the read/write targets. Now `terraform plan` doesn't generate superfluous changes.
