### ISSUE TITLE
Add Makefile target for creating a Github release

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#43393]
Our release process is largely automated with the following Makefile commands driving it:

- [make update-version](https://github.com/gravitational/teleport/blob/5e25f0192e0d77148dfb66eb8bd4025ecf11f209/Makefile#L1209): updates release version in various scripts/files
- [make update-tag](https://github.com/gravitational/teleport/blob/5e25f0192e0d77148dfb66eb8bd4025ecf11f209/Makefile#L1237): tags the commit and pushes tags to Github
- [make tag-build](https://github.com/gravitational/teleport/blob/5e25f0192e0d77148dfb66eb8bd4025ecf11f209/Makefile#L1271): kicks off GHA workflow for building release assets
- [make tag-publish](https://github.com/gravitational/teleport/blob/5e25f0192e0d77148dfb66eb8bd4025ecf11f209/Makefile#L1291): kicks off GHA workflow for promoting built assets to production repositories

The part with creating a [Github release](https://github.com/gravitational/teleport/releases) is still manual though.

Let's create another Makefile target, say `make create-github-release` that uses Github CLI tool to create a Github release. It should populate the release description appropriately, with the release's changelog extracted from `CHANGELOG.md` file and corresponding "Download" and "Teleport Plugins" sections. Maybe have a template with the release description which we can easily modify if needed.

When creating a release, keep in mind that only the release from the latest "release branch" (e.g. `branch/v16` at this moment) should be set as "latest".

**Comment by fheinecke** [comment]
Example download links for plugins can be found here: https://github.com/gravitational/teleport-plugins/releases/tag/v15.3.1. Note that all the files names include the release version.

Currently, the domain used for these URLs is `get.gravitational.com`. However, sometime next week this will switch to `cdn.teleport.dev`. For example, `https://get.gravitational.com/teleport-access-slack-v15.3.1-linux-amd64-bin.tar.gz` will change to `https://cdn.teleport.dev/teleport-access-slack-v15.3.1-linux-amd64-bin.tar.gz`.
