### ISSUE TITLE
Consistently apply `teleport.dev/*` tags to all Teleport-managed/created AWS resources

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#43427]
## What would you like Teleport to do?

When using the Teleport Discover flow for databases (which installs an ECS container running the `db_service`), there's a set of `teleport.dev/` tags added to this resource which makes it easier to find in future:

https://github.com/gravitational/teleport/blob/ff6997f2bf345d2fcd150105e1021dc03f2b511f/lib/integrations/awsoidc/deploydatabaseservice.go#L169-L182

There's also a similar set of tags applied for EC2 Instance Connect endpoints:

https://github.com/gravitational/teleport/blob/ff6997f2bf345d2fcd150105e1021dc03f2b511f/lib/integrations/awsoidc/create_ec2ice.go#L41-L47

The actual OIDC integration inside AWS doesn't have similar tags applied though, which makes it harder to find:

![Screenshot 2024-06-24 at 15 38 04](https://github.com/gravitational/teleport/assets/897821/25dd1517-ecb8-415d-9c0b-b11c5ff4088b)

Other things that aren't tagged with the `teleport.dev` tags (but should be) include:
- S3 bucket created for OIDC provider public key
- S3 bucket created for external audit storage
- Athena glue DB created for external audit storage
- Athena workgroup created for external audit storage

## What problem does this solve?

Discoverability/grouping/clean-up of resources.

## If a workaround exists, please include it.

Tag the resources yourself - but this is impractical because it's not obvious what they are or where they are in some cases.

**Comment by marcoandredinis** [comment]
Tags should be added for the IAM Identity Provider resource
https://github.com/gravitational/teleport/blob/bdb5d1a2a19573ee60ec60e0137c3a520d327ee3/lib/integrations/awsoidc/idp_iam_config.go#L392

S3 bucket and objects will not be used anymore as per https://github.com/gravitational/teleport/issues/44053

I'll see if we can add the tags for the External Audit Storage resources

**Comment by taraspos** [comment]
I think DynamoDB tables are missing tags as well.

**Comment by GavinFrazar** [comment]
We should add tags to the EKS access entry we create
https://github.com/gravitational/teleport/blob/0dce6fff4694bccfbed2c02c0c4513dee22ee71c/lib/integrations/awsoidc/eks_enroll_clusters.go#L411-L414

If so, then I think that will also require adding `eks:TagResource` to `StatementForEKSAccess()`
(see: https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonelastickubernetesservice.html)

We should also add tags to the SSM document creation here:
https://github.com/gravitational/teleport/blob/0dce6fff4694bccfbed2c02c0c4513dee22ee71c/lib/integrations/awsoidc/ec2_ssm_iam_config.go#L168-L173

**Comment by marcoandredinis** [comment]
All resources created using the Discover Flows are tagged.

**Comment by r0mant** [comment]
> All resources created using the Discover Flows are tagged.

@marcoandredinis Is there a documentation anywhere for this and is this outlined in any of the Discover flows? How do users know what to look for to find cloud resources created by Teleport?

**Comment by marcoandredinis** [comment]
> @marcoandredinis Is there a documentation anywhere for this and is this outlined in any of the Discover flows? How do users know what to look for to find cloud resources created by Teleport?

Created this PR to add docs about it:
https://github.com/gravitational/teleport/pull/46632
