### ISSUE TITLE
4.3.5 AMIs not in us-east-1, us-east-2 regions

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4350]
### Description

**What happened**:
The us-east-1 and us-east-2 don't have the enterprise 4.3.5 AMIs.  You then can't run the terraform example deploy script in those regions.

**What you expected to happen**:

Be able to deploy via terraform in us-east-1 and us-east-2 regions.

**How to reproduce it (as minimally and precisely as possible)**:
Start a terraform deploy process.
Set the ami to a 4.3.5 enterprise
`export TF_VAR_ami_name="gravitational-teleport-ami-ent-4.3.5"`
set the region to us-east-1
`export TF_VAR_region="us-east-1"`
Run make plan

```bash
Error: Your query returned no results. Please change your search criteria and try again.

  on data.tf line 4, in data "aws_ami" "base":
   4: data "aws_ami" "base" {


make: *** [Makefile:51: plan] Error 1
```

**Comment by webvictim** [comment]
Thanks for pointing this out. I've made those two AMIs public now. Not sure what happened, but I'll try and make the process a bit more resilient for the future.
