### ISSUE TITLE
Machine ID: Simplify `tbot` installation UX by performing ACL and FS modifications at runtime

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#43554]
Today, we provide the `tbot init` command to initialise directories and files with ACLs and Linux FS permissions. In particular, it sports functionality which allows granting a "reader user" read-only access to the artifacts. This is ideal in most installations where it's desired for `tbot` to run as one Linux user, and for another service that consumes the credentials to run as a different Linux user.

Today, the `tbot init` command must be run before `tbot start` is first run, and after any changes to the configuration that use specify directory destinations. It's another step in the flow - and is easily forgotten. In addition, this command must be run for each destination.

Removing this step, and instead performing this automatically at runtime, would yield a few benefits:

- One less command to run during installation, and to be forgotten about after making configuration changes. This has become particularly complex as we've supported more destinations - and some of these are not supported by `tbot init`. It's not clear when this command is actually necessary.
- `tbot` has the ability to "correct" permissions that have drifted at runtime.
- Running `tbot init` as a separate command assumes that we know about all artifacts that will be produced prior to runtime. This limits our ability to determine which artifacts should be created at runtime. For example, we may want to produce an artifact for each Kubernetes cluster that matches certain rules.
- Ability to configure the desired ACLs/Permissions as part of the main tbot configuration file.

The primary negative is that it would require the user that `tbot` runs as to already have ownership permissions on the specified directory, or the permissions necessary to create a directory within the parent directory. It feels like this is not an unreasonable ask. Most administrators installing services on Linux will be familiar with the need to change directory ownership to allow the user a service runs as to modify it. In fact, as the main data directory of `tbot` is not configured by `tbot init`, we already expect administrators to understand this today.

As part of this, we'll suggest the use of a new filesystem hierarchy for Machine ID to simplify initial setup:
- `/var/machine-id` should be created and chown'd to the user `tbot` will run as. This directory name should be adjusted if you have multiple instances of `tbot` running.
- `/var/machine-id/data` will be automatically created by `tbot` and will contain the internal data for `tbot`.
- `/var/machine-id/...` other subdirectories will be specified by the user for each of their outputs, as `tbot` owns the root directory, it can create these directories and configure ACLs and perms as necessary to allow other users to read these directories.

**Comment by strideynet** [comment]
Additionally, revisit https://github.com/gravitational/teleport/issues/20309 - I've opened a simple patch for now which makes this fail less hard but when we complete this work, we should switch to UIDs rather than full users to work around `/etc/passwd` unavailability.

**Comment by timothyb89** [comment]
> we should switch to UIDs rather than full users to work around `/etc/passwd` unavailability

Since I think users are most likely to want to keep interacting with named users when possible, I imagine we'll want to support both on some level. I figure we can treat any numeric value as a uid/gid, and for named values, attempt to resolve their UID/GID. The underlying system only encodes UIDs/GIDs and the library only operates on them anyway. I don't think it'll be a big lift to support both.

I'm leaning toward a syntax like this:

```yaml
version: v2
onboarding:
  join_method: token
storage:
  type: directory
  path: /var/lib/teleport/bot
  symlinks: try-secure
  acls: try
services:
  - type: identity
    destination:
      type: directory
      path: ./foo
      symlinks: try-secure
      acls: try
      readers:
        - user: foo
        - user: 123
        - group: bar
        - group: 456
```

Unfortunately we have some overloaded heritage from the old `acls` field taking up our most obvious candidate name, so for now I've picked `readers` to indicate the new section.
