### ISSUE TITLE
Teleport 4.4 Test Plan 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4359]
## Manual Testing Plan

Below are the items that should be manually tested with each release of Teleport.
These tests should be run on both a fresh install of the version to be released
as well as an upgrade of the previous version of Teleport.

- [x] Adding nodes to a cluster - @Joerger 
  - [x] Adding Nodes via Valid Static Token
  - [x] Adding Nodes via Valid Short-lived Tokens
  - [x] Adding Nodes via Invalid Token Fails
  - [x] Revoking Node Invitation

- [x] Labels - @Joerger
  - [x] Static Labels
  - [x] Dynamic Labels

- [x] Trusted Clusters - @Joerger
  - [x] Adding Trusted Cluster Valid Static Token
  - [x] Adding Trusted Cluster Valid Short-lived Token
  - [x] Adding Trusted Cluster Invalid Token
  - [x] Removing Trusted Cluster

- [x] RBAC  - @Joerger 

  Make sure that invalid and valid attempts are reflected in audit log.

  - [x] Successfully connect to node with correct role
  - [x] Unsuccessfully connect to a node in a role restricting access by label
  - [x] Unsuccessfully connect to a node in a role restricting access by invalid SSH login
  - [x] Allow/deny role option: SSH agent forwarding
  - [x] Allow/deny role option: Port forwarding

- [x] Users  - @quinqu 
With every user combination, try to login and signup with invalid second factor, invalid password to see how the system reacts.

  - [x] Adding Users Password Only
  - [x] Adding Users OTP
  - [x] Adding Users U2F
  - [x] Login Password Only
  - [x] Login OTP
  - [x] Login U2F
  - [x] Login OIDC
  - [x] Login SAML
  - [x] Login GitHub
  - [x] Deleting Users

- [x] Backends - @Joerger
  - [x] Teleport runs with etcd
  - [x] Teleport runs with dynamodb
  - [x] Teleport runs with dir

- [x] Session Recording
  - [x] Session recording can be disabled
  - [x] Sessions can be recorded at the node
    - [x] Sessions in remote clusters are recorded in remote clusters
  - [x] Sessions can be recorded at the proxy
    - [x] Sessions on remote clusters are recorded in the local cluster
    - [x] Enable/disable host key checking.

- [x] Audit Log  - @Joerger 
  - [x] Failed login attempts are recorded
  - [x] Interactive sessions have the correct Server ID
    - [x] Server ID is the ID of the node in regular mode
    - [x] Server ID is randomly generated for proxy node
  - [x] Exec commands are recorded
  - [x] `scp` commands are recorded
  - [x] Subsystem results are recorded

- [ ] Interact with a cluster using `tsh` - @quinqu 

   These commands should ideally be tested for recording and non-recording modes as they are implemented in a different ways.

  - [x] tsh ssh \<regular-node\>
  - [x] tsh ssh \<node-remote-cluster\>
  - [x] tsh ssh -A \<regular-node\>
  - [x] tsh ssh -A \<node-remote-cluster\>
  - [x] tsh ssh \<regular-node\> ls
  - [x] tsh ssh \<node-remote-cluster\> ls
  - [x] tsh join \<regular-node\>
  - [x] tsh join \<node-remote-cluster\>
  - [x] tsh play \<regular-node\>
  - [x] tsh play \<node-remote-cluster\>
  - [x] tsh scp \<regular-node\>
  - [x] tsh scp \<node-remote-cluster\>
  - [x] tsh ssh -L \<regular-node\>
  - [x] tsh ssh -L \<node-remote-cluster\>
  - [x] tsh ls
  - [x] tsh clusters

- [x] Interact with a cluster using `ssh` - @Joerger 
   Make sure to test both recording and regular proxy modes.
  - [x] ssh \<regular-node\>
  - [x] ssh \<node-remote-cluster\>
  - [x] ssh -A \<regular-node\>
  - [x] ssh -A \<node-remote-cluster\>
  - [x] ssh \<regular-node\> ls
  - [x] ssh \<node-remote-cluster\> ls
  - [x] scp \<regular-node\>
  - [x] scp \<node-remote-cluster\>
  - [x] ssh -L \<regular-node\>
  - [x] ssh -L \<node-remote-cluster\>

- [ ] Interact with a cluster using the Web UI
  - [x] Connect to a Teleport node
  - [ ] Connect to a OpenSSH node
  - [ ] Check agent forwarding is correct based on role and proxy mode.

### Combinations - @webvictim 

For some manual testing, many combinations need to be tested. For example, for
interactive sessions the 12 combinations are below.

- [x] Connect to a OpenSSH node in a local cluster using OpenSSH.
- [x] Connect to a OpenSSH node in a local cluster using Teleport.
- [x] Connect to a OpenSSH node in a local cluster using the Web UI.
- [x] Connect to a Teleport node in a local cluster using OpenSSH.
- [x] Connect to a Teleport node in a local cluster using Teleport.
- [x] Connect to a Teleport node in a local cluster using the Web UI.
- [x] Connect to a OpenSSH node in a remote cluster using OpenSSH.
- [x] Connect to a OpenSSH node in a remote cluster using Teleport.
- [x] Connect to a OpenSSH node in a remote cluster using the Web UI.
- [x] Connect to a Teleport node in a remote cluster using OpenSSH.
- [x] Connect to a Teleport node in a remote cluster using Teleport.
- [x] Connect to a Teleport node in a remote cluster using the Web UI.

### Teleport with EKS/GKE

* [ ] Deploy Teleport on a single EKS cluster
* [ ] Deploy Teleport on two EKS clusters and connect them via trusted cluster feature
* [ ] Deploy Teleport Proxy outside of GKE cluster fronting connections to it (this feature is not yet supported for EKS)

### Teleport with FIPS mode

* [x] Perform trusted clusters, Web and SSH sanity check with all teleport components deployed in FIPS mode.

### Migrations

* [x] Migrate trusted clusters from 4.3.0 to 4.4.0
  * [x] Migrate auth server on main cluster, then rest of the servers on main cluster
        SSH should work for both main and old clusters
  * [ ] Migrate auth server on remote cluster, then rest of the remote cluster
       SSH should work

### Command Templates

When interacting with a cluster, the following command templates are useful:

#### OpenSSH

```
# when connecting to the recording proxy, `-o 'ForwardAgent yes'` is required.
ssh -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p" \
  node.example.com

# the above command only forwards the agent to the proxy, to forward the agent
# to the target node, `-o 'ForwardAgent yes'` needs to be passed twice.
ssh -o "ForwardAgent yes" \
  -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p" \
  node.example.com

# when connecting to a remote cluster using OpenSSH, the subsystem request is
# updated with the name of the remote cluster.
ssh -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p@foo.com" \
  node.foo.com
```

#### Teleport

```
# when connecting to a OpenSSH node, remember `-p 22` needs to be passed.
tsh --proxy=proxy.example.com --user=<username> --insecure ssh -p 22 node.example.com

# an agent can be forwarded to the target node with `-A`
tsh --proxy=proxy.example.com --user=<username> --insecure ssh -A -p 22 node.example.com

# the --cluster flag is used to connect to a node in a remote cluster.
tsh --proxy=proxy.example.com --user=<username> --insecure ssh --cluster=foo.com -p 22 node.foo.com
```

### Teleport with SSO Providers

- [x] G Suite install instructions work
    - [x] G Suite Screenshots are up to date
- [ ] ActiveDirectoy install instructions work
    - [ ] Active Directoy Screenshots are up to date
- [x] Okta install instructions work
    - [x] Okta Screenshots are up to date
- [x] OneLogin install instructions work
    - [x] OneLogin Screenshots are up to date
- [x] OIDC install instructions work
    - [x] OIDC Screenshots are up to date

### Teleport Plugins

- [x] Test receiving a message via Teleport Slackbot
- [ ] Test receiving a new Jira Ticket via Teleport Jira

#### Top Nav
- [x] Verify that user name is displayed.
- [x] Verify that user menu shows a logout button.

#### Cluster List
- [x] Verify that root cluster is displayed with the proper label.
- [X] SKIPPED Verify that "Name", "Version", "Nodes" and "Public URL" shows the correct information. ( Note: This was removed in 4.4 ) 
- [x] Verify that column sorting works.
- [x] Verify that cluster "View" button works as a hyperlink by opening a new browser tab.
- [x] Verify that search works.

#### Top Nav
- [x] Verify that user name is displayed.
- [x] Verify that Breadcrumb Navigation has a link to dashboard.
- [x] Verify that cluster name is displayed.
- [x] Verify that clicking on Teleport logo navigates to the Dashboard.

#### Side Nav
- [x] Verify that "Nodes" item is highlighted.
- [x] Verify that each item has an icon.

#### Nodes
- [x] Verify that "Nodes" table shows all joined nodes.
- [x] Verify that "Connect" button shows a list of available logins.
- [x] Verify that "Hostname", "Address" and "Labels" columns show the current values.
- [x] Verify that "Search" works.
- [ ] Verify that terminal opens when clicking on one of the available logins.

#### Active Sessions
- [x] Verify that "empty" state is handled.
- [ ] Verify that it displays the session when session is active.
- [x] Verify that "Description", "Session ID", "Users", "Nodes" and "Duration" columns show correct values.
- [x] Verify that "OPTIONS" button allows to join a session.

#### Audit log
- [x] Verify that Audit log show sessions and audit log. 
- [x] Verify that time range button is shown and works.

#### Audit log (Sessions)
- [x] Verify that Sessions table shows the correct session values.
- [x] Verify that Play button opens a session player.
- [x] Verify that search works (it should do a search on all table cells).

#### Auth Connectors.
- [x] Verify that creating OIDC/SAML/GITHUB connectors works.
- [x] Verify that editing  OIDC/SAML/GITHUB connectors works.
- [x] Verify that error is shown when saving an invalid YAML.
- [x] Verify that correct hint text is shown on the right side.

  Card Icons
  - [x] Verify that GITHUB card has github icon
  - [x] Verify that SAML card has SAML icon
  - [x] Verify that OIDC card has OIDC icon

#### Roles
- [x] Verify that roles are shown.
- [x] Verify that "Create New Role" dialog works.
- [x] Verify that deleting and editing works.
- [x] Verify that error is shown when saving an invalid YAML.
- [x] Verify that correct hint text is shown on the right side.

#### Trusted Clusters
- [x] Verify that adding/removing a trusted cluster works.
- [x] Verify that correct hint text is shown on the right side.

#### Help & Support
- [x] Verify that all URLs work and correct (no 404)

### Account
- [x] Verify that Account screen is accessibly from the user menu for local users.
- [x] Verify that changing a local password works (OTP, U2F)

### Terminal
- [x] Verify that top nav has a user menu (Dashboard and Logout).
- [x] Verify that switching between tabs works on alt+[1...9].

#### Node List Tab
- [ ] Verify that Cluster selector works (URL should change too)
- [x] Verify that Quick access input works. It
- [x] Verify that Quick access input handles input errors.
- [x] Verify that "Connect" button shows a list of available logins.
- [x] Verify that "Hostname", "Address" and "Labels" columns show the current values.
- [x] Verify that "Search" works.
- [x] Verify that new tab is created when starting a session.

#### Session Tab
- [x] Verify that session and browser tabs both show the title with login and node name.
- [x] Verify that terminal resize works (use midnight commander (sudo apt-get install mc))
- [x] Verify that session tab shows a list of participants when a new user joins the session.
- [x] Verify that tab automatically closes on "$ exit" command.
- [x] Verify that SCP Upload works.
- [x] Verify that SCP Upload handles invalid paths and network errors.
- [x] Verify that SCP Download works.
- [x] Verify that SCP Download handles invalid paths and network errors.

### Session Player
- [x] Verify that it can replay a session.
- [x] Verify that scrolling behavior.
- [ ] Verify that error message is displayed (use invalid SID)

### Invite Form
- [x] Verify that input validation.
- [x] Verify that invite works with 2FA disabled.
- [x] Verify that invite works with OTP enabled.
- [x] Verify that invite works with U2F enabled.
- [x] Verify that error message is shown if an invite is expired/invalid.

### Login Form
- [x] Verify that input validation.
- [x] Verify that login works with 2FA disabled.
- [x] Verify that login works with OTP enabled.
- [x] Verify that login works with U2F enabled.
- [x] Verify that login works for Github/SAML/OIDC.
- [x] Verify that account is locked after several unsuccessful attempts.
- [x] Verify that redirect to original URL works after successful login.

### RBAC
 Create the following role ( note role is valid ) 
```
  spec:
  allow:
    logins:
    - root
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
  deny:
    logins: null
  options:
    cert_format: standard
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
```
  - [x] Verify that a user has access only to: "Cluster List", "Nodes", and "Active Sessions".
  - [x] Verify that a user is redirected to the login page.
  - [x] Verify that after successful login, a user is redirected to the Node List.

Add the following resource to enable read access to the audit log
```
  rules:
  - resources:
      - event
      verbs:
      - list
```
- [x] Verify that the audit log is accessible via UI.
- [x] Verify that access to recorded sessions is denied (by opening a session player).

Add the following resource to enable read access to recorded sessions
```
  rules:
  - resources:
      - session
      verbs:
      - read
```
- [x] Verify that a user can re-play a session (session.end).

Add the following resource to enable read access to the roles

```
- resources:
      - role
      verbs:
      - list
      - read
```
- [x] Verify that a user can see the roles
- [x] Verify that a user cannot create/delete/update a role

Add the following resource to enable read access to the auth connectors

```
- resources:
      - auth_connector
      verbs:
      - list
      - read
```
- [x] Verify that a user can see the list of auth connectors.
- [x] Verify that a user cannot create/delete/update the connectors.

Add the following resource to enable read access to trusted clusters
``` 
deny:
    logins: null
    rules:
  - resources:
      - trusted_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
```
- [x] Verify that a user can see the list of trusted clusters.
- [x] Verify that a user cannot create/delete/update a trusted cluster.

## Other Teleport Features
 - [x] Tested PAM integration
 - [x] Tested enhanced session recording. 

## Performance/Soak Test

Using `tsh bench` tool, perform the soak tests and benchmark tests on the following configurations:

* Cluster with 10K nodes in normal (non-IOT) node mode with ETCD
* Cluster with 10K nodes in normal (non-IOT) mode with DynamoDB

* Cluster with 1K IOT nodes with ETCD
* Cluster with 1K IOT nodes with DynamoDB

* Cluster with 500 trusted clusters with ETCD
* Cluster with 500 trusted clusters with DynamoDB

**Soak Tests**

Run 4hour soak test with a mix of interactive/non-interactive sessions:

```
tsh bench --duration=4h --threads=10 user@teleport-monster-6757d7b487-x226b ls
tsh bench -i --duration=4h --threads=10 user@teleport-monster-6757d7b487-x226b ps uax
```

Observe prometheus metrics for goroutines, open files, RAM, CPU, Timers and make sure there are no leaks

- [ ] Verify that prometheus metrics are accurate.

**Breaking load tests**

Load system with tsh bench to the capacity and publish maximum numbers of concurrent sessions with interactive
and non interactive tsh bench loads.

### AWS

- [x] Deploy Teleport to AWS. Using DynamoDB & S3
- [x] Deploy Teleport Enterprise to AWS. Using HA Setup https://gravitational.com/teleport/docs/aws-terraform-guide/

### GCP

- [x] Deploy Teleport to GCP. Using Cloud Firestore & Cloud Storage
- [ ] Deploy Teleport to GKE. Google Kubernetes engine.
- [x] Deploy Teleport Enterprise to GCP.

### IBM

- [ ] Deploy Teleport to IBM Cloud. Using IBM Database for etcd & IBM Object Store
- [ ] Deploy Teleport to IBM Cloud Kubernetes.
- [x] Deploy Teleport Enterprise to IBM Cloud.

**Comment by klizhentas** [comment]
@awly @fspmarshall @russjones let's start attaching old vs new run profiles

Node: m4.2xlarge

```bash
tsh bench --duration=4h --threads=10 user@<node> ls
tsh bench -i --duration=4h --threads=10 user@<node> ps uax
```

Check out two runs side by side 4.3 vs 4.4:

[172.31.9.250.tar.gz](https://github.com/gravitational/teleport/files/5322349/172.31.9.250.tar.gz)

![4 3-vs-4 4](https://user-images.githubusercontent.com/13717/95002433-ce506b00-0588-11eb-8abb-d44f3bdb7066.png)

**Comment by klizhentas** [comment]
![4 4-soak](https://user-images.githubusercontent.com/13717/95005378-7deb0480-05ac-11eb-93f5-f2f51e8ee086.png)

4 hour soak test with mixed load results. Two previous 10 min runs captured for comparison.

**Comment by klizhentas** [comment]
## Sync node recording soak test

![4 4-soak-sync](https://user-images.githubusercontent.com/13717/95029238-a5e57100-065b-11eb-9b14-bdcfbdb723a7.png)


```
$ tsh bench --duration=4h --threads=10 root@ip-172-31-9-250-us-west-2-compute-internal ls

* Requests originated: 143980
* Requests failed: 0

Histogram

Percentile Duration
---------- --------
25         74 ms
50         86 ms
75         101 ms
90         126 ms
95         155 ms
99         282 ms
100        15519 ms
```

```
$ tsh bench --interactive --duration=4h --threads=10 root@ip-172-31-9-250-us-west-2-compute-internal ps uax

* Requests originated: 143986
* Requests failed: 0

Histogram

Percentile Duration
---------- --------
25         74 ms
50         86 ms
75         101 ms
90         127 ms
95         157 ms
99         282 ms
100        15415 ms
```

**Comment by klizhentas** [comment]
## Proxy recording soak test

![4 4-soak-proxy-async](https://user-images.githubusercontent.com/13717/95100995-8c3d3b80-06e6-11eb-9d9b-7b769ecbb953.png)


```bash
$ tsh bench --duration=4h --threads=10 root@ip-172-31-9-250-us-west-2-compute-internal ls

* Requests originated: 143942
* Requests failed: 0

Histogram

Percentile Duration
---------- --------
25         135 ms
50         282 ms
75         432 ms
90         589 ms
95         699 ms
99         955 ms
100        15679 ms

```

```
tsh bench --interactive --duration=4h --threads=10 root@ip-172-31-9-250-us-west-2-compute-internal ps uax
^Xd
* Requests originated: 143947
* Requests failed: 0

Histogram

Percentile Duration
---------- --------
25         170 ms
50         323 ms
75         459 ms
90         612 ms
95         722 ms
99         975 ms
100        8039 ms
```

**Comment by russjones** [comment]
@klizhentas I've assigned some blocks of the test plan to @Joerger and @quinqu. The parts they're working on have been marked in the original ticket.

**Comment by klizhentas** [comment]
## Teleport 10K iot idle

![10k-iot](https://user-images.githubusercontent.com/13717/95509363-4348e980-0969-11eb-8fb0-ab4fdfc8141e.png)

**Comment by klizhentas** [comment]
## 500 Trusted clusters

![500-tc](https://user-images.githubusercontent.com/13717/95632683-0f3df900-0a3b-11eb-8360-0e872917655c.png)

**Comment by klizhentas** [comment]
## 10K regular etcd

Lot's of traffic (1-2Mb/s between auth servers and etcd). Proxy traffic is good - 300Kb/sec per 10K nodes (compared to 8-10x of that in IOT mode).

![10k-regular-etcd](https://user-images.githubusercontent.com/13717/95663550-e8dc9400-0af4-11eb-884b-f007a2eea68f.png)

**Comment by klizhentas** [comment]
## Memory leak 10K

I've been scaling cluster up 5K nodes and down several times and observed this:

![10k-leak](https://user-images.githubusercontent.com/13717/95667982-4c30eb00-0b22-11eb-8dc2-80726138de88.png)

The profile is similar to what is described here:

https://github.com/grpc/grpc-go/issues/3728

It's not a goroutine leak, but HTTP servers never get closed for some reason.

**Comment by benarent** [comment]
Teleport 4.4 has been made GA.

Marking test plan as complete.
