### ISSUE TITLE
Tctl users add --format=json returns empty string

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4364]
### Description

**What happened**:

```bash
$tctl users add bob --roles=admin --format=json
# prints nothing
```

**What you expected to happen**:

```
$tctl users add bob --roles=admin --format=json
{"token": "hex", "ttl": "24h"}
```

**How to reproduce it (as minimally and precisely as possible)**:
see subject

### Environment
- Teleport version (use `teleport version`):
Teleport 4.4 server and client
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by Joerger** [comment]
It looks like the only thing that would cause it to be blank is if the format is mispelled, it has to be `json` all lowercase. I'll make it default to Text, and we could make it case insensitive too.
