### ISSUE TITLE
Broken reference to exec command in the event handler helm chart 

### ISSUE THREAD

**Issue by pudovd** [gravitational/teleport#43669]
**Expected behavior:**
Successfully started Event Handler plugin after executing the helm install command. 

**Current behavior:**
Back-off restarting failed container teleport-plugin-event-handler in pod teleport-plugin-event-handler-xxx

**Bug details:**
- Teleport version: `16.0.1`
- Recreation steps: 
```
helm repo add teleport https://charts.releases.teleport.dev
helm install teleport-plugin-event-handler teleport/teleport-plugin-event-handler --version 16.0.1 -f values.yaml
```
- Debug logs
```
# kubectl describe pod teleport-plugin-event-handler-xxx
...
  Normal   Pulling                 32s                kubelet                  Pulling image "public.ecr.aws/gravitational/teleport-plugin-event-handler:16.0.1"
  Normal   Pulled                  28s                kubelet                  Successfully pulled image "public.ecr.aws/gravitational/teleport-plugin-event-handler:16.0.1" in 3.966321778s (3.966331377s including waiting)
  Normal   Created                 13s (x3 over 28s)  kubelet                  Created container teleport-plugin-event-handler
  Warning  Failed                  13s (x3 over 28s)  kubelet                  Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/teleport-event-handler": stat /usr/local/bin/teleport-event-handler: no such file or directory: unknown
```

A root cause is the difference within the [Dockerfile](https://github.com/gravitational/teleport/blob/v16.0.1/integrations/event-handler/Dockerfile#L26) and the [deployment template](https://github.com/gravitational/teleport/blob/v16.0.1/examples/chart/event-handler/templates/deployment.yaml#L38).

**Comment by evanfreed** [comment]
I too am seeing this, updated [here](https://github.com/gravitational/teleport/commit/1118933acb2327b3abbf6abdbaec93566a762dc8#diff-dfa60c20c9c3b8bcd653e24ba3304d3869559db31b0e85115788f10931bfaf92)

**Comment by pudovd** [comment]
@fheinecke, can you fix this ticket?

**Comment by fheinecke** [comment]
This should be fixed on all supported branches. A fix for v15 will go out with the next v15 release.
