### ISSUE TITLE
Session recording cannot be exported

### ISSUE THREAD

**Issue by Venture200** [gravitational/teleport#43707]
Expected behavior:
Should be exported

Current behavior:
Cannot be exported

Bug details:
- Teleport version
Teleport v15.4.5 git: go1.21.11
Proxy version: 15.4.4

- Recreation steps
Login to cluster and run `tsh recordings export <session-id>`

- Debug logs
ERROR: this session can't be exported, please visit https://<redacted>:443/web/cluster/<<edacted>/session/<session-id>?recordingType=desktop&durationMs=207879 to view it

When I list the sessions I can see all the listed recordings, but exporting them fails 

 `tsh recordings export <session-id> -d` producted below 
 
 
```
Original Error: *trace.BadParameterError this session can&#39;t be exported, please visit https://<redacted>:443/web/cluster/<redacted>/session/session-id?recordingType=desktop&amp;durationMs=207879 to view it
Stack Trace:
        github.com/gravitational/teleport/tool/tsh/common/recording_export.go:134 github.com/gravitational/teleport/tool/tsh/common.writeMovie
        github.com/gravitational/teleport/tool/tsh/common/recording_export.go:66 github.com/gravitational/teleport/tool/tsh/common.onExportRecording
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:1438 github.com/gravitational/teleport/tool/tsh/common.Run
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:599 github.com/gravitational/teleport/tool/tsh/common.Main
        github.com/gravitational/teleport/tool/tsh/main.go:26 main.main
        runtime/proc.go:271 runtime.main
        runtime/asm_amd64.s:1695 runtime.goexit
User Message: this session can&#39;t be exported, please visit https://<redacted>:443/web/cluster/<redacted>/session/session-id?recordingType=desktop&amp;durationMs=207879 to view it
```

**Comment by stevenGravy** [comment]
Session recordings for desktops prior to version 15 are supported, not 15+. This is expected behavior.

**Comment by Venture200** [comment]
@stevenGravy the matter is about exporting session recordings. According to the doc : Teleport supports recording and playback of desktop sessions. https://goteleport.com/docs/ver/15.x/desktop-access/reference/sessions/

**Comment by stevenGravy** [comment]
Yes those docs will be updated. Desktop sessions recorded in v15+ agents are only playable via the Web UI, not exportable.
