### ISSUE TITLE
Provide the ability to use tctl using an IdP / 2nd factor 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4372]
### Feature Request
We will soon let customers interact with Teleports `tctl` auth tool using an exported identify file.  https://github.com/gravitational/teleport/pull/4318

We should add the same ability but using Teleports built  in user management.

```
remote$ tctl status \
                --auth-server=teleport.example.com:3080 \
                --auth=okta
```

We'll need to add more configs to Teleports RBAC to limit the access to the admin tool. 

### Motivation
This encourages short lived tokens and usability for accessing `tctl` 

### Who's it for?
OSS User, Pro, Enterprise

**Comment by zmb3** [comment]
@benarent I think we can close this now, as `tctl` will pick up the identity generated by `tsh login`, and `tsh` already supports the behavior you describe here.

Agree?

**Comment by benarent** [comment]
Yes, we can close this issue.
