### ISSUE TITLE
Provide Kubernetes proxy configuration option for terraform example

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4373]
### Feature Request
Provide a method of specifying k8s settings within the terraform example for the proxy.  Given the upcoming multi k8s cluster support it will likely require a file to configure instead of just variables.

### Motivation
Users of the terraform have to alter the proxy setting manually or create another AMI version to include k8s settings.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by webvictim** [comment]
Similar to https://github.com/gravitational/teleport/issues/4908
