### ISSUE TITLE
Teleport Discover prompts you to add first resource when you have already added it

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#43777]
The Web UI will occasionally prompt you to add your first resource even though you have already added the resources you want. Users should not see this prompt since they have already added the resources they want.

<img width="495" alt="image" src="https://github.com/gravitational/teleport/assets/5017502/fbd1996c-6ac6-4c47-acc0-54a809de254e">

**Comment by zmb3** [comment]
Looks like a duplicate of #39595

**Comment by russjones** [comment]
Okay, let's close this in favor of #39595.
