### ISSUE TITLE
Clarification Needed: AGPL-3.0 Compliance

### ISSUE THREAD

**Issue by komodin** [gravitational/teleport#43789]
Hi,

I've been reviewing the terms and conditions displayed when accessing the Teleport application, and I noticed a message that states:

```
Welcome to Teleport
Companies may use Teleport Community Edition on the condition they have less than 100 employees and less than $10MM in annual revenue. If your company exceeds these limits, please contact us to evaluate and use Teleport.

By clicking continue, you agree to our Terms and Conditions.
```

I noticed that this message was added in Teleport 16. I'm a bit confused about this message because I understand that the majority of the source code in this repository is licensed under the GNU Affero General Public License (AGPL-3.0), except for the Teleport API module which is under the Apache 2.0 license. As far as I know, the AGPL-3.0 license is quite strict about not allowing additional restrictions on the use of the software.

Could you please clarify if this usage restriction is compliant with the AGPL-3.0? My understanding is that the AGPL-3.0 does not permit imposing such conditions on users based on the size of the company or its revenue. I just want to make sure we are using and distributing the software correctly in accordance with the license terms.

Thanks for your help!

**Comment by strideynet** [comment]
@komodin - ah apologies for missing the core of your question there. I believe the best way to get an answer on that would be to send an email to opensource@goteleport.com since the team who monitors that will be better equipped to answer you.

**Comment by komodin** [comment]
@strideynet no worries! Perhaps I didn’t explain it clearly in my first message. I'll send an email there. Thank you so much for your response!

**Comment by komodin** [comment]
Hello @strideynet, I wrote to the email `opensource@goteleport.com` on July 3rd and wrote again on July 11th, but I haven't even received an acknowledgment of receipt. Do you have a way to ask internally about the matter? Thank you very much and have a great weekend!

**Comment by klizhentas** [comment]
Ezequiel,

Teleport code base is dual licensed. 

The code that you see in OSS is licensed to open source users under AGPL v3 and also licensed by two different licenses - modified Apache 2 and commercial MSA. 

The enterprise edition and binaries of teleport and a community edition and binaries of teleport leveraging are licensed under the commercial terms of MSA and modified Apache 2 with restrictions respectively.

Teleport does not distribute AGPL v3.0 binaries.

The restriction that you see applies to a compiled community edition with a modified Apache 2 license you can see included in the Community Edition binary, not the AGPL v3.0 source code.

Teleport does not distribute AGPL v3.0 binaries.
