### ISSUE TITLE
`TestKubeMiddleware/expired_certificate_is_still_reissued_if_request_context_expires` flakiness

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#43821]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/9783519373/job/27012313611?pr=43644

#### Relevant snippet

```
=== Failed
=== FAIL: lib/srv/alpnproxy TestKubeMiddleware/expired_certificate_is_still_reissued_if_request_context_expires (0.00s)
    local_proxy_test.go:540: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/alpnproxy/local_proxy_test.go:540
        	Error:      	Not equal: 
        	            	expected: 500
        	            	actual  : 200
        	Test:       	TestKubeMiddleware/expired_certificate_is_still_reissued_if_request_context_expires

=== FAIL: lib/srv/alpnproxy TestKubeMiddleware (2.60s)
```

**Comment by AntonAM** [comment]
Couldn't reproduce it locally as is (only with adding millisecond to context deadline), but this should fix it https://github.com/gravitational/teleport/pull/44044

**Comment by ravicious** [comment]
https://github.com/gravitational/teleport/actions/runs/10008626068/job/27666847483?pr=44452#step:6:1601

**Comment by zmb3** [comment]
https://github.com/gravitational/teleport/actions/runs/10146461171/job/28054553726
