### ISSUE TITLE
Show Kubernetes Session in Active Sessions UI

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4383]
### Feature Request
List K8s sessions in Active Sessions similar to SSH sessions.

### Motivation
While they could not join the session that would allow monitoring what sessions are currently active.  Administrators often want to know what sessions are active within a proxy. 

### Who's it for?
OSS User, Pro, Enterprise

**Comment by webvictim** [comment]
I suspect that the reason for this is because you can't join the session. I agree though - we should list the ongoing sessions just as we do for SSH.

**Comment by ToniRib** [comment]
Just bumping this and wondering if this is a feature that's going to get worked on anytime soon. Even if you can't join the k8s session, it would be nice to still be able to see what's going on live.

**Comment by alex-kovoy** [comment]
@kimlisa could you investigate if we can show the k8s active sessions?

**Comment by zmb3** [comment]
This was recently fixed for v10 and will be backported to v9 as well.
