### ISSUE TITLE
Empty Audit Log shows React error in Leaf Cluster

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4393]
### Description

**What happened**:

The audit log was empty in DynamoDB for a leaf cluster and when the user navigates to the audit log they get a `Cannot read property 'map' of null'.  

![image](https://user-images.githubusercontent.com/60704961/94571244-c36ea100-023d-11eb-9c4f-b2f2f1bb909c.png)

**What you expected to happen**:

No entries or a empty log message. 

**How to reproduce it (as minimally and precisely as possible)**:

Create a leaf cluster that uses DynamoDB as it storage.  Remove all entries in the events table. Through the root cluster navigate to the audit log in the leaf cluster.

### Environment
- Teleport version (use `teleport version`): 4.3.6 enterprise
- OS (e.g. from `/etc/os-release`): Ubuntu

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Browser environment**

- Browser Version (for UI-related issues): Chrome  85.0.4183.121

**Comment by russjones** [comment]
@alex-kovoy Any idea?

**Comment by alex-kovoy** [comment]
The error should be logged in the console with the traces, so it should be enough to copy&past it. This one is the client side issue which we already identified.
