### ISSUE TITLE
Release 1.0 of Teleport

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#440]
### Description

We have now completed a 3rd party pen test and security code audit. Lets remove all the warnings from the documentation and bake a first official 1.0

### TODO

- Update documentation
- Simplify builds (compatibility with `go build`, Github releases and "native" git ref instead of "linkflags" (using my birthday present)

**Comment by jaxxstorm** [comment]
If I can help with the documentation in anyway, I'd be happy to help!

**Comment by kontsevoy** [comment]
@jaxxstorm thanks, will ping you!

**Comment by kontsevoy** [comment]
@jaxxstorm we just merged "Trusted Clusters" into "master". You can see the staging documentation here: https://web.gravitational.io/teleport/docs/admin-guide/#trusted-clusters

Any suggestions?

**Comment by jaxxstorm** [comment]
@kontsevoy great docs, very clear and concise! will add this to the puppet module also.

**Comment by kontsevoy** [comment]
a-a-a-a-aaaaalmost there.....
