### ISSUE TITLE
Include Token Name in join_token.create Audit Events

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#44017]
What would you like Teleport to do?
Currently, Teleport does not include the token name in the audit event:
~~~
{
  "cluster_name": "schisa.teleport.sh",
  "code": "TJT00I",
  "ei": 0,
  "event": "join_token.create",
  "expires": "0001-01-01T00:00:00Z",
  "join_method": "token",
  "roles": [
    "Node"
  ],
  "time": "2024-07-10T15:56:41.27Z",
  "uid": "3559ceaa-afce-413a-9668-d794772e8342",
  "user": "paul@gravitational.com",
  "user_kind": 1
}
~~~

Request is to include the token name into the join_token.create event.

What problem does this solve?
This token_name is present in redacted form in the instance.join audit event
~~~
{
  "addr.remote": "10.19.106.23",
  "cluster_name": "schisa.teleport.sh",
  "code": "TJ002I",
  "ei": 0,
  "event": "instance.join",
  "host_id": "6e7ccf92-c68f-4cbb-866d-1341132e0afb",
  "method": "token",
  "node_name": "teleport-proxy-5bff695bbb-bnfkc",
  "role": "Proxy",
  "success": true,
  "time": "2024-07-08T18:54:19.947Z",
  "token_expires": "1970-01-01T00:00:00Z",
  "token_name": "************************************************b7b1b2db2051c184",
  "uid": "744e491d-f45a-4c5d-9ee4-8b2eea13b3df"
}
~~~

Having the same token name output available in the join_token.create event would allow admins to correlate which user created the join token being used to join instances.

**Comment by strideynet** [comment]
This seems pretty reasonable - I do think that generally, we ought to move away from our "token" join method to a v2 which splits the secret part from the name - which would remove the need to redact the name entirely.
