### ISSUE TITLE
Go API Examples

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#4403]
Add API examples on how to:

* Token management CRUD.
* Role CRUD.
* Cluster label CRUD.
* Receive Access Request.
* Allow/Deny Access Request.

**Comment by russjones** [comment]
See the following: https://github.com/gravitational/teleport/tree/master/examples/go-client

**Comment by benarent** [comment]
Note: This can start once https://github.com/gravitational/teleport/pull/4320 has been merged

**Comment by russjones** [comment]
@Joerger Let's add these to the docs instead of https://github.com/gravitational/teleport/tree/master/examples. You can work with @benarent to figure out where in the docs to place them.

**Comment by webvictim** [comment]
Can we do both somehow? That way people can clone the repo to check out the code easily rather than having to do a clumsy copy/paste from the docs.

**Comment by Joerger** [comment]
Yeah might as well, I'll need to run each code snippet anyways, shouldn't be hard to combine them into an example.

**Comment by benarent** [comment]
yes, we can embed them into docs. We already do this using 

```yaml
{!examples/resources/saml-connector.yaml!}
```
