### ISSUE TITLE
JSON logging format for /var/log/teleport.log

### ISSUE THREAD

**Issue by dnwe** [gravitational/teleport#4407]
### Feature Request

In addition to having timestamps in the teleport daemon log file (/var/log/teleport.log) (#2676) it would be useful if we could configure the log output to consist of structured json rather than the current plain format

### Motivation

In large scale multi-cluster deployments, where log files are typically pushed to a unified logging service, pushing them when they have already been output into a JSON format would simplify matters

### Who's it for?

Teleport Enterprise

**Comment by zmb3** [comment]
This is doable today by setting `teleport.log.format.output` in the configuration file.
