### ISSUE TITLE
tctl auth sign --format=kubernetes should always overwrite the destination file

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#4409]
### Description

**What happened**:

`tctl auth sign --format=kubernetes --out=./kubeconfig` fails when `./kubeconfig` exists and is not a valid kubeconfig.
When it is valid, `tctl auth sign` updates it (adds new credential/server entries)

**What you expected to happen**:

`tctl auth sign` should always overwrite the destination file.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ tctl auth sign --format=openssh --out=./cert.out
# success
$ tctl auth sign --format=kubernetes --out=./cert.out
error: failed to parse existing kubeconfig "./cert.out": couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

**Comment by stmuraka** [comment]
@awly seems to be fixed in at least version `4.3.7`
