### ISSUE TITLE
Provide Microsoft Teams Workflow Plugin for Approval Workflow

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4412]
### Feature Request
Provide a Msft Teams Approval Workflow Plugin

### Motivation
Microsoft Teams usage continues to grow and is gaining popularity with companies.  

### Who's it for?
Pro, Enterprise

**Comment by benarent** [comment]
@stevenGravy Is this for a specific customer? In that case do you know the R1, R2 , R3 size?

**Comment by Valien** [comment]
Starting to hear and see more requests for MS Teams support. Variety of opportunity sizes.

**Comment by stevenGravy** [comment]
Closing as this is tracked here https://github.com/gravitational/teleport-plugins/issues/61
