### ISSUE TITLE
Support Rocky Linux in node-join and agent/agentless installer scripts

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#44171]
## What would you like Teleport to do?

Support Rocky Linux (the "new CentOS") in Teleport installation scripts.

It's binary compatible with RHEL/CentOS, so checks like this can likely just have `rocky` added to the supported list:

- https://github.com/gravitational/teleport/blob/f06547a437fcdce389a75169b63998d2fe00d102/api/types/installers/agentless-installer.sh.tmpl#L149
- https://github.com/gravitational/teleport/blob/f06547a437fcdce389a75169b63998d2fe00d102/lib/web/scripts/node-join/install.sh#L926

## What problem does this solve?

Enables easier installs on distros which are technically supported.

## If a workaround exists, please include it.

Edit installer scripts yourself.

**Comment by zmb3** [comment]
@marcoandredinis is this good to close?

**Comment by marcoandredinis** [comment]
Yes, implemented in https://github.com/gravitational/teleport/pull/44283 and https://github.com/gravitational/teleport/pull/44319
