### ISSUE TITLE
Release notes on downloads page do not format markdown well

### ISSUE THREAD

**Issue by fheinecke** [gravitational/teleport#44239]
## Applies To

https://goteleport.com/download/ with "show release notes" expanded

## Details

The format of markdown code blocks (\`like this\`) in release notes looks strange, primarily due to the lack of kerning and font change without background or text color change. I would expect that these be rendered `like this`, or something similar to it. The current styling makes it difficult to tell where code blocks start and stop.

There is no header for the release notes, rather, they just start with the bullet points. This is fine for major version releases (such as 16.0.0), but looks somewhat strange for minor releases (i.e. 13.0.2). The 16.0.3 release, IMO, looks much better.

## How will we know this is resolved?

When code blocks are easy to identify and read, and release notes are easier to parse.

**Comment by ptgott** [comment]
We've added this to our issue tracking for the main Teleport site, which we maintain separately from this repo.
