### ISSUE TITLE
I can't use tsh scp "error receiving version packet from serve"

### ISSUE THREAD

**Issue by tnubeo1111** [gravitational/teleport#44266]
Expected behavior:

I use the following command: tsh scp ./test/note.txt thalt@hni--master-101.test.vn:/home/vcr/ssl, then I assume the note.txt file can be copied to the server: hni--master-101.test.vn

Current behavior:

But when I use the command tsh scp ./test/note.txt thalt@hni--master-101.test.vn:/home/vcr/ssl it gives error "ERROR: error receiving version package from server: machine Unexpected server closed connection: Unexpected EOF"

Bug details:
- Teleport version:  Teleport v16.0.4 git:v16.0.4-0-gc733a8b go1.22.5
                                    Proxy version: 14.3.20
- Recreation steps:  I used a login session that used **tsh ssh** and still managed to access the internal server. Next, I opened a new session to use the **tsh scp** command and got the error above
- Debug logs

**Comment by tnubeo1111** [comment]
Sorry, I have fixed it, maybe my server has some permissions blocked.

**Comment by beaudmitchell** [comment]
Noticed this happening when tsh on my machine was v15, but the Teleport server of my organization had upgraded to v16. Installing the latest version of tsh so client and server's main versions matched resolved this for me. Not certain if that was your issue as well, but throwing this out there in case someone else runs across the issue too.
