### ISSUE TITLE
ssh.node has exited with error session_recording must either be: node,proxy,off, aborting

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4429]
### Description

**What happened**:

While testing session_streaming, I tried to connect a node running `Teleport v4.3.5 git:v4.3.5-0-g122349e78 go1.13.2` and it wasn't able to connect to the cluster running with `session_recording: node_sync`. 

```log
[ec2-user@ip-172-31-14-24 ~]$ sudo /usr/local/bin/teleport start
ERRO [AUTH]      "Failed to register through auth server: 404 page not found\n; falling back to trying the proxy server" auth/register.go:126
ERRO [PROC:1]    Critical service ssh.node has exited with error session_recording must either be: node,proxy,off, aborting. service/signals.go:145
error: session_recording must either be: node,proxy,off
```

Do we want to fix this? Or just mark it as a known issue with session streaming?

**Comment by webvictim** [comment]
A 4.3.x client should be able to connect to a 4.4.x auth/proxy without any problem. I think we should fix this.

**Comment by webvictim** [comment]
`node_sync` is only supported in Teleport >=4.4 - all nodes must be updated to take advantage of it.

**Comment by webvictim** [comment]
(needs a mention in the release notes)
