### ISSUE TITLE
Working through the proxy and firewall

### ISSUE THREAD

**Issue by freeseacher** [gravitational/teleport#443]
Hi!

Wonderful idea, guys! 
But i don't understand if teleport can help me or not. i have such a scheme 

1. server with public ip. I can control it by myself in any case. lets name it remote
2. several servers behind the firewall and proxy. from them I have only access to internet to port http/https. lets call them cluster.
3. i have vpn from remote to cluster. 
4. i can make connections from remote to cluster to port 22/443. others are blocked. 
5. on remote side on port 443 i already have web site behind the nginx. so i can proxy requests to teleport

So my question is, can teleport help me get access from internet to cluster?

**Comment by kontsevoy** [comment]
@freeseacher your question/request is similar to #437. Teleport has (undocumented) "reverse tunnel" feature, which allows SSH nodes to create an outbound SSH tunnel to a Teleport proxy via any port, in your case it would have to be 443.

We are currently in the process of making reverse tunnels easier to use and documenting them. At the same time, we're marking Teleport as "production-ready". Look for a new release within a few days!

**Comment by freeseacher** [comment]
Today i try to use teleport again. and still no luck :(

As far as i can see teleport does't respect https_proxy env variable set so i cant add node to cluster. 
but i had reduced complexity of setup. 
Currentrly i can make connections from ssh node to any internet ip and port. but still only through http proxy.

**Comment by kontsevoy** [comment]
@freeseacher can we jump on Google hangout with you to examine your use case?

**Comment by freeseacher** [comment]
yep, sure!

**Comment by kontsevoy** [comment]
ping me on ev@gravitational.com plz!

**Comment by freeseacher** [comment]
bump.

**Comment by kontsevoy** [comment]
@freeseacher did you send me an email? Looking forward to chatting.

**Comment by freeseacher** [comment]
Some summary:
* i mean http_proxy like squid 
* and talking about https://en.wikipedia.org/wiki/HTTP_tunnel
* there are several variants to make some software that cant work through proxy do so. some variants: https://wiki.archlinux.org/index.php/HTTP_tunneling
* docker-compose file like that 
```
Squid:
  image: sameersbn/squid:3.3.8-14
  ports:
    - "3128:3128"
  volumes:
    - /data/squid/cache:/var/spool/squid3
  restart: always
```
will activate proxy server squid. that can be accessed with http_proxy=http://0.0.0.0:3128
it can be used for testing. 
Of cause i will try to help to debug and make that feature as much as possible

**Comment by kontsevoy** [comment]
@freeseacher makes sense, thanks

**Comment by kontsevoy** [comment]
@freeseacher see if this will help you:
https://github.com/nf/gohttptun

**Comment by kontsevoy** [comment]
Closing this: it's very unlikely that we'll support it (high cost, low demand).
