### ISSUE TITLE
Routing of proxied requests

### ISSUE THREAD

**Issue by metanovii** [gravitational/teleport#44325]
What would you like Teleport to do?

Hashicorp boundary has the ability to bind a target host to a specific worker (proxy node) node. This allows you to have a common system for different clouds. An example is shown in the screenshot.

![image](https://github.com/user-attachments/assets/9c3182dd-4026-4252-b69b-601b1512643c)

And link for doc https://developer.hashicorp.com/boundary/docs/concepts/filtering/worker-tags#example-worker-filter-for-targets

**Comment by webvictim** [comment]
Similar request to https://github.com/gravitational/teleport/issues/28541
