### ISSUE TITLE
Procedure for OpenSSH Cert Authority Rotation

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#44398]
## Applies To
https://goteleport.com/docs/management/operations/ca-rotation/

## Details
Document clear and detailed instructions for handling  CA rotation for OpenSSH nodes. Docs should also clarify the phase during the rotation cycle when the usage of the one-shot command `teleport join openssh` should be executed.

something similar to the DB cert  rotation docs
https://goteleport.com/docs/management/operations/db-ca-rotation/

## How will we know this is resolved?
Guide should detail steps such that after a CA rotation, access to OpenSSH nodes via tsh is successful.

**Comment by ptgott** [comment]
Does this PR satisfy this request? https://github.com/gravitational/teleport/pull/40852

**Comment by oshati** [comment]
Yes it does
https://github.com/gravitational/teleport/issues/37125
