### ISSUE TITLE
tsh tunnelling occasionally hangs

### ISSUE THREAD

**Issue by sofuture** [gravitational/teleport#444]
I've noticed that when I run a command with `watch` that communicates through a teleport tunnel, it will occasionally hang. My `watch` command will hang and stop refreshing, but the issue is the inability to use the tunnel. Unrelated commands that attempt to use the tunnel will hang as well. Killing the current tsh process, and restarting the tunnel seems to fix this for a while.

In my specific case, it's almost always been running `watch kubectl get pods` over a teleport tunnel. The hang happens after 1+ hours, it's not very consistent.

Running `v0.1.0-alpha.15` which is pretty old, so I will follow up once I have upgraded.

**Comment by sofuture** [comment]
I can reproduce with `v0.2.0-beta.2`. 

Interestingly a different port that I'm tunnelling with the same `tsh` process continues to work with no issue. Since restarting the teleport tunnel fixes the issue, it does *seem* to be a `tsh` issue, and not an issue with the server on the other side of the tunnel.

**Comment by kontsevoy** [comment]
Had several tunnels continuously stream data to connected clients for 10+ hours. Stress tests for connect/disconnect also did not reveal any locks - all under vagrant. This looks like network error handling issue somewhere. Will keep digging.

**Comment by sofuture** [comment]
I haven't seen this, but I haven't specifically tried to reproduce in some time. Closing for now, will reopen if it repros.
