### ISSUE TITLE
Explain how users can track usage metrics 

### ISSUE THREAD

**Issue by tenaciousdlg** [gravitational/teleport#44631]
## Applies To

https://goteleport.com/docs/usage-billing/

## Details

The Usage Billing doc should explain where users can find their usage in the Teleport UI and which specific tenant (licensing) would have that.

## How will we know this is resolved?

When clients can self serve knowing where to go to look up usage data without reaching out to Teleport.

**Comment by webvictim** [comment]
Crude instructions I wrote for this:

1) Go to https://teleport.sh/
2) Enter their tenant name as assigned during onboarding
3) Sign in using their admin's configured username/password/MFA
4) Click on "Access Management" at the top

![image](https://github.com/user-attachments/assets/8e3519f1-016f-40dd-b213-9d048c55ecba)

5) Click on "Summary" under "Usage and Billing" at the left-hand side

![image](https://github.com/user-attachments/assets/97188b0a-21b1-4081-a752-c7178668be85)

6) Usage data will be shown there

![image](https://github.com/user-attachments/assets/47e8b8f5-7ad1-4c32-b402-b543ebb8f676)
