### ISSUE TITLE
Audit log is reporting SO user login failed [undefined] but it works. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4466]
### Description

**What happened**:
When logging into a cluster, it works but we output a failure to the audit log. 
![image](https://user-images.githubusercontent.com/559288/95271340-82086380-07f2-11eb-838c-9eb523d83714.png)

I found this while testing 4.4 test plan.  https://github.com/gravitational/teleport/issues/4359

### Environment
- Teleport version (use `teleport version`):  `Teleport Enterprise v4.4.0-alpha.1 git: go1.14.4b4`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by kimlisa** [comment]
backend error:
![Screenshot from 2020-10-09 18-15-19](https://user-images.githubusercontent.com/43280172/95642149-6bb11080-0a5b-11eb-85a1-5277393d3f1c.png)
