### ISSUE TITLE
Windows tsh issue

### ISSUE THREAD

**Issue by thierrydecker** [gravitational/teleport#4471]
### Description

In my configuration, tsh ssh works fine from a Debian shell but I can't make it work on windows tsh cli.

Note: Works fine from web browser from the same Windows machine

### Environment
- Teleport version: Teleport v4.3.5 git:v4.3.5-0-g122349e78 go1.13.2
- Tsh version: Teleport v4.3.5 git:v4.3.5-0-g122349e78 go1.13.2
- OS: Windows 10

- Where are you running Teleport? Dedicated Hardware

**Relevant Debug Logs If Applicable**

- ` tsh ssh --proxy=teleport --user=tdecker tdecker@teleport --debug`:  (same command as in Debian shell)

error: Get https://teleport:3080/v1/webapi/ping: x509: certificate signed by unknown authority

- `teleport --debug`: 

DEBU [PROXY]     conn(192.168.1.148:55691->192.168.1.145:3023, user=tdecker) auth attempt fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs local:192.168.1.145:3023 remote:192.168.1.148:55691 user:tdecker srv/authhandlers.go:151
DEBU [PROXY]     conn(192.168.1.148:55691->192.168.1.145:3023, user=tdecker) auth attempt with key ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs, &ssh.Certificate{Nonce:[]uint8{0x8d, 0x47, 0xc8, 0x7d, 0x89, 0xc6, 0x23, 0x23, 0xf5, 0xea, 0xf2, 0x4c, 0x3c, 0x45, 0x92, 0x8d, 0x21, 0xf7, 0x87, 0x4b, 0x55, 0x45, 0x90, 0xab, 0x64, 0x38, 0x15, 0x21, 0xe4, 0x38, 0x9a, 0xcf}, Key:(*ssh.rsaPublicKey)(0xc000cf65b0), Serial:0x0, CertType:0x1, KeyId:"tdecker", ValidPrincipals:[]string{"tdecker"}, ValidAfter:0x5f7d6e58, ValidBefore:0x5f7e1754, Permissions:ssh.Permissions{CriticalOptions:map[string]string{}, Extensions:map[string]string{"permit-agent-forwarding":"", "permit-port-forwarding":"", "permit-pty":"", "teleport-roles":"{\"version\":\"v1\",\"roles\":[\"admin\"]}", "teleport-route-to-cluster":"teleport", "teleport-traits":"{\"kubernetes_groups\":null,\"kubernetes_users\":[\"tdecker\"],\"logins\":[\"tdecker\"]}"}}, Reserved:[]uint8{}, SignatureKey:(*ssh.rsaPublicKey)(0xc000cf65f0), Signature:(*ssh.Signature)(0xc000c1ce40)} fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs local:192.168.1.145:3023 remote:192.168.1.148:55691 user:tdecker srv/authhandlers.go:151
DEBU [PROXY]     Successfully authenticated fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs local:192.168.1.145:3023 remote:192.168.1.148:55691 user:tdecker srv/authhandlers.go:196
DEBU [SSH:PROXY] Incoming connection 192.168.1.148:55691 -> 192.168.1.145:3023 vesion: SSH-2.0-Go. sshutils/server.go:430
DEBU [KEEPALIVE] Starting keep-alive loop with with interval 5m0s and max count 3. srv/keepalive.go:67
DEBU [PROXY]     Handling request subsystem, want reply true. id:12 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:55691 teleportUser:tdecker regular/sshserver.go:1140
DEBU [PROXY]     Subsystem request: proxySites(). id:12 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:55691 teleportUser:tdecker regular/sshserver.go:1254
DEBU [NODE]      proxysites.start(ServerContext(192.168.1.148:55691->192.168.1.145:3023, user=tdecker, id=12)) regular/sites.go:55
DEBU [NODE]      Subsystem proxySites() finished with result: <nil>. regular/sshserver.go:1262
DEBU [PROXY]     Close session request: <nil>. id:12 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:55691 teleportUser:tdecker regular/sshserver.go:1099
DEBU [SSH:PROXY] Received out-of-band request: &{Type:recording-proxy@teleport.com WantReply:true Payload:[] ch:<nil> mux:0xc0003cb110}. sshutils/server.go:456
DEBU [NODE]      Global request (recording-proxy@teleport.com, true) received regular/sshserver.go:1302
DEBU [NODE]      Replied to global request (recording-proxy@teleport.com, true): false regular/sshserver.go:1324
DEBU [PROXY]     Handling request subsystem, want reply true. id:13 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:55691 teleportUser:tdecker regular/sshserver.go:1140
DEBU [NODE]      parse_proxy_subsys("proxy:teleport:0@default@teleport") regular/proxy.go:70
DEBU [NODE]      newProxySubsys({default teleport 0 teleport}). regular/proxy.go:172
DEBU [PROXY]     Subsystem request: proxySubsys(cluster=default/teleport, host=teleport, port=0). id:13 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:55691 teleportUser:tdecker regular/sshserver.go:1254
DEBU [SUBSYSTEM] Starting subsystem trace.fields:map[dst:192.168.1.145:3023 src:192.168.1.148:55691] regular/proxy.go:201
DEBU [KEEPALIVE] Starting keep-alive loop with with interval 5m0s and max count 3. srv/keepalive.go:67
DEBU [SUBSYSTEM] proxy connecting to host=teleport port=0, exact port=false trace.fields:map[dst:192.168.1.145:3023 src:192.168.1.148:55691] regular/proxy.go:318
DEBU [PROXY:SER] Dialing from: "192.168.1.148:55691" to: "192.168.1.145:3022". trace.fields:map[cluster:teleport] reversetunnel/localsite.go:183
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
DEBU [NODE]      conn(192.168.1.148:55691->192.168.1.145:3022, user=tdecker) auth attempt fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs local:192.168.1.145:3022 remote:192.168.1.148:55691 user:tdecker srv/authhandlers.go:151
DEBU [NODE]      conn(192.168.1.148:55691->192.168.1.145:3022, user=tdecker) auth attempt with key ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs, &ssh.Certificate{Nonce:[]uint8{0x8d, 0x47, 0xc8, 0x7d, 0x89, 0xc6, 0x23, 0x23, 0xf5, 0xea, 0xf2, 0x4c, 0x3c, 0x45, 0x92, 0x8d, 0x21, 0xf7, 0x87, 0x4b, 0x55, 0x45, 0x90, 0xab, 0x64, 0x38, 0x15, 0x21, 0xe4, 0x38, 0x9a, 0xcf}, Key:(*ssh.rsaPublicKey)(0xc000dd16e0), Serial:0x0, CertType:0x1, KeyId:"tdecker", ValidPrincipals:[]string{"tdecker"}, ValidAfter:0x5f7d6e58, ValidBefore:0x5f7e1754, Permissions:ssh.Permissions{CriticalOptions:map[string]string{}, Extensions:map[string]string{"permit-agent-forwarding":"", "permit-port-forwarding":"", "permit-pty":"", "teleport-roles":"{\"version\":\"v1\",\"roles\":[\"admin\"]}", "teleport-route-to-cluster":"teleport", "teleport-traits":"{\"kubernetes_groups\":null,\"kubernetes_users\":[\"tdecker\"],\"logins\":[\"tdecker\"]}"}}, Reserved:[]uint8{}, SignatureKey:(*ssh.rsaPublicKey)(0xc000dd1720), Signature:(*ssh.Signature)(0xc0008551c0)} fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs local:192.168.1.145:3022 remote:192.168.1.148:55691 user:tdecker srv/authhandlers.go:151
DEBU [NODE]      Successfully authenticated fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs local:192.168.1.145:3022 remote:192.168.1.148:55691 user:tdecker srv/authhandlers.go:196
DEBU [NODE]      Checking permissions for (tdecker,tdecker) to login to node with RBAC checks. fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs local:192.168.1.145:3022 remote:192.168.1.148:55691 user:tdecker srv/authhandlers.go:323
DEBU [SSH:NODE]  Incoming connection 192.168.1.148:55691 -> 192.168.1.145:3022 vesion: SSH-2.0-Go. sshutils/server.go:430
DEBU [SSH:PROXY] Received out-of-band request: &{Type:recording-proxy@teleport.com WantReply:true Payload:[] ch:<nil> mux:0xc0003cb110}. sshutils/server.go:456
DEBU [NODE]      Global request (recording-proxy@teleport.com, true) received regular/sshserver.go:1302
DEBU [NODE]      Replied to global request (recording-proxy@teleport.com, true): false regular/sshserver.go:1324
DEBU [KEEPALIVE] Starting keep-alive loop with with interval 5m0s and max count 3. srv/keepalive.go:67
DEBU [PROXY]     Handling request subsystem, want reply true. id:14 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:55691 teleportUser:tdecker regular/sshserver.go:1140
DEBU [NODE]      parse_proxy_subsys("proxy:teleport:0@default@teleport") regular/proxy.go:70
DEBU [NODE]      newProxySubsys({default teleport 0 teleport}). regular/proxy.go:172
DEBU [PROXY]     Subsystem request: proxySubsys(cluster=default/teleport, host=teleport, port=0). id:14 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:55691 teleportUser:tdecker regular/sshserver.go:1254
DEBU [SUBSYSTEM] Starting subsystem trace.fields:map[dst:192.168.1.145:3023 src:192.168.1.148:55691] regular/proxy.go:201
DEBU [SUBSYSTEM] proxy connecting to host=teleport port=0, exact port=false trace.fields:map[dst:192.168.1.145:3023 src:192.168.1.148:55691] regular/proxy.go:318
DEBU [PROXY:SER] Dialing from: "192.168.1.148:55691" to: "192.168.1.145:3022". trace.fields:map[cluster:teleport] reversetunnel/localsite.go:183
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
DEBU [NODE]      conn(192.168.1.148:55691->192.168.1.145:3022, user=tdecker) auth attempt fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs local:192.168.1.145:3022 remote:192.168.1.148:55691 user:tdecker srv/authhandlers.go:151
DEBU [NODE]      conn(192.168.1.148:55691->192.168.1.145:3022, user=tdecker) auth attempt with key ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs, &ssh.Certificate{Nonce:[]uint8{0x8d, 0x47, 0xc8, 0x7d, 0x89, 0xc6, 0x23, 0x23, 0xf5, 0xea, 0xf2, 0x4c, 0x3c, 0x45, 0x92, 0x8d, 0x21, 0xf7, 0x87, 0x4b, 0x55, 0x45, 0x90, 0xab, 0x64, 0x38, 0x15, 0x21, 0xe4, 0x38, 0x9a, 0xcf}, Key:(*ssh.rsaPublicKey)(0xc000a16360), Serial:0x0, CertType:0x1, KeyId:"tdecker", ValidPrincipals:[]string{"tdecker"}, ValidAfter:0x5f7d6e58, ValidBefore:0x5f7e1754, Permissions:ssh.Permissions{CriticalOptions:map[string]string{}, Extensions:map[string]string{"permit-agent-forwarding":"", "permit-port-forwarding":"", "permit-pty":"", "teleport-roles":"{\"version\":\"v1\",\"roles\":[\"admin\"]}", "teleport-route-to-cluster":"teleport", "teleport-traits":"{\"kubernetes_groups\":null,\"kubernetes_users\":[\"tdecker\"],\"logins\":[\"tdecker\"]}"}}, Reserved:[]uint8{}, SignatureKey:(*ssh.rsaPublicKey)(0xc000a163a0), Signature:(*ssh.Signature)(0xc00072d200)} fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs local:192.168.1.145:3022 remote:192.168.1.148:55691 user:tdecker srv/authhandlers.go:151
DEBU [NODE]      Successfully authenticated fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs local:192.168.1.145:3022 remote:192.168.1.148:55691 user:tdecker srv/authhandlers.go:196
DEBU [NODE]      Checking permissions for (tdecker,tdecker) to login to node with RBAC checks. fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:DMeCokoyZA5Ts17LkTMa5zO4rGXoYcno4RMKOHuGjLs local:192.168.1.145:3022 remote:192.168.1.148:55691 user:tdecker srv/authhandlers.go:323
DEBU [SSH:NODE]  Incoming connection 192.168.1.148:55691 -> 192.168.1.145:3022 vesion: SSH-2.0-Go. sshutils/server.go:430
DEBU [SSH:NODE]  Received out-of-band request: &{Type:x-teleport-version WantReply:true Payload:[] ch:<nil> mux:0xc0003cb730}. sshutils/server.go:456
DEBU [PROXY]     Client 192.168.1.148:55691 disconnected. id:14 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:55691 teleportUser:tdecker regular/sshserver.go:1104
DEBU [SSH:PROXY] Closed connection 192.168.1.148:55691. sshutils/server.go:432
DEBU [NODE]      Subsystem proxySubsys(cluster=default/teleport, host=teleport, port=0) finished with result: read tcp 192.168.1.145:45380->192.168.1.145:3022: use of closed network connection. regular/sshserver.go:1262
DEBU [PROXY]     Client 192.168.1.148:55691 disconnected. id:13 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:55691 teleportUser:tdecker regular/sshserver.go:1104
DEBU [SSH:NODE]  Closed connection 192.168.1.148:55691. sshutils/server.go:432
DEBU [NODE]      Subsystem proxySubsys(cluster=default/teleport, host=teleport, port=0) finished with result: read tcp 192.168.1.145:45382->192.168.1.145:3022: use of closed network connection. regular/sshserver.go:1262
DEBU [SSH:NODE]  Closed connection 192.168.1.148:55691. sshutils/server.go:432
2020-10-07 10:03:09.512021 I | http: TLS handshake error from 192.168.1.148:55692: remote error: tls: bad certificate

**Comment by webvictim** [comment]
Can you run the `tsh` command you’re trying with `tsh -d` and provide those logs please?

**Comment by thierrydecker** [comment]
I and thanks for your reply.

I run this command to login to teleport instance:

> **tsh --proxy=teleport --user=tdecker --insecure login**                        
WARNING: You are using insecure connection to SSH proxy https://teleport:3080 
Enter password for Teleport user tdecker:                                     
Enter your OTP token:                                                         
xxxxxx                                                                        
WARNING: You are using insecure connection to SSH proxy https://teleport:3080 
> Profile URL:  https://teleport:3080                                         
  Logged in as: tdecker                                                       
  Cluster:      teleport                                                      
  Roles:        admin*                                                        
  Logins:       tdecker                                                       
  Valid until:  2020-10-08 04:08:30 +0200 CEST [valid for 12h0m0s]            
  Extensions:   permit-agent-forwarding, permit-port-forwarding, permit-pty   
                                                                              
                                                                              
* RBAC is only available in Teleport Enterprise                               
  https://gravitational.com/teleport/docs/enterprise

Then this one to ssh to the teleport host:

> **tsh ssh tdecker@teleport**
error: Get https://teleport:3080/v1/webapi/ping: x509: certificate signed by unknown authority

And this one with debug flag:

> **tsh ssh tdecker@teleport -d**                                                                 
error: Get https://teleport:3080/v1/webapi/ping: x509: certificate signed by unknown authority

As you can see, no debug information...

Also try these detailled commands;

> **tsh ssh --user=tdecker tdecker@teleport -d**
error: Get https://teleport:3080/v1/webapi/ping: x509: certificate signed by unknown authority

> **tsh ssh --proxy=teleport --user=tdecker tdecker@teleport -d**
error: Get https://teleport:3080/v1/webapi/ping: x509: certificate signed by unknown authority

On each of these different tries, I get these logs on the teleport server:

DEBU [PROXY]     conn(192.168.1.148:57897->192.168.1.145:3023, user=tdecker) auth attempt fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU local:192.168.1.145:3023 remote:192.168.1.148:57897 user:tdecker srv/authhandlers.go:151
DEBU [PROXY]     conn(192.168.1.148:57897->192.168.1.145:3023, user=tdecker) auth attempt with key ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU, &ssh.Certificate{Nonce:[]uint8{0xf6, 0x1, 0xe4, 0xa2, 0xa, 0xfa, 0xc5, 0x18, 0x59, 0xc4, 0xb3, 0x5, 0x1f, 0x63, 0x72, 0x4c, 0xa2, 0x50, 0x75, 0x95, 0x4, 0x27, 0x19, 0xd3, 0x5c, 0xd, 0x5e, 0x9a, 0x90, 0xed, 0xe1, 0xa1}, Key:(*ssh.rsaPublicKey)(0xc000892fe0), Serial:0x0, CertType:0x1, KeyId:"tdecker", ValidPrincipals:[]string{"tdecker"}, ValidAfter:0x5f7dcd1e, ValidBefore:0x5f7e761a, Permissions:ssh.Permissions{CriticalOptions:map[string]string{}, Extensions:map[string]string{"permit-agent-forwarding":"", "permit-port-forwarding":"", "permit-pty":"", "teleport-roles":"{\"version\":\"v1\",\"roles\":[\"admin\"]}", "teleport-route-to-cluster":"teleport", "teleport-traits":"{\"kubernetes_groups\":null,\"kubernetes_users\":[\"tdecker\"],\"logins\":[\"tdecker\"]}"}}, Reserved:[]uint8{}, SignatureKey:(*ssh.rsaPublicKey)(0xc000893020), Signature:(*ssh.Signature)(0xc0006ea6c0)} fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU local:192.168.1.145:3023 remote:192.168.1.148:57897 user:tdecker srv/authhandlers.go:151
DEBU [PROXY]     Successfully authenticated fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU local:192.168.1.145:3023 remote:192.168.1.148:57897 user:tdecker srv/authhandlers.go:196
DEBU [SSH:PROXY] Incoming connection 192.168.1.148:57897 -> 192.168.1.145:3023 vesion: SSH-2.0-Go. sshutils/server.go:430
DEBU [KEEPALIVE] Starting keep-alive loop with with interval 5m0s and max count 3. srv/keepalive.go:67
DEBU [PROXY]     Handling request subsystem, want reply true. id:11 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:57897 teleportUser:tdecker regular/sshserver.go:1140
DEBU [PROXY]     Subsystem request: proxySites(). id:11 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:57897 teleportUser:tdecker regular/sshserver.go:1254
DEBU [NODE]      proxysites.start(ServerContext(192.168.1.148:57897->192.168.1.145:3023, user=tdecker, id=11)) regular/sites.go:55
DEBU [NODE]      Subsystem proxySites() finished with result: <nil>. regular/sshserver.go:1262
DEBU [PROXY]     Close session request: <nil>. id:11 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:57897 teleportUser:tdecker regular/sshserver.go:1099
DEBU [SSH:PROXY] Received out-of-band request: &{Type:recording-proxy@teleport.com WantReply:true Payload:[] ch:<nil> mux:0xc00034f1f0}. sshutils/server.go:456
DEBU [NODE]      Global request (recording-proxy@teleport.com, true) received regular/sshserver.go:1302
DEBU [NODE]      Replied to global request (recording-proxy@teleport.com, true): false regular/sshserver.go:1324
DEBU [KEEPALIVE] Starting keep-alive loop with with interval 5m0s and max count 3. srv/keepalive.go:67
DEBU [PROXY]     Handling request subsystem, want reply true. id:12 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:57897 teleportUser:tdecker regular/sshserver.go:1140
DEBU [NODE]      parse_proxy_subsys("proxy:teleport:0@default@teleport") regular/proxy.go:70
DEBU [NODE]      newProxySubsys({default teleport 0 teleport}). regular/proxy.go:172
DEBU [PROXY]     Subsystem request: proxySubsys(cluster=default/teleport, host=teleport, port=0). id:12 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:57897 teleportUser:tdecker regular/sshserver.go:1254
DEBU [SUBSYSTEM] Starting subsystem trace.fields:map[dst:192.168.1.145:3023 src:192.168.1.148:57897] regular/proxy.go:201
DEBU [SUBSYSTEM] proxy connecting to host=teleport port=0, exact port=false trace.fields:map[dst:192.168.1.145:3023 src:192.168.1.148:57897] regular/proxy.go:318
DEBU [PROXY:SER] Dialing from: "192.168.1.148:57897" to: "192.168.1.145:3022". trace.fields:map[cluster:teleport] reversetunnel/localsite.go:183
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
DEBU [NODE]      conn(192.168.1.148:57897->192.168.1.145:3022, user=tdecker) auth attempt fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU local:192.168.1.145:3022 remote:192.168.1.148:57897 user:tdecker srv/authhandlers.go:151
DEBU [NODE]      conn(192.168.1.148:57897->192.168.1.145:3022, user=tdecker) auth attempt with key ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU, &ssh.Certificate{Nonce:[]uint8{0xf6, 0x1, 0xe4, 0xa2, 0xa, 0xfa, 0xc5, 0x18, 0x59, 0xc4, 0xb3, 0x5, 0x1f, 0x63, 0x72, 0x4c, 0xa2, 0x50, 0x75, 0x95, 0x4, 0x27, 0x19, 0xd3, 0x5c, 0xd, 0x5e, 0x9a, 0x90, 0xed, 0xe1, 0xa1}, Key:(*ssh.rsaPublicKey)(0xc0004bf300), Serial:0x0, CertType:0x1, KeyId:"tdecker", ValidPrincipals:[]string{"tdecker"}, ValidAfter:0x5f7dcd1e, ValidBefore:0x5f7e761a, Permissions:ssh.Permissions{CriticalOptions:map[string]string{}, Extensions:map[string]string{"permit-agent-forwarding":"", "permit-port-forwarding":"", "permit-pty":"", "teleport-roles":"{\"version\":\"v1\",\"roles\":[\"admin\"]}", "teleport-route-to-cluster":"teleport", "teleport-traits":"{\"kubernetes_groups\":null,\"kubernetes_users\":[\"tdecker\"],\"logins\":[\"tdecker\"]}"}}, Reserved:[]uint8{}, SignatureKey:(*ssh.rsaPublicKey)(0xc0004bf340), Signature:(*ssh.Signature)(0xc000a9d540)} fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU local:192.168.1.145:3022 remote:192.168.1.148:57897 user:tdecker srv/authhandlers.go:151
DEBU [NODE]      Successfully authenticated fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU local:192.168.1.145:3022 remote:192.168.1.148:57897 user:tdecker srv/authhandlers.go:196
DEBU [NODE]      Checking permissions for (tdecker,tdecker) to login to node with RBAC checks. fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU local:192.168.1.145:3022 remote:192.168.1.148:57897 user:tdecker srv/authhandlers.go:323
DEBU [SSH:NODE]  Incoming connection 192.168.1.148:57897 -> 192.168.1.145:3022 vesion: SSH-2.0-Go. sshutils/server.go:430
DEBU [SSH:PROXY] Received out-of-band request: &{Type:recording-proxy@teleport.com WantReply:true Payload:[] ch:<nil> mux:0xc00034f1f0}. sshutils/server.go:456
DEBU [NODE]      Global request (recording-proxy@teleport.com, true) received regular/sshserver.go:1302
DEBU [NODE]      Replied to global request (recording-proxy@teleport.com, true): false regular/sshserver.go:1324
DEBU [PROXY]     Handling request subsystem, want reply true. id:13 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:57897 teleportUser:tdecker regular/sshserver.go:1140
DEBU [NODE]      parse_proxy_subsys("proxy:teleport:0@default@teleport") regular/proxy.go:70
DEBU [NODE]      newProxySubsys({default teleport 0 teleport}). regular/proxy.go:172
DEBU [PROXY]     Subsystem request: proxySubsys(cluster=default/teleport, host=teleport, port=0). id:13 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:57897 teleportUser:tdecker regular/sshserver.go:1254
DEBU [SUBSYSTEM] Starting subsystem trace.fields:map[dst:192.168.1.145:3023 src:192.168.1.148:57897] regular/proxy.go:201
DEBU [SUBSYSTEM] proxy connecting to host=teleport port=0, exact port=false trace.fields:map[dst:192.168.1.145:3023 src:192.168.1.148:57897] regular/proxy.go:318
DEBU [KEEPALIVE] Starting keep-alive loop with with interval 5m0s and max count 3. srv/keepalive.go:67
DEBU [PROXY:SER] Dialing from: "192.168.1.148:57897" to: "192.168.1.145:3022". trace.fields:map[cluster:teleport] reversetunnel/localsite.go:183
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
DEBU [NODE]      conn(192.168.1.148:57897->192.168.1.145:3022, user=tdecker) auth attempt fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU local:192.168.1.145:3022 remote:192.168.1.148:57897 user:tdecker srv/authhandlers.go:151
DEBU [NODE]      conn(192.168.1.148:57897->192.168.1.145:3022, user=tdecker) auth attempt with key ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU, &ssh.Certificate{Nonce:[]uint8{0xf6, 0x1, 0xe4, 0xa2, 0xa, 0xfa, 0xc5, 0x18, 0x59, 0xc4, 0xb3, 0x5, 0x1f, 0x63, 0x72, 0x4c, 0xa2, 0x50, 0x75, 0x95, 0x4, 0x27, 0x19, 0xd3, 0x5c, 0xd, 0x5e, 0x9a, 0x90, 0xed, 0xe1, 0xa1}, Key:(*ssh.rsaPublicKey)(0xc0009ba630), Serial:0x0, CertType:0x1, KeyId:"tdecker", ValidPrincipals:[]string{"tdecker"}, ValidAfter:0x5f7dcd1e, ValidBefore:0x5f7e761a, Permissions:ssh.Permissions{CriticalOptions:map[string]string{}, Extensions:map[string]string{"permit-agent-forwarding":"", "permit-port-forwarding":"", "permit-pty":"", "teleport-roles":"{\"version\":\"v1\",\"roles\":[\"admin\"]}", "teleport-route-to-cluster":"teleport", "teleport-traits":"{\"kubernetes_groups\":null,\"kubernetes_users\":[\"tdecker\"],\"logins\":[\"tdecker\"]}"}}, Reserved:[]uint8{}, SignatureKey:(*ssh.rsaPublicKey)(0xc0009ba670), Signature:(*ssh.Signature)(0xc000e9a940)} fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU local:192.168.1.145:3022 remote:192.168.1.148:57897 user:tdecker srv/authhandlers.go:151
DEBU [NODE]      Successfully authenticated fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU local:192.168.1.145:3022 remote:192.168.1.148:57897 user:tdecker srv/authhandlers.go:196
DEBU [NODE]      Checking permissions for (tdecker,tdecker) to login to node with RBAC checks. fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:Vt8YGtWNXD7PIWfukr1PbW5sP71QH021n61E9vTwKrU local:192.168.1.145:3022 remote:192.168.1.148:57897 user:tdecker srv/authhandlers.go:323
DEBU [SSH:NODE]  Incoming connection 192.168.1.148:57897 -> 192.168.1.145:3022 vesion: SSH-2.0-Go. sshutils/server.go:430
DEBU [SSH:NODE]  Received out-of-band request: &{Type:x-teleport-version WantReply:true Payload:[] ch:<nil> mux:0xc0002f9570}. sshutils/server.go:456
DEBU [SSH:PROXY] Closed connection 192.168.1.148:57897. sshutils/server.go:432
DEBU [NODE]      Subsystem proxySubsys(cluster=default/teleport, host=teleport, port=0) finished with result: read tcp 192.168.1.145:36906->192.168.1.145:3022: use of closed network connection. regular/sshserver.go:1262
DEBU [NODE]      Closing session due to cancellation. regular/sshserver.go:1128
DEBU [NODE]      Subsystem proxySubsys(cluster=default/teleport, host=teleport, port=0) finished with result: read tcp 192.168.1.145:36904->192.168.1.145:3022: use of closed network connection. regular/sshserver.go:1262
DEBU [PROXY]     Client 192.168.1.148:57897 disconnected. id:12 local:192.168.1.145:3023 login:tdecker remote:192.168.1.148:57897 teleportUser:tdecker regular/sshserver.go:1104
DEBU [SSH:NODE]  Closed connection 192.168.1.148:57897. sshutils/server.go:432
DEBU [SSH:NODE]  Closed connection 192.168.1.148:57897. sshutils/server.go:432
2020-10-07 16:17:56.490781 I | http: TLS handshake error from 192.168.1.148:57898: remote error: tls: bad certificate

**Comment by webvictim** [comment]
Try `tsh ssh tdecker@teleport --insecure -d` for connecting to the node.

**Comment by webvictim** [comment]
Regarding this issue, `tsh ssh` isn't actually supported on Windows. If you do manage to resolve the access issue, you will ultimately see this error:

```console
ERROR REPORT:
Original Error: *trace.BadParameterError sessions not supported on Windows
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/client/session_windows.go:49 github.com/gravitational/teleport/lib/client.newSession
        /go/src/github.com/gravitational/teleport/lib/client/api.go:1485 github.com/gravitational/teleport/lib/client.(*TeleportClient).runShell
        /go/src/github.com/gravitational/teleport/lib/client/api.go:990 github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:890 main.onSSH.func1
        /go/src/github.com/gravitational/teleport/lib/client/api.go:363 github.com/gravitational/teleport/lib/client.RetryWithRelogin
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:889 main.onSSH
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:362 main.Run
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:194 main.main
        /opt/go/src/runtime/proc.go:212 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit
User Message: sessions not supported on Windows
```

To use Teleport on Windows you need to use `ssh.exe` from the OpenSSH client package. We have some instructions here on how to do this: https://community.gravitational.com/t/how-to-connect-to-teleport-hosts-using-windows/559

**Comment by webvictim** [comment]
Closing this issue.

**Comment by ofer-dev** [comment]
Will tsh ssh be supported on Windows?

**Comment by webvictim** [comment]
We don’t currently have any plans to support it. There is a guide on how to use Teleport with ssh.exe on Windows here: https://community.gravitational.com/t/how-to-connect-to-teleport-hosts-using-windows/559
