### ISSUE TITLE
Improve Okta Synchronizer role naming convention

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#44740]
What would you like Teleport to do?

Using Teleport [Synchronization with Okta and SCIM](https://goteleport.com/docs/enroll-resources/application-access/okta/sync-scim/#synchronizing-access-lists-from-okta-groups-and-applications) the roles created are named using the Okta Group ID. Teleport should offer a way to make role naming more user-friendly. 

Example role naming: 
`Roles: 00g1384xuktchXYZ.., 00g25a0qwj2rXYZ.., access, auditor, editor, teleport-admin`

What problem does this solve?
The names used are nondescriptive and do not help end users understand their roles. 

If a workaround exists, please include it.

**Comment by smallinsky** [comment]
> This work is already in progress.
> 
> @smallinsky is there an existing issue already open?

We don't we can keep this issue open for visibility.

**Comment by r0mant** [comment]
This was fixed a couple of weeks ago.

**Comment by smallinsky** [comment]
Fixed in https://github.com/gravitational/teleport.e/pull/4803
