### ISSUE TITLE
tsh aws prepends extra lines to stdout

### ISSUE THREAD

**Issue by Dawnflash** [gravitational/teleport#44858]
Expected behavior:

`tsh aws s3 ls` (or any other AWS CLI command) returns only the output from AWS, eg.

```
2024-12-15 10:35:32 mybucket
```

Alternatively any extra lines from teleport should be printed to stderr.

Current behavior:

It returns 2 extra lines in stdout. This is very undesirable when piping forward.

```
Proxying connections to aws on 127.0.0.1:54277
To avoid port randomization, you can choose the listening port using the --port flag.
2024-12-15 10:35:32 mybucket
```

Additionally the `--port` flag referenced refers to the `tsh proxy app` command which is reused by the `tsh aws` command apparently and the flag is unusable with the `tsh aws` command so this is very confusing for the user that might attempt to run `tsh aws --port 12345 s3 ls` to try to remove the message and be met with "flag not defined". This could use some polishing.

Bug details:
- Teleport version:  v16.1.0
- Recreation steps: run `tsh aws <anything>`

**Comment by greedy52** [comment]
fixed by #45159
