### ISSUE TITLE
More contrast favicon

### ISSUE THREAD

**Issue by GDreyV** [gravitational/teleport#45258]
Hi! It's really tiny-tiny improvement request but by any chance could you please make favicon a bit more contrast (e.g. use white background or just border) to make it look a bit better in the dark mode browsers?
That's how it looks like right now:
![image](https://github.com/user-attachments/assets/58ebdf79-d4eb-404b-ba5d-a59a8d472e43)
Thanks!

**Comment by zmb3** [comment]
Are you up to date?

It should switch to a white favicon in dark mode. Looks like this for me

<img width="212" alt="image" src="https://github.com/user-attachments/assets/fc01ed8b-2d67-47f2-aebe-39eb526f8f4b">

**Comment by GDreyV** [comment]
I'm on Microsoft Edge for Business
Version 127.0.2651.86 (Official build) (64-bit)
I'm not sure if it's exactly dark theme, maybe it's just the way how it looks in general. Also, people might use custom background which might be different from the dark/light theming

**Comment by GDreyV** [comment]
Thank you!

**Comment by olingerc** [comment]
Hi,

Not sure if it related to this. But I have since some time now only a white favicon which makes it invisible in my browser (firefox) and leaves white holes in my favorites bar
![Image](https://github.com/user-attachments/assets/28032b4b-8dae-4ac6-baf3-56cb3f857c5f)

**Comment by avatus** [comment]
What version of Twleport are you running @olingerc ?

**Comment by olingerc** [comment]
Hi @avatus. We have version 15.4.14

**Comment by avatus** [comment]
This will be fixed in the next release of v15, and is already fixed in v16 and higher.
Thanks for info, @olingerc !
