### ISSUE TITLE
Microsoft SSO login is using Auth0 style 

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport#4525]
### Description

**What happened**: Customer reported after upgrading to 4.3.7 Microsoft SSO login in the Web UI is using the Auth0 style.

![MicrosoftAsAuth0](https://user-images.githubusercontent.com/8000186/95806045-a3b68e80-0cbb-11eb-99ac-e96710bebd10.PNG)

**What you expected to happen**: Style of Web UI button should be updated to the correct Microsoft style. 

### Environment
- Teleport version (use `teleport version`): `4.3.7`

**Comment by stevenGravy** [comment]
the name comparison is case sensitive now.  If you make this the display `  display: microsoft` the icon will show.    `display: Microsoft` will show the above icon.

**Comment by webvictim** [comment]
We should probably fix that issue so that we lowercase any value for `display` before it's evaluated.
