### ISSUE TITLE
Explain IAM Role Name input field in AWS OIDC integration

### ISSUE THREAD

**Issue by flyinghermit** [gravitational/teleport#45387]
In the AWS IAM OIDC integration Step 1, we ask to enter an IAM role name. But it is not clear enough what is expected off that field. Will Teleport create a new role under provided role name? Or are user's expected to provide a name of a role that aready exists. What is expected off that role (scope, permissions etc) and how and for what purpose we will use it (only configure integration? resource permission? both?)

<img width="1082" alt="Screenshot 2024-08-12 at 1 09 35 PM" src="https://github.com/user-attachments/assets/c6be4a11-5d3f-466b-9ed5-daea95a641ac">

### What would you like Teleport to do?

Update description and display a hint in the UI, or link to docs that has the proper explanation on the role requirement.

### What problem does this solve?

Better getting started experience with the AWS OIDC integration.

**Comment by zmb3** [comment]
<img width="673" alt="Image" src="https://github.com/user-attachments/assets/2a7f0d5a-1b19-43f7-98a3-c73e8fbdcec5" />

Looks like this was completed.
