### ISSUE TITLE
user signup welcome to Teleport shows old logo

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#45425]
Expected behavior:

The user signup pages would use the new logo.

Current behavior:

Both self-hosted and cloud show the previous Logo when a user is signing up their user credentials.

<img width="759" alt="image" src="https://github.com/user-attachments/assets/e2ff973e-2e7f-43e9-b9bb-8a81c64da606">

Bug details:
- Teleport version: 16 and 17 dev
- Recreation steps

Invite a local user to sign up.

**Comment by zmb3** [comment]
@avatus can you grab this one? Looks like it's `web/packages/design/src/assets/images/TeleportLogoII.tsx`
