### ISSUE TITLE
Connecting to an offline IoT node via SSH gives a weirdly-formatted error

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4542]
**What happened**: I restarted Teleport on an IoT node (`zeus`) after upgrading it to a newer version and it did the occasional thing it does where it doesn't actually restart for 90 seconds (which is another bug in itself, but I digress). While this was going on, `tsh ssh zeus` gave me this error:

```console
$ tsh ssh zeus
error: failed connecting to node zeus. node is offline, please try again later
```

This error is helpful and useful.

Running `ssh zeus` sporadically gives me this garbled error, however: 

```console
$ ssh zeus
node is offline, please try again latersubsystem request failed on channel 0
kex_exchange_identification: Connection closed by remote host
```

It seems to be returning the error with no line break at the end, so it looks odd. This error also doesn't always appear - it happens maybe 1 in 5 times you try to connect. The other times you just get:

```console
$ ssh zeus
subsystem request failed on channel 0
kex_exchange_identification: Connection closed by remote host
```

Here's the full `ssh -v` output:

```console
$ ssh -v zeus
OpenSSH_8.1p1, OpenSSL 1.1.1g FIPS  21 Apr 2020
debug1: Reading configuration data /home/gus/.ssh/config
debug1: Reading configuration data /home/gus/.ssh/teleport/ssh_config
debug1: /home/gus/.ssh/teleport/ssh_config line 6: Applying options for zeus
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: configuration requests final Match pass
debug1: re-parsing configuration
debug1: Reading configuration data /home/gus/.ssh/config
debug1: Reading configuration data /home/gus/.ssh/teleport/ssh_config
debug1: /home/gus/.ssh/teleport/ssh_config line 6: Applying options for zeus
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: Executing proxy command: exec sh -c '~/.ssh/teleport/login.sh example.domain.com username && ssh example.domain.com -s proxy:zeus:3022'
debug1: identity file /home/gus/.tsh/keys/example.domain.com/username type 0
debug1: identity file /home/gus/.tsh/keys/example.domain.com/username-cert type 4
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: kex_exchange_identification: banner line 0: /usr/bin/ssh-keygen
node is offline, please try again latersubsystem request failed on channel 0
kex_exchange_identification: Connection closed by remote host
```

These are the relevant sections of `~/.ssh/teleport/ssh_config`:

```console
Host example.domain.com
    User gus
    Port 3023
    IdentityFile ~/.tsh/keys/example.domain.com/username

Host zeus
    User gus
    ProxyCommand sh -c '~/.ssh/teleport/login.sh example.domain.com username && ssh example.domain.com -s proxy:%h:%p'
    Port 3022
    IdentityFile ~/.tsh/keys/example.domain.com/username
    HostKeyAlias zeus.example.domain.com
```

`~/.ssh/teleport/login.sh` is a simple bash wrapper script that runs `tsh login --proxy=example.domain.com --user=username` if the Teleport-issued user certificate has expired.

**What you expected to happen**: If we return a "node is offline, please try again later" message from the proxy subsystem, it should have a line break at the end so that it can be read easily via `ssh`.

**How to reproduce it (as minimally and precisely as possible)**: Take an IoT node offline and try to connect to it through the Teleport proxy via ssh.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.6git:v4.3.6-0-gfabee242d go1.13.2`
- Tsh version (use `tsh version`): `Teleport v4.3.6 git:v4.3.6-0-gfabee242d go1.13.2`
- OS (e.g. from `/etc/os-release`): Fedora 31

**Comment by webvictim** [comment]
OpenSSH client version: `OpenSSH_8.1p1, OpenSSL 1.1.1g FIPS  21 Apr 2020`

**Comment by zmb3** [comment]
This was fixed in https://github.com/gravitational/teleport/pull/7165
