### ISSUE TITLE
Teleport Connect "Cancel" button still launches browser session

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#45478]
Expected behavior:
When Device Trust is enabled in Teleport and you choose to launch Teleport Connect there is a pop up that allows you to "Launch Web Session" or click "Cancel". Update the "Cancel" button to be more clear on what will happen when you do click "Cancel".

Current behavior:
When clicking the "Cancel" button a browser session is launched.

Bug details:
- Teleport version: v16.1.4
- Recreation steps: Login to Teleport Web UI with Device Trust enabled. Launch Teleport Connect from the link in the browser. Click Cancel.
<img width="429" alt="Screenshot 2024-08-14 at 11 14 34 AM" src="https://github.com/user-attachments/assets/b82333c6-72e6-479f-9264-3c8f827fd286">

- Debug logs

**Comment by avatus** [comment]
For context, this is the desired behavior. The session that is launched after clicking "Cancel" is NOT authorized. It is the same as clicking "continue without device trust" in the web passthrough page. The solution to this should be better language on the dialog/button
