### ISSUE TITLE
No longer possible to completely hide the "Access Management" section of the UI

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#45537]
## Expected behavior

The "Access Management" section of the Teleport web UI should be automatically hidden if you have no permissions to perform any admin actions inside the cluster.

As shown by the popularity of [this discussion post showing how to hide Teleport's web UI sections](https://github.com/gravitational/teleport/discussions/11920), this is key functionality sought by Teleport administrators to make it easier for non-admin users to navigate the cluster.

## Current behavior

Removing all permissions from a user still shows the Access Management section of the UI, with two active subheadings:

### Enroll new resource

![image](https://github.com/user-attachments/assets/0adcb6b8-e127-4d74-a876-cebf7c42fcd0)

It is pointless to show this section to users when they have no permission for any of the resource adding flows.

### Access lists

![image](https://github.com/user-attachments/assets/f26f1557-0490-4fd0-a99a-35e214cc767a)

This page even tells you the reason why you can't see access lists, but then still shows them.

Modifying the web UI's ACLs so that these sections are not shown without appropriate permissions (or can at least be hidden by adding `deny` rules for specific RBAC resources) will help to make the UI less confusing for non-administrative users.

Bug details:
- Teleport version: 16.1.4

**Comment by zmb3** [comment]
This is working as intended. Hiding sections of the UI is available to enterprise customers who meet certain requirements, the details of which are not appropriate in the OSS issue tracker.
