### ISSUE TITLE
Document how to use kubernetes_resources for providing access to cluster-level resources like CRDs

### ISSUE THREAD

**Issue by zifeo** [gravitational/teleport#45543]
## Applies To

https://goteleport.com/docs/enroll-resources/kubernetes-access/controls/

## Details

Currently, only namespaced examples are referenced and it is unclear how to provide user with a cluster-wide fine-grained permissions (e.g. deploy CRD like the prom-stack), or if this is even doable/supported.

## How will we know this is resolved?

Provide an example or clarify how to control cluster-level resources permissions.

## Related Issues

None

**Comment by zmb3** [comment]
CRDs are not currently supported. That's being tracked over at #35273.

**Comment by zifeo** [comment]
@zmb3 Thanks, what about cluster role bindings? https://github.com/gravitational/teleport/issues/35273 is only about crd.
