### ISSUE TITLE
Unclear that I need to sign in again via the web interface to access AAP app

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4559]
**What happened**: I refreshed a tab which I had opened yesterday with an AAP app loaded. The page went away and was replaced with the single word "Forbidden" in black text on a white background.

I signed into my Teleport cluster via another tab and refreshed the page again - still the same "Forbidden" message.

In the end, I had to close my existing tab, go back to the "Applications" tab in Teleport and start completely a new session by clicking on the app. This wasn't very clear to me - I initially expected that if I needed to reauthenticate to access the app, I would be redirected to the Teleport sign-in page to complete the sign-in and then sent back to the app afterwards.

Not sure if this is a deliberate decision for security, but it breaks the use of deep links to other apps via AAP. My expected flow would be that if you need to sign in to access an app, you are redirected to a sign-in page and then sent back to the URL you initially requested after this is complete - Teleport does this for its own internal links as well.

**What you expected to happen**: Either I should be redirected to the Teleport sign-in page when trying to load an app that I no longer have a session for, or the "Forbidden" message should be edited to say something like "Reauthentication via Teleport is required to access this service." as a clue that I need to go and log in again to start a brand new session.

It isn't currently clear at all whether "Forbidden" is a message coming from Teleport or being returned by the app that Teleport is proxying (I know now that it's coming from Teleport, but another user might not)

**How to reproduce it (as minimally and precisely as possible)**: Access an app via Teleport, let your session time out and then try to refresh the page.

### Environment
- Teleport version (use `teleport version`): `Teleport v5.0.0-beta.2 git:v5.0.0-beta.2-0-g412fb2062 go1.14.4`

**Comment by russjones** [comment]
Hrm, interesting bug. One thing to note is that with just the domain, the best I can do is best effort resolution, so until the application switcher gets added, we may want to punt on this one. But we should discuss.
