### ISSUE TITLE
Teleport Operator: Add CRD for bot and token resources

### ISSUE THREAD

**Issue by moorara** [gravitational/teleport#45609]
What would you like Teleport to do?

I'd like to deploy/apply the Teleport bot and join token resources as Kubernetes resources.

What problem does this solve?

This allows creating a Helm chart for installing `tbot` as well as creating bootstrapping Teleport resources using the Helm chart pattern.

If a workaround exists, please include it.

No workaround for deploying the bot and join token resources using Helm.

**Comment by strideynet** [comment]
Dupe of https://github.com/gravitational/teleport/issues/34285 for adding the Bot resource to the operator.

The ProvisionToken resource can already be configured using the Teleport Operator - if you are having issues using this please open a ticket describing them.
