### ISSUE TITLE
JIRA Access Request should clarify that TLS cannot be self-signed for webhook

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#45654]
## Applies To

https://goteleport.com/docs/admin-guides/access-controls/access-request-plugins/ssh-approval-jira/

## Details

JIRA Access Request guide should explicitly state that it will require a valid TLS certificate for the webhook. Using a self-signed certificate will result in "TLS handshake error"

**Comment by stevenGravy** [comment]
There are some other issues with the TLS Certs instructions:
- mentions Caddy as used but is not actually shown how to setup
- helm chart leaves out setting up the TLS certs
