### ISSUE TITLE
Update uses of libu2f-host to libfido2

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4569]
### Feature Request
`u2f-host` is deprecated (https://developers.yubico.com/libu2f-host/)

https://developers.yubico.com/libfido2/ is the new hotness. We should change any use of libu2f-host and the `u2f-host` binary to libfido2 and whatever the new binary is.

### Motivation
U2F isn't going away

### Who's it for?
OSS User, Pro, Enterprise

**Comment by awly** [comment]
I plan on using https://github.com/flynn/u2f for the new U2F features later in the year.
One fewer CGO dependencies :axe:

**Comment by webvictim** [comment]
Great news!

**Comment by awly** [comment]
We'll stop using `u2f-host` as part of https://github.com/gravitational/teleport/issues/3878
