### ISSUE TITLE
AAP labels aren't shown in application browser

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4571]
**What happened**: See #4570 for config example and screenshot - just wanted to make a separate issue so this is tracked/addressed.

The application browser doesn't show any labels on the apps, even though they are set in the config. We do show labels against nodes in the Teleport UI, so I figure we should here too. They can give useful context about exactly what people are connecting to, plus they can be dynamic commands to give additional information if desired. Given that labels are used by RBAC to gate access to apps, it's also nice to be able to easily see what labels you can use for this on an app-by-app basis.
 
I'm not sure if this is a deliberate decision or whether it just hasn't been implemented yet. If it's a deliberate decision, we should rethink it.

**What you expected to happen**: We should show app labels.

**How to reproduce it (as minimally and precisely as possible)**: Use config from #4570, open application browser see that there are no labels.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v5.0.0-beta.2 git:v5.0.0-beta.2-0-g412fb2062 go1.14.4`

**Comment by benarent** [comment]
Thanks for making the issue Gus.  I think we dropped it for the beta, but we should do another design round for these cards. I also think we can drop the cluster name, since we are no longer apps from different clusters together.

@alexwolfe Did you have a design with labels for these cards?

**Comment by stevenGravy** [comment]
A customer was also interested in seeing a search as they may have a large number of apps listed. An icon option has been raised as well.

**Comment by benarent** [comment]
@stevenGravy When you say large, how many are we talking 1 - 25, 25 - 50, 50 - 100, 100 - 200, 200 - 500 etc..

**Comment by robcoward** [comment]
We could soon be exposing >80 apps (depending on the roles people have assigned) so 👍  for this request.

**Comment by alex-kovoy** [comment]
related #5448

**Comment by kimlisa** [comment]
closing in favor of #5448

**Comment by kimlisa** [comment]
closing in favor of #5448
