### ISSUE TITLE
Grafana dashboard supplied with HA reference Terraform has blank tables/entities

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4572]
**What happened**: The Grafana dashboard for "Teleport Health Stats" that we supply with our HA reference Terraform has some blank entries in it - looks like the queries either aren't valid for the specified metrics any more or there's been a breaking change to the InfluxDB queries.

![2020-10-16-135951__1625x1369__maim](https://user-images.githubusercontent.com/897821/96287942-03ad7d80-0fb9-11eb-92b9-3bba6e647bbc.png)

**What you expected to happen**: All items on the reference "Teleport Health Stats" dashboard should contain useful data.

The dashboard config is here: https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/ha-autoscale-cluster/assets/health-dashboard.json

As per https://github.com/gravitational/teleport/issues/2734, we should also migrate to using Prometheus directly rather than Telegraf.

**How to reproduce it (as minimally and precisely as possible)**: Set up a Terraform using https://github.com/gravitational/teleport/tree/master/examples/aws/terraform/ha-autoscale-cluster, load the Grafana dashboard (https://<url>:8443), log in with `admin` and the configured password (`TF_VAR_grafana_pass`) and look at the dashboard.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.4.0-rc.3 git:v4.4.0-rc.3-0-g32997e9ac go1.14.4`

**Comment by webvictim** [comment]
This could be done at the same time as #2734

**Comment by webvictim** [comment]
Same thing as https://github.com/gravitational/teleport/issues/5628

**Comment by pschisa** [comment]
This dashboard example used for load testing may be a decent alternative: https://github.com/gravitational/teleport/blob/master/assets/monitoring/health-dashboard.json
