### ISSUE TITLE
Web UI wraps long output(?)

### ISSUE THREAD

**Issue by pirogoeth** [gravitational/teleport#458]
Not quite sure what's going on here, but when using the web ui, longer output seems to get unnecessarily wrapped (I think?)

![screenshot](http://i.imgur.com/Wsizuew.png)

I am using an "older" version of Teleport (v0.2.0-beta.1.19+1ae47782147d26 git:1ae47782147d268fd19c19aa01bc5bdb546c59a9), so I'm not sure if you guys have fixed it in the meantime.

**Comment by kontsevoy** [comment]
@pirogoeth we see this too sometimes. Does this happen 100% of the time? Does resizing a window help?

**Comment by pirogoeth** [comment]
@kontsevoy It's kinda strange -- apparently it doesn't happen 100% of the time for me. It happens when I connect as root, but not when I connect as a different user. 

I just did some testing and apparently having LS_COLORS set fixes it...(??)

https://gist.github.com/pirogoeth/764a3fa02434c0e85d8dc72d05bb6302

**Comment by kontsevoy** [comment]
@pirogoeth yeah, we see this too every once in a while - also depends on a browser, OS and the available fonts. I doubt it will get fixed soon, it depends on the open source JS-based control we use. But we'll try, thank you!

**Comment by pirogoeth** [comment]
@kontsevoy :+1: thanks!

**Comment by kontsevoy** [comment]
I think we fixed this in 1.0.5
