### ISSUE TITLE
Add RBAC to OSS edition

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4581]
### Feature Request

Add role based access control to open source edition to improve user experience and increase open source adoption.

## Details

Teleport 5.1 when updated will add support for role based access controls. Some role options will be available in OSS, but others will be enterprise only.

The following options and features will remain in Enteprise only:

* `request_access` [Access requests](https://github.com/gravitational/teleport/pull/4573)
* `max_connections` [Fedramp AC control](https://github.com/gravitational/teleport/commit/ae2336dfd00cb7ba712e0885718691ee680f0353)
* OIDC / SAML SSO 
* FedRamp/FIPS mode

Write down RFD with a more detailed proposal

## Related

#3683

**Comment by klizhentas** [comment]
cc @benarent @russjones

**Comment by benarent** [comment]
Duplicate of https://github.com/gravitational/teleport/issues/4136.

I'll work on combining these into a RFD.

**Comment by klizhentas** [comment]
closing as a dupe
