### ISSUE TITLE
Implement hosted email access plugin

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#45969]
Integrations page currently redirects users to [documentation](https://goteleport.com/docs/admin-guides/access-controls/access-request-plugins/ssh-approval-email/) when they click on email plugin asking them to setup a self-hosted service:

<img width="517" alt="Screenshot 2024-08-28 at 9 53 27 AM" src="https://github.com/user-attachments/assets/1c531c49-0134-4cc3-82f1-3e223b74339b">

We should convert it to a hosted Mailgun/SMTP plugin that functions similarly to other hosted plugins. Together with hosted MS Teams being worked on in https://github.com/gravitational/teleport/issues/24495, it will complete the set of hosted access plugins we support.

## Success criteria

- [x] Users can setup hosted email integration via web UI.
- [x] Should support both Mailgun API key and SMTP server credentials like self-hosted plugin does.
- [x] Should be supported in both Cloud and self-hosted Teleport clusters.
- [x] Should support notification routing rules.
- [x] Product metrics are updated accordingly.
- [x] Should update documentation accordingly.

**Comment by bernardjkim** [comment]
Hosted email access plugin supported starting `v17.0.2`
