### ISSUE TITLE
Clean up shadow on resource icons

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#45966]
Some of our resource icons have a shadow that is getting cut off by the bounding box. It's only visible in the light theme.

For example, look at the top icon here: 

<img width="143" alt="image" src="https://github.com/user-attachments/assets/b5b604bb-102c-428a-bd67-c3a21da15076">

Or the application icon here:

<img width="93" alt="image" src="https://github.com/user-attachments/assets/1611f4ca-260b-46bb-94c5-bff052696b45">

**Comment by roraback** [comment]
Updated application, database, kubeserver, and server icons to eliminate shadows and [uploaded to Google Drive](https://drive.google.com/drive/folders/1p5D7wL-O3HfdjGIujM_ZKrj2gQgJSnbX?usp=drive_link). Easiest to find them if you sort by the modified date, in descending order.

![image](https://github.com/user-attachments/assets/70d092d5-5b05-46b1-ad3b-df121bdd43e1)
