### ISSUE TITLE
Implement new floating alerts (A.K.A. Shared/Notifications in Storybook)

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#45977]
[Floating Alerts (A.K.A. Shared/Notifications in Storybook):](https://www.figma.com/file/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?type=design&node-id=8919-1325&mode=design&t=lfboeNMENiqaZygH-4) _**Intents:**_ neutral, primary, danger, warning, success

**Comment by zmb3** [comment]
@bl-nero what's left for this one?

**Comment by bl-nero** [comment]
@zmb3 I intended to do some optional work here, but won't have time to this. Closing.
