### ISSUE TITLE
`TestKube` flakiness

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#45986]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/10603785318/job/29388916169

#### Relevant snippet

```
=== RUN   TestKube
    kube_integration_test.go:149: 
        	Error Trace:	/__w/teleport/teleport/integration/kube_integration_test.go:149
        	            				/__w/teleport/teleport/integration/kube_integration_test.go:171
        	Error:      	Condition never satisfied
        	Test:       	TestKube
--- FAIL: TestKube (61.77s)
FAIL integration.TestKube (61.77s)
FAIL integration

=== Failed
=== FAIL: integration TestKube (61.77s)
    kube_integration_test.go:149: 
        	Error Trace:	/__w/teleport/teleport/integration/kube_integration_test.go:149
        	            				/__w/teleport/teleport/integration/kube_integration_test.go:171
        	Error:      	Condition never satisfied
        	Test:       	TestKube
```

**Comment by tigrato** [comment]
`TestKube` spins a local kubernetes cluster using kind and creates a POD. The pod uses `nginx:alpine` image ([here](https://github.com/gravitational/teleport/blob/58269666caa342e73a9ea0684e82fc654ed58c2c/integration/kube_integration_test.go#L1913)) and it waits for the pod to become ready.
Lately, we started seeing several issues with GHA network where the image download takes an eternity and the 60s isn't enough.

**Comment by tigrato** [comment]
> Do we have any other options than pulling an nginx image from the public internet for every test?

Yeah, we can probably replace it with anything that we can pull from github registry. Not sure if we can build it and make it available to kind

**Comment by GavinFrazar** [comment]
```
=== RUN   TestKube
    kube_integration_test.go:157: 
        	Error Trace:	/__w/teleport/teleport/integration/kube_integration_test.go:157
        	            				/__w/teleport/teleport/integration/kube_integration_test.go:179
        	Error:      	Condition never satisfied
        	Test:       	TestKube
--- FAIL: TestKube (61.02s)
FAIL integration.TestKube (61.02s)
FAIL integration

=== Failed
=== FAIL: integration TestKube (61.02s)
    kube_integration_test.go:157: 
        	Error Trace:	/__w/teleport/teleport/integration/kube_integration_test.go:157
        	            				/__w/teleport/teleport/integration/kube_integration_test.go:179
        	Error:      	Condition never satisfied
        	Test:       	TestKube
```
https://github.com/gravitational/teleport/actions/runs/11186373071/job/31101273442?pr=47224 on master

**Comment by tigrato** [comment]
This is likely caused by the same issue. I need to replace the nginx image with any other container
