### ISSUE TITLE
Pasting content within Web SSH sessions not consistent with CLI

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4603]
### Description

**What happened**:

Pasting multi line content in a Web SSH session can result in different formatting then the original content.  Using `ssh` or `tsh ssh` does not have this issue.
Content being copied:
![image](https://user-images.githubusercontent.com/60704961/96736098-4214b500-138a-11eb-8497-bfc3f8adc2b1.png)

Result:
![image](https://user-images.githubusercontent.com/60704961/96736005-290c0400-138a-11eb-8d62-d3891ee8597c.png)

**What you expected to happen**:
Pasting content in a text editor within a web ssh session would be the same as a `ssh` or `tsh ssh` session.  

**How to reproduce it (as minimally and precisely as possible)**:
Open a web ssh session.
Copy a formatted set of text from a client machine terminal to the clipboard.  
```yaml
kind: role
metadata:
  name: access-plugin
spec:
  allow:
    logins:
    - access-plugin
    node_labels:
      '*': '*'
    rules:
```
Open a editor within the web session, `vi test.yaml`.  Paste the contents.

### Environment
- Teleport version (use `teleport version`):4.4.0
- Tsh version (use `tsh version`): 4.4.0
- User desktop: Ubuntu 20.04.1 LTS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Browser environment**

- Browser Version (for UI-related issues): Version 86.0.4240.111 (Official Build) (64-bit)

**Comment by russjones** [comment]
@stevenGravy Could this be your text editor?

**Comment by webvictim** [comment]
Steven and I tried to reproduce this on Slack back when he first reported it. it doesn't happen if he sets `set paste` in `vim` on the remote machine, IIRC.

**Comment by zmb3** [comment]
I was going to suggest `:set paste` here. This is a vim thing, not a Teleport thing. If it works with `tsh` that's probably because your terminal emulator (iTerm) has the smarts to detect this and fix it automatically.

See also: https://stackoverflow.com/questions/2514445/turning-off-auto-indent-when-pasting-text-into-vim
