### ISSUE TITLE
No makefile in linux/darwin 1.0.0 binary

### ISSUE THREAD

**Issue by Punkbob** [gravitational/teleport#461]
Just a heads up that the install instructions that tell you to use sudo make install, will fail as the compiled releases do not have a makefile, and are not structured like previous releases.

**Comment by kontsevoy** [comment]
ah, great catch. thanks.

**Comment by kontsevoy** [comment]
@Punkbob we've re-uploaded the tarballs. I haven't bumped the version up because 1.0 hasn't been publicly announced/released yet.
