### ISSUE TITLE
When I try to login to a teleport cluster via tsh it fails

### ISSUE THREAD

**Issue by Punkbob** [gravitational/teleport#462]
Works fine to login in via the webui but fails via tsh. I blew away /var/lib/teleport on all these hosts before upgrading to 1.0.0 as well as .tsh on the client's I've been using to test from, the error that it spits back its:

INFO[0019] Successfully authenticated with teleport.protenus.com:3023  file=client/api.go:805                                                                
INFO[0019] proxyClient.GetSites() returned: [{"name":"b895ca68-ec95-4619-999e-XXXXXXXXX","lastconnected":"2016-06-21T16:52:11.396720322Z","status":"online
"}]  file=client/client.go:109                                                                                                                               
DEBU[0019] Received a new set of keys from teleport.host:3023  file=client/api.go:831                                                                
DEBU[0019] checking host key of teleport.host:3023                                                                                                   
  file=client/keyagent.go:105                                                                                                                                
DEBU[0019] Successfully authenticated with teleport.host:3023  file=client/api.go:839                                                                
INFO[0019] proxyClient.GetSites() returned: [{"name":"b895ca68-ec95-4619-999e-XXXXXX","lastconnected":"2016-06-21T16:52:11.41834027Z","status":"online"
}]  file=client/client.go:109                                                                                                                                
INFO[0019] connecting to node: @b895ca68-ec95-4619-999e-XXXXXXX  file=client/client.go:173                                                              
dial tcp [fe80::103c:45ff:febb:f60b]:3025: connect: invalid argument                                                                                         
ERRO[0019] Failed connecting to cluster b895ca68-ec95-4619-999e-XXXXXXXX: ssh: subsystem request failed  file=client/client.go:156                       
Failed connecting to cluster b895ca68-ec95-4619-999e-XXXXXXXXX: ssh: subsystem request failed

**Comment by kontsevoy** [comment]
On a surface looks like IPv6 issue (which we do not yet support). We'll try to reproduce.

**Comment by Punkbob** [comment]
It also happens over IPv4

**Comment by kontsevoy** [comment]
do you have HTTPS certificate configured for the proxy? and if not, what happens if you specify `--insecure` flag to `tsh ssh`?

**Comment by kontsevoy** [comment]
Andrew, would you be willing to do a Goolge Hangout with us to help diagnose/reproduce the issue? Thanks.

**Comment by Punkbob** [comment]
Tried with the insecure flag still failed and will mess with it again this weekend to see if its something I did, but otherwise I'd be willing to set something up next week?

**Comment by kontsevoy** [comment]
@Punkbob  Sure. Ping me on ev@kontsevoy.com and I'll shoot you some times via email.

**Comment by Punkbob** [comment]
Resolved itself after a serious of reboots this week. No idea what was wrong still.
