### ISSUE TITLE
Bump X-term to 3.1.0  |  Windows + Firefox users can't see copy/paste options in context menu of Firefox

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4621]
### Description

**What happened**:
We bumped X-Term in 4.3, but we've a customer running into a copy / paste issue with Firefox and Windows that's been fixed in 3.1.0 https://github.com/xtermjs/xterm.js/pull/1253.

As @alex-kovoy suggested, now will be a good time to split out xterm versions https://github.com/gravitational/webapps/issues/92#issuecomment-637637485 

**Example without Copy and Paste Menu**
![image](https://user-images.githubusercontent.com/559288/96887126-1f8da500-1439-11eb-938c-cb3bb90eb691.png)

### Environment
- Teleport version (use `teleport version`): 4.3.7

**Browser environment**
- Firefox ( 71 ~ 82 )

**Comment by jacobb84** [comment]
Looks like this is still an issue in Teleport 8.0.7 with Firefox 95.  Are there plans to bump the version in version 8 or 9 of teleport?

**Comment by zmb3** [comment]
xterm.js is way past 3.1.0 now

**Comment by benarent** [comment]
confirmed, we are now on 4.1.15 https://github.com/gravitational/webapps/blob/master/packages/teleport/package.json#L22
