### ISSUE TITLE
Create redirects for old documentation

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4631]
## Summary

The documentation refactor should not break existing [link references](https://github.com/gravitational/teleport/search?l=Go&q=https%3A%2F%2Fgravitational.com%2Fteleport%2Fdocs%2F&type=code)

We can't update all versions of teleport binaries referencing the docs. We can create redirects from the old documentation to new URLs.

**Comment by webvictim** [comment]
This is kinda the same thing as https://github.com/gravitational/teleport/issues/3605

Going forward we should create and use a redirection short link service for all documentation URLs. This way we can automatically check all redirects in one place and flag an alert to fix any that break.

**Comment by klizhentas** [comment]
Implemented
