### ISSUE TITLE
Add 4.4 to list of supported versions in faq

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4633]
### Description

**What happened**:
4.4 is not listed with support and release dates in faq.
https://gravitational.com/teleport/docs/faq/#which-version-of-teleport-is-supported

**What you expected to happen**:

New version like 4.4 is added.

**Comment by webvictim** [comment]
We should put a note in https://github.com/gravitational/teleport/blob/master/docs/preflight.md as a reminder

**Comment by inertial-frame** [comment]
This needs to be updated for 6.1+
