### ISSUE TITLE
Prevent Teleport event handler crash when ingesting audit Log larger than 1 MB

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#46352]
What would you like Teleport to do?
When the following condition is experienced, report a warning message indicating that a session could not be processed because of file size. Continue with the next event-id to process. 

`ERRO   Error ingesting Audit Log err:rpc error: code = Unknown desc = db.session.postgres.statements.parse event <event-id> is 1.1 MiB and cannot be returned because it exceeds the maximum response size of 1.0 MiB event-handler/events_job.go:96`

What problem does this solve?
The Teleport event handler process will crash and cannot move past this condition without manual intervention. 

If a workaround exists, please include it.
Stop the teleport event handler. Delete the storage directory tracking files. Recreate the id file with an entry of the troublesome event-id, and restart the teleport event handler process. It will pickup the next event after the troublesome event.

**Comment by zmb3** [comment]
@r0mant @capnspacehook is this issue resolved with the event trimming work that we recently completed?

**Comment by capnspacehook** [comment]
It should be, new 'db.session.postgres.statements.parse' events will be truncated if they are too large

**Comment by capnspacehook** [comment]
This was fixed in https://github.com/gravitational/teleport/pull/45931. Teleport versions 16.4.3, 15.4.19, and 14.3.32 and later versions contain this fix. If you are still experiencing issues after upgrading with audit log events growing too large, please open a new issue and we'll take a look at it. Thanks!
