### ISSUE TITLE
Typos in User Manual regarding description for Linux download link and support for single SSH jumphost.

### ISSUE THREAD

**Issue by thetuber** [gravitational/teleport#4636]
## Summary
Description for the link to download the Linux binary references the Mac version.

Duplicate item regarding support for single SSH jumphost.

### Audience
All

### Location
Existing User Manual.

**Comment by thetuber** [comment]
From the User Manual, under "Installing tsh":

    Linux Users: Download Mac Teleport Binary. Includes tsh

Should be:

    Linux Users: Download Linux Teleport Binary. Includes tsh

**Comment by thetuber** [comment]
See PR #4637

**Comment by webvictim** [comment]
Thanks!
