### ISSUE TITLE
DynamoDB backed event view is limited on 5K events

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4640]
### Description

**What happened**:

No events are returned in DynamoDB event view after 5K events. Fix the backend pagination

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by russjones** [comment]
This will be fixed in Teleport 6.2 https://github.com/gravitational/teleport/milestone/55.
