### ISSUE TITLE
ARM/ARM64 packages

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4641]
### Feature Request
We should have arm/arm64 RPM/DEB packages available for download.

### Motivation
At the moment installing Teleport on a Raspberry Pi or other ARM device is still a very manual process. It'd be good to offer a convenient package format that people using these devices can leverage for installation.

### Potential issues
Our download page will get busier with all these extra builds being displayed, plus the build process will need to run more parallel jobs. We also need to store more builds for each release.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by benarent** [comment]
Once completed we should also support ARM Container Builds https://github.com/gravitational/teleport/issues/3384

**Comment by tokyowizard** [comment]
Looking forward to ARM64 support. We'd like to try it on [Amazon's EC2 T2g instances](https://aws.amazon.com/about-aws/whats-new/2020/09/announcing-new-amazon-ec2-t4g-instances-powered-by-aws-graviton2-processors/).

**Comment by webvictim** [comment]
The PR adding arm64 tarballs has been merged, but is pending support being added to the download portal for showing those builds. Once it's ready, I'll release Teleport 4.3.8 and 4.4.2 with arm64 builds available.

ARM/ARM64 RPM/DEB packages are a little way off yet.

**Comment by webvictim** [comment]
arm64 tarballs for 4.4.2 are out: https://gravitational.com/teleport/download

**Comment by didiersmith** [comment]
These binaries don't work for me on my Jetson AGX:

```
$ teleport --help
teleport: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by teleport)

$ uname -a
Linux AGX-AU-699-82888-0004-400L0 4.9.140-tegra #1 SMP PREEMPT Fri Oct 16 12:25:00 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux

$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

I was able to work around this by making the modification suggested by @gclawes here: https://github.com/gravitational/teleport/issues/3384#issuecomment-735456862

Following that change, a `make docker` produces valid binaries in build/.

```
$ ls -lht ./build
total 133M
-rwxr-xr-x 1 deep-thought deep-thought 59M Jan  5 11:58 teleport
-rwxr-xr-x 1 deep-thought deep-thought 34M Jan  5 11:58 tsh
-rwxr-xr-x 1 deep-thought deep-thought 41M Jan  5 11:58 tctl
$ ./build/teleport version
Teleport v5.0.0-dev git:v4.4.0-alpha.1-322-g6f52dd6ee-dirty go1.15.5
```

**Comment by webvictim** [comment]
@didiersmith Thanks for the information. I've added the AGX to the compatibility matrix I'm building here: https://github.com/gravitational/teleport/issues/4754#issuecomment-749587441

**Comment by gclawes** [comment]
The arm64 packages in the `deb https://deb.releases.teleport.dev/ stable main` repository appear to be out of date.  The latest available is `6.2.17`.
```
gclawes ~ $ sudo apt update
Hit:1 http://security.debian.org/debian-security bullseye-security/updates InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease                                                                                    
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease                                                                            
Hit:4 https://deb.releases.teleport.dev stable InRelease                                                                                 
Hit:5 http://download.opensuse.org/repositories/home:/danielthompson/Debian_Testing ./ InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
gclawes ~ $ apt-cache policy teleport
teleport:
  Installed: (none)
  Candidate: 6.2.17
  Version table:
     6.2.17 500
        500 https://deb.releases.teleport.dev stable/main arm64 Packages
```

**Comment by gclawes** [comment]
Actually, this appears to be an issue with all platforms.  `6.2.17` is the only version available in the repository.

**Comment by webvictim** [comment]
See #8166

**Comment by gclawes** [comment]
Thanks!

**Comment by espadolini** [comment]
@webvictim we can close this, right?

**Comment by webvictim** [comment]
Yes!
