### ISSUE TITLE
kubernetes application discovery images are missing

### ISSUE THREAD

**Issue by Venture200** [gravitational/teleport#46426]
Expected behavior:
Images should exists

Current behavior:
Images are missing

Bug details:
- Teleport version
15.4.16
- Recreation steps
docker pull public.ecr.aws/gravitational/teleport-distroless:17.0.0-dev

- Debug logs
What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview public.ecr.aws/gravitational/teleport-distroless:17.0.0-dev
Error response from daemon: manifest for public.ecr.aws/gravitational/teleport-distroless:17.0.0-dev not found: manifest unknown: Requested image not found

I am trying to install teleport-kube-agent helm chart but images are missing which are in values.yaml

**Comment by tigrato** [comment]
`17.0.0-dev` is a development tag that is never pushed because it's under active development.
Should checkout release branch `branch/v16` and work from there and never from master as images are never pushed.

**Comment by tigrato** [comment]
<img width="2053" alt="Screenshot 2024-09-10 at 14 17 31" src="https://github.com/user-attachments/assets/8407c9f8-52be-4434-978b-86a2bd308afd">

You should be able to see a red banner at the top indicating it's a dev release
