### ISSUE TITLE
Can't connect to teleport-connect 16.1.8 or higher in fish shell

### ISSUE THREAD

**Issue by Hasoo** [gravitational/teleport#46473]
Expected behavior:
SSH connection successful

Current behavior:
![Screenshot 2024-09-11 at 9 00 58 PM](https://github.com/user-attachments/assets/20186567-7c63-413b-acae-870b33c14100)

Bug details:
mac Sonoma 14.6.1
fish 3.7.1
teleport-connect 16.1.8 or higher

The screenshot error is from version 16.2.2, and after downgrading, I found that the issue exists up to version 16.1.8.
there is no issue in zsh shell.

**Comment by gzdunek** [comment]
Thank you for the report! I can confirm the issue, this [PR](https://github.com/gravitational/teleport/pull/46631) should fix it.
