### ISSUE TITLE
GCP discovery guide doesn't tell you to add serviceAccountUser role which is needed

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#46476]
## Applies To

https://goteleport.com/docs/enroll-resources/auto-discovery/servers/gcp-discovery/#step-26-configure-iam-permissions-for-teleport

## Details

The docs need to tell you to add the `roles/iam.serviceAccountUser` role to the service account created in step 2, otherwise the user will be unable to associate the service account with the Teleport discovery instance. It doesn't appear in the list.

Command needed:

```console
gcloud projects add-iam-policy-binding <project-id> \
--member="serviceAccount:<sa-name>@<project-id>.iam.gserviceaccount.com" \
--role="roles/iam.serviceAccountUser"
```

## How will we know this is resolved?

Follow the guide start to finish and have things work out of the box.

## Related Issues

None evident so far.

**Comment by atburke** [comment]
The docs already tell you to add `iam.serviceAccounts.actAs`, `iam.serviceAccounts.get`, and `iam.serviceAccounts.list` to the custom role. Is there an extra benefit to using `roles/iam.serviceAccountUser` instead?
