### ISSUE TITLE
Add support Microsoft Windows

### ISSUE THREAD

**Issue by xaircore** [gravitational/teleport#465]
Add support to Microsoft Windows OS

**Comment by kontsevoy** [comment]
@xaircore do you have a Windows client use case or both? Adding support to `tsh` may be feasible, but `teleport` server probably won't happen, it's outside of our expertise/business.

**Comment by jdc0589** [comment]
@kontsevoy I'd love to see official builds of the `tsh` client for windows and osx.

**Comment by kontsevoy** [comment]
We're working on #481 but we're not adding Windows support for the server component.
