### ISSUE TITLE
Follow Terraform release rules

### ISSUE THREAD

**Issue by seboudry** [gravitational/teleport#46527]
Hi!

Teleport terraform provider repository dont't follow [Terraform release rules](https://developer.hashicorp.com/terraform/registry/providers/publishing#manually-preparing-a-release).

Especially on archive name:
* actual : `terraform-provider-teleport-v14.3.3-linux-arm64-bin.zip`
* format : `terraform-provider-{NAME}_{VERSION}_{OS}_{ARCH}.zip`
* wanted : `terraform-provider-teleport_14.3.3_linux_arm64.zip`

This have an impact on tooling like hermitcrab (a provider network mirror service).
https://github.com/seal-io/hermitcrab/issues/15

**Comment by zmb3** [comment]
This is not something we're likely to change at this point. It's unfortunate that we don't follow the naming conventions recommended for publishing to HashiCorp's registry, but any change now would likely break a bunch of existing automation.
