### ISSUE TITLE
Create a WebInterface for roles creation

### ISSUE THREAD

**Issue by Zathiel** [gravitational/teleport#46612]
What would you like Teleport to do?

Having a possibility to have a User role creation interface 

What problem does this solve?

Mistake in roles creation and a better experience 

If a workaround exists, please include it.

**Comment by iamlucas13** [comment]
> What would you like Teleport to do?
> 
> Having a possibility to have a User role creation interface
> 
> What problem does this solve?
> 
> Mistake in roles creation and a better experience
> 
> If a workaround exists, please include it.

I agree, this feature is kindly needed.

**Comment by zmb3** [comment]
This is already in progress.

**Comment by Zathiel** [comment]
hey @zmb3 

Hope you are fine !

Thanks for this  hint

Any PR or something i can follow up

**Comment by zmb3** [comment]
Not yet, but we'll keep this issue open so that you can stay subscribed here for updates.

**Comment by bl-nero** [comment]
I have just realized I forgot to attach PRs to this issue; my apologies. I'll mention this issue in all the following PRs to keep it as a tracking item. For now, here's the list of ones that have already been merged, to keep things in order: https://github.com/gravitational/teleport/pull/47100, https://github.com/gravitational/teleport/pull/47189, https://github.com/gravitational/teleport/pull/47253, https://github.com/gravitational/teleport/pull/47674, https://github.com/gravitational/teleport/pull/47803, https://github.com/gravitational/teleport/pull/47992

**Comment by Zathiel** [comment]
Hey @bl-nero 

Thanks for the feedback 

Wich milestone should we expect the final things released if you already know ?

**Comment by zmb3** [comment]
@Zathiel we're planning for a 17.1 release, but it's still early so that is subject to change.

**Comment by Zathiel** [comment]
Hi @bl-nero any new PR ongoing for this ?

@zmb3 thanks for the planning can you keep me in touch also

Regards

**Comment by zmb3** [comment]
This is still slated for 17.1. You're welcome to monitor our upcoming releases page for updates - it's not feasible for us to provide personal updates to any individual interested in a feature.

**Comment by Zathiel** [comment]
@zmb3 thanks for the fast reply

Im not asking for individual update but linked PR on this issues to have a better overview on this

hope that make sence 

Regards
