### ISSUE TITLE
MariaDB support?

### ISSUE THREAD

**Issue by robertsilen** [gravitational/teleport#46629]
Does Teleport support MariaDB? Any reason not to mention it on the README?

**Comment by stevenGravy** [comment]
Teleport supports MariaDB for database access. Please see https://goteleport.com/docs/enroll-resources/database-access/enroll-self-hosted-databases/mysql-self-hosted/ as an example. Not all features are included in the README. You should be able to find that and more in the docs. Please also consider joining the slack community for questions like this.

**Comment by robertsilen** [comment]
Cool, thank you for the clarification and further advice! Much appreciated. I made a PR suggestion to add MariaDB to the readme where other databases are listed too. Hope that is reasonable :) See https://github.com/gravitational/teleport/pull/46665
