### ISSUE TITLE
Disturbing error message when running the install-node script

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#4663]
When running the auto-install script, I see the following errors:

```bash
INFO [PROC]      Generating new host UUID: 8a2ff5e7-f8af-43f4-a9b3-d6b059877a1f. service/service.go:576
INFO [PROC:1]    Joining the cluster with a secure token. service/connect.go:349
ERRO [AUTH]      Failed to register through auth server: invalid character '<' looking for beginning of value; falling back to trying the proxy server auth/register.go:126
INFO [PROC]      Node has obtained credentials to connect to cluster. service/connect.go:377
```

> ERRO [AUTH]      Failed to register through auth server: invalid character '

Gus thinks that it's connecting to an auth server and if it gets a web response it logs that error and tries the proxy mode connection instead which is expected behavior.

If this error is expected behavior, we need to change it to INFO and provide a better message then  `invalid character '<' looking for beginning of value; falling back to trying the proxy server auth/register.go:126` as this is the first thing a user sees when trying out Teleport cloud.

**Comment by benarent** [comment]
I noticed this while running Teleport 5.0 Beta.  It also seems to repeat itself multiple times. I wonder if we can just show it once during startup. 

How's this? It's a little less alarming. 

```diff
ERRO [AUTH]      Failed to register through auth server: invalid character '<' looking for beginning of value; falling back to trying the proxy server auth/register.go:126
+INFO [AUTH]    Unable to register directly to teleport auth: attempting connection through proxy auth/register.go:126
```

**Comment by webvictim** [comment]
As I mentioned on Slack, it might be worth Teleport doing some internal logic where it says:
- if the port being connected to is 443 or 3080 (common proxy ports), try proxy connection logic first, followed by auth
- if the port being connected to anything else, try auth connection logic first, followed by proxy

We should also only raise an `ERROR` after both connection methods have failed.

**Comment by klizhentas** [comment]
@russjones a customer just hit the same issue and was confused by it. Easy to fix and will reduce support load.

**Comment by benarent** [comment]
+1 @GregChase ran into this issue again today.

**Comment by andrejtokarcik** [comment]
In my attempts to reproduce this I encountered a differently worded message:
```
ERRO [AUTH]      "Failed to register through auth server: 404 page not found\n; falling back to trying the proxy server" auth/register.go:126
```
I imagine that by changing the level/logic for this message the present issue should be resolved as well. However, to be sure, could any of the original reporters confirm they're seeing the different message too?
