### ISSUE TITLE
`teleport configure` should include app

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4665]
### Feature Request
When running `teleport configure` we should include 'app' in Tokens to make the quickstart easier. 

```diff
#
# Sample Teleport configuration file
# Creates a single proxy, auth and node server.
#
# Things to update:
#  1. ca_pin: Obtain the CA pin hash for joining more nodes by running 'tctl status'
#     on the auth server once Teleport is running.
#  2. license-if-using-teleport-enterprise.pem: If you are an Enterprise customer,
#     obtain this from https://dashboard.gravitational.com/web/
#
teleport:
  nodename: pop-os
  data_dir: /var/lib/teleport
  auth_token: e26caba19611540d173b686de94477f283f6fdb0b71337b1
  auth_servers:
  - 127.0.0.1:3025
  log:
    output: stderr
    severity: INFO
  ca_pin: sha256:ca-pin-hash-goes-here
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  tokens:
  - proxy,node:e26caba19611540d173b686de94477f283f6fdb0b71337b1
+  - proxy,node,app:e26caba19611540d173b686de94477f283f6fdb0b71337b1
```

### Motivation
Improving TAA Quickstart

### Who's it for?
OSS User, Pro, Enterprise

**Comment by webvictim** [comment]
I think the problem with this is that `app_service` defaults to off, and regular `proxy,node` setups (which are both enabled by default) wouldn't be able to join with a `proxy,node,app` token.

I guess we could change the example config from `teleport configure` to specifically enable `app_service` if we want?

**Comment by benarent** [comment]
As we are building out more defined product support, I'm inclined to provided a per product `teleport configure`, for people getting quickly setup.. I need to think about this more. I'll remove RJ for now.

**Comment by zmb3** [comment]
`teleport configure` does support apps now, though it doesn't generate static tokens as they are insecure. I'm going to close this old issue.
