### ISSUE TITLE
Clean up the 2FA registration fields (Google Authenticator)

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#4666]
The record which we create in Google Authenticator is confusing, especially when user name is email.

![image](https://user-images.githubusercontent.com/7816406/97669140-d8676b80-1a59-11eb-849c-932613483f35.png)

![image](https://user-images.githubusercontent.com/7816406/97668971-7eff3c80-1a59-11eb-8782-0f2838feae59.png)

I suggest we:

1. Remove the port
2. Replace the `teleport` title with the hostname 
3. Display the user name at the bottom.

See how it's done in OKTA

![image](https://user-images.githubusercontent.com/7816406/97668805-27f96780-1a59-11eb-9fa9-0586be55d8cb.png)

@benarent

**Comment by zmb3** [comment]
Not planning on making changes here given the desire to deprecate TOTP (see #20725)
