### ISSUE TITLE
Audit Log doesn't recognize   static_host_user.create

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#46673]
Expected behavior:

Static user audit log events are recognized.

Current behavior:

Static user events not recognized. 

![image](https://github.com/user-attachments/assets/e2a997dd-23e4-4cda-87aa-3bc3b11688f3)

![image](https://github.com/user-attachments/assets/d7a8aad6-4d32-41f7-85f4-378d5e92a099)

Bug details:
- Teleport version: 16.3.0
- Recreation steps

Add a static user config.

**Comment by zmb3** [comment]
Are you sure your proxy server is on 16.3.0? I'm looking at the code and I don't see anything missing.

**Comment by stevenGravy** [comment]
> Are you sure your proxy server is on 16.3.0? I'm looking at the code and I don't see anything missing.

Yes, 16.3. Same audit unknown issue on another self-hosted 16.3 to confirm.

![image](https://github.com/user-attachments/assets/496f92c9-177e-40c6-9b83-0ca1ba2d321d)

**Comment by zmb3** [comment]
Looks like the backport of #46246 was done incorrectly.

**Comment by zmb3** [comment]
Fixed by #46697
