### ISSUE TITLE
`TestCARenewer` flakiness

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#46755]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/10926425068/job/30330249649#step:6:2216

#### Relevant snippet

```
    ca_test.go:368: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/db/ca_test.go:368
        	Error:      	Condition never satisfied
        	Test:       	TestCARenewer
        	Messages:   	failed to wait the CA download
```

**Comment by zmb3** [comment]
Also caught by nightly flake detector: https://github.com/gravitational/teleport.e/actions/runs/10938757044/job/30367551771
