### ISSUE TITLE
Can OIDC be considered to become an open source (not exclusively enterprise) feature in the future?

### ISSUE THREAD

**Issue by queglay** [gravitational/teleport#4676]
I've just come across this project and I'd like to consider it for another OSS IAC project I am working on.

### Feature Request
I'd love to explore using Teleport with Hashicorp Vault OSS, but without Open ID available in the open source variant, its not an option for me.
 
### Motivation
Combining Teleport with Hashicorp Vault for other open source IAC projects would be a wonderful thing!

### Who's it for?
OSS User

Thanks if you can consider this at some point in the future.

**Comment by benarent** [comment]
Hi @queglay, Thank you for getting in touch. For OSS users we've a few options, we currently provide Github as an SSO provider https://gravitational.com/resources/guides/github-sso-provider-kubernetes-ssh/ . You can also create local users that'll enforce 2FA using hardware or app tokens.  

Thank you for checking out Teleport and I hope this can work for you.

**Comment by TheAnachronism** [comment]
I agree that OIDC should also be available in the open-source version.
SSO is essentials for cloud tools today, and limiting your users to either none or just one provider can often be a reason people turn away from your product.
This movement goes so far, that there's even a [wall of shame](https://sso.tax/) for companies which consider SSO as only enterprise level. There are multiple rants online that go about the issue with SSO restricted to enterprise [one example](https://www.reddit.com/r/msp/comments/lryldl/sso_should_be_a_standard_feature_for_all_saas/)

I really do hope, that SSO can be made open source for teleport and other products that have similar licensing.

**Comment by dounoit** [comment]
yeah - this is a total show stopper - its very unfortunate. please reconsider :-)

**Comment by Smartich0ke** [comment]
I would also love for this to be available in the community edition. Security is a basic necessity, not something you lock away behind paywalls.

**Comment by MajorTwip** [comment]
Bump

**Comment by artichoked1** [comment]
Given this has been raised multiple times by several users over the years, is there any chance of this decision being re-considered?

**Comment by fuad00** [comment]
Bump. shame on you

**Comment by unknownconstant** [comment]
Genuine feedback, not a rant:

I can't test your software and I'm not going to reach out to you to evaluate it formally so I won't show up in your stats. However, I do exist and I'm lost business.

I have to jump through corporate hurdles to test things formally, but I can't test it at home either as the "community edition" blocks basic functionality. Teleport looks like a good fit for us, but being unable to test it, and having no pricing info I have no motivation to hand over personal info for a short lived trial - I don't know what it is I'm trialling!

For a security product, identity synchronisation is an absolute requirement, github isn't a reasonable option.
