### ISSUE TITLE
Enable staggered automatic upgrades on Teleport Cloud

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#46788]
### What would you like Teleport to do?

Introduce the ability for Teleport Cloud customers to manage multiple maintenance schedules for agent updates. Specifically, allow different groups of resources/servers to have unique update frequencies and schedules.

The ability to define more than one update channel could also be a feasible path forward.

### What problem does this solve?

Staggering updates across critical infrastructure is a best practice to implement. For reference, consider the recent Crowdstrike incident that created a wide-spread problem due to a bad update.

The current limitation for Teleport Cloud customers only supports a single maintenance schedule via the Web UI, and there is only one non-user-configurable channel available.

This feature enhances control over agent updates, offering a mechanism to isolate potential issues to test servers before applying the same updates to production servers.

### If a workaround exists, please include it.

A self hosted version endpoint external to Teleport Cloud could be implemented so certain agents would follow it instead of the main update channel on the teleport.sh tenent.

Documentation links:
- [Setting up Automatic Agent Updates](https://goteleport.com/docs/upgrading/automatic-agent-updates/#step-14-enable-automatic-agent-upgrades)
- [Assigning version channels](https://goteleport.com/docs/upgrading/automatic-agent-updates/#optional-assign-the-version-served-by-the-version-server)

#### Example Scenario:
- Test servers are set to update every Monday at 02:00 UTC.
- Production servers are set to update once every two weeks on Sundays at 03:00 UTC.

or

- Test servers use the stable/cloud channel
- Prod servers use a new stable/prod channel that is updated after the stable/cloud channel gets its new version

**Comment by zmb3** [comment]
This is actively being worked on. Changes to the cloud platform are tracked in the cloud repo (see https://github.com/gravitational/cloud/issues/10289).

I don't think we need an issue in OSS Teleport to track work that's already being tracked elsewhere.

**Comment by zmb3** [comment]
Additionally, we also have this request at #30825, so I'll close this as a duplicate.
