### ISSUE TITLE
Clean up log level checks in lib/services/role.go

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#4681]
Checks like https://github.com/gravitational/teleport/blob/abe2b607d5a5dba30120f6f46ddb2642dcee87a1/lib/services/role.go#L1781 are redundant, calling `log.Debugf(...)` handles log level internally.
There's also minimal performance impact - the log message isn't parsed/formatted unless log level matches up.

**Comment by zmb3** [comment]
This is already fixed.
