### ISSUE TITLE
SSO connectors example/default role should be admin vs admins

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4682]
### Feature Request
When setting up a SSO connector it default role is `admins` but the cluster has an `admin` role. This can often catch people out. 

```diff
kind: github
version: v3
metadata:
  name: new_github_connector
spec:
  # Github OAuth app client ID
  client_id: <client-id>
  # Github OAuth app client secret
  client_secret: <client-secret>
  # Github will make a callback to this URL after successful authentication
  # cluster-url is the address the cluster UI is reachable at
  redirect_url: "https://<cluster-url>/v1/webapi/github/callback"
  # connector display name that will be appended to the title of "Login with"
  # button on the cluster login screen so it will say "Login with Github"
  display: Github
  # mapping of Github team memberships to Gravity cluster roles
  teams_to_logins:
    - organization: <github-org>
-      team: admins
+     team: admin
      logins:
-        - "admins"
+        - "admin"
```

### Motivation
One less issue when setting up a connector.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by benarent** [comment]
@kimlisa Do you know where these are set? Is it imported or via a webapps resource? 
![image](https://user-images.githubusercontent.com/559288/97933909-ee5e8000-1d28-11eb-9895-ca2fca04c920.png)

**Comment by webvictim** [comment]
https://github.com/gravitational/webapps.e/blob/master/teleport/src/cluster/components/AuthConnectors/templates/github.yaml
