### ISSUE TITLE
Unable to access request a resource which I already have access to Teleport Connect

### ISSUE THREAD

**Issue by 4durban** [gravitational/teleport#46880]
The expected behavior was the previous one, the previous to the update where you switched the Resource Access Request to the Resource view. What I expected is that when I select "Access Request -> Show Requestable Resources" everything should disappear and only appear the resources that I can Request Access to (that was the previous behavior).  But now when I select "Show Requestable Resources" resources that I already have access to are the ones that appear. 

![image](https://github.com/user-attachments/assets/5c36fe0d-64c6-4b05-a478-de6c47f4af66)

I guess the issue comes from the fact that a particular user is able to access that resource with two different roles, a normal user and a privileged one (that's the one that is trying to Access Request to), this was working fine, and if I do it from the web it still works fine. So when the user tries to Request Access from Teleport Connect to the same resource but with a different role is not able to request so because he already has access to that cluster with a non-privileged user.

I could do a "Role Access Request" but that's not the behavior that we want, since it grants access to a complete role, not a particular resource.

The fact that from the web is working fine makes me think that this is some kind of bug from the Teleport Connect app, which is something important in our environment. 

As you can see in this screenshot from the web site is working fine:

![image](https://github.com/user-attachments/assets/0bd30876-69bf-4f89-a565-fb8457b48740)

The issue appeared since you changed the resource view to that switch. The previous one, the one that had to different checkboxes to select, in 16.1.0 it was working:

![image](https://github.com/user-attachments/assets/652b46b8-d665-4734-a100-6d60c9e8047a)

But after that we have found no way to request access to a resource you already have access with a different role. I must say that in the web only works because you have not deleted the section "Access Requests -> New Access Request" and you can Access Request a resource from there, but the resource view is also bugged. 

![image](https://github.com/user-attachments/assets/85e89aa3-0918-4fd2-853b-70577aec0d52)

And the same applies to all the other resources, kubernetes is just one of them and the issue that we faced. I think is something critical since it makes Access Requests unusable for us in Teleport Connect, which is one of the main points of use for our users. And please before removing a section, which you did in Teleport Connect please leave some time for users to test, because if issues like this happen you leave the user with no option to "rollback" or user the legacy way until is solved.

**Comment by 4durban** [comment]
I even can give you the call that is being done wrong.

When you login the request being done is right and you see the proper resources. The first one is the one done when you login, the second one is when you switch back to only accesible resources, and the putting the switch back to Requestable, as you can see the third and the first one should be the same, since the resources shown should be the same. There is no point in showing all resources when I specifically say to only show requestable resources, that produces the bug I told you about, not being able to Access Request to resource you already have access to:

![image](https://github.com/user-attachments/assets/b81f407a-f9d3-4b5c-bf52-f14ba9e33922)

The issue is with the includedResourceMode=all it should not be done this call with "all" it should be done with "includedResourceMode=requestable" as the first one for this to work.

The change should not be that difficult and until it is not done the issue is not going to disappear. I must say that @webvictim tag this as Teleport-Connect but the issue also affects the Web UI so please relabel this in order to inform that the issue is both with Teleport Connect and Web UI.

The better part is that from the Web UI the tab "Access Request" is not removed (as per 16.2.0) so resources can be requested from there, but in Teleport-Connect is indeed removed. But the moment that you remove it from the Web UI the Access Request are going to be unusable. I think that it is something that should be dealt with as soon as possible.

**Comment by avatus** [comment]
As of 16.2.1, you can request access to resources you already have access to, you can select them using the checkbox on the resource item and then select "Request Access"

![Image](https://github.com/user-attachments/assets/a3c319cd-d15a-41a8-8fd7-787fba0f8794)
