### ISSUE TITLE
Teleport OSS - LDAP and other OIDC than GitHub

### ISSUE THREAD

**Issue by gecube** [gravitational/teleport#46944]
Good day!

I want to revive the question here: #1641 

It sounds ridiculous that in OSS (free) version teleport supports only local users or GitHub OIDC. It means that company that wants to adopt teleport should write some middleware or patch the teleport code. Both options are working and necessary tooling could be found on internet. It means that people that don't want to buy a corporate license of teleport (like we did buy it because of another nice tooling like approval workflows and compliance matters!!!!) WON'T DO IT ANYWAY staying on the OSS (free) version of teleport. But it would be beneficial to Teleport as a company to make Teleport solution more widely used - because of supporting community and involving more and more users and customers into it. 

So I am kindly asking to consider options to add
* direct integration with LDAP user catalogue (let's say from FreeIPA or openldap)
* let users to use different than GitHub OIDC providers

SAML could be available ONLY in enterprise as "really" "enterprise" option (integration with AD and other stuff).

**Comment by zmb3** [comment]
This is not something we are considering at this time.

**Comment by denny-webb** [comment]
The Wall of Shame
https://sso.tax/
