### ISSUE TITLE
role cannot unmarshal number

### ISSUE THREAD

**Issue by kgtw** [gravitational/teleport#4699]
### Description

**What happened**:

Using a role with node labels of `account: 12345678` causes teleport to throw errors, even though this is valid yaml.

```
json: cannot unmarshal number into Go value of type []string
```

**What you expected to happen**:

Node labels to accept any valid yaml.

**How to reproduce it (as minimally and precisely as possible)**:

Create a role with node labels `xyz: 123`

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v4.3.7git:v4.3.7-0-g3687d398b go1.13.2
- Tsh version (use `tsh version`): Teleport v4.3.5 git:v4.3.5-0-g122349e78 go1.13.2
- OS (e.g. from `/etc/os-release`): 

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
 
**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by webvictim** [comment]
YAML's type casting is very annoying sometimes. The short-term workaround is of course to quote the string (`account: "12345678"`) to avoid this, but we'll take a look at automatically casting any non-string values to strings to avoid this.
