### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [gravitational/teleport#4700]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://github.com/gravitational/teleport/blob/master/web/README.md

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by webvictim** [comment]
Thanks for the check, I've raised a PR to fix it.

If you're looking for feedback, one thing that would be more useful to provide in automatic comments like this would be a [direct link to the file and line number where the error is found](https://github.com/gravitational/teleport/blame/master/README.md#L124). This would have saved me having to go and navigate Github's forced automatic Markdown rendering to go and find the link.

**Comment by MrCull** [comment]
@webvictim many thanks. this is a brand new project and feedback is very much appreciated :)

I have linked your comment to an issue in my repo where someone else has provided similar feedback.
