### ISSUE TITLE
Provide device trust list for user in Account Setting

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#47034]
What would you like Teleport to do?

Provide the list of devices a user has associated for device trust.

What problem does this solve?

A user could confirm matching a list for `tsh device asset-tag` matches to their list of trusted devices.  Otherwise it can be hard to know what devices are registered for your user w/o being an admin.  Users typically migrate every few years to new computers so they could confirm which devices are missing.

If a workaround exists, please include it.

A user would have to ask a admin to get the list of devices associated with their user.

**Comment by avatus** [comment]
Closed with https://github.com/gravitational/teleport.e/pull/5557
