### ISSUE TITLE
Ability to dynamically add and remove apps under Kubernetes

### ISSUE THREAD

**Issue by Nuru** [gravitational/teleport#4705]
### Feature Request
We would like to be able to add and remove applications to/from the Teleport Application Access Proxy (AAP) without editing/altering `teleport.yaml` under Kubernetes. There are a 2 ways we can see this working and they are not mutually exclusive.

1. AAP could function as a Kubernetes [Ingress Controller](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/). This would allow us to add an application by adding an Ingress, which is the normal Kubernetes way, and would automatically integrate with [external-dns](https://github.com/kubernetes-sigs/external-dns) and [cert-manager](https://github.com/jetstack/cert-manager) and other Kubernetes services.
1. AAP could find applications and services via Kubernetes Annotations, similar to how [external-dns does](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/faq.md#how-do-i-specify-a-dns-name-for-my-kubernetes-objects).

Almost equally important is the ability to have applications immediately removed from the dashboard. In the current (5.0.0.beta.9) implementation, updating the list of apps under Kubernetes involves creating a new pod to read the new ConfigMap, which leaves the dashboard showing a duplicate list of apps (old then new) for some time. 

### Motivation
The fundamental design goal of Kubernetes is that every application/service fully describes its requirements and no other services need to be adjusted except by the Resources deployed by the application/service. We deploy multiple versions of apps (feature branches, release candidates) via CI/CD and they should automatically appear and disappear from the AAP dashboard as they are deployed and removed. 

### Who's it for?
Anyone using Teleport AAP with Kubernetes

**Comment by chifu1234** [comment]
@russjones What does the label q2 means? Thanks :D

**Comment by programmerq** [comment]
This was added in Teleport 14.0.0

https://goteleport.com/docs/ver/14.x/application-access/enroll-kubernetes-applications/get-started/

See also: https://github.com/gravitational/teleport/issues/25538 and https://github.com/gravitational/teleport/blob/branch/v14/rfd/0135-kube-apps-discovery.md
