### ISSUE TITLE
Ability to act as Identity Provider for Grafana

### ISSUE THREAD

**Issue by Nuru** [gravitational/teleport#4708]
### Feature Request
[Grafana](https://grafana.com/oss/grafana/) has support for user accounts and roles, with users having their own configurable preferences and history, and roles granting/limiting access to certain actions. It would be ideal for Teleport Application Access Proxy (AAP), having already authenticated a user and assigned a role (#4706), to communicate that information to Grafana in a trusted way, eliminating the need for an alternate authentication system.

AAP already generates [JSON Web Tokens](https://jwt.io/) (JWT) and Grafana already accepts JWT for identification and roles as part of its [Generic OAuth2 support](https://grafana.com/docs/grafana/latest/auth/generic-oauth/#generic-oauth-authentication), including relatively arbitrary [parsing of the JWT](https://grafana.com/docs/grafana/latest/auth/generic-oauth/#jmespath-examples) to pull information of it. 

What is missing is the ability to register AAP's signing key as being trusted by Grafana, and, since JWT are bearer tokens that cannot be revoked, and therefore should have limited life spans (less than 10 minutes), a way to automatically refresh the JWT. These mechanisms are, of course, built in to OAuth2, so rather than attempt to extend Grafana's basic proxy authentication support to accept JWT (https://github.com/grafana/grafana/pull/9166), it might be better (and would certainly be more fully under Gravitational's control) to expand Teleport to be a minimal OAuth2 server. It need not implement the full OAuth2 spec (it would be sufficient to only implement the Authorization Code Flow for Confidential Clients, along with the standard server information APIs such as the token introspection endpoint), but could probably integrate with an open-source OAuth2 library such as [go-oauth2](https://github.com/go-oauth2/oauth2) with no more than the same level of effort as creating a custom solution.

### Motivation
Teleport is a server that provides authentication and access control. The more it implements standard IdP protocols, the greater its utility and wider its scope, making it a more compelling solution. 

Grafana is a very widely used tool (and just one example of one that can use the widely implemented OAuth2 protocol), but without the ability of AAP to function as an IdP for Grafana, users will have to log in twice, once to AAP and then again to Grafana, and administrators will have to configure users twice, once for AAP and once for Grafana, which will be especially annoying if AAP supports the organization's SSO but Grafana does not.

### Who's it for?
Pro, Enterprise

**Comment by benarent** [comment]
We've added JWT Support to Grafana https://github.com/grafana/grafana/pull/29995 You can try this with Grafana 8 beta. 
https://grafana.com/grafana/download/8.0.0-beta2?pg=get&plcmt=selfmanaged-box1-cta1
