### ISSUE TITLE
Add link in docs inviting readers to submit an issue, or correction to documentation on the github

### ISSUE THREAD

**Issue by GregChase** [gravitational/teleport#4715]
## Summary
In documentation for many OSS projects, there are links inviting readers to raise issues, or make a pull request to improve documentation.  Often they just make small fixes such as grammar or improve errors in examples.

### Audience
Advanced users

### Location
Top or bottom of each document?  

"See a problem with the docs or have an idea?  Raise an issue | Make a Pull Request"

**Comment by klizhentas** [comment]
Implemented
