### ISSUE TITLE
Web Login Success URL returns success message even when not in authentication process

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4718]
### Description

**What happened**:

If a user cut and pastes the Login Success URL they always receive a success message.  This occurs in a incognito session to separate from the authentication browser session.

**What you expected to happen**:

A user would receive a error or info message  that this is used for an authentication process.

**How to reproduce it (as minimally and precisely as possible)**:
Use the `web/msg/info/login_success` reference in a teleport proxy web address:
ex: `https://teleport.example.com:3080/web/msg/info/login_success`

### Environment
- Teleport version (use `teleport version`): 4.4.1
- Tsh version (use `tsh version`): 4.4.1
- OS (e.g. from `/etc/os-release`): ubuntu

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Browser environment**

- Browser Version (for UI-related issues): Chrome

**Comment by webvictim** [comment]
Is this actually an issue? Surely the only way anyone would get the URL is by logging in successfully...

**Comment by stevenGravy** [comment]
@webvictim  More of a experience issue that someone could copy the URL and think it actually did something. To me it's a confirmation message in a request, not just static content.
