### ISSUE TITLE
RDS Discover flow error `database cluster <db-cluster> has no instance`

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#47197]
Expected behavior:
Aurora clusters with zero instances should be skipped

Current behavior:
`database fetch error: database cluster <db-cluster> has no instance` is returned while listing databases preventing the flow.
https://github.com/gravitational/teleport/blob/7a6dbcbafa6ed260fabb83c59894648ea6f361b9/lib/integrations/awsoidc/listdatabases.go#L224-L237

Bug details:
- Teleport version: v16
- Recreation steps: Create a Aurora cluster. Delete the instances without deleting the cluster.
- Debug logs:

`aws rds describe-db-clusters --region us-west-1 --db-cluster-identifier <db-cluster-id>` shows empty `"DBClusterMembers": [],`
`aws rds describe-db-instances --region us-west-1 --filters Name=db-cluster-id,Values=<db-cluster-id>` is also empty

**Comment by GavinFrazar** [comment]
If there are no instances then there is no database to connect to, right?

**Comment by greedy52** [comment]
> If there are no instances then there is no database to connect to, right?

yes. based on this discovery code, it won't register any database too:
https://github.com/gravitational/teleport/blob/71d5f6f19b04ce4d897537a8b2c1c09c982e4e73/lib/srv/discovery/common/database.go#L593-L597

this is a such weird state. RDS shouldn't report `available` status.
