### ISSUE TITLE
U2F support

### ISSUE THREAD

**Issue by Omeryl** [gravitational/teleport#472]
This is just a feature request, but I primarily use U2F for two factor. Would it be possible to do this, especially since both the browser (Firefox with Addon, Native in Chrome) and local access with Golang is possible?

**Comment by kontsevoy** [comment]
Will keep this open for future OSS contributors.

**Comment by jcj83429** [comment]
Since there is no go library to interface with U2F keys yet, would it be acceptable to implement the commandline client side with the libu2f-host C library or the u2f-host program included in libu2f-host?

**Comment by kontsevoy** [comment]
@jcj83429 this would be a nice feature so we're not closing the issue, but keeping it open for 3rd party contributors.

**Comment by jcj83429** [comment]
@alchar, @bibekaur, @jdahiya and I are university students and we will be adding U2F support to Gravitational Teleport for a computer security course project.

**Comment by kontsevoy** [comment]
@jcj83429 awesome! Thanks for your help.

**Comment by jcj83429** [comment]
For U2F login, would it be acceptable for the authentication to fail before requesting a signature from the U2F key if the password entered is incorrect or should we wait until we get a signature from the U2F key before we announce whether the password was correct?

**Comment by Omeryl** [comment]
Failing before the token is the pattern of Google, etc. so I think it's fine.

**Comment by klizhentas** [comment]
consider it implemented
