### ISSUE TITLE
Docker quickstart

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4720]
## Summary

I was almost able to run teleport locally in docker with two steps:

```
$ docker run --entrypoint=teleport quay.io/gravitational/teleport:4.4.2 configure > teleport.yaml
$ docker run -v $(pwd)/teleport.yaml:/etc/teleport/teleport.yaml -p 3080:3080 -p 3022:3022 quay.io/gravitational/teleport:4.4.2
```

I think it's cool. Why not add it for users in some quickstarts, esp for application proxy.

**Comment by webvictim** [comment]
There's a quickstart guide here: https://gravitational.com/teleport/docs/quickstart-docker/

Also a `docker-compose` file which handles config generation etc: https://github.com/gravitational/teleport/blob/master/docker/teleport-quickstart.yml
