### ISSUE TITLE
`create_host_user_default_shell` seems to be ignored

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#47283]
When using `create_host_user_default_shell: /bin/bash` with host user creation, Teleport should respect that option.

The current behavior seems to be that it ignores `create_host_user_default_shell` and goes with the `SHELL` value as set in `/etc/default/useradd`.

This was observed on a 16.4.2 cluster with a 16.4.2 node, with a user in a single role that has `create_host_user_default_shell` set.

When Teleport creates the user, `useradd` logs the following:

```
Oct 07 10:13:40 myhost useradd[2351677]: new group: name=ubuntu, GID=1007
Oct 07 10:13:40 myhost useradd[2351677]: new user: name=ubuntu, UID=1003, GID=1007, home=/home/ubuntu, shell=/bin/sh, from=none
Oct 07 10:13:40 myhost useradd[2351677]: add 'ubuntu' to group 'teleport-keep'
Oct 07 10:13:40 myhost useradd[2351677]: add 'ubuntu' to shadow group 'teleport-keep'
```

This happens whether the value is set to `bash` or `/bin/bash`. The `/etc/shells` file lists `/bin/bash`.

**Comment by ravicious** [comment]
@eriktate I think the `shell` variable might be always empty and we change it only if it isn't empty. This means, I think, that we end up never using the option provided by a role.

https://github.com/gravitational/teleport/blob/9cd659e1aa69cac03c822d524b54f04754f5e471/lib/services/access_checker.go#L1063-L1065

**Comment by eriktate** [comment]
> [@eriktate](https://github.com/eriktate) I think the `shell` variable might be always empty and we change it only if it isn't empty. This means, I think, that we end up never using the option provided by a role.
> 
> [teleport/lib/services/access_checker.go](https://github.com/gravitational/teleport/blob/9cd659e1aa69cac03c822d524b54f04754f5e471/lib/services/access_checker.go#L1063-L1065)
> 
> Lines 1063 to 1065 in [9cd659e](/gravitational/teleport/commit/9cd659e1aa69cac03c822d524b54f04754f5e471)
>  if shell != "" { 
>  	shell = hostUserShell 
>  }

This was exactly the problem, should have been `shell == ""` instead :facepalm: This also probably should've had some test coverage to begin with (which it does now) :sweat_smile: Thanks for figuring this out @ravicious !
