### ISSUE TITLE
Display auth version and cluster URL on the cluster list view

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#4734]
It seems that we fixed the bug with performance issues while fetching the cluster URLs and auth version. Now we need to put it back.

Essentially revert back what we removed from this PR: https://github.com/gravitational/webapps/pull/148
![image](https://user-images.githubusercontent.com/7816406/98414956-4e676600-204a-11eb-933b-114f15a6a851.png)

**Comment by russjones** [comment]
Fixed in #6049.
