### ISSUE TITLE
Add release notes to documentation similar to go

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4741]
Take a look at those release notes:

https://golang.org/doc/go1.15#commonname

Nice, table of contents with links to the doc and expanded changelog.

let's add a section in our documents with release notes for 5.0 following similar structure

**Comment by stevenGravy** [comment]
Nice @klizhentas , I would also like a easy way to navigate to the major release info from the minor version release notes.  So when 5.0.1 comes out it's easy to see the 5.0.0 one.  Maybe there's a way to include all the notes for a Major release together?

**Comment by ptgott** [comment]
It looks like we added `changelog.md` [after this comment thread](https://github.com/gravitational/teleport/commits/4fe45ab350a43d43a7d04f027d8111b9ba8a2175/docs/5.0/changelog.md?browsing_rename_history=true&new_path=docs/pages/changelog.mdx&original_branch=master), so I'm not sure if we've resolved this issue or not. @stevenGravy @klizhentas is there any more work we need to do on this?

**Comment by klizhentas** [comment]
@ptgott I think we solved it with 

https://goteleport.com/docs/changelog/
