### ISSUE TITLE
Support `automountServiceAccountToken` in `teleport-cluster` helm charts

### ISSUE THREAD

**Issue by rohithrrao** [gravitational/teleport#47594]
**What would you like Teleport to do?**
`teleport-custer` helm charts should support support setting the value of `automountServiceAccountToken`

**What problem does this solve?**
Disabling ServiceAccount token mounts is a common [security](https://aws.github.io/aws-eks-best-practices/security/docs/pods/#disable-serviceaccount-token-mounts) [best](https://aws.github.io/aws-eks-best-practices/security/docs/pods/#disable-serviceaccount-token-mounts) [practice](https://docs.lacework.net/compliance/policies/lacework-global-749) and also a requirement for some production environments.

**If a workaround exists, please include it.**
Create your own ServiceAccount with `automountServiceAccountToken` set to `false`. But it increases the maintenance burden on Helm chart users.

**Comment by hugoShaka** [comment]
Please note that this will not change anything for the pods as every deployment from the chart already disables automatic SA creds mount when projected volumes are supported.
