### ISSUE TITLE
Better errors with proxy connecting to auth service in Web/HTTP portion

### ISSUE THREAD

**Issue by Omeryl** [gravitational/teleport#476]
So, this is a weird one.

I was testing around and trying to add a user, immediately the web proxy was telling me the token was expired. Looking at tctl shows it wasn't. Looking finally at debug output showed that it was simply unable to connect to the auth service. I suspect there are a few other circumstances that might cause errors messages that don't make sense, so can we get a cursory check through everything to make sure the errors returned make sense? In this case a early check to see if the auth service is even reachable would be a great UI improvement.

Thanks!

**Comment by kontsevoy** [comment]
@Omeryl not a "weird one" at all. Great catch, thanks!

**Comment by kontsevoy** [comment]
merging with #511
