### ISSUE TITLE
Audit log entry shows years span for k8s exec session length

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4761]
### Description

**What happened**:
After ending a k8s exec session the log showed a 2020 year length for the session which was only seconds or minutes.

![image](https://user-images.githubusercontent.com/60704961/98591721-a1d1f200-229e-11eb-835d-a79f710aaaa4.png)

![image](https://user-images.githubusercontent.com/43280172/98594198-2dd91f00-2289-11eb-8bdf-baca36d615e1.png)

**What you expected to happen**:

Match to the time length of the session.  

**How to reproduce it (as minimally and precisely as possible)**:

Connect a teleport instance to a k8s cluster and open a session.  This was a external teleport instance that uses a kubeconfig configuration to connect to a EKS cluster.

### Environment
- Teleport version (use `teleport version`): 4.4.4
- Tsh version (use `tsh version`): 4.4.4

**Comment by stevenGravy** [comment]
@kimlisa @alex-kovoy  fyi

**Comment by alex-kovoy** [comment]
the session_start field is not populated somewhere.

**Comment by kimlisa** [comment]
https://github.com/gravitational/teleport/blob/branch/4.4/lib/kube/proxy/forwarder.go#L657
start time is missing for both `session.start` and `session.end` events

![image (1)](https://user-images.githubusercontent.com/43280172/98598245-06855080-228f-11eb-8c34-b02a4064bf46.png)

**Comment by webvictim** [comment]
It looks like `time` is set OK in the `session.start` event but `session.start` isn't set in `session.end`?
