### ISSUE TITLE
Teleport enterprise does not load license properly

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#47764]
### Expected behavior:
- teleport loads the license from /var/lib/teleport/license.pem
- if it fails to load the license, it prints an actionable error

### Current behavior:
- teleport without a configuration file does not try to read the license from `/var/lib/teleport/license.pem`
- teleport does not respect the `--debug` flag and only shows `INFO` logs
- teleport swallows the real error and tells me 
  ```
  ERROR: initialization failed
  # 	auth server requires a valid license file to start, please set the correct license_file path under auth_service section in your teleport 
  config or put the license into the default search location at /var/lib/teleport/license.pem
  ```
- as soon as I create `/etc/teleport.yaml` everything starts to work

### Bug details:
- Teleport version 16.4.3 Enterprise
- Recreation steps:
  - get an enterprise build and a valid license file
  - run `teleport start --debug` without a config file in `/etc/teleport.yaml`
- Debug logs

**Comment by zmb3** [comment]
Similar to #24954
