### ISSUE TITLE
Teleport Auth Service allows names to have a slash `/` but tctl cannot delete them

### ISSUE THREAD

**Issue by coltonparsons-vgs** [gravitational/teleport#47838]
## Expected Behavior
Either `/` would be forbidden in entry names, or `tctl` would allow these resources to be deleted.

## Current Behavior
A variety of scenarios allow entries to be created with forward-slashes in their names, but tctl cannot properly reference them by name.

Specific instances of this have been filed and addressed, e.g.:
* https://github.com/gravitational/teleport/issues/9107
* https://github.com/gravitational/teleport/issues/10576

But the issue continues to exist in the general case.

For my specific situation, it happens when using `tctl lock` on a root cluster. The attached leaf clusters automatically create locks with `name: <root-cluster>/<lock-name>` which cannot be subsequently deleted. https://github.com/gravitational/teleport/issues/33619 covers a different aspect of this issue, but does not mention the `/` is what makes the locks un-deletable.

## Bug Details
- Teleport version: `Teleport v15.4.18 git:v15.4.18-0-gf0d8629 go1.22.7`
- Recreation steps: Run `tctl lock ...` on a trusted cluster.
- Debug logs: difficulty getting these, as locks don't seem to propagate to leaf clusters after restarting Teleport (might be a separate bug?)

**Comment by zmb3** [comment]
This was recently fixed.
