### ISSUE TITLE
App mode missing

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4789]
The "app" mode is not documented in Teleport CLI

```
teleport start --help is not showing it
```

In this case the existence of teleport start --roles=app can only be found by looking into the code, No mention in the docs either

Same for `tokens add`

**Comment by kontsevoy** [comment]
Specifically, when I run `teleport start --help` and looking at this line, and not seeing it:

```
  -r, --roles            Comma-separated list of roles to start with [proxy,node,auth]
```

Also, Application Access is a big deal, so in the output of `teleport start --help` I would include an example too, right now it's too SSH heavy (two examples of `--roles=node`, let's swap one for `--roles=app`).
