### ISSUE TITLE
ls command doesn't work with different OS users

### ISSUE THREAD

**Issue by jaxxstorm** [gravitational/teleport#479]
I'm trying to do an `ls` command with tsh on a remote proxy:

```
tsh --user lbriggs --proxy teleport_host ls
```

However, it seems to want to do an SSH handshake as my currently logged in user?

```
access denied to login "Lee" when connecting to : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by jaxxstorm** [comment]
I did notice from #408 that it's possible to override this with`TELEPORT_LOGIN` env var, which makes it work:

```
export TELEPORT_LOGIN=lbriggs; tsh --user lbriggs --proxy beld-teleport-1.dapt.to ls
```

it would be nice if there was a `~/.tsh/config` file I could use where I could set this permanently.

**Comment by woohgit** [comment]
You can pass the `--login lbriggs` to our tsh command.

**Comment by kontsevoy** [comment]
correct.
