### ISSUE TITLE
Windows server

### ISSUE THREAD

**Issue by camile-forth** [gravitational/teleport#47919]
What would you like Teleport to do?

to add this ressources

What problem does this solve?

to connect with windows ressoursces

If a workaround exists, please include it.

**Comment by zmb3** [comment]
Hi there, can you be a bit more specific about what you're looking for?

**Comment by zmb3** [comment]
Teleport does support connecting to Windows servers. Without more information about what you're trying to do, this is not actionable. Feel free to reopen if you can provide more details.
