### ISSUE TITLE
2FA for logging into different clusters

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4801]
### Feature Request
Provide a 2FA challenge to users in the CLI and web when they login to different clusters.  

### Motivation
Having multiple leaf clusters provides a potential large amount of resources available to users. This adds security as a user navigates across resources in a enterprise. 

### Who's it for?
OSS User, Pro, Enterprise

**Comment by zmb3** [comment]
Closing as not planned. If additional MFA is desired, per-session MFA can be enforced via leaf cluster RBAC.
