### ISSUE TITLE
The resource card in Connect lacks a shadow when hovered

### ISSUE THREAD

**Issue by gzdunek** [gravitational/teleport#48065]
In Connect there is no shadow:
![Image](https://github.com/user-attachments/assets/b7c809c1-6fb3-452e-b81c-1eddbfc23157)

Web UI works fine:
![Image](https://github.com/user-attachments/assets/5af240f4-1f61-4e3b-93e8-9e125630087d)

**Comment by gzdunek** [comment]
It looks like Electron 33.x broke it. After downgrading to 33.2, the shadow works fine. 
I thought maybe Chromium had something to do with it, but it doesn't seem to. Electron 33.x comes with Chromium 130. Locally I have Chrome 131 and it works fine there (I also tried Electron 34 which comes with Chromium 132 - no success).
I didn't find an issue about this problem, I think we need to open one and provide a test case.

**Comment by ravicious** [comment]
We can ship 17.0.0 without this being fixed, AFAIK it's just this place?
