### ISSUE TITLE
[v14] external audit storage results in `NoncurrentVersionExpiration action must be a positive integer`

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#48155]
When running `teleport integration configure externalauditstorage --bootstrap ...` command to enable external audit storage, it fails with the following error:

```
ERROR: setting lifecycle configuration on S3 bucket 
    operation error S3: PutBucketLifecycleConfiguration, https response error StatusCode: 400, RequestID: aaa, HostID: bbb, api error InvalidArgument: 'NewerNoncurrentVersions' for NoncurrentVersionExpiration action must be a positive integer
```

It looks like this some issue was originally introduced on branch/v15 before 15.0.0, but was fixed by https://github.com/gravitational/teleport/pull/37068.

It wasn't backported to branch/v14 at that time, but the same bug was later introduced in #39490.

It looks like backporting #37068 would be sufficient to fix it for branch/v14 too.

**Comment by nklaassen** [comment]
@rosstimothy the bug was introduced in v15 by a dependency update, v14 was still on the older version of aws-sdk-go-v2 and the fix wasn't relevant or even possible, this was an `int` vs `*int` issue with the update. marco later updated the depency in v14 but missed the fix

**Comment by nklaassen** [comment]
sure, backport is up here https://github.com/gravitational/teleport/pull/48179
