### ISSUE TITLE
Time restriction functionality with role request

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport#4820]
### Feature Request
A customer shared they would like more functionality around approval workflows regarding setting a time restriction for a role once granted. 

For example once a user request a role and it is approved, they are able to use that role for whatever defined amount of session time. 

### Motivation
For this customer they do not want to create fine grained roles because administering those roles is rather difficult and hard to find boundaries on the permission. For them they are finding it is best to create more coarse privileged levels, but granting them for a very fine session time so they can control who is really using the role right now (if production issue or issue occurs immediately, then can track who did what).

### Who's it for?
OSS User, Pro, Enterprise

**Comment by russjones** [comment]
@benarent Is this a request for access during certain hours (for example 9AM - 5PM)?

**Comment by zmb3** [comment]
@jakule @r0mant this was fixed with the new `max_duration` option, right?
