### ISSUE TITLE
Better Create Role UX

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#4825]
When creating a role via Web UI, it's unclear what resources I am giving access to. I would expect that the role template would list all currently available resources with their verbs so I do not need to use documentation to figure it out.

Also, consider adding several templates: `admin`, `restricted`, `server access only` to pick from.

New users have zero sense what below role is for.

![image](https://user-images.githubusercontent.com/7816406/99091973-92082580-259e-11eb-9e44-4b95b08eaa0d.png)

**Comment by zmb3** [comment]
Closing in favor of #46612
