### ISSUE TITLE
Access requests review requests

### ISSUE THREAD

**Issue by wolfjudge** [gravitational/teleport#48279]
What would you like Teleport to do?

**To preserve all of the Access Requests on the Reviewed tab of Access Requests page**

What problem does this solve?

**Going through Audit events to search for all the Access Request and compare IDs in Audit logs to server names and wasting time going through multiple pages to get a simple info that all ISO 27001 certified companies need to have when auditor comes in and wants to check on Access Requests.**

**Comment by zmb3** [comment]
Thanks for the issue. We are already tracking this at https://github.com/gravitational/teleport.e/issues/4860 (internal link).
