### ISSUE TITLE
trusted clusters: server doesn't support provided key type

### ISSUE THREAD

**Issue by woohgit** [gravitational/teleport#483]
Hey,

I created a trusted cluster setup. Followed all steps and I'm stuck now. I connected 1 node to the tst-cluster. The main cluster does not have any nodes, it's just the "main database" actually.

The apapai user in theory is allowed to login to the tst-cluster  I can list the connected nodes on the tst-cluster using the main cluster as a proxy

```bash
 tsh --proxy=main-cluster --user=apapai --login=apapai clusters                                      
Cluster Name     Status
------------     ------
main             online
tst-cluster      online
```

```bash
$ tsh --proxy=main-cluster --cluster=tst-cluster --user=apapai --login apapai ls
Node Name                       Node ID                                  Address                 Labels
---------                       -------                                  -------                 ------
i-0135f37cc51a3bc4a     65939ba3-1e70-4ac2-a7ed-b9fcb5a80316     xxx.xxx.xxx.xxx:3022     
```

```bash
# tctl auth ls
CA keys for the local cluster tst-cluster:

CA Type     Fingerprint
-------     -----------
user        b4:d0:a6:57:65:1b:b7:ea:c1:bc:4f:75:45:6a:d8:77
host        b4:23:2b:13:8b:73:34:3e:e1:f4:36:d5:5b:22:51:0c

CA Keys for Trusted Clusters:

Cluster Name     CA Type     Fingerprint                                         Allowed Logins
------------     -------     -----------                                         --------------
main             user        46:a4:44:cf:81:6d:e8:a7:e5:e1:47:2f:b4:51:7f:1a     apapai
main             host        a5:1f:39:35:8e:a8:e2:43:e1:18:f2:c5:71:07:f9:21     N/A
```

```bash
# tctl users ls
User       Allowed to login as
----       -------------------
apapai     root,ubuntu
```

But when I want to connect to it, I get this error:

```
$ tsh ssh --proxy=main-cluster --cluster=tst-cluster --user=apapai ubuntu@i-0135f37cc51a3bc4a
access denied to login "ubuntu" when connecting to i-0135f37cc51a3bc4a:3022: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

On the node the logs are the following:

```
INFO[0009] [::]:3022 accepted connection from xxx.xxx.xxx.xxx:46264  file=sshutils/server.go:156
INFO[0009] conn(xxx.xxx.xxx.xxx:46264->yyy.yyy.yyy.yyy:3022, user=ubuntu) auth attempt with key ssh-rsa f0:20:d7:b2:22:49:21:03:5e:f8:e6:50:ff:7c:3e:39  file=srv/sshserver.go:458
WARN[0009] server doesn't support provided key type      file=srv/sshserver.go:469 fingerprint=ssh-rsa f0:20:d7:b2:22:49:21:03:5e:f8:e6:50:ff:7c:3e:39 local=yyy.yyy.yyy.yyy:3022 remote=xxx.xxx.xxx.xxx:46264 user=ubuntu
INFO[0009] [::]:3022 accepted connection from xxx.xxx.xxx.xxx:46266  file=sshutils/server.go:156
INFO[0010] conn(xxx.xxx.xxx.xxx:46266->yyy.yyy.yyy.yyy:3022, user=ubuntu) auth attempt with key ssh-rsa-cert-v01@openssh.com 8e:e5:67:43:c3:1d:b8:f0:ed:57:70:7c:6f:f1:01:86  file=srv/sshserver.go:458
INFO[0010] server.EmitAuditEvent(auth)                   file=srv/sshserver.go:442
```

I even tried with this configuration, but I get the same error, even if `apapai` is allowed to login as `root` and `ubuntu`. The users `root` and `ubuntu` are exist on the target system.

```
tctl auth ls
CA keys for the local cluster tst-cluster:

CA Type     Fingerprint
-------     -----------
user        b4:d0:a6:57:65:1b:b7:ea:c1:bc:4f:75:45:6a:d8:77
host        b4:23:2b:13:8b:73:34:3e:e1:f4:36:d5:5b:22:51:0c

CA Keys for Trusted Clusters:

Cluster Name     CA Type     Fingerprint                                         Allowed Logins
------------     -------     -----------                                         --------------
main             user        46:a4:44:cf:81:6d:e8:a7:e5:e1:47:2f:b4:51:7f:1a     ubuntu,root,apapai
main             host        a5:1f:39:35:8e:a8:e2:43:e1:18:f2:c5:71:07:f9:21     N/A
```

Any hints? What's wrong? Maybe it's with the auth_servers variable is wrong here?

What should be the `auth_servers` value on the tst-cluster if it's a trusted cluster? The IP of the main-cluster or could it be the `127.0.0.1`?

My goal is to have only 1 place where we store the users: it's the main-cluster. The tst-cluster should allow logins via the main-cluster and I only want to add users to the main-cluster. I though using this trusted-cluster setup this could be achieved, but maybe I misunderstood something.

I would like to allow only the teleport user `apapai` to be able to login to `tst-cluster` joined nodes as `ubuntu` or `root`, and no  one else added to the `main-cluster`. Is this possible with the trusted-clusters setup?

Please advice,

**update**:

I created a new node and joined to the main cluster. Via the Web UI I can log-in and connect to it as "root", but from command line it fails with the same error message. What am I doing wrong?

The command I tried now is:

```
 tsh --proxy=main-cluster --user=apapai --login=apapai --cluster=main ssh root@nagios-ops-01
access denied to login "root" when connecting to nagios-ops-01:3022: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by woohgit** [comment]
**update 2**:

Meanwhile I found the problem. An old credential was cached, so I did another login and everything started to work as expected.

**Comment by alperaydemir** [comment]
if it's not too much trouble, can you attach your configuration for both clusters? I'm trying to setup the same thing but got stuck with basically not nowing if the `tst-cluster` nodes should point to `main-cluster`s auth server or not. basically `tst-cluster` does not get listed when I bring it up.

**Comment by woohgit** [comment]
It was my bad. I deleted and re-added the user papai and it did not ask a new login, it cached my old one, so that was the reason why it wasn't working. By logging in again to the main cluster everything started to work. Probably the best would be to re-configure my session to live only max 1 hr.
