### ISSUE TITLE
`trusted_cluster` resource renames itself, breaking subsequent updates

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#48309]
### Expected behaviour:

- As a user I create a resource called `clusterA` while my remote cluster real name is `clusterA.example.com`
Either I have a name mismatch error when I create the resource, or the resource name stays `clusterA`

### Current behaviour:

- The resource is renamed from `clusterA` to `clusterA.example.com` in the backend
- I don't have a unique identifier to get the resource anymore
- If I edit the role mapping and apply again for `clusterA` it silently drop my changes

### Bug details:
- Teleport version v16.4.2
- Recreation steps: create a TC resource whose name is different than the root cluster name
- Debug logs

### Additional notes

- this is blocking TC support in the operator

**Comment by bernardjkim** [comment]
Hey @hugoShaka, I've written up a small patch to add resource name validation for trusted_clusters in https://github.com/gravitational/teleport/pull/49169. However, is there any concern for potentially breaking automation for some users that have been using an invalid trusted_cluster name up until now?
