### ISSUE TITLE
Error message is not display in web UI session records for invalid SID

### ISSUE THREAD

**Issue by avatus** [gravitational/teleport#48395]
Expected behavior:
An error should be displayed if an invalid session id is placed into the URL.

Current behavior:
A "valid" but empty screen is shown.
![Image](https://github.com/user-attachments/assets/30effde3-bccd-4c57-a91b-7955e96f96fc)

If you remove any of the other query params, you get an error saying they are invalid.

Bug details:
- Teleport version - 17
- Recreation steps - Copy a valid session recording URL and update the sid to something invalid (123). 
- Debug logs
The logs do display a session wasn't found
```
Original Error: *interceptors.RemoteError a recording for session 40c-ad27-446d-b121-ef338c340 was not found
Stack Trace:
        github.com/gravitational/teleport/api@v0.0.0/client/client.go:2448 github.com/gravitational/teleport/api/client.(*Client).StreamSessionEvents.func1
        runtime/asm_arm64.s:1223 runtime.goexit
User Message: a recording for session 40c-ad27-446d-b121-ef338c340 was not found] player/player.go:200
```

**Comment by zmb3** [comment]
I can confirm the error is being sent to the web UI, so the bug appears to be in the web UI.

![Image](https://github.com/user-attachments/assets/d787b799-5226-41d6-b653-a4f8b0b15f99)
