### ISSUE TITLE
WebUI should list trusted-cluster joined nodes too

### ISSUE THREAD

**Issue by woohgit** [gravitational/teleport#484]
## Original Problem

The WebUI lists the joined nodes which is cool.
Is it possible to list the trusted-cluster joined nodes too? That would be pretty useful.

Or at least the ability to select a `cluster` from the Web UI, and after the selection only the selected cluster related nodes should be listed.

## UI Polish

* Lets have "cluster" dropdown to be horizontally aligned with the "search" field on every host.
* When creating an SSH session Teleport Web UI currently does not check for errors (and because of that it shows "disconnected" inside the terminal when something goes wrong).

**Comment by kontsevoy** [comment]
@woohgit yes that will be useful, it's in our to-do list.

**Comment by kontsevoy** [comment]
## Behavior change

When a user clicks on "SSH" button to open a new terminal, he must be presented with a popup showing an error.

## UI changes:

Nodes tab:
```
Nodes               Cluster: [cluster-name]    [search]	  <-- on the same "line"
Cluster-name:

* If we have two or more clusters, show them as-is.
* If we have only 1 cluster, and its name is a GUID, show the proxy host name (from the URL)
```

Sessions tab:
Merge active + archived sessions into the same table, with active sessions shown on top.
```
Sessions              [date-picker]         Cluster: [cluster-name]    [search]   <-- on the same "line"


Session ID	Login				Node			Started	(UTC)			Duration
----------------------------------------------------------------------------------------------------------------
[play] xxxxxxx	ekontsevoy [127.82.10.1]	master [127.1.1.5]	02/31/2016 02:14:11 	  	00:12:00
		klizhentas [10.0.12.1]		
----------------------------------------------------------------------------------------------------------------
```

**Comment by kontsevoy** [comment]
This is now in master.
