### ISSUE TITLE
Provide a way to tell tctl to ignore /etc/teleport.yaml

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4841]
I can see a need for me personally to run `tctl` against remote clusters from my laptop, which also happens to have `/etc/teleport.yaml` present because it's used for Teleport testing. 

This might be a bit of an edge case, but I'm wondering whether we should provide some way to explicitly specify that `tctl` should use my `tsh` credentials and ignore the Teleport config file for cases like this. The alternative is always that I can just write some kind of `tctl-remote` wrapper for myself that hides the existence of `/etc/teleport.yaml`. Maybe I can just explicitly specify the identity file to use.

I'm not sure how common this would be outside of the company.

_Originally posted by @webvictim in https://github.com/gravitational/teleport/pull/4783#discussion_r521059059_

**Comment by webvictim** [comment]
New issue as requested by @russjones

**Comment by webvictim** [comment]
This request is especially important because you now can't run `tctl` against a remote cluster if you have an `/etc/teleport.yaml` file on your machine. I just had to rename the config to be able to use `tctl` with my `~/.tsh` credentials 🙄

**Comment by webvictim** [comment]
Got hit by this again a few times lately...

**Comment by a-palchikov** [comment]
I'm thinking that there should be no defaults and that `tsh` should just set up the environment for the rest of the session - like the recent suggestion with `tsh env`. Another option is a configuration file but not a central location but something you can control - analogy is git with its `.git` directory as hard defaults but having the ability to use configuration file when provided on command line.

If the defaults are hard ingrained and difficult to get rid of, still make them opt-in with some flag - it looks like it's not just you running into such issues.

**Comment by webvictim** [comment]
I think the reason that `tctl` defaults to loading the config from disk is because its traditional usage was only intended to be on the auth server itself, where it would read `/etc/teleport.yaml` to find out the value of `data_dir` and any configured backend storage, then connect using the same config as Teleport and perform operations directly.

I agree that this issue could use some more thought, but the config loading logic is quite tightly coupled to `tctl`'s operation (particularly in a non-Enterprise setting) and I wanted to just provide an easy, optional workaround for the problem with as little effort as possible. It seems fairly likely that `tctl` may undergo some refactoring soon as part of the upcoming work to add RBAC to open source.
