### ISSUE TITLE
Merge SSH reverse tunnel and SSH proxy port

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4843]
### Feature Request

The same SSH server can serve both SSH reverse tunnel port and normal client port based on the certificate:

* If presented a host certificate, it is used as a reverse tunnel port
* If presented a user certificate, it is used as a usual SSH jumphost

Because we already multiplex on 3080 SSH and HTTPS, this will reduce the default number of ports users have to open to one.

**Comment by webvictim** [comment]
Same thing as #3211?

**Comment by webvictim** [comment]
I think we could theoretically serve the Kubernetes API via the same port too.

**Comment by pschisa** [comment]
Using a single port for Teleport services is resolved in Teleport 8.0 by TLS routing and https://github.com/gravitational/teleport/pull/7524.  Marking this issue as closed now.
