### ISSUE TITLE
Teleport 5.0 - Manual Test Plan 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4846]
## Manual Testing Plan

Below are the items that should be manually tested with each release of Teleport.
These tests should be run on both a fresh install of the version to be released
as well as an upgrade of the previous version of Teleport.

- [x] Adding nodes to a cluster @russjones 
  - [x] Adding Nodes via Valid Static Token
  - [x] Adding Nodes via Valid Short-lived Tokens
  - [x] Adding Nodes via Invalid Token Fails
  - [x] Revoking Node Invitation

- [x] Labels @benarent 
  - [x] Static Labels
  - [x] Dynamic Labels

- [x] Trusted Clusters @Joerger 
  - [x] Adding Trusted Cluster Valid Static Token
  - [x] Adding Trusted Cluster Valid Short-lived Token
  - [x] Adding Trusted Cluster Invalid Token
  - [x] Removing Trusted Cluster

- [x] RBAC @awly 

  Make sure that invalid and valid attempts are reflected in audit log.

  - [x] Successfully connect to node with correct role
  - [x] Unsuccessfully connect to a node in a role restricting access by label
  - [x] Unsuccessfully connect to a node in a role restricting access by invalid SSH login
  - [x] Allow/deny role option: SSH agent forwarding
  - [x] Allow/deny role option: Port forwarding

- [x] Users @a-palchikov 
With every user combination, try to login and signup with invalid second factor, invalid password to see how the system reacts.

  - [x] Adding Users Password Only
  - [x] Adding Users OTP
  - [x] Adding Users U2F
  - [x] Login Password Only
  - [x] Login OTP
  - [x] Login U2F
  - [x] Login OIDC
  - [x] Login SAML
  - [x] Login GitHub
  - [x] Deleting Users

- [x] Backends @webvictim 
  - [x] Teleport runs with etcd
  - [x] Teleport runs with dynamodb
  - [x] Teleport runs with sqlite
  - [x] GCP/Firestore (@benarent)

- [x] Session Recording @russjones 
  - [x] Session recording can be disabled
  - [x] Sessions can be recorded at the node
    - [x] Sessions in remote clusters are recorded in remote clusters
  - [x] Sessions can be recorded at the proxy
    - [x] Sessions on remote clusters are recorded in the local cluster
    - [x] Enable/disable host key checking.

- [x] Audit Log @benarent 
  - [x] Failed login attempts are recorded
  - [x] Interactive sessions have the correct Server ID
    - [x] Server ID is the ID of the node in regular mode
    - [x] Server ID is randomly generated for proxy node
  - [x] Exec commands are recorded
  - [x] `scp` commands are recorded
  - [x] Subsystem results are recorded

- [x] Interact with a cluster using `tsh` @Joerger 

   These commands should ideally be tested for recording and non-recording modes as they are implemented in a different ways.

  - [x] tsh ssh \<regular-node\>
  - [x] tsh ssh \<node-remote-cluster\>
  - [x] tsh ssh -A \<regular-node\>
  - [x] tsh ssh -A \<node-remote-cluster\>
  - [x] tsh ssh \<regular-node\> ls
  - [x] tsh ssh \<node-remote-cluster\> ls
  - [x] tsh join \<regular-node\>
  - [x] tsh join \<node-remote-cluster\>
  - [x] tsh play \<regular-node\>
  - [x] tsh play \<node-remote-cluster\>
  - [x] tsh scp \<regular-node\>
  - [x] tsh scp \<node-remote-cluster\>
  - [x] tsh ssh -L \<regular-node\>
  - [x] tsh ssh -L \<node-remote-cluster\>
  - [x] tsh ls
  - [x] tsh clusters

- [x] Interact with a cluster using `ssh` @awly 
   Make sure to test both recording and regular proxy modes.
  - [x] ssh \<regular-node\>
  - [x] ssh \<node-remote-cluster\>
  - [x] ssh -A \<regular-node\>
  - [x] ssh -A \<node-remote-cluster\>
  - [x] ssh \<regular-node\> ls
  - [x] ssh \<node-remote-cluster\> ls
  - [x] scp \<regular-node\>
  - [x] scp \<node-remote-cluster\>
  - [x] ssh -L \<regular-node\>
  - [x] ssh -L \<node-remote-cluster\>

- [ ] Interact with a cluster using the Web UI @a-palchikov 
  - [x] Connect to a Teleport node
  - [x] Connect to a OpenSSH node
  - [ ] Check agent forwarding is correct based on role and proxy mode.

### Combinations @webvictim 

For some manual testing, many combinations need to be tested. For example, for
interactive sessions the 12 combinations are below.

- [x] Connect to a OpenSSH node in a local cluster using OpenSSH.
- [x] Connect to a OpenSSH node in a local cluster using Teleport.
- [x] Connect to a OpenSSH node in a local cluster using the Web UI.
- [x] Connect to a Teleport node in a local cluster using OpenSSH.
- [x] Connect to a Teleport node in a local cluster using Teleport.
- [x] Connect to a Teleport node in a local cluster using the Web UI.
- [x] Connect to a OpenSSH node in a remote cluster using OpenSSH.
- [x] Connect to a OpenSSH node in a remote cluster using Teleport.
- [x] Connect to a OpenSSH node in a remote cluster using the Web UI.
- [x] Connect to a Teleport node in a remote cluster using OpenSSH.
- [x] Connect to a Teleport node in a remote cluster using Teleport.
- [x] Connect to a Teleport node in a remote cluster using the Web UI.

### Teleport with EKS/GKE @awly 

* [x] Deploy Teleport on a single EKS cluster
* [x] Deploy Teleport on two EKS clusters and connect them via trusted cluster feature
* [x] Deploy Teleport Proxy outside of GKE cluster fronting connections to it (this feature is not yet supported for EKS)

### Teleport with multiple Kubernetes clusters @benarent 

Note: you can use GKE or EKS or minikube to run Kubernetes clusters.
Minikube is the only caveat - it's not reachable publicly so don't run a proxy there.

* [x] Deploy combo auth/proxy/kubernetes_service outside of a Kubernetes cluster, using a kubeconfig
  * [x] Login with `tsh login`, check that `tsh kube ls` has your cluster
  * [x] Run `kubectl get nodes`, `kubectl exec -it $SOME_POD -- sh`
  * [x] Verify that the audit log recorded the above request and session
* [x] Deploy combo auth/proxy/kubernetes_service inside of a Kubernetes cluster
  * [x] Login with `tsh login`, check that `tsh kube ls` has your cluster
  * [x] Run `kubectl get nodes`, `kubectl exec -it $SOME_POD -- sh`
  * [x] Verify that the audit log recorded the above request and session
* [x] Deploy combo auth/proxy_service outside of the Kubernetes cluster and kubernetes_service inside of a Kubernetes cluster, connected over a reverse tunnel
  * [x] Login with `tsh login`, check that `tsh kube ls` has your cluster
  * [x] Run `kubectl get nodes`, `kubectl exec -it $SOME_POD -- sh`
  * [x] Verify that the audit log recorded the above request and session
* [x] Deploy a second kubernetes_service inside of another Kubernetes cluster, connected over a reverse tunnel
  * [x] Login with `tsh login`, check that `tsh kube ls` has both clusters
  * [x] Switch to a second cluster using `tsh kube login`
  * [x] Run `kubectl get nodes`, `kubectl exec -it $SOME_POD -- sh` on the new cluster
  * [x] Verify that the audit log recorded the above request and session
* [x] Deploy combo auth/proxy/kubernetes_service outside of a Kubernetes cluster, using a kubeconfig with multiple clusters in it
  * [x] Login with `tsh login`, check that `tsh kube ls` has all clusters

### Teleport with FIPS mode @russjones  

* [x] Perform trusted clusters, Web and SSH sanity check with all teleport components deployed in FIPS mode.

### Migrations @russjones @benarent 

* [x] Migrate trusted clusters from 2.4.0 to 2.5.0
  * [x] Migrate auth server on main cluster, then rest of the servers on main cluster
        SSH should work for both main and old clusters
  * [x] Migrate auth server on remote cluster, then rest of the remote cluster
       SSH should work

### Command Templates

When interacting with a cluster, the following command templates are useful:

#### OpenSSH

```
# when connecting to the recording proxy, `-o 'ForwardAgent yes'` is required.
ssh -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p" \
  node.example.com

# the above command only forwards the agent to the proxy, to forward the agent
# to the target node, `-o 'ForwardAgent yes'` needs to be passed twice.
ssh -o "ForwardAgent yes" \
  -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p" \
  node.example.com

# when connecting to a remote cluster using OpenSSH, the subsystem request is
# updated with the name of the remote cluster.
ssh -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p@foo.com" \
  node.foo.com
```

#### Teleport

```
# when connecting to a OpenSSH node, remember `-p 22` needs to be passed.
tsh --proxy=proxy.example.com --user=<username> --insecure ssh -p 22 node.example.com

# an agent can be forwarded to the target node with `-A`
tsh --proxy=proxy.example.com --user=<username> --insecure ssh -A -p 22 node.example.com

# the --cluster flag is used to connect to a node in a remote cluster.
tsh --proxy=proxy.example.com --user=<username> --insecure ssh --cluster=foo.com -p 22 node.foo.com
```

### Teleport with SSO Providers @benarent 

- [x] G Suite install instructions work
    - [x] G Suite Screenshots are up to date
- [ ] ActiveDirectoy install instructions work
    - [ ] Active Directoy Screenshots are up to date
- [x] Okta install instructions work
    - [x] Okta Screenshots are up to date
- [x] OneLogin install instructions work
    - [x] OneLogin Screenshots are up to date
- [x] OIDC install instructions work
    - [x] OIDC Screenshots are up to date

### Teleport Plugins @Joerger 

- [x] Test receiving a message via Teleport Slackbot
- [x] Test receiving a new Jira Ticket via Teleport Jira

## Main
For main, test with admin role that has access to all resources.

#### Top Nav
- [x] Verify that cluster selector displays all (root + leaf) clusters
- [x] Verify that user name is displayed
- [x] Verify that user menu shows logout, help&support, and account settings

#### Side Nav
- [x] Verify that each item has an icon
- [x] Verify that Collapse/Expand works and collapsed has icon `>`, and expand has icon `v`
- [x] Verify that it automatically expands and highlights the item on page refresh

#### Servers aka Nodes
- [x] Verify that "Servers" table shows all joined nodes
- [x] Verify that "Connect" button shows a list of available logins
- [x] Verify that "Hostname", "Address" and "Labels" columns show the current values
- [x] Verify that "Search" by hostname, address, labels works
- [x] Verify that terminal opens when clicking on one of the available logins
- [x] Verify that clicking on `Add Server` button renders dialogue set to `Automatically` view
  - [x] Verify clicking on `Regenerate Script` regenerates token value in the bash command
  - [x] Verify using the bash command successfully adds the server (refresh server list)
  - [x] Verify that clicking on `Manually` tab renders manual steps
  - [x] Verify that clicking back to `Automatically` tab renders bash command

#### Applications
- [x] Verify that all apps registered are shown
- [x] Verify that clicking on the app icon takes you to another tab
- [x] Verify that clicking on `Add Application` button renders dialogue
  - [x] Verify input validation (prevent empty value and invalid url)
  - [x] Verify after input and clicking on `Generate Script`, bash command is rendered
  - [x] Verify clicking on `Regenerate` button regenerates token value in bash command
  - [x] Verify using the bash command successfully adds the application (refresh app list)

#### Active Sessions
- [x] Verify that "empty" state is handled
- [x] Verify that it displays the session when session is active
- [x] Verify that "Description", "Session ID", "Users", "Nodes" and "Duration" columns show correct values
- [x] Verify that "OPTIONS" button allows to join a session

#### Audit log
- [x] Verify that time range button is shown and works
- [x] Verify that clicking on `Session Ended` event icon, takes user to session player
- [x] Verify event detail dialogue renders when clicking on events `details` button
- [x] Verify searching by type, description, created works

#### Users
- [x] Verify that users are shown
- [x] Verify that creating a new user works
- [x] Verify that editing user roles works
- [x] Verify that removing a user works
- [x] Verify resetting a user's password works
- [x] Verify search by username, roles, and type works

#### Auth Connectors
- [x] Verify that creating OIDC/SAML/GITHUB connectors works
- [x] Verify that editing  OIDC/SAML/GITHUB connectors works
- [x] Verify that error is shown when saving an invalid YAML
- [x] Verify that correct hint text is shown on the right side

#### Auth Connectors Card Icons
- [x] Verify that GITHUB card has github icon
- [x] Verify that SAML card has SAML icon
- [x] Verify that OIDC card has OIDC icon
- [x] Verify when there are no connectors, empty state renders

#### Roles
- [x] Verify that roles are shown
- [x] Verify that "Create New Role" dialog works
- [x] Verify that deleting and editing works
- [x] Verify that error is shown when saving an invalid YAML
- [x] Verify that correct hint text is shown on the right side

#### Managed Clusters
- [x] Verify that it displays a list of clusters (root + leaf)
- [x] Verify that every menu item works: nodes, apps, audit events, session recordings.

#### Help&Support
- [x] Verify that all URLs work and correct (no 404)

#### Strategy Reason
Create the following role:
```
kind: role
metadata:
  name: restrict
spec:
  allow:
    request:
      roles:
      - <some other role to assign user after approval>
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 8h0m0s
    port_forwarding: true
    request_access: reason
    request_prompt: <some custom prompt to show in reason dialogue>
version: v3
```
- [x] Verify after login, reason dialogue is rendered with prompt set to `request_prompt` setting
- [x] Verify after clicking `send request`, pending dialogue renders
- [x] Verify after `tctl requests approve <request-id>`, dashboard is rendered
- [x] Verify the correct role was assigned

#### Strategy Always
With the previous role you created from `Strategy Reason`, change `request_access` to `always`:
- [x] Verify after login, pending dialogue is rendered
- [x] Verify after `tctl requests approve <request-id>`, dashboard is rendered
- [x] Verify after login, `tctl requests deny <request-id>`, access denied dialogue is rendered

#### Strategy Optional
With the previous role you created from `Strategy Reason`, change `request_access` to `optional`:
- [x] Verify after login, dashboard is rendered

## Account
- [x] Verify that Account screen is accessibly from the user menu for local users.
- [x] Verify that changing a local password works (OTP, U2F)

## Terminal
- [x] Verify that top nav has a user menu (Main and Logout)
- [x] Verify that switching between tabs works on alt+[1...9]

#### Node List Tab
- [x] Verify that Cluster selector works (URL should change too)
- [x] Verify that Quick launcher input works
- [x] Verify that Quick launcher input handles input errors
- [x] Verify that "Connect" button shows a list of available logins
- [x] Verify that "Hostname", "Address" and "Labels" columns show the current values
- [x] Verify that "Search" by hostname, address, labels work
- [x] Verify that new tab is created when starting a session

#### Session Tab
- [x] Verify that session and browser tabs both show the title with login and node name
- [x] Verify that terminal resize works
    - Install midnight commander on the node you ssh into: `$ sudo apt-get install mc`
    - Run the program: `$ mc`
    - Resize the terminal to see if panels resize with it
- [x] Verify that session tab shows/updates number of participants when a new user joins the session
- [x] Verify that tab automatically closes on "$ exit" command
- [x] Verify that SCP Upload works
- [x] Verify that SCP Upload handles invalid paths and network errors
- [x] Verify that SCP Download works
- [x] Verify that SCP Download handles invalid paths and network errors

## Session Player
- [x] Verify that it can replay a session
- [x] Verify that when playing, scroller auto scrolls to bottom most content
- [x] Verify when resizing player to a small screen, scroller appears and is working
- [x] Verify that error message is displayed (enter a invalid SID in the URL)

## Invite Form
- [x] Verify that input validates
- [x] Verify that invite works with 2FA disabled
- [x] Verify that invite works with OTP enabled
- [x] Verify that invite works with U2F enabled
- [x] Verify that error message is shown if an invite is expired/invalid

## Login Form
- [x] Verify that input validates
- [x] Verify that login works with 2FA disabled
- [x] Verify that login works with OTP enabled
- [x] Verify that login works with U2F enabled
- [x] Verify that login works for Github/SAML/OIDC
- [ ] Verify that account is locked after several unsuccessful attempts
- [x] Verify that redirect to original URL works after successful login

## RBAC
Create a role, with no `allow.rules` defined:
```
kind: role
metadata:
  name: test
spec:
  allow:
    app_labels:
      '*': '*'
    logins:
    - root
    node_labels:
      '*': '*'
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: false
    max_session_ttl: 8h0m0s
    port_forwarding: true
version: v3
```
- [x] Verify that a user has access only to: "Servers", "Applications", "Active Sessions" and "Manage Clusters"
- [x] Verify there is no `Add Server` button in Server view
- [x] Verify there is no `Add Application` button in Applications view
- [x] Verify only `Nodes` and `Apps` are listed under `options` button in `Manage Clusters`

Add the following resource under `spec.allow.rules` to enable read access to the audit log:
```
  - resources:
      - event
      verbs:
      - list
```
- [x] Verify that the `Audit Log` and `Session Recordings` is accessible
- [x] Verify that playing a recorded session is denied

Add the following resource to enable read access to recorded sessions
```
  - resources:
      - session
      verbs:
      - read
```
- [x] Verify that a user can re-play a session (session.end)

Add the following resource to enable read access to the roles

```
- resources:
      - role
      verbs:
      - list
      - read
```
- [x] Verify that a user can see the roles
- [x] Verify that a user cannot create/delete/update a role

Add the following resource to enable read access to the auth connectors

```
- resources:
      - auth_connector
      verbs:
      - list
      - read
```
- [x] Verify that a user can see the list of auth connectors.
- [x] Verify that a user cannot create/delete/update the connectors

Add the following resource to enable read access to users
```
  - resources:
      - user
      verbs:
      - list
      - read
```
- [x] Verify that a user can access the "Users" screen
- [x] Verify that a user cannot create/delete/update a user

Add the following resource to enable read access to trusted clusters
```
  - resources:
      - trusted_cluster
      verbs:
      - list
      - read
```
- [x] Verify that a user can access the "Trust" screen
- [x] Verify that a user cannot create/delete/update a trusted cluster.

## Performance/Soak Test @fspmarshall @quinqu 

Using `tsh bench` tool, perform the soak tests and benchmark tests on the following configurations:

* Cluster with 10K nodes in normal (non-IOT) node mode with ETCD
* Cluster with 10K nodes in normal (non-IOT) mode with DynamoDB

* Cluster with 1K IOT nodes with ETCD
* Cluster with 1K IOT nodes with DynamoDB

* Cluster with 500 trusted clusters with ETCD
* Cluster with 500 trusted clusters with DynamoDB

**Soak Tests**

Run 4hour soak test with a mix of interactive/non-interactive sessions:

```
tsh bench --duration=4h --threads=10 user@teleport-monster-6757d7b487-x226b ls
tsh bench -i --duration=4h --threads=10 user@teleport-monster-6757d7b487-x226b ps uax
```

Observe prometheus metrics for goroutines, open files, RAM, CPU, Timers and make sure there are no leaks

- [x] Verify that prometheus metrics are accurate.

**Breaking load tests**

Load system with tsh bench to the capacity and publish maximum numbers of concurrent sessions with interactive
and non interactive tsh bench loads.

### AWS

- [x] Deploy Teleport to AWS. Using DynamoDB & S3
- [x] Deploy clean Teleport Enterprise to AWS. Using HA Setup https://gravitational.com/teleport/docs/aws-terraform-guide/
- [x] Deploy upgrade from 4.4 to 5.0 Teleport Enterprise AWS terraform.

### GCP

- [x] Deploy Teleport to GCP. Using Cloud Firestore & Cloud Storage
- [x] Deploy Teleport to GKE. Google Kubernetes engine.
- [x] Deploy Teleport Enterprise to GCP.

### IBM

- [x] Deploy Teleport to IBM Cloud. Using IBM Database for etcd & IBM Object Store
- [x] Deploy Teleport to IBM Cloud Kubernetes.
- [x] Deploy Teleport Enterprise to IBM Cloud.

### Teleport Cloud

- [x] Deploy a Teleport Cloud instance on ~teleport.sh~cloud.gravitational.io
- [x] Add a node to your cluster using the UI wizard
- [x] Add an application to your cluster using the UI wizard
- [x] Test that application works
- [x] Log into your node via `tsh ssh` and start a long-running (~30 minute) session, make sure you don't get disconnected
- [x] Log into your node via the web UI and start a long-running (~30 minute) session, make sure you don't get disconnected

## Application Access @russjones @benarent 

- [x] Run an application within local cluster.
  - [x] Verify the debug application `debug_app: true` works.
  - [x] Verify an application can be configured with command line flags.
  - [x] Verify an application can be configured from file configuration.
  - [x] Verify that application are available at auto-generated addresses `name.rootProxyPublicAddr` and well as `publicAddr`.
- [x] Run an application within a trusted cluster.
  - [x] Verify that applications are available at auto-generated addresses `name.rootProxyPublicAddr`.
- [x] Verify Audit Records.
  - [x] `app.session.start` and `app.session.chunk` events are created in the Audit Log.
  - [x] `app.session.chunk` points to a 5 minute session archive with multiple `app.session.request` events inside.
  - [x] `tsh play <chunk-id>` can fetch and print a session chunk archive.
- [x] Verify JWT using [verify-jwt.go](https://github.com/gravitational/teleport/blob/master/examples/jwt/verify-jwt.go).
- [x] Verify RBAC.

**Comment by Joerger** [comment]
`tsh join [session-id] ` is failing for me with `error: session [session-id] not found or it has ended`. I have another tsh ssh connection running, and used the session-id given by `teleport status`. I get the same error through the web ui.

**Comment by quinqu** [comment]
When you add a user ( ex: `tctl users add ec2-user --roles admin`) the output below shows. When I replace `<proxyhost> ` with the actual proxy host, it works. Not a huge cause for concern, however could be confusing to some folks. 
```
User ec2-user has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h0m0s:
https://<proxyhost>:3080/web/invite/9dcf9f297e90fde6ab2e3a39d97417f2

NOTE: Make sure <proxyhost>:3080 points at a Teleport proxy which users can access.
```

**Comment by russjones** [comment]
@quinqu You need to set `public_addr` under `proxy_service`. Can you set that and try again?

**Comment by quinqu** [comment]
`public_addr` is set.

**Comment by webvictim** [comment]
Could be similar to #3217 ?

**Comment by quinqu** [comment]
## Cluster with 1K IOT nodes with DynamoDB against proxy

![Screenshot from 2020-11-17 08-53-43](https://user-images.githubusercontent.com/42625018/99420757-72307480-28b2-11eb-955b-78ad14ea3ccb.png)


`tsh bench -d  --duration 4h --threads=10 root@ip-172-31-2-191-us-west-2-compute-internal ls`

```
* Requests originated: 73943
* Requests failed: 0

Histogram

Percentile Duration 
---------- -------- 
25         1402 ms  
50         1659 ms  
75         2197 ms  
90         3009 ms  
95         3525 ms  
99         13327 ms 
100        33279 ms 
```

`tsh bench -d --interactive --duration 4h --threads=10 root@ip-172-31-2-191-us-west-2-compute-internal ps aux`

```
* Requests originated: 74446
* Requests failed: 0

Histogram

Percentile Duration 
---------- -------- 
25         1399 ms  
50         1654 ms  
75         2191 ms  
90         3005 ms  
95         3515 ms  
99         13087 ms 
100        34719 ms 

```

**Comment by webvictim** [comment]
@fspmarshall The "Invisibile" `teleport-nologin` logins are showing up in the output of `tctl auth export --type=host`:

```
[root@ip-172-31-52-229 ~]# tctl auth export --type=host
DEBU[0000] Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s  trace.component=sqlite
DEBU[0000] Synchronous: 0, busy timeout: 10000           trace.component=sqlite
DEBU[0000] Connecting to auth servers: [{0.0.0.0:3025 tcp }]. 
@cert-authority *.ip-172-31-52-229-ec2-internal ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmTxGPukcNa0DWp9WEn0cMkPOZp+eS643dkhC3d9loxL+putBiFOTpBlOR2v7UM+5W4SXnrkAGgRW9tKUByzA79xL8vPHMLrOH5A46W5JIjLavXzNuAY1mHEvG2d3kX24IHn30DNdFXfi70TMxf2oZFAidHwDtIdhzyuDkYuAlJoBK296SmvbWlHyZrc5RAEfitI7DjovsUj73eKc/9PR45qGeQdctKgffp+QvdWuUBJ2lGEPms6NdO+AKT7jDFOgRVj9gaQgibgVHn/IN4yyFOHVwZ3N/aazCDaoECTBGhS5PwESO/STogv8+63BqA6Nf4mwUZNIQlU+WNo4TYCLb logins=-teleport-nologin-8085713f-77d8-49eb-8240-6720638df045&type=host
```

**Comment by quinqu** [comment]
## Cluster with 10K nodes in IOT mode with DynamoDB
When I am running the load test with 10k nodes, the interactive sessions keep dropping to 0 after around 30 min.
![Screenshot from 2020-11-18 10-09-47](https://user-images.githubusercontent.com/42625018/99570066-4383ce00-2986-11eb-8c5e-26e1c1f86ecd.png)

**Comment by quinqu** [comment]
## Cluster with 10K nodes in IOT mode with DynamoDB
Interactive sessions drop to 0 after about 2 hours 

![Screenshot from 2020-11-18 21-05-14](https://user-images.githubusercontent.com/42625018/99698234-65905580-2a45-11eb-9eba-04db025eaba2.png)

```
tsh bench -d  --duration 4h --threads=10 root@ip-172-31-2-11-us-west-2-compute-internal ls 

* Requests originated: 14787
* Requests failed: 8
* Last error: several requests hang: timeout waiting for 10 threads to finish
Histogram
Percentile Duration 
---------- -------- 
25         229 ms   
50         331 ms   
75         977 ms   
90         3679 ms  
95         5623 ms  
99         30143 ms 
100        36479 ms 
```
```
tsh bench -d  --interactive --duration 4h --threads=10 root@ip-172-31-2-11-us-west-2-compute-internal ps aux

* Requests originated: 17432
* Requests failed: 14
* Last error: several requests hang: timeout waiting for 10 threads to finish
Histogram
Percentile Duration 
---------- -------- 
25         254 ms   
50         335 ms   
75         787 ms   
90         3057 ms  
95         5323 ms  
99         26719 ms 
100        35103 ms 

```

**Comment by klizhentas** [comment]
@quinqu this looks like a possible significant regression

https://github.com/gravitational/teleport/issues/4359#issuecomment-703189400

**Comment by klizhentas** [comment]
@fspmarshall @quinqu @russjones I just re-ran the test on the cluster. I do not see any regressions here:

![run](https://user-images.githubusercontent.com/13717/99756944-2abd0a80-2aa3-11eb-8ebf-54fd208a4757.png)

May be we have different configurations?

I have 2 proxies m4.4xlarge (16 cores, 64GB RAM) each.
2 auth servers m4.4xlarge
target node m2.2xlarge

**Comment by klizhentas** [comment]
Another difference could be that when I run a soak test against 1 node, I don't scale up the cluster to 10K. I run those tests separately:

* 10K scale up/scale down
* 10K scale up/ cert authority rotate
* 4h hour soak test - against 1 node.

**Comment by quinqu** [comment]
4 hour soak test with the new `tsh bench` without coordinated omission and implemented with an "open" system where requests are independent of each other 

![Screenshot from 2020-11-23 15-30-23](https://user-images.githubusercontent.com/42625018/100032150-3282f480-2dac-11eb-8c4d-459f977fe094.png)

```
tsh bench -J tfivepointzero-proxy-6ab55f525b051303.elb.us-west-2.amazonaws.com:3023 --duration=4h root@ip-172-31-9-106-us-west-2-compute-internal ls

* Requests originated: 143988
* Requests failed: 0
Histogram
Percentile Response Duration Service Duration 
---------- ----------------- ---------------- 
25         58 ms             57 ms            
50         362 ms            361 ms           
75         1286 ms           1286 ms          
90         2107 ms           2105 ms          
95         3837 ms           3837 ms          
99         30047 ms          30047 ms         
100        31807 ms          31807 ms 
```

```
tsh bench --interactive -J tfivepointzero-proxy-6ab55f525b051303.elb.us-west-2.amazonaws.com:3023 --duration=4h root@ip-172-31-9-106-us-west-2-compute-internal ps uax

* Requests originated: 143985
* Requests failed: 0
Histogram
Percentile Response Duration Service Duration 
---------- ----------------- ---------------- 
25         56 ms             56 ms            
50         371 ms            371 ms           
75         1293 ms           1292 ms          
90         2117 ms           2117 ms          
95         3963 ms           3963 ms          
99         30047 ms          30047 ms         
100        31615 ms          31615 ms  
```

**Comment by quinqu** [comment]
## 10K scale up/scale down
instance types:  
proxies, auths: m4.4xlarge

![Screenshot from 2020-11-24 09-07-45](https://user-images.githubusercontent.com/42625018/100127995-8c2f0180-2e34-11eb-98f1-48c3ecbb06cf.png)

**Comment by klizhentas** [comment]
@quinqu how many scale up/down cycles is this?

**Comment by quinqu** [comment]
@klizhentas 1 scale up and 1 scale down

**Comment by quinqu** [comment]
I find it odd that one proxy and one auth is taking most of the load so looking into it right now

**Comment by klizhentas** [comment]
@quinqu can you try a couple of scale up/down cycles in a row? We can than see baseline CPU/RAM usage. One proxy and one auth are taking most of the load probably because we need to turn on cross zone load balancing.

**Comment by quinqu** [comment]
It looks like there is a memory leak. The heap usage isn't going back down to it's initial state. The proxies have overlapping lines so the load is pretty even there. The auths however don't really have a balanced load. Crossed-load balancing is enabled on both proxy and auth, though. And I didn't see any weird or concerning errors on the auths when running `journalctl -u teleport-auth -f ` to see if there was a reason why the load was essentially all on one auth server. 

![Screenshot from 2020-11-24 12-15-34](https://user-images.githubusercontent.com/42625018/100146481-d624e100-2e4e-11eb-88e3-6e46f578c8a6.png)

**Comment by benarent** [comment]
Formally closing our milestone based on 5.0 Release https://github.com/gravitational/teleport/releases/tag/v5.0.0
