### ISSUE TITLE
Include User Agent Header as part of Jamf Pro Plugin

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#48479]
What would you like Teleport to do?

As part of Jamf best practices, we've been asked to send User-Agent header. 
 https://developer.jamf.com/developer-guide/docs/application-header-best-practices 

What problem does this solve?

The Jamf Technology team have requested this. In the future, Jamf may provide additional value or benefits to members of the Technology Partner Program who incorporate the use of User-Agent headers into their applications 

If a workaround exists, please include it.

**Comment by zmb3** [comment]
This was fixed with https://github.com/gravitational/teleport.e/pull/5363
