### ISSUE TITLE
Add new resource / (SSH Server | Database Service) fails to generate a valid node join script

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#48508]
Expected behavior:
When using Enroll New Resource flow, we receive a script that should be able to enroll a new SSH Node.
![Image](https://github.com/user-attachments/assets/87c6ac4e-b693-45e2-a6fb-39f7e15425ae)

Current behavior:
When running the script, we get the following error:
![Image](https://github.com/user-attachments/assets/69e1ed81-8bbf-4ba1-bda0-9bd622c37223)

Bug details:
- Version: 17.0.0-alpha.4
- Recreation steps
Create a new Cloud Tenant and try to enroll a new SSH Server using the UI.

Logs:
```
{"caller":"web/join_tokens.go:385","component":"web","error":"error cached until '2024-11-06 11:53:43.882015629 +0000 UTC m=+595.319983751': non-200 status code received: '404'","level":"info","message":"Failed to get auto upgrades version.","timestamp":"2024-11-06T11:53:23Z"}
```

Note: this also happens for the NodeJoin script when used for deploying a Database Service for a self-hosted database.

Note2: this also happens for the self-hosted Kubernetes enrollment (there's no version argument after the `--version` flag):
![Image](https://github.com/user-attachments/assets/38e1c11b-2e6f-498f-ab10-34a995f56d49)

**Comment by GavinFrazar** [comment]
seeing the same with RDS enrollment flow on 17.0.0-alpha.4

I get the "non-200 status code received: '404'" as well when clicking the "deploy" service button

cannot reproduce if build that version locally though.

**Comment by marcoandredinis** [comment]
@GavinFrazar Thank you for confirming.
I'm observing the exact same issue.

So far, this is what I was able to investigate:
- release build 17.0.0-alpha.4: NOK
- local build of `v17.0.0-alpha.4` tag using base image 17.0.0-alpha.4: NOK
- local build of `v17.0.0-alpha.4` tag using base image 16.4.6: OK

**Comment by greedy52** [comment]
possibly related:
- https://github.com/gravitational/teleport/issues/48389

**Comment by GavinFrazar** [comment]
> [@GavinFrazar](https://github.com/GavinFrazar) Thank you for confirming. I'm observing the exact same issue.
> 
> So far, this is what I was able to investigate:
> 
> * release build 17.0.0-alpha.4: NOK
> * local build of `v17.0.0-alpha.4` tag using base image 17.0.0-alpha.4: NOK
> * local build of `v17.0.0-alpha.4` tag using base image 16.4.6: OK

the v17 base image NOK was really key to figuring this out.
The base image tag is used by our deploy-cloud.sh script to generate a target image tag.
That tag is then picked up by cloud's operator and used to template a configmap using the major version of the tag.
So if you use v17+ tag, you get an auto upgrades channel in your config map that looks like this:

```
      automatic_upgrades_channels:
        stable/cloud:
          forward_url: https://updates.releases.teleport.dev/v1/stable/cloud/v17
```

that URL returns 404 because we don't have a v17 channel yet.

If I use v16 base image, then I get this in configmap instead:

```
      automatic_upgrades_channels:
        stable/cloud:
          forward_url: https://updates.releases.teleport.dev/v1/stable/cloud/v16
```

**Comment by greedy52** [comment]
i can repro this now after switching to non-enterprise build:
```
logger.ts:28 [components/CatchError] render TypeError: Cannot read properties of undefined (reading 'expiryText')
    at StepsWithToken (Manually.tsx:161:18)
    at renderWithHooks (chunk-A6E3XU77.js?v=08aab753:11548:26)
    at mountIndeterminateComponent (chunk-A6E3XU77.js?v=08aab753:14926:21)
    at beginWork (chunk-A6E3XU77.js?v=08aab753:15914:22)
    at beginWork$1 (chunk-A6E3XU77.js?v=08aab753:19753:22)
    at performUnitOfWork (chunk-A6E3XU77.js?v=08aab753:19198:20)
    at workLoopSync (chunk-A6E3XU77.js?v=08aab753:19137:13)
    at renderRootSync (chunk-A6E3XU77.js?v=08aab753:19116:15)
    at recoverFromConcurrentError (chunk-A6E3XU77.js?v=08aab753:18736:28)
    at performSyncWorkOnRoot (chunk-A6E3XU77.js?v=08aab753:18879:28)
```
