### ISSUE TITLE
Add Drone cron job to delete old unsupported AMIs

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4855]
We currently have AMIs hosted going all the way back to Teleport 3.1 (when they were first added).

To unclutter this, we should remove all AMIs that are no longer supported, i.e. those which are more than 3 release versions old. This figure may need some tweaking, as it's possible that there are customers still using these AMIs.

Currently, that would mean we keep 4.2.x, 4.3.x and 4.4.x with all older AMIs being deleted.

When 5.0 is released, we should delete all 4.2.x AMIs as well.

**Comment by webvictim** [comment]
I'll leave this issue open so we don't lose track of the fact that at some point we're going to need to stop storing old AMIs, but we're not going to rush into deleting anything soon.

**Comment by russjones** [comment]
Unless costs become an issue, let's just keep old AMIs for people that want them.
