### ISSUE TITLE
Two-Factor Auth - Make the TOTP Authenticator Key available to copy

### ISSUE THREAD

**Issue by knzy-pro** [gravitational/teleport#48576]
What would you like Teleport to do?

When setting up two factor auth for my admin account I would like to be able to obtain the totp authenticator key so I can use it in my password manager (bitwarden) to generate the verification code. Currently we are restricted to using a QR scanner on the mobile app.

What problem does this solve?
Store and generate the verification code via password manager app/extension

If a workaround exists, please include it.

**Comment by zmb3** [comment]
This is not something we're planning on addressing.

See https://github.com/gravitational/teleport/issues/18289#issuecomment-1341321126 for the last time this came up.
