### ISSUE TITLE
Confusing session player experience with no read rights to a session recording

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#48612]
Expected behavior:
If I don't have permissions to play a session, the play button should be disabled or at least I should be given a clear error

Current behavior:
Instead, I'm able to get to the player and the player attempts to stream session contents, which are empty, and just sits there doing nothing.

Bug details:
- Teleport version: 17.0.0-alpha.4
- Recreation steps
1. Create a user who can list session recordings, but can't play them.
2. Log in as that user, go to session recordings list and play a session.

**Comment by bl-nero** [comment]
Similar issue: https://github.com/gravitational/teleport/issues/48395

**Comment by zmb3** [comment]
I'm guessing this was fixed by #48840 because it seems to be working correctly now:

<img width="883" alt="Image" src="https://github.com/user-attachments/assets/73aab66b-a1cd-484a-bcb6-26ecb5010fdc" />
