### ISSUE TITLE
Trusted Clusters should be searchable in Web UI

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#48623]
### Expected Behavior
Users should have the ability to search for specific trusted clusters within the Teleport UI, allowing efficient navigation and management of multiple clusters.

### Current Behavior
In Teleport version 15, the search functionality for trusted clusters is missing, requiring users to manually scroll through the list of trusted clusters. This is inefficient and cumbersome, especially for users managing a large number of trusted clusters.

This was reported by a user that has _hundred_ of trusted clusters.

```
% tsh clusters | wc -l
526
```

#### Teleport Version
Teleport version 15.x

#### Recreation Steps
1. Upgrade a Teleport cluster from version 14 to version 15.
2. Attempt to search for a trusted cluster using the Teleport UI.
3. Observe that the search functionality for trusted clusters is absent, necessitating manual navigation through the list.

#### Debug Logs
N/A (web UI issue)

**Comment by TeleLos** [comment]
In version 14 you could narrow down the list of clusters in the search drop down. This feature is no longer available in the newer version 15 and 16. `c-tr` is requesting this functionality is restored. 

Teleport V14

![Image](https://github.com/user-attachments/assets/0a6e23b1-f620-4d7a-83be-59e7f6fbea33)


Teleport V16

![Image](https://github.com/user-attachments/assets/0153a100-6ab5-40c9-bb66-6f24c43f07a5)

**Comment by ravicious** [comment]
From what I see, in Teleport v16+ the search input is automatically shown if you have more than 5 clusters (1 root and 4 leaf clusters). This was done in #37104, but it wasn't backported to v15. I'll push the backport soon.
