### ISSUE TITLE
K8s Related Startup Failure, 5.0.0-RC1

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#4862]
### Description

**What happened**:
Upgraded from 4.4.5 to 5.0.0-RC1. Teleport service errors and crashes. 

**What you expected to happen**:
Teleport to start up without issue. 

**How to reproduce it (as minimally and precisely as possible)**:
Specific to my environment, likely. 

### Environment
- Teleport version (use `teleport version`): 5.0.0-RC1
- Tsh version (use `tsh version`): N/A
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04.6 LTS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP

**Relevant Debug Logs If Applicable**
Configuration, logs, and `/var/lib/teleport` here:
https://drive.google.com/drive/folders/1xgGlPDF83hP13y3Iu8bvR3Qd5zVJcufP?usp=sharing

**Comment by travelton** [comment]
@russjones I experienced this issue on my internal test cluster. Assigned to you for visibility. Let me know if I can capture any additional info for you.

**Comment by awly** [comment]
A storage schema change for new k8s service has slipped into 4.4 release.
I later made an incompatible change to this schema on master, without realizing the previous one was included in 4.4.

Will fix the regression, thanks for catching this!
