### ISSUE TITLE
tsh option: only populate ssh agent and not save identity files

### ISSUE THREAD

**Issue by ollyg** [gravitational/teleport#4863]
### Feature Request
A command line option for `tsh` which would suppress storage of the identity files (certificates) and only populate the SSH Agent. An error is thrown if this is requested and the Agent is not available, or the `--out` option is also provided. For example:

````
tsh login --proxy=proxy.example.com --agent-only
````

### Motivation
In order to avoid the security risk of certificates being farmed from a user's home directory and used to access a Cluster. Identity files would only remain in memory within the Agent on the local machine.

### Who's it for?
Anyone - OSS User, Pro, Enterprise

### Other Information
* I tried setting `--out=/dev/null` but it stopped the Agent from being populated as well. Perhaps Agent step requires the identity files on disk already?
* I wonder if this is going to stop `tsh status` from working?
* I will try to find the time to patch and PR but no promises.
* We are an Enterprise customer already - issue here as discussed with @webvictim on Slack support.

**Comment by russjones** [comment]
Change the UX of `tsh` to reduce the number of flags to improve to flow here.

**Comment by russjones** [comment]
@xacrimon Can you implement [RFD #18](https://github.com/gravitational/teleport/blob/master/rfd/0018-agent-loading.md) to resolve this issue?

**Comment by xacrimon** [comment]
on it

**Comment by webvictim** [comment]
@travelton raised an excellent point that we should also expose an RBAC setting to enforce that certificates can only be stored in an SSH agent and must not be written to disk.

**Comment by xacrimon** [comment]
Should we do this in a different PR and open a new issue for it?

**Comment by webvictim** [comment]
@xacrimon Yes, let's not delay the current implementation.

**Comment by xacrimon** [comment]
Solved by #5825
