### ISSUE TITLE
notifications: add ability to create with ttl and custom labels

### ISSUE THREAD

**Issue by rcanderson23** [gravitational/teleport#48631]
What would you like Teleport to do?

1. Create notifications with custom ttl: `tctl notifications create --title="Title" --content="Content" --ttl=1d`
2. Create notifications with custom label: `tctl notifications create --title="Title" --content="Content" --label=owner=bot --label=another=label`
3. Be able to list notifications by label: `tctl notifications ls --label=owner=bot` 

What problem does this solve?
- Ability to create short or long term alerts with custom TTL. 
- Improve ability to get specific set of metrics

If a workaround exists, please include it.

**Comment by sclevine** [comment]
Note that for Cloud, we'd like to create notifications with no TTL that we can add/remove using our own automation.

**Comment by zmb3** [comment]
> Note that for Cloud, we'd like to create notifications with no TTL that we can add/remove using our own automation.

Can you get by with just setting a larger TTL than you'll expect you'll ever need? (180d for example)

**Comment by sclevine** [comment]
> Can you get by with just setting a larger TTL than you'll expect you'll ever need? (180d for example)

We plan to manage notifications declaratively, so this could result in a mismatch between our configuration system (Kubernetes resource spec) and what the user sees after 180 days. That said, if very large values are supported (e.g., 10 years), probably not an issue.
