### ISSUE TITLE
Log spam on client disconnect with agent forwarding

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#4878]
### Description

**What happened**:

Cleanly closing the client session when using agent forwarding produces this error in server log:
```
ERRO [NODE]      agent server for user "awly" stopped: accept unix /tmp/teleport-515338789/teleport-934582.socket: use of closed network connection id:25 local:127.0.0.1:3022 login:awly remote:[::1]:36396 teleportUser:awly regular/sshserver.go:781
```

**What you expected to happen**:

No errors are logged on clean disconnect.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ tsh ssh -A nodename
% exit
$
```

### Environment
- Teleport version (use `teleport version`): 5.0-rc.1
- Tsh version (use `tsh version`): 5.0-rc.1

**Comment by russjones** [comment]
Tracked here https://github.com/gravitational/teleport/issues/4252.
