### ISSUE TITLE
Request roles with tsh 5.0 client gets error

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4895]
### Description

**What happened**:

Attempting to use the `tsh -d login --request-roles=prod` returns a `Error transport is closing`.  Using the 4.4.5 client will work with the same request.

**What you expected to happen**:
Receive  the waiting for requesting of role.

**How to reproduce it (as minimally and precisely as possible)**:

Set two roles and add request roles for the one of them. Have a user be assigned to one role that can request the other. Attempt to request a role.

### Environment
- Teleport version (use `teleport version`): 5.0.rc1
- Tsh version (use `tsh version`): 5.0.rc1
- OS (e.g. from `/etc/os-release`):

### Logs
```bash
ERROR REPORT:
Original Error: *trace.ConnectionProblemError transport is closing
Stack Trace:
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:1613 main.getRequestResolution
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:864 main.executeAccessRequest
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:540 main.onLogin
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:423 main.Run
        /go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:209 main.main
        /opt/go/src/runtime/proc.go:213 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1375 runtime.goexit
User Message: 
```

**Comment by fspmarshall** [comment]
Fixed in #4907
