### ISSUE TITLE
Notification when login in a ressources

### ISSUE THREAD

**Issue by Zathiel** [gravitational/teleport#49034]
Hello Team,
Hope everyone is fine

What would you like Teleport to do?

Add a notification system 
For example : When a connexion is established to a following ressources send a mail (SMTP?) to clusters admin

What problem does this solve?

Improvment in cluster management

If a workaround exists, please include it.

NA

Thanks !

**Comment by zmb3** [comment]
This is not something we'll be looking to do in the near future, but it could be accomplished with a custom integration that reads from the audit log, or by forwarding your audit log to a SIEM that has the ability to program custom alerts.
