### ISSUE TITLE
ha-autoscale-cluster reference Terraform doesn't support Teleport Kubernetes service

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4908]
### Feature Request
There's no listener for port 3026 in our reference HA Terraform which means this setup can't be used to connect to the Teleport Kubernetes service. We should add one.

### Motivation
We offer Kubernetes support via Teleport, we should support it via all deployment methods.

### Who's it for?
Terraform users

**Comment by webvictim** [comment]
I've done most of this work - https://github.com/gravitational/teleport/commit/4e95f297562348bdb93342d319d0de89b6eaeb59

Just need to verify this a bit more and then I'll raise a PR.

**Comment by webvictim** [comment]
I am going to wait for #5032 to be fixed before creating a PR for the Kubernetes listener code.

**Comment by ptgott** [comment]
@webvictim Checking whether this one's still relevant. Thanks!

**Comment by webvictim** [comment]
Pretty sure this one's been fixed for a while now.
