### ISSUE TITLE
Provide uninstall steps for Teleport Automatic upgrader

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#49126]
## Applies To

https://goteleport.com/docs/upgrading/automatic-agent-updates
https://goteleport.com/docs/admin-guides/management/admin/uninstall-teleport

## Details

The uninstall Teleport instructions do not mention the `teleport-upgrade` installation for Linux machine installation.

## How will we know this is resolved?

Provides instructions on removing
- teleport-ent-updater installation
- Remove dirs
   -  /etc/teleport-upgrade.d/
   - /var/lib/teleport-upgrade

This remove the script installation, configuration and state dir.

**Comment by ptgott** [comment]
Thanks! Closing as a duplicate of https://github.com/gravitational/teleport/issues/46593
