### ISSUE TITLE
Wider SDK and API support beyond one language

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#4914]
### Feature Request
- wider SDK support, a single language SDK is not ideal
- API for labeling + CRUD endpoints
- API for roles (CRUD)
- API for mapping labels and environments to roles (CRUD) (or vice versa)

### Who's it for?
Enterprise

**Comment by klizhentas** [comment]
https://github.com/gravitational/teleport/pull/4746

**Comment by JonGilmore** [comment]
I'd love to see this feature as well, would certainly clean things up with our processes around teleport, and provide greater flexibility.

**Comment by stevenGravy** [comment]
Closing as the API has expanded and we have not seen many issues in using the Go API
