### ISSUE TITLE
Nested Access Lists name/link in Access List Members table is misaligned and in the wrong font and wrong size

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#49162]
### Expected behavior:
The name of nested access lists should be in Ubuntu and should align with the left edge of the table header. It should source our "Body 2" font styles so that it matches the rest of the table (and so that it gets updated if we ever change the "Body 2" styles).

### Current behavior:
The name of nested access lists is in Arial, slightly undersized at 13.33px and regular instead of light weight, and is slightly indented due to 6px of padding being added to the text. Looks like this is using a custom-styled button, whereas it might be more appropriate as a link (`<a>`)?

![Image](https://github.com/user-attachments/assets/653bfc21-c366-45e6-aa8d-9c468f3b88eb)

### Bug details:
- Teleport version: 17.0.1
- Recreation steps: Open the detail page for any list with nested lists in it.
- Debug logs: N/A

Thanks to @zmb3 for catching it!

**Comment by kiosion** [comment]
It's a `button` instead of `a` since it uses an onClick handler to navigate, I think the font/padding are props on the base Button that I just forgot to override... should be a simple enough fix
