### ISSUE TITLE
Web UI - Node session recordings, blank node and duration 

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#4919]
The missing values in the Node and Duration columns, these are nodes tunneling in (IoT mode)... Is this a bug? 

<img width="1435" alt="Screen Shot 2020-11-18 at 10 52 38 PM" src="https://user-images.githubusercontent.com/241714/99623535-f50c1900-29f1-11eb-9906-7e7fc90aacfb.png">

```
# search?from=2020-11-18T06:00:00.000Z&to=2020-11-19T05:59:59.999Z&limit=10000 > search.json
```
[search.json](https://drive.google.com/file/d/1AOQZdrWHTALt6bdqenrGVBeboU9paMwA/view?usp=sharing)

### Environment
- Teleport version (use `teleport version`): 5.0.0-rc.2
- Browser version: Chrome Version 86.0.4240.198 (Official Build) (x86_64)

**Comment by alex-kovoy** [comment]
session.end event is missing the following fields:
`server_addr`, `server_hostname`, `session_start`, and `session_stop`  which were added in 4.3. 

```json
{
      "code": "T2004I",
      "ei": 13,
      "enhanced_recording": false,
      "event": "session.end",
      "interactive": true,
      "namespace": "default",
      "participants": [
        "travelton"
      ],
      "server_id": "eb1221ba-a82f-4fa9-9258-9cbb20a45b81",
      "sid": "84f762af-8e0a-4e3e-b440-b25091fcec80",
      "time": "2020-11-19T04:52:21.82Z",
      "uid": "2ad22783-7788-46b8-b49c-135dff1fca26",
      "user": "travelton"
    },
```

**Comment by alex-kovoy** [comment]
So either this event was generated by the older version or this is a bug on our backend.

**Comment by travelton** [comment]
> So either this event was generated by the older version or this is a bug on our backend.

Yep, this was the issue. Upgraded the node and that solved the issue. Closing this bug report. Thanks @alex-kovoy
