### ISSUE TITLE
UI Workflow Master Ticket

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#4937]
# Description
UI workflow break down. For issue: https://github.com/gravitational/teleport/issues/4028

https://app.avocode.com/revisions/77400993/comments/?design=52149182

![Screenshot from 2020-12-10 20-49-24](https://user-images.githubusercontent.com/43280172/101864733-57f05c00-3b29-11eb-896c-3cc5b5419088.png)
![Screenshot from 2020-12-10 20-49-50](https://user-images.githubusercontent.com/43280172/101864745-60e12d80-3b29-11eb-8dff-59d5e5bcf39f.png)
![Screenshot from 2020-12-10 20-49-10](https://user-images.githubusercontent.com/43280172/101864754-663e7800-3b29-11eb-873d-9d7e6a6acde9.png)

### Basic workflow features
Frontend:
- [x] Create a `access requests` tab on side nav under `activity`
- [x] List ONLY the logged in users request
- [x] Create new requests
  - [x] Display roles requestable to select
- [x] Assume approved requests

Backend requirement:
  - [x] GET list of requests
  - [x] Retrieve list of roles requestable

### Extend basic features
Frontend:
- ~~Add filters in list view~~ 
- View requests
  - [x] Delete this request with confirmation dialogue 
  - [x] Display approval threshold required
- Submit review requests
  - ~~Allow reviewer to override rules~~ will not be part of 6.0
  - [x] DENY or APPROVE
  - [x] Optional review message input
- Extend Create new requests
  - [x] Able to type input/list suggested reviewers username to select 

 
Backend requirement:
  - [x] DELETE a request
  - [x] PUT update a request
  - [x] get list of suggested reviewers for a request

### Implement Banner for assumed roles
https://app.avocode.com/revisions/77435353/?design=52233887
![Screenshot from 2020-12-10 20-47-40](https://user-images.githubusercontent.com/43280172/101864778-76565780-3b29-11eb-896a-b791af66cdf2.png)

- [ ] Create a banner that details role assumed, expiration and provide `switch back` button that switches role back to default

**Comment by kimlisa** [comment]
Please review @alex-kovoy @benarent @klizhentas 
I marked questions with `QUESTION:`

**Comment by alex-kovoy** [comment]
@kimlisa thank you for this master ticket! Lets start with the Admin experience which seems the most straightforward and I will answer your questions regarding other parts afterwards.

**Comment by klizhentas** [comment]
> QUESTION: What should happen after clicking on it? Change access role btn text to assumed? Should one approval deny other requests? Can a user switch back and forth between multiple approved requests?

Let's change access role btn text to assumed. One approval or denial should not affect other requests. User can switch back only by using global "Switch back" mode. They can then assume another role from the same modal. They should be able to assume another roles if they click "Switch back" or if they use the same list.

**Comment by klizhentas** [comment]
>Banner QUESTION: Which banner style am I going with?

Style 1

**Comment by klizhentas** [comment]
>QUESTION: Revoking an approved request isn't a feature present in tctl atm, so this state might also just be view request button too.

Yes, let's ignore Revoke

**Comment by klizhentas** [comment]
@alexwolfe will post the latest designs in sketch.com next week here

**Comment by klizhentas** [comment]
@kimlisa @alex-kovoy this code should go in enterprise only repo

**Comment by alex-kovoy** [comment]
> Style 1

@klizhentas the 2nd is more universal as it would work in the terminal/session player as well.

**Comment by klizhentas** [comment]
@alex-kovoy fair point. I am going with style 1 because it does not disrupt the vertical space. We will work on adding a state for the player as well.

**Comment by alex-kovoy** [comment]
After looking at it, taking a bit of a vertical space to handle this use case actually seems fine but if go with the 1st then we are claiming a horizontal space of the top nav which might be more useful for something else. What I like about the 2nd is that we can use it for other notifications by stacking them on top of each other, like notificats/alerts from SalesCenter about expired licenses/payments. Each would have close "x" button to dismiss and would work on every screen.

**Comment by klizhentas** [comment]
Add GRPC api method that returns the current user their context:

```
GetCurrentUserInfo() -> Info
type Info struct {
    CanRequest []roles
}
```

**Comment by kimlisa** [comment]
@alexwolfe @klizhentas ui update:
![image](https://user-images.githubusercontent.com/43280172/100148313-6e23ca00-2e51-11eb-95f9-30b441bfa9f2.png)

changing the expiry time is not a feature present, so i am leaving this one out too

**Comment by alex-kovoy** [comment]
> Add GRPC api method that returns the current user their context:

@fspmarshall I just recall that we do have UserContext on the webapi level which we can use to return this information. If so, we can handle it ourselves.

**Comment by jeffjen** [comment]
Is the workflow related to only requesting access, not approving access?

**Comment by kimlisa** [comment]
@jeffjen you can also approve/deny access request in the UI
