### ISSUE TITLE
Server Addr missing Address  "server_addr": "[::]:3022",

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4938]
### Description

**What happened**:
It doesn't look like we are parsing server addr, because of IPV6 maybe? 

```json
{
  "code": "T2004I",
  "ei": 35,
  "enhanced_recording": false,
  "event": "session.end",
  "interactive": true,
  "namespace": "default",
  "participants": [
    "benarent"
  ],
  "server_addr": "[::]:3022",
  "server_hostname": "i-083e63d0daecd1315",
  "server_id": "a0518380-0d53-4188-ac8b-8ddd8103e45b",
  "session_start": "2020-11-19T19:45:11.238914025Z",
  "session_stop": "2020-11-19T20:29:30.95539198Z",
  "sid": "09d03df7-27d0-4e3e-ba74-6fa9d2d58c4a",
  "time": "2020-11-19T20:29:30.955Z",
  "uid": "6a351453-dea2-467d-8fcb-98fd14106bfa",
  "user": "benarent"
}
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by russjones** [comment]
The auth server might not be detecting `[::]` and converting it to the IP address that it sees from the remote side like it does for `0.0.0.0`.

**Comment by awly** [comment]
`[::]:3022` is the IPv6 version of `0.0.0.0:3022` - the server's listening address.
the code emitting those events should be using the `LocalAddr` of the `ssh.ServerConnection` instead.
