### ISSUE TITLE
White screen after upgrading to 17.0.1

### ISSUE THREAD

**Issue by evrynet1** [gravitational/teleport#49399]
Expected behavior:

Login page loading

Current behavior:

Login page is blank showing white screen (Safari, OSX)

Bug details:
- Teleport version: 17.0.1
- Recreation steps: upgrading from 16.4 to 17.0
- Debug logs

logs are empty but developer console showing the following error:

![Image](https://github.com/user-attachments/assets/4b3014bf-51c0-4666-98c5-3d83f94922f5)

UPDATE: after enabling debug logging I see the followings in logs while visiting the login page:

 Could not authenticate: missing session cookie web/apiserver.go:663

**Comment by zmb3** [comment]
The missing session cookie error is nothing to be concerned with, it just means your session had expired.

Does this happen with all browsers? Are you running multiple proxies?

**Comment by evrynet1** [comment]
@zmb3 looks like something like this maybe: https://github.com/gravitational/teleport/pull/33807

**Comment by zmb3** [comment]
I doubt it's related to a session cookie in any way.

The error is effectively a nil pointer dereference in JS, so there's either a UI bug or something about the way you've deployed/upgraded Teleport is causing the UI to see invalid data.

**Comment by evrynet1** [comment]
I have downgraded teleport back to 16 but no change, very weird.

**Comment by zmb3** [comment]
How are you deployed? I suspect your browser is still seeing old (new?) web assets.

**Comment by zmb3** [comment]
Ah, looks like you might be using an old version of Safari.

`toSorted` was introduced in Safari 16 in 2022. Are you on a version older than that?

https://caniuse.com/?search=tosorted

**Comment by evrynet1** [comment]
@zmb3 you right, I'm on 15.5 however its weird that even if we downgrade the blank page remains while it was working with Teleport 16 previously. To add we also have CloudFlare in front of it however I flushed all cache there and still no change. Gonna ask my collegaues for their browser versions and see if upgrading do the trick. thank you.

**Comment by bl-nero** [comment]
@evrynet1 I'm pretty confident that this is either an incomplete rollout or a caching issue, since the code in question has never been backported to the v16 branch.
