### ISSUE TITLE
Prevent cloud admins from configuring explicty deny on user/role creation/update if only single admin user exists in the cloud licensing dashboard

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#49410]
What would you like Teleport to do?

Prevent cloud admins from configuring explicit deny on user/role creation/update if only single admin user exists in the cloud licensing dashboard.

What problem does this solve?

Recently we ran into an issue with a customer who added the `dashboard-user` role to their sole admin user (default `dashboard-admin` role) before they were able to invite other users or add a secondary admin to the dashboard. This required the cloud team to manually reset this user's roles b/c the `dashboard-user` role has an explicit deny for creating/modifying users and roles which override the allow grant by the `dashboard-admin`

If a workaround exists, please include it.

n/a

**Comment by zmb3** [comment]
This is something we've looked at several times and are tracking internally at https://github.com/gravitational/cloud/issues/10175
