### ISSUE TITLE
UI Loop error after label selection from advanced search

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#49504]
Expected behavior:

A user can select a label after a advanced search for resources.

Current behavior:

A flashing loop will occur in the UI if a use attempts to select a label after a advanced search

https://github.com/user-attachments/assets/1253ac67-d283-401e-9f25-cd17671a49c1

Bug details:
- Teleport version: 17.0.2
- recreated on google chrome: Version 131.0.6778.86 (Official Build) (arm64) on macos 
- Recreation steps

1. Have a resource with more then one label
2. Do advanced search or select one label to start
3. Select another label from the search results

**Comment by pnrao1983** [comment]
![Image](https://github.com/user-attachments/assets/9bbaed93-7052-4de1-97e2-c6cf66e7cfa2)
I got this error when selecting multiple labels:
Firefox Browser and the Teleport is at 17.0.1

**Comment by zmb3** [comment]
`The operation is insecure` doesn't appear anywhere in the Teleport codebase, which suggests that this particular error is coming from somewhere else.

**Comment by paulw99796** [comment]
Thanks Carlos.
I can see there is a fix in the pipeline which is great news.

Regards Paul



OFFICIAL
