### ISSUE TITLE
Access List audit entries doesn't include access list title

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#49542]
Expected behavior:

The access list title is included. This is what users see in the UI, not the uuid.

Current behavior:

The details and listing for Access Lists does not include the access list title. This makes it hard to connect the audit log to the web ui.

![Image](https://github.com/user-attachments/assets/bcfa0d69-5dca-4f5a-91e2-938edd285493)

Bug details:
- Teleport version: 17.0.2
- Recreation steps

1. Create a access lsit
2. View the audit log entry for Access List

**Comment by zmb3** [comment]
Duplicate of #49053
