### ISSUE TITLE
Provide a Verbose Flag for tsh kube ls

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4960]
### Description

**What happened**:
```
tsh kube ls -v
error: unknown short flag '-v'
```

TODO

**Comment by awly** [comment]
@benarent what additional info would you like to see with `-v`?

**Comment by russjones** [comment]
* Last heartbeat time.
* Labels.

**Comment by russjones** [comment]
Maybe also `--format=json`.

**Comment by avinashupadhya99** [comment]
Hi, can I work on this? I've spent a couple of days getting familiar with the code and can make the changes for this.

**Comment by avinashupadhya99** [comment]
How do you get the last heartbeat time of a kubernetes cluster? I was able to get the labels but not the last heartbeat time.
![image](https://user-images.githubusercontent.com/52544819/140685759-5237f345-ab26-4734-bbe8-338a9bb4f4ea.png)

**Comment by webvictim** [comment]
Fixed by #11203
