### ISSUE TITLE
Mobile app for Teleport

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4969]
### Feature Request
It’s very difficult to use Teleport’s web terminal on a phone because there’s no ctrl/alt/tab keys and no arrow keys. Terminal apps like Termius implement these keys to make terminals usable on a phone, but you can’t use terminal emulators with Teleport because none of them support SSH certificates, and there’s no way to run `tsh` to get a certificate on a phone anyway. It might be possible to do by issuing a cert on a computer and copying it to the phone, but this whole flow isn’t ideal.

Even if we just built a very simple app which just embedded a browser view of the web UI with a better keyboard, it would make Teleport much more usable in remote debugging situations where you might just need to run a few commands and scroll through the output.

### Motivation
Sometimes you need to log onto a server but don’t have your laptop with you.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by Valien** [comment]
Just had a customer request for a mobile app that would allow or showcase Application access.

**Comment by modem7** [comment]
Even being able to have a web view w/ virtual keyboard support (especially function keys) would be a great step forward.

**Comment by marcel-st** [comment]
+1 to the request, adding this will make the app more integrated into the Cloud native way of working on any device.

**Comment by bsgrigorov** [comment]
This would be a great feature to add.
