### ISSUE TITLE
enable_cross_zone_load_balancing is missing in our HA terraform

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4974]
Our HA terraform automation is missing cross zone loabalancing.
It is present in our cloudformation.
Without cross zone load balancing, tunnels will not work properly

**Comment by klizhentas** [comment]
https://github.com/gravitational/teleport/blob/3dfc56624b4fdeb5777a6fea3756f9ce95cf7fc4/examples/aws/cloudformation/ent.yaml#L197

**Comment by webvictim** [comment]
We should evaluate more closely whether this is actually desirable or not. Cross-zone load balancing isn't a panacea; it actually introduces more failure scenarios into a deployment and can result in unpredictable behaviour.

https://www.niels-ole.com/cloud/aws/linux/2020/10/18/nlb-resets.html

**Comment by webvictim** [comment]
This is enabled now.

https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/ha-autoscale-cluster/proxy_network.tf#L124
