### ISSUE TITLE
Documentation for `tctl auth sign --kube-cluster` is missing

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4976]
## Summary
The docs from https://github.com/gravitational/teleport/pull/4446 reflecting `--kube-cluster` made it into 4.3 but none of the other versions (4.4, 5.0). We should copy the section on `tctl auth sign` into the other post-4.3 branches too.

**Comment by benarent** [comment]
I've picked this up as part of my 5.0 Kubernetes improvements.
