### ISSUE TITLE
Audit Log does not show all the data when querying audit-events from the DynamoDB exceeds 1MB

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#4977]
When querying audit-events from the DynamoDB, Teleport does not return all events within given time interval when a single query results exceed `~1MB` of data. More info here 

> A single Query operation can retrieve a maximum of 1 MB of data. This limit applies before any FilterExpression is applied to the results. If LastEvaluatedKey is present in the response and is non-null, you must paginate the result set (see Paginating Table Query Results).

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html and 
https://stackoverflow.com/questions/57526653/dynamodb-index-does-not-return-all-data

Steps to repro: 

Generate a lot of events for a given time range (you can use `tsh bench`) and notice that Audit List does not show all results for this time interval. You can also try creating `a single event` ~700kb to have the only this one show up in the Audit log.

Note that in addition to DynamoDB limit, Teleport also has its own limit on maximum number of events it can return (10k).

**Comment by a-palchikov** [comment]
Do I understand this correctly, that the client also needs to support loading of additional data - in effect, some sort of pagination or load more to extend the HTTP API?

**Comment by webvictim** [comment]
It seems DynamoDB's limit for one query is 1MB and after that the `LastEvaluatedKey` entry must be used to paginate and get further events - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.Pagination.html

My guess is that this will require a change to the backend logic which loads events from DynamoDB to handle the `LastEvaluatedKey` entry being set and add it to queries accordingly when the quantity of data to be displayed is high. Depending on how this is implemented, the client may also need pagination - but I would hope that the backend could be made smart enough to handle this on its own.

**Comment by a-palchikov** [comment]
Yes, I'm aware of the DynamoDB behavior - my question was regarding the client since as far as I can tell, this will require changes the HTTP endpoint for the client to request more data and how this is supposed to look like. The server side is already sort of taking the DynamoDB behavior regarding paging into account so it would be easier to extend.

**Comment by alex-kovoy** [comment]
@a-palchikov teleport backend does not support pagination (across all data sources). Instead Teleport has a maximum number of records it can handle, a hardcoded value of 10k. This particular issue is about not being able to return even this 10k number from dynamodb because it does not handle paged dynamodb results.

I will create another issue for adding a proper pagination support to teleport.

**Comment by alex-kovoy** [comment]
related https://github.com/gravitational/teleport/issues/5388

**Comment by a-palchikov** [comment]
@alex-kovoy Again - I understand, but there's no client (web) counterpart since this would be of little use with no proper support for advancing in the stream.

**Comment by alex-kovoy** [comment]
@a-palchikov our even search API is very limited, it only returns 10k of events without an ability to paginate. This ticket is about returning at least this number (10k) events from dynamo db. Right now people cannot view events even for 1 day interval because of this bug. 

The proper solution will be implemented as part of #5388 and it will include both client side and server side changes.

Closed by https://github.com/gravitational/teleport/pull/5381
