### ISSUE TITLE
Tbot: `invalid symlinks mode` error in `tbot kube credentials`

### ISSUE THREAD

**Issue by verdel** [gravitational/teleport#49802]
**Expected behavior:**

Obtaining a valid `client.authentication.k8s.io/v1beta1` response from the command `tbot kube credentials --destination-dir ...`, which is used in the `exec` section of `kubeconfig.yaml` created when running `tbot start -c ...`

**Current behavior:**

```
ERROR REPORT:
Original Error: *trace.BadParameterError invalid symlinks mode &#34;&#34;
Stack Trace:
	github.com/gravitational/teleport/lib/tbot/botfs/fs_linux.go:131 github.com/gravitational/teleport/lib/tbot/botfs.openSymlinksMode
	github.com/gravitational/teleport/lib/tbot/botfs/fs_linux.go:225 github.com/gravitational/teleport/lib/tbot/botfs.Read
	github.com/gravitational/teleport/lib/tbot/config/destination_directory.go:458 github.com/gravitational/teleport/lib/tbot/config.(*DestinationDirectory).Read
	github.com/gravitational/teleport/tool/tbot/kube.go:76 main.onKubeCredentialsCommand
	github.com/gravitational/teleport/tool/tbot/main.go:116 main.Run.func7
	github.com/gravitational/teleport/lib/tbot/cli/cli.go:122 github.com/gravitational/teleport/lib/tbot/cli.(*genericExecutorHandler[...]).TryRun
	github.com/gravitational/teleport/tool/tbot/main.go:256 main.Run
	github.com/gravitational/teleport/tool/tbot/main.go:50 main.main
	runtime/proc.go:272 runtime.main
	runtime/asm_amd64.s:1700 runtime.goexit
```
Bug details:
- Teleport version: 17.0.3

- Recreation steps
1. Create `tbot-cluster-name.yaml`
```yaml
version: v2
onboarding:
  join_method: kubernetes
  token: bot
  ca_pins:
    - ...
storage:
  type: memory
proxy_server: ...
outputs:
  - type: kubernetes
    kubernetes_cluster: cluster-name
    destination:
      type: directory
      symlinks: try-secure
      path: /kubernetes/cluster-name
certificate_ttl: 5m0s
renewal_interval: 5m0s
oneshot: true
```
2. Run `tbot start -c tbot-cluster-name.yaml`
3. Try to run command from `kubeconfig.yaml` `exec` section:
```shell
> tbot kube credentials --destination-dir=/kubeconfigs/cluster-name -d

ERROR REPORT:
Original Error: *trace.BadParameterError invalid symlinks mode &#34;&#34;
Stack Trace:
	github.com/gravitational/teleport/lib/tbot/botfs/fs_linux.go:131 github.com/gravitational/teleport/lib/tbot/botfs.openSymlinksMode
	github.com/gravitational/teleport/lib/tbot/botfs/fs_linux.go:225 github.com/gravitational/teleport/lib/tbot/botfs.Read
	github.com/gravitational/teleport/lib/tbot/config/destination_directory.go:458 github.com/gravitational/teleport/lib/tbot/config.(*DestinationDirectory).Read
	github.com/gravitational/teleport/tool/tbot/kube.go:76 main.onKubeCredentialsCommand
	github.com/gravitational/teleport/tool/tbot/main.go:116 main.Run.func7
	github.com/gravitational/teleport/lib/tbot/cli/cli.go:122 github.com/gravitational/teleport/lib/tbot/cli.(*genericExecutorHandler[...]).TryRun
	github.com/gravitational/teleport/tool/tbot/main.go:256 main.Run
	github.com/gravitational/teleport/tool/tbot/main.go:50 main.main
	runtime/proc.go:272 runtime.main
	runtime/asm_amd64.s:1700 runtime.goexit
User Message: invalid symlinks mode &#34;&#34;

```
- Additional information

This issue was most likely introduced in the following [PR](https://github.com/gravitational/teleport/pull/47130).

In version `16.4.9`, when running the command `tbot kube credentials --destination-dir ...`, the function [tshwrap.GetDestinationDirectory(cfg)](https://github.com/gravitational/teleport/blob/7cd07ee269f8f6e99e31363f87e71c77e5fef1fe/tool/tbot/kube.go#L69) was executed.

This function returned a `DestinationDirectory` object that was implicitly created in the [FromCLIConf](https://github.com/gravitational/teleport/blob/7cd07ee269f8f6e99e31363f87e71c77e5fef1fe/lib/tbot/config/config.go#L764-L789) function when the `--destination-dir` option was used.

The [CheckAndSetDefaults()](https://github.com/gravitational/teleport/blob/7cd07ee269f8f6e99e31363f87e71c77e5fef1fe/lib/tbot/config/config.go#L827-L829) method was executed for the configuration. The [CheckAndSetDefaults()](https://github.com/gravitational/teleport/blob/7cd07ee269f8f6e99e31363f87e71c77e5fef1fe/lib/tbot/config/config.go#L376-L381) method was executed for all Services within it.

And for the `Service` added via the `--destination-dir` option, the `CheckAndSetDefaults()` method executed the [validateOutputDestination()](https://github.com/gravitational/teleport/blob/7cd07ee269f8f6e99e31363f87e71c77e5fef1fe/lib/tbot/config/service_identity.go#L106) method for the `DestinationDirectory`.

[Where](https://github.com/gravitational/teleport/blob/7cd07ee269f8f6e99e31363f87e71c77e5fef1fe/lib/tbot/config/output.go#L56), accordingly, the default values are [set](https://github.com/gravitational/teleport/blob/7cd07ee269f8f6e99e31363f87e71c77e5fef1fe/lib/tbot/config/destination_directory.go#L76-L82), including for `Symlinks`.

Currently, after the following [PR](https://github.com/gravitational/teleport/pull/48186) was merged, the method [tshwrap.GetDestinationDirectory(cfg)](https://github.com/gravitational/teleport/blob/01fc9f0acfde26950c00076180c207aee77f194a/lib/tbot/tshwrap/wrap.go#L136-L146) explicitly returns a `DestinationDirectory` object when the `--destination-dir` option is used. For this object, the `CheckAndSetDefaults()` method is executed.

After the [PR](https://github.com/gravitational/teleport/pull/47130) was merged, when running the command `tbot kube credentials --destination-dir ...`, the function [config.DestinationFromURI()](https://github.com/gravitational/teleport/blob/1bcff22e55a87bed13cd0d88d33ed39f69222b9d/tool/tbot/kube.go#L71) is executed, and the `Symlinks` attribute is not set. As a result, the error `invalid symlinks mode` occurs later in the [botfs.fs_linux](https://github.com/gravitational/teleport/blob/1bcff22e55a87bed13cd0d88d33ed39f69222b9d/lib/tbot/botfs/fs_linux.go#L130-L131).

**Comment by timothyb89** [comment]
This will be fixed once #50370 merges, but for a workaround until the fix is released, you can disable the credential helper with `tbot start k8s ... --disable-exec-plugin` or by setting `disable_exec_plugin: true` in the service configuration like this:

```yaml
# [...snip...]
services:
  - type: kubernetes
    destination:
      type: directory
      path: ./foo
      symlinks: try-secure
      acls: try
    kubernetes_cluster: example
    disable_exec_plugin: true
```
