### ISSUE TITLE
Improve Ansible Documentation

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#4987]
## Summary
We need to improve documentation [here](https://goteleport.com/teleport/docs/admin-guide/#ansible-integration) regarding Ansible. 

> Ansible uses the OpenSSH client by default. This makes it compatible with Teleport without any extra work, except configuring OpenSSH client to work with Teleport Proxy

But how?

We should provide two examples:
A) Configuring ~/.ssh/config to proxy through the Teleport Proxy. 
B) Configuring your Ansible inventory to proxy through the Teleport Proxy.

### Audience
Users of Ansible 

### Location
Existing guide. https://goteleport.com/teleport/docs/admin-guide/#ansible-integration

**Comment by travelton** [comment]
ETA: 12/4

**Comment by benarent** [comment]
Closing as old ticket and latest docs and best practices are here https://goteleport.com/docs/enroll-resources/machine-id/access-guides/ansible/
