### ISSUE TITLE
tsh should have a configurable MOTD

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4988]
### Feature Request
MOTD / Message of the Day lets teams share messages about system use / compliance https://nvd.nist.gov/800-53/Rev4/control/AC-8. We currently offer [PAM MOTD](https://linux.die.net/man/8/pam_motd ) as a solution but this doesn't work for Kubernetes, Applications etc.

A customer would like to set a mostly static ~440 chars message, for one customer it wouldn't change often but we should consider flexibility in the message. Such as providing dynamic info on what role /cluster/label  the user is logging into the system. 

### Motivation
Customer request and adding AC-8 to other protocols 

### Who's it for?
Enterprise

**Comment by gclawes** [comment]
How would motd work for kubernetes? Display when the kubeconfig exec plugin runs?

**Comment by robertogiordani** [comment]
@benarent do you have any update? We need this feature in the 4.4.x version too

**Comment by stmuraka** [comment]
@russjones @benarent should also be an option to be displayed on Web UI

**Comment by russjones** [comment]
@tcsc Let's implement MOTD functionality at `tsh login` time. This makes the most sense looking at AC-8(b):

```
Retains the notification message or banner on the screen until users acknowledge the usage conditions and take explicit actions to log on to or further access the information system; and
```

If we were to do this at `tsh ssh` this would effectively mean you must always have to have a PTY attached and would break (or at least make very difficult) things like scp or automation tooling like Ansible.

**Comment by tcsc** [comment]
I'm planning to add the MOTD to the webapi ping response. How does that sit with everyone?

**Comment by alex-kovoy** [comment]
@russjones if we want to show it in WebUI, where do we want to do it? Show a dialog right after successful login, the same way as we show license notifications? Is it for both versions OSS/Enterprise?
