### ISSUE TITLE
Add the ability to use includes in teleport.yaml 

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4997]
Copied from [community](https://community.goteleport.com/t/add-the-ability-to-use-includes-in-teleport-yaml/892)

With the upcoming release of 5.0 and Applications, teleport.yaml could become very unwieldy if dozens, or even hundreds of web apps are added to the config.

It would be useful to have individual includes in teleport.yaml, or a /etc/teleport.d include directory rather than a single monolithic file.

This could also allow for modularization of teleport, app, proxy, auth sections in a /etc/teleport.d where /etc/teleport.yaml has a single line such as
includedir: /etc/teleport.d

**Comment by webvictim** [comment]
Same thing as https://github.com/gravitational/teleport/issues/3042

**Comment by webvictim** [comment]
Closing this in favour of #3042
