### ISSUE TITLE
Add SNI override for k8s 1.18 config file

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5001]
kubectl added support for SNI overrides in 1.18: https://github.com/kubernetes/kubernetes/pull/88769

we should update tsh to set the tls-server-name field in kubeconfig which should, theoretically, solve the problem of 600+ clusters solved in #3870 for tsh

probably requires updating `kube proxy` GetTLSConfigForClient to match logic in [middleware](https://github.com/gravitational/teleport/blob/master/lib/auth/middleware.go#L227)

verify that solution solves the problem

**Comment by awly** [comment]
@klizhentas should we backport this to 4.4/4.3/4.2?

**Comment by awly** [comment]
@russjones @andrejtokarcik let's try to fix this soon-ish (before 5.1 is fully ready)
Let me know if you'd like to sync to get more details.

**Comment by Aharic** [comment]
Will this fix apply only to tsh client and be supported across releases (so for example, a client running tsh client 4.2 w/ 5.1.2 root cluster)?

**Comment by awly** [comment]
Yes, the fix will apply to `tsh` only.
It will work for any client version we support (at this point, probably 4.3/5/6) and server versions as old as 4.2 if not older.

**Comment by awly** [comment]
> so for example, a client running tsh client 4.2 w/ 5.1.2 root cluster

Users should not be using 4.2 clients against 5.1 servers. See https://goteleport.com/teleport/docs/admin-guide/#component-compatibility

**Comment by travelton** [comment]
Just to be clear, we are back porting this to 4.2, correct? We have a customer needing this in 4.2.

**Comment by awly** [comment]
4.2 is no longer a supported version of Teleport (see https://goteleport.com/docs/faq/#which-version-of-teleport-is-supported)
4.4 is the oldest supported version for now, until v7 comes out.

**Comment by awly** [comment]
Ugh, there's a wrinkle in implementing this: the k8s endpoint serving cert doesn't have the necessary SAN with a cluster name. So simply setting the same SNI value as we do when talking to the Auth API does not work (without disabling client-side TLS verification)

The "correct" way to solve this is to update the SANs we generate for k8s (and all other TLS endpoints) to contain the encoded cluster name. However, that's a bit of a migration. The clients can't set the SNI values until all servers get updated and rotate their serving certs. So backporting it will be a no-go.

Need to think through some other possibilities:
- use a more clever TLS validation that doesn't rely on SNI to figure out the cert issuer
- some hacky usage of an existing SAN to signal "i'm a user, only load the CA of the current cluster"
- check proxy version via the `Ping` endpoint and set SNI if it's a version containing the fix

**Comment by awly** [comment]
The "fix" is here https://github.com/gravitational/teleport/pull/6519
Assuming this is approved, backporting all the way to 4.2 should be easy

**Comment by awly** [comment]
Backport PRs:
- v6 https://github.com/gravitational/teleport/pull/6666
- v5 https://github.com/gravitational/teleport/pull/6667
- v4.4 https://github.com/gravitational/teleport/pull/6668
- v4.3 https://github.com/gravitational/teleport/pull/6669
- v4.2 https://github.com/gravitational/teleport/pull/6670

**Comment by awly** [comment]
All backports merged except 4.3 (pending some unrelated test failures).
