### ISSUE TITLE
Dual Authorization Workflows

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#5007]
Implement [RFD 14: Custom Approval Conditions](https://github.com/gravitational/teleport/pull/5071).

**Comment by benarent** [comment]
How does this differ compared to https://github.com/gravitational/teleport/issues/4736 ?

**Comment by russjones** [comment]
@benarent This ticket is focused on implementing requiring approval conditions (like two approves) before you can establish a session. #4736 is about requiring multiple people to be active within a particular session.
