### ISSUE TITLE
Break out MAU by month over N period of time

### ISSUE THREAD

**Issue by phall-teleport** [gravitational/teleport#50085]
What would you like Teleport to do?
It would be great to break out MAU (monthly active users) by month over a given period within the last year say 3, 6, 12 months. 

What problem does this solve?
Allow a customer to view their MAU count over a longer period of time than last 30 days, this also avoids the issue of on the first day of the new billing cycle the dashboard showing 0 users.

If a workaround exists, please include it.
None currently.

**Comment by zmb3** [comment]
This is already tracked internally at https://github.com/gravitational/cloud/issues/8856
