### ISSUE TITLE
Configurable flag to allow read/only or private sessions

### ISSUE THREAD

**Issue by jaxxstorm** [gravitational/teleport#501]
Currently, the model of teleport is that anyone with an account can join a session and they instantly get the full ability to type commands.

After demoing the application to some security folks at $work, they loved the auditing features and the ability to see what happened, but had concerns about the lack of "permissions" in that people could join sessions even when the desire was simply to do a standard task.

Would it be possible to have a flag or config option to set a join session as read only? Alternatively, have some kind of system whereby when a user attempts to join a session, the original user can grant them permission rather than having a default "open" session.

**Comment by kontsevoy** [comment]
This is being done as part of RBAC see #620
