### ISSUE TITLE
Clickable Labels and Multi-level Label Filtering

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#5021]
### Feature Request
 Requesting that label manipulation is enhanced for the WebUI. The search functionality should work as filters which allow for multiple labels to search for at once. Additionally, it would be nice if clicking on the label displays all hosts with the simular label 

How it will work:
Nodes Labels
server01 - country:Spain os=Centos env=production owner=user01
server02 - country:Spain os=Debian env=production owner=user02
server03 - country:Spain os=Debian env=dev owner=user02
server04 - country:Italy os=Centos env=production
server04 - country:Italy os=Centos env=production owner=user01

If one is to filter the following: Spain
It will list all servers labelled by Spain (server01, server02 and server03)

But if searching for Spanish servers where the owner is user02, the filter could be as this form: Spain+user02 (it's just an example), the result could be: server02 and server03.
Or list all Spanish servers where the user is not user02 (filter: Spain not user02 or something similar)

### Motivation
This would greatly improve the unified resource catalog which would allow to quickly query and locate resources based on labels. The label functionality at the moment is not versatile. 

### Who's it for?
OSS User, Pro, Enterprise

**Comment by benarent** [comment]
Thanks for creating the issue @yjperez, I've added a UI tag and we'll review this in an upcoming design session.

**Comment by nshenry03** [comment]
Yes please, we would like this as well!

**Comment by zmb3** [comment]
@rudream @kimlisa good to close this one?

**Comment by rudream** [comment]
Feature was added in 9.2
