### ISSUE TITLE
Document dynamic registration of Windows desktops

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#50219]
## Applies To

[Windows Desktops](https://goteleport.com/docs/enroll-resources/desktop-access/desktop-access/)

## Details

Document dynamic registration of Windows desktops using `tctl` and Terraform.

## How will we know this is resolved?

A new guide is available, similar to the [Dynamic Database Registration](https://goteleport.com/docs/enroll-resources/database-access/guides/dynamic-registration/), and the [Terraform provider resource list](https://goteleport.com/docs/reference/terraform-provider/resources/resources/) is updated.

## Related Issues

https://github.com/gravitational/teleport/issues/37103

**Comment by zmb3** [comment]
This was documented in #48968.
