### ISSUE TITLE
Teleport fails to request access to application in web UI - 17.0.5

### ISSUE THREAD

**Issue by portswigger-tim** [gravitational/teleport#50326]
Expected behavior:
User is able to create an access request from the resources page of the web UI

Current behavior:
Results in an error: `Cannot convert undefined or null to object`:
![Image](https://github.com/user-attachments/assets/9da0290e-a1eb-4938-ba40-d7e7f031c4ee)

The following errors are viewable in Chrome developer tools: 
![Image](https://github.com/user-attachments/assets/743d2fae-3ac8-477b-9990-5bc88c80e715)

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by zmb3** [comment]
Hi there,

Unfortunately, this is an issue with the 17.0.5 build. We started a 17.0.6 patch release on Friday but ran into issues with GitHub actions, so the fix won't be available until 17.1.0 (slated for tomorrow).

In the meantime, the best option is to downgrade back to 17.0.4.
