### ISSUE TITLE
reversetunnel_connected_proxies metric missing

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#5043]
### Description

**What happened**: I'm trying to read the `reversetunnel_connected_proxies` metric as documented on the [Metrics page
](https://goteleport.com/teleport/docs/metrics-logs-reference/) but it doesn't appear to exist.

**What you expected to happen**: I expect `curl teleport.fqdn:3434/metrics | grep reverse` to show the `reversetunnel_connected_proxies` metric.

I've checked the [code](https://github.com/gravitational/teleport/blob/master/metrics.go) and don't see a mention of that metric, even in the history.

### Environment
- Teleport version (use `teleport version`): 4.4.5
- Tsh version (use `tsh version`): N/A (not using `tsh`)
- OS (e.g. from `/etc/os-release`): Using official teleport-ent docker image.

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by kinghrothgar** [comment]
Can confirm this bug exists in 4.3.5 also.
