### ISSUE TITLE
Access Workflows inconsistently allowing access for elevated Kubernetes access

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5047]
### Description

**What happened**:

A user gets approved for a role with another k8s group.  The access granted by that group is sometimes allowed and sometimes not.  In this scenario a user has by default access to the `developer-oncall` k8s group.  They get access to the `staging-oncall-exec` group.  While the status says they have the new group `Kubernetes groups:  developer-oncall, staging-oncall-exec` the access is sometimes allowed, sometimes denied.

```bash
# kubectl get po -n staging
Error from server (Forbidden): pods is forbidden: User "stevexxxx" cannot list resource "pods" in API group "" in the namespace "staging"
```
**What you expected to happen**:
The access would work.  Removing a x509 pem file seems to help but not sure if that's just a red herring.

**How to reproduce it (as minimally and precisely as possible)**:

Create a `dev` and `staging` namespace. Have groups assigned in different roles for access to those respective namespaces.  Have a role that can request another with access to another namespace. See the attached roles text with examples of `developer-oncall-exec` and `staging-oncall-exec`. 

Create roles that access to different k8s groups.  See example attached
[k8roles.txt](https://github.com/gravitational/teleport/files/5639171/k8roles.txt)

### Environment
- Teleport version (use `teleport version`): 5.0.0 ent
- Tsh version (use `tsh version`): 5.0.0

**Comment by stevenGravy** [comment]
This is only happening with the k8s elevated privileges.  The ssh nodes access works as expected.

**Comment by awly** [comment]
I suspect it's because we [use roles from the auth API](https://github.com/gravitational/teleport/blob/5841b80054e0f08c12f6a34b6402f79b87772215/lib/kube/proxy/forwarder.go#L403-L407) instead of the cert in k8s handler.
With those roles, k8s proxy requests an ephemeral user cert and caches it.

k8s proxy code should trust the roles from the cert, as long as that cert is signed by teleport CA and valid.

**Comment by Aharic** [comment]
Another customer is hitting this. What @awly is saying re: caching makes sense. Based on what I'm seeing in my testing it appears that we never update the local kube cert in the .tsh/keys/cluster directory after role elevation. We set it the first time a user executes a kubectl command but never update it after a user goes through the access-workflows process. 

Users have to either log out and log back in w/ the role-elevation request in the initial login, or they have to have not executed any `kubectl` commands in the less-privileged role before elevating to a higher-privilege role. Alternatively, they can also delete the cert in the .tsh/keys/cluster directory after elevating roles and it will work.

**Comment by tcsc** [comment]
After a bit of digging, it looks as if there is a mismatch in where the elevated roles get written to & read from on the `tsh` side.  

The new roles specified in a new teleport login cert at `~/.tsh/keys/$HOST/$USER-x509.pem`, which is all well and good. But the cert presented for Kubernetes access is `~/.tsh/keys/$HOST/$USER-kube/teleport/$CLUSTER-x509.pem`, which does _not_ have the elevated roles applied, leading the the access denied error.

When logging in from scratch and requesting the elevated privileges at the same time, the Kubernetes certificate is regenerated and contains the elevated roles, leading to the inconsistency in behaviour.

**Comment by benarent** [comment]
( +1 this issue. I had the same issue while recording a video for access controls. Glad @tcsc already has a PR for it )

**Comment by awly** [comment]
@tcsc can this be closed now?

**Comment by russjones** [comment]
@awly @tcsc Yes, let's close looks like it was merged to `master` and backported to `branch/v6` in: https://github.com/gravitational/teleport/pull/6492 and https://github.com/gravitational/teleport/pull/6757.

**Comment by highb** [comment]
I just ran into this today with tsh version `Teleport v6.1.5 git:v6.1.5-0-gdad2a7b5b go1.16.2`, looking forward to getting the fix!

**Comment by highb** [comment]
To follow up; I downloaded `Teleport v6.2.0-rc.1 git:v6.2.0-rc.1-0-g4d311a139 go1.16.2` via the Releases page and it seems to completely solves the issue!
