### ISSUE TITLE
HA Load Balancer Requirements

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#5050]
We should update Teleport documentation to explain that Teleport requires L4 round robin load balancers for the reverse tunnel subsystem and we should also explain how the reverse tunnel subsystem works to explain why this is required.

**Comment by klizhentas** [comment]
@russjones see here: 

https://goteleport.com/teleport/docs/admin-guide/#adding-a-node-located-behind-nat

may be a matter of making this section more visible. What prompted this issue?

**Comment by russjones** [comment]
https://goteleport.com/blog/teleport-discovery-protocol/

**Comment by russjones** [comment]
Let's add examples of how to do this with haproxy and nginx as well for on-prem customers.

**Comment by ptgott** [comment]
Related discussion forum comment: Related discussion comment: https://github.com/gravitational/teleport/discussions/16061#discussioncomment-4248671

**Comment by zmb3** [comment]
Teleport no longer requires L4 load balancers: https://goteleport.com/docs/architecture/tls-routing/#working-with-layer-7-load-balancers-or-reverse-proxies-preview
