### ISSUE TITLE
Disable --insecure in `tsh FIPS` mode

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5073]
### Description

Should not be able to set `--insecure` in `tsh fips mode`

**Comment by tcsc** [comment]
Just realised I misread this ticket and have patched in `teleport` rather than `tsh`. Is there a FIPS mode for `tsh` at the moment (I don't _think_ there is, but could be wrong)? Or would fixing this require changing `tsh` build such that `tsh` knows about build setup?
