### ISSUE TITLE
Document tctl get rc, tctl rm rc etc.

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#5092]
## Summary
It's possible to use tctl to view remote clusters and remove trusted clusters etc., but it is not currently documented.

### Audience
CLI docs

### Location
Add to tctl section

**Comment by zmb3** [comment]
Looks like this is documented now:

- tctl get: https://goteleport.com/docs/access-controls/guides/role-templates/
- tctl rm: https://goteleport.com/docs/setup/reference/cli/#tctl-rm
