### ISSUE TITLE
Proxy advertise address

### ISSUE THREAD

**Issue by gfloyd** [gravitational/teleport#510]
We're using service discovery for our proxy nodes, which means we have a single proxy URL that can be used (like `teleport.service.consul.domain.com:3080`) to connect to any available proxy. Is there a way for the various commands like `teleport status` and `tctl users add` to use this address when it outputs URLs?

For example, if I run `teleport status` I get a session URL like:

`https://<hostname>:3080/web/sessions/<session>`

But that URL is not reachable, so we have to manually replace the `<hostname>` part with our service discovery URL.

If this isn't currently possible, could there maybe be something like an `advertise_address` config option to override that URL?

**Comment by kontsevoy** [comment]
@gfloyd Have you tried setting `--nodename` flag of your proxy toteleport.service.consul.domain.com`? If that won't work, we should fix it. If you're using YAML configuration, the corresponding setting is `nodename`.

**Comment by gfloyd** [comment]
Thanks, that does work.

It's not ideal, since our proxies are also nodes, which leads to multiple nodes with the same name:

```
$ tsh ls
Node Name                         
---------                         
teleport.service.consul.domain.com
teleport.service.consul.domain.com
teleport.service.consul.domain.com
<etc>
```

Not a big deal, just removes the convenience of being able to `tsh ssh <nodename>`.

**Comment by kontsevoy** [comment]
@gfloyd yep. in your case you may want to run two teleport processes on proxy nodes: proxy-only and node-only, with different YAML flags, that would give you exactly the outcome you're looking for IMO. Cheers, closing.

**Comment by gfloyd** [comment]
Ah, I didn't think of that solution! Thanks so much.
