### ISSUE TITLE
Teleport Proxy Kube service does not support ProxyProtocol  V1 

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#5109]
In the HA mode, with a load balancer that is configured with proxy protocol v1 enabled, Teleport Proxy Kube service does not work as it does not understand the proxy protocol (v1).

Steps to reproduce:

1. Have a setup where Teleport Proxy service is behind AWS Classic Load Balaner with proxy protocol enabled
2. Connect some k8s cluster to your Teleport Proxy
3. Try accessing your k8s cluster using Teleport.

```
$ kubectl get pods 
```

timeout.

Related https://github.com/gravitational/teleport/issues/4904

**Comment by klizhentas** [comment]
We need this for cloud release March 1st so adding here.
