### ISSUE TITLE
Can't kubectl exec

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#5129]
### Description

**What happened**:

I'm currently trying to kubectl exec into a pod, but it's not working. This is with 5.0, so if the other fixes made it into 5.0.1, I'lll have the Cloud Team update my instance.

```
➜  ~ kubectl exec --stdin --tty --v=7 shell-demo -- /bin/bash


I1215 17:33:37.162774   84849 loader.go:375] Config loaded from file:  /Users/benarent/.kube/config
I1215 17:33:37.235298   84849 round_trippers.go:420] GET https://asteroid-sun.teleport.sh:3026/api/v1/namespaces/default/pods/shell-demo
I1215 17:33:37.235321   84849 round_trippers.go:427] Request Headers:
I1215 17:33:37.235326   84849 round_trippers.go:431]     Accept: application/json, */*
I1215 17:33:37.235330   84849 round_trippers.go:431]     User-Agent: kubectl/v1.19.3 (darwin/amd64) kubernetes/1e11e4a
I1215 17:33:38.198799   84849 round_trippers.go:446] Response Status: 200 OK in 963 milliseconds
I1215 17:33:38.211542   84849 round_trippers.go:420] POST https://asteroid-sun.teleport.sh:3026/api/v1/namespaces/default/pods/shell-demo/exec?command=%2Fbin%2Fbash&container=nginx&stdin=true&stdout=true&tty=true
 I1215 17:33:38.211572   84849 round_trippers.go:427] Request Headers:
I1215 17:33:38.211578   84849 round_trippers.go:431]     X-Stream-Protocol-Version: v4.channel.k8s.io
I1215 17:33:38.211582   84849 round_trippers.go:431]     X-Stream-Protocol-Version: v3.channel.k8s.io
I1215 17:33:38.211585   84849 round_trippers.go:431]     X-Stream-Protocol-Version: v2.channel.k8s.io
I1215 17:33:38.211589   84849 round_trippers.go:431]     X-Stream-Protocol-Version: channel.k8s.io
I1215 17:33:38.211592   84849 round_trippers.go:431]     User-Agent: kubectl/v1.19.3 (darwin/amd64) kubernetes/1e11e4a
I1215 17:33:38.747025   84849 round_trippers.go:446] Response Status: 101 Switching Protocols in 535 milliseconds
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup Cloud Account
2. Connect Kubernetes using a tunnel
3. https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/ 
4. 
### Environment
- Teleport version (use `teleport version`): `Teleport Cloud 5.0.0`

**Comment by awly** [comment]
This is likely https://github.com/gravitational/teleport/pull/5009
Please upgrade to 5.0.1 (proxy_service and teleport_service) and try again.

**Comment by benarent** [comment]
Thanks @awly I updated both and I can now `kubectl exec` into the pod. 
![image](https://user-images.githubusercontent.com/559288/102351873-0e779500-3f9f-11eb-9492-b0943b74318a.png)

but... now I'm unable to playback the session.  Should I create a new bug for this? 

![image](https://user-images.githubusercontent.com/559288/102351967-2e0ebd80-3f9f-11eb-9f9e-511adbff4b7b.png)
![image](https://user-images.githubusercontent.com/559288/102351977-31a24480-3f9f-11eb-8a61-f166c166b4c8.png)

**Comment by awly** [comment]
Yeah, that's a separate bug.
Can you play it back from the audit log page (clicking on the `Session Ended` icon)?
