### ISSUE TITLE
Enable loading ca pin from files similar to auth tokens

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5162]
### Feature Request
Enable specifying a file to load the CA pin value as allowed for auth tokens.
```yaml
teleport:
   ca_pin: /etc/teleport/ca_pin
```

### Motivation
Allows for more generic loading of ca_pins from secure stores same as enabling for auth tokens. 

### Who's it for?
OSS User, Pro, Enterprise

**Comment by strideynet** [comment]
Closed by https://github.com/gravitational/teleport/pull/12796
