### ISSUE TITLE
Incorrect Node Token Max TTL

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#5163]
## Summary
From the docs, it states the max TTL for dynamic tokens is 48h. However, you can actually generate tokens with longer expiration. We might discourage this due to entropy of the underlying algo (verify with dev), but it's not limited to 48h. 

This is important for Teleport Cloud, because you might need to establish a long lived token that you can bake into an AMI. 

```
tctl tokens add --type=node --ttl 8760h
```

### Audience
All

### Location
Existing docs.

**Comment by benarent** [comment]
As a best practice we shouldn't be encouraging 1yr certificates and should be encouraging the use of shorter lived certs.  

I have written this before, but it'll be good to have more examples. For Teleport Cloud users, users should request a new invite token for each node. This also greatly reduces the attack vector of rouge nodes joining from a long lived invite token. 

> In the above example we've provided two options. One with 1yr (8760h) time to live and one for just 25hrs. As proponents of short lived SSH certificates we recommend the same for automation.

> Handling secrets is out of scope of our docs, but at a high level we recommend using providers secrets managers. Such as AWS Secrets Manager, GCP Secrets Manager, or on prem using a project like Vault. Then running a nightly job on the auth server to sign and publish a new kubeconfig. In our example, we've added 1hr, and during this time both kubeconfigs will be valid.

> Taking this a step further you could build a system to request a very short lived token for each CI run. We plan to make this easier for operators to integrate in the future by exposing and documenting more of our API.

**Comment by inertial-frame** [comment]
@travelton, @benarent - was going through some of our backlog tickets. @benarent thanks for the initial research! Noticed that the `8760h` `ttl` shows up in quite a few docs pages. 

I just checked `tctl help tokens add` and the following CLI message shows up: `Set expiration time for token, default is 1 hour, maximum is 48 hours`. Not sure if that's out of date or inaccurate. If it is, the cli-docs also needs to be updated here: https://goteleport.com/docs/cli-docs/#tctl-tokens-add.

**Comment by inertial-frame** [comment]
Some further investigations:

- `sudo tctl tokens add --type=node  --ttl 8760h` displays `This invitation token will expire in 525600 minutes`
- `sudo tctl tokens add --type=node  --ttl 100000h` displays `This token will expire in 6000000 minutes`
- `sudo tctl tokens add --type=node  --ttl 1000000h` displays `This invitation token will expire in 60000000 minutes`

By contrast:

- `sudo tctl users add tele-admin --roles=editor,access --logins=root,ubuntu,ec2-user --ttl 10000000h` displays
`ERROR: time: invalid duration "10000000h"`
- `sudo tctl users add tele-admin --roles=editor,access --logins=root,ubuntu,ec2-user --ttl 1000h` displays `ERROR: failed to create user invite token: maximum token TTL is 48h0m0s hours`

So, while we should recommend keeping `tctl token` <= 48 hours, it looks like programmatically the cap is > `8760h`.

**Comment by inertial-frame** [comment]
See also: https://github.com/gravitational/teleport/issues/5978

**Comment by inertial-frame** [comment]
The Edit Pass updated all of our documentation to "Correct TTL to short-lived certs - this should be 1-10h for client certificates and 3 months or 2190h for DB". No code changes have been made.
