### ISSUE TITLE
Provide a role option to limit audit log/session replay to permitted resources

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5165]
### Feature Request
Currently users that have access to all resource audit logs entries if they can see the audit log.  Often we receive a request to restrict access in the audit log and session replaying to only those resources the user can currently access.

### Motivation
Restricts access to potentially sensitive information to users who don't have access to those resources.  Also reduces the amount of items in the log a user needs to search there to view their associated resources.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by klizhentas** [comment]
https://github.com/gravitational/teleport/issues/5430

**Comment by zmb3** [comment]
Closing as duplicate of #5430
