### ISSUE TITLE
Increase teleport 'ssh' client compatibility

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#5168]
### Feature Request

The `tsh ssh` command isn't quite as compatible as it could be when comparing it to the openssh `ssh` client binary. This can be problematic when trying to use a system that calls out to an ssh binary. Visual Studio code, for example, has support to provide the full path to an `ssh` type binary. Some options could be implemented as dummy options simply for script compatibility.

* `tsh ssh` is a command plus an extra argument while `ssh` is a single command. (a shell alias helps only some usecases, but not all)
* `tsh ssh` does not support the same set of options that `ssh` does:
  * `-V` - outputs version
  * `-v` - verbose mode
  * `-4` and `-6`
  * `-a`
  * `-B` and `-b`
  * `-C` and `-c`
  * `-E`
  * `-e`
  * and many more

### Motivation

When a teleport user wants to teleport ssh with a program or process that expects openssh, they must go to some non-trivial effort to get the openssh compatibility set up in their ssh_config file. This process is error prone and frustrating.

If there was a `tsh ssh` client that acted more like the openssh `ssh` binary out of the box, this could _greatly_ reduce friction during setup time.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by a-palchikov** [comment]
Is `-F configfile` also being considered?

**Comment by zmb3** [comment]
The goal for `tsh` is not to maximize compatibility and support every option that `ssh` does. Given that, I don't see us making much progress on this issue as written.

If there's a specific workflow that works in `ssh` but can't be used with teleport, I think we should file a separate issue rather than keep this umbrella issue open.

Fair?

**Comment by programmerq** [comment]
Closing in favor of creating separate issues per use case.
