### ISSUE TITLE
Authenticate application users via TLS client key/cert

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#5170]
### Feature Request

Currently, the application feature works via a bearer token that is obtained interactively in a web browser session. Some users need to access the applications with other user agents. Many CLI tools support TLS client certificates/keys to authenticate. In the context of teleport, this could be as simple as setting the path to the key and certificate in `~/.tsh/keys/...` in a config file after logging in via `tsh login`.

### Motivation

Allow non-web-browser user agents a way to authenticate to utilize applications.

### Who's it for?

Enterprise

**Comment by r0mant** [comment]
Same as https://github.com/gravitational/teleport/issues/5213 which was implemented.
