### ISSUE TITLE
Structured warnings for servers/clusters.

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport#5173]
The logs of a busy teleport instance can be very verbose.  Certain warnings which unambiguously demand user action, and are not due to transitive events, aught to be available via `tsh` and possibly even the Web UI.

### Usecases

- Warnings which will be upgraded to errors in future versions (e.g. #5057) are effectively breaking changes, and will eventually lead to failed upgrades if unaddressed for too long.
- Obvious signs of misconfiguration, such as when the proxy LB clearly has session affinity (an issue which can currently be very non-obvious).
- Unsupported version mismatches between servers, or older servers which are missing security patches (this would require storing the latest security-related patch version by role).

### Proposal

Add a new `warning` resource with `SubKind` corresponding to the entity with which the resource is assocaited.  Reading a given warning would require having `read` permissions for both the `warning` resource and the resource assoicated with the specific warning's subkind (to allow warnings to contain meaningful details).  A user meeting this criteria could do something like this:

```
$ tsh warnings ls
Kind  Summary                                                           ID
----- ----------------------------------------------------------------- ------------------------------------
proxy Proxy lb appears to sticky, some nodes may be unreachable         926ac709-1724-44a6-80f8-685236e83c57
auth  Unexpected config field, this will be an error in future versions 3bd15b49-c95a-4c1d-8052-e98f0a4ccb71
# ...
```
```
$ tsh warnings describe 926ac709-1724-44a6-80f8-685236e83c57

Summary: Proxy lb appears to sticky, some nodes may be unreachable

Last report:
  Source: node/d389aed0-7335-4e71-a579-08a5b126ad40
  Time: 18 Dec 20 22:16 UTC

Help:
  The reversetunnel system requires a fair load balancing scheme for proper functioning.  Sticky load balancing
  may cause some nodes and/or clusters to be unreachable.  One of the following may help:
  - Ensure that cross-zone load balancing is enabled (AWS)
  - Ensure that Session Affinity is set to None (GCP)
```

**Comment by klizhentas** [comment]
Any reason this could not be built on top of our existing events with a filter type?

```
$ tctl events --sev=warn
$ tctl events --type=session.start --start=
```

**Comment by fspmarshall** [comment]
> Any reason this could not be built on top of our existing events with a filter type?

@klizhentas Good point, improved event search might be all thats needed for this.  I guess the root of this issue is really that it would be nice to have a unified mechanism for communicating *calls to action*, and making them very visible.  Extrapolating based on a quick glance at the `dynamoevents` impl, I think there may be efficiency concerns with storing high-priority warnings as normal events (expensive to search for in a busy cluster).  Events related to specific sessions are already partitioned together though, no reason we couldn't do that for other kinds of events.

**Comment by klizhentas** [comment]
@fspmarshall I got it this is a slightly different use case. I would record those warning on the auth server and proxy resource level and then showed them as `tctl status`, so people can see errors like time drift between auth servers and proxies and other key errors

**Comment by zmb3** [comment]
@fspmarshall I think we can close this one as you've basically implemented it already with the upgrade system. What do you think?
