### ISSUE TITLE
Kubernetes connect error in leaf cluster

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5185]
### Description

**What happened**:

If the leaf cluster does not map  all of the roles of the  root cluster user, their attempt to perform kubernetes requests can be rejected.  This can sometimes manifest after a user has login to one or more other clusters, not immediately on the first requests.

```bash
$ kubectl get po
Error from server (Forbidden): unknown (get pods)
```

Example:

User
  Root cluster 
     roles: admin, development, staging

  Leaf Cluster
     roles: admin, development
      roles mapping:
           admin -> admin
           development -> development
           staging -> admin

Note that staging maps to admin, so the leaf does not have staging.

Using ssh nodes has not produced this problem.

Logs in attempt to navigate leaf clusters and then `kubectl get po` calls:
```bash
ERRO [PROXY:PRO] Failed to create cluster session: access denied: failed to authenticate with auth server. proxy/forwarder.go:1098
WARN [PROXY:PRO] Failed to get certificate for user: remote-steven@goteleport.com-tele1c, users: map[remote-steven@goteleport.com-tele1c:{}], groups: map[system:authenticated:{} system:masters:{}], teleport cluster: localhost, kube cluster: example3: role clusteradmin is not found. proxy/forwarder.go:1420
ERRO [PROXY:PRO] Failed to create cluster session: access denied: failed to authenticate with auth s
```

If all roles are mapped, 1 to 1 (admin -> admin, development -> development, staging -> staging), there appears to be no errors in navigating clusters and k8s requests.

**What you expected to happen**:

Roles that are not mapped are ignored and not required in the leaf cluster. 

**How to reproduce it (as minimally and precisely as possible)**:

Have multiple roles at the root cluster.  Just map admin to admin for the leaf cluster and add a kube_service to a eks cluster.  Have the user have multiple roles at the root level.  Have the user navigate from the root to the leaf and attempt to do `kubectl` commands. 

### Environment
- Teleport version (use `teleport version`): 5.0.2
- Tsh version (use `tsh version`): 5.0.2

**Comment by awly** [comment]
@stevenGravy could you also provide:
- the `trusted_cluster` definition
- all role definitions for both root and leaf clusters

The error mentions role `clusteradmin` which is suspicious because it's not one of the mentioned roles at all.
