### ISSUE TITLE
Allow leaf admin to at least view roles, trusted clusters, and auth connectors

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#5186]
### Feature Request

Currently, when a root cluster user is mapped to the admin role on a leaf cluster, several items are completely disabled in the GUI. This appears to be to help prevent the admin user from inadvertently disconnecting the leaf cluster from the root cluster.

### Motivation

Root cluster admins who don't have direct leaf cluster access may still need to inspect configurations for validation or troubleshooting purposes.

### Who's it for?
Enterprise

**Comment by zmb3** [comment]
There is no such thing as an "admin" role anymore, so I think we can close this as deprecated.
