### ISSUE TITLE
Deleting a user, deletes all users who has the same prefix.

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#5188]
### Description

**What happened**: 
Example: I had local users `test`, `test1`, `test2`. If I delete `test`, it also deletes `test1` and `test2`. 

However, if I delete `test1`, `test` and `test2` still exists.

**What you expected to happen**:
Only delete the user I specified, not all users with the same prefix.

**How to reproduce it (as minimally and precisely as possible)**:
The behavior is the same in UI and in tctl.
- Create usernames: test, test1, test2
- In UI, delete user `test`, refresh browser to see test1 and test2 gone from list.
- In tctl, run `$ tctl users rm test`, then run `$ tctl users ls`, to see test1 and test2 gone.

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v5.0.0-dev git:v4.4.0-alpha.1-176-gd952671ab-dirty go1.14.1
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): locally

**Comment by awly** [comment]
That's a bug in our persistence logic: https://github.com/gravitational/teleport/blob/master/lib/services/local/users.go#L338-L339
User data is stored in multiple entries under the `/web/users/$username/...` prefix.
We do a `DeleteRange` on `/web/users/$username`, but should be deleting `/web/users/$username/` (extra trailing slash) to avoid catching users with the same name prefix.

Quick grep for `DeleteRange` shows the same problem for `DeleteTunnelConnections` and `DeleteResetPasswordToken`

**Comment by r0mant** [comment]
Possible duplicate: https://github.com/gravitational/teleport/issues/12328.
