### ISSUE TITLE
Problems with the ports when connecting tsh

### ISSUE THREAD

**Issue by guanana** [gravitational/teleport#521]
Hi,

I'm having some issues to deploy the different teleport I have in the environment. It seems that now you can specify the port of the proxy where you want to connect but for some reason I'm having this weird issue:

proxy_service:
  enabled: "yes"
  listen_addr: teleport-auth.example.local:3033
  **web_listen_addr: teleport-auth.example.local:3083**
  tunnel_listen_addr: teleport-auth.example.local:3034
  https_key_file: /etc/teleport-infra/teleport-auth.key
  https_cert_file: /etc/teleport-infra/teleport-auth.crt

> [root@teleport-auth ~]# tsh -d --proxy=teleport-auth.example.local:3033 --user smith2 ls
> INFO[0000] no host login given. defaulting to root       file=client/api.go:208
> INFO[0000] using FSLocalKeyStore                         file=client/keystore.go:73
> ERRO[0000] open /root/.tsh/keys/teleport-proxy-1.example.local:3033/smith2.cert: no such file or directory  file=client/keystore.go:166
> INFO[0000] SSH_AUTH_SOCK is not set. Is local SSH agent running?  file=client/api.go:1027
> ERRO[0000] open /root/.tsh/keys/teleport-proxy-1.example.local:3033/smith2.cert: no such file or directory  file=client/keystore.go:166
> INFO[0000] connecting to proxy: teleport-auth.example.local:3033 with host login root  file=client/api.go:819
> DEBU[0000] checking host key of teleport-auth.example.local:3033
>   file=client/keyagent.go:105
> **DEBU[0000] not using loopback pool for remote proxy addr: teleport-auth.example.local:3080**  file=client/api.go:993
> dial tcp 10.211.64.109:3080: getsockopt: connection refused

I tried with another proxy of the cluster but because I have the port 3080 assigned for another instance it allows me to put my password and token but because the instance is the incorrect one 3080 not 3083 it returns me a message with denied error

**Comment by kontsevoy** [comment]
@guanana your `tsh` command did not specify the HTTPS proxy port (only SSH). Try `--proxy=teleport-auth.example.local:3033,3083`

**Comment by guanana** [comment]
Seems so, working.

Thanks
