### ISSUE TITLE
Session recordings has blank for node column for kubernetes

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5212]
### Description

**What happened**:

The session recordings list has a blank entry for the node when a k8s exec session is listed.  This example shows first a k8s exec and then a ssh node exec.  Note the latter does have a node.

![image](https://user-images.githubusercontent.com/60704961/103441913-5f35f180-4c1f-11eb-9925-cd8446f66346.png)

**What you expected to happen**:

The cluster name, pod name and namespace listed along with a k8s icon like in the audit log.  There is no context given other then the session id which requires the user to navigate the audit log.

**How to reproduce it (as minimally and precisely as possible)**:

Run a exec session to a k8s pod that is recorded.

### Environment
- Teleport version (use `teleport version`): 5.0.2

**Comment by russjones** [comment]
@stevenGravy Looks like @awly has merged, can you rebuild and try? Or we can get you binaries if that works for you.
