### ISSUE TITLE
Application Access - Curl REST APIs after tsh login

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#5213]
### Feature Request
After authenticating using `tsh login` users want to be able to use Curl to make REST API requests against their Application Access applications. For example, `curl https://grafana.myurl:3080/api/search`

### Motivation
Many customers interact with their applications programmatically rather than via a web UI.

### Who's it for?
Enterprise

**Comment by klizhentas** [comment]
@r0mant would be cool if we could support HTTP and HTTP/2.0 as well for GRPC
