### ISSUE TITLE
Change auto-updated Docker image version format

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#5216]
As per https://github.com/gravitational/teleport/blob/e7cfd031e89b442bb4b56882d18bbc08f6b2e697/rfd/0012-teleport-versioning.md, we are moving to a more semver-compatible model where any Teleport 5.x.x component will be compatible with any other 5.x.x component. This means that our current [quay.io tag format](https://quay.io/repository/gravitational/teleport?tag=latest&tab=tags) for auto-generated Docker images (https://github.com/gravitational/teleport/issues/3357, https://github.com/gravitational/teleport/pull/3793) needs to change from 5.0, 5.1, 5.2, 6.0, 6.1, 6.2 to 5, 6 etc.

We should publish `quay.io/repository/gravitational/teleport:5` which always contains the latest `5.x.x` version. The next image will then be `quay.io/repository/gravitational/teleport:6` which is the latest `6.x.x` version.

**Comment by awly** [comment]
We can also keep `5.1`, `5.2` etc tags for consistency, if it's not too much extra work

**Comment by webvictim** [comment]
We can certainly keep these; it might be  a good idea to prevent confusion. I'll leave the decision up to @benarent

**Comment by benarent** [comment]
As @awly let's keep 5.1, 5.2 at least until we launch 6.0. For auto-generated changes I think it's best to make changes with the major version and communicate it out to customers. For this, I would just start with version `quay.io/repository/gravitational/teleport:6` at the same time we release 6.0.0

**Comment by webvictim** [comment]
I've written a PR to add the missing 5.1 image, as that should have been done when 5.1 was released.

I'll write a separate PR to also add a `quay.io/repository/gravitational/teleport:5` image to be compatible with the new versioning scheme (pointed to latest `5.x.x`) then we can update this to `quay.io/repository/gravitational/teleport:6` when 6.0.0 is released and make an announcement about the change in the release notes.

@benarent What should our support matrix be here? We currently build images for 5.1 and the previous two branches (so 5.0 and 4.4) - should we be doing `teleport:4`, `teleport:5` and `teleport:6` for these new versions?

**Comment by awly** [comment]
> What should our support matrix be here?

We'll be in a weird transition state for a bit.
Right now, supported versions are `teleport:4.3`, `teleport:4.4` and `teleport:5`.
On next release, it'll be `teleport:4.4`, `teleport:5` and `teleport:6`.
And then `teleport:5`, `teleport:6`, `teleport:7`.

Speaking of which branches, we'll probably want `branch/v5` and `branch/v6` instead of 5.0, 5.1, etc.

Does that sound ok?

**Comment by webvictim** [comment]
I agree with both points. That all sounds fine to me.
