### ISSUE TITLE
Migrate to AWS registry from Quay.io

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5225]
### Feature Request

To consolidate our software distribution sources, move off quay.io registry to AWS. 

Consider using AWS managed registry, it will let us use our existing SSO and IAM for publishing.
Otherwise, consider alternative AWS and K8s hosted registry solutions that integrate with K8s and AWS well.

**Comment by TravisGary** [comment]
Pricing for AWS registry is by data transfer out compared to quay's pricing by number of private repo's (we pay $30/month for 10 currently).  Its very likely we will pay much more with AWS

AWS offers 500GB/Month for free for public repo data transfer out and [then I think its $0.09 per GB after that](https://aws.amazon.com/ecr/pricing/).  Its very likely I could negotiate us some credit for switching.  

The reporting from Quay is not great on bandwidth used or number of downloads each month so its hard to make an estimate on the costs of AWS.

**Comment by TravisGary** [comment]
It seems like quay's activity logs only show up to 100 events over the last month so I can't estimate much unless there is a better way to get analytics.

**Comment by knisbet** [comment]
Just adding in that support for docker content trust should be a consideration. I don't know off hand if there is actually any requirement on the repo side so it might not matter, but we should probably check.

Some of the kubernetes draft STIGs I think were mentioning this to some degree, and I also have it as a consideration for our internal roadmap.

**Comment by wadells** [comment]
One feature I like about ECR (or would prefer to see in other options) is tag immutability:

https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-tag-mutability.html

This encourages stability in published artifacts and reproducible usage of those tags, something that has bitten us in the past: https://github.com/gravitational/gravity/issues/1482#issue-610541654

Unfortunately for ECR, the setting looks to be all or nothing for a repository, meaning we couldn't have a floating x:5 and immutable x:5.0.1 in the same repo.

**Comment by wadells** [comment]
> If we replace Quay we also need to replace its built in [vulnerability scanner Clair](https://github.com/quay/clair) The static analysis of our images was a key part of our SOC2 audit. Since Clair is open source we could host it and continue to use it or consider alternatives.

https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html uses Clair behind the scenes and is built into ECR.

**Comment by wadells** [comment]
Otherwise, I don't know that we have any special requirements from the gravity side.  Our build/CI is a heavy consumer of quay, including lots of service accounts/"robot users", but none of the usage is advanced.

**Comment by wadells** [comment]
Also, we probably can't turn off quay entirely as long as we support Gravity.  It has quay image paths baked into the product.  For example

https://github.com/gravitational/gravity/blob/5.5.56/lib/defaults/defaults.go#L1215

**Comment by wadells** [comment]
If you're looking at this, take https://github.com/gravitational/teleport/issues/4159 under consideration too.

**Comment by jimbishopp** [comment]
This is almost done. Tracking this work in https://github.com/gravitational/cloud/issues/1839
