### ISSUE TITLE
Deploy Docs on Release Promotion

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#5236]
Right now we have a separate docs deployment pipeline outside of Drone, since our docs contain a changelog, this step has to be done manually for each release.

https://goteleport.com/teleport/docs/changelog/

We should be able to deploy docs from Drone and should automatically redeploy docs when cutting a release.

**Comment by wadells** [comment]
I'm winding down Jenkins. If this isn't taken care of before I get to it, I'll put some time into migrating  https://jenkins.gravitational.io/job/Teleport-Deploy-Docs/. My timeline to get to this is end of January or top of February.

**Comment by webvictim** [comment]
I think the work that @klizhentas and @iAdramelk are doing is likely to change this as well.
