### ISSUE TITLE
Show kubernetes cluster labels in `tsh kube ls`

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#5244]
### Feature Request

`tsh kube ls` output should include labels

### Motivation

Consistency with SSH nodes and observability

### Who's it for?
OSS User, Pro, Enterprise

**Comment by awly** [comment]
Also add the number of `kubernetes_service` instances serving the cluster.
This may help debug cases where a user configures `kubernetes_service` for two distinct clusters with the same `kube_cluster_name`.

**Comment by r0mant** [comment]
This was fixed.
