### ISSUE TITLE
Session uploads not completing after restart and backoff behaving unexpectedly.

### ISSUE THREAD

**Issue by auhsoja** [gravitational/teleport#5254]
### Description

You might have to bear with me on this one because I don't have administrator privileges or an intimate relationship with our teleport system. However, my boss asked me to investigate this.

**What happened**:
After restart for some of our nodes, there seems to be a continuous, rapid upload failure as seen in the following images:

![one](https://user-images.githubusercontent.com/25823209/104034841-69b43600-519f-11eb-9cd1-884958146104.jpg)
![two](https://user-images.githubusercontent.com/25823209/104034871-72a50780-519f-11eb-889d-ee531c8036ab.jpg)
![three](https://user-images.githubusercontent.com/25823209/104034859-6de05380-519f-11eb-9fbf-9377c809c2e7.jpg)

We believe that the backoff behavior is not functioning properly because all of these events happen in the same second, and the issue is consistent (i.e. I am told that if you check the status after waiting for a while, you will still see a similar log).

When I examined the code, I had a few theories about what's going on (assuming there is, in fact, a problem). First of all, while I don't think it's the problem, it seems like good practice to add Jitter to the `LinearBackoff` created in `lib/events/filesessions/fileasync.go:172` (i.e. add `Jitter: utils.NewJitter()` in the instantiation).

Also, I was curious about whether this case (see below image) would actually get called, or if there was some possibility for `backoff` to be Inc'ed repeatedly, resetting the timeout channel.

![image](https://user-images.githubusercontent.com/25823209/104036822-e3e5ba00-51a1-11eb-9217-b36ab5d56710.png)

That said, this would still require a constant stream of event emissions, and I am not sure how that would happen based on the things I've looked at thus far.

**What you expected to happen**:
A small number of failures happen, and then after a few seconds they are retried and then succeed. The retrials should not all be in the same second.

**How to reproduce it (as minimally and precisely as possible)**:
I am a little bit less sure about this one. I am really sorry that this might be a little bit vague and unhelpful, but I can only tell you what I know. Suggestions and next steps would be appreciated if there's not enough to go off of here.

### Environment
- Teleport version (use `teleport version`): `Teleport v5.0.0-dev git:v4.4.0-alpha.1-197-g986bf08ab-dirty go1.15.4`
- Tsh version (use `tsh version`): `Teleport v5.0.0-dev git:v4.4.0-alpha.1-197-g986bf08ab-dirty go1.15.4`
- OS (e.g. from `/etc/os-release`): 
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicated hardware.

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by benarent** [comment]
Hi @auhsoja , Thanks for creating a comprehensive issue.

 A few things:
1. We completed a large refactor of the session uploader with 4.4 See https://github.com/gravitational/teleport/pull/4045 . Can you check which version the main Teleport Cluster is running?
2. You are running `Teleport v5.0.0-dev` ~ which is a dev tag. Could you try `v5.0.2` https://goteleport.com/teleport/download 
3. If you don't need the sessions / recordings you can remove them by deleting or manually exporting them from `/var/lib/teleport/log`
4. If you email me your company name, I can get our CS team to follow up with your Teleport Admin. ben@goteleport.com

**Comment by auhsoja** [comment]
I don't think we need the session logs; we're just trying to optimize for reliability and worried the above behavior was associated with a recent crash. That said, I'm a little bit confused about how deleting the logs after the fact will fix the issue. Is there a setting in the `yaml` file to suppress the uploads?

With respect to the other questions, I will get that information immediately.

**Comment by benarent** [comment]
> Is there a setting in the `yaml` file to suppress the uploads?

Yes, you can but it's on the auth server. It has these options.

```
# This section configures the 'auth service':
auth_service:
    # Optional setting for configuring session recording. Possible values are:
    #    "node"  : sessions will be recorded on the node level  (the default)
    #    "proxy" : recording on the proxy level, see "recording proxy mode" section.
    #    "off"   : session recording is turned off
    #
    # EXPERIMENTAL *-sync modes
    # Proxy and node send logs directly to S3 or other storage without
    # storing the records on disk at all. *-sync requires all nodes to be
    # upgraded to 4.4.
    #
    #    "node-sync" : session recordings will be streamed from node -> auth -> storage service
    #    "proxy-sync : session recordings will be streamed from proxy -> auth -> storage service
    #
    session_recording: "node"
```

**Comment by auhsoja** [comment]
Oh wonderful. This seems like exactly the type of solution we're looking for (assuming the problem really is limited to the session uploads). I'll see about making this change on the relevant nodes as soon as I can.

**Comment by auhsoja** [comment]
Update: After setting `session_recording: "off"` on our auth server and restarting both the auth server and a node, the issue seems to persist as seen here:

![image](https://user-images.githubusercontent.com/25823209/104387618-83d67700-5505-11eb-96a4-d72ccca21974.png)

Any further suggestions?

**Comment by benarent** [comment]
@auhsoja Can you make sure both auth and node are up to date with the latest version of Teleport.

**Comment by auhsoja** [comment]
After upgrading everything, things seem to be working as expected. Thanks so much for your help and sorry for bothering you about something so simple. I suppose upgrading everything should've been the first step as opposed to the last...
