### ISSUE TITLE
teleport proxy ignores multiple auth_servers

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#5255]
### Description

**What happened**:

When specifying multiple `auth_servers` in the teleport proxy config file, the proxy fails to connect to anything but the first server listed.

**What you expected to happen**:

Teleport proxy should try connect to all listed auth servers instead of only the first one

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`): 4.4.6
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by robertogiordani** [comment]
@programmerq when the fix will be available?

**Comment by pschisa** [comment]
It would be nice if all resources (ssh_service, kube_service, db_service, app_service) respected multiple auth_servers for failover at a minimum.

**Comment by zmb3** [comment]
We're actually heading in the opposite direction and introducing config version 3 which will support both `proxy_server` and `auth_server` (singular).

Deployments with > 1 proxy/auth should use a load balancer.
