### ISSUE TITLE
Method to manipulate and standardize case of returned values from saml and oidc connectors before matching

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#5267]
### Feature Request
Ability to convert all received values from a SAML or OIDC connector to either uppercase or lowercase before processing and matching against a given set of values.

### Motivation
Some customers have configured integration with external auth services such as ADFS that they have no control over. These services may at times return a mix of lower case and upper case values which are impossible to fully anticipate and match, even with regex. It would be helpful if we could have an option to convert all values to lowercase/uppercase before processing against a match criteria to make it easier to integrate with environments that customers may not have full control over.

### Who's it for?
Enterprise

**Comment by TravisGary** [comment]
I have made this mistake a few times not getting the case correct for groups that come from Okta.  Personally I don't see much value for roles being case sensitive.

**Comment by rocking-e** [comment]
This would be a very helpful feature. Right now we support 3 AD domains via SAML/Okta. And it seems at least one group can't decide how to spell their group so it has 3 different case-different spellings in the 3 AD domains.

**Comment by russjones** [comment]
What are the functions you are looking for? `lower` and `upper`?

**Comment by webvictim** [comment]
Another +1 for `lower` and `upper` functions from a prospect I'm working with.

**Comment by Aharic** [comment]
upper and lower would work for the original use case discussed above.

**Comment by sagardeo2105** [comment]
What's the timeline on this feature. 
We're running into similar issue and would like to use `lower/upper` function or string manipulation on the returned values from oidc connector.

**Comment by nklaassen** [comment]
I believe this issue is better tracked by https://github.com/gravitational/teleport/issues/6707 which will solve this issue
