### ISSUE TITLE
Provide multi group mapping example for OneLogin documentation

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5274]
## Summary
The OneLogin example only shows how to map a single group admin.  Most would want to map multiple groups to different Teleport roles. 

### Audience
Enterprise users

### Location
Update existing OneLogin guide

**Comment by ptgott** [comment]
@stevenGravy Looks like this includes two groups: https://github.com/gravitational/teleport/blame/master/examples/resources/onelogin-connector.yaml

Is there anything else we need to do on this?

**Comment by ptgott** [comment]
Closing since the example already shows how to map the `admin` and `dev` groups to the `editor` and `access` roles
