### ISSUE TITLE
Ability to add extensions to user certificates generated by teleport

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#5275]
### Feature Request
Ability to add extensions to user certificates generated by teleport.

### Motivation
Customer would like to SSH into the Github Enterprise Server/Cloud and use a user certificate signed by the teleport.
However GHES/GHEC requires a user certificate that has a 'login@github.com' extension, among others. 

### Who's it for?
Enterprise

**Comment by Aharic** [comment]
Reference documentation for GHES/GHEC: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/about-ssh-certificate-authorities

**Comment by somethingnew2-0** [comment]
Similar to https://github.com/gravitational/teleport/issues/7830

**Comment by benarent** [comment]
This has been fixed by https://goteleport.com/docs/setup/guides/ssh-key-extensions/#step-23-configure-the-github-key-extension
