### ISSUE TITLE
Ability to select whether the one-click server add script calls to proxy or auth server

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#5282]
### Feature Request
Would be helpful if we could flesh out the one-click node script that is generated through WebUI so that users could select whether it calls to a proxy or directly to the auth server.

### Motivation
This would be helpful in environments where customers run primarily in IoT mode.

### Who's it for?
Enterprise

**Comment by zmb3** [comment]
cc @r0mant in case this is something that can be considered with teleport discover
