### ISSUE TITLE
Teleport should have option to reload config file.

### ISSUE THREAD

**Issue by leif-ohlin** [gravitational/teleport#533]
Our setup:
One "main" server/cluster running all 3 services.

Other servers set up as their own cluster at different locations. These are firewalled/NATted.

To access a server we use tsh through the "main" proxy to the other locations.
When you add a new location you have to setup the trust - this means adding the location servers certificate to the configuration of the "main" cluster (and vice versa) - then restart the main cluster.
This restart makes all ongoing connections die. If instead of a restart the service could reload its configuration file it'd be quite a bit more useful.

**Comment by klizhentas** [comment]
@leif-ohlin one quick way to solve this problem is to start using etcd backend - in this mode teleport does not need to reload any configuration and all changes are dynamic and take effect instantly.

**Comment by kontsevoy** [comment]
@leif-ohlin I think reliably applying configuration changes without full restarts is going to be incredibly complex (and complexity is something you always need to avoid when dealing with security products). Say, you change listening ports or re-generate certs, the sockets would have to close anyway. 

While I agree, this is a very useful suggestion, I do not see us allocating time to do this. Internally we primarily use `etcd` configuration backend, although it's not well-documented at this moment. So perhaps what we should do instead, is to document `etcd` integration better (or even add consul, as other folks have requested). 

I hope I am not disappointing you too much by closing this? We'll spend our time elsewhere to make your life even easier. Promise. ;-)
