### ISSUE TITLE
Create Drone IAM users/roles/policies programmatically using Terraform (and import current state)

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#5336]
Drone's IAM users and policies are currently configured fairly well using the principle of least privilege, but they were created by hand rather than using Terraform.

We should:
- add the definitions of all users as currently implemented into Terraform
- run `terraform import` on the current users/policies
- make sure that no changes are proposed.

**Comment by zmb3** [comment]
Closing since we're moving away from Drone
