### ISSUE TITLE
Reduce Teleport's glibc version requirements

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#5338]
Using Ubuntu 18.04 as our buildbox base image means that binaries created by Drone have a minimum glibc version of 2.27. We should build our binaries in a buildbox with a lower glibc version to make them more compatible with older distributions.

_Originally posted by @webvictim in https://github.com/gravitational/teleport/issues/4754#issuecomment-749587441_:

Statically-compiled binaries would fix this (#4896) but are untested and have historically introduced a number of other issues with unpredictable DNS resolution when running in Docker/Kubernetes.

One workaround for this which would prevent huge fragmentation of our build matrix while also not needing us to switch to statically-compiled binaries may be to just change the Teleport buildbox to always bootstrap and build Go from source in a container which uses an older glibc version; we do this already for [CentOS 6 binaries](https://github.com/gravitational/teleport/blob/master/build.assets/Dockerfile-centos6). We could use CentOS 7 which would give us glibc 2.18.

Here's the list of required glibc versions that I know of so far (run `ldd --version` to see the required glibc version for a given distro):

| Distro | glibc version |
| --- | --- |
| CentOS 6 | 2.12 |
| CentOS 7 | 2.18 |
| CentOS 8 | 2.28 |
| Ubuntu 18.04 | 2.27 |
| Ubuntu 18.10 | 2.28 |
| Ubuntu 20.04 | 2.31 |
| Ubuntu 20.10 | 2.32 |
| Fedora 32 | 2.31 |
| Synology DSM 6.2.3 | 2.20 |
| Amazon Linux 2 | 2.26 |
| NVIDIA Jetson AGX | 2.27 |

**Comment by zmb3** [comment]
We should get back down to GLIBC 2.18 when @LKozlowski's rustls changes are finalized, which turns out to be good enough since we no longer support CentOS 6.

**Comment by webvictim** [comment]
This is fantastic - back to one RPM/package for all :)

**Comment by jakule** [comment]
I think this issue can be closed as we switched our buildbox to CentOS 7 https://github.com/gravitational/teleport/pull/14062
