### ISSUE TITLE
db vs database?

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#5349]
### Description

**What happened**:
When trying Teleport Database Access, I initially tried `db` vs `database`. I would suggest we support 'db' alongside database to be consistant with other flags such as `tctl auth sign --format=db` 

```
➜  ~ tctl tokens add --type=db
error: role Db is not registered

➜  ~ tctl tokens add --type=database
The invite token: 750XXX
This token will expire in 60 minutes.
Fill out and run this command on a node to start proxying the database:

> teleport start \
   --roles=database \
   --token=750XXX \
   --ca-pin=sha256:11221b201c5b472d1df5ef627355a27deffc1cdafb1b85f0ffa74ad0cf7617b4 \
   --auth-server=teleport.asteroid.earth:3080 \
   --db-name= \
   --db-protocol= \
   --db-uri=


Please note:

  - This invitation token will expire in 60 minutes.
  - Database address  must be reachable from the new database
    service.
  - When proxying an on-prem database, it must be configured with Teleport CA
    and key pair issued by "tctl auth sign --format=db" command.
  - When proxying an AWS RDS or Aurora database, the region must also be
    specified with --db-aws-region flag.
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`): Teleport 6.0 Alpha

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

AWS

**Comment by r0mant** [comment]
@benarent Do we want to support both, or would just renaming it to `db` be fine? We still can I think while we're in alpha. The reason is that right now each role name (auth, app, etc.) maps to a single Teleport process role so I'm just thinking adding support for multiple (db/database) would require non-trivial changes for little gain.

**Comment by benarent** [comment]
After reviewing the I think we should just go with `db' as this follows our short pattern of `app`, `kube` etc.
