### ISSUE TITLE
Include multiple k8s clusters kube_service in documentation

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5354]
## Summary

Provide documentation on how to include multiple k8s clusters in a teleport agent.  This should also include how to run the `get-kubeconfig.sh` script and then add that into a kube config used by `kube_service`. 

The kubernetes migration document provides details on this but is not immediately available to doc web.  Users have to search or find in the github docs directly to find this information.

### Audience
All k8s users

### Location
Additional guide off of Kubernetes guide

**Comment by awly** [comment]
This will show up at https://goteleport.com/docs/kubernetes-access/guides/standalone-teleport/ once 6.2 is released
