### ISSUE TITLE
Quick start guide and installation docs different on installing Teleport

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5357]
## Summary
The steps to install Teleport are different in the installation guide and quick start.  It's not clear why you would have different versions. 

### Audience
All
### Location
Same guides.

**Comment by inertial-frame** [comment]
Wonder if some of the TLS steps from https://goteleport.com/blog/letsencrypt-teleport-ssh/ might also be useful here?

**Comment by inertial-frame** [comment]
Should be corrected now from 6.1+. Thanks!
