### ISSUE TITLE
TLS certificates from Let's Encrypt broken in teleport

### ISSUE THREAD

**Issue by leif-ohlin** [gravitational/teleport#536]
I've set up a teleport proxy with a public IP using Let's Encrypt TLS certificates.
Because Let's Encrypt itself is not trusted it uses trust from DST CA to sign certificates to it's users.

With other web servers this is usually not a problem as you tell the web server to either use a chain certificate as a supplement to the normal certificate or a fullchain certificate that includes both.

With the teleport proxy I cannot get this to work. No matter which type of certificate (cert.pem / chain.pem / fullchain.pem) I use the tsh client always warns me that I'm using a self-signed certificate (which is both right and wrong - depending on your point of view)

Is there any way to make the proxy present the chain certificate?

**Comment by klizhentas** [comment]
The chain should work actually, we need to dig into this

**Comment by kontsevoy** [comment]
@leif-ohlin does `curl` work with Lets Encrypt certs on that box? We use Lets encrypt too and on some older Linux machines their certificates aren't in the system's `capath`, BTW here's the list Teleport uses:

https://golang.org/src/crypto/x509/root_linux.go

**Comment by leif-ohlin** [comment]
I'm at customers the next couple of days, I'll get back to you when I'm back in the office.

**Comment by leif-ohlin** [comment]
First of all:
/var/lib/teleport/webproxy_cert.pem is a softlink to the fullchain.pem - a soft link because of how let's encrypt works. Certs only have a 3 months lifetime - a copy of the file has been tested, same result.
webproxy_key.pem points to the private key.

Certificate paths is:
1. Our teleport server.
2. Let's Encrypt Authority X3 
3. DST Root CA X3

curl says:
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

awk -v cmd='openssl x509 -noout -subject' '
    /BEGIN/{close(cmd)};{print | cmd}' < /etc/ssl/certs/ca-certificates.crt | grep "DST Root" says:
subject= /O=Digital Signature Trust Co./CN=DST Root CA X3

on both server and client.

A test from https://www.ssllabs.com/ssltest/ shows that the cert from Let's encrypt is an "extra download" and thus not provided by the server.

**Comment by leif-ohlin** [comment]
Created another teleport server for the lab at home - here it actually works.
Home lab runs 1.0.5, not working server runs 1.1.0.

openssl s_client -showcerts -connect FQDN:port

shows that the not working sever only sends the one certificate and not the chain.
I'll try installing the 1.0.5 version and check if this helps.

**Comment by leif-ohlin** [comment]
Found the error. Sorry for wasting your time.
"someone" had added https_cert_file: directive to the teleport.yaml file. This stopped teleport from checking the links I made in /var/lib/teleport

**Comment by klizhentas** [comment]
no worries, glad you've sorted it out! Thanks for using Teleport!
