### ISSUE TITLE
Add repo path build parameter to Drone.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#5361]
**Description**

Add the ability to specify a repo build path to Drone when building from a tag. This allows building from repos other than `teleport.git`.

**Comment by webvictim** [comment]
Related to https://github.com/gravitational/teleport/pull/5283

**Comment by webvictim** [comment]
The required Drone changes for this should be implemented already, we just need to test.

**Comment by webvictim** [comment]
This has been tested now and various other improvements added. It's possible to run the full test suites, plus builds on `push` and release builds on `tag`.
