### ISSUE TITLE
Use Teleport for application to application connections

### ISSUE THREAD

**Issue by ghakfoort** [gravitational/teleport#5368]
Every server you want to access has a Teleport Node running. Users can access this server through teleport. It would be nice if other processes on this server can use the teleport node process to "proxy/secure" a connection from an application on the server to an application on another server. 

For example: Every server has a telegraf agent which collects metrics ands send it to InfluxDB. If we are able to route this connection between Telegraf and InfluxDB through Teleport, we can secure it and manage it in a teleport kind of way instead of managing it the old fashioned way (firewall changes for every new server/project).

**Comment by awly** [comment]
We were discussing this idea recently.
The approach was to help facilitate mTLS connections using a teleport-issued certificate.

This wouldn't tunnel everything through SSH, so you would still need firewall changes. Teleport would just handle the credential management. But I like the idea of using a tunnel to avoid opening up a bunch of ports, as long as it doesn't defeat the purpose of the firewall.

**Comment by zmb3** [comment]
App access is the recommended way to secure and manage connections to other services.
