### ISSUE TITLE
First Steps - Questions

### ISSUE THREAD

**Issue by SebTM** [gravitational/teleport#537]
Hello,

thank your for providing a powerful and fancy tool to mange server-access-control. I've head from teleport by a fellow but he didn't used it and so I hope, you can give me some answers.

**Situation:** We are starting with a complete new infrastructure. We will have about 20 servers and would like to use teleport to manage the access-control and monitoring of user-actions (session-recording).

**Plan:** We are planning to have one entry-server acting as teleport-proxy, auth-server and also as something like a "jumphost". All technicians will be able to connect here with a "non-root-user" (ssh-key) to be able to use "tsh"-command.

**Questions:**
- Would you recommend this procedure? (Jumphost, connecting to proxy/auth-server by key, ...)
- As I learned while installing/using a test-instance of teleport, I have to specify at creation of the user which users he can access on the server, right?
  - Can't I change this setting without recreating the user?
  - Is it good practice to use "root" here?

Thanks for your help!

**Comment by kontsevoy** [comment]
To answer your questions:

a) Yes, in fact "jump-host" is exactly what Teleport proxy is. In a simple use case, the proxy would run with all 3 roles (node, proxy, auth) and the rest of your cluster would only run in `node` role. In a more comprehensive setup, you'd move `auth` role to a separate machine that only org. admins have access to.

b) Yes, you have to assign the allowed machine logins to each Teleport user at creation. "root" is no less secure than a regular sudo user, but it's often recommended to disable SSH for root.

c) Unfortunately there is "modify user" `tctl` command yet, so it's a bit inconvenient (you have to delete/re-add users if you need to change mappings) but we're releasing this feature very soon.

I hope this helps!

**Comment by SebTM** [comment]
Thank you for the fast reply!

a) That sounds good - where is the benefit to run node on the jumpserver if everyone have to connect to it by key-auth as there is currently no tsh-client for every os? As If I would move the auth-server to another machine, how can I "declare" that user a - has access to it and user b not? Only if I have different user on the server? (like root on all "uncritical" machines and "admin" for auth-server and some other "critical"?)

b) Do I need to run a ssh-server after having a working teleport? or can I just remove it?

c) I think from time to time many user will need it :D

**Comment by kontsevoy** [comment]
a) Well, without `node` on a machine, you have no SSH access to it. So if you're running `proxy`-only on a host, how will you maintain it? The answer is either have a `node` role enabled as well, or have `sshd` installed side-by-side, just for superuser-administration purposes.

To restrict users we recommend creating OS logins that act as, basically, roles: `backup`, `dev`, `test`, `admin` - whatever you see fit. You can use Chef/Ansible/Salt to create them on all of your machines and configure box-level permissions to these users. Then you'd map them to Teleport accounts.

b) See above. Perhaps to feel more confident, you could still have `sshd` as a backup, configured to trust only a small number of keys for your administrator(s), while regular users should be restricted to Teleport only.

c) Yes! :) See, Teleport is a library and we're internally running it against `etcd` back-end so we're updating users via `etcd` API, but you're right, there should be tctl command as well.
