### ISSUE TITLE
Issues with Example Docker-Compose Steps

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#5376]
## Summary
From a prospect:
1. Config generated by init container contains hardcoded /path/to/license.
2. Compose itself doesn't allow bind mounting (the step where it mounts license file)
Interesting that the container doesn't provide enough information in the error, so I've had to run it in debug to find this out.

**Comment by a-palchikov** [comment]
Can you please link to the docker compose file for reference?

**Comment by jon-can** [comment]
https://goteleport.com/teleport/docs/enterprise/quickstart-enterprise/#quickstart-using-docker-compose
