### ISSUE TITLE
Use protobuf definitions instead of JSON schema for storage data validation

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#5402]
### Feature Request

Remove all JSON schema usage from `api/types` and rely on protobuf schema for validation.
Use https://godoc.org/github.com/gogo/protobuf/jsonpb or something similar to parse storage data to/from in-memory protos.

### Motivation

JSON schema was added when teleport didn't use protobufs yet.
Protobufs already define the schema for data, and it can be used to validate JSON blobs while parsing.
This makes JSON schema redundant. Removing it will reduce the amount of boilerplate needed when working on data storage changes.

Caution: we mix github.com/gogo/protobuf with google.golang.org/protobuf, which may cause surprising behavior. For example, github.com/golang/protobuf/jsonpb is deprecated in favor of google.golang.org/protobuf/encoding/protojson which doesn't work with gogoproto-generated stubs. But github.com/gogo/protobuf/jsonpb from gogoproto doesn't respect JSON struct tags.

### Who's it for?

Teleport team

**Comment by Joerger** [comment]
This should come after #5384, which moves the JSON schemas and refactors the marshalling logic.
