### ISSUE TITLE
Remote leaf cluster connection status and heartbeat no longer accurate?

### ISSUE THREAD

**Issue by dnwe** [gravitational/teleport#5405]
### Description

**What happened**:

We had previously written some automatic cleanup based on looking at the output of `tctl get rc`  json output to find remote leaf clusters that were showing offline, and cross referencing those against our own inventory to find deprovisioned clusters.

However, at some point in recent versions of the Teleport 4.x series on our remote cluster setup (kube-api proxy only) we are no longer seeing accurate reporting for the heartbeat and connection status on the `tctl get rc` output. Even after the remote Kubernetes clusters are long deprovisioned, the heartbeat timestamp is inexplicably up-to-date and the connection status shows as online

**What you expected to happen**:

If the remote Kubernetes clusters targetted by a remote cluster definition are deleted, the Teleport heartbeating should no longer succeed and the connection status should transition to offline

**How to reproduce it (as minimally and precisely as possible)**:

Setup a main and remote leaf cluster configuration of Teleport kubernetes definitions and test all is working. Then deprovision/delete the Kubernetes cluster referenced by the remote leaf config. The heartbeating should start to fail and the connection status should transition to offline

### Environment
- Teleport version (use `teleport version`): v4.4.7-0-g19cca224e 
- Tsh version (use `tsh version`): v4.4.7-0-g19cca224e 
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.1 LTS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): IBM Cloud

**Browser environment**

- N/A

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by dnwe** [comment]
I did notice that https://github.com/gravitational/teleport/pull/4234 first landed in v4.4.0 and we upgrade to that around October — so that may be related?

**Comment by dnwe** [comment]
Please let me know if you need `teleport --debug` output from either the "main" or the "leaf" teleport processes?

**Comment by awly** [comment]
Tested this locally with 4.4.7. When I stop the leaf cluster (kill the teleport process), `tctl get rc` on the root reports `connection: offline` within a minute and the `last_heartbeat` timestamp stays on the last reported value and is not updated.

When the leaf disappears, root proxy debug logs should print something similar to:
```
DEBU [SSH:PROXY] Closed connection [::1]:39426. sshutils/server.go:440
INFO [PROXY:SER] Cluster agent disconnected. cluster:leaf reversetunnel/remotesite.go:343
DEBU [PROXY:SER] Requesting connection to @remote-auth-server [] in remote cluster. cluster:leaf reversetunnel/remotesite.go:598
WARN [REVERSE:L] Re-init the cache on error: transport is closing. cache/cache.go:333
DEBU [DISCOVERY] Disconnecting connection to leaf [::1]:39426: agent disconnected. reversetunnel/conn.go:168
WARN [PROXY:SER] Request for connection to remote site failed: leaf is offline: no active tunnels to root found. cluster:leaf reversetunnel/remotesite.go:607
DEBU [REVERSE:L] Reloading Linear(attempt=0, duration=0s). cache/cache.go:344
DEBU [PROXY:SER] Deleting connection record. cluster:leaf reversetunnel/remotesite.go:346
DEBU [AUTH]      Dial to addr teleport.cluster.local failed: leaf is offline: no active tunnels to root found. auth/clt.go:312
WARN [REVERSE:L] Re-init the cache on error: connection error: desc = "transport: Error while dialing leaf is offline: no active tunnels to root found". cache/cache.go:333
DEBU [REVERSE:L] Reloading Linear(attempt=1, duration=1s). cache/cache.go:344
INFO [PROXY:SER] Cluster connection closed. cluster:leaf reversetunnel/remotesite.go:320
DEBU [PROXY:SER] Requesting connection to @remote-auth-server [] in remote cluster. cluster:leaf reversetunnel/remotesite.go:598
```
(where `leaf` is the name of my leaf cluster).

@dnwe a couple questions:
- can you paste the output of `tctl get rc` on the root with these lingering leaf clusters? even if it's redacted and partial output
- are you sure that deprovisioning your k8s cluster on IBM cloud immediately stops all the pods and nodes? Is it possible that the leaf teleport instance keeps running?
- can you paste the debug teleport logs from the main cluster, right at the moment when a leaf gets deprovisioned?
- are leaf instances also running 4.4.7?

**Comment by dnwe** [comment]
@awly ah ok, from your reply it sounds like I may have just misunderstood how the heartbeating and connection status works in practice. I assumed that the teleport pods were heartbeating the kube-api endpoint for the remote cluster they were responsible for proxying to. It sounds like they're heartbeating from the main teleport pod against the local leaf cluster pod instead?

![image](https://user-images.githubusercontent.com/8060970/106162096-9eecec00-617f-11eb-8d32-b3b297ed756d.png)

I _thought_ that if "cluster-2" (e.g.,) in the above was deprovisioned and the kube-api endpoint stopped responding then the connection status for "cluster-2" in cluster-main (where all the teleport pods are running) would move to disconnected.

**Comment by awly** [comment]
Heartbeats go from the leaf cluster pod to the main cluster pod, not the other way.
Leaf cluster pods don't do any heartbeating to the k8s API. You can only notice that a k8s cluster disappeared if you make a request through teleport. And even then, the teleport cluster status (`tctl get rc`) is not affected.

A leaf teleport cluster can proxy k8s API connections, but it can also exist on its own and proxy SSH connections to non-k8s VMs. This is why a leaf teleport cluster status is not tied to a k8s cluster status.

If you want automated cleanup of teleport instances when k8s clusters get deleted, consider using Teleport 5.0 with the new k8s integration: https://goteleport.com/teleport/docs/kubernetes-access/#option-1-standalone-teleport-gateway-for-multiple-k8s-clusters (instead of trusted clusters).
In this setup, you run a teleport pod inside of the leaf k8s cluster. When this k8s cluster gets deleted, the pod goes away too and the main teleport cluster cleans up the entry automatically.

**Comment by dnwe** [comment]
Thanks for the clarifications. Apologies for the confusion here
