### ISSUE TITLE
teleport-kube-agent chart v0.0.2 broken

### ISSUE THREAD

**Issue by defreng** [gravitational/teleport#5406]
### Description

**What happened**:
The new teleport-kube-agent chart version 0.0.2 is broken, since it already contains a `db_service` configuration section although it only references the teleport 5 application

The pods are stuck in a crashloop with:
```
error: unrecognized configuration key: 'db_service'
```

Also, version 0.0.1 disappeared from the Helm chart repo.

**What you expected to happen**:
* Released chart versions to stay on the Helm repo (referenced in https://charts.releases.teleport.dev/index.yaml )
* Ensure compatibility of the helm chart with the referenced teleport image

**Comment by webvictim** [comment]
@defreng Thanks for raising this issue. I've fixed the problem in `teleport-kube-agent` and pushed an updated 0.0.2 version to https://charts.releases.teleport.dev.
