### ISSUE TITLE
Feature Request: lock and unlock user

### ISSUE THREAD

**Issue by zbindenren** [gravitational/teleport#541]
Would be a great feature to lock and unlock users with the command:

```
tctl users lock <login>
```

User still exists, but cannot login.

```
tctl users unlock <login>
```

User can login again.

**Comment by guanana** [comment]
👍

**Comment by kontsevoy** [comment]
@zbindenren this has been released with 2.3

**Comment by zbindenren** [comment]
Thx

**Comment by mpitt** [comment]
@kontsevoy I've tried to unlock myself, but the syntax from this issue doesn't work:
```
# tctl version
Teleport v2.3.0 git:v2.3.0-0-g92bfdcd5
# tctl users unlock <myself>
expected command but got "unlock"
```

**Comment by kontsevoy** [comment]
@mpitt this works differently. See [the docs](https://gravitational.com/teleport/docs/2.3/admin-guide/#editing-users)

**Comment by mpitt** [comment]
Thanks for the link, I must have been looking at the wrong version of the docs.
