### ISSUE TITLE
Add SSH support to tsh for Windows.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#5415]
Currently `tsh.exe` only supports `tsh login` to fetch certificates which then have to be used with OpenSSH.

Add the ability to use `tsh ssh` to `tsh.exe`. In theory this should now be possible now that Microsoft added Windows Pseudo Console (ConPTY) [1][2].

Some relevant reading:

[1] https://github.com/creack/pty/issues/95
[2] https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/

**Comment by klizhentas** [comment]
https://github.com/creack/pty/pull/109/files

**Comment by webvictim** [comment]
Related to #4989
