### ISSUE TITLE
"database or disk is full" ~ How I killed my Teleport Instance. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#5424]
### Description

**What happened**:

While replicating https://github.com/gravitational/teleport/issues/3235 I accidentally locked myself out of my cluster by filling up diskspace for a Teleport node running proxy+auth+node. 

After sending in a few GB of files, my SCP failed. After I tried to `tsh ssh` into the box I got the below message. 

```bash
➜  ~ tsh ssh root@i-083e63d0daecd1315
mkdir /var/lib/teleport/log/upload/streaming/default/multi/537ef133-b5b8-49bf-9e20-4533e21bd0b9: no space left on deviceerror: ssh: could not start shell
```

After trying to tsh login, I got a disk full message.

```bash
➜  ~ tsh login --proxy=teleport.asteroid.earth:3080 --auth=github
error: database or disk is full
```

The UI also threw this unformatted JSON error message. 

![image](https://user-images.githubusercontent.com/559288/106053558-cc626880-609f-11eb-9483-b5aafcebe02c.png)

**What you expected to happen**:
We could file this bug under user error. e.g. Don't fill your disk up and expect to login a small Teleport instance.

Logging it here to see if we can improve error messages etc.

**Comment by benarent** [comment]
I was able to still access the system using OpenSSH backup. 
```
➜  Downloads  ssh -i "mbp.pem" ubuntu@eXX

Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-1030-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Jan 27 21:11:06 UTC 2021

  System load:  0.48              Processes:             110
  Usage of /:   99.8% of 7.69GB   Users logged in:       0
  Memory usage: 33%               IPv4 address for eth0: 172.31.13.139
  Swap usage:   0%

  => / is using 99.8% of 7.69GB

```

**Comment by benarent** [comment]
Other thoughts: It would be good for users using single node and local filesystem, it'll be good to report on disk usage.

**Comment by webvictim** [comment]
We should be able to fail gracefully like ssh does, i.e. allow logins to continue if there is no disk space. Maybe we can also add an option to fail hard if sessions can't be recorded, for situations where it isn't desirable to allow people to log in without a session recording.

**Comment by zmb3** [comment]
@gabrielcorado is this resolved by #12916?

**Comment by gabrielcorado** [comment]
Yes. We have [an integration test](https://github.com/gravitational/teleport/blob/master/integration/integration_test.go#L1020) with similar reproduction steps from this issue.

**Comment by HeenaBansal20** [comment]
@webvictim , I am facing little different issue where my Vm's get no longer available in teleport GUI once they got out of disk.  Do we have any configuration which we can use that will allow VM's to stay in teleport though they become unreachable.

**Comment by gabrielcorado** [comment]
@HeenaBansal20 The issue we solved was related to the session start flow and recording. If your VM instance is no longer available as a resource at Teleport, it could indicate your agent is unhealthy or failing in some procedure it executes. In that case, could you open a separate issue and provide more details (like reproduction steps, logs, and Teleport version)? Thanks.
