### ISSUE TITLE
Join links printed by tctl aren't correct for joining via proxy

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#5429]
### Description

**What happened**: Running `tctl tokens add` or `tctl nodes add` on Cloud instances prints an auth server address that's wrong for two reasons:

1) It's an internal pod IP rather than an externally-accessible address (`proxy_service.public_addr`)
2) It uses port 3025 rather than 3080 (it should use the same port as `proxy_service.public_addr`)

**What you expected to happen**: `tctl` and/or the server should know that for Cloud instances, nodes and other services must join via the proxy. It may be that we should add a setting to Teleport which dictates whether nodes are expected to join via auth or proxy, then set this printed address accordingly.

See diff below for changes that should happen.

```diff
$ tctl tokens add --type=node --ttl=1h

The invite token: 238179057b40cde5eca6647352a24fae
This token will expire in 60 minutes

Run this on the new node to join the cluster:

 teleport start \
   --roles=node \
   --token=238179057b40cde5eca6647352a24fae \
   --ca-pin=sha256:deaaec29ace4e8584606015dfa682501703141ea979fa5d30a1d5085097e2c9e \
-   --auth-server=100.96.82.200:3025
+    --auth-server=example.teleport.sh:443

Please note:

  - This invitation token will expire in 60 minutes
-  - 100.96.82.200:3025 must be reachable from the new node
+ - example.teleport.sh:443 must be reachable from the new node
```

**How to reproduce it (as minimally and precisely as possible)**: Run `tctl tokens add --type=node` on a Cloud instance.

### Environment
- Teleport version (use `teleport version`): Teleport 5.1.0

**Comment by mcbattirola** [comment]
merged on master
awaiting backports to remove `blocked` tag

**Comment by pierrebeaucamp** [comment]
I'd keep it until it's in a tagged release so we can deploy it.
