### ISSUE TITLE
windows binary ?

### ISSUE THREAD

**Issue by anjanb** [gravitational/teleport#543]
hi there,

  I see that there are binaries for linux and mac. Today, windows can natively run docker applications. Why are you leaving out those of us who choose windows ? and those of us who are forced to use windows.

A lot of applications are developed for windows -- it should not be too difficult to port this to windows.

thank you very much,

**Comment by jakoch** [comment]
See #465 and #481

**Comment by kontsevoy** [comment]
@anjanb You're correct, it _feels_ possible that's why we're keeping #481 open. Teleport has 3rd party dependencies on some libraries that don't run on Windows yet. We'll look into either contributing to them or swapping them for a more portable counterparts. Closing this one as a dupe
