### ISSUE TITLE
Audit log should capture full 'tsh ssh' cli command

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#5447]
### Feature Request

When users interact with `tsh ssh`, they have the ability to pass several options to the `tsh` command. These currently do not appear in the audit logs. The audit logs should capture this information to help enable true audit capabilities for the entire teleport workflow

### Motivation

Some user-supplied options could have security concern consequences. Those should be auditable. 

### Who's it for?

Enterprise

**Comment by klizhentas** [comment]
@programmerq what options are required?
