### ISSUE TITLE
Application access UI is not scalable

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#5448]
### Feature Request

Currently, the applications dashboard works only for scenarios where a user doesn't have a lot of applications. Feedback from customers is that it will be challenging to use it if they want to expose hundreds or thousands of apps:

> But since we will need to display hundreds (and potentially thousands) - a better web ui is needed there. Currently it looks like the system is engineered to support 1-15 applications which is not our use case. A similar to the servers screen table view with search bar is preferable.

Some ideas on how to make the UI scale better (cc @alexwolfe):

* Show as a table instead of cards-based view.
* Searching/filtering by names/labels.
* Pagination.
* Bookmarking?

### Motivation

To support users who want to connect large numbers of applications.

### Who's it for?

Application access users.

**Comment by alex-kovoy** [comment]
@rudream here is the link to [avocode](https://app.avocode.com/revisions/81546856/?design=54920357)

**Comment by alex-kovoy** [comment]
@rudream could you create a PR? It needs to go to 7.0 release

**Comment by alex-kovoy** [comment]
closing it in favor of https://github.com/gravitational/webapps/issues/373 and https://github.com/gravitational/webapps/issues/374

Pagination, table view, sorting, and filtering have been implemented.
