### ISSUE TITLE
Duplicate UUID's in teleport

### ISSUE THREAD

**Issue by FartParty** [gravitational/teleport#546]
I'm running into a really weird issue with 1.1.0.  I currently have teleport publish a ttl'd token every 10 minutes my ephemeral nodes can access and use to register with the cluster.  When I do this, however, I quite often run into two different instances that have the exact same teleport UUID.  When this happens, the nodes are only intermittently reachable in the cluster and they often look like two systems attempting to use the same key.

To fix this issue, I typically have to clear teleport's state and then re-register the nodes.  When the nodes come up, they do not have any teleport state at all.

It seems to me like teleport isn't creating unique ID's for new nodes when using the same TTL token, or, I'm doing something totally wrong.

**Comment by kontsevoy** [comment]
@FartParty how do instances get added? Are you using any kind of disk imaging in your workflow? Host UUID is stored in `/var/lib/teleport/host_uuid`. Perhaps you're re-using pre-existing `/var/lib/teleport` somehow when adding new nodes? (maybe via AWS AMI or similar method)

**Comment by FartParty** [comment]
@kontsevoy I double checked and there is no data that exists in `/var/lib/teleport` when we see duplicate uuid's.  For the time being we have a workaround where new nodes generate their own host_uuid file and then join the cluster using the token.

**Comment by kontsevoy** [comment]
@FartParty we've made an honest effort to reproduce it in many different ways, and so far we're failing ;) 

Here's an idea:
Can you confirm that you end up with two machines with identical `/var/lib/host_uuid` file? Thank you for the help!

**Comment by kontsevoy** [comment]
@FartParty I am going to mark this as `user-error` for now, since we're unable to reproduce it (and not for the lack of trying!) but we'll keep it open for a while waiting for someone else to provide more info.

**Comment by coreywagehoft** [comment]
I am using disk imaging in my work flow.  Is there a good way to generate a new UUID?

**Comment by klizhentas** [comment]
Ev will correct me if I'm wrong, but should be as easy as:

```
uuid -v4
2c1a7e93-5a2c-43b0-9de1-5001176c661c
```

**Comment by kontsevoy** [comment]
I would say that `/var/lib/teleport` (AKA "data dir") is not supposed to be shared between different Teleport nodes. The recommendation would be to wipe out that directory after "image restore" operation. 

Even doing `uuid -v4` isn't necessary, simply deleting this file will force Teleport to create a new one.

**Comment by coreywagehoft** [comment]
Ok thanks for the clarification!  Should not be a problem for me to do that on a startup.  Great product to far!
