### ISSUE TITLE
Wrong url shows

### ISSUE THREAD

**Issue by guanana** [gravitational/teleport#547]
Hi,

When I create a new user from the auth server it display a url that is not correct. The server is only auth and we have another to be the proxy, instead the proxy host it shows the auth host

https://teleport-auth:3080/web/newuser/79ae1fc5acd2c26d10764178b02d0615

instead of 

https://teleport-proxy-1:3080/web/newuser/79ae1fc5acd2c26d10764178b02d0615

If you change the url manually you can access the webpage (teleport-proxy-1)

**Comment by kontsevoy** [comment]
@guanana `teleport-auth` is the hostname that gets detected and suggested by default. In reality there is no way of knowing for sure what DNS points to, so the `tctl` tool tries to suggest something useful, but ultimately (and this is reflected in the documentation) users need to know the hostnames their proxies are running on.

**Comment by guanana** [comment]
That I meant is not the name, is the port number

**Comment by kontsevoy** [comment]
@guanana `tct` reads that port from `/etc/teleport.yaml` by default. If you have another config file, you have to use `tctl --config another-config-file.yaml` when adding users.
