### ISSUE TITLE
Compile ARM binaries with BPF support

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#5482]
Teleport ARM binaries aren't compiled with BPF/BCC support, so cannot be used for enhanced session recording. Turns out that this is a bit of an oversight, which was only discovered when the `libbpfcc` and `libbpfcc-dev` packages actually got installed as part of an Ansible run and builds started failing.

The reason these packages won't work is because they're version 0.3 which is too old - we need at least 0.11. The ARM buildbox is running a 4.19 kernel with Debian buster, so there's a few potential solutions:
- upgrade the distro to something newer (Ubuntu 18.04+) which does have high enough versioned `libbpfcc` packages
- find someone compiling their own `libbpfcc` 0.11+ package and providing it for Debian buster
- (probably the best solution) build the BPF libraries from source
  - the problem is that the ARM buildbox is a Raspberry Pi and it will take forever to compile
  - it will also likely make builds fail during the compilation process due to resource contention/timeouts, so it should be done at a weekend.

**Comment by zmb3** [comment]
Tracking this at #14206 now.
