### ISSUE TITLE
Add Code Examples of automated SSH workflows with Teleport using Go

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#5489]
Documentation request:
Request to have documentation or examples provided for using Teleport with Go to perform simple automated SSH workflows such as establishing an ssh session with teleport and running some commands over the established session.

**Comment by ptgott** [comment]
@pschisa Just to make sure I understand, does "teleport" mean the Proxy Service, a host running the SSH Service, or both? What would be some examples of commands to run? Thanks!

**Comment by pschisa** [comment]
The intention was to provide an example in golang utilizing the API to perform a functional action like retrieve/reference credentials, ssh in to a node, and execute a command.

**Comment by ptgott** [comment]
@pschisa When would users want to build a custom API client for retrieving credentials and SSHing into a host vs., say, managing host certificates via Machine ID (https://goteleport.com/docs/machine-id/guides/host-certificate/) and using a standard SSH client to access the host?
