### ISSUE TITLE
Enhanced Session Recording documentation incomplete install instructions

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#5512]
## Summary
When following Step 2: Install BCC Tools of the Enhanced Session Recording on a fresh Debian install, I followed the instructions and ran the single command:
`apt -y install bpfcc-tools`

However, after configuring and enabling Teleport service, I received the following error:

```
teleport[843]: DEBU [BPF]       Starting enhanced session recording. bpf/bpf.go:128
teleport[843]: chdir(/lib/modules/4.19.0-13-cloud-amd64/build): No such file or directory
teleport[843]: WARN [PROC:1]    Teleport process has exited with error: failed to load libbcc service:ssh.node
```

This was only resolved when I followed the step from the compile from source instructions for Debian to Install Linux Kernel Headers

`apt-get install linux-headers-$(uname -r)` 

I suggest we add this command as well to the Ubuntu/Debian section of the ESR documentationfor the download since the single command does not seem to cover all requirements for Debian.

### Audience
users installing enhanced session recording

### Location
https://goteleport.com/teleport/docs/features/enhanced-session-recording/

**Comment by ptgott** [comment]
Closing since, after this issue was opened, the "Linux distributions and supported kernels" table no longer includes Debian. E.g., see: https://github.com/gravitational/teleport/pull/7341
