### ISSUE TITLE
Provide a method to set a default user other then the local machine user id

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5549]
### What

Provide a method within `tsh` usage to specify a default user instead of the machine userid. 
`tsh` uses the current userid if none is specified for `tsh ssh myserver`.  Often a user has a specific user they use different then the login id in their local machine for ssh server.   

### How
A user could specify a default login in a file within `~/.tsh` or via  a `tsh` executable setting (Ex: `tsh setdefaultuser -l steven`). 

### Why
having to specify the username for each `ssh` has been reported as annoying.  You can also specify this in `ssh` so this mimics a `ssh` feature.

```
Host *
    User steven
```

### Workaround

Place this function in `~/.bashrc` to use a specific user instead of the default with `tshssh`
```bash
tshssh() { tsh ssh -A --login=steven "$@"; }
```

Then a user can call `tshssh myserver` to open a session with `steven` as the login.

### Which platform(s)
- [X] Teleport Open Source
- [X] Teleport Cloud
- [x] Teleport Enterprise
- [ ] Other

### Which component(s)
- [x] Server Access
- [ ] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [X] CLI Clients
- [ ] Web Clients
- [ ] Other

**Comment by webvictim** [comment]
You can set the `TELEPORT_LOGIN` environment variable to specify which Unix user to log in as by default.
