### ISSUE TITLE
Bot that publishes vercel branches on Teleport docs PRs

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5557]
### What

We are using vercel in a creative way. Our repo `next` has multiple submodules to our docs. Once we merge the PR, the vercel build publishes the documents and updates the submodules. This works well, and allows us to have docs in sync with our branches (finally).

However, Vercel has a very cool feature, that is not available to us because of the way we use it. When creating a PR to repo, vercel triggers the build and posts a comment with preview. It makes it trivial to review the changes.

See for example here:

https://github.com/gravitational/next/pull/94#issuecomment-776874565

This is impossible to do with deploy hooks.

I wonder if we can:

* When someone submits a PR to one of our docs branches, create a PR to `next` repo that updates the submodule
* Use API to wait until vercel builds the branch and post the result to the original PR

Vercel has API and CLI:

https://vercel.com/download

https://github.com/vercel/vercel/blob/master/packages/now-client/src/deploy.ts

That would be fun project that will also help to improve UX

**Comment by webvictim** [comment]
@russjones is working on a bot to automatically process and comment on Github PRs. Once he's done that, I'll pick up the base logic and build on it to work with Vercel.

**Comment by klizhentas** [comment]
@webvictim @russjones I feel like most of the bot PR logic is here:

https://github.com/gravitational/force/tree/master/pkg/github

Let me know what kind of help you need

**Comment by benarent** [comment]
Just some extra notes for this issue.

We can create previews without PRs using `vercel` CLI tooling, so no extra PR is required https://vercel.com/docs/concepts/deployments/preview-deployments 

We should scope to https://github.com/gravitational/docs,  Then the last item, is to return the preview link back once complete.

**Comment by ptgott** [comment]
Looks like there's an API endpoint that lets you create a new Vercel deployment (https://vercel.com/docs/rest-api/endpoints#create-a-new-deployment). If you omit the `target` parameter, the target will be `preview`.

So would this be the flow? (i.e., in a GHA workflow)
- Check out a branch of `gravitational/docs`
- Update `.gitmodules` in the `gravitational/docs` branch to point the submodule for the default version in the `content` directory to the current feature branch (e.g., `GITHUB_REF_NAME` in GHA)
- Push the new `gravitational/docs` branch to GitHub
- Send a deployment request to the Vercel API with the `gravitational/docs` branch, indicating that this is a preview
- Post a comment including the deployment URL and name of the `gravitational/docs` branch (so we can delete it later) to the `gravitational/teleport` PR
