### ISSUE TITLE
Improve teleport configure subcommand

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5559]
### What

It should ask you a couple of questions and generate a valid teleport.yaml and write it to the disk.

* What is your cluster name? (For example example.com). Cluster name can not be changed, so pick a unique name. If you choose a name that matches your domain name, configuration will be easier.

* Backend? Dir by default.

* Acme. Should offer acme for auto cert generation

* Should print the survey at the end.

## Test

`teleport configure --test /path` should test config for errors.

**Comment by webvictim** [comment]
Related to https://github.com/gravitational/teleport/issues/3248

**Comment by webvictim** [comment]
```
gus@artemis:~$ sudo teleport configure --test /etc/teleport.yaml
ERROR:
unknown long flag '--test'
