### ISSUE TITLE
tls: handshake message of length 188425 bytes exceeds maximum of 65536 bytes. service/service.go:1329

### ISSUE THREAD

**Issue by wangzw** [gravitational/teleport#5572]
### Description

**What happened**:

I have a four nodes teleport cluster (2 auth nodes and 2 proxy nodes) and many others clusters trust on it. 
It works well for a long time. Recently the four nodes teleport cluster has been reboot and proxy nodes cannot connect to auth node again.

I found following error message in proxy node's log. 

```
INFO [PROC:1]    Proxy failed attempt connecting to auth server: Post https://teleport.cluster.local/v2/tokens/register: tls: handshake message of length 188425 bytes exceeds maximum of 65536 bytes. service/service.go:1329
INFO [PROC:1]    Node failed attempt connecting to auth server: Post https://teleport.cluster.local/v2/tokens/register: tls: handshake message of length 188425 bytes exceeds maximum of 65536 bytes. service/service.go:1329
```

And following error message from error message from auth node's log.

```
2021/02/15 15:56:33 http: TLS handshake error from 10.0.0.7:44016: remote error: tls: internal error
```

From the proxy node's log. Golang has a 65536 bytes size limit of tls handshake message but teleport is transferring a larger package.

I tried with curl and something seems wrong with teleport auth node self-signed certificate, usually it is too large.

```
curl -k -v https://teleport.cluster.local:3025/v2/tokens/register
* About to connect() to teleport.cluster.local port 3025 (#0)
*   Trying 127.0.0.1...
* Connected to teleport.cluster.local (127.0.0.1) port 3025 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS error -12249 (SSL_ERROR_RX_MALFORMED_HANDSHAKE)
* SSL received a malformed Handshake record.
* Closing connection 0
curl: (35) SSL received a malformed Handshake record.
```

I tried dump the packages using tcpdump, and I found many trusted clusters' name in the certificate.
[tcpdump.txt](https://github.com/gravitational/teleport/files/5983155/tcpdump.txt)

And there are truly many trusted clusters in the system.

```
# tctl get rc | grep name
  name: fd9ff722-008c-4eae-86bc-5d702305b441
  name: fde3e8c6-313b-4421-8c07-8518b5ddcc58
  name: fe12d499-abfd-4dd5-8a44-50da9399b65d
  name: fe6a4dca-6563-4bc8-a6fe-3274d9c3fc2f
  name: fe76e998-e0bd-4bbd-87e7-19788739ff54
  name: fe7d0118-6d09-42e7-b3ca-a09d83feaa79
  name: fe9d972a-ab94-4b00-a095-6061117902df
  name: fec1b05b-577d-4891-86d8-fc2559b5fa51
  name: fee87d11-8cfa-4e49-8b04-5b88171c48ce
  name: fee8cca5-c34d-40d4-b80d-578e2800e296
  name: ff054c28-2c62-44f7-9599-2e74b3f13471
  name: ff4a086f-cb7e-4733-a4af-00253705f21b
  name: ff5bb147-3b51-41cf-8880-fb73e203de85
  name: ff6fb15b-05d1-426f-a802-0e04cb9ff8b3
  name: ffbbf51b-ba74-48c5-a4c6-d5edc6bb5bf2
  ......
# tctl get rc | grep name -c
1265
``` 

**So, the problem is that the auth's self-signed certificate is too large and proxy node failed to setup a TLS connection with auth node.**

After removing all trusted clusters, proxy node successfully connected to auth node and the system is back to normal.

### Server Details
- Teleport version (run `teleport version`): `Teleport v3.1.8 git:v3.1.8-0-g4cceea49 go1.11.5`
- Server OS (e.g. from `/etc/os-release`): `CentOS 7.5`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Cloud Environment
- Additional details:

teleport server is started with following command line, and there is a load balance server in front of the proxy node. 

```
/usr/local/bin/teleport start --pid-file=/tmp/teleport-auth.pid --config=/etc/teleport.yaml --insecure-no-tls
```

### Which platform(s)
- [ x ] Teleport Open Source
- [ ] Teleport Cloud
- [ ] Teleport Enterprise
- [ ] Other

### Which component(s)
- [x] Server Access
- [ ] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [ ] CLI Clients
- [ ] Web Clients
- [ ] Other

**Comment by webvictim** [comment]
I think that this bug may have been fixed in Teleport v4.3.0 - see https://github.com/gravitational/teleport/issues/3870

If you're running Teleport v3.1.8 you should look to upgrade. There have been many improvements to Teleport since that version was released.

**Comment by wangzw** [comment]
Thanks for your rapid response. 

I was trying to upgrade teleport from v3.1.8 to the latest version but got no luck to make it work. It has a long upgrade path 
 and complicated upgrade process for a multiply auth node cluster from the description of the document. 

I'm seeking another way of upgrading to the latest version, that is dump all objects out and

**Comment by webvictim** [comment]
@wangzw What type of storage are you using for Teleport's backend currently?

**Comment by wangzw** [comment]
> @wangzw What type of storage are you using for Teleport's backend currently?

using ETCD

**Comment by webvictim** [comment]
You could potentially use `tctl get all --with-secrets > backup.yaml` to dump everything out of your cluster backend to a YAML file, then spin up a new Teleport cluster on 5.x and use `teleport start --bootstrap backup.yaml` to import all that data. 

One issue is that due to https://github.com/gravitational/teleport/issues/3642, the bootstrap flag does not currently support adding trusted clusters - so you would need to re-add all the trusted cluster relationships to get them to reconnect. This may be prohibitive in your situation as you have so many trusted clusters, but hopefully you have some kind of configuration management/infrastructure as code which might make this easier.

**Comment by wangzw** [comment]
@webvictim Thanks for you answer. Re-adding trusted cluster is not an issue to me, we can do that batch and automatically. 

But for teleport v3.1.8 , `tctl get all` does not work, `--with-secrets` neither.

**Comment by wangzw** [comment]
I guess that I can rebuild the teleport cluster logically. Dump objects without `--with-secrets` flags and import into the latest version cluster. Maybe users have to re-register but we do not have many users. I do not know if it works but it is worth a try.

**Comment by webvictim** [comment]
Yes, that would work. If you dump users with `tctl get users --with-secrets` then the passwords should be kept too.

You can concatenate all the exported YAML files together into one with `---` as a separator and then `teleport start --bootstrap concat.yaml` to import everything at once.

`tctl get cas --with-secrets` will also be useful if you want to keep your user/host CAs.
