### ISSUE TITLE
my user login is an email address, which is contains an @ character. how to login using `tsh ssh`

### ISSUE THREAD

**Issue by adzimzf** [gravitational/teleport#5578]
### What
How to `tsh ssh` with user name contains @ character

I've checked the code, it will split the user & host using @ character

`tool/tsh/tsh.go:555`

## Why
I can't `tsh ssh` using user host like this `myemail@gmail.com@beta127.0.0.1`

### Which platform(s)
- [ ] Teleport Open Source
- [ ] Teleport Cloud
- [x] Teleport Enterprise

### Which component(s)
- [ ] Server Access
- [ ] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [x] CLI Clients
- [ ] Web Clients
- [ ] Other

**Comment by russjones** [comment]
@adzimzf What OS are you using? Typically Linux does not allow `@` symbol in the username.

**Comment by webvictim** [comment]
Does `tsh ssh -l myemail@gmail.com <host>` work?

**Comment by adzimzf** [comment]
> @adzimzf What OS are you using? Typically Linux does not allow `@` symbol in the username.

both my local and remote are Ubuntu.
but it works when accessing from teleport webui.

**Comment by adzimzf** [comment]
> Does `tsh ssh -l myemail@gmail.com <host>` work?

I'll try it first

**Comment by adzimzf** [comment]
> Does `tsh ssh -l myemail@gmail.com <host>` work?

Hi, it works, thanks anyway
