### ISSUE TITLE
Copy and paste

### ISSUE THREAD

**Issue by guanana** [gravitational/teleport#558]
Hi,

I don't know if is something you can change on the behavior but for some day-a-day operations is a real nightmare not having the copy and paste as you normal do on terminal. Can you make something to change that?

**Comment by kontsevoy** [comment]
@guanana You mean in the web UI?

It's documented here:
http://gravitational.com/teleport/docs/user-manual/#web-ui

**Comment by yyevgenii** [comment]
I followed instructions from article
http://gravitational.com/teleport/docs/user-manual/#web-ui

and I can get into copy mode with Ctrl+A (like in GNU Screen terminal multiplexer), I can navigate with hjkl and select some text with space button, but I don't know how to paste it. Ctrl+V doesn't work, as Ctrl+A ] (like in GNU Screen). I use Chrome browser on windows.

**Comment by alex-kovoy** [comment]
What teleport version are you using? In the latest releases, past works as in regular terminals i.e. ctrl+shift+v.

**Comment by yyevgenii** [comment]
@alex-kovoy I use 1.3 branch, seems it doesn't have updated xterm.js. I'll try to upgrade. Thank you.
