### ISSUE TITLE
Helm charts improvements

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5582]
### What

* [x] Add tests of helm charts to our CI/CD pipeline to avoid regressions
* [x] Release `teleport-kube-agent` and `teleport-cluster` to be our official charts
* [x] Extend `teleport-cluster` to support custom configuration, GKE and EKS scenarios
* [x] Provide migration guide from `teleport` to `teleport-cluster` and update the docs
* [x] Helm chart version should match Teleport version

## Strategy of Teleport Cluster

Keep amount of configuration parameters to a recommended minimum subset. Promote 3 major use cases:

* Standalone chart with ACME and PVC for getting started
* HA AWS chart with DynamoDB and S3
* HA GCP chart with Firebase and GCS

For every other scenario, provide escape hatch - ability for folks to mount their config files and give a couple of examples

## Strategy for Teleport Kube Agent

Teleport Kube Agent should support multiple roles and apps, provide ways to add apps to existing Database agent for example.

Add respective guides to documentation sections

**Comment by aelkugia** [comment]
From customer (`c-fg`) they would like to see the functionality from #5680 in the upcoming Helm chart improvements. Summarized here:

- allow the spec of both initContainer and sidecar containers in the chart values.yaml when deployed
- allow sidecar containers to be provisioned alongside the auth container, watching a configMap for new/updated yaml configs and triggering `tctl create -f <filename>` to process any updates

**Comment by webvictim** [comment]
It's unlikely that I'll be adding native support for initContainers or sidecars to our supported Teleport Helm chart as we're trying to keep everything as simple as possible. 

The likelihood is that Teleport itself will be improved in upcoming releases to better support reading roles/connectors from ConfigMaps/Secrets. We may provide an example of how to configure a sidecar container.

**Comment by robcoward** [comment]
@webvictim we're not asking you to support sidecars, just to add 9 lines to the helm chart templates (and 2 variables in the values.yml) - as already proposed in #5680 - to allow users the option to specifying their own customised deployment via their helm value.yml overides, while still benefitting from the main opinionated supported helm chart for Teleport. This is not an uncommon pattern, used in many other helm chart deployments, giving users the option to customise how they deploy their software.

**Comment by webvictim** [comment]
I understand, however acquiescing to every request is what allowed the current Helm chart to get into its rather convoluted state. We will rightly be expected to support any options that we add to the Helm chart, so the idea going forward is that we're going to keep the chart as simple as possible to provide an easier experience for everyone. People are very welcome to fork it and add their own custom modifications (as you have done) but we won't be accepting those modifications upstream to avoid the existing situatioin.

**Comment by klizhentas** [comment]
https://github.com/gravitational/teleport/issues/5354

**Comment by webvictim** [comment]
Final thing to do to close this issue after merging the PRs and backports: update the `teleport-helm-cron` job in `.drone.yml` to no longer package and publish the `teleport` Helm chart - only `teleport` and `teleport-cluster`.
