### ISSUE TITLE
Document cluster labels in the admin guide

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#5583]
## Details

https://goteleport.com/teleport/docs/admin-guide/ has no mention on cluster labels added in 5.0
The only "public docs" are https://github.com/gravitational/teleport/blob/master/CHANGELOG.md#cluster-labels

### Category
- [x] New Feature
- [ ] Improve Existing
- [ ] Remove Outdated

### Which platform(s)
- [ ] Teleport Open Source
- [ ] Teleport Cloud
- [x] Teleport Enterprise
- [ ] Other

### Which component(s)
- [ ] Server Access
- [ ] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [ ] CLI Clients
- [ ] Web Clients
- [x] Other

**Comment by ptgott** [comment]
Now that we have [this page](https://goteleport.com/docs/setup/admin/trustedclusters/), is there more work to be one on this issue?

**Comment by ptgott** [comment]
The section related to creating a join token for a Trusted Cluster doesn't mention labels (https://goteleport.com/docs/management/admin/trustedclusters/#create-a-join-token). We could add these instructions in a `Details` box.
