### ISSUE TITLE
Allow teleport-kube-agent Helm Chart to use dynamic token

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#5585]
### What
Currently the teleport-kube-agent Helm Chart must use a static token. We would like to use dynamic tokens with this Chart. https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-kube-agent

### Which platform(s)

- [x] Teleport Enterprise

### Which component(s)
- [x] Kubernetes Access

**Comment by klizhentas** [comment]
To solve this problem we need to keep x509 in Kubernetes. @klizhentas - ping me to elaborate.

**Comment by webvictim** [comment]
You can also just use a PersistentVolumeClaim for /var/lib/teleport as a workaround.

**Comment by awly** [comment]
PVCs seem to be non-portable currently (you need to know exactly what kind of PV to create).
It would be great to use something portable that works out-of-the-box, like storing host identity in a Secret.

**Comment by stefansedich** [comment]
Adding a +1 here, we are looking at setting up Teleport and having to manage static tokens really doesn't play well with our GitOps way of doing things.

**Comment by gclawes** [comment]
Wondering if the idea discussed here is on the table: https://github.com/gravitational/teleport/issues/5031#issuecomment-738235287

Using kubernetes `Secret` objects for credential persistence.

**Comment by webvictim** [comment]
https://github.com/gravitational/teleport/pull/7123 adds support for running the `teleport-kube-agent` as a `StatefulSet` with persistent storage for exactly this purpose.

**Comment by gclawes** [comment]
@webvictim Is `StatefulSet` with persistent storage the long-term solution to this?  It seems like using a kubernetes `Secret` is going to be more k8s-native (and I'd guess better for HA `kube-teleport-agent`).

**Comment by russjones** [comment]
@r0mant I'm wondering if this is something we can use certbot to solve instead? Let's chat about this.

**Comment by r0mant** [comment]
> I'm wondering if this is something we can use Machine ID to solve instead?

Maybe. But I think that we'll just be moving the same problem to Machine ID instead - bots still have to join the cluster somehow. I think an easier solution is to teach Teleport agents to keep their identity credentials in Kubernetes secrets like suggested in https://github.com/gravitational/teleport/issues/4832 so they don't have to rejoin the cluster every time the pod restarts. If we do that, any agent (kube, bot, app/db, etc.) will be able to take advantage of it. And then if we wanted to we could teach Machine ID to refresh these credentials in secrets but that's a bit different from this particular issue I think.

**Comment by russjones** [comment]
@benarent @jon-can This has been fixed, but due change in behavior, we're not going to release this until Teleport 11.
