### ISSUE TITLE
Log spam in kube/proxy/portforward.go

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#5594]
### Description

**What happened**:

Function `monitorStreamPair` is spamming logs. See [/lib/kube/proxy/portforward.go:263-272](https://github.com/gravitational/teleport/blob/master/lib/kube/proxy/portforward.go#L263-L272). 

See [gist](https://gist.githubusercontent.com/travelton/7aa5c148f9f25c5b9ae12638ca74146c/raw/ca1def8e8a019e3e7d5a9259467dddb12851d273/gistfile1.txt) for example of log spam.

**What you expected to happen**:

This method should print the pointer using `%p` instead of `%v`. 

### Reproduction Steps
1. Configure a Teleport cluster w/ Kubernetes node. 
2. `kubectl port-forward <pod> <port>:<port>`
3. Pull data over the forwarded port and watch Teleport Proxy logs. 

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
```
Feb 17 00:20:53 server-1 teleport[29552]: INFO             (conn=&{0xc000eccc60 [0xc001ac3360 0xc001ac3400 0xc0006ff5e0 0xc0006ff680 0xc001a0ec80 0xc001a0ed20 0xc001a0f4a0 0xc001a0f540 0xc00203e140 0xc00203e1e0 0xc00203e8c0 0xc00203eb40 0xc00203f9a0 0xc00203fc20 0xc00203e640 0xc00203e6e0 0xc00203edc0 0xc00203ee60 0xc00203f720 0xc00203f7c0 0xc000fd4460 0xc000fd4500 0xc000fd4a00 0xc000fd4b40 0xc000fd4f00 0xc000fd4fa0 0xc000eec000 0xc000eec0a0] {0 0} 0x1e507a0 0x1e2e420}, request=13) successfully received error and data streams proxy/portforward.go:269
```

### Which platform(s)
- [ ] Teleport Open Source
- [ ] Teleport Cloud
- [x] Teleport Enterprise
- [ ] Other

### Which component(s)
- [ ] Server Access
- [x] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [ ] CLI Clients
- [ ] Web Clients
- [ ] Other

**Comment by awly** [comment]
@travelton since you know exactly how to fix this, mind submitting a PR?
