### ISSUE TITLE
Allow differentiated labels for a single kubernetes_service configuration

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#5604]
### What

Currently in 5.1.2, a `kubernetes_service` config block can take a single `kubernetes_config` file, and a single label configuration. These labels will apply uniformly to all clusters defined in that one `kubernetes_config` file.

It should be possible to specify different labels for different clusters. 

### How

A few possibilities come to mind. Based on https://github.com/gravitational/teleport/blob/v5.1.2/lib/config/configuration.go#L719-L734 it appears that the limitation is mostly in the config file implementation, so a more robust config approach should do the trick.

* A list-based configuration file format could allow multiple sets of kubernetes_config+labels
* A more robust labeling syntax could facilitate regex matching against cluster names to define labels.

### Why

It should be possible to grant different access to different clusters by label when using the new one-to-many `kubernetes_service` approach.

### Workaround

Run one kubernetes_service per cluster, which increases the workload for the teleport administrator.

### Which platform(s)
- [ ] Teleport Open Source
- [ ] Teleport Cloud
- [x] Teleport Enterprise
- [ ] Other

### Which component(s)
- [ ] Server Access
- [X] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [ ] CLI Clients
- [ ] Web Clients
- [ ] Other

**Comment by tigrato** [comment]
@programmerq this is already possible in Teleport 11 if you use dynamic kube clusters
