### ISSUE TITLE
Update Teleport to use Go 1.16

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#5606]
Go 1.16 was [released yesterday](https://blog.golang.org/go1.16), we should update Teleport to use it.

Issues/PRs which are waiting on this:
- #3437
- #3158 
- #5496 
- #5595

@russjones and I agreed that because the Go 1.16 release is so close to our 6.0 cut-off, we should hold off and do this as part of Teleport 6.1.

**Comment by klizhentas** [comment]
@webvictim @russjones is this one good to close?

**Comment by webvictim** [comment]
Yes, we’re on Go 1.16 in master now.
