### ISSUE TITLE
Server labeling

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5612]
### What

If we allow users to create `Server` entries with unique host UUIDs, whenever the server heartbeats, if the entry is persistent and has a label managed by API, the server heartbeat should not overwrite it.

So users can create `tctl create -f server.yaml`. Then users when joining nodes make sure that identity of the host matches with the server. If that happens, the server will not overwrite the entry. This will allow users to switch their resource catalogs to Teleport.

**Comment by russjones** [comment]
@klizhentas Might get cumbersome for large deployments. For example, a 5,000 server inventory would mean you have to maintain those 5,000 resources in source control and and update the labels inside 5,000 of them to make changes and then also re-upsert them when you make changes.

What do you think about a mapping scheme that allows you to append additional labels? Something roughly like "If the servers UUID (or nodname) matches some expression, then append this list of labels."

You would be able to do it with a single resource and should be straightforward to add support for this to Teleport. We could just apply the mapping during the heartbeat.

**Comment by webvictim** [comment]
Similar to https://github.com/gravitational/teleport/issues/5499

**Comment by klizhentas** [comment]
Extend join tokens to encode labels in the node certs instead.

**Comment by zmb3** [comment]
@capnspacehook @r0mant `tctl create -f server.yaml` is now supported with agentless mode, right? Can we close this issue?

**Comment by capnspacehook** [comment]
Yes, this can be closed.
