### ISSUE TITLE
Support etcd for audit event storage

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#5626]
### What

etcd should be able to store audit events.

### Why

DynamoDB and Firestore can store both cluster state and audit events.
etcd is only implemented as cluster state storage today, but there's no reason it can't store audit events.
It should be consistent with other HA backends.

### Workaround

n/a

### Which platform(s)
- [x] Teleport Open Source
- [ ] Teleport Cloud
- [ ] Teleport Enterprise
- [ ] Other

### Which component(s)
- [ ] Server Access
- [ ] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [ ] CLI Clients
- [ ] Web Clients
- [x] Other

**Comment by klizhentas** [comment]
@awly I don't think it's a great medium for events tbh, on a large scale system, etcd will be overwhelmed. I think systems like ElasticSearch and Splunk are better designed to store structured events.

**Comment by awly** [comment]
@klizhentas what are our QPS targets for events, considering the largest supported clusters?
Per https://etcd.io/docs/v3.4.0/op-guide/performance/ a 3-node etcd can take ~500 QPS from 1 client and this can be scaled by adding more clients (more auth servers).

I agree that specialized log aggregation products would work better, and etcd data model doesn't fit well for append-only logs. But maybe for small-scale setups it's sufficient?

**Comment by klizhentas** [comment]
The problem is not QPS, but with large amounts of time-series data stored in etcd. It is not designed to handle time series data and it's performance will degrade over time, as the data set grows.

**Comment by stevenGravy** [comment]
MongoDB, Couchbase seem like good options for the config and events

**Comment by awly** [comment]
@klizhentas makes sense.
https://github.com/gravitational/teleport/pull/5634 to explain this out in the docs.

@stevenGravy mongodb is notoriously lossy, I would be very hesitant to entrust cluster data to it.
