### ISSUE TITLE
apiserver_test fails with "Proxy didn't register within 5s after startup"

### ISSUE THREAD

**Issue by gururajrkatti** [gravitational/teleport#5648]
### Description

I was trying to run the unit tests on ppc64le. I found one of the tests failing. Then I tried it on intel(amd64), there also it fails with same error.
apiserver_test fails as 

"--- FAIL: TestU2FLogin/second_factor_u2f (7.54s)
        apiserver_test.go:2321: Proxy didn't register within 5s after startup."

**What you expected to happen**:
Test should pass as "ok"

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.make full
2. make test

### Server Details
- Teleport version (run `teleport version`): v6.0.0-alpha.2
- Server OS (e.g. from `/etc/os-release`):  Ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicated H/W as well as Travis server also
- Additional details: 

### Client Details
- Tsh version (`tsh version`):v6.0.0-alpha.2
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Browser version (for UI-related issues): NA
- Installed via (e.g. apt, yum, brew, website download): git source
- Additional details:  Downloaded from git source and built.

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

### Which platform(s)
- [ ] Teleport Open Source
- [ ] Teleport Cloud
- [x] Teleport Enterprise
- [ ] Other

### Which component(s)
- [x] Server Access
- [ ] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [ ] CLI Clients
- [ ] Web Clients
- [ ] Other

**Comment by awly** [comment]
@gururajrkatti what do you get with:
```
go test -run U2FLogin -count=10 ./lib/web/
```
The test passes consistently for me on amd64, I don't have a ppc64le box to try.
It's likely that your system is resource constrained and the test just hits an internal timeout.

If we confirm the above, I can bump the timeout to be more generous.

**Comment by awly** [comment]
NVM, there was a big in proxy startup check: https://github.com/gravitational/teleport/pull/5703

**Comment by gururajrkatti** [comment]
@awly thanks for the response. This test also fails for me .. below is tail of output

```
time="2021-02-25T06:05:23Z" level=warning msg="Failed to find roles or traits in                                x509 identity for bob. Fetching\tfrom backend. If the identity provider allows                                username changes, this can potentially allow an attacker to change the role of t                               he existing user."
time="2021-02-25T06:05:23Z" level=warning msg="Failed to find roles or traits in                                x509 identity for bob. Fetching\tfrom backend. If the identity provider allows                                username changes, this can potentially allow an attacker to change the role of t                               he existing user."
--- FAIL: TestU2FLogin (0.00s)
    --- FAIL: TestU2FLogin/second_factor_on (5.72s)
        apiserver_test.go:2321: Proxy didn't register within 5s after startup.
    --- FAIL: TestU2FLogin/second_factor_u2f (5.92s)
        apiserver_test.go:2321: Proxy didn't register within 5s after startup.
    --- FAIL: TestU2FLogin/second_factor_off (5.53s)
        apiserver_test.go:2321: Proxy didn't register within 5s after startup.
FAIL
FAIL    github.com/gravitational/teleport/lib/web       105.121s
FAIL
```
