### ISSUE TITLE
Add GRPC method to client that returns version and modules.Features

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5652]
### What

Add GRPC /discovery method that returns:

* Teleport version
* Teleport lib.modules.Features to clients to review
* Public address of web proxy

Port Features struct to protobuf

**Comment by marshall-lee** [comment]
There's also `Ping` method that returns server version, I just expect to get `features` from the response as well.

**Comment by Joerger** [comment]
> * Public address of web proxy

@klizhentas IIUC this request will be made to the web proxy,  so should this be "Public address of the proxy tunnel"?
