### ISSUE TITLE
Add "kubernetes_users" example to RBAC documentation

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#5655]
## Details
In the RBAC documentation section there is no mention of "kubernetes_users". We should add this field to the example admin role included on the page. https://goteleport.com/teleport/docs/enterprise/ssh-rbac/
### Category
- [ ] New Feature
- [x] Improve Existing
- [ ] Remove Outdated

### Which platform(s)
- [ ] Teleport Open Source
- [x] Teleport Cloud
- [x] Teleport Enterprise
- [ ] Other

### Which component(s)
- [ ] Server Access
- [X] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [ ] CLI Clients
- [ ] Web Clients
- [ ] Other

**Comment by ptgott** [comment]
@jon-can I see this mentioned a few places in the docs now, e.g., [here](https://goteleport.com/docs/kubernetes-access/controls/) and [here](https://goteleport.com/docs/access-controls/guides/role-templates/#interpolation-rules). Anything left to address in this issue?
