### ISSUE TITLE
Streamline adding nodes

### ISSUE THREAD

**Issue by wjdavis5** [gravitational/teleport#567]
Currently adding nodes requires a bit of manual intervention. Given that we use AWS where machines are very transient it would be exceptional if we could automate this process. It would be possible via some shell scripting, but it would be nice if these were a part of the app. I'm thinking a couple of scenarios

1. When I'm at the console for one of our main teleport servers and want to add a new node, I should be able to provide ssh credentials to that node and teleport would install and configure itself on the target node.

2. When I have a machine using chef I could call an endpoint on one of my teleport servers that would automate the process of adding that node to the cluster. Endpoint is rather ambiguous here, it could be any number of things from an http endpoint or perhaps a socket etc. If we get 1. working then it would even be doable to ssh that add command from the joining node to the server that would then initiate the installation of teleport and adding in one fell swoop.

Thoughts? I'd be happy to help out, but I've admittedly never used GO before I found this project :)

**Comment by kontsevoy** [comment]
@wjdavis5 you should be using "static tokens". They do not require `tctl` at all. Maybe we need to make them more visible in a documentation?

http://gravitational.com/teleport/docs/admin-guide/#adding-nodes-to-the-cluster -> scroll to "static tokens".

Also the master branch has [examples](https://github.com/gravitational/teleport/tree/master/examples/local-cluster) directory where you can see a 3-node cluster (where auth, proxy and node are separated for cleanliness) and that example uses static tokens too.

Do you have suggestions on how we should re-package documentation? This is by far number one question we get ;)

**Comment by kontsevoy** [comment]
we should rename the label from "user-error" to "documentation-needs-improvement" :)

**Comment by wjdavis5** [comment]
Ok so I'll walk through that bit of documentation:

> You can pre-generate your own tokens and add them to certificate authority (CA) config file:

 I read this and dont understand how it fits my use case. We dont have a CA at all, so that is confusing. We are using AWS Opsworks and some aws-cli scripting to create / destroy machines as needed. I want a new machine to come online, have teleport auto-magically installed, and join my cluster.

Now that I've re-read it a few times I think maybe the mix up is simply b/c the terminology 'CA' is being used. In this case you dont mean "_my existing enterprise cert authority_" but you instead mean "_the teleport CA node_"

So my process end-to-end would be

1. Add the teleport configuration with my static token to my primary teleport server (we only have one today)
2. Write a chef recipe that downloads / installs teleport
3. From chef call the following command 'teleport start --roles=node--token=%MY_PREGENERATED_TOKEN_VALUE% --auth-server=%PRIMARY_TELEPORT_DNS'

The only thing that would make this easier is if there was an ubuntu/debian ppa I could use to keep things up to date.

**Comment by kontsevoy** [comment]
@wjdavis5 bingo, that's exactly the workflow we use internally. Debian/RHEL packages are in the works, BTW - they're in the source tree (from an OSS contributor) but we need to QA and incorporate them into the builds.

We'll update the docs, then I'll close this issue. Thanks!

**Comment by kontsevoy** [comment]
@wjdavis5 see the changes we've made to the documentation [here](https://github.com/gravitational/teleport/commit/13088c0fe8a275c5adaa293124bfbcca4acf186a)
