### ISSUE TITLE
Reverse tunnel using openssh 

### ISSUE THREAD

**Issue by sghenimi** [gravitational/teleport#5675]
### What
I need to have ssh access to devices that are behind firewall. The installation of teleport client ARMv7 version didn't succeed on the devices (due to the lib.so.6 librarie). I decided to use openssh to interact with my teleport server. My question is the following: is there any way to do reverse tunnel using openssh. 

The configuration will be the following:
- devices with openssh client behind firewall.
<----- Reverse tunnel -----
- My server holding teleport server.

## Why
For deployment.

### Which platform(s)
- [Teleport Open Source

### Which component(s)

- [x] Other

**Comment by stevenGravy** [comment]
@sghenimi please post these questions in our discussion section.  https://github.com/gravitational/teleport/discussions

**Comment by sghenimi** [comment]
questions posted in discussion section https://github.com/gravitational/teleport/discussions/5687#discussion-3237456
