### ISSUE TITLE
`tsh logout` leaves state behind which might break the next `tsh login`

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/teleport#5688]
### Description

**What happened**:
After logging out with `tsh logout`, a profile file is left behind with web/ssh addresses that can confuse the next attempt to `tsh login`.

Given a `~/.tsh/profile` with the following contents:
```
web_proxy_addr: teleport:5080
ssh_proxy_addr: teleport:5023
user: user
cluster: teleport
```

An attempt to `tsh login` via a proxy running on `3080` fails and the following warning is displayed:
```
tsh login --proxy=localhost:3080 --insecure --user=user
WARNING: You are using insecure connection to SSH proxy https://localhost:5080
```

**What you expected to happen**:
`tsh logout` clear all state so that the next `tsh login` succeeds.

Teleport version:
```
$ git describe --tags
v6.0.0-alpha.2-142-g485856fbb
```

**Comment by zmb3** [comment]
Can no longer reproduce this.
