### ISSUE TITLE
tsh join/play fails in proxy record mode on 6.0.0-rc.1

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#5702]
### Description
`tsh join` and `tsh play` fail both in terminal and on the web proxy while in proxy record mode. The only exception is `tsh play` on a local node. 

If this is intended behavior in proxy recording mode, we should fix the "Interact with a cluster using tsh" section in the [Testplan](https://github.com/gravitational/teleport/issues/5654). 

**What happened**:
- `tsh join` gives an error on local and remote nodes: `ERROR: session `[session_id]` not found or it has ended`
- `tsh play` gives an error on remote nodes: `ERROR: open bin/remote/data/log/records/[session_id].tar: no such file or directory
`

**What you expected to happen**:
No errors.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
```bash
 # local node
 > tsh ssh local-node
 # copy session_id from teleport logs or web proxy
 > tsh join [session_id]
 > tsh play [session_id]

 # remote node
 > tsh ssh remote-node
 # copy session_id from teleport logs or web proxy
 > tsh join [session_id]
 > tsh play [session_id]
```

**Comment by webvictim** [comment]
As per the previous issue (https://github.com/gravitational/teleport/issues/3913) I think this is by design. The docs have a warning in that the functionality is not supported.

Leaving this issue open to track updating the test plan.

**Comment by igtsekov** [comment]
I hit this bug. But I can add some additional information. When connecting via the CLI, `teleport status` outputs prints mistaken session ID. If I logged in to the web interface under the `Active session` I see the correct ID of the session. I still cannot join but I can play it later. I am using version 6.0.2
