### ISSUE TITLE
Invalid data directory: '/var/lib/teleport'

### ISSUE THREAD

**Issue by Malayke** [gravitational/teleport#572]
I add user got some error, and do not understand why show this error.

```shell
$ tar zxpf teleport-v1.2.0-linux-amd64-bin.tar.gz 
$ cd teleport/
/teleport$ sudo make install
mkdir -p /var/lib/teleport /usr/local/share/teleport /usr/local/bin
cp -f teleport tctl tsh /usr/local/bin/
cp -fr app index.html /usr/local/share/teleport/
$ sudo teleport start
[AUTH]  Auth service is starting on 0.0.0.0:3025
[Node] Successfully registered with the cluster
[Proxy] Successfully registered with the cluster
[SSH]   Service is starting on 0.0.0.0:3022
[PROXY] Reverse tunnel service is starting on 0.0.0.0:3024
[PROXY] Web proxy service is starting on 0.0.0.0:3080
[PROXY] SSH proxy service is starting on 0.0.0.0:3023
```
In another terminal:

```shell
$ tctl users add $USER
Invalid data directory: '/var/lib/teleport'
```

OS: Ubuntu 16.04.1 LTS
Kernel: Linux ubuntu 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Where am I wrong? Who knows how to solve this problem?

**Comment by kontsevoy** [comment]
@Malayke looks like you're trying to run `tctl` on a machine without teleport auth running. See what [the docs](http://gravitational.com/teleport/docs/admin-guide/#adding-and-deleting-users) say:

> you have to use tctl tool on the same node where the auth server is running, i.e. teleport was started with --roles=auth

**Comment by tylerdurden0306** [comment]
Im running into the same issue here and just like in the screenshot it says this when I start teleport: 

_[AUTH]  Auth service is starting on 0.0.0.0:3025_

When I run the command like you suggest it just hangs. Is there something else we are missing?
