### ISSUE TITLE
Update GPG key to use info@goteleport.com

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#5728]
### Description

**What happened**:
As we've moved from Gravitational -> GoTeleport. We should update other email addresses we show to customers.

![image](https://user-images.githubusercontent.com/559288/109201966-4cd7c000-7757-11eb-84f1-0a4cf41c3580.png)

**Comment by wadells** [comment]
We'll consider this when we next work on release signing keys.  In the interim we have a statement out about these:

https://goteleport.com/security/

> We use the following certificates and public keys to sign our software. Many of these keys and certificates use our legal business name “Gravitational Inc.” and our former domain “gravitational.com”. Don’t worry – [Gravitational is Teleport](https://goteleport.com/blog/gravitational-is-teleport/).

**Comment by zmb3** [comment]
@wadells I'm going to close this stale issue that's been sitting for years as the dev team is not planning to take any action here. We can open a new internal issue if this is still something we want to track.
