### ISSUE TITLE
Provide CLI parameter for data dir

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5752]
### What
Provide the ability to set data dir via one of the `teleport start` parameters.

### How
Add a parameter `datadir` so this can be set when `teleport` is started.

```bash
teleport start --datadir=/var/lib/myteleport
```

### Why
Allows specifying data directory without populating into a teleport config file. Many other parameters are available via CLI parameters (roles, labels, debug,...).  In the case of wanting to run a sep teleport agent then an existing teleport install on the same machine this requires the usage of the `teleport.yaml` file to set a diff data dir.

### Workaround
None exists.

### Which platform(s)
- [x] Teleport Open Source
- [ ] Teleport Cloud
- [x] Teleport Enterprise
- [ ] Other

### Which component(s)
- [] Server Access
- [ ] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [ ] CLI Clients
- [ ] Web Clients
- [X ] Other

**Comment by klizhentas** [comment]
@stevenGravy why not use config file for this? Would like to avoid having too many flags.

**Comment by stevenGravy** [comment]
@klizhentas if you wanted to quickly run a ssh service but already have a teleport dir in place you have to make a file just for that one setting.

**Comment by pschisa** [comment]
+1 for a similar use case of wanting to set up the Teleport SSH service with a single command but now the CI/CD pipeline needs to manage loading a config file just to set the data directory for Teleport service

**Comment by stevenGravy** [comment]
As you can now configure the data-dir to a config in a parameter, closing.
