### ISSUE TITLE
Teleport API client should rotate its CA

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5765]
### What

Implement Golang client credential updater that watches for CA updates and re-issues it's own certificates.

Otherwise most clients will be broken on `tctl rotate`

### When

This is not urgent, but important to have in 6.1 perhaps?

**Comment by zmb3** [comment]
I think this is solved by Machine ID. What to you think, @klizhentas - can we close this one?

**Comment by strideynet** [comment]
> I think this is solved by Machine ID. What to you think, @klizhentas - can we close this one?

I think Machine ID goes a good way in helping with this, but we still need to either provide a nice code example of how to connect the Teleport API client up to an identity file on disk that may change, or modify the API client to natively support this.
