### ISSUE TITLE
Error logging in and logging out

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#5774]
### Description

`tsh login` showed me an error I have never seen before. I tried to clean up my state by typing `tsh logout` but got the same error:

```
~: tsh login --auth=github asteroid-moon.teleport.sh
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:37035/a91c96a0-bbac-412b-b7fe-455b914cc274
ERROR:
	read /home/ekontsevoy/.tsh/keys/asteroid-sun.teleport.sh/kontsevoy-kube/asteroid-sun.teleport.sh: is a directory

~: tsh logout
ERROR:
	read /home/ekontsevoy/.tsh/keys/asteroid-sun.teleport.sh/kontsevoy-kube/asteroid-sun.teleport.sh: is a directory
```

**What you expected to happen**:

The first error is weird. I never touched `~/.tsh` manually, so if `tsh` doesn't like what's inside - its our fault. Also, `tsh logout` should have been able to recover just by nuking bad content.

Just in case, I have tarballed my `~/.tsh` directory and attaching to this ticket.

## Version

```
$ tsh version
Teleport v6.0.0-rc.1 git:v6.0.0-rc.1-0-g5470bb912 go1.15.5
```

## Attached `.tsh` directory

Putting it on GDrive in case there's fresh/valid cert inside:
https://drive.google.com/file/d/15BfEjVSE-1VGxI_03494gWWRFSkqa-oQ

**Comment by kontsevoy** [comment]
## Update

I deleted `~/.tsh`
Then I tried:

```
$ tsh login --auth=github asteroid-moon.teleport.sh
ERROR:
	No proxy address specified, missed --proxy flag?
```

When I give it the `proxy` flag, it works. So it definitely was confused by something in my old `.tsh`.

**Comment by klizhentas** [comment]
@kontsevoy the cloud is version 5.1.2 that does not yet supports database service.

**Comment by klizhentas** [comment]
@kontsevoy I tried to reproduce the first error, but could not. Can you reproduce? Did you have a leftover directories from other tsh versions by any chance?

**Comment by kontsevoy** [comment]
> Did you have a leftover directories from other tsh versions by any chance?

Yes. I attached the tarball to the original ticket above.

**Comment by klizhentas** [comment]
@russjones the error happens because there is an unexpected folder in the `keys` directory for `teleport-moon.asteroid.sh`. I suggest we ignore directories when load keys. However it's interesting how this folder showed up there in the first place. Ev says it may be generated by previous version of tsh. Either way, easy enough to improve the behavior and QOL for users.

**Comment by kontsevoy** [comment]
Also, why didn't `tsh logout` work? Would be nice if that command could just wipe out everything (when used without arguments) to be a safe fallback to "bad state" situations in the future.

**Comment by tcsc** [comment]
By "everything" do you mean the entire contents of the `.tsh/keys` directory? Or is there a subset that should be preserved?

**Comment by kontsevoy** [comment]
By "everything" I meant the data created by `tsh login`. The client config files in `~/.tsh` are harmless AFAIK.

**Comment by tcsc** [comment]
Interestingly, that is what the current code actually does. But it unfortunately attempts to initialize the local keystore  _before_ wiping the `keys` dir, and so never got far enough to actually do the wipe.
