### ISSUE TITLE
Improve error message when DB or app services are not implemented

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5776]
### Description

**What happened**:
Try tsh 6.0 with Teleport 5.1:

```
tsh db ls
ERROR:
        unknown method GetDatabaseServers for service proto.AuthService

```

**What you expected to happen**:

If the server returns `trace.NotImpelemented` or grpc method not found, improve the error message:

```
This server does not implement this feature yet. Likely the client version you are using is newer than the server. The server version: %v, the client version: %v. Please upgrade the server or downgrade the client. 
```

**Comment by martinscholz83** [comment]
I have an idea how to implement it but I need to know if all `unimplemented` errors coming back from server should have this detailed error message or just this particular call? Is it possible to make a contribution?

**Comment by klizhentas** [comment]
@martinscholz83 it's pretty safe to provide this error message for all methods returning `unimplemented`, yes, feel free to send a PR and tag me and @r0mant to review.
