### ISSUE TITLE
RFD and plan for switching to mTLS with SNI for all protocols

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5777]
### What

Create RFD, issues and migration plan for switching teleport to one port design with TLS and SNI as they key building blocks.

## Related

* #4843 Merge SSH tunnel ports
* #4447 Use GRPC for reverse tunnels
* #3211 Find a way to reduce number of ports
* [Multiplex k8s traffix over tls](https://community.gravitational.com/t/kubernetes-api-proxy-through-tunnel/415)
* [Kevins' design doc](https://docs.google.com/document/d/1Yi3xbTpCas-JwHnrr_sgpIvjXh1kTs6iWzGMOHyhm-Q/edit)
* [Low usage tier](https://github.com/gravitational/cloud/issues/323)

**Comment by knisbet** [comment]
Also want to add in that I'd like to scope creep this into also supporting resumption of a connection through an alternate proxy. That way cloud maintenance that reschedules pods just result in a hiccup as the connection is re-established through an alternative proxy (and would also make it possible to support IP roaming in theory as well).

**Comment by russjones** [comment]
@r0mant @smallinsky I am going to close this since I think this was delivered in 8.0. If you think it hasn't feel free to re-open.
