### ISSUE TITLE
RFD: Review and merge bot

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5779]
### What

It will be hard to scale the team with the current rebase and review merge strategy. We need a bot:

*  that assigns reviewers most efficiently
* auto cherry-picks (applies patch?) to branches
* backports?
* detects broken builds

**Comment by webvictim** [comment]
Drone already checks for broken builds when commits are pushed to `master` or `branch/v6` so hopefully this part is already covered.

@russjones is already working on a bot which assigns reviewers. I wrote a rough bash script that does backports:

```bash
#!/bin/bash
set -eo pipefail

if ! command -v jq 2>&1 >/dev/null; then
    echo "jq must be installed"
    exit 1
fi

# who do you want to assign the PR to?
ASSIGNEES="$(gh api /user | jq -r '.login')"

# don't change below here
ASSIGNEE_SPEC=""
if [[ "${ASSIGNEES}" != "" ]]; then
    ASSIGNEE_SPEC="--assignee ${ASSIGNEES}"
fi

LABEL_SPEC=""
if [[ "$1" != "" ]]; then
    LABELS="$1"
    LABEL_SPEC="--label ${LABELS}"
fi

PARENT_BRANCH=$(git log --pretty=format:'%D' HEAD^ | grep 'origin/' | head -n1 | sed 's@origin/@@' | sed 's@,.*@@')
BRANCH_SPEC=$(echo ${BRANCH} | cut -d'/' -f2-)
COMMIT_NAME="[${BRANCH_SPEC}] Backport '$(git --no-pager log -F --format=%B -n 1 HEAD | tr -d '\n')'"
ORIGINAL_PR_ID=$(echo ${COMMIT_NAME} | cut -d# -f2 | tr -d ')' | tr -d "'")
BODY_MESSAGE="Backports #${ORIGINAL_PR_ID} to \`${PARENT_BRANCH}\`"

gh pr create --web --base "${PARENT_BRANCH}" --title "${COMMIT_NAME}" --body "${BODY_MESSAGE}" ${ASSIGNEE_SPEC} ${LABEL_SPEC}
```

It'd be nice to build this sort of logic into the bot so you can comment on a PR when it's ready to be merged and it'll go into a queue to be automatically rebased and merged. Github's API may be able to do a lot of the heavy lifting for us.

**Comment by webvictim** [comment]
This is still a huge priority for the whole Teleport team. The workload of the review/update/update/update/merge/backport/update/merge cycle is huge and takes a lot of everyone's time to negotiate.

**Comment by zmb3** [comment]
We actually have all of these things now, so closing this out.
