### ISSUE TITLE
utmp/wtmp support breaks macOS ssh node's web terminal

### ISSUE THREAD

**Issue by wxiaoguang** [gravitational/teleport#5783]
### Description

**What happened**:

https://github.com/gravitational/teleport/commit/324ccda21f68c35eafc00d48551974cf81351995#diff-76045a1d6e2c8f7d42000a7065c3c58579e87c33c0efd6f813701a28d970fefdR161

`reexec.go:161`:  `ttyName, err = os.Readlink(tty.Name())`

It always fails in macOS. Web terminal reports: `Failed to launch: failed to resolve tty soft link: readlink /proc/self/fd/6: no such file or directory.` and exits.

**What you expected to happen**:

Debugging `teleport` used to work in macOS

**Workaround**:

```
		if runtime.GOOS == "linux" {
			ttyName, err = os.Readlink(tty.Name())
			if err != nil {
				return errorWriter, teleport.RemoteCommandFailure, trace.BadParameter("failed to resolve tty soft link: %v", err)
			}
			err = uacc.Open(c.UtmpPath, c.WtmpPath, c.Login, c.Hostname, c.RemoteAddr, ttyName)
			if err != nil && !trace.IsAccessDenied(err) {
				return errorWriter, teleport.RemoteCommandFailure, trace.Wrap(err)
			}
		}

...
...
	if runtime.GOOS == "linux" {
		uaccErr := uacc.Close(c.UtmpPath, c.WtmpPath, ttyName)
		if uaccErr != nil && !trace.IsAccessDenied(uaccErr) {
			return errorWriter, teleport.RemoteCommandFailure, trace.Wrap(uaccErr)
		}
	}
	return ioutil.Discard, exitCode(err), trace.Wrap(err)

```

**Comment by klizhentas** [comment]
@xacrimon @russjones could be a regression in 6.0-rc.1 on MacOS, can you folks take a look

**Comment by xacrimon** [comment]
Will submit a patch tomorrow. I know why this happens.

**Comment by xacrimon** [comment]
In light of this I think MacOS CI may be worth looking into so that we can automatically catch these annoying cross-platform differences in our pipelines. What do you think? @webvictim

**Comment by xacrimon** [comment]
Submitted a patch for this issue.

**Comment by webvictim** [comment]
@xacrimon Possibly; an issue with this is that some of our tests don't run natively on Mac, hence why we run them all in Docker. Some developers also don't have Macs and you can't run MacOS in Docker, so some people don't have an easy way to run anything locally. We also don't currently have enough spare Mac build infrastructure to run tests natively on every commit. We can put fixing all these things on the to-do list.

**Comment by webvictim** [comment]
Interestingly, `sudo make integration-root` also passes on Mac...

**Comment by xacrimon** [comment]
Huh, that's uhm, interesting. It executes the exact code described in this issue.

**Comment by webvictim** [comment]
```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.2.1
BuildVersion:	20D74
```
