### ISSUE TITLE
Investigate database access support with AWS RDS Proxy / Cloud SQL Proxy

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#5809]
### What

Some prospects mention that they use RDS proxy or Cloud SQL proxy to connect to their databases.

We need to figure out whether this setup works with Database Access and how to make it work if it doesn't and/or update documentation with some instructions.

https://aws.amazon.com/rds/proxy/
https://cloud.google.com/sql/docs/mysql/sql-proxy (same for Postgres)

**Comment by greedy52** [comment]
sub issue #9820 created for tracking RDS proxy progress

**Comment by ptgott** [comment]
Closing as completed
