### ISSUE TITLE
tsh status shows the wrong Kubernetes cluster

### ISSUE THREAD

**Issue by fraenkel** [gravitational/teleport#5815]
### Description

**What happened**:

`tsh status` shows a Kubernetes cluster that I did not login into.

**What you expected to happen**:

`tsh status` shows the correct Kubernetes cluster I am logged into.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. rm -rf ~/.tsh
2. tsh --proxy MY_PROXY kube ls
  - I login
  - I see the list of clusters and one is selected based on my kubeconfig
3. tsh status
  - the Kubernetes cluster is set to the first cluster in the list above, which is not the selected one
4. tsh kube login CLUSTER
5. tsh status
  - the Kubernetes cluster is still the first one in the list and not what I logged into.

### Server Details
- Teleport version (run `teleport version`): 5.1.2
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Client Details
- Tsh version (`tsh version`): 5.2.1
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Installed via (e.g. apt, yum, brew, website download): brew
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by awly** [comment]
@fraenkel can you try this again with 6.1.2?
This should work as expected now.

**Comment by fraenkel** [comment]
Sorry but its still not right.

1. tsh logout
2. tsh status
3. tsh clusters
4. tsh status

That last status shows I am logged into a kubernetes cluster, but a tsh kube ls does not have it selected or any k8s selected as expected.

**Comment by awly** [comment]
@fraenkel does this happen when you manually `tsh login` after `logout`?

**Comment by fraenkel** [comment]
If I login then it selects the first k8s cluster.

**Comment by fraenkel** [comment]
If I delete my .tsh directory and do a tsh clusters, the first k8s cluster is selected. My guess is that I had a previous cluster selected that is now gone but some sequence selects a new one.

**Comment by awly** [comment]
Thanks for the details @fraenkel 
We don't have anyone free to work on this right now, but will keep this bug in the backlog

**Comment by awly** [comment]
Actually, I believe https://github.com/gravitational/teleport/pull/6824 should fix this.
The issue was that we look at the teleport TLS certificate in `~/.tsh/keys/$proxy/$user-x509.pem` to report the k8s cluster name. That PR changes `tsh status` to actually parse `~/.kube/config` and report based on its `current-context`.

No promises, but I'll try to get this included in 6.2, which comes out in about 2 weeks.

**Comment by awly** [comment]
This should be fixed in 6.2.
@fraenkel you can try using `tsh` from v6.2.0-beta.1 (it should appear shortly on https://goteleport.com/teleport/download/
