### ISSUE TITLE
kube_service silently ignores clusters with invalid names

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5816]
### Description

**What happened**:
If a `kube_service` `kubeconfig_file` file has a invalid name the Teleport logs do not mention it on INFO level.  The cluster is just ignored. This can happen if the admin ran the tool to generate a kubeconfig file on AWS and the cluster name is written with invalid chars, ex:`arn:aws:eks:us-east-1:005223150550:cluster/mycluster`.

![image](https://user-images.githubusercontent.com/60704961/109682175-2ac1b180-7b4c-11eb-90bf-1795976174bb.png)

**What you expected to happen**:
A error entry in the startup to indicate that a cluster has an invalid name.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.Run the `get-kubeconfig.sh` against a AWS cluster
2. Configure a `kube_service` in the same instance as the teleport proxy with `kube_listen_addr`.
3.Make a `kube_service` entry using the `kubeconfig_file` option with the `kubeconfig` output
4. Start teleport. 

### Server Details
- Teleport version (run `teleport version`):5.1.2
- Server OS (e.g. from `/etc/os-release`): ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by awly** [comment]
Should be logged at warning level, but otherwise same as https://github.com/gravitational/teleport/issues/4995
