### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by jchauncey** [gravitational/teleport#582]
`Users of main user --cluster=cluster-b flag of tsh tool if they want to connect to any nodes of cluster-b.`
Should be `Users of main use --cluster` (Found in the trusted clusters section)

Here - http://gravitational.com/teleport/docs/admin-guide/#high-availability-and-clustering
`Install etcd and configure peer and client TLS authentication using etcd security guide.` 
The link to the etcd security guide 404s. I think it should go here - https://github.com/coreos/etcd/blob/master/Documentation/op-guide/security.md

**Comment by kontsevoy** [comment]
@jchauncey thanks! fixing...
