### ISSUE TITLE
App access should support IdP app catalogs

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#5822]
### What

> Some prospects have looked at application access for non-technical teams and expressed interest in having a seamless login. For example, a user would go directly from the org’s Okta portal to an application, authenticating through Teleport but never actually interacting with Teleport.

**Comment by zmb3** [comment]
Related: #13924

**Comment by r0mant** [comment]
Yeah should be possible when using [Teleport as IdP](https://goteleport.com/docs/access-controls/idps/?scope=enterprise).
