### ISSUE TITLE
Update RBAC documentation

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5861]
## Details

RBAC is now in OSS, but some parameters are not. We have added lots of options like `request_reason` and need to show with examples how to use those too, including generating RBAC using API and integrating roles and access worfklows.

document:

* claims_to_roles
* future work: Forrest's thresholds

### Category

- New Feature
- Improve Existing
- Remove Outdated

**Comment by klizhentas** [comment]
Explain request reason and how to use it programmatically

**Comment by klizhentas** [comment]
add access controls section

  * RBAC
  * Guides
  * Reference
 
Add impersonate

**Comment by zmb3** [comment]
I believe most of this has been addressed in the last year or so.

@ptgott would you mind taking a quick look and determining whether we can close this issue?

**Comment by ptgott** [comment]
This has been completed
