### ISSUE TITLE
API package should be godoc friendly

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5863]
### What

Take a look at the example of the `autocert` package docs:

https://pkg.go.dev/golang.org/x/crypto/acme/autocert#pkg-overview

And compare to Teleport's API

https://pkg.go.dev/github.com/gravitational/teleport/api@v0.0.0-20210304221830-6d8f77815793/client

Add a couple of inline examples, and improve comments to make pkg.go.dev documentation more friendly to beginners.

**Comment by klizhentas** [comment]
cc @Joerger

**Comment by klizhentas** [comment]
cc @russjones

**Comment by klizhentas** [comment]
it seems as simple as fixing the comments in the docs, any way we can expedite this?

**Comment by awly** [comment]
Dup of https://github.com/gravitational/teleport/issues/5860
