### ISSUE TITLE
Multiple auth servers in config doesn't work if the last on is not reachable.

### ISSUE THREAD

**Issue by nmaki** [gravitational/teleport#593]
I have multiple auth servers listed in my config file. Not all the auth servers are necessarily up so I would expect the service to loop through all the listed auth servers until it can connect to one. I'm only seeing it attempt to connect to the last one though. Lets say I have the following config.
`auth_servers:
        - 10.1.0.2:3025
        - 10.1.0.3:3025
        - 10.1.0.4:3025
        - 10.1.0.5:3025
        - 10.1.0.6:3025
`
Assume 10.1.0.6 is not reachable at the time an ssh server is coming up. An ssh server will loop forever only trying to connect to the last server in the provided list.

**Comment by klizhentas** [comment]
@nmaki Can you show what's in the authservers.json file in `/var/lib/teleport`?

**Comment by nmaki** [comment]
@klizhentas there is not authservers.json in the folder /var/lib/teleport. The node has not joined a cluster yet.

**Comment by nmaki** [comment]
It looks like this line might be the culprit?

https://github.com/gravitational/teleport/blob/5a0e0616f426a3b8f6a60b786ac9dfddb7c0e238/lib/config/configuration.go#L138

**Comment by kontsevoy** [comment]
Closed by #597 (thanks @nmaki)
