### ISSUE TITLE
Consider mTLS support for app access

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5934]
### What

We could support many more cases if we supported mTLS pass through to the target. For example RDP proxying.
Consider this scenario.

**Comment by martinscholz83** [comment]
Having RDP as supported protocol will be a big plus I think. For RDP you not necessarily need mTLS except your'e using a RDP Gateway or some kind windows smart card authentication. So it should be fine to just tunnel it and open the default RDP client on your client (mstsc,...) pointing to teleport gateway and then do the authentication there.

**Comment by zmb3** [comment]
This works today with TCP app access.

@r0mant can we close this out?

**Comment by r0mant** [comment]
Yep: https://goteleport.com/docs/application-access/guides/tcp/.
