### ISSUE TITLE
Add the ability to restrict access to roles based on source ip address / CIDR range

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#5971]
### What
Add an option to role configurations allowing users to restrict access via that role to a specific source IP address or CIDR range

### How
Add an addition option to the roles configuration.  A user matching the allowed source IPs is allowed to log in, other users will be denied.  Default value should be allow any source IP.  Users with multiple roles must match the approved source IPs from all associated roles or be denied.

### Why
Additional level of network security, especially for machine to machine communication through Teleport

### Workaround
Not in Teleport.  If you have an SSO provider and the user is authenticating via SSO then it is possible the SSO can restrict access based on source IP and then you can use Teleport's IP pinning to ensure access only comes from the whitelisted IP addresses in the SSO provider (Okta example: https://support.okta.com/help/s/article/How-to-Allow-Access-to-the-Okta-Applications-Only-From-a-Specific-IP-Range?language=en_US)

gz#5860

**Comment by pschisa** [comment]
@zmb3 The IP pinning feature does not seem like it will satisfy the use case.  This would cover some situations but the other scenario is short-lived credentials generated for a machine-user which are then stored in a secrets manager for the various CI services to consume.

IP pinning seems like it won't solve the problem as the service consuming the credentials didn't issue them, and is in a different CIDR range

**Comment by pschisa** [comment]
+1 to the use case for Teleport SaaS customers looking to restrict access to specific corporate address ranges to enforce access through a VPN or on site as an added precaution

**Comment by zmb3** [comment]
Closing in favor of #10201
