### ISSUE TITLE
Expose an RBAC setting to enforce tsh to not store credentials on disk

### ISSUE THREAD

**Issue by xacrimon** [gravitational/teleport#5972]
### What

Related to #4863, @travelton made the excellent point that an RBAC option should be exposed that forces tsh to run in system agent only mode which means it only stores certificates and keys in the system SSH agent instead on disk as is the default. When #5825 is merged, this mode can be used by providing ash with the `--add-keys-to-agent=only` flag but there is no way for Teleport deployment administrators to enforce the usage of this option which may be desirable for security reasons.

**Comment by klizhentas** [comment]
seems less like something you would enforce in role, but more of a user/cluster configuration preference?

**Comment by xacrimon** [comment]
Maybe something to put in the authprefs resource?

**Comment by zmb3** [comment]
This was addressed with the PIV support in https://github.com/gravitational/teleport/pull/15874
