### ISSUE TITLE
Stop recommending long lived creds

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5978]
## Details

https://goteleport.com/teleport/docs/user-manual/#ssh-certificates-for-automation

Replace with short lived and explainer how to publish to SSM and GCP secrets manager

**Comment by inertial-frame** [comment]
We've updated all TTL examples to use more appropriate time frames. There's a Short-Lived Cert article planned that will cover the rest of this ticket.

**Comment by inertial-frame** [comment]
All articles 6.2+ are now up to date.
