### ISSUE TITLE
Unable to remove remote clusters on Teleport cloud

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#5992]
### Description
Running the command `tctl rm rc/<cluster-name>` via the proxy for Teleport cloud is not deleting the named cluster but returning an error with no message:

tctl rm rc/cluster-name
ERROR: not found

Expectation is this would remove the remote cluster from the list presented by `tctl get rc`

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Add a remote cluster to your Teleport cloud cluster
2. Attempt to remove the cluster with `tctl rm rc/<cluster-name`

### Server Details
Teleport cloud

### Client Details
tsh version - Teleport v6.0.0 git:v6.0.0-0-g56547d4e3 go1.15.5

### Debug Logs

> tctl rm rc/cluster-name -d
> 
> DEBU             Debug logging has been enabled. common/tctl.go:324
> DEBU             No config file or identity file, loading auth config via extension. common/tctl.go:350
> DEBU [KEYSTORE]  Returning SSH certificate "/Users/paulschisa/.tsh/keys/schisa.teleport.sh/superpaul-cert.pub" valid until "2021-03-15 22:07:39 -0400 EDT", TLS certificate "/Users/paulschisa/.tsh/keys/schisa.teleport.sh/superpaul-x509.pem" valid until "2021-03-16 02:07:39 +0000 UTC". client/keystore.go:355
> DEBU             Found active profile: {https   schisa.teleport.sh:443   false   } superpaul. tctl/profile.go:45
> DEBU [KEYSTORE]  Returning SSH certificate "/Users/paulschisa/.tsh/keys/schisa.teleport.sh/superpaul-cert.pub" valid until "2021-03-15 22:07:39 -0400 EDT", TLS certificate "/Users/paulschisa/.tsh/keys/schisa.teleport.sh/superpaul-x509.pem" valid until "2021-03-16 02:07:39 +0000 UTC". client/keystore.go:355
> DEBU             Setting auth server to web proxy schisa.teleport.sh:443. tctl/profile.go:77
> DEBU             Connecting to auth servers: [{schisa.teleport.sh:443 tcp }]. common/tctl.go:195
> DEBU [CLIENT]    HTTPS client init(proxyAddr=schisa.teleport.sh:443, insecure=false) client/weblogin.go:318
> DEBU             Attempting to connect using reverse tunnel address schisa.teleport.sh:3024. common/tctl.go:233
> DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:221
> DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:221
> DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:136
> DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:136
> DEBU [CLIENT]    Validated host schisa.teleport.sh:3024. client/keyagent.go:98
> DEBU [CLIENT]    Validated host schisa.teleport.sh:3024. client/keyagent.go:98
> 
> ERROR REPORT:
> Original Error: *trace.NotFoundError not found
> Stack Trace:
> 	/go/src/github.com/gravitational/teleport/lib/utils/utils.go:372 github.com/gravitational/teleport/lib/utils.OpaqueAccessDenied
> 	/go/src/github.com/gravitational/teleport/lib/auth/auth_with_roles.go:62 github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).action
> 	/go/src/github.com/gravitational/teleport/lib/auth/auth_with_roles.go:2177 github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).DeleteRemoteCluster
> 	/go/src/github.com/gravitational/teleport/lib/auth/apiserver.go:2438 github.com/gravitational/teleport/lib/auth.(*APIServer).deleteRemoteCluster
> 	/go/src/github.com/gravitational/teleport/lib/auth/apiserver.go:292 github.com/gravitational/teleport/lib/auth.(*APIServer).withAuth.func1
> 	/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:61 github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1
> 	/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:387 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
> 	/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:173 github.com/gravitational/teleport/lib/httplib.RewritePaths.func1
> 	/opt/go/src/net/http/server.go:2042 net/http.HandlerFunc.ServeHTTP
> 	/go/src/github.com/gravitational/teleport/lib/auth/middleware.go:529 github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP
> 	/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
> 	/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
> 	/opt/go/src/net/http/server.go:2843 net/http.serverHandler.ServeHTTP
> 	/opt/go/src/net/http/server.go:1925 net/http.(*conn).serve
> 	/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit
> Caught:
> 	/private/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:131 github.com/gravitational/teleport/lib/httplib.ConvertResponse
> 	/private/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/auth/clt.go:273 github.com/gravitational/teleport/lib/auth.(*Client).Delete
> 	/private/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/auth/clt.go:895 github.com/gravitational/teleport/lib/auth.(*Client).DeleteRemoteCluster
> 	/private/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:456 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).Delete
> 	/private/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tctl/common/resource_command.go:137 github.com/gravitational/teleport/tool/tctl/common.(*ResourceCommand).TryRun
> 	/private/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/e/tool/tctl/resource_command.go:41 main.(*ResourceCommandE).TryRun
> 	/private/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tctl/common/tctl.go:164 github.com/gravitational/teleport/tool/tctl/common.Run
> 	/private/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/e/tool/tctl/main.go:29 main.main
> 	/usr/local/go/src/runtime/proc.go:204 runtime.main
> 	/usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit
> User Message: not found

**Comment by webvictim** [comment]
Try adding this rule to a role that the user has:

```yaml
spec:
  allow:
    rules:
    - resources:
      - remote_cluster
      verbs:
      - delete
```

**Comment by pschisa** [comment]
Adding the rule to the role resolved the issue.  I am now able to run `tctl rm rc/<cluster-name>` successfully.

**Comment by webvictim** [comment]
I believe that the root cause of this issue is still the same as #5352 - `tctl` behaves differently when run locally on the same host as the auth server to the way it does when run remotely with certfiicates from `tsh login`. We should probably leave this issue open for tracking a fix to that, as it will affect other cloud customers.
