### ISSUE TITLE
Add a plug-in system

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#600]
Teleport is easy to extend by implementing various interfaces, but we need a _standartized_ way to add optional functionality.

Something like `contrib` package with a simple "must implement" interface everyone would use. When done, move DynamoDB to this design.

**Comment by kontsevoy** [comment]
Waiting on Golang 1.8 plugin system.

**Comment by benarent** [comment]
Doing a ticket cleanup, this should be covered by upcoming API / SDK work.
