### ISSUE TITLE
Introduce standard linting rules

### ISSUE THREAD

**Issue by gzigzigzeo** [gravitational/teleport#6013]
In the Teleport main repo, we have the following linter setup:

```sh
FLAGS = "golint,unused,govet,typecheck,deadcode,goimports,varcheck,structcheck,bodyclose,staticcheck,ineffassign,unconvert,misspell"
golangci-lint run \
	--disable-all \
	--exclude-use-default \
	--exclude='S1002: should omit comparison to bool constant' \
	--skip-dirs vendor \
	--uniq-by-line=false \
	--max-same-issues=0 \
	--max-issues-per-linter 0 \
	--timeout=5m \
	--enable $(GO_LINTERS) \
	$(GO_LINT_FLAGS)
```

In teleport-plugins repo the setup is slightly different:

```sh
FLAGS = "unused,govet,typecheck,deadcode,goimports,varcheck,structcheck,bodyclose,staticcheck,ineffassign,unconvert,misspell,gosimple,golint"
golangci-lint run \
	--disable-all \
	--exclude-use-default \
	--skip-dirs vendor \
	--uniq-by-line=false \
	--max-same-issues=0 \
	--max-issues-per-linter 0 \
	--timeout=5m \
	--enable $(GO_LINTERS) \
	$(FLAGS)
```

Problems:

1. Setup is different, so, our codebase follows slightly different standards.
2. `--exclude-use-default` flag excludes the important rule which must be checked:

```
    # EXC0002 golint: Annoying issue about not having a comment. The rare codebase has such comments
    - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
```

Proposition:

1. Create unified rule definitions file (`.golangci.yml`) for all our repos.
2. Set `--exclude-use-default=false`, and replace it with manual exclusions for rules we do not truly need, keeping EXC0002, for instance.
3. Add an example configuration for pre-commit hook which would run the linter over a new files locally (with `golangci-lint run --new`) and would block pushing problematic code, or, at least, warn a commiter (optional, one could use Lefthook or similar tool to automate it).
4. Add linters to the CI (that possibly will require explicit exclusion of the "old" code which could still have issues).

**Comment by awly** [comment]
Agree, we should update `teleport-plugins` to use the same linter settings.
I don't think moving them to a config file makes much of a difference, just a layer of indirection.

As for `--exclude-use-default`, here are the specific checks it filters out:

```
                                         # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
                                         - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked

                                         # EXC0002 golint: Annoying issue about not having a comment. The rare codebase has such comments
                                         - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)

                                         # EXC0003 golint: False positive when tests are defined in package 'test'
                                         - func name will be used as test\.Test.* by other packages, and that stutters; consider calling this

                                         # EXC0004 govet: Common false positives
                                         - (possible misuse of unsafe.Pointer|should have signature)

                                         # EXC0005 staticcheck: Developers tend to write in C-style with an explicit 'break' in a 'switch', so it's ok to ignore
                                         - ineffective break statement. Did you mean to break out of the outer loop

                                         # EXC0006 gosec: Too many false-positives on 'unsafe' usage
                                         - Use of unsafe calls should be audited

                                         # EXC0007 gosec: Too many false-positives for parametrized shell calls
                                         - Subprocess launch(ed with variable|ing should be audited)

                                         # EXC0008 gosec: Duplicated errcheck checks
                                         - (G104|G307)

                                         # EXC0009 gosec: Too many issues in popular repos
                                         - (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)

                                         # EXC0010 gosec: False positive is triggered by 'src, err := ioutil.ReadFile(filename)'
                                         - Potential file inclusion via variable

                                         # EXC0011 stylecheck: Annoying issue about not having a comment. The rare codebase has such comments
                                         - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
``` 

The only ones that may be worth enabling are: EXC0004, EXC0005.

EXC0002 and EXC0011 i'm unsure about. It's generally nice, but there are cases where it's redundant.
More importantly, we'd need for someone to clean up all 680 places where we miss exported comments, which is hard to prioritize against other work.

**Comment by webvictim** [comment]
One benefit of using a `.golangci.yml` file would be that many editors can automatically read it and determine which settings to enable/disable.

**Comment by gzigzigzeo** [comment]
I think, yaml file has several benefits:

1. It allows to fine-tune `golangci-lint` settings. For example, specific linter options could be passed from the file only, there's no way to pass them from command-line.
2. I totally agree, it allows to share the same setup with an editor.
3. It provides convention: everyone would know where to look for linting rules.

**Comment by gzigzigzeo** [comment]
I also agree that EX0002 is very questionable and does not provide any useful info most of the time, but EX0011 is rather useful than not.

**Comment by webvictim** [comment]
I think if we were to enable EXC0011 on `teleport` currently there would be many fixes required; unfortunately we don't have time at the moment. We can probably enable it for `teleport-plugins` though, as the codebase is much smaller.

**Comment by awly** [comment]
```
                                         # EXC0002 golint: Annoying issue about not having a comment. The rare codebase has such comments
                                         - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
                                         # EXC0011 stylecheck: Annoying issue about not having a comment. The rare codebase has such comments
                                         - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
```

They're the same thing coming from two different liners, right?

**Comment by gzigzigzeo** [comment]
Yes, my mistake, I read 0002 as the requirement of having the comment for a package definition. They are the same thing from different linters. We could start with teleport-plugins and migrate to main codebase later, that's a good proposition.
