### ISSUE TITLE
Broken doc link for `passwords` in search.

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#6014]
## Details
When searching for `passwords` in the docs using the search bar the following shows up (see image). 

![Screen Shot 2021-03-16 at 9 07 21 AM](https://user-images.githubusercontent.com/1424442/111314667-ffed5800-8637-11eb-811a-064b0b0a1b38.png)

But when you click the link it takes you to this link: https://goteleport.com/teleport/docs/cloud/#how-do-you-store-passwords Which has nothing to do or show regarding FAQ's or passwords.  I searched the FAQ page manually and also did not see anything related to passwords.

### Category

- Improve Existing

**Comment by webvictim** [comment]
Should be redirected to https://goteleport.com/teleport/docs/cloud/faq/#how-do-you-store-passwords

**Comment by inertial-frame** [comment]
Looks like Algolia provides support for promoting various objects, topics, or results in a customized way: https://www.algolia.com/products/rules/ - using that we could improve the `password` result-set by promoting `certificates`, `authentication`, or other related keywords.

**Comment by ptgott** [comment]
Is this working for you now, @Valien?

**Comment by Valien** [comment]
All good!
