### ISSUE TITLE
Track viewing history of session recordings

### ISSUE THREAD

**Issue by at6432** [gravitational/teleport#6017]
### Feature Request
There should be an audit log entry when a user views a session recording. Currently users with sufficient privileges can access and view session recordings anonymously. 

### Motivation
Some compliance/regulatory standards, such as HIPAA, require organizations to retain logs of all activity where sensitive data (PII/PHI) may be exposed to internal personnel.

### Who is it for?
Community, Pro, Enterprise

**Comment by zmb3** [comment]
Closing as duplicate of #13880 which is being worked on now.
