### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by albertog** [gravitational/teleport#602]
can you connect a node host to proxy host in other diferent network ? if itis false can I have a proxy connected with several proxies ?

**Comment by kontsevoy** [comment]
@albertog yes you can. but you'd need two proxies (one for each network). 

It will look something like this:

```
[node-a] <---> [proxy-on-network-a]  <-------> [proxy-on-network-b] <---> [node-b]
```
... and you can connect from [node-a] to [node-b] using this syntax:

```
$ tsh --cluster=proxy-on-network-b ssh node-b
```

This feature is called "trusted clusters" and is covered here:
https://gravitational.com/teleport/docs/admin-guide/#trusted-clusters
