### ISSUE TITLE
Improve "tctl status" display of CA pins.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#6032]
At the moment `tctl status` shows the old CA pin during two thirds of CA rotation and only the new CA pin for the last third. This makes joining a cluster with a CA pin during rotation extremely difficult.

**Comment by GavinFrazar** [comment]
This looks like it's already been solved unless I'm not understanding how to reproduce it @russjones

**Comment by GavinFrazar** [comment]
closing this as I believe it's already been resolved
