### ISSUE TITLE
Teleport should emit "Audit Events" on SSO login errors 

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#6046]
Currently it's impossible to troubleshoot SSO errors (SAML, OIDC, Github) without having access to Teleport logs (or restarting Teleport to enable a debug mode)

Instead, Teleport Proxy should emit audit "Failed Login" events with the error description. This way people can troubleshoot the issue from web UI.

**Comment by klizhentas** [comment]
I think it's partially already true - we do emit descriptions on SSO errors, but may be not all errors? What error cases are not covered?

**Comment by alex-kovoy** [comment]
@klizhentas there are several critical places where it's missing on the auth service around `CreateXXXAuthRequest`/`ValidateXXXRequest`

https://github.com/gravitational/teleport/blob/master/lib/auth/saml.go#L304
https://github.com/gravitational/teleport/blob/master/lib/auth/oidc.go#L192
https://github.com/gravitational/teleport/blob/master/lib/auth/github.go#L40

Why cannot we emit them on the auth_with_roles.go layer? Seems like a natural place for this kind of stuff. 

There are also some errors on the proxy side 
https://github.com/gravitational/teleport/blob/master/lib/auth/github.go#L40 But I think it's OK to ignore it for now
