### ISSUE TITLE
Database access should support graceful shutdown

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#6047]
### What

In the current database access implementation, an active database session (e.g. `psql` or `mysql`) will lose connection if a Teleport process restarts for example.

Depending on the client implementation, it may reconnect after the service comes back up but a better solution would be to have Teleport wait for the active db sessions to terminate (possibly with some grace period) during hot reload. Teleport SSH connections support that, database connections should too.

Here's what we need to do:

* Confirm the current behavior and see if psql/mysql can reconnect after Teleport app agent restarts.
* Implement graceful shutdown support similar to how SSH connections are handled.

### How

Should work similar to SSH.

### Why

Nobody likes their sessions to be terminated.

### Workaround

N/A

**Comment by greedy52** [comment]
Implemented by https://github.com/gravitational/teleport/pull/27491
