### ISSUE TITLE
Allow Configuring Auth Preferences from Web UI

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#6059]
There needs to be a way to configure/change auth preferences from Teleport Web UI.

For this feature we need:

- [ ]  UI Designs.
- [ ]  Auth Service API.
- [ ]  Implement UI for the Auth Preferences.

@klizhentas it seems that Auth API will be ready soon, could you provide us the designs for UI?

**Comment by zmb3** [comment]
Tracking this at #11578 now.
