### ISSUE TITLE
RFD request: location aware tsh routing

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6082]
### What

@awly mentioned that @andrejtokarcik had an idea about tsh location aware routing. This is a very important for cloud and large scale deployment. Let's start with RFD.

**Comment by awly** [comment]
The idea is briefly described in https://github.com/gravitational/teleport/blob/7a07532b2b9aca77b823989c3b98af6e7c6e3229/rfd/0019-cluster-routing.md#future-work

**Comment by awly** [comment]
@klizhentas @andrejtokarcik while we could make some tweaks in routing for trusted clusters, it would need customer opt-in and only apply in very specific setups.

IMO we should leave clever routing optimizations to DNS and load balancers. It seems out of scope for Teleport to solve.
Closing this for now, reopen if you disagree.
