### ISSUE TITLE
Support persistent `--user` configuration

### ISSUE THREAD

**Issue by matschaffer** [gravitational/teleport#6085]
### What
What would you like Teleport to do differently?

We have teleport set up for our org so everyone comes in as `ubuntu`

```
tsh ssh ubuntu@k=v
```

It'd be great to not have to include `ubuntu@` every time. But instead just use:

```
tsh ssh k=v
```

If I do that today it tries to use my laptop's `$USER` which isn't supported by our instances.

### How
How would you implement this?

A couple of ideas come to mind:
- Support `$TELEPORT_USER` env var to pre-select the `--user` value for `tsh ssh`
- Support some sort of `Host teleport` match in `~/.ssh/config` and honor a `User` option in there
- Allow specification of default user in teleport host data, have `tsh ssh` use that if no user is specified

### Why
Why do you need this?

The extra typing/remembering/training to include the `ubuntu@` would be nice to drop.

### Workaround
If a workaround exists, please include it.

Some folks use bash wrappers to get around this, but not everyone installs them. Everyone installs `tsh` so would be nice if the tool supported it out of the box.

**Comment by webvictim** [comment]
There's actually already an environment variable that does this - `TELEPORT_LOGIN`

**Comment by matschaffer** [comment]
Oh, woah. That's fantastic.

I don't see that mentioned anywhere on https://goteleport.com/docs/cli-docs/#tsh-ssh - so maybe just a doc update is in order.

**Comment by savv3** [comment]
Wow, why is this not part of the documentation? Was lucky to find this issue. Was searching for exactly this thing

**Comment by webvictim** [comment]
It's under the `tsh` section of the docs, see here: https://goteleport.com/docs/setup/reference/cli/#tsh-mfa-rm

(it's missing a heading which makes it harder to link to)
