### ISSUE TITLE
Web UI Idle Timeout

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#6092]
Right now Teleport supports idle timeouts for SSH sessions, however the Web UI does not. If you leave your browser open, the browser will continue to extend your Web UI session. For compliance purposes, we should idle timeout your Web UI session as well.

**Comment by alex-kovoy** [comment]
@russjones Is it about Web SSH (websockets) or browser sessions? Does `tsh` has a timeout interval?

**Comment by russjones** [comment]
Browser session.
