### ISSUE TITLE
Move "lib/services/license.go" to "/api/types.go"

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#6093]
### Description

Need to move `lib/services/license.go` under the ` /api/types.go` so when Cloud revendors this files, it does not pick up everything from the services (including some k8s dependencies). 

This change is about moving files from 1 location to another.

**Comment by Joerger** [comment]
What does Cloud need from `lib/services/license.go`? The only thing in there is json marshaling logic which can be replaced with basic json marshaling. Perhaps an old version of the file is vendored?

**Comment by alex-kovoy** [comment]
We have been using these marshalers to marshal/unmarshal the license. I replaced them with the basic JSON marshaling as it does not look that we need those.
