### ISSUE TITLE
Documentation error.

### ISSUE THREAD

**Issue by leif-ohlin** [gravitational/teleport#610]
Hello.

In your admin guide:
https://github.com/gravitational/teleport/blob/master/docs/admin-guide.md
and
http://gravitational.com/teleport/docs/admin-guide/

In your examples for setting up trusted clusters you have two different ways to do it.
Once you put in under the proxy_service heading - which is wrong.
and once you put it under the auth_service heading - which works much better.

**Comment by kontsevoy** [comment]
Thank you @leif-ohlin
