### ISSUE TITLE
tsh agent with --cluster

### ISSUE THREAD

**Issue by leif-ohlin** [gravitational/teleport#611]
Hello

First the setup:
One "main" cluster - publicly accessible IP, full stack of teleport services.
Several other remote nodes, behind NAT. Each remote node is actually a full cluster as well. Each node is on a different NATed network, at different sites. Not accessible from the internet, but with access to the internet and thus to the main cluster.
Trust is setup from the remote nodes to the main cluster.
Clients can log in with tsh from anywhere with internet access to any nodes.
So far so good.

Now - we'd like to use the "normal" OpenSSH client as well - for compatibility with other standard tools such as sshuttle.
Thus - "tsh --proxy main.fqdn --cluster some_cluster agent" - but tsh seems to ignore --cluster in agent mode?
This seems to be confirmed by the main cluster log in debug mode:
"DEBU[0029] proxy_subsystem: no site specified. connecting to default: 'main'  file=srv/proxy.go:127"

Is this possible to do?

**Comment by kontsevoy** [comment]
@leif-ohlin this appears to be a bug. Thank you for reporting!

**Comment by russjones** [comment]
@leif-ohlin We've made some changes to Teleport to support OpenSSH interoperability. What you want to do (use OpenSSH clients to connect to Teleport nodes) now works on master.

In addition, you don't have to pass `--cluster` to `tsh` when launching the agent. Also, if you don't want to use the Teleport agent at all, we also now load your keys into the running system SSH agent as well.

So this should resolve the issues you have been having. You can build from master and give it a shot or wait a few weeks and get the binary when we officially document and release the next version of Teleport.

**Comment by kontsevoy** [comment]
@russjones is this fixed? Shall we close this?

**Comment by russjones** [comment]
@kontsevoy I think we can close this.

@leif-ohlin if you are still running into issues feel free to re-open/comment and I can dig in further.
