### ISSUE TITLE
Teleport 6.0.2 - Approving access request within Slack fails to approve role within Teleport

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#6120]
### Description

**What happened**:
Approving an access request within Slack fails to approve the request within Teleport
**What you expected to happen**:
Approving an access request in Slack should approve the request as expected

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Request a role within Teleport
2. Click "Approve" within Slack to approve the request
3. Approval fails

### Server Details
- Teleport version (run `teleport version`): 6.0.2
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

### Debug Logs
`ERRO  Failed to parse json body error:json: cannot unmarshal object into Go struct field InteractionCallback.state of type string slack_http_id:1616530738-2 slack/callback_server.go:90`

**Comment by eigokor** [comment]
Here is a workaround to fix this, until official release:

https://github.com/slack-go/slack/issues/816#issuecomment-704200440

**Comment by Joerger** [comment]
@fspmarshall You mentioned that this should no longer be an issue, can you confirm that and close this if so?

**Comment by fspmarshall** [comment]
Should be fixed as of [v6.1.0](https://github.com/gravitational/teleport-plugins/releases/tag/v6.1.0).
