### ISSUE TITLE
Further app/db access docs updates

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#6138]
Need to add the following information to the docs regarding app/db access:

- [x] Database access Cloud SQL guide.
- [x] Database access audit events.
- [x] Database access more GUI client guides.
- [x] Database access different AWS accounts.
- [x] App access RBAC.
- [ ] App access audit events.
- [x] App access architecture (similar to database access).

**Comment by ptgott** [comment]
@r0mant Just checking to see if there are any updates on this issue. Maybe we could split some of these checkbox items into separate issues so we can track them independently?

**Comment by ptgott** [comment]
#41009 satisfies the architecture item

**Comment by ptgott** [comment]
Since the final unresolved bullet now overlaps with #10350, I am closing this so we can track this work in the newer issue.
