### ISSUE TITLE
http: panic: invalid memory address

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#6141]
### Description

**What happened**:
While helping a customer I noticed Teleport panicking. I think it's a latest version of Teleport but can't be 100% sure. 

![image](https://user-images.githubusercontent.com/559288/112400092-d5993b80-8cc4-11eb-8e27-e5035644a9b3.png)

**Comment by xacrimon** [comment]
After some source digging and going off the line counts in the stacktrace this seems to be a v5 issue as the code in the stacktrace has been moved and rewritten in v6.
