### ISSUE TITLE
Investigate using aptly for DEB repo

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#6159]
reprepro is complicated to use and hard to test locally - it needs a lot of mounts in specific places, plus the filesystem structure is very finicky and you have to be careful not to mount anything in the wrong location etc.

[Aptly](https://github.com/aptly-dev/aptly) looks like it'd be a lot easier to use and would also allow us to have multiple package versions in the same repo, which people have requested. It's also written in Go, which would inevitably make it easier to understand. It's MIT-licensed, which I think is OK.

**Comment by wadells** [comment]
I'm consolidating tracking of this under https://github.com/gravitational/teleport/issues/8166.  I'll keep aptly in mind as I evaluate fixes.
