### ISSUE TITLE
Export audit events to S3 in parquet format

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6160]
If we support S3 audit events in Parquet format, this will make us compatible with a range of analytics and SIEM tools out of the box - from Snowflake to Panther.

gz#4058

**Comment by klizhentas** [comment]
@russjones is that something we are going to address as 7.0 or 6.3? I know we discussed this, but haven't settled on a date/release.

**Comment by zmb3** [comment]
@tobiaszheller this is complete, right?
