### ISSUE TITLE
6.1 Test Plan

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#6187]
## Manual Testing Plan

Below are the items that should be manually tested with each release of Teleport.
These tests should be run on both a fresh install of the version to be released
as well as an upgrade of the previous version of Teleport.

### Teleport Sanity Test - @russjones 

* [ ] Perform trusted clusters, Web and SSH sanity check with all teleport components deployed in FIPS mode.
* [ ] Perform trusted clusters, Web and SSH sanity check with all teleport components deployed in non-FIPS mode.

- [x] RBAC @awly 

  Make sure that invalid and valid attempts are reflected in audit log.

  - [x] Successfully connect to node with correct role
  - [x] Unsuccessfully connect to a node in a role restricting access by label
  - [x] Unsuccessfully connect to a node in a role restricting access by invalid SSH login
  - [x] Allow/deny role option: SSH agent forwarding
  - [x] Allow/deny role option: Port forwarding

- [x] Verify that custom PAM environment variables are available as expected. @quinqu 

- [ ] Users @benarent @awly 
With every user combination, try to login and signup with invalid second factor, invalid password to see how the system reacts.

  - [x] Adding Users Password Only
  - [x] Adding Users OTP
  - [x] Adding Users U2F
  - [x] Managing MFA devices
    - [x] Add an OTP device with `tsh mfa add`
    - [x] Add a U2F device with `tsh mfa add`
    - [x] List MFA devices with `tsh mfa ls`
    - [x] Remove an OTP device with `tsh mfa rm`
    - [x] Remove a U2F device with `tsh mfa rm`
    - [x] Attempt removing the last MFA device on the user
      - [x] with `second_factor: on` in `auth_service`, should fail
      - [x] with `second_factor: optional` in `auth_service`, should succeed
  - [x] Login Password Only
  - [x] Login with MFA
    - [x] Add 2 OTP and 2 U2F devices with `tsh mfa add`
    - [x] Login via OTP
    - [x] Login via U2F
  - [x] Login OIDC
  - [x] Login SAML
  - [x] Login GitHub
  - [x] Deleting Users

- [ ] Session Recording @andrejtokarcik @tcsc 
  - [ ] Session recording can be disabled
  - [x] Sessions can be recorded at the node
    - [x] Sessions in remote clusters are recorded in remote clusters
  - [x] Sessions can be recorded at the proxy
    - [x] Sessions on remote clusters are recorded in the local cluster
    - [x] Enable/disable host key checking.

- [x] Audit Log @r0mant  
  - [x] Failed login attempts are recorded
  - [x] Interactive sessions have the correct Server ID
    - [x] Server ID is the ID of the node in regular mode
    - [x] Server ID is randomly generated for proxy node
  - [x] Exec commands are recorded
  - [x] `scp` commands are recorded
  - [x] Subsystem results are recorded

- [x] Interact with a cluster using `tsh` @xacrimon @Joerger 

   These commands should ideally be tested for recording and non-recording modes as they are implemented in a different ways.

  - [x] tsh ssh \<regular-node\>
  - [x] tsh ssh \<node-remote-cluster\>
  - [x] tsh ssh -A \<regular-node\>
  - [x] tsh ssh -A \<node-remote-cluster\>
  - [x] tsh ssh \<regular-node\> ls
  - [x] tsh ssh \<node-remote-cluster\> ls
  - [x] tsh join \<regular-node\>
  - [x] tsh join \<node-remote-cluster\>
  - [x] tsh play \<regular-node\>
  - [x] tsh play \<node-remote-cluster\>
  - [x] tsh scp \<regular-node\>
  - [x] tsh scp \<node-remote-cluster\>
  - [x] tsh ssh -L \<regular-node\>
  - [x] tsh ssh -L \<node-remote-cluster\>
  - [x] tsh ls
  - [x] tsh clusters

- [x] Interact with a cluster using `ssh`  @awly
   Make sure to test both recording and regular proxy modes.
  - [x] ssh \<regular-node\>
  - [x] ssh \<node-remote-cluster\>
  - [x] ssh -A \<regular-node\>
  - [x] ssh -A \<node-remote-cluster\>
  - [x] ssh \<regular-node\> ls
  - [x] ssh \<node-remote-cluster\> ls
  - [x] scp \<regular-node\>
  - [x] scp \<node-remote-cluster\>
  - [x] ssh -L \<regular-node\>
  - [x] ssh -L \<node-remote-cluster\>

- [ ] Interact with a cluster using the Web UI @quinqu 
  - [x] Connect to a Teleport node
  - [x] Connect to a OpenSSH node
  - [ ] Check agent forwarding is correct based on role and proxy mode.

### User accounting @benarent 

- [x] Verify that active interactive sessions are tracked in `/var/run/utmp` on Linux.
- [x] Verify that interactive sessions are logged in `/var/log/wtmp` on Linux.

### Combinations @r0mant @tcsc 

For some manual testing, many combinations need to be tested. For example, for
interactive sessions the 12 combinations are below.

- [x] Connect to a OpenSSH node in a local cluster using OpenSSH.
- [x] Connect to a OpenSSH node in a local cluster using Teleport.
- [x] Connect to a OpenSSH node in a local cluster using the Web UI.
- [x] Connect to a Teleport node in a local cluster using OpenSSH.
- [x] Connect to a Teleport node in a local cluster using Teleport.
- [x] Connect to a Teleport node in a local cluster using the Web UI.
- [x] Connect to a OpenSSH node in a remote cluster using OpenSSH.
- [x] Connect to a OpenSSH node in a remote cluster using Teleport.
- [x] Connect to a OpenSSH node in a remote cluster using the Web UI.
- [x] Connect to a Teleport node in a remote cluster using OpenSSH.
- [x] Connect to a Teleport node in a remote cluster using Teleport.
- [x] Connect to a Teleport node in a remote cluster using the Web UI.

### Teleport with EKS/GKE @webvictim @awly 

* [x] Deploy Teleport on a single EKS cluster
* [x] Deploy Teleport on two EKS clusters and connect them via trusted cluster feature
* [x] Deploy Teleport Proxy outside of GKE cluster fronting connections to it (use [this script](https://github.com/gravitational/teleport/blob/master/examples/k8s-auth/get-kubeconfig.sh) to generate a kubeconfig)
* [x] Deploy Teleport Proxy outside of EKS cluster fronting connections to it (use [this script](https://github.com/gravitational/teleport/blob/master/examples/k8s-auth/get-kubeconfig.sh) to generate a kubeconfig)

### Teleport with multiple Kubernetes clusters @Joerger @awly 

Note: you can use GKE or EKS or minikube to run Kubernetes clusters.
Minikube is the only caveat - it's not reachable publicly so don't run a proxy there.

* [x] Deploy combo auth/proxy/kubernetes_service outside of a Kubernetes cluster, using a kubeconfig
  * [x] Login with `tsh login`, check that `tsh kube ls` has your cluster
  * [x] Run `kubectl get nodes`, `kubectl exec -it $SOME_POD -- sh`
  * [x] Verify that the audit log recorded the above request and session
* [x] Deploy combo auth/proxy/kubernetes_service inside of a Kubernetes cluster
  * [x] Login with `tsh login`, check that `tsh kube ls` has your cluster
  * [x] Run `kubectl get nodes`, `kubectl exec -it $SOME_POD -- sh`
  * [x] Verify that the audit log recorded the above request and session
* [x] Deploy combo auth/proxy_service outside of the Kubernetes cluster and kubernetes_service inside of a Kubernetes cluster, connected over a reverse tunnel
  * [x] Login with `tsh login`, check that `tsh kube ls` has your cluster
  * [x] Run `kubectl get nodes`, `kubectl exec -it $SOME_POD -- sh`
  * [x] Verify that the audit log recorded the above request and session
* [x] Deploy a second kubernetes_service inside of another Kubernetes cluster, connected over a reverse tunnel
  * [x] Login with `tsh login`, check that `tsh kube ls` has both clusters
  * [x] Switch to a second cluster using `tsh kube login`
  * [x] Run `kubectl get nodes`, `kubectl exec -it $SOME_POD -- sh` on the new cluster
  * [x] Verify that the audit log recorded the above request and session
* [x] Deploy combo auth/proxy/kubernetes_service outside of a Kubernetes cluster, using a kubeconfig with multiple clusters in it
  * [x] Login with `tsh login`, check that `tsh kube ls` has all clusters

### Migrations @russjones 

* [ ] Migrate trusted clusters from 2.4.0 to 2.5.0
  * [ ] Migrate auth server on main cluster, then rest of the servers on main cluster
        SSH should work for both main and old clusters
  * [ ] Migrate auth server on remote cluster, then rest of the remote cluster
       SSH should work

### Command Templates

When interacting with a cluster, the following command templates are useful:

#### OpenSSH

```
# when connecting to the recording proxy, `-o 'ForwardAgent yes'` is required.
ssh -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p" \
  node.example.com

# the above command only forwards the agent to the proxy, to forward the agent
# to the target node, `-o 'ForwardAgent yes'` needs to be passed twice.
ssh -o "ForwardAgent yes" \
  -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p" \
  node.example.com

# when connecting to a remote cluster using OpenSSH, the subsystem request is
# updated with the name of the remote cluster.
ssh -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p@foo.com" \
  node.foo.com
```

#### Teleport

```
# when connecting to a OpenSSH node, remember `-p 22` needs to be passed.
tsh --proxy=proxy.example.com --user=<username> --insecure ssh -p 22 node.example.com

# an agent can be forwarded to the target node with `-A`
tsh --proxy=proxy.example.com --user=<username> --insecure ssh -A -p 22 node.example.com

# the --cluster flag is used to connect to a node in a remote cluster.
tsh --proxy=proxy.example.com --user=<username> --insecure ssh --cluster=foo.com -p 22 node.foo.com
```

### Teleport with SSO Providers @benarent 

- [x] G Suite install instructions work
    - [x] G Suite Screenshots are up to date
- [ ] ActiveDirectoy install instructions work
    - [ ] Active Directoy Screenshots are up to date
- [x] Okta install instructions work
    - [x] Okta Screenshots are up to date
- [x] OneLogin install instructions work
    - [x] OneLogin Screenshots are up to date
- [x] OIDC install instructions work
    - [x] OIDC Screenshots are up to date

### Teleport Plugins @quinqu 

- [x] Test receiving a message via Teleport Slackbot
- [x] Test receiving a new Jira Ticket via Teleport Jira

## Main
For main, test with admin role that has access to all resources.

#### Top Nav
- [x] Verify that cluster selector displays all (root + leaf) clusters
- [x] Verify that user name is displayed
- [x] Verify that user menu shows logout, help&support, and account settings

#### Side Nav
- [x] Verify that each item has an icon
- [x] Verify that Collapse/Expand works and collapsed has icon `>`, and expand has icon `v`
- [x] Verify that it automatically expands and highlights the item on page refresh

#### Servers aka Nodes
- [x] Verify that "Servers" table shows all joined nodes
- [x] Verify that "Connect" button shows a list of available logins
- [x] Verify that "Hostname", "Address" and "Labels" columns show the current values
- [x] Verify that "Search" by hostname, address, labels works
- [x] Verify that terminal opens when clicking on one of the available logins
- [x] Verify that clicking on `Add Server` button renders dialogue set to `Automatically` view
  - [x] Verify clicking on `Regenerate Script` regenerates token value in the bash command
  - [x] Verify using the bash command successfully adds the server (refresh server list)
  - [x] Verify that clicking on `Manually` tab renders manual steps
  - [x] Verify that clicking back to `Automatically` tab renders bash command

#### Applications
- [x] Verify that all apps registered are shown
- [x] Verify that clicking on the app icon takes you to another tab
- [x] Verify that clicking on `Add Application` button renders dialogue
  - [x] Verify input validation (prevent empty value and invalid url)
  - [x] Verify after input and clicking on `Generate Script`, bash command is rendered
  - [x] Verify clicking on `Regenerate` button regenerates token value in bash command
  - [x] Verify using the bash command successfully adds the application (refresh app list)

#### Active Sessions
- [x] Verify that "empty" state is handled
- [x] Verify that it displays the session when session is active
- [x] Verify that "Description", "Session ID", "Users", "Nodes" and "Duration" columns show correct values
- [x] Verify that "OPTIONS" button allows to join a session

#### Audit log
- [x] Verify that time range button is shown and works
- [x] Verify that clicking on `Session Ended` event icon, takes user to session player
- [x] Verify event detail dialogue renders when clicking on events `details` button
- [x] Verify searching by type, description, created works

#### Users
- [x] Verify that users are shown
- [x] Verify that creating a new user works
- [x] Verify that editing user roles works
- [x] Verify that removing a user works
- [x] Verify resetting a user's password works
- [x] Verify search by username, roles, and type works

#### Auth Connectors
- [x] Verify that creating OIDC/SAML/GITHUB connectors works
- [x] Verify that editing  OIDC/SAML/GITHUB connectors works
- [x] Verify that error is shown when saving an invalid YAML
- [x] Verify that correct hint text is shown on the right side
- [x] Verify that encrypted SAML assertions work with an identity provider that supports it (Azure).

#### Auth Connectors Card Icons
- [x] Verify that GITHUB card has github icon
- [x] Verify that SAML card has SAML icon
- [x] Verify that OIDC card has OIDC icon
- [x] Verify when there are no connectors, empty state renders

#### Roles
- [x] Verify that roles are shown
- [x] Verify that "Create New Role" dialog works
- [x] Verify that deleting and editing works
- [x] Verify that error is shown when saving an invalid YAML
- [x] Verify that correct hint text is shown on the right side

#### Managed Clusters
- [x] Verify that it displays a list of clusters (root + leaf)
- [x] Verify that every menu item works: nodes, apps, audit events, session recordings.

#### Help & Support
- [ ] Verify that all URLs work and correct (no 404)

### Creating Access Rquests
1. Create a role with limited permissions (defined below as `allow-roles`). This role allows you to see the Role screen and ssh into all nodes.
1. Create another role with limited permissions (defined below as `allow-users`). This role session expires in 4 minutes, allows you to see Users screen, and denies access to all nodes.
1. Create another role with no permissions other than being able to create requests (defined below as `default`)
1. Create a user with role `default` assigned
1. Create a few requests under this user to test pending/approved/denied state.
```
kind: role
metadata:
  name: allow-roles
spec:
  allow:
    logins:
    - root
    node_labels:
      '*': '*'
    rules:
    - resources:
      - role
      verbs:
      - list
      - read
  options:
    max_session_ttl: 8h0m0s
version: v3
```
```
kind: role
metadata:
  name: allow-users
spec:
  allow:
    rules:
    - resources:
      - user
      verbs:
      - list
      - read
  deny:
    node_labels:
      '*': '*'
  options:
    max_session_ttl: 4m0s
version: v3
```
```
kind: role
metadata:
  name: default
spec:
  allow:
    request:
      roles:
      - allow-roles
      - allow-users
      suggested_reviewers:
      - random-user-1
      - random-user-2
  options:
    max_session_ttl: 8h0m0s
version: v3
```
- [x] Verify that creating a new request works
  - [x] Verify that under requestable roles, only `allow-roles` and `allow-users` are listed
  - [x] Verify input validation requires at least one role to be selected
  - [x] Verify you can select/input/modify reviewers
- [x] Verify after creating, requests are listed in pending states

### Viewing & Approving/Denying Requests
Create a user with all admin priveldeges so you can approve/deny request (use different browser or incognito mode so you don't have to keep logging out/in)
- [x] Verify you can view access request from request list and when viewing:
  - [x] Verify there is list of reviewers you selected (empty list if none selected AND none wasn't defined in roles)
  - [x] Verify threshold name is there (it should be `default` if not defined in role)
  - [x] Verify you can approve a request with message, and immediately see updated state with your review stamp (green checkmark) and message box
  - [x] Verify you can deny a request, and immediately see updated state with your review stamp (red cross)
  - [x] Verify deleting the denied request is removed from list

### Assuming Approved Requests
- [x] Verify assume buttons are only present for approved request and for logged in user
  - [x] Verify that assuming `allow-roles` allows you to see roles screen and ssh into nodes
  - [x] Verify that after clicking on the assume button, it is disabled in both the list and in viewing
  - [x] After assuming `allow-roles`, verify that assuming `allow-users` allows you to see users screen, and denies access to nodes.
    - [x] Verify that after 4 minutes, the user is automatically logged out
- [x] Verify that after logging out (or getting logged out automatically) and relogging in, permissions are reset to `default`, and requests that are not expired and are approved are assumable again.
#### Strategy Reason
Create the following role:
```
kind: role
metadata:
  name: restrict
spec:
  allow:
    request:
      roles:
      - <some other role to assign user after approval>
  options:
    max_session_ttl: 8h0m0s
    request_access: reason
    request_prompt: <some custom prompt to show in reason dialogue>
version: v3
```
- [x] Verify after login, reason dialogue is rendered with prompt set to `request_prompt` setting
- [x] Verify after clicking `send request`, pending dialogue renders
- [x] Verify after `tctl requests approve <request-id>`, dashboard is rendered
- [x] Verify the correct role was assigned

#### Strategy Always
With the previous role you created from `Strategy Reason`, change `request_access` to `always`:
- [x] Verify after login, pending dialogue is rendered
- [x] Verify after `tctl requests approve <request-id>`, dashboard is rendered
- [x] Verify after login, `tctl requests deny <request-id>`, access denied dialogue is rendered

#### Strategy Optional
With the previous role you created from `Strategy Reason`, change `request_access` to `optional`:
- [x] Verify after login, dashboard is rendered

## Account
- [x] Verify that Account screen is accessibly from the user menu for local users.
- [x] Verify that changing a local password works (OTP, U2F)

## Terminal
- [x] Verify that top nav has a user menu (Main and Logout)
- [x] Verify that switching between tabs works on alt+[1...9]

#### Node List Tab
- [x] Verify that Cluster selector works (URL should change too)
- [x] Verify that Quick launcher input works
- [x] Verify that Quick launcher input handles input errors
- [x] Verify that "Connect" button shows a list of available logins
- [x] Verify that "Hostname", "Address" and "Labels" columns show the current values
- [x] Verify that "Search" by hostname, address, labels work
- [x] Verify that new tab is created when starting a session

#### Session Tab
- [x] Verify that session and browser tabs both show the title with login and node name
- [x] Verify that terminal resize works
    - Install midnight commander on the node you ssh into: `$ sudo apt-get install mc`
    - Run the program: `$ mc`
    - Resize the terminal to see if panels resize with it
- [x] Verify that session tab shows/updates number of participants when a new user joins the session
- [x] Verify that tab automatically closes on "$ exit" command
- [x] Verify that SCP Upload works
- [x] Verify that SCP Upload handles invalid paths and network errors
- [x] Verify that SCP Download works
- [x] Verify that SCP Download handles invalid paths and network errors

## Session Player
- [x] Verify that it can replay a session
- [x] Verify that when playing, scroller auto scrolls to bottom most content
- [x] Verify when resizing player to a small screen, scroller appears and is working
- [x] Verify that error message is displayed (enter a invalid SID in the URL)

## Invite Form
- [x] Verify that input validates
- [x] Verify that invite works with 2FA disabled
- [x] Verify that invite works with OTP enabled
- [x] Verify that invite works with U2F enabled
- [x] Verify that error message is shown if an invite is expired/invalid

## Login Form
- [x] Verify that input validates
- [x] Verify that login works with 2FA disabled
- [x] Verify that login works with OTP enabled
- [x] Verify that login works with U2F enabled
- [x] Verify that login works for Github/SAML/OIDC
- [x] Verify that account is locked after several unsuccessful attempts
- [x] Verify that redirect to original URL works after successful login

## Multi-factor Authentication (mfa)
Create/modify `teleport.yaml` and set the following authentication settings under `auth_service`
```
authentication:
  type: local
  second_factor: optional
  require_session_mfa: yes
```
#### MFA create, login, password reset
- [x] Verify when creating a user, and setting password, required 2nd factor is `totp` (TODO: temporary hack, ideally want to allow user to select)
- [x] Verify at login page, there is a mfa dropdown menu (none, u2f, otp), and can login with `otp`
- [x] Verify at reset password page, there is the same dropdown to select your mfa, and can reset with `otp`

#### MFA require auth
Through the CLI, `tsh login` and register a u2f key with `tsh mfa add` (not supported in UI yet)

- [x] Verify logging in with registered u2f key works
- [ ] Verify connecting to a ssh node prompts you to tap your registered u2f key

## RBAC
Create a role, with no `allow.rules` defined:
```
kind: role
metadata:
  name: test
spec:
  allow:
    app_labels:
      '*': '*'
    logins:
    - root
    node_labels:
      '*': '*'
  options:
    max_session_ttl: 8h0m0s
version: v3
```
- [x] Verify that a user has access only to: "Servers", "Applications", "Active Sessions" and "Manage Clusters"
- [x] Verify there is no `Add Server` button in Server view
- [x] Verify there is no `Add Application` button in Applications view
- [x] Verify only `Nodes` and `Apps` are listed under `options` button in `Manage Clusters`

Add the following under `spec.allow.rules` to enable read access to the audit log:
```
  - resources:
      - event
      verbs:
      - list
```
- [x] Verify that the `Audit Log` and `Session Recordings` is accessible
- [x] Verify that playing a recorded session is denied

Add the following to enable read access to recorded sessions
```
  - resources:
      - session
      verbs:
      - read
```
- [x] Verify that a user can re-play a session (session.end)

Add the following to enable read access to the roles

```
- resources:
      - role
      verbs:
      - list
      - read
```
- [x] Verify that a user can see the roles
- [x] Verify that a user cannot create/delete/update a role

Add the following to enable read access to the auth connectors

```
- resources:
      - auth_connector
      verbs:
      - list
      - read
```
- [x] Verify that a user can see the list of auth connectors.
- [x] Verify that a user cannot create/delete/update the connectors

Add the following to enable read access to users
```
  - resources:
      - user
      verbs:
      - list
      - read
```
- [x] Verify that a user can access the "Users" screen
- [x] Verify that a user cannot create/delete/update a user

Add the following to enable read access to trusted clusters
```
  - resources:
      - trusted_cluster
      verbs:
      - list
      - read
```
- [x] Verify that a user can access the "Trust" screen
- [x] Verify that a user cannot create/delete/update a trusted cluster.

- [x] Enterprise users has read/create access_request access, despite resource setting

## Performance/Soak Test @fspmarshall @quinqu 

Using `tsh bench` tool, perform the soak tests and benchmark tests on the following configurations:

* Cluster with 10K nodes in normal (non-IOT) node mode with ETCD
* Cluster with 10K nodes in normal (non-IOT) mode with DynamoDB

* Cluster with 1K IOT nodes with ETCD
* Cluster with 1K IOT nodes with DynamoDB

* Cluster with 500 trusted clusters with ETCD
* Cluster with 500 trusted clusters with DynamoDB

**Soak Tests** @fspmarshall @quinqu 

Run 4hour soak test with a mix of interactive/non-interactive sessions:

```
tsh bench --duration=4h user@teleport-monster-6757d7b487-x226b ls
tsh bench -i --duration=4h user@teleport-monster-6757d7b487-x226b ps uax
```

Observe prometheus metrics for goroutines, open files, RAM, CPU, Timers and make sure there are no leaks

- [ ] Verify that prometheus metrics are accurate.

**Breaking load tests** @fspmarshall @quinqu 

Load system with tsh bench to the capacity and publish maximum numbers of concurrent sessions with interactive
and non interactive tsh bench loads.

## Application Access @r0mant 

- [x] Run an application within local cluster.
  - [x] Verify the debug application `debug_app: true` works.
  - [x] Verify an application can be configured with command line flags.
  - [x] Verify an application can be configured from file configuration.
  - [x] Verify that applications are available at auto-generated addresses `name.rootProxyPublicAddr` and well as `publicAddr`.
- [x] Run an application within a trusted cluster.
  - [x] Verify that applications are available at auto-generated addresses `name.rootProxyPublicAddr`.
- [x] Verify Audit Records.
  - [x] `app.session.start` and `app.session.chunk` events are created in the Audit Log.
  - [x] `app.session.chunk` points to a 5 minute session archive with multiple `app.session.request` events inside.
  - [x] `tsh play <chunk-id>` can fetch and print a session chunk archive.
    - [x] Works with `tsh play --format=json /path/to/tar`.
- [x] Verify JWT using [verify-jwt.go](https://github.com/gravitational/teleport/blob/master/examples/jwt/verify-jwt.go).
- [x] Verify RBAC.
- [x] Verify an app with websockets (e.g. [NodeRed](https://nodered.org/docs/getting-started/docker)).
- [x] Verify application access CLI flow.
  - [x] Root cluster.
  - [x] Leaf cluster.

## Database Access @r0mant 

- [x] Connect to a database within a local cluster.
  - [x] Self-hosted Postgres.
  - [x] Self-hosted MySQL.
  - [x] AWS Aurora Postgres.
  - [x] AWS Aurora MySQL.
  - [x] GCP Cloud SQL Postgres.
- [x] Connect to a database within a remote cluster via a trusted cluster.
  - [x] Self-hosted Postgres.
  - [x] Self-hosted MySQL.
  - [x] AWS Aurora Postgres.
  - [x] AWS Aurora MySQL.
  - [x] GCP Cloud SQL Postgres.
- [x] Verify audit events.
  - [x] `db.session.start` is emitted when you connect.
  - [x] `db.session.end` is emitted when you disconnect.
  - [x] `db.session.query` is emitted when you execute a SQL query.
- [x] Verify RBAC.
  - [x] `tsh db ls` shows only databases matching role's `db_labels`.
  - [x] Can only connect as users from `db_users`.
  - [x] _(Postgres only)_ Can only connect to databases from `db_names`.
  - [x] `db.session.start` is emitted when connection attempt is denied.

**Comment by awly** [comment]
RBAC: reproduced two known issues around agent/port forwarding https://github.com/gravitational/teleport/issues/4881 and https://github.com/gravitational/teleport/issues/3222
Not a 6.1 regression.

**Comment by andrejtokarcik** [comment]
Session recording cannot be properly disabled: #6254.

**Comment by Joerger** [comment]
Relogging in to tsh has the potential to fail, due new ssh certs change along with some recent bug fixes: #6268.
Should be an easy fix. @awly

**Comment by awly** [comment]
Small problem with port forwarding using openssh client: https://github.com/gravitational/teleport/issues/3784#issuecomment-812082730
Not a release blocker.

**Comment by awly** [comment]
MFA management: https://github.com/gravitational/teleport/issues/5803 hasn't been fixed yet.
Not a release blocker.

**Comment by quinqu** [comment]
### 
Dynamo (IOT) -- scaled to 500 -> 0 -> 500 -> 0 -> 1000 -> 0 -> 1000 -> 0 -> 500

**Comment by quinqu** [comment]
### Dynamo (IOT)

#### 500 trusted clusters
![Screenshot from 2021-04-05 11-09-30](https://user-images.githubusercontent.com/42625018/113633257-77a01880-9621-11eb-8b38-2f5588dd645c.png)

#### 10k nodes
![Screenshot from 2021-04-05 12-52-39](https://user-images.githubusercontent.com/42625018/113633306-90103300-9621-11eb-8d6f-655e81934393.png)

#### Soak 
```
tsh bench -d --duration=30m ec2-user@host ls

* Requests originated: 17999
* Requests failed: 0

Histogram

Percentile Response Duration 
---------- ----------------- 
25         183 ms            
50         195 ms            
75         212 ms            
90         232 ms            
95         251 ms            
99         370 ms            
100        1949 ms  
```

```
tsh bench -d --interactive --duration=30m ec2-user@host ps uax

* Requests originated: 17999
* Requests failed: 0

Histogram

Percentile Response Duration 
---------- ----------------- 
25         188 ms            
50         205 ms            
75         219 ms            
90         236 ms            
95         254 ms            
99         364 ms            
100        2189 ms  

```

**Comment by quinqu** [comment]
### Dynamo (non-IOT)

#### 10k nodes 
![Screenshot from 2021-04-07 13-48-36](https://user-images.githubusercontent.com/42625018/113942025-0abd8780-97b5-11eb-8349-553a0fd929e8.png)

#### Soak

```
tsh bench -d --duration 30m ec2-user@host ls

* Requests originated: 17999
* Requests failed: 0

Histogram

Percentile Response Duration 
---------- ----------------- 
25         173 ms            
50         191 ms            
75         207 ms            
90         228 ms            
95         251 ms            
99         372 ms            
100        1254 ms 
```


```
tsh bench -d --interactive --duration 30m ec2-user@host ps uax

* Requests originated: 17999
* Requests failed: 0

Histogram

Percentile Response Duration 
---------- ----------------- 
25         182 ms            
50         198 ms            
75         216 ms            
90         236 ms            
95         258 ms            
99         376 ms            
100        1266 ms   
```

**Comment by fspmarshall** [comment]
### ETCD (IoT)

#### 10k nodes

![10k-etcd-iot](https://user-images.githubusercontent.com/30576607/114069291-b0273880-9853-11eb-8f51-96cc1a5a7ffa.png)

#### Soak

```
tsh bench --duration=30m root@loadtest-6f7dbd6b5d-xx7p8 ls

* Requests originated: 17930
* Requests failed: 0

Histogram

Percentile Response Duration 
---------- ----------------- 
25         2030 ms           
50         3281 ms           
75         5847 ms           
90         7891 ms           
95         8911 ms           
99         12295 ms          
100        25823 ms
```

```
tsh bench --interactive --duration=30m root@loadtest-6f7dbd6b5d-b9s79 ps aux

* Requests originated: 17980
* Requests failed: 0

Histogram

Percentile Response Duration 
---------- ----------------- 
25         2097 ms           
50         3915 ms           
75         6663 ms           
90         8943 ms           
95         10807 ms          
99         17487 ms          
100        58943 ms
```

**Comment by fspmarshall** [comment]
### ETCD (non-IoT)

#### 10k nodes

![10k-etcd](https://user-images.githubusercontent.com/30576607/114069966-6723b400-9854-11eb-96b7-24ce1eb6e659.png)

### Soak

```
tsh bench --duration=30m root@loadtest-6f7dbd6b5d-h8627 ls

* Requests originated: 17948
* Requests failed: 1
* Last error: failed to authenticate with proxy monster.gravitational.co:3023: ssh: handshake failed: EOF

Histogram

Percentile Response Duration 
---------- ----------------- 
25         2449 ms           
50         4327 ms           
75         6711 ms           
90         8615 ms           
95         10063 ms          
99         15655 ms          
100        40863 ms
```

```
tsh bench --interactive --duration=30m root@loadtest-6f7dbd6b5d-cqcj5 ps aux

* Requests originated: 17945
* Requests failed: 0

Histogram

Percentile Response Duration 
---------- ----------------- 
25         2451 ms           
50         4363 ms           
75         6739 ms           
90         8663 ms           
95         10215 ms          
99         16767 ms          
100        57503 ms
```

**Comment by andrejtokarcik** [comment]
Session recordings done with `session_recording: proxy` have empty "Node" value in the web UI list. Not a 6.1 regression: #3906.

**Comment by fspmarshall** [comment]
#### 500 Trusted Clusters (etcd)

![500-tc-etcd](https://user-images.githubusercontent.com/30576607/114218755-af0f0d80-991e-11eb-88da-77e681a17605.png)

#### Notes

- A significant amount of proxy memory is held onto while the `remote_cluster` resources continue to exist.  Manually deleting them returns memory usage (nearly) pre-scale levels.  This is a known issue and not a blocker for 6.1 release.
