### ISSUE TITLE
CLI node filtering using tctl

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#6196]
### What
Currently you can leverage `tsh ls <key>=<value>` to return filtered results in the CLI but you cannot do this with `tctl nodes ls <key>=<value>`.  

It would be nice to be able to filter nodes in the CLI using TCTL if you're an admin user.

### How
Add ability to allow certain users based on RBAC to leverage `tctl` to filter and display nodes based on key/value pairs/labels.

### Why
CLI improvements for Admins that utilize `tctl` all the time instead of bouncing between `tsh` and `tctl`

### Workaround
Right now you can use `tsh` to do this. See issue #3860

**Comment by zmb3** [comment]
Closing this, as `tsh` and `tctl` now support the same search options.
