### ISSUE TITLE
Errors after switching between "On-Demand" and "Provisioned" DynamoDB Capacity

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#6201]
### Description

**What happened**:
After switching between `on-demand` and `provisioned` mode on the dynamo db cluster state table, the following errors begin showing up periodically in both auth servers:

~~~
DEBU [DYNAMODB]  Shard ID  closed with error: ExpiredIteratorException: Shard iterator has expired, reseting buffers. dynamo/shards.go:115
ERRO [DYNAMODB]  Poll streams returned with error: ExpiredIteratorException: Shard iterator has expired. dynamo/shards.go:61
~~~

No noted functionality issues with the cluster except the error logging.

**What you expected to happen**:
Switching between capacity modes in DynamoDB backend for cluster state will not cause errors.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a Teleport cluster using a DynamoDB backend with the HA terraform example.  I also added a single node and some trusted cluster relationships to generate some activity.
2. In the AWS console, go to the cluster state table and change the mode from 'Provisioned' to 'On-demand' and back again with the same values under the 'Capacity' tab
3. Observe the logs of the auth server (the messages should start occurring periodically every ~15-20 minutes)

### Server Details
- Teleport version (run `teleport version`): Teleport Enterprise v5.1.2
- Server OS (e.g. from `/etc/os-release`): AWS Linux
- Where are you running Teleport? AWS

**Comment by yjperez** [comment]
We discovered in the events table, if provisioned mode was enabled and some upgraded from 5.x to 6.x they would see below errors:

```
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/events/dynamoevents/dynamoevents.go:983 github.com/gravitational/teleport/lib/events/dynamoevents.(*Log).createV2GSI
        /go/src/github.com/gravitational/teleport/lib/events/dynamoevents/dynamoevents.go:390 github.com/gravitational/teleport/lib/events/dynamoevents.(*Log).migrateRFD24.func1
        /go/src/github.com/gravitational/teleport/lib/backend/helpers.go:146 github.com/gravitational/teleport/lib/backend.RunWhileLocked
        /go/src/github.com/gravitational/teleport/lib/events/dynamoevents/dynamoevents.go:389 github.com/gravitational/teleport/lib/events/dynamoevents.(*Log).migrateRFD24
        /go/src/github.com/gravitational/teleport/lib/events/dynamoevents/dynamoevents.go:343 github.com/gravitational/teleport/lib/events/dynamoevents.(*Log).migrateRFD24WithRetry
        /opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit
User Message: ValidationException: One or more parameter values were invalid: Neither ReadCapacityUnits nor WriteCapacityUnits can be specified for index: timesearchV2 when BillingMode is PAY_PER_REQUEST
        status code: 400, request id: ND9LL9IUAEE2OEL3MLKLU12K3FVV4KQNSO5AEMVJF66Q9ASUAAJG] dynamoevents/dynamoevents.go:350
```

Additionally, Audit Logs and Session Recordings are not accessible via the UI.
