### ISSUE TITLE
Teleport fails to build on both master branch and release 6.0.2

### ISSUE THREAD

**Issue by scardracs** [gravitational/teleport#6227]
### Description

**What happened**:
The make full command fails to work

**What you expected to happen**:
Compile the full code

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
Reproduction: always
1. Clone the teleport git
2. Run make full inside teleport directory
3. Teleport fails to build

Build log: actually "e" and "webassets" are completely empty

mkdir -p lib/web/build
---> Building OSS web assets.
cd webassets/teleport/ ; zip -qr ../../lib/web/build/webassets.zip .
/bin/sh: riga 1: cd: webassets/teleport/: No such file or directory
zip I/O error: No such file or directory
zip error: Could not create output file (../../lib/web/build/webassets.zip)
make: *** [Makefile:381: lib/web/build/webassets.zip] Errore 15

Latest known working version: teleport 4.1.4

**Comment by scardracs** [comment]
I have also noticed that e doesn't exist at all https://github.com/gravitational/teleport.e/tree/db06d98a9f921585c9ebee988d4448c520afe5cf

**Comment by webvictim** [comment]
`e` is an Enterprise-only submodule and is not expected to be populated unless you have access to that repo.

#6231 will fix the `make full` issue. Thanks for reporting.

**Comment by scardracs** [comment]
Thanks, I will wait for it :)
