### ISSUE TITLE
Allow displaying a different label for a provider

### ISSUE THREAD

**Issue by tehsis** [gravitational/teleport#623]
I want to be able to use Teleport with a different user provider than Google (auth0 in this case)

The current implementation actually allows this but it will show "using google" in the UI.

My proposal is to add a field to oidc configuration that allows to set this label to a friendly name for the connection (and use the id to identify it)

I have created the PR #617 with a proposed implementation of this scenario which also supports multiple oidc providers in the UI.

**Comment by klizhentas** [comment]
this proposal and PR looks good to me, I will wait for the review of our UI team and we will merge your PR

**Comment by tehsis** [comment]
Closing since the PR got merged. Thanks!
