### ISSUE TITLE
Display Teleport version in Web UI

### ISSUE THREAD

**Issue by mpitt** [gravitational/teleport#6244]
### What
I would like to see the running Teleport version in the Web UI.

### How
Display the version somewhere in small text (e.g. at the bottom of the sidebar?)

### Why
To verify what version of Teleport is currently running on my proxy.

**Comment by stevenGravy** [comment]
@mpitt you can see the version by selecting the user name in the upper right, then help and support

![image](https://user-images.githubusercontent.com/60704961/113147403-bcc9e200-91fe-11eb-865b-0347f54e946a.png)

![image](https://user-images.githubusercontent.com/60704961/113147458-ca7f6780-91fe-11eb-81cd-42b1170c3aff.png)

**Comment by mpitt** [comment]
Right, it is there, thanks @stevenGravy !

I remain of the opinion that cluster info should be more visible/discoverable, though. But feel free to close this, I have what I need.
