### ISSUE TITLE
Support GRPC connect/call options in teleport/api

### ISSUE THREAD

**Issue by marshall-lee** [gravitational/teleport#6276]
### What

In `teleport/api` package need to support `WaitForReady(true)` call option and `grpc.ConnectParams{Backoff: ...}` dial option.

### How

Don't have a strong opinion on API design but perhaps:

- Connect params: move to client config.
- Call options: allow to optionally pass grpc call options per method like it does the `grpc` library itself.

### Why

In https://github.com/gravitational/teleport-plugins we struggle to completely switch to `teleport/api` package. Generally it already fits really well but there're some quirks.

One of the things is that our events watcher (calling `WatchEvents`) uses `WaitForReady(true)` call option. This option makes us leverage a built-in exponential backoff mechanism for free. I know that `WaitForReady` is kinda problematic but in a case of events watcher it fits really well.

The code where we use `WaitForReady`: https://github.com/gravitational/teleport-plugins/blob/master/access/service_job.go#L24

### Workaround

We could write an exponential backoff from scratch but why we do this since `grpc` library already has backoff mechanism internally.

**Comment by Joerger** [comment]
I believe this is one of the main things I'll be working on for 7.0, Moving the access plugin code to `teleport/api/cllient/workflows` and using the new api client - #5465. I'll definitely keep this in mind and make sure to keep this functionality in place. 

Is there a reason that the new API client needs to be used in teleport-plugins right now rather than the custom gRPC client used now?  https://github.com/gravitational/teleport-plugins/blob/361d3c01bc764b5c2e6e52ea5dba648a6f5eeada/access/access.go#L154-L161

**Comment by marshall-lee** [comment]
@Joerger 

Hmm I believe all the things that `access` package can do are already present in `teleport/api/client`.

There're all necessary operations for `AccessRequest` resource https://github.com/gravitational/teleport/blob/854da4899049f754b81a23eb9272ba635533e1e8/api/client/client.go#L591-L604 and there's an event watcher https://github.com/gravitational/teleport/blob/740d184d1cfc69ae2e96c50ee738b13884fb232b/api/client/streamwatcher.go#L31-L50.

So I really doubt that additional `workflows` subpackage is necessary at all.

> Is there a reason that the new API client needs to be used in teleport-plugins right now rather than the custom gRPC client used now?

It's not urgent at all to migrate teleport-plugins to new `teleport/api/client` but I had already made a try and everything is fine except a couple of little problems and this issue is one of them.

**Comment by klizhentas** [comment]
@Joerger @marshall-lee I would like all plugins to switch to new client before the 6.1 release or shortly after the release. Can you please add missing parameter so @marshall-lee can switch the usage?

**Comment by Joerger** [comment]
@klizhentas Understood, everything should be fixed (merged by EOD). Do we still plan on [moving workflows](https://github.com/gravitational/teleport/blob/33b5c33ea2b593b2bba0e5b66e08d607d582f964/rfd/0010-api.md#move-access-requests-code-into-client) to `api/client/workflows`?
