### ISSUE TITLE
Teleport AMI for AWS region eu-north-1

### ISSUE THREAD

**Issue by Roiki11** [gravitational/teleport#6277]
### What
Please publish your amis in the Stockholm region. They're currently not available and copying returns a permission error.

### Why
I run my aws infra(both personal and work) mainly on eu-north-1 and it would be nice to have the official amis available for use in the same region.

**Comment by webvictim** [comment]
I'm going to backport this fix to `branch/v6` so that we will have AMIs available in the `eu-north-1` region (plus others) when Teleport 6.2 is released.

**Comment by webvictim** [comment]
As of Teleport 6.2, AMIs are available in this [list of regions](https://github.com/gravitational/teleport/blob/branch/v6.2/assets/aws/Makefile#L29):

```
eu-north-1
ap-south-1
eu-west-1
eu-west-2
eu-west-3
ap-northeast-1
ap-northeast-2
ap-northeast-3
sa-east-1
ca-central-1
ap-southeast-1
ap-southeast-2
eu-central-1
us-east-1
us-east-2
us-west-1
us-west-2
```
