### ISSUE TITLE
YubiKey 4 not working with new mfa feature.

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#6278]
### Description

**What happened**:

While testing, I was able to add both YubiKey 4 and a YubiKey 5 NFC, but I can't login with Yubikey 4.

```
Name    Type Added at                      Last used
------- ---- ----------------------------- -----------------------------
otp     TOTP Wed, 31 Mar 2021 16:22:37 UTC Thu, 01 Apr 2021 16:25:41 UTC
yubi    U2F  Thu, 01 Apr 2021 16:01:47 UTC Thu, 01 Apr 2021 16:01:47 UTC
bentest U2F  Thu, 01 Apr 2021 16:25:51 UTC Thu, 01 Apr 2021 16:26:01 UTC
```
![image](https://user-images.githubusercontent.com/559288/113325073-c15ccc00-92cc-11eb-8ce3-954fa18843f1.png)

**Comment by awly** [comment]
The issue here was that `app_id` changed in the `auth_service` U2F config.
Changing the `app_id` effectively un-registers all the keys.

I'll include a warning in the docs as a short-term solution.
