### ISSUE TITLE
u2f: derive app_id and facets from proxy's public_addr

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#6279]
### What

The `u2f` section of the `auth_service` config generated automatically based on the `public_addr` of the proxy.

### How

There are 2 fields: `app_id` and `facets`.
`app_id` can be some canonical form of the `proxy_service.public_addr` - always using `https://` prefix and port suffix.
`facets` can contain various permutations of the `public_addr`, like with/without `https://` prefix, with/without the port, with port 443 in proxy is behind an LB and with the default 3080 port.

Note that the `u2f` field should still be available, in case users want to do something custom.

### Why

The `u2f` config is finicky and requires understanding of the U2F protocol to get right.
Most users will just keep tweaking it until some combination works, without understanding why.

For most use cases, the derived values described above will be correct and will make MFA setup much easier.

### Workaround

Configure everything by hand.

**Comment by zmb3** [comment]
Closing, as we've deprecated u2f in favor of webauthn.
