### ISSUE TITLE
Postgres clients can send GSSEncRequest as a startup message instead of SSLRequest

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#6284]
### Description

**What happened**:

Under some circumstances, which are still unclear, Postgres clients (psql or pgAdmin for example), send a different initial handshake message than we expect. We expect the first message to be `SSLRequest` which indicates the start of TLS connection, but sometimes the first message is `GSSENCRequest`. This manifests into the error similar to this on the client side:

```
psql: error: could not connect to server: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

And corresponding logs on the server:

```
Apr 01 16:14:44 ip-172-31-25-182 teleport[723468]: WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *trace.BadParameterError multiplexer failed to detect connection protocol, first few bytes were: []byte{0x0, 0x0, 0x0, 0x8, 0x4, 0xd2, 0x16, 0x30}\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:396 github.com/gravitational/teleport/lib/multiplexer.detectProto\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:285 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:206 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit\nUser Message: multiplexer failed to detect connection protocol, first few bytes were: []byte{0x0, 0x0, 0x0, 0x8, 0x4, 0xd2, 0x16, 0x30}" multiplexer/multiplexer.go:209
```

The unexpected message here is the encoded `GSSENCRequest` (see https://www.postgresql.org/docs/12/protocol-message-formats.html), the `SSLRequest` we expect is slightly different:

```
➜  src go run pgproto.go
SSLRequest:	[]byte{0x0, 0x0, 0x0, 0x8, 0x4, 0xd2, 0x16, 0x2f}
GSSEncRequest:	[]byte{0x0, 0x0, 0x0, 0x8, 0x4, 0xd2, 0x16, 0x30}
```

**What you expected to happen**:

We should reply with `N` to GSSEncRequest messages to indicate that server doesn't support it and have client gracefully fallback to TLS. Also, add the following line to each service configuration in ~/.pg_service.conf file we generate to disable GSS encryption explicitly:

```
gssencmode=disable
```

**Workaround**

Until the issue is fixed, manually updating pg_service.conf file to add the line shown above fixes the issue.

**Comment by stevenGravy** [comment]
For pgAdmin you can set this env variable that will turn off prior to starting the desktop client. 

```bash
export PGGSSENCMODE=disable
```

**Comment by ericnelson** [comment]
We have quite a few pgAdmin users in our org, I think at least for Mac users the least annoying workaround is the following 
This seems to have been introduced in pgAdmin 4 v6.5. pgAdmin 4 v5.7 does not exhibit the issue

1. Create a config_local.py in /Users/eric/Desktop/pgAdmin 4 v6.5.app/Contents/Resources/web ( modify for your specific version)

**Comment by liath** [comment]
Here's a little one-liner to make sure all the services in `~/.pg_service.conf` have `gssEncMode=disabled`
```shell
perl -i -p -e 's/^gssencmode.*\n//;s/^(\[.*\]\n)/\1gssencmode=disable\n/' ~/.pg_service.conf
```
