### ISSUE TITLE
"remote error: tls: bad certificate" when connecting service through tunnel

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#6291]
### Description

**What happened**:

While going through the test plan, I was working on the scenario with connecting an application server to the cluster, and noticed the following error in the proxy logs printed over and over as soon as app server comes online:

```
ERRO [PROXY:SER] "proxy2021/04/01 15:42:46 http: TLS handshake error from 127.0.0.1:59409: remote error: tls: bad certificate\n" utils/cli.go:304
ERRO [PROXY:SER] "proxy2021/04/01 15:42:46 http: TLS handshake error from 127.0.0.1:59410: remote error: tls: bad certificate\n" utils/cli.go:304
```

The same error appears in proxy logs when connecting SSH node in IoT mode (over reverse tunnel) as well, and I presume that would be also true for database and K8s services as well. No errors are visible in the app server process logs.

After some investigations I think I tracked it down to dialing to the auth server through the tunnel:

https://github.com/gravitational/teleport/blob/branch/v6.0/lib/service/connect.go#L876

This code was updated in 6.0 to use the new API client which also does gRPC dial now. My theory is that since grpc.Dial is non-blocking by default, it keeps failing and retrying in the background producing this error on the proxy side. "remote error: tls: bad certificate" indicates that the connecting client can't validate the server's certificate which I think can be related to the fact that ServerName is set to the encoded cluster name (`xxx.teleport.cluster.local`) while the certificate presented by the proxy obviously doesn't have it among its SANs.

This error only appears in 6.0, it's not present in 5.0. Also, it's not clear what its implications are, everything seems to be working normally so it might be just a harmless side-effect leading to grpc client being effectively not connected when we're dialing internally, but we should fix it anyway.

**What you expected to happen**:

Not see the error in the logs.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Start auth/proxy process.
2. Start app server process (or SSH server connecting over reverse tunnel).
3. Observe the error in the proxy logs.

### Server Details
- Teleport version (run `teleport version`): 6.0 and later

**Comment by Joerger** [comment]
@r0mant The bug occurs whether or not the gRPC connection is dialed in the background so that doesn't seem to be related. 

Interestingly, if you add `defer func() { c.grpc() }()` to the top of `NewTLSClient` in `v5.0`, the same error gets logged, so it must be caused by the grpc connection. The only relevant difference here between 5.0 and 6.0 here is that 6.0+ doesn't lazily dial grp, so every client will have a grpc conenction.

Can you help me understand what you mean about the ServerName? I have a feeling this is the source of the issue since we have `teleport.cluster.local` hardcoded into the grpc dialer.

**Comment by r0mant** [comment]
@Joerger Yeah, that's what I basically meant. I dumped the TLS connection state on the proxy side and it showed ServerName set to something like `664928.teleport.cluster.local` which is the result of `EncodeClusterName()` which we put into ServerName everywhere in the TLS configs, but the actual host we're connecting to in reverse tunnel mode is the proxy web address (i.e. `root.gravitational.io:3080` in my case) so my theory was that that it's failing the certificate server name validation and thus logs this error. It basically seems like we never have a working grpc client in the API client but like you noted it likely went unnoticed until now because we don't actually use it anywhere?
