### ISSUE TITLE
Provide encryption option for Sessions

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#6311]
### What
Encrypt sessions via  a local method such as kms or other encryption techniques specified in auth server.  

### How
Provide a method of specifying encryption so sessions could be encrypted and decrypted within Teleport. 

### Why
Sessions may contain sensitive information and some clients do not want to rely on S3 or directory encryption alone.

**Comment by russjones** [comment]
```
Allow for option to encrypt Sessions prior to uploading to storage via local method with ClientApplicationKeptKey. Option 2 from AWS documentation 
https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingClientSideEncryption.html
```

**Comment by russjones** [comment]
This has been backported #9262, will close item in Queue after it's been released.
