### ISSUE TITLE
tsh --cluster works in Telekube but not in OSS teleport

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#634]
I noticed the difference between how OSS Teleport works vs its proprietary "Telekube edition" when `--cluster` flag is used.

In Telekube, if you're logged in you can do:

```
$ tsh --cluster=XXX ls
```

And you will see hosts in cluster XXX, but in OSS teleport I get "ssh subsystem failed".

**Comment by klizhentas** [comment]
@kontsevoy that's because `tele` sets the proper user in the profile as well, while `tsh login` apparently not.

**Comment by kontsevoy** [comment]
I tried passing `--user` to `tsh ls` too. I'll show you on Monday.
