### ISSUE TITLE
Docs structure update

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6391]
## Description

I'm working on the next iteration of the documentation structure refactor.
Here is a new structure:

* [x] Home (Renamed from documentation)
  * [x] Introduction
     * [x] Introduction becomes shorter and gets tiles pointing to products and popular use-cases links
  * [x] Adopters
  * [x] Getting Started
  * [x] FAQ
  * [x] Changelog
* [x] Setup (renamed from infrastructure guides)
   * [x] Configuration (ported from admin manual)
     * [x] Admin manual subsections split
   * [x] Terraform (moved from infrastructure guides)
   * [x] Helm (New section Gus is working on it)
     * [x] EKS
     * [x] AWS etc
* [x] Reference
  * [x] Client libraries
    * [x] Golang (A simple page with almost no content and a link to pkg.go.dev done by Brian)
  * [x] Glossary (moved from admin guide)
  * [x] Full config (moved from admin guide)
* [x] Server access (New section).
  * [x] Introduction (New)
  * [x] Getting Started (moved from user guide)
  * [x] Guides
    * [x] SSH 
    * [x] PAM (moved from other section)
    * [x] OpenSSH (moved from other sections)
* [x] Kubernetes Access
  * [x] Introduction (moved from Home)
* [x] Database Access
  * [x] Introduction (moved from Home)
* [x] Application Access
  * [x] Introduction (moved from Home)
* [x] Enterprise
* [x] Cloud
* [x] Access Controls
   * [x] Guides
      * [ ] Access requests (new guide)
   * [x] SSO (moved from Enterprise)
      * [x] Github (OSS)
      * [x] Okta
      * [x] OneLogin
      * [x] Azure AD
      * [x] ADFS
* [ ] Architecture
  * [ ] Security (new section)

## New structure explained

* Home becomes the landing section for everyone, so it has to be short
* Introduction will become shorter and will include a "lauchpad" to most popular sections and products
* Server access becomes a new product
* Advanced features has to be really removed, because it's all about SSH and will be merged into Server access
* Duplicate Kubernetes Access entries in Home and Tiles are confusing, the experiment did not work, have to move it to intros.
* SSO becomes more visible
* Separate Setup section (Similar to Giltab, Istio, Kubernetes docs). Setup has to be higher because once people have learned teleport, they will just mostly live there and in reference.
* Security section gets added to architecture.
* Admin guide gets split into parts of server access, and reference

**Comment by klizhentas** [comment]
@webvictim @benarent @r0mant @stevenGravy JFYI. I am working on the next refactor wave of docs and it will be helpful for you to review and be aware what's about to change in the coming weeks. Please ask me questions!

**Comment by benarent** [comment]
I think this a good start and foundation for the docs. 

I double checked out search analytics, and we currently have these 10 terms as most searched.  Will role and RBAC go into 'Access Controls`, Docker is another search, which is currently hidden. Should we bubble up this content in Step? 

  | Query | Count | CTR | CVR | Click Pos. | % Total Searches
-- | -- | -- | -- | -- | -- | --
1 | role | 62 | 0.00% | 0.00% | 0 | 1.40%
2 | rbac | 56 | 0.00% | 0.00% | 0 | 1.26%
3 | sso | 41 | 0.00% | 0.00% | 0 | 0.92%
4 | github | 40 | 0.00% | 0.00% | 0 | 0.90%
5 | roles | 39 | 0.00% | 0.00% | 0 | 0.88%
6 | ssh | 38 | 0.00% | 0.00% | 0 | 0.86%
7 | docker | 37 | 0.00% | 0.00% | 0 | 0.83%
8 | saml | 32 | 0.00% | 0.00% | 0 | 0.72%
9 | openssh | 32 | 0.00% | 0.00% | 0 | 0.72%
10 | ansible | 31 | 0.00% | 0.00% | 0 | 0.70%

**Comment by awly** [comment]
@klizhentas 
- which section describes how to install teleport binaries (tarballs/debs/rpms)?
- we have https://goteleport.com/docs/cli-docs/ right now, is that getting removed?
  - I think we _should_ remove it and improve `--help` output as needed
- same question for https://goteleport.com/docs/metrics-logs-reference/

**Comment by klizhentas** [comment]
@inertial-frame let's start with Server access section.

**Comment by inertial-frame** [comment]
@klizhentas - Sounds great - I'll begin reviewing these items tonight. 

FYI - the changelog was also updated and backported from 7.0 but we may need to do this again as we reached the 6.2 deadline to pick up any other changes made since.

**Comment by inertial-frame** [comment]
Will also verify some of the redirects and broken links: https://github.com/gravitational/teleport/issues/6896

Also will complete the 6.2 edit pass once all content is finalized.

**Comment by inertial-frame** [comment]
https://github.com/gravitational/teleport/pull/7043 addresses the new SSH document along with some of the Admin Guide refactor.

**Comment by ptgott** [comment]
Closing because we have this structure in place now.
