### ISSUE TITLE
U2F UX issues

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#640]
## Description

Here's a list of UI/UX issues I've encountered while using U2F:

* When U2F error happens on the client, we see:

```
U2F Error: BAD_REQUEST
```
Error message. We should convert it to more human readable format.

* Improve U2F information messages

When signing up or using u2f it's not clear that you have to press the button even following the instructions.

* Too Many buttons

Now it's too many various login buttons everywhere. Rethink sign-in flow a bit especially when using U2F.

**Comment by marchofreason** [comment]
Yeah I have this problem as well - In fact I can't even get U2F to work with Teleport for sign-in
Created a new user and when signing up and selecting U2F it just says BAD_REQUEST

Have tried using two different Yubikeys but no matter the order can't complete the sign up process...

**Comment by marchofreason** [comment]
@klizhentas Sorry didn't mention this but yes I did try this with Google Chrome. Need me to send you any logs / developer console output?

Using the latest release from the binaries here: 
[v1.3.1](https://github.com/gravitational/teleport/releases/download/v1.3.1/teleport-v1.3.1-linux-amd64-bin.tar.gz)

**Comment by klizhentas** [comment]
@marchofreason can you send me your teleport config with U2F section. Just make sure to remove all secrets there. What's the domain name address you are accessing it from?

**Comment by marchofreason** [comment]
@klizhentas I'm sorry the issue seems to have been that I had the configuration wrong. Auth and proxy server were the same so all I did was set U2F to enabled. Nothing further. 

All working fine now!

**Comment by klizhentas** [comment]
@marchofreason awesome, glad to hear that

**Comment by kontsevoy** [comment]
@klizhentas what are we doing with this one?

**Comment by klizhentas** [comment]
@kontsevoy Ideally @alex-kovoy will handle the error on the UI and show something like:

```
Please check your U2F token settings, make sure it is plugged in and you are using supported browser
```

**Comment by klizhentas** [comment]
and then we can close this.
