### ISSUE TITLE
Process callback error given when user doesn't have a matching role in Teleport

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#6409]
### Description

**What happened**:

Users get the generic message unable to process callback when their traits don't match to roles.  This can create the impression that something is wrong with Teleport when it's typically the configuration.

![image](https://user-images.githubusercontent.com/60704961/114427630-45df0280-9b89-11eb-93b5-187a5b7e3d8e.png)

**What you expected to happen**:

Teleport in most cases has processed the callback but there is not a matching role. This message could be given that would give the user the context that they did authenticate with their SSO but they do not have a matching role in Teleport configured.  that's different then when an actual callback error occurs that there is no connectivity or other technical issue.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Configure a Github or other SSO connector.  
2. Log in with a user that has a team or group that doesn't match to a available Teleport role
3.The error message will show.

### Server Details
- Teleport version (run `teleport version`): 6.1.0
- Server OS (e.g. from `/etc/os-release`): ubuntu

**Comment by yjperez** [comment]
Additionally, the same callback error is given when a user is locked. It would be nice if the logic can be modified to display a more custom message.

**Comment by russjones** [comment]
@atburke Let's use this error message `You are not authorized, please contact your SSO administrator.`.

**Comment by stevenGravy** [comment]
We now have troubleshooting now in guides.  We can make a common troubleshooting page that lists things to check. 

https://goteleport.com/docs/enterprise/sso/azuread/#troubleshooting
