### ISSUE TITLE
Gravity installation fails at post-install-hook

### ISSUE THREAD

**Issue by pachalk** [gravitational/teleport#6410]
Please check the below logs and let me know the reason why it is failing

Pod "gravity-install-5afffe-hjw7f" in namespace "kube-system", has changed state from "Running" to "Succeeded".
Container "gravity-install" changed status from "running" to "terminated, exit code 0".

Sat Apr 10 16:19:36 UTC [INFO] [gravity-01] Executing postInstall hook for site:7.0.12.
Created Pod "site-app-post-install-dcc7f6-dn8nq" in namespace "kube-system".

Container "post-install-hook" created, current state is "waiting, reason PodInitializing".

Pod "site-app-post-install-dcc7f6-dn8nq" in namespace "kube-system", has changed state from "Pending" to "Running".
Container "post-install-hook" changed status from "waiting, reason PodInitializing" to "running".

[ERROR]: failed connecting to https://gravity-site.kube-system.svc.cluster.local:3009/healthz
	Get https://gravity-site.kube-system.svc.cluster.local:3009/healthz: dial tcp 100.100.244.216:3009: connect: connection refused
Container "post-install-hook" changed status from "running" to "terminated, exit code 255".

Container "post-install-hook" restarted, current state is "running".

[ERROR]: failed connecting to https://gravity-site.kube-system.svc.cluster.local:3009/healthz
	Get https://gravity-site.kube-system.svc.cluster.local:3009/healthz: dial tcp 100.100.244.216:3009: connect: connection refused
Container "post-install-hook" changed status from "running" to "terminated, exit code 255".

Container "post-install-hook" changed status from "terminated, exit code 255" to "waiting, reason CrashLoopBackOff".

Container "post-install-hook" restarted, current state is "running".

[ERROR]: failed connecting to https://gravity-site.kube-system.svc.cluster.local:3009/healthz
	Get https://gravity-site.kube-system.svc.cluster.local:3009/healthz: dial tcp 100.100.244.216:3009: connect: connection refused
Container "post-install-hook" changed status from "running" to "terminated, exit code 255".

Container "post-install-hook" changed status from "terminated, exit code 255" to "waiting, reason CrashLoopBackOff".

Pod "site-app-post-install-dcc7f6-dn8nq" in namespace "kube-system", has changed state from "Running" to "Succeeded".
Container "post-install-hook" restarted, current state is "terminated, exit code 0".

<unknown> has completed, 58 seconds elapsed.
Sat Apr 10 16:20:34 UTC [DEBUG] [gravity-01] Application gravitational.io/site:7.0.12 does not have status hook.
Sat Apr 10 16:20:35 UTC [INFO] [gravity-01] Executing phase: /runtime/kubernetes.
Sat Apr 10 16:20:35 UTC [DEBUG] [gravity-01] Application gravitational.io/kubernetes:7.0.12 does not have install hook.
Sat Apr 10 16:20:35 UTC [DEBUG] [gravity-01] Application gravitational.io/kubernetes:7.0.12 does not have postInstall hook.
Sat Apr 10 16:20:35 UTC [DEBUG] [gravity-01] Application gravitational.io/kubernetes:7.0.12 does not have status hook.
Created Pod "install-89f805-shxct" in namespace "kube-system".

Container "install" created, current state is "waiting, reason PodInitializing".

Sat Apr 10 16:20:36 UTC [INFO] [gravity-01] Executing phase: /app/application.
Sat Apr 10 16:20:36 UTC [INFO] [gravity-01] Executing install hook for application:0.2.2.
Pod "install-89f805-shxct" in namespace "kube-system", has changed state from "Pending" to "Running".
Container "install" changed status from "waiting, reason PodInitializing" to "running".

namespace/ingress-nginx created
namespace/metallb-system created
clusterrole.rbac.authorization.k8s.io/use-privileged-psp created
clusterrolebinding.rbac.authorization.k8s.io/privileged-role-bind created
podsecuritypolicy.extensions/privileged-new created
role.rbac.authorization.k8s.io/ingress-nginx.psp-role created
rolebinding.rbac.authorization.k8s.io/ingress-nginx.psp-rolebinding created

Sat Apr 10 16:53:56 UTC [ERROR] [gravity-01] Phase execution failed: gravitational.io/application:0.2.2 install hook failed
	Job was active longer than specified deadline.

**Comment by stevenGravy** [comment]
hi @pachalk this is the Teleport repository.  please use the Gravity repository.

**Comment by pachalk** [comment]
Thank you @stevenGravy posted in Gravity repo.
