### ISSUE TITLE
AWS Terraform scripts put license_file parameter in wrong configuration section for latest code

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#6411]
### Description

**What happened**:
After deploying a Teleport cluster using the example AWS starter cluster example, the configuration file produced put the `license_file` parameter under the global section.  This produces the following error upon starting on the latest software:

`Mar 22 17:03:51 Leaf-Cluster1-Node1-US-West teleport[2423]: ERRO             Teleport configuration is invalid: yaml: unmarshal errors:  line 11: field license_file not found in type config.Global. config/fileconf.go:316
Mar 22 17:03:51 Leaf-Cluster1-Node1-US-West teleport[2423]: ERRO             This error will be enforced in the next Teleport release. config/fileconf.go:317`

The Teleport documentation references the `license_file` parameter being under the `auth_service` configuration.  Moving the `license_file` parameter under the `auth_service` element in the /etc/teleport.yaml and restarting eliminated the errors.

**What you expected to happen**:
Our Terraform example will place the 'license_file' parameter under the appropriate configuration element in /etc/teleport.yaml config upon deployment.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Deploy a new cluster using the example at teleport/examples/aws/terraform/starter-cluster

### Server Details
- Teleport version (run `teleport version`): 6.1.0
- Server OS (e.g. from `/etc/os-release`): Amazon Linux
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by webvictim** [comment]
Good spot! Fixed by #6420
