### ISSUE TITLE
teleport binary is dynamically linked (instead of static)

### ISSUE THREAD

**Issue by jeremyd** [gravitational/teleport#642]
I noticed the release is dynamically linked to /lib64/ld-linux-x86-64.so.2  which means that it won't run on Alpine linux.  Is it possible to change the build to statically linked binaries?

I'm trying some tricks now with my build using tips from: http://matthewkwilliams.com/index.php/2014/09/28/go-executables-are-statically-linked-except-when-they-are-not/

**Comment by jeremyd** [comment]
I modified my build to use this command:

go build -o build/teleport -i -tags dynamodb -ldflags '-w -s -extldflags "-static"' ./tool/t
eleport

file says 
```
file teleport
teleport: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped
```

Which still seems dynamically linked .. but it does run now on alpine + debian.  I noticed it doesn't mention ld-linux.so.2 anymore..

**Comment by jeremyd** [comment]
I'm attempting to compile with static link and I'm hitting an error in the code here:

```
go build -o build/teleport -i -tags dynamodb -ldflags '-w -s' ./tool/teleport
# github.com/gravitational/teleport/lib/srv
lib/srv/exec.go:209: osUser.GroupIds undefined (type *user.User has no field or method GroupIds)
```

**Comment by jeremyd** [comment]
I found a command that works to compile it statically from inside the container created by build.assets/Dockerfile .  I understand that there may be reasons why you can't distribute a statically linked binary against glibc, perhaps in the future I can get a build working that is compiled against musl instead.

```
go build -o build/teleport -i -tags dynamodb -ldflags '-w -s -linkmode external -extldflags "-static"' ./tool/teleport
```

**Comment by jeremyd** [comment]
I created some stuff to help out with dynamodb builds / static builds.  I pushed up a PR here, let me know if you'd be interested in accepting it or if I can do anything to help make it acceptable.  Thanks!  

https://github.com/gravitational/teleport/pull/643

**Comment by kontsevoy** [comment]
@jeremyd the PR is going in, thanks. We're won't be switching to static builds by default though. I hope this compromise works for your purposes?

**Comment by jeremyd** [comment]
Can anyone help me debug this panic?  This happens just after I login when using a static build.  When I use a dynamic linked build things seem ok.

https://gist.github.com/jeremyd/84c09e3f5b811addc5ef2f580b6c99fb

**Comment by kontsevoy** [comment]
@jeremyd most likely you're somehow linking against two different libc versions. I would try to wipe out both `pkg` directories under `$GOROOT` and `$GOHOME` and do a full rebuild.
