### ISSUE TITLE
Adapt RPM repository to not cause errors on openSUSE

### ISSUE THREAD

**Issue by tacerus** [gravitational/teleport#6445]
### What
Hello! I am aware that openSUSE is not a supported operating system. However, the RPM package works absolutely flawlessly on a good dozen openSUSE machines I deployed. Unfortunately though, the RPM repository lacks a few optimizations in order not to cause errors, and in order to comply with the security policies employed by the openSUSE developers. I would absolutely love if you could perform these minor changes in order for the experience on SUSE based operating systems to be less troubled.

### How

- Sign the file "repomd.xml" - an unsigned repomd.xml file causes zypper (the package manager), as well as YaST (the system management tool), to display warning messages, which are only able to be bypassed either by disabling security features, or by manually accepting the issue every time a repository refresh is being performed. [Image 1 (adding the repository)](https://pasta.lysergic.dev/?0fd3780b6297d91d#6GtucnTf9MPS9ZRW4mvJczLuj7KmV5mtNBqXsL8XTWg2) [Image 2 (disabling and enabling the repository)](https://pasta.lysergic.dev/?684a3faa852f6f74#GZ5Vav8ZJsXjsfBAxDY7rVEkPsM1SJUBs3dfeCMfqRj9)
- Publish the signatures public key. [Image Part 1](https://pasta.lysergic.dev/?3cd2aefe5ca96d01#4KxNjsGgGcgFEUioJHcpR6KeAZpvz9bYvWtAFsBjLAVo) [Image Part 2](https://pasta.lysergic.dev/?eb7051f5be8df0a3#Gh7RJ7ZUBB4uiWm2ip87KYgTWbVtzriKqPFSn1mp2LEr)
- Soften the permissions of the directory structure - other RPM repositories are freely browsable, which is not the case with your repository. It seems your repository employs more strict permissions, which would need to be adjusted in order to allow the package managers to access desired metadata files and directories. [Image Part 1](https://pasta.lysergic.dev/?9f49060ee681cc2f#EtCqo3GXbK9f8hQGKsKPBJj7t3qRdk1LKt2HCWGZQxH4) [Image Part 2](https://pasta.lysergic.dev/?ec2cf3ccd4734af2#9AgXMQ5EAYCgjMreNVnyYqFeresmkWosbmHF34qvkCQL)
- Alternatively, if maintaining these additional changes is a challenge, the packages could be hosted on [openSUSE's  OBS](https://build.opensuse.org/) (happily as a non-supported mirror), which takes care of the requirements.

### Why
Since the RPM package itself is working flawlessly on openSUSE, even if installed through the repository (after skipping the errors, of course), it would, in my opinion, be a minor task to also adjust the repository accordingly, in order for openSUSE users (and likely SUSE Enterprise Linux users as well) to enjoy installations and updates using already established package management routines.

A particular annoyance is found during automated deployments. I included the repository and package in an AutoYaST installation profile - while the security checks in such a profile can be softened, manual user intervention to accept the errors during the deployment is still required.

### Workaround

- Manually accepting the errors during installations and upgrades -> annoying.
- Disabling the repository after the installation and only enabling it on demand -> possibly missing out on crucial security updates and risking accidental teleport uninstalls during cleanups of orphaned packages (zypper marks packages from disabled repositories as orphaned).
- Self-hosting the repository -> possibly missing out on crucial security updates and annoying to maintain for a single package.

I would like to use this opportunity to thank for the marvelous piece of software - I will keep using it no matter of the outcome of my request. :-)

**Comment by wadells** [comment]
Thanks for the detailed report @tacerus.  I'm taking a look at our rpm and deb repo managment, and this issue is a wealth of info.  I'll report back here once I have some updates.

**Comment by wadells** [comment]
@tacerus: Can you give me further repro steps?  E.g. what commands do you need to run 

> * Sign the file "repomd.xml"

I've got a PR up for this: https://github.com/gravitational/teleport/pull/9027.  It'll need backports, but should be relatively quick and uncontroversial. :crossed_fingers: 

>     * Publish the signatures public key. [Image Part 1](https://pasta.lysergic.dev/?3cd2aefe5ca96d01#4KxNjsGgGcgFEUioJHcpR6KeAZpvz9bYvWtAFsBjLAVo) [Image Part 2](https://pasta.lysergic.dev/?eb7051f5be8df0a3#Gh7RJ7ZUBB4uiWm2ip87KYgTWbVtzriKqPFSn1mp2LEr)

The public key is published: https://rpm.releases.teleport.dev/RPM-GPG-KEY-teleport', and referenced in the repo:

```console
$ curl -s https://rpm.releases.teleport.dev/teleport.repo | grep gpg
gpgcheck=1
gpgkey=https://rpm.releases.teleport.dev/RPM-GPG-KEY-teleport
```

Does it need to be published in a certain keyserver or location to work with zypper/YaST/suse?

>     * Soften the permissions of the directory structure - other RPM repositories are freely browsable, which is not the case with your repository. It seems your repository employs more strict permissions, which would need to be adjusted in order to allow the package managers to access desired metadata files and directories. [Image Part 1](https://pasta.lysergic.dev/?9f49060ee681cc2f#EtCqo3GXbK9f8hQGKsKPBJj7t3qRdk1LKt2HCWGZQxH4) [Image Part 2](https://pasta.lysergic.dev/?ec2cf3ccd4734af2#9AgXMQ5EAYCgjMreNVnyYqFeresmkWosbmHF34qvkCQL)

This isn't a permissions issue -- we don't have a media directory at all. https://rpm.releases.teleport.dev/media1/media doesn't exist, and  isn't created by `createrepo`.  Can you link some documentation our further info about what is expected to be here and why YaST needs it?

For more info, see our rpm repo metadata publishing workflow here:

https://github.com/gravitational/teleport/blob/d67e9b347f7b3eaaf467255761fec2551e8ffde6/.drone.yml#L4347-L4391

>     * Alternatively, if maintaining these additional changes is a challenge, the packages could be hosted on [openSUSE's  OBS](https://build.opensuse.org/) (happily as a non-supported mirror), which takes care of the requirements.

IMO, this is unlikely.  Because we distribute security software, and Teleport enterprise has some non-free code, we typicaly avoid involving 3rd parties in distribution.  I'd need to know a lot more about OBS (and maybe talk to one of the engineers maintaining it) before we'd consider building/publishing there.  If OBS is more of a mirror situation, that may be easier

**Comment by wadells** [comment]
Hi @tacerus. The RPM repo metadata is now signed using the same key that signs the packages:

```
walt@work:/tmp/suse$ curl -O https://rpm.releases.teleport.dev/repodata/repomd.xml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2985  100  2985    0     0   7192      0 --:--:-- --:--:-- --:--:--  7192
walt@work:/tmp/suse$ curl -O https://rpm.releases.teleport.dev/repodata/repomd.xml.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   833  100   833    0     0   5553      0 --:--:-- --:--:-- --:--:--  5553
walt@work:/tmp/suse$ gpg --verify repomd.xml.asc repomd.xml
gpg: Signature made Tue 11 Jan 2022 05:57:35 PM PST
gpg:                using RSA key 0C5E8BA5658E320D1B031179C87ED53A6282C411
gpg: Good signature from "Gravitational, Inc <info@gravitational.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0C5E 8BA5 658E 320D 1B03  1179 C87E D53A 6282 C411
```

You can find the public key here:

https://rpm.releases.teleport.dev/RPM-GPG-KEY-teleport

If there are other things SUSE needs to work with the repo, please reopen with specific details, per https://github.com/gravitational/teleport/issues/6445#issuecomment-971132296
