### ISSUE TITLE
Do not show billing and usage on non-cloud

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6447]
We should not show billing and usage on non-teleport cloud UI:

<img width="281" alt="Screen Shot 2021-04-13 at 10 21 40 PM" src="https://user-images.githubusercontent.com/13717/114658480-b596df80-9ca6-11eb-8b66-802878578ab6.png">

**Comment by alex-kovoy** [comment]
@kimlisa when resolving user ACL, lets also check for the cloud feature being enabled 

https://github.com/gravitational/teleport/blob/master/lib/web/ui/usercontext.go#L181


```golang
modules.GetModules().Features().Cloud
```

**Comment by alex-kovoy** [comment]
@kimlisa sorry for the wrong pointer, I forgot that proxy does not use modules when running in the stand-alone mode. And you are right, the proxy need to be able to query the auth service to get this info.
