### ISSUE TITLE
Improve missing bootstrap file error message 

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#6477]
If you specify a `--bootstrap` flag to Teleport and the path specified does not exist, Teleport fails with a undescriptive error message:

```
error: path '/tmp/state.yaml' does not exist
```

Teleport should provide context on why it is failing to start to help the user resolve this issue, for example:

```
error: failed to bootstrap cluster configuration: path '/tmp/state.yaml' does not exist 
```

**Comment by zmb3** [comment]
Looks like this was fixed in #19009.

When I run `teleport start --bootstrap=doesnotexist.yaml` I get:

```
ERROR: path 'doesnotexist.yaml' does not exist
```
