### ISSUE TITLE
Port checker on client tools

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#6484]
### What
Provide a mechanism to check port access to confirm a `tsh` access to a proxy.  
```bash
$ tsh checkaccess --proxy=teleport.example.com
Checking ports. Note you will 
Web teleport.example.com: 443 confirmed
SSH teleport.example.com:3023 unavailable
Kube teleport.example.com:3026 available
DB teleport.example.com:3036 available

You have at least one port not available [SSH].  This will likely cause issues. 
```

### How
Provide a network check on a specific port is reachable

### Why
First time users and installations often don't have all the ports available (web, ssh) from any or all workstations.  This provides a mechanism to validate that.  As we move to consolidate ports this could also be a way to confirm connectivity even to one port.

### Workaround
Users do manual checks using various networking tools. 
```bash
teleport teleport.example.com 3023
```

**Comment by zmb3** [comment]
I'm going to consider this not planned given that:
- there hasn't been much traction on this in 2.5 years
- with multiplexing you rarely see anything other than port 443 being open
