### ISSUE TITLE
Add `--format` support to `tctl tokens add`

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#6486]
### What
When adding a token using `tctl tokens add --type` or similar, there is no option to get JSON output or anything which is machine-readable.

### How
Add `--format` support to other `tctl` commands.

### Why
This would be very useful to have so that the token can be parsed easily in situations where `tctl` is used to set up dynamic tokens, rather than needing to use `awk` etc.

### Workaround
`export TOKEN=$(sudo tctl tokens add --type=node --ttl=5m 2>&1 | grep "invite token:" | awk -F: '{print $2}' | tr -d ' ')`

**Comment by r0mant** [comment]
@capnspacehook Yes, let's unhide it.
