### ISSUE TITLE
`tctl` resource commands should support application and database servers

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#6488]
### Description

Add support for application and database servers to `tctl` resource commands, similar to `node` and `kube_service` resources:

```
$ tctl get app_server
$ tctl get db_server
$ tctl rm app_server/grafana
$ tctl rm db_server/mysql
```

**Comment by webvictim** [comment]
+1, I've also found it super confusing that `kube_service` is a thing but `app_service` and `db_service` are not.

**Comment by r0mant** [comment]
This is supported now (in 8.0) via dynamic registration:
https://goteleport.com/docs/ver/8.0/application-access/guides/dynamic-registration/
https://goteleport.com/docs/ver/8.0/database-access/guides/dynamic-registration/
