### ISSUE TITLE
Use Teleport to get short lived AWS access key and secret

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#6497]
### What
We want to use Teleport to grant short-lived AWS access keys and secrets to users.

### How
After `tsh login` a user would receive a temporary AWS access key and secret to use with the AWS cli.

**Comment by 1inh** [comment]
This would be really helpful. May I know if this is something the teleport team plans to have on the road map?

**Comment by stevenGravy** [comment]
Users can get access to AWS Accounts with App Access via cli and console
