### ISSUE TITLE
Separate viewing of audit logs and session recordings in Teleport roles

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#6498]
### What
I want to allow certain Teleport roles to only view audit logs and not session recordings.

### How
Create additional settings within Teleport roles to allow/deny to audit logs and session recordings separately.

**Comment by russjones** [comment]
@jon-can This should be possible, `KindEvent` gives you access to the audit log and `KindSession` for session recordings. I can look up what they are exposed as externally in a little bit.

**Comment by pschisa** [comment]
I tested these deny rules on my admin role which has an allow any resource with any verb statement with the following results:

~~~
  deny:
    rules:
    - resources:
      - session
      verbs:
      - '*'
~~~
This did not have any effect on my ability to view session recordings or audit events


~~~
  deny:
    rules:
    - resources:
      - event
      verbs:
      - '*'
~~~
This blocked my access to both session recordings and events with the message in the UI: `access denied to perform action 'list' on event`

It seems like the ability to list both session recordings and audit events are tied to the `event` resource permissions

**Comment by pschisa** [comment]
Correction, it is possible to prevent the session recordings from being accessed and still view audit logs by removing access to the `session` resource.  The session recordings will still be visible in the UI but when attempting to play them the UI will report the session recording playback is not available.  While the UI experience is rough around the edges, the session recording viewing can be prevented while still able to view audit logs.
