### ISSUE TITLE
Dynamic registration for apps and databases

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#6538]
### What

Users should be able to register applications and databases without having to update static yaml configuration.

### How

We should write a more detailed RFD but the basic idea is:

* Assuming there's a Teleport agent with "app" or "db" role is already registered in the cluster.
* Users should be able to create `AppServer` or `DatabaseServer` resource using tctl/API.
* App/DB agents are watching respective AppServer/DatabaseServer resources and updating their proxied apps/dbs configuration accordingly.
* App/DB agents can be configured to watch App/DB resources with specific labels.

In the context of this might be a good opportunity to refactor AppServer into a separate resource: https://github.com/gravitational/teleport/issues/5807.

### Why

Required for terraform provider and also makes it easier to register new apps/databases.

**Comment by stevenGravy** [comment]
@r0mant @klizhentas  great to have this part of the terraform provider

**Comment by r0mant** [comment]
This will be available in 8.0.
