### ISSUE TITLE
Add ability for Teleport to remove unused created UNIX users

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#6541]
### What
Currently, Teleport is able to integrate with PAM to create local UNIX users on login.  However, Teleport does not currently offer any mechanism to remove unused local users from the node.

Request is to add a feature to clean up unused UNIX users created by Teleport after a certain amount of time of inactivity or when a user is removed from Teleport.

### How
Ideally would like to see a configurable option in Teleport to have a locally created UNIX user deleted after a set amount of time of inactivity on the SSH node or when a Teleport user is removed.

### Why
As the integration with PAM to create users on login is intended to allow large enterprises to manage UNIX users automatically through Teleport, this would allow Teleport to fully manage the lifecycle of UNIX users.

This also helps enhance security by ensuring UNIX users of ex-employees would automatically be removed if the Teleport user was deleted or after a set amount of time.

### Workaround
Manually remove unwanted users or create an external script to remove unwanted users based on some parameters (for example `lastlog`)

**Comment by zmb3** [comment]
This is resolved with Teleport 10's automatic user creation.
