### ISSUE TITLE
PAM environmental variables break ssh login if corresponding value is NULL

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#6545]
### Description

**What happened**:
Customer enabled PAM on a server and configured a number of environmental variables they expected their IdP to pass back. The IdP was misconfigured, however, and did not pass the expected key:value pairs. This broke all ssh connectivity to the node, including connectivity for existing users, until these environmental variables were removed from the teleport config.

**What you expected to happen**:
If an admin misconfigures their IdP and expected attributes are not passed back to teleport during the authorization process, this should not break all SSH connectivity to the node. We should either ignore the null value or pass in a placeholder if necessary.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Set up PAM on a node w/ environmental variables configured in the teleport config.
2. Log in w/ an auth connector but make sure that the expected env variable key:value pair is not passed back by the connector on login.
3. Attempt to SSH to a node via WebUI either with a non-existent or already-existent Linux user.
4. Observe inability to log in.

### Server Details
- Teleport version (run `teleport version`): 6.1.1

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
```
disconnected
ssh: could not start shell
```

**Comment by xacrimon** [comment]
PR with a bugfix open. Will backport to v6 once merged in master which means inclusion in the 6.2 release.
