### ISSUE TITLE
Helm chart discloses secret tokens

### ISSUE THREAD

**Issue by Nuru** [gravitational/teleport#6547]
### Description

**What happened**:

Installing Teleport via the Helm chart using Helmfile, the secret tokens (like auth_token) are displayed in the output

**What you expected to happen**:

Secrets should be redacted.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Set up `values.yaml` with secret tokens
2. Run `helm diff --suppress-secrets`
3. Observe secret tokens in the output

### Server Details
- Additional details: Teleport chart version: 0.0.12

### Additional Information

Secrets should be stored in `Secrets` not `ConfigMaps` to avoid this. While `Secrets` are not cryptographically secure, they do a lot to prevent accidental disclosure such as in this case.

**Comment by webvictim** [comment]
The `teleport` Helm chart is being replaced with the `teleport-cluster` and `teleport-kube-agent` charts as part of #5582.

The `teleport-cluster` chart does not have this issue.

`teleport-kube-agent` allows you to create a `Secret` containing the token ahead of time and then use a blank value for the token to read it from the secret. This will prevent the value being shown in output.

**Comment by awly** [comment]
Closing this, as the old `teleport` chart is being deprecated
