### ISSUE TITLE
Allow fqdn as cluster name in aws terraform

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#6548]
### What
Allow fqdn and similar long values for cluster names as the teleport configuration allows. 

The terraform script throws an error for long cluster names due to the usage of the clustername in aws resource names (loadbalancers,...). Often the approach on cluster names is to use the proxy dns (teleport.example.com). Similarly our cloud approach is you get <subdomain>.teleport.sh.  
![image](https://user-images.githubusercontent.com/60704961/115718301-fba80f00-a348-11eb-846e-02da1bf86d54.png)

### How
Modify terraform script to use a different naming scheme then just the cluster name.

### Why
Provides parity with cloud and other similar approaches that the name of the cluster can be a fqdn or a long value.

### Workaround
Modify terraform script to use a different name.

**Comment by webvictim** [comment]
1. This is a Terraform limitation - you can't have dots in a variable name because it uses `.` as a resource separator.

2. Same as #1.

3. AWS has a limit of 32 characters for a load balancer name. https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateLoadBalancer.html
