### ISSUE TITLE
Merge style guide into docs

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6549]
## Details

Please meerge this guide https://gravitational.slab.com/posts/docs-guide-v4yjrmxl and PR into https://goteleport.com/docs/docs/

this way external contributors can see it too, I planned to make the docs/docs to be more visible and have a separate section, so let’s do that too
in particular this seems to fit alongside with https://goteleport.com/docs/docs/best-practices/

Let's create a proper navigation too:

Docs -> 
   Intro
   Guides/Best practices
              /Style

**Comment by inertial-frame** [comment]
Style guide is merged now -> closing. Will still make modifications and improvements to style guidelines.
