### ISSUE TITLE
High network load due to login.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#6554]
During SSO login, Auth creates a `types.User` which is then replicated to all proxies and nodes. For clusters with many nodes (10k+) this can cause high network load as `types.User` is replicated to all proxies and nodes.

Investigate why nodes need `types.User` and potentially see if we can stop replicating this to nodes to reduce network load.

**Comment by rosstimothy** [comment]
#8471 stopped propagating `types.User` to nodes
