### ISSUE TITLE
Failed reading web assets from the binary. zip: not a valid zip file

### ISSUE THREAD

**Issue by adilsond** [gravitational/teleport#656]
I tried to build teleport from source since I need 32bit binaries. But the application is stuck with the following message:

build/teleport start
[AUTH]  Auth service is starting on 0.0.0.0:3025
[PROXY] Reverse tunnel service is starting on 0.0.0.0:3024
[PROXY] Web proxy service is starting on 0.0.0.0:3080
[PROXY] starting the web server: Failed reading web assets from the binary. zip: not a valid zip file
Failed reading web assets from the binary. zip: not a valid zip file

I tried to figure out where is the zip file and why this message. This error doesn't occours with the binaries from github. But since only amd64 binaries are available, they are not a option for me.

To reproduce this error I used:
Ubuntu 16.04
golang 1.7 from https://launchpad.net/~adilson/+archive/ubuntu/golang
Follow all the istructions to build teleport and run, as root:

build/teleport start -d

**Comment by klizhentas** [comment]
try `make release` to get a binary with zip assets

**Comment by adilsond** [comment]
It worked here. Thanks. :+1:
