### ISSUE TITLE
`tctl auth sign --out=tls` creds dont work with terraform provider

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6566]
### Description

When client loads credentials from `.tsh` the provider works well.

How to reproduce:

Follow the quickstart in fork here:

https://github.com/gzigzigzeo/teleport-plugins/blob/feature/terraform/terraform/GETTING_STARTED.md

Login into cloud.

Run terraform apply with the following provider config

```
provider "teleport" {
#  cert_path    = var.cert_path
#  key_path     = var.key_path
#  root_ca_path = var.root_ca_path

  addr = "smoke.teleport.sh:443"
  # identity_file_path = "id"
}
```

This returns error when using `tctl auth sign --out=tls` creds:

```
provider "teleport" {
  cert_path    = var.cert_path
  key_path     = var.key_path
  root_ca_path = var.root_ca_path

  addr = "smoke.teleport.sh:443"
}
```

**Comment by Joerger** [comment]
What error does it return? `tctl auth sign --out=tls` creds will only work with the Auth server address, but is `smoke.teleport.sh:443` the web proxy address?

**Comment by Joerger** [comment]
@klizhentas Is this still an issue? I think `tctl auth sign --out=tls` credentials should just be taken out of the quickstart, identity/profile credentials can provide ssh connectivity instead.

**Comment by Joerger** [comment]
Opened a PR to teleport-plugins to resolve this - https://github.com/gravitational/teleport-plugins/pull/231
