### ISSUE TITLE
Teleport service logs get overwritten on restart

### ISSUE THREAD

**Issue by anurag-work** [gravitational/teleport#6581]
### Description
Log file /var/lib/teleport/teleport.log gets overwritten when service is restarted
**What you expected to happen**:
The file should be appended to 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Setup teleport as a service
```
[Unit]
Description=Teleport SSH Service
After=network.target

[Service]
Type=simple
User=teleport
Group=teleport
Restart=on-failure
EnvironmentFile=-/etc/default/teleport
ExecStart=/usr/local/bin/teleport start --pid-file=/var/lib/teleport/teleport.pid --diag-addr=0.0.0.0:3030 --config=/var/lib/teleport/teleport.yaml
ExecReload=/bin/kill -HUP $MAINPID
PIDFile=/var/lib/teleport/teleport.pid
LimitNOFILE=8192

[Install]
WantedBy=multi-user.target
```
teleport.yaml
```
teleport:
  log:
    output: /var/lib/teleport/teleport.log
    severity: DEBUG
```
2. Restart teleport service

### Server Details
- Teleport version (run `teleport version`): 6.0.1
- Server OS (e.g. from `/etc/os-release`): ubuntu 20.04/centos 7.9
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): on prem
- Additional details:

This makes debugging issues nearly impossible

**Comment by zmb3** [comment]
This was fixed with https://github.com/gravitational/teleport/pull/43359
