### ISSUE TITLE
Advertise proper server version to MySQL clients

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#6584]
### Description

In MySQL protocol, server reports its version to the connecting clients during the very first handshake message. In Teleport Database Access clients connect to the Proxy which currently doesn't have information about target MySQL database version so we hardcode version to `8.0.0-Teleport`.

This causes some incompatibility issues between the client and the server. For example, in version 8.0.3 MySQL removed a `query_cache_size` parameter and when clients think they're connecting to a 8.0.0 version (reported by our Proxy) they still try to query it and the target server returns an error.

This is primarily causing issues for applications that use Java drivers, such as DBeaver or DataGrip GUI clients.

### Expected behavior

Teleport should provide a way to advertise specific version to MySQL clients.

**Comment by gecube** [comment]
Hi! Why is it closed? Right now we faced the same issue with DataGrip and Amazon Mysql 8.0.33

```
Unknown system variable 'query_cache_size'
```
