### ISSUE TITLE
add fips, approval plugins, and updated access requests

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/teleport#6588]
## Details

Update enterprise faq entry and enterprise home page to reflect new changes.

Add approval plugins to community now

### Category
- Improve Existing
- Remove Outdated

**Comment by klizhentas** [comment]
@inertial-frame correction on the name, let's call our approval workflows to be access requests, here is a full glossary here:

https://lucid.app/publicSegments/view/841d8e82-216e-4b0e-9758-5e50a531f6ac/image.png

Which we should also publish to the docs at some point

**Comment by inertial-frame** [comment]
@klizhentas - I wonder if the product outline/glossary might be a good fit here: https://goteleport.com/docs/ver/6.2/faq/ - seems like it could use a helpful depiction of the core features?

**Comment by inertial-frame** [comment]
**Status**: Temporarily on hold while we determine the best approach here. Reopen the backport tickets once merged and/or settled.

This pertains to the 6700-6702.
