### ISSUE TITLE
Role = Node signup tokens do not last the specified --ttl=timeperiod

### ISSUE THREAD

**Issue by jeremyd** [gravitational/teleport#660]
I'm trying to create a long lasting token for node signup > 1 month or so.  Everytime I use a value it says it's doing it:

```
Please note:
  - This invitation token will expire in 599940 minutes
```

However, the token is actually set to expire more like in 30 min.

```
Token                                Role       Expiry Time (UTC)
-----                                ----       -----------------
xxx     Node       23 Dec 16 21:17 UTC
```

**Comment by kontsevoy** [comment]
@jeremyd which backend are you using? etcd, local (default) or DynamoDB?

**Comment by jeremyd** [comment]
Using etcd

**Comment by kontsevoy** [comment]
@klizhentas can you take a look plz? you're ze etcd masta.

**Comment by jeremyd** [comment]
I tried the same test in 1.3.2 thinking this fix would have landed, but I get the same results.  My tokens do not last the specified ttl (using etcd2 backend).  I assume this code made it into 1.3.2 judging from the timeline but .. perhaps the committed fix wasn't enough?

**Comment by klizhentas** [comment]
the fix is on the client, so you have to make sure you have new tctl as well.

**Comment by jeremyd** [comment]
So I installed this via the release tgz.  It has tctl and all the binaries, all version 1.3.2.. Then I run tctl on the same server where I install teleport.

```
teleport version                                                              
WARN[0000] syslog not available. reverting to stderr     file=utils/cli.go:52 func=utils.InitLoggerCLI
Teleport v1.3.2 git:v1.3.2-0-g33044f6
# tctl version
WARN[0000] syslog not available. reverting to stderr     file=utils/cli.go:52 func=utils.InitLoggerCLI
Teleport v1.3.2 git:v1.3.2-0-g33044f6
```

**Comment by jeremyd** [comment]
I'm reading through the code, and I think maybe it just doesn't do the conversion of TTL into expiration.  When I dump etcd, the expiration field shows the time 30 min from now.  I'm not seeing how this field gets set from the TTL yet..

**Comment by klizhentas** [comment]
Are you sure it's in 1.3.2? I've landed it in master, but not sure if it has landed in 1.3.2 really

**Comment by jeremyd** [comment]
I'm not sure no .. I was basing this on the time the commit was made. (will try to check harder)

**Comment by kontsevoy** [comment]
This is not in 1.3.2

**Comment by jeremyd** [comment]
Oh, darn, it didn't make the release.  OK cool, I'll just compile it up then I suppose.. Thanks!

**Comment by kontsevoy** [comment]
@jeremyd yeah, you can just apply the patch yourself to 1.3.2 codebase. `master` is not recommended for production use.
