### ISSUE TITLE
Support a "route to most recent" mode for duplicate hostnames/IPs.

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport#6613]
Teleport currently refuses to dial ambiguous node targets (e.g `alice@example.com` when two nodes claim the `example.com` hostname).  This is a good _default_ behavior, because it keeps people from being silently redirected to an unintended node (a potential security concern).  It poses problems, however, for folks who regularly create and destroy nodes within a small IP/hostname pool.  We should support a mode where the node that most recently heartbeated is always dialed instead.

**Comment by yjperez** [comment]
This feature will provide a better user experience for #5046

**Comment by russjones** [comment]
Fixed in https://github.com/gravitational/teleport/pull/8567/files
