### ISSUE TITLE
As a user, I should be able to request new roles from the Web UI and use them on the CLI. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#6622]
### What

Currently when a user requests a role, using `tsh request new` this user will only be able to use the role use `tsh`, using something like `tsh request assume` 

**Example Request** 
I'm not able to use the role in the CLI. 
![image](https://user-images.githubusercontent.com/559288/116320475-26d99680-a76d-11eb-9c57-8348454dc43f.png)

### Why
Access Requests should work across tools, web -> cli -> web again. This is 

### Workaround
The only workaround is to use a pure CLI flow. `tsh request new`

**Comment by Valien** [comment]
Just had a customer ask about this today. Good to hear there is a feature-request for this!

**Comment by zmb3** [comment]
This should work just fine today.
