### ISSUE TITLE
Add audit event for failed Kubernetes attempts

### ISSUE THREAD

**Issue by wadells** [gravitational/teleport#6633]
### What
Teleport version: 6.0.1

Attempting login with an expired ssh certificate will generate an event like the following in Teleport's audit logs:

```
{
  "addr.local": "...",
  "addr.remote": "...",
  "cluster_name": "",
  "code": "T3007W",
  "ei": 0,
  "error": "ssh: cert has expired",
  "event": "auth",
  "login": "...",
  "success": false,
  "time": "...",
  "uid": "...",
  "user": "..."
}
```

Attempting to login with an expired  cerfificate in a kubeconfig results in the following on the client side:

```
Unable to connect to the server: remote error: tls: bad certificate
```

But no record in the audit log, as far as I can tell.  It'd be great to have kuberentes calls with expired certificates show up in the audit log.

### Why
These logs are useful for forensics if expired credentials are still in use somewhere.

### Notes
I haven't checked the database access audit behavior for failed logins -- it may be worth taking a look at that too while you're in the same area.

### Workaround
Not that I'm aware of.

**Comment by zmb3** [comment]
Closing in favor of #39921
