### ISSUE TITLE
Improve output of parallel tsh ssh commands

### ISSUE THREAD

**Issue by henrikno** [gravitational/teleport#6635]
### What
When running tsh ssh across multiple hosts, the output is intermingled because it runs concurrently. E.g. running uptime might output
```
Running command on 10.13.37.2:3022:
 17:37:52 up 242 days, 17:23,  0 users,  load average: 0.93, 1.12, 1.22
 17:37:53 up 223 days, 11:08,  0 users,  load average: 0.70, 1.20, 1.45
Running command on 10.13.37.1:3022:
Running command on 10.13.37.42:3022:
 17:37:54 up 105 days, 21:51,  0 users,  load average: 1.49, 1.65, 1.70
```
Which host is which? If the command output multiple lines it's even harder to read.

### How
There are multiple ways, e.g. either buffer the output, then dump it all when the command ends, printing the hostname first. Or print the hostname as a prefix for each output line.

### Why
Sometimes we want to quickly check some condition on a bunch of hosts, and don't want to create an ansible playbook or similar. 

### Workaround
We have some workarounds but they're not convenient.
E.g. make sure all the output is on one line, make sure theres only one command doing the output otherwise it might get garbled, and prepend the hostname. For example to get the available memory:
`tsh ssh user@role=myrole 'HOST=$(hostname | tr "\n" " "); FREE=$(free -m | grep "^Mem:" | awk "{ print \$7 }"); echo $HOST $FREE' | grep -v 'Running command'`
Another workaround is to do it in a loop, e.g. 
`for HOST in $(tsh ls ${selection} |  grep '^[^ -N].*' | awk '{ print $1 }'); do echo $HOST; tsh ssh user@${HOST} ${cmd}; done`
But it's a lot slower since it's sequential.

**Comment by gwellington** [comment]
Having these logging enhancements when executing against multiple hosts would be awesome.  

I think at a minimum having the host logged per line would be great and if `tsh` can produce summary something similar to:
[host1] success
[host2] failed with exit code 128
[host3] success

2 hosts succeeded; 1 host failed

Lastly, if there is an option to log this to file that would be awesome.  Ideally, if we can have 1 file/host along with a summary as well.  The summary files could be something similar to:

`hosts.succeeded`
```
host1
host3
```

`hosts.failed`
```
host2
```
