### ISSUE TITLE
Need to use tolerations and node selectors with the teleport-cluster chart

### ISSUE THREAD

**Issue by dheitman42** [gravitational/teleport#6679]
### What
Need to be able to utilize tolerations and node selectors in the teleport-cluster chart.

### How
https://github.com/gravitational/teleport/pull/6678

### Why
This is required in order to run on isolated nodes, out of concern for availability in the event of noisy neighbor issues and/or for security isolation.

### Workaround
Any workaround would require maintaining a fork of the chart.

**Comment by hugoShaka** [comment]
Tolerations and affinities support was added in https://github.com/gravitational/teleport/pull/6344 but we forgot to come back to you and close the issue.
