### ISSUE TITLE
Document new features of 2.0

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#668]
Version 2.0 gains quite a few significant new features. This ticket is a reminder to update the documentation for them. 

Preliminary list (feel free to update) includes:

* Role-based access control (RBAC)
* High Availability (HA) section for FS-based backend.
* Build-in DynamoDB backend
* New 2nd factor auth options (U2F)

From @russjones 

* TOTP instead of HOTP for local users.
* Authentication changes.
* OIDC configuration changes.
* Addition of `TrustedClusters` resources.
* Dynamic Configuration.
* Agent key loading for system SSH agents.
* SSH agent forwarding

Current TODO

- [x] HA section with storage backends
- [x] etcd
- [x] DynamoDB

**Comment by russjones** [comment]
* Authentication changes.
* OIDC configuration changes.
* `TrustedClusters` resources.
