### ISSUE TITLE
Allow for arbitrary pod annotations in teleport-cluster chart

### ISSUE THREAD

**Issue by dheitman42** [gravitational/teleport#6681]
### What
The teleport-cluster chart should support an arbitrary set of pod annotation to accommodate various environmental requirements, and specifically to allow for KIAM role annotations (a necessary prerequisite to HA support).

### How
https://github.com/gravitational/teleport/pull/6680

### Why
In order to provide for future support of HA via DyanmoDB/S3, KIAM role annotations should be supported, to allow for use of IAM roles for AWS access.  Further, allowing for an arbitrary set of pod annotations can be useful for specific environmental configurations.

### Workaround
None

**Comment by webvictim** [comment]
Annotations for pods, deployments, services and configs are supported n the changes from https://github.com/gravitational/teleport/pull/6344
