### ISSUE TITLE
Cannot connect to trusted cluster node via web ui

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#669]
repro:

 1. set up a trusted cluster 
 2. open web ui and try to connect to trusted cluster node
 3. notice that the session gets successfully created but web-socket connection disconnects.

**Comment by klizhentas** [comment]
that could be a permission issue. when setting up a trusted cluster, you'd need to create a role that allows remote connections to succeed.

**Comment by kontsevoy** [comment]
@klizhentas also, on brand new setups this means that the role must be created when `trusted_clusters` setting is found in the YAML file. This is a higher level setting. `trusted_cluster=trust+tunnel`. Probably falls into my bucket.

**Comment by kontsevoy** [comment]
This has been fixed by @klizhentas
