### ISSUE TITLE
Algolia search only searches the current version of docs

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/teleport#6704]
## Details

Algolia Search:

1. Searches only the current version of the docs even when a newer version is selected and actively being read.
2. Displays only current docs in the result fields - clicking on these will take you to the current docs even when an article with the same name exists in the newer version from whence the search is being made.
3. Passing in a version number does not refine the search results.

### Category
- New Feature
- Improve Existing

**Comment by ptgott** [comment]
Closing this because it doesn't relate to docs content. I'm also not sure we want to make the docs searchable across versions. If we do, we should create an issue in `gravitational/docs`. What do you think, @klizhentas @xinding33?
