### ISSUE TITLE
Remove the "." from the end of the auth token generated by "tctl tokens add" command

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#6713]
## Details
Currently, the output from the `tctl tokens add` command includes a line with the auth token that ends in a period that is not part of the auth token:

`The invite token: 3ab58ba4a753a91dd8f9c8f7a50bcb7c.`

Request is to remove the period from being added at the end of the invite token line as it is confusing if the period is part of the token or not.

**Comment by Aharic** [comment]
Appears to have been introduced [here](https://github.com/gravitational/teleport/pull/7905/files#diff-b882e24e60badd0efddf342f0c451dcd476199078b709401405d88293574a27dR89) for app and node tokens, and has been part of db tokens for quite some time as well as seen [here](https://github.com/gravitational/teleport/pull/5005/files#diff-db13ff9c073b7b27e5f4971201c73c7d9ed34692d42d028968e50cc5f7e3682fR89)
