### ISSUE TITLE
Azure backend for object storage.

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6719]
### What
What would you like Teleport to do differently?

### How
How would you implement this?

### Why
Why do you need this?

### Workaround
If a workaround exists, please include it.

**Comment by klizhentas** [comment]
@russjones can we consider this to 7.0 as an option, should take 2-3 days?

**Comment by russjones** [comment]
Related issue: https://github.com/gravitational/teleport/issues/6117 to fully support Azure.

**Comment by corkrean** [comment]
Related to #5956

**Comment by zmb3** [comment]
Closing as duplicate #5956 and #6117.
