### ISSUE TITLE
Add details on minimum MacOS version supported by a given `teleport/tsh` version

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#6727]
_Originally posted by @joyshmitz in https://github.com/gravitational/teleport/discussions/6631_

It looks like Golang and/or MacOS have changed the APIs used for certain calls with newer versions, meaning that `tsh` v6.1.2 does not work on MacOS 10.11.6.

If we can find a reliable way to determine what the minimum version of MacOS supported by a given Golang version is, we should update our docs (and possibly download page) to include this information.

This may also be related to `cgo` and the build toolchain used on our MacOS build box - details below:

```
# sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H15
```

**Comment by inertial-frame** [comment]
It seems that https://github.com/golang/go/wiki/MinimumRequirements was partially updated to address similar questions for (Ubuntu and macOS): https://github.com/golang/go/issues/43996

**Comment by zmb3** [comment]
Operating system support is documented at https://goteleport.com/docs/installation/#operating-system-support
