### ISSUE TITLE
Add additional JSON output flags to other TSH commands

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#6742]
### What
Currently you can only get the json output in `tsh ls --format=json`. This works great but would like to see this expanded (customer request).

Add json output options to the following tsh commands:

- `tsh db ls --format=json`
- `tsh db env --format=json`
- `tsh db config --format=json`
- `tsh status --format=json`
- etc.

I would go as far as looking at any `tsh` command that outputs to the CLI the ability to output to json. This would enable customers to parse the info and leverage it in other tools.

Reference this closed issue - #3660 

### How
Expanding the `tsh ls --format=json` command to all other `tsh` commands

### Why
A customer requested this feature.

### Workaround
None at the moment. Not possible to extract this info from the other commands.

**Comment by pschisa** [comment]
+1 to adding this functionality to the `tsh db` and `tsh kube` commands

**Comment by ringerc** [comment]
Huge +1 especially for `tsh kube ls`, `tsh status`
