### ISSUE TITLE
Redis DB proxy support

### ISSUE THREAD

**Issue by joshdurbin** [gravitational/teleport#6761]
### What

I'd like to suggest, discuss the possibility of opening a PR to enable Redis as a supported "database" / proxy pass through similar to what's being done now for Postgres / MySQL DB access. To be clear; this is to expose internal Redis systems to external user via Teleport and not as a storage mechanism for internal Teleport server functions.

### How

There are a number of projects that [do this](https://github.com/liues1992/redis-proxy) that rely or are based off [go-redis](github.com/go-redis/redis/). Of particular interest to me, though, is the ability to proxy and provide rules to enable or toggle write access to the client. At this point I'm just gauging if the maintainers are interested in this.

### Why

Widen the scope of DBs Teleport can provide access to.

### Workaround

n/a

**Comment by pschisa** [comment]
Redis support PR: https://github.com/gravitational/teleport/pull/10053
