### ISSUE TITLE
Write documentation about audit logs

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#677]
## Description

I've received several requests about the structure of audit logs and how to manage them:

https://news.ycombinator.com/item?id=13275723

Write down some logs and examples how to do that with some providers.

**Comment by klizhentas** [comment]
More feedback:

```
This is awesome ! Would love to see a doc for detailed audit logging when you have one up.
This in itself is a killer app !
EDIT: one more request, please make you docs/makefile a little more beginner friendly. For example, your get-started page (or your makefile target) does not have systemd targets in place. I think you guys take care of necessary selinux permissions inside code.. but not sure if it does so for /var/lib/teleport. it might be useful to consider using ansible (which will make this very practical for devops)
```

**Comment by sandys** [comment]
+1 guys - this is super awesome. also want to add my voice for ansible based one click installation - should be very helpful if we are looking to deploy this to our servers.

**Comment by kontsevoy** [comment]
Closed:
https://github.com/gravitational/teleport.docs/commit/d6185cbc8744e10b47ad11b28c854170f57c3086
