### ISSUE TITLE
Odd Logins output when a user has no login

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#6789]
### Description

**What happened**:

If a user has no login there is a long uuid like id. 

```bash
tsh login --proxy=teleport.example.com:443 
Enter password for Teleport user steven:
Enter your OTP token:
668332
> Profile URL:        https://teleport.example.com:443
  Logged in as:       steven
  Cluster:            ip-172-31-68-3
  Roles:              admin
  Logins:             -teleport-nologin-0a430fb6-8d1b-4d33-9bca-086d3687a30e
  Kubernetes:         disabled
  Valid until:        2021-05-08 09:19:40 -0400 EDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```

**What you expected to happen**:

A message that indicates no logins instead of a random no login id.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a Teleport instance and a user with `admin` role
2. Login via `tsh` with the user

### Server Details
- Teleport version (run `teleport version`): 6.1.5
- Server OS (e.g. from `/etc/os-release`): ubuntu 
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`): 6.1.5
- Computer OS (e.g. Linux, macOS, Windows): ubuntu linux

**Comment by russjones** [comment]
@fspmarshall Why did we start adding the `-teleport-nologin` principal to certificates again?

**Comment by fspmarshall** [comment]
@russjones this is necessary for openssh compat. Openssh treats no logins as a wildcard allow, the exact opposite of what no logins means for teleport.

We *must* keep the placeholder login, but it would be fine to filter it out of tsh output if it is causing confusion.

**Comment by webvictim** [comment]
I think filtering the principal from `tsh` output makes most sense to avoid confusion. I believe that the web UI already does this.
