### ISSUE TITLE
Make survey more visible

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#6799]
### What

Let's make survey more visible - add it as a permanent message in Teleport UI.

Add a splash screen in the UI with a message and a form that submits a similar data to `usage.teleport.dev`

```echo "Thanks for installing Teleport."
echo ""
echo "Is it OK if we collect some info about your install?"
echo "Please run this command to send in a survey."
echo "optional: Replace email to join our newsletter and get a swag package."
echo "$ curl -X POST https://usage.teleport.dev -F OS=${machine} -F use-case="access my ..." -F email="alice@example.com"
```

**Comment by zmb3** [comment]
@klizhentas @xinding33 do we still want to do this? If so we can probably use a similar solution to what we just did in Teleport Connect

**Comment by zmb3** [comment]
Closed due to inactivity.
