### ISSUE TITLE
QR code for Teleport not working with Lastpass Authenticator

### ISSUE THREAD

**Issue by marchofreason** [gravitational/teleport#680]
Loving Teleport so far - First attempt at creating a user when trying to add the OTP with LastPass Authenticator it seems 
The error says "Invalid QR Code - Device Pairing Failed"
[Screenshot sample here](https://dl.dropboxusercontent.com/u/3222505/IMG_1820.JPG)

Google Authenticator works as advertised.

(Excuse the picture - Had to take a photo as android 7.x restricts screenshots on "Secure apps")

**Comment by klizhentas** [comment]
I wonder if it's because last pass does not support HOTP, only TOTP. We are planning to add support for TOTP as well.

**Comment by kontsevoy** [comment]
Dupe of #522
