### ISSUE TITLE
When uploads fail to complete, include the host's UUID in the error message

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#6802]
### What
Currently if Teleport has an error uploading a session, you just see a message at `WARN` level saying `Failed to complete upload.` with no extra information that can be used to track down the faulty session recording (like host UUID, hostname, filename etc)

```
WARN             Failed to complete upload. error:[
ERROR REPORT:
Original Error: *trace.BadParameterError MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
        status code: 400, request id: BASXNQNG0ADNMXDH, host id: dX59WtsYAs4YD3wYneXa/wSWEaoQIo9J4rHARNoXKROaPWSgosgFrkjSnTmL&#43;HySuDmrGskYMKI=
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/events/s3sessions/s3handler.go:365 github.com/gravitational/teleport/lib/events/s3sessions.ConvertS3Error
        /go/src/github.com/gravitational/teleport/lib/events/s3sessions/s3stream.go:112 github.com/gravitational/teleport/lib/events/s3sessions.(*Handler).CompleteUpload
        /go/src/github.com/gravitational/teleport/lib/events/stream.go:624 github.com/gravitational/teleport/lib/events.(*sliceWriter).completeStream
        /go/src/github.com/gravitational/teleport/lib/events/stream.go:497 github.com/gravitational/teleport/lib/events.(*sliceWriter).receiveAndUpload
        /opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit
User Message: MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
        status code: 400, request id: BASXNQNG0ADNMXEL, host id: dX59WtsYAs4YD3wYneXa/wSWEaoQIo9J4rHARNoXKROaPWSgosgFrkjSnTmL&#43;HySuDmrGskYN1I=] events/stream.go:627
```

### How
Augment the warning message with the failing host's UUID so it can be looked up in `tctl get nodes`.

### Why
Spurious warnings in the auth server logs with no easy method to investigate them further are not useful.

### Workaround
Turn the log level on the auth servers up to `DEBUG` and hope that there's a related message containing UUID or other information immediately before/after the warning.

**Comment by vitorenesduarte** [comment]
I'm thinking that we could simply add the session ID to those logs and that would be enough to find out further information about the node/pod by searching the audit log using the web UI. Below I try to demonstrate why.

Note that adding the session ID to those logs is very simple (48cece8ff25015af74afba82ee7bd3547dd77700), and from what I could tell, it doesn't seem to be the case for node/pod info.

---

#### Why adding session ID might be enough

I'm seeing `session.upload` audit events being generated in the following 3 cases:

- non-interactive SSH session:

<img width="986" alt="tsh-non-interactive" src="https://user-images.githubusercontent.com/4520516/203976987-881690a1-36c5-43c6-be5c-dd4cb7d77932.png">

- interactive SSH session:

<img width="1059" alt="tsh-interactive" src="https://user-images.githubusercontent.com/4520516/203976985-7fe95f86-d4c1-4cbe-a85d-edf7ec7c1a23.png">

- interactive Kubernetes session:

<img width="920" alt="kubectl-interactive" src="https://user-images.githubusercontent.com/4520516/203976975-7de24117-00a6-459a-b789-0c9b5ed649a2.png">

Each of these `session.upload` events is preceded by a `session.end` event which contains information about the node/pod in question:

- `session.end` for interactive & non-interactive SSH sessions:

```json
{
  "cluster_name": "vitor.teleport.sh",
  "code": "T2004I",
  "ei": 1,
  "enhanced_recording": false,
  "event": "session.end",
  "interactive": ...,
  "login": "ubuntu",
  "namespace": "default",
  "participants": [
    "vitor-local"
  ],
  "server_hostname": "...",
  "server_id": "...",
  "server_labels": {
    "teleport.internal/resource-id": "e390734e-0d66-441a-bb2c-72494d07b3ea"
  },
  "session_recording": "node",
  "session_start": "...",
  "session_stop": "...",
  "sid": "76649ce1-9f86-4d85-8af4-8b2c66479ba1",
  "time": "...",
  "uid": "...",
  "user": "vitor-local"
}
```

- `session.end` for interactive Kubernetes sessions:

```json
{
  "addr.local": "...",
  "addr.remote": "...",
  "cluster_name": "vitor.teleport.sh",
  "code": "T2004I",
  "ei": 20,
  "enhanced_recording": false,
  "event": "session.end",
  "initial_command": [
    "sh"
  ],
  "interactive": true,
  "kubernetes_cluster": "vitor-dev",
  "kubernetes_container_image": "nginx:1.14.2",
  "kubernetes_container_name": "nginx",
  "kubernetes_groups": [
    "system:authenticated",
    "system:masters"
  ],
  "kubernetes_labels": {
    "teleport.internal/resource-id": "7a426893-c720-4baf-b234-2688606579cf"
  },
  "kubernetes_node_name": "ip-192-168-77-72.us-west-2.compute.internal",
  "kubernetes_pod_name": "nginx-deployment-9456bbbf9-rf8rq",
  "kubernetes_pod_namespace": "default",
  "kubernetes_users": [
    "vitor.teleport.sh-vitor-dev"
  ],
  "login": "vitor-local",
  "namespace": "default",
  "participants": [
    "vitor-local"
  ],
  "proto": "kube",
  "server_id": "...",
  "session_recording": "node",
  "session_start": "...",
  "session_stop": "...",
  "sid": "4c17d2ac-5b13-4b20-b53c-0888cd020190",
  "time": "...",
  "uid": "...",
  "user": "vitor-local"
}
```

Furthermore, `session.end` events are searchable by session id (which we would now be able to retrieve from the warning logs):

- non-interactive SSH session:

<img width="950" alt="Screenshot 2022-11-25 at 11 45 45" src="https://user-images.githubusercontent.com/4520516/203979333-ff5b3066-3e73-472f-a284-af6c30e8c418.png">

- interactive SSH session:
<img width="1020" alt="Screenshot 2022-11-25 at 11 46 29" src="https://user-images.githubusercontent.com/4520516/203979329-8d02e64b-31d8-4c38-8b79-9f83cac37b4c.png">

- interactive Kubernetes session:

<img width="904" alt="Screenshot 2022-11-25 at 11 46 08" src="https://user-images.githubusercontent.com/4520516/203979331-23ba6c7c-a66b-40e5-8e13-93e9945f0b9b.png">

WDYT @webvictim?

---

Note that `session.upload` events are not searchable ATM, but we could change their description to include the session ID like in the other session events:

<img width="501" alt="Screenshot 2022-11-25 at 11 55 29" src="https://user-images.githubusercontent.com/4520516/203980826-d2f5d1cc-1f25-45e2-84ec-c7fd1c4cc130.png">

**Comment by webvictim** [comment]
Looks great @vitorenesduarte. I think the main issue here was people seeing "failed to upload" warnings on their auth servers and having no idea which of their many connected hosts actually contains the failing session recording. Hopefully the session ID will appear at least next to the host ID somewhere and give them enough information to track it down.
