### ISSUE TITLE
add support for loading connector secrets from a file (k8s secret)

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#6815]
### What

The SSO connectors (OIDC, GitHub) require sensitive values like client_secret. This is currently stored in the teleport database in the clear. The ability to load that value from a more secure system such as a k8s secret would help keep that secret value secure. 

### How

If the oidc client_secret value looks like a file path and the file exists, read the value from that file. This can be used in conjunction with the k8s secret system, or other systems that can expose a protected secret as a file that teleport can access.

### Why

To help keep sensitive values in the k8s secret system where that is a policy

### Workaround

There is currently no workaround.

**Comment by gclawes** [comment]
For clusters that are not k8s-hosted, it would still be nice for the `attributes_to_roles` configuration to be separate from the oidc/saml resource in terraform, as in #19861

**Comment by webvictim** [comment]
Adding the title of https://github.com/gravitational/teleport/issues/19861 here for search purposes: "Don't store saml connector secrets in CI/CD"
