### ISSUE TITLE
Quickstart login instructions incorrect?

### ISSUE THREAD

**Issue by oskapt** [gravitational/teleport#682]
It seems that the instructions in [the quick start](http://gravitational.com/teleport/docs/quickstart/) are missing something. The instructions say to log in using:
```
tsh --proxy=localhost localhost
```

This returns the following:
```
expected command but got "localhost"
```
Based on [other portions of the documentation](http://gravitational.com/teleport/docs/user-manual/#interactive-shell), the command should be
```
tsh --proxy=localhost ssh localhost
```

**Comment by kontsevoy** [comment]
@oskapt thanks, fixed.
