### ISSUE TITLE
Web assets breaking on 1.3.1

### ISSUE THREAD

**Issue by vancluever** [gravitational/teleport#687]
Hey all!

First off - amazing tool... can't wait to really give this a spin! :)

Second off - not too sure what's happening here, but it looks like there's an issue loading the web assets on the latest version. I noticed that the assets were moved to the binary in v1.3.0.

Debug isn't giving too much in the way of info, but a curl is saying that the connection is being closed prematurely. [Gist here][1].

[1]: https://gist.github.com/vancluever/689e5a2fa01fd47d948573803abb6398

In contrast, v1.2.0 works just fine.

FWIW I'm running this out of a docker container, with a custom `Dockerfile`, content in [this gist][2].

[2]: https://gist.github.com/vancluever/a25d735f79c97527b12303353d680a42

Any ideas on what this might be?

**Comment by kontsevoy** [comment]
@vancluever tried to reproduce your issue on Ubuntu 16.04 LTS. Here's the updated Dockerfile I used (I only added EXPOSE command to it):

```
FROM ubuntu:latest

RUN apt-get update && apt-get -y install curl make && \
  cd /tmp && \
  curl -LO https://github.com/gravitational/teleport/releases/download/v1.3.1/teleport-v1.3.1-linux-amd64-bin.tar.gz && \
  tar zxvf teleport-v1.3.1-linux-amd64-bin.tar.gz && \
  cd teleport && \
  make install && \
  rm -rf /tmp/* && \
  rm -rf /var/lib/apt/lists

WORKDIR /root
EXPOSE 3080
CMD /bin/bash -l
```

I built the container with

```
$ docker build -t userteleport:latest .
```
Launched with:

```
$ docker run --rm=true -ti -p 3080:3080 userteleport:latest /usr/local/bin/teleport start -d
```

Then I hit `https://localhost:3080` in a browser and everything worked.

**Comment by vancluever** [comment]
Hey @kontsevoy, thanks for the quick response!

My docker is currently 1.12.3 (on Arch), I'm giving it a go on my Mac right now to see if it's any different (looks like latest on there is 1.12.5). Will edit with the results.

FWIW, if it's working on your side then no sweat, if there's issues on things like live hosts I'll send a message along.

**Comment by kontsevoy** [comment]
Actually I see now (screenshot above) - "failed"

**Comment by vancluever** [comment]
Yeah, the assets were coming up ERR_CONTENT_LENGTH_MISMATCH. Most of the fonts, which was creating broken images in the sidebar. Will post a screenshot tomorrow :)

**Comment by vancluever** [comment]
Hey @kontsevoy - looks like you've found the issue, but just wanted to follow up with the screenshot:

![teleport-1 3 1-content-lenght-mismatch](https://cloud.githubusercontent.com/assets/10704423/21593522/e0ca5236-d0cc-11e6-9337-2d1f79490062.png)

Thanks again for looking into it so quickly!

**Comment by kontsevoy** [comment]
@vancluever can you please validate this build? 
http://s3.gravitational.io/ev/teleport-v1.3.2-linux-amd64-bin.tar.gz

If everything is OK on your side, we'll do an official release.

**Comment by vancluever** [comment]
Hey @kontsevoy, looks good! Screenshot attached with all assets loading properly


![screen shot 2017-01-04 at 10 03 27 am](https://cloud.githubusercontent.com/assets/10704423/21653295/3b6adca8-d265-11e6-8b2b-1b075dd512db.png)

**Comment by kontsevoy** [comment]
Thanks @vancluever We'll probably push a new minor release with this fix.
