### ISSUE TITLE
New user creation: Google Authenticator wording causing confusion

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#6872]
### Description

**What happened**:

When a new user is created in Teleport the default screen they see shows the QR code and the wording says to use Google Authenticator.

![Screen Shot 2021-05-14 at 11 51 11 AM](https://user-images.githubusercontent.com/1424442/118296915-7d540e00-b4ab-11eb-8917-2550b62c27d9.png)

This confuses users as they think that is the only way to create an MFA token is by downloading and using the Google Authenticator tool. 

**What you expected to happen**:

The wording should be changed to mention that any major MFA authentication app will work. I use Microsoft Authenticator exclusively and works without an issue. I have also used BitWarden's authenticator as well as Okta Verify with no issue.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create new user
2. Access Teleport temporary URL to finalize user creation
3. See QR code and wording around Google Authenticator and be confused if you don't use that tool.

**Comment by stevenGravy** [comment]
The message has been updated to not only specify Google auth.
