### ISSUE TITLE
Use the new events api  with pagination for events screen

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#6878]
### What
Use the new events api with pagination for audit log screen and session recordings? (currently uses the same endpoint and just filters for `session.end` events)

### Reference
RFD: https://github.com/gravitational/teleport/blob/master/rfd/0019-event-iteration-api.md
Implementation: https://github.com/gravitational/teleport/pull/6731

**Comment by zmb3** [comment]
@EdwardDowling can yo have a look at this RFD and see if it helps with your `tsh sessions ls` work?

**Comment by EdwardDowling** [comment]
> @EdwardDowling can you have a look at this RFD and see if it helps with your `tsh sessions ls` work?

This would definitely greatly clean up the tsh sessions ls functionality

**Comment by kimlisa** [comment]
dup of https://github.com/gravitational/webapps/issues/322
