### ISSUE TITLE
Missing metrics from diagnostic endpoint

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#6888]
### Description
Certain metrics listed in our documentation are not present in the 6.1 software release (checked 6.1.0 and 6.1.1).

The following is a list of metrics available on our website that were not present when checking the diag-addr metrics endpoint:
~~~
user_max_concurrent_sessions_hit_total
failed_login_attempts_total
certificate_mismatch_total
proxy_connection_limit_exceeded_total
failed_connect_to_node_attempts_total
user_login_total
heartbeat_connections_missed_total
heartbeat_connections_received_total
cluster_name_not_found_total
trusted_clusters
reversetunnel_connected_proxies
~~~

**Comment by jdconti** [comment]
@pschisa think these were only recently added in `6.1.5` via https://github.com/gravitational/teleport/pull/6511

**Comment by pschisa** [comment]
Thanks @jdconti! Upgrading to 6.1.5 got the expected metrics present.
