### ISSUE TITLE
Thundering herd on auth server restart

### ISSUE THREAD

**Issue by jdconti** [gravitational/teleport#6889]
### Description

**What happened**:  Thundering herd on auth server restart

**What you expected to happen**: Random jitter on reconnect to prevent thundering herd.

### Reproduction Steps
1. Deploy large cluster

2. Restart auth server(s)
3. Observe all clients attempt to reconnect on the same second.

### Server Details
- Teleport version (run `teleport version`):
```
Teleport Enterprise v6.1.5 git:v6.1.5-0-gdad2a7b5b go1.15.5
```
- Server OS (e.g. from `/etc/os-release`):
```
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Bare metal
- Additional details:

### Client Details
N/A

### Debug Logs
N/A

**Comment by SEJeff** [comment]
some jitter on reconnect along with exponential backoff is a solid approach to mitigate this.

**Comment by fspmarshall** [comment]
This is likely related to the watchers used by `cache` and `ProxyWatcher`.  Those watchers have a fairly tight (10 second) maximum backoff.  We could probably bump the maximum backoff to ~1min jittered without any significant determent.
