### ISSUE TITLE
Invalid Character while registering U2F key

### ISSUE THREAD

**Issue by crdnl** [gravitational/teleport#689]
Was trying to register a U2F key (Feitian ePass) with my server.

Error on Browser (Opera 43.0.2442.7 and Chrome 55.0.2883.87) : 
`{"message":"asn1: syntax error: PrintableString contains invalid character"}`

Error in console:
`ERRO[0012] asn1: syntax error: PrintableString contains invalid character  file=auth/new_web_user.go:281 func=auth.(*AuthServer).CreateUserWithU2FToken`
`ERRO[0012] asn1: syntax error: PrintableString contains invalid character  file=auth/apiserver.go:772 func=auth.(*APIServer).createUserWithU2FToken`

POST Response to U2F Button Press
https://gist.github.com/crdnl/452c20e8165b107f81d05912d67db89f

**Comment by crdnl** [comment]
If you guys want to look at my environment, send me a PM.

**Comment by kontsevoy** [comment]
@jcj83429 @alchar @bibekaur @jdahiya can you guys take a quick look please?

**Comment by crdnl** [comment]
@jcj83429 It's a Feitien ePass that I got from eBay. ATM I currently don't have another kind of U2F key available.

**Comment by klizhentas** [comment]
@crdnl I've got feitan key by mail today, will try to reproduce and will get back to you.

**Comment by crdnl** [comment]
@klizhentas Alrighty, thanks.

**Comment by crdnl** [comment]
@klizhentas Any update?

**Comment by russjones** [comment]
@crdnl This ticket has gotten pretty old, if you are still running into an issue, please re-open this ticket.
