### ISSUE TITLE
Investigate more consistent Docker image usage

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#6895]
_Originally posted by @wadells in https://github.com/gravitational/teleport/pull/6228#issuecomment-840046457_

I've been playing around with a better way to do docker images in Make, inspired by `docker build --iidfile` and go modules.  The idea being is: a floating tag in the Makefile is locked at a specific hash with a file committed to the repo (akin to go.mod vs go.sum).  Then that specific hash can be updated and committed when needed.  It isn't quite vendoring since the image/layers don't end up in the git repo, but it is close as  we use a cryptographic hash of the image we want to fetch.

```make
REPO := alpine
VERSION := 3.13.5
IMAGE := $(REPO):$(VERSION)
IIDFILE := $(REPO)-$(VERSION).iid

.PHONY: box
box: $(IIDFILE)

$(IIDFILE): Makefile
        docker pull $(IMAGE) # or docker build etc
        docker inspect --format='{{index .RepoDigests 0}}' $(IMAGE) > $(IIDFILE)

.PHONY: refetch
refetch:
        docker pull $(IMAGE) # or docker build etc
        docker inspect --format='{{index .RepoDigests 0}}' $(IMAGE) > $(IIDFILE)

.PHONY: run
run: $(IIDFILE)
        docker run --rm -ti $$(cat $(IIDFILE)) sh
```

In use:

```console
$ make run   
docker pull alpine:3.13.5 # or docker build etc
3.13.5: Pulling from library/alpine
Digest: sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
Status: Downloaded newer image for alpine:3.13.5
docker.io/library/alpine:3.13.5
docker inspect --format='{{index .RepoDigests 0}}' alpine:3.13.5 > alpine-3.13.5.iid
docker run --rm -ti $(cat alpine-3.13.5.iid) sh
/ # exit
$ make run
docker run --rm -ti $(cat alpine-3.13.5.iid) sh
/ # exit
$ docker image rm alpine:3.13.5
Untagged: alpine:3.13.5
Untagged: alpine@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
Deleted: sha256:6dbb9cc54074106d46d4ccb330f2a40a682d49dda5f4844962b7dce9fe44aaec
$ make run                     
docker run --rm -ti $(cat alpine-3.13.5.iid) sh
Unable to find image 'alpine@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f' locally
docker.io/library/alpine@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f: Pulling from library/alpine
540db60ca938: Already exists 
Digest: sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
Status: Downloaded newer image for alpine@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
/ # exit
```

This  neatly solves the re-download problem in a Make native way (using the mtime on the `.iid`).  Furthermore, it works towards build determinism/reproducibility and reducing the risk of 3rd party supply chain attacks (a tag we depend on is updated by a malicious party -- we wouldn't pick it up until an employee refetched and committed, which allows the PR cycle).

**Comment by wadells** [comment]
Food for thought, related to building/using deterministic docker images https://grahamc.com/blog/nix-and-layered-docker-images

**Comment by wadells** [comment]
We saw the `docker:dind` floating ref upgrade from `20.10.6` to `20.10.7` today, resulting in both teleport push builds and gravity docs builds failing with malformed (but previously working) volumes.

Unfortunately, drone yaml isn't as easily integrated with the image sha pin discussed above.  Perhaps dronegen could help here.

**Comment by wadells** [comment]
Prior art from the community, for inspiration/consideration:

https://github.com/safe-waters/docker-lock
