### ISSUE TITLE
Configurable idle web session timeout (Web UI)

### ISSUE THREAD

**Issue by marchofreason** [gravitational/teleport#691]
Hi All,

Is it possible to adjust the timeout for login on the Web UI? It would be great to be able to prevent users from timing out and having to login with their Google Authenticator / OTP each time.

**Comment by kontsevoy** [comment]
@marchofreason just curious, what would you set for yourself [idle session interval]?

**Comment by marchofreason** [comment]
@kontsevoy I would adjust all of our timeouts to 24 hours across the entire teleport experience. We have a small startup and people would login once a day in the morning into the proxy / auth server.

**Comment by klizhentas** [comment]
Looks like we don't honor session timeout in role settings for web sessions. I will take a look

**Comment by kontsevoy** [comment]
@klizhentas it's a constant `auth.WebSessionTTL` currently defined in `lib/auth/auth.go`
