### ISSUE TITLE
Allow alternate hostnames or hostname aliases for tsh ssh

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#6914]
### What

Customers would like to have the ability to define alt hostnames or hostname aliases that they can use to connect with tsh ssh. Currently users can only connect to a node with the node-name or a full label key and value (eg., `tsh ssh label-key=label-value`). Customer would like to be able to use configured alias or if not possible have the ability to use just a label value without having to specify the full key:value combo. Specifically, a few have requested the ability to configure multiple hostname aliases similar to what's possible with ScaleFT.

### Workaround

Current workaround is to use a label key:value pairs but this is not ideal for customer use cases that gave rise to feature request. Also has potential impact on processing speed if clusters with thousands of nodes exist with dozens of individual alias hostnames on each node, requiring Teleport to check through each one.

**Comment by zmb3** [comment]
This is possible today with tsh aliases. Are we good to close this @deusxanima?

**Comment by deusxanima** [comment]
Aliases work. Good to close.
