### ISSUE TITLE
Delete duplicate entries in our metrics reference

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#6919]
## Details
The following metrics are duplicated twice in the list available at https://goteleport.com/docs/metrics-logs-reference/
~~~
backend_batch_write_requests_total
backend_batch_read_seconds
audit_failed_emit_events
audit_percentage_disk_space_used
~~~
 These duplicate entries should be removed from the list as it looks like an error.

### Category
- Improve Existing

**Comment by inertial-frame** [comment]
This is merged in 6.1, 6.2 and waiting to be merged in 7.0 thanks!
