### ISSUE TITLE
Insecure Certificate when using Letsencrypt via CLI

### ISSUE THREAD

**Issue by marchofreason** [gravitational/teleport#692]
We seem to be having a weird error with our Teleport setup. Our Auth and Proxy server are running on the same VM - All the nodes are configured without any issues and logins are working from the Web GUI

On our Auth server the end of the teleport.yaml config for the **proxy_service** has this:
```
    # The HTTPS listen address to serve the Web UI and also to authenticate the
    # command line (CLI) users via password+HOTP
    web_listen_addr: 0.0.0.0:3080

    # TLS certificate for the HTTPS connection. Configuring these properly is
    # critical for Teleport security.
    https_key_file: /etc/letsencrypt/live/auth.mime.ai/privkey.pem
    https_cert_file: /etc/letsencrypt/live/auth.mime.ai/cert.pem
```
On the Web GUI the HTTPS connection is working fine and showing a secure connection and valid certificate.

Now we are trying to get Command Line going and when trying to login via `tsh login --proxy=auth.ourserver.com` the following error comes up:

```
WARNING:
 The proxy you are connecting to uses the self-signed HTTPS certificate.
 Try --insecure flag if you know what you're doing.
```

Any ideas?

**Comment by bshelton229** [comment]
Give using the concatenated `fullchain.pem` as the `https_cert_file` a try.

```yaml
https_key_file: /etc/letsencrypt/live/auth.mime.ai/privkey.pem
https_cert_file: /etc/letsencrypt/live/auth.mime.ai/fullchain.pem
```

**Comment by kontsevoy** [comment]
@marchofreason AFAIK Letsencrypt is not universally supported by Linux distros. Golang (language `tsh` is written in) looks at the following dirs when establishing https connections:

```
"/etc/ssl/certs/ca-certificates.crt", // Debian/Ubuntu/Gentoo etc.
"/etc/pki/tls/certs/ca-bundle.crt",   // Fedora/RHEL
"/etc/ssl/ca-bundle.pem",             // OpenSUSE
"/etc/pki/tls/cacert.pem",            // OpenELEC
```

Do `curl` and `wget` work when you point them at Teleport proxy?

**Comment by marchofreason** [comment]
@kontsevoy I didn't reply sorry but @bshelton229 had the right answer. The Letsencrypt cert worked perfectly, all I just needed to do was replace the Cert_file with fullchain.pem

Maybe could recommend putting that into the Documentation as I wouldn't have guessed it was the error otherwise?
