### ISSUE TITLE
Clipboard Paste into WebUI

### ISSUE THREAD

**Issue by marchofreason** [gravitational/teleport#693]
Apologies for opening too many issues (if not applicable) - 

It seems that our users  are unable to paste into the WEBUI - Copy FROM the  WebUI works fine but can't paste text into the UI.

We have tried to use the following keyboard shortcuts
```
Ctrl + Insert
Ctrl + V
Right Click (No Paste - Just Inspect and HTML menu)
```

**Comment by alex-kovoy** [comment]
You can copy&paste using the mouse. For working with a keyboard, Teleport employs tmux-like "prefix" mode. To enter prefix mode, press Ctrl+A.

While in prefix mode, you can press Ctrl+V to paste, or enter text selection mode by pressing [. When in text selection mode, move around using hjkl, select text by toggling space and copy it via Ctrl+C. 

http://gravitational.com/teleport/docs/user-manual/#web-ui
