### ISSUE TITLE
TLS should not be required for etcd backend

### ISSUE THREAD

**Issue by mikkeloscar** [gravitational/teleport#694]
I don't think TLS should be a hard requirement for using the etcd backend. There are a couple of use cases where you might wanna run without TLS.

* When testing locally (though it's not complicated to setup test certs)
* In environments where you can protect etcd in other ways.
  * An example could be running teleport in AWS and use security groups to allow only the auth instance(s) to connect to etcd.

A simple solution would be to remove these checks: https://github.com/gravitational/teleport/blob/master/lib/backend/etcdbk/cfg.go#L45-L50

Alternatively the solution could be to add a config value `insecure_disable_tls: true` in case you don't want it to fallback to non-TLS when you forget to define the `tls_{cert|key}_file` values.

**Comment by kontsevoy** [comment]
@mikkeloscar good timing, we were in the middle of tidying up the backend plugins.
