### ISSUE TITLE
Configure Ansible to use Teleport tsh

### ISSUE THREAD

**Issue by maanas** [gravitational/teleport#695]
Hello there,
We are tying to set up a teleport cluster and us the same to install and manage node using ansible. I m able to use the alias to connect to node
`alias ssh="tsh ssh --proxy=localhost --user=root" and connect to node.

I tried following the instruction given in admin manual. I added following in for ssh proxy
`Host *.web01.server.com
  ProxyCommand ssh -p 3023 %r@localhost -s proxy:%h:%p
`
I m stuck at this line 
`tsh agent will print environment variables into the console. Configure your system to evaluate these variables: they tell ssh to use tsh to authenticate you against work.example.com cluster.

When everything is configured properly, you can use ssh to connect to any node behind work.example.com:
`

I tried to run the agent and set the environment variable and execute
ssh root@node1 but it does not work.

Please advise.

**Comment by kontsevoy** [comment]
The documentation says you should be using `ssh` client with Ansible, not the alias:
http://gravitational.com/teleport/docs/admin-guide/#using-teleport-with-openssh

When you launch `tsh agent` command, it will print something like:
```
SSH_AUTH_SOCK=/var/folders/lp/7xn30l_s3h37cy29dv8yd5hh0000gn/T/ef9650f2-1d67-4068-bce7-27b983bc0506.socket; export SSH_AUTH_SOCK;
SSH_AGENT_PID=5997; export SSH_AGENT_PID;
echo Agent pid 5997;
```

You need to apply this to your environment. One way to do this is via `tsh agent > file` followed by `source ./file`, so when you do `echo $SSH_AGENT_PID` you should see `5997` printed.

Once you do that, the regular `ssh` will work by talking to `tsh` running in the SSH agent mode, and ansible will work too (follow the doc again and set `scp_if_ssh = True` in Ansible config)

**Comment by maanas** [comment]
Thank you, Will try and get back. In the meanwhile we are going to use only the teleport master to monitor and record the session and use the normal ssh key based login to the nodes.
