### ISSUE TITLE
Auditlog process taking 100% CPU on Ubuntu server

### ISSUE THREAD

**Issue by madaerodog** [gravitational/teleport#6951]
### Description

**What happened**:

This might not be a bug but I require your assistance in analyzing this issue maybe it's an actual security vulnerability.
I have a Linode Ubuntu server that I use for testing IoT prototypes and I usually need remote access and I use Teleport latest version 6.1.5 (upgraded from an older one). I and another colleague are the only ones with access to the server and we only installed teleport, an mqtt broker, and InlfuxDB on the server all from official links.

A few days ago I have received an alert from Linode that my server is using over 95% CPU continuously and I have logged in and to my surprise, a process started by the teleport user that I have created is running the command named "auditlog" and that is taking all the CPU. 

Digging further the actual command that is run by the process is 

ADDRKEY=_a_very_long_key SSH_CONNECTION=suspicious_ip_not_ours 50428 myserverip 22 LANG=en_US.UTF-8XDG_SESSION_ID=605 USER=teleport PWD=/home/teleport HOME=/home/teleport SSH_CLIENT=suspicious_ip_not_ours 50428 22 MAIL=/var/mail/teleport SHELL=/bin/bash SHLVL=2 LANGUAGE=en_US : LOGNAME=teleport XDG_RUNTIME_DIR=/run/user/1000 PATH=/tmp:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games_=/usr/bin/nohup

Now you can imagine my shock when visiting said http://suspicious_ip_not_ours it was a tor exit router that I have no knowledge or idea how it is connected to my install. Cleary my server has been compromised but just out of curiosity I still let it run to further debug it.

Interestingly I can kill the process and Teleport runs just fine, even the auditlog entries on the webapp look ok, but suspiciously 
after a day or so the process reappears eating all my CPU again.

I tried to use grep to find the ip string in any files on the disk with no success.

Does anybody have any idea how I could proceed in unraveling what is happening?
The easy thing would be just to format the server and start fresh but maybe our experience can help others.
Thank you in advance,
If I can help with any pieces of information or you have any idea what to do to find the culprit please let me know.

**Comment by klizhentas** [comment]
@madaerodog hello Constantin, can you please join our slack channel https://goteleport.com/slack and DM me there - `sasha` for faster assistance? Refer this issue in the message.

**Comment by webvictim** [comment]
@madaerodog Did you create a `teleport` user on the host as part of your installation process? It looks like maybe you didn't set a strong password on that account or set it to a `nologin` shell and it got brute forced via SSH (port 22). Teleport doesn't create a system user itself when you install via tarball, RPM or DEB.

I suspect that `auditlog` is just a crypto miner or something which was installed as part of the compromise. You should consider the entire server compromised at this point and reimage from scratch, as you mentioned. If you do create a user named `teleport` yourself, make sure that the user is either deactivated or has a strong password. You should also set its shell to `/sbin/nologin` or `/bin/false` so that it cannot be used interactively.

**Comment by madaerodog** [comment]
Thank you all for the good advice, we have investigated further and indeed the attacker entered directly through SSH alone and not Teleport and just used the auditlog entry to probably cover his traces since the user was named teleport.
Since we do not know if there are other tamperings besides entering via ssh and running the command that was eating our CPU I thinks its best for us to start fresh and listen to the better practices recommended by both you and users on Github about users with restricted permissions for install and no login to shell and more strict SSH settings.

I guess it's a lesson to learn here, strong passwords are not enough, do take care of creating new users with full access rights and how you store/share said passwords.
