### ISSUE TITLE
ssh agent delete and re-add key functionality broken on 6.1.0+

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#6956]
### Description

**What happened**:

Customer use case requires users to run `ssh-add -D` to periodically remove keys from ssh agent, and then run `ssh-add <key_path>` to re-add specific keys only (including Teleport certs and keys). This functionality works fine pre 6.1.0 but appears broken in 6.1.0+ implementation.

**What you expected to happen**:

Users should be able to delete all keys from ssh agent and re-add them one-by-one and have it work, as it did pre 6.1.0.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Log into teleport via `tsh login`
2. Run `ssh-add -l` and observe a list of keys added post-login
3. Run `ssh <teleport_hostname>` and observe successful login
4. Run `ssh-add -D` to remove drop all keys
5. Run `ssh-add <key_path>` to re-add specific keys only (including Teleport keys)
5. Run `ssh <teleport_hostname>` again and observe failure with `permission denied (public key)` error

### Server Details
- Teleport version (run `teleport version`): 6.1.0

### Client Details
- Tsh version (`tsh version`): 6.1.0

**Comment by flybyray** [comment]
file structure in ~/.tsh changed

`~/.tsh/keys/<teleport host>/<username>-cert.pub` moved  to `~/.tsh/keys/<teleport host>/<username>-ssh/<cluster name>-cert.pub`

as a workarround you may need to make a symbolic link to the original location. as many ssh-agent implementations have an automatism to load additional file with `-cert.pub` suffix.

```
tsh login ...
ln -s ~/.tsh/keys/<teleport host>/<username>-ssh/<cluster name>-cert.pub ~/.tsh/keys/<teleport host>/<username>-cert.pub
# just an example for the keychain ssh agent
eval $(keychain --eval --clear --agents ssh ~/.tsh/keys/<teleport host>/<username>)
```

**Comment by flybyray** [comment]
or this patch on top of v6.2.0
```diff
diff --git a/api/profile/profile.go b/api/profile/profile.go
index 893ffa262..2881f6e36 100644
--- a/api/profile/profile.go
+++ b/api/profile/profile.go
@@ -314,12 +314,12 @@ func (p *Profile) TLSCAsPath() string {
 
 // SSHDir returns the path to the profile's ssh directory.
 func (p *Profile) SSHDir() string {
-       return filepath.Join(p.UserKeyDir(), p.Username+constants.SSHDirSuffix)
+       return p.UserKeyDir()
 }
 
 // SSHCertPath returns the path to the profile's ssh certificate.
 func (p *Profile) SSHCertPath() string {
-       return filepath.Join(p.SSHDir(), p.SiteName+constants.FileExtSSHCert)
+       return filepath.Join(p.SSHDir(), p.Username+constants.FileExtSSHCert)
 }
 
 // SSHCAsPath returns the path to the profile's ssh certificate authorities.
diff --git a/lib/client/keyagent_test.go b/lib/client/keyagent_test.go
index 133419a36..133daecf1 100644
--- a/lib/client/keyagent_test.go
+++ b/lib/client/keyagent_test.go
@@ -114,7 +114,7 @@ func (s *KeyAgentTestSuite) TestAddKey(c *check.C) {
                s.username,                            // private key
                s.username + constants.FileExtPub,     // public key
                s.username + constants.FileExtTLSCert, // Teleport TLS certificate
-               filepath.Join(s.username+constants.SSHDirSuffix, s.key.ClusterName+constants.FileExtSSHCert), // SSH certificate
+               filepath.Join(s.key.Username+constants.FileExtSSHCert), // SSH certificate
        }
        for _, file := range expectedFiles {
                _, err := os.Stat(filepath.Join(s.keyDir, "keys", s.hostname, file))
diff --git a/lib/client/keystore.go b/lib/client/keystore.go
index 2a4bfd74c..e6317a0a1 100644
--- a/lib/client/keystore.go
+++ b/lib/client/keystore.go
@@ -176,7 +176,7 @@ func (fs *FSLocalKeyStore) AddKey(key *Key) error {
        }
 
        // Store per-cluster key data.
-       if err := fs.writeBytes(key.Cert, inProxyHostDir(key.Username+constants.SSHDirSuffix, key.ClusterName+constants.FileExtSSHCert)); err != nil {
+       if err := fs.writeBytes(key.Cert, inProxyHostDir(key.Username+constants.FileExtSSHCert)); err != nil {
                return trace.Wrap(err)
        }
        // TODO(awly): unit test this.
@@ -384,9 +384,9 @@ var WithAllCerts = []CertOption{WithSSHCerts{}, WithKubeCerts{}, WithDBCerts{},
 type WithSSHCerts struct{}
 
 func (o WithSSHCerts) relativeCertPath(idx KeyIndex) string {
-       components := []string{idx.ProxyHost, idx.Username + constants.SSHDirSuffix}
+       components := []string{idx.ProxyHost}
        if idx.ClusterName != "" {
-               components = append(components, idx.ClusterName+constants.FileExtSSHCert)
+               components = append(components, idx.Username+constants.FileExtSSHCert)
        }
        return filepath.Join(components...)
 }
```

**Comment by flybyray** [comment]
> 
> 
> [v6.2.0...flybyray:patch-6956](https://github.com/gravitational/teleport/compare/v6.2.0...flybyray:patch-6956)
> 
> ```diff
> diff --git a/api/profile/profile.go b/api/profile/profile.go
> index 893ffa262..2881f6e36 100644
> --- a/api/profile/profile.go
> +++ b/api/profile/profile.go
> @@ -314,12 +314,12 @@ func (p *Profile) TLSCAsPath() string {
>  
>  // SSHDir returns the path to the profile's ssh directory.
>  func (p *Profile) SSHDir() string {
> -       return filepath.Join(p.UserKeyDir(), p.Username+constants.SSHDirSuffix)
> +       return p.UserKeyDir()
>  }
>  
>  // SSHCertPath returns the path to the profile's ssh certificate.
>  func (p *Profile) SSHCertPath() string {
> -       return filepath.Join(p.SSHDir(), p.SiteName+constants.FileExtSSHCert)
> +       return filepath.Join(p.SSHDir(), p.Username+constants.FileExtSSHCert)
>  }
>  
>  // SSHCAsPath returns the path to the profile's ssh certificate authorities.
> diff --git a/lib/client/keyagent_test.go b/lib/client/keyagent_test.go
> index 133419a36..133daecf1 100644
> --- a/lib/client/keyagent_test.go
> +++ b/lib/client/keyagent_test.go
> @@ -114,7 +114,7 @@ func (s *KeyAgentTestSuite) TestAddKey(c *check.C) {
>                 s.username,                            // private key
>                 s.username + constants.FileExtPub,     // public key
>                 s.username + constants.FileExtTLSCert, // Teleport TLS certificate
> -               filepath.Join(s.username+constants.SSHDirSuffix, s.key.ClusterName+constants.FileExtSSHCert), // SSH certificate
> +               filepath.Join(s.key.Username+constants.FileExtSSHCert), // SSH certificate
>         }
>         for _, file := range expectedFiles {
>                 _, err := os.Stat(filepath.Join(s.keyDir, "keys", s.hostname, file))
> diff --git a/lib/client/keystore.go b/lib/client/keystore.go
> index 2a4bfd74c..e6317a0a1 100644
> --- a/lib/client/keystore.go
> +++ b/lib/client/keystore.go
> @@ -176,7 +176,7 @@ func (fs *FSLocalKeyStore) AddKey(key *Key) error {
>         }
>  
>         // Store per-cluster key data.
> -       if err := fs.writeBytes(key.Cert, inProxyHostDir(key.Username+constants.SSHDirSuffix, key.ClusterName+constants.FileExtSSHCert)); err != nil {
> +       if err := fs.writeBytes(key.Cert, inProxyHostDir(key.Username+constants.FileExtSSHCert)); err != nil {
>                 return trace.Wrap(err)
>         }
>         // TODO(awly): unit test this.
> @@ -384,9 +384,9 @@ var WithAllCerts = []CertOption{WithSSHCerts{}, WithKubeCerts{}, WithDBCerts{},
>  type WithSSHCerts struct{}
>  
>  func (o WithSSHCerts) relativeCertPath(idx KeyIndex) string {
> -       components := []string{idx.ProxyHost, idx.Username + constants.SSHDirSuffix}
> +       components := []string{idx.ProxyHost}
>         if idx.ClusterName != "" {
> -               components = append(components, idx.ClusterName+constants.FileExtSSHCert)
> +               components = append(components, idx.Username+constants.FileExtSSHCert)
>         }
>         return filepath.Join(components...)
>  }
> ```

works only in special.
one day after expiry i got
```
ERROR: failed to fetch TLS key for username
open ~/.tsh/keys/<proxy host>/certs.pem: no such file or directory
```

**Comment by andrejtokarcik** [comment]
Would it suffice to add a symlink `~/.tsh/keys/<proxy>/<username>-cert.pub` pointing to the currently selected cluster cert?

**Comment by flybyray** [comment]
> Would it suffice to add a symlink `~/.tsh/keys/<proxy>/<username>-cert.pub` pointing to the currently selected cluster cert?

Yes that is currently my  workarround on Linux systems. But that would be difficult with windows systems ( not using WSL ).

**Comment by webvictim** [comment]
This also breaks some of our own OpenSSH guides which only list `KeyFile` in `~/.ssh/config` and rely on SSH's default behaviour of appending `-cert.pub` to the name of the `IdentityFile` to get the `CertificateFile`.

I've updated https://github.com/gravitational/teleport/discussions/5530 to handle this now but it blindsided quite a few people who weren't using/couldn't use `ssh-agent` along with `tsh login`.

**Comment by zmb3** [comment]
`tsh config` does the right thing now, so this is no longer an issue
