### ISSUE TITLE
Teleport Node install in Alpine linux

### ISSUE THREAD

**Issue by rphanikrishna** [gravitational/teleport#7008]
How do we configure a node in Alpine Linux 

 Since the code is for systemd any how to document for installing in openrc clients 

- Teleport version :6.2
- Server OS :Alpine linux 3.13
- Where are you running Teleport?: Homelab/Dedicated Hardware
- Additional details: any installation information for Alpine linux clients.

**Comment by rphanikrishna** [comment]
While executing 'teleport' am getting the below error messages
Error relocating /usr/local/bin/teleport: __memcpy_chk: symbol not found
Error relocating /usr/local/bin/teleport: __memset_chk: symbol not found

**Comment by rphanikrishna** [comment]
Which libc version dependency is there for teleport in Alpine linux ?

**Comment by webvictim** [comment]
Alpine Linux uses musl libc which is not supported by Teleport. You must use a distribution which implements glibc. Something like https://hub.docker.com/r/frolvlad/alpine-glibc/ should work.

**Comment by rphanikrishna** [comment]
Thank you @webvictim it help me and am able to run Teleport node in Alpine linux
