### ISSUE TITLE
tsh login --out does not work

### ISSUE THREAD

**Issue by gzigzigzeo** [gravitational/teleport#7014]
The following works fine:

```
tsh login --proxy evilmartians.teleport.sh:443 --user gzigzigzeo@evilmartians.com
```

But when I try to use `--out`, tsh reports error:
```
./build/tsh login --proxy evilmartians.teleport.sh:443 --user gzigzigzeo@evilmartians.com --out /tmp/id
Enter password for Teleport user gzigzigzeo@evilmartians.com:
Enter your OTP token:
*******
ERROR: no auth method available
```

- Teleport Cloud
- ```Darwin gzigzigzeos-MacBook-Air.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64```
- tsh: ```Teleport v7.0.0-dev git:v6.0.0-alpha.2-400-g3954ee48f go1.16.2```, ```Teleport v7.0.0-dev git:v6.0.0-alpha.2-554-gc15a980e2-dirty go1.16.2``` (latest built from source)

Tried to remove `~/.tsh` folder, no effect.

**Comment by corkrean** [comment]
A customer has also reported this issue. 

If you run `tsh login --out=file.pem ` before you have authenticated, you will not authenticate (see stack trace below) and no identity file will be created. If you run `tsh login --out=file.pem ` after you have authenticated the identity file will be created. 

Is it a bug or a feature that you must authenticate via `tsh login` before creating an identity file via `tsh login --out=file.pem`?

**Comment by stevenGravy** [comment]
This is working as expected now. Can't recreate these errors.
