### ISSUE TITLE
Improve cloud specific database access documentation

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#7020]
## Details

Database access guides should be more friendly to Cloud users. Currently, all guides assume self-hosted Teleport edition and, while the process for self-hosted and Cloud is very similar, Cloud users may feel lost.

Update the guides to help Cloud users get started with database access faster.

**Comment by ptgott** [comment]
Hi @r0mant, after the PRs in https://github.com/gravitational/teleport/issues/10637, is there any additional work that needs to be done on this issue?

**Comment by r0mant** [comment]
@ptgott No, I think we're good. Let's close this one.
