### ISSUE TITLE
Access Requests: Default Email notifications if plug-ins are not used.

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#7034]
### What
When a user creates an Access Request having an email notification sent to the approvers would be handy. That way if they do not have a tool like Jira, Slack, etc implemented they can still get an email that lets them know a new request has come in. 

### How

On creating the request it would generate an email that is sent to the approvers for the request. Approvers can click the approve/deny and/or view the request by clicking the link in the email (would open up their browser to request page).

### Why

For customers that do not have tools like Jira, Slack, etc implemented. This provides a basic notification for them to start using access requests without being logged into Teleport to approve it.

### Workaround

None. Approvers have to either use a plugin or stay logged into Teleport to see requests (or keep running `tctl requests ls`)

**Comment by webvictim** [comment]
I think this would still need to be implemented as a plugin, because emails are hard to send without proper SMTP servers etc being deliberately configured.

**Comment by Valien** [comment]
For on-prem for sure as clients will want to utilize their own SMTP/Exchange servers most likely. With cloud - possibly tie into an email API like Mailgun, SES, Sendgrid, etc?

**Comment by Valien** [comment]
On today's call @klizhentas mentioned to tag this as a potential plug-in request (i.e. build an email plug-in so that customers can leverage whichever email tool they want to send emails).

**Comment by Valien** [comment]
Related issue #6438

**Comment by wadells** [comment]
We have an access request plugin for email available: https://github.com/gravitational/teleport-plugins/tree/master/access/email

However, I do see that this plugin is missing from the workflows documentation:

https://github.com/gravitational/teleport/tree/8c2ced7e2bd14e6456b2eedf55c3b92a9242396e/docs/pages/enterprise/workflow

I'd expect we'd see a `ssh-approval-email.mdx`
