### ISSUE TITLE
Race condition during signup/creation of users

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#704]
While working on https://github.com/gravitational/teleport/issues/522 I found a race condition in user signup/creation.

### Problem

The [CreateUserWithToken](https://github.com/gravitational/teleport/blob/master/lib/auth/new_web_user.go#L152-L213) function has a race condition in it. Two requests can arrive to this function at the same time and because it is [no longer protected by locks](https://github.com/gravitational/teleport/commit/4ed536a2f02dc6246eb007d029d0efabd2f55623#diff-297d8bc443f3aa5a0263c97f741a9242) this can cause unexpected behavior.

For example, imagine two requests arrive to this function with a 1 ms difference. The second one will overwrite the password, role, user, and hotp models created by the first request because the signup token has not been deleted and all requests are upserts instead of creates.

The [GetSignupTokenData](https://github.com/gravitational/teleport/blob/master/lib/auth/new_web_user.go#L104-L119) function tries to mitigate this, but this approach is not sufficient as it itself is a [Time of check to time of use](https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use) bug.

### Solution

_Short term solution:_

In `CreateUserWithToken` instead of using `UpsertPassword`, `UpsertRole`, `UpsertUser`, and `UpsertHOTP` create functions `CreatePassword`, `CreateRole`, `CreateUser`, and `CreateHOTP` and use those instead. In addition, remove the check from `GetSignupTokenData` as it will no longer be needed.

_Long term solution:_

The short term solution solves the problem in this situation, however the current approach without locks will manifest race conditions whenever multiple models need to be updated atomically. Two potential solutions exist:

1. Reintroduce locks. Lock use can be restricted to security critical operations (like user creation) that are typically not done that frequently.

2. Consolidate all information needed for a user into a single model then perform compare and swap operations to atomically access it.

A combination of both is probably ideal. The second option will greatly simplify working with models and the first is unfortunately necessary anywhere concurrency can be an issue.

Thoughts?

**Comment by kontsevoy** [comment]
Is replacing `UpsertUser()` with `CreateUser()` enough? Sounds like it's the first thing we call and the 2nd competing request will get bounced right there. I would love to avoid backend-dependent locks, they're a pain and clearly unnecessary since the root cause of this is 'upsert' semantics.

**Comment by kontsevoy** [comment]
By the way the only place in Teleport where AcquireLock is necessary is [this](https://github.com/gravitational/teleport/blob/master/lib/session/session.go#L388). If we find a cheap way to get rid of it, we can remove these global locks completely.

**Comment by benarent** [comment]
@russjones I'm reviewing open issue with priority labels. Is this issue still relevant? Do you think this should be a P1 issue?

**Comment by russjones** [comment]
@alex-kovoy Did a bunch of refactoring around this, let's close it.

**Comment by gandhibhai** [comment]
I also found race condition in account creation vulnerability in a program of bugcrowd but they did not pay attention to me because I am only 14 years old.
