### ISSUE TITLE
Helm chart repo not showing latest charts

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7046]
### Description

**What happened**:

**What you expected to happen**:

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.
2.
3.

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by webvictim** [comment]
The charts are there, we just don’t use the Teleport version number at the moment pending changes to the release process.

We have to decide whether we really want to be bumping Teleport version and doing a full release every single time we make a Helm chart change. It seems overkill to me when we could just version the chart independently of the `appVersion`.

**Comment by klizhentas** [comment]
@webvictim it's easier for users, so they don't have to think about chart version vs teleport version. Same for kubectl vs kubernetes. They follow the exact same versioning process, but kubectl can work with some other versions too. Let's please align plugins, teleport, cloud and all other versions to be exactly the same.

**Comment by gclawes** [comment]
Agree with @klizhentas.  If the chart is versioned with teleport, changes to it are treated the same way feature releases in the code are.  In a production setting this is critical for preventing drift between the features of the software and the features of the helm chart.

I think of helm charts like RPM specs.  A change to the way an RPM is built is versioned as a new software release.

**Comment by webvictim** [comment]
Related to https://github.com/gravitational/teleport/issues/6887

**Comment by webvictim** [comment]
This has been fixed now - versioned Teleport charts are published along with Teleport releases.
