### ISSUE TITLE
Nodes not visible if no valid login exists

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#7051]
### Description

**What happened**:

Users with roles that have full node visibility (`'*' : '*'`) but no valid logins (either just `internal.logins` or something like `no-login-35q532452345-2352rwe235-235wdsfw`) are not able to see any nodes in the Servers menu until at least one valid login is added. 

**What you expected to happen**:

Users should still be able to see the nodes even if they do not have a login they can use to access the nodes. This is useful for cases such as auditors, reviewers...etc.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create user and tie to role that has either only `internal.logins` or some other non-valid login specified.
2. Confirm role has full node visibility with wildcard label matching.
3. Log in as user and observe that you cannot see any nodes.
4. Go back to role and add a valid login (anything will do here, even if it doesn't exist as a unix user on the end nodes)
5. Log back in and observe that you can now see all nodes as expected.

### Server Details
- Teleport version (run `teleport version`): 6.1.0+

**Comment by Valien** [comment]
Ran into this issue today with a customer. Nodes successfully joined but never showed up until a login was added. Needs to be added to the documentation as it is only shown in an example.

**Comment by TellTaleMajora** [comment]
Can confirm it occurred in version Teleport v7.2.0 git:v7.2.0-0-g513ed6735 go1.16.2  and did not see any errors other than the web page "No servers found"

Thankfully I found this thread.
