### ISSUE TITLE
Provide roles examples

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#7062]
## Details
The roles examples are spread out and targeted at specific usage across the documentation.  A more real-life comprehensive set of examples with advanced setting (regular expressions) would help to better understand how to use RBAC. 

### Category
- New Feature
- Improve Existing

**Comment by inertial-frame** [comment]
Following up: it isn't clear that our docs are comprehensive (contains all updated roles) nor singular (shows all such info in one spot).

1. Update our documentation in the Admin Guide, Architecture, and CLI reference to reflect all available types.
2. These should include:  `auth`, `trusted_cluster`, `proxy`, `node`, `app`, `kube`, and `db` (plus any others).
3. Any other places where this is relevant (probably not in articles that discuss the three primary Node modes).

**Comment by zmb3** [comment]
@stevenGravy the preset roles and a full role definition are documented here: https://goteleport.com/docs/access-controls/reference/?scope=enterprise

Is there anything else you'd like to see before we can close this one out?

**Comment by stevenGravy** [comment]
Examples are now in.
