### ISSUE TITLE
Implement Machine ID

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7066]
###

The original [RFD](https://github.com/gravitational/teleport/blob/master/rfd/0010-api.md#move-client-implementation-to-apiclient) mentioned credential loaders, but failed to specify how credentials will be rotated:

* [ ] Create an RFD that allows to subscribe to rotation state API (similarly to how nodes are doing it) and auto-rotate credentials. 
* [ ] This will allow all plugins to receive short lived certificates once and re-request new certificates before those expire. Once we create #4688, this will allow to lock out the rogue/obsolete clients.

**Comment by russjones** [comment]
Phase 1

- [x] Rebase off `master`.
- [x] Refactor to remove need for `types.Bot` resource.
- [x] Initial research/design into host certificate issuance.
- [ ] Create PR to update impersonation to support role only impersonation.
- [ ] Split renewable certificate and impersonated certificate.
- [ ] Initial research/design into file permissions.
- [ ] Add support for CA rotation.
- [ ] Add support for signal handling.
- [ ] Cleanup UX.

Phase 2

- [ ] Complete research into host certificate issuance.
- [ ] Create PR to add RPC for host certificate issuance.
- [ ] Add support for host certificate issuance.
- [ ] Complete research into file permissions.

**Comment by timothyb89** [comment]
PR tracking:

* Cert bot RFD: https://github.com/gravitational/teleport/pull/7986
* Role impersonation: https://github.com/gravitational/teleport/pull/9561

**Comment by zmb3** [comment]
Closing this one, as everything outstanding is tracked in separate issues.
