### ISSUE TITLE
Audit Log - Track Deleted Access Requests

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#7078]
### What
When the `tctl requests rm` command is performed this is not audited.

### How
Log this event when removing a request

### Why
To prevent bad actors from attempting to obfuscate their step

### Workaround
Compare initiation request with approval and deny requests

**Comment by yjperez** [comment]
Another possible solution is introducing a soft-delete which would have to be purged manually.

**Comment by Valien** [comment]
Another idea brought up today in a customer conversation: ability to see audit trailer of access requests in audit log. So even if a request is deleted and gone the audit trail will still be searchable/listed.
