### ISSUE TITLE
Remove hardcoded tokens 

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/teleport#7086]
## Details

Remove hardcoded join tokens and instead use token files: `--token=./token.file`.

For example like the step 2/4 here: https://goteleport.com/docs/server-access/getting-started/#step-24-add-a-node-to-the-cluster

### Category
- Improve Existing
- Remove Outdated

**Comment by klizhentas** [comment]
Great catch, but instead of fixing the docs I will submit a patch 

https://github.com/gravitational/teleport/blob/master/lib/utils/token.go#L30

**Comment by klizhentas** [comment]
Ok, here we go: https://github.com/gravitational/teleport/pull/7090

**Comment by inertial-frame** [comment]
It does - great catch `hasPrefix` looks for the exact start of the string, not a match: https://golang.org/pkg/strings/#HasPrefix!

**Comment by inertial-frame** [comment]
This has been updated in all Edit Passes as well. Thanks!
