### ISSUE TITLE
Create and validate the workflow for Teleport to access Cockroachdb servers.

### ISSUE THREAD

**Issue by fire** [gravitational/teleport#7101]
### What
What would you like Teleport to do differently?

Create and validate the workflow for teleport to access cockroachdb servers.

https://goteleport.com/docs/database-access/guides/postgres-self-hosted/

### How
How would you implement this?

Trust the Teleport CA as the CockroachDB root. ??? Then, Teleport can access cockroachdb servers.

### Why
Why do you need this?

I want to use Cockroachdb and Teleport.

### Workaround
Not that I know of.

**Comment by webvictim** [comment]
Related: https://github.com/gravitational/teleport/issues/1742

**Comment by r0mant** [comment]
CockroachDB is available in 8.0: https://goteleport.com/docs/ver/8.0/database-access/guides/cockroachdb-self-hosted/.
