### ISSUE TITLE
Build and publish terraform provider to our downloads page

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7104]
From what I see [here](https://github.com/gravitational/teleport-plugins/blob/master/.drone.yml#L171) terraform-provider is not built and published, please build and publish it alongside access plugins.

P.S. Foreseeing questions about publishing to official terraform registry, this is not a priority for us.

**Comment by webvictim** [comment]
https://github.com/gravitational/teleport-plugins/pull/248 merged support for building `terraform-provider-teleport` for `darwin/amd64` and `linux/amd64`.

https://github.com/gravitational/teleport-plugins/pull/249 handles the publishing of 6.2.1 (which will include the Terraform provider)
