### ISSUE TITLE
Empty internal kubernetes groups, users cause k8s access issue

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#7105]
### Description

**What happened**:
Having the default `'{{internal.kubernetes_users}}'` and `'{{internal.kubernetes_groups}}'` that are not populated add blank entries into the user's session.  Even if there are valid groups `system:masters` for k8s access the user is prevented due to these entries when attempting access. 

```yaml
kind: role
metadata:
  id: 1622385914405261600
  name: admin
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    db_names:
    - '{{internal.db_names}}'
    db_users:
    - '{{internal.db_users}}'
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    - system:masters
    kubernetes_labels:
      '*': '*'
    kubernetes_users:
    - '{{internal.kubernetes_users}}'
```

Note that below there is a kubernetes user entry even through it's blank.  Also the `,` before `system:masters`
```
> Profile URL:        https://teleport.example.com:443
  Logged in as:       steven
  Cluster:            ip-172-31-73-92
  Roles:              admin
  Logins:             root
  Kubernetes:         enabled
  Kubernetes cluster: "test6"
  Kubernetes users:   
  Kubernetes groups:  , system:masters
  Valid until:        2021-05-30 23:43:48 -0400 EDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```

The following error will occur when attempting to get access.

```
Error from server (InternalError): an error on the server ("Internal Server Error: \"/api/v1/namespaces/default/pods?limit=500\": requested [{Group      } {Group  system:masters    } {Group  system:authenticated    }] without impersonating a user") has prevented the request from succeeding (get pods)
```
If the user role has no empty internal values then it will work as expected.

**What you expected to happen**:

Blank entries are ignored for groups and users and not attempted for access.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Add to a `admin` role a valid group for k8s access (`system:masters`) with no entries for the local user for `kubernetes_group` or `kubernetes_user` for its user traits.
2. Install the helm chart on a k8s cluster
3. Attempt to interact.

### Server Details
- Teleport version (run `teleport version`): 6.2.1
- Server OS (e.g. from `/etc/os-release`): ubuntu
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS EC2

### Client Details
- Tsh version (`tsh version`): 6.2.1
- Computer OS (e.g. Linux, macOS, Windows): ubuntu

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

teleport kube agent logs:
```
[KUBERNETE] INFO Round trip: GET https://172.20.0.1:443/api?timeout=32s, code: 500, duration: 6.885573ms tls:version: 304, tls:resume:false, tls:csuite:1301, tls:server:remote.kube.proxy.teleport.cluster.local forward/fwd.go:185
[KUBERNETE] DEBU Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3024 reversetunnel/agent.go:439
[KUBERNETE] DEBU Received out-of-band proxy transport request for remote.kube.proxy.teleport.cluster.local [3ab66001-4c92-45eb-b72f-48636d7c3d3b.ip-172-31-73-92]. leaseID:1 target:teleport.example.com:3024 reversetunnel/transport.go:151
[KUBERNETE] DEBU Handing off connection to a local kubernetes service leaseID:1 target:teleport.example.com:3024 reversetunnel/transport.go:192
            DEBU Ignoring unsupported cluster name name "remote.kube.proxy.teleport.cluster.local". proxy/server.go:204
[AUTH]      DEBU ClientCertPool -> cert(ip-172-31-73-92 issued by ip-172-31-73-92:1410546591381521537732037332880173364) auth/middleware.go:593
[AUTH]      DEBU ClientCertPool -> cert(ip-172-31-73-92 issued by ip-172-31-73-92:132465604809741175036259237226716266744) auth/middleware.go:593
[KUBERNETE] DEBU Handling kubernetes session for user: steven, users: map[:{}], groups: map[:{} system:authenticated:{} system:masters:{}], teleport cluster: ip-172-31-73-92, kube cluster: test6 using local credentials. proxy/forwarder.go:1436
[KUBERNETE] INFO Round trip: GET https://172.20.0.1:443/api?timeout=32s, code: 500, duration: 6.283264ms tls:version: 304, tls:resume:false, tls:csuite:1301, tls:server:remote.kube.proxy.teleport.cluster.local forward/fwd.go:185
```

**Comment by timothy-spencer** [comment]
Do you have a good workaround for this?  I have tried doing a `tctl get roles > roles.yaml`, editing that to take out the offending lines, and then `tctl create -f roles.yaml`, but I still have the empty group in there when I do a `tsh status` or `tsh login`.

**Comment by timothy-spencer** [comment]
Nevermind.  I found out that you have to log out and back in after editing the role to take out the `internal.kubernetes_groups` lines for it to work.  So that's a workaround!

**Comment by timothy-spencer** [comment]
Oh, looks like you need to get rid of `internal.kubernetes_users` too.

**Comment by pierreyves-lebrun** [comment]
Does the teleport team need help to resolve this bug?
