### ISSUE TITLE
chart: Chart.yaml version field is not Semver 2.0

### ISSUE THREAD

**Issue by gclawes** [gravitational/teleport#7106]
### Description

**What happened**:
Helm expects the `version` field of `Chart.yaml` to be [Semver 2.0](https://semver.org/) formatted.  The current version is `6`, which violates this.  Breaking this breaks certain helm tools, such as `helmsman`

https://semver.org/#spec-item-2
> 2. A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

https://helm.sh/docs/topics/charts/#the-chartyaml-file

Issue that arises with `helmsman` when using `version: 6`:
```
2021-05-30 23:01:40 INFO: Acquiring current Helm state from cluster
panic: runtime error: slice bounds out of range [:-1]

goroutine 118 [running]:
github.com/Praqma/helmsman/internal/app.(*helmRelease).getChartName(0xc000552ca8, 0xc000138b08, 0x8)
        /go/src/github.com/Praqma/helmsman/internal/app/helm_release.go:97 +0x13d
github.com/Praqma/helmsman/internal/app.(*currentState).inspectUpgradeScenario(0xc0001a2048, 0xc0005563c0, 0xc000215500, 0xc000612180, 0xc0007c0101, 0xd38380)
        /go/src/github.com/Praqma/helmsman/internal/app/decision_maker.go:318 +0x5c5
github.com/Praqma/helmsman/internal/app.(*currentState).decide(0xc0001a2048, 0xc0005563c0, 0xc000528580, 0xc000215500, 0xc000612180)
        /go/src/github.com/Praqma/helmsman/internal/app/decision_maker.go:122 +0x267
github.com/Praqma/helmsman/internal/app.(*currentState).makePlan.func1(0xc000620570, 0xc00056c000, 0xc0001a2048, 0xc000556000, 0xc000215500, 0xc0005563c0, 0xc000612180)
        /go/src/github.com/Praqma/helmsman/internal/app/decision_maker.go:80 +0xe5
created by github.com/Praqma/helmsman/internal/app.(*currentState).makePlan
        /go/src/github.com/Praqma/helmsman/internal/app/decision_maker.go:74 +0x212
```
A similar issue was reported in helmsman with dots in the chart name: https://github.com/Praqma/helmsman/issues/229#issuecomment-481620372.

I tested migrating chart version `0.0.4` to `6`, which uncovered this issue above.  I do not believe an issue in Praqma/helmsman is warranted, as it is behaving as expected.

**What you expected to happen**:
`Chart.yaml` `version: 6` should be `version: 6.0.0` or `version: 0.0.6`

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Use [helmsman](https://github.com/praqma/helmsman) to install `teleport-kube-agent` chart version `0.0.4`: 
To install: `helmsman -f helmsman.yaml --install`
Example helmsman.yaml state file (fill in your own `<proxy>` `<cluster name>` `<token>`:
```
helmRepos:
  teleport: https://charts.releases.teleport.dev

namespaces:
  teleport: {}

apps:
  teleport:
    name: teleport
    chart: teleport/teleport-kube-agent
    version: 0.0.4
    namespace: teleport
    enabled: true
    priority: -5
    valuesFile: teleport-values.yaml
    secretsFile: teleport-secrets.yaml
    setString:
      proxyAddr: "<proxy>"
      kubeClusterName: "<cluster name>"
      teleportVersionOverride: "6.2.1"
      authToken: "<token>"
```
2. Change version to `6` and run `helmsman -f helmsman.yaml --apply` (expected to work).
3. Run helmsman again without `--install` to check state (expected to fail due to bad version): `helmsman -f helmsman.yaml`

### Server Details
- Teleport version (run `teleport version`): 6.2.1
- Server OS (e.g. from `/etc/os-release`): k3s 1.21.1
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Kubernetes
- Additional details:

### Client Details
- Tsh version (`tsh version`): N/A
- Computer OS (e.g. Linux, macOS, Windows): N/A
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): helm chart
- Additional details:

**Comment by gclawes** [comment]
Related: #5582 #7046

**Comment by webvictim** [comment]
The charts in the repo will be fixed at the same time as #7046. They'll inherit the same version as the release tag.

We still need a solution for `master`, which uses `6` as its version currently. I think the easiest proposal is that after we start cutting Helm repo charts from release tags, we change the version on `master` to be `7.0.0-dev` (to comply with semver) but leave the `appVersion` field as `6` (which means there will always be a Docker image available, as we don't build/publish Docker images from `master`)

**Comment by gclawes** [comment]
Yeah, I could see keeping the simple `appVersion: 6`  for master, as long as releases had the more specific version numbers.


This may or may not be slightly off topic, let me know if you want another issue opened for it:
I noticed the teleport charts have a somewhat unusual use of the repository/tag values and `appVersion` in the form of the `teleportVersionOverride` value, that's significantly different from the default helm recommends and that other charts out in the wild use.

If you run `helm create <chart name>` with a recent version of helm, the default templates will populate the image fields like this:
```
image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
```
From default values looking like this:
```
image:
  repository: <image repo>
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
```

Compare this to the current setup (from `teleport-kube-agent`):
```
{{- if .Values.teleportVersionOverride }}
  {{- $_ := set . "teleportVersion" .Values.teleportVersionOverride }}
{{- else }}
  {{- $_ := set . "teleportVersion" .Chart.Version }}
{{- end }}
...
        image: "{{ if .Values.enterprise }}{{ .Values.enterpriseImage }}{{ else }}{{ .Values.image }}{{ end }}:{{ .teleportVersion }}"
```
and values.yaml:
```
# Version of teleport image, if different from appVersion in Chart.yaml.
teleportVersionOverride: ""
...
# Container image for the agent. Since this runs without the auth_service, we
# don't need the enterprise version.
image: quay.io/gravitational/teleport
```

In my view at least, it would make sense for teleport charts to behave more like other charts out in the wild, and may make it easier to deal with the `appVersion` field.

**Comment by webvictim** [comment]
I think at the time this chart was written, we still didn't really have a clearly defined sense of how the `.Chart.AppVersion` field could be used in relation to the charts. Now we do, your suggestion makes a lot more sense. Unfortunately we'll probably still need to support `.Values.teleportVersionOverride` for a while but we can make some changes to use that interchangably with `.Values.tag` during the migration.

**Comment by webvictim** [comment]
Related to https://github.com/gravitational/teleport/issues/6887

**Comment by webvictim** [comment]
This should be resolved now as we're releasing charts along with Teleport versions, so the version field will always be semver formatted.
