### ISSUE TITLE
Lack of AMIs for me-south-1

### ISSUE THREAD

**Issue by Upgreydd** [gravitational/teleport#7122]
### Description
No AMI for Bahrain.
No me-south-1 image for Teleport.

**Comment by webvictim** [comment]
As per https://github.com/gravitational/teleport/blob/master/assets/aws/Makefile#L25-L29, we only publish Teleport AMis to non-opt-in regions (i,e. those which are available to all AWS customers by default).

You can see a list of regions along with their opt-in status [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html).

If you need an AMI in `me-south-1`, please create it yourself using Packer or copy it from one of the regions in the list.
