### ISSUE TITLE
Allow configurability of TTL parameter for db/server/kube agent ageout

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#7129]
### What
It would be nice to be able to configure and modify the TTL used for db/server/kube agent aging out, specifically for testing environments and environments with a lot of ephemeral agent connections which may come and go throughout the hour. 

### How
Ideally as a config variable in the .yaml config file, but also would be nice to have it as a flag that could be passed on agent join.

### Why
A number of customers have requested this feature to make administration of environments which run ephemeral agents easier. Likewise, it would be useful for troubleshooting and stabilizing container environments with connectivity issues where an agent may try to re-register after going down but the previous agent has not yet aged out. Being able to force the previous agent to age out in a faster time-period would hep avoid connectivity issues as observed in some kube environments.

**Comment by russjones** [comment]
@Aharic Can you share this with ticket with customers https://github.com/gravitational/teleport/issues/7263, specifically the route to most recent idea that @fspmarshall suggested?

**Comment by Aharic** [comment]
Resolved by fixes mentioned in RJs comment above. Closing as such.
