### ISSUE TITLE
Search API downloads entire DB when querying for "event.name" field

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#7143]
Currently, when using SearchEvents API to query the events, auth service downloads entire DB (page by page) while trying to complete client side filtering based on the `event.name` field. For customers who have gigabytes of data this approach does not scale and will result in timeouts (at best).

https://github.com/gravitational/teleport/blob/master/lib/events/dynamoevents/dynamoevents.go#L775

```go
accepted := false
for i := range eventTypes {
	if e.EventType == eventTypes[i] {
		accepted = true
		break
	}
}
if accepted || !doFilter {
	values = append(values, e)
	left--
	if left == 0 {
		break dateLoop
	}
}
```			

While we are waiting for a more sophisticated solution, meanwhile I suggest the following:
1. Do not support searching on multiple `event.name` values, use only `equal` operator for DynamoDB backend. Return an error if multiple event.names are passed.
2. When event.name is specified, make it part of the query. It wont be fast but much faster than it is now (then we can add a secondary index).

I am sure _nobody_ used this API before, so there wont be any breaking changes to existing customers.

The Teleport Web UI (especially Recored Sessions) needs this fix because we cannot display the list of recorded sessions without it (or without _downloading_ entire DB by the auth service)

![pagination](https://user-images.githubusercontent.com/43280172/119589210-31e11000-bd87-11eb-9c3b-ef9f84693d85.gif)

**Comment by xacrimon** [comment]
Okay, I've delved into the problem and I have some thoughts. I suggest that we as soon as possible start filtering events on the DynamoDB side using filter expressions and arrays. This is not the most efficient solution possible but it easily allows us to filter by multiple event types without pulling all the data which is significantly better.

Eventually I want to introduce some other clever way to perform filtering but this should make it workable in the near future. Sounds good? @alex-kovoy

**Comment by xacrimon** [comment]
Opened #7231 implementing this strategy.
