### ISSUE TITLE
Safe to download? Safe to install?  Sigs?  Shasums?

### ISSUE THREAD

**Issue by jeff-nulogy** [gravitational/teleport#715]
Got some tips or best practices around installing _safely?_ We'd like to make sure nothing's tampered with on the way to our sacred servers.  Don't see any sums on your downloads page or signed commits or anything on this project.  Perhaps I'm blind...

The paranoia is strong when considering replacements for sshd.

**Comment by klizhentas** [comment]
@jeff-nulogy we need to improve our distribution for sure. Meanwhile the most reliable way is to build from sources as long as you trust github and use your own signing/checking.

**Comment by kontsevoy** [comment]
@jeff-nulogy we have chosen to rely on Github here, if Github is compromised the attacker can change anything in Github releases, including hashes, so shasums or signatures are not going to make you more secure _as long as they are posted only on Github_. 

To make these tools effective we need to duplicate release notes from the Releases tab on our website or, even better, get into Linux distros (in progress).

**Comment by kontsevoy** [comment]
@jeff-nulogy closing this and will start publishing sha1sum on releases page.
