### ISSUE TITLE
Enhanced telemetry reporting 

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#7172]
### What

A few customers have requested enhanced telemetry reporting on Teleport nodes. Among the requests have been asks for easier reporting/gathering of teleport version running on nodes that can be used to more easily verify successful upgrades in a cluster running hundreds or thousands of nodes.

### Why

Customer request to make upgrades and management easier.

### Workaround

Currently customers can either append labels to nodes via dynamic command such as `command: ["/bin/sh", "-c", "teleport version | cut -d ' ' -f 3"]` or run a tctl command such as `tctl get nodes | egrep -i 'hostname: |version' | grep -vi 'v2'`

**Comment by zmb3** [comment]
I believe this has been deprecated by @fspmarshall's inventory work with automatic upgrades.
