### ISSUE TITLE
Add a guide for non-interactive database access users

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#7183]
## Details

Some users want to use database access with their CI systems or other robot accounts.

We need to add a guide for it that would explain how to:

* Generate user's identity file using `tctl auth sign`.
* Use it with `tsh db login` command to fetch credentials.
* Connect to the database from automation system.

**Comment by ptgott** [comment]
@r0mant Does the [Machine ID with Databases](https://goteleport.com/docs/machine-id/guides/databases/) guide resolve this?

**Comment by ptgott** [comment]
Closing since we have a guide to using Machine ID with databases.
