### ISSUE TITLE
SOC 2 compliance doc section

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7186]
## Details

https://docs.google.com/document/d/1sQ8kE26W8cyiye7EMXYL6S9wXZ9S3gB2Rct-9Zvccv8/edit#

**Comment by inertial-frame** [comment]
We previously discussed: https://github.com/gravitational/teleport/issues/6706 and creating a new Security Article under the Architecture Section.

This might be a prime candidate for that along with some of the SSH Hardening subsection (in the new SSH article, can be broken into an include and placed in both), Bastion Pattern, and Short-Lived certificate best practices.

**Comment by ptgott** [comment]
@klizhentas Since we have added [this page](https://goteleport.com/how-it-works/soc2-ssh-kubernetes/) to the main site, is there any more work that needs to be done on this issue? Thanks

**Comment by ptgott** [comment]
Closing since we now have a page on SOC 2
