### ISSUE TITLE
Allow privileged user to join any active session

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#7188]
### What

Currently, a user can only join a session if they have access to the login being utilized.

### How

Either allow regex/globbing in the logins list, or add a new permission to allow joining sessions that meet certain criteria.

### Why

A privileged teleport user may need to join existing sessions for various reasons-- training, real-time auditing, assisting a lower level tech with a task, etc.

### Workaround

The current workaround is to manually list out allowed logins and ask the privileged user to log out and log back in if that list needs to change. That also has the side effect that the privileged user could initiate new sessions as those others users rather than just joining an existing session. --not an ideal workaround

**Comment by zmb3** [comment]
We might be able to close this based on the moderated sessions support in v9.

@programmerq @xacrimon what do you think?

**Comment by xacrimon** [comment]
@zmb3 I think so, join policies allow you to specify what sessions you can join based on a role of the session creator. Logins are not required anymore as on Teleport 10.
