### ISSUE TITLE
UX issues with getting started

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7199]
### Description

Following docker getting started guide, users encountered these issues:

* [x] Node terminology is not explained, could be anything. Users are confused
* [x] The fact one has to connect to ssh endpoints using "tsh" client is not obvious. Users also don't know that they can connect using openssh
* [x] docker-compose -f teleport-quickstart.yml up -d command has no /etc/teleport.yml to configure. That only applies to native installs
* [x] After following setup users stuck on X.509 self signed issue:
tsh login --proxy=x.x.x.x.:3080 --user=testuser
ERROR: Get "https://x.x.x.x.x:3080/webapi/ping": x509: certificate is valid for 127.0.0.1, 172.18.0.3, ::1, ::1, not x.x.x.x

This could be solved with quick --insecure (OK for local dev) 

* [x] How to add SSH nodes (what's next) is unclear

**Comment by inertial-frame** [comment]
@travelton - adding you.

**Comment by inertial-frame** [comment]
Updated the PR #7225 to include `tsh` instructions using the `--insecure` flag.
