### ISSUE TITLE
Validation Pass 6.2+

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/teleport#7259]
## Details

We've done a great job improving the quality of our Documentation with new UI/UX components, editing, better layout and organization, easier samples, and so on. 

We've previously relied almost exclusively on three points of Documentation validation:

1. PR reviews.
2. Spot-checking - very specific tickets aimed at correcting a single command or the like.
3. Authorship - validation when writing the article.

Many teams distinguish between two kinds of routine Documentation/Technical Writing work that they typical alternate between (in addition to writing code samples, writing new articles, API testing, etc.):

**1. Edit Passes** are intended to _**bring every article up to a basic standard of styling and so on**_. If we can get a bunch of easy fixes in we will but that's a secondary aim. 

- This is not trivial since phrasing, branding, promises, etc. can convey things with legal implications. 
- Lowered Flesch-Kincaid scores reduce customer satisfaction and increase bounce rates. 
- Our bounce rates have been higher than we want and are increasingly in the range that we'd want (somewhere < 40% or thereabouts is fairly commonly accepted as a reasonable metric).
- This is akin to "Editing".
- Address many smaller issues during the process.

**2. Refresh/Validation Passes** is the (re)validation of articles that **_have already gone live and have previously been validated and signed off on by others._**

- During this process, steps are more closely examined, revalidated, examples corrected, images and so on fixed.
- This is closer to "Quality Assurance" - Manual Product Validation to supplement Engineering Integration, Regression, and Unit Testing.
- This is probably the most time-consuming aspect of routine Documentation work.
- When there's nothing else in a backlog this is the default thing to be doing.

With the conclusion of the Edit Passes for 6.1, 6.2, and 7.0 in sight, we can prioritize the **Refresh/Validation**.  Also, it's unlikely that major editing will be required 6.2+ since we will port all of our editorial changes forward.

We will prioritize Guides and Getting Started documents first. Then come back to update Reference and Configuration documentation:

1. We are already updating our Reference and Configuration documentation. This is more likely to updated and changed during routine Engineering PR's than Guides and Getting Started steps.
2. Guides and Getting Started are often the first point of entry into our Documentation but often the least validated (gets written then neglected).
3. One benefit of the redundant Configuration and Reference examples that we have is that finding an answer to Reference and Configuration issues is likely easier to find than figuring out how to Get Started after some command breaks the setup flow.
4. A lot of Configuration and Reference documentation improvements were also made during the Edit Pass: https://github.com/gravitational/teleport/issues/6943

### Category

- New Feature
- Improve Existing
- Remove Outdated

**Comment by inertial-frame** [comment]
----

Checkmarks indicate that steps were verified or config updated previously (here or in addressing other issues/PR's). 

Does not include Edit Pass editorial items. Does not include planned additions or Reference Documentation (like adding required fields to CLI documentation) - just validation of existing steps and config (we will scope other PR's and Issues to address those).

Some items may still need updating but this pass will hopefully cover nearly all updates (aside from pending code changes and the like):

- [ ] Home Section
    - [x] Getting Started
    - [ ] Installation
    - [ ] Production Guide
- [x] Setup Section
    - [x] Guides
        - [x] Terraform Provider
        - [x] Local Docker
- [ ] Application Access Section
    - [ ] Getting Started
    - [ ] Guides
        - [ ] Connecting Web Apps
        - [ ] Integrating with JWTs
        - [ ] Application API Access
- [x] Server Access Section
    - [x] Getting Started
    - [x] Guides
        - [x] Using Teleport with PAM
        - [x] OpenSSH Guide
- [ ] Kubernetes Access Section
    - [ ] Getting Started
    - [ ] Guides
        - [ ] Multiple Clusters
        - [ ] CI/CD
        - [ ] Federation
        - [ ] Migration
        - [ ] Standalone
    - [ ] Helm Guides
        - [x] AWS EKS Cluster
        - [x] Google Cloud GKE Cluster
        - [ ] Customize Deployment Config
        - [ ] Migration From Older Charts
    - [ ] Helm Chart Reference
    - [ ] Access Controls
- [ ] Database Access Section
    - [ ] Getting Started
    - [ ] Guides
        - [ ] AWS RDS/Aurora PostgresSQL
        - [ ] AWS RDS/Aurora MySQL
        - [ ] AWS Redshift PostgresSQL
        - [ ] GCP Cloud SQL PostgresSQL
        - [ ] Self-Hosted PostgreSQL
        - [ ] Self-Hosted MySQL
        - [ ] Database GUI Clients
- [ ] Access Controls Section
    - [ ] Getting Started
    - [ ] Guides
       - [ ] Role Templates
        - [ ] Second Factor - U2F
        - [ ] Per-session MFA
        - [ ] Dual Authorization
        - [ ] Impersonation
- [ ] Infrastructure Guides Section
    - [ ] AWS
    - [ ] AWS Terraform
    - [ ] GCP
    - [ ] IBM
- [ ] Teleport Enterprise Section
    - [ ] Quick Start Guide
    - [ ] Single Sign-On (SSO)
        - [ ] Azure Active Directory (AD)
        - [ ] Active Directory (ADFS)
        - [ ] Google Workspace
        - [ ] GitLab
        - [ ] OneLogin
        - [ ] OIDC
        - [ ] Okta
    - [ ] Access Requests
        - [x] Integrating Teleport with Slack
        - [ ] Integrating Teleport with Mattermost
        - [ ] Integrating Teleport with Jira Cloud
        - [ ] Integrating Teleport with Jira Server
        - [ ] Integrating Teleport with PagerDuty
- [ ] Cloud Section
    - [ ] Getting Started
- [ ] Advanced Features Section
    - [ ] Enhanced Session Recording
- [x] Reference Section
    - [x] API
        - [x] Teleport API Introduction
        - [x] Getting Started
        - [x] API Architecture

**Comment by inertial-frame** [comment]
Setup and configuration steps for Cloud, hosted, etc. is here: https://docs.google.com/document/d/1C8CT-JSFpRcxPxfP1zX4a-LwTb5NKlWyG0mk4f6q5MI/edit# - some of these will be added to the existing documentation (above) and is also a planned expansion to the Setup Section.

**Comment by ptgott** [comment]
Going to close this, as it's now a few versions behind.
