### ISSUE TITLE
Cluster bootstrapping clairification

### ISSUE THREAD

**Issue by vancluever** [gravitational/teleport#726]
Hey all,

From what I can gather, the docs on clustering mainly detail:

 * How to use a shared storage backend
 * How to have nodes join an existing cluster via known auth servers and pre-configured tokens (latter if desired)

However, the docs don't really detail the following:

 * How to bootstrap an auth cluster. In say something like an AWS ASG, the reality is that auth servers will start without any knowledge of each other, so they will not know what address to join and further to that may create a split brain as they would start up at the approximately the same time, see a nonexistent cluster and do the needful to attempt to initialize it. I'm not too sure what kind of implications this has on a shared backend.
 * What to use as an auth server in a HA scenario when adding a new node. If one is using the individual auth server nodes to join, there needs to be a discovery system in place, a dynamically updated DNS record, or a LB endpoint (not too sure if this would work with auth servers though). At the moment, for this, I'm thinking of scripting something together that mimics the [`retry-join-ec2`][1] flags in Consul, where hosts are discovered via a specific EC2 tag from which a host list is constructed to join. I'm also debating using this to help cluster the auth servers, but I'm still worried about the bootstrapping issues I mentioned above.

[1]: https://www.consul.io/docs/agent/options.html#_retry_join_ec2_tag_key

It would be nice to have some docs for the latter two scenarios, so that there is some direction. One thing I'm curious about is how the bootstrapping process works in Teleport - do auth servers in the same cluster with shared storage (ie: etcd or Dynamo) need to know about each other beforehand? Can a cluster be bootstrapped by just starting up multiple servers at once or does the bootstrap process need to be handled by one server before other auth servers join the cluster? Et cetera.

Any help would be appreciated!

**Comment by kontsevoy** [comment]
Sure, the docs need to be better (as always). But to answer your question, the bootstrapping sequence is:

1. Start the 1st auth server. Configure it to have a static "join token".
2. Start the 2nd auth server and tell it to join the 1st with the token.

**Comment by vancluever** [comment]
Great detail and answers pretty much all of my questions and makes my life much easier :) thanks @kontsevoy!

Will leave open as I see you've tagged it :)

**Comment by vancluever** [comment]
Hey @kontsevoy, just going to close this issue now (should serve as an easy reference for people looking for info regarding this topic still). Thanks again for the info and all the awesome work on Teleport!
