### ISSUE TITLE
Update automatic node join script to support databases

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#7262]
### What

Update our existing script for joining nodes to support bringing up database service agents as well.

### Why

To make it easier to start database proxies with a single command.

**Comment by zmb3** [comment]
@r0mant I assume we can close this one as automatically joining DBs will be revisited for Teleport Discover.

**Comment by r0mant** [comment]
https://github.com/gravitational/teleport/issues/17446 duplicate.
