### ISSUE TITLE
Migrate to dedicated Algolia Account.

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#7273]
### What
We've been using the awesome DocsSearch project for a bit https://github.com/algolia/docsearch-configs/blob/master/configs/goteleport.json but it only provides us limited control over indexing and editing of results.

We should move to a dedicated account. To do this, we need to 

1. Signup for an account ( @TravisGary ) 
2. Setup our own DocSearch crawler. https://docsearch.algolia.com/docs/run-your-own/#run-the-crawl-from-the-docker-image This can be done as part of Docs CI/CD Process

### Why
For better control over the crawl and search options.

### Workaround
If a workaround exists, please include it.

**Comment by inertial-frame** [comment]
Related:

1. https://github.com/gravitational/teleport/issues/6014
2. https://github.com/gravitational/teleport/issues/6704

Wonder if the new account will help address those?

**Comment by ptgott** [comment]
We are now tracking search-related issues in `gravitational/docs`, so I am closing this.
