### ISSUE TITLE
Build K8s Operator (operatorhub.io)

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#7279]
### What
As our Helm charts improve it would be nice to see an Operator built for Teleport. This can potentially simplify installs, deployments, and support for customers.

### How
Leverage best practices defined for K8s operators and publish an operator on www.operatorhub.io

### Why
Extend the capabilities of Teleport for our customers and provide Day 1/2 operations support ease of use.

### Workaround
Currently we only have Helm charts which are awesome but could grow (and Operatorhub does support Helm charts as well).

**Comment by zmb3** [comment]
@r0mant can we close this one?

**Comment by zmb3** [comment]
Closing at not planned. If we do someday decide to publish to operatorhub it will be because of new information or requests, not because of this old buried issue :-)
