### ISSUE TITLE
Reference Terraform index format is out of sync with Teleport itself

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#7306]
We define the old `timesearch` index schema in our reference `ha-autoscale-cluster` Terraform: https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/ha-autoscale-cluster/dynamo.tf#L56-L63

This causes issues with Teleport 6.2+ which migrates indexes to a newer `timesearchv2` format.

Example output with issues:

```
Terraform v1.0.0
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
...
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.teleport-ha-autoscale-cluster.aws_dynamodb_table.teleport_events has been changed
  ~ resource "aws_dynamodb_table" "teleport_events" {
        id             = "infra-dev-events"
        name           = "infra-dev-events"
        tags           = {
            "TeleportCluster" = "infra-dev"
        }
        # (7 unchanged attributes hidden)

      + attribute {
          + name = "CreatedAtDate"
          + type = "S"
        }
      - attribute {
          - name = "EventNamespace" -> null
          - type = "S" -> null
        }

      + global_secondary_index {
          + hash_key           = "CreatedAtDate"
          + name               = "timesearchV2"
          + non_key_attributes = []
          + projection_type    = "ALL"
          + range_key          = "CreatedAt"
          + read_capacity      = 10
          + write_capacity     = 10
        }
      - global_secondary_index {
          - hash_key           = "EventNamespace" -> null
          - name               = "timesearch" -> null
          - non_key_attributes = [] -> null
          - projection_type    = "ALL" -> null
          - range_key          = "CreatedAt" -> null
          - read_capacity      = 20 -> null
          - write_capacity     = 20 -> null
        }
```

Applying this `terraform plan` would result in the new indexes (created by Teleport) being deleted and the old indexes (managed by Terraform) restored, which would likely break Teleport behaviour completely.

This will potentially affect any customer who is configuring their Teleport infrastructure using Terraform, so should be addressed as a matter of priority. The reference Terraform needs to be updated to handle the new index format.

We should either:
- modify the Terraform to have the new index format (risky because if customers deploy using the updated version and are running a pre-6.2.x Teleport version, their deployment may break)
- remove the index/DynamoDB definitions from Terraform examples entirely, as Teleport is in control of them. This could be a destructive operation for customer clusters, so the current index definitions should be replaced with appropriate `lifecycle` directives to ignore existing indexes and not destroy them.

See https://github.com/gravitational/cloud/issues/718 for further context.

**Comment by jeffjen** [comment]
Migration script should be handled outside of production code.

The way we had to address this is

1. Create GSI index timesearchV2 via TF
2. Run Auth Server at v6.2
3. Wait until complete, which results in GSI timesearch removed
4. Patch TF to mark GSI timesearch and Attr EventNamespace removed

This should be clearly addressed in migration plan, in the documentation, in the release note.
