### ISSUE TITLE
`GetChecker` does not work with remote cert authorities

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#732]
## Description

Steps to reproduce:

* Create cluster `a` and `b`
* Cluster `a` should be a proxy to `b`
* Create user on cluster `a` -> `bob`
* `tsh --cluster=b --proxy=cluster-a ls` will not work because of `GetUser` in cert checker will fail as user `bob` is not found.

**Comment by kontsevoy** [comment]
To reproduce you can simply:
```
$ cd vagrant && vagrant up
$ vagrant status
```

This will give you two clusters: `a-auth` and `b-auth`.
... and then you have to `tctl -c /opt/teleport.yaml auth export` on both machines.

P.S. vagrant sometimes hangs when waiting on the network, re-starting `up` helps.
