### ISSUE TITLE
Add more SSO Customization styles/icons

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#7325]
### What

Teleport has the ability to display icons for github, okta, microsoft, google, bitbucket, and openid. Additional options would be appreciated. In particular, duo and auth0 would be appreciated. The ability to add custom icons/colors would also be appreciated.

### How

If adding only a few more custom styles, I would just add more to the list in the code so there are more choices.

If a custom icon/color were to be supported, I would extend the connector yaml to have a field for the color code, and perhaps a base64 encoded image.

### Why

This will improve the user experience so users can be a little more confident that they will be presented with a login page for the particular auth service in question.

### Workaround

No workaround

**Comment by bxker** [comment]
@benarent @programmerq I feel like this issue and #3896 fell off. Or, I can not find any new issues tracking this. I believe this would be a simple QoL update to the platform.

Context: we currently use the Google SSO OIDC connector and I keep getting questions why Teleport has a Google Plus icon for login. I don't have any answers and I feel as if it questions legitimacy while logging in for our end users.

**Comment by zmb3** [comment]
Closing in favor of #36883
