### ISSUE TITLE
Add a PodDisruptionBudget to Helm Charts

### ISSUE THREAD

**Issue by tghaas** [gravitational/teleport#7330]
### What
I'd like a PodDisruptionBudget added to the Helm Charts as a definable option in teleport-cluster and probably teleport-kube-agent

### How
Add a pdb.yaml to the templates directory that would be enabled and take options from the values.yaml file.

### Why
With cluster auto scaling enabled this would ensure that there are always X pods available to service requests.

### Workaround
If a workaround exists, please include it.

I'm happy to submit a PR for this.

**Comment by webvictim** [comment]
#7138 addresses this.
