### ISSUE TITLE
Duplicate databases when agent is restarted

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#7342]
### Description

**What happened**:

If a Teleport node with a `database_service` is restarted the same databases are repeated for 10-15 mins.  

```bash
 tsh db ls
Name        Description         Labels Connect
----------- ------------------- ------ --------------------------------------------------------------------------
> db01 'Aurora db'        psql "service=teleport-cluster-01-db01 user=<user> dbname=<database>"
> db01 'Aurora db'        psql "service=teleport-cluster-01-db01 user=<user> dbname=<database>"
```

**What you expected to happen**:

Only a single entry of a database name that will use the agent that is active.  If a agent is stopped the expectation is those dbs could automatically be removed. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.  Configure a agent with `database_service` and connect to a Teleport cluster
2. List the databases
3. Restart the database agent
4. List and confirm the database is repated

### Server Details
- Teleport version (run `teleport version`): 6.2.3
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by r0mant** [comment]
This issue was addressed as a part of HA tweaks work (https://github.com/gravitational/teleport/pull/7293), will be a part of 7.0.
