### ISSUE TITLE
OIDC user login fail

### ISSUE THREAD

**Issue by Wiston999** [gravitational/teleport#7357]
### Description

We are upgrading our Teleport infrastructure. We come from teleport v4.2.9 (where this issue wasn't happening) and are currently running teleport v5.2.1.  The issue first time appeared on teleport v4.4.9.

**What happened**:

Users are experiencing OIDC login errors the first time they login everyday. Once login is retried, it works as expected.

**What you expected to happen**:

Users should login successfully the first time without having to retry.

### Reproduction Steps
The issue is hard to reproduce as it happens once every 24h (approx) for each user. Even if using incognito mode on browser, the error doesn't reproduce, so probably this is a server side problem.
1. Login in teleport web using OIDC connector
2. Retry login in teleport web using OIDC connector

### Server Details
- Teleport version (run `teleport version`): `Teleport Enterprise v5.2.1 git:v5.2.1-0-g81218b38a go1.15.5`
- Server OS (e.g. from `/etc/os-release`): `Debian 10`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): `Dedicated hardware`
- Additional details:

### Client Details
- Tsh version (`tsh version`): `Teleport v5.2.1 git:v5.2.1-0-g81218b38a go1.15.5`
- Computer OS (e.g. Linux, macOS, Windows): `Linux Ubuntu`
- Browser version (for UI-related issues): `Google Chome  91.0.4472.101`
- Installed via (e.g. apt, yum, brew, website download): `Website download`
- Additional details:

### Debug Logs
Logs from `journalctl`:
```jun 18 08:28:56 auth-prod-1 teleport-ent[843947]: INFO [AUDIT]     user.login attributes:map[acr:1 teleport.example.com auth_time:1.624004934e+09 teleport.example.com email:vcabezas@example.com email_verified:false exp:1.624048134e+09 family_name:Cabezas Lucena given_name:Victor groups:[root admin operator] iat:1.624004935e+09 iss:https://oidc.example.com/auth/realms/master jti:[REDACTED] k8s_groups:[k8s-cluster-admin] locale:es name:Victor Cabezas Lucena preferred_username:vcabezas session_state:[REDACTED] sub:[REDACTED] typ:ID username:vcabezas] cluster_name: code:T1001W ei:0 error:"/web/users/vcabezas@example.com/params" is not found event:user.login message:"/web/users/vcabezas@example.com/params" is not found method:oidc success:false time:2021-06-18T08:28:56.141Z uid:5bcae201-9ab3-444e-ad2a-02b281364f7b user: events/emitter.go:318
jun 18 08:29:11 auth-prod-1 teleport-ent[843947]: INFO [AUDIT]     user.create cluster_name: code:T1002I connector:keycloak.example.com ei:0 event:user.create expires:2021-06-18T20:29:11.162164785Z name:vcabezas@example.com roles:[admin root operator dev-username] time:2021-06-18T08:29:11.169Z uid:[REDACTED] user:system events/emitter.go:318
```

Logs from `/var/lib/teleport/log/events.log`
```
{
  "ei": 0,
  "event": "user.login",
  "uid": "[REDACTED]",
  "code": "T1001W",
  "time": "2021-06-18T05:39:53.848Z",
  "cluster_name": "",
  "user": "",
  "success": false,
  "error": "\"/web/users/vcabezas@example.com/params\" is not found",
  "message": "\"/web/users/vcabezas@example.com/params\" is not found",
  "method": "oidc",
  "attributes": {
    "name": "Victor Cabezas Lucena",
    "auth_time": 1623912848,
    "aud": "teleport.example.io",
    "given_name": "Victor",
    "typ": "ID",
    "groups": [
      "admin",
      "operator",
      "root"
    ],
    "exp": 1620999248,
    "iat": 1623994712,
    "email_verified": false,
    "iss": "https://keycloak.example.com/auth/realms/master",
    "k8s_groups": [
      "k8s-cluster-admin"
    ],
    "email": "vcabezas@example.com",
    "preferred_username": "vcabezas",
    "family_name": "Victor Cabezas Lucena",
    "azp": "teleport.example.com",
    "session_state": "[REDACTED]",
    "username": "vcabezas",
    "sub": "[REDACTED]",
    "acr": "0",
    "jti": "[REDACTED]"
  }
}
```

**Comment by zmb3** [comment]
@Wiston999 are you still having issues with OIDC?

**Comment by Wiston999** [comment]
Hi, we are no longer having issues with OIDC. We are using `v7.3.22` at the moment so at some point between `v5.2.1` and `v7.3.22` this is fixed.

**Comment by zmb3** [comment]
Thanks for following up!
