### ISSUE TITLE
Ability to limit openssh certs by source host/ip via whitelist command/config option

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#7366]
### What
Request to have the ability to lock down openssh access through teleport by source ip or host. 

### How
Ideally with a flag option to be passed along with the `tctl auth sign --user=user --format=openssh` command.

### Why
Increased security and parity with offerings such as AWS console automation.

**Comment by zmb3** [comment]
Source IP pinning for SSH (teleport and openssh) was added in Teleport 10.
