### ISSUE TITLE
Disk reservation on Teleport servers to make sure access is not lost due to lack of space

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#7388]
### What
A number of customers have run into an issue where they're unable to access Teleport at times due to lack of disk space. Request is to have teleport reserve X amount of space on startup to ensure that `tsh ssh` access is not lost as the only remedy to this issue when it presents is ssh-ing into the server/node, clearing out space, and restarting teleport - something that's not feasible in certain environments where customers only have access to the node through Teleport tunnel and `tsh ssh`

### How
Hard reservation to account for space needed by Teleport processes and `tsh ssh`

### Why
Customers have run into issue and been locked out in the past.

### Workaround
Customer have to manually guess and scope the amount of space required for Teleport, which may not always be accurate.

gz#4021

**Comment by corkrean** [comment]
After testing, I have confirmed that `node sync` mode solves the issue of losing access when disk space is full.

**Comment by pschisa** [comment]
Similar requests to issues #5424 and #2200

**Comment by gabrielcorado** [comment]
Closed by #12916.
