### ISSUE TITLE
Document missing cli command

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/teleport#7404]
## Details

Previously, the Web UI and `tctl` were the primary ways to request new roles/permissions. Now, `tsh` has the ability to do this as well.

`tsh login ...` is documented: https://goteleport.com/docs/cli-docs/#examples-8 but other methods like `tsh request new` are not.

Add documentation for `tsh request new` and any approval or denial flags.

See: https://github.com/gravitational/teleport/blob/6c34385e359d21917787ddeb1866d4dc304d30df/tool/tsh/access_request.go#L289

Also some other commands that are missing like `tsh apps ...`: https://docs.google.com/spreadsheets/d/1lu0sf_hrYv7hIuGpqFRcq0EIGC8d3cspB9t_b8fduIk/edit?usp=sharing

### Category
- New Feature
- Improve Existing
- Remove Outdated

**Comment by Abhijnan-Bajpai** [comment]
Is this issue still open? If so, I would like to work on this.

**Comment by zmb3** [comment]
`tsh request new` (and other related commands) are documented here: https://goteleport.com/docs/setup/reference/cli/#tsh-request-new
