### ISSUE TITLE
gRPC conversions - public CA Cert endpoint

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#7413]
### What
Add public CA Cert export endpoints needed by Greenhouse.

Updates #6394

**Comment by zmb3** [comment]
@marcoandredinis didn't you recently add a public endpoint for our CA certs, or was that for databases only?

**Comment by marcoandredinis** [comment]
Only for DBs.
It returns the CA certs and a key pair for mTLS usage
https://github.com/gravitational/teleport/pull/14526

What would be the goal here? A gRPC method to return only the CA Certs?

**Comment by zmb3** [comment]
> What would be the goal here? A gRPC method to return only the CA Certs?

We've had a few requests to expose the CA certs to unauthenticated users, which would make setup of some parts of Teleport easier as you could just use `curl` to pull them down rather than running `tctl auth export` and copying the file out. (It likely would be HTTP, not GRPC)

**Comment by marcoandredinis** [comment]
I still need to tidy up the PR description but please let me know if that's close to what you were looking for
https://github.com/gravitational/teleport/pull/15491
