### ISSUE TITLE
Feature Request: Better Access Controls 

### ISSUE THREAD

**Issue by ekristen** [gravitational/teleport#743]
It would be nice to allow certain users access to specific nodes only.

**Comment by kontsevoy** [comment]
@ekristen this is already done for the upcoming 2.0 (it's in master). Dupe of #620

**Comment by ekristen** [comment]
Thanks @kontsevoy I apologize, I missed the issue because it was already closed. I'll have to check out the code from master! Thanks.

**Comment by kontsevoy** [comment]
@ekristen or wait a few weeks for 2.0 to come out. master doesn't have docs right now.
