### ISSUE TITLE
WebUI "Add Server" button disabled with `admin` role

### ISSUE THREAD

**Issue by tcsc** [gravitational/teleport#7433]
### Description

**What happened**:

Logged into WebUI with a user that only has `admin` role, and the "Add ..." button is disabled:
![Add Server Disabled](https://user-images.githubusercontent.com/1959769/123741479-782d1000-d8ed-11eb-8773-37ced364625e.png)

**What you expected to happen**:
If an `admin` is expected to be a complete cluster admin, I'd expect the "Add..." buttons to be enabled.

### Reproduction Steps
1. Log into WebUI with a user that only has the `admin` role
2. Observe that the "Add ..." button is disabled for servers, databases, etc
3. Add `editor` role to user
4. Log out of UI and back in
5. Observe that the "Add ..." button is enabled for servers, databases, etc

### Server Details
- Teleport v6.2.5 git:v6.2.5-0-gde3ec05d7 go1.15.5
- Ubuntu 20.04.2 LTS
- Running locally

### Client Details
- Firefox 89.0.2 on Ubuntu 20.04.2 LTS

**Comment by jonaskello** [comment]
I have the same issue. Is there any workarounds?

**Comment by zmb3** [comment]
Closing this as we've deprecated the admin role entirely.
