### ISSUE TITLE
Plugin Documentation Improvements

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/teleport#7439]
## Details

We're currently in the process of modifying our plugin documentation: https://github.com/gravitational/teleport/issues/6404

This ticket tracks several additional plugin-related changes:

- [x] Verify and/or update use of Direct Messaging mode with Slack Plugin - depends on where this is installed (channel/user, private channel).
- [x] Verify simultaneous use of Direct Messaging mode and Channel notification
- [x] Verify and/or update `suggested_reviewers`.
- [ ] Update other plugins to use `suggested_reviewers`.

### Category

- New Feature
- Improve Existing
- Remove Outdated

**Comment by inertial-frame** [comment]
https://github.com/gravitational/teleport-plugins/pull/259 and https://github.com/gravitational/teleport/pull/7041 address `suggested_reviews` for the Slack Plugin.

**Comment by ptgott** [comment]
Added in ecdb9dfff7480bb362e3ef6b096ad581afe08587
