### ISSUE TITLE
Easier reconnections in the web ui once disconnected?

### ISSUE THREAD

**Issue by felixdesouza** [gravitational/teleport#7446]
#### What would you like Teleport to do differently?

When disconnected part way through a session in the web UI, there is no way to "restart" said session without having to close that window down and start again. It would be neat if it was possible to start a new session but on the same node in the windows that are currently open.

#### How would you implement this?
Have a modal or some way of alerting the user that they have been disconnected and offer the user a way to reconnect all current tabs etc. Understandably the session doesn't resume, but it's just a single click.

#### Why do you need this?
Compared to the CLI, if you were disconnected, you can just go to the previous command and start again. Whereas if you're disconnected in the Web UI, you have to select to open a new session, and then find the node that you were just on, and then it opens a new tab which is quite jarring especially if you have a few tabs open.

**Comment by zmb3** [comment]
Refreshing the page will start a new session on the same node.
