### ISSUE TITLE
TLS handshake

### ISSUE THREAD

**Issue by Fastidious** [gravitational/teleport#745]
When trying to access my server web interface, I get:

```
[user@fubar:~]$ 2017/02/02 11:10:53 http: TLS handshake error from XXX.XXX.XXX.XXX:55334: remote error: tls: unknown certificate
```

**Comment by kontsevoy** [comment]
What is this output of? `tsh --proxy=N`? Did you configure teleport with SSL cert for HTTPS? If you have not, please use `--insecure` flag.

**Comment by ksorathiya** [comment]
I have configured SSL cert for HTTPS, still getting the same error when accessing a node on a trusted cluster. Yes on the trusted cluster SSL certificate is not setup. Does that matters?
