### ISSUE TITLE
Trusted-Cluster Mapping Typo

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#7461]
## Details
Current trusted cluster mapping [example](https://goteleport.com/docs/trustedclusters/#example) states 'Now, we need to establish trust between roles "root:admin" and "leaf:admin",' but should say 'Now, we need to establish trust between roles "root:admin" and "leaf:access".'

### Category
- Improve Existing

**Comment by ptgott** [comment]
Closing since this line is no longer in the Trusted Clusters guide.
