### ISSUE TITLE
Elasticsearch support (DB access)

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#7482]
### What
Would like Teleport to have the ability to manage Elasticsearch components (adding ES as a supported data source/database)

### How
Add new functionality

### Why
Customer request and growth of OSS platform.

### Workaround
None currently.

Success criteria:
* Teleport can provide access to Elasticsearch databases with audit logging support.

**Comment by benarent** [comment]
@smallinsky what happened with ElasticSearch., I heard rumors that it works with Teleport Application Access, but we've not blogged / shared much new about the support yet.
