### ISSUE TITLE
x509: certificate is valid for ::1, 127.0.0.1, not x.x.x.x (the public ip of my vps)

### ISSUE THREAD

**Issue by noriuky** [gravitational/teleport#749]
this happen when i try to connect to any teleport cluster by any pc which is not part of the cluster it self using this command:
tsh --proxy=x.x.x.x ssh root@y.y.y.y
where xxxx is the teleport server public ip and yyyy is another server running teleport as client.
I follow the guide on teleport website [here](https://gravitational.com/teleport/docs/admin-guide) "Using OpenSSH Client" 

I can still access any server of the cluster with ssh x.x.x.x  but teleport dont record the session.
i want force to use tsh via command line or webui to all team so i can record them.
Tnx for your help.

**Comment by kontsevoy** [comment]
For production/secure use Teleport must be running behind a fully configured SSL endpoint, i.e. you should not be accessing it via IP, and instead you should purchase an SSL cert and configure Teleport to use it.

But... For testing purposes pass `--insecure` to `tsh`.
