### ISSUE TITLE
Clarify that AWS ALBs are not supported

### ISSUE THREAD

**Issue by ari-becker** [gravitational/teleport#7499]
## Details
The [documentation](https://goteleport.com/docs/aws-terraform-guide/#use_acm) today still claims that AWS Application Load Balancers are supported for serving in front of the web UI. This would even be preferable in many cases as an AWS ALB allows the user to use AWS's edge networking products, including AWS WAF and AWS Shield, for additional network security.

However, in practice this doesn't seem to fully work for proxied web applications; when attempting to access the API of a proxied web application, [tsh login will generate client certificates](https://goteleport.com/docs/application-access/guides/api-access/) which are not supported by AWS ALBs, and the traffic will fail to reach the Teleport proxy instances. Instead, the web UI must sit behind an AWS Network Load Balancer, and the proxy cannot use AWS ACM certificates for the web UI.

Alternatively - please clarify how to serve the web UI proxy on one port (which can sit behind an ALB) and for the web application proxy (which uses client certificates) to sit on another port (which can sit behind an NLB).

### Category
- Improve Existing

**Comment by aranair** [comment]
Just to clarify, this will not be an issue with nlb/letsencrypt setup right?

**Comment by ari-becker** [comment]
> Just to clarify, this will not be an issue with nlb/letsencrypt setup right?

Correct, as an NLB just proxies TCP traffic without terminating TLS

**Comment by webvictim** [comment]
I think most if not all of this has been covered by https://github.com/gravitational/teleport/pull/18823?

**Comment by ptgott** [comment]
Between that and the HA guide (https://goteleport.com/docs/deploy-a-cluster/high-availability/), I think we can close this.
