### ISSUE TITLE
Time limited server access

### ISSUE THREAD

**Issue by dkrutsko** [gravitational/teleport#7504]
### What
From the documentation, I see that Teleport supports Slack integration for the user approval process. I would like to know if there's a feature that allows someone temporary access to a server. For instance, asking for 6-hours or 1-week worth of access before the privilege is revoked.

### How
If you're editing users, perhaps an extra field in the yaml that specifies the time range (start and expiry time), or through Slack, maybe some ability to select a time range.

### Why
Most of the time, we find that people only need access to a server or group of servers to test something out, especially when they're working on a feature and they need access to do something on the server temporarily before not needing access again for a long time.

**Comment by zmb3** [comment]
Access requests are the mechanism by which you can request temporary access to a server:

- https://goteleport.com/blog/access-requests/
- https://goteleport.com/docs/enterprise/workflow/
