### ISSUE TITLE
Session recordings exceed limit

### ISSUE THREAD

**Issue by andycui66** [gravitational/teleport#7514]
### Description

**What happened**:
Getting error "number of events retrieved for specified date range has exceeded the maximum limit of 9999 events" when trying to list session recordings.
![Screen Shot 2021-07-09 at 12 20 30 PM](https://user-images.githubusercontent.com/5249524/125108538-2ab06000-e0b0-11eb-8173-5d7b119da2ce.png)

We have automatic job running with Teleport which generate tons of session recordings everyday. With that large number of recordings, Teleport cannot show it at all. 

**What you expected to happen**:
Show large number of recordings.
Or be able to skip some recording upload so we can reduce the volume.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Upload more than 10k recordings in a day
2. Go to "Session recordings" page
3.

### Server Details
- Teleport version (run `teleport version`): 6.2.5
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Client Details
- Tsh version (`tsh version`): 6.2.5
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues): Chrome
- Installed via (e.g. apt, yum, brew, website download): brew
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by Valien** [comment]
Just encountered this issue when running a `psal databasename < databasedump.sql` that generated a ton of logging entries. Even though session recordings are not that many it seems to be tied into the Audit Log potentially as well.

**Comment by Aharic** [comment]
Is this the same issue that was resolved in https://github.com/gravitational/teleport/pull/7638?

**Comment by xacrimon** [comment]
@zmb3 Yep, this has been fixed for some time.
