### ISSUE TITLE
CA certificate produced by `tsh app login` does not include intermediate certificates, causing default curl invocation to fail

### ISSUE THREAD

**Issue by ari-becker** [gravitational/teleport#7518]
### Description

**What happened**:
Running `tsh app login foo` produces the following output:

```text
Logged into app foo. Example curl command:

curl \
  --cacert /home/ari/.tsh/keys/example.com/certs.pem \
  --cert /home/ari/.tsh/keys/example.com/ari@example.com-app/example.com/foo-x509.pem \
  --key /home/ari/.tsh/keys/example.com/ari@example.com \
  https://foo.example.com:443
```

When running the proposed command (with `--verbose` added, for the sake of this bug report), `curl` complains with:

```text
*   Trying 1.2.3.4:443...
* Connected to foo.example.com (1.2.3.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /home/ari/.tsh/keys/example.com/certs.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**What you expected to happen**:

For the `curl` call to succeed.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Issue a 90-day ACME certificate from ZeroSSL https://zerossl.com/ and configure the Teleport proxy service to use it
2. Note that the certificate issued by ZeroSSL, and therefore the certificate file referenced in `teleport.yaml`'s `proxy_service.https_keypairs[0].cert_file` includes the full certificate chain including root certificate and intermediate certificates
3. Add an Application to proxy, call it `foo`
4. `tsh app login foo`
5. `curl` call as described above
6. Note that the certificate at `/home/<you>/.tsh/keys/example.com/certs.pem` does not include the full certificate chain

### Server Details
- Teleport version (run `teleport version`): 6.2.6
- Server OS (e.g. from `/etc/os-release`): Running within a container on Kubernetes - `quay.io/gravitational/teleport:6.2.6`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

### Client Details
- Tsh version (`tsh version`): 6.2.3
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): Nix

### Debug Logs
Not relevant?

### Workaround
Simply remove the `--cacert` line:
```text
curl \
  --cert /home/ari/.tsh/keys/example.com/ari@example.com-app/example.com/foo-x509.pem \
  --key /home/ari/.tsh/keys/example.com/ari@example.com \
  https://foo.example.com:443
```
which works as expected (as ZeroSSL is a trusted public CA).

**Comment by strideynet** [comment]
We should probably just remove the `--cacert` line from the demo curl in the output, any production instance of Teleport will most likely be operating with a certificate issued by a trusted public certificate authority. I find the `--cacert` somewhat misleading and potentially confusing to an operator who knows that their proxy has been deployed with a trusted public cert.
