### ISSUE TITLE
Proposal: seed_config behavior

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#752]
## Description

`seed_config: false` is set by default that can lead to confusing scenarios when backend data is deleted after service restart, see #746 

First of all I suggest to make it a bit more explicit:

## Rename seed_config to `source`

To make it explicit, rename this setting to "source" meaning source of truth for configuration.

## Source: backend

* If `source: config` then the data from config file is only populated once per startup of the first auth server in the cluster. 
* The hash of the config is remembered in the back-end
* If the config changes, warning should be issued that the changes are going to be ignored

## Source: config

* No new entries added to the back-end are going to be deleted
* On every startup, the server is going to overwrite entries from config to the back-end

## Source default values

* When no config is specified, we assume file system "static" backend and `source: config`
* When any dynamic back-end is specified, teleport assumes `source: backend`

This setting could be manually overridden by user explicitly.

**Comment by kontsevoy** [comment]
Dupe. See #795
