### ISSUE TITLE
Possible problem on chart release versions on https://charts.releases.teleport.dev

### ISSUE THREAD

**Issue by ronaldmiranda** [gravitational/teleport#7520]
hello guys, there is a problem when deploying teleport helm chart with the default version, which leads to 6.0.0 version of helm chart, this default chart diverge with the actual version properties that is documented.
i want to ask you if using the version "6" instead the "6.0.0" of helm chart is the correct one and it should be the default for the release of chart.

**Comment by webvictim** [comment]
Version `"6"` is currently correct. This will deploy the latest version of Teleport 6.x using `quay.io/gravitational/teleport:6`

We are looking to change this in future to automatically bump the chart version to match new versions of Teleport when released - see #6887.

Related to #7046 
Related to #7106

**Comment by webvictim** [comment]
This has been resolved now, we publish chart releases along with Teleport releases.
