### ISSUE TITLE
[v.6.2] /docs/pages/database-access/guides/gui-clients.mdx

### ISSUE THREAD

**Issue by HatBeardZero** [gravitational/teleport#7526]
## Details
PGAdmin GUI missing step.  In order to connect via the GUI after retreiving the login, i had to set a user environment variable of c:\users\USER\.pg_service.conf in order for pgadmin to recognize the service. 

### Category
- Improve Existing

**Comment by r0mant** [comment]
We updated our pgAdmin connect instruction a while ago so this is no longer relevant.
