### ISSUE TITLE
Add documentation around `deb.releases.teleport.dev` and `rpm.releases.teleport.dev`

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#7546]
## Details
Scattered in our GitHub repos and in our official Teleport docs are references to these two repositories:
- https://deb.releases.teleport.dev
- https://rpm.releases.teleport.dev

But no README or documentation that explains what really is in these repos.  Had a customer ask what packages were listed and if you run a `grep Package /var/lib/apt/lists/deb.releases.teleport.dev_dists_stable_main_binary-amd64_Packages` (on Ubuntu/Debian distros) command you'll get a list of the packages available which are:
- `teleport`
- `teleport-ent`
- `teleport-ent-fips`

For customers that leverage IaC to patch and provision it would be good to have a page detailing what is in these repos from a security and user help viewpoint.

As an example, I leverage these repos in my Ansible playbooks to update and patch my EC2 and GCP instances. It simplifies the administration of Teleport. For customers using Teleport at scale, these repos are very helpful in the day-to-day management of their infrastructure.

### Category

- New Feature
- Improve Existing

**Comment by Valien** [comment]
Also this page - https://charts.releases.teleport.dev/ and corresponding code - https://github.com/gravitational/teleport/tree/master/examples/chart

**Comment by ptgott** [comment]
We removed all references to these repos in https://github.com/gravitational/teleport/pull/36022
