### ISSUE TITLE
OTP test fail

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#755]
We have a stress-tests set up on `metal` node which runs `make test` in a loop. In 6.5% of the test runs (approx every 15th run) we get this failure:

```
FAIL: apiserver_test.go:265: APISuite.TestOTPCRUD

apiserver_test.go:293:
    c.Assert(err, NotNil)
... value = nil
```

**Comment by kontsevoy** [comment]
not valid.

**Comment by russjones** [comment]
Fixed in https://github.com/gravitational/teleport/pull/766.
