### ISSUE TITLE
Clickable Links in the Web Terminal

### ISSUE THREAD

**Issue by jdconti** [gravitational/teleport#7569]
### What
What would you like Teleport to do differently? Add support for clickable links in the web terminal.

A user just requested this and it seems like a sensible feature.

### How
How would you implement this? ¯\\_(ツ)_/¯

### Why
Why do you need this? UX

### Workaround
If a workaround exists, please include it.

**Comment by russjones** [comment]
This issue needs investigation on how the terminal we use in the Web UI detects URLs. In theory we could do this, but don't want to open ourselves up to security vulnerabilities.

**Comment by zmb3** [comment]
Opened #22043 to address this.

URL detection is via this regex, which looks safe to me: https://github.com/xtermjs/xterm.js/blob/9154831afa9aea78306d8edad8fe403616758ad3/addons/xterm-addon-web-links/src/WebLinksAddon.ts#L9-L20
