### ISSUE TITLE
Change the Log Level for tcp connection reset by peer errors

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#7605]
### What
Currently, the following message is produced at an error level:
`read tcp a.b.c.d:3023->w.x.y.z:4321 read: connection reset by peer sshutils/server.go:667`

This error has been shown to be a byproduct of load balancer health checks (the a.b.c.d IP is the private IP of the load balancer) without any bearing on actual Teleport cluster or user connectivity/performance.  This is the same behavior noted in issue #2815 and could also be resolved if #2815 is resolved instead.

The request is to change this message from log level ERROR to something like WARN or INFO so that setting the logging level to ERROR could filter out these messages as they are spammed rather frequently and do not seem to always indicate an actionable error on the user side (or even any degraded performance)

### How
Change the log level in the code to report this as INFO

### Why
To make ERROR logs more useable and not full of spam.

**Comment by zmb3** [comment]
> This is the same behavior noted in issue https://github.com/gravitational/teleport/issues/2815 and could also be resolved if https://github.com/gravitational/teleport/issues/2815 is resolved instead.

#2815 was in fact resolved.
