### ISSUE TITLE
[v.6.2] /docs/pages/faq.mdx -- Remove reference to Teleport pro

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#7626]
## Details
The comparison chart detailing Pro needs to be removed as Pro is no longer offered

https://goteleport.com/docs/faq/#how-is-open-source-different-from-enterprise

This table is used quite a bit during demos and conversations around differences between OSS and Enterprise.

### Category

- Improve Existing
- Remove Outdated

**Comment by sshahcodes** [comment]
related to #7516?

**Comment by Valien** [comment]
Ah, didn't find it in search. Thanks @sshahcodes . That is the same info.

**Comment by ptgott** [comment]
Looks like there's one lingering mention of "Teleport Pro" at the bottom of the page
