### ISSUE TITLE
tsh env variable for kube-cluster

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#7641]
### What
Ability to set kube-cluster as a tsh env.

### How
Automatically log into and pin the specified kube-cluster once a user executes `tsh login`

### Why
Customer ask for shops that have contractors/reps that work exclusively in a single kube cluster.

**Comment by Joerger** [comment]
Just to clarify, the ask is that `tsh login --proxy=... --kube-cluster=example.com` works with `KUBE_CLUSTER=example.com tsh login --proxy=...` instead right? Or is the expectation that `--proxy` is no longer provided either?

One alternative though: if the contractors/reps are only working with a single kube cluster, it would be better to provide them access to only that cluster. That way, if the user only has access to a single kube cluster, that one should be automatically pinned/selected after `tsh login`.
