### ISSUE TITLE
ssh client to login to teleport node does not work

### ISSUE THREAD

**Issue by stephencheng** [gravitational/teleport#765]
tried to test this in two different scenarios:

1. from a redhat7 box to ssh to node06 via authproxy2
2. from mac to node06 via authproxy2

I tried the approach detailed here: https://github.com/gravitational/teleport/blob/master/docs/admin-guide.md#using-openssh-client

both failed with similar message, 

-------------error for case1--------------
[stephencheng@client root]$ ssh -v stephencheng@node06
OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 70: Applying options for *
debug1: Executing proxy command: exec ssh -p 3023 stephencheng@authproxy2 -s proxy:node06:22
debug1: identity file /home/stephencheng/.ssh/id_rsa type -1
debug1: identity file /home/stephencheng/.ssh/id_rsa-cert type -1
debug1: identity file /home/stephencheng/.ssh/id_dsa type -1
debug1: identity file /home/stephencheng/.ssh/id_dsa-cert type -1
debug1: identity file /home/stephencheng/.ssh/id_ecdsa type -1
debug1: identity file /home/stephencheng/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/stephencheng/.ssh/id_ed25519 type -1
debug1: identity file /home/stephencheng/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1
debug1: permanently_drop_suid: 1002
ssh: error while loading shared libraries: libcrypt.so.1: cannot map zero-fill pages: Cannot allocate memory
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: Connection closed by remote host

lots of this line: ssh_exchange_identification: Connection closed by remote host

-------------error for case 2-------------

Ξ ~CM_CONF_DIR/ssh → ssh -v stephencheng@node06
OpenSSH_7.2p2, OpenSSL 1.0.2h 3 May 2016
debug1: Reading configuration data /Users/stephencheng/.ssh/config
debug1: /Users/stephencheng/.ssh/config line 9: Applying options for *
debug1: Reading configuration data /usr/local/etc/ssh/ssh_config
debug1: Executing proxy command: exec ssh -p 3023 stephencheng@authproxy2 -s proxy:node06:22
debug1: permanently_drop_suid: 501
debug1: identity file /Users/stephencheng/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/stephencheng/.ssh/id_rsa-cert type -1
debug1: identity file /Users/stephencheng/.ssh/id_dsa type 2
debug1: key_load_public: No such file or directory
debug1: identity file /Users/stephencheng/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/stephencheng/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/stephencheng/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/stephencheng/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/stephencheng/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2
fork failed: Resource temporarily unavailable
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: Connection closed by remote host

Also I wonder why we need to run: tsh --proxy=work.example.com agent in client node?

If you want a centralised setup of ssh service, why do you need a client to download teleport and install it there?

Please can you give me a hint what could be possibly wrong? is this a bug or I didn't hit right step? anything I missed?

**Comment by kontsevoy** [comment]
`ssh` connects to port 22 by default. Teleport uses `3022`, can you try `ssh -p 3022` instead?

**Comment by stephencheng** [comment]
Sorry, this still does not work for me, I am suspecting that it's issue with older version of openssh talking to teleport:

If you check my reported error above, you can see key word: allocate memory.

configure I used:
[root@client .ssh]# cat config
Host *
    ProxyCommand ssh -p 3023 %r@proxy1 -s proxy:%h:3022

Similar here as below:

---------------------log-----------------------
[root@client ~]# tsh --proxy=proxy1 agent
SSH_AUTH_SOCK=/tmp/79b29f70-daf1-4070-99ab-8c2ee94ce169.socket; export SSH_AUTH_SOCK;
SSH_AGENT_PID=6175; export SSH_AGENT_PID;
echo Agent pid 6175;

Broadcast message from systemd-journald@client (Tue 2017-02-14 10:47:30 AEDT):

systemd[1]: Caught <ABRT>, cannot fork for core dump: Cannot allocate memory


Broadcast message from systemd-journald@client (Tue 2017-02-14 10:47:30 AEDT):

systemd[1]: Freezing execution.

---------------end log-----------------

[root@client .ssh]# ssh -v stephencheng@node1
OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /root/.ssh/config
debug1: /root/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Executing proxy command: exec ssh -p 3023 stephencheng@proxy1 -s proxy:node1:3022
debug1: permanently_set_uid: 0/0
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1
debug1: permanently_drop_suid: 0
ssh: error while loading shared libraries: libutil.so.1: failed to map segment from shared object: Cannot allocate memory
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: Connection closed by remote host
