### ISSUE TITLE
Allow DynamoDB TTL/Expiration configuration to be set via Teleport install config options

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#7662]
### What
When installing Teleport using some of our AWS guides that auto-sets DynamoDB, etc. a default TTL of 1 year is set and is not currently configurable.

It is documented here - https://goteleport.com/docs/admin-guide/#using-dynamodb

Users that self-host might get confused when told that when you self-host and leverage DynamoDB you can have a longer TTL or even indefinite TTL.

The only way to disable this is to go into AWS console (or via CLI probably) and disable TTL expiration.

![Screen Shot 2021-07-23 at 9 05 33 AM](https://user-images.githubusercontent.com/1424442/126793261-dddbe942-862b-4207-ac44-8461a89af774.png)

### How

1. Either clarify in our documentation how to remove the TTL or better yet
2. Have a TTL config option where the users can set a pre-determined (or none) TTL when installing and configuring Teleport

### Why
Mainly for self-hosted/Enterprise customers that want more granular control of their audit logs and need longer retention periods.

### Workaround
Disabling TTL within AWS console manually is the only option right now.

**Comment by russjones** [comment]
@xacrimon Can the TTL be set on table creation time? If that's the case, we can set the TTL then, otherwise if the table exists use the existing TTL. This would allow users to configure/create tables using Terraform with their own TTL values.

**Comment by xacrimon** [comment]
@russjones So TTL is set per item via a column which we manually set and not per table and there is no default setting. We can however offer a configurable TTL option in Teleport that allows the user to disable or configure TTL in Teleport.

**Comment by xacrimon** [comment]
I've opened a fix for this in #8840 allowing for a custom TTL configuration.
