### ISSUE TITLE
Ability to have MFA remember a device

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#7677]
### What
Would like the ability for MFA to remember a device for X days. This would allow for users to only be prompted every few days rather than every logon.

### How
Remember MAC address or implement cookie

### Why
Nice to have quality of life improvement

### Workaround
Continue entering MFA at every login

**Comment by zmb3** [comment]
We have not seen significant demand for this and it weakens the security model of MFA, so I'm closing this for now.
