### ISSUE TITLE
Role `kube` is not supported in provisioning tokens

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7683]
### Description

A user tried following the guide https://goteleport.com/docs/kubernetes-access/guides/multiple-clusters/#connecting-clusters

but using Terraform provider instead.

In the original guide, command looks like this:

```
TOKEN=$(kubectl exec -ti "${POD?}" -- tctl nodes add --roles=kube --ttl=10000h --format=json | jq -r '.[0]')
```

it references role `kube`. When trying to specify provisioning token resource in terraform, setting `roles=[kube]` does not work, but setting `roles=[Kube]` uppercase works, because CLI tool converts lower case to built-in uppercase role.

* [ ] Improve the error message. Instead of `Error: role kube is not registered` detect the system role and say `Error: role kube is not registered, did you mean system role Kube?`
* [ ] Even better, give an example in terraform
* [ ] Or, find a way for this to become consistent, e.g. in the original example --roles=Kube ?

**Comment by zmb3** [comment]
Tagging with `good-starter-issue` as I believe this should have been fixed by #9756 and we just need someone to verify.
