### ISSUE TITLE
Raspberry PI4 broken

### ISSUE THREAD

**Issue by wargas92** [gravitational/teleport#7686]
### Description
Hi, 
I tried to use teleport with my PIs 4 in order to have access remotely. The teleport services are hosted in AWS using an EC2 instance.
Everything is working for a while.
**What happened**:

After a couple of hours my Pis was fried.  
No way to power on.
I reduced the setup of pi's only to teleport contained in a service that is started at boot, since I need a bit of robustness to power loss.

The pi was tested with 20 power on/off before installing teleport in order to be sure that the board was ok for my needs.
After installing teleport the pi was not able to have the same reliability, going in a dead state.

I tried all the steps with 4 different PIs and all of them goes in the same state

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Installing teleport as node in rpi with the right token 
2. instantiate a service according to the documentation guide
3. Try 20 up to 50 power on/off without shutting down (power loss).

### Server Details
- Teleport version: 6.0.0 ce
- Server OS (e.g. from `/etc/os-release`): centos rhel fedora
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS/EC2 instance

### Node Details
- Teleport: 6.0.2
- Computer OS (e.g. Linux, macOS, Windows): Rapbian OS
- Installed via (e.g. apt, yum, brew, website download): binary download 

Is there a way to know what was the issue and if it is related with Teleport?
T&R

**Comment by zmb3** [comment]
I'm going to close this due to inactivity. Feel free to start a discussion if you're still having trouble.

I suspect tweaking the sqlite backend configuration may help here.
