### ISSUE TITLE
Can't connect mysql rds (x509: certificate relies on legacy Common Name field)

### ISSUE THREAD

**Issue by phanmduong** [gravitational/teleport#7694]
### Description
x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching

**What happened**:
I call tsh in my computer
<img width="934" alt="Screen Shot 2021-07-26 at 22 08 58" src="https://user-images.githubusercontent.com/18007936/127012848-d86e08e0-31bb-41a4-b1a1-1b41033514bb.png">
But it has error. I checked log on server teleport 
<img width="1244" alt="Screen Shot 2021-07-26 at 22 10 13" src="https://user-images.githubusercontent.com/18007936/127013073-54753ae9-8544-4b73-9f0b-79f602cd018e.png">

**What you expected to happen**:
I want to my computer can connect mysql rds via teleport

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. I create IAM in amazon and enable mysql IAM authentication
2. I check connect mysql using aws iam on server teleport. It's working
3. when i use teleport to connect mysql rds not working 

### Server Details
- Teleport version (run `teleport version`): Teleport v6.2.8 git:v6.2.8-0-g0bbeffb63 go1.15.5
- Server OS (e.g. from `/etc/os-release`): ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): aws
- Additional details:

### Client Details
- Tsh version (`tsh version`): v6.2.8 git: go1.16.6
- Computer OS (e.g. Linux, macOS, Windows): macos
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download): brew
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
2021-07-26T15:06:31Z [AUDIT:1]   INFO Creating directory /var/lib/teleport-db/log/upload/streaming. service/service.go:1925
2021-07-26T15:06:31Z [AUDIT:1]   INFO Creating directory /var/lib/teleport-db/log/upload/streaming/default. service/service.go:1925
2021-07-26T15:06:31Z [DB:SERVIC] INFO Database service has successfully started: [DatabaseServer(Name=colorme, Type=rds, Version=6.2.8, Labels=map[env:dev])]. service/db.go:215
2021-07-26T15:06:36Z ERRO [DB:SERVIC] Failed to handle connection. addr:54.151.135.73:3024 error:[
ERROR REPORT:
Original Error: *errors.withStack x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/srv/db/mysql/engine.go:163 github.com/gravitational/teleport/lib/srv/db/mysql.(*Engine).connect
	/go/src/github.com/gravitational/teleport/lib/srv/db/mysql/engine.go:77 github.com/gravitational/teleport/lib/srv/db/mysql.(*Engine).HandleConnection
	/go/src/github.com/gravitational/teleport/lib/srv/db/server.go:401 github.com/gravitational/teleport/lib/srv/db.(*Server).handleConnection
	/go/src/github.com/gravitational/teleport/lib/srv/db/server.go:367 github.com/gravitational/teleport/lib/srv/db.(*Server).HandleConnection
	/go/src/github.com/gravitational/teleport/lib/reversetunnel/transport.go:234 github.com/gravitational/teleport/lib/reversetunnel.(*transport).start
	/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit
User Message: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0] db/server.go:369
^C2021-07-26T15:14:02Z [PROC:1]    INFO Got signal "interrupt", exiting immediately. service/signals.go:86
- Run tsh with --debug flag (`tsh --debug`)
 mysql --defaults-group-suffix=_teleport.eduto.net-colorme
ERROR 1105 (HY000): x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

**Comment by zmb3** [comment]
This is related to Go 1.15's deprecation of the common name field for verification.

AWS provides instructions on how to use the AWS CLI to regenerate certificates for your RDS instance [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html):

> If you are using a Go version 1.15 application with a DB instance that was created or updated to the rds-ca-2019 certificate prior to July 28, 2020, you must update the certificate again. Run the modify-db-instance command shown in the AWS CLI section using rds-ca-2019 as the CA certificate identifier. In this case, it isn't possible to update the certificate using the AWS Management Console. If you created your DB instance or updated its certificate after July 28, 2020, no action is required. For more information, see Go GitHub issue #39568.

**Comment by pschisa** [comment]
Teleport could work around this issue after implementation of #7636

**Comment by jeffery-jen** [comment]
Since v8.1.5 this issue cannot be resolved simply by adding `GODEBUG="x509ignoreCN=0"`

**Comment by JohnAtOlo** [comment]
I've been getting this error and nothing in the documentation is working. I can't get the RDS cert to rotate even though it's already on the 2019 CA.

**Comment by beercialfo** [comment]
@JohnAtOlo Did you update the cert via cli or console?, Does it require restart of the RDS instance?

**Comment by JohnAtOlo** [comment]
I tried via CLI (well, Terraform actually) on one instance and it wasn't clear if it was taken effect or not so for the rest of my instances I used the console and backfilled terraform.

It claimed to require a restart but I saw no downtime.

It did regenerate certs and apps had to accept the new certs, so it was a bit disruptive but in the end it resolved this issue.

**Comment by beercialfo** [comment]
Thank you @JohnAtOlo
