### ISSUE TITLE
Use utils.Deduplicate when building list of host principals

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#770]
## Descriptoin

When building host principals, make sure to use `utils.Deduplicate`, otherwise you will end up with duplicate principals in case if HostUUID and NodeName are the same thing

```
       Valid: forever
        Principals: 
                172_28_128_5.metal8.metal8
                172_28_128_5.metal8.metal8
        Critical Options: (none)
```

**Comment by russjones** [comment]
Fixed in #772.
