### ISSUE TITLE
Ability to reconfigure trusted clusters without having to destroy/recreate trusted cluster

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#7723]
### What
Teleport currently requires users to delete/rebuild trusted clusters completely if/when making trusted-cluster config changes. It would be good to be able to update the relationship (for role mapping purposes, for example) without having to destroy and rebuild the relationship each time.

### How
Either have a sync check at a set interval or some other similar mechanism that allows changes in the trusted cluster config to be propagated. 

### Why
Ease of managing cluster relationships especially when mappings between clusters change often.

**Comment by zmb3** [comment]
This was implemented.
