### ISSUE TITLE
Add ability to disable S3 versioning API calls

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#7743]
### What

Currently, when using S3, teleport will query the object for the oldest version as a measure against tampering. (see https://github.com/gravitational/teleport/blob/4de9e94a510638cf61991eff57526c606512b83b/lib/events/s3sessions/s3handler.go#L190-L196)

As far as I can tell, this is the only use we make of the S3 versioning API.

Non-official S3 implementations may not have versioning code implemented.

Specifically, When running minio without its [erasure coding](https://docs.min.io/docs/minio-erasure-code-quickstart-guide.html) enabled, it returns [error 501 not implemented](https://github.com/minio/minio/issues/10158) for any attempt to get a version of an object.

Additionally, when running minio in the azure object gateway mode, versioning is not supported and a similar situation occurs.

### How

An opt-out of using any versioning calls in the teleport configuration for S3 would fill the gap here. It should be properly caveated in the documentation as only being necessary if the user runs into an S3 API "not implemented" type error without it.

### Why

To increase compatibility with non-amazon S3 implementations.

This would include development appropriate single node minio instances and production appropriate minio azure object gateway instances.

Other non-amazon S3 implementations may benefit from this as well.

### Workaround

none

**Comment by zmb3** [comment]
See also #10698

**Comment by programmerq** [comment]
Considering that buckets with versioning disabled are still not _immutable_, this request does indeed raise the possibility of a security concern. Non-amazon S3 implementations may not have a feature that could make an object immutable to protect against the same hypothetical attack. I think that means that this is for sure appropriate to close in favor of #10698 to document the security posture that bucket versioning grants.
