### ISSUE TITLE
Desktop Access preview/beta implementation

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#7761]
Tracking issue for Desktop Access implementation, defined in https://github.com/gravitational/teleport/pull/7725

- client UI (@ibeckermayer)
  - [x] desktop output streaming
  - [x] user input forwarding
  - [x] ~~username/password prompt~~ no longer supported

- `windows_desktop_service` gateway mode (@zmb3)
  - [x] RDP client
  - [x] static hosts
  - [x] ~~username/password authentication~~ no longer supported
  - [x] smart card authentication
  - [x] AD host discovery via LDAP - Beta (@zmb3) (#8615)
  
- RBAC bindings
  - [x] allowed usernames - Beta (@zmb3)
  - [x] host labels - Beta (@zmb3)
  - [x] user locking - Beta (@zmb3)
  - [x] idle session timeout - Beta (@zmb3)
  - [x] concurrent session limit (@ibeckermayer )
- [x] make performance tolerable
- documentation - Beta
  - admin documentation
    - [x] AD setup
    - [x] RBAC

Testing:

- [x] docs on local test env setup - Beta
- [x] testplan section - Beta
- [x] multiple sessions as the same user on the same host should only allow 1 to be active - Beta
- [x] multiple sessions as different users on the same host - Beta
- [x] ~~username/password fallback~~ no longer supported
- [x] fuzz tests for RDP client - done by contractor

**Comment by zmb3** [comment]
Closing this, remaining work to take from preview to GA is being tracked under #8742
