### ISSUE TITLE
HA etcd config question

### ISSUE THREAD

**Issue by stephencheng** [gravitational/teleport#777]
For a HA configuration using etcd, I am just wondering what's the architecture of etcd setup? the doco didn't say much about it.

1. Is it a etcd cluster? like a few etcd instances running, then in the teleport config file we put a elb entry for it?

2. the doco shows below config:
        peers:
        - https://172.17.0.1:4001

I am wondering what's expected to be in there? is it a list of https urls with different ip addresses?  if so, why not use a load balanced entry?

If it's single url, or only allow single url there, it must mean it only allow single etcd, then the etcd becomes single point of failure.

I am hoping the doco could be a little more detailed on HA setting using etcd.

Clarification on above would be much appreciated.

**Comment by klizhentas** [comment]
Check out etcd clustering guide:

https://coreos.com/etcd/docs/latest/op-guide/clustering.html

In clusered setup etcd is not a SPOF as it can tolerate node failures. In the list of peers you can supply the list of ETCD peers.

When supplying etcd backend the config will be managed by etcd and not locally, yes.

You could put etcd behind LB but then make sure that your LB is not a SPOF.

**Comment by stephencheng** [comment]
great, I will try it out. 

Thanks
