### ISSUE TITLE
Missing Roles on Upgrade in AWS DynamoDB storage

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#7772]
### Description

**What happened**:

In a aws dynamodb/s3 stored cluster with 2500 roles, only 911 were available after upgrading from 6.2.7 to 6.2.8.  This can also occur on a restart. Reapplying the roles allows them to stay persisted.

**What you expected to happen**:

All roles would migrate from previous version. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Configure a 6.2.7 Teleport instance with a AWS backend
2. Generate 2500 roles with the following script and apply
```bash
#!/bin/bash

for i in {1..2500}
do
cat << EOT >> example.yaml 
kind: role
metadata:
  name: admin$i
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    db_names:
    - '{{internal.db_names}}'
    db_users:
    - '{{internal.db_users}}'
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    kubernetes_labels:
      '*': '*'
    kubernetes_users:
    - '{{internal.kubernetes_users}}'
    logins:
    - '{{internal.logins}}'
    - root
    node_labels:
      '*': '*'
    rules:
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - auth_connector
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - session
      verbs:
      - list
      - read
    - resources:
      - trusted_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - user
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - token
      verbs:
      - list
      - create
      - read
      - update
      - delete
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
---
EOT
done
```
```bash
sudo tctl create -f example.yaml
```
3. Upgrade to version 6.2.8
4. Confirm the number of roles
```
sudo tctl get roles | grep admin -c
```

### Server Details
- Teleport version (run `teleport version`): 6.2.7
- Server OS (e.g. from `/etc/os-release`): Ubuntu
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by russjones** [comment]
Tried reproducing this with etcd and sqlite, could not. Also tried reproducing in 5.2.1 where it manifests itself as well.

Appears to be an issue specifically with the DynamoDB backend.
