### ISSUE TITLE
Support SSH option RemoteForward or -R with tsh ssh

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#7776]
### What
Request is to have teleport support the SSH option `RemoteForward` with `tsh ssh -o`.  Ideally, the flag `-R` could also be used with `tsh ssh` as well

### Workaround
Use OpenSSH client

**Comment by Aharic** [comment]
+1 for `tsh ssh -R`

**Comment by russjones** [comment]
https://github.com/gravitational/teleport/pull/4566

**Comment by fabriciofeijo** [comment]
We are also need this feature to use with Wireshark remote capture.

**Comment by ziranjameshe** [comment]
Hi @r0mant, any update one this?

**Comment by petrasl1976** [comment]
It was also useful for remote file edit on desktop editors via `rmate` or `rsubl`

**Comment by nevermort** [comment]
Hi there, are any updates here?

**Comment by adityagandhi-humane** [comment]
> Hi there, are any updates here?

+1

**Comment by gcosta-lively** [comment]
+1

**Comment by petrasl1976** [comment]
+1

**Comment by revawiki** [comment]
This is a needed feature, my organization can't move entirely to Teleport from AWS SSM because lack of remote port forwarding options. Hope it will be added soon.

**Comment by atburke** [comment]
Completed as part of #37117
