### ISSUE TITLE
TestResolveDefaultAddrTimeoutBeforeAllRacersLaunched fails intermittently: "too many open files"

### ISSUE THREAD

**Issue by ymatsiuk** [gravitational/teleport#7794]
### Description

**What happened**:
Seems like having [1000](https://github.com/gravitational/teleport/blob/a8db09fe1e25e9854cc8764f868305f61a6f0699/tool/tsh/resolve_default_addr_test.go#L240) connections leaves almost no room for the build server to breath if we consider 1024 is default limit.
```
2021-08-04 13:27:39.869762 I | http: Accept error: accept tcp 127.0.0.1:33657: accept4: too many open files; retrying in 5ms
--- FAIL: TestResolveDefaultAddrTimeoutBeforeAllRacersLaunched (0.61s)
panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: too many open files [recovered]
        panic: httptest: failed to listen on a port: listen tcp6 [::1]:0: socket: too many open files
```

**What you expected to happen**:
All tests must succeed on the build node, so the package is built and cached successfully.
Otherwise everyone else who uses nix/NixOS must build the package every single time they upgrade the system.

More details on failed builds:
```
Build Status for nixpkgs.teleport.x86_64-linux on unstable
✖ (Failed) teleport-6.2.7 from 2021-07-29 - https://hydra.nixos.org/build/149041948

Last Builds:
✖ (Failed) teleport-6.2.7 from 2021-07-22 - https://hydra.nixos.org/build/148284356
✖ (Failed) teleport-6.2.7 from 2021-07-21 - https://hydra.nixos.org/build/148120062
✖ (Failed) teleport-6.2.7 from 2021-07-15 - https://hydra.nixos.org/build/147791606
✖ (Failed) teleport-6.2.7 from 2021-07-06 - https://hydra.nixos.org/build/147232108
✖ (Failed) teleport-6.2.7 from 2021-07-04 - https://hydra.nixos.org/build/146996985
✔ teleport-6.2.5 from 2021-06-26 - https://hydra.nixos.org/build/146494848
✖ (Failed) teleport-6.2.5 from 2021-06-22 - https://hydra.nixos.org/build/146098071
✖ (Failed) teleport-6.2.3 from 2021-06-17 - https://hydra.nixos.org/build/145771855
✖ (Failed) teleport-6.2.3 from 2021-06-13 - https://hydra.nixos.org/build/145346398
```

Does it make sense to lower [this](https://github.com/gravitational/teleport/blob/a8db09fe1e25e9854cc8764f868305f61a6f0699/tool/tsh/resolve_default_addr_test.go#L240) number?

CC: @russjones (this started to appear after https://github.com/gravitational/teleport/pull/6880)

**Comment by zmb3** [comment]
This also happens often on macOS, where the default `maxfiles` limit is much lower.

**Comment by ymatsiuk** [comment]
Meanwhile I lowered the value to [`100`](https://github.com/NixOS/nixpkgs/blob/b626776ab2e9c4389e8f7717193dc15b0f337bb5/pkgs/servers/teleport/test.patch#L10) to fix the build
```Build Status for nixpkgs.teleport.x86_64-linux on unstable
✔ teleport-6.2.8 from 2021-08-05 - https://hydra.nixos.org/build/149509150
```
Higher values seem an overkill and more like a benchmark than unit test 🙂 unless there is a good reason behind it that I can't see
