### ISSUE TITLE
tsh login takes too long to time out

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#7795]
### Description

**What happened**:  Attempts to `tsh login` to a non-routable proxy server take 2m30s to time out. `tsh` does not respect SIGINT during this time and must be forcefully terminated.

**What you expected to happen**: 
- there should be a more reasonable timeout on this operation, so that the user doesn't get the impression that `tsh` is hung
- `tsh` should still respect SIGINT while it is attempting to connect to the proxy so that the user can abort the login rather than being forced to wait for it to eventually time out

### Reproduction Steps
Attempt to login to a proxy that will timeout.
1. `tsh login --proxy=foo.invalid --auth=local --user=foo`
2. Observe process hanging.
3. Attempt to abort with ctrl+c - debug output shows signal received (`DEBU [TSH]       signal: interrupt tsh/tsh.go:542`) but process continues to hang until it eventually times out (2m30s later)

### Client Details
- Tsh version (`tsh version`): Teleport v7.0.0-beta.1 git:v7.0.0-beta.1-95-gda3c3dcc6 go1.16.6
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Installed via (e.g. apt, yum, brew, website download): built from source

**Comment by zmb3** [comment]
PR #7801 at least fixes cancelation, so that the process doesn't have to be killed.

As for a shorter timeout, I think we might want to only do that for local auth, as SSO flows can take a bit longer. Thoughts?

**Comment by mo-markcrossland** [comment]
I don't know any SSO process that takes longer than 2 minutes 30 to work. Do you have any examples?

**Comment by zmb3** [comment]
Maybe not longer than 2m30, but I'm more thinking we should limit local logins to something like 5-10 seconds, and SSO that involves a user entering some sort of 2nd factor can definitely take longer than that.

**Comment by zmb3** [comment]
This has been fixed and now times out after 5s.
