### ISSUE TITLE
X11 Forwarding support for Teleport nodes

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#7799]
### What
Enable the ability to use X11 forwarding through Teleport proxy to a Teleport node.  Ideally this would work with `tsh` and OpenSSH clients but just OpenSSH clients at first would be sufficient.

### How
Allow X11 forwarding to Teleport nodes and audit X11 activity in audit events

### Why
Enables the ability to maintain the full benefits of Teleport to support applications and workflows that still require X11 forwarding to function.

### Workaround
Use and OpenSSH client and OpenSSH node integration for X11 forwarding

**Comment by jdconti** [comment]
Windows 10 with MobaXterm 21.2.0.4642 at present; we're also using Xming 7.7.0.10 as a standalone X server.  It's also worth mentioning Mac with XQuartz and RHEL 7/8 with native X servers.  Let me know if you need any additional info, thanks!

**Comment by russjones** [comment]
@Joerger Teleport in proxy recording mode will forwarding `x11-req` from `ssh` to `sshd`. However, this only allows OpenSSH clients to talk to OpenSSH servers through Teleport.

Let's take the following approach to rolling out X11 support:

- [ ] Add support for `tsh -X`. This will allow Teleport clients to talk to an OpenSSH servers through Teleport (in proxy recording mode).
- [ ] Add support for X11 forwarding (handling `x11-req`) to Teleport servers (in regular mode). Then you will be able to support OpenSSH servers and clients with Teleport.
