### ISSUE TITLE
feature question: does one instance of teleport support multiple clusters

### ISSUE THREAD

**Issue by stephencheng** [gravitational/teleport#781]
I understand that in auth configuration section, you could configure one cluster for one running instance of teleport auth or proxy.

My question is whether one running instance supports multiple clusters?

A use case is that if I have multiple teams running different application A,B and C, I'd like one centralised teleport auth server to support multiple teams' logins. In this case, I will setup one cluster of auth servers, instead of many HA clusters of A, B and C.

Core team, please confirm.

Thankks

**Comment by kontsevoy** [comment]
@stephencheng sure.

What you're describing is what we have at work. To set this up, you:

1. Create, say, 3 clusters A, B, C.
2. Cluster "A" is the "master" and holds identities of all users.
3. Clusters B and C do not have any users, but they're configured to trust cluster A (i.e. all users from A are automatically propagated to B and C).

This is called "trusted clusters".
Docs:
https://gravitational.com/teleport/docs/admin-guide/#trusted-clusters

**Comment by stephencheng** [comment]
Thanks.

Yes, I understand the concept of trusted cluster and I have already made it work.

Here my real problem is that I don't want to create physical cluster A, B and C, in this case I will need to run 3 teleport services with 1-1 mapping:

cluster A: 1 teleport instance running (1 yaml config) <-> 1 cluster A <->  1 auth service <-> multiple teleport nodes
cluster B: 1 teleport instance running (1 yaml config) <-> 1 cluster A <->  1 auth service <-> multiple teleport nodes
cluster C: 1 teleport instance running (1 yaml config) <-> 1 cluster A <->  1 auth service <-> multiple teleport nodes


I'd like:
                                      /-> cluster A
1 teleport service <->   -> cluster B
                                      \-> cluster C

the cluster in here become a virtual boundary of team/app level segregation

So I guess I am seeking a centralised configuration to eliminate number of teleport services running 

Are you supporting this model as I described?

Thanks

**Comment by stephencheng** [comment]
@kontsevoy I am not sure how to reopen this issue but hoping you could see my update and need your advice on it.

Thank you

**Comment by kontsevoy** [comment]
@stephencheng yeah, closed issues are still good to discuss features. what you're describing is what we internally call "infrastructure partitioning" and creating separate clusters for that is an overkill. my guess is that you want to partition your nodes based by who can access them.

For that Teleport supports RBAC, see #620. This falls into enterprise teleport 2.0 feature set (to be released this Feb).

**Comment by stephencheng** [comment]
@kontsevoy thanks very much, I guess the feature I am looking for is the namespace mentioned in there.

Do you have a set date of the release of 2.0? will it be also in open source version?

Btw, I couldn't seems find detailed docs of features in enterprise version compared to open source version. Is there a link for it?

We are now looking for above fine grained access control plus AD integration.
