### ISSUE TITLE
Proxy logs are spammed with error reports in EKS clusters

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#7810]
### Description

**What happened**:
When a Teleport cluster is deployed in AWS EKS, the Teleport pod logs are spammed full of the following errors:
~~~
WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 192.168.33.59:3080-&gt;192.168.51.158:56549: i/o timeout\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:282 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:206 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit\nUser Message: failed to peek connection\n\tread tcp 192.168.33.59:3080-&gt;192.168.51.158:56549: i/o timeout" multiplexer/multiplexer.go:209
~~~

The first IP is the Teleport pod and the second IP is the INTERNAL-IP of one of the nodes

This does not correlate with any observable issue and makes the logs very difficult to parse for real warnings and information.  The best guess at the moment is that the EKS infrastructure is causing Teleport to falsely report these warnings, similar to #2815 

**What you expected to happen**:
Teleport pod will not be spammed with these messages unless there is an actual problem.

### Reproduction Steps
1. Deploy a cluster in EKS
2. Observe logs on the proxy pod

### Server Details
- Teleport version (run `teleport version`): 6.1.5
- Where are you running Teleport?: AWS EKS

**Comment by pschisa** [comment]
Something like this suggestion https://github.com/gravitational/teleport/issues/2815#issuecomment-738877660 to wrap repeating log messages together over time would also help since the main issue is that the application logs become unreadable with too many warning messages repeated.

**Comment by gclawes** [comment]
Seeing a similar issue with `teleport-kube-agent` in a bare-metal cluster:

```
82022-06-14T23:38:36Z WARN [MX:KUBERN] "\nERROR REPORT:\nOriginal Error: *net.OpError read pipe: i/o timeout\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:261 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:221 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_arm64.s:1133 runtime.goexit\nUser Message: failed to peek connection\n\tread pipe: i/o timeout" multiplexer/multiplexer.go:224
```

**Comment by aardbol** [comment]
Same in GCP GKE:

`WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 10.56.0.3:3080-&gt;10.56.0.1:11844: i/o timeout\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:396 github.com/gravitational/teleport/lib/multiplexer.detectProto\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:259 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:221 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit\nUser Message: failed to peek connection\n\tread tcp 10.56.0.3:3080-&gt;10.56.0.1:11844: i/o timeout" multiplexer/multiplexer.go:224`
