### ISSUE TITLE
Allow the ability to modify the scrollback buffer on UI shell

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#7814]
### What
Allow the ability to increase the scrollback buffer on a terminal session on the web UI.

### How
Implement some form of rc file to modify the web terminal

### Why
This will allow for users to view commands and outputs previously displayed

### Workaround
Work from the CLI rather than UI.

**Comment by zmb3** [comment]
Going to close this in favor of the newer duplicate at #20293.
