### ISSUE TITLE
Performance becomes much slower on large clusters with a DynamoDB backend

### ISSUE THREAD

**Issue by quinqu** [gravitational/teleport#7815]
### Description

**What happened**:
Running `tsh bench` on large clusters (10k), significantly slows down performance. 

### Reproduction Steps

As minimally and precisely as possible, describe step-by-step how to reproduce the problem.

1. Create a cluster with 2 auths, 2 proxies, and 10k nodes a Dynamo backend 
2. Create a cluster with 2 auths, 2 proxies, and 1 node with a Dynamo backend 
3. Run the following commands against one node (in each cluster) in parallel 

- `tsh bench --duration=4h <user>@<hostname> ls`
- `tsh bench -i --duration=4h <user>@<hostname> ps uax`

4. Compare latency profiles, you'll see that the cluster with 10k nodes performs significantly slower than the cluster with 1k 

Ref: 
https://github.com/gravitational/teleport/issues/7572#issuecomment-893821330
https://github.com/gravitational/teleport/issues/7572#issuecomment-893916848

### Server Details
- Teleport version (run `teleport version`):
  - Ran building from this branch https://github.com/gravitational/teleport/tree/fspmarshall/v7-debug-2, but running on 7.0 should reflect the same behavior 

- Server OS (e.g. from `/etc/os-release`): Amazon Linux
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Just AWS for the small cluster. Provisioning nodes on GCP for the large cluster while the auths and proxies are being run on AWS

**Comment by zmb3** [comment]
@rosstimothy I think this issue is outdated and can be closed. Can you have a look and close it if you agree?
