### ISSUE TITLE
[v.6.2] /docs/pages/config-reference.mdx

### ISSUE THREAD

**Issue by Thom-x** [gravitational/teleport#7817]
## Details
In section "Quickstart using docker-compose"

Command `curl -Lso teleport-quickstart.yml https://raw.githubusercontent.com/gravitational/teleport/v6.2.7/docker/teleport-quickstart.yml`
Version in compose file is `quay.io/gravitational/teleport:5` instead of `quay.io/gravitational/teleport:6` it should be 6, or next steps in doc are not working properly.
Example: 
`docker exec teleport tctl users add testuser --roles=editor,access --logins=root,ubuntu,ec2-user`
Is giving an error because with teleport 5 `--roles` and `--logins` does not exists.

### Category

- Improve Existing

**Comment by sshahcodes** [comment]
PR in progress - #7539

**Comment by zmb3** [comment]
Closing - the 6.2 docs are no longer live.
