### ISSUE TITLE
teleport-cluster helm chart should support running pods as non-root user

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#7821]
### What

Our helm chart should be able to start the teleport pods as a non-root user.

### How

The deployment template would have a section to render a securityContext with a non-root uid similar to the [teleport-kube-agent deployment template](https://github.com/gravitational/teleport/blob/a177241e89513fb15e6e2e66fb1f40183755ae08/examples/chart/teleport-kube-agent/templates/deployment.yaml#L52-L59).

### Why

Some environments require all software that can run as non-root to run as a non-root user. This common security policy is aligned with NIST 800-53r5 AC6 Least Privilege.

### Workaround

Currently, it is possible to implement a helm [post-renderer](https://helm.sh/docs/topics/advanced/#post-rendering) that can add the securitycontext to the rendered resources before creating them in the cluster. This is less than ideal since the `--post-renderer` flag and binary must be provided exactly the same way on every system that ever does a helm operation. The post-renderer does not follow the release at all. This means that if someone makes a small change to the values for the release, the post-renderer patch will not be applied if they forget to include it explicitly in the helm command.

gz#3157

**Comment by webvictim** [comment]
This will be exposed by https://github.com/gravitational/teleport/pull/11939 which should be merged soon.

**Comment by webvictim** [comment]
Yes. `teleport-cluster` now exposes a `securityContext` value that can be set to override this: https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L285-L287
