### ISSUE TITLE
Define a set of privileged operations in the UI that require second factor

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7833]
### What

We have introduced [privileged operations](https://github.com/gravitational/teleport/blob/master/rfd/0029-account-lifecycle.md) Search for "authorizing privileged operations". 

We should revise operations performed by UI and require second factor confirmation according to the flow described above.

* [ ] Revise all administrative operations that require elevated security:
 * [ ] Request approvals/denials
 * [ ] Adding or removing auth connectors, users and roles
 * [ ] Anything else missing?
* [ ] Start requiring authorization for the privileged operations above if the user has enrolled MFA keys. 

Consider possible downgrade attack - a user would like to remove their MFA keys and then perform the admin action in the UI. To do that using UI users would have to tap the MFA key first, which protects them from the downgrade attack. If a user would want to remove MFA key using CLI, they would also have to tap MFA key to complete the cycle.

* [ ] Improve https://goteleport.com/docs/cli-docs/#tsh-mfa-rm to require a second factor confirmation if the user has MFA key to prevent from a downgrade attack.
* [ ] Require MFA for similar admin actions as above for CLI operations as well. Make enforcement on the auth api level by requiring extra certificate extension signature for the privileged operations

**Comment by zmb3** [comment]
@Joerger would you say this is done now that the admin actions RFD has been merged?

**Comment by Joerger** [comment]
I plan on closing this once the implementation is complete, at least for the endpoints mentioned in this issue - https://github.com/gravitational/teleport/issues/33767

**Comment by strideynet** [comment]
@Joerger should be good to close this now #33767 is complete and v15 is shipped ?
