### ISSUE TITLE
You do not have access to add a server

### ISSUE THREAD

**Issue by hakerakn** [gravitational/teleport#7834]
### Discussed in https://github.com/gravitational/teleport/discussions/7832

<div type='discussions-op-text'>

<sup>Originally posted by **hakerakn** August  8, 2021</sup>
Hello, I have had the following problem for several days:
As a blade on the "Add server" button, the button is not active. He wrote me the following inscription "You do not have access to add a server"

The user is: teleport-admin
It has the following roles: access, admin</div>

**Comment by zmb3** [comment]
Looks like this was answered in the discussion.
