### ISSUE TITLE
Allow for `tsh login` w/out requiring browser login

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#7838]
### What
A number of customers have requested the ability to log in via CLI while taking advantage of OIDC/SAML integration w/out having to open a browser to log in. 

### How
AWS and Azure CLI  utilize Puppeteer to automate a headless browser instance and allow the entire exchange to take place in the CLI.

### Why
Quality of Experience and ability to extend into environments where browsers may not be available and port forwarding may not be an option.

gz#3967

gz#3968

**Comment by acherifi** [comment]
We would love to see this. We would like to leverage Teleport in our CI/CD system but the browser login prevents us to do so

**Comment by klizhentas** [comment]
Collect more info to understand the use-case

**Comment by zmb3** [comment]
@Aharic any updates on this request?

**Comment by chfoster-viasat** [comment]
Hello, we just encountered this. Our use case is we have a remote machine that several non-engineers are intending to use that doesn't have browser access. These non-engineers should be able to use OIDC SSO for their existing accounts. Because of this we have to resort to local users.

**Comment by Joerger** [comment]
Headless SSO is now available for `tsh ls`, `tsh ssh`, `tsh scp` - https://github.com/gravitational/teleport/issues/21519

Bringing Headless SSO to additional features will be tracked in https://github.com/gravitational/teleport/issues/21520
