### ISSUE TITLE
[v.7.0] /docs/pages/getting-started.mdx

### ISSUE THREAD

**Issue by abdul-elah-js** [gravitational/teleport#7871]
## Details
I don't know if the product is still supported, but the docker documentation is out-dated, none of the images mentioned in there is available

### Category
- Remove Outdated

**Comment by ptgott** [comment]
Hi @abdul-elah-js, thanks for reporting. It looks like the `quay.io/gravitational/teleport:7.0` image name [here](https://goteleport.com/docs/setup/guides/docker/#step-14-pick-your-image) should be `quay.io/gravitational/teleport:7`. Are there any other docs pages you've noticed where the image names/tags are incorrect?
