### ISSUE TITLE
Notification feature for the requestee for Access Request Approvals

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#7873]
### What
It would be nice to have the option to send Access Request approvals/denial notifications to requestees somehow so they don't have to just keep a request open and check on it constantly until it's approved. There may be instances where it's not possible to get approval right away which can hinder workflow if users have to constantly keep checking back in on their request manually.

### Why
Request by customer.

**Comment by zmb3** [comment]
This was addressed with the notification system in Teleport 16.
