### ISSUE TITLE
VSCode ssh session recordings not recorded properly

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#7884]
### Description

**What happened**:

SSH connections to nodes using VSCode 'Remote - SSH' extension (through Teleport proxy) are not being recorded in Teleport. Following behavior has been observed:

- Session is present in Active Sessions for 30 seconds only (always 30 seconds) and then disappears.
- The actual session remains open in VSCode even after it disappears from Active Sessions in Teleport.
- Audit log shows that a session is created with a valid session ID, but session updates happen against a blank session id:

```
Session Data | Usage report has been updated for session [] | 2021-08-11 18:33:20 | DETAILS
Port Forwarding Started | User [teleport-user] started port forwarding | 2021-08-11 18:33:20 | DETAILS
Session Started | User [teleport-user] has started a session [c0867e6f-4ea2-4afc-92a9-71c7e809a553]
```

- session.end occurs more than 30 minutes after the actual session is disconnected from the VSCode side
- when session.end does occur, it appears that the session is recorded as a 'non-interactive' session. 

```
User [teleport-user] has ended a non-interactive session [8eceb7ce-d765-404c-bb60-6203377046a0] on node [cloud-node-2]
User [teleport-user] command execution on node 172.12.0.1:59478 failed [exit status 255]
```
- A session like the one described above does not appear in Session Recordings.
- If a session is joined via WebUI or CLI before the 30 second timeout is triggered and the session disappears from Active Sessions, the session is kept alive in Active Sessions until the joint session is exited.
- If a session is ended from VSCode side before the 30 second timeout is triggered, the session is properly ended in teleport and recorded properly (appears in Session Recordings).

It seems like there may be keepalives between VSCode ssh server and Teleport that are not interacting properly but I have not been able to confirm with certainty yet. VSCode 'Remote - SSH' extension does have a number of 30 second hard-coded timers, but I have not been able to mitigate any of them w/ the configurable options on either end.

**What you expected to happen**:

VSCode sessions should be treated like any other OpenSSH session and recorded for posterity.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Setup VSCode OpenSSH integration through Teleport using the VSCode Remote - SSH extension
2. Connect to a node via VSCode
3. Observe the session as active in Teleport's Active Sessions menu for 30 seconds
4. Observe the session disappear from Active Sessions after 30 seconds
5. Confirm that the session is still open in VSCode and users can continue to interact w/ the remote node through it
6. Close out session via VSCode and observe the empty SessionID updates noted above
7. Wait 30 min or so (may take longer depending on how busy the cluster is) and observe the non-interactive session message in the audit logs

### Server Details
- Teleport version (run `teleport version`): 6.2.8

### Client Details
- Tsh version (`tsh version`): 6.2.8

**Comment by 2022liuws** [comment]
I had the same problem
