### ISSUE TITLE
Cluster Name pulling internal DNS name that could change and on reboot assigns diff name

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#7894]
### Description

Stood up a single cluster using our [Starter Cluster Terraform](https://github.com/gravitational/teleport/tree/master/examples/aws/terraform/starter-cluster) and works with no issue but what it does is assign the AWS internal DNS name as the cluster name.

![Screen Shot 2021-08-12 at 1 11 07 PM](https://user-images.githubusercontent.com/1424442/129239717-13fadc48-4cd4-484d-b547-2ad89d0e6bdc.png)

If you make a change to the system that requires a reboot (say SG update, etc) then AWS will assign to it a new IP address and therefore a new internal DNS name. When the cluster comes back up it will have the new name assigned to it and not the previous one.

![Screen Shot 2021-08-12 at 1 10 58 PM](https://user-images.githubusercontent.com/1424442/129239878-a371cc98-144e-4c01-b62e-01c420c934dd.png)

![Screen Shot 2021-08-12 at 1 10 28 PM](https://user-images.githubusercontent.com/1424442/129239891-f907ab98-6963-4948-aab7-9c86818f76bc.png)

But in the CLUSTER dropdown it will still reference the old non-valid DNS/IP name. If you have the cluster connected to a root cluster it will show the old DNS name as well:

![Screen Shot 2021-08-12 at 1 16 44 PM](https://user-images.githubusercontent.com/1424442/129240055-96623d05-74ed-45d0-9fc5-1cc5bda80629.png)

You can still SSH to the cluster but logging and info (it seems) will still have the non-valid node/hostname in it's entries.

SSH example:

![Screen Shot 2021-08-12 at 1 18 39 PM](https://user-images.githubusercontent.com/1424442/129241105-7ac0ffbc-9540-49b0-9264-27cb7a7a883b.png)

Current IP of cluster is a `39.7` but Teleport still thinks it's the old `41.110`

**What you expected to happen**:

Expected the server to either pick up my FQDN that is defined in the Terraform or the new updated AWS internal DNS name.

### Reproduction Steps

1. Stand up cluster our Terraform example. It will assign the AWS internal DNS name to the cluster host/name
2. Make a change to Terraform SG (ex: update the SSH IP from all the world to just your home for example). The forces a network change on the server
3. AWS will assign a new internal IP and DNS name most likely.
4. Log into your cluster and be confused that it says one things bug shows another...
5. 
### Server Details
- Teleport version (run `teleport version`): `v7.0.2`
- Server OS (e.g. from `/etc/os-release`): Amazon Linux 2
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Client Details
- Tsh version (`tsh version`): `v6.2.7`
- Computer OS (e.g. Linux, macOS, Windows): OSX

**Comment by stevenGravy** [comment]
This is no longer the case.  The cluster-name matches the cluster-name given.
