### ISSUE TITLE
Unable to `tsh ls` in Teleport Lab & Signup URL 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#7898]
### Description

I was testing out Teleport Lab, it's awesome but I ran into a couple of issues. 

**What happened**:

1. I was unable to `tsh ls`, as It resulted in the below error. 
```
container(term) /: tsh ls
ERROR: Get "https://proxy.luna.teleport:3080/webapi/ping": dial tcp 172.18.0.2:3080: connect: connection refused
```

2. I was able to add a user, but had to change the URL to `localhost:443` for things to work. It would be good if we could set the link to something more obvious.
```diff
container(term) /: tctl users add testuser --roles=editor,access --logins=root,ubuntu,ec2-user
User "testuser" has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h:
https://proxy.luna.teleport:443/web/invite/c48d35f164d362d8cbbfdd1de080ed76
+https://localhost:443/web/invite/c48d35f164d362d8cbbfdd1de080ed76 

NOTE: Make sure proxy.luna.teleport:443 points at a Teleport proxy which users can access.
```

### Server Details
- Teleport version (run `teleport version`): Teleport Lab 7
- Mac
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

**Comment by stevenGravy** [comment]
@benarent  The PRs  #7902 #7903 fix this.  If you change the tsh alias and remove the port number specification it will work

**Comment by benarent** [comment]
@stevenGravy Any thoughts on why I should still be seeing this with teleport-lab 7.0? https://quay.io/repository/gravitational/teleport-lab?tab=tags  it seems this release should have included your fixes.

**Comment by zmb3** [comment]
@benarent do we still have work to do here or can we close this?

**Comment by zmb3** [comment]
No response in 2 years, I'm going to assume this won't be addressed.
