### ISSUE TITLE
Teleport helm chart repository contains incorrect versions

### ISSUE THREAD

**Issue by jdeprin** [gravitational/teleport#7900]
The current helm repository lists the following charts
```
helm search repo teleport-cluster --versions
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION
teleport/teleport-cluster	6            	6          	Teleport is a unified access plane for your inf...
teleport/teleport-cluster	6.0.0        	6          	Teleport is a unified access plane for your inf...
teleport/teleport-cluster	5.0.0        	5.0        	Teleport is a unified access plane for your inf...
teleport/teleport        	0.0.13       	6          	[This chart is deprecated, use teleport-cluster...
```
The correct chart, or at least the chart that matches the documentation and this repo is version `6`.  Using chart version `6.0.0` results in a very similar but unusable set of resources.  It is quite common to include top level services such as Teleport as a requirement in other charts.  When doing so you need to specify a version to pull.  The standard for Helm is to use Semver numbers (https://helm.sh/docs/chart_best_practices/conventions/#version-numbers). 

**What happened**:
Pulled chart 6.0.0 and attempted to use a values file for chart version 6

**What you expected to happen**:
I would expect that there is only a version 6.0.0 of the chart.  

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. You can see the issue by running:
```
helm template teleport teleport/teleport-cluster --set clusterName=TTEESSTT --set highAvailability.replicaCount=10000 --set chartMode=custom
```

The `clusterName` will update as expected but the replicat count will still show as 1.  This is because that value is not a variable in the chart version 6.0.0 which is pulled by default.

**Comment by webvictim** [comment]
Related to https://github.com/gravitational/teleport/issues/6887

**Comment by webvictim** [comment]
This has been fixed now, charts are published along with Teleport release versions.
