### ISSUE TITLE
OIDC Regression

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#792]
Found a OIDC login regression, this occurs when trying to create a new user.

![](https://cloud.githubusercontent.com/assets/5017502/23324042/6a64689a-faa0-11e6-9360-4c42b025083b.png)

**Comment by russjones** [comment]
This issue is not a regression bug, but rather a UX issue. Two issues:

1. `tctl` allows you to add a user without passing in the `identity`. Like `tsh` it should know what kinds of authentication the auth server supports and return an error if `identity` is not passed in.

       $ ./tctl users add rjones
       Signup token has been created and is valid for 3600 seconds. Share this URL with the user:
       https://localhost:3080/web/newuser/9989f0055d2231693384a9bb1e23fa9c

1. `tctl` provides a signup link for OIDC even though one is not needed and will take you nowhere, this is the cause of the "Whoops, we can not find that." image linked at the start of this thread.

       $ ./tctl users add rjones --identity google:russjones@example.com
       Signup token has been created and is valid for 3600 seconds. Share this URL with the user:
       https://localhost:3080/web/newuser/9989f0055d2231693384a9bb1e23fa9c

We do have what seems like a regression bug, when you add a user with an `identity` using `tctl` and try and log in, eventually you land on a page that says:

       {"message":"user with identity OIDCIdentity(connectorID=google, email=russjones@example.com) not found"}

and the backend has a similar log line:

       INFO[0168] VALIDATE error: user with identity OIDCIdentity(connectorID=google-legacy, email=russellvaleriusjones@gmail.com) not found  file=web/apiserver.go:452 func=web.(*Handler).oidcCallback

**Comment by klizhentas** [comment]
Here's my proposal on how to fix the confusing behavior:

* deprecate `tctl user add --auth=` as we are not going to support this combined local/OIDC mode in the future, so `tctl user add` will always add local users, never `hybrid` users.

* UI `newuser` methuod should always add local user and ignore auth preference, so there is no "signup" for OIDC mode.
