### ISSUE TITLE
Web UI session prevention

### ISSUE THREAD

**Issue by AritraWork97** [gravitational/teleport#7927]
What : 

Is there any way we can prevent opening ssh sessions from the browser and make users log in via terminal but keep the login list which shows the username and node name which a person can access.

Why :

For production sites, I don't want anyone other than the admins to be able to ssh to a server via the web browser. If we can disable the web ui login functionality but keep the node name and the login list, we can setup per session mfa which I dont think is possible via the web ui.

**Comment by klizhentas** [comment]
We will be working on restricting sessions to the web, we might as well add RBAC control that is more flexible and does the opposite, for example:

```
options:
    client: [all, desktop, web] 
```

**Comment by klizhentas** [comment]
@zmb3 does it still need product decision? See the comment above.

**Comment by zmb3** [comment]
Closing in favor of #21544.
