### ISSUE TITLE
Attempting to do a rollout restart of teleport-kube-agent results in an hour of downtime due to double-registration

### ISSUE THREAD

**Issue by ari-becker** [gravitational/teleport#7931]
### Description

**What happened**:
When running a `kubectl rollout restart deployment/<teleport-kube-agent-release-name`, attempting to use the application (e.g. Grafana) results in `500 Internal Error` and the application is listed twice in the application list. Once the old application times out and is removed from the list, then the application begins to work normally again.

**What you expected to happen**:
* To be able to restart the pods (i.e. as part of an upgrade, or to tolerate machine failure) without downtime.
* Document how to set up high-availability correctly

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Install the `teleport-kube-agent` chart
2. Run `kubectl rollout restart` etc.
3. Attempt to use any of the services exposed by the chart's deployment

### Server Details
- Teleport version (run `teleport version`): 7.0.2 (not a new issue, has been an issue for a while)
- Server OS (e.g. from `/etc/os-release`): N/A, using the `teleport-kube-agent` chart
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Kubernetes

**Comment by yjperez** [comment]
This is a similar issue to #5183

**Comment by ari-becker** [comment]
> This is a similar issue to #5183

Yes it sounds like mostly the same issue. However, I consider part of this issue to include double-registration. End-users should not see `Grafana` listed twice in the applications list, just because agents with slightly different identities connected back to the gateway, when the agents are configured to present the same global URL.

**Comment by stefansedich** [comment]
@ari-becker I got around this by configuring a host_uuid in my configuration.

To make this easy I mount `HOST_UUID` as a well known value for each instance to an environment variable. then using an init container I run `echo "$(HOST_UUID)" > /var/lib/teleport/host_uuid` to get the value copied to the right place.

Now when I restart instances when the new one comes up it has the same ID as the old instance and there are no longer duplicate applications or long downtimes.

**Comment by ari-becker** [comment]
@yjperez @stefansedich seems like this would be fixed by https://github.com/gravitational/teleport/pull/8007 , which allows for running the agent as a StatefulSet
