### ISSUE TITLE
Separate Repository for 6.X and 7.X

### ISSUE THREAD

**Issue by MiteshShah** [gravitational/teleport#7941]
### Description

**What happened**:
We setup teleport cluster 6.X and added 19k nodes (6.x) 2 weeks ago using following commands.
```
---
- name: Adding Teleport Repository Key
  apt_key: keyserver=keyserver.ubuntu.com id=0xC87ED53A6282C411
  register: apt_key
  tags: teleport

- name: Adding Teleport Repository
  apt_repository: repo='deb https://deb.releases.teleport.dev/ stable main' state=present filename=teleport
  register: repository
  tags: teleport

- name: Installing Teleport
  apt: name=teleport state=latest
  register: package_install
  # The notify will call the ../handlers/main.yml
  notify: service teleport restart
  tags: teleport
  ```

Everything working fine till last week but since last weekends our Weekly Package upgrade (apt dist-upgrade) run and its upgraded all of our nodes teleport to 7.0.2 while our cluster is on 6.X 
 

**What you expected to happen**:

Ideally Teleport should have separate repo for 6.X and 7.x so if someone setup/used 6.X they only receive updated for 6.x not 7.x and vice versa.

If you check php 7.x/8.X or MariaDB 10.1/10.2/10.3/10.4 all they manage in separate repo to avoid accidently update issue.

**Comment by wadells** [comment]
See https://github.com/gravitational/teleport/issues/7691 as well.

**Comment by wadells** [comment]
Thanks for filing the issue.

I'm consolidating tracking of debian packaging fixes under https://github.com/gravitational/teleport/issues/8166

> If you check php 7.x/8.X or MariaDB 10.1/10.2/10.3/10.4 all they manage in separate repo to avoid accidently update issue.

This sounds like a wise idea -- looking into how to best roll this out.
