### ISSUE TITLE
Terrform Impersonator Roles

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#7948]
We're recommending a Terraform impersonator role that denies access to all nodes, yet we are recommending this role to the "current user". Would it make more sense to allow access to "null" labels or suggest that users create a service account for this role?

https://goteleport.com/docs/setup/guides/terraform-provider/#step-24-create-a-terraform-user

**Comment by alexfornuto** [comment]
Resolved by #23855 which updated the page with a newly defined role that has no `deny` clauses.
