### ISSUE TITLE
Write an example Go program for access requests

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7952]
### What

Write an example go program that handles access requests and only uses our official api. Customers are looking at teleport-plugins repo that has dependency on lib/client and get stuck.

https://pkg.go.dev/github.com/gravitational/teleport/api/client

**Comment by Joerger** [comment]
This [unmerged PR](https://github.com/gravitational/teleport/pull/6827/files) converts the [access example](https://github.com/gravitational/teleport-plugins/tree/master/access/example) to use the official api. If this is what you're looking, for I can reopen the PR and touch it up.

**Comment by klizhentas** [comment]
@Joerger yes, that's exactly it!

**Comment by Joerger** [comment]
In addition to this basic example, I think the best way to exemplify usage of the API would be to add more godoc examples, like [this](https://github.com/gravitational/teleport/pull/6826/files#diff-d05d2bd7d497f14fc8106736b6813fdfe5a39cf7d8bf8b4ecfae0d2c8301ff6c).
