### ISSUE TITLE
Comprehensive list of `tctl get` resources

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#7958]
## Details
In tinkering with awly's recent changes which add a couple of new services, I discovered that there wasn't documentation regarding which resources are available via `tctl get`. The CLI docstring gives a few examples but nothing exhaustive, and the [online documentation](https://goteleport.com/docs/cli-docs/#tctl-get) is largely the same. I ctrl-F'd for "resource" on the cli-docs page and ultimately found a link to the [resource guide](https://goteleport.com/docs/cli-docs/#tctl-get), which has a list but it seems to be out of date.

As a noob `tctl` user, I was hoping for a list of possible resources when I ran `tctl get --help` (that may not be the best solution, maybe it should be a separate command, or something else). On the online docs side of things, we may wish to update the resource list, and add a quick link to it on any command that asks for a `<resource-type>` on the cli-docs documentation page (similar to how we have for "Global Flags" for many commands).

### Category
- Improve Existing

**Comment by ptgott** [comment]
Closing so we can track this here: https://github.com/gravitational/teleport/issues/16948
