### ISSUE TITLE
Cloudflare proxy traffic is not compatible with teleport sshproxy 

### ISSUE THREAD

**Issue by gabrieloandco** [gravitational/teleport#7962]
### Description

**What happened**:
Teleport is able to decode HTTPS proxy traffic coming from Cloudflare but not ssh (sshproxy port 2087->3023)

**What you expected to happen**:
To be able to work with Cloudflare like the HTTPS port does. 

### Server Details
- Teleport version: 7.0.2
- Server OS : Docker container
- Where are you running Teleport? : AKS

### Client Details
- Tsh versio: 7.0.2:
- Computer OS: Ubuntu 20.04
- Installed via: apt

### Debug Logs
tsh --proxy=teleport-dev.test.me:443 -J teleport-dev.test.me:2087  login --debug​

WARN [CLIENT]    Failed to authenticate with proxy teleport-dev.test.me:2087. error:[ssh: handshake failed: ssh: overflow reading version string] client/api.go:2045

**Comment by webvictim** [comment]
Theoretically this should work: `tsh login --proxy teleport-dev.test.me:443,2087`

(at least, I assume this old style comma separated ports strategy still works)

**Comment by jaxxstorm** [comment]
Confirmed, this is quite a fun one to figure out as well
