### ISSUE TITLE
SAML support

### ISSUE THREAD

**Issue by tidalf** [gravitational/teleport#797]
SAML support would be great for infrastructure with existing IDP (Microsoft ADFS for example) that doesn't support oidc.
https://github.com/crewjam/saml works better with my tests than this one https://github.com/RobotsAndPencils/go-saml.

The easiest way to integrate with teleport would be to duplicate a part of the current oidc code since the auth flow and most things are similar but perhaps that's not the good way.

**Comment by dadicool** [comment]
There was an issue already about fixing the oidc integration to support Azure AD. Look here #621

**Comment by tidalf** [comment]
SAML and OIDC are two different things (and ADFS and Azure too).

**Comment by dadicool** [comment]
I read adfs as azure ad. My bad. In deed, saml support is needed for adfs. +1 on that feature :)

**Comment by kontsevoy** [comment]
This has been released as part of [Teleport Enterprise](http://gravitational.com/teleport/docs/2.0/saml/)
