### ISSUE TITLE
does it have adfs oauth support?

### ISSUE THREAD

**Issue by stephencheng** [gravitational/teleport#798]
I understand teleport now support oauth (OIDC)

Can you confirm if it supports adfs backend oauth authentication?

**Comment by klizhentas** [comment]
We haven't tested it with adfs. If it supports OIDC protocol we support it too.

**Comment by stephencheng** [comment]
@klizhentas 

What are the expected response is from the OIDC to teleport? Is there any where I can have this kind of service contract?

**Comment by klizhentas** [comment]
it is literally OIDC, nothing special, if you are looking for examples, we will soon publish docs/tutorials on the subject

**Comment by tidalf** [comment]
adfs 2012 does not support full oidc (just oauth). 
adfs 2016 support oidc, it almost works with teleport, if you hack the go-oidc to accept upn instead of email.
however I haven't found a way to make it works so it sends groups or email instead of upn.
