### ISSUE TITLE
Db failed to establish connection to cluster object not found teleport

### ISSUE THREAD

**Issue by gabrieloandco** [gravitational/teleport#7983]
### Description

**What happened**:
Couldn't Proxy database from KubeAgent

**What you expected to happen**:
DB being listed with tsh db ls and properly proxied

### Reproduction Steps
Install kube agent helm chart setting database values (name,uri,protocol), it is a postgres database. 

Installed on AKS as a Helm chart. 

### Debug Logs
2021-08-19T00:41:19Z ERRO [PROC:1]    Db failed to establish connection to cluster: , object not found. service/connect.go:70

**Comment by stevenGravy** [comment]
@gabrieloandco was this a self-hosted postgresql db?  Can you confirm the db host and port are available from that namespace the agent is running from?

**Comment by gabrieloandco** [comment]
No, it is on Azure without a Firewall. There are other apps in the cluster connecting to it without any issue.

**Comment by stevenGravy** [comment]
how did you configure access to the database?  We have not released support for azure dbs that use iam authentications.

**Comment by gabrieloandco** [comment]
No IAM authentication, is just plain postgres with SSL. The other apps connect to it using the outbound from the cluster. I disabled the firewall for testing and it doesn't work anyway. Also I don't get what is the exact issue with that error message.

**Comment by stevenGravy** [comment]
@gabrieloandco so did you install the Teleport certs into the postgres server?  That's required for it to be able to access the database for self-hosted.  I'm not clear how you're doing SSL. https://goteleport.com/docs/database-access/guides/postgres-self-hosted/#configure-postgresql-server

**Comment by gabrieloandco** [comment]
It is not self hosted, it is a PaaS. For me it is enough to be reachable once I login to the cluster.

**Comment by stevenGravy** [comment]
As mentioned we do not support that yet. For Azure, it can connect to a self-host postgresql db where the certs can be installed.

**Comment by gabrieloandco** [comment]
I'll close the issue then.
