### ISSUE TITLE
Can we increase the teleport-proxy timeout?

### ISSUE THREAD

**Issue by liyuankui** [gravitational/teleport#799]
A console will disconnect if idle for about one minute, can we increase it?

**Comment by klizhentas** [comment]
Yes 2.0 has adjustable session timeouts

**Comment by klizhentas** [comment]
sorry, as a follow up - 2.0 is coming really soon and we have adjustable session timeouts based on RBAC both for web and SSH sessions.

**Comment by klizhentas** [comment]
I'm going to close this issue for now, meanwhile watch for news on our email list or on twitter for updates
