### ISSUE TITLE
Make it possible to specify static join token in helm chart teleport-cluster

### ISSUE THREAD

**Issue by jonaskello** [gravitational/teleport#8003]
### What
Specify static join token in helm chart teleport-cluster

### How
Add to helm chart template

### Why
I want a simpler setup without the complexity of dynamic join tokens

### Workaround
Use helm chart in custom mode, however this disables a lot of the helm chart I still want to have, like acme support.

**Comment by jonaskello** [comment]
It would also be nice if we could set ca-pin in the `teleport-kube-agent`.

**Comment by webvictim** [comment]
I'm afraid we won't be adding this functionality to the Helm chart. Static tokens are essentially passwords, and Teleport's philosophy is to eliminate passwords wherever possible. Dynamic tokens with a short TTL should always be used. 

Please feel free to maintain your own fork of the Helm chart which implements this functionality.
