### ISSUE TITLE
Update Okta SSO integration instructions

### ISSUE THREAD

**Issue by nick-oh** [gravitational/teleport#8004]
## Details
In my view, the picture of Okta integration description is wrong.

The description of the values that must be entered in ATTRIBUTE STATEMENTS in the description is different from the value of the captured image as an example of this.

In SINGLE ATTRIBUTE STATEMENTS, the value of Name should be Username, Name format should be Unspecified, and Value should be user.login. However, the captured picture is Name: email, Name format: Basic, Value: user.email.

It seems that the image needs to be modified to match the captured image and the description.

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
Yes, this was resolved in #23053, thanks for tagging me. And thanks @nick-oh for the issue!
