### ISSUE TITLE
Add tutorial pop-ups to showcase new features in Teleport UI.

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#8005]
### What

Many modern web apps will have temporary CSS-style popups to showcase new features or guide a user on how to navigate a user interface upon first logging into the app.

It would be a really nice customer/user experience to have something similar for users when logging into the Teleport UI.

Example from a recent Gmail update:

<img width="593" alt="Screen Shot 2021-08-20 at 8 20 56 AM" src="https://user-images.githubusercontent.com/1424442/130238328-a6b4fb19-e827-48a5-b6cf-2f0067f81ad8.png">

Thanks to @colinedwardwood for the original idea!

### How
Assuming it is CSS-driven but having guided popups on the Teleport UI to showcase certain features. Ala, a light tutorial.

### Why

To make Teleport more awesome. And to help ease new users into the UI (as it can be overwhelming upon first logging in - the What do I do now?)

### Workaround

None. Feature does not exist.

**Comment by zmb3** [comment]
Closing as not planned. If we do decide to do this, it will be as part of a new effort and not because we stumbled across a 2+ year old issue
