### ISSUE TITLE
Command executions audit log description uses the node IP, not node name

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#8042]
### Description

**What happened**:
Command Execution audit log entry descriptions show a IP:port number instead of the node name.  

![image](https://user-images.githubusercontent.com/60704961/130639365-88ae0061-aaed-4fda-aae5-a10168218b07.png)

**What you expected to happen**:

The node name should show, not a IP. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. run a command execution `tsh ssh root@node ls /tmp`
2. View the audit log
3.

### Server Details
- Teleport version (run `teleport version`): 7.0.3
- Server OS (e.g. from `/etc/os-release`): ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): aws

**Comment by zmb3** [comment]
This was fixed in https://github.com/gravitational/webapps/pull/1089
