### ISSUE TITLE
PagerDuty plugin documentation is no longer accurate

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#8044]
## Details
The PagerDuty plugin documentation is no longer accurate: https://goteleport.com/docs/enterprise/workflow/ssh-approval-pagerduty/

It should be updated with this: https://github.com/gravitational/teleport-plugins/blob/master/access/pagerduty/README.md

### Category
- Improve Existing

**Comment by ptgott** [comment]
We have updated this guide in 7204503cca9223740d3f5868ccdfacb32fd2b1d3
