### ISSUE TITLE
Oracle DB Support

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#8064]
### What
Add Oracle DB support

### Why
Hearing from customers that have large and multiple Oracle DB's in their environment that they would like to see Teleport support this.

### Workaround
None at the moment.

**Comment by savv3** [comment]
We would be very interested in this

**Comment by juwilie** [comment]
Hello @r0mant? Any updates on that request? It was planned for 9.0 but feature is not there

**Comment by pschisa** [comment]
@r0mant @smallinsky Any updates on a possible timeline for this feature?

**Comment by r0mant** [comment]
@pschisa It might get scheduled for Q1.

**Comment by pschisa** [comment]
Do we have any insight into the GUI tools that will be tested/supported?  Support for  [Toad](https://www.quest.com/products/toad-for-oracle/) has been requested

**Comment by smallinsky** [comment]
> Do we have any insight into the GUI tools that will be tested/supported? Support for [Toad](https://www.quest.com/products/toad-for-oracle/) has been requested

Not yet, I will check this windows/client in next week.

**Comment by benarent** [comment]
Database Access with Oracle can now be closed. https://goteleport.com/docs/database-access/guides/oracle-self-hosted/
