### ISSUE TITLE
Use CIS hardened images for Teleport published AMIs/Containers

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#8078]
### What
Request is to see Teleport use CIS hardened images or harden the Teleport images following CIS benchmark guidelines for Teleport published AMIs.

### How
Either use a provided CIS hardened image (https://www.cisecurity.org/cis-hardened-image-list/) as a base or follow the benchmark guidelines (https://www.cisecurity.org/cis-benchmarks/) when building the Teleport AMIs

### Why
Better out-of-the-box security for Teleport AMIs and helpful for those that require CIS hardening for security audits.

### Workaround
Build a customer CIS hardened AMI running Teleport

gz#4441

**Comment by electricthunder** [comment]
CIS hardening would be great, minimal vulnerabilities is the main challenge - we can CIS harden the images ourselves but if there are a bunch of vulnerabilities found, then it's going to cause issues for compliance exercises with remediation timelines associated.

Does this scope of work include looking to migrate to more minimal containers / AMIs with less vulnerabilities? like Amazon Linux, Alpine, possibly RHEL?

**Comment by moisesmejia1200** [comment]
Team, would we have an  ETA for CIS hardened Image of kube-agent?

**Comment by r0mant** [comment]
This was implemented in 12 and 13, see distroless Docker images instructions here: https://goteleport.com/docs/installation/#docker.
