### ISSUE TITLE
Add documentation for the Jira Plugins status endpoint and new config parameter

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#8086]
## Details
https://github.com/gravitational/teleport-plugins/pull/240 has added a new `/status` endpoint to the Jira plugin.

https://github.com/gravitational/teleport-plugins/pull/238 has added a new `type` parameter to the configuration to allow for setting the Jira type to a custom value other than task.

Both of these updates should be incorporated into the Jira plugin documentation for users to be able to easily know about and utilize these new features
https://goteleport.com/docs/enterprise/workflow/ssh-approval-jira-cloud/
https://goteleport.com/docs/enterprise/workflow/ssh-approval-jira-server/

### Category
- New Feature
- Improve Existing

**Comment by ptgott** [comment]
Folding this into our overall project to refresh the JIRA guide (https://github.com/gravitational/teleport/issues/14580).
