### ISSUE TITLE
ability to filter when listing kube clusters

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#8087]
### What

currently, `tsh kube ls` simply dumps every single kube cluster.

It should have the ability to apply filters to that list to programmatically grab resource names by label or other criteria.

In the use case where this feature request came up, kubernetes clusters are ephemeral and can have a different name as they go through their lifecycle. The idea is to filter on label by expressions such as "env=prod and client=acme" to hit the Acme Inc production cluster that may have a randomized portion of the resource name.

Additionally, having this filter functionality in `tsh kube login` to specify which cluster to access by a filter expression would make things a little simpler for this usecase.

### How

```
tsh kube ls --label env=production,client=acme -f name
```

Help info for these new options might look like this:

```

   --label           List of comma separated labels or label=value pairs to apply to the list as a filter.
   -f, --format      Format output (text, json, names)

```

The `--label` functionality should allow for multiple labels to be passed together. I would expect that AND is the correct behavior here, but someone may want OR functionality as well.

The `-f, --format` option would give it parity with `tsh ls -f` functionality. For cases where simple label filtering isn't quite enough, the json structured data is easily processed. The `tsh ls -v` option may be appropriate here too (again, for parity)

### Why

With no machine parseable friendly way to list all kube clusters that meet certain criteria, finding the correct cluster name is annoying and manual in this environment. Adding the ability to list or specify a resource with a filter expression will speed up workflows and deal with the ephemeral resource names.

### Workaround

One would need to try to use shell scripting, sed, awk, or implement their own teleport client to grab the data in a filterable/sortable format.

**Comment by roobeshm** [comment]
Do we have any update on when this can be expected ?

**Comment by roobeshm** [comment]
Can we get this prioritized and target to get in next releases ? This will help us in many ways for users to quickly filter when there a huge list of kubes.

**Comment by r0mant** [comment]
@roobeshm Latest Teleport version supports both advanced label filtering and output formats:

```
$ tsh kube ls --help
...
      --query                    Query by predicate language enclosed in single quotes. Supports ==, !=, &&, and || (e.g. --query='labels["key1"] ==
                                 "value1" && labels["key2"] != "value2"')
  -f, --format                   Format output (text, json, yaml)
```

Take a look at https://goteleport.com/docs/setup/reference/predicate-language/#resource-filtering for predicate language reference.

Does this solve your issue?

**Comment by r0mant** [comment]
Like I mentioned below, it should now be supported, feel free to reopen if something's still missing.

**Comment by roobeshm** [comment]
Thank you @r0mant , so this is supported in latest version 9 and not in 8.3.10 right ?

**Comment by r0mant** [comment]
@roobeshm Yes.

**Comment by roobeshm** [comment]
@r0mant  do you know in which version of v9 ? I am hesitant to go with v9.2.1 at this point(due to other issues), is this feature available from any 9 version ? Like 9.1.1 or 9.1.3 ?

**Comment by kylern** [comment]
@roobeshm please upgrade to v9.2.3

**Comment by roobeshm** [comment]
Thanks, tested and working.
