### ISSUE TITLE
With OIDC and role mapping, MaxSessionTTL check cannot be passed from web session.

### ISSUE THREAD

**Issue by brumfb** [gravitational/teleport#809]
I believe this commit: https://github.com/gravitational/teleport/commit/d6ff6f62048b9abfa1b3a377435c92b843c6d5ca#diff-e84082ce87963ba1d7d85b48fe926693 introduced a bug where the ttl check cannot be passed as the ttl value is set to the role's MaxSessionTTL.  This prevents the user from logging into a web session.  You can see the MaxSessionTTL is adjusted here (https://github.com/gravitational/teleport/blob/master/lib/services/role.go#L408) and then later is expected to be _less_ than that value (https://github.com/gravitational/teleport/blob/master/lib/services/role.go#L420).  

This adjustment call is made from https://github.com/gravitational/teleport/blob/master/lib/auth/auth.go#L626, so the adjustment takes place if the default CertDuration is longer than the role's MaxSessionTTL.

**Comment by klizhentas** [comment]
@brumfb good catch, looking into it now, although I'm trying to figure out why I can't reproduce :/

**Comment by brumfb** [comment]
It only occurs through a web session, I think, so if you are trying via tsh behavior might be different.

**Comment by klizhentas** [comment]
@brumfb I'm trying to trigger it via web session, but can't for some reason

**Comment by klizhentas** [comment]
I know I should as the code flow you outlined should not work, properly, digging

**Comment by klizhentas** [comment]
@brumfb can you confirm with latest master that your issue is fixed?

**Comment by brumfb** [comment]
Yes, I'm sure that will fix it.  That is the fix I applied in my local version to initially get around the issue.  Thanks for the quick turnaround.
