### ISSUE TITLE
Sign macOS tar archive

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#8092]
**Description**

Support for signing macOS packages was added in https://github.com/gravitational/teleport/issues/7076, but the binaries in the tar archive remain unsigned. No technical exists for why the binaries in the tar archive can not be signed.

**Comment by r0mant** [comment]
The last remaining bit here is to add signing to enterprise tarballs as well, tracked in https://github.com/gravitational/teleport.e/issues/741. After that we can close this.
