### ISSUE TITLE
Upgrade from 6.2.8 to 7.1.0 on Linux amd64 is resulting in internal error; operation insecure.

### ISSUE THREAD

**Issue by joshdurbin** [gravitational/teleport#8109]
### Description

**What happened**:

After upgrading from Teleport 6.2.8 to 7.1.0 on Linux amd64, an internal error is experienced when trying to SSH to infrastructure. The specific message from the internal error is "The operation is insecure." I don't see anything in the changeling that would obviously point to a change that would break things, so I'm opening this as a bug.

**What you expected to happen**:

Session initiation to target teleport-nodes.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Upgrade version to 7.1.0
2. Attempt to SSH to a teleport node via the Teleport web interface (not tsh)
3. Receive error
4. Restarts of all Teleport nodes/roles does not resolve the issue

### Server Details
- Happens on 7.1.0 amd64 but does not happen on 6.2.8 (we pin-ed / downgraded after observing this)
- Server OS (e.g. from `/etc/os-release`): Debian Buster 
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP
- Additional details: The system users that Teleport users are trying to initiate sessions as are special; they have special shell assignments that lock them into a ncurses-like flow. In the example below, the `container-jump` user uses this functionality to access our Nomad Container environment workloads (not k8s).

```
[integration][us-central1][root@teleport-node-fsd3]:/var/lib/teleport# cat /etc/passwd | grep jump
container-jump:x:20070:1012:Container Jump User:/home/container-jump:/usr/bin/container-jump
db-jump:x:20071:1013:DB Jump User:/home/db-jump:/usr/bin/db-jump
```

```
[integration][us-central1][root@teleport-auth-8g9p]:~# tctl get role --format json | jq '.[] | select(.metadata.name=="jump-user")'
{
  "kind": "role",
  "version": "v3",
  "metadata": {
    "name": "jump-user",
    "id": 1595959534340603600
  },
  "spec": {
    "options": {
      "forward_agent": false,
      "max_session_ttl": "8h0m0s",
      "port_forwarding": false,
      "cert_format": "standard",
      "enhanced_recording": [
        "command",
        "network"
      ]
    },
    "allow": {
      "logins": [
        "container-jump",
        "db-jump"
      ],
      "node_labels": {
        "*": "*"
      },
      "rules": [
        {
          "resources": [
            "session"
          ],
          "verbs": [
            "list",
            "read"
          ]
        }
      ],
      "app_labels": {
        "*": "*"
      },
      "kubernetes_labels": {
        "*": "*"
      },
      "db_labels": {
        "*": "*"
      }
    },
    "deny": {}
  }
}
```

### Client Details
- Tsh version (`tsh version`): n/a
- Computer OS (e.g. Linux, macOS, Windows): n/a
- Browser version (for UI-related issues): n/a
- Installed via (e.g. apt, yum, brew, website download): n/a
- Additional details: n/a

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

### Screenshots

<img width="1436" alt="Screen Shot 2021-08-31 at 13 33 54" src="https://user-images.githubusercontent.com/532881/131572346-de4bd841-23cf-4cfd-94d9-53e1265e9293.png">

**Comment by stevenGravy** [comment]
@joshdurbin this is due to #7928 . That will be fixed in a upcoming release.  Other browsers should work.

**Comment by joshdurbin** [comment]
Thanks!
