### ISSUE TITLE
Make the audit log clear if a session network request has been denied. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#8126]
### Description

**What happened**:

We can differentiate blocked session requests by there action field. Enhanced Recording sets the action to 0 (OBSERVED) while Restricted Session sets this value to 1 (DENIED).  This makes it hard to debug and figure out if someone accidentally blocked all traffic. 

https://goteleport.com/docs/server-access/guides/restricted-session/#step-44-inspect-logs

But it's very unclear on the audit log. 

![image](https://user-images.githubusercontent.com/559288/131758901-853d69d7-b426-48f4-8750-0af7d3ab3b87.png)

```
{
  "action": 1,
  "cgroup_id": 2583,
  "cluster_name": "teleport-7.asteroid.earth",
  "code": "T4002I",
  "dst_addr": "142.250.69.206",
  "dst_port": 443,
  "ei": 25,
  "event": "session.network",
  "login": "root",
  "namespace": "default",
  "operation": 0,
  "pid": 16091,
  "program": "curl",
  "server_id": "9b3902b7-db13-49cc-96f1-c4e94d268ad7",
  "sid": "adb71255-ac6a-42ff-8584-9616f8e79484",
  "src_addr": "0.0.0.0",
  "time": "2021-09-01T23:29:31.981Z",
  "uid": "a4993e66-4581-4849-8ab1-e2249bfb4ddd",
  "user": "benarent",
  "version": 4
}
```

```
{
  "action": 0,
  "cgroup_id": 2583,
  "cluster_name": "teleport-7.asteroid.earth",
  "code": "T4002I",
  "dst_addr": "142.250.69.206",
  "dst_port": 443,
  "ei": 33,
  "event": "session.network",
  "login": "root",
  "namespace": "default",
  "operation": 0,
  "pid": 16095,
  "program": "curl",
  "server_id": "9b3902b7-db13-49cc-96f1-c4e94d268ad7",
  "sid": "adb71255-ac6a-42ff-8584-9616f8e79484",
  "src_addr": "10.0.0.234",
  "time": "2021-09-01T23:30:34.695Z",
  "uid": "57b9ed4d-b21b-41be-ad69-994d72ffa3d9",
  "user": "benarent",
  "version": 4
}
```
**What you expected to happen**:

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.
2.
3.

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by zmb3** [comment]
Network restrictions have been removed from the product, so this is no longer relevant.
