### ISSUE TITLE
Web UI downloads dozens of megabytes of data to display node list

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#8147]
### Description

Customer reported that the Web UI downloads dozens of megabytes to display the list of nodes. This customer has 30k nodes.

### Proposed Solution

Teleport now supports a paginated list of nodes, instead of pulling down all servers, Teleport should display a paginated list.

**Comment by zmb3** [comment]
Closing this as the server side pagination in 9.2 should address it.
