### ISSUE TITLE
Add filtering by events for audit log screen

### ISSUE THREAD

**Issue by kimlisa** [gravitational/teleport#8155]
### What
For the UI audit log screen, allow users to filter by event type ie: `user.login`, `app.session.start`, `session.end`, etc

### Demo
Demo of how it would work like (not the final design):

![filter-extend4](https://user-images.githubusercontent.com/43280172/132389885-00a93c24-7064-431b-b9ba-c2d96afbc1b7.gif)

### Why
- To allow users to browse audit log by event types
- Avoid confusion resulting from sparse results with pagination + search bar filtering. The search bar filters by the current set of results and the results may or may not include what they are looking for. This can result in a empty table and a confusing `fetch more` button (which again may or may not include what they are looking for). To avoid this, we should clear the search bar per `fetch more`

**Comment by stevenGravy** [comment]
be neat to be able to have a version where you could save the filters

**Comment by zmb3** [comment]
Combining this with #5844
