### ISSUE TITLE
Deb repo inconsistent versions available

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#8166]
### Description

It seems that with build infrastructure only one version is available at a time, and a build run modifies the version from 7.x to 6.x is back based on what last build has been run.

For example:

teleport 7.x back disappeared from  `https://deb.releases.teleport.dev/ stable main`  and now there is only 6.x there

**Comment by keenan-v1** [comment]
This is a huge blocker right now as our infrastructure is designed to use apt to install Teleport.

**Comment by wadells** [comment]
Recommended workaround, until we refactor the apt repositories:

Do not use the repo, instead, download and install your prefered `teleport`, `teleport-ent`, or `teleport-ent-fips` deb directly:

```console
$ curl -O https://get.gravitational.com/teleport_7.3.3_amd64.deb
# snip ...
$ apt install ./teleport_7.3.3_amd64.deb
# snip ....
Setting up teleport (7.3.3) ...
$ teleport version
Teleport v7.3.3 git:v7.3.3-0-g47ccf9e5f go1.16.2
```

**Comment by webvictim** [comment]
Got hit by this myself today.
