### ISSUE TITLE
Treat empty-string role match criteria with an OR operator

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#8167]
### What
Currently any explicit label key that is added to a role's label match criteria is automatically treated with an AND operand and is then required to exist on the node in order for a node to match and be visible. For example:

```
  allow:
    app_labels:
      env: xxx
      dept: xxx
```
In order for a node to match it must have both 'env' and 'dept' labels configured. If a node is missing either of these, it will not match and will not be visible. However, if only one of these is used as a match criteria (say `env: xxx`), nodes with and without the `dept:` label will match so long as they have the `env:xxx` label configured. This presents an issue in scenarios where a customer may wish to match all nodes labeled with an `env` and `dept` labels, but exclude those that also have a specific `project` label, for example. As soon as the `project` label is added to the match criteria, all of the other nodes with the matching `env` and `dept` but lacking the `project` label become invisible. If the `project` label is left off, however, an admin cannot exclude specific nodes that do include it on a selective basis as required. 

Using the explicit deny statements does not work as a workaround in this case as it does not allow for role stacking, so users who later assume a role that grants temporary access the the previously-denied `project` nodes will still be unable to see them due to the fact that deny statements take precedence over the allow statements. 

The ask is to allow for users in the above scenario to be able to selectively match nodes with the `project` label for exclusion without invalidating all the previously matched criteria.

### How
Allowing users to configure an empty project value (`project: ""`) as a match criteria should treat all nodes without a `project` label effectively as if they had the `project` label key configured on them (thus allowing them to get around the AND operand), but exclude those that actually have a specific `project` values configured (such as `project: test`). 

This gives admins the ability to keep all nodes that previously matched the `env` and `dept` criteria visible, including those without an explicit `project` label key configured on the node, while also giving them the ability to exclude those that do have the `project` label key configured with anything other than a blank value.

### Why
Customer ask.

### Workaround
No real workaround currently exists. Only way to accomplish the above is for an admin to roll out the `project` label key to ALL nodes, and then only match for those that don't contain the value they want to exclude. This can get problematic with large resources that are spread out among numerous environments and may belong to different departments...etc.

**Comment by zmb3** [comment]
@nklaassen is this solved by label expressions?

**Comment by nklaassen** [comment]
I'd say it is, you could have a role this this to allow access to nodes with matching env and dept, and no project:
```yaml
spec:
  allow:
    node_labels_expression: |
      labels["env"] == "xxx" && labels["dept"] == "xxx" && labels["project"] == ""
```
