### ISSUE TITLE
Support Webauthn in the Web UI

### ISSUE THREAD

**Issue by codingllama** [gravitational/teleport#8192]
### What

Webauthn is the new hotness for MFA support. It is backwards compatible with U2F and allows a slew of new login methods (such as Touch ID).

Relevant links:

* https://github.com/gravitational/teleport/blob/master/rfd/0040-webauthn-support.md (RFD)
* https://github.com/gravitational/teleport/issues/6478 (server-side feature request)

### How

Server-side login support for Webauthn is already implemented (landed with https://github.com/gravitational/teleport/pull/8094, used by tsh login since https://github.com/gravitational/teleport/pull/8176).

Implementation in modern browsers is fairly straightforward: in a nutshell, you call [navigator.credentials.get](https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/get) for login and [navigator.credentials.create](https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/create) for registration.

Relevant API endpoints are `/webapi/mfa/login/begin` and `/webapi/mfa/login/finishsession` - there are webauthn fields in both for transport of the necessary data. Everything is compatible with the reference implementation, duo-labs/webauthn, so it should be simple to adapt [example webauthn code](https://github.com/hbolimovsky/webauthn-example/blob/master/index.html) to our needs.

Some nice introductory links are:

* https://webauthn.io
* https://webauthn.guide

If any questions arise shout me, I'd be happy to help.

### Why

Webauthn support is the pathway to features we really want, such as Touch ID support.

### Workaround

Be sad and never use Touch ID in the web.

**Comment by codingllama** [comment]
Tagging a few people for awareness: @alex-kovoy @russjones @klizhentas

**Comment by codingllama** [comment]
At this very moment login is support, but registration is on the way. You can login with Webauthn using registered U2F devices, so don't let that stop you. I'm raising the feature now so folks have time to catch up, I'm hoping that by then I'll have registration ready for you as well.

**Comment by codingllama** [comment]
I've just put together a toy web interface to exercise webauthn at https://github.com/gravitational/teleport/pull/8326 - it is a good starting point for the actual web integration.

**Comment by benarent** [comment]
> but registration is on the way.

I was just setting up a demo enviroment, it would be great to provide new users the option of using u2f or otp. We added support with 'optional' but the user needs to add OTP firs

**Comment by kimlisa** [comment]
done with:
https://github.com/gravitational/teleport/pull/8642
https://github.com/gravitational/teleport/pull/8559
https://github.com/gravitational/webapps/pull/423
https://github.com/gravitational/webapps/pull/421
https://github.com/gravitational/webapps/pull/418
