### ISSUE TITLE
Invalid BUILDBOX_PASSWORD does not reliably cause tag builds to fail

### ISSUE THREAD

**Issue by wadells** [gravitational/teleport#8208]
### Description

**What happened**:
The 7.0.0-dev.52 release failed while unlocking the builder keychain:

```console
+ set -u
+ cd $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
+ export VERSION=$(cat $WORKSPACE_DIR/go/.version.txt)
+ export HOME=/Users/build
+ security unlock-keychain -p ${BUILDBOX_PASSWORD} login.keychain
security: SecKeychainUnlock login.keychain: The user name or passphrase you entered is not correct.
```

As seen at:

https://drone.teleport.dev/gravitational/teleport/4150/13/4

Stemming from this code:

https://github.com/gravitational/teleport/blob/5662732d7a9ec8b1c65cb6c529f5984e91fa26d5/dronegen/mac_pkg.go#L108-L122

This is because the credential in Drone's `BUILDBOX_PASSWORD` secret is incorrect.  Fixing that is out of scope for this issue (but I'll take care of that shortly in the ops repo). What I'm concerned about, is that we didn't notice this invalid credential for months, because `security unlock-keychain` doesn't fail if a invalid password is provided -- so long as the keychain is already unlocked.

```console
build@buildbox-intel ~ % security unlock-keychain -p totally-bogus-password login.keychain
build@buildbox-intel ~ % echo $?                                                           
0
```

The issue only triggered because I rebooted `buildbox-intel` last Friday to apply apple security updates.

**What you expected to happen**:

I'd like our build automation to reliably fail if `BUILDBOX_PASSWORD` is incorrect (or there are other keychain issues) so that we notice immediately, instead of months down the line when the builder is rebooted for security patches.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Change `build@buildbox-intel`'s password
3. Reboot `buildbox-intel` or run `security lock-keychain login.keychain` as the build user 
4. Watch the next release fail

**Comment by wadells** [comment]
cc @webvictim @russjones @quinqu @tcsc

**Comment by webvictim** [comment]
Interesting - I didn't realise that the keychain would be unlocked perpetually. Maybe the pre-build step should be updated to lock the keychain as a prerequisite?

**Comment by wadells** [comment]
`buildbox-intel` died on its own of old age, as documented in https://github.com/gravitational/teleport.e/issues/2275.

We're not replacing it -- instead using cross compilation or GitHub Actions built in Mac runners to take care of the workflows.  As such, we won't hit this same code path anymore.  No need to keep this open.
