### ISSUE TITLE
Remove dependance on unmanaged keychain state during Mac builds

### ISSUE THREAD

**Issue by wadells** [gravitational/teleport#8210]
### What
During Teleport's Mac signing process, it relies on unmanaged state on its buildbox.  Specifically,
the presence of the correct certificates preloaded in the login keychain:

https://github.com/gravitational/teleport/blob/f825d4558c1de466957577d4d973589a85d49077/.drone.yml#L2812-L2813

https://github.com/gravitational/teleport/blob/5662732d7a9ec8b1c65cb6c529f5984e91fa26d5/build.assets/build-package.sh#L71-L73

I'd like to remove this requirement -- such that all signing certificates/keys are managed as release secrets, and we have the appropriate automation to leverage those secrets on mac builders with an default/empty keychains.

### How
I have an untested hypothesis we could use a workflow like:

1. Load the apple signing certificates via a base64'd tar, similar to [linux](https://github.com/gravitational/teleport/blob/5662732d7a9ec8b1c65cb6c529f5984e91fa26d5/.drone.yml#L1710) or [windows](https://github.com/gravitational/teleport/blob/5662732d7a9ec8b1c65cb6c529f5984e91fa26d5/.drone.yml#L3626).
2. Create a randomized, temporary, dedicated keychain using `security create-keychain`.  Lets call it `KCX`
3. trap `security delete-keychain <KCX>`
4. Load the signing certificates into the new keychain `KCX`
5. `codesign --keychain <KCX> ...` / `productsign --keychain <KCX> ...` (maybe these are different secrets/tarballs even)
6. Make sure to certs on disk and keychain is cleaned up before terminating the build

### Why
This sensitive certificate data is not managed like any other secrets in the Teleport release process -- it is installed by hand on the builders and left lying around on the boxes after the build is done. Exceptions like this create security and reliability risks as folks are less likely to consider the implications of them during future changes.

Furthermore, reliance on the login keychain:

https://github.com/gravitational/teleport/blob/f825d4558c1de466957577d4d973589a85d49077/.drone.yml#L2812-L2813

Means the login info for this user is available in the drone secrets.  This is worry some as ssh and vnc are currently available on these builders.

**Comment by wadells** [comment]
See #8208 for the failure that sparked this, and #8092 for related, contemporary work.

**Comment by wadells** [comment]
cc @webvictim @russjones @tcsc @quinqu @timothyb89 @kbence

**Comment by webvictim** [comment]
Yep, great idea. Ephemeral keychain seems like a good way to solve it.

**Comment by zmb3** [comment]
This needs to also work with Electron, where we don't explicitly call `codesign` or `productsign`.
