### ISSUE TITLE
Caching for JS file 

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/teleport#8219]
### Description
Getting a warning from Semrush for the teleport js file served on signup pages. Can we enable caching for this? Thanks. 

![image](https://user-images.githubusercontent.com/407237/133133347-be2011b0-9100-4587-9cfc-0d63c848ab94.png)

**Comment by alex-kovoy** [comment]
this file comes with recapcha keys to avoid consequent request to the server, if `Semrush` stats is really important, we can set the following headers (5 min).

```
age: 120
cache-control: public, max-age=300
```
