### ISSUE TITLE
Cloud SQL for MySQL not getting a port on proxy server

### ISSUE THREAD

**Issue by Anchorist** [gravitational/teleport#8240]
### Description

**What happened**:

`db_service` does not spawn port "3036"

**What you expected to happen**:

Port given by `tsh db login <db-name>` in `~/.my.cnf` to be proper one

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Configure teleport via `/etc/teleport.yaml`, enable all services, use `public_addr`
2. Configure Cloud SQL for MySQL in `/etc/teleport.yaml`
3. `tsh login` to proxy

### Server Details
- Teleport version (run `teleport version`): 7.1
- Server OS (e.g. from `/etc/os-release`): Debian 10 (Buster)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP
- Additional details:

### Client Details
- Tsh version (`tsh version`): `Teleport v7.1.0 git:v7.1.0-0-gb52a7d89f go1.16.2`
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): on Debian via pkg, on macOS via pkg
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`): Nothing relevant shows, db.init went successfully.
- Run tsh with --debug flag (`tsh --debug`) ` tsh db login cloudsql --debug 
ERROR: unexpected --debug`

netstat output
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      502/sshd
tcp6       0      0 :::3080                 :::*                    LISTEN      8865/teleport
tcp6       0      0 :::3022                 :::*                    LISTEN      8865/teleport
tcp6       0      0 :::3023                 :::*                    LISTEN      8865/teleport
tcp6       0      0 :::3024                 :::*                    LISTEN      8865/teleport
tcp6       0      0 :::3025                 :::*                    LISTEN      8865/teleport
tcp6       0      0 :::22                   :::*                    LISTEN      502/sshd
```

my.cnf
```
[client_teleport-cloudsql]
host=<redacted>
port=3036
ssl-mode=VERIFY_IDENTITY
ssl-ca=/Users/<redacted>/.tsh/keys/<redacted>/certs.pem
ssl-cert=/Users/<redacted>/.tsh/keys/<redacted>/teleport-admin-db/teleport/cloudsql-x509.pem
ssl-key=/Users/<redacted>/.tsh/keys/<redacted>/teleport-admin
```

**Comment by stevenGravy** [comment]
@Anchorist the proxy service needs to have the mysql port defined. db service does not maintain the ports exposed on the proxy. https://goteleport.com/docs/database-access/reference/configuration/#proxy-configuration

**Comment by Anchorist** [comment]
thanks @stevenGravy , https://goteleport.com/docs/ver/7.0/database-access/guides/mysql-cloudsql/#setup-teleport-database-service example has proxy_service as `enabled: "no"`, how to understand this?

**Comment by stevenGravy** [comment]
@Anchorist that's a situation where you are running the database service on a different machine. The auth server address there points and registers through the proxy service.  So in that case the user connects to the proxy service on the server machine and the database service is deployed on another machine.  If you look at this diagram you'll see the database service is separate from the proxy service. https://goteleport.com/docs/database-access/architecture/

**Comment by Anchorist** [comment]
Ok I get it, thanks!
