### ISSUE TITLE
kubernetes_groups and kubernetes_users traits always empty

### ISSUE THREAD

**Issue by ognjenVlad** [gravitational/teleport#8300]
### Description
Can not access GitHub claims on Self Hosted community Teleport

### What happened:
Added kube_groups and kube_users to teams_to_logins, tsh showing empty traits for kubernetes_groups and kubernetes_users

### What you expected to happen:
Traits are populated and can be accessible with external prefix?

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Add kube_groups and kube_users to teams_to_logins
2. Try to use them inside role templates 

### Server Details
- Teleport version (run `teleport version`): 7.1.2
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS 
- Additional details: Standalone teleport server

### Client Details
- Tsh version (`tsh version`): 7.1.2
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download): website download
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by aharper273** [comment]
Have you found a workaround for this?
