### ISSUE TITLE
Select actual line text and Paste not working.

### ISSUE THREAD

**Issue by noriuky** [gravitational/teleport#833]
Hi, i've read older post and still not working.
I try to copy text from the actual cursor row but it's impossible, the selection vanish togheter with cursor blinking.

right click of mouse never show Paste,
CTRA+a  work but not following CTRL+v

still not working plz add also SHIFT+ins (paste) and CTRL+ins (copy)

**Comment by alex-kovoy** [comment]
Could you tell more about your environment? 
- What browser/OS do you have on your client?
- What OS is running on your server (node)?

**Comment by noriuky** [comment]
Sure sry i forgot.
My server run Centos7
i use firefox on win10

**Comment by tidalf** [comment]
this pr for term.js seems to fix the copy + paste for me : https://github.com/chjj/term.js/pull/97

**Comment by noriuky** [comment]
Ok can you explain how to install this and where? i'm not expert of this.
it should be on server or on client side?
did this fix also the (cursor key UP) not working on teleport too.
is useful to call prev commands.

**Comment by kontsevoy** [comment]
@noriuky this is now incorporated into Teleport 2.2
