### ISSUE TITLE
Helm - Configurable Storage Class

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#8343]
### What
Create a variable to allow for a storage class other than the default

### How
Add a new variable to override the default storage class

### Why
Some storage providers may have multiple default storage classes and this causes helm to crash mid install

### Workaround
Ensure your cluster only has one default storage class

**Comment by webvictim** [comment]
This should be achievable now by creating your own `PersistentVolumeClaim` (with a custom `StorageClass`) and passing the name to the chart: https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L83-L85
