### ISSUE TITLE
tsh ls fails with handshake error

### ISSUE THREAD

**Issue by chrisRidgers** [gravitational/teleport#838]
Currently attempting to debug this behaviour:

Running `tsh --insecure --proxy=<auth.domain.name> ssh root@<auth.domain.name>` successfully get's me a shell on my server running an auth server, a proxy, and a node.

However:  running `tsh -d --insecure --proxy=<auth.domain.nam>e ls` get's me this output:

```
ERRO[0000] access denied to login "<username>" when connecting to : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain  file=client/client.go:157 func=client.(*ProxyClient).ConnectToSite
access denied to login "<username>" when connecting to : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

From the server, which is also running verbosely:

```
WARN[3453] conn(<ip_from->ip_to>, user=<username>) ERROR: Failed to authorize user <username>, err: ssh: principal "<username>" not in the set of valid principals for given certificate: ["root"]  file=auth/tun.go:425 func=auth.(*AuthTunnel).keyAuth
```

The setup in question it pretty minimal: one server instance running the auth, node and proxy.  My local box running tsh, and also configured is a second node on a different server.  This setup was working last night: all i did was ssh (none teleport) into my server and run `teleport start --nodename=auth.domain.name`.

The command `tsh --insecure --proxy=auth.domain.name clustsers` appears to work fine.  And a second user on his own device also has this problem attempting to list the nodes but can ssh into them well enough.

**Comment by klizhentas** [comment]
@chrisRidgers try setting username to the one listed in your principal:

`tsh --login=root -d --insecure --proxy=<auth.domain.nam>e ls`

**Comment by chrisRidgers** [comment]
That: worked.

Thanks.

I think I've misunderstood part of the process then:

I thought that tsh would login to teleport using my username (not root), and be validated because there is a similarly named user.

So my local username matches a username in teleport which has mappings to the root user on my nodes: this makes sense because when I ssh in using `root@` syntax this is successful.

But the `tsh ls` command: I presumed I wasn't actually logging into one of my nodes (using any mapping) because I was just querying my auth server (via the proxy) for a list of nodes...  and that the two factor auth of my username-> the teleport user would be sufficient.

What have I missed: am I being logged in to my auth server behind the scenes?  Similar to:

`tsh --proxy=<auth.domain.name> --insecure ssh root@auth.domain.name> tctl nodes ls`

??

I'm not sure that makes sense because I can login to my proxy's web interface using just my username/ password and authenticator... and see the nodes in my cluster... which is essentially what I'm doing during the authentication phase of the `tsh ls` command.

(Apologies for warbling).

**Comment by chrisRidgers** [comment]
As part of another test I granted someone else access to the cluster with a mapping to a user that doesn't exist on my nodes and sure enough he couldn't `tsh ls` even with the `--user` set to the user in my principal.  He could however login to the web proxy using is credentials and see the nodes listed there.

So it appears I can't `tsh ls` unless I have access to my auth/proxy (they're both currently running on the same server) via one of my principal listed users... but I'm not sure I understand why: should it be that restrictive given I've logged in on the CLI with 2FA?

**Comment by klizhentas** [comment]
This limitation comes from the fact that SSH expects your login to match one of the issued principals for your SSH cert, that's why we get this somewhat strange behavior.

**Comment by chrisRidgers** [comment]
And via the web interface/ proxy?

How's it sourcing the list of nodes for me to ssh into?  (The web login doesn't ask me for a username to check with my principals).

**Comment by kontsevoy** [comment]
@chrisRidgers the web UI runs fully authenticated via HTTPS -> Teleport internal auth API. Certificates are not used in that case. I am closing this for now unless there are objections.

**Comment by chrisRidgers** [comment]
@kontsevoy ah right cheers.

Yeh no objections: just trying to understand what's happening where.
