### ISSUE TITLE
Add `mongo_public_addr` and `mongo_listen_addr` to proxy configuration

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#8400]
### What

Similar to `postgres_public_addr` and `mysql_public_addr` we need to add a `mongo_public_addr` proxy configuration setting for cases when MongoDB database access users have their proxy behind an Application Load Balancer.

**Comment by pschisa** [comment]
We should also add the `mongo_listen_addr` proxy configuration setting similar to `postgres_listen_addr` and `mysql_listen_addr` for cases where users need to use the `no-tls-insecure` option with TLS terminated on load balancers

**Comment by vj-gsr** [comment]
@r0mant any chance is this available anytime soon, also meanwhile if we want to have any port other than `web_listen_addr` is this possible?

**Comment by smallinsky** [comment]
Implemented in: https://github.com/gravitational/teleport/pull/9194
