### ISSUE TITLE
Exercise benchmarks in CI

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#8401]
Our CI builds do not exercise benchmarks, making it hard to catch breakages that occur in benchmarks but not tests.

For example, `BenchmarkCheckAccessToServer` has been broken for about 4 months.

At a minimum, ensure that CI runs the benchmarks. As an extra, it might be nice to actually catch performance regressions by failing builds if benchmarks increase greater than some threshold.

**Comment by doggydogworld** [comment]
For now I'll just update the CI build to include benchmarks. Our unit testing should catch any breaking changes introduced to benchmarks.

I think detecting performance regressions is a bit out of scope. There are some considerations around ensuring a reliable baseline to compare against that it probably merits a RFD. I did try looking for an existing RFD for it but couldn't find one so correct me if I just missed it.
