### ISSUE TITLE
When an application user is asked to authenticate again, the browser path is not preserved for after redirection

### ISSUE THREAD

**Issue by ari-becker** [gravitational/teleport#8428]
### Description

**What happened**:
Users will send links to application pages behind Teleport to their colleagues.
If their colleagues have not authenticated recently, Teleport will ask the colleague to authenticate.
After the colleague is authenticated, they are redirected to the application main page, not to the link that the user sent to their colleague.

**What you expected to happen**:
For the link to be preserved.

In context, we have monitoring and alerting set up so that our alerts include links to monitoring dashboards that are behind a Teleport installation. When the user clicks on one of these links, we expect them to see the monitoring dashboard. If the user needs to click the link twice - once to login to the application through Teleport and once to reach the actual monitoring dashboard, then this is a source of friction that affects our Mean Time to Resolution. 

### Reproduction Steps
1. Presume Grafana is set up at `https://grafana.teleport.example.com`
2. Force a logout by going to `https://grafana.teleport.example.com/teleport-logout`
3. In a web browser, go to `https://grafana.teleport.example.com/dashboards`
4. As the user is unauthenticated, Teleport asks the user to authenticate
5. After the user is authenticated, the user is directed to `https://grafana.teleport.example.com` and not to `https://grafana.teleport.example.com/dashboards`

### Server Details
- Teleport version (run `teleport version`): 7.1.1
- Server OS (e.g. from `/etc/os-release`): Official Teleport Enterprise docker image
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Client Details
- Tsh version (`tsh version`): N/A
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Browser version (for UI-related issues): Firefox 92
- Installed via (e.g. apt, yum, brew, website download): N/A
- Additional details: N/A

### Debug Logs
N/A

gz#5647

**Comment by Aharic** [comment]
Confirmed behavior internally.

**Comment by klizhentas** [comment]
this is in progress, @avatus
