### ISSUE TITLE
Support remote port forwarding

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#8432]
### What

Currently, `tsh ssh` only supports local forwards `tsh ssl -L ...`, which corresponds with the openssh `ssh -L` command.

Openssh also supports remote forwards `ssh -R ...`, but tsh ssh does not. Additionally, the teleport ssh_service throws an error if you attempt to use `ssh -R` with a teleport ssh_service, the teleport ssh server throws an error because remote forwarding is not implemented

### How

add tsh ssh -R to the tsh client and make ssh -R work with the teleport service too.

### Why

Remote debugger wants to connect to a port, and a remote forward makes it easy to run code remotely and a local debugger.

### Workaround

nothing clean or easy-- usually a complicated combination of socat, nc, proxies, or other tricks to pipe stuff over stdio.

**Comment by pschisa** [comment]
Similar to https://github.com/gravitational/teleport/issues/7776

**Comment by zmb3** [comment]
Closing as duplicate of #7776
