### ISSUE TITLE
helm teleport/teleport-cluster should be able to expose 3025

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#8444]
### What

The teleport/teleport-cluster helm chart currently does not allow you to expose the auth server at all. There are still usecases where a connection to the auth service without going through a tunnel is desirable.

### How

add a boolean value that controls whether 3025 is included in the service definition for teleport.

### Why

* some third party or custom plugins expect to hit 3025 directly.
* ssh nodes need to interact with 3025 for direct dial mode.
* kubernetes service can also be utilized in direct dial mode when connecting to 3025 instead of the web port.

### Workaround

there is not a good workaround-- at this time, one must fork the chart to get this functionality.

**Comment by fheinecke** [comment]
This was fixed in #18857 and now the 3025 is always available via the k8s service.
