### ISSUE TITLE
Support `mongosh` when connecting to a MongoDB

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#8472]
### What

`tsh db connect` currently uses `mongo` CLI client when connecting to a MongoDB database. `mongo` is obsolete now and is going to be eventually replaced by `mongosh` to `tsh db connect` should support using it too.

### How

`tsh db connect` should try to use `mongosh` and fallback to `mongo` if it's not available.

### Notes

Customers say `mongosh` also handles CA somewhat differently, might require additional tweaks:

> mongosh handles the ca differently too. from my testing, i couldn't get mongosh to use the trusted ca in my system keychain (macos). would be good to add that as something we should try handling too.

**Comment by Tener** [comment]
Do we want an option to force the usage of `mongo` instead of `mongosh`? From the docs `mongosh` does not support all of the options of `mongo` and thus some people may want to use the old client instead. OTOH I believe such users would be better of using `tsh db config --format=cmd` anyways?

**Comment by r0mant** [comment]
@Tener Yeah, with Teleport people would normally use `tsh db connect` command which should use the most appropriate client automatically (try `mongosh` first, then fallback to `mongo`). If folks want to use a specific client, they would just invoke it directly like you mentioned.
