### ISSUE TITLE
[v.7.0] /docs/pages/setup/reference/cli.mdx

### ISSUE THREAD

**Issue by twakes** [gravitational/teleport#8473]
## Details
The "Name" column in the Teleport Start table is very narrow, making it difficult to read.  I've also noticed that our tables split the text in words. It would be nice to prevent that globally and only create newlines in between words or hyphens for better readability.

### Category
- Improve Existing

**Comment by ptgott** [comment]
Closing since we are tracking this in gravitational/docs#126
