### ISSUE TITLE
[v.7.0] /docs/pages/architecture/authentication.mdx

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#8474]
## Details
Correcting a few typos and clarifying some wording.

This part under -- https://goteleport.com/docs/architecture/authentication/?scope=enterprise#issuing-node-certificates

```
<Admonition
  type="tip"
  title="Token TTL"
>
  When using dynamic tokens, their default time to live (TTL) is 30
  minutes, but it can be reduced (not increased) via
  [`tctl nodes add --ttl`](../setup/reference/cli.mdx#tctl-nodes-add) flag.
</Admonition>

```
The wording - `(not increased)` is incorrect. You can set a longer TTL. Maybe clarify the example with something like `tctl nodes add --ttl=10m` or `60m` to show examples of how to set it.

This part under -- https://goteleport.com/docs/architecture/authentication/?scope=enterprise#auth-state

```
- **Recorded Sessions** When Teleport users launch remote shells via `tsh ssh` command, their interactive sessions are recorded and stored by the auth server. Each recorded session is a file that is saved in /var/lib/teleport by default but can also be saved in external storage, like an AWS S3 bucket.
```

Need to put the "/var/lib/teleport" into code format -- `/var/lib/teleport`

This part under -- https://goteleport.com/docs/architecture/authentication/?scope=enterprise#audit-log

```
<Admonition
  type="warning"
  title="Compatibility Warning"
>
  Because all SSH events like `exec` or `session_start` are by default reported by the Teleport node service, they will not be logged if you are using OpenSSH `sshd` daemon on your nodes. [Recording proxy mode](proxy.mdx#recording-proxy-mode)
</Admonition>
```
The URL link is grammatically incorrect. Need to add something like -- `See [Recording proxy mode](proxy.mdx#recording-proxy-mode) for more information.`

### Category

- Improve Existing

**Comment by ptgott** [comment]
We rewrote this guide in 7fc8f4dfd60c5b6bcbaecae68ee7499839d2bf78, so these line edits won't apply—we can create another issue for updated line edits if needed.
