### ISSUE TITLE
Azure Database for MySQL support for database access

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#8482]
### What
Provide support for Msft Azure managed [Azure Database for MySQL](https://azure.microsoft.com/en-us/services/mysql/#security) with database access. 

### How
Utilize the IAM or other protocols supported by Azure to enable a Teleport agent to connect. 

### Why
Provide support for accessing and auditing user connections to Msft Azure MySQL .

### Workaround
None, Azure does not all for certificate configuration as with self-hosted mysqls.

**Comment by r0mant** [comment]
Duplicate of https://github.com/gravitational/teleport/issues/8557 and will be addressed in https://github.com/gravitational/teleport/pull/8951.
