### ISSUE TITLE
Users created without roles causes error in web users list

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#8518]
### Description

**What happened**:

Unable to see the list of users in web console if any of the users are missing any role assignment.  Not sure if users shouldn't be created if no roles are set.

![image](https://user-images.githubusercontent.com/60704961/136460635-683d0686-cfcd-47f9-93db-cd5316272ae9.png)

**What you expected to happen**:
Users are listed.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a user
user.yaml:
```yaml
kind: user
metadata:
  name: jeff
version: v2
```

`tctl create -f user.yaml`
2. Go to Team -> Users in web console

### Server Details
- Teleport version (run `teleport version`): 7.2.0
- Server OS (e.g. from `/etc/os-release`): ubuntu

**Comment by zmb3** [comment]
This is no longer an issue:

<img width="1534" alt="image" src="https://github.com/gravitational/teleport/assets/7527103/81a69c11-a694-4a05-8262-6ecfca439b7d">
