### ISSUE TITLE
Denying the `kube_service` resource in a role prevents tsh login

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#8529]
### Description

**What happened**: In an attempt to hide the Kubernetes tab from the Web UI for users that don't need Kubernetes access, I was directed to deny the `kube_service` resource from the role.  When the `kube_service` resource is denied (at least list and read), the tab does successfully go away but then a user is no longer able to login via `tsh` (Web UI login still works)

~~~
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:61819/02d4a3d0-0caa-4f29-a149-1ecbfe436145
ERROR: rpc error: code = PermissionDenied desc = access denied to perform action 'list' on kube_service
~~~

~~~
ERROR REPORT:
Original Error: *status.Error rpc error: code = PermissionDenied desc = access denied to perform action &#39;list&#39; on kube_service
Stack Trace:
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/client.go:781 github.com/gravitational/teleport/api/client.(*Client).GetKubeServices
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/kube/utils/utils.go:155 github.com/gravitational/teleport/lib/kube/utils.KubeClusterNames
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/kube.go:278 main.fetchKubeClusters.func1
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/client/api.go:461 github.com/gravitational/teleport/lib/client.RetryWithRelogin
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/kube.go:260 main.fetchKubeClusters
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/kube.go:308 main.fetchKubeStatus
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/kube.go:366 main.updateKubeConfig
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:857 main.onLogin
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:597 main.Run
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:266 main.main
	/usr/local/go/src/runtime/proc.go:225 runtime.main
	/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
User Message: rpc error: code = PermissionDenied desc = access denied to perform action &#39;list&#39; on kube_service
~~~

**What you expected to happen**: Login will still succeed via `tsh` with the `kube_service` denied (this is the behavior for the `app_server` and `db_server` resource if hiding their respective UI tabs)

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a role that denies access to the resource `kube_service` to hide the web UI tab
2. Try to login to a user with that role via tsh

### Server Details
- Teleport version (run `teleport version`): tsh version 7.1.3, cluster version 6.2.10

**Comment by zmb3** [comment]
There are several areas where a `tsh login` will attempt to `updateKubeConfig`. In some cases a failure to do so is considered a fatal error. In other cases we attempt to continue the login anyway.

I would say we should not fail on login unless `--kube-cluster` is specified or we're re-logging in to an existing profile that already has `KubeEnabled == true`.

**Comment by webvictim** [comment]
I think `kube_service` has now been updated to `kube_server`. At any rate, the same issue is still present:

```
ERROR: access denied to perform action "list" on "kube_server"
```

**Comment by tigrato** [comment]
@pschisa can you test with the latest version of Teleport?

I recently changed the behavior to not update the kubeconfig on login if you don't manually specify the `--kube-cluster` flag.  #19694

 Since this was a breaking change, it's only available in Teleport 12.

**Comment by pschisa** [comment]
Verified on v12.0.1 auth/proxy and tsh client version that denying the kube_server resource as below
~~~
    rules:
    - resources:
      - kube_server
      verbs:
      - '*'
~~~
denies the Kubernetes web page but still permits a `tsh login`
