### ISSUE TITLE
FIPS build. Debian Repository installs teleport-ent-fips_6.2.14-debug.4_amd64.deb

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#8531]
### Description

**What happened**:
The latest fips build in our Debian repo is an old version of Teleport and appears to be a debug build (teleport-ent-fips_6.2.14-debug.4_amd64.deb).

**What you expected to happen**:
I expect the latest GA Teleport version to be available.

**Comment by wadells** [comment]
This is https://github.com/gravitational/teleport/issues/8166.  `teleport-ent-fips` suffers the same behavior (and root cause) as the `teleport-ent` and `teleport` packages.

**Comment by wadells** [comment]
When I checked just now, I saw:

```
root@d07fedb69dac:/# apt-cache madison teleport         
  teleport | 6.2.18-label-debug.2 | https://deb.releases.teleport.dev stable/main amd64 Packages
root@d07fedb69dac:/# apt-cache madison teleport-ent
teleport-ent | 6.2.18-label-debug.2 | https://deb.releases.teleport.dev stable/main amd64 Packages
root@d07fedb69dac:/# apt-cache madison teleport-ent-fips
teleport-ent-fips | 6.2.18-label-debug.2 | https://deb.releases.teleport.dev stable/main amd64 Packages
```
