### ISSUE TITLE
Desktop Access: determine whether we can enable NLA for additional security

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#8546]
For desktop access, we currently require that [Network Level Authentication (NLA)](https://en.wikipedia.org/wiki/Network_Level_Authentication) is disabled on the target Windows hosts.

NLA is a feature of RDP that when enabled prevents the server from establishing an RDP connection before the user is authenticated. Smart card login appears to operate after the RDP connection is established, so our current assumption is that NLA + passwordless smart card login is not possible.

Confirm whether it is possible to enable NLA with smart card authentication. This could provide an added layer of security by ensuring that RDP sessions are only initiated from the Teleport windows desktop service.

Further reading:

- https://github.com/FreeRDP/FreeRDP/issues/3239
- https://community.rsa.com/t5/securid-access-knowledge-base/how-does-remote-desktop-handle-smart-card-and-nla/ta-p/10459
- https://blog.qdsecurity.se/2021/05/29/remote-desktop-mfa-network-level-authentication-and-kdc-proxy/

**Comment by LordGaav** [comment]
It seems that FreeRDP has implemented NLA + Smartcard: https://github.com/FreeRDP/FreeRDP/pull/7620
