### ISSUE TITLE
Text edit copy/ paste function not behaving correctly in WebUI terminal sessions with Nano

### ISSUE THREAD

**Issue by nickbrennan1** [gravitational/teleport#8549]
When pasting text containing indentations and newlines into a terminal session launched via the WebUI in a Nano session, text is not pasted with the correct formatting - newlines are ignored. This appears to affect sessions using a Macbook.

Affected browsers: 
Chrome Version 94.0.4606.71 
Brave Version 1.30.87 Chromium: 94.0.4606.71
Firefox 93.0
Safari Version 15.0 (16612.1.29.41.4, 16612)

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Launch a webUI session and open a terminal to a Ubuntu 20.04 host
2. Launch a nano session
3. Paste the following text:

  - name: OS
    command: ["/bin/sh", "-c", "/bin/cat /etc/issue| awk '{print $1,$2}'"]
    period: 10h0m0s
  - name: uptime
    command: ['uptime', '-p']
    period: 0h5m0s

This appears to affect all versions of the webUI. SSH sessions launched using `tsh` are not affected. Tested against Ubuntu 20.04, Centos 8.4.2105 and Debian 10.

**Comment by r0mant** [comment]
@nickbrennan1 When you get a chance, could you please confirm the following
- Were you actually able to repro this? _Update:_ Seems like you were. 
- Does this only repro with nano or other editors also.

**Comment by zmb3** [comment]
Works fine for me. Assuming this was fixed sometime between Teleport 7 and now.
