### ISSUE TITLE
Document that Letsencrypt cannot be used in a FIPS cluster

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#8555]
## Details
Nodes can't be added to a FIPS Teleport Cluster that is using Letsencrypt certificates. Letsencrypt uses ECDSA rather than RSA. FIPS/boringcrypto is only approved to use 2048- or 3072- bit RSA. Trying to add a node to a FIPS cluster that is using Letsencrypt certificates results in this error:
```
Node failed to establish connection to cluster: Post "https://redacted.example.com:443/v1/webapi/host/credentials": x509: certificate specifies an incompatible key usage, Get "https://teleport.cluster.local/v2/cacert": remote error: tls: internal error. service/connect.go:67
```

### Category
- Improve Existing

**Comment by stevenGravy** [comment]
Good to confirm if certbot can still be used

**Comment by pschisa** [comment]
+1 user was blocked on node rollout not knowing their LetsEncrypt cert would not work with the `--fips` flag.  Confirmed on v10.1.2

**Comment by pschisa** [comment]
Might no longer be an issue if not implemented before https://github.com/gravitational/teleport/issues/3519 is closed

**Comment by pschisa** [comment]
This is no longer true as of version 11.1.4
