### ISSUE TITLE
Replace defunct urls in reference `teleport.yaml`

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#8566]
## Details
Throughout the reference `teleport.yaml` (`docs/pages/setup/reference/config.mdx`), there are now defunct urls like https://goteleport.com/docs/admin-guide/#filesystem-layout which should be changed for appropriate live urls.

You can find all these defunct urls with
```bash
grep -rn 'goteleport.com/docs/admin-guide' docs/
```

### Category
- Improve Existing

**Comment by zmb3** [comment]
This has been fixed.
