### ISSUE TITLE
tsh ssh + command passes the command as plaintext to the logs

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#8587]
### Description

**What happened**:

Running `tsh ssh node <command>` records the command in plaintext in the teleport logs. This is a problem for customers who run scripts which require credentials that are passed as part of the full script launch command. 

**What you expected to happen**:

There should be a way to disable plaintext logging of `tsh ssh` commands for customers who have similar use cases and need pass credentials inline.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a script on a remote node that takes an inline credential input
2. Run `tsh ssh node <script exec> <--credentials your creds>
3. Observe the credentials and script exec command being logged in the Teleport logs on the node

### Debug Logs
```
Oct 13 15:10:59 node teleport[804827]: 2021-10-13T15:10:59Z INFO [NODE]      Started local command execution: "python3 test.py --creds 1234test" id:68 idle:30m0s local:10.0.0.1:52358 login:user remote:192.168.0.1:50173 teleportUser:user srv/exec.go:182
Oct 13 15:11:00 db teleport[804827]: 2021-10-13T15:11:00Z INFO [AUDIT]     exec addr.local:10.0.0.1:52358 addr.remote:192.168.0.1:50173 code:T3002I command:python3 test.py --creds 1234test ei:0 event:exec exitCode:0 login:user namespace:default server_id:a7d9164a-6c1f-4664-a6f8-13fd34069033 sid: time:2021-10-13T15:11:00.397Z uid:a79bd25e-4131-4c22-8801-a4d041b92b00 user:user events/emitter.go:324
```

**Comment by zmb3** [comment]
The command is captured in the audit logs by design. Even if we were to not log this item, it would likely still be captured in shell history and in the Teleport Audit Log.

Best practice is to not run commands with sensitive credentials. This can be accomplished via environment variables, `read -s` or a number of other means.
