### ISSUE TITLE
Connect to Kubernetes/DB screen UX improvements

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#8589]
### What
Improve user experience when using the Teleport UI on the Kubernetes and Database `connect` buttons. Currently it opens a pop-up that shows how to copy and connect via the CLI.

What it doesn't show is if a user is using an SSO provider like Google, Okta, etc. That option -- `--auth=Okta`, etc. - doesn't show in the example. See screenshots for how it looks today.

Kubernetes:

![Screen Shot 2021-10-13 at 10 55 47 AM](https://user-images.githubusercontent.com/1424442/137179501-7180b1e6-5dec-4e35-be22-f04e48d69b41.png)

Database:

![Screen Shot 2021-10-13 at 12 44 34 PM](https://user-images.githubusercontent.com/1424442/137179511-13c39508-432d-406c-92a8-2c67bf4e3eb2.png)

Users that are using SSO would be confused if they attempt to connect to K8s or DB's following these instructions as connecting without the `--auth=` option will default to the local Teleport user/database.

### How

Dynamically populate this content with the current `--auth=??` that the user has logged in as. Since Teleport knows how a user logged into the system some logic could be built to repopulate an `auth` field so that it shows the full login when a user clicks the connect button.

### Why
Improve user experience (and feedback from a customer)

### Workaround

None at the moment.

**Comment by zmb3** [comment]
This was fixed in 4110794acdc5d3d2b171fc7172c837da61bdb5d8
