### ISSUE TITLE
Provide details when logging the error "Failed to retrieve client pool. "

### ISSUE THREAD

**Issue by anurag-work** [gravitational/teleport#8594]
### Description

**What happened**:
Cluster was reconfigured with a different name . Some old nodes that were not re-configured continue to try to connect to the old cluster
**What you expected to happen**:
Error log prints details about the node that is trying to access . Like an IP address or hostname or some other identifying information.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Setup a cluster and add a node to the cluster
2. Reconfigure the cluster with the FQDN/IP but change the cluster name. Don't reconfigure the node to use the new cluster
3. New cluster is full of error messages but with no information regarding the node .
```
Failed to retrieve client pool. Client cluster "old-cluster-name", target cluster "new-cluster-name"
```

### Server Details
- Teleport version (run `teleport version`):6.2.3
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

In environments where teleport is not the only method of access , some servers might have stale teleport configurations and it is not possible to find the offending server.

**Comment by qixiangyang** [comment]
same question
