### ISSUE TITLE
Rust / OpenSSL Issue:  undefined symbol: EC_GROUP_get_curve_GF2m, version OPENSSL_1_1_0

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#8626]
### Description

**What happened**:

When building desktop access, I've noticed that Rust / OpenSSL is more picky, and am only able to build & use on the same distro. When building on a Ubuntu 20 machine, I'm able to run on a 20 machine. If it's older, I get this error.
 
```
 ~ $ /opt/teleport start -d --config=/etc/teleport.yaml
/teleport: symbol lookup error: /opt/teleport: undefined symbol: EC_GROUP_get_curve_GF2m, version OPENSSL_1_1_0
```

**What you expected to happen**:

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
a. Setup Go and Install Rust
1. Clone Teleport
2. Build with `make full DESKTOP_ACCESS=yes`

**Comment by zmb3** [comment]
Closing, as there's no more OpenSSL in desktop access. Thanks to @LKozlowski!
