### ISSUE TITLE
Desktop Access Audit Log is 'Unknown' 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#8638]
### Description

**What happened**:
Session start & end events are 'Unknown' 
![image](https://user-images.githubusercontent.com/559288/137546632-ccfc2de4-1c21-4ae4-afbc-8e112bae269c.png)

**What you expected to happen**:
```
event": "windows.desktop.session.start" 
event": "windows.desktop.session.end"
```

Version: Teleport 8. ( built from master )

**Comment by zmb3** [comment]
This was fixed in webapps.
