### ISSUE TITLE
Terraform spec out of synch with docs version

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#8645]
## Details

The role resource in the docs terraform spec does not match to the terraform plugin.  Ex: `db_labels` is the right field instead of `database_labels`

### Category
- Improve Existing

**Comment by zmb3** [comment]
Looks like `database_labels` is also mentioned in:

- docs/pages/access-controls/reference.mdx
- docs/pages/access-controls/guides/role-templates.mdx

@smallinsky can the DB access team take a look at fixing these docs?

**Comment by ptgott** [comment]
@marcoandredinis Does your PR to update the Terraform reference fix this?

**Comment by ptgott** [comment]
Thanks! I'll close this issue for now. If there are any more issues with the Terraform reference, we can point them out in a new, more specific issue.
