### ISSUE TITLE
ERROR: application name "<UUID>" must be a valid DNS subdomain

### ISSUE THREAD

**Issue by rtsisyk** [gravitational/teleport#8657]
### Description

**What happened**:

I found a bug either in the code or in documentation:
 
ERROR: application name "3184f5f1-bf83-40ca-803b-e936286f16c5" must be a valid DNS subdomain: https://goteleport.com/teleport/docs/application-access/#application-name:

> An application name should make a valid sub-domain (<=63 characters, no spaces, only a-z 0-9 _ - allowed).

 “3184f5f1-bf83-40ca-803b-e936286f16c5" definitely matches "(<=63 characters, no spaces, only a-z 0-9 _ - allowed)."

### Server Details

Teleport 6.2.0 from ancient Helm chart

**Comment by ulysseskan** [comment]
Also, the error needs to link to the correct docs page:
https://goteleport.com/docs/application-access/guides/connecting-apps/#application-name
