### ISSUE TITLE
Pulling back large numbers of DB nodes in the webUI appears not to paginate and fails with "grpc: received message larger than max"

### ISSUE THREAD

**Issue by nickbrennan1** [gravitational/teleport#8685]
When a large number of DB instances (ie 1k) are registered, when a user tries to view the available databases via the webUI, the UI is not populated and instead returns the error `grpc: received message larger than max (6140052 vs 4194304)`.

This appears to be linked to previous issue [7415](https://github.com/gravitational/teleport/pull/7415) but instead for DB nodes.

Expected behaviour is that the list of available DB connections would be returned.

**Comment by russjones** [comment]
@r0mant What do you think about adding a `ListResources` RPC and then have some helpers that convert to the type of resource you need (node, kube, app, db).
