### ISSUE TITLE
[v.7.0] /docs/pages/kubernetes-access/helm/guides/aws.mdx

### ISSUE THREAD

**Issue by mikejk8s** [gravitational/teleport#8686]
## Details

Hello,

The IAM Policy Role for Dynamodb requires an additional permission or Teleport will error when starting. 

Each of the 2 policies requires:

"dynamodb:UpdateContinuousBackups"

Thank you!

### Category

- Improve Existing

**Comment by webvictim** [comment]
Same as #11411
