### ISSUE TITLE
Trusted clusters config is not accepting keys in old export format

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#869]
## Steps to reproduce

* Upgrade binary
* Copy the new master.ca from the Teleport server and restart teleport. 
* Teleport is unable to start and I'm getting this error in the logs:

/opt/teleport/master.ca:L0. invalid file format. expected '@cert-authority` marker

## Expected results

* System should work properly and accept trusted cluster

**Comment by klizhentas** [comment]
Here is my proposal:

* Deprecate the `key_file` section in static config for `trusted_cluster` (remove from docs, but still support the code)
* Instead, accept new `yaml` strucrture for `trusted cluster`
* Introduce `tctl auth export --compat=1.0` flag that exports the keys in the old format to preserve backwards compatibility for existing installs

**Comment by olivierpilotte** [comment]
Is there a workaround to this problem? I'm testing rc2 / rc3 at the moment and wanted to give the trusted clusters a try, but got impeded by this bug.

**Comment by klizhentas** [comment]
you can just stick to 1.3.2 and it will work
