### ISSUE TITLE
DB Access should be able to provide access for a cross account database

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#8741]
### What

Currently, teleport will provide access to an aws database that is directly available to teleport. If the aws credentials only get access to be able to assume another role that grants access to a cross account database, teleport does not see it.

It is difficult to externally implement the aws assume and it would be great for teleport to be able to handle this itself.

https://aws.amazon.com/blogs/database/managing-amazon-rds-databases-in-multi-account-environments-with-the-aws-cli/ - details on how the cross account assume works

### How

Teleport would attempt a role assume to access a database.

### Why

this is necessary for a cross account database.

### Workaround

no clean workaround

**Comment by webvictim** [comment]
This is now tracked in https://github.com/gravitational/teleport/issues/21872

**Comment by GavinFrazar** [comment]
closing since its being tracked in the other issue now
