### ISSUE TITLE
Investigate and fix DynamoDB scaling on 50k node clusters

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#8747]
Investigate and fix DynamoDB scaling on 50k node clusters

**Comment by russjones** [comment]
@fspmarshall How do you feel about this one at the moment? Should we close this now to focus on smaller scoped items?

**Comment by russjones** [comment]
@fspmarshall @rosstimothy Can we close this, I think DynamoDB can scale to 50k now?

**Comment by rosstimothy** [comment]
```
tctl nodes ls | wc -l
50785
```
@russjones ^^  think we are safe to close this one for now
