### ISSUE TITLE
[v.7.0] /docs/pages/setup/reference/terraform-provider.mdx

### ISSUE THREAD

**Issue by champs** [gravitational/teleport#8750]
## Details

Under `teleport_role` allow/deny attribute should be `kubernetes_groups` not `kube_groups`.

### Category
- Remove Outdated

**Comment by amruth-acharya** [comment]
@colinedwardwood  Should i change the kube_users to kubernetes_users too?

**Comment by pimguilherme** [comment]
Hey folks! Just FYI there are a bunch other parameters which are not aligned with the actual spec.. some examples:

kube_groups -> kubernetes_groups
kube_users -> kubernetes_users

all the *labels are
database_labels.name
database_labels.values,

while they should be
database_labels.key
database_labels.value

spec.options.bpf -> enhanced_recording
spec.options.certificate_format -> cert_format
  
cheers!

**Comment by zmb3** [comment]
This has been fixed.
