### ISSUE TITLE
Convert trace and rountdrip to Go modules

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#8755]
Our https://github.com/gravitational/trace and https://github.com/gravitational/roundtrip packages are not Go modules yet. Convert them to Go modules.

**Comment by aditya-K2** [comment]
I have opened a pull request [here](https://github.com/gravitational/trace/pull/69) waiting for it to be merged.

**Comment by justinas** [comment]
Fixed in https://github.com/gravitational/trace/pull/57 and https://github.com/gravitational/roundtrip/pull/23 . Shall we bump the `roundtrip` dependency to `v1.0.2` here?

**Comment by zmb3** [comment]
> Fixed in [gravitational/trace#57](https://github.com/gravitational/trace/pull/57) and [gravitational/roundtrip#23](https://github.com/gravitational/roundtrip/pull/23) . Shall we bump the `roundtrip` dependency to `v1.0.2` here?

Sure! I'm going to close this in any case.
