### ISSUE TITLE
tsh config should include the remote login name in the ProxyCommand

### ISSUE THREAD

**Issue by colinedwardwood** [gravitational/teleport#8761]
### What
When I run tsh config it outputs a config that includes the ProxyCommand
`ProxyCommand ssh -p 3023 teleport.example.com -s proxy:$(echo %h | cut -d '.' -f 1):%p` but this will not respect any remote user I specify in my `ssh` command and it should.

### How
Replace `ProxyCommand ssh -p 3023 teleport.example.com -s proxy:$(echo %h | cut -d '.' -f 1):%p` with `ProxyCommand ssh -p 3023 %r@teleport.example.com -s proxy:$(echo %h | cut -d '.' -f 1):%p`

### Why
This will enable me to use `ssh username@hostname` and have the username respected.

**Comment by timothyb89** [comment]
Hi @colinedwardwood, is this still an issue for you with Teleport v7.2+? It should be fixed with https://github.com/gravitational/teleport/pull/7848 (released with tsh v7.2), though you will need to re-generate your ssh config.

**Comment by colinedwardwood** [comment]
thanks, you're right, I'm going to close this issue.
