### ISSUE TITLE
Investigate dynamic libraries for 8.0.0-beta.3

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#8765]
In Teleport 7.1.0 we dynamically linked to:

```
$ ldd teleport 
	linux-vdso.so.1 (0x00007ffde3310000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7695ff2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7695fec000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7695dfa000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f769601f000)
```

With 8.0.0-beta.2 we have a few additions:

```
$ ldd teleport
	linux-vdso.so.1 (0x00007ffe161f5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc386852000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc38684c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc3866fd000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc3866e2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc3864f0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc386881000)
```

Investigate whether `libm` and `libgcc_s` are actually required or if we can remove these dependencies.

**Comment by xacrimon** [comment]
As far as I am aware, these are dependencies of `glibc` and these are pulled in by any substantial C/C++/Rust code. Statically linking these are technically possible but these libraries are LGPL licensed which excludes that option if I am not mistaken.

If we really need to avoid these dependencies integral to `glibc` the only real solution is to use a MUSL based target for C/C++/Rust code. These are available but they come with the disadvantage of MUSL generally being slower (sometimes significantly) than glibc for core tasks.

**Comment by zmb3** [comment]
See #9028 for a separate but related issue with libc compatibility.
