### ISSUE TITLE
Vault Secrets Engine Plugin for providing Teleport short-lived access certs

### ISSUE THREAD

**Issue by highb** [gravitational/teleport#8795]
### What
What would you like Teleport to do differently?

Instead of implementing a workflow [based around `tctl auth sign` to generate short-lived certificates myself](https://goteleport.com/docs/kubernetes-access/guides/cicd/#short-lived-certs-for-kubernetes-cicd), it would be wonderful to have a Vault plugin that could handle that workflow automatically.

### How
How would you implement this?

I'd [talk to Hashicorp about partnerships](https://www.vaultproject.io/docs/partnerships) or, if I had abundant free time, I would implement it myself using their [docs](https://www.vaultproject.io/docs/internals/plugins) and [tutorial](https://learn.hashicorp.com/tutorials/vault/plugin-backends).

### Why
Why do you need this?

Automated systems such as CI/CD should have RBAC controlled and auditable access to resources, just as users do. The current workflow would still require an active user to generate the short lived certs periodically, or a separate, trusted and isolated CI/CD process to sign in and generate the short-lived cert for the CI/CD pipeline. 

Integration with Hashicorp Vault would permit automated generation of the short-lived certs for k8s, DB, etc access on a completely programmatic basis, along with lifecycle hooks that could allow revocation once the automated workflow is completed.

### Workaround
If a workaround exists, please include it.

* Use the existing `tctl auth sign` workflow manually with a long TTL and then sharing that cert directly with whatever automated system needs access.
* Creating a trusted/isolated CI/CD job that has credentials to generate certs for jobs and then pass them along to a consumer job.

**Comment by highb** [comment]
After discussing with @pschisa , this may be an integration point for `tbot` https://github.com/gravitational/teleport/issues/7066

**Comment by zmb3** [comment]
Correct, Machine ID is our answer to replacing `tctl auth sign` workflows, not another vendor's product.
