### ISSUE TITLE
web sessions should reconnect in case if connection gets lost

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#88]
## Description

Right now when teleport proxy looses connection to the remote server, users see `disconnected` screen. We should detect connection losses and reconnect automatically

## How success looks like

* [ ] if connection to the remote server gets lost and restored, teleport proxy web UI will reconnect
* [ ] teleport proxy will reconnect with exponential backoff to make sure it does not send browser to reconnect loop.
* [ ] users will see "reconnect in ..." message in terminal when this occurs

**Comment by kontsevoy** [comment]
low priority (likely won't be done any time soon)
