### ISSUE TITLE
Trim output of `ListNodes` to not show nodes that have hit TTL

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#8834]
DynamoDB can take up to 48 hours to TTL out a resource (like an SSH server) from the backend. 

From the [DynamoDB documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/howitworks-ttl.html
):

```
Depending on the size and activity level of a table, the actual delete operation of an expired item
can vary. Because TTL is meant to be a background process, the nature of the capacity used to expire and
delete items via TTL is variable (but free of charge). TTL typically deletes expired items within 48
hours of expiration.
```

This means users can have stale nodes show up in the Web UI or `tsh ls` output. The default output for should be updated to trim the stale entries when presenting this to the user. Internally we should track the stale entries to ensure consistency in cache state.

**Comment by russjones** [comment]
@fspmarshall You want to add support for a flag to be able to show stale entries right?

**Comment by fspmarshall** [comment]
@russjones Yeah, I prefer the idea of filtering being opt-in.  Or, at the very least, of continuing to show nodes until they are stale by a few multiples of the offline threshold, and providing clear warnings if a large number of nodes are filtered out.  With the exception of dynamo clusters with high turnover rates, a large number of stale node entries usually means that the nodes are still available, but something else has gone wrong (e.g. slow event propagation).

**Comment by corkrean** [comment]
Related to #10019
