### ISSUE TITLE
WebUI becomes unusable when role deleted from logged-in user

### ISSUE THREAD

**Issue by tcsc** [gravitational/teleport#8835]
### Description

**What happened**:
1. Create new "deny-agent-forwarding" role
2. Applied new role to logged-in user
3. Logged out of WebUI and back in
4. Removed new role from user
5. Deleted new role via "users" page

![delete-role](https://user-images.githubusercontent.com/1959769/139971257-93bbab07-a764-47c6-b844-6c80aab63b2f.png)

**What you expected to happen**:

WebUI to display users page as per normal

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
See above

### Server Details
- Teleport version (run `teleport version`): Teleport v8.0.0-beta.2 git:v8.0.0-beta.2-0-g8383bdaeb go1.17.2
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Locally

### Workarouns
- Wait for current login to expire
- Restart server

**Comment by ravicious** [comment]
Still the case on v14 master at a1f8f06405. Although at least now we don't show "Internal server error", instead just pretty much every page in the UI shows a regular error message saying "role foo is not found".

This is not specific to the Web UI. After recreating this with tsh, `tsh ls` returns the same error.

**Comment by rudream** [comment]
Fixed in https://github.com/gravitational/teleport/pull/45610
