### ISSUE TITLE
tsh login --request-roles hangs

### ISSUE THREAD

**Issue by vrivanov-rb** [gravitational/teleport#8839]
### Description

**What happened**:

Run `tsh login --request-roles=...` and _immediately_ approve the request (using an event watcher and the api).
Login command hangs on `Waiting for request approval...` If I list the request using tsh or tctl on the auth, I see that the request has indeed been approved already.

**What you expected to happen**:

`tsh login` to go through almost immediately.

### Reproduction Steps
1. `tsh login --request-roles=...`
2. Approve request immediately e.g. via the api in a small daemon

### Server Details
- Teleport version (run `teleport version`): 7.1.3
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details: A race condition exists in the tsh implementation -- the request and the watcher for request events get created in separate channels, and although the channel that sets up the watcher is started first, there is no guarantee that the watcher will be operational by the time the main thread creates the request. Thus it is possible that tsh misses some events on the newly-created request, if those events occur immediately after the request's creation and before the handling for them is set up.

### Client Details
- Tsh version (`tsh version`): 7.1.3
- Computer OS (e.g. Linux, macOS, Windows): Ubuntu 20.04.3 LTS
- Browser version (for UI-related issues): firefox
- Installed via (e.g. apt, yum, brew, website download): deb
- Additional details:

**Comment by programmerq** [comment]
This was fixed by #9193.

The fix appeared in 8.0.6 / 7.3.9
