### ISSUE TITLE
Uninstall Documentation

### ISSUE THREAD

**Issue by Gerst20051** [gravitational/teleport#8852]
## Details

It's not documented how to uninstall teleport after following the installation instructions here:

https://goteleport.com/docs/installation/#macos

When installed with `brew` it's just `brew uninstall teleport`.

```sh
TSH_VERSION='7.1.3'
TSH_FILENAME="tsh-$TSH_VERSION.pkg"

open ~/$TSH_FILENAME
# or
sudo installer -pkg ~/$TSH_FILENAME -target /
```

What are the steps to remove this on `macOS` after it's been manually installed?

### Category
- Improve Existing

**Comment by encryptblockr** [comment]
why is this still open?

uninstall documentation taking years to write? possibly a few lines of docs???

**Comment by sirajulm** [comment]
For manual install I had to remove `tbot`, `tctl`, `telport`, `tsh` from `/usr/local/bin` I'm not sure if there is any further clutter.

If you are busy writing code, and don't have time for documentation, please write some code for bundling an uninstaller in the package as well.
