### ISSUE TITLE
Cluster bootstrapping fails with static tokens

### ISSUE THREAD

**Issue by analbeard** [gravitational/teleport#886]
I'm attempting to bootstrap a test cluster using Ansible and I cannot get a new node to authenticate against my initial auth server. One thing I can't see in the docs is how the roles are applied - in this instance my proxy is both proxy and node (obviously), so the static auth token is configured for 'proxy,node' - would this be correct?

I've created a gist with the config and errors for both ends:

https://gist.github.com/analbeard/897a84ebd7a40675d488178d16dcc39a

**Comment by bcg62** [comment]
the docs suggest using pwgen for tokens, you should wind up with something like this which seems different than your configuration.

```
$ pwgen -s -1 32
RWs4BccrGv2YER4T9oYW84KgYmXBjG4X
```

**Comment by analbeard** [comment]
It turns out that this was user error. In my config file I had my list of auth tokens as follows:

```
auth_service:
  auth_token:
    - "proxy,node:6cf52bd9-202e-4ac7-95bd-217ce1ff2530"
    - "node:556b5d0b-d9e9-4680-a6e3-10c7126b972e"
```

however that should have just been just 'tokens:' instead of 'auth_token:'.
