### ISSUE TITLE
CloudFormation example is broken with Teleport v8

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#8860]
### Description

**What happened**: Deploying the CloudFormation example does not result in a usable Teleport cluster: `tsh login` never succeeds due to multiple issues.

**What you expected to happen**: A fully functional example cluster should be brought up, similar to the two working Terraform examples; `tsh login` should succeed.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Configure AWS profile/env vars (key, key ID, region, etc)
2. If desired, modify the AMI map in `oss.yaml` for your given region to point to a different Teleport release
3. Follow the [README](https://github.com/gravitational/teleport/tree/master/examples/aws/cloudformation); run `make create-stack` to deploy the Teleport nodes
4. Observe that the resulting stack doesn't fully work

### Server Details
- Teleport version (run `teleport version`): v8.0.0-beta.2
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

Server issues:
 * Needed to manually restart the Teleport service on the SSH nodes after the proxies fully initialized as they did not automatically pick up the changed CA pins
 * The proxy load balancer doesn't forward port 3023 so tsh can never log in
 * A rule manually added to the proxy's load balancer to forward 3023, tsh login still fails:

       Original Error: *trace.ConnectionProblemError Get &#34;https://teleport.cluster.local/v2/authorities/host?load_keys=false&#34;: ssh: rejected: connect failed (Cannot open new SSH session on reverse tunnel. Are you connecting to the right port?)

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

**Comment by zmb3** [comment]
The CloudFormation example was removed.
