### ISSUE TITLE
Null route can cause high latency when connecting to hosts

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#8866]
If you add a null route using `ip route add ...` to auth on a node then attempt to `tsh ssh` into that node, it will take a very long time to run (about 6 minutes). The following appears in the logs indicating that session establishment may be hung on attempting to create an active session.

```
Failed to create new session: Post "https://teleport.cluster.local/v2/namespaces/default/sessions":
   dial tcp w.x.y.z:3025: connect: connection timed out
```

**Comment by rosstimothy** [comment]
Neither `ip route add -host $auth_ip reject`  or  `ip route add -host $auth_ip blackhole` cause latency issues with `tsh ssh`. I was only able to reproduce this with `ip route add $auth_ip dev lo`.
