### ISSUE TITLE
Can't CTRL+C out of `tsh login` when tsh requests OTP token

### ISSUE THREAD

**Issue by alexatcanva** [gravitational/teleport#8867]
### Description

**What happened**: When running the command `tsh login` and am prompted for an OTP token, ctrl-c does not exit the OTP request.

**What you expected to happen**:
The command terminates and I am brought back to my shell.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Run `tsh login`
2. Provide password
3. CTRL+C when prompted for OTP token

### Client Details
- Tsh version (`tsh version`): v8.0.0-alpha.1
- Computer OS (e.g. Linux, macOS, Windows): MacOs
- Browser version (for UI-related issues): N/a
- Installed via (e.g. apt, yum, brew, website download): website download
- Additional details: N/a

### Debug Logs
N/a

**Comment by zmb3** [comment]
@codingllama can you confirm whether this is still an issue? I feel like it might be fixed by your recent work.

**Comment by codingllama** [comment]
Yep, that sounds familiar.

I've tested on master, v9.2.3 and v8.3.10, they all abort when you press CTRL-C. It goes something like this

```shell
$ tsh login
> Enter password for Teleport user llama: <types password>
> Enter an OTP code from a device: <CTRL-C>
ERROR: context canceled
```

Closing the issue.
