### ISSUE TITLE
advertise_ip defaulting to loopback in Teleport 2.0.0 RC2

### ISSUE THREAD

**Issue by ekristen** [gravitational/teleport#887]
I just installed RC2 and all the new nodes I've registered have defaulted to 127.0.0.1 for its advertise_ip.

**Comment by ekristen** [comment]
Actually I pulled all the code out and ran just the discovery code manually on my server and it detects the correct IP, but when run in the context of teleport it is selecting 127.0.0.1. It is unclear as to why.

**Comment by kontsevoy** [comment]
@ekristen actually the  reason `advertise_ip` is available to tweak is precisely because it is impossible for any process to guess which IP address you want to use for accessing this node in a multi-homed environment.
