### ISSUE TITLE
UI is broken in RC2

### ISSUE THREAD

**Issue by ekristen** [gravitational/teleport#888]
It seems that the UI will not load in RC2.  

```
TypeError: item is undefined[Learn More]  app.664c1b2299a0e6544be9.js:5497:10
```

**Comment by ekristen** [comment]
Seems this has to do with oidc stuff not being configured properly? Perhaps the documentation is out of date?

**Comment by alex-kovoy** [comment]
Could you share the config which causes this behavior or a full exception stack from browser console? 

Thank you!

**Comment by ekristen** [comment]
I was using `oidc_connectors` instead of `oidc` .. I believe since the publishing of v2.0.0 and then the retraction, there was some mixup in docs too, at one point it talked about oidc_connectors but I'm unable to find it now.
