### ISSUE TITLE
TLS routing documentation updates

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#8918]
- [x] Migration guide from standard deployment to TLS routing (incl. downgrade guide)
- [x] Architecture reference guide - how TLS routing works
- [x] Refresher of OpenSSH guide to accommodate TLS routing
- [x] Update reference configuration
- [x] Refresh DB guides to support TLS routing

**Comment by r0mant** [comment]
@klizhentas Do you have ideas on how to integrate TLS routing information in our documentation? I.e. do you want to have a separate top-level section dedicated to it (like App Access, Database Access, etc.), or just have it throughout the docs since it's not really a single "feature" but rather affects various parts of the product?

For example, we could place the upgrade/downgrade guides under Setup/Admin Guides and the architecture reference under top-level Architecture section if that sounds okay but I'm open to doing it another way too.

**Comment by klizhentas** [comment]
@r0mant I think the best way to integrate it is to embed it into corresponding guides and update them to by default use the new TLS routing. For most users (who will be new to the system) this will be the only way.

We should also have a separate TLS routing section in the architecture part of the setup and reference in configuration + migration guides.
