### ISSUE TITLE
Official Docker Image?

### ISSUE THREAD

**Issue by genexp** [gravitational/teleport#893]
Hey Team - Wondered if you had plans to release an official Docker image?  I noticed there are many poorly maintained ones out there.

  https://hub.docker.com/

**Comment by kontsevoy** [comment]
we never thought a single-file executable needed to be put in a docker container :) besides, `teleport` needs to run as `root` to impersonate user logins. but I guess this could be used for testing?

**Comment by genexp** [comment]
Yeah you're right. I'm not sure what I was thinking here.

**Comment by kontsevoy** [comment]
hehe, cool. we'll save ourselves a bit of time by not starting to maintain this _for now_ and instead invest in other areas, like maintaining BSD or/and ARM binaries! :) we may revisit this later!

**Comment by francislavoie** [comment]
Counterpoint - it would make it easier to update the binary by having it wrapped in a container and pulling it down from dockerhub. Also, it, would make it easier to have a `docker-compose.yml` to just boot up a stack quickly.

**Comment by genexp** [comment]
Hey Francis - But when you connected to the daemon, it would grant you
access to the container rather than the host.  Not exactly expected
behavior right?

**Comment by francislavoie** [comment]
Actually, I would expect that. Unless I misunderstand how Teleport works (I'm just about to set it up in the coming days), I'd rather lock it from having access to the rest of the things running on my host machine. If it wants to run commands like `ssh`, it should do it from inside the container.

**Comment by francislavoie** [comment]
I guess I'll clarify - I'd run Teleport on one of our internal machines, it would connect to the various machines I want SSH access to via OpenSSH. I don't think I'll be running Teleport on my other machines if I don't need to, rather keep things simple.

**Comment by jalberto** [comment]
It also can be useful to deploy Teleport as a pod in k8s, and use it to ssh other pods or k8s nodes

**Comment by taemon1337** [comment]
I think this should be revisited for a number of reasons,  I'm looking at using teleport inside of containers specifically to limit access and ability within cluster.  Also distribution through docker images would be a benefit and should be easy since you're already building with containers.  Also, since the teleport binaries are not statically linked, they do have dependencies, as shown when you try to run them inside containers.

**Comment by klizhentas** [comment]
@kontsevoy we should update the docs, we now release to docker as well, our images are all here:

https://quay.io/repository/gravitational/teleport?tag=latest&tab=tags

**Comment by kontsevoy** [comment]
@klizhentas any reason we're not tagging with `latest`?

**Comment by kontsevoy** [comment]
Updated the docs & the README
