### ISSUE TITLE
Enable HA for Access Request Plugins

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#8931]
Currently, Teleport does not support HA for access plugins. If a user tries to run separate instances of a plugin, they will receive duplicate "notifications" for each access request. 

It would be beneficial to availability and UX if a user could run two separate instances of a plugin, and only receive one notification in their notification application (e.g. Slack, Jira) for each access request.

**Comment by stevenGravy** [comment]
would put this in the teleport-plugins repository

**Comment by corkrean** [comment]
Ahhh right. Here is the new issue: https://github.com/gravitational/teleport-plugins/issues/361
