### ISSUE TITLE
Kube config context tls-server-name prepending kube

### ISSUE THREAD

**Issue by scottcrawford03** [gravitational/teleport#8933]
### Description
Changes introduced here: https://github.com/gravitational/teleport/blob/master/tool/tsh/kube.go#L315-L316

**What happened**:
When logging into a kube agent with tsh kube login the context that is created has a `tls-server-name` set with `kube.` prepending it.

As a result I get cert errors like so:
```
Unable to connect to the server: x509: certificate is valid for teleport, teleport-root.sqprod.co, localhost, remote.kube.proxy.teleport.cluster.local, *.teleport.cluster.local, teleport.cluster.local, *.teleport-root.sqprod.co, not kube.127.0.0.1
```

Note the last part of that message, it’s looking for a server name of kube.127.0.0.1. This is coming from ~/.kube/config:
$ cat ~/.kube/config
...
- cluster:
    certificate-authority-data: …
    server: https://127.0.0.1:3026
    tls-server-name: kube.127.0.0.1
  name: teleport-root
...
**What you expected to happen**:
We expected to have a valid tls-server-name that allowed us to make kubectl calls in the teleport context.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. be on tsh v8.0.0-alpha.1 and login to a teleport-ent:7.2.1 cluster
2. observe your kube context having the `kube.` prepended to the tls-server-name

### Server Details
- Teleport version (run `teleport version`): teleport-ent:7.2.1
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Client Details
- Tsh version (`tsh version`): Teleport v8.0.0-alpha.1 git: go1.17.1
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

**Comment by smallinsky** [comment]
Fixed in  https://github.com/gravitational/teleport/pull/8940
