### ISSUE TITLE
Access Request Plugin Docs for Cloud Users

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#8936]
In our TOML documentation for access plugins we specify  `auth_server = "example.com:3025"`, when for cloud users this should be `auth_server = "exampletenant.sh:443"`.

Additionally, cloud users shouldn't use` tctl auth sign --format=tls --user=access-plugin --out=auth --ttl=2190h`, they should generate an identity file using `tctl auth sign --user=access-plugin --out=auth.pem --ttl=2190h`.

When Cloud users use an identity file, users should specify it in the TOML like this: `identity = "/var/lib/teleport/plugins/slack/auth_id"`

This has been fixed on the Slack plugin page, but still needs to be fixed on the Mattermost, Jira Cloud, Jira Server, and PagerDuty access plugin pages.

**Comment by ptgott** [comment]
Hi @corkrean, thanks for flagging this. Would you mind adding some context for why Cloud users need the `identity` field versus `client_key`, `client_crt`, and `root_cas`? From doing a little bit of digging into this, my impression was that the `--format` flag determines which fields you need to supply in the plugin config, and which credential files the plugin [looks for](https://github.com/gravitational/teleport-plugins/blob/master/lib/config.go#L85-L95), but either `identity` or `client_key`/`client_crt`/`root_cas` is acceptable.

**Comment by corkrean** [comment]
Hi @ptgott, I'm not too familiar with the plumbing behind this, but I think the core issue is that in order to access the Teleport auth service API through the proxy, an identify file is required. On Teleport Cloud, the auth server is not exposed so you must go through the Proxy. 

If you want to dig deeper, I've attached a stack trace from a user on Teleport 7.3 who attempted to connect a plugin through the proxy (on Teleport Cloud) with client_key, client_crt, and root_cas:

```
Original Error: context.deadlineExceededError context deadline exceeded
Stack Trace:
        /go/src/github.com/gravitational/teleport-plugins/vendor/github.com/gravitational/teleport/api/client/client.go:273 github.com/gravitational/teleport/api/client.connect
        /go/src/github.com/gravitational/teleport-plugins/vendor/github.com/gravitational/teleport/api/client/client.go:101 github.com/gravitational/teleport/api/client.New
        /go/src/github.com/gravitational/teleport-plugins/access/jira/app.go:165 main.(*App).init
        /go/src/github.com/gravitational/teleport-plugins/access/jira/app.go:114 main.(*App).run
        /go/src/github.com/gravitational/teleport-plugins/lib/process.go:216 github.com/gravitational/teleport-plugins/lib.NewServiceJob.func1
        /go/src/github.com/gravitational/teleport-plugins/lib/process.go:237 github.com/gravitational/teleport-plugins/lib.(*serviceJob).DoJob
        /go/src/github.com/gravitational/teleport-plugins/lib/process.go:83 github.com/gravitational/teleport-plugins/lib.NewProcess.func2.1
        /usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
User Message: context deadline exceeded] lib/bail.go:17
```

**Comment by ptgott** [comment]
Thanks! Looks like Teleport writes different information to disk depending on the format, e.g., with `file` it writes a list of CA host certificates [in authorized host format](https://github.com/gravitational/teleport/blob/1967ca2ad46148e4f786a8a38c7455bd56c559e4/lib/client/identityfile/identity.go#L122), whereas with format `tls` it [does not](https://github.com/gravitational/teleport/blob/1967ca2ad46148e4f786a8a38c7455bd56c559e4/lib/client/identityfile/identity.go#L155). I'll make some time to change the plugin guides next week.

**Comment by ptgott** [comment]
I have a draft PR for this here: https://github.com/gravitational/teleport/pull/9470

I'll remove the "draft' status after I give this a round of edits.
