### ISSUE TITLE
Google Workspace SSO Missing Step

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#8942]
To use Google SSO with Teleport, you must enable the Admin SDK API in your GCP project. This step is not mentioned in [the docs](https://goteleport.com/docs/enterprise/sso/google-workspace/#google-workspace-as-sso-for-ssh). 

Presently, the only way a user would know to do this would be by looking at the error auth log that tells the user they must enable the Admin SDK API.

**Comment by espadolini** [comment]
@ptgott do we need to fix this for the v7 and earlier docs? #9907 is probably going to be only for v8 and later

**Comment by ptgott** [comment]
@espadolini I think we need to support the docs until v6.2 per this page: https://goteleport.com/docs/faq/#which-version-of-teleport-is-supported

**Comment by zmb3** [comment]
v6 is out of support.

@espadolini @ptgott can we close this?

**Comment by espadolini** [comment]
v7 is still technically supported for a few more weeks, and the v7 docs don't have the indication either; it might be a moot point regardless, as #8831 would make the OIDC stuff for google entirely obsolete, requiring no code changes on our part.

**Comment by ptgott** [comment]
Closing since we'll be shifting the docs soon to make v10 the default.
