### ISSUE TITLE
Access Controls on Sessions?

### ISSUE THREAD

**Issue by ekristen** [gravitational/teleport#895]
Shouldn't session playback be restricted to the user that created it or an admin user?

**Comment by klizhentas** [comment]
pre-RBAC teleport users were all admins of sorts, post-RBAC users you can manage it by tweaking users roles

**Comment by ekristen** [comment]
Thank you for the information.

**Comment by klizhentas** [comment]
we should all more docs on this

**Comment by ekristen** [comment]
That would be much appreciated. Thanks for all the awesome work on this project.  So far you've been moving fast on iterations, but I'm keeping my eye out on ways to contribute.
