### ISSUE TITLE
SSH agent does not use TLS routing when enabled

### ISSUE THREAD

**Issue by dboslee** [gravitational/teleport#8952]
### Description

**What happened**:
After configuring the auth server with `proxy_listener_mode: multiplex` new ssh nodes continue to connect over the `tunnel_public_addr`

The following log line is the most relevant...
```
Failed to ping web proxy "david.cloud.gravitational.io:11001" addr: Get "https://david.cloud.gravitational.io:11001/webapi/find": tls: first record does not look like a TLS handshake reversetunnel/transport.go:93
```

The issue seems to be cause by the following function trying to use the web api over the tunnel_public_addr. https://github.com/gravitational/teleport/blob/853da7716dfc09a63c7f3d025a4b0dac23493dbc/lib/reversetunnel/agent.go#L263

To fix the issue I am thinking the proxy web address and tunnel address would need to be passed in when the agent pool is initialized here...
https://github.com/gravitational/teleport/blob/853da7716dfc09a63c7f3d025a4b0dac23493dbc/lib/service/service.go#L1998-L2002

**What you expected to happen**:
I expected that new ssh node would connect over the web port using TLS routing.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Configure teleport as follows
```
version: v2
teleport:
...
auth_service:
   ...
  proxy_listener_mode: multiplex
...

proxy_service:
  web_listen_addr: 0.0.0.0:443
  public_addr: example.teleport.com:443
  tunnel_public_addr: example.teleport.com:11001
...
```
The important parts are that the auth_service has `proxy_listener_mode: multiplex` and the proxy_service has `tunnel_public_addr` specified.

2. Start the server
3. Connect an ssh node with debug logging.
4. Observe the port used by the reverse tunnel.

### Server Details
- Teleport version (run `teleport version`):
8.0.0-rc.1

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
 Teleport Cloud Staging

**Comment by smallinsky** [comment]
Fixed in https://github.com/gravitational/teleport/pull/8993
