### ISSUE TITLE
Add state directory to systemd unit

### ISSUE THREAD

**Issue by nicka101** [gravitational/teleport#8954]
## Details
Sample systemd unit file should specify:
```
StateDirectory=teleport
StateDirectoryMode=0710
```
for systemd to automatically create the /var/lib/teleport directory and set its perms to 0710

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
I believe this is no longer an issue, now that the Teleport installer creates the systemd unit files during installation. If that's not the case, let us know. Otherwise I'll mark this issue to close in a few days.
