### ISSUE TITLE
Webfrontend Session Replay not working ... sometimes

### ISSUE THREAD

**Issue by wohlben** [gravitational/teleport#898]
There seems to be a *really* strange bug in the Webfrontend

My first impression was the teleport.log.severity setting, but that that didn't really hold up on further testing. Affected sessions are however permanently tainted and cant be played on the web frontend. The error only affects the webfrontend, as the tsh play $SID works fine for everything.

The access URL (node id and session id) seem to be correct (compared them to the file found in ~/log/sessions/default/${SID}.session.log and the nid from tctl nodes ls)

i **think** the bug might be triggered by using ctrl-d on the web console. Or at least thats when I get this in stdout from the server:
```
(RED) Apr 05 08:45:45 teleport-server /usr/local/bin/teleport[20644]: time="2017-04-05T08:45:45Z" level=error msg="os: process already finished"
(RED) Apr 05 08:45:45 teleport-server /usr/local/bin/teleport[20644]: time="2017-04-05T08:45:45Z" level=error msg="tls: use of closed connection"
Apr 05 08:45:45 teleport-server teleport[20644]: time="2017-04-05T08:45:45Z" level=error msg="os: process already finished" file="srv/sess.go:551" func="srv.(*session).start.func3"
Apr 05 08:45:45 teleport-server teleport[20644]: time="2017-04-05T08:45:45Z" level=error msg="tls: use of closed connection" file="utils/websocketwriter.go:100" func="utils.(*WebSockWrapper).Write"
Apr 05 08:46:47 teleport-server teleport[20644]: 2017/04/05 08:46:47 http: TLS handshake error from 127.0.0.1:48344: EOF

```

The server is running on an opensuse leap 42.2. I've tested from ubuntu 16.10 with latest firefox and chrome

relevant files:
[affected session.log](http://uu.zoy.org/p/gb22jw#x=F4/qAHP5ugCE3lMA)

[bytes file](http://uu.zoy.org/p/PA8okQ#x=FfLdAMi+5gDks28A)

[teleport.yml](http://uu.zoy.org/p/0749Qg#x=l6UxAE0NKwAuux4A)

**Comment by alex-kovoy** [comment]
Can be related #816
