### ISSUE TITLE
Update .github for release branches

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#8984]
Update .github/CODEOWNERS to mirror `master` for `branch/v8`, `branch/v7`, and `branch/v6.2`.

**Comment by russjones** [comment]
Also, backport `.github/workflow/*` to `branch/v7` `branch/v6.2` as well once CODEOWNERS is removed.

I think @zmb3's suggestion here to remove source is good idea as well. It would also validate our assumptions that bot only ever runs off `master` and also make things easy to reason about.

https://github.com/gravitational/teleport/pull/8975#issuecomment-967736740

**Comment by quinqu** [comment]
`.github/workflows/*` includes the actual bot code itself, did you mean `.github/workflows/*.yml`?

**Comment by russjones** [comment]
@quinqu Looks like you've made the changes for `branch/v7` and `branch/v6.2`, can you make the changes to `branch/v8` as well?

**Comment by quinqu** [comment]
Yes, I backported to `branch/v8` last week. Closing.

**Comment by russjones** [comment]
@quinqu CODEOWNERS has not been updated: https://github.com/gravitational/teleport/blob/branch/v8/.github/CODEOWNERS

**Comment by quinqu** [comment]
oops, my bad! fixed https://github.com/gravitational/teleport/pull/9058
