### ISSUE TITLE
Update U2F documentation section

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#899]
> If your Teleport is deployed with the same teleport process running as a proxy and as an auth server, you can omit app_id and  facets settings.
> app_id should be the U2F App ID of your cluster.  app_id defaults to the auth server's hostname if not set.

But apparently it does not work if app_id and facets settings are missing.

**Comment by russjones** [comment]
We also need to document the changes to OIDC connectors and new features like Dynamic Roles: https://github.com/gravitational/teleport/pull/897

I'll take care of this.

**Comment by russjones** [comment]
Fixed in https://github.com/gravitational/teleport/pull/909.
