### ISSUE TITLE
Feature Request: Lookup table interpolation

### ISSUE THREAD

**Issue by ben-z** [gravitational/teleport#8990]
### What
Lookup table interpolation. My use case is that I want to map Github SSO username to existing logins.

### How
An interpolation in the form of `{{lookup(query, table, 'default-value')}}`.

### Why
Currently, there doesn't appear to be a way to give a user extra logins based on other attributes. This will make it really easy for existing development machines (each user having one user account) to migrate to teleport.

[Related discussion](https://github.com/gravitational/teleport/discussions/7248)

### Workaround
Create a GitHub team per user and enumerate them in the GitHub connector configuration file.

**Comment by zmb3** [comment]
This might be resolved by role variables (#11042).

@nklaassen can you chat with @benarent when he returns and see if we can incorporate this into the role variables work?

**Comment by nklaassen** [comment]
Going to close this one as we have #6707 and the problem should be addressed by [RFD 78](https://github.com/gravitational/teleport/pull/14977) which will allow you to define arbitrary traits which you can use to set logins
