### ISSUE TITLE
Session Record DB Access Commands like we do with k8s commands

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#9019]
### What
Add db to list of services that support session recordings, along with ssh and k8s.

### Why
Customer feature request.

### Workaround
Currently users have to parse out audit logs and pull out commands manually this way.

**Comment by stevenGravy** [comment]
having a expandable/collapsable way to have a collection of db activities would be helpful, same with the BPF audit entries and individual k8s entries.

**Comment by russjones** [comment]
I think there are two issues here.

1. Applications and Database don't have a session like SSH and Kubernetes does. We can investigate how we can aggregate and create a "session" for the user. Application Access creates 5 minute chunks if I recall correctly.

2. Do we want to log/capture the results of a query?

**Comment by rikkaewesson** [comment]
Our concern is that `tsh db login` allows users to log in as a single user (admin, readonly, etc) - and logging via `pg_audit` will only show that parent user. Without the ability to record user sessions through teleport we're limited in what logs we can easily or concisely audit and trace back to each end user.

**Comment by pschisa** [comment]
Similar request to #5799

**Comment by zmb3** [comment]
Closing in favor of #5799
