### ISSUE TITLE
Update the teleport-cluster Helm chart to use StatefulSets with PVs

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#9020]
### What
Currently, the `teleport-cluster` Helm chart example supports persistent volumes as a Deployment instead of using StatefulSets.  The Teleport Helm chart for `teleport-kube-agent` supports StatefulSets when a persistent volume is enabled (see PR https://github.com/gravitational/teleport/pull/7123).  

Request is to update the `teleport-cluster` Helm chart example to use StatefulSets when a persistent volume is used.

### Why
As mentioned in the `teleport-kube-agent` PR, StatefulSet is geared towards applications with state, Deployments are geared towards stateless (or more specifically ephemeral storage for pods)

**Comment by russjones** [comment]
This is for auth servers. So you can maintain state across redeploy/restart.

**Comment by russjones** [comment]
Might be related to this work https://github.com/gravitational/teleport/issues/2838

**Comment by hugoShaka** [comment]
Initial versions of https://github.com/gravitational/teleport/pull/18274 were deploying auth pods using StatefulSets, after some testing this was reverted:

- Teleport does not support being replicated with local storage, only one pod can be run when storage is enabled. AFAIU there is no difference between a 1-pod deployment with `Recreate` strategy and a 1-pod statefulset.
- However, when running Teleport with a HA backend, the auth pods become stateless and a Deployment is a better fit for this kind of workload.

Unless Teleport starts supporting multi-replica with local storage, there seems to be virtually no gain from switching to StatefulSet. @pschisa do you know what issues the customer is trying to solve by switching to a statefulset?

**Comment by pschisa** [comment]
I reviewed the notes and I believe this was a case of the proxy services running separate from the auth services and looking for ways to persist the /var/lib/teleport of the proxy services upon pod/container rotation as a workaround to the issue where AWS will persist entries in a DynamoDB backend.  This was causing instability when rotating the proxy instances as removed proxies were still listed as available.

**Comment by hugoShaka** [comment]
It seems this issue is more about the pressure applied by agents when trying to connect to a stale proxy than linked to the way we deploy it. Cloud, Terraform, Cloudformation and some manual setups are deploying Teleport the same way. I don't think it makes sense to address the issue by having the Helm charts do a snowflake setup.

If it's ok with you @pschisa, I'll close the issue in favour of https://github.com/gravitational/teleport/issues/20057, which should address the root cause more globally.

**Comment by pschisa** [comment]
Sounds good to me
