### ISSUE TITLE
[v.7.0] /docs/pages/getting-started/linux-server.mdx

### ISSUE THREAD

**Issue by erasma** [gravitational/teleport#9031]
## Details
Good Day - Following the guide for ubuntu caused my to run version 8.0 on the server and 7.3 on the node which would not allow the tunnel (IOT Mode) to work

there was not clear error other then it saying it could not connect to the proxy server. 

can the instructions be for the same version & maybe add in the app if there is a miss match node to server it's prompts the user 

from the page

Install a Teleport client locally 
For more options (including RPM/DEB packages and downloads for i386/ARM/ARM64) please see our installation page.

curl -O https://get.gravitational.com/teleport-v7.3.2-linux-amd64-bin.tar.gz
tar -xzf teleport-v7.3.2-linux-amd64-bin.tar.gz
cd teleport

sudo ./install
Teleport binaries have been copied to /usr/local/bin

To configure the systemd service for Teleport take a look at examples/systemd/README.mdx

### Category

- Remove Outdated

**Comment by zmb3** [comment]
This has been fixed.
