### ISSUE TITLE
Missing Audit Logs and Session Recordings in WebUI for clusters deployed in GCP

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#9032]
### Description

Users with clusters deployed in GCP are seeing issues when attempting to access session recordings and audit logs. Symptoms include the following:

1. When browsing Session Recordings they appear to be gone from a Teleport perspective, but are intact in the GCS bucket.
2. When browsing through Audit Logs it doesn't seem to show all records at once (filter or no) and in some cases shows only a subset of total amount of logs available and visible in the backend. Customers sometimes have to click "fetch more" 5 times to get all records, but even this is not consistent.

**What you expected to happen**:

Teleport WebUI should bring up all audit events and session recordings available in the backend.

### Server Details
- Teleport version (run `teleport version`): 7.2.0+
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP

gz#3549

**Comment by adubkov** [comment]
Teleport Version: 7.1.2

**Comment by russjones** [comment]
@xacrimon Any update on this?

**Comment by zmb3** [comment]
Partially addressed by https://github.com/gravitational/teleport/pull/13017

**Comment by zmb3** [comment]
Closing this for now since it seems #13017 has resolved the issues.
