### ISSUE TITLE
Add SELinux instructions for running Teleport as a daemon

### ISSUE THREAD

**Issue by cshabazian** [gravitational/teleport#9038]
## Details
Fix the SELinux security context of the systemd file by running
chcon system_u:object_r:systemd_unit_file_t:s0 /etc/systemd/system/teleport.service
After creating the service.  

### Category

- New Feature
- Improve Existing
- Remove Outdated

**Comment by alexfornuto** [comment]
The page this issue was originally written for no longer exists, and I haven't heard anything else about this being an issue... I'm asking anyone to bring it up if so, otherwise we'll close this issue in a few days.
