### ISSUE TITLE
Implement ttl/cleanup for firestore audit logs

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#9039]
Currently, teleport writes audit logs to firestore and that database will always increase in usage. Since firestore itself doesn't have a ttl / expiration feature, it would be nice if teleport could be configured to automatically delete records over a certain age.

**Comment by zmb3** [comment]
This is supported today, isn't it?

@espadolini to confirm I'm not speaking nonsense.

**Comment by espadolini** [comment]
Yep, it's been there since the very beginning, enabled by default (opt-out with the `disableExpiredDocumentPurge` parameter in the URI) with a default expiration time of one year.
