### ISSUE TITLE
Trying to run teleport in auth role

### ISSUE THREAD

**Issue by ritesh** [gravitational/teleport#907]
I'm trying to bootstrap a teleport cluster. If I run 
`teleport start --roles=auth`, I expect this to start an auth server. Instead it returns `BoltDB backend: 'path' is not set, initializing teleport` and quits. This is on a brand new host, with an empty /var/lib/teleport directory. If I run teleport without specifying roles, it works as described in the quickstart and I get an auth service, proxy service and node on the same host. 

My understanding is that to bootstrap a cluster you would need to start in this order. Auth server->proxy->nodes. Is that how it's meant to be or is my understanding incorrect?
I'm running the [latest binary release](https://github.com/gravitational/teleport/tree/v2.0.0-rc.2)

**Comment by klizhentas** [comment]
@ritesh this is fixed in master

**Comment by ritesh** [comment]
Nice, thanks! FYI, the binary release works as you'd expect with `--roles=auth` if you use the DynamoDB backend.
