### ISSUE TITLE
Accept session id for tsh play -f json command

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#9082]
### What
When using the `tsh play -f json` command, it looks for an actual session recording file on your local machine.  This is different from normal `tsh play` usage which just requires the session id and queries the logged in Teleport cluster.

Request is to have `tsh play -f json` accept both the file format (with .tar) to preserve offline behavior and just the session id (without .tar) where it can reach out to the logged in Teleport cluster to keep it in line with normal `tsh play` usage.

**Comment by russjones** [comment]
1. We want to support `tsh play` with a UUID to fetch a session from the cluster and then `-f` to display either events or the byte stream.
2. Support `tsh play` with a path on disk to parse local archive and then use `-f` to display either events or byte stream.

**Comment by russjones** [comment]
1. `tsh play UUID` downloads the session tarball from the proxy and plays back the session recording.
2. `tsh play -f json UUID` downloads the session tarball from the proxy and prints out JSON events.
3. `tsh play *.tar` plays back session recording from file on disk.
4. `tsh play -f json *.tar` prints JSON events from file on disk.

Here `*` means any path on disk or no path.
