### ISSUE TITLE
Require MFA tap on protocol level for all user-initiated administrative actions

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#9089]
### What

In 8.0 if MFA is enrolled, Teleport UI asks for MFA authentication for any administrative action. This protects from SSO takeover - if someone hacks SSO, they would need to hack Teleport MFA UI as well, to perform any administrative action.

This should be a requirement for any `tctl` administrative action initiated by the user:

* `tctl rm/edit`
* `tctl users`
* `tctl bots`
* `tctl nodes`
* `tsh request`
* Check for anything else that might be in scope

We have time to harden this until February, before the the audit, that will verify this statement.

**Comment by klizhentas** [comment]
@russjones please add this as a pure product/security request from me to the product queue.

**Comment by zmb3** [comment]
See also #5674, which is the same request but for the Web UI instead of tctl.
