### ISSUE TITLE
Missing Commit in v8 | Unable to use "+" sign when logging in via SSO

### ISSUE THREAD

**Issue by alexatcanva** [gravitational/teleport#9103]
### Description

**What happened**:
Unable to login using SSO authentication when using a "+" in resource.
**What you expected to happen**:
Be able to login using SSO authentication when using a "+" in the resource. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. `tsh login --auth=<SSO PROVIDER>`
2. Use a resource name with a "+"
3. Auth server throws errors

### Server Details
- Teleport version (run `teleport version`): 8
- Server OS (e.g. from `/etc/os-release`): N/a
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details: N/a

### Client Details
- Tsh version (`tsh version`): 8
- Computer OS (e.g. Linux, macOS, Windows): Mac Os
- Browser version (for UI-related issues): N/a
- Installed via (e.g. apt, yum, brew, website download): website download
- Additional details:
Error from auth server:
 error:[special characters are not allowed in resource names, please use name composed only from characters, hyphens a...

This was fixed in this commit here: https://github.com/gravitational/teleport/commit/71ea32fbaee7ceb701cd3806cb17588f7f2d23d1#diff-8397490ddee53dfda01cf1fd34e082e21c73dcb6407f7c7ea5ea5293f32bc13a

However this didn't seem to be re-released with v8.0.0 (it was present in v7.3.3)

**Comment by rosstimothy** [comment]
@atburke - We need a backport of #8396 to `branch/v8`
