### ISSUE TITLE
Teleport allows creating a SAML connector with empty `signing_key`

### ISSUE THREAD

**Issue by kbence** [gravitational/teleport#9104]
### Description

**What happened**: when reapplying a SAML connector that's previously been acquired via `tctl get connector/...`, the signing key is getting removed due to the fact, that `tctl get` strips it from the output. This results in a malformed SAML connector and disables authentication via that connector.

**What you expected to happen**: Teleport should either accept the empty private key and avoid changing it in the config, or throw an error and refuse to create / replace it.

### Reproduction Steps

1. On the UI, check if the SAML connector has a non-empty private key under `spec.signing_key_pair.private_key`
2.  Log in to the cluster using `tsh login ...`.
3. Get the current SAML connector using `tctl`, eg. `tctl get connector/my-saml-connector > temp.yaml`.
4. Replace the connector with the same YAML: `tctl create -f temp.yaml`.
5. Check the UI again, the key `spec.signing_key_pair.private_key` will be empty.

### Server Details
- Teleport version (run `teleport version`):  `Teleport Enterprise v7.3.2 git:v7.3.2-0-gaa361fbc1 go1.16.2`
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Teleport Cloud
- Additional details:

### Client Details
- Tsh version (`tsh version`): `Teleport Enterprise v7.3.3 git: go1.17.2`
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Installed via (e.g. apt, yum, brew, website download): compiled from git repo
- Additional details:

### Workaround

Deleting the key `spec.signing_key_pair` forces Teleport to regenerate the key.

**Comment by hugoShaka** [comment]
Fired this footgun during an incident this week and this made troubleshooting and fixing the SAML connector harder than it should have been.

I can reproduce this on a french build from `branch/v16`.
