### ISSUE TITLE
Automate AWS AD setup

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#9115]
When trying to get LDAPS and PKI infrastructure (for issuing certificates inside the domain) working with AWS Managed AD. 

Most of it seems to be manual steps, such as the huge blog post you have to follow to get it enabled.

Azure managed AD comes with LDAPS enabled out of the box.

The big issue is that Microsoft doesn't provide good ways to automate group policy objects. Many customers will already have most of this infrastructure set up - but I'm unsure if this is the case with AWS managed AD. LDAPS (a Teleport requirement) isn't something that you'd have enabled just for regular domain usage unless you have a specific need for it.

- It took engineer two hours to follow the blog post and that's clearly a non-starter for customers. It did actually work, but you have to follow things to the letter and there's a lot of potential issues that may crop up.

- There is a CloudFormation template (https://github.com/aws-quickstart/quickstart-microsoft-pki/blob/main/templates/two-tier.template) and associated PowerShell script (https://github.com/aws-quickstart/quickstart-microsoft-pki/blob/main/scripts/Modules/Module-Pki/Module-Pki.psm1) that looks to automate most of those same steps we followed in the blog post. 

@webvictim will try to get AWS managed AD setup deployed via automation this week and run the automation against it to see if I can fix any potential issues. If we at least have some recommended commands for customers which work in our demo environments, that will put us in a good place for deploying this with prospects.

From @klizhentas:

Can we use `tctl autoconfigure` approach to automate that configuration [similar to DB access](https://github.com/gravitational/teleport/blob/master/rfd/0046-database-access-config.md)?

**Comment by zmb3** [comment]
Dup of #8805?

**Comment by klizhentas** [comment]
closed and moved comments in favor of #8805
