### ISSUE TITLE
Add more logging configuration to helm's chart

### ISSUE THREAD

**Issue by pimguilherme** [gravitational/teleport#9123]
### What
We would like to request that log options like formatting (json) and an option to send audit logs to STDOUT while still sending to DynamoDB using the helm chart is possible. This is to be done on this chart: https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/

### How
We can simply add some logic to the cfg template and some values to the helm chart :)

### Why
We need this to enable sending JSON logs to our logging facility, and having the same log available on the container logs for both auditing and internal teleport stuff. We could use a custom config file but we're going this way to possibly help others

### Workaround
The workaround is to use the custom chart mode and edit these files directly on the teleport.yml file

**Comment by pimguilherme** [comment]
This is a summary of the changes:
![image](https://user-images.githubusercontent.com/1406885/143283442-bca8fa34-8f09-4526-b0c6-bd48389b052b.png)

![image](https://user-images.githubusercontent.com/1406885/143283470-635e59b2-7491-4ddc-9aee-515295b5e5b0.png)

**Comment by webvictim** [comment]
This was added in https://github.com/gravitational/teleport/pull/9130 / https://github.com/gravitational/teleport/pull/9484
