### ISSUE TITLE
Explicitly end application access sessions on teleport gui sign out

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#9124]
### Description

**What happened**: When logging out of the teleport web UI, any teleport application access sessions remain valid.

**What you expected to happen**: Logging out of the teleport web UI should server-side invalidate all application access sessions immediately.

NIST 800-53r5 has AC12 and SC-23(1) that would support the behavior of logging out of the gui invalidating all sessions for that user on that browser.

We do provide _a_ way to log out of an individual application, one at a time by hitting `/teleport-logout` and this is [documented here](https://goteleport.com/docs/application-access/guides/connecting-apps/#logging-out-of-applications). This isn't enough on its own since a user cannot confidently know that they have no active session cookies for teleport resources after they click on the "sign out" button in teleport. This is especially true since the application access cookie is still valid after the browser tab is closed.

### Reproduction Steps

As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Log in to a teleport web gui.
2. Access any application access application.
3. Log out of teleport web gui.
4. Observe that you can still access the already open application.

### Server Details

- Teleport version (run `teleport version`): tested and observed on 7.2.0, 7.3.3, and 8.0.0
- Server OS (e.g. from `/etc/os-release`): N/A
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): kubernetes
- Additional details:

### Client Details

- Tsh version (`tsh version`): N/A
- Computer OS (e.g. Linux, macOS, Windows): N/A
- Browser version (for UI-related issues): Google Chrome 96.0.4664.45 on osx
- Installed via (e.g. apt, yum, brew, website download): N/A
- Additional details:

### Debug Logs

Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by russjones** [comment]
@r0mant Can you update this ticket with details on how you plan to fix this.

We'll also need to allocate some fullstack engineering time to make this happen as well.

**Comment by russjones** [comment]
This is also useful for password reset situations.

**Comment by r0mant** [comment]
@gabrielcorado Just to recap, the way we want to address this is:

- When creating a web or application sessions, make sure that they have proper username set (as a part of resource spec).
- When handling [logout](https://github.com/gravitational/teleport/blob/v8.1.0/lib/web/apiserver.go#L1426) and deleting the web session, make sure to delete all app sessions for the same username as well.

We probably also want to clear all web/app sessions when resetting a password for a user like @russjones mentioned above but I feel like it's a bit tangential and can be done in a separate PR.
