### ISSUE TITLE
Replace OG Image for this Repo

### ISSUE THREAD

**Issue by C-STYR** [gravitational/teleport#9169]
### Description
Transfers [this issue](https://github.com/gravitational/web/issues/2374) from gravitational/web to the appropriate repo, which is a request by Marketing to replace the outdated OG image on this repo with a current one.  The new image can be found in the link in the comments on the original issue linked above. 

How to fix: 
The image can be replaced using [these instructions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview).  Only a user with access to the Settings page for this repo can effect this replacement, but the whole process should take about 30 seconds once in the right hands.

Here's a screenshot of the gravitational/next version of the same interface: 
![Screen Shot 2021-11-30 at 12 40 16 PM](https://user-images.githubusercontent.com/73362670/144049094-958b98ed-fb65-4522-b4bd-63bab9718ac6.png)

**Comment by russjones** [comment]
Done.
