### ISSUE TITLE
Show a clearer error message when a user runs tctl prior to writing the host UUID

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#9175]
### What
As mentioned in [this issue](https://github.com/gravitational/teleport/issues/8077), if you attempt to run a `tctl` command before Teleport starts and writes the host UUID to a file, `tctl` will return a cryptic error:

```
lstat /var/lib/teleport/host_uuid: no such file or directory
```

It would be great if `tctl` indicated here that `teleport` needs to be started before you can use `tctl`. If you run `teleport start`, wait until the host UUID is written to a file, then terminate the process, the `tctl` error is more verbose:

```
[CLIENT]       Cannot connect to the auth server: failed direct dial to auth server: Get "https://teleport.cluster.local/v2/configuration/name": dial tcp 127.0.0.1:3025: connect: connection refused
        Get "https://teleport.cluster.local/v2/configuration/name": dial tcp 127.0.0.1:3025: connect: connection refused.
Is the auth server running on "127.0.0.1:3025"?
```

### How
Currently, [`utils.ReadHostUUID`](https://github.com/gravitational/teleport/blob/38b24f68032d76768dca5a7c98758e48dce282dd/lib/utils/utils.go#L429-L436) returns an error from `ReadPath` using `trace.Wrap(err)`. We can add an argument to `trace.Wrap` indicating that Teleport must be started before you can run `tctl` commands.

### Why
While production deployments of Teleport are unlikely to encounter this issue, since it only takes place if `teleport` has not been run on a host, this reduces friction while spinning up a demo deployment, where a user might be tempted to run `tctl` before running `teleport start` (this is how I ran into the issue).

### Workaround
N/A: remember to run `teleport start` before any `tctl` commands.

**Comment by ulysseskan** [comment]
I ran into this today and would like to see this too.
