### ISSUE TITLE
Show Available DB Users for a Database with tsh

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#9181]
### What
Currently, it is not possible for an end-user of Teleport to validate which DB users they have available through Teleport to access a database using the `tsh` tool.  The feature request is to offer some option to view available DB users using the `tsh` tool as an end-user.

### How
The main requirement is to be able to view available DB users for a database using `tsh` before `tsh db login` is required so any method that accomplishes that workflow is acceptable.  I would suggest this functionality be included in the `tsh db ls` command, either by default or as an opt-in flag. 

### Why
Not all end users will be aware of which DB users are available, especially in a dynamic environment or using access requests

**Comment by Tener** [comment]
It isn't clear to me how exactly is this supposed to work.

My best guess is that `tsh db ls` should somehow evaluate access rules to find available users for currently logged in user. But we don't have any way of actually doing that in `tsh` -- the appropriate access check logic looks tied to auth server. We could expose that with a new endpoint, but that sounds rather complex compared to what we want to achieve here?

Another issue is that with permissive access rules (allowed db_users = '*') we don't really have any finite set of usernames to display. This gets complicated further if the deny rules are in place (allow=*, deny=root,admin -- how to display that?).

Am I overcomplicating things or is there some misunderstanding on my part? Or maybe I mistakenly expected lower complexity from [good-starter-issue](https://github.com/gravitational/teleport/labels/good-starter-issue) label.

Can you give your thoughts @r0mant @pschisa @smallinsky ?

**Comment by smallinsky** [comment]
The list of available DB users is already encoded in user identity:   https://github.com/gravitational/teleport/blob/master/lib/tlsca/ca.go#L121  and can be read by tsh command during `tsh db ls` command. 
Though the information provided by DBUsers field is not complete to handle the ` allow: '*" deny: "root,admin"` case. 
We can consider adding db user deny list to the user identity or fetch it dynamically during `tsh db ls` command execution.
In terms of UX in the case of `allow: '*" deny: "root,admin"` we can just display `*` with some information that `root,admin` users are excluded for the `*` group.

**Comment by Tener** [comment]
@pschisa do you know if we need to backport this to older versions?

**Comment by pschisa** [comment]
Asking now and will gauge the urgency.  Is a v8 backport non-trivial?

**Comment by Tener** [comment]
v8 should be easy and if needed other versions should be doable too.

**Comment by pschisa** [comment]
Confirmed v9 is necessary.  If v8 is easy then doing both would definitely cover all current requests

**Comment by pschisa** [comment]
Confirmed a request for v8 if possible, so v8 and v9 would suit all needs

**Comment by Tener** [comment]
Awesome, thanks for confirming.
