### ISSUE TITLE
`tsh proxy ssh` does not respect user from `%r@%h:%p` spec when TLS routing is disabled

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#9212]
### Description

If the Teleport 8.0 cluster is running in the **non TLS routing** mode (i.e. `version: v1` and `proxy_listener_mode: separate`), `tsh proxy ssh` command does not correctly parse the connection spec `%r@%h:%p`:

```
ProxyCommand tsh proxy ssh %r@%h:%p
```

When trying to connect with a regular `ssh` client, you get the following error in the proxy indicating it's trying to use the default host login instead of the one from the spec:

```
ssh: principal "r0mant" not in the set of valid principals for given certificate: ["root" "ubuntu"]
```

If proxy command is updated to include host login via explicit CLI flag, it starts working correctly:

```
ProxyCommand tsh -l %r proxy ssh %r@%h:%p
```

It looks like sshProxy method should be updated to take username from `tc.HostLogin` instead of `cf.NodeLogin`:

https://github.com/gravitational/teleport/blob/v8.0.0/tool/tsh/proxy.go#L125

**Comment by smallinsky** [comment]
Fixed in https://github.com/gravitational/teleport/pull/9219
