### ISSUE TITLE
The apt repository is providing outdated teleport version

### ISSUE THREAD

**Issue by ZeroClover** [gravitational/teleport#9225]
### Description

**What happened**:

When I installed teleport for the new leaf node today, I found that the version provided by the apt repository was 6.2.19, which prevented connection to the root node with teleport 7.0 or later. #7689

![image](https://user-images.githubusercontent.com/13190004/144688084-6fbffd65-5aad-40e0-89b2-78adcd7519d0.png)

**What you expected to happen**:

The apt repository should provide the latest Teleport binary.

**Comment by pschisa** [comment]
seems related to #8166

**Comment by webvictim** [comment]
This was fixed in #8166
