### ISSUE TITLE
JuypterHub not working behind Teleport

### ISSUE THREAD

**Issue by lyh16** [gravitational/teleport#9245]
### Description

**What happened**:
You can log in to JupyterHub, but you can't do anything inside. 'New Notebook', 'Open Notebook', 'Delete Notebook', etc. all result in the "Not Found" error.
**What you expected to happen**:
Be able to perform all necessary activities on the JupyterHub as if I was accessing it locally.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Set up Teleport proxy+auth+node server outside of firewall
2. Add internal (behind firewall) JupyterHub app to Teleport
3. Log into JupyterHub account

### Server Details
- Teleport version (run `teleport version`): Teleport v8.0.1 git:v8.0.1-0-gb95fb530b go1.17.3
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.4.3 LTS (Focal Fossa)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Outside proxy server -> Oracle Cloud Compute Instance, JupyterHub -> Dedicated Hardware
- Additional details:  Log in: O, Open notebook: O, Load kernel: X, Delete notebook: X, Open JSON file: O

### Client Details
- Tsh version (`tsh version`): Teleport v8.0.1 git:v8.0.1-0-gb95fb530b go1.17.3
- Computer OS (e.g. Linux, macOS, Windows): Windows 11
- Browser version (for UI-related issues): Firefox (64-bit)
- Installed via (e.g. apt, yum, brew, website download): Website download
- Additional details: Log in: O, Open notebook: O, Load kernel: X, Delete notebook: X, Open JSON file: O / The JupyterHub itself works fine when I access it from an internal computer. The issues only arise when I try to access the JuypterHub from outside of the corporate network via Teleport.

**Comment by ivan-tkatchev** [comment]
We fixed this by putting the proper rewrite: headers: "host: ..." directive in the Teleport yml config.
Jupyter wants the Referer and Host to match, so you need to tell Teleport to send a Host header that matches your Teleport Jupyter app public address.
