### ISSUE TITLE
can I limit number of login session?

### ISSUE THREAD

**Issue by stephencheng** [gravitational/teleport#925]
is there a way to limit 5 login sessions for example?

**Comment by kontsevoy** [comment]
you mean simultaneous users? or simultaneous sessions per user?

**Comment by kontsevoy** [comment]
also, what the use case would be, thanks!

**Comment by stephencheng** [comment]
I mean the simultaneous session per user.

A use case would be:

1. user a login as usera using web terminal
2. user a also login using a cli command

if I config the limit of the concurrent session count to be 2, then if any one using usera's account to login using another browser or cli command in another tab, then the session will be rejected.

**Comment by kontsevoy** [comment]
@stephencheng we'll consider it. won't promise anything publicly.. ;-) still curious, why would you want to have a limit like this. wouldn't "session duration" be a better limit? one can even theoretically lock themselves out, by leaving a session open somewhere and then hit the limit from a new location and not being able to fix it.

**Comment by stephencheng** [comment]
This is to not to encourage a group of people to share the same login account hence result in security issue

Thanks
