### ISSUE TITLE
Recorded Sessions Unavailable but are on server ready to view

### ISSUE THREAD

**Issue by Wolfwood369** [gravitational/teleport#9259]
### Discussed in https://github.com/gravitational/teleport/discussions/9258

<div type='discussions-op-text'>

<sup>Originally posted by **Wolfwood369** December  6, 2021</sup>
in both versions 7.1 and now 8.0.1, when I try to view recorded sessions, what I get is a message:

"Recording for this session is not available."

I have searched for an answer to this issue without success. I check the server and the recordings are there. Everything tells me that the session is ready to view. I simply can't play it on the front end.

FYI - I set up teleport with 2 separate containers. One is the frontend that is exposed externally and the other is the authentication server the is behind my firewall. I'm getting the feeling that something about this setup is what is contributing.</div>

**Comment by stevenGravy** [comment]
@Wolfwood369 likely that your role doesn't ahve `session` resource as list and read.

**Comment by stevenGravy** [comment]
In your access role please add the following

```yaml
    - resources:
      - session
      verbs:
      - list
      - read
```

**Comment by Wolfwood369** [comment]
100% that fixed it. Such a tiny oversight with big implications.

**Comment by Wolfwood369** [comment]
Thanks for the help.
