### ISSUE TITLE
[tsh] Odd behavior with wrapping long commands

### ISSUE THREAD

**Issue by ekristen** [gravitational/teleport#926]
When using the `tsh` command there is a weird wrapping or lack thereof wrapping behavior happening. 

With copy and paste if the command is longer than the terminal, it puts the entire command on the second line, well sort of, it really has it on the first line with the prompt, but you cannot see the text unless you scroll back with your cursor. 

If you type a command that is larger than your terminal then it just wraps back on itself. 

Here is a gif of the copy and paste, if you want to see the second let me know. 

![out](https://cloud.githubusercontent.com/assets/48329/24964501/aef2c4f6-1f5e-11e7-85db-705cf24d72d8.gif)

**Comment by kontsevoy** [comment]
@ekristen we actually see this behavior with long commands in Gnome terminal on ubuntu, not just with `tsh`. In other words this is outside of our control. ;)

**Comment by aashley** [comment]
Actually I'd disagree with you, having used gnome-terminal as my primary interface for better than 10 years now the *only* program I experience this with is tsh

**Comment by ekristen** [comment]
I agree with Adam.

**Comment by kontsevoy** [comment]
this can be related: #1087
