### ISSUE TITLE
Abrupt connection disruption of all nodes to Teleport

### ISSUE THREAD

**Issue by WilliamLoy** [gravitational/teleport#9269]
### Description

**What happened**:
All nodes dropped connection to Teleport.

Restarting auth server resolved the issue. 

**What you expected to happen**:
Nodes to maintain the connection. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
Unable to replicate. 

### Server Details
- Teleport version (run `teleport version`):6.2.13
- Server OS (e.g. from `/etc/os-release`):  Ubuntu 20.04.1 LTS
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Dec 06 22:13:53 ip teleport[864]: 2021-12-06T22:13:53Z WARN [AUTH]      "\nERROR REPORT:\nOriginal Error: *trace.NotFoundError cluster configuration not found\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/services/local/configuration.go:219 github.com/gravitational/teleport/lib/services/local.(*ClusterConfigurationService).GetClusterConfig\n\t/go/src/github.com/gravitational/teleport/lib/cache/cache.go:1049 github.com/gravitational/teleport/lib/cache.(*Cache).GetClusterConfig\n\t/go/src/github.com/gravitational/teleport/lib/auth/permissions.go:233 github.com/gravitational/teleport/lib/auth.(*authorizer).authorizeBuiltinRole\n\t/go/src/github.com/gravitational/teleport/lib/auth/permissions.go:116 github.com/gravitational/teleport/lib/auth.(*authorizer).fromUser\n\t/go/src/github.com/gravitational/teleport/lib/auth/permissions.go:102 github.com/gravitational/teleport/lib/auth.(*authorizer).Authorize\n\t/go/src/github.com/gravitational/teleport/lib/auth/apiserver.go:273 github.com/gravitational/teleport/lib/auth.(*APIServer).withAuth.func1\n\t/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:61 github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:387 github.com/julienschmidt/httprouter.(*Router).ServeHTTP\n\t/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:173 github.com/gravitational/teleport/lib/httplib.RewritePaths.func1\n\t/opt/go/src/net/http/server.go:2042 net/http.HandlerFunc.ServeHTTP\n\t/go/src/github.com/gravitational/teleport/lib/auth/middleware.go:541 github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP\n\t/opt/go/src/net/http/server.go:2843 net/http.serverHandler.ServeHTTP\n\t/opt/go/src/net/http/server.go:1925 net/http.(*conn).serve\n\t/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit\nUser Message: cluster configuration not found" auth/apiserver.go:283

**Comment by zmb3** [comment]
Closed due to inactivity.
