### ISSUE TITLE
Implement auth connector configurator and tester

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#9270]
As of today, the feature is fully implemented in code. Some tasks remain. Here is the breakdown of individual tasks, finished and not.

- [x] `tctl sso configure`
  - [x] [RFD link](https://github.com/gravitational/teleport/blob/master/rfd/0070-tctl-sso-configure-command.md), issue: https://github.com/gravitational/teleport/pull/9845
  - [x] GitHub support: https://github.com/gravitational/teleport/pull/12783
  - [x] SAML support: https://github.com/gravitational/teleport/pull/11508
  - [x] OIDC support: https://github.com/gravitational/teleport/pull/12519
  - [x] CLI reference: https://github.com/gravitational/teleport/pull/13148
- [x] `tctl sso test`
  - [x] [RFD link](https://github.com/gravitational/teleport/blob/master/rfd/0071-tctl-sso-test-command.md), issue: https://github.com/gravitational/teleport/pull/9775
  - [x] GitHub support: https://github.com/gravitational/teleport/pull/12783
  - [x] SAML support: https://github.com/gravitational/teleport/pull/11508
  - [x] OIDC support: https://github.com/gravitational/teleport/pull/12519
  - [x] CLI reference: https://github.com/gravitational/teleport/pull/13148
- [ ] Documentation update
  - [x] CLI reference update: https://github.com/gravitational/teleport/pull/13148
  - [x] Enterprise SSO page, references to relevant topics: https://github.com/gravitational/teleport/pull/14227
  - [x] Github SSO guide: https://github.com/gravitational/teleport/pull/14227
  - [ ] Individual enterprise IdP guides (Okta, Google Workspace, ...): 
- [x] Test plan update https://github.com/gravitational/teleport/pull/13058
  - [x] `tctl sso configure`
  - [x] `tctl sso test`
- [x] Validate the feature against Teleport Cloud.

<details>
  <summary>Original issue description.</summary>

> ## What
> 
> Teleport allows users to create auth connectors to connect their cluster to an IdP but does not provide any tools to simplify this configuration and users often struggle to configure it correctly.
> 
> Teleport should provide a mechanism for users to create and test an auth connector. We're starting with CLI improvements but will extend it to UI in future so keep this in mind and design APIs in a way that they can be used by both.
> 
> ## Scope
> 
> We want to start by supporting most commonly used providers and have ability to extend to others in future. For the initial scope let's focus on:
> 
> - [ ] Okta (SAML)
> - [ ] Google (OIDC)
> - [ ] ADFS (SAML)
> 
> ## UX
> 
> The idea behind the UX is as follows:
> 
> - Provide a way to generate an auth connector resource yaml from one of presets, with as much info prepopulated as we can (e.g. from `.well-known`).
> - Provide a way to test the connector given the resource yaml file.
> 
> With this flow a user will be able to 1) generate connector yaml file from one of presets, 2) test it and see whether it works and what claims/attributes are returned, 3) create it in the cluster using existing `tctl create` command.
> 
> ### Creating auth connector
> 
> We're using `teleport xxx configure` subcommands to generate configurations for various services. So the command could look like:
> 
> ```
> $ tsh sso configure [--preset=okta] https://example.com/.well-known \
>         --attributes-to-roles="{}" \
>         --signing-keys=/path/to/xxx
> ```
> 
> We could also generate a config with some sections (like, role mapping) prefilled but commented out so users can edit it. The command would produce a connector resource yaml that would look something like:
> 
> ```yaml
> kind: saml
> version: v2
> metadata:
>   name: okta
> spec:
>   acs: https://proxy.example.com:3080/v1/webapi/saml/acs
>   attributes_to_roles:
>     # - {name: "groups", value: "okta-admin", roles: ["admin"]}
>   entity_descriptor:
>     # can autofill
>   signing_keys: |
>     # sample signing keys
> ```
> 
> ### Testing auth connector
> 
> Once the connector yaml exists, user should be able to test it e.g.
> 
> ```
> $ tsh sso test okta.yaml
>   http://localhost:8080/1234
> 
>  > claims:
>         email: foo@example.com
>         uid: 201
> ```
> 
> The command would take the user through the SSO flow and print out received claims and the role the user would be assigned in Teleport according to the role map.
> 
> We should start by creating an RFD.

</details>

**Comment by r0mant** [comment]
@Tener Can this be closed now?

**Comment by Tener** [comment]
@r0mant the SSO guides are not updated, but I think we can take this out of the scope of this particular issue and mark it as completed.
