### ISSUE TITLE
Allow multiple Windows Desktop Services that proxy to different sets of desktops

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#9277]
### What

While Teleport supports multiple Windows Desktop Services, they must all have connectivity to the full set of Windows Desktops. This is because when establishing a connection, Teleport picks a Windows Desktop Service at random.

### How

Add a field to the Windows Desktop resource that lists the ID or IDs of the Windows Desktop Services that can reach the desktop. Select an appropriate service to proxy the RDP connection at connect-time.

### Why

To enable access to disparate sets of desktops behind different firewalls.

**Comment by zmb3** [comment]
Implementation notes:

- `windows_desktop_service` reports `WindowsDesktop` resources to the auth server, either via [heartbeats](https://github.com/gravitational/teleport/blob/730352c3b0c3add811eb71a8892a78db126bb38a/lib/srv/desktop/windows_server.go#L389-L413) (for static hosts) or the [reconciler](https://github.com/gravitational/teleport/blob/730352c3b0c3add811eb71a8892a78db126bb38a/lib/srv/desktop/discovery.go#L58-L61) (for hosts discovered via LDAP)
- these heartbeats should include a new field that identifies the `windows_desktop_service` which reported the desktop. Database access uses the `HostID` field for this: https://github.com/gravitational/teleport/blob/b95fb530bb7d3ad356d7dce3ec115045db5c6fa8/lib/srv/db/server.go#L517
- at connection time, the Teleport proxy currently selects a random windows_desktop_service to connect to:
https://github.com/gravitational/teleport/blob/730352c3b0c3add811eb71a8892a78db126bb38a/lib/web/desktop.go#L100-L106
- the above should be update to select a service that is capable of connecting to the specified desktop. Database access builds a list of candidates here:
https://github.com/gravitational/teleport/blob/b95fb530bb7d3ad356d7dce3ec115045db5c6fa8/lib/srv/db/proxyserver.go#L504-L512
and then selects one from that list here:
https://github.com/gravitational/teleport/blob/b95fb530bb7d3ad356d7dce3ec115045db5c6fa8/lib/srv/db/proxyserver.go#L297-L310

**Comment by russjones** [comment]
@zmb3 @lxea Do we want to backport this and release it in Teleport 8.3.x or wait until Teleport 9?
