### ISSUE TITLE
SSH node cache errors

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#931]
This is NOT from the production branch(s). This is new stuff going into 2.1.
When I run a stress-test (having many _concurrent_ clients executing the command below) I see them fail sometimes with the error.

Client looping this:

```
$ tsh ssh --proxy=localhost ls / > /dev/null
```

## Error One

Server spits this into the logs:

```
WARN[2583] failed to execute command /var/lib/teleport/cache/node/authorities/user error:  directory not empty  file=srv/sshserver.go:516 func=srv.(*Server).isAuthority
```

or 

```
ERRO[2543] failed to execute command /var/lib/teleport/cache/node/authorities/user error:  directory not empty  file=srv/sshserver.go:616 fingerprint=ssh-rsa-cert-v01@openssh.com e2:b8:d9:17:8a:44:f4:0a:53:82:13:57:bd:17:5e:40 func=srv.(*Server).keyAuth local=127.0.0.1:3022 remote=::1:61803 user=ekontsevoy
```

## Error Two

Another (when this happens a 100% valid user would get "access denied" error):

```
WARN[0290] open /var/lib/teleport/cache/proxy/authorities/user/0651e63d-4262-404d-9466-9003a7eec33b: no such file or directory  file=srv/sshserver.go:516 func=srv.(*Server).isAuthority
```

## Error Three

When I launch 50 simultaneous clients, I see the following error in the server logs:

```
WARN[1685] Backoff: using cached value due to recent errors  file=state/cachingaccesspoint.go:418 func=state.(*CachingAuthClient).try
```

And then `teleport` locks up (stops accepting connections and CPU utilization is at 0%). `tsh` would just hang trying to connect.

**Comment by kontsevoy** [comment]
looks like it's the same error, it's just logged differently from 2 places.

**Comment by kontsevoy** [comment]
can we close it? seems to be fixed by #961

**Comment by klizhentas** [comment]
I still think error three could still be a problem.

**Comment by klizhentas** [comment]
I could not reproduce the locks so far - did a series of tests, and did not encountered the locks. I saw the slowness though due to load on the server, but the sessions were completing.

**Comment by kontsevoy** [comment]
@klizhentas claims the last issue is not happening anymore under our brand new stress testing framework.
