### ISSUE TITLE
Trusted Cluster Feature Request / Clarification - Support Multiple Roles

### ISSUE THREAD

**Issue by ekristen** [gravitational/teleport#932]
## Current Behavior

When you create a trusted cluster you define the role or roles required to be assigned to a user from the main cluster. 

If that role states that the login allowed is `ubuntu` that is the only login that the user from the main cluster can use, even if the user has more roles associated or more allowed logins associated with it on the main cluster.

## Requested Behavior 

When you create a trusted cluster you define a role or list of roles required to be assigned to a user from the main cluster, if that user has that role associated then they are allowed to login.

In addition to that, if the user from the main cluster has 3 roles assigned to it, when they login to cluster-b (the trusted cluster) the role names should be passed down with the login process. This way if the other roles have been created on cluster-b and state the user has certain restrictions or other logins that can be used, they take affect.

For example: on cluster-A (the main cluster) user `ekristen` has 3 roles `user:ekristen,admin,superadmin`. 

* `superadmin` logins are `root`
* `admin` logins are `admin`
* `user:ekristen` logins are `ekristen`

When logging into any server in cluster-A (the main cluster) user ekristen is allowed to login as `ekristen, admin, or root`. 

Currently when logging into trusted cluster cluster-B, since the required role is `superadmin` user `ekristen` is only allowed to login as root. 

The request is this, when user `ekristen` logins to a server in cluster-B (via cluster-A), all 3 role names should be transmitted to `cluster-B` as apart of the auth process. If role `user:ekristen` exists on cluster-B, then allow ekristen to also login as `ekristen`. If the role `admin` exists on cluster-B, then allow ekristen to also login as `admin`. If neither of the roles exist, the only role by default due to required roles would be `superadmin` and the login of `root`.

**Comment by ekristen** [comment]
Thoughts?

**Comment by kontsevoy** [comment]
@ekristen this has been released with 2.3
