### ISSUE TITLE
tsh ls commands should declutter output with many labels present

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#9321]
### What
What would you like Teleport to do differently?

If an environment makes extremely heavy use of labeling, the `tsh ls`, `tsh db ls`, `tsh kube ls`, or `tsh app ls` command can have extremely cluttered output.

The end user may not know nor care about the labels, and their experience is affected by a resource having a lot of labels.

### How

There are a lot of possible solutions that would work. Some possibilities include:

* tsh ls commands truncate long label lists by default and allow you to opt back in to the full output with a `--no-trunc` type option (similar to docker commands)
* a change to the rbac system could allow a given user to not have permissions to see the labels on a node or resource they otherwise can see.
* a new feature could allow a teleport admin to designate labels as "hidden by default" or as "system" labels.

### Why

quality of life

### Workaround

ugly wrapper script or diy api client, both not practical for a qol improvement.

-----

This particular issue came up in the context of `tsh db ls`, but all the `tsh ls` commands have some inconsistencies. There are several existing issues related to `tsh ls` type functionality:

* https://github.com/gravitational/teleport/issues/9181
* https://github.com/gravitational/teleport/issues/8087
* https://github.com/gravitational/teleport/issues/6742
* https://github.com/gravitational/teleport/issues/5244
* https://github.com/gravitational/teleport/issues/4892
* https://github.com/gravitational/teleport/pull/9091

**Comment by russjones** [comment]
Namespaced labels are labels with `/` in them, for example `teleport.dev/postgres`. These are labels used to make RBAC decisions.

These labels will be sorted to the end of a slice. Then we will show all that can be seen determined by the width of the terminal window and then use `...` to truncate similar to `tctl requests ls`.

The verbose flag `-v` can be used to show all.

**Comment by russjones** [comment]
Merged in #9668 and #9589.
