### ISSUE TITLE
Stress testing the ssh output failed.

### ISSUE THREAD

**Issue by jeremyje** [gravitational/teleport#933]
`ls / -laR | lolcat`

overwhelmed the server. I got a lot of these in the logs and also the web ui froze.

WARN[0537] Audit log cannot keep up. Dropping event ''   file=state/log.go:101 func=state.(*CachingAuditLog).post
WARN[0537] Audit log cannot keep up. Dropping event ''   file=state/log.go:101 func=state.(*CachingAuditLog).post
WARN[0537] Audit log cannot keep up. Dropping event ''   file=state/log.go:101 func=state.(*CachingAuditLog).post

**Comment by klizhentas** [comment]
thanks for your report, we will take a look!

**Comment by klizhentas** [comment]
@jeremyje can you tell me the teleport version as well?

**Comment by jeremyje** [comment]
teleport version
Teleport v2.1.0-alpha.2 git:v2.1.0-alpha.2-0-g415dea46

**Comment by jeremyje** [comment]
Also Chrome SSH extension works fine with that command. I'm also connected to a server over a Gigabit line.

**Comment by klizhentas** [comment]
I was able to reproduce setting to 2.1 milestone

**Comment by klizhentas** [comment]
@alex-kovoy that is only partially addressed, so I'm keeping this open. Other issues are server based and are related to inefficient transfer of the events via event logs, so I will keep assigned to myself.
