### ISSUE TITLE
Rancher / Vcenter environment. Helm chart for nodeport?

### ISSUE THREAD

**Issue by arcreigh** [gravitational/teleport#9331]
My kubernetes install is not going to plan. The helm chart / documentation states that the install chart relies on loadbalancer. When deploying in a self hosted environment not a cloud environment the load balancer is unable to query an API to obtain an external IP which causes the load balancer to never fully provision.

Is there a flag or some other mechanism in place to allow for a nodeport service instead of a load balancer service?

**Comment by arcreigh** [comment]
Worked around by installing metallb into the on prem environment. It needs to be noted that this really should have some kind of alternative helm chart that does not rely on LoadBalancer as LoadBalancer only works (by default) In cloud environments. Metallb is a workaround that allows you to define internal addresses and still allow for all the benefits of running teleport on a home kubernetes lab.

**Comment by webvictim** [comment]
This is now doable with `service.type`: https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L238-L243
