### ISSUE TITLE
Teleport in Amphere K8s get CrashLoopBackOff

### ISSUE THREAD

**Issue by fdelucchijr** [gravitational/teleport#9348]
### Description

**What happened**:
When I try to run Teleport on a K8s node at Oracle in an Amphere A1 2vcpu 12 RAM it gets the following error:
`/usr/local/bin/teleport: error while loading shared libraries: libpthread.so.0: ELF load command alignment not page-aligned`
This is probably related to [this](https://github.com/dart-lang/sdk/issues/47709).

**What you expected to happen**:
Simply start teleport to manage my k8s internal apps 😢.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Install terraform-cluster helm chart in any amphere cluster

### Server Details
- Teleport version: is running quay.io/gravitational/teleport:8.0.3 image
- Server OS: Ubuntu 20.04, but this shouldn't be a problem because containerization 
- Where are you running Teleport?: Oracle Amphere OKE Cluster

**Comment by webvictim** [comment]
All of the Teleport images hosted on https://quay.io/repository/gravitational/teleport?tab=tags (including `quay.io/gravitational/teleport:8.0.3`) contain `amd64` binaries. It appears that the A1 is an ARM-based CPU, meaning that `amd64` binaries wouldn't run on it.

You'd need to build a container with Teleport `arm` or `arm64` binaries instead ([available for download here](https://goteleport.com/teleport/download/)) and change the chart to use this image instead.

Related to #3384

**Comment by zmb3** [comment]
We now offer ARM container builds.

**Comment by fdelucchijr** [comment]
Thanks!!!
