### ISSUE TITLE
Server Install Script

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#9361]
### Description

**What happened**:
When looking into the server install script that is provided one can change the URL and grab the script from another teleport system. 
**What you expected to happen**:
Since the token value is unique in the URL for each system then it should not respond with the install script unless the token is matching to the teleport cluster itself. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Login to Teleport
2. Copy the URL to the server install script
3. Change the DNS name to another valid teleport setup and press enter

**Comment by zmb3** [comment]
This isn't a bug. The token in the URL is used to substitute a placeholder in the script.

Whether or not we should change that is of course up for debate. It would introduce some extra book-keeping and state management for arguably little value, IMO.
