### ISSUE TITLE
Allow custom HTTP headers in API requests provided through the environment

### ISSUE THREAD

**Issue by stouset** [gravitational/teleport#9375]
### What

Square requires connections to internal systems to transit through a BeyondCorp web proxy. Authentication is performed against this proxy by including a custom authentication cookie to proxied HTTP requests.

We'd like to be able to configure the teleport client to issue requests with these headers. Additionally, we'd like teleport to respect the existence of `https_proxy` and `http_proxy` environment variables through [`http.ProxyFromEnvironment`](https://pkg.go.dev/net/http#ProxyFromEnvironment).

### How

1. all `http.Client` initialization should configure the client with `Proxy: http.ProxyFromEnvironment`.

2. HTTP clients that fallback to insecure should allow doing so if either the request URL is a localhost address (current behavior) *or* if the proxy is a localhost address.

3. HTTP clients should look for an environment variable (suggested: `TELEPORT_WEBCLIENT_HEADERS`). When this variable is present, the headers contained within should be passed on through to HTTP client requests.

### Why

To get through Square's BeyondCorp authenticating proxy.

### Workaround

Unfortunately no workaround exists.

**Comment by stouset** [comment]
https://github.com/gravitational/teleport/pull/9376

**Comment by stouset** [comment]
https://github.com/gravitational/teleport/pull/9377

**Comment by stouset** [comment]
Closes #6831

**Comment by klizhentas** [comment]
Removing `needs-product-decision` see discussion and comments on:

https://github.com/gravitational/teleport/pull/9475

**Comment by r0mant** [comment]
This was implemented in https://github.com/gravitational/teleport/pull/10336.
