### ISSUE TITLE
tsh kube login should preserve TELEPORT_HOME when writing kubeconfig

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#9387]
### Description

**What happened**:

If you set the TELEPORT_HOME variable, it tells the `tsh` binary to look in an alternate location instead of `~/.tsh`. Unfortunately, when TELEPORT_HOME is set, and the kubeconfig file is written out, the presence of this setting is not considered. The effect is that kubectl commands don't work properly.

**What you expected to happen**:

The kubeconfig that tsh writes out should preserve the TELEPORT_HOME variable functionality. This will likely mean that the kubeconfig entries will need to have the `env:` key populated with the TELPORT_HOME key and value, and the `tsh kube credentials` command will need to respect it as well.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. set `TELEPORT_HOME` to a non-default location.
2. do a `tsh login` and `tsh kube login`
3. attempt to run any `kubectl` command.

### Server Details
- Teleport version (run `teleport version`): 8.0.0
- Server OS (e.g. from `/etc/os-release`): n/a
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): n/a
- Additional details:

### Client Details
- Tsh version (`tsh version`): 8.0.0
- Computer OS (e.g. Linux, macOS, Windows): mac
- Browser version (for UI-related issues): n/a
- Installed via (e.g. apt, yum, brew, website download): website download
- Additional details:

**Comment by programmerq** [comment]
Additionally, any tsh function should respect the TELEPORT_HOME setting. `tsh config`, `tsh db login`, etc should all have similar testing done around TELEPORT_HOME

**Comment by gclawes** [comment]
Relevant documentation for `env:` from client-go credential plugin: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

**Comment by jakule** [comment]
Recently we fixed the TELEPORT_HOME in many places on master:
https://github.com/gravitational/teleport/pull/9226
https://github.com/gravitational/teleport/pull/9240
https://github.com/gravitational/teleport/pull/9436

If needed we could also port them to v8 branch.
