### ISSUE TITLE
failing compile on smartos

### ISSUE THREAD

**Issue by logic855** [gravitational/teleport#939]
Hi,

I am trying to compile teleport on smartos.

```
# getting & building:
$ go get github.com/gravitational/teleport
$ cd $GOPATH/src/github.com/gravitational/teleport
$ make
```
which results in:
```
go build -o build/tsh -i  -ldflags '-w -s' ./tool/tsh
# github.com/gravitational/teleport/vendor/github.com/docker/docker/pkg/term
vendor/github.com/docker/docker/pkg/term/tc_other.go:11: undefined: Termios
vendor/github.com/docker/docker/pkg/term/tc_other.go:16: undefined: Termios
vendor/github.com/docker/docker/pkg/term/term.go:19: undefined: Termios
Makefile:36: recipe for target 'build/tsh' failed
make: *** [build/tsh] Error 2
```

I found that the docker term.go has been updated to also support solaris, but when i replace vendor/github.com/docker/docker/pkg/term with the latest from the docker github I get the following error:
```
go build -o build/tsh -i  -ldflags '-w -s' ./tool/tsh
# github.com/gravitational/teleport/lib/client
lib/client/api.go:1241: undefined: terminal.GetState
lib/client/api.go:1253: undefined: terminal.Restore
Makefile:36: recipe for target 'build/tsh' failed
make: *** [build/tsh] Error 2
```

```
# go version
go version go1.7.4 solaris/amd64
```
Any thoughts on how I can fix this? Would love to run teleport on solaris servers.

**Comment by kontsevoy** [comment]
@logic855 unfortunately we do not have the resources to support anything other than Linux/OSX/BSD at the moment. The issue (seems to be) is that one of the OSS Golang libraries we're using in Teleport does not support Solaris. 

If someone with a SmartOS box can suggest a patch, we'll happily take it. Thanks.

**Comment by russjones** [comment]
@logic855 Are you still using SmartOS? It looks like support for SmartOS/Solaris may have been added to github.com/docker/docker/pkg since this ticket was created so this may not longer be an issue.

We're going to close this ticket for now, if you are still running into issues, can you create another ticket or a PR with the fix and we'd be happy to look at it.
