### ISSUE TITLE
WebUI should use server-side APIs for pagination, search, and filtering the data.

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#9399]
Teleport Web API needs to support pagination, filtering, and search for the following resource endpoints: ListNodes, ListApps, ListKubes, and ListDesktopAccess. 

This is required by WebUI to finally stop doing client side pagination which causes severe performance issues.  https://github.com/gravitational/teleport/issues/8147

The checklist required to complete this task:
- [x] Write a short RFD with proposed backend changes.
- [x] Implement backend changes (WebAPI)
- [x] Address backend changes on the client side

Some notes:
1. Teleport Auth/Proxy services already support pagination for above resources which are stored in the distributed memory cache. 
2. We would need to introduce `Query` and `Filter` abstractions. Check if `Filter` can be of different kinds where `Label` is one of them.

**Comment by zmb3** [comment]
@kimlisa @rudream I think we're good to close this one, right?
