### ISSUE TITLE
tsh wrongly complaining about self-signed certificate

### ISSUE THREAD

**Issue by eburghar** [gravitational/teleport#940]
I have installed a valid letsencrypt certificate to use with teleport, removed the `/var/lib/teleport/webproxy_*` files (just to be sure), and updated `teleport.yaml` to point to the cert and key location.

When pointing the web browser to port `https://cluster.domain.com:3080`, it's all green and the browser sees the letsencrypt certificate, but when I try to `tsh --proxy=cluster.domain.com login`, i received the message 

```
WARNING:
 The proxy you are connecting to uses the self-signed HTTPS certificate.
 Try --insecure flag if you know what you're doing.
```

`tsh` doesn't complain when using the exact same certificate through a reverse proxied teleport with nginx on port `443`.

**Comment by nikatjef** [comment]
You need to add letsencrypt's root CA to your CA Certificates directory, which varies based on distribution. Your browser is working because it uses a different set of CA certificates. See Issue #692

As for the next part of your issue with the reverse proxy, I suspect that you are connecting with a different "destination" name when you use the reverse proxy. The hostname of cluster.domain.com is not the same hostname as localhost.

**Comment by eburghar** [comment]
Thanks for your answer,

I checked on a browser just to be sure that `teleport` was also using the letsencrypt certificate and not the self-signed one as `tsh` was complaining about.

To summarize:
 - `https://cluster.domain.com:3080` and `https://cluster.domain.com` are both using the letsencrypt certificate
- `tsh https://cluster.domain.com:443 login` works flawlessly (meaning that the letsencrypt authority is trusted system wide)
- `tsh https://cluster.domain.com login` return the message about self-signed certificate

At least i think that the error message needs to be changed. It looks like (didn't check the code) `tsh` complaining about self-signed certificate even if it is another issue.

**Comment by nikatjef** [comment]
Per the issue I linked previously, the error is basically saying that tsh cannot validate the cert.  It validates by comparing the cert signature to a list of CA's that it knows about.  That list of CA's is different between your web browser and your tsh / teleport / java / etc.

Not sure which distribution you are using, but I got past this issue (on Ubuntu) by following these steps;
'''sh
sudo mkdir /usr/share/ca-certificates/letsencrypt
sudo mv ca.crt /usr/share/ca-certificates/letsencrypt
sudo dpkg-reconfigure ca-certificates
'''

In the third step I added a check mark next to the letsencrypt CA.  Once it finished, tsh no longer complained about my certificates.

**Comment by eburghar** [comment]
Thanks for your help,

The letsencrypt X3 CA is correctly installed otherwise

`tsh https://cluster.domain.com:443 login`

would complain about a self-signed certificate too.

To be sure that the same certificate was used,  and instead of using a browser (which is confusing by seeing your answer), I can also do

`curl -v https://cluster.domain.com:3080` and 
`curl -v https://cluster.domain.com`

Which both return the exact same valid letsencrypt certificate.

In any case, the certificate is not self-signed and the error message is wrong and confusing.

**Comment by darshandzend** [comment]
@eburghar I recently ran into this. The solution was to put `fullchain.pem` instead of `cert.pem` for `https_cert_file` in proxy configuration yaml. 

    https_cert_file: /etc/letsencrypt/live/ci.hotelsoft.com/fullchain.pem

**Comment by kontsevoy** [comment]
@darshandzend and @nikatjef are correct, thanks for answering guys.
