### ISSUE TITLE
Does not work on vmware ESXi machines

### ISSUE THREAD

**Issue by weikinhuang** [gravitational/teleport#942]
teleport does not start up on the esxi service console.

**Expected:**
When trying to run `./teleport start --help`, it should print the message. 

**Actual:**
I get a `Segmentation fault`.

**Comment by ekristen** [comment]
@weikinhuang can you provide more information about the operating system you are using?

**Comment by weikinhuang** [comment]
@ekristen I'm trying to run teleport on Vmware ESXi 6.5.0

**Comment by ekristen** [comment]
@weikinhuang oh you mean directly on VMWare ESXi ... gotcha, sorry about that, I read that differently.

**Comment by weikinhuang** [comment]
Yes directly on esxi

**Comment by tidalf** [comment]
usually esxi needs statically linked binaries.

**Comment by klizhentas** [comment]
we don't support these builds right now, feel free to send a PR if you feel like debugging/fixing it
