### ISSUE TITLE
[v.8.0] /docs/pages/installation.mdx

### ISSUE THREAD

**Issue by jonaskello** [gravitational/teleport#9438]
## Details
Describe the documentation improvements you wish to see.

Powershell instructions are missing command for unpacking the zip.
It says move `tsh` to your path but there is no `tsh` until you unpack it.

This command could be added after downloading and checking the zip

```powershell
Expand-Archive -LiteralPath teleport-v8.0.5-windows-amd64-bin.zip tsh
```

### Category
- Improve Existing

**Comment by ptgott** [comment]
We added these instructions in a229817bd0
