### ISSUE TITLE
Built-in letsencrypt support

### ISSUE THREAD

**Issue by philhug** [gravitational/teleport#944]
It would be great if teleport could install and renew a letsencrypt certificate automatically.
E.g. similar to how caddy does it:
https://github.com/mholt/caddy
or
https://github.com/alash3al/httpsify

**Comment by Oneiroi** [comment]
I would love this feature, so adding my vote and comment to this issue.

**Comment by kontsevoy** [comment]
For those who are watching this ticket:
https://gravitational.com/blog/letsencrypt-teleport-ssh/

We don't believe that adding vendor-specific code to a security product like an SSH server is generally a good idea. Occasionally we'll make exceptions (like Github auth support) but Let's encrypt is just too easy to get working using `certbot`, so I wrote a simple tutorial for it.

**Comment by eegilbert** [comment]
Hi Ev, thanks for the guide. I would caution against running the refresh of the Let's Encrypt cert every other day. There are rate limits in place as described [here](https://letsencrypt.org/docs/rate-limits/).

**Comment by kontsevoy** [comment]
@eegilbert thanks, I updated the guide.

**Comment by zedtux** [comment]
The problem with this guide is that on renewal, the teleport service is not restarted and therefore continues to serve the old certificate.
