### ISSUE TITLE
Create a separate RPM repository for CentOS 7

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#9448]
### What
As of Teleport 8, the RPM repository (https://rpm.releases.teleport.dev/) as detailed in the installation guide (https://goteleport.com/docs/installation/) does not provide RPMs which are compatible with CentOS 7. This means that if a CentOS 7 user was on a previous version of Teleport and they run `yum update`, their Teleport installation will be broken due to the required glibc version in Teleport 8 being too high for CentOS 7 machines.

This glibc issue is being tracked in https://github.com/gravitational/teleport/issues/9247 which will address the issue of broken upgrades. However, Teleport should also provide a repository suitable for CentOS 7 which provides Teleport 8 binaries compiled against a lower glibc version. These CentOS 7 binaries are currently available to the public (such as https://get.gravitational.com/teleport-v8.0.6-linux-amd64-centos7-bin.tar.gz) but there is no RPM or repository available at present.

### How
Add a separate RPM repository for CentOS 7. This could potentially be done using the `$releasever` variable on the current repo, or we could add a separate `rpm-centos7.releases.teleport.dev` repo.

### Why
CentOS 7 is not end of life until June 2024 and many customers are still using it.

### Workaround
Current workaround is to uninstall the Teleport RPM (either manually or using yum/dnf) and then manually install the binary tarball distribution from the URL above.

Related issues:
#9028 
#9247 

gz#3949

**Comment by amalikn** [comment]
+1

**Comment by evrynet1** [comment]
+1

**Comment by Stanislasss** [comment]
+1

**Comment by Stanislasss** [comment]
+1

**Comment by webvictim** [comment]
As an FYI to everyone +1ing this post, since Teleport 8.0.7 the Teleport RPM repo now distributes RPMs which are built on CentOS 7 and will work with that distro.

**Comment by webvictim** [comment]
@russjones Can you comment on this? I believe we only override the RPMs to the CentOS 7 ones when publishing to the repo, and don't do it yet for those published to the dashboard?

**Comment by russjones** [comment]
Correct. The CentOS 7 RPMs are in our repo and no longer rely on libatomic. However, we have not published to our dashboard yet.

**Comment by r0mant** [comment]
Starting from Teleport 10 all our artifacts are built on CentOS 7 so RPMs should be compatible also. Closing this.
