### ISSUE TITLE
Tsh does not respect /etc/environment

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#945]
This file should be read upon login and environment variables from it should be set.

**Comment by russjones** [comment]
Upon further investigation, it looks like reading `/etc/environment` is typically done with a PAM module `pam_env.so`. In OpenSSH: https://github.com/openssh/openssh-portable/blob/master/session.c#L1129-L1145

Since we won't be supporting PAM at the moment, I'm gonna close this for now.
