### ISSUE TITLE
Teleport nodes failed to reconnect on restart of auth.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#9474]
Customer reported they upgraded auth then proxy from 6.2.12 to 7.3.7.

At this point, nodes lost connection and failed to reconnect. Upgrading nodes to 7.3.7 resolved the issue.

Action items:

Try and reproduce with versions above. If we can reproduce, verify that it is no longer an issue in 7.x and 8.x releases. If it still is an issue, fix.

**Comment by fspmarshall** [comment]
Outdated.  Tests with older clients have been done since then and haven't encountered this issue.  Likely resolved.
