### ISSUE TITLE
ETCD based HA deployment sessions issue

### ISSUE THREAD

**Issue by jiangytcn** [gravitational/teleport#948]
### Deployment
1. 3 nodes ETCD cluster
2. 2 nodes teleport cluster
3. Ubuntu 14.04 vm under OpenStack

every teleport node configure auth、proxy、node jobs and followed [guide](http://gravitational.com/teleport/docs/2.0/admin-guide/#high-availability)
and all nodes behind a loadbalancer for the webgui(port 3080)

### Issues

couldn't display the sessions page. **_unable to retrieve list of sessions_**. 
and the sessions only in one node within  **data_dir**

after remove the node which the **data_dir** is empty from the LB, the page works well.

Is that means i need to have a shared storage server for the **data_dir** ? or am i misconfigured the settings?
Is it workable with following architecture? ![Is it workable with following architecture](http://ooqupn61c.bkt.clouddn.com/teleport-ha-arch.png)

**Comment by jiangytcn** [comment]
@kontsevoy could you help on this :) Thank you

**Comment by klizhentas** [comment]
@jiangytcn in OSS teleport sessions are stored on disk, so you have to use distributed storage to replicate them

**Comment by klizhentas** [comment]
you don't need to replicate the whole data dir, only the sessions in the data dir, as the other metadata is stored in etcd and is node local

**Comment by jiangytcn** [comment]
@klizhentas thank you.
 just as the diagram showed, i setup the cluster mode and make the sessions directory shared across whole proxy nodes. But unfortunately, the sessions api request occasionally response empty sessions. what is weird is that when ssh to one node, it could response the session just launched, but went to empty as i close the ssh connection(over webgui). 

PS: using nfs to replicate the sessions for temporary

**Comment by jiangytcn** [comment]
FYI config settings
> teleport:
  nodename: 192.168.2.6
  data_dir: /var/vcap/store/teleport
  pid_file: /var/vcap/sys/run/teleport_auth/app.pid
  auth_token: cluster-join-token
  advertise_ip: 192.168.2.6
  auth_servers:
  \- 192.168.2.6:3025
  \- 192.168.2.7:3025  
connection_limits:
    max_connections: 1000
    max_users: 250
  log:
    output: stderr
    severity: INFO
  storage:
     type: etcd
     peers: ["http://192.168.2.251:4001", "http://192.168.2.252:4001", "http://192.168.2.253:4001"]
     prefix: workbench.secrets
     insecure: true
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  tokens:
  \- proxy,node:cluster-join-token
  oidc_connectors: []
ssh_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3022
  labels:
    workbench_role: auth
  commands:
  \- name: hostname
    command: [/bin/hostname]
    period: 1m0s
  \- name: arch
    command: [/bin/uname, -p]
    period: 1h0m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: 0.0.0.0:3080
  tunnel_listen_addr: 0.0.0.0:3024
  https_key_file: /var/vcap/jobs/teleport_auth/config/webproxy.key
  https_cert_file: /var/vcap/jobs/teleport_auth/config/webproxy.crt

**Comment by jiangytcn** [comment]
As the auth/proxy server are stateless, why still checking the host_id?

Auth/proxy 1: 
> workbench_app/2853739a-7992-450d-b392-a2e0b6b35827:/var/vcap/store/teleport# cat host_uuid
9eaee59b-d594-4896-be58-6c6cd0bcea5d

log file
>level=warning msg="site '9eaee59b-d594-4896-be58-6c6cd0bcea5d' not found" file="web/apiserver.go:1606" func="web.(*Handler).WithClusterAuth.func1"
---
Auth/proxy 2:
> workbench_app/2853739a-7992-450d-b392-a2e0b6b35827:/var/vcap/store/teleport# cat host_uuid
9eaee59b-d594-4896-be58-6c6cd0bcea5d

log file
> level=warning msg="site '17b6e895-9477-4b15-96c9-958fde82592c' not found" file="web/apiserver.go:1606" func="web.(*Handler).WithClusterAuth.func1"

**Comment by kontsevoy** [comment]
@jiangytcn the current HA configuration does not automatically replicate the stored sessions, this is something you'd need to do yourself (i.e. make sure that /var/lib/teleport/log is syncronized across all nodes). We'll update the docs to reflect that.
