### ISSUE TITLE
Change default app directory

### ISSUE THREAD

**Issue by DUOLabs333** [gravitational/teleport#9488]
### What
By default, `teleport` uses `/var/lib/teleport` as its "main" directory. However, it should allow others to change it.

### How
Pass directories through flags.

### Why
I want some flexibility in set u.

### Workaround
If a workaround exists, please include it.

**Comment by klizhentas** [comment]
You can use data_dir to set the path in the config. See reference for details

https://goteleport.com/docs/setup/reference/config/#teleportyaml
