### ISSUE TITLE
Dynamic App Create/Delete event shows Unknown on Audit Log

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#9490]
### Description

**What happened**:

Unknown event on app create in audit log

![image](https://user-images.githubusercontent.com/60704961/146680518-8500fe73-c691-4c26-9c9e-df278ffff4d6.png)

**What you expected to happen**:

Log entry for dynamic app creation and deletion.  Assume this needs to be checked for other dynamic adds/deletes like DBs.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Follow directions to add a new app as here https://goteleport.com/docs/application-access/guides/dynamic-registration/
2. Check audit log after adding app

### Implementation

Example for similar database CRUD events: https://github.com/gravitational/webapps/pull/413

### Server Details
- Teleport version (run `teleport version`): 8.0.6
- Server OS (e.g. from `/etc/os-release`): amazon linux 2

**Comment by mdwn** [comment]
This has been addressed by https://github.com/gravitational/webapps/pull/1216 and backported to v8, v9, and v10.
