### ISSUE TITLE
Teleport cron build fails: 'gzip: invalid magic'

### ISSUE THREAD

**Issue by wadells** [gravitational/teleport#9494]
### Description

**What happened**:
The cron build that is supposed to regularly update our "floating" OCI images has been failing since 2021-12-03.  For instance, here's the one from today:

https://drone.teleport.dev/gravitational/teleport/9581

```
 ---> 68ded39973da
Step 9/15 : RUN mkdir -p build &&     curl -Ls https://get.gravitational.com/${DOWNLOAD_TYPE}-${VERSION_TAG}-${OS}-${ARCH}${EXTRA_DOWNLOAD_ARGS}-bin.tar.gz | tar -xzf - &&     cp $DOWNLOAD_TYPE/teleport $DOWNLOAD_TYPE/tctl $DOWNLOAD_TYPE/tsh build
 ---> Running in fc20d99f2f09
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c mkdir -p build &&     curl -Ls https://get.gravitational.com/${DOWNLOAD_TYPE}-${VERSION_TAG}-${OS}-${ARCH}${EXTRA_DOWNLOAD_ARGS}-bin.tar.gz | tar -xzf - &&     cp $DOWNLOAD_TYPE/teleport $DOWNLOAD_TYPE/tctl $DOWNLOAD_TYPE/tsh build' returned a non-zero code: 2
```

This has been going on since roughly the top of December.  The last successful cron build I see is :

https://drone.teleport.dev/gravitational/teleport/8715

And the first failure:

https://drone.teleport.dev/gravitational/teleport/8796

**What you expected to happen**:

I expect:

1) these builds to run to completion
2) someone to look into failures if they don't
or
3) we retire the functionality and update [our documentation about automatically updated images](https://github.com/gravitational/teleport/blob/d012a0b6d96cffd05e368dabab3febe94bf020b2/docs/pages/includes/image.mdx)

### Reproduction Steps
Wait until the cron build kicks off tomorrow and it will repro.  Alternatively, add a trigger you control to:

https://github.com/gravitational/teleport/blob/d012a0b6d96cffd05e368dabab3febe94bf020b2/.drone.yml#L760-L769

And use that trigger to kick off and test.  Be careful, as this will push images, unless there are other hacks to prevent that.

**Comment by wadells** [comment]
cc: @russjones @tcsc @webvictim

**Comment by webvictim** [comment]
Looks like a bad download URL, or possibly that the Drone IP has been blocked from downloading. Well done for noticing, @wadells. I thought there was meant to be a Slack alert on this but I guess not (or it isn't working)

**Comment by wadells** [comment]
Seeing errattic updates in the quay.io logs.  Unfortunately, they don't give much additional context (e.g. what creds were used to push the update)

https://quay.io/repository/gravitational/teleport?tab=history

![image](https://user-images.githubusercontent.com/187314/153316434-7ae2f2d1-cf6b-49c3-9020-fb8bca74f28d.png)

**Comment by wadells** [comment]
I can cross reference the quay tag history to successful runs of the `teleport-docker-cron` job.  It looks like it was working intermittently in January, and https://drone.platform.teleport.sh/gravitational/teleport/10030 (Feb 1) is the last good build in drone -- which lines up with the above.

**Comment by wadells** [comment]
I'm able to repro from my workstation with the following:
```
docker build --target teleport --build-arg DOWNLOAD_TYPE=teleport --build-arg VERSION_TAG=8.8.8 --build-arg OS=linux --build-arg ARCH=amd64 -t foo -f build.assets/Dockerfile-cron build.assets/
```

**Comment by wadells** [comment]
Debugging build here:

https://drone.platform.teleport.sh/gravitational/teleport/10189/1/4

The url that fails is:

```https://get.gravitational.com/teleport-v7.3.13^{}-linux-amd64-bin.tar.gz```

particularly `^{}` looks like it may be related to signed git tags vs unsigned git tags.  Digging further.

**Comment by wadells** [comment]
> particularly ^{} looks like it may be related to signed git tags vs unsigned git tags. 

https://git-scm.com/docs/gitrevisions#Documentation/gitrevisions.txt-emltrevgtemegemv0998em

Its definately signed vs unsigned tags:

```
walt@work:~/git/teleport$ git ls-remote --tags https://github.com/gravitational/teleport | grep v8 | grep -Ev '(alpha|beta|rc|dev)' | cut -d/ -f3 | sort -nr
v8.2.0
v8.1.5^{}
v8.1.5
v8.1.4^{}
v8.1.4
v8.1.3^{}
v8.1.3
v8.1.2
v8.1.1
v8.1.0^{}
v8.1.0
v8.0.7
v8.0.6
v8.0.5^{}
v8.0.5
v8.0.4^{}
v8.0.4
v8.0.1^{}
v8.0.1
v8.0.0
walt@work:~/git/teleport$ git show -q v8.2.0
commit bfd1780d2ea1908fef86ec63099e97107ba951c1 (tag: v8.2.0)
Author: Russell Jones <rjones@gravitational.com>
Date:   Wed Feb 9 01:07:00 2022 +0000

    Release 8.2.0.
walt@work:~/git/teleport$ git show -q v8.1.5
tag v8.1.5
Tagger: Roman Tkachenko <roman@goteleport.com>
Date:   Mon Feb 7 11:53:24 2022 -0800

Release 8.1.5.

commit c71e00771b7ad51f5de7d6a8ea45640be841f6de (tag: v8.1.5)
Author: Russell Jones <russjones@users.noreply.github.com>
Date:   Mon Feb 7 11:46:57 2022 -0800

    Release 8.1.5 (#10194)
```

This stems from:  https://github.com/gravitational/teleport/blob/df68e738641bbc73a42bec5af30084280d0c4292/.drone.yml#L791

Basically, when @russjones ran the releases, the tags were unsigned and worked fine with the existing automation.  When @r0mant ran releases, the tags were signed, and would cause this job to fail.

**Comment by wadells** [comment]
Two possible fixes: 

1) put a quick shell hack in that strips the `^{}` suffix.  Ugly but easy to develop.  I've got this ready now.
2) develop a go script like [version-check](https://github.com/gravitational/teleport/tree/df68e738641bbc73a42bec5af30084280d0c4292/build.assets/version-check) to scrape the GitHub releases api and determine the most recent release within each branch.  A bit more R&D (still reasonable for today), but probably more future proof.

Preferences @russjones?

**Comment by wadells** [comment]
I have a draft branch of option 2 here: https://github.com/gravitational/teleport/tree/walt/drone-docker-test

Unfortunately I was running into fiddlyness while wiring it up, and have to call it a night.  I'll check in tomorrow.
