### ISSUE TITLE
Web UI Terminal disconnects after short period of time in IE11 

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#952]
It was observed that terminal web-socket connections break in IE11 .

**Comment by kontsevoy** [comment]
Tested today, this does not happen anymore. This could be due to @russjones implementing keep-alive messaging and the new web UI now uses the same client `tsh` does.

**Comment by kontsevoy** [comment]
BTW, Edge also works great. All 4 major browsers on Windows work really well: IE11, Edge, Firefox and Chrome.
