### ISSUE TITLE
Add TOTP code to user signup/password reset

### ISSUE THREAD

**Issue by modem7** [gravitational/teleport#9520]
### What
During user signup/password reset, the TOTP code is only available as a QR code. 

![image](https://user-images.githubusercontent.com/4349962/146978925-0f9faac5-5465-4b8e-933b-a3b86bf42736.png)
(this has since been regenerated for obvious reasons).

### How
List TOTP authenticator key under QR code for scenarios where cameras are not available + a link to regenerate the QR code + key.

### Why
Some corporate policies do not allow the use of a camera, so a written code would be very useful.

**Comment by zmb3** [comment]
Duplicate of #3472
