### ISSUE TITLE
Deprecate teleport-daemonset

### ISSUE THREAD

**Issue by nitrocode** [gravitational/teleport#9553]
### Description

Please add a note to deprecate the daemonset chart with an appropriate alternative.

## references

* https://github.com/gravitational/teleport/pull/5233

**Comment by pkprzekwas** [comment]
@nitrocode is there a reason why this code has been deprecated? I'm trying to find an easy way to connect all of k8s nodes to my teleport cluster.

**Comment by nitrocode** [comment]
@pkprzekwas 

I believe @gravitational deprecated it due to security issues and this chart is leftover for some reason. I spoke to them about it on a call and said it was confusing because it's not explicitly stated that it's deprecated. Their new architecture no longer requires the daemonset.

**Comment by pkprzekwas** [comment]
@nitrocode 
 
thanks for the update! Do you know where I can find some information regarding the new architecture you've mentioned? It's still not clear to me how to connect Kubernetes workers to the teleport cluster. At this point I'm exploring two scenarios:
- teleport cluster hosted on the same Kubernetes cluster
- external teleport cluster

**Comment by nitrocode** [comment]
@pkprzekwas 

I cannot find a link for this new architecture. Their guides show that teleport must be installed on the instance with a join token in order to join the cluster.

https://goteleport.com/docs/setup/guides/joining-nodes-aws-iam/

**Comment by pkprzekwas** [comment]
@nitrocode 

Sorry, but I don't see how this [document](https://goteleport.com/docs/setup/guides/joining-nodes-aws-iam/) helps in my case - I'm not using IAM or even running my machines on AWS. Can you explain what you meant?

**I'm looking for easiest possible solution to configure teleport's `ssh_service` on all nodes of a Kubernetes cluster.**

I was able achieve my goal with custom solution based on the `deamonset` example, but the fact that it's been deprecated concerns me.

**Comment by nitrocode** [comment]
Sorry @pkprzekwas I cannot help but perhaps some others might.

cc: @ptgott @r0mant @zmb3 in case you folks can share some insight. It would help if some docs can be added to show that the daemonset is deprecated and some alternatives that could be considered.

**Comment by pkprzekwas** [comment]
@ptgott @r0mant @zmb3 do you have any updates regarding alternatives for configuring ssh on underlying kubernetes cluster nodes?

**Comment by ptgott** [comment]
Hi @pkprzekwas, you'll get much faster responses if you ask in our [discussion forum](https://github.com/gravitational/teleport/discussions/) or in [Slack](https://goteleport.com/slack/).

The best solution for you will depend on your infrastructure. If your organization is managing the underlying nodes, you might consider, for example:

- Running a `teleport` daemon directly on each node (https://goteleport.com/docs/server-access/getting-started/), i.e., not managed by Kubernetes (this would also enable you to access your nodes in case there's an incident involving Kubernetes, e.g., it can't schedule the `teleport` pod for whatever reason)
- Configuring existing OpenSSH servers on the nodes to trust Teleport's CA (https://goteleport.com/docs/server-access/guides/openssh/)

Again, though, I would ask in the discussion forums/Slack for detailed responses.

@zmb3 Do you know if it's still possible to install the daemonset chart? Can we close this?

**Comment by wadells** [comment]
The `teleport` chart has been deleted from helm.releases.teleport.dev
