### ISSUE TITLE
Webui SSH doesn't allow writing characters that require alt key

### ISSUE THREAD

**Issue by tjlaxs** [gravitational/teleport#958]
I don't know if this is just a mac problem. But when I try to write for example the $ sign with alt+4 the prompt changes to ```(arg: 4)``` which is what happens with Escape 4 also. So maybe its thinking its the wrong mod key or something? I have a finnish keyboard layout and a macintosh keyboard so, it might be an issue with these also.

**Comment by nikatjef** [comment]
I believe that is a terminal session issue rather than Teleport.  I say that because I get the same thing at my local console with a basic US qwerty keyboard on my Linux desktop.

But just for sanity sake, I decided to tsh to my home cluster and got the same thing.

**Comment by klizhentas** [comment]
ok, closing based on @nikatjef research
