### ISSUE TITLE
[v.9.0] /docs/pages/setup/admin/trustedclusters.mdx

### ISSUE THREAD

**Issue by Qdigital** [gravitational/teleport#9585]
## Details
Describe the documentation improvements you wish to see.

### Category

- New Feature
- Improve Existing
- Remove Outdated

**Comment by ptgott** [comment]
Hi @Qdigital, would you mind doing one of the following?
- Describe the changes you would like to see in this page
- Describe the issues you are having with this page
- Close the issue

Thanks!
