### ISSUE TITLE
Ensure self-hosted Teleport instructions include "IoT mode" instructions

### ISSUE THREAD

**Issue by JanoschDeurer** [gravitational/teleport#9588]
## Details
We want to run our auth server behind a NAT, whilst the proxy is running publicly. In the documentation of the config we found the following documentation (https://goteleport.com/docs/setup/reference/config/): 

```yaml
    # Reverse tunnel listening address. An auth server (CA) can establish an
    # outbound (from behind the firewall) connection to this address.
    # This will allow users of the outside CA to connect to behind-the-firewall
    # nodes.
    #
    # If not set, behavior depends on the config file version:
    #
    # "v2": listener is not created, reverse tunnel traffic is multiplexed on web_listen_addr
    # "v1": defaults to 0.0.0.0:3024
    tunnel_listen_addr: 0.0.0.0:3024
```
This indicates that it is possible to run the proxy as we intend to. However, it is unclear to us how to do so. The rest of the documentation reads as if it is only possible to connect from the proxy to the auth server, not vice versa. So if there is a way to connect the auth server to the proxy from behind a NAT it would be great to have some documentation for it.

If you give me a hint on how it is intended to be used and we get it running, I can offer to write some documentation for it.

### Category

- Improve Existing

**Comment by ptgott** [comment]
We've done a lot of work on updating our docs guides to suit a Teleport Cloud use case, where the Auth Service runs in a private network while the Proxy Service is exposed to the internet. 

We should still:
- see if there are any how-to guides where the assumption is that resources in self-hosted clusters connect to the Auth Service directly 
- include alternative instructions in those guides for connecting to the Auth Service through the Proxy Service

In the past, we have called this architecture "IoT mode", but this isn't really a term we use anymore in the documentation.

**Comment by ptgott** [comment]
I'm going to fold this one into #21305, which we are now actively working on this quarter. Joining in "IoT Mode" will now be the default within the docs.
