### ISSUE TITLE
Forced "dual/multi-key" sessions?

### ISSUE THREAD

**Issue by copumpkin** [gravitational/teleport#959]
I don't mean MFA here, but rather getting two (or possibly more) separate users to share a session before allowing either of them to proceed.

The idea would be similar to those dual-key nuclear launch systems, where it takes two different users with separate keys (cryptographic in our case) to do scary stuff.

I see that teleport already supports session sharing, so this would boil down to "forced session sharing". One of the users would actually be running commands on the remote machine, but would be unable to proceed without a live observer session.

Is this something that's possible today via configuration, or would it need new feature work?

**Comment by kontsevoy** [comment]
@copumpkin thanks for the suggestion. there's been very loud headscratching here in Gravitational HQ :)

we do not see how would you make it work in the SSH world. Teleport is not a closed system, it is 100% compatible with OpenSSH, which means you may be hitting an OpenSSH server (running `sshd`) or a user may join using OpenSSH `ssh` client. The way session sharing is done today is via a simple terminal multiplexing (same as you'd DIY with `screen`, for example) so this feature has nothing to do with security and we doubt this can be bolted on...
