### ISSUE TITLE
interactive database session idle timeout

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#9592]
### What

A teleport administrator should be able to set an idle timeout for an interactive database session.

If a user connects and there is an idle timeout value of _t_, they must issue a command before that time is met. If a long running query takes longer than _t_, it should not disconnect because the active query should not count as "idle" time on the part of the user since they are waiting for work to be done.

### How

The default behavior should remain the same and effectively have no idle timeout value. This can be represented as a 0. It should be configurable in the RBAC system. An optional default idle timeout for an entire database in the `db_service.databases` entry in the config file could work as well, since the timeout value may be different by either user/group or database.

### Why

Internal company security policy dictates a maximum idle time for an interactive database shell. This type of requirement is consistent with NIST 800-53r5 maximum idle session time requirements

### Workaround

None so far.

**Comment by xinding33** [comment]
@programmerq is the general use case around configurable idle timeout at the 1) user level, 2) resource level, or 3) both? Also, can you point me to the specific control in NIST 800-53r5 referencing maximum idle session time requirements? The one I'm aware of is control AC-12 (screenshot below). I just want to make sure we're talking about the same thing. Thanks!

![image](https://user-images.githubusercontent.com/24904723/147973424-83d72a22-8bea-45cb-bee5-026b4c2a9feb.png)

**Comment by r0mant** [comment]
@programmerq FYI database connections should respect the role's `client_idle_timeout` option (cc @smallinsky - I think we added it when adding disconnect_expired_cert as well, correct?)

**Comment by smallinsky** [comment]
Yes, That is correct. Database connection already respects global `client_idle_timeout` network config setting and per role `role_option.client_idle_timeout` flag.

**Comment by programmerq** [comment]
I'm closing this out since `client_idle_timeout` and `role_options.client_idle_timeout` will do the trick.
