### ISSUE TITLE
Teleport-DocTest fails to catch certain errors

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#9600]
It appears as though the `remark` check in our `Teleport-DocTest` is misconfigured somehow. I mistakenly added a comment to `teleport/docs/pages/desktop-access/reference.mdx` in the HTML form below which ultimately broke the docs build.

```mdx
<!--  NOTE to devs: If you update this reference yaml, you likely want to mirror the changes in docs/pages/setup/reference/config.mdx -->
```

I think what's happening is that the quay.io image being used for that test isn't using the [`.remark.js`](https://github.com/gravitational/next/blob/main/.remarkrc.js) we have in the `next` repository. I tested this by copying `teleport/docs/*` (which still had the breaking html comment) into `next/content/9.0/docs/` and then running `yarn markdown-lint`, which surfaced the error

```
content/9.0/docs/pages/desktop-access/reference.mdx
           1:1  error    21:2: Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
```

However if I remove `next/.remarkrc.js` and run the same `yarn markdown-lint`, the error disappears.

**Comment by zmb3** [comment]
@tcsc is this one fixed now or is there still work to do?

**Comment by ptgott** [comment]
Closed as completed
