### ISSUE TITLE
[v.8.0] /docs/pages/installation.mdx - Update repository installation steps

### ISSUE THREAD

**Issue by KyleRAnderson** [gravitational/teleport#9611]
## Details
I would like to see updated instructions for adding the Teleport repository which do not use the deprecated and insecure `apt-key` program. `apt-key` has been deprecated as of Ubuntu 20.10 and onward (see [Ubuntu 21.04 manpage](http://manpages.ubuntu.com/manpages/hirsute/man8/apt-key.8.html)) and is no longer going to be available by default after Debian 11 and Ubuntu 22.04. 

The Debian wiki documents the current recommended way for adding such repositories: https://wiki.debian.org/DebianRepository/UseThirdParty#Sources.list_entry.

### Category
- Improve Existing
- Remove Outdated

**Comment by ptgott** [comment]
`apt-key` is also used in:
- docs/pages/getting-started/linux-server.mdx
- docs/pages/server-access/getting-started.mdx
