### ISSUE TITLE
helm: document bring your own TLS certs

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#9627]
Our Helm chart should be able to utilize pre-existing public ACM certs as an alternative to cert-manager. 

This AWS guide is a good example of how this could be done: https://aws.amazon.com/premiumsupport/knowledge-center/terminate-https-traffic-eks-acm/

**Comment by xinding33** [comment]
As discussed during the 1/4 product + CS sync, this should already be supported and we just need to add docs.

@ptgott fyi.

**Comment by zmb3** [comment]
Can we close this, or do we have specific helm docs that need updating?

The option is documented in the chart itself: https://github.com/gravitational/teleport/blob/39ffa567669c01481fdaa3cfe3e5de827a4c3734/examples/chart/teleport-cluster/values.yaml#L172-L184

**Comment by ptgott** [comment]
These values fields are documented in the teleport-cluster chart reference now, so I think we can close this.
