### ISSUE TITLE
dependence discrepancy between yum-provided and dashboard-provided rpm and deb files

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#9636]
### Description

**What happened**:

When installing teleport via `https://get.gravitational.com/teleport-ent-8.0.7-1.x86_64.rpm`, it includes a teleport binary with the following linked libraries:

```
ldd teleport
	linux-vdso.so.1 =>  (0x00007ffff5bef000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f26d914e000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f26d8f32000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f26d8c30000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f26d8a1a000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f26d864c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f26d9352000)
```

When installing it via `yum-config-manager --add-repo https://rpm.releases.teleport.dev/teleport.repo && yum install teleport-ent`, it results in a different binary with the following dependencies:

```
ldd teleport
	linux-vdso.so.1 =>  (0x00007ffc908e3000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd8ab197000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd8aaf7b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fd8aac79000)
	libatomic.so.1 => not found
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd8aaa63000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd8aa695000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd8ab39b000)
```

Additionally, these RPMs have different checksums:

057d098092cb7cfe6cde60a6848b02b4  teleport-ent-8.0.7-1.x86_64.rpm
7324f00753455df9652c7245efe97f6a  teleport-ent-8.0.7-1-centos7.x86_64.rpm (from el7 centos yum repo)

https://rpm.releases.teleport.dev/8.0.7/teleport-ent-8.0.7-1-centos7.x86_64.rpm seems to be the URL that yum uses on both centos7 and amazon linux 2.

**What you expected to happen**:

If libatomic really does need to be installed, it should be listed as a dependency in the rpm manifest. Since not every build of teleport seems to include this (as seen by the output of ldd), I'm wondering if maybe it needs to be a compile time dependency rather than a dynamically linked runtime dependency.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. wget https://rpm.releases.teleport.dev/8.0.7/teleport-ent-8.0.7-1-centos7.x86_64.rpm
2. yum localinstall teleport-ent-8.0.7-1-centos7.x86_64.rpm
3. teleport version

### Server Details
- Teleport version (run `teleport version`): 8.0.7 enterprise
- Server OS (e.g. from `/etc/os-release`): centos 7, amazon linux 2, possibly others
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): n/a
- Additional details:

### Debug Logs

```
$teleport help
teleport: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

$ ldd /usr/local/bin/teleport
	linux-vdso.so.1 (0x00007ffce15eb000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff63cdaa000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff63cb8c000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff63c84c000)
	libatomic.so.1 => not found
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff63c636000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff63c28b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff63cfae000)

$ ldd /usr/local/bin/tctl
	linux-vdso.so.1 (0x00007ffe37da5000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f21248f9000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f21245b9000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f212439b000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f2124185000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2123dda000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2124afd000)

$ ldd /usr/local/bin/tsh
	linux-vdso.so.1 (0x00007fffc418c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2086182000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f2085f7e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2085bd3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f20863a0000)
```

**Comment by programmerq** [comment]
There was also a report of a .deb release having a similar libatomic dependency, but the `teleport-ent_8.0.7_amd64.deb` files that I was able to find don't seem to be affected.

**Comment by zmb3** [comment]
Closing this as the fixes are complete. `libatomic` will no longer be required as of Teleport 8.1 which is slated to be released in the next week or two.
