### ISSUE TITLE
Teleport Kubernetes Access doesn't work with GKE Autopilot Clusters

### ISSUE THREAD

**Issue by vijaynandwani** [gravitational/teleport#9642]
### Description

I tried to setup Teleport Kubernetes Access on 4 GKE Clusters:

1) Cluster A (GKE Standard) - 1.21.5-gke.1302 version
2) Cluster B (GKE Standard) - 1.19.14-gke.1900 version
3) Cluster C (GKE Autopilot Cluster) - 1.20.10-gke.1600 version
4) Cluster D (GKE Autopilot Cluster) - 1.21.5-gke.1302 version 

I tried doing it with the [Teleport Agent Method](https://goteleport.com/docs/kubernetes-access/getting-started/agent/) and [Standalone Teleport Method](https://goteleport.com/docs/kubernetes-access/guides/standalone-teleport/) using [get-kubeconfig.sh](https://github.com/gravitational/teleport/blob/master/examples/k8s-auth/get-kubeconfig.sh)

**What happened**:

I run `tsh kube ls` and then `tsh kube login <cluster-name>`
Then I run `kubectl get pods`

On Clusters A and B, I get list of pods or a response such as `No resources found in <X> namespace.`
On Clusters C and D, I get error message `error: the server doesn't have a resource type "pods"`

**What you expected to happen**:

The command `kubectl get pods` should work on all 4 clusters

### Reproduction Steps
1. Create a GKE Autopilot Cluster on Regular Channel
2. Run [get-kubeconfig.sh](https://github.com/gravitational/teleport/blob/master/examples/k8s-auth/get-kubeconfig.sh) script and add `kubeconfig` in your teleport server
3. Login into cluster using `tsh kube login <cluster-name>` and try to get the list of pods `kubectl get pods`

### Server Details
- Teleport version (run `teleport version`): Teleport v8.0.7 git:v8.0.7-0-geb8076446 go1.17.3
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Google Compute Engine
- Additional details:

### Client Details
- Tsh version (`tsh version`): Teleport v8.0.7 git: go1.17.5
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download): brew
- Additional details:

**Comment by martin-berwanger-maven** [comment]
I am also having an issue getting Teleport to work on an Autopilot cluster, it seems related to:
Error from server (Forbidden): users "XXXXX@XXXXX.XXX" is forbidden: User "system:serviceaccount:XXXXXX:teleport-kube-agent" cannot impersonate resource "users" in API group "" at the cluster scope: GKEAutopilot authz: user impersonation is not allowed

**Comment by colinedwardwood** [comment]
Teleport can work with Autopilot clusters. See the discussion here: https://github.com/gravitational/teleport/discussions/11959

**Comment by tigrato** [comment]
This is no longer a limitation of GKE autopilot distributed via the Release channel.
Teleport should work out of the box if users are not impersonating the `system:masters` group. For those who receive an error message similar to

```
groups "system:masters" is forbidden: User "system:serviceaccount:teleport:teleport-agent" cannot impersonate resource "groups" in API group "" at the cluster scope: GKE Warden authz [denied by user-impersonation-limitation]: impersonating system identities are not allowed
```

This is a limitation of GKE and you need to create a custom Kubernetes group mapped to Kubernetes ClusterRole `cluster-admin`

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: admin
```

Once you create the ClusterRoleBinding, configure your Teleport user to impersonate `admin` instead of `system:masters`
