### ISSUE TITLE
Terraform provider doc contains incorrect label definition parameters

### ISSUE THREAD

**Issue by nickbrennan1** [gravitational/teleport#9652]
The Terraform Provider documentation [here](https://goteleport.com/docs/setup/reference/terraform-provider/#teleport_role) states for parameters for label definition that `names` and `values` should be used with the provider for the following `allow`/ `deny` definitions:

- node_labels
- app_labels
- cluster_labels 
-  db_labels

However, this is incorrect. The actual definitions should use `key` in place of `name` and `value` rather than `values` as in the example file [here](https://github.com/gravitational/teleport/blob/master/examples/resources/terraform/terraform-user-role.tf#L54).

**Comment by ptgott** [comment]
It looks like this is now a map of string arrays (see: https://goteleport.com/docs/reference/terraform-provider/), so I think we can close this issue. Please feel free to reopen if the issue still exists.
