### ISSUE TITLE
Add GLIBC >= 2.18 into [v.8.0] /docs/pages/getting-started/linux-server.mdx

### ISSUE THREAD

**Issue by guidorugo** [gravitational/teleport#9672]
## Details
Fresh install in CentOS7 with glibc 2.17.

`
$ curl -O https://get.gravitational.com/teleport-v8.0.7-linux-amd64-bin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 59.9M  100 59.9M    0     0  1140k      0  0:00:53  0:00:53 --:--:--  535k
$ tar -xzf teleport-v8.0.7-linux-amd64-bin.tar.gz
$ cd teleport
$ ls
CHANGELOG.md  examples  install  README.md  tctl  teleport  tsh  VERSION
$ sudo ./install
Teleport binaries have been copied to /usr/local/bin

Thanks for installing Teleport.

Is it OK if we collect some info about your install?
Please run this command to send in a survey.
Optional: Replace email to join our newsletter and get a swag package.
$ curl -X POST https://usage.teleport.dev -F OS=linux -F use-case="access my ..." -F email="alice@example.com"

Otherwise, ignore!
$ teleport --help
teleport: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by teleport)
teleport: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by teleport)
$ sudo teleport --help
teleport: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by teleport)
teleport: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by teleport)
$ uname -a
Linux localhost.localdomain 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`

### Category
- Improve Existing

## Notes
Afaik CentOS 7 glibc package latest version is 2.17-317.

**Comment by zmb3** [comment]
FYI: There's a separate download at https://get.gravitational.com/teleport-v8.0.7-linux-amd64-centos7-bin.tar.gz that was compiled on CentOS 7 which will work with older versions of GLIBC.

**Comment by zmb3** [comment]
@guidorugo I'm going to close this, but feel free to let us know if the CentOS 7 build doesn't work for you. Happy to take another look if necessary.

**Comment by alwaysastudent** [comment]
@zmb3 this issue is occurring with debian as well. Is there an alternative version for this?

```
# uname -a
Linux xxxx-123 4.14.81.bm.24-amd64 #1 SMP Debian 4.14.81.bm.24 Tue Aug 11 01:43:51 UTC 2020 x86_64 GNU/Linux
```


```
 /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/bin/teleport)

```

**Comment by guidorugo** [comment]
> @guidorugo I'm going to close this, but feel free to let us know if the CentOS 7 build doesn't work for you. Happy to take another look if necessary.

It worked with Cent7 tar gz file. 

I also try it in ubuntu 16.04 and works great (with glibc 2.23)
