### ISSUE TITLE
Ability to choose Auth Connector button styling

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#9684]
### What
Currently the Teleport Auth Connector `spec.display` value controls whether the button styling is one of the built-in presets or a default OpenID styling. Customers would like to able to use the Microsoft/Azure styling with an alternate text label on the button to differentiate between multiple SAML applications in Azure. 

### How
Allow for button styling override if one specified, or else default to the current defaults.

### Why
Customer use case where they have multiple SAML applications in Azure and want to be able to differentiate among them visually.

**Comment by zmb3** [comment]
Going to close this one as a duplicate and track it over in #3896.
