### ISSUE TITLE
Support for u2f and otp simultaneously 

### ISSUE THREAD

**Issue by markojak** [gravitational/teleport#969]
Hi All,

Would it be possible to support both OTP and U2F as authentication mechanisms? We have some users who have U2F and some who would prefer use an Authenticator application on their phones.

Thoughts?
Happy to do a Fork and try to help with the implementation of this if someone can also point me in the right direction.

**Comment by francislavoie** [comment]
Definitely +1 for this. For example, Dropbox attempts U2F first by default, with a link to fallback to TOTP if the user chooses. Enforcing one or the other isn't the best scheme - U2F is easier if your device is already plugged in, but OTP can be easier if you don't.

**Comment by gclawes** [comment]
+1 for this, as well as being able to change U2F/OTP tokens from the web UI after account creation.

**Comment by dadicool** [comment]
+1 on this, I am not enabling U2F on our setup because I can't mandate everybody to have a key.

**Comment by aberoham** [comment]
+1 for a very similar request, support both at once. Via an end-user: "Is it possible to use a Yubikey to provide the Teleport user passsword at login, as well as the two factor authentication token?"

**Comment by gclawes** [comment]
Kinda defeats the point of 2-factor auth, having 2 separate sources of authentication secrets.

**Comment by mpitt** [comment]
+1, we cannot force all our users to switch to U2F, but we would still like to offer the option

**Comment by awly** [comment]
https://github.com/gravitational/teleport/issues/1929 is a superset of this request, closing this one.
We'll aim to get this fixed in 5.0 (in ~1-2 months from now).
