### ISSUE TITLE
Creating  Remote Users

### ISSUE THREAD

**Issue by whitepiratebaku** [gravitational/teleport#9692]
### What
Hi, it may be better if Teleport can create users on remote hosts. Like You are adding new user with some role, and teleport goes to nodes which role has access and addes new user there if not exists.

### Why
If admins needs to add user for too many machines these could be easier, yes configuration management tools also can be used but maybe you can think about a nice feature.

**Comment by zmb3** [comment]
This is supported today for desktops and SSH servers and support for creating database users is in progress.
