### ISSUE TITLE
Support resize during desktop sessions

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#9702]
The browser should listen for resize events and send updated client screen spec messages if the user changes the size of the window.

The windows desktop service should translate these to the appropriate RDP message and forward them to the target desktop.

**Comment by zmb3** [comment]
It sounds like this is supported with [RDP 8.1](https://techcommunity.microsoft.com/t5/security-compliance-and-identity/resolution-and-scaling-level-updates-in-rdp-8-1/ba-p/248077) and up (which happens to be WS 2012 R2 and newer, what we already support).

**Comment by zmb3** [comment]
Looks like this is done via https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/dfc234ce-481a-4674-9a5d-2a7bafb14432

**Comment by ThomasHoutrique** [comment]
Hello, any update on this feature ? (:
