### ISSUE TITLE
No way to edit users

### ISSUE THREAD

**Issue by kinghrothgar** [gravitational/teleport#971]
As far as I can tell, there is no way to edit users. This means that if user mappings need to be changed, the user must be deleted and re-added requiring them to re-setup their account.

**Comment by shaharmor** [comment]
Is this in the making?

**Comment by kinghrothgar** [comment]
I just realized this also includes changing user password I believe?

**Comment by unreality** [comment]
This seems like a fairly important feature, is it on the roadmap for next release?

**Comment by Orad** [comment]
crap. I've been searching for ages in the documentation.

**Comment by TheDeadCode** [comment]
+1. I haven't found a way to simply add a mapping to an existing user, and re-setup TOTP can be kind of a pain for people.

**Comment by kontsevoy** [comment]
2.3 (coming up in a couple of days) supports user editing via resources.

**Comment by kontsevoy** [comment]
password change has been moved to #1294
