### ISSUE TITLE
[v.8.0] /docs/pages/installation.mdx PowerShell echo environment variable command

### ISSUE THREAD

**Issue by KyleRAnderson** [gravitational/teleport#9714]
## Details
I'd like the command to echo an environment variable to be updated to function properly in PowerShell. The current command looks like it's for command prompt.

### Category

- Improve Existing

**Comment by ptgott** [comment]
I've [tested the installation instructions in PowerShell](https://github.com/gravitational/teleport/blame/bb59734edf0477a714ca28e43c25292b4df3d745/docs/pages/installation.mdx#L271) since this issue was opened, so I think we can close this.
