### ISSUE TITLE
[v.8.0] /docs/pages/setup/admin/trustedclusters.mdx

### ISSUE THREAD

**Issue by gsoneill** [gravitational/teleport#9717]
## Details
The documentation has some visual display issues. See https://goteleport.com/docs/setup/admin/trustedclusters/#dynamic-join-tokens where the example commands are overlapping with other text.

This issue is present in both Firefox and Chrome, tested from macOS.

![image](https://user-images.githubusercontent.com/1486960/148812954-a1fe3d80-683a-4f93-9d7e-f3ce0b985f33.png)

### Category
- Improve Existing

**Comment by zmb3** [comment]
See gravitational/next#751

**Comment by greedy52** [comment]
The bug is fixed now.
