### ISSUE TITLE
AWS Credential brokering fails with federated accounts

### ISSUE THREAD

**Issue by giles-betteromics** [gravitational/teleport#9727]
### Description

I have some kubernetes clusters running on amazon EKS for which I can't get the aws credential creation to work properly

The following patch adds logging to the system which corrects the problem per the AWS documentation at https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-custom-url.html which states "Note
Do not use the SessionDuration HTTP parameter if you got the temporary credentials with GetFederationToken. Doing so will cause the operation to fail."

Patch:
```
$ git diff origin/master
diff --git a/lib/srv/app/cloud.go b/lib/srv/app/cloud.go
index 4d3102a91..3a2bc80b5 100644
--- a/lib/srv/app/cloud.go
+++ b/lib/srv/app/cloud.go
@@ -18,14 +18,11 @@ package app

 import (
        "encoding/json"
-       "fmt"
        "io"
        "net/http"
        "net/url"
-       "time"

        "github.com/gravitational/teleport/lib/tlsca"
-
        "github.com/aws/aws-sdk-go/aws/arn"
        "github.com/aws/aws-sdk-go/aws/credentials/stscreds"
        awssession "github.com/aws/aws-sdk-go/aws/session"
@@ -150,16 +147,8 @@ func (c *cloud) GetAWSSigninURL(req AWSSigninRequest) (*AWSSigninResponse, error
                return nil, trace.Wrap(err)
        }

-       // Max AWS federation session duration is 12 hours. The federation endpoint
-       // will error out if we request more.
-       duration := req.Identity.Expires.Sub(c.cfg.Clock.Now())
-       if duration > maxSessionDuration {
-               duration = maxSessionDuration
-       }
-
        tokenURL.RawQuery = url.Values{
                "Action":          []string{"getSigninToken"},
-               "SessionDuration": []string{fmt.Sprintf("%d", int(duration.Seconds()))},
                "Session":         []string{string(sessionBytes)},
        }.Encode()

@@ -222,6 +211,4 @@ const (
        federationURL = "https://signin.aws.amazon.com/federation"
        // consoleURL is the default AWS console destination.
        consoleURL = "https://console.aws.amazon.com/ec2/v2/home"
-       // maxSessionDuration is the max federation session duration.
-       maxSessionDuration = 12 * time.Hour
 )
```

**What happened**:

Role fails to be correctly assumed:

```
$ tsh app login --aws-role TeleportReadOnly aws-betteromics
Logged into AWS app aws-betteromics. Example AWS cli command:

tsh aws s3 ls
$ tsh aws s3 ls

An error occurred (500) when calling the ListBuckets operation (reached max retries: 2): Internal Server Error
ERROR: exit status 254

$ tsh aws s3 ls
2021-10-13 15:15:26 betteromics-identity-tfstate
```

Agent log contains
```
2021-12-19T19:40:38Z WARN [APP:SERVI] Failed to serve request: non-200 response from AWS federation endpoint: "400 Bad Request" map[Content-Security-Policy:[default-src 'none' https://aws.amazon.com https://*.signin.aws.amazon.com https://signin.aws.amazon.com 'unsafe-inline'; img-src 'self' data: https://*.signin.aws.amazon.com https://signin.aws.amazon.com https://opfcaptcha-prod.s3.amazonaws.com https://images-na.ssl-images-amazon.com https://d1.awsstatic.com https://internal-cdn.amazon.com https://media.amazonwebservices.com https://d36cz9buwru1tt.cloudfront.net https://d0.awsstatic.com; media-src 'self' https://*.signin.aws.amazon.com https://signin.aws.amazon.com https://media.amazonwebservices.com...
```

**What you expected to happen**:

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create kubernetes cluster on amazon eks
2. Allow cluster service account to assume iam role
3. Delegate appropriate permissions to iam role

### Server Details
- Teleport version (run `teleport version`):
`Teleport v8.0.0-alpha.1 git:v8.0.0-alpha.1-331-gd012a0b6d go1.17.2`
- Server OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
AWS EKS cluster node
- Additional details:
Teleport agent is running on kubernetes cluster using a serviceAccount annotated as follows:

```
annotations:
  serviceAccount:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXX:role/TeleportCorpClusterRole
```
This aws account has an oidc delegated role with it to allow kubernetes to assume this role, and AWS has an iam policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "sts:AssumeRole",
                "sts:AssumeRoleWithWebIdentity"
            ],
            "Resource": "arn:aws:iam::XXX:role/TeleportReadOnly"
        }
    ]
}
```
and is delegated appropriate permissions

### Client Details
- Tsh version (`tsh version`):
`Teleport v8.0.1 git:v8.0.1-0-gb95fb530b go1.17.3`
- Computer OS (e.g. Linux, macOS, Windows):
macOs 12.1
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
website download
- Additional details:

### Debug Logs
See above (I actually instrumented the code to get more logging to figure out what was wrong; I've removed said logging from the patch - essentially I was logging the tokenURL generated by the code)

**Comment by r0mant** [comment]
@giles-betteromics Thank you for reporting this! Reading the ticket description, I'm a bit confused:

- Your patch updates the `GetAWSSigninURL` function that generates a URL for signing into AWS web console (used by Teleport web UI).
- The issue you mention is related to the AWS CLI access (`tsh aws`) which does not go through that code path.

So basically changes in `GetAWSSigninURL` should not affect AWS CLI access in any way, so I'm very curious as to why it seems to fix the issue for you.

Could you please confirm whether you're having issues with AWS CLI access (i.e. `tsh aws`) or AWS web console access through Teleport? Thanks!

**Comment by giles-betteromics** [comment]
This was aws cli access via tsh aws. The code path did seem to go through this... let me disable it and try again, I will update this ticket.

**Comment by giles-betteromics** [comment]
Ok, I restarted my server and I agree, that code path was not executed for the command line. So the log I was seeing was confusing and I had two problems at the time. The federated identity failure is absolutely to do with the web console access and not the command line - apologies.

However I now see many errors trying to access aws via the command line which don't correlate with the log messages. I suspect there are actually two problems - but please consider this bug report about web console access, not aws command line.

**Comment by r0mant** [comment]
Got it, thank you @giles-betteromics! This is what I suspected. We'll take a look at this with respect to the AWS console access and make a patch once confirmed.

**Comment by giles-betteromics** [comment]
Cheers! I'm guessing that what might be happening with my 500 error talking to `tsh aws s3 ls` is that there is some kind of cache on the teleport server side, and when I bounce the teleport-agent it takes a few minutes to notice that the old one has gone away? Restarting it seems to cause the errors, and when it is erroring I see no traffic to the teleport agent that I just restarted.

**Comment by r0mant** [comment]
@giles-betteromics If you're running it as a pod in Kubernetes (which it seems like you are), then you're likely running into https://github.com/gravitational/teleport/issues/9126. We have a PR out to fix it (https://github.com/gravitational/teleport/pull/9288) which should get merged in within the next few days, after that we'll backport to v8 and publish a patch release.

**Comment by giles-betteromics** [comment]
That sounds exactly like it - thanks!

**Comment by greedy52** [comment]
For the web console issue, I don't think the code is calling `GetFederationToken`. I think we are doing a `AssumeRole` through `stscreds.NewCredentials`.

In the same [aws doc](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-custom-url.html), it also mentions

> Additionally, if you use the AssumeRole* API operations, you must call them as an IAM user with long-term credentials. Otherwise, the call to the federation endpoint in step 3 fails.

I suspect using the IAM role through EKS service account is **NOT** `long-term`. Will update if I find out more or a solution.

**Comment by giles-betteromics** [comment]
Yeah I couldn't find GetFederationToken being called either when I turned on volumes of debugging, it was just a clue that made me grab the URL that is generated, and I accidentally found that removing the SessionDuration parameter made the get request work. If there are other ways to accomplish this on AWS's EKS I'm all ears, Im not wedded to the iam role approach - it just worked! I'm somewhat allergic to putting AWS keys into the process though because then we have to come up with a rotation strategy. That said if you look at the hashicorp vault solution for this I'm fine with that - where you can have vault rotate the key on its own on periodic intervals.

**Comment by greedy52** [comment]
@giles-betteromics thanks for the input! it's definitely a bug on our side. This probably breaking in other situations too. Will look into a solution. thanks!
