### ISSUE TITLE
Teleport trying to connect to old Auth server IP 

### ISSUE THREAD

**Issue by marchofreason** [gravitational/teleport#973]
Our Auth server was destroyed and we re-deployed a full Teleport Auth Server to a new VM.
Any new servers we add as nodes work 100% but any of our previous servers seem to be still trying to connect to the old IP address

This is regardless if we are using the IP address is the teleport.yaml or if we are using the DNS. We've checked DNS Cache and this is also not an issue as the OS level is seeing the new IP Address

**Top line shows the OLD IP address. This address is not anywhere in the .yaml file !**

May 08 11:08:39 teleport[23243]: dial tcp 159.8.177.211:3025: i/o timeout 
May 08 11:08:39 systemd[1]: teleport.service: Main process exited, code=exited, status=1/FAILURE
May 08 11:08:39 systemd[1]: teleport.service: Unit entered failed state.
May 08 11:08:39 systemd[1]: teleport.service: Failed with result 'exit-code'.
May 08 11:08:39 systemd[1]: teleport.service: Service hold-off time over, scheduling restart.
May 08 11:08:39 systemd[1]: Stopped Teleport SSH Service.
May 08 11:08:39 systemd[1]: Started Teleport SSH Service.

**Comment by a-palchikov** [comment]
I think you might have these IPs cached in `authservers.json` cache: https://github.com/gravitational/teleport/blob/master/docs/2.0/admin-guide.md#run-multiple-instances-of-teleport-proxy

**Comment by marchofreason** [comment]
This appears to be it. Thanks so much a-palchikov! 

I'm getting an unusual error now though if I remove the authservers.json 

May 09 18:59:31 server.hostname.com teleport[42795]: access denied to 'ac54f2d8-447b-4bda-a942.server': bad username or credentials

The auth_token under `teleport:` appears to be fine as other servers are using the same teleport.yaml configuration....

**Comment by a-palchikov** [comment]
This error seems to be caused by the renewed CA certificate but I'm not sure about your particular setup so you could elaborate a bit.
On the other side, I'm not a primary teleport developer and I delegated your question so you can get a more authoritative answer.

**Comment by marchofreason** [comment]
@a-palchikov I think you might be right - Basically what we did was terminate the old server, re-initiate a new server and re-do the certificate. Since then any previous nodes that connected no longer work.

Do you have any advice about completely "wiping" teleport from the node so that we can start from scratch?

**Comment by marchofreason** [comment]
App

**Comment by russjones** [comment]
@marchofreason `rm -fr /var/lib/teleport` works. :)

You may have bumped into an issue with dynamic configuration. If you specify a backend (like etcd, dynamodb, dir) we only read the configuration file the first time Teleport starts and from then on the source of truth is the backend.

For situations like these I recommend you set `dynamic_config: false` to force Teleport to read configuration from disk. This is probably why you kept seeing the old IP address in the logs.
