### ISSUE TITLE
Database auto-discovery fails with databases created by CloudFormation.

### ISSUE THREAD

**Issue by jacobb84** [gravitational/teleport#9737]
### Description

**What happened**:
I created a MySql RDS instance via CloudFormation scripts and setup the teleport database auto-discovery agent. The database wasn't showing up in Teleport however. Once I confirmed permissions were correct I turned on debugging and looked at the logs. I saw the following error repeated:

`INFO [RDS-WATCH] Could not convert RDS instance "*******" to database resource: invalid label key: "aws:cloudformation:stack-id". labels:map[*:[*]] region:us-east-1 watchers/rds.go:114`

The root of the problem seems to be with this function: https://github.com/gravitational/teleport/blob/807c6d6627ad13c67ad1e14a8457962a725320df/lib/services/database.go#L219-L226 

It's adding every tag as a label, including ones with reserved characters. Could we adjust the logic to either filter out invalid tags or give us the ability to opt-in only specific tags to be included as labels?

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a AWS::RDS::DBInstance in CloudFormation
2. Turn on Teleport Database auto-discovery agent.

### Server Details
- Teleport version (run `teleport version`): 8.0.7
- Server OS (e.g. from `/etc/os-release`): Debian 11
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by greedy52** [comment]
https://github.com/gravitational/teleport/blob/c4bb671f2f78380541940de4ed17339484728e57/api/types/resource.go#L257-L266

**Comment by jacobb84** [comment]
Wow, thanks all for the quick turn-around on this!
