### ISSUE TITLE
Teleport 8.0.7 install fails on Debian - `GLIBC_2.25' not found (required by teleport)

### ISSUE THREAD

**Issue by alwaysastudent** [gravitational/teleport#9750]
### Description

Getting an error `'GLIBC_2.25' not found (required by teleport)` on all teleport commands.

Downloaded and installed the Teleport on a Debian system from https://get.gravitational.com/teleport-v8.0.7-linux-amd64-bin.tar.gz

```
# teleport version
teleport: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by teleport)

```

**What happened**:

Teleport binary process does not work, and it throws an error on all teleport commands `'GLIBC_2.25' not found (required by teleport)` on all teleport commands.

**What you expected to happen**:

Expected to run without any errors, the previous versions used run well.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Install Teleport in a Debian machine with the following OS spec

```
$cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

```
uname -r
4.14.81.bm.24-amd64
```

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):

```
$cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
# uname -a
Linux xxxx-123 4.14.81.bm.24-amd64 #1 SMP Debian 4.14.81.bm.24 Tue Aug 11 01:43:51 UTC 2020 x86_64 GNU/Linux

# cat /etc/issue
Debian GNU/Linux 9 \n \l
```

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):  Physical machine

- Additional details:

### Client Details
- Tsh version (`tsh version`): 
```
tsh version
Teleport v8.0.7 git:v8.0.7-0-geb8076446 go1.17.3
```

**Comment by zmb3** [comment]
The "CentOS 7" builds [here](https://get.gravitational.com/teleport-v8.0.7-linux-amd64-centos7-bin.tar.gz) are not specific to CentOS 7, they're just built against an older GLIBC. 

Let me know if they don't work for you.
