### ISSUE TITLE
Weird formatting on https://goteleport.com/docs/setup/admin/trustedclusters/

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#9751]
It looks like there's a formatting/ordering issue:

![Screenshot 2022-01-12 at 09 14 28](https://user-images.githubusercontent.com/897821/149147372-1cd8d464-0d89-4e93-81c7-a1de8d650563.png)

**Comment by ptgott** [comment]
We've mostly rewritten the Trusted Clusters guide since this issue was created, so I am closing it.
