### ISSUE TITLE
Prefixing an application name with "kubernetes" makes the proxy route it as a Kubernetes cluster

### ISSUE THREAD

**Issue by pzduniak** [gravitational/teleport#9755]
Cute bug. I just wish I tried renaming the app name earlier :-)

### Description

**What happened**: I tried to expose the Kubernetes Dashboard through Application Access.

**What you expected to happen**: I expected it to work.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Expose the dashboard like this:
```json
        {
          name: 'kubernetes-dashboard',
          uri: 'https://kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local:443',
          insecure_skip_verify: true,
        },
```
2. Watch it fail spectacularly

### Server Details
- Teleport version (run `teleport version`): 8.0.7
- Server OS (e.g. from `/etc/os-release`): Docker
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Oracle Cloud
- Additional details:

### Client Details
Irrelevant. Browser access.

### Debug Logs
Every request to `kubernetes-dashboard.teleport.realdomain.com` returns this certificate instead of the configured web access one:
```
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: street=; postalCode=null; O=Proxy; CN=186f4adf-d811-4f3c-b897-3b0deb70217a.teleport.realdomain.com; 1.3.9999.1.7=teleport.realdomain.com
*  start date: Jan 12 13:09:14 2022 GMT
*  expire date: Jan 10 13:10:14 2032 GMT
*  issuer: O=teleport.realdomain.com; CN=teleport.realdomain.com; serialNumber=85759893679173037217089499040542964166
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway
```
Per this log (caused by sending an unauthenticated request to the domain), it goes into the Kubernetes forwarding logic:
```
2022-01-12T14:26:39Z WARN [PROXY:PRO] Denying proxy access to unauthenticated user of type auth.BuiltinRole - this can sometimes be caused by inadvertently using an HTTP load balancer instead of a TCP load balancer on the Kubernetes port. proxy/forwarder.go:365
```
I have two Kubernetes clusters with the same root domain (ie. the kubernetes dashboard domain is `kubernetes-dashboard.teleport.global.rootdomain.com`, `rootdomain.com` is hidden):
![image](https://user-images.githubusercontent.com/917230/149160808-c5fb3ead-e169-4197-9a56-f61ae7dd2bbc.png)

**Comment by zmb3** [comment]
@smallinsky we can close this one now, right?

**Comment by smallinsky** [comment]
Fixed by https://github.com/gravitational/teleport/pull/9777
