### ISSUE TITLE
Add the remote IP address for events such as login, etc.

### ISSUE THREAD

**Issue by SalvoRusso8** [gravitational/teleport#9778]
### What
Add the remote IP address as a field in the events that are missing it.

### Why
Because it will be very useful to get this information when using Teleport Event Handler for example to block an IP that is performing an attack through login attempts.

**Comment by ap-wtioit** [comment]
Would love this feature. Current teleport logs only allow us to see that there is going something on:
* event.log
  ```
  {"ei":0,"event":"user.login","uid":"46496f1e-f415-453b-a670-05c800cb8aaf","code":"T1000W","time":"2022-01-26T09:26:50.649Z","cluster_name":"redacted","user":"testing_audit_log","success":false,"error":"invalid username, password or second factor","method":"local"}
  {"ei":0,"event":"user.login","uid":"48209e2e-29e9-4337-929f-192cbd3bb9f5","code":"T1000W","time":"2022-01-26T09:28:51.628Z","cluster_name":"redacted","user":"testing_audit_log","success":false,"error":"invalid username, password or second factor","method":"local"}
  ```
And only with the help of nginx in front of teleport we can get the IPs  
* access.log (nginx, web login attempt, redacted IP)
  ```
  256.256.256.256 - - [26/Jan/2022:10:26:50 +0100] "POST /v1/webapi/sessions HTTP/1.1" 403 3120 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
  ```
* access.log (nginx, tsh login attempt, redacted IP)
  ```
  256.256.256.256 - - [26/Jan/2022:10:28:56 +0100] "POST /v1/webapi/ssh/certs HTTP/1.1" 403 89 "-" "Go-http-client/1.1"
  ```

**Comment by zmb3** [comment]
@strideynet I believe this is what you're working on now, correct?

**Comment by strideynet** [comment]
@zmb3 That's correct (https://github.com/gravitational/teleport/issues/12523) is a bit more specific to what I'm currently working on, which is focussing on actions via the web interface first and following up with actions from `tsh` et al shortly.
