### ISSUE TITLE
Capture backspace in browser-based console session

### ISSUE THREAD

**Issue by iJebus** [gravitational/teleport#979]
I've been giving Teleport a bit of a test-run and just noticed that hitting the backspace key (or delete key) in a browser-based console session is getting captured by my browser and going back in history rather than deleting the previous character.

More exactly, the first press of backspace deletes the previous character, pressing backspace again then goes back to the previous page. I'm using Vivaldi.

This is isn't a bug with Teleport but perhaps it's a behaviour you'd like to try override, as I doubt many people pressing backspace or the delete key in the console will be expecting to go backwards in history.

**Comment by kontsevoy** [comment]
@iJebus trying to reproduce here... without success. 

Questions:
1. Your OS?
2. Your browser/version?

Thanks.

**Comment by alex-kovoy** [comment]
What version of teleport did you use? Recent releases have a new, updated web terminal control.

**Comment by kontsevoy** [comment]
marking as invalid unless @iJebus comes back.

**Comment by iJebus** [comment]
Hey @kontsevoy @alex-kovoy , sorry for the delay. I could have sworn that I had tested it in both Chrome and Vivaldi at the time; I just did it again and Chrome doesn't display the issue while Vivaldi does. Given that, I'd say it's pretty safe to leave as invalid/'not your problem' and close. 

For your curiosity:
OSX 10.12.5
Vivaldi 1.9.818.50
Chrome 58.0.3029.110
Teleport v2.0.6 git:v2.0.5-2-g0b0de0a0-dirty (via vagrant)

**Comment by kontsevoy** [comment]
@iJebus thanks for getting back to us. As much as we want to keep everyone happy, we do not have the resources to support/test for non-common configurations such as Vivaldi browser. Our focus is OSX/Windows/Linux (on the platform dimension) and Firefox+Chrome on the browser side.
