### ISSUE TITLE
Custom S3 bucket options (Cloud)

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#9818]
### What
With our SaaS/Cloud offering the S3-backend is not currently configurable. It would be nice to be able to customize this and allow customers to input their own S3 (or Backblaze) buckets for session recording storage options.

### How
Allow a configurable option within Teleport UI or `.yaml` to let customers add their own S3 buckets

### Why
Allow customers some ownership of their own data and S3 costs

### Workaround
None for Cloud. If a customer self-hosts then this is not an issue.

**Comment by kelcya** [comment]
This would be great for companies that deal with PHI (personal health information).

**Comment by michaelnowin** [comment]
Is this something we're actively tracking as a feature? Have a use case where this popped up around PHI

**Comment by zmb3** [comment]
Tracking this at gravitational/cloud#4661
