### ISSUE TITLE
Force connections to go through the proxy

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#982]
### Issue

At the moment, if you have a valid SSH certificate, you can connect to a node directly and bypass the proxy. It would be nice if Teleport nodes would only accept connections from the proxy always forcing you to connect via the proxy.

This feature could potentially break OpenSSH interoperability (unless we implement this via TCP wrappers as OpenSSH does).

**Comment by kontsevoy** [comment]
@russjones how would a node know if that's a proxy connecting? proxies (in cloud environments) can come and go, change their IPs, etc. Besides, you can implement L4 rules on your network stack, like in security groups or directly in switches.

**Comment by kontsevoy** [comment]
@russjones LMK if you had something specific in mind, otherwise I suggest we close this.

**Comment by russjones** [comment]
@kontsevoy We briefly discussed this yesterday, but it's a request from a commercial customer. Let's discuss this offline?

**Comment by klizhentas** [comment]
To allow this we should:

* Allow nodes to esablish individual reverse tunnels to the proxy.
* Bind teleport node to localhost.

**Comment by klizhentas** [comment]
dupe as of some ticket, Ev will do bookeeping

**Comment by kontsevoy** [comment]
#803 is how we'd recommend doing it. I guess we're committing to implementing #803 at some point
