### ISSUE TITLE
Cluster Role Mapping

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#983]
## Description

In Teleport every organization is represented by the "Trusted Cluster".
Imagine the situation when we have the following clusters set up:

* Acme cluster this is a main cluster that manages local users of Acme corp
* Hooli cluster - this is a cluster that manages users of Hooli corp

* Alice is a user local to Acme cluster, and we need to map Alice's roles to Hooli cluster roles dynamically.

### Some security considerations

Acme cluster and Hooli cluster both control their roles and users. Even if Alice is root on cluster Acme, she may not even have any SSH root access from Hooli's cluster standpoint.

### Proposal

We are going to introduce new interpretation of labels and call it cluster role mappings. 

![teleport cluster role mapping - role mapping schema](https://cloud.githubusercontent.com/assets/13717/26087170/20069280-39a4-11e7-97f6-ee383b926f1e.png)

Here is the flow:

* Alice Authenticates with local cluster Acme auth server with local credentials
* Alice is a member of local `Devs` Group
* Alice receives OpenSSH certificate with extension metadata encoded and contains `roles: ["Devs"]` properties. This metadata is protected by the signature and can not be tampered

* When Alice authenticates with cluster Hooli, cluster local Auth server detects metadata `roles: ["Devs"]`.

* Cluster Hooli has to control what labels it will allow to map to Roles, because labels become a security feature. We are going to introduce `map_remote_roles` property to `TrustedCluster` spec to specify how to map remote roles to local roles.

```yaml
kind: trused_cluster
version: v1
metadata:
   name: acme
spec:
  role_map: 
      - remote: Devs
        local: [HooliDevs, Remotes]
```

This means that cluster Hooli allows to map Acme's 'Devs' roles received in certificate metadata to local roles `HooliDevs` and `Remotes`

By default `map_remote_roles` are empty and all metadata received via labels is ignored. If `map_remote_roles` are specified, the property `roles` of the trusted cluster will be prohibited, so these properties are mutually exclusive.

### OpenSSH compatibility

In this mode `allowed_logins` should still contain the principals of the target clusters, but it will be additionally limited by RBAC access control.

Some old OpenSSH servers have a bug that treat all non-critical extensions as critical ( https://bugzilla.mindrot.org/show_bug.cgi?id=2387) so we should be aware of this in the documentation.

**Comment by kontsevoy** [comment]
looks good, I would remname `map_remote_roles` to `role_map` because you need a noun, not a verb, also it's shorter

**Comment by brumfb** [comment]
Overall, makes sense and should satisfy what we are trying to accomplish.  A couple questions:
* Is this `This means that cluster Hooli allows to map Acme's 'Devs' roles received in certificate metadata to local roles Devs and Remotes` supposed to read `This means that cluster Hooli allows to map Acme's 'Devs' roles received in certificate metadata to local role HooliDevs`?
* Do roles and roles_map need to be mutually exclusive or could it's usage be triggered on incoming metadata?  This could really go either way, I think, but allowing for this might help existing installs moving to the role_map if they want without inadvertently disabling someones access. The trusted cluster defined roles becomes the default map, essentially.
* Does the local role (ie HooliDev) limit/control access based on the incoming login principal or is this still entirely driven from the Acme role?

**Comment by klizhentas** [comment]
@brumfb 

> Is this This means that cluster Hooli allows to map Acme's 'Devs' roles received in certificate metadata to local roles Devs and Remotes supposed to read This means that cluster Hooli allows to map Acme's 'Devs' roles received in certificate metadata to local role HooliDevs?

Sorry, there was a typo there, we will be mapping remote role `Devs` to local roles `HooliDevs` and `Remotes`

> Do roles and roles_map need to be mutually exclusive or could it's usage be triggered on incoming metadata? This could really go either way, I think, but allowing for this might help existing installs moving to the role_map if they want without inadvertently disabling someones access. The trusted cluster defined roles becomes the default map, essentially.

I just want to keep only one property, vs multiple properties. Also triggering by metadata could be a security risk, as it will be pushed by remote cluster, not local cluster - local cluster still to have control.  We will support `roles` for a while, but will ask to switch when updating cluster resources - should not break anything. I will add a way to map everything to some roles, so you can roll this in stages `'*': [old mapping]`

**Comment by ekristen** [comment]
This is a huge +1, makes trusted clusters much more friendly and usable.

**Comment by klizhentas** [comment]
This is implemented, will need to write docs as a separate activity.
