### ISSUE TITLE
Allow TTL to Exceed 12 Hours when Using SSO Authentication

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#9837]
Customers sometimes need to generate long-lived certs that exceed 12 hours for "service accounts". 

Presently, when you authenticate with an SSO user, impersonation of another user is still capped at 12 hours, regardless of the role max_session_ttl of the user that is being impersonated.

**Comment by russjones** [comment]
We want to discourage the use of long-lived certificates. Teleport 9 will have our alternative https://github.com/gravitational/teleport/issues/7066.
