### ISSUE TITLE
teleport-kube-agent Helm Chart expansion to allow app/db dynamic registration

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#9846]
### What
Modify the existing teleport-kube-agent helm chart to allow customers to use application dynamic registration. Right now there is no way to set the app_service resource in the config

### Why
Customer request/Feature parity

### Workaround
customers have to manually build out the functionality and fork the helm charts which creates issues when trying to keep 1x1 parity with teleport upstream.

**Comment by gary-shaw-kidsloop** [comment]
Another option is to do [post rendering](https://helm.sh/docs/topics/advanced/#post-rendering) with `Kustomize`. I do think it might be a good idea to allow arbitrary configuration changes via the chart such as `extra config` section. 

An extra config section for applications in this instance would not only have allowed the addition of the `dynamic registration` but also allowed other features to be added without a chart change being required necessarily.

**Comment by r0mant** [comment]
Copied description from the duplicate ticket https://github.com/gravitational/teleport/issues/10362:

```
For dynamic discovery to work on an agent, resource labels are defined on the agent at startup, ie:

app_service:
  enabled: "yes"
  resources:
  - labels:
      "*": "*"

However, it is not possible to define this in the custom helm chart, as the resources keyword is already used to define [kubernetes limits](https://goteleport.com/docs/kubernetes-access/helm/reference/#resources).

Require the ability to define resource labels to enable dynamic registration feature on kube agents
```
