### ISSUE TITLE
Clean up the "Connect to Kubernetes Cluster" modal order in the WebUI

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#9852]
## Details
Users have suggested moving the Note about the kubeconfig variable that's currently at the bottom of the modal that pops up when a user navigates to Kubernetes > <cluster-name> > Connect in the WebUI somewhere before current Step 2 in that same modal. A few users have accidentally made changes to their their current kubeconfig files before getting to the bottom and reading that.

### Category

- Improve Existing

**Comment by ptgott** [comment]
@Aharic Would you mind adding a screenshot of the modal so we can see what needs to be done without setting up a demo environment? Thanks!

**Comment by zmb3** [comment]
This has been fixed. Here's a screenshot of the latest modal:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/7527103/199843351-466cf9f2-b5da-4b49-80e1-2d7011f29868.png">
