### ISSUE TITLE
Document the use of labels in our Kubernetes guides

### ISSUE THREAD

**Issue by zen** [gravitational/teleport#9860]
## Details
Documentation is inconsistent on what labels are used with Teleport deployed to Kubernetes. In Helm guide the default namespace and label is teleport (e.g. app=teleport). In this guide, the label used is app=teleport-cluster

### Category

- Improve Existing

**Comment by ptgott** [comment]
Closing because we removed the use of the `app` label in https://github.com/gravitational/teleport/pull/19881.
