### ISSUE TITLE
Request approval date showing incorrectly in webui

### ISSUE THREAD

**Issue by colinedwardwood** [gravitational/teleport#9863]
### Description

**What happened**:
When you approve an access request in the cli, the approval date displayed is incorrect.
"cwood@goteleport.com approved this request 2021 years ago"

**What you expected to happen**:
I expect a correct time frame displayed.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. request a role
2. approve request in cli
3. view approval in webui

### Server Details
- Teleport version (run `teleport version`): Teleport Enterprise v8.1.0 git:v8.1.0-0-g3dc269bef go1.17.3
- Server OS (e.g. from `/etc/os-release`):PRETTY_NAME="Amazon Linux 2"
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS EC2
- Additional details:

### Client Details
- Tsh version (`tsh version`):Teleport v8.1.0 git:v8.1.0-0-g3dc269bef go1.17.3
- Computer OS (e.g. Linux, macOS, Windows): macos
- Browser version (for UI-related issues): chrome
- Installed via (e.g. apt, yum, brew, website download): website download
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by dancmeyers** [comment]
We see this error, but _not_ with requests approved via the Web UI. Only requests approved via the CLI `tsh` command (which is output by the Teleport Slack bot to make approving requests easier) results in the incorrect date:

Teleport Enterprise v9.0.1 git:v9.0.1-0-g7bbe6f15c go1.17.7 on AWS EKS, using the Teleport Helm chart to deploy. Client installed from the Enterprise portal, and reports the exact same version string as the server. This is on MacOS.

**Comment by colinedwardwood** [comment]
true, I updated my description, it's approvals via the CLI.

**Comment by zmb3** [comment]
Tagging with `time-to-value` as I expect more OSS users to try out access requests with the launch of Teleport 10, and they should have a better experience.
