### ISSUE TITLE
Default config file in docs is not actually the default?

### ISSUE THREAD

**Issue by k4kfh** [gravitational/teleport#988]
I am trying to set up a new Teleport server, and I followed the quick start guide. I installed everything and ran Teleport, and it works (I can access the web UI login page). When I create the ``/etc/teleport.yaml`` file with [the contents here](http://gravitational.com/teleport/docs/2.0/admin-guide/#configuration-file) and point the Teleport server to it on startup, it gives a bunch of certificate errors about the certificates being missing.

Would it be possible to update the config file listed in the docs to accurately reflect the defaults? I'm assuming it's a file naming issue, but I am a little uneducated with HTTPS and certificates so I don't really know what to change.

Thanks!

**Comment by russjones** [comment]
@k4kfh My guess is this section of the configuration file is giving you problems. 

```
https_key_file: /etc/teleport/teleport.key
https_cert_file: /etc/teleport/teleport.crt
```

You'll need both of those to point to valid certificate and key files. You can either buy a certificate from a commercial vendor or use Let's Encrypt to obtain a free certificate.

If you just want to experiment with Teleport and don't wish to buy certificates, remove those two lines from the config file and Teleport will generate self signed certificates for you. Warning: we don't recommend you do this for production servers as it could potentially open you up to MITM attacks.
