### ISSUE TITLE
Deleting MFA devices fails with U2F devices and Webauthn conf

### ISSUE THREAD

**Issue by mpitt** [gravitational/teleport#9884]
### Description

**What happened**: I tried deleting an MFA device (of 4 I have set up), after upgrading the cluster `second_factor` config from `u2f` to `webauthn`. The deletion failed with "cannot delete the last webauthn device for this user; add a replacement device first to avoid getting locked out"

**What you expected to happen**: the device should be deleted as long as it's not the last one.

### Reproduction Steps

1. Have a cluster with `second_factor: u2f`
2. Create a user and add one or more u2f devices
3. Change the cluster auth config to `second_factor: webauthn`
4. Add a WebAuthn MFA device
5. Try to delete any MFA device: it will fail because with the `second_factor: webauthn` configuration the `deleteMFADeviceSafely` function will only count devices with type `webauthn`, even though `u2f` devices can still be used

### Server Details
- Teleport version (run `teleport version`): 8.0.7
- Server OS (e.g. from `/etc/os-release`): Ubuntu 18.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details: -

### Client Details
- Tsh version (`tsh version`): N/A (using web)
- Computer OS (e.g. Linux, macOS, Windows): macOS, Linux
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): N/A
- Additional details: -

### Debug Logs
N/A

### Side note

I had to look into DynamoDB and decode the cluster state related to my MFA devices to see what was going on. It would be useful to expose more of this information in the UI or CLI (e.g. type and ID of the MFA devices in this case).

### Workaround

Add at least two new devices. With two `webauthn` devices, it's possible to delete U2F ones. It's even possible to add again the very same security key that is already present as U2F.

**Comment by codingllama** [comment]
It looks to me that this got fixed by #10476, before that it looks like we counted U2F and WebAuthn devices separately. This landed on Teleport v10 and onwards.

Thanks for the detailed bug report and apologies for the delay!
