### ISSUE TITLE
Expand SSO docs to include generic SAML instructions

### ISSUE THREAD

**Issue by afalahi** [gravitational/teleport#9886]
## Details
Add a generic SAML documentation instead of just Okta. Also, the spacing/parsing of the SAML assertion is very picky and difficult to troubleshoot, it's best to add the `entity_descriptor_url` during the initial setup instead of saving and editing to paste the URL. The URL handles the metadata parsing better than copy-pasting.

The OIDC Provider is also difficult to set up, I only managed to get it working with Auth0, but two other vendors failed with not so much to go on and I haven't been able to get it working yet.

### Category
- Improve Existing

**Comment by sama8** [comment]
If relevant -> [SAML Jackson](https://github.com/boxyhq/jackson)
