### ISSUE TITLE
Add a "How to revoke access" guide

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#9888]
## Details
A common concern for users of a certificate-based authentication solution like Teleport is how to revoke a certificate before it expires, e.g., if the certificate has been compromised. For users searching for "revocation" in the context of Teleport, we should create a guide to the mechanisms we offer for revoking access. Currently, these are:

- [Resource locking](https://goteleport.com/docs/access-controls/guides/locking/)
- [Certificate rotation](https://goteleport.com/docs/setup/operations/ca-rotation/)

The most likely home for this guide is in the [Security section](https://goteleport.com/docs/setup/security/), which currently contains a preventative guide to reducing the blast radius of attacks. The "How to revoke access" guide would be more focused on addressing an ongoing situation.

### Category
- Improve Existing

**Comment by klizhentas** [comment]
One of the most modern ways to revoke access in Teleport is to place lock on MFA device ID. this way the locking will be granular. 

Another thing worth mentioning is that Teleport is not using revocation lists, instead we rely on short lived certificates (with per session MFA as short lived as one minute) so by default access always expires, compared to revocation lists, where by default access is granted. Locks are helpful enforcement, but short lived certs are really the key of our locking strategy.

**Comment by SCLogo** [comment]
what can we do when E.G. somebody hacked the user's pc and got an approvement somehow? Is there a way to  revoke the session before it runs out ?

**Comment by klizhentas** [comment]
@SCLogo once you lock a user in teleport, all their sessions will be terminated:

https://goteleport.com/docs/access-controls/guides/locking/

**Comment by zmb3** [comment]
This is documented here: https://goteleport.com/docs/server-access/guides/openssh/#revoke-an-ssh-certificate
