### ISSUE TITLE
tsh not using creds from ssh-agent when add-keys-to-agent=only is enabled

### ISSUE THREAD

**Issue by rosskusler** [gravitational/teleport#9891]
### Description

**What happened**: I tried to use the --add-keys-to-agent=only option to prevent tsh from storing SSH keys and certificates on the local filesystem and only store them in the running ssh-agent. It definitely stored an SSH key and certificate in the ssh-agent and did not store and credentials on disk (~/.tsh) however every subsequent call to tsh requires that I re-authenticate. It seems that tsh is not finding the stored key/certificate in the agent for some reason.

**What you expected to happen**: I expected tsh to retrieve or use the key/certficate from ssh-agent to authenticate to teleport.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Logout of teleport
$ tsh logout
Logged out all users from all proxies

2. Verify that we do not have any credentials
$ ls ~/.tsh/keys/teleport-ssh-demo.accessline.com
certs.pem

3. Clear any identities from ssh-agent
$ ssh-add -D
All identities removed.

4. Verify no identities are loaded
$ ssh-add -l
The agent has no identities.

5. Ensure that teleport is configured to only store keys/certs in ssh-agent
$ export TELEPORT_ADD_KEYS_TO_AGENT=only

6. log into teleport. Note that I do successfully authenticate and get a cert loaded into ssh-agent but the CLI says 'Not logged in' at the end... I think because it cannot find credentials on disk.
$ tsh login --proxy=teleport-ssh-demo.accessline.com --debug
ERRO [KEYSTORE]  open /Users/redacteduser/.tsh/keys/teleport-ssh-demo.redacedcorp.com/redacteduser: no such file or directory client/keystore.go:246
DEBU [CLIENT]    open /Users/redacteduser/.tsh/keys/teleport-ssh-demo.redacedcorp.com/redacteduser: no such file or directory client/api.go:751
INFO [CLIENT]    no host login given. defaulting to redacteduser client/api.go:1102
INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.Wma42v1QJe/Listeners" client/api.go:2963
DEBU [TSH]       key for {ProxyHost:teleport-ssh-demo.redacedcorp.com Username:redacteduser ClusterName:teleport-ssh-demo.redacedcorp.com} not found tsh/tsh.go:1964
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport-ssh-demo.redacedcorp.com:443 client/api.go:2924
DEBU             Attempting GET teleport-ssh-demo.redacedcorp.com:443/webapi/ping webclient/webclient.go:62
Enter password for Teleport user redacteduser:
Enter your OTP token:
982463
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport-ssh-demo.redacedcorp.com:443 client/api.go:2924
DEBU [CLIENT]    HTTPS client init(proxyAddr=teleport-ssh-demo.redacedcorp.com:443, insecure=false) client/weblogin.go:221
DEBU [KEYAGENT]  Adding CA key for teleport-ssh-demo.redacedcorp.com client/keyagent.go:302
DEBU [KEYSTORE]  Adding known host teleport-ssh-demo.redacedcorp.com with proxy teleport-ssh-demo.redacedcorp.com and key: SHA256:Adwm3Xhus05AADYh52xkKUcxiFqfTc3axUpYyLx2Xfk client/keystore.go:544
INFO [KEYAGENT]  Loading SSH key for user "redacteduser" and cluster "teleport-ssh-demo.redacedcorp.com". client/keyagent.go:180
INFO [CLIENT]    Connecting proxy=teleport-ssh-demo.redacedcorp.com:3023 login="redacteduser" client/api.go:2156
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com REDACTED FOR CLARITY\n." client/keyagent.go:338
DEBU [KEYAGENT]  Validated host teleport-ssh-demo.redacedcorp.com:3023. client/keyagent.go:344
INFO [CLIENT]    Successful auth with proxy teleport-ssh-demo.redacedcorp.com:3023. client/api.go:2163
DEBU [KEYSTORE]  Returning Teleport TLS certificate from memory, valid until "2022-01-22 09:08:05 +0000 UTC". client/keystore.go:801
DEBU [CLIENT]    Client  is connecting to auth server on cluster "teleport-ssh-demo.redacedcorp.com". client/client.go:840
DEBU [CLIENT]    Client  is connecting to auth server on cluster "teleport-ssh-demo.redacedcorp.com". client/client.go:840
DEBU [KEYAGENT]  Adding CA key for teleport-ssh-demo.redacedcorp.com client/keyagent.go:302
DEBU [CLIENT]    Client  is connecting to auth server on cluster "teleport-ssh-demo.redacedcorp.com". client/client.go:840
DEBU [KEYSTORE]  Adding known host teleport-ssh-demo.redacedcorp.com with proxy teleport-ssh-demo.redacedcorp.com and key: SHA256:Adwm3Xhus05AADYh52xkKUcxiFqfTc3axUpYyLx2Xfk client/keystore.go:544
DEBU [KEYSTORE]  Returning Teleport TLS certificate from memory, valid until "2022-01-22 09:08:05 +0000 UTC". client/keystore.go:801
INFO [CLIENT]    Connecting proxy=teleport-ssh-demo.redacedcorp.com:3023 login="redacteduser" client/api.go:2156
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com REDACTED FOR CLARITY\n." client/keyagent.go:338
DEBU [KEYAGENT]  Validated host teleport-ssh-demo.redacedcorp.com:3023. client/keyagent.go:344
INFO [CLIENT]    Successful auth with proxy teleport-ssh-demo.redacedcorp.com:3023. client/api.go:2163
DEBU [CLIENT]    Found clusters: [{"name":"teleport-ssh-demo.redacedcorp.com","lastconnected":"2022-01-21T21:08:06.148407118Z","status":"online"}] client/client.go:110
DEBU [KEYSTORE]  Returning Teleport TLS certificate from memory, valid until "2022-01-22 09:08:05 +0000 UTC". client/keystore.go:801
DEBU [CLIENT]    Client  is connecting to auth server on cluster "teleport-ssh-demo.redacedcorp.com". client/client.go:840
DEBU [CLIENT]    Client  is connecting to auth server on cluster "teleport-ssh-demo.redacedcorp.com". client/client.go:840
INFO [CLIENT]    Connecting proxy=teleport-ssh-demo.redacedcorp.com:3023 login="redacteduser" client/api.go:2156
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com REDATED FOR CLARITY\n." client/keyagent.go:338
DEBU [KEYAGENT]  Validated host teleport-ssh-demo.redacedcorp.com:3023. client/keyagent.go:344
DEBU [CLIENT]    Client  is connecting to auth server on cluster "teleport-ssh-demo.redacedcorp.com". client/client.go:840
INFO [CLIENT]    Successful auth with proxy teleport-ssh-demo.redacedcorp.com:3023. client/api.go:2163
DEBU [KEYSTORE]  Returning Teleport TLS certificate from memory, valid until "2022-01-22 09:08:05 +0000 UTC". client/keystore.go:801
DEBU [KEYSTORE]  Returning Teleport TLS certificate from memory, valid until "2022-01-22 09:08:05 +0000 UTC". client/keystore.go:801
DEBU [CLIENT]    Client  is connecting to auth server on cluster "teleport-ssh-demo.redacedcorp.com". client/client.go:840
ERRO [KEYSTORE]  open /Users/redacteduser/.tsh/keys/teleport-ssh-demo.redacedcorp.com/redacteduser: no such file or directory client/keystore.go:246
DEBU [CLIENT]    open /Users/redacteduser/.tsh/keys/teleport-ssh-demo.redacedcorp.com/redacteduser: no such file or directory client/api.go:751

ERROR REPORT:
Original Error: *trace.NotFoundError Not logged in.
Stack Trace:
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:2171 main.onStatus
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:985 main.onLogin
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:628 main.Run
	/tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:285 main.main
	/var/folders/ys/8czjjsys38x504kj8172pd_m0000gp/T/drone-tYtBnOaBO5pCtiR0/home/drone/build-9807-1641839578-toolchains/go/src/runtime/proc.go:255 runtime.main
	/var/folders/ys/8czjjsys38x504kj8172pd_m0000gp/T/drone-tYtBnOaBO5pCtiR0/home/drone/build-9807-1641839578-toolchains/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: Not logged in

7. Check ssh-agent for the identity
$ ssh-add -l
2048 SHA256:5d05NFV9lBqJICCoX+b8cshN+OOzku2mMp4uV5pxN6E teleport:redacteduser (RSA-CERT)
2048 SHA256:5d05NFV9lBqJICCoX+b8cshN+OOzku2mMp4uV5pxN6E teleport:redacteduser (RSA)

8. Confirm that no creds were written to disk:
$ ls ~/.tsh/keys/teleport-ssh-demo.accessline.com
certs.pem

9. Query teleport for list of servers (it forces me to login again). If I enter my password/u2f token it will list the servers I have access to. If I run the command again though I get prompted again for password/u2f.
$ tsh ls --debug
INFO [CLIENT]    no host login given. defaulting to redacteduser client/api.go:1102
INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.Wma42v1QJe/Listeners" client/api.go:2963
DEBU [TSH]       key for {ProxyHost:teleport-ssh-demo.redactedcorp.com Username:redacteduser ClusterName:teleport-ssh-demo.redactedcorp.com} not found tsh/tsh.go:1964
DEBU [CLIENT]    Activating relogin on no SSH auth methods loaded, are you logged in?. client/api.go:517
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport-ssh-demo.redactedcorp.com:443 client/api.go:2924
DEBU             Attempting GET teleport-ssh-demo.redactedcorp.com:443/webapi/ping webclient/webclient.go:62
Enter password for Teleport user redacteduser:

### Server Details
- Teleport version (run `teleport version`):  8.0.1
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): dedicated hardware in kubernetes using quay.io/gravitational/teleport:8.0.1
- Additional details:

### Client Details
- Tsh version (`tsh version`): v8.1.0
- Computer OS (e.g. Linux, macOS, Windows): macOS Monterey
- Browser version (for UI-related issues): n/a
- Installed via (e.g. apt, yum, brew, website download): website download
- Additional details:

### Debug Logs
included in the repro steps

**Comment by rosskusler** [comment]
It looks like this is the immediate cause:

DEBU [TSH] key for {ProxyHost:teleport-ssh-demo.redactedcorp.com Username:redacteduser ClusterName:teleport-ssh-demo.redactedcorp.com} not found tsh/tsh.go:1964

**Comment by rosskusler** [comment]
Is this feature working for others?

**Comment by Joerger** [comment]
I get the same issue, you have to always run `tsh` with the `-k` flag and re-login for each request.

The best workaround for now would be to set `TELEPORT_ADD_KEYS_TO_AGENT=only` and re-login on every `tsh` request. 

@russjones @xacrimon Is this a simple UX oversight, or intentional? Would it be possible to update the `tsh login` flow to check for existing ssh-agent keys for the Teleport user, rather than requiring them to be in the `~/.tsh` keys directory?

**Comment by russjones** [comment]
@rosskusler At the moment `--add-keys-to-agent` is strictly concerned with how keys are added to a running SSH agent. See the following RFD for more details.

https://github.com/gravitational/teleport/blob/master/rfd/0018-agent-loading.md#details

However, `tsh` will always use the certificates on disk for authentication, `tsh` only really uses the agent to forward credentials to another server.

**Comment by rosskusler** [comment]
@russjones  thank you for the info.  Yeah, it was my hope that this feature would eliminate the need to store the SSH key and certificate on disk. It is something that we worry about. Hope you have a great day.

**Comment by russjones** [comment]
@rosskusler Alright, this is something we want to do, but it's not scheduled yet. When it does get scheduled I'll come back and update this ticket.

**Comment by rosskusler** [comment]
@russjones I think I was under the mis-impression that Teleport used the SSH certificate as a credential for authenticating usersto Teleport (for the purpose of 'tsh kube ls, etc) and didn't realize that it actually uses a x.509 certificate instead. Is the idea of #7830 to add extensions to the SSH cert so that it can be used as an alternative to the x.509 cert.. because openssh certs can be shared using ssh agent forwarding? Or do I have it wrong? :)

**Comment by Joerger** [comment]
@rosskusler FYI we are planning to working on this soon, and have moved it to a separate issue - https://github.com/gravitational/teleport/issues/10489 if you'd like to keep an eye on it.
