### ISSUE TITLE
Optional limiting of an SSH certificate to a single IP

### ISSUE THREAD

**Issue by rosskusler** [gravitational/teleport#9894]
### What
When teleport issues a SSH certificate upon successful authentication, have the option for the clients IP-address to be encoded in the SSH certificate. Then when teleport is presented with a certificate that does contain an IP-address it should only accept the auth request if it is coming from that IP-address.

### How
We would probably need a global or per-user attribute named something like "embed-sourceip-in-cert". When a user with this setting enabled successfully authenticates from IP a.b.c.d, teleport would embed a.b.c.d in the SSH certificate somehow. Then when a user tries using the certificate for something (tsh ssh, tsh kube login, etc) the auth server should check to see whether the certificate contains an IP-address. If it does and if the IP-address doesn't match the source-IP of the request, the auth server would reject the request. If the certificate IP-address matches the source-IP, the request would proceed as it does currently. If the certificate doesn't contain any IP-address, obviously, teleport would just proceed handling the request as it does currently. In some cases it might be necessary to look at the Forwarded or X-Forwarder-For http headers instead of the actual source-IP of the request. We also add custom extensions teleport-roles, teleport-route-to-cluster, and teleport-traits. Maybe we could just add a teleport-certificate-ip extension too.

### Why
If an attacker gets onto a developer workstation they potentially can steal the certificate/private key and re-use it from somewhere else. This feature request would essentially scope a SSH key/certificate to a single source-IP address so that it cannot as easily be re-used somewhere else. This would probably not work for all situations and it probably wouldn't be enabled by default. But it could be useful for other organizations and would provide a security benefit.

### Workaround
The ability to store the SSH key and certificate in ssh-agent might be a viable alternative for some organizations. This feature could potentially work in tandem with that should (an SSH certificate with an IP-address could still be loaded into ssh-agent).

**Comment by strideynet** [comment]
Closed by https://github.com/gravitational/teleport/pull/13243
