### ISSUE TITLE
Only show the logins actually allowed in the Web UI

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#9896]
In the Web UI, Teleport creates and shows a set of all allowed logins from all roles assigned to the user. This set might be much larger than that allowed to a particular server. Imagine you have 1 role that allows you to access `server01` as `foo` and `server02` as `bar`. The drop down for both `server01` and `server02` would show you `foo` and `bar`.

In the past we could do any optimization here server side because the backend would return a list of all the nodes. Doing this RBAC check on 10k+ nodes would be too slow.

Now with pagination support coming in https://github.com/gravitational/teleport/issues/9399, we should be able to do this because running RBAC checks to only return the list of allowed logins per server should be doable if we're only returning a page at a time.

**Comment by stevenGravy** [comment]
https://github.com/gravitational/teleport/issues/3311 similar

**Comment by zmb3** [comment]
Not sure when this was fixed, but it's no longer an issue.

**Comment by ravicious** [comment]
I believe this was fixed by https://github.com/gravitational/webapps/pull/873.
