### ISSUE TITLE
Configuration option for users wanting to configure multiple kubernetes clusters with kubeconfig file

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#9911]
### What
Customers who manage remote environments that they have no control over often rely on kubeconfig files to manage and connect remote kubernetes clusters to their central Teleport cluster. There is currently no mechanism to allow teleport to read  a single kubeconfig file and parse out the different remote clusters so they can be separated based on RBAC needs.

### How
How would you implement this?

### Why
MSPs and customers who use Teleport to manage their own customer environments that they have no control over do not always have the option to deploy a Teleport kube agent in the remote environments and have to rely on kubeconfigs on the proxy to connect to the remote clusters.

### Workaround
Current workaround is to run separate kubernetes_service processes and run a separate kubeconfig file for each. This is a burdensome process and not easily scalable for customers with a large amount of remote environments, especially as those environments may often come into and go out of existence depending on their sub-client environments.

**Comment by tigrato** [comment]
This functionality is already available when using a single kubeconfig file with multiple context values defined
