### ISSUE TITLE
Block `session.connect` when Windows Desktop session starts

### ISSUE THREAD

**Issue by atburke** [gravitational/teleport#9917]
### Description

**What happened**: The `session.connect` event introduced in #9370 is being incorrectly emitted when starting a desktop session.

**What you expected to happen**: `session.connect` should not be emitted.

**Comment by zmb3** [comment]
@atburke can we close this one?

**Comment by atburke** [comment]
I don't think this was ever implemented.

**Comment by zmb3** [comment]
I no longer see session.connect events and there are two merged PRs linked above.

**Comment by atburke** [comment]
If you're not seeing the event, then I'd say it's safe to close this.
