### ISSUE TITLE
Can't use Web Terminal from mobile

### ISSUE THREAD

**Issue by shaharmor** [gravitational/teleport#994]
Hi,
When trying to connect using the Web Terminal on Chrome browser on iPhone 7+ I get disconnected all the time.

On desktop its working.

**Comment by shaharmor** [comment]
On the server I see: `http: TLS handshake error from x.x.x.x:yyyyy: EOF`

**Comment by nikatjef** [comment]
One of the guys in my office had this issue with his Mac.  We figured out that the problem was cause by our SSL key.  Once we changed that to a recognized CA signed certificate he was able to connect to the web terminal.

**Comment by kontsevoy** [comment]
@shaharmor we have confirmed, @nikatjef is correct: this is an issue of how self-signed certificates are handled on the mobile. The browser is refusing to use the self-signed cert. Once you connect to a proper HTTPS proxy (with a purchased SSL cert) the web-based terminal will work (although it's not very enjoyable, but we'll work on that!)
