### ISSUE TITLE
Document which configuration parameters can be referenced as a file path

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#9946]
## Details
Currently, the `auth_token` parameter can be passed as a string or file path but our configuration reference file only mentions the string method: https://goteleport.com/docs/setup/reference/config/

Request is to update the configuration reference file to include the file path method on any option(s) where this functionality is avaialable

**Comment by ptgott** [comment]
Note to self: we use `utils.TryReadValueAsFile` to read a config value as a file path or a literal value.
