### ISSUE TITLE
Include the file name of the uploaded file in audit log

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#9959]
### What
Have Teleport include the name of the file uploaded in the audit log event `SCP Upload` when a file is uploaded through the Web UI.  Currently only the file path up to the destination directory is shown

### How
Add the file name to the audit log

### Why
It is important to know what file the user uploaded for audit purposes

**Comment by dmsergeevN26** [comment]
It would also be relevant to see the file size. However, the ideal solution is to store the file along with the user session

**Comment by stevenGravy** [comment]
Here's an example where a user does a `tsh scp file.txt ubuntu@myserver1:/home/ubuntu`

Only the `path` destination is stored.

**Comment by zmb3** [comment]
Duplicate of #3900
