### ISSUE TITLE
Spammed by your sales team

### ISSUE THREAD

**Issue by andyshinn** [gravitational/teleport#9982]
Regression of https://github.com/gravitational/teleport/issues/2593

### Description

**What happened**:

Your sales team is spamming me and others using data harvested by ZoomInfo.

**What you expected to happen**:

Fire your sleazy sales team and cut all ties with data harvesting services like ZoomInfo.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Have an email address. 
2. Work in the industry.
3. Receive email from Bari Sonnier.

### Server Details
- Teleport version (run `teleport version`): Who cares?
- Server OS (e.g. from `/etc/os-release`): Ask Bari, it's probably in ZoomInfo.
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): I'm not and won't ever because of this.
- Additional details: I am angry to the point I cannot see straight.

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:
Reference #2592

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by klizhentas** [comment]
@andyshinn thanks for your report. We will investigate why you have been contacted despite your request not to and get back to you.

**Comment by bardiashahali** [comment]
@andyshinn - Apologies for your negative experience with our sales team. I've chatted with the individuals who sent you that email and rest assured you've been removed from all future outreach. As an early-stage company, we really appreciate your thoughtful feedback and will use it to improve our internal processes. Thank you.
