### ISSUE TITLE
Implement `tctl tokens add --format=token`

### ISSUE THREAD

**Issue by hatched** [gravitational/teleport#9986]
### What
In the [getting started guide](https://goteleport.com/docs/server-access/getting-started/) and elsewhere the code used to generate a token for adding additional nodes to the cluster requires that you grep the output to get the token.

`sudo tctl tokens add --type=node | grep -oP '(?<=token:\s).*' > token.file`

This currently [doesn't work out of the box](https://github.com/gravitational/teleport/issues/6713) because the `token.file` includes a token with a `.` that needs to be removed. 

It would be nice if this grep was not required.

### How
We could add a flag to the `tctl tokens add` command to dump the proper token value to a file. 

A couple ideas:
```
$ tctl tokens add --type=node --tokenfile
/path/to/tokenfile

$tctl tokens add --type=node --format=token
/path/to/tokenfile
```
- Dumping the path after outputting the token makes it easy to script with.
- The latter example would allow the `tokens add` command to support multiple output formats `json`, `yaml`. 

### Why
Requiring the user to grep the token value is error prone and requires that we keep the structure of the return value of the `tokens add` command consistent else we run the risk of breaking scripts. 

### Workaround
`sudo tctl tokens add --type=node | grep -oP '(?<=token:\s).*' > token.file`

**Comment by russjones** [comment]
Let's do `--format=token` to only show the token then it becomes easier to consume by scripts. We should also remove the period so it's easier to double click and actually get the token.

**Comment by zmb3** [comment]
Looks like this was added in #12327:

```
❯ tctl tokens add --format=text --type=node
b5bee4dceb645f56e91c5818f5a35f5b
```
