### ISSUE TITLE
Ability to list all automation certs issued with `tctl auth sign` and revoke individually as needed

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#9988]
### What
Admins sometime issue certs with `tctl auth sign` that they would then like to revoke after the fact without necessarily locking the user out completely via session locking. It would be good to have the ability to run commands such as `tctl auth ls` and pair it with something like a `--revoke` flag to then revoke previously issued identity certs without placing a lock on a user level.

**Comment by roobeshm** [comment]
interested to see this feature live.

**Comment by zmb3** [comment]
I'm going to close this for now, as there are no plans to track issued certificates or implement certificate revocation at this time.
