### ISSUE TITLE
Feature request - 'view only' session sharing

### ISSUE THREAD

**Issue by bcg62** [gravitational/teleport#999]
when using IDM for user authentication with role templates where each user has their own login, the current shared login concepts no longer seem correct.

Following #924 each user should only be able to see their own recorded sessions. They do not have permission to login as other users and as such should not be able to see their recorded content, sensitive information could be exposed leading to a violation of RBAC where a user obtains information outside of their access level.

Additionally, when each user has their own unique login session sharing is not possible. There should be a mechanism where a user can chose to share their current session with other users who can only watch rather than participate. This would be extremely useful for training, presenting, information sharing etc.

**Comment by kontsevoy** [comment]
@bcg62 Teleport 2.3 is coming out next week. It has much more granular RBAC rules, and they include session restrictions. While you cannot do read-only sessions just yet, you can turn off session access for groups of people.

**Comment by eldios** [comment]
This is now possible through RBAC. Closing.

**Comment by klizhentas** [comment]
I don't think we have this option on a per-user granual level

**Comment by kontsevoy** [comment]
I just tried and it appears that session sharing DISAPPEARED from 4.x release. There's simply no option to do it in the web UI. 

Marking this as a "bug" and upgrading to 4.1

**Comment by kontsevoy** [comment]
@klizhentas let's not over-complicate things. For non-privileged users they should not be allowed to "hide" their session (perhaps their superiors must always have the option to override what they're doing). If we're adding a per-session key, then there needs to be another RBAC rule to allow/disallow users to do this.

I propose we close this.

**Comment by zmb3** [comment]
Going to close this one, given it's been inactive for a couple years.

The good news is in this time we've added RBAC for sessions and moderated sessions, which allows view-only participants, covering both of the requests here.
